
[#live-export]
=== Manuellen Export in Katalog starten

Du hast mindestens ein Datenfeld für den Export hinzugefügt? Dann kannst du einen manuellen Export des Katalogs starten. Sobald der Export abgeschlossen ist, kannst du die Exportdatei über die Notifications herunterladen.

In welchem Format die Daten exportiert werden, legst du in den Formateinstellungen des Katalogs fest. Du kannst Daten in den Formaten CSV, TXT, JSON und XML herunterladen.

[tabs]
====
Manuellen Export im Katalog starten::
+
--

. Öffne das Menü *Daten » Kataloge*. +
→ Die Katalog-Übersicht wird geöffnet.
. Öffne den Katalog.
. Klicke in der Symbolleiste oben auf *Daten herunterladen* (material:file_download[]). +
→ Der Export wird gestartet. +
*_Wichtig:_* Der Export läuft im Hintergrund. Es wird _kein_ Fenster angezeigt, über das du die Datei sofort herunterladen kannst. Auch der Export kleiner Datenmengen dauert ca. 30 Minuten. +
→ Wenn der Export abgeschlossen ist, wirst in den Notifications (material:notifications_none[]) angezeigt, dass die Exportdatei heruntergeladen werden kann.
. Klicke im Notification Center auf material:link[] *Herunterladen*. +
*_Tipp:_* Die Notification wird nicht mehr angezeigt? Die Datei kann immer über die URL in den *Download-Einstellungen* abgerufen werden.
. Speichere die Datei auf deinem Rechner.

--
 
Manuellen Export in Katalogübersicht starten::
+
--

. Öffne das Menü *Daten » Kataloge*. +
→ Die Katalog-Übersicht wird geöffnet.
. Klicke in der Zeile des Katalogs auf die weiteren Aktionen (material:more_vert[]).
. Klicke auf *Daten herunterladen* (material:file_download[]). +
→ Der Export wird gestartet. +
*_Wichtig:_* Der Export läuft im Hintergrund. Es wird _kein_ Fenster angezeigt, über das du die Datei sofort herunterladen kannst. Auch der Export kleiner Datenmengen dauert ca. 30 Minuten. +
→ Wenn der Export abgeschlossen ist, wirst in den Notifications (material:notifications_none[]) angezeigt, dass die Exportdatei heruntergeladen werden kann.
. Klicke im Notification Center auf material:link[] *Herunterladen*. +
*_Tipp:_* Die Notification wird nicht mehr angezeigt? Die Datei kann immer über die URL in den *Download-Einstellungen* abgerufen werden.
. Speichere die Datei auf deinem Rechner.
--
====
