:author: team-plenty-channel

Lerne, wie du vorhandene Kataloge verwaltest. Diese Informationen gelten für Marktplatz-Formate und für Standardformate.

[#catalogue-rights]
== Rechte für Backend-Benutzer:innen vergeben

:rights-purpose: Kataloge sehen können
:right-one: pass:quotes[*Daten > Datenaustausch > Export > Katalog > Anzeigen*]

include::_includes:partial$rights.adoc[]

[#15]
== Spalten der Katalog-Übersicht anpassen

Du kannst selbst entscheiden, welche Informationen in den Tabellenspalten angezeigt werden. Gehe dafür folgendermaßen vor:

[.instruction]
Spalten der Katalog-Übersicht anpassen:

. Öffne das Menü *Daten » Kataloge*. +
→ Die Katalog-Übersicht wird geöffnet.
. Klicke oben rechts auf *Spalten konfigurieren* (material:settings[]). +
→ Das Fenster *Spalten konfigurieren* wird geöffnet.
. Wähle, welche Spalten angezeigt werden sollen.
. Verschiebe (material:sort[]) die Spalten, sodass sie in der gewünschten Reihenfolge angezeigt werden.
. Klicke auf *Bestätigen*, um deine Einstellungen zu speichern.

[#190]
== Kataloge kopieren

Du möchtest einen gut konfigurierten Katalog nutzen, um schnell einen neuen Katalog zu erstellen? Geht!
Beim Kopieren werden zugeordnete Datenfelder übernommen - auch, wenn du das Format wechselst. Du kannst sogar eine andere Sprache für die Kopie wählen.

[tabs]
====
Einen Katalog kopieren::
+
--
[.instruction]
Katalog kopieren:

. Öffne das Menü *Daten » Kataloge*. +
→ Die Katalog-Übersicht wird geöffnet.
. Navigiere in die Zeile des Katalogs.
. Klicke auf die weiteren Aktionen (material:more_vert[]).
. Klicke auf *Kopieren* (material:content_copy[]). +
*_Oder_*: Hake den Katalog an, den du kopieren möchtest.
. Klicke oben in der Katalog-Übersicht auf *Kataloge kopieren* (material:content_copy[]). +
→ Ein Fenster wird geöffnet.
. Wenn gewünscht, passe den automatisch vergebenen Namen für die Kopie an.
. *_Optional:_* Wähle ein anderes Format aus der Dropdown-Liste. Bereits zugeordnete Datenfelder werden dabei übernommen.
. *_Optional:_* Wähle eine andere Sprache aus der Dropdown-Liste.
. Klicke auf *Kopieren*. +
→ Der Katalog wird kopiert und in der Katalog-Übersicht angezeigt.

--

Mehrere Kataloge kopieren::
+
--
Du kannst auch mehrere Kataloge gleichzeitig kopieren. Allerdings ist es in diesem Fall nicht möglich, eine Formatänderung an den Katalogen vorzunehmen oder eine andere Sprache zu wählen.

[.instruction]
Mehrere Kataloge kopieren:

. Öffne das Menü *Daten » Kataloge*. +
→ Die Katalog-Übersicht wird geöffnet.
. Wähle die Kataloge, die du kopieren möchtest.
. Klicke auf *Kataloge kopieren* (material:content_copy[]). +
→ Alle gewählten Kataloge werden kopiert und in der Katalog-Übersicht angezeigt. +
. *_Optional:_* Um die automatisch vergebenen Namen für die kopierten Kataloge zu ändern, öffne die Kataloge einzeln und passe den Namen in den Grundeinstellungen an.

--
====

[#210]
== Kataloge löschen

Du kannst einen Katalog oder mehrere Kataloge gleichzeitig löschen.

[tabs]
====
Einen Katalog löschen::
+
--
[.instruction]
Einen Katalog löschen:

//tag::delete-catalogue[]
. Öffne das Menü *Daten » Kataloge*. +
→ Die Katalog-Übersicht wird geöffnet.
. Navigiere in die Zeile des Katalogs, den du löschen möchtest.
. Klicke auf die weiteren Aktionen (material:more_vert[]).
. Klicke auf *Löschen* (material:delete[]). +
→ Eine Sicherheitsabfrage wird eingeblendet.
. Bestätige den Löschvorgang. +
→ Der Katalog wird gelöscht. +
*_Oder_*: Öffne einen Katalog.
. Klicke oben auf die weiteren Aktionen (material:more_vert[]).
. Klicke auf *Katalog löschen* (material:delete[]). +
→ Eine Sicherheitsabfrage wird eingeblendet.
. Bestätige den Löschvorgang. +
→ Der Katalog wird gelöscht.
//end::delete-catalogue[]
--

Mehrere Kataloge löschen::
+
--
Gehe wie unten beschrieben vor, um mehrere Kataloge gleichzeitig zu löschen.

[.instruction]
Mehrere Kataloge löschen:

. Öffne das Menü *Daten » Kataloge*. +
→ Die Katalog-Übersicht wird geöffnet.
. Wähle die Kataloge, die du löschen möchtest.
. Klicke oben rechts auf *Ausgewählte Kataloge löschen* (material:delete[]). +
→ Eine Sicherheitsabfrage wird eingeblendet.
. Bestätige den Löschvorgang. +
→ Die Kataloge werden gelöscht.

--
====

[#250]
== Andere Katalog-Version wiederherstellen

Über die weiteren Aktionen und auch in der Ansicht eines Katalogs kannst du vorherige Versionen eines Katalogs wiederherstellen. Die letzten 100 Versionen des Katalogs sind verfügbar.

[.instruction]
Katalog-Version wiederherstellen:

//tag::reset-catalogue[]
. Öffne das Menü *Daten » Kataloge*. +
→ Die Katalog-Übersicht wird geöffnet.
. Navigiere in die Zeile des Katalogs.
. *_Möglichkeit 1:_* In der Katalogübersicht
  .. Öffne die weiteren Aktionen (material:more_vert[]).
  .. Klicke auf *Katalog-Version wiederherstellen* (material:history[]). +
. *_Möglichkeit 2:_* Im Katalogmenü
  .. Öffne den Katalog.
  .. Klicke in der Symbolleiste auf die weiteren Aktionen (icon:ellipsis-v[]).
  .. Klicke auf *Katalog-Version wiederherstellen* (material:history[]).
. Wähle im angezeigten Fenster die Version, die du wiederherstellen möchtest. +
*_Tipp:_* Die letzten 100 Versionen des Katalogs sind verfügbar.
. Klicke auf *Wiederherstellen*. +
→ Die Version des Katalogs wird wiederhergestellt und in der Übersicht angezeigt.
//end::reset-catalogue[]

[#240]
== Gelöschten Katalog wiederherstellen

In der Katalog-Übersicht stellst du den letzten Stand eines gelöschten Katalogs wieder her.

[.instruction]
Gelöschten Katalog wiederherstellen:

. Öffne das Menü *Daten » Kataloge*. +
→ Die Katalog-Übersicht wird geöffnet.
. Klicke auf *Gelöschten Katalog wiederherstellen* (material:undo[role="orange"]). +
→ Ein Fenster wird geöffnet.
. Wähle einen Katalog aus der Dropdown-Liste.
. Klicke auf *Wiederherstellen*. +
→ Der Katalog wird wiederhergestellt und in der Übersicht angezeigt.

[#270]
== Kataloge exportieren

Exportiere Kataloge, um sie anschließend in andere plentymarkets Systeme importieren zu können. Gleichzeitig dient der Export als Daten-Backup.

TIP: Mit diesen Einstellungen exportierst du den Katalog selbst. Du exportierst also die Informationen, welche Datenfelder der Katalog enthält, und nicht die Daten, die für diese Datenfelder in plentymarkets gespeichert sind.

[.instruction]
Kataloge exportieren:

. Öffne das Menü *Daten » Kataloge*. +
→ Die Katalog-Übersicht wird geöffnet.
. Setze ein Häkchen für den Katalog, den du exportieren möchtest. Du kannst auch mehrere Kataloge auf einmal wählen.
. Klicke oben auf *Katalog exportieren* (material:file_download[]). +
→ Ein Fenster wird geöffnet.
. Wähle einen Speicherort. +
→ Die gewählten Kataloge werden exportiert und an dem gewünschten Ort gespeichert.

[#280]
== Kataloge importieren

Nutze die Importfunktion, um Kataloge aus anderen plentymarkets Systemen oder zuvor als Backup gesicherte Kataloge wieder zu importieren.

TIP: Mit diesen Einstellungen importierst du den Katalog selbst. Du importierst also die Informationen, welche Datenfelder der Katalog enthält, und nicht die Daten, die für diese Datenfelder in plentymarkets gespeichert sind.

[.instruction]
Kataloge importieren:

. Öffne das Menü *Daten » Kataloge*. +
→ Die Katalog-Übersicht wird geöffnet.
. Klicke oben auf *Katalog importieren* (material:file_upload[]). +
→ Ein Fenster wird geöffnet.
. Wähle die Katalog-Datei, die du importieren möchtest. +
*_Wichtig:_* Du kannst immer nur einen Katalog importieren. +
→ Der Katalog wird importiert und in der Übersicht angezeigt. +
→ Der Name des importierten Kataloges enthält den Zusatz `(1)`. +
Stammt der Katalog aus einem anderen System, wird der Name beibehalten.
