:author: team-plenty-channel

Wenn du in den Importeinstellungen ein Intervall festgelegt hast, wird die Datei automatisch regelmäßig importiert. Du kannst den Import aber auch jederzeit manuell starten.

//tag::single-import[]
Du hast zwei Möglichkeiten, die Datei zu importieren:

[cols="1,3a"]
|===
| Import (material:play_circle_outline[role="blue"])
| Der Import läuft im Hintergrund.

* *_Vorteil:_* Du kannst auch große Datenmengen importieren. +
* *_Nachteil:_* Du kannst den Fortschritt nicht live verfolgen.

| Live-Import (material:play_circle[role="blue"])
| Der Import wird sofort gestartet. Der Fortschritt wird live angezeigt.

* *_Vorteile:_*
  ** Du kannst den Fortschritt des Import in Echtzeit verfolgen.
  ** Ergebnis und Fehler des Imports werden direkt unter dem Fortschrittsbalken angezeigt.
* *_Nachteil:_*
  ** Bei großen Datenmengen kann es zu einer Zeitüberschreitung kommen. Der Import wird dann abgebrochen. Verwende in diesem Fall stattdessen den Import im Hintergrund.

|===

[tabs]
====
Import starten::
+
--

//tag::async-import[]
Der Import läuft im Hintergrund.

[.instruction]
Import starten:

. Öffne das Menü *Daten » Import » [Import öffnen]*.
. Klicke in der Symbolleiste auf *Import ausführen* (material:play_circle_outline[role="blue"]). +
*_Tipp:_* Noch schneller geht es, wenn du in der Importübersicht in der Zeile des Imports auf *Import ausführen* (icon:play-circle[role="grey"]) klickst. +
→ Die Daten werden importiert. +
*_Wichtig:_* Der Import läuft im Hintergrund.
. Öffne das Menü, in das die Daten importiert wurden.
. Prüfe, ob die Daten wie erwartet importiert wurden.

//end::async-import[]

--
 
Live-Import starten::
+
--

//tag::live-import[]
Beim Live-Import kannst du den Fortschritt des Import in Echtzeit im Tab *Datenimport* verfolgen.

*_Wichtig:_*

* Wenn du den Live-Import startest, wird ein neues Browser-Tab geöffnet. In diesem Browser-Tab wird das plentymarkets Tab *Datenimport* angezeigt.
* Wenn du das Browser-Tab oder das plentymarkets Tab *Datenimport* schließt, während der Import läuft, wird der Import angehalten. Du kannst den Import über das Menü *Daten » Status* fortsetzen.
* Bei großen Datenmengen kann es zu einer Zeitüberschreitung kommen. Der Import wird dann abgebrochen. Verwende in diesem Fall stattdessen den Import im Hintergrund.

[.instruction]
Live-Import starten:

. Öffne das Menü *Daten » Import » [Import öffnen]*.
. Klicke in der Symbolleiste auf *Live-Import ausführen* (material:play_circle[role="blue"]). +
*_Tipp:_* Noch schneller geht es, wenn du in der Importübersicht in der Zeile des Imports auf *Live-Import ausführen* (material:play_circle_outline[role="grey"]) klickst. +
→ Ein neues Browser-Tab wird geöffnet. plentymarkets und das Tab *Datenimport* werden angezeigt. +
*_Kein neues Tab?_* Dann hast du wahrscheinlich einen Pop-up-Blocker im Einsatz. Erlaube Pop-ups für dein System und es kann losgehen. +
→ Die Daten werden importiert. +
*_Wichtig:_* Wenn du das Browser-Tab oder das plentymarkets Tab *Datenimport* schließt, während der Import läuft, wird der Import angehalten. Du kannst den Import über das Menü *Daten » Status* fortsetzen. +
→ Der Fortschritt wird in Echtzeit angezeigt. +
. Öffne das Menü, in das die Daten importiert wurden.
. Prüfe, ob die Daten wie erwartet importiert wurden.
//end::live-import[]
--
====
//end::single-import[]
