:author: team-plenty-channel

Wenn du in den Importeinstellungen ein Intervall festgelegt hast, wird die Datei automatisch regelmäßig importiert. Du kannst den Import aber auch jederzeit manuell starten.

//tag::single-import[]
Du hast zwei Möglichkeiten, die Datei zu importieren:

[cols="1,3a"]
|===
| Asynchroner Import
| Der Import läuft im Hintergrund.

* *_Vorteil:_* Du kannst auch große Datenmengen importieren. +
* *_Nachteil:_* Du kannst den Fortschritt nicht live verfolgen.

| Live-Import
| Der Import wird live angezeigt.

* *_Vorteil:_* Du kannst den Fortschritt des Import in Echtzeit verfolgen.
* *_Nachteile:_*
  ** Bei großen Datenmengen kann es zu einer Zeitüberschreitung kommen. Der Import wird dann abgebrochen. Verwende in diesem Fall stattdessen den asynchronen Import.
  ** Das Browser-Tab und das plentymarkets Tab *Datenimport* dürfen nicht geschlossen oder neu geladen werden, während der Import läuft. Wenn du es doch tust, wird der Import gestoppt.

|===

[tabs]
====
Asynchronen Import starten::
+
--

//tag::async-import[]
Beim asynchronen Import läuft der Import im Hintergrund.

[.instruction]
Asynchronen Import starten:

. Öffne das Menü *Daten » Import » [Import öffnen]*.
. Klicke in der Symbolleiste auf *Import ausführen* (icon:play-circle[role="grey"]). +
*_Tipp:_* Noch schneller geht es, wenn du in der Zeile des Imports in der Importübersicht auf *Import ausführen* (icon:play-circle[role="grey"]) klickst. +
→ Die Daten werden importiert. +
*_Wichtig:_* Der Import läuft im Hintergrund.
. Öffne das Menü, in das die Daten importiert wurden.
. Prüfe, ob die Daten wie erwartet importiert wurden.

//end::async-import[]

--
 
Live-Import starten::
+
--

//tag::live-import[]
Beim Live-Import kannst du den Fortschritt des Import in Echtzeit im Tab *Datenimport* verfolgen.

*_Wichtig:_*

* Wenn du den Live-Import startest, wird ein neues Browser-Tab geöffnet. In diesem Browser-Tab wird das plentymarkets Tab *Datenimport* angezeigt. Während der Import läuft, dürfen das Browser-Tab und das plentymarkets Tab *Datenimport* nicht geschlossen oder neu geladen werden. Wenn du es doch tust, wird der Import angehalten.
* Bei großen Datenmengen kann es zu einer Zeitüberschreitung kommen. Der Import wird dann abgebrochen. Verwende in diesem Fall stattdessen den asynchronen Import.

[.instruction]
Live-Import starten:

. Öffne das Menü *Daten » Import » [Import öffnen]*.
. Klicke in der Symbolleiste auf *Live-Import ausführen* (icon:play-circle[role="grey"]). +
→ Ein neues Browser-Tab wird geöffnet. plentymarkets und das Tab *Datenimport* werden angezeigt. +
*_Kein neues Tab?_* Dann hast du wahrscheinlich einen Pop-up-Blocker im Einsatz. Erlaube Pop-ups für dein System und es kann losgehen. +
→ Die Daten werden importiert. +
*_Wichtig:_* Das Browser-Tab und das plentymarkets Tab *Datenimport* dürfen nicht geschlossen oder neu geladen werden, während der Import läuft. Wenn du es doch tust, wird der Import angehalten. +
→ Der Fortschritt wird in Echtzeit angezeigt. +
. Öffne das Menü, in das die Daten importiert wurden.
. Prüfe, ob die Daten wie erwartet importiert wurden.
//end::live-import[]
--
====
//end::single-import[]
