[#1700]
== Grundeinrichtung: Datenimport mit Assistenten durchführen

Du möchtest Kontakt- oder Artikeldaten importieren und fragst dich, wie du das in deinem plentymarkets System am schnellsten tun kannst? Dann verwende die dafür vorgesehenen Assistenten. Mit diesen Assistenten erstellst du Schritt für Schritt eine Imporvorlage. Du kannst also genau festlegen, welche Daten importiert werden sollen. Im Anschluss kannst du mit einem weiteren Assistenten deine mit Daten gefüllte Importvorlage direkt hochladen und den Import ausführen.

[#1800]
=== Assistent "Kontaktdatenimport" durchlaufen

Für den Import von Kontaktdaten steht dir neben dem Import-Tool der Kontaktdatenimport-Assistent zur Verfügung. Dieser Assistent hilft dir dabei, eine auf deine Bedürfnisse zugeschnittene Importvorlage zu erstellen. Diese Vorlage kannst du anschließend herunterladen und mit deinen Daten befüllen.

Du findest den Assistenten *Kontaktdatenimport* im Menü *Einrichtung » Assistenten » Grundeinrichtung*. In diesem Assistenten nimmst du die folgenden Einstellungen vor:

* Du wählst den Namen des Imports, der später im System angezeigt werden soll.
* Du wählst, welche Kontaktdaten, Adressdaten und Firmendaten du importieren möchtest.
* Du wählst, welche Kontakte und Kontaktoptionen du importieren möchtest.
* Du wählst, welche Adressen du importieren möchtest.
* Du lädst die Importvorlage als CSV-Datei herunter. Ergänze deine Daten in dieser Datei. Beachte, dass die ersten 3 Zeilen der Datei nicht geändert werden dürfen.

Um deine Kontaktdaten zu importieren, kannst du den Assistenten <<#1200, Daten hochladen>> verwenden. Alternativ kannst du die Importdatei auch im Menü *Daten » Import* manuell hochladen.

[#1900]
=== Assistent "Artikelimport" durchlaufen

Für den Import von Artikeldaten steht dir neben dem Import-Tool der Assistent *Artikelimport* zur Verfügung. Dieser Assistent hilft dir dabei, eine auf deine Bedürfnisse zugeschnittene Importvorlage zu erstellen. Diese Vorlage kannst du anschließend herunterladen und mit deinen Daten befüllen.

Du findest den Assistenten *Artikelimport* im Menü *Einrichtung » Assistenten » Grundeinrichtung*. In diesem Assistenten nimmst du die folgenden Einstellungen vor:

* Du wählst den Namen des Imports, der später im System angezeigt werden soll.
* Du wählst, welche Artikeldaten du importieren möchtest.
* Du wählst, welche Verkaufspreise du importieren möchtest und legst deren Formatierung fest.
* Du lädst die Importvorlage als CSV-Datei herunter. Ergänze deine Daten in dieser Datei. Beachte, dass die ersten 3 Zeilen der Datei nicht geändert werden dürfen.

Um deine Artikeldaten zu importieren, kannst du den Assistenten <<#1200, Daten hochladen>> verwenden. Alternativ kannst du die Importdatei auch im Menü *Daten » Import* manuell hochladen.

[#1200]
=== Assistent "Daten hochladen" durchlaufen

Den Assistenten *Daten hochladen* kannst du verwenden, um eine mit deinen Daten gefüllte Importvorlage hochzuladen und den Import direkt auszuführen.

Du findest den Assistent *Daten hochladen* im Menü *Einrichtung » Assistenten » Grundeinrichtung*. In diesem Assistenten nimmst du die folgenden Einstellungen vor:

* Du lädst die mit deinen Daten gefüllte Importvorlage hoch. +
*_Hinweis_*: Falls du noch keine Importvorlage hast, erstelle die Vorlage über den Import-Assistenten.
* Du führst den Import aus. Hier kannst du bestimmen, ob du den Import direkt ausführen möchtest, wenn du den Assistenten abschließt. Alternativ kannst du den Import auch im Menü *Daten » Import* starten.

Anschließend kannst du den über den Assistenten erstellten Import in der Übersicht im Menü *Daten » Import* sehen. Ein Abgleich ist hier nicht vorhanden, da es sich um neue Daten handelt. Im Tab *Zuordnung* des Imports wurden bereits alle Felder deiner CSV-Datei automatisch den plentymarkets Datenfeldern zugewiesen.
