If you want to use the plentyWarehouse app to manage the processes in your warehouse, all you need is a mobile device with an Android operating system. A regular smartphone might be sufficient for trying out the app. However, we recommend using professional devices with integrated barcode scanners for everyday tasks in bigger warehouses. <<table-requirements-plentywarehouse>> contains a list of so-called MDC devices that we recommend for using the plentyWarehouse app.

[IMPORTANT]
.Note Android minimum version
====
No matter if you want to use the plentyWarehouse app on a smartphone or on the hardware listed below: *version 7.0 or higher of the Android operating system* needs to be installed on your app. We reserve the right to increase this minimum requirement on a yearly basis in order to guarantee compatibility with Android.
====

[[table-requirements-plentywarehouse]]
.Managing stock with the plentyWarehouse app
[cols="1,3"]
|====
|Hardware |Where to buy in Germany

|M3 SM15 Mobile Computer
|link:https://www.sundsits.de/produkt/m3-sm15-mobile-computer-wifi-und-lte/[View SundS ITS offer^] +

SundS ITS +
Beselerstr. 2-6 +
50354 Hürth, Germany +
info@sundsits.de +
Phone: +49(0)2233-7064010 +
Fax: +49(0)2233-7064011 +
link:https://www.sundsits.de[www.sundsits.de^]

|Zebra TC 21
|link:https://www.sundsits.de/produkt/zebra-tc21/[View SundS ITS offer^] +

SundS ITS +
Beselerstr. 2-6 +
50354 Hürth, Germany +
info@sundsits.de +
Phone: +49(0)2233-7064010 +
Fax: +49(0)2233-7064011 +
link:https://www.sundsits.de[www.sundsits.de^]

|Zebra TC 26
|link:https://www.sundsits.de/produkt/zebra-tc26/[View SundS ITS offer^] +

SundS ITS +
Beselerstr. 2-6 +
50354 Hürth, Germany +
info@sundsits.de +
Phone: +49(0)2233-7064010 +
Fax: +49(0)2233-7064011 +
link:https://www.sundsits.de[www.sundsits.de^]

|====
