Learn how to manage existing catalogues. This information applies to both marketplace and default formats.

[#catalogue-rights]
== Assigning rights for back end users

:rights-purpose: see catalogues
:right-one: pass:quotes[*Data > Data exchange > Export > Catalogue > Show*]

include::_includes:partial$rights.adoc[]

[#15]
== Customizing catalogue overview columns

You can customize the information that is displayed in the table columns. To do so, proceed as follows:

[.instruction]
Customizing catalogue overview columns:

. Go to *Data » Catalogues*. +
→ The catalogue overview opens.
. At the top right, click on *Configure columns* (material:settings[]). +
→ The window *Configure columns* opens.
. Select which columns you want to be displayed.
. Move (material:sort[]) the columns so they are displayed in the desired order.
. Click on *Confirm* to save your settings.

[#190]
== Copying catalogues

Do you want to quickly create new catalogues based on well configures ones that you already use? No problem!
Any data fields that you have already mapped are copied, even if you select a different format. You can also select a different language for the copy.

[tabs]
====
Coping one catalogue::
+
--
[.instruction]
Coping a catalogue:

. Go to *Data » Catalogues*. +
→ The catalogue overview opens.
. In the row of the catalogue, click on the further actions (material:more_vert[]).
. Click on *Copy* (material:content_copy[]). +
*_Or_*: Tick the box of the catalogue that you want to copy.
. At the top in the catalogue overview click on *Copy catalogue* (material:content_copy[]). +
→ A window opens.
. If desired, adjust the automatically created name for the copy.
. *_Optional:_* Select another format from the drop-down list. Data fields that have already been mapped will be transferred.
. *_Optional:_* Select another language from the drop-down list.
. Click on *Copy*. +
→ The catalogue is copied and displayed in the catalogue overview.

--

Copying multiple catalogues::
+
--
You can also copy several catalogues at once. However, in this case you cannot change the format or language of the catalogues.

[.instruction]
Copying several catalogues:

. Go to *Data » Catalogues*. +
→ The catalogue overview opens.
. Select the catalogues that you want to copy.
. Click on *Copy catalogue* (material:content_copy[]). +
→ All selected catalogues are copied and displayed in the catalogue overview. +
. *_Optional:_* If you want to edit the automatically created names of the copied catalogues, open the catalogues individually and adjust the name in the basic settings.

--
====

[#210]
== Deleting catalogues

You can delete one catalogue or multiple catalogues at the same time.

[tabs]
====
Deleting one catalogue::
+
--
[.instruction]
Deleting one catalogue:

//tag::delete-catalogue[]
. Go to *Data » Catalogues*. +
→ The catalogue overview opens.
. In the row of the catalogue that you want to delete, click on the further actions (material:more_vert[]).
. Click on *Delete* (material:delete[]). +
→ You are asked to confirm your decision.
. Confirm the deletion. +
→ The catalogue is deleted. +
*_Or_*: Open a catalogue.
. Click on the further actions (material:more_vert[]) at the top.
. Click on *Delete catalogue* (material:delete[]). +
→ You are asked to confirm your decision.
. Confirm the deletion. +
→ The catalogue is deleted.
//end::delete-catalogue[]
--

Deleting multiple catalogues::
+
--
Proceed as follows in order to delete several catalogues at once.

[.instruction]
Deleting several catalogues:

. Go to *Data » Catalogues*. +
→ The catalogue overview opens.
. Select the catalogues that you want to delete.
. At the top right, click on *Delete selected catalogues* (material:delete[]). +
→ You are asked to confirm your decision.
. Confirm the deletion. +
→ The catalogues are deleted.

--
====

[#250]
== Restoring another catalogue version

You can restore a previous catalogue version via the further actions or in the view of a catalogue. The last 100 versions of the catalogue are available.

[.instruction]
Restoring a catalogue version:

//tag::reset-catalogue[]
. Go to *Data » Catalogues*. +
→ The catalogue overview opens.
. *_Alternative 1:_* In the catalogue overview
  .. In the row of the catalogue, open the further actions (material:more_vert[]).
  .. Click on *Restore catalogue version* (material:history[]). +
. *_Alternative 2:_* In the catalogue menu
  .. Open the catalogue.
  .. In the toolbar, click on the additional actions (icon:ellipsis-v[]).
  .. Click on *Restore catalogue version* (material:history[]).
. In the window shown, select the version that you want to restore. +
*_Tip:_* The last 100 versions of the catalogue are available.
. Click on *Restore*. +
→ The catalogue version is restored and displayed in the catalogue overview.
//end::reset-catalogue[]

[#240]
== Restoring a deleted catalogue

In the catalogue overview, you can restore the last version of a deleted catalogue.

[.instruction]
Restoring a deleted catalogue:

. Go to *Data » Catalogues*. +
→ The catalogue overview opens.
. Click on *Restore deleted catalogue* (material:undo[role="orange"]). +
→ A window opens.
. Select a catalogue from the drop-down list.
. Click on *Restore*. +
→ The catalogue is restored and displayed in the catalogue overview.

[#270]
== Exporting catalogues

Export catalogues to import them into other plentymarkets systems afterwards. At the same time, an export also serves as a backup.

TIP: These settings export the catalogue itself. As such, the import contains information on the settings and data fields the catalogue contains. The import cannot be used to import data for plentymarkets data fields.

[.instruction]
Exporting catalogues:

. Go to *Data » Catalogues*. +
→ The catalogue overview opens.
. Place a check mark for the catalogue that you want to export. You can also select several catalogues at once.
. At the top, click on *Export catalogue* (material:file_download[]). +
→ A window opens.
. Select a storage location. +
→ The selected catalogues are exported and saved at the desired location.

[#280]
== Importing catalogues

Use the import function to import catalogues from other plentymarkets systems or catalogues that have been saved as backup beforehand.

TIP: These settings import the catalogue itself. As such, the import contains information on the settings and data fields the catalogue contains and not the data that is saved for these data fields in plentymarkets.

[.instruction]
Importing catalogues:

. Go to *Data » Catalogues*. +
→ The catalogue overview opens.
. At the top, click on *Import catalogue* (material:file_upload[]). +
→ A window opens.
. Select the catalogue file that you want to import. +
*_Important:_* You can only import one catalogue at a time. +
→ The catalogue is imported and displayed in the overview. +
→ The name of the imported catalogue contains the addition `(1)`. +
If the catalogue originates from another system, the name stays the same.
