:author: team-plenty-channel

If you specified an interval in the import settings, the file is regularly imported automatically. However, you can also start an import manually at any time.

//tag::single-import[]
There are two ways to import the file:

[cols="1,3a"]
|===
| Import (material:play_circle_outline[role="blue"])
| The import runs in the background.

* *_Advantage:_* You can import large amounts of data. +
* *_Disadvantage:_* You cannot track the progress live.

| Live import (material:play_circle[role="blue"])
| The import starts immediately. The progress is shown in real time.

* *_Advantages:_*
  ** You can follow the import progress in real time.
  ** Results and any errors are shown directly underneath the progress bar.
* *_Disadvantage:_*
  ** The import can run into a timeout if you try to import large amounts of data. If that happens, the import is cancelled. In such cases, use the background import instead.

|===

[tabs]
====
Starting an import::
+
--

//tag::async-import[]
The import runs in the background.

[.instruction]
Starting an import:

. Go to *Data » Import » [Open import]*.
. In the toolbar, click on *Run import* (material:play_circle_outline[role="blue"]). +
*_Tip:_* Even quicker: In the import overview, find the import. On the right, click on *Run import* (icon:play-circle[role="grey"]). +
→ The data is imported. +
*_Important:_* The import runs in the background.
. Open the menu that the data was imported to.
. Check if the data was imported as expected.

//end::async-import[]

--
 
Starting a live import::
+
--

//tag::live-import[]
The live import allows you to see the import progress in real time in the tab *Data import*.

*_Important:_*

* When you start the live import, a new browser tab opens. In this browser tab, the plentymarkets tab *Data import* is shown.
* The import stops if you close the browser tab or the plentymarkets tab *Data import* while the import is in progress. Go to *Data » Status* to resume the import.
* The import can run into a timeout if you try to import large amounts of data. If that happens, the import is cancelled. In such cases, use the background import instead.

[.instruction]
Starting a live import:

. Go to *Data » Import » [Open import]*.
. In the toolbar, click on *Run live import* (material:play_circle[role="blue"]). +
*_Tip:_* Even quicker: In the import overview, find the import. On the right, click on *Run live import* (material:play_circle_outline[role="grey"]). +
→ a new browser tab opens. plentymarkets and the tab *Data import* are shown. +
*_No new tab?_* Then you are probably using a pop-up blocker. Allow pop-ups for your system to continue. +
→ The data is imported. +
*_Important:_* The import stops if you close the browser tab or the plentymarkets tab *Data import* while the import is in progress. Go to *Data » Status* to resume the import. +
→ The progress is shown in real time. +
. Open the menu that the data was imported to.
. Check if the data was imported as expected.
//end::live-import[]
--
====
//end::single-import[]
