:author: team-plenty-channel

If you specified an interval in the import settings, the file is regularly imported automatically. However, you can also start an import manually at any time.

//tag::single-import[]
There are two ways to import the file:

[cols="1,3a"]
|===
| Asynchronous import
| The import runs in the background.

* *_Advantage:_* You can import large amounts of data. +
* *_Disadvantage:_* You cannot track the progress live.

| Live import
| The import progress is shown in real time.

* *_Advantage:_* You can follow the import progress in real time.
* *_Disadvantages:_*
  ** The import can run into a timeout if you try to import large amounts of data. If that happens, the import is cancelled. In such cases, use the asynchronous import instead.
  ** Do not close or reload the browser tab or the plentymarkets tab *Data import* while the import is in progress. If you do so, the import will be cancelled.

|===

[tabs]
====
Starting an asynchronous import::
+
--

//tag::async-import[]
For asynchronous imports, the import runs in the background.

[.instruction]
Starting an asynchronous import:

. Go to *Data » Import » [Open import]*.
. In the toolbar, click on *Run import* (icon:play-circle[role="grey"]). +
*_Tip:_* Even quicker: In the import overview, find the row of the import and click on *Run import* (icon:play-circle[role="grey"]). +
→ The data is imported. +
*_Important:_* The import runs in the background.
. Open the menu that the data was imported to.
. Check if the data was imported as expected.

//end::async-import[]

--
 
Starting a live import::
+
--

//tag::live-import[]
The live import allows you to see the import progress in real time in the tab *Data import*.

*_Important:_*

* When you start the live import, a new browser tab opens. In this browser tab, the plentymarkets tab *Data import* is shown. Do not close or reload the browser tab and the plentymarkets tab *Data import* while the import is in progress. If you do, the import stops and is cancelled.
* The import can run into a timeout if you try to import large amounts of data. If that happens, the import is cancelled. In such cases, use the asynchronous import instead.

[.instruction]
Starting a live import:

. Go to *Data » Import » [Open import]*.
. In the toolbar, click on *Run live import* (icon:play-circle[role="grey"]). +
→ a new browser tab opens. plentymarkets and the tab *Data import* are shown. +
*_No new tab?_* Then you are probably using a pop-up blocker. Allow pop-ups for your system to continue. +
→ The data is imported. +
*_Important:_* Do not close or reload the browser tab or the plentymarkets tab *Data import* while the export is in progress. If you do, the import stops and is cancelled. +
→ The progress is shown in real time. +
. Open the menu that the data was imported to.
. Check if the data was imported as expected.
//end::live-import[]
--
====
//end::single-import[]
