= Shopify-App einrichten
:keywords: Shopify, plentymarkets App, Shopify Assistent, Shopify Shops, Shopify verbinden
:description: Erfahre, wie du dein plentymarkets Konto mit Shopify verknüpfst, um deine Daten zu synchronisieren.
:author: team-plenty-channel

:shopify:
:market: Shopify
:referrer-option: Shopify
:referrer: Shopify

Genau wie plentymarkets ist auch Shopify eine vollumfängliche E-Commerce-Plattform, mit der du dein Online-Business starten, stetig ausbauen und verwalten kannst. Da Shopify vollständig cloud-basiert und -gehostet ist, brauchst du dich nicht um das Aktualisieren oder Warten von Software oder Webservern zu kümmern.

include::partial$shopify-differences.adoc[]

[#registrierung]
== Bei Shopify registrieren

Um dich bei Shopify zu registrieren, folge den unten beschriebenen Schritten zur App-Installation.

[.instruction]
Bei Shopify registrieren:

. Öffne die Seite link:https://www.shopify.com/signup[Shopify^].
. Öffne das Menü *Admin » Apps*.
. Klicke auf *Anpassung deines Shops*.
. Suche nach der *plentymarkets* App. +
→ Die plentymarkets App wird angezeigt.
. Klicke auf *App hinzufügen*. +
→ Die Bestätigung wird angezeigt.
. Klicke auf *App installieren*. +
→ Die App wird installiert und die Seite zur Registrierung von plentymarkets wird geöffnet.
. Gib deine PID, die Benutzer:in und das Passwort ein. +
*_Tipp:_* Falls du noch keine Zugangsdaten hast, kannst du dich hier für ein System registrieren.
. Klicke auf *Login*. +
→ Die plentymarkets App wird geöffnet.
. Verbinde einen plentymarkets Mandanten. +
*_Tipp:_* Die Umschaltfläche am rechten Rand zeigt an, ob ein Mandant verbunden ist. +
→ Du kannst nun die Einstellungen für Import und Export wie gewünscht vornehmen.

[#integration]
== Verbindung zu Shopify einrichten

In den folgenden Kapiteln ist beschrieben, wie du die Schnittstelle zu Shopify in plentymarkets einrichtest.

[#2885714092]
=== Videotutorial: Installation und Konfiguration

video::4D_3vFrVBIQ[youtube]

[#shopify-konfigurations-assistent]
=== Assistent für Shopify-Konfiguration durchlaufen

Der Assistent *Shopify-Konfiguration* leitet dich durch alle notwendigen Schritte, um deine Shopify-Verbindung einzurichten.

[.instruction]
Assistent *Shopify-Konfiguration* durchlaufen:

. Öffne das Menü *Einrichtung » Assistenten » Omni-Channel*.
. Klicke auf den Assistenten *Shopify-Konfiguration*.
. Klicke auf die verfügbare Konfiguration. +
→ Der Assistent wird geöffnet.
. Folge den Anweisungen auf dem Bildschirm. Wenn du zusätzliche Informationen zu einer der Optionen benötigst, klappe die Infobox unter dieser Beschreibung auf (icon:chevron-down[role="darkGrey"]).
. Wenn alles passt, klicke auf icon:check[role="green"] *Abschließen*. +
→ Der Assistent ist abgeschlossen. +
→ Die Verbindung zu Shopify wird eingerichtet.

[.collapseBox]
.Optionen im Assistenten
--

[width="100%"]
[cols="1,2a"]
|======
|Einstellung |Erläuterung

2+^| Schritt *Shopify-Verbindung*

| Shopify-Verbindung
| Zeigt den Shopify-Hostnamen, den verbundenen plentymarkets Mandanten und den Verbindungsstatus an. In diesem Schritt ist keine Aktion verfügbar oder notwenig.

2+^| Schritt *Artikelverwaltung*

a| Artikelverwaltung
| Bestimme, ob du Artikel importieren oder exportieren möchtest und wie dies ablaufen soll. +
*_Hinweis:_* Import- und Exportprozesse für Artikel können nicht gleichzeitig aktiv sein.

2+^| Schritt *Warenbestands-Verwaltung*

| Warenbestands-Verwaltung
| Bestimme, wie der Import und Export von Warenbestand ablaufen soll. Artikelpreise sind hier ebenfalls mit eingeschlossen. +
*_Hinweis:_* Import- und Exportprozesse für Warenbestand können nicht gleichzeitig aktiv sein.

2+^| Schritt *Zuordnung plentymarkets Lager zu Shopify-Standort*

| Lagerzuordnungen
| Ordne deine plentymarkets Vertriebslager Shopify-Standorten zu. Du kannst auch mehrere plentymarkets Vertriebslager mit ein und demselben Shopify-Standort verknüpfen. Die Auswahl in diesem Schritt beeinflusst den Import und Export von Warenbestand sowie die Auftragsabwicklung. +
*_Hinweis:_* Nur Warenbestand aus Vertriebslager, die einem Standort zugeordnet wurden, kann exportiert und importiert werden.

2+^| Schritt *Auftragsverwaltung*

| Auftragsverwaltung
| Bestimme, wie der Import von Auftragsdaten aus Shopify ablaufen soll. Entscheide außerdem, wie Rückerstattungen und Stornierungsanfragen gehandhabt werden sollen.

2+^| Schritt *Kontaktverwaltung*

| Kontaktverwaltung
| Bestimme, wie der Import von Kontaktdaten aus Shopify ablaufen soll.

2+^| Schritt *Versandprofil-Zuordnung*

| Versandprofil-Zuordnung
| Verknüpfe Versandprofile von Shopify und plentymarkets. Anhand dieser Verknüpfungen werden automatisch Versandprofile für importierte Aufträge bestimmt. Du kannst für jedes bestehende Shopify-Profil ein entsprechendes plentymarkets Profil wählen.
|======
--

[#shopify-assistent-eingabefeldzuordnungen]
=== Assistent zur Eingabefeldzuordnung durchlaufen

Der Assistent zur *Eingabefeldzuordnung* hilft dir dabei, benutzerdefinierte Zuordnungen zwischen Shopify-Eingabefeldern und plentymarkets Quellfeldern zu erstellen. Diese Zuordnungen werden für den Artikelexport verwendet.

*_Hinweis:_* Pro Assistentendurchlauf kannst du nur eine Eingabefeldzuordnung erstellen. Durchlaufe den Assistenten also für jede weitere Zuordnung noch einmal.

[.instruction]
Assistent zur Eingabefeldzuordnung durchlaufen:

. Öffne das Menü *Einrichtung » Assistenten » Omni-Channel*.
. Klicke auf den Assistenten *Eingabefeldzuordnungen*.
. Klicke auf die verfügbare Konfiguration. +
→ Der Assistent wird geöffnet.
. Folge den Anweisungen auf dem Bildschirm. Wenn du zusätzliche Informationen zu einer der Optionen benötigst, klappe die Infobox unter dieser Beschreibung auf (icon:chevron-down[role="darkGrey"]).
. Wenn alles passt, klicke auf icon:check[role="green"] *Abschließen*. +
→ Der Assistent ist abgeschlossen. +
→ Die Eingabefeldzuordnungen werden erstellt.

[.collapseBox]
.Optionen im Assistenten
--

[width="100%"]
[cols="1,2a"]
|======
|Einstellung |Erläuterung

2+^| Schritt *Shopify-Konto*

| *Shopify-Konto*
| Zeigt an, für welches Shopify-Konto die Einstellungen vorgenommen werden. In diesem Schritt ist keine Aktion notwendig.

2+^| Schritt *Bestehende Eingabefeldzuordnungen*

| *Bestehende Eingabefeldzuordnungen*
| Zeigt die vorhandenen Eingabefeldzuordnungen an. Falls eine Zuordnung nicht mehr benötigt wird, kannst du sie hier zum Löschen wählen. Sobald der Assistent abgeschlossen ist, werden die gewählten Zuordnungen gelöscht.

2+^| Schritt *Neue Eingabefeldzuordnung erstellen*

| *Neue Eingabefeldzuordnung erstellen*
| Wähle das Shopify-Feld, dem du im nächsten Schritt eine Datenquelle in plentymarkets zuordnen möchtest. Wenn du aktuell keine neuen Zuordnungen erstellen möchtest, lasse dieses Feld leer.

*_Hinweis:_* Pro Assistentendurchlauf kannst du nur eine Eingabefeldzuordnung erstellen. Durchlaufe den Assistenten also für jede weitere Zuordnung noch einmal. Wenn du *Metafeld* wählst, wird ein neuer Assistentenschritt erstellt.

2+^| Schritt *Metafeld-Konfiguration* (optional)

| *Metafeld-Konfiguration*
| Dieser Schritt ist nur verfügbar, wenn du im Schritt *Neue Eingabefeldzuordnung erstellen* die Option *Metafeld* wählst. Gib den Metafeld-Namespace und Metafeld-Namen von Shopify ein.

*_Hinweis:_* Damit Shopify-Metafelder im Shopify-Backend sichtbar sind, wird eine spezielle Shopify-App benötigt. Wenn du nähere Informationen zu Shopify-Metafeldern benötigst, öffne das link:https://help.shopify.com/en/manual/metafields[Shopify Help Center^]. Gib dort das Stichwort *Metafeld* ein.

2+^| Schritt *plentymarkets Quelleingabefeld*

| *plentymarkets Quelleingabefeld*
| Wähle das plentymarkets Quelleingabefeld, das als Exportdatenquelle verwendet werden soll. +
*_Hinweis:_* Zuordnungen von Quelleingabefeldern sind nur für *Artikelexporte* verfügbar.

2+^| Schritt *Eigenschaft* (optional)

| *Eigenschaft*
| Dieser Schritt ist nur verfügbar, wenn du im Schritt *plentymarkets Quelleingabefeld* die Option *Eigenschaft* gewählt hast. Wähle die Eigenschaft, die als Exportdatenquelle verwendet werden soll.

|======
--

////
[.collapseBox]
.*_Beispielkonfiguration:_* Grundpreis zuordnen
--

In Shopify werden Grundpreisangaben über Metafelder abgebildet. Diese Metafelder werden beim Export der Artikeldaten automatisch erstellt. Du musst die Metafelder also nicht selbst in Shopify erstellen.

Um den Grundpreis zu Shopify zu exportieren, durchläufst du den Assistenten *Shopify: Eingabefelderzuordnungen* dreimal. Dabei verknüpfst du die folgenden plentymarkets Datenfelder mit Metafeldern von Shopify:

* Grundpreis
* Grundpreis: Inhalt
* Grundpreis: Einheit

Die Vorgehensweise und die Einstellungen pro Durchlauf werden hier nur einmal beschrieben.

[.instruction]
plentymarkets Datenfelder für Grundpreisangaben zuordnen:

. Öffne das Menü *Einrichtung » Assistenten » Omni-Channel*.
. Öffne den Assistenten *Shopify: Eingabefelderzuordnungen*.
. Wähle das Shopify-Konto, für das du eine Zuordnung erstellen möchtest. +
→ Der Schritt *Neue Eingabefelderzuordnung erstellen* wird geöffnet.
. Wähle aus der Dropdown-Liste *Verknüpfbare Shopify-Eingabefelder* die Option *Metafeld*.
. Klicke auf *Weiter*. +
→ Der Schritt *Metafeld-Konfiguration* wird geöffnet.
. Nimm die Metafeld-Einstellungen vor:
    * *_Durchlauf 1:_* Gib *Metafeld-Namespace* und *Metafeld-Namen* für den Grundpreis ein.
    * *_Durchlauf 2:_* Gib *Metafeld-Namespace* und *Metafeld-Namen* für den Inhalt des Grundpreises ein.
    * *_Durchlauf 3:_* Gib *Metafeld-Namespace* und *Metafeld-Namen* für die Einheit des Grundpreises ein. +
*_Tipp:_* Metafeld-Namespace und Metafeld-Name sind frei wählbar, müssen aber eindeutig sein.
. Klicke auf *Weiter*. +
→ Der Schritt *plentymarkets Quelleingabefeld* wird geöffnet.
. Wähle eine Option.
    * *_Durchlauf 1:_* Wähle die Option *Grundpreis*.
    * *_Durchlauf 2:_* Wähle die Option *Grundpreis: Inhalt*.
    * *_Durchlauf 3:_* Wähle die Option *Grundpreis: Einheit*.
. Klicke auf *Weiter*.
. Klicke auf *Abschliessen*. +
→ Die Metafelder werden beim nächsten Artikelexport auf Shopify erstellt.

--
////

[#weitere-shops]
=== _Optional:_ Weitere Shopify-Shops verknüpfen

Beachte die folgenden Hinweise, wenn du mehr als einen Shopify-Shop mit plentymarkets verknüpfen möchtest:

* Für jede neue Verknüpfung wird ein separater plentymarkets Mandant und ein separates Shopify-Konto benötigt.
* Um eine zusätzliche Verknüpfung zu erstellen, musst du die plentymarkets App in jedem Shopify-Shop installieren, den du verbinden möchtest.

[#RM4RZXPC]
== Auftragsherkunft aktivieren

:referrer: Shopify
:referrer-option: pass:quotes[Option *Shopify*]

include::maerkte:partial$auftragsherkunft-aktivieren.adoc[]

[#UNO4F1PH]
== Verkaufspreis wählen

:referrer-price: Shopify

include::maerkte:partial$verkaufspreis-festlegen.adoc[]

[#LFL990IP]
== Benutzerdefinierte Auftragseigenschaften importieren

Mit der Shopify-Integration kannst du beim Auftragsimport in plentymarkets benutzerdefinierte Auftragseigenschaften importieren. 

Benutzerdefinierte Auftragseigenschaften erstellt zum Beispiel das Shopify-Plugin link:https://apps.shopify.com/product-personalizer[Product Personalizer^]. Mit diesem Plugin bietest du Kund:innen die Möglichkeit, bei der Bestellung eigenen Text einzugeben. So kannst du personalisierte Produkte anbieten, zum Beispiel mit einer Gravur.

Voraussetzungen für das Importieren von benutzerdefinierten Auftragseigenschaften sind:

* Im Menü *Einrichtung » Artikel » Merkmale* erstellst du ein Merkmal, für das du rechts die Option *Bestellmerkmal* aktivierst.
* Der plentymarkets Artikel hat das Merkmal, bei dem die Option *Bestellmerkmal* aktiviert ist.

[#XV8ANTMR]
== Varianten vorbereiten

Bereite nun deine Varianten vor.

*_Bevor du loslegst:_* Jeder Artikel darf höchstens 100 Varianten haben. Dieses Limit gibt Shopify vor. Artikel mit mehr als 100 Varianten werden also nicht zu Shopify exportiert.

[#beschraenkung-warenbestand]
=== Informationen zur Bestandsbeschränkung

Im Shopify-Backend entscheidet die Option *Verkauf fortsetzen, auch wenn Produkte nicht auf Lager sind* darüber, ob Produkte auch verkauft werden, wenn kein oder zu wenig Bestand im Lager ist. Ob beim Export von Warenbestand diese Option für eine Variante in Shopify aktiviert wird ist abhängig von der plentymarkets Einstellung xref:artikel:verzeichnis.adoc#220[Bestandsbeschränkung].

Je nachdem, welche *Beschränkung* du für eine Variante in plentymarkets festgelegt hast, ist die Checkbox *Verkauf fortsetzen, auch wenn Produkte nicht auf Lager sind* aktiv oder inaktiv:

[cols="2,2"]
|====
| plentymarkets Option *"Beschränkung"* | Shopify-Option *"Verkauf fortsetzen, auch wenn Produkte nicht auf Lager sind"*

| *Keine*
| Aktiviert

| *Auf Netto-WB*
| Nicht aktiviert

| *Keinen WB für diese Variante führen*
| Aktiviert
|====

[#300]
=== Variantenverfügbarkeit einstellen

:market-availability: Shopify
:option-availability: Shopify

include::maerkte:partial$variantenverfuegbarkeit.adoc[]

[#0U31GAX6]
=== Mandant an der Variante aktivieren

Nur Varianten werden exportiert, für die der Mandant (Shop) aktiviert ist, über den du auf {market} verkaufst.

[.instruction]
Mandant an der Variante aktivieren:

. Öffne das Menü *Artikel » Artikel bearbeiten » [Artikel öffnen] » [Variante öffnen]*.
. Wechsele in das Varianten-Tab *Verfügbarkeit*.
. Aktiviere im Bereich *Mandant (Shop)* den Mandanten (Shop), über den du auf {market} verkaufst.
. Speichere die Einstellung.

[#MK10HTRN]
=== SKU speichern

Nur Varianten werden exportiert, für die eine SKU für die Herkunft *Shopify* gespeichert ist.

[.instruction]
SKU für Shopify speichern:

. Öffne das Menü *Artikel » Artikel bearbeiten » [Artikel öffnen] » [Variante öffnen] » Varianten-Tab: Einstellungen*.
. Wechsele in das Tab *Verfügbarkeit*.
. Klicke im Bereich *SKU* auf *Hinzufügen* (icon:plus-square[role="green"]). +
→ Das Bearbeitungsfenster *Neue SKU* wird angezeigt.
. Wähle die Herkunft *Shopify*.
. Wähle das dazugehörige Marktplatzkonto.
. Gib die SKU ein.
. Klicke auf *Hinzufügen* (icon:plus-square[role="green"]). +
→ Die SKU wird gespeichert und angezeigt.

[#TUVEBVS1]
=== Weitere Pflichtangaben ergänzen

Die folgenden Angaben sind Pflicht für den Variantenexport zu Shopify. Ergänze diese Angaben, damit deine Varianten an Shopify exportiert werden.

[.collapseBox]
.Speichere für den Artikel einen "Name 1" und einen "Artikeltext".
--

[.instruction]
Name 1 und Artikeltext speichern:

. Öffne das Menü *Artikel » Artikel bearbeiten » [Artikel öffnen]*.
. Wechsle in das Tab *Texte*.
. Wähle in der Symbolleiste die *Sprache*, in der du Artikeldaten zu Shopify exportierst.
. Gib einen Namen in das Feld *Name 1* ein.
. Gib einen Artikeltext in das Feld *Artikeltext* ein.
. Klicke auf *Speichern*.
--

[.collapseBox]
.Stelle sicher, dass für die Variante ein Attributname und eine Attributwert in der Exportsprache gespeichert sind.
--

Für die Variante müssen ein Attributname und ein Attributwert in der Sprache gespeichert sein, in der du Artikeldaten an Shopify exportierst.

[.instruction]
Attributnamen und Attributwert an Variante prüfen:

. Öffne das Menü *Artikel » Artikel bearbeiten » [Artikel öffnen] » [Variante öffnen]*.
. Navigiere im Tab *Einstellungen* zum Bereich *Grundeinstellungen*. +
→ Die mit der Variante verknüpften Attribute werden unterhalb der Einstellung *Position* angezeigt.

Nun kannst du in den Einstellungen der Attribute prüfen, ob Attributname und Attributwert in der korrekten Sprache gespeichert sind.

[.instruction]
Name und Wert eines Attributs prüfen:

. Öffne das Menü *Einrichtung » Artikel » Attribute » [Attribut öffnen] » Tab: Werte*.
. Wechsele in das Tab *Name*.
. Prüfe den Inhalt des Eingabefelds der Sprache.
. Gib wenn nötig einen Namen für das Attribut ein.
. Wechsele in das Tab *Werte*.
. Wähle in der Symbolleiste die *Sprache*, in der du Artikeldaten zu Shopify exportierst.
→ Die Werte des Attributs werden angezeigt.
. Gib wenn nötig einen Namen für den Attributwert ein.
. Klicke auf *Speichern*, wenn du Änderungen vorgenommen hast.
--

[#OPOU57M9]
=== _Checkliste:_ Voraussetzungen für Variantenexport

include::maerkte:partial$checklist-variations.adoc[tag=checklist-intro]

include::maerkte:partial$checklist-variations.adoc[tag=checklist-variation-active]

include::maerkte:partial$checklist-variations.adoc[tag=checklist-variation-referrer]

include::maerkte:partial$checklist-variations.adoc[tag=checklist-availability-active]

include::maerkte:partial$checklist-variations.adoc[tag=checklist-net-stock]

include::maerkte:partial$checklist-variations.adoc[tag=checklist-sales-price]

:number-of-variations: 100
include::maerkte:partial$checklist-variations.adoc[tag=checklist-number-of-variations]

include::maerkte:partial$checklist-variations.adoc[tag=checklist-name-text-shopify]

include::maerkte:partial$checklist-variations.adoc[tag=checklist-attributes-shopify]

include::maerkte:partial$checklist-variations.adoc[tag=checklist-market-sku]

include::maerkte:partial$checklist-variations.adoc[tag=checklist-market-client]

[#E4EO9VDN]
== Auftragsabwicklung

Hier findest du Informationen zur Auftragsabwicklung.

[#ereignisaktionen]
=== Ereignisaktionen erstellen

Mit den xref:automatisierung:ereignisaktionen.adoc#[plentymarkets Ereignisaktionen] automatisierst du die Auftragskommunikation mit Shopify.

Für die Shopify-App sind die folgenden Ereignisaktionen verfügbar:

*_Tipp:_* Ereignisaktionen richtest du im Menü *Einrichtung » Aufträge » Ereignisse* ein. In der Liste *Aktion hinzufügen* findest du die Aktionen für die Shopify-App im Ordner *Plugins*.

* Shopify App: plentymarkets Auftrags-ID in Shopify speichern
* Shopify App: Archiviere Shopify Auftrag
* Shopify App: Sende manuell hinzugefügte Zahlung an Shopify
* Shopify App: Versandbestätigung an Shopify senden
* Shopify App: Sende Retoure an Shopify
* Shopify App: Storno Benachrichtung an Shopify senden
* Shopify App: Gutschrift an Shopify senden
* Shopify App: Erstattung/Stornierung an Shopify senden
* Shopify App: Erstattung/Stornierung ohne Bestandserhöhung an Shopify senden

[#dsgvo]
== Kontaktimport und DSGVO

Aufgrund von Vorgaben der Datenschutzgrundverordnung (DSGVO) wurden die folgenden Richtlinien für Konten und Aufträge von Kund:innen implementiert:

[[tabelle-dsgvo]]
.Berücksichtigung der DSGVO beim Auftragsimport
[cols="1,2"]
|===
|*Szenario* |*Erläuterung*

| Kund:in wird als regulärer Kontakt importiert
| Wird die Authentizität der Shopify-Kund:in durch eine eindeutige externe Kontakt-ID garantiert, wird ein reguläres Konto erstellt.

| Ein bestehender plentymarkets Kontakt wird mit dem importierten Auftrag verknüpft
| Es wird geprüft, ob eine Kund:in von Shopify mit dieser externen Kontakt-ID in der Vergangenheit schon einmal importiert wurde. Wird ein Kontakt gefunden, wird der neue Auftrag diesem Kontakt zugeordnet.

| Kund:in wird als Gast importiert
| Hat die Kund:in kein plentymarkets Konto und kann die Authentizität der Kund:in auch von Shopify nicht garantiert werden, wird die Kund:in als Gast importiert. Dies gilt auch, wenn die Kontaktdaten mehrerer Aufträge identisch sind.

*Tipp:* Du kannst Kontakte des Typs *Gast* in xref:crm:schnellsuche.adoc#gastzugang-umwandeln[reguläre Kontakte umwandeln].
|===

[#plugin-help]
== Hilfefunktionen nutzen

Im Menü *Einrichtung » Märkte » Shopify-App* kannst du die folgenden Funktionen nutzen:

* <<#3873695972, Die Verbindungsbereitschaft prüfen.>>
* <<#6535986175, Exportbedingungen einer Variante prüfen.>>
* <<#8878636701, Alle 10 Minuten einen Artikel manuell exportieren.>>
* <<#4973807959, Alle 5 Minuten den Warenbestand einer Variante oder eines ganzen Artikels exportieren.>>
* <<#0389029301, Die plentymarkets Auftrags-ID anhand der Shopify-Auftragsnummer finden.>>
* <<#7088931107, Eine Artikelbereinigung planen.>>

[#3873695972]
=== Verbindung zu Shopify prüfen

[.instruction]
Verbindungsbereitschaft prüfen:

. Öffne das Menü *Einrichtung » Märkte » Shopify App » Bereitschaft prüfen*.
. Klicke auf *Prüfen*. +
→ Es wird geprüft, ob eine Verbindung zu Shopify.com hergestellt werden kann. +
→ Es wird geprüft, ob Shopify Direct Checkout installiert ist. +
*_Tipp:_* Erfüllte Bedingungen sind grün und mit einem *OK* markiert. Fehlgeschlagene Bedingungen sind rot und mit einem *X* markiert.

*_Keine Verbindung zu Shopify? Dann prüfe die folgenden Bedingungen:_*

* Ist im Menü *Einrichtung » Aufträge » Auftragsherkunft* die Herkunft *Shopify* aktiviert?
* Gibt es mehr als eine *Shopify*-Herkunft im Menü *Einrichtung » Aufträge » Auftragsherkunft*? Stelle sicher, dass die ID mit der höchsten Zahl aktiviert ist.

[#6535986175]
=== Exportbedingungen einer Variante prüfen

Prüfe, ob eine Variante alle Bedingungen für den Export zu Shopify erfüllt.

[.instruction]
Exportbedingungen einer Variante prüfen:

. Wähle den Webshop, für den du die Variante überprüfen möchtest.
. Öffne das Menü *Einrichtung » Märkte » Shopify App » Hilfe » Exportbedingungen*.
. Gib eine gültige Varianten-ID ein.
. Klicke auf *Prüfen*. +
→ Es wird geprüft, ob die Variante die Exportbedingungen erfüllt. +
*_Tipp:_* Erfüllte Bedingungen sind grün und mit einem *OK* markiert. Fehlgeschlagene Bedingungen sind rot und mit einem *X* markiert. +
*_Wichtig:_* Varianten müssen alle Bedingugnen erfüllen, um exportiert zu werden.

*_Die folgenden Bedingungen werden geprüft:_*

* Ist die Variante aktiv? +
→ Im Menü *Artikel » Variante » Einstellungen » Bereich: Verfügbarkeit » Aktiv* muss ein Häkchen gesetzt sein.
* Ist die Variante für den Marktplatz Shopify verfügbar? +
→ *Artikel »Variante » Verfügbarkeit » Bereich: Märkte » Option: Shopify* muss aktiv sein.
* Stimmt die *Variante » Mandant Zuordnung* mit der *Webshop*-Auswahl überein? +
→ *Artikel » Variante » Verfügbarkeit » Bereich: Mandant » [Gewählter Mandant]*.
* Ist ein *Artikeltext* am Artikel gespeichert? +
→ *Artikel » Texte » Artikeltext* muss verfügbar sein.
* Ist ein *Name 1* am Artikel gespeichert? +
→ *Artikel » Texte » Name 1* muss ausgefüllt sein.
* Hat die Variante eine SKU für Shopify? +
→ *Artikel » Variante » Verfügbarkeit » Bereich: SKU* muss eine *SKU* für die Herkunft *Shopify* enthalten.
* Hat die Variante einen für Shopify freigegebenen Verkaufspreis mit Standardwährung?
* Ist für die ausgewählte Artikelexportsprache ein Varianten-Attributname gespeichert?
* Ist für die ausgewählte Artikelexportsprache ein Varianten-Attribuwert gespeichert?
* Ist für die ausgewählte Artikelexportsprache ein Titel und eine Beschreibung des Artikels gespeichert?
* Hat der Artikel maximal 100 Varianten? +
→ Exportierte Artikel dürfen nicht mehr als 100 Varianten enthalten. Dieses Limit wird von Shopify vorgegeben.

// TODO: Liste besser gestalten.

[#8878636701]
=== Einen Artikel manuell exportieren

Zu Testzwecken kannst du alle 10 Minuten einen Artikel manuell exportieren.

[.instruction]
Artikel manuell exportieren:

. Öffne das Menü *Einrichtung » Märkte » Shopify-App » Artikelexport*.
. Wähle einen Webshop.
. Gib eine gülitge Artikel-ID ein.
. Klicke auf *Ausführen*. +
→ Wenn alle Exportbedingungen erfüllt sind, werden der Artikel und die dazugehörigen Varianten exportiert.

*_Hinweis:_* Wenn du einen oder mehrere Artikel auf Shopify gelöscht hast, um sie noch einmal zu exportieren, bereinigt der erste Export nur die Datenbank. Erst der zweite Export speichert den Artikel wieder auf Shopify.

[#2729787975]
=== Bestände manuell exportieren

Zu Testzwecken kannst du alle 5 Minuten manuell Warenbestände für einen Artikel exportieren. Für eine Variante ist der Export alle 3 Minuten möglich.

[tabs]
====
Bestand für einen Artikel manuell exportieren::
+
--

[.instruction]
Bestand für einen Artikel exportieren:

. Öffne das Menü *Einrichtung » Märkte » Shopify-App » Bestandsexport*.
. Wähle einen Webshop.
. Wähle aus der Dropdown-Liste *xxx* die Option *Exportiere Warenbestand für Artikel*.
. Gib eine gültige *Artikel-ID* ein.
. Klicke auf *Ausführen*. +
→ Wenn alle Exportbedingungen erfüllt sind, wird der Warenbestand für den Artikel exportiert. +
*_Hinweis:_* Den nächsten manuellen Export eines Artikels kannst du erst nach 5 Minuten starten.
--
 
Bestand für eine Variante manuell exportieren::
+
--
[.instruction]
Bestand für eine Variante exportieren:

. Öffne das Menü *Einrichtung » Märkte » Shopify-App » Bestandsexport*.
. Wähle einen Webshop.
. Wähle aus der Dropdown-Liste *xxx* die Option *Exportiere Warenbestand für Variante*.
. Gib eine gültige *Varianten-ID* ein.
. Klicke auf *Ausführen*. +
→ Wenn alle Exportbedingungen erfüllt sind, wird der Warenbestand für die Variante exportiert. +
*_Hinweis:_* Den nächsten manuellen Export einer Variante kannst du erst nach 3 Minuten starten.
--
====

[#8869548744]
=== Benutzerdefiniertes Startdatum für Bestandsexport festlegen

Wenn du Warenbestände für Artikel mit einem älteren *Letzte Änderung*-Datum exportieren möchtest.

[.instruction]
Startdatum festlegen:

. Öffne das Menü *Einrichtung » Märkte » Shopify-App » Bestandsexport*.
. Wähle einen Webshop.
. Wähle aus der Dropdown-Liste die Option *Aktualisierungsdatum*.
. Wähle ein Startdatum aus dem *Kalender*.
. Gib eine *Uhrzeit* ein.
. Klicke auf *Speichern*. +
→ Der nächste Bestandsexport wird zum gewählten Zeitpunkt ausgeführt. +
*_Wichtig:_* Das angezeigte Startdatum wird nach jedem Export aktualisiert.

[#0389029301]
== plentymarkets Auftrags-ID anhand Shopify-Bestell-ID finden

Wenn Kund:innen dich mit der Shopify-Bestell-ID kontaktieren kannst du diese ID verwenden, um die plentymarkets Auftrags-ID des Auftrags zu finden.

[.instruction]
plentymarkets Auftrags-ID finden:

. Öffne das Menü *Einrichtung » Märkte » Shopify-App » Auftrags-ID finden*.
. Wähle den Webshop, für den du die Shopify-Bestell-ID erhalten hast.
. Gib eine gültige Shopify-Bestellnummer ein.
. Klicke auf *Suchen*. +
→ Wenn die Shopify-Bestellnummer gültig ist, wird die plentymarkets Auftrags-ID angezeigt.

[#7088931107]
== Artikelbereinigung planen

Plane eine Artikelbereinigung, wenn: 

* Artikel oder Varianten aus plentymarkets gelöscht wurden und auch aus Shopify entfernt werden sollen.
* Artikel oder Varianten manuell aus Shopify gelöscht wurden und das Plugin keinen neuen Export durchführt.
* Alle Shopify-Artikel gelöscht werden und ein neuer Export aus plentymarkets gestartet werden soll. In diesem Fall deaktiviere den Artikelexport und lösche alle Artikel aus Shopify. Plane eine Artikelbereinigung. Am nächsten Morgen kannst du den Artikelexport reaktivieren.

*_Hinweis:_* Verwende die Artikelbereinigung nicht, wenn deine Artikel nach der Einrichtung der Verbindung aus Shopify importiert wurden. Das kann zu Artikelverlust auf Shopify führen. Die Artikelbereinigung wird nur einmal ausgeführt, nachdem sie geplant wurde. Plane nach Bedarf neue Artikelbereinigungen.
 
[.instruction]
Artikelbereinigung planen:

. Öffne das Menü *Einrichtung » Märkte » Shopify-App » Artikelbereinigung*.
. Wähle den *Webshop*, für den du ein Cleanup planen möchtest.
. Clicke auf *Bereinigung planen*. +
→ Betroffene Artikel werden beim nächsten nächtlichen Export auf Shopify gelöscht.

*_Hinweis:_* Bereits exportierte Artikel und Varianten werden in den folgenden Fällen bei der Bereinigung aus Shopify gelöscht:

* Aus der plentymarkets Variante wurden *Mandant (Client)* und *Shopify-Marktplatz* entfernt.
* Die Variante wurde aus plentymarkets gelöscht.
* Bei Artikeln ohne aktive Varianten wird der gesamte Artikel auf Shopify gelöscht.
