= Customising the reorder view

:keywords: MyView, design reorder view, customise reorder view, adjust reorder view, adjust columns for reorder view, configure columns, compact view
:author: team-order-core
:description: Learn how to customize the overview of your reorders. In the editing mode, decide for yourself which information and settings you need for managing your reorders.

On this page, you will learn how to customize the overview of your reorders according to your preferences using various views and settings.

[#100]
== Customising the reorder view

In the compact view, the order details you selected are displayed space-efficiently directly in the overview.

You can customize the compact view and determine which information about your reorders should be displayed in the xref:working-with-reorders-new.adoc#370[editing mode]. Additionally, you can choose the size of the various information fields and, if necessary, add colour highlighting to further visually differentiate the fields.

In the following chapters you will learn how to customise the compact view according to your needs.

[#150]
=== Choosing the fields for the reorder overview

First, choose which fields should be displayed in your reorder overview. To do so, proceed as follows.

[.instruction]
Choosing the fields for the reorder overview:

. Go to *Stock » Reorder (Test phase)*.
. Carry out the Search (material:search[]) to display reorders.
. At the top right, click on *Edit view* (terra:design_inline_edit[]) to edit the compact view in the editing mode.
. At the top right of the main window, click on *Edit* (material:edit[role=skyBlue]). +
→ The editing mode opens.
. In the settings on the right, select the fields to be displayed in the compact view by checking (material:check_box[role=skyBlue]) the options in the *Compact view* area. You can find further information on the available fields in <<#table-reorder-compact-view-title>>. +
*_Tip:_* Move material:drag_indicator[] the selected fields via drag-and-drop to the desired position until they are displayed in the desired order. Specify <<#170, which information>> each field should contain. +
. If you are satisfied with the selected fields, click on *Save view* (material:save[role=skyBlue]) at the top right.
. Enter a name for the new view and click on *Create view*. +
→ The new view is created.

[TIP]
.Do you have admin rights?
======
Only xref:business-decisions:user-accounts-access.adoc#[admin users] can create and edit views.
If you are not an admin:

. Turn to someone with admin rights.
. Ask the person to create the necessary views for you and to assign them to your user account.
======

[[table-reorder-compact-view-title]]
.Fields for the compact view
[cols="1,3"]
|===
|Setting |Explanation

| *Supplier address*
|Displays supplier's address.

| *Warehouse*
|Displays the target warehouse to which the reorder should be delivered. 

| *Tags*
|Displays the tags that are assigned to this reorder.

| *Item quantity*
|Displays the quantity of items in the reorder.

| *Supplier ID*
|Displays the ID of the supplier.

| *Owner*
|Displays the owner of the reorder.

| *Status*
|Displays the status of the reorder.

| *Currency*
|Displays the currency of the reorder.

| *Invoice total*
|Displays the invoice amount of the reorder.

| *External order ID*
|Displays the external ID of the order.

| *Main document*
|In case a document has already been created for the reorder, the document number is displayed. By clicking on the number, the document opens.

| *Ordered date*
|Displays the date the order was placed.

| *Payment due date*
|Displays payment due date of the reorder.

| *Delivery date*
|Displays the delivery date of the reorder.

| *Finish date*
|Displays the finish date of the reorder.

| *Custom property (1-5)*
|Displays the selected custom property. There are 5 fields available.

| *Finish date*
|Displays the address of the target warehouse.

|===

[#170]
==== Configuring fields

For the fields you have chosen, you can make additional settings such as determining the field size, changing the title, or adding a colour highlighting. To do so, proceed as follows.

[.instruction]
Configuring fields:

. Go to *Stock » Reorder (Test phase)*.
. Carry out the Search (material:search[]) to display reorders.
. At the top right, click on *Edit view* (terra:design_inline_edit[]) to edit the compact view in the editing mode.
. At the top right of the main window, click on *Edit* (material:edit[role=skyBlue]). +
→ The editing mode opens.
. Expand the fields (material:chevron_right[]) to configure them. Refer to the information given in <<#table-reorder-view-field-settings>>.
. If you are satisfied with the selected fields, click on *Save view* (material:save[role=skyBlue]) at the top right. +
→ The changes are saved.

[[table-reorder-view-field-settings]]
.Settings for the fields in compact view
[cols="1,3"]
|===
|Setting |Explanation

| *Custom field name*
|Here you can enter another title for the respective field if desired.

| *Colour highlighting*
|Optionally select a colour highlighting that will be shown on the left side of the respective field. This can help to visually separate and highlight the fields. If you don’t select a colour, a grey highlight will be displayed on the field by default. +
The following fields already have the following highlight by default: +
*Invoice address* = red +
*Delivery address* = red +
*Contact ID* = blue +
*Main document* = blue

| *Field size (horizontal)*
|Select how wide the field should be displayed in the overview. Select between the options *small*, *medium* and *large*. +
*_Note:_** For the fields *Tags* and *Invoice address* you can also select the vertical field size.

| *Only show icon*
|Select whether only the icon for the field (e.g. for the status) should be displayed. +
Note that this setting is only available for specific fields.

| *Show in header*
|Choose whether the field should also be displayed in the header of the reorder.
Note that this setting is only available for specific fields.

|===

[#190]
==== Selecting functions and filter settings

In the editing mode you can also decide which functions and filters should be displayed in the reorder overview. To adjust the settings, proceed as follows.

[.instruction]
Selecting functions and filters:

. Go to *Stock » Reorder (Test phase)*.
. Carry out the search (material:search[]) to display orders.
. At the top right, click on *Edit view* (terra:design_inline_edit[]) to edit the compact view in the editing mode.
. At the top right of the main window, click on *Edit* (material:edit[role=skyBlue]). +
→ The editing mode opens.
. At the top right in the *Settings* section, carry out the settings for the view. Refer to the information given in <<#table-general-settings-reorder-view>>.
. If you are satisfied with the settings for the view, click on *Save view* (material:save[role=skyBlue]) at the top right. +
→ The changes are saved.

[[table-general-settings-reorder-view]]
.Settings for functions and filters
[cols="1,3"]
|===
|Setting |Explanation

| *Group functions*
|Choose which xref:working-with-reorders-new.adoc#100[group functions] should be shown by default for reorders. All remaining group functions will be available in the context menu (material:more_vert[]) right next to it.

| *Menu functions*
|Select which menu functions should be displayed for orders by default. All remaining menu functions will be available in the context menu (material:more_vert[]) right next to it.

| *Colour highlighting*
|Choose whether the header should have the colour of the status, a custom colour, or no colour at all. 

| *Filter*
|Select in how many columns the selected filters should be displayed in the filter selection.

| *Autocomplete*
|Select what should be automatically searched for in the quick search when an entry is made. Set a checkmark (material:check_box[role=skyBlue]) for all desired options.

|===

[TIP]
.Sort by reorders
====
In the compact view you can sort your orders by the *Order ID* and the *Status*. To do so, select one of the two options from the *Sort by drop-down list* and decide whether you want the reorders to be displayed in *Descending* (material:arrow_downward[]) or in *Ascending* (material:arrow_downward[]) order.
====