= The plentyWarehouse app
:keywords: plentyWarehouse, plenty Warehouse, plentyWarehouse overview, plenty Warehouse overview
:description: The newly-developed plentyWarehouse app offers you numerous possibilities to deal with mobile stock management efficiently.
:author: team-app-bi

The newly-developed plentyWarehouse app offers you numerous possibilities to deal with mobile stock management efficiently.
Step by step, all stock management features that are already available in the xref:app:app.adoc#[existing plentymarkets app] will become part of the new plentyWarehouse app. Our goal in this development process is to offer more a more intuitive user experience, stable performance and a technical basis that is both reliable and up-to-date. You can profit from all of these advantages and a number of new features by downloading the plentyWarehouse app.

[#100]
== Which functions does the plentyWarehouse app offer?

The following functions are currently available in plentyWarehouse. Click on the entries in the list to access the respective page of the manual along with further information and instructions.

* xref:stock-management:items-and-storage-locations.adoc#100[Item search]
* xref:stock-management:items-and-storage-locations.adoc#400[Inspecting storage locations]
* xref:stock-management:redistributing-items.adoc#[Redistributing items]
* xref:stock-management:reshelving-items.adoc#[Reshelving items]
* xref:stock-management:carrying-out-stocktaking.adoc#[Taking stock]
* xref:stock-management:mobile-pick-lists.adoc#[Working with pick lists]
* xref:stock-management:box-picking.adoc#[Carrying out box picking]
* xref:stock-management:printing-labels.adoc#[Printing labels for items and storage locations]

[#200]
== Downloading and installing the plentyWarehouse app

First, download the plentyWarehouse app and install it on a device that meets the hardware requirements.

* link:https://play.google.com/store/apps/details?id=com.plentysystems.plentywarehouse&hl=en[The plentyWarehouse app on Google Play Store^]

include::app:partial$hardware-plentywarehouse.adoc[]

[#300]
== How do you set it up?

Have you downloaded the plentyWarehouse app and installed it on the appropriate hardware? Then you can proceed with setting up the app.

The xref:stock-management:installation-and-initial-setup.adoc#[Installation and initial setup] page of the manual offers you detailed information on your first app login, finding your way around the plentyWarehouse app and carrying out the basic settings required before productive use of the app.
