= plentyWarehouse: Rights management
:keywords:
:description:
:author: team-app

////
Platzhalter für englische Seite

Auf diese Seite wird aus dem Ankündigungs-Popup in der plentyWarehouse App verlinkt. Sie soll Informationen enthalten, wie die Rechte in plentyWarehouse ab Ende Juni funktionieren und was die ToDos für User sind. Diese Seite bleibt im Handbuch unsichtbar und ist nur für diesen Zweck gedacht, da App-User von ihren Geräten meist nicht für weitere Informationen das Forum aufrufen können.
////

[discrete]
== Assigning rights for roles

Assign the rights for functions within the plentyWarehouse App to users with roles that are *_not_* of the type *Administrator*.

Complete this step before 29 June 2023.

[.instruction]
Assigning rights for roles:

. Use an *Administrator* account to log into your system.
. Go to *Setup » Account management » Roles*.
. Click on *Search* icon:search[role="darkGrey"]. +
→ All roles that exist in the system are listed. +
. Open the desired role.
. *_Important:_* Make sure that you are using the *Simple mode* of the rights view.
. Expand the menu entry *plentyWarehouse*.
. Activate material:check_box[role=skyBlue] the functions that should be visible and thus usable for the role in plentyWarehouse. Also, pay attention to the individual rights for the *Incoming items* function.
. *Save* icon:save[role="darkGrey"] the settings. +
→ The selected functions are visible for the role.

[TIP]
.Do you need help?
====
Visit our link:https://forum.plentymarkets.com/c/app-pos/plentywarehouse/579[forum category^] to find the right contact persons to help you out with individual questions or problems. The forum is also the place to go for further up-to-date information on this topic.
====

