= Variations: Enabling stock tracking
:keywords: Stock management, Stock limitation, Limitation, To net stock, Do not administer stock for this variation, Delivery time, Processing time, Handling time, Availability, Availability with stock, Availability without stock, Storage location type, Reorder level, Stock turnover (in days), Suggested storage location
:description: Should plentysystems track the stock levels of your products? This page explains the product settings that are relevant to stock management.
:author: team-stock

////
zuletzt bearbeitet 10.05.2022
////

plentysystems includes several product settings that are relevant to stock management.
This page explains the settings and helps you configure your products so that you can track their stock levels at any time.

[#100]
== Which variations should be tracked?

First, decide which products should have their stock levels tracked.

. Go to *Item » Edit item » [Open variation] » Tab: Settings » Area: Availability*.
. Select the appropriate option from the drop-down list *Limitation*.
. *Save* (terra:save[role="green"]) the settings.

[cols="1s,4a"]
|===
|Setting |Explanation

| None
|This setting is useful for situations where you could technically count the stock units, but it doesn’t matter whether the stock is negative or not.
The product is available, just without any particular stock value.

*_Note_*: Some marketplaces only consider the stock value that is assigned to the variation.
So if you select this setting, then the marketplace might never have an active offer for the product because it might never understand this as a positive stock value.
Check how your target marketplaces will interpret the stock limitation setting before you begin selling on them.

| To net stock
|This is the most commonly used option.
It prevents you from accidentally overselling items.
The stock is limited to the net stock.
This net stock level is transmitted to marketplaces.

*_What does net stock mean?_* +
This number indicates how many copies of the item are currently available for sale.
The net stock is a subset of the physical stock.
Substract all reserved quantities from the physical stock and you will get the net stock.
xref:stock-management:managing-stocks.adoc#100[Further information].

| Do not administer stock for this variation
|This setting is useful for situations where it would be very time-consuming to count the stock units.
For example, imagine you sell construction supplies and you have millions of copies of a screw.

*_Note_*: Some marketplaces only consider the stock value that is assigned to the variation.
So if you select this setting, then the marketplace might never have an active offer for the product because it might never understand this as a positive stock value.
Check how your target marketplaces will interpret the stock limitation setting before you begin selling on them.

*_Note_*: If this setting is selected, then the variation’s *Stock* tab will not include the sub-tabs *Correction*, *Stock*, *Supply* and *Item movement*.

|===

[#200]
== What is the variation’s availability?

Next, enter the average delivery time for your variations.
This information can either be static or dynamic.

* *Static*: You select a processing time that is always true for the variation, e.g. ready to be shipped within 3 days.
* *Dynamic*: You select one processing time that applies if the variation is in stock, e.g. ready to be shipped within 3 days.
And you select another processing time that applies if the variation is not in stock, e.g. ready to be shipped within 2 weeks.

[.collapseBox]
.*Static setting*
--

TIP: There are ten availability levels in plentysystems.
Make sure you’ve already defined the availability levels in the menu *Setup » Item » Availability* before you proceed.
xref:item:availability.adoc#100[Further information].

. Go to *Item » Edit item » [Open variation] » Tab: Settings » Area: Availability*.
. Select the appropriate availability level (symbols 1-10).
. *Save* (terra:save[role="green"]) the settings.

--

[.collapseBox]
.*Dynamic setting*
--

TIP: There are ten availability levels in plentysystems.
Make sure you’ve already defined the availability levels in the menu *Setup » Item » Availability* before you proceed.
xref:item:availability.adoc#100[Further information].

. Go to *Setup » Stock » Warehouse » [Open warehouse] » Settings*.
. Select the appropriate availability level (symbol 1-10) for the settings *Availability with stock* and *Availability without stock*.
. *Save* (terra:save[role="darkGrey"]) the settings.

If the variation is assigned to multiple warehouses and they all have different availability levels, then plentysystems will always use the best option.
Example: The item is available in warehouse A and B.

* Warehouse A has an availability of 2 days.
* Warehouse B has an availability of 5 days.
* In this case, warehouse A will be used since it has the better availability level.

--

[#300]
== Where are the variations located?

Where is the variation stored?
Assign your variations to the appropriate storage locations.
This is useful so that you can:

* xref:stock-management:new-incoming-items.adoc#450[correctly receive incoming goods].
* xref:stock-management:working-with-reorders.adoc#[reorder goods when you start to run out].


[TIP]
.Have you already saved warehouse information?
====
Before you can link variations to storage locations, you’ll need to tell plentysystems a little bit about your warehouse.
How many zones, racks, shelves and storage locations are there in your warehouse?
xref:stock-management:setting-up-a-warehouse.adoc#[Set up your warehouse] before you continue.
====

////

. Go to *Item » Items » [Open variation] » Element: Warehouse*.
. Click on *Add warehouse* (icon:plus[role="darkGrey"]). +
→ A pop-up window will open.
. Select the warehouse that you want to link.
. Click on *Apply*. +
→ The data will be displayed as a table.
. *Save* (terra:save[role="darkGrey"]) the settings.

////

. Go to *Item » Edit item » [Open variation] » Tab: Warehouse*.
. Select the appropriate warehouse from the drop-down list.
. Click on *Add* (icon:plus[role="green"]). +
→ The warehouse is assigned to the variation and you can carry out further settings.
. *Save* (terra:save[role="green"]) the settings.

//zukunft - die beschreibungen in der tabelle verständlicher machen (siehe Schulung mit Oskar) und auch mit den Beschreibungen unter warenwirtschaft:wareneingaenge-verwalten.adoc#200 angleichen - dafür includes verwenden

[cols="1s,4a"]
|===
|Setting |Explanation

| Warehouse
|Here you see the warehouse that was selected.
This is purely informative and cannot be changed.

| Storage location type
|Select the storage location type according to the size of the variation.

//this doesn't make sense - in the ui you can choose 1-20 : it doesn't match the warehouse dimensions saved
| Zone
|Select a zone if you have set up zones for this warehouse.

| Reorder level
|Enter the quantity at which the variation should be reordered.
If the variation’s stock level sinks down to this reorder level, then plentysystems will automatically suggest that you reorder it. This means that the variation is only reordered once it has reached the reorder level.

*_Note_*: If the xref:stock-management:setting-up-a-warehouse.adoc#reorder-value_variation_warehouse[difference between the current stock level and the reorder level] is calculated dynamically, then you can only save the value `0` here.

| Stock turnover (in days)
|Enter the number of days that the stock should suffice until the next reorder.
This value is relevant for calculating the reorder quantity.

*_Note_*:
If no value is entered here, then the stock turnover (in days) is not taken into consideration when calculating a reorder date.

*_Practical example_*:
A standard value that could be used for the stock turnover is 14 days.
Once the item has reached the reorder level, the 14 days will be used to calculate how many copies of the item need to be reordered. In other words, the suggested reorder quantity would be sufficient for the following 14 days.

| Maximum stock
|Currently not in use.

//klären, ob diese Option eine Funktion hat - es klang als ob wir uns nicht sicher sind, ob Amazon den Wert hier berücksichtigt
| Stock buffer
|Enter a stock buffer.
This causes the stock to be reduced by this value for certain markets.

*_Example_*: There are 50 copies of an item in stock.
You want to keep 10 copies of the item as a buffer, so that the item cannot be sold out completely on the market.
This is done by entering 10 as the stock buffer.
As a result, 40 copies of the item are transmitted to the marketplace.

*_Note_*:

* The values entered here are only used for the markets xref:markets:amazon-setup.adoc#[Amazon] and xref:markets:shopgate.adoc#[Shopgate].
The buffer entered here takes priority over the buffer values entered in the marketplace.
* This setting is irrelevant for all other markets.
Here, the market's stock buffer settings take priority.

| Batch
|Select this option if the batch number should be saved for this variation and warehouse.

*_Note_*: Once stock has been booked into the warehouse, you will no longer be able to deactivate this option.
If the stock level for the warehouse is 0, then it will be possible to activate or deactivate the option.

| BBD
|Select this option if the best before date should be saved for this variation and warehouse.

*_Note_*: Once stock has been booked into the warehouse, you will no longer be able to deactivate this option.
If the stock level for the warehouse is 0, then it will be possible to activate or deactivate the option.

| Suggested storage location
|Select a storage location that should automatically be suggested when the variation is reordered.

*_Note_*: The standard storage location serves as a placeholder. It means that you haven’t chosen a specific storage location yet.

|===
