= Mobile Warenwirtschaft
:author: team-app-bi
:keywords: App, mobile Warenwirtschaft, App Warenwirtschaft, App Bestände verwalten, mobile Lagerverwaltung
:description: Soll dein Lagerpersonal mit einer mobilen Warenwirtschaft kommissionieren? Die plentymarkets App unterstützt dich beim Picken und Packen. Weiterhin können Lagermitarbeiter:innen die App nutzen, um Ware zu verräumen oder Inventur durchzuführen.

Soll dein Lagerpersonal mit einer mobilen Warenwirtschaft kommissionieren? Die plentymarkets App unterstützt dich beim Picken und Packen. Weiterhin können Lagermitarbeiter:innen die App nutzen, um Ware zu verräumen oder Inventur durchzuführen.

[IMPORTANT]
.Jetzt zur plentyWarehouse App wechseln!
====
Die Funktionen zur mobilen Warenwirtschaft in der plentymarkets App werden nicht mehr weiterentwickelt. Wir empfehlen dir, die neuen und verbesserten Funktionen in der plentyWarehouse App zu nutzen. xref:warenwirtschaft:plentywarehouse.adoc#[Hier] erhältst du alle wichtigen Informationen zu plentyWarehouse.
====

* xref:app:rollende-kommissionierung.adoc#[Rollende Kommissionierung]
* xref:app:einbuchen-umbuchen.adoc#[Ware einbuchen und umbuchen]
* xref:app:verraeumen.adoc#[Ware verräumen]
* xref:app:inventur.adoc#[Inventur durchführen]
