CheckExternal: false
DirectoryPath: "build/"
IgnoreDirs:
- "changelog"
IgnoreDirectoryMissingTrailingSlash: true
IgnoreInternalEmptyHash: true
IgnoreURLs:
- "https://www.linkedin.com/company/plentymarkets-ltd/"
- "https://twitter.com/plentymarkets"
- "https://marketplace.plentymarkets.com/"
- "www.example.com"
- "/de-de/manual/main/willkommen/systemvoraussetzungen.html"
- "/de-de/manual/main/business-entscheidungen/systemadministration.html"
- "/de-de/manual/main/willkommen/assistenten.html"
- "/de-de/manual/main/business-entscheidungen/eol.html"
- "/en-gb/manual/main/welcome/quick-start-system-requirements.html"
- "/en-gb/manual/main/business-decisions/system-administration.html"
- "/en-gb/manual/main/welcome/assistants.html"
- "/en-gb/manual/main/business-decisions/eol.html"
LogSort: document
