CheckExternal: false
DirectoryPath: "build/"
IgnoreDirs:
- "changelog"
IgnoreDirectoryMissingTrailingSlash: true
IgnoreInternalEmptyHash: true
IgnoreURLs:
- "https://www.linkedin.com/company/plentymarkets-ltd/"
- "https://twitter.com/plentymarkets"
- "https://marketplace.plentymarkets.com/"
- "www.example.com"
