site:
  title: plentymarkets manual
  url: https://knowledge.plentymarkets.com/en-gb
content:
  sources:
    - url: ./
      branches: HEAD
      start_path: adocOutput/en
asciidoc:
  attributes:
    tabs: tabs
output:
  dir: ./build/en
ui:
  bundle:
    url: https://github.com/plentymarkets/plenty-docs-ui/raw/main/build/ui-bundle.zip
    snapshot: true
