# Either clone the content repositories listed under sources or delete the respective blocks.
# Clone the UI repository from plenty-docs-ui.
# Change USER in the url paths to your user name.
site:
  title: plentymarkets manual
  url: https://knowledge.plentymarkets.com/en-gb
content:
  sources:
    - url: ./
      branches: HEAD
      start_path: docs/en-gb
asciidoc:
  attributes:
    # Organisation
    copyright: © 2021 plentysystems AG
    orgname: plentysystems AG
    # General
    icons: font
    linkattrs:
    sectnums:
    numbered:
    xrefstyle: short
    source-highlighter: highlightjs
    example-caption!:
    stem: latexmath
    # Extensions
    tabs: tabs
  extensions:
    - ./lib/tabs-block.js
    - ./lib/inline-icon.js
output:
  dir: ./build/en-gb
ui:
  bundle:
    url: /Users/USER/workspace/plenty-docs-ui/build/ui-bundle.zip
    snapshot: true
