= Bankdaten verwalten
:keywords: Bank, Bankdaten, EBICS, SEPA, SEPA-Lastschriftmandat, Lastschrift, Bankinformationen, Konto, Bankkonto, Kontoinhaber, Kontonummer, Konto-Nr., Konto-Nummer, BLZ, Bankleitzahl, Account, IBAN, Bankverbindung, BIC, Mandat, Einzugsermächtigung, Abbuchungsauftrag, Bankdaten, Zahlungsverkehrsdaten, EBICS-Konto, Vormerkposten, Geschäftskonto, Geschäftskonten, Auszugsbereitstellung, buchungstagsorientiert, Buchungstag, auszugsorientiert, Auszugsnummer, Auszusgserstellung, technischer Teilnehmer, Buchung, Buchungen, STA, VMK, EU Typ, EU TYP T, Typ T, Kontoeinstellungen, Tagesumsatz, Tagesumsätze, Geschäftsvorfall, Geschäftsvorfälle, Zahlungsabruf, manueller Zahlungsabruf, INI, INI-Brief, Initialisierung, HIA, CAMT, Abrufintervall, Transaktion, Kreditinstitut, Überweisung, Lastschrift, Firmenlastschrift, Zahlungsempfänger, Gläubiger-Identifikationssnummer, Mandatsreferenz
:description: Verwalte deine Bankdaten und die Bankdaten deiner Kund:innen. Richte EBICS und SEPA in deinem plentymarkets System ein.
:author: team-fulfillment-payment

Auf dieser Handbuchseite erfährst du, wie du deine <<#eigene-bankdaten, Bankdaten>> und die <<#bankdaten-kunden, Bankdaten deiner Kund:innen>> in plentymarkets speicherst und wie du <<#ebics, EBICS>> und <<#220, SEPA>> einrichtest.

[#eigene-bankdaten]
== Eigene Bankdaten speichern

Die Bankdaten, die in den Grundeinstellungen zentral gespeichert werden, sind global im gesamten plentymarkets System verknüpft. Die gespeicherten Bankdaten gelten somit für alle Mandanten. Es ist nicht möglich, unterschiedliche Bankdaten für verschiedene Mandanten zu speichern. Eine Korrektur der Bankdaten ist ausschließlich im Menü *Einrichtung » Einstellungen » Bank* vorzunehmen. Änderungen wirken sich auf das gesamte System aus.

[.instruction]
Bankdaten speichern:

. Öffne das Menü *Einrichtung » Einstellungen » Bank*.
. Gib deine Bankdaten ein. Beachte dazu die Erläuterungen in <<#tabelle-bankdaten-speichern>>.
. *Speichere* (material:save[]) die Einstellungen.

[[tabelle-bankdaten-speichern]]
.Bankdaten speichern
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Inhaber:in*
|Gib den Vornamen und Nachnamen der Kontoinhaber:in ein. +

Verwende die Variable *Kontoinhaber (Stammdaten)* für E-Mail-Vorlagen, die du über den xref:crm:emailbuilder.adoc#[EmailBuilder] erstellst. +
Verwende die Template-Variable *$BankAccountOwner* für E-Mail-Vorlagen, die du über die xref:crm:e-mails-versenden.adoc#1200[Mandanteneinstellungen] erstellst.

| *Kontonummer*
|Gib die Kontonummer ein. +

Verwende die Variable *IBAN (Stammdaten)* für E-Mail-Vorlagen, die du über den xref:crm:emailbuilder.adoc#[EmailBuilder] erstellst. Die IBAN setzt sich zusammen aus der Länderkennung (DE für Deutschland), einer Prüfziffer sowie der bisherigen Bankleitzahl und Kontonummer. +
Verwende die Template-Variable *$BankAccount* für E-Mail-Vorlagen, die du über die xref:crm:e-mails-versenden.adoc#1200[Mandanteneinstellungen] erstellst.

| *BLZ*
|Gib die Bankleitzahl ein. +

Verwende die Variable *IBAN (Stammdaten)* für E-Mail-Vorlagen, die du über den xref:crm:emailbuilder.adoc#[EmailBuilder] erstellst. Die IBAN setzt sich zusammen aus der Länderkennung (DE für Deutschland), einer Prüfziffer sowie der bisherigen Bankleitzahl und Kontonummer. +
Verwende die Template-Variable *$BankCode* für E-Mail-Vorlagen, die du über die xref:crm:e-mails-versenden.adoc#1200[Mandanteneinstellungen] erstellst.

| *Bank*
|Gib den Namen der Bank ein. +
Verwende die Variable *Bankname (Stammdaten)* für E-Mail-Vorlagen, die du über den xref:crm:emailbuilder.adoc#[EmailBuilder] erstellst. Die IBAN setzt sich zusammen aus der Länderkennung (DE für Deutschland), einer Prüfziffer sowie der bisherigen Bankleitzahl und Kontonummer. +
Verwende die Template-Variable *$BankName* für E-Mail-Vorlagen, die du über die xref:crm:e-mails-versenden.adoc#1200[Mandanteneinstellungen] erstellst.

| *IBAN*
|Gib die Internationale Bankleitzahl ein. +

Verwende die Variable *IBAN (Stammdaten)* für E-Mail-Vorlagen, die du über den xref:crm:emailbuilder.adoc#[EmailBuilder] erstellst. +
Verwende die Template-Variable *$BankIban* für E-Mail-Vorlagen, die du über die xref:crm:e-mails-versenden.adoc#1200[Mandanteneinstellungen] erstellst.

|====

[#bankdaten-kunden]
== Bankdaten von Kund:innen speichern

In einem xref:crm:kontakt-bearbeiten.adoc#erlaeuterungen-einzelne-bereiche[Kontaktdatensatz] kannst du die xref:crm:kontakt-bearbeiten.adoc#bankdaten[Bankdaten der Kund:in] speichern. Die Bankdaten benötigst du z.B. für die Zahlungsart xref:payment:lastschrift.adoc#[Lastschrift]. In plentymarkets gibt es auch eine xref:payment:beta-zahlungen-verwalten.adoc#intable-import-customer-bank-data[Importfunktion] der Bankdaten. Beachte dabei jedoch die aktuelle Rechtslage, auch in anderen Lieferländern.

[.instruction]
Bankdaten der Kund:in speichern:

. Öffne das Menü *CRM » Kontakte*.
. Suche den Kontakt anhand der Filtereinstellungen. Beachte dazu die Erläuterungen zu den Filtern auf der Seite xref:crm:kontakt-suchen.adoc#[Kontakt suchen]. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicke in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicke in der Navigation auf der linken Seite auf *Bankdaten*.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<#tabelle-bankdaten-kunden-speichern>>.
. *Speichere* (material:save[]) die Einstellungen.

[[tabelle-bankdaten-kunden-speichern]]
.Bankdaten von Kund:innen speichern
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *IBAN*, *BIC*, *Inhaber:in*, *Kontonummer*, *Bankleitzahl*
|Wie lauten die Bankdaten des Kontakts? +
Die Felder *IBAN* und *Inhaber:in* sind Pflichtfelder.

| *Bankname, Straße, PLZ und Ort der Bank*
|Wie lautet der Name und die Adresse der Bank?

| *Land der Bank*
|Wähle das Land aus der Dropdown-Liste.

| *SEPA-Lastschriftmandat*
|Standardmäßig ist das SEPA-Lastschriftmandat _nicht_ aktiviert (material:toggle_off[]). Aktiviere daher die Schaltfläche (material:toggle_on[role=skyBlue]), wenn der Kontakt das SEPA-Lastschriftmandat unterschrieben hat. +
*_Wichtig:_* Erst nach dem Aktivieren dieser Option können die pain.008-Formate für den SEPA-Zahlungsverkehr abgerufen werden. Wie du SEPA-Lastschriften mit einem Prozess automatisch in eine ZIP-Datei exportieren kannst, damit du diese Datei deiner Bank zur Verfügung stellen kannst, ist auf der Handbuchseite xref:automatisierung:aktionen.adoc#410[Aktionen/Steuerelemente] im Handbuchbereich xref:automatisierung:prozesse.adoc#[Prozesse] beschrieben.

| *SEPA-Lastschriftmandat erteilt am*
|Nur sichtbar, wenn die Option *SEPA-Lastschriftmandat* aktiviert wurde (material:toggle_on[role=skyBlue]). +
Das Datum, an dem der Kontakt dem SEPA-Lastschriftmandat zugestimmt hat, wird angezeigt. Alternativ kannst du das Datum aus dem Kalender wählen (material:today[]).

| *Art des Mandats*
|Nur sichtbar, wenn die Option *SEPA-Lastschriftmandat* aktiviert wurde (material:toggle_on[role=skyBlue]). +
Wähle eine Option aus der Dropdown-Liste: +
*SEPA-Firmen-Lastschrift* = Mit dem Buchungsauftrag (Firmenkund:innen, B2B) vergleichbares Mandat. +
*SEPA-Basis-Lastschrift* = Mit der Einzugsermächtigung (Standardkund:innen) vergleichbares Mandat.

| *Ausführungsmodalität*
|Nur sichtbar, wenn die Option *SEPA-Lastschriftmandat* aktiviert wurde (material:toggle_on[role=skyBlue]). +
Wähle eine Option aus der Dropdown-Liste: +
*Einmalige Zahlung* = Wird typischerweise für Standardaufträge verwendet. +
*Wiederkehrende Zahlung* = Wird typischerweise für regelmäßige Abbuchungen, Abo-Verträge etc. verwendet.

|====

[#ebics]
== EBICS

EBICS (Electronic Banking Internet Communication Standard) bezeichnet einen in Deutschland multibankfähigen Standard für die Übertragung von Zahlungsverkehrsdaten über das Internet. Durch die Umstellung auf das standardisierte EBICS-Verfahren wird der Abruf von Zahlungen vereinfacht und einheitlich. Du kannst EBICS mit dem link:https://marketplace.plentymarkets.com/ebics_5098[EBICS^]-Plugin vollständig in dein plentymarkets System integrieren. Der Umweg über Drittanbieter ist somit nicht erforderlich.

Für die Kommunikation per EBICS werden deine Umsätze in einer Datei ähnlich einem Kontoauszug bei deiner Bank gespeichert. Die Datei wird von plentymarkets importiert und die Umsätze werden in deinem plentymarkets System gebucht. Das verknüpfte EBICS-Konto stellt eine Art Verbundkonto dar, das mehrere Bankkonten umfassen kann. Täglich wird eine Datei mit allen Umsätzen des EBICS-Kontos erzeugt (Format CAMT053 oder MT940), sofern diese bei der Bank aktiviert sind. Diese Datei kann dann nachts abgerufen werden und am nächsten Morgen stehen alle Eingänge des Tages zur Verfügung. Außerdem werden täglich mehrere Dateien mit Vormerkposten erzeugt (Format CAMT052 oder MT942), die ebenfalls abgerufen werden können, um die Vormerkposten in dein plentymarkets System einzubuchen.

EBICS wird mit dem EBICS-Plugin in dein System eingebunden. Lade dafür das EBICS-Plugin im link:https://marketplace.plentymarkets.com/ebics_5098[plentyMarketplace^] herunter. Um EBICS einzurichten, musst du einige grundlegende Einstellungen in deinem plentymarkets System ausführen. Diese Einstellungen werden in den folgenden Unterkapiteln erläutert.

////
[IMPORTANT]
.EBICS-Modul buchen
====
Um ein Konto anzulegen, muss zuerst das EBICS-Modul über den xref:business-entscheidungen:dein-vertrag.adoc#30[Konfigurator] gebucht werden.
====
////

[#70]
=== EBICS bei deiner Bank beantragen

Der erste Schritt zur Nutzung von EBICS in plentymarkets ist die Anmeldung für das Verfahren bei deiner Bank. Von deiner Bank erhältst du Dokumente, die du ausfüllst und zurückschickst. Daraufhin erhältst du von der Bank die für die Nutzung benötigten Daten wie z.B. die Bank-Kunden-ID. +
Die folgenden Angaben in den Unterlagen sind für EBICS Pflicht.

[IMPORTANT]
.Bestehende EBICS-Konten
====
Bereits bestehende und verwendete EBICS-Konten dürfen _nicht_ in plentymarkets eingerichtet werden. Ein EBICS-Konto kann mehrere Benutzer:innen haben. Benutzer:innen werden unter EBICS als Teilnehmer bezeichnet. Beantrage also ggf. einen neuen Teilnehmer (auch technische Teilnehmer möglich), den du ausschließlich für plentymarkets verwendest.
====

[#80]
==== Kontonummern

Gib die Kontonummern der Konten ein, für die der Abruf der Umsätze in plentymarkets eingebucht werden soll. Die Angabe von Kontonummern ist optional, weil der Abruf technisch über die Benutzerdaten erfolgt.

[IMPORTANT]
.Nur Geschäftskonten speichern
====
In plentymarkets besteht derzeit _keine_ Möglichkeit, einzelne Konten individuell für den EBICS-Abruf einzurichten. Das heißt, dass die Zahlungsvorgänge deiner Bank nur global für alle angegebenen Konten des plentymarkets Systems abgerufen werden können. Dazu zählen z.B. auch Zahlungsvorgänge deines Privatkontos, falls dieses gespeichert wurde. Um dies zu vermeiden, speichere nur die Kontonummern der Geschäftskonten.
====

[WARNING]
.Gleiches Konto für mehrere Benutzer:innen
====
Verweisen mehrere Benutzer:innen auch aus verschiedenen plentymarkets Systemen auf dasselbe Konto (bei vielen Banken werden mehrere Konten auch in einem Verbundskonto geführt), kann dies zu Problemen beim Abruf führen, wenn die Aufrufe parallel laufen. Dies lässt sich derzeit nicht abfangen.
====

[#90]
==== Auszugsbereitstellung

Die Auszugsbereitstellung kann entweder buchungstagsorientiert oder auszugsorientiert erfolgen.

[[table-provision-bank-statements]]
.Auszugsbereitstellung
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Buchungstagsorientiert*
|Eine fiktive fortlaufende Auszugsnummer wird mitgeliefert. Diese Einstellung ist standardmäßig voreingestellt.

| *Auszugsorientiert*
|Die effektive Auszugsnummer wird mitgeliefert. Voraussetzung hierfür ist eine tägliche automatische Auszugserstellung.
|====

[#100]
==== Teilnehmer

Bei der Umstellung deiner Konten auf EBICS erstellst du für deine Konten einen oder mehrere xref:business-entscheidungen:benutzerkonten-zugaenge.adoc#10[Benutzer:innen]. Benutzer:innen werden unter EBICS als Teilnehmer bezeichnet. Du kannst Teilnehmer mit unterschiedlichen Auftragstypen anlegen. Von diesen Teilnehmern muss ein Teilnehmer mittels der von der Bank erhaltenen *Teilnehmer-ID* im plentymarkets System gespeichert werden.

plentymarkets benötigt nur einen Teilnehmer, z.B. einen technischen Teilnehmer mit den niedrigsten Berechtigungen, um den EBICS-Zahlungsabruf durchzuführen. Pro EBICS-Konto darf nur ein Teilnehmer eingerichtet werden.

[#110]
==== Auftragstyp

In <<#table-order-signature-types>> werden die Auftragstypen erläutert, die plentymarkets für einen erfolgreichen Abruf der Buchungen deines EBICS-Kontos benötigt. Beachte zudem die Erläuterungen zu den Auftrags- und Unterschriftstypen im Formular deiner Bank.

[[table-order-signature-types]]
.Auftrags- und Unterschriftstypen
[cols="1,3"]
|====
|Typ |Erläuterung

| *STA*
|Tagesumsätze *MT940* bzw. *CAMT053*. Der <<#180, Abruf der Transaktionen>> erfolgt am Ende des Tages.

| *VMK*
|Vormerkposten *MT942* bzw. *CAMT052*. Vormerkposten der Transaktionen, die von Bank zu Bank unterschiedlich mehrmals am Tag erzeugt und zum Download bereitgestellt werden. Diese <<#190, Angabe>> ist für plentymarkets optional.

| *EU Typ „T“*
|Unterschriftstyp, der ausschließlich zum Abruf der Transaktionsdaten berechtigt.
|====

[#120]
=== EBICS-Konto anlegen

Um EBICS zu nutzen, lege zunächst ein Konto an. Gehe dazu wie im Folgenden beschrieben vor.

[.instruction]
Konto anlegen:

. Öffne das Menü *Einrichtung » Aufträge » Zahlung » Plugins » EBICS*.
. Klicke auf *Neues Konto erstellen* (material:add_box[]). +
→ Das Fenster *Neues Konto* wird geöffnet.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<#table-ebics-account-settings>>.
. *Speichere* (material:save[]) die Einstellungen. +
→ Das Konto wird erstellt.

[[table-ebics-account-settings]]
.Kontoeinstellungen für EBICS
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Aktiv*
|Aktiviere die Schaltfläche, um dieses Konto als aktiv zu markieren.

| *Kontoname*
|Gib einen internen Namen ein, unter dem das Konto in der Übersicht erscheinen soll.

| *Vorname*
|Gib den Vornamen der Kontoinhaber:in ein.

| *Nachname*
|Gib den Nachnamen der Kontoinhaber:in ein.

| *Bank-Teilnehmer-ID*
|Gib die Bank-Teilnehmer-ID ein wie von der Bank erhalten.

| *Bank-Kunden-ID*
|Gib die Bank-Kunden-ID ein wie von der Bank erhalten.

| *Bank*
|Wähle die Bank aus der Liste.

| *Bank erstellen*
|Aktiviere die Schaltfläche, um eine Bank hinzuzufügen, die nicht in der oben beschriebenen Liste aufgeführt ist. +
*Bank*: Gib die Bankparameter manuell ein wie von der Bank erhalten. +
*URL*: Gib die URL der Bank ein. +
Diese Option ist nur beim Erstellen eines Kontos verfügbar.

| *Accountversion*
|Wähle aus der Dropdown-Liste, welche Accountversion verwendet werden soll. Details dazu erhältst du von deiner Bank.

| *EBICS-Version*
|Wähle aus der Dropdown-Liste, welche EBICS-Version die Bank verwendet. Details dazu erhältst du von deiner Bank.

| *Vormerkposten*
|Wähle aus der Dropdown-Liste, mit welchem Verfahren die Vormerkposten abgerufen werden sollen. Details dazu erhältst du von deiner Bank.

| *Tagesumsätze*
|Wähle aus der Dropdown-Liste, mit welchem Verfahren die Tagesumsätze abgerufen werden sollen. Details dazu erhältst du von deiner Bank.

| *IBAN/Kontonummer*
|Gib die IBANs bzw. Kontonummern der verknüpften Konten kommasepariert ein. Das CAMT-Format benötigt die Eingabe der IBAN, das MT-Format benötigt die Eingabe der Kontonummer.

|====

[#130]
==== Einstellungen am EBICS-Konto vornehmen

Nachdem das Konto angelegt wurde, kann es aus der Kontoübersicht bearbeitet werden. Mit einem eingerichteten Konto stehen dir verschiedene Funktionen zur Verfügung. Diese werden im Folgenden erläutert. Des Weiteren wird neben dem Konto der Log mit Meldungen für dieses individuelle Konto angezeigt.

[.instruction]
Konto bearbeiten:

. Öffne das Menü *Einrichtung » Aufträge » Zahlung » Plugins » EBICS*.
. Klicke auf *Bearbeiten*, um das Konto zu öffnen. +
→ Das Fenster *Kontoeinstellungen* wird geöffnet.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<#table-ebics-settings>>.
. *Speichere* (material:save[]) die Einstellungen.

[IMPORTANT]
.Domainwechsel
====
Speichere nach einem xref:business-entscheidungen:domains.adoc#[Domainwechsel] die Grundeinstellungen des Kontos erneut, um die EBICS-Daten zu aktualisieren.
====

[[table-ebics-settings]]
.Einstellungen für EBICS
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Kontoeinstellungen*
|Die Einstellungen des ausgewählten Kontos.

| *Geschäftsvorfälle*
|Verwaltet die automatisch abgerufenen Geschäftsvorfälle.

| *Manueller Zahlungsabruf*
|Ermöglicht im Falle eines technischen Fehlers den manuellen Abruf aller Aufträge zu einem bestimmten Datum. +
*_Hinweis:_* Diese Funktion ruft lediglich die im System vorhandenen Daten noch einmal ab. Es findet _kein_ erneuter Abgleich mit der Bank statt.

| *Status abrufen*
|Ruft den aktuellen Initialisierungsstatus des Kontos vom EBICS-Tool ab.

| *Auftragsarten abrufen*
|Ruft die auf dem Konto verfügbaren Auftragsarten ab. Es handelt sich dabei um die Arten, die gerade auf dem Server verfügbar sind. +
*_Achtung:_* Wenn du diese Funktion zu häufig nutzt, kann es zu Fehlfunktionen kommen.

| *Konto initialisieren*
|Die Schlüssel werden generiert und mittels INI zum Abgleich an die Bank übermittelt. HIA wird ausgeführt.

| *INI-Brief*
|Erstellt aus den generierten Schlüsseln einen INI-Brief als PDF und lädt das Dokument herunter. Dieser Brief muss ausgedruckt und an die Bank geschickt werden. Die Schaltfläche ist inaktiv, bis die Schlüssel erfolgreich erstellt wurden. +
*_Hinweis:_* Für den fehlerfreien Download des INI-Briefs musst du den den Pop-up-Blocker deines Browsers deaktivieren.

| *Initialisierung abschließen (HPB)*
|Schließt den Initialisierungsvorgang mit der Bank ab.

| *Experten-Modus*
|Alle folgenden Schaltflächen sind ausschließlich für den Fall vorgesehen, dass die Bank eine erneute Ausführung anfordert, und stehen erst nach Aktivierung der Schaltfläche zur Verfügung. +
*_Wichtig:_* Die Nutzung des Expertenmodus kann dein EBICS-Konto außer Kraft setzen, sodass es durch das Kreditinstitut zurückgesetzt werden muss. Nutze diese Funktionen ausschließlich, wie von deinem Kreditinstitut gefordert.

| *Schlüssel erstellen*
|Erstellt die Schlüssel für die Initialisierung.

| *INI*
|Initialisiert das EBICS-Konto.

| *HIA*
|Führt HIA aus.

| *HPB*
|Führt HPB aus.

|====

[IMPORTANT]
.Änderungen nur nach Rücksprache mit der Bank
====
Nimm Änderungen nur nach Rücksprache mit deiner Bank vor. Wenn du z.B. die neuen CAMT-Formate nutzen möchtest, kläre mit deiner Bank, ob das Format unterstützt wird und lasse das Format aktivieren. Passe dann die Kontoeinstellungen und ggf. die Vormerkposten wie hier beschrieben an.

Wenn ein Konto zurückgesetzt wurde und deine Bank neue Schlüssel benötigt, empfehlen wir, den betreffenden EBICS-Account in plentymarkets neu einzurichten, weil nur dann neue Schlüssel erzeugt werden.
====

[#140]
==== Konto initialisieren

Nachdem du die Zugangsdaten in plentymarkets eingegeben hast, meldet sich plentymarkets auf elektronischem Weg bei deiner Bank an. Für einen EBICS-Abruf sind geheime Schlüsselwerte erforderlich, die programmintern generiert werden. +
Nachdem die Schlüssel erzeugt wurden und die elektronische Erstanmeldung abgeschlossen ist, müssen die Schlüssel unterschrieben und in ausgedruckter Form an die Bank geliefert werden. +
*_Beachte:_* Nur der in plentymarkets gespeicherte Teilnehmer ist zu dieser Unterschrift berechtigt. Die Bank wird _keine_ Freigabe der EBICS-Schnittstelle erteilen, wenn die Unterschrift nicht von genau diesem gespeicherten Teilnehmer stammt.

[TIP]
.Pop-up-Blocker im Browser
====
Für den fehlerfreien Download des INI-Briefs musst du den Pop-up-Blocker deines Browsers deaktivieren.
====

[.instruction]
Konto initialisieren:

. Öffne das Menü *Einrichtung » Aufträge » Zahlung » Plugins » EBICS*.
. Klicke auf der Karte des Kontos, das du initialisieren möchtest, auf *Bearbeiten*. +
→ Das Tab *Kontoeinstellungen* wird geöffnet.
. Klicke auf *Konto initialisieren*. +
→ Die Schlüssel werden generiert. INI und HIA werden ausgeführt. +
→ Wenn alle Vorgänge erfolgreich abgeschlossen sind, wird die Schaltfläche *INI-Brief erstellen* aktiviert.
. Klicke auf *INI-Brief erstellen*. +
→ Der INI-Brief wird als PDF-Dokument heruntergeladen.
. Unterschreibe den INI-Brief und übermittele ihn an deine Bank. +
→ Die Bank prüft die Daten und gibt das Konto frei. Du erfährst von deiner Bank, wann dieser Vorgang abgeschlossen ist.
. Klicke auf *Initialisierung abschließen (HPB)*. +
→ Das Konto ist erfolgreich initialisiert.

Wenn alle Werte bei der Bank eingegangen sind, werden die ausgedruckten Werte mit den elektronisch gesendeten Werten verglichen und die EBICS-Schnittstelle wird freigegeben. Ab diesem Moment werden die Transaktionen in den <<#150, unten beschriebenen Intervallen>> abgerufen.

[#150]
=== Abrufintervalle für Transaktionen

Deine Bank stellt maximal zweimal täglich die Transaktionen des jeweiligen Tages in Datenform zur Abholung bereit. plentymarkets ruft die Daten aktuell um 6:00 Uhr, um 13:00 Uhr und um 23:00 Uhr ab. Die Transaktionsdaten sind etwa eine Stunde nach Abruf in den Systemen verfügbar. Zudem stellt die Bank mehrmals am Tag Vormerkposten mit den Transaktionen des aktuellen Tages in Datenform zur Abholung bereit.

[#160]
=== Abrufintervalle Vormerkposten

Weil die Zeiten, in denen die Vormerkposten bereitgestellt werden, von Kreditinstitut zu Kreditinstitut unterschiedlich sind, ruft plentymarkets die Daten, falls verfügbar, zwischen 8:00 und 18:00 stündlich von den Kreditinstituten ab. Bei EBICS-Buchungen mit unbestätigtem Vormerkposten wird die Angabe *Vormerkposten* in roter Schrift dargestellt. Wird der Vormerkposten bestätigt, wechselt der Schriftzug von rot auf grün. Zusätzlich wird die bestätigte Buchung dem entsprechenden Auftrag zugeordnet, ohne die Zahlung nochmals zu buchen. Damit Vormerkposten bestätigt werden, ist die Aktivierung der Tagesumsätze erforderlich. Beachte dazu die Erläuterungen in <<#table-ebics-settings>>.

[#170]
=== Geschäftsvorfälle verwalten

Geschäftsvorfälle sind die bankfachlichen Auftragsarten, die du mit deinem Kreditinstitut abwickelst. Nach dem Anlegen sind noch keine Geschäftsvorfälle aktiviert. Aktiviere für den automatischen Import und die Zuordnung der üblichen Geschäftsvorfälle die folgenden Standardgeschäftsvorfälle:

* 005 – Lastschrift (Einzugsermächtigungsverfahren)
* 006 – Sonstige Einzugspapiere
* 020 - Überweisung
* 051 - Überweisungsgutschrift
* 052 – Dauerauftragsgutschrift
* 063 – GS EU-Standardüberweisung
* 065 – Überweisungsgutschrift (Ausl.-Überweisung ohne Meldeteil)
* 070 – Scheckeinreichung
* 088 – Überweisungsgutschrift P1 DTE
* 104 - SEPA Direct Debit (Einzelbuchung-Soll, B2B)
* 105 - SEPA Direct Debit (Einzelbuchung-Soll, Core)
* 106 – SEPA Cards Clearing (EB-Soll)
* 107 – SEPA Direct Debit (EB, Karte am Point of Sale)
* 152 – SEPA-Dauerauftragsgutschrift
* 159 – SEPA Credit Transfer Retoure (Haben) für unanbringliche Über
* 166 - SEPA Credit Transfer (Einzelbuchung-Haben)
* 169 – SEPA Credit Transfer (EB Haben Spende)
* 181 – SEPA Direct Debit (Haben; Wiedergutschrift)
* 184 – SEPA Direct Debit (Haben; Wiedergutschrift, B2B)
* 201 – Zahlungsauftrag
* 202 – Auslandsvergütung
* 206 – Auslandsüberweisung
* 211 – Zahlungseingang über elektronische Medien

[.instruction]
Geschäftsvorfälle verwalten:

. Öffne das Menü *Einrichtung » Aufträge » Zahlung » Plugins » EBICS*.
. Klicke auf der Karte des Kontos, das du verwalten möchtest, auf *Bearbeiten*. +
→ Das Fenster *Kontoeinstellungen* wird geöffnet.
. Klicke auf *Geschäftsvorfälle*.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<#table-ebics-settings-transactions>>.
. *Speichere* (material:save[]) die Einstellungen.

[[table-ebics-settings-transactions]]
.Einstellungen für Geschäftsvorfälle vornehmen
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Code*
|Gib den Code eines spezifischen Geschäftsvorfalls ein und klicke auf *Suchen*.

| *Bezeichnung*
|Gib die Beschreibung eines spezifischen Geschäftsvorfalls ein und klicke auf *Suchen*.

| *Anzeigen*
|Standardmäßig werden nur aktive Geschäftsvorfälle angezeigt. +
*Alle*: Zeigt eine Liste mit allen Geschäftsvorfällen. +
*Nur aktive*: Zeigt alle aktivierten Geschäftsvorfälle. +
*Nur inaktive*: Zeigt alle nicht aktivierten Geschäftsvorfälle.

| *Gruppe*
| *Alle*: Zeigt eine Liste mit allen Geschäftsvorfällen. +
*Credit*: Zeigt alle Geschäftsvorfälle vom Typ Credit. +
*Debit*: Zeigt alle Geschäftsvorfälle vom Typ Debit.

|====

[#180]
==== Inaktive Geschäftsvorfälle laden

Wenn auf deinem Konto Zahlungen eingehen, deren Geschäftsvorfall du nicht aktiviert hast, können diese vom EBICS-Plugin nicht erfasst werden. Füge diese Geschäftsvorfälle deinem Konto hinzu.

[.instruction]
Inaktive Geschäftsvorfälle laden:

. Öffne das Menü *Einrichtung » Aufträge » Zahlung » Plugins » EBICS*.
. Klicke auf der Karte des Kontos, das du bearbeiten möchtest, auf *Bearbeiten*. +
→ Das Fenster *Kontoeinstellungen* wird geöffnet.
. Klicke auf *Geschäftsvorfälle*.
. Klicke auf *Inaktive Geschäftsvorfälle laden*. +
→ Das Fenster zur Suche wird geöffnet.
. Gib das Datum ein, für das du die Geschäftsvorfälle laden möchtest.
. Klicke auf *Suchen*. +
→ Alle Zahlungen des eingegebenen Tages, für die keine Geschäftsvorfälle aktiv sind, werden angezeigt.
. Wähle die Geschäftsvorfälle, die du aktivieren möchtest.
. *Speichere* (material:save[]) die Einstellungen. +
→ Die Geschäftsvorfälle sind aktiviert.

Um die Zahlungen zuzuordnen, muss für dieses Datum ein manueller Zahlungsabruf wie in <<#table-ebics-settings>> beschrieben durchgeführt werden. Alle zukünftigen Zahlungen werden automatisch zugeordnet.

[#190]
==== Noch nicht verwendete Geschäftsfälle hinzufügen

Wenn Zahlungen unter einem Geschäftsvorfallcode eingehen, der nicht aktiv ist, wird dieser automatisch zur globalen Liste der Geschäftsvorfälle hinzugefügt und kann von dort aus <<#170, wie oben>> beschrieben aktiviert werden.

[#200]
=== Alte Integration migrieren

Wenn du die bisherige EBICS-Integration nutzt, kannst du deine vorhandenen Konten in das neue Plugin überführen. Führe dafür die folgenden Schritte durch.
Der Button für die Migration wird nur angezeigt, wenn Konten in der alten Integration vorhanden, aktiv und vollständig durch die Bank freigeschaltet sind.

[.instruction]
Migration durchführen:

. Öffne das Menü *Einrichtung » Aufträge » Zahlung » Plugins » EBICS*.
. Klicke auf *Migration von bestehenden EBICS-Konten*. +
→ Alle Daten der alten Integration werden ins Plugin migriert. +
→ Der Button wird ausgeblendet. +
→ Die Konten werden im Plugin aktiviert. +
. Deaktiviere die Konten in der alten Integration.
. Aktiviere die Geschäftsvorfälle in den Konten im Plugin <<#170, wie oben>> beschrieben.

[#220]
== SEPA-Lastschriftmandat einrichten

Im Rahmen der SEPA-Initiative (Single Euro Payments Area) ist der Euro-Zahlungsverkehr in Deutschland und 35 weiteren europäischen Staaten seit dem 1. Februar 2014 vereinheitlicht. Seit diesem Stichtag sind Überweisungen und Lastschriften nur noch mit IBAN und BIC möglich. Lastschriften werden unterteilt in:

* *SEPA-Basis-Lastschrift* → vergleichbar mit einer Einzugsermächtigung
* *SEPA-Firmenlastschrift* → vergleichbar mit einem Abbuchungsauftrag

Firmenlastschriften sind nur zwischen Unternehmen zulässig (B2B) und benötigen gesonderte Mandate. Von deinen Kund:innen benötigst du ein SEPA-Lastschriftmandat, das die bisherige Einzugsermächtigung ersetzt. Das Mandat bildet die rechtliche Grundlage zum Einzug von SEPA-Lastschriften.

[#230]
=== Dokumentenvorlage erstellen

Im Menü *Einrichtung » Aufträge » Dokumente* gibt es im Untermenü *SEPA-Lastschriftmandat* eine Vorlage für das SEPA-Lastschriftmandat. Weitere Informationen zu Dokumenten findest du auf der Handbuchseite zum Thema xref:auftraege:auftragsdokumente.adoc#[Dokumentenvorlagen].

[.instruction]
Dokumentenvorlage einrichten:

. Öffne das Menü *Einrichtung » Mandant » [Mandant wählen] » Standorte » [Standort wählen] » Dokumente*.
. Klicke auf die Vorlage *SEPA-Lastschriftmandat*. +
→ Das Tab *Vorlage* wird geöffnet.
. Wähle eine *Sprache* aus der Dropdown-Liste.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<#tabelle-einrichtung-dokumentenvorlage>>.
. *Speichere* (material:save[]) die Einstellungen.

[[tabelle-einrichtung-dokumentenvorlage]]
.Dokumentenvorlage einrichten
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+^|Informationen des Zahlungsempfängers

| *Name des Zahlungsempfängers; +
Straße und Hausnummer; +
Postleitzahl und Ort; +
Land*
|Gib die Daten der Händler:in ein.

| *Gläubiger-Identifikationsnummer*
|Gib die Gläubiger-Identifikationsnummer ein.

| *Mandatsreferenz*
|Die Mandatsreferenz wird aus der Kunden-ID generiert und automatisch gespeichert.

| *Zahlungsart*
|Gib die Ausführungsmodalität ein. Gib entweder *Einmalige Zahlung* oder *Wiederkehrende Zahlung* ein.

| *Name des Zahlungspflichtigen*
|Der Name wird automatisch aus den gespeicherten Bankdaten gezogen. Wenn dort keine Daten gespeichert, wird der am xref:crm:kontakt-bearbeiten.adoc#kontaktdetails[Kontaktdatensatz] gespeicherte Name genommen.

2+^|Formatierung

| *X-Achse;  +
Y-Achse*
|Die Werte orientieren sich am Koordinatensystem mit X- und Y-Achse. Die X-Achse verläuft von links nach rechts und die Y-Achse von oben nach unten. Die Nullpunkte liegen also links oben. Weitere Informationen zum Koordinatensystem findest du im Kapitel <<#230, Dokumentenvorlage erstellen>>.

| *Schriftgröße*
|Wähle die Schriftgröße in Pixeln.

| *Hervorhebung*
|Wähle *Normal* oder *Fett*.

| *Informationen des Zahlungspflichtigen*
|Die Informationen werden aus dem Kontaktdatensatz geladen und automatisch gespeichert. Damit IBAN und BIC in der Vorlage für das SEPA-Lastschriftmandat ausgegeben werden, müssen sie im Kontaktdatensatz im Bereich xref:crm:kontakt-bearbeiten.adoc#bankdaten[Bankdaten] gespeichert sein.

| *Alle Seiten der Vorlage ausgeben*
|Wähle, ob alle Seiten der Vorlage ausgegeben werden sollen.

| *Zeichensatz*
|Wähle *ISO-8859-1* oder *Unicode*. +
*_Hinweis:_* Das Generieren von PDF-Dokumenten in Unicode kann länger dauern.
|====

[#240]
=== PDF-Vorlage hochladen

Im Tab *PDF-Vorlage* lädst du eine PDF-Vorlage hoch, die das Layout deines Briefkopfes mit Firmendaten und Logo deines Unternehmens beinhaltet. Füge bei der Gestaltung der PDF-Vorlage die erforderlichen Feldnamen für die Werte der Vorlage und im unteren Bereich ein Unterschriftenfeld mit einer Linie für die Unterschrift der Kund:in ein.

[IMPORTANT]
.Felder in der PDF-Vorlage einfügen
====
Die Feldnamen für die Werte der Vorlage, z.B. IBAN, BIC oder Zahlungsart werden nicht über die Dokumentenvorlage ausgegeben. Speichere die Feldnamen fest in der PDF-Vorlage.
====

[.instruction]
PDF-Vorlage hochladen:

. Öffne das Menü *Einrichtung » Mandant » [Mandant wählen] » Standorte » [Standort wählen] » Dokumente*.
. Klicke auf die Vorlage *SEPA-Lastschriftmandat*. +
→ Das Tab *Vorlage* wird geöffnet.
. Wähle eine *Sprache* aus der Dropdown-Liste.
. Wechsle in das Tab *PDF-Vorlage » Tab: Neue Vorlage*.
. Klicke auf *Durchsuchen...*. +
→ Das Fenster *Datei hochladen* wird geöffnet.
. Öffne die PDF-Datei.
. *Speichere* (material:save[]) die Einstellungen.

[#250]
=== E-Mail-Vorlage erstellen

Um deinen Kund:innen direkt nach dem Einkauf im Webshop das SEPA-Lastschriftmandat zur Verfügung zu stellen, erstelle eine E-Mail-Vorlage mit dem SEPA-Lastschriftmandat als Anhang. Richte zum Versand der E-Mail eine <<#260, Ereignisaktion>> ein.

[.instruction]
E-Mail-Vorlage erstellen:

. Öffne das Menü *Einrichtung » Mandant » [Mandant wählen] » E-Mail » Vorlagen*.
. Wechsle in das Tab *Neue E-Mail-Vorlage*.
. Gib einen *Namen* ein und wähle unter *PDF-Anhang* die Option *SEPA-Lastschriftmandat*.
. Gib im Tab *E-Mail-Nachricht* einen Text ein, der die Kund:in darüber informiert, dass das angehängte SEPA-Lastschriftmandat mit Unterschrift zurückgeschickt werden muss.

[#260]
=== E-Mail-Vorlage per Ereignisaktion versenden

Die E-Mail-Vorlage an deine Kund:innen versendest du z.B. durch eine xref:automatisierung:ereignisaktionen.adoc#[Ereignisaktion], die durch einen neuen Auftrag ausgelöst wird.

:table-event-procedure: <<event-procedure-send-sepa-to-customer>>
include::_includes:partial$event-procedure.adoc[]

[[event-procedure-send-sepa-to-customer]]
.Ereignisaktion zum automatischen Senden von SEPA-Lastschriftmandaten an Kund:innen
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

| *Ereignis*
| *Auftragsanlage: Neuer Auftrag*
|

| *Filter 1*
| *Auftrag &gt; Auftragstyp*
| *Auftrag*

| *Filter 2*
| *Auftrag &gt; Zahlungsart*
| *Lastschrift*

| *Aktion*
| *Kunde &gt; E-Mail versenden*
| *Vorlage für SEPA-Lastschriftmandat; +
Kunde*
|====

[#270]
=== E-Mail-Vorlage per  Gruppenfunktion versenden

Die E-Mail-Vorlage kannst du alternativ auch in der *Kontaktübersicht* über die Gruppenfunktion versenden.

[.instruction]
E-Mail-Vorlage versenden:

. Öffne das Menü *CRM » Kontakte*.
. Suche den Kontakt anhand der Filtereinstellungen. Beachte dazu die Erläuterungen zu den Filtern auf der Seite xref:crm:kontakt-suchen.adoc#[Kontakt suchen]. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Wähle (material:check_box[role=skyBlue]) die Kontakte, an die du die E-Mail-Vorlage senden möchtest. 
. Klicke in der Symbolleiste oben auf *E-Mail-Vorlage senden* (material:forward_to_inbox[]). +
→ Das Fenster *E-Mail-Vorlage senden* öffnet sich.
. Wähle die zuvor erstellte E-Mail-Vorlage zur SEPA-Information aus der Dropdown-Liste.
. Klicke auf *Ausführen*. +
→ Die E-Mail-Vorlage wird an die gewählten Kontakte gesendet.

Weitere Details dazu findest du im Kapitel xref:crm:kontakt-bearbeiten.adoc#gruppenfunktion[Gruppenfunktion nutzen] auf der Handbuchseite xref:crm:kontakt-bearbeiten.adoc#[Kontakt bearbeiten].

[#280]
=== SEPA-Zahlungsverkehr in den Bankdaten aktivieren

Wenn du das unterschriebene SEPA-Lastschriftmandat einer Kund:in erhalten hast, ist die im Folgenden beschriebene Einstellung erforderlich, um den SEPA-Zahlungsverkehr zu aktivieren und die pain008-Formate abzurufen.

[.instruction]
SEPA-Lastschriftmandat in den Bankdaten aktivieren:

. Öffne das Menü *CRM » Kontakte*.
. Suche den Kontakt anhand der Filtereinstellungen. Beachte dazu die Erläuterungen zu den Filtern auf der Seite xref:crm:kontakt-suchen.adoc#[Kontakt suchen]. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicke in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicke in der Navigation auf der linken Seite auf *Bankdaten*.
. Aktiviere (material:toggle_on[role=skyBlue]) *SEPA-Lastschriftmandat*.
. *Speichere* (material:save[]) die Einstellungen.

Weitere Informationen zu Bankdaten findest du im Kapitel <<#bankdaten-kunden, Bankdaten von Kund:innen speichern>>.

[#290]
=== SEPA-Zahlungsverkehr automatisieren

Du hast die Möglichkeit, Prozesse einzurichten, um deine SEPA-Zahlungsprozesse zu automatisieren. Dazu findest du im Menü *Einrichtung » Prozesse* die entsprechenden Aktionen xref:automatisierung:aktionen.adoc#400[SEPA Pain001] und xref:automatisierung:aktionen.adoc#410[SEPA Pain008].
