= Probleme mit Payment Plugins
:keywords: payment plugin, payment-plugin, Zahlungsplugin, Zahlungs-Plugin, Zahlungplugin, Zahlung-Plugin
:description: Wie du Probleme mit den Payment-Plugins lösen kannst.
:author: team-fulfillment-payment

Zahlungsarten wie zum Beispiel xref:payment:paypal.adoc#[PayPal], xref:payment:mollie.adoc#[Mollie] oder xref:payment:klarna.adoc#[Klarna] werden über Plugins in dein System eingebunden. Durch das Durchlaufen des dazugehörigen Assistenten werden die Zahlungsarten eingerichtet und sind dann in deinem System verfügbar. +
Hin und wieder kommt es zu Konfigurationsfehlern in diesem Prozess. Die folgende Checkliste soll dir helfen, mögliche Fehlerquellen selbst zu finden und zu beheben.

Überprüfe die folgenden Einstellungen, wenn es ein Problem mit einem Payment Plugin gibt:

[%interactive]
* [ ] Ist das Plugin korrekt xref:plugins:hinzugefuegte-plugins-installieren.adoc#[installiert und bereitgestellt]?
* [ ] Wurde IO die höchste Positionsnummer im Plugin-Set zugewiesen?
* [ ] Ist das Plugin im Hauptmandanten installiert und bereitgestellt?
* [ ] Befindet sich das Plugin in der aktuellsten Version? +
→ Überprüfe dies anhand des Changelogs. Diesen findest du im Tab *Changelog* des jeweiligen Plugins auf dem link:https://marketplace.plentymarkets.com/plugins/payment/payment-integrationen[plentyMarketplace^]. Hier als Beispiel der link:https://marketplace.plentymarkets.com/paypal_4690[Changelog von PayPal].
* [ ] Wurde der Assistent korrekt durchlaufen?
* [ ] Sind die Zugangsdaten korrekt eingegeben worden?
* [ ] Ist der richtige Modus ausgewählt worden? +
→ Es wird unterschieden zwischen Live- bzw. Produktivmodus und Testmodus. Wähle Live- bzw. Produktivmodus aus, um eine Zahlungsart nutzen zu können.
* [ ] Ist die Zahlungsart in der Kundenklasse erlaubt? +
→ Damit eine Zahlungsart für eine Kundenklasse verwendet werden kann, muss sie in der Kundenklasse erlaubt werden. Überprüfe dies im Menü *Einrichtung » CRM » Kundenklassen* im Bereich *Erlaubte Zahlungsarten*.
* [ ] Ist die Zahlungsart in den Versandprofilen freigegeben? +
→ Zahlungsarten können in Versandprofilen gesperrt werden. Möchtest du eine Zahlungsart für ein Versandprofil nutzen, überprüfe im Menü *Einrichtung » Aufträge » Versand » Optionen* im Bereich *Gesperrte Zahlungsarten* des Tabs *Versandprofile*, ob die Zahlungsart nicht gesperrt ist.

Konntest du alle Punkte abhaken, sollte es keine Probleme mit der Zahlungsart geben. Falls du immer noch auf Schwierigkeiten stößt, findest du weitere Informationen zu jeder Plugin-Zahlungsart im Handbuchbereich xref:payment:payment-plugins.adoc#[Payment Plugins] oder du fragst unsere Supporter im link:https://forum.plentymarkets.com/[Forum].
