= Kauf auf Rechnung
:keywords: Zahlungsarten, Rechnung, Rechnungskauf, Kauf auf Rechnung, Rechnungs-Plugin, Rechnungs-Assistent, Rechnungsassistent, invoice-plugin, invoice, Rechnungszahlung, Rechnungs-Zahlung, Rechnungsschnittstelle, Zahlungsplugin, Zahlungs-Plugin, Payment-Plugin, Paymentplugin, Payment-Integration, Paymentintegration, Paymentschnittstelle, Payment-Schnittstelle, Zahlart, Zahlarten, Zahlart, Zahlarten
:description: Erfahre mehr über die Integration des Plugins Kauf auf Rechnung.
:author: team-fulfillment-payment

Mit dem Kauf auf Rechnung-Plugin bindest du die Zahlungsart *Rechnung* in deinen Webshop ein und stellst sie so deinen Kund:innen zur Auswahl. Lade dafür das Kauf auf Rechnung-Plugin im link:https://marketplace.plentymarkets.com/invoice_4760[plentyMarketplace^] herunter. Die Einrichtung der Zahlungsart erfolgt über einen Assistenten. Zudem musst du einige grundlegende Einstellungen in deinem plentymarkets System ausführen, damit die Zahlungsart auch in deinem System aktiviert ist. +
Die Erklärungen auf dieser Seite finden nach dem Hinzufügen des Plugins Anwendung. Allgemeine Informationen zum Hinzufügen und Installieren von Plugins findest du im Abschnitt xref:plugins:plugins.adoc#[Plugins] des Handbuchs.

[#10]
== Ausführen des Assistenten

:name-des-assistenten: Kauf auf Rechnung
:name-der-zahlungsart: Kauf auf Rechnung

include::_includes:partial$assistant-payment-processing.adoc[]

[#30]
== Kundenklassen und Versandprofile

include::_includes:page$kundenklassen-und-versandprofile.adoc[]

[#40]
== Sprachelemente anpassen

Du kannst Benennungen, die das Kauf auf Rechnung-Plugin mitbringt, im Menü *CMS » Mehrsprachigkeit* nach deinen Bedürfnissen in allen verfügbaren Systemsprachen anpassen. Gehe dazu wie im Folgenden beschrieben vor.

[.instruction]
Sprachdateien anpassen:

. Öffne das Menü *CMS » Mehrsprachigkeit.*
. Wähle auf der linken Seite die *Ausgangssprache* aus der Dropdown-Liste.
. Wähle auf der rechten Seite die *Zielsprache* aus der Dropdown-Liste.
. Klappe im Bereich *Invoice* die Sektionen *Bankdaten*, *Verwendungszweck* und *Zahlungsart* aus.
. Gib im Bereich der Zielsprache die gewünschten Texte für die einzelnen Sprachelemente ein.
. Speichere (material:save[]) die Einstellungen.
. Stelle das Plugin-Set erneut bereit, um die Änderungen zu übernehmen.

Über die Auswahl *Deutsch* als *Zielsprache*, kannst du die deutschen Benennungen für deinen Webshop anpassen. Die gewählten Benennungen werden dann auch im Backend übernommen, allerdings bleibt der Zusatz _Plugin_. So bleibt die Zugehörigkeit einer Zahlungsart nachvollziehbar. Lade das Backend neu, um die Änderungen sehen zu können.
Weitere Informationen zum Bearbeiten von im Webshop angezeigten Texten findest du auf der Handbuchseite xref:webshop:ceres-einrichten.adoc#231[Webshop-Texte bearbeiten].

[#50]
== Rechnungsdokument

Rechnungen kannst du manuell oder automatisch über eine xref:automatisierung:ereignisaktionen.adoc#events-documents[Ereignisaktion] erzeugen. Wichtig ist für beide Vorgehensweisen, dass du vorher eine xref:auftraege:auftragsdokumente.adoc#300[Dokumentenvorlage] eingerichtet hast. Mehr Informationen zum Rechnungsdokument findest du im Handbuchabschnitt xref:auftraege:rechnungen-erzeugen.adoc#[Rechnungen].
