= Payment Assistent wird nicht angezeigt
:keywords: payment assistent, payment-assistent, Zahlungsassistent, Zahlung-Assistent
:page-aliases: fehlender-payment-assistent.adoc
:id: P7ZKQZK
:author: team-order-payment

Du hast ein Payment-Plugin über den link:https://marketplace.plentymarkets.com/plugins/payment/payment-integrationen[plentyMarketplace^] heruntergeladen und siehst nun den dazugehörigen Assistenten nicht, um die Zahlungsart einzurichten? Beachte zunächst, dass es einige Minuten dauern kann, bis der Assistent im System angezeigt wird. Siehst du den Assistenten dann immer noch nicht, überprüfe die folgenden Punkte:

[%interactive]
* [ ] Ist das Plugin korrekt xref:plugins:hinzugefuegte-plugins-installieren.adoc#[installiert und bereitgestellt]?
* [ ] Ist das Plugin im Hauptmandanten installiert und bereitgestellt?
* [ ] Sind nach der Installation und Bereitstellung des Plugins der Cache und die Cookies des Browsers gelöscht worden?
* [ ] Überprüfe, ob das Plugin-Set, in dem die Zahlungsart installiert ist, auch das aktive Plugin-Set ist.

Falls du immer noch auf Schwierigkeiten stößt, kannst du unsere Supporter im link:https://forum.plentymarkets.com/[Forum] um Hilfe bitten.
