= Payment Plugins
:keywords: Payment, Payment-Plugin, Payment Plugin, Plugin-Zahlungsart, Zahlungsart, Zahlart, Zahlarten, Zahlmittel, Zahlungsmittel
:description: Erfahre mehr über die Payment Plugins in plentymarkets.
:author: team-fulfillment-payment

In diesem Bereich werden die von plentymarkets entwickelten Payment Plugins beschrieben. Auf jeder Seite findest du einen Link zum Download des Plugins, eine Einrichtungsanleitung sowie relevante Informationen. Der Download der Plugins findet über den link:https://marketplace.plentymarkets.com/plugins/payment/payment-integrationen[plentyMarketplace^] statt.

Von plentymarkets entwickelte Payment-Integrationen:

* xref:payment:barzahlung.adoc#[Barzahlung]
* xref:payment:ebics.adoc#[EBICS]
* xref:payment:kauf-auf-rechnung.adoc#[Kauf auf Rechnung]
* xref:payment:klarna.adoc#[Klarna]
* xref:payment:lastschrift.adoc#[Lastschrift]
* xref:payment:mollie.adoc#[Mollie]
* xref:payment:nachnahme.adoc#[Nachnahme]
* xref:payment:payone.adoc#[PAYONE]
* xref:payment:paypal.adoc#[PayPal]
* xref:payment:sofort.adoc#[Sofortüberweisung von Klarna]
* xref:payment:vorkasse.adoc#[Vorkasse]

[IMPORTANT]
.Plugins im Hauptmandanten
====
Plugins mit Backend-Funktionen, wie zum Beispiel Ereignisaktionen, müssen immer auch im Hauptmandanten installiert werden. Zusätzlich muss eine Installation in dem Plugin-Set erfolgen, in dem die Zahlungsart verwendet werden soll. Dort muss das Plugin dann auch aktiviert werden.
====

Generell gilt, dass das Plugin-Set, in dem eine Zahlungsart eingebunden ist, nach Anpassungen oder Aktualisierungen am Zahlungart-Plugin neu bereitgestellt werden sollte. Wie man ein Plugin aktualisiert erfährst du auf der Handbuchseite xref:plugins:installierte-plugins-aktualisieren.adoc#[Installierte Plugins aktualisieren]. +
Wird etwas nicht korrekt angezeigt oder gibt es ansonsten Probleme mit einer Zahlungsart, kann es zudem helfen, den Assistenten erneut zu durchlaufen. Auch danach empfiehlt es sich, das entsprechende Plugin-Set neu zu bauen.
