= Payment
:keywords: Payment, Zahlungen, Zahlungen verwalten, Bankverkehr, Zahlungsarten, Zahlungsanbieter
:description: Zahlungen verwalten und Schnittstellen zu Zahlungsarten und Zahlungsanbietern einrichten.
:author: team-fulfillment-payment

Ein wichtiges Merkmal im Verkauf sind die angebotenen Zahlungsarten. Wenn hier die richtige Auswahl fehlt, kann es passieren, dass Kund:innen am Ende des Bestellvorgangs den Kauf abbrechen oder gar nicht erst in deinem Webshop kaufen. +
Um dies zu verhindern, solltest du herausfinden, welche Zahlungsarten von deiner Zielgruppe bevorzugt genutzt werden. Im Themenbereich Payment wird beschrieben, wie du Zahlungsarten und Zahlungsanbieter in plentymarkets einrichtest und verwaltest. Zudem werden die Funktionen und der Umgang mit Zahlungen, Währungen und Bankdaten beschrieben.

[.row]
====
[.col-md-6]
.Zahlungsarten verwalten
=====
* xref:payment:zahlungsarten-verwalten.adoc#[Zahlungsarten verwalten]
* xref:payment:zahlungsarten-verwalten.adoc#25[Standard-Zahlungsart festlegen]
* xref:payment:zahlungsarten-verwalten.adoc#30[Zahlungsart in Kundenklasse erlauben]
* xref:payment:zahlungsarten-verwalten.adoc#50[Rabatt auf Zahlungsart gewähren]
* xref:payment:zahlungsarten-verwalten.adoc#65[Übersicht der Zahlungsarten im System]
* xref:payment:zahlungsarten-verwalten.adoc#70[Marktplatz-Zahlungsarten]
=====

[.col-md-6]
.Zahlungs- und Bankverkehr allgemein
=====
* xref:payment:beta-zahlungen-verwalten.adoc#[Zahlungen verwalten]
* xref:payment:beta-zahlungen-verwalten.adoc#30[Zahlungen zuordnen]
* xref:payment:beta-zahlungen-verwalten.adoc#20[Zahlungen suchen]
* xref:payment:bankdaten-verwalten.adoc#[Bankdaten verwalten]
* xref:payment:bankdaten-verwalten.adoc#ebics[EBICS einrichten]
* xref:payment:bankdaten-verwalten.adoc#200[SEPA-Lastschriftmandat einrichten]
* xref:payment:waehrungen.adoc#[Währungen verwalten]
=====
====

[#400]
== Zahlungsanbieter und Zahlungsarten

Dir stehen verschiedene Zahlungsanbieter und Zahlungsarten zur Verfügung. Diese werden jeweils über eigene xref:payment:payment-plugins.adoc#[Plugins] in dein plentymarkets System eingebunden. Lade dir die Plugins aus dem link:https://marketplace.plentymarkets.com/plugins/payment/payment-integrationen[plentyMarketplace^] herunter, um sie in deinem System zu installieren.
