= Zahlungsarten verwalten
:keywords: Zahlungsart, Zahlungsarten, Standardzahlungsart, Standard-Zahlungsart, plugin-zahlungsart, Zahlungsartenübersicht, Zahlart, Zahlarten
:description: Richte Zahlungsarten in deinem plentymarkets System ein und aktiviere diese.
:author: team-fulfillment-payment

Zahlungsarten werden über Plugins eingebunden. Die einzelnen Payment Plugins kannst du im entsprechenden Bereich des link:https://marketplace.plentymarkets.com/plugins/payment[plentyMarketplace^] herunterladen. Die Anleitungen zum Einrichten der Zahlungsarten findest du ebenfalls im Marketplace oder im Bereich xref:payment:payment-plugins.adoc#[Payment Plugins] im Handbuch.

Auf dieser Handbuchseite erfährst du, welche Einstellungen für Zahlungsarten du vornehmen musst. Weiterhin findest du eine xref:payment:zahlungsarten-verwalten.adoc#65[Übersicht der Zahlungsarten in deinem System] sowie der zur Verfügung stehenden xref:payment:zahlungsarten-verwalten.adoc#70[Marktplatz-Zahlungsarten]. Die Marktplatz-Zahlungsarten sind automatisch in deinem plentymarkets System verfügbar, sobald du ein aktives Konto für den entsprechenden Marktplatz hast.

[#25]
== Standard-Zahlungsart festlegen

Gehe wie im Folgenden beschrieben vor, um die Zahlungsart festzulegen, die standardmäßig im Bestellvorgang in deinem Webshop voreingestellt ist.

[.instruction]
Standard-Zahlungsart festlegen:

. Öffne das Menü *Einrichtung » Mandant » [Mandant wählen] » Aufträge*.
. Wähle unter *Standard-Zahlungsart* eine Zahlungsart aus der Dropdown-Liste.
. *Speichere* (material:save[]) die Einstellungen.

[#30]
== Zahlungsart in Kundenklasse erlauben

In den Grundeinstellungen deiner Kundenklassen müssen Zahlungsarten erlaubt sein. Diese Einstellungen betreffen z.B. auch die *Standard-Endkund:innen*. Neue Zahlungsarten müssen den erlaubten Zahlungsarten hinzugefügt werden. Genauso kannst du hier Zahlungsarten für bestimmte Kundenklassen ausschließen, indem du die Zahlungsarten aus der Liste entfernst. Prüfe die Einstellungen unter *Erlaubte Zahlungsarten* deiner Kundenklassen, nachdem du eine neue Zahlungsart in deinem System eingerichtet hast. Weitere Details dazu findest du im Handbuchbereich xref:crm:kontakte.adoc#[Kontakte] im Kapitel xref:crm:vorbereitende-einstellungen.adoc#kundenklasse-erstellen[Kundenklasse erstellen].

[TIP]
.SSL-Zertifikat und Verschlüsselung
====
Wir empfehlen dir grundsätzlich, wenn du mit Zahlungs- und Kund:innendaten arbeiten, eine xref:business-entscheidungen:ssl-zertifikat_bestellen.adoc#[SSL-Verschlüsselung] für deinen Webshop. Für Zahlungsarten, die mit einem iframe arbeiten, ist dies zwingend.
====

[#50]
== Rabatt auf Zahlungsart gewähren

Du kannst für deine Kund:innen Rabatt auf Zahlungsarten gewähren. Dies ist eine Einstellung in den Kundenklassen, die es ermöglicht im Webshop einen Rabatt auf bestimmte Zahlungsarten anzubieten. Wie du einen Rabatt auf eine Zahlungsart in einer Kundenklasse festlegst, erfährst du im Handbuchbereich xref:crm:kontakte.adoc#[Kontakte] im Kapitel xref:crm:vorbereitende-einstellungen.adoc#rabatt-zahlungsart[Rabatt auf Zahlungsart einrichten].

[#60]
==  Versand ohne Zahlungseingang

Bei einigen Zahlungsarten, z.B. der Zahlung auf Rechnung, erfolgt der Versand bereits vor dem Zahlungseingang. Bei Beschränkung des xref:warenwirtschaft:warenbestaende-verwalten.adoc#[Warenbestands] auf Netto-Warenbestand prüft das System, ob Bestand vorhanden ist, und versetzt den Auftrag je nach Bestandsverfügbarkeit in den Status 4 oder 5. Wenn du diese Einstellung anwenden möchtest, setze in den xref:auftraege:grundeinstellungen.adoc#[Grundeinstellungen] des Auftrags im Menü *Einrichtung » Aufträge » Einstellungen* die Einstellung *Statuswechsel auf 4 statt 5, wenn Warenbestand fehlt* auf *JA*. Wenn du für diese Einstellung *NEIN* gewählt hast, ist _keine_ Beschränkung des Warenbestands eingestellt. Der Auftrag wird dann direkt zum Versand freigegeben, d.h. er wird in Status 5 versetzt.

Bei folgenden Zahlungsarten erfolgt der Versand vor dem Zahlungseingang:

*  Rechnung
*  Lastschrift
*  Nachnahme
*  Amazon

Beachte dazu auch die Handbuchseite xref:warenwirtschaft:warenbestaende-verwalten.adoc#[Bestand überwachen].

[#65]
== Übersicht der Zahlungsarten

Im Menü *Einrichtung » Aufträge » Zahlung » Zahlungsarten* findest du eine Übersicht über die Zahlungsarten und deren IDs in deinem plentymarkets System. +
Standardmäßig werden hier alle Plugin-Zahlungsarten angezeigt (material:toggle_off[]). Möchtest du alle im System vorhandenen Zahlungsarten sehen? Dann ändere die Schaltfläche oberhalb der Tabelle von material:toggle_off[] *Es werden alle Plugin-Zahlungsarten angezeigt* auf material:toggle_on[role=skyBlue] *Es werden alle im System vorhandenen Zahlungsarten angezeigt*.

*_Beachte:_* Es ist _nicht_ möglich, in der Übersicht Zahlungsarten zu aktivieren. +
Wenn du Zahlungsarten in dein plentymarkets System einbinden und deinen Kund:innen zur Verfügung stellen möchtest, musst du das entsprechende Plugin im link:https://marketplace.plentymarkets.com/plugins/payment[plentyMarketplace^] herunterladen. Die Anleitungen zum Einrichten der Zahlungsarten findest du ebenfalls im Marketplace oder im Bereich xref:payment:payment-plugins.adoc#[Payment Plugins] im Handbuch.

[[table-payment-methods-overview]]
.Übersicht der Zahlungsarten
[cols="1,3"]
|====
|Tabellenspalte |Erläuterung

| *ID*
|Die eindeutige ID der Zahlungsart. +
Dies ist eine Standardspalte.

| *Zahlungsart*
|Der Name der Zahlungsart. +
Dies ist eine Standardspalte.

| *Suchbar im Backend*
|Wenn eine Zahlungsart im Backend suchbar ist, wird sie an allen Stellen im System, an denen du eine Zahlungsart wählen kannst, angezeigt. Zum Beispiel in den Dropdown-Listen in xref:automatisierung:ereignisaktionen.adoc#[Ereignisaktionen] oder in xref:crm:vorbereitende-einstellungen.adoc#kundenklasse-erstellen[Kundenklassen]. +
material:check_circle[role=green] = Die Zahlungsart ist suchbar im Backend. +
material:cancel[role=red] = Die Zahlungsart ist _nicht_ suchbar im Backend. +
Dies ist eine Standardspalte.

| *Aktiv im Backend*
|Wenn eine Zahlungsart im Backend aktiv ist, kann sie einem Auftrag bei manueller Auftragserstellung zugewiesen werden. Außerdem ist die Zahlungsart auch suchbar im Backend, d.h. sie wird an allen Stellen im System, an denen du eine Zahlungsart wählen kannst, angezeigt. Zum Beispiel in den Dropdown-Listen in xref:automatisierung:ereignisaktionen.adoc#[Ereignisaktionen] oder in xref:crm:vorbereitende-einstellungen.adoc#kundenklasse-erstellen[Kundenklassen]. +
material:check_circle[role=green] = Die Zahlungsart ist im Backend aktiv. +
material:cancel[role=red] = Die Zahlungsart ist _nicht_ im Backend aktiv. +
Dies ist eine Standardspalte.

| *Zahlungsart Abonnement*
|Zeigt an, ob die Zahlungsart für xref:auftraege:abonnement.adoc#[Abonnements] genutzt werden kann. Dies sind die Zahlungsarten *Rechnung*, *Vorkasse* und *Lastschrift*. +
Dies ist _keine_ Standardspalte.

| *pluginKey* und *paymentKey*
|Dies sind eindeutige Werte, mit denen man eine Zahlungsart systemweit identifizieren kann. Sie werden beim Registrieren einer Zahlungsart durch die Entwickler:in bestimmt. Nutzbar sind diese Werte vor allem für Entwickler:innen, z.B. wenn man die ID einer Zahlungsart aus dem System auslesen möchte. +
Dies ist _keine_ Standardspalte.

|====

[#70]
== Marktplatz-Zahlungsarten

Marktplatz-Zahlungsarten sind Zahlungsarten, die in Verbindung mit der Einrichtung eines Marktplatzes zur Kennzeichnung von Zahlungseingängen genutzt werden. Die Marktplatz-Zahlungsarten sind automatisch in deinem plentymarkets System verfügbar, sobald du ein aktives Konto für den entsprechenden Marktplatz hast.

* xref:maerkte:amazon-einrichten.adoc#4500[Amazon]
* xref:maerkte:bol-com.adoc#650[BOL.com]
* xref:maerkte:cdiscount.adoc#900[Cdiscount]
* xref:maerkte:check24.adoc#700[Check24]
* xref:maerkte:ebay-einrichten.adoc#2250[eBay-Rechnungskauf]
* xref:maerkte:fruugo.adoc#600[Fruugo]
* xref:maerkte:idealo-einrichten.adoc#1100[idealo Direktkauf]
* xref:maerkte:kaufland-de-einrichten.adoc#800[Kaufland.de]
* xref:maerkte:neckermann-at-einrichten.adoc#1600[Neckermann.at]
* xref:maerkte:plus-gartenxxl.adoc#400[Netto]
* xref:maerkte:otto-market.adoc#425[OTTO Payment]
* xref:maerkte:shopgate.adoc#600[Shopgate Payment]
* xref:maerkte:yatego.adoc#900[Yatego Rechnung]
* xref:maerkte:zalando.adoc#delivery-pdf-upload[Zalando Payment]
