[.collapseBox]
.*Tip: How to filter API log entries*
--

By default, entries are sorted by their ID. You can filter the entries so that fewer search results are included in the list. An API name filter and a date filter are available for this purpose. It is possible to combine both filters so that only entries for a specific format and day are displayed.

[.instruction]
Filtering log entries by name:

. Go to *Data » API log*.
. Select a format from the *Process* drop-down list.
. Click on *Search* (icon:search[role="darkGrey"]).

[IMPORTANT]
.The desired format is not displayed?
======
The formats are not displayed in the *Process* drop-down list until the process has been carried out once and has therefore been logged. If you do not find new formats in this list, the process has not been carried out yet or the error you are looking for has not yet occurred.
======

[.instruction]
Filtering log entries by date:

. Go to *Data » API log*.
. Select a *Date* from the calendar.
. Click on *Search* (icon:search[role="darkGrey"]).

--
