////
Hinweise zur Datei:
Kapitelüberschrift “Bearbeitungsmodus nutzen” verwenden (je nach Ebene der Überschrift selbst einbinden).
Anwendungsfall für die spezielle myView händisch auf der Seite hinzufügen - Warum möchte ich den Bearbeitungsmodus nutzen?
////

:menu-path:
:edit-object:

The editing mode allows a high degree of flexibility for positioning content and data in the *{menu-path}* menu. This works by intuitively positioning elements via drag-and-drop. You can individually adjust and edit each element. <<#table-functions-editing-mode>> contains an overview of the functions available in the editing mode.

[TIP]
.Do you have admin rights?
======
Only xref:business-decisions:user-accounts-access.adoc#[admin users] can create and edit views.
If you are not an admin:

. Turn to someone with admin rights.
. Ask them to create the necessary views for you and assign them to your user account.
======

//// 
TODO: GIF hier einfügen
////

[[table-functions-editing-mode]]
.Available settings in the editing mode
[cols="2,1,6"]
|====

|Element |Symbol |Explanation

| *Edit view*
|icon:design_inline_edit[set=plenty]
| Opens the view for editing. +
You can move the elements to a different place with drag-and-drop and adjust the size of the components.

| *Undo*
|icon:undo[set=material]
| Undoes the last change, unless this change has already been saved.

| *Redo*
|icon:redo[set=material]
| Restores the previously undone change.

| *Default view*
|
| This area displays the view that is currently opened. Click on icon:sort-down[role=darkGrey] to switch to another view or to create a new view.

| *Restoring the previously saved state*
|icon:restore[set=material]
| Resets the view to the state that was last saved.

| *Save*
|icon:save[set=material]
| Saves the changes. You can save as many different views as you like. +
When you want to edit {edit-object} the next time, you can open your preferred view via the drop-down list in the top right. Also in this drop-down list, you can create a new view by clicking on icon:add[set=material] *Create new preset...*.

| *Edit*
|icon:edit[set=material]
|When you edit the element, you can see in the *Elements* area on the right side which elements have not been added yet and are therefore still available. Elements that have already been added are disabled and cannot be used another time.

| *Delete*
|icon:delete[set=material]
|Deletes the element.

| *Close*
|icon:close[set=material]
| Closes the editing mode. If you have not saved the changes yet, a security inquiry appears.

|====
