
First, create the tags that you want to use.

[.instruction]
Creating a tag:

. Go to *Setup » Settings » Tags*.
. Click on *Create new tag* (icon:plus[role="green"]). +
→ A window opens on the right-hand side.
. Carry out the settings. Expand the info boxes below (icon:chevron-down[role="darkGrey"]) to learn more about the settings.
. *Save* (icon:save[role="green"]) the settings. +
→ The tag is created and added to the list.

[.collapseBox]
.*More about the settings*
--
[[table-tag-settings]]
[cols="1,3"]
|====
|Setting |Explanation

| *ID*
| The tag ID is automatically assigned and cannot be changed.
It is used to uniquely identify your tags.

*_Use case_*: Tag links can be imported.
For example, while you import item and variation data, you can also directly link the appropriate tags.
This is done, e.g. by specifying the tag ID.

| *Name EN* +
[red]#(Mandatory field)#
| Enter a name for the tag.
The name is the keyword that highlights the data record.

*_Tip_*: The name can include spaces. As such, tag names can consist of multiple words.

| *Colour*
a| What background colour should the tag text have?
There are three ways to choose the colour:

* Enter the colour’s hexadecimal value.
* Enter the English name for one of the 16 basic colours (black, red, silver, white, etc.)
* Click on the square on the right and click on the colour spectrum.

|[#intable-availability]*Availability*
a| What types of data records will you link to this tag?
Select all of the appropriate availabilities (icon:check-square[role="blue"]).

[cols="1,3"]
!===
! Section ! Example of use

! *Board*
! Do you want to highlight specific task cards on boards? +
*_Example:_* Specify that some tasks have a high or low priority.

! *Category Link*
! Do you want to highlight specific categories in the back end? +
*_Example:_* Specify that a category should only be used for seasonal offers.

*_Note_*: Category tags are _not visible_ to customers in the online store.

! *Ticket*
! Do you want to highlight specific tickets within the ticket system? +
*_Example:_* Specify that the ticket relates to a specific sales channel like Amazon or eBay.

! *Contact*
! Do you want to highlight specific contacts? +
*_Example:_* Specify the customer’s preferred method of communication.

! *Variation*
! Do you want to highlight specific variations? +
*_Example:_* If you sell ladders, specify that some ladders were awarded a seal of approval for their safety features.

*_Note_*: Variation tags can be made _visible_ to customers in the online store.
Do so by <<#intable-client, selecting the appropriate client>> further below.

! *Order*
! Tags can currently be created for orders, but they cannot be linked to orders yet.
Therefore, this option is currently not in use.

! *Messages*
! Do you want to highlight specific messages within the messenger tool? +
*_Example:_* Specify that the message relates to a specific sales channel like Amazon or eBay.

! *Message (billable)*
! Do you occasionally write fee-based messages in the messenger tool?
In other words, should the customer be charged for the minutes that elapsed while writing the message?

While writing a fee-based message, you’ll need to select at least one tag with this availability.
Otherwise, the message cannot be created.
!===

|[#intable-client]*Client* +
(functional for plentyShop LTS 5.0 and higher)
| In which plentyShops should the tag be visible to customers?
Select all of the appropriate webshops (icon:check-square[role="blue"]).

*_Note_*: This option only appears if you <<#intable-availability, selected the availability Variation>>.

| *Name DE* +
*Name FR* +
*Name IT* +
etc.
| Translate the tag names into other languages.

*_Example of use_*: Variation tags can be made visible to customers in the online store.
If your online store is available in multiple languages, then the tag names should also appear in these languages.
|====
--

[TIP]
.Tags can be edited at any time
====
Use the search function to find specific tags.
The optional filters can be used to limit the search results:

* *Name* = Enter the tag's name in the main language of your plentymarkets system.
* *Availability* = Select one or more availabilities. The search results will only include tags with this availability.
* *Language* = Select one or more languages. The search results will only include tags that have a name saved in this language.
====
