
Tags are texts, like keywords or phrases.
First, create all of the necessary tags.

. Go to *Setup » Settings » Tags*.
. Click on icon:plus[role="darkGrey"]. +
→ A pop-up window opens. This window is divided into several steps.
. Carry out the settings in each step.

[TIP]
.Tags can not be created via import
====
Tags can only be created manually, as described here in the instructions.
It is not possible to create tags with the import tool.
====

[discrete]
==== Step: Name

[cols="1,4a"]
|===
|Setting |Explanation

| *Tag name* +
[red]#(Mandatory field)#
|Enter a name for the tag.
The name is the keyword or phrase that highlights the data record.

*_Tip_*: The name can include spaces. As such, tag names can consist of multiple words.

*_Note_*:
Once you’ve created the tag, you can translate the name into other languages.

| *Tag colour* +
[red]#(Mandatory field)#
|What background colour should the tag text have?
Click on material:square[role="darkGrey"] and choose the colour.

*_How do I choose a colour_*?

* Enter the colour values directly. Click on material:unfold_more[role="darkGrey"] to toggle between the different options:
** Enter the colour’s RGB values.
** Enter the colour’s HSL values.
** Enter the colour’s hexadecimal value.
* Click in the colour spectrum and use the slider.
* Click on icon:eyedropper[role="darkGrey"] and select the colour from somewhere on your screen.

|===

---

[discrete]
==== Step: Availabilities

[cols="1,4a"]
|===
|Setting |Explanation

|[#intable-availability]*Availability type* +
[red]#(Mandatory field)#
| What do you want to use the tag for?
In other words, what types of data records will you link to the tag?
Select all of the appropriate availabilities (icon:check-square[role="blue"]).

[cols="1,4"]
!===

! *Category*
! Do you want to highlight specific categories in the back end?

*_Example:_* Specify that a category should only be used for seasonal offers.

*_Note_*: Category tags are _not visible_ to customers in the online store.

! *Ticket*
! Do you want to highlight specific tickets within the ticket system?

*_Example:_* Specify that the ticket relates to a specific sales channel like Amazon or eBay.

! *Contact*
! Do you want to highlight specific contacts?

*_Example:_* Specify the customer’s preferred method of communication.

! *Variation*
! Do you want to highlight specific variations?

*_Example:_* If you sell ladders, specify that some ladders were awarded a seal of approval for their safety features.

*_Note_*: Variation tags can be made _visible_ to customers in the online store.
Once you’ve finished creating the tag, open the advanced settings and select the appropriate clients.

! *Order*
! Do you want to highlight specific reorders and redistributions?

*_Example_*: Specify which kind of products were reordered or redistributed.

*_Note_*: Currently, tags can only be used for reorders and redistributions. They cannot be used for any other order types.

! *Messenger conversations*
! Do you want to highlight specific conversations within the messenger tool?

*_Example:_* Specify that the message relates to a specific sales channel like Amazon or eBay.

! *Messenger: Billable messages*
! Do you occasionally write fee-based messages in the messenger tool?
In other words, should the customer be charged for the minutes that elapsed while writing the message?

While writing a fee-based message, you’ll need to select at least one tag with this availability.
Otherwise, the message cannot be created.
!===

|===

---

[discrete]
==== Step: Done

[cols="1,4"]
|===
|Setting |Explanation

| *Summary*
a|Here you can see a summary of the settings that you selected.
Click on *Create tag* if you are satisfied with the settings.

Afterwards, you will have the following options:

[cols="1,4a"]
!===

! *To the tag*
!The pop-up window will close and the newly created tag will open for further editing.

! *Create another tag*
!The pop-up window will re-start for the next tag.

! *Close*
!The pop-up window will close.

!===

|===

[.collapseBox]
.*To the tag: which advanced settings are available?*
--

[cols="1,3a"]
|===
|Setting |Explanation

| *ID*
| The tag ID is automatically assigned and cannot be changed.
It is used to uniquely identify your tags.

*_Use case_*: Tag links can be imported.
For example, while you import item and variation data, you can also directly link the appropriate tags.
This is done, e.g. by specifying the tag ID.

|[#intable-client]*Client* +
| In which plentyShops should the tag be visible to customers?
Select all of the appropriate webshops (icon:check-square[role="blue"]).

*_Note_*: This option only appears if you selected the availability <<#intable-availability, Variation>>.

| *Name DE* +
*Name FR* +
*Name IT* +
etc.
|Is your plentyShop available in multiple languages?
Variation tags can be made visible to customers in the online store.
If your online store is available in multiple languages, then the tag names should also appear in these languages.

. Click on icon:plus[role="darkGrey"] and select a language version from the drop-down list.
. Enter a translation of the name.

|===

--
