= Nachbestellungen anlegen (Testphase)
:keywords: Nachbestellungen anlegen, Nachbestellungen manuell anlegen, Nachbestellungen anlegen neue UI, neue Nachbestellung
:author: team-order-core
:description: Erfahre, wie du Nachbestellungen manuell in drei Schritten anlegst. Dies über über Nacbestellung möglich.

Es kann vorkommen, dass du eine Nachbestellung bezogen auf ein spezielles Lager oder eine spezielle Lieferant:in erstellen möchtest. 

[.instruction]
Gehe dazu wie folgt vor:

. Öffne das Menü *Waren* » *Nachbestellung (Testphase)*.
. Klicke links in der Seitennavigation auf *material:add[] Neue Nachbestellung*.
→ Das Menü zur Erstellung einer neuen Nachbestellung öffnet sich.

Die Anlage einer neuen Nachbestellung verläuft in drei Schritten. 

Im ersten Schritt werden Auftragsdetails erfasst, im zweiten Schritt werden Auftragspositionen hinzugefügt und bearbeitet und im dritten Schritt wird die Nachbestellung erstellt.

[#100]
== Nachbestellungsdetails erfassen

Im ersten Schritt solltest du die Felder in den Bereichen *Auftragsdetails* und *Status und Tags* ausfüllen. Beachte dazu die Erläuterung zu allen Feldern in der <<table-order-details-new-reorder>>.

[[table-order-details-new-reorder]]
.Allgemeine Einstellungen
[cols="1,3"]
|===
|Einstellung |Erläuterung

| *Lieferant*
|Wähle den Lieferant aus der Dropdown-Liste. 

| *Lager*
|Wähle das Ziellager, an das die Nachbestellung geliefert werden soll.

| *Lieferdatum*
|Wähle das Lieferdatum für die Nachbestellung.

| *Zahlungsziel*
|Wähle das Datum, das als Zahlungsziel festgelegt wird.

| *Wechselkurs*
|Gib den geltenden Wechselkurs für die gewählte Währung ein. 

| *Systemwährung*
|Die xref:payment:waehrungen.adoc#30[Systemwährung] ist vorausgewählt. Über die Dropdown-Liste kannst du die Währung für die Nachbestellung anpassen.

| *Zusatzliche Informationen*
|Gib hier weitere Details oder spezielle Anweisungen ein, die für die Bestellung oder Lieferung relevant sind.

| *Mandant*
|Wähle den Mandanten aus der Dropdown-Liste.

| *Eigner*
|Gib einen Eigner (den bearbeitenden Nutzer) ein. Hast du einen <<#intable-default-owner, Standard Eigner>> gesetzt, ist dieser vorausgewählt. Ansonsten werden dir in der Dropdown-Liste nur Eigner angezeigt, die das Benutzerrecht haben, Nachbestellungen zu erstellen und zu bearbeiten.

| *Tags*
|*Optional:* Wähle ein oder mehrere Tags für die neue Nachbestellung aus.

| *Status*
|Wähle den Status für die Nachbestellung.

|===

Wenn du mit allen Einstellungen fertig bist, klicke auf *Auftragspositionen*, um zum nächsten Schritt zu gelangen.

[#200]
== Auftragspositionen - Artikel finden und hinzufügen

Sobald du alle Auftragsdetails eingetragen hast, kannst du nun in diesem Schritt deine gewünschten Artikel in Form von Auftragspositionen zum Warenkorb hinzufügen. 

[#210]
=== Artikel suchen

Anhand der Suche (material:search[]) kannst du die gewünschten Artikel finden und zur Nachbestellung hinzufügen. 
Verwende eine der folgenden Möglichkeiten, um nach Artikeln zu suchen:

[.instruction]
Artikel suchen:

.. *_Möglichkeit 1:_* Klicke auf material:search[], um direkt eine Liste aller Artikel zu sehen.
.. *_Möglichkeit 2:_* Gib etwas in das Suchfeld ein und klicke auf einen der automatischen Vorschläge.
.. *_Möglichkeit 3:_* Klicke auf material:tune[], um die Suchergebnisse mit Hilfe von Filtern einzugrenzen.

Nutze außerdem die in der folgenden <<table-reorder-filters, Tabelle>> aufgeführten Filter, um die Suche weiter einzugrenzen. 

[[table-reorder-filters]]
.Filter für Auftragspositionen
[cols="1,3"]
|===
|Filter |Erläuterung

| *Artikel ID*
|Gib eine ID ein, um nach Artikeln mit dieser ID zu filtern.

| *Artikelname*
|Gib einen Namen ein, um nach Artikeln mit diesem Namen zu filtern.

| *Variantennummer*
|Gib eine Variantennummer ein, um nach Artikeln mit dieser Variantennummer zu filtern.
*_Tipp:_* Für diesen Filter ist auch eine Teilsuche möglich. Somit genügt es, wenn du lediglich die ersten Zeichen der Variantennummer eingibst, um danach zu suchen.

| *Varianten-ID*
|Gib eine Varianten-ID ein, um nach Artikeln mit dieser Varianten-ID zu filtern.

| *Barcode*
|Gib einen Barcode ein, um nach Artikeln mit diesem Barcode zu filtern.

| *Hersteller*
|Gib einen Hersteller ein, um nach Artikeln dieses Herstellers zu filtern.

| *Liferanten-Artikel-Nummer*
|Gib die Nummer der Lieferant:in ein, um nach Artikeln mit dieser Lieferantennummer zu suchen.

| *Variation-Tag*
|Gib ein Tag ein, um nach Variationen mit diesem Tag zu filtern.

| *Nur aktive Artikel anzeigen*
|Aktiviere diese Option (material:done[role=skyBlue]), um nach aktiven Artikeln zu filtern.

| *Beschränken auf Lieferant*
|Aktiviere diese Option (imaterial:done[role=skyBlue]), um die Suche nach Lieferanten zu filtern.

|===

[#220]
==== Aktuellen Filter speichern

Du hast die Möglichkeit deine Filter zu speichern. Gespeicherte Filter sind bei jedem Öffnen des Menüs unter (bookmark icon) auswählbar, ähnlich wie Lesezeichen. Jede:r Benutzer:in kann eigene Filter festlegen.

Um einen Filter zu speichern, gehe wie folgt vor:

. Führe eine Suche aus.
. Klicke auf *Gespeicherte Filter* (material:bookmarks[role=darkGrey]s).
. Klicke auf material:bookmark_border[role=darkGrey] *Aktuellen Filter speichern*.
. Gib einen Namen ein und schalte die optionalen Einstellungen bei Bedarf ein (material:toggle_on[role=skyBlue]).
. Klicke auf *Speichern*. +
→ Die Filtereinstellungen erscheinen nun unter *Gespeicherte Filter* (material:bookmarks[role=darkGrey]).

[#230]
==== Gespeicherte Filter anwenden

Um die gespeicherte Filter anzuwenden, gehe wie folgt vor: 

. Klicke auf *Gespeicherte Filter* (material:bookmarks[role=darkGrey]s).
. Klicke auf eine bereits erstellte Filtereinstellung.
→ Die Suche wird ausgeführt und die verwendeten Sucheinstellungen werden oben als Chips dargestellt.

[#240]
=== Artikel zum Warenkorb hinzufügen

Nachdem du mithilfe der Suche oder anhand von Filtern alle gewünschten Artikel gefunden hast, kannst du sie zum Warenkorb hinzufügen. Gehe dazu wie folgt vor.

[.instruction]
Artikel hinzufügen:

. Gib die Menge des Artikels ein, die dem Auftrag hinzugefügt werden soll.
. Klicke am Ende der jeweiligen Zeile auf *Zum Warenkorb hinzufügen* (material:add_shopping_cart[]), um den Artikel zum Warenkorb hinzuzufügen.
. Wiederhole diese Schritte, um weitere Artikel hinzuzufügen.

[.collapseBox]
.*Artikeltabelle individualisieren*
--

Die Artikeltabelle kann individuell gestaltet werden. Das bedeutet, dass du selbst entscheiden kannst, welche Informationen dir in den Tabellenspalten angezeigt werden und in welcher Reihenfolge sie platziert sind. Um die Tabelle anzupassen, gehe vor wie folgt.

[.instruction]
Tabelle individualisieren:

. Klicke auf *Spalten konfigurieren* (material:settings[]). +
→ Das Fenster *Spalten konfigurieren* wird geöffnet.
. Wähle, welche Spalten angezeigt werden sollen. 
. Verschiebe (material:drag_indicator[]) die Spalten so, dass sie in der gewünschten Reihenfolge angezeigt werden.
. Klicke auf *Bestätigen*, um deine Auswahl zu speichern.

Wenn du die Tabelle einmal angepasst hast, wird diese Auswahl gespeichert. Die Tabelle bleibt also gleich, auch wenn du diesen Auftrag abgeschlossen hast und weitere Aufträge anlegst. Du kannst das Layout jederzeit ändern. 

Standardmäßig werden dir folgende Tabellenspalten angezeigt:

* Varianten-ID
* Variantennummer
* Artikelname
* Netto-WB
* Lieferanten-Informationen
* Menge
* Warenkorb-Symbol

Die folgenden Tabellenspalten können ausgewählt werden, werden aber standardmäßig nicht angezeigt:

* Bestandsstatus
* Status
* Artikel-ID
* Artikel-ID / Varianten-ID
* Attribute
* Variantenname
* Original-EK
* Verfügbarkeit
--

[#250]
=== Warenkorb bearbeiten

Nachdem du die gewünschten Artikel zum Warenkorb hinzugefügt hast, kannst du sie noch bearbeiten. Die Felder, die bearbeitet werden können, haben ein Stiftsymbol (material:edit[]) daneben. Du kannst zum Beispiel die *Menge* ändern oder *Artikel löschen*. Im Feld *Preis* kannst du den voreingetragenen Einkaufspreis ändern oder gewährten Rabatt eingeben, falls deine Lieferant:in dir beispielsweise kurzfristig einen veränderten Preis zugesagt hat. Im Feld *Lieferanten-Artikel-Bez.* kannst du die Bezeichnung für den Artikel anpassen. 

Wann immer du eine Änderung in einem Feld vornimmst, wird oben links eine Speichertaste (material:save[]) angezeigt, die du anklicken solltest, um deine Änderungen zu speichern.

*_Hinweis:_* Die Änderungen gelten nur für die Nachbestellung, in der sie vorgenommen wurden. Möchtest du die xref:artikel:einstellungen.adoc#[Artikeleinstellungen] generell anpassen, kannst du dies im Menü *Artikel » Artikel bearbeiten* im entsprechenden Tab machen.

Auftragspositionen im Warenkorb können auch gelöscht werden. Klicke dafür auf *Löschen* (material:delete[]) am Ende der jeweiligen Zeile.

Nachdem du alle gewünschten Artikel im Warenkorb abschließend bearbeitet hast, klicke auf Übersicht, um zum dritten und letzten Schritt zu gelangen. Du kannst auch zu den Auftragsdetails zurückkehren, indem du auf Auftragsdetails klickst. Artikel im Warenkorb werden gespeichert, wenn du vor oder zurückkehrst.

[.collapseBox]
.*Warenkorbtabelle individualisieren*
--
Die Warenkorbtabelle lässt sich individuell anpassen. Du kannst wählen, welche Tabellenspalten dir in welcher Reihenfolge angezeigt werden sollen. Wenn du die Tabelle angepasst hast, wird diese Auswahl gespeichert.

[.instruction]
Tabelle individualisieren:

. Klicke auf *Spalten konfigurieren* (material:settings[]). +
→ Das Fenster *Spalten konfigurieren* wird geöffnet.
. Wähle, welche Spalten angezeigt werden sollen.
. Verschiebe (material:drag_indicator[]) die Spalten, sodass sie in der Reihenfolge angezeigt werden, in der du sie benötigst.
. Klicke auf *Bestätigen*, um deine Auswahl zu speichern.

[[table-shopping-cart]]
.Tabellenspalten Warenkorb
[cols="1,3"]
|===
|Einstellung |Erläuterung

| *Varianten-ID*
|Zeigt die Varianten-ID der Auftragsposition an. Mit Klick auf die ID wird die Variante geöffnet. +
Diese Spalte ist eine Standardspalte.

| *Artikelname*
|Zeigt den am Artikel hinterlegten Namen an. Passe den Namen bei Bedarf an (material:edit[]). +
Diese Spalte ist eine Standardspalte.

| *Lieferanten-Informationen*
|Zeigt die Informationen über Lieferanten, die an der Variation hinterlegt sind. +
Diese Spalte ist eine Standardspalte.

| *Menge*
|Zeigt die Menge der Artikel an. Passe die Menge bei Bedarf an. +
*_Hinweis:_* Wenn du die Menge änderst, musst du die *Speichern* (materiel:save[]).
Diese Spalte ist eine Standardspalte.

| *Preis*
|Zeigt den Preis an. Passe den Preis bei Bedarf an. +
*_Hinweis:_* Wenn du den Preis änderst, musst du den *Speichern* (materiel:save[]).
Diese Spalte ist eine Standardspalte.

| *Rabatt [%]*
|Zeigt den Rabatt in Prozent an. Passe den Rabatt bei Bedarf an. +
*_Hinweis:_* Wenn du den Rabatt änderst, musst du den *Speichern* (materiel:save[]). +
Diese Spalte ist eine Standardspalte.

| *Rabattierter Preis*
|Zeigt den für die Auftragsposition gewährten Rabatt an. +
Diese Spalte ist eine Standardspalte.

| *Lieferanten-Artikel-Nummer*
|Zeigt die Artikel Nummer der Lieferant:in an. +
Diese Spalte ist eine Standardspalte.

| *Auftrags-ID*
|Ist dieses Feld gewählt, sind die Aktionen zum Bearbeiten (material:edit[]) und Löschen (material:delete[]) des Artikels verfügbar.

| *Artikel-ID*
|Zeigt die Artikel-ID an. Mit Klick auf die ID wird der Artikel geöffnet. +
Diese Spalte ist eine optionale Spalte.

| *Variantennummer*
|Zeigt die Nummer der Variante an. Wenn du auf die Variantennummer klickst, gelangst du direkt in die Einstellungen der jeweiligen Variante. +
Diese Spalte ist eine optionale Spalte.

| *Attribute*
|Zeigt die Attribute an. +
Diese Spalte ist eine optionale Spalte.

| *Variantenname*
|Zeigt den Namen der Variante an. +
Diese Spalte ist eine optionale Spalte.

| *Barcode*
|Zeigt den Barcode des Artikels an. +
Diese Spalte ist eine optionale Spalte.

| *System-EK*
|Zeigt den Einkaufspreis des Systems an. +
Diese Spalte ist eine optionale Spalte.

| *Aktionen*
|Ist dieses Feld gewählt, sind die Aktionen zum Bearbeiten (material:edit[]) und Löschen (material:delete[]) des Artikels verfügbar.

| *Lieferanten-Artikel-Bez.*
|Zeigt die Artikel Bezeichnung der Lieferant:in an.
Diese Spalte ist eine optionale Spalte.

| *Auswahl*
|Ist dieses Feld gewählt, ist es möglich für mehrere Auftragspositionen gleichzeitig eine Aktion auszuführen. Die verfügbare Aktionen sind *Löschen* (material:delete[]) und *Rabatt* (%).
Diese Spalte ist eine optionale Spalte.

| *Modell*
|Zeigt das Modell der Varianten an.
Diese Spalte ist eine optionale Spalte.

|===
--

[#260]
== Übersicht - Nachbestellung erstellen

Im letzten Schritt siehst du eine Übersicht aller Einstellungen, die du für die Nachbestellung in den vorherigen Schritten konfiguriert hast, bevor du die Nachbestellung erstellst. 

In der *Übersichtstabelle* werden dir Infoboxen mit verschiedenen Beträgen für diese Nachbestellung angezeigt:

* Nettowarenwert
* Artikelmenge
* Rabatt
* Warenbezug gesamt (im Folgenden erläutert)

In den *Auftragsdetails* kannst du das Lager, das Lieferdatum, das Zahlungsziel, die Währung, den Mandant, sowie den Eigner bei Bedarf noch einmal anpassen.

Unterhalb der Auftragsdetails, wird eine Tabelle mit *Status und Tags* angezeigt, die du hier bei Bedarf nochmal anpassen kannst.

Die Tabelle mit den *Auftragspositionen* gibt dir einen Überblick über die Einstellungen, die du im vorherigen Schritt vorgenommen hast.

*Warenbezugskosten*

Wenn Waren nachbestellt werden, entstehen verschiedene Kosten. Diese können im Bereich Warenbezugskosten zu einer Nachbestellung hinzugefügt werden. So werden die bekannten Zusatzkosten als Eigenschaften an der Nachbestellung gespeichert und in dieser auch angezeigt, damit du auf einen Blick alle relevanten Informationen zu einer Nachbestellung hast. Die Anzeige der zusätzlichen Warenbezugskosten erfolgt in der gleichen Währung, in der die Nachbestellung abgeschlossen wurde.

Folgende Warenbezugskosten können hinterlegt werden:

* Vermittlungsgebühren
* Zölle
* Rollgeld
* Frachtkosten
* Sonstige Kosten
* Verpackungskosten
* Porto
* Mindermengenzuschläge
* Transportversicherung

Klicke direkt in das Feld der jeweiligen Kosten, die du hinzufügen möchtest, und gib den entsprechenden Betrag manuell ein. Erlaubt sind Beträge mit maximal 2 Dezimalstellen. Die Kosten werden automatisch in der Währung hinzugefügt, die für die Nachbestellung gesetzt wurde. 

Wenn du mit allen Einstellungen zufrieden bist, klicke auf *material:save[] Nachbestellung erstellen*. Die Nachbestellung wird erstellt und automatisch geöffnet. In der Seitennavigation links siehst du die aktuell geöffnete Nachbestellung (ID). Die Nachbestellung ist anschließend in der Übersicht im Menü *Waren » Nachbestellung (Testphase)* verfügbar.