= Nachbestellungsansicht gestalten

:keywords: MyView, Nachbestellungsansicht gestalten, Nachbestellungssansicht anpassen, Spalten für Nachbestellungen anpassen, Spalten konfigurieren, Kompaktansicht
:author: team-order-core
:description: Erfahre, wie du die Übersicht deiner Nachbestellungen individuell gestalten kannst. Entscheide im Bearbeitungsmodus selbst, welche Informationen und Einstellungen du in deiner Nachbestellungsverwaltung benötigst.

Auf dieser Handbuchseite erfährst du, wie du die Übersicht der Nachbestellungen mit Hilfe von verschiedenen Ansichten und zahlreichen Einstellungen genau nach deinen Wünschen gestaltest.

[#100]
== Nachbestellungsansicht gestalten

In der Kompaktansicht werden die von dir gewählten Auftragsdetails platzsparend direkt in der Übersicht angezeigt.

Du kannst die Kompaktansicht individuell gestalten und im xref:working-with-reorders.adoc#370[Bearbeitungsmodus] festlegen, welche Informationen zu deinen Nachbestellungen angezeigt werden sollen. Außerdem kannst du wählen, wie groß die verschiedenen Felder der Informationen sein sollen und bei Bedarf auch farbliche Markierungen hinzufügen, um die Felder zusätzlich visuell voneinander abzugrenzen.

In den folgenden Kapiteln erfährst du, wie du die Kompaktansicht nach deinen Wünschen gestaltest.

[#150]
=== Felder für die Nachbestellungsübersicht wählen

Wähle zunächst, welche Felder zu deinen Nachbestellungen in der Übersicht angezeigt werden sollen. Gehe dazu vor wie folgt.

[.instruction]
Felder für die Nachbestellungsübersicht wählen:

. Öffne das Menü *Waren » Nachbestellung (Testphase)*.
. Führe die Suche (material:search[]) aus, um Nachbestellungen anzuzeigen.
. Klicke oben rechts auf *Ansicht bearbeiten* (terra:design_inline_edit[]), um die Kompaktansicht im Bearbeitungsmodus zu gestalten.
. Klicke oben rechts in der Hauptansicht auf *Bearbeiten* (material:edit[role=skyBlue]). +
→ Der Bearbeitungsmodus wird geöffnet.
. Wähle (material:check_box[role=skyBlue]) rechts in den Einstellungen im Bereich *Kompaktansicht* die Felder, die in der Kompaktansicht angezeigt werden sollen. Weitere Informationen zu den verfügbaren Feldern findest du in <<#table-reorder-compact-view-title>> und <<#table-reorder-compact-view>>. +
*_Tipp:_* Ziehe (material:drag_indicator[]) die gewählten Felder per Drag-and-Drop in die gewünschte Reihenfolge. Lege fest, <<#170, welche Informationen>> die einzelnen Felder enthalten sollen. +
. Bist du mit den gewählten Feldern zufrieden, klicke oben rechts auf *Ansicht speichern* (material:save[role=skyBlue]).
. Vergib einen Namen für die neue Ansicht und klicke auf *Ansicht erstellen*. +
→ Die neue Ansicht wird erstellt.

[TIP]
.Hast du Admin-Rechte?
======
Nur xref:business-entscheidungen:benutzerkonten-zugaenge.adoc#[Admin-Nutzer:innen] können Ansichten erstellen und bearbeiten.
Falls du kein Admin bist:

. Wende dich an eine Person mit Admin-Rechten.
. Bitte die Person, die erforderlichen Ansichten zu erstellen und sie für dein Benutzer:innenkonto freizugeben.
======

[[table-reorder-compact-view-title]]
.Felder für die Kompaktansicht
[cols="1,3"]
|===
|Einstellung |Erläuterung

| *Lieferantenadresse*
|Zeigt die Lieferantenadresse an.

| *Lager*
|Zeigt das Ziellager, an das die Nachbestellung geliefert werden soll. 

| *Tags*
|Zeigt die Tags an, die der Nachbestellung zugeordnet sind.

| *Artikelmenge*
|Zeigt die Artikelmenge aller Artikel in der Nachbestellung an.

| *Lieferanten-ID*
|Zeigt die ID des Lieferanten an.

| *Eigner*
|Zeigt die Eigner:in der Nachbestellung an.

| *Status*
|Zeigt den Status der Nachbestellung an.

| *Währung*
|Zeigt die Währung des Nachbestellung an.

| *Rechnungsbetrag*
|Zeigt den Rechnungsbetrag der Nachbestellung an.

| *Externe Auftrags-ID*
|Zeigt die externe ID des Auftrags an.

| *Hauptdokument*
|Wurde bereits ein Dokument für die Nachbestellung erstellt, wird die Nummer des Dokuments angezeigt. Mit Klick auf die Nummer wird das Dokument geöffnet.

| *Bestelldatum*
|Zeigt das Bestelldatum an.

| *Zahlungsziel*
|Zeigt die Eigner:in der Nachbestellung an.

| *Lieferdatum*
|Zeigt die Eigner:in der Nachbestellung an.

| *Abschlussdatum*
|Zeigt das Abschlussdatum der Nachbestellung an.

| *Benutzerdefinierte Eigenschaft (1-5)*
|Zeigt die ausgewählte benutzerdefinierte Eigenschaft an. Es sind 5 Felder verfügbar.

| *Abschlussdatum*
|Zeigt die Adresse des Ziellagers an.

|===

[#170]
==== Felder konfigurieren

Für die von dir gewählten Felder kannst du weitere Einstellungen vornehmen und so beispielsweise die Feldgröße bestimmen, den Titel ändern oder eine farbliche Markierung hinzufügen. Gehe dazu vor wie folgt.

[.instruction]
Felder konfigurieren:

. Öffne das Menü *Waren » Nachbestellung (Testphase)*.
. Führe die Suche (material:search[]) aus, um Nachbestellungen anzuzeigen.
. Klicke oben rechts auf *Ansicht bearbeiten* (terra:design_inline_edit[]), um die Kompaktansicht im Bearbeitungsmodus zu gestalten.
. Klicke oben rechts in der Hauptansicht auf *Bearbeiten* (material:edit[role=skyBlue]). +
→ Der Bearbeitungsmodus wird geöffnet.
. Klappe die Felder aus (material:chevron_right[]), um die Felder zu konfigurieren. Beachte dazu die Erläuterungen in <<#table-reorder-view-field-settings>>.
. Bist du mit den Einstellungen der Felder zufrieden, klicke oben rechts auf *Ansicht speichern* (material:save[role=skyBlue]). +
→ Die Änderungen werden gespeichert.

[[table-reorder-view-field-settings]]
.Einstellungen für die Felder in der Kompaktansicht
[cols="1,3"]
|===

| *Benutzerdefinierter Feldname*
|Hier kannst du bei Bedarf einen anderen Titel für das jeweilige Feld eingeben.

| *Farbliche Markierung*
|Wähle optional eine farbliche Markierung, die links am Rand des jeweiligen Felds angezeigt wird. Dies kann dabei helfen, die Felder visuell voneinander abzugrenzen und hervorzuheben. Wählst du keine Farbe, wird standardmäßig eine graue Markierung am Feld angezeigt. +
Die folgenden Felder haben standardmäßig bereits die folgende Markierung: +
*Rechnungsadresse* = rot +
*Lieferadresse* = rot +
*Kontakt-ID* = blau +
*Hauptdokument* = blau

| *Feldgröße (horizontal)*
|Wähle, wie breit das Feld in der Übersicht angezeigt werden soll. Wähle zwischen den Optionen *klein*, *mittel* und *groß*. +
*_Hinweis:_* Für die Felder *Tags* und *Rechnungsadresse* kann außerdem die vertikale Feldgröße gewählt werden.

| *Nur Symbol anzeigen*
|Wähle, ob nur das Symbol für das Feld (z.B. für den Status) angezeigt werden soll. +
Beachte, dass diese Einstellung nur für bestimmte Felder verfügbar ist.

| *Anzeigen in Kopfzeile*
|Wähle, ob das Feld auch in der Kopfzeile der Nachbestellung angezeigt werden soll. 
Beachte, dass diese Einstellung nur für bestimmte Felder verfügbar ist.

|===

[#190]
==== Funktionen und Filter-Einstellungen wählen

Im Bearbeitungsmodus kannst du außerdem einstellen, welche Funktionen und Filter in der Nachbestellungsübersicht angezeigt werden sollen. Um die Einstellungen vorzunehmen, gehe vor wie folgt.

[.instruction]
Funktionen und Filter wählen:

. Öffne das Menü *Waren » Nachbestellung (Testphase)*.
. Führe die Suche (material:search[]) aus, um Aufträge anzuzeigen.
. Klicke oben rechts auf *Ansicht bearbeiten* (terra:design_inline_edit[]), um die Kompaktansicht im Bearbeitungsmodus zu gestalten.
. Klicke oben rechts in der Hauptansicht auf *Bearbeiten* (material:edit[role=skyBlue]). +
→ Der Bearbeitungsmodus wird geöffnet.
. Nimm rechts oben im Bereich *Einstellungen* die Einstellungen für die Ansicht vor. Beachte dazu die Erläuterungen in <<#table-general-settings-reorder-view>>.
. Bist du mit den Einstellungen der Ansicht zufrieden, klicke oben rechts auf *Ansicht speichern* (material:save[role=skyBlue]). +
→ Die Änderungen werden gespeichert.

[[table-general-settings-reorder-view]]
.Einstellungen für Funktionen und Filter
[cols="1,3"]
|===

| *Gruppenfunktionen*
|Wähle, welche xref:working-with-reorders.adoc#100[Gruppenfunktionen] standardmäßig für Nachbestellungen angezeigt werden sollen. Alle restlichen Gruppenfunktionen sind dann direkt daneben im Kontextmenü (material:more_vert[]) verfügbar.

| *Menüfunktionen*
|Wähle, welche Menüfunktionen standardmäßig für Aufträge angezeigt werden sollen. Alle restlichen Menüfunktionen sind dann direkt daneben im Kontextmenü (material:more_vert[]) verfügbar.

| *Kopfzeile farbliche Markierung*
|Wähle, ob die Kopfzeile die Farbe des Status, eine benutzerdefinierte Farbe oder gar keine Farbe haben soll. 

| *Filter*
|Wähle, in wie vielen Spalten die gewählten Filter in der Filterauswahl angezeigt werden sollen.

| *Autovervollständigung*
|Wähle, wonach in der Schnellsuche bei einer Eingabe automatisch gesucht werden soll. Setze dazu ein Häkchen (material:check_box[role=skyBlue]) für alle gewünschten Optionen.

|===

[TIP]
.Nach Nachbestellungen sortieren
====
In der Kompaktansicht kannst du deine Aufträge nach *Auftrags-ID* und *Status* sortieren. Wähle dazu eine der Optionen aus der Dropdown-Liste *Sortieren nach* und entscheide, ob du die Nachbestellungen *Absteigend* (material:arrow_downward[]) oder *Aufsteigend* (material:arrow_upward[]) sortieren möchtest.
====