= Die plentyWarehouse App
:keywords: plentyWarehouse, plenty Warehouse, plentyWarehouse Übersicht, plenty Warehouse Übersicht
:description: Die plentyWarehouse App bietet dir zahlreiche Möglichkeiten, die mobile Warenwirtschaft einfach und effizient abzuwickeln.
:author: team-app-bi

Die plentyWarehouse App bietet dir zahlreiche Möglichkeiten, die mobile Warenwirtschaft einfach und effizient abzuwickeln.
Nach und nach überführen wir alle Funktionen zur Warenwirtschaft aus der xref:app:app.adoc#[bereits bekannten plentysystems App] in die neue plentyWarehouse App. Unser Ziel dabei sind die Schaffung intuitiverer Bedienkonzepte, eine stabile Performance und eine zuverlässige, hochaktuelle technische Basis. Von all diesen Vorteilen und einer Reihe ganz neuer Entwicklungen profitierst du, wenn du die plentyWarehouse App herunterlädst.

[#100]
== Welche Funktionen bietet die plentyWarehouse App?

Die plentypWarehouse App beinhaltet eine Reihe von Funktionen. Klicke auf die einzelnen Einträge in der Liste, um zur entsprechenden Handbuchseite mit weiteren Informationen und Anleitungen zu gelangen.

* xref:warenwirtschaft:installation-und-ersteinrichtung.adoc#[Installation und Ersteinrichtung]
* xref:warenwirtschaft:artikel-und-lagerorte.adoc#100[Artikelsuche]
* xref:warenwirtschaft:artikel-und-lagerorte.adoc#400[Lagerorte inspizieren]
* xref:warenwirtschaft:booking-incoming-items.adoc#[Wareneingänge erfassen]
* xref:warenwirtschaft:artikel-umbuchen.adoc#[Artikel umbuchen]
* xref:warenwirtschaft:artikel-verraeumen.adoc#[Artikel verräumen]
* xref:warenwirtschaft:inventur-durchfuehren.adoc#[Inventur durchführen]
* xref:warenwirtschaft:mobile-picklisten.adoc#[Mit Picklisten arbeiten]
* xref:warenwirtschaft:rollende-kommissionierung.adoc#[Rollende Kommissionierung durchführen]
* xref:warenwirtschaft:etiketten-drucken.adoc#[Etiketten für Artikel und Lagerorte drucken]

[#200]
== Die plentyWarehouse App herunterladen und installieren

Lade die plentyWarehouse App herunter und installiere sie auf einem passenden Gerät.

* link:https://play.google.com/store/apps/details?id=com.plentysystems.plentywarehouse[Die plentyWarehouse App im Google Play Store^]

include::app:partial$hardware-plentywarehouse.adoc[]

[#300]
== Welche Schritte gehören zur Einrichtung?

Du hast die plentyWarehouse App heruntergeladen und auf der passenden Hardware installiert? Dann kannst du mit der Einrichtung fortfahren.

Auf der Handbuchseite xref:warenwirtschaft:installation-und-ersteinrichtung.adoc#[Installation und Ersteinrichtung] findest du detaillierte Informationen zum ersten Login in der App, zur allgemeinen Orientierung und zu den grundlegenden Einstellungen, die du vor dem produktiven Einsatz von plentyWarehouse vornehmen musst.

[#400]
=== Auf dem Laufenden bleiben

Wartest du sehnsüchtig auf ein neues Feature? Wir informieren dich gerne über Änderungen an der Software! Versionen der plentyWarehouse App sind durch Versionsnummern gekennzeichnet. Änderungen werden zudem link:https://forum.plentymarkets.com/c/app-pos/plentywarehouse/579[in einem Changelog^] veröffentlicht. Abonniere den Changelog und bleibe immer auf dem Laufenden.
