= Die plentyWarehouse App (Beta)
:keywords: plentyWarehouse, plenty Warehouse, plentyWarehouse Übersicht, plenty Warehouse Übersicht
:description: Die neu entwickelte plentyWarehouse App bietet dir zahlreiche Möglichkeiten, die mobile Warenwirtschaft einfach und effizient abzuwickeln.
:author: team-app-bi

Die neu entwickelte plentyWarehouse App bietet dir zahlreiche Möglichkeiten, die mobile Warenwirtschaft einfach und effizient abzuwickeln.
Nach und nach überführen wir alle Funktionen zur Warenwirtschaft aus der xref:app:app.adoc#[bereits bekannten plentymarkets App] in die neue plentyWarehouse App. Unser Ziel dabei sind die Schaffung intuitiverer Bedienkonzepte, eine stabile Performance und eine zuverlässige, hochaktuelle technische Basis. Von all diesen Vorteilen und einer Reihe ganz neuer Entwicklungen profitierst du, wenn du die plentyWarehouse App herunterlädst.

[IMPORTANT]
.Hinweise zum aktuellen Stand der plentyWarehouse App
====
Die plentyWarehouse App befindet sich in der offenen Beta-Phase. Das bedeutet, dass wir fortlaufend Anpassungen und Fehlerbehebungen vornehmen und schrittweise neue Versionen veröffentlichen, die diese Änderungen enthalten. Ebenso werden die enthaltenen Funktionen Schritt für Schritt erweitert. Feedback und Fragen nehmen wir in dieser Phase gern im link:https://forum.plentymarkets.com/c/app-pos/plentywarehouse/579[Forum^] entgegen. Dort findest du auch jederzeit aktuelle Informationen.
====

[#100]
== Welche Funktionen bietet die plentyWarehouse App?

Aktuell sind folgende Funktionen in plentyWarehouse enthalten. Klicke auf die einzelnen Einträge in der Liste, um zu den entsprechenden Handbuchseite mit weiteren Informationen und Anleitungen zu gelangen.

* xref:warenwirtschaft:artikel-und-lagerorte.adoc#100[Artikelsuche]
* xref:warenwirtschaft:artikel-und-lagerorte.adoc#400[Lagerorte inspizieren]
* xref:warenwirtschaft:artikel-umbuchen.adoc#[Artikel umbuchen]
* xref:warenwirtschaft:artikel-verraeumen.adoc#[Artikel verräumen]
* xref:warenwirtschaft:inventur-durchfuehren.adoc#[Inventur durchführen]
* xref:warenwirtschaft:mobile-picklisten.adoc#[Mit Picklisten arbeiten]
* xref:warenwirtschaft:rollende-kommissionierung.adoc#[Rollende Kommissionierung durchführen]
* xref:warenwirtschaft:etiketten-drucken.adoc#[Etiketten für Artikel und Lagerorte drucken]

[#200]
== Die plentyWarehouse App herunterladen und installieren

Lade die plentyWarehouse App herunter und installiere sie auf einem passenden Gerät.

* link:https://play.google.com/store/apps/details?id=com.plentysystems.plentywarehouse[Die plentyWarehouse App im Google Play Store^]

include::app:partial$hardware-plentywarehouse.adoc[]

[#300]
== Welche Schritte gehören zur Einrichtung?

Du hast die plentyWarehouse App heruntergeladen und auf der passenden Hardware installiert? Dann kannst du mit der Einrichtung fortfahren.

Auf der Handbuchseite xref:warenwirtschaft:installation-und-ersteinrichtung.adoc#[Installation und Ersteinrichtung] findest du detaillierte Informationen zum ersten Login in der App, zur allgemeinen Orientierung und zu den grundlegenden Einstellungen, die du vor dem produktiven Einsatz von plentyWarehouse vornehmen musst.
