= Lagerorte mit Eigenschaften charakterisieren
:keywords: Eigenschaft, Lagerort Eigenschaft, Lagerort-Eigenschaft, Lagerorteigenschaft, Eigenschaften, Lagerort Eigenschaften, Lagerort-Eigenschaften, Lagerorteigenschaften, Eigenschaft erstellen, Eigenschaftstyp, Eigenschaft-Typ, Eigenschaftsgruppe, Eigenschaft bearbeiten, Auswahleigenschaft, Auswahleigenschaften, Lagerort charakterisieren, Lagerorte charakterisieren
:description: Durch das Anlegen von Eigenschaften kannst du deine Lagerorte über die Standard-Datenfelder in plentymarkets hinaus charakterisieren. Zum Beispiel, die Information, dass ein Lagerort für Kühlwaren geeignet ist.
:id: QP7QGZW
:author: team-stock

////
zuletzt bearbeitet 06.05.2022
////

Eigenschaften kannst du dir als zusätzliche Datenfelder vorstellen, die nicht standardmäßig in plentymarkets enthalten sind.
Durch das Anlegen von Eigenschaften kannst du deine Lagerorte über die Standard-Datenfelder hinaus charakterisieren.
Zum Beispiel, die Information, dass ein Lagerort für Kühlwaren geeignet ist.

//#video#

Diese Handbuchseite führt dich Schritt für Schritt durch die manuelle Anlage von Eigenschaften:

* xref:warenwirtschaft:properties.adoc#60[Erstelle die Eigenschaften] und xref:warenwirtschaft:properties.adoc#10[sortiere sie in Gruppen].
* xref:warenwirtschaft:properties.adoc#70[Verknüpfe die Eigenschaften] mit den passenden Lagerorten.

[#10]
== Gruppen

Im Laufe der Zeit wirst du wahrscheinlich sehr viele Eigenschaften für unterschiedliche Anwendungsfälle benötigen.
Gruppen helfen dir dabei, den Überblick zu behalten.

[#20]
=== Neue Gruppe erstellen

Erstelle zuerst alle nötigen Gruppen, z.B. die Gruppe "Lager Berlin".

. Öffne das Menü *Einrichtung » Einstellungen » Eigenschaften » Gruppen*.
. Klicke auf icon:plus[role="darkGrey"] *Gruppe erstellen*.
. Passe die Einstellungen an deine Bedürfnisse an.
. Speichere (icon:save[set=plenty, role="darkGrey"]) die Einstellungen.

//#GIF#

==== Details

[cols="1,4a"]
|====
|Einstellung |Erläuterung

| *ID*
|Sobald du die Gruppe erstmalig gespeichert hast, erhält sie automatisch eine fortlaufende und einzigartige ID.
Die ID kann nicht geändert werden.

| *Position*
|Gib eine Positionsnummer für die Eigenschaftsgruppe ein.
Standardmäßig wird aufsteigend nach Positionsnummer sortiert.
Wenn ein Lagerort Eigenschaften aus mehreren Gruppen hat, werden die Gruppen aufsteigend dargestellt.

*_Tipp_*: Speichere die Positionsnummern in 10er-Schritten, damit du mögliche neue Eigenschaftsgruppen dazwischen einfügen kannst.

| *Gruppentyp*
|Diese Option ist nicht für Lagerort-Eigenschaften relevant.
Sie ist für einen anderen Anwendungsfall gedacht: nämlich für xref:artikel:personalisierte-artikel.adoc#[Bestelleigenschaften vom Typ Kein].

| *Aufpreistyp*
|Diese Option ist nicht für Lagerort-Eigenschaften relevant.
Sie ist für einen anderen Anwendungsfall gedacht: nämlich für xref:artikel:personalisierte-artikel.adoc#[Bestelleigenschaften].

|====

==== Namen

[cols="1,4a"]
|======
|Einstellung |Erläuterung

| *Name*
|Gib einen Namen für die Eigenschaftsgruppe in der angegebenen Sprache ein.

*_Hinweis_*: Klicke auf icon:plus[role="darkGrey"], um den Namen in weitere Sprachen zu übersetzen.

| *Beschreibung*
|Gib eine Beschreibung für die Eigenschaftsgruppe in der angegebenen Sprache ein.

*_Hinweis_*: Klicke auf icon:plus[role="darkGrey"], um die Beschreibung in weitere Sprachen zu übersetzen.

| icon:plus[role="darkGrey"]
|Soll der Gruppenname in mehreren Sprachen verfügbar sein?

. Klicke auf icon:plus[role="darkGrey"] und wähle eine Sprachversion aus der Dropdown-Liste.
. Gib Übersetzungen für den Namen und die Beschreibung ein.
|======

[#30]
=== Bestehende Gruppe suchen

Zuvor erstellte Eigenschaftsgruppen werden in einer Übersicht angezeigt.

. Öffne das Menü *Einrichtung » Einstellungen » Eigenschaften » Gruppen*.
.. *_Option 1_*: Klicke auf icon:search[role="darkGrey"], um eine Liste aller Gruppen zu sehen.
.. *_Option 2_*: Klicke auf icon:filter[role="darkGrey"], um die Suchergebnisse mit Hilfe von Filtern einzugrenzen.
. Klicke auf eine Gruppe in der Ergebnisliste, um eine Detailansicht zu öffnen.
Dort kannst du die Einstellungen der Gruppe ändern.

[cols="1,4"]
|====
|Filter |Erläuterung

| *ID*
|Gib eine ID ein, um nach der Gruppe mit genau dieser ID zu suchen.

*_Hintergrund-Info_*: Bei der Erstellung erhält jede Gruppe automatisch eine fortlaufende und einzigartige ID.

| *Name*
|Gib einen Namen ein, um nach Gruppen mit diesem Namen zu suchen.
Es ist auch möglich, nach Teilen des Namens zu suchen.

| *ZURÜCKSETZEN*
|Setzt die gewählten Filterkriterien zurück.

| *SUCHEN*
|Führt die Suche aus. Die gefundenen Gruppen werden in der Übersicht angezeigt.

*_Tipp_*: Setze keine Filter, wenn du alle Gruppen in der Übersicht sehen möchtest.
|====

[#40]
=== Gruppe wieder löschen

Bereits erstellte Gruppen werden im Menü *Einrichtung » Einstellungen » Eigenschaften » Gruppen* angezeigt.
Gruppen können hier auch gelöscht werden.

. Wähle die Gruppen (icon:check-square[role="blue"]), die du löschen möchtest.
. Klicke oben links auf icon:trash[role="darkGrey"].
. Bestätige deine Entscheidung.

*_Hinweis_*: Die Eigenschaften, die den Gruppen zugeordnet sind, bleiben erhalten.

[#50]
== Eigenschaften

Eigenschaften kannst du dir als zusätzliche Datenfelder vorstellen, die nicht standardmäßig in plentymarkets enthalten sind.
Durch das Anlegen von Eigenschaften kannst du deine Lagerorte über die Standard-Datenfelder hinaus charakterisieren.
Zum Beispiel, die Information, dass ein Lagerort für Kühlwaren geeignet ist.

[#60]
=== Neue Eigenschaft erstellen

Erstelle die Eigenschaften, die du zur Charakterisierung deiner Lagerorte verwenden möchtest, z.B. die Notiz "für Kühlwaren geeignet".

. Öffne das Menü *Einrichtung » Einstellungen » Eigenschaften » Konfiguration*.
. Klicke auf icon:plus[role="darkGrey"] *Eigenschaft erstellen*.
. Passe die Einstellungen an deine Bedürfnisse an.
. Speichere (icon:save[set=plenty, role="darkGrey"]) die Einstellungen.

//#GIF#

[#62]
==== Details

[cols="1,4a"]
|======
|Einstellung |Erläuterung

| *ID*
|Sobald du die Eigenschaft erstmalig gespeichert hast, erhält sie automatisch eine fortlaufende und einzigartige ID.
Die ID kann nicht geändert werden.

| *Bereich* +
([red]#Pflichtfeld#)
|Wofür möchtest du die Eigenschaft nutzen?
Wähle den entsprechenden Bereich aus der Dropdown-Liste.
Je nachdem, welchen Bereich du hier wählst, ändern sich die weiteren Einstellungen im Menü.

*_Hinweis_*: Diese Einstellung kann nach dem Speichern nicht mehr geändert werden.

*_Hinweis_*: Diese Handbuchseite erklärt Eigenschaften vom Bereich *Lagerort*.
Solche Eigenschaften werden zur Charakterisierung von deinen Lagerorten verwendet.
Eigenschaften können aber auch für die nähere Charakterisierung von xref:artikel:eigenschaften.adoc#500[Artikeln] oder xref:crm:kontakte-verwalten.adoc#950[Kontakten] verwendet werden.
Klicke auf die Links, um mehr über diese anderen Anwendungsfälle zu erfahren.

| *Typ* +
([red]#Pflichtfeld#)
|Welche Art von Eigenschaft möchtest du anlegen?
Wähle den Eigenschaftstyp aus der Dropdown-Liste.

*_Hinweis_*: Diese Einstellung kann nach dem Speichern nicht mehr geändert werden.

[cols="1,4a"]
!======
!Typ !Wofür ist der Typ geeignet?

! *Kein*
!Der Name der Eigenschaft kann angezeigt werden.
Dies eignet sich, z.B. um Stichwörter für einen Lagerort hervorzuheben ("für Kühlwaren geeignet").

! *Auswahl*
!Eignet sich für Situationen, in denen es zwar mehrere Auswahlmöglichkeiten gibt, aber nur eine davon auf den Lagerort zutrifft.

*_Anwendungsbeispiel_*: +
Stell dir vor, du hast mehrere Kühl- und Gefrierschränke in deinem Lager.
Die Kühlschränke werden zur Lagerung von Lebensmitteln bei 4° C verwendet.
Die Gefrierschränke werden zur Lagerung von Lebensmitteln bei -18° C verwendet.
Bei den Kühlschränken soll die Information "Temperatur: 4° C" angezeigt werden und bei den Gefrierschränken die Information "Temperatur: -18° C".

. xref:warenwirtschaft:properties.adoc#66[Erstens]: Erstellst du die verschiedenen Auswahlmöglichkeiten, wie 4° C und -18° C.
. xref:warenwirtschaft:properties.adoc#70[Zweitens]: Während du die Eigenschaft mit deinen Lagerorten verknüpfst, gibst du an, welche Lagerorte den Wert "4° C" haben sollen und welche den Wert "-18° C".

!======

| *Position* +
([red]#Pflichtfeld#)
|Gib eine Positionsnummer für die Eigenschaft ein.
Standardmäßig wird aufsteigend nach Positionsnummer sortiert.

*_Tipp_*: Speichere die Positionsnummern in 10er-Schritten, damit du mögliche neue Eigenschaften dazwischen einfügen kannst.
|======

[#64]
==== Namen

[cols="1,4a"]
|======
|Einstellung |Erläuterung

| *Name* +
([red]#Pflichtfeld#)
|Gib einen Namen für die Eigenschaft in der angegebenen Sprache ein.

*_Hinweis_*: Der Name ist auf 255 Zeichen begrenzt.

*_Hinweis_*: Klicke auf icon:plus[role="darkGrey"], um den Namen in weitere Sprachen zu übersetzen.

| *Beschreibung*
|Gib eine Beschreibung für die Eigenschaft in der angegebenen Sprache ein.

*_Hinweis_*: Klicke auf icon:plus[role="darkGrey"], um die Beschreibung in weitere Sprachen zu übersetzen.

| icon:plus[role="darkGrey"]
|Soll der Eigenschaftsname in mehreren Sprachen verfügbar sein?

. Klicke auf icon:plus[role="darkGrey"] und wähle eine Sprachversion aus der Dropdown-Liste.
. Gib Übersetzungen für den Namen und die Beschreibung ein.
|======

[#66]
==== Auswahlwerte

[IMPORTANT]
.Nicht für jeden Eigenschaftstyp sichtbar
====
Diesen Bereich siehst du nur, wenn du mit einer Eigenschaft vom Typ *Auswahl* arbeitest.
Dieser Bereich ist für Eigenschaften vom Typ *Kein* unsichtbar.
====

Hier definierst du die einzelnen Werte, die zur Auswahl stehen.

. Klicke auf *Auswahlwert anlegen* (icon:plus[role="darkGrey"]). +
→ Das Fenster *Auswahlwert anlegen* wird geöffnet.
. Gib einen Namen für den Wert in der angegebenen Sprache ein. +
*_Hinweis_*: Der Name ist auf 255 Zeichen begrenzt.
Es gibt keine visuelle Anzeige, wenn diese Grenze überschritten wird.
Beim Speichern des Auswahlwertes wird der Name nach 255 Zeichen abgeschnitten.
. Wähle bei Bedarf eine Positionsnummer.
. Klicke auf *Speichern*. +
→ Der Wert wird erstellt und in der Übersicht angezeigt.
Der Wert erhält automatisch eine fortlaufende und einzigartige ID, die nicht geändert werden kann.
. Soll der Auswahlwert-Name in mehreren Sprachen verfügbar sein?
Dann klicke auf den Wert, um eine Detailansicht zu öffnen.
Dort kannst du Übersetzungen und Beschreibungen für den Wert eingeben.

[#68]
==== Gruppen

[cols="1,4a"]
|======
|Einstellung |Erläuterung

| *Gruppen* +
([red]#Pflichtfeld#)
|Jede Eigenschaft muss zu mindestens einer Gruppe gehören.
Wähle die passende Gruppe aus der Dropdown-Liste aus.
Die gewählten Gruppen werden hier als sogenannte "Chips" dargestellt.
Klicke auf icon:close[set=darkGrey], um eine Gruppe wieder zu entfernen.

*_Hinweis_*: Diese Dropdown-Liste enthält nur xref:artikel:eigenschaften.adoc#1200[Eigenschaftsgruppen, die bereits angelegt wurden].
|======

[TIP]
.Mehrere Eigenschaften einer Gruppe zuordnen
====
plentymarkets enthält eine Funktion, mit der du mehrere Eigenschaften gleichzeitig einer Gruppe zuordnen kannst.

. Öffne das Menü *Einrichtung » Einstellungen » Eigenschaften » Konfiguration*.
. Wähle die Eigenschaften (icon:check-square[role="blue"]), die du der Gruppe zuordnen möchtest.
. Klicke auf *Gruppen verknüpfen* (icon:link[set=material]). +
→ Das Fenster *Gruppen verknüpfen* wird geöffnet.
. Wähle eine oder mehrere Eigenschaftsgruppen (icon:check-square[role="blue"]).
. Klicke auf *Link*. +
→ Die gewählten Eigenschaften werden den Gruppen zugeordnet.
====

[#70]
=== Eigenschaften mit Lagerorten verknüpfen

Nachdem du eine Eigenschaft erstellt hast, kannst du sie mit einem Lagerort verknüpfen.

. Öffne das Menü *Einrichtung » Waren » Lager » [Lager wählen] » Lagerorte*.
. Suche (icon:search[role="blue"]) den Lagerort anhand der Filtereinstellungen.
. Klicke auf einen Lagerort, um seine Details zu sehen.
Hier kannst du bis zu 3 Eigenschaften und die dazugehörigen Werte hinzufügen.
.. Wähle die Eigenschaft aus der Dropdown-Liste *Eigenschaft* aus.
.. Wähle den Wert aus der Dropdown-Liste *Wert* aus.
Dieses Feld ist nur verfügbar, wenn die Eigenschaft vom Typ Auswahl ist.
. *Speichere* (icon:save[set=plenty, role="green"]) die Einstellungen. +
→ Die Eigenschaften werden mit dem Lagerort verknüpft.

//#GIF#

[TIP]
.Mehrere Lagerorte mit Eigenschaften verknüpfen
====
Nutze die Gruppenfunktion (icon:cog[role="darkGrey"]), wenn du mehreren Lagerorten gleichzeitig mit Eigenschaften verknüpfen möchtest.
====

[#80]
=== Bestehende Eigenschaften suchen

Zuvor erstellte Eigenschaften werden in einer Übersicht angezeigt.

include::_includes:page$eigenschaften-suchen.adoc[]

[#90]
=== Eigenschaften exportieren

:stock:
include::_includes:page$eigenschaften-exportieren.adoc[]

:!stock:

[#100]
=== Eigenschaften wieder löschen

include::_includes:page$eigenschaften-loeschen.adoc[]

[#110]
== Fragen und Antworten

[.collapseBox]
.*Kann ich die Eigenschaften importieren, anstatt sie manuell anzulegen?*
--

Ja.
Wenn du ganz viele Eigenschaften erstellen will, dann kannst eine Menge Zeit sparen, indem du sie importierst.

* xref:daten:praxisbeispiel-elasticsync-eigenschaften.adoc#[Dieses praktische Beispiel] führt dich Schritt für Schritt durch den Import-Prozess.
* xref:daten:elasticSync-eigenschaften.adoc#[Diese Referenz-Seite] erläutert die Abgleich- und Zuordnungsfelder, die dir beim Importieren von Eigenschaften und Eigenschaftsgruppen zur Verfügung stehen.

--

[.collapseBox]
.*Kann ich Eigenschaften auch zur Charakterisierung von Produkten und Kontakten verwenden?*
--

Ja.
Eigenschaften können auch für die nähere Charakterisierung von xref:artikel:eigenschaften.adoc#[Produkten] oder xref:crm:kontakte-verwalten.adoc#950[Kontakte] verwendet werden.
Klicke auf die Links, um mehr über diese andere Anwendungsfälle zu erfahren.

--
