= plentyWarehouse: Rechteverwaltung
:keywords:
:description:
:author: team-app-bi

////
Auf diese Seite wird aus dem Ankündigungs-Popup in der plentyWarehouse App verlinkt. Sie soll Informationen enthalten, wie die Rechte in plentyWarehouse ab Ende Juni funktionieren und was die ToDos für User sind. Diese Seite bleibt im Handbuch unsichtbar und ist nur für diesen Zweck gedacht, da App-User von ihren Geräten meist nicht für weitere Informationen das Forum aufrufen können. Diese Seite wird ca. im Juli 2023 gelöscht. Keine andere Stelle darf auf diese Seite verlinken!
////

== Rechte für Rollen vergeben

Gewähre Rollen von Benutzern, die *_nicht_* vom Typ *Administrator* sind, die Rechte für Funktionen innerhalb der plentyWarehouse App. 

Erledige diesen Schritt vor Ende Juni 2023.

[WARNING]
.Bereits vorhandene Berechtigungen sind weiterhin notwendig!
====
Die bestehenden Berechtigungen für das plentymarkets Backend, die für die korrekte Funktionsweise von plentyWarehouse benötigt werden (Beispiel: xref:warenwirtschaft:booking-incoming-items.adoc#150[Berechtigungen für den Wareneingang]), bleiben von dieser Änderung unberührt und sind weiterhin notwendig.
====

[.instruction]
Rechte für Rollen vergeben:

. Logge dich mit einem Admin-Zugang in deinem plentymarkets System ein.
. Öffne das Menü *Einrichtung » Kontoverwaltung » Rollen*.
. Klicke auf *Suchen* icon:search[role="darkGrey"]. +
→ Alle im System vorhandenen Rollen werden aufgelistet.
. Öffne die gewünschte Rolle.
. Aktiviere material:check_box[role=skyBlue] die Funktionen, die für die Rolle sichtbar und somit in plentyWarehouse nutzbar sein sollen. Beachte auch die Einzelberechtigungen zur Funktion *Wareneingang*.
. *Speichere* icon:save[role="darkGrey"] die Einstellungen. +
→ Die gewählten Funktionen sind für die Rolle sichtbar.

[TIP]
.Brauchst du Hilfe?
====
In unserer link:https://forum.plentymarkets.com/c/app-pos/plentywarehouse/579[Kategorie im Forum^] findest du die richtigen Ansprechpartner für individuelle Fragen und Probleme. Dort erhältst du auch kurzfristig die aktuellsten Informationen zum Thema.
====