= Rollende Kommissionierung
:author: team-mobile
:keywords: plentyWarehouse Box-Kommissionierung, plentyWarehouse rollende Kommissionierung, mobil kommissionieren, mobile Kommissionierung
:description: Erfahre, wie die rollende Kommissionierung in der plentyWarehouse App funktioniert.

include::partial$hinweis-voraussetzungen.adoc[]
include::partial$hinweis-offene-beta.adoc[]

Mit der rollenden Kommissionierung können deine Mitarbeiter:innen im Lager mehrere Aufträge gleichzeitig picken und versandfertig vorsortiert an den Packtisch liefern.

Die plentyWarehouse App bietet dir eine überarbeitete und optimierte Funktion zur rollenden Kommissionierung. Auf dieser Handbuchseite findest du alle notwendigen Informationen.

Zunächst folgt eine <<#100, kurze Beschreibung der rollenden Kommissionierung>>, die den Ablauf erklärt. Danach werden die <<#200, Einstellungen>> beschrieben, die du im Voraus vornehmen solltest. Diese Einstellungen greifen dann später, wenn du die <<#800, Funktion nutzt>>.

[#100]
== Wie funktioniert die rollende Kommissionierung?

Klappe die Box unten auf, um mehr über den Ablauf bei der rollenden Kommissionierung zu erfahren.

[.collapseBox]
.Ablauf der rollenden Kommissionierung
--
Das Lagerpersonal hat einen Kommissionierwagen, der mit durch das Lager bewegt wird. Auf diesem Kommissionierwagen befindet sich eine beliebige Anzahl an Boxen. Jede Box wird dabei einem Auftrag zugeordnet, der abgewickelt werden soll.

Während das Lagerpersonal mit dem Wagen durch das Lager läuft, zeigt ein mobiles Endgerät an, welche Artikel gepickt werden sollen. Dabei werden gleiche Artikel gruppiert. Kommt der gleiche Artikel beispielsweise in zwei verschiedenen Aufträgen vor, sieht das Lagerpersonal direkt, dass zwei Exemplare dieses Artikels gepickt werden sollen. Das Lagerpersonal pickt den Artikel und legt ihn dann die Box, die zum jeweiligen Auftrag gehört. So wird jeder Artikel beim Picken automatisch dem entsprechenden Auftrag zugeordnet.

Sobald alle Boxen mit Artikeln befüllt sind, kehrt das Lagerpersonal zum Packtisch zurück. Nun wird die erste Box gescannt und somit der entsprechende Auftrag aufgerufen. Das Lagerpersonal wickelt diesen Auftrag dann wie gewohnt ab. Am Ende dieses Vorgangs wird die Verbindung zwischen Auftrag und Box aufgelöst. Somit steht die Box wieder zur Verfügung und kann vom Lagerpersonal beim nächsten Durchlauf erneut verwendet werden.
--

[IMPORTANT]
.Einstellungen für mehrere Lager vornehmen
====
Entscheide vorab, in wie welchen Lagern das Lagerpersonal die rollende Kommissionierung nutzen soll. Nimm dann die <<#200, einmaligen Einstellungen>> einzeln für jedes gewünschte Lager vor. 
====

[#200]
== Einstellungen zur rollenden Kommissionierung vornehmen

Wenn du zum ersten mal mit der Funktion zur rollenden Kommissionierung arbeitest, solltest du sicherstellen, dass die folgenden Einstellungen vorher durchgeführt werden. Ansonsten kommt es bei Problemen zum Ablauf.

[#300]
=== Einstellungen im plentymarkets Backend vornehmen

Bevor du <<#800, die rollende Kommissionierung nutzt>>, musst du ein paar Einstellungen einmalig in deinem plentymarkets System vornehmen. Diese Einstellungen bestimmen z.B., welche Boxen zur Verfügung stehen, welche Lagermitarbeiter:innen die rollende Kommissionierung nutzen dürfen und wann genau die Verknüpfung zwischen Auftrag und Box wieder aufgelöst werden soll.

[#400]
==== Boxen zur Verfügung stellen

Jeder Artikel wird im Lager an seinem eigenen xref:warenwirtschaft:lager-einrichten.adoc#500[Lagerort] aufbewahrt. Wenn das Lagerpersonal einen Auftrag pickt, wird der Artikel aus dem Lagerort geholt und in eine Box gelegt. Dort bleibt der Artikel so lange, bis der Auftrag fertig gepackt und versendet wurde.

Somit sind Boxen nichts anderes als temporäre Lagerorte. Wie “normale” Lagerorte auch, musst du Boxen einmalig im Voraus erstellen. Konkret erstellst du einen Lagerort pro Box und bestimmst dann, dass du diese Lagerorte zum Zweck der rollenden Kommissionierung verwenden möchtest.

[.instruction]
Boxen zur Verfügung stellen:

. Melde dich in deinem plentymarkets System an.
. Öffne das Menü *Einrichtung » Waren » Lager » [Lager wählen] » Lagerorte*.
. Erstelle neue Lagerorte für die rollende Kommissionierung. Beachte dabei die Erläuterungen im Kapitel xref:warenwirtschaft:lager-einrichten.adoc#500[Lagerorte generieren].
. Stelle den *Zweck* des Lagerortes auf *Box*.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#500]
==== Rechte für die rollende Kommissionierung vergeben

Bevor die rollende Kommissionierung mit plentyWarehouse durchgeführt wird, muss sichergestellt sein, dass alle Benutzer:innen über die entsprechenden Berechtigungen verfügen. Nur so können die Aufträge korrekt kommissioniert werden.

:rights-purpose: die rollende Kommissionierung in plentyWarehouse verwenden können
:right-one: pass:quotes[*Artikel > Artikel > Artikelbild > Arikelbildname > Anzeigen*]
:right-two: pass:quotes[*Aufträge > Anzeigen*]
:right-three: pass:quotes[*Aufträge > Aktualisieren*]
:right-four: pass:quotes[*Kommentare > Anzeigen*]
:right-five: pass:quotes[*Kommentare > Erstellen*]

include::_includes:page$rechte.adoc[]

[#600]
==== Abwicklungsprozesse anpassen
//TODO: Haben wir sowas für Prozesse?

Der Packvorgang der rollenden Kommissionierung kann im bestehenden xref:automatisierung:prozesse-einrichten.adoc#[Auftragsabwicklungsprozess] deines Unternehmens integriert werden. Dazu müssen jeweils eine Aktion und eine Subaktion zum bestehenden Abwicklungsprozess hinzugefügt werden.

[.instruction]
Bestehende Abwicklungsprozesse anpassen:

. Öffne das Menü *Einrichtung » Prozesse » [Prozess wählen]*.
. Füge die Aktion und die Subaktion hinzu. Nimm die Einstellungen gemäß <<table-procedure-subprocedure-picking>> vor.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[[table-procedure-subprocedure-picking]]
.Aktion und Subaktion für die rollende Kommissionierung
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Aktion: Auftragssuche*
|Füge die Aktion xref:automatisierung:aktionen.adoc#190[Auftragssuche] zum Arbeitsschritt xref:automatisierung:arbeitsschritte.adoc#auftragsbearbeitung[Auftragsbearbeitung] hinzu. Diese Aktion sucht nach einzelnen Aufträgen, um sie im Anschluss weiter zu bearbeiten. +
Öffne die Einstellungen zur Aktion und stelle den *Modus* auf *Box-Suche*. Somit bestimmst du, dass das Lagerpersonal die Box - d.h. den temporären Lagerort - scannen und plentymarkets daraufhin den entsprechenden Auftrag abrufen soll.

| *Subaktion: Entferne Auftrag von Box*
|Füge die Subaktion xref:automatisierung:subaktionen.adoc#195[Entferne Auftrag von Box] zur Aktion xref:automatisierung:aktionen.adoc#170[Auftrag] hinzu. Diese Subaktion löst die Verbindung zwischen Auftrag und Box. Somit steht die Box wieder frei zur Verfügung und kann beim nächsten Durchlauf wiederverwendet werden.
|====

[#700]
=== Einstellungen in der plentyWarehouse App vornehmen

Bevor du <<#800, die rollende Kommissionierung nutzen kannst>>, musst du ein paar Einstellungen einmalig in der plentyWarehouse App vornehmen. Diese Einstellungen bestimmen z.B., wie viele Aufträge auf einmal gepickt werden sollen und wie die App im Fehlerfall vorgehen soll.

[.instruction]
Einstellungen vornehmen:

. xref:warenwirtschaft:installation-und-ersteinrichtung.adoc#300[Logge dich in plentyWarehouse ein].
. Tippe auf das Menüsymbol (icon:bars[role="darkGrey"]) oben links.
. Tippe unten auf *Einstellungen* (icon:settings[set=material]). +
→ Das Einstellungsmenü öffnet sich.
. Tippe auf *Rollende Kommissionierung*.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<table-pw-settings-box-picking>>.

[[table-pw-settings-box-picking]]
.Einstellungen in der plentymarkets App vornehmen
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+^| Bereich *Allgemeine Einstellungen*
| *Lager*
|In welchem Lager möchtest du picken? Wenn du die rollende Kommissionierung später nutzt, werden nur Aufträge, die sich in diesem Lager befinden, auf deiner Artikelliste angezeigt. +
*_Tipp:_* Die xref:warenwirtschaft:lager-einrichten.adoc#200[Lager] in dieser Dropdown-Liste verwaltest du im Backend deines plentymarkets Systems unter *Einrichtung » Waren » Lager*.

| *Standardanzahl Boxen*
|Eine Box steht für einen Auftrag, der kommissioniert wird. Wähle hier aus, wie viele Aufträge du standardmäßig auf einmal picken möchtest. Wenn du die rollende Kommissionierung später nutzt, ist die hier ausgewählte Anzahl voreingestellt. Bevor du mit der rollenden Kommissionierung beginnst, kannst du diese Anzahl manuell erhöhen oder verringern.

| *Bestätigungsdialog vor Umbuchung anzeigen*
|Wenn du diese Option aktivierst, wirst du bei jedem Artikel, den du während der rollenden Kommissionierung pickst, gefragt, ob der Artikel wirklich in die Box gelegt werden soll. Du kannst erst mit dem nächsten Artikel fortfahren, wenn du diese Abfrage bestätigt hast.

| *Lagerort-Scan verpflichtend*
|Wie sollen die Boxen für die rollende Kommissionierung ausgewählt werden? +
*Aktiviert* (icon:toggle-on[role="green"]) = Boxen _müssen_ per Scan ausgewählt werden, damit anschließend Artikel gebucht werden können. +
*Nicht aktiviert* (icon:toggle-off[role="darkGrey"]) = Boxen können manuell ausgewählt werden, indem du auf sie tippst.

| *Sortierung der Aufträge*
|Diese Einstellung bestimmt, 

2+^| Bereich *Status*

| *Quellstatus*
|Welche Aufträge möchtest du picken? Wenn du die rollende Kommissionierung später nutzt, werden nur Aufträge, die sich in diesem Status befinden, auf deiner Artikelliste angezeigt. +
*_Tipp:_* Die xref:auftraege:auftraege-verwalten.adoc#1200[Status] in dieser Dropdown-Liste verwaltest du im Backend deines plentymarkets System unter *Einrichtung » Aufträge » Status*.

| *Zielstatus*
|Wie möchtest du Aufträge, die sich gerade im Pickvorgang befinden, kennzeichnen? Setze Aufträge in einen neuen Status, damit sie nicht aus Versehen mehrmals für den Pickvorgang zur Verfügung gestellt werden. +
*_Tipp:_* Die xref:auftraege:auftraege-verwalten.adoc#1200[Status] in dieser Dropdown-Liste verwaltest du im Backend deines plentymarkets System unter *Einrichtung » Aufträge » Status*.

| *Fehlerstatus*
|Wie soll die App im Fehlerfall vorgehen? Kommt es beim Picken eines Auftrags zu einem Fehler, wird der Auftrag in den hier gewählten Status gesetzt. Später kannst du dann in plentymarkets alle fehlerhaften Aufträge mit diesem Status suchen und diese gesondert abarbeiten. +
*_Tipp:_* Die xref:auftraege:auftraege-verwalten.adoc#1200[Status] in dieser Dropdown-Liste verwaltest du im Backend deines plentymarkets System unter *Einrichtung » Aufträge » Status*.

2+^| Bereich *Artikelerfassung*

| *Scan verpflichtend*
|

| *Einzelerfassung bis Menge*
|

2+^| Bereich *Box-Auswahl*

| *Lagerortsuchfelder*
| 

| *Fokus auf Lagerortsuchfeld*
|

|====

[#800]
== Mit der plentyWarehouse App kommissionieren

Nachdem du alle vorbereitenden Einstellungen vorgenommen hast, kannst du die plentyWarehouse App nutzen, um mehrere Aufträge gleichzeitig zu picken und versandfertig vorsortiert an den Packtisch zu liefern.

[IMPORTANT]
.Stehen Aufträge bereit?
====
Aufträge werden nur mit der App kommissioniert, wenn sie die Kriterien aus den <<#700, Einstellungen>> erfüllen, also wenn sie sich auf das richtige Lager beziehen und sich aktuell im ausgewählten Ausgangsstatus befinden. Erfüllen zur Zeit keine Aufträge diese Kriterien, sind keine Aufträge für die rollende Kommissionierung verfügbar.
====

[#900]
=== Anzahl der Boxen festlegen

Lege zuerst fest, mit wie vielen Boxen du arbeiten möchtest, d.h. wie viele Aufträge gleichzeitig kommissioniert werden sollen.

[.instruction]
Anzahl der Boxen festlegen:

. xref:warenwirtschaft:installation-und-ersteinrichtung.adoc#300[Logge dich in plentyWarehouse ein].
. Tippe auf das Menüsymbol (icon:bars[role="darkGrey"]) oben links. +
icon:map-signs[] *_Oder:_*: Finde die Kachel *Rollende Kommissionierung* im Bereich *Funktionen* auf dem Dashboard.
. Tippe auf *Rollende Kommissionierung*. +
→ Der Startbildschirm wird angezeigt.
. Tippe auf das Plus oder Minus, um die <<Einstellungen in der plentymarkets App vornehmen, vordefinierte Anzahl>> der Boxen zu erhöhen oder zu verringern. //TODO: intable link
. Tippe auf *Start*, um fortzufahren. +
→ Die entsprechenden Aufträge werden auf eine Artikelliste gestellt und in den von dir festgelegten Zielstatus //TODO: intable link gesetzt.


[#1000]
=== Artikel im Lager finden

plentymarkets erstellt automatisch eine Auflistung aller Artikel, die nun im Lager gepickt werden sollen. Dabei werden gleiche Artikel gruppiert. Kommt der gleiche Artikel beispielsweise in zwei verschiedenen Aufträgen vor, sieht das Lagerpersonal direkt, dass zwei Exemplare gepickt werden sollen.

Die Liste enthält wichtige Informationen zu den Artikeln, die gepickt werden sollen. Das Lagerpersonal sieht nicht nur, wie viele Exemplare eines Artikels gepickt werden sollen, sondern auch den Artikelnamen und den Lagerort des Artikels.

Nun läuft das Lagerpersonal mit dem Kommissionierwargen zum Lagerort des ersten Artikels. Dort angekommen, scannt das Lagerpersonal den Barcode des ersten Artikels. Alternativ kann in der App auf den Artikel getippt werden.

[.instruction]
Mit der Artikelliste arbeiten:

. Schaue auf die Liste, um herauszufinden, wo der Artikel gelagert wird.
. Laufe mit dem Kommissionierwagen zum Artikel.
. Scanne den Barcode des Artikels oder tippe in der App auf den Artikel.

[#1100]
=== Auftrag mit einer Box verknüpfen

In welcher Box willst du diesen Artikel zwischenlagern? Scanne eine leere Box oder tippe auf eine leere Box in der App. So werden Auftrag und Box miteinander verknüpft.

[IMPORTANT]
.Aufträge mit mehreren Artikeln
====
Manche Aufträge enthalten mehr als nur einen Artikel. Hast du bereits den ersten Artikel eines Auftrags gescannt und mit einer Box verknüpft, brauchst du beim zweiten Artikel keine weitere Box zu verknüpfen, sondern kannst die bereits angefangene Box weiter verwenden.
====

[#1200]
=== Artikel picken

plentyWarehouse zeigt dir einige wichtige Informationen zum Pickvorgang an. Somit siehst du die Anzahl der Artikel, die gepickt werden sollen, so wie den Lagerort, an dem sich die Artikel befinden.

[.instruction]
Artikel picken:

. Schaue in die App, um Informationen zum Pickvorgang zu erfassen.
. Scanne den Artikel oder tippe auf das Plus oder Minus, um die Anzahl der gepickten Exemplare anzupassen. +
*_Hinweis:_* Beim Scannen erhöht sich die Anzahl automatisch um eins.
. Lege die Exemplare in die entsprechende Box.
. Scanne die soeben gepickte Box oder tippe auf das grüne Häkchen, um den Pickvorgang abzuschließen. +
→ Im Hintergrund verknüpft plentymarkets den Artikel mit der Box. Der Lagerort des Artikels wird somit auf diesen temporären Lagerort geändert. Im plentymarkets System ist eine xref:warenwirtschaft:warenbestaende-verwalten.adoc#1100[Warenbewegung] zu sehen.
. Wiederhole Schritte 1 bis 4 für jeden Auftrag, der diesen Artikel enthält. +
→ Wurde dieser Artikel fertig gepickt, wechselt der Bildschirm zurück zur <<#1000, Artikelliste>> und du kannst mit dem nächsten Artikel fortfahren. +
→ Wurden alle Artikel fertig gepickt, wird der Abschlussbildschirm angezeigt. 
. Klicke auf das rote Häkchen, um die rollende Kommissionierung abzuschließen.

[#1300]
=== Zusätzliche Aktionen für Artikel

Während du <<#1200, Artikel pickst>>, kann es zu Sonderfällen kommen. Beispielsweise kann es sein, dass du einen Artikel ans Ende der Liste verschieben möchtest, weil du erst später am Lagerort des Artikels ankommst. Außerdem kann es sein, dass ein Artikel am Lagerort nicht vorrätig ist oder du eine Notiz mit einem Hinweis zum Auftrag hinterlassen möchtest.

Dazu stehen dir in der Ansicht des jeweiligen Artikels einige Shortcuts zur Verfügung, mit denen du diese Aktionen schnell durchführen kannst. <<table-box-picking-shortcuts>> enthält weitere Informationen zu den verfügbaren Shortcuts.

[[table-box-picking-shortcuts]]
.Verfügbare Shortcuts in der Artikelansicht
[cols="2,1,6"]
|====
|Bedienelement |Symbol |Erläuterung

|[intable-add-note]*Kommentar*
|icon:chat[set=material]
| Öffnet die Ansicht zur Eingabe einer Auftragsnotiz. Nutze diese Funktion, um einen Kommentar zu speichern, der in der späteren Abwicklung an jedem Auftrag, in dem der Artikel vorhanden ist, im Backend deines plentymarkets System einsehbar ist.

|[#intable-enter-quantity]*Menge eingeben*
|icon:iso[set=material]
| Öffnet die Ansicht zur Eingabe der Artikelmenge.

| *Artikel verschieben*
|icon:low_priority[set=material]
| Verschiebt den Artikel an das Ende der Pickliste. Diese Funktion ist nützlich, wenn du einen Artikel vorerst überspringen möchtest, beispielsweise wenn er momentan nicht am angegebenen Lagerort vorhanden ist.

| *Artikel entfernen*
|icon:cancel[set=material]
| Entfernt den Artikel von der Artikelliste. Nutze diese Funktion, wenn der betreffende Artikel nicht am Lagerort vorhanden ist. Optional kannst du im selben Schritt auch einen Kommentar eingeben, der als Auftragsnotiz gespeichert wird und am jedem Auftrag, in dem der Artikel enthalten ist, im plentymarkets Backend einsehbar ist. Außerdem wird der Auftrag in den Fehlerstatus verschoben.

| *Artikelinformationen* 
|icon:info[set=material]
| Öffnet eine Seite mit weiteren Informationen zum Artikel. Je nachdem, welche du Einstellung für die Option xref:warenwirtschaft:installation-und-ersteinrichtung.adoc#intable-other-settings[Shortcut-Verhalten]gewählt hast, erscheint eine Abfrage, ob du nach dem Aufrufen der Artikelinformationen automatisch zur Pickliste zurückgeleitet werden möchtest.

|====

[#1400]
=== Rollende Kommissionierung abschließen

//TODO: Info über Endscreen

[#1500]
=== Artikel packen

Sobald alle Boxen mit Artikeln befüllt sind, läuft das Lagerpersonal zum Packtisch zurück. Nun wird die erste Box gescannt und somit der entsprechende Auftrag aufgerufen. Das Lagerpersonal xref:automatisierung:prozesse-ausfuehren.adoc#[wickelt diesen Auftrag wie gewohnt ab]. Dabei wird der Warenausgang vom Transferlagerort, d.h. von der Box, gebucht.

Am Ende dieses Vorgangs wird die Verbindung zwischen Auftrag und Box aufgelöst. Somit steht die Box wieder zur Verfügung und kann vom Lagerpersonal beim nächsten Durchlauf erneut verwendet werden.
