= Einzelkommissionierung
:author: team-app
:keywords: Einzelkommissionierung plentyWarehouse, einzelne Aufträge picken plentyWarehouse, einzelnen Auftrag kommissionieren

include::partial$hinweis-voraussetzungen.adoc[]

Mit der **Einzelkommissionierung** lassen sich gezielt einzelne Aufträge suchen und die Artikel für diese Aufträge kommissionieren. Wird ein Auftrag über die in der Funktion integrierte Auftragssuche ausgewählt, wird für diesen Auftrag eine temporäre Pickliste generiert. Diese Pickliste wird dann in plentyWarehouse angezeigt und kann direkt abgearbeitet werden. Somit kannst du schnellstmöglich die Artikel für einzelne Aufträge kommissionieren, ohne erst im plentysystems Backend eine Pickliste generieren zu müssen. Hierduch entsteht nicht nur ein zeitlicher Vorteil für deine Auftragsabwicklung, sondern der gesamte Workflow wird vereinfacht und die Ware gelangt noch schneller auf den Weg zu deinen Kund:innen! 

[#100]
== Rechte für die Einzelkommissionierung vergeben

Bevor die Einzelkommissionierung durchgeführt wird, muss sichergestellt sein, dass alle Benutzer:innen ohne Rolle vom Typ *Administrator* über die entsprechenden Berechtigungen verfügen. Nur so kann die Einzelkommissionierung korrekt durchgeführt und die Bestandsänderungen im plentysystems Backend gespeichert werden.

:rights-purpose: die Funktion Einzelkommissionierung in plentyWarehouse nutzen können

:right-one: pass:quotes[*plentyWarehouse > Wareneingang > Einzelkommissionierung > Betrachten*]

include::_includes:partial$rights-simple-mode.adoc[]

[#150]
== Berechtigungen für Auftragsstatus erteilen

Typischerweise befinden sich Aufträge, die mit der Einzelkommissionierung abgearbeitet werden sollen, in bestimmten xref:auftraege:auftraege-verwalten.adoc#1200[Auftragsstatus]. Welche Status das genau sind, hängt individuell vom Workflow deines Unternehmens ab.

Um die Einzelkommissionierung fehlerfrei durchzuführen, musst du im plentysystems Backend genau diese Auftragsstatus zur Anzeige und zur Bearbeitung freigeben.

[.instruction]
Berechtigungen für Auftragsstatus freigeben:

. Öffne das Menü *Einrichtung » Kontoverwaltung » Rollen » [Rolle auswählen]*.
. Scrolle zum Bereich *Zugriffsrechte*.
. Öffne den Menüpunkt *Änderbare Auftragsstatus* (icon:chevron-down[role="darkGrey"]).
. *Aktiviere* (material:check_box[role=skyBlue]) die Auftragsstatus, in denen sich die Aufträge normalerweise befinden.
. Öffne den Menüpunkt *Sichtbare Auftragsstatus* (icon:chevron-down[role="darkGrey"]).
. *Aktiviere* (material:check_box[role=skyBlue]) auch hier die Auftragsstatus, in denen sich die Aufträge normalerweise befinden.
. Klicke auf *Speichern* (material:save[]).

[#200]
== Einstellungen zur Einzelkommissionierung vornehmen

Die Einzelkommissionierung in plentyWarehouse lässt sich mithilfe verschiedener Einstellungen auf deine Bedürfnisse und Arbeitsabläufe anpassen.

include::partial$plentywarehouse-rights-settings.adoc[]

Du kannst beispielsweise bestimmen, in welcher Reihenfolge die Artikel für die Einzelkommissionierung sortiert werden sollen. Außerdem kannst du vielfältige Statuseinstellungen für Szenarien wie den Fehlerfall vornehmen und festlegen, wie Artikel erfasst werden sollen. 

[.instruction]
Einstellungen zur Einzelkommissionierung vornehmen:

. xref:warenwirtschaft:installation-und-ersteinrichtung.adoc#300[Logge dich in plentyWarehouse ein].
. Tippe auf das Menüsymbol icon:bars[role="darkGrey"] oben links.
. Tippe unten auf *Einstellungen* material:settings[]. +
→ Das Einstellungsmenü wird geöffnet.
. Tippe auf *Einzelkommissionierung* material:shopping_cart_checkout[role="darkGrey"].
. Nimm die Einstellungen für die Einzelkommissionierung vor. Beachte dazu die Erläuterungen in <<table-pw-single-order-picking-settings>>.

[[table-pw-single-order-picking-settings]]
.Einstellungen zur Einzelkommissionierung in plentyWarehouse
[cols="1,3"]
|===
|Einstellung |Erläuterung

2+^| Bereich *Allgemeine Einstellungen*

| *Suchfelder*
| Verwende die Umschaltflächen, um festzulegen, welche Kriterien während der Suche nach Aufträgen, die du mit der Einzelkommissionierung abarbeiten möchtest, genutzt werden sollen. +
*Aktiviert* icon:toggle-on[role="green"] = Es wird möglich sein, Aufträge anhand dieses Kriteriums zu suchen. +
*_Tipp:_* Tippe und halte material:drag_handle[] für jedes aktivierte Suchkriterium, um die Reihenfolge der angezeigten Suchfelder anzupassen.

| *Fokus auf Suchfeld*
|Tippe auf das Suchfeld, in das der Cursor beim Öffnen der Funktion automatisch springen soll. Wenn du kein Suchfeld wählst, musst du bei der Suche erst in ein Feld tippen, bevor du den Suchwert eingeben kannst.

| *Sortierung*
|In welcher Reihenfolge sollen die Aufträge in den Suchergebnissen angezeigt werden? Wähle eine der beiden folgenden Optionen. +
*Datum absteigend* = Aufträge werden absteigend nach ihrem Erstellungsdatum sortiert. Somit beginnt die Liste mit der neuesten Auftrag. +
*Datum aufsteigend* = Aufträge werden aufsteigend nach ihrem Erstellungsdatum sortiert. Somit beginnt die Liste mit dem ältesten Auftrag.

| [#intable-item-name-prio]*Priorisierung von Artikelnamen*
|Tippe auf diese Option, um festzulegen, in welcher Reihenfolge die Bestandteile des Artikelnamens angezeigt werden, während du die Funktion verwendest. Tippe und halte (material:drag_handle[]) für jeden Bestandteil, um die Reihenfolge der angezeigten Bestandteile anzupassen.

| [#intable-close-pick-list]*Pickliste automatisch schließen*
|Aktiviere diese Option, um die Pickliste automatisch abzuschließen, wenn alle benötigten Artikel gepickt wurden.

2+^| Bereich *Status*

| [#intable-source-status]*Quellstatus*
|Welche Aufträge möchtest du picken? Wenn du die Einzelkommissionierung später nutzt, werden nur Aufträge, die sich in diesem Status befinden, auf deiner Artikelliste angezeigt. +
*_Tipp:_* Die xref:auftraege:auftraege-verwalten.adoc#1200[Status] in dieser Dropdown-Liste verwaltest du im Backend deines System unter *Einrichtung » Aufträge » Auftragsstatus*.

| [#intable-target-status]*Blockstatus*
|Wie möchtest du Aufträge, die sich gerade im Pickvorgang befinden, kennzeichnen? Sobald die Einzelkommissionierung mit plentyWarehouse gestartet wird, werden Aufträge automatisch in diesen Status gesetzt. So können sie nicht aus Versehen mehrmals für den Pickvorgang zur Verfügung gestellt werden. +
*_Tipp:_* Die xref:auftraege:auftraege-verwalten.adoc#1200[Status] in dieser Dropdown-Liste verwaltest du im Backend deines System unter *Einrichtung » Aufträge » Auftragsstatus*.

| [#intable-success-status]*Erfolgsstatus*
|Wähle den Status aus, in den Aufträge gesetzt werden, nachdem sie erfolgreich die Einzelkommissionierung durchlaufen haben, also alle benötigten Artikel gepickt wurden.

| *Fehlerstatus*
|Wie soll die App im Fehlerfall vorgehen? Kommt es bei der Einzelkommissionierung zu einem Fehler, weil beispielsweise ein Artikel nicht gepickt werden kann, wird der Auftrag in den hier gewählten Status gesetzt. Außerdem wird am Auftrag selbst eine Notiz angelegt, die genauere Informationen zum Artikel und zum Lagerort enthält. Später kannst du dann im Menü *Aufträge » Aufträge bearbeiten* nach Aufträgen mit diesem Status suchen und diese gesondert abarbeiten. +
*_Tipp:_* Die xref:auftraege:auftraege-verwalten.adoc#1200[Status] in dieser Dropdown-Liste verwaltest du im Backend deines System unter *Einrichtung » Aufträge » Auftragsstatus*.

2+^| Bereich *Artikelerfassung*

| [#intable-itemscan]*Artikel-Scan verpflichtend*
|Verwende diese Option, um festzulegen, welche Regeln für das Erfassen von Artikeln für die Einzelkommissionierung gelten sollen. +
*Keine Einschränkungen* = Artikel können entweder durch Scannen des Barcodes oder per manueller Auswahl hinzugefügt werden. +
*Artikelsuche einschränken* = Artikel ohne Barcode können über die Artikelsuche erfasst werden. Artikel mit Barcode _müssen_ durch Scannen des Barcodes auf dem Artikeletikett erfasst werden. +
*Verpflichtender Artikel-Scan* = Alle Artikel _müssen_ durch Scannen des Barcodes auf dem Artikeletikett erfasst werden. Eine manuelle Auswahl von Artikeln über die Suche ist nicht möglich.

| *Einzelerfassung bis Menge*
|Wenn du Artikel mit einem Scanner erfasst, kannst du mit dieser Einstellung bestimmen, ab wie vielen gescannten Exemplaren einer Variante automatisch die vorhandene Gesamtmenge in das Mengenfeld eingetragen wird. +
*_Beispiel:_* Wenn du die Zahl *5* ins Mengenfeld eingibst, wird nach dem fünften Scannen der Variante automatisch die Gesamtmenge eingetragen.

|===

[#300]
== Einzelkomissionierung durchführen

Nachdem du die vorbereitenden Einstellungen vorgenommen und die notwendigen Rechte vergeben hast, kannst du mit der Einzelkommissionierung beginnen.

[#310]
=== Auftrag suchen

Suche zunächst den Auftrag, dessen Artikel du mithilfe der Einzelkommissionierung picken möchtest. Gehe dazu wie unten beschrieben vor.

[.instruction]
Pickliste öffnen:

. xref:warenwirtschaft:installation-und-ersteinrichtung.adoc#300[Logge dich in plentyWarehouse ein].
. Tippe auf das Menüsymbol (icon:bars[role="darkGrey"]) oben links. +
icon:map-signs[] *_Oder:_* Finde die Kachel *Einzelkommissionierung* im Bereich *Funktionen* auf dem Dashboard.
. Tippe auf *Einzelkommissionierung* (material:shopping_cart_checkout[role="darkGrey"]). +
→ Das Suchmenü für Aufträge wird geöffnet.
. Finde den gewünschten Auftrag. <<table-single-order-picking-search>> enthält weitere Informationen zu den verfügbaren Suchfiltern.
. Tippe auf *Suchen* (icon:search[role="darkGrey"]). +
→ Die gefilterten Suchergebnisse werden angezeigt.
. Tippe auf einen Eintrag, um den Auftrag für die Einzelkommissionierung zu öffnen.

[[table-single-order-picking-search]]
.Verfügbare Suchfilter für Aufträge
[cols="1,3"]
|===

|Filter |Erläuterung

| *Auftags-ID*
| Filtert alle vorhandenen Aufträge nach ihrer Auftrags-ID.

| *Kontakt-ID*
| Filtert alle vorhandenen Aufträge nach der ID des Kontakts, von dem der Auftrag stammt.

| *Kontaktdaten*
| Filtert alle vorhandenen Aufträge nach beliebigen Kontaktdaten, beispielsweise Adressen oder Namen.

| *Rechnungsnummer*
| Filtert alle vorhandenen Aufträge nach der Rechnungsnummer.

| *Externe Auftrags-ID / Belegnummer*
| Filtert alle vorhandenen Aufträge nach der externen Auftrags-ID oder einer beliebigen Belegnummer.

|===

[#320]
=== Artikel picken

Sobald du einen Auftrag ausgewählt hast, wird dir im Tab *Offen* direkt die Liste der Artikel angezeigt, die gepickt werden müssen. So werden alle Artikel nacheinander von den Lagerorten entnommen. Bereits gepickte Artikel kannst du einsehen, indem du auf das Tab *Gepickt* tippst.

Für jeden Artikel wird neben weiteren Informationen wie dem Artikelbild der Lagerort angegeben, auf dem er sich befindet, sowie die Menge des Artikels, die gepickt werden muss.

[TIP]
.Sichtbarkeit von Artikelbildern in plentyWarehouse
====
Werden Artikelbilder, die du in deinem System gespeichert hast, nicht in der Artikelliste angezeigt? Stelle in diesem Fall sicher, dass du im plentysystems Backend die betreffenden xref:artikel:import-export-anlage-verzeichnis.adoc#94[Bilder mit den passenden Varianten verknüpft] hast.
====

Je nachdem, welche Einstellung du für die Option xref:warenwirtschaft:single-order-picking.adoc#intable-itemscan[Artikelscan verpflichtend] gewählt hast, kannst du die Artikel nun der Reihe nach Scannen oder die Menge über das Mengenfeld erfassen.

[IMPORTANT]
.Internetverbindung erforderlich
====
Grundsätzlich können Artikel auch ohne Verbindung zum Internet gepickt werden, sodass kurze Verbindungsabbrüche kein Problem sind. Es gibt jedoch eine Ausnahme: Stelle sicher, dass dein Gerät über eine Verbindung zum Internet verfügt, bevor du die Pickliste abschließt. Ohne Internetverbindung kann die Pickliste nicht ordnungsgemäß abgeschlossen werden und es kommt zu Folgefehlern.
====

[#330]
=== Einzelkommissionierung abschließen

Um die Einzelkommissionierung und damit auch die Pickliste für einen Auftrag abzuschließen, hast du zwei verschiedene Möglichkeiten:

* Erfasse die Artikel auf der Liste, bis die Meldung `Alle Artikel gepickt` angezeigt wird. Tippe dann auf das rote Häkchen rechts unten.

* Aktiviere im Menü *Einstellungen » Einzelkommissionierung* die Einstellung <<#intable-close-pick-list, *Pickliste automatisch schließen*>>. Wenn du dann die Einzelkommissionierung durchführst, werden Picklisten automatisch geschlossen,sobald du alle Artikel erfasst hast.
