= Varianten: Bestandsführung ermöglichen
:keywords: Bestandsführung, Bestandsbeschränkung, Beschränkung, Auf Netto-WB, Keinen WB für diese Variante führen, Lieferzeit, Bearbeitungszeit, Abfertigungszeit, Verfügbarkeit, Verfügbarkeit mit Bestand, Verfügbarkeit ohne Bestand, Lagerorttyp, Meldebestand, Lagerreichweite, Lagerortvorschlag
:description: Soll plentymarkets die Lagerbestände deiner Produkte überwachen? Diese Seite erläutert die Produkt-Einstellungen, die für die Bestandsverwaltung relevant sind.
:author: team-stock

////
zuletzt bearbeitet 10.05.2022
////

plentymarkets enthält einige Produkt-Einstellungen, die für die Bestandsverwaltung relevant sind.
Diese Seite erläutert die Einstellungen und hilft dir, deine Produkte so zu konfigurieren, dass du die Lagerbestände jederzeit verfolgen kannst.

[#100]
== Welche Varianten sollen erfasst werden?

Entscheide zuerst, für welche Produkte plentymarkets die Lagerbestände überwachen soll.

. Öffne das Menü *Artikel » Artikel bearbeiten » [Variante öffnen] » Tab: Einstellungen » Bereich: Verfügbarkeit*.
. Wähle die passende Option aus der Dropdown-Liste *Beschränkung*.
. *Speichere* (terra:save[role="green"]) die Einstellungen.

[cols="1s,4a"]
|===
|Einstellung |Erläuterung

| Keine
|Diese Einstellung ist nützlich für Situationen, in denen du zwar den Bestand zählen könntest, es aber keine Rolle spielt, ob der Bestand negativ wird.
Das Produkt steht zur Verfügung, nur ohne einen bestimmten Bestandswert.

*_Hinweis_*: Manche Marktplätze berücksichtigen ausschließlich den Bestandswert, der der Variante zugeordnet ist.
Wenn du also diese Einstellung wählst, kann es sein, dass der Marktplatz nie ein aktives Angebot für das Produkt hat, da es nie als ein positiver Bestandswert verstanden wird.
Prüfe, wie deine Ziel-Marktplätze die Einstellungen zur Bestandsbegrenzung interpretieren, bevor du mit dem Verkauf beginnst.

| Auf Netto-WB
|Dies ist die am häufigsten verwendete Option.
Sie verhindert, dass Artikel versehentlich überverkauft werden.
Der Warenbestand wird auf den Netto-Bestand beschränkt.
Dieser Netto-Bestand wird an Marktplätze übermittelt.

*_Was bedeutet Netto-Bestand?_* +
Diese Zahl gibt an, wie viele Exemplare derzeit zum Verkauf zur Verfügung stehen.
Der Netto-Warenbestand ist eine Teilmenge des physischen Bestands.
Wenn vom physischen Warenbestand alle Reservierungen abgezogen werden, ergibt sich der Netto-Bestand.
xref:warenwirtschaft:warenbestaende-verwalten.adoc#100[Weitere Informationen].

| Keinen WB für diese Variante führen
|Diese Einstellung ist nützlich für Situationen, in denen es sehr mühsam wäre, die Bestandseinheiten zu zählen.
Stell dir zum Beispiel vor, du verkaufst Baumaterial und hast Millionen Exemplare einer Schraube.

*_Hinweis_*: Manche Marktplätze berücksichtigen ausschließlich den Bestandswert, der der Variante zugeordnet ist.
Wenn du also diese Einstellung wählst, kann es sein, dass der Marktplatz nie ein aktives Angebot für das Produkt hat, da es nie als ein positiver Bestandswert verstanden wird.
Prüfe, wie deine Ziel-Marktplätze die Einstellungen zur Bestandsbegrenzung interpretieren, bevor du mit dem Verkauf beginnst.

*_Hinweis_*: Wenn diese Einstellung gewählt wird, werden im Tab *Bestand* der Variante die Tabs *Korrektur*, *Warenbestand*, *Zulauf* und *Warenbewegung* ausgeblendet.

|===

[#200]
== Wie ist die Verfügbarkeit der Varianten?

Gib als nächstes die durchschnittliche Lieferzeit deiner Varianten an.
Diese Angabe kann entweder statisch oder dynamisch sein.

* *Statisch*: Du wählst eine Abfertigungszeit, die immer für die Variante gilt, z.B. Versand innerhalb von 3 Tagen.
* *Dynamisch*: Du wählst eine Abfertigungszeit für den Fall, dass die Variante auf Lager ist, z.B. Versand innerhalb von 3 Tagen.
Und du wählst eine zweite Abfertigungszeit für den Fall, dass die Variante nicht auf Lager ist, z.B. Versand innerhalb von 2 Wochen.

[.collapseBox]
.*Statische Einstellung*
--

TIP: In plentymarkets stehen zehn Verfügbarkeitsstufen zur Auswahl.
Stelle sicher, dass du die Verfügbarkeitsstufen bereits im Menü *Einrichtung » Artikel » Verfügbarkeit* definiert hast, bevor du fortfährst.
xref:artikel:verfuegbarkeit.adoc#100[Weitere Informationen].

. Öffne das Menü *Artikel » Artikel bearbeiten » [Variante öffnen] » Tab: Einstellungen » Bereich: Verfügbarkeit*.
. Wähle die passende Verfügbarkeitsstufe (Symbole 1-10).
. *Speichere* (terra:save[role="green"]) die Einstellungen.

--

[.collapseBox]
.*Dynamische Einstellung*
--

TIP: In plentymarkets stehen zehn Verfügbarkeitsstufen zur Auswahl.
Stelle sicher, dass du die Verfügbarkeitsstufen bereits im Menü *Einrichtung » Artikel » Verfügbarkeit* definiert hast, bevor du fortfährst.
xref:artikel:verfuegbarkeit.adoc#100[Weitere Informationen].

. Öffne das Menü *Einrichtung » Waren » Lager » [Lager öffnen] » Einstellungen*.
. Wähle die passende Verfügbarkeitsstufe (Symbole 1-10) für die Einstellungen *Verfügbarkeit mit Bestand* und *Verfügbarkeit ohne Bestand*.
. *Speichere* (terra:save[role="darkGrey"]) die Einstellungen.

Falls die Variante mehreren Lagern mit unterschiedlichen Verfügbarkeitsstufen zugeordnet ist, dann nimmt plentymarkets immer die beste Option.
Beispiel: Der Artikel ist in Lager A und B verfügbar.

* Lager A hat eine Verfügbarkeit von 2 Tagen.
* Lager B hat eine Verfügbarkeit von 5 Tagen.
* In diesem Fall wird das Lager A verwendet, da es die bessere Verfügbarkeit bietet.

--

[#300]
== Wo befinden sich die Varianten?

Wo wird die Variante gelagert?
Ordne deine Varianten dem passenden Lagerort zu.
Dies ist nützlich, damit du später:

* xref:warenwirtschaft:wareneingaenge-verwalten.adoc#450[den Wareneingang buchen kannst].
* xref:warenwirtschaft:nachbestellungen-vornehmen.adoc#[Waren nachbestellen kannst, wenn sie zur Neige gehen].


[TIP]
.Hast du bereits Lager-Informationen gespeichert?
====
Bevor du Varianten mit Lagerorten verknüpfen kannst, musst du plentymarkets ein wenig über dein Lager mitteilen.
Wie viele Zonen, Regale, Regalböden und Lagerorte gibt es in deinem Lager?
xref:warenwirtschaft:lager-einrichten.adoc#[Richte dein Lager ein], bevor du fortfährst.
====

////

. Öffne das Menü *Artikel » Artikel-UI » [Variante öffnen] » Element: Lager*.
. Klicke auf *Lager hinzufügen* (icon:plus[role="darkGrey"]). +
→ Es öffnet sich ein Pop-up-Fenster.
. Wähle das Lager aus, das du verknüpfen möchtest.
. Klicke auf *Übernehmen*. +
→ Die Daten werden als Tabelle dargestellt.
. Nimm weitere Einstellungen bei Bedarf vor.
. *Speichere* (terra:save[role="darkGrey"]) die Einstellungen.

////

. Öffne das Menü *Artikel » Artikel bearbeiten » [Variante öffnen] » Tab: Lager*.
. Wähle das zu verknüpfende Lager aus der Dropdown-Liste aus.
. Klicke auf *Hinzufügen* (icon:plus[role="green"]). +
→ Das Lager wird der Variante zugeordnet und weitere Einstellungen können optional vorgenommen werden.
. *Speichere* (terra:save[role="green"]) die Einstellungen.

//zukunft - die beschreibungen in der tabelle verständlicher machen (siehe Schulung mit Oskar) und auch mit den Beschreibungen unter warenwirtschaft:wareneingaenge-verwalten.adoc#200 angleichen - dafür includes verwenden

[cols="1s,4a"]
|===
|Einstellung |Erläuterung

| Lager
|Hier siehst du das soeben ausgewählte Lager.
Dies ist rein informativ und kann nicht geändert werden.

| Lagerorttyp
|Wähle anhand der Artikelgröße einen Lagerorttyp.

//this doesn't make sense - in the ui you can choose 1-20 : it doesn't match the warehouse dimensions saved
| Zone
|Wähle eine Zone, wenn das Lager in Zonen eingeteilt wurde.

| Meldebestand
|Gib die Anzahl ein, bei der eine Nachbestellung der Variante erfolgen soll.
Erst wenn die Variante auf diesen Meldebestand sinkt, wird ein Mengenvorschlag für die Variante angezeigt, da erst bei Erreichen des Meldebestands eine Nachbestellung erfolgen soll.

*_Hinweis_*: Wenn du die xref:warenwirtschaft:lager-einrichten.adoc#Meldebestand_Variante_Lager[Differenz zum Meldebestand] dynamisch berechnen lässt, darf hier nur `0` gespeichert werden.

| Lagerreichweite
|Gib die Anzahl der Tage ein, den der Warenbestand bis zur nächsten Nachbestellung reichen soll.
Die Lagerreichweite fließt in die Berechnung des Nachbestellungsvorschlags ein.

*_Hinweis_*:
Wird hier kein Wert eingetragen, wird die Lagerreichweite bei der Berechnung eines Nachbestellungstermins nicht berücksichtigt.

*_Praxisbeispiel_*:
Ein Standardwert aus der Praxis für die Lagerreichweite ist z.B. 14 Tage.
Wenn der Artikel den Meldebestand erreicht hat, werden die 14 Tage zur Berechnung der Nachbestellmenge berücksichtigt, d.h. es wird die Menge zur Nachbestellung vorgeschlagen, die für die folgenden 14 Tage ausreicht.

| Maximalbestand
|Derzeit ohne Funktion.

//klären, ob diese Option eine Funktion hat - es klang als ob wir uns nicht sicher sind, ob Amazon den Wert hier berücksichtigt
| Bestandspuffer
|Gib einen Bestandspuffer ein.
Dies bewirkt, dass der Bestand für bestimmte Marktplätze um den eingetragenen Wert reduziert wird.

*_Beispiel_*: Der Artikel hat einen Bestand von 50.
Du möchtest einen Bestandspuffer von 10 Artikeln, damit der Artikel nicht vollständig über den Marktplatz abverkauft wird.
Dazu gibst du 10 als Bestandspuffer ein.
Zum Marktplatz wird dann ein Bestandswert von 40 übertragen.

*_Hinweis_*:

* Hier eingetragene Werte gelten nur für die Marktplätze xref:maerkte:amazon-einrichten.adoc#[Amazon] und xref:maerkte:shopgate.adoc#[Shopgate].
Die Werte sind gegenüber den hinterlegten Bestandspufferwerten dieser Marktplätze dominant.
* Bei allen anderen Marktplätzen ist diese Einstellung irrelevant.
Hier haben die Bestandspuffer-Einstellungen des jeweiligen Marktplatzes Vorrang.

| Charge
|Wähle, ob für die Variante und das Lager die Charge der Produkte erfasst werden soll.

*_Hinweis_*: Sobald Lagerbestand auf dem Lager vorhanden ist, kann diese Option nicht mehr deaktiviert werden.
Ist der Lagerbestand auf dem Lager gleich 0, ist das Aktivieren und Deaktivieren der Option möglich.

| MHD
|Wähle, ob für die Variante und das Lager das Mindesthaltbarkeitsdatum der Produkte erfasst werden soll.

*_Hinweis_*: Sobald Lagerbestand auf dem Lager vorhanden ist, kann diese Option nicht mehr deaktiviert werden.
Ist der Lagerbestand auf dem Lager gleich 0, ist das Aktivieren und Deaktivieren der Option möglich.

| Lagerortvorschlag
|Wähle einen Lagerort, der bei Nachbestellungen automatisch vorgeschlagen werden soll.

*_Hinweis_*: Der Standard-Lagerort dient als Platzhalter und bedeutet, dass noch kein Lagerort zugewiesen wurde.

|===
