= Varianten: Bestandsführung ermöglichen
:description: #Text#
:id: 5YBTHK1
:author: team-stock

////
zuletzt bearbeitet 06.05.2022
////

#Intro#

== Welche Artikel sollen erfasst werden?

[#200]
== Wo befinden sich die Artikel?

Wo wird diese Variante gelagert?
Ordne deine Varianten dem passenden Lagerort zu.
Indem du diese Daten in plentymarkets speicherst, kannst du später xref:warenwirtschaft:wareneingaenge-verwalten.adoc#450[den Wareneingang buchen].

[TIP]
.Hast du bereits Lager-Informationen gespeichert?
====
Bevor du Varianten mit Lagerorten verknüpfen kannst, musst du plentymarkets ein wenig über dein Lager mitteilen.
Wie viele Zonen, Regale, Regalböden und Lagerorte gibt es in deinem Lager?
xref:warenwirtschaft:lager-einrichten.adoc#[Richte dein Lager ein], bevor du fortfährst.
====

[.instruction]
Lager hinzufügen:

. Öffne das Menü *Artikel » Artikel-UI » [Variante öffnen] » Element: Lager*.
. Klicke auf *Lager hinzufügen* (icon:plus[role="darkGrey"]). +
→ Es öffnet sich ein Pop-up-Fenster.
. Wähle das Lager aus, das du verknüpfen möchtest.
. Klicke auf *Übernehmen*. +
→ Die Daten werden als Tabelle dargestellt.
. *Speichere* (icon:save[set=plenty, role="darkGrey"]) die Einstellungen.

//zukunft - die beschreibungen in der tabelle verständlicher machen (siehe Schulung mit Oskar) und auch mit den Beschreibungen unter warenwirtschaft:wareneingaenge-verwalten.adoc#200 angleichen - dafür includes verwenden

[cols="1,4a"]
|====
|Einstellung |Erläuterung

| *Lager*
|Hier siehst du das soeben ausgewählte Lager.
Dies ist rein informativ und kann nicht geändert werden.

| *Lagerorttyp*
|Wähle anhand der Artikelgröße einen Lagerorttyp.

//this doesn't make sense - in the ui you can choose 1-20 : it doesn't match the warehouse dimensions saved
| *Zone*
|Wähle eine Zone, wenn das Lager in Zonen eingeteilt wurde.

| *Meldebestand*
|Gib die Anzahl ein, bei der eine Nachbestellung der Variante erfolgen soll.
Erst wenn die Variante auf diesen Meldebestand sinkt, wird ein Mengenvorschlag für die Variante angezeigt, da erst bei Erreichen des Meldebestands eine Nachbestellung erfolgen soll.

*_Hinweis_*: Wenn du die xref:warenwirtschaft:lager-einrichten.adoc#Meldebestand_Variante_Lager[Differenz zum Meldebestand] dynamisch berechnen lässt, darf hier nur `0` gespeichert werden.

| *Maximalbestand*
|Gib den maximalen Bestand für das Lager ein.
Der Maximalbestand wird für den Bestellmengenvorschlag berücksichtigt, sodass der Vorschlag den Maximalbestand nicht überschreitet.

| *Lagerreichweite*
|Gib die Anzahl der Tage ein, den der Warenbestand bis zur nächsten Nachbestellung reichen soll.
Die Lagerreichweite fließt in die Berechnung des Nachbestellungsvorschlags ein.

*_Hinweis_*:
Wird hier kein Wert eingetragen, wird die Lagerreichweite bei der Berechnung eines Nachbestellungstermins nicht berücksichtigt.

*_Praxisbeispiel_*:
Ein Standardwert aus der Praxis für die Lagerreichweite ist z.B. 14 Tage.
Wenn der Artikel den Meldebestand erreicht hat, werden die 14 Tage zur Berechnung der Nachbestellmenge berücksichtigt, d.h. es wird die Menge zur Nachbestellung vorgeschlagen, die für die folgenden 14 Tage ausreicht.

| *Bestandspuffer*
|Gib einen Bestandspuffer ein.
Dies bewirkt, dass der Bestand für bestimmte Marktplätze um den eingetragenen Wert reduziert wird.

*_Hinweis_*:
Hier eingetragene Werte gelten für die Marktplätze xref:maerkte:amazon-einrichten.adoc#[Amazon] und xref:maerkte:shopgate.adoc#[Shopgate].
Die Werte sind gegenüber den hinterlegten Bestandspufferwerten dieser Marktplätze dominant.
Bei anderen Marktplätzen, die nicht hier aufgeführt sind, haben die Bestandspuffer-Einstellungen des jeweiligen Marktplatzes Vorrang vor dieser Einstellung.

*_Beispiel_*: Der Artikel hat einen Bestand von 50.
Du möchtest einen Bestandspuffer von 10 Artikeln, damit der Artikel nicht vollständig über den Marktplatz abverkauft wird.
Dazu gibst du 10 als Bestandspuffer ein.
Zum Marktplatz wird dann ein Bestandswert von 40 übertragen.

| *Charge*
|Wähle, ob für die Variante und das Lager die Charge der Produkte erfasst werden soll.

*_Hinweis_*: Sobald Lagerbestand auf dem Lager vorhanden ist, kann diese Option nicht mehr deaktiviert werden.
Ist der Lagerbestand auf dem Lager gleich 0, ist das Aktivieren und Deaktivieren der Option möglich.

| *MHD*
|Wähle, ob für die Variante und das Lager das Mindesthaltbarkeitsdatum der Produkte erfasst werden soll.

*_Hinweis_*: Sobald Lagerbestand auf dem Lager vorhanden ist, kann diese Option nicht mehr deaktiviert werden.
Ist der Lagerbestand auf dem Lager gleich 0, ist das Aktivieren und Deaktivieren der Option möglich.

| *Lagerortvorschlag*
|Wähle einen Lagerort, der bei Nachbestellungen automatisch vorgeschlagen werden soll.

*_Hinweis_*: Der Standard-Lagerort bedeutet, dass kein Lagerort zugewiesen wurde.

|====

---

Eine Variante muss mit einem Lager samt Lagerort verknüpft werden, damit ein Wareneingang gebucht werden kann. Der Standard-Lagerort dient als Platzhalter-Lagerort, was bedeutet, dass noch kein Lagerort zugeordnet wurde. Wähle deshalb einen deiner Lagerorte als Lagerortvorschlag.

[IMPORTANT]
.Bei Lagerortvorschlag kein Wareneingang auf Standard-Lagerort möglich
====
Wenn eine Variante mit einem Lagerortvorschlag verknüpft wurde, ist der Wareneingang auf den Standard-Lagerort nicht mehr möglich.
====

[IMPORTANT]
.Vererben der Einstellung an Varianten
====
Wenn du ein Lager für eine Hauptvariante aktivierst, wird diese Einstellung auch an alle Varianten des Artikels xref:artikel:vererbung.adoc#[vererbt].
====

[.instruction]
Variante mit Lagerort verknüpfen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. xref:artikel:suche.adoc#100[Suche] und öffne den Artikel.
. Wechsele in das Tab *Lager*.
. Wähle ein Lager aus der Dropdown-Liste.
. Klicke auf *Hinzufügen* (icon:plus-square[role="green"]). +
→ Das Lager wird der Variante zugeordnet und weitere Einstellungen können optional vorgenommen werden.

[[tabelle-lagereinstellungen-variante]]
.Lagereinstellungen einer Variante
[cols="1,2"]
|====
|Einstellung |Erläuterung

|[#intable-lagerorttyp]*Lagerorttyp*
|Wähle anhand der Artikelgröße einen Lagerorttyp.

| *Zone*
|Wähle eine Zone, wenn das Lager in Zonen eingeteilt wurde.

| *Meldebestand*
|Gib die Anzahl ein, bei der eine Nachbestellung der Variante erfolgen soll. Erst wenn die Variante auf diesen Meldebestand sinkt, wird ein Mengenvorschlag für die Variante angezeigt, da erst bei Erreichen des Meldebestands eine Nachbestellung erfolgen soll. +
*_Hinweis:_* Wenn du die xref:warenwirtschaft:lager-einrichten.adoc#Meldebestand_Variante_Lager[Differenz zum Meldebestand] dynamisch berechnen lässt, darf hier nur `0` gespeichert werden.

| *Lagerreichweite*
|Gib die Anzahl der Tage ein, den der Warenbestand bis zur nächsten Nachbestellung reichen soll. Die Lagerreichweite fließt in die Berechnung des Nachbestellungsvorschlags ein. Ein Standardwert aus der Praxis für die Lagerreichweite ist z.B. 14 Tage. Wenn der Artikel den Meldebestand erreicht hat, werden die 14 Tage zur Berechnung der Nachbestellmenge berücksichtigt, d.h. es wird die Menge zur Nachbestellung vorgeschlagen, die für die folgenden 14 Tage ausreicht.
Wird hier kein Wert eingetragen, wird die Lagerreichweite bei der Berechnung eines Nachbestellungstermins nicht berücksichtigt.

| *Maximalbestand*
|Gib den maximalen Bestand für das Lager ein. Der Maximalbestand wird für den Bestellmengenvorschlag berücksichtigt, sodass der Vorschlag den Maximalbestand nicht überschreitet.

| *Bestandspuffer*
|Gib einen Bestandspupper ein. Ein Bestandspuffer bewirkt, dass der Bestand für bestimmte Marktplätze um den eingetragenen Wert reduziert wird. +
__Beispiel__: Der Artikel hat einen Bestand von 50. Du möchtest einen Bestandspuffer von 10 Artikeln, damit der Artikel nicht vollständig über den Marktplatz abverkauft wird. Dazu gibst du *10* als Bestandspuffer ein. Zum Marktplatz wird dann ein Bestandswert von *40* übertragen. +
Hier eingetragene Werte gelten für die Marktplätze xref:maerkte:amazon-einrichten.adoc#[Amazon] und xref:maerkte:shopgate.adoc#[Shopgate]. Die Werte sind gegenüber den hinterlegten Bestandspufferwerten dieser Marktplätze dominant. +
Bei anderen Marktplätzen, die nicht hier aufgeführt sind, haben die Bestandspuffer-Einstellungen des jeweiligen Marktplatzes Vorrang vor dieser Einstellung.

| *MHD*
|Wähle, ob für die Variante und das Lager das Mindesthaltbarkeitsdatum der Produkte erfasst werden soll. +
*_Hinweis:_* Sobald Lagerbestand auf dem Lager vorhanden ist, kann die Option *MHD* nicht mehr deaktiviert werden. Ist der Lagerbestand auf dem Lager gleich 0, ist das Aktivieren und Deaktivieren der Option *MHD* möglich.

| *Charge*
|Wähle, ob für die Variante und das Lager die Charge der Produkte erfasst werden soll. +
*_Hinweis:_* Sobald Lagerbestand auf dem Lager vorhanden ist, kann die Option *Charge* nicht mehr deaktiviert werden. Ist der Lagerbestand auf diesem Lager gleich 0, ist das Aktivieren und Deaktivieren der Option *Charge* möglich.

| *Lagerortvorschlag*
|Wähle einen Lagerort, der bei Nachbestellungen automatisch vorgeschlagen werden soll. Die Einstellung *Standard-Lagerort* bedeutet, dass kein Lagerort zugewiesen wurde.
|====
