= Warenwirtschaft
:keywords: Waren, Wareneingang, Warenausgang, Warenwirtschaft, Bestand, Warenbestand, Mobile Warenwirtschaft
:id: 200DET3
:author: team-stock

Die in plentymarkets integrierte Warenwirtschaft unterstützt dich dabei, den Überblick über deine aktuellen Bestände sowie den Zulauf und Ausgang von Waren zu behalten. Die Warenwirtschaft ermöglicht dir die Verwaltung deiner Lager, das Reservieren von Beständen sowie automatisierte Bestandsaktualisierungen. +
In diesem Themenbereich findest du Informationen zum Erstellen und Bearbeiten von Lagern, zum Einbuchen und Zuordnen von Beständen sowie zum Nachbestellen von Waren. +
Nur wenn du Bestände führst, kann dein System Bestand reservieren und automatisch reduzieren, sobald der Warenausgang für einen Auftrag gebucht wird. Reservierungen verhindern, dass bereits verkaufte Ware doppelt verkauft wird.

Grob gilt folgende Reihenfolge für das Einrichten der Warenwirtschaft:

* Lager erstellen
* Lieferant:innen erstellen
* Wareneingang buchen
* Nachbestellung erstellen

Für eine funktionierende Warenwirtschaft spielen viele Punkte eine Rolle. Dazu gehört das Pflegen von Meldebeständen und Mindestabnahmen für Varianten, das Kontrollieren von Beständen oder Zuläufen aus Bestellungen sowie Retouren, aber auch Inventuren. Ein weiterer Punkt ist die Reservierung von Bestand für Listings, die du in plentymarkets verwenden kannst. Wie du für Listings Bestand reservierst, wird auf den Seiten der Listingplattformen beschrieben. Rund um das Thema Warenwirtschaft schließen sich noch viele Themen an, z.B. das Erstellen von Dokumenten für die Kommissionierung. Außerdem findest du auf dieser Seite eine Übersicht über die Funktionen der mobilen Warenwirtschaft in der <<app#, plentymarkets App>>.

[.row]
====
[.col-md-6]
.Lager planen und einrichten
=====
* xref:warenwirtschaft:lager-einrichten.adoc#100[Lager planen]
* xref:warenwirtschaft:lager-einrichten.adoc#200[Lager einrichten]
* xref:warenwirtschaft:lager-einrichten.adoc#700[Packen vorbereiten]
* xref:warenwirtschaft:lager-einrichten.adoc#800[Lagerorte scannen ermöglichen]
=====

[.col-md-6]
.Warenmengen erfassen und buchen
=====
* **xref:crm:kontakte-verwalten.adoc#20[Lieferant:innen anlegen]**
* **xref:warenwirtschaft:wareneingaenge-verwalten.adoc#100[Lieferant:innen einer Variante zuordnen]**
* **xref:warenwirtschaft:wareneingaenge-verwalten.adoc#200[Lagerort einer Variante angeben]**
* **xref:warenwirtschaft:wareneingaenge-verwalten.adoc#500[Wareneingang und Mengen erfassen]**
* **xref:warenwirtschaft:wareneingaenge-verwalten.adoc#1100[Bestand auf Varianten buchen]**
* **xref:warenwirtschaft:wareneingaenge-verwalten.adoc#1300[Warenbewegung durch Wareneingang einsehen]**
* **xref:warenwirtschaft:umbuchungen-vornehmen.adoc#[Ware umbuchen]**
=====

[.col-md-6]
.Bestände überblicken und nachbestellen
=====
* **<<warenwirtschaft/warenbestaende-verwalten#100, Welche Bestände gibt es?>>**
* **<<warenwirtschaft/warenbestaende-verwalten#200, Wann wird Bestand reserviert?>>**
* **xref:warenwirtschaft:warenbestaende-verwalten.adoc#500[Bestand einzelner Varianten umbuchen]**
* **xref:warenwirtschaft:nachbestellungen-vornehmen.adoc#[Nachbestellungen vornehmen]**
* **xref:warenwirtschaft:rueckstandsliste-verwalten.adoc#[Warenzulauf prüfen]**
* **xref:warenwirtschaft:inventur-vornehmen.adoc#[Inventur vornehmen]**
=====

[.col-md-6]
.Dokumente zur Kommissionierung
=====
* **xref:auftraege:pickliste.adoc#[Pickliste]**
* **xref:auftraege:packliste.adoc#[Packliste]**
* **xref:auftraege:lager-pickliste.adoc#[Lager-Pickliste]**
=====

[.col-md-6]
.Waren ausbuchen
=====
* **xref:warenwirtschaft:waren-ausbuchen.adoc#20[Warenausgang automatisieren]**
* **<<warenwirtschaft/waren-ausbuchen#50, Stornierungen, Retouren und Gewährleistungen bearbeiten>>**
* **xref:warenwirtschaft:waren-ausbuchen.adoc#90[Warenausgang manuell vornehmen]**
=====

[.col-md-6]
.Mindesthaltbarkeitsdatum (MHD) und Chargen
=====
* **xref:warenwirtschaft:mhd-charge-verwalten.adoc#[Übersicht]**
* **<<warenwirtschaft/wareneingaenge-verwalten#810, Wareneingang mit MHD und/oder Charge>>**
=====

[.col-md-6]
.Mobile Warenwirtschaft in der plentymarkets App
=====
* **xref:app:rollende-kommissionierung.adoc#[Rollende Kommissionierung]**
* **xref:app:einbuchen-umbuchen.adoc#[Ware einbuchen und umbuchen]**
* **xref:app:verräumen.adoc#[Ware verräumen]**
* **xref:app:inventur.adoc#[Inventur durchführen]**
=====


====

'''
