= Ware einbuchen
:keywords: Ware buchen, Ware freigeben, Bestand buchen, Wareneingang, Wareneingänge, Ware einbuchen, Bestand einbuchen, Ware erfassen, Wareneingang erfassen, Meldebestand, Lagerreichweite, Maximalbestand, Bestandspuffer, MHD, Charge, Lagerortvorschlag, Einkaufspreis, Einkaufspreis ermitteln, EK, Menge, UVP, Preis, Warenbezugskosten, leerer Lagerort, Lagerort leer, Lagerbestandseintrag
:description: Du hast gerade eben Waren von deinem Lieferanten erhalten. Was nun? Auf dieser Seite lernst du, wie du den Bestand in plentymarkets einbuchen kannst.
:author: team-stock

Es gibt verschiedene Wege, über die du Waren in dein System buchen kannst.
Voraussetzung für einen Wareneingang ist, dass der Variante ein Lager, ein Lagerort und ein Lieferant zugeordnet sind.

Auf dieser Seite wird der Wareneingang über das Menü *Waren » Neuer Wareneingang* beschrieben.
Nur wenn du Wareneingänge und Warenausgänge buchst und so Warenbestände in plentymarkets führst, kann dein System Varianten anhand der xref:artikel:artikel-verwalten.adoc#200[Beschränkung und Verfügbarkeit] automatisiert im Webshop ein- und ausblenden sowie Listings automatisiert starten und beenden.

[#250]
== Einkaufspreis ermitteln

Die Einstellungen zum Einkaufspreis in plentymarkets sind vielfältig.
In Varianten werden dir zwei verschiedene Einkaufspreise angezeigt. Ein Feld zeigt immer den gleitenden Einkaufspreis. Welcher Einkaufspreis im 2. Feld angezeigt wird, bestimmst du durch deine Einstellungen. Du hast die Möglichkeit, einen Einkaufspreis einzutragen oder bei Wareneingängen z.B. den Einkaufspreis des aktuellen Wareneingangs an Varianten und Lieferant:innen zu übertragen. Außerdem kannst du ebenfalls einen weiteren Durchschnittseinkaufspreis übertragen. Hierbei handelt es sich um eine Art Live-Durchschnittseinkaufspreis. Welche Einstellungsoptionen du hast, um den Einkaufspreis zu übertragen, wird im nächsten Kapitel, <<#300, Lagerort und Einkaufspreis übertragen>>, beschrieben. +
Die Berechnung der 2 unterschiedlichen Durchschnittseinkaufspreise wird im Folgenden erläutert.

[[tabelle-durchschnittseinkaufspreis-berechnen]]
.Formeln Durchschnittseinkaufspreis
[cols="1a,1a"]
|===
|Livedurchschnittsberechnung |Berechnung gleitender Durchschnittseinkaufspreis

|latexmath:[LDEK_{neu} = {LDEK_{alt} \cdot Menge_{alt} + EK_{neu} \cdot Menge_{neu}\over Menge_{alt} + Menge_{neu}}] +
 +
LDEK~neu~ = Neuer Live-Durchschnittseinkaufspeis +
LDEK~alt~ = Alter Live-Durchschnittseinkaufspreis +
Menge~alt~ = Bisherige Bestandsmenge +
EK~neu~ = Einkaufspreis im Wareneingang +
Menge~neu~ = Menge im Wareneingang
|latexmath:[GLD_{neu} = {GLD_{alt} \cdot Menge_{alt} + EK_{neu} \cdot Menge_{neu}\over Menge_{alt} + Menge_{neu}}] +
 +
GLD~neu~ = Neuer gleitender Durchschnittseinkaufspeis +
GLD~alt~ = Alter gleitender Durchschnittseinkaufspreis +
Menge~alt~ = Bisherige Bestandsmenge +
EK~neu~ = Einkaufspreis im Wareneingang +
Menge~neu~ = Menge im Wareneingang

a|Bei dieser Methode wird in folgenden Fällen eine Neuberechnung ausgelöst:

* Wareneingang
* Warenausgang

Der aktuelle Durchschnitt wird z.B. in Statistiken oder Exporten ausgegeben. Damit dieser Durchschnittspreis auch im Artikel angezeigt wird, muss zusätzlich eingestellt werden, dass der Durchschnittseinkaufspreis auf Varianten übertragen wird. +
Um diesen Preis in der Variante zu sehen, wähle im Menü *Einrichtung » Waren » Warenbestand » Wareneingang* für die Einstellung *Einkaufspreis* die Option  *Durchschnittseinkaufspreis auf Variante übertragen*. Die weiteren Optionen werden in <<tabelle-einkaufspreis-lagerort-übertragen>> erläutert.

a|Bei dieser Methode wird in folgenden Fällen eine Neuberechnung ausgelöst:

* Wareneingang

Allerdings muss dafür das Lager, in das du Bestand buchst, auch für den GLD berücksichtigt werden. Der GLD wird in der Variante automatisch in einem separaten Feld eingetragen. +
Welche Lager für den *gleitenden Durchschnittspreis* berücksichtigt werden sollen, stellst du im Menü *Einrichtung » Waren » Warenbestand » Wareneingang* ein.

|===

[#300]
== Lagerort und Einkaufspreis übertragen

Beim Hinzufügen von Artikeln kannst du sowohl den Einkaufspreis als auch die UVP und den Lagerort angeben. Die UVP wird bei Freigabe eines Wareneingangs automatisch in die Variantendaten übernommen. Wenn ein Wareneingang die gleiche Variante mehrmals, jedoch mit unterschiedlichen UVPs enthält, wird bei der Freigabe die höchste UVP übernommen. Ob und wie Einkaufspreise von Wareneingängen zu den Artikeldaten übertragen werden und ob und wie ein Lagerort aus einem Wareneingang zu einem Artikel übertragen wird, legst du vorab fest.

[.instruction]
Übertragung festlegen:

. Öffne das Menü *Einrichtung » Waren » Warenbestand » Wareneingang*.
. Wähle eine Einstellung. Beachte dazu die Erläuterungen in <<tabelle-einkaufspreis-lagerort-übertragen>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[[tabelle-einkaufspreis-lagerort-übertragen]]
.Preis- und Lagerortübertragung festlegen
[cols="1,2"]
|===
|Einstellung |Erläuterung

| *Einkaufspreis*
|Wähle, ob und wohin der EK aus dem Wareneingang übertragen werden soll. Die Übertragung erfolgt bei Freigabe eines Wareneingangs. +
*Einkaufspreis nicht übertragen* = Der Einkaufspreis wird nicht übertragen. Wähle diese Einstellung, wenn du den Einkaufspreis in der Variante manuell pflegen möchtest. +
*Einkaufspreis auf Variante übertragen* = Der Einkaufspreis wird automatisch im Tab *Einstellungen* einer Variante hinterlegt. Wenn du im selben Wareneingang dieselbe Variante mit unterschiedlichen Einkaufspreisen buchst, wird der letzte Einkaufspreis der Variante aus dem Wareneingang übertragen. +
*Einkaufspreis auf Variante und Lieferant übertragen* = Der Einkaufspreis wird automatisch im Tab *Einstellungen* einer Variante sowie im Tab *Bestand* in den Lieferant:innen-Daten hinterlegt. Wenn du im selben Wareneingang dieselbe Variante mit unterschiedlichen Einkaufspreisen buchst, wird der letzte Einkaufspreis der Variante aus dem Wareneingang übertragen. +
*Live-Durchschnittseinkaufspreis auf Variante übertragen* = Bei jedem Wareneingang und Warenausgang wird der durchschnittliche EK neu berechnet und angepasst. Zum Berechnen werden die tatsächlichen Einkaufspreise der im Lager verfügbaren Bestände einer Variante herangezogen. Der errechnete Mittelwert wird im Tab *Einstellungen* einer Variante hinterlegt. Die Formel zum Berechnen findest du in <<tabelle-durchschnittseinkaufspreis-berechnen>>. +
*Höchsten Einkaufspreis auf Variante übertragen* = Bei mehreren unterschiedlichen Einkaufspreisen wird der höchste Einkaufspreis aus dem aktuellen Wareneingang in die Variantendaten übertragen. +
*Niedrigsten Einkaufspreis auf Variante übertragen* = Bei mehreren unterschiedlichen Einkaufspreisen wird der niedrigste Einkaufspreis aus dem aktuellen Wareneingang in die Variantendaten übertragen.

| *Lagerort*
| Wähle, ob und wohin der Lagerort übertragen werden soll. Die Übertragung erfolgt bei Freigabe eines Wareneingangs. +
*Lagerort nicht übertragen* = Der Lagerort wird nicht übertragen. +
*Lagerort auf Variante übertragen* = Der Lagerort wird automatisch als Lagerort-Vorschlag in das Tab *Lager* einer Variante übernommen. Der Lagerort wird mit jedem Wareneingang neu übertragen. +
*Lagerort auf Variante übertragen, wenn noch kein Lagerort oder Standard-Lagerort hinterlegt wurde* = Die Übertragung erfolgt nur, wenn noch kein Lagerort hinterlegt wurde.
|===

//diese Erklärung passt besser hier oder weiter unten bei Ware einbuchen?

////
[IMPORTANT]
.Bei Lagerortvorschlag kein Wareneingang auf Standard-Lagerort möglich
====
Wenn eine Variante mit einem Lagerortvorschlag verknüpft wurde, ist der Wareneingang auf den Standard-Lagerort nicht mehr möglich.
====
////

[#400]
== UVP und Preis zuordnen

Damit du im Wareneingang eine UVP eingeben kannst, ordne zu, welcher Verkaufspreis als UVP genutzt werden soll. Außerdem kannst du wählen, welcher Verkaufspreis dir im Wareneingang angezeigt wird.

[.instruction]
UVP und Preis zuordnen:

. Öffne das Menü *Einrichtung » Waren » Neuer Wareneingang*.
. Wähle für *UVP* einen deiner Verkaufspreise aus der Dropdown-Liste.
. Wähle für *Preis* einen deiner Verkaufspreise aus der Dropdown-Liste.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

Die Zuordnung im Menü *Einrichtung » Waren » Neuer Wareneingang* allein genügt nicht, um einen Verkaufspreis in einer Variante anzuzeigen. Der Verkaufspreis muss außerdem mit einer Variante verknüpft werden. Verkaufspreise legst du im Menü *Einrichtung » Artikel » Verkaufspreise* an. Wie du Verkaufspreise anlegst und mit Varianten verknüpfst, ist auf der Handbuchseite xref:artikel:preise.adoc#200[Verkaufspreise und Preiskalkulation] beschrieben. Dort erfährst du zum Beispiel auch, wie du mit der Preiskalkulation Preise für Kund:innen-Klassen berechnest.

[#450]
== Ware über das Backend einbuchen

Du hast verschiedene Möglichkeiten, einen Wareneingang zu buchen, z.B. per App, per Datenimport oder über den Menüpunkt *Neuer Wareneingang*. In diesem Menü hast du die Möglichkeit, neben dem Bestand auch weitere Daten, wie Warenbezugkosten, anzugeben.

[discrete]
=== Rechte für Backend-Benutzer:innen vergeben

:rights-purpose: Wareneingänge sehen können
:right-one: pass:quotes[*Warenbestände > Wareneingänge > Anzeigen*]
:right-two: pass:quotes[*Warenbestände > Neuer Wareneingang > Anzeigen*]

include::_includes:partial$rights.adoc[]

[#500]
=== Wareneingang erfassen

Das Erfassen eines Wareneingangs teilt sich in zwei Schritte. Zunächst gibst du übergeordnete Daten wie die Lieferant:in und die Währung an. Im zweiten Schritt gibst du an, welche Artikel in welcher Menge geliefert wurden.

==== Allgemeine Daten eines Wareneingangs erfassen

Um einen Wareneingang zu erfassen, benötigst du mindestens ein Lager und ein:e Lieferant:in.
Lieferant:innen legst du als xref:crm:kontakt-erstellen.adoc#kontakt-erstellen[Kund:innen] an und ordnest ihnen den Kund:innen-Typ Lieferant zu.
Außerdem muss mindestens ein:e Benutzer:in als xref:business-entscheidungen:benutzerkonten-zugaenge.adoc#40[Eigner:in für Wareneingänge] aktiviert sein, damit der Wareneingang einer Eigner:in zugeordnet werden kann.
Ohne Eigner:in kann kein Wareneingang erfasst werden.
Die Eigner:innen stehen dir nach ID sortiert zur Verfügung.
Wenn die eingeloggte Benutzer:in als Eigner:in möglich ist, wird diese vorausgewählt.

[.instruction]
Allgemeine Daten eines Wareneingangs erfassen:

. Öffne das Menü *Waren » Neuer Wareneingang*.
. Klicke auf *Neuer Wareneingang* (icon:plus-square[role="green"]). +
→ Ein neues Tab wird geöffnet.
. Trage einen *Lieferanten* ein. +
→ Mit der Pfeiltaste nach unten öffnest du eine Liste aller Lieferant:innen. Alternativ werden ab Eingabe des dritten Buchstabens Vorschläge eingeblendet.
. Wähle ein Lager. +
→ Wenn ein Hauptlager für die Variante gespeichert ist, ist das xref:artikel:artikel-verwalten.adoc#290[Hauptlager] vorausgewählt.
. Wähle eine:n Eigner:in. +
→ Wenn du als xref:business-entscheidungen:benutzerkonten-zugaenge.adoc#40[Eigner:in] für Wareneingänge aktiviert wurdest, bist du als eingeloggte:r Benutzer:in als Eigner:in vorausgewählt.
. Nimm weitere optionale Einstellungen vor.
. Klicke auf *Speichern* (icon:save[role="green"]), um den Wareneingang anzulegen. +
→ Der Wareneingang wird in einem Tab geöffnet, erhält eine ID und den Status *Erfasst*. Mit Klick auf das Plus am linken Rand der Kopfzeile des Wareneingangs werden weitere Angaben sichtbar.

Wenn du den Wareneingang in einer anderen Währung als deiner xref:payment:waehrungen.adoc#30[Standardwährung] bezahlst, wird der xref:payment:waehrungen.adoc#20[Umrechnungskurs] voreingetragen.

Um den Wareneingang zu vervollständigen, füge Artikel und Warenbezugskosten hinzu.

[#600]
==== Artikel zum Wareneingang hinzufügen

Du kannst Varianten einzeln oder auch mehrere Varianten gleichzeitig hinzufügen. Es können jedoch nur Varianten von Artikeln hinzufügt werden, die bereits angelegt sind. Wenn ein neuer Artikel geliefert wird, lege zunächst den Artikel mit Varianten im Menü xref:artikel:neue-artikel.adoc#[Artikel] an.
Zunächst werden dir alle Artikel aller Lieferant:innen aufgelistet. Nutze die Suche, um Artikel einzelner Lieferant:innen anzuzeigen. +
Wenn du einen Einkaufspreis für eine Variante eingetragen hast, ist dieser hier voreingetragen und kann übernommen werden. Ein Klick auf die Artikel-ID öffnet den Artikel zur Bearbeitung. Wie du vorgehst, um die gelieferten Artikel dem Wareneingang hinzuzufügen, wird nachfolgend beschrieben.

[#700]
[discrete]
===== Varianten einzeln hinzufügen

Um Varianten einzeln hinzuzufügen, gehe vor wie foglt.

[.instruction]
Varianten einzeln hinzufügen:

. Öffne das Menü *Waren » Neuer Wareneingang*.
. Öffne einen Wareneingang.
. Klicke auf *Artikel hinzufügen* (icon:plus-square[role="green"]). +
→ Die Übersicht der vorhandenen Artikel wird geöffnet.
. Nutze die Suche und verwende Filter, um die Ergebnisse einzugrenzen. Beachte dabei die Erläuterungen in <<tabelle-variantenfilter-wareneingang>>.
. Klicke auf *Suchen* (icon:search[role="blue"]). +
→ Die Artikel, die den eingegebenen Suchkriterien entsprechen, werden aufgelistet.
. Trage optional den *Einkaufspreis* ein.
. Trage die *Menge* ein (Pflichtangabe). +
→ Die Variante wird nach dem Eingeben der Menge automatisch gewählt.
. Wähle einen *Lagerort* aus der Dropdown-Liste. +
→ Wenn du einer Variante noch keinen Lagerort zugeordnet hast, kannst du hier auch einen Lagerort zuordnen. Klicke dafür auf *Suchen*. Der Standard-Lagerort ist ein Platzhalter-Lagerort und bedeutet, dass kein Lagerort zugeordnet ist.
. Trage optional eine *UVP* ein. +
→ Die UVP wird nach Freigabe des Wareneingangs in die Variantendaten übernommen.
. Klicke in der Spalte *Aktionen* auf *Artikel hinzufügen* (icon:plus-square[role="green"]). +
→ Die Variante wird dem Wareneingang hinzugefügt.

[[tabelle-variantenfilter-wareneingang]]
.Artikelfilter
[cols="1,2"]
|===
|Einstellung |Erläuterung

|*Artikel-ID*
|Filtert nach der ID des Artikels.

|*Varianten-ID*
|Filtert nach der ID der Variante.

|*Variantennummer*
|Filtert nach der Nummer der Variante.

| *Artikeldaten*
|Durchsucht den Artikelnamen 1 und die Meta-Keywords eines Artikels.

| *Barcode*
|Filtert Barcodes wie EAN, UPC oder ISBN je nach Barcodetyp, den du angelegt hast.

|*Lieferantenartikelnummer*
|Filtert nach der Lieferantenartikelnummer.

|*Nachbestellungs-ID*
|Filtert nach der ID der Nachbestellung.
|===

Mit Klick auf *Zurücksetzen* (icon:undo[role="orange"]) setzt du alle Filtereinstellungen zurück, sodass dir alle Artikel unabhängig von der Lieferant:in angezeigt werden. Führe nach dem Zurücksetzen eine Suche aus, damit die Liste aktualisiert wird.

[#800]
[discrete]
===== Mehrere Varianten gleichzeitig hinzufügen

Wenn du mehrere Varianten gleichzeitig hinzufügen möchtest, trage die Menge und optional auch den Einkaufspreis ein. +
*_Tipp:_* Nutze die Tabulatortaste, um ins nächste Eingabefeld zu springen.

Du kannst nur Varianten der aktuellen Seite hinzufügen. Beim Wechsel auf eine neue Seite wird die Liste für diese Seite geladen und vorherige Angaben werden verworfen.

[.instruction]
Mehrere Varianten hinzufügen:

. Öffne das Menü *Waren » Neuer Wareneingang*.
. Öffne einen Wareneingang.
. Klicke auf *Artikel hinzufügen* (icon:plus-square[role="green"]). +
→ Ein Fenster zur Artikelsuche und -auswahl wird geöffnet.
. Trage Suchbegriffe ein und wähle Filter. Beachte dabei die Erläuterungen in <<tabelle-variantenfilter-wareneingang>>.
. Klicke auf *Suchen*. +
→ Die Varianten, die den eingegebenen Suchkriterien entsprechen, werden aufgelistet.
. Trage optional den *Einkaufspreis* ein.
. Trage die *Menge* ein (Pflichtangabe). +
→ Die Variante wird nach Eingabe der Menge automatisch gewählt.
. Trage optional eine *UVP* ein. +
→ Die UVP wird nach Freigabe des Wareneingangs in die Artikeldaten übernommen.
. Trage die *Menge*, den *Einkaufspreis* und die *UVP* für weitere Varianten ein.
. Klicke oberhalb der Artikelliste auf *Hinzufügen* (icon:plus-square[role="green"]). +
→ Die Varianten werden dem Wareneingang hinzugefügt.

Wenn du erneut eine Menge der gleichen Variante hinzufügst und der Einkaufspreis sowie der Lagerort gleich sind, wird diese Menge zur bereits vorhandenen Menge addiert. Wenn sich Einkaufspreis oder Lagerort unterscheiden, wird die Variante noch einmal aufgeführt.

[#810]
=== Wareneingang mit MHD und/oder Charge buchen

Du kannst Varianten mit Mindesthaltbarkeitsdatum (MHD) und/oder Chargeninformationen einbuchen.
Dafür muss an der Variante im Tab *Lager* für das Lager die Option *MHD* und/oder *Charge* aktiviert sein.
xref:warenwirtschaft:variations-track-stock.adoc#300[Weitere Informationen zur Einstellung findest du hier].

[IMPORTANT]
.Variante mit MHD und Charge einbuchen
====
Standardmäßig darf auf einen Lagerort pro Variante nur ein MHD/Charge gebucht werden. Es wird empfohlen, diese Einstellung nicht zu ändern. Wenn du unterschiedliche MHD/Chargen auf denselben Lagerort buchst, kann es zu Problemen bei der Kommissionierung kommen. Die Einstellung nimmst du im Menü *Einrichtung » Waren » Warenbestand » Wareneingang* über die Option *Lagerort auf Chargen/MHD beim Wareneingang beschränken* vor.
====

[.instruction]
Varianten mit MHD und/oder Charge hinzufügen:

. Öffne das Menü *Waren » Neuer Wareneingang*.
. Öffne einen Wareneingang.
. Klicke auf *Artikel hinzufügen* (icon:plus-square[role="green"]). +
→ Ein Fenster zur Artikelsuche und -auswahl wird geöffnet.
. Trage Suchbegriffe ein und wähle Filter. Beachten dazu die Erläuterungen in <<tabelle-variantenfilter-wareneingang>>.
. Klicke auf *Suchen*. +
→ Die Varianten, die den eingegebenen Suchkriterien entsprechen, werden aufgelistet.
. Trage optional den *Einkaufspreis* ein.
. Trage die *Menge* ein (Pflichtangabe). +
→ Die Variante wird nach dem Eingeben der Menge automatisch gewählt.
. Trage einen Wert für *MHD/Charge* ein.
. Trage optional eine *UVP* ein. +
→ Die UVP wird nach Freigabe des Wareneingangs in die Artikeldaten übernommen.
. Trage die *Menge*, den *Einkaufspreis* und die *UVP* für weitere Varianten ein.
. Klicke auf die Schaltfläche *Hinzufügen* (icon:plus-square[role="green"]), die oberhalb der Artikelliste angezeigt wird.  +
→ Die Varianten werden dem Wareneingang hinzugefügt.

[#900]
=== Warenbezugskosten hinzufügen

Kosten, die beim Bezug der Ware anfallen, hinterlegst du als Warenbezugskosten.

[.instruction]
Warenbezugskosten hinzufügen:

. Öffne das Menü *Waren » Neuer Wareneingang*.
. Öffne den gewünschten Wareneingang.
. Klicke auf das kleine Plus, um die Kopfzeile aufzuklappen.
. Klicke auf *Warenbezugskosten* (Münzen). +
→ Ein Fenster wird geöffnet.
. Trage deine Kosten ein.
. Klicke auf *Speichern* (icon:save[role="green"]). +
→ Die Kosten werden hinzugefügt.

[#1000]
=== Status ändern und nachvollziehen

Sobald du einen Wareneingang angelegt hast, erhält dieser den Status *Erfasst*. Alle Änderungen des Status werden in der *Statushistorie* gespeichert. Mit einem Klick auf *Statushistorie öffnen* (icon:history[role="blue"]) kannst du sehen, von wem, wann und über welches Medium ein Status geändert wurde.

[.instruction]
Status ändern:

. Öffne das Menü *Waren » Neuer Wareneingang*.
. Öffne einen Wareneingang.
. Wähle einen Status aus der Dropdown-Liste. Die Status *In Prüfung*, *Fehler*, *Storniert* und *Freigegeben* stehen zur Verfügung.
. *Speichere* (icon:save[role="green"]) den Status. +
→ Der Status wird geändert.

[[tabelle-status-wareneingang]]
.Verfügbare Status
[cols="1,2"]
|===
|Status |Erläuterung

| *Erfasst*
|Jeder Wareneingang erhält diesen Status automatisch nach dem Anlegen.

| *In Prüfung*
|Dieser Status ist sinnvoll, wenn alle gelieferten Artikel erfasst sind und noch einmal ein Abgleich mit dem Lieferschein oder einer Bestellung erfolgt.

| *Fehler*
|Für Wareneingänge, die einen Fehler enthalten.

| *Storniert*
|Für Wareneingänge, die nicht mehr genutzt werden sollen. Wareneingänge können nicht gelöscht werden, daher bietet sich dieser Status für fehlerhafte Wareneingänge an.

| *Freigegeben*
|Die Ware wird dem Bestand hinzugefügt, d.h. sie wird für ausstehende Aufträge, neue Listings etc. berücksichtigt. Daher wird der Wareneingang für eine weitere Bearbeitung gesperrt.

| *Korrektur*
|Erlaubt die erneute Bearbeitung einiger Angaben, wie Lieferant:in, Lieferscheinnummer etc. Der Einkaufspreis kann allerdings nicht mehr bearbeitet werden.
|===

[#1100]
=== Bestand auf Variante buchen

Durch die Freigabe des Wareneingangs wird die Menge im Wareneingang dem Bestand einer Variante hinzugefügt und die UVP aus dem Wareneingang wird für die Variante übernommen. Bei unterschiedlichen UVPs für eine Variante wird die höchste UVP in die Variante übernommen. +
Sobald ein Wareneingang den Status *Freigegeben* erhält, können Varianten weder geändert noch weitere Varianten hinzugefügt werden. Auch andere Daten, wie z.B. die Lieferant:in, sind im Status *Freigegeben* nicht mehr änderbar.

Den Bestand einer Variante siehst du im Tab *Bestand* » Tab *Warenbestand*. Im Tab *Warenbewegung* werden zusätzlich alle Warenbewegungen angezeigt, d.h. hier siehst du auch, wenn z.B. der Einkaufspreis im Wareneingang geändert wurde. Alle Änderungen der Artikelmenge oder des Einkaufspreises in einem Wareneingang werden unabhängig vom Status des Wareneingangs als Warenbewegungen festgehalten.

Den Bestand aller Artikel und Varianten siehst du im Menü xref:warenwirtschaft:warenbestaende-verwalten.adoc#[Waren » Warenbestände].

[#1200]
=== Notiz hinzufügen

Nutze Notizen, um z.B. Informationen für Kolleg:innen zur Nachbearbeitung zu speichern. Notizen lassen sich nicht ändern oder löschen.

[.instruction]
Notiz hinzufügen:

. Öffne das Menü *Waren » Neuer Wareneingang*.
. Öffne einen Wareneingang.
. Klicke auf *Notizen* (terra:order_note[role="blue"]). +
→ Ein Fenster wird geöffnet.
. Gib eine Notiz ein.
. Optional kannst du deine Notiz auch formatieren.
. Klicke auf *Speichern* (icon:save[role="green"]). +
→ Die Notiz wird gespeichert und links im Notizfenster angezeigt.

[#1300]
=== Wareneingang ändern und korrigieren

Ob du einen Wareneingang noch ändern kannst oder nicht, hängt vom Status des Wareneingangs ab. In den Status *Erfasst*, *In Prüfung*, *Fehler* und *Storniert* sind Wareneingänge noch änderbar. Angaben wie z.B. Lieferant:in, Lieferscheinnummer und Artikelmenge lassen sich ändern. Bei Änderungen von sensiblen Daten, wie Einkaufspreis und Artikelmenge, wird automatisch eine Notiz angelegt. Als Autor:in der Notiz wird die bearbeitende Person gespeichert. Freigegebene Wareneingänge können nicht mehr geändert werden. Im Status *Korrektur* sind die Menge und übergeordnete Angaben wie das Lager etc. wieder änderbar.

[#1400]
=== Wareneingang exportieren

Der Export eines Wareneingangs erfolgt im CSV-Format. Gehe wie nachfolgend beschrieben vor, um einen Wareneingang zu exportieren.

[.instruction]
Wareneingang exportieren:

. Öffne das Menü *Waren » Neuer Wareneingang*.
. Wähle einen Wareneingang.
. Klicke links auf das kleine Plus, um den Kopfbereich des Wareneingangs zu öffnen.
. Klicke auf *Export* (icon:download[role="purple"]). +
→ Die Datei wird heruntergeladen.
. Wähle beim Öffnen der Datei *Semikolon* als Trennzeichen.

[#1500]
=== PDF-Beleg erstellen

Das Erstellen eines PDF-Belegs ist nur im Status *Freigegeben* möglich.

[.instruction]
PDF-Beleg erstellen:

. Öffne das Menü *Waren » Neuer Wareneingang*.
. Wähle einen Wareneingang.
. Klicke links auf das kleine Plus, um den Kopfbereich des Wareneingangs zu öffnen.
. Klicke auf *Beleg erstellen*. +
→ Der Beleg wird im PDF-Format heruntergeladen.

[#1550]
== Ware über die plentymarkets App einbuchen

Ware kann auch über die plentymarkets App eingebucht werden. Wie das geht und welche Einstellungen du im Voraus vornehmen musst, erfährst du auf der Handbuchseite xref:app:einbuchen-umbuchen.adoc#[Ware einbuchen und umbuchen].

[#1600]
== Wareneingang suchen

Für die Suche nach Wareneingängen gibt es zwei Menüs, *Waren » Wareneingänge* und *Waren » Neuer Wareneingang*. Im Menü *Waren » Wareneingänge* werden alle Wareneingänge aufgelistet, egal ob sie über die App, per Import-Tool oder über das Menü *Neuer Wareneingang* erfolgt sind. Im Menü *Neuer Wareneingang* werden nur Wareneingänge aufgeführt, die über dieses Menü erfolgt sind.

[#1700]
=== Neuen Wareneingang suchen

Mit der Wareneingangssuche kannst du gezielt Wareneingänge listen. Viele der Suchfilter beziehen sich auf Artikel oder Varianten eines Artikels. Mit ihnen suchst du also Wareneingänge, in denen Artikel oder Varianten mit dieser ID, Nummer oder Markierung vorkommen. Beim Öffnen des Menüs sind standardmäßig die letzten zwei Monate als Lieferzeitraum eingestellt. Wenn du einen Wareneingang suchst, der weiter zurückliegt, wird dieser erst aufgelistet, wenn du die Filter zurücksetzt.

[.instruction]
Neuen Wareneingang suchen:

. Öffne das Menü *Waren » Neuer Wareneingang*.
. Wähle die gewünschten Sucheinstellungen. Beachte dazu die Erläuterungen in <<tabelle-wareneingang-suchen-app>>.
. Klicke auf *Suchen* (icon:search[role="blue"]). +
→ Die Wareneingänge, die den Suchkriterien entsprechen, werden angezeigt.

[[tabelle-wareneingang-suchen-app]]
.Sucheinstellungen für Wareneingänge
[cols="1,2"]
|===
|Einstellung |Erläuterung

| *Barcode*
|Sucht Varianten mit dem eingetragenen Barcode. Ein Barcode kann eine EAN, UPC, ISBN etc. sein.

| *Nachbestellungs-ID*
|Sucht alle Wareneingänge, in denen ein Artikel aus der Nachbestellung enthalten ist.
|===

[#1800]
=== Wareneingang im Menü *Waren » Wareneingänge* suchen

Waren gehen auf verschiedenen Wegen ins System ein. Du kannst Waren z.B. per Rest, per Import-Tool, in den Artikeldaten oder über das Menü *Neuer Wareneingang* einbuchen. Egal auf welchem Weg die Ware in dein System eingebucht wurde, im Menü *Waren » Wareneingänge* findest du alle Wareneingänge. Die Suche erfolgt immer monatsweise.

[.instruction]
Wareneingang suchen:

. Öffne das Menü *Waren » Wareneingänge*.
. Wähle die gewünschten Filter. Der aktuelle Monat ist voreingestellt. +
. Klicke auf *Suchen* (icon:search[role="blue"]). +
→ Die Wareneingänge, die den Suchkriterien entsprechen, werden angezeigt.

[IMPORTANT]
.Archivierte Einträge erkennen
====
Archiviert wird ein Eintrag frühestens nach drei Monaten und dann auch nur, wenn bereits alle eingegangenen Waren wieder ausgebucht oder umgebucht wurden. Wenn ein Wareneingang arichiviert wurde, wird ein Archivsymbol in der Spalte *Archiv* angezeigt.
Archivdaten können nicht geändert oder gelöscht werden.
====

Folgende Möglichkeiten stehen dir in diesem Menü außerdem zur Verfügung:

* Wareneingänge monatsweise exportieren
* Wareneingänge öffnen, bearbeiten und einzeln exportieren

Im Tab *Base* können die Einstellungen *Lieferant*, *Lieferdatum* und *Lieferscheinnummer* geändert werden. Im Tab *Artikel* ist es möglich, den *Einkaufspreis* anzupassen.

[#1900]
== Leere Lagerorte löschen

Im Menü *Einrichtung » Waren » Warenbestand » Wareneingang* gibt es die Möglichkeit, einen Zeitraum zu bestimmen, nach dem leere Lagerorte gelöscht werden. Bei Aktivierung der Option *Leeren Lagerort löschen nach* wird der Eintrag nach Ablauf des festgelegten Zeitraums aus der Tabelle entfernt und die Verknüpfung mit den einzelnen Artikeln wird gelöscht. Im System wird dann nicht mehr berücksichtigt, dass der Artikel jemals auf dem Lagerort gelagert war. +
*_Hinweis:_* Dies gilt nicht für den Standard-Lagerort (ID 0) des Hauptlagers am Artikel oder an der Variante; dieser ist immer sichtbar.

[#2000]
== Lagerbestandseinträge von 0 ausblenden

Im Menü *Einrichtung » Waren » Warenbestand » Wareneingang* gibt es die Möglichkeit, Lagerbestandseinträge von 0 nach einem bestimmten Zeitraum auszublenden. Lagert man einen Artikel in einem zweiten Lager, geht der Bestand auf Null. Mit Aktivierung der Option *Lagerbestandseintrag von “0” ausblenden nach*, wird der Eintrag in der Bestandsübersicht der Variante nach dem festgelegten Zeitraum ausgeblendet, bleibt aber im Hintergrund gespeichert. Dadurch können Rückbuchungen oder Wareneingänge, die als Einstellung *Verwendeter Lagerort* haben, diesen weiterhin nutzen bzw. anzeigen. +
*_Hinweis:_* Dies gilt nicht für den Standard-Lagerort (ID 0) des Hauptlagers am Artikel oder an der Variante; dieser ist immer sichtbar.
