= FAQ: plentyShop LTS
:keywords: FAQ, FAQs, Frequently Asked Questions, Häufig gestellte Fragen, Fragenkatalog
:description: Auf dieser Seite findest du eine Liste der häufig gestellten Fragen zum Thema plentyShop LTS.
:id: PW5LCY3
:author: team-webshop
:description: Hier findest du die am häufigsten gestellten Fragen zum Thema plentyShop LTS.

////
zuletzt bearbeitet 20.09.22
////

// TODO: Alle FAQs aus Forum importieren

Auf dieser Seite findest du einige häufig gestellte Fragen rund um plentyShop LTS.

// expand

[#general]
== Allgemeine Fragen

[.collapseBox]
.*Was bedeutet LTS?*
--

Seit der plentyShop-Version 5.0.0 die wir am 20. April 2020 veröffentlicht haben, handelt es sich bei plentyShop LTS, um eine sogenannte **Long-Term-Support** Version.
Das bedeutet für uns, dass wir plentyShop weiterhin mit Updates für Fehlerbehebungen, Stabilität und Rechtssicherheit versorgen. 
Wir versuchen Änderungen, die wir in der LTS am Plugin durchführen, immer auf das Notwendigste zu begrenzen, damit Kund:innen problemlos updaten können und keine Anpassungen an anderen Plugins, Themes und benutzerdefinierten Änderungen notwendig werden. 
Auf der anderen Seite bedeutet der LTS-Status aber auch, dass wir keine Änderungen mehr vornehmen werden, die zu sogenannten Breaking Changes führen und die Stabilität des Produkts gefährden.
--

[.collapseBox]
.*Wie lange wird plentyShop LTS bestehen?*
--
Nach momentanem Planungsstand werden wir plentyShop LTS bis mindestens Q1/2025 anbieten.
--

[.collapseBox]
.*Wie kann ich mich an der Entwicklung von plentyShop LTS beteiligen?*
--
Wir bieten regelmäßige öffentliche Reviews an, in denen wir die Ergebnisse der letzten Wochen präsentieren. Kund:innen können an diesen Reviews teilnehmen und ihre Fragen und ihr Feedback einbringen. Alle aktuellen Informationen rund um unsere Reviews findest du link:https://forum.plentymarkets.com/t/ankuendigung-oeffentliches-review-von-team-plentyshop-announcement-public-review-team-plentyshop/693618[in diesem Forenpost^]. +

Falls du selbst Entwickler:in bist und dich in der Weiterentwicklung von plentyShop LTS einbringen willst, erklärt dir unser link:https://github.com/plentymarkets/plugin-ceres/blob/stable/contributionGuide.md[Contribution Guide^] was du beachten musst.

--

[.collapseBox]
.*Wie bediene ich den ShopBuilder und was kann ich damit machen?*
--

In unserem link:https://www.youtube.com/watch?v=s_9DCTlF_qg[Livestream^] am 17. April 2020 haben wir euch das Arbeiten mit dem ShopBuilder vom ersten Schritt bis zum fertigen, voll funktionstüchtigen plentyShop vorgestellt. Außerdem zeigt der Live-Mitschnitt viele neue Funktionen von plentyShop LTS, wie beispielsweise Artikelsets und neue Widgets für die Suche. Der Live-Mitschnitt ist ein toller Einstiegspunkt für plentyShop-Neulinge.

--

[.collapseBox]
.*Wie gehe ich am besten bei einem Update von plentyShop LTS vor?*
--

Am besten hältst du dich beim Updaten von plentyShop LTS an link:https://knowledge.plentymarkets.com/de-de/manual/main/webshop/best-practices.html#updates[diesen Best Practice^].

--

[#troubleshooting]
== Troubleshooting

[.collapseBox]
.*Warum wird meine Kategorie nicht im Shop angezeigt?*
--

Gehe xref:artikel:checkliste-kategorien-anzeige.adoc#[diese Checkliste] Schritt für Schritt durch. Sollte deine Kategorie trotzdem nicht angezeigt werden, kontaktiere uns im link:https://forum.plentymarkets.com/c/plentyshop[Forum^].

--

[.collapseBox]
.*Warum wird mein Artikel nicht im Shop angezeigt?*
--

Gehe xref:artikel:checkliste-artikel-anzeige.adoc#[diese Checkliste] Schritt für Schritt durch. Sollte dein Artikel trotzdem nicht angezeigt werden, kontaktiere uns im link:https://forum.plentymarkets.com/c/plentyshop[Forum^].

--

[.collapseBox]
.*Mein Shop erzielt keine guten Werte bei Page Speed Insights. Was kann ich tun, um meine Werte zu verbessern?*
--

Schau dir mal xref:webshop:best-practices#psi[diesen Best Practice] an und setze die einzelnen Punkte so gut du kannst um.

--

[.collapseBox]
.*Ich bin unzufrieden mit der Suche in meinem Onlineshop. Wie kann ich die Suche nach meinen Bedürfnissen anpassen?*
--

Schau dir mal xref:webshop:best-practices#suche[diesen Best Practice] an und setze die einzelnen Punkte so gut du kannst um.

--

[.collapseBox]
.*Warum werden in der Kategorienavigation nur 2 Ebenen und nicht 4 Ebenen angezeigt?*
--

Die Anzahl der Ebenen steuerst du über die Widget-Einstellungen im ShopBuilder. 
In der normalen Kategorienavigation kannst du nur 2 Ebenen ausgeben lassen.
Wenn du 4 Ebenen ausgeben willst, kannst du im ShopBuilder im Widget *Kategorienavigation* den Stil auf *Mega Menü* ändern. 
Falls du mehr als 4 Ebenen anzeigen lassen willst, musst du dies über ein eigenes Theme anpassen.

--

[.collapseBox]
.*Warum wird mir im Shop anderer Inhalt angezeigt als im ShopBuilder?*
--

Das liegt vermutlich am Cache. Dein Shop ist noch auf einem älteren Stand als der Inhalt im ShopBuilder. Lösche deine Cookies und Website-Daten wie in link:https://forum.plentymarkets.com/t/howto-cookies-und-website-daten-loeschen-clear-cookies-and-site-data/571579[diesem Forenbeitrag^] beschrieben und versuche es erneut.

--

[.collapseBox]
.*In meinem plentyShop werden veraltete Daten angezeigt. Wieso werden meine Änderungen nicht live im Shop angezeigt?*
--
Falls du den *ShopBooster* nutzt, musst du den Cache möglicherweise einmal selbst invalidieren. Wie das geht, erfährst du auf der xref:webshop:ceres-einrichten#sofort-invalidieren[plentyShop LTS Handbuchseite].

--

[.collapseBox]
.*Warum wird im Beschreibungstext meiner Kategorie im Shop etwas anderes angezeigt, als ich im Backend gespeichert habe?*
--
Für plentyShops, die mit dem ShopBuilder gestaltet werden, greifen die alten Kategorieeinstellungen nicht mehr vollumfänglich. Falls du im Menü *Artikel » Kategorien* Texte in den Kategorieeinstellungen gepflegt hast (bspw. in den Tabs *Beschreibung 1*, *Beschreibung 2* oder *Template*), musst du diese Texte auch in den betreffenden ShopBuilder-Inhalten pflegen, da die Texte nicht automatisch übernommen werden können.
--


[.collapseBox]
.*In meinem Shop kommt die Fehlermeldung "Bei der Versandkostenberechnung kam es zu einem Fehler. Bitte benachrichtigen Sie den Betreiber." Was kann ich dagegen tun?*
--

Unsere Freund:innen von Team Fulfillment haben link:https://forum.plentymarkets.com/t/fulfillment-faq/591262/5[eine Checkliste^] zusammengestellt, die dir wahrscheinlich weiterhelfen wird.

--

[.collapseBox]
.*Ich möchte den Text „inkl. ges. MwSt. zzgl. Versandkosten“ auf der Artikel- und Kategorieseite ändern. Wo kann ich dies tun?*
--

Du kannst die meisten Onlineshop-Texte im Menü **CMS » Mehrsprachigkeit** anpassen.
Diesen Textbaustein passt du an den folgenden beiden Stellen an:
- CMS » Mehrsprachigkeit » Plugin-Set wählen » Sprache wählen » Bereich: Ceres » Artikel
- CMS » Mehrsprachigkeit » Plugin-Set wählen » Sprache wählen » Bereich: Ceres » Artikelansicht

*Speichere* deine Änderungen und stelle das Plugin-Set neu bereit, damit die Änderungen in deinem Shop erscheinen.

--

[.collapseBox]
.*Ich möchte eine Datei in meinem CMS » Webspace hochladen, allerdings dauert es sehr lange bis ich den Webspace öffnen kann. Auch das Hochladen einer Datei dauert sehr lange. Woran kann das liegen?*
--

Eine hohe Anzahl an Dateien im Webspace kann die Performance nachteilig beeinflussen.
Versuche deine Dateien in Unterordnern zu verwalten, um die Menge an gleichzeitig angezeigten Dateien zu verringern. 
Beachte, dass eine Datei im Webspace nicht über 10 MB groß sein darf.
Beachte beim Upload-Prozess, dass du maximal 10 Dateien auf einmal hochladen kannst.

--

[.collapseBox]
.*In meinem plentyShop werden veraltete Daten angezeigt. Wieso werden meine Änderungen nicht live im Shop angezeigt?*
--
Falls du den *ShopBooster* nutzt, musst du den Cache möglicherweise einmal selbst invalidieren. Wie das geht, erfährst du auf der xref:webshop:ceres-einrichten#sofort-invalidieren[plentyShop LTS Handbuchseite].

--

[.collapseBox]
.*Wie gehe ich am besten bei einem Update von plentyShop LTS vor?*
--

Am besten hältst du dich beim Updaten von plentyShop LTS an link:https://knowledge.plentymarkets.com/de-de/manual/main/webshop/best-practices.html#updates[diesen Best Practice^].

--

[.collapseBox]
.*Wie tausche ich das Firmenlogo aus?*
--

Du kannst das Firmenlogo im Header deines plentyShops über den ShopBuilder austauschen. 

. Öffne das Menü _CMS » ShopBuilder_.
. Wähle eine Kategorie im Kategoriebaum auf der linken Seite.
. Öffne einen Inhalt im Bereich **Header-Inhalte**, indem du darauf klickst.
. Öffne die Widget-Einstellungen des Widgets **Kategorienavigation**.
. In der Einstellung *Firmenlogo* kannst du eine Bilddatei für dein Logo hochladen.
. Klicke auf *Datei wählen*, um eine Bilddatei aus dem Webspace zu wählen oder eine neue Bilddatei hochzuladen.
. Klicke im Menü *Meine Dateien* auf die Zeile der Bilddatei, die du als Logo wählen möchtest.
. Klicke auf die *Wählen*-Schaltfläche. +
+
Achte auf die Sichtbarkeit des Headers. Wenn du unterschiedliche Header im Einsatz hast, musst du das Firmenlogo in mehr als einem Header-Inhalt austauschen.

--

[.collapseBox]
.*Wie kann ich einstellen, welche Variante auf der Artikelkachel in der Kategorie angezeigt wird?*
--
Welche Variante auf der Artikelkachel gezeigt wird, kannst du mit der Einstellung *Sortierung der Varianten für die Artikelkachel* im plentyShop LTS Assistenten einstellen. Die Einstellung findest du im Schritt *Seitennummerierung und Sortierung*.

--