= Template-Funktionen
:page-index: false

== Allgemeines

Die CMS-Syntax unterstützt unterschiedliche Arten von Funktionen, welche entweder global oder nur innerhalb bestimmter Templates verwendet werden können.

== Globale Funktionen

In diesem Bereich sind solche Funktionen zu finden, welche sowohl im Bereich Webdesign als auch in E-Mail-Vorlagen verwendet werden können.

Einige PHP-Funktionen wurden auch in der CMS-Syntax zugänglich gemacht. Die Verwendung ist weitestgehend identisch mit der Verwendung direkt in PHP.

xref:webshop:cms-syntax.adoc#global-phpfunctions[PHP Funktionen öffnen]

== Webdesign

[.row]
====
[.col-md-6]
.PageDesign
=====
Vorranging findest du in diesem Bereich Link-Funktionen, welche URLs auf bestimmte Bereiche (u.a. Kategorien, Startseite, Warenkorb) zurückliefern.

xref:webshop:cms-syntax.adoc#webdesign-pagedesign[PageDesign öffnen]
=====

[.col-md-6]
.Navigation
=====
Die unterschiedlichen Container zur Darstellung von Navigationsmenüs (Kategorie-Navigation) werden über Funktionen dieses Bereichs aufgerufen.

xref:webshop:cms-syntax.adoc#webdesign-navigation[Navigation öffnen]
=====
====

[.row]
====
[.col-md-6]
.ItemView
=====
Zur Darstellung von Artikeln (u.a. Produktseite, Suchergebnis) stehen die meisten Container und demzufolge auch die größte Anzahl an Funktionen zur Verfügung.

xref:webshop:cms-syntax.adoc#webdesign-itemview[ItemView öffnen]
=====

[.col-md-6]
.Category
=====
Dieser Bereich verfügt über eine sehr übersichtliche Anzahl an Funktionen. Relevant ist jedoch die Funktion Form(), welche ein Formular zurückliefert.

xref:webshop:cms-syntax.adoc#webdesign-category[Category öffnen]
=====
====
== E-Mail-Vorlagen

Innerhalb von E-Mail-Vorlagen stehen einige Link-Funktionen zur Verfügung.

xref:owebshop:cms-syntax.adoc#e-mail-email[E-Mail öffnen]
