= Artikel und Varianten manuell anlegen
:keywords: Neue Artikel-UI, Artikel » Artikel-UI, Artikel erstellen, Artikeldaten erstellen, Artikel anlegen, Artikeldaten anlegen, Variante erstellen, Variantendaten erstellen, Variante anlegen, Variantendaten anlegen, Artikelanlage, Artikel anlage, Artikel manuell anlegen, Artikel manuell erstellen, Neuer Artikel, Neue Artikel, Neue Variante, Neue Varianten, Neues Produkt, Neue Produkte, Variantenanlage, Varianten anlage, Variante anlage, Artikelerstellung
:description: Erfahre, wie du Artikel und Varianten manuell erstellst.
:id: KTXPUX4
:author: team-item

////
zuletzt bearbeitet 16.05.22
////

//ToDo - gifs erstellen
//ToDo - sobald der Artikeltyp bei der Anlage auswählbar ist, die Inhalte überarbeiten und sichtbar schalten
//ToDo - langfristig: video erstellen

Bist du bereit, deine Artikeldaten in plentymarkets einzupflegen?
Auf dieser Seite lernst du, Artikel und Varianten manuell zu erstellen.

//#video#

[discrete]
==== Ablauf

* Erstelle den xref:artikel:artikel-manuell-anlegen.adoc#200[Artikeldatensatz].
* Soll der Artikel z.B. in unterschiedlichen Größen oder Farben erhältlich sein? Dann erstelle xref:artikel:artikel-manuell-anlegen.adoc#300[alle nötigen Varianten].
* Füge xref:artikel:artikel-manuell-anlegen.adoc#400[weitere Produktdaten] wie Bilder, Texte und Bestandsinformationen hinzu.
* Schau dir regelmäßig eine xref:artikel:artikel-manuell-anlegen.adoc#500[Vorschau des Artikels im plentyShop] an und finde heraus, wo du noch weitere Produktdaten hinzufügen oder Einstellungen optimieren musst.
* xref:artikel:artikel-manuell-anlegen.adoc#600[Aktiviere den Artikel], wenn er verkaufsfertig ist.

[TIP]
.Willst du Artikel lieber importieren?
====
Diese Seite beschreibt die manuelle Erstellung von Artikeln und Varianten.
Dies ist zum Beispiel sinnvoll, wenn du nur wenige neue Produkte zum Sortiment hinzufügen möchtest.
Was aber, wenn du mehrere hundert Artikeldatensätze hinzufügen willst?
Es würde ewig dauern, dies manuell zu tun.
Wirf einen Blick auf die unterschiedlichen xref:artikel:import-export-anlage.adoc#[Tools] zum Importieren von Artikelinformationen.
Wähle das Tool, das für deine Situation am besten geeignet ist.
====

[#100]
== Voraussetzungen

Diese Seite setzt voraus, dass du bereits Grundkenntnisse über die Artikelstruktur in plentymarkets hast:

* Kennst du den xref:artikel:struktur.adoc#[Unterschied zwischen Artikeln und Varianten]?
* Weißt du, wie Varianten ihre xref:artikel:vererbung.adoc#[Daten vererben] können?

Zudem müssen folgende Daten im System vorhanden sein, um wie hier beschrieben Artikel und Varianten manuell zu erstellen:

* xref:artikel:attribute.adoc#[Attribute und Attributwerte]
* xref:artikel:kategorien.adoc#[Kategorien]
* xref:artikel:preise.adoc#[Verkaufspreise]


[#200]
== Einen neuen Artikel erstellen

Erstelle den Artikeldatensatz, indem du einige grundlegende Produktinformationen eingibst.
Keine Sorge, der Artikel wird nicht sofort zum Verkauf stehen.
Nach der Erstellung fügst du weitere Produktinformationen hinzu und aktivierst den Artikel, wenn er verkaufsfertig ist.

//#gif#

[.instruction]
Einen neuen Artikel erstellen:

. Öffne das Menü *Artikel » Artikel-UI*.
. Klicke auf *Neuen Artikel anlegen* (icon:plus[role="darkGrey"]). +
→ Ein Pop-Up Fenster wird geöffnet. Dieses Fenster ist in mehrere Schritte unterteilt.
. Nimm die Einstellungen in jedem Schritt vor.

[discrete]
==== Schritt: Artikeldaten

:manual:

[cols="1,4a"]
|===
|Einstellung |Erläuterung

//|[#intable-typ]*Typ*
//a|Welche Art von Artikel willst du erstellen? In den meisten Fällen wirst du wahrscheinlich einen "normalen Artikel" erstellen, d.h. einen Artikel vom Typ *Standard*.

//Die anderen Optionen in der Dropdown-Liste sind für andere Anwendungsfälle vorgesehen:

//* *Standard* = Erstellt einen normalen Artikel oder ein xref:artikel:multipacks-pakete-sets.adoc#2000[Artikelpaket].
//* *Set* = Erstellt ein xref:artikel:multipacks-pakete-sets.adoc#3000[Artikelset].
//* *Multipack* = Erstellt einen xref:artikel:multipacks-pakete-sets.adoc#1000[Multipack-Artikel].

//*_Hinweis_*: Diese Einstellung kann nach der Artikelanlage nicht mehr geändert werden.

| *Name* +
[red]#(Pflichtfeld)#
|Gib einen Namen für den Artikel ein.

*_Hinweis_*:
Nachdem du den Artikel erstellt hast, kannst du den Namen in weitere Sprachen übersetzen oder auch weitere Namen hinzufügen, z.B. wenn der Artikel auf Marktplätzen anders genannt werden soll.

|===

[discrete]
==== Schritt: Kategorien

[cols="1,4"]
|===
|Einstellung |Erläuterung

| *Kategorien wählen* +
[red]#(Pflichtfeld)#
a|In welche Kategorie soll der Artikel einsortiert werden?

. Klicke auf *Kategorien wählen*. +
→ Ein Pop-Up Fenster wird geöffnet.
. Erweitere die Einträge (icon:chevron-right[role="darkGrey"]) und wähle alle Kategorien (icon:check-square[role="blue"]), in denen dieser Artikel erscheinen soll.
. Klicke auf *Übernehmen*. +
→ Die gewählten Kategorien werden als Tabelle dargestellt.
Klicke auf material:delete[role="darkGrey"], um eine Kategorie aus dieser Liste zu entfernen, oder klicke auf icon:pencil[role="darkGrey"] *Kategorien wählen*, um weitere Kategorien hinzuzufügen.

*_Hinweis_*: Diese Liste enthält nur die xref:artikel:kategorien.adoc#[Kategorien], die du bereits in plentymarkets angelegt hast.

|===

[discrete]
==== Schritt: Hauptvariante (Optional)

[TIP]
.Was ist eine Hauptvariante?
====
Die erste Variante eines Artikels wird als Hauptvariante bezeichnet.
Hat ein Artikel mehrere Varianten, kann die Hauptvariante entweder selbst ein verkaufbares Produkt sein oder rein virtuell bestehen, um die weiteren Untervarianten des Artikels anhand von Vererbung zu verwalten.
====

[cols="1s,4"]
|===
|Einstellung |Erläuterung

| Variantennr.
|Gib eine Nummer für die Hauptvariante ein.

| Inhalt +
Einheit
|Gib einen numerischen Wert für die Hauptvariante ein und wähle eine Einheit aus der Dropdown-Liste, z.B. 500ml oder 150g.

| Attribute wählen
a|Die Hauptvariante kann entweder selbst ein verkaufbares Produkt sein oder rein virtuell bestehen, um die weiteren Untervarianten des Artikels anhand von Vererbung zu verwalten.
Das heißt, die Hauptvariante kann Attribute besitzen, muss es aber nicht.

. Klicke auf *Attribute wählen*. +
→ Ein Pop-Up Fenster wird geöffnet.
. Erweitere die Attribute (icon:chevron-right[role="darkGrey"]) und wähle die Attributwerte (icon:check-square[role="blue"]), die du für die Hauptvariante verwenden willst, z.B. die Größe "klein" und die Farbe "rot".
. Klicke auf *Übernehmen*. +
→ Die gewählten Attributwerte werden als Tabelle dargestellt.
Klicke auf material:delete[role="darkGrey"], um einen Attributwert aus dieser Liste zu entfernen, oder klicke auf icon:pencil[role="darkGrey"] *Attribute wählen*, um weitere Attributwerte hinzuzufügen.

*_Hinweis_*: Diese Liste enthält nur die xref:artikel:attribute.adoc#[Attribute und Werte], die du bereits in plentymarkets angelegt hast.

*_Empfehlung_*: Es ist technisch möglich, Attribute hier auszuwählen. Wir empfehlen dies jedoch nicht.
Vielmehr empfehlen wir dir, zuerst den neuen Artikel ohne Attribute anzulegen. Anschließend empfehlen wir dir, Attribute auszuwählen, während du die xref:artikel:artikel-manuell-anlegen.adoc#300[benötigten Varianten erstellst]. +
Warum? Verknüpfst du Attribute bereits jetzt mit der Hauptvariante, müssen alle folgenden Varianten zwangsläufig aus den gleichen Attributen erzeugt werden. Dies ist nicht der Fall, wenn du Attribute erst bei der Variantenanlage verknüpfst.
Im Nachhinein bist du also flexibler.
|===

[discrete]
==== Schritt: Fertig

[cols="1s,4"]
|===
|Einstellung |Erläuterung

| Zusammenfassung
a|Hier siehst du eine Zusammenfassung deiner gewählten Einstellungen.
Klicke auf *Artikel erstellen*, wenn du mit den Angaben einverstanden bist.

Nach der Erstellung hast du folgende Möglichkeiten:

[cols="1s,4a"]
!===

! Zum Artikel
!Das Pop-up-Fenster wird geschlossen und der neu erstellte Artikeldatensatz wird zur weiteren Bearbeitung geöffnet.

! Weiteren Artikel erstellen
!Das Pop-up-Fenster wird für den nächsten Artikel neu gestartet.

! Schliessen
!Das Pop-up-Fenster wird geschlossen.

!===

|===

[#300]
== Benötigte Varianten erstellen

Manche Artikel, wie Schuhe und T-Shirts, werden in verschiedenen Größen und Farben verkauft.
Mit anderen Worten: Kunden kaufen nicht nur ein T-Shirt, sondern eine bestimmte Variante eines T-Shirts, z.B. in der Farbe rot und der Größe S.
Erstelle zunächst alle nötigen Varianten.

//#gif#

[.instruction]
Benötigte Varianten erstellen:

. Öffne das Menü *Artikel » Artikel-UI » [Artikel öffnen] » Variantenübersicht*.
. Klicke auf *Varianten erstellen* (icon:plus[role="darkGrey"]). +
→ Ein Pop-Up Fenster wird geöffnet. Dieses Fenster ist in mehrere Schritte unterteilt.
. Nimm die Einstellungen in jedem Schritt vor.

[discrete]
==== Schritt: Einstellungen

[cols="1s,4"]
|===
|Einstellung |Erläuterung

| Inhalt +
Einheit
a|Nutze diesen Bereich, wenn die Varianten sich durch ihre Menge und/oder Einheit unterscheiden sollen.

*_Beispiel_*: Eine Seife, die in 100ml, 250ml und 500ml erhältlich ist.

*_Vorgehensweise_*:

. Gib die Menge und Einheit der ersten Variante ein, z.B. 100ml.
. Klicke auf *Varianten erstellen*.
. Wiederhole den Vorgang für 250ml und für 500ml.

| Attribute auswählen
a|Nutze diesen Bereich, wenn die Varianten sich durch ihre Attributwerte unterscheiden sollen.

*_Beispiel_*: Ein T-Shirt, das in der Farbe grün oder blau und in der Größe S, M oder L erhältlich ist.

*_Vorgehensweise_*:

. Klicke auf *Attribute auswählen*. +
→ Ein Pop-Up Fenster wird geöffnet.
. Erweitere die Attribute (icon:chevron-right[role="darkGrey"]) und wähle alle Attributwerte (icon:check-square[role="blue"]), die du verwenden willst, z.B. die Größen "S", "M", "L" und die Farben "grün" und "blau".
. Klicke auf *Übernehmen*. +
→ Die gewählten Attributwerte werden als Tabelle dargestellt.
Klicke auf icon:pencil[role="darkGrey"] *Attribute auswählen*, wenn du deine Auswahl ändern möchtest.
. Klicke auf *Vorschau* und vergewissere dich, dass die Kombinationen korrekt sind.
. Klicke auf *Varianten erstellen*.

*_Hinweis_*: Diese Liste enthält nur die xref:artikel:attribute.adoc#[Attribute und Werte], die du bereits in plentymarkets angelegt hast.

|===

[discrete]
==== Schritt: Vorschau

[cols="1s,4"]
|===
|Einstellung |Erläuterung

| Vorschau
|Nutze diesen Bereich, wenn du dich vergewissern willst, dass die Kombinationen korrekt sind.

*_Beispiel_*: Die Größen "S", "M", "L" kombiniert mit den Farben "grün" und "blau" ergeben 6 Varianten.

*_Hinweis_*: Oberhalb der Tabelle siehst du, wie viele Kombinationen erstellt werden.
Es gibt keine Begrenzung, wie viele Kombinationen möglich sind.
|===

[discrete]
==== Schritt: Zusammenfassung

[cols="1s,4"]
|===
|Einstellung |Erläuterung

| Zusammenfassung
|Hier siehst du eine Bestätigung, dass die Varianten erstellt wurden.

*_Hinweis_*:
Es kann einige Minuten dauern, bis die neuen Varianten in der Übersicht erscheinen.

|===

[#400]
== Weitere Produktdaten hinzufügen

Während der Artikelerstellung hast du bereits einige grundlegende Produktinformationen eingegeben.
Füge jetzt weitere Informationen hinzu.
Zum Beispiel kannst du:

* xref:artikel:verzeichnis.adoc#40[Bilder hochladen]
* xref:artikel:verzeichnis.adoc#50[Produkttexte schreiben]
* xref:artikel:verzeichnis.adoc#340[Preise hinterlegen]
* xref:artikel:verzeichnis.adoc#30[Bestandsinformationen einsehen]

[#500]
== Artikel im Frontend anschauen

Neugierig, wie das neue Produkt in deinem plentyShop oder auf Amazon aussehen wird?
Schau dir eine Vorschau des Artikels an und finde heraus, wo du noch weitere Produktdaten hinzufügen oder Einstellungen optimieren musst.

//#gif#

[.instruction]
Vorschau des Artikels ansehen:

. Klicke auf *Produkt Link* (material:open_in_new[role="darkGrey"]) in der Toolbar. +
→ Ein Pop-Up Fenster wird geöffnet.
. Nimm die Einstellungen vor.
. Klicke auf material:open_in_new[role="darkGrey"] *Öffnen*. +
→ Eine Vorschau des Artikels wird angezeigt.

[TIP]
.Produkt-Links für Artikel oder Varianten
====
Du kannst den Produkt-Link für einen Artikel oder für eine Variante aufrufen.
Der Produkt-Link Button befindet sich in der Toolbar der Artikel- und Variantenansicht.
====

[cols="1s,4a"]
|===
|Einstellung |Erläuterung

| URL
|Die URL des Produkts wird oben in einer Info-Box angezeigt.
Klicke auf die URL, um die Seite in einem neuen Tab zu öffnen.
Klicke auf terra:copy[role="darkGrey"], um die URL in die Zwischenablage zu kopieren.

| Verkaufskanal
|Möchtest du sehen, wie das Produkt in deinem plentyShop oder auf Amazon aussehen wird?

[cols="1s,4a"]
!===

! plentyShop LTS Preview
!
Du siehst eine Vorschau im plentyShop.
Mögliche Anwendungen:

* Du willst prüfen, wie ein Produkt im plentyShop aussehen wird, bevor du es für deine Endkunden sichtbar schaltest.
* Du bist gerade dabei, deinen plentyShop umzugestalten und willst prüfen, wie ein Produkt mit einem anderen Plugin-Set aussehen würde.

*_Weitere Einstellungen_*: Wähle auch den Mandanten und das Plugin-Set.

! plentyShop LTS live
!
Du siehst, wie das Produkt aktuell im plentyShop aussieht.
Mögliche Anwendung:

* Du willst prüfen, welche Preise und Informationen angezeigt werden, wenn Endkunden deinen plentyShop über ein bestimmtes Preisportal aufrufen.

*_Weitere Einstellungen_*: Wähle auch den Mandanten und die Herkunft.

! Amazon
!Du siehst eine Vorschau auf Amazon.
Stelle sicher, dass du bereits eine ASIN für die Variante hinterlegt hast.
Die Vorschau kann nur dann erstellt werden, wenn die Variante eine ASIN hat.

*_Weitere Einstellung_*: Wähle auch die ASIN.

!===

| Mandant (Shop)
|In welchem Mandanten, d.h. in welchem Webshop, willst du die Vorschau sehen?
Wähle den Mandanten aus der Dropdown-Liste aus.

*_Hintergrund-Info_*: Mit plentymarkets kannst du mehrere Webshops, d.h. xref:webshop:mandanten-verwalten.adoc#[mehrere Mandanten], mit nur einer Software verwalten.
Somit ist es möglich, über ein plentymarkets System mehrere unterschiedliche Geschäftsbereiche zu realisieren.

*_Hinweis_*: Diese Option wird nur angezeigt, wenn du den Verkaufskanal *plentyShop LTS Preview* oder *plentyShop LTS live* gewählt hast.

| Plugin-Set
|In welchem Plugin-Set willst du die Vorschau sehen?
Wähle das Plugin-Set aus der Dropdown-Liste aus.

*_Hintergrund-Info_*: In plentymarkets stehen xref:plugins:plugins.adoc#[Plugins] nicht für sich alleine, sondern werden zu sogenannten Plugin-Sets zusammengefasst.
So kannst du zum Beispiel saisonale Layouts für deinen plentyShop gestalten oder neue Versionen von Plugins testen bevor du sie live schaltest.

*_Hinweis_*: Diese Option wird nur angezeigt, wenn du den Verkaufskanal *plentyShop LTS Preview* gewählt hast.

| Herkunft
|Willst du prüfen, welche Preise und Informationen angezeigt werden, wenn Endkunden deinen plentyShop über ein bestimmtes Preisportal aufrufen?
Wähle die Herkunft aus der Dropdown-Liste aus.

*_Hinweis_*: Diese Option wird nur angezeigt, wenn du den Verkaufskanal *plentyShop LTS live* gewählt hast.

| ASIN
|Welche ASIN möchtest du für die Vorschau verwenden?
Wähle die ASIN aus der Dropdown-Liste aus.

*_Hinweis_*: Diese Dropdown-Liste enthält nur die ASINs, die bereits für die Variante hinterlegt sind.
Hast du noch keine ASIN für die Variante gespeichert?
Oder hast du noch keine ASIN aus der Dropdown-Liste gewählt?
Dann siehst du eine Fehlermeldung in der Info-Box oben.

*_Hinweis_*: Diese Option wird nur angezeigt, wenn du den Verkaufskanal *Amazon* gewählt hast.

|===

[#600]
== Produkte für den Verkauf freigeben

Varianten sind für Kunden im plentyShop nicht sichtbar, bis sie aktiviert werden.
Das heißt, du kannst an inaktiven Varianten arbeiten, ohne dass deine Kunden es merken.
Du aktivierst die Variante, sobald sie in deinem plentyShop veröffentlicht werden soll.

[.instruction]
Variante aktivieren:

. Öffne das Menü *Artikel » Artikel-UI » [Variante öffnen] » Element: Verfügbarkeit und Sichtbarkeit*.
. Wähle die Option *Aktiv* (icon:toggle-on[role="blue"]).
. *Speichere* (terra:save[role="darkGrey"]) die Einstellungen.

[TIP]
.Vollständige Checkliste zur Artikel-Sichtbarkeit
====
Artikel müssen nicht nur aktiviert werden, sondern benötigen sie auch einen Preis, eine Kategorie und positive Netto-Warenbestand.
Sonst werden Kunden den Artikel nicht kaufen können.
Arbeite xref:artikel:checkliste-artikel-anzeige.adoc#[diese Checkliste] durch und vergewissere dich, dass dein Artikel alle Voraussetzungen erfüllt, um im plentyShop sichtbar zu sein.
Diese Checkliste hilft dir, mögliche Fehlerquellen bei der Artikelsichtbarkeit ausfindig zu machen.
====
