= Barcodes und Etiketten
:keywords: Barcode, Barcodes, Etikett, Etiketten, Artikeletikett, Artikeletiketten, Barcode-Typ, Barcodetyp, Barcode-Typen, Barcodetypen, GS1, GTIN, ISBN, QR, CODE 128, UPC, FNSKU, Nummernkreis, Grundpreis
:description: Lerne, Barcodes Schritt für Schritt einzurichten und auf Artikeletiketten anzuzeigen.
:author: team-item

////
zuletzt bearbeitet 01.12.2022
////

Barcodes dienen zur eindeutigen Kennzeichnung von Artikeln.
Sie werden zum Beispiel auf Artikel-Etiketten oder auf Dokumenten wie Rechnungen und Lieferscheinen dargestellt.

Diese Handbuchseite führt dich Schritt für Schritt durch die Einrichtung:

* xref:artikel:barcodes.adoc#100[Konfiguriere die Barcode-Typen]: Lege fest, ob du GTIN, ISBN, UPC oder QR Barcodes brauchst.
* xref:artikel:barcodes.adoc#200[Erwerbe ggf. einen Pool an Barcodes]: Falls du Barcodes nicht direkt vom Hersteller erhältst, d.h. falls du eine Eigenmarke vertreibst, dann musst du Barcodes von einer Organisation wie GS1 erwerben.
* xref:artikel:barcodes.adoc#300[Ordne die Barcodes deinen Artikeln zu]: Verknüpfe deine Barcodes mit deinen Varianten.
* xref:artikel:barcodes.adoc#900[Gestalte die Artikel-Etiketten]: Entscheide, wie groß das Etikett sein soll und welche Informationen auf dem Etikett angezeigt werden sollen.
* xref:artikel:barcodes.adoc#1000[Drucke die Artikel-Etiketten aus]: Etiketten können für einen bestimmten Lagerort, eine bestimmte Variante oder für weitere Anwendungsfälle erzeugt und ausgedruckt werden.

[#100]
== Barcode-Typen konfigurieren

Welche Barcode-Typen benötigst du?
Auf welchen Verkaufsplattformen wirst du die einzelnen Barcode-Typen verwenden?
Speichere zunächst einige grundlegende Einstellungen für deine Barcodes.

. Öffne das Menü *Einrichtung » Artikel » Barcode*.
. Klicke auf icon:plus[role="darkGrey"]. +
→ Ein Pop-Up Fenster wird geöffnet. Dieses Fenster ist in mehrere Schritte unterteilt.
. Nimm die Einstellungen in jedem Schritt vor.

---

[discrete]
==== Schritt: Name

[cols="1,4a"]
|===
|Einstellung |Erläuterung

| *Name* +
[red]#(Pflichtfeld)#
|Gib einen Namen für den Barcode-Typ ein.
Der Name ist das Keyword oder die Phrase, die den Datensatz hervorhebt.

*_Tipp_*: Der Name darf Leerzeichen enthalten. Der Name kann also auch aus mehreren Wörtern bestehen.

| *Typ* +
[red]#(Pflichtfeld)#
|Wähle den Typ aus der Dropdown-Liste aus.

[cols="1,4"]
!===

!
*GTIN 8*; +
*GTIN 13*; +
*GTIN 14*; +
*GTIN 128*
! Global Trade Item Number (früher European Article Number, EAN) ist eine Produktkennzeichnung für Handelsartikel.
Die GTIN besteht aus 8, 13, 14 oder maximal 128 Ziffern, die zentral verwaltet und an Hersteller auf Antrag vergeben wird.

13-stellige GTINs setzen sich zusammen aus Basisnummer, Artikelnummer und Prüfziffer.
Die Basisnummer hat 7 bis 9 Stellen und besteht aus dem Länderpräfix der GS1-Mitgliedsgesellschaft, zum Beispiel 400 bis 440 für Deutschland, und der Unternehmensnummer.
Die Artikelnummer des Herstellers hat 3 bis 5 Stellen (je nach Länge der Basisnummer).
Die Prüfziffer nimmt die letzte Stelle ein.

! *ISBN*
! International Standard Book Number (Internationale Standardbuchnummer) ist eine eindeutige 10- oder 13-stellige Nummer zur Kennzeichnung von Büchern und anderen selbstständigen, nicht fortlaufenden Veröffentlichungen, zum Beispiel Multimedia-Produkten und Software.

! *QR*
! Quick Response Code.
Im Code sind Version, Datenformat und Informationen enthalten.

! *CODE 128*
! Alphanumerischer Strichcode.
Der Code128 setzt sich zusammen aus Startzeichen, Nutzinformation, Prüfziffer und Stoppzeichen.

! *UPC*
! Universal Product Code ist eine Produktkennzeichnung für Handelsartikel.
Der UPC ist eine 12-stellige Nummer.
Durch Voranstellung einer *0* kann die Zahlenkette als 13-stellige GTIN verwendet werden.

!===

*_Praxisbeispiel: FNSKU-Barcodes_*:
Auch wenn es für FNSKU keinen bestimmten Barcodetyp gibt, kannst du trotzdem FNSKU-Barcodes in plentysystems konfigurieren.
Gib einen aussagekräftigen Namen ein und wähle den gewünschten Typ, z.B. Code 128.

|===

---

[discrete]
==== Schritt: Verkaufskanäle

[cols="1,4a"]
|===
|Einstellung |Erläuterung

| *Barcode-Verkaufskanal*
|Auf welchen Verkaufsplattformen wirst du diesen Barcode-Typ verwenden?
Wähle alle passenden Verkaufskanäle (icon:check-square[role="blue"]).

|===

---

[discrete]
==== Schritt: Fertig

[cols="1,4"]
|===
|Einstellung |Erläuterung

| *Zusammenfassung*
a|Hier siehst du eine Zusammenfassung deiner gewählten Einstellungen.
Klicke auf *Barcode erstellen*, wenn du mit den Angaben einverstanden bist.

Nach der Erstellung hast du folgende Möglichkeiten:

[cols="1,4a"]
!===

! *Zum Barcode*
!Das Pop-up-Fenster wird geschlossen und der neu erstellte Barcode-Typ wird zur weiteren Bearbeitung geöffnet.

! *Weiteren Barcode erstellen*
!Das Pop-up-Fenster wird für den nächsten Barcode-Typ neu gestartet.

! *Schliessen*
!Das Pop-up-Fenster wird geschlossen.

!===

|===

[#200]
== Barcodes erwerben und Nummernkreis speichern

Hast du bereits GTINs (Barcodes) für deine Artikel?
Möglicherweise nicht, wenn du die Artikel direkt importierst und deine Hersteller keine GTINs vergeben.
In diesem Fall kannst du GTINs von einer Organisation wie link:https://www.gs1-germany.de/[GS1^] erwerben.
Beispielsweise kannst du ein Nummernkreis bestehend aus 1000 Barcodes kaufen.

Aber wie kriegst du diesen Pool an Barcodes in plentysystems rein?
Du musst sie nicht extra importieren.
Teile plentysystems einfach mit, wie viele GTINs du besitzt und mit welcher Nummer diese beginnen.
Wenn du dann xref:artikel:barcodes.adoc#300[einem Artikel einen Barcode zuweist], wird automatisch der nächste verfügbare Barcode verwendet.

[.instruction]
GTIN-Nummernkreis speichern:

. Öffne das Menü *Einrichtung » Artikel » GTIN*.
. Gib den Startwert ein. +
→ Bei 13-stelligen GTINs wird ein 12-stelliger Wert eingegeben.
Die Prüfziffer wird automatisch angehängt.
. Gib die Anzahl der GTINs ein.
. *Speichere* (terra:save[role="green"]) die Einstellungen.

[TIP]
.Warum sieht der Nummernkreis nicht fortlaufend aus?
====
Auf den ersten Blick sieht es vielleicht nicht so aus, als ob der Nummernkreis immer um 1 erhöht wird.
Aber vergesse nicht, dass die letzte Ziffer eine Prüfziffer ist.
Die 12 Stellen davor sind fortlaufend.
Lasse die Prüfziffer weg, wenn du den Startwert eingibst.
====

[#300]
== Barcodes zu Produkten zuordnen

Ein Barcode wird mit xref:artikel:struktur.adoc#[einer einzelnen Variante] verknüpft und nicht mit dem Artikel als Ganzes.
Wenn du zum Beispiel ein T-Shirt in den Farben Rot oder Blau verkaufst, dann haben das rote und das blaue T-Shirt jeweils einen eigenen Barcode.

Du hast verschiedene Möglichkeiten, deine Produkte mit Barcodes zu versehen:

[.collapseBox]
.*Manuell*
--

Wenn du nur wenige Produkte hast, dann ist es wahrscheinlich am schnellsten, die Barcodes manuell zu verknüpfen.

//neue Artikel-UI - Konfig unten löschen und dafür die include einblenden
//include::page$verzeichnis.adoc[tag=barcode-manually-link]

. Öffne das Menü *Artikel » Artikel bearbeiten » [Variante öffnen] » Tab: Einstellungen » Bereich: Barcode*.
. Wähle einen bereits konfigurierten Barcode-Typ aus der Dropdown-Liste.
. Klicke auf *Hinzufügen* (icon:plus[role="green"]). +
→ Der Barcode-Typ wird hinzugefügt und in der Liste angezeigt.
. Gib den Code in das Feld *Code* ein.
. *Speichere* (terra:save[role="green"]) die Einstellungen.

--

[.collapseBox]
.*Per Import*
--

Wenn du viele Produkte hast, dann ist es wahrscheinlich am schnellsten, die Barcodes zu importieren.

plentysystems verfügt über ein xref:daten:ElasticSync.adoc#[Import-Tool], mit dem du mehrere Barcodes gleichzeitig importieren kannst.
Die Idee ist ganz einfach.
Anstatt Barcodes manuell zu Artikeln zuzuordnen, trägst du die gleiche Informationen in eine CSV-Datei ein und importierst diese Datei dann in dein System.

* Anstatt den Barcode-Typ im Artikeldatensatz auszuwählen, xref:daten:elasticSync-artikel.adoc#1910[stellst du den Barcode-Typ als Abgleichfeld ein].
* Anstatt den Barcode manuell im Artikeldatensatz einzutragen, xref:daten:elasticSync-artikel.adoc#2320[trägst du den Barcode in ein Zuordnungsfeld ein].

--

[.collapseBox]
.*Automatisch aus dem Nummernkreis*
--

Hast du einen xref:artikel:barcodes.adoc#200[Nummernkreis bestehend aus GTIN 13 Barcodes] gekauft, dann kann plentysystems deinem Artikel automatisch den nächsten verfügbaren Barcode zuordnen.

//neue Artikel-UI - Konfig unten löschen und dafür die include einblenden
//include::page$verzeichnis.adoc[tag=barcode-automatic-link]

. Öffne das Menü *Artikel » Artikel bearbeiten » [Variante öffnen] » Tab: Einstellungen » Bereich: Barcode*.
. Wähle einen bereits konfigurierten GTIN 13 Barcode-Typ aus der Dropdown-Liste.
. Klicke auf *Hinzufügen* (icon:plus[role="green"]). +
→ Der Barcode-Typ wird hinzugefügt und in der Liste angezeigt.
. Klicke auf *GTIN generieren* (terra:execute[role="darkGrey"]), um automatisch den nächsten verfügbaren Barcode einzufügen.
. *Speichere* (terra:save[role="green"]) die Einstellungen.

//neue Artikel-UI - Tip einblenden und dafür den gleichen Tip weiter unten löschen
//TIP: Um GTINs für mehrere Varianten gleichzeitig zu generieren, nutze die xref:artikel:group-functions.adoc#300[Varianten-Gruppenfunktion].

TIP: Um GTINs für mehrere Varianten gleichzeitig zu generieren, nutze die xref:artikel:massenbearbeitung.adoc#300[Varianten-Gruppenfunktion] oder die xref:artikel:massenbearbeitung.adoc#600[Varianten-Stapelverarbeitung].

TIP: Diese Funktion ist nur für den Typ *GTIN 13* verfügbar. Bei allen anderen Typen ist die Schaltfläche deaktiviert.

--

[#700]
== Fehlerbehebung: Doppelte Barcodes

Es ist technisch möglich, den selben Barcode für mehrere Varianten zu speichern.
Wenn doppelte Barcodes nicht gewünscht sind, kannst du mehrmals vergebene Codes ermitteln und korrigieren.

[#730]
=== Duplikate ermitteln und korrigieren

. Öffne das Menü *Einrichtung » Artikel » Barcode*.
. Klicke auf den Bereich material:manage_search[role="darkGrey"] *Duplikate* in der linken Navigation. +
→ Es öffnet sich eine Liste aller doppelten Barcodes.
. Nutze die Filter (material:tune[role="darkGrey"]), um die Suchergebnisse bei Bedarf einzugrenzen.
. Klicke auf die ID der Variante, deren Code geändert werden soll. +
→ Die Variante wird geöffnet.
. Bearbeite den Code der Variante.
. *Speichere* (terra:save[role="darkGrey"]) die Änderung.

[#760]
=== Standard-Einstellungen anpassen

Wie genau soll die Prüfung für doppelte Barcodes sein?
Willst du doppelte Barcodes gänzlich unterbinden?
Du kannst die Einstellungen an die individuellen Bedürfnisse deines Unternehmens anpassen.

. Öffne das Menü *Einrichtung » Artikel » Einstellungen*.
. Wähle die Einstellungen für doppelte Barcodes. Beachte die folgende Tabelle.
. *Speichere* (terra:save[role="green"]) die Einstellungen.

[TIP]
.Die Prüfung wird nur über das Backend  vollzogen
====
Wie legst du die Barcodes an?
Über das Backend (Benutzeroberfläche), Import oder REST?
Die Prüfung für doppelte Barcodes wird nur über das Backend vollzogen.
Das Verknüpfen doppelter Barcodes kann per Import oder REST unabhängig von den Einstellungen erfolgen.
====

[cols="1,3a"]
|===
|Einstellung |Erläuterung

| *Genauigkeit doppelte Barcode-Prüfung*
|Wie genau soll die Suche sein?
Diese Einstellung bestimmt die Prüfgenauigkeit für doppelte Barcodes.

[cols="1,3"]
!===

! *Barcode Definition*
!Es wird pro numerischem Code geprüft.
Es wird also geprüft, ob ein bestimmter Code bereits bei einer bestimmten Definition hinterlegt ist.

*_Beispiel_*:
Wenn du den Barcode 1234 bei der Definition "GTIN 13_1" hinterlegt hast, dann könntest du den selben Code auch bei der Definition "GTIN 13_2" hinterlegen.

! *Barcode Typ*
!Es wird pro Barcode-Typ geprüft.
Zum Beispiel: doppelte Barcodes vom Typ GTIN.

! *Global*
!Es wird über alle Barcodes hinweg geprüft.

!===

| *Verhalten bei doppeltem Barcode*
|Wie soll plentysystems reagieren, wenn du versuchst, einen bereits vergebenen Barcode zu einem Produkt zuzuordnen?

[cols="1,3"]
!===

! *Zulassen*
!Es ist möglich, doppelte Barcodes zu speichern.

! *Warnen*
!Es ist möglich, doppelte Barcodes zu speichern.
Du siehst jedoch eine gelbe Warnmeldung, die dir mitteilt, dass der Barcode bereits für eine andere Variante hinterlegt ist.

! *Verhindern*
!Es ist nicht möglich, doppelte Barcodes zu speichern.
Du siehst eine rote Warnmeldung, die dir mitteilt, dass der Barcode nicht gespeichert wurde, da er bereits für eine andere Variante hinterlegt ist.

!===

|===

[#900]
== Etiketten gestalten

Artikeletiketten sind Hinweisschildchen auf einem Artikel oder der Artikelverpackung.
Sie enthalten Informationen wie Preis, Inhalt, Barcode etc.
Zuerst gestaltest du deine Etiketten mit Hilfe von Vorlagen.
Jede Vorlage enthält Informationen über die Größe des Etiketts, die Daten, die auf dem Etikett erscheinen sollen, und wo die einzelnen Daten auf dem Etikett positioniert werden sollen.
Du kannst bis zu 10 Etikettenvorlagen speichern.

. Öffne das Menü *Einrichtung » Artikel » Etiketten*.
. Klappe den Bereich *Neue Vorlage* auf (icon:plus-square-o[role="darkGrey"]).
. Passe die Einstellungen an deine Bedürfnisse an:
.. xref:artikel:barcodes.adoc#930[Gib Eckdaten und die Größe des Etiketts ein].
.. xref:artikel:barcodes.adoc#960[Entscheide, welche Daten auf dem Etikett erscheinen sollen].
.. xref:artikel:barcodes.adoc#980[Konfiguriere das Erscheinungsbild des Etiketts].
. *Speichere* (terra:save[role="green"]) die Einstellungen.

[#930]
=== Eckdaten und Größe des Etiketts

[cols="1,3a"]
|===
|Einstellung |Erläuterung

| *Name*
|Gib einen internen Namen für das Etikett ein.
Der Name ist für Kunden nicht sichtbar.
Wenn du mehrere Etikettenvorlagen erstellst, dann dient der Name zur Unterscheidung deiner Etiketten.

| *Sprache*
|In welcher Sprache soll das Etikett sein?
Wähle die passende Sprache aus der Dropdown-Liste aus.
Standardmäßig ist die Systemsprache voreingestellt.

| *Zeichensatz*
|Welchen Zeichensatz soll das Etikett verwenden?
Wähle den Zeichensatz aus der Dropdown-Liste aus.

| *Seite*
|Gib die Seitenbreite und -höhe in Millimeter ein.
Wenn du einen xref:automatisierung:drucker.adoc#50[Etikettendrucker] verwendest, dann können die Seitengröße und Etikettengröße identisch sein.

| *Seitenrand*
|Gib die Seitenränder links und oben in Millimeter ein.

| *Etikett*
|Gib die Breite und Höhe des Etiketts in Millimeter ein.
Die Größe des Etiketts muss zu den Werten der Seitengröße und der Zeilen- und Spaltenanzahl passen.

| *Zeilen pro Seite*
|Gib die Anzahl der Zeilen pro Seite ein.

| *Spalten pro Seite*
|Gib die Anzahl der Spalten pro Seite ein.
|===

[#960]
=== Welche Daten sollen auf dem Etikett erscheinen?

Gib mit Hilfe der X-Y-Koordinaten an, welche Informationen auf dem Etikett erscheinen sollen und wo jede Information positioniert werden soll.

* *_Welche Info_*:
Auf den Etiketten werden nur Werte ausgegeben, für die X- und Y-Koordinaten gespeichert wurden.
Gib also Koordinaten für jede Information ein, die auf dem Etikett erscheinen soll.

* *_Position der Info_*:
Gib Koordinaten ein, um Artikeldaten auf dem Etikett zu positionieren.
Die Werte orientieren sich am Koordinatensystem mit X- und Y-Achse.
Die X-Achse verläuft von links nach rechts und die Y-Achse von oben nach unten.
Nullwerte liegen also links und oben.

[cols="1s,3a"]
|===
|Einstellung |Erläuterung

|Sprache
|
. Gib X-Y-Koordinaten ein, um xref:artikel:barcodes.adoc#930[die ausgewählte Sprache] auf dem Etikett anzuzeigen.
. xref:artikel:barcodes.adoc#980[Konfiguriere das Erscheinungsbild].

|Artikel-ID; +
Varianten-ID; +
Varianten-Nr.; +
Variantenname; +
Externe Varianten-ID; +
Modell; +
Nummer der Hauptvariante
|
. Gib X-Y-Koordinaten ein, um die Artikeldaten auf dem Etikett anzuzeigen.
. xref:artikel:barcodes.adoc#980[Konfiguriere das Erscheinungsbild].

|Artikelname
|
. Gib X-Y-Koordinaten ein, um den Artikelnamen auf dem Etikett anzuzeigen.
. xref:artikel:barcodes.adoc#980[Konfiguriere das Erscheinungsbild].

[cols="1s,4"]
!===

!Name
!Wähle, ob du Name 1, 2 oder 3 als Artikelname verwenden willst.

!===

|Barcode; +
GTIN-Barcode; +
ISBN
|
. Gib X-Y-Koordinaten ein, um den Barcode auf dem Etikett anzuzeigen.
. xref:artikel:barcodes.adoc#980[Konfiguriere das Erscheinungsbild].

[cols="1s,4"]
!===

!GTIN darstellen
!Wähle diese Option (icon:check-square[role="blue"]), um die GTIN unter dem Barcode anzuzeigen.

!===

|1. Preis; +
2. Preis; +
Grundpreis
|
. Gib X-Y-Koordinaten ein, um den Preis/Grundpreis der Variante anzuzeigen.
. xref:artikel:barcodes.adoc#980[Konfiguriere das Erscheinungsbild].

[cols="1s,4"]
!===

!Preistyp
!Entscheide, ob der Verkaufspreis oder die UVP angezeigt werden soll. +
*_Hinweis_*: Wird der UVP gewählt, wird unabhängig vom gewählten Verkaufspreis immer der UVP der Variante ausgegeben.

!Verkaufspreis
!Entscheide, welcher Verkaufspreis angezeigt werden soll. +
*_Hinweis_*: Ist als Preistyp *Verkaufspreis* eingestellt, wird der Betrag dieses Preises nur dann von der Variante gezogen, wenn in der Auftragsposition kein Preis hinterlegt ist; ansonsten wird der Preis aus der Auftragsposition genommen. +
Dieser Hinweis gilt nur dann, wenn die Etiketten zu einem Auftrag erzeugt werden. Etiketten können in diesem Fall aus dem Auftrag heraus oder aus der Vorschau erzeugt werden.

!===

*_Hinweis_*: Wenn du den Preis und Grundpreis angezeigen willst, dann stelle sicher, dass für beide Optionen derselbe Preistyp und/oder Verkaufspreis ausgewählt wird.

|Attribute
|
. Gib X-Y-Koordinaten ein, um den Attributnamen und Attributwert der Variante anzuzeigen.
. xref:artikel:barcodes.adoc#980[Konfiguriere das Erscheinungsbild].

[cols="1s,4"]
!===

!Attributnamen ausblenden
!Wähle diese Option (icon:check-square[role="blue"]), um nur den Attributwert anzuzeigen. Der Attributname wird ausgeblendet.

!===

|Lagerort
|
. Gib X-Y-Koordinaten ein, um den xref:warenwirtschaft:variations-track-stock.adoc#300[vorgeschlagenen Lagerort der Variante] auf dem Etikett anzuzeigen.
. xref:artikel:barcodes.adoc#980[Konfiguriere das Erscheinungsbild].

|Bestand; +
Einheit; +
Währung
|
. Gib X-Y-Koordinaten ein, um die Artikeldaten auf dem Etikett anzuzeigen.
. xref:artikel:barcodes.adoc#980[Konfiguriere das Erscheinungsbild].

|Artikelbild
|Gib X-Y-Koordinaten ein, um das Artikelbild auf dem Etikett anzuzeigen.

[cols="1s,4"]
!===

!Höhe/Breite (mm)
!Gib Maximalwerte für die Höhe und Breite des Bildes ein.
Wenn das Bild größer als die eingegebenen Werte ist, wird das Bild proportional eingepasst, damit das Bild nicht verzerrt angezeigt wird.

!Artikelbild-Position
!Viele Artikel haben mehr als nur ein Bild.
Indem du hier eine Positionsnummer wählst, gibst du an, welches Artikelbild auf dem Etikett angezeigt werden soll.

Standardmäßig ist *Position 0* voreingestellt.
Die Artikelbildpositionen werden im Tab *Bilder* eines Artikels festgelegt.
Wenn eine Position gewählt wurde, zu der kein Bild verfügbar ist, wird das erste verfügbare Bild, mit Position 0 beginnend, verwendet.

!===

|Artikel-Freitextfeld 1 bis 4
|
. Gib X-Y-Koordinaten ein, um das Freitextfeld auf dem Etikett anzuzeigen.
. xref:artikel:barcodes.adoc#980[Konfiguriere das Erscheinungsbild].

[cols="1s,4"]
!===

!Freitextfeld
!Wähle das xref:artikel:artikel-verwalten.adoc#70[Freitextfeld], dessen Text auf dem Etikett angezeigt werden soll.

!===

|Freitextfeld 1 bis 4
|
. Gib X-Y-Koordinaten ein, um das Freitextfeld auf dem Etikett anzuzeigen.
. xref:artikel:barcodes.adoc#980[Konfiguriere das Erscheinungsbild].

[cols="1s,4"]
!===

!Eingabefeld
!In diesem Bereich kannst du zusätzliche Freitextfelder einrichten.
Gib Text in das Eingabefeld ein.
Der eingegebene Text wird auf dem Etikett angezeigt.

!===

|Grafik
|Gib X-Y-Koordinaten ein, um eine Grafik auf dem Etikett anzuzeigen.

[cols="1s,4a"]
!===

!Höhe/Breite (mm)
!Gib Maximalwerte für die Höhe und Breite des Bildes ein.
Wenn das Bild größer als die eingegebenen Werte ist, wird das Bild proportional eingepasst, damit das Bild nicht verzerrt angezeigt wird.

!URL
!
. Lade deine Grafiken im Menü *CMS » Webspace* hoch.
. Kopiere die URL der Grafik aus dem Webspace.
. Füge die URL in dieses Feld ein.

!===

2+^s|Auftragsbezogene Daten

|Auftrags-ID; +
Externe Auftrags-ID; +
Artikelanzahl
|
. Gib X-Y-Koordinaten ein, um die auftragsbezogene Parameter auf dem Etikett anzuzeigen.
. xref:artikel:barcodes.adoc#980[Konfiguriere das Erscheinungsbild].

|Lieferland
|
. Gib X-Y-Koordinaten ein, um das Lieferland auf dem Etikett anzuzeigen.
. xref:artikel:barcodes.adoc#980[Konfiguriere das Erscheinungsbild].

[cols="1s,4"]
!===

!Darstellung
!Entscheide, ob der Name oder ISO-Code des Landes auf dem Etikett angezeigt werden soll.

!===

|===

[#980]
=== Erscheinungsbild des Etiketts

[cols="1s,3a"]
|===
|Einstellung |Erläuterung

|X/Y
|Gib mit Hilfe der X-Y-Koordinaten an, welche Informationen auf dem Etikett erscheinen sollen und wo jede Information positioniert werden soll.

* *_Welche Info_*:
Auf den Etiketten werden nur Werte ausgegeben, für die X- und Y-Koordinaten gespeichert wurden.
Gib also Koordinaten für jede Information ein, die auf dem Etikett erscheinen soll.

* *_Position der Info_*:
Gib Koordinaten ein, um Artikeldaten auf dem Etikett zu positionieren.
Die Werte orientieren sich am Koordinatensystem mit X- und Y-Achse.
Die X-Achse verläuft von links nach rechts und die Y-Achse von oben nach unten.
Nullwerte liegen also links und oben.

|5px
|Sollen die Artikeldaten eher klein oder groß dargestellt werden?
Wähle die passende Schriftgröße aus der Dropdown-Liste aus.

|Normal
|Sollen die Artikeldaten in normaler oder fetter Schrift dargestellt werden?
Wähle den passenden Schriftschnitt aus der Dropdown-Liste aus.

|Titel verbergen
|Der Titel des Artikelparameters wird standardmäßig auf dem Etikett angezeigt.
Wähle diese Option (icon:check-square[role="blue"]), wenn der Titel nicht angezeigt werden soll.

|Zeilenumbruch erlauben
|Wähle diese Option (icon:check-square[role="blue"]), wenn der Text in die nächste Zeile umbrechen soll, wenn er die Breite des Etiketts überschreitet.

|===

[TIP]
.Testseite drucken
====
Je nach Drucker weichen einige Ausdrucke auch bei einer korrekt eingerichteten Vorlage von den Einstellungen ab. Drucke daher beim Einrichten der Vorlage Probedrucke auf Normalpapier. Korrigiere die Positionen, bis du mit dem Ergebnis zufrieden bist, bevor du Etikettenpapier verwendest.
====

[#1000]
== Etiketten erzeugen und drucken

Du hast verschiedene Möglichkeiten, Etiketten zu erzeugen und auszudrucken.

[.collapseBox]
.*Etiketten manuell für einen Lagerort generieren*
--

Gehe wie folgt vor, um Etiketten manuell für einen bestimmten Lagerort zu generieren und auszudrucken:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. xref:artikel:suche.adoc#400[Suche] und öffne die Variante.
. Klicke auf den Tab *Lager*.
. Stelle sicher, dass du im Feld *Lagerortvorschlag* einen Lagerort ausgewählt hast.
Wurde kein Lagerort für eine Variante gewählt, wird der Standard-Lagerort stattdessen automatisch als Platzhalter-Lagerort verwendet.
. Klicke auf das Etikettensymbol (icon:barcode[role="blue"]) weiter rechts. +
→ Das Fenster *Etiketten generieren* wird geöffnet.
. Gib ein, wie viele Etiketten generiert werden sollen.
. Wähle die Etikettenvorlage aus der Dropdown-Liste.
. Klicke auf terra:execute[role="darkGrey"] *Etiketten generieren*. +
→ Eine PDF-Datei mit der gewählten Anzahl der Etiketten wird generiert.

TIP: Wird auf deinen Etiketten immer nur den Standard-Lagerort angezeigt? +
 +
*_Tipp 1_*: Möglicherweise hast du keinen Lagerort-Vorschlag für die Variante gespeichert.
Öffne die Variante und klicke auf den Tab *Lager*.
Stelle sicher, dass du im Feld *Lagerortvorschlag* einen Lagerort ausgewählt hast.
Wurde kein Lagerort für eine Variante gewählt, wird der Standard-Lagerort stattdessen automatisch als Platzhalter-Lagerort verwendet. +
 +
*_Tipp 2_*: Möglicherweise hast du auf das falsche Etikettensymbol geklickt.
Klicke auf das Etikettensymbol icon:barcode[role="blue"] weiter rechts im Tab *Lager*.
Klickst du stattdessen auf das Etikettensymbol in der obere Artikel-Symbolleiste, wird der Standard-Lagerort auf deinem Etikett fälschlicherweise angezeigt.
Denk daran, dass jede Variante an einem anderen Ort gelagert werden kann.
Mit anderen Worten, kann ein Artikel mehrere Lagerorte haben.
Wenn du also ein Etikett für den gesamten Artikel generierst, weiß plentysystems nicht, welcher Lagerort vorgesehen ist, und verwendet stattdessen den Standard-Lagerort.

--

[.collapseBox]
.*Etiketten manuell für eine Variante generieren*
--

Gehe wie folgt vor, um Etiketten manuell für eine bestimmte Variante zu generieren und auszudrucken:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. xref:artikel:suche.adoc#400[Suche] und öffne die Variante.
. Klicke in der untere Symbolleiste auf das Etikettensymbol (icon:barcode[role="blue"]). +
→ Das Fenster *Etiketten generieren* wird geöffnet.
. Gib ein, wie viele Etiketten generiert werden sollen.
. Wähle die Etikettenvorlage aus der Dropdown-Liste.
. Klicke auf *Etiketten generieren* (terra:execute[role="darkGrey"]). +
→ Eine PDF-Datei mit der gewählten Anzahl der Etiketten wird generiert.


TIP: Es ist auch möglich, Etiketten für alle Varianten eines Artikels zu generieren.
Klicke dazu in der obere Symbolleiste auf das Etikettensymbol icon:barcode[role="blue"].

--

[.collapseBox]
.*Etiketten manuell für alle Artikel eines Auftrags generieren*
--

Sobald du eine xref:artikel:barcodes.adoc#900[Etikettenvorlage] fertig erstellt hast, wird eine weitere Option eingeblendet.
Verwende diese Option, um Etiketten für alle Artikel eines bestimmten Auftrags manuell zu generieren.

. Öffne das Menü *Einrichtung » Artikel » Etiketten*.
. Klappe eine existierende Vorlage auf (icon:plus-square-o[role="darkGrey"]).
. Gib die Auftrags-ID ein.
. Klicke auf *Vorschau* (icon:eye[role="blue"]). +
→ Eine PDF-Datei mit Etiketten für die im Auftrag enthaltenen Artikel wird generiert.

--

[.collapseBox]
.*Etiketten aus der plentyWarehouse App drucken*
--

Benutzt du die plentyWarehouse App?
Dann kannst du mit deinem mobilen Gerät nach Artikeln suchen und Etiketten ausdrucken.

xref:warenwirtschaft:etiketten-drucken.adoc#[Weitere Informationen].

--

[.collapseBox]
.*Etiketten beim Wareneingang automatisch drucken*
--

Möchtest du Etiketten beim Wareneingang automatisch ausdrucken?
Dann erstelle xref:automatisierung:prozesse-einrichten.adoc#[einen plentysystems-Prozess] und füge xref:automatisierung:aktionen.adoc#150[die Aktion Artikeletikett] hinzu.

--
