= Einheiten
:keywords: Einheit, Einheiten, Maßeinheit, Maßeinheiten, Größe, Maße, Länge, Breite, ISO-Code, ISO, Dezimalzahlen, Inhalt, Grundpreis, Preis pro, Stück, Kilogramm, Gramm, Milligramm, Liter
:description: Standardmäßig sind 52 Einheiten in plentymarkets gespeichert. Lerne, wie du weitere Maßeinheiten bei Bedarf erstellst.
:id: IHTSF1W
:author: team-item

////
zuletzt bearbeitet 18.10.2021
////

Einheiten wie Kilogramm, Liter und Zentimeter helfen dir, die Größe oder Maße deiner Produkte zu definieren.
Standardmäßig sind 52 Einheiten nach ISO-Code in plentymarkets gespeichert.
Du kannst jedoch xref:artikel:einheiten.adoc#100[weitere Maßeinheiten bei Bedarf erstellen] oder die bestehenden Einheiten anpassen.

Darüber hinaus kannst du:

* den xref:artikel:einheiten.adoc#150[Inhalt] deiner Varianten angeben, z.B. 1 Stück, 500 Gramm, 2,4 Liter, usw.
* Einheiten mit unterschiedlichen Mengen kombinieren und somit xref:artikel:einheiten.adoc#200[Varianten erzeugen].
Beispielsweise verkaufst du eine Flasche Seife, die in 50ml, 100ml oder 150ml erhältlich ist.
* den xref:artikel:einheiten.adoc#300[Grundpreis] deiner Varianten angeben, d.h. die Kosten pro Pfund, Liter oder einer anderen Maßeinheit.

[#100]
== Neue Einheiten erstellen und bestehende anpassen

Standardmäßig sind 52 Einheiten nach ISO-Code in plentymarkets gespeichert.
Wirf dir einen Blick auf die bereits vorhandenen Einheiten.
Erstelle bei Bedarf weitere Einheiten oder passe die bestehende Einheiten an.

[tabs]
====
Neue Einheit erstellen::
+
--

. Öffne das Menü *Einrichtung » Artikel » Einheiten*.
. Klicke auf icon:plus[role="green"] *Neu*. +
→ Das Fenster *Neue Einheit anlegen* wird geöffnet.
. Gib einen Namen für die Einheit ein.
Wähle einen geeigneten Namen, da der Text für Kunden im Webshop sichtbar ist.
. Gib optional eine Positionsnummer ein.
Wenn du keine Nummer eingibst, wird automatisch die Positionsnummer 0 vergeben.
. Klicke auf icon:save[set=plenty, role="green"] *Speichern*. +
→ Die neue Einheit wird erstellt und öffnet sich automatisch in einem neuen Tab.
. Passe die Einstellungen bei Bedarf weiter an.

--
Bestehende Einheiten anpassen::
+
--

. Öffne das Menü *Einrichtung » Artikel » Einheiten*.
. Klicke auf eine Einheit. +
→ Die Einheit öffnet sich in einem neuen Tab.
. Passe die Einstellungen bei Bedarf an.
. *Speichere* (icon:save[set=plenty, role="green"]) die Einstellungen.

--
====

[cols="1,3"]
|===
|Einstellung |Erläuterung

| *Position*
|Gib eine Positionsnummer für die Einheit ein.
Die Einheiten werden im Backend nach ihrer Positionsnummer sortiert dargestellt.

*_Hinweis_*: Hast du beim Anlegen der Einheit keine Positionsnummer eingegeben, wird automatisch die Positionsnummer 0 vergeben.

| *Maßeinheit (ISO)*
|Wähle eine Maßeinheit anhand des ISO-Codes.

*_Hinweis_*: Du kannst nur aus den vorhandenen ISO-Codes wählen.
Die ISO-Codes selber lassen sich nicht manuell erweitern.

| *Dezimalzahlen*
|Sind Dezimalzahlen für diese Maßeinheit zulässig?
Zum Beispiel macht ein halber Liter Sinn.
Aber ein halber Kanister wäre dagegen nicht sinnvoll.

| *Sprache*
|Inhalt und Einheit der Variante werden im Webshop angezeigt, z.B. 1 Stück, 500 Gramm, 2,4 Liter, usw.
Gib daher einen geeigneten Namen für die Einheit in allen von dir verwendeten Sprachen ein.
|===

[#150]
== Inhalt deiner Varianten angeben

[tabs]
====
Manuell::
+
--

Wenn du den Inhalt für nur wenige Varianten angeben möchtest, dann empfiehlt es sich, dies manuell zu tun.

. Öffne das Menü *Artikel » Artikel bearbeiten » [Variante öffnen] » Tab: Einstellungen » Bereich: Maße » Option: Inhalt*.
. Gib eine Zahl in das linke Feld ein.
. Wähle eine Einheit aus der rechten Dropdown-Liste aus.
. *Speichere* (icon:save[set=plenty, role="green"]) die Einstellungen.

--
Import::
+
--

Wenn du den Inhalt für viele Varianten angeben möchtest, dann empfiehlt es sich, dies xref:daten:ElasticSync.adoc#[per Import] zu tun.

. Erstelle einen xref:daten:elasticSync-artikel.adoc#[Import vom Typ Artikel].
. Verwende den Zuordnungsfeldern:
.. xref:daten:elasticSync-artikel.adoc#1810[Inhalt Menge] und xref:daten:elasticSync-artikel.adoc#1800[Inhalt Einheit]. +
+
oder
.. xref:daten:elasticSync-artikel.adoc#1810[Inhalt Menge] und xref:daten:elasticSync-artikel.adoc#1820[Inhalt Maßeinheit (ISO)].

--
====

[#200]
== Einheiten kombinieren und Varianten erzeugen

Einheiten kannst du mit unterschiedlichen Mengen kombinieren und somit Varianten erzeugen. Beispielsweise verkaufst du eine Flasche Seife, die in 50ml, 100ml oder 150ml erhältlich ist.

xref:artikel:neue-artikel.adoc#200[Beim Erstellen eines Artikels] kannst du die Einheit und den Inhalt des Artikels direkt eingeben. Wenn du xref:artikel:neue-artikel.adoc#400[zusätzliche Varianten erstellst], kannst du auch die Einheit und den Inhalt jeder Variante eingeben.

[#300]
== Grundpreis auf Vertriebskanälen und Etiketten anzeigen

Sicherlich hast du schon den Grundpreis gesehen, der in den Regalen der Lebensmittelgeschäfte aufgeführt ist.
Der Grundpreis gibt die Kosten pro Pfund, Liter oder andere Maßeinheit an.

Berechnet wird er auf Grundlage von xref:artikel:artikel-verwalten.adoc#270[Einheit, Inhalt] und xref:artikel:artikel-verwalten.adoc#240[Preis] des Artikels.
Dargestellt werden kann er xref:artikel:artikel-verwalten.adoc#270[im plentyShop], auf Vertriebskanälen wie xref:maerkte:varianten-vorbereiten.adoc#860[Amazon], xref:maerkte:ebay-einrichten.adoc#4000[eBay], xref:maerkte:otto-market.adoc#1302[OTTO] oder xref:maerkte:plus-gartenxxl.adoc#365[Netto] und xref:artikel:barcodes.adoc#900[auf Artikeletiketten].
