= Export
:keywords: Artikeldaten exportieren, Artikel exportieren, Exportieren Artikel, Artikel Export, Artikel-Export, Export Artikel, Artikelexport, Variant exportieren, Variante exportieren, Varianten exportieren, Exportieren Variant, Exportieren Variante, Exportieren Varianten, Variant Export, Variante Export, Varianten Export, Variant-Export, Variante-Export, Varianten-Export, Export Variant, Export Variante, Export Varianten, Variantexport, Varianteexport, Variantenexport, Produkt exportieren, Produkte exportieren, Ware exportieren, Waren exportieren
:description: Auf dieser Seite werden einige Tools zum Exportieren von Artikel- und Variantendaten vorgestellt.
:author: team-item

Es gibt viele Gründe, Artikel- und Variantendaten zu exportieren.
Zum Beispiel, vielleicht willst du:

* deine Artikel- und Variantendaten an Marktplätze übertragen.
* eine mit Produktdaten gefüllte CSV-Datei exportieren. Dann die Datei überarbeiten und wieder importieren.

Diese Seite stellt die Tools dafür kurz vor. Klicke auf die Links, um ausführlichere Informationen über die Tools zu lesen.


[discrete]
=== Kataloge

Verwende xref:daten:marktplatzexport.adoc#[Kataloge], um den Export von Variantendaten an Marktplätze und andere Verkaufskanäle durchzuführen. Aktuell kannst du Kataloge nutzen, um Daten an die Marktplätze REWE, Etsy, Metro, OTTO Market und Amazon zu übertragen.

Kataloge dienen dazu, Variantendaten für den Export an einen Verkaufskanal vorzubereiten.


[discrete]
=== Elastischer Export

Willst du eine mit Produktdaten gefüllte CSV-Datei exportieren? Danach kannst du z.B. die Datei überarbeiten und wieder importieren.
Die Artikeldaten werden in zwei Schritten exportiert:

Verwende zuerst den xref:daten:FormatDesigner.adoc#[FormatDesigner], um sogenannte Datenformate zu erstellen. Mit anderen Worten entscheidest du, welche Daten exportiert werden sollen.

In einem zweiten Schritt verwendest du dann den xref:daten:elastischer-export.adoc#[Elastischen Export], um die soeben erstellten Datenformate zu exportieren.
