= Massenbearbeitung
:keywords: Massenbearbeitung, Massenverarbeitung, Stapelbearbeitung, Stapelverarbeitung, Gruppen-Funktion, Gruppen-Funktionen, Gruppenfunktion, Gruppenfunktionen, Group function, Batch process, Batch processing, Artikel gleichzeitig bearbeiten, Artikel gleichzeitig verarbeiten, Batch-Verarbeitung, Batchverarbeitung, Suchen & Ersetzen, Suchen und ersetzen, Kopieren, Artikel kopieren
:description: plentymarkets beinhaltet verschiedene Funktionen zur Massenverarbeitung. Lerne, wie du mehrere Artikel oder Varianten gleichzeitig bearbeitest.
:id: S71L7WQ
:author: team-item

////
zuletzt bearbeitet 14.07.2022
////

Dein Business läuft und du hast bereits ein solides Produktportfolio aufgebaut.
Aber wie gehst du am besten mit den Produktdaten im Arbeitsalltag um?
plentymarkets beinhaltet verschiedene Funktionen zur Massenverarbeitung.

[cols="1,5a"]
|===

|xref:artikel:group-functions.adoc#100[Gruppenfunktion]
|Nutze die Gruppenfunktion, um mehrere Artikel oder Varianten gleichzeitig zu bearbieten.

*_Beispiele_*:

* du willst die Artikel auswählen, die in einem Sonderverkauf angeboten werden sollen.
* du willst den Preis aller Varianten eines bestimmten Herstellers erhöhen.

|xref:artikel:group-functions.adoc#650[Import & Export]
|Nutze den Import & Export, um mehrere Artikel oder Varianten gleichzeitig in einer CSV-Datei zu bearbeiten.

*_Ablauf_*:

. Exportiere eine CSV-Datei, die mit Produktdaten gefüllt ist.
. Überarbeite die Datei und importiere sie wieder.

|xref:artikel:group-functions.adoc#700[Suchen & Ersetzen]
|Stell dir vor, du hast gerade erfahren, dass dein Hersteller ein Zubehörteil umbenannt hat.
Jetzt ist es an dir, den Namen in allen Artikeltexten zu ändern.
Verwende die Suchen & Ersetzen-Funktion, um ein Wort oder eine Formulierung global in allen Artikeltexten anzupassen.

|xref:artikel:group-functions.adoc#800[Kopieren]
|Stell dir vor, du willst einen neuen Artikel zu deinem Sortiment hinzufügen.
Er ist einem bestehenden Produkt recht ähnlich.
Kopiere in diesem Fall das bestehende Produkt.
Ändere danach die abweichenden Einstellungen für den neuen Artikel.
|===

[#100]
== Gruppenfunktionen

Nutze die Gruppenfunktion, um mehrere Artikel oder Varianten gleichzeitig zu bearbeiten.
Wähle dabei die zu bearbeitenden Artikel oder Varianten direkt aus.
Mit der Gruppenfunktion kannst du, zum Beispiel:

* die Artikel auswählen, die in einem Sonderverkauf angeboten werden sollen.
* den Preis aller Artikel eines bestimmten Herstellers erhöhen.

[#200]
=== Artikel-Gruppenfunktion

. Öffne das Menü *Artikel » Artikel-UI*.
. xref:artikel:artikelsuche.adoc#100[Setze Suchfilter bei Bedarf und starte die Suche].
. Wähle (icon:check-square[role="blue"]) die zu bearbeitenden Artikel aus.
. Klicke in der Symbolleiste auf material:layers[role="darkGrey"] *»* material:layers[role="darkGrey"] *Artikel-Gruppenfunktion*. +
→ Das Fenster *Artikel-Gruppenfunktion* wird geöffnet.
. Welche Einstellungen möchtest du ändern?
Wähle (icon:check-square[role="blue"]) die entsprechenden Aktionen aus der Dropdown-Liste aus. +
→ Die Aktionen werden zum unteren Teil des Fensters hinzugefügt.
. Konfiguriere die Einstellungen im unteren Teil des Fensters.
. Führe die Gruppenfunktion aus.

#GIF#

[cols="1,3"]
|===
| Aktion | Erläuterung

2+| *Artikelbilder*

| *Artikelbilder löschen*
|Wähle diese Option (icon:check-square[role="blue"]), um alle Artikelbilder der gewählten Artikel zu löschen.

| *Zweites Artikelbild löschen*
|Wähle diese Option (icon:check-square[role="blue"]), um das zweite Artikelbild der gewählten Artikel zu löschen.

2+| *Artikeleinstellungen*

| *Erlöskonto*
|Gib bis zu 11 Ziffern für das xref:auftraege:buchhaltung.adoc#800[Erlöskonto] ein.

| *Hersteller*
|Wer stellt die gewählten Artikel her?
Wähle den passenden xref:artikel:hersteller.adoc#[Hersteller] aus der Dropdown-Liste.

| *Herstellungsland*
|In welchem Land wurden die gewählten Artikel hergestellt?
Wähle das passende Herstellungsland aus der Dropdown-Liste.

| *Markierung 1*; +
*Markierung 2*
|Weist mehreren Artikeln gleichzeitig eine oder zwei Markierungen zu.

| *Seriennummer*
|Diese Option ist nur für Artikel mit Seriennummern relevant.
Mit dieser Option xref:artikel:seriennummern.adoc#900[ermöglichst du das Scannen] für mehrere Artikel gleichzeitig.

| *Set Preis aktualisieren*
|Diese Option ist nur für xref:artikel:multipacks-pakete-sets.adoc#3900[Artikelsets] relevant. Mit dieser Option kannst du den sogenannten "Ab-Preis" für mehrere Artikel gleichzeitig aktualisieren.

| *Shop-Aktion*
|Sollen die ausgewählten Artikel mit einer xref:artikel:shop-aktionen.adoc#[Shop-Aktion] hervorgehoben werden?
Falls ja, dann gib hier an, ob du die Artikel als Sonderangebot, Neuheit oder Top-Artikel kennzeichnen willst.

| *Zustand*
|Wie ist der Zustand der gewählten Artikel?
Wähle den passenden Zustand aus der Dropdown-Liste.

2+| *Marktplatzspezifische Artikeleinstellungen*

| *Amazon FBA*
|Sollen die gewählten Artikel über FBA vermarktet werden?

include::maerkte:partial$amz-variantenverfuegbarkeit.adoc[tag=amazon-fba-note]

icon:toggle-on[role="blue"] = Ja, der Artikel wird über FBA vermarktet. +
icon:toggle-off[role="darkGrey"] = Nein, der Artikel wird nicht über FBA vermarktet.

| *Amazon-Produkttyp*
|
include::maerkte:partial$amz-variantenverfuegbarkeit.adoc[tag=produkttyp]
include::maerkte:partial$amz-variantenverfuegbarkeit.adoc[tag=produkttyp-export]

include::maerkte:partial$amz-variantenverfuegbarkeit.adoc[tag=produkttyp-note]

| *Artikel-Zeitstempel für Marktplatzexporte aktualisieren*
|Setzt den Zeitstempel *Letzte Änderung* auf das aktuelle Datum und die aktuelle Uhrzeit.

*_Hintergrund_*: Manchmal ist es notwendig, den Zeitstempel zu aktualisieren, z.B. xref:maerkte:best-practices-amazon-artikeldatenexport.adoc#200[wenn du die Artikel bei Amazon verkaufen willst].
Der Grund dafür ist, dass Artikel nur dann nach Amazon exportiert werden, wenn sie innerhalb der letzten 24 Stunden bearbeitet wurden.

| *FBA-Abwicklung*
|
include::maerkte:partial$amz-variantenverfuegbarkeit.adoc[tag=fba-abwicklung]

| *Listing anlegen*
|Wähle diese Option (icon:check-square[role="blue"]), um für die gewählten Artikel Listings auf eBay, Hood oder Ricardo zu erstellen.

*_Zusätzliche Einstellungen_*: Hast du eine xref:artikel:artikel-verwalten.adoc#_listing_voreinstellungen[Listing-Vorlage am Artikel hinterlegt]?
Die Listing-Vorlage bestimmt z.B., ob die Listings für eBay, Hood oder Ricardo gelten.
Hat der Artikel keine Listing-Vorlage, wird standardmäßig versucht, ein eBay-Angebot zu erstellen, da dies der häufigste Fall ist.

**__Beispiel__**: Stell dir vor, du möchtest ein Hood-Listing anlegen. In diesem Fall musst du eine Listing-Vorlage am Artikel hinterlegen.
plentymarkets weiß, dass es Hood Listings erstellen soll, weil das Hood-Konto in der Vorlage gespeichert ist.

| *Listing-Vorlage*
|Wähle eine xref:maerkte:ebay-einrichten.adoc#5500[bereits erstellte Listing-Vorlage], um sie mit den gewählten Artikeln zu verknüpfen.

2+| *Versandprofile*

| *Aktuelle Versandprofile löschen*
|Wähle diese Option (icon:check-square[role="blue"]), wenn du vorhandene xref:fulfillment:versand-vorbereiten.adoc#1000[Versandprofile] aus dem Artikel entfernen möchtest.

*_Hinweis_*:
Die Versandprofile selbst werden nicht gelöscht. Sie werden lediglich aus dem Artikel entfernt.

| *Versandprofile*
|Wie werden die gewählten Artikel versandt?
Wähle alle passenden xref:fulfillment:versand-vorbereiten.adoc#1000[Versandprofile] aus der Dropdown-Liste (icon:check-square[role="blue"]).

*_Hinweis_*:
Nutze diese Aktion zusammen mit der Aktion *Aktuelle Versandprofile löschen*, wenn die neuen Versandprofile die vorhandenen ersetzen sollen.
Das heißt, wenn die vorhandenen Versandprofile zuerst aus dem Artikeldatensatz entfernt werden sollen.

|===

[#300]
=== Varianten-Gruppenfunktion

. Öffne das Menü *Artikel » Artikel-UI*.
. xref:artikel:artikelsuche.adoc#100[Setze Suchfilter bei Bedarf und starte die Suche].
. Wähle (icon:check-square[role="blue"]) die zu bearbeitenden Varianten aus.
. Klicke in der Symbolleiste auf material:layers[role="darkGrey"] *»* material:layers[role="darkGrey"] *Varianten-Gruppenfunktion*. +
→ Das Fenster *Varianten-Gruppenfunktion* wird geöffnet.
. Welche Einstellungen möchtest du ändern?
Wähle (icon:check-square[role="blue"]) die entsprechenden Aktionen aus der Dropdown-Liste aus. +
→ Die Aktionen werden zum unteren Teil des Fensters hinzugefügt.
. Konfiguriere die Einstellungen im unteren Teil des Fensters.
. Führe die Gruppenfunktion aus.

#GIF#

[cols="1,3"]
|===
| Aktion | Erläuterung

2+| *Lager und Versand*

| *Hauptlager*
|

| *Lagereinstellungen*
|

| *Portoaufschlag 1*; +
*Portoaufschlag 2*
|

2+| *Paketeinstellungen*

| *Paket: Bruttogewicht automatisch aus Bestandteilen berechnen*
|Soll das Butto-Gewicht automatisch anhand der Paket-Bestandteile berechnet werden?

icon:toggle-on[role="blue"] = Aktiviert die Paketautomatik. +
icon:toggle-off[role="darkGrey"] = Deaktiviert die Paketautomatik.

*_Hinweis_*:
Diese Einstellung ist nur für xref:artikel:multipacks-pakete-sets.adoc#2500[Artikelpakete] relevant.

| *Paket: Gleitenden Nettoeinkaufspreis automatisch aus Bestandteilen berechnen*
|Soll der gleitende Netto-Einkaufspreis automatisch anhand der Paket-Bestandteile berechnet werden?

icon:toggle-on[role="blue"] = Aktiviert die Paketautomatik. +
icon:toggle-off[role="darkGrey"] = Deaktiviert die Paketautomatik.

*_Hinweis_*:
Diese Einstellung ist nur für xref:artikel:multipacks-pakete-sets.adoc#2500[Artikelpakete] relevant.

| *Paket: Nettoeinkaufspreis automatisch aus Bestandteilen berechnen*
|Soll der Netto-Einkaufspreis automatisch anhand der Paket-Bestandteile berechnet werden?

icon:toggle-on[role="blue"] = Aktiviert die Paketautomatik. +
icon:toggle-off[role="darkGrey"] = Deaktiviert die Paketautomatik.

*_Hinweis_*:
Diese Einstellung ist nur für xref:artikel:multipacks-pakete-sets.adoc#2500[Artikelpakete] relevant.

| *Paket: Nettogewicht automatisch aus Bestandteilen berechnen*
|Soll das Netto-Gewicht automatisch anhand der Paket-Bestandteile berechnet werden?

icon:toggle-on[role="blue"] = Aktiviert die Paketautomatik. +
icon:toggle-off[role="darkGrey"] = Deaktiviert die Paketautomatik.

*_Hinweis_*:
Diese Einstellung ist nur für xref:artikel:multipacks-pakete-sets.adoc#2500[Artikelpakete] relevant.

2+| *Tags*

| *Alle Tags entfernen*
|Wähle diese Option (icon:toggle-on[role="blue"]), wenn du _alle vorhandenen_ xref:artikel:markierungen.adoc#400[Tags] aus der Variante entfernen möchtest.

*_Hinweis_*:
Die Tags selbst werden nicht gelöscht.
Sie werden lediglich aus der Variante entfernt.

| *Tags entfernen*
|Willst du _ein paar bestimmte_ xref:artikel:markierungen.adoc#400[Tags] aus der Variante entfernen?
Klicke in das Feld und wähle die Tags, die von der Variante entfernt werden sollen.

*_Hinweis_*:
Die Tags selbst werden nicht gelöscht.
Sie werden lediglich aus der Variante entfernt.

| *Tags hinzufügen*
|Welche Tags möchtest du mit der Variante verknüpfen?
Klicke in das Feld und wähle die Tags, die mit der Variante verknüpft werden sollen.

*_Hinweis_*:
Nutze diese Aktion zusammen mit der Aktion *Alle Tags entfernen*, wenn die neuen Tags die vorhandenen ersetzen sollen.
Das heißt, wenn die vorhandenen Tags zuerst aus dem Variantendatensatz entfernt werden sollen.

2+| *Varianteneinstellungen*

| *Gewicht brutto*
|

| *Gewicht netto*
|

| *Grundpreis anzeigen*
|

| *GTIN generieren*
|

| *Kategorien*
|

| *Varianten-Zeitstempel für Marktplatzexporte aktualisieren*
|

| *Vererbung*
|

| *Zolltarifnummer*
|

2+| *Verfügbarkeit und Sichtbarkeit*

| *Aktiv*
|

| *Angezeigte Lieferzeit*
|

| *Bestandsbeschränkung*
|

| *Für Mandanten trotz negativem netto Warenstand sichtbar stellen*
|

| *Immer unsichtbar in Artikelauflistung*
|

| *In Artikelauflistung sichtbar, wenn positiver Netto-Warenbestand*
|

| *In Artikelauflistung unsichtbar, wenn negativer Netto-Warenbestand*
|

| *Lieferbar, wenn positiver Netto-Warenbestand*
|

| *Mandanten (Shops)*
|

| *Nicht lieferbar, wenn negativer Netto-Warenbestand*
|

| *Sichtbar, wenn positiver Netto-Warenbestand*
|

| *Unsichtbar, wenn negativer Netto-Warenbestand*
|

| *Verkaufskanäle*
|

2+| *Verkaufspreise*

| *Preiskalkulation*
|

| *Verkaufspreis*
|

|===

[#650]
== Import & Export

Nutze den Import & Export, wenn du z.B. viele Artikel und Varianten gleichzeitig anpassen willst.
Exportiere eine CSV-Datei, die mit Produktdaten gefüllt ist.
Dann überarbeite die Datei und importiere sie wieder.

[discrete]
=== Ablauf

. Lade die nötigen Plugins herunter:
.. Elastischer Export
.. FormatDesigner
. Erstelle sogenannte Datenformate mit Hilfe des FormatDesigners.
. Richte den elastischen Export ein. Wähle dabei das soeben erstellte Datenformat aus.
. Exportiere die CSV-Datei, überarbeite diese und importiere sie wieder in plentymarkets.

[discrete]
=== Weiterführende Informationen

[.row]
====
[.col-md-6]
.Elastischer Export
=====
* link:https://marketplace.plentymarkets.com/plugins/sales/marktplaetze/elasticexport_4763[Plugin: Elastischer Export^]
* xref:daten:elastischer-export.adoc#[Einrichung und Verwendung]
* xref:daten:best-practices-elastischer-export.adoc#[Fehlerbehebung]
* xref:daten:dropshipping-elasticexport-bp.adoc#[Praxisbeispiel]
=====

[.col-md-6]
.FormatDesigner
=====
* link:https://marketplace.plentymarkets.com/formatdesigner_6483[Plugin: FormatDesigner^]
* xref:daten:FormatDesigner.adoc#[Eigene Datenformate erstellen]
* xref:daten:format-typen.adoc#[Liste der verfügbaren Formattypen]
=====

[.col-md-6]
.Import-Tool
=====
* xref:daten:ElasticSync.adoc#[Import-Tool nutzen]
* xref:daten:sync-typen.adoc#[Liste der verfügbaren Importtypen]
* xref:daten:best-practices-elasticsync-variantenanlage.adoc#[Praxisbeispiel: Neue Artikel und Varianten importieren]
=====
====

[#700]
== Suchen & Ersetzen

////
späteren zeitpunkt - Liste der möglichen Datenbankfelder ergänzen mit Links oder includes für die jeweilige Erklärungen
////

Stell dir vor, du hast gerade erfahren, dass dein Hersteller ein Zubehörteil umbenannt hat.
Jetzt ist es an dir, den Namen in allen Artikeltexten zu ändern.

Verwende die Suchen & Ersetzen-Funktion, um ein Wort oder eine Formulierung global in allen Artikeltexten anzupassen.
Mit anderen Worten, suche nach einem bestimmten Artikeltext in der Datenbank und ersetze die Ergebnisse mit neuen Texten.

[.instruction]
Artikeltexte suchen und ersetzen:

. Öffne das Menü *Artikel » Suchen & Ersetzen*.
. Wähle das Datenbankfeld.
. Gib einen Suchbegriff in das erste Feld ein. Beachte die Groß-/Kleinschreibung.
. Gib einen neuen Text in das zweite Feld ein.
. Klicke auf *Suchen*. +
→ Die Anzahl der gefundenen Artikel wird angezeigt.
. Klicke auf *Alle ersetzen*. +
→ Alle Texte werden durch die neuen Texte ersetzt.

[#800]
== Artikel und Varianten kopieren

Stell dir vor, du willst einen neuen Artikel zu deinem Sortiment hinzufügen.
Er ist einem bestehenden Produkt recht ähnlich.
Kopiere in diesem Fall das bestehende Produkt.
Ändere danach die abweichenden Einstellungen für den neuen Artikel.

[.instruction]
Artikel kopieren:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. xref:artikel:suche.adoc#100[Suche] und öffne den Artikel.
. Klicke auf *Kopieren* (terra:copy[role="yellow"]) in der oberen Symbolleiste. +
→ Das Fenster *Kopieren* wird geöffnet.
. Klicke auf terra:save[role="green"] *Kopieren*. +
→ Der Artikel wird kopiert und in einem neuen Tab geöffnet.

[discrete]
===== Was wird genau kopiert?

Es wird eine Kopie des Artikels und seiner Varianten erstellt.
Du kannst den neuen Artikel xref:artikel:artikel-verwalten.adoc#[weiter bearbeiten].
Prüfe z.B. die xref:artikel:artikel-verwalten.adoc#240[Verkaufspreise], xref:artikel:artikel-verwalten.adoc#250[Barcodes] und xref:artikel:artikel-verwalten.adoc#200[Verfügbarkeiten] besonders sorgfältig und passe sie bei Bedarf an.

[cols="1,1,1"]
|===
| Wird kopiert | Wird nicht kopiert |Wird automatisch vergeben

a|* Artikeldaten, die du im Tab **Global** eingibst
* Artikeltexte
* Freitextfelder
* Merkmale
* Bilder
* Cross-Selling-Einstellungen
* Verkaufspreise samt hinterlegter Werte
* Barcodes samt hinterlegter Werte
* Artikelpakete
* Eigenschaften
a|* Listings
* Media-Dateien
* Verfügbarkeit der Hauptvariante, d.h. der Artikel wird deaktiviert
* Maße
* Kosten
a|* Eine neue Artikel-ID wird vergeben.
* Neue Varianten-IDs werden vergeben.
* Neue Variantennummern werden vergeben.
|===

[TIP]
.Varianten können auch kopiert werden!
====
Kopiere eine Variante, um sie in verschiedenen Mengen anzubieten. Sämtliche Variantendaten werden beim Kopieren übernommen. Hauptvarianten können nicht kopiert werden.

. xref:artikel:suche.adoc#400[Suche] und öffne eine Variante (Ausnahme: die Hauptvariante).
. Klicke auf *Kopieren* terra:copy[role="yellow"] in der unteren Symbolleiste. +
→ Das Fenster **Kopieren** wird geöffnet.
. Gib den Inhalt ein und wähle die Einheit.
. Klicke auf terra:save[role="green"] *Kopieren*. +
→ Die Variante wird kopiert und in einem neuen Tab geöffnet.
====
