= Tags und Markierungen
:keywords: Tag, Tags, Markierung, Markierungen, Markierung 1, Markierung 2
:description: Verliere nicht den Überblick! Tags und Markierungen sind gute Möglichkeiten, Artikel übersichtlicher zu gestalten und besser zu sortieren.
:id: EQTFNT8
:author: team-item

Willst du den Überblick über deine Produkte im Backend behalten?
In plentymarkets ist dies durch Tags und Markierungen möglich.

[discrete]
==== Was ist der Unterschied zwischen Tags und Markierungen?

[cols="1,4a"]
|====

| xref:artikel:markierungen.adoc#400[Tags]
|
*_Technische Angaben_*:

* Tags sind Texte, wie Keywords oder Phrasen.
* Tags werden mit einzelnen Varianten verknüpft.
* Deine Varianten können mit beliebig vielen Tags verknüpft werden.

*_Anwendungsbeispiele_*:

* du willst den Überblick über viele verschiedene Varianten im Backend behalten.
* du willst einige Varianten im Frontend mit Schlagworten versehen.

//* Entscheide, welche Tags für Kunden im plentyShop sichtbar sein sollen.
//* Tags können auch sogar andere Datentypen hervorheben, z.B. Kunden, Aufträge, Tickets usw.

| xref:artikel:markierungen.adoc#100[Markierungen] +
(werden nicht weiterentwickelt)

|
*_Technische Angaben_*:

* Markierungen sind grafische Symbole.
* Markierungen werden mit ganzen Artikeldatensätzen verknüpft.
* Deine Artikel können mit maximal zwei Markierungen verknüpft werden.

*_Anwendungsbeispiel_*:

* du willst den Überblick über viele verschiedene Artikel im Backend behalten.

|====

[#400]
== Tags

Willst du den Überblick über deine Varianten im Backend behalten?
Oder willst du deine Varianten im Frontend mit Schlagworten versehen?
Tags machen es möglich.

* *_Backend-Übersicht_*: du siehst die Tags, wenn du deine Artikel und Varianten im Backend betrachtest.
Solche visuellen Unterstützungen helfen dir, die richtige Variante auf den ersten Blick zu finden.
Du kannst sogar gezielt xref:artikel:suche.adoc#intable-tags[nach Varianten im Backend suchen], die ein bestimmtes Tag haben.
* *_Schlagworte im plentyShop_*: du entscheidest, welche Tags für Kunden im plentyShop sichtbar sein sollen und welche nicht.
//* *_Weitere Datentypen_*: du kannst Tags sogar auch verwenden, um andere Datentypen hervorzuheben, z.B. Kunden, Aufträge, Tickets usw.

[#500]
=== Neue Tags erstellen

include::_includes:page$tags-creation.adoc[]

[#550]
=== Bestehende Tags finden

include::_includes:page$tags-search.adoc[]

[#600]
=== Varianten mit Tags versehen

Nachdem du deine Tags erstellt hast, kannst du sie mit Varianten verknüpfen.
Tags können:

* xref:artikel:artikel-verwalten.adoc#268[manuell mit Varianten verknüpft werden].
* xref:daten:elasticSync-artikel.adoc#2290[mit Hilfe einer Importdatei verknüpft werden].
* xref:artikel:massenbearbeitung.adoc#300[mit Hilfe der Varianten-Gruppenfunktion verknüpft werden].
* xref:artikel:massenbearbeitung.adoc#600[mit Hilfe der Varianten-Stapelverarbeitung verknüpft werden].

[TIP]
.Vererbungsverhalten
====
Tags, die du mit der Hauptvariate verknüpfst, werden an die Untervarianten des Artikels vererbt. Wenn du pro Variante eigene Tags speichern möchtest, deaktiviere die Vererbung und speichere eigene Tags an den Varianten.
====

[#700]
=== Fragen und Antworten

[.collapseBox]
.*Wie finde ich alle Varianten, die mit einem bestimmten Tag verknüpft wurden?*
--

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Stelle die Filter links wie folgt ein:
.. Setze links den Filter xref:artikel:suche.adoc#intable-tabellentyp[Tabellentyp] auf *Varianten*.
.. Setze links den Filter xref:artikel:suche.adoc#intable-aktiv[Aktiv] auf *ALLE*.
.. Wähle im Filter xref:artikel:suche.adoc#intable-tags[Klicken, um Tags hinzuzufügen] die Tags aus der Dropdown-Liste.
. Klicke auf *Suchen* (icon:search[role="blue"]). +
→ Alle Varianten, die mit dem Tag verknüpft wurden, werden angezeigt.

--

[.collapseBox]
.*Wie mache ich Tags für Kunden im Frontend sichtbar?*
--

. Öffne das Menü *Einrichtung » Einstellungen » Tags » [Tag öffnen]*.
. Wähle den passenden Webshop aus der Dropdown-Liste *Mandant*. +
*_Hinweis_*: Diese Option wird nur angezeigt, wenn du die Verfügbarkeit xref:artikel:markierungen.adoc#intable-bereich[Variante] gewählt hast.
. *Speichere* (icon:save[set=plenty, role="darkGrey"]) die Einstellungen.
. Nutze das ShopBuilder-Widget xref:webshop:shop-builder.adoc#_tags[Artikel » Tags], um zu steuern, wie die Tags in deinem Webshop angezeigt werden sollen.

--

[.collapseBox]
.*Können Tags auch per Import erstellt werden?*
--

Nein.
Tags können nicht per Import erstellt werden
Es ist nur möglich, Tags manuell zu erstellen, wie in der obigen Anleitung beschrieben.

Es ist jedoch möglich, Tags per Import mit Varianten zu verknüpfen.
xref:daten:elasticSync-artikel.adoc#2290[Weitere Informationen].

--

[.collapseBox]
.*Werden Tags vererbt? Werden sie also von der Hauptvariante an die Untervarianten weitergegeben?*
--

Tags, die du mit der Hauptvariate verknüpfst, werden an die Untervarianten des Artikels vererbt. Wenn du pro Variante eigene Tags speichern möchtest, deaktiviere die Vererbung und speichere eigene Tags an den Varianten.

--

[.collapseBox]
.*Ich kann keine Tags erstellen oder bearbeiten. Warum nicht?*
--

include::_includes:page$tags-rights.adoc[]

////
Personen mit xref:business-entscheidungen:benutzerkonten-zugaenge.adoc#10[Backend-Zugriffsrechten] können dieses Menü nur sehen, wenn ein Admin ihnen Zugriff gewährt hat.

. Wende dich an eine Person mit Administratorrechten für das plentymarkets-System.
. Diese Person öffnet das Menü *Einrichtung » Einstellungen » Benutzer » Rechte » Benutzer*.
. Dann öffnet sie das Benutzerkonto und schaltet die notwendigen Rechte frei.
. *Speichere* (icon:save[role="green"]) die Einstellungen.
. Sollte das Problem weiterhin bestehen, wende dich an die link:https://forum.plentymarkets.com/c/aenderungshistorie/604[Supporter im Forum^].

[discrete]
===== Menü-Sichtbarkeiten

Dieser Bereich stellt die Menüstruktur in plentymarkets dar.
Wähle die Menüpunkte (icon:check-square[role="blue"]), die für den Benutzer sichtbar sein sollen.
Hast du hier ein Menü ausgewählt, werden automatisch auch die entsprechenden REST-Rechte unter *Berechtigungen* mit ausgewählt.

[cols="1,1"]
|====
|Recht |Erläuterung

| *Daten > Änderungshistorie > Suche*
|Das Recht, die xref:daten:aenderungshistorie.adoc#200[Live-Suche] zu sehen und zu nutzen.

| *Daten > Änderungshistorie > Tagesänderungen*
|Das Recht, die xref:daten:aenderungshistorie.adoc#900[Tagesänderungen] zu sehen und zu nutzen.

| *Daten > Änderungshistorie > Archiv*
|Das Recht, das xref:daten:aenderungshistorie.adoc#1000[Archiv] zu sehen und die kostenpflichtigen Archivdateien anzufordern und herunterzuladen.

| *Daten > Änderungshistorie > Einstellungen*
|Das Recht, die xref:daten:aenderungshistorie.adoc#1100[Einstellungen der Änderungshistorie] zu sehen und zu ändern.
|====

[discrete]
===== Berechtigungen

Die REST-Rechte, die für bestimmte Aktionen benötigt werden.
Hast du ein Menü unter *Menü-Sichtbarkeiten* ausgewählt, werden automatisch auch hier die entsprechenden REST-Rechte mit ausgewählt.

[cols="1,1"]
|====
|Recht |Erläuterung

| *Daten > Änderungshistorie > Archiv > Anfordern*
|Das Recht, die kostenpflichtigen xref:daten:aenderungshistorie.adoc#1000[Archivdateien] anzufordern und herunterzuladen.

| *Daten > Änderungshistorie > Archiv > Anzeigen*
|Das Recht, das xref:daten:aenderungshistorie.adoc#1000[Archiv] zu sehen.

| *Daten > Änderungshistorie > Einstellungen > Aktualisieren*
|Das Recht, die xref:daten:aenderungshistorie.adoc#1100[Einstellungen der Änderungshistorie] zu ändern.

| *Daten > Änderungshistorie > Einstellungen > Anzeigen*
|Das Recht, die xref:daten:aenderungshistorie.adoc#1100[Einstellungen der Änderungshistorie] zu sehen.

| *Daten > Änderungshistorie > Suche > Anzeigen*
|Das Recht, die xref:daten:aenderungshistorie.adoc#200[Live-Suche] zu sehen und zu nutzen.

| *Daten > Änderungshistorie > Tagesänderungen > Anzeigen*
|Das Recht, die xref:daten:aenderungshistorie.adoc#900[Tagesänderungen] zu sehen und zu nutzen.
|====
////

--

[#100]
== Markierungen

Die Idee ist ganz einfach.
Weise jedem deiner Artikel eine oder zwei Markierungen zu.
Diese Markierungen wirst du sehen, wenn du deine Artikel im Backend betrachtest.
Solche visuellen Unterstützungen helfen dir, die richtigen Artikel auf den ersten Blick zu finden.
Du kannst auch xref:artikel:suche.adoc#100[gezielt nach Artikeln im Backend suchen], die eine bestimmte Markierung oder Kombination von Markierungen haben.

Wirf zunächst einen Blick auf die verschiedenen Markierungen, die in plentymarkets enthalten sind.
Die Markierungen sind standardmäßig nach der ID benannt.
Du kannst sie aber xref:artikel:markierungen.adoc#200[bei Bedarf umbenennen].
Sobald du mit den Namen zufrieden bist, kannst du die xref:artikel:markierungen.adoc#300[Markierungen mit Artikeln verknüpfen].

[#200]
=== Markierungen umbenennen

Wirf zunächst einen Blick auf die verschiedenen Markierungen, die in plentymarkets enthalten sind.
Es gibt 31 Symbole, die du als "Markierung 1" verwenden kannst und 11 Symbole, die du als "Markierung 2" verwenden kannst.
Die Markierungen sind standardmäßig nach der ID benannt.
Du kannst sie aber bei Bedarf umbenennen.

[.instruction]
Markierung umbenennen:

. Öffne das Menü *Einrichtung » Artikel » Markierungen*.
. Gib unter *Name* einen Namen ein.
. *Speichere* (icon:save[set=plenty, role="green"]) die Einstellungen.

[#300]
=== Artikel mit Markierungen versehen

Sobald du mit den Namen zufrieden bist, kannst du die Markierungen mit Artikeln verknüpfen.
Diese Markierungen wirst du sehen, wenn du deine Artikel im Backend betrachtest.
Solche visuellen Unterstützungen helfen dir, die richtigen Artikel auf den ersten Blick zu finden.
Du kannst auch xref:artikel:suche.adoc#100[gezielt nach Artikeln im Backend suchen], die eine bestimmte Markierung oder Kombination von Markierungen haben.

[.instruction]
Artikel mit bis zu zwei Markierungen versehen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. xref:artikel:suche.adoc#100[Suche] und öffne den Artikel. +
→ Ganz weit rechts in der Symbolleiste sind zwei Schaltflächen für Markierungen.
. Klicke auf eine oder beide der Schaltflächen und wähle eine Markierung aus der Dropdown-Liste.
. *Speichere* (icon:save[set=plenty, role="green"]) die Einstellungen.
