= Multipacks und Artikelpakete (neue Artikel-UI)
:keywords: Neue Artikel-UI, Artikel » Artikel-UI, Artikel zusammenfassen, Artikel kombinieren, Produkte zusammenfassen, Produkte kombinieren, Varianten zusammenfassen, Varianten kombinieren, Kombiangebot, Kombiangebote, Multipack, Multipacks, Multi-Pack, Multi-Packs, Multi Pack, Multi Packs, Artikelpaket, Artikelpakete, Artikel-Paket, Artikel-Pakete, Artikel Paket, Artikel Pakete, Paket, Pakete, Kit, Geschenkset, Bundle, Bundles, Bestandteil, Bestandteile, Komponent, Komponente, Paketbestandteil, Paketbestandteile, Paket-Bestandteil, Paket-Bestandteile, Paketautomatik
:description: Erfahre, wie du Produkte in plentymarkets kombinierst und sie als eine Verkaufseinheit anbietest.
:author: team-item

////
zuletzt bearbeitet 06.10.2022
////

//ToDo - sobald Sets mit der neue UI kompatibel sind, dann folgende Keywords ergänzen:
//Set, Sets, Artikelset, Artikelsets, Artikel-Set, Artikel-Sets, Artikel Set, Artikel Sets, Ab-Preis, Ab-Preise, Ab Preis, Ab Preise, Setpreis, Setbestandteil, Setbestandteile, Setbestandteilen
//ToDo - sobald Sets mit der neue UI kompatibel sind, dann den Kapitel hinzufügen und auch die Preamble-Text anpassen, um Sets zu erwähnen
//ToDo - Gifs ergänzen
//Kommentare innerhalb der Seite abarbeiten
//FAQ Bereich ergänzen und die Pakete-Varianten-Frage überarbeiten

plentymarkets bietet verschiedene Möglichkeiten, Produkte zu kombinieren und als eine Verkaufseinheit anzubieten.
Diese Seite beschreibt das Grundkonzept und die manuelle Erstellung von Multipacks und Artikelpaketen.

[TIP]
.Manuelle Erstellung vs. Import
====
Diese Seite konzentriert sich auf die manuelle Erstellung.
plentymarkets enthält aber auch ein Import-Tool, mit dem du Multipacks und Artikelpakete importieren kannst.
Ausführlichere Informationen dazu findest du im xref:artikel:multipack-paket-set.adoc#400[FAQ-Bereich].
====

[discrete]
=== Voraussetzungen

Diese Seite setzt voraus, dass du bereits Grundkenntnisse über die Artikelstruktur in plentymarkets hast.
Du sollst den xref:artikel:struktur.adoc#[Unterschied zwischen Artikeln und Varianten] kennen und du sollst wissen, wie Varianten ihre xref:artikel:vererbung.adoc#[Daten vererben].

Zudem müssen folgende Daten im System vorhanden sein, um wie hier beschrieben Multipacks oder Artikelpakete manuell zu erstellen:

* xref:artikel:attribute.adoc#[Attribute und Attributwerte]
* xref:artikel:kategorien.adoc#[Kategorien]
* xref:artikel:preise.adoc#[Verkaufspreise]

[#100]
== Multipacks

*_Beispiel_*: 1 Flasche Wasser, eine Packung mit 6 Flaschen und eine Packung mit 12 Flaschen.

*_Technische Angaben_*:

* Multipacks sind verschiedene Stückzahlen derselben Variante.
* Die Hauptvariante entspricht der kleinsten Verkaufseinheit des Produkts, z.B. 1 Flasche.
* Alle weiteren Varianten sind Kombinationen dieser kleinsten Verkaufseinheit, z.B. 6 oder 12 Flaschen.
* Bestand wird nur an der Hauptvariante verwaltet.
* Alle Varianten eines Multipacks haben dieselben Attribute.

[#110]
=== Ein neues Multipack erstellen

Erstelle den Multipack-Datensatz, indem du einige grundlegende Produktinformationen eingibst.
Nach der Erstellung fügst du weitere Produktinformationen hinzu und aktivierst das Multipack, wenn es verkaufsfertig ist.

//#gif#

[.instruction]
Ein neues Multipack erstellen:

. Öffne das Menü *Artikel » Artikel-UI*.
. Klicke auf icon:plus[role="darkGrey"] und wähle *Multipack-Artikel*.
. Ein Pop-Up Fenster wird geöffnet. Dieses Fenster ist in mehrere Schritte unterteilt. Nimm die Einstellungen in jedem Schritt vor.

[.collapseBox]
.*Schritt: Name*
--

//ToDo - füge die Tabelle stattdessen mit ein Include-Tag ein

:manual:

[cols="1,4a"]
|===

| *Artikelname* +
[red]#(Pflichtfeld)#
|Gib einen Namen für den Artikel ein.

*_Hinweis_*:
Nachdem du den Artikel erstellt hast, kannst du den Namen in weitere Sprachen übersetzen oder auch weitere Namen hinzufügen, z.B. wenn der Artikel auf Marktplätzen anders genannt werden soll.

|===

--

[.collapseBox]
.*Schritt: Kategorien*
--

//ToDo - füge die Tabelle stattdessen mit ein Include-Tag ein

[cols="1,4"]
|===

| *Kategorien wählen* +
[red]#(Pflichtfeld)#
a|In welche Kategorie soll der Artikel einsortiert werden?

. Klicke auf *Kategorien wählen*. +
→ Ein Pop-Up Fenster wird geöffnet.
. Erweitere die Einträge (icon:chevron-right[role="darkGrey"]) und wähle alle Kategorien (icon:check-square[role="blue"]), in denen der Artikel erscheinen soll.
Diese Liste enthält nur die xref:artikel:kategorien.adoc#[Kategorien], die du bereits in plentymarkets angelegt hast.
. Klicke auf *Übernehmen*. +
→ Die gewählten Kategorien werden als Tabelle dargestellt.
Klicke auf material:delete[role="darkGrey"], um eine Kategorie aus dieser Liste zu entfernen, oder klicke auf icon:pencil[role="darkGrey"] *Kategorien wählen*, um weitere Kategorien hinzuzufügen.

|===

--

[.collapseBox]
.*Schritt: Hauptvariante*
--

Die erste Variante eines Artikels wird als Hauptvariante bezeichnet.

* Bei einem Multipack entspricht die Hauptvariante der kleinsten Verkaufseinheit des Produkts, z.B. 1 Flasche.
* Alle weiteren Varianten sind Kombinationen dieser kleinsten Verkaufseinheit, z.B. 6 oder 12 Flaschen.
* Bestand wird nur an der Hauptvariante verwaltet.

[cols="1s,4"]
|===

| Variantennr.
|Gib eine Nummer für die Hauptvariante ein.

| Inhalt +
Einheit
|Gib einen numerischen Wert für die Hauptvariante ein und wähle eine Einheit aus der Dropdown-Liste, z.B. 500ml oder 150g.

| Attribute wählen
a|Die Hauptvariante kann Attribute besitzen, muss es aber nicht.

. Klicke auf *Attribute wählen*. +
→ Ein Pop-Up Fenster wird geöffnet.
. Erweitere die Attribute (icon:chevron-right[role="darkGrey"]) und wähle die Attributwerte (icon:check-square[role="blue"]), die du für die Hauptvariante verwenden willst, z.B. "mit Kohlensäure".
Diese Liste enthält nur die xref:artikel:attribute.adoc#[Attribute und Werte], die du bereits in plentymarkets angelegt hast.
. Klicke auf *Übernehmen*. +
→ Die gewählten Attributwerte werden als Tabelle dargestellt.
Klicke auf material:delete[role="darkGrey"], um einen Attributwert aus dieser Liste zu entfernen, oder klicke auf icon:pencil[role="darkGrey"] *Attribute wählen*, um weitere Attributwerte hinzuzufügen.

*_Hinweis_*: Alle Varianten eines Multipacks haben dieselben Attribute.
Innerhalb eines Multipacks können also nicht z.B. manche Wasserflaschen mit und andere ohne Kohlensäure sein.

|===

--

[.collapseBox]
.*Schritt: Fertig*
--

//ToDo - füge die Tabelle stattdessen mit ein Include-Tag ein

[cols="1s,4"]
|===

| Zusammenfassung
a|Hier siehst du eine Zusammenfassung deiner gewählten Einstellungen.
Klicke auf *Artikel erstellen*, wenn du mit den Angaben einverstanden bist.

Nach der Erstellung hast du folgende Möglichkeiten:

[cols="1s,4a"]
!===

! Zum Artikel
!Das Pop-up-Fenster wird geschlossen und der neu erstellte Artikeldatensatz wird zur weiteren Bearbeitung geöffnet.

! Weiteren Artikel erstellen
!Das Pop-up-Fenster wird für den nächsten Artikel neu gestartet.

! Schliessen
!Das Pop-up-Fenster wird geschlossen.

!===

|===

--

[#120]
=== Benötigte Stückzahlen erstellen

Multipacks sind verschiedene Stückzahlen derselben Variante.
Kunden kaufen z.B. entweder 1 Flasche Wasser, eine Packung mit 6 Flaschen oder eine Packung mit 12 Flaschen.

//#gif#

[.instruction]
Benötigte Stückzahlen erstellen:

. Öffne das Menü *Artikel » Artikel-UI » [Multipack öffnen] » Variantenübersicht*.
. Klicke auf *Varianten erstellen* (icon:plus[role="darkGrey"]).
. Ein Pop-Up Fenster wird geöffnet. Dieses Fenster ist in mehrere Schritte unterteilt. Nimm die Einstellungen in jedem Schritt vor.

[.collapseBox]
.*Schritt: Einstellungen*
--

[cols="1,4a"]
|===

| *Größe der Packung*
|Die Hauptvariante entspricht der kleinsten Verkaufseinheit des Produkts, z.B. 1 Flasche.
Hier erstellst du alle weiteren Kombinationen dieser kleinsten Verkaufseinheit, z.B. 6 oder 12 Flaschen.

*_Vorgehensweise_*:

. Gib eine Stückzahl für die Variante ein. Zum Beispiel, die Hauptvariante mal 6.
. Klicke auf *Weiter* und dann auf *Multipack-Variante erstellen*.
. Wiederhole den Vorgang für die nächste Stückzahl. Zum Beispiel, die Hauptvariante mal 12.

|===

--

[.collapseBox]
.*Schritt: Zusammenfassung*
--

[cols="1s,4"]
|===

| Zusammenfassung
a|Hier siehst du eine Zusammenfassung deiner gewählten Einstellungen.
Klicke auf *Multipack-Variante erstellen*, wenn du mit den Angaben einverstanden bist.

Nach der Erstellung hast du folgende Möglichkeiten:

[cols="1s,4a"]
!===

! Zur Multipack-Variante
!Das Pop-up-Fenster wird geschlossen und die neu erstellte Variante wird zur weiteren Bearbeitung geöffnet.

! Weitere Multipack-Variante erstellen
!Das Pop-up-Fenster wird für die nächste Variante neu gestartet.

! Schliessen
!Das Pop-up-Fenster wird geschlossen.

!===

|===

--

[#130]
=== Weitere Produktdaten hinzufügen

Während der Erstellung hast du bereits einige grundlegende Informationen angegeben.
Füge jetzt weitere Produktdaten hinzu.
Wie soll das Multipack zum Beispiel aussehen?
Welche Bilder und Texte sollen angezeigt werden?

[.collapseBox]
.*Verkaufspreis*
--

Wie viel soll das Multipack kosten, wenn es als 1er, 6er- oder 12er-Pack verkauft wird?
Entscheide, welcher Preis für jede Stückzahl gelten soll.
Dazu musst du die Vererbung von Verkaufspreisen deaktivieren und Preise für jede Stückzahl einzeln speichern.

---

[.instruction]
Preis für die Hauptvariante festlegen:

. Öffne das Menü *Artikel » Artikel-UI » [Multipack öffnen] » [Hauptvariante öffnen] » Element: Verkaufspreise*.
. Klicke auf icon:plus[role="darkGrey"]. +
→ Es öffnet sich ein Pop-up-Fenster.
. Wähle die Verkaufspreise (icon:check-square[role="blue"]), die du mit der Variante verknüpfen willst.
. Klicke auf *Übernehmen*. +
→ Die Daten werden als Tabelle dargestellt.
. Gib den Geldbetrag ein.
. *Speichere* (terra:save[role="darkGrey"]) die Einstellungen.

---

[.instruction]
Preis für eine Untervariante festlegen:

. Öffne das Menü *Artikel » Artikel-UI » [Multipack öffnen] » [Untervariante öffnen]*.
. Klicke auf *Vererbung* (terra:item_variation_inheritance[role="darkGrey"]) in der oberen Symbolleiste.
. Deaktiviere die Vererbung von Verkaufspreisen.
. Klicke auf *Ausführen*.
. Navigiere zum Element *Verkaufspreise*.
. Gib einen abweichenden Geldbetrag für die Untervariante ein.
. *Speichere* (terra:save[role="darkGrey"]) die Einstellungen.
. Wiederhole den Vorgang für die weiteren Stückzahlen.

--

[.collapseBox]
.*Warenbestand*
--

Bestand wird nur an der Hauptvariante gepflegt.
Das heißt, der Bestand der weiteren Varianten ist rein informativ.
Wenn sich der Bestand der Hauptvariante ändert, wird der Bestand für die anderen Varianten des Artikels neu berechnet.

--

[#140]
=== Multipack im Frontend anschauen

//mit ein Include-Tag einbinden

Neugierig, wie das neue Produkt in deinem plentyShop oder auf Amazon aussehen wird?
Schau dir eine Vorschau des Artikels an und finde heraus, wo du noch weitere Produktdaten hinzufügen oder Einstellungen optimieren musst.

//#gif#

[.instruction]
Vorschau des Artikels ansehen:

. Klicke auf *Produkt Link* (material:open_in_new[role="darkGrey"]) in der Toolbar. +
→ Ein Pop-Up Fenster wird geöffnet.
. Nimm die Einstellungen vor.
. Klicke auf material:open_in_new[role="darkGrey"] *Öffnen*. +
→ Eine Vorschau des Artikels wird angezeigt.

[TIP]
.Produkt-Links für Artikel oder Varianten
====
Du kannst den Produkt-Link für einen Artikel oder für eine Variante aufrufen.
Der Produkt-Link Button befindet sich in der Toolbar der Artikel- und Variantenansicht.
====

[cols="1s,4a"]
|===
|Einstellung |Erläuterung

| URL
|Die URL des Produkts wird oben in einer Info-Box angezeigt.
Klicke auf die URL, um die Seite in einem neuen Tab zu öffnen.
Klicke auf terra:copy[role="darkGrey"], um die URL in die Zwischenablage zu kopieren.

| Verkaufskanal
|Möchtest du sehen, wie das Produkt in deinem plentyShop oder auf Amazon aussehen wird?

[cols="1s,4a"]
!===

! plentyShop LTS Preview
!
Du siehst eine Vorschau im plentyShop.
Mögliche Anwendungen:

* Du willst prüfen, wie ein Produkt im plentyShop aussehen wird, bevor du es für deine Endkunden sichtbar schaltest.
* Du bist gerade dabei, deinen plentyShop umzugestalten und willst prüfen, wie ein Produkt mit einem anderen Plugin-Set aussehen würde.

*_Weitere Einstellungen_*: Wähle auch den Mandanten und das Plugin-Set.

! plentyShop LTS live
!
Du siehst, wie das Produkt aktuell im plentyShop aussieht.
Mögliche Anwendung:

* Du willst prüfen, welche Preise und Informationen angezeigt werden, wenn Endkunden deinen plentyShop über ein bestimmtes Preisportal aufrufen.

*_Weitere Einstellungen_*: Wähle auch den Mandanten und die Herkunft.

! Amazon
!Du siehst eine Vorschau auf Amazon.
Stelle sicher, dass du bereits eine ASIN für die Variante hinterlegt hast.
Die Vorschau kann nur dann erstellt werden, wenn die Variante eine ASIN hat.

*_Weitere Einstellung_*: Wähle auch die ASIN.

!===

| Mandant (Shop)
|In welchem Mandanten, d.h. in welchem Webshop, willst du die Vorschau sehen?
Wähle den Mandanten aus der Dropdown-Liste aus.

*_Hintergrund-Info_*: Mit plentymarkets kannst du mehrere Webshops, d.h. xref:webshop:mandanten-verwalten.adoc#[mehrere Mandanten], mit nur einer Software verwalten.
Somit ist es möglich, über ein plentymarkets System mehrere unterschiedliche Geschäftsbereiche zu realisieren.

*_Hinweis_*: Diese Option wird nur angezeigt, wenn du den Verkaufskanal *plentyShop LTS Preview* oder *plentyShop LTS live* gewählt hast.

| Plugin-Set
|In welchem Plugin-Set willst du die Vorschau sehen?
Wähle das Plugin-Set aus der Dropdown-Liste aus.

*_Hintergrund-Info_*: In plentymarkets stehen xref:plugins:plugins.adoc#[Plugins] nicht für sich alleine, sondern werden zu sogenannten Plugin-Sets zusammengefasst.
So kannst du zum Beispiel saisonale Layouts für deinen plentyShop gestalten oder neue Versionen von Plugins testen bevor du sie live schaltest.

*_Hinweis_*: Diese Option wird nur angezeigt, wenn du den Verkaufskanal *plentyShop LTS Preview* gewählt hast.

| Herkunft
|Willst du prüfen, welche Preise und Informationen angezeigt werden, wenn Endkunden deinen plentyShop über ein bestimmtes Preisportal aufrufen?
Wähle die Herkunft aus der Dropdown-Liste aus.

*_Hinweis_*: Diese Option wird nur angezeigt, wenn du den Verkaufskanal *plentyShop LTS live* gewählt hast.

| ASIN
|Welche ASIN möchtest du für die Vorschau verwenden?
Wähle die ASIN aus der Dropdown-Liste aus.

*_Hinweis_*: Diese Dropdown-Liste enthält nur die ASINs, die bereits für die Variante hinterlegt sind.
Hast du noch keine ASIN für die Variante gespeichert?
Oder hast du noch keine ASIN aus der Dropdown-Liste gewählt?
Dann siehst du eine Fehlermeldung in der Info-Box oben.

*_Hinweis_*: Diese Option wird nur angezeigt, wenn du den Verkaufskanal *Amazon* gewählt hast.

|===

[#150]
=== Multipack für den Verkauf freigeben

//mit ein Include-Tag einbinden

Varianten sind für Kunden im plentyShop nicht sichtbar, bis sie aktiviert werden.
Das heißt, du kannst an inaktiven Varianten arbeiten, ohne dass deine Kunden es merken.
Du aktivierst die Variante, sobald sie in deinem plentyShop veröffentlicht werden soll.

[.instruction]
Variante aktivieren:

. Öffne das Menü *Artikel » Artikel-UI » [Variante öffnen] » Element: Verfügbarkeit und Sichtbarkeit*.
. Wähle die Option *Aktiv* (icon:toggle-on[role="blue"]).
. *Speichere* (terra:save[role="darkGrey"]) die Einstellungen.

[TIP]
.Vollständige Checkliste zur Artikel-Sichtbarkeit
====
Artikel müssen nicht nur aktiviert werden, sondern benötigen sie auch einen Preis, eine Kategorie und positive Netto-Warenbestand.
Sonst werden Kunden den Artikel nicht kaufen können.
Arbeite xref:artikel:checkliste-artikel-anzeige.adoc#[diese Checkliste] durch und vergewissere dich, dass dein Artikel alle Voraussetzungen erfüllt, um im plentyShop sichtbar zu sein.
Diese Checkliste hilft dir, mögliche Fehlerquellen bei der Artikelsichtbarkeit ausfindig zu machen.
====

[#200]
== Artikelpakete

*_Beispiel_*: Ein Bartpflege-Kit bestehend aus einer Schere, einer Bürste, Bartöl und Bartwachs.

*_Technische Angaben_*:

* Die Bestandteile (z.B. Schere, Bürste, Bartöl, Bartwachs) können:
** zum Einen als einzelne Artikel angeboten werden.
** zum Anderen als Paket angeboten werden.
Endkunden kaufen dann das ganze Paket.
Sie können nicht selbst entscheiden, welche Bestandteile im Paket enthalten sind.
Zum Beispiel können sie das Bartpflege-Kit nicht ohne das Bartwachs kaufen.
* Es ist möglich, den Paketpreis günstiger als die Summe der Einzelpreise zu definieren.
* Es ist möglich, Varianten mit unterschiedlichen Steuersätzen zusammen in einem Paket anzubieten.
* Alle Bestandteile müssen auf dem selben Lager liegen.
* Der Warenbestand des Pakets richtet sich nach dem Bestandteil mit dem geringsten Bestand.
Am Paket selbst pflegst du keinen Bestand.

[#210]
=== Ein neues Artikelpaket erstellen

Bleiben wir bei dem Beispiel, dass du ein Bartpflege-Kit bestehend aus einer Schere, einer Bürste, Bartöl und Bartwachs erstellen möchtest.
Dies erfolgt in drei Schritten:

. Du erstellst die einzelnen Bestandteile, d.h. die Schere, die Bürste, das Bartöl und das Bartwachs.
. Du erstellst das Paket selbst, d.h. das Bartpflege-Kit.
. Du fügst die Bestandteile dem Paket hinzu.

[.collapseBox]
.*Die einzelnen Bestandteile erstellen*
--

Die Bestandteile können als einzelne Artikel und/oder als Paket gekauft werden.
Beispiel: Die Schere kann als Einzelartikel gekauft werden.
Sie kann aber auch Teil des Pakets sein.

[.instruction]
Ein Bestandteil erstellen:

. Öffne das Menü *Artikel » Artikel-UI*.
. Klicke auf icon:plus[role="darkGrey"] und wähle *Standard-Artikel*.
. Ein Pop-Up Fenster wird geöffnet. Dieses Fenster ist in mehrere Schritte unterteilt. Nimm die Einstellungen in jedem Schritt vor.
xref:artikel:artikel-manuell-anlegen.adoc#200[Weitere Informationen zu den Einstellungen].

[TIP]
.Füge noch weitere Produktdaten für die Bestandteile hinzu
====
Wie soll der Bestandteil aussehen, wenn er als Einzelartikel angeboten wird?
Welches Bild und welcher Text sollen angezeigt werden?
Wie viel soll der Einzelartikel kosten?
Füge noch weitere Informationen hinzu, für den Fall, dass der Bestandteil als Einzelartikel verkauft wird.
Zum Beispiel kannst du:

* xref:artikel:verzeichnis.adoc#40[Bilder hochladen]
* xref:artikel:verzeichnis.adoc#50[Produkttexte schreiben]
* xref:artikel:verzeichnis.adoc#340[Preise hinterlegen]
* xref:artikel:verzeichnis.adoc#30[Bestandsinformationen einsehen]
====

--

[.collapseBox]
.*Das Paket selbst erstellen*
--

Erstelle nun einen Artikel, der das Paket selbst darstellt.
Am Paket selbst pflegst du keinen Bestand.
Der Warenbestand des Pakets richtet sich nach dem Bestandteil mit dem geringsten Bestand.

[.instruction]
Einen neuen Artikel erstellen:

. Öffne das Menü *Artikel » Artikel-UI*.
. Klicke auf icon:plus[role="darkGrey"] und wähle *Standard-Artikel*.
. Ein Pop-Up Fenster wird geöffnet. Dieses Fenster ist in mehrere Schritte unterteilt. Nimm die Einstellungen in jedem Schritt vor.
xref:artikel:artikel-manuell-anlegen.adoc#200[Weitere Informationen zu den Einstellungen].
. Anschließend fügst du die Bestandteile dem Paket hinzu.

[TIP]
.Vorhandenen Artikel als Paket verwenden
====
Anstatt einen neuen Paketartikel zu erstellen, kannst du auch einen vorhandenen Artikel verwenden und diesem Bestandteile hinzufügen.
Beachte, dass der Paketartikel, dem du Bestandteile hinzufügst, keinen eigenen Bestand haben darf.
====

--

[.collapseBox]
.*Die Bestandteile zum Paket hinzufügen*
--

Wähle alle Bestandteile, die zusammen als Paket verkauft werden sollen.
Es ist möglich, Varianten mit unterschiedlichen Steuersätzen zusammen in einem Paket anzubieten.
Alle Bestandteile müssen aber auf dem selben Lager liegen.

//ToDo - als Include von der Verzeichnis-Seite einbinden (oder andersrum, also hier ausgeschrieben und als Include in die Verzeichnis-Seite, siehe auch da die ToDo) - Attribute verwenden, um Variante öffnen in Paket öffnen > Varianten-Ebene zu ändern

[.instruction]
Bestandteile zum Paket hinzufügen:

. Öffne das Menü *Artikel » Artikel-UI » [Paket öffnen] » [Varianten-Ebene] » Element: Paket*.
. Klicke im Element auf icon:ellipsis-v[role="darkGrey"] und dann auf icon:plus[role="darkGrey"] *Paketbestandteile hinzufügen*. +
→ Es öffnet sich ein Pop-up-Fenster.
. Wähle die Varianten (icon:check-square[role="blue"]), die du zum Paket hinzufügen möchtest.
. Klicke auf *Übernehmen*. +
→ Die Daten werden als Tabelle dargestellt.
. Gib die Menge ein.
. *Speichere* (terra:save[role="darkGrey"]) die Einstellungen.

--

[#220]
=== Produktdaten für das Paket hinzufügen

Wie soll das Paket aussehen, wenn es als Ganzes angeboten wird?
Welches Bild und welcher Text sollen angezeigt werden?
Wie viel soll das Gesamtpaket kosten?
Füge jetzt weitere Informationen hinzu, für den Fall, dass das Paket als Ganzes verkauft wird.

[.collapseBox]
.*Verkaufspreis*
--

Der Paketpreis wird unabhängig von den Preisen der einzelnen Bestandteile festgelegt.
Zum Beispiel könntest du den Paketpreis günstiger als die Summe der Einzelpreise definieren.

//ToDo - als Include von der Verzeichnis-Seite einbinden - Attribute verwenden, um Variante öffnen in Paket öffnen > Varianten-Ebene zu ändern

. Öffne das Menü *Artikel » Artikel-UI » [Paket öffnen] » [Varianten-Ebene] » Element: Verkaufspreise*.
. Klicke auf icon:plus[role="darkGrey"]. +
→ Es öffnet sich ein Pop-up-Fenster.
. Wähle die Verkaufspreise (icon:check-square[role="blue"]), die du mit der Variante verknüpfen willst.
. Klicke auf *Übernehmen*. +
→ Die Daten werden als Tabelle dargestellt.
. Gib den Geldbetrag ein.
. *Speichere* (terra:save[role="darkGrey"]) die Einstellungen.

In der Auftragsabwicklung wird nur der Paketpreis angegeben.
Die Bestandteile werden ohne Einzelpreise angegeben.

--

[.collapseBox]
.*Warenbestand*
--

Der Warenbestand des Pakets richtet sich nach dem Bestandteil mit dem geringsten Bestand.
Am Paket selbst pflegst du keinen Bestand.

--

[.collapseBox]
.*Gewicht und Einkaufspreis*
--

//ToDo - als Include von der Verzeichnis-Seite einbinden (oder andersrum, also hier ausgeschrieben und als Include in die Verzeichnis-Seite, siehe auch da die ToDo) - Attribute verwenden, um Variante öffnen in Paket öffnen > Varianten-Ebene zu ändern

Ein Artikelpaket ist eine Zusammenstellung mehrerer Bestandteile.
Jeder Bestandteil verfügt wiederum über wichtige Kennzahlen, wie Gewicht und Einkaufspreis.
Aber wie setzen sich diese Kennzahlen für das Artikelpaket insgesamt zusammen?
Du kannst das Gewicht und den EK für das Artikelpaket selber eingeben.
Es gibt aber auch die Möglichkeit, diese Kennzahlen automatisch berechnen zu lassen.

. Öffne das Menü *Artikel » Artikel-UI » [Paket öffnen] » [Varianten-Ebene] » Element: Paket*.
. Klicke im Element auf icon:ellipsis-v[role="darkGrey"] und dann auf icon:cog[role="darkGrey"] *Paketautomatiken konfigurieren*. +
→ Es öffnet sich ein Pop-up-Fenster.
. Wähle die gewünschten Automatismen (icon:toggle-on[role="blue"]).
. Klicke auf *Übernehmen*.

[cols="1,3"]
|===

| *Paket: Bruttogewicht automatisch aus Bestandteilen berechnen*
|Das Butto-Gewicht wird automatisch anhand der Bestandteile berechnet.
Das heißt, im Element *Inhalt / Dimensionen* wird zukünftig das Feld xref:artikel:verzeichnis.adoc#180[Gewicht in Gramm brutto] ausgegraut sein.

| *Paket: Nettogewicht automatisch aus Bestandteilen berechnen*
|Das Netto-Gewicht wird automatisch anhand der Bestandteile berechnet.
Das heißt, im Element *Inhalt / Dimensionen* wird zukünftig das Feld xref:artikel:verzeichnis.adoc#180[Gewicht in Gramm netto] ausgegraut sein.

| *Paket: Nettoeinkaufspreis automatisch aus Bestandteilen berechnen*
|Der Netto-Einkaufspreis wird automatisch anhand der Bestandteile berechnet.
Das heißt, im Element *Kosten* wird zukünftig das Feld xref:artikel:verzeichnis.adoc#190[Einkaufspreis netto] ausgegraut sein.

| *Paket: Gleitenden Nettoeinkaufspreis automatisch aus Bestandteilen berechnen*
|Der gleitende Netto-Einkaufspreis wird automatisch anhand der Bestandteile berechnet.
Das heißt, im Element *Kosten* wird zukünftig das Feld xref:artikel:verzeichnis.adoc#190[Gleitender Durchschnittseinkaufspreis netto] ausgegraut sein.

|===

[TIP]
.Berechnungsautomatik standardmäßig aktivieren
====
Hast du nur wenige Artikel, die du von der automatischen Berechnung ausschließen möchtest?
Kein Problem!
Du kannst die Berechnungsautomatik standardmäßig aktivieren.

. Öffne das Menü *Einrichtung » Artikel » Einstellungen*.
. Bestimme welche Kennzahlen standardmäßig berechnet werden sollen.
Verwende dabei folgende Optionen:
* *Paketautomatik für Gewicht brutto*
* *Paketautomatik für Gewicht netto*
* *Paketautomatik für EKs*
* *Paketautomatik für GLD EKs*
====

--

[#230]
=== Paket im Frontend anschauen

//ToDo - Include

Neugierig, wie das neue Produkt in deinem plentyShop oder auf Amazon aussehen wird?
Schau dir eine Vorschau des Artikels an und finde heraus, wo du noch weitere Produktdaten hinzufügen oder Einstellungen optimieren musst.

//#gif#

[.instruction]
Vorschau des Artikels ansehen:

. Klicke auf *Produkt Link* (material:open_in_new[role="darkGrey"]) in der Toolbar. +
→ Ein Pop-Up Fenster wird geöffnet.
. Nimm die Einstellungen vor.
. Klicke auf material:open_in_new[role="darkGrey"] *Öffnen*. +
→ Eine Vorschau des Artikels wird angezeigt.

[TIP]
.Produkt-Links für Artikel oder Varianten
====
Du kannst den Produkt-Link für einen Artikel oder für eine Variante aufrufen.
Der Produkt-Link Button befindet sich in der Toolbar der Artikel- und Variantenansicht.
====

[cols="1s,4a"]
|===
|Einstellung |Erläuterung

| URL
|Die URL des Produkts wird oben in einer Info-Box angezeigt.
Klicke auf die URL, um die Seite in einem neuen Tab zu öffnen.
Klicke auf terra:copy[role="darkGrey"], um die URL in die Zwischenablage zu kopieren.

| Verkaufskanal
|Möchtest du sehen, wie das Produkt in deinem plentyShop oder auf Amazon aussehen wird?

[cols="1s,4a"]
!===

! plentyShop LTS Preview
!
Du siehst eine Vorschau im plentyShop.
Mögliche Anwendungen:

* Du willst prüfen, wie ein Produkt im plentyShop aussehen wird, bevor du es für deine Endkunden sichtbar schaltest.
* Du bist gerade dabei, deinen plentyShop umzugestalten und willst prüfen, wie ein Produkt mit einem anderen Plugin-Set aussehen würde.

*_Weitere Einstellungen_*: Wähle auch den Mandanten und das Plugin-Set.

! plentyShop LTS live
!
Du siehst, wie das Produkt aktuell im plentyShop aussieht.
Mögliche Anwendung:

* Du willst prüfen, welche Preise und Informationen angezeigt werden, wenn Endkunden deinen plentyShop über ein bestimmtes Preisportal aufrufen.

*_Weitere Einstellungen_*: Wähle auch den Mandanten und die Herkunft.

! Amazon
!Du siehst eine Vorschau auf Amazon.
Stelle sicher, dass du bereits eine ASIN für die Variante hinterlegt hast.
Die Vorschau kann nur dann erstellt werden, wenn die Variante eine ASIN hat.

*_Weitere Einstellung_*: Wähle auch die ASIN.

!===

| Mandant (Shop)
|In welchem Mandanten, d.h. in welchem Webshop, willst du die Vorschau sehen?
Wähle den Mandanten aus der Dropdown-Liste aus.

*_Hintergrund-Info_*: Mit plentymarkets kannst du mehrere Webshops, d.h. xref:webshop:mandanten-verwalten.adoc#[mehrere Mandanten], mit nur einer Software verwalten.
Somit ist es möglich, über ein plentymarkets System mehrere unterschiedliche Geschäftsbereiche zu realisieren.

*_Hinweis_*: Diese Option wird nur angezeigt, wenn du den Verkaufskanal *plentyShop LTS Preview* oder *plentyShop LTS live* gewählt hast.

| Plugin-Set
|In welchem Plugin-Set willst du die Vorschau sehen?
Wähle das Plugin-Set aus der Dropdown-Liste aus.

*_Hintergrund-Info_*: In plentymarkets stehen xref:plugins:plugins.adoc#[Plugins] nicht für sich alleine, sondern werden zu sogenannten Plugin-Sets zusammengefasst.
So kannst du zum Beispiel saisonale Layouts für deinen plentyShop gestalten oder neue Versionen von Plugins testen bevor du sie live schaltest.

*_Hinweis_*: Diese Option wird nur angezeigt, wenn du den Verkaufskanal *plentyShop LTS Preview* gewählt hast.

| Herkunft
|Willst du prüfen, welche Preise und Informationen angezeigt werden, wenn Endkunden deinen plentyShop über ein bestimmtes Preisportal aufrufen?
Wähle die Herkunft aus der Dropdown-Liste aus.

*_Hinweis_*: Diese Option wird nur angezeigt, wenn du den Verkaufskanal *plentyShop LTS live* gewählt hast.

| ASIN
|Welche ASIN möchtest du für die Vorschau verwenden?
Wähle die ASIN aus der Dropdown-Liste aus.

*_Hinweis_*: Diese Dropdown-Liste enthält nur die ASINs, die bereits für die Variante hinterlegt sind.
Hast du noch keine ASIN für die Variante gespeichert?
Oder hast du noch keine ASIN aus der Dropdown-Liste gewählt?
Dann siehst du eine Fehlermeldung in der Info-Box oben.

*_Hinweis_*: Diese Option wird nur angezeigt, wenn du den Verkaufskanal *Amazon* gewählt hast.

|===

[#240]
=== Paket für den Verkauf freigeben

//ToDo - Include

Varianten sind für Kunden im plentyShop nicht sichtbar, bis sie aktiviert werden.
Das heißt, du kannst an inaktiven Varianten arbeiten, ohne dass deine Kunden es merken.
Du aktivierst die Variante, sobald sie in deinem plentyShop veröffentlicht werden soll.

[.instruction]
Variante aktivieren:

. Öffne das Menü *Artikel » Artikel-UI » [Variante öffnen] » Element: Verfügbarkeit und Sichtbarkeit*.
. Wähle die Option *Aktiv* (icon:toggle-on[role="blue"]).
. *Speichere* (terra:save[role="darkGrey"]) die Einstellungen.

[TIP]
.Vollständige Checkliste zur Artikel-Sichtbarkeit
====
Artikel müssen nicht nur aktiviert werden, sondern benötigen sie auch einen Preis, eine Kategorie und positive Netto-Warenbestand.
Sonst werden Kunden den Artikel nicht kaufen können.
Arbeite xref:artikel:checkliste-artikel-anzeige.adoc#[diese Checkliste] durch und vergewissere dich, dass dein Artikel alle Voraussetzungen erfüllt, um im plentyShop sichtbar zu sein.
Diese Checkliste hilft dir, mögliche Fehlerquellen bei der Artikelsichtbarkeit ausfindig zu machen.
====

[#400]
== Fragen und Antworten

[.collapseBox]
.*Standard-Artikel vs. Multipack-Artikel*
//.*Standard-Artikel vs. Multipack-Artikel vs. Set-Artikel*
--

* *Standard-Artikel*: Dieser Typ eignet sich für:
** Normale Artikel und Varianten.
Beispiel: Ein T-Shirt, das in den Farben Rot, Blau und Grün erhältlich ist.
xref:artikel:artikel-manuell-anlegen.adoc#200[Weitere Informationen zur Erstellung].
** Pakete.
Beispiel: Ein Bartpflege-Kit bestehend aus einer Schere, einer Bürste, Bartöl und Bartwachs.
xref:artikel:multipack-paket-set.adoc#200[Weitere Informationen zur Erstellung].
* *Multipack-Artikel*: Dieser Typ eignet sich für Multipacks.
Beispiel: 1 Flasche Wasser, eine Packung mit 6 Flaschen und eine Packung mit 12 Flaschen.
xref:artikel:multipack-paket-set.adoc#100[Weitere Informationen zur Erstellung].
//* *Set-Artikel*: Dieser Typ eignet sich für Sets.
//Beispiel: Eine Fußballuniform bestehend aus einem Trikot, Shorts und Socken. Endkunden stellen ihre eigenen Uniformen zusammen, indem sie die gewünschte Größe und Farbe für jede der drei Komponenten auswählen.
//xref:artikel:multipack-paket-set.adoc#300[Weitere Informationen zur Erstellung].

*_Hinweis_*: Diese Einstellung kann nicht mehr geändert werden, nachdem du den Artikel erstellt hast.

--

[.collapseBox]
.*Manuelle Erstellung vs. Import*
--

Diese Seite konzentriert sich auf die manuelle Erstellung.
plentymarkets enthält aber auch ein xref:daten:ElasticSync.adoc#[Import-Tool], mit dem du Multipacks und Artikelpakete importieren kannst.
Die Idee ist ganz einfach.
Anstatt Artikeldaten manuell in plentymarkets zu speichern, trägst du die gleiche Informationen in eine CSV-Datei ein und importierst diese Datei dann in dein System.

* Verwende dazu den Import-Typ *Artikel*.
* Gib mit Hilfe des Zuordnungsfeldes xref:daten:elasticSync-artikel.adoc#250[Artikel / Typ] an, welche Art von Artikel du importieren willst.

--

////
//ToDo - this should be something like a Praxisbeispiel within the FAQ chapter
[discrete]
[#2300]
==== Mehrere Pakete in einem Artikel abbilden

Artikelvarianten können zu Paketen mit verschiedenen Bestandteilen werden. Auf diese Weise gestaltest du Artikelpakete komplex und vielseitig nach deinen Anforderungen.

*_Beispiel für Paketvarianten_*: du möchtest je ein Handtuch und ein Badetuch im Paket in unterschiedlichen Farben verkaufen. Hierfür sind folgende Schritte notwendig:

* Attribut erstellen mit den notwendigen Werten, zum Beispiel rot und blau
* Artikel erstellen, der als Paketartikel dient, zum Beispiel Handtuchpaket
* Varianten erstellen und dabei die Attributwerte verknüpfen
* Artikel für Paketbestandteile erstellen, zum Beispiel Handtuch und Badetuch
* Varianten für Paketbestandteile erstellen, zum Beispiel rotes Handtuch, blaues Handtuch etc.
* Paketbestandteile zu den Varianten des Artikelpakets hinzufügen

Auf diese Weise bietest du in deinem plentyShop den Artikel *Handtuchpaket* als Paket in den Farben *Rot* und *Blau* an.

[#300]
== Sets
////
