= Artikel (alte PIM-UI)
:description: Dieses Kapitel beschreibt das neue Artikel-Menü, das sich derzeit in einer Testphase befindet.
:author: team-item

////
zuletzt bearbeitet 10.05.2023
////

Dieses Kapitel beschreibt die alte Benutzeroberfläche im Bereich Artikel PIM.

PIM steht für Product Information Management. Mit dem PIM von plentysystems verwaltest du alle Informationen deiner Artikel in einem zentralen System. Das heißt, du pflegst deine Produktdaten in plentysystems ein. Daraufhin kannst du deine Ware auf diversen Marktplätzen, im eigenen plentyShop und im stationären Laden verkaufen.

Müssen Daten, wie z.B. die Beschreibung oder der Preis eines Artikels, zu einem späteren Zeitpunkt geändert werden, musst du diese Daten lediglich zentral in plentysystems ändern. Die Änderung kann automatisch auf allen genutzten Vertriebskanälen angezeigt werden.

== Häufig gestellte Fragen

[.collapseBox]
.*Wie kann ich Feedback geben?*
--

Feedback zum neuen Artikel-Menü ist in link:https://forum.plentymarkets.com/c/item/18[dieser Forenkategorie] herzlich willkommen.

--

[.collapseBox]
.*Wird das alte Artikel-Menü bald abgeschafft?*
--

Nein.
Das Menü *Artikel » Artikel bearbeiten* wird nicht in nächster Zeit abgeschaltet werden.
Derzeit können die neue und alte Artikel-Menüs parallel verwendet werden.

--

[.collapseBox]
.*Führen Links aus anderen Menüs in das neue Artikel-Menü?*
--

Du kannst selbst entscheiden, ob das alte oder neue Artikel-Menü standardmäßig verwendet werden soll.

. Öffne das Menü *Einrichtung » Artikel » Neue Artikel UI (Testphase)*.
. Aktiviere die Umschalttaste (icon:toggle-on[role="blue"]), wenn das neue Artikel-Menü als Standard verwendet werden soll.
Ist der Schalter aktiviert, werden Links aus anderen Menüs (z.B. Aufträge) auf das neue Artikel-Menü umgeleitet.
. Speichere (terra:save[role="darkGrey"]) die Einstellungen.
. Melde dich bei plentysystems ab und dann wieder an.

Diese Einstellung gilt nur für das jeweilige Benutzerkonto.
Sie kann jederzeit aktiviert oder deaktiviert werden.

--

[.collapseBox]
.*Welche Funktionen fehlen?*
--

Folgende Funktionalitäten fehlen und sind nicht geplant:

* Merkmale
* Freitextfelder
* Artikel-Tab Media
* Artikel-Tab Statistik

--
