= Varianten-Nummern
:keywords: Variantennummer, Variantennummern, Varianten-Nummer, Variantennr., Präfix für neue Variantennummern, Zuletzt vergebene Variantennummer, Präfix, NEW-
:description: Neue Varianten erhalten automatisch eine Variantennummer. Entscheide selbst, nach welchem Muster neue Variantennummern vergeben werden sollen.
:author: team-item

////
zuletzt bearbeitet 12.03.2021
////

Jedes Mal, wenn du eine xref:artikel:neue-artikel.adoc#[neue Variante anlegst], erhält diese automatisch eine Variantennummer.
Du kannst selbst entscheiden, nach welchem Muster die neuen Variantennummern vergeben werden sollen.

[.instruction]
Muster für Variantennummern wählen:

. Öffne das Menü *Einrichtung » Artikel » Einstellungen*.
. Nimm Einstellungen für *Präfix für neue Variantennummern* und *Zuletzt vergebene Variantennummer* vor.
. *Speichere* (terra:save[role="green"]) die Einstellungen.

[cols="1,3"]
|===
|Einstellung |Erläuterung

| *Präfix für neue Variantennummern*
|Gib ein Präfix ein, das beim Generieren neuer Variantennummern vorangestellt werden soll.
Ist das Feld leer, wird das Präfix *NEW-* verwendet.

| *Zuletzt vergebene Variantennummer*
|Zeigt die Variantennummer, die zuletzt vergeben wurde.
Weitere neue Variantennummern werden aufsteigend ab dieser Nummer generiert.
Die angezeigte Variantennummer wird aktualisiert, sobald eine neue Variantennummer generiert wurde.
Angezeigt wird also immer die Variantennummer, die beim Erstellen der letzten Variante vergeben wurde.
Gib eine andere Zahl ein, um das Muster für neue Variantennummern zu ändern.
Als nächste Variantennummer wird diese Zahl plus 1 vergeben.
|===
