= Was ist Vererbung?
:keywords: Vererbung, Vererbung, Vererbung, Erben, Vererbungsfunktion, Hauptvariante, Sub-Variante, Untervariante, Einzelvererbung, Vererbungsverhalten
:description: Lerne, wie deine Varianten Daten und Einstellungen von der Hauptvariante erben.
:author: team-item

////
zuletzt bearbeitet 11.10.2022
////

//tag::inheritance-preamble[]
plentysystems ermöglicht es dir, viele Informationen für jede Variante separat zu pflegen.
Eine Variante kann zum Beispiel ein wenig mehr als die anderen kosten oder sie kann andere Maße haben.

Aber keine Sorge, das bedeutet nicht, dass der Pflegeaufwand gleich in die Höhe schießt, wenn du viele Varianten hast.
Um dies zu verhindern, wird die erste Variante deines Artikels als Hauptvariante definiert.
Die Hauptvariante gibt ihre Daten an alle anderen Varianten weiter.
Das heißt, die Daten werden standardmäßig vererbt.
Bei Bedarf kannst du die Vererbung deaktivieren und abweichende Informationen für einzelne Varianten speichern.
//end::inheritance-preamble[]

video::167716545[vimeo]

[TIP]
.Praxisbeispiele: Hauptvariante
====

//tag::what-is-main-variation[]
Die erste Variante eines Artikels wird als Hauptvariante bezeichnet. Hat ein Artikel mehrere Varianten, kann die Hauptvariante entweder selbst ein verkaufbares Produkt sein oder rein virtuell bestehen, um die weiteren Untervarianten des Artikels anhand von Vererbung zu verwalten.

Stell dir mal vor, du verkaufst ein T-Shirt in den Größen S, M, L und XL:

* *_Hauptvariante ist nicht verkaufbar_*: Die Hauptvariante steht nicht zum Verkauf und entspricht auch keiner dieser Größen. Die Hauptvariante ist lediglich ein Datencontainer zur Verwaltung von Preisen, Kategorien und anderen Produkteinstellungen.
* *_Hauptvariante ist verkaufbar_*: Die Hauptvariante steht zum Verkauf und entspricht einer dieser Größen, z.B. S.
//end::what-is-main-variation[]

====

[#200]
== Vererbung deaktivieren

//tag::deactivate-inheritance[]
Wenn du eine neue Untervariante erstellst, werden zunächst alle vererbbaren Einstellungen von der Hauptvariante übernommen.
Sind für die Untervariante andere Einstellungen erforderlich, musst du die Vererbung an die Untervariante deaktivieren und dann abweichende Einstellungen speichern.

[.instruction]
Vererbung deaktivieren:

//interner Kommentar - der Konfig hier ist fast genau das selbe wie in die Verzeichnis Seite für die neue UI - falls hier etwas geändert wird, bitte in der Verzeichnis Seite auch anpassen

. Öffne das Menü *Artikel » Artikel » [Untervariante öffnen]*.
. Klicke auf das Symbol terra:item_variation_inheritance[role="darkGrey"] in der Toolbar. +
→ Es öffnet sich ein Pop-up-Fenster.
. Entscheide, welche Einstellungen vererbt werden sollen:
.. Wähle die Einstellungen, die vererbt werden sollen (icon:check-square[role="blue"]).
.. Wähle die Einstellungen ab, die nicht vererbt werden sollen (icon:square-o[role="darkGrey"]).
. Klicke auf *Ausführen*.
. Ändere die nicht vererbten Einstellungen wie benötigt.
. *Speichere* (terra:save[role="darkGrey"]) die Einstellungen.

//end::deactivate-inheritance[]

[#300]
== Wechsel der Hauptvariante

//tag::switch-main-variation[]
Falls du mit der aktuellen Hauptvariante nicht zufrieden bist, kannst du eine andere Variante zur Hauptvariante machen.
Dabei wird die Untervariante zur neuen Hauptvariante und die bisherige Hauptvariante wird zur Untervariante.

[.instruction]
Andere Variante zur Hauptvariante machen:

. Öffne das Menü *Artikel » Artikel » [Artikel öffnen] » Variantenübersicht*.
. Öffne die Untervariante, die zur neuen Hauptvariante werden soll.
. Klicke in der Toolbar auf icon:ellipsis-v[role="darkGrey"] und dann auf material:star[role="darkGrey"] *Zur Hauptvariante machen*.
. Bestätige die Sicherheitsabfrage.

[TIP]
.Vererbung bei Wechsel der Hauptvariante
====
Die vererbbaren Werte der neuen Hauptvariante werden mit den Werten der Untervarianten abgeglichen.
Bei einem Wechsel der Hauptvariante bleiben alle Werte erhalten und die folgende Vererbungslogik greift:

* Für Werte der Untervarianten, die mit den Werten der neuen Hauptvariante identisch sind, wird die Vererbung automatisch aktiviert.
* Werte, die nicht mit dem Wert der neuen Hauptvariante übereinstimmen, werden direkt an der Untervariante gespeichert, also nicht vererbt.

Deaktiviere die Vererbung an den Untervarianten, wenn dieses Vererbungsverhalten nicht deinen Anforderungen entspricht.
====

//end::switch-main-variation[]

== Fragen und Antworten

[.collapseBox]
.*Was ist Vererbung?*
--

include::page$vererbung.adoc[tag=inheritance-preamble]

--

[.collapseBox]
.*Was ist eine Hauptvariante?*
--

include::page$vererbung.adoc[tag=what-is-main-variation]

--

[.collapseBox]
.*Wie deaktiviere ich die Vererbung?*
--

include::page$vererbung.adoc[tag=deactivate-inheritance]

--

[.collapseBox]
.*Kann ich eine andere Hauptvariante wählen?*
--

include::page$vererbung.adoc[tag=switch-main-variation]

--
