= Plugins
:author: team-plugin-core
:keywords: plugin, erweiterung, addon, integrationen
:description: Nutze Plugins, um dein System zu erweitern, deinen eigenen plentyShop einzurichten oder weitere Verkaufskanäle anzubinden.
:page-pagination:
:pos: plugins
:id: XPOMS9R

Plugins sind Erweiterungen, die du in dein plentymarkets System integrieren kannst. Sie bilden beispielsweise die Grundlage für deinen Webshop, dienen als Schnittstelle zum Verbinden von plentymarkets mit anderen Vertriebskanälen oder geben dir Möglichkeiten, um einfacher mit deinen Kund:innen zu kommunizieren.

In plentymarkets stehen Plugins nicht für sich alleine, sondern werden zu sogenannten Plugin-Sets zusammengefasst. Wenn du mehr als einen Webshop betreibst, kannst du so etwa unterschiedliche Layouts und Zahlungsarten für die beiden Shops verwalten. Selbst mit nur einem Vertriebskanal hast du aufgrund von Plugin-Sets die Möglichkeit, neue Versionen von Plugins zu testen bevor du sie tatsächlich live schaltest.

include::plugins:partial$anzahl-erlaubter-plugin-sets.adoc[]

== Mehr zum Thema Plugins

====
* Wenn du neue Plugins suchst, um dein plentymarkets System zu erweitern, besuche link:https://marketplace.plentymarkets.com/[plentyMarketplace^].
* Benötigst du eine bestimmte Funktionalität und wirst auf Marketplace nicht fündig, stelle dein Anliegen in der link:https://marketplace.plentymarkets.com/plentyprojects/[Projektbörse^] ein und erarbeite zusammen mit einer unserer link:https://marketplace.plentymarkets.com/partners[Partneragenturen^] eine Lösung. Oder...
* Erstelle deine eigenen Plugins. Mehr Informationen dazu findest du auf link:http://developers.plentymarkets.com/[plentyDevelopers^].
====
