[#plugin-deaktivieren]
= Plugin deaktivieren

Wenn du ein Plugin deaktivierst, wird es nicht mehr in deinem Webshop und Backend geladen. Diese Änderung wird direkt übernommen, ohne dass ein erneutes Bereitstellen des Plugin-Sets notwendig ist. So deaktivierte Plugins können auf gleichem Wege auch wieder aktiviert werden, ohne dass das Plugin-Set bereitgestellt werden muss.

Deaktivierte Plugins werden beim Bereitstellen eines Plugin-Sets nicht berücksichtigt. Wenn du ein Plugin-Set einmal erfolgreich bereitgestellt hast, ohne dass ein bestimmtes Plugin aktiviert war, musst du nach dem Aktivieren des Plugins <<plugins/hinzugefuegte-plugins-installieren#plugin-installieren, das Plugin-Set erneut bereitstellen>> bevor das Plugin aktiv ist.

Ob du ein Plugin durch Aktivieren und Deaktivieren aktiv oder inaktiv schalten kannst, kannst du im Menü *Plugins » Plugin-Übersicht* an der Spalte *Aktive Version* erkennen. Ist hier eine Versionsnummer eingetragen, musst du das Set nicht bereitstellen, um das Plugin aktiv zu schalten.

Du solltest ein Plugin dann deaktivieren, wenn du es nur vorübergehend nicht nutzen möchtest. Anders als beim Löschen eines Plugins, bleibt beim Deaktivieren die <<plugins/installierte-plugins-konfigurieren#lokale-vs-globale-konfiguration, lokale Konfiguration>> des Plugin erhalten.

Zum Deaktivieren eines Plugins, andere den Zustand des Plugins zu inaktiv (icon:toggle-off[]).