= Creating user classes
:lang: en
include::{includedir}/_header.adoc[]
:position: 10020
:url: videos/personalisation/user-accounts/create-user-class
:author: team-import-export

//tag::einleitung[]
[cols="2, 1" grid=none]
|===
|See which user classes are available in plentymarkets and learn how they can limit the menus and features that your employees can access.
|<<videos/personalisation/user-accounts/create-user-class#video, Creating user classes>>

|===
//end::einleitung[]

video::175831491[vimeo]

// tag::transkript[]
[.collapseBox]
.Transcript
--

Welcome to plentymarkets e-learning. Your plentymarkets system includes a wide range of functions that help you do everything from fulfill orders and manage stock, to provide customer support or publish newsletters and blog entries in your online store. If you have several employees working for you, then you'll probably have someone like a content manager publishing your blog entries, a warehouse technician fulfilling your orders and a support team fielding customer questions. Each of these employees will need to work with different functions and menus within your plentymarkets system.

This is the idea behind user classes. In the simplest terms, user classes are just different types of users who are given specific rights to your plentymarkets system.

So for example, call centre users are members of your support team who field customer questions. So they're given the right to access functions like the ticket system, customer data records and customer orders. The logistics class is for someone like a warehouse technician. So this user class is given the right to access stock and order information. And the blog class is for someone like your content manager. So this user class has the right to publish blog entries on your website.

This video tutorial takes a look at user classes. You'll learn about all of the different user classes that are available in plentymarkets and you'll see how they can easily be used to limit which menus and features are visible to your employees. Let's get started. I've already opened my plentymarkets system to the menu *Settings » Basic settings » User » Accounts*.


Here on the right, I see all of the user accounts that have already been created in my system. And this column here shows me which user class was saved for each of these accounts. If you're creating a new user account, then you'll select the user class from this drop-down menu here. Or if you're editing an existing user account, then you'll see the user class here. Alright, so now that you know where to save this setting, let's look at each of the user classes in detail.


Let's begin with the admins. This class has the right to access all menus and functions in plentymarkets without limitation. Admins are also allowed to create and edit other user accounts.
So make sure that you always have at least one admin user in your system, because you'll need an admin if you want to add new user accounts for other employees. And just keep in mind that if you have more than one admin user, then these user accounts will all be treated equally. So be sure to only make someone an admin if you really trust them to have unlimited access to your plentymarkets system. Since admins are able to create or delete other user accounts, other admins will also theoretically have the right to delete or modify your user account.

Now let's look at call center users. As I mentioned just a moment ago, this user class is intended for members of your support team. They're allowd to access the homepage and calendar in your plentymarkets system. And since your support team communicates with customers, this user class is allowed to access the ticket system and customer data records. And since a lot of the questions they'll field will probably relate to customer orders, this class is also allowed to access order information.


Let's see what plentymarkets looks like when someone from this user class logs into the system. Here you can see that the user is not able to delete any of the user accounts and there's no longer a button up here for creating a new user account. This user is not able to open other user accounts. Rather, the user can only open his or her own account.

Here the user can edit personal settings, like their own name, email address or password.
But the user can not edit other information. For example, the user can not switch their own account to a different class. Alright, and in terms of menus in plentymarkets, this user is able to access the homepage and calendar, customer information and the ticket system as well as customer orders. So this is what plentymarkets looks like for my call center employee. But before a call center user starts working with plentymarkets, there are still a few more settings that an admin user will need to customise for this account. Let me show you what I mean. So I'm going to log into plentymarkets as an admin and open the user account for my call center employee.


Here I click on the "Right" tab and I need to customise the settings saved for this user in the "Visibility" tab. So here, for example, you can limit which warehouses the user is allowed to work with. And here, you can limit which order statuses the user should be able to see. In other words, when the user opens the menu *Orders » Edit orders*, then he or she will only be able to see the orders that are in one of the statuses selected here. The selectable order statuses are similar. This specifies which order statuses the user should be able to set. In other words, when the user is working with orders, he or she will only be able to change the order's status to one of the statuses specified here. If you manage several different stores, then use this "Client" option here to decide which clients the user should be authorised to work with. And a bit farther down, select ticket statuses. When the user works with tickets, he or she will only be able to see tickets that are in one of the statuses specified here.

Alright, now let's look at a few other types of user classes. The blog class is intended for someone like a content manager whose job it is to publish blog entries on your website. This user class is allowed to access the homepage and calendar and it's also allowed to access the blog menu.

A logistics user is someone like a warehouse technician whose job it is to ship and fulfill orders.
This user class is allowed to access the homepage and calendar, manage stock and incoming items, access order information and import or export data from plentymarkets.

Let's take a quick look at what plentymarkets will look like when someone from the logistics user class logs into the system. Up here we can see which menus this user is allowed to access. Since the user ships and fulfills orders, it makes sense that he or she has access to stock and order information. And here in the settings menu, we see that this user is allowed to access stock settings or create fulfillment processes. OK and again, before a logistics user starts working with plentymarkets, there are still a few more settings that an admin user will need to customise for this account. So again, I just log into plentymarkets as an admin, open the user account for my logistics user, click on the "Right" tab and customise these same settings in the "Visibility" tab.

Alright, now let's take a look at the last few types of user classes. API users are external partners who are allowed to communicate via the A-P-I interface. Once you've created an API user, you'll need to give this user the right to carry out specific API calls. API users do not automatically have the right to carry out all calls. Rather, an admin will have to open this user account and select the individual calls that this user should be able to carry out. OK, so just as you've seen before, an admin user will need to open this user account and click on the "Right" tab. This time in the "SOAP API" tab, just place check marks next to whichever calls the user should be allowed to carry out.


OK, and last but certainly not least, we have variable user accounts. Variable accounts can be completely customised. In other words, you can pick and choose which exact access rights a variable user should have. An admin user will need to define which menus within plentymarkets should be visible to the user which SOAP calls the user should be able to carry out and which warehouses, order statuses, clients and tickets the user should be authorised to see. So this user class can be thought of as a way to mix and match all of the user classes that we've talked about so far. Variable user accounts are ideal for employees who need access to several different areas within plentymarkets, but who still shouldn't be given unlimited access like an admin. Alright, so just like I've done before, I'll log in with my admin user account, open my variable account, click on the "Right" tab and customise the settings in the "Visibility" tab. As you've also seen, I activate individual SOAP calls in the SOAP A-P-I tab and here in the "Menu" tab, I just place check marks next to whichever menus this user should be able to see. These check boxes here correspond to the blue menu bar in plentymarkets.



--
//end::transkript[]
