= Use attributes to create different item variations
:lang: en
include::{includedir}/_header.adoc[]
:position: 10030
:url: videos/items/attributes
:id: SIWPWQQ
:author: none

//tag::einleitung[]
[cols="2, 1" grid=none]
|===
|Whether you create items manually or import a CSV file, attributes are an integral part of your item data. Learn how to create them in your system and link them to your item variations.
|<<videos/items/attributes-attributes#video, Create attributes (0:31)>>

<<videos/items/attributes-variations#video, Create variations with attributes (2:04)>>

|===
//end::einleitung[]

video::265563423[vimeo]

// tag::transkript[]
[.collapseBox]
.Transcript
--
In our last tutorials, you've become more and more familiar with the wonderful world of items.
You've learned what settings are important to create items and how inheritance plays a big role in their family-like structure.

Now families are obviously made up of one-of-a-kind members - in plentymarkets-speak, we're talking about variations. But what distinct characteristics make variations unique within the item family? Attributes! They're the building blocks of variations. So if you want to offer customers different variations of an item, this video is for you!

But before we continue, let's just quickly clarify the difference between attributes and properties because they sometimes get mixed up.
In plentymarkets, we use properties for item families to express their uniqueness with features. Properties are passive characteristics that aren't required to create items, but do highlight certain technical details, like wifi for example.
Now back to the topic at hand!

Over the course of the last videos, you've become acquainted with this fancy raccoon t-shirt. Now let's set everything up so we can sell this t-shirt in different colours and sizes.

Whether you create items manually or import a CSV file, attributes are an integral part of your item data. They're managed centrally in your system and later linked to an item. That makes managing item data a piece of cake.
But enough with the theory! Let's get to work!

So we want different colours and sizes: Two different attributes that include several different attribute values.
As you can see, my list of attributes already includes size and the attribute values small through large.
Now let's give that t-shirt some colour. To set up a new attribute, we'll give it a name and then add the various colours the t-shirt is sold in, so yellow, red and black.

By the way, you'll often run into this internal name. All that means is that this name is only visible to you, not your customers. And just a friendly tip: your backend name should be as exact as possible.
Also, attributes are multilingual. So whether it's German, Chinese or Czech, you don't need to create additional attributes for languages. Simply select the language you need and enter the corresponding names of the values.
Alrighty! Size and colour! Check, check!

Time to create different variations of an item with these two attributes. But just a quick note, even though you can add new values to existing attributes later on, you can't add completely new attributes to existing variations. So make sure you've got the attributes you need in your system before you begin structuring your items.

This is our beloved t-shirt, fresh from the press, with the most important item settings. But without attributes, no variations!
Variations are always created as subordinate entities of an item.

Let's begin with the birds and the bees and create a new variation.
As always, content is a mandatory field. Next, select all the attributes and attribute values that are relevant for this t-shirt. In our case that's colours yellow, black and red and sizes small through large.

And for those of you who want to use the automatic import function, there are two ways to list your attributes on CSV files so that they can be organized correctly in your system.
Okay, now click the magic button - and presto! Our raccoon t-shirt is now available in 9 different variations - three different colours, three different sizes. Plus, each variation has it's very own ID so you can easily find it.

They say the apple doesn't fall far from the tree! Item variations are very similar to the main variation, except that they now include attributes in the data set and, just like real children, they can inherit settings from the main variation. So all you've gotta do is enter settings in the main variation if you want them to be passed down to the other variations.

But still, kids are individuals. So let them be unique!
For example, you can upload an individual image for every colour or enter an individual barcode or manage the variation's stock individually.
Heck! You can even individualise prices for, say, certain sizes!
Right on!

You've learned how to create attributes under the System menu and later link them to your item data when you create variations.
Make each variation as unique as it needs to be so your item family can thrive! Your customers will thank you for it!
--
//end::transkript[]
