= Automating returns
:lang: en
include::{includedir}/_header.adoc[]
:position: 10050
:url: videos/order-processing/returns-and-cancellations/automatic-returns
:id: BLSVIHS
:author: team-order-payment

//tag::introduction[]
[cols="2, 1" grid=none]
|===
|Learn how to automatically create returns with the help of a plentymarkets process. This video teaches you how to use the example process below and customise its settings as needed.
|<<videos/order-processing/returns-and-cancellations/automatic-returns-search-order#video, Searching for an order (0:34)>>

<<videos/order-processing/returns-and-cancellations/automatic-returns-scanning-items#video, Scanning the returned item (1:38)>>

<<videos/order-processing/returns-and-cancellations/automatic-returns-default-values#video, Customising default values (2:27)>>


|===
//end::introduction[]


video::243256565[vimeo]

File for this video:
link:https://cdn02.plentymarkets.com/pmsbpnokwu6a/frontend/plentyprocess/Automatic-Returns_2017_11_17_08_.plentyprocess[Automatic-Returns]{nbsp}icon:external-link[]

// tag::transcript[]
[.collapseBox]
.Transcript
--

Your business is doing great! Orders are pouring in and your staff members are busy shipping items to customers.
But every now and then, someone's bound to send an item back.
You've got two options.
Create a return manually, as you saw in the previous video or team up with plentymarkets processes and automate the job in no time!
Simply download the process file directly below this video and import it into your plentymarkets system.

So far, so good. Let's use this process to create a return!
The process starts out with a bunch of search fields which we use to find the order that's being returned.
Easy enough! But what if you only want one or two of these search fields? The rest are just in the way!
Simply head on over to your process settings and tell plentymarkets which search fields you want to see.

While you're here, tell plentymarkets which search field you use most often. Or in other words, where your mouse cursor should start out automatically.
Voila! I no longer see the customer number and my cursor starts out in the customer ID field.
Alright, so I search for an order and plentymarkets gives me a list of results.
Here I can see information about the order and here I can see information about the individual items included in the order.
Back in the settings, you can also customise which exact information should be displayed in the table.
You can tell plentymarkets that it should only display certain types of orders in the results or that it should prevent your warehouse technician from selecting certain types of orders.

Next, select the appropriate order and scan the barcode or ID of whichever item is being returned.
Alternatively, select the item down here to open the same pop-up window.
All that's left to do now is specify the item's status and its value.
Then tell plentymarkets where the item is located within your warehouse.
And indicate how many copies of the item are being returned.

When you're finished specify the return status and the reason for return.
The return is created and it appears in the order overview.

Before saying goodbye, I'd like to show you one last way that you can customise this process.
While creating the return just now, you surely noticed that some values were selected by default.
If you want to change any of these default values, then just head on over to the process settings and modify the information like so.
The next time you create a return, these values will be suggested by default.

And there you have it! A fully customised return process, which meets your business' needs.
Simply download the process file and import it into your system.
Then customise the process as needed and use it to automatically create returns in your plentymarkets system.
