= Automatically sending email templates
:lang: en
include::{includedir}/_header.adoc[]
:position: 10050
:url: videos/personalisation/emails/automatic-despatch
:id: KVZAKJD
:author: team-crm

//tag::einleitung[]
[cols="2, 1" grid=none]
|===
|plentymarkets can automatically send emails to customers whenever specific events occur. This video introduces you to two different ways of sending emails - with the automatic emailing function and with event procedures.
|<<videos/personalisation/emails/automatic-despatch-emails#video, Automatic emails (0:31)>>

<<videos/personalisation/emails/automatic-despatch-event-procedures#video, Event procedures (1:41)>>

|===
//end::einleitung[]

video::214835758[vimeo]

// tag::transkript[]
[.collapseBox]
.Transcript
--

Things are starting to come together nicely. You've created beautiful email templates and you're ready to start sending them out to your customers. But how?

Between order confirmations, forgotten passwords and other routine notifications, you'll be working late nights if you try to keep up with all those emails yourself. It would be much quicker if emails were just sent automatically! Wouldn't it be great if routine events acted like dominoes and automatically triggered specific emails? Well, you're in luck because plentymarkets does just that!

This "Automatic email" menu contains a list of routine events that online sellers are likely to encounter in their day-to-day business. For example, a customer bought one of your items on Amazon or a new customer created an account in your online store. Here in this menu, simply tell plentymarkets which of your email templates it should send out every time the event occurs.

If you want to take another look at one of your email templates, just click on the pencil icon to open the template in a new menu and edit it as needed. Alternatively, you may find that some events just don't apply to your business. For example, if you don't sell items on Rakuten, then you won't need to send automatic order confirmations. In this case, just select the option "do not send".

Once you've told plentymarkets how it should react to every event listed in this menu, you will have automated a large portion of your email communication.

But what about more complicated situations? For example, if your customer bought a specific item, then you may also want to send an email containing assembly instructions. Or if your customer spent a certain amount of money in your store, then you may want to reward them by emailing a discount code for their next purchase. In plentymarkets, all of these custom situations can be recreated with event procedures. It's the same idea as before. An event triggers an email. But here in this menu, you can get much more specific.

Let's take a look at the example mentioned just a moment ago - so sending assembly instructions along with a specific item. Add a filter to specify which item needs to have been purchased. And then add a procedure to specify which email should be sent. Of course, that was just a quick example. If you're new to event procedures and you'd like a more thorough explanation, then check out our video series on automation.

Have fun setting up your plentymarkets system and sending out routine emails in the blink of an eye.

--
//end::transkript[]
