= Saving eBay business policies
:lang: en
include::{includedir}/_header.adoc[]
:position: 10020
:url: videos/ebay/settings/business-policies
:id: LMJ5PWJ
:author: team-multi-channel

//tag::introduction[]
[cols="2, 1" grid=none]
|===
|eBay shipping profiles tell customers how they will pay for items on eBay, how these items will be shipped, and how customers can return items they don't want to keep. Learn how to easily create and manage eBay shipping profiles in your plentymarkets system!
|<<videos/ebay/settings/business-policies-payment#video, Terms of payment (2:02)>>

<<videos/ebay/settings/business-policies-shipping-conditions#video, Shipping conditions (3:01)>>

<<videos/ebay/settings/business-policies-return-policy#video, Return policy (3:48)>>

<<videos/ebay/settings/business-policies-shipping-profiles#video, Shipping profiles (4:14)>>

|===
//end::introduction[]

video::198655889[vimeo]

// tag::transcript[]
[.collapseBox]
.Transcript
--
Our eBay puzzle is starting to take shape. Now let's learn how to create shipping profiles, which tell your customers how you handle payment, shipping and returns.

In other words, let's learn how to create business policies!

By now, your interface is live and you've linked all of your eBay accounts.

From here, you'll easily be able to find the “Business policies” menu a bit farther down in the navigation bar. Here, you can save important information about payment, shipping and returns.

And then you can combine all of this information into a shipping profile. But what is a shipping profile anyway? Don’t confuse it with the regular shipping settings that you save elsewhere in your plentymarkets system.

Instead, think of eBay shipping profiles as a way to tell customers how they should pay for their items on eBay, how these items will be shipped, and - in worst case - how customers can return any items that they don't want to keep.

So for example, you may want to tell customers that you accept payments via PayPal and that you ship items with Royal Mail.

You’ll simply combine this information into a so-called “shipping profile”, which your customers will see when they buy your items on eBay. Of course, one size may not fit all! You may want to use different payment or shipping conditions for different items. No problem! In plentymarkets, you can create as many shipping profiles as needed.

Up here, just decide which eBay account and country platform you want to create business policies for.

Just remember that any time you make a change up here, you’ll need to click on the little gear-wheel icon to reload the menu.

OK, and one last thing to keep in mind is that your business policies here in plentymarkets are the same as your business policies on eBay. In other words, if you’ve already saved business policies on eBay, then you can click on this download arrow here to import them into your plentymarkets system. Or alternatively – you can create new policies directly in plentymarkets. Either way, just make sure that in the future, you only make changes to your business policies in plentymarkets. This  ensures that both plentymarkets and eBay will be informed of any changes. And it also gives you the comfort of managing data in one, central location.

Alright, so now let’s take a look at the information saved here from left to right. First up, payment conditions.

Just click on the “New” tab and enter a name for your terms of payment.

Then use this field here to specify how customers should be allowed to pay for their items.

If you selected PayPal up here then you’ll also need to tell plentymarkets which PayPal account you want it to use. And don't worry if you're not completely sure how to link your PayPal account with plentymarkets. That topic is covered in our other online reference materials.

If you decide to use the function “Immediate payment”, then you’ll only be able to offer PayPal. That’s simply because of the way that eBay has designed its checkout process.

Last but not least, you can enter payment instructions for your customers to see. Of course, which text you enter is completely up to you.

Just save your changes and the payment conditions are created in plentymarkets as well as on eBay!

As you can see, our puzzle is easily put together! The procedure is nearly identical for shipping and return conditions.

Just like before, click on the “New” tab and enter a name for your shipping conditions.

Then use this drop-down menu here to specify how many days you’ll need to prepare the item for shipping. But don’t get confused – this number doesn’t include the delivery time. It’s not possible to specify a delivery time here in these settings.

Finally, you can provide information about your domestic shipping options.

And if you also provide international shipping with eBay, then you can save this information as well.

If you want your customers to be able to choose between multiple shipping methods, then enter all of them here.

Or, you could also create a new set of shipping conditions for every shipping method that you offer.

Now let's take a look at the "Return policy".

Just like before, you'll start out by giving your return policy a name and then you'll write a description for it.

Down here in the drop-down menus, you’ll first specify whether items can be returned at all.

And then you’ll specify how long returns are accepted and who pays the return costs.

When you click on the save icon, you'll have completed all three pieces of information.

Now you’re ready to combine this information into a shipping profile.

As always, start out by entering a unique name. And just as a side note, these names that we've been entering will become especially important if you create several different profiles because this is how you'll tell them all apart.

A bit further down, you'll need to enter the postcode and city where your company is located.

Then you'll use these three drop-down menus to select the payment, shipping and return conditions that you just created. And really, that’s all there is to it!

But before leaving the menu, you may want to look at the “Buyer requirements”. These settings are useful if you want to prohibit specific customers from buying your items.

For example, you may want to exclude customers who don’t have a PayPal account or customers who live in a country that you can’t deliver items to.

And it's as easy as that!

Your eBay puzzle is starting to take shape! I'm sure you're raring to go and excited to add the next piece to your puzzle.

Go ahead and watch the next tutorial in this series where you'll learn how to link shipping profiles to your listings and prepare items for being sold on eBay.
--
//end::transcript[]
