= Introduction to personalisation
:lang: en
include::{includedir}/_header.adoc[]
:position: 10010
:url: videos/personalisation/company-data
:id: ZLZJIAI
:author: team-crm

//tag::einleitung[]
[cols="2, 1" grid=none]
|===
|Add your own corporate image to plentymarkets! Learn how to display your company letterhead on important documents and create your very own email signature. See where you can save bank information and master data about your business.
|<<videos/personalisation/company-data-document-templates#video, Document templates (0:09)>>

<<videos/personalisation/company-data-email-signature#video, Email signature (1:05)>>

<<videos/personalisation/company-data-bank-master-data#video, Bank and master data (2:29)>>

|===
//end::einleitung[]

video::193685800[vimeo]

// tag::transkript[]
[.collapseBox]
.Transcript
--

Before your business opens its doors to customers, you'll want to make sure that you've saved some basic information about your company behind the scenes. First, I'll show you how to save your company letterhead on the documents that you send to customers. You can find the area for saving this information by clicking on the menu "Locations", then by opening whichever location you want to work with and clicking on "Documents".

In this menu, you can save your company information and logo on documents like the invoice.
Here in this first tab, you'll see several text fields.
You can either continue using the default text that's found here or you can modify these fields as needed.
Next, click on the "PDF template" tab and upload a PDF file of whatever company letterhead or stationery you want the document to be printed on. Now you can click on the "Preview" icon to see what your invoice looks like with your company letterhead.

Next you'll also want your company information to appear at the end of emails that you send to customers. To do so, you'll need to save your company information in a so-called email signature.
On the one hand, you could either enter this company information at the end of every single email template that you send to customers.

Or a much simpler solution would be to use a placeholder - or in other words, a template variable for your signature. If you're not familiar with the concept of template variables, they're an easy way to manage information in one, central location, and then have this information appear in several different emails. So where can you find this one, central location where information is saved? Well, just navigate to the "Signature" menu and and save your company information in the text box here.

So this way, if you ever need to make changes to your email signature in the future, then you'll only have to make changes in this one, central location, and then the changes will automatically go into effect in all of your emails at once.
Just one last thing to note.
Make sure that you enter the template variable called "Signature HTML" if you send email templates in HTML format or use the template variable called "Signature Text" if you send email templates in plain text format. Either way, when your customers place an order, they'll receive a confirmation email that includes your signature.

Last but certainly not least, let's take a quick look at the "Settings" menu. Here you'll need to enter information into the menus "Master data" and "Bank". The information that you enter into these two menus will be used for several different functions within plentymarkets. For example, when you create a shipping label or when you give customers your bank account information so that they can pay for items with a wire transfer.

Well done! You've made it! You've taken your first steps toward saving your own company information. Once you're ready, I hope you'll join me with the next video, where we'll dive even deeper with plentymarkets!

--
//end::transkript[]
