= Manually creating eBay listings
:lang: en
include::{includedir}/_header.adoc[]
:position: 10020
:url: videos/ebay/listings/create-listings
:id: PWB6PBM
:author: team-multi-channel

//tag::introduction[]
[cols="2, 1" grid=none]
|===
|This video looks at several different item settings which are important for eBay. It teaches you how to configure these settings and how to convert your item data record into a listing.
|<<videos/ebay/listings/create-listings-prepare-items#video, Preparing items to be sold on eBay (0:27)>>

<<videos/ebay/listings/create-listings-ebay-listings#video, Turning items into eBay listings (2:57)>>

|===
//end::introduction[]

video::202024746[vimeo]

// tag::transcript[]
[.collapseBox]
.Transcript
--
Our eBay puzzle is really coming together now. We've made great progress so far and we're ready to knock out the next piece. So let's get going and take a closer look at the actual items that will be sold on eBay.

We've recently added a rubber duck to our product portfolio. But before we start showing him off to customers, let's make sure he's looking his best. Since we want as many customers to buy the item as possible, we need to make sure that it includes all of the settings that are necessary for eBay.

Alright, so first - logically - it's only possible to sell an item on eBay if it's active in plentymarkets.

So the first thing you'll need to do is go into your item data record and make sure that you've checked this option right here. And just as a side note: if you want to sell multiple variations of this item on eBay - so for example a red, blue and green duck too - then you'll need to make sure that you've activated each of these variations.

Second, you'll need to make sure that your sales prices are ready to go. So you'll either need to link your item's existing sales price with eBay. Or, a bit simpler, you can create a completely new sales price that's only for eBay.

So just head on over to the menu "Settings » Item » Sales prices" and check whether you have an existing price that you want to use for eBay.

Or click on the "New" button to create a price exclusively for eBay.

Either way, just make sure that you select the referrer eBay and select your eBay account.

Before leaving this menu, you should also take a look at two other settings. First up, the price type. For eBay, the basic rule is just to make sure that you haven't checked any of these boxes here. At least when you're first getting started.

If you want to add a recommended retail price at some point too, then make sure that you've already saved another sales price that goes along with it. This is because the recommended retail price is essentially just decoration. It's just something that's displayed in red strike-through text next to the actual price.

The other setting that you should look at in this menu is the client.

If you work with multiple clients, then you'll need to make sure that your standard - or default client - was selected here too.

Now let's jump back over to our item and fine-tune the last few settings.

First, you'll want to look at the content of your item. If you're planning to sell multiple variations of the item on eBay, then just make sure that all of your variations have the same content. So for example, if you're selling something like wine glasses, then you won't be able to have variations of 3, 6 and 9 glasses. So take a look at which variations should be used in your listing and make sure that they all have the same content.

And lastly, we'll switch over the the "Availability" tab and add whichever eBay platforms we want this item to appear on.

You can either select all of the eBay country platforms in general or you can get more specific and choose which exact platforms you want to work with.

Don't forget to save your settings when you're done.

Now that we've got our duck looking sharp, we're ready to send him out into the world. In other words, we're ready to list him on eBay and have customers start their bidding.

We can turn our item into an eBay listing by clicking on this icon up here and configuring the settings in the pop-up window.

First, we tell plentymarkets which market or even markets, we want to sell our duck on.

And then of course, we can also choose which eBay country platform we want to use.

Now let's take a look at the right side of this window.

Up here, I see the type. Since we're setting up an eBay listing, we can either make customers face each other head to head in an "Auction" or we can keep things a bit more relaxed with a "Fixed price".

"Shop item" is only relevant for the market Hood, so you can just ignore this one for now.

This option here is really just a visual aid for your customers. It doesn't affect your stock in any way. Rather, it just tells customers how many components are included in the item.

So for example, you may sell a pack of 10 pencils or a 6-pack of cola.

This next option here is really important. Before you start selling this item, you'll want to decide whether your auction should only be visible to customers when you have sufficient stock.

In the simplest terms, just decide whether you want to risk overselling the item or if you'd rather not.

But watch out! Do you remember configuring the automatic stock update for your eBay interface?

Well, if you choose "unlimited with synchronisation" or "limited without reservation", then you'll need to have activated the automatic stock update in the initial settings.

Here you can see how all of the puzzle pieces link together to form one big picture.

Alright, we're making good headway. If you're creating a fixed price listing then you can place a check mark here to make sure that your item is sold on eBay for the same price that's also listed in your item data record.

In other words, do you remember the hourly price synchronisation that we configured for our interface? Well, the price will only be synchronised every hour if you've placed a check mark here.

The advantage of this option is that if you ever change the price in your data record, then it will automatically be updated on eBay too.

Down here, you can choose which number you want to use as the item number in your listing. Which option you choose here depends mainly on which eBay country platform and which category you want to list your item in.

But in the UK, it's pretty typical to use the UPC.

Lastly, remember how we talked about the content of your variations earlier in this video?

Well, if you had variations with different content, then you'll need to specify which one your listing applies to.

It's as easy as that! The new listing is created and displayed in an overview.

Once you're ready, you can edit your listing even further and finish off this portion of the puzzle.
--
//end::transcript[]
