= Dialogue - Letting employees decide how a process continues
:lang: en
include::{includedir}/_header.adoc[]
:position: 100110
:url: videos/automation/processes/dialogue
:id: YEBGNVN
:author: team-mobile

//tag::einleitung[]
[cols="2, 1" grid=none]
|===
|Put your employees in the driver's seat! Use the control element dialogue to ask your employees a question and have them choose the best answer.
|

|===
//end::einleitung[]

video::227218743[vimeo]

// tag::transkript[]
[.collapseBox]
.Transcript
--
If this, do that. Four simple words that sum up Dr. Process' next superpower. If an item's small, ship it one way. If it's large, ship it another way.
Sounds kind of like a split, right? Well, pretty close. A dialogue can be thought of more or less as a split with a few extra options.
Just like a split, a dialogue is also a fork in the road, which allows you to send your process down different paths. But this time, which path an order takes depends solely on what your warehouse technician decides to do.

So in other words, the dialogue asks your warehouse technician a question - for example "how will you ship this item?"
And your employee answers the question by clicking on a button.
The process then continues down one path or another, depending on which button was clicked on.
Pretty simple, right? You can customize this control element just as easily.
Simply use this area up here to write the question that you want to ask your employee.
And then add a button for every possible answer.
Here you'll enter text for the answer - in my case, different ways of shipping items.
And here you'll tell plentymarkets where the process should continue if this answer is chosen.

Before we see this control element in action, I'd like to mention one other difference between split and dialogue. Whereas split only lets you send your process down two different paths, you can use dialogue to branch your process into three, four or even five different paths.
Here I've added new procedures and sub-procedures that help me fulfill orders with Amazon Prime.
And here I've added another button to my dialogue, which allows my warehouse technician to choose Amazon Prime as a shipping option.

OK, let's try out the process and see what happens.
Your warehouse technician will start out by searching for whichever order is currently being fulfilled.
Once plentymarkets has found the correct order data, our dialogue springs into action.
Your warehouse technician reads the question and picks the appropriate answer.
The process then continues on down whichever path was chosen.

Now that you understand how the dialogue works, let's see how it fits into a more complex process.
Here in this process, our warehouse technician searches for a pick list and then scans the items on that list. If something goes wrong - for example if one of the items isn't in stock, then our warehouse technician will just click on a button, which leads down to a filter and then ultimately down to our dialogue.
The dialogue here is set up so that our employee can indicate what the problem was.
For example, the item is out of stock or maybe the warehouse technician mistakenly clicked on this button and wants to go back.

If the item is out of stock, then the order continues down this path here, where its status will be changed, it will be removed from the process and the warehouse technician will return to the item registration window.
On the other hand, if our employee clicks on cancel, then we'll follow the path to the right, where the filter will be reset and the item registration window will appear again.

Now it's your turn! Try adding dialogues and see how they allow employees to engage and interact with your processes!
--
//end::transkript[]
