= eBay in three easy steps
:lang: en
include::{includedir}/_header.adoc[]
:position: 10010
:url: videos/ebay/ebay-introduction
:id: K6K9ZBZ
:author: team-multi-channel

//tag::introduction[]
[cols="2, 1" grid=none]
|===
|Did you know that you can control your eBay sales from within plentymarkets? It's easy as 1-2-3! This video gives you a quick overview of how to link your account and start auctions. More detailed explanations of the settings can be found in our other eBay videos further below.
|<<videos/ebay/ebay-introduction-link-account#video, Linking your eBay account to plentymarkets (0:23)>>

<<videos/ebay/ebay-introduction-preparing-items#video, Preparing items to be sold on eBay (1:29)>>

<<videos/ebay/ebay-introduction-creating-listings#video, Creating a new listing (2:12)>>

|===
//end::introduction[]

video::196548931[vimeo]

// tag::transcript[]
[.collapseBox]
.Transcript
--
Want your items to reach a wider audience? Then it's time to start thinking about eBay! With plentymarkets, you can list your items on eBay and manage the entire process from one central location.

Sit back and join me on a quick tour through the basic settings that you'll need to configure when you begin listing products on eBay. The settings are easy as 1-2-3!

The first thing you'll need to do is link your eBay account with plentymarkets.

So just navigate to the menu System » Markets » eBay » Accounts and click on the plus icon to link your eBay account with plentymarkets.

In the new window, enter your eBay user name and select your country platform.

Then click on the gear wheel icon when you're finished.

You'll be forwarded to eBay, where you'll need to enter your login details and go through the authentication process. Congratulations, your account is active.

Next, let's take a quick look at eBay business policies.

This is where you can decide on the terms of payment, shipping conditions and return policy that should apply to your eBay customers.

Up top, just select your eBay account and eBay platform.

Now you can create business policies in your plentymarkets system and then combine these individual policies into a single shipping profile, which your eBay customers will be able to see along with every item that you list.

Now let's move on to the second step, where we'll focus on items.

Just navigate to the menu System » Item » Sales prices and open whichever price you want to use for eBay.

First, link the referrer eBay and second, link your actual eBay account.

Alright, now open the item overview, click on whichever item you want to list on eBay and then click on the "Availability" tab.

Here you'll need to specify which markets this item should be available on.

As always, don't forget to save your settings.

And now for step number three.

Let's create a listing for this item. This is done by clicking on the little plus icon up here.

First, decide whether you want to create a regular auction or whether you want the item to be sold at a fixed price.

Next, decide how you want to manage stock levels for your auction. If you want to manage your stock later, simply select 'unlimited (without synchronization)'.

Or you can limit the number of items you sell on eBay to the number of items that you actually have in stock. This will prevent you from overselling items.

Next, decide whether you want eBay to use whatever price was saved for this item in your plentymarkets system.

Lastly, select the market "eBay" and specify which platform the listing should appear on.

The new listing will be created when you click on Save and it can be customised down to the last detail.

Here on the left, you can decide how long your listing should run and you can decide the maximum amount of item copies that should be sold.

On the right, you can specify which VAT rate should apply to the listing and you can link the shipping profile that you defined in your eBay business policies.

Now you're ready to switch to the "Market" tab and save a few settings that only apply to eBay.

Start out by clicking on the magnifying glass and linking your item to whichever eBay category it should appear in.

Next, specify your item's condition and save your changes.

Last but not least, use this function up here to check your listing for any possible errors.

Once you've passed the test, specify that the listing is ready for use and start it by clicking on the play icon up here.

Like I said, it's easy as 1-2-3. Your item is now available on eBay and sales can start rolling in.

So what's up next? Just check out our other eBay videos for more in-depth explanations of the topics covered in this tutorial and have fun setting up your eBay listings in plentymarkets!
--
//end::transcript[]
