= Import and reply to eBay feedback in your system
:lang: en
include::{includedir}/_header.adoc[]
:position: 10050
:url: videos/ebay/plugins/ebay-feedback
:id: SYGDEBV
:author: team-multi-channel

//tag::introduction[]
[cols="2, 1" grid=none]
|===
|The eBay feedback plugin allows you to remain up to speed on what your customers think of your offers. And you can respond to feedback just as easily from the comfort of your system.
|<<videos/ebay/plugins/ebay-feedback-download#video, Download the eBay feedback plugin (0:12)>>

<<videos/ebay/plugins/ebay-feedback-setup#video, Set up eBay feedback (0:45)>>

<<videos/ebay/plugins/ebay-feedback-read-respond#video, Read and respond to feedback (2:08)>>

<<videos/ebay/plugins/ebay-feedback-event-procedure#video, Set up an event procedure (2:23)>>

|===
//end::introduction[]

video::272912886[vimeo]

// tag::transcript[]
[.collapseBox]
.Transcript
--
You've managed to navigate the unknowns of e-commerce successfully thanks to your quick wit and wealth of experience. But some things are difficult to know. That's why you rely on customer feedback to tweak your offers on eBay.

Just head on over to the plentyMarketplace and grab the eBay feedback plugin. This handy tool automatically imports unanswered feedback into plentymarkets once a day where you can respond to comments directly from the comfort of your system. No unnecessary login required!

And just a head's up, feedback is imported via your ticket system so make sure it's included in your plentymarkets module package and that you've already set up the essentials beforehand.

As you can see, you'll also need these two plugins down here to re-link your eBay account to your system and ensure that communication between your system and eBay goes smoothly.

(SLOW) Once the plugin is up and running in the productive mode, the eBay feedback function will soon appear HERE.

Now depending on whether you're a glass half-empty or half-full kind of person, select the type of feedback you want or simply select them all.

Since you've already set up the fundamentals in your ticket system, it's time to link the right client, ticket role, ticket type, and status. Linking this data ensures that the info is imported properly from eBay to plenty and that your response is sent back to the right recipient. So make sure you've set up that data correctly in your ticket system beforehand.

To map the feedback types, you'll first have to set up the right tags.

So you'll need to create a POSITIVE tag and link it to your ticket system. As well as create neutral and negative tags.

After a quick system refresh, map the tags correctly with the feedback types here.

Now link the right users so they can process this feedback. Just make sure you've authorised your employees to access the ticket system in their user accounts beforehand.

Alright, since the whole point of this plugin is to bring outside information into plentymarkets, you'll need to activate the ticket import.

Once saved, the eBay feedback import is ready to go!

But obviously it's not enough to just know what your customers are thinking. You need to interact with them as well.

So you'll obviously read the feedback. And then simply reply to it in the ticket itself via the "Add message" button.

But hold on a sec. If feedback is automatically imported into your system, then it makes sense that your responses are sent out automatically as well. That's where an event procedure comes into play. Check out how event procedures work in this video.

Give your NEW event procedure a name and select the event that triggers the procedure that answers eBay feedback.

Also, to make sure your system doesn't sift through ALL of your existing tickets, set up a filter that specifies a type or status of ticket and only goes through new eBay feedback.

And for the event procedure to work make sure it's active.

Right on! With your new eBay feedback plugin you'll instantly be up to speed on what your customers think of your offers and can respond to feedback just as easily. Enjoy the e-commerce adventures that lie ahead.
--
//end::transcript[]
