= Linking your eBay account to plentymarkets
:lang: en
include::{includedir}/_header.adoc[]
:position: 10010
:url: videos/ebay/settings/ebay-account
:id: AFOMWXF
:author: team-multi-channel

//tag::introduction[]
[cols="2, 1" grid=none]
|===
|Learn how to link your eBay account with plentymarkets and check which settings your interface is running with.
|<<videos/ebay/settings/ebay-account-interface-setup#video, Setting up the interface (0:36)>>

<<videos/ebay/settings/ebay-account-settings#video, Account settings (1:55)>>

<<videos/ebay/settings/ebay-account-initial-settings#video, Initial settings (3:26)>>

|===
//end::introduction[]

video::198652645[vimeo]

// tag::transcript[]
[.collapseBox]
.Transcript
--
eBay - a short name, but a big topic. plentymarkets gives you a wide range of eBay settings, which can be customised to meet your needs. But don't get overwhelmed by all the options. Instead, imagine eBay as one big puzzle. All of the separate pieces join up to form a whole. We'll look at each piece individually and you'll see how they link together as one big picture.

Let's start by looking at a key piece of the puzzle that connects to lots of other things around it.

In other words, let's look at the interface to your eBay account. It allows plentymarkets and eBay to communicate with each other.

Once you're ready to set up the interface, just open up plentymarkets and navigate to the menu "System » Markets » eBay » Accounts".

Here you can see all of the eBay accounts that are already linked to your plentymarkets system, and you can also add new accounts. Because of course, part of having sales run smoothly is being able to manage all of your eBay accounts directly within plentymarkets!

In the new window, enter your eBay user name and select a different country platform if needed.

If you're just getting started, then you might want to check this option here. This will prevent orders from being imported into plentymarkets just yet and it will give you time to finish configuring your settings and finding your way around.

Simply click on the gear wheel icon when you're finished.

You'll be forwarded to eBay, where you'll need to enter your login details and authorize plentymarkets to communicate directly with your eBay account. This step generates a unique ID, called the token.

Don't forget to renew your eBay token before it expires.

The first piece of the puzzle is complete! Now, you could start managing eBay listings straight away. But for the sake of clarity, let's break down the eBay interface into even smaller puzzle pieces and see which settings your interface is currently running with.

First, let's concentrate on the "Account settings" which are saved separately for every eBay account.

Remember that check box you clicked just a moment ago? Once you're ready to start managing your eBay sales in plentymarkets, just come back here and tell plentymarkets which eBay platform it should start retrieving sales from.

Orders will be imported into plentymarkets and managed here as usual.

Alright, now keep in mind that in a puzzle, everything is linked together. You may want - or even need - to customise some of the interface settings, depending on how you set up your listings and how you manage your stock.

The hourly price synchronisation is a good example of an option that only fits in our puzzle depending on how you want to combine it with other pieces.

When you create listings, you're able to tie the price of your offer to the price of your item. If you've done so and you also use the hourly price synchronisation then any time that you make changes to an item's price, these changes will automatically be transferred to eBay within an hour.

These options here are another feature that can save you time and energy. If you use the plentymarkets ticket system, then you'll want to look at these settings, which allow you to have your customers' eBay messages imported into plentymarkets as tickets. This saves you from having to switch back and forth between plentymarkets and eBay when you provide customer service.

Keep in mind that there are lots of other little puzzle pieces in this menu, which you can mix and match to form a picture of your business and its unique fulfilment processes.

But for now let's switch over to the "Initial settings" tab and see what's going on here. You can think of the initial settings as the edge of your puzzle because they apply to all of your eBay accounts equally.

Here I especially want to mention the SKU - or stock keeping unit. This number is used to synchronise important information about your items. If you leave this option set to "No", then plentymarkets will be instructed to use the market-listing ID and variation ID for your SKU, rather than the variation number. We recommend that you leave this option set to "No" so that you don't encounter any problems with the synchronisation.

Now let's take a look at this option down here. If you select "Yes", then as soon as you book an item as outgoing, plentymarkets will notify eBay that the item was shipped and it will also transmit the package number. So if you select "Yes" here, then make sure that package numbers are saved for eBay orders before you book items as outgoing.

Again, remember that everything is connected in a puzzle. The automatic stock update is another option that only fits in our puzzle depending on how you want to combine it with other pieces. It comes into play depending on how you want to manage stock levels in your listings.

Now that you've linked your eBay account to plentymarkets, let's work on another part of the puzzle and see how things like business policies, item settings and listings fit into the big picture for eBay.
--
//end::transcript[]
