= Manually editing eBay listings
:lang: en
include::{includedir}/_header.adoc[]
:position: 10030
:url: videos/ebay/listings/edit-listings
:id: NLT7A33
:author: team-multi-channel

//tag::introduction[]
[cols="2, 1" grid=none]
|===
|Learn how to edit the basic settings, description and marketplace settings for your eBay listings. At the end of this video, you'll be ready to start your listings on eBay.
|<<videos/ebay/listings/edit-listings-basic-settings#video, Saving basic settings (0:21)>>

<<videos/ebay/listings/edit-listings-description-layout#video, Editing the description and layout (1:58)>>

<<videos/ebay/listings/edit-listings-specific-options#video, Configuring eBay-specific options (2:44)>>

|===
//end::introduction[]

video::202026068[vimeo]

// tag::transcript[]
[.collapseBox]
.Transcript
--
We're making great progress on our eBay puzzle. Only one piece left before customers start bidding on your items and sales start rolling in!

In plentymarkets, listings are grouped together in an overview. Here you'll need to put the finishing touches on your listings before they go live.

So just open whichever listing you want to work with and then configure the settings in these three tabs.

Let’s look at each tab individually, starting with the “Base” tab – or the area for saving basic information about your listing.

Imagine you’re sitting in front of a blank piece of paper and are sketching out just what your auction should look like. You’ll probably start out by deciding the nuts and bolts of your auction, so things like the starting price, how long your auction will last, and how your item will be shipped to customers.

These basic facts are all spelled out in your listing’s “Base” tab.

This area up here primarily includes the same options that you saw when creating your listing.

But there are a few new options here as well. For example, you can use this drop-down menu to tell plentymarkets which eBay account it should use.

Most of the new options, though, are found in the lower portion of the screen down here.

For example, you can specify how long you want your auction to last.

Or if you're selling the item for a fixed price, then you can make the offer good til cancelled.

And you can also choose whether you want your auction to automatically be restarted again once it has ended.

This option here lets you give customers the impression that supplies are limited.

Just note that if you activated the automatic stock update while configuring the eBay interface and your listing either uses the stock dependency "unlimited (with synchronization)" or "limited without reservation", then the automatic stock update will rely on the number entered here.

The VAT rate is a mandatory entry. But keep in mind that it's only displayed for some eBay categories and it isn’t actually subtracted from your price. The VAT is simply displayed along with the listing.

This option down here is a good example of how all the pieces of the puzzle come together for eBay. Here, select one of the shipping profiles that you set up in your eBay business policies.

Now that you’ve decided which basic information should be shown to customers, you’re ready to format this information by adding design elements and writing a unique description.

So essentially, the "Description and layout" tab is where you'll enter the title, subtitle, and description for your listing. You'll notice that plentymarkets has gotten you started by automatically entering the name and description from your item data record. But you can make changes to these texts if needed.

If you're looking for more advanced options, then you may prefer to work with layout templates. Or if you're not so great with code, then you can work with a graphic design agency and have them create attractive layouts for you.

And just pay attention to what information is included in your template. For example, if your layout template includes a description, then of course, you won't need to enter one here too.

The listing is really starting to come together now. We've saved some basic information and given it an attractive layout. Now we're ready to add a few eBay-specific elements, such as the eBay category and a hit counter.

Let's get right to it and look at the "Market" tab.

Up here, we can search for and select the most appropriate eBay category for our listing.

And as soon as you've selected an eBay category, you'll be able to specify the condition of your item down here.

You can customize the rest of the settings here to meet your needs.

For example, these two fields here allow you to automatically reject and accept best offers from your customers.

And down here you can decide whether you want to use eBay's "Gallery" and "Featured first" services for an extra charge.

Down here you can specify whether this listing should use eBay Plus or you can go with the basic setting, which means that plentymarkets will just use whatever eBay Plus setting you saved when configuring your interface.

And here, you can add the properties that are recommended or sometimes even required for certain eBay categories. This can be thought of as just a way to add additional info about your item.

For example, you may want to add a recommended age for a rubber duck or specify which country the duck was manufactured in.

Once you've finished saving your settings, you'll want to click on this link up here to check the configuration. In other words, you'll want to check and make sure that you haven't accidentally selected any options that contradict each other.

If settings are incorrect or are missing, then you'll see an error message that tells you what still needs to be done. But in best case, you'll see a green check mark, which tells you that your settings are correct.

Now you're ready to save one last setting before your puzzle is complete. Just head back over to the "Base" tab, place a check mark next to the words "Ready for use", and save your settings.

It's now possible to start your listing by clicking on the play button up here.

Well done! You've made it! Your product is on eBay! Once you've got the hang of it, you may be curious about some of the more advanced eBay options. We've got you covered! Just check out the rest of our video tutorials and have fun working with plentymarkets!
--
//end::transcript[]
