= Adding extra information to your sync
:lang: en
include::{includedir}/_header.adoc[]
:position: 10010
:url: videos/data-transfer/extra-features/extra-information-sync
:id: A7WFYLS
:author: team-import-export

//tag::einleitung[]
[cols="2, 1" grid=none]
|===
|You want to import a file into plentymarkets, but it's missing a few key pieces of information? No need to modify the file by hand! You can use ElasticSync's "Own Value" function to add missing information to your sync. +
*_Note:_* The term *ElasticSync* is outdated and has been replaced by *import*.
|
|===
//end::einleitung[]

video::329761403[vimeo]

// tag::transkript[]
[.collapseBox]
.Transcript
--
Your supplier sent you a new file, chock-full of product data!
But, wait a minute. The data isn't quite right. Some pieces of information are missing and need to be added to the file.

Let me show you what I mean. Imagine you've got a spreadsheet, which lists a bunch of item IDs and how many copies of each item you've got in stock. Well, unfortunately, plentymarkets won't understand this quantity on its own.
Instead, it also wants to know where you've got these items. So, which warehouse you're storing the items in and more specifically, which storage location within that warehouse.
Simply take a look at our online manual, if you're not sure which information needs to go together.

Just like you can add a new column to a CSV file and fill in your own values, you can do the exact same thing with ElasticSync!

This video builds on what you've already learned in our basic instructional video and looks at this option here, which adds custom information to your file.
All you need to do is tell plentymarkets that you want to add your own value or symbolically speaking, that you want to add a new column to your file.

Then tell plentymarkets what the column will be used for.
Finally, tell plentymarkets which value it should fill into the column. So in this example, the warehouse.

And then you can do the exact same thing again to add your own value for the storage location.

Here, you'll need to tell plentymarkets the storage location ID. For example, 0 for your default storage location.
Just one last word to the wise. You'll use an ID to tell plentymarkets which storage location you're referring to.

Simply open up the "System" menu and look up the storage location ID. Alternatively, you can use 0 for the default storage location.

Good job! You've added the missing information to your file and now you're ready to import all of this product data into plentymarkets!
--
//end::transkript[]
