= Keeping track of your FBA orders
:lang: en
include::{includedir}/_header.adoc[]
:position: 10050
:url: videos/amazon/orders/fba-orders
:id: CJXGOJP
:author: team-multi-channel

//tag::introduction[]
[cols="2, 1" grid=none]
|===
|Want Amazon to fulfil orders on your behalf? And want plentymarkets to keep track of these orders? Simply configure a few settings in your system and you'll always be in the loop!
|<<videos/amazon/orders/fba-orders-warehouse#video, Creating an FBA warehouse (1:18)>>

<<videos/amazon/orders/fba-orders-settings#video, Configuring the FBA settings (1:51)>>

<<videos/amazon/orders/fba-orders-products#video, Telling plentymarkets which products are FBA (5:36)>>

<<videos/amazon/orders/fba-orders-event-procedures#video, Creating event procedures (6:20)>>

<<videos/amazon/orders/fba-orders-shipping-items#video, Shipping your items to Amazon and generating reports (6:54)>>

|===
//end::introduction[]

video::314713940[vimeo]

// tag::transcript[]
[.collapseBox]
.Transcript
--
Some travellers don't want to spend hours and hours planning a vacation. Time is money! They'd rather save time by booking an all-inclusive vacation package.

You can think of Amazon in much the same way. When it comes to fulfilling orders, some sellers want an all-inclusive package. If that's you, then you'll need to configure these settings here, so that Amazon is able to fulfil orders on your behalf.

On the other hand, if you'd prefer to be your own tour guide, then you'll need to configure the MFN settings, so that plentymarkets knows how to deal with the sales you made on Amazon.

This video focuses on Amazon's all-inclusive fulfilment package called FBA.

Sellers can book this service if they'd like to store their products in Amazon's warehouse and then have Amazon fulfil orders on their behalf and ship packages for them with the Prime label.

Once you've signed up for FBA, you'll need to create an FBA warehouse in your plentymarkets system and configure a few other relevant settings.

You'll need to tell plentymarkets which of your products will be fulfilled by Amazon.

And you'll need to create an event procedure, which automatically sends invoices to your customers.

Finally, you'll ship your inventory to Amazon, where it'll be stored and you'll create reports for your FBA orders.

Okay, let's get down to it.

Since your products will be stored in Amazon's warehouse, you'll need to start out by telling plentymarkets a little bit about this warehouse.

Essentially, you just need to give it a name and specify that it's a so-called "repair" warehouse which is run by Amazon.

Once you've saved the settings the last thing you'll need to do here is pick a location. Or in other words, you'll need to choose the country where you do business with Amazon. So, if you've got an FBA contract with Amazon UK, then you'll pick UK here.

With the warehouse all squared away, head on over to the "Markets" menu and then navigate to the Amazon settings.

Now click on the "Order settings" tab, scroll down to FBA and check this option here to make the other options accessible.

You'll need to configure these options here for Amazon FBA.

Don't worry too much about the other options for now. They'll come into play later, if you also want to use Amazon's so-called "Multi-Channel" service.

But for now, just leave the "referrer" option set to "only Amazon orders".

Okay, the status.

Keep in mind that FBA is a service which packs and ships orders on your behalf.

Afterwards, a record of the order will be imported into your plentymarkets system.

And here, you'll specify which status the order should be given when it's imported.

Since Amazon's already fulfilled the order and shipped the item, we recommend picking a status that starts with the number 7.

For example, 7.2.

But just FYI, if you don't see an appropriate status in this drop-down menu, then you can create one in the order settings.

Outgoing items is really similar. Again, since Amazon fulfils orders and ships items on your behalf, it makes sense that your record shows the outgoing items as already having been booked.

The "warehouse" option is also pretty easy to understand. Just pick the FBA warehouse that you created a moment ago.

One advantage of FBA is that Amazon provides customer service and handles any returns. But what if you still want to stay in the loop and see what sort of items are being returned to Amazon or refunded with credit notes?

In this case, just tell plentymarkets that it should import records of all these returns and of all these credit notes.

This option here is another way to stay in the loop when Amazon customers return items. In this case, if your customer paid for the item on Amazon with a gift card and now your customer wants to return the item, then this option here will make sure that a record of the gift card lands in your plentymarkets system.

Finally, we recommend that you use the automatic hourly stock import. This function here will help you keep track of how much inventory you've got in Amazon's warehouse. It helps you know when you're running low and need to reorder a product.

Once you've finished configuring the options, head on over to the "Settings" tab and take one last look at the "Initial settings" area. Have you configured everything here correctly?

If you run several different stores, have you already used this option here to specify which store your Amazon orders are attributed to?

How about this option? Have you decided how you'd like to calculate VAT for your invoices?

Since calculating VAT is quite complex, you may want to use Amazon's VAT calculation service and have them do it for you.

If you'd like to use Amazon VCS, then you'll need to book the service within your Amazon account and then select the option in plentymarkets. Just note that this function is still in the process of being developed.

Once you've finished configuring all of the settings in these three tabs you're ready to activate the Amazon interface and save your settings.

Next, you'll need to tell plentymarkets which of your products should be fulfilled by Amazon.

Simply open whichever products this applies to and click on the "Multi-Channel" tab.

Now select the appropriate region and check this option here.

Lastly, open the item variation and then the "Availability" tab.

Here, you'll need to add "Amazon FBA" to the list of markets where this item is available.

Just FYI, if you need to activate FBA for several different items, then you'll probably find it quicker to use the group functions.

At this point, you'll want to set up an event procedure, which automatically creates and sends invoices to the customers who buy your Amazon FBA items.

Simply create a new event procedure which automatically generates an invoice whenever you receive a new order from Amazon FBA.

Then create a second event procedure which automatically e-mails this invoice to the customer as soon as it's been created.

You're nearing the finish line. At this point, you're ready to ship your products to Amazon and put them in the driver's seat. Keep in mind that once you've sent your products to Amazon, they'll have complete control over this inventory.

Amazon will decide how many of your items are fit to be sold. So for example, you may send Amazon 60 copies of an item. But if one gets broken along the way, then Amazon may only put 59 of them up for sale.

Once you've sent Amazon your products, you'll want to know how many they've deemed fit for sale. In other words, you'll want to synchronise your own stock level with Amazon.

When you first start using FBA, you'll need to do this manually.

And what that means is that you'll need to log into Seller Central and download a CSV file, which lists all of your inventory.

Then upload this file for your Amazon account.

Later, once you've made your first sale, you'll be able to automatically synchronise your FBA stock levels once a day simply by clicking on this icon here.

But for now, the very last thing you'll need to do, is head on over to the "Reports" menu and tell Amazon how often it should create a report for new FBA orders.

OK, so just select the appropriate Amazon account and then decide how often the reports should be generated. We recommend every 4 hours.

Then click on the gear-wheel icon when you're ready to schedule the FBA order report.

Congratulations! Amazon will now begin fulfilling orders on your behalf.

That is, Amazon will begin fulfilling those orders that were placed on Amazon.

But what about all the orders that are placed in your online store, on eBay, or on a handful of other marketplaces? You can instruct Amazon to fulfil all those orders too! Check out our video on Amazon Multi-Channel and see just how it's done.
--
//end::transcript[]
