= Fulfill your orders with a plentymarkets process
:lang: en
include::{includedir}/_header.adoc[]
:position: 10040
:url: videos/order-processing/processing-orders/fulfill-orders-with-processes
:id: UF2XO4V
:author: team-order-payment

//tag::introduction[]
[cols="2, 1" grid=none]
|===
|Once your order reaches status 5 in your system, you've still got to fetch it from your warehouse, pack and ship it as well as send your customer some essential documents. Create a process in your system to make fulfillment as efficient as possible. Download your process here:
|

|===
//end::introduction[]


video::225269182[vimeo]

File for this video:
link:https://cdn02.plentymarkets.com/pmsbpnokwu6a/frontend/plentyprocess/Pickliste__Rechnung___Versandlab.plentyprocess[Fulfillment process]{nbsp}icon:external-link[]

// tag::transcript[]
[.collapseBox]
.Transcript
--

E-commerce can be a veritable retail paradise. But the Sisyphean fulfillment trap can always sneak up on you and you may wind up being crushed under the weight all those menial tasks.
Good thing you've got plentymarkets processes! Automatically create a pick list and shipping labels and send your customers essential documents. Now fulfilling your orders is a piece of cake!

Now the whole point of processes is that you can customize your system so that it works for you so make sure the process reflects the way you want to run your store. But to help you get started, the process we're working with in this video is available for download in the video description.
Downloaded process are great for getting you started ASAP, but just a head's up: you'll need to configure things like your printer settings and order statuses.

Alright, so right off the bat you can see that this process only includes one work step. Since I just imported this process, I've still got to select the status I want the process to search for, so "status 5 cleared for shipping". Once they're found, it's a good idea to change the status of those orders to "6 currently being shipped".
As you can see, we've included a pick list here. Just delete it if it makes more sense for you to create a pick list in a separate process.

Once you've collected all of your items in your warehouse, the actual cycle of this process begins in this big loop here until all the orders that are run through have been processed.

So the items included in your orders are registered and a shipping label is printed.
If you use DHL Shipping in your shipping centre, your shipping labels are automatically printed and the package number is automatically registered in your order. But whatever shipping service provider you've opted for, you can either use a direct interfaces or create a "Polling" step to communicate with them.

Now you might be wondering why the invoice and delivery note and all other documents are printed after the shipping step and not directly when you first receive the order... Well, creating an invoice locks your order which ensures regulatory compliance. Often sellers create an invoice too early in the order process only to realise shortly after that there's a mistake on it. If the invoice has already been generated, you'd have to create a reversal document to unlock your order and make the necessary changes.
For your customers' sake, include the return form and label in the package. But just so you know, a label kann only be created in this process if your working with DHL Return Online.
