= Linking your Amazon account with plentymarkets
:lang: en
include::{includedir}/_header.adoc[]
:position: 10020
:url: videos/amazon/interface-introduction
:id: DONYMS2
:author: team-multi-channel

//tag::introduction[]
[cols="2, 1" grid=none]
|===
|This video shows you how to set up the MWS interface to connect your Amazon account to plentymarkets. Learn how to find your seller ID and merchant token on Seller Central and where to enter them in your plentymarkets system.
|<<videos/amazon/interface-activate-mws-interface#video, Activating the MWS interface (0:34)>>

<<videos/amazon/interface-merchant-token-seller-id#video, Merchant token and seller ID (1:26)>>

<<videos/amazon/interface-link-account#video, Linking your Amazon account to plentymarkets (1:58)>>

|===
//end::introduction[]

video::196421219[vimeo]

// tag::transcript[]
[.collapseBox]
.Transcript
--
Welcome to the jungle! With your machete in hand, you're ready to brave the thicket of Amazon ...

Thanks to plentymarkets you've got a handy guide that'll get you to your destination.

The first stop on our journey is Interface Place, where two worlds merge together, so Amazon and plentymarkets!

And how will you get there? Well first, we'll traverse the MWS interface, collect the necessary token and seller ID, and safely reach your plentymarkets backend where you will link your Seller Central account.

Before you start out on your journey, you'll need to create a seller account with Amazon and use this data to log into Seller Central.

Alright, so MWS - or rather Marketplace Web Service!

But what does MWS actually do? Well this is essentially the interface that allows data to be exchanged between Amazon and plentymarkets.

Now head on through Seller Central to Settings and User permissions where you will click this button to allow your account to be accessed via the MWS interface.

Just grab the necessary info from our manual. We've provided you with the link here in the video.

And just so you know, our manual also provides a direct link to the MWS interface.

Back in Seller central, enter "plentymarkets" as the developer's name and the developer ID.

Now simply accept the licence agreements and there you go! You've successfully activated the MWS interface! plentymarkets can now access your Amazon seller account.

The identifiers listed here are really important and we'll need to use some of them right away. So copy your Seller ID and the MWS Authorisation Token. The MWS token will later be entered into the Merchant Token field in your backend. Also, if you need this info at a later time, you can simply find it here on Seller Central.

So here, your Seller ID and the token you need.

Now just a head's up. You've got to manually renew your access token before the expiry date ... which can be done here with a simple click of the mouse.

Okay, enough with the prep work! Time to link your Amazon Seller Central account with plentymarkets.

Under system, open the MARKET you want, so AMAZON where we'll enter the SETTINGS you need to link your NEW Amazon account.

Here you'll specify the Amazon platform where your items will be listed.

Once you enter the email address you use for Seller Central, create your new account.

This is where the identifiers from the MWS interface come into play. The Seller ID and the MWS Authorisation Token.

When you're ready to activate the interface, simply place a check mark here. But just hang tight for a bit. This isn't your final stop on your tour through Amazon. It makes sense to activate the interface at the very end when you're sure that you've finished configuring everything correctly.

Now click save and get ready for what's up next.

You'll definitely want your items to be displayed on Amazon and your Amazon orders to be imported into your system.

And maybe you want to use services such as Amazon Prime or FBA.

Alright, so the first stop on your trek through Amazon has been a success! Check out our other videos to get you through the jungle safely!
--
//end::transcript[]
