= Introduction: Order processing step-by-step
:lang: en
include::{includedir}/_header.adoc[]
:position: 10010
:url: videos/order-processing/introduction-order-processing-step-by-step
:id: 4HKI12F
:author: team-order-payment

//tag::introduction[]
[cols="2, 1" grid=none]
|===
|This video gives you an overview of all the different processes that need to be carried out once an item has been purchased. Join us on our tour and see which stops are on the journey!
|
|===
//end::introduction[]


video::214839945[vimeo]

// tag::transcript[]
[.collapseBox]
.Transcript
--
Welcome and thank you for joining us on this factory tour! We'll go on site and see just exactly how an item goes from being purchased to being delivered at your customer's front door.
When your customer buys an item, the order is automatically imported into your plentymarkets system and you can open it to see further information.

And this brings us to the first stop on our tour - the accounting department! Here the order waits until your customers have paid for their items and your employee has saved a record of this payment.
Once payment has been received, it's off to the next station.

The warehouse. Here you can see our warehouse technician hard at work. It's his job to find the item in the warehouse and create all of the necessary documents like the invoice.
Once the item has been packaged it can be sent on its way! Not long now until your customer receives the delivery. As always, this real-life delivery process is also recorded electronically in plentymarkets!

Now the customer decides whether to keep or return the item. If the package is sent back to your business, then you'll complete the process by taking care of the return. If the item was defective, then this may mean making any necessary repairs before the item is fit to be sold again.

Thanks for joining us! Now that you know which stations are on the tour, please feel free to walk around and take a closer look at any of the rooms in our factory. Our employees will be happy to show you around!
