= Introducing ElasticSync
:lang: en
include::{includedir}/_header.adoc[]
:position: 10010
:url: videos/data-transfer/introducing-elasticsync
:id: QXLUN6S
:author: team-import-export

//tag::einleitung[]
[cols="2, 1" grid=none]
|===
|What's ElasticSync? And what does it have to do with communication? This introductory video uses communication as a metaphor for importing and exporting data. Scroll down and watch the rest of the videos in this series to learn more about the tool. +
*_Note:_* The term *ElasticSync* is outdated and has been replaced by *import*.
|
|===
//end::einleitung[]

video::322745095[vimeo]

// tag::transkript[]
[.collapseBox]
.Transcript
--
Communication is key.
Little kids get that instinctively when they speak their first words.
But what does communication have to do with your plentymarkets system?

Well, you can think of communication as a simple exchange of ideas or information.
You communicate with your customers, business partners and suppliers. But you also communicate with your system every time you import or export data.

And that's where ElasticSync comes into play.
You can think of ElasticSync as a sort of Swiss army knife for communication. It helps you import data into your system manually or automatically.

For example, whenever your supplier saves a list of item information, plentymarkets can access this information and then check whether it matches the data in your system.
All you need to do is create a so-called sync.

This video series teaches you all about ElasticSync and how it can help your business conquer day-to-day tasks.
So what are you waiting for? Communication is the key to success with plentymarkets!
--
//end::transkript[]
