= Item structure and import options
:lang: en
include::{includedir}/_header.adoc[]
:position: 10030
:url: videos/basics/item-structure-import-options
:id: EUGNVQC
:author: none

//tag::einleitung[]
[cols="2, 1" grid=none]
|===
|The analogy of a home with a parent and children allows you to easily understand item structure in your system. Also, see what options are available to get items into your system.
|<<videos/basics/item-structure-import-options-first-part#video, Item structure (0:18)>>

<<videos/basics/item-structure-import-options-second-part#video, Import options (2:48)>>

|===
//end::einleitung[]

video::257103395[vimeo]

// tag::transkript[]
[.collapseBox]
.Transcript
--
Now that you have plentymarkets, it's time to get your items out into the e-commerce world. But before you do that, let's talk about some of the basics, so how items are structured, the role that variations and inheritance play - and of course, how to get items into your system by either creating them manually or importing them.

So first off, items and item variations. Think of your item structure as a home, with a parent and some kids. The item itself can be thought of as the family's home where fundamental information that is relevant to everything within that item is stored globally, meaning that it applies to all variations of that item. Every item has a main variation, so a parent, that can pass down characteristics like sales prices to other variations, so its children.

Alright, now to this item, a raccoon motto t-shirt. The global tab contains info such as the condition or manufacturer of an item. And under texts you can provide written information on your item like the name, descriptions and technical data.

When a new item is created, a main variation that cannot be deleted is generated automatically. In the main variation tab, we can instantly see that the item is sold for 29.99. In its role as the parent, the main variation is the head of this whole undertaking and passes down certain characteristics, like the sales price, to its children, so the variations listed here. Now don't forget, sales prices have to be configured beforehand.

So what about these so-called child variations. Well as is the case when you're selling products such as clothing, one item often comes in different colours and sizes. These characteristics are called attributes and are used to create variations such as these three variations in yellow, sizes small to large and these three variations in red, sizes small to large as well.

Now just so you know, the main variation can either be a sellable product or a virtual one - virtual meaning that the main variation is not sold to customers but instead used to manage other variations by using the inheritance function.

Alright, now let's take a peek inside the variation containing the red t-shirt in small. As you can see, the price of 29.99 has been inherited from the main variation. However, if for example the red t-shirt is a bit more expensive than the yellow t-shirt, you can simply deactivate the inheritance function like so, and enter the price you want.

You've also got the possibility of linking the right item image to your variation so that the yellow t-shirt and the red t-shirt are both displayed in their respective colours.

The great thing about working with variations is that it gives you lots of options for structuring the products you offer. And if you need to, you can also change one of several variations in the main variation later. Now just a head's up, you'll have to set up things like attributes before creating your items. Check out our other videos for setting up items in detail.

Just as a single family home does not a community make, you generally need more than one item in your store for a solid business. So how do you grow and get all of your items into your system? Well, obviously you can create an item manually via the New button.

But what if you've already got loads of items in digital format - like let's say your supplier has provided you with item data in the form of item lists. No problem. You've got a couple of different options to import item data into your system under the Data menu. ElasticSync, for example, allows you to import item data from CSV files into your system.

If you're working with dropshipping and receive your data from your supplier in real time, you can also opt for ElasticSync. Simply set up a sync in your system and let plentymarkets do the rest. And since many of you are already selling items on eBay, simply use the eBay listings import function.

Now that you know how items are structured you can start building your item community!

--
//end::transkript[]
