= Linking your email account with plentymarkets
:lang: en
include::{includedir}/_header.adoc[]
:position: 10020
:url: videos/personalisation/emails/link-email-account
:author: team-crm

//tag::einleitung[]
[cols="2, 1" grid=none]
|===
|This video teaches you how to link your email account with plentymarkets so that emails can be sent on your behalf. This video also shows you how to save an email signature and how to send blind copies of emails to another person.
|<<videos/personalisation/emails/link-email-account-save-data#video, Saving email access data (0:33)>>

<<videos/personalisation/emails/link-email-account-create-signature#video, Creating an email signature (1:29)>>

<<videos/personalisation/emails/link-email-account-blind-copies#video, Sending blind copies of emails (2:07)>>

|===
//end::einleitung[]

video::212556599[vimeo]

// tag::transkript[]
[.collapseBox]
.Transcript
--

If you think about it, your business probably has dozens or even hundreds of email addresses. There's an email address for every employee and there are also department-specific addresses like "info at" and "billing at". Now it's time to decide which of these email addresses you want to use when sending routine emails to customers.

Anyone who has ever gone to the movies knows that you'll need to show a ticket before you're given access to the theater. When it comes to email, you'll do something very similar. Once you've decided which email account you want to use, you'll need to save access data for this account so that your emails are allowed through to customers.

So just log into plentymarkets and navigate to the area for saving email access data. Here you'll see a wide range settings like the outgoing mail server, the port and the encryption method. Just ask your email provider which exact settings you should choose. Or if your email provider is mailbox.org, then open up the plentymarkets online manual to see which exact settings you'll need to enter.

Here, enter your own name or the name of your company as it should be displayed to customers. And here, enter whichever email address you want to use for sending invoices, shipping confirmations and other emails to customers.

And the last thing you'll want to do in this menu is activate the test mode, which you can think of as the dress rehersal before opening night. As long as the test mode is activated here, emails will only be sent to your own email address. So this gives you the opportunity to send a few test emails to yourself and make sure that everything's running smoothly before you begin sending real emails to customers.

Alright, so once you've saved your access data, you're ready to create a signature. While Shakespeare signed his plays like this your email signature is simply information that's added to the end of every email.

Generally, the email signature includes the same sort of information that's also found in your company letterhead. But when you're creating your own signature, make sure that you comply with the legal regulations in the country where you do business. Because some countries have strict regulations about which information needs to be included in the signature. And before we move on.... spoiler alert! The next video in this series will teach you how you can actually add this signature to the end of your emails.

When putting on a play, sometimes it's helpful to have a prompter, who hides in the shadows and whispers lines of text to your actors.
The email information service in plentymarkets can be thought of in much the same way.

Just like a prompter passes on information without being seen by the audience, here you can choose to have blind copies of outgoing emails passed on to another address of your choice. Just select "Yes" here and then enter whichever email address the blind copies should be sent to.
So with the settings configured like this, my Jane Doe email address will receive a blind copy of every email that's automatically sent by plentymarkets. And of course, since this is a blind copy, the recipient will not see that this Jane Doe address was also sent a copy of the email. So this can be really helpful, for example, if you're just starting out with your online store and you want to keep an eye on all of your sent emails and make improvements to them as necessary.

And here, just place a check mark if you don't want to receive blind copies of all the newsletters that plentymarkets sends on your behalf.
The second thing that you can do in this menu is choose to receive an email notification every time someone orders an item in your online store.
Here again, just enter whichever email address this notification should be sent to.

In this tutorial, you learned how to save email access data, how to create an email signature and how to receive blind copies of outgoing emails. Once you're comfortable with these topics, continue on to the next video, where we'll look at the actual content and design of your emails.

--
//end::transkript[]
