= Importing item and listing data from your eBay account
:lang: en
include::{includedir}/_header.adoc[]
:position: 10010
:url: videos/ebay/listings/listing-import
:id: KQGFJTI
:author: team-multi-channel

//tag::introduction[]
[cols="2, 1" grid=none]
|===
|Do you already have item and listing information saved on eBay? There's an easy way to transfer all of this data into your plentymarkets system. This video teaches you how to configure eBay import settings and choose the options that are right for you.
|<<videos/ebay/listings/listing-import-account-platform#video, Selecting your eBay account and platform (0:23)>>

<<videos/ebay/listings/listing-import-settings#video, Choosing which path to take (0:47)>>

<<videos/ebay/listings/listing-import-extra-features#video, Picking extra features (1:49)>>

<<videos/ebay/listings/listing-import-preview#video, Seeing a preview of the import (2:28)>>

<<videos/ebay/listings/listing-import-start#video, Starting the import for real (3:12)>>

|===
//end::introduction[]

video::267560178[vimeo]

// tag::transcript[]
[.collapseBox]
.Transcript
--
Sure, you might be new to plentymarkets, but that doesn't necessarily mean you're new to e-commerce. You might've been selling items on eBay for years!

No need to re-invent the wheel and manually enter all this item information into plentymarkets.

Just use the eBay listing import to easily transfer item data from your eBay account into your plentymarkets system.

How does it work?

Just open up the "eBay listings" menu and configure the import settings as needed.

First, use this area up here to tell plentymarkets which eBay account and platform you want to import data from.

Then tell plentymarkets, which warehouse the newly imported items should be assigned to and which stock dependence settings they should be given.

You can think of this next area as a choose-your-own-adventure or as a fork in the road.

If you're completely new to plentymarkets, then you might want to import your listing information from eBay and use this information to create new items in plentymarkets.

On the other hand, if you already have your item data in plentymarkets, then you may only want to import corresponding eBay listings.

Or if you've already got items and listings in plentymarkets, then you may only want to update your stock information.

Which option you pick depends on what you want to do.

Let's assume you're completely new to plentymarkets and you want to create items from your eBay listing information. In this case, turn your attention to these three options here and decide whether you want to use the eBay item number, listing title, or a combination of these two when searching for listings to import into your plentymarkets system.

We recommend that you use the eBay item number because it's the most accurate method of telling exactly which information is which.

Once you've settled on an option, you'll be ready to scroll down to this last area here and decide which types of little extra features should be included in the import.

For example, if you use JavaScript or HTML elements in your listing descriptions on eBay, then you'll probably want to check this option here so that they're filtered out, and only plain text descriptions are imported into plentymarkets.

You may also find this option here useful if you're just starting out with plentymarkets. If you haven't created a category structure for your items in plentymarkets yet, then check this option to import your eBay shop categories and link these categories to your items in plentymarkets.

Once you're ready to start the import, decide whether you want to import all of your eBay listings, only a few pages of listings, as they're organised within your eBay account, or only a few specific listings.

You can think of the import as being split into two steps.

First, there's the preview, which is essentially just a trial run or a simulation of the import. It gives you time to catch and fix any potential errors before the real thing.

When you start the preview you'll see information about its status here. This log shows you which settings were used and when the preview started and finished.

Click on the magnifying glass to see detailed information about the items and listings included in the import.

If you're happy with the results, then just click on this little plus to return to the configuration area, turn off the preview function, and start the import for real.

Your eBay listing information will be imported and it will be used to create new items in your plentymarkets system. If your items were available in several different sizes or colours on eBay, then all of the different attributes and variations will be created in plentymarkets too.

Just a quick word to the wise for those of you who already have item data in plentymarkets and are looking to import the corresponding eBay listings.

We recommend that you check this option here because it will help plentymarkets accurately match your listings to the correct variations in plentymarkets.

Those of you who sell on eBay motors should know that it's possible to import your parts compatibility listings and activate them where appropriate.

In this video, you learned how to configure the import settings and choose the options that are right for you. You learned how to use the preview function to catch and fix any potential errors. And you learned how to start the import once you're satisfied with the results.

Now it's your turn to explore the possibilities of the eBay listings import and see just how much time you'll save by importing data rather than entering it all by hand.
--
//end::transcript[]
