= Creating mailbox.org email accounts
:lang: en
include::{includedir}/_header.adoc[]
:position: 10010
:url: videos/personalisation/emails/mailboxorg
:id: HFDWYL9
:author: team-crm

//tag::einleitung[]
[cols="2, 1" grid=none]
|===
|This video walks you through the process of creating mailbox.org email accounts for all of the users who work with your plentymarkets system. It also teaches you how to create aliases, i.e. department-specific or non-person email accounts.
|<<videos/personalisation/emails/mailboxorg-mailbox-vs-alias#video, Mailbox vs. alias (0:56)>>

<<videos/personalisation/emails/mailboxorg-mailbox-settings#video, Mailbox settings (1:35)>>

<<videos/personalisation/emails/mailboxorg-alias-settings#video, Alias settings (3:04)>>

|===
//end::einleitung[]

video::212555839[vimeo]

// tag::transkript[]
[.collapseBox]
.Transcript
--

It's almost showtime! But before turning the spotlight on your online store, there are still a few more tasks to complete behind the scenes. Next up? How you'll communicate with customers via email. This video walks you through the process of creating mailbox.org email accounts for all of the users, who work with your plentymarkets system.

The last few videos in this series compared user accounts to actors in a play. At this point, we're ready to send our actors to hair and makeup, to give them the finishing touches before they're sent out on stage.
Or in terms of plentymarkets, we'll put the finishing touches on our users by giving them email accounts. Simply log into plentymarkets as an admin and then navigate to the user accounts menu. Open your own user account and then click on the "Email" tab.

You're ready to dive right in and create a new mailbox. This is done simply by clicking on the green plus icon and then saving the settings in the pop-up window that appears. OK, so the most important thing here is to decide whether you're creating a mailbox or an alias. It's pretty common to find aliases or stage names in show business. For example, you've probably heard of Elton John, but you may not recognise him by his given-name: Reginald Kenneth Dwight. Here, mailboxes and aliases work much the same way.

You can think of a mailbox as your given name. Mailboxes are essentially just your email inbox or your main email address. Aliases, on the other hand, can be thought of as stage names. These are additional email addresses like "info at" or "billing at" and they redirect messages to a specific person.

Most of the other options here are pretty straight forward, so we'll just breeze through them. First, enter whichever email address should be assigned to the mailbox. So here, enter the local part of the email address, or the part of the address that's left of the "at" symbol and here, select the domain, or the part of the address that's right of the "at" symbol.
Next, enter the user's first and last name. And just note here that this name will be displayed along with the email address as part of the sender information. So just make sure that you enter something here that you're comfortable with other people seeing.
Here, select whichever user the mailbox should be assigned to.

This next option is really useful if you want to forward emails that are sent to this address to a different mailbox as well. So just enter one or more email addresses here. And if you enter more than one address like I am, then just use commas to separate them.

OK, and as soon as you've entered text into the "Forwarding" field, you'll see a check box that appears here. If you leave the check mark, then a copy of each message will be saved in this mailbox. And conversely, if you remove the check mark, then your emails will be forwarded on - without saving a copy of them in this mailbox.

Alright, and lastly, enter a secure password and then re-enter it for confirmation. Then down here, select whichever fee includes the amount of storage, number of aliases and features that you want. The fee that you choose will be added to your plentymarkets bill. Once you're satisfied with all of the settings, click on this button here to create the mailbox.

The mailbox is now displayed here in the overview, and I can see some information about it if I move my mouse over the columns of information. Now that you know how to create a mailbox, let's look at how to create an alias. Just like before, click on the green plus icon, but now, select "Alias" as the email address type.

OK, there are only two things that you need to do when creating an alias. First, enter the email address, like "info at" and select the domain. Second, specify which mailbox this email address should forward to. Now this alias also appears in my overview and here, I can see which mailbox it forwards to.
That's all there is to creating mailboxes and aliases! Once you've finished setting up all of your email accounts, you'll be ready to continue on by saving your email server access data in plentymarkets.

--
//end::transkript[]
