= Managing MFN returns
:lang: en
include::{includedir}/_header.adoc[]
:position: 10030
:url: videos/amazon/orders/mfn-returns
:id: 1T7C7NB
:author: team-multi-channel

//tag::introduction[]
[cols="2, 1" grid=none]
|===
|Someone bought your item on Amazon, but now they want to send it back. How's that going to work? This video teaches MFN sellers how to manage their returns with plentymarkets.
|<<videos/amazon/orders/mfn-returns-create-new-return#video, Creating a new return in plentymarkets (0:40)>>

<<videos/amazon/orders/mfn-returns-notify-amazon#video, Notifying Amazon of returns (1:40)>>

<<videos/amazon/orders/mfn-returns-statuses#video, Using statuses to understand Amazon's reply (2:08)>>

|===
//end::introduction[]

video::307436538[vimeo]

// tag::transcript[]
[.collapseBox]
.Transcript
--
Someone bought your giraffe t-shirt on Amazon! But they bought the wrong size and now they want to send it back.

How's that going to work?

Once your customer has logged into Amazon and printed out a return label, she's ready to send the item back.

It won't be long until the package arrives at your business, and you'll get down to work.

This video teaches you what to do when Amazon items are returned to your store. There are essentially just three steps.

First, you'll create a new return in plentymarkets and second, you'll notify Amazon of the return.

Third, you'll find out whether Amazon received your notification.

OK, first things first. You'll need to create a return, which corresponds to the original order in plentymarkets. Now there are two ways to do this.

On the one hand, you could open up with original order and manually create the return like so.

Or on the other hand, you may want to use a process, which automatically creates returns for you in your plentymarkets system.

All your warehouse technician needs to do is find the order that's being returned, select this order, and then scan the barcode or ID for any items that it includes.

At this point, your warehouse technician will inspect the item to see whether it's in good condition or whether it was damaged by the customer.

Finally, your warehouse technician creates the return.

It will land in the order overview where you can continue processing it even further.

And where you'll create a credit note to refund the customer.

At this point, you'll want to automatically send Amazon some information about the return.

This is really easy to do by creating an event procedure which goes into effect as soon as you've created a credit note for Amazon returns.

Any time this happens, plentymarkets will automatically notify Amazon of the new return.

And then plentymarkets will tell you either that the return was successfully transmitted to Amazon, or that something went wrong along the way.

More specifically, plentymarkets will change the return's status to one number if everything went well and a different number if there was a problem.

Essentially, you can pick whichever statuses you'd like but in practice, we recommend that you head on over to the order status menu and create two new Amazon return statuses with the next logical numbers, so in this example 9.6 and 9.7.

And that's exactly what I'll do.

I just enter a logical number, like 9.6

Then give it a name and save the settings.

Then one more time to create another status for returns that were not transmitted correctly.

Your next stop will be in the Amazon MFN settings where you'll tell plentymarkets which statuses you've created for returns that were successfully sent to Amazon and returns that could not be sent to Amazon.

When plentymarkets switches the return's status to 9.6, it will also close your customer's return within her Amazon account.

Congratulations! You've done it! You've learned how to efficiently handle any Amazon items that are returned to your store.
--
//end::transcript[]
