= The difference between MFN and FBA
:lang: en
include::{includedir}/_header.adoc[]
:position: 10010
:url: videos/amazon/orders/mfn-fba
:id: LD51PYA
:author: team-multi-channel

//tag::introduction[]
[cols="2, 1" grid=none]
|===
|Are you a do-it-yourselfer or a fan of full service? MFN and FBA have different advantages for different sellers. Learn what's right for you before setting up your plentymarkets system to fulfill Amazon orders.
|<<videos/amazon/orders/mfn-fba-part-one#video, MFN (0:33)>>

<<videos/amazon/orders/mfn-fba-part-two#video, FBA (1:22)>>

<<videos/amazon/orders/mfn-fba-pan-european-fba#video, Pan-European FBA (2:04)>>

<<videos/amazon/orders/mfn-fba-multi-channel#video, Multi-Channel (2:38)>>

|===
//end::introduction[]

video::307426121[vimeo]

// tag::transcript[]
[.collapseBox]
.Transcript
--
Amazon ... behold the beautiful shopping panorama laid out before you. Every year it attracts more and more travelers looking to settle down with their products. You're also feeling the pangs of wanderlust - and with your best items in tow, you're off to the Amazon jungle.

So what awaits you? Once your items are online, let the great shopping adventure begin! But every order that's generated means plethora of fulfilment tasks.

MFN vs. FBA. And Pan-Europe! And Multichannel! There are so many ways to experience Amazon. So how do you choose what’s right for you?

Well, for one thing, you have to know what you NEED for the type of trip you're taking.

The experienced do-it-yourselfers amongst you might only need a plane ticket and a backpack to get what you need out of your Amazon adventure. MFN, so the Merchant Fulfilled Network, gives you more responsibility, but all the freedom to fulfil your orders as you see fit!

Since this expedition is nothing for rookies, you’ll need to have a few things in the bag: some experience, a solid e-commerce business that does everything from A to Z ... AND you need to offer pretty great customer service.

That’s quite a bit to lug around. But despite all that baggage, you have the freedom to handle shipping, returns, credit notes etc. the way you want.

And if you meet the requirements of a Prime Seller, there’s nothing stopping you from taking advantage of perks such as fast and free delivery.

But there’s no shame in wanting a few more amenities.

FBA is kind of like the Amazon Wellness package. You don't even have to go abroad to get the full scope of feel-good services. All you have to do is show up and relax.

Grab your speedo and let Amazon do the heavy-lifting for you. Depending on your country of business, the Amazon platform you'll be working with stores your items in its own warehouses and takes care of all fulfilment tasks for you - so order processing, shipping, returns, credit notes etc. etc. All that with great customer service to boot.

Plus, you’re automatically eligible for Prime. That’s great for both you AND your customers.

And if you want to stay in the know, decide yourself what fulfilment steps you want imported into your system.

Amazon’s Pan-European FBA package, on the other hand, is the whopper of all wellness trips. This comprehensive international deal puts you on a first-class cruise through the Amazon Empire.

With Pan-Europe you can sell your products across Europe while placing your inventory closer to your customers. In general, fulfilling and delivering orders is faster and cheaper! And since FBA means you’re automatically eligible for Prime, Pan-Europe means you’ll reach millions of additional Prime customers across the continent!

FBA…! Whether it’s the wellness package in your home country or the big multinational cruise, you might as well go for the gold and book the additional all-inclusive option as well. With Amazon’s Multi-Channel Fulfilment, you reap all the benefits of FBA regardless of whether your item was purchased on Amazon, bol, eBay, Rakuten or whatever other eligible marketplace.

So have another eBay Sunrise! No headaches for you because Amazon’s got you covered! Cheers to that!

Now do you need a little bit of pampering or are you an adventurous do-it-yourselfer? Either way, Amazon gives you options. Once you’ve chosen the right package, it’s time to set up plentymarkets so that the vast expanse of Amazon can come to you. Check out our more in-depth tutorials to learn how!
--
//end::transcript[]
