= Fulfilling your own orders with MFN
:lang: en
include::{includedir}/_header.adoc[]
:position: 10020
:url: videos/amazon/orders/mfn-orders
:id: GBBJRFN
:author: team-multi-channel

//tag::introduction[]
[cols="2, 1" grid=none]
|===
|Someone bought your item on Amazon! Want to fulfil the order yourself? This video teaches you which settings you'll need to configure so that plentymarkets correctly imports the sales you made on Amazon.
|<<videos/amazon/orders/mfn-orders-configure-settings#video, Configuring the MFN settings (0:48)>>

<<videos/amazon/orders/mfn-orders-activate-settings#video, Activating the MFN settings (3:49)>>

|===
//end::introduction[]

video::307433826[vimeo]

// tag::transcript[]
[.collapseBox]
.Transcript
--
Some travellers are real do-it-yourselfers! They don't want an all-inclusive vacation package. They'd rather be their own tour guide and plan the trip themselves!

You can think of Amazon in much the same way. When it comes to fulfilling orders, some sellers want to do it themselves. If that's you, then you'll need to configure these settings here and tell plentymarkets exactly how you'd like it to import the sales you made on Amazon.

On the other hand, if you'd prefer to book an all-inclusive package, then you'll need to configure the FBA settings, so that Amazon is able to fulfil orders on your behalf.

This video is geared toward do-it-yourselfers. In other words, it teaches you how to configure and ultimately activate the MFN settings in plentymarkets.

Alright, strap on those boots and let's hit the trail!

First up, tell plentymarkets whether it should automatically import the sales you made on Amazon.

And second, tell plentymarkets whether it should automatically notify Amazon once you've shipped the package.

But just a little side note. plentymarkets only considers a package to have been shipped if the order is in status 7 and if the outgoing items have been booked.

So just keep in mind that only orders that meet these criteria are considered to have been shipped.

OK, continuing on, decide how you'd like the names of items to be displayed.

You'll see these item names while fulfilling orders in your plentymarkets system.

And your customers will also see these names displayed on documents like the invoice and the delivery note.

So essentially, just decide whether you'd like to use the same name that you also use in your online store.

Or whether you'd prefer to be consistent with the name that you use on Amazon - either with or without the SKU as additional information.

Use this option here to specify whether orders should be marked as already paid for or as still waiting for payment, when they're imported into your system.

In most cases, it makes sense to assume that Amazon will indeed stick to its end of the bargain and transfer the customer's payment to your bank account. So you may as well assume that orders are paid for and start fulfilling them straight away without losing any valuable handling time.

These next two options let you choose the order status for returns that were successfully transmitted to Amazon and returns that couldn't be transmitted. But don't worry too much about these options right now. You'll learn more in an extra video about managing returns.

This setting here is useful if you're worried about accidentally overselling items.

One way that you can reduce the likelihood is by automatically importing pending orders. Or in other words, importing orders that have yet to be approved by Amazon. These orders will only include rudimentary data, like the item's name. But the stock will already be reserved, and you'll receive the missing customer data once the order is approved.

Overselling's probably not something you worry about if you sell bulk goods or if you don't track your stock levels anyway but in most cases, it's a nice tool to have.

Use this last setting here to decide whether Amazon credit notes should automatically be imported into plentymarkets. Again, don't worry too much about this option right now because we'll take another look at it in our video about managing returns.

Once you've finished configuring the options, head on over to the "Settings" tab and take one last look at the "Initial settings" area. Have you configured everything here correctly?

If you run several different stores, have you already used this option here to specify which store your Amazon orders are attributed to?

How about this option? Have you decided how you'd like to calculate VAT for your invoices?

Since calculating VAT is quite complex, you may want to use Amazon's VAT calculation service and have them do it for you.

If you'd like to use Amazon VCS, then you'll need to book the service within your Amazon account and then select the option in plentymarkets. Just note that this function is still in the process of being developed.

Once you've finished configuring all of the settings in these three tabs, you're ready to activate the Amazon interface and save your settings.

Finally, you'll need to open up the "Data exchange" menu and then the reports. Here you'll tell Amazon how often it should create a report for new MFN orders. Or essentially, how often it should notify plentymarkets of new orders.

OK, so just select the appropriate Amazon account and then decide how often the reports should be generated. We recommend picking the shortest possible interval, so there's no unnecessary delay in your fulfilment processes.

Click on the gear-wheel icon when you're ready to schedule the MFN order report.

If you fulfil your own orders, then you're the tour guide on your journey to Amazon. Check out our next videos and learn about other attractions to see along the way. How do you offer Amazon Prime when you fulfil your own orders? And how do you deal with returns? Join us for the next videos and find out!
--
//end::transcript[]
