= Selling miscellaneous items that aren't in your system
:lang: en
include::{includedir}/_header.adoc[]
:position: 10040
:url: videos/pos/setting-up-pos/miscellaneous
:id: RVIPKIM
:author: team-mobile

//tag::einleitung[]
[cols="2, 1" grid=none]
|===
|This video teaches you how to sell miscellaneous items that aren't managed in your plentymarkets system. All you need to do is create a so-called "dummy item", give cashiers the right to sell this item and have cashiers enter the price while ringing up customers.
|<<videos/pos/setting-up-pos/miscellaneous-create#video, Creating dummy items (0:48)>>

<<videos/pos/setting-up-pos/miscellaneous-price#video, Having cashiers enter the price (1:48)>>

<<videos/pos/setting-up-pos/miscellaneous-rights#video, Granting rights to cashiers (2:03)>>

<<videos/pos/setting-up-pos/miscellaneous-sell#video, Selling dummy items in your POS system (2:32)>>

|===
//end::einleitung[]

video::288160054[vimeo]

// tag::transkript[]
[.collapseBox]
.Transcript
--
It's late at night and Dorothy's busy entering product information into plentymarkets. She's got a bunch of miscellaneous household items that she sells for a pound each.
But entering tons of product information just to make a few quid? Not really worth it.
There's a more efficient way!
Simply create a dummy item in plentymarkets and let it stand in for all the miscellaneous, remnant or seasonal items that aren't worth creating individual data records for.

This video walks you through the process in three steps. First, you'll create a dummy data record for every VAT rate you charge in your store. Second, you'll have cashiers enter the item price while ringing up customers. And third, you'll give your cashiers the right to sell dummy items.

Alright, step one, open up your plentymarkets system and create a new item, just like you would for any other products you sell in your store.
There are just a few settings that differ from regular items. For starters, tell plentymarkets that you don't want to manage stock levels for dummy items and then select the appropriate VAT rate for the dummy. Keep in mind that you'll need to create a separate dummy item for every VAT rate that you charge in your store.
So you'll need to create two different dummy items if you sell some items with 20% VAT and other items with 5% VAT.

Finally, enter the sales price. For example, 1 pound if you're going to sell all your household items for the same price or zero pounds if some items will be more expensive than others.
Don't worry, you won't really be giving items away for free. Cashiers will enter the actual price while ringing up customers.
And this brings us to the next step of the process. Open up the settings for your point of sale system and tell plentymarkets that you'd like cashiers to enter the real price of these items while making a sale.

Finally, you'll need to give your cashiers the right to sell dummy items.
Whether you grant rights to individual employees or to all of the employees who fulfil a specific role, the steps will be the same.
Simply click on the "Rights" tab and then the "Mobile" tab.
Here, give your cashiers the right to edit item prices and rename items.

It's easy for cashiers to ring up dummy items.
In fact, the process is nearly identical to ringing up any other item.
Cashiers simply find the dummy item and they're immediately prompted to enter the price.
Cashiers can then re-name the dummy item if they'd prefer to change the text that will appear on the customer's receipt.
When they're done, cashiers will ring up customers and accept payment just like they would when making any other sale.
So follow Dorothy's example and create dummy items that stand in for all the miscellaneous, remnant or seasonal items that aren't worth creating individual data records for.
--
//end::transkript[]
