= Having Amazon fulfil orders from any platform with multi-channel FBA
:lang: en
include::{includedir}/_header.adoc[]
:position: 10060
:url: videos/amazon/orders/multi-channel-fba
:id: JMY9SFA
:author: team-multi-channel

//tag::introduction[]
[cols="2, 1" grid=none]
|===
|Amazon can fulfil orders placed on eBay in your online store or on any other sales channel. And you can keep track of it all with plentymarkets. Simply configure a subset of FBA options and you'll be on your way.
|
|===
//end::introduction[]

video::314727596[vimeo]

// tag::transcript[]
[.collapseBox]
.Transcript
--
Did you know that Amazon can fulfil orders on your behalf?

In other words, you can store your products in Amazon's warehouse and then have them fulfil orders and ship packages for you with the Prime label.

But the best part? It doesn't matter if your customer bought the item on Amazon, eBay, in your online store or on any other sales channel. Wherever you made the sale, Amazon can take care of it for you!

Once you've booked this so-called "Multi-Channel" service in your Amazon account you'll need to watch our video on Amazon FBA and configure the settings in your plentymarkets system accordingly.

Afterwards, you'll be ready to focus on the sub-set of options that apply specifically to multi-channel.

Okay, first off, the point of multi-channel is that you're asking Amazon to not only fulfil those orders that were placed on Amazon but also to fulfil orders placed on eBay, your online store or any other sales channel.

So of course, it makes sense to pick this option here.

Now moving on to the status. Keep in mind that Multi-Channel FBA is a service which packs and ships orders on your behalf.

Here, you'll specify which status the order should be given when it's handed over to Amazon to be fulfilled.

Since Amazon will then fulfil the order and ship the item, this will be the order's final status. And as such, we recommend picking a status that starts with the number 7.

So for example, 7.3.

But just FYI, if you don't see an appropriate status in this drop-down menu, then you can create one in the order settings.

Next up, item bundles. Let me start out by saying, there's no right or wrong choice here. Which option you choose depends on how you've set up your item bundles on Amazon.

Let me explain. Imagine you sell camping gear, like a compass, a flashlight and a Swiss army knife.

Okay, now the question is - do you only sell these items individually?

Or do you perhaps offer them all together in a survival kit? Or in other words, in an item bundle.

Or can customers choose between buying the survival kit or buying one or two of the items individually?

That's the idea behind this drop-down menu here.

You'll want to choose "Transmit without package position" if you only sell the items individually, and each individual item has its own SKU.

On the other hand, you'll want to choose "Transmit package position only" if you only sell the items together in a bundle, and the bundle has its own SKU.

Or, you'll want to choose "Transmit all order positions" if you sell the items in a bundle with a SKU, and you also sell the items individually, with their own SKUs.

Finally, use this option here to choose whatever type of shipping was stipulated in your contract with Amazon. If you're not sure what type of shipping was agreed upon, then take a look in your Amazon contract or in the terms and conditions.

Congratulations! Amazon will now begin fulfilling orders on your behalf regardless whether they were placed on Amazon, in your online store, on eBay or on any other sales channel.
--
//end::transcript[]
