= Omni-channel sales from one, central command centre
:lang: en
include::{includedir}/_header.adoc[]
:position: 10020
:url: videos/basics/omni-channel-sales-command-centre
:id: 0ASYI2Y
:author: team-webshop, team-mobile, team-multi-channel

//tag::einleitung[]
[cols="2, 1" grid=none]
|===
|You can control your sales activities on dozens of different platforms, from one, central plentymarkets system. Learn how plentymarkets helps you sell items in an online store, on marketplaces like Amazon and eBay, or in a brick and mortar store.
|<<videos/basics/omni-channel-sales-command-centre-online-marketplaces#video, Online marketplaces (0:40)>>

<<videos/basics/omni-channel-sales-command-centre-brick-and-mortar-store#video, Your brick and mortar store (1:06)>>

<<videos/basics/omni-channel-sales-command-centre-online-store#video, Your online store (1:41)>>

|===
//end::einleitung[]

video::257101803[vimeo]

// tag::transkript[]
[.collapseBox]
.Transcript
--
Your business is on a mission. Its goal? Selling products to customers!

Whatever route you choose to take, plentymarkets helps you get there. Whether you sell items in an online store, on marketplaces like Amazon and eBay, or in a brick and mortar store, plentymarkets helps you manage your sales activities and keep your stock levels up-to-date.
However you mix and match your omni-channel strategy, you can rely on an online store, point of sale module and interfaces to tons of popular sales platforms. In other words, you can control your sales activities on all of these different sales platforms, from one, central plentymarkets system.

Want to sell your items on marketplaces like Amazon and eBay? No problem!
You can give plentymarkets the ability to communicate with other sales platforms by entering your access data for the platform.

But what if you want to sell on a market that's not in this list? What if you're more interested in niche markets for homemade or specialty products? Just check out the wide range of plugins that you can download and add on to your plentymarkets system.

Maybe you also sell items in the real world and not just the virtual one. plentymarkets has the tools to help you succeed both online and off. Your point of sale system is composed of the POS module, as well as optional hardware like a credit card reader, cash drawer or receipt printer and the plentymarkets app, which turns your mobile device into a modern cash register, or till, which you can use to ring up walk-in customers. The plentyMarketplace also includes several helpful plugins, which you can use to install credit and debit card terminals in your brick and mortar store.

Want to sell products in your very own online store? You can use this powerful template as the foundation for your unique shopping experience. Of course, you can add on to your online store with a wide range of themes, widgets and payment providers. It's easy to add plugins to your plentymarkets system. Essentially, all you need to do is download the plugin of your choice, install the purchase and then activate it.

If you already rely on an external shop system like woo-commerce or shopify, then just download the connector to link your front end shop with the back end functions in plentymarkets. Mix and match your omni-channel strategy as needed. We're here to help you with our online manual and video tutorials. Here you'll find video courses that teach you all about plugins, POS, multi-channel and much more.
--
//end::transkript[]
