= Linking your printer to plentymarkets
:lang: en
include::{includedir}/_header.adoc[]
:position: 10020
:url: videos/automation/processes/printer
:id: DYMMAOZ
:author: team-mobile

//tag::einleitung[]
[cols="2, 1" grid=none]
|===
|You can use processes to automatically print pick lists, invoices, shipping labels and other documents. First, you'll just need to link your printer with plentymarkets and configure its settings.
|<<videos/automation/processes/printer-settings#video, Configuring printer settings (0:26)>>

<<videos/automation/processes/printer-processes#video, Selecting printers within processes (1:48)>>

|===
//end::einleitung[]

video::227218634[vimeo]

// tag::transkript[]
[.collapseBox]
.Transcript
--
Up in the sky! It's the signal! Online sellers are calling out to Dr. Process. They want to use his super powers to print pick lists, invoices and shipping labels at the speed of light.
When our hero arrives on the scene, he finds a printer that's been causing lots of trouble. The thing works just fine, but it won't communicate with plentymarkets. Let Dr. Process show you the way!

Simply navigate to the "Basic settings" menu, move your mouse over the word "Printer" and click on the little triangle.
Give your printer a name and select it from the list of printers that are currently connected to your own computer.

Next, spend some time thinking about how you want to configure your printer settings and page setup.
So for example, which paper size you want to use, whether you want to print landscape or portrait and what sort of margins you'd like to have on the page.

Repeat these steps as often as necessary if you'd like to add other printers or configure other paper sizes and page arrangements.
The settings that you enter here will be used every time that you print something with this printer configuration.
Or if you'd rather allow employees to select their own page setup for every print job then just tell plentymarkets that it should open the printer dialogue whenever something is printed.

Once you've finished configuring the settings, print a test page to make sure that you're satisfied with the end result.
printer noise?
If you're unhappy with the print quality, then you may want to try switching the printer plugin from default to Cups, PDFBox or ZPL if you're working with a Zebra label printer.

As soon as you've finished adding printers in the basic settings menu, you'll be able to select them within your own processes.
Every time you use the sub-procedure called "Print", you'll be able to specify which printer you'd like to use for the job.
So for example here, I'll use my standard HP printer for things like invoices and pick lists.
And I'll use my label printer for shipping labels.

Don't worry if this screen here is unfamiliar to you and you're thinking: "what? sub-procedures? how?" We've got other videos in this series that teach you how to create processes and add elements to them.
Just like that Dr. Process has turned our uncooperative printer into a strong ally! Together we can move forward and tackle even the most complex fulfillment job.
--
//end::transkript[]
