= Quicklinks in your order overview
:lang: en
include::{includedir}/_header.adoc[]
:position: 10030
:url: videos/order-processing/processing-orders/quicklinks-order-overview
:id: BM051KK
:author: team-order-payment

//tag::introduction[]
[cols="2, 1" grid=none]
|===
|Learn about important info and some basic functions in the order overview. Help out your customer with a few quick clicks.
|


|===
//end::introduction[]


video::219701201[vimeo]

// tag::transcript[]
[.collapseBox]
.Transcript
--

Alright, let's continue with our tour of the company! We're currently in customer service where Peter is taking customer calls at his desk.
Oh and there's one already!

Hello, I recently placed an order with your shop and I'm still waiting for the delivery.

Obviously your customer can check the account they've created for your shop themselves to see how far along their order is. Or you can simply answer your customer's questions right away.
The order overview gives you exactly that - a complete overview of all your orders where you can quickly retrieve your customer's specific order by entering some basic information such as the Order or customer ID or your customer's name. The order you're looking for shows up right away and as you can see
 it's in status 3.3. That means that your customer hasn't paid in full yet which the payment bar demonstrates as well. You can also see when this order was created and when it was payed for right here.
And these buttons give you a few additional possibilities such as generating an invoice as well as booking payment and outgoing items.
So as you can see, you can take some essential order processing steps right in your order overview.

Okay, sorry about the partial payment. I'll get that straightened out. I'd also like to order the same item for my sister as a gift. Can you do that for me?

No problem. Your order overview even provides you with a button that allows you to check whether you've got enough of those items in stock. If you don't, you can simply re-order those items directly.
But if all is well, you can simply add the item to your order if you haven't yet generated an invoice for it.

Oh and by the way! Can you send me a copy of the revised invoice?

Yes. We. Can! Simply generate the invoice, click the little email button here and select the invoice attachment like so.
Obviously this was just the beginning. Your order overview provides you with loads of additional features and info.
It's kind of like the floor plan of a building. It's what you'd consult to get the lay of the land - where you would survey your orders at a glance and access relevant options at the click of a button.
To learn more about order processing, just check out our other videos!
