= Ringing up customers with the plentymarkets app
:lang: en
include::{includedir}/_header.adoc[]
:position: 10010
:url: videos/pos/working-with-app/ringing-up-customers
:id: 4D4NVEW
:author: team-mobile

//tag::einleitung[]
[cols="2, 1" grid=none]
|===
|Use the plentymarkets app to add items to your cart, make changes to the order as you go and use your customer's payment method of choice.
|<<videos/pos/working-with-app/ringing-up-customers-checkout#video, Add items to the shopping cart (0:31)>>

<<videos/pos/working-with-app/ringing-up-customers-discount#video, Enter a discount (1:03)>>

<<videos/pos/working-with-app/ringing-up-customers-note#video, Add a note (1:16)>>

<<videos/pos/working-with-app/ringing-up-customers-customer-class#video, Select a customer class (1:29)>>

<<videos/pos/working-with-app/ringing-up-customers-pause#video, Pause the checkout process (1:44)>>

<<videos/pos/working-with-app/ringing-up-customers-edit#video, Edit order (2:02)>>

<<videos/pos/working-with-app/ringing-up-customers-payment#video, Accept payment (2:14)>>

|===
//end::einleitung[]

video::286536680[vimeo]

// tag::transkript[]
[.collapseBox]
.Transcript
--
Dorothy has become quite the plenty buff and had a blast setting up the app for her store. Now it's all ready to go for her new employee.
Since today is Young Destin's first shift behind the till, he's a bit nervous. But with the plentymarkets app, ringing up customers is easy as pie.
With his morning mochacino in hand, Young Destin logs into the app.
He opens up his POS till and within minutes his first customer already wants to buy 3 jars of Dorothy's famous strawberry jam.

The plentymarkets app gives you a few different options for adding items to the checkout basket.
In the search function, simply enter the item ID or its name.
If you've saved barcodes in your item data, then simply scan the item.
But if the item is a strong seller, then make it a favourite to quickly add it to your basket like so.
Three jars of strawberry jam. You're welcome!

Now Dorothy offers a 5% discount when customers buy 3 jars of jam or more. To enter the discount, tap on the little wrapped present down here. Gift card codes are also entered here, but that's a story for a different video.
For Dorothy's 5 % discount, enter the amount in percent.
Since Dorothy runs a tight ship, she's asked Young Destin to make a note of anything out of the ordinary such as discounts. The pin down here allows you to add a note to your order.
And the little business card allows you to differentiate between customers. By selecting a specific customer class, Dorothy gives some customers an additional discount because of decades of loyalty. Otherwise Dorothy treats everyone as a standard customer.

But whoops, this customer forgot something. While they've gone back for one more jar of jam, simply go to the menu up here and pause the checkout process by parking the receipt. This allows you to ring up other customers in the meantime. Once you're customer is ready, simply call up their purchase and continue as usual.
To make any changes to this purchase, tap on the item and select the change you want to make.

And now according to Dorothy's favourite band, listen to the money talk! Use this button here for debit or credit card payments. If a customer pays the exact amount in cash just tap on this button here. Or simply enter the amount your customer gave you and give them back the change you owe them.
Now your ready for your next customer.

Dorothy has prepped Young Destin well in case he makes a few mistakes on his first day. If something goes wrong with one of the orders, just go back and cancel it that very same day – but only before you've created the end-of-day Z Report. Once the Z report is out, any order that needs to be cancelled must be processed as a return because returns can be created any time. Just check out the video to see how that works.
Alright, it's coming around closing time and young Destin has done well. And if young Destin can do it, so can you! Processing purchases in your brick-and-mortar store is easy with the plentymarkets app. That way you can focus on what's important – your customers!

--
//end::transkript[]
