= Create sales prices and price calculations for items
:lang: en
include::{includedir}/_header.adoc[]
:position: 10040
:url: videos/items/sales-prices
:id: QMHLEVZ
:author: none

//tag::einleitung[]
[cols="2, 1" grid=none]
|===
|Sales prices and price calculations are managed centrally in your system and can be linked to items. Use the item inheritance function to pass on prices to different variations.
|<<videos/items/sales-prices-prices#video, Creating prices (1:25)>>

<<videos/items/sales-prices-calculations#video, Creating price calculations (2:22)>>

|===
//end::einleitung[]

video::265563480[vimeo]

// tag::transkript[]
[.collapseBox]
.Transcript
--
"Welcome to my online store where all my items are free!" +
Yeah, that's not really in any seller's best interest. So let's talk about how you can manage your sales prices for every sales channel you use and if you want, get your system to automatically conduct price calculations for you!
But first things first. Let's welcome back our fancy shmancy raccoon t-shirt we've all come to love.

The nice thing about working with prices in plentymarkets is the flexibility. And thanks to the inheritance function, you simply enter a sales price in the main variation and it passes on that information to its subordinate variations, which is great if all of your variations are supposed to cost the same amount.

But if the red t-shirt actually costs a bit more, no worries. Just deactivate the inheritance function and enter the price that's right for each variation individually!
Just like attributes, properties and categories for example, sales prices can be linked to your item. This data is managed centrally in the system menu which has certain advantages as you'll soon see.

Remember the price we were just working with in our item? Well, this is it. Any new system usually already includes two prices. I've already configured this price to include all relevant currencies, clients, customer classes and countries.

The thing is, this price only applies to my online store. But e-commerce wouldn't be what it is without Amazon or eBay. Since we've already got eBay listed here, let's get to work on Amazon.
Alright, a new price needs a position so it can be sorted properly, a name - again, the internal name is just for you and the external one for your customers.
The price is also only valid for a minimum quantity.
You'll then specify the currencies you're working with and also whatever clients, customer classes and countries you want to activate this price for.
The referrer is the platform you want your new price to apply to, so Amazon. But don't forget: your Amazon account has to be linked to your system beforehand.

Great! New price, new opportunities! And since every price has its very own ID, you can add it to your CSV file so it can easily be imported and automatically linked to your item data.
To link it manually, select the price you want from the dropdown and add it like so. Perfect!

Since many sellers offer their products for a wee bit less on Amazon than in their webshop due to ranking issues, let's give it a little discount.
But what if you don't want to waste valuable time and brainpower calculating prices? Just let plenty do it for you.
Let's say you want your eBay price to be calculated on the basis of your item's net purchase price, plus an additional 120%.
As with lots of other important item data, price calculations are also set up centrally in your system. We'll call our new calculation exactly what is - an eBay price calculation.
Right, so our item's purchase price serves as the basis to calculate our eBay price. We also want to add a value in percent to our purchase price. 120 to be exact.
Back in the reloaded item overview, our eBay price needs to be linked to our t-shirt, as does our new price calculation.
And before you know it, your system is doing the work for you.
Welcome to life on easy street!

--
//end::transkript[]
