= Creating sales promotions with the eBay Marketing plugin
:lang: en
include::{includedir}/_header.adoc[]
:position: 10020
:url: videos/ebay/plugins/sales-promotions
:id: JEXP7CB
:author: team-multi-channel

//tag::introduction[]
[cols="2, 1" grid=none]
|===
|Create sales, discounts and special offers to catapult your listings to the very top!
|<<videos/ebay/plugins/sales-promotions-relink-account#video, Relinking the eBay account (0:18)>>

<<videos/ebay/plugins/sales-promotions-create#video, Creating eBay sales promotions (0:45)>>

|===
//end::introduction[]

video::240810586[vimeo]

// tag::transcript[]
[.collapseBox]
.Transcript
--
Attention, all you eBay treasure seekers! Your fedora, leather jacket and whip are sales, discounts and special offers. Use the potential of sales promotions to catapult your listings to the very top!

And to set all that up directly in your system, just go to the plentyMarketplace which offers you the plugins you'll need to do that.

So you've downloaded the plugins. Although you've probably already linked your eBay account to your system to create and start listings, you're going to have to link them again. Why, you ask! Well all eBay plugins need to undergo additional authentication.

Without this "bridge", so to speak, these plugins will not be able to interact with your eBay account - or to put it simply: you won't have access to exciting marketing tools like sales promotions!

Once you've installed the plugins and they've been deployed, you can access your eBay sales promotions in the navigation under "Listings".

Clicking on the plus sign gives you access to a new sales promotion.

First you enter a few basic details, like what platform and what account you want the sales promotion to be run from, what you want it to be called, and the priority you want to give it. So if you're running several promotions simultaneously and sell an item, the priority will decide which sales promotion will apply.

The start and end dates of your promotion are solely up to you.

Now it's time to define the "rules" which are basically the factors that have to be met for your customer to be eligible for the deal.

So for example, you can offer your customer a 10-euro discount if they buy more than 3 items.

Or you don't stipulate any condition at all and just offer a 20% discount.

All that's missing now is the inventory you want the sales promotion to apply to.

If you don't want to offer all your products at a discount, you've a got a few different filter options to work with.

Select what platform you want the filters to apply to, so for example eBay categories. Now choose the particular category and click the "add filter" icon to specify the condition of the items.

AAAND you can exclude certain listings from the get-go. To do so, simply specify the SKU or listing IDs.

Ready? Perfect! Now just check and see if all the details you entered are correct. Because after you've saved the settings, there will be a few things you won't be able to change. But even if you do discover a mistake, it's not that big of a deal because your promotion is initially saved as a draft. That way you can plan and set up all of your different sales promotions before they go live. The only exception is if your starting time is "now".

And once you're ready to present your sales promotion to the masses, simply open it and you'll be able to see the listings you've included in your promotion with the preview function, you'll be able to start the promotion, pause it, or cancel it, or delete it completely.

Now that you know how to create promotions in your system - off you go, treasure seeker! Your fortune awaits!
--
//end::transcript[]
