= Setting up and managing storage locations
:lang: en
include::{includedir}/_header.adoc[]
:position: 10010
:url: videos/stock-management/setting-up-and-managing-storage-locations
:id: 29WAZ4D
:author: team-stock

//tag::einleitung[]
[cols="2, 1" grid=none]
|===
|Your items aren't just floating around in space, but are found in specific storage locations. Learn how to replicate your warehouse layout in plentymarkets using dimensions.
|<<videos/stock-management/setting-up-and-managing-storage-locations-create-warehouse#video, Create a new warehouse (0:56)>>

<<videos/stock-management/setting-up-and-managing-storage-locations-create-dimensions#video, Create dimensions (2:12)>>

<<videos/stock-management/setting-up-and-managing-storage-locations-create-storage-locations#video, Create storage locations (3:33)>>

<<videos/stock-management/setting-up-and-managing-storage-locations-print-labels#video, Printing labels (4:45)>>
|===
//end::einleitung[]

video::271444664[vimeo]

// tag::transkript[]
[.collapseBox]
.Transcript
--
The endless depths of stock management ... (spacey, wheeeee)
As your items float through the vast expanse, your inventory is sometimes swallowed by the odd black hole. There's not much you can do about it... Or can you?

Of course you can!
It's post big bang and over time your items have become well organised. They're located on specific shelves in specific zones in specific WAREHOUSES.
Your stock management is a cosmos born from your own creation.

There are warehouses ...
... with different purposes ...
... in which items have been sorted in different dimensions and precise storage locations.

Since your warehouses are route-optimised, mistakes are reduced to a minimum and your employees can go about the picking process to get your items to your customers as quickly as possible.
Now how to begin this great endeavour of creating your own warehouse galaxy?

Well you can build on these pre-existing galaxies ...
.. or start fresh by creating a new one! A NEW warehouse ... needs a name.

And since every life form and system needs a specific set of parameters to function, you'll also need to specify a warehouse type. The fundamental question? What is the purpose of this warehouse?
The sales warehouse is sort-of a handy all-rounder where you store items that are for sale. Plus, it allows you to use automatic processes, such as stock reservation and order status changes.

But maybe you need a place to store defective items that need to be repaired before they're sent out into the great wide open. The nice thing about a repair warehouse is that its stock is not communicated to your online store or other platforms which means that those items cannot be sold.
Different warehouse types have different functions. Just check out our manual for more in-depth information.

For our purposes though, we'll be setting up a sales warehouse.
Another fundamental question: what great enterprise manages your warehouse?
Well, if you're not using a third-party such as Amazon FBA or DHL to fulfill your orders, select OWN warehouse here.

A new warehouse is born! But this vast empty space still needs something ... items - but not just yet!
You need to create a layout first. With up to 10 dimensions like zones ... racks ... shelves and so on, you've got almost all the possibilities under the sun to create storage locations, so the exact place an item is actually stored before being sold!

Every new warehouse ... initially shows 2 example dimensions. They are not part of your layout per se, but they can be saved as is, adapted to the structure you want or simply deleted. But remember, you're going to need at least one dimension to create storage locations.
Every galaxy is structured according to a certain logic. Once you know how you're going to structure your dimensions, the galactic rule is to create them from smallest to largest.

Let's use the example dimensions as a basis, so we'll start with a shelf ... and a rack. Just know that you can adapt them to your specific needs.
Now we'll create a zone ... with a logical prefix, so Z ... and choose the separator we want to divide the prefixes.

Once you've ADDED your new dimension, you can clearly see that they've all been listed in order from smallest to largest. That's why you create the smallest one first because anytime you create a new dimension, it will supersede any other pre-existing dimensions.
Up here, the preview shows the rack, shelf and storage location - again, in the order from largest to smallest. If you're working with more than one of the same dimensions, like the 2 zones, it makes sense to display the dimension in the name like so.

The same goes for route-optimised picking. It's also usually helpful for the position of the dimension to be taken into account in your route-optimized pick path.
After a quick save ... all of your new dimensions are available in your system ...
... and you can begin creating storage locations.

But how does plenty know how many different zones or shelves or whatnot you need? Well your not the master of this galaxy for nothing!
When configuring the dimensions to generate storage locations, you'll need to consult your warehouse layout to make sure you're setting everything up according to plan.

Right, so I said that this warehouse only has two zones, which I've named Zone 1 and Zone 2. But I could just as easily have named them Zone A and B. Again, check the manual to see what values are admissible.
The start position refers to where you'll begin the pick path. In this example, that's Zone 1.

Alright, now do that with EVERY dimension ...
So each Zone includes four racks ... and each rack includes three shelves.

Now to those actual storage locations. According to my layout, I've planned storage locations A through Z. And as always in my case, I'll start with position 1.
As soon as you click save, your system will instantly preview the first and last 500 storage locations. Spot check the list to make sure the structure is right ... Looking good!

Now get ready to create you're very own warehouse galaxy!
Your system generates storage locations in the background. And depending on how many combinations you've got, it might take a short while before your storage locations are displayed correctly.

Now speaking of displaying things ... printing labels for your storage locations is super practical.
All you have to do is configure the labels the way you want beforehand.
Simply scan your items and their storage locations ...
... to automatically book merchandise into your system.

Right on! Now that you know how to configure dimensions to set up storage locations in your system, it's time to ring in a new era with a bang ... (BANG!) Time to be the master of your e-commerce universe! (and hurtle your products to their buyers along intergalactic superhighways!)
--
//end::transkript[]
