= Split - Sending processes down two different paths
:lang: en
include::{includedir}/_header.adoc[]
:position: 10090
:url: videos/automation/processes/split
:id: LTQTCDR
:author: team-mobile

//tag::einleitung[]
[cols="2, 1" grid=none]
|===
|Introducing the control element split! It checks whether your orders meet specific criteria and then sends them down one fulfillment path or another.
|

|===
//end::einleitung[]

video::225362548[vimeo]

// tag::transkript[]
[.collapseBox]
.Transcript
--
Why not kill two birds with one stone? Use Dr. Process' superpowers to tackle two jobs at once! Want to create a process that simultaneously fulfills orders for two different shipping providers? Or step-up your processes with two different plans of attack? It's split time! No, not the latest fitness craze.
It's Dr. Process' next superpower!

As the name suggests, this control element allows you to split up your process into two different paths.
Which path an order takes depends on whether it meets certain criteria.
For example, whether the order is shipped by a specific provider.
We'll practice using our power on this very simple example process, which only fulfills one order. Think of this as the training ground where you'll be introduced to the split before seeing its full range of power in a more realistic example.

Imagine you ship most of your items with DHL.
But you also sell a few specialty items, which are shipped with DPD.
Our split here makes sure that every item ends up with the correct shipping label. The split checks whether the order meets specific criteria - in this case, being shipped with DHL. If the order meets the criteria, then it takes the path to the right and lands in the shipping center, where the shipment is registered with DHL and a shipping label is printed.
If the order doesn't meet the criteria, then it follows the path further down and a polling file is generated for DPD.
The jump here prevents the order from continuing on and getting a DHL shipping label too.
Instead the order jumps down here to the end.

Now let's try out this example process and see what happens.
When I click on "Start", plentymarkets first prompts me to search for whichever order I want to work with.
Once I've found the correct order, my split will spring into action and figure out whether it should be shipped with DHL or DPD.
And it was DPD! A polling file has been generated and saved on my computer.

Now that you understand how the split works, let's put it to the test in a more complex process.
Here we can find our split towards the very end.
Its job is to check whether all of the items and serial numbers have been correctly registered.
If they have, then we take this path here, which leads back to the pick list search.
On the other hand, if there are any items or serial numbers that haven't been registered yet, then we take the path further down and the process jumps back up to the item registration window.

Of course, it's your call when you want to split a process and which criteria should separate one path from the other. Try out several different filters to get a feel for how you can steer your fulfillment process in one direction or another.
--
//end::transkript[]
