= What are work steps?
:lang: en
include::{includedir}/_header.adoc[]
:position: 10040
:url: videos/automation/processes/work-steps
:id: BUOSZYI
:author: team-mobile

//tag::einleitung[]
[cols="2, 1" grid=none]
|===
|Every process always includes at least one work step. But there are three different types to choose from. Which one should you pick? How do the three types differ?
|<<videos/automation/processes/work-steps-group#video, Order group processing (0:47)>>

<<videos/automation/processes/work-steps-single#video, Single order processing (3:18)>>

<<videos/automation/processes/work-steps-incoming#video, Incoming items (4:36)>>

|===
//end::einleitung[]

video::223469587[vimeo]

// tag::transkript[]
[.collapseBox]
.Transcript
--
You gotta have the right tools for every job.
Dr. Process' sword, for example, is great when attacking opponents.
But pretty useless when our hero needs to defend himself.
When in trouble, Dr. Process is better protected with his shield and battle armor.
And once he's caught the bad guys, his truth serum is just the right tool for cutting through lies.
Every tool is particularly well-suited for a specific task. You just gotta have the right tools for the job.

The same can be said of work steps in plentymarkets.
When creating a new work step, you'll notice that there are three different types to choose from. And each type is particularly well-suited for a specific task.
As the names suggest, you can either add a work step for tackling several orders at once, for modifying one order at a time, or for dealing with incoming items.

If that's still a bit abstract, try thinking about your company's own fulfillment process. When collecting items from your warehouse, it would be pretty inefficient to pick items for one order at a time.
Instead, it makes a lot more sense to print one long pick list - say, for the next 20 orders that are ready to be shipped.
And then to walk through your warehouse and collect items for all of these orders at the same time.
And that's exactly what is meant by a work step that tackles several orders at once.

Let's take a look at its settings.
The top portion of this window is used for saving some basic information about your work step, like its name and how many orders should be included in one cycle of the process.

The bottom left portion of the window is for saving filters. Think of this area as telling plentymarkets which exact orders should be included in the process.
The drop-down menu includes a wide range of possible filters, such as orders that are going to be delivered to a specific country, orders that are included in a loyalty program like Amazon Prime or orders that are currently in a specific status, like status 5.
Keep adding filters the same way until you've finished narrowing down the orders that should be included in your process.

Then use the bottom right portion of the window to tell plentymarkets what should happen to the orders once they've been processed.
Essentially, tell plentymarkets whether you want to change the orders' status, owner or flag.
Make sure that you select at least one option here because doing so prevents the process from being carried out in an endless loop.
For example, I've told plentymarkets to carry out this process for all orders that are currently in status 5. If I don't make the order status change at the end of the process, then this work step would just end up processing the same orders over and over.

OK and since I'm going to be printing a pick list with information about 20 different orders, I'll use this option here to tell plentymarkets just how I want these orders arranged on that pick list.
Alright, that's all there is to it! But now what? Once you've printed a pick list, what next?
Realistically, your own processes will probably be composed of several different work steps. In this case, you'll need to use this "Next step" drop-down to specify how one work step should transition into the next.
Once a work step has finished, the next step can either be started automatically or the process can be paused until the next step is started manually.
Once you've finished editing your work step, it will be created and you can add further elements to it.

Back in our warehouse, we've finished collecting items from the shelves and we're ready to put the finishing touches on each individual order.
For example, we're ready to scan each order's barcode, place the relevant documents in our package and book it as outgoing.
This is the idea behind our work step for processing one order at a time.

The settings here are pretty minimal.
Just enter a name and tell plentymarkets how it should transition into the next step of the process.
The only thing that you really need to keep in mind about this work step is that it only processes one order at a time.
And plentymarkets will only know which order is being processed, if you add an "order search" procedure directly after it.
Once you're done, add further elements to your work step.
So during this portion of the process, an entry field appears on the screen and my warehouse technician scans the barcode for the first order.
Doing so automatically generates all of the relevant documents for this one specific order. And my warehouse technician places these documents in the package.
Finally, the order is booked as outgoing and my process jumps back up here and waits for the second order barcode to be scanned.

Here in this example, you can see the difference between a work step that processes several orders at once and a work step that processes one order at a time.
But what about the third type of work step? What's that used for?
Well, to answer that question, let's think about a different example. This time imagine that your most popular item has run out of stock.
You've re-ordered the item from your supplier and finally the delivery has arrived!
Now you'll need some sort of process, which allows you to book the item back into stock.
And that's exactly the idea behind this "incoming items" work step. It comes in handy whenever you need to book items back into stock.
Like I said, you gotta have the right tools for the job. Regardless whether you're tackling several orders at once, modifying one order at a time, or dealing with incoming items, plentymarkets processes give you the right tools to get the job done.

--
//end::transkript[]
