= Cloud usage
:keywords: Usage, usage data, Cloud usage, cloud
:author: team-app-bi
This page explains the calculation types, dimensions and filters available to you for the key figure Cloud usage.

Item images, receipts, order documents and a variety of other data of your plentymarkets system are stored in the cloud. This kind of storage is limited depending on your plentymarkets edition. You will be billed separately if you exceed the amount of memory available to you. This is why you can track the cloud usage of your plentymarkets system uses at any time.

:key-figure: The cloud usage

include::partial$key-figure-introduction.adoc[]

[IMPORTANT]
.Using the default key figure
====
The key figure *Cloud usage* is a so-called default key figure. This means that it is already set up in your system with some preparatory settings. Thus, you don’t necessarily have to create an additional key figure. Go to *Setup » plentyBI » Key figures* and click on the key figure *Cloud usage* that has been created by `plentymarkets`. If needed, adjust the preselected options and add the desired <<#300, filters>>.
====

[#100]
== plentyBI edition

This key figure is free of charge.
So you can use the key figure without having to book a plentyBI edition first.

However, note that _other functions and key figures_ cost money in the plentyBI tool.

Simply choose the right plentyBI edition with the help of the plentymarkets configurator.

* *_New customers_*: Choose the appropriate plentyBI edition link:https://get.plentymarkets.com/[while you order plentymarkets^].
* *_Existing customers_*: Choose the appropriate plentyBI edition xref:business-decisions:your-contract.adoc#30[in the "My account" area].

[#150]
== Calculation

=== Number of items

The cloud usage is calculated based on the number of items that have been created in your plentymarkets system.

=== Number of variations

The cloud usage is calculated based on the number of variations that have been created in your plentymarkets system.

=== CDN traffic

The cloud usage is calculated based on the CDN traffic that is generated e.g. when customers access content in your online store.

=== Database storage

The cloud usage is calculated based on the memory of the database storage currently used by your plentymarkets system.

=== Document storage

The cloud usage is calculated based on the memory of the document storage currently used by order documents and receipts of your plentymarkets system.

=== Web content storage

The cloud usage is calculated based on the web content that is saved in your plentymarkets system.

[#200]
== Dimension

=== Creation date

:key-figure: The cloud usage
:this-means: This means that usage data is grouped by the date on which the usage was caused.

include::partial$creation-date.adoc[]

[#300]
== Filters

include::partial$filter-introduction.adoc[]

=== Creation date

Use this filter to group cloud usage by the date or period of time in which the usage was caused.

Select one of the following comparison operators and then select the desired date or time period on the right.


[.collapseBox]
.Comparison operators available for this filter
--

:filter-ending: dates selected
:filter: dates selected
:commas:

[cols="1,3"]
|====
| Comparison operator | Explanation

include::partial$is-equal-to.adoc[]

include::partial$is-between.adoc[]

include::partial$greater-than-or-equal-to.adoc[]

include::partial$less-than-or-equal-to.adoc[]

include::partial$greater-than.adoc[]

include::partial$less-than.adoc[]


|====

--

//Praxisbeispiel (mit Kachel) hinzufügen
