= GDPR
:lang: en
include::{includedir}/_header.adoc[]
:description: Via this page, download an abridged version of the record of processing activities within plentymarkets in accordance with GDPR.
:keywords: DSGVO, GDPR, data protection, data protection regulation, record of processing activities, processing directory, May 25, 2018, person-related data, processing documentation
:position: 20
:url: business-decisions/legal-requirements/gdpr
:id: 8NCZ7LJ
:author: team-crm

This page of the manual includes a download link of an abridged version of the record of processing activities with plentymarkets in accordance with GDPR.

[#100]
== What is GDPR?

As of May 25, 2018, the link:http://data.consilium.europa.eu/doc/document/ST-5419-2016-INIT/en/pdf[General Data Protection Regulation^]{nbsp}icon:external-link[] goes into effect throughout Europe and thus replaces all national regulations.

The GDPR applies to all companies operating in the European Union and processing personal data such as names, bank data and address data. It requires companies to organise and document any processes where personal data is processed in line with the GDPR.

[#200]
== Important notes

Note that this record only contains the processing activities within the software plentymarkets. You will need to add the names and descriptions of any other processing activities that take place within your company (e.g. payroll accounting or processes within other software programs).

plentymarkets makes no claim to completeness regarding this record. It is intended to be a supplement when creating your own record of processing activities.  

Please note that only *plentymarkets systems as of version 7* are GDPR compliant. The plentymarkets online store plugin *plentyShop LTS* will be GDPR compliant after the checkbox for consenting to the data transmission to shipping service providers has been added with the release of *version 2.9.0*.

[#300]
== Download link

link:https://cdn02.plentymarkets.com/pmsbpnokwu6a/frontend/plentymarkets_Rechtliches/Processing_directory_for_customers.pdf[Download the document^]{nbsp}icon:external-link[] as a supplement to your own record of processing activities (link:https://github.com/plentymarkets/template-processing-directory/releases[version history^]{nbsp}icon:external-link[]). This document only describes the processing activities within the software plentymarkets.  


[#500]
== Contract for processing acc.to art. 28 §3 General Data Protection Regulation (GDPR)

On Thursday, 24th of May, 2018, plentymarkets is updated in order to manage the conclusion of contracts for processing according toarticle 28 § 3 of the General Data Protection Regulation (GDPR) in a digital fashion. The contract is concluded digitally in the *My Account* area of link:https://marketplace.plentymarkets.com/en[plentyMarketplace^]{nbsp}icon:external-link[].

[.instruction]
Concluding the contract digitally:

. Go to *plentymarkets Logo (Start) » My account*.
. Click on *Contracts* (icon:file-text[role="darkGrey"]).
. Click on the tab *Documents* (icon:pencil[role="darkGrey"]).
. Click on the contract *Vertragsanlage zur Auftragsverarbeitung (DS-GVO) Juli 2019*. It is only available in German.
. Download the contract.
. Enter your name and submit the form. This concludes the contract.

This process forgoes the need for concluding the contract by mail, thereby saving time and money.

After the contract has been concluded, you can download a version of the contract including the name of the signatory and the date of the contract conclusion. Simply access the *Contracts* (German: Verträge) area again and click on *Vertragsdokument signiert herunterladen* (translation: Download contract with signature).

Please keep this document for the purpose of contractual documentation.

For further information, refer to this link:https://forum.plentymarkets.com/t/vertragsanlage-zur-auftragsverarbeitung-i-s-d-art-28-abs-3-datenschutz-grundverordnung-dsgvo/483954[forum thread^]{nbsp}icon:external-link[].

[#600]
== Change history for contact data

In the *Data » Change history* menu, a new change history is available via which you can see which user – for example, an employee or the customer in the online store – has changed data. This can be addresses, contact options, address options, company data and bank data, for example.

For further information, refer to this link:https://forum.plentymarkets.com/t/dsgvo-aenderungshistorie-fuer-kontaktdaten-integriert/486705[forum thread^]{nbsp}icon:external-link[].

[#700]
== Transferring the email address and telephone number of the customer to shipping service providers

Please note that plentymarkets as a software must comply with the principle of _Privacy by default_ in accordance with GDPR. This is why we generally implemented the setting that this data (email and telephone number) is not transferred to the shipping service providers. This means that you can choose from now on whether the data of your customers is transferred or whether you want to transfer an alternative value. Or simply leave the default setting and do not transfer this data.

For further information, refer to this link:https://forum.plentymarkets.com/t/dsgvo-uebertragung-von-e-mail-adresse-und-telefonnummer-an-versanddienstleister/486536[forum thread^]{nbsp}icon:external-link[]. At the bottom of the thread, you will find a button to expand the English version.

[#800]
== Downloading all data of a contact or guest account

In the *CRM » Quick search* menu, it is possible to download a ZIP file with all data and documents that are saved for a contact. This can be done with simply one click. The ZIP file contains an HTML file that you can open in your browser and via which you can download all documents. Furthermore, it is possible to save the data in a machine-parsable format.

For further information, refer to the <<crm/quick-search#download-all-data, Quick search>> page.

[#900]
== Automatically cleaning up data

Go to the *Setup » Settings » Hosting » Cleansing* menu and determine the time period after which certain data records are automatically deleted from your plentymarkets system. Step by step, further areas will be added to this menu.

You can also delete tickets automatically from your ticket system. This setting is not carried out in the *Setup » Settings » Hosting » Cleansing* menu, but via the procedure manager in the ticket system in the *Setup » CRM » Ticket system » Procedures* menu. Further information about the ticket system as well as an example scenario can be found on the <<crm/using-the-ticket-system#3000, Using the ticket system>> page.

[#1000]
== Manually anonymising data records

In the *CRM » Quick search* menu, it is possible to remove data of a contact respectively to make this data illegible in such way that no reference to this specific person is given any longer.

*_Exception:_* If address data is assigned to an order, this data will not be removed or made illegible due to tax reasons. However, the contact relation will be deleted.

For further information, refer to the <<crm/quick-search#ananomyise-data-record, Quick search>> page.
