= Usage data
:keywords: Host, Hosting, Hoster, Web hosting, Hosting data, Data volume, Traffic, Storage use, Resources
:description: Learn more about usage data and how traffic is generated.
:author: team-cloud

The data volume and allowed traffic provided to you depends on your plentymarkets edition. You will be billed if you exceed the amount of memory available to you. As such, you can track the data volume your plentymarkets system uses at any time.

Usage data is displayed in the menu *plentymarkets Logo (Start) » Hosting*.
Click on one of the sub-menus on the left to access the corresponding data.

[TIP]
.Displaying usage data in the dashboard
====
Did you know that you can display the usage data of your plentymarkets system on your dashboard as well?
To do so, start by setting up the free key figure xref:business-decisions:traffic-usage.adoc#[Traffic usage]. Then, place an element of the type xref:business-decisions:myview-dashboard.adoc#500[tile] on your dashboard to view the key figure and your usage conveniently at any time.
====

[#100]
[discrete]
=== Information about traffic

Traffic is generated every time a person visits your online store, clicks on various items, clicks on images to enlarge them, downloads files, etc.

Additional traffic is generated in the following cases:

* When exchanging data with markets.
* REST calls, since they create connections to the server. +
*_Tip:_* Depending on the type of call, they may generate a substantial amount of traffic. You should optimize your calls, e.g. so that you do not retrieve all of the information, but rather only the changes.
* When your website is scanned by link:https://en.wikipedia.org/wiki/Web_crawler[bots^]. The bots save your pages, which results in traffic. For example, a Google bot does this so that Google can find items from your store along with their descriptions. Bots are controlled by proprietary algorithms, which makes it impossible to predict when such bots will visit your website. +
*_Tip:_* To take some control of bot behaviour, you can xref:online-store:setting-up-ceres.adoc#203[block bots] by using the robots.txt file.
* If your product portfolio has expanded, resulting in more data and images. This will cause more bots to crawl your site.
