= Items below reorder level (Live)
:keywords: Reorder level, items below reorder level, reorder level (Live), business intelligence, statistics, key figure, key figures, dashboard
:description: This page explains the calculation types, dimensions and filters available to you for the key figure Items below reorder level (Live).
:author: team-app-bi

:key-figure: Items below reorder level (Live)

include::partial$key-figure-introduction.adoc[]

plentymarkets calculates the live number of items per warehouse whose stock is lower than the determined reorder level by checking and loading stocks from the database in real time.

[IMPORTANT]
.Using the default key figure
====
The key figure *Items below reorder level (Live)* is a so-called default key figure. This means that it is already set up in your system with some preparatory settings. Thus, you don’t necessarily have to create an additional key figure. You can find the key figure configuration in the *Setup » plentyBI » Key figures* menu. There, the entry for the key figure *Items below reorder level (Live)* that has been created by `plentymarkets` is displayed.
====

[#100]
== Calculation

=== Total

:key-figure: The key figure Items below reorder level (Live)
:that-means: This means that the items are counted according to the selected dimension and filters, summed up and displayed in real time.

include::partial$total.adoc[]

[#200]
== Dimension

=== Warehouse

The item quantity is displayed in real time for each warehouse.
The data is taken from the database.
