= Listings (Live)
:keywords: Listings, market listings, listings live, check listings live, listing status, listings key figure, business intelligence, statistics, key figure, key figures, dashboard
:description: This page explains the calculation types, dimensions and filters available to you for the key figure Listings (Live).
:author: team-bi

:key-figure: Listings (Live)

include::partial$key-figure-introduction.adoc[]

plentysystems calculates the live quantity of listings by checking all listings and their status on the respective market and loading the results from the database in real time. 

[IMPORTANT]
.Limited data availability
====
The results of this key figure are limited to a period reaching from the previous day to the current day. Thus, it’s not possible to view data from earlier periods.
====

[#100]
== Calculation

=== Total

:key-figure: The key figure Listings (Live)
:that-means: This means that the listings are counted according to the selected dimension and filters and displayed in real time.

include::partial$total.adoc[]

[#200]
== Dimension

=== Listings

The number of listings is taken from the database in real time.

[#300]
== Filters

Using the following three filters, you can limit the results of the key figure Listings (Live) according to your needs.

=== Successful

Select the filter *Successful* along with the comparison operator *Is equal to* and the option *Successful* to filter for listings that have been successfully published. Alternatively, use the option *Not successful* to filter for unsuccessful listings.

=== Marketplace

Select the filter *Market* along with the comparison operator *Corresponds to one of these values* and the option *Market* to filter for one, several or all markets on which you are listing items. Alternatively, use the comparison operator *Corresponds to none of these values* to exclude selected markets from the evaluation of the listings.

=== Verification

Select the filter *Verification* along with the comparison operator *Is equal to* and the option *Succeeded* to filter for listings that have passed the verification process on the respective market. Alternatively, use the option *Failed* to filter for listings that failed the verification process.




