= Orders (Live)
:keywords: live orders, realtime, real time, orders, number of orders, quantity, quantity of orders, Business Intelligence, BI, statistics, key figure, key figures, Dashboard
:page-aliases: orders-live.adoc
:description: This page explains the calculation types, dimensions and filters available to you for the key figure Orders (Live).
:author: team-app-bi

:key-figure: Orders (Live)

include::partial$key-figure-introduction.adoc[]

plentysystems calculates the live number of orders by checking and loading the orders from the database in real time. +
In addition, select a xref:business-decisions:live-orders.adoc#200[dimension] to determine how the result is grouped.
Set xref:business-decisions:live-orders.adoc#300[filters] to specify the criteria for the calculation of the sales volume.
Note that those orders are counted that you define in the filter *Order type*. If you don't set this filter, all orders of all order types are counted.

[IMPORTANT]
.Using the default key figure
====
The key figure *Orders (Live)* is a so-called default key figure. This means that it is already set up in your system with some preparatory settings. Thus, you don’t necessarily have to create an additional key figure. Go to *Setup » plentyBI » Key figures* and click on the key figure *Orders (Live)* that has been created by `plentymarkets`. If needed, adjust the preselected options and add the desired <<#300, filters>>.
====

[#400]
== plentyBI edition

include::partial$key-figure-requirement-edition.adoc[]

[#100]
== Calculation

=== Total

:key-figure: The key figure Orders (Live)
:that-means: This means that the number of orders is counted according to the selected dimension and filters and displayed in real time.

include::partial$total.adoc[]

[#200]
== Dimension

=== Order

The number of orders is displayed in real time. The data is taken from the database. All order types are counted if you don't set the filter *Order type* with a selection.


=== Order status, order

The number of orders in each order status is displayed in real time. The data is taken from the database. All order statuses are counted if you don't set the filter *Order status* with a selection.


[#300]
== Filters

include::partial$filter-introduction.adoc[]

// Order referrer

include::partial$order-referrer.adoc[]

// Order status

include::partial$order-status.adoc[]

_Note_ that all order statuses are displayed if you don’t select anything here.

// Order type

include::partial$order-type.adoc[]

// Created

include::partial$created.adoc[]

//Warehouse

include::partial$warehouse.adoc[]

Note that main orders are filtered out if this filter is set.

// Client

include::partial$client.adoc[]

// Outgoing items booked

include::partial$outgoing-items-booked.adoc[]

// Payment status

include::partial$payment-status.adoc[]
