= Payments (Live)
:keywords: payments, payments in real time, incoming payments in real time, number of payments, received payments, business intelligence, statistic, statistics, key figure, key figures, dashboard
:description: This page explains the calculation types, dimensions and filters available to you for the key figure Payments (Live).
:author: team-app-bi

:key-figure: Payments (Live)

include::partial$key-figure-introduction.adoc[]

plentymarkets calculates the live number of payments by checking and loading incoming payments, the payment status and the payment method from the database in real time. +
In addition, select a xref:business-decisions:live-payments.adoc#200[dimension] to determine how the result is grouped.
Set xref:business-decisions:live-payments.adoc#300[filters] to specify the criteria for the calculation of the sales volume.

[IMPORTANT]
.Using the default key figure
====
The key figure *Payments (Live)* is a so-called default key figure. This means that it is already set up in your system with some preparatory settings. Thus, you don’t necessarily have to create an additional key figure. Go to *Setup » plentyBI » Key figures* and click on the key figure *Payments (Live)* that has been created by `plentymarkets`. If needed, adjust the preselected options and add the desired <<#300, filters>>.
====

[#100]
== plentyBI edition

include::partial$key-figure-requirement-edition.adoc[]

[#200]
== Calculation

=== Total

The key figure Payments (Live) is calculated on the basis of all available data. This means that payments are counted according to the selected dimension and filters, summed up and displayed in real time.

[#300]
== Dimension

=== Payments

The number of payments is displayed in real time. The data is taken from the database.

=== Current payments

//TODO

=== Payment, payment method

The number of payments as well as their respective payment methods available in the system are displayed in real time. The data is taken from the database. If you don’t set the filter *Payment method* and don’t make a selection for the filter, all payment methods will be included.


[#400]
== Filters

include::partial$filter-introduction.adoc[]

// Assigned

include::partial$assigned.adoc[]

// Received at

include::partial$received-at.adoc[]

// Imported at

include::partial$imported-at.adoc[]

// Assigned at

include::partial$assigned-at.adoc[]

// Payment method

include::partial$payment-method.adoc[]