= Payments (Live)
:keywords: payments, payments in real time, incoming payments in real time, number of payments, received payments, business intelligence, statistic, statistics, key figure, key figures, dashboard
:description: This page explains the calculation types, dimensions and filters available to you for the key figure Payments (Live).
:author: team-app-bi

:key-figure: Payments (Live)

include::partial$key-figure-introduction.adoc[]

plentymarkets calculates the live number of payments by checking and loading incoming payments, payment status and the payment method from the database in real time. +
In addition, select a xref:business-decisions:live-payments.adoc#300[dimension] to determine how the result is grouped.
Set xref:business-decisions:live-payments.adoc#400[filters] to specify the criteria for the calculation of the payments.

[IMPORTANT]
.Using the default key figure
====
The key figure *Payments (Live)* is a so-called default key figure. This means that it is already set up in your system with some preparatory settings. Thus, you don’t necessarily have to create an additional key figure. Go to *Setup » plentyBI » Key figures* and click on the key figure *Payments (Live)* that has been created by `plentymarkets`. If needed, adjust the preselected options and add the desired <<#300, filters>>.
====

[#200]
== Calculation

=== Current and unassigned payments

All payments that have been imported into the system on the current and the previous day are displayed. In addition, all payments that are currently not assigned to an order are displayed.

[IMPORTANT]
.Limited selection
====
If you select the calculation type *Current and unassigned payments*, you can use the <<#400, filters>> described below to further limit the result. However, it is not possible to select a <<#300, dimension>>.
====

=== Total

The key figure Payments (Live) is calculated on the basis of all available data. This means that payments are counted according to the selected dimension and filters, summed up and displayed in real time.

[#300]
== Dimension

=== Payment

The number of payments is displayed in real time. The data is taken from the database.

=== Payment method

The number of payments available in the system as well as their respective payment methods are displayed in real time. The data is taken from the database. If you don’t set the filter *Payment method* and don’t make a selection for the filter, all payment methods will be included.


[#400]
== Filters

include::partial$filter-introduction.adoc[]

// Received at

include::partial$received-at.adoc[]

// Imported at

include::partial$imported-at.adoc[]

// Payment method

include::partial$payment-method.adoc[]

// Assigned

include::partial$assigned.adoc[]

// Assigned at

include::partial$assigned-at.adoc[]