= Managing mailboxes
:keywords: Email, mailbox, create mailbox, basic fee, manage mailbox
:description: Working with plentymarkets: manage mailboxes, create new mailboxes and edit already existing mailboxes in the plentymarkets system.
:author: Dennis Schulze

[#10]
== Managing mailboxes

If plentymarkets manages your domains, then you can go to *Settings » Setup » Email* to create and manage mailboxes for system users. You need admin rights to manage mailboxes. These mailboxes are created and hosted by the third party email provider link:https://mailbox.org/business/[mailbox.org^]. You will learn how to create mailboxes and additional email addresses (aliases) for these mailboxes.

[IMPORTANT]
.Mailboxes with other provider
====
The configuration described is only relevant for plentymarkets customers with domains managed by plentymarkets who want to use the external provider link:https://mailbox.org/business/[mailbox.org^]. If you manage your email account with a different provider and want the plentymarkets system to send emails from this provider too, you do not need to set up mailbox.org. However, you still need to refer to the chapter xref:crm:sending-emails.adoc#100[Saving the email server's access data] on the xref:crm:sending-emails.adoc#[Sending emails] page of the manual.
====

[#20]
== Create mailbox

Proceed as described below to create mailbox.org mailboxes for system users. You need admin rights to create mailboxes and aliases.

[.instruction]
Creating a new mailbox:

. Go to *Setup » Settings » Email*.
. Click on *Create mailbox* (material:add[role=green]). +
→ The *Create mailbox* window opens.
. Select the email address type *Mailbox*.
. Carry out the additional settings. Note <<tabelle-postfach>>.
. Click on *Create mailbox*. +
→ The mailbox is created on the servers of the external provider mailbox.org.

[[table-mailbox]]
.Create mailbox
[cols="1,3"]
|====
|Setting |Explanation

| *Email address type*
|Select the email address type *Mailbox*. +
*Mailbox* = A new mailbox is created. +
*Alias* = An additional email address for an existing mailbox is created. Select the mailbox for this alias by selecting the option *Target mailbox*.

| *Email address*
|Enter the email address that you want to assign to this mailbox. Enter the local part of the email address left of the @ sign. Select the domain part of the email address from the dropdown list. +
*_Note:_* You cannot create mailboxes for test domains (for example @plenty-test-drive) or for external domains that are not hosted by plentymarkets. +
*_Note:_* After an email address is deleted, this address is locked for 48 hours. You need to wait until the end of this period before you can create an email address with this name again.

| *First name* +
*Last name*
|Enter the first name and last name of the person with this user account. This name will be displayed with the email address as part of the sender information.

| *System user*
|Select the user account you want to assign the mailbox to.

| *Forwarding*
|Enter one or more email addresses if you want to forward emails sent to this address to a different mailbox. Separate multiple email addresses by commas, for example customer@your-plentystore.co.uk,consultant@your-plentystore.co.uk.

| *Save emails in mailbox*
|Option becomes selectable once a forwarding address is entered. +
Activated = Emails are forwarded to the target email addresses. Copies of the forwarded emails will be saved in this mailbox. +
Not activated = Emails are directly forwarded to the target email addresses. No emails are saved in this mailbox.

| *Password*; +
*Repeat password*
|Enter a password and re-enter it for confirmation. +
*_Note:_* The password has to contain at least 8 characters and a combination of upper case letters, lower case letters and numbers.

| *Rate*
|Select a fee model. All prices shown are subject to VAT. Your plentymarkets contract will be updated after the mailbox is created.
|====

[#25]
=== Saving the mailbox.org server's access data in plentymarkets

In order to plentymarkets sending emails (like order confirmations) for you, you have to save the login details of the mailbox.org mailbox that should send the emails under *Setup » Assistants » Basic setup*.

[#30]
== Creating an additional email address (alias) for a mailbox

Create an alias for the mailbox if you want the mailbox to be linked to more than one email address. The number of email addresses you can create per mailbox depends on the fee you select. Proceed as described below to create an additional email address for a mailbox.

[.instruction]
Creating an additional email address for a mailbox:

. Go to *Setup » Settings » Email*.
. Click on *Create mailbox* (material:add[role=green]). +
→ The *Create mailbox* window opens.
. Select the email address type *Alias*.
. Carry out the additional settings. Note <<#table-email-addresses>>.
. Click on *Create mailbox*. +
→ The additional email address is created.

[[table-email-addresses]]
.Creating an additional email address for a mailbox
[cols="1,3"]
|====
|Setting |Explanation

| *Email address type*
|Select the email address type *Alias*. +
*Mailbox* = A new mailbox is created. +
*Alias* = An additional email address for an existing mailbox is created. Select the mailbox for this alias by selecting the option *Target mailbox*.

| *Email address*
|Enter the email address that you want to assign to this mailbox. Enter the local part of the email address left of the @ sign. Select the domain part of the email address from the dropdown list. +
*_Note:_*After an email address is deleted, this address is locked for 48 hours. You need to wait until the end of this period before you can create an email address with this name again.

| *Target mailbox*
|Select the mailbox that emails to this alias address are to be sent to.
|====

[#35]
== Entering SPF and DKIM entries

You can enter SPF and DKIM entries in the domain assistant to increase the spam reputation of your domain. Proceed as follows to enter your SPF and/or DKIM entries in the domain assistant:

[.instruction]
Entering the SPF entry

. Go to *Setup » Assistants » Basic setup » Domains*.

. Open the domain where you want to enter the SPF entry. +
→ The domain settings open up.
. Click on *Settings for an external mail server*
. Enter you SPF entry under *SPF*.
[TIP]
.SPF of mailbox.org
====
If your mailbox provider is mailbox.org you can use \`v=spf1 mx include:mailbox.org ~all\` as SPF entry. You can copy it and enter it under *SPF*.
====
. Click on *Summary*.
. Click on *Complete*. +
→ The SPF entry is saved.

[.instruction]
Entering the DKIM entry

. Go to *Setup » Assistants » Basic setup » Domains*.
. Open the domain where you want to enter the DKIM entry. +
→ The domain settings open up.
. Click on *Configure TXT Records*
. Enter the DKIM entry under *Target* of a source. +
[TIP]
.DKIM entry for mailbox.org
====
v=DKIM1; k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2K4PavXoNY8eGK2u61LIQlOHS8f5sWsCK5b+HMOfo0M+aNHwfqlVdzi/IwmYnuDKuXYuCllrgnxZ4fG4yVaux58v9grVsFHdzdjPlAQfp5rkiETYpCMZwgsmdseJ4CoZaosPHLjPumFE/Ua2WAQQljnunsM9TONM9L6KxrO9t5IISD1XtJb0bq1lVI/e72k3mnPd/q77qzhTDmwN4TSNJZN8sxzUJx9HNSMRRoEIHSDLTIJUK+Up8IeCx0B7CiOzG5w/cHyZ3AM5V8lkqBaTDK46AwTkTVGJf59QxUZArG3FEH5vy9HzDmy0tGG+053/x4RqkhqMg5/ClDm+lpZqWwIDAQAB
====
*Or*: if you have no source yet, create one by clicking on *Add new entry* (material:add[]). +
[start=5]
. Click on *Summary*. +
*Or*: if you have no source yet, create one by clicking on *Add new entry* (material:add[]).
. Click on *Summary*.
. Click on *Complete*. +
→ The DKIM entry is saved.


[#40]
== Change basic fee

By default, the basic fee *Business Reseller* applies to the hosting of mailboxes by mailbox.org through plentymarkets. This basic fee is free. However, it does not include support by mailbox.org. You can change your basic fee at any time. Change your basic fee model if you want to receive support from mailbox.org or want to extend the services you receive from mailbox.org. The selected basic fee applies to all mailboxes in your plentymarkets system including all clients.

[.instruction]
Changing your basic fee model:

. Go to *Setup » Settings » Email*.
. Click on *Change basic fee* (material:edit[]). +
→ The *Select basic fee* window opens.
. Check the specifications of the different basic fee models.
. Select the basic fee you want to book.
. Click on *Change basic fee*. +
→ The fee is saved and your plentymarkets contract is updated. mailbox.org will send you an email with additional information.

[#50]
== Deleting a mailbox

Proceed as described below to delete a mailbox. You need admin rights to delete mailboxes/aliases. After deleting a mailbox/alias, you need to wait 48 hours before you can create a new mailbox/alias with the email address that you just deleted.

[WARNING]
.Emails can no longer be accessed after deleting a mailbox
====
After deleting a mailbox, you can no longer access the emails saved in the mailbox via mailbox.org. Make sure that you have saved local copies of any emails you still need access to before deleting the mailbox.
====

[.instruction]
Deleting a mailbox:

. Go to *Setup » Settings » Email*. +
→ A list of the mailboxes is displayed.
. Click on the mailbox in this list that you want to delete.
. Click on *Delete* (material:remove[role="red"]). +
→ The mailbox and all associated aliases are deleted on the mailbox.org server. +
→ Your plentymarkets contract is updated.