= Managing reports
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Report, raw data, analyse raw data, create raw data, raw data format
:position: 10
:url: business-decisions/plenty-bi/reports/managing-reports
:id: LAKHMQK
:author: team-bi

A report is a data analysis that determines a single key performance indicator (KPI) or a list of KPIs. The data base for this analysis is an export of raw data at regular intervals. This data is saved on a secure cloud storage.

== Raw data

Raw data is collected in the background, usually over night.  The settings made in the *Setup » plentyBI » Raw data* determine which types of raw data are saved.  You can retrieve the generated files via the REST API and process the data externally.

=== For end users

We have observed that business decisions are often not made based on key figures, but rather intuitively. In order to change this behaviour, we recommend using a business intelligence tool. Ideally, such a tool analyses different data from several sources. Start now and use our integrated plentyBI dashboard to keep track of relevant data and key figures. Further information is available in the <<business-decisions/plenty-bi#, plentyBI>> section of the manual.

=== For developers

Raw data is available in CSV format and can therefore easily be processed.  All plentymarkets systems have a standardised REST API. The documentation is available on link:https://developers.plentymarkets.com/[this page^]{nbsp}icon:external-link[].

Raw data is retrieved in two steps. We recommend retrieving the data once a day after around noon. the process of generating raw data is completed for all systems.

1.	First, a list of available raw data files is retrieved via this link:https://developers.plentymarkets.com/en-gb/plentymarkets-rest-api/index.html#/BI/get_rest_bi_raw_data[route^]{nbsp}icon:external-link[]. The time at which the latest file of the last retrieval was created serves as a filter for the next retrieval so that data is not requested several times. The number of files that are generated per day may vary depending on how many creator processes are activated for a plentymarkets system. Furthermore, only a certain number of data rows is written in each file. If required, a additional file is created. With this route, either all files of a single creator or all files that were created during the retrieval interval are exported.
2.	With this link:https://developers.plentymarkets.com/en-gb/plentymarkets-rest-api/index.html#/BI/get_rest_bi_raw_data_file[route^]{nbsp}icon:external-link[], a raw data file is exported. The required file path is contained in the sample space of the REST route listed in point 1.  Raw data files are provided as a GZIP-compressed CSV file (RFC 1952). A comma is used as column separator.

[TIP]
.Standard time stamp format
====
The standard date format is MM/DD/YYYY HH:MI:SS TZ. This date format can be copied directly to an AWS Redshift column of the type TIMESTAMPTZ. Example: 01/30/2019 05:14:57 Europe/Berlin
====

=== Data format creator

The creator is a specific process that provides a raw data format. Each creator only saves data after you have activated the creator in the *Setup » plentyBI » Raw data* menu.

The individual data formats are named in English. For explanations and links to individual format pages, refer to <<table-reports-data-formats>>.


[IMPORTANT]
.Limited storage periods for raw data and calculation results
====
Within your plentymarkets system, raw data serve as the data basis for the key figures available in the <<business-decisions/plenty-bi#, plentyBI>> module. Depending on the plentyBI edition that was booked, raw data is stored for different periods of time.
The following storage periods apply per plentyBI edition: +

* plentyBI XS: 6 months
* plentyBI S: 12 months
* plentyBIM:14 months
* plentyBI L: 48 months

The calculation results yielded by the stored raw data are available for different periods of time, according to your plentyBI edition: +

* plentyBI XS: 12 months
* plentyBI S: 24 months
* plentyBI M: 36 months
* plentyBI L: 120 months

More detailed information on each raw data format is available by clicking on the links in <<table-reports-data-formats>>.
====


[[table-reports-data-formats]]
.Available raw data formats
[cols="1,3"]
|====
|Data format |Explanation

|accountContacts
|Contact person +
For further information, refer to the <<business-decisions/plenty-bi/reports/data-formats/accountcontacts#, accountContacts>> page of the manual.

|accounts
|Company +
For further information, refer to the <<business-decisions/plenty-bi/reports/data-formats/accounts#, accounts>> page of the manual.

|categories
|Categories +
For further information, refer to the <<business-decisions/plenty-bi/reports/data-formats/categories#, categories>> page of the manual.

|feedbacks
|Feedbacks +
For further information, refer to the <<business-decisions/plenty-bi/reports/data-formats/feedbacks#, feedbacks>> page of the manual.

|itemManufacturer
|Manufacturer +
For further information, refer to the <<business-decisions/plenty-bi/reports/data-formats/itemmanufacturers#, itemManufacturer>> page of the manual.

|itemVariations
|Variation +
For further information, refer to the <<business-decisions/plenty-bi/reports/data-formats/itemvariations#, itemVariations>> page of the manual.

|itemVariationSuppliers
|Links between suppliers and variations +
For further information, refer to the <<business-decisions/plenty-bi/reports/data-formats/itemvariationsuppliers#, itemVariationSuppliers>> page of the manual.

|marketplaceStockMovement
|Stock information that was exported to specific markets +
For further information, refer to the <<business-decisions/plenty-bi/reports/data-formats/marketplaceStockMovement#, marketplaceStockMovement>> page of the manual.

|messages
|Messages +
For further information, refer to the <<business-decisions/plenty-bi/reports/data-formats/messages#, messages>> page of the manual.

|messageTagRelations
|Tag relations of messages +
For further information, refer to the <<business-decisions/plenty-bi/reports/data-formats/messageTagRelations#, messageTagRelations>> page of the manual.

|orderDocuments
|Order documents +
For further information, refer to the <<business-decisions/plenty-bi/reports/data-formats/orderdocuments#, orderDocuments>> page of the manual.

|orderItemAmounts
|Value of order items +
For further information, refer to the <<business-decisions/plenty-bi/reports/data-formats/orderitemamounts#, orderItemAmounts>> page of the manual.

|orderItemProperties
|Property of the order item +
For further information, refer to the <<business-decisions/plenty-bi/reports/data-formats/orderitemproperties#, orderItemProperties>> page of the manual.

|orderItems
|Order item +
For further information, refer to the <<business-decisions/plenty-bi/reports/data-formats/orderitems#, orderItems>> page of the manual.

|orderProperties
|Order property +
For further information, refer to the <<business-decisions/plenty-bi/reports/data-formats/orderproperties#, orderProperties>> page of the manual.

|orders
|Order +
For further information, refer to the <<business-decisions/plenty-bi/reports/data-formats/orders#, orders>> page of the manual.

|orderStatuses
|Order status +
For further information, refer to the <<business-decisions/plenty-bi/reports/data-formats/orderstatuses#, orderStatuses>> page of the manual.

|paymentOrderRelations
|Relations between payments and orders +
For further information, refer to the <<business-decisions/plenty-bi/reports/data-formats/paymentorderrelations#, paymentOrderRelations>> page of the manual.

|payments
|Payments +
For further information, refer to the <<business-decisions/plenty-bi/reports/data-formats/payments#, payments>> page of the manual.

|properties
|Properties +
For further information, refer to the <<business-decisions/plenty-bi/reports/data-formats/properties#, properties>> page of the manual.

|propertyRelations
|Links between properties and other data +
For further information, refer to the <<business-decisions/plenty-bi/reports/data-formats/propertyrelations#, propertyRelations>> page of the manual.

|stockManagementStock
|Stock +
For further information, refer to the <<business-decisions/plenty-bi/reports/data-formats/stockmanagementstock#, stockManagementStock>> page of the manual.

|stockManagementStockMovements
|Stock movements +
For further information, refer to the <<business-decisions/plenty-bi/reports/data-formats/stockmanagementstockmovements#, stockManagementStockMovements>> page of the manual.

|stockManagementWarehouses
|Storage +
For further information, refer to the <<business-decisions/plenty-bi/reports/data-formats/stockmanagementwarehouses#, stockManagementWarehouses>> page of the manual.

|tags
|Tags +
For further information, refer to the <<business-decisions/plenty-bi/reports/data-formats/tags#, tags>> page of the manual.

|tagRelations
|Tag links +
For further information, refer to the <<business-decisions/plenty-bi/reports/data-formats/tagrelations#, tagRelations>> page of the manual.

|users
|User +
For further information, refer to the <<business-decisions/plenty-bi/reports/data-formats/users#, users>> page of the manual.

|variationValidation
|Variations that have been exported to markets but have been rejected +
For further information, refer to the <<business-decisions/plenty-bi/reports/data-formats/marketplacevariationvalidation#, variationValidation#, variationValidation>> page of the manual.

|====

More data formats will be added to this table as they become available.
