= Own cloud infrastructure
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Cloud, Own Cloud, Infrastructure, Cloud infrastructure, Version, Versions, Versioning, Versioning process, Manual versioning process, Beta, Early, Stable, Hosting
:position: 67
:url: business-decisions/system-administration/own-cloud-infrastructure
:id: 8NSQ6X6
:author: team-cloud

////
zuletzt aktualisiert am 07.01.21
////

When ordering plentymarkets, sellers can choose between different hosting options:

* Cloud hosting with servers located in Frankfurt or Ireland.
* Hosting with your own cloud infrastructure.

This page of the manual describes the second option: your own cloud infrastructure.
This option is available to sellers with an link:https://www.plentymarkets.com/product/editions/enterprise/[ENTERPRISE edition^].
In this scenario, sellers have their own cloud with their own DB server and webserver.

[#100]
== Versioning: practical example

You can operate any number of plentymarkets systems within your own cloud infrastructure.
For example, imagine you have a test system and a productive system:

* You use the test system to try out new software functions.
As soon as a new function is released, the change should appear in your test system so that you can try it out.
* You use the productive system for your day-to-day business.
New functions shouldn’t appear in your productive system immediately because they might distract from your daily business.
You don’t want new functions to appear in your productive system until you’ve tried them out in the test system and decided they meet your needs.

You decide when new functions should appear in each of your systems.
Should new updates appear automatically?
Or should the updates be added manually?
You are completely flexible with the configuration.

[#200]
== Setup

. Go to *Setup » Settings » Hosting » Manual Versioning Process*. +
→ You will see a list of all the systems within your own cloud infrastructure.
. In the line *Plenty ID: [Own ID and URL]*, click on the down arrow on the right (icon:chevron-down[role="darkGrey"]). +
→ You will see the versioning settings for this system.
. Check the settings and change them as needed. Note <<table-manual-versioning-process>>.

[TIP]
.Why don’t I see the menu?
====
This menu is only available for sellers who have their own cloud infrastructure.
If you do not have your own cloud infrastructure, then you will not see this menu in your system.
====

[[table-manual-versioning-process]]
.Versioning process
[cols="1,3"]
|====
|Setting |Explanation

| *plentymarkets version*
|In the upper left corner, you’ll find information about this system.
You’ll see the name of the development state (beta, early, stable). You’ll also see the date and time of whichever version is currently being used.

| *Automatically update to new version*
a|Should updates be added to this system automatically or manually?
Click on the toggle button in the lower left corner to turn automatic updates on and off.

[cols="1,5a"]
!======

!icon:toggle-on[role="green"]
!Updates will be added to the system automatically.
You do not need to configure any additional settings for this system.

*_Practical example_*: choose this setting, e.g. for the test system that you use to try out new software functions.

!icon:toggle-off[role="red"]
!Updates will be added to the system manually.
Before you start the update process, use the additional settings to specify _which updates_ should be added.

*_Practical example_*: choose this setting, e.g. for the productive system that you use for your day-to-day business.

!======

| *Update to version of another system*
a|This area is only displayed if you selected manual updates (icon:toggle-off[role="red"]).

. Take a look at _the middle area_.
. Select one of your systems from the drop-down list.
. Click on *Start update process*. +
→ The exact version of the selected system will be applied.

| *Update to newest version*
a|This area is only displayed if you selected manual updates (icon:toggle-off[role="red"]).

. Take a look at _the area on the right_.
. Click on *Start update process*. +
→ The newest version will be applied.
|====

[#300]
== Frequently Asked Questions (FAQ)

[.collapseBox]
.*What are the advantages and disadvantages of automatic updates?*
--

* *_Time factor_*:
Automatic updates save time.
Manual updates take more time because you will need to implement them yourself on a regular basis.

* *_Change factor_*:
Are you worried that automatic updates might negatively affect your system?
You might be worried that new functions could distract from your day-to-day business.
In this case, choose manual updates and decide for yourself when the system should change.

--

[.collapseBox]
.*I’m not happy with an update. What can I do?*
--

Report the problem in the link:https://forum.plentymarkets.com/[forum].
We’ll be happy to help.
Don’t update your system just yet.
Rather, wait until the problem has been fixed or until you’ve received additional instructions from our support team.

--

[.collapseBox]
.*Can I switch back down to an older version?*
--

No.
You can only update to a newer version.
It is not possible to switch back to an older version.

Therefore, we recommend trying out new functions in your test system first.
Update your productive system after you’ve tried out the new functions and decided they meet your needs.

--


[.collapseBox]
.*Can I postpone an update indefinitely?*
--

No.
Updates can not be postponed forever.
If you're using a version that's over _3 weeks_ old, then you'll start receiving daily messages, reminding you to update.

--

[.collapseBox]
.*My system includes multiple clients. Can I choose different versioning settings for each client?*
--

No.
When you open the menu *Setup » Settings » Hosting » Manual Versioning Process*, you’ll see a list of all the systems within your own cloud infrastructure.
Individual clients are not listed here.

It is not possible to choose an individual version for a client.
Rather, the client always uses the same version as the main shop.

--
