= plentyBI
:lang: en
include::{includedir}/_header.adoc[]
:keywords: BI, Business intelligence, plentyBI overview, plentyBI functions
:description: Learn more about the tools in plentymarkets that help you make clever business decisions.
:position: 30
:url: business-decisions/plenty-bi
:nav-alias: Overview
:id: CC4EFZF
:author: team-bi

[#100]
== What is plentyBI?

plentyBI is a business intelligence tool that is directly integrated in your plentymarkets system. You can use plentyBI to keep track of important key figures and data of your business at any time. The high number of available settings allows you to provide transparency and make clever business decisions whenever you want. 

[#200]
== How do you set it up?

Setting up plentyBI requires two essential steps. First, you create a data basis by setting up key figures. Then, you display and analyse this data on your individual dashboard.

** <<business-decisions/plenty-bi/myview-dashboard#200, Creating key figures>>
** <<business-decisions/plenty-bi/myview-dashboard#400, Setting up the dashboard>>

[#300]
== Which functions are available?

plentyBI offers you a big variety of features. For each key figure, you can make flexible decisions on how detailed the calculation is and what criteria are applied. Likewise, you have numerous options when setting up your dashboard. This allows you to display data according to your wishes and easily trace all important developments.

** <<business-decisions/plenty-bi/key-figures#, List of available key figures>>
** <<business-decisions/plenty-bi/myview-dashboard#408, Assigning user rights for the dashboard>>
** <<business-decisions/plenty-bi/myview-dashboard#405, Functions in the dashboard editing mode>>
** <<business-entscheidungen/plenty-bi/myview-dashboard#410, Using different diagram types, tiles and tables on the dashboard>>
** <<business-decisions/plenty-bi/myview-dashboard#900, Displaying notifications on the dashboard>>


[#400]
== Stay up to date

Are you looking forward to an upcoming feature for plentyBI? We’re happy to keep you in the loop about changes to the software! You can see a record of changes link:https://forum.plentymarkets.com/c/changelog[in our changelog^]. Subscribe to the changelog and always stay up to date.

