= Prohandel connector
:keywords: Prohandel, Prohandel connector, Prohandel-Connector, Prohandel add-on
:description: Learn how to connect your Prohandel system with plentymarkets.
:page-index: false
:id: NCUBFL8
:author: team-plenty-channel

////
zuletzt bearbeitet 07.04.2022

Interner Hinweis zur Seite:
Diese Seite richtet sich in erster Linie am plenty-Einrichtungs-Team.
Es ist sehr unwahrscheinlich, dass ein bestehender plenty-Kunde sich spontan entscheidet Prohandel zu nutzen und versucht das Plugin selbst einzurichten.
Viel eher ist der Anwendungsfall, dass ein Händler bereits Prohandel nutzt (z.B. für sein Mode-Einzelhandel).
Der Händler möchte seine Ware zukünftig auch online verkaufen und entscheidet sich für plenty (u.a. weil wir diese Schnittstelle haben).
Der Händler wäre also ganz neu bei plenty und würde sein System samt Prohandel-Plugin zusammen mit dem Einrichtungs-Team einrichten.
////

//ToDo when the page can be made visible in the left navigation - remove the attribute :page-index: false from the header and add the page to the navigation file in the ROOT folder

////
offene Fragen:
-bei "Optionen für den Artikelimport > Gruppierungsschema > Beispiel supplierNumber-categoryNumber-supplierArticleNumber": Hier wäre es schön, wenn es eine Liste mit den möglichen Datenfeldern gäbe, die man eingeben kann. Zudem wäre eine Info zur Syntax nicht schlecht. Team Prohandel müsste uns diese Infos liefern.
-bei "Neu importierte Artikeldaten öffnen": Klären, ob das so bleiben wird (also, dass die Versandprofile nicht automatisch aktiviert werden, weil die API per REST arbeitet). Falls ja, dann ein Hinweis hier in diesem Kapitel einbauen, dass der Händler seine Versandprofile prüfen und aktivieren soll.
https://forum.plentymarkets.com/t/api-prohandel-versandprofil-e-bei-neuen-artikeln-aktivieren/652140/7
////

Prohandel and plentymarkets – a winning combination.
Do you already use Prohandel as an inventory management tool for retail fashion?
And are you ready to get started in e-commerce with plentymarkets?
The Prohandel plugin connects your Prohandel system with plentymarkets.

* Continue using Prohandel for your offline sales.
* Transmit your item data from Prohandel to plentymarkets.
* Modify the item data in plentymarkets as needed and then sell your items on various marketplaces, sales channels and online shops.

[#10]
== Requirements

This page assumes that you’re already a customer of link:https://www.prohandel.de/[Prohandel] and link:https://www.plentymarkets.com/[plentymarkets].
Have your access data for both systems at hand.
While setting up the interface, you will need to enter your access data to make the connection.

Furthermore, you will map your Prohandel barcodes, sales prices, categories, etc. to those in plentymarkets.
If you have not set up your plentymarkets system yet, then you should create the following data before you continue:

* xref:stock-management:setting-up-a-warehouse.adoc#[Warehouses]
* xref:orders:order-referrer.adoc#[Order referrers]
* xref:item:flags.adoc#400[Tags]
* xref:item:barcodes.adoc#[Barcodes]
* xref:item:attributes.adoc#[Attributes]
* xref:item:properties.adoc#[Properties]
* xref:item:prices.adoc#[Sales prices]
* xref:item:categories.adoc#[Categories]

[#20]
== Downloading and installing the plugin

The Prohandel plugin is available on plentyMarketplace.
It connects your Prohandel system with plentymarkets.

The Prohandel plugin can:

* *_Import items_*:
Item data is transmitted from Prohandel to plentymarkets.
You decide which item data should be sent to plentymarkets and how the items should be structured there.
* *_Export orders_*:
Order data is transmitted from plentymarkets to Prohandel.
plentymarkets notifies Prohandel of the sale and automatically books the revenue into the correct Prohandel sales store.
* *_Update stock levels and prices_*:
Whenever stock levels or prices are updated in Prohandel, this information is transmitted to plentymarkets.

[.collapseBox]
.*Step-by-step instructions*
--

. Download the Prohandel plugin from plentyMarketplace. +
→ If prompted, sign into plentyMarketplace.
Use the same access data as for the “My account” area.
. Go to *Plugins » Plugin set overview*.
Plugins can only be used as part of a plugin set. Therefore:
.. *_Option A_*: Create a completely new plugin set.
To do so, click on icon:plus[role="darkGrey"] *Add plugin set* and enter a name.
.. *_Option B_*: Create a copy of an existing plugin set.
To do so, click on *Copy plugin set* (terra:copy[]) in the *Actions* column.
.. *_Option C_*: Decide which existing plugin set is suitable for the Prohandel plugin.
. Open the plugin set by clicking on the line in the table. +
→ The plugin set opens.
. Click on icon:plus[role="darkGrey"] *Add plugin*.
. Select the Prohandel plugin from the list. +
→ Information about the plugin is displayed.
. Select the version you want to install from the *Select version* drop-down list.
The newest version is selected by default.
. To install the plugin, click on icon:arrow-down[role="darkGrey"] *Install*. +
→ The plugin is installed. +
→ After installation has finished, the plugin set opens.
. Switch the plugin to active (icon:toggle-on[role="blue"]).
. Deploy the plugin set (icon:cloud-upload[role="darkGrey"]).

Are you new to plugins?
The xref:plugins:plugins.adoc#[plugins chapter] of the manual teaches you more about plugins and how they work in plentymarkets.

--

[TIP]
.Configuration takes place in the assistant
====
You do not need to configure any settings directly in the plugin.
Instead, open the assistant.
It guides you through the setup process.
====

[#30]
== Completing the assistant

The assistant helps you specify how plentymarkets and Prohandel should communicate with each other.
For example, you’ll decide which item data should be sent to plentymarkets and how the items should be structured there.

[.instruction]
Configuring the settings in the assistant:

. Go to *Setup » Assistants » Plugins » [Open plugin set]*.
. Click on *Prohandel Assistant*.
. Follow the instructions on the screen.
Information about the individual steps can be found further below on this page.
. In the step *Summary*, check your settings to makes sure they are correct.
. Once all of the settings are correct, click on icon:check[role="green"] *Finalise*. +
→ The settings are saved.

[#40]
=== Connection

In this step, you’ll connect plentymarkets and Prohandel.
In other words, you’ll enter your access data so that plentymarkets and Prohandel can communicate with each other.

[[table-connection-settings]]
.Connection
[cols="1,3"]
|====
|Setting |Explanation

| *URL*
|Enter the URL that you received from Prohandel.
Example: `your-shop.prohandel.de`

| *User name*
|Enter the user name for your Prohandel account.
The user name is an email address.

| *Password*
|Enter the password for your Prohandel account.
|====

[#43]
=== Consider locations in the warehouse

In this step, decide whether plentymarkets should track the exact location of each item in the warehouse.

*_Background knowledge_*:

* plentymarkets not only allows you to track an item’s stock levels, but also to track where the item is located within the warehouse.
** In plentymarkets, the item’s location is called the “storage location”.
** In Prohandel, the item’s location is called the “shop”.

[[table-storage-location-function]]
.Consider locations in the warehouse
[cols="1,3a"]
|====
|Setting |Explanation

| *Consider locations*
|Should plentymarkets track the exact location of each item in the warehouse?

icon:toggle-on[role="blue"] = The item’s exact storage location will be recorded.
When stock levels change, i.e. when items are received or shipped out, the specific storage location will be taken into consideration.
If you’ve activated this function, then you’ll also need to configure the settings in the step *Mapping of locations*.

icon:toggle-off[role="darkGrey"] = The item’s storage location will not be recorded.
In plentymarkets, the “default” storage location will always be used.

|====

[#46]
=== Mapping of locations

In this step, you match your Prohandel shops with your plentymarkets storage locations.
The storage locations in plentymarkets are generated automatically.

*_Example_*:

* During the item import, plentymarkets learns that an item is stored in Prohandel shop 1234.
* The plugin then automatically creates a matching plentymarkets storage location in the menu *Setup » Stock » Warehouse » [Open warehouse] » Storage locations* and links it in this step of the assistant.

[[table-storage-location-mapping]]
.Mapping of locations
[cols="1,3a"]
|====
|Setting |Explanation

| *Prohandel store*
|These are the stock-keeping stores in Prohandel.
Select the appropriate store from the drop-down list.

| *Prohandel shop*
|These are the shop names in Prohandel.
Select the appropriate shop from the drop-down list.

| *plentymarkets storage location*
|These are the storage location IDs in the plentymarkets menu *Setup » Stock » Warehouse » [Open warehouse] » Storage locations*.

|====

[TIP]
.Naming logic
====
You can find the automatically generated storage locations in the menu *Setup » Stock » Warehouse » [Open warehouse] » Storage locations*.
The storage location’s name always follows a certain logic.
The storage locations are called: `Prohandel level:Prohandel SL for shop 1234`.
In this example, `1234` represents the Prohandel shop number.
This name can not be changed.
It is hard-coded.
====

[#50]
=== Mapping of stock-keeping stores

In this step, you’ll map your stock-keeping Prohandel stores with your plentymarkets warehouses.
In doing so, your stock levels in Prohandel can be synchronised with plentymarkets and kept up-to-date.
For example, if the stock level sinks in Prohandel, then plentymarkets will also be informed of the change.

[[table-stock-branch-matching]]
.Mapping of stock-keeping stores
[cols="1,3"]
|====
|Setting |Explanation

| *Prohandel store*
|These are the stock-keeping stores in Prohandel.
Select the appropriate store from the drop-down list.

| *plentymarkets warehouse*
|These are the warehouses that you’ve set up in plentymarkets.
Select the appropriate warehouse from the drop-down list.

*_Requirement_*:
Have you already xref:stock-management:setting-up-a-warehouse.adoc#[created warehouses in plentymarkets]?
This drop-down list only includes warehouses that already exist in plentymarkets.

| icon:plus[role="green"]
|Adds another line.
This allows you to map multiple stores and warehouses.

| icon:minus-circle[role="red"]
|Deletes a line.
This allows you to remove mappings that are no longer needed.
|====

[TIP]
.1:1 mapping is recommended
====
* Ideally, you should create a 1:1 mapping.
* It doesn’t make sense to link multiple plentymarkets warehouses with the same Prohandel store.
In this case, your data would repeatedly be transmitted from Prohandel to plentymarkets.
The data would not be split.
====

[#60]
=== Mapping of sales stores

In this step, you’ll map your plentymarkets sales channels with the appropriate Prohandel sales stores.
Imagine you’ve just sold a product on a market like eBay, Amazon or Check24.
Which sales store should the revenue be booked into and the order data transmitted to?

[[table-sales-branch-matching]]
.Mapping of sales stores
[cols="1,3"]
|====
|Setting |Explanation

| *Prohandel store*
|These are the sales stores in Prohandel.
Select the appropriate store from the drop-down list.

| *Client (store)*
|These are the clients that you operate with plentymarkets.
Select the appropriate client from the drop-down list.

When an order is transmitted to Prohandel, it includes information about the client that it relates to.

| *Order referrers*
|These are the order referrers that you use in plentymarkets.
Select the appropriate referrers (icon:check-square[role="blue"]).

When an order is transmitted to Prohandel, it includes information about the sales channel that it relates to.
This allows you to keep a statistical record in Prohandel of which sales channels are particularly profitable or which ones cause the most returns.

*_Requirement_*:
Have you already xref:orders:order-referrer.adoc#[activated the appropriate referrers in plentymarkets]?
The drop-down list only includes active referrers.

| icon:plus[role="green"]
|Adds another line.
This allows you to map multiple stores and sales channels.

| icon:minus-circle[role="red"]
|Deletes a line.
This allows you to remove mappings that are no longer needed.
|====

[#70]
=== Options for the item import

In this step, you’ll decide which item data should be transmitted from Prohandel to plentymarkets and how the items should be structured there.

[[table-item-import-options]]
.Options for the item import
[cols="1,3a"]
|====
|Setting |Explanation

2+^| *Item filter*

| *Filter basis*; +
*From date*
|Which items should be imported into plentymarkets?

. Select a basis from the drop-down list.
. Enter a date into the field.

[cols="1,3a"]
!===

! *Incoming goods - First date*
!This is a timestamp for items in Prohandel.
The timestamp is generated when the item is initially created in Prohandel.
This timestamp never changes.

*_Note_*:
Don’t confuse this timestamp with the second date for incoming goods. It’s updated every time new goods are received for the item.

! *Sale - Second date*
!This is a timestamp for items in Prohandel.
The timestamp indicates when the item was last sold.
This timestamp is updated in Prohandel every time the item is sold.

!===

*_Example_*:
Imagine you use the first incoming goods date as the filter basis and you enter the date 01.01.2020.
In this case, only those items that were first procured on or after January 1st, 2020 will be imported.

2+^| *Grouping scheme*

| *Grouping scheme*
|Items are structured differently in Prohandel and in plentymarkets.

* *_Prohandel_*: In Prohandel, an item can be thought of as a colour variation.
For example, an item is a t-shirt in the colour blue.
A second item is the t-shirt in the colour red.
Both items have size variations.
For example, Blue S, Blue M, Blue L and Red S, Red M, Red L.
* *_plentymarkets_*: In plentymarkets, an item can be thought of as a data container.
An item always includes one or more variations, i.e. one or more saleable versions of the product.
For example, if a t-shirt is available in the colours blue and red and the sizes S, M, L, then all of the colours and sizes together make up the item.
Each individual combination (Blue S, Blue M, Blue L, Red S, Red M, Red L) is a variation of this item.

In this step, you’ll specify a grouping scheme so that your Prohandel items will be structured correctly when they are imported into plentymarkets.
This is a text field, i.e. you can enter any grouping scheme.

*_Example_*:
If you enter the grouping scheme `supplierNumber-categoryNumber-supplierArticleNumber`, then all of the Prohandel items that have the same supplier number, category number and supplier item number, will be grouped together into one plentymarkets item.

2+^| *Tag for imported items*

| *plentymarkets tag*
|Do you want to assign a specific tag to all of your newly imported items?
If so, then select the appropriate tag from the drop-down list.
By assigning a tag to your items, you can easily tell which items were recently imported, open their data records and refine the item data saved in plentymarkets.

*_Requirement_*:
Have you already xref:item:flags.adoc#400[created the necessary tags in plentymarkets]?
This drop-down list only includes tags that have already been created and made available for variations.

2+^| *Behaviour of items with a specific value*

| *Field name*; +
*Field value*; +
*Import behaviour*
|Do you only want to import specific items?
Or do you want to exclude specific items from the import?

. Which items are we talking about?
Select the field name and field value.
. Decide what should happen to these items.
Select the import behaviour.

[cols="1,3a"]
!===

! *Only import those items with specified value*
!Only those items with the specified field value and field name will be imported.
All other items will be ignored.

! *Skip items with specified value*
!The items with the specified field value and field name will be skipped.
In other words, they will not be imported.

!===

*_Example_*:
Imagine you sell clothing that is available in various patterns.
In Prohandel, each pattern is identified by a unique ID.
You only want the products with pattern number 5 to be imported into plentymarkets.
To do so, you’ll choose the field name *patternNumber*, the field value *5* and the import behaviour *Only import those items with specified value*.

|====

[#80]
=== Mapping of item data fields

In this step, you’ll decide what the data that comes from Prohandel should look like in plentymarkets.
In other words, where the data should be saved in plentymarkets.

[[table-item-import-field-mappings]]
.Mapping of item data fields
[cols="1,3a"]
|====
|Setting |Explanation

2+^| *Barcode mapping*

| *EAN*
|Which plentymarkets barcode type matches your Prohandel EAN?
Select the barcode type from the drop-down list.

*_Requirement_*: Have you already xref:item:barcodes.adoc#100[configured barcode types in plentymarkets]?
This drop-down list only includes the barcode types that already exist in plentymarkets.

| *Number*
|Which plentymarkets barcode type matches your internal number for identifying the size in Prohandel?
Select the barcode type from the drop-down list.

*_Requirement_*: Have you already xref:item:barcodes.adoc#100[configured barcode types in plentymarkets]?
This drop-down list only includes the barcode types that already exist in plentymarkets.

| *Article number*
|Which plentymarkets barcode type matches your Prohandel article number?
Select the barcode type from the drop-down list.

*_Requirement_*: Have you already xref:item:barcodes.adoc#100[configured barcode types in plentymarkets]?
This drop-down list only includes the barcode types that already exist in plentymarkets.

2+^| *Attributes mapping*

| *Supplier colour*
|Which plentymarkets attribute matches your Prohandel supplier colour?
Select the attribute from the drop-down list.

*_Requirement_*: Have you already xref:item:attributes.adoc#[configured attributes in plentymarkets]?
This drop-down list only includes the attributes that already exist in plentymarkets.

| *Size*
|Which plentymarkets attribute matches your Prohandel size?
Select the attribute from the drop-down list.

*_Requirement_*: Have you already xref:item:attributes.adoc#[configured attributes in plentymarkets]?
This drop-down list only includes the attributes that already exist in plentymarkets.

2+^| *Properties mapping*

| *Individual item number*
|Which plentymarkets data field matches your individual item number in Prohandel?
Select the appropriate option from the drop-down list.

[cols="1,3a"]
!===

! *None*
!The individual item number will not be transferred.

! *Name 1*
!The individual item number will be saved under: xref:item:managing-items.adoc#50[Item » Edit item » [Open item\] » Tab: Texts » Entry field: Name 1]
//ToDo - sobald die neue Artikel-UI standard ist, dann diesen Satz einblenden und dafür den alten Satz löschen
//The individual item number will be saved under: xref:item:directory.adoc#50[Item » Item UI » [Open item\] » Element: Texts » Entry field: Name 1]

! *Variation property*
!A second drop-down list opens.
It includes a list of properties that exist in plentymarkets.
Select a property from this list if you want the Prohandel individual item number to be saved as this property in plentymarkets.

*_Requirement_*: Have you already xref:item:properties.adoc#[configured properties in plentymarkets]?
This drop-down list only includes the properties that already exist in plentymarkets.
!===

| *Supplier item number*
|Which plentymarkets data field matches your supplier item number in Prohandel?
Select the appropriate option from the drop-down list.

[cols="1,3a"]
!===

! *None*
!The supplier item number will not be transferred.

! *External variation ID*
!The supplier item number will be saved under: xref:item:managing-items.adoc#190[Item » Edit item » [Open variation\] » Tab: Settings » Area: Basic settings » Entry field: External Variation ID]
//ToDo - sobald die neue Artikel-UI standard ist, dann diesen Satz einblenden und dafür den alten Satz löschen
//The supplier item number will be saved under: xref:item:directory.adoc#170[Item » Item UI » [Open variation\] » Element: Settings » Entry field: External ID]

! *Variation property*
!A second drop-down list opens.
It includes a list of properties that exist in plentymarkets.
Select a property from this list if you want the Prohandel supplier item number to be saved as this property in plentymarkets.

*_Requirement_*: Have you already xref:item:properties.adoc#[configured properties in plentymarkets]?
This drop-down list only includes the properties that already exist in plentymarkets.
!===

| *Season number*; +
*Incoming goods - First date*; +
*Incoming goods - Second date*; +
*NOS*; +
*Identification number*; +
*Sale - First date*; +
*Sale - Second date*
|Which plentymarkets property matches the Prohandel data field?
Select the appropriate option from the drop-down list.

[cols="1,3a"]
!===

! *None*
!The Prohandel data field will not be transferred.

! *Variation property*
!A second drop-down list opens.
It includes a list of properties that exist in plentymarkets.
Select a property from this list if you want the Prohandel data field to be saved as this property in plentymarkets.

*_Requirement_*: Have you already xref:item:properties.adoc#[configured properties in plentymarkets]?
This drop-down list only includes the properties that already exist in plentymarkets.
!===

2+^| *Features*

| *Import Prohandel suppliers as plentymarkets manufacturers*
|Should the Prohandel supplier be saved as a manufacturer in plentymarkets?
In plentymarkets, you can find an item’s manufacturer in the menu *Item » Edit item » [Open item] » Tab: Global » Drop-down list: Manufacturer*.
//ToDo - sobald die neue Artikel-UI standard ist, dann diesen Satz einblenden und dafür den alten Satz löschen
//In plentymarkets, you can find an item’s manufacturer in the menu *Item » Item UI » [Open item] » Element: Settings » Drop-down list: Manufacturer*.

| *Import Prohandel patterns as plentymarkets tags*
|Should the Prohandel pattern be saved as a tag in plentymarkets?
In plentymarkets, you can find an item’s tag in the menu *Item » Edit item » [Open variation] » Tab: Settings » Area: Tags*.
//ToDo - sobald die neue Artikel-UI standard ist, dann diesen Satz einblenden und dafür den alten Satz löschen
//In plentymarkets, you can find an item’s tag in the menu *Item » Item UI » [Open variation] » Element: Tags*.

|====

[#90]
=== Mapping of sales prices

* In the upper area, you map the sales prices used in Prohandel to the sales prices in plentymarkets.
* In the lower area, you map the special prices used in Prohandel to the sales prices in plentymarkets.

[[table-sales-prices]]
.Mapping of sales prices
[cols="1,3"]
|====
|Setting |Explanation

2+^| *Sales prices*

| *Sales price*
|Which plentymarkets sales price do you want to use for the sale price in Prohandel?
Select the appropriate plentymarkets sales price from the drop-down list.

*_Requirement_*: Have you already xref:item:prices.adoc#[configured sales prices in plentymarkets]?
This drop-down list only includes the sales prices that already exist in plentymarkets.

| *Sales price (label price)*
|Which plentymarkets sales price do you want to use for the label price in Prohandel?
Select the appropriate plentymarkets sales price from the drop-down list.

*_Requirement_*: Have you already xref:item:prices.adoc#[configured sales prices in plentymarkets]?
This drop-down list only includes the sales prices that already exist in plentymarkets.

2+^| *Prohandel special price*

| *ID of the Prohandel special price*
|What is the special price’s ID in Prohandel?
Enter the ID into this field.

| *Sales price (special price)*
|Which plentymarkets sales price do you want to map to your Prohandel special price?
Select the appropriate plentymarkets sales price from the drop-down list.

*_Requirement_*: Have you already xref:item:prices.adoc#[configured sales prices in plentymarkets]?
This drop-down list only includes the sales prices that already exist in plentymarkets.

| *From*; +
*To*
|When should this sales price be valid?
Select the “from” and “to” dates from the drop-down lists.

*_Requirement_*: Have you already xref:item:properties.adoc#[configured properties in plentymarkets]?
This drop-down list only includes the properties that already exist in plentymarkets.
We recommend creating properties of the type “Date” for the from and to dates.

|====

[TIP]
.No need to map the purchase price
====
The Prohandel purchase price is mapped statically to the plentymarkets net purchase price.
In other words, you do not need to link the Prohandel purchase price to the plentymarkets purchase price.
It is already mapped.
====

[#100]
=== Mapping of categories

In this step, you map the categories used in Prohandel to the categories in plentymarkets.
This way, your items are directly sorted into the correct plentymarkets categories when they are imported from Prohandel.

[[table-category-mapping]]
.Mapping of categories
[cols="1,3"]
|====
|Setting |Explanation

| *Default item category*
|Imagine you created a new category in Prohandel.
But you forgot to map it with a corresponding plentymarkets category.
If you import items from the non-mapped Prohandel category, they will land in the default plentymarkets category.

| *Prohandel category*
|These are your categories in Prohandel.
Select the appropriate category from the drop-down list.

| *plentymarkets category*
|These are the categories that you’ve set up in plentymarkets.
Select the appropriate category from the drop-down list.

*_Requirement_*: Have you already xref:item:categories.adoc#[created categories in plentymarkets]?
This drop-down list only includes the categories that already exist in plentymarkets.

| icon:plus[role="green"]
|Adds another line.
This allows you to map multiple categories.

| icon:minus-circle[role="red"]
|Deletes a line.
This allows you to remove mappings that are no longer needed.
|====

[TIP]
.Alternative procedure without assigning categories
====
Technically speaking, you could just select a default category and then skip the rest of the category assignment.
As a result, your items would always land in the default category when they are imported.
If needed, you would then manually have to move the items into different plentymarkets categories.
====

[#110]
=== Cron settings

Data is transmitted between Prohandel and plentymarkets with the help of so-called "Crons".
In this step, you’ll activate the cron jobs that should run automatically (icon:check-square[role="blue"]).

include::_includes:partial$crons.adoc[]

[[table-cron-settings]]
.When do the crons run?
[cols="1,1,3a"]
|====
|Cron |Interval |Explanation

| *Item import*
|Daily
|
* Once you have completed the assistant, all of your items will initially be transmitted from Prohandel to plentymarkets.
This initial, full import can take a few days to finish, depending on the number of products.
* Afterwards, only a sub-set of items will be imported, based on the previously selected xref:business-decisions:prohandel.adoc#70[import settings].
* Only new items are imported and new variations on existing items.
Existing items are not updated with this cron.
* The item import starts at the end of the day, or rather during the night.

| *Item update*
|Hourly
|Existing items and variations are updated.
This cron updates the following data:

* Linked variation properties
* Tags (assuming that the Prohandel pattern is imported as a tag)
* Manufacturers (assuming that the manufacturer is imported)
* EAN

| *Price update*
|Hourly
|

| *Stock update*
|Every 15 minutes
|
|====

[#120]
== Opening and modifying newly imported item data

The next time the cron job runs, your item data will be transmitted from Prohandel to plentymarkets.
This assumes that you’ve:

* activated the *Item import* cron (icon:check-square[role="blue"]).
* completed the assistant.
* activated the plugin within the set.

[#130]
=== Opening newly imported items

Open a few item data records and make sure that your item data was correctly imported.

. Go to *Item » Edit item*.
. Use the xref:item:search.adoc#[search filters] on the left to specify which items you want to access.
For example:
.. Set the *Active* filter to *ALL* or *No*, since items are inactive when they are imported.
.. Set the *Tag* filter to whichever xref:business-decisions:prohandel.adoc#70[tag for newly imported items] you chose in the assistant.
. Click on *Search* (icon:search[role="blue"]). +
→ The search results are displayed in an overview on the right.
. Click on an item in the overview to open the item data record.

//ToDo - sobald die neue Artikel-UI standard ist, dann diesen Konfig einblenden und dafür den alten Konfig löschen
//. Go to *Item » Item UI*.
//. Use the search filters (material:tune[role="darkGrey"]) to specify which items you want to access.
//For example:
//.. Set the *Active* filter to *No*, since items are inactive when they are imported.
//.. Set the *Tags* filter to whichever xref:business-decisions:prohandel.adoc#70[tag for newly imported items] you chose in the assistant.
//. Click on icon:search[role="blue"] *Search*. +
//→ The search results are displayed in an overview.
//. Click on an item in the overview to open the item data record.

[TIP]
.Main variation vs. Sub-variation
====
Check the data that was transmitted for the main variation and for the sub-variations.

* *_Main variation_*: An item’s first variation is called its main variation.
It is not for sale, but rather is purely virtual and helps you manage the sub-variations via xref:item:inheritance.adoc#[inheritance].
When you open an item data record, the main variation automatically opens too.
* *_Sub-variation_*: The sub-variations are the saleable versions of the product.
For example, if a t-shirt is sold in the colours blue and red and the sizes S, M, L, then every single combination (Blue S, Blue M, Blue L, Red S, Red M, Red L) is a sub-variation.
To open a sub-variation, click on the tab *Variations* and then on *Search* (icon:search[role="blue"]).
Finally, click on a sub-variation in the overview.
====

[#140]
=== Modifying item data

Once you’re happy with the item data that was transmitted, you can start preparing your items to be sold online.
For example, you can:

* add xref:item:managing-items.adoc#50[descriptive texts], xref:item:managing-items.adoc#90[product images] and relevant xref:item:managing-items.adoc#50[meta data].
* specify where your products should be sold, i.e. select xref:item:managing-items.adoc#340[order referrers] and xref:item:managing-items.adoc#340[clients].
* xref:item:managing-items.adoc#200[activate] your variations when you are ready for them to go live.

For a complete list of all the item data fields in plentymarkets, refer to the page xref:item:managing-items.adoc#[Directory of data fields].

[#150]
== Processing orders

When a product is sold, the order data lands in the plentymarkets menu *Orders » Edit orders*.
The order can be processed here and its progress can be tracked with the help of a status.

Further information about processing orders in plentymarkets can be found on the xref:orders:managing-orders.adoc#[Managing orders] page of the manual.

[#160]
== Setting up event procedures

Of course, the order data shouldn’t just stay in plentymarkets. Rather, it should also be transmitted to Prohandel.
You’ll set up four so-called event procedures to do this.
They only need to be set up once, in order for the export to work correctly.

[.instruction]
Setting up an event procedure:

. Go to *Setup » Orders » Events*.
. Click on *Add event procedure* (icon:plus[role="green"]). +
→ The *Create new event procedure* window opens.
. Enter a distinct name for the event procedure.
. Select the event as listed in the following tables.
. Click on terra:save[role="green"] *Save*. +
→ The event procedure is created and can be edited further.
. Click on *Add procedure* (icon:plus[role="green"]) and select the procedure as listed in the following tables.
. Optional: Click on *Add filter* (icon:plus[role="green"]) and select filters if you only want the event procedure to apply in certain situations.
For example, the event procedure could only apply to specific sales channels or clients.
. Activate the event procedure (icon:check-square[role="blue"]) once it should go into effect.
From the point of activation onwards, the event procedure applies your settings to the selected orders.
. Save (terra:save[role="green"]) the settings.

For further information, refer to the xref:automation:event-procedures.adoc#[Event procedures] page of the manual.

[#170]
=== Notifying Prohandel of new orders

When a new order lands in plentymarkets, Prohandel should be informed of the order.
This allows Prohandel to reserve the necessary stock and avoid overselling.

[[table-event-procedure-one]]
[cols="1,2"]
|====

|Event
|New order

|Filter (optional)
|Order > Referrer +
Order > Client (store)

|Procedure
|Plugins > Prohandel: Reserve stock
|====

[#180]
=== Notifying Prohandel of payment and shipment

Fully processed orders are in status 7.
This status means that payment has been received and items have been booked as outgoing.
At this point, Prohandel should also be informed of the changes to the order.

[[table-event-procedure-two]]
[cols="1,2"]
|====

|Event
|Outgoing items booked

|Filter (optional)
|Order > Referrer +
Order > Client (store)

|Procedure
|Plugins > Prohandel: Send shipping and payment notification to Prohandel
|====

[#190]
=== Notifying Prohandel of cancellations

A cancellation:

* means that the customer changed his or her mind and no longer wants the item that was purchased.
* happens before you receive payment and ship the items.
* can be understood as reversing the stock reservation.
plentymarkets notifies Prohandel that the stock reservation is null and void.

You can cancel an order by changing its status to 8.
At this point, Prohandel should be informed of the cancellation so that stock stops being reserved.

[[table-event-procedure-three]]
[cols="1,2"]
|====

|Event
|Status change to 8

|Filter (optional)
|Order > Referrer +
Order > Client (store)

|Procedure
|Plugins > Prohandel: Send order cancellation to Prohandel
|====

[#200]
=== Notifying Prohandel of returns

A return:

* means that the customer changed his or her mind and no longer wants the item that was purchased.
* happens after you receive payment and ship the items.

Since payment has already been received, you need to refund the customer.
In other words, you need to inform Prohandel of the return so that the revenue can be booked back out of the sales store.

[[table-event-procedure-four]]
[cols="1,2"]
|====

|Event
|New return

|Filter (optional)
|Order > Referrer +
Order > Client (store)

|Procedure
|Plugins > Prohandel: Send return notification to Prohandel
|====
