= SPoCC interface
:keywords: SPoCC, SPoCC interface, SPoCC connector, SPoCC extension, Apollon, Single Point of Content and Communication
:description: Learn how to connect your SPoCC system with plentymarkets.
:page-index: false
:author: team-plenty-channel

////
erstellt am 28.06.2022
Project Manager: Tina Gerber

Similar to Prohandel, SPoCC is a content database with stock management. Stock management is primarily used by shoe sellers. Item data (i.e. master data, properties, images, stock, prices) are imported to plentymarkets and order details is exported to SPoCC (previously called Apollon).
////

//ToDo when the page can be made visible in the left navigation - remove the attribute :page-index: false from the header and add the page to the navigation file in the ROOT folder

SPoCC and plentymarkets – a great combination.
Do you already use SPoCC as an inventory management tool for shoe retail?
And are you ready to get started in e-commerce with plentymarkets?
The SPoCC plugin connects your SPoCC system to plentymarkets.

* Continue using SPoCC for your sales.
* Import the item data imported in the SPoCC database to plentymarkets.
* Modify the item data in plentymarkets as needed and then sell your items on various marketplaces, sales channels and online shops.
* Export order data to SPoCC.

[#data-exchange]
== Data exchange

After you have set up the interface to SPoCC, the automatic processes described in <<#data-exchange>> are available.

[[data-exchange]]
.Data exchange
[cols="3a,3a"]
|===
|Data |Interval

| Import of new items to plentymarkets +
Master data: EAN, name, itemnumbers, colour, size, etc.
| Once every 24 hours

| Import of additional item data to plentymarkets: +
SPoCC attributes in properties
| Every 60 minutes

| Import of images to plentymarkets
| Every 60 minutes

| Import of prices to plentymarkets
| * Complete import every 24 hours
* Changed data every 15 minutes

| Import of stock details to plentymarkets
| * Complete import every 24 hours
* Changed data every 15 minutes

| Export of orders to SPoCC: +
* Create order, notifications, reserve stock
* Update order when ready four shipping
| When event procedure is triggered

| Request order status:
* Cancellation
| Every 20 minutes

| Provide shipping documents
|

| Export package type
|
|===

[#10]
== Requirements

This page assumes that you are already a customer of link:https://www.SPoCC.io/[SPoCC] and link:https://www.plentymarkets.com/[plentymarkets].
Have your access data for both systems at hand.
While setting up the interface, you will enter your access data to make the connection.

Furthermore, you will map your SPoCC barcodes, sales prices, categories, etc. to those in plentymarkets.
If you have not set up your plentymarkets system yet, then you should create the following data before you continue:

* xref:stock-management:setting-up-a-warehouse.adoc#[Warehouses]
* xref:orders:order-referrer.adoc#[Order referrers]
* xref:item:flags.adoc#400[Tags]
* xref:item:barcodes.adoc#[Barcodes]
* xref:item:attributes.adoc#[Attributes]
* xref:item:properties.adoc#[Properties]
* xref:item:prices.adoc#[Sales prices]
* xref:item:categories.adoc#[Categories]

[#20]
== Downloading and installing the plugin

The SPoCC plugin is available on plentyMarketplace.
The plugin connects your SPoCC system to plentymarkets.

The SPoCC plugin offers the following functionality:

* *_Import items_*:
Item data is exported from SPoCC to plentymarkets.
You decide which item data is sent to plentymarkets and how the items are structured there.
* *_Export orders_*:
Order data is transmitted from plentymarkets to SPoCC.
plentymarkets notifies SPoCC of the sale and automatically books the revenue into the correct SPoCC sales store.
* *_Update stock levels and prices_*:
Whenever stock levels or prices are updated in SPoCC, this information is transmitted to plentymarkets.

[.collapseBox]
.*Step-by-step instructions*
--

. Download the SPoCC plugin from plentyMarketplace. +
→ If prompted, sign into plentyMarketplace.
Use the same access data as for the “My account” area.
. Go to *Plugins » Plugin set overview*.
Plugins can only be used as part of a plugin set. Therefore:
.. *_Option A_*: Create a completely new plugin set.
To do so, click on icon:plus[role="darkGrey"] *Add plugin set* and enter a name.
.. *_Option B_*: Create a copy of an existing plugin set.
To do so, click on *Copy plugin set* icon:copy[set=plenty] in the *Actions* column.
.. *_Option C_*: Decide which existing plugin set is suitable for the SPoCC plugin.
. Open the plugin set by clicking on the line in the table. +
→ The plugin set opens.
. Click on icon:plus[role="darkGrey"] *Add plugin*.
. Select the SPoCC plugin from the plugin list. +
→ Information about the plugin is displayed.
. Select the version you want to install from the *Select version* drop-down list.
The newest version is selected by default.
. To install the plugin, click on icon:arrow-down[role="darkGrey"] *Install*. +
→ The plugin is installed. +
→ After installation has finished, the plugin set opens.
. Switch the plugin to active (icon:toggle-on[role="blue"]).
. Deploy the plugin set (icon:cloud-upload[role="darkGrey"]).

Are you new to plugins?
The xref:plugins:plugins.adoc#[plugins chapter] of the manual teaches you more about plugins and how they work in plentymarkets.

--

[TIP]
.Interface is set up in the assistant
====
You do not need to configure any settings directly in the plugin.
Instead, open the assistant.
The assistant guides you through the setup process.
====

[#30]
== Completing the assistant

The assistant helps you specify how plentymarkets and SPoCC communicate with each other.
For example, you’ll decide which item data is sent to plentymarkets and how the items are structured there.

[.instruction]
Configuring the settings in the assistant:

. Go to *Setup » Assistants » Plugins » [Open plugin set]*.
. Click on *SPoCC assistant*.
. Follow the instructions on the screen.
Information about the individual steps can be found further below on this page.
. In the step *Summary*, check your settings to makes sure they are correct.
. Once all of the settings are correct, click on icon:check[role="green"] *Finalise*. +
→ The settings are saved.

[#40]
=== Step "Connection"

In this step, you’ll connect plentymarkets and SPoCC.
In other words, you’ll enter your access data so that plentymarkets and SPoCC can communicate with each other.

[[table-connection-settings]]
.Step "Connection"
[cols="1,3"]
|===
|Setting |Explanation

| *API key*
| Enter the API key that you received from SPoCC.

| *Retailer ID*
| Enter the seller ID that you received from SPoCC.

| *Customer number*
| Enter your SPoCC customer number.

| *Channel ID*
| Enter the Channel ID that you received from SPoCC.
|===

[#80]
=== Step "Options for the item import"

In this step, you’ll decide what the data that comes from SPoCC should look like in plentymarkets.
In other words, where the data should be saved in plentymarkets.

[[table-item-import-field-mappings]]
.Options for the item import
[cols="1,3a"]
|===
|Setting |Explanation

2+^| Default category

| *Default item category*
|Imagine you created a new category in SPoCC.
But you forgot to map it with a corresponding plentymarkets category.
If you import items from the non-mapped Prohandel category, they will land in the default plentymarkets category.

*_Requirement_*: Have you already xref:item:categories.adoc#[created categories in plentymarkets]?
This drop-down list only includes the categories that already exist in plentymarkets.

2+^| Barcode

| *Barcode*
|Which plentymarkets barcode type matches your SPoCC barcode?
Select the barcode type from the drop-down list.

*_Requirement_*: Have you already xref:item:barcodes.adoc#100[configured barcode types in plentymarkets]?
This drop-down list only includes the barcode types that already exist in plentymarkets.

2+^| Attributes

| *Colour attribute*
|Which plentymarkets attribute matches your SPoCC colour attribute?
Select the attribute from the drop-down list.

*_Requirement_*: Have you already xref:item:attributes.adoc#[configured attributes in plentymarkets]?
This drop-down list only includes the attributes that already exist in plentymarkets.

| *Size*
|Which plentymarkets attribute matches your SPoCC size?
Select the attribute from the drop-down list.

*_Requirement_*: Have you already xref:item:attributes.adoc#[configured attributes in plentymarkets]?
This drop-down list only includes the attributes that already exist in plentymarkets.
|===

[#sales-price-mapping]
=== Step "Map sales prices"

There are three prices in SPoCC:

* Sales price
* Target price
* Recommended retail price

[[table-sales-prices]]
.Mapping of sales prices
[cols="1,3"]
|===
|Setting |Explanation

| *Sales price*
|Which plentymarkets sales price do you want to use for the sale price in SPoCC?
Select the appropriate plentymarkets sales price from the drop-down list.

*_Requirement_*: Have you already xref:item:prices.adoc#[configured sales prices in plentymarkets]?
This drop-down list only includes the sales prices that already exist in plentymarkets.

| *Target price*
|Which plentymarkets sales price do you want to use for the target price in SPoCC?
Select the appropriate plentymarkets sales price from the drop-down list.

*_Requirement_*: Have you already xref:item:prices.adoc#[configured sales prices in plentymarkets]?
This drop-down list only includes the sales prices that already exist in plentymarkets.

| *Recommended retail price*
|Which plentymarkets sales price do you want to use for the recommended retail price in SPoCC?
Select the appropriate plentymarkets sales price from the drop-down list.

*_Requirement_*: Have you already xref:item:prices.adoc#[configured sales prices in plentymarkets]?
This drop-down list only includes the sales prices that already exist in plentymarkets.
|===

[#43]
=== Step "Map properties"

In plentymarkets, you use properties to handle SPoCC attributes.
As such, you map plentymarkets properties to your SPoCC attributes in this step.



. From the drop-down list *plentymarkets property* on the left side, select a property. +
*_Requirement_*: Have you already xref:item:properties.adoc#[configured properties in plentymarkets]?
This drop-down list only includes the properties that already exist in plentymarkets.
. From the drop-down list *SPoCC attribute* on the right, select an attribute. +
→ The two records are mapped to each other.

[[table-property-mapping]]
.Properties mapping
[cols="1,3"]
|===
|Setting |Explanation

| *SPoCC attribute*
|These are your attributes in SPoCC.
Select the appropriate attribute from the drop-down list.

| *plentymarkets property*
|These are the categories that you’ve set up in plentymarkets.
Select the appropriate property from the drop-down list.

*_Requirement_*: Have you already xref:item:properties.adoc#[configured properties in plentymarkets]?
This drop-down list only includes the properties that already exist in plentymarkets.

| icon:plus[role="green"]
| Adds another line.
This allows you to map multiple properties.

| icon:minus-circle[role="red"]
|Deletes a line.
This allows you to remove mappings that are no longer needed.
|===



[#category-mapping]
=== Step: "Map categories"

In this step, you map the product groups used in SPoCC to the categories in plentymarkets.
This way, your items are directly sorted into the correct plentymarkets categories when they are imported from SPoCC.

*_Important:_* Any items in SPoCC categories that you did not map in this step are sorted into the category

[[table-category-mapping]]
.Mapping of categories
[cols="1,3"]
|===
|Setting |Explanation

| *SPoCC product group*
| These are your product groups in SPoCC.
Select the appropriate product group from the drop-down list.

| *plentymarkets category*
| These are the categories that you’ve set up in plentymarkets.
Select the appropriate category from the drop-down list.

*_Requirement_*: Have you already xref:item:categories.adoc#[created categories in plentymarkets]?
This drop-down list only includes the categories that already exist in plentymarkets.

| icon:plus[role="green"]
| Adds another line.
This allows you to map multiple categories.

| icon:minus-circle[role="red"]
| Deletes a line.
This allows you to remove mappings that are no longer needed.
|===

[TIP]
.Alternative procedure without assigning categories
====
Technically speaking, you could just select a default category and then skip the rest of the category assignment.
As a result, your items would always land in the default category when they are imported.
If needed, you would then manually have to move the items into different plentymarkets categories.
====

[#warehouse-mapping]
=== Step "Map warehouses"

In this step, you map your Channel Store Number from SPoCC to your plentymarkets warehouses.

[[table-warehouse-mapping]]
.Mapping warehouses
[cols="1,3a"]
|===
|Setting |Explanation

| *SPoCC Channel Store Number*
|These are the warehouses in SPoCC.
Select the appropriate Channel Store Number from the drop-down list.

| *plentymarkets warehouse*
| These are the warehouses in the plentymarkets menu *Setup » Stock » Warehouse*.

|===

////

    "

[#cron-settings]
=== [TODO] Step "Cron settings"

Data is transmitted between SPoCC and plentymarkets with the help of Crons.

include::_includes:partial$crons.adoc[]

In this step, you’ll activate the cron jobs that should run automatically (icon:check-square[role="blue"]).

[[table-cron-settings]]
.When do the crons run?
[cols="1,1,3a"]
|===
|Cron |Interval |Explanation

| *Item import*
|Daily
|
* Once you have completed the assistant, all of your items will initially be transmitted from SPoCC to plentymarkets.
This initial, full import can take a few days to finish, depending on the number of products.
* Afterwards, only a sub-set of items will be imported, based on the previously selected xref:business-decisions:SPoCC.adoc#70[import settings
* Only new items are imported and new variations on existing items.
Existing items are not updated with this cron.
* The item import starts at the end of the day, or rather during the night.

| *Item update*
|Hourly
|Existing items and variations are updated.
This cron updates the following data:

* Linked variation properties
* Tags (assuming that the SPoCC pattern is imported as a tag)
* Manufacturers (assuming that the manufacturer is imported)
* EAN

| *Price update*
|Hourly
|

| *Stock update*
|Every 15 minutes
|
|===
////

[#120]
== Opening and modifying newly imported item data

The next time the cron job runs, your item data will be transmitted from SPoCC to plentymarkets.
This assumes that you’ve:

* activated the *Item import* cron (icon:check-square[role="blue"]).
* completed the assistant.
* activated the plugin within the set.

[#130]
=== Opening newly imported items

Open a few item data records and make sure that your item data was correctly imported.

. Go to *Item » Edit item*.
. Use the xref:item:search.adoc#[search filters] on the left to specify which items you want to access.
For example:
.. Set the *Active* filter to *ALL* or *No*, since items are inactive when they are imported.
.. Set the *Tag* filter to whichever xref:business-decisions:SPoCC.adoc#70[tag for newly imported items] you chose in the assistant.
. Click on *Search* (icon:search[role="blue"]). +
→ The search results are displayed in an overview on the right.
. Click on an item in the overview to open the item data record.

[TIP]
.Main variation vs. Sub-variation
====
Check the data that was transmitted for the main variation and for the sub-variations.

* *_Main variation_*: An item’s first variation is called its main variation.
It is not for sale, but rather is purely virtual and helps you manage the sub-variations via xref:item:inheritance.adoc#[inheritance].
When you open an item data record, the main variation automatically opens too.
* *_Sub-variation_*: The sub-variations are the saleable versions of the product.
For example, if a t-shirt is sold in the colours blue and red and the sizes S, M, L, then every single combination (Blue S, Blue M, Blue L, Red S, Red M, Red L) is a sub-variation.
To open a sub-variation, click on the tab *Variations* and then on *Search* (icon:search[role="blue"]).
Finally, click on a sub-variation in the overview.
====

[#140]
=== Modifying item data

Once you’re happy with the item data that was transmitted, you can start preparing your items to be sold online.
For example, you can:

* add xref:item:managing-items.adoc#50[descriptive texts], xref:item:managing-items.adoc#90[product images] and relevant xref:item:managing-items.adoc#50[meta data].
* specify where your products should be sold, i.e. select xref:item:managing-items.adoc#340[order referrers] and xref:item:managing-items.adoc#340[clients].
* xref:item:managing-items.adoc#200[activate] your variations when you are ready for them to go live.

For a complete list of all the item data fields in plentymarkets, refer to the page xref:item:managing-items.adoc#[Directory of data fields].

[#150]
== Processing orders

When a product is sold, the order data lands in the plentymarkets menu *Orders » Edit orders*.
The order can be processed here and its progress can be tracked with the help of a status.

Further information about processing orders in plentymarkets can be found on the xref:orders:managing-orders.adoc#[Managing orders] page of the manual.

[#160]
== Setting up event procedures

Of course, the order data shouldn’t just stay in plentymarkets. Rather, it should also be transmitted to SPoCC.
You’ll set up four so-called event procedures to do this.
They only need to be set up once, in order for the export to work correctly.

[.instruction]
Setting up an event procedure:

. Go to *Setup » Orders » Events*.
. Click on *Add event procedure* (icon:plus[role="green"]). +
→ The *Create new event procedure* window opens.
. Enter a distinct name for the event procedure.
. Select the event as listed in the following tables.
. Click on icon:save[set=plenty, role="green"] *Save*. +
→ The event procedure is created and can be edited further.
. Click on *Add procedure* (icon:plus[role="green"]) and select the procedure as listed in the following tables.
. Optional: Click on *Add filter* (icon:plus[role="green"]) and select filters if you only want the event procedure to apply in certain situations.
For example, the event procedure could only apply to specific sales channels or clients.
. Activate the event procedure (icon:check-square[role="blue"]) once it should go into effect.
From the point of activation onwards, the event procedure applies your settings to the selected orders.
. Save (icon:save[set=plenty, role="green"]) the settings.

For further information, refer to the xref:automation:event-procedures.adoc#[Event procedures] page of the manual.

[#170]
=== Notifying SPoCC of new orders

When a new order lands in plentymarkets, SPoCC should be informed of the order.
This allows SPoCC to reserve the necessary stock and avoid overselling.

[[table-event-procedure-one]]
[cols="1,2"]
|===

|Event
|New order

|Filter (optional)
|Order > Referrer +
Order > Client (store)

|Procedure
|Plugins > SPoCC: Reserve stock
|===

[#180]
=== Notifying SPoCC of shipping

Automatically inform SPoCC that the order is ready for shipping.

[[table-event-procedure-two]]
[cols="1,2"]
|===

|Event
|Outgoing items booked

|Filter (optional)
|Order > Referrer +
Order > Client (store)

|Procedure
|Plugins > SPoCC: Notify SPoCC of shipping
|===
