= Traffic usage
:keywords: Usage, usage data, traffic usage, traffic
:author: team-app-bi
:description: This page explains the calculation types, dimensions and filters available to you for the key figure Traffic usage.

The data volume and allowed traffic provided to you depends on your plentysystems edition. You will be billed separately if you exceed the amount of memory available to you. This is why you can track the data volume your plentysystems system uses at any time.

:key-figure: The traffic usage

include::partial$key-figure-introduction.adoc[]

[TIP]
.What is traffic?
====
Do you need more information on this topic or are you unsure which events cause so-called traffic? Take a look at the xref:business-decisions:hosting-data.adoc#100[Usage data] manual page.
====

[IMPORTANT]
.Using the default key figure
====
The key figure *Traffic usage* is a so-called default key figure. This means that it is already set up in your system with some preparatory settings. Thus, you don’t necessarily have to create an additional key figure. Go to *Setup » plentyBI » Key figures* and click on the key figure *Traffic usage* that has been created by `plentymarkets`. If needed, adjust the preselected options and add the desired <<#300, filters>>.
====

[#100]
== plentyBI edition

This key figure is free of charge.
So you can use the key figure without having to book a plentyBI edition first.

However, note that _other functions and key figures_ cost money in the plentyBI tool.

Simply choose the right plentyBI edition with the help of the plentysystems configurator.

* *_New customers_*: Choose the appropriate plentyBI edition link:https://get.plentymarkets.com/[while you order plentysystems^].
* *_Existing customers_*: Choose the appropriate plentyBI edition xref:business-decisions:your-contract.adoc#30[in the "My account" area].

[#200]
== Dimension

=== Creation date

:key-figure: The traffic usage
:this-means: This means that usage data is grouped by the date on which the usage was caused.

include::partial$creation-date.adoc[]

[#300]
== Filters

include::partial$filter-introduction.adoc[]

=== Creation date

Use this filter to group traffic usage by the date or period of time in which the usage was caused.

Select a comparison operator and then select the desired date or time period on the right.

//Praxisbeispiel (mit Kachel) hinzufügen
