= Usage
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Usage, Usage data, Change history, History
:position: 1300
:url: business-decisions/plenty-bi/key-figures/usage
:id: UU0TJVT
:author: team-item
//zuletzt bearbeitet 08.03.2021
//ToDo - Video einbinden

When you use the <<data/change-history#100, change history>>, the following costs are incurred based on usage:

* 15 cents per 10,000 logged changes.
* 15 cents per 10,000 archived changes.
* 1 euro for requesting a file from the archive.

To know how much the change history costs, you first need to know how much it’s used.
With the help of this free key figure, you can view your usage any time.

//Video

:key-figure: Usage

include::../../_textblocks/plentyBI-template/key-figure-introduction.adoc[]

[#100]
== Calculation

=== Average
//Durchschnitt wird wohl erst für andere Anwendungsfälle außer Änderungshistorie Sinn machen - ist nur als Vorbereitung da

:key-figure: The usage
:that-means: That means, the key figure displays the average number of loggable changes.

include::../../_textblocks/plentyBI-calculation-type/average.adoc[]

////
[discrete]
===== Example of use

Are you curious how much the change history costs you _on average_ each month?
Proceed as follows:

. Create a “usage” key figure and select the “average” calculation type.
. In the <<business-decisions/plenty-bi/myview-dashboard#400, dashboard>>, create a bar chart to visualise your average usage data over the last 12 months.
. <<business-decisions/plenty-bi/key-figures/usage#600, Calculate>> your average monthly costs based on this usage data.
////

=== Maximum
//Maximum wird wohl erst für andere Anwendungsfälle außer Änderungshistorie Sinn machen - ist nur als Vorbereitung da

:key-figure: The usage
:that-means: That means, the key figure displays the highest number of loggable changes so far.

include::../../_textblocks/plentyBI-calculation-type/maximum.adoc[]

=== Total

:key-figure: The usage
:that-means: That means, the key figure displays the total number of loggable changes.

include::../../_textblocks/plentyBI-calculation-type/sum.adoc[]

[discrete]
===== Example of use

Are you curious how much the change history will cost you this month?
Proceed as follows:

. Create a “usage” key figure and select the “total” calculation type.
. In the <<business-decisions/plenty-bi/myview-dashboard#400, dashboard>>, create a tile to display the total number of changes this month.
. <<business-decisions/plenty-bi/key-figures/usage#600, Calculate>> your total costs for the month accordingly.


[#200]
== Dimension

=== Creation date

:key-figure: The usage
:this-means: This means that the date when the change was logged is considered in the calculation.

include::../../_textblocks/plentyBI-dimensions/creation-date.adoc[]

[#300]
== Filters

include::../../_textblocks/plentyBI-template/filter-introduction.adoc[]

=== Creation date

Do you want to know how many changes were logged on a specific date or during a specific time period?
Use this filter to analyse your usage according to the date when the change was made.

Select one of the following comparison operators and then select the desired date from the calendar (icon:calendar[]).


[.collapseBox]
.Comparison operators available for this filter
--


:filter-ending: selected dates (icon:calendar[])
:filter: selected dates (icon:calendar[])
:commas:

[[table-key-figures-operators-created-at]]
[cols="1,1,3"]
|====
| Comparison operator | Symbol | Explanation

include::../../_textblocks/plentyBI-operators/is-equal-to.adoc[]

include::../../_textblocks/plentyBI-operators/is-between.adoc[]

include::../../_textblocks/plentyBI-operators/greater-than-or-equal-to.adoc[]

include::../../_textblocks/plentyBI-operators/less-than-or-equal-to.adoc[]

include::../../_textblocks/plentyBI-operators/greater-than.adoc[]

include::../../_textblocks/plentyBI-operators/less-than.adoc[]


|====

--

=== Service

Do you only want to analyse a specific aspect of the change history?

[cols="1,3"]
|====
| Service | Explanation

| *Change history - Live changes*
|Use this filter to determine the number of logged changes in the <<data/change-history#200, live search>>.

*_Note_*:
Usage data is tallied up once a day.
This is done each night for the previous day.
So tonight for yesterday.

| *Change history - Archive changes*
|Use this filter to determine the number of logged changes in the <<data/change-history#1000, archive>>.

*_Note_*:
Usage data is tallied up once a month.
So if you track your usage e.g. with a bar chart, you will notice a monthly spike when the archive data is calculated.

| *Change history - Archive requests*
|Use this filter to see how often someone requested an <<data/change-history#1000, archive file>> for a fee.
|====

Select one of the following comparison operators from the first drop-down list. Select the appropriate service from the second drop-down list.

[.collapseBox]
.Comparison operators available for this filter
--


:filter-ending: service selected
:commas:

[[table-key-figures-operators-created-at]]
[cols="1,1,3"]
|====
| Comparison operator | Symbol | Explanation

include::../../_textblocks/plentyBI-operators/is-equal-to.adoc[]

include::../../_textblocks/plentyBI-operators/is-not-equal.adoc[]


|====

--

[#400]
== Required raw data

None.
Unlike other key figures, you don’t have to activate any raw data here.

However, since this key figure measures your use of the change history, you will only see data if you have <<data/change-history#1100, activated the change history for your system>>.

[#500]
== Edition

This key figure is free of charge.
So you can use the key figure without having first booked a plentyBI edition.

However, note that _other functions and key figures_ cost money in the plentyBI tool.
Simply choose the right plentyBI edition with the help of the plentymarkets configurator.

* *_New customers_*: Choose the appropriate plentyBI edition link:https://get.plentymarkets.com/[while you order plentymarkets^].
* *_Existing customers_*: Choose the appropriate plentyBI edition <<business-decisions/your-contract#30, in the "My account" area>>.

[#600]
== Example calculation

When you use the <<data/change-history#100, change history>>, the following costs are incurred based on usage:

* 15 cents per 10,000 logged changes.
* 15 cents per 10,000 archived changes.
* 1 euro for requesting a file from the archive.

So if you want to use plentymarkets in compliance with GoBD regulations - i.e. if you want to store relevant changes in plentymarkets for up to 11 years - then you will be charged 30 cents for every 10,000 changes.
The cost of a data package is only billed in the month in which it was logged.


On average, a system makes 177,000 loggable changes during one month.
This corresponds to an average of 18 packages (177,000 / 10,000 rounded up).
If the change history and archive are both activated, then the average cost per month is 18 * 0.15 * 2 = €5.40.
