= User accounts and access
:keywords: Owner, User, User accounts, User account, Manage users, managing users, user management, manage user accounts, managing user accounts, Role, Roles, Right, Rights, assign rights, assigning rights, menu and REST API rights, determine visibilities, access, user access, CUL user licence, user licence, user licences, limit, limitation, password strength, password security, admin, REST API, master data, plentymarkets forum, session management, admin rights
:description: Working with plentymarkets: Manage user accounts, create new user accounts and edit existing user accounts in the plentymarkets system.
:id: CHBIF6G
:author: team-plenty-channel

:user access: pass:quotes[Select a *user access*.]
:table: Pay attention to the information given in <<table-user-accesses>>.

Create accounts for new users and edit existing user accounts in the user menu. Furthermore, assign roles and accesses to users.

* You use roles to group user accounts, assigning the same rights to several accounts.
* Within the roles you assign menu and plugin visibilities as well as REST-API permissions.

Five free CUL user licences are included in every plentymarkets system. If you need additional user accounts, book them in the link:http://www.plentymarkets.co.uk/prices/[configurator].

[NOTE]
.What is a CUL user licence?
====
CUL stands for concurrent user licencing. The licence determines how many user accounts can have access to the plentymarkets back end, the REST API and the plentymarkets app. As such, we limit simultaneous use and not the number of user accounts you can create.
====

[#35]
== Security settings

In the menu *Setup » Account management » Security* you manage the requirements for new passwords that users must fulfil

[.instruction]
Configuring the security settings:

. Open the menu  *Setup » Account management » Security*.
. Carry out the settings. Note <<#table-password-security>>.
. *Save* (material:save[]) the settings.

[[table-password-security]]
.Password strength and automatic logout
[cols="1,3"]
|====
|Setting |Explanation

2+^| *Password security*

| *Activate password security*
|If this option is active, new passwords must meet the criteria set for password security.

| *Minimum length*
|Enter the minimum number of characters for new passwords. +
*_Note:_* For security reasons, the minimum length is 8 characters.

| *Password criteria*
|Activate the criteria for new passwords. +
*_Note:_* For security reasons, at least 3 criteria have to be activated.

| *Minimum amount of fulfilled criteria*
|Select the minimum number of criteria that new passwords need to meet. +
*_Note:_* For security reasons, at least 3 criteria have to be activated.

| *Number of latest passwords*
|Enter the number of previously used passwords that users cannot use again. The user is notified, if they try to enter a previously used password. If you do not want to use this function, let the slider stay at 0. +
*_Note:_* The number of passwords to be saved has to be 20 or less.

| *Maximum password age (days)*
|The user account is locked at the end of this period. If you do not want to use this function, let the slider stay at 0.

| *Password expiration notification (days):*
|Choose the number of days with the slider.
This many days before the password expires, the user will start receiving a daily reminder to change the password.
If you do not want to use this function, let the slider stay at 0.
|====

[#10]
== Creating a user account

When using your plentymarkets system for the first time, a default user account of the access type *Administrator* with administrative rights is already set up in the system. You need at least one administrator user account. As such, either create a new user account of the *Administrator* access and delete the default user account afterwards or edit the existing user account. Proceed as described below to create a new user of any access type.

include::partial$benutzerkonto-erstellen-en_gb.adoc[]

The user name must not contain any spaces and must have at least 5 characters.

The user accesses are preset and the accesses' settings cannot be changed. The following table includes detailed information about preset rights and rights that you can assign individually:

[[table-user-accesses]]
.Overview of available user accesses
[cols="1,3"]
|====
|Access |Explanation

| *Administrator*
|Access with all rights and no restrictions. Has to be assigned to at least one user account because only an administrator can create, edit and manage user accounts without any restrictions. When using multiple administrator accounts, these accounts all have equal rights.

| *Only API user*
|Access for xref:business-decisions:user-accounts-access.adoc#120[REST calls] that can be assigned in the user account. REST calls are activated individually. REST calls are not assigned to user accounts by default. +

*Attention*: Users with this user access are not allowed to access the back end.
|====


[NOTE]
The access types *Call centre*, *Logistics*, *Blog* and *Newsletter2Go* do not exist anymore and have been migrated to the standard user account.


[#20]
== Editing a user account

After creating a user account, the new account is displayed in the user account overview. Select a user account to edit the account settings. You may not be able to see all of the settings. The settings that are visible depend on your own user access and on the user access of the user account that is being edited.

[.instruction]
Editing a user account:

. Open the menu  *Setup » Account management » Accounts*.
. Click on *Search* (material:search[]). +
→ All user accounts are displayed.
. Take the changes according to <<#table-user-data>> 
. *Save* (material:save[]) the settings.

[TIP]
.Password is saved
====
The password you entered when creating your user account will not be visible in the editing mode later on, but it is saved. You do not have to re-enter the password when editing the user account.
====

[#30]
=== Entering user data

In the user account you enter information and change the settings of a user account. Only users with administrative rights can edit the *user name*, *IP restriction*, *user access* and *roles*. All other user data can also be changed by a user in their own account. In this tab, it is also possible to block a user account.

[[table-user-data]]
.A user account's data
[cols="1,3"]
|====
|Setting |Explanation

2+^| *General*

| *User*
|Enter a name without spaces. The user name is a mandatory field and is needed for the login. The user name must not contain any spaces and must have at least 5 characters.

| *Name*
|Actual name of the user displayed in the title bar of the plentymarkets back end.

| *Email*
|Enter the user account's email address. The email address is important for system notifications, notifications from event procedures and group communication within the system.

| *Time zone*
|Select the user's time zone.

| *Language*
|Select the language for the admin area. This is the default language that is used when logging in.

2+^| *Login data*

| *Password*
|Enter a new password to give the user account this password.

| *Repeat password*
|Enter the password again.

| *App Pin*
|include::app:partial$app-pin.adoc[]

| *Repeat App Pin*
|Re-enter the PIN.

| *Restrict IP*
|Enter the IP address of the user's computer. The user will only be allowed to log into plentymarkets with this IP address.

| *Enable Forum Account*
|Click if a forum account should be created for the user. The user must have entered a valid Email address 

| *User deactivated*
|Activate to deactivate the user account. Deactivated users will no longer be able to log into the system.

2+^| *Rights*

| *User access*
|Select the user access for the user account. You can choose between*Administrator* and *Only API user*. +
 An *Administrator* has all menu visibilities, role-defined views, access rights and permissions. They can create and deactivate user accounts as well as unblock the login. Besides that, they can create, edit, delete and assign roles. +
 *Only API user* can only use REST-API calls, they do not get any menu or plugin visibilities.

| *Assigned roles*
|Select roles for the user account. xref:business-decisions:user-accounts-access.adoc#70[Roles] have to be created beforehand so they can be selected here.

| *Signature*
| Text that is automatically attached to messages and comments of the user within the ticket system.

| *Ticket complimentary close*
| Text, that is automatically attached to messages and comments of the user within the ticket system as xref:crm:using-the-ticket-system.adoc#300[complimentary close].
|====

[#40]
=== Activating owners

If the user account should be an owner, is determined by activating *Edit* and/or *Create* in the visibilities of the simple mode role view. For example: if a role needs to be an owner for orders, you need to assign *Edit* or *Create* in *Order*.

[TIP]
.Edit and Create are not available
====
There are visibilities were you can only activate *See*. In this case the role will be active as owner when *See* is activated.
====

[.instruction]
Setting a user as owner:

. Open the menu  *Setup » Account management » Roles*.
. Select a role. +
→ The rights overview of the role opens in simple mode.
. Activate *Edit* or *Create* in the column which the role should be available as an owner.
. *Save* (material:save[]) the settings.

// Attention // // //

[#42]
=== Managing mailboxes

If plentymarkets manages your domains, then you can go to *Setup » Settings » Email* to create and manage mailboxes for system users. You need admin rights to manage mailboxes. These mailboxes are created and hosted by the third party email provider link:https://mailbox.org/business/[mailbox.org^]. You will learn how to create mailboxes and additional email addresses (aliases) for these mailboxes.

[IMPORTANT]
.Mailboxes with other provider
====
The configuration described is only relevant for plentymarkets customers with domains managed by plentymarkets who want to use the external provider link:https://mailbox.org/business/[mailbox.org^]. If you manage your email account with a different provider and want the plentymarkets system to send emails from this provider too, you do not need to set up mailbox.org. However, you still need to refer to chapter xref:crm:emailbuilder.adoc#email-server-login-details[Saving the email server's login details] on the xref:crm:emailbuilder.adoc#[EmailBuilder] page of the manual.
====

[#44]
==== Create mailbox

Proceed as described below to create mailbox.org mailboxes for system users. You need admin rights to create mailboxes and aliases.

[.instruction]
Creating a new mailbox:

. Go to *Setup » Settings » Email*.
. Click on *Create mailbox*. +
→ The *Create mailbox* window opens.
. Select the email address type *Mailbox*.
. Carry out the additional settings. Note <<#table-mailbox>>.
. Click on *Create mailbox*. +
→ The mailbox is created on the servers of the external provider mailbox.org.

[[table-mailbox]]
.Create mailbox
[cols="1,3"]
|====
|Setting |Explanation

| *Email address type*
|Select the email address type *Mailbox*. +
*Mailbox* = A new mailbox is created. +
*Alias* = An additional email address for an existing mailbox is created. Select the mailbox for this alias by selecting the option *Target mailbox*.

| *Email address*
|Enter the email address that you want to assign to this mailbox. Enter the local part of the email address left of the @ sign. Select the domain part of the email address from the dropdown list. +
*_Note:_* You cannot create mailboxes for test domains (for example @plenty-test-drive) or for external domains that are not hosted by plentymarkets. +
*_Note:_* After an email address is deleted, this address is locked for 48 hours. You need to wait until the end of this period before you can create an email address with this name again.

| *First name* +
*Last name*
|Enter the first name and last name of the person with this user account. This name will be displayed with the email address as part of the sender information.

| *System user*
|Select the user account you want to assign the mailbox to.

| *Forwarding*
|Enter one or more email addresses if you want to forward emails sent to this address to a different mailbox. Separate multiple email addresses by commas, for example customer@your-plentystore.co.uk,consultant@your-plentystore.co.uk.

| *Save emails in mailbox*
|Option becomes selectable once a forwarding address is entered. +
Activated = Emails are forwarded to the target email addresses. Copies of the forwarded emails will be saved in this mailbox. +
Not activated = Emails are directly forwarded to the target email addresses. No emails are saved in this mailbox.

| *Password*; +
*Repeat password*
|Enter a password and re-enter it for confirmation. +
*_Note:_* The password has to contain at least 8 characters and a combination of upper case letters, lower case letters and numbers.

| *Rate*
|Select a fee model. All prices shown are subject to VAT. Your plentymarkets contract will be updated after the mailbox is created.
|====

==== Saving the mailbox.org server's access data in plentymarkets

For plentymarkets to send emails such as order confirmations on your behalf, you need to save the link:https://kb.mailbox.org/en/private/faq-article/setup-other-e-mail-clients-manually[login details] of the mailbox.org mailbox from which you want to send these emails in the xref:crm:emailbuilder.adoc#email-server-login-details[Email accounts] assistant in the *Setup » Assistants » Basic setup* menu.

[#46]
==== Creating an additional email address (alias) for a mailbox

Create an alias for the mailbox if you want the mailbox to be linked to more than one email address. The number of email addresses you can create per mailbox depends on the fee you select. Proceed as described below to create an additional email address for a mailbox.

[.instruction]
Creating an additional email address for a mailbox:

. Go to *Setup » Settings » Email*.
. Click on *Create mailbox* (material:add[]). +
→ The *Create mailbox* window opens.
. Select the email address type *Alias*.
. Carry out the additional settings. Note <<#table-email-addresses>>.
. Click on *Create mailbox*. +
→ The additional email address is created.

[[table-email-addresses]]
.Creating an additional email address for a mailbox
[cols="1,3"]
|====
|Setting |Explanation

| *Email address type*
|Select the email address type *Alias*. +
*Mailbox* = A new mailbox is created. +
*Alias* = An additional email address for an existing mailbox is created. Select the mailbox for this alias by selecting the option *Target mailbox*.

| *Email address*
|Enter the email address that you want to assign to this mailbox. Enter the local part of the email address left of the @ sign. Select the domain part of the email address from the dropdown list. +
*_Note:_* After an email address is deleted, this address is locked for 48 hours. You need to wait until the end of this period before you can create an email address with this name again.

| *Target mailbox*
|Select the mailbox that emails to this alias address are to be sent to.
|====

[#46a]
==== Change basic fee

By default, the basic fee *Business Reseller* applies to the hosting of mailboxes by mailbox.org through plentymarkets. This basic fee is free. However, it does not include support by mailbox.org. You can change your basic fee at any time. Change your basic fee model if you want to receive support from mailbox.org or want to extend the services you receive from mailbox.org. The selected basic fee applies to all mailboxes in your plentymarkets system including all clients.

[.instruction]
Changing your basic fee model:

. Go to *Setup » Settings » Email*.
. Click on *Change basic fee* (material:edit[]). +
→ The *Select basic fee* window opens.
. Check the specifications of the different basic fee models.
. Select the basic fee you want to book.
. Click on *Change basic fee*. +
→ The fee is saved and your plentymarkets contract is updated. mailbox.org will send you an email with additional information.

[#47]
==== Deleting a mailbox

Proceed as described below to delete a mailbox. You need admin rights to delete mailboxes/aliases. After deleting a mailbox/alias, you need to wait 48 hours before you can create a new mailbox/alias with the email address that you just deleted.

[WARNING]
.Emails can no longer be accessed after deleting a mailbox
====
After deleting a mailbox, you can no longer access the emails saved in the mailbox via mailbox.org. Make sure that you have saved local copies of any emails you still need access to before deleting the mailbox.
====

[.instruction]
Deleting a mailbox:

. Go to *Setup » Settings » Email*. +
→ A list of the mailboxes is displayed.
. Click on the mailbox in this list that you want to delete.
. Click on *Delete* (material:remove[role="red"]). +
→ The mailbox and all associated aliases are deleted on the mailbox.org server. +
→ Your plentymarkets contract is updated.

[#50]
=== Personal settings

You find the *personal settings* either under plentymarkets logo on the top left or under your profile picture in the top right. In this area, you can change the settings of the user account currently logged into the system. Therefore, you can only see this tab in your own user account. The personal settings are separated in the tabs xref:welcome:customising-system.adoc#70[General] and xref:welcome:customising-system.adoc#80[Shortcuts] that only affect you.

[#85]
== Editing multiple user accounts

Edit multiple user accounts with the *More* (material:more_vert[]) in the *User* menu. Here, previously selected user accounts are edited.

[.instruction]
Using the group function:

. Open the menu  *Setup » Account management » Accounts*.
. Select the users that you want to edit.
. Click on *More*  (material:more_vert[]).
. Carry out the settings. Note the explanations in <<#table-more>>.
. Click on *Apply*. +
→ The user accounts are updated.

[[table-more]]
.Editing multiple user accounts via *More*
[cols="1,3"]
|====
|Setting |Explanation

|*Assign roles*
|Activate to assign one or more roles to selected user accounts. A dialog opens. Choose one or more roles in the drop down menu. Confirm your selection by clicking on *Assign roles*. The roles will be assigned to the selected user accounts.

|*Remove roles*
|Activate to remove one or more roles to selected user accounts. A dialog opens. Choose one or more roles in the drop down menu. Confirm your selection by clicking on *Remove roles*. The roles will be removed from the user accounts.

| *Send email*
|Activate to send an email to the selected user accounts. The email programme opens. The email addresses of the user accounts are entered in the recipient field.

| *Reset previously started box picking*
| Activate to reset previously started box picking of selected users.

| *Logout*
|Activate to log out selected users.
|====

[#105]
== Managing rights

In plentymarkets you assign rights by assigning roles. The roles include menu and plugin visibilities as well as REST-API permissions. Thus, a user has always the rights of the roles that were assigned to them. Only exception being administrators that have every right, independent of roles.
In the menu *Set » Account management » Roles* you can create new roles or edit existing ones. When creating or editing a role you can assign resources that should be visible for the user under *access rights*. Roles can be created by user that are *Administrator* or from user that have the necessary rights to do so. +
Assign every user account only those rights required for their field of work. This way, security is increased and errors can be prevented in your system.

The table of the user rights is divided in four columns. In these columns you can assign rights when checking the boxes in the *See*, *Edit*, *Create* or *Delete* option. Two of these four options change there name in the advanced mode: *See* changes to *Read* and *Edit* to *Update*.

[#106]
=== Simple and advanced mode

When creating or editing a role there are two modes: the simple and the advanced mode. Which mode is relevant for which role depends on the rights you want to assign. The simple mode and advanced mode are linked. If you check menu visibilities in the simple mode the corresponding permissions in the advanced mode will be checked automatically. The connection only exists in this direction. If you check permissions in the advanced mode no menu or plugin visibilities will be checked automatically. +

You only have to switch to the advanced mode if you have a role that addresses the plentymarkets API by an app of your own. When you only use the plentymarkets apps, you should use the simple mode.



**Simple mode** = In the simple mode you can assign menu and plugin visibilities of the plentymarkets apps. The table of the simple mode is structured the same as the navigation and also displays individual plugins.

**Advanced mode** = In the advanced mode you assign permissions. These are REST-API rights that are necessary for loading and writing data.

[#110]
=== Assigning roles

To assign a role, proceed as follows:

. Open the menu  *Setup » Account management » Accounts*. +
→ The overview opens.
. Select an *Account*. +
→ The account detail view opens.
. Click on *Assigned roles* in the *Rights* area. +
→ The dropdown menu expands.
. Choose an existing role. +
*_Or:_* Create a new role. Therefore, click on *Create new role* (material:add[]). +

→ The user account is assigned the rights of the role.

[#115]
=== Assigning rights for roles

[.instruction]
Assigning rights for roles:

. Open the menu  *Setup » Account management » Roles*. +
→ The overview opens.
. Click on *Search* (material:search[]) to see all existing roles.
. Select a role. +
→ The rights overview of the role opens in simple mode.
. Tick the check boxes in the respective area to assign the role rights. Activate entire areas or expand areas to activate individual rights that the user account should have access to.
. *Save* (material:save[]) the settings.

[#116]
=== Assigning rights for role-defined views

In the detail view of the role, you can assign views users of a role can see and use in the area *Role-defined views*. The default view is always preselected. Once another view exists, it is possible to deactivate the default view and to assign the rights for another view instead. Note that at least one view needs to be assigned.

[.instruction]
Assigning rights for role-defined views:

. Open the menu  *Setup » Account management » Roles*. +
→ The overview opens.
. Click on *Search* (material:search[]) to see all existing roles. +
→ All existing roles are displayed.
. Select a role. +
→ The overview opens.
. Click on *Role-defined views*. +
→ All role-defined views are displayed.
. Assign the rights for views by ticking the check boxes.
. *Save* (material:save[]) the settings. +
→ The rights for the selected views are assigned to the role.

[#100]
=== Assigning access rights

Under *Setup » Account management » Roles » [Select role]* you decide, which areas and settings a user can see when they a open a menu. For example: if the role does not have any rights assigned for specific warehouse or order status, no warehouse or order status is visible to them.

.Adjustable access rights
[cols="1,3"]
|====
|Setting |Explanation

| *Sales warehouse*; +
*Repair warehouse*; +
*Storage warehouse*; +
*Transit warehouse*; +
*Distribution warehouse*; +
*Special warehouse* (type *Other*) +
|Grant rights for warehouses to the user. Only previously created xref:stock-management:setting-up-a-warehouse.adoc#300[warehouse types] are available. +
*All* = The user has access to all warehouses. +
*None* = The user has access to none of the warehouses.

| *Visible order statuses*
|Select which order statuses should be *visible* to the user. The user with this role only see orders that have this status.

| *Selectable order statuses*
|Assign order status that user with this role should see.

| *Clients (stores)*
|Select one, several or all clients visible to the user with this role assigned. Users with this role will only be able to see those areas. If no client is selected, then specific rights such as the right to access certain menus will not go into effect. This is because the user will not have access to any of the clients. +
*All* = The user with this role has access to none of the warehouses. +
*Default* = The user with this role has access to the default store.

| *Ticket status*
|Select ticket statuses. Users with this role will be able to view and edit tickets that are in these statuses. +
*Invisible* = The user with this role will not see tickets with this status. +
*Visible* = The user with this role will sees all tickets with this status. +
*Own only* = The user with this role will only see tickets that are in this status and that they own. +
All tickets are listed in the ticket overview, including those tickets that are not visible to the role. However, the user with this role is unable to open invisible tickets.
|====

[#120]
=== Managing menu and REST API rights

In the advanced mode you specify which permissions for the REST API are granted to a user account with a role. User accounts of the *Administrator* access have all permissions.

[.instruction]
Managing menu and REST API rights:

. Open the menu  *Setup » Account management » Roles*.
. Select a role. +
→ Or create a new role.
. Switch to *Advanced* (material:toggle_on[role=skyBlue]). +
→ The table of the advanced mode is displayed.
. Assign the permissions for the respective area by ticking the check boxes. Activate entire areas or expand areas to activate individual rights that the user account should have access to.
. *Save* (material:save[]) the settings.

[#125]
=== Activating app rights

Under *Mobile* in the simple view of the roles you can determine which areas and key figures should be visible for a role in the plentymarkets App.

[.instruction]
Activating rights for mobile access:

. Open the menu  *Setup » Account management » Roles*.
. Select a role.
. Open the area *Mobile* in the simple view.
. Activate the functions and key figures that the role should have access to in the app.
. *Save* (material:save[]) the settings.

[#145]
=== Unblocking a user account

The maximum number of login attempts is 5 per user account or 25 per IP address. If the maximum number of login attempts is exceeded, the account is blocked for 24 hours. Users with admin rights can unblock a user account manually before this 24 hour period has passed.

[.instruction]
Unblocking a user account:

. Open the menu  *Setup » Account management » Accounts*. +
→ The user accounts are displayed.
. Double click on the blocked user account. +
→ The user account opens.
. Click on *Unblock login*. +
→ The user account is unblocked.

[#70]
== Creating roles

Roles are used for grouping user accounts and assigning the same rights to multiple user accounts without making changes to every single user account.

[.instruction]
Creating a new role:

. Open the menu  *Setup » Account management » Roles*.
. Click on *New* (material:add[]). +
→ The *New Role* window opens.
. Enter a *Name* for the role.
. *Save* (material:save[]) the settings. +
→ The role opens in a new tab and can be edited.

A role has to be edited in order to define rights that are assigned to user accounts with this role. Therefore, edit the role after creating it.

[#80]
== Editing roles

After creating a role, it will open in a new tab for editing. The role is also added to the role overview so that you can open and edit it easier. Roles are listed by ID in the overview. Every role is divided into four areas. Under *Settings* you can change the name of the role. Under *Rights* you assign menu and plugin visibilities in the simple view and REST-API permissions in the advanced view. Under *Role-defined views* you can assign the available views for MyView. The standard view is selected by default. Under *Access rights* you can assign resources the role should have access to. For further information about rights, refer to the xref:business-decisions:user-accounts-access.adoc#105[Managing rights] chapter. +

[.instruction]
Editing roles

. Open the menu  *Setup » Account management » Roles*.
. Open the role you want to edit. +
→ The rights overview of the role opens in simple mode.
. Change the role in the different areas by checking or unchecking the boxes.
. *Save* (material:save[]) the settings.

[.instruction]
Linking roles to a user account:

. Open the menu  *Setup » Account management » Accounts*.
. Open a user account.
. Click on *Assigned roles* in the *Rights* area.
. Select one, several or all of the listed roles.
. *Save* (material:save[]) the settings.

[.subhead]
Example of use

The administrator of the company MyStore creates multiple roles. All the rights to be assigned to every user account are included in the Employee role. With this role, it is no longer necessary to assign these rights to every single user. Also, changes to rights concerning all user accounts can be made in the Employee role. In addition to this role, the administrator creates the Warehouse technician and Accounting roles - specific roles for a small group of users only.

.Example for roles
[cols="1,3,3"]
|====
|Role |Authorisations |Menu visibilities

| *Employees*
|Clients (stores) » Standard
|Start » Webmail +
Start » Forum

| *Warehouse technician*
|Warehouse
|Setup » Stock » Warehouse +
Stock +
Orders » Fulfilment

| *Accounting*
|
|Start » Vacation +
Setup » Client » Select client » Accounting
|====

Mr. Doe is a logistics specialist at MyStore and receives the Employee and Warehouse technician roles. If a user account has several roles, the user rights are added up. Therefore, Mr. Doe receives the rights *Clients (stores)*, *Webmail* and *Forum* from the Employee role as well as the rights *Warehouse*, *Stock* and *Fulfilment* from the Warehouse technician role. However, he doesn't have the *Vacation* and *Accounting* rights because the Accounting role wasn't assigned to his user account.

== Copying roles

If you need an additional role which slightly differs from an existing role, copy the existing role and make changes in respective areas of the copy.

[.instruction]
Copying a role:

. Open the menu  *Setup » Account management » Roles*.
. Select a role.
. In the line of the role, click on *More* (material:more_vert[]). +
→ An option window appears.
. Choose *Duplicate role* +
→ The role will be created and named *Copy of [Name of the copied role]*.

[#60]
== Searching user accounts

Filters help you to search for user accounts. If no filters are used, all user accounts are displayed in the overview.

[.instruction]
Searching user accounts

. Open the menu  *Setup » Account management » Accounts*.
. Put in the necessary filter under *Filter*.
. Click on *Search*(material:search[]). +
→ The filtered user accounts show up.


.Filter options for users
[cols="1,3"]
|====
|Setting |Explanation

| *Search*
|Perform a search. Select appropriate filter options for the search beforehand.

| *Reset* (material:refresh[])
|Reset the filters to their original settings.

| *ID*
|Enter an ID to search for the user account that has this ID.

| *Name*
|Enter the name to search for the user accounts with this real name.

|*User*
| Enter the user name to search for the user accounts with this real name.

| *Email*
|Type in the Email address to search for user accounts with this specific Email address.
|====

[#150]
== Linking roles and processes

You can also use roles for xref:automation:setting-up-processes.adoc#[processes].

[.instruction]
Linking roles and processes:

. Go to *Setup » Processes » Per Role*.
. Click on the *arrow* in the line of a particular *role*. Then click on *New process* (image 1).
. Enter a *Name* for the role.
. Select the setting *Role* from the *Visibility* drop-down list. +
→ The option *Role* is displayed.
. Select a *Role* from the drop-down list.
. Select whether you want users of this role to be able to *change* the settings.
. Select the *warehouse* for the process and a *colour*.
. *Save* (icon:save[role="green"]) the settings.

The processes are displayed for the selected role. Due to the visibility setting, the process will be available to user accounts with the corresponding role only.

[#153]
== Creating an account for the plentymarkets forum

include::partial$forum-konto.adoc[]

[#160]
== Managing the number of logged in user accounts

Depending on your plentymarkets edition, the user accounts that can be logged into plentymarkets at the same time may be limited. This limit applies to the plentymarkets back end, the REST API and the plentymarkets app.

You can do the following if you reach the user limit:

* Ask users to log out manually
* <<#170, Log out users>>
* <<#190, Increase the user limit of your plentymarkets contract>>


[#170]
=== Logging out users

Proceed as described below to log out users.

[NOTE]
.Administrator rights mandatory
====
You need administrator rights to log out users.
====

[.instruction]
Logging out users:

. Go to *Setup » Account management » Accounts*.
. Click on *Search* (material:search[]). +
→ All user accounts are displayed.
. Activate the check boxes of the users that you want to log out.
. Click on *More* (material:more_vert[]). +
→ A dropdown menu opens.
. Click on *Logout*.
→ The selected users are logged out. +

[#180]
=== Logging out users when user limit is exceeded

If the number of user accounts has been reached or exceeded, admin users can access the *Setup » Account management » Accounts* menu by clicking on the error message that is shown when they attempt to log in.

[.instruction]
Logging out users when user limit is exceeded:

. Log into the plentymarkets back end. +
→ An error message is displayed.
. Click on the link in the error message. +
→ The *Setup » Account management » Accounts* menu opens. +
. Click on *Search* (material:search[]). +
→ All user accounts are displayed.
. Activate the check boxes of the users that you want to log out.
. Click on *More* (material:more_vert[]). +
→ A dropdown menu opens.
. Click on *Logout*.
→ The selected users are logged out. +
*_Note:_* The login via the error message is valid for 10 minutes. You are automatically logged out after this time.

[#190]
=== Booking additional user licenses

You can book additional user licenses in the xref:business-decisions:your-contract.adoc#["My account" area].

[.instruction]
Booking additional user licenses:

include::partial$accessing-configurator.adoc[]
