= Version (Beta, Early, Stable)
:keywords: State of development, Stage of development, Development stages, Version, Version cycle, Versioning, Software release, Software releases, Release cycle, Beta, Early, Stable
:description: Learn more about our system versions, their advantages and disadvantages, as well as how to change the version of your system.
:author: team-cloud

////
zuletzt bearbeitet 22.07.2022
////

plentymarkets is continuously being improved and developed further.
When a new function is released, it goes through three stages of development: Beta, Early and Stable.

[#10]
== Understanding the release cycle

[discrete]
=== Beta

Developer teams release their newly developed functions into the Beta version.
In this version, the function is tested and reported bugs are fixed.
The beta phase lasts a minimum of 7 days.

[cols="1a,1a", width=100%]
|===
|Advantages of Beta |Disadvantages of Beta

|
* Very early access to new features
* Lots of influence on development decisions
* Possibility to test your own plugins early

|
* Bugs may be encountered

|===

---

[discrete]
=== Early

After a minimum of 7 days, the Beta version is merged into the Early version. This assumes that no critical bugs were found during the Beta phase or that these bugs have been fixed. The early phase also lasts a minimum of 7 days.

[cols="1a,1a", width=100%]
|===
|Advantages of Early |Disadvantages of Early

|
* Early access to new features
* Faster support in the forum: queries are prioritised
* Some influence on development decisions

|
* May still contain some bugs

|===

---

[discrete]
=== Stable

After a minimum of 7 days, the Early version is merged into the Stable version. This assumes that no more serious bugs were found during the Early phase.


[cols="1a,1a", width=100%]
|===
|Advantages of Stable |Disadvantages of Stable

|
* Stability

|
* Later access to new features and improvements
* Less influence on development decisions

|===

[#20]
== Changing the version

Systems are given the Stable version by default.
However, if you want to benefit from improvements and new features earlier, then you can switch your system to an earlier version.

[IMPORTANT]
.This change cannot be undone
====
We’re happy that you want to help make plentymarkets even better by using an earlier version and reporting bugs.
But note that once you switch to an earlier version, it will not be possible to switch back.
Carefully weigh the advantages and disadvantages of the versions before switching your system.
====

[.instruction]
Switching your system to an earlier version:

. Go to *Setup » Client » Settings » Version*. +
*_Note_*: All clients have the same version.
So if you work with multiple clients, then they will all be switched to the new version.
. Use the drop-down list to select the version that you want to switch the system to. +
*_Important_*: You can only switch the system to an earlier version.
It is not possible to switch to a later version.
. *Save* (terra:save[role="darkGrey"]) the setting. +
→ The system will be switched to the selected version.
This can take up to 30 minutes.

[#30]
== Stay up to date

You want to be informed of newly developed functions and fixed bugs?
Take a look at our link:https://forum.plentymarkets.com/c/changelog/13[changelog].
It gives you an overview of the changes that have recently been made.
