= Changing state of development
:lang: en
include::{includedir}/_header.adoc[]
:keywords: State of development, Development state, Version, Version cycle, Version life cycle, Beta, Early, Stable
:position: 30
:url: business-decisions/system-administration/version-cycle
:id: 4YXZVNG
:author: team-cloud

plentymarkets is provided as software as a service. The code is improved and expanded continuously. The version life cycle of plentymarkets consists of the states of development *Beta*, *Early* und *Stable*.

[#10]
== States of development of plentymarkets version cycle

By default, your system is set to the *Stable* version. However, if you want to benefit from improvements and new features earlier, you can set your system to a version with an earlier state of development. <<table-version-cycle>> shows the states of development of the plentymarkets version life cycle.

[IMPORTANT]
.This change cannot be undone.
====
You want to help us to constantly make plentymarkets better by working with an early state of development and providing us with feedback regarding any bugs and improvements? Great! However, note that a change to a version with an earlier state of development cannot be undone. As such, carefully weigh the <<#table-version-cycle, advantages and disadvantages>> of the different states of development before setting your system to an earlier state of development.
====

[[table-version-cycle]]
.States of developments of the plentymarkets version cycle
[cols="1,3,1,1"]
|====
|State |Description |Advantages |Disadvantages

|Beta
|Developer teams merge finished features and functionalities into the *Beta* version. In this version, customers and partners can test these new features. Reported bugs are eliminated.
a| * Very early access to new features
* Very high degree of influence on development decisions
* Possibility to test your own plugins early
a| * Bugs can occur

|Early
|If no critical bugs are found or if these bugs have been fixed, the beta state is merged into the *Early* version after 7 days or more.
a| * Early access to new features
* Faster support Queries are prioritised
* High potential for influencing development decisions
a| * May still contain some bugs

|Stable
|If no substantial bugs are found during the *Early* phase, the state of the *Early* version is merged into the *Stable* version after 7 days or more.
a| * Stability
a| * Late access to new features and improvements
* Less potential for influencing development decisions
|====


[#20]
== Set system to earlier state of development

Proceed as described below to Switch to an earlier state of development.

[IMPORTANT]
.This change cannot be undone.
====
A change to a version with an earlier state of development cannot be undone. Carefully weigh the <<#table-version-cycle, advantages and disadvantages>> of the different states of development before setting your system to an earlier state of development.
====

[.instruction]
Set system to an earlier version of the version cycle:

. Go to *Setup » Client » Default client » Version*. +
*_Note:_* All clients have the same version as the default client. As such, the whole system is set to the selected version. +
→ The menu *Version* opens.
. In the drop-down menu, select the version you want to change to. +
*_Important:_* You can only set the system to an earlier state of development. The system cannot be set to a later state of development.
. *Save* the settings. +
→ The system is set to the selected state of development. +
*_Note:_* It can take up to 30 minutes for the system to be set to a different version.
