= Customising your system
:keywords: User account, user image, Gravatar, greeting, customary close, Signature, SignatureHTML, Personal settings, Menu layout, Edit layout, Menu layouts, Shortcut, shortcut key, start page, favourite, CSS editor, tasks, calendar
:description: Are you new to plentysystems? Then you'll probably want to customise your user account and system.
:author: denise-breidenbach

This manual page describes the settings as well as other areas of plentysystems you can use to personalise your user account.

[#10]
== Customising your own user account

[#20]
=== Opening the user account

There are two different ways to access your own user account.

* Hover with your mouse over the user icon (material:account_circle[]) in the top right, then click on your name.
* Open the menu  *Setup » Account management » Accounts*. Click on *Search* (material:search[]) and select your account.

[#30]
=== Adding a user image

In order to have a user image displayed instead of the empty user button (icon:user-circle[]) in your plentysystems back end, you have to be registered with link:https://de.gravatar.com/[gravatar.com^].

[.instruction]
Adding a user image:

. <<#20, Open your own user account>>. +
→ The user account opens.
. Enter the email address that you use for gravatar.com in the *Email* field.
. *Save* (icon:save[role="green"]) the settings. +
→ Reload the system to display the user image.

[#50]
=== Signature

Enter a text into the *Signature* area. This text is automatically added to the end of your messages and comments in the ticket system. Generally, this text consists of your contact details as well as information about where your company is registered and its registration number. Depending on your company’s legal form, the name of the company, the chief executive officer and, if applicable, the European VAT number are all mandatory inputs.
When sending emails from the ticket system, the signature will automatically be added to the end of the email.

[TIP]
.Template variable for the signature
====
The template variables *$Signature* and *$SignatureHTML* contain the complimentary close.
====

[.instruction]
Setting up the signature:

. <<#20, Open your own user account>>.
. Open the *Signature* area.
. Enter your signature.
. *Save* (material:save[]) the settings.

[WARNING]
.Mandatory entries in emails
====
Since the beginning of 2007, mandatory entries for email signatures in Germany correspond to those for company business letters. Non-compliance can result in a fine or in a costly warning being issued by a competitor. +
Read up on the legal regulations for signatures in your own country or contact a legal adviser for such information.
====

[#60]
=== Personal settings

You find the *personal settings* either under plentysystems logo on the top left or under your profile picture in the top right. In this area, you can change the settings of the user account currently logged into the system. The *personal settings* are divided into 2 tabs with settings that only apply to you personally. These tabs are *General* and *Shortcuts*.

[#70]
==== General

Under *General* you can activate *Warn if tabs are open when the window is closed*. When this is activated, your browser will show you a warning, if you close a browser window with plentysystems tabs open.

[#80]
==== Shortcuts

Default shortcuts are saved in this tab. Shortcuts are used for many functions that are carried out on a regular basis. You can use shortcuts to open important menus in plentysystems or to switch between tabs and tab levels. For example, the shortcut *Alt + I* opens the item overview.+I* the article overview opens. *Alt + W* is used to close the tab again.

[IMPORTANT]
.Some shortcut combinations are not possible
====
Do not use any shortcut that is specific to an operating system. Shortcuts differ from one operating system to the next. For example: the *F* keys. +
The combination *cmd / Strg + The combination *cmd / Ctrl
====

+
W* is reserved for the browser and is therefore not possible.[.instruction]Setting up shortcuts:

. Hover your cursor at the plentysystems logo at the top left of the screen. +
→ a dropdown menu expands.
. Click on*Personal settings*. +
→ The personal settings opens in the *Shortcuts* tab.
. Carry out the settings. See <<#table-shortcuts>>
. *Save* (material:save[]) the settings.

[[tabelle-shortcuts]]
.Shortcuts
[cols="1,2"]
|====
|Shortcut |Explanation

2+^| *General*

| *Alt + W*
|Closes the current tab.

| *Shift + Alt + RIGHT (arrow right)*
|Moves one tab to the right.

| *Shift + Alt + LEFT (arrow left)*
|Moves one tab to the left.

| *Alt + R*
|Reloads the current tab.

| *Alt + ESC*
|The user account is logged out.

2+^| *Open areas*

| *Alt + I*
|Opens the menu *Item » Edit item*.

| *Alt + O*
|Opens the menu *Orders » Edit orders*.

| *Alt + Y*
|Opens the menu *Item » Category*.

| *Alt + C*
|Opens the menu *CRM » Contacts*.

| *Alt + T*
|Opens the menu *CRM » Ticket system*.

| *Alt + N*
|Opens the area *New contact* within the menu *CRM » Contacts*.

// | *Alt + M*
// |Opens the menu *CRM » Quick search*.

| *Alt + S*
|Opens the *online shop*.

| *Alt + E*
|Opens the online shop with the inline editing function.

[NOTE]
.Restoring the default shortcuts
====
Click on *Reset shortcuts* (material:refresh[]) to reset the shortcuts to their default settings.
====

[#85]
==== Reset user interface configurations

In the toolbar of the personal settings you can reset user preferences back to default by clicking on *Reset user interface configurations* (material:refresh[]). User preferences include selected MyViews, table settings (column width, results per page and column configurations), favorites and global shortcuts.

[.instruction]
Proceed as follows to reset the user interface configurations:
. Hover your cursor at the plentysystems logo at the top left of the screen. +
→ a dropdown menu expands.
. Click on*Personal settings*. +
→ The personal settings opens.
. Click on *Reset user interface configurations * (material:refresh[]).
→ A pop-Up opens.
. Click on *Confirm*.
. *Save* (material:save[]) your settings.

[#90]
=== Favourites

If you use some menus very frequently, you may want to save them to a list of favourites. This allows you to access the menus quickly. Click on icon:ellipsis-v[] in the top right of the plentysystems back end to display your favourites.

Open up the *Favourites* tab within the personal settings of your user account to see all of the menu paths that were saved as favourites. Favourites can also be deleted in this menu. Use the *Up* and *Down* arrows to sort your favourites. The tab is only visible for your own user account.

[.instruction]
Adding a menu to favourites:

. Open the menu that you want to add to as favourite.
. Click in the tab of the menu on icon:ellipsis-v[] and select icon:star-o[] *Add link to favourites*. +
→ *_Note:_* Favourites are only visible in this menu once you have saved at least one favourite.

[.instruction]
Deleting a menu from favourites:

. Click on icon:ellipsis-v[] in the top right of the plentysystems back end. +
→ The list shows the favourites you saved. +
. Click on *x* next to the menu path to remove the menu from the favourites. +
→ icon:map-signs[] *_Or:_* Click on *Delete all favourites* and confirm the security question with *Delete* to delete all favourites saved in your system.

[#140]
== Adding further menus with plugins

include::partial$backend-plugin-sets-en_gb.adoc[]

Refer to the xref:plugins:plugins.adoc#[Plugins] chapter for further information about setting up plugins and plugin sets.

[#110]
== Personalising the dashboard

The dashboard is displayed when you log into plentysystems.
It shows you helpful statistics, diagrams and notes at a glance.

Admin users can customise the dashboard as needed.
In other words, they can decide which elements, statistics and notes should be displayed on the dashboard.

[TIP]
.Practical examples
====
You can decide which information should be displayed on the dashboard.
For example, you can add a:

* xref:business-decisions:myview-dashboard.adoc#700[diagram] to see the latest statistics and key figures for your company.
* xref:welcome:customise-system.adoc#190[task widget] to keep track of your current projects.
* xref:business-decisions:myview-dashboard.adoc#1100[forum announcement widget] to see important messages from the forum.
====

[#190]
== Practical example: tracking tasks

You can use the task widget to keep track of your company's work processes.
Simply assign tasks to individual employees and then track the progress of each task.
This way you can always keep an eye on current projects.

[TIP]
.Practical example: monthly newsletter
====
Imagine your company sends a monthly newsletter to inform customers of seasonal sales.
The marketing department is responsible for writing the texts, creating the graphics and sending the email.

* Create a newsletter task and assign it to your marketing department.
* Whenever a step is completed, the marketing team updates the progress.
* Since the task widget is on the dashboard, all of the participants can track the progress any time.
====

[#200]
[.collapseBox]
.*Necessary roles
--

Users without *Administrator* rights can only access limited areas and menus in the plentysystems back end. Thus, their access to the system is limited. Should a coworker see the menu *plentysystems Logo (Start) » Tasks* a person with *Administrator* rights needs to assign a fitting role.

[.instruction]
Setting the visibility for back end users:

. Open the menu  *Setup » Account management » Accounts*.
. Use the search function and open the account that you want to edit.
. Assign the appropriate role under *Assigned roles*. +
→ Or: create a role with *Task* visibilities in the simple mode in before.
. *Save* (material:save[]) the settings.

--

[#240]
=== Adding the task widget to the dashboard

If the task widget isn’t already on the dashboard, then an admin will need to add it.

[.instruction]
Adding the widget:

. Go to *plentysystems logo (Start) » Dashboard*.
. Click on *Edit view* (terra:design_inline_edit[]).
. Drag-and-drop the *My tasks* element from the settings menu on the dashboard.
. *Save* (terra:save[]) the settings.

Further information about xref:business-decisions:myview-dashboard.adoc#400[customising the dashboard].

[#210]
=== Creating a new task

Imagine your company sends a monthly newsletter to inform customers of seasonal sales.
You can create a newsletter task and assign it to your marketing department.

[.instruction]
Creating a task:

. Go to *plentysystems logo (Start) » Dashboard » Element: My tasks*.
. Click on *New task* (icon:plus[role="darkGrey"]). +
→ A pop-up window will open.
. Enter information about the task. Refer to the table.
. Click on *Save*. +
→ A task ID is automatically assigned by the system and cannot be changed.

[cols="1,3a"]
|===
|Setting |Explanation

| *Title*
|Enter a title for the task, e.g. "Newsletter".

| *Description*
|Enter a description of the task and format the text.
For example, you could write a list of the individual steps, such as “texts”, “graphics” and “send email”.

| *Progress*
|Move the slider to specify the task's progress as a percentage.

*_Note_*: This is the task's progress when it is first created.
The progress can be updated as the task moves forward.

| *Priority*
|Select the task's priority.
The priorities range from one grey star (lowest priority) to two yellow stars (highest priority).

| *Flag*
|Select a flag for the task.
The flag helps you find tasks again in the future.

| *Owner*
|Who is responsible for this task?
Select the task's owner, e.g. your marketing manager.
|===

[#230]
=== Tracking and updating your own tasks

The task widget displays your own tasks on the dashboard when you log into plentysystems.
You can edit your tasks further any time.
For example, you can update the progress or add information to the description.

[.instruction]
Updating a task:

. Go to *plentysystems logo (Start) » Dashboard » Element: My tasks*. +
→ Your incomplete tasks are displayed by default.
. Click on icon:ellipsis-v[role="darkGrey"] and decide how the task should be changed.
* icon:pencil[role="darkGrey"] *Update task* = The same pop-up window opens that you already saw while creating the task.
Here you can edit the task further.
* material:delete[role="darkGrey"] *Delete* = You will need to confirm your decision to delete the task.
* material:task_alt[role="darkGrey"] *Mark task as completed* = The progress will be set to 100% and the task will be moved to the *Completed* area.
* material:task_alt[role="darkGrey"] *Mark task as incomplete* = This option is only visible for completed tasks.
The progress will be set to 0% and the task will be moved to the *Incomplete* area.

[#220]
=== Tracking and updating company-wide tasks

It’s not only possible to manage your own tasks, but also to keep track of your employee’s tasks.

[.instruction]
Tracking company-wide tasks:

. Go to *plentysystems logo (Start) » Dashboard*. +
→ Your incomplete tasks are displayed by default.
. Click on *Reset* (icon:undo[role="orange"]) and select the necessary filters.
Refer to the table.
. Click on *Search* (icon:search[role="blue"]). +
→ The tasks that correspond to the search criteria entered are shown.

[cols="1,3a"]
|===
|Filter |Explanation

| *Title/Description*
|Filters for tasks that have a specific keyword in their title or description.
Enter the keyword into the text field.

*_Note_*: Enter at least 4 characters.
This is a full text search filter.

| *ID*
|Filters for the task with a specific ID.
Enter the ID into the text field.

*_Note_*: The system automatically assigns consecutive task IDs.
This ID cannot be changed.

| *Ticket ID*
|Filters for the tasks that belong to a specific ticket.
Enter the ticket ID.
xref:crm:using-the-ticket-system.adoc#4000[Further information].

| *Progress*
|Filters for the tasks that have a specific progress.
Select an operator and the progress from the drop-down lists.

| *Priority*
|Filters for the tasks that have a specific priority.
Select an operator and the priority from the drop-down lists.

| *Date of creation*
|Filters for the tasks that were created at a specific time.
Select an operator from the drop-down list and a date from the calendar (icon:calendar[]).

| *Flag*
|Filters for the tasks that have a specific flag.
Select the flag from the drop-down list.

| *Owner*
|Filters for the tasks that are assigned to a specific person.
Select the owner from the drop-down list.
|===

[#245]
=== Creating tasks in the ticket system

Not only can tasks be created in the widget, but they can also be created in the xref:crm:using-the-ticket-system.adoc#4000[ticket system].
For example, you can directly create any tasks that result from a telephone inquiry.

[.instruction]
Creating a task in the ticket system:

. Go to *CRM » Ticket system » [Open ticket] » Tab: Tasks*.
. Click on icon:plus[role="green"] *New task*.
. Carry out the settings. Refer to the explanations in the chapter xref:welcome:customise-system.adoc#210[Creating a new task].
. *Save* (terra:save[role="green"]) the settings. +
→ The task is linked to the ticket.
This link is also visible in the overview under *plentysystems logo (Start) » Tasks*.

[#150]
== Configuring table columns

In some meus, the overview is customisable.
That means, you can decide:

* which columns should be displayed.
* which order the columns should be displayed in.
* whether the results should be displayed in ascending or descending order.

[#183]
== Activating full screen mode

If you want to use more of your screen space for back end views, you can use full screen mode. Activating full screen mode hides the menu bar. You can show the menu bar dynamically by hover the mouse over the top edge of your browser tab.

To activate or deactivate full screen mode, click on icon:ellipsis-v[] in the upper right corner of the plentysystems back end, then click on either *Fullscreen on* material:fullscreen[] or *Fullscreen off* material:fullscreen-exit[].

[#185]
== Choosing a dark or light theme

There are various themes and options to change the design of your back end. You can change the following elements:

* Menu bar colour
* Size of various elements
* Button colour

To change the design of your back end, carry out the following steps:

[.instruction]
Changing the design:

. Hover over the user icon (icon:user-circle[]).
. Click on *Themes*. +
→ The *Themes* window opens.
. Select the desired design.

//// 
[#180]
== Bestimmte Editoren verbieten

Some menus have a drop-down list from which users can select their preferred editor.
By default, the editors *Editor*, *Syntax editor* and *Text field* are available for selection.
You can deactivate individual editors as needed, e.g. if you want to make sure that your employees only use the syntax editor.

[.instruction]
Deactivating editors:

. Go to *Setup » Settings » Editors*. +
→ The *Areas* tab opens.
. Remove the check mark next to the editors that should not be displayed in the drop-down list of the corresponding area.
. *Save* (icon:save[role="green"]) the settings.

[discrete]
=== Changing the CSS of the editor

The editor uses the *CSSContent* by default. If a background image is used there and this is bothersome or not desired, you can individually edit the CSS in the menu *Setup » Settings » Editors » Tab: CSS*. Alternatively, you can use the *Standard* CSS with a white background. You can also create your own *customised* CSS and specify additional formatting, e.g. fonts.

To change the CSS for the editor, go to *Setup » Settings » Editors » Tab: CSS*.

[.instruction]
Changing the CSS of the editor:

. Go to *Setup » Settings » Editors*.
. Click on the *CSS* tab.
. Select the desired CSS. Pay attention to the information given in <<table-css-editors>>.
. *Save* (icon:save[role="green"]) the settings.

[[table-css-editors]]
.Available CSS
[cols="1,3"]
|====
|Setting |Explanation

| *As in the online store (CSSContent)*
|The store CSS will be loaded in the editor.

| *Standard*
|A simple standard CSS will be loaded in the editor. The background colour is white.

| *User-defined*
|The simple standard CSS will be displayed in an editing window and can be customised with the syntax editor. +
*_Note:_* Click on *Reset* to reset the CSS to the standard CSS.
|====
////