= Customising your system
:keywords: User account, user image, Gravatar, greeting, customary close, Signature, SignatureHTML, Personal settings, Menu layout, Edit layout, Menu layouts, Shortcut, shortcut key, start page, favourite, CSS editor, tasks, calendar
:description: Are you new to plentymarkets? Then you'll probably want to customise your user account and system.
:author: denise-breidenbach

This page describes the settings that you can use to customise your user account and other areas of your plentymarkets system.

[#10]
== Customising your own user account

[#20]
=== Opening the user account

There are two different ways to access your own user account.

* Move your mouse cursor over the user symbol in the top right corner (icon:user-circle[]) and then click on your name.
* Go to *Setup » Settings » User » Accounts*. Then click on the button icon:user[] *My account*.

[#30]
=== Adding a user image

In order to have a user image displayed instead of the empty user button (icon:user-circle[]) in your plentymarkets back end, you have to be registered with link:https://de.gravatar.com/[gravatar.com^].

[.instruction]
Adding a user image:

. <<#20, Open your own user account>>. +
→ The tab *Master data* opens.
. Enter the email address that you use for gravatar.com in the *Email* field.
. *Save* (icon:save[role="green"]) the settings. +
→ Reload the system to display the user image.

[#40]
=== Complimentary close

Enter a text into the *Complimentary close* tab. This text is automatically added to the end of your messages and comments in the ticket system. Generally, this text consists only of a closing and your name. When sending emails from the ticket system, the complimentary close and the <<#50, signature>> will automatically be added to the end of the email.

[.instruction]
Setting up the complimentary close:

. <<#20, Open your own user account>>.
. Click on the *Complimentary close* tab.
. Enter your complimentary close.
. *Save* (icon:save[role="green"]) the settings.

[#50]
=== Signature

Enter a text into the *Signature* tab. This text is automatically added to the end of your messages and comments in the ticket system. Generally, this text consists of your contact details as well as information about where your company is registered and its registration number. Depending on your company’s legal form, the name of the company, the chief executive officer and, if applicable, the European VAT number are all mandatory inputs.
When sending emails from the ticket system, the <<#40, complimentary close>> and the signature will automatically be added to the end of the email.

[TIP]
.Template variable for the signature
====
The template variables *$Signature* and *$SignatureHTML* contain the complimentary close.
====

[.instruction]
Setting up the signature:

. <<#20, Open your own user account>>.
. Click on the *Signature* tab.
. Enter your signature.
. *Save* (icon:save[role="green"]) the settings.

[WARNING]
.Mandatory entries in emails
====
Since the beginning of 2007, mandatory entries for email signatures in Germany correspond to those for company business letters. Non-compliance can result in a fine or in a costly warning being issued by a competitor. +
Read up on the legal regulations for signatures in your own country or contact a legal adviser for such information.
====

[#60]
=== Personal settings

Use the *Personal settings* tab to change the settings of whichever user is currently logged into the system. Therefore, you can only see this tab in your own user account. The tab is divided into 3 tabs with settings that only apply to you personally. These tabs are *General*, *Shortcuts* and *Favourites*.

[#70]
==== General

Tabs are marked with a red flag if you made changes, but did not save these changes.
If you close a tab without having saved the changes, a window will appear that you have to edit before being able to continue working with your system.

* Click on *Close* to close the tab without saving the changes.
* Click on *Cancel* to save the settings or to make further changes.

If you do not want to have such warning messages displayed for your user account, deactivate this function in the *General* tab of your own personal settings.
You can also reset the user-specific settings here.

[.instruction]
Carrying out general settings:

. <<#20, Open your own user account>>.
. Click on the tab *Personal settings » General*.
. Carry out the settings. Note <<tabelle-allgemein>>.
. *Save* (icon:save[role="green"]) the settings.

[[tabelle-allgemein]]
.General settings
[cols="1,3"]
|====
|Button |Explanation

| *Reset messages*
|Users can deactivate certain messages, e.g. the message that is displayed when plentymarkets needs to be reloaded in order for updates to go into effect. This setting is saved for each individual user. Click on this button again to reset all of the relevant settings for the user. For example, all of the messages that were deactivated will be displayed again.

| *Reset all*
|Resets all of the user-specific settings, e.g. the messages described above, the content and column widths in tables, any favourites, etc.

| *Warn if tabs are open and the window is to be closed*
|Activated = A warning will be displayed if you try to close a window while tabs are still open. +
Deactivated = The window will be closed without warning.
|====

[#80]
==== Shortcuts

Default shortcuts are saved in this tab. Shortcuts are used for many functions that are carried out on a regular basis. You can use shortcuts to open important menus in plentymarkets or to switch between tabs and tab levels. For example, the shortcut *Alt + I* opens the item overview. *Alt + W* is used to close the tab again.

[IMPORTANT]
.Some shortcut combinations are not possible
====
Do not use any shortcut that is specific to an operating system. Shortcuts differ from one operating system to the next. For example: the *F* keys. +
The combination *cmd / Ctrl + W* is reserved for the browser and is therefore not possible.
====

[.instruction]
Setting up shortcuts:

. <<#20, Open your own user account>>.
. Click on the tab *Personal settings » Shortcuts*.
. Set the shortcuts. Note <<tabelle-shortcuts>>.
. *Save* (icon:save[role="green"]) the settings.

[[tabelle-shortcuts]]
.Shortcuts
[cols="1,2"]
|====
|Shortcut |Explanation

2+^| *Global shortcuts*

| *Alt + W*
|Closes the current tab.

| *Shift + Alt + DOWN (arrow down)*
|Moves down one tab level.

| *Shift + Alt + UP (arrow up)*
|Moves up one tab level.

| *Shift + Alt + RIGHT (arrow right)*
|Moves one tab to the right.

| *Shift + Alt + LEFT (arrow left)*
|Moves one tab to the left.

| *Alt + R*
|Reloads the current tab.

| *Alt + ESC*
|Logs out the user account and locks the back end.

2+^| *Open areas*

| *Alt + I*
|Opens the menu *Item » Edit item*.

| *Alt + O*
|Opens the menu *Orders » Edit orders*.

| *Alt + Y*
|Opens the menu *Item » Category*.

| *Alt + C*
|Opens the menu *CRM » Contacts*.

| *Alt + T*
|Opens the menu *CRM » Ticket system*.

| *Alt + N*
|Opens the area *New contact* within the menu *CRM » Contacts*.

| *Alt + M*
|Opens the menu *CRM » Quick search*.

| *Alt + S*
|Opens the *online shop*.

| *Alt + E*
|Opens the online shop with the inline editing function.

2+^| *Edit order*

| *Shift + Alt + N*
|Opens the customer notes in an order; available in all tabs of the order.

| *Shift + Alt + A*
|Opens the order notes in an order; available in all tabs of the order.
|====

[NOTE]
.Restoring the default shortcuts
====
Click on *Reset shortcuts* to reset the shortcuts to their default settings.
====

[#90]
==== Favourites

If you use some menus very frequently, you may want to save them to a list of favourites. This allows you to access the menus quickly. Click on icon:ellipsis-v[] in the top right of the plentymarkets back end to display your favourites.

Open up the *Favourites* tab within the personal settings of your user account to see all of the menu paths that were saved as favourites. Favourites can also be deleted in this menu. Use the *Up* and *Down* arrows to sort your favourites. The tab is only visible for your own user account.

[.instruction]
Adding a menu to favourites:

. Open the menu that you want to add to as favourite.
. Click in the tab of the menu on icon:ellipsis-v[] and select icon:star-o[] *Add link to favourites*. +
→ *_Note:_* Favourites are only visible in this menu once you have saved at least one favourite.

[.instruction]
Deleting a menu from favourites:

. Click on icon:ellipsis-v[] in the top right of the plentymarkets back end. +
→ The list shows the favourites you saved. +
. Click on *x* next to the menu path to remove the menu from the favourites. +
→ icon:map-signs[] *_Or:_* Click on *Delete all favourites* and confirm the security question with *Delete* to delete all favourites saved in your system.

[#140]
== Adding further menus with plugins

include::partial$backend-plugin-sets-en_gb.adoc[]

Refer to the xref:plugins:plugins.adoc#[Plugins] chapter for further information about setting up plugins and plugin sets.

[#110]
== Personalising the dashboard

The dashboard is displayed when you log into plentymarkets.
It shows you helpful statistics, diagrams and notes at a glance.

Admin users can customise the dashboard as needed.
In other words, they can decide which elements, statistics and notes should be displayed on the dashboard.

[TIP]
.Practical examples
====
You can decide which information should be displayed on the dashboard.
For example, you can add a:

* xref:business-decisions:myview-dashboard.adoc#700[diagram] to see the latest statistics and key figures for your company.
* xref:welcome:customise-system.adoc#190[task widget] to keep track of your current projects.
* xref:business-decisions:myview-dashboard.adoc#1100[forum announcement widget] to see important messages from the forum.
====

[#190]
== Practical example: tracking tasks

You can use the task widget to keep track of your company's work processes.
Simply assign tasks to individual employees and then track the progress of each task.
This way you can always keep an eye on current projects.

[TIP]
.Practical example: monthly newsletter
====
Imagine your company sends a monthly newsletter to inform customers of seasonal sales.
The marketing department is responsible for writing the texts, creating the graphics and sending the email.

* Create a newsletter task and assign it to your marketing department.
* Whenever a step is completed, the marketing team updates the progress.
* Since the task widget is on the dashboard, all of the participants can track the progress any time.
====

[#200]
[.collapseBox]
.*Necessary user rights*
--

Users of the type *Back end* can only access limited areas and menus in the plentymarkets back end. Thus, their access to the system is limited. If users of this type should be able to see the *plentymarkets logo (Start) » Tasks* menu, a user of the type *Admin* has to assign the right listed in the following for users of the type *Back end*.

[.instruction]
Setting the visibility for back end users:

. Go to *Setup » Settings » User » Rights » User*.
. Use the search function (icon:search[role="blue"]) and open the account that should be edited.
. Expand the *Authorisations: Start* menu.
. Select the setting *Tasks*.
. *Save* (icon:save[role="green"]) the settings.

--

[#240]
=== Adding the task widget to the dashboard

If the task widget isn’t already on the dashboard, then an admin will need to add it.

[.instruction]
Adding the widget:

. Go to *plentymarkets logo (Start) » Dashboard*.
. Click on *Edit view* (terra:design_inline_edit[]).
. Drag-and-drop the *My tasks* element from the settings menu on the dashboard.
. *Save* (terra:save[]) the settings.

Further information about xref:business-decisions:myview-dashboard.adoc#400[customising the dashboard].

[#210]
=== Creating a new task

Imagine your company sends a monthly newsletter to inform customers of seasonal sales.
You can create a newsletter task and assign it to your marketing department.

[.instruction]
Creating a task:

. Go to *plentymarkets logo (Start) » Dashboard » Element: My tasks*.
. Click on *New task* (icon:plus[role="darkGrey"]). +
→ A pop-up window will open.
. Enter information about the task. Refer to the table.
. Click on *Save*. +
→ A task ID is automatically assigned by the system and cannot be changed.

[cols="1,3a"]
|===
|Setting |Explanation

| *Title*
|Enter a title for the task, e.g. “Newsletter”. 

| *Description*
|Enter a description of the task and format the text.
For example, you could write a list of the individual steps, such as “texts”, “graphics” and “send email”.

| *Progress*
|Move the slider to specify the task’s progress as a percentage.

*_Note_*: This is the task’s progress when it is first created.
The progress can be updated as the task moves forward.

| *Priority*
|Select the task’s priority.
The priorities range from one grey star (lowest priority) to two yellow stars (highest priority).

| *Flag*
|Select a flag for the task.
The flag helps you find tasks again in the future.

| *Owner*
|Who is responsible for this task?
Select the task’s owner, e.g. your marketing manager.
|===

[#230]
=== Tracking and updating your own tasks

The task widget displays your own tasks on the dashboard when you log into plentymarkets.
You can edit your tasks further any time.
For example, you can update the progress or add information to the description.

[.instruction]
Updating a task:

. Go to *plentymarkets logo (Start) » Dashboard » Element: My tasks*. +
→ Your incomplete tasks are displayed by default.
. Click on icon:ellipsis-v[role="darkGrey"] and decide how the task should be changed.
* icon:pencil[role="darkGrey"] *Update task* = The same pop-up window opens that you already saw while creating the task.
Here you can edit the task further.
* material:delete[role="darkGrey"] *Delete* = You will need to confirm your decision to delete the task.
* material:task_alt[role="darkGrey"] *Mark task as completed* = The progress will be set to 100% and the task will be moved to the *Completed* area.
* material:task_alt[role="darkGrey"] *Mark task as incomplete* = This option is only visible for completed tasks.
The progress will be set to 0% and the task will be moved to the *Incomplete* area.

[#220]
=== Tracking and updating company-wide tasks

It’s not only possible to manage your own tasks, but also to keep track of your employee’s tasks.

[.instruction]
Tracking company-wide tasks:

. Go to *plentymarkets Logo (Start) » Tasks*. +
→ Your incomplete tasks are displayed by default.
. Click on *Reset* (icon:undo[role="orange"]) and select the necessary filters.
Refer to the table.
. Click on *Search* (icon:search[role="blue"]). +
→ The tasks that correspond to the search criteria entered are shown.

[cols="1,3a"]
|===
|Filter |Explanation

| *Title/Description*
|Filters for tasks that have a specific keyword in their title or description.
Enter the keyword into the text field.

*_Note_*: Enter at least 4 characters.
This is a full text search filter.

| *ID*
|Filters for the task with a specific ID.
Enter the ID into the text field.

*_Note_*: The system automatically assigns consecutive task IDs.
This ID cannot be changed.

| *Ticket ID*
|Filters for the tasks that belong to a specific ticket.
Enter the ticket ID.
xref:crm:using-the-ticket-system.adoc#4000[Further information].

| *Progress*
|Filters for the tasks that have a specific progress.
Select an operator and the progress from the drop-down lists.

| *Priority*
|Filters for the tasks that have a specific priority.
Select an operator and the priority from the drop-down lists.

| *Date of creation*
|Filters for the tasks that were created at a specific time.
Select an operator from the drop-down list and a date from the calendar (icon:calendar[]).

| *Flag*
|Filters for the tasks that have a specific flag.
Select the flag from the drop-down list.

| *Owner*
|Filters for the tasks that are assigned to a specific person.
Select the owner from the drop-down list.
|===

[#245]
=== Creating tasks in the ticket system

Not only can tasks be created in the widget, but they can also be created in the xref:crm:using-the-ticket-system.adoc#4000[ticket system].
For example, you can directly create any tasks that result from a telephone inquiry.

[.instruction]
Creating a task in the ticket system:

. Go to *CRM » Ticket system » [Open ticket] » Tab: Tasks*.
. Click on icon:plus[role="green"] *New task*.
. Carry out the settings. Refer to the explanations in the chapter xref:welcome:customise-system.adoc#210[Creating a new task].
. *Save* (terra:save[role="green"]) the settings. +
→ The task is linked to the ticket.
This link is also visible in the overview under *plentymarkets logo (Start) » Tasks*.

[#150]
== Configuring table columns

In some meus, the overview is customisable.
That means, you can decide:

* which columns should be displayed.
* which order the columns should be displayed in.
* whether the results should be displayed in ascending or descending order.

include::item:page$item-search.adoc[tag=configure-columns-overview]

[#183]
== Activating full screen mode

If you want to use more of your screen space for back end views, you can use full screen mode. Activating full screen mode hides the menu bar. You can show the menu bar dynamically by hover the mouse over the top edge of your browser tab.

To activate or deactivate full screen mode, click on icon:ellipsis-v[] in the upper right corner of the plentymarkets back end, then click on either *Fullscreen on* material:fullscreen[] or *Fullscreen off* material:fullscreen-exit[].

[#185]
== Choosing a dark or light theme

There are various themes and options to change the design of your back end. You can change the following elements:

* Menu bar colour
* Size of various elements
* Button colour

To change the design of your back end, carry out the following steps:

[.instruction]
Changing the design:

. Hover over the user icon (icon:user-circle[]).
. Click on *Themes*. +
→ The *Themes* window opens.
. Select the desired design.

[#180]
== Prohibiting specific editors

Some menus have a drop-down list from which users can select their preferred editor.
By default, the editors *Editor*, *Syntax editor* and *Text field* are available for selection.
You can deactivate individual editors as needed, e.g. if you want to make sure that your employees only use the syntax editor.

[.instruction]
Deactivating editors:

. Go to *Setup » Settings » Editors*. +
→ The *Areas* tab opens.
. Remove the check mark next to the editors that should not be displayed in the drop-down list of the corresponding area.
. *Save* (icon:save[role="green"]) the settings.

[discrete]
=== Changing the CSS of the editor

The editor uses the *CSSContent* by default. If a background image is used there and this is bothersome or not desired, you can individually edit the CSS in the menu *Setup » Settings » Editors » Tab: CSS*. Alternatively, you can use the *Standard* CSS with a white background. You can also create your own *customised* CSS and specify additional formatting, e.g. fonts.

To change the CSS for the editor, go to *Setup » Settings » Editors » Tab: CSS*.

[.instruction]
Changing the CSS of the editor:

. Go to *Setup » Settings » Editors*.
. Click on the *CSS* tab.
. Select the desired CSS. Pay attention to the information given in <<table-css-editors>>.
. *Save* (icon:save[role="green"]) the settings.

[[table-css-editors]]
.Available CSS
[cols="1,3"]
|====
|Setting |Explanation

| *As in the online store (CSSContent)*
|The store CSS will be loaded in the editor.

| *Standard*
|A simple standard CSS will be loaded in the editor. The background colour is white.

| *User-defined*
|The simple standard CSS will be displayed in an editing window and can be customised with the syntax editor. +
*_Note:_* Click on *Reset* to reset the CSS to the standard CSS.
|====

[#250]
== Calendar function

The calendar in the *plentymarkets logo (Start) » Calendar* menu of your plentymarkets system allows you to make appointments and plan deadlines. This helps you organise your own and your employees' time and improve internal processes.

The calendar shows your appointments. In addition, it shows the appointments of any users whose calenders have been made visible to you and which you have activated in the *filter*.

You can choose to show the day, week or month. Click on the button *Today* to change to the view of the current day.

The filter shows a list of all users for which you at least have read permissions. Place a check mark to show a user's appointments in your calendar. You can show the calendars of multiple users at the same time.

[discrete]
[#260]
=== Assigning user rights for back end users

Users of the type *Back end* can only access limited areas and menus in the plentymarkets back end. Thus, their access to the system is limited. If users of this type should be able to see the *plentymarkets logo (Start) » Calendar* menu, a user of the type *Admin* has to assign the right listed in the following for users of the type *Back end*.

[.instruction]
Setting the visibility for back end users:

. Go to *Setup » Settings » User » Rights » User*.
. Use the search function (icon:search[role="blue"]) and open the account that should be edited.
. Expand the *Authorisations: Start* menu.
. Select the setting *Calendar*.
. *Save* (icon:save[role="green"]) the settings.

[discrete]
[#270]
=== Setting the back end user as owner

For persons with *Back end* access, the calendar has to be activated as described in the following. It is not possible to activate the calendar for persons with *REST API* access.

The right assigned to a user can be deactivated in the *Owner* tab at any time.

[.instruction]
Setting the back end user as owner:

. Go to *Setup » Settings » User » Accounts*.
. Open the user account with the *Back end* access.
. Click on the *Owner* tab.
. Activate the option *Calendar*.
. *Save* (icon:save[role="green"]) the settings. +
→ The new tab *Calendar* is visible and can be set up as described in the next chapter.

[discrete]
[#280]
=== Carrying out basic calendar settings and setting access rights for users

Proceed as described below to carry out basic calendar settings such as saving the password and to set the access rights for users. You can select between the settings *No access*, *Read* and *Read & write*.

[.instruction]
Carrying out basic calendar settings and setting access rights for users:

. Go to *Setup » Settings » User » Accounts*.
. Open the user account.
. Click on the *Calendar* tab.
. Carry out the settings. Note <<#table-calendar-basic-settings>>.
. *Save* (icon:save[role="green"]) the settings.

[[table-calendar-basic-settings]]
.Carrying out basic calendar settings
[cols="1,3"]
|====
|Setting |Explanation

| *Server address*; +
*Server path*; +
*Port*
|Automatically saved by the system. +
The server address and server path are required for configuring an <<#320, external calendar tool>> such as Google Calendar.

| *New password*
|A password must be entered during setup of the calendar account. This password is required for the <<#320, external calendar tools>>. The password can be changed at any time. +
*_Important:_* After saving, the password is no longer shown and cannot be retrieved. +
If you use an external calendar tool, you might need to re-enter the password when the password is changed.

| *Repeat password*
|Enter the password again to confirm it.

| *Description*
|The description is shown within the information and settings for the calendar.

| *Right*
|Select which users can access this owner's calendar. Also select the type of access right assigned to these users. Users have to be assigned at least read permission in order to see the calendar. +
*No access* = The user has neither read nor write permissions for this owner's calendar. +
*Read* = The user can view the calendar. +
*Write* = The user can edit and delete appointments in the calendar.
|====

[discrete]
[#290]
=== Creating an appointment

Proceed as described below to create an appointment. Depending on your access rights that are set according to <<#table-calendar-basic-settings>>, you can also create appointments for other users. You can only create appointments for users for which you have write permissions. You cannot select users for which you do not have write permissions.

[.instruction]
Creating an appointment:

. Go to *plentymarkets logo (Start) » Calendar*. +
→ *_Tip:_* To do so, point your cursor at the plentymarkets logo at the top left of the screen.
. Select the point in time of the appointment by clicking the time in the calendar. +
→ *_Tip:_* Select the time period for the appointment by clicking the start time and move the cursor to the end time of the appointment.
. Carry out the settings in the *Appointment details* area. Note <<#table-create-appointment>>.
. *Save* (icon:save[role="green"]) the settings.

[[table-create-appointment]]
.Creating an appointment
[cols="1,3"]
|====
|Setting |Explanation

| *Title*
|Is shown in the calendar overview.

| *All day*
|Specifies that the appointment lasts the entire day. In the daily and weekly view of the calendar, all appointments are shown in the top row. This helps to ensure that the calendar does not become cluttered.

| *From / To*
|The date and time are pre-selected but can be edited.

| *Type*
|Select the type of appointment from the drop-down list.

| *Calendar*
|Select the owner you want to create the appointment for.

| *Description*
|Enter the description, e.g. further information about the appointment. This description is shown in the appointment details and visible to all users with access rights to the calendar.
|====

[discrete]
[#300]
=== Editing an appointment

Click on an appointment to open the appointment details and edit the details.

[.instruction]
Editing an appointment:

. Go to *plentymarkets logo (Start) » Calendar*.
. Click on the appointment that you would like to edit. +
→ The window *Appointment details* opens.
. Carry out the changes. Note <<#table-create-appointment>>.
. *Save* (icon:save[role="green"]) the settings.

[discrete]
[#310]
=== Deleting an appointment

Delete appointments when they have been created by mistake or when they have become obsolete.

[.instruction]
Deleting an appointment:

. Go to *plentymarkets logo (Start) » Calendar*.
. Click on the appointment that you would like to delete. +
→ The window *Appointment details* opens.
. Click on *Delete* (icon:minus-square[role="red"]). +
→ The appointment is deleted and removed from the calendar overview.

[discrete]
[#320]
=== Synchronising the calendar with external calendar tools

You can use a link:https://en.wikipedia.org/wiki/CalDAV[CalDAV^] interface to synchronise your calendar with external calendar tools. For example, you can synchronise your calendar with tools such as Mac Calendar or iPad Calendar.

The option *Calendar* has to be activated in the *Owner* tab of the user account as described in the <<#270, Setting the back end user as owner>> chapter. You need to know the settings for the user in order to carry out the configuration. The settings are saved in the user's *Calendar* tab.

Refer to the external tool's documentation to find out how to synchronise your plentymarkets calendar with the external calendar tool.
