= Automating processes
:lang: en
include::{includedir}/_header.adoc[]
:position: 150
:icons: font
:docinfodir: /workspace/manual-adoc
:docinfo1:
:url: welcome/quick-start/quick-start-automating-processes
:id: MCO2VYQ
:author: team-mobile, team-order-payment

IMPORTANT: Have you already added plugins to your system? Not yet? Return to <<welcome/quick-start/quick-start-adding-plugins-to-the-system#, Adding plugins to the system>>.

On this page, we explain the basic settings that you should carry out in your plentymarkets system in order to automate processes. We recommend carrying out these settings before starting productive work with your system. Your plentymarkets system then completes these automatic processes in the background. +
In general, plentymarkets offers you 4 different methods of automating your work flows:

* Automatically sending email templates
* Event procedures
* Procedure manager
* Processes

[#10]
== Automatically sending email templates

In the step <<welcome/quick-start/quick-start-initial-settings#, initial settings>>, you learned how to set up the email templates for automatically sending email templates. +
Now, use the menu *Setup » Client » [Select client] » Email » Automatic* to select which email template should be sent in specific situations. Some options, such as sending the email template *webshop: Incoming order* when receiving a new order via your webshop are already preset in this menu. Check these settings and adjust them where necessary. To do so, proceed as described below.

[.instruction]
Setting up automatic emails:

. Go to *Setup » Client » [Select client] » Email » Automatic*.
. From the drop-down list next to the respective event, select an email template that should be sent automatically as soon as the event takes place.
. Select the option *do not send* if _no_ email template should be sent.
. *Save* (icon:save[role="green"]) the settings.

[WARNING]
.Have you set up the email template correctly?
====
In the *Setup » Client » [Select client] » Email » Automatic* menu, you should only select email templates that you have edited and completed with your individual data.
====

[#20]
== Setting up event procedures

Your daily business as a seller involves plenty of routine tasks. Order processing in particular is a complex process that requires you to act systematically. plentymarkets offers you the so-called event procedures that allow you to automate such routine tasks. +

The principle behind the event procedures consists of 3 steps. First, you select an event that triggers the procedure. You can use several filter settings to set up specific conditions for this event. The third step consists of selecting concrete procedures that should be carried out by the system as soon as the event takes place. The system will automatically carry out the defined procedure whenever this event occurs in the future. +

The following 2 event procedures have proven to be of value in the daily businesses of many plentymarkets sellers. We recommend that you automate sending your invoices in your plentymarkets system according to the first event procedure.

The first event procedure automatically generates the invoice document as soon as outgoing items have been booked for the corresponding order. Set up the event procedure according to the information provided in <<table-event-procedure-quick-start-generating-an-invoice>>.

[IMPORTANT]
.Setting up the document template
====
To make sure that the event procedure described below functions correctly, you need to finish setting up the template for the *invoice* document beforehand. An instruction is provided on the <<orders/order-documents#, order documents>> page of the manual.
====

[.collapseBox]
.Setting up an event procedure
--
. Go to *Setup » Orders » Events*.
. Click on *Add event procedure* at the bottom left (icon:plus-square[role="green"]). +
→ The *Create new event procedure* window opens.
. Enter a distinct name for the event procedure.
. Select the *event* according to <<table-event-procedure-quick-start-generating-an-invoice>>.
. *Save* (icon:save[role="green"]) the settings.
. Carry out the settings according to the information provided in <<table-event-procedure-quick-start-generating-an-invoice>>.
. Select the option *Active*.
. *Save* (icon:save[role="green"]) the settings.
--

[[table-event-procedure-quick-start-generating-an-invoice]]
.Setting up the event procedure “Generating an invoice”
[cols="1,3,3"]
|====
|Setting |Option |Selection

| *Event*
| *Order change > Outgoing items booked*
|

| *Filter 1*
| *Order > Order type*
| *Order*

| *Procedure 1*
| *Documents > Generate invoice*
|If needed, enter a *comment* that will be displayed on the generated invoice.
|====

After generating the invoice, you can automatically send it to your customers as an email attachment using another event procedure. Set up this second event procedure according to the information provided in <<table-event-procedure-quick-start-send-invoice>>.

[.collapseBox]
.Setting up an event procedure
--
. Go to *Setup » Orders » Events*.
. Click on *Add event procedure* at the bottom left (icon:plus-square[role="green"]). +
→ The *Create new event procedure* window opens.
. Enter a distinct name for the event procedure.
. Select the *event* according to <<table-event-procedure-quick-start-send-invoice>>.
. *Save* (icon:save[role="green"]) the settings.
. Carry out the settings according to <<table-event-procedure-quick-start-send-invoice>>.
. Select the option *Active*.
. *Save* (icon:save[role="green"]) the settings.
--

[[table-event-procedure-quick-start-send-invoice]]
.Setting up the event procedure “Sending invoices to customers”
[cols="1,3,3"]
|====
|Setting |Option |Selection

| *Event*
| *Documents > Invoice generated*
|

| *Filter 1*
| *Order > Order type*
| *Order*

| *Procedure 1*
| *Customer > Send email*
|Use the plus icon to select the email template *Order: Invoice PDF attachment* for the *Customer*. This way, the *invoice* document is sent as an email attachment in PDF format.
|====

Event procedures offer numerous further possibilities of automating your plentymarkets system. To learn more about the function of event procedures and gain insight into more practical examples, pay attention to the links at the end of this page.

[#30]
== Using the procedure manager

Similar to the event procedures, the procedure manager can be used to carry out automatic procedures as soon as selected events take place. However, the procedure manager offers you the additional possibility to carry out the procedures automatically at a fixed point in time each day. Thus, the procedure manager is ideal to manage processes that should take place at regular intervals. +
Pay attention to the links at the end of this page in order to obtain more information about setting up and using the procedure manager.

[#40]
== Using processes

Processes are yet another tool that you can use to automate processes in your plentymarkets system. Setting up processes is recommended for example when order documents should not only be generated, but also printed automatically. You can only use processes if you have installed the plentyBase tool. Using processes is aimed at advanced plentymarkets users. Processes are therefore not further explained in the quick start. +
Pay attention to the links at the end of this page in order to obtain more information about setting up processes.

[#50]
== Check list

Work through the check list in order to review your settings for automating processes.

[%interactive]
* [ ] Did you select which <<#10, email templates>> should be sent automatically?
* [ ] Did you automate generating and sending invoices with the help of <<#20, event procedures>>?

[#60]
== More about automation

* <<crm/sending-emails#, Emails>>
* <<automation/event-procedures#, Event procedures>>
* <<automation/procedure-manager#, Procedure manager>>
* <<automation/best-practices-automation#, Best Practices: Procedure manager and event procedures>>
* <<automation/processes/setting-up-processes#, Setting up processes>>

TIP: Continue to the <<welcome/quick-start/quick-start-guide-final-steps#, final steps>>
