= Carrying out initial settings
:description: In this part of the quick start, you learn which initial settings you have to carry out.
:id: U4A9SAW
:author: team-crm

IMPORTANT: Have you already allowed pop-ups, added a bookmark for your back end login and checked the system requirements? Not yet? Return to xref:welcome:quick-start.adoc#[Quick start].

In this part of the quick start, you find explanations about general settings such as saving company data and bank details as well as explanations about setting up the email despatch and email templates. Furthermore, we explain on this page how you order a domain and an SSL certificate for your online shop.

You can carry out some of the above mentioned settings with our virtual assistants. They will help you set up your system step by step.

[#100]
== Adjusting the user account and saving the company, contact and bank details

Go to *Setup » Assistants* and open the *Basic setup* area. Complete the *Basics* assistant to carry out the following settings:

* Customise your own user account
* Save company details
* Save contact details
* Save bank details

[IMPORTANT]
.Changing contract information
====
Making changes to this master data will _not_ have any effect on the customer information that is saved in your contract with plentymarkets, e.g. for billing purposes. Contract information has to be changed in the *plentymarkets logo (Start) » My account* menu in the *Contracts* area.
====

Your bank details can be replaced with the corresponding text via variables in email templates. This means that plentymarkets replaces the variables with the corresponding content in the emails. The variable `Account holder (master data)` will be replaced with the name of the account holder and `Bank name (master data)` inserts the name of the bank. `IBAN (master data)` will be replaced with the IBAN and `BIC (master data)` with the BIC. Go to the xref:crm:emailbuilder.adoc#[EmailBuilder] to create email templates quickly and easily with drag-and-drop. 

For further information about variables, refer to the chapters xref:welcome:quick-start-initial-settings.adoc#600[Example: Customising the email template] and xref:welcome:quick-start-initial-settings.adoc#700[Inserting variables in the template] further down on this page.

[#150]
== Setting up locations

Go to *Setup » Assistants* and open the *Basic setup* area. Complete the *Locations* assistant to carry out the following settings:

* Create a location and save the VAT number
* Determine the gross or net order sums on your invoices when shipped to EU member states and non-EU states
* Save the rounding behaviour of the order sums
* Save the VAT rates for the location

[TIP]
.Changing the default location
====
You can change the default location in the *Setup » Client » [Select client] » Settings* menu. The default location will be used in other areas, e.g. during the order process in the online shop. As such, it affects how VAT is displayed. +
*_Note:_* Whenever you carry out changes in this menu, other users are logged out automatically and have to log in again. This ensures that the changes also apply to the other user profiles.

For further information about the settings in this menu, refer to the xref:online-store:setting-up-clients.adoc#[Setting up clients] page.

Note also that you have to activate the xref:fulfilment:preparing-the-shipment.adoc#200[country of delivery] for the location in the *Setup » Orders » Shipping » Settings » Tab: Countries of delivery* menu so that it is shown as new default location in the *Setup » Client » [Select client] » Settings* menu.
====

[#250]
== Creating a customer class

Use customer classes to categorise your customer base according to specific criteria. You can determine the minimum order quantities, grant discounts and decide whether the prices in your online shop are displayed as gross or net prices.

For the beginning, we recommend creating 2 customer classes:

* B2C for your end customers
* B2B for sellers

You may need the customer classes for further settings that you carry out in your plentymarkets system such as saving sales prices.

[.instruction]
Creating a customer class:

. Go to *Setup » CRM » Customer classes*.
. Click on the *New customer class* tab.
. Carry out the desired settings. Note <<#table-quick-start-create-customer-class>>.
. *Save* (icon:save[role="green"]) the settings.

[[table-quick-start-create-customer-class]]
.Creating a customer class
[cols="1,3"]
|====
|Setting |Explanation

| *Name*
|Enter the name for the customer class, e.g. standard customer or B2C.

| *Discount type*
|If required, select a discount type. For further information about the discount types, refer to the xref:crm:preparatory-settings.adoc#use-discount-system[Using the discount system] chapter on the xref:crm:preparatory-settings.adoc#[Carrying out the preparatory settings] page.

| *Allowed payment methods*
|Select which methods of payment are permitted for the customer class. These methods of payment will later be available in your online shop. By default, all available methods of payment are allowed.

| *Display of the prices in the online store*
|Select whether the prices are displayed as gross or net prices in the online shop.

|====

For more information about customer classes, head over to the to the xref:crm:preparatory-settings.adoc#create-customer-class[Carrying out the preparatory settings] page.

[#300]
== Setting up the email despatch

Go to *Setup » Assistants* and open the *Basic setup* area. Complete the *Email accounts* assistant to carry out the following settings:

* To authorise plentymarkets to send emails via your email account, you have to enter the login details of your email program in plentymarkets. Note that it might be necessary to obtain an approval from your email provider so that plentymarkets is allowed to send emails.
* Activating the test mode
* Saving the signature for your outgoing emails
* Activating the information service to receive a blind copy of all outgoing emails
* Linking email template with certain events to ensure that these templates will be sent to your customers once the event occurs.

[TIP]
.Test mode sends emails only to your email address
====
There is a test mode which is activated by default. When the test mode is activated, emails are only sent to the email address you saved. This allows you to check all settings of the email despatch and the content before you switch to the live mode.
====

[#500]
== Setting up email templates

plentymarkets generates all emails based on templates. For the beginning, we recommend setting up the email templates listed in <<#table-email-templates>>. Email templates are created in the *CRM » EmailBuilder* menu.

You can adapt all email templates to your individual needs. Go to the chapter xref:welcome:quick-start-initial-settings.adoc#600[Example: Customising the email template] further down on this page of the manual to find an example about how to customise the email template *Shop: Order confirmation*.

[[table-email-templates]]
.Email templates that are already set up in your system
[cols="1,3"]
|====
|Email template |Explanation

| *Order: Invoice*
|Sends the invoice to the customer as an attachment. +
*_Important:_* An invoice template for the location *Germany* is already pre-configured. You can adapt the template to your individual needs. To do so, go to *Setup » Client » [Select client] » Locations » [Select location] » Documents » Invoice*. If an invoice already exists for the order and you set up an event procedure, the invoice will be sent to your customer automatically because the PDF attachment *Invoice* is selected by default in the template *Order: Invoice as PDF attachment*. +
 For further information refer to the quick start page xref:welcome:quick-start-automating-processes.adoc#[Automating processes].

| *Order: Shipping confirmation*
|Is sent when the items are shipped. +
*_Tip:_* Create an xref:welcome:quick-start-automating-processes.adoc#[event procedure] with the event *Package number* and add filters and procedures so that the package number that is saved in the order will be displayed via the variable `Tracking URL`. For further information refer to the quick start page xref:welcome:quick-start-automating-processes.adoc#[Automating processes].

| *Shop: Order confirmation*
|Informs the customer that their order has been received. +
*_Important:_* For legal reasons, you should insert the cancellation rights as well as the terms and conditions in this email template. Also, pay close attention to any wording in the email template that relates to the contract between you and your customer. It is therefore recommended that you have your texts checked by a specialist lawyer. +
Save the texts for the cancellation rights and the terms and conditions in the *Setup » Client » [Select client] » Online store » Legal* menu. The variables `Cancellation rights in HTML format` and `General terms and conditions in HTML format` are automatically replaced with the cancellation rights and the terms and conditions in the email.
|====

[TIP]
====
There are many other xref:crm:emailbuilder.adoc#[default templates] that are already available in your plentymarkets system. Adjust these email templates, if required, and link them with an event in the *Setup » Assistants » Basic setup* menu in the *Automatic despatch* step of the *Email accounts* assistant or set up an event procedure. For further information refer to the quick start page xref:welcome:quick-start-automating-processes.adoc#[Automating processes].
====

[#550]
=== Saving legal information

It is important that you save the legal information for your online shop in advance. Legal information include terms and conditions, cancellation rights, privacy policy, legal disclosure and cancellation form. Insert variables in the email template. The variables will be replaced with the text in the email templates.

We recommend having the texts checked by a specialist lawyer before you use them.

[.instruction]
Saving legal information:

. Go to *Setup » Client » [Select client] » Online store » Legal*.
. Expand the language *English* (icon:plus-square-o[]).
. Insert the texts in the corresponding tabs *Terms and conditions*, *Cancellation right*, *Privacy policy*, *Legal disclosure* and *Cancellation form* in the *HTML* tab. +
*_Tip:_* Have the texts about the legal information checked by a specialist lawyer.
. *Save* (icon:save[role="green"]) the settings.

[#600]
=== Example: Customising the email template

In this chapter, we explain how you customise an email template based on the email template *Shop: Order confirmation*.

[.instruction]
Customising the email template:

. Go to *CRM » EmailBuilder*.
. Expand the folder (material:chevron_right[]) that contains the template you want to edit.
. Click on the template.
. Click on material:edit[] (*Edit*).
. If required, change the text.
. For example, insert the variables `Cancellation rights in HTML format` and `General terms and conditions in HTML format` to ensure that the texts for the general terms and conditions and the cancellation right are automatically replaced with the correct content in the email template that you send. +
*_Note 1:_* You have saved these texts in the system in advance as described in the xref:welcome:quick-start-initial-settings.adoc#550[Saving legal information] chapter. +
*_Note 2:_* You can search for the available variables on the left side of the opened template.
. Further information about the variables for legal information can be found in <<#table-emailbuilder-variables-legal>> at the end of this chapter.
. Replace the sample contact data at the end of the template with your own contact data. +
*_Tip:_* You can use the variable `Signature in HTML format` for this.
. *Save* (material:save[]) the settings.

[[table-emailbuilder-variables-legal]]
.EmailBuilder variables for legal information
[cols="1,3,3"]
|====
|Legal information |Variable |Where do I save the text?

| *Terms and conditions*
| `General terms and conditions in HTML format`
|Go to *Setup » Client » [Select client] » Online store » Legal » [Expand language]*. Click on the *Terms and conditions* tab and save the text in the *HTML* tab.

| *Cancellation rights*
| `Cancellation rights in HTML format`
|Go to *Setup » Client » [Select client] » Online store » Legal » [Expand language]*. Click on the *Cancellation rights* tab and save the text in the *HTML* tab.

| *Privacy policy*
| `Privacy policy in HTML format`
|Go to *Setup » Client » [Select client] » Online store » Legal » [Expand language]*. Click on the *Privacy policy* tab and save the text in the *HTML* tab.

| *Legal disclosure*
| `Legal disclosure in HTML format`
|Go to *Setup » Client » [Select client] » Online store » Legal » [Expand language]*. Click on the *Legal disclosure* tab and save the text in the *HTML* tab. 

| *Cancellation form*
| `Cancellation form in HTML format`
| Go to *Setup » Client » [Select client] » Online store » Legal » [Expand language]*. Click on the *Cancellation form* tab and save the text in the *HTML* tab.

|====

[#650]
=== Linking the order confirmation template with an event procedure

You have <<#600, adjusted>> the email template *Shop: Order confirmation* according to your needs and saved it? Great! Now set up an event procedure to ensure that the email template *Shop: Order confirmation* will be sent automatically to your customers once they place an order in your online shop.

[.instruction]
Linking the order confirmation template with an event procedure:

. Go to *Setup » Orders » Events*.
. Click on *Add event procedure*. +
→ The *Create new event procedure* window opens.
. Enter a name, e.g. `New order online shop`.
. Select the *event* according to <<#table-event-procedure-new-order-online-shop>>.
. *Save* (icon:save[role="green"]) the settings.
. Carry out the settings as listed in <<#table-event-procedure-new-order-online-shop>>.
. Select the option *Active*.
. *Save* (icon:save[role="green"]) the settings.

[[table-event-procedure-new-order-online-shop]]
.Event procedure to automatically send an order confirmation when an order has been placed in your online shop
[cols="1,3,3"]
|====
|Setting |Option |Selection

| *Event*
| *Order generation: New order*
| 

| *Filter*
| *Order > Referrer*
| *Client (store)*

| *Action*
| *Customer > Send email*
| Add the adjusted template **Shop: Order confirmation** template and select *Customer* as recipient

|====

[#700]
=== Inserting variables in the template

You can insert as many variables as you like in your email templates. When plentymarkets sends emails, it automatically replaces the variables with the corresponding content. The variable `Full name` will therefore be replaced with the first name and last name of the customer and the variable `Order ID` insert the ID of the order.

[.instruction]
Inserting variables in the template:

. Go to *CRM » EmailBuilder*.
. Open the email template into which you would like to insert the variables.
. Click on material:edit[] (*Edit*). +
→ The editor with the template opens.
. Click again on material:edit[] (*Edit*). +
→ On the left side next to the template, you can see the *Variables* area.
. In the *Search* field, enter the name of the variable or expand the different categories to search for the variables.
. By clicking on the variable, the variable is inserted in your template at the desired position.
. *Save* (material:save[]) the settings.

[TIP]
.Insert variable `URL to order confirmation`
====
All emails that will be sent to your customers should contain the variable `URL to order confirmation`. This function replaces the link to the *My account* area of your online shop. Your customers can then click on the link to update their data, see the order history, add further items to the order or track the order status.
====

[#800]
=== Attaching files to email templates

You can add 2 types of files to your email templates:

* dynamic attachments 
* static attachments

We describe the difference of these 2 attachments in the following.

Possible types of a dynamic attachment, e.g. the invoice or delivery note, are xref:orders:order-documents.adoc#100[location-based documents] in your plentymarkets system. Go to *Setup » Client » [Select client] » Locations » [Select location] » Return slip* to set up these documents.

A static attachment could be for example a product catalogue, instructions or a photo file. Go to *CMS » Documents* to upload these files.

[#900]
==== Creating and attaching dynamic attachments

The documents that you can send as dynamic attachment are automatically generated by your plentymarkets system. An example of such a document is the invoice.

It is set up in 3 steps:

1. Create a document template, e.g. in a business letter template including the logo, and save it to your computer
2. Adjust the document settings (in the following, this step is described in detail)
3. Link the document with the email template (in the following, this step is described in detail)

[.instruction]
Adjusting the document settings:

. Go to *Setup » Client » [Select client] » Locations » [Select location] » Documents*.
. Select the document that you want to edit, e.g. *Invoice*. +
*_Note:_* The document *Invoice* is preset by default. If required, adapt the invoice template.
. Click on the tab *PDF template*.
. Click on *Add template* (icon:plus-square[role="green"]).
. If required, select a *Payment method*. +
*_Note:_* The setting *Standard* is selected by default.
. Click on *Choose template* (icon:upload[role="purple"]).
. Open the PDF document template that you previously created.
. Click on *Upload template* (icon:save[role="green"]).
. Click on *Preview* (icon:eye[role="blue"]) to display a preview of the document.
. Click on *Delete* (icon:minus-square[role="red"]) to delete the document.

[.instruction]
Linking a document with the email template:

. Go to *CRM » EmailBuilder*.
. Open the email template.
. On the right side in the *Settings* area, select (material:check_box[role=skyBlue]) from the *Dynamic attachments* drop-down list the file that you want to send as attachment.
. *Save* (material:save[]) the settings. +
→ The document is attached to the email.

[#1000]
==== Creating and attaching static attachments

All of the documents that you want to attach to an email template as static attachment have to be uploaded to the system first. An example of such a document are the terms and conditions. This document is often attached with the order confirmation – given that you did _not_ directly insert the terms and conditions in the email template by using the variable `General terms and conditions in HTML format`.

It is set up in 2 steps. First, you upload the document in the *CMS » Documents* menu. Second, attach the document to an email template. To do so, proceed as described below.

[.instruction]
Uploading a document:

. Go to *CMS » Documents*.
. Click on *Browse...* in the *Upload* tab.
. Select the file that you want to upload and click on *Open*.
. Select one of the options from the *Right* drop-down list. +
*_Note:_* The right specifies whether the document should be visible to *Employees* or *Customers* only or to all visitors of your online shop (*Public*).
. If required, enter a name for the folder.
. *Save* (icon:save[role="green"]) the settings.

[.instruction]
Linking a document with an email template:

. Go to *CRM » EmailBuilder*.
. Open the email template.
. In the top right, click on material:translate[] *Language-dependent settings*.
. Select the file that you want to send as attachment for the correct language from the drop-down list *Static attachments*.
. *Save* (material:save[]) the settings. +
→ The file is attached to the email.

[#1100]
== Ordering a domain

The word "domain" refers to an Internet address in the form of a name and an extension, i.e. the top level domain, e.g. *.de*. You can freely select the name. A domain is unique, i.e. the exact same domain may never be used twice. Therefore, when registering a desired domain, e.g. with a hosting service provider, it is necessary to check whether your desired domain has already been used.

For further information, refer to the xref:business-decisions:domains.adoc#[Domains] page of the manual.

[#1200]
== Buying an SSL certificate

An SSL certificate is used to encrypt your website and provides a secure connection to your online shop. Your customers can see when you are using an SSL certificate as your website will be accessed via _https_.
It is important that the domain for which you want to order the SSL certificate is set as main domain.

For further information, refer to the xref:business-decisions:ssl-certificate.adoc#[SSL certificates] page of the manual.

[#1300]
== Check list

Work through the check list in order to review your settings for the initial settings.

[%interactive]

* [ ] Did you complete the *Basics* assistant?
* [ ] Did you complete the *Locations* assistant?
* [ ] Did you complete the *Email accounts* assistant?
* [ ] Did you insert the variable `Signature in HTML format` at the end of your email templates?
* [ ] Did you replace the sample data with your own contact data in all email templates?
* [ ] Do all email templates contain the variable `URL to order confirmation`?
* [ ] Did you order a domain for your online shop?
* [ ] Did you buy an SSL certificate?
* [ ] Did you deactivate the test mode after having tested all the settings so that the emails are from now on sent to your customers and not to your email address any longer?

[#1400]
== More about initial settings

* xref:crm:preparatory-settings.adoc#create-customer-class[Creating a customer class]
* xref:crm:emailbuilder.adoc#email-server-login-details[Saving the email server login details]
* xref:crm:emailbuilder.adoc#create-template[Creating a template]
* xref:online-store:setting-up-ceres.adoc#300[Saving legal information]
* xref:business-decisions:domains.adoc#[Domains]
* xref:business-decisions:ssl-certificate.adoc#[SSL certificates]
* xref:business-decisions:your-contract.adoc#[Your contract with plentymarkets]

TIP: Continue to xref:welcome:quick-start-stock-management.adoc#[Setting up a warehouse and supplier]
