= Preparing order processing
:lang: en
include::{includedir}/_header.adoc[]
:position: 110
:icons: font
:url: welcome/quick-start/quick-start-preparing-order-processing
:id: C0B259C
:author: team-order-payment

IMPORTANT: Have you already set up your online shop? Not yet? Return to <<welcome/quick-start/quick-start-online-store#, setting up the plentyShop LTS webshop>>.

You can manage incoming orders from your online shop in the back end of your plentymarkets system. On this page, you can find the necessary settings that you should carry out to prepare for order processing.

[#10]
== Carrying out basic settings

First, carry out the basic settings for the *Orders* area. Some of the settings are already preset in your plentymarkets system and can be changed later on, if required. However, there are some settings that you should change immediately. Those settings are explained in <<table-orders-quick-start-basic-settings>>. Proceed as follows to carry out the settings:

[.instruction]
Carrying out the basic settings:

. Go to *Setup » Orders » Settings*.
. Carry out the settings according to <<table-orders-quick-start-basic-settings>>.
. *Save* (icon:save[role="green"]) the settings.

[[table-orders-quick-start-basic-settings]]
.Carrying out basic settings
[cols="1,3"]
|====
|Setting |Explanation

| *Automatic warehouse selection*
|The automatic warehouse selection automatically assigns the corresponding warehouse connected to the items included in the order. We recommend selecting one of the following 2 options: +
*b) depending on the item’s main warehouse*: With this option, the main warehouse assigned to an item decides about the warehouse that is automatically selected. The main warehouse has to be saved in the variation data beforehand. Selecting this option makes sense if you always want to ship particular items from a fixed warehouse. +
*c) depending on the highest stock level*: This option selects the warehouse according to the highest stock level of the variation. Selecting this option makes sense if an item is shipped from several different warehouses. We also recommend this option if you start your business using only one warehouse for all variations. If you start shipping items from several different warehouses later on, you do not have to change this setting.

A more detailed explanation of all the warehouse options can be found under <<orders/basic-settings##intable-warehouse-selection, Automatic warehouse selection>>.

| *Status changes to 4 instead of 5 if stock is missing*
|We recommend selecting *YES* here. This setting prevents orders containing items that are out of stock from entering the order status *[5] Cleared for shipping* by mistake. Instead, the orders automatically remain in *status [4] In preparation for shipping*.
|====

A more detailed explanation of all basic settings in the *Setup » Orders » Settings* menu can be found in the manual section <<orders/basic-settings#, Basic settings>>.

[#20]
== Setting up order documents

Order documents, such as invoices and delivery notes, are important parts of order processing. Before processing orders in your plentymarkets system, you need to set up document templates for those documents. While setting up the templates, you determine which information is displayed on the documents. In addition, you can include the individual header or letterhead of your company in the document template. +

plentymarkets distinguishes between fulfilment documents and location-based documents. Fulfilment documents such as the pick list or packing list are needed for the processes of picking and shipping orders. For further information on setting up these documents, pay attention to the links at the end of this page. +

[#30]
=== Setting up invoice documents

When preparing your plentymarkets system for order processing, the location-based documents are of particular importance. In the following section, we describe how to set up the document templates for *Invoice* and *Reversal document* by quickly transferring the default settings to these templates. You can proceed the same way when setting up document templates for other necessary order documents.

[.instruction]
Setting up the template for the *Invoice* document:

. Go to *Setup » Client » [Select client] » Locations » [Select location] » Documents » Invoice*.
. Change to the *Transfer* tab.
. Click on *Accept* (icon:cog[]) in the *Apply the settings from default document template*  area.
. A new window opens. Confirm your selection by clicking on *OK*. +
→ The default document template saved in your plentymarkets system is applied to the *Invoice* document.
. Change to the *PDF template* tab.
. Click on *Add template* (icon:plus-square[role="green"]).
. Leave the preset setting for *Payment method* on *Default* and change the *Language* to *en*.
. Click on *Choose template file* (icon:upload[role="purple"]).
. Select the PDF template containing the individual letterhead or logo of your company saved on your local computer.
. Click on *Upload template*(icon:save[role="green"]). +
→ The PDF template is uploaded.
. Open the *Template* tab.
. Click on *Preview* (icon:eye[role="blue"]). +
→ A preview of the *Invoice* document containing your individual PDF template as well as the previously transferred default settings is displayed.

After finishing the steps explained above, you have successfully set up a default template for the *Invoice* document. This is sufficient for most use cases. However, there are some additional settings that allow you to further customise the document, if needed. To do so, proceed as described below.

[.instruction]
Carrying out additional settings for the *Invoice* document:

. Open the *Template* tab.
. Carry out the desired settings. <<table-quick-start-invoice-additional-settings>> describes some useful options.
. Click on *Preview* (icon:eye[role="blue"]). +
→ A preview of the *Invoice* document containing your individual PDF template as well as the previously transferred default settings is displayed.
. *Save* (icon:save[role="green"]) the settings.

[[table-quick-start-invoice-additional-settings]]
.Carrying out additional settings for the *Invoice* document
[cols="1,3"]
|====
|Setting |Explanation

| *Margins*
|Here, you determine the margins of the document. The margin settings correspond to the German DIN A4 format. Carry out adjustments according to the customary formats in your country. In some cases, it can be necessary to adjust the *Top* margin to a higher value to ensure that the letterhead containing the company logo is displayed properly on the document template.

2+| *Positioning the mandatory elements* area

| *Own VAT number*
|Use this field to display your company’s own VAT number on the invoice. In case you have not already done so, you must enter your VAT number beforehand in the *System » System settings » Client » [Select client] » Locations » [Select location] » Accounting* menu. We recommend to only use this field to display the VAT number on the *Invoice* document in case it is not already included in your company’s letterhead.

2+| *Optional elements below stock unit table* area

| *Incoming payment*
|Select *YES* to display the date of complete incoming payment on the invoice.

| *Note*
|The note is displayed at the bottom of the invoice document. The default text is *Thank you for your order!*. Adjust this text according to your own wishes and requirements.

|====

You have now carried out all necessary steps for setting up the *Invoice* document. Thus, all invoices belonging to orders with the order language English are generated according to your settings for all payment methods.

[IMPORTANT]
.Generating invoices in other languages
====
As already described above, the invoice belongs to the location-based documents in your plentymarkets system. This means that the invoice document, as well as all further document templates, have to be set up for all additional languages you require. This becomes necessary if you accept orders from foreign countries in your online shop or if your company operates in a location outside your own country. You can easily transfer the settings carried out in the previous steps to invoice documents in other languages. Further information and instructions on setting up the document template are available in the <<orders/order-documents#, Order documents>> section of the manual.
====

[#40]
=== Setting up the reversal document

In addition to the invoice, the *Reversal document invoice* is the second mandatory document for which you should set up a document template before starting to process orders. You can easily transfer the settings carried out for the *Invoice* document to the document template for the *Reversal document invoice*. The reversal document is a kind of reverse invoice. This document is mandatory for cancelling invoices that you have already generated. In addition, reversal documents are relevant to accounting, just like invoices. Thus, you should carefully carry out the settings described in the following.

[.instruction]
Setting up the template for the *Reversal document invoice* document:

. Go to *Setup » Client » [Select client] » Locations » [Select location] » Documents » Invoice*.
. Change to the *Transfer* tab.
. In the *Apply settings to target template* area, select the target template *Reversal document invoice*.
. Click on *Copy* (icon:cog[]).
. A new window opens. Confirm your selection by clicking on *OK*. +
→ The template for the *Invoice* document is applied to the *Reversal document invoice* document.
. Go to *Setup » Client » [Select client] » Locations » [Select location] » Documents » Invoice*.
. In the *Document name/number* field in the *Positioning of the mandatory elements* area, enter the text *Reversal document invoice*.
. *Save* (icon:save[role="green"]) the settings.
. Open the *PDF template* tab.
. Click on Add template (icon:plus-square[role="green"]).
. Leave the preset setting for *Payment method* on *Default* and change the *Language* to *en*.
. Click on *Select template*.
. Select the PDF template containing the individual letterhead or logo of your company saved on your local computer.
. Click on *Upload template* (icon:upload[role="purple"]). +
→ The PDF template is uploaded.
. Open the *Template* tab.
. Click on *Preview* (icon:eye[role="blue"]). +
→ A preview of the *Reversal document invoice* containing your individual PDF template as well as the settings transferred from the *Invoice* document is displayed.

[#50]
=== Setting up the delivery note

In contrast to the *Invoice* document, sending a delivery note along with the order is not mandatory. Nonetheless, the delivery note is one of the most important shipping documents for many sellers. With the help of a delivery note, your customers can make sure that the shipment contains all ordered items and is thus complete. +
Proceed as described below to set up a document template for the *Delivery note* document.

[.instruction]
Setting up a template for the *Delivery note* document:

. Go to *Setup » Client » [Select client] » Locations » [Select location] » Documents » Delivery note*.
. Change to the *Transfer* tab.
. Click on *Accept* (icon:cog[]) in the *Apply the settings from default document template*  area.
. A new window opens. Confirm your selection by clicking on *OK*. +
→ The default document template saved in your plentymarkets system is applied to the *Delivery note* document.
. Change to the *PDF template* tab.
. Click on *Add template* (icon:plus-square[role="green"]).
. Leave the preset setting for *Payment method* on *Default* and change the *Language* to *en*.
. Click on *Choose template file* (icon:upload[role="purple"]).
. Select the PDF template containing the individual letterhead or logo of your company saved on your local computer.
. Click on *Upload template*(icon:save[role="green"]). +
→ The PDF template is uploaded.
. Open the *Template* tab.
. Click on *Preview* (icon:eye[role="blue"]). +
→ A preview of the *Delivery note* document containing your individual PDF template as well as the previously transferred default settings is displayed.

After finishing the steps explained above, you have successfully set up a default template for the *Delivery note* document. This way, all information considered mandatory for delivery notes (customer name, order number, order date, item quantity and item descriptions) is displayed on the document by default. However, there are some additional settings that allow you to further customise the document, if needed. To do so, proceed as described below.

[.instruction]
Carrying out additional settings for the *Delivery note* document:

. Go to *Setup » Client » [Select client] » [Select location] » Documents » Delivery note*.
. Open the *Template* tab.
. Carry out the desired settings. <<table-quick-start-delivery-note-additional-settings>> describes some useful options.
. *Save* (icon:save[role="green"]) the settings.

[[table-quick-start-delivery-note-additional-settings]]
.Carrying out additional settings for the *Delivery note* document
[cols="1,3"]
|====
|Setting |Explanation

| *Margins*
|Here, you determine the margins of the document. The margin settings correspond to the German DIN A4 format. Carry out adjustments according to the customary formats in your country. In some cases, it can be necessary to adjust the *Top* margin to a higher value to ensure that the letterhead containing the company logo is displayed properly on the document template.

2+| *Positioning the mandatory elements* area

| *Ordered on*
|The default document template displays the date at which the document itself was generated. Using the *Ordered on* field, you can additionally display the date on which the order was placed.

| *Referrer*
|Enter a description in the text field, for example *Order referrer*, and select the respective coordinates. This way, the delivery note can display information on whether the order reached you via your online shop or via an integrated market.

2+| *Columns stock units* area

| *Variation image*
|You can upload images and assign variations to an item in the *Images* tab of the item. This image can also be displayed on the delivery note. To display the image, select a position in the *Pos* field and enter an optional description that will appear next to the image.
|====

You have now carried out all necessary steps to set up the *Delivery note* document. Thus, all delivery notes belonging to orders with the order language English are generated according to this template.

[#60]
== Using the order overview

In the *Orders » Edit orders* menu, plentymarkets offers you an overview of all incoming orders. The order overview lists orders regardless of the order referrer. It does not matter whether you have created the orders manually or they have reached you via markets you have integrated in your plentymarkets system such as *eBay* or *Amazon*. +
Different business cases such as returns, credit notes, repairs and warranties are created as individual orders with their own types in your plentymarkets system. These order types are always linked to the original main order. The main orders are also available in the order overview. +
On the left-hand side of the *Orders » Edit orders* menu, several filters and search possibilities are available to limit the number of orders displayed. With these you can search for data as for example the *Order ID* or the *Invoice number*. The date filter is set to display orders that were received during the past 2 months by default. Adjust the filters *Date* as well as *from* and *to*, so that more orders than those for the last two months are displayed.

By default, the order overview offers you access to the following data for every order listed:

* Order ID
* Date on which the order was received/created
* Invoice number
* Incoming payment
* Outgoing items
* Shipping date
* Order referrer
* Status
* Shipping profile
* Payment method

The function *Show existing processes* is particularly useful. It is available for every order. This function shows you if and which processes in the form of returns or credit notes are available and linked to the respective order.

[#70]
== Editing orders

Click on the order ID displayed at the left-hand side of each order to open the order itself. Several tabs are available within the order. Since there are numerous possibilities for working with orders using those tabs, we will only outline some important functions. Further information about orders can be found in the <<orders/managing-orders#, Managing orders>> section of the manual.

Within an order, you can:

* Access the contact data of the customer in the *Customer data* tab.
* Send emails to customers or find out which emails have already been sent to the customer in the *Email* tab.
* Manually generate order documents in the *Receipts* tab in case you have not automated the generation of order documents using <<automation/event-procedures#, event procedures>>.
* Manually book incoming payment in the *Payment* tab, if needed.
* Book *outgoing items* in the *Settings* tab.
* Use the *Overview* tab to manually change the *Status* to *[8] Cancelled* to cancel an order, if necessary.

[WARNING]
.Do not delete orders
====
In general, you should never delete orders. Malfunctions with items and shipping profile settings may occur when deleting orders. Furthermore, orders cannot be deleted when tax relevant documents have already been generated.
====

[#80]
== Check list

Work through the checklist in order to review your settings for preparing order processing.

[%interactive]

* [ ] Did you carry out the <<#10, basic settings>> for order processing?
* [ ] Did you set up the document template for the <<#30, invoice>> document?
* [ ] Did you set up the document template for the <<#40, reversal document invoice>> document?
* [ ] Did you familiarise yourself sufficiently with the <<#50, order overview>> and the possibilities of <<#60, editing orders>>?

[#90]
== More about order processing

* <<orders/managing-orders#, Managing orders>>
* <<orders/basic-settings#, Basic settings for orders>>
* <<orders/managing-orders#, Order types>>
* <<orders/managing-orders#200, Manually creating orders>>
* <<orders/managing-orders#1200, Order statuses>>
* <<orders/order-documents#, Order documents>>
* <<orders/order-referrer#, Order referrer>>.

Continue with <<quick-start/quick-start-markets#, Integrating markets>>.
