= Booking stock
:lang: en
include::{includedir}/_header.adoc[]
:keywords: book stock, booking stock, incoming items, add items, add an item, correct stock, correcting stock, stock correction
:position: 90
:url: welcome/quick-start/quick-start-booking-stock
:id: ZTYZTPX
:author: team-stock

IMPORTANT: Have you already set up your item catalogue? Not yet? Return to <<welcome/quick-start/quick-start-item-catalogue#, Setting up a catalogue of items>>.

All incoming items have to be booked into your stock management system. Depending on the amount of items you want to add, you can use different menus. For other options than the one explained here, refer to the <<stock-management/new-incoming-items#, New incoming items>> manual page.

[#100]
== Booking stock
The following section describes how to book new stock.

[.instruction]
Booking stock:

. Go to *Stock » New incoming items*.
. Click on *New incoming items*.
. Select a supplier by entering the name.
. *Save* (icon:save[role="green"]) the settings.
. Click on *Add item*. +
→ A new window for searching and selecting items opens.
. Enter search terms and select filter options. Pay attention to the information given in <<filter-items>>.
. Click on *Search* (icon:search[role="blue"]). +
→ The items that match the search criteria are listed.
. Enter the *Purchase price* (optional).
. Enter the *Quantity* (mandatory). +
→ The item is automatically selected after entering a quantity.
. Select a *Storage location* from the drop-down list. +
→ If you have not yet saved a storage location for an item, you can specify a new storage location here as well. To do so, click on *Search* (icon:search[role="blue"]).
. Enter the *RRP* (optional). +
→ The RRP will be applied to the item data once the incoming items data record is approved.
. To the right of the *Procedures* column, click on *Add item*. +
→ The item is added to the incoming items data record.

[[filter-items]]
.Item filters
[cols="1,3"]
|====
|Setting |Explanation

| *Item data*
|Searches item name 1 and the item's meta keywords.

| *Reset*
|Resets all of the filter settings, so that all items are displayed regardless of supplier. After the reset, click on *Search* to update the item list.
|====

Click on *Back to incoming items* to return to the overview of the incoming items data record.

[TIP]
.Correcting stock
====
Correct the stock if you have already booked stock for the main item and now want to specify how many of those items are in each variation.
====

TIP: Continue with <<welcome/quick-start/quick-start-online-store#, setting up your plentyShop>>.
