= Final steps
:author: kevin-stederoth
:keywords:
:description: In the final part of the quickstart guide, check if you're ready to go live and unlock your plentyShop.

The finish line is in sight. Use the checklist below to ensure that you have completed all necessary steps. Then it is finally time to unlock your shop. And last but not least, we want to show you some resources to help you find your way around plentymarkets.

[#10]
== Final check

Have you already...

[%interactive]

* [ ] carried out the welcome:quick-start-initial-settings.adoc#[initial settings]?
* [ ] set up your xref:welcome:quick-start-stock-management.adoc#[warehouse and supplier]?
* [ ] set up xref:welcome:quick-start-shipping-options.adoc#[shipping options]?
* [ ] set up your xref:welcome:quick-start-item-catalogue.adoc#[catalogue of items]?
* [ ] booked xref:welcome:quick-start-booking-stock.adoc#[stock]?
* [ ] set up your xref:welcome:quick-start-online-store.adoc#[online shop]?
* [ ] set up xref:welcome:quick-start-setting-up-payment-processing.adoc#[payment processing]?
* [ ] prepared xref:welcome:quick-start-preparing-order-processing.adoc#[order processing]?
* [ ] xref:welcome:quick-start-automating-processes.adoc#[automated] your processes?

[#20]
== Unlocking the online shop

Now you are almost done. At the beginning of this quick start, we locked the online shop and ensured that all emails would be sent to our own address for testing purposes. Before starting business, we have to revert these settings.

[.instruction]
Deactivating the test mode:

. Go to *Setup » Assistants » Basic setup*.
. Open the *Email accounts* assistant.
. Go to the *Login details* step. In the area *Would you like to activate the live mode?*, activate (material:check_box[role=skyBlue]) the option *Activate live mode*.
. Complete the assistant.
. Click on *Finalise* to save your settings.

[.instruction]
Unlocking the online shop:

. Go to *Setup » Client » Standard Shop (Standard) » Online store » Settings.*
. Click on *Unlock online store now*.

icon:rocket[role="blue"] *Congratulations! Your shop is now online!* icon:rocket[role="blue"]

[#30]
== Stay up to date

We constantly work on improving plentymarkets. To make sure you are always well-informed about all updates, we recommend to subscribe to the *Changelog* category in our forum. For this, you first need a forum account.

[.instruction]
Creating an account:

. Go to *Setup » Settings » User » Accounts* » Name of your user account.
. Click on *Create account*.

[.instruction]
Subscribing to the change log:

. Go to *Support » Forum » Go directly to the forum*. +
→ The forum opens in a new tab.
. Log in with your login details.
. Open your account settings by clicking on your avatar in the upper right corner and clicking on *Settings*.
. Open the *Categories* menu.
. Enter “Version 7” in the *Watched* field and confirm your input with the enter key.
. *Save* the settings.

From now on, you will automatically receive email notifications when a new change log is posted.

[#40]
== More about the manual

As you continue to dive deeper into the plentymarkets system to extend your store, you will probably reference this manual somewhat frequently. There are two ways to navigate it: the navigation tree and the search function. Use the navigation tree on the left to explore the manual or to get an overview of an entire topic. Use the search function to look up specific key words.

[NOTE]
.Versions
====
The manual describes the functionality of plentymarkets systems according to the beta version. However, by default, new systems use the stable version. As a result, some parts of the manual may deviate from your system environment for up to two weeks.

If you want to switch to a different version, open your back end and go to *Setup » Client » Global » Version* for more information.
====

[#50]
== More from plentymarkets

* If you want to add more functionality to your system or online shop, go to link:https://marketplace.plentymarkets.com/en[plentyMarketplace^] to check out more plugins.
* You can find news and announcements concerning plentymarkets on our link:https://www.plentymarkets.co.uk/blog/[blog^].
* Ever get stuck? Visit our link:https://forum.plentymarkets.com/[forum^] to receive help and learn useful tips and tricks from our supporters.
* Have a look at our xref:videos:videos.adoc#[video tutorials] if you are more of a visual learner.
* Our consultants will support you with help and advice, just link:https://www.plentymarkets.com/knowledge/help-centre/[make an appointment^].
* Or ask our link:https://marketplace.plentymarkets.com/en/partners[partner agencies^] for professional support when designing your online shop.
* Follow us on link:https://www.facebook.com/plentymarkets[Facebook^] and link:https://www.twitter.com/plentymarkets[Twitter^].
