= Setting up a warehouse and supplier
:lang: en
include::{includedir}/_header.adoc[]
:keywords: warehouse, warehouses, supplier, suppliers, set up a warehouse, setting up a warehouse, set up a supplier, setting up a supplier, set up warehouse, setting up warehouses, set up supplier, setting up suppliers
:position: 40
:url: welcome/quick-start/quick-start-stock-management
:id: ME2XTHD
:author: team-stock

IMPORTANT: Have you already saved your contact data, set up your email account and email templates and ordered a domain as well as a SSL certificate? Not yet? Return to <<welcome/quick-start/quick-start-initial-settings#, the initial settings>>.

In order to have a functional stock management system, you need to set up at least one warehouse and supplier and you will have to save stock. The first two are covered on this page.

If you do not want to track stock in plentymarkets, open the menu *Item » Edit item*, click on the tab *Variation ID » Settings* and select the option *Do not administer stock for this variation* for the *Limitation* setting. Then continue with <<item/managing-items#660, managing item images>>.

[#100]
== Setting up a warehouse

The following section describes how to set up a warehouse. However, it only includes the initial settings for a warehouse. Information on more detailed settings are provided on the manual pages listed below. +
It is recommended to have a distribution warehouse and a repair warehouse from the start.

[.instruction]
Setting up a warehouse:

. Go to *Setup » Stock » Warehouse*.
. Select one of the existing warehouses *KS Repair* or *KS Sales*.
. In the submenu, click on *Settings* (icon:cog[]). +
→ The overview of the warehouse opens.
. Rename the warehouse in the field *Warehouse name*.
. Select a warehouse type and a logistics type.
. *Save* (icon:save[role="green"]) the settings. +
→ The warehouse is set up and displayed on the left in the directory tree.
. Open the warehouse to see the sub-menus.

[#200]
== Setting up a supplier

The following section describes how to set up a supplier. Here, a supplier is only a type of a contact.

[.instruction]
Setting up a supplier:

. Go to *CRM » Contacts*.
. Click on *Create new contact*.
. Enter the name of the supplier.
. Select the type *Supplier*.
. In the *New address* field, select an address type (invoice or delivery address).
. Enter the address data.
. *Save* (icon:save[role="green"]) the settings.

[#300]
== More about warehouses and suppliers

* <<stock-management/setting-up-a-warehouse#, Setting up a warehouse>>
* <<crm/managing-contacts#100, Managing contacts>>.

TIP: Continue with <<welcome/quick-start/quick-start-online-store-introduction#, Setting up the online store: Introduction>>
