= Setting up the online store: Introduction
:lang: en
include::{includedir}/_header.adoc[]
:author: team-plugin-core
:position: 50
:url: welcome/quick-start/quick-start-online-store-introduction
:id: QCU0NOG
:author: team-webshop

IMPORTANT: Have you already set up a warehouse and created a supplier? Not yet? Return to <<welcome/quick-start/quick-start-stock-management#, Setting up a warehouse and supplier>>.

After creating your items and possibly setting up an interface to eBay in the previous chapters, we will now incorporate various payment methods in your online store as well as how to change its design. plentymarkets provides these functionalities, as well as others, via plugins.

There are no plugins installed on your system by default. Go to *System » Assistants* and complete the *Integrations Assistant* to install some basic extensions.

For the purposes of this quick start guide, we will use plentyShop LTS, the payment methods PayPal and cash in advance, as well as DHL as shipping provider. If you do not want to use some of them, skip the respective chapters of the quick start guide.

After completing the *Integrations Assistant*, go to *Plugins » Plugin set overview*.

[NOTE]
.Installation time
====
Installing your plugins may take a few minutes. The table in the *Plugin set overview* indicates when installation has finished.
====

The table shows your plugin sets. Sets are collections of plugins that all impact the design and functionality of your store as a whole. By linking a set to a client, you activate it for the associated store. Later on you can also create new sets without linking them to a client.This allows you to test changes without them impacting your live environment. Throughout this quick start, we will only work with the standard-shop set provided by default, however. First, unlink the set from the client.

include::../../plugins/_textblocks/instructions/plugin-set-verknuepfung-aufheben-en_gb.adoc[]

Open a plugin set (icon:pencil[role=yellow]) to view the plugins installed in the set.

Right next to the plugin sets, you will find filter settings. You can use these to display a different selection of plugins according to various criteria. When you open a plugin set, it shows all plugins installed in that set by default.

We will have a closer look at the plugins plentyShop LTS and IO later on. For now, we want to give customers the possibility to actually pay for their purchases.

TIP: Continue with <<welcome/quick-start/quick-start-setting-up-payment-processing#, payment processing>>.
