= Tags
:lang: en
include::{includedir}/_header.adoc[]
:keywords: tag, tags, create tags
:description: Learn how to manage tags in plentymarkets.
:position: 20
:url: welcome/general-functions/tags
:id: UZRABLS
:author: team-crm

Tags are keywords that you can use to highlight data records in plentymarkets.
Tags are very versatile. For example, tags help you:

* keep track of large amounts of data in the back end.
That means, you highlight specific customers, variations, categories, messages, etc.
* highlight products in the front end.
That means, you assign keywords to specific variations.

Essentially, the process consists of just two steps.
First, <<welcome/general-functions/tags#100, create the tags>>.
Second, <<welcome/general-functions/tags#400, link the tags>> with the appropriate data records.

[#50]
== Requirement: Necessary user rights

Users of the type *Back end* can only access limited areas and menus in the plentymarkets back end. Thus, their access to the system is limited. If you want users with *Back end* access to work with tags, then someone with *Admin* access will need to give them the necessary rights.

[.instruction]
Assigning user rights:

. Go to *Setup » Settings » User » Rights » User*.
. Use the search function (icon:search[role="blue"]) and open the account that should be edited.
. In the *Authorisations* area, activate the rights as listed in <<#table-tags-required-rights-back-end-user>>.
. *Save* (icon:save[role="green"]) the settings.

[[table-tags-required-rights-back-end-user]]
.Granting user rights
[cols="1,3"]
|====
|Setting |Explanation

| *Setup > Tag > Update*
|The right to edit existing tags.

| *Setup > Tag > Show*
|The right to see tags in the plentymarkets system.

| *Setup > Tag > Create*
|The right to create new tags.

| *Setup > Tag > Delete*
|The right to delete tags.

| *Setup > Tag > Tag relationship > Update*
|The right to edit existing tag links.

| *Setup > Tag > Tag relationship > Show*
|The right to see tag links in the plentymarkets system.

| *Setup > Tag > Tag relationship > Create*
|The right to create new tag links.

| *Setup > Tag > Tag relationship > Delete*
|The right to delete tag links.
|====

[#100]
== Creating and editing tags

[#200]
=== Creating new tags

//tag::create-new-tags[]
First, create the tags that you want to use for your products, customers, orders, tickets, etc.

[.instruction]
Creating a new tag:

. Go to *Setup » Settings » Tags*.
. Click on *Create new tag* (icon:plus[role="green"]). +
→ A window opens on the right-hand side.
. Carry out the settings. Note the explanations in <<#table-tag-settings>>.
. *Save* (icon:save[role="green"]) the settings. +
→ The tag is created and added to the list.

[[table-tag-settings]]
.Creating a tag
[cols="1,3"]
|====
|Setting |Explanation

| *ID*
|The tag ID is automatically assigned and cannot be changed.
It is used to uniquely identify your tags.

*_Use case_*: Tag links can be imported.
For example, while you import item and variation data, you can also directly link the appropriate tags.
This is done, e.g. by specifying the tag ID.

| *Name EN* +
[red]#(Mandatory field)#
|Enter a name for the tag.
The name is the keyword that highlights the data record.

*_Tip_*: The name can include spaces, i.e. it can be multiple words.

| *Colour*
a|What background colour should the tag text have?
There are three ways to choose the colour.

* Enter the colour’s hexadecimal value.
* Enter the English name for one of the 16 basic colours (black, red, silver, white, etc.) +
* Click on the square on the right and choose the colour.

|[#intable-availability]*Availability*
a|What types of data records will you link to this tag?
Select all of the appropriate availabilities (icon:check-square[role="blue"]).

[cols="1,3"]
!===
!Availability !Example of use

! *Board*
!Do you want to highlight specific task cards on boards?
For example, you could specify that some tasks have a high or low priority.

! *Category*
!Do you want to highlight specific categories in the back end?
For example, you could specify that a category should only be used for seasonal offers.

*_Note_*: Category tags are _not visible_ to customers in the online store.

! *Ticket*
!Do you want to highlight specific tickets within the ticket system?
For example, you could specify that the ticket relates to a specific sales channel like Amazon or eBay.

! *Contact*
!Do you want to highlight specific contacts?
For example, you could specify the customer’s preferred method of communication.

! *Variation*
!Do you want to highlight specific variations?
For example, if you sell ladders, you could specify that some ladders were awarded a seal of approval for their safety features.

*_Note_*: Variation tags can be made _visible_ to customers in the online store.
Do so by <<welcome/general-functions/tags#intable-client, selecting the appropriate client>> further below.

! *Order*
!Tags can currently be created for orders, but they cannot be linked to orders yet.
Therefore, this option is currently not in use.

! *Messages*
!Do you want to highlight specific messages within the messenger tool?
For example, you could specify that the message relates to a specific sales channel like Amazon or eBay.

! *Message (billable)*
!Do you occasionally write fee-based messages in the messenger tool?
In other words, should the customer be charged for the minutes that elapsed while writing the message?

While writing a fee-based message, you’ll need to select at least one tag with this availability.
Otherwise, the message cannot be created.
!===

|[#intable-client]*Client* +
(functional for plentyShop LTS 5.0 and higher)
|In which webshops should the tag be visible to customers?
Select all of the appropriate webshops (icon:check-square[role="blue"]).

*_Note_*: This option only appears if you <<welcome/general-functions/tags#intable-availability, selected the availability Variation>>.

| *Name DE* +
*Name FR* +
*Name IT* +
etc.
|Translate the tag names into other languages.

*_Example of use_*: Variation tags can be made visible to customers in the online store.
If your online store is available in multiple languages, then the tag names should also appear in these languages.
|====
//end::create-new-tags[]

//Falls es irgendwann möglich ist, Tags mit dem Import-Tool zu importieren, dann hier ein Kapitel ergänzen

[#300]
=== Searching for and editing existing tags

You can search for existing tags and modify their settings again at any time.

[.instruction]
Searching for and opening tags:

. Go to *Setup » Settings » Tags*.
. Select one or more filters on the left. Note the explanations in <<#table-tag-filter>>.
. Click on *Search* (icon:search[role="blue"]). +
→ The corresponding tags will be displayed in the middle.
The tags are sorted alphabetically.
. Click on a tag to open it. +
→ <<welcome/general-functions/tags#200, The settings>> can be modified again on the right.

[[table-tag-filter]]
.Tag filters
[cols="1,3"]
|====
|Setting |Explanation

| *Name*
|Search for the tag by its name.

*_Note_*: Tag names can be saved in multiple languages.
However, you can only search for names in the main language of your plentymarkets system.

| *Availability*
|Select one or more availabilities (icon:check-square[role="blue"]).
The search results only include tags that were activated for this availability.

| *Language*
|Select one or more languages (icon:check-square[role="blue"]).
The search results only include tags that have a name saved in this language.
|====

[#400]
== Linking tags

Once you’ve created your tags, you can link them with data records.

[[table-link-tags]]
.Linking tags
[cols="1,3"]
|====
|Tag availability |How are such tags linked?

|Board
|<<welcome/customise-system#380, Tags are manually linked to task cards on boards>>.

|Category
|<<item/settings/categories#700, Tags are manually linked to categories in the back end>>.

|Ticket
|<<crm/using-the-ticket-system#1800, Tags are manually linked to tickets in the ticket system>>.

|Contact
|<<crm/managing-contacts#300, Tags are manually linked to contacts>>.

|Variation
a|* <<item/managing-items#268, Tags can manually be linked to variations>>.
* <<data/importing-data/sync-types/elasticSync-item#2290, Tag links can be imported>>.

|Messages
|<<crm/messenger#create-message, Tags are manually linked to messages within the messenger tool>>.

|Message (billable)
|<<crm/messenger#create-message, Tags are manually linked to fee-based messages within the messenger tool>>.
|====
