= plentyPOS einrichten
:author: team-app-bi
:keywords: plentyPOS, plenty POS, POS einrichten, POS Einrichtung, POS Benutzer, POS Zahlungsart, POS Buchungskonto, POS Selbstabholung, Preise Kassenaufträge, Rundungsverhalten Kassenaufträge, Kassenauftrag, Dummy-Artikel, Diversartikel, POS Gutschein, POS Retoure, Kasse verbinden, POS verbinden, Kassenbeleg senden, Kassenbeleg drucken, Kundenkarte, Kassenjournal, Kassenauftrag ändern, POS Auftrag ändern, Kasse löschen, POS löschen, POS entkoppeln, POS Berechtigungen, POS Rechte
:table-event-procedure: <<table-POS-event-procedure-outgoing-items>>, <<table-POS-event-procedure-send-receipt>>
:description: Richtest du plentyPOS zum ersten Mal ein? Diese Seite führt dich Schritt für Schritt durch den Prozess.

Mit dem mobilen Kassensystem plentyPOS integrierst du den stationären Handel mühelos in plentymarkets.

Diese Handbuchseite enthält Anleitungen zur Einrichtung deines plentyPOS. Richtest du plentyPOS zum ersten Mal ein? Dann empfehlen wir dir, die Kapitel auf dieser Handbuchseite der Reihe nach sorgfältig durchzugehen und die Einstellungen vorzunehmen.

Nutze alternativ die folgenden Links und die Navigation auf der rechten Seite, um gezielt zu den gewünschten Inhalten auf dieser Handbuchseite zu gelangen.

* <<#10, Erste Schritte und allgemeine Informationen>>
* <<#130, Benutzerkonten für plentyPOS verwalten>>
* <<#710, Zahlungsarten für Kassenaufträge aktivieren>>
* <<#950, Buchungskonten für plentyPOS Kassenvorfälle speichern>>
* <<#180, Versandart Selbstabholung einrichten>>
* <<#100, Preise für Kassenaufträge verwalten>>
* <<#800, Rundungsverhalten für Kassenaufträge festlegen>>
* <<#95, Standardkunden für Kassenaufträge erstellen>>
* <<#220, Dummy-Artikel erstellen>>
* <<#2100, Mehrzweckgutscheine und Aktionsgutscheine>>
* <<#3600, Retouren vorbereiten>>
* <<#3000, Warenausgang automatisch buchen>>
* <<#230, Kasse mit Gerät verbinden>>
* <<#250, Senden des Kassenbelegs an Bestandskund:innen einrichten>>
* <<#990, Kundenkarten verwenden>>
* <<#1000, Druck von Kassenbelegen über andere Drucker einrichten>>
* <<#1090, Druck von Artikeletiketten einrichten>>
* <<#1100, plentyPOS ohne Internetverbindung nutzen>>
* <<#400, Kassenvorgänge im Kassenjournal suchen>>
* <<#960, Kassenaufträge im plentymarkets Backend ändern>>
* <<#910, Kasse außer Betrieb nehmen>>

[#10]
== Erste Schritte und allgemeine Informationen

Das Kassensystem plentyPOS wird über die xref:app:installieren.adoc#[plentymarkets App] bereitgestellt. Wirf einen Blick in unsere Dokumentation und lerne:

* welche xref:app:installieren.adoc#400[Hardware-Voraussetzungen] für plentyPOS bestehen.
* wo du die kostenlose xref:app:installieren.adoc#500[plentymarkets App herunterladen] kannst.
* wie du deinen Mitarbeiter:innen xref:app:installieren.adoc#600[Zugang zur App] gewährst.
* wie du dich in die App xref:app:installieren.adoc#1100[einloggst und zurechtfindest].

plentyPOS ist für das Kassieren mit den Währungen Euro (EUR), Schweizer Franken (CHF) und Britische Pfund (GBP) vorbereitet. Du kannst die Kasse allerdings nur in der xref:payment:waehrungen.adoc#30[Systemwährung] betreiben. Die Systemwährung legst du im Menü *Einrichtung » Aufträge » Zahlung » Währungen* fest.

[IMPORTANT]
====
.Kasse buchen
Um plentyPOS verwenden zu können, link:https://www.plentymarkets.com/de/produkt/preise/[buche zunächst eine oder mehrere Kassen^] für deine plentymarkets Edition. Informationen zu den Konditionen findest du direkt bei der Buchung oder auf der link:https://www.plentymarkets.com/de/produkt/module/point-of-sale/[plentyPOS Produktseite^].
====

Nachdem du Kassen gebucht hast, dauert es zunächst zwei bis drei Minuten, bis der Aktivierungsprozess im Hintergrund abgeschlossen ist. Logge dich dann aus deinem plentymarkets System aus und wieder ein. Dieser Schritt ist auch notwendig, wenn du bereits Kassen eingerichtet hast und im Nachhinein eine oder mehrere neue Kassen hinzubuchst.

Anschließend richtest du die Kassen im plentymarkets Backend ein. Zunächst weist du die Kassen einem Mandanten zu, indem du die Kasse im Menü *Einrichtung » POS » [Mandant wählen]* erstellst und weitere Einstellungen vornimmst. Gehe dazu wie unten beschrieben vor.

[WARNING]
.POS-Einstellungen nicht im laufenden Betrieb ändern
====
Ändere POS-Einstellungen nicht im laufenden Betrieb. Wenn du dennoch Änderungen an den POS-Einstellungen vornimmst, fordere das Kassenpersonal auf, sich aus der App auszuloggen und wieder einzuloggen, da sonst vor allem bei einer Änderung der Rundungseinstellungen Unstimmigkeiten in den Gesamtbeträgen entstehen.
====

[#40]
=== Kasse erstellen

Erstelle zunächst im plentymarkets Backend eine Kasse für den gewünschten Mandanten (Shop).

[.instruction]
Kasse für Mandanten erstellen:

. Öffne das Menü *Einrichtung » POS » [Mandant wählen]*.
. Klicke auf *Neue Kasse*. +
→ Das Fenster *Neue Kasse* wird eingeblendet.
. Gib einen Namen für die Kasse ein.
. *Speichere* (icon:save[role="darkGrey"]) die Einstellungen. +
→ Der Kasse wird eine Herkunft zugeordnet. +
→ Die Kasse wird gespeichert und zur weiteren Bearbeitung geöffnet.

<<table-POS-menu-bar>> beschreibt die Menüleiste der Kasse.

[[table-POS-menu-bar]]
.Menüleiste der Kasse
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *ID*
|Eindeutige Kennung der Kasse. Diese ID wird automatisch und mandantenübergreifend vergeben und ist nicht änderbar.

| *Kopieren*
|Erstellt eine neue Kasse mit den Einstellungen der geöffneten Kasse. Dabei werden Name und Herkunft neu vergeben. +
*_Hinweis:_* Das Kopieren einer Kasse ist nur möglich, wenn eine ausreichende Anzahl an Kassen gebucht wurde.

| *Gerät*
|Zeigt die eindeutige ID des Geräts an, wenn die Kasse bereits mit einem Gerät gekoppelt ist.

| *Löschen*
|Löscht die Kasse aus dem System.
|====

[#50]
=== Grundeinstellungen der Kasse vornehmen

Du befindest dich nun im Menü *Einrichtung » POS » [Mandant öffnen]*.

Stelle sicher, dass du die neu erstellte Kasse geöffnet hast, indem du auf den Namen der Kasse links im Menübaum klickst. Nimm dann im Tab *Grundeinstellungen* die gewünschten Einstellungen vor. Beachte dazu die Erläuterungen in <<table-POS-basic-settings>>.

[[table-POS-basic-settings]]
.Tab *Grundeinstellungen* der Kasse
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Name*
|Gib einen Namen für die Kasse ein.

| *Herkunft*
|Beim Buchen einer Kasse wird automatisch eine Herkunft für diese Kasse generiert, um Aufträge, die über diese Kasse ins System gelangen, eindeutig zu kennzeichnen. Der neuen Kasse wird automatisch eine verfügbare POS-Herkunft (103.01 bis 103.99) zugeordnet.

| *Standardkunde*
|Wähle den für Kassenaufträge <<#95, erstellten Standardkunden>>, dem über diese Kasse generierte Aufträge zugeordnet werden sollen.

2+^| *Standort*

| *Name 1-4*; +
*Adresse 1-4*; +
*Postleitzahl*; +
*Ort*; +
*Land*
|Gib den Firmennamen und die Adresse des Ladengeschäfts ein, an dem die Kasse betrieben wird. +
*_Hinweis:_* In Deutschland und anderen Ländern ist die Adresse eine Pflichtangabe, um ein rechtssicheres Arbeiten mit der Kasse zu ermöglichen. Genaue Standortangaben mit Steuerberater:in klären. +
*_Standort Österreich:_* Nachdem der Startbeleg für die Kasse erstellt wurde, kann das Land des Kassenstandorts nicht mehr geändert werden.

2+^| *Vertriebslager*

| *Vertriebslager*
|Wähle, für welches Vertriebslager die über diese Kasse genierten Aufträge gebucht werden sollen. +
*_Hinweis:_* Artikel ohne Netto-Warenbestand werden im POS-Warenkorb rot markiert, können aber verkauft werden. Deshalb kann es zu rechnerischen Überverkäufen kommen.

2+^| *Retoure*

| *Standard-Reparaturlager*
|Wähle, welches Lager bei Retouren als Standardreparaturlager vorgeschlagen wird.

| *Standard-Regal*
|Wähle, welches Regal bei Retouren vorgeschlagen wird.

| *Standard-Reparaturlagerort*
|Wähle, welcher Lagerort bei Retouren als Standard-Reparaturlagerort vorgeschlagen wird. +
*_Tipp:_* Drücke zweimal die Pfeiltaste, um eine Liste der Lagerorte anzuzeigen.

| *Retourenbetrag als Gutschein auszahlen* +
|Wähle, ob das Kassenpersonal einen Gutschein in Höhe des Retourenbetrags aushändigen darf, statt den Betrag bar auszuzahlen.

| *Varianten-ID des Retourengutscheins* +
|Gib die ID der Variante ein, die als Gutscheinartikel für Retouren dient.

2+^| *Warenbewegung*

| *Warenbestand bei Stornierung zurückbuchen*
|Aktiviere die Option, um den Warenbestand automatisch zurückzubuchen, wenn ein Auftrag storniert wird.

| *Externer Auftrag: Warenausgang automatisch buchen* +
(ab App-Version 1.9.2)
|Wähle, ob für externe Aufträge, die an der Kasse bezahlt werden, der Warenausgang automatisch gebucht werden soll. +
Aktiviert (Standardeinstellung) = Der Warenausgang wird automatisch gebucht. Die Schaltfläche *Warenausgang buchen* wird Kassenkräften nicht angezeigt. +
Nicht aktiviert = Der Warenausgang wird nur gebucht, wenn das Kassenpersonal auf *Warenausgang buchen* tippt. +
*_Tipp:_* Deaktiviere die Option, wenn die Ware nicht direkt an der Kasse ausgegeben wird.

| *Warenausgang von externen Aufträgen: Ware aus POS-Vertriebslager buchen* +
(ab App-Version 1.9.2)
|Wähle, aus welchem Lager die Auftragspositionen ausgebucht werden, wenn externe Aufträge an der Kasse abgeschlossen werden. +
Nicht aktiviert (Standardeinstellung) = Die Auftragspositionen werden aus dem Lager gebucht, das dem Auftrag bei der Erstellung zugeordnet wurde. +
Aktiviert = Die Auftragspositionen werden aus dem für die Kasse eingestellten *Vertriebslager* gebucht. Das Lager, das am Auftrag gespeichert ist, wird überschrieben.

2+^| *Artikelfilter*

| *Marktplatz-Verfügbarkeit berücksichtigen*
|Wähle, ob für die Kasse die Marktplatz-Verfügbarkeit berücksichtigt werden soll. Die Marktplatz-Verfügbarkeit wird im Tab *Verfügbarkeit*, Bereich *Märkte* der Variante aktiviert. +
Option aktiviert = In der Kasse sind nur Varianten verfügbar, für die im Tab *Verfügbarkeit*, Bereich *Märkte* die Herkunft der Kasse aktiviert ist. +
Option nicht aktiviert = Auch nicht für die Herkunft der Kasse aktivierte Varianten sind in der Kasse verfügbar und können aufgerufen und verkauft werden.

| *Nur aktive Varianten berücksichtigen*
|Wähle, ob für die Kasse nur aktive Varianten berücksichtigt werden sollen. Varianten werden im Tab *Einstellungen* der Variante aktiviert. +
Option aktiviert = In der Kasse sind nur Varianten verfügbar, für die im Tab *Einstellungen* der Variante die Option xref:artikel:artikel-manuell-anlegen.adoc#600[Aktiv] aktiviert ist. +
Option nicht aktiviert = Aktive und inaktive Varianten sind in der Kasse verfügbar und können aufgerufen und verkauft werden.

2+^|[#pos-item-information]*Artikelinformationen*

| *Attribute*
|Aktiviere (icon:check-square[role="blue"]) diese Option, um in der Kassieransicht die xref:artikel:attribute.adoc#[Attribute] der Artikel anzuzeigen. +
*_Hinweis:_* Diese Option ist standardmäßig aktiviert.

| *Unverbindliche Preisempfehlung*
|Aktiviere (icon:check-square[role="blue"]) diese Option, um in der Kassieransicht die unverbindliche Preisempfehlung der Artikel anzuzeigen.

| *Altersfreigabe (FSK)*
|Aktiviere (icon:check-square[role="blue"]) diese Option, um in der Kassieransicht die am Artikel gepflegte Information zur xref:artikel:import-export-anlage-verzeichnis.adoc#intable-altersfreigabe[Altersfreigabe] anzuzeigen.

| *Netto-Warenbestand*
|Aktiviere (icon:check-square[role="blue"]) diese Option, um in der Kassieransicht den xref:glossar:glossar.adoc#netto-warenbestand[Netto-Warenbestand] des Artikels anzuzeigen.

| *Externe Varianten-ID*
|Aktiviere (icon:check-square[role="blue"]) diese Option, um in der Kassieransicht die xref:artikel:import-export-anlage-verzeichnis.adoc#intable-externe-varianten-id[externe Varianten-ID] anzuzeigen.

| *Variantennummer*
|Aktiviere (icon:check-square[role="blue"]) diese Option, um in der Kassieransicht die xref:artikel:import-export-anlage-verzeichnis.adoc#intable-variantennummer[Variantennummer] anzuzeigen.

| *Einkaufspreis*
|Aktiviere (icon:check-square[role="blue"]) diese Option, um in der Kassieransicht den xref:artikel:import-export-anlage-verzeichnis.adoc#intable-ek-netto[Einkaufspreis] des Artikels anzuzeigen.

2+^| *Bedienung*

| *Preisabfrage wenn Artikelpreis 0,00*
|Aktiviere die Option, um die manuelle Preiseingabe zu öffnen, wenn beim Kassieren ein 0-Euro-Artikel gewählt wird.

| *Favoriten mit Menge 1 hinzufügen*
|Aktiviere die Option, um beim Kassieren Favoriten automatisch mit der Menge 1 in den POS-Warenkorb zu legen. Artikel mehrmals in den Warenkorb legen, um die Anzahl zu erhöhen. +
*_Tipp:_* Bei Favoriten, die über die Artikelsuche hinzugefügt werden, wird die Menge weiterhin manuell eingegeben.

| *Numpad (Tablet-Ansicht): Buttons für schnelle Mengeneingabe und passende Zahlung einblenden*
a|Aktiviere die Option, um die Komfortfunktionen auf dem Ziffernblock der Kasse einzublenden. +
Nicht aktiviert = Die Komfortfunktionen werden nicht eingeblendet. +
Aktiviert = Die folgenden Komfortfunktionen werden als zusätzliche Reihe im Ziffernblock der Kasse eingeblendet:

* *Mal* = Kassenbenutzer:innen können die Menge eingeben, bevor sie einen Artikel scannen oder einen Favoritenartikel wählen. Wenn vor dem Scannen keine Menge eingegeben wird, wird der gescannte Artikel mit der Menge 1 in den POS-Warenkorb gelegt.
* *Passend* = Bei passender Barzahlung können Kassenbenutzer:innen auf diese Schaltfläche tippen, statt den erhaltenen Betrag einzugeben. Das Feld *Erhalten* wird mit dem zu zahlenden Betrag aufgefüllt.

| *Soll-Bestand anzeigen*
|Wähle, ob der Soll-Bestand beim Erstellen eines xref:pos:pos-kassenbenutzer.adoc#230[Tagesabschlusses] oder xref:pos:pos-kassenbenutzer.adoc#450b[Kassensturzes] sichtbar sein soll. Diese Option ist standardmäßig deaktiviert. Somit sieht das Kassenpersonal beim Zählen _nicht_, wie viel Geld in der Kasse erwartet wird. Es ist sinnvoll, diese Einstellung nicht zu ändern, damit das Kassenpersonal den Bestand wirklich selbst zählt. Ist die Information eingeblendet, kann das Kassenpersonal den Soll-Bestand direkt übernehmen, ohne selbst gezählt zu haben.

| *Kassenschublade*
|Wähle, ob die Kassenschublade sich nur öffnen soll, wenn Kund:innen in bar zahlen oder ein Betrag erstattet wird. Wenn diese Option aktiviert ist, wird die Kassenschublade bei Kartenzahlungen oder -erstattungen nicht geöffnet.

2+^| *Kundenkarte*

| *Kundenidentifikation* +
(ab App-Version 1.9.2)
|Wähle, welche Kontaktdaten durchsucht werden, wenn ein Barcode mit einem Pluszeichen (+) als Präfix gescannt wird. +
*Kontakt-ID* (Standardeinstellung) = Wähle diese Option, wenn Barcodes die Kontakt-ID enthalten. +
*Kundennummer* (empfohlen) = Wähle diese Option, wenn Barcodes die Kundennummer enthalten. +
*_Tipp:_* Bei der Einstellung *Kundennummer* können vorab Kundenkarten mit Barcodes gedruckt werden. Der Barcode-Code wird dann ohne das Pluszeichen in dem Feld *Kundennummer* des Kontakts gespeichert. Weitere Informationen zur Beschaffung und Verwendung von Kundenkarten findest du im Kapitel <<#990, Kundenkarten verwenden>>.

2+^| *Fiskalisierung (Deutschland)* +
(ab App-Version 1.10.0)

| *Seriennummer der Kasse*
| Nach erfolgreicher Kopplung der Kasse mit einer technischen Sicherheitseinrichtung wird die Seriennummer hier automatisch eingetragen.

| *Seriennummer der TSE*
| Nach erfolgreicher Kopplung der Kasse mit einer technischen Sicherheitseinrichtung wird die Seriennummer hier automatisch eingetragen.

| *Public Key der TSE*
| Nach erfolgreicher Kopplung der Kasse mit einer technischen Sicherheitseinrichtung wird der Public Key hier automatisch eingetragen.

2+^| *Fiskalisierung (Österreich)*

| *Kassenidentifikationsnummer*
| Kassenidentifikationsnummer, die über FinanzOnline gemeldet wurde.

| *AES-Schlüssel* +
(nur neue Kassen mit Standort Österreich)
|Gib den AES-Schlüssel ein, mit dem der Umsatzzähler der Kasse verschlüsselt werden soll. Der AES-Schlüssel ist frei wählbar. Nachdem der Startbeleg für die Kasse erstellt wurde, kann der AES-Schlüssel nicht mehr geändert werden. +
*_Tipp:_* Auf *Schlüssel generieren* klicken, um einen zufälligen Schlüssel zu generieren. +
*_Hinweis:_* Existierende Kassen können nicht nachträglich manipulationssicher gemacht werden. Neue Kasse erstellen und alte Kasse außer Betrieb nehmen, um Sicherheitseinrichtung einzurichten.

| *Vertrauensdiensteanbieter* +
(nur neue Kassen mit Standort Österreich)
|Gib den Namen des Vertrauensdiensteanbieters ein, bei dem das Zertifikat gekauft wurde. +
*_Hinweis:_* Existierende Kassen können nicht nachträglich manipulationssicher gemacht werden. Neue Kasse erstellen und alte Kasse außer Betrieb nehmen, um Sicherheitseinrichtung in Betrieb zu nehmen.

| *Seriennummer des Signaturzertifikats* +
(nur neue Kassen mit Standort Österreich)
|Gib die Seriennummer des Signaturzertifikats ein (siehe Unterlagen des Vertrauensdiensteanbieters). +
*_Hinweis:_* Existierende Kassen können nicht nachträglich manipulationssicher gemacht werden. Erstelle eine neue Kasse und nimm die vorherige Kasse außer Betrieb, um die Sicherheitseinrichtung in Betrieb zu nehmen.
|====

[#60]
=== Favoriten verwalten

Du hast die Möglichkeit, Varianten zur Favoritenliste hinzuzufügen. Dadurch kann das Kassenpersonal häufig verkaufte Varianten schneller aufrufen und zum POS-Warenkorb hinzufügen.

[#70]
==== Varianten als Favoriten speichern

Gehe wie unten beschrieben vor, um Varianten als Favoriten zu speichern.

[.instruction]
Varianten als Favoriten speichern:

. Öffne das Menü *Einrichtung » POS » [Mandant wählen]*.
. Öffne die Kasse.
. Wechsele in das Tab *Favoriten*.
. Öffne das Tab *Variante hinzufügen*. +
→ Eine Liste der Varianten wird angezeigt.
. *_Optional:_* Nutze die Filter, um die Anzeige einzuschränken.
. Klicke auf *Varianten hinzufügen*. +
→ Die Varianten werden zur Liste der Favoriten hinzugefügt und im Tab *Favoriten* angezeigt. +
→ Beim nächsten Synchronisieren mit plentyPOS werden die Favoriten an die Kasse übertragen.

[TIP]
.Favoriten des Kassenpersonals haben Priorität
====
Das Kassenpersonal kann eigene Favoriten in plentyPOS speichern. Die Favoriten des Kassenpersonals haben dabei Priorität gegenüber den im plentymarkets Backend gespeicherten Favoriten.
====

[#80]
==== Reihenfolge der Favoriten ändern

Die Priorität der Favoriten legst du über die Pfeilsymbole des Tabs *Favoriten* fest. Die am häufigsten verkaufte Variante sollte ganz oben in der Liste stehen. Die erste Variante der Liste des Menü wird dem Kassenpersonal auch als erste Variante der Favoritenliste vorgeschlagen. Gehe wie unten beschrieben vor, um die Reihenfolge der Favoriten festzulegen.

[.instruction]
Reihenfolge der Favoriten ändern:

. Öffne das Menü *Einrichtung » POS » [Mandant wählen]*.
. Öffne die Kasse.
. Öffne das Tab *Favoriten*. +
→ Die Liste der Varianten auf der Favoritenliste wird angezeigt.
. Klicke in der Spalte *Aktionen* auf den Pfeil der Variante, deren Position du ändern möchtest. +
→ Mit dem Pfeil nach oben erhöhst du die Priorität der Variante. +
→ Mit dem Pfeil nach unten verringerst du die Priorität der Variante.

[#90]
==== Favoritenliste auf andere Kassen übertragen

Die Favoritenliste einer Kasse kann auf andere Kassen des Mandanten übertragen werden. Dabei werden in der Zielkasse vorhandene Favoriten nicht gelöscht. Gehe dazu wie unten beschrieben vor.

[.instruction]
Favoriten auf andere Kassen übertragen:

. Öffne das Menü *Einrichtung » POS » [Mandant wählen]*.
. Öffne die Kasse.
. Öffne das Tab *Favoriten*. +
→ Die Liste der Varianten auf der Favoritenliste wird angezeigt.
. Klicke auf *Favoriten übertragen*. +
→ Das Fenster *Favoriten übertragen* wird angezeigt.
. Aktiviere die Kassen, zu denen du die Favoriten dieser Kasse kopieren möchten.
. Klicke auf *Speichern* (icon:save[role="darkGrey"]). +
→ Die Favoriten werden auf die gewählten Kassen übertragen.

[#110]
==== Varianten aus Liste der Favoriten löschen

Gehe wie unten beschrieben vor, um Varianten aus der Liste der Favoriten zu löschen. Aus der Liste gelöschte Varianten werden beim nächsten Synchronisieren mit der POS-App aus der Favoritenliste der Kasse entfernt.

[.instruction]
Varianten aus Liste der Favoriten löschen:

. Öffne das Menü *Einrichtung » POS » [Mandant wählen]*.
. Öffne die Kasse.
. Öffne das Tab *Favoriten*. +
→ Die Liste der Varianten auf der Favoritenliste wird angezeigt.
. Klicke in der Spalte der Variante auf *Löschen*. +
→ Die Variante wird aus der Liste der Favoriten entfernt.

[#120]
=== Belegvorlage bearbeiten

Im Tab *Beleg* der Kasseneinstellungen bestimmst du die Daten, die auf Belegen ausgegeben werden sollen. Lade optional ein Bild hoch und lege Kopf- und Fußzeile für Belege fest. Standardmäßig ist die Kopfzeile mit den im Menü *Einrichtung » Einstellungen » Stammdaten* gespeicherten Daten befüllt. Diese Daten kannst du pro Kasse anpassen. Die Fußzeile gestaltest du individuell, um zum Beispiel auf Aktionsangebote oder deinen Onlineshop hinzuweisen.

[.instruction]
Belegvorlage bearbeiten:

. Öffne das Menü *Einrichtung » POS » [Mandant wählen]*.
. Öffne die Kasse.
. Wechsele in das Tab *Beleg*.
. Aktiviere die Komponenten, die auf Belegen der Kasse angezeigt werden sollen.
. Nimm die gewünschten Einstellungen vor. Beachte dazu die Erläuterungen in <<table-POS-receipt-template>>.
. *Speichere* (icon:save[role="darkGrey"]) die Einstellungen. +
→ Die Belegvorlage wird erstellt.

[[table-POS-receipt-template]]
.Belegvorlage bearbeiten
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+^|Belegeinstellungen

| *Gutscheinbeleg drucken und speichern*
a|Wähle, ob ein Gutscheinbeleg gedruckt und im Dokumentenarchiv gespeichert werden soll. +

Nicht aktiviert (Standard) = Kein Gutscheinbeleg wird erstellt. +
Aktiviert = Beim Verkauf oder einer Teileinlösung eines Gutscheins wird ein Gutscheinbeleg erstellt. +
→ Der Gutscheinbeleg wird erstellt und im Dokumentenarchiv gespeichert. +
→ Wenn die Option *Automatisches Drucken* im Menü *plentymarkets App » Einstellungen » POS* aktiviert ist, wird der Gutscheinbeleg nach dem Kassenbeleg ausgedruckt. +
→ Wenn *Automatisches Drucken* im Menü *plentymarkets App » Einstellungen » POS* nicht aktiviert ist, können Kassenbenutzer:innen den Gutscheinbeleg nach Abschluss des Auftrags manuell drucken. +
Der Gutscheinbeleg enthält die folgenden Informationen zum Gutschein:

* Gutscheinwert
* Gutschein-Code
* Bei Teileinlösung: eingelöster Betrag und Restbetrag

*_Hinweis:_* Beim Verkauf eines Gutscheins wird der Gutschein-Code unabhängig von der gewählten Einstellung immer auf dem normalen Kassenbeleg ausgegeben.

| *Grand Total auf Tagesabschluss ausblenden*
|Wähle, ob das xref:glossar:glossar#grand-total[Grand Total] im Tagesabschlussbericht aufgeführt werden soll. +
Nicht aktiviert (Standard) = Das Grand Total wird nicht im Tagesabschlussbericht aufgeführt. +
*_Hinweis:_* In diesem Fall kann das Grand Total nur von POS-Benutzer:innen mit Admin-Rechten am POS selbst eingesehen werden. +
Aktiviert = Das Grand Total wird im Tagesabschlussbericht aufgeführt.

| *Verwendete Rabatt-Codes auf Tagesabschluss einzeln auflisten*
|Wähle, ob Rabatt-Codes, die im Rahmen von xref:glossar:glossar#aktionsgutschein[Aktionsgutscheinen] eingelöst wurden, einzeln im Tagesabschlussbericht aufgeführt werden sollen. +

Nicht aktiviert (Standard) = Die Gesamtmenge aller eingelösten Rabatt-Codes wird im Tagesabschluss aufgeführt. +
Aktiviert = Identische Rabatt-Codes erhalten einen einzelnen Eintrag im Tagesabschlussbericht. Zusätzlich wird die jeweilige Anzahl der Rabatt-Codes angegeben, sodass zwischen verschiedenen Codes differenziert wird.

2+^|Beleginhalte

| *Identische Auftragspositionen*
|Wähle, wie mehrere identische Varianten auf dem Beleg dargestellt werden sollen. +
*Einzeln darstellen* = Unabhängig von der gekauften Stückzahl wird jede gekaufte Variante einzeln aufgeführt. Beispiel: +
---------------------------------------------------- +
Katzenfutter CaTasty Deluxe           6,99 EUR A +
Katzenfutter CaTasty Deluxe           6,99 EUR A +
Katzenfutter CaTasty Deluxe           6,99 EUR A +
---------------------------------------------------- +
*Zusammenfassen* = Identische Varianten werden zusammengefasst. Beispiel: +
---------------------------------------------------- +
Katzenfutter CaTasty Deluxe          20,97 EUR A +
3 x 6,99 EUR A +
---------------------------------------------------- +

| *Details zur Auftragsposition*
|Aktiviere eine der Optionen *Varianten-ID*, *Variantennummer*, *Attribute* oder *Ext. Varianten-ID*, um auf
dem Beleg die entsprechende Zusatzinformation zum verkauften Artikel auszugeben. Die Information wird unterhalb des Artikelnamens auf dem Kassenbeleg angezeigt. Aktiviere die Option *Keine*, um keine Zusatzinformation anzuzeigen.

| *Bild*
|Aktiviere die Option und wähle eine PNG-Datei, die auf Belegen der Kasse ausgeben werden soll. Die Datei muss vorher im Menü *CMS » Bilder-Galerie* hochgeladen werden.

| *Kopfzeile*
|Wenn die Option aktiviert ist, wird Inhalt des Felds als Kopfzeile aller Belege der Kasse ausgegeben. Standardmäßig ist die Kopfzeile mit den im Menü *Einrichtung » Einstellungen » Stammdaten* gespeicherten Daten befüllt. Daten bei Bedarf anpassen.

| *Barcode*
|Sollen Barcodes auf deinen Belegen erscheinen? +
Im Falle einer xref:pos:pos-kassenbenutzer.adoc#175[Retoure] oder eines xref:pos:pos-online-bestellungen#[Click & Collect-Auftrags] bringen Kund:innen typischerweise ihre Kaufbelege mit in den Laden. Wurde ein Barcode auf dem Beleg gedruckt, muss das Kassenpersonal lediglich xref:pos:pos-kassenbenutzer.adoc#520[den Barcode scannen], um den entsprechenden Auftrag aufzurufen. +
Barcodes helfen also dem Kassenpersonal, Aufträge schneller zu finden. Die manuelle Eingabe der Belegnummer oder Auftrags-ID entfällt. +
*_Hinweis_* Die Belegnummer wird als Barcode dargestellt und enthält dabei ein Sternchen (*) als Präfix. Beim Scannen gibt das Sternchen an, dass eine Belegnummer gesucht wird.

| *Fußzeile*
|Aktiviere die Option und gib einen zusätzlichen Text ein.

|====

[#130]
== Benutzerkonten für POS verwalten

Um dem Kassenpersonal den Zugriff auf plentyPOS zu ermöglichen, sind die folgenden Vorbereitungen nötig:

* Benutzerkonto für Kassenpersonal ohne Admin-Konto erstellen
* Berechtigung für Sichtbarkeit von POS aktivieren
* Berechtigungen für POS-Funktionen aktivieren (optional)
* Berechtigungen für Kommunikation mit plentymarkets Backend über die REST-API aktivieren
* Berechtigungen für Sichtbarkeit von Kennzahlen aktivieren (optional)
* Auftragsherkünfte aktivieren

Die Einstellungen, die du benötigst, um ein Benutzerkonto für Kassenpersonal zu erstellen, werden nachfolgend beschrieben. Allgemeine Informationen zu Benutzerkonten und Berechtigungen findest du auf der Handbuchseite xref:business-entscheidungen:benutzerkonten-zugaenge.adoc#[Benutzer:innen-Konten und Zugänge].

[TIP]
.Tipp: Rolle für Kassenpersonal erstellen
====
Um die Rechteverwaltung für Kassenpersonal zu vereinfachen, erstelle eine xref:business-entscheidungen:benutzerkonten-zugaenge.adoc#70[Rolle] mit den Berechtigungen, die du Kassenpersonal zuweisen möchtest, und verknüpfe diese Rolle mit den Benutzerkonten des Kassenpersonals.
====

[#140]
=== Konto für Kassenpersonal erstellen

Damit neues Kassenpersonal Zugriff auf plentyPOS erhält, erstelle zunächst im plentymarkets Backend xref:business-entscheidungen:benutzerkonten-zugaenge.adoc#[Benutzerkonten] für diese Personen. Gehe dazu wie unten beschrieben vor.

[.instruction]
Benutzerkonto für Kassenpersonal erstellen:

. Öffne das Menü *Einrichtung » Kontoverwaltung » Konten*.
. Klicke auf *Neu* (icon:plus-square[]). +
. Gib den *Benutzernamen* ein.
. Gib den *realen Namen* ein.
. Gib das *Passwort* ein.
. Wiederhole das Passwort.
. Gib eine *App-PIN* mit 4 bis 12 Ziffern ein.
. Wiederhole die App-PIN.
. Gib die E-Mail-Adresse der Kassenkraft ein, damit die Person Benachrichtigungen des Systems empfängt.
. *Speichere* (icon:save[role="darkGrey"]) die Einstellungen.

[TIP]
.App-PIN für schnellen Kontowechsel
====
Die App-PIN erlaubt einen schnellen Wechsel des Benutzerkontos in bestimmten Menüs der plentymarkets App. Beim ersten Anmelden in der App wird aber das Passwort abgefragt. Dein Kassenpersonal benötigt also Passwort *und* PIN.
====

[#150]
=== Berechtigungen für Kassenpersonal erteilen

Erteile nun Berechtigungen für die Kommunikation zwischen plentyPOS und dem plentymarkets Backend.

:rights-purpose: die Grundfunktionen von plentyPOS als Kassenpersonal nutzen können
:right-one: pass:quotes[*POS > Lesen*]
:right-two: pass:quotes[*CRM > Kampagne > Code > Lesen*]
:right-three: pass:quotes[*CRM > Kampagne > Code > Erstellen*]
:right-four: pass:quotes[*CRM > Kampagne > Code > Löschen*]
:right-five: pass:quotes[*CRM > Adresse > Anzeigen*]
:right-six: pass:quotes[*Aufträge > Lesen*]
:right-seven: pass:quotes[*Aufträge > Erstellen*]
:right-eight: pass:quotes[*Warenbestände > Lager > Lagerort > Lesen*]

include::_includes:partial$rights.adoc[]

[#160]
=== POS-Sichtbarkeit für Kassenpersonal aktivieren

Nun legst du fest, welche Bereiche und Kennzahlen für Kassenpersonal ohne Admin-Konto in der plentymarkets App sichtbar sein sollen.

[.instruction]
App-Berechtigungen aktivieren:

. Öffne das Menü *Einrichtung » Kontoverwaltung » Rollen*. +
→ Die Übersicht wird geöffnet. +
. Klicke auf *Suchen* (icon:search[role="blue"]), um alle Rollen zu sehen.
. Öffne die gewünschte Rolle.
. Klicke auf *Rechte*.
. Aktiviere (icon:check-square[role="blue"]) die Option *plentymarkets App / plentyPOS » POS-Funktionen » Betrachten*.
. *Speichere* (icon:save[role="darkGrey"]) die Einstellungen.
. Wenn die Kassenkraft auf weitere Bereiche der plentymarkets App zugreifen soll, aktiviere xref:pos:pos-einrichten.adoc#170[weitere Berechtigungen].
. *Speichere* (icon:save[role="darkGrey"]) die Einstellungen. +
→ Die Kassenkraft hat Zugriff auf plentyPOS und kann Kassenaufträge erstellen.

[#170]
=== Berechtigungen für optionale POS-Funktionen aktivieren

Damit Kassenpersonal in plentyPOS Preise bearbeiten, Auftragspositionen umbenennen und/oder Rabatte gewähren können, musst du die Berechtigungen dazu zuweisen. Wie du Rollen einrichtest und Benutzern zuweist, erfährst du xref:business-entscheidungen:benutzerkonten-zugaenge.adoc#70[hier]. Dort schaltest du auch weitere App-Funktionen für Kassenpersonal frei.

Im plentymarkets Backend legst du über das Zuweisen von Rollen fest, welche POS-Funktionen Kassenpersonal verwenden darf. Dort legst du außerdem fest, welche weiteren Bereiche und Kennzahlen in der plentymarkets App sichtbar sein sollen.

[.instruction]
Berechtigungen für POS-Funktionen aktivieren:

. Öffne das Menü *Einrichtung » Kontoverwaltung » Rollen*. +
→ Die Übersicht wird geöffnet. +
. Klicke auf *Suchen* (icon:search[role="blue"]), um alle Rollen zu sehen.
. Öffne die gewünschte Rolle.
. Klicke auf *Rechte*.
. Aktiviere die POS-Funktionen, die der Kassenkraft zur Verfügung stehen sollen. Beachte dazu die Erläuterungen in <<table-POS-rights>>.
. *Speichere* (icon:save[role="darkGrey"]) die Einstellungen.

[[table-POS-rights]]
.Mobile-Berechtigungen für Kassenpersonal
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+^|Sichtbare Funktionen

| *POS*
|Gewährt Kassenpersonal Zugang zu plentyPOS.

2+^|POS-Funktionen

| *Preis bearbeiten*
|Erlaubt Kassenpersonal, Preise in Aufträgen zu bearbeiten.

| *Artikelposition umbenennen*
|Erlaubt Kassenpersonal, Positionen des Auftrags umzubenennen.

| *Rabatt gewähren*
|Erlaubt Kassenpersonal, Rabatte auf Auftragspositionen oder ganze Aufträge zu gewähren. +
*_Hinweis:_* Artikel, bei denen die Option *Aktionsgutschein/POS-Rabatt* auf *Verboten* gestellt ist, können nicht rabattiert werden.

| *Kassieren*
|Erlaubt Kassenpersonal zu kassieren.

| *Kasse sperren*
|Erlaubt Kassenpersonal, die Kasse zu sperren.

| *Einlagen und Entnahmen*
|Erlaubt Kassenpersonal, Einlagen und Entnahmen zu tätigen.

| *Kassensturz*
|Erlaubt Kassenpersonal, Kassenstürze durchzuführen.

| *Tagesabschluss*
a|Erlaubt Kassenpersonal, Tagesabschlüsse zu erzeugen. +
Tagesabschlussberichte enthalten folgende Informationen: +

* Barbestand: Anfangsbarbestand, Entnahmen, Einlagen, Soll-Kassenbestand, Ist-Kassenbestand
* Umsatz: seit letztem Tagesabschluss (Summe) und seit Inbetriebnahme der Kasse (Grand Total)
* Steuerbericht: Steuersatz, Steuersumme und Nettoumsatz
* Zahlungsarten: Aufschlüsselung des Umsatzes nach Zahlungsart
* Retournierte Artikel: Anzahl und Summe
* Stornierungen: Anzahl und Summe
* Rabattierte Artikel: Anzahl und Summe
* Verkaufte Gutscheine: Anzahl und Summe
* Benutzer: Umsatz, Stornierungen und Retouren pro Benutzer

| *Zwischenbericht*
a|Erlaubt Kassenpersonal, Zwischenberichte zu erzeugen. +
Zwischenberichte enthalten folgende Informationen: +

* Barbestand: Entnahmen, Einlagen, Soll-Kassenbestand
* Umsatz: seit letztem Tagesabschluss (Summe) und seit Inbetriebnahme der Kasse (Grand Total)
* Steuerbericht: Steuersatz, Steuersumme und Nettoumsatz
* Zahlungsarten: Aufschlüsselung des Umsatzes nach Zahlungsart
* Retournierte Artikel: Anzahl und Summe
* Stornierungen: Anzahl und Summe
* Rabattierte Artikel: Anzahl und Summe
* Verkaufte Gutscheine: Anzahl und Summe
* Benutzer: Umsatz, Stornierungen und Retouren pro Benutzer

| *TSE-Einheit*
|Erlaubt Kassenpersonal, das Menü *TSE-Einheit* in der plentymarkets App zu öffnen. In diesem Menü stehen xref:pos:pos-rechtssicherheit.adoc#900[Informationen zum Status der technischen Sicherheitseinrichtung] zur Verfügung. Zudem wird Kassenpersonal mit dieser Berechtigung erlaubt, xref:pos:pos-rechtssicherheit.adoc#700[TSE-Exporte] zu erstellen.

| *Artikel synchronisieren*
|Erlaubt Kassenpersonal, Artikeldaten mit der Kasse zu synchronisieren.

| *Aufträge hochladen*
|Erlaubt Kassenpersonal, Kassenaufträge in plentymarkets hochzuladen.

| *Retoure anlegen*
|Erlaubt Kassenpersonal, Retouren zu buchen.

| *Kunde auswählen*
|Erlaubt Kassenpersonal, während des Kassierens Kundendaten aufzurufen und einen plentymarkets Bestandskunden zu wählen.

| *Stornierung*
|Erlaubt Kassenpersonal, Aufträge zu stornieren.
|====

[#175]
=== Auftragsherkünfte für Kassenpersonal aktivieren

[.instruction]
Auftragsherkünfte aktivieren:

. Öffne das Menü *Einrichtung » Kontoverwaltung » Rollen*. +
→ Die Übersicht wird geöffnet.
. Klicke auf *Suchen* (icon:search[role="blue"]). +
→ Die gefundenen Rollen werden angezeigt.
. Öffne die gewünschte Rolle.
. Gehe zum Bereich *Zugriffsrechte*.
. Öffne den Eintrag *Auftragsherkünfte*. +
→ Eine Liste der verfügbaren Auftragsherkünfte wird angezeigt. Dabei wird jede verfügbare Kasse als separate Auftragsherkunft aufgelistet.
. Aktiviere alle Kassen, an denen die Kassenkraft arbeiten soll.
. *Speichere* (icon:save[role="darkGrey"]) die Einstellungen.

[WARNING]
.Auftragsherkünfte sorgfältig aktivieren
====
Achte genau darauf, *alle* POS-Auftragsherkünfte zu aktivieren, zu denen das Kassenpersonal Kassiervorgänge ausführen soll. Betreibst du beispielsweise 2 Kassen, aktiviere im Benutzerkonto beide Kassen als Auftragsherkunft. Ansonsten ist es der Kassenkraft nicht möglich, an Kasse 1 zu kassieren und später an der Kasse 2 einen Retourenvorgang für den selben Verkauf durchzuführen.
====

=== Gesperrte POS-Benutzer entsperren

Wenn Kassenbenutzer:innen das Passwort beim Login mehrmals hintereinander falsch eingegeben, wird das Konto eine gewisse Zeit gesperrt. Wenn du Admin-Rechte hast, kannst du diese Sperre im plentymarkets Admin-Bereich frühzeitig aufheben.

[.instruction]
Benutzer entsperren:

. Öffne das Menü *Einrichtung » Kontoverwaltung » Konten*.
. Öffne ein Konto.
. Klicke im Bereich *Anmeldedaten* auf *Login entsperren*. +
→ Die Kassenkraft kann sich wieder bei der plentymarkets App anmelden.

[#710]
== Zahlungsarten für Kassenaufträge aktivieren

Damit Aufträge über plentyPOS kassiert werden können, aktivierst du die Zahlungsarten, die du über plentyPOS erlauben möchtest. Mindestens die Zahlungsart *Bar bei Übergabe* muss aktiviert werden, damit Kassenaufträge bar bezahlt werden können. Weitere Zahlungsarten sind optional.

Zur Aktivierung der Zahlungsarten für plentyPOS benötigst du das kostenlose Plugin *plentyPOS Zahlungsarten*. Das Plugin stellt die folgenden Zahlungsarten zur Verfügung:

* *4 » Bar bei Übergabe* für Barzahlungen
* *11 » Barverkauf/EC-Karte* für Kartenzahlungen über externe EC-Kartenterminals
* *1700 » Coupon* für Gutscheinzahlungen

[.instruction]
Zahlungsarten für Kassenaufträge aktivieren:

. Installiere das Plugin link:https://marketplace.plentymarkets.com/pospaymentmethodrenaming_6813[plentyPOS Zahlungsarten^]. +
*_Hinweis:_* Beachte die Informationen im Tab *Beschreibung* des Plugins im plentyMarketplace.
. Öffne das Menü *Einrichtung » Assistenten » Plugins*.
. Wähle das Plugin-Set, in dem du das Plugin installiert hast.
. Öffne den Assistenten *plentyPOS Zahlungsarten*.
. Vergib Namen für die Zahlungsarten.
. Schließe den Assistenten ab. +
→ Die Zahlungsarten werden aktiviert und stehen im Menü *Einrichtung » Aufträge » Zahlungen » Zahlungsarten zur Verfügung*. Dort kannst du bei Bedarf einzelne Zahlungsarten deaktivieren. Achte jedoch darauf, dass für plentyPOS immer mindestens die Zahlungsart *Bar bei Übergabe* aktiviert sein muss.

[IMPORTANT]
.Zahlungsarten umbenennen
====
Du kannst den Assistenten zu einem späteren Zeitpunkt erneut durchlaufen, wenn du die Namen der Zahlungsarten erneut ändern möchtest. Der Name wird im plentymarkets Backend, auf plentyPOS Belegen, im Zwischenbericht, Tagesabschluss und in den über plentyPOS generierten Exporten angezeigt.
====

Beachte auch, dass Zahlungsarten in einem weiteren Schritt für Kundenklassen erlaubt werden müssen. Weitere Informationen findest du unter xref:payment:zahlungsarten-verwalten.adoc#30[Zahlungsart in Kundenklasse erlauben].

[TIP]
.Zahlungsart Barverkauf/EC-Karte
====
Stelle für die Zahlungsart *11 » Barverkauf/EC-Karte* außerdem im Menü *Einrichtung » POS » [Mandant wählen] » [POS wählen] » Tab: Zahlungsart* die Option *Ohne Anbindung* im Bereich *EC-Terminal* ein.
====

[#1070]
=== Kartenterminals anbinden

Bestimmte Kartenterminals können über ein Plugin an plentyPOS angebunden werden. Aktuell unterstützt plentyPOS folgende Anbindungen:

* link:https://marketplace.plentymarkets.com/plugins/payment/ingenicozvt_5140[Ingenico-Geräte über ZVT-Schnittstelle^]
* link:https://marketplace.plentymarkets.com/plugins/payment/sumup_5141[SumUp Air^]
* link:https://marketplace.plentymarkets.com/plugins/payment/VerifoneZVT_5504[Verifone-Geräte über ZVT-Schnittstelle^]
* link:https://marketplace.plentymarkets.com/zettle_54918[Zettle by PayPal^]

Wie du die Plugins einrichtest und weitere Informationen findest du in den Beschreibungen der Plugins.

[#1080]
=== Kauf auf Rechnung und Anzahlungen anbieten

Wenn du Bestandskund:innen die Möglichkeit geben möchtest, Kassenaufträge per Rechnung oder mithilfe einer Anzahlung zu bezahlen, benötigst du das folgende Plugin:

* link:https://marketplace.plentymarkets.com/plugins/payment/PosInvoice_5590[POS Kauf auf Rechnung^]

Wie du das Plugin einrichtest und weitere Informationen findest du in der Beschreibung des Plugins.

[#950]
== Buchungskonten für plentyPOS Kassenvorfälle speichern

Aufträge, die über plentyPOS generiert werden, werden den in plentymarkets gespeicherten xref:auftraege:buchhaltung.adoc#800[Erlöskonten] zugewiesen. Da Einlagen, Entnahmen und Differenzen aus Kassenstürzen keine Aufträge sind, kannst du für diese Kassenvorfälle eigene Buchungskonten speichern. Du legst also fest, auf welche Buchungskonten Einlagen und Entnahmen gebucht werden, die über plentyPOS Kassen getätigt werden. Außerdem speicherst du Buchungskonten für Differenzen, die sich aus Kassenstürzen ergeben.

=== Buchungskonten für Kassensturzdifferenzen speichern

Wenn beim Kassensturz der Ist-Kassenbestand vom Soll-Kassenbestand abweicht, muss die Differenz entweder ausgeglichen oder gebucht werden. Wenn die Differenz gebucht wird, wird der Ist-Kassenbestand als neuer Soll-Kassenbestand übernommen. Gleichzeitig wird abhängig vom Vorzeichen des Differenzbetrags entweder eine Einlage (+) oder eine Entnahme (-) gebucht. Gehe wie unten beschrieben vor, um Buchungen, die sich aus Kassensturzdifferenzen ergeben, Buchungskonten zuzuweisen.

[.instruction]
Buchungskonten für Kassensturzdifferenzen speichern:

. Öffne das Menü *Einrichtung » Mandant » [Mandant wählen] » Standorte » [Standort wählen] » Buchhaltung*. +
→ Das Tab *Grundeinstellungen* wird geöffnet.
. Wechsele in das Tab *Konten*. +
→ Das Tab *Buchungsschlüssel* wird geöffnet.
. Wechsele in das Tab *Kassenvorfälle*.
. Klicke im Bereich *Entnahme* in der Zeile *Kassensturz* in das Feld der Spalte *Konto*.
. Gib das Konto ein, auf das Entnahmen gebucht werden, die entstehen, wenn der Ist-Kassenbestand größer ist als der Soll-Kassenbestand.
. Klicke im Bereich *Einlage* in der Zeile *Kassensturz* in das Feld der Spalte *Konto*.
. Gib das Konto ein, auf das Einlagen gebucht werden, die entstehen, wenn der Soll-Kassenbestand größer ist als der Ist-Kassenbestand.
. *Speichere* (icon:save[role="darkGrey"]) die Einstellungen. +
→ Die Buchungskonten werden gespeichert. +
→ Einlagen und Entnahmen, die durch Kassensturzdifferenzen entstehen, werden automatisch auf die gespeicherten Konten gebucht.

=== Buchungskonten für allgemeine Einlagen und Entnahmen speichern

Wenn Kassenpersonal Einlagen und Entnahmen über plentyPOS durchführt, wählt die Kassenkraft einen Kassenvorfall als Grund für die Buchung. Systemseitig sind dafür standardmäßig ein Kassenvorfall *Entnahme* und ein Kassenvorfall *Einlage* verfügbar, die nicht gelöscht werden können. Für diese Vorfälle kannst du Buchungskonten speichern, wenn die Beträge auf bestimmte Buchungskonten gebucht werden sollen. Gehe wie unten beschrieben vor, um Konten für diese Vorfälle zu speichern. Optional speicherst du in einem weiteren Schritt zusätzliche Konten, um mit mehreren Buchungskonten zu arbeiten.

[.instruction]
Buchungskonten für Einlagen und Entnahmen speichern:

. Öffne das Menü *Einrichtung » Mandant » [Mandant wählen] » Standorte » [Standort wählen] » Buchhaltung*. +
→ Das Tab *Grundeinstellungen* wird geöffnet.
. Wechsele in das Tab *Konten*. +
→ Das Tab *Buchungsschlüssel* wird geöffnet.
. Wechsele in das Tab *Kassenvorfälle*.
. Klicke im Bereich *Entnahme* in der Zeile *Entnahme* in das Feld der Spalte *Konto*.
. Gib das Konto ein, auf das allgemeine Entnahmen gebucht werden sollen.
. Klicke im Bereich *Einlage* in der Zeile *Einlage* in das Feld der Spalte *Konto*.
. Gib das Konto ein, auf das allgemeine Einlagen gebucht werden sollen.
. *Speichere* (icon:save[role="darkGrey"]) die Einstellungen. +
→ Die Buchungskonten werden gespeichert. +
→ Einlagen oder Entnahmen werden diesem Konto zugewiesen.

=== Weitere Buchungskonten für Einlagen und Entnahmen speichern

Wenn plentyPOS Einlagen und Entnahmen je nach Grund verschiedenen Buchungskonten zugewiesen werden sollen, legst du weitere Kassenvorfälle an. Diese Kassenvorfälle kann das Kassenpersonal wählen, wenn Bargeld aus der Kasse entnommen oder in die Kasse gelegt wird. Gehe wie unten beschrieben vor, um weitere Kombinationen aus Kassenvorfall und Buchungskonto zu speichern.

[.instruction]
Weitere Buchungskonten für Einlagen und Entnahmen speichern:

. Öffne das Menü *Einrichtung » Mandant » [Mandant wählen] » Standorte » [Standort wählen] » Buchhaltung*. +
→ Das Tab *Grundeinstellungen* wird geöffnet.
. Wechsele in das Tab *Konten*. +
→ Das Tab *Buchungsschlüssel* wird geöffnet.
. Wechsele in das Tab *Kassenvorfälle*.
. Klicke auf *Neue Einlage* oder *Neue Entnahme*. +
→ Eine leere Zeile wird eingefügt.
. Gib die *Bezeichnung* ein, die Kassenpersonal bei Einlagen oder Entnahmen in einer Dropdown-Liste angezeigt wird.
. Gib das Buchungskonto ein, dem die Einlage oder Entnahme buchhalterisch zugewiesen wird. +
*_Tipp:_* Über die Pfeile steuerst du die Reihenfolge, in der die Vorfälle in der App angezeigt werden.
. *Speichere* (icon:save[role="darkGrey"]) die Einstellungen. +
→ Das Buchungskonto wird gespeichert. +
→ Das Kassenpersonal kann bei Einlagen oder Entnahmen den Vorfall aus der Dropdown-Liste wählen.


[#180]
== Versandart Selbstabholung einrichten

Damit Kassenaufträge korrekt in plentymarkets verbucht werden, ermöglichst du die Versandart *Selbstabholung* für die Artikel, die du über plentyPOS abrechnen möchtest. Dazu sind folgende Vorbereitungen notwendig:

* Versanddienstleister *Selbstabholung* erstellen
* Versandprofil *Selbstabholung* erstellen
* Versandprofil *Selbstabholung* am Artikel aktivieren

Diese Vorbereitungen werden nachfolgend beschrieben.

[#190]
=== Versanddienstleister Selbstabholung erstellen

Gehe wie unten beschrieben vor, um einen Versanddienstleister *Selbstabholung* zu erstellen. Nur die für diesen Versanddienstleister relevanten Einstellungen werden beschrieben. Allgemeine Informationen zu Versanddienstleistern findest du auf der Handbuchseite xref:fulfillment:versand-vorbereiten.adoc#800[Versand vorbereiten].

[.instruction]
Versanddienstleister Selbstabholung erstellen:

. Öffne das Menü *Einrichtung » Aufträge » Versand » Optionen » Tab: Versanddienstleister*.
. Klicke auf *Neu* (icon:plus-square[role="green"]). +
→ Ganz unten wird eine neue Zeile hinzugefügt.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<table-POS-shipping-provider-pickup>>.
. *Speichere* (icon:save[role="darkGrey"]) die Einstellungen.

[[table-POS-shipping-provider-pickup]]
.Versanddienstleister *Selbstabholung* erstellen
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Name (de)*
|Gib den Namen für den Versanddienstleister ein, zum Beispiel *Selbstabholung*.

| *Name (Backend)*
|Gib einen Namen ein, der nur im Backend deines Systems angezeigt wird, zum Beispiel *Selbstabholung*.

| *Versanddienstleister*
|Wähle die Option *Selbstabholer* aus der Dropdown-Liste.
|====

[#200]
=== Versandprofil Selbstabholung erstellen

Erstelle nun ein Versandprofil für die Selbstabholung. Nur die für dieses Versandprofil relevanten Einstellungen werden beschrieben. Allgemeine Informationen zu Versandprofilen findest du auf der Handbuchseite xref:fulfillment:versand-vorbereiten.adoc#1000[Versand vorbereiten].

[.instruction]
Versandprofil für Selbstabholer erstellen:

. Öffne das Menü *Einrichtung » Aufträge » Versand » Optionen » Tab: Versandprofile*.
. Klicke auf *Neu* (icon:plus-square[role="green"]).
. Wähle den eben erstellten Versanddienstleister aus der Dropdown-Liste.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<table-POS-shipping-profile-pickup>>.
. *Speichere* (icon:save[role="darkGrey"]) die Einstellungen. +
→ Das Tab *Portotabelle* wird angezeigt.
. *Speichere* (icon:save[role="darkGrey"]) die Einstellungen des Tabs *Portotabelle* ohne Änderungen.

[[table-POS-shipping-profile-pickup]]
.Versandprofil *Selbstabholung* erstellen
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Versanddienstleister*
|Wähle den Versanddienstleister *Selbstabholung* aus der Dropdown-Liste.

| *Mandanten (Shops)*
|Diese Option wird nur angezeigt, wenn mindestens ein Mandant in deinem System eingerichtet ist. Wähle einen Mandanten oder die Option *ALLE*, wenn das Versandprofil für alle Webshops gelten soll.

| *Auftragsherkunft*
|Wähle deine plentyPOS-Kasse(n) als Auftragsherkunft.

| *Gesperrte Zahlungsarten*
|Wähle die Zahlungsarten, die du für das Versandprofil *Selbstabholung* nicht anbieten möchtest.
|====

[#210]
=== Versandprofil Selbstabholung am Artikel aktivieren

Aktiviere nun das Versandprofil *Selbstabholung* bei den Artikeln, die du über die Kasse verkaufen möchtest.

[.instruction]
Versandprofil Selbstabholung aktivieren:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Öffne den Artikel.
. Wechsele in das Tab *Global*.
. Aktiviere das Versandprofil *Selbstabholung*.
. *Speichere* (icon:save[role="darkGrey"]) die Einstellungen.

Du möchtest das Versandprofil für eine größere Anzahl an Artikeln gleichzeitig aktivieren? Dann nutze die xref:artikel:massenbearbeitung.adoc#100[Artikel-Gruppenfunktion].

[#100]
== Preise für Kassenaufträge verwalten

Um POS-Preise für Varianten zu hinterlegen, benötigst du mindestens einen xref:artikel:preise.adoc#[Verkaufspreis], bei dem die POS-Herkunft der Kasse aktiviert ist. Verkaufspreise erstellst und verwaltest du zentral. Preise für Varianten hinterlegst du, indem du Varianten mit dem Verkaufspreis verknüpfst und einen Preis speicherst.

[#750]
=== Verkaufspreis für Kassenaufträge erstellen

Wenn du bereits Verkaufspreise erstellt hast, die deinen Anforderungen für Kassenaufträge entsprechen, aktiviere bei diesen Verkaufspreisen die Herkunft der Kasse. Gehe sonst wie unten beschrieben vor, um einen neuen Verkaufspreis für Kassenaufträge zu erstellen. Nur die für POS-Herkünfte relevanten Einstellungen werden beschrieben.

[.instruction]
Verkaufspreis für Kassenaufträge erstellen:

. Öffne das Menü *Einrichtung » Artikel » Verkaufspreise*.
. Klicke auf *Neu* (icon:plus-square[role="green"]). +
→ Das Tab *Neu* wird geöffnet.
. Nimm die Einstellungen gemäß <<table-POS-sales-price>> vor.
. *Speichere* (icon:save[role="darkGrey"]) die Einstellungen.

[[table-POS-sales-price]]
.Verkaufspreis für Kassenaufträge erstellen
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Position*
|Gib die Positionsnummer ein. Verkaufspreise werden im Bereich *Verkaufspreise* von Artikelvarianten aufsteigend sortiert.

| *Interner Name DE*
|Gib einen internen Namen ein. Dieser Name wird nur im plentymarkets Backend angezeigt.

| *Externer Name DE*
|Gib einen externen Namen ein. Der externe Name wird im Webshop angezeigt.

| *Ab Menge*
|Gib einen Mengenwert ein Über Verkaufspreise mit verschiedenen Mengenwerten bildest du mengenbezogene Preisstaffelungen in plentymarkets ab.

| *Währung*
|Aktiviere die Währung, in der Kassenaufträge kassiert werden.

| *Preistyp*
|Aktiviere den Preistyp für den Verkaufspreis. +
*UVP* = Aktiviere die Option, wenn der Verkaufspreis ein unverbindlicher Verkaufspreis (UVP) ist. Wird der UVP und ein weiterer Verkaufspreis an der Variante verknüpft, dann wird der UVP im Webshop in rot und durchgestrichen neben dem Verkaufspreis dargestellt. +
*_Hinweis:_* Preise des Typs *UVP* dienen nur dazu, den Preisvergleich zwischen dem UVP und einem Verkaufspreis darzustellen. Varianten können nicht zu diesem UVP-Preis verkauft werden. +
*Aktionspreis* = Aktiviere die Option, um einen Verkaufspreis als Aktionspreis zu kennzeichnen.

| *Mandant*
|Aktiviere die Mandanten (Shops), mit denen der Verkaufspreis verknüpft wird.

| *Land*
|Aktiviere das Land, in dem die Kasse eingesetzt wird.

| *Herkunft*
|Aktiviere eine oder mehrere plentyPOS Auftragsherkünfte, mit denen der Verkaufspreis verknüpft wird.
|====

[#550]
=== Verkaufspreis mit Varianten verknüpfen

Verknüpfe nun den POS-Verkaufspreis mit den Hauptvarianten der Artikel, die du über die Kasse verkaufen möchtest. Verkaufspreise werden von der Hauptvariante an Varianten vererbt. Du kannst Verkaufspreise auch individuell mit Varianten verknüpfen.

[.instruction]
Verkaufspreis mit Hauptvariante verknüpfen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Öffne den Artikel. +
→ Das Tab *Einstellungen* der Hauptvariante wird geöffnet.
. Wähle im Bereich *Verkaufspreise* den Preis aus der Dropdown-Liste.
. Wähle, ob der Preis ein Brutto- oder Nettopreis ist.
. *_Optional:_* Wähle eine Preiskalkulation.
. Klicke auf *Hinzufügen*. +
→ Der Verkaufspreis wird hinzugefügt und in der Liste angezeigt.
. Gib einen Wert in das Feld *Preis* ein.
. *Speichere* (icon:save[role="darkGrey"]) die Einstellungen. +
→ Die Preise werden an die Varianten des Artikels vererbt. Speichere für Varianten mit abweichendem Preis einen eigenen Wert.

[#800]
== Rundungsverhalten für Kassenaufträge festlegen

Beträge werden auf plentyPOS Kassenbelegen grundsätzlich mit 2 Nachkommastellen dargestellt. Über die Einstellungen im plentymarkets Backend steuerst du, ob die Preise in den Aufträge auch im Hintergrund auf 2 Nachkommastellen gerundet oder ob mit 4 Nachkommastellen gerechnet werden soll. Das Rundungsverhalten für Aufträge, die über plentPOS Kassen generiert werden, wird über die folgenden 3 Optionen gesteuert:

.Erforderliche Optionen für Rundungsverhalten bei Kassenaufträgen
[cols="10,1,1"]
|====
|Menü |Option |Mögliche Einstellungen

|Einrichtung » Mandant » [Mandant wählen] » Standorte » [Standort wählen] » Buchhaltung
|Anzahl Nachkommstellen bei Preisen
a|
* 2
* 4

|Einrichtung » Mandant » [Mandant wählen] » Standorte » [Standort wählen] » Buchhaltung
|Nur Gesamtpreise runden
a|
* Ja
* Nein

|Einrichtung » POS » [Mandant wählen] » [Kasse öffnen] » Tab: Beleg
|Identische Auftragspositionen
a|
* Einzeln darstellen
* Zusammenfassen
|====

Aus diesen Einstellungen ergeben sich 6 Einstellungskombinationen:

* Auftragspositionen einzeln darstellen, Einzelpreise auf 2 Nachkommastellen runden
* Auftragspositionen einzeln darstellen, Einzelpreise auf 4 Nachkommastellen runden
* Auftragspositionen einzeln darstellen, Gesamtpreise auf 4 Nachkommastellen runden
* Auftragspositionen zusammenfassen, Einzelpreise auf 2 Nachkommastellen runden
* Auftragspositionen zusammenfassen, Einzelpreise auf 4 Nachkommastellen runden
* Auftragspositionen zusammenfassen, Gesamtpreise auf 4 Nachkommastellen runden

[IMPORTANT]
.Einstellungen beeinflussen Gesamtbeträge
====
Abhängig von den gewählten Einstellungen kommt es zu unterschiedlichen Gesamtbeträgen. Dies wirkt sich beispielsweise auf die Berechnung des Umsatzes im Steuerbericht des xref:pos:pos-kassenbenutzer.adoc#230[Tagesabschlusses] aus. Beachte, dass sich die Abweichungen potenzieren, je mehr Artikel mit Rundungsbedarf pro Auftrag/Beleg verkauft werden.
====

=== Beispielrechnung

<<table-POS-rounding>> zeigt eine Beispielrechnung, um die Rundungsabweichungen zu verdeutlichen, die durch die verschiedenen Einstellungskombinationen entstehen.

Die Beispielrechnung beruht auf den folgenden Daten:

. Berechnungsbasis: Artikel zum Preis von 4,545 Euro
. Rechnung 1: Verkauf von 10 Artikeln
. Rechnung 2: Verkauf von 10 Artikeln mit 5 % Positionsrabatt

[[table-POS-rounding]]
.Beispielrechnung bei einem Artikelpreis mit 4 Nachkommastellen
[cols="2,1,1"]
|====
|Gewählte Einstellungen |Rechnung 1 (4,545 Euro x 10) Gesamtpreis auf Beleg |Rechnung 2 (4,545 Euro x 10 - 5%) Gesamtpreis auf Beleg

|Anzahl Nachkommastellen = 2  +
Auftragspositionen = Einzeln darstellen
|45,50 Euro
|43,20 Euro

|Anzahl Nachkommastellen = 4  +
Nur Gesamtpreise runden = Nein +
Auftragspositionen = Einzeln darstellen
|45,45 Euro
|43,18 Euro

|Anzahl Nachkommastellen = 4 +
Nur Gesamtpreise runden = Ja +
Auftragspositionen = Einzeln darstellen
|45,45 Euro
|43,18 Euro

|Anzahl Nachkommastellen = 2 +
Auftragspositionen = Zusammenfassen
|43,50 Euro
|43,50 Euro

|Anzahl Nachkommastellen = 4 +
Nur Gesamtpreise runden = Nein +
Auftragspositionen = Zusammenfassen
|45,45 Euro
|43,18 Euro

|Anzahl Nachkommastellen = 4 +
Nur Gesamtpreise runden = Ja +
Auftragspositionen = Zusammenfassen
|45,45 Euro
|43,18 Euro
|====

Detaillierte Informationen und weitere Rechnungsbeispiele zum Rundungsverhalten findest du auch auf der Handbuchseite xref:auftraege:buchhaltung.adoc#150[Buchhaltung].

[#95]
== Standardkunden für Kassenaufträge erstellen

Damit Kassenaufträge korrekt in plentymarkets gespeichert werden, muss jedem Auftrag ein Kontakt zugeordnet sein. Dazu erstellst du im plentymarkets Backend einen Kontakt vom Typ *Standardkunde*. Im Folgenden werden nur die Einstellungen werden beschrieben, die für das Erstellen des Standardkunden für Kassenaufträge relevant sind. Allgemeine Informationen zum Erstellen von Kontakten findest du auf der Handbuchseite xref:crm:kontakt-erstellen.adoc#[Kontakt erstellen].

[IMPORTANT]
.Einstellungen für Standardkunden für Kassenaufträge mit Steuerberater abstimmen
====
Kläre im Vorfeld mit deinem Steuerbüro, welche Einstellungen für Standardkunden für Kassenaufträge sinnvoll sind.
====

[.instruction]
Standardkunden für Kassenaufträge erstellen:

. Öffne das Menü *CRM » Kontakte*.
. Klicke auf *Neuen Kontakt erstellen*.
. Nimm die Einstellungen gemäß <<table-POS-default-customer>> vor.
. *Speichere* (icon:save[role="darkGrey"]) die Einstellungen.
. Öffne das Menü *Einrichtung » POS » [Mandant wählen] » [Kasse öffnen] » Grundeinstellungen*.
. Gib die ID des Standardkunden in das Feld *Standardkunde* ein.
. *Speichere* (icon:save[role="darkGrey"]) die Einstellungen.

[[table-POS-default-customer]]
.Standardkunden für Kassenaufträge erstellen
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Firma*
|Gib einen Firmennamen ein, zum Beispiel plentymarkets Kasse.

| *Anrede*
|Wähle die Option *Firma* aus der Dropdown-Liste.

| *Straße; +
PLZ*; +
*Ort*
|Gib Straße, Postleitzahl und Ort ein.

| *Land*
|Wähle das Land aus der Dropdown-Liste, in dem die Kasse eingesetzt wird. Die Standardeinstellung richtet sich nach der Option *Land* im Menü xref:willkommen:schnelleinstieg-basiseinstellungen.adoc#100[Einrichtung » Einstellungen » Stammdaten].

| *Mandant*
|Wähle einen Mandanten aus der Dropdown-Liste, wenn die Kasse nicht dem Standardmandanten zugeordnet ist.

| *Typ*
|Wähle die Option *Kunde* aus der Dropdown-Liste.
|====

[#220]
== Dummy-Artikel erstellen

Im Tagesgeschäft kommt es vor, dass Artikel verkauft werden sollen, für die es keinen Datensatz im System gibt. Zum Beispiel wird häufig für Diversartikel kein Datensatz erstellt. Um diese Artikel trotzdem kassieren zu können, erstellst du Dummy-Artikel. Kassenpersonal fügt dann den Dummy-Artikel zum POS-Warenkorb hinzu und passen den Preis und optional den Namen der Auftragsposition an.

Die folgenden Vorbereitungen sind nötig, um mit Dummy-Artikeln zu arbeiten.

* Einen Dummy-Artikel für jeden Umsatzsteuersatz erstellen, der für die Produkte deines Portfolios relevant sind. Wenn du Artikel mit 19% und 7% verkaufst, benötigst du also zwei Dummy-Artikel.
* Option *Preisabfrage wenn Artikelpreis 0* aktivieren, damit Kassenpersonal den Preis manuell eingeben kann.
* Kassenpersonal Rechte zum Bearbeiten von Preisen erteilen.
* Kassenpersonal Rechte zum Umbenennen von Auftragspositionen erteilen (optional).

Die erforderlichen Einstellungen werden in <<table-POS-dummy-item>> kurz erläutert. Die  Zwischenüberschriften der Tabelle geben an, in welchem Menü du die Einstellung vornimmst.

[[table-POS-dummy-item]]
.Empfohlene Einstellungen für Dummy-Artikel
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+^| *Artikel » Artikel bearbeiten » Neuen Artikel erstellen » Tab: Einstellungen*

| *Beschränkung*
|Wähle die Option *Keinen WB für diese Variante führen*.

| *Preis*
|Wähle den Verkaufspreis für die Kasse gib den Preis *0,00* Euro ein.

| *Umsatzsteuer*
|Gib den Umsatzsteuersatz ein, der für den Dummy-Artikel gelten soll.

2+^| *Einrichtung » POS » [Mandant wählen] » [Kasse öffnen]*

| *Preisabfrage wenn Artikelpreis 0*
|Aktiviere die Option.

2+^| *Einrichtung » Kontoverwaltung » Rollen » [Rolle öffnen] » Rechte » plentymarkets App / plentyPOS*

| *Preis bearbeiten*
|Aktiviere das Recht für das Kassenpersonal, damit das Kassenpersonal den Preis anpassen kann.

| *Artikelposition umbenennen*
|Aktiviere das Recht für das Kassenpersonal, wenn das Kassenpersonal den Namen von Dummy-Artikeln anpassen können soll.
|====

[#2100]
== Mehrzweckgutscheine und Aktionsgutscheine

In plentymarkets sind Mehrzweckgutscheine im Sinne von _Geschenkgutscheinen_ zu verstehen. Es handelt sich dann um einen Mehrzweckgutschein, wenn der Inhaber diesen zur Einlösung gegen Gegenstände oder Dienstleistungen verwenden kann.

Aktionsgutscheine sind dagegen im Sinne von _werblichen Aktionen_ zu verstehen. Es handelt sich dann um einen Aktionsgutschein, wenn der Inhaber zu einem Preisnachlass berechtigt wird, z.B. 20% auf alles außer Tiernahrung.

Obwohl Mehrzweckgutscheine und Aktionsgutscheine unterschiedliche Anwendungsfälle haben, werden beide auf die gleiche Art und Weise in plentymarkets konfiguriert. Deshalb sind beide Themen hier im gleichen Kapitel beschrieben.

Um Mehrzweckgutscheine und Aktionsgutscheine mit plentyPOS anzubieten, sind die folgenden Vorbereitungen im plentymarkets Backend erforderlich:

* Entscheide, xref:auftraege:gutscheine.adoc#artikel-gutscheinzahlung-vorbereiten[welche Artikel aus deinem Sortiment] per Gutschein bezahlbar sein sollen.
* xref:auftraege:gutscheine.adoc#gutscheinartikel-erstellen[Erstelle Gutscheinartikel] mit 0% MwSt., d.h. füge die kaufbaren Geschenkgutscheine deinem Sortiment hinzu.
* xref:auftraege:gutscheine.adoc#kampagne-erstellen[Erstelle eine Kampagne] für deine Gutscheine. Bestimme mit der Option *Gutscheinart*, ob es sich um Mehrzweckgutscheine oder Aktionsgutscheine handelt.
* xref:auftraege:gutscheine.adoc#gutscheinartikel-mit-kampagne-verknuepfen[Verknüpfe deine Gutscheinartikel mit der Kampagne].
* *_Optional:_* xref:pos:pos-einrichten.adoc#850[Generiere Gutschein-Codes] oder speichere deine eigenen Gutschein-Codes im Backend.
* *_Optional:_* Gutscheinvordrucke erstellen und dem Kassenpersonal zur Verfügung stellen.
* *_Optional:_* Gutschein-Codes dem Kassenpersonal zur Verfügung stellen.

[IMPORTANT]
.Vorgehensweise bei mehreren Kassen
====
Du hast mehr als eine Kasse und möchtest mit eigenen Gutschein-Codes arbeiten? Dann teile die ausgedruckten Gutschein-Codes zwischen den Kassen auf oder erstelle für jede Kasse eigene Gutscheinkampagnen und -artikel, damit jeder Gutschein-Code nur einmal verkauft wird.
====

[#830]
=== Kampagne für POS-Mehrzweckgutscheine erstellen

Erstelle nun für den Verkauf von Gutscheinen über plentyPOS eine oder mehrere eigene Kampagnen. Du hast folgende Möglichkeiten:

* Du erstellst eine Kampagne für alle Gutscheine, die du über plentyPOS verkaufst.
* Du erstellst eine Kampagne pro Gutscheinwert. +
*_Beispiel:_* Du möchtest Gutscheine im Wert von 10 Euro, 25 Euro und 50 Euro sowie einen Gutschein verkaufen, bei dem das Kassenpersonal den Wert frei wählen kann. Du erstellst also 3 Kampagnen mit den Rabattwerten 10, 25 und 50 Euro sowie eine Kampagne mit einem beliebigen Rabattwert.

Wenn du mehr als eine Kasse einsetzt und mit eigenen Gutschein-Codes arbeiten möchtest, kann es sinnvoll sein, pro Kasse eigene Kampagnen anzulegen. So erstellst du eine Kampagne für Mehrzweckgutscheine:

[.instruction]
Kampagne für POS-Mehrzweckgutscheine erstellen:

. Öffne das Menü *Aufträge » Gutscheine*.
. Klicke auf *Neue Kampagne*.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<table-POS-gift-card-campaigns>>.
. *Speichere* (icon:save[role="darkGrey"]) die Einstellungen. +
→ Die neue Kampagne wird erstellt und in der Übersicht angezeigt.

[[table-POS-gift-card-campaigns]]
.Einstellungen für POS-Mehrzweckgutschein-Kampagnen
[cols="1,3"]
|====
|Einstellung |Benutzereingabe

2+^|Kampagne

| *Name*
|Gib einen Namen für die Kampagne ein. +
*_Tipp_*: Der Name sollte den Namen der Kasse und den Gutscheinwert enthalten.

| *Beschreibung*
|Gib optional eine Beschreibung ein.

| *Konzept: Code*
|Wähle die Option *Mehrere Codes*, damit jeder Gutschein-Code nur einmal eingelöst werden kann und Restbeträge bei Teileinlösungen korrekt berechnet werden.

| *Konzept: Einlösungen*
|Wähle die Option *Einlösung bis Wert aufgebraucht ist*.

| *Nutzung*
| Wähle eine der Optionen *Einzelbestellungen*, xref:auftraege:scheduler.adoc#[Abonnements] oder beide.

| *Mindestbestellwert*
|Gib keinen Wert ein, da Mehrzweckgutscheine wie Zahlungsmittel zu behandeln sind und keinem Mindestbestellwert unterliegen dürfen.

2+^|Gültigkeiten

| *Startdatum*
|Gib das Datum ein, ab dem die Kampagne aktiv ist.

| *Enddatum*
|Gib das Datum ein, bis zu dem die Kampagne aktiv ist.

| *Code-Gültigkeit in Wochen*
|Gib den Wert *0* ein.

2+^|Gutschein

| *Gutscheintyp*
|Wähle die Option *Gutschein*.

| *Gutscheinart*
|Wähle die Option *Mehrzweckgutschein*.

| *Code-Länge*
|Wähle die Zeichenlänge des Gutschein-Codes.

| *Rabattart*
|Wähle die Option *Festbetrag*.

| *Rabattwert*
|Gib den Gutscheinwert ein, zum Beispiel 10,00 = 10 Euro. +
*_Hinweis:_* Ändere den Rabattwert nicht mehr, nachdem der erste Gutschein verkauft wurde. +
*_Tipp:_* Dieser Wert wird Codes automatisch zugewiesen, wenn im Tab *Codes* über *Gutschein-Codes manuell generieren* Codes generiert werden, ohne dass ein Betrag in das Feld *Wert* eingegeben wird. +

| *Inkl. Versandkosten*
|Aktiviere diese Option nicht.

2+^|Filter

| *Artikel über Preisportale*
|Wähle die Option *Nicht erlauben*, da plentyPOS nicht an Preisportale angebunden ist.

| *Kategorien*
|Wähle die Kategorien, in denen der Gutschein einlösbar sein soll. Die Auswahl gilt auch für alle Unterkategorien einer markierten Kategorie.

| *Artikel*
|Gib keinen Wert ein, da Mehrzweckgutscheine wie Zahlungsmittel zu behandeln sind und nicht auf bestimmte Artikel beschränkt werden dürfen.

| *Mandanten (Shops)*
|Wähle die Mandanten (Shops), für die die Gutscheine der Kampagne gelten sollen.

| *Kundenklassen*
|Wähle die Kundenklassen, für die die Gutscheine der Kampagne gelten sollen.

| *Kundentypen*
|Wähle die Kundentypen, für die die Gutscheine der Kampagne gelten sollen.
|====

[#850]
=== Gutschein-Codes verwalten

Mehrzweckgutscheine werden in plentyPOS eingelöst, indem das Kassenpersonal den Gutschein-Code eingibt. Damit der Gutschein-Code eingelöst werden kann, muss der Code zum Zeitpunkt der Einlösung in einer Kampagne des plentymarkets Backends gespeichert sein.

Aus Sicht des Kassenpersonals ergeben sich aus den Konfigurationsmöglichkeiten in plentymarkets drei mögliche Szenarien beim Verkauf eines Gutscheins:

* Der Gutschein-Code wird automatisch von der Kasse generiert.
* Das Kassenpersonal hat eine Liste mit Gutschein-Codes pro Gutscheinwert, die in plentymarkets gespeichert sind. Die Kassenkraft gibt einen Code ein. Der Gutscheinwert wird abgerufen.
* Das Kassenpersonal hat eine Liste mit Gutschein-Codes, die nicht in plentymarkets gespeichert sind. Die Kassenkraft gibt einen Code und einen Gutscheinwert ein.

Nachfolgend wird beschrieben, wie du Gutschein-Codes für diese verschiedenen Szenarien konfigurierst.

[#2200]
==== Automatisch Gutschein-Code beim Verkauf generieren

Am wenigsten administrativen Aufwand hast du, wenn Kassenbenutzer:innen beim Verkauf eines Gutscheins über plentyPOS einen zufälligen xref:pos:pos-kassenbenutzer.adoc#250[Gutschein-Code generieren]. Beim Hochladen des Kassenauftrags werden der Gutschein-Code und der damit verbundene Gutscheinwert in die Kampagne importiert, die mit dem Gutscheinartikel verknüpft ist. Der Gutschein-Code wird auf dem Beleg ausgegeben und optional wird ein Gutscheinbeleg erstellt. Das Kassenpersonal kann den Gutschein-Code außerdem per Hand auf einem dekorativen Gutscheinvordruck vermerken.

[#2300]
==== Mit eigenen Gutschein-Codes arbeiten

Wenn du Kassenpersonal Gutschein-Codes aushändigen möchtest, die beim Kassieren eingegeben werden sollen, erhöht sich der administrative Aufwand. Du hast aber auch mehr Möglichkeiten, dekorative Gutscheinvordrucke zu erstellen, auf denen nur der Gutschein-Code oder aber der Gutschein-Code und der Gutscheinwert bereits vermerkt sind. Das Kassenpersonal gibt dann einfach diese Gutscheinvordrucke aus.

Gutschein-Codes können entweder vor dem Verkauf oder beim Verkauf des Gutscheins im System gespeichert werden.

Um Gutschein-Codes vor dem Verkauf im plentymarkets Backend zu speichern:

* Du generierst vor dem Verkauf Gutschein-Codes mit festem Wert in der Kampagne.
* Du speicherst vor dem Verkauf eigene Gutschein-Codes mit festem Wert in der Kampagne.

In diesen Fällen stellst du dem Kassenpersonal eine Liste mit diesen Gutschein-Codes und dem dafür gespeicherten Gutscheinwert bereit.

Um Gutschein-Codes beim Verkauf zu speichern:

* Kassenbenutzer:innen geben beim Verkauf des Gutscheins einen noch nicht in plentymarkets gespeicherten Gutschein-Code und den Gutscheinwert ein.

In diesen Fällen stellst du dem Kassenpersonal eine Liste mit den Gutschein-Codes bereit. Den Wert des Gutscheins gibt das Kassenpersonal beim Kassieren als Preis für den Gutschein ein.

[IMPORTANT]
.Erstellungsdatum beachten
====
Du hast bereits in plentymarkets generierte Gutschein-Codes an das Kassenpersonal ausgehändigt und möchtest weitere Gutschein-Codes generieren? Dann achte auf das Erstellungsdatum. In plentymarkets werden Gutschein-Codes nicht als verkauft gekennzeichnet. Um Gutschein-Codes nicht doppelt zu verkaufen, bringst du nur die Codes in Umlauf, die du an einem bestimmten Datum erstellt hast. Am einfachsten geht das, indem du Gutscheine im Menü *Aufträge » Gutscheine* generierst und diese Gutschein-Codes als CSV-Datei exportierst. Die CSV-Datei filterst du nach dem Erstellungsdatum, also nach der Spalte *GeneriertAm*. So erhältst du nur die neuen Gutschein-Codes.
====

[#2400]
==== Gutschein-Codes manuell generieren

Mit dem Gutschein-Generator im Tab *Codes* einer Kampagne erzeugst du einen oder mehrere automatisch generierte Gutschein-Codes.

[.instruction]
Gutschein-Codes mit festem Wert manuell generieren:

. Öffne das Menü *Aufträge » Gutscheine*.
. Klicke auf die Kampagne, für die du Gutschein-Codes erzeugen möchtest.
. Öffne das Tab *Codes*.
. Gib im Bereich *Gutschein-Codes manuell generieren* links die gewünschte Anzahl an Gutschein-Codes ein.
. *_Optional:_* Gib in das Feld *Wert* den Wert ein, der dem Gutschein-Code zugewiesen werden soll. +
*_Tipp:_* Wenn du das Feld *Wert* leer lässt, wird dem Code der Rabattwert der Kampagne zugewiesen.
. *Speichere* (icon:save[role="darkGrey"]) die Eingabe. +
→ Die Gutschein-Codes werden erzeugt und zur Liste der Gutschein-Codes hinzugefügt.
. Klicke auf *Exportieren*, um die Gutschein-Codes zu exportieren. +
→ Ein CSV-Export aller Gutschein-Codes der Kampagne wird erstellt.
. Filtere die Spalte *GeneriertAm* der CSV-Datei nach dem aktuellen Datum. So erhältst du eine Liste aller neu erstellten Gutschein-Codes. +
. Stelle dem Kassenpersonal die Gutschein-Codes und Informationen zum Wert der Codes zur Verfügung. +
*_Hinweis:_* Bringe Gutschein-Codes nicht mehrfach in Umlauf. Teile bei mehreren Kassen die Gutschein-Codes entweder auf oder erstelle separate Kampagnen pro Kasse.

[#2500]
==== Eigene Gutschein-Codes mit festem Wert speichern

Statt Gutschein-Codes in plentymarkets zu generieren, kannst du auch vor dem Verkauf eigene Gutschein-Codes in plentymarkets speichern. Gültige Zeichen für Gutschein-Codes sind Klein- und Großbuchstaben, Ziffern, Unterstriche (_) und Bindestriche (-).

[.instruction]
Eigenen Gutschein-Code mit festem Wert speichern:

. Öffne das Menü *Aufträge » Gutscheine*.
. Klicke auf die Kampagne, für die du einen Gutschein-Code speichern möchtest.
. Öffne das Tab *Codes*.
. Gib im Bereich *Gutschein-Code manuell eintragen* rechts einen Code mit zwischen 6 und 24 Zeichen ein.
. *Speichere* die Eingabe. +
→ Der Gutschein-Code wird gespeichert und zur Liste der Gutschein-Codes hinzugefügt. +
*_Tipp:_* Mit dem Datenformat *CampaignCoupon* importierst du mehrere Gutschein-Codes gleichzeitig. Als Gutscheinwert wird dabei der *Rabattwert* importiert. Lege also pro Gutscheinwert eine eigene Kampagne an, wenn du mit dem Datenformat arbeiten möchtest.
. Stelle dem Kassenpersonal die Gutschein-Codes und Informationen zum Wert der Codes zur Verfügung. +
*_Hinweis:_* Bringe Gutschein-Codes nicht mehrfach in Umlauf. Teile bei mehreren Kassen die Gutschein-Codes entweder auf oder erstelle separate Kampagnen pro Kasse.

[#3900]
=== Drucken und Speichern von Gutscheinbelegen aktivieren

Optional kann ein Gutscheinbeleg erstellt und gedruckt werden. Der Gutscheinbeleg enthält die folgenden Informationen zum Gutschein:

* Gutscheinwert
* Gutschein-Code
* Bei Teileinlösung:
	* Eingelöster Betrag
	* Restbetrag

[.instruction]
Drucken von Gutscheinbelegen aktivieren:

. Öffne das Menü *Einrichtung » POS » [Mandant wählen]*.
. Öffne die Kasse.
. Wechsele in das Tab *Beleg*.
. Aktiviere die Option *Gutscheinbeleg drucken und speichern*.
. *Speichere* (icon:save[role="darkGrey"]) die Einstellungen. +
→ Beim Verkauf oder einer Teileinlösung eines Gutscheins wird ein Gutscheinbeleg erstellt. +
→ Der Gutscheinbeleg wird im Dokumentenarchiv gespeichert. +
→ Wenn die Option *Automatisches Drucken* im Menü *plentymarkets App » Einstellungen » POS* aktiviert ist, wird der Gutscheinbeleg nach dem Kassenbeleg ausgedruckt. +
→ Wenn *Automatisches Drucken* im Menü *plentymarkets App » Einstellungen » POS* nicht aktiviert ist, können Kassenbenutzer:innen den Gutscheinbeleg nach Abschluss des Auftrags manuell drucken. +
*_Hinweis:_* Beim Verkauf eines Gutscheins wird der Gutschein-Code unabhängig von der gewählten Einstellung immer auf dem normalen Kassenbeleg ausgegeben.


[#840]
=== Gutscheinartikel erstellen

Erstelle nun einen oder mehrere Gutscheinartikel. Da die Kampagnen-ID auf der Artikelebene zugeordnet wird, kannst du bei Mehrzweckgutscheinen nicht mit Varianten arbeiten. Detaillierte Informationen zum Erstellen von Artikeln findest du auf der Handbuchseite xref:artikel:neue-artikel.adoc#[Neue Artikel anlegen]. Hier werden nur die Einstellungen beschrieben, die du speziell zum Erstellen von Gutscheinartikeln benötigst.

==== Gutscheinartikel mit festem Preis erstellen

Bei Gutscheinartikeln mit festem Preis erfolgt beim Kassieren keine Preisabfrage. Du beschleunigst also den Kassiervorgang, bist aber auch weniger flexibel.

Beachte bei vorhandenen Gutschein-Codes:

* Der Wert des vorhandenen Gutschein-Codes muss mit dem Preis des Artikels übereinstimmen. Der Gutscheinartikel muss also mit der Kampagne verknüpft sein, die die Gutschein-Codes mit den korrekten Werten enthält. Bei einer Kampagne pro Gutscheinwert wird also jede Kampagne mit nur einem Artikel verknüpft. Bei einer Kampagne mit verschiedenen Gutscheinwerten wird diese Kampagne mit mehreren Gutscheinartikeln verknüpft.

[.instruction]
Gutscheinartikel mit festem Preis erstellen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Klicke auf *Neu* (icon:plus-square[role="green"]). +
→ Das Tab *Neuer Artikel* wird geöffnet.
. Wähle den Typ *Standard*.
. Gib einen Namen ein. +
*_Tipp_*: Der Name sollte den Gutscheinwert enthalten.
. Gib als Inhalt *1 Stück* ein.
. Wähle eine Kategorie.
. Wähle einen Verkaufspreis aus der Dropdown-Liste. +
*_Hinweis_*: Der Verkaufspreis muss mit der Auftragsherkunft der Kasse verknüpft sein.
. Gib als Preis den Gutscheinwert ein.
. *Speichere* (icon:save[role="darkGrey"]) die Einstellungen. +
→ Der Artikel wird erstellt und zur weiteren Bearbeitung geöffnet.
. Nimm die weiteren Einstellungen vor. Beachte dazu die Erläuterungen in <<table-POS-multipurpose-coupon-item-settings>>.
. *Speichere* (icon:save[role="darkGrey"]) die Einstellungen.

[#2600]
==== Gutscheinartikel mit flexiblem Wert erstellen

Gutscheinartikel mit flexiblem Wert sind Artikel mit einem Preis von 0,00 Euro. Den Preis, zu dem der Gutscheinartikel tatsächlich an der Kasse verkauft wird, steuerst du auf zwei verschiedene Arten:

* Beim Kassieren gibt das Kassenpersonal einen in plentymarkets vorhandenen Gutschein-Code ein. Der Wert dieses Gutschein-Codes wird zum Preis des Artikels.
* Beim Kassieren generiert das Kassenpersonal entweder automatisch einen Code oder speichert einen eigenen Gutschein-Code und gibt einen Gutscheinwert ein.

[.instruction]
Gutscheinartikel mit flexiblem Preis erstellen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Klicke auf *Neu* (icon:plus-square[role="green"]). +
→ Das Tab *Neuer Artikel* wird geöffnet.
. Wähle den Typ *Standard*.
. Gib einen Namen ein.
. Gib als Inhalt *1 Stück* ein.
. Wähle eine Kategorie.
. Wähle einen Verkaufspreis aus der Dropdown-Liste. +
*_Hinweis_*: Der Verkaufspreis muss mit der Auftragsherkunft der Kasse verknüpft sein.
. Gib als Preis *0,00* Euro ein.
. *Speichere* (icon:save[role="darkGrey"]) die Einstellungen. +
→ Der Artikel wird erstellt und zur weiteren Bearbeitung geöffnet.
. Nimm die weiteren Einstellungen vor. Beachte dazu die Erläuterunngen in <<table-POS-multipurpose-coupon-item-settings>>.
. *Speichere* (icon:save[role="darkGrey"]) die Einstellungen. +
→ *_Mit vorhandenem Gutschein-Code:_* Das Kassenpersonal gibt den Gutschein-Code einer Kampagne ein, die mit dem Artikel verknüpft ist. Der Artikel wird mit dem Wert des Gutschein-Codes berechnet. +
→ *_Ohne vorhandenen Gutschein-Code:_* Das Kassenpersonal wird aufgefordert, einen Preis einzugeben, wenn der Artikel in den POS-Warenkorb gelegt wird.

[[table-POS-multipurpose-coupon-item-settings]]
.Artikeleinstellungen für Mehrzweckgutscheine mit festem und flexiblem Wert
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+^| *Artikel » Artikel bearbeiten » Artikel öffnen » Variante öffnen » Tab: Einstellungen*

| *Aktiv*
|Aktiviere die Option.

| *Beschränkung*
|Wähle die Option *Keine*.

| *Umsatzsteuer*
|Wähle die Option *0%*.

2+^| *Artikel » Artikel bearbeiten » Artikel öffnen » Variante öffnen » Tab: Verfügbarkeit*

| *Märkte*
|Wähle die Kasse(n) aus der Dropdown-Liste, über die die Gutscheinartikel verkauft werden sollen.

| *Mandant*
|Wähle den Mandant, der der Kasse zugeordnet ist.

2+^| *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Felder*

| *Kampagne ID*
|Gib die ID der Gutscheinkampagne ein, um den Artikel mit der Kampagne zu verknüpfen.
|====

[#2700]
=== Gutscheinkarten verkaufen und einlösen

Eine praxisnahe und einfache Methode im Umgang mit Gutscheinen ist der Verkauf von Gutscheinkarten in variabler Höhe direkt an der Kasse. So kann dein Kassenpersonal stets schnell und umkompliziert Gutscheine in der von Kund:innen gewünschten Höhe direkt an der Kasse verkaufen.
Nimm dazu zuerst die folgenden vorbereitenden Einstellungen vor:

* Sofern noch nicht vorhanden, musst du eine xref:pos:pos-einrichten.adoc#830[geeignete Kampagne] in plentymarkets erstellen.
* Lege dir einen xref:pos:pos-einrichten.adoc#2600[Gutscheinartikel mit flexiblem Wert] für diese Art von Gutscheinen in plentymarkets an.
* Füge diesen Gutscheinartikel dem xref:pos:pos-einrichten.adoc#60[Favoritenbereich] deiner Kasse hinzu.
* Beschaffe dir link:http://lmgtfy.com/?q=Barcode-Karten+Druck[Barcode-Karten^] mit vorgefertigten Codes. Die meisten Anbieter erwarten eine CSV-Datei, die die einzelnen Codes enthält, die auf den Karten platziert werden sollen, sowie eine Layout-Vorlage im Photoshop- oder Adobe-Illustrator-Format für das Rahmendesign.

[TIP]
.Präfix bei Gutscheincode voranstellen
====
Wenn du deinen Gutscheincodes das Präfix *#* voranstellst, beschleunigst du später den Einlösungsvorgang, weil plentyPOS dadurch direkt beim Scannen erkennt, dass es sich um einen Gutschein handelt. So musst du nicht erst manuell die Schaltfläche für den Gutscheindialog betätigen.
====

Das folgende Video bietet dir einen Überblick über die einzelnen Schritte, die zum Verkauf von Gutscheinkarten notwendig sind.

.Gutscheinverkauf
video::382590843[vimeo]

Du möchtest wissen, wie die Einlösung der verkauften Gutscheinkarten abläuft? Im unten verlinkten Video findest du genauere Informationen.

.Gutscheineinlösung
video::382590675[vimeo]

[#3800]
=== Berechtigungen für Gutscheinverkauf erteilen

Personen mit Admin-Rechten haben standardmäßig die Berechtigungen, Mehrzweckgutscheine zu erstellen. Benutzern ohne Admin-Konto müssen diese Berechtigungen separat erteilt werden.

:rights-purpose: Gutscheine verkaufen können
:right-one: pass:quotes[*CRM > Kampagne > Code > Lesen*]
:right-two: pass:quotes[*CRM > Kampagne > Code > Erstellen*]
:right-three: pass:quotes[*CRM > Kampagne > Code > Löschen*]

include::_includes:partial$rights.adoc[]

[#2710]
=== Besonderheiten beim Verkauf von Mehrzweckgutscheinen

* Der Umsatz erhöht sich beim Verkauf des Mehrzweckgutscheins nicht.
* Verkaufte Gutscheine werden auf dem Tagesbericht separat ausgewiesen. Der Barbestand wird nur erhöht, wenn der Gutschein bar bezahlt wurde.

[#2800]
=== Besonderheiten beim Einlösen von Mehrzweckgutscheinen

* Der Wert des Mehrzweckgutscheins wird vom Gesamtbetrag inkl. Steuern abgezogen.
* Der Umsatz erhöht sich um den eingelösten Gutscheinbetrag.
* Auf dem Tagesbericht wird der eingelöste Gutscheinwert mit der Zahlungsart *Gutschein* ausgewiesen.
* Der Barbestand der Kasse erhöht sich durch die Einlösung des Gutscheins nicht.

[#3600]
== Retouren vorbereiten

In den Kasseneinstellungen wählst du einen Standard-Reparaturlagerort für Retouren und legst in den Berechtigungen fest, wer Retouren durchführen darf. Wenn du Retourenbeträge nur in bar auszahlen möchtest, sind keine weiteren Einstellungen nötig, um Retouren über plentyPOS abzuwickeln. Beachte die xref:pos:pos-einrichten.adoc#2000[Hinweise zu Retouren]. Wenn du die Möglichkeit haben möchtest, den Retourenbetrag als Gutschein auszuzahlen, bereitest du außerdem xref:pos:pos-einrichten.adoc#3100[Retourengutscheine] vor.


[#2000]
=== Hinweise zu Retouren

Beachte die folgenden Hinweise zu Retouren:

* Retourenbeträge können in bar, per Kartenzahlung an Kund:innen oder in Form eines Gutscheins ausgezahlt werden.
* Mehrzweckgutscheine können nicht zurückgegeben werden.
* Über die Kasse können für alle im System gespeicherten Aufträge Retouren gebucht werden. Es können also auch Artikel aus Aufträgen mit anderen Herkünften zurückgegeben werden. Die Entscheidung, ob Artikel zurückgeben werden können, trifft das Kassenpersonal. Informiere deshalb das Kassenpersonal, ob und wenn ja welche Herkünfte von der Retoure ausgeschlossen sind.
* Als Lagerort für Retourenartikel wird Kassenkräften standardmäßig der Lagerort angezeigt, der im Tab *Grundeinstellungen* der Kasse als *Standard-Reparturlagerort* festgelegt ist. Kassenkräfte können optional einen anderen Lagerort für die Retourenartikel wählen. Die möglichen Lagerorte werden in der folgenden Reihenfolge angezeigt:
  .. Lagerort aus Auftrag = Der Lagerort, an dem der Artikel lag, als er verkauft wurde.
  .. Standard-Reparaturlagerort = Der im Tab *Grundeinstellungen* der Kasse festgelegte *Reparturlagerort*.
  .. Lagerortvorschläge = Die Lagerortvorschläge der Lager, die mit der Variante verknüpft sind.
  .. Verwendete Lagerorte = Die Lagerorte, in denen die Variante bereits lagert.
Informiere das Kassenpersonal darüber, an welchen Lagerort Retouren gebucht werden sollen.
* Bei Retouren für einen Hauptauftrag mit Versandkosten entscheidet das Kassenpersonal, ob die Versandkosten erstattet werden. Schule deshalb das Kassenpersonal, damit bekannt ist, in welchen Fällen die Versandkosten erstatten werden sollen.
* Weise das Kassenpersonal an, zurückgegebene Artikel auf dem Kaufbeleg durchzustreichen. So verhinderst du, dass Artikel mehrmals zurückgegeben werden.
* Bei Kauf auf Rechnung oder Anzahlungen bei einer Retoure erst Geld aushändigen, wenn der Preis der zurückgegebenen Artikel höher ist als der Betrag, der bisher bezahlt wurde.
* Der Retourenbetrag kann statt in bar auch in Form eines Gutscheins ausgezahlt werden. Wenn du diese Möglichkeit nutzen möchtest, schule das Kassenpersonal, damit bekannt ist, in welchen Fällen der Retourenbetrag in bar und in welchen Fällen der Betrag als Gutschein ausgezahlt werden soll.

[#3100]
=== Retourengutscheine vorbereiten

Statt den Retourenbetrag in bar auszuzahlen, kann ein Gutschein über den Retourenbetrag erstellt und ausgehändigt werden. Bei einer solchen Retoure wird der Retourenbetrag nur theoretisch ausgezahlt und sofort ein Gutschein über denselben Betrag gekauft. Bei einer Retoure mit Gutschein werden also eine Retoure, eine Gutschrift und ein neuer Auftrag erstellt.

Um Gutscheine für Retouren zu erstellen, sind die folgenden Vorbereitungen im plentymarkets Backend erforderlich:

* Gutscheinkampagne mit Gutscheinart *Mehrzweckgutschein* erstellen.
* Gutscheinartikel mit 0% MwSt. erstellen und mit der Gutscheinkampagne verknüpfen.
* Gutscheinartikel für Retouren mit der Kasse verknüpfen.
* Berechtigungen für Kassenpersonal ohne Admin-Konto erteilen.


Diese Schritte werden nachfolgend kurz erläutert. Eine detaillierte Anleitung zum Erstellen von Kampagnen und Gutscheinen findest du auf der Handbuchseite xref:auftraege:gutscheine.adoc#[Gutscheine].


[#3200]
==== Kampagne für Gutscheine aus Retouren erstellen

Erstelle eine Kampagne für Gutscheine aus Retouren.

[.instruction]
Kampagne für Gutscheine aus Retouren erstellen:

. Öffne das Menü *Aufträge » Gutscheine*.
. Klicke auf *Neue Kampagne*.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<table-POS-refund-campaign>>.
. *Speichere* (icon:save[role="darkGrey"]) die Einstellungen. +
→ Die neue Kampagne wird erstellt und in der Übersicht angezeigt.

[[table-POS-refund-campaign]]
.Einstellungen für Gutscheine aus Retouren
[cols="1,3"]
|====
|Einstellung |Eingabe

2+^|Kampagne

| *Name*
|Gib einen Namen für die Kampagne ein.

| *Beschreibung*
|Gib optional eine Beschreibung ein.

| *Konzept: Code*
|Wähle die Option *Mehrere Codes*.

| *Konzept: Einlösungen*
|Wähle die Option *Einlösung bis Wert aufgebraucht ist*.

| *Nutzung*
|Wähle eine der Optionen *Einzelbestellungen* oder xref:auftraege:scheduler.adoc#[Abonnements] oder beides.

| *Mindestbestellwert*
|Gib keinen Wert ein.

2+^|Gültigkeiten

| *Startdatum*
|Gib das Datum ein, ab dem die Kampagne aktiv ist.

| *Enddatum*
|Gib das Datum, bis zu dem die Kampagne aktiv ist.

| *Code-Gültigkeit in Wochen*
|Gib *0* ein.

2+^|Gutschein

| *Gutscheintyp*
|Wähle die Option *Gutschein*.

| *Gutscheinart*
|Wähle die Option *Mehrzweckgutschein*.

| *Code-Länge*
|Wähle die Zeichenlänge des Gutschein-Codes.

| *Rabattart*
|Wähle die Option *Festbetrag*.

| *Rabattwert*
|Gib einen Gutscheinwert ein, zum Beispiel 1,00.

| *Inkl. Versandkosten*
|Aktiviere die Option nicht.

2+^|Filter

| *Artikel über Preisportale*
|Wähle die Option *Nicht erlauben*.

| *Kategorien*
|Wähle die Kategorien, in denen der Gutschein einlösbar sein soll. Die Auswahl gilt auch für alle Unterkategorien einer markierten Kategorie.

| *Artikel*
|Gib keinen Wert ein.

| *Mandanten (Shops)*
|Wähle die Mandanten (Shops), für die die Gutscheine der Kampagne gelten sollen.

| *Kundenklassen*
|Wähle die Kundenklassen, für die die Gutscheine der Kampagne gelten sollen.

| *Kundentypen*
|Wähle die Kundentypen, für die die Gutscheine der Kampagne gelten sollen.
|====

[#3300]
==== Gutschein-Codes verwalten

Die Gutschein-Codes für Gutscheine aus Retouren verwaltest du genauso wie andere Gutschein-Codes. Du hast folgende Möglichkeiten:

* <<#2200, Die Kasse generiert automatisch einen Gutschein-Code.>>
* <<#2300, Die Kassenkraft gibt einen Code ein, der noch nicht in plentymarkets gespeichert ist.>>


[#4000]
==== Drucken und Speichern von Gutscheinbelegen aktivieren

Optional kann ein Gutscheinbeleg erstellt und gedruckt werden. Der Gutscheinbeleg enthält die folgenden Informationen zum Gutschein:

* Gutscheinwert
* Gutschein-Code
* Bei Teileinlösung:
	* Eingelöster Betrag
	* Restbetrag

[.instruction]
Drucken von Gutscheinbelegen aktivieren:

. Öffne das Menü *Einrichtung » POS » [Mandant wählen]*.
. Öffne die Kasse.
. Wechsele in das Tab *Beleg*.
. Aktiviere die Option *Gutscheinbeleg drucken und speichern*.
. *Speichere* (icon:save[role="darkGrey"]) die Einstellungen. +
→ Beim Verkauf oder einer Teileinlösung eines Gutscheins wird ein Gutscheinbeleg erstellt. +
→ Der Gutscheinbeleg wird im Dokumentenarchiv gespeichert. +
→ Wenn die Option *Automatisches Drucken* im Menü *plentymarkets App » Einstellungen » POS* aktiviert ist, wird der Gutscheinbeleg nach dem Kassenbeleg ausgedruckt. +
→ Wenn *Automatisches Drucken* im Menü *plentymarkets App » Einstellungen » POS* nicht aktiviert ist, können Kassenbenutzer:innen den Gutscheinbeleg nach Abschluss des Auftrags manuell drucken. +
*_Hinweis:_* Beim Verkauf eines Gutscheins wird der Gutschein-Code unabhängig von der gewählten Einstellung immer auf dem normalen Kassenbeleg ausgegeben.

[#840b]
==== Gutscheinartikel für Retouren erstellen

Erstelle einen Gutscheinartikel mit einem Preis von 0,00 Euro. Hier werden nur die Einstellungen beschrieben, die du zum Erstellen von Gutscheinartikeln für Gutscheine aus Retouren benötigst.

[.instruction]
Gutscheinartikel für Retouren erstellen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Klicke auf *Neu* (icon:plus-square[role="green"]). +
→ Das Tab *Neuer Artikel* wird geöffnet.
. Wähle den Typ *Standard*.
. Gib einen Namen ein.
. Gib als Inhalt *1 Stück* ein.
. Wähle eine Kategorie.
. Wähle einen Verkaufspreis aus der Dropdown-Liste. +
*_Hinweis_*: Der Verkaufspreis muss mit der Auftragsherkunft der Kasse verknüpft sein.
. Gib als Preis *0,00* Euro ein.
. *Speichere* (icon:save[role="darkGrey"]) die Einstellungen. +
→ Der Artikel wird erstellt und zur weiteren Bearbeitung geöffnet.
. Nimm die weiteren Einstellungen vor. Beachte dazu die Erläuterungen in <<table-POS-refunds-gift-cards-item-settings>>.
. *Speichere* (icon:save[role="darkGrey"]) die Einstellungen.
. Notiere dir die ID der Variante.

[[table-POS-refunds-gift-cards-item-settings]]
.Artikeleinstellungen für Gutscheine für Retouren
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+^| *Artikel » Artikel bearbeiten » Artikel öffnen » Variante öffnen » Tab: Einstellungen*

| *Aktiv*
|Aktiviere die Option.

| *Beschränkung*
|Wähle die Option *Keine*.

| *Umsatzsteuer*
|Wähle die Option *0%*.

2+^| *Artikel » Artikel bearbeiten » Artikel öffnen » Variante öffnen » Tab: Verfügbarkeit*

| *Märkte*
|Wähle die Kasse(n) aus der Dropdown-Liste.

| *Mandant*
|Wähle den Mandant der Kasse.

2+^| *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Felder*

| *Kampagne ID*
|Gib die ID der Gutscheinkampagne ein, um den Artikel mit der Kampagne zu verknüpfen.
|====

[#3400]
==== Gutscheinartikel für Retouren mit Kasse verknüpfen

[.instruction]
Gutscheinartikel für Retouren mit Kasse verknüpfen:

. Öffne das Menü *Einrichtung » POS » [Mandant wählen]*.
. Öffne die Kasse. +
→ Das Tab *Grundeinstellungen* wird angezeigt.
. Aktiviere die Option *Gutschein über Retourenbetrag erzeugen*. +
. Gib in das Feld *Varianten-ID des Retourengutscheins* die Varianten-ID des Retourengutscheins ein. +
→ Der Gutscheinartikel wird bei Retouren automatisch gewählt.


[#3700]
==== Berechtigungen für Retourengutscheine erteilen

Personen mit Admin-Rechten haben standardmäßig die Berechtigung, Retourengutscheine zu erstellen. Personen ohne Admin-Konto müssen diese Berechtigungen separat erteilt werden.

:rights-purpose: Retourengutscheine erstellen können
:right-one: pass:quotes[*CRM > Kampagne > Code > Lesen*]
:right-two: pass:quotes[*CRM > Kampagne > Code > Erstellen*]
:right-three: pass:quotes[*CRM > Kampagne > Code > Löschen*]

include::_includes:partial$rights.adoc[]

[#3500]
==== Besonderheiten bei Gutscheinen aus Retouren

* Im Kassenjournal wird ein Gutschein aus einer Retoure als neuer Auftrag mit dem Vermerk *Aus Retoure erzeugter Gutschein* dargestellt. Wie bei der Barauszahlung wird eine Gutschrift erstellt. Der Barbestand wird für die Gutschrift reduziert, für den neuen Auftrag jedoch wieder erhöht und bleibt somit gleich.
* Auf dem Tagesbeleg wird auch ein als Gutschein ausgezahlter Retourenbetrag als Bar-Retoure aufgeführt.
* Gutscheine aus einer Retoure werden auf dem Tagesbericht als verkaufte Gutscheine ausgewiesen. Der Barbestand bleibt gleich.

[#3000]
== Warenausgang automatisch buchen

Der Warenbestand wird nicht automatisch verringert, wenn du einen Artikel verkaufst. Erstelle die unten beschriebene Ereignisaktion, um Waren automatisch auszubuchen, wenn ein Kassenauftrag erstellt wird. Weitere Informationen zum Verwalten von Warenbestand findest du auf der Handbuchseite xref:warenwirtschaft:waren-ausbuchen.adoc#[Waren ausbuchen].

include::_includes:partial$event-procedure.adoc[]

[[table-POS-event-procedure-outgoing-items]]
.Ereignisaktion zum automatischen Buchen des Warenausgangs beim Erstellen eines Kassenauftrags
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

| *Ereignis*
| *Dokumente: Kassenbeleg generiert*
|

| *Filter 1*
| *Auftrag &gt; Auftragstyp*
| *Auftrag*

| *Filter 2*
| *Auftrag &gt; Herkunft*
|Wähle die Kassen, für die Warenausgang gebucht werden soll.

| *Aktion*
| *Auftrag &gt; Warenausgang buchen*
|
|====

[#230]
== Kasse mit Gerät verbinden

Verbinde nun die Kasse mit dem Gerät, auf dem die Kasse betrieben werden soll.

=== Kasse mit Gerät koppeln

Gehe wie unten beschrieben vor, um eine Kasse mit dem Gerät zu koppeln, auf dem die Kasse betrieben werden soll.

[IMPORTANT]
.Automatische Datums- und Zeiteinstellung aktivieren
====
Damit Kassenaufträge und Tagesabschlüsse ordnungsgemäß mit dem plentymarkets Backend synchronisiert werden, müssen Datum und Uhrzeit des Geräts stets korrekt eingestellt sein. Deshalb empfehlen wir, am Gerät die Einstellung zur automatischen Aktualisierung von Datum und Uhrzeit zu aktivieren. So wird vermieden, dass zeitliche Unstimmigkeiten in den Tagesabschlüssen oder bei anderen Belegen auftreten.
====

[.instruction]
Kasse mit Gerät koppeln:

. Öffne die plentymarkets App auf dem Gerät, das du mit der Kasse koppeln möchtest.
. Öffne das Menü *plentymarkets App » Einstellungen » POS*.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<table-POS-link-device>>.
. *Speichere* (icon:save[role="darkGrey"]) die Einstellungen. +
→ Das Gerät wird mit der Kasse gekoppelt.

[[table-POS-link-device]]
.Kasse mit Gerät koppeln
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Mandant*
|Wähle den Mandant, für den die Kasse erstellt wurde.

| *POS*
|Wähle die Kasse.

| *Preis*
|Wähle, ob die Auftragspositionen in Brutto- oder Nettopreisen angezeigt werden sollen.

| *Fiskalisierung*
|Nach erfolgreicher Kopplung wird in diesem Feld die IP-Adresse der xref:pos:pos-rechtssicherheit.adoc#500[technischen Sicherheitseinrichtung], die mit der Kasse gekoppelt ist, angezeigt.

| *Bondrucker*
|Gib die IP-Adresse des Bondruckers ein. +
*_Tipp:_* Tippe auf *Testbeleg drucken*, um einen Testbeleg zu drucken.

| *Drucker*
|Optional können über das Plugin plentyBase <<1000, weitere Drucker>> angebunden werden.

| *Automatisches Drucken*
| *Ein* = Standardeinstellung. Belege werden automatisch gedruckt, wenn ein Vorgang abgeschlossen wurde. +
*Aus* =  Das Drucken von Belegen muss manuell ausgelöst werden.

| *Darstellung* +
(nur Tablets)
| *Smartphone* =  Für Smartphones optimierte Darstellung; Hoch- oder Querformat. +
*Tablet* = Für Tablets optimierte Darstellung; nur Querformat.

| *Startbeleg erstellen* +
(nur neue Kassen mit Standort Österreich)
|Wähle diese Option, um den xref:pos:pos-rechtssicherheit.adoc#1600[Startbeleg  zu erstellen] und so die manipulationssichere Sicherheitseinrichtung für die Kasse zu aktivieren. Nachdem der Startbeleg erstellt wurde, kann das Standortland der Kasse nicht mehr geändert werden.

| *Endbeleg erstellen* +
(nur Kassen mit Standort Österreich und aktivierter Sicherheitseinrichtung)
|Wähle diese Option, um xref:pos:pos-rechtssicherheit.adoc#2300[den Endbeleg zu erstellen] und so die manipulationssichere Sicherheitseinrichtung für die Kasse zu deaktivieren. Nachdem der Endbeleg erstellt wurde, kann die Kasse nicht mehr verwendet werden.
|====

[#240]
=== Kasse von Gerät entkoppeln

Du hast die Möglichkeit, die Koppelung einer Kasse mit dem Gerät aufzuheben. Stattdessen kannst du entweder eine andere Kasse mit dem Gerät verbinden oder keine Kasse wählen.

[.instruction]
Kasse von Gerät entkoppeln:

. Öffne die plentymarkets App.
. Öffne das Menü *plentymarkets App » Einstellungen » POS*.
. Wähle für die Einstellung *POS* eine andere Kasse oder wähle den leeren Eintrag.
. *Speichere* (icon:save[role="darkGrey"]) die Einstellungen. +
→ Das Gerät wird von der Kasse entkoppelt.

[IMPORTANT]
.Entkoppelung der Kasse nur auf dem Gerät möglich
====
Du kannst die Kasse nur über die Einstellungen auf dem Gerät von der Kasse entkoppeln. Wende dich bei einem Verlust oder Defekt des Geräts an den plentymarkets Support, um die Koppelung aufzuheben.
====

[#250]
== Senden des Kassenbelegs an Bestandskund:innen einrichten

plentymarkets ermöglicht dir, Kassenbelege per Ereignisaktion automatisch an die am Kontaktdatensatz gespeicherte E-Mail-Adresse zu senden. Dazu erstellst du zunächst eine E-Mail-Vorlage mit dem PDF-Anhang *Kassenbeleg*. Erstelle dann eine Ereignisaktion. Für Kassenaufträge, die im <<#1100, Offline-Modus>> erstellt werden, wird die Ereignisaktion jedoch erst ausgeführt, wenn die Kassenaufträge in das plentymarkets Backend hochgeladen werden. Prüfe die aktuellen gesetzlichen Bestimmungen zum Versand von E-Mails, bevor du die Ereignisaktion aktivierst.

[#260]
=== E-Mail-Vorlage erstellen

Erstelle zunächst eine xref:crm:e-mails-versenden.adoc#1200[E-Mail-Vorlage], die versendet wird, wenn ein Kassenbeleg generiert wird.

[.instruction]
E-Mail-Vorlage erstellen:

. Öffne das Menü *Einrichtung » Mandant » [Mandant wählen] » E-Mail » Vorlagen*.
. Klicke auf *Neue E-Mail-Vorlage*. +
→ Das Fenster *Neue E-Mail-Vorlage* wird geöffnet.
. Gib einen Namen für die Vorlage ein.
. Wähle einen Eigner oder *Alle* aus der Dropdown-Liste *Eigner*.
. Klicke auf *Speichern* (icon:save[role="darkGrey"]). +
→ Die E-Mail-Vorlage wird erstellt und je nach gewähltem Eigner in einem der drei Ordner gespeichert.
. Wähle den PDF-Anhang *Kassenbeleg*.
. Nimm die weiteren Einstellungen vor. Beachte die Erläuterungen unter xref:crm:e-mails-versenden.adoc#1200[Neue E-Mail-Vorlage erstellen].
. *Speichere* (icon:save[role="darkGrey"]) die Einstellungen.

[#270]
=== Ereignisaktion für automatischen E-Mail-Versand erstellen

Erstelle nun eine Ereignisaktion, die die E-Mail-Vorlage versendet, wenn ein Kassenbeleg generiert wird.

include::_includes:partial$event-procedure.adoc[]

[[table-POS-event-procedure-send-receipt]]
.Ereignisaktion zum automatischen Senden des Kassenbelegs
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

| *Ereignis*
| *Dokumente: Kassenbeleg generiert*
|

| *Filter 1*
| *Auftrag &gt; Auftragstyp*
| *Auftrag* +
*Retoure*

| *Filter 2*
| *Auftrag &gt; Herkunft*
|Wähle die Kasse, für die Kassenbelege per E-Mail versendet werden sollen.

| *Aktion*
| *Kunde &gt; E-Mail versenden*
| *Vorlage*: Wähle die E-Mail-Vorlage für den Kassenbeleg. +
*Empfänger*: Wähle die Option *Kunde*.
|====

[#990]
== Kundenkarten verwenden

Neben dem automatischen Versand von Kassenbelegen kannst du Bestandskund:innen einen weiteren Service anbieten. Kundenkarten mit Barcodes erlauben dir, den Barcode direkt beim xref:pos:pos-kassenbenutzer.adoc#30[Kassiervorgang] zu scannen. So wird automatisch ein Kontakt ausgewählt. Wie bei <<#2700, Gutscheinkarten>> wird der Kontakt anhand eines Barcodes auf der Kundenkarte gefunden. Je nach Vorgehensweise kann der Kontakt entweder über die Kontakt-ID oder die Kundennummer gefunden werden. <<table-pos-loyalty-cards>> erläutert beide Vorgehensweisen und beschreibt vorbereitende Schritte zur Erstellung der Kundenkarten.

[WARNING]
.Nur eine Vorgehensweise auswählen
====
Überlege dir im Voraus, wie du vorgehen möchtest und welche Zuordnung für dich und deine Arbeitsweise im Ladengeschäft passend sind. Ändere die Vorgehensweise später nicht, da die Kontaktdaten sonst im Kassiervorgang nicht mehr korrekt gefunden werden können.
====

[[table-pos-loyalty-cards]]
.Vorgehensweisen zur Verwendung von Kundenkarten
|====

|Zuordnung über Kontakt-ID |Zuordnung über Kundennummer

a|Für die Zuordnung per Kontakt-ID muss bereits ein Kontaktdatensatz pro Kund:in existieren, denen du eine Kundenkarte aushändigen möchtest. Diese Methode bietet sich an, wenn du eine große Gruppe bereits existierender Bestandskund:innen Kundenkarten anfertigen lassen möchtest. +

* Kontaktdatensätze verwaltest du im Backend deines plentymarkets Systems. xref:crm:kontakt-erstellen.adoc#kontakt-erstellen[Füge neue Kontakte hinzu] oder nutze die xref:crm:kontakt-suchen.adoc#[Suche] im Menü *CRM » Kontakte*, um die Kontakt-IDs der Kund:innen einzusehen, für die du Kundenkarten drucken möchtest.

a|Für die Zuordnung per Kundennummer muss nicht zwingend ein Kontaktdatensatz vorhanden sein. Du kannst also nach deinen Wünschen fortlaufende Kundennummern wählen und diese als Grundlage für die Barcodes verwenden. So kannst du auch eine größere Anzahl von Kundenkarten im Vorfeld drucken lassen. Achte jedoch darauf, selbst gewählte Kundennummern nicht doppelt zu vergeben.

* Ergänze bei Aushändigung der Kundenkarte manuell die Kundennummer im entsprechenden Kontaktdatensatz. Trage dazu die Kundennummer (ohne Präfix) im Feld *Kundennummer* im Menü *CRM » Kontakte » [Kontakt öffnen]* ein. *Speichere* (icon:save[role="darkGrey"]) die Einstellungen.

|====

Sobald du dich für eine Vorgehensweise entschieden hast, kannst du mit der Beschaffung der Kundenkarten fortfahren.

* Wähle einen Anbieter aus, um Barcode-Karten mit vorgefertigten Codes drucken zu lassen. Die meisten Anbieter erwarten eine CSV-Datei, die die einzelnen Codes enthält, die auf den Karten platziert werden sollen, sowie eine Layout-Vorlage im Photoshop- oder Adobe-Illustrator-Format für das Rahmendesign.

* Nutze ein Online-Tool, um die benötigten Barcodes zu generieren und anschließend im geforderten Format an den Anbieter weiterzuleiten.

[IMPORTANT]
.Korrekten Präfix verwenden
====
Stelle der Kontakt-ID oder der Kundennummer beim Generieren der Barcodes jeweils den Präfix *+* (ohne Leerzeichen) voran. Nur so kann beim späteren Scan des Barcodes der Kontaktdatensatz korrekt durchsucht und zugeordnet werden.
====

[#1000]
== Druck von Kassenbelegen über andere Drucker einrichten

Standardmäßig werden alle Kassenbelege über den Bondrucker gedruckt, den du im Menü *plentymarkets App » Einstellungen » POS* über die Option *Bondrucker* festlegst. Zusätzlich kannst du aber Kassenbelege auch auf anderen Druckern ausdrucken. Zum Beispiel kann es sinnvoll sein, Belege auf einem DIN-A4-Drucker statt auf Thermopapier zu drucken, die länger aufbewahrt werden müssen.

[TIP]
.Bondrucker läuft ohne plentyBase
====
Der Bondrucker wird über die IP-Adresse des Druckers an die plentymarkets App angebunden. Deshalb ist plentyBase für die Nutzung des Bondruckers nicht erforderlich. Du benötigst plentyBase also nur, wenn du andere Drucker an plentyPOS anbinden möchtest.
====

Um zusätzliche Drucker zu nutzen, benötigst du einen im Netzwerk zugänglichen Rechner, der mit einem oder mehreren Druckern verbunden ist, über die du die Kassenbelege drucken möchtest. Auf diesem Rechner installierst du das Plugin xref:automatisierung:plentybase-installieren.adoc#[plentyBase]. plentyBase dient dazu, eine Verbindung zwischen der plentymarkets App und dem lokalen Rechner herzustellen. So kann die Kasse auf die Drucker zugreifen, auf die auch der lokale Rechner zugreifen kann. Im plentymarkets Backend konfigurierst du diese Drucker im Menü *Einrichtung » Einstellungen » Drucker*.

[#1010]
=== plentyBase installieren und einrichten

plentyBase ist ein von plentymarkets entwickeltes Plugin. Anders als die meisten anderen plentymarkets Plugins wird plentyBase jedoch nicht im plentymarkets Backend aktiviert. Stattdessen wird plentyBase auf einem lokalen Rechner installiert und ausgeführt. plentyBase stellt eine Schnittstelle bereit, über die du aus dem plentymarkets Backend und/oder der plentymarkets App die Drucker nutzen kannst, die an den Computer angeschlossen sind.

Damit die Drucker in der plentymarkets App verfügbar sind, müssen die folgenden Vorraussetzungen erfüllt sein:

* plentyBase muss auf dem Rechner installiert sein. +
→ Die Installationsdatei lädst du im link:https://marketplace.plentymarkets.com/plugins/integration/plentyBase_5053[plentyMarketplace^] herunter.
* plentyBase muss auf dem Rechner konfiguriert sein. +
→ Die Konfigurationsanleitung findest du auf der Handbuchseite xref:automatisierung:plentybase-installieren.adoc#[plentyBase]. +
*_Hinweis:_* Aktiviere bei der Einrichtung die Option *HTTP-Server*. Nur so kann plentyPOS mit plentyBase kommunizieren.
* plentyBase muss auf dem Rechner gestartet sein. +
*_Empfehlung:_* Konfiguriere plentyBase so, dass plentyBase beim Starten des Rechners automatisch gestartet wird.
* Die Verbindungsdaten von plentyBase müssen in der plentymarkets App gespeichert sein. +
→ Wie du die plentyBase Verbindungsdaten in der App speicherst, erfährst du auf der Handbuchseite xref:automatisierung:plentybase-installieren.adoc#[plentyBase].
* Die Drucker müssen im plentymarkets Backend im Menü *Einrichtung » Einstellungen » Drucker* konfiguriert sein.

[#1020]
=== Drucker für Kassenbelege speichern

Nachdem du plentyBase eingerichtet hast, kannst du im Menü *plentymarkets App » Einstellungen » POS* im Bereich *Drucker* die im plentymarkets Backend konfigurierten Drucker wählen.

Gehe wie unten beschrieben vor, um festzulegen, welche Kassenbelege über welchen Drucker gedruckt werden sollen.

[.instruction]
Drucker pro Belegart festlegen:

. Öffne die plentymarkets App.
. Öffne das Menü *plentymarkets App » Einstellungen » POS*.
. Nimm im Bereich *Drucker* die Einstellungen vor. Beachte dazu die Erläuterungen in <<table-POS-printers>>.
. *Speichere* (icon:save[role="darkGrey"]) die Einstellungen.

[[table-POS-printers]]
.Drucker für Kassenbelege festlegen
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Standard-Drucker*
|Wähle in der Dropdown-Liste den Standard-Drucker für die Kasse. Standardmäßig ist der Bondrucker vorausgewählt. +
*_Hinweis:_* In der Dropdown-Liste werden der Bondrucker und die Drucker im Netzwerk angezeigt, auf die die Kasse Zugriff hat.
Wenn in der Dropdown-Liste außer dem Bondrucker und dem Standarddrucker keine Drucker angezeigt werden, wird es Zeit für ein <<1040, Troubleshooting>>.

| *Kaufbeleg*; +
*Tagesabschluss*; +
*Zwischenbericht*; +
*Kassensturz*; +
*Stornierungsbeleg*; +
*Einlage und Entnahme*; +
*Gutscheinbeleg*; +
*Retourenbeleg*; +
*Gutschriftbeleg*
|Der Standard-Drucker ist vorausgewählt. Wenn alle Kassenbelege auf dem Standard-Drucker gedruckt werden sollen, sind keine weiteren Einstellungen erforderlich. Wähle ansonsten in den Dropdown-Listen der einzelnen Kassenbelege den Drucker, auf dem der Beleg gedruckt werden soll. +
*_Hinweis:_* In den Dropdown-Listen werden der Bondrucker und die Drucker im Netzwerk angezeigt, auf die die Kasse Zugriff hat.
Wenn in den Dropdown-Listen außer dem Bondrucker und dem Standarddrucker keine Drucker angezeigt werden, wird es Zeit für ein <<1040, Troubleshooting>>.
|====

[#1060]
=== Testseite drucken

Gehe wie unten beschreiben vor, um eine Testseite zu drucken.

[.instruction]
Testseite drucken:

. Öffne die plentymarkets App.
. Öffne das Menü *plentymarkets App » Einstellungen » POS*.
. Tippe oben rechts auf das Menü-Symbol.
. Tippe auf *Testdruck*. +
→ Das Fenster *Testdruck* wird angezeigt.
. Wähle in der Dropdown-Liste den Beleg, für den du das Drucken testen möchtest.
. Tippe auf *Testseite drucken*. +
→ Eine Testseite wird gedruckt. +
→ Wenn keine Testseite gedruckt wird, prüfe die Einstellungen wie im <<1050, Troubleshooting-Fall 2>> beschrieben.

[#1030]
=== Troubleshooting: Fehler bei Druckern

[#1040]
==== Fall 1: In den Kasseneinstellungen können keine Drucker gewählt werden

Du hast bisher noch keine zusätzlichen Drucker in den POS-Einstellungen gespeichert. In den Dropdown-Listen des Bereichs *Drucker* werden außer dem Bondrucker und dem Standard-Drucker keine Drucker angezeigt. Bondrucker und Standard-Drucker sind in diesem Fall identisch.

* Ist plentyBase auf einem Rechner im Netzwerk installiert? +
→ Die Installationsdatei lädst du im link:https://marketplace.plentymarkets.com/plugins/integration/plentyBase_5053[plentyMarketplace^] herunter.
* Wurde plentyBase korrekt konfiguriert? +
→ Die Konfigurationsanleitung findest du auf der Handbuchseite xref:automatisierung:plentybase-installieren.adoc#[plentyBase]. +
*_Tipp:_* Wurde die Option *HTTP-Server* aktiviert und ein HTTP-Port angegeben?
* Wurden die plentyBase Einstellungen in der App gespeichert? +
→ Wie du die plentyBase Verbindungsdaten in der App speicherst, erfährst du auf der Handbuchseite xref:automatisierung:plentybase-installieren.adoc#[plentyBase]. +
*_Tipp:_* Wurde der richtige HTTP-Port in der App gespeichert?
* Ist plentyBase auf dem Rechner gestartet? +
*_Empfehlung:_* Konfiguriere plentyBase so, dass plentyBase beim Starten des Rechners automatisch gestartet wird.
* Wurde der Drucker im plentymarkets Backend xref:automatisierung:drucker.adoc#[gespeichert und konfiguriert]?

[#1050]
==== Fall 2: Drucker sind in den Kasseneinstellungen gespeichert, aber nicht erreichbar

Der Drucker wurde für den Druck einer oder mehrerer Belege ausgewählt und die Einstellungen gespeichert. Der Drucker ist aber nun mit einem Dreieck gekennzeichnet und nicht erreichbar.

* Ist der Rechner an, auf dem plentyBase installiert ist?
* Ist der Drucker an und funktionsbereit?
* Ist der Drucker mit dem Rechner verbunden?
* Ist plentyBase auf dem Rechner gestartet?
* Wurden die plentyBase Konfigurationseinstellungen vor kurzem geändert, zum Beispiel der HTTP-Port oder der Access Token? +
→ Wenn ja, wurden die neuen Einstellungen in der plentymarkets App gespeichert?
* Wurde die Druckerkonfiguration aus dem plentymarkets Backend entfernt? +
→ Drucker konfigurierst du im Menü *Einrichtung » Einstellungen » Drucker*.

[#1090]
== Druck von Artikeletiketten einrichten

Wie du Etikettenvorlagen erstellst und Artikeletiketten in der Artikelsuche der plentymarkets App druckst, erfährst du auf der Handbuchseite xref:app:artikelsuche.adoc#[Artikel-, Kunden- und Auftragssuche].

[IMPORTANT]
.plentyBase einrichten
====
Um Etiketten drucken zu können, benötigst du das kostenlose Plugin plentyBase. plentyBase stellt eine Schnittstelle bereit, über die du aus dem plentymarkets Backend und/oder der plentymarkets App die Drucker nutzen kannst, die an den Computer angeschlossen sind. Wie du plentyBase installierst und konfigurierst erfährst du auf der Handbuchseite xref:automatisierung:plentybase-installieren.adoc#[plentyBase].
====

[#1100]
== plentyPOS ohne Internetverbindung nutzen

Viele Vorgänge kannst du mit plentyPOS auch offline durchführen. Dies ist wichtig, wen am Standort deiner Kasse die Internetverbindung ausfällt oder du die Kasse kurzzeitig an einem Ort betreibst, an dem keine Internetverbindung besteht.

Speziell für diesen Anwendungsfall haben wir das Plugin *plentyBase ItemCachePOS* entwickelt. Du kannst das Plugin link:https://marketplace.plentymarkets.com/plentybaseitemcachepos_6313[kostenlos im plentyMarketplace^] herunterladen. Klicke auf das Tab *Beschreibung*, um zu erfahren, wie die Einrichtung funktioniert.

Beachte die folgenden Voraussetzungen, damit du das Plugin korrekt einrichten und in Verbindung mit plentyPOS nutzen kannst:

[%interactive]

* [ ] Das Tool xref:automatisierung:plentybase-installieren.adoc#[plentyBase] muss auf deinem Rechner installiert sein und ausgeführt werden
* [ ] Die xref:app:installieren.adoc#2050[Verbindungsdaten für plentyBase] müssen in der plentymarkets App gespeichert seind
* [ ] Das Plugin link:https://marketplace.plentymarkets.com/plugins/channels/marktplaetze/elasticexport_4763[Elastischer Export^] muss in deinem plentymarkets System installiert und bereitgestellt sein
* [ ] Das Plugin link:https://marketplace.plentymarkets.com/plugins/integration/formatdesigner_6483[FormatDesigner^] muss in deinem plentymarkets System installiert und bereitgestellt sein

Nachdem du das Plugin *plentyBase ItemCachePOS* vollständig eingerichtet hast, kannst auch ohne Internetverbindung Artikel über plentyPOS verkaufen. Das Plugin funktioniert wie ein Zwischenspeicher, in dem die Vorgänge abgelegt werden, wenn keine Internetverbindung besteht. Sobald wieder eine Internetverbindung besteht, werden die durchgeführten Vorgänge automatisch im Hintergrund mit deinem plentymarkets System synchronisiert.

[WARNING]
.Offline-Aufträge werden beim Deinstallieren der App gelöscht
====
Wenn du die App deinstallierst, bevor die Aufträge an plentymarkets übertragen wurden, werden die lokal gespeicherten Aufträge unwiederbringlich gelöscht und können auch vom plentymarkets Support nicht wiederhergestellt werden. Prüfe daher vor jedem Deinstallieren der App, dass keine Offline-Aufträge auf dem Gerät vorhanden sind.
====

Folgende Funktionen für Kassiervorgänge kannst du im Offline-Betrieb nutzen:

* xref:pos:pos-kassenbenutzer.adoc#50[Manuelle Artikelsuche] in der Kasse und der Retourenansicht
* xref:pos:pos-kassenbenutzer.adoc#70[Scannen von Artikeln] in der Kasse und der Retourenansicht
* Artikel an xref:pos:pos-einrichten.adoc#95[Standardkunden] verkaufen
* xref:pos:pos-kassenbenutzer.adoc#380[Retouren ohne Zuordnung zum Hauptauftrag] buchen
* Nach xref:pos:pos-kassenbenutzer.adoc#60[Favoriten] suchen
* xref:pos:pos-kassenbenutzer.adoc#170[Rabatte] auf Artikel gewähren

[IMPORTANT]
.Einschränkungen im Offline-Betrieb
====
Die folgenden Vorgänge können ohne Internetverbindung nicht durchgeführt werden, auch wenn du das Plugin *plentyBase ItemCachePOS* nutzt:

* xref:pos:pos-kassenbenutzer.adoc#250[Verkauf] und xref:pos:pos-kassenbenutzer.adoc#160[Einlösung] von Gutscheinen
* xref:pos:pos-kassenbenutzer.adoc#135[Bestandskund:innen auswählen]
* xref:pos:pos-kassenbenutzer.adoc#440[Anzahlungen entgegennehmen]
* xref:pos:pos-online-bestellungen.adoc#900[Online-Bestellungen (Click & Collect)] laden und kassieren
* xref:pos:pos-kassenbenutzer.adoc#370[Retouren mit Zuordnung zum Hauptauftrag] buchen
* xref:pos:pos-kassenbenutzer.adoc#220[Zwischenberichte] erstellen
* xref:pos:pos-kassenbenutzer.adoc#230[Tagesabschlussberichte] erstellen
* xref:pos:pos-kassenbenutzer.adoc#450b[Kassensturzberichte] erstellen
====

[#400]
== Kassenvorgänge im Kassenjournal suchen

Alle Kassenvorgänge werden in plentymarkets dokumentiert. Im Menü *Daten » POS » Protokolle » Kassenjournal* kannst du Kassenvorgänge suchen, anzeigen und bei Bedarf exportieren. Mit den Filtern des Tabs *Filter* grenzt du die im Kassenjournal angezeigten Kassenvorgänge anhand bestimmter Kriterien ein. Die gefundenen Kassenvorgänge werden im Tab *Kassenjournal* aufgelistet. Die Ergebnisse sind standardmäßig nach dem Datum sortiert. Gehe wie unten beschrieben vor, um Kassenvorgänge im Kassenjournal zu suchen.

[.instruction]
Kassenvorgänge im Kassenjournal suchen:

. Öffne das Menü *Daten » POS » Protokolle » Kassenjournal*.
. Wähle die Filter. Beachte dazu die Erläuterungen in <<table-POS-cash-journal-menu>>.
. Klicke auf *Suchen* (icon:search[role="blue"]). +
→ Die Kassenvorgänge, die den Suchkriterien entsprechen, werden im Tab *Kassenjournal* aufgelistet.

[[table-POS-cash-journal-menu]]
.Menü *Kassenjournal*
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+^|Tab: Filter

| *Suchen*
|Klicke ohne Filtereinstellungen auf *Suchen* (icon:search[role="blue"]), um alle Kassenvorgänge anzuzeigen. +
icon:map-signs[] *_Oder:_* Grenze die Suchergebnisse durch Filtereinstellungen ein und klicke auf *Suchen* (icon:search[role="blue"]). Die gefundenen Kassenvorgänge werden im Tab *Kassenjournal* aufgelistet.

| *Reset*
|Setzt die eingestellten Filterkriterien zurück.

| *Belegnummer: von*; +
*Belegnummer: bis*
|Gib die Belegnummer des ersten und des letzten Belegs ein, um Kassenvorgänge einer bestimmten Belegabfolge anzuzeigen. Um nur einen Beleg anzuzeigen, gib die gesuchte Belegnummer in die Felder *Belegnummer: von* und *Belegnummer: bis* ein.

| *Buchungskonto*
|Gib ein xref:pos:pos-einrichten.adoc#950[Buchungskonto] ein, um Kassenvorgänge eines bestimmten Buchungskontos anzuzeigen.

| *Verk. Gutscheine zu Betrag*
|Möchtest du verkaufte Gutscheine wie Umsätze behandeln? +
*Option aktiviert* = Gutscheinverkäufe zählen zum Umsatz. Die Beträge werden also als "Einnahmen" im Kassenjournal verzeichnet. Gutscheinverkäufe fließen in den Wert rein, der rechts in die Spalte *Betrag* zu sehen ist. Gutscheine werden auch im PDF-Export und CSV-Export wie Umsätze behandelt.

| *Mandant (Shop)*
|Wähle einen Mandanten (Shop) aus der Dropdown-Liste, um die Ergebnisse auf Kassenvorgänge dieses Mandanten einzugrenzen.

| *Kasse*
|Wähle eine Kasse aus der Dropdown-Liste, um die Ergebnisse auf Kassenvorgänge dieser Kasse einzugrenzen.

| *Benutzer*
|Wähle einen Benutzernamen aus der Dropdown-Liste, um die Ergebnisse auf Kassenvorgänge dieser Kassenkraft einzugrenzen.

| *Zahlungsart*
|Wähle eine Zahlungsart aus der Dropdown-Liste, um die Ergebnisse auf Kassenvorgänge mit dieser Zahlungsart einzugrenzen. Die Dropdown-Liste enthält nur aktive Zahlungsarten.

| *Zeitraum*
|Wähle eine Zeitspanne, um die angezeigten Kassenvorgänge auf diesen Zeitraum zu beschränken. +
Um Belege eines benutzerdefinierten Zeitraums anzuzeigen, wähle die Option *Datumsauswahl* und gib im Feld *von* das Startdatum und im Feld *bis* das Enddatum ein oder wähle die Daten aus dem angezeigten Kalender.

| *Typ*
|Wähle einen Typ aus der Dropdown-Liste, um die Ergebnisse auf Kassenvorgänge dieses Typs einzugrenzen.

2+^|Tab: Kassenjournal

| *Datum*
|Datum und Uhrzeit des Kassenvorgangs

| *Vorgang*
|Zeigt an, ob der Vorgang eine Einnahme (*E*) oder eine Ausgabe (*A*) ist.

| *Betrag*
|Wert des Kassenvorgangs

| *Belegnummer*
|Fortlaufende Nummer des Belegs, der für den Kassenvorgang erstellt wurde. Auf die Belegnummer klicken, um den Beleg im PDF-Format zu öffnen.

| *Typ*
|Typ des Kassenvorgangs

| *Barbestand*
|Barbestand der Kassen nach Abschluss des Kassenvorgangs

| *Auftrags-ID*
|ID des in plentymarkets erstellten Auftrags

| *Steuersatz*
|Steuersätze, die für diesen Auftrag zum Tragen kommen.

| *USt.*
|Im Auftragswert enthaltene Umsatzsteuer

| *Buchungstext*
|Buchungstext für den Kassenvorgang. Bei Einlagen und Entnahmen entspricht der Buchungstext dem Grund der Bargeldbewegung.
|====

[#960]
== Kassenaufträge im plentymarkets Backend ändern

Für Kassenaufträge wird ein Auftrag im plentymarkets Backend erstellt. Nach dem Erstellen des Auftrags können keine nachträglichen Änderungen von rechtlich relevanten Auftragsdaten vorgenommen werden. Ausgenommen hiervon sind Auftragsdaten, die sich im Rahmen der Bearbeitung und Erfüllung von Aufträgen ändern bzw. deren Historie dokumentieren:

* Sprache
* Status
* Bezahlter Betrag
* Zahlungsstatus
* Retourengründe
* Auftrag lässt sich Sammelauftrag zuordnen
* Lieferanschrift
* E-Mail-Versand
* Auftragsnotiz
* Versanddatum
* Rückgabedatum

[#910]
== Kasse außer Betrieb nehmen

Lösche eine Kasse, die du nicht mehr benötigst, um diese Kasse dauerhaft außer Betrieb zu nehmen. Die Geschäftsvorfälle, die über die Kasse abgewickelt wurden, bleiben im System gespeichert und können weiter steuerrechtlich ausgewertet werden.

[TIP]
.Besonderheit bei Kassenstandort Österreich
====
Bei Kassen mit Standort Österreich, bei denen die Sicherheitseinrichtung aktiviert wurde, muss der Endbeleg in der App erstellt werden, um die Kasse dauerhaft außer Betrieb zu nehmen. Dadurch wird die Kasse automatisch gelöscht.
====

[.instruction]
Kasse löschen:

. Öffne das Menü *Einrichtung » POS » [Mandant wählen]*.
. Klicke auf die Kasse. +
→ Das Tab *Grundeinstellungen* der Kasse wird geöffnet.
. Klicke oben links auf *Löschen*. +
→ Die Kasse wird gelöscht. +
*_Hinweis:_* Bei Kassen mit Standort Österreich und aktivierter Sicherheitseinrichtung muss der xref:pos:pos-rechtssicherheit.adoc#2300[Endbeleg in der App] erstellt werden. Dadurch wird die Kasse automatisch gelöscht.
