= Kassensystem plentyPOS
:author: team-app
:keywords: plentyPOS Übersicht, POS Funktionen, plenty POS
:description: plentyPOS ist das von plentysystems entwickelte Kassensystem. Die Funktionalitäten von plentyPOS werden über die plentymarkets App bereitgestellt.

[#100]
== Was ist plentyPOS?

plentyPOS (*Point of Sale*) ist unser eigens entwickeltes Kassensystem, mit dem du den stationären Handel im Ladengeschäft mühelos abwickelst. Die Funktionalitäten von plentyPOS werden über die xref:app:app.adoc#[plentymarkets App] bereitgestellt.
Dieser Handbuchbereich bietet dir einen Überblick über alle Informationen zur Einrichtung und optimalen Nutzung von plentyPOS.

[TIP]
.POS Demo-Modus
====
Du interessierst dich für plentyPOS und möchtest dir selbst einen unverbindlichen Eindruck von den Funktionen verschaffen? Dann findest du xref:pos:demo.adoc#[hier] eine ausführliche Anleitung zur Nutzung des Demo-Modus von plentyPOS.
====

[#200]
== Welche Schritte gehören zur Einrichtung?

Du hast dich bereits entschieden, plentyPOS als Kassensystem in deinem Ladengeschäft zu nutzen? Prima! Schaue dich auf den folgenden Seiten um, um Anleitungen und Kontakt zu unseren Servicepartnern zu erhalten.

* xref:willkommen:systemvoraussetzungen.adoc#500[Passende Hardware auswählen]
* xref:pos:pos-einrichten.adoc#[plentyPOS einrichten]
* xref:pos:pos-kassenbenutzer.adoc#[plentyPOS als Kassenpersonal nutzen]

[#300]
== Welche Funktionen stehen dir zur Verfügung?

Dein fertig eingerichtetes plentyPOS System bietet dir umfassende Möglichkeiten, dein Tagesgeschäft im stationären Handel komfortabel abzuwickeln. Je nachdem, in welchem Umfang du die Kasse nutzen möchtest, stehen dir die folgenden Funktionen zur Verfügung:

** xref:pos:pos-kassenbenutzer.adoc#30[Kassieren]
** xref:pos:pos-einrichten.adoc#2700[Gutscheine verkaufen und einlösen]
** xref:app:artikelsuche.adoc#400[Artikeletiketten drucken]
** xref:pos:pos-kassenbenutzer.adoc#173[Aufträge stornieren]
** xref:pos:pos-kassenbenutzer.adoc#175[Retouren buchen]
** xref:pos:pos-online-bestellungen.adoc#[Online-Bestellungen an der Kasse abwickeln (Click & Collect)]
** xref:pos:pos-kassenbenutzer.adoc#180[Einlagen und Entnahmen buchen]
** xref:pos:pos-kassenbenutzer.adoc#210[Tagesabschluss, Zwischenbericht und Kassensturzbericht erstellen]

Zusätzlich gibt es einige rechtliche Vorgaben und spezifische Exporte, die du beim Einsatz von plentyPOS beachten musst:

** xref:pos:pos-rechtssicherheit.adoc#100[Kassenvorgänge in Deutschland rechtssicher belegen]
** xref:pos:pos-rechtssicherheit.adoc#1000[Kasse in Österreich rechtssicher betreiben]
** xref:pos:pos-rechtssicherheit.adoc#300[IDEA-Export erstellen]
** xref:pos:pos-rechtssicherheit.adoc#950[DSFinV-K-Export erstellen]
** xref:pos:pos-einrichten.adoc#950[Buchungskonten für Kassenvorfälle speichern]


[#400]
== Auf dem Laufenden bleiben

Wartest du sehnsüchtig auf ein neues Feature für plentyPOS? Wir informieren dich gerne über Änderungen an der Software! Änderungen werden link:https://forum.plentymarkets.com/c/changelog/changelog-app[in einem Changelog^] veröffentlicht. Abonniere den Changelog und bleibe immer auf dem Laufenden.
