= Adding plugins to the system
:author: team-plugin-core
:keywords: plugin, extension, addon, git, github, bitbucket, gitlab, integrationen, plentymarketplace
:description: To extend your system with plugins, you have 3 options: the integration assistant, plentyMarketplace and Git.
:page-pagination:
:id: BZCJL1G

There are multiple ways of adding plugins to your plentymarkets system. Using the <<integrations-assistant, Integrations assistant>>, you can set up your online store quick and easy. You can purchase plugins on <<marketplace-plugins, plentyMarketplace>>, some for free, others for additional costs. If you need a custom plugin designed to satisfy your particular needs, you can <<git-plugins, add it via Git>>.

[#integrations-assistant]
== Integrations assistant

A new plentymarkets system does not come with any plugins pre-installed. If you want to run your own online store or set up a connection to the store systems Shopify or WooCommerce, you can use the *Integrations assistant* to select and install the most important plugins in one go.

The following plugins are available via the assistant:

* Online stores
** plentyShop LTS & IO +
→ These plugins form the basis of your own plenty online store.
** Shopify
** WooCommerce
* Payment methods
** PayPal
** Mollie
** Klarna
** PAYONE
** Cash in advance
** Cash on delivery
** Invoice
** EBICS
* Shipping service providers
** DHL (DE)
** DHL Preferred Delivery (DE)
** DHL Retoure Online
** Hermes (DE)
** DPD (DE)
** DPD (UK)

NOTE: If you select the plugins via the assistant, the installation process does not include any more steps and you can continue with xref:plugins:configuring-installed-plugins.adoc#[configuring the plugins].

[#marketplace-plugins]
== Marketplace plugins

You will add most plugins to your system via link:https://marketplace.plentymarkets.com/en[plentyMarketplace^].plentyMarketplace offers a great selection of different plugins that you can purchase and use right away. To purchase a plugin on plentyMarketplace, proceed as follows:

include::partial$marketplace-plugin-kaufen-en_gb.adoc[]

include::partial$hinzugefuegte-plugins-installieren-en_gb.adoc[]

[[table-purchase-options]]
include::partial$marketplace-kaufoptionen-en_gb.adoc[]

[#git-plugins]
== Git plugins

If you cannot find the plugin you need on plentyMarketplace, you can also add plugins from Git repositories. Some external developers also provide their plugins this way. For more information on available plugins, contact these developers directly. To contact a developer, either use the link:https://marketplace.plentymarkets.com/en/partners[partner overview^], write a message in the link:https://forum.plentymarkets.com/c/suche-biete/suche-biete-plugins[Suche/Biete^] forum category or create a link:https://marketplace.plentymarkets.com/en/plentyprojects[new project request^] on plentyMarketplace.

[NOTE]
.No review by plentymarkets
====
When a provider upload a plugin on plentyMarketplace, it's reviewed by plentymarkets employees. For plugins that aren't distributed via plentyMarketplace, there's no such review. This means that in these cases, plentymarkets cannot check the functionality of the plugin.

If you want to add a third-party plugin from a source other than plentyMarketplace to your system, we recommend that you cover any data protection concerns you may have and thoroughly test the plugin's functionality.
====

[#access-token-private-repositories]
=== Creating access tokens for private repositories

For private repositories, you need a personal access token in addition to the repository URL. How to create the token varies slightly from site to site. 

[IMPORTANT]
.Assisted providers
====
At the moment, we support the following providers: GitHub, Bitbucket, GitLab.

If you add plugins via a different provider, we won't provide any support in cases of unexpected behaviour.
====

[tabs]
====
GitHub::
+
--
include::partial$git-zugriffstoken-github-en_gb.adoc[]
--

Bitbucket::
+
--
include::partial$git-zugriffstoken-bitbucket-en_gb.adoc[]
--

GitLab::
+
--
include::partial$git-zugriffstoken-gitlab-en_gb.adoc[]
--

====

[#adding-git-repository]
=== Adding Git repositories

This section describes how to add a Git repository to your system. By adding the repository to the system, you can use the plugin managed in the repository.

If you want to add a private repository, first generate an access token as described above. When adding a public repository, you don’t need an access token.

include::partial$git-repository-hinzufuegen-en_gb.adoc[]

include::partial$hinzugefuegte-plugins-installieren-en_gb.adoc[]

[#git-repositories-functional-overview]
=== Functional overview

include::partial$git-repository-verwaltung-en_gb.adoc[]
