= Configuring installed plugins
:lang: en
include::{includedir}/_header.adoc[]
:author: team-plugin-core
:keywords: plugin, extension, addon, container, configuration
:description: Configure your plugins.
:position: 30
:id: H4HJIKA

[.previous-navigation]
<<plugins/installing-added-plugins#, icon:long-arrow-left[] Installing added plugins>>

'''

include::./_textblocks/notes/installierte-plugins-konfigurieren-en_gb.adoc[]

This page contains information on plugin configuration in general. This includes the <<local-vs-global-configuration,difference between local and global settings>> as well as <<configuration-export-import,exporting and importing local configurations>>. It also explains <<container-links,container links>>.
include::./_textblocks/explanations/container-verknuepfung-en_gb.adoc[]

[#local-vs-global-configuration]
== Local vs. global configuration

Plugins can be configured either on a local or a global level.

You can set local configurations in the detail view of the plugin. When you configure a plugin locally, the configuration only applies to a single plugin set. This means that if the plugin is installed in two or more plugin sets, you have to configure it in each set separately. When the plugin gets deleted, the configuration is deleted, too.

Global configurations are carried out in the *Setup* menu. When you configure a plugin globally, the configuration applies to all plugin sets the plugin is installed in.

// @TODO
// Add that global configs are retained according to our BPs (after writing said BPs), but that we cannot guarantee it.

include::./_textblocks/importants/plugin-konfigurationsausnahmen-en_gb.adoc[]

[#configuration-export-import]
== Exporting and importing local configurations

You can export and import local configurations of a plugin. By exporting and importing configurations, you can easily transfer from one plugin set to another. Proceed as follows:

include::./_textblocks/instructions/plugin-konfiguration-exportieren-en_gb.adoc[]

include::./_textblocks/instructions/plugin-konfiguration-importieren-en_gb.adoc[]

include::./_textblocks/warnings/import-limitierung-en_gb.adoc[]

include::./_textblocks/tips/batch-plugin-konfiguration-en_gb.adoc[]

[#container-links]
== Container links

include::./_textblocks/explanations/container-verknuepfung-en_gb.adoc[]
To see which containers to link, check the instructions of the respective plugin.

To select container links, proceed as follows:

include::./_textblocks/instructions/plugin-container-verknuepfung-en_gb.adoc[]

include::./_textblocks/tips/standard-container-verknuepfungen-en_gb.adoc[]

'''

[.previous-navigation]
<<plugins/installing-added-plugins#, icon:long-arrow-left[] Installing added plugins>>
