= Plugins
:author: team-plugin-core
:keywords: plugin, extension, addon, integrationen
:description: Use plugins to extend your system, set up your own plentyShop or connect to more sales channels.
:pos: plugins
:id: XPOMS9R

Plugins are extensions you can integrate into your plentymarkets system. For example, they form the basis of your online store, serve as interface between plentymarkets and other sales channels, or provide you with ways for communicating with your customers more easily.

plentymarkets doesn't consider each plugin in a vacuum, but compiles them in so-called plugin sets. If you run more than one online store, plugin sets allow you to use different layouts and payments methods for both stores. Even if you only have one sales channel, with plugin sets you can test new versions of plugins before switching them live.

include::plugins:partial$anzahl-erlaubter-plugin-sets-en_gb.adoc[]

NOTE: Continue with xref:plugins:adding-plugins-system.adoc#[Adding plugins to the system].

== More about plugins

====
* If you're looking for new plugins for your plentymarkets system, visit link:https://marketplace.plentymarkets.com/[plentyMarketplace^].
* If you require certain functionality and can't find what you need on plentyMarketplace, link:https://marketplace.plentymarkets.com/en/plentyprojects/[post a project request^] and find a solution together with our link:https://marketplace.plentymarkets.com/en/partners[partner agencies^]. Or...
* Create your own plugins. For more information on creating plugins, see link:http://developers.plentymarkets.com/[plentyDevelopers^].
====
