= Removing installed plugins
:author: team-plugin-core
:keywords: plugin, extension, addon, git, github, gitlab, bitbucket, repository
:description: If you don't want to use a plugin anymore, you can deactive or delete it.
:id: MSCTNZP

There are multiple ways to remove plugins installed in a plugin set. You can <<#deactivating-plugins, deactivate>> individual plugins, so that they're no longer loaded in your online store and back end, or completely <<#deleting-plugins-from-plugin-sets, delete them from a plugin set>>. If you want to delete all plugins from a set, you can <<#deleting-plugin-sets, delete the plugin set itself>> instead.

It's not possible to completely remove plugins from the system that you purchased on plentyMarketplace. But, if it's a Git plugin, you can <<#deleting-git-repositories, delete the corresponding repository>>.

[#deactivating-plugins]
== Deactivating plugins

When you deactivate a plugin, it's no longer loaded in your online store and back end. This change is effective immediately, without deploying the plugin set. If you deactivate a plugin this way, it can be reactivated in the same way, again without having to deploy the plugin set.

But, deactivated plugins are disregarded during deployment. If you successfully deployed a plugin set once while a given plugin was deactivated, you have to activate the plugin and xref:plugins:installing-added-plugins.adoc[deploy the plugin set again] before the plugin is active.

For whether you can toggle a plugin active or inactive by activating and deactivating it, see the *Active version* column in the *Plugins » Plugin overview* menu. If there's a version number, you don't have to deploy the set to toggle the plugin active.

You should deactivate a plugin if you don't want to use it temporarily. Unlike when deleting a plugin, deactivating a plugin retains its xref:plugins:configuring-installed-plugins.adoc[local configuration].

To deactivate a plugin, switch the plugin inactive (icon:toggle-off[]).

[#deleting-plugins-from-plugin-sets]
== Deleting plugins from plugin sets

When you delete a plugin, all of its files are removed from the plugin set. Delete a plugin if you don't want to use it anymore.

include::partial$plugin-loeschen-einstellungen-en_gb.adoc[]

To delete a plugin, proceed as follows:

include::partial$plugin-loeschen-en_gb.adoc[]

After deleting a plugin, you can find it among your uninstalled plugins. If you purchased the plugin on plentyMarketplace, you cannot completely remove it from your system.

[#deleting-plugin-sets]
== Deleting plugin sets

When you delete a plugin set, all files of all the plugins contained in the set are removed from your active storage. Delete a plugin set if you don't want to use any of the contained plugins in this configuration anymore.

include::partial$plugin-loeschen-einstellungen-en_gb.adoc[]

To delete a plugin set, proceed as follows:

include::partial$plugin-set-loeschen-en_gb.adoc[]

[#deleting-git-repositories]
== Deleting Git repositories:

If you don't need a Git plugin anymore, you can delete the corresponding repository to completely remove the plugin from your system. To delete a Git repository, you first have to <<#deleting-plugins-from-plugin-sets, delete the corresponding plugin from all plugin sets>>.

include::partial$git-repository-loeschen-en_gb.adoc[]
