= Updating installed plugins
:author: team-plugin-core
:keywords: plugin, extension, addon, git, branch, commit
:description: When a new plugin version becomes available and you want to benefit from the improvements, you have to update the plugin. This page walks you through the update process step by step.
:id: YTCRHEX

Occasionally, plugin developers may provide a new version of their plugin. If you've already installed such a plugin in a plugin set, you have to update it to use the new version. Since this means changing your plugin set, you should create a copy of your plugin set before updating the plugin.

include::partial$sicherheitskopie-en_gb.adoc[]

include::partial$plugin-set-erstellen-en_gb.adoc[]

Depending on whether you <<marketplace-plugins, purchased the plugin from plentyMarketplace>> or <<git-plugins, added it to your system via Git>>, the possibilities you have for updating are different.

[#marketplace-plugins]
== Marketplace plugins

If there is an update for a plugin, under *Action*, the *Update* button of the plugin is highlighted.

include::partial$plugin-aktualisieren-en_gb.adoc[]

Marketplace plugins cannot be downgraded to an older version. If you want to use an older version of the plugin, you have to xref:plugins:removing-installed-plugins.adoc#deleting-plugins-from-plugin-set[delete] and then xref:plugins:installing-added-plugins.adoc[reinstall] it.

[#git-plugins]
== Git plugins

You can update a Git plugin in different ways. To use a newer version of the current branch, you can <<pulling-branches, pull the branch>>. But, you can also use a different branch by <<switching-branches, changing branches>> or use an older version of the plugin by <<#switching-commits, checking out any commit>>.

[#pulling-branches]
=== Pulling branches

If your Git repository contains a newer state of the plugin and you want to use it in plentymarkets, you can pull the branch.

[NOTE]
.Removed in Plugin Build 2
====
Starting on 25 July, 2022, a new deployment process (Plugin Build 2) will be gradually released on all plentymarkets systems. The new deployment process automatically updates Git plugins that you've installed via a branch to the newest version.

When your system has been switched to Plugin Build 2, the UI will no longer include actions for pulling branches.
====

include::partial$git-branch-pullen-en_gb.adoc[]

[#switching-branches]
=== Switching branches

You can switch between branches of a Git repository. Branches are local settings. In other words, you can use the same plugin in multiple sets, but work with different branches. This is useful if you want to, for example, use a stable branch in your active plugin set and test a new feature in an inactive plugin set at the same time.

[WARNING]
.Automatischer Pull in Plugin Build 2
====
Starting on 25 July, 2022, a new deployment process (Plugin Build 2) will be gradually released on all plentymarkets systems. The new deployment process automatically updates Git plugins that you've installed via a branch to the newest version.

When your system has been switched to Plugin Build 2, you'll be informed about the changes when you deploy a plugin set that contains Git plugins for the first time. If you want to prevent the deployment process from updating a Git plugin automatically, <<#switching-commits, switch to a commit>>
====

include::partial$git-branch-wechseln-en_gb.adoc[]

[#switching-commits]
=== Switching commits

If you want to use a different state of your repository, but didn’t create a branch for it, you can also access individual commits.

include::partial$git-commit-wechseln-en_gb.adoc[]