= CRM
:keywords: customer data, contact data, ticket system, emails, email, EmailBuilder, newsletter, quick search, messenger, messages, companies, company
:description: Learn how to manage your contact and company data, use the ticket system for your customer communication and send emails and newsletters.
:id: IWIIOPV
:author: team-crm

In this area, you find all information about xref:crm:create-contact.adoc#[creating] and xref:crm:edit-contact.adoc#[editing] contact data records – from the address via orders to properties, documents and much more. +
Create xref:crm:preparatory-settings.adoc#create-customer-class[customer classes], xref:crm:preparatory-settings.adoc#create-type[types] and use the xref:crm:preparatory-settings.adoc#use-discount-system[discount types] in plentymarkets. Manage your xref:crm:companies.adoc#[companies] and link contacts with the companies.

Use the xref:crm:quick-search.adoc#[quick search] to retrieve at a glance all information that is saved for a contact or the address data of a guest order. In this area, you can also download - in accordance with GDPR - all data that is saved for a contact or a guest order and anonymise data records.

Use the xref:crm:messenger-testphase.adoc#[messenger] to create messages that can be assigned to your contacts. Messages are only visible in your plentymarkets back end and cannot be accessed by your contacts.

All emails that are sent with plentymarkets are based on email templates. Learn how to xref:crm:sending-emails.adoc#1200[create email templates] and how to xref:crm:sending-emails.adoc#2300[set up the automatic despatch] for your email templates. Use the xref:crm:emailbuilder-testphase.adoc#[new EmailBuilder] to create your templates even faster and more intuitive.

Furthermore, learn how to use the xref:crm:using-the-ticket-system.adoc#[ticket system] for your customer communication and how to retain control over orders that are still unpaid with the help of the xref:crm:ar-list.adoc#[AR list].

Set up a xref:crm:sending-newsletters.adoc#[newsletter] service in your system to automatically inform your customers at regular intervals about news in your plentyShop.

[.row]
====
[.col-md-6]
.Managing contacts and companies
======
* xref:crm:preparatory-settings.adoc#create-customer-class[Creating a customer class]
* xref:crm:preparatory-settings.adoc#create-type[Creating a customer type]
* xref:crm:create-contact.adoc#[Creating a contact]
* xref:crm:edit-contact.adoc#[Editing a contact]
* xref:crm:preparatory-settings.adoc#use-discount-system[Using the discount system]
* xref:crm:ar-list.adoc[Showing the accounts receivable list]
* xref:crm:companies.adoc#[Managing companies]
======

[.col-md-6]
.Sending emails
======
* xref:crm:sending-emails.adoc#100[Saving the email server's login details]
* xref:crm:sending-emails.adoc#200[Selecting the encryption for email communication]
* xref:crm:sending-emails.adoc#1200[Creating an email template]
* xref:crm:emailbuilder-testphase.adoc#[Creating an email template with the new EmailBuilder]
======
====

[.row]
====
[.col-md-6]
.Using the ticket system
======
* xref:crm:using-the-ticket-system.adoc#700[Adding a role]
* xref:crm:using-the-ticket-system.adoc#800[Adding a type]
* xref:crm:using-the-ticket-system.adoc#900[Adding a status]
* xref:crm:using-the-ticket-system.adoc#1100[Adding a topic]
* xref:crm:using-the-ticket-system.adoc#1600[Creating a ticket]
======

[.col-md-6]
.Setting up newsletters
======
* xref:crm:sending-newsletters.adoc#[Sending newsletters]
======
====

[.row]
====
[.col-md-6]
.Finding data records
======
* xref:crm:quick-search.adoc#[Using the quick search]
======

[.col-md-6]
.Managing messages
======
* xref:crm:messenger-testphase.adoc#[Using the messenger]
======
====
