= CRM
:keywords: customer data, contact data, ticket system, emails, email, EmailBuilder, newsletter, quick search, messenger, messages, companies, company, address data, addresses
:description: Learn how you manage contact, company and address data and customer communication in the CRM area of plentymarkets.
:author: team-crm

In this area, you find all information about xref:crm:create-contact.adoc#[creating] and xref:crm:edit-contact.adoc#[editing] contact data records – from the address via orders to properties, documents and much more. +
Create xref:crm:preparatory-settings.adoc#create-customer-class[customer classes] and xref:crm:preparatory-settings.adoc#create-type[types] and use the xref:crm:preparatory-settings.adoc#use-discount-system[discount system] in plentymarkets. Manage your xref:crm:companies.adoc#[companies] and link contacts with the companies.

Use the xref:crm:quick-search.adoc#[quick search] to retrieve at a glance all information that is saved for a contact or the address data of a guest order. In this area, you can also download - in accordance with GDPR - all data that is saved for a contact or a guest order and anonymise data records.

Use the xref:crm:messenger-testphase.adoc#[messenger] for the email despatch and email receipt in plentymarkets or create internal messages that are only visible in your plentymarkets back end and cannot be accessed by your contacts.

All emails that are sent with plentymarkets are based on email templates. Use the xref:crm:emailbuilder.adoc#[EmailBuilder] to create your templates quickly and intuitively.

Furthermore, learn how to use the xref:crm:using-the-ticket-system.adoc#[ticket system] for your customer communication and how to retain control over orders that are still unpaid with the help of the xref:crm:ar-list.adoc#[AR list].

// Set up a xref:crm:sending-newsletters.adoc#[newsletter] service in your system to automatically inform your customers at regular intervals about news in your plentyShop.

[.row]
====
[.col-md-6]
.Managing contacts and companies
======
* xref:crm:preparatory-settings.adoc#create-customer-class[Creating a customer class]
* xref:crm:preparatory-settings.adoc#create-type[Creating a customer type]
* xref:crm:create-contact.adoc#[Creating a contact]
* xref:crm:edit-contact.adoc#[Editing a contact]
* xref:crm:preparatory-settings.adoc#use-discount-system[Using the discount system]
* xref:crm:ar-list.adoc#[Showing the accounts receivable list]
* xref:crm:companies.adoc#[Managing companies]
======

[.col-md-6]
.Sending emails
======
* xref:crm:emailbuilder.adoc#email-server-login-details[Saving the email server login details]
* xref:crm:emailbuilder.adoc#[Creating an email template with the EmailBuilder]
* xref:crm:sending-emails.adoc#1200[Creating an email template via the client settings (old way)]
======
====

[.row]
====
[.col-md-6]
.Sending and receiving messages
======
* xref:crm:messenger-testphase.adoc#[Using the messenger]
* xref:crm:messenger-testphase.adoc#create-message[Creating a new message]
======

[.col-md-6]
.Finding data records
======
* xref:crm:quick-search.adoc#[Using the quick search]
* xref:crm:quick-search.adoc#download-all-data[Downloading all data]
* xref:crm:quick-search.adoc#anonymise-data-record[Anonymising a data record]
======
====

[.row]
====
[.col-md-6]
.Using the ticket system
======
* xref:crm:using-the-ticket-system.adoc#1600[Creating a ticket]
======
====
