= CRM
:keywords: customer data, contact data, emails, email, EmailBuilder, messenger, messages, companies, company, address data, addresses
:description: Learn how you manage contact, company and address data and customer communication in the CRM area of plentysystems.
:author: team-crm

In this area, you find all information about xref:crm:create-contact.adoc#[creating] and xref:crm:edit-contact.adoc#[editing] contact data records – from the address via orders to properties, documents and much more. +
Create xref:crm:preparatory-settings.adoc#create-customer-class[classes] and xref:crm:preparatory-settings.adoc#create-type[types] and use the xref:crm:preparatory-settings.adoc#use-discount-system[discount system] in plentysystems. Manage your xref:crm:companies.adoc#[companies] and link contacts with the companies.

In the *CRM » Contacts* menu, you can see at a glance all information that is saved for a xref:crm:contacts.adoc#[contact or the address data of a guest order]. In this area and in compliance with GDPR, you can also xref:crm:edit-contact.adoc#download-all-data[download all data] that is saved for a contact or a guest order, xref:crm:edit-contact.adoc#anonymise-data-record[anonymise data records] and xref:crm:edit-contact.adoc#convert-guest-account[plentyShop and marketplace guest order into regular contact data records].

Use the xref:crm:messenger.adoc#[messenger] for the email despatch and email receipt in plentysystems or create internal messages that are only visible in your plentysystems back end and cannot be accessed by your contacts.

All emails that are sent with plentysystems are based on email templates. Use the xref:crm:emailbuilder-overview.adoc#[EmailBuilder] to create your templates quickly and intuitively.

Furthermore, learn how to retain control over orders that are still unpaid with the help of the xref:crm:ar-list.adoc#[AR list].
