= EmailBuilder
:keywords: EmailBuilder, E-Mail Builder, E-mail templates, Widgets, email templates, document attachment, Email variables, twig expressions, Email despatch, Code widget, Widgets E-Mail-templates, Variables
:description: Learn how to use the EmailBuilder in plentysystems and create email templates with a modular concept using widgets and variables.
:author: team-crm
:page-aliases: emailbuilder-testphase.adoc, emailbuilder.adoc

In this topic, you can find all details about the EmailBuilder. +
All emails that are sent with plentysystems to your xref:crm:contacts.adoc#[contacts] are based on templates. You create and manage templates with the EmailBuilder in the *CRM » EmailBuilder* menu.

Watch this link:https://www.youtube.com/watch?v=LnQ2MpTZEQw[video^] to learn more about the EmailBuilder.

[TIP]
.Email templates are sent in multipart format
====
The email templates in the EmailBuilder use the multipart format. This means that the emails are sent in an HTML and in a text version at the same time. +
This ensures that your emails can be read by all recipients, even if their email client restricts or completely disables the display of HTML in emails. On the other hand, the HTML versions of your emails that you designed are displayed for the recipients whose email client allows the display of HTML. The advantage for you is that you only have to maintain one email template.
====

The EmailBuilder is a modular construction kit for quickly creating and editing your email templates via drag-and-drop. The EmailBuilder consists of 2 views: the configuration manager and the editor.

* With the configuration manager, you create folders and, if needed, sub-folders, templates as well as templates for your footer and your header.

* With the editor, you fill your templates, headers and footers with content. You can create a template for an invoice, for example, and use this template for all invoices that are sent to your customers in the future.

You can then use the header and footer templates in the email templates as desired. Header and footer are globally active; changes you make to the header and footer affect the rest of all existing templates and all other templates that you will create in the future.

Create xref:crm:emailbuilder-work-with-emailbuilder.adoc#create-text-block[text blocks], thus ready-made text modules that save you a lot of time and effort, particularly if you often answer the same questions or deal with the same problems. You can then use the text blocks also in the xref:crm:messenger.adoc#use-text-blocks[Messenger]. 

To be even more flexible when designing your templates, you can use the xref:crm:emailbuilder-expert-mode.adoc#[expert mode].

The header, the footer and the settings in the template such as the name, the subject etc. form the framework of your email, so to say. +
The content of the template is formed with the xref:crm:emailbuilder-work-with-emailbuilder.adoc#insert-widget[widgets] and xref:crm:emailbuilder-variables-twig-expressions.adoc#available-variables[variables]. In the emails that are sent to your customer, the variables will then be replaced with the correct content. For example: The variable `Delivery address First name and last name` will be replaced in the email with the first name and the last name of the contact from the delivery address.

In case of certain events, e.g. if a new order is placed in your plentyShop or when a contact subscribes to a newsletter, your system xref:crm:emailbuilder-automate-email-despatch.adoc#[automatically creates emails from these templates] and sends them to your contacts.

[discrete]
== Quick access to the sub-pages

Click on one of the following entries in the list to be forwarded directly to the corresponding manual page:

* xref:crm:emailbuilder-preparatory-settings.adoc#[Carrying out the preparatory settings]
* xref:crm:emailbuilder-work-with-emailbuilder.adoc#[Working with the EmailBuilder]
* xref:crm:emailbuilder-automate-email-despatch.adoc#[Automating the email despatch]
* xref:crm:emailbuilder-expert-mode.adoc#[Using the expert mode]
* xref:crm:emailbuilder-variables-twig-expressions.adoc#[Using variables and twig expressions]
* xref:crm:emailbuilder-code-examples.adoc#[Code examples]
