= Automating the email despatch
:keywords: set up automatic email despatch, Email accounts assistant, set up event procedure, assistant for email despatch, set up email despatch to multiple email addresses
:description: Learn how to automate the email despatch to your customers.
:page-pagination:
:author: team-crm

You have multiple options in plentysystems to automate the email despatch to your customers.

* <<#automatic-email-despatch, Setting up the automatic email despatch>>
* <<#set-up-event-procedures, Setting up event procedures>>
* <<#email-despatch-to-multiple-email-addresses, Setting up the email despatch to multiple email addresses>>

[IMPORTANT]
.Viewing the template usage
====
Click on material:assessment[] *Template usage* within the template to see in which areas of your system the EmailBuilder template has been used. The following filters are available:

* Email accounts assistant - Automatic despatch
* Messenger inbox
* Messenger automation
* Order event
* Order procedure
* Process

For further information, refer to the xref:crm:emailbuilder-work-with-emailbuilder.adoc#template-usage[Working with the EmailBuilder] user manual page.
====

[#automatic-email-despatch]
== Setting up the automatic email despatch

Set up the automatic despatch in the *Email accounts* assistant. You can find the assistant in the *Setup » Client » Global » Email accounts* menu. +
You link different events with xref:crm:emailbuilder-work-with-emailbuilder.adoc#create-template[templates] that you have already created.

Refer to the xref:crm:emailbuilder-preparatory-settings.adoc#email-automatic-despatch[Carrying out the preparatory settings] user manual page.

[#set-up-event-procedures]
== Setting up event procedures

Besides the possibility to <<#automatic-email-despatch, link events and templates>>, you can also set up event procedures in the *Setup » Orders » Events* menu. Define an event, activate one or more filters and decide which procedures your system should carry out automatically when the event occurs.

For example, you can use filters to trigger a procedure once a contact has placed a certain number of orders or has been assigned another class. The procedure could send an email that includes a coupon. For further information, refer to the xref:automation:event-procedures.adoc#[Event procedures] page.

[#email-despatch-to-multiple-email-addresses]
== Setting up the email despatch to multiple email addresses

Go to *Setup » Orders » Events* to set up an xref:automation:event-procedures.adoc#[event procedure] that will send an email to your customers and employees when the event that you determined occurs in your plentyShop.

Add in the event procedure the procedure *Customer > Send email* and select the appropriate template as well as the recipients to send the email to multiple recipients at the same time once the selected event occurs.

The following recipients are available:

* Customer
* Warehouse
* Invoice address from order
* Invoice address from order
* Contact email business
* Contact email private
* Contact email PayPal
* available owners

You can either send the same template to all recipients or select a separate template each.
