= FAQ: CRM
:keywords: FAQ CRM, questions and answers CRM
:description: On this page, you can find questions and answers about the CRM area.
:author: team-crm

On this page, you can find questions and answers about the CRM area. We are continuously adding more questions and answers to this list.

[#faq-section-addresses]
== Addresses

[#faq-delete-address-not-possible]
[.collapseBox]
.Why am I not able to delete addresses?
--
A customer calls you and informs you that his address has changed. You open the contact data record, search for the address and want to delete it. Why is this not possible? +
If the address is linked with an order, you _cannot_ delete this address. This is related to the legal retention period in compliance with GoBD.

To avoid that “old” addresses of your contacts are used by mistake when manually creating an order, the new address has to be set as primary invoice and delivery address. Once this setting has been carried out, this new primary address will be shown by default when creating a new order in your plentymarkets back end.

*_Note:_* Your customer is able to delete the old address or to edit existing addresses in his My account area. These addresses are, however, not completely removed or synchronised with your plentymarkets back end. This is why the addresses are still visible in your plentymarkets system.
--

[#faq-address-not-selectable]
[.collapseBox]
.I cannot see the country in the contact data record. Why?
--
You want to manually create a new contact but the desired country is not available in the *Country* drop-down list?

In order to be able to select the country from the drop-down list in the contact data record, you have to activate the country first. Go to *Setup » Orders » Shipping » Settings* » Tab: *Shipping profiles*. Search for the desired country and set it to material:check_circle[] *Active*.
--

[#faq-guest-orders-section]
== Guest orders

[#faq-guest-order-plentyshop-not-found]
[.collapseBox]
.I cannot find any guest orders in the contact UI. Why?
--
In order to be able to work GDPR-compliant, _no_ contact data record is created for guest orders that are coming into your system via the plentyShop. Only the address data from the order is saved. This data that is saved in your plentymarkets system can therefore _not_ be found in the *CRM » Contacts* menu. +
The address data of the person who ordered as a guest in your plentyShop can only be found via the quick search in the *CRM » Quick search* menu.

*_Note:_* The situation is different for guest orders that are imported in your system via marketplaces. In these cases, a contact data record is created.

*Guest orders in the CRM » Quick search menu:*

* In case of guest orders via your plentyShop, the saved data record consists only of the address and the corresponding order. A contact ID is _not_ assigned. But, the symbol material:done[] is shown in the overview in the *Guest* column.

* In case of a guest order via a marketplace, a contact ID is assigned and the symbol material:done[] is shown in the overview’s *Guest* column.
--

[#faq-gdpr-anonymise-section]
== GDPR / Anonymising and deleting customer data

[#faq-delete-customer-data]
[.collapseBox]
.How can I delete contact data in compliance with GDPR?
--
A customer asks you to delete her data from your system. To be in compliance with GDPR, you are obliged to delete or make the customer’s data illegible. You have to do following: 

* Go to *CRM » Quick search*.
* Search for the data record and open it.
* Click on icon:user-secret[] (*Anonymise data record*) in the upper line.
* → A window opens. Here, you have to enter the contact ID again to confirm the anonymisation action. +
*_Important:_* This anonymisation action _cannot_ be undone.
* Click on *Anonymise*.

The following data is anonymised:

* First and last name of the contact

The following data is deleted:

* Addresses and address relations
* Address options
* Order relations
* Contact options
* Any relation to a company
* Bank details
* Order confirmation URLs become invalid

Inform the customer that her data has now been deleted from your system. If in doubt, consult a specialist lawyer on how best to formulate this message.

*_Note:_* If the button *Anonymise data record* is deactivated in the data record that you want to delete, it means that this data record is a guest order. In this case, the button is deactivated because the data record is not a contact. Deleting or making the data illegible in such way that no reference to this person is given any longer is _not_ needed for guest orders. 

For further information, refer to the xref:crm:quick-search.adoc#anonymise-data-record[Quick search] page.
--

[#faq-anonymise-button-contacts]
[.collapseBox]
.I cannot find the button to anonymise customer data. Where is it?
--
It is most likely that you are looking for the button in the wrong menu. Anonymising contact data is only possible via the *CRM » Quick search* menu and _not_ via the *CRM » Contacts* menu. 

For further information about anonymising contact data, refer to the box <<#faq-delete-customer-data, How can I delete contact data in compliance with GDPR?>> and to the xref:crm:quick-search.adoc#anonymise-data-record[Quick search] page.
--

[#email-templates]
== Email templates
 
[#faq-practical-example-tracking-url]
[.collapseBox]
.How can I send an email template with the tracking URL to my customers once the package number is available at the order?
--
You would like to send an email template that contains the tracking URL to your customers as soon as the order has been successfully registered with the shipping service provider and the package number is available at the order? 

Just have a look at this xref:crm:practical-example-send-tracking-url.adoc#[practical example] where we explain step by step which settings you need to carry out in your plentymarkets system.
--

[#emailbuilder-migration-old-templates]
== EmailBuilder: Migration of old templates

[.collapseBox]
.plenty migrates the old email templates from my system to the new EmailBuilder version. What does that mean and do I need to to anything after the migration?
--
As announced in this forum thread, the templates that you created in the past in the *Setup » Client » [Select client] » Email » Templates* menu will be migrated automatically to the new EmailBuilder. Also the structure and the variables from the old templates will be transferred.

*Todo: Check the content of the migrated templates*

Due to the complexity of some templates, it is unfortunately not possible to guarantee that all template content will be migrated correctly.

Therefore, check the content of the migrated templates.

*Todo: Check linked email templates that are sent in an automated way*

Check also in your entire plentymarkets system all menus where you linked email templates that are sent in an automated way based on a certain event. These are the following menus:

* Event procedures
* Ticket event procedures
* (*Setup » Client » [Select client] » Email » Automatic* menu)
* Processes
* Procedure manager
* Ticket procedure manager

*Todo: Manually transfer multi-language templates*

If you have already created a template in multiple languages, you have to manually adjust the content of them in the new EmailBuilder. Use the copy function to do so.

Further details about the new EmailBuilder can be found in our xref:crm:emailbuilder.adoc#[user manual].

--

// == Email despatch
