= FAQ: CRM
:keywords: FAQ CRM, questions and answers CRM
:description: On this page, you can find questions and answers about the CRM area.
:author: team-crm

On this page, you can find questions and answers about the CRM area. We are continuously adding more questions and answers to this list.

[#faq-section-addresses]
== Addresses

[#faq-delete-address-not-possible]
[.collapseBox]
.Why am I not able to delete addresses?
--
A customer calls you and informs you that his address has changed. You open the contact data record, search for the address and want to delete it. Why is this not possible? +
If the address is linked with an order, you _cannot_ delete this address. This is related to the legal retention period in compliance with GoBD.

To avoid that “old” addresses of your contacts are used by mistake when manually creating an order, the new address has to be set as primary invoice and delivery address. Once this setting has been carried out, this new primary address will be shown by default when creating a new order in your plentymarkets back end.

*_Note:_* Your customer is able to delete the old address or to edit existing addresses in his My account area. Also you as a seller can adjust the addresses in the customer’s My account area. These deleted or adjusted addresses are, however, not completely removed or synchronised with your plentymarkets back end. This is why the addresses are still visible in your plentymarkets system.
--

[#faq-address-not-selectable]
[.collapseBox]
.I cannot see the country in the contact data record. Why?
--
You want to manually create a new contact but the desired country is not available in the *Country* drop-down list?

In order to be able to select the country from the drop-down list in the contact data record, you have to activate the country first. Go to *Setup » Orders » Shipping » Settings* » Tab: *Shipping profiles*. Search for the desired country and set it to material:check_circle[] *Active*.

*_Note:_* If you set the country of delivery to *Active*, it is automatically available to be selected in your plentyShop by customers.
--

[#faq-delivery-county-backoffice-active]
[.collapseBox]
.I want to have a country of delivery visible in my plentymarkets back end only, but not in my online shop. Is this possible?
--
Yes, this is possible. To be able to select this country for example in the contact data record’s drop-down list, you have to set this country to *Back office active*. Go to *Setup » Orders » Shipping » Settings* » Tab: *Shipping profiles*. Search for the desired country and set it to material:flag[] *Back office active*.
--

[#faq-supplier-delivery-country-active]
[.collapseBox]
.How can I activate a country for suppliers only?
--
You want to select in a supplier’s contact data record a country that is not available in the list, but you don’t want this country to be selectable in other menus of your back end nor your plentyShop? 

To be able to select this country for example in the drop-down list of a supplier’s contact data record, you have to set this country to *Supplier is active*. Go to *Setup » Orders » Shipping » Settings* » Tab: *Shipping profiles*. Search for the desired country and set it to material:person[] *Supplier is active*.
--

[#faq-guest-orders-section]
== Guest orders

[#faq-guest-order-plentyshop-not-found]
[.collapseBox]
.I cannot find any guest orders in the contact UI. Why?
--
In order to be able to work GDPR-compliant, _no_ contact data record is created for guest orders that are coming into your system via the plentyShop. Only the address data from the order is saved. This data that is saved in your plentymarkets system can therefore _not_ be found in the *CRM » Contacts* menu. +
The address data of the person who ordered as a guest in your plentyShop can only be found via the quick search in the *CRM » Quick search* menu.

*_Note:_* The situation is different for guest orders that are imported in your system via marketplaces. In these cases, a contact data record is created.

*Guest orders in the CRM » Quick search menu:*

* In case of guest orders via your plentyShop, the saved data record consists only of the address and the corresponding order. A contact ID is _not_ assigned. But, the symbol material:done[] is shown in the overview in the *Guest* column.

* In case of a guest order via a marketplace, a contact ID is assigned and the symbol material:done[] is shown in the overview’s *Guest* column.
--

[#faq-gdpr-anonymise-section]
== GDPR / Anonymising and deleting customer data

[#faq-delete-customer-data]
[.collapseBox]
.How can I delete contact data in compliance with GDPR?
--
A customer asks you to delete her data from your system. To be in compliance with GDPR, you are obliged to delete or make the customer’s data illegible. You have to do following: 

* Go to *CRM » Quick search*.
* Search for the data record and open it.
* Click on icon:user-secret[] (*Anonymise data record*) in the upper line.
* → A window opens. Here, you have to enter the contact ID again to confirm the anonymisation action. +
*_Important:_* This anonymisation action _cannot_ be undone.
* Click on *Anonymise*.

The following data is anonymised:

* First and last name of the contact

The following data is deleted:

* Addresses and address relations
* Address options
* Order relations
* Contact options
* Any relation to a company
* Bank details
* Order confirmation URLs become invalid

Inform the customer that her data has now been deleted from your system. If in doubt, consult a specialist lawyer on how best to formulate this message.

*_Note:_* If the button *Anonymise data record* is deactivated in the data record that you want to delete, it means that this data record is a guest order. In this case, the button is deactivated because the data record is not a contact. Deleting or making the data illegible in such way that no reference to this person is given any longer is _not_ needed for guest orders. 

For further information, refer to the xref:crm:quick-search.adoc#anonymise-data-record[Quick search] page.
--

[#faq-anonymise-button-contacts]
[.collapseBox]
.I cannot find the button to anonymise customer data. Where is it?
--
It is most likely that you are looking for the button in the wrong menu. Anonymising contact data is only possible via the *CRM » Quick search* menu and _not_ via the *CRM » Contacts* menu. 

For further information about anonymising contact data, refer to the box <<#faq-delete-customer-data, How can I delete contact data in compliance with GDPR?>> and to the xref:crm:quick-search.adoc#anonymise-data-record[Quick search] page.
--

[#faq-area-contacts-plentyshop]
== Contact / plentyShop

[#faq-log-into-shop]
[.collapseBox]
.Why is my contact not able to log into the shop anymore?
--
If your contact cannot log into your plentyShop anymore, this may have the following reasons:

* The sub-type of the email address was changed from *private* to *business*.
* The contact has entered a wrong password several times in a row.

If the contact enters the wrong password in your plentyShop 4 times in a row, the contact will be blocked for the login for 24 hours and receives the message in the plentyShop to contact the administrator. With one click, you unlock the contact’s login and your contact is able to log into the your plentyShop again as usual. For further information, refer to the xref:crm:edit-contact.adoc#unlock-login[Editing a contact] page.
--

[#email-templates]
== Email templates
 
[#faq-practical-example-tracking-url]
[.collapseBox]
.How can I send an email template with the tracking URL to my customers once the package number is available at the order?
--
You would like to send an email template that contains the tracking URL to your customers as soon as the order has been successfully registered with the shipping service provider and the package number is available at the order? 

Just have a look at this xref:crm:practical-example-send-tracking-url.adoc#[practical example] where we explain step by step which settings you need to carry out in your plentymarkets system.
--

[#faq-email-templates-new]
[.collapseBox]
.Why is there a "[NEW]" in front of some email templates?
--
If `[NEW]` is written in front of your email templates, this means that these templates are <<#emailbuilder-migration-old-templates, migrated email templates>>. You can edit these templates at any time in the *CRM » EmailBuilder* menu.
--

[#emailbuilder-migration-old-templates]
== EmailBuilder: Migration of old templates

[.collapseBox]
.plenty migrates the old email templates from my system to the new EmailBuilder version. What does that mean and do I need to to anything after the migration?
--
As announced in this link:https://forum.plentymarkets.com/t/neue-funktionen-des-emailbuilders-inkl-migration-bestehender-vorlagen-new-features-of-emailbuilder-incl-migration-of-existing-templates/693489[forum thread^], the templates that you created in the past in the *Setup » Client » [Select client] » Email » Templates* menu will be migrated automatically to the new EmailBuilder. Also the structure and the variables from the old templates will be transferred.

*Todo: Check the content of the migrated templates*

Due to the complexity of some templates, it is unfortunately not possible to guarantee that all template content will be migrated correctly.

Therefore, check the content of the migrated templates.

*Todo: Check linked email templates that are sent in an automated way*

Check also in your entire plentymarkets system all menus where you linked email templates that are sent in an automated way based on a certain event. These are the following menus:

* Event procedures
* Ticket event procedures
* Automatic despatch (*Setup » Assistants » Basic setup* menu » Assistant: *Email accounts* » Step: *Automatic despatch*)
* Processes
* Procedure manager
* Ticket procedure manager

*Todo: Manually transfer multi-language templates*

If you have already created a template in multiple languages, you have to manually adjust the content of them in the new EmailBuilder. Use the copy function to do so.

You can find a practical example with instructions which settings to check after the migration of the old email templates on the user manual page xref:crm:practical-example-migration-templates.adoc#[EmailBuilder: Todo after the migration of the old email templates]. +
Further details about the new EmailBuilder can be found in our xref:crm:emailbuilder.adoc#[user manual].
--

[#email-despatch]
== Sending emails 

[#activate-live-mode]
[.collapseBox]
.Where can I deactivate the test mode/activate the live mode for the email despatch?
--
Go to *Setup » Assistants » Basic setup* and open the *Email accounts* assistant. Go to the *Login details* step. In the area *Would you like to activate the live mode?*, you can find the checkbox *Activate live mode*.

Activate (material:check_box[role=skyBlue]) this checkbox to activate the live mode. +
If this checkbox is not activated (material:check_box_outline_blank[]), the test mode is activated. This means that in test mode, all emails are only sent to the saved email address. This makes sense in order to check the settings before switching to live mode. 

Activating the live mode applies globally for the entire email despatch in plentymarkets. Thus, it also applies for the email despatch via the messenger.
--

[#prioritisation-event-procedures]
[.collapseBox]
.How are the email addresses saved in plentymarkets prioritised?
--
The email address from the invoice address has priority over the email address from the contact options. If no email address is saved in the invoice address, the email address from the contact options is taken as fallback. This fallback applies if you select in the event procedure the option *Contact* for the procedure *Customer > Send email*. The following prioritisation applies: The private email address has priority over the business email address.
--

[#email-despatch-to-multiple-different-email-addresses]
[.collapseBox]
.How can I send an email to multiple different email addresses?
--
Set up an event procedure in the *Setup » Orders » Events* menu. After you selected the desired event, select the procedure *Customer > Send email* afterwards. There, you can select the following recipients:

* Invoice address from order
* Invoice address from order
* Contact email business
* Contact email private
* Contact email PayPal

You can either select the same or a separate email template for each of these recipients. This way, an email will be sent to the above mentioned recipients at the same time once the selected event occurs.
--

[#coupons]
== Coupons

[#cancelled-coupons]
[.collapseBox]
.I would like to activate a cancelled coupon code. Can I do that?
--
No. Coupon codes that have already been cancelled cannot be activated again. +
This is because a relation to an order already exists. This means that a coupon that has already been redeemed is not valid any longer, even if the order itself has been cancelled. +
In this case, you have to generate new coupon codes in the *Orders » Coupons* menu. How this works, is described on the xref:orders:coupons.adoc#generate-coupon-codes[Coupons] page.
--
