= Guidelines: Switching from ticket system to Messenger
:keywords: guidelines switching to Messenger, switch to Messenger, switch from ticket system to Messenger, Ticket system Messenger switch, what to take into consideration when switching from ticket system to Messenger
:description: These guidelines describe the settings to be carried out for switching from the ticket system to the Messenger.
:author: team-crm

[IMPORTANT]
.About these guidelines
====
These guidelines are aimed at all sellers who have already worked with the ticket system in the past and are now switching to the Messenger. +
The guidelines are designed to enable a smooth transition from the ticket system to the Messenger and show you step by step which settings you should carry out in the Messenger. +
Please note that these guidelines focus on the common use cases known from practice and cannot take every individual setting into account.
====

<<#table-overview-switch-ticket-system-messenger>> shows an overview which settings are described on this page and in which menu you have to carry out the settings. +
Click on the link to get redirected to the corresponding chapter.

[[table-overview-switch-ticket-system-messenger]]
.Overview: Settings for switching from ticket system to Messenger
[cols="2,2"]
|====
|Setting |Menu path

| <<#assign-rights, Assigning rights>>
| *Setup » Account management » Roles*

| <<#define-roles-and-owners, Defining roles>>
| *Setup » CRM » Messenger » Roles*

| <<#create-groups-types-statues, Creating groups, types and statuses>>
| *Setup » CRM » Messenger » Groups, types and statuses*

| <<#create-tags-for-messenger, Creating tags for the Messenger>>
| *Setup » Settings » Tags*

| <<#link-ebay-account-with-messenger, eBay setup>> (optional)
| *Setup » CRM » Messenger » Marketplaces » eBay*

| <<#set-up-inboxes-for-receiving-sending-emails, Setting up inboxes for receiving and sending emails>> (complete *Messenger configuration* assistant)
|*Setup » CRM » Messenger » Inboxes*

| <<#set-up-forwarding-with-external-provider, Setting up an email forwarding with external providers>> to ensure that emails will arrive in your system
| _Setup with external provider_

| <<#create-folders, Creating folders>>
| *CRM » Messenger*

| <<#save-filters, Saving filters>> and activate them for other users, if needed
| *CRM » Messenger*

| <<#set-up-automations, Setting up automations>>
| *Setup » CRM » Messenger » Automation*

a| General settings:

* <<#automatically-empty-trash, Automatically emptying trash>>
* <<#automatically-archive-conversation, Automatically archiving conversations>>
* <<#whisper-mode-for-all-users, Globally activating the whisper mode for all users>>
| *Setup » CRM » Messenger » General*

|====

[#assign-rights]
== Assigning rights

:rights-purpose: see and create messages in the messenger
:right-one: pass:quotes[*CRM > Message > Read*]
:right-two: pass:quotes[*CRM > Message > Create*]
:right-three: pass:quotes[*CRM > Messenger > Read*]
:right-four: pass:quotes[*CRM > Messenger > Update*]
:right-five: pass:quotes[*CRM > Messenger > Create*]
:right-six: pass:quotes[*Comments > Read*]
:right-seven: pass:quotes[*Comments > Create*]
:right-eight: pass:quotes[*Setup > Tag > Read*]
:right-nine: pass:quotes[*Setup > Tag > Create*]

include::_includes:partial$rights.adoc[]

[#define-roles-and-owners]
== Defining roles and owners

A role provides information about the members of your staff involved in handling a conversation. Roles can be individually assigned for each conversation. +
A conversation can be assigned to multiple owners. This requires you to define different roles for the Messenger. You can individually assign these roles to an owner. 

[IMPORTANT]
Creating a role is a prerequisite for being able to add an owner to the conversation.

[#create-role]
=== Creating a role

Proceed as described below to create a role. Later, you first select a role in the conversation and can then <<#assign-role-and-owner, assign an owner>>.

[.instruction]
Creating a role:

. Go to *Setup » CRM » Messenger » Roles*. +
icon:map-signs[] *_Or:_* If you are already in the Messenger menu, click on the left side below the material:settings[] *Settings* area on material:group[] *Roles*.
. Click on material:add[] *New role*.
. Enter a position number, if needed.
. Enter the German and English names for the role.
. Click on material:save[] (*Save*).

[#assign-role-and-owner]
=== Assigning a role and owner to a conversation

After you have <<#create-role, created the role>>, you can assign an owner to Messenger conversations. +
You can assign a role and an owner in 2 ways: 

* for each conversation individually by clicking on material:more_vert[] in the Messenger overview
** Click <<#context-menu-conversation-change-owner, here>> to get redirected to the *Changing the owner* chapter.
* via the group function in the Messenger overview.
** Click <<#group-function, here>> to get redirected to the *Using the group function* chapter.

[#create-groups-types-statues]
== Creating groups, types and statuses

Proceed as described below to create groups, types and statuses for the Messenger. Note that only a person with Admin rights is able to create groups, types and statuses.

[#create-group]
=== Creating a group

Proceed as described below to create a new group for the Messenger.

[.instruction]
Creating a group:

. Go to *Setup » CRM » Messenger » Groups, types and statuses*. +
icon:map-signs[] *_Or:_* If you are already in the Messenger menu, click on the left side below the material:settings[] *Settings* area onmaterial:checklist_rtl[] *Groups, types and statuses*.
. Click on material:add[]*Add group*.
. Enter a position number.
. Enter the German name for the group.
. Click on material:add[] (*Add language*) to add the group name also in English.
. Click on material:save[]. +
→ The group is created and the area *Types* is automatically opened.

[#add-type-status]
=== Adding a type and status

You can create as many different types for a Messenger group as you want, e.g. `Customer inquiry` or `Complaint`. In the next step, you can add a status for the type with a colour and a progress indicator in percent. You can create groups, types and statuses in German and English.

The following describes how to create a status and a type directly one after the other. If you would like to add further statuses to an existing type at a later stage, the description in the <<#add-new-status-to-existing-type, Adding a new status to an existing type>> chapter will help you.

[.instruction]
Adding a type:

. Go to *Setup » CRM » Messenger » Groups, types and statuses*. +
icon:map-signs[] *_Or:_* If you are already in the Messenger menu, click on the left side below the material:settings[] *Settings* area onmaterial:checklist_rtl[] *Groups, types and statuses*.
. Open the group.
. In the *Types* area, click on material:add[] *Add type*.
. In the *Details* area, enter a number for the position.
. In the *Names* area, enter a name for the type.
. Enter a name for the type. +
*_Optional:_* Click on material:add[]*Add language* to add the type name also in English.
. *Save* (material:save[]) the settings. +
→ The type opens and the *Status* area appears.
. In the *Status* area, click on material:add[] *Add status*.
. In the *Details* area, select a percentage value from the *Progress* drop-down list.
. In the *Colour* field, enter the link:https://html-color-codes.info/webfarben_hexcodes/[Hex code^] of the colour or select the colour by clicking on material:rectangle[].
. In the *Position* area, enter a number for the position.
. *Save* (material:save[]) the settings.
. In the *Names* area, enter a name for the status. +
*_Optional:_* Click on material:add[] *Add language* to add the status name also in English.
. *Save* (material:save[]) the settings.

[#add-new-status-to-existing-type]
=== Adding a new status to an existing type

For each <<#add-type-status, type>> in the Messenger, determine one or multiple statuses with percentage indicator and colour to track the processing progress of your conversations.

[.instruction]
Adding a new status to an existing type:

. Go to *Setup » CRM » Messenger » Groups, types and statuses*. +
icon:map-signs[] *_Or:_* If you are already in the Messenger menu, click on the left side below the material:settings[] *Settings* area onmaterial:checklist_rtl[] *Groups, types and statuses*.
. Open the group.
. In the *Types* area, click in the line of the type that you want to add a status to.
. In the *Status* area, click on material:add[] *Add status*.
. In the *Details* area, select a percentage value from the *Progress* drop-down list.
. In the *Colour* field, enter the link:https://html-color-codes.info/webfarben_hexcodes/[Hex code^] of the colour or select the colour by clicking on material:rectangle[].
. In the *Position* area, enter a number for the position.
. *Save* (material:save[]) the settings.
. In the *Names* area, enter a name for the status. +
*_Optional:_* Click on material:add[] *Add language* to add the status name also in English.
. *Save* (material:save[]) the settings.

The selected type and the selected status are then shown in the open conversation next to the tags. You can also search for conversations with certain types and statuses and sort the conversations in the overview in ascending and descending order by the type and status (material:arrow_upward[] and material:arrow_downward[]).

[#create-tags-for-messenger]
== Creating tags for the Messenger

Tags are keywords that make grouping conversations and messages very easy.

Create tags for the Messenger to assign these tags to the conversations and messages and to filter for these tags in the Messenger. You can also automatically set or remove tags for the conversation later when a defined event occurs if you set up a corresponding automation in Messenger.

It is important that you create the required tags for the *Messenger conversation* area. Otherwise, the tags will not be available in the Messenger.

[.instruction]
Creating a tag:

. Go to *Setup » Settings » Tags*.
. Click on material:add[]. +
→ A pop-up window will open.
. Enter a name for the tag.
. Select the background colour that the tag should have. To do so, click on material:stop[role=black] and select the colour.
. Check the details in the summary.
. If you think it’s okay, click on *CREATE TAG*.

Create as many more tags as you like according to this scheme.

[#link-ebay-account-with-messenger]
== Linking the ebay account with the Messenger (optional)

You can directly retrieve the eBay messages from your linked eBay account and import them into the Messenger. Of course, you can also use the Messenger to type your replies. Your customer receives the message via the eBay messaging system.

Because linking the eBay account with the Messenger is an optional setting, we do not list in detail here which settings you need to carry out, but simply refer to the xref:crm:messenger.adoc#manage-ebay-messages-in-messenger[Managing eBay messages in the Messenger] chapter.

[#set-up-inboxes-for-receiving-sending-emails]
== Setting up inboxes for receiving and sending emails

If you want to use the Messenger for sending and receiving emails, you have to complete the *Messenger configuration* assistant. You can find the assistant in the *Setup » CRM » Messenger » Inboxes* menu.

[TIP]
You have to complete the assistant once for each inbox that you want to create. +
You can assign tags to each inbox to be able to <<#create-tags-for-messenger, filter>> for these tags later.

In the following, the single steps of the *Messenger configuration* assistant are explained.

=== Step: Service activation

Activate the Messenger service for this inbox here. If the button is blue (material:toggle_on[]), the service is activated.

=== Step: Email forwarding

A cryptic email address is automatically created here that builds the forwarding email address. Copy this email address and set up an <<#set-up-forwarding-with-external-provider, email forwarding to this address with your external providers>>. This way, you ensure that your emails will be forwarded automatically. Note that you cannot change this cryptic email address.

In the lower part, enter all email addresses that are allowed to send messages to the cryptic, forwarding email address stated above. You can add as many email addresses as you like by clicking on *Add new entry* (material:add[]). Existing email addresses can be deleted by clicking on *Remove entry* (material:delete[]). +
*_Note:_* At least one email address has to be entered here.

=== Step: Settings for sending emails

Save the login details of the email inbox here that you want to use to send emails from. This is necessary to make sure that your system is able to send and receive emails via the Messenger.

After having entered the login details, select the encryption method and enter the sender email address and the sender name. This email address and this name will be shown to the recipients of your emails from this inbox.

*_Note for mailbox.org mailboxes:_* Enter the port *465* and select *SSL* as encryption method.

In the *Default inbox*, you can activate (material:check_box[role=skyBlue]) the option *Determine as default inbox* to make sure that this inbox is preselected when writing new messages in the Messenger.

Select also in this step an email template for the email despatch.

[IMPORTANT]
.Live mode in *Email accounts* assistant has to be activated
====
In the xref:crm:emailbuilder.adoc#email-server-login-details[Login details] step of the *Email accounts* assistant, the option *Activate live mode* has to be activated (material:check_box[role=skyBlue]) in the *Would you like to activate the live mode?* area. This ensures that the test mode will be deactivated and all emails sent to the respective recipients. 

Activating the live mode applies globally for the entire email despatch in plentysystems. Thus, it also applies for the email despatch via the Messenger.
====

[TIP]
.Use the default template *Messenger default NEW*
====
We recommend to use the default template *Messenger default NEW* for the Messenger. This template is already available in your system in the *CRM » EmailBuilder* menu in the *Default templates* folder. You can, of course, adjust this template according to your needs. This template will be automatically preselected when you write a new conversation.

The template contains the following variables:

* Name of the client in the subject line, displayed as {{globals.clientName}}
** So called _twig expressions_ in double curly brackets need to be inserted in the template’s subject because it is not possible to use “normal” variables in the subject line. For further information, refer to the xref:crm:emailbuilder.adoc#variables-emailbuilder[Available variables and twig expressions] chapter on the xref:crm:emailbuilder.adoc#[EmailBuilder] page.
* Full name
* Signature in HTML format
====

Of course, you can select a template in this step that you have created yourself in the *CRM » EmailBuilder* menu.

=== Step: Settings for receiving emails

Save the name of the inbox here. Also select one or multiple tags that should be assigned to the messages when these messages are received from and sent to the forwarded addresses.

Also select one or multiple subscribers from the list so that they will be informed when a new message is in the inbox.

In the *Owners and roles* area, select a default role and a default owner from the lists. 

In the *Group, type and status* area, select a default group, a default type and a default status that will be assigned to new messages in this inbox.

If you activate (material:check_box[role=skyBlue]) the option *Activate notifications* in the last section, you will be informed in your plentysystems back end next to the material:notifications[] symbol as soon as a
<<#notification-new-message, new message is available in the Messenger>>.

[#set-up-forwarding-with-external-provider]
== Setting up an email forwarding with the external provider

To ensure that the emails arrive in your system, you must set up forwarding to Messenger with your external provider. +
We have compiled a list of common providers and have created brief instructions for each of these providers on what settings you need to carry out to set up email forwarding to the Messenger.

Please have a look at this xref:crm:practical-example-email-forwarding-messenger.adoc#[page] whether an instruction is available for your provider.

[#create-folder]
== Creating a folder

To give your conversations more structure and clarity, you can create as many folders as you like and automatically assign your conversations to these folders later.

Proceed as described below to add a new folder.

[.instruction]
Adding a new folder:

. Go to *CRM » Messenger*.
. In the side navigation on the left, click in the line material:3p[]*My folders* on material:more_vert[] (*More options*) and then on material:add[]*Add new folder*. +
→ The *Add new folder* window opens.
. Enter a name for the folder.
. Click on *Save*. +
→ The folder is created. You can find the folder under material:3p[] *My folders*.

By clicking on the folder, only the conversations contained in this folder are shown in the overview. 

Don’t forget to set up a corresponding <<#set-up-automations, automation>> later to ensure that certain conversations end up in the folders you have defined.

[#save-filters]
== Saving filters

When you start a search, your selected filters are displayed up top as so-called “chips”. You can save these filters to apply them again more quickly and easily in the future.

[.instruction]
Saving the current filter:

. Start a search.
. Click on *Saved filters* (material:bookmarks[]).
. Click on material:bookmark_border[] *Save current filter*.
. Enter a name for the filter.
. Activate (material:toggle_on[role=skyBlue]) the option *Set as default filter* if this filter should be the default one.
. Activate (material:toggle_on[role=skyBlue]) the option *Create filter for all users* so that this filter is available for all users.
. Click on *SAVE*. +
→ The filter now appears under *Saved filters* (material:bookmarks[]).

[TIP]
Use drag-and-drop to arrange the filters in a specific order by clicking on *Move* (material:drag_indicator[]). Click on material:delete[] to delete a filter.

[#apply-saved-filters]
=== Applying saved filters

Proceed as follows to apply an already saved filter for the search.

[.instruction]
Applying saved filters:

. Click on *Saved filters* (material:bookmarks[]).
. Click on a filter that you have already created. +
→ The search is started and the filter settings are displayed up top as so-called “chips”.

[TIP]
You find all <<#save-current-filter, saved filters>> in the folder material:bookmarks[] *My filters* in the side navigation of the Messenger. By clicking on the corresponding filter, the filter settings are applied to the folder that you have currently opened.

[#default-filter]
=== Setting a default filter

To make sure that you don’t have to select a filter that you use quite often from the list of your <<#apply-saved-filters, saved filters>> every time when opening the *CRM » Messenger* menu, you can set a created filter as default filter. Every time when you open the Messenger, this filter will be automatically applied.

You can set a filter as default filter directly when creating it or you can set the filter as default in the overview afterwards. +
In the line of the saved filter, click on material:star[] *Set as default*. If you want to set another filter as default filter, deactivate the currently selected default filter by clicking on material:star_outline[] *Do not use as default*.

[#set-up-automations]
== Setting up automations

If you worked with events and procedures in the ticket system, you can now realise this via the Messenger menu *Automation*.

The possibilities in the Messenger automation are diverse, especially when it comes to combining filters, triggers and actions. Therefore, we cannot list all possible scenarios due to the countless and individual setting options.

Learn on the xref:crm:messenger.adoc#[Messenger] page in the xref:crm:messenger.adoc#automate-events[Automating events in the Messenger] chapter which filters, triggers and actions are available.

On the xref:crm:practical-example-messenger-automation.adoc#[Practical example: Setting up Messenger automations] page, you can find some common examples for setting up automations in the Messenger. This page is constantly being updated and filled with new examples.

[#general-settings]
== Carrying out general settings

In the *General* area of the Messenger, you can set the number of days after which <<#automatically-empty-trash, conversations will be permanently deleted from trash>>. And you can also set the number of days here after which <<#automatically-archive-conversation, conversations should be automatically moved to the archive>>. +
Also you can globally activate the <<#whisper-mode-for-all-users, whisper mode for all users>> in your system. 

[#automatically-empty-trash]
=== Automatically emptying trash

Set after how many days deleted messages and deleted conversations should be automatically removed from trash. To do so, proceed as described below. Note that only a person with Admin rights is able to carry out this setting.

[.instruction]
Automatically emptying trash:

. Go to *Setup » CRM » Messenger » General*. +
icon:map-signs[] *_Or:_* If you are already in the Messenger menu, click on the left side below the material:settings[] *Settings* area on material:folder_open[] *General*.
. In the *Automatically empty trash* area, activate (material:toggle_on[role=skyBlue]) the option *Activate “Automatically empty trash” function*.
. In the *Number of days (max. 5 years)* area, enter a number.
. *Save* (material:save[]) the settings. +
→ All deleted messages and conversations that are contained in the trash will be automatically removed from trash after the number of days you entered here.

[#automatically-archive-conversation]
=== Automatically archiving conversations

Set the number of days after which conversations should be automatically moved to the archive. To do so, proceed as described below. Note that only a person with Admin rights is able to carry out this setting.

[.instruction]
Automatically archiving conversations:

. Go to *Setup » CRM » Messenger » General*. +
icon:map-signs[] *_Or:_* If you are already in the Messenger menu, click on the left side below the material:settings[] *Settings* area on material:folder_open[] *General*.
. In the *Automatically archive conversations* area, activate (material:toggle_on[role=skyBlue]) the option *Activate “Automatically archive conversations” function*.
. In the *Number of days (max. 5 years)* area, enter a number.
. *Save* (material:save[]) the settings. +
→ All conversations will be automatically moved to the archived after the number of days entered here.

[#whisper-mode-for-all-users]
=== Globally activating the whisper mode for all users

If you have mainly worked with comments, i.e. internal messages, in the ticket system, you can use whisper mode in the Messenger. +
You can activate the whisper mode globally for all users. This means that the whisper mode is automatically activated for all new conversations and when replying to existing messages. Of course, you can switch anytime back to “normal” messages.

[.instruction]
Activating the whisper mode for all users:

. Go to *Setup » CRM » Messenger » General*. +
icon:map-signs[] *_Or:_* If you are already in the Messenger menu, click on the left side below the material:settings[] *Settings* area on material:folder_open[] *General*.
. In the *Activate whisper mode automatically for all users* area, activate (material:toggle_on[role=skyBlue]) the option *Activate whisper mode*.
. *Save* (material:save[]) the settings. +
→ The whisper mode is now automatically activated for all users when creating a new conversation and when replying to an existing message.
