= Practical example: Setting up Messenger automations
:keywords: Messenger automation, automate events, example messenger automation, confirmation in case of new email from customer, confirmation in case of new conversation from contact
:description: This practical example contains common examples how to automate events in the Messenger.
:author: team-crm

On this page, you will find common examples for setting up automations in the Messenger. This page is constantly being updated and filled with new examples.

[#confirmation-new-conversation]
== Setting up a confirmation email in case of a new email from customers

In the following, you can find an example with a step-by-step instruction how you set up that your customers will automatically receive a confirmation email once they sent you an email with an inquiry.

[.instruction]
Setting up a confirmation email in case of a new email from customers:

. Go to *Setup » CRM » Messenger » Automation*. +
icon:map-signs[] *_Or:_* If you are already in the Messenger, expand the area material:settings[] *Settings* on the left side below the trash folder and click on material:auto_mode[] *Automation* to get redirected to the *Setup » CRM » Messenger » Automation* menu.
. Click on material:add[] *Add automation*.
. Enter the a name for the automation, e.g. `New conversation / confirmation email`.
. Select the setting *Event-based* as *Type*.
. In the *Trigger* area, click on *Add trigger* (material:add[]).
. Select the trigger *New conversation from contact*.
. In the *Filter* area, click on *Add filter* (material:add[]).
. Select the filter *Inbox of conversation*.
. Select the appropriate inbox from the drop-down list, e.g. `Customer service`.
. Select the filter *Group, type and status of conversation*.
. Select the appropriate group from the drop-down list *Group*, e.g. `General`.
. Select a type from the drop-down list *Type*, e.g. `Inquiry`.
. Select the appropriate status from the drop-down list *Status*, e.g. `New`.
. In the *Action* area, click on *Add action* (material:add[]).
. Select the action *Send email*.
. Select the template from the drop-down list. +
→ First, you have to create the template in the xref:crm:emailbuilder.adoc#[EmailBuilder]. +
→ In our example, the template’s name is _Messenger: Confirmation - New conversation_.
. In the *Email addresses of recipients* field, enter further email addresses if you want to add further recipients to the conversation. +
Existing recipients, i.e. the senders of the original email, receive the email automatically. +
If users have subscribed for the conversation, they will receive a notification in the back end and not an email if you selected in the field *Email to all subscribers of the conversation* further down below the setting *Yes*.
. In the *Users* field, you can select (material:check_box[role=skyBlue]) further subscribers and add them to the conversation.
. Click on material:save[] (*Save*).
