= Carrying out the preparatory settings
:keywords: address layout, address layout documents, customer class, contact class, customer type, type, create customer class, create type, create properties for contact, customer properties, customer properties on documents, tags for contacts, contact tags, tags for customers, customer tags, discount system, discount on customer class, customer class discount, discount on net value of items, discount on payment method, sales price as discount, manual discount for customers, manual discount for contacts, grant discount
:descriptions: Learn which preparatory settings you have to carry out in order to work with contact data records in plentymarkets.
:page-pagination:
:author: team-crm

You have to carry out some preparatory settings to be able to optimally use the contact management in the *CRM » Contacts* menu.

By clicking on an entry in the following list, you will be directly forwarded to the corresponding sub-chapter:

* <<#address-layout, Setting up the address layout for location-based order documents>>
* <<#assign-rights, Assigning rights for back end users>>
** <<#activate-rights-areas-buttons, Activating rights for certain areas and buttons in the contact data record>>
** <<#activate-view-other-users, Activating views for other users>>
* <<#create-customer-class, Creating a customer class>>
* <<#create-type, Creating a type>>
* <<#create-tags, Creating tags>>
* <<#properties-introduction, Creating properties>>
* <<#use-discount-system, Using the discount system>> (optional)

[#address-layout]
== Setting up the address layout for location-based order documents

In the *Setup » CRM » Address layout* menu, you can individually set up address layouts for your countries of delivery for your xref:orders:order-documents-new.adoc#[location-based order documents] such as delivery notes, invoices, credit notes and return slips. The address layouts for the countries of delivery _Germany_, _France_ and the _United Kingdom_ are already available in your plentymarkets system by default. Proceed as described below to set up an address layout for your order documents.

[.instruction]
Setting up the address layout for location-based order documents:

. Go to *Setup » CRM » Address layout*.
. Click on *New layout* (material:add[]).
. Carry out the desired settings. Note <<#table-set-up-address-layout>>.
. *Save* (material:save[]) the settings.

[[table-set-up-address-layout]]
.Setting up the address layout for location-based order documents
[cols="1,3"]
|====
|Setting |Explanation

2+^| *General settings*

| *Layout name*
|What’s the name of the layout?

| *Use as standard address layout*
|Do you want to use this layout as standard layout? If so, activate the toggle button (material:toggle_on[role=skyBlue]). In the overview on the left side, the default address layout is marked with a star (material:star[]).

2+^| *Field list* +
If required, enter English and German names for the field names in order that this names can be displayed when designing the address layout.

2+^| *Switch to layout design* +
Click on material:sync_alt[] to switch to the layout design. The areas *Countries*, *Layout* and *Fields* appear.

| *Countries*
|Select one country or multiple countries from the list to which the address layout should apply.

| *Layout* / +
*Fields*
|Drag the address fields from the *Fields* area to the *Layout* area. By doing so, you individually design the address layout for each country of delivery by using drag-and-drop. +
*_Tip:_* It is possible to add further rows (maximum number of rows:{nbsp}6) and to remove individual fields and complete rows. Blank rows can also be used. The number of fields per row is _not_ limited.

|====

[discrete]
=== Activating the new address layout in the location-based order document

In order that the address layout is automatically displayed on your location-based order documents, you have to carry out a setting in the corresponding order document. Your plentymarkets system automatically checks the country of delivery saved in the order and displays the corresponding order document in the layout listed in the *Setup » CRM » Address layout* menu. To do so, proceed as described below.

[.instruction]
Activating the new address layout in the location-based order document:

. Go to *Setup » Client » [Select client] » Locations » [Select location] » Documents »[Select document]*.
. In the *Basic settings: _Document name_* area, activate (material: check_box[role=skyBlue]) the option *New address layout*. +
→ The option above *Structure of the invoice/delivery address* is hidden and the document is displayed in the address layout that you saved in the *Setup » CRM » Address layout* menu.
. *Save* (material:save[]) the settings.


[discrete]
=== Assigning rights for back end users for the address layout

:rights-purpose: see and edit the address layouts
:right-one: pass:quotes[*CRM > Address layout > Show*]
:right-two: pass:quotes[*CRM > Address layout > Create*]
:right-three: pass:quotes[*CRM > Address layout > Update*]

include::_includes:partial$rights.adoc[]

[#assign-rights]
== Assigning rights for back end users

:rights-purpose: pass:quotes[work with the *CRM » Contacts* menu]
:right-one: pass:quotes[*CRM > Address > Show*]
:right-two: pass:quotes[*CRM > Contact > Show*]
:right-three: pass:quotes[*Setup > Property > Show*]
:right-four: pass:quotes[*Setup > Tag > Show*]

include::_includes:partial$rights.adoc[]

[#activate-rights-areas-buttons]
=== Activating rights for certain areas and buttons in the contact data record

If persons with *Back end* access rights are not able to see certain xref:crm:edit-contact.adoc#details-individual-areas[areas in the contact data record] and/or buttons and functions within these areas, check the rights in the corresponding user account. You can find the user accounts in the *Setup » Settings » User » Rights » User* menu.

[.collapseBox]
.Rights for areas, buttons and functions in contact data record
--

<<#table-missing-areas-contact-data-record>> lists the rights that need to be activated in the user account if a person with *Back end* access rights cannot see areas within the contact data record.

[[table-missing-areas-contact-data-record]]
.Rights for areas in the contact data record
[cols="2,2"]
|====
|Missing area in contact data record |Required right in user account

| xref:crm:edit-contact.adoc#orders[Orders], xref:crm:edit-contact.adoc#account[Account]
|Orders > Show +
Orders > Order status > Show

| xref:crm:edit-contact.adoc#properties[Properties]
|Setup > Property > Show +
Setup > Property > Relation > Show

| xref:crm:edit-contact.adoc#bank-details[Bank details]
|CRM > Bank details > Show

| xref:crm:edit-contact.adoc#tickets[Tickets]
|CRM > Ticket > Show

| xref:crm:edit-contact.adoc#company[Company]
|CRM > Company > Show

| xref:crm:edit-contact.adoc#messenger[Messenger]
|CRM > Message > Show

|====

<<#table-missing-buttons-contact-data-record>> lists the rights that need to be activated in the user account if a person with *Back end* access rights cannot see buttons and/or functions within certain areas of the contact data record.

[[table-missing-buttons-contact-data-record]]
.Rights for buttons and functions in contact data record
[cols="2,2"]
|====
|Missing button/function in contact data record |Required right in user account

| xref:crm:edit-contact.adoc#plentyshop-login[plentyShop login], xref:crm:edit-contact.adoc#change-password-manually[Changing the password], input field with login URL, xref:crm:edit-contact.adoc#copy-open-link[copy button], xref:crm:edit-contact.adoc#copy-open-link[open link]
|CRM > Password > Edit

| Overview, xref:crm:edit-contact.adoc#orders[orders], new order, new offer etc.
|Orders > Create

|Overview, tickets, xref:crm:edit-contact.adoc#tickets[button to create new ticket]
|CRM > Ticket > Create

|Overview, xref:crm:search-contact.adoc#context-menu-overview[Messenger button in context menu]
|CRM > Message > Show

|Messenger, xref:crm:edit-contact.adoc#messenger[button to create new message]
|CRM > Message > Create

|Bank details, xref:crm:edit-contact.adoc#bank-details[Add/edit/delete bank details]
|CRM > Bank details > Create +
CRM > Bank details > Update +
CRM > Bank details > Delete

| Companies, xref:crm:edit-contact.adoc#company-not-linked-yet[delete relation to contact], xref:crm:edit-contact.adoc#delete-company-relation[delete relation to company]
|CRM > Company > Create +
CRM > Company > Update +
CRM > Company > Delete

|Contact details context menu, xref:crm:edit-contact.adoc#delete-contact-detail-view[Delete button]
|CRM > Contact > Delete

|Overview, xref:crm:edit-contact.adoc#delete-contact-overview[context menu], button xref:crm:search-contact.adoc#context-menu-overview[delete contact]
|CRM > Contact > Delete

|====
--

[#activate-view-other-users]
=== Activating views for other users

At a later point, you might probably set up a xref:crm:create-contact.adoc#[new view to create a new contact] or a xref:crm:edit-contact.adoc#edit-view[new view to edit an existing contact]. It is possible to activate these views also for other users in your plentymarkets system to allow them to work with these views. +
The default view is activated for all users by default. You can also withdraw the right for the default view for a user.

All settings that are related to activating views are done in the user account in the *Setup » Settings » User » Rights » User* menu in the *Views* area.

* Activating views for users to create a new contact data record: +
Go to the user account and open in the *Views* area the *CRM > Contacts > New contact > Custom views* area. Select (material:check_box[role=skyBlue]) the desired views from the list.

* Activating views for users to edit an existing contact data record: +
Go to the user account and open in the *Views* area the *CRM > Contact details > Custom views* area. Select (material:check_box[role=skyBlue]) the desired views from the list.

[#create-customer-class]
== Creating a customer class

Use customer classes to categorise your customer base according to specific criteria. For example, you can create a customer class for consumers (B2C) that displays gross prices for the items in your plentyShop. Create another customer class for sellers (B2B) that displays net prices for the items in your plentyShop. Further options are discounts based on the net value of your items, discounts based on the payment method or discount scales for a selected customer class.

*_Note_*: If a contact registers in your plentyShop and selects the salutation *Company*, the customer class that you created for B2B contacts will apply automatically.

[TIP]
.Tip: Consider a concept for types and classes in advance
====
It is recommended to create a concept for organising your customer base into types and classes before saving customer data. By doing this, you will save time later on. For example, types and classes are automatically assigned when the initial configuration is missing. Decide which types and classes you need, create them and assign them to the contacts when upon creation.
====

You can create and individually configure as many customer classes as you like in the *Setup » CRM » Classes* menu. An ID is automatically assigned to customer classes. This ID is displayed to the left of the customer classes’ name in the overview. However, customer classes are _not_ ordered by ID. Instead, the order is set using the option *Position*.

If you create a new customer class, this customer class is available in the detail view of the contact in the *CRM » Contacts » [Open contact]* menu.

[.instruction]
Creating a customer class:

. Go to *Setup » CRM » Customer classes*.
. Click on the *New customer class* tab.
. Carry out the desired settings. Note <<#table-create-customer-class>>.
. *Save* (material:save[]) the settings.

[[table-create-customer-class]]
.Creating a customer class
[cols="1,3"]
|====
|Setting |Explanation

|[#intable-customer-class-minimum-order-value]*Minimum order value*
|Enter the minimum order quantity if you want to require customers to order a specific quantity of items or if you want to require them to order a minimum quantity to get a discount.

|[#intable-customer-class-name]*Name*
|Enter a name for the new customer class, e.g. *wholesaler* or *premium customer*.

|[#intable-customer-class-position]*Position*
|If you do not enter a position, the next available position number is assigned automatically. The position is primarily used to sort the customer classes in the menu. It is relevant e.g. in combination with the visibility of item prices in the plentyShop. This can be set under *Display of the prices in the online store*.

|[#intable-customer-class-terms-of-payment]*Payment due date, percentage for early payment discount, early payment discount and valuta*
|Payment due date, percentage for early payment discount, days for early payment discount and valuta are the terms of payment. +
*_Important:_* The terms of payment that are saved in the contact data record have priority over the values entered here. +
The terms of payment are saved in the xref:orders:managing-orders.adoc#intable-payment-terms-order[order settings]. The values in the contact data record have also priority over the values in the order settings. The values can be manually adjusted or entered in the order if no values are saved in the contact data record or in the customer class. The terms of payment saved in the order are then shown on the xref:orders:order-documents.adoc#intable-payment-terms-documents[documents]. Note the example xref:crm:companies.adoc#example-terms-of-payment[Terms of payment with valuta, payment due date, days for early payment discount and percentage for early payment discount] on the xref:crm:companies.adoc#[Companies] page.

|[#intable-customer-class-contact-id]*Customer ID*
|Enter the ID of the contact who should receive the multi-invoices that are created from xref:orders:managing-orders.adoc#800[multi-orders]. Multi-orders are generated for this customer class and the invoice is sent to that contact.

|[#intable-customer-class-discount-type]*Discount type*
|Select the discount type. The number of options that are visible depends on which discount type was selected. If you do no want to offer a discount, select the option *No discount*. Further information and explanations about the discount types in plentymarkets can be found in the <<#use-discount-system, Using the discount system>> chapter.

|[#intable-customer-class-volume-discount]*Volume discount*
|Select whether the value entered in the *Setup » Item » Sales prices* menu under *Minimum quantity* should be taken into account or not.

|[#intable-customer-class-allowed-payment-methods]*Allowed payment methods*
|Select which of the payment methods that are available in the plentyShop should be permitted for this customer class. +
All of the available payment methods are selected by default. When you integrate new payment methods, you have to permit them here. This is because new payment methods are not automatically included in the list of allowed payment methods. +
*_Important:_* Pay attention to which xref:fulfilment:preparing-the-shipment.adoc#1000[payment methods are blocked in the shipping profiles] that you want to use for this customer class. Check those settings to make sure that they are compatible with the settings you make here. If you want to permit a payment method for a customer class, you should make sure it is _not_ blocked in the shipping profiles. Make sure that the corresponding customer class is _not_ blocked either.

|[#intable-customer-class-payment-instruction]*Payment instruction*
|The payment instructions that are saved here are displayed on invoices. For example, you could enter payment information that relates to a specific customer class.

|[#intable-customer-class-display-online-shop]*Display of the prices in the online shop*
|Select whether *gross* or *net* prices are displayed in the online shop. +
*_Important:_* This option only sets how prices are displayed. It does not influence the way prices are calculated for the customer class. This option is particularly important for the customer class with position 1\. This customer class is automatically assigned to contacts if no customer class was selected in the contact data record.
|====

You can link sales prices with customer classes. Go to *Setup » Items » Sales prices* and select one of the customer classes that you created under the setting *Class*. For further information, refer to the xref:item:prices.adoc#100[Sales prices and price calculation] page.

[#create-type]
== Creating a type

Types are used to classify and differentiate contacts. Some types are available by default in your plentymarkets system and _cannot_ be deleted. These types are *Customer*, *Sales representative*, *Supplier*, *Partners*, *Manufacturer* and *Interested party*. The types that you created are available in the *Type* drop-down list in the *CRM » Contacts* menu.

When creating a new contact data record, the type *Customer* is automatically set by default. Customers who were assigned to the type *Supplier* are available in certain drop-down lists, e.g. in a variation’s *Supplier* tab.

Proceed as described below to create types.

[.instruction]
Creating a type:

. Go to *Setup » CRM » Types*.
. Click on *Add type* (material:add[role=green]).
. Enter a name.
. *Save* (icon:save[role="green"]) the settings.

[#create-tags]
== Creating tags for contacts

You can assign tags to your contacts and filter them by tags in the contact overview. Tags are keywords that you can assign to your contacts.

Which user rights are required and how to create tags is explained below.

[TIP]
.Tags for contacts
====
Only those tags can be selected in the contact data record that were created in the *Setup » Settings » Tags* menu for the area *Contacts.*
====

[#rights-tags]
=== Assigning rights for back end users

include::_includes:page$tags-rights.adoc[]

[#create-tag]
=== Creating tags

include::_includes:page$tags-creation.adoc[]

[#search-tag]
=== Searching for tags

include::_includes:page$tags-search.adoc[]

[#properties-introduction]
== Creating properties

Properties are frequently occurring information that you can use to further characterise your contacts. For example, you can save in every contact data record how the contact wants to be contacted by you and if they want to have your new product catalogue.

You can show most of the properties also on your <<#properties-on-documents, order documents>>.

You can also create <<#group-properties, property groups>> to get a better overview in case you are working with a large number of properties.

The following sub-chapters describe how to <<create-properties, create>>, <<#link-properties, link>>, <<#search-properties, search for>> and <<#delete-properties, delete>> properties and how to <<#group-properties, group>> as well as <<#import-properties, import>> and <<#export-properties, export>> them.

[#create-properties]
=== Creating new properties

Go to *Setup » Settings » Properties » Configuration* and create properties. Afterwards, <<#link-properties, link>> the property with the contact. Proceed as described below to create a property.

include::_includes:page$creating-new-properties.adoc[]

[#property-details]
==== Details

include::_includes:page$creating-new-properties-details.adoc[tag=crm]

[#property-names]
==== Names

include::_includes:page$creating-new-properties-names.adoc[tag=crm]

[#property-selection-values]
==== Selection values

[IMPORTANT]
.Not visible for every type of property
====
You will only see this area if you are working with a property of the type *Selection* or *Multi selection*.
This area is invisible for all of the other property types.
====

include::_includes:page$creating-new-properties-selectionvalues.adoc[]

[#property-groups]
==== Groups

include::_includes:page$creating-new-properties-groups.adoc[]

[#property-visibilities]
==== Visibilities

include::_includes:page$creating-new-properties-visibilities.adoc[tag=crm]

[#property-options]
==== Options

include::_includes:page$creating-new-properties-options.adoc[tag=crm]

[#link-properties]
=== Linking properties with the contact

After you have created the property in the *Setup » Settings » Properties » Configuration* menu, you can link the property with the contact. To do so, proceed as described below.

[.instruction]
Linking the property with the contact:

. Go to *CRM » Contacts*.
. Search for the contact by means of the filter settings. Note the explanations about the filters on the xref:crm:search-contact.adoc#[Searching for a contact] page. +
→ The contacts that correspond to the search criteria entered are displayed.
. Click in the line of the contact to open the data record.
. Click on *Properties* on the left side. +
→ All properties that are available for the contact are displayed and you add them there.

////
letzten Satz in der Konfig prüfen.
////

[#properties-on-documents]
=== Showing properties on documents

You can show the contact properties on your xref:orders:order-documents.adoc#[order documents], such as on your offers.

Go to *Setup » Client » [Select client] » Locations » [Select location] » Documents » [Select document]* to create the template. In the document’s *Customer properties* area, you can see all properties that are available for the *Contact* area.

In order that the property is shown on your documents exactly as you want it, you have to rename the property in the text field right next to it. You could, for example, enter the text _Sales contact person_ for the property type *Short text* and your phone number for any queries for the property type *Whole number*.

*_Note:_* Do not forget to enter the coordinates for the X and Y axis in the field below to ensure that your content is correctly positioned on your document. Fur further information, refer to the xref:orders:order-documents.adoc#600[Order documents] page of the manual.

[TIP]
.Check how the properties are positioned on your document
====
You can easily check whether all properties are positioned as you want it:

* Open the contact data record in the *CRM » Contacts* menu.
* Click on *Orders* on the left side. +
→ The order opens in the *Orders » Edit order* menu.
* In the order, click on the *Receipts* tab.
* Select the document template that you used to set up the customer properties, e.g. _Offer_ from the drop-down list. +
→ The template opens.
* Check the correct positioning of the customer properties on the document.
====

[#group-properties]
=== Grouping properties

If you have lots of properties, then you can group them together so that it’s easier to keep track of them in your plentymarkets back end.

[#create-new-group]
==== Creating a new group

:crm:
include::_includes:page$creating-new-groups.adoc[]

:!crm:

[#work-with-properties]
=== Working with existing properties

[#search-properties]
==== Searching for properties

include::_includes:page$searching-for-properties.adoc[]

[#import-properties]
==== Importing properties

Use the import tool and the import type *Properties* to import properties into your plentymarkets system. The fields that you can use for mapping and matching are described on the page of the manual of the import type xref:data:elasticSync-properties.adoc#[Properties].

For general information about importing data into your plentymarkets system, refer to the xref:data:ElasticSync.adoc#[Using the import tool] page of the manual.

[#export-properties]
==== Exporting properties

:crm:
include::_includes:page$exporting-properties.adoc[]

:!crm:

[#delete-properties]
==== Deleting properties again

include::_includes:page$deleting-properties.adoc[]

[#use-discount-system]
== Using the discount system (optional)

[TIP]
.Setting up the discount system is optional
====
Setting up the discount system in plentymarkets is optional. Read over the discount options in the following sub-chapters and then decide whether you want to allow discounts, for example via the customer classes.
====

In plentymarkets, you have various possibilities for offering discounts. You may give your contacts a <<#customer-class-discount, customer class discount>>, a <<#discount-payment-method, discount based on the method of payment>> or a <<#discount-scale-net-value-of-items, discount scale based on the net value of items>>. Furthermore, you can save <<#discount-sales-price, sales prices as discounts>> and enter <<#discount-manually, manual discounts>>. Go to *Setup » CRM » Customer classes* to carry out the settings for the types of discounts. The following sub-chapters describe which settings you need to carry out in order to give discounts.

[#customer-class-discount]
=== Setting up a customer class discount

In a customer class, you can determine discounts that are only effective for this customer class. Furthermore, you have further configuration possibilities, such as activating the sales price’s volume discount. Make sure that the discounts can be added for each configuration.

Proceed as described below to save a discount for customer classes.

[.instruction]
Setting up a customer class discount:

. Go to *Setup » CRM » Customer classes*.
. Expand the customer class that the discount should be applied to (icon:plus-square-o[]).
. Select the option *Customer class discount* as *Discount type*. +
→ A further area to carry out settings opens.
. Under *Discount in %*, enter the percentage that you would like to have deducted.
. Select whether the *Volume discount* should be taken into consideration.
. Select which of the payment methods that are available in the plentyShop should be permitted for this customer class.
. Enter payment instructions. +
→ These payment instructions are displayed on invoices.
. Select whether the prices in the online shop should be shown in *gross* (including VAT) or *net* (excluding VAT).
. *Save* (material:save[]) the settings.

[#discount-scale-net-value-of-items]
=== Setting up a discount scale based on the net value of items

Would you like to reward your contacts with discounts when they regularly make large purchases in your plentyShop? If so, determine amounts that should be discounted based on the net value of items in the order.

[.instruction]
Setting up a discount scale based on the net value of items:

. Go to *Setup » CRM » Customer classes*.
. Expand the customer class that the discount scale should be applied to (icon:plus-square-o[]).
. Select the option *Discount scale based on net value of items* as *Discount type*. +
→ A table with further settings opens.
. Enter monetary amounts under the words *Minimum net value of items* in an ascending order.
. Under *Discount in %*, enter the percentage that you would like to have deducted in ascending order. +
→ If you enter 50, e.g. in the field *Minimum net value of items* and 2 in the field *Discount in %*, a 2% discount is offered for orders totalling £50 or more.
. Select whether the *Volume discount* should be taken into consideration.
. Select which of the payment methods that are available in the plentyShop should be permitted for this customer class.
. Enter payment instructions. +
→ These payment instructions are displayed on invoices.
. Select whether the prices in the online shop should be shown in *gross* (including VAT) or *net* (excluding VAT).
. *Save* (material:save[]) the settings.

[discrete]
==== How do your customers see the discount in your plentyShop?

The discount is calculated and displayed once the customer has finished putting items into their shopping cart and has gone to the checkout. Initially, only the total discount is displayed in the shopping cart. When the customer completes the order and clicks on Go to cashier, the discount is calculated for the individual variations in addition to the total discount and displayed accordingly.

[#discount-payment-method]
=== Setting up a discount based on the method of payment

With the discount type *Discount based on the method of payment* you offer customers a discount if they use one or more payment methods.

[TIP]
.Directly saving a discount based on the method of payment
====
Instead of configuring the settings in this menu, it is also possible to directly save a global discount for a payment method. An example is a discount in percent for the payment method *Cash in advance*. For further information, refer to the xref:payment:managing-payment-methods.adoc#[Managing payment methods] page of the manual. You are not able to completely customise the settings if you save a discount directly for a payment method. It is only possible to completely customise the settings when using the option *Discount based on the method of payment* in the *Setup » CRM » Customer classes* menu.
====

Proceed as described below to set up a discount based on one or more payment methods.

[.instruction]
Setting up a discount based on the method of payment:

. Go to *Setup » CRM » Customer classes*.
. Expand the customer class that the discount should be applied to (icon:plus-square-o[]).
. Enter a *Payment due date* in days, which you would like to permit for this customer class.
. Select the option *Discount based on method of payment* for the *discount type*. +
→ A table with further settings opens.
. Select one or several payment methods that the discount should be applied to.
. Under *Discount in %*, enter the percentage that you would like to have deducted.
. Select whether the *Volume discount* should be taken into consideration.
. Select which of the payment methods that are available in the online shop should be permitted for this customer class.
. Enter payment instructions. +
→ These payment instructions are displayed on invoices.
. Select whether the prices in the online shop should be shown in *gross* (including VAT) or *net* (excluding VAT).
. *Save* (material:save[]) the settings.

[#discount-sales-price]
=== Saving sales prices as discounts

A volume-related discount is created as own price in the *Setup » Item » Sales prices* menu. Using the option *Minimum quantity* in the *Settings* area, you specify for the sales price from which item quantity the discounted price should be valid. You can realise graduated prices by creating multiple sales prices accordingly and entering the desired minimum quantities.

The discounted sales price is activated once you set the option *Volume discount* in the customer class to *Include*. A customer receives the discount in case they belong to the customer class and in case they order at least the quantity saved for the sales price.

[.instruction]
Saving sales prices as discounts:

. Go to *Setup » Item » Sales prices*.
. Open the sales price.
. Enter a number in the *Settings* tab in the field *Minimum quantity*. This number determines from which item quantity the discounted price is valid.
. Activate the customer classes in the *Class* area for which the sales price should be valid.
. *Save* (icon:save[role="green"]) the settings.

For further information, refer to the xref:item:prices.adoc#100[Sales prices and price calculation] page.

[#discount-manually]
=== Manually entering a discount

Not only is it possible to automatically assign discounts, but it is also possible to manually assign a discount to some or all of the variations contained in an order. There are 2 ways to manually enter discounts: in the list view of the xref:orders:managing-orders.adoc#1300[order search] and in the editing window of an xref:orders:managing-orders.adoc#1530[order].

[#discount-single-item-order-search]
==== Entering a discount for individual items in the order search

If you would like to quickly assign discounts to individual variations within an order, you can do that directly in the order search. Proceed as described below to enter or edit a discount for individual items in the order search.

[.instruction]
Entering a discount for individual items in the order search:

. Go to *Orders » Edit orders*. +
→ The order search appears.
. Click on *Discount* on the right-hand side of an order (default value:{nbsp}0%). +
→ A window for entering the percentage opens.
. Enter the desired percentage of discount.
. *Save* (icon:save[role="green"]) the settings. +
→ The discount value appears and the discount is deducted from the variation.

[#discount-single-item-order]
==== Entering a discount for individual items in an order

The variations are displayed at the very bottom of the order overview. You can also assign discount values to individual variations here or you can edit discount values. Proceed as described below to enter or edit a discount for an item in the order.

[.instruction]
Entering a discount for individual items in an order:

. Go to *Orders » Edit orders*.
. Open the order that you want to discount. This is done by clicking on the order number.
. Click on *Edit* (icon:pencil[]) in the lower area of the order’s *Overview* tab.
. Select the percentage of discount from the *Discount* drop-down list.
. *Save* (icon:save[role="green"]) the settings.

[#discount-all-items-in-order]
==== Entering a discount for all items of an order

Proceed as described below to enter or edit a discount for all variations of an order.

[.instruction]
Entering a discount for all items of an order:

. Go to *Orders » Edit orders*.
. Open the order that you want to discount. This is done by clicking on the order number.
. Click on *Edit* (icon:pencil[]) in the lower area of the order’s *Overview* tab.
. Click on the link *Give discount on all items* below the variation list.
. Select the percentage value from the displayed drop-down list.
. Click on *Save* to the right of the drop-down list.
. *Save* (icon:save[role="green"]) the settings.
