= Quick search
:keywords: quick search, address search, search addresses, GDPR, guest access, guest order, order as a guest, search guest, anonymise customer, anonymise, delete customer data, delete data record, delete customer, delete contact, download all data of customer, download customer data, customer requests deletion of his data
:description: Learn how to use the quick search in plentymarkets to find contact data records and address data from guest orders.
:author: team-crm

Use the quick search to get an overview of all information that is saved for a contact or an address data record of a guest order. Learn on this page of the manual how to <<#download-all-data, download all data of a contact or guest order>> and how to <<#anonymise-data-record, anonymise data records>> in compliance with GDPR.

[NOTE]
.Guest orders coming into your system via plentyShop can only be found in the quick search
====
In order to be able to work GDPR-compliant, _no_ contact data record is created for guest orders that are coming into your system via the plentyShop. Only the address data is saved. This data that is saved in your plentymarkets system can therefore _not_ be found in the *CRM » Contacts* menu. The address data of the person who ordered as a guest in your plentyShop can only be found via the quick search. This is why you can only use the quick search to convert the data from the plentyShop guest order into a regular contact data record.

Further information about converting plentyShop guest orders into regular contact data records can be found in the <<#convert-guest-account, Converting a plentyShop and marketplace guest order into a contact data record>> chapter.
====

[#user-rights]
== Assigning rights for back end users

:rights-purpose: work with the quick search
:right-one: pass:quotes[*CRM > Contact > Show*]

include::_includes:partial$rights.adoc[]

For further information about the rights for the *CRM » Contacts* menu for back end users, refer to the xref:crm:preparatory-settings.adoc#assign-rights[Carrying out the preparatory settings] page.

[#search-data-record]
== Searching for a data record

Proceed as follows to search for data records via the quick search.

[TIP]
.Sort data records in ascending and descending order
====
For the following entries in the overview, you can click on the arrows (material:arrow_upward[] or material:arrow_downward[]) next to the entry to show the data records in ascending or descending order:

* ID 
* Rating
* First name
* Last name
* Number of orders
* Postcode
====

[.instruction]
Searching a data record in the quick search:

. Go to *CRM » Quick search*.
* *_Alternative 1:_* Click on material:search[] (*Search*) to get a list of all data records.
* *_Alternative 2:_* Enter a value in the search field and select the appropriate filter from the suggestion list. *_Example:_* If you enter a number, the possible filters with this ID will be suggested such as for example the contact ID.
* *_Alternative 3:_* Click on material:tune[] to narrow down the search results with filters.
. Note the explanations about the filters in <<#table-filter-quick-search>>.  +
*_Tip:_* You can enter multiple search terms into the search fields at one time. This makes your search run quicker and be more accurate.
. Click on material:search[] *Search*. +
→ The data records that correspond to the search criteria entered are shown in the overview. <<#table-settings-quick-search>> explains further setting options in the data record.

[[table-filter-quick-search]]
.Quick search filters
[cols="1,3"]
|====
|Setting |Explanation

| *ID*
|Each contact data record automatically receives a consecutive and unique ID. It doesn't matter if the data record was saved manually or automatically. 2 contacts never have the same ID. The ID is always a real number. For example, 00521 or ABC8354 are therefore invalid.

| *Name*
|Enter the first name and/or last name or the name of the company to search for the data records with this name or company name.

| *Contact data*
|In this field, you can search for the name, address, company, customer number and eBay name.

| *Email*
|Enter the complete email address to search for the data record with this email address.

| *Telephone*
|Enter the telephone number to search for the data record with this number. You can also search for parts of the telephone number. Enter at least 3 numbers.

| *Address*
|Enter the street name and/or house number. It is also possible to search only for parts of the street and parts of the house number.

| *Postcode*
|Enter the postcode. +
*_Note:_* The search is also carried out for postcodes that are saved in the address data records of the contact. It is also possible to search only for parts of the postcode. Enter at least 3 numbers.

| *Town*
|Enter the town that is saved in the data record. The search is also carried out for towns that are saved in the address data records of the contact. It is also possible to search only for parts of the town.

| *Country*
|Select a country to only display data records from this country. The country is saved within the contact data. +
Select the setting *All except Germany* to only display data records from all countries except Germany.

| *Tags*
|Select a tag to only search for data records with this tag.

| *Owner*
|Select the owner to only search for data records that are linked to this owner. The owner has to be saved in the contact data record. +
*_Important:_* Only owners for whom the *Customer* option has been activated in the *Owner* tab can be selected from the drop-down list.

| *Type*
|Select the type to only search for data records with this type.

| *Rating*
|Select the rating to only search for data records with this rating. 5 yellow stars are the best rating, 5 red stars are the worst rating.

| *Customer class*
|Select the customer class to only search for contacts with this class.

| *Client*
|Select a client to only display data records that correspond to this client. The client is saved within the contact data record. +
*_Important:_* Back end users can only select those clients that they have a right to access. Go to *Setup » Settings » User » Accounts* and set the rights in the user account in the xref:business-decisions:user-accounts-access.adoc#100[Rights] tab.

| material:replay[]
|Resets the selected filter criteria.

| material:search[] *SEARCH*
|Starts the search. The data records found are listed in the overview. +
*_Tip:_* Don’t choose any filters if you want to see all of the data records in the overview.

|====

[#save-current-filter]
=== Saving the current filter

When you start a search, your selected filters are displayed at the top as chips. You can save these filters to apply them again more quickly and easily in the future.

[.instruction]
Saving the current filter: 

. Start a search.
. Click on *Saved filters* (material:bookmarks[]).
. Click on material:bookmark_border[] *Save current filter*.
. Enter a name for the filter.
. Decide whether
** this filter should be <<#default-filter, set as default filter>> (material:toggle_on[role=skyBlue])
** this filter should be created for all users (material:toggle_on[role=skyBlue]).
. Click on *SAVE*. +
→ The filter now appears under *Saved filters* (material:bookmarks[]).

[TIP]
Use drag-and-drop to arrange the filters in a specific order by clicking on *Move* (material:drag_indicator[]). Click on material:delete[] to delete a filter.

[#apply-saved-filters]
=== Applying saved filters

Proceed as follows to apply an already saved filter for the search.

[.instruction]
Applying saved filters: 

. Click on *Saved filters* (material:bookmarks[]).
. Click on a filter that you have already created. +
→ The search is started and the filter settings are displayed up top as so-called “chips”.

[#default-filter]
=== Setting a default filter

To make sure that you don’t have to select a filter that you use quite often from the list of your <<#apply-saved-filters, saved filters>> every time when opening the *CRM » Quick search* menu, you can set a created filter as default filter. Every time when you open the quick search, this filter will be automatically applied.

You can set the filter as default filter directly when creating it as described in <<#save-current-filter, Saving the current filter>> or you can set the filter as default in the overview afterwards.

Click in the line of the saved filter on material:star_border[] *Set as default*. If you want to set another filter as default filter, deactivate the currently selected default filter by clicking on material:star[] *Do not use as default*.

[#edit-data-record]
== Editing a data record

When you found the desired <<#search-data-record, data record>>, you see further possible settings in the first line of the data record. These settings are explained in <<#table-settings-quick-search>>.

[TIP]
When you open a data record in the *CRM » Quick search* menu, you can click on *Start* (material:play_circle[]) to start the timer. Click on *Pause* (material:pause_circle[]) to stop the timer. Click on *Reset* (terra:reset[]) to set the time to 0.

[[table-settings-quick-search]]
.Settings in the quick search
[cols="2,6"]
|====
|Setting |Explanation

| *CONTACT ID*
|Opens the xref:crm:edit-contact.adoc#[contact data record] in the *CRM » Contacts* menu. +
*_Note:_* If the data record is a guest order, this field is not available.

| *ORDERS*
|Opens the *Orders » Edit orders* menu. The ID of the contact is automatically selected as filter. +
Click on material:add[] *New order* right next to *ORDERS* to create a new xref:orders:managing-orders.adoc#[order] in the *Orders » Edit orders* menu. +
*_Note:_* If the data record is a guest order, these fields are not available.

| *OFFERS*
|Opens the *Orders » Edit orders* menu. The ID of the contact is automatically selected as filter. +
Click on material:add[] *New offer* right next to *OFFERS* to create a new offer in the *Orders » Edit orders* menu. +
*_Note:_* If the data record is a guest order, these fields are not available.

| *MESSENGER*
|Opens the *Messenger*. +
Click on material:add[] *New message* right next to *MESSENGER* to open the messenger to create a new message. The contact ID is already prefilled in the recipient field. +
You can xref:crm:messenger-testphase.adoc#intable-whisper-mode[whisper] the message, xref:crm:messenger-testphase.adoc#create-message[send] the message or xref:crm:messenger-testphase.adoc#capture-minutes[capture minutes for the message] and define the minutes as free minutes or paid minutes. +
*_Note:_* If the data record is a guest order, the fields *MESSENGER* and *New message* are not available.

| *TICKETS*
|Opens the *CRM » Ticket system* menu. The ID of the contact is automatically selected as filter. +
Click on material:add[] *New ticket* right next to *TICKETS* to open the editing window for creating a new xref:crm:using-the-ticket-system.adoc#[ticket] in the *CRM » Ticket system* menu. +
*_Note:_* If the data record is a guest order, these fields are not available.

| *Download all data of the contact*
|Click on material:file_download[] to download all data that is saved for this data record. +
Further information can be found in the chapter <<#download-all-data, Downloading all data of a contact or a guest order>>.

| *Send newsletter opt-in email*
|Click on material:outgoing_mail[] to send an email for the newsletter opt-in respectively the confirmation for the newsletter opt-in. +
*_Note:_* If the customer is not registered for the newsletter yet, they will receive the automatic email for newsletter opt-in. If the customer is already registered for the newsletter, but has not confirmed yet, they will receive the confirmation for the newsletter opt-in. +
*_Note:_* If the data record is a guest order, this field is not available.

| *Anonymising a data record*
|Click on icon:user-secret[] to anonymise the data record. Anonymising data is only possible when the data record is a "real" contact and _not_ a guest order. +
For further information, refer to the <<#anonymise-data-record, Anonymising a data record>> chapter.

| *Convert guest into contact*
|Click on material:swap_horiz[] to convert the address data from a guest order into a regular contact data record. In the *History* area of the newly created contact data record, the entry *Converted by* as well as the name of the person who converted the data record are added. +
Further information can be found in the <<#convert-guest-account, Converting a plentyShop and marketplace guest order into a contact data record>> chapter. +
*_Note:_* If this is already a contact, this field is disabled.

| *Reload data*
|Click on material:refresh[] to update the data of this data record.

| *Pause* / *Start*
|Click on material:pause_circle[] to stop the timer. Click on material:play_circle[] to start the timer again.

| *Reset*
|Click on terra:reset[] to reset the timer to 0.

|====

[#convert-guest-account]
== Converting a plentyShop and marketplace guest order into a contact data record 

The *CRM » Quick search* menu allows you to convert with just one click the address data from a guest order that came into your system either via your plentyShop or via a marketplace into a regular contact data record.

* In case of a guest order via the plentyShop, the saved data record only consists of the address and the corresponding order; a contact ID is _not_ saved. However, the symbol material:done[] is shown in the overview’s *Guest* column.

* In case of a guest order via a marketplace, a contact ID is assigned and the symbol material:done[] is shown in the overview’s *Guest* column.

If a company name is additionally contained in the address, a company data record is also created when converting the data record.

[.instruction]
Converting a plentyShop and marketplace guest order into a contact data record:

. Go to *CRM » Quick search*.
* *_Alternative 1:_* Click on material:search[] (*Search*) to get a list of all data records.
* *_Alternative 2:_* Enter a value in the search field and select the appropriate filter from the suggestion list.
* *_Alternative 3:_* Click on material:tune[] to narrow down the search results with filters.
. Note the explanations about the filters in <<#table-filter-quick-search>>.  +
*_Tip:_* You can enter multiple search terms into the search fields at one time. This makes your search run quicker and be more accurate.
. Click on material:search[] *Search*. +
→ The data records that correspond to the search criteria entered are shown in the overview.
. Click in the line of the data record. +
→ The data record opens.
. Click on *Convert guest to contact* (material:swap_horiz[]) in the upper line. +
→ A window appears and you need to confirm your decision. +
. If you have worked in compliance with GDPR, click on *Convert*. +
→ The data record is converted into a contact data record and automatically obtains the next free contact ID. In the *History* area of the contact data record, the entry *Converted by* as well as the name of the person who converted the data record are added.

[TIP]
.plentyShop guest orders and marketplace guest orders 
====
plentyShop guest orders get the symbol material:done[] in the overview’s _Guest_ column, but *no* contact ID. Marketplace guest orders get the symbol material:done[] in the overview’s *Guest* column and in addition a contact ID.

*_Notes about converting a guest order into a contact data record_*

* Converting a plentyShop guest order is only possible in the *CRM » Quick search* menu.

* Converting a marketplace guest order is both possible in the *CRM » Quick search* menu and in the contact data record in the *CRM » Contacts* menu. How to proceed in this case is described in the xref:crm:edit-contact.adoc#convert-guest-to-regular-account[Converting a guest order into a regular contact data record] chapter on the xref:crm:edit-contact.adoc#[Editing a contact] page.
====

[#download-all-data]
== Downloading all data of a contact or guest order

In the *CRM » Quick search* menu, you can download with just one click all data that is saved for a contact or the address data belonging to a guest order as a ZIP file. The ZIP file contains an HTML file and a machine-parsable file in JSON format.

[.instruction]
Downloading all data of a contact or guest order:

. Go to *CRM » Quick search*.
* *_Alternative 1:_* Click on material:search[] (*Search*) to get a list of all data records.
* *_Alternative 2:_* Enter a value in the search field and select the appropriate filter from the suggestion list.
* *_Alternative 3:_* Click on material:tune[] to narrow down the search results with filters.
. Note the explanations about the filters in <<#table-filter-quick-search>>.  +
*_Tip:_* You can enter multiple search terms into the search fields at one time. This makes your search run quicker and be more accurate.
. Click on material:search[] *Search*. +
→ The data records that correspond to the search criteria entered are shown in the overview.
. Click in the line of the data record. +
→ The data record opens.
. Click on *Download all data of the contact* (material:file_download[]) in the upper line. +
→ A dialogue window appears. Determine a location on your computer where the ZIP file is saved.

Further information about the download file can be found in this link:https://forum.plentymarkets.com/t/dsgvo-button-fuer-den-datenexport-zu-einem-kunden-integriert/486915[changelog^] thread in the plentymarkets forum.

[#anonymise-data-record]
== Anonymising a data record

You can delete data of a contact respectively make this data illegible in such way that no reference to this person is given any longer.

[TIP]
Anonymising data is only possible when the data record is a "real" contact and not a guest order.

[IMPORTANT]
.Which data is anonymised and deleted?
====
By clicking on *Anonymise* (icon:user-secret[]), the following data in the data record of the contact is anonymised and deleted:

* This data is anonymised: First name, last name
* This data is deleted: Contact options, address options, addresses, address relations, order relations, account relations, bank details
====

[.instruction]
Anonymising a data record:

. Go to *CRM » Quick search*.
* *_Alternative 1:_* Click on material:search[] (*Search*) to get a list of all data records.
* *_Alternative 2:_* Enter a value in the search field and select the appropriate filter from the suggestion list.
* *_Alternative 3:_* Click on material:tune[] to narrow down the search results with filters.
. Note the explanations about the filters in <<#table-filter-quick-search>>.  +
*_Tip:_* You can enter multiple search terms into the search fields at one time. This makes your search run quicker and be more accurate.
. Click on material:search[] *Search*. +
→ The data records that correspond to the search criteria entered are shown in the overview.
. Click in the line of the data record. +
→ The data record opens.
. Click on *Anonymise data record* (icon:user-secret[]) in the upper line. +
→ A window appears and you need to confirm your decision.
. Enter the ID of the contact that you would like to anonymise.
. Click on *Anonymise*. +
→ The data record is anonymised.
