= Quick search
:keywords: quick search, address search, search addresses, GDPR, guest access, guest order, order as a guest, search guest, anonymise customer, anonymise, delete customer data, delete data record, delete customer, delete contact, download all data of customer, download customer data, customer requests deletion of his data
:description: Learn how to use the quick search in plentymarkets.
:id: RZPMSR4
:author: team-crm

Use the quick search to get an overview of all information that is saved for a contact or an address data record of a guest order. Learn on this page of the manual how to <<#download-all-data, download all data of a contact or guest order>> and how to <<#anonymise-data-record, anonymise data records>> in compliance with GDPR.

[NOTE]
.Guest orders coming into your system via plentyShop can only be found in the quick search
====
In order to be able to work GDPR-compliant, _no_ contact data record is created for guest orders that are coming into your system via the plentyShop. Only the address data is saved. This data that is saved in your plentymarkets system can therefore _not_ be found in the *CRM » Contacts* menu. The address data of the person who ordered as a guest in your plentyShop can only be found via the quick search. This is why you can only use the quick search to convert the data from the plentyShop guest order into a regular contact data record.

Further information about converting plentyShop guest orders into regular contact data records can be found in the <<#convert-guest-account, Converting a plentyShop and marketplace guest order into a contact data record>> chapter.
====

[#user-rights]
== Assigning rights for back end users

:rights-purpose: work with the quick search
:right-one: pass:quotes[*CRM > Contact > Show*]

include::_includes:partial$rights.adoc[]

For further information about the rights for the *CRM » Contacts* menu for back end users, refer to the xref:crm:preparatory-settings.adoc#assign-rights[Carrying out the preparatory settings] page.

[#find-data-records]
== Finding data records via the quick search

Proceed as follows to find data records via the quick search.

[.instruction]
Finding data records via the quick search:

. Go to *CRM » Quick search*.
. Select at least one filter. Note <<#table-filter-quick-search>>.
. Click on *Search* (icon:search[role="blue"]). +
→ The data records that correspond to the search criteria entered are displayed.
. Click in the line of the data record. +
→ The overview with the areas *Invoice address*, *Master data* and *Info* appears.
. Click in the line *Orders* to display the orders. +
→ Click in the line of the order to directly access the order in the *Orders » Edit orders* menu.
. Click in the line *Addresses* to display further addresses. +
→ Click in the line of the address to directly access the address overview and make changes.
. Click in the line *Messenger* to display the messages. +
→ Click on *New message* (material:add[]). The stop watch in the top right corner starts automatically once you open the message. Click next to the *Minutes* field on *Billable* (material:toggle_off[] terra:pay_cash[]) to bill the time. +
*_Note:_* For further information, refer to the xref:crm:messenger.adoc#[Messenger] page.
. Click in the line *Events* to add new events or edit existing events. +
→ Click on *Add event* (material:add[]) to save this time. +
→ *_Note:_* Events are only available for contact data records, _not_ for guest orders.
. Click in the line *Tickets* to display the tickets. +
→ Click in the line of the ticket to directly access the ticket in the *CRM » Ticket system* menu.

[[table-filter-quick-search]]
.Quick search filters
[cols="1,3"]
|====
|Setting |Explanation

| *Search*
|Click on icon:search[role="blue"] to show the data records found that match with the search criteria. +
*_Note:_* At least one filter has to be selected.

| *Reset*
|Click on icon:undo[role="orange"] to reset the filter criteria set.

| *ID*
|Each contact automatically receives a consecutive and unique ID. It doesn’t matter if the data record was saved manually or automatically. 2 contacts never have the same ID. The ID is always a real number. For example, 00521 or ABC8354 are therefore invalid. +
*_Note:_* Click on the arrows (icon:sort[]) next to the ID in the overview to sort the contact data records found in ascending or descending order according to their ID.

| *Name*
|Enter the first name and/or last name or the name of the company to search for the contact(s) with this name or company name. +
*_Note:_* Click on the arrows (icon:sort[]) in the columns *First name* and *Last name* in the overview to show the contact data records found in alphabetical order.

| *Contact data*
|In this field, you can search for the name, address, company, customer number and eBay name. +
*_Note:_* In order to search for the eBay name, first enter the parameter `ebay:` followed by the eBay name that you search for.

| *Address*
|Enter the street name and/or house number. It is also possible to search only for parts of the street and parts of the house number.

| *Postcode*
|Enter the postcode. +
*_Note:_* The search is also carried out for postcodes that are saved in the address data records of the contact. It is also possible to search only for parts of the postcode. Enter at least 3 numbers.

| *Town*
|Enter the town that is saved for the contact. The search is also carried out for towns that are saved in the address data records of the contact. It is also possible to search only for parts of the town.

| *Email*
|Enter the complete email address to search for the contact with this email address.

| *Telephone*
|Enter the telephone number to search for the contact with this number. You can also search for parts of the telephone number. Enter at least 3 numbers.

| *Tags*
|Select a tag to only search for contacts with this tag.

| *Country*
|Select a country to only display contacts from this country. The country is saved within the contact data. +
Select the setting *All except Germany* to only display contacts from all countries except Germany.

| *Owner*
|Select the owner to only search for contacts that are linked to this owner. The owner has to be saved in the contact data record. +
*_Important:_* Only owners for whom the *Customer* option has been activated in the *Owner* tab can be selected from the drop-down list.

| *Type*
|Select the type to only search for contacts with this type.

| *Customer class*
|Select the customer class to only search for contacts with this class.

| *Rating*
|Select the rating to only search for contacts with this rating. 5 yellow stars are the best rating, 5 red stars are the worst rating.

| *Client*
|Select a client to only display contacts that correspond to this client. The client is saved within the contact data record. +
*_Important:_* Back end users can only select those clients that they have a right to access. Go to *Setup » Settings » User » Accounts* and set the rights in the user account in the xref:business-decisions:user-accounts-access.adoc#90[Rights] tab.

|====

[TIP]
When you open a data record in the *CRM » Quick search* menu, you can click on *Start* (material:play_circle[]) to start the timer. Click on *Pause* (material:pause_circle[]) to stop the timer. Click on *Reset* (terra:reset[]) to set the time to 0.

[#further-settings]
== Further settings

When you open a data record in the quick search, you see further possible settings in the first line of the data record. These settings are explained in <<#table-settings-quick-search>>.

[[table-settings-quick-search]]
.Settings in the quick search
[cols="2,6"]
|====
|Setting |Explanation

| *CONTACT ID*
|Opens the contact data record in the *CRM » Contacts* menu. +
*_Note:_* If the data record is a guest order, this field is not available.

| *ORDERS*
|Opens the *Orders » Edit orders* menu. The ID of the contact is automatically selected as filter. +
Click on material:add[] *New order* right next to *ORDERS* to create a new order in the *Orders » Edit orders* menu. +
*_Note:_* If the data record is a guest order, these fields are not available.

| *OFFERS*
|Opens the menu *Orders » Edit orders*. The ID of the contact is automatically selected as filter. +
Click on material:add[] *New offer* right next to *OFFERS* to create a new offer in the *Orders » Edit orders* menu. +
*_Note:_* If the data record is a guest order, these fields are not available.

| *MESSENGER*
|Opens the *Messenger* area further down in this view. +
Click on material:add[] *New message* right next to *MESSENGER* to open the editing window for creating a new message further down in this view. +
*_Note:_* If the data record is a guest order, these fields are not available.

| *TICKETS*
|Opens the *CRM » Ticket system* menu. The ID of the contact is automatically selected as filter. +
Click on material:add[] *New ticket* right next to *TICKETS* to open the editing window for creating a new ticket in the *CRM » Ticket system* menu. +
*_Note:_* If the data record is a guest order, these fields are not available.

| *Download all data of the contact*
|Click on material:file_download[] to download all data that is saved for this data record. +
Further information can be found in the chapter <<#download-all-data, Downloading all data of a contact or a guest order>>.

| *Send newsletter opt-in email*
|Click on material:outgoing_mail[] to send an email for the newsletter opt-in respectively the confirmation for the newsletter opt-in. +
*_Note:_* If the customer is not registered for the newsletter yet, they will receive the automatic email for newsletter opt-in. If the customer is already registered for the newsletter, but has not confirmed yet, they will receive the confirmation for the newsletter opt-in. +
*_Note:_* If the data record is a guest order, this field is not available.

| *Anonymising a data record*
|Click on icon:user-secret[] to anonymise the data record. Anonymising data is only possible when the data record is a "real" contact and _not_ a guest order. +
For further information, refer to the <<#anonymise-data-record, Anonymising a data record>> chapter.

| *Convert guest into contact*
|Click on material:swap_horiz[] to convert the address data from a guest order into a regular contact data record. In the *History* area of the newly created contact data record, the entry *Converted by* as well as the name of the person who converted the data record are added. +
Further information can be found in the <<#convert-guest-account, Converting a plentyShop and marketplace guest order into a contact data record>> chapter. +
*_Note:_* If this is already a contact, this field is disabled.

| *Reload data*
|Click on icon:undo[] to update the data from this data record.

| *Pause* / *Start*
|Click on material:pause_circle[] to stop the timer. Click on material:play_circle[] to start the timer again.

| *Reset*
|Click on terra:reset[] to reset the timer to 0.

|====

[#convert-guest-account]
== Converting a plentyShop and marketplace guest order into a contact data record 

The *CRM » Quick search* menu allows you to convert with just one click the address data from a guest order that came into your system either via your plentyShop or via a marketplace into a regular contact data record.

* In case of a guest order via the plentyShop, the saved data record only consists of the address and the corresponding order; a contact ID is _not_ saved. However, the symbol material:done[] is shown in the overview’s *Guest* column.

* In case of a guest order via a marketplace, a contact ID is assigned and the symbol material:done[] is shown in the overview’s *Guest* column.

If a company name is additionally contained in the address, a company data record is also created when converting the data record.

[.instruction]
Converting a plentyShop and marketplace guest order into a contact data record:

. Go to *CRM » Quick search*.
. Select at least one filter. Note <<#table-filter-quick-search>>.
. Click on *Search* (icon:search[role="blue"]). +
→ The data records that correspond to the search criteria entered are displayed.
. Click in the line of the data record. +
→ The data record opens.
. In the header, click on *Convert guest to contact* (material:swap_horiz[]]). +
→ A window appears and you need to confirm your decision. +
. If you have worked in compliance with GDPR, click on *Convert*. +
→ The data record is converted into a contact data record and automatically obtains the next free contact ID. In the *History* area of the contact data record, the entry *Converted by* as well as the name of the person who converted the data record are added.

[TIP]
.plentyShop guest orders and marketplace guest orders 
====
plentyShop guest orders get the symbol material:done[] in the overview’s *Guest* column, but _no_ contact ID. Marketplace guest orders get the symbol material:done[] in the overview’s *Guest* column and in addition a contact ID.

*_Notes about converting a guest order into a contact data record_*

* Converting a plentyShop guest order is only possible in the *CRM » Quick search* menu.

* Converting a marketplace guest order is both possible in the *CRM » Quick search* menu and in the contact data record in the *CRM » Contacts* menu. How to proceed in this case is described in the xref:crm:edit-contact.adoc#convert-guest-to-regular-account[Converting a guest order into a regular contact data record] chapter on the xref:crm:edit-contact.adoc#[Editing a contact] page.
====

[#download-all-data]
== Downloading all data of a contact or guest order

In the *CRM » Quick search* menu, you can download with just one click all data that is saved for a contact or the address data belonging to a guest order as a ZIP file. The ZIP file contains an HTML file and a machine-parsable file in JSON format.

[.instruction]
Downloading all data of a contact or guest order:

. Go to *CRM » Quick search*.
. Select at least one filter.
. Click on *Search* (icon:search[role="blue"]). +
→ The data records that correspond to the search criteria entered are displayed.
. Click in the line of the data record. +
→ The overview with the areas *Invoice address*, *Master data* and *Info* appears.
. Click on *Download all data of the contact* (material:file_download[]) in the upper line. +
→ A dialogue window appears. Determine a location on your computer where the ZIP file is saved.

Further information about the download file can be found in this link:https://forum.plentymarkets.com/t/dsgvo-button-fuer-den-datenexport-zu-einem-kunden-integriert/486915[changelog^] thread in the plentymarkets forum.

[#anonymise-data-record]
== Anonymising a data record

You can delete data of a contact respectively make this data illegible in such way that no reference to this person is given any longer.

[TIP]
Anonymising data is only possible when the data record is a "real" contact and not a guest order.

[.instruction]
Anonymising a data record:

. Go to *CRM » Quick search*.
. Select at least one filter.
. Click on *Search* (icon:search[role="blue"]). +
→ The contacts that correspond to the search criteria entered are displayed.
. Click in the line of the contact. +
→ The overview of the contact opens.
. Click on *Anonymise data record* (icon:user-secret[]) in the upper line. +
→ A window appears and you need to confirm your decision.
. Enter the ID of the contact that you would like to anonymise.
. Click on *Anonymise*. +
→ The data record is anonymised.

[TIP]
.Which data is anonymised and deleted?
====
By clicking on *Anonymise data record* (icon:user-secret[]), the following data in the data record of the contact is anonymised and deleted:

* This data is anonymised: First name, last name
* This data is deleted: Contact options, address options, addresses, address relations, order relations, account relations, bank details
====
