= Newsletters
:lang: en
include::{includedir}/_header.adoc[]
:keywords: newsletter, double opt-in, newsletter, newsletter template, visibility newsletter, email folder, newsletter login details, CleverReach
:description: Learn how to use plentymarkets to send newsletters to your customers.
:position: 1000
:url: crm/sending-newsletters
:id: JIHLVCR
:author: team-crm

This page of the manual describes which settings you need to carry out to send newsletters with plentymarkets. Send your newsletters e.g. with the <<crm/sending-newsletters#100, newsletter service integrated in plentymarkets>>, via the integrated interface to <<crm/sending-newsletters#1700, CleverReach>> or via other email marketing and newsletter plugins available in the link:https://marketplace.plentymarkets.com/en/plugins/integration[plentyMarketplace^]{nbsp}icon:external-link[].

[#100]
== Setting up the newsletter service integrated in plentymarkets

In the following sub-chapters, you will learn how to set up the newsletter service that is integrated in plentymarkets.

[TIP]
.Double opt-in method
====
The double opt-in method is used in plentymarkets. This means that the recipient is sent an email after having asked to receive the newsletter. This email contains a link that is used to confirm the newsletter subscription. Only after the customer has clicked on the link is the customer registered for the newsletter. This method is integrated in plentymarkets and cannot be changed.
====

[#200]
=== Entering newsletter login details

Go to *Setup » Client » [Select client] » Email » Newsletter*. Enter the login details to use the newsletter service that is integrated in plentymarkets.

[.instruction]
Entering newsletter login details:

. Go to *Setup » Client » [Select client] » Email » Newsletter*.
. Carry out the desired settings. Note <<#table-newsletter-login-details>>.
. *Save* (icon:save[role="green"]) the settings.

[[table-newsletter-login-details]]
.Entering newsletter login details
[cols="1,3"]
|====
|Setting |Explanation

| *Name of sender*
|Enter your name or the name of the online shop. The name is displayed to the recipient.

| *Email address*
|Enter the email address as it is listed in the email program. The newsletter is sent via this email address.

| *Outgoing mail server/SMTP server*
|Enter the outgoing mail server as specified by the provider (usually smtp.domain.co.uk or mail.domain.co.uk). +
*_mailbox.org:_* For mailbox.org mailboxes, enter the outgoing mail server *smtp.mailbox.org* and select the setting *SSL* as the *encryption method*.

| *User name*
|Enter the user name that matches the email address. +
*_mailbox.org:_* The mailbox.org user name is the complete email address of the mailbox.org mailbox.

| *Password*
|Enter the password that matches the user name and email address.

| *Port (standard port: 25)*
|Enter the value *25*. This value is correct for nearly all providers. Otherwise, ask your provider about the correct port. +
*_mailbox.org:_* For mailbox.org mailboxes, enter the port *465* and select the setting *SSL* as *encryption method*.

| *Encryption*
| Select *SSL*, *TLS* or *No encryption*. +
*_mailbox.org:_* For mailbox.org mailboxes, select the setting *SSL*. +
Further information can be found in the <<crm/sending-emails#200, Selecting the encryption for email communication>> chapter on the <<crm/sending-emails#, Emails>> page of the manual.
|====

[#300]
=== Creating an email folder

Go to *Setup » CRM » Newsletter » plentymarkets » Email folder* to create folders for sending newsletters. Afterwards, you save the email addresses of your customers in these folders. This allows you to send different newsletters to different target groups. Proceed as described below to create a new email folder.

[.instruction]
Creating an email folder:

. Go to *Setup » CRM » Newsletter » plentymarkets » Email folder*.
. Enter a name for the folder under *Create new email folder*.
. Change the folder ID if needed.
. Carry out the desired settings. Note <<#table-create-email-folder>>.
. *Save* (icon:save[role="green"]) the settings. +
→ The email folder is created and displayed in the overview.

[[table-create-email-folder]]
.Creating email folders for sending newsletters
[cols="1,3"]
|====
|Setting |Explanation

| *ID*
|The folder ID that was assigned when the folder was created. Consecutive IDs are automatically assigned by default. However, a different ID can be assigned as needed while creating the folder. The ID `0` cannot be used. +
*_Note:_* Do not use the same ID for multiple folders. If you enter an already existing ID, the original folder is overwritten.

| *Name*
|The name of the email folder. If you activate the option *Can be selected by customers*, this name is also visible for customers in the online shop.

| *Can be selected by customers*
|Activate if you want the folder to be selected by customers in your online shop. If this option is activated, the folder is displayed in the *My account* area of the online shop. Customers are then able to subscribe to the newsletters that are included in this folder.

| *Position*
|Enter a position number to specify which order the folders should be displayed in.

| *Visibility*
|Decide whether the newsletter folder should be visible for the default online shop only or whether it should be visible for all online shop. The folder is completely invisible if you select *None*.

| *Delete*
|Activate and click on *Save* to delete the folder.
|====

[#400]
=== Editing an email folder

Existing email folders can also be edited in the menu *Setup » CRM » Newsletter » plentymarkets » Email folder*. Proceed as follows to edit the settings of an email folder.

[.instruction]
Editing an email folder:

. Go to *Setup » CRM » Newsletter » plentymarkets » Email folder*.
. Carry out the desired changes. Note <<#table-create-email-folder>>.
. *Save* (icon:save[role="green"]) the settings.

[#500]
=== Assigning email addresses to the newsletter main folder

Add the ShopBuilder widget *Newsletter* to your plentyShop to provide the newsletter registration for your customers. With this widget, select the email folder that is automatically linked with the email address of a person once this person subscribed to your newsletter in your online shop.

How to proceed is described on the <<online-store/shop-builder#_newsletter, Setting up the ShopBuilder>> page of the manual.

[#600]
=== Allowing customers to select newsletters

Let your customers choose which newsletters they want to receive. This is advantageous, for example, if you regularly send newsletters about different topics. Your customers can select any of the email folders that you have activated for the option *Can be selected by customers* in <<#table-create-email-folder>>. Your customers can select these folders in the *My account* area of the online shop. The customer's email address is saved in this email folder in your plentymarkets system.

[#700]
=== Creating an email template

Use an email template to send your confirmation email. Use template variables in your template to make sure that the correct name of the customer as well as the confirmation link is automatically included in the template. Proceed as follows to create the email template that contains the confirmation link.

[IMPORTANT]
.Using template variables and template functions
====
There is a wide range of template variables and template functions for your email templates available in plentymarkets. Open the email template and click on *Template variables and template functions* (icon:code[role="blue"]). Copy the template variable or template function from this area and insert it to the desired position in the email template in the *Email message* tab. You can copy them to plain text or to text in HTML format.

For further information, refer to the <<crm/sending-emails#, Emails>> page of the manual.
====

[.instruction]
Creating an email template:

. Go to *Setup » Client » [Select client] » Email » Templates*.
. Click on *New email template* (icon:plus-square[role="green"]). +
→ The *New email template* window opens.
. Enter the name for the email template.
. Select the owner from the drop-down list.
. Click on *Save* (icon:save[role="green"]). +
→ The email template is created and saved in one of the 3 folders, depending on the selected setting in the *Owner* drop-down list. Note the information about *Owner* in <<#table-create-email-template>>.
. Carry out the desired settings. Note <<#table-create-email-template>>.
. Insert the template variable `$CustomerFullName` into the text of the email. +
→ This template variable makes the first name and last name available.
. Insert the template variable `$NewsletterConfirmURL` into the text of the email. +
→ This template variable makes the confirmation link available.
. *Save* (icon:save[role="green"]) the settings.

If the recipient of the email clicks on the link that was inserted with the template variable `$NewsletterConfirmURL`, the recipient confirms the newsletter registration and will receive from now on the newsletter to the saved email address.

If you would like to use the <<crm/sending-newsletters#800, double opt-in method>>, a further step is required. You have to create two templates and select them for the events *Newsletter opt-in* and *Newsletter opt-in confirmation* in the *Setup » Client » [Select client] » Email » Automatic* menu.


[[table-create-email-template]]
.Creating a new email template for sending newsletters
[cols="1,3"]
|====
|Setting |Explanation

| *Save*
|Saves (icon:save[role="green"]) the settings in the email template.

| *Template variables and template functions*
|Click on icon:code[role="blue"] to open the *Template variables and functions* area from which the template variables and template functions are copied for the email template.

2+| *Tab: Settings*

| *Owner*
|If the name of the owner has already been selected from the drop-down list upon creation of the email template, the name of the owner is displayed here. Otherwise, select the owner from the drop-down list. This setting can be changed at any time. +
*All* = The template is saved under *General email templates*. +
Own user name = The template is saved under *General email templates*. +
Other user name = The template is saved under *Email templates from other users*. +
*_Note:_* You have to be logged into the system as a user in order to create your own email templates under *My email templates*.

| *Name*
|If the name has already been entered upon creation of the email template, the name of the email template is displayed here. Otherwise, enter the name for the template. +
The name can be changed at any time. The name is not displayed to the recipient.

| *Content*
|Select whether the message should be saved as *plain text* or in *HTML format*.

| *Template type*
|Select for which area the email template should be available. Possible options: *All* (default setting), *Order*, *Customers*, *Online store*, *Ticket* or *Scheduler*. +
*All* / *Online store* = The email template is available for all areas. +
*Order* = The email template is only available for the selected area. The template is not visible in the other areas. If the ticket is linked with an order, email templates with the template type *Order* can also be selected in the ticket. +
*Customers* = The email template is only available for the selected area. The template is not visible in the other areas. +
*Ticket* = The email template is only available for the selected area. The template is not visible in the other areas. +
*Scheduler* = The email template is available for all areas where the template type *Order* is visible.

| *PDF attachment*
|Select the attachment from the drop-down list. The documents that can be selected from this drop-down list are for example generated in the *Orders » Fulfilment* menu or through shipment-related processes.

| *Document attachment*
|Documents that were uploaded under *CMS » Documents* are displayed here. You can attach one of these documents to an email template. +
 All email templates can be sent with up to 2 attachments in a standardised way: Use email templates to send PDF documents relating to fulfilment (e.g. invoices) or other files (e.g. brochures or instructions). For example, it would be useful to attach PDF documents of your cancellation rights and terms and conditions to the email template *Confirmation of online store order*.

| *Reply to*
|Enter an email address. If someone replies to the email template, their message is sent to this address. If no email address was entered, replies to the template are sent to the <<crm/sending-emails#100, email address that is saved>> under *Setup » Client » [Select client] » Email » Login details*. For example, it is useful to enter the accounting department's email address for the *PDF invoice* email template. Questions about the invoice would directly be sent to your accounting department and wouldn't have to be forwarded to them in an extra step.

| *Use design*
|Activate if the content of the email should be sent with the <<crm/sending-emails#800, design that was saved>> under *Setup » Client » [Select client] » Email » HTML design*. If the option is not activated, only the content of the email template is used.

| *Client (store)*
|Activate one, multiple or *ALL* clients (shops). The email template is only valid for the selected clients (shops).

2+| *Tab: Email message*

| *Select language*
|The selected language is displayed here and can be changed.

| *Subject*
|Enter the subject text. Select the subject name very carefully so that your customers can easily recognise the emails in their inbox and so that the emails are not filtered out as spam.

| *Content / Item list*
|Insert the text or list of items in these tabs. Use *plain text* or text in *HTML format*. Template variables and template functions can be used to display the content. +
*_Note:_* Check which type of content was selected in the *Settings* tab under *Content*. Enter the text of the email into this corresponding tab. For example, if *Plain text only* is selected but you entered content into the *Text in HTML format* tab, this content is not sent in the email.
|====

[#800]
=== Linking email templates with the double opt-in function

In the next step, link the email template that you have just created with the double opt-in function and select another template for the option *Newsletter opt-in confirmation*. If you use the double opt-in method, the customer has to confirm the newsletter registration in a second step after they have registered for the newsletter.

[TIP]
.Notes about the double opt-in method
====
You have to <<crm/sending-newsletters#700, create>> 2 templates and select these for the events *Newsletter opt-in* and *Newsletter opt-in confirmation* in the *Setup » Client » [Select client] » Email » Automatic* menu. The selected template under *Newsletter opt-in* is sent when the customer has registered for the newsletter. This template should contain the confirmation link that the customer has to click in order to complete the newsletter registration. Use the template variable `$NewsletterConfirmURL` to display the confirmation link. This template variable contains the URL to confirm the newsletter registration. The selected template under *Newsletter opt-in confirmation* is sent when the customer has activated the confirmation link.

In the contact data record in the *CRM » Contacts » [Open contact] » Area: Details* menu, the *Newsletter* option is activated automatically when the customer has registered for the newsletter during the order process and has confirmed the newsletter registration via the confirmation link.
====

[.instruction]
Linking the email template with the double opt-in function:

. Go to *Setup » Client » [Select client] » Email » Automatic*.
. Select the email template that was previously created from the *Newsletter opt-in* drop-down list.
. Select the email template that was previously created from the *Newsletter opt-in confirmation* drop-down list.
. *Save* (icon:save[role="green"]) the settings.

You can see the confirmation status by going to *Setup » CRM » Newsletter » plentymarkets » Emails*. Customers who confirmed that they want to receive the newsletter are designated with the status *[green]#confirmed#*. Customers who did not go through the double opt-in process are designated with the status *[red]#not confirmed#*.

The *IP address* and the *confirmation URL* used for a confirmation are saved in the database. This data can be retrieved afterwards via a link:https://developers.plentymarkets.com/rest-doc/newsletter/details#list-a-recipient[REST-Call^]{nbsp}icon:external-link[]. This is not displayed in the back end.

[#900]
=== Saving an email address

The email addresses that newsletters should be sent to are saved in various folders. Go to *Setup » CRM » Newsletter » plentymarkets » Emails* to manage the email addresses that are saved in these folders. If you have not yet created a <<crm/sending-newsletters#300, folder structure>> for your newsletters, we recommend doing so before you continue.

Proceed as described below to save an email address in an email folder.

[.instruction]
Saving an email address:

. Go to *Setup » CRM » Newsletter » plentymarkets » Emails*.
. Expand the folder (icon:plus-square-o[]).
. Expand the area *New email address* (icon:plus-square-o[]).
. Carry out the desired settings. Note <<#table-save-email-address>>.
. *Save* (icon:save[role="green"]) the settings.

[[table-save-email-address]]
.Settings for saving a new email address
[cols="1,3"]
|====
|Setting |Explanation

| *First name*
|Enter the contact’s first name.

| *Last name*
|Enter the contact’s last name.

| *Email*
|Enter the contact’s email address.

| *Folder*
| Select the <<crm/sending-newsletters#300, email folder>> where the data should be saved.
|====

[#1000]
=== Creating a newsletter

Proceed as described below to create new newsletters. You can also edit existing newsletter.

[.instruction]
Creating a newsletter:

. Go to *CRM » Newsletter*.
. Expand the area *New newsletter* (icon:plus-square-o[]). +
→ The editing window for the new newsletter opens.
. Carry out the desired settings. Note <<#table-create-newsletter>>.
. *Save* (icon:save[role="green"]) the settings.

[[table-create-newsletter]]
.Settings for creating a newsletter
[cols="1,3"]
|====
|Setting |Explanation

| *Placeholders*
|Lists the placeholders that are recognised by the system and replaced in the message. +
Currently available placeholders: +
*+[NAME]+* = First name and last name of the recipient +
*+[EMAIL]+* = Email address of the recipient +
*+[RECIPIENTID]+* = ID of the recipient +
//*+[FOLDERID]+* = ID of the newsletter folder


| *Image gallery*
|Opens the <<online-store/online-store/cms#webspace, CMS » Webspace>> menu. +
Upload an image there, copy the link to the clipboard by clicking on icon:clipboard[role="yellow"], go back to the newsletter menu and click on *Image* in the editor of the *HTML Newsletter* area. The *Image properties* window opens. In the *Image info* tab, insert the copied link of the image in the field *URL*, enter an alternative text and in the *Link* tab, insert the copied link of the image once more in the *URL* field to link the image with the newsletter.

| *Input layout template*
|Clicking on *Input layout template* inserts the form of address *[Guten Tag]* along with the placeholder *[NAME]* in the *HTML newsletter* area. The newsletter recipient’s name is automatically replaced in the template variable.

| *Subject*
|Enter a subject for the newsletter.

| *Editor*
|The *CKEditor* is preselected. If required, select another editor from the drop-down list.

| *HTML newsletter*
|Enter the content of the newsletter as HTML code. +
*_Note:_* Texts can only be saved in one field. Therefore, you can either enter text into the *HTML newsletter* or the *Text newsletter* area.

| *Text newsletter*
|Enter the newsletter's content as plain text only. +
*_Note:_* Texts can only be saved in one field. Therefore, you can either enter text into the *HTML newsletter* or the *Text newsletter* area.

|====

[#1100]
=== Searching for persons by their email address or last name

Proceed as described below to search for an email address in an email folder. You can either search for persons by their email address or by their last name.

[.instruction]
Searching for persons by their email address or last name:

. Go to *Setup » CRM » Newsletter » plentymarkets » Emails*.
. Expand the email folder (icon:plus-square-o[]).
. Select the option *Email address* or *Last name* from the drop-down list. Customers are searched for by this criterion.
. Enter the email address or last name in the search field.  +
→ It is sufficient to only enter part of the name or email address. Leave the field blank if you want to display all email addresses or last names.
. Click on *Search* (icon:search[role="blue"]). +
→ The search result(s) are displayed.

The confirmation status is also displayed in the search results. The <<crm/sending-newsletters#800, double opt-in method>> is used in plentymarkets. This means that an email is sent to the recipient after having asked to receive the newsletter. This email contains a link that is used to confirm the newsletter subscription. Customers who confirmed that they want to receive the newsletter are designated with the status *[green]#confirmed#*. Otherwise, you see the words *[red]#not confirmed#*.

[#1200]
=== Editing an email address

Once you have found an email address with the search function, you can edit the data that is saved for this person. For example, this is useful if you need to update a person’s email address or if you want to move the contact data record into a different email folder. To do so, proceed as described below.

[.instruction]
Editing an email address:

. Go to *Setup » CRM » Newsletter » plentymarkets » Emails*.
. Search for the person as described in the chapter <<crm/sending-newsletters#1100, Searching for persons by their email address or last name>>.
. Expand the person’s data (icon:plus-square-o[]).
. Carry out the desired changes. Note <<#table-save-email-address>> in the <<crm/sending-newsletters#900, Saving an email address>> chapter.
. *Save* (icon:save[role="green"]) the settings.

[#1300]
=== Exporting and importing email addresses

The previous chapters describe how to manage individual email addresses. If you want to edit several email addresses at once, it is recommended that you work with the <<data/importing-data/ElasticSync#, import tool>>. Import new and edit existing email addresses with the import type <<data/importing-data/sync-types/elasticSync-newsletter-recipient#, Newsletter recipient>>.

You can also export email addresses. To do so, create an <<data/exporting-data/FormatDesigner#, export format>> in the *Data » FormatDesigner* menu and export the data afterwards via the <<data/exporting-data/elastic-export#, Elastic export>>.

[#1400]
=== Copying customer data into an email folder

Go to *Setup » CRM » Newsletter » plentymarkets » Email filter* to filter customer data and copy this data into specific email folders. For example, you can search for all customers who purchased a certain item during a specific time period. You can use the folders when <<crm/sending-newsletters#1000, sending newsletters>> to these customer groups in the *CRM » Newsletter* menu.

Proceed as described below in order to copy customer data into an email folder.

[.instruction]
Copying customer data into an email folder:

. Go to *Setup » CRM » Newsletter » plentymarkets » Email filter*.
. Carry out the settings in the *Copy all customer data into email folder(s)* area. Note <<#table-copy-customer-data>>.
. Click on *Transfer emails into folder* (icon:cog[]).

[[table-copy-customer-data]]
.Copying customer data into an email folder
[cols="1,3"]
|====
|Setting |Explanation

| *Newsletter registration*
|Select one of the following options: +
*ALL* = The data of all customers who have subscribed to the newsletter are copied into the email folder. This includes customers who confirmed their newsletter subscription with the <<crm/sending-newsletters#800, double opt-in method>> and customers who have not yet confirmed. +
*Only customers who have consented to the receipt of newsletters* = Only the data of customers who have subscribed to the newsletter are copied into the email folder.

| *Country*
|Select the country to only filter customers from this country. For example, this makes it possible to send one version of a newsletter to customers who live in the United Kingdom and another version to customers who live in Ireland.

| *Email folder*
|Select the email folder. The customer data is saved in this email folder.
|====

[#1500]
=== Filtering customer data

The customer filter helps you find more specific customer data. Proceed as described below in order to filter customer data and to copy this data into an email folder.

[.instruction]
Filtering customer data:

. Go to *Setup » CRM » Newsletter » plentymarkets » Email filter*.
. Carry out the settings in the *Filter* area. Note <<#table-filter-customer-data>>.
. Click on *Preview* (icon:eye[role="blue"]) to show the data. +
→ The *Preview* area that contains the customer data opens. Check the result.
. Click on *Transfer emails into folder* (icon:cog[]).

[[table-filter-customer-data]]
.Settings for the customer filter
[cols="1,3"]
|====
|Setting |Explanation

| *Minimum order value*
|Enter a minimum order value to filter customers whose orders reached or exceeded this value.

| *Category 1-3*
|Select up to 3 category levels to filter customers who bought an item in this category or sub-category.

| *Item ID*
|Enter one or more item IDs to filter customers who bought these items.

| *Exact order time*
|Enter a time period or select the dates from the calendar to filter customers who placed an order during this time period. If you do not want to filter by the date, activate the option *No exact order time*.

| *Country*
|Select the country to only filter customers from this country. For example, this makes it possible to send one version of a newsletter to customers who live in the United Kingdom and another version to customers who live in Ireland.

| *Client (store)*
|Select a client (store) to filter customers who bought an item from this client (store).

| *Customer class*
| Select a <<crm/managing-contacts#15, customer class>> to filter customers who belong to this class.

| *Order referrer*
|Select an order referrer to filter customers who placed orders with this order referrer.

| *Newsletter registration*
|Choose between the options *ALL* and *Only customers who have consented to the receipt of newsletters*. +
*ALL* = The data of all customers who have subscribed to the newsletter are copied into the email folder. This includes customers who confirmed their newsletter subscription with the <<crm/sending-newsletters#800, double opt-in method>> and customers who have not yet confirmed. +
*Only customers who have consented to the receipt of newsletters* = Only the data of customers who have subscribed to the newsletter are copied into the email folder.

| *Email folder*
|Select the email folder. The data is saved in this email folder.
|====

[#1600]
=== Sending newsletters

After you <<crm/sending-newsletters#700, created>> and <<crm/sending-newsletters#800, linked>> the email template and have <<crm/sending-newsletters#1000, created the newsletter>>, you set which email addresses that are saved in the email folders the newsletter should be sent to. To do so, go to *CRM » Newsletter*. Using the *Filter* option, you can decide whether to send a newsletter to all email addresses or only to confirmed email addresses. Carry out this setting in the *Send newsletter* tab of the newsletter.

[TIP]
.Only a limited number of newsletters is sent during the day
====
Note that only a limited number of newsletters is sent to your customers during the day. At night, a larger number of emails is allowed to be sent to your customers.

* During the day between 8:00am and 12:00 midnight: 60 emails every 15 minutes
* At night between 12:00 midnight and 8:00am: 500 emails every 15 minutes
====

[.instruction]
Sending newsletters:

. Go to *CRM » Newsletter*.
. Expand the newsletter that you want to send (icon:plus-square-o[]).
. Click on the *Send newsletter* tab.
. Select a group under *Send newsletter* to group from the drop-down list.
. Select the option *ALL* or *To confirmed email addresses only* from the *Filter* drop-down list.
. Click on *Send* (icon:envelope-o[role="purple"]). +
→ The newsletter are sent according to the settings that you selected above.

[#1650]
=== Inserting an unsubscribe link for the newsletter

You should make it possible for your newsletter recipients to unsubscribe from your newsletter(s) at any time. In order that the recipient can unsubscribe from the newsletter, you have to insert the unsubscribe link in the newsletter template in the *CRM » Newsletter* menu or as you choose in any other email template in the *Setup » Client » [Select client] » Email » Templates* menu.

It is possible to add a link that unsubscribes the recipients from all newsletter folders (see point 1) or a link that unsubscribes the recipients from a certain newsletter folder (see point 2):

. *+http://[domain name]/?OrderShow=CancelNewsletter+* +
When recipients click on this link, they unsubscribe from all newsletter folders.

. *+http://[domain name]/?OrderShow=CancelNewsletter&folderId=1+* +
When recipients click on this link, they unsubscribe from a certain newsletter folder. In this example, the recipients would unsubscribe from the folder with ID `1`.

The domain is saved in the *Setup » Client » [Select client] » Settings* menu.

[#1700]
== Sending newsletters with CleverReach

Proceed as described below to send newsletters to your customers with link:https://www.cleverreach.com/en/[CleverReach^]{nbsp}icon:external-link[].

[#1800]
=== Registering with CleverReach

Register for free in order to use CleverReach in plentymarkets. To do so, go to the link:https://www.cleverreach.com/en/login/[CleverReach website^]{nbsp}icon:external-link[]. For further information about the settings in CleverReach, refer to the link:http://support.cleverreach.de/hc/de[CleverReach help center^]{nbsp}icon:external-link[].

[#1900]
=== Setting up CleverReach in plentymarkets

Proceed as described below to set up the CleverReach interface in plentymarkets.

[.instruction]
Setting up CleverReach in plentymarkets:

. Go to *Setup » CRM » Newsletter » CleverReach*.
. Carry out the desired settings. Note <<#table-set-up-cleverreach>>.
. Enter your *API key*.
. Enter the *List ID* of the group that you created in CleverReach.
. *Save* (icon:save[role="green"]) the settings.
. Click on *Generate group attributes* (icon:cog[]). +
→ Data fields are set up in CleverReach. This way the customer data that you transfer can be saved and processed.
. Open the CleverReach back end and open the group whose list ID you entered into plentymarkets.
. Delete the data fields that you do not want to use in CleverReach. +
→ The following data fields are currently transferred from plentymarkets to CleverReach: *Birthday*, *First name*, *Gender (form of address)*, *Lang (language)* and *Last name*.
. Go back to *Setup » CRM » Newsletter » CleverReach* in your plentymarkets back end.
. Select the option *Automatic transfer (daily)* so that the data is transmitted.
. *Save* (icon:save[role="green"]) the settings.

[[table-set-up-cleverreach]]
.Carrying out settings for CleverReach
[cols="1,3"]
|====
|Setting |Explanation

| *Generate group attributes*
|Generates the data fields (group attributes) for CleverReach.

| *Carry out data transfer*
|Transfers data fields (group attributes) to CleverReach. The following data fields are currently transferred from plentymarkets to CleverReach: *Birthday*, *First name*, *Gender (form of address)*, *Lang (language)* and *Last name*. Select the area from the drop-down list. +
*_Note:_* This is to be carried out before you transfer the actual customer data. Refer to the following instructions.

| *API key*
|Enter the API key that you received from CleverReach.

| *List ID*
|Enter the list ID that you received from CleverReach.

| *Order referrers*
|Select the order referrers that should be available for CleverReach. Referrers that do not allow data to be transferred are not selected by default. +
*_Note:_* Check the selected order referrers before you begin working with CleverReach. This helps you avoid potential warnings or reprimands.

| *Export starting with order status*
|Select a status. Data is exported starting from this status.

| *Automatic transfer (daily)*
|Activate if data should automatically be transferred every day.
|====

[IMPORTANT]
.First transfer
====
During the first automatic transfer, customer data is transferred from the past 3 days. After that, only new customers' data is transferred.
====

You can use filters in CleverReach if you do not want to write to all customers whose data you have transferred to CleverReach. Further information can be found on the link:https://support.cleverreach.de/hc/en-us[CleverReach^]{nbsp}icon:external-link[] support page.

[#2000]
=== Manually transmitting data

Use the *Carry out data transfer* option to only transfer customer data for a specific customer type. This allows you to sort the plentymarkets customer types into different CleverReach groups.

[IMPORTANT]
.Should I use the automatic transfer?
====
If you use the option *Carry out data transfer* in order to transfer data filtered by customer type, you may have to deactivate the automatic transfer. The automatic transfer transfers all new data without considering the different customer types.
====

[.instruction]
Manually transmitting data:

. Go to *Setup » CRM » Newsletter » CleverReach*.
. Enter your *API key*.
. Enter the *List ID* of the group that you created in CleverReach.
. *Save* (icon:save[role="green"]) the settings.
. Click on *Generate group attributes* (icon:cog[]). +
→ Data fields are set up in CleverReach. This way the data that you transfer can be saved and processed.
. Open the CleverReach back end and open the group whose list ID you entered into plentymarkets.
. Delete the data fields that you do not want to use in CleverReach. +
→ The following data fields are currently transferred from plentymarkets to CleverReach: *Birthday*, *First name*, *Gender (form of address)*, *Lang (language)* and *Last name*.
. Go back to *Setup » CRM » Newsletter » CleverReach* in your plentymarkets back end.
. Select the customer type from the drop-down list *Carry out data transfer*.
. *Save* (icon:save[role="green"]) the settings.
. Click on *Export*. +
→ The customer data is transmitted.
