= MyViews kennenlernen
:keywords: MyViews, myviews, MyView, myview, Ansichten gestalten, Ansicht gestalten, myView nutzen, myView verwenden, myView einrichten, Elemente platzieren, myView Rechte, myView Benutzerrechte
:description: Auf dieser Seite zeigen wir dir, was genau MyViews sind und wie du sie optimal für dein Business nutzen kannst.
:author: denise-breidenbach

[#100]
= Was bedeutet MyView?

MyViews sind Benutzeroberflächen in deinem System, die auf einer speziell von plentysystems entwickelten Technologie basieren. Während du viele Bereiche in plentysystems nicht verändern kannst, hast du bei MyViews die Möglichkeit, das Layout auf vielfältige Weise anzupassen. Beispielsweise kannst du Bereiche nach deinen Wünschen anordnen, Elemente hinzufügen und individuelle Filtereinstellungen vornehmen - und das sind nur einige Möglichkeiten, die dir MyViews bieten. Auf dieser Handbuchseite möchten wir dir einen zentralen Einblick in die besonderen MyView-Funktionen geben.

Die wichtigsten Bereiche in plentysystems sind über die letzten Jahre umgestaltet worden und stehen als MyView zur Verfügung, um dir ein Maximum an Flexibilität zu bieten. <<table-myview-overview>> enthält eine Liste aller verfügbarer MyViews - klicke einfach auf die Links, um detaillierte Informationen über die einzelnen Menüs zu erhalten.

[[table-myview-overview]]
.MyViews im Überblick
[cols="1,3,2"]
|===
|Menüpfad |Beschreibung |Weiterführende Links
| *Aufträge » Aufträge*
|
|

| *Artikel » Artikel (Testphase)*
|
|

| *CRM » Kontakte*
|
|

| *plentysystems Logo (Start) » Dashboard*
|
|

|===

* Die neue Auftrags
- Was ist/bedeutet myView? 
- Wo kommen myViews im System vor? Item UI, Order UI, Dashboard, Kontakt-UI - inkl. Verlinkungen zu Handbuchseiten
- Warum sind myViews so toll?




////

TODO: Funktionen, die für jede myView verfügbar sind und immer gleich funktionieren

- Bearbeitungsmodus (siehe Include)
- Neue Ansicht erstellen (siehe Include)
- Element platzieren (siehe Include)
- Filter speichern und gespeicherte Filter anwenden (siehe Include)
- Standardfilter festlegen (siehe Include)
- Einstellungen, um Bereiche standardmäßig ein- oder auszuklappen
- Abstandshalter einfügen
- Zeilen fixieren
- Ansicht importieren und exportieren

////


////

TODO: Sonstige Informationen

- Gibt es Standardansichten, die voreingestellt sind? Was sind dabei die Besonderheiten?
- Berechtigungen für myViews
- Wer kann myViews anlegen? - nur Admins
- Wie vergebe ich Rechte?
- Kann ich Sichtbarkeiten sonst irgendwie einschränken?

////