= Zahlungsabwicklung einrichten
:icons: font
:id: LKPTJCQ
:author: team-order-payment

IMPORTANT: Hast du schon das Plugin-Set *standard-shop* deaktiviert? Noch nicht? Dann geht's hier zurück zum Thema xref:willkommen:schnelleinstieg-webshop-einleitung.adoc#[Webshop einrichten: Einleitung].

In diesem Abschnitt des Schnelleinstiegs findest du grundlegende Informationen zum Einbinden von Zahlungsarten in deinen Webshop sowie zu den notwendigen Grundeinstellungen, damit Zahlungen korrekt in deinem plentymarkets System verarbeitet werden.

[#10]
== Zahlungsarten einrichten

In deinem plentyShop kannst du deinen Kund:innen verschiedene Zahlungsarten anbieten. Alle Zahlungsarten werden über die Plugin-Struktur von plentymarkets integriert. Je nach deinen Wünschen kannst du eine Vielzahl von Zahlungsarten in deinem Webshop anbieten.

Der Download der Payment Plugins erfolgt im link:https://marketplace.plentymarkets.com/plugins/payment[plentyMarketplace^]{nbsp}icon:external-link[]. Auf der Handbuchseite xref:payment:payment-plugins.adoc#[Payment Plugins] findest du Informationen sowie Anleitungen zum Einrichten für die von plentymarkets entwickelten Payment Plugins. +
Assistenten führen durch alle Einstellungen und beinhalten die notwendigen Konfigurationen. Nach Download des Plugins findest du die Assistenten in deinem System im Menü *Einrichtung » Assistenten » Plugins » [Plugin-Set wählen]*. Wähle hier das Plugin-Set, in dem das Plugin installiert werden soll. Informationen, wie du dafür vorgehst, findest du im Abschnitt xref:willkommen:schnelleinstieg-plugins.adoc#[Plugins dem System hinzufügen] des Schnelleinstiegs.

[#20]
== Grundeinstellungen für Zahlungen vornehmen

Zusätzlich zur Einrichtung der Plugins für die Zahlungsarten musst du noch einige Einstellungen in deinem plentymarkets System vornehmen, damit die Zahlungen im Allgemeinen korrekt verarbeitet werden. Zudem ist die Angabe deiner Umsatzsteuer-ID verpflichtend.

[#90]
=== Regeln für Zahlungseingänge festlegen

Damit Zahlungseingänge wie gewünscht erfasst werden, nimm zuerst die Grundeinstellungen für Zahlungen vor.

[.instruction]
Regeln für Zahlungseingänge festlegen:

. Öffne das Menü *Einrichtung » Aufträge » Zahlung » Eingänge*.
. Nimm die Einstellungen anhand der Informationen in <<table-basic-settings-incoming-payment>> vor.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[[table-basic-settings-incoming-payment]]
.Grundeinstellungen für Zahlungseingänge vornehmen
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Übereinstimmung für automatische Zuordnung*
|Gehen Zahlungen in dein System ein, werden sie anhand einer Überprüfung der Übereinstimmung automatisch zu einem Auftrag zugeordnet. Wähle dafür einen Wert zwischen *0.7* (nicht so genaue Übereinstimmung zur Zuordnung nötig) und *1.0* (genaue Übereinstimmung nötig). Ist dieser Wert höher eingestellt, kann das Problem auftreten, dass Zahlungen nicht zugeordnet werden können. Daher ist in der *Standard-Einstellung* ein Wert von *0,75* eingestellt.

| *Zahlungskulanz*
|Damit z.B. interne Nachkommabeträge (ab der dritten Nachkommastelle) nicht zu falschen Buchungen führen, sollte ein *Mindestbetrag* von *0,01* eingetragen sein (Standard-Einstellung). Wenn z.B. *0,05* eingestellt ist, werden Fehlbeträge bis 5 Cent trotzdem als korrekte Buchung behandelt.

| *Kundenbankdaten importieren*
|Wählen, ob die *Bankdaten* der Kund:innen beim Zahlungseingang *importiert* und in den jeweiligen *Kundendaten* hinterlegt werden sollen oder nicht. +
*_Wichtig:_* Da Bankdaten nur mit Zustimmung der Kund:innen importiert und gespeichert werden dürfen, ist hier standardmäßig *Nein* voreingestellt. Vor dem Aktivieren die Rechtslage zu diesem Thema beachten, ggf. auch im jeweiligen Lieferland.

|*Aufträge mit folgenden Zahlungsarten von der automatischen Zuordnung ausschließen*
|Wähle hier Zahlungsarten aus, für die keine Zahlungen ins System eingehen. Diese werden dann bei der automatischen Zahlungszuordnung nicht beachtet. +
Eine Mehrfachauswahl ist über die Tastatur möglich.

|*Aufträge mit folgenden Herkünften von der automatischen Zuordnung ausschließen*
|Wähle hier Herkünfte aus, für die keine Zahlungen ins System eingehen. Diese werden dann bei der automatischen Zahlungszuordnung nicht beachtet. +
Eine Mehrfachauswahl ist über die Tastatur möglich.

|====

[#100]
=== Umsatzsteuer-ID hinterlegen

Für den Standort Deutschland sind die gesetzlich vorgeschriebenen Umsatzsteuersätze von 19% und 7% bereits voreingestellt. Steuerrechtlich verpflichtend ist zusätzlich die Angabe deiner Umsatzsteuer-ID. Gehe wie folgt vor, um eine Umsatzsteuer-ID für Deutschland anzugeben.

[.instruction]
Umsatzsteuer-ID hinterlegen:

. Öffne das Menü *Einrichtung » Mandant » [Mandant wählen] » Standorte » [Standort wählen] » Buchhaltung*.
. Öffne das Tab *Umsatzsteuersätze*.
. Öffne die Konfiguration *Deutschland*.
. Gib im Feld *Umsatzsteuer-ID* deine Umsatzsteuer ein.
. *Speichere* (icon:save[role="green"]) die Einstellung.

[IMPORTANT]
.Standorte und steuerliche Einstellungen
====
Die Einstellungen zu Steuersätzen sowie die weiteren Optionen im Tab *Buchhaltung* sind standortabhängig. Das bedeutet, dass du für jedes weitere Lieferland außer Deutschland die korrekten Steuersätze hinterlegen musst. Wir empfehlen bei Unsicherheit grundsätzlich, Änderungen mit einem Steuerberater zu besprechen. Beachte auch die Kapitel zum Thema xref:auftraege:buchhaltung.adoc#300[Umsatzsteuereinstellungen vornehmen] im Handbuchabschnitt xref:auftraege:buchhaltung.adoc#[Buchhaltung].
====

[#120]
== Mehr zum Thema Zahlungsabwicklung

* xref:auftraege:buchhaltung.adoc#[Buchhaltung]
* xref:payment:zahlungsarten-verwalten.adoc#[Zahlungsarten verwalten]
* xref:payment:beta-zahlungen-verwalten.adoc#[Zahlungen verwalten]
* xref:payment:bankdaten-verwalten.adoc#63[Bankdaten von Kund:innen speichern]

TIP: Weiter zum Thema xref:willkommen:schnelleinstieg-versandoptionen.adoc#[Versandoptionen einrichten].
