= Lager und Lieferant:in einrichten
:keywords: Lager, Lieferant, Lieferanten, Lager einrichten, Lieferant einrichten, Lieferanten einrichten
:id: ME2XTHD
:author: team-stock

IMPORTANT: Hast du schon deine Kontaktdaten gespeichert, dein E-Mail-Konto und die E-Mail-Vorlagen eingerichtet und eine Domain und das SSL-Zertifikat bestellt? Noch nicht? Dann geht's hier zurück zum Thema xref:willkommen:schnelleinstieg-basiseinstellungen.adoc#[Basiseinstellungen vornehmen].

Für eine funktionierende Warenwirtschaft müssen mindestens Lager, Lieferant:in und Warenbestand eingerichtet werden. Die beiden ersteren werden auf dieser Seite behandelt.

Wenn du die Warenbestände nicht in plentymarkets führen möchtest, wähle im Menü *Artikel » Artikel bearbeiten* im Tab *Varianten-ID » Einstellungen* bei der Einstellung *Beschränkung* die Option *Keinen Warenbestand für diese Variante führen*. Fahre dann fort mit xref:artikel:artikel-verwalten.adoc#660[Artikelbilder verwalten].

[#100]
== Lager einrichten

Im Folgenden ist beschrieben, wie du ein Lager einrichtest. Hier werden allerdings lediglich die Basiseinstellungen für ein Lager erläutert. Informationen zu detaillierteren Einstellungen sind auf den unten aufgeführten Handbuchseiten zu finden. +
Es wird empfohlen, von vornherein ein Vertriebslager und ein Reparaturlager einzurichten.

[.instruction]
Lager einrichten:

. Öffne das Menü *Einrichtung » Waren » Lager*.
. Wähle eines der bestehenden Lager *KS Repair* oder *KS Sales*.
. Klicke im Untermenü auf *Einstellungen* (icon:cog[]). +
→ Die Übersicht des Lagers wird geöffnet.
. Benenne das Lager im Feld *Lagername* um.
. Wähle einen Lagertyp und einen Logistiktyp.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Das Lager wird eingerichtet und links im Verzeichnisbaum angezeigt.
. Öffne das Lager, um die Untermenüs zu sehen.

[#200]
== Lieferant:innen einrichten

Im Folgenden ist beschrieben, wie du eine Lieferant:in einrichtest. Eine Lieferant:in ist hier nur Typ eines Kontakts.

[.instruction]
Lieferant:innen einrichten:

. Öffne das Menü *CRM » Kontakte*.
. Klicke auf *Neuen Kontakt erstellen*.
. Gib den Namen der Lieferant:in ein.
. Wähle den Typ *Lieferant*.
. Wähle im Feld *Neue Adresse* einen Adresstyp (Rechnungs- oder Lieferadresse).
. Gib die Adressdaten ein.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#300]
== Mehr zum Thema Lager und Lieferant:innen

* xref:warenwirtschaft:lager-einrichten.adoc#[Lager einrichten]
* xref:crm:kontakt-erstellen.adoc#[Kontakt erstellen].

TIP: Weiter zum Thema xref:willkommen:schnelleinstieg-webshop-einleitung.adoc#[Webshop einrichten: Einleitung]
