= Basiseinstellungen vornehmen
:description: Erfahre in diesem Teil des Schnelleinstiegs, welche Basiseinstellungen du vornehmen musst.
:id: U4A9SAW
:author: team-crm

IMPORTANT: Hast du schon Popups erlaubt, ein Lesezeichen für dein Backend-Login gesetzt und die Systemvoraussetzungen geprüft? Noch nicht? Dann geht's hier zurück zum Thema xref:willkommen:schnelleinstieg.adoc#[Schnell durchstarten].

In diesem Teil des Schnelleinstiegs findest du Erläuterungen zu allgemeinen Einstellungen wie dem Speichern von Firmen- und Bankdaten sowie zum Einrichten des E-Mail-Versands und E-Mail-Vorlagen. Außerdem erklären wir dir auf dieser Seite, wie du eine Domain und ein SSL-Zertifikat für deinen Webshop bestellst.

Für einige der genannten Einstellungen stehen dir unsere virtuellen Assistenten zur Verfügung. Diese helfen dir dabei, dein System Schritt für Schritt optimal einzurichten.

// TODO: für Dennis :) 
// Kapitel "Benutzer:innenkonto anpassen" hier einfügen

[#100]
== Eigene Firmen-, Kontakt - und Bankdaten speichern

[IMPORTANT]
.Vertragsdaten ändern
====
Eine Änderung der Stammdaten in diesem Menü ändert _nicht_ die Kundenstammdaten deines plentysystems Vertrages z.B. für die Rechnungsstellung. Vertragsdaten passt du im Menü *plentysystems Logo (Start) » Mein Konto* im Bereich *Verträge* an. +
Weitere Informationen findest du auf dieser xref:business-entscheidungen:dein-vertrag.adoc#[Handbuchseite].
====

Gib deine eigenen Firmen-, Kontakt- und Bankdaten im System ein. Diese Informationen kannst du später zum Beispiel über Variablen in deinen E-Mail-Vorlagen ausgeben. +
Weitere Informationen zu den Variablen findest du weiter unten auf dieser Seite in den Kapiteln xref:willkommen:schnelleinstieg-basiseinstellungen.adoc#600[Beispiel: E-Mail-Vorlage anpassen] und xref:willkommen:schnelleinstieg-basiseinstellungen.adoc#700[Variablen in die Vorlage einfügen].

=== Eigene Firmen- und Kontaktdaten speichern

Gehe wie im Folgenden beschrieben vor, um deine eigenen Firmen- und Kontaktdaten im System zu speichern.

[.instruction]
Firmen- und Kontaktdaten speichern:

. Öffne das Menü *Einrichtung » Einstellungen » Stammdaten*.
. Fülle die Felder aus bzw. wähle die Optionen aus den Dropdown-Listen.
. *Speichere* (material:save[]) die Einstellungen.

=== Eigene Bankdaten speichern

Gehe wie im Folgenden beschrieben vor, um deine eigenen Bankdaten im System zu speichern. +
Deine Bankdaten können über Variablen in E-Mail-Vorlagen ausgegeben werden. Das bedeutet, dass plentysystems in den E-Mails selbst die Variablen durch den jeweiligen Inhalt ersetzt. Die Variable `Kontoinhaber (Stammdaten)` wird so durch den Namen des Kontoinhabers ersetzt und `Bankname (Stammdaten)` setzt den Namen der Bank ein. `IBAN (Stammdaten)` wird durch die IBAN und `BIC (Stammdaten)` durch den BIC ersetzt. E-Mail-Vorlagen erstellst du schnell und einfach per Drag-and-drop mit dem xref:crm:emailbuilder.adoc#[EmailBuilder]. 

[.instruction]
Bankdaten speichern:

. Öffne das Menü *Einrichtung » Einstellungen » Bank*.
. Fülle die Felder aus.
. *Speichere* (material:save[]) die Einstellungen.

[#150]
== Standorte anlegen

Öffne das Menü *Einrichtung » Assistenten* und dort den Bereich *Grundeinrichtung*. Durchlaufe dann den Assistenten *Standorte*, um die folgenden Einstellungen vorzunehmen:

* Standort anlegen und Umsatzsteuer-Identifikationsnummer speichern
* Brutto- oder Netto-Auftragssummen auf deinen Rechnungen für die Lieferung in EU-Mitgliedsstaaten und Nicht-EU-Staaten festlegen
* Rundungsverhalten der Auftragssummen speichern
* Umsatzsteuersätze für den Standort speichern

[TIP]
.Standard-Standort ändern
====
Den Standard-Standort änderst du im Menü *Einrichtung » Mandant » [Mandant wählen] » Einstellungen*. Der Standard-Standort wird dann z.B. auch im Bestellvorgang im Webshop verwendet, was u.a. die Anzeige der MwSt. beeinflusst. +
*_Hinweis:_* Wenn du in diesem Menü Änderungen vornimmst, werden andere Benutzer:innen automatisch ausgeloggt und müssen sich neu einloggen, damit die Änderungen auch für diese Benutzer:innenprofile greifen.

Weitere Informationen zu den Einstellungen in diesem Menü findest du auf der Handbuchseite xref:webshop:mandanten-verwalten.adoc#20[Mandanten verwalten].

Beachte außerdem, dass du das xref:fulfillment:versand-vorbereiten.adoc#200[Lieferland] für den Standort erst im Menü *Einrichtung » Aufträge » Versand » Optionen » Tab: Lieferländer* aktivieren musst, damit es dir als neuer Standard-Standort im Menü *Einrichtung » Mandant » [Mandant wählen] » Einstellungen* zur Verfügung steht.
====

[#250]
== Kundenklasse erstellen

Mit Kundenklassen unterteilst du deinen Kundenstamm nach unterschiedlichen Kriterien. Du kannst z.B. Mindestbestellmengen festlegen, Rabatte gewähren und entscheiden, ob die Preise in deinem Webshop in brutto oder netto angezeigt werden.

Für den Anfang empfehlen wir dir das Erstellen von 2 Kundenklassen:

* B2C für deine Endkund:innen
* B2B für Händler:innen

Du benötigst die Kundenklassen für eventuelle weitere Einstellungen, die du in deinem System vornehmen möchtest, wie z.B. das Speichern von Verkaufspreisen.

[.instruction]
Kundenklasse erstellen:

. Öffne das Menü *Einrichtung » CRM » Kundenklassen*.
. Wechsele in das Tab *Neue Kundenklasse*.
. Nimm die gewünschten Einstellungen vor. Beachte dazu die Erläuterungen in <<#table-quick-start-create-customer-class>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[[table-quick-start-create-customer-class]]
.Kundenklasse erstellen
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Bezeichnung*
|Name für die Kundenklasse eingeben, z.B. Standardkund:innen oder B2C.

| *Rabattart*
|Ggf. Rabattart wählen. Weitere Informationen zu den Rabattarten findest du auf der Handbuchseite xref:crm:vorbereitende-einstellungen.adoc#[Vorbereitende Einstellungen vornehmen] im Kapitel xref:crm:vorbereitende-einstellungen.adoc#rabattsystem-nutzen[Rabattsystem nutzen].

| *Erlaubte Zahlungsarten*
|Wählen, welche Zahlungsarten, die später in deinem Webshop verfügbar sind, für die Kundenklasse erlaubt sein sollen. Standardmäßig sind alle verfügbaren Zahlungsarten erlaubt.

| *Anzeige der Preise im Webshop*
|Wählen, ob die Preise im Webshop brutto oder netto angezeigt werden sollen.

|====

Weitere Informationen und Einstellungsmöglichkeiten in den Kundenklassen findest du auf der Handbuchseite xref:crm:vorbereitende-einstellungen.adoc#kundenklasse-erstellen[Vorbereitende Einstellungen vornehmen].

[#300]
== E-Mail-Versand einrichten

Öffne das Menü *Einrichtung » Mandant » Global » E-Mail-Konten*. Durchlaufe dann den Assistenten *E-Mail-Konten*, um die folgenden Einstellungen vorzunehmen:

* Zugangsdaten deines E-Mail-Kontos speichern, damit plentysystems über dein E-Mail-Konto E-Mails für dich versenden kann. Beachte, dass es möglich sein kann, dass du dir eine Freigabe bei deinem E-Mail-Provider einholen musst, damit plentysystems die E-Mails versenden darf.
* Live-Modus aktivieren
* Signatur für deine ausgehenden E-Mails speichern
* Infodienst aktivieren, um eine Blindkopie aller ausgehenden E-Mails zu erhalten
* E-Mail-Vorlagen mit bestimmten Ereignissen verknüpfen, damit diese Vorlagen bei Eintritt des Ereignisses an deine Kund:innen versendet werden.

[TIP]
.Testmodus sendet E-Mails nur an deine E-Mail-Adresse
====
Es gibt einen Testmodus, der standardmäßig aktiviert ist. Im Testmodus werden alle E-Mails nur an die von dir eingegebene E-Mail-Adresse gesendet. So kannst du alle Einstellungen und Inhalte testen, bevor du live mit dem E-Mail-Versand arbeitest.
====

[#500]
== E-Mail-Vorlagen einrichten

plentysystems erzeugt alle E-Mails auf Basis von Vorlagen. <<#table-email-templates>> listet die E-Mail-Vorlagen auf, deren Einrichtung wir dir für den Anfang empfehlen. E-Mail-Vorlagen werden im Menü *CRM » EmailBuilder* erstellt.

Du kannst alle E-Mail-Vorlagen an deine Erfordernisse anpassen. Weiter unten auf dieser Seite im Kapitel xref:willkommen:schnelleinstieg-basiseinstellungen.adoc#600[Beispiel: E-Mail-Vorlage anpassen] findest du ein Beispiel, wie du die E-Mail-Vorlage *Shop: Eingangsbestätigung Bestellung* anpasst.

[[table-email-templates]]
.Bereits vorkonfigurierte E-Mail-Vorlagen
[cols="1,3"]
|====
|E-Mail-Vorlage |Erläuterung

| *Auftrag: Rechnung PDF-Anhang*
|Sendet die Rechnung als Dateianhang an deine Kund:innen. +
*_Wichtig:_* Eine Rechnungsvorlage für den Standort *Deutschland* ist bereits vorkonfiguriert. Du kannst die Vorlage nach Bedarf im Menü *Einrichtung » Mandant » [Mandant wählen] » Standorte » [Standort wählen] » Dokumente » Rechnung* anpassen. Wenn eine Rechnung für den Auftrag existiert und du eine Ereignisaktion eingerichtet hast, wird die Rechnung automatisch an deine Kund:innen versendet, weil in der Vorlage *Auftrag: Rechnung PDF-Anhang* der PDF-Anhang *Rechnung* bereits standardmäßig gewählt ist. +
 Weitere Informationen dazu findest du auf der Schnelleinstiegsseite xref:willkommen:schnelleinstieg-automatisierung.adoc#[Vorgänge automatisieren].

| *Auftrag: Versandbestätigung*
|Wird bei Versand der Ware verschickt. +
*_Tipp:_* Erstelle eine xref:willkommen:schnelleinstieg-automatisierung.adoc#20[Ereignisaktion] mit dem Ereignis *Paketnummer* und füge Filter und Aktionen hinzu, damit die am Auftrag gespeicherte Paketnummer über die Variable `Tracking-URL` ausgegeben wird. Weitere Informationen findest du auf der Schnelleinstiegsseite xref:willkommen:schnelleinstieg-automatisierung.adoc#[Vorgänge automatisieren].

| *Shop: Eingangsbestätigung Bestellung*
|Benachrichtigung an deine Kund:innen, dass die Bestellung eingegangen ist. +
*_Wichtig:_* In dieser E-Mail-Vorlage solltest du aus rechtlichen Gründen eine Widerrufsbelehrung sowie die AGB einfügen. Von großer Bedeutung in dieser E-Mail-Vorlage sind alle Formulierungen, die das vertragliche Verhältnis mit den Kund:innen betreffen. Deine Texte solltest du daher von einem kundigen Anwaltsbüro prüfen lassen. +
Die Texte für die Widerrufsbelehrung und die AGB speicherst du im Menü *Einrichtung » Mandant » [Mandant wählen] » Webshop » Rechtliches*. Über die Variablen `Widerrufsrecht im HTML-Format` und `Allgemeine Geschäftsbedingungen im HTML-Format` werden das Widerrufsrecht und die AGB dann automatisch in der E-Mail ausgegeben.
|====

[TIP]
====
Es gibt viele weitere xref:crm:emailbuilder.adoc#standardvorlagen-verwenden[Standardvorlagen], die bereits in deinem System vorhanden sind. Diese E-Mail-Vorlagen musst du ggf. anpassen und mit einem Ereignis im Menü *Einrichtung » Assistenten » Grundeinrichtung* im Assistenten *E-Mail-Konten* im Schritt *Automatischer Versand* verknüpfen oder eine Ereignisaktion einrichten. Weitere Informationen findest du auf der Schnelleinstiegsseite xref:willkommen:schnelleinstieg-automatisierung.adoc#[Vorgänge automatisieren].
====

[#550]
=== Rechtliche Angaben speichern

Es ist wichtig, dass du vorab die rechtlichen Angaben für deinen Webshop speicherst. Dazu zählen die AGB, das Widerrufsrecht, die Datenschutzerklärung, das Impressum sowie das Widerrufsformular. In der E-Mail-Vorlage selbst fügst du Variablen ein, die den Text in der E-Mail-Vorlage dann ersetzen.

Wir empfehlen, die Texte im Vorfeld von einem kundigen Anwaltsbüro prüfen zu lassen, bevor du diese verwendest.

[.instruction]
Rechtliche Angaben speichern:

. Öffne das Menü *Einrichtung » Mandant » [Mandant wählen] » Webshop » Rechtliches*.
. Klappe die Sprache *Deutsch* auf (icon:plus-square-o[]).
. Füge die Texte in den jeweiligen Tabs *AGB*, *Widerrufsrecht*, *Datenschutzerklärung*, *Impressum* und *Widerrufsformular* im Tab *HTML* ein. +
*_Tipp:_* Lasse die Texte zu den rechtlichen Angaben von einem kundigen Anwaltsbüro prüfen.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#600]
=== Beispiel: E-Mail-Vorlage anpassen

Anhand des Beispiels der E-Mail-Vorlage *Shop: Eingangsbestätigung Bestellung* beschreiben wir im Folgenden, wie du eine E-Mail-Vorlage im EmailBuilder anpasst.

[.instruction]
E-Mail-Vorlage anpassen:

. Öffne das Menü *CRM » EmailBuilder*.
. Klappe den Ordner auf (material:chevron_right[]), der die Vorlage enthält, die du bearbeiten möchtest.
. Klicke auf die Vorlage.
. Klicke auf material:edit[] (*Bearbeiten*).
. Ändere ggf. den Text.
. Füge z.B. die Variablen `Widerrufsrecht im HTML-Format` und `Allgemeine Geschäftsbedingungen im HTML-Format` ein, damit in der versendeten E-Mail-Vorlage die Texte für die AGB und das Widerrufsrecht ausgegeben werden. +
*_Hinweis 1:_* Die Texte hast du vorab im System gespeichert wie in Kapitel xref:willkommen:schnelleinstieg-basiseinstellungen.adoc#550[Rechtliche Angaben speichern] beschrieben. +
*_Hinweis 2:_* Die verfügbaren Variablen kannst du links neben der geöffneten Vorlage suchen.
. Weitere Informationen zu den Variablen für rechtliche Angaben findest du in <<#table-emailbuilder-variables-legal>> am Ende dieses Kapitels.
. Ersetze die Musterkontaktdaten am Ende der Vorlage durch deine Kontaktdaten. +
*_Tipp:_* Du kannst dafür die Variable `Signatur im HTML-Format` verwenden.
. *Speichere* (material:save[]) die Einstellungen.

[[table-emailbuilder-variables-legal]]
.EmailBuilder-Variablen für die rechtlichen Angaben
[cols="1,3,3"]
|====
|Rechtliche Angabe |Variable |Wo speichere ich den Text?

| *AGB*
| `Allgemeine Geschäftsbedingungen im HTML-Format`
|im Menü *Einrichtung » Mandant » [Mandant wählen] » Webshop » Rechtliches » [Sprache aufklappen]* im Tab *AGB* im Tab *HTML*

| *Widerrufsrecht*
| `Widerrufsrecht im HTML-Format`
|im Menü *Einrichtung » Mandant » [Mandant wählen] » Webshop » Rechtliches » [Sprache aufklappen]* im Tab *Widerrufsrecht* im Tab *HTML*

| *Datenschutzerklärung*
| `Datenschutzerklärung im HTML-Format`
|im Menü *Einrichtung » Mandant » [Mandant wählen] » Webshop » Rechtliches » [Sprache aufklappen]* im Tab *Datenschutzerklärung* im Tab *HTML*

| *Impressum*
| `Impressum im HTML-Format`
|im Menü *Einrichtung » Mandant » [Mandant wählen] » Webshop » Rechtliches » [Sprache aufklappen]* im Tab *Impressum* im Tab *HTML* 

| *Widerrufsformular*
| `Widerrufsformular im HTML-Format`
| im Menü *Einrichtung » Mandant » [Mandant wählen] » Webshop » Rechtliches » [Sprache aufklappen]* im Tab *Widerrufsformular* im Tab *HTML*

|====

[#650]
=== Vorlage für die Eingangsbestätigung mit einer Ereignisaktion verknüpfen

Du hast die E-Mail-Vorlage *Shop: Eingangsbestätigung Bestellung* nach deinen Erfordernissen <<#600, angepasst>> und gespeichert? Sehr gut! Richte nun eine Ereignisaktion, damit die E-Mail-Vorlage *Shop: Eingangsbestätigung Bestellung* automatisch an deine Kund:innen versendet wird, wenn diese eine Bestellung in deinem Webshop aufgegeben haben.

[.instruction]
Vorlage für die Eingangsbestätigung mit einer Ereignisaktion verknüpfen:

. Öffne das Menü *Einrichtung » Aufträge » Ereignisse*.
. Klicke auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
. Gib einen Namen ein, z.B. `Neuer Auftrag Webshop`.
. Wähle das *Ereignis* gemäß <<#table-event-procedure-new-order-online-shop>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen.
. Nimm die Einstellungen gemäß <<#table-event-procedure-new-order-online-shop>> vor.
. Setze ein Häkchen bei *Aktiv*.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[[table-event-procedure-new-order-online-shop]]
.Ereignisaktion zum automatischen Versenden einer Eingangsbestätigung bei Bestellung in deinem Webshop
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

| *Ereignis*
| *Auftragsanlage: Neuer Auftrag*
| 

| *Filter*
| *Auftrag > Herkunft*
| *Mandant (Shop)*

| *Aktion*
| *Kunde > E-Mail versenden*
| Angepasste Vorlage **Shop: Eingangsbestätigung Bestellung** hinzufügen und als Empfänger *Kunde* wählen

|====

[#700]
=== Variablen in die Vorlage einfügen

In E-Mail-Vorlagen kannst du beliebig viele Variablen einfügen. In den E-Mails selbst ersetzt plentysystems die Variablen und durch den jeweiligen Inhalt. Die Variable `Vollständiger Name` wird so z.B. durch den Vornamen und Nachnamen der Kund:in ersetzt und die Variable `Auftrags-ID` setzt die ID des Auftrags ein.

[.instruction]
Variablen in die Vorlage einfügen:

. Öffne das Menü *CRM » EmailBuilder*.
. Öffne die E-Mail-Vorlage, in die du Variablen einfügen möchtest.
. Klicke auf material:edit[] (*Bearbeiten*). +
→ Der Editor mit der Vorlage wird geöffnet.
. Klicke erneut auf material:edit[] (*Bearbeiten*). +
→ Links neben der Vorlage siehst du den Bereich *Variablen*.
. Gib im Feld *Suche* den Namen der Variable ein oder klappe die verschiedenen Kategorien auf, um die Variablen zu suchen.
. Mit einem Klick auf die Variable fügst du die Variable an der gewünschten Stelle deiner Vorlage ein. 
. *Speichere* (material:save[]) die Einstellungen.

[TIP]
.Variable `URL zur Auftragsübersicht` einfügen
====
Alle E-Mails an deine Kund:innen sollten die Variable `URL zur Auftragsübersicht` enthalten. Diese Funktion gibt den Link zum Bereich *Mein Konto* deines Webshops aus. Mit einem Klick auf diesen Link können deine Kund:innen jederzeit ihre Daten aktualisieren, die Auftragshistorie einsehen, weitere Artikel zur Bestellung hinzufügen und den Status der Bestellung verfolgen.
====

[#800]
=== Dateien an E-Mail-Vorlagen anhängen

Du kannst 2 Arten von Dateien an deine E-Mail-Vorlagen anhängen:

* dynamische Anhänge 
* statische Anhänge

Den Unterschied dieser beiden Anhänge beschreiben wir im Folgenden.

Die möglichen Typen eines dynamischen Anhangs, z.B. Rechnung oder Lieferschein, sind xref:auftraege:auftragsdokumente.adoc#100[standortbezogene Dokumente] in deinem System. Diese Dokumente richtest du im Menü *Einrichtung » Mandant » [Mandant wählen] » Standorte » [Standort wählen] » Dokumente* ein.

Statische Anhänge können z.B. ein Artikelprospekt, eine Anleitung oder eine Fotodatei sein. Du lädst diese Dateien im Menü *CMS » Dokumente* hoch.

[#900]
==== Dynamischen Anhang erstellen und anhängen

Die Dokumente, die du als dynamischen Anhang versenden kannst, werden automatisch von deinem System erzeugt. Ein Beispiel für ein solches Dokument ist die Rechnung.

Das Einrichten erfolgt in 3 Schritten:

1. Dokumentenvorlage, z.B. eine Geschäftsbriefvorlage inklusive Logo, erstellen und auf deinem Rechner speichern
2. Dokumenteinstellungen anpassen (im Folgenden detaillierter beschrieben)
3. Dokument mit der E-Mail-Vorlage verknüpfen (im Folgenden detaillierter beschrieben)

[.instruction]
Dokumenteinstellung anpassen:

. Öffne das Menü *Einrichtung » Mandant » [Mandant wählen] » Standorte » [Standort wählen] » Dokumente*.
. Wähle das Dokument, das du bearbeiten möchtest, z.B. *Rechnung*. +
*_Hinweis:_* Das Dokument *Rechnung* ist bereits voreingestellt. Passe die Rechnungsvorlage ggf. an.
. Wechsele in das Tab *PDF-Vorlage*.
. Klicke auf *Vorlage hinzufügen* (icon:plus-square[role="green"]).
. Wähle ggf. eine *Zahlungsart*. +
*_Hinweis:_* Standardmäßig ist die Einstellung *Standard* gewählt.
. Klicke auf *Vorlage auswählen* (icon:upload[role="purple"]).
. Öffne die zuvor erstellte PDF-Dokumentvorlage.
. Klicke auf *Vorlage hochladen* (icon:save[role="green"]).
. Klicke auf *Vorschau* (icon:eye[role="blue"]), um eine Vorschau des Dokuments anzeigen zu lassen.
. Klicke auf *Löschen* (icon:minus-square[role="red"]), um das Dokument zu löschen.

[.instruction]
Dokument mit der E-Mail-Vorlage verknüpfen:

. Öffne das Menü *CRM » EmailBuilder*.
. Öffne die E-Mail-Vorlage.
. Wähle (material:check_box[role=skyBlue])auf der rechten Seite im Bereich *Einstellungen* aus der Dropdown-Liste *Dynamische Anhänge* die Datei, die du als Anhang versenden möchtest.
. *Speichere* (material:save[]) die Einstellungen. +
→ Das Dokument wird als Anhang mit versendet.

[#1000]
==== Statischen Anhang erstellen und anhängen

Alle Dokumente, die du über eine E-Mail-Vorlage als statischen Anhang versenden möchtest, müssen vorher im System hochgeladen werden. Ein Beispiel für ein solches Dokument sind die AGB, weil dieses Dokument häufig als Anhang der Eingangsbestätigung einer Bestellung versendet wird – vorausgesetzt du hast die AGB _nicht_ über die Variable `Allgemeine Geschäftsbedingungen im HTML-Format` direkt in der Vorlage eingefügt.

Das Einrichten erfolgt in 2 Schritten. Zunächst lädst du das Dokument im Menü *CMS » Dokumente* hoch. Dann verknüpfst du das Dokument mit einer E-Mail-Vorlage. Gehe dazu wie im Folgenden beschrieben vor.

[.instruction]
Dokument hochladen:

. Öffne das Menü *CMS » Dokumente*.
. Klicke im Tab *Upload* auf *Datei auswählen*.
. Wähle die Datei, die du hochladen möchtest, und klicke auf *Öffnen*.
. Wähle eine der Optionen unter *Berechtigung*. +
*_Hinweis:_* Mit der Berechtigung legst du fest, ob das Dokument nur für *Mitarbeiter*, nur für *Kunden* oder *öffentlich*, also für alle Besucher:innen des Webshops, verfügbar sein soll.
. Gib ggf. einen Namen für den Ordner ein.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[.instruction]
Dokument mit einer E-Mail-Vorlage verknüpfen:

. Öffne das Menü *CRM » EmailBuilder*.
. Öffne die E-Mail-Vorlage.
. Klicke ganz oben rechts auf material:translate[] *Sprachabhängige Einstellungen*.
. Wähle in der richtigen Sprache aus der Dropdown-Liste *Statische Anhänge* die Datei, die du als Anhang versenden möchtest.
. *Speichere* (material:save[]) die Einstellungen. +
→ Die Datei wird als Anhang mit versendet.

[#1100]
== Domain bestellen

Der Begriff "Domain" bezeichnet eine Internetadresse in Form eines Namens sowie einer Erweiterung, der Top-Level-Domain, z.B. *.de*. Du kannst den Namen frei wählen. Eine Domain ist einmalig und darf weltweit nicht doppelt vorkommen. Bei der Registrierung der Domain, zum Beispiel bei einem Hosting-Dienstleister, wird daher geprüft, ob deine gewünschte Domain noch nicht vergeben ist.

Weitere Informationen findest du auf der Handbuchseite xref:business-entscheidungen:domains.adoc#[Domains].

[#1200]
== SSL-Zertifikat bestellen

Ein SSL-Zertifikat dient dazu, deine Website zu verschlüsseln und gewährleistet eine sichere Verbindung zu deinem Webshop. Wenn du ein SSL-Zertifikat verwendest, ist deine Website über _https_ erreichbar.
Wichtig ist, dass die Domain, für die du das SSL-Zertifikat bestellen möchtest, eine aktivierte Hauptdomain ist.

Weitere Informationen findest du auf der Handbuchseite xref:business-entscheidungen:ssl-zertifikat_bestellen.adoc#[SSL-Zertifikate].

[#1300]
== Checkliste

Arbeite die Checkliste durch, um deine Einstellungen zum Thema Basiseinstellungen zu prüfen.

[%interactive]

* [ ] Hast du den Assistenten *Basics* durchlaufen?
* [ ] Hast du den Assistenten *Standorte* durchlaufen?
* [ ] Hast du den Assistenten *E-Mail-Konten* durchlaufen?
* [ ] Hast du die Variable `Signatur im HTML-Format` am Ende deiner E-Mail-Vorlagen hinzugefügt?
* [ ] Hast du in allen E-Mail-Vorlagen die Musterdaten durch deinen eigenen Kontaktdaten ergänzt?
* [ ] Enthalten alle E-Mail-Vorlagen die Variable `URL zur Auftragsübersicht`?
* [ ] Hast du die Domain für deinen Webshop bestellt?
* [ ] Hast du ein SSL-Zertifikat gebucht?
* [ ] Hast du nach dem Testen den Testmodus deaktiviert, damit E-Mails ab sofort an deine Kund:innen und nicht mehr an dich selbst versendet werden?

[#1400]
== Mehr zum Thema Basiseinstellungen

* xref:crm:vorbereitende-einstellungen.adoc#kundenklasse-erstellen[Kundenklassen erstellen]
* xref:crm:emailbuilder.adoc#e-mail-server-zugangsdaten[E-Mail-Server-Zugangsdaten speichern]
* xref:crm:emailbuilder.adoc#vorlage-erstellen[Vorlage erstellen]
* xref:webshop:ceres-einrichten.adoc#legal[Rechtliche Angaben speichern]
// * xref:willkommen:schnelleinstieg-automatisierung.adoc#10[Automatischer E-Mail-Versand]
// * xref:crm:newsletter-versenden.adoc#[Newsletter]
// * xref:crm:ticketsystem-nutzen.adoc#[Ticketsystem]
* xref:business-entscheidungen:domains.adoc#[Domains]
* xref:business-entscheidungen:ssl-zertifikat_bestellen.adoc#[SSL-Zertifikat]
* xref:business-entscheidungen:dein-vertrag.adoc#[Dein Vertrag mit plentysystems]

TIP: Weiter zum Thema xref:willkommen:schnelleinstieg-warenwirtschaft.adoc#[Lager und Lieferant:in einrichten]
