= Dein System personalisieren
:keywords: Benutzerkonto, Benutzerbild, Gravatar, Grußformel, Signatur, SignatureHTML, Persönliche Einstellungen, Menüansicht, Ansicht einrichten, Shortcut, Tastenkürzel, Tastenkombination, Startseite, Favorit, CSS-Editor, Aufgaben, Kalender
:description: Bist du neu bei plentymarkets? Dann empfiehlt es sich, zunächst dein Benutzerkonto und System individuell anzupassen.
:author: denise-breidenbach

Diese Handbuchseite beschreibt die Einstellungen, mit denen du dein Benutzerkonto und auch weitere Bereiche deines plentymarkets Systems individuell anpassen kannst.

[#10]
== Dein eigenes Benutzerkonto anpassen

[#20]
=== Benutzerkonto öffnen

Es gibt zwei Möglichkeiten, auf dein eigenes Benutzerkonto zuzugreifen.

* Bewege den Mauszeiger über das Benutzersymbol oben rechts (icon:user-circle[]) und klicke dann auf deinen Namen.
* Öffne das Menü *Einrichtung » Einstellungen » Benutzer » Konten*. Klicke dann auf die Schaltfläche icon:user[] *Mein Konto*.

[#30]
=== Benutzerbild hinzufügen

Um ein Benutzerbild statt der leeren Benutzer-Schaltfläche (icon:user-circle[]) in deinem plentymarkets Backend anzeigen zu lassen, musst du bei link:https://de.gravatar.com/[gravatar.com^] angemeldet sein.

[.instruction]
Benutzerbild hinzufügen:

. <<#20, Öffne dein eigenes Benutzerkonto>>. +
→ Das Tab *Stammdaten* öffnet sich.
. Gib im Feld *E-Mail* die E-Mail-Adresse, mit der du bei gravatar.com angemeldet bist, ein.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Lade das System neu, um das Benutzerbild zu sehen.

[#40]
=== Grußformel

Im Tab *Grußformel* gibst du einen Text ein, der deinen Nachrichten und Kommentaren im Ticketsystem automatisch als Grußformel angefügt wird. Dieser besteht in der Regel nur aus einem Briefabschluss sowie deinem Namen. Beim Versenden von E-Mails aus dem Ticketsystem wird erst die Grußformel und dann die <<#50, Signatur>> automatisch an die E-Mail angehängt.

[.instruction]
Grußformel einrichten:

. <<#20, Öffne dein eigenes Benutzerkonto>>.
. Wechsele in das Tab *Grußformel*.
. Gib deine Grußformel ein.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#50]
=== Signatur

Im Tab *Signatur* gibst du einen Text ein, der deinen Nachrichten und Kommentaren im Ticketsystem automatisch als Signatur angefügt wird. Diese besteht in der Regel aus deinen Kontaktdaten sowie Angaben zum Amtsgericht und Handelsregisternummer. Je nach Rechtsform des Unternehmens gehört die Angabe von Firmennamen, Namen von Geschäftsführer:innen sowie ggf. der USt-IdNr. zu den Pflichtangaben.
Beim Versenden von E-Mails aus dem Ticketsystem wird erst die <<#40, Grußformel>> und dann die Signatur automatisch an die E-Mail angehängt.

[TIP]
.Template-Variable für die Signatur
====
Die Template-Variablen *$Signature* und *$SignatureHTML* beinhalten die Grußformel.
====

[.instruction]
Signatur einrichten:

. <<#20, Öffne dein eigenes Benutzerkonto>>.
. Wechsele in das Tab *Signatur*.
. Gib deine Signatur ein.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[WARNING]
.Pflichtangaben in E-Mails
====
In Deutschland entsprechen seit Anfang 2007 die Pflichtangaben in E-Mails denen der Geschäftsbriefe des Unternehmens. Bei Nichtbeachtung besteht die Gefahr eines Zwangsgeldes oder einer kostenpflichtigen Abmahnung durch einen Mitbewerber. +
Informiere dich also über die rechtlichen Vorschriften zur Signatur in deinem Land und befrage bei Bedarf deinen Rechtsbeistand.
====

[#60]
=== Persönliche Einstellungen

Im Tab *Persönliche Einstellungen* nimmst du die Einstellungen vor, die nur für das im System angemeldete Benutzerkonto gelten. Deshalb ist das Tab für dich auch nur in deinem eigenen Benutzerkonto sichtbar. Das Tab unterteilt sich in 3 Tabs mit Einstellungen, die nur dich persönlich betreffen. Diese Tabs sind *Allgemein*, *Shortcuts* und *Favoriten*.

[#70]
==== Allgemein

Tabs werden durch eine rote Markierung gekennzeichnet, wenn du Änderungen vorgenommen, diese Änderungen jedoch noch nicht gespeichert hast.
Wenn du das Tab schließt, ohne die Änderungen gespeichert zu haben, wird ein Hinweisfenster angezeigt, das du aktiv bearbeiten musst, um fortzufahren.

* Klicke auf *Schließen*, um das Tab zu schließen, ohne die Änderungen zu speichern.
* Klicke auf *Abbrechen*, um die Änderungen zu speichern oder weitere Anpassungen vorzunehmen.

Wenn solche Warnhinweise für dein Benutzerkonto nicht mehr angezeigt werden sollen, deaktiviere die Funktion im Tab *Allgemein* deiner persönlichen Einstellungen.
Außerdem kannst du hier die benutzerspezifischen Einstellungen zurücksetzen.

[.instruction]
Allgemeine Einstellungen vornehmen:

. <<#20, Öffne dein eigenes Benutzerkonto>>.
. Öffne das Tab *Persönliche Einstellungen » Allgemein*.
. Nimm die Einstellungen vor. Beachte <<tabelle-allgemein>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[[tabelle-allgemein]]
.Allgemeine Einstellungen
[cols="1,3"]
|====
|Schaltfläche |Erläuterung

| *Meldungen zurücksetzen*
|Meldungen, z.B. die Meldung zum Neuladen von plentymarkets für Aktualisierungen, können durch einen Klick deaktiviert werden. Diese Einstellung wird benutzerabhängig gespeichert. Durch erneutes Klicken werden alle relevanten Einstellungen des Benutzerkontos zurückgesetzt, also alle deaktivierten Meldungen werden wieder angezeigt.

| *Alles zurücksetzen*
|Setzt alle benutzerabhängig gespeicherten Einstellungen zurück, z.B. die oben genannten Meldungen, Spaltengrößen und Spalteninhalte bei Tabellen, gewählte Favoriten etc.

| *Warnen, wenn Tabs offen sind und das Fenster geschlossen wird*
|Aktiviert = Beim Schließen eines Fensters wird eine Warnung ausgegeben, wenn noch Tabs geöffnet sind. +
Deaktiviert = Das Fenster wird ohne Warnung geschlossen.
|====

[#80]
==== Shortcuts

Du kannst Standard-Shortcuts hinterlegen, die du für verschiedene wiederkehrende Funktionen nutzt, z.B. das Öffnen von wichtigen Menüs in plentymarkets und das Wechseln zwischen Tabs und Tab-Ebenen. So wird zum Beispiel mit der Tastenkombination *Alt + I* die Artikelübersicht geöffnet. Mit *Alt + W* wird das Tab wieder geschlossen.

[IMPORTANT]
.Nicht alle Shortcut-Kombinationen sind möglich
====
Verwende keine systemspezifischen Shortcut-Kombinationen. Diese Shortcut-Kombinationen sind je nach Betriebssystem unterschiedlich. Beispiel: die *F*-Tasten. +
Die Kombination *cmd / Strg + W* ist nicht möglich, da die Shortcut-Kombination vom Browser reserviert ist.
====

[.instruction]
Shortcuts einrichten:

. <<#20, Öffne dein eigenes Benutzerkonto>>.
. Öffne das Tab *Persönliche Einstellungen » Shortcuts*.
. Lege die Shortcuts fest. Beachte <<tabelle-shortcuts>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[[tabelle-shortcuts]]
.Shortcuts
[cols="1,2"]
|====
|Shortcut |Erläuterung

2+^| *Globale Shortcuts*

| *Alt + W*
|Schließt das aktive Tab.

| *Shift + Alt + DOWN (Pfeiltaste nach unten)*
|Wechselt eine Tab-Ebene nach unten.

| *Shift + Alt + UP (Pfeiltaste nach oben)*
|Wechselt eine Tab-Ebene nach oben.

| *Shift + Alt + RIGHT (Pfeiltaste nach rechts)*
|Wechselt ein Tab nach rechts.

| *Shift + Alt + LEFT (Pfeiltaste nach links)*
|Wechselt ein Tab nach links.

| *Alt + R*
|Lädt das aktive Tab neu.

| *Alt + ESC*
|Loggt das Benutzerkonto aus und sperrt das Backend.

2+^| *Bereiche öffnen*

| *Alt + I*
|Öffnet das Menü *Artikel » Artikel bearbeiten*.

| *Alt + O*
|Öffnet das Menü *Aufträge » Aufträge bearbeiten*.

| *Alt + Y*
|Öffnet das Menü *Artikel » Kategorien*.

| *Alt + C*
|Öffnet das Menü *CRM » Kontakte*.

| *Alt + T*
|Öffnet das Menü *CRM » Ticketsystem*.

| *Alt + N*
|Öffnet den Bereich *Neuer Kontakt* im Menü *CRM » Kontakte*.

| *Alt + M*
|Öffnet das Menü *CRM » Schnellsuche*.

| *Alt + S*
|Öffnet den *Webshop*.

| *Alt + E*
|Öffnet den Webshop mit aktivierter Inline-Editing-Funktion.

2+^| *Auftrag bearbeiten*

| *Shift + Alt + N*
|Öffnet im Auftrag die Kundennotizen; in allen Tabs des Auftrags möglich.

| *Shift + Alt + A*
|Öffnet im Auftrag die Auftragsnotizen; in allen Tabs des Auftrags möglich.
|====

[NOTE]
.Standard-Shortcuts wiederherstellen
====
Änderungen werden über *Shortcuts zurücksetzen* wieder auf die Standardeinstellungen zurückgesetzt.
====

[#90]
==== Favoriten

Favoriten dienen dazu, häufig gebrauchte Menüpunkte schnell aufzurufen. Klicke auf icon:ellipsis-v[] oben rechts im plentymarkets Backend, um deine Favoriten anzuzeigen.

Im Tab *Favoriten* der persönlichen Einstellungen deines Benutzerkontos werden die Menüpfade angezeigt, die du als Favoriten angelegt hast. Die Favoriten können hier gelöscht oder mit den *Aufwärts*- und *Abwärts*-Pfeilen sortiert werden. Das Tab ist nur beim eigenen Benutzerkonto sichtbar.

[.instruction]
Menü zu Favoriten hinzufügen:

. Öffne das Menü, das du als Favorit hinzufügen möchtest.
. Klicke im Tab des Menüs auf icon:ellipsis-v[] und wähle icon:star-o[] *Link zu Favoriten hinzufügen*. +
→ *_Hinweis:_* Favoriten sind im Menü erst sichtbar, wenn du mindestens einen Favoriten gespeichert hast.

[.instruction]
Menü aus Favoriten entfernen:

. Klicke auf icon:ellipsis-v[] oben rechts im plentymarkets Backend. +
→ In der Liste werden deine gespeicherten Favoriten angezeigt. +
. Klicke neben dem Menüpfad auf *x*, um das Menü aus den Favoriten zu entfernen. +
→ icon:map-signs[] *_Oder:_* Klicke auf *Alle Favoriten löschen* und bestätige die Sicherheitsabfrage mit *Löschen*, um alle Favoriten zu löschen.

[#140]
== Mit Plugins weitere Menüpunkte hinzufügen

include::partial$backend-plugin-sets.adoc[]

Mehr über das Einrichten von Plugins und Plugin-Sets findest du im Themenbereich xref:plugins:plugins.adoc#[Plugins].

[#110]
== Dashboard personalisieren

Das Dashboard wird direkt angezeigt, wenn du dich im plentymarkets einloggst.
So siehst du hilfreiche Statistiken, Diagramme und Notizen auf einen Blick.

Admin-Nutzer können das Dashboard individuell gestalten.
Das heißt, sie können selbst entscheiden, welche Elemente, Statistiken und Notizen auf dem Dashboard angezeigt werden sollen.

[TIP]
.Praxisbeispiele
====
Du entscheidest selbst, welche Informationen auf dem Dashboard angezeigt werden sollen.
Zum Beispiel kannst du ein:

* xref:business-entscheidungen:myview-dashboard.adoc#700[Diagramm] hinzufügen, um die neuesten Statistiken und Kennzahlen für dein Unternehmen zu sehen.
* xref:willkommen:system-personalisieren.adoc#190[Aufgaben-Widget] hinzufügen, um den Überblick über deine laufenden Tasks zu behalten.
* xref:business-entscheidungen:myview-dashboard.adoc#1100[Forum-Ankündigungs-Widget] hinzufügen, um wichtige Nachrichten aus dem Forum zu sehen.
====

[#190]
== Praxisbeispiel: Aufgaben verfolgen

Mit Hilfe des Aufgaben-Widgets hast du die Arbeitsabläufe deines Unternehmens immer im Blick.
Du weist einzelnen Mitarbeitern Aufgaben zu und kannst dann den Fortschritt jeder Aufgabe verfolgen.
So behältst du immer den Überblick über laufende Projekte.

[TIP]
.Praxisbeispiel: Monatlicher Newsletter
====
Stell dir vor, dein Unternehmen verschickt einmal im Monat einen Newsletter, um Kunden über saisonale Angebote zu informieren.
Die Marketing-Abteilung ist für das Schreiben der Texte, die Erstellung der Grafiken und den Versand der E-Mail zuständig.

* Erstelle eine Newsletter-Aufgabe und weise sie deiner Marketing-Abteilung zu.
* Wenn ein Teilschritt erledigt ist, aktualisiert das Marketing-Team den Fortschritt.
* Da sich das Aufgaben-Widget auf dem Dashboard befindet, können alle Beteiligten den Fortschritt jederzeit verfolgen.
====

[#200]
[.collapseBox]
.*Nötige Benutzerrechte*
--

Benutzer:innen vom Typ *Backend* sehen nur bestimmte Bereiche und Menüs in plentymarkets. Somit können sie nur eingeschränkt im System arbeiten. Sollen Mitarbeiter:innen mit diesem Zugang das Menü *plentymarkets Logo (Start) » Aufgaben* sehen können, muss eine Person mit *Admin*-Zugang das im folgenden beschriebene Recht für Benutzer:innen vom Typ *Backend* vergeben.

[.instruction]
Sichtbarkeit für Backend-Benutzer:innen einstellen:

. Öffne das Menü *Einrichtung » Einstellungen » Benutzer » Rechte » Benutzer*.
. Nutze die Suchfunktion (icon:search[role="blue"]) und öffne das zu bearbeitende Konto.
. Klappe das Menü *Berechtigungen: Start* auf.
. Wähle die Einstellung *Aufgaben*.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

--

[#240]
=== Aufgaben-Widget zum Dashboard hinzufügen

Falls das Aufgaben-Widget noch nicht auf dem Dashboard vorhanden ist, muss es zunächst von einem Admin hinzugefügt werden.

[.instruction]
Widget hinzufügen:

. Öffne das Menü *plentymarkets Logo (Start) » Dashboard*.
. Klicke auf *Ansicht bearbeiten* (terra:design_inline_edit[]).
. Platziere das Element *Meine Aufgaben* per Drag-and-drop auf dem Dashboard.
. *Speichere* (terra:save[]) die Einstellungen.

Weitere Informationen zur xref:business-entscheidungen:myview-dashboard.adoc#400[Gestaltung des Dashboards].

[#210]
=== Neue Aufgabe erstellen

Stell dir vor, dein Unternehmen verschickt einmal im Monat einen Newsletter, um Kunden über saisonale Angebote zu informieren.
Du kannst eine Newsletter-Aufgabe erstellen und sie deiner Marketing-Abteilung zuweisen.

[.instruction]
Aufgabe erstellen:

. Öffne das Menü *plentymarkets Logo (Start) » Dashboard » Element: Meine Aufgaben*.
. Klicke auf *Neue Aufgabe* (icon:plus[role="darkGrey"]). +
→ Es öffnet sich ein Pop-up-Fenster.
. Gib Informationen zur Aufgabe ein. Siehe dazu die Tabelle.
. Klicke auf *Speichern*. +
→ Eine Aufgaben-ID wird automatisch vom System vergeben und kann nicht geändert werden.

[cols="1,3a"]
|===
|Einstellung |Erläuterung

| *Titel*
|Gib einen Titel für die Aufgabe ein, z.B. "Newsletter".

| *Beschreibung*
|Gib eine Beschreibung für die Aufgabe ein und formatiere den Text.
Du könntest zum Beispiel eine Liste der einzelnen Teilaufgaben schreiben, wie "Texte", "Grafiken" und "E-Mail-Versand".

| *Fortschritt*
|Bewege den Schieberegler, um den Fortschritt der Aufgabe in Prozent anzugeben.

*_Hinweis_*: Dies ist der Fortschritt der Aufgabe, wenn sie erstmals erstellt wird.
Während die Aufgabe voranschreitet, kann der Fortschritt aktualisiert werden.

| *Priorität*
|Wähle die Priorität der Aufgabe.
Die Prioritäten reichen von einem grauen Stern (niedrigste Priorität) bis zu zwei gelben Sternen (höchste Priorität).

| *Markierung*
|Wähle eine Markierung für die Aufgabe.
Die Markierung hilft dir, Aufgaben später wiederzufinden.

| *Eigner*
|Wer ist für diese Aufgabe verantwortlich?
Wähle den Eigner der Aufgabe, z.B. dein Marketing-Manager.
|===

[#230]
=== Eigene Aufgaben verfolgen und aktualisieren

Mit dem Aufgaben-Widget werden deine eigenen Aufgaben direkt auf dem Dashboard angezeigt, sobald du dich in plentymarkets einloggst.
Hier kannst du deine Aufgaben jederzeit weiter bearbeiten.
Zum Beispiel kannst du den Fortschritt aktualisieren oder die Beschreibung ergänzen.

[.instruction]
Aufgabe aktualisieren:

. Öffne das Menü *plentymarkets Logo (Start) » Dashboard » Element: Meine Aufgaben*. +
→ Deine unerledigten Aufgaben werden standardmäßig angezeigt.
. Klicke auf icon:ellipsis-v[role="darkGrey"] und entscheide, wie die Aufgabe geändert werden soll.
* icon:pencil[role="darkGrey"] *Aufgabe aktualisieren* = Es öffnet sich das Pop-up-Fenster, das du beim Erstellen der Aufgabe bereits gesehen hast.
Hier kannst du die Aufgabe weiter bearbeiten.
* material:delete[role="darkGrey"] *Löschen* = Du musst deine Entscheidung, die Aufgabe zu löschen, bestätigen.
* material:task_alt[role="darkGrey"] *Aufgabe als erledigt markieren* = Der Fortschritt wird auf 100% gesetzt und die Aufgabe wird in den Bereich *Erledigt* verschoben.
* material:task_alt[role="darkGrey"] *Aufgabe als unerledigt markieren* = Diese Option ist nur für erledigte Aufgaben sichtbar.
Der Fortschritt wird auf 0% gesetzt und die Aufgabe wird in den Bereich *Unerledigt* verschoben.

[#220]
=== Firmenweite Aufgaben verfolgen und aktualisieren

Es ist nicht nur möglich, deine eigenen Aufgaben zu verwalten, sondern auch die Aufgaben deiner Mitarbeiter im Blick zu behalten.

[.instruction]
Firmenweite Aufgaben verfolgen:

. Öffne das Menü *plentymarkets Logo (Start) » Aufgaben*. +
→ Deine unerledigten Aufgaben werden standardmäßig angezeigt.
. Klicke auf *Zurücksetzen* (icon:undo[role="orange"]) und wähle die benötigten Filter.
Siehe dazu die Tabelle.
. Klicke auf *Suchen* (icon:search[role="blue"]). +
→ Die Aufgaben, die den eingestellten Suchkriterien entsprechen, werden angezeigt.

[cols="1,3a"]
|===
|Filter |Erläuterung

| *Titel/Beschreibung*
|Filtert nach den Aufgaben, die ein bestimmtes Stichwort in ihrem Titel oder in ihrer Beschreibung haben.
Gib dazu das Stichwort in das Textfeld ein.

*_Hinweis_*: Gib mindestens 4 Zeichen ein.
Dieser Filter ist eine Volltextsuche.

| *ID*
|Filtert nach der Aufgabe mit einer bestimmten ID.
Gib dazu die ID in das Textfeld ein.

*_Hinweis_*: Die Aufgaben-IDs werden automatisch vom System vergeben und sind fortlaufend.
Die ID kann nicht geändert werden.

| *Ticket-ID*
|Filtert nach den Aufgaben, die zu einem bestimmten Ticket gehören.
Gib dazu die Ticket-ID ein.
xref:crm:ticketsystem-nutzen.adoc#4000[Weitere Informationen].

| *Fortschritt*
|Filtert nach den Aufgaben, die einen bestimmten Fortschritt haben.
Wähle dazu einen Operator und den Fortschritt aus den Dropdown-Listen.

| *Priorität*
|Filtert nach den Aufgaben, die eine bestimmte Priorität haben.
Wähle dazu einen Operator und die Priorität aus den Dropdown-Listen.

| *Datum der Erstellung*
|Filtert nach den Aufgaben, die zu einem bestimmten Zeitpunkt erstellt wurden.
Wähle dazu einen Operator aus der Dropdown-Liste und ein Datum aus dem Kalender (icon:calendar[]).

| *Markierung*
|Filtert nach den Aufgaben, die eine bestimmte Markierung haben.
Wähle dazu die Markierung aus der Dropdown-Liste.

| *Eigner*
|Filtert nach den Aufgaben, die einer bestimmten Person zugewiesen sind.
Wähle dazu den Eigner aus der Dropdown-Liste.
|===

[#245]
=== Aufgaben im Ticketsystem erstellen

Neben dem Widget können Aufgaben auch im xref:crm:ticketsystem-nutzen.adoc#4000[Ticketsystem] erstellt werden.
So kannst du zum Beispiel direkt die Aufgaben erstellen, die sich aus einer telefonischen Anfrage ergeben.

[.instruction]
Aufgabe im Ticketsystem erstellen:

. Öffne das Menü *CRM » Ticketsystem » [Ticket öffnen] » Tab: Aufgaben*.
. Klicke auf icon:plus[role="green"] *Neue Aufgabe*.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen im Kapitel xref:willkommen:system-personalisieren.adoc#210[Neue Aufgabe erstellen].
. *Speichere* (terra:save[role="green"]) die Einstellungen. +
→ Die Aufgabe ist mit dem Ticket verknüpft.
Diese Verknüpfung wird auch in der Übersicht im Menü *plentymarkets Logo (Start) » Aufgaben* angezeigt.

[#150]
== Tabellenspalten konfigurieren

In einigen Menüs ist die Übersicht anpassbar.
Das heißt, du kannst selbst entscheiden:

* welche Spalten angezeigt werden sollen.
* in welcher Reihenfolge die Spalten dargestellt werden sollen.
* ob die Ergebnisse in aufsteigender oder absteigender Reihenfolge dargestellt werden sollen.

include::artikel:page$artikelsuche.adoc[tag=configure-columns-overview]

[#183]
== Vollbildmodus aktivieren

Wenn du mehr Platz auf deinem Bildschirm für die Ansichten im Backend freigeben möchtest, kannst du den Vollbildmodus verwenden. Im Vollbildmodus wird die Menüleiste ausgeblendet. Du kannst die Menüleiste dynamisch im Vollbildmodus einblenden, indem du den Mauszeiger an die obere Kante deines Browsertabs bewegst.

Um den Vollbildmodus zu aktivieren bzw. zu deaktivieren, klicke auf icon:ellipsis-v[] oben rechts im plentymarkets Backend und klicke auf *Vollbildmodus an* material:fullscreen[] bzw. *Vollbildmodus aus* material:fullscreen-exit[].

[#185]
== Dark oder Light Theme wählen

Du kannst das Design deines Backends mit verschiedenen Themes und Optionen anpassen. Dabei kannst du folgende Elemente ändern:

* Farbe der Menüleiste
* Größe von verschiedenen Elementen
* Einfärbung von Schaltflächen

Um das Design deines Backends anzupassen, gehe wie folgt vor:

[.instruction]
Design anpassen:

. Zeige mit der Maus auf das Kontosymbol (icon:user-circle[]).
. Klicke auf *Themes*. +
→ Das Fenster *Themes* wird geöffnet.
. Wähle das gewünschte Design.

[#180]
== Bestimmte Editoren verbieten

In einigen Menüs sehen Nutzer eine Dropdown-Liste, aus der sie ihren bevorzugten Editor wählen können.
Standardmäßig stehen die Editoren *Editor*, *Syntax-Editor* und *Textfeld* zur Auswahl.
Bei Bedarf kannst du einzelne Editoren deaktivieren, z.B. wenn du deine Mitarbeiter zwingen willst, nur den Syntax-Editor zu benutzen.

[.instruction]
Editoren deaktivieren:

. Öffne das Menü *Einrichtung » Einstellungen » Editoren*. +
→ Das Tab *Bereiche* öffnet sich.
. Entferne das Häkchen neben den Editoren, die in der Dropdown-Liste des Bereichs nicht angezeigt werden sollen.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[discrete]
=== CSS des Editors einstellen

In der Standardeinstellung wird für den Editor das *CSSContent* verwendet. Wenn dort z.B. ein Hintergrundbild verwendet wird und dieses bei der Bearbeitung im Editor stört, kannst du das CSS im Menü *Einrichtung » Einstellungen » Editoren » Tab: CSS*  anpassen. Alternativ steht mit dem *Standard*-CSS ein weißer Hintergrund zur Verfügung. Du hast auch die Möglichkeit, ein *benutzerdefiniertes* CSS zu erstellen, in dem du die Formatierung weiterer Inhalte, z.B. Schriften, individuell festlegst.

Um das CSS für den Editor einzustellen, öffne das Menü *Einrichtung » Einstellungen » Editoren » Tab: CSS*.

[.instruction]
CSS für den Editor einstellen:

. Öffne das Menü *Einrichtung » Einstellungen » Editoren*.
. Wechsele in das Tab *CSS*.
. Wähle das gewünschte CSS. Beachte dazu die Erläuterungen in <<tabelle-css-editoren>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[[tabelle-css-editoren]]
.Verfügbare CSS
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Wie im Webshop (CSSContent)*
|Das Webshop-CSS wird in den Editor geladen.

| *Standard*
|Ein einfaches Standard-CSS wird in den Editor geladen. Die Hintergrundfarbe ist weiß.

| *Benutzerdefiniert*
|Das einfache Standard-CSS wird in einem Bearbeitungsfenster angezeigt und kann mit dem Syntax-Editor angepasst werden. +
*_Hinweis:_* Mit einem Klick auf *Zurücksetzen* wird das CSS wieder auf das Standard-CSS zurückgesetzt.
|====

[#250]
== Kalender-Funktion

Der Kalender im Menü *plentymarkets Logo (Start) » Kalender* deines plentymarkets Systems bietet dir die Möglichkeit, Termine zu planen, um deine zeitliche Organisation und die deiner Mitarbeiter:innen zu steuern und interne Abläufe zu verbessern.

Der Kalender enthält die eigenen Termine sowie die Termine der Mitarbeiter:innen, deren Kalender für die aktuell angemeldete Personen sichtbar gestellt und im *Filter* aktiviert wurden.

Du kannst zwischen der Anzeige des Tages, der Woche und des Monats wählen. Durch Klick auf die Schaltfläche *Heute* wechselst du zurück zur Ansicht des aktuellen Tages.

Im Filter wird eine Liste der Benutzer:innen angezeigt, für die die aktuell angemeldete Person mindestens Leserechte hat. Durch Setzen eines Häkchens werden die Termine dieses Benutzers im Kalender angezeigt. Du kannst die Kalender mehrerer Benutzer:innen gleichzeitig anzeigen.

[discrete]
[#260]
=== Benutzerrechte für Backend-Benutzer:innen vergeben

Benutzer:innen vom Typ *Backend* sehen nur bestimmte Bereiche und Menüs in plentymarkets. Somit können sie nur eingeschränkt im System arbeiten. Sollen Mitarbeiter:innen mit diesem Zugang das Menü *plentymarkets Logo (Start) » Kalender* sehen können, muss eine Person mit *Admin*-Zugang das im folgenden beschriebene Recht für Benutzer:innen vom Typ *Backend* vergeben.

[.instruction]
Sichtbarkeit für Backend-Benutzer:innen einstellen:

. Öffne das Menü *Einrichtung » Einstellungen » Benutzer » Rechte » Benutzer*.
. Nutze die Suchfunktion (icon:search[role="blue"]) und öffne das zu bearbeitende Konto.
. Klappe das Menü *Berechtigungen: Start* auf.
. Wähle die Einstellung *Kalender*.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[discrete]
[#270]
=== Backend-Benutzer:innen als Eigner einstellen

Für Personen mit dem Zugang *Backend* muss die Kalendernutzung wie im Folgenden beschrieben aktiviert werden. Für Personen mit dem Zugang *REST-API* ist keine Aktivierung des Kalenders möglich.

Die Berechtigung kann im Tab *Eigner* eines Benutzerkontos jederzeit wieder deaktiviert werden.

[.instruction]
Backend-Benutzer:innen als Eigner einstellen:

. Öffne das Menü *Einrichtung » Einstellungen » Benutzer » Konten*.
. Öffne das zu bearbeitende Konto mit dem Zugang *Backend*.
. Wechsele in das Tab *Eigner*.
. Aktiviere die Option *Kalender*.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Das neue Tab *Kalender* ist sichtbar und kann wie im nächsten Kapitel beschrieben eingerichtet werden.

[discrete]
[#280]
=== Grundeinstellungen im Kalender vornehmen und Zugriffsrechte für Benutzer:innen einstellen

Gehe wie im Folgenden beschrieben vor, um Grundeinstellungen im Kalender wie z.B. die Vergabe des Passwort vorzunehmen und die Zugriffsrechte für Benutzer:innen einzustellen. Du kannst zwischen den Einstellungen *Kein Zugriff*, *Lesen* und *Lesen & Schreiben* wählen.

[.instruction]
Grundeinstellungen im Kalender vornehmen und Zugriffsrechte für Benutzer:innen einstellen:

. Öffne das Menü *Einrichtung » Einstellungen » Benutzer » Konten*.
. Öffne das zu bearbeitende Konto.
. Öffne das Tab *Kalender*.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<#table-calendar-basic-settings>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[[table-calendar-basic-settings]]
.Grundeinstellungen im Kalender vornehmen
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Serveradresse*; +
*Serverpfad*; +
*Port*
|Wird automatisch vom System gespeichert. +
Die Server-Adresse und der Server-Pfad sind für die Konfiguration eines <<#320, externen Kalender-Tools>> (z.B. Google Calendar) erforderlich.

| *Neues Passwort*
|Beim Einrichten des Kalender-Accounts wird ein Passwort benötigt, das von <<#320, externen Kalender-Tools>> abgefragt wird. Das Passwort kann jederzeit geändert werden. +
*_Wichtig:_* Das Passwort wird nach dem Speichern nicht mehr angezeigt und kann nicht wiederhergestellt werden. +
Bei Verwendung externer Kalender-Tools muss bei einer Änderung des Passworts dort das Passwort ggf. erneut eingegeben werden.

| *Passwort wiederholen*
|Zuvor eingegebenes neues Passwort durch erneute Eingabe bestätigen.

| *Beschreibung*
|Die Beschreibung wird bei den Informationen bzw. Einstellungen des Kalenders angezeigt.

| *Berechtigung*
|Wähle, welche Personen Zugriff auf den Kalender dieses Eigners haben sollen und welche Zugriffsrechte diese Personen haben sollen. Um den Kalender sehen zu können, müssen diese Personen mindestens Leserechte haben. +
*Kein Zugriff* = Die Person hat weder Lese- noch Schreibzugriff auf den Kalender dieses Eigners. +
*Lesen* = Der Kalender ist für die Person sichtbar. +
*Schreiben* = Die Person darf Termine im Kalender bearbeiten und löschen.
|====

[discrete]
[#290]
=== Termin erstellen

Gehe wie im Folgenden beschrieben vor, um einen Termin zu erstellen. Abhängig von deinen Zugriffsrechten, die gemäß <<#table-calendar-basic-settings>> eingestellt werden, kannst du auch Termine für andere Benutzer:innen erstellen. Du kannst nur Termine für Benutzer:innen erstellen, für die du Schreibrechte hast. Benutzer:innen, für die du nicht über Schreibrechte verfügst, stehen beim Erstellen eines Termins nicht zur Auswahl.

[.instruction]
Termin erstellen:

. Öffne das Menü *plentymarkets Logo (Start) » Kalender*. +
→ *_Tipp:_* Zeige dazu mit der Maus auf das plentymarkets Logo oben links.
. Wähle den Zeitpunkt des Termins mit einem Klick in das Feld bei der Uhrzeit. +
→ *_Tipp:_* Wähle den Zeitraum des Termins mit einem Klick in das Feld der Startzeit und ziehe den Cursor bis zur Endzeit des Termins.
. Nimm die Einstellungen im Bereich *Termininformationen* vor. Beachte dazu die Erläuterungen in <<#table-create-appointment>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[[table-create-appointment]]
.Termin erstellen
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Titel*
|Wird in der Kalenderübersicht angezeigt.

| *Ganztägig*
|Legt fest, dass der Termin den ganzen Tag dauert. Termine werden dann in der Tages- und Wochenansicht in der oberen Leiste angezeigt und der Kalender bleibt übersichtlich.

| *Von / Bis*
|Datum und Uhrzeit sind voreingestellt, können jedoch angepasst werden.

| *Typ*
|Art des Termins aus der Dropdown-Liste wählen.

| *Kalender*
|Wählen, für welchen Eigner der Termin angelegt werden soll.

| *Beschreibung*
|Beschreibung eingeben, z.B. Details zum Termin. Diese Beschreibung wird auch anderen Benutzer:innen mit Zugriffsrechten auf den Kalender in den Termininformationen angezeigt.
|====

[discrete]
[#300]
=== Termin bearbeiten

Klicke auf einen Termin, um die Termininformationen zu öffnen und diese zu ändern.

[.instruction]
Termin bearbeiten:

. Öffne das Menü *plentymarkets Logo (Start) » Kalender*.
. Klicke auf den Termin, den du ändern möchtest. +
→ Das Fenster *Termininformationen* wird geöffnet.
. Nimm die Änderungen vor. Beachte dazu die Erläuterungen in <<#table-create-appointment>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[discrete]
[#310]
=== Termin löschen

Lösche Termine, wenn diese fälschlicherweise erstellt wurden oder die Termine hinfällig geworden sind.

[.instruction]
Termin löschen:

. Öffne das Menü *plentymarkets Logo (Start) » Kalender*.
. Klicke auf den Termin, den du löschen möchtest. +
→ Das Fenster *Termininformationen* wird geöffnet.
. Klicke auf *Löschen* (icon:minus-square[role="red"]). +
→ Der Termin wird gelöscht und aus der Kalenderübersicht entfernt.

[discrete]
[#320]
=== Kalender mit externen Kalender-Tools synchronisieren

Über eine link:https://de.wikipedia.org/wiki/CalDAV[CalDAV^]-Schnittstelle synchronisierst du deinen Kalender mit externen Kalender-Tools. Du kannst den Kalender z.B. mit dem Mac-Kalender oder iPad-Kalender synchronisieren.

Im Benutzerkonto des Teammitglieds muss dazu wie im Kapitel <<#270, Backend-Benutzer:innen als Eigner einstellen>> beschrieben im Tab *Eigner* die Option *Kalender* aktiviert sein. Du benötigst außerdem die Einstellungen, die im Tab *Kalender* des Benutzerkontos gespeichert sind.

Informationen darüber, wie du deinen plentymarkets Kalender mit externen Kalender-Tools synchronisierst, findest du in der Dokumentation des externen Kalender-Tools.
