= Dein System personalisieren
:keywords: Benutzerkonto, Benutzerbild, Gravatar, Grußformel, Signatur, SignatureHTML, Persönliche Einstellungen, Menüansicht, Ansicht einrichten, Shortcut, Tastenkürzel, Tastenkombination, Startseite, Favorit, CSS-Editor, Aufgaben
:description: Bist du neu bei plentymarkets? Dann empfiehlt es sich, zunächst dein Benutzerkonto und System individuell anzupassen.
:author: denise-breidenbach

Diese Handbuchseite beschreibt die Einstellungen, mit denen du dein Benutzerkonto und auch weitere Bereiche deines plentymarkets Systems individuell anpassen kannst.

[#10]
== Dein eigenes Benutzerkonto anpassen

[#20]
=== Benutzerkonto öffnen

Es gibt zwei Möglichkeiten, auf dein eigenes Benutzerkonto zuzugreifen.

* Bewege den Mauszeiger über das Benutzersymbol oben rechts (material:account_circle[]) und klicke dann auf deinen Namen.
* Öffne das Menü *Einrichtung » Kontoverwaltung » Konten*. Klicke dann *Suchen* (material:search[]) und wähle dein Konto aus.

[#30]
=== Benutzerbild hinzufügen

Um ein Benutzerbild statt der leeren Benutzer-Schaltfläche (icon:user-circle[]) in deinem plentymarkets Backend anzeigen zu lassen, musst du bei link:https://de.gravatar.com/[gravatar.com^] angemeldet sein.

[.instruction]
Benutzerbild hinzufügen:

. <<#20, Öffne dein eigenes Benutzerkonto>>. +
→ Das Benutzer:innen-Konto öffnet sich.
. Gib im Feld *E-Mail* die E-Mail-Adresse, mit der du bei gravatar.com angemeldet bist, ein.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Lade das System neu, um das Benutzerbild zu sehen.

[#50]
=== Signatur

Im Bereich *Signatur* gibst du einen Text ein, der deinen Nachrichten und Kommentaren im Ticketsystem automatisch als Signatur angefügt wird. Diese besteht in der Regel aus deinen Kontaktdaten sowie Angaben zum Amtsgericht und Handelsregisternummer. Je nach Rechtsform des Unternehmens gehört die Angabe von Firmennamen, Namen von Geschäftsführer:innen sowie ggf. der USt-IdNr. zu den Pflichtangaben.
Beim Versenden von E-Mails aus dem Ticketsystem wird die Signatur automatisch angehängt.

[TIP]
.Template-Variable für die Signatur
====
Die Template-Variablen *$Signature* und *$SignatureHTML* beinhalten die Grußformel.
====

[.instruction]
Signatur einrichten:

. <<#20, Öffne dein eigenes Benutzerkonto>>.
. Öffne den Bereich *Signatur*.
. Gib deine Signatur ein.
. *Speichere* (material:save[]) die Einstellungen.

[WARNING]
.Pflichtangaben in E-Mails
====
In Deutschland entsprechen seit Anfang 2007 die Pflichtangaben in E-Mails denen der Geschäftsbriefe des Unternehmens. Bei Nichtbeachtung besteht die Gefahr eines Zwangsgeldes oder einer kostenpflichtigen Abmahnung durch einen Mitbewerber. +
Informiere dich also über die rechtlichen Vorschriften zur Signatur in deinem Land und befrage bei Bedarf deinen Rechtsbeistand.
====

[#60]
=== Persönliche Einstellungen

Die *Persönliche Einstellungen* findest du unter dem plentymarkets Logo oben links oder unter deinem Profilbild oben rechts. Hier nimmst du die Einstellungen vor, die nur für das im System angemeldete Benutzerkonto gelten. Die *Persönlichen Einstellungen* unterteilen sich   in 2 Tabs mit Einstellungen, die nur dich persönlich betreffen. Diese Tabs sind *Allgemein* und *Shortcuts*.

[#70]
==== Allgemein

Im Tab *Allgemein* kannst du benutzerspezifische Einstellungen zurückssetzen. Beachte für mehr Informationen <<#tabelle-allgemein>>.

[.instruction]
Allgemeine Einstellungen vornehmen:

. Gehe mit dem Mauszeiger auf das plentymarkets Logo oben links. +
→ Ein Dropwdown-Menü klappt aus.
. Klicke auf *Persönliche Einstellungen*. +
→ Die Persönlichen Einstellungen öffnen sich im Tab *Shortcuts*.
. Wechsel in das Tab *Allgemein*.
. Nimm die Einstellungen vor. Beachte <<#tabelle-allgemein>>.
. *Speichere* (material:save[]) die Einstellungen.

[[tabelle-allgemein]]
.Allgemeine Einstellungen
[cols="1,3"]
|====
|Schaltfläche |Erläuterung

| *Meldungen zurücksetzen*
|Meldungen, z.B. die Meldung zum Neuladen von plentymarkets für Aktualisierungen, können durch einen Klick deaktiviert werden. Diese Einstellung wird benutzerabhängig gespeichert. Durch erneutes Klicken werden alle relevanten Einstellungen des Benutzer:innen-Kontos zurückgesetzt, also alle deaktivierten Meldungen werden wieder angezeigt.

| *Alles zurücksetzen*
|Setzt alle benutzerabhängig gespeicherten Einstellungen zurück, z.B. die oben genannten Meldungen, Spaltengrößen und Spalteninhalte bei Tabellen, gewählte Favoriten etc.

| *Warnen, wenn Tabs offen sind und das Fenster geschlossen wird*
|Aktiviert = Beim Schließen eines Fensters wird eine Warnung ausgegeben, wenn noch Tabs geöffnet sind. +
Deaktiviert = Das Fenster wird ohne Warnung geschlossen.
|====

[#80]
==== Shortcuts

Du kannst Standard-Shortcuts hinterlegen, die du für verschiedene wiederkehrende Funktionen nutzt, z.B. das Öffnen von wichtigen Menüs in plentymarkets und das Wechseln zwischen Tabs und Tab-Ebenen. So wird zum Beispiel mit der Tastenkombination *Alt + I* die Artikelübersicht geöffnet. Mit *Alt + W* wird das Tab wieder geschlossen.

[IMPORTANT]
.Nicht alle Shortcut-Kombinationen sind möglich
====
Verwende keine systemspezifischen Shortcut-Kombinationen. Diese Shortcut-Kombinationen sind je nach Betriebssystem unterschiedlich. Beispiel: die *F*-Tasten. +
Die Kombination *cmd / Strg + W* ist nicht möglich, da die Shortcut-Kombination vom Browser reserviert ist.
====

[.instruction]
Shortcuts einrichten:

. Gehe mit dem Mauszeiger auf das plentymarkets Logo oben links. +
→ Ein Dropwdown-Menü klappt aus.
. Klicke auf *Persönliche Einstellungen*. +
→ Die Persönlichen Einstellungen öffnen sich im Tab *Shortcuts*.
. Nimm die Einstellungen vor. Beachte <<#tabelle-shortcuts>>.
. *Speichere* (material:save[]) die Einstellungen.

[[tabelle-shortcuts]]
.Shortcuts
[cols="1,2"]
|====
|Shortcut |Erläuterung

2+^| *Globale Shortcuts*

| *Alt + W*
|Schließt das aktive Tab.

| *Shift + Alt + DOWN (Pfeiltaste nach unten)*
|Wechselt eine Tab-Ebene nach unten.

| *Shift + Alt + UP (Pfeiltaste nach oben)*
|Wechselt eine Tab-Ebene nach oben.

| *Shift + Alt + RIGHT (Pfeiltaste nach rechts)*
|Wechselt ein Tab nach rechts.

| *Shift + Alt + LEFT (Pfeiltaste nach links)*
|Wechselt ein Tab nach links.

| *Alt + R*
|Lädt das aktive Tab neu.

| *Alt + ESC*
|Loggt das Benutzerkonto aus und sperrt das Backend.

2+^| *Bereiche öffnen*

| *Alt + I*
|Öffnet das Menü *Artikel » Artikel bearbeiten*.

| *Alt + O*
|Öffnet das Menü *Aufträge » Aufträge bearbeiten*.

| *Alt + Y*
|Öffnet das Menü *Artikel » Kategorien*.

| *Alt + C*
|Öffnet das Menü *CRM » Kontakte*.

| *Alt + T*
|Öffnet das Menü *CRM » Ticketsystem*.

| *Alt + N*
|Öffnet den Bereich *Neuer Kontakt* im Menü *CRM » Kontakte*.

// | *Alt + M*
// |Öffnet das Menü *CRM » Schnellsuche*.

| *Alt + S*
|Öffnet den *Webshop*.

| *Alt + E*
|Öffnet den Webshop mit aktivierter Inline-Editing-Funktion.

2+^| *Auftrag bearbeiten*

| *Shift + Alt + N*
|Öffnet im Auftrag die Kundennotizen; in allen Tabs des Auftrags möglich.

| *Shift + Alt + A*
|Öffnet im Auftrag die Auftragsnotizen; in allen Tabs des Auftrags möglich.
|====

[NOTE]
.Standard-Shortcuts wiederherstellen
====
Änderungen werden über *Shortcuts zurücksetzen* wieder auf die Standardeinstellungen zurückgesetzt.
====

[#90]
==== Favoriten

Favoriten dienen dazu, häufig gebrauchte Menüpunkte schnell aufzurufen. Klicke auf icon:ellipsis-v[] oben rechts im plentymarkets Backend, um deine Favoriten anzuzeigen.

Im Tab *Favoriten* der persönlichen Einstellungen deines Benutzerkontos werden die Menüpfade angezeigt, die du als Favoriten angelegt hast. Die Favoriten können hier gelöscht oder mit den *Aufwärts*- und *Abwärts*-Pfeilen sortiert werden. Das Tab ist nur beim eigenen Benutzerkonto sichtbar.

[.instruction]
Menü zu Favoriten hinzufügen:

. Öffne das Menü, das du als Favorit hinzufügen möchtest.
. Klicke im Tab des Menüs auf icon:ellipsis-v[] und wähle icon:star-o[] *Link zu Favoriten hinzufügen*. +
→ *_Hinweis:_* Favoriten sind im Menü erst sichtbar, wenn du mindestens einen Favoriten gespeichert hast.

[.instruction]
Menü aus Favoriten entfernen:

. Klicke auf icon:ellipsis-v[] oben rechts im plentymarkets Backend. +
→ In der Liste werden deine gespeicherten Favoriten angezeigt. +
. Klicke neben dem Menüpfad auf *x*, um das Menü aus den Favoriten zu entfernen. +
→ icon:map-signs[] *_Oder:_* Klicke auf *Alle Favoriten löschen* und bestätige die Sicherheitsabfrage mit *Löschen*, um alle Favoriten zu löschen.

[#140]
== Mit Plugins weitere Menüpunkte hinzufügen

include::partial$backend-plugin-sets.adoc[]

Mehr über das Einrichten von Plugins und Plugin-Sets findest du im Themenbereich xref:plugins:plugins.adoc#[Plugins].

[#110]
== Dashboard personalisieren

Das Dashboard wird direkt angezeigt, wenn du dich im plentymarkets einloggst.
So siehst du hilfreiche Statistiken, Diagramme und Notizen auf einen Blick.

Admin-Nutzer können das Dashboard individuell gestalten.
Das heißt, sie können selbst entscheiden, welche Elemente, Statistiken und Notizen auf dem Dashboard angezeigt werden sollen.

[TIP]
.Praxisbeispiele
====
Du entscheidest selbst, welche Informationen auf dem Dashboard angezeigt werden sollen.
Zum Beispiel kannst du ein:

* xref:business-entscheidungen:myview-dashboard.adoc#700[Diagramm] hinzufügen, um die neuesten Statistiken und Kennzahlen für dein Unternehmen zu sehen.
* xref:willkommen:system-personalisieren.adoc#190[Aufgaben-Widget] hinzufügen, um den Überblick über deine laufenden Tasks zu behalten.
* xref:business-entscheidungen:myview-dashboard.adoc#1100[Forum-Ankündigungs-Widget] hinzufügen, um wichtige Nachrichten aus dem Forum zu sehen.
====

[#190]
== Praxisbeispiel: Aufgaben verfolgen

Mit Hilfe des Aufgaben-Widgets hast du die Arbeitsabläufe deines Unternehmens immer im Blick.
Du weist einzelnen Mitarbeitern Aufgaben zu und kannst dann den Fortschritt jeder Aufgabe verfolgen.
So behältst du immer den Überblick über laufende Projekte.

[TIP]
.Praxisbeispiel: Monatlicher Newsletter
====
Stell dir vor, dein Unternehmen verschickt einmal im Monat einen Newsletter, um Kunden über saisonale Angebote zu informieren.
Die Marketing-Abteilung ist für das Schreiben der Texte, die Erstellung der Grafiken und den Versand der E-Mail zuständig.

* Erstelle eine Newsletter-Aufgabe und weise sie deiner Marketing-Abteilung zu.
* Wenn ein Teilschritt erledigt ist, aktualisiert das Marketing-Team den Fortschritt.
* Da sich das Aufgaben-Widget auf dem Dashboard befindet, können alle Beteiligten den Fortschritt jederzeit verfolgen.
====

[#200]
[.collapseBox]
.*Nötige Rolle*
--

Benutzer:innen ohne *Administrator*-Zugang sehen nur bestimmte Bereiche und Menüs in plentymarkets. Somit können sie nur eingeschränkt im System arbeiten. Sollen Mitarbeiter:innen das Menü *plentymarkets Logo (Start) » Aufgaben* sehen können, muss eine Person mit *Administrator*-Zugang die passende Rolle an Benutzer:innen-Konten vergeben.

[.instruction]
Sichtbarkeit für Backend-Benutzer:innen einstellen:

. Öffne das Menü *Einrichtung » Kontoverwaltung » Konten*.
. Nutze die Suchfunktion (material:search[]) und öffne das zu bearbeitende Konto.
. Weise dem Konto die passende Rolle unter *zugewiesene Rollen* zu. +
→ Oder: erstelle vorher eine Rolle mit den *Aufträge* Sichtbarkeiten im Einfachen Modus.
. *Speichere* (material:save[]) die Einstellungen.

--

[#240]
=== Aufgaben-Widget zum Dashboard hinzufügen

Falls das Aufgaben-Widget noch nicht auf dem Dashboard vorhanden ist, muss es zunächst von einem Admin hinzugefügt werden.

[.instruction]
Widget hinzufügen:

. Öffne das Menü *plentymarkets Logo (Start) » Dashboard*.
. Klicke auf *Ansicht bearbeiten* (terra:design_inline_edit[]).
. Platziere das Element *Meine Aufgaben* per Drag-and-drop auf dem Dashboard.
. *Speichere* (terra:save[]) die Einstellungen.

Weitere Informationen zur xref:business-entscheidungen:myview-dashboard.adoc#400[Gestaltung des Dashboards].

[#210]
=== Neue Aufgabe erstellen

Stell dir vor, dein Unternehmen verschickt einmal im Monat einen Newsletter, um Kunden über saisonale Angebote zu informieren.
Du kannst eine Newsletter-Aufgabe erstellen und sie deiner Marketing-Abteilung zuweisen.

[.instruction]
Aufgabe erstellen:

. Öffne das Menü *plentymarkets Logo (Start) » Dashboard » Element: Meine Aufgaben*.
. Klicke auf *Neue Aufgabe* (icon:plus[role="darkGrey"]). +
→ Es öffnet sich ein Pop-up-Fenster.
. Gib Informationen zur Aufgabe ein. Siehe dazu die Tabelle.
. Klicke auf *Speichern*. +
→ Eine Aufgaben-ID wird automatisch vom System vergeben und kann nicht geändert werden.

[cols="1,3a"]
|===
|Einstellung |Erläuterung

| *Titel*
|Gib einen Titel für die Aufgabe ein, z.B. "Newsletter".

| *Beschreibung*
|Gib eine Beschreibung für die Aufgabe ein und formatiere den Text.
Du könntest zum Beispiel eine Liste der einzelnen Teilaufgaben schreiben, wie "Texte", "Grafiken" und "E-Mail-Versand".

| *Fortschritt*
|Bewege den Schieberegler, um den Fortschritt der Aufgabe in Prozent anzugeben.

*_Hinweis_*: Dies ist der Fortschritt der Aufgabe, wenn sie erstmals erstellt wird.
Während die Aufgabe voranschreitet, kann der Fortschritt aktualisiert werden.

| *Priorität*
|Wähle die Priorität der Aufgabe.
Die Prioritäten reichen von einem grauen Stern (niedrigste Priorität) bis zu zwei gelben Sternen (höchste Priorität).

| *Markierung*
|Wähle eine Markierung für die Aufgabe.
Die Markierung hilft dir, Aufgaben später wiederzufinden.

| *Eigner*
|Wer ist für diese Aufgabe verantwortlich?
Wähle den Eigner der Aufgabe, z.B. dein Marketing-Manager.
|===

[#230]
=== Eigene Aufgaben verfolgen und aktualisieren

Mit dem Aufgaben-Widget werden deine eigenen Aufgaben direkt auf dem Dashboard angezeigt, sobald du dich in plentymarkets einloggst.
Hier kannst du deine Aufgaben jederzeit weiter bearbeiten.
Zum Beispiel kannst du den Fortschritt aktualisieren oder die Beschreibung ergänzen.

[.instruction]
Aufgabe aktualisieren:

. Öffne das Menü *plentymarkets Logo (Start) » Dashboard » Element: Meine Aufgaben*. +
→ Deine unerledigten Aufgaben werden standardmäßig angezeigt.
. Klicke auf icon:ellipsis-v[role="darkGrey"] und entscheide, wie die Aufgabe geändert werden soll.
* icon:pencil[role="darkGrey"] *Aufgabe aktualisieren* = Es öffnet sich das Pop-up-Fenster, das du beim Erstellen der Aufgabe bereits gesehen hast.
Hier kannst du die Aufgabe weiter bearbeiten.
* material:delete[role="darkGrey"] *Löschen* = Du musst deine Entscheidung, die Aufgabe zu löschen, bestätigen.
* material:task_alt[role="darkGrey"] *Aufgabe als erledigt markieren* = Der Fortschritt wird auf 100% gesetzt und die Aufgabe wird in den Bereich *Erledigt* verschoben.
* material:task_alt[role="darkGrey"] *Aufgabe als unerledigt markieren* = Diese Option ist nur für erledigte Aufgaben sichtbar.
Der Fortschritt wird auf 0% gesetzt und die Aufgabe wird in den Bereich *Unerledigt* verschoben.

[#220]
=== Firmenweite Aufgaben verfolgen und aktualisieren

Es ist nicht nur möglich, deine eigenen Aufgaben zu verwalten, sondern auch die Aufgaben deiner Mitarbeiter im Blick zu behalten.

[.instruction]
Firmenweite Aufgaben verfolgen:

. Öffne das Menü *plentymarkets Logo (Start) » Aufgaben*. +
→ Deine unerledigten Aufgaben werden standardmäßig angezeigt.
. Klicke auf *Zurücksetzen* (icon:undo[role="orange"]) und wähle die benötigten Filter.
Siehe dazu die Tabelle.
. Klicke auf *Suchen* (icon:search[role="blue"]). +
→ Die Aufgaben, die den eingestellten Suchkriterien entsprechen, werden angezeigt.

[cols="1,3a"]
|===
|Filter |Erläuterung

| *Titel/Beschreibung*
|Filtert nach den Aufgaben, die ein bestimmtes Stichwort in ihrem Titel oder in ihrer Beschreibung haben.
Gib dazu das Stichwort in das Textfeld ein.

*_Hinweis_*: Gib mindestens 4 Zeichen ein.
Dieser Filter ist eine Volltextsuche.

| *ID*
|Filtert nach der Aufgabe mit einer bestimmten ID.
Gib dazu die ID in das Textfeld ein.

*_Hinweis_*: Die Aufgaben-IDs werden automatisch vom System vergeben und sind fortlaufend.
Die ID kann nicht geändert werden.

| *Ticket-ID*
|Filtert nach den Aufgaben, die zu einem bestimmten Ticket gehören.
Gib dazu die Ticket-ID ein.
xref:crm:ticketsystem-nutzen.adoc#4000[Weitere Informationen].

| *Fortschritt*
|Filtert nach den Aufgaben, die einen bestimmten Fortschritt haben.
Wähle dazu einen Operator und den Fortschritt aus den Dropdown-Listen.

| *Priorität*
|Filtert nach den Aufgaben, die eine bestimmte Priorität haben.
Wähle dazu einen Operator und die Priorität aus den Dropdown-Listen.

| *Datum der Erstellung*
|Filtert nach den Aufgaben, die zu einem bestimmten Zeitpunkt erstellt wurden.
Wähle dazu einen Operator aus der Dropdown-Liste und ein Datum aus dem Kalender (icon:calendar[]).

| *Markierung*
|Filtert nach den Aufgaben, die eine bestimmte Markierung haben.
Wähle dazu die Markierung aus der Dropdown-Liste.

| *Eigner*
|Filtert nach den Aufgaben, die einer bestimmten Person zugewiesen sind.
Wähle dazu den Eigner aus der Dropdown-Liste.
|===

[#245]
=== Aufgaben im Ticketsystem erstellen

Neben dem Widget können Aufgaben auch im xref:crm:ticketsystem-nutzen.adoc#4000[Ticketsystem] erstellt werden.
So kannst du zum Beispiel direkt die Aufgaben erstellen, die sich aus einer telefonischen Anfrage ergeben.

[.instruction]
Aufgabe im Ticketsystem erstellen:

. Öffne das Menü *CRM » Ticketsystem » [Ticket öffnen] » Tab: Aufgaben*.
. Klicke auf icon:plus[role="green"] *Neue Aufgabe*.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen im Kapitel xref:willkommen:system-personalisieren.adoc#210[Neue Aufgabe erstellen].
. *Speichere* (terra:save[role="green"]) die Einstellungen. +
→ Die Aufgabe ist mit dem Ticket verknüpft.
Diese Verknüpfung wird auch in der Übersicht im Menü *plentymarkets Logo (Start) » Aufgaben* angezeigt.

[#150]
== Tabellenspalten konfigurieren

In einigen Menüs ist die Übersicht anpassbar.
Das heißt, du kannst selbst entscheiden:

* welche Spalten angezeigt werden sollen.
* in welcher Reihenfolge die Spalten dargestellt werden sollen.
* ob die Ergebnisse in aufsteigender oder absteigender Reihenfolge dargestellt werden sollen.

include::artikel:page$artikelsuche.adoc[tag=configure-columns-overview]

[#183]
== Vollbildmodus aktivieren

Wenn du mehr Platz auf deinem Bildschirm für die Ansichten im Backend freigeben möchtest, kannst du den Vollbildmodus verwenden. Im Vollbildmodus wird die Menüleiste ausgeblendet. Du kannst die Menüleiste dynamisch im Vollbildmodus einblenden, indem du den Mauszeiger an die obere Kante deines Browsertabs bewegst.

Um den Vollbildmodus zu aktivieren bzw. zu deaktivieren, klicke auf icon:ellipsis-v[] oben rechts im plentymarkets Backend und klicke auf *Vollbildmodus an* material:fullscreen[] bzw. *Vollbildmodus aus* material:fullscreen-exit[].

[#185]
== Dark oder Light Theme wählen

Du kannst das Design deines Backends mit verschiedenen Themes und Optionen anpassen. Dabei kannst du folgende Elemente ändern:

* Farbe der Menüleiste
* Größe von verschiedenen Elementen
* Einfärbung von Schaltflächen

Um das Design deines Backends anzupassen, gehe wie folgt vor:

[.instruction]
Design anpassen:

. Zeige mit der Maus auf das Kontosymbol (icon:user-circle[]).
. Klicke auf *Themes*. +
→ Das Fenster *Themes* wird geöffnet.
. Wähle das gewünschte Design.

[#180]
== Bestimmte Editoren verbieten

In einigen Menüs sehen Nutzer eine Dropdown-Liste, aus der sie ihren bevorzugten Editor wählen können.
Standardmäßig stehen die Editoren *Editor*, *Syntax-Editor* und *Textfeld* zur Auswahl.
Bei Bedarf kannst du einzelne Editoren deaktivieren, z.B. wenn du deine Mitarbeiter zwingen willst, nur den Syntax-Editor zu benutzen.

[.instruction]
Editoren deaktivieren:

. Öffne das Menü *Einrichtung » Einstellungen » Editoren*. +
→ Das Tab *Bereiche* öffnet sich.
. Entferne das Häkchen neben den Editoren, die in der Dropdown-Liste des Bereichs nicht angezeigt werden sollen.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[discrete]
=== CSS des Editors einstellen

In der Standardeinstellung wird für den Editor das *CSSContent* verwendet. Wenn dort z.B. ein Hintergrundbild verwendet wird und dieses bei der Bearbeitung im Editor stört, kannst du das CSS im Menü *Einrichtung » Einstellungen » Editoren » Tab: CSS*  anpassen. Alternativ steht mit dem *Standard*-CSS ein weißer Hintergrund zur Verfügung. Du hast auch die Möglichkeit, ein *benutzerdefiniertes* CSS zu erstellen, in dem du die Formatierung weiterer Inhalte, z.B. Schriften, individuell festlegst.

Um das CSS für den Editor einzustellen, öffne das Menü *Einrichtung » Einstellungen » Editoren » Tab: CSS*.

[.instruction]
CSS für den Editor einstellen:

. Öffne das Menü *Einrichtung » Einstellungen » Editoren*.
. Wechsele in das Tab *CSS*.
. Wähle das gewünschte CSS. Beachte dazu die Erläuterungen in <<tabelle-css-editoren>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[[tabelle-css-editoren]]
.Verfügbare CSS
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Wie im Webshop (CSSContent)*
|Das Webshop-CSS wird in den Editor geladen.

| *Standard*
|Ein einfaches Standard-CSS wird in den Editor geladen. Die Hintergrundfarbe ist weiß.

| *Benutzerdefiniert*
|Das einfache Standard-CSS wird in einem Bearbeitungsfenster angezeigt und kann mit dem Syntax-Editor angepasst werden. +
*_Hinweis:_* Mit einem Klick auf *Zurücksetzen* wird das CSS wieder auf das Standard-CSS zurückgesetzt.
|====