////
Hinweise zur Datei:
Kapitelüberschrift “Bearbeitungsmodus nutzen” verwenden (je nach Ebene der Überschrift selbst einbinden)
Anwendungsfall für die spezielle myView händisch auf der Seite hinzufügen - Warum möchte ich den Bearbeitungsmodus nutzen?

:menu-path:
:edit-object:
////


Der Bearbeitungsmodus bietet dir viel Flexibilität beim Anordnen von Inhalten und Daten im Menü {menu-path}. Grundsätzlich platzierst du Elemente intuitiv per Drag-and-drop. Du kannst jedes Element individuell anpassen und weiter bearbeiten. <<#table-functions-editing-mode>> enthält einen Überblick über die Funktionen, die im Bearbeitungsmodus zur Verfügung stehen.

[TIP]
.Hast du Admin-Rechte?
======
Nur xref:business-entscheidungen:benutzerkonten-zugaenge.adoc#[Admin-Benutzer:innen] können Ansichten erstellen und bearbeiten.
Falls du kein Admin bist:

. Wende dich an eine Person mit Admin-Rechten.
. Bitte die Person, die erforderlichen Ansichten für dich zu erstellen und sie für dein Benutzer:innenkonto freizugeben.
======

//// 
TODO: GIF hier einfügen
////

[[table-functions-editing-mode]]
.Verfügbare Funktionen im Bearbeitungsmodus
[cols="2,1,6"]
|====

|Bedienelement |Symbol |Erläuterung

| *Ansicht bearbeiten*
|terra:design_inline_edit[]
| Öffnet die Ansicht zur Bearbeitung. +
Du kannst die Elemente per Drag-and-drop an einer anderen Stelle positionieren und die Größe der Elemente anpassen.

| *Rückgängig*
|material:undo[]
| Macht die letzte Änderung rückgängig, solange die betreffende Änderung noch nicht gespeichert wurde.

| *Wiederherstellen*
|material:redo[]
| Stellt eine rückgängig gemachte Änderung wieder her.

| *Standardansicht*
|
| Dieser Bereich zeigt an, welche Ansicht aktuell geöffnet ist. Klicke auf icon:sort-down[role=darkGrey], um zu einer anderen Ansicht zu wechseln oder eine neue Ansicht zu erstellen.

| *Letzten Speicherpunkt wiederherstellen*
|material:restore[]
| Setzt die Ansicht auf den Stand zurück, der beim letzten Speichern vorhanden war.

| *Speichern*
|material:save[]
| Speichert die Änderungen. Auf diese Weise kannst du beliebig viele Ansichten nach deinen Wünschen speichern. +
Wenn du das nächste Mal {edit-object} bearbeiten möchtest, kannst du die von dir bevorzugte Ansicht über die Dropdown-Liste oben rechts öffnen. Ebenfalls über diese Dropdown-Liste erstellst du mit einem Klick auf material:add[] *Neue Ansicht erstellen…* eine neue Ansicht.

| *Bearbeiten*
|material:edit[]
|Wenn du das Element bearbeitest, siehst du auf der rechten Seite im Bereich *Elemente*, welche Elemente in diesem Bereich noch nicht verwendet wurden und dir somit noch zur Verfügung stehen. Bereits verwendete Elemente sind ausgegraut und können nicht ein weiteres Mal verwendet werden.

| *Löschen*
|material:delete[]
|Löscht das Element.

| *Schließen*
|material:close[]
| Beendet den Bearbeitungsmodus. Wenn du die Änderungen nicht gespeichert hast, wird eine Sicherheitsabfrage angezeigt.

|====
