= Adjusting the online shop search
:lang: en
:keywords: Webshop, online shop, online store, shop, store, client, Standard, plentyShop LTS, Plugin, Ceres, HowTo, setup, Plugin sets, search, item, recommended, relevance, suggestions, results, Boost, item, data fields, item data, priorisation, and, or, Keywords, variation position, Name, plentyShop
:position: 120
:author: team-webshop

This Best Practice supports you in familiarising yourself with the various search options available in plentyShop, so that you can customise the online shop search for the purposes of your store. +
The search settings are mainly carried out in the **Search** step of the plentyShop LTS assistant, which you can find at **Setup » Assistents » Plugins » Select plugin set » plentyShop LTS**. +    

== Sorting search results by relevance

The sorting value **Relevance** sorts search results in accordance with a numeric score that the plentymarkets system determines. The higher this numeric score, the higher the corresponding item's position in the list of the search results. You can determine the calculation of the relevance score in 2 different places in the backend: The plentyShop LTS assistant hosts a slimmed version of this setting in the **Search** step under **Priorisation of search values for the "Relevance" option**. You can find the complete priorisation settings in the **Setup » Item » Search » Front end » Search settings** menu. +

Here, you can activate item data fields that you want to be considered in the calculation of the **Relevance** score. If you activate the fields **Name 1**, **Description**, and **Keywords**, for instance, an item that includes the entered search term in all three item fields will be considered to be more **relevant** than an item that only contains the search term in its name. The first item will thus be displayed higher in the list of search results than the latter item. +

[IMPORTANT]
====
You should deactivate the field **Name (deprecated)** This fields subsumes the three data fields **Name 1**, **Name 2**, and **Name 3**. You can exert more precise influence over the relevant sorting if you deactivate this field. 
====

The **boost** of the individual data fields serves to determine the priorisation. The precise value of the individual boost fields is less important than the order of the boost values. If the boost value for the field **Name 1** is higher than the value for **Name 2**, an item that includes the entered search term in the field **Name 1** will receive a higher numeric relevance score than an item that includes the search term in the field **Name 2**. 

The sorting by **Relevance** will usually list those search results first, that correspond to *all* of the entered search terms, followed by those results that only contain a part of the entered searchs terms. +

[IMPORTANT]
====
Note that the item data fields you activate in the **Consider in search suggestions** area are automatically activated in the **Consider in search results** area, as well. If necessary, you can set the boost value of certain fields to 0 if you don't want them to affect the **Relevance** sorting value. 
====

== Sorting search results by recommended

The sorting value **Recommended** serves to sort search results in accordance to 3 values that you select and prioritise. You carry out these settings in the field **Recommended sorting of search results** in the **Search** step of the plentyShop LTS assistant. +

The 3 sorting values interact with each other in the following way: Your items are first checked for the first sorting value; if 2 or more items would be sorted into the same position of the search results, the second value affects the sorting of the search results. If, as a result of the second sorting process, 2 or more items would be sorted into the same position, the third value becomes effective. + 

**Example:** +
You've configured the recommended sorting of search results in your online shop in such a way that the first sorting value is **Relevance**, followed by **Variation position** as the second and **Price (increasing)** as the third value. A customer of your shop enters "Blue pants" as a search term. The search now goes over your entire item catalogue and assesses it according to the relevance sorting. The item data fields of your items are checked for both search terms ("blue" and "pants"). Depending on the item data fields you've activated for the **Relevance** sorting (name, description, etc.), multiple results may be returned that have the same (invisible) numeric relevance score. In the next step, the results are checked for their *Variation position*, which you either entered yourself or which is determined by the monthly sales. Finally, those results that have both the same relevance score and the same variation position are sorted by their price.

== AND search

Currently, it is not possible to set up plentyShops in such a way that the search only functions as an "AND" search, i.e. that the search exclusively returns results that correspond to **all** search terms. However, the plentyShop search can simulate an "AND" search. For this, you need to select the sorting value **Relevance** for the setting **Default sorting of search results** in the **Search** step of the plentyShop LTS assistant. Alternatively, you can also select the sorting value **Recommended**, as long as **Relevance** is selected as the first value of the recommended sorting option. +
That way, search results that contain all of the entered search terms are displayed first, followed by those that only correspond to parts of the search query. It is not possible to exclude the latter from the search.

