= Testing plentyShop LTS updates for theme compatibility
:lang: en
:keywords: online store, shop, plentyShop, client, plentyShop LTS, plugin, Callisto, standard, HowTo, productive, setting, plugin sets, themes
:position: 10
:author: team-webshop

In this best practice you will learn which steps are necessary in order to test newly published version upgrades of the plentyShop LTS template plugin without impacting the productive live operation of your plentyShop.
 Due to implementations of new features, bugfixes and changes to the user interface, dependencies between external plugins (for instance link:https://marketplace.plentymarkets.com/plugins/themes[layout themes^]) and plentyShop LTS may lead to issues when updating to a new plentyShop LTS version.
Therefore it is advisable to create a copy of your current *plugin set* configuration, with which you can test the compatibility of the newly released plentyShop LTS version and external plugins.

== Copying a plugin set

First, you should create a new *Plugin set*, onto which you can transfer the current settings of your plentyShop LTS shop. To do so, proceed as follows:

[.instruction]
Copying a plugin set:

. Go to *Plugins » Plugin overview*.
. Click on *Create new set*. +
→ The *New plugin set* window opens.
. Enter a name for the plugin set, which should ideally communicate that this is a copy of your plentyShop LTS shop.
. Select the plugin set for which you want to copy the current configuration from the *Copy plugin set* drop-down list.
. *Save* the settings. +
→ The new plugin set will be created.

The plugin set copy now contains the exact same settings as the one used as your plentyShop LTS shop. At this point, both the original set and its copy are identical.
It is advisable to repeat this process before any major update, so that the plugin set is up to date.

== Updating plentyShop LTS for the copied plugin set

In the next step, you need to update the copied plugin set to the current plentyShop LTS version.

[.instruction]
Updating the plugin set:

. Go to *Plugins » Plugin overview*.
. Select the newly created copy of the plugin set. +
→ The *Plugin set details* window opens.
. In the line of the *plentyShop LTS* plugin, click on *Update* in the *Action* column. +
→ The *Install plugin* window opens.
→ The most current version of the plugin is preselected.
. Click on *Install*. +
→ The plugin will open.
. Repeat steps 3 and 4 for the plugin *IO*.
. Click on *Save & publish plugins*.

The copy of the plugin set is now at a more current stage than the plugin set of your plentyShop LTS shop.
Click on the plugin set copy in the list of plugin sets on the left side of the interface. You can access your plentyShop LTS plentyShop in combination with the plugin set copy in preview mode via the button *Plugin set preview*. That way, you can assess whether the current changes to the plentyShop LTS plugin result in incompatibilities with external plugins, like a theme, that your are using.
If the external plugins are functioning correctly under the new plentyShop LTS version, you can either <<plugins#70, activate>> the plugin set copy for the relevant client or *Update* the original plugin set, as detailed above.

[NOTE]
====
Some dependencies betwen external plugins and *plentyShop LTS*/*IO* may not be immediately apparent. For this reason it is advisable to not dismiss the original plugin set prematurely, so that the switch to the previous version is still possible after a number of days without adjusting the plentyShop LTS settings again. If you want to be informed about incompatabilities or other issues between external plugins and a new version of *plentyShop LTS*/*IO*, you are invited to visit the link:https://forum.plentymarkets.com/c/ceres-webshop[forum^].
====
