To counteract the misuse of e-mail forms, you should set up Google reCAPTCHA for your contact form. plentyShop only allows contact forms to be sent that are protected by reCAPTCHA on the front end. +

In the following chapters you will learn how to set up reCAPTCHA in plentyShop.

==== Get reCAPTCHA keys from Google

To set up reCAPTCHA, you need a *Website key* and a *Secret key*, which you get from Google when you register your website for reCAPTCHA. To obtain the keys for your domain, follow these steps: +

[.instruction]
Getting the reCAPTCHA keys:

. Open the link:https://www.google.com/recaptcha/admin/create[Google reCAPTCHA website^].
. Enter a *Label* for your shop. The label serves as a way to identify the keys.
. Select *Point-based (v3)* as the reCAPTCHA type.
. Enter a domain in the input field *Add domain* under *Domains*. Make sure to remove "https://" and any slashes at the end of the URL.
. Click *Send*. +
→ You are redirected to the next page, where your reCAPTCHA keys are displayed.
. Note down the *Website key* and the *Secret key*, so that you have them available when you need to enter them in the plentyShop LTS assistant.

As soon as you have received your reCAPTCHA keys, you must enter them in the plentShop LTS assistant in the next step.

==== Setting up reCAPTCHA in the plentyShop LTS assistant

Open the plentymarkets back end in order to set up Google reCAPTCHA.

[.instruction]
Setting up reCAPTCHA for plentyShop LTS:

. Open the *Setup » Assistants » Plugins » Choose plugin set » plentyShop LTS* menu.
. Choose a client.
. Navigate to the assistant step *Online store*.
. In the *Online store* step, navigate to the *Google reCAPTCHA* section.
. Select *Version 3* as the *reCAPTCHA version*.
. In the input field *API key*, enter the website key you received from Google.
. In the input field *Secret key*, enter the secret key you received from Google.
. If necessary, change the *Threshold* value.
. In the assistant navigation on the left, click on *Summary*.
. In the *Summary* step of the assistant, click on *Finalise*.

This completes the setup of reCAPTCHA. +
If you still receive spam via the contact form after setting up reCAPTCHA, you can increase the *Threshold* of the reCAPTCHA in the first step to catch further spam attempts.

[IMPORTANT]
====
Please note that you must inform your customers in your privacy policy that your online store uses Google reCAPTCHA.
====

