= Bessere Werte bei Google Page Speed Insights erzielen
:lang: de
:keywords: Webshop, Mandant, Standard, plentyShop LTS, Plugin, plentyShop LTS, HowTo, Einrichtung, Plugin-Sets, Google, PSI, page speed, Page Speed, Index, Pages Speed Index, Performance, Geschwindigkeit, Optimierung, Optimieren, Web Vitals, Largest Contentful Paint, CLP, Cumulative Layout Shift, CLS, TTFI, Time, TTFB, Interactive, Viewport, sichtbarer Bereich, SEO, SSR, Server-Side Rendering, Rendering
:position: 110
:author: team-webshop

In diesem Best Practice lernst du, auf welche Dinge du achten musst, um deine Performance-Werte bei link:https://developers.google.com/speed/pagespeed/insights/?hl=de[Google Page Speed Insights] zu verbessern. Im ersten Schritt zeigen wir dir, wie du mit den Mitteln, die plentyShop LTS bereits mitbringt, höhere PSI-Werte erzielen kannst. Zu einem späteren Zeitpunkt wird diese Anleitung auch Anpassungen enthalten, die du mit einem eigenen Theme umsetzen kannst, um von Google PSI besser bewertet zu werden. Die hier aufgeführten Maßnahmen erfordern keinerlei Programmierungskenntnisse.

Im Folgenden sind einige Anpassungen aufgeführt, die du für deinen plentyShop durchführen kannst, um die von Google erfassten Werte zu verbessern:
    
== Live-Modus im plentyShop LTS-Plugin aktivieren

Im Plugin plentyShop LTS hast du die Möglichkeit, zwischen dem *Entwicklungsmodus* und dem *Live-Modus* zu wählen. Im Entwicklungsmodus kannst du Debugging-Optionen nutzen und die Dateien des Plugins werden nicht minimiert und gebündelt, was sich negativ auf die Webshop-Performance auswirkt. Wir raten dir daher, den Live-Modus zu verwenden, um deinen Webshop performanter zu machen. Gehe wir im Folgenden beschrieben vor, um den Live-Modus zu aktivieren:

[.instruction]
Live-Modus aktivieren:

. Öffne das Menü *Plugins » Plugin-Set-Übersicht*.
. Wähle das Plugin-Set aus deines Webshops aus.
. Klicke auf *Plugin-Set bearbeiten*.
. Klicke in der Zeile des Plugins plentyShop LTS auf icon:cog[role="darkGrey"] *Einstellungen*. +
→ Die plentyShop LTS-Einstellungen werden geöffnet.
. Klicke auf das Tab *Logging und Performance*.
. Wähle für die Einstellung *Performance-Level* die Option *Live-Modus*.
. *Speichere* (icon:save[role="green"]) die Einstellungen.


Dadurch, dass du diese Einstellung aktiviert hast, werden die plentyShop LTS-Dateien gebündelt und minimiert, was zu einer schnelleren Auslieferungszeit der Seiten im Webshop führt.

== Vue Server-Side Rendering aktivieren

Mit plentyShop LTS v5.0.29 führen wir Vue Server-Side Rendering (kurz: SSR) ein. Durch SSR werden viele Shop-Komponenten bereits auf dem Server verarbeitet, sodass bereits generierte Seiten direkt an den Browser ausgeliefert werden können. Der Browser muss den übermittelten Code nicht erneut ausführen. Dies hat insbesondere auf die Bewertung der mobilen Seiten positiven Einfluss. +

Im plentyShop-Assistenten und in den plentyShop LTS-Einstellungen könnt ihr im Bereich *Performance* die Einstellung *Vue Server-Side Rendering aktivieren* vornehmen. Aktiviere diese Einstellung erst in einem separaten Plugin-Set und teste deinen Shop, bevor du SSR auch für dein Produktivsystem aktivierst. +

Wenn du SSR verwenden möchtest, solltest du die Bilder-Widgets, die du auf deinen Seiten verwendest, anpassen. Für Bilder-Widgets stehen dir zwei hilfreiche Einstellungen zur Verfügung: Peloading und Lazyloading. Die folgenden Kapitel erklären dir, wie du deine Bilder am besten einstellst.

== Bilder-Widgets optimal einstellen

Bilddateien sind eine der größeren Problemquellen für einen performanten Webshop. Du solltest also darauf achten, dass du nur so viele Bilder-Widgets in deinen Seiten verbaust, wie für deine Zwecke nötig sind. Eine geringere Zahl von Bilder-Widgets wird sich positiv auf die Webshop-Geschwindigkeit auswirken. +

=== Bilder im sichtbaren Bereich vorladen (Preloading)

Ab plentyShop LTS v5.0.29 haben die Widgets Bilderbox, Bilderkarussell, Hintergrundbild und Artikelbild die Einstellung **Bild vorladen**. Diese Einstellung kann nur mit dem oben beschriebenen Server-Side Rendering verwendet werden. Indem du Bilder, die sich beim Aufruf der Seite im sichtbaren Bereich befinden, vorlädst, kannst du den Largest Contentful Paint (LCP) deutlich reduzieren. Der LCP ist abhängig davon, wann das größte gerenderte Inhaltselement im sichtbaren Bereich erscheint. Meistens handelt es sich dabei um Bilder. +
Du solltest die Einstellung *Bild vorladen* für alle Bilder aktivieren, die sich in der initialen Ansicht der Seite befinden, also bevor die Benutzerin weiter nach unten gescrollt hat. Weiter unten erfährst du, wie du den Largest Contentful Paint auf deinen Seiten ausfindig machen kannst.

=== Bilder im nicht sichtbaren Bereich nachladen (Lazy Loading)

Weiterhin emfehlen wir dir, für sämtliche Widgets, die Bilder beinhalten, die Option *Nur sichtbare Inhalte laden* in den Widget-Einstellungen zu aktivieren. Diese Option, das sogenannte "Lazy Loading", sorgt dafür, dass die Bilddateien, die sich beim ersten Aufruf der Seite nicht im aktuellen Sichtbereich befindet, zu einem späteren Zeitpunkt nachgeladen wird. Dies wirkt sich positiv auf die Performance des Webshops aus. +
Lazy Loading ist für Widgets in ShopBuilder-Vorlagen standardmäßig deaktiviert.

[IMPORTANT]
====
Wenn du Server-Side Rendering (SSR) verwendest, ist es wichtig, dass Lazy Loading nur für diejenigen Bilder-Widgets aktiviert wird, die sich beim Aufruf der jeweiligen Seite nicht im sichtbaren Bereich befinden.
====

=== Moderne Bildformate verwenden

Darüber hinaus raten wir dir, die Bilder, die du im Webshop anzeigen willst, in möglichst modernen Bildformaten abzulegen. Wir empfehlen dir, in den Widgets *Bilderbox*, *Bilderkarussell* und *Hintergrundbild* das Feld *Bildauswahl* zu nutzen, um dort Bilder im *WebP-Format* zu hinterlegen. Wenn du eine WebP-Datei nutzt, wird dir zusätzlich die Option *Bildauswahl für ältere Browser* eingeblendet, um Bilder auch in Browsern anzuzeigen, die bisher keine WebP-Formate unterstützen. Dort solltest du nach Möglichkeit das Format JPEG verwenden. +

=== Largest Contenful Paint (LCP) identifizieren

Um den LCP auf deinen Seiten zu identifizieren, kannst du link:https://developers.google.com/speed/pagespeed/insights/[PageSpeed Insights] nutzen. +

[.instruction]
LCP identifizieren:

. Öffne link:https://developers.google.com/speed/pagespeed/insights/[PageSpeed Insights].
. Gib die URL der Seite, deren LCP du überprüfen willst ein.
. Klicken auf *Analysieren*.
→ Die Analyse der Seite wird gestartet.
. Scrolle nach abgeschlossener Analyse zum Bereich *Diagnose*.
. Klicke auf *Largest Contentful Paint-Element*, um den Bereich auszuklappen.
. Das angezeigte Inhaltselement ist der LCP dieser Seite.

Nachdem du den LCP identifiziert hast, überprüfe nun, ob du für dieses Element:
. Preloading aktiviert hast
. das Bild im WebP-Format hinterlegt hast
. die Dateigröße reduzieren kannst

Diese drei Maßnahmen helfen dabei, den Largest Contentful Paint gering zu halten.

== Anzahl der Plugins reduzieren

Jedes zusätzliche Frontend-Plugin, das du in deinem plentyShop einbindest, kann deine Shop-Performance negativ beeinflussen. Dies gilt insbesondere für Plugins, die eine große Menge Javascript mit sich bringen. Du solltest also nur die Plugins in deinem aktiven Plugin-Set aktivieren, die du wirklich für den Produktivbetrieb deines plentyShops brauchst. +
Um zu überprüfen, welche Plugins sich besonders negativ auf deine Performance auswirken, kannst du eine Plugin-Set-Kopie deines jetzigen plentyShops anlegen und zunächst alle Plugins bis auf plentyShop LTS und IO deaktivieren. Nach einem PSI-Test schaltest du nun das nächste Plugin, von dem du denkst, dass es für deinen plentyShop notwendig ist, aktiv, machst den nächsten PSI-Test und wiederholst den Vorgang für alle weiteren Plugins deiner Plugin-Set-Kopie. +
Falls du SSR nutzt, ist es sinnvoll, Plugins einzubinden, die bereits ein SSR-fähiges Update erhalten haben. Wende dich im Zweifelsfall an die Entwickler:innen der betreffenden Plugins. In link:https://forum.plentymarkets.com/t/known-issues-plugins/643980[diesem Thema] sind Plugins aufgelistet, bei denen Inkompatibilitäten mit SSR bekannt sind.  

== Anzahl der Widgets reduzieren

Die Zahl der Widgets, die du auf deinen Webshop-Seiten verbaust, können die Performance deines Webshops negativ beeinflussen: Je mehr Widgets du pro Seite nutzt, desto langsamer lädt diese Seite. Dies gilt insbesondere für Bilder-Widgets und für Widgets, die eine große Menge an Artikeldaten enthalten. Jedes zusätzliche Widget beinträchtigt die Zeit bis zur ersten vollständigen Interaktivität der Seite. +
Wir empfehlen dir daher, nur so viele Widgets pro Seite zu verwenden, wie für deine Zwecke nötig sind. Vor allem auf Kategorieseiten, auf denen große Datenmengen und komplexes Javascript geladen werden muss, solltest du, wenn möglich, die Anzahl der dargestellten Artikel reduzieren und dadurch die Ladezeit verbessern. 

== ShopBooster aktivieren

Die Time-to-first-Byte (TTFB) ist ebenfalls Bestandteil der PSI-Erfassung, auch wenn sie nur einen geringen Teil der Wertung darstellt. Um deine TTFB zu verbessern, kannst du für deinen plentyShop LTS das kostenpflichtige Zusatzmodul ShopBooster aktivieren. Dadurch werden Seiteninhalte von plentyShop LTS Webshops bei einem zweiten Aufruf in den Cache geschrieben, um dadurch deutlich bessere Ladezeiten für deine Nutzer:innen zu erzielen. +

Insbesondere im Zusammenspiel mit Server-Side Rendering (SSR) ist es sinnvoll, ShopBooster zu aktivieren, da die Verwendung von SSR die TTFB leicht erhöhen kann. 


[IMPORTANT]
.Zusätzliche Kosten
====
Durch das Aktivieren des ShopBoosters fallen *pro Mandant* zusätzliche Kosten in Höhe von 0,004 € pro 100 Seitenaufrufe und -änderungen an. Ein Seitenaufruf ist der Vorgang, bei dem ein Shop-Besucher oder ein Webcrawler eine URL des Online-Shops aufruft; eine Seitenänderung wird durch folgende Vorgänge ausgelöst:

- Aktualisieren von Kategorien- und Artikeldaten
- Aktualisieren von ShopBuilder-Seiten
- Bereitstellen von Plugins
- Speichern von Einstellungen in der plentyShop LTS-Konfiguration
- Invalidieren des Caches bei Deaktivierung des ShopBoosters

Die Zusatzkosten des ShopBoosters betragen monatlich *maximal* 100€ pro Mandant.
====

[.instruction]
ShopBooster aktivieren:

. Öffne das Menü *Einrichtung » Mandant » Mandant wählen » Webshop » ShopBooster*.
. Klicke auf *ShopBooster aktivieren*. +
→ Ein Fenster öffnet sich, welches dich auf entsprechende zusätzliche Kosten hinweist.
. Klicke auf *Bestätigen* um den ShopBooster zu aktivieren. +
→ Die Meldung *ShopBooster wurde aktiviert* wird eingeblendet.

Auf die gleiche Weise kannst du den ShopBooster wieder deaktivieren.

[.instruction]
ShopBooster deaktivieren:

. Öffne das Menü *Einrichtung » Mandant » Mandant wählen » Webshop » ShopBooster*.
. Klicke auf *ShopBooster deaktivieren*. +
→ Ein Fenster öffnet sich, welches dich auf zusätzliche Kosten hinweist.
. Klicke auf *Bestätigen* um den ShopBooster zu deaktivieren. +
→ Die Meldung *ShopBooster wurde deaktiviert* wird eingeblendet.

== Unsichtbaren Text durch eigene Schriftarten vermeiden

Falls du eigene Schriftarten einbindest, ohne dabei auf die Design-Einstellungen des ShopBuilders zurückzugreifen, kann es dazu kommen, dass manche Browser versuchen, den Text darzustellen, bevor die betroffene Font-Datei geladen wurde. Dadurch kommt es zu einem sogenannten *Flash of invisible text (FOIT)*, also einer kurzen Zeit, in der der darzustellende Text vom Browser nicht angezeigt werden kann. +
Um dies zu vermeiden, kannst du über eine CSS-Anweisung vorübergehend eine Systemschriftart anzeigen lassen, bis die betroffene Schriftart geladen wurde. Dazu fügst du in deinem eigenen CSS (beispielsweise über das Plugin link:https://marketplace.plentymarkets.com/plugins/storefront/widgets/cfourcustomcssjs_5143[Custom CSS/JS im Frontend]) die Anweisung *font-display: swap* in deinen *@font-face* Styles ein. Dadurch vermeidest du unangenehme FOIT, was sich positiv auf den PSI-Wert deines Webshops auswirkt.

== Javascript in Code-Widgets vermeiden

Im ShopBuilder steht dir ein Code-Widget zur Verfügung, über das du zusätzliche Anpassungen vornehmen kannst, die der ShopBuilder nicht von selbst bereitstellt. Wenn du eigenen Code einbinden möchtest, raten wir dir dazu, eigenes Javascript nicht über Code-Widgets zu realisieren, sondern beispielsweise über das Plugin link:https://marketplace.plentymarkets.com/plugins/storefront/widgets/cfourcustomcssjs_5143[Custom CSS/JS im Frontend] oder ein eigenes Theme. Zusätzliches Javascript in Code-Widgets zu verarbeiten, wirkt sich negativ auf die Ladezeit der Seite aus. +
Falls du eigenes Javascript über ein Plugin oder ein Theme einbindest, empfehlen wir dir, das Javascript ganz am Ende des HTML-Body zu verbauen.


== Plugins für Zahlungsarten richtig verknüpfen

Wenn du Plugin-Zahlungsarten für deinen plentyShop verwendest, die eine große Menge an eigenen Daten beinhalten, wie beispielsweise AmazonPay oder PayPal, ist es für die Performance deines Webshops unerlässlich, dass du diese Plugins mit den richtigen Layout-Containern verknüpfst. In plentyShop LTS 5.0 wurden neue Layout-Container hinzugefügt, um Javascript und CSS der Zahlungsplugins nur an den Stellen zu laden, an denen sie wirklich gebraucht werden. +
Die Plugin-Beschreibungen der jeweiligen Zahlungsarten, z.B. link:https://marketplace.plentymarkets.com/paypal_4690#80.[PayPal], enthalten bereits detaillierte Anleitungen, wie du die Plugins mit den richtigen Containern verknüpfst. Generell gilt, dass du das Javascript der jeweiligen Zahlungsart mit dem Container *Checkout.AfterScriptsLoaded* und nicht mehr mit dem Container *ScriptLoader.AfterScriptsLoaded* verknüpfen solltest, um die Performance deines Webshops zu verbessern.
