= Webshop-Suche einstellen
:lang: de
:keywords: Webshop, Mandant, Standard, plentyShop LTS, Plugin, Ceres, HowTo, Einrichtung, Plugin-Sets, Suche, Artikel, Empfohlen, Relevanz, Sucheinstellungen, Such, Vorschläge, Ergebnisse, Boost, Artikeldatenfelder, Artikeldaten, Gewichtung, Relevanz, Empfohlen, UND, und, oder, Keywords, Variantenposition, Name, Boost,
:position: 120
:author: team-webshop

Dieses Best Practice hilft dir dabei, die unterschiedlichen Sucheinstellungen, die dir für plentyShop zur Verfügung stehen, besser zu verstehen, sodass du die Webshop-Suche optimal für dich nutzen kannst. +
Die Sucheinstellungen für den Webshop nimmst du hauptsächlich im Schritt **Suche** des plentyShop LTS-Assistenten vor. Diesen findest du unter **Einrichtung » Assistenten » Plugins » Plugin-Set wählen » plentyShop LTS**. +

== Sortierung der Suchergebnisse nach Relevanz 

Der Sortierungswert **Relevanz** sortiert die Suchergebnisse entlang eines vom System berechneten Punktewerts. Je höher der errechnete Wert, desto höher wird der jeweilige Artikel in der Liste der Suchergebnisse angezeigt. Wie die Berechnung dieses Punktewerts gewichtet wird, kannst du an 2 Stellen im System bestimmen: Im Assistenten findest du im Schritt **Suche** unter **Gewichtung der Suchwerte für den Wert "Relevanz"** eine abgespeckte Version der Einstellung. Im Menü **Einrichtung » Artikel » Suche » Frontend » Sucheinstellungen** findest du die vollständigen Einstellungen zur Gewichtung des Sortierungswerts **Relevanz**. +

Hier aktivierst du die Artikeldatenfelder, die für eine Sortierung nach **Relevanz** berücksichtigt werden sollen. Aktivierst du beispielsweise die Felder **Name 1**, **Beschreibung** und **Keywords**, so wird ein Artikel, bei dem der eingegeben Suchbegriff in allen drei Datenfeldern enthalten ist, als **relevanter** erachtet, als ein Artikel, bei dem der Suchbegriff nur im Artikelnamen steht, und dadurch weiter oben in der Liste der Suchergebnisse angezeigt. +

[IMPORTANT]
====
Du solltest das Feld **Name (deprectated)** deaktivieren. Dieses Feld fasst die drei Datenfelder **Name 1**, **Name 2** und **Name 3** zusammen. Du kannst gezielter Einfluss auf die **relevante** Sortierung nehmen, wenn dieses Feld inaktiv ist. 
====

Der **Boost** des jeweiligen Datenfelds dient dazu, eine Reihenfolge der Gewichtung festzulegen. Der genaue Wert, den du eingibst, spielt dabei keine Rolle, solange die jeweiligen Werte unterschiedlich hoch sind. Ist der Boost für das Feld **Name 1** höher als der Boost für **Name 2**, so wird ein Artikel, bei dem der eingegebene Suchbegriff im Feld **Name 1** steht, einen höheren Punktewert für die relevante Sortierung erhalten, als ein Artikel, der den Suchbegriff im Feld **Name 2** stehen hat, und wird somit weiter oben in der Liste der Suchergebnisse angezeigt. +

Die Sortierung nach **Relevanz** wird in aller Regel zuerst die Suchergebnisse auflisten, die sämtliche eingegebenen Suchbegriffe enthalten, gefolgt von Ergebnissen, die nur einen Teil der Suchergebnisse enthalten. +

[IMPORTANT]
====
Beachte, dass Artikeldatenfelder, die du im Bereich **In den Suchvorschlägen berücksichtigen** aktivierst, automatisch auch im Bereich **In den Suchergebnissen berücksichtigen** aktiviert werden. Stelle den Boost ggf. auf den Wert 0, wenn du nicht möchtest, dass diese Felder Einfluss auf den Sortierungswert **Relevanz** haben. 
====

== Sortierung der Suchergebnisse nach Empfohlen

Der Sortierungswert **Empfohlen** sortiert die Suchergebnisse nach drei Werten, die du selbst bestimmst und miteinander verkettest. Du nimmst diese Einstellung im Schritt **Suche** des Assistenten im Feld **Empfohlene Sortierung der Suchergebnisse** vor. +

Die Verkettung der Sortierungswerte funktioniert so, dass deine Shop-Artikel im ersten Schritt auf den ersten Sortierungswert hin überprüft werden; liefert diese Prüfung 2 oder mehr Ergebnisse zurück, die nun in den Suchergebnissen gleich hoch priorisiert wären, so greift der zweite Sortierungswert, den du für die empfohlene Sortierung hinterlegt hast. Sollte es nach der Prüfung auf den zweiten Sortierungswert immer noch Artikel geben, die in den Suchergebnissen gleich hoch priorisiert wären, dann greift der dritte verkettete Wert und ordnet die Ergebnisse entsprechend an. +

**Beispiel:** +
Du hast die empfohlene Sortierung in deinem Webshop so eingestellt, dass zuerst auf den Wert **Relevanz**, dann auf die **Variantenposition** und zuletzt auf **Preis (aufsteigend)** geprüft wird. Eine Kundin in deinem Webshop sucht den Begriff "Blaue Hose". Die Suche prüft nun deinen Artikelkatalog zuerst hinsichtlich der von dir eingestellten Gewichtung des Suchwerts **Relevanz**, wie oben beschrieben. Die Datenfelder deiner Artikel werden auf beide Suchbegriffe hin geprüft. Je nachdem, welche Artikeldatenfelder (Beschreibung, Variantenname, etc.) du aktiviert hast, können hier Artikel mit dem gleichen Relevanzwert gelistet werden. Im nächsten Schritt werden diese Ergebnisse daraufhin geprüft, ob du ihnen eine bestimmte **Variantenposition** zugewiesen hast. Dies kann auch über die Einstellung **Variantenposition nach monatlichen Verkäufen berechnen** erfolgt sein. Abschließend werden die Ergebnisse, die sowohl einen gleichen **Relevanzwert** und eine gleiche **Variantenposition** haben, aufsteigend nach Preis sortiert.

[#und-suche]
== UND-Suche

Mit plentyShop LTS Version 5.0.18 wurde im plentyShop LTS-Assistenten die Möglichkeit geschaffen, eine "Und"-Suche für den Webshop zu aktivieren, die nur im ersten Schritt nur Suchergebnisse zurückliefert, die sämtliche in der Suchanfrage eingegebenen Suchbegriffe enthalten. Du hast nun die Möglichkeit, den Suchoperator für die Vorschläge in der Schnellsuche im Header und für die Suchergebnisseite separat einzustellen. Gehe wie im Folgenden beschrieben vor, um die "Und"-Suche zu aktivieren:

[.instruction]
"Und"-Suche aktivieren:

. Öffne den plentyShop LTS-Assistenten im Menü *Einrichtung » Assistenten » Plugins »* _Plugin-Set wählen_ *» plentyShop LTS*.
. Navigiere zum Schritt *Suche*.
. Wähle im Bereich *Suchoperator für Suchergebnisse* die Option *Und-Operator* für die Einstellungen *Operator für die Suchergebnisseite* und *Operator für die Schnellsuche*.
. Schließe den Assistenten ab, damit deine Einstellungen gespeichert werden.
→ Die "Und"-Suche wurde für deinen Webshop aktiviert.

[IMPORTANT]
====
Wenn der Und-Operator für die Suchergebnisseite ausgewählt ist und es für eine Suchanfrage keine passenden Suchergebnisse gibt, wird eine zweite Suche mit dem Oder-Operator ausgeführt, um Kund:innen alternative Vorschläge zu unterbreiten. Über diesen Suchvorschlägen wird ein Hinweis eingeblendet, dass keine passenden Suchergebnisse existieren.
====

