= plentyShop LTS-Updates sicher testen
:lang: de
:keywords: Webshop, Mandant, Standard, plentyShop LTS, Plugin, Callisto, plentyShop LTS, HowTo, Produktiv, Einrichtung, Plugin-Sets, Themes
:position: 10
:author: team-webshop

In diesem Best Practice erfährst du, welche Schritte nötig sind, um neu veröffentlichte Versionen des plentyShop LTS Plugins zu testen, ohne dass dabei der produktive Betrieb deines Webshops beinträchtigt wird.

Durch das Hinzufügen von neuen Features, das Beheben von Bugs und die Vereinfachung der Benutzeroberfläche kann es immer wieder dazu kommen, dass extern entwickelte Plugins, bei denen Abhängigkeiten zu plentyShop LTS bestehen (wie beispielsweise link:https://marketplace.plentymarkets.com/plugins/themes[Themes^]), bei einem Update auf eine höhere plentyShop LTS Version zu Problemen führen.

Wir empfehlen, eine Kopie des Plugin-Sets zu erstellen, mit deren Hilfe die Kompatibilität zwischen einer neuen plentyShop LTS Version und anderen Plugins überprüft werden kann.

== Plugin-Set kopieren

Du solltest zunächst ein neues *Plugin-Set* erstellen, auf welches du alle Einstellungen deines jetzigen plentyShop LTS Webshops überträgst. Gehe dafür wie folgt vor:

[.instruction]
Plugin-Set kopieren:

. Öffne das Menü *Plugins » Plugin-Set-Übersicht*.
. Klicke in der Zeile deines aktiven Plugin-Sets auf *Plugin-Set kopieren* (icon:copy[set=plenty]). +
→ Das Fenster *Plugin-Set kopieren* wird geöffnet.
. Gib einen Namen für das Plugin-Set ein, der ausdrückt, dass das Set eine Kopie deines plentyShops ist.
. Klicke auf *Erstellen*.
→ Das neue Plugin-Set wird erstellt.

Deine Plugin-Set Kopie enthält nun die gleichen Einstellungen wie dein plentyShop LTS Shop. Zu diesem Zeitpunkt sind diese beiden Plugin-Sets identisch.
Du solltest diesen Vorgang vor jedem größeren Update zu wiederholen, damit die Plugin-Set-Kopie auf einem aktuellen Stand ist.

== plentyShop LTS in der Plugin-Set-Kopie aktualisieren

Im nächsten Schritt aktualisierst du die Plugins *plentyhop LTS* und *IO* in der erstellten Kopie des Plugin-Sets:

[.instruction]
Plugin-Set Update:

. Öffne das Menü *Plugins » Plugin-Set-Übersicht*.
. Wähle die erstellte Kopie des Plugin-Sets. +
→ Die Plugin-Set-Ansicht wird geöffnet.
. Klicke in der Zeile des Plugins *plentyShop LTS* auf *Aktualisieren* in der Spalte *Aktion*. +
→ Das Fenster *Plugin aktualisieren* wird geöffnet. +
→ Die aktuelle Version des Plugins ist vorausgewählt.
. Bestätige gegebenenfalls, dass du die *ToDos* zur Kenntnis genommen hast.
. Klicke auf *Aktualisieren*. +
→ Die ausgewählte Version des Plugins wird installiert.
. Wiederhole die Schritte 3 bis 5 für das Plugin *IO*.
. Klicke auf *Plugin-Set bereitstellen*.

Die Kopie des Plugin-Sets befindet sich nun auf einem aktuelleren Stand, als das Plugin-Set, über das dein plentyShop LTS Shop läuft.

Klicke nun auf das neu erstelle Plugin-Set in der Plugin-Set-Liste auf der linken Seite der Oberfläche. 
Über die Schaltfläche *Plugin-Set Vorschau* kannst du deinen plentyShop LTS Shop mit dem aktualisierten Plugin-Set im Vorschaumodus aufrufen. 
Überprüfe, ob die Änderungen an plentyShop LTS zu Fehlern mit dem von dir genutzten Theme führen. +

Wenn die von dir genutzten externen Plugins nach dem plentyShop LTS-Update wie gewünscht laufen, kannst du nun entweder die erstellte Kopie des Plugin-Sets für den Mandanten <<plugins#70, aktivieren>> oder die Plugins deines ursprünglichen Plugin-Set wie oben beschrieben *aktualisieren*.

[NOTE]
====
Manche Abhängigkeiten zwischen externen Plugins und *plentyShop LTS*/*IO* sind nicht sofort ersichtlich. Es ist daher ratsam, das ursprüngliche Plugin-Set nicht vorschnell zu verwerfen, sodass der Wechsel auf die vorherige Version auch nach ein paar Tagen noch möglich ist, ohne dass die plentyShop LTS Konfiguration erneut angepasst werden muss. Im link:https://forum.plentymarkets.com/c/ceres-webshop[Forum^] erfährst du schnell, welche Probleme zwischen externen Plugins und neuen *plentyShop LTS*/*IO* Versionen bestehen können.
====
