= Verzicht auf Widerrufsrecht im Checkout einbauen

:lang: de
:keywords: Webshop, Mandant, Standard, plentyShop LTS, Plugin, Ceres, HowTo, Einrichtung, Plugin-Sets, Artikel, Eigenschaften, Zustimmung, Consent, Checkbox, Checkout, Widget, ShopBuilder, Widerruf, Widerrufsrecht, Anforderung, rechtlich, Rechtliches, digital, digitale Medien
:position: 130
:author: team-webshop

Du bietest in deinem plentyShop digitale Inhalte an und möchtest, dass Kund:innen explizit auf ihr Widerrufsrecht verzichten können? Dann nutze das ShopBuilder-Widget *Zustimmung im Checkout*. Für das Widget legst du eine eigene Eigenschaft an. Für alle Artikel im Warenkorb, die mit dieser Eigenschaft verknüpft sind, müssen Kund:innen im Checkout bestätigen, dass sie auf ihr Widerrufsrecht verzichten. +

Das Widget steht ab plentyShop LTS Version 5.0.51 zur Verfügung.

== Eigenschaft erstellen

Erstelle zuerst eine Eigenschaft, die dazu dient, im Checkout eine Checkbox mit entprechendem Text anzuzeigen.
Deine Kund:innen müssen diese Checkbox anklicken, bevor sie die Bestellung abschließen können.
Neben der Checkbox wird ein Text angezeigt, der deine Kund:innen darüber informiert, dass mit dem Kauf der Ware auf ihr Widerrufsrecht verzichten.
Wie du den Text anpasst, erfährst du weiter unten. +
Erstelle nun eine Eigenschaft. Es spielt dabei keine Rolle, von welchem *Typ* die Eigenschaft ist oder welche *Bestelloptionen* du wählst. Die Eigenschaft muss im Bestellvorgang des Webshops sichtbar sein.

[.instruction]
Neue Eigenschaft erstellen:

. Öffne das Menü *Einrichtung » Einstellungen » Eigenschaften » Konfiguration*.
. Klicke auf icon:plus[role="darkGrey"] *Eigenschaft erstellen*.
. Passe die Einstellungen an deine Bedürfnisse an.
. Aktiviere im Bereich *Sichtbarkeiten* mindestens die Option *Anzeige im Bestellvorgang im Webshop*.
. Speichere (icon:save[role="darkGrey"]) die Einstellungen.

Mehr zum Thema Eigenschaften findest du auf der Handbuchseite xref:artikel:eigenschaften.adoc[Eigenschaften und Merkmale].

== Widget im Checkout-Inhalt platzieren

Du platzierst das Widget *Zustimmung im Checkout* auf einem ShopBuilder-Inhalt vom Typ *Checkout*.
Das Widget ist nicht in der Checkout-Vorlage des ShopBuilders enthalten. +

[.instruction]
Widget platzieren:

. Öffne das Menü *CMS » ShopBuilder*.
. Öffne die Kategorie, die du für den Checkout benutzt.
. Öffne innerhalb der Kategorie einen Inhalt vom Typ *Checkout*. +
→ Die Editor-Ansicht wird geöffnet.
. Öffne links im Widget-Baum die Widget-Kategorie *Checkout*.
. Ziehe das Widget *Zustimmung im Checkout* in deinen Checkout-Inhalt. +
→ Eine Checkbox mit Text wird auf deinem Inhalt angezeigt.
. Klicke auf (icon:cog[role="darkGrey"]) *Einstellungen*, um die Widget-Einstellungen zu öffnen.
. Gib die ID der Eigenschaft, die du erstellt hast, im Feld *Eigenschafts-ID* ein.
. Nimm ggf. weitere Widget-Einstellungen vor.
. Speichere (icon:save[role="darkGrey"]) die Einstellungen.

Für alle Artikel, die mit der angegebenen Eigenschaft verknüpft sind, wird im Checkout die Zustimmungs-Checkbox angezeigt.
Der Text neben der Checkbox informiert Kund:innen darüber, dass sie auf ihr Widerrufsrecht für diese Artikel verzichten.
Im Text werden die Artikelnamen der betroffenen Artikel angezeigt. Im ShopBuilder wird ein Platzhaltertext angezeigt.

== Texte anpassen

Das Widget greift auf 2 Textbausteine zu: der Text, der neben der Checkbox im Checkout angezeigt wird, und die Fehlermeldung, die angezeigt wird, wenn Kund:innen diese Checkbox nicht aktivieren.

Du kannst beide Texte im Menü *CMS » Mehrsprachigkeit* anpassen. +

[.instruction]
Checkout-Text anpassen:

. Öffne das Menü *CMS » Mehrsprachigkeit*.
. Wähle im rechten Bereich *Zielsprache*, die Sprache, für die du den Text anpassen willst.
. Klappe unter *Ceres* den Bereich *Kaufabwicklung* aus.
. Passe den Eintrag *CHECKOUTBASKETITEMCONSENT* nach deinen Wünschen an.
. Speichere (icon:save[role="darkGrey"]) die Einstellungen.

Der Platzhalter `<b>items:</b>` wird im Text mit einer Liste der Artikel gefüllt, die mit der Eigenschaft verknüpft sind. +

[.instruction]
Fehlermeldung anpassen:

. Öffne das Menü *CMS » Mehrsprachigkeit*.
. Wähle im rechten Bereich *Zielsprache*, die Sprache, für die du den Text anpassen willst.
. Klappe unter *Ceres* den Bereich *Kaufabwicklung* aus.
. Passe den Eintrag *CHECKOUTCHECKBASKETITEMCONSENT* nach deinen Wünschen an.
. Speichere (icon:save[role="darkGrey"]) die Einstellungen.
