= Neue Preisangabenverordnung: Niedrigster Preis der letzten 30 Tage anzeigen

:lang: de
:keywords: Webshop, Mandant, Standard, plentyShop LTS, Plugin, Ceres, HowTo, Einrichtung, Plugin-Sets, Artikel, Preisangabenverordnung, PangV, Preise, Ermäßigung, Sale, Discount, rechtliche Anforderung, Artikelkachel, Live-Shopping, CSS, 
:position: 140
:author: team-webshop

Zum 28.05.2022 tritt die neue Preisangabenverordnung in Kraft.
Durch die neue Preisangabenverordnung gilt für Händler:innen eine zusätzliche Informationspflicht: Bei Preisermäßigungen müssen Händler:innen den günstigsten Preis einer Ware, der in den letzten 30 Tagen vor der Preisermäßigung galt, angeben. Weitere Informationen zur Informationspflicht findest du link:https://www.it-recht-kanzlei.de/preisagabenpflichten-preisermaessigungen-waren.html[hier^]. +

Mit dem Veröffentlichen von plentyShop LTS 5.0.51 kannst du diese Vorgabe in deinem plentyShop umsetzen. Falls dein Artikel einen *Streichpreis* hat und für den Artikel ein *niedrigster Preis* hinterlegt ist, wird ein Hinweis am Artikel angezeigt, der den niedrigsten Preis der letzten 30 Tage enthält. Dieser Hinweis wird auf der Artikeleinzelansicht, auf Artikelkacheln in Listen und Kategorien und bei Live-Shopping-Artikeln angezeigt.

== Niedrigsten Preis im Backend hinterlegen

Damit plentyShop LTS den niedrigsten Preis der letzten 30 Tage anzeigen kann, muss dieser im Backend hinterlegt sein.
Du kannst den niedrigsten Preis für Waren entweder manuell anlegen, importieren oder automatisch berechnen lassen. +

Wie du den niedrigsten Preis für deine Waren anlegst, erfährst du auf der Handbuchseite xref:artikel:preise.adoc#950[Verkaufspreise und Preiskalkulation]. Klappe dazu den Bereich *Ich bin verpflichtet, den niedrigsten Preis der letzten 30 Tage anzuzeigen. Wie mache ich das?* aus. +

Sobald der niedrigste Preis für eine Ware hinterlegt ist, gibt plentyShop LTS den entsprechenden Hinweis am Artikel aus. Beachte, dass der Hinweis nur angezeigt wird, wenn auch ein *Streichpreis* vorhanden ist, beispielsweise ein UVP.

=== Hinweistexte anpassen

Der niedrigste Preis einer Variante wird mit dem Hinweis "Niedrigster Preis der letzten 30 Tage: `<span>:price</span>`" angegeben. Du kannst diesen Text im Menü *CMS » Mehrsprachigkeit* anpassen. Es gibt 3 verschiedene Einträge für diesen Text: *itemLowestPrice* für den Hinweis auf Artikelkacheln in Listen und Kategorien, *singleItemLowestPrice* für den Hinweis auf der Artikeleinzelansicht und *liveShoppingLowestPrice* für den Hinweis für Live-Shopping-Artikel. +

[.instruction]
Hinweistexte anpassen:

. Öffne das Menü *CMS » Mehrsprachigkeit*.
. Wähle im rechten Bereich *Zielsprache*, die Sprache, für die du den Text anpassen willst.
. Klappe unter *Ceres* den Bereich *Artikel* aus.
. Passe den Eintrag *itemLowestPrice* nach deinen Wünschen an.
. Klappe unter *Ceres* den Bereich *Artikelansicht* aus.
. Passe den Eintrag *singleItemLowestPrice* nach deinen Wünschen an.
. Klappe unter *Ceres* den Bereich *Live Shopping* aus.
. Passe den Eintrag *liveShoppingLowestPrice* nach deinen Wünschen an.
. Speichere (icon:save[role="darkGrey"]) die Einstellungen.

Der Platzhalter `<span>:price</span>` wird im Text mit dem im Backend hinterlegten niedrigsten Preis befüllt.

[WARNING]
.Übersetzungsschlüssel itemLowestPrice
====
Der Übersetzungsschlüssel *itemLowestPrice* kann durch einen Fehler in plentyShop LTS-Version 5.0.51 noch nicht bearbeitet werden. Wir werden diesen Fehler in der nächsten Version beheben. Dein plentyShop ist hinsichtlich der neuen Preisangabenverordnung trotzdem rechtssicher. Du kannst zum jetzigen Zeitpunkt nur den Text für die Artikelkacheln nicht selbst anpassen.
====

=== CSS-Klassen für die Angabe des niedrigsten Preises

Um den niedrigsten Preis und den Hinweistext nach deinen Wünschen zu gestalten, haben wir 3 CSS-Klassen hinzugefügt, die du referenzieren kannst. +

Mit der CSS-Klasse `lowest-price` kannst du den Preis und Hinweistext in der Artikeleinzelansicht am Preis-Widget gestalten. +
Mit der CSS-Klasse `category-lowest-price` kannst du den Preis und Hinweistext für Artikelkacheln in Artikellisten und in Kategorien stylen. Diese Klasse betrifft auch inaktive Live-Shopping-Artikel, also Live-Shopping-Artikel, die bereits abgelaufen oder noch nicht gestartet sind. +
Mit der CSS-Klasse `live-shopping-lowest-price` kannst du den Preis und Hinweistext für aktive Live-Shopping-Artikel gestalten.
