*plentyShop LTS* wird mit einer Standardstartseite als Platzhalter ausgeliefert. +
Du passt die Startseite deines Shops mit dem xref:webshop:shop-builder.adoc#shopbuilder-intro[ShopBuilder] an. +
Deaktiviere die Standardstartseite, damit diese mit der ShopBuilder-Startseite ersetzt wird.

[#60.instruction]
Standard-Startseite deaktivieren:

. Öffne das Menü *Plugins » Plugin-Übersicht*. +
→ Die Plugin-Übersicht wird geöffnet.
. Klicke auf *plentyShop LTS*. +
→ Das Plugin wird geöffnet.
. Klicke im Verzeichnisbaum auf *Konfiguration*.
. Wechsle in das Tab *Startseite*.
. Deaktiviere die Einstellung *Standardstartseite anzeigen*.
. Aktiviere die Einstellung *ShopBuilder Startseite anzeigen*.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Die Standard-Startseite wird deaktiviert und deine ShopBuilder Startseite kann angezeigt werden.

[#65]

==== plentyShop LTS-Startseite mit dem ShopBuilder erstellen

Mit dem ShopBuilder kannst du die Startseite deines plentyShops mit wenigen Handgriffen in deinem Terra-Backend erstellen und bearbeiten.

Informationen zur Einrichtung des ShopBuilders findest du auf der ShopBuilder xref:webshop:shop-builder.adoc#shopbuilder-intro[Handbuchseite].