Um der missbräuchlichen Nutzung von E-Mail-Formularen entgegenzuwirken, solltest du für dein Kontaktformular Google reCAPTCHA einrichten. plentyShop lässt nur das Versenden von Kontaktformularen zu, die durch reCAPTCHA Frontend-seitig abgesichert sind. +

In den folgenden Kapiteln erfährst du, wie du reCAPTCHA im plentyShop einrichtest.

==== reCAPTCHA-Schlüssel erhalten

Um reCAPTCHA einzurichten, benötigst du einen *Websiteschlüssel* und einen *Geheimen Schlüssel*, den du von Google erhältst, wenn du deine Website für reCAPTCHA registrierst. Gehe wie folgt vor, um die Schlüssel für deine Domain zu erhalten: +

[.instruction]
reCAPTCHA-Schlüssel erhalten:

. Öffne die link:https://www.google.com/recaptcha/admin/create[Google reCAPTCHA Seite^].
. Gib ein *Label* für deine Seite ein. Dieses Label dient zur Identifizierung der Schlüssel.
. Wähle *Punktebasiert (v3)* als reCAPTCHA-Typ.
. Gib deine Domain unter *Domains* im Feld *Domain hinzufügen* ein. Achte darauf, "https://" und Slashes am Ende der URL zu entfernen.
. Klicke auf *Senden*. +
→ Du wirst zur nächsten Seite weitergeleitet, auf der deine reCAPTCHA-Schlüssel angezeigt werden.
. Notiere dir den *Websiteschlüssel* und den *Geheimen Schlüssel*, damit du die Schlüssel im plentyShop LTS-Assistenten hinterlegen kannst.

Sobald du deine reCAPTCHA-Schlüssel erhalten hast, musst du diese im nächsten Schritt im plentShop LTS-Assistenten hinterlegen.

==== reCAPTCHA mit dem plentyShop LTS-Assistenten einrichten

Öffne dein plentyMarkets Backend, um die reCAPTCHA-Einrichtung vornzunehmen.

[.instruction]
reCAPTCHA für plentyShop LTS einrichten:

. Öffne das Menü *Einrichtung » Assistenten » Plugins » Plugin-Set wählen » plentyShop LTS*.
. Wähle einen Mandanten.
. Navigiere im Assistenten zum Schritt *Webshop*.
. Navigiere Schritt *Webshop* zu dem Abschnitt *Google reCAPTCHA*.
. Wähle *Version 3* als *reCAPTCHA-Version*.
. Gib im Feld *API-Schlüssel* den Websiteschlüssel ein, den du von Google erhalten hast.
. Gib im Feld *Geheimer Schlüssel* den geheimen Schlüssel ein, den du von Google erhalten hast.
. Ändere ggf. den *Grenzwert*.
. Klicke links in der Navigation des Assistenten auf *Zusammenfassung*.
. Klicke im Schritt *Zusammenfassung* des Assistenten auf *Abschließen*.

Damit ist die Einrichtung von reCAPTCHA abgeschlossen. +
Falls du nach der Einrichtung von reCAPTCHA noch Spam über das Kontakformular erhalten solltest, kannst du im ersten Schritt den *Grenzwert* des reCAPTCHAs erhöhen, um weitere Spamversuche abzufangen. 

[IMPORTANT]
====
Beachte, dass du deine Kund:innen in deiner Datenschutzerklärung darüber informieren musst, dass dein Shop Google reCAPTCHA verwendet.
====

