Der link:https://www.plentymarkets.eu/blog/Volle-Kraft-voraus-ShopBooster-bringt-deinen-Ceres-Shop-auf-Hochtouren/b-2125/[ShopBooster^] ist ein Zusatzmodul, über welches Seiteninhalte von plentyShop LTS in den Cache geschrieben werden. Dadurch erzielst du deutlich bessere Ladezeiten im Shop. +

Der ShopBooster sorgt dafür, dass Seiten nach dem ersten Aufruf in den Cache gespeichert werden, sodass sie danach bei jedem erneuten Aufrufen schneller ausgeliefert werden können. 
Bestimmte Ereignisse sorgen dafür, dass Inhalte wieder invalidiert werden. 
Das bedeutet, dass sie aus dem Cache gelöscht werden, wenn sich beispielsweise Plugin-Einstellungen ändern. +

Der ShopBooster schreibt alle Webshop-Inhalte in den Cache, mit Ausnahme der Seiten *Mein Konto*, *Checkout*, *Warenkorb*, *Auftragsbestätigung* und solchen Seiten, die Kund:innendaten erhalten.

[TIP]
.Keine zusätzlichen Kosten
====
Der ShopBooster und all seine Funktionen sind ohne zusätzliche Kosten nutzbar.
====

[#cache-bloecke-aktivieren]
=== Cache-Blöcke aktivieren

Durch die Verwendung von Cache-Blöcken kannst du gewährleisten, dass bereits gecachte Seiteninhalte nicht unnötig invalidiert werden. Cache-Blöcke teilen die Seiteninhalte in Blöcke auf, die separat invalidiert werden können. Inhalte, die auf mehreren Seiten identisch sind (z.B. der Footer) können somit einmalig erneuert werden und dann auf allen gecachten Inhalten ersetzt werden, ohne dass alle betroffenen Seiten vollständig invalidiert werden müssen.

Dies führt zu einer verbesserten Cache-Abdeckung und im Durchschnitt auch zu einer verbesserten Time-to-first-Byte (TTFB), die einen starken Einfluss auf PSI haben kann.

[NOTE]
.Anpassungen für zusätzliches Theme
====
Cache-Blöcke sind direkt mit plentyShop LTS und plentyShop LTS Modern kompatibel. Falls du ein zusätzliches Theme nutzt, müssen Anpassungen daran gemacht werden, damit Cache-Blöcke einen Effekt haben.
Weitere Informationen dazu findest du in unserer link:https://developers.plentymarkets.com/en-gb/developers/main/plentyshop-plugins/shopbooster-cache-blocks.html#_using_the_plentyshop_lts_cache_blocks_in_your_own_theme[Entwicklerdokumentation^].
====

[.instruction]
ShopBooster Cache-Blöcke aktivieren:

. Öffne das Menü *Einrichtung » plentyShop » (Mandanten wählen) » ShopBooster*.
. Klicke auf *Cache-Blöcke aktivieren*. +
→ Die Cache-Blöcke werden aktiviert.

Auf die gleiche Weise kannst du ShopBooster Cache-Blöcke wieder deaktivieren.

[.instruction]
ShopBooster Cache-Blöcke deaktivieren:

. Öffne das Menü *Einrichtung » plentyShop » (Mandanten wählen) » ShopBooster*.
. Klicke auf *Cache-Blöcke deaktivieren*. +
→ Die Cache-Blöcke werden deaktiviert.

[#softpurging]
=== Softpurging

ShopBooster verwendet das sogenannte Softpurging, um die Webshop-Performance zu erhöhen. 
Wenn Inhalte invalidiert werden, wird der alte gecachte Inhalt beim Aufruf der Seite ein weiteres Mal ausgegeben, während der aktualisierte Inhalt im Hintergrund in den Cache geschrieben wird. Dadurch können Webshop-Inhalte immer schnell aus dem Cache geladen werden. 

[#invalidierung]
=== Invalidierung des ShopBooster-Caches

Das Invalidieren von Inhalten, die im ShopBooster-Cache gespeichert sind, sorgt dafür, dass diese Inhalte aus dem Cache gelöscht werden, um zu vermeiden, dass veraltete Inhalte im plentyShop angezeigt werden. 

==== Invalidierung anstoßen

Die folgenden Aktionen oder Ereignisse führen zu einer teilweisen oder vollständigen Invalidierung des ShopBooster-Caches: +

* Bearbeiten oder Löschen einer Kategorie +
* Löschen einer Verknüpfung zwischen Variante und Kategorie +
* Änderungen an Plugin-Einstellungen +
* Verknüpfen eines Mandanten mit einem Plugin-Set +
* Manuelles Invalidieren im Menü *Einrichtung » Mandant » ShopBooster* +
* Erstellen, bearbeiten oder löschen eines Live-Shopping-Angebots +
* Abschließen eines Kaufs eines Artikels, der zu einem Live-Shopping-Angebot gehört. Dabei wird die Invalidierung nur angestoßen, wenn es sich bei dem gekauften Artikel um den letzten verfügbaren Artikel des Live-Shopping-Angebots handelt. +
* Speichern von Rechtstexten im Menü *Einrichtung » Mandant » [Mandant wählen] » Webshop » Rechtliches* +
* Speichern von Einstellungen im plentyShop LTS Assistenten +
* Bearbeiten von Verkaufspreisen im Menü *Einrichtung » Artikel » Verkaufspreise* +
* Bereitstellen des Plugin-Sets +

==== Dauer der Invalidierung

In den meisten Fällen dauert es etwa 5 Minuten, bis die Inhalte, die im ShopBooster-Cache liegen, invalidiert wurden. In seltenen Fällen kann das Invalidieren bis zu 10 Minuten dauern.

[#invalidierung-deaktivieren]
=== Invalidierung deaktivieren

Du kannst im Bereich *Invalidierung deaktivieren* die Invalidierung des ShopBoosters bis zu dem eingetragenen Termin deaktivieren. Dadurch werden deine Artikeldaten bis zum gewählten Zeitpunkt immer aus dem Cache geladen, ohne dass dieser gelöscht bzw. aktualisiert wird. Das führt dazu, dass dein plentyShop schnellere Ladezeiten erzielen kann. +

Beachte, dass bei inaktiver Invalidierung Änderungen an der Sichtbarkeit des Artikels nicht mehr aktualisiert werden, sodass bspw. Artikel in deinem plentyShop sichtbar sein können, die durch Ausverkauf nicht mehr sichtbar sein sollten. Es ist für deine Kund:innen dadurch aber nicht möglich, nicht verfügbare Artikel zu kaufen.

[.instruction]
Invalidierung deaktivieren:

. Öffne das Menü *Einrichtung » plentyShop » (Mandanten wählen) » ShopBooster*.
. Gib das Datum ein, bis zu welchem die Invalidierung deaktiviert werden soll.
. Gib die Uhrzeit ein, bis zu welcher die Invalidierung deaktiviert werden soll.
. *Speichere* deine Eingabe.

[#sofort-invalidieren]
=== Cache sofort invalidieren

Du kannst gecachte Inhalte manuell aus dem Cache entfernen. Dir stehen 5 Invalidierungen pro Tag zur Verfügung. Die Invalidierungen werden jede Nacht um 00:00 Uhr zurückgesetzt. Beachte, dass die Ladezeiten deines Shops nach einer Invalidierung höher sind, bis deine Shopseiten durch den ersten Aufruf wieder in den Cache geschrieben werden.

[.instruction]
Cache manuell invalidieren:

. Öffne das Menü *Einrichtung » plentyShop » (Mandanten wählen) » ShopBooster*.
. Klicke im Bereich *Cache sofort invalidieren* auf die Schaltfläche *Invalidieren*. +
→ Der Cache wird gelöscht und die Mitteilung *Cache wurde invalidiert* wird angezeigt. +
→ Die Zahl der *Für heute verbleibende Invalidierungen* wird um 1 reduziert.

[#shopbooster-parameter]
=== Zusätzliche Abfrageparameter  

//überarbeiten sobald die UI online ist
ShopBooster bietet dir die Möglichkeit, zusätzliche Abfrageparameter hinzuzufügen, um plentyShop-Seiten mit diesen Abfrageparametern aus dem ShopBooster-Cache zu laden. 
Du kannst auch bestimmte Abfrageparameter vom ShopBooster-Caching ausschließen. 
Wenn Nutzer:innen auf eine Seite mit ausgeschlossenen Abfrageparametern zugreifen, wird stattdessen die gleiche Seite ohne Parameter aus dem ShopBooster-Cache geladen. +
// Beispiel please
Du kannst beliebig viele Abfrageparameter hinzufügen oder ausschließen, ohne dass es sich nachteilig auf deine Shop-Performance auswirkt.

==== Abfrageparameter hinzufügen

Im Menü **Einrichtung » Mandant » [Mandanten wählen] » Webshop » ShopBooster** kannst du im Bereich *Abfrageparameter* weitere Parameter hinzufügen. Es gibt keine minimale oder maximale Anzahl an Zeichen. +
Standardmäßig werden Seiten mit den folgenden Abfrageparametern von ShopBooster in den Cache geschrieben: +

* ReferrerID +
* ShipToCountry +
* Currency +
* currency +
* page +
* items +
* sorting +
* facets +
* category +

Um zusätzliche Abfrageparameter hinzuzufügen, gehe wie folgt vor: +

[.instruction]
Abfrageparameter hinzufügen:

. Öffne das Menü *Einrichtung » plentyShop » (Mandanten wählen) » ShopBooster*.
. Klicke im Bereich *Abfrageparameter* in das Eingabefeld **Enthaltene Abfrageparameter**. +
. Gib den Abfrageparameter ein, den du zum ShopBooster-Cache hinzufügen möchtest.
. Klicke auf die *Plus*-Schaltfläche neben dem Eingabefeld. +
→ Der Abfrageparameter wurde hinzugefügt und wird unterhalb des Eingabefelds angezeigt. +
→ Seiten, deren URL diesen Abfrageparameter beinhalten, werden nun aus dem ShopBooster-Cache geladen. +

Um einen Parameter wieder zu entfernen, klicke auf die *X*-schaltfläche auf dem betreffenden Parameter.

==== Abfrageparameter vom ShopBooster-Cache ausschließen

Im Menü **Einrichtung » Mandant » [Mandanten wählen] » Webshop » ShopBooster** kannst du im Bereich *Abfrageparameter* bestimmte Parameter vom Caching ausschließen. Durch das Ausschließen eines Abfrageparameters wird beim Aufruf einer Seite mit diesem Parameter stattdessen die Version der Seite ohne diesen Parameter aus dem ShopBooster-Cache geladen. Beim Aufruf der URL "plentymarkets.com?gclid=123" wird demnach der Inhalt der Seite "plentymarkets.com" aus dem Cache geladen und angezeigt. +
Es gibt keine minimale oder maximale Anzahl an Zeichen. +
Standardmäßig werden die folgenden Abfrageparametern von ShopBooster ausgeschlossen: +

* gclid +
* idealoid +
* vmtrack_id +
* vmst_id +
* utm_source +
* utm_medium +
* utm_campaign +

Um bestimmte Abfrageparameter auszuschließen, gehe wie folgt vor: +

[.instruction]
Abfrageparameter ausschließen:

. Öffne das Menü *Einrichtung » plentyShop » (Mandanten wählen) » ShopBooster*.
. Klicke im Bereich *Abfrageparameter* in das Eingabefeld **Ausgeschlossene Abfrageparameter**. +
. Gib den Abfrageparameter ein, den du vom ShopBooster-Cache ausschließen möchtest.
. Klicke auf die *Plus*-Schaltfläche neben dem Eingabefeld. +
→ Der Abfrageparameter wurde hinzugefügt und wird unterhalb des Eingabefelds angezeigt. +
→ Seiten, deren URL diesen Abfrageparameter beinhalten, werden nun ohne diesen Parameter aus dem ShopBooster-Cache geladen. +

Um einen Parameter wieder zu entfernen, klicke auf die *X*-schaltfläche auf dem betreffenden Parameter.

[#cache-status-pruefen]
=== Cache-Status einer Seite prüfen

Um sicherzustellen, dass der ShopBooster wirksam ist und eine Seite aus dem Cache geladen wird, kannst du die Entwicklertools deines Browsers verwenden.
Die folgende Anleitung basiert auf dem Google Chrome Browser.

[.instruction]
Cache-Status einer Seite prüfen:

. Öffne eine Artikel- oder Kategorieseite in deinem Shop.
. Öffne die Entwicklertools, indem du rechtsklickst und *Untersuchen* wählst. +
→ Die Entwicklertools werden geöffnet.
. Klicke in der oberen Leiste auf das Tab *Netzwerk*.
. Klicke in der *Filtern-Leiste* auf *Doc*.
. Klicke unter *Name* auf den Namen der Seite.
. Öffne in der Detailansicht der Seite das Tab *Header*.
. Prüfe, ob im Abschnitt *Antwortheader* der Eintrag *x-plenty-cache: hit* erscheint.

Falls der Antwortheader den Eintrag *x-plenty-cache: hit* enthält, liegt die Seite im ShopBooster-Cache. Falls du den Eintrag nicht findest, liegt die untersuchte Seite nicht im Cache.

[NOTE]
====
Beachte, dass Shop-Seiten 1 mal aufgerufen werden müssen, damit sie in den Cache geschrieben werden. Falls die untersuchte Seite keinen *x-plenty-cache: hit*-Eintrag enthält, lade die Seite erneut. Falls die Seite immer noch nicht aus dem Cache geladen wird, kontaktiere uns im link:https://forum.plentymarkets.com/c/plentyshop/125[Forum^].
====