Der Integrationenassistent installiert für dich die beiden Plugins plentyShop LTS und IO. Du kannst darüber auch die Zahlungsanbieter und Versanddienstleister installieren, die du für plentyShop verwenden willst. Gehe wie folgt vor, um plentyShop LTS und IO zu installieren:

[.instruction]
Integrationenassistenten durchlaufen:

. Öffne das Menü *Einrichtung » Assistenten » Grundeinrichtung » Integrationen*.
. Aktiviere im Schritt **Online-Shops** die Option **plentyShop LTS installieren**.
. Aktiviere ggf. Zahlunsanbieter und Versanddienstleister, deren Dienste du nutzen möchtest.
. Wähle im Schritt **Informationen zur Installation** das **Plugin-Set**, in dem du die Plugins installieren möchtest.
. Klicke im Schritt **Zusammenfassung** auf **Abschließen**. +
→ plentyShop LTS, IO und ggf. weitere Zahlungs- und Versand-Plugins werden geladen und installiert.

[WARNING]
.Assistent mit ähnlichem Namen
====
Es gibt neben dem Integrationenassistent den ähnlich benannten Bereich **Einrichtung » Assistenten » Integration**, in dem bspw. der Assistent für Versandeinstellungen liegt. Achte darauf, dass du den Integrationenassistent unter **Grundeinrichtung** durchläufst, um die Plugins zu installieren.
====