Die Inhaltsübersicht ist in 3 Bereiche, sogenannte Portlets, unterteilt: *Header-Inhalte*, *Inhalte für die ausgewählte Kategorie* und *Footer-Inhalte*.
Header- und Footer-Inhalte sind standardmäßig eingeklappt und können durch Klick auf (icon:chevron-right[role="darkGrey"]) angezeigt werden.
In der Inhaltsübersicht siehst du, welche Inhalte *aktiv* sind, für welche Inhalte sie *sichtbar* sind, welche *Typen* die Inhalte haben, wie sie heißen und wann sie *erstellt* und *zuletzt bearbeitet* wurden.
Hier kannst du xref:webshop:shop-builder.adoc#inhalte-erstellen[neue Inhalte erstellen], xref:webshop:shop-builder.adoc#inhalte-aktivieren[Inhalte aktivieren], xref:webshop:shop-builder.adoc#sichtbarkeit[sichtbar schalten], xref:webshop:shop-builder.adoc#inhalt-duplizieren[kopieren], und vieles mehr.

[#inhalte-erstellen]
==== Inhalte im ShopBuilder erstellen

In der Content-Manager-Ansicht des ShopBuilders legst du für deine Kategorien neue *Inhalte* an, die du daraufhin im Editor des ShopBuilders bearbeitest. Ein *Inhalt* ist jeweils ein Seitenentwurf. Du kannst viele verschiedene Inhalte pro Kategorie erstellen und je nach Bedarf *aktivieren* und *deaktivieren*. Dies ist beispielsweise hilfreich, um saisonabhängige Startseiten zu designen oder Shopaktionen im voraus zu gestalten. +
Pro Kategorie kann nur ein Inhalt gleichzeitig aktiv sein.

[#content-typen]
[TIP]
.Content-Typen
====
Beim Erstellen von neuen Inhalten für **Content**-Kategorien kannst du aus 4 verschiedenen Typen wählen:

- Inhalte vom Typ *Content* verwendest du für die Startseite und statische Seiten, wie die Firmengeschichte oder deine Versandkosteninformationen.
- Inhalte vom Typ *Checkout* verwendest du für die Kaufabwicklung.
- Inhalte vom Typ *Mein Konto* verwendest du für den Kund:innenbereich in deinem Webshop.
- Inhalte vom Typ *Softlogin* verwendest du, um den Zugang Bestellbestätigungsseiten für Gastbestellungen zu ermöglichen.

Beim Erstellen von neuen Inhalten für **Artikel**-Kategorien kannst du aus den folgenden Typen wählen:

- Inhalte vom Type *Artikelansicht* verwendest du für die Darstellung individueller Artikel.
- Inhalte vom Typ *Kategorieansicht* verwendest du für die Darstellung von Artikelkategorien.
- Inhalte vom Typ *Artikelsuchergebnis* verwendest du für die Seite, die angezeigt wird, nachdem Kund:innen eine Suche abschicken.
- Inhalte vom Typ *Artikelset* verwendest du für xref:artikel:multipacks-pakete-sets.adoc#3000[Sets], die verschiedene Artikel beinhalten.
====

[.instruction]
Inhalt erstellen:

. Öffne das Menü *CMS » ShopBuilder*. +
→ Die Content-Manager-Ansicht des ShopBuilders wird geöffnet.
. Wähle links im Kategoriebaum die Kategorie, für die du einen Inhalt erstellen möchtest.
. Klicke auf die Schaltfläche *Inhalt hinzufügen* (icon:plus-square[role="green"]). +
→ Die Auswahl der Content-Typen wird geöffnet.
. Wähle den xref:webshop:shop-builder.adoc#content-typen[Content-Typen], den du für deinen Inhalt verwenden willst. +
→ Das Fenster **Neuen Inhalt vom Typ "Content-Typ" erstellen** wird geöffnet.
. Gib einen Namen für den Inhalt ein.
. Wähle ggf. eine Vorlage aus.
. Klicke auf **Erstellen**. +
→ Der neu erstellte Inhalt wird in der Übersicht angezeigt.


[#inhalte-aktivieren]
==== Inhalte aktivieren

Damit dein Inhalt im plentyShop angezeigt wird, musst du ihn *aktivieren*.
Aktive Inhalte werden in der Spalte *Aktiv* blau und mit *aktiviertem Toggle-Schalter* (icon:toggle-on[role="blue"])hervorgehoben.
Pro Kategorie kann nur 1 Inhalt aktiv sein.

[.instruction]
Inhalt aktivieren:

. Öffne das Menü *CMS » ShopBuilder*. +
→ Die Content-Manager-Ansicht des ShopBuilders wird geöffnet.
. Klicke in der Zeile des Inhalts, den du aktivieren möchtest, auf den Toggle-Schalter (icon:toggle-on[role="darkGrey"]) in der Spalte *Aktiv*. +
→ Bei *Artikelkategorien* wird das Fenster xref:webshop:shop-builder.adoc#sichtbarkeit[Inhalt aktivieren] geöffnet. +
→ Bei *Content-Kategorien* wird der Inhalt aktiviert und nun blau in der Übersicht dargestellt. +
→ Das Aktivieren eines Inhalts deaktiviert einen zuvor aktiven Inhalt.

[#sichtbarkeit]
==== Sichtbarkeit von Inhalten für Artikelkategorien

Wenn du Inhalte der Typen *Artikelansicht*, *Kategorieansicht* oder *Artikelsets* aktivierst, wird ein Fenster geöffnet, in dem du angibst, für welche Artikel oder Kategorien du deinen Inhalt aktivieren willst.

[[tabelle-sichtbarkeit]]
.Sichtbarkeit von Inhalten für Artikelkategorien

[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Alle*
|Der Inhalt wird global für alle Artikel/Kategorien/Artikelsets aktiviert. In der Inhaltsübersicht wird diese Sichtbarkeit durch die Weltkugel (icon:globe[role="darkGrey"]) gekennzeichnet.

|*Aktuelle Kategorie und ihre Unterkategorien*
|Der Inhalt wird für die Kategorie, in der er erstellt wurde, und alle enthaltenen Unterkategorien aktiviert. Falls es einen anderen Inhalt gibt, der global für *alle* Artikel/Kategorien/Artikelsets aktiviert ist, wird dieser hiermit überschrieben. In der Inhaltsübersicht wird diese Sichtbarkeit durch das Vererbungs-Icon (icon:files-o[role="darkGrey"]) gekennzeichnet.

|*Aktuelle Kategorie*
|Der Inhalt wird nur für die aktuelle Kategorie, nicht aber für enthaltene Unterkategorien aktiviert. Falls es einen anderen Inhalt gibt, der global für *alle* Artikel/Kategorien/Artikelsets aktiviert ist, wird dieser hiermit überschrieben. In der Inhaltsübersicht wird diese Sichtbarkeit durch das Datei-Icon (icon:file[role="darkGrey"]) gekennzeichnet.

|====


//[#vorlagen]
// ==== Vorlagen

// Wir bieten Standardvorlagen für die meisten Inhaltstypen an, auf die du beim Erstellen eines Inhalts zurückgreifen kannst. Diese sind ein guter Ausgangspunkt, von dem aus du deinen Webshop individuell gestalten kannst.


// Kapitel ausbauen
// welche Vorlagen gibt es noch nicht?



[#inhalte-header-footer]
==== Inhalte für Header und Footer im ShopBuilder erstellen

In der Content-Manager-Ansicht des ShopBuilders kannst du auf die gleiche Weise Header- und ein Footer-Inhalte erstellen. Header und Footer sind global, also für den gesamten Webshop, wirksam.

[.instruction]
Einen Header oder Footer im ShopBuilder erstellen:

. Öffne das Menü *CMS » ShopBuilder*. +
→ Die Content-Manager-Ansicht des ShopBuilders wird geöffnet.
. Klicke im Abschnitt *Header-Elemente* oder *Footer-Elemente* auf *Neu*. +
→ Das Fenster *Neue Seite erstellen* wird geöffnet.
. Gib einen Namen für den Inhalt ein.
. Wähle ggf. eine Vorlage fpr den Header oder Footer.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Der Inhalt für Header oder Footer wurde angelegt.

[#inhalte-loeschen]
==== Inhalte im ShopBuilder löschen

Du kannst im ShopBuilder erstellte Seiten auch wieder entfernen. Beachte, dass der Inhalt dadurch unwiderruflich verloren geht.

[.instruction]
Inhalt löschen:

. Öffne das Menü *CMS » ShopBuilder*. +
→ Die Content-Manager-Ansicht des ShopBuilders wird geöffnet.
. Klicke in der Zeile des Inhalts, den du löschen möchtest, auf die (icon:ellipsis-v[role="darkGrey"])-Schaltfläche, um das Kontextmenü für Inhalte einzublenden.
. Klicke auf *Inhalt löschen*. +
→ Das Fenster *Inhalt löschen* wird geöffnet.
. Klicke auf die Schaltfläche *Löschen*. +
→ Der Inhalt wird gelöscht. +
→ Die Meldung *Die Seite wurde erfolgreich gelöscht* wird angezeigt.

[#inhalte-umbenennen]
==== Inhalte im ShopBuilder umbenennen

Du kannst Inhalte im ShopBuilder jederzeit umbenennen.

[.instruction]
Inhalt umbenennen:

. Öffne das Menü *CMS » ShopBuilder*. +
→ Die Content-Manager-Ansicht des ShopBuilders wird geöffnet.
. Klicke in der Zeile des Inhalts, den du umbenennen möchtest, auf die (icon:ellipsis-v[role="darkGrey"])-Schaltfläche, um das Kontextmenü für Inhalte einzublenden.
. Klicke auf *Inhalt umbenennen*. +
→ Das Fenster *Inhalt: "Inhaltsname" umbenennen* wird geöffnet.
. Gib einen *Namen* ein.
. Klicke auf die Schaltfläche *OK*. +
→ Der Inhalt wird umbenannt. +
→ Die Meldung *Inhalt umbenannt* wird angezeigt.

[#inhalt-duplizieren]
==== Inhalte duplizieren

In der Content-Manager-Ansicht des ShopBuilders können erstellte Inhalte dupliziert werden. Dadurch kannst du schnell kleine, saisonabhängige Änderungen an deinen Inhalten vornehmen und Inhalte in andere Plugin-Sets,  weitere Sprachen oder in andere Kategorien kopieren.

[.instruction]
Inhalt duplizieren:

. Öffne das Menü *CMS » ShopBuilder*. +
→ Die Content-Manager-Ansicht des ShopBuilders wird geöffnet.
. Klicke in der Zeile des Inhalts, den du duplizieren möchtest, auf die (icon:ellipsis-v[role="darkGrey"])-Schaltfläche, um das Kontextmenü für Inhalte einzublenden.
. Klicke auf *Duplizieren*. +
→ Das Fenster *Inhalt duplizieren* wird geöffnet.
. Gib einen *Namen* ein. Standardmäßig ist der Name des ursprünglichen Inhalts mit dem Suffix "(Kopie)" ausgefüllt.
. Wähle eine *Zielsprache*, ein *Ziel-Plugin-Set* und eine *Zielkategorie*, in die der Inhalt kopiert werden soll.
. Hake das Kästchen *Inhalt aktivieren* an, falls die Kopie direkt aktiviert werden soll. _Hinweis_: Dadurch kann ein anderer überschrieben werden.
. Klicke auf die Schaltfläche *Duplizieren*. +
→ Der Inhalt wird dupliziert. +
→ Die Meldung *Inhalt dupliziert* wird angezeigt.

[#inhalt-wiederherstellen]
==== Ältere Version eines Inhalts wiederherstellen

Du kannst deinen Inhalt jederzeit auf eine ältere Version zurücksetzen.
In der Übersicht der älteren Versionen des Inhalts wird die aktuell aktive Version immer an oberster Stelle angezeigt.
Die *Zurücksetzen*-Schaltfläche ist für die aktive Version ausgegraut.

[.instruction]
Inhalt zurücksetzen:

. Öffne das Menü *CMS » ShopBuilder*. +
→ Die Content-Manager-Ansicht des ShopBuilders wird geöffnet.
. Klicke in der Zeile des Inhalts, den du zurücksetzen möchtest, auf die (icon:ellipsis-v[role="darkGrey"])-Schaltfläche, um das Kontextmenü für Inhalte einzublenden.
. Klicke auf *Ältere Version wiederherstellen*. +
→ Das Fenster *Inhalt auf älteren Stand zurücksetzen* wird geöffnet.
. Klicke in der Zeile der Inhaltsversion, die du wiederherstellen willst, auf *Zurüksetzen* (icon:undo[role="darkGrey"]). +
→ Der Inhalt wird auf die gewählte Version zurückgesetzt. +
→ Die Meldung *Inhalt wurde erfolgreich wiederhergestellt* wird angezeigt.



// hier wird's wieder spannend
// neuer Screenshot?
// brauchen wir dieses Kapitel auf dieser Ebene? Was kann ich hier erklären=
// widgets reinziehen / widget einstellungen