= CRM
:keywords: Kundendaten, Kontaktdaten, Ticketsystem, E-Mails, Emails, EmailBuilder, Newsletter, Schnellsuche, Messenger, Nachrichten, Firmen, Firma, Adressdaten, Adressen
:description: Erfahre, wie du im CRM-Bereich von plentymarkets Kontakt-, Firmen- und Adressdaten verwaltest und die Kommunikation mit deinen Kund:innen steuerst.
:author: team-crm

In diesem Themenbereich findest du alle Informationen zum xref:crm:kontakt-erstellen.adoc#[Erstellen] und xref:crm:kontakt-bearbeiten.adoc#[Bearbeiten] von Kontaktdatensätzen – von der Adresse über Aufträge bis hin zu Eigenschaften, Dokumenten u.v.m. +
Erstelle xref:crm:vorbereitende-einstellungen.adoc#kundenklasse-erstellen[Kundenklassen] und xref:crm:vorbereitende-einstellungen.adoc#typ-erstellen[Typen] und nutze das xref:crm:vorbereitende-einstellungen.adoc#rabattsystem-nutzen[Rabattsystem] in plentymarkets. Verwalte deine xref:crm:firmen.adoc#[Firmen] und verknüpfe Kontakte mit den Firmen.

Über die xref:crm:schnellsuche.adoc#[Schnellsuche] kannst du alle Informationen eines Kontakts oder die Adressdaten einer Gastbestellung auf einen Blick aufrufen. In diesem Bereich kannst du außerdem DSGVO-gemäß alle Daten zu einem Kontakt oder einer Gastbestellung herunterladen und Datensätze anonymisieren.

Nutze den xref:crm:messenger-testphase.adoc#[Messenger], um Nachrichten zu erstellen, die deinen Kontakten zugeordnet werden. Diese Nachrichten sind nur in deinem plentymarkets Backend sichtbar und können nicht von deinen Kontakten aufgerufen werden.

Alle E-Mails, die über plentymarkets versendet werden, basieren auf E-Mail-Vorlagen. Erfahre, wie du xref:crm:e-mails-versenden.adoc#1200[E-Mail-Vorlagen erstellst] und wie du den xref:crm:e-mails-versenden.adoc#2300[automatischen Versand] für deine E-Mail-Vorlagen einrichtest. Nutze den xref:crm:emailbuilder-testphase.adoc#[neuen EmailBuilder], um deine Vorlagen noch schneller und intuitiver zu erstellen.

Erfahre außerdem, wie du das xref:crm:ticketsystem-nutzen.adoc#[Ticketsystem] für deine Kundenkommunikation nutzt und wie du mit Hilfe der xref:crm:op-liste.adoc#[OP-Liste] die Kontrolle über noch unbezahlte Aufträge behältst.

Richte einen xref:crm:newsletter-versenden.adoc#[Newsletter]-Dienst in deinem System ein, um deine Kund:innen in regelmäßigen Abständen automatisch über Neuerungen in deinem Webshop zu informieren.

[.row]
====
[.col-md-6]
.Kontakte und Firmen verwalten
======
* xref:crm:vorbereitende-einstellungen.adoc#kundenklasse-erstellen[Kundenklasse erstellen]
* xref:crm:vorbereitende-einstellungen.adoc#typ-erstellen[Typ erstellen]
* xref:crm:kontakt-erstellen.adoc#[Kontakt erstellen]
* xref:crm:kontakt-bearbeiten.adoc#[Kontakt bearbeiten]
* xref:crm:vorbereitende-einstellungen.adoc#rabattsystem-nutzen[Rabattsystem nutzen]
* xref:crm:op-liste.adoc#[Offene Posten anzeigen]
* xref:crm:firmen.adoc#[Firmen verwalten]
======

[.col-md-6]
.E-Mails versenden
======
* xref:crm:e-mails-versenden.adoc#100[E-Mail-Server-Zugangsdaten speichern]
* xref:crm:e-mails-versenden.adoc#200[Verschlüsselung der E-Mail-Kommunikation wählen]
* xref:crm:e-mails-versenden.adoc#1200[E-Mail-Vorlage erstellen]
* xref:crm:emailbuilder-testphase.adoc#[E-Mail-Vorlage mit dem neuen EmailBuilder erstellen]
======
====

[.row]
====
[.col-md-6]
.Ticketsystem nutzen
======
* xref:crm:ticketsystem-nutzen.adoc#700[Rolle hinzufügen]
* xref:crm:ticketsystem-nutzen.adoc#800[Typ hinzufügen]
* xref:crm:ticketsystem-nutzen.adoc#900[Status hinzufügen]
* xref:crm:ticketsystem-nutzen.adoc#1100[Thema hinzufügen]
* xref:crm:ticketsystem-nutzen.adoc#1600[Ticket erstellen]
======

[.col-md-6]
.Newsletter einrichten
======
* xref:crm:newsletter-versenden.adoc#[Newsletter versenden]
======
====

[.row]
====
[.col-md-6]
.Datensätze finden
======
* xref:crm:schnellsuche.adoc#[Schnellsuche verwenden]
======

[.col-md-6]
.Nachrichten verwalten
======
* xref:crm:messenger-testphase.adoc#[Messenger verwenden]
======
====
