= CRM
:keywords: Kundendaten, Kontaktdaten, Ticketsystem, E-Mails, Emails, EmailBuilder, Newsletter, Messenger, Nachrichten, Firmen, Firma, Adressdaten, Adressen
:description: Erfahre, wie du im CRM-Bereich von plentysystems Kontakt-, Firmen- und Adressdaten verwaltest und die Kommunikation mit deinen Kund:innen steuerst.
:author: team-crm

In diesem Themenbereich findest du alle Informationen zum xref:crm:kontakt-erstellen.adoc#[Erstellen] und xref:crm:kontakt-bearbeiten.adoc#[Bearbeiten] von Kontaktdatensätzen – von der Adresse über Aufträge bis hin zu Eigenschaften, Dokumenten u.v.m. +
Erstelle xref:crm:vorbereitende-einstellungen.adoc#kundenklasse-erstellen[Kundenklassen] und xref:crm:vorbereitende-einstellungen.adoc#typ-erstellen[Typen] und nutze das xref:crm:vorbereitende-einstellungen.adoc#rabattsystem-nutzen[Rabattsystem] in plentysystems. Verwalte deine xref:crm:firmen.adoc#[Firmen] und verknüpfe Kontakte mit den Firmen.

Im Menü *CRM » Kontakte* kannst du alle Informationen eines xref:crm:kontakte.adoc#[Kontakts oder die Adressdaten einer Gastbestellung] auf einen Blick aufrufen. In diesem Bereich kannst du außerdem DSGVO-gemäß xref:crm:kontakt-bearbeiten.adoc#alle-daten-herunterladen[alle Daten zu einem Kontakt oder einer Gastbestellung herunterladen],  xref:crm:kontakt-bearbeiten.adoc#[Datensätze anonymisieren] und xref:crm:kontakt-bearbeiten.adoc#gastzugang-umwandeln[plentyShop- und Marktplatz-Gastbestellungen in Kontaktdatensätze umwandeln].

Nutze den xref:crm:messenger-testphase.adoc#[Messenger] für den E-Mail-Versand und E-Mail-Empfang in plentysystems oder erstelle interne Nachrichten, die nur in deinem plentysystems Backend sichtbar und nicht von deinen Kontakten aufgerufen werden können.

Alle E-Mails, die über plentysystems versendet werden, basieren auf E-Mail-Vorlagen. Erfahre, wie du mit dem xref:crm:emailbuilder-testphase.adoc#[EmailBuilder] deine Vorlagen schnell und intuitiv erstellst.

Erfahre außerdem, wie du das xref:crm:ticketsystem-nutzen.adoc#[Ticketsystem] für deine Kundenkommunikation nutzt und wie du mit Hilfe der xref:crm:op-liste.adoc#[OP-Liste] die Kontrolle über noch unbezahlte Aufträge behältst.

// Richte einen xref:crm:newsletter-versenden.adoc#[Newsletter]-Dienst in deinem System ein, um deine Kund:innen in regelmäßigen Abständen automatisch über Neuerungen in deinem Webshop zu informieren.
