= E-Mail-Versand automatisieren
:keywords: Automatischen E-Mail-Versand einrichten, E-Mail-Konten Assistent, Ereignisaktion einrichten, Assistent für E-Mail-Versand, E-Mail-Versand an mehrere E-Mail-Adressen einrichten
:description: Erfahre, wie du den E-Mail-Versand an deine Kund:innen automatisierst.
:page-pagination:
:author: team-crm

In plentysystems stehen dir mehrere Möglichkeiten zur Verfügung, den E-Mail-Versand an deine Kund:innen zu automatisieren.

* <<#automatischer-e-mail-versand, Automatischen E-Mail-Versand einrichten>>
* <<#ereignisaktionen-einrichten, Ereignisaktionen einrichten>>
* <<#e-mail-versand-an-mehrere-e-mail-adressen, E-Mail-Versand an mehrere E-Mail-Adressen einrichten>>

[IMPORTANT]
.Verwendung der Vorlage einsehen
====
Mit einem Klick auf material:assessment[] *Verwendung der Vorlage* innerhalb der Vorlage kannst du sehen, in welchem Bereich deines Systems die EmailBuilder-Vorlage verwendet wird. Weitere Informationen findest du auf der Handbuchseite xref:crm:emailbuilder-mit-dem-emailbuilder-arbeiten.adoc#verwendung-der-vorlage[Mit dem EmailBuilder arbeiten].
====

[#automatischer-e-mail-versand]
== Automatischen E-Mail-Versand einrichten

Den automatischen Versand richtest du im Assistenten *E-Mail-Konten* ein. Der Assistent steht dir im Menü *Einrichtung » Mandant » Global » E-Mail-Konten* zur Verfügung. +
Dort verknüpfst du verschiedene Ereignisse mit bereits erstellten xref:crm:emailbuilder-mit-dem-emailbuilder-arbeiten.adoc#vorlage-erstellen[Vorlagen].

Welche Ereignisse verfügbar sind, erfährst du auf der Handbuchseite xref:crm:emailbuilder-vorbereitende-einstellungen.adoc#e-mail-automatischer-versand[Vorbereitende Einstellungen vornehmen].

[#ereignisaktionen-einrichten]
== Ereignisaktionen einrichten

Neben dem <<#automatischer-e-mail-versand, Verknüpfen von Ereignissen und Vorlagen>> hast du außerdem die Möglichkeit, Ereignisaktionen im Menü *Einrichtung » Aufträge » Ereignisse* einzurichten. Definiere ein Ereignis, setze einen oder mehrere Filter und lege Aktionen fest, die von deinem System automatisch im Ereignisfall ausgeführt werden.

Richte z.B. ein, dass der E-Mail-Versand eines Gutscheins ausgelöst wird, wenn eine Person eine bestimmte Anzahl an Aufträgen generiert hat oder wenn diese Person einer anderen Klasse zugewiesen wurde. Weitere Informationen findest du auf der Handbuchseite xref:automatisierung:ereignisaktionen.adoc#[Ereignisaktionen].

[#e-mail-versand-an-mehrere-e-mail-adressen]
== E-Mail-Versand an mehrere E-Mail-Adressen einrichten

Im Menü *Einrichtung » Aufträge » Ereignisse* kannst du eine xref:automatisierung:ereignisaktionen.adoc#[Ereignisaktion] einrichten, die bei Eintritt des von dir gewählten Ereignisses in deinem plentyShop eine E-Mail an deine Kund:innen und Mitarbeiter:innen versendet.

Füge in der Ereignisaktion die Aktion *Kunde > E-Mail versenden* hinzu und wähle dann dort die passende Vorlage sowie die Empfänger:innen, um die E-Mail bei Eintritt des gewählten Ereignisses zeitgleich an mehrere Empfänger:innen zu versenden.

Die folgenden Empfänger:innen stehen zur Verfügung:

* Kunde
* Lager
* Rechnungsadresse aus Auftrag
* Lieferadresse aus Auftrag
* Kontakt E-Mail geschäftlich
* Kontakt E-Mail privat
* Kontakt E-Mail PayPal
* verfügbare Eigner

Du kannst entweder die selbe Vorlage an alle Empfänger:innen senden oder jeweils eine separate Vorlage wählen.
