= E-Mail-Versand automatisieren
:keywords: Automatischen E-Mail-Versand einrichten, E-Mail-Konten Assistent, Ereignisaktion einrichten, Assistent für E-Mail-Versand, E-Mail-Versand an mehrere E-Mail-Adressen einrichten
:description: Erfahre, wie du den E-Mail-Versand an deine Kund:innen automatisierst.
:page-pagination:
:author: team-crm

In plentysystems stehen dir mehrere Möglichkeiten zur Verfügung, den E-Mail-Versand an deine Kund:innen zu automatisieren:

* <<#automatischer-e-mail-versand, Automatischen E-Mail-Versand einrichten>>
* <<#ereignisaktionen-einrichten, Ereignisaktionen einrichten>>
* <<#e-mail-versand-an-mehrere-e-mail-adressen, E-Mail-Versand an mehrere E-Mail-Adressen einrichten>>

[IMPORTANT]
.Verwendung der Vorlage einsehen
====
Mit einem Klick auf material:assessment[] *Verwendung der Vorlage* innerhalb der Vorlage kannst du sehen, in welchem Bereich deines Systems die EmailBuilder-Vorlage verwendet wird. Die folgenden Filter stehen zur Verfügung:

* E-Mail-Konten-Assistent - Automatischer Versand
* Messenger-Posteingang
* Messenger-Automatisierung
* Auftragsereignis
* Auftragsaktion
* Prozess

Weitere Informationen findest du auf der Handbuchseite xref:crm:emailbuilder-mit-dem-emailbuilder-arbeiten.adoc#verwendung-der-vorlage[Mit dem EmailBuilder arbeiten].
====

[#automatischer-e-mail-versand]
== Automatischen E-Mail-Versand einrichten

Den automatischen Versand richtest du im Assistenten *E-Mail-Konten* ein. Der Assistent steht dir im Menü *Einrichtung » Mandant » Global » E-Mail-Konten* zur Verfügung. +
Dort verknüpfst du verschiedene Ereignisse mit bereits erstellten xref:crm:emailbuilder-mit-dem-emailbuilder-arbeiten.adoc#vorlage-erstellen[Vorlagen].

Welche Ereignisse verfügbar sind, erfährst du auf der Handbuchseite xref:crm:emailbuilder-vorbereitende-einstellungen.adoc#e-mail-automatischer-versand[Vorbereitende Einstellungen vornehmen].

[#ereignisaktionen-einrichten]
== Ereignisaktionen einrichten

Neben dem <<#automatischer-e-mail-versand, Verknüpfen von Ereignissen und Vorlagen>> hast du außerdem die Möglichkeit, Ereignisaktionen im Menü *Einrichtung » Aufträge » Ereignisse* einzurichten. Definiere ein Ereignis, setze einen oder mehrere Filter und lege Aktionen fest, die von deinem System automatisch im Ereignisfall ausgeführt werden.

Richte z.B. ein, dass der E-Mail-Versand eines Gutscheins ausgelöst wird, wenn eine Person eine bestimmte Anzahl an Aufträgen generiert hat oder wenn diese Person einer anderen Klasse zugewiesen wurde. Weitere Informationen findest du auf der Handbuchseite xref:automatisierung:ereignisaktionen.adoc#[Ereignisaktionen].

[#e-mail-versand-an-mehrere-e-mail-adressen]
== E-Mail-Versand an mehrere E-Mail-Adressen einrichten

Im Menü *Einrichtung » Aufträge » Ereignisse* kannst du eine xref:automatisierung:ereignisaktionen.adoc#[Ereignisaktion] einrichten, die bei Eintritt des von dir gewählten Ereignisses in deinem plentyShop eine E-Mail an deine Kund:innen und Mitarbeiter:innen versendet.

Füge in der Ereignisaktion die Aktion *Kunde > E-Mail versenden* hinzu und wähle dann dort die passende Vorlage sowie die Empfänger:innen, um die E-Mail bei Eintritt des gewählten Ereignisses zeitgleich an mehrere Empfänger:innen zu versenden.

Die folgenden Empfänger:innen stehen zur Verfügung:

* Kunde
* Lager
* Rechnungsadresse aus Auftrag
* Lieferadresse aus Auftrag
* Kontakt E-Mail geschäftlich
* Kontakt E-Mail privat
* Kontakt E-Mail PayPal
* verfügbare Eigner

Du kannst entweder die selbe Vorlage an alle Empfänger:innen senden oder jeweils eine separate Vorlage wählen.

[#e-mail-service-nutzen]
== E-Mail-Service nutzen

Über den E-Mail-Service kannst du ganz gezielt E-Mail-Vorlagen manuell versenden. Den E-Mail-Service kannst du in den folgenden Bedienoberflächen nutzen:

* im Menü *Aufträge » Aufträge*
** <<#e-mail-service-im-auftrag, im Auftrag>> selbst
** über die Gruppenfunktion in der <<e-mail-service-auftragsuebersicht-gruppenfunktion, Auftragsübersicht>>
* über die Gruppenfunktion in der <<e-mail-service-kontaktuebersicht-gruppenfunktion, Kontaktübersicht>> im Menü *CRM » Kontakte*

// * im Menü *CRM » Messenger*
// ** in einer neuen Konversation
// ** in der Antwortnachricht

[#filteroptionen-e-mail-service]
=== Filteroptionen im E-Mail-Service

In <<#table-emailbuilder-filter-options-email-service>> siehst du die vorhandenen Filteroptionen im E-Mail-Service.

[[table-emailbuilder-filter-options-email-service]]
.Filteroptionen im E-Mail-Service
[cols="1,3"]
|====
|Filter |Erläuterung

| *Eigner*
|Wähle einen Eigner aus der Liste, um nur Vorlagen anzuzeigen, die diesem Eigner zugewiesen sind.

| *Mandant*
|Wähle einen Mandanten aus der Liste, um nur Vorlagen anzuzeigen, die diesem Mandant zugewiesen sind.

| *ID*
|Gib die ID der Vorlage ein, um nur die Vorlage mit genau dieser ID anzuzeigen.

| *Name*
|Gib den Namen der Vorlage ein, um nur die Vorlage mit genau diesem Namen anzuzeigen. +
Du kannst auch nach Teilen des Namens suchen.

| *Sortieren nach*
| Wähle eine Option aus der Liste, um festzulegen, nach welchen Kriterien die gefundenen Vorlagen sortiert werden sollen. +
Verfügbare Optionen: *Erstelldatum*, *ID*, *Name*.

| *Sortierreihenfolge*
| Wähle, ob die gefundenen Vorlagen aufsteigend oder absteigend anhand des Erstelldatums, der ID oder des Namens angezeigt werden sollen.

|====

[#aktuellen-filter-speichern]
=== Aktuellen Filter speichern

Wenn du eine Suche im E-Mail-Service ausführst, siehst du deine gewählten Filter oben als so genannte "Chips" dargestellt. Diese Filter kannst du speichern, um sie in Zukunft schneller und einfacher wieder verwenden zu können.

[.instruction]
Aktuellen Filter speichern: 

. Führe eine Suche aus.
. Klicke auf *Gespeicherte Filter* (material:bookmarks[]).
. Klicke auf material:bookmark_border[] *Aktuellen Filter speichern*.
. Gib einen Namen für den Filter ein.
. Entscheide, ob
** dieser <<#filter-als-standard, Filter als Standard>> festgelegt werden soll (material:toggle_on[role=skyBlue])
** dieser Filter für alle Benutzer:innen erstellt werden soll (material:toggle_on[role=skyBlue]).
. Klicke auf *SPEICHERN*. +
→ Der Filter erscheint nun unter *Gespeicherte Filter* (material:bookmarks[]).

[TIP]
Lege die Reihenfolge der Filter per Drag-and-drop mit einem Klick auf *Verschieben* (material:drag_indicator[]) fest. Klicke auf material:delete[], um einen Filter zu löschen.

[#gespeicherte-filter-anwenden]
=== Gespeicherte Filter anwenden

Gehe wie im Folgenden vor, um einen gespeicherten Filter in der Suche anzuwenden.

[.instruction]
Gespeicherte Filter anwenden: 

. Klicke auf *Gespeicherte Filter* (material:bookmarks[]).
. Klicke auf einen bereits erstellten Filter. +
→ Die Suche wird ausgeführt und die verwendeten Filtereinstellungen werden oben als so genannte "Chips" dargestellt.

[#filter-als-standard]
=== Filter als Standard festlegen

Damit du einen häufig verwendeten Filter nicht jedes Mal beim Öffnen des E-Mail-Service erst aus der Liste deiner <<#gespeicherte-filter-anwenden, gespeicherten Filter>> wählen musst, kannst du einen erstellten Filter als Standard festlegen. Jedes Mal, wenn du den E-Mail-Service öffnest, wird dieser Filter dann also automatisch ausgeführt.

Du kannst einen Filter direkt beim Erstellen als Standard festlegen wie im Kapitel <<#aktuellen-filter-speichern, Aktuellen Filter speichern>> beschrieben oder du legst den Filter nachträglich aus der Übersicht heraus als Standard fest.

Klicke in der Zeile des gespeicherten Filters auf material:star_border[] *Als Standard festlegen*. Wenn du einen anderen Filter als Standard festlegen möchtest, deaktiviere den aktuell gewählten Standardfilter mit einem Klick auf material:star[] *Nicht als Standard verwenden*.

[#e-mail-service-im-auftrag]
=== E-Mail-Service im Auftrag nutzen

Du kannst den E-Mail-Service sowohl <<#e-mail-vorlage-ueber-e-mail-service-versenden, im Auftrag selbst>> als auch über die <<#e-mail-service-auftragsuebersicht-gruppenfunktion, Gruppenfunktion in der Auftragsübersicht>> nutzen. Außerdem kannst du die bereits gesendeten E-Mail-Vorlagen über die <<#gesendete-e-mail-vorlagen-auftrag, Historie>> ansehen.

[#e-mail-vorlage-ueber-e-mail-service-versenden]
==== E-Mail-Vorlage über den E-Mail-Service im Auftrag versenden 

Im Auftrag im Menü *Aufträge » Aufträge* kannst du über die Schaltfläche material:email[] (*E-Mail-Service*) zum einen gezielt E-Mail-Vorlagen versenden und zum anderen die bereits versendeten E-Mail-Vorlagen in der Historie einsehen.

Gehe wie im Folgenden beschrieben vor, um eine E-Mail-Vorlage über den E-Mail-Service im Auftrag zu nutzen.

[.instruction]
E-Mail-Vorlage über den E-Mail-Service im Auftrag versenden:

. Öffne das Menü *Aufträge » Aufträge*.
. Suche den Auftrag anhand der Filtereinstellungen. Beachte dazu die Erläuterungen zu den Filtern auf der Seite xref:auftraege:order-search.adoc#[Aufträge suchen]. +
→ Die Aufträge, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicke auf die Auftrags-ID, um den Datensatz zu öffnen.
. Klicke oben in der Symbolleiste auf material:email[] (*E-Mail-Service*). +
→ Das Fenster *E-Mail-Service* öffnet sich.
. Wähle im Bereich *Vorlagen* eine Option aus der Dropdown-Liste *Empfängertyp*.
. Wähle eine Sprache aus der Dropdown-Liste *Vorlagensprache*. +
→ *_Hinweis:_* Hier ist die Sprache aus dem Auftrag automatisch vorausgewählt.
. Nutze die Filter, um nach der passenden EmailBuilder-Vorlage zu suchen. Beachte die Erläuterungen zu den Filtern im Unterkapitel <<#filteroptionen-e-mail-service, Filteroptionen im E-Mail-Service>>. +
→ Die Vorlagen, die den eingestellten Suchkriterien entsprechen, werden angezeigt. Beziehungsweise: Die Ordner, die die Vorlagen mit den eingestellten Suchkriterien enthalten, werden angezeigt.
. Klicke auf die Vorlage.
. Klicke auf der rechten Seite im Bereich *Vorschau* auf material:preview[] *VORLAGE LADEN*, um die Vorschau der Vorlage anzuzeigen. +
*_Hinweis:_* Außerdem wird das E-Mail-Konto, die Empfänger:in, der Betreff und falls vorhanden die Anhänge angezeigt. +
*_Tipp:_* Klicke neben der Empfänger:in auf material:more_vert[], um die Felder *CC* und *BCC* hinzuzufügen.
. Falls gewünscht, füge weitere Anhänge hinzu, indem du auf material:attach_file[] klickst.
. Klicke auf material:send[] *SENDEN*, um die Vorlage an die eingegebenen Empfänger:innen zu versenden.

[#gesendete-e-mail-vorlagen-auftrag]
==== Gesendete E-Mail-Vorlagen im Auftrag ansehen

Über die Historie im E-Mail-Service kannst du alle zu einem Auftrag gesendeten E-Mail-Vorlagen ansehen.

[.instruction]
Gesendete E-Mail-Vorlagen im Auftrag ansehen:

. Öffne das Menü *Aufträge » Aufträge*.
. Suche den Auftrag anhand der Filtereinstellungen. Beachte dazu die Erläuterungen zu den Filtern auf der Seite xref:auftraege:order-search.adoc#[Aufträge suchen]. +
→ Die Aufträge, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicke auf die Auftrags-ID, um den Datensatz zu öffnen.
. Klicke oben in der Symbolleiste auf material:email[] (*E-Mail-Service*). +
→ Das Fenster *E-Mail-Service* öffnet sich.
. Wechsele in das Tab *Historie*. +
→ Dort siehst du in der Versandhistorie den Typ, die Auftrags-ID, Datum und Uhrzeit, wann die Vorlage versendet wurde, die Empfänger:in, den Vorlagennamen und die Vorlagen-ID.

[#e-mail-service-auftragsuebersicht-gruppenfunktion]
=== E-Mail-Service über die Gruppenfunktion in der Auftragsübersicht nutzen

Gehe wie im Folgenden beschrieben vor, um eine E-Mail-Vorlage über die Gruppenfunktion in der Auftragsübersicht zu versenden.

[.instruction]
E-Mail-Service über die Gruppenfunktion in der Auftragsübersicht nutzen:

. Öffne das Menü *Aufträge » Aufträge*.
. Suche die Aufträge anhand der Filtereinstellungen. Beachte dazu die Erläuterungen zu den Filtern auf der Seite xref:auftraege:order-search.adoc#[Aufträge suchen]. +
→ Die Aufträge, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Wähle (material:check_box[role=skyBlue]) die Aufträge, für die du eine E-Mail-Vorlage versenden möchtest.
. Klicke oben in der Symbolleiste auf material:email[] (*E-Mail versenden*). +
→ Das Fenster *E-Mail-Service* öffnet sich. +
→ Im Bereich *Vorlagen* siehst du die Auftrags-IDs, die du gerade gewählt hast.
. Wähle eine Option aus der Dropdown-Liste *Empfängertyp*.
. Wähle eine Sprache aus der Dropdown-Liste *Vorlagensprache*.
. Nutze die Filter, um nach der passenden EmailBuilder-Vorlage zu suchen. Beachte die Erläuterungen zu den Filtern im Unterkapitel <<#filteroptionen-e-mail-service, Filteroptionen im E-Mail-Service>>. +
→ Die Vorlagen, die den eingestellten Suchkriterien entsprechen, werden angezeigt. Beziehungsweise: Die Ordner, die die Vorlagen mit den eingestellten Suchkriterien enthalten, werden angezeigt.
. Klicke auf die Vorlage.
. Klicke auf material:send[] *SENDEN*.

[#e-mail-service-kontaktuebersicht-gruppenfunktion]
=== E-Mail-Service über die Gruppenfunktion in der Kontaktübersicht nutzen

Gehe wie im Folgenden beschrieben vor, um eine E-Mail-Vorlage über die Gruppenfunktion in der Kontaktübersicht zu versenden.

[.instruction]
E-Mail-Service über die Gruppenfunktion in der Kontaktübersicht nutzen:

. Öffne das Menü *CRM » Kontakte*.
. Suche die Aufträge anhand der Filtereinstellungen. Beachte dazu die Erläuterungen zu den Filtern auf der Seite xref:crm:kontakt-suchen.adoc#[Kontakt suchen]. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Wähle (material:check_box[role=skyBlue]) die Kontakte, an die du eine E-Mail-Vorlage versenden möchtest.
. Klicke oben in der Symbolleiste auf material:email[] (*E-Mail-Vorlage senden*). +
→ Das Fenster *E-Mail-Service* öffnet sich. +
→ Im Feld *Empfänger* siehst du die Namen der Kontakte, die du gerade gewählt hast.
. Wähle eine Sprache aus der Dropdown-Liste *Vorlagensprache*.
. Nutze die Filter, um nach der passenden EmailBuilder-Vorlage zu suchen. Beachte die Erläuterungen zu den Filtern im Unterkapitel <<#filteroptionen-e-mail-service, Filteroptionen im E-Mail-Service>>. +
→ Die Vorlagen, die den eingestellten Suchkriterien entsprechen, werden angezeigt. Beziehungsweise: Die Ordner, die die Vorlagen mit den eingestellten Suchkriterien enthalten, werden angezeigt.
. Klicke auf die Vorlage.
. Klicke auf material:send[] *SENDEN*.
