= EmailBuilder
:keywords: EmailBuilder, E-Mail Builder, E-Mail-Vorlagen, Widgets, Emailvorlagen, Dokumentenanhang E-Mail, Email-Vorlagen Baukasten, E-Mail-Variablen, twig expressions, E-Mail-Versand, Code-Widget, Widgets E-Mail-Vorlagen, Variablen
:description: Erfahre, wie du den EmailBuilder in plentysystems verwendest und E-Mail-Vorlagen im Baukastenprinzip mithilfe von Widgets und Variablen erstellst.
:page-aliases: emailbuilder-testphase.adoc, emailbuilder.adoc
:author: team-crm

In diesem Themenbereich findest du alle Informationen rund um den EmailBuilder. +
Alle E-Mails, die du über plentysystems an deine xref:crm:kontakte.adoc#[Kontakte] versendest, basieren auf Vorlagen. Vorlagen erstellst und verwaltest du mit dem EmailBuilder im Menü *CRM » EmailBuilder*.

include::_includes:partial$emailbuilder-uebersicht-menue-aufbau.adoc[]

Schau dir das folgende link:https://www.youtube.com/watch?v=denxnArUsJ0[Video^] an, um mehr über den EmailBuilder zu erfahren.

[TIP]
.E-Mail-Vorlagen werden im Multipart-Format versendet
====
Die E-Mail-Vorlagen im EmailBuilder verwenden das Multipart-Format. Das bedeutet, dass deine E-Mails gleichzeitig in einer HTML- und in einer Textversion versendet werden. +
So sind deine E-Mails für alle Empfänger:innen lesbar, auch wenn deren E-Mail-Client die Anzeige von HTML in E-Mails einschränkt oder ganz unterbindet. Auf der anderen Seite werden die von dir gestalteten HTML-Versionen deiner E-Mail-Vorlagen für die Empfänger:innen angezeigt, deren E-Mail-Client die Darstellung von HTML erlaubt. Der Vorteil für dich hierbei ist, dass du nur eine E-Mail-Vorlage pflegen musst.
====

Der EmailBuilder ist ein Baukastenmodul, mit dem du deine E-Mail-Vorlagen schnell und einfach per Drag-and-drop erstellen und bearbeiten kannst. Der EmailBuilder besteht aus 2 Ansichten: dem Konfigurationsmanager und dem Editor.

* Im Konfigurationsmanager erstellst du Ordner, ggf. Unterordner, Vorlagen sowie Vorlagen für deinen Footer und deinen Header.

* Im Editor befüllst du deine Vorlagen, Header und Footer mit Inhalt. Du kannst zum Beispiel eine Vorlage für eine Rechnung erstellen und diese zukünftig für alle Rechnungen an deine Kund:innen verwenden.

Die Header- und Footer-Vorlagen kannst du dann beliebig in deinen E-Mail-Vorlagen verwenden. Header und Footer sind global wirksam; Änderungen, die du am Header und Footer vornimmst, wirken sich demnach auch auf alle bestehenden Vorlagen sowie weitere Vorlagen, die du zukünftig erstellst, aus.

Erstelle xref:crm:emailbuilder-mit-dem-emailbuilder-arbeiten.adoc#textblock-erstellen[Textblöcke], also fertige Textbausteine, die dir die Arbeit enorm erleichtern, besonders wenn du häufig mit Standardfragen oder Standardproblemen konfrontiert wirst. Du kannst die Textblöcke dann auch im xref:crm:messenger.adoc#textbloecke-verwenden[Messenger] verwenden. 

Um noch flexibler beim Gestalten deiner Vorlagen zu sein, kannst du den xref:crm:emailbuilder-expertenmodus.adoc#[Expertenmodus] verwenden.

Mit dem Header, dem Footer und den Einstellungen in der Vorlage wie Name, Betreff etc. erstellst du sozusagen das Gerüst deiner E-Mail. +
Den Inhalt der Vorlage bildest du mit den xref:crm:emailbuilder-mit-dem-emailbuilder-arbeiten.adoc#widget-einfuegen[Widgets] und xref:crm:emailbuilder-variablen-twig-expressions.adoc#verfuegbare-variablen[Variablen]. Die Variablen werden dann in der E-Mail an deine Kund:innen durch den korrekten Inhalt ersetzt. Zum Beispiel wird die Variable `Lieferadresse Vorname und Nachname` in der E-Mail dann durch den Vornachnamen und Nachnamen des Kontakts aus der Lieferadresse ausgegeben.

Außerdem kannst du einstellen, dass dein System bei bestimmten Ereignissen, z.B. beim Eingehen neuer Bestellungen in deinem plentyShop oder nachdem Kund:innen deinen Newsletter abonniert haben, xref:crm:emailbuilder-e-mail-versand-automatisieren.adoc#[automatisch E-Mails aus diesen Vorlagen] erstellt und an deine Kund:innen versendet.

[discrete]
== Schnellzugriff auf die Unterseiten

Klicke auf einen der folgenden Einträge, um direkt zu der jeweiligen Handbuchseite zu gelangen:

* xref:crm:emailbuilder-vorbereitende-einstellungen.adoc#[Vorbereitenden Einstellungen vornehmen]
* xref:crm:emailbuilder-mit-dem-emailbuilder-arbeiten.adoc#[Mit dem EmailBuilder arbeiten]
* xref:crm:emailbuilder-e-mail-versand-automatisieren.adoc#[E-Mail-Versand automatisieren]
* xref:crm:emailbuilder-expertenmodus.adoc#[Expertenmodus verwenden]
* xref:crm:emailbuilder-variablen-twig-expressions.adoc#[Variablen und twig expressions verwenden]
* xref:crm:emailbuilder-code-beispiele.adoc#[Code-Beispiele]
