= E-Mail-Versand automatisieren
:keywords: Automatischen E-Mail-Versand einrichten, E-Mail-Konten Assistent, Ereignisaktion einrichten, Assistent für E-Mail-Versand, E-Mail-Versand an mehrere E-Mail-Adressen einrichten
:description: Erfahre, wie du den E-Mail-Versand an deine Kund:innen automatisierst.
:page-pagination:
:author: team-crm

In plentysystems stehen dir mehrere Möglichkeiten zur Verfügung, den E-Mail-Versand an deine Kund:innen zu automatisieren:

* <<#automatischer-e-mail-versand, Automatischen E-Mail-Versand einrichten>>
* <<#ereignisaktionen-einrichten, Ereignisaktionen einrichten>>
* <<#e-mail-versand-an-mehrere-e-mail-adressen, E-Mail-Versand an mehrere E-Mail-Adressen einrichten>>

[IMPORTANT]
.Verwendung der Vorlage einsehen
====
Mit einem Klick auf material:assessment[] *Verwendung der Vorlage* innerhalb der Vorlage kannst du sehen, in welchem Bereich deines Systems die EmailBuilder-Vorlage verwendet wird. Die folgenden Filter stehen zur Verfügung:

* E-Mail-Konten-Assistent - Automatischer Versand
* Messenger-Posteingang
* Messenger-Automatisierung
* Auftragsereignis
* Auftragsaktion
* Prozess

Weitere Informationen findest du auf der Handbuchseite xref:crm:emailbuilder-mit-dem-emailbuilder-arbeiten.adoc#verwendung-der-vorlage[Mit dem EmailBuilder arbeiten].
====

[#automatischer-e-mail-versand]
== Automatischen E-Mail-Versand einrichten

Den automatischen Versand richtest du im Assistenten *E-Mail-Konten* ein. Der Assistent steht dir im Menü *Einrichtung » Mandant » Global » E-Mail-Konten* zur Verfügung. +
Dort verknüpfst du verschiedene Ereignisse mit bereits erstellten xref:crm:emailbuilder-mit-dem-emailbuilder-arbeiten.adoc#vorlage-erstellen[Vorlagen].

Welche Ereignisse verfügbar sind, erfährst du auf der Handbuchseite xref:crm:emailbuilder-vorbereitende-einstellungen.adoc#e-mail-automatischer-versand[Vorbereitende Einstellungen vornehmen].

[#ereignisaktionen-einrichten]
== Ereignisaktionen einrichten

Neben dem <<#automatischer-e-mail-versand, Verknüpfen von Ereignissen und Vorlagen>> hast du außerdem die Möglichkeit, Ereignisaktionen im Menü *Einrichtung » Aufträge » Ereignisse* einzurichten. Definiere ein Ereignis, setze einen oder mehrere Filter und lege Aktionen fest, die von deinem System automatisch im Ereignisfall ausgeführt werden.

Richte z.B. ein, dass der E-Mail-Versand eines Gutscheins ausgelöst wird, wenn eine Person eine bestimmte Anzahl an Aufträgen generiert hat oder wenn diese Person einer anderen Klasse zugewiesen wurde. Weitere Informationen findest du auf der Handbuchseite xref:automatisierung:ereignisaktionen.adoc#[Ereignisaktionen].

[#e-mail-versand-an-mehrere-e-mail-adressen]
== E-Mail-Versand an mehrere E-Mail-Adressen einrichten

Im Menü *Einrichtung » Aufträge » Ereignisse* kannst du eine xref:automatisierung:ereignisaktionen.adoc#[Ereignisaktion] einrichten, die bei Eintritt des von dir gewählten Ereignisses in deinem plentyShop eine E-Mail an deine Kund:innen und Mitarbeiter:innen versendet.

Füge in der Ereignisaktion die Aktion *Kunde > E-Mail versenden* hinzu und wähle dann dort die passende Vorlage sowie die Empfänger:innen, um die E-Mail bei Eintritt des gewählten Ereignisses zeitgleich an mehrere Empfänger:innen zu versenden.

Die folgenden Empfänger:innen stehen zur Verfügung:

* Kunde
* Lager
* Rechnungsadresse aus Auftrag
* Lieferadresse aus Auftrag
* Kontakt E-Mail geschäftlich
* Kontakt E-Mail privat
* Kontakt E-Mail PayPal
* verfügbare Eigner

Du kannst entweder die selbe Vorlage an alle Empfänger:innen senden oder jeweils eine separate Vorlage wählen.

[#e-mail-service-im-auftrag]
== E-Mail-Service im Auftrag nutzen

Im Auftrag im Menü *Aufträge » Aufträge* kannst du über die Schaltfläche material:email[] (*E-Mail-Service*) zum einen gezielt E-Mail-Vorlagen versenden und zum anderen die bereits versendeten E-Mail-Vorlagen in der Historie einsehen.

=== E-Mail über den E-Mail-Service versenden

// TODO: Einleitung


[.instruction]
E-Mail über den E-Mail-Service versenden:

. Öffne das Menü *Aufträge » Aufträge*.
. Suche den Auftrag anhand der Filtereinstellungen. Beachte dazu die Erläuterungen zu den Filtern auf der Seite xref:auftraege:order-search.adoc#[Aufträge suchen]. +
→ Die Aufträge, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicke auf die Auftrags-ID, um den Datensatz zu öffnen.
. Klicke oben in der Symbolleiste auf material:email[] (*E-Mail-Service*). +
→ Das Fenster *E-Mail-Service* öffnet sich.
. Wähle im Bereich *Vorlagen* eine Option aus der Dropdown-Liste *Empfängertyp*
. Wähle eine Sprache aus der Dropdown-Liste *Vorlagensprache*.
. Nutze die Filter, um nach der passenden EmailBuilder-Vorlage zu suchen. Beachte die Erläuterungen zu den Filtern im Unterkapitel XXXX. +
→ Die Vorlagen, die den eingestellten Suchkriterien entsprechen, werden angezeigt. Beziehungsweise: Die Ordner, die die Vorlagen mit den eingestellten Suchkriterien enthalten, werden angezeigt.
. Klicke auf die Vorlage.
. Klicke auf der rechten Seite im Bereich *Vorschau* auf material:preview[] *VORLAGE LADEN*, um die Vorschau der Vorlage anzuzeigen. +
*_Hinweis:_* Außerdem wird das E-Mail-Konto, die Empfänger:in, der Betreff und falls vorhanden die Anhänge angezeigt. +
*_Tipp:_* Klicke neben der Empfänger:in auf material:more_vert[], um die Felder *CC* und *BCC* hinzuzufügen.
. Falls gewünscht, füge weitere Anhänge hinzu, indem du auf material:attach_file[] klickst.
. Klicke auf material:send[] *SENDEN*, um die Vorlage an die eingegebenen Empfänger:innen zu versenden.

==== Filteroptionen im E-Mail-Service

[[table-emailbuilder-filter-options-email-service]]
.Filteroptionen im E-Mail-Service
[cols="1,3"]
|====
|Filter |Erläuterung

| *Eigner*
|

| *Mandant*
|

| *ID*
|

| *Name*
|

| *Sortieren nach*
|

| *Sortierreihenfolge*
|

|====

=== Historie

////

Im Menü *Aufträge » Aufträge* hast du über die Schaltfläche *E-Mail-Service* die Möglichkeit, alle E-Mail-Vorlagen, die du an die mit dem Auftrag verknüpften Kontakte versendet hast, anzuzeigen.

Gesendete E-Mail-Vorlagen pro Person anzeigen:

Öffne das Menü Aufträge » Aufträge bearbeiten.

Öffne den Auftrag.

Wechsele in das Tab Mail.

Wechsele in das Tab Gesendete E-Mails.
→ Das Datum, die Uhrzeit, die E-Mail-Adresse, die ID und der Name der Vorlage sowie die Auftrags-ID werden angezeigt.

Klappe den Bereich Weitere an den Kunden gesendete E-Mails…​ auf, um alle E-Mails anzuzeigen, die an diese Person gesendet wurden. Hier werden auch E-Mails angezeigt, die diese Person aus einem anderen Auftrag heraus erhalten hat. Mit einem Klick auf die Auftrags-ID wird die Auftragsübersicht dieses Auftrags in einem separaten Tab geöffnet.
////