= FAQ
:keywords: FAQ CRM
:description: Auf dieser Handbuchseite findest du Fragen und Antworten aus dem Themengebiet CRM.
:author: team-crm

Auf dieser Handbuchseite findest du Fragen und Antworten aus dem Themengebiet CRM. 

// TODO: Datei in nav.adoc einbinden

== Adressen

[#faq-adresse-nicht-loeschen]
[.collapseBox]
.Warum kann ich Adressen nicht löschen?
--
Ein Kunde ruft bei dir an und teilt dir mit, dass sich seine Adresse geändert hat. Du öffnest seinen Kontaktdatensatz, suchst die alte Adresse und möchtest diese löschen. Warum geht das nicht? +
Wenn die Adresse mit einem Auftrag verknüpft ist, ist es _nicht_ möglich, diese Adresse zu löschen. Dies hängt mit der gesetzlichen Aufbewahrungsfrist zusammen.

Um zu vermeiden, dass "alte" Adressen deiner Kontakte fälschlicherweise bei der Auftragsanlage verwendet werden, muss die neue Adresse als primäre Rechnungs- und Lieferadresse gesetzt werden. Danach wird diese neue primäre Adresse standardmäßig in der Auftragsanlage sowohl in deinem plentymarkets Backend als auch in deinem Online-Shop angezeigt.
--

[#faq-adresse-nicht-waehlbar]
[.collapseBox]
.Ich sehe das Land nicht im Kontaktdatensatz. Warum?
--
Du möchtest manuell einen neuen Kontakt anlegen, aber in der Dropdown-Liste *Land* wird das gewünschte Land nicht angezeigt?

Damit das Land in der Dropdown-Liste im Kontaktdatensatz wählbar ist, musst du es zunächst aktivieren. Gehe dazu in das Menü *Einrichtung » Aufträge » Versand » Optionen* » Tab: *Lieferländer*. Suche dort das gewünschte Land und setze es auf material:check_circle[] *Aktiv*.
--

== Gastbestellungen

[#faq-gastbestellung-plentyshop-nicht-auffindbar]
[.collapseBox]
.Ich finde keine Gastbestellungen in der Kontakte-UI. Warum?
--
Um DSGVO-konform zu arbeiten, wird bei Gastbestellungen, die über den plentyShop in dein System kommen, _kein_ Kontaktdatensatz erstellt. Es werden lediglich die Adressdaten aus dem Auftrag gespeichert. Diese Daten, die in deinem plentymarkets System gespeichert werden, können daher _nicht_ über das Menü *CRM » Kontakte* gefunden werden. +
Die Adressdaten der Person, die als Gast in deinem plentyShop bestellt hat, können nur über die Schnellsuche im Menü *CRM » Schnellsuche* gefunden werden.

*_Beachte:_* Anders verhält es sich bei Gastbestellungen, die über Marktplätze in dein System importiert werden, weil in diesen Fällen ein Kontaktdatensatz erstellt wird.

*Gastbestellungen im Menü CRM » Schnellsuche:*

* Bei einer Gastbestellung über deinen plentyShop besteht der gespeicherte Datensatz lediglich aus der Adresse und dem zugehörigen Auftrag. Eine Kontakt-ID wird _nicht_ vergeben. Jedoch wird das Symbol material:done[] in der Übersicht in der Spalte *Gast* angezeigt.

* Bei einer Gastbestellung über einen Marktplatz wird eine Kontakt-ID vergeben und das Symbol material:done[] wird in der Übersicht in der Spalte *Gast* angezeigt.
--

== DSGVO / Daten anonymisieren

[#faq-kundendaten-loeschen]
[.collapseBox]
.Wie lösche ich Kontaktdaten DSGVO-konform?
--
Eine Kundin fordert dich auf, ihre Daten bei dir im System zu löschen. Folgendes ist zu tun: 

* Öffne das Menü *CRM » Schnellsuche*.
* Suche den Datensatz der Kundin und öffne ihn.
* Klicke 

*_Hinweis:_* Wenn die Schaltfläche *Datensatz anonymisieren* in dem Datensatz, den du löschen möchtest, ausgegraut ist, bedeutet das, dass es sich um eine Gastbestellung handelt. In diesem Fall ist die Schaltfläche deaktiviert, weil der Datensatz kein Kontakt ist. Das Löschen bzw. Unkenntlichmachen, damit kein Bezug mehr zu der Person hergestellt werden, ist _nicht_ nötig. 
--

[#faq-daten-anonymisieren]
[.collapseBox]
.Wie anonymisiere ich Kontaktdaten?
--
Text
--

[#faq-anonymisieren-button-kontakte]
[.collapseBox]
.Ich finde den Button zum Anonymisieren der Kund:innendaten nicht. Wo ist er?
--
Text
--

== E-Mail-Vorlagen