= FAQ: CRM
:keywords: FAQ CRM, Fragen und Antworten CRM
:description: Auf dieser Handbuchseite findest du Fragen und Antworten aus dem Themengebiet CRM.
:author: team-crm

Auf dieser Handbuchseite findest du Fragen und Antworten aus dem Themengebiet CRM. Wir werden diese Liste kontinuierlich um weitere Fragen und Antworten ergänzen.

[#faq-bereich-adressen]
== Adressen

[#faq-adresse-nicht-loeschen]
[.collapseBox]
.Warum kann ich Adressen nicht löschen?
--
Ein Kunde ruft bei dir an und teilt dir mit, dass sich seine Adresse geändert hat. Du öffnest seinen Kontaktdatensatz, suchst die alte Adresse und möchtest diese löschen. Warum geht das nicht? +
Wenn die Adresse mit einem Auftrag verknüpft ist, ist es _nicht_ möglich, diese Adresse zu löschen. Dies hängt mit der gesetzlichen Aufbewahrungsfrist gemäß GoBD zusammen.

Um zu vermeiden, dass "alte" Adressen deiner Kontakte fälschlicherweise bei der manuellen Auftragsanlage verwendet werden, muss die neue Adresse als primäre Rechnungs- und Lieferadresse gesetzt werden. Danach wird diese neue primäre Adresse standardmäßig in der Auftragsanlage in deinem plentymarkets Backend angezeigt.

*_Hinweis:_* Dein Kunde kann in seinem Mein Konto-Bereich die alte Adresse löschen bzw. bestehende Adressen bearbeiten. Diese Adressen werden dann aber nicht komplett entfernt bzw. mit deinem plentymarkets Backend synchronisiert und sind nach wie vor in deinem plentymarkets System sichtbar.
--

[#faq-adresse-nicht-waehlbar]
[.collapseBox]
.Ich sehe das Land nicht im Kontaktdatensatz. Warum?
--
Du möchtest manuell einen neuen Kontakt anlegen, aber in der Dropdown-Liste *Land* wird das gewünschte Land nicht angezeigt?

Damit das Land in der Dropdown-Liste im Kontaktdatensatz wählbar ist, musst du es zunächst aktivieren. Gehe dazu in das Menü *Einrichtung » Aufträge » Versand » Optionen* » Tab: *Lieferländer*. Suche dort das gewünschte Land und setze es auf material:check_circle[] *Aktiv*.
--

[#faq-bereich-gastbestellungen]
== Gastbestellungen

[#faq-gastbestellung-plentyshop-nicht-auffindbar]
[.collapseBox]
.Ich finde keine Gastbestellungen in der Kontakte-UI. Warum?
--
Um DSGVO-konform zu arbeiten, wird bei Gastbestellungen, die über den plentyShop in dein System kommen, _kein_ Kontaktdatensatz erstellt. Es werden lediglich die Adressdaten aus dem Auftrag gespeichert. Diese Daten, die in deinem plentymarkets System gespeichert werden, können daher _nicht_ über das Menü *CRM » Kontakte* gefunden werden. +
Die Adressdaten der Person, die als Gast in deinem plentyShop bestellt hat, können nur über die Schnellsuche im Menü *CRM » Schnellsuche* gefunden werden.

*_Beachte:_* Anders verhält es sich bei Gastbestellungen, die über Marktplätze in dein System importiert werden, weil in diesen Fällen ein Kontaktdatensatz erstellt wird.

*Gastbestellungen im Menü CRM » Schnellsuche:*

* Bei einer Gastbestellung über deinen plentyShop besteht der gespeicherte Datensatz lediglich aus der Adresse und dem zugehörigen Auftrag. Eine Kontakt-ID wird _nicht_ vergeben. Jedoch wird das Symbol material:done[] in der Übersicht in der Spalte *Gast* angezeigt.

* Bei einer Gastbestellung über einen Marktplatz wird eine Kontakt-ID vergeben und das Symbol material:done[] wird in der Übersicht in der Spalte *Gast* angezeigt.
--

[#faq-bereich-dsgvo-anonymisieren]
== DSGVO / Kundendaten anonymisieren und löschen

[#faq-kundendaten-loeschen]
[.collapseBox]
.Wie lösche ich Kontaktdaten DSGVO-konform?
--
Eine Kundin fordert dich auf, ihre Daten bei dir im System zu löschen. Daher bist du gemäß DSGVO verpflichtet, die Daten der Kundin zu löschen bzw. unkenntlich zu machen. Folgendes ist zu tun: 

* Öffne das Menü *CRM » Schnellsuche*.
* Suche den Datensatz der Kundin und öffne ihn.
* Klicke in der Leiste ganz oben auf icon:user-secret[] (*Datensatz anonymisieren*).
* Ein Fenster öffnet sich. Hier musst du erneut die Kontakt-ID der Kundin eingeben, um das Anonymisieren zu bestätigen. +
*_Wichtig:_* Das Anonymisieren kann _nicht_ rückgängig gemacht werden.
* Klicke auf *Anonymisieren*.

Die folgenden Daten werden anonymisiert:

* Vorname und Nachname des Kontakts

Die folgenden Daten werden gelöscht:

* Adressen und Adressverknüpfungen
* Adressoptionen
* Auftragsverknüpfungen
* Kontaktoptionen
* Verknüpfung zu einer Firma
* Bankdaten
* Bestellbestätigungs-URLs werden ungültig

Informiere im Anschluss die Kundin darüber, dass ihre Daten in deinem System nun gelöscht sind. Erkundige dich im Zweifelsfall bei einem Fachanwalt, wie du diese Nachricht am besten formulierst.

*_Hinweis:_* Wenn die Schaltfläche *Datensatz anonymisieren* in dem Datensatz, den du löschen möchtest, ausgegraut ist, bedeutet das, dass es sich um eine Gastbestellung handelt. In diesem Fall ist die Schaltfläche deaktiviert, weil der Datensatz kein Kontakt ist. Das Löschen bzw. Unkenntlichmachen der Daten, damit kein Bezug mehr zu der Person hergestellt werden kann, ist bei Gastbestellungen _nicht_ nötig. 

Weitere Informationen findest du auf der Handbuchseite xref:crm:schnellsuche.adoc#datensatz-anonymisieren[Schnellsuche].
--

[#faq-anonymisieren-button-kontakte]
[.collapseBox]
.Ich finde den Button zum Anonymisieren der Kund:innendaten nicht. Wo ist er?
--
Möglicherweise befindest du dich im falschen Menü. Das Anonymisieren von Kontaktdaten ist nur über das Menü *CRM » Schnellsuche* möglich, _nicht_ über das Menü *CRM » Kontakte*. 

Weitere Informationen zum Anonymisieren von Kontaktdaten findest du in der Box <<#faq-kundendaten-loeschen, Wie lösche ich Kontaktdaten DSGVO-konform?>> und auf der Handbuchseite xref:crm:schnellsuche.adoc#datensatz-anonymisieren[Schnellsuche].
--

[#e-mail-vorlagen]
== E-Mail-Vorlagen
 
[#faq-praxisbeispiel-tracking-url]
[.collapseBox]
.Wie kann ich eine E-Mail-Vorlage mit der Tracking-URL senden, sobald die Paketnummer am Auftrag verfügbar ist?
--
Du möchtest eine E-Mail-Vorlage, die die Tracking-URL (auch Sendungsverfolgung genannt) enthält, an deine Kund:innen versenden, sobald der Auftrag erfolgreich beim Versanddienstleister angemeldet und die Paketnummer am Auftrag verfügbar ist? 

Dann schau dir dieses xref:crm:praxisbeispiel-tracking-url-senden.adoc#[Praxisbeispiel] an, in dem wir Schritt für Schritt erklären, welche Einstellungen du in deinem plentymarkets System vornehmen musst.
--


[#priorisierung-e-mail-adressen]
== Priorisierung der gespeicherten E-Mail-Adressen in Ereignisaktionen

[#priorisierung-ereignisaktionen]
[.collapseBox]
.Wie werden die in plentymarkets gespeicherten E-Mail-Adressen in Ereignisaktionen priorisiert?
--
Die E-Mail-Adresse aus der Rechnungsadresse hat Vorrang vor der E-Mail-Adresse aus der Lieferadresse.

Wenn weder in der Rechnungsadresse noch in der Lieferadresse eine E-Mail-Adresse gespeichert ist, wird als Fallback die E-Mail-Adresse aus den Kontaktoptionen genommen. Dieser Fallback greift, wenn du in der Ereignisaktion in der Aktion *Kunde > E-Mail versenden* die Option *Kontakt* wählst. Hierbei gilt die folgende Priorisierung:

Die private E-Mail-Adresse hat Vorrang vor der geschäftlichen E-Mail-Adresse.
--

[#emailbuilder-migration-alte-vorlagen]
== EmailBuilder: Migration der alten Vorlagen

[.collapseBox]
.plenty migriert die alten E-Mail-Vorlagen aus meinem System in die neue Version des EmailBuilders. Was bedeutet das und muss ich nach der Migration irgendetwas tun?
--
Wie in diesem link:https://forum.plentymarkets.com/t/neue-funktionen-des-emailbuilders-inkl-migration-bestehender-vorlagen-new-features-of-emailbuilder-incl-migration-of-existing-templates/693489[Forumsbeitrag^] angekündigt, werden Vorlagen, die du in der Vergangenheit im Menü *Einrichtung » Mandant » [Mandant wählen] » E-Mail » Vorlagen* erstellt hast, automatisch in den neuen EmailBuilder migriert. Auch die Struktur und die Variablen werden aus den alten Vorlagen übernommen.

*Todo: Inhalte der migrierten Vorlagen prüfen*

Aufgrund der teilweise sehr komplexen Vorlagen ist es leider nicht möglich zu garantieren, dass alle Inhalte der Vorlagen korrekt migriert werden.

Prüfe daher die Inhalte der migrierten Vorlagen.

*Todo: Verknüpfte E-Mail-Vorlagen, die automatisiert versendet werden, prüfen*

Prüfe außerdem in deinem gesamten plentymarkets System alle Stellen, an denen du E-Mail-Vorlagen verknüpft hast, die basierend auf einem bestimmten Ereignis automatisiert versendet werden. Das sind die folgenden Stellen:

* Ereignisaktionen
* Ticket-Ereignisaktionen
* Automatischer Versand (Menü *Einrichtung » Mandant » [Mandant wählen] » E-Mail » Automatischer Versand*)
* Prozesse
* Aktionsmanager
* Ticket-Aktionsmanager

*Todo: Mehrsprachige Vorlagen manuell überführen*

Wenn du bereits eine Vorlage in mehreren Sprachen angelegt hast, musst du die Inhalte im neuen EmailBuilder manuell nachpflegen. Nutze dazu die Kopieren-Funktion.

Alle Informationen zum neuen EmailBuilder findest du in unserem xref:crm:emailbuilder.adoc#[Handbuch].

--

// == E-Mail-Versand
