= Leitfaden: Umstieg vom Ticketsystem auf den Messenger
:keywords: Leitfaden Umstieg auf Messenger, Umstieg vom Ticketsystem auf den Messenger, Ticketsystem Messenger Umstieg, was beachten beim Umstieg von Ticketsystem auf Messenger
:description: Dieser Leitfaden beschreibt die Einstellungen für den Umstieg vom Ticketsystem auf den Messenger.
:author: team-crm

[IMPORTANT]
.Über diesen Leitfaden
====
Dieser Leitfaden richtet sich an alle Händler:innen, die bereits in der Vergangenheit mit dem Ticketsystem gearbeitet haben und nun auf den Messenger umsteigen. +
Der Leitfaden soll einen reibungslosen Umstieg vom Ticketsystem auf den Messenger ermöglichen und zeigt dir Schritt für Schritt, welche Einstellungen du im Messenger vornehmen solltest. +
Bitte beachte, dass wir uns mit diesem Leitfaden auf die aus der Praxis bekannten gängigen Use cases konzentrieren und nicht jede individuelle Einstellung berücksichtigen können.
====

<<#table-overview-switch-ticket-system-messenger>> zeigt eine Übersicht, welche Einstellungen auf dieser Handbuchseite beschrieben werden und in welchem Menü du die Einstellungen vornimmst. +
Mit einem Klick auf den Link wirst du direkt in das entsprechende Kapitel weitergeleitet.

[[table-overview-switch-ticket-system-messenger]]
.Übersicht: Einstellungen für den Umstieg vom Ticketsystem auf den Messenger
[cols="2,2"]
|====
|Einstellung |Menüpfad

| <<#rollen-definieren, Rollen definieren>>
| *Einrichtung » CRM » Messenger » Rollen*

| <<#gruppen-typen-status-erstellen, Gruppen, Typen und Status erstellen>>
| *Einrichtung » CRM » Messenger » Gruppen, Typen und Status*

| <<#tags-fuer-messenger-erstellen, Tags für den Messenger erstellen>>
| *Einrichtung » Einstellungen » Tags*

| <<#ebay-konto-mit-messenger-verbinden, eBay-Einrichtung>> (optional)
| *Einrichtung » CRM » Messenger » Marktplätze » eBay*

| <<#posteingaenge-fuer-empfang-versand-einrichten, Posteingänge für den Empfang und Versand einrichten>>  (Assistent *Messenger-Konfiguration* durchlaufen)
|*Einrichtung » CRM » Messenger » Posteingänge*

| <<#weiterleitung-bei-externem-provider-einrichten, Weiterleitung beim externen Provider einrichten>>, damit E-Mails in deinem System ankommen
| _Einrichtung beim externen Provider_

| <<#ordner-erstellen, Ordner erstellen>>
| *CRM » Messenger*

| <<#filter-speichern, Filter speichern>> und ggf. für andere Benutzer:innen freigeben
| *CRM » Messenger*

| <<#automatisierungen-einrichten, Automatisierungen einrichten>>
| *Einrichtung » CRM » Messenger » Automatisierung*

a| Allgemeine Einstellungen:

* <<#papierkorb-automatisch-leeren, Papierkorb automatisch leeren>>
* <<#konversation-automatisch-archivieren, Konversationen automatisch archivieren>>
* <<#fluestermodus-fuer-alle-benutzer, Flüstermodus für alle Benutzer:innen global aktivieren>>
| *Einrichtung » CRM » Messenger » Allgemein*

|====


// TODO: mit CSEs klären: welche Rechte im Vgl. Ticketsystem/Messenger?


[#rollen-definieren]
== Rollen definieren

// TODO: Konfig

[#gruppen-typen-status-erstellen]
== Gruppen, Typen und Status erstellen

// TODO: Konfig

[#tags-fuer-messenger-erstellen]
== Tags für den Messenger erstellen

Tags sind Schlagworte, die dir das Gruppieren von Konversationen und Nachrichten erleichtern.

Erstelle Tags für den Messenger, um den Konversationen und Nachrichten diese Tags zuzuordnen und nach diesen Tags im Messenger zu filtern. Du kannst später auch bei Eintritt eines festgelegten Ereignisses Tags für die Konversation automatisch setzen oder entfernen, wenn du eine entsprechende Automatisierung im Messenger einrichtest.

Wichtig ist, dass du die benötigten Tags für den Bereich *Messenger-Konversationen* erstellst. Andernfalls sind die Tags nicht im Messenger verfügbar.

[.instruction]
Tag erstellen:

. Öffne das Menü *Einrichtung » Einstellungen » Tags*.
. Klicke auf material:add[]. +
→ Ein Pop-up-Fenster öffnet sich.
. Folge den Anweisungen.
. Prüfe die Angaben in der Zusammenfassung.
. Wenn du mit dem ER

// TODO: konfig weiterschreiben.


[#ebay-konto-mit-messenger-verbinden]
== eBay-Konto mit dem Messenger verbinden (optional)

// hier nur verlinken auf das entsprechende Kapitel auf Messenger-Seite?

[#posteingaenge-fuer-empfang-versand-einrichten]
== Posteingänge für den Empfang und den Versand einrichten

Damit du den Messenger für den E-Mail-Versand und den E-Mail-Empfang verwenden kannst, musst du den Assistenten *Messenger-Konfiguration* durchlaufen und Posteingänge einrichten. Du findest den Assistenten im Menü *Einrichtung » CRM » Messenger » Posteingänge*.

[TIP]
Für jeden Posteingang - also jedes Postfach - das du erstellen möchtest, musst du den Assistenten jeweils einmal durchlaufen. +
Du kannst jedem Posteingang andere Tags zuweisen, um später nach diesen Tags <<#tags-fuer-messenger-erstellen, filtern>> zu können.

Im Folgenden werden die einzelnen Schritte innerhalb des Assistenten *Messenger-Konfiguration* erläutert.

=== Schritt: Service-Aktivierung

Aktiviere hier den Messenger-Service für diesen Posteingang. Wenn die Schaltfläche blau (material:toggle_on[]) ist, ist der Service aktiviert.

=== Schritt: E-Mail-Weiterleitung

Hier wird automatisch eine kryptische E-Mail-Adresse, die die weiterleitende E-Mail-Adresse darstellt, erstellt. Kopiere diese E-Mail-Adresse und richte <<#weiterleitung-bei-externem-provider-einrichten, bei deinem E-Mail-Anbieter eine Weiterleitung an diese Adresse>> ein. Damit stellst du sicher, dass deine E-Mails automatisch weitergeleitet werden. Beachte, dass du diese kryptische E-Mail-Adresse nicht ändern kannst.

Gib im unteren Bereich alle E-Mail-Adressen ein, die Nachrichten an die kryptische, weiterleitende E-Mail-Adresse oben senden dürfen. Du kannst beliebig viele E-Mail-Adressen mit einem Klick auf *Neuen Eintrag hinzufügen* (material:add[]) hinzufügen. Bestehende E-Mail-Adressen können mit einem Klick auf *Eintrag entfernen* (material:delete[]) gelöscht werden. +
*_Hinweis:_* Mindestens eine E-Mail-Adresse muss hier eingetragen werden.


=== Schritt: Einstellungen für den E-Mail-Versand


=== Schritt: Einstellungen für den E-Mail-Empfang

[#weiterleitung-bei-externem-provider-einrichten]
== Weiterleitung beim externen Provider einrichten

Damit die E-Mails auch in deinem System ankommen, musst du eine Weiterleitung auf den Messenger bei deinem externen Provider einrichten. +
Wir haben eine Liste mit gängigen Providern zusammengestellt und haben für jeden dieser Provider eine kurze Anleitung erstellt, welche Einstellungen du vornehmen musst, um die Weiterleitung auf den Messenger einzurichten.

Schau bitte auf dieser xref:crm:praxisbeispiel-e-mail-weiterleitung-messenger.adoc#[Handbuchseite], ob eine Anleitung für deinen Provider dabei ist.

[#ordner-erstellen]
== Ordner erstellen

// TODO: Konfig

[#filter-speichern]
== Filter speichern
// ggf. für Benutzer freigeben

[#automatisierungen-einrichten]
== Automatisierungen einrichten

Wenn du im Ticketsystem mit Ereignissen und Aktionen gearbeitet hast, kannst du dies im Messenger über den Menüpunkt *Automatisierung* realisieren.

// im Ticketsystem ging das über Ereignisse und Aktionsmanager
// TODO: hier noch mit CSEs klären, welche Automatisierungen unbedingt aufgeführt werden müssen.

[#allgemeine-einstellungen]
== Allgemeine Einstellungen vornehmen

Im Bereich *Allgemein* des Messenger kannst du die Anzahl der Tage einstellen, nach der <<#papierkorb-automatisch-leeren, Konversationen dauerhaft aus dem Papierkorb entfernt>> werden. Und du kannst hier auch die Anzahl der Tage einstellen, nach der <<#konversation-automatisch-archivieren, Konversationen automatisch ins Archiv verschoben>> werden. +
Außerdem kannst du den <<#fluestermodus-fuer-alle-benutzer, Flüstermodus global für alle Benutzer:innen>> in deinem System aktivieren. 

[#papierkorb-automatisch-leeren]
=== Papierkorb automatisch leeren

Stelle ein, nach wie vielen Tagen gelöschte Nachrichten und gelöschte Konversationen automatisch aus dem Papierkorb entfernt werden sollen. Gehe dazu wie im Folgenden beschrieben vor. Beachte, dass nur eine Person mit Admin-Rechten diese Einstellung vornehmen kann.

[.instruction]
Papierkorb automatisch leeren:

. Öffne das Menü *Einrichtung » CRM » Messenger » Allgemein*. +
icon:map-signs[] *_Oder:_* Wenn du dich bereits im Messenger befindest, klicke auf der linken Seite unterhalb von material:settings[] *Einstellungen* auf material:folder_open[] *Allgemein*.
. Aktiviere (material:toggle_on[role=skyBlue]) im Bereich *Papierkorb automatisch leeren* die Option *Funktion "Papierkorb automatisch leeren" aktivieren*.
. Gib im Bereich *Anzahl an Tagen (max. 5 Jahre)* eine Zahl ein.
. *Speichere* (material:save[]) die Einstellungen. +
→ Alle im Papierkorb enthaltenen gelöschten Nachrichten und Konversationen werden automatisch nach der Anzahl der hier eingegebenen Tage aus dem Papierkorb entfernt.

[#konversation-automatisch-archivieren]
=== Konversationen automatisch archivieren

Stelle ein, nach wie vielen Tagen Konversationen automatisch ins Archiv verschoben werden sollen. Gehe dazu wie im Folgenden beschrieben vor. Beachte, dass nur eine Person mit Admin-Rechten diese Einstellung vornehmen kann.

[.instruction]
Konversationen automatisch archivieren:

. Öffne das Menü *Einrichtung » CRM » Messenger » Allgemein*. +
icon:map-signs[] *_Oder:_* Wenn du dich bereits im Messenger befindest, klicke auf der linken Seite unterhalb von material:settings[] *Einstellungen* auf material:folder_open[] *Allgemein*.
. Aktiviere (material:toggle_on[role=skyBlue]) im Bereich *Konversationen automatisch archivieren* die Option *Funktion "Automatisches Archivieren" aktivieren*.
. Gib im Bereich *Anzahl der Tage (max. 5 Jahre)* eine Zahl ein.
. *Speichere* (material:save[]) die Einstellungen. +
→ Alle Konversationen werden automatisch nach der Anzahl der hier eingegebenen Tage ins Archiv verschoben.

[#fluestermodus-fuer-alle-benutzer]
=== Flüstermodus für alle Benutzer:innen global aktivieren

Wenn du im Ticketsystem hauptsächlich mit Kommentaren, also internen Nachrichten, gearbeitet hast, kannst du im Messenger den Flüstermodus verwenden. +
Du kannst den Flüstermodus global für alle Benutzer:innen aktivieren. Somit ist der Flüstermodus bei allen neuen Konversationen und beim Antworten auf bestehende Nachrichten automatisch aktiviert. Selbstverständlich kannst du jederzeit auch auf "normale" Nachrichten umschalten.

[.instruction]
Flüstermodus für alle Benutzer:innen aktivieren:

. Öffne das Menü *Einrichtung » CRM » Messenger » Allgemein*. +
icon:map-signs[] *_Oder:_* Wenn du dich bereits im Messenger befindest, klicke auf der linken Seite unterhalb von material:settings[] *Einstellungen* auf material:folder_open[] *Allgemein*.
. Aktiviere (material:toggle_on[role=skyBlue]) im Bereich *Flüstermodus automatisch für alle Benutzer:innen aktivieren* die Option *Flüstermodus aktivieren*.
. *Speichere* (material:save[]) die Einstellungen. +
→ Der Flüstermodus ist nun automatisch für alle Benutzer:innen beim Erstellen einer neuen Konversation und beim Antworten auf eine bestehende Nachricht aktiviert.
