= Leitfaden: Umstieg vom Ticketsystem auf den Messenger
:keywords: Leitfaden Umstieg auf Messenger, Umstieg vom Ticketsystem auf den Messenger, Ticketsystem Messenger Umstieg, was beachten beim Umstieg von Ticketsystem auf Messenger
:description: Dieser Leitfaden beschreibt die Einstellungen für den Umstieg vom Ticketsystem auf den Messenger.
:author: team-crm

[IMPORTANT]
.Über diesen Leitfaden
====
Dieser Leitfaden richtet sich an alle Händler:innen, die bereits in der Vergangenheit mit dem Ticketsystem gearbeitet haben und nun auf den Messenger umsteigen. +
Der Leitfaden soll einen reibungslosen Umstieg vom Ticketsystem auf den Messenger ermöglichen und zeigt dir Schritt für Schritt, welche Einstellungen du im Messenger vornehmen solltest. +
Bitte beachte, dass wir uns mit diesem Leitfaden auf die aus der Praxis bekannten gängigen Use cases konzentrieren und nicht jede individuelle Einstellung berücksichtigen können.
====

<<#table-overview-switch-ticket-system-messenger>> zeigt eine Übersicht, welche Einstellungen auf dieser Handbuchseite beschrieben werden und in welchem Menü du die Einstellungen vornimmst. +
Mit einem Klick auf den Link wirst du direkt in das entsprechende Kapitel weitergeleitet.

[[table-overview-switch-ticket-system-messenger]]
.Übersicht: Einstellungen für den Umstieg vom Ticketsystem auf den Messenger
[cols="2,2"]
|====
|Einstellung |Menüpfad

| <<#rollen-und-eigner-definieren, Rollen definieren>>
| *Einrichtung » CRM » Messenger » Rollen*

| <<#gruppen-typen-status-erstellen, Gruppen, Typen und Status erstellen>>
| *Einrichtung » CRM » Messenger » Gruppen, Typen und Status*

| <<#tags-fuer-messenger-erstellen, Tags für den Messenger erstellen>>
| *Einrichtung » Einstellungen » Tags*

| <<#ebay-konto-mit-messenger-verbinden, eBay-Einrichtung>> (optional)
| *Einrichtung » CRM » Messenger » Marktplätze » eBay*

| <<#posteingaenge-fuer-empfang-versand-einrichten, Posteingänge für den Empfang und Versand einrichten>>  (Assistent *Messenger-Konfiguration* durchlaufen)
|*Einrichtung » CRM » Messenger » Posteingänge*

| <<#weiterleitung-bei-externem-provider-einrichten, Weiterleitung beim externen Provider einrichten>>, damit E-Mails in deinem System ankommen
| _Einrichtung beim externen Provider_

| <<#ordner-erstellen, Ordner erstellen>>
| *CRM » Messenger*

| <<#filter-speichern, Filter speichern>> und ggf. für andere Benutzer:innen freigeben
| *CRM » Messenger*

| <<#automatisierungen-einrichten, Automatisierungen einrichten>>
| *Einrichtung » CRM » Messenger » Automatisierung*

a| Allgemeine Einstellungen:

* <<#papierkorb-automatisch-leeren, Papierkorb automatisch leeren>>
* <<#konversation-automatisch-archivieren, Konversationen automatisch archivieren>>
* <<#fluestermodus-fuer-alle-benutzer, Flüstermodus für alle Benutzer:innen global aktivieren>>
| *Einrichtung » CRM » Messenger » Allgemein*

|====

// TODO: mit CSEs klären: welche Rechte im Vgl. Ticketsystem/Messenger?

[#rollen-und-eigner-definieren]
== Rollen und Eigner definieren

Eine Rolle repräsentiert die Beziehung deiner Mitarbeiter:innen zu einer Konversation. Du kannst jeder Konversation individuell eine Rolle zuordnen. +
Eine Konversation kann mehreren Eignern zugewiesen werden. Dazu definierst du für den Messenger Rollen, die dann den Eignern zugeordnet werden können. 

[IMPORTANT]
Das Erstellen einer Rolle ist Voraussetzung dafür, dass du einen Eigner an der Konversation setzen kannst.

[#rolle-erstellen]
=== Rolle erstellen

Gehe wie im Folgenden beschrieben vor, um eine Rolle zu erstellen. Später wählst du dann in der Konversation zunächst eine Rolle aus und kannst dann einen <<#rolle-und-eigner-zuweisen, Eigner zuweisen>>.

[.instruction]
Rolle erstellen:

. Öffne das Menü *Einrichtung » CRM » Messenger » Rollen*. +
icon:map-signs[] *_Oder:_* Wenn du dich bereits im Messenger befindest, klicke auf der linken Seite unterhalb von material:settings[] *Einstellungen* auf material:group[] *Rollen*.
. Klicke auf material:add[] *Neue Rolle*.
. Gib ggf. eine Positionsnummer ein.
. Gib den deutschen und den englischen Namen für die Rolle ein.
. Klicke auf material:save[] (*Speichern*).

[#rolle-und-eigner-zuweisen]
=== Rolle und Eigner einer Konversation zuweisen

Nachdem du die Rolle <<#rolle-erstellen, erstellt>> hast, kannst du den Konversationen im Messenger einen Eigner zuweisen. +
Du kannst das Zuweisen einer Rolle und eines Eigners auf 2 Arten durchführen: 

* für jede Konversation einzeln mit einem Klick auf material:more_vert[] in der Messenger-Übersicht
** Klicke <<#kontextmenue-konversation-eigner-aendern, hier>>, um in das Kapitel *Eigner ändern* weitergeleitet zu werden.
* über die Gruppenfunktion in der Messenger-Übersicht.
** Klicke <<#gruppenfunktion, hier>>, um in das Kapitel *Gruppenfunktion nutzen* weitergeleitet zu werden.

[#gruppen-typen-status-erstellen]
== Gruppen, Typen und Status erstellen

Gehe wie im Folgenden beschrieben vor, um Gruppen, Typen und Status für den Messenger zu erstellen. Beachte, dass nur eine Person mit Admin-Rechten Gruppen, Typen und Status erstellen kann.

[#gruppe-erstellen]
=== Gruppe erstellen

Gehe wie im Folgenden beschrieben vor, um eine neue Gruppe für den Messenger zu erstellen.

[.instruction]
Gruppe erstellen:

. Öffne das Menü *Einrichtung » CRM » Messenger » Gruppen, Typen und Status*. +
icon:map-signs[] *_Oder:_* Wenn du dich bereits im Messenger befindest, klicke auf der linken Seite unterhalb von material:settings[] *Einstellungen* auf material:checklist_rtl[] *Gruppen, Typen und Status*.
. Klicke auf material:add[] *Gruppe hinzufügen*.
. Gib eine Position ein.
. Gib den deutschen Namen für die Gruppe ein.
. Klicke auf material:add[] (*Sprache hinzufügen*), um den Gruppennamen auch in Englisch hinzuzufügen. 
. Klicke auf material:save[]. +
→ Die Gruppe wird erstellt und der Bereich *Typen* wird automatisch geöffnet.

[#typ-status-hinzufuegen]
=== Typ und Status hinzufügen

Du kannst beliebig viele Typen für eine Messenger-Gruppe erstellen, z.B. `Kund:innenanfrage` oder `Beschwerde`. Im nächsten Schritt kannst du einen Status für den Typen in Form einer Farbe und einer Fortschrittsangabe in Prozent hinzufügen. Gruppen, Typen und Status kannst du in deutscher und englischer Sprache erstellen.

Im Folgenden ist beschrieben, wie du einen Typen und einen Status direkt hintereinander erstellst. Wenn du zu einem späteren Zeitpunkt weitere Status zu einem bestehenden Typen hinzufügen möchtest, hilft dir die Beschreibung im Kapitel <<#neuen-status-zu-bestehendem-typ-hinzufuegen, Neuen Status zu einem bestehenden Typ hinzufügen>> weiter.

[.instruction]
Typ hinzufügen:

. Öffne das Menü *Einrichtung » CRM » Messenger » Gruppen, Typen und Status*. +
icon:map-signs[] *_Oder:_* Wenn du dich bereits im Messenger befindest, klicke auf der linken Seite unterhalb von material:settings[] *Einstellungen* auf material:checklist_rtl[] *Gruppen, Typen und Status*.
. Öffne die Gruppe.
. Klicke im Bereich *Typen* auf material:add[] *Typ hinzufügen*.
. Gib im Bereich *Details* eine Zahl für die Position ein.
. Gib im Bereich *Namen* einen Namen für den Typ ein.
. Gib einen Namen für den Typ ein. +
*_Optional:_* Klicke auf material:add[] *Sprache hinzufügen*, um den Typ auch in englischer Sprache hinzuzufügen.
. *Speichere* (material:save[]) die Einstellungen. +
→ Der Typ wird geöffnet und der Bereich *Status* wird sichtbar.
. Klicke im Bereich *Status* auf material:add[] *Status hinzufügen*.
. Wähle im Bereich *Details* eine Prozentzahl aus der Dropdown-Liste *Fortschritt*.
. Gib im Feld *Farbe* den link:https://html-color-codes.info/webfarben_hexcodes/[Hex-Code^] der Farbe ein oder wähle die Farbe mit einem Klick auf material:rectangle[]. 
. Gib im Feld *Position* eine Zahl für die Position ein.
. *Speichere* (material:save[]) die Einstellungen.
. Gib im Bereich *Namen* einen Namen für den Status ein. +
*_Optional:_* Klicke auf material:add[] *Sprache hinzufügen*, um den Status auch in englischer Sprache hinzuzufügen.
. *Speichere* (material:save[]) die Einstellungen.

[#neuen-status-zu-bestehendem-typ-hinzufuegen]
=== Neuen Status zu einem bestehenden Typ hinzufügen

Lege zu jedem <<#typ-status-hinzufuegen, Typ>> im Messenger einen oder mehrere Status mit Prozentangabe und Farbauswahl fest, um den Bearbeitungsfortschritt deiner Konversationen zu verfolgen.

[.instruction]
Neuen Status zu einem bestehenden Typ hinzufügen:

. Öffne das Menü *Einrichtung » CRM » Messenger » Gruppen, Typen und Status*. +
icon:map-signs[] *_Oder:_* Wenn du dich bereits im Messenger befindest, klicke auf der linken Seite unterhalb von material:settings[] *Einstellungen* auf material:checklist_rtl[] *Gruppen, Typen und Status*.
. Öffne die Gruppe.
. Klicke im Bereich *Typen* in die Zeile des Typs, für den du einen Status hinzufügen möchtest.
. Klicke im Bereich *Status* auf material:add[] *Status hinzufügen*.
. Wähle im Bereich *Details* eine Prozentzahl aus der Dropdown-Liste *Fortschritt*.
. Gib im Feld *Farbe* den link:https://html-color-codes.info/webfarben_hexcodes/[Hex-Code^] der Farbe ein oder wähle die Farbe mit einem Klick auf material:rectangle[]. 
. Gib im Feld *Position* eine Zahl für die Position ein.
. *Speichere* (material:save[]) die Einstellungen.
. Gib im Bereich *Namen* einen Namen für den Status ein. +
*_Optional:_* Klicke auf material:add[] *Sprache hinzufügen*, um den Status auch in englischer Sprache hinzuzufügen.
. *Speichere* (material:save[]) die Einstellungen.

Der gewählte Typ und der gewählte Status werden dann in der geöffneten Konversation neben den Tags angezeigt. Du kannst auch nach Konversationen mit bestimmten Typen und Status suchen und die Konversationen in der Übersicht anhand des Typs und Status aufsteigend und absteigend sortieren (material:arrow_upward[] und material:arrow_downward[]).

[#tags-fuer-messenger-erstellen]
== Tags für den Messenger erstellen

Tags sind Schlagworte, die dir das Gruppieren von Konversationen und Nachrichten erleichtern.

Erstelle Tags für den Messenger, um den Konversationen und Nachrichten diese Tags zuzuordnen und nach diesen Tags im Messenger zu filtern. Du kannst später auch bei Eintritt eines festgelegten Ereignisses Tags für die Konversation automatisch setzen oder entfernen, wenn du eine entsprechende Automatisierung im Messenger einrichtest.

Wichtig ist, dass du die benötigten Tags für den Bereich *Messenger-Konversationen* erstellst. Andernfalls sind die Tags nicht im Messenger verfügbar.

[.instruction]
Tag erstellen:

. Öffne das Menü *Einrichtung » Einstellungen » Tags*.
. Klicke auf material:add[]. +
→ Ein Pop-up-Fenster öffnet sich.
. Gib einen Namen für das Tag ein.
. Wähle eine Farbe aus, die der Hintergrund des Tags haben soll. Klicke dazu auf material:stop[role=black] und wähle die Farbe aus.
. Prüfe die Angaben in der Zusammenfassung.
. Wenn du zufrieden bist, klicke auf *TAG ERSTELLEN*.

Erstelle beliebig viele weitere Tags nach diesem Schema.

[#ebay-konto-mit-messenger-verbinden]
== eBay-Konto mit dem Messenger verbinden (optional)

Du kannst die eBay-Nachrichten deines verknüpften eBay-Kontos direkt abrufen und in den Messenger importieren. Natürlich kannst du über den Messenger auch antworten. Die Nachricht erreicht deine Kund:innen dann über das Nachrichtensystem von eBay.

Weil das Verknüpfen des eBay-Kontos mit dem Messenger optional ist, listen wir hier nicht detailliert auf, welche Einstellungen du vornehmen musst, sondern verweisen lediglich auf das Kapitel xref:crm:messenger.adoc#ebay-nachrichten-im-messenger-verwalten[eBay-Nachrichten im Messenger verwalten].

[#posteingaenge-fuer-empfang-versand-einrichten]
== Posteingänge für den Empfang und den Versand einrichten

Damit du den Messenger für den E-Mail-Versand und den E-Mail-Empfang verwenden kannst, musst du den Assistenten *Messenger-Konfiguration* durchlaufen und Posteingänge einrichten. Du findest den Assistenten im Menü *Einrichtung » CRM » Messenger » Posteingänge*.

[TIP]
Für jeden Posteingang - also jedes Postfach - das du erstellen möchtest, musst du den Assistenten jeweils einmal durchlaufen. +
Du kannst jedem Posteingang andere Tags zuweisen, um später nach diesen Tags <<#tags-fuer-messenger-erstellen, filtern>> zu können.

Im Folgenden werden die einzelnen Schritte innerhalb des Assistenten *Messenger-Konfiguration* erläutert.

=== Schritt: Service-Aktivierung

Aktiviere hier den Messenger-Service für diesen Posteingang. Wenn die Schaltfläche blau (material:toggle_on[]) ist, ist der Service aktiviert.

=== Schritt: E-Mail-Weiterleitung

Hier wird automatisch eine kryptische E-Mail-Adresse, die die weiterleitende E-Mail-Adresse darstellt, erstellt. Kopiere diese E-Mail-Adresse und richte <<#weiterleitung-bei-externem-provider-einrichten, bei deinem E-Mail-Anbieter eine Weiterleitung an diese Adresse>> ein. Damit stellst du sicher, dass deine E-Mails automatisch weitergeleitet werden. Beachte, dass du diese kryptische E-Mail-Adresse nicht ändern kannst.

Gib im unteren Bereich alle E-Mail-Adressen ein, die Nachrichten an die kryptische, weiterleitende E-Mail-Adresse oben senden dürfen. Du kannst beliebig viele E-Mail-Adressen mit einem Klick auf *Neuen Eintrag hinzufügen* (material:add[]) hinzufügen. Bestehende E-Mail-Adressen können mit einem Klick auf *Eintrag entfernen* (material:delete[]) gelöscht werden. +
*_Hinweis:_* Mindestens eine E-Mail-Adresse muss hier eingetragen werden.

=== Schritt: Einstellungen für den E-Mail-Versand

Hier speicherst du die Zugangsdaten des E-Mail-Postfachs, aus dem du E-Mails versenden möchtest. Dies ist erforderlich, damit dein System E-Mails über den Messenger versenden und empfangen kann.

Wähle nach Eingabe der Zugangsdaten die Verschlüsselung und gib die Absender-E-Mail-Adresse sowie den Absendernamen ein. Diese E-Mail-Adresse und dieser Name wird den Empfänger:innen deiner E-Mails aus diesem Postfach angezeigt.

*_Hinweis für Postfächer bei mailbox.org:_* Gib den Port *465* ein und wähle als Verschlüsselung die Einstellung *SSL*.

Im Bereich *Standard-Posteingang* kannst du die Option *Als Standard-Posteingang festlegen* aktivieren (material:check_box[role=skyBlue]), damit dieser Posteingang beim Schreiben neuer Nachrichten aus dem Messenger vorausgewählt ist.

Außerdem wählst du in diesem Schritt eine E-Mail-Vorlage für den E-Mail-Versand.

[IMPORTANT]
.Live-Modus im Assistenten *E-Mail-Konten* muss aktiviert sein
====
Im Assistenten *E-Mail-Konten* im Schritt xref:crm:emailbuilder.adoc#e-mail-server-zugangsdaten[Zugangsdaten] muss im Bereich *Möchtest du den Live-Modus aktivieren?* die Option *Live-Modus aktivieren* aktiviert (material:check_box[role=skyBlue]) sein. Dadurch wird der Testmodus deaktiviert und alle E-Mails werden an die jeweiligen Empfänger:innen versendet. 

Das Aktivieren des Live-Modus gilt global für den gesamten E-Mail-Versand in plentysystems. Somit auch für den E-Mail-Versand über den Messenger.
====

[TIP]
.Standardvorlage *Messenger default NEW* verwenden
====
Wir empfehlen, die Standardvorlage *Messenger default NEW* für den Messenger zu verwenden. Diese Vorlage ist bereits in deinem System im Menü *CRM » EmailBuilder* im Ordner *Standardvorlagen* vorhanden. Du kannst diese Vorlage nach deinen Wünschen anpassen. Diese Vorlage wird automatisch vorausgewählt, wenn du eine neue Konversation schreibst.

Die Vorlage enthält die folgenden Variablen:

* Name des Mandanten in der Betreffzeile, dargestellt als &#123;&#8288;&#123;globals.clientName&#125;&#8288;&#125;
** Im Betreff der Vorlage muss eine sogenannte _twig expression_ in doppelt geschweiften Klammern enthalten sein, weil in der Betreffzeile keine "normalen" Variablen verwendet werden können. Weitere Informationen dazu findest du auf der Handbuchseite xref:crm:emailbuilder.adoc#[EmailBuilder] im Kapitel xref:crm:emailbuilder.adoc#variablen-emailbuilder[Verfügbare Variablen und twig expressions].
* Vollständiger Name
* Signatur im HTML-Format
====

Du kannst in diesem Schritt selbstverständlich auch eine Vorlage wählen, die du selbst im Menü *CRM » EmailBuilder* erstellt hast.

=== Schritt: Einstellungen für den E-Mail-Empfang

Hier speicherst du den Namen für das Postfach. Außerdem wählst du den oder die Tags, die die Nachrichten erhalten sollen, wenn diese von weitergeleiteten Adressen empfangen oder versendet werden.

Wähle außerdem eine oder mehrere Abonnent:innen aus der Liste, damit diese bei neuen Nachrichten in diesem Posteingang informiert werden.

Im Bereich *Eigner und Rollen* wählst du eine Standardrolle und einen Standardeigner aus den Listen. 

Im Bereich *Gruppe, Typ und Status* wählst du eine Standardgruppe, einen Standardtyp und einen Standardstatus, die dann neuen Nachrichten in diesem Posteingang zugewiesen werden.

Wenn du im letzten Abschnitt die Option *Benachrichtigungen aktivieren* aktivierst (material:check_box[role=skyBlue]), wirst du in deinem plentysystems Backend oben rechts neben dem Symbol material:notifications[] informiert, sobald eine
<<#benachrichtigung-neue-nachricht, neue Nachricht im Messenger eingegangen>> ist.

[#weiterleitung-bei-externem-provider-einrichten]
== Weiterleitung beim externen Provider einrichten

Damit die E-Mails auch in deinem System ankommen, musst du eine Weiterleitung auf den Messenger bei deinem externen Provider einrichten. +
Wir haben eine Liste mit gängigen Providern zusammengestellt und haben für jeden dieser Provider eine kurze Anleitung erstellt, welche Einstellungen du vornehmen musst, um die Weiterleitung auf den Messenger einzurichten.

Schau bitte auf dieser xref:crm:praxisbeispiel-e-mail-weiterleitung-messenger.adoc#[Handbuchseite], ob eine Anleitung für deinen Provider dabei ist.

[#ordner-erstellen]
== Ordner erstellen

Um deinen Konversationen mehr Struktur und Übersichtlichkeit zu geben, kannst du beliebig viele Ordner erstellen und später deine Konversationen automatisiert diesen Ordnern zuweisen.

Gehe wie im Folgenden beschrieben vor, um einen neuen Ordner hinzuzufügen.

[.instruction]
Neuen Ordner hinzufügen:

. Öffne das Menü *CRM » Messenger*.
. Klicke in der Seitennavigation links in der Zeile material:3p[] *Meine Ordner* auf material:more_vert[] (*Weitere Optionen*) und dann auf material:add[] *Neuen Ordner hinzufügen*. +
→ Das Fenster *Neuen Ordner hinzufügen* öffnet sich.
. Gib einen Namen für den Ordner ein.
. Klicke auf *Speichern*. +
→ Der Ordner wird erstellt. Du findest den Ordner unter material:3p[] *Meine Ordner*.

Mit einem Klick auf den Ordner werden dann nur die in diesem Ordner vorhandenen Konversationen in der Übersicht angezeigt. 

Denk daran, später eine entsprechende <<#automatisierungen-einrichten, Automatisierung einzurichten>>, damit bestimmte Konversationen in den von dir definierten Ordnern landen.

[#filter-speichern]
== Filter speichern

Wenn du eine Suche ausführst, siehst du deine gewählten Filter oben als so genannte "Chips" dargestellt. Diese Filter kannst du speichern, um sie in Zukunft schneller und einfacher wieder verwenden zu können.

[.instruction]
Aktuellen Filter speichern:

. Führe eine Suche aus.
. Klicke auf *Gespeicherte Filter* (material:bookmarks[]).
. Klicke auf material:bookmark_border[] *Aktuellen Filter speichern*.
. Gib einen Namen für den Filter ein.
. Aktiviere (material:toggle_on[role=skyBlue]) die Option *Als Standard festlegen*, wenn dieser Filter der Standardfilter sein soll.
. Aktivere (material:toggle_on[role=skyBlue]) die Option *Filter für alle Benutzer erstellen*, damit dieser Filter für alle Benutzer:innen verfügbar ist.
. Klicke auf *SPEICHERN*. +
→ Der Filter erscheint nun unter *Gespeicherte Filter* (material:bookmarks[]).

[TIP]
Lege die Reihenfolge der Filter per Drag-and-drop mit einem Klick auf *Verschieben* (material:drag_indicator[]) fest. Klicke auf material:delete[], um einen Filter zu löschen.

[#gespeicherte-filter-anwenden]
=== Gespeicherte Filter anwenden

Gehe wie im Folgenden vor, um einen gespeicherten Filter in der Suche anzuwenden.

[.instruction]
Gespeicherte Filter anwenden:

. Klicke auf *Gespeicherte Filter* (material:bookmarks[]).
. Klicke auf einen bereits erstellten Filter. +
→ Die Suche wird ausgeführt und die verwendeten Filtereinstellungen werden oben als so genannte "Chips" dargestellt.

[TIP]
Du findest alle <<#aktuellen-filter-speichern, gespeicherten Filter>> im dem Ordner material:bookmarks[] *Meine Filter* in der Seitennavigation des Messenger. Mit einem Klick auf den jeweiligen Filter werden die Filtereinstellungen in dem Ordner, in dem du dich gerade befindest, angewendet.

[#filter-als-standard]
=== Filter als Standard festlegen

Damit du einen häufig verwendeten Filter nicht jedes Mal beim Öffnen des Menüs *CRM » Messenger* erst aus der Liste deiner <<#gespeicherte-filter-anwenden, gespeicherten Filter>> wählen musst, kannst du einen erstellten Filter als Standard festlegen. Jedes Mal, wenn du den Messenger öffnest, wird dieser Filter dann also automatisch ausgeführt.

Du kannst einen Filter direkt beim Erstellen als Standard festlegen oder du legst den Filter nachträglich aus der Übersicht heraus als Standard fest. +
Klicke in der Zeile des gespeicherten Filters auf material:star[] *Als Standard festlegen*. Wenn du einen anderen Filter als Standard festlegen möchtest, deaktiviere den aktuell gewählten Standardfilter mit einem Klick auf material:star_outline[] *Nicht als Standard verwenden*.

[#automatisierungen-einrichten]
== Automatisierungen einrichten

Wenn du im Ticketsystem mit Ereignissen und Aktionen gearbeitet hast, kannst du dies im Messenger über den Menüpunkt *Automatisierung* realisieren.

// TODO: hier noch mit CSEs klären, welche Automatisierungen unbedingt aufgeführt werden müssen.

Die Möglichkeiten in der Messenger-Automatisierung sind vielfältig. Erfahre auf der Handbuchseite xref:crm:messenger.adoc#[Messenger] im Kapitel xref:crm:messenger.adoc#ereignisse-automatisieren[Ereignisse im Messenger automatisieren], welche Filter, Auslöser und Aktionen dir zur Verfügung stehen.

Auf der Handbuchseite xref:crm:praxisbeispiel-messenger-automatisierung.adoc#[Praxisbeispiel: Messenger-Automatisierungen einrichten] findest du gängige Beispiele zum Einrichten von Automatisierungen im Messenger. Diese Seite wird ständig aktualisiert und mit neuen Beispielen befüllt.

[#allgemeine-einstellungen]
== Allgemeine Einstellungen vornehmen

Im Bereich *Allgemein* des Messenger kannst du die Anzahl der Tage einstellen, nach der <<#papierkorb-automatisch-leeren, Konversationen dauerhaft aus dem Papierkorb entfernt>> werden. Und du kannst hier auch die Anzahl der Tage einstellen, nach der <<#konversation-automatisch-archivieren, Konversationen automatisch ins Archiv verschoben>> werden. +
Außerdem kannst du den <<#fluestermodus-fuer-alle-benutzer, Flüstermodus global für alle Benutzer:innen>> in deinem System aktivieren. 

[#papierkorb-automatisch-leeren]
=== Papierkorb automatisch leeren

Stelle ein, nach wie vielen Tagen gelöschte Nachrichten und gelöschte Konversationen automatisch aus dem Papierkorb entfernt werden sollen. Gehe dazu wie im Folgenden beschrieben vor. Beachte, dass nur eine Person mit Admin-Rechten diese Einstellung vornehmen kann.

[.instruction]
Papierkorb automatisch leeren:

. Öffne das Menü *Einrichtung » CRM » Messenger » Allgemein*. +
icon:map-signs[] *_Oder:_* Wenn du dich bereits im Messenger befindest, klicke auf der linken Seite unterhalb von material:settings[] *Einstellungen* auf material:folder_open[] *Allgemein*.
. Aktiviere (material:toggle_on[role=skyBlue]) im Bereich *Papierkorb automatisch leeren* die Option *Funktion "Papierkorb automatisch leeren" aktivieren*.
. Gib im Bereich *Anzahl an Tagen (max. 5 Jahre)* eine Zahl ein.
. *Speichere* (material:save[]) die Einstellungen. +
→ Alle im Papierkorb enthaltenen gelöschten Nachrichten und Konversationen werden automatisch nach der Anzahl der hier eingegebenen Tage aus dem Papierkorb entfernt.

[#konversation-automatisch-archivieren]
=== Konversationen automatisch archivieren

Stelle ein, nach wie vielen Tagen Konversationen automatisch ins Archiv verschoben werden sollen. Gehe dazu wie im Folgenden beschrieben vor. Beachte, dass nur eine Person mit Admin-Rechten diese Einstellung vornehmen kann.

[.instruction]
Konversationen automatisch archivieren:

. Öffne das Menü *Einrichtung » CRM » Messenger » Allgemein*. +
icon:map-signs[] *_Oder:_* Wenn du dich bereits im Messenger befindest, klicke auf der linken Seite unterhalb von material:settings[] *Einstellungen* auf material:folder_open[] *Allgemein*.
. Aktiviere (material:toggle_on[role=skyBlue]) im Bereich *Konversationen automatisch archivieren* die Option *Funktion "Automatisches Archivieren" aktivieren*.
. Gib im Bereich *Anzahl der Tage (max. 5 Jahre)* eine Zahl ein.
. *Speichere* (material:save[]) die Einstellungen. +
→ Alle Konversationen werden automatisch nach der Anzahl der hier eingegebenen Tage ins Archiv verschoben.

[#fluestermodus-fuer-alle-benutzer]
=== Flüstermodus für alle Benutzer:innen global aktivieren

Wenn du im Ticketsystem hauptsächlich mit Kommentaren, also internen Nachrichten, gearbeitet hast, kannst du im Messenger den Flüstermodus verwenden. +
Du kannst den Flüstermodus global für alle Benutzer:innen aktivieren. Somit ist der Flüstermodus bei allen neuen Konversationen und beim Antworten auf bestehende Nachrichten automatisch aktiviert. Selbstverständlich kannst du jederzeit auch auf "normale" Nachrichten umschalten.

[.instruction]
Flüstermodus für alle Benutzer:innen aktivieren:

. Öffne das Menü *Einrichtung » CRM » Messenger » Allgemein*. +
icon:map-signs[] *_Oder:_* Wenn du dich bereits im Messenger befindest, klicke auf der linken Seite unterhalb von material:settings[] *Einstellungen* auf material:folder_open[] *Allgemein*.
. Aktiviere (material:toggle_on[role=skyBlue]) im Bereich *Flüstermodus automatisch für alle Benutzer:innen aktivieren* die Option *Flüstermodus aktivieren*.
. *Speichere* (material:save[]) die Einstellungen. +
→ Der Flüstermodus ist nun automatisch für alle Benutzer:innen beim Erstellen einer neuen Konversation und beim Antworten auf eine bestehende Nachricht aktiviert.
