= Leitfaden: Umstieg vom Ticketsystem auf den Messenger
:keywords:
:description: 
:author: team-crm

// TODO: add to nav.adoc

Diese Handbuchseite dient als Leitfaden für einen reibungslosen Umstieg vom Ticketsystem auf den Messenger und zeigt dir Schritt für Schritt, welche Einstellungen du im Messenger vornehmen solltest. +
Bitte beachte, dass wir bei diesem Leitfaden von den gängigen Use cases ausgegangen sind und nicht jede individuelle Einstellung auf dieser Seite berücksichtigen können.

<<#table-overview-switch-ticket-system-messenger>> zeigt eine Übersicht, welche Einstellungen auf dieser Handbuchseite beschrieben werden und in welchem Menü du die Einstellungen vornimmst. +
Mit einem Klick auf den Link wirst du direkt in das entsprechende Kapitel weitergeleitet.

[[table-overview-switch-ticket-system-messenger]]
.Übersicht: Einstellungen für den Umstieg vom Ticketsystem auf den Messenger
[cols="2,2"]
|====
|Einstellung |Menüpfad

| xref:crm:messenger.adoc#rollen-fuer-eigner[Rollen definieren]
| *Einrichtung » CRM » Messenger » Rollen*

a| xref:crm:messenger.adoc#typen-status-erstellen[Gruppen erstellen]

* Typen und Status für die Gruppen erstellen

| *Einrichtung » CRM » Messenger » Gruppen, Typen und Status*

| xref:crm:messenger.adoc#tags-messenger[Tags für den Messenger erstellen]
| *Einrichtung » Einstellungen » Tags*

| eBay-Einrichtung (optional) (LINK)
| *Einrichtung » CRM » Messenger » Marktplätze » eBay*

| Posteingänge für den Empfang und Versand einrichten (LINK) +
Assistent *Messenger-Konfiguration* durchlaufen +
Weiterleitung beim externen Provider einrichten, damit E-Mails in deinem System ankommen
| *Einrichtung » CRM » Messenger » Posteingänge*

| Ordner erstellen (LINK)
| *CRM » Messenger*

| Filter speichern (LINK) +
ggf. für andere Benutzer:innen freigeben
| *CRM » Messenger*

| Automatisierungen einrichten (LINK)
| *Einrichtung » CRM » Messenger » Automatisierung*

| Allgemeine Einstellungen (LINK) +
Konversationen automatisch archivieren +
Papierkorb automatisch leeren + 
Flüstermodus für alle Benutzer:innen global aktivieren
| *Einrichtung » CRM » Messenger » Allgemein*

|====


1. Rollen definieren
2. Gruppen erstellen, dafür Typen und Status erstellen
3. Tags für den Messenger erstellen 
    für den Bereich *Messenger-Konversationen* erstellen
4. (optional) eBay-Einrichtung -> hier nur verlinken auf das entsprechende Kapitel.
5. Posteingänge für Empfang und Versand einrichten
    Assistent Messenger-Konfiguration durchlaufen
    Weiterleitung beim externen Provider einrichten, damit E-Mails auch im System ankommen (hier verlinken auf die Seite)
6. Ordner im Ticketsystem
- beschreiben, wie man dafür Filter im Messenger einrichtet.
7. Filter speichern und ggf. für Benutzer freigeben
8. Automatisierungen einrichten
    im Ticketsystem ging das über Ereignisse und Aktionsmanager
9. Allgemeine Einstellungen (Konversationen automatisch archivieren, Papierkorb automatisch leeren, Flüstermodus für alle)