= Messenger
:keywords: Messenger, Nachrichten, Nachrichten abrechnen, kostenpflichtige Nachrichten
:description: Erfahre, wie du mit dem Messenger in plentymarkets arbeitest.
:id: RQ7TB6P
:author: team-crm

Nutze den Messenger, um im Backend Nachrichten zu erstellen, die deinen Kontakten zugeordnet werden. Diese Nachrichten funktionieren wie Notizen, sind nur in deinem plentymarkets Backend sichtbar und können _nicht_ von deinen Kontakten aufgerufen werden.

Erfahre auf dieser Handbuchseite, wie du neue Nachrichten zu deinem Kontakt <<#nachricht-erstellen, erstellst>>, alle zu einem Kontakt <<#nachrichten-anzeigen, vorhandenen Nachrichten aufrufst>> sowie vorhandene Nachrichten <<#nachricht-bearbeiten, bearbeitest>> und <<#nachricht-loeschen, löschst>>.

[#vorbereitende-einstellungen]
== Vorbereitende Einstellungen

Wenn Benutzer:innen vom Typ *Backend* mit dem Messenger arbeiten sollen, musst du als Person mit *Admin*-Zugang zunächst Rechte für diese Benutzer:innen vergeben. Außerdem musst du <<#tags-messenger, Tags erstellen>>, damit diese für den Messenger zur Verfügung stehen.

[#benutzerrechte-backend-benutzer]
=== Rechte für Backend-Benutzer:innen vergeben

:rights-purpose: Nachrichten im Messenger sehen und erstellen
:right-one: pass:quotes[*CRM > Nachricht > Anzeigen*]
:right-two: pass:quotes[*CRM > Nachricht > Erstellen*]
:right-three: pass:quotes[*Kommentare > Anzeigen*]
:right-four: pass:quotes[*Kommentare > Erstellen*]
:right-five: pass:quotes[*Einrichtung > Eigenschaft > Anzeigen*]
:right-six: pass:quotes[*Einrichtung > Eigenschaft > Erstellen*]
:right-seven: pass:quotes[*Einrichtung > Tag > Anzeigen*]
:right-eight: pass:quotes[*Einrichtung > Tag > Erstellen*]

include::_includes:partial$rights.adoc[]

[#tags-messenger]
=== Tags für den Messenger erstellen

include::_includes:page$tags-creation.adoc[]

[TIP]
Wenn du Nachrichten erstellen möchtest, die über den Messenger _kostenpflichtig_ abgerechnet werden sollen, erstelle nach dem selben Schema Tags für den Bereich *Nachrichten (kostenpflichtig)*. Diese Tags musst du dann der <<#nachricht-erstellen, Nachricht>> hinzufügen.

[#tags-messenger-search]
=== Tags für den Messenger suchen

include::_includes:page$tags-search.adoc[]

[#nachricht-erstellen]
== Nachricht erstellen

Erstelle zu jedem deiner Kontakte beliebig viele Nachrichten.

[.instruction]
Nachricht erstellen:

. Öffne das Menü *CRM » Kontakte*.
. Suche (icon:search[role="blue"]) den Kontakt anhand der Filtereinstellungen wie auf der Handbuchseite xref:crm:kontakt-suchen.adoc#[Kontakt suchen] beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Öffne das Kontextmenü mit einem Klick auf material:more_vert[] ganz rechts in der Zeile des Kontakts und wähle material:message[] *Messenger*. +
icon:map-signs[] *_Oder:_* Klicke in die Zeile des Kontakts, um den Kontaktdatensatz zu öffnen und dann auf der linken Seite auf *Messenger*. +
→ Der Bereich *Messenger* wird geöffnet.
. Klicke auf *Neue Nachricht* (material:add[]).
. Erstelle die Nachricht. Beachte dazu die Erläuterungen in <<#table-new-message-messenger>>.
. Klicke auf *Senden* (material:outgoing_mail[]). +
→ Die Nachricht wird erstellt.

[[table-new-message-messenger]]
.Neue Nachricht im Messenger erstellen
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Empfänger*
|Wähle die Person, die die Nachricht erhalten soll, aus der Dropdown-Liste oder gib die ersten 3 Buchstaben des Namens dieser Person ein, um Vorschläge zu erhalten. +
Standardmäßig sind *ALLE* Empfänger:innen sowie der eigene Name gewählt.

| *Stoppuhr*
|Die Stoppuhr oben rechts beginnt zu zählen, wenn du den Bereich *Messenger* öffnest. +
Klicke auf material:pause_circle[], um die Stoppuhr anzuhalten bzw. auf material:play_circle[], damit die Zeit weiterläuft. Klicke auf terra:reset[], um die Stoppuhr auf 0 zurückzusetzen.

| *Titel*
|Gib den Titel der Nachricht ein. Dies ist eine Pflichtangabe.

| *Tags*
|Wähle Tags aus der Dropdown-Liste oder gib die ersten 3 Buchstaben des Tags ein, um Vorschläge zu erhalten.

| *Flüstern*
|Wenn du auf die Schaltfläche *Flüstern* (material:visibility[] material:toggle_off[]) klickst, ist die Nachricht nur für deine Mitarbeiter:innen, die die Berechtigung für den Messenger haben, sichtbar. Deine Kontakte können die Nachricht _nicht_ einsehen. Die Funktion *Flüstern* ist aktiviert, wenn die Schaltfläche so aussieht: material:visibility_off[] material:toggle_on[role=skyBlue]. +
*_Hinweis:_* Wenn die Funktion *Flüstern* aktiviert ist (material:visibility_off[] material:toggle_on[role=skyBlue]), sind das Feld *Minuten* und die Schaltfläche *kostenpflichtig* deaktiviert.

| *Nachricht*
|Füge Text über die Zwischenablage ein und formatiere ggf. den Text mit den Funktionen in der Symbolleiste. Dies ist eine Pflichtangabe.

| *Dateien anhängen*
|Klicke auf material:attach_file[], um beliebig viele Dateianhänge zur Nachricht hochzuladen. +
Die folgenden Dateitypen sind als Anhang in der Nachricht zulässig: +
bmp, csv, gif, jpeg, json, pdf, png, tiff, txt, zip.

| *Minuten*
|Gib die Minuten in das Feld ein, die du für eine bestimmte Aufgabe oder Einheit speichern oder später auch abrechnen möchtest. +
Wenn du die hier eingegebenen Minuten abrechnen möchtest, musst du einen Tag vom Typ *Nachrichten (kostenpflichtig)* wählen und die Schaltfläche terra:pay_cash[] material:toggle_off[] aktivieren.

| *Kostenpflichtig*
|Aktiviere die Schaltfläche terra:pay_cash[] material:toggle_off[], um die im Feld *Minuten* eingegeben Minuten kostenpflichtig abzurechnen. +
*_Wichtig:_* Wenn du die Schaltfläche aktivierst hast (terra:pay_cash[] material:toggle_on[role=skyBlue]), musst du zwingend ein <<#tags-messenger, Tag>> vom Typ *Nachrichten (kostenpflichtig)* mit der Nachricht verknüpfen. Dieses Tag muss zuvor im Menü *Einrichtung » Einstellungen » Tags* <<#tags-messenger, erstellt>> worden sein. Andernfalls kann die Nachricht _nicht_ erstellt werden.

| *Senden*
|Klicke auf material:outgoing_mail[], um die Nachricht zu erstellen.

|====

[#nachrichten-anzeigen]
== Nachrichten anzeigen

Aus dem geöffneten Kontakt heraus lassen sich alle zu dem Kontakt gespeicherten Nachrichten im Messenger anzeigen.

[.instruction]
Nachrichten anzeigen:

. Öffne das Menü *CRM » Kontakte*.
. Suche (icon:search[role="blue"]) den Kontakt anhand der Filtereinstellungen wie auf der Handbuchseite xref:crm:kontakt-suchen.adoc#[Kontakt suchen] beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Öffne das Kontextmenü mit einem Klick auf material:more_vert[] ganz rechts in der Zeile des Kontakts und wähle material:message[] *Messenger*. +
icon:map-signs[] *_Oder:_* Klicke in die Zeile des Kontakts, um den Kontaktdatensatz zu öffnen und dann auf der linken Seite auf *Messenger*. +
→ Alle zu dem Kontakt gespeicherten Nachrichten werden angezeigt.

Du kannst einzelne Nachrichten mit einem Klick auf die Nachricht anzeigen. Über die Sortierung kannst du die Nachrichten aufsteigend oder absteigend nach Datum anzeigen.

[#nachricht-bearbeiten]
== Nachricht bearbeiten

Du kannst Nachrichten jederzeit bearbeiten. Gehe dazu wie im Folgenden beschrieben vor.

[.instruction]
Nachricht bearbeiten:

. Öffne das Menü *CRM » Kontakte*.
. Suche (icon:search[role="blue"]) den Kontakt anhand der Filtereinstellungen wie auf der Handbuchseite xref:crm:kontakt-suchen.adoc#[Kontakt suchen] beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Öffne das Kontextmenü mit einem Klick auf material:more_vert[] ganz rechts in der Zeile des Kontakts und wähle material:message[] *Messenger*. +
icon:map-signs[] *_Oder:_* Klicke in die Zeile des Kontakts, um den Kontaktdatensatz zu öffnen und dann auf der linken Seite auf *Messenger*. +
→ Der Bereich *Messenger* wird geöffnet und die gespeicherten Nachrichten werden angezeigt.
. Klicke auf die Nachricht, die du bearbeiten möchtest.
. Nimm die gewünschten Änderungen vor. Beachte dazu die Erläuterungen in <<#table-messenger-edit-message>>.

[[table-messenger-edit-message]]
.Nachricht bearbeiten
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Nachricht nicht geschlossen*
|Mit einem Klick auf material:toggle_off[] material:done[] neben der Kontakt-ID (material:person[]) wird die Nachricht geschlossen. +
In der Nachrichtenübersicht wird die Nachricht dann mit einem material:done[role=green] angezeigt. Dies signalisiert anderen Mitarbeiter:innen, dass diese Nachricht bereits bearbeitet wurde. +
Mit einem Klick auf material:toggle_on[role=skyBlue] material:done[] wird die Nachricht wieder geöffnet.

|Kontakt-ID
|Mit einem Klick auf material:person[] _Kontakt-ID_ wird die Detailansicht des Kontakts geöffnet.

| *Sichtbarkeiten ändern*
|Mit einem Klick auf material:edit[] änderst du die Sichtbarkeiten. Du kannst bereits ausgewählte Empfänger:innen entfernen und neue Empfänger:innen hinzufügen. +
*_Wichtig:_* Das Ändern von Sichtbarkeiten bezieht sich immer auf den gesamten Nachrichtenverlauf. Das bedeutet, wenn du einen Namen entfernst, kann diese Person keine der Nachrichten mehr sehen. Wenn du eine Person hinzufügst, kann dieser alle Nachrichten im Verlauf sehen.

| *Antworten*
|Mit einem Klick auf icon:reply[] antwortest du auf die Nachricht.

| *Löschen*
|Mit einem Klick auf material:delete[] löschst du den gesamten Nachrichtenverlauf. +
*_Wichtig:_* Beim Löschen werden die Hauptnachricht und alle zugehörigen Nachrichten gelöscht.

| *Stoppuhr*
|Die Stoppuhr beginnt zu zählen, sobald der Bereich *Messenger* geöffnet wird. +
Klicke auf material:pause_circle[], um die Stoppuhr anzuhalten bzw. auf material:play_circle[], damit die Zeit weiterläuft. Klicke auf terra:reset[], um die Stoppuhr auf 0 zurückzusetzen.

| *Tags bearbeiten*
|Mit einem Klick auf *Tags bearbeiten* (material:edit[]) direkt an der Nachricht löschst du bestehende Tags oder fügst neue Tags hinzu. +
Ein Klick auf *Tags speichern* (material:save[]) speichert die Änderung an den Tags.

|====

[#nachricht-loeschen]
== Nachricht löschen

Mit einem Klick auf material:delete[] an der geöffneten Nachricht löschst du den gesamten Nachrichtenverlauf. +
*_Wichtig:_* Beim Löschen werden die Hauptnachricht und alle zugehörigen Nachrichten gelöscht.

Bevor der Nachrichtenverlauf endgültig gelöscht wird, wird ein Fenster angezeigt, in dem du das Löschen der Nachricht noch einmal bestätigen musst.
