= Newsletter (altes Tool)
:keywords: Newsletter, Double-Opt-In-Funktion, Newsletter Vorlage, Sichtbarkeit Newsletter, E-Mail-Ordner, CleverReach
:description: Erfahre, wie du Newsletter über plentymarkets an deine Kund:innen versendest.
:author: team-crm

[IMPORTANT]
.Newsletter und CleverReach werden nicht mehr weiterentwickelt
====
Der in plentymarkets integrierte Newsletter sowie die Schnittstelle zu <<#1700, CleverReach>> werden nicht mehr weiterentwickelt. Wenn du plentymarkets schon länger nutzt, kannst die im Folgenden aufgelisteten Menüs weiterhin sehen und nutzen. Erweiterungen und Neuerungen werden aber nicht mehr vorgenommen.

* CRM » Newsletter
* Einrichtung » Mandant » [Mandant wählen] » E-Mail » Newsletter
* Einrichtung » CRM » Newsletter » CleverReach

Bei Systemen, die seit September 2022 ausgeliefert werden, sind die oben genannten Menüpunkte nicht mehr sichtbar.

Wir empfehlen dir, ein Newsletter-Plugin zu nutzen. Du findest alle verfügbaren Newsletter-Plugins im link:https://marketplace.plentymarkets.com/[plentyMarketplace^]. Ein Datum für das Ende der Bereitstellung des in plentymarkets integrierten Newsletters und CleverReach folgt in Kürze. +
Die folgenden Menüpunkte bleiben weiterhin in allen Systemen bestehen und werden _nicht_ entfernt, weil diese auch für Newsletter-Plugins relevant sind:

* Einrichtung » CRM » Newsletter » plentymarkets » E-Mail-Ordner
* Einrichtung » CRM » Newsletter » plentymarkets » E-Mails
* Einrichtung » CRM » Newsletter » plentymarkets » E-Mail-Filter

====

Auf dieser Handbuchseite ist beschrieben, welche Einstellungen du vornehmen musst, um Newsletter mit plentymarkets an deine xref:crm:kontakte.adoc#[Kontakte] zu versenden. Versende deine Newsletter z.B. mit dem in plentymarkets xref:crm:newsletter-versenden.adoc#100[integrierten Newsletter-Dienst], über die integrierte Schnittstelle zu xref:crm:newsletter-versenden.adoc#1700[CleverReach] oder übere weitere im link:https://marketplace.plentymarkets.com/plugins/integration[plentyMarketplace^] verfügbare E-Mail-Marketing- und Newsletter-Plugins.

[#100]
== In plentymarkets integrierten Newsletter-Dienst einrichten

In den folgenden Unterkapiteln erfährst du, wie du den in plentymarkets integrierten Newsletter-Dienst einrichtest.

[TIP]
.Double-Opt-In-Methode
====
In plentymarkets wird die Double-Opt-In-Methode verwendet, d.h. Empfänger:innen erhalten nach Bestellung des Newsletters eine E-Mail mit einem Bestätigungslink. Erst nachdem die Empfänger:innen auf den Link geklickt haben, sind diese Personen für den Newsletter angemeldet. Diese Methode ist fest integriert und kann nicht geändert werden.
====

[#200]
=== Newsletter-Zugangsdaten eingeben

Im Menü *Einrichtung » Mandant » [Mandant wählen] » E-Mail » Newsletter* gibst du die Zugangsdaten ein, um den in plentymarkets integrierten Newsletter-Dienst zu nutzen.

[.instruction]
Newsletter-Zugangsdaten eingeben:

. Öffne das Menü *Einrichtung » Mandant » [Mandant wählen] » E-Mail » Newsletter*.
. Nimm die gewünschten Einstellungen vor. Beachte dazu die Erläuterungen in <<#table-newsletter-login-details>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[[table-newsletter-login-details]]
.Newsletter-Zugangsdaten eingeben
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Name des Absenders*
|Gib deinen eigenen Namen oder den Namen deines plentyShops ein. Der Name wird den Empfänger:innen angezeigt.

| *E-Mail-Adresse*
|Gib die E-Mail-Adresse ein, wie sie auch im E-Mail-Programm steht. Über diese E-Mail-Adresse wird der Newsletter versendet.

| *Postausgangsserver / SMTP-Server*
|Gib den Postausgangsserver wie vom Provider angegeben ein (meist smtp.domain.de oder mail.domain.de). +
*_mailbox.org:_* Gib für Postfächer bei mailbox.org den Postausgangsserver *smtp.mailbox.org* ein und wähle die Verschlüsselung *SSL*.

| *Benutzername*
|Gib den Benutzer:innenname zu der E-Mail-Adresse ein. +
*_mailbox.org:_* Der mailbox.org-Benutzer:innenname ist die vollständige E-Mail-Adresse des mailbox.org-Postfachs.

| *Passwort*
|Gib das Passwort zu dem Benutzer:innenname und der E-Mail-Adresse ein.

| *Port (Standardport: 25)*
|Gib den Wert *25* ein. Dieser Wert ist für fast alle Provider korrekt. Erfrage ggf. den korrekten Port beim Provider. +
*_mailbox.org:_* Gib für Postfächer bei mailbox.org den Port *465* ein und wähle die Verschlüsselung *SSL*.

| *Verschlüsselung*
| Wähle *SSL*, *TLS* oder *keine Verschlüsselung*. +
*_mailbox.org:_* Wähle für Postfächer bei mailbox.org die Verschlüsselung *SSL*. +
Weitere Informationen findest du im Kapitel xref:crm:e-mails-versenden.adoc#200[Verschlüsselung der E-Mail-Kommunikation wählen] auf der Handbuchseite xref:crm:e-mails-versenden.adoc#[E-Mails].
|====

[#300]
=== E-Mail-Ordner erstellen

Im Menü *Einrichtung » CRM » Newsletter » plentymarkets » E-Mail-Ordner* erstellst du Ordner für den Versand von Newslettern. In diesen Ordnern speicherst du dann die E-Mail-Adressen deiner Kund:innen. Dies ermöglicht den Versand von Newslettern auf bestimmte Zielgruppen. Gehe wie im Folgenden beschrieben vor, um einen neuen E-Mail-Ordner zu erstellen.

[.instruction]
E-Mail-Ordner erstellen:

. Öffne das Menü *Einrichtung » CRM » Newsletter » plentymarkets » E-Mail-Ordner*.
. Gib im Bereich *Neuen E-Mail-Ordner anlegen* einen Namen für den Ordner ein.
. Ändere ggf. die ID des Ordners.
. Nimm die gewünschten Einstellungen vor. Beachte dazu die Erläuterungen in <<#table-create-email-folder>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Der E-Mail-Ordner wird erstellt und in der Übersicht angezeigt.

[[table-create-email-folder]]
.E-Mail-Ordner für den Versand von Newslettern erstellen
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *ID*
|Wird beim Erstellen eines neuen Ordners fortlaufend vergeben. Du kannst die Ordner-ID kann beim Erstellen eines neuen Ordners ändern. Die ID `0` kann nicht vergeben werden. +
*_Hinweis:_* Gib eine eindeutige ID ein. Wird eine bereits bestehende ID eingegeben, wird der ursprüngliche Ordner überschrieben.

| *Bezeichnung*
|Dies ist der Name des E-Mail-Ordners. Wird die Option *Auswählbar durch Kunden* aktiviert, ist der Name für Kund:innen im plentyShop sichtbar.

| *Auswählbar durch Kunden*
|Aktiviere diese Option, wenn der Ordner von Kund:innen in deinem plentyShop gewählt werden soll. Der Ordner wird im Bereich *Mein Konto* des plentyShops angezeigt. Kund:innen wählen dann Newsletter anhand der dort verfügbaren Ordner.

| *Position*
|Gib die Position ein, um festzulegen, in welcher Reihenfolge die Ordner angezeigt werden sollen.

| *Sichtbarkeit*
|Lege fest, ob der Newsletter-Ordner nur für den Standard-Webshop oder für alle Webshops sichtbar sein soll. Mit der Einstellung *Keiner* wird die Sichtbarkeit des Ordners deaktiviert.

| *Löschen*
|Aktiviere diese Option und klicke auf *Speichern*, um den Ordner zu löschen.
|====

[#400]
=== E-Mail-Ordner bearbeiten

Bestehende E-Mail-Ordner bearbeitest du ebenfalls im Menü *Einrichtung » CRM » Newsletter » plentymarkets » E-Mail-Ordner*. Gehe wie im Folgenden beschrieben vor, um die Einstellungen eines E-Mail-Ordners zu bearbeiten.

[.instruction]
E-Mail-Ordner bearbeiten:

. Öffne das Menü *Einrichtung » CRM » Newsletter » plentymarkets » E-Mail-Ordner*.
. Nimm die gewünschten Änderungen vor. Beachte dazu die Erläuterungen in <<#table-create-email-folder>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#500]
=== E-Mail-Adressen dem Newsletter-Hauptordner zuordnen

Füge das ShopBuilder-Widget *Newsletter* in deinen plentyShop ein, damit deine Kund:innen sich für deinen Newsletter anmelden können. Über das Widget wählst du den E-Mail-Ordner, der automatisch mit der E-Mail-Adresse einer Person verknüpft wird, wenn diese Person den Newsletter im plentyShop abonniert.

Wie du dazu vorgehen musst, ist auf der Handbuchseite xref:webshop:shop-builder.adoc#_newsletter[ShopBuilder einrichten] beschrieben. Wirf zudem auch gerne einen Blick in unser Webinar xref:webshop:shopbuilder-startseite-aktionsseite.adoc#[ShopBuilder - Startseite und Aktionsseite für den Webshop]. Dort wird ab Minute 22:10 erklärt, wie du das Newsletter-Widget in deinem plentyShop einbindest.

[#600]
=== Newsletter-Wahl für Kund:innen erlauben

Lasse deine Kund:innen selbst bestimmen, welche Newsletter sie von dir erhalten. Das ist z.B. von Vorteil, wenn du regelmäßig Newsletter zu verschiedenen Themenbereichen versendest. Deine Kund:innen können alle E-Mail-Ordner, die du unter der Option *Auswählbar durch Kunden* in <<#table-create-email-folder>> aktiviert hast, im Bereich *Mein Konto* des plentyShops wählen. Die E-Mail-Adresse dieser Person wird dann in diesem E-Mail-Ordner in deinem plentymarkets System gespeichert.

[#700]
=== E-Mail-Vorlage erstellen

Versende deine Bestätigungs-E-Mail per E-Mail-Vorlage. Nutze Template-Variablen, damit die Vorlage beim Versenden automatisch den richtigen Namen der Person, die die Vorlage erhalten soll, sowie den Bestätigungslink enthält. Gehe wie im Folgenden beschrieben vor, um die E-Mail-Vorlage zu erstellen.

[IMPORTANT]
.Template-Variablen und Template-Funktionen beachten
====
In plentymarkets steht dir eine umfangreiche Auswahl an Template-Variablen und Template-Funktionen für deine E-Mail-Vorlagen zur Verfügung. Öffne die E-Mail-Vorlage und klicke auf *Template-Variablen -und Funktionen* (icon:code[role="blue"]). Kopiere aus diesem Bereich die Template-Variable bzw. Template-Funktion und füge diese in der E-Mail-Vorlage im Tab *E-Mail-Nachricht* in den reinen Text oder in den HTML-formatierten Text an der gewünschten Stelle ein.

Weitere Informationen findest du auf der Handbuchseite xref:crm:e-mails-versenden.adoc#[E-Mails].
====

[.instruction]
E-Mail-Vorlage erstellen:

. Öffne das Menü *Einrichtung » Mandant » [Mandant wählen] » E-Mail » Vorlagen*.
. Klicke auf *Neue E-Mail-Vorlage* (icon:plus-square[role="green"]). +
→ Das Fenster *Neue E-Mail-Vorlage* wird geöffnet.
. Gib den Namen für die E-Mail-Vorlage ein.
. Wähle einen Eigner aus der Dropdown-Liste.
. Klicke auf *Speichern* (icon:save[role="green"]). +
→ Die E-Mail-Vorlage wird erstellt und abhängig von der gewählten Einstellung in der Dropdown-Liste *Eigner* in einem der 3 Ordner gespeichert. Beachte dazu die Erläuterung zu *Eigner* in <<#table-create-email-template>>.
. Nimm die gewünschten Einstellungen vor. Beachte dazu die Erläuterungen in <<#table-create-email-template>>.
. Füge die Template-Variable `$CustomerFullName` in den Text der E-Mail ein. +
→ Diese Template-Variable gibt den Vornamen und den Nachnamen der Person aus, die die E-Mail-Vorlage erhalten soll.
. Füge die Template-Variable `$NewsletterConfirmURL` in den Text der E-Mail ein. +
→ Diese Template-Variable gibt den Bestätigungslink aus.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

Wenn Empfänger:innen der E-Mail auf den durch die Template-Variable `$NewsletterConfirmURL` eingefügten Link  klicken, bestätigen sie die Anmeldung zum Newsletter und erhalten ab sofort Newsletter an ihre E-Mail-Adresse.

Wenn du die xref:crm:newsletter-versenden.adoc#800[Double-Opt-In-Methode] verwenden möchtest, ist ein weiterer Schritt notwendig. Du musst jeweils eine Vorlage erstellt haben und diese im Menü *Einrichtung » Assistent » Grundeinrichtung* » Assistent: *E-Mail-Konten* » Schritt: *Automatischer Versand* für die Ereignisse *Newsletter Opt-In* und *Bestätigung Newsletter Opt-In* gewählt haben.


[[table-create-email-template]]
.Neue E-Mail-Vorlage für den Newsletter-Versand erstellen
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Speichern*
|Speichert (icon:save[role="green"]) die Einstellungen in der E-Mail-Vorlage.

| *Template-Variablen -und Funktionen*
|Mit einem Klick auf icon:code[role="blue"] wird der Bereich *Template-Variablen -und Funktionen* geöffnet, aus dem die Template-Variablen bzw. Template-Funktionen für die E-Mail-Vorlage kopiert werden.

2+^| *Tab: Einstellungen*

| *Eigner*
|Wenn der Name des Eigners bereits beim Erstellen aus der Dropdown-Liste gewählt wurde, wird hier der Name des Eigners angezeigt. Andernfalls Eigner aus der Dropdown-Liste wählen. Diese Einstellung kann jederzeit geändert werden. +
*Alle* = Die Vorlage wird unter *Allgemeine E-Mail-Vorlagen* gespeichert. +
Eigener Benutzer:innenname = Die Vorlage wird unter *Meine E-Mail-Vorlagen* gespeichert. +
Anderer Benutzer:innenname = Die Vorlage wird unter *E-Mail-Vorlagen anderer Benutzer* gespeichert. +
*_Hinweis:_* Um eine eigene E-Mail-Vorlage unter *Meine E-Mail-Vorlagen* zu erstellen, muss man als Benutzer:in im System eingeloggt sein.

| *Name*
|Wenn der Name der E-Mail-Vorlage bereits beim Erstellen eingegeben wurde, wird hier der Name der E-Mail-Vorlage angezeigt. Gib ansonsten einen anderen Namen ein, unter dem diese Vorlage gespeichert werden soll. +
Du kannst den Namen jederzeit ändern. Der Name wird den Empfänger:innen _nicht_ angezeigt.

| *Inhalt*
|Wähle, ob die Nachricht als *reiner Text* oder als *HTML-formatierte Nachricht* gespeichert werden soll.

| *Template-Typ*
|Wähle, in welchem Bereich die E-Mail-Vorlage als Auswahl zur Verfügung steht. Mögliche Optionen: *Alle* (Standardeinstellung), *Auftrag*, *Kunden*, *Webshop*, *Ticket* oder *Scheduler*. +
*Alle* / *Webshop* = Die E-Mail-Vorlage steht in allen Bereichen als Auswahl zur Verfügung. +
*Auftrag* = Die E-Mail-Vorlage steht ausschließlich für den gewählten Bereich als Auswahl zur Verfügung. Die Vorlage ist in anderen Bereichen _nicht_ sichtbar. Wenn das Ticket mit einem Auftrag verknüpft ist, sind E-Mail-Vorlagen mit dem Template-Typ *Auftrag* ebenfalls im Ticket wählbar. +
*Kunden* = Die E-Mail-Vorlage steht ausschließlich für den gewählten Bereich als Auswahl zur Verfügung. Die Vorlage ist in anderen Bereichen _nicht_ sichtbar. +
*Ticket* = Die E-Mail-Vorlage steht ausschließlich für den gewählten Bereich als Auswahl zur Verfügung. Die Vorlage ist in anderen Bereichen _nicht_ sichtbar. +
*Scheduler* = Die E-Mail-Vorlage steht in allen Bereichen, in denen auch der Template-Typ *Auftrag* sichtbar ist, als Auswahl zur Verfügung.

| *PDF-Anhang*
|Wähle einen Anhang aus der Dropdwon-Liste. Die Dokumente, die hier in der Dropdown-Liste zur Verfügung stehen, werden u.a. im Menü *Aufträge » Fulfillment* oder durch versandbezogene Prozesse erzeugt.

| *Dokumentenanhang*
|Wähle auf Wunsch unter *CMS » Dokumente* hochgeladene eigene Dokumente, die an die E-Mail-Vorlage anhängt werden sollen. +
 Alle E-Mail-Vorlagen können mit bis zu 2 Anhängen standardisiert an deine Kund:innen versendet werden: PDF-Dokumente aus dem Bereich Fulfillment (z.B. Rechnungen) oder andere Dateien (z.B. ein Artikelprospekt oder eine Anleitung). Für die Vorlage *Eingangsbestätigung Webshop Bestellung* wären z.B. die Widerrufsbelehrung und die AGB im PDF-Format eine sinnvolle Ergänzung.

| *Antwort an*
|Gib die E-Mail-Adresse ein, an die die Antworten auf diese E-Mail-Vorlage gesendet werden sollen. Wenn keine E-Mail-Adresse eingegeben ist, werden Antworten auf diese Vorlage standardmäßig an die im Assistenten *E-Mail-Konten* im Schritt *Zugangsdaten*  xref:crm:e-mails-versenden.adoc#100[gespeicherte E-Mail-Adresse] versendet. Beispielsweise ist es sinnvoll, die E-Mail-Adresse der Buchhaltungsabteilung für die E-Mail-Vorlage *PDF-Rechnung* einzugeben. So gehen z.B. Rückfragen zur Rechnung direkt an die Buchhaltungsabteilung und müssen nicht weitergeleitet werden.

| *Design verwenden*
|Aktiviere diese Option, wenn der Inhalt der E-Mail mit dem im Menü *Einrichtung » Mandant » [Mandant wählen] » E-Mail » HTML-Design* xref:crm:e-mails-versenden.adoc#800[gespeicherten Design] versendet werden soll. Wenn du die Option _nicht_ aktivierst, wird nur der Inhalt der E-Mail-Vorlage verwendet.

| *Mandant (Shop)*
|Aktiviere einen, mehrere oder *ALLE* Mandanten (Shops). Die E-Mail-Vorlage ist nur für die gewählten Mandanten (Shops) gültig.

2+^| *Tab: E-Mail-Nachricht*

| *Sprache wählen*
|Die Sprache wird hier angezeigt und kann geändert werden.

| *Betreff*
|Gib den Betreff ein. Wähle dabei den Betreff mit großer Sorgfalt, damit die E-Mails im Postfach deiner Kund:innen leicht erkennbar sind und nicht dem Spam-Filter zum Opfer fallen.

| *Inhalt / Artikelliste*
|Gib in diese Tabs den Text bzw. die Artikelauflistung als *reinen Text* oder als *HTML-formatierten Text* ein. Für den Inhalt stehen verschiedene Template-Variablen und Template-Funktionen zur Verfügung. +
*_Hinweis:_* Nur der Inhalt des Tabs, dessen Inhaltstyp im Tab *Einstellungen* unter *Inhalt* festgelegt wurde, wird berücksichtigt. Wenn dort also z.B. *Nur reiner Text* eingestellt wurde, jedoch nur das Tab *HTML-formatierter Text* Inhalt enthält, wird _keine_ E-Mail versendet.
|====

[#800]
=== E-Mail-Vorlagen mit der Double-Opt-In-Funktion verknüpfen

Im nächsten Schritt verknüpfst du die soeben erstellte E-Mail-Vorlage mit der Double-Opt-In-Funktion und wählst eine weitere Vorlage für das Ereignis *Bestätigung Newsletter Opt-In*. Bei der Double-Opt-In-Methode müssen die Empfänger:innen nach Anmeldung zum Newsletter die Newsletter-Anmeldung in einem zweiten Schritt bestätigen.

[TIP]
.Hinweise zur Double-Opt-In-Methode
====
Wähle im Menü *Einrichtung » Assistenten » Grundeinrichtung* » Assistent: *E-Mail-Konten* » Schritt: *Automatischer Versand* 2 xref:crm:newsletter-versenden.adoc#700[zuvor erstellte] Vorlagen für die Ereignisse *Newsletter Opt-In* und *Bestätigung Newsletter Opt-In*. Die gewählte Vorlage unter *Newsletter Opt-In* wird versendet, wenn eine Person sich für deinen Newsletter anmeldet. Diese Vorlage sollte den Bestätigungslink enthalten, den die Person anklicken muss, um die Newsletter-Anmeldung abzuschließen. Den Bestätigungslink bildest du mit der Template-Variable `$NewsletterConfirmURL`, die die URL zur Bestätigung der Newsletter-Anmeldung beinhaltet, ab. Die gewählte Vorlage unter *Bestätigung Newsletter Opt-In* wird versendet, sobald die Person den Bestätigungslink aktiviert hat.

Im Kontaktdatensatz im Menü *CRM » Kontakte » [Kontakt öffnen]* im Bereich *Kontaktdetails* wird die Option *Newsletter* automatisch aktiviert, wenn die Person sich im Bestellvorgang für den Newsletter angemeldet und die Newsletter-Anmeldung über den Bestätigungslink bestätigt hat.
====

[.instruction]
E-Mail-Vorlagen mit der Double-Opt-In-Funktion verknüpfen:

. Öffne das Menü *Einrichtung » Assistenten » Grundeinrichtung*. 
. Öffne den Assistenten *E-Mail-Konten*.
. Wähle im Schritt *Automatischer Versand* für die Option *Newsletter Opt-In* die soeben erstellte E-Mail-Vorlage aus der Dropdown-Liste.
. Wähle im Schritt *Automatischer Versand* für die Option *Bestätigung Newsletter Opt-In* die E-Mail-Vorlage aus der Dropdown-Liste.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

Den Status der Bestätigung siehst du im Menü *Einrichtung » CRM » Newsletter » plentymarkets » E-Mails*. Bei Personen, die den Newsletter-Bezug nach der vorstehend beschriebenen Vorgehensweise bestätigt haben, ist dies am Status *[green]#bestätigt#* zu erkennen. Bei Personen, die das Double-Opt-in nicht oder noch nicht durchgeführt haben, steht dort *[red]#nicht bestätigt#*.

Die *IP-Adresse* und die verwendete *Bestätigungs-URL* einer Bestätigung werden in der Datenbank gespeichert. Diese Daten lassen sich anschließend über einen link:https://developers.plentymarkets.com/rest-doc/newsletter/details#list-a-recipient[REST-Call^] abrufen. Im Backend erfolgt keine Anzeige.

[#900]
=== E-Mail-Adresse speichern

E-Mail-Adressen für den Versand von Newslettern werden in verschiedenen Ordnern gespeichert. Im Menü *Einrichtung » CRM » Newsletter » plentymarkets » E-Mails* verwaltest du die E-Mail-Adressen der verfügbaren Ordner. Falls du noch keine xref:crm:newsletter-versenden.adoc#300[Ordnerstruktur] für deine Newsletter angelegt hast, empfiehlt es sich, dies vorab zu tun.

Gehe wie im Folgenden beschrieben vor, um eine E-Mail-Adresse in einem E-Mail-Ordner zu speichern.

[.instruction]
E-Mail-Adresse speichern:

. Öffne das Menü *Einrichtung » CRM » Newsletter » plentymarkets » E-Mails*.
. Klappe den Ordner auf (icon:plus-square-o[]).
. Klappe den Bereich *Neue E-Mail-Adresse* (icon:plus-square-o[]) auf.
. Nimm die gewünschten Einstellungen vor. Beachte dazu die Erläuterungen in <<#table-save-email-address>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[[table-save-email-address]]
.Einstellungen zum Speichern einer neuen E-Mail-Adresse
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Vorname*
|Gib den Vornamen der Person ein.

| *Nachname*
|Gib den Nachnamen der Person ein.

| *E-Mail*
|Gib die E-Mail-Adresse der Person ein.

| *Ordner*
|Wähle den xref:crm:newsletter-versenden.adoc#300[E-Mail-Ordner], in dem die Daten gespeichert werden sollen.
|====

[#1000]
=== Newsletter erstellen

Neue Newsletter erstellst du wie im Folgenden beschrieben. Du kannst so auch bestehende Newsletter bearbeiten.

[.instruction]
Newsletter erstellen:

. Öffne das Menü *CRM » Newsletter*.
. Klappe den Bereich *Neuer Newsletter* (icon:plus-square-o[]) auf. +
→ Das Bearbeitungsfenster für den neuen Newsletter wird geöffnet.
. Nimm die gewünschten Einstellungen vor. Beachte dazu die Erläuterungen in <<#table-create-newsletter>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[[table-create-newsletter]]
.Einstellungen zum Erstellen eines Newsletters
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Platzhalter*
|Listet auf, welche Platzhalter vom System erkannt und in der Nachricht ersetzt werden. +
Aktuell mögliche Platzhalter: +
*+[NAME]+* = Vorname und Nachname des Empfängers +
*+[EMAIL]+* = E-Mail-Adresse des Empfängers +
*+[RECIPIENTID]+* = ID des Empfängers +
//*+[FOLDERID]+* = ID des Newsletter-Ordners


| *Bilder-Galerie*
|Öffnet das Menü *CMS » Webspace*. +
Lade dort ein Bild hoch (material:file_upload[]), kopiere den Link mit einem Klick auf material:content_copy[] in die Zwischenablage, wechsele zurück in das Newsletter-Menü und klicke im Editor im Bereich *HTML Newsletter* auf *Bild*. Das Fenster *Bild-Eigenschaften* öffnet sich. Füge dort im Tab *Bild-Info* den kopierten Link zum Bild in das Feld *URL* ein, gib einen alternativen Text ein und füge im Tab *Link* den kopierten Link erneut in das Feld *URL* ein, um das Bild mit dem Newsletter zu verknüpfen.

| *Layout-Vorlage einspielen*
|Bei Klick auf *Layout-Vorlage einspielen* wird die Anrede *[Guten Tag]* sowie der Platzhalter *[NAME]* im Bereich *HTML Newsletter* eingesetzt. Für den Platzhalter wird beim Versenden automatisch der Name der Person, die den Newsletter erhalten soll, eingefügt.

| *Betreff*
|Gib den Betreff für den Newsletter ein.

| *Editor*
|Der *CKEditor* ist vorausgewählt. Wähle ggf. einen anderen Editor aus der Dropdown-Liste.

| *HTML Newsletter*
|Gib den Inhalt des Newsletters als HTML-Code ein. +
*_Wichtig:_* Texte können nur in einem Bereich gespeichert werden. Gib daher entweder im Bereich *HTML Newsletter* oder im Bereich *Text Newsletter* Inhalte ein.

| *Text Newsletter*
|Gib den Inhalt des Newsletters in reiner Textform ein. +
*_Wichtig:_* Texte können nur in einem Bereich gespeichert werden. Gib daher entweder im Bereich *HTML Newsletter* oder im Bereich *Text Newsletter* Inhalte ein.

|====

[#1100]
=== Personen anhand der E-Mail-Adresse oder des Nachnamen suchen

Gehe wie im Folgenden beschrieben vor, um eine E-Mail-Adresse in einem E-Mail-Ordner zu suchen. Suche Kund:innen entweder anhand der E-Mail-Adresse oder des Nachnamens.

[.instruction]
Personen anhand der E-Mail-Adresse oder des Nachnamen suchen:

. Öffne das Menü *Einrichtung » CRM » Newsletter » plentymarkets » E-Mails*.
. Klappe den E-Mail-Ordner auf (icon:plus-square-o[]).
. Wähle aus der Dropdown-Liste die Einstellung *E-Mail-Adresse* oder *Nachname*, um anhand dieser Einstellung zu suchen.
. Gib die E-Mail-Adresse bzw. den Nachnamen der Person in das Suchfeld ein.  +
→ Für die Suche ist es ausreichend, wenn du nur einen Teil des Namens oder der E-Mail-Adresse eingibst. Lasse das Feld leer, um alle E-Mail-Adressen bzw. Nachnamen anzuzeigen.
. Klicke auf *Suche* (icon:search[role="blue"]). +
→ Das Suchergebnis wird angezeigt.

Im Suchergebnis wird auch der Status der Bestätigung angezeigt. In plentymarkets wird die xref:crm:newsletter-versenden.adoc#800[Double-Opt-In-Methode] verwendet. Dabei erhalten Empfänger:innen nach dem Bestellen des Newsletters eine E-Mail mit einem Link, über den sie die Newsletter-Bestellung bestätigen müssen. Kunden:innen, die den Newsletter-Bezug so bestätigt haben, erkennst du an dem Status *[green]#bestätigt#*. Andernfalls steht dort *[red]#nicht bestätigt#*.

[#1200]
=== E-Mail-Adresse bearbeiten

Nachdem du eine E-Mail-Adresse über die Suchfunktion gefunden hast, kannst du die Daten für diese Person bearbeiten. Ändere z.B. die E-Mail-Adresse der Person oder verschiebe den Kontaktdatensatz in einen anderen E-Mail-Ordner. Gehe dazu wie im Folgenden beschrieben vor.

[.instruction]
E-Mail-Adresse bearbeiten:

. Öffne das Menü *Einrichtung » CRM » Newsletter » plentymarkets » E-Mails*.
. Suche die Person wie im Kapitel xref:crm:newsletter-versenden.adoc#1100[Personen anhand der E-Mail-Adresse oder des Nachnamen suchen] beschrieben.
. Klappe die Daten der Person auf (icon:plus-square-o[]).
. Nimm die gewünschten Änderungen vor. Beachte dazu die Erläuterungen in <<#table-save-email-address>> im Kapitel xref:crm:newsletter-versenden.adoc#900[E-Mail-Adresse speichern].
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#1300]
=== E-Mail-Adressen exportieren und importieren

In den vorigen Kapiteln ist beschrieben, wie du eine einzelne E-Mail-Adresse verwaltest. Wenn du mehrere E-Mail-Adressen gleichzeitig bearbeiten möchtest, ist es sinnvoll, mit dem xref:daten:ElasticSync.adoc#[Import-Tool] zu arbeiten. Importiere neue und bearbeite bestehende E-Mail-Adressen mit dem Import-Typ xref:daten:elasticSync-newsletter-empfaenger.adoc#[Newsletter-Empfänger].

Du kannst die E-Mail-Adressen auch exportieren. Erstelle dazu im Menü *Daten » FormatDesigner* zunächst das xref:daten:FormatDesigner.adoc#[Exportformat] und exportiere die Daten anschließend über den xref:daten:elastischer-export.adoc#[elastischen Export].

[#1400]
=== Daten von Kund:innen in einen E-Mail-Ordner kopieren

Im Menü *Einrichtung » CRM » Newsletter » plentymarkets » E-Mail-Filter* filterst du nach Daten von Kund:innen und kopierst die E-Mail-Adressen dieser Kund:innen in bestimmte E-Mail-Ordner. Du hast z.B. die Möglichkeit, nach Kund:innen zu suchen, die bestimmte Artikel in einem bestimmten Zeitraum erworben haben. Verwende die Ordner dann für den xref:crm:newsletter-versenden.adoc#1000[Newsletter-Versand] im Menü *CRM » Newsletter*, um Newsletter an diese Kundengruppen zu senden.

Gehe wie im Folgenden beschrieben vor, um Daten von Kund:innen in einen E-Mail-Ordner zu kopieren.

[.instruction]
Daten von Kund:innen in einen E-Mail-Ordner kopieren:

. Öffne das Menü *Einrichtung » CRM » Newsletter » plentymarkets » E-Mail-Filter*.
. Nimm die gewünschten Einstellungen im Bereich *Alle Kundendaten in E-Mail-Ordner kopieren* vor. Beachte dazu die Erläuterungen in <<#table-copy-customer-data>>.
. Klicke auf *E-Mails in Ordner übertragen* (icon:cog[]).

[[table-copy-customer-data]]
.Kundendaten in einen E-Mail-Ordner kopieren
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Newsletter-Anmeldung*
|Wähle eine der folgenden Optionen: +
*ALLE* = Die Daten aller Kund:innen, die den Newsletter bestellt haben, werden in den E-Mail-Ordner kopiert. Umfasst sowohl Kund:innen, die den Newsletter-Empfang mit der xref:crm:newsletter-versenden.adoc#800[Double-Opt-In-Methode] bestätigt haben, als auch Kund:innen, die dies noch nicht getan haben. +
*Nur Kunden, welche dem Empfang von Newslettern zugestimmt haben* = Nur die Daten von Kund:innen, die den Newsletter-Empfang bestätigt haben, werden in den E-Mail-Ordner kopiert.

| *Land*
|Wähle ein Land, um nur Kund:innen aus diesem Land zu filtern. Dies ermöglicht es zum Beispiel, unterschiedliche Newsletter an Kund:innen in Deutschland und in Österreich zu versenden.

| *E-Mail-Ordner*
|Wähle einen E-Mail-Ordner. Die Daten der Kund:innen werden in diesen E-Mail-Ordner kopiert.
|====

[#1500]
=== Daten von Kund:innen filtern

Mit dem Filter filterst du die Daten deiner Kund:innen noch genauer. Gehe wie im Folgenden beschrieben vor, um die Daten zu filtern und in einen E-Mail-Ordner zu kopieren.

[.instruction]
Kundendaten filtern:

. Öffne das Menü *Einrichtung » CRM » Newsletter » plentymarkets » E-Mail-Filter*.
. Nimm die gewünschten Einstellungen im Bereich *Kundenfilter* vor. Beachte dazu die Erläuterungen in <<#table-filter-customer-data>>.
. Klicke auf *Vorschau* (icon:eye[role="blue"]), um die Daten anzuzeigen. +
→ Der Bereich *Vorschau* wird mit den Daten der Kund:innen eingeblendet. Prüfe das Ergebnis.
. Klicke auf *E-Mails in Ordner übertragen* (icon:cog[]).

[[table-filter-customer-data]]
.Einstellungen für den Kundenfilter
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Mindestbestellwert*
|Gib einen Mindestbestellwert ein, um nach Kund:innen zu filtern, die ab diesem Bestellwert eingekauft haben.

| *Kategorie 1-3*
|Wähle bis zu 3 Kategorieebenen, um nach Kund:innen zu filtern, die Artikel in dieser Kategorie oder Unterkategorie gekauft haben.

| *Artikel-ID*
|Gib eine oder mehrere Artikel-IDs ein, um nach Kund:innen zu filtern, die diese Artikel gekauft haben.

| *Bestellzeitpunkt*
|Gib einen Zeitraum ein oder wähle das Datum aus dem Kalender, um nach Kund:innen zu filtern, die innerhalb dieses Zeitraums bestellt haben. Wenn kein Datumsfilter angewendet werden soll, aktiviere die Option *Kein Bestellzeitpunkt*.

| *Land*
|Wähle ein Land, um nur Kund:innen aus diesem Land zu filtern. Dies ermöglicht es zum Beispiel, unterschiedliche Newsletter an Kund:innen in Deutschland und in Österreich zu versenden.

| *Mandant (Shop)*
|Wähle einen Mandant (Shop), um nach Kund:innen zu filtern, die Artikel bei diesem Mandanten (Shop) gekauft haben.

| *Kundenklasse*
|Wähle eine xref:crm:vorbereitende-einstellungen.adoc#kundenklasse-erstellen[Kundenklasse], um nach Kund:innen zu filtern, die dieser Kundenklasse angehören.

| *Auftragsherkunft*
|Wähle eine Auftragsherkunft, um nach Kund:innen zu filtern, die Bestellungen über diese Auftragsherkunft vorgenommen haben.

| *Newsletter-Anmeldung*
|Wähle die Option *ALLE* oder *Nur Kunden, welche dem Empfang von Newslettern zugestimmt haben*. +
*ALLE* = Die Daten aller Kund:innen, die den Newsletter bestellt haben, werden in den E-Mail-Ordner kopiert. Umfasst sowohl Kund:innen, die den Newsletter-Empfang mit der xref:crm:newsletter-versenden.adoc#800[Double-Opt-In-Methode] bestätigt haben, als auch Kund:innen, die dies noch nicht getan haben. +
*Nur Kunden, welche dem Empfang von Newslettern zugestimmt haben* = Nur die Daten von Kund:innen, die den Newsletter-Empfang bestätigt haben, werden in den E-Mail-Ordner kopiert.

| *E-Mail-Ordner*
|Wähle einen E-Mail-Ordner. Die Daten werden in diesen E-Mail-Ordner kopiert.
|====

[#1600]
=== Newsletter versenden

Nachdem du die xref:crm:newsletter-versenden.adoc#700[E-Mail-Vorlage erstellt] und xref:crm:newsletter-versenden.adoc#800[verknüpft] und den xref:crm:newsletter-versenden.adoc#1000[Newsletter erstellt] hast, stellst du im Menü *CRM » Newsletter* ein, an welche der in den E-Mail-Ordnern gespeicherten E-Mail-Adressen der Newsletter gesendet werden soll. Außerdem legst du mit der Option *Filter* fest, ob der Newsletter an alle oder nur an bestätigte E-Mail-Adressen gesendet werden soll. Diese Einstellung nimmst du im Tab *Newsletter senden* des erstellten Newsletters vor.

[TIP]
.Eingeschränkter Newsletter-Versand am Tag
====
Beachte, dass dein Newsletter tagsüber eingeschränkt an deine Kund:innen versendet wird. In der Nacht wird der Versand einer größeren Anzahl von E-Mails erlaubt.

* Am Tag zwischen 8:00 und 0:00 Uhr: 60 E-Mails je Viertelstunde
* Nachts zwischen 0:00 und 8:00 Uhr: 500 E-Mails je Viertelstunde
====

[.instruction]
Newsletter versenden:

. Öffne das Menü *CRM » Newsletter*.
. Klappe den Newsletter, den du versenden möchtest, auf (icon:plus-square-o[]).
. Wechsele in das Tab *Newsletter versenden*.
. Wähle unter *Sende Newsletter an Gruppe* eine Gruppe aus der Dropdown-Liste.
. Wähle unter *Filter* die Option *ALLE* oder die Option *Nur an bestätigte E-Mail-Adressen*.
. Klicke auf *Senden* (icon:envelope-o[role="purple"]). +
→ Der Newsletter wird gemäß der oben gewählten Einstellungen versendet.

[#1650]
=== Link zum Abbestellen des Newsletters einfügen

Du solltest deinen Newsletter-Empfänger:innen jederzeit die Möglichkeit geben, deinen Newsletter wieder abzubestellen. Damit Empfänger:innen den Newsletter abbestellen können, musst du den Link zum Abbestellen in die Newsletter-Vorlage im Menü *CRM » Newsletter* oder in jede andere beliebige E-Mail-Vorlage im Menü *Einrichtung » Mandant » [Mandant wählen] » E-Mail » Vorlagen* einfügen.

Es ist möglich einen Abmelde-Link hinzuzfügen, der Empfänger:innen von allen Newsletter-Ordnern abmeldet (siehe Punkt 1) oder einen Link, der Empfänger:innen von einem bestimmten Newsletter-Ordner abmeldet (siehe Punkt 2):

. *+http://[Domain-Name]/?OrderShow=CancelNewsletter+* +
Wenn Empfänger:innen auf diesen Link klicken, werden sie aus allen Newsletter-Ordnern abgemeldet.

. *+http://[Domain-Name]/?OrderShow=CancelNewsletter&folderId=1+* +
Wenn Empfänger:innen auf diesen Link klicken, werden sie aus einem bestimmten Newsletter-Ordner abgemeldet. In diesem Beispiel handelt es sich um den Ordner mit der ID `1`.

Deine Domain findest du im Menü *Einrichtung » Mandant » [Mandant wählen] » Einstellungen*.

[#1700]
== Newsletter mit CleverReach versenden

Gehe wie im Folgenden beschrieben vor, um deine Newsletter mit link:https://www.cleverreach.de/[CleverReach^] an deine Kund:innen zu versenden.

[TIP]
.Export zu CleverReach greift auf Ordner mit ID 2 zu
====
*_Beachte:_* Der Export zu CleverReach greift automatisch auf den Newsletter-E-Mail-Ordner mit der ID 2 im Menü *Einrichtung » CRM » Newsletter » plentymarkets » E-Mail-Ordner* zu. 
====

[#1800]
=== Bei CleverReach registrieren

Registriere dich kostenlos auf der link:https://www.cleverreach.de/[Website von CleverReach^], um CleverReach in plentymarkets zu nutzen. Weitere Informationen zu den Einstellungen in CleverReach findest du in der link:http://support.cleverreach.de/hc/de[Hilfe^] von CleverReach.

[#1900]
=== CleverReach in plentymarkets einrichten

Gehe wie im Folgenden beschrieben vor, um die Schnittstelle zu CleverReach in plentymarkets einzurichten.

[TIP]
.Export zu CleverReach greift auf Ordner mit ID 2 zu
====
*_Beachte:_* Der Export zu CleverReach greift automatisch auf den Newsletter-E-Mail-Ordner mit der ID 2 im Menü *Einrichtung » CRM » Newsletter » plentymarkets » E-Mail-Ordner* zu. 
====

[.instruction]
CleverReach in plentymarkets einrichten:

. Öffne das Menü *Einrichtung » CRM » Newsletter » CleverReach*.
. Nimm die gewünschten Einstellungen vor. Beachte dazu die Erläuterungen in <<#table-set-up-cleverreach>>.
. Gib deinen *API-Key* ein.
. Gib die *Listen-ID* der in CleverReach angelegten Gruppe ein.
. *Speichere* (icon:save[role="green"]) die Einstellungen.
. Klicke auf *Standardattribute generieren* (icon:cog[]). +
→ Datenfelder werden in CleverReach erzeugt, damit die Daten der Kund:innen, die du überträgst, gespeichert werden.
. Öffne im CleverReach-Backend die Gruppe, deren ID du in plentymarkets eingegeben hast.
. Lösche die Datenfelder, deren Inhalt du nicht bei CleverReach verwenden möchtest. +
→ Aktuell werden die Datenfelder *Birthday (Geburtstag)*, *Vorname*, *Gender (Anrede)*, *Lang (Sprache)* und *Nachname* von plentymarkets an CleverReach übertragen.
. Wechsele zurück in das Menü *Einrichtung » CRM » Newsletter » CleverReach* des plentymarkets Backend.
. Aktiviere die Option *Automatische Übertragung (täglich)*, damit die Daten übertragen werden.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[[table-set-up-cleverreach]]
.Einstellungen für CleverReach vornehmen
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Gruppenattribute erzeugen*
|Erzeugt die Datenfelder (Gruppenattribute) für CleverReach.

| *Datenübertragung ausführen*
|Überträgt die Datenfelder (Gruppenattribute) an CleverReach. Aktuell werden die Datenfelder *Birthday (Geburtstag)*, *Vorname*, *Gender (Anrede)*, *Lang (Sprache)* und *Nachname* von plentymarkets an CleverReach übertragen. Wähle den Bereich aus der Dropdown-Liste. +
*_Hinweis:_* Führe die Übertragung der eigentlichen Daten aus. Beachte dazu die Anleitung weiter unten.

| *API-Key*
|Gib den API-Key ein, wie von CleverReach erhalten.

| *Listen-ID*
|Gib die Listen-ID aus CleverReach ein.

| *Auftragsherkünfte*
|Wähle die Auftragsherkünfte, die für CleverReach verfügbar sein sollen. Herkünfte, die keine Datenübertragung gestatten, sind standardmäßig _nicht_ gewählt. +
*_Hinweis:_* Prüfe die Auswahl der Auftragsherkünfte vor der Arbeit mit CleverReach, um potenzielle Abmahnungen zu vermeiden.

| *Export ab Auftragsstatus*
|Wähle den Status, ab dem die Daten exportiert werden sollen.

| *Automatische Übertragung (täglich)*
|Aktiviere die Option, wenn Daten täglich automatisch übertragen werden sollen.
|====

[IMPORTANT]
.Erste Übertragung
====
Bei der ersten automatischen Übertragung werden die Daten der Kund:innen der in den vorhergehenden 3 Tagen neu erstellten Kund:innen übertragen. Anschließend werden nur noch die Daten der Kund:innen übertragen, die seit der letzten Übertragung hinzugekommen sind.
====

Wenn du nicht allen Kund:innen schreiben möchtest, deren Daten du zu CleverReach übertragen hast, hast du in CleverReach Filtermöglichkeiten. Nähere Informationen hierzu findest du auf der Support-Seite von link:http://support.cleverreach.de/entries/21538892-wie-kann-ich-meine-empfanger-filtern[CleverReach^].

[#2000]
=== Daten manuell übertragen

Mit der Option *Datenübertragung ausführen* werden nur die Daten eines bestimmten Kundentyps übertragen. Dies bietet die Möglichkeit, die Kundentypen in separate Gruppen bei CleverReach einzuordnen.

[TIP]
.Export zu CleverReach greift auf Ordner mit ID 2 zu
====
*_Beachte:_* Der Export zu CleverReach greift automatisch auf den Newsletter-E-Mail-Ordner mit der ID 2 im Menü *Einrichtung » CRM » Newsletter » plentymarkets » E-Mail-Ordner* zu. 
====

[IMPORTANT]
.Automatische Übertragung sinnvoll?
====
Wenn du die Option *Datenübertragung ausführen* nutzt, um die Daten gefiltert nach Kundentyp zu übertragen, solltest du überlegen, ob die automatische Übertragung noch sinnvoll für dich ist, weil bei dieser Option unabhängig vom Kundentyp übertragen wird.
====

[.instruction]
Daten manuell übertragen:

. Öffne das Menü *Einrichtung » CRM » Newsletter » CleverReach*.
. Gib deinen *API-Key* ein.
. Gib die *Listen-ID* der in CleverReach angelegten Gruppe ein.
. *Speichere* (icon:save[role="green"]) die Einstellungen.
. Klicke auf *Standardattribute generieren* (icon:cog[]). +
→ Datenfelder werden in CleverReach erzeugt, damit die Daten, die du überträgst, gespeichert werden.
. Öffne im CleverReach-Backend die Gruppe, deren ID du in plentymarkets eingegeben hast.
. Lösche die Datenfelder, deren Inhalt du nicht bei CleverReach verwenden möchtest. +
→ Aktuell werden die Datenfelder *Birthday (Geburtstag)*, *Vorname*, *Gender (Anrede)*, *Lang (Sprache)* und *Nachname* von plentymarkets an CleverReach übertragen.
. Wechsele zurück in das Menü *Einrichtung » CRM » Newsletter » CleverReach* des plentymarkets Backend.
. Wähle aus der Dropdown-Liste *Datenübertragung ausführen* den Kundentyp.
. *Speichere* (icon:save[role="green"]) die Einstellungen.
. Klicke auf *Exportieren* (icon:cog[]). +
→ Die Kundendaten werden übertragen.
