= Offene Posten
:keywords: OP-Liste, offene Posten, OP, offener Betrag, Forderung, offene Forderung, Forderungen, offen, op, opliste, OPliste
:description: Erfahre, wie du mit der Offene Posten-Liste in plentysystems arbeitest und so einen Überblick über bezahlte und unbezahlte Beträge deiner Kontakte erhältst.
:author: team-order-core

Im Menü *CRM » OP-Liste* erhältst du eine Übersicht über offene Posten. Alle xref:crm:kontakte.adoc#[Kontakte] mit ausstehenden Forderungen werden aufgelistet.

[#vorbereitende-einstellungen]
== Vorbereitende Einstellungen

Im Menü *Einrichtung » CRM » Buchhaltung » Einstellungen* wählst du Standardeinstellungen für die xref:crm:op-liste.adoc#filtern[Suchfilter] der Offenen Posten-Tabelle. Beachte dazu die Erläuterungen in <<#table-default-settings-filters-ar-list>>.

[[table-default-settings-filters-ar-list]]
.Filtereinstellungen Offene Posten
[cols="1,3"]
|====
|Einstellung |Erläuterung

|[#intable-ar-list-default-filter-contact-type]*Filter Kundentyp*
|Lege fest, welche xref:crm:vorbereitende-einstellungen.adoc#typ-erstellen[Kundentypen] für den Filter *Kundentyp* in der OP-Liste zur Verfügung stehen sollen. Wählst du für diese Einstellung keine Kundentypen, werden im Filter *Gast* und *Kunde* zur Auswahl angeboten.

|[#intable-ar-list-default-filter-customer-class]*Filter Kundenklasse*
|Lege fest, welche Kundenklassen für den Filter *Kundenklasse* in der OP-Liste zur Verfügung stehen sollen. Wählst du für diese Einstellung keine Kundenklassen, werden im Filter immer alle erstellten xref:crm:vorbereitende-einstellungen.adoc#kundenklasse-erstellen[Kundenklassen] zur Auswahl angeboten.

|====

[TIP]
.Berechtigung für Benutzer:innen ohne Adminrechte vergeben
====
Damit für Benutzer:innen ohne Adminrechte die OP-Liste sichtbar ist, musst du die Option aktivieren. Öffne dazu die Rolle im Menü *Einrichtung » Kontoverwaltung » Rollen* und wähle im xref:business-entscheidungen:benutzerkonten-zugaenge.adoc#70[einfachen Modus] die Option *CRM > OP-Liste > Betrachten*. Anschließend musst du diese Rolle dem Benutzer:innenkonto xref:business-entscheidungen:benutzerkonten-zugaenge.adoc#110[zuweisen].
====

[#verwalten]
== Offene Posten verwalten

Die Tabelle im Menü *CRM » OP-Liste* enthält Informationen zum Kontakt sowie die Anzahl der offenen Posten eines Kontakts und die Höhe der Forderung, die sich aus den offenen Posten ergibt. Hat ein Kontakt eine offene Forderung überbezahlt, wird dieser Betrag mit weiteren ausstehenden Forderungen verrechnet. Bestehen keine weiteren Forderungen, wird in der Spalte *Forderung* ein Minusbetrag angezeigt. +
Beim Öffnen der OP-Liste wird dir immer eine bereits gefilterte Ansicht gezeigt. Gefiltert wird automatisch nach den Kundentypen *Kunde* und *Gast*. Über den xref:crm:op-liste.adoc#intable-ar-list-filter-contact-type[Filter Kundentyp] kannst du offene Forderungen für weitere Kundentypen anzeigen lassen.

Wenn du in der Zeile der Tabelle auf die Kontakt-ID klickst, wirst du zum xref:crm:kontakt-bearbeiten.adoc#erlaeuterungen-einzelne-bereiche[Kontaktdatensatz] des entsprechenden Kontakts weitergeleitet. Klicke dort auf der linken Seite auf *Konto*, um die offenen Beträge mit überschrittenem Zahlungsziel für diesen Kontakt anzuzeigen. Handelt es sich um eine Gastbestellung, wirst du bei Klicken in die Zeile zum entsprechenden Auftrag weitergeleitet.

Du kannst diese Tabelle individuell anpassen. Das bedeutet, dass du selbst entscheiden kannst, welche Informationen dir in den Tabellenspalten angezeigt werden. Gehe dafür folgendermaßen vor:

[.instruction]
Tabelle individualisieren:

. Klicke auf *Spalten konfigurieren* (material:settings[]). +
→ Das Fenster *Spalten konfigurieren* öffnet sich.
. Wähle, welche Spalten angezeigt werden sollen. Beachte dafür <<#table-ar-list>>.
. Verschiebe (material:drag_indicator[]) die Spalten, so dass sie in der Reihenfolge angezeigt werden, in der du sie brauchst.
. Klicke auf *Bestätigen*, um deine Auswahl zu speichern.

Wenn du die Tabelle einmal angepasst hast, wird diese Auswahl gespeichert. Du kannst das Layout jederzeit ändern. Die zu Verfügung stehenden Spalten findest du in <<#table-ar-list>>. Dort ist zu jeder Spalte auch die Information hinterlegt, ob es sich um eine Standardspalte handelt. Standardspalten werden angezeigt, wenn die Tabelle nicht individualisiert ist.

[[table-ar-list]]
.Tabelle Offene Posten
[cols="1,3"]
|====
|Einstellung |Erläuterung

| [#intable-ar-list-contact-id]*Kontakt-ID*
|Die Kontakt-ID des Kontaktes mit offenen Forderungen wird angezeigt. Durch Klick direkt auf die Kontakt-ID öffnet sich der Kontaktdatensatz des Kontaktes. +
Diese Spalte ist eine Standardspalte.

| [#intable-ar-list-type]*Typ*
|Der Kundentyp des Kontaktes mit offenen Forderungen wird angezeigt. +
Diese Spalte ist eine Standardspalte.

| [#intable-ar-list-first-name]*Vorname*
|Der Vorname des Kontaktes mit offenen Forderungen wird angezeigt. +
Diese Spalte ist eine Standardspalte.

| [#intable-ar-list-last-name]*Nachname*
|Der Nachname des Kontaktes mit offenen Forderungen wird angezeigt. +
Diese Spalte ist eine Standardspalte.

| [#intable-ar-list-email]*E-Mail*
|Die E-Mail-Adresse des Kontaktes mit offenen Forderungen wird angezeigt. +
Diese Spalte ist eine Standardspalte.

| [#intable-ar-list-company]*Firma*
|Die Firma des Kontaktes mit offenen Forderungen wird angezeigt, wenn diese im Kontaktdatensatz hinterlegt ist. +
Diese Spalte ist eine Standardspalte.

| [#intable-ar-list-client]*Mandant*
|Der Mandant des letzten Auftrages des Kontaktes mit offenen Forderungen wird angezeigt. +
Diese Spalte ist eine Standardspalte.

| [#intable-ar-list-last-order]*Letzter Auftrag*
|Das Datum des letzten Auftrages des Kontaktes mit offenen Forderungen wird angezeigt.  +
Diese Spalte ist eine Standardspalte.

| [#intable-ar-list-number-accounts-receivable]*Offene Posten*
|Die Anzahl der unbezahlten Aufträge des Kontaktes mit offenen Forderungen wird angezeigt. +
Diese Spalte ist eine Standardspalte.

| [#intable-ar-list-pending-amount]*Forderung*
|Die Höhe der Forderungen, also die offenen Beträge des Kontaktes mit offenen Forderungen, werden angezeigt. Hat ein Kontakt eine offene Forderung überbezahlt, wird dieser Betrag mit weiteren ausstehenden Forderungen verrechnet. Bestehen keine weiteren Forderungen, wird in dieser Spalte ein Minusbetrag angezeigt. +
Diese Spalte ist eine Standardspalte.

| [#intable-ar-list-customer-class]*Kundenklasse*
|Die Kundenklasse des Kontaktes mit offenen Forderungen wird angezeigt. +
Diese Spalte ist keine Standardspalte.

| [#intable-ar-list-rating]*Kundenbewertung*
|Die Kundenbewertung des Kontaktes mit offenen Forderungen wird angezeigt. +
Diese Spalte ist keine Standardspalte.

| [#intable-ar-list-country]*Land*
|Das Land der Rechnungsadresse des Kontaktes mit offenen Forderungen wird angezeigt. +
Diese Spalte ist keine Standardspalte.

| *Aktion*
| In dieser Spalte stehen dir verschiedene Aktionen zur Verfügung. Durch Klicken auf *Auftragssuche öffnen* (material:launch[]) wirst du zur Auftragsübersicht im Menü *Aufträge » Aufträge bearbeiten* weitergeleitet. Dort wird eine gefilterte Ansicht gezeigt. Dadurch siehst du direkt die unbezahlten und teilbezahlten nicht stornierten Aufträge der entsprechenden Kund:in. +
Durch Klicken auf *Messenger öffnen* (material:message[]) wirst du in den Bereich *Messenger* im Kontaktdatensatz des ausgewählten Kontakts weitergeleitet. +
Diese Spalte ist eine Standardspalte.

|====

In der letzten Zeile der Tabelle wird dir die Summe jeweils der Anzahl der *Offenen Posten* und der *Forderungen* angezeigt. In diesem Bereich wird immer das zusammengerechnet, was auf dem jeweiligen Tabellenblatt dargestellt ist. Umfasst die offene Posten Tabelle in deinem System also mehr Seiten als eine, werden hier nicht die offenen Posten und Forderungen der anderen Seiten hinzugezählt.

[#filtern]
== Offene Posten filtern

Dir stehen verschiedene Filtereinstellungen für die offene Posten-Tabelle zur Verfügung. Setze diese Filter im Menü *CRM » OP-Liste* mit einem Klick auf material:filter_alt[] und klicke auf *SUCHEN*. Du kannst pro Filter mehrere Werte eingeben oder aus den Dropdown-Listen mehrere Filter wählen (material:check_box[role=skyBlue]). Du kannst auch mehrere Filter miteinander kombinieren, um die Suchergebnisse zu verfeinern. <<#table-filters-ar-list>> erläutert die Filtereinstellungen.

[[table-filters-ar-list]]
.Filtereinstellungen Offene Posten
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Kontakt-ID*
|Suche mit diesem Filter nach einem bestimmten Kontakt mit offenen Forderungen. Die Eingabe mehrerer Kontakt-IDs ist möglich, um nach mehreren Kontakten gleichzeitig zu suchen.

| [#intable-ar-list-filter-contact-type]*Kundentyp*
|Suche mit diesem Filter nach offenen Forderungen von bestimmten xref:crm:vorbereitende-einstellungen.adoc#typ-erstellen[Kundentypen]. Wähle (material:check_box[role=skyBlue]) dafür aus der Dropdown-Liste einen oder mehrere Typen. Beim Öffnen der OP-Liste wird dir immer eine bereits gefilterte Ansicht gezeigt. Gefiltert wird automatisch nach den Kundentypen *Kunde* und *Gast*. +
Beachte auch die xref:crm:op-liste.adoc#intable-ar-list-default-filter-contact-type[Standardeinstellung] für diesen Filter.

| *Kundenklasse*
|Suche mit diesem Filter nach offenen Forderungen von bestimmten xref:crm:vorbereitende-einstellungen.adoc#kundenklasse-erstellen[Kundenklassen]. Wähle (material:check_box[role=skyBlue]) dafür aus der Dropdown-Liste eine oder mehrere Kundenklassen. Beachte auch die xref:crm:op-liste.adoc#intable-ar-list-default-filter-customer-class[Standardeinstellung] für diesen Filter.

|*Land*
|Suche mit diesem Filter nach offenen Forderungen gruppiert nach Land. Gefiltert wird nach dem Land der Rechnungsadresse. Wähle (material:check_box[role=skyBlue]) dafür aus der Dropdown-Liste ein oder mehrere Länder.

| *Mandant*
|Suche mit diesem Filter nach offenen Forderungen gruppiert nach Mandant. Wähle (material:check_box[role=skyBlue]) dafür aus der Dropdown-Liste einen oder mehrere Mandanten.

| *E-Mail*
|Suche mit diesem Filter nach einem Kontakt mit offenen Forderungen, dem diese E-Mail-Adresse zugeordnet ist.

| *Posten*
|Mit diesem Filter legst du in Kombination mit den Filtern *von* und *bis* einen Bereich fest, in dem entweder *Offene Posten* (Anzahl von unbezahlten und teilbezahlten Aufträgen) oder *Offene Forderungen* (Höhe der offenen Posten), gesucht werden. Wähle dafür den entsprechenden Wert aus der Dropdown-Liste. Lege anschließend den Bereich fest.

| *Von* und *Bis*
|Mit diesen Filtern legst du in Kombination mit der Auswahl des Filters *Posten* einen Bereich für Anzahl oder Höhe der offenen Posten fest. Wähle für diese Filter den Bereich, in dem gesucht werden soll.

| *ZURÜCKSETZEN*
|Setzt die gewählten Filterkriterien zurück.

| *SUCHEN*
|Führt die Suche aus. Die gefundenen Ergebnisse werden in der Übersicht angezeigt.

|====
