= Praxisbeispiel: Messenger-Automatisierungen einrichten
:keywords: Messenger Automatisierung, Ereignisse automatisieren, Beispiel Messenger Automatisierung, Eingangsbestätigung bei neuer E-Mail vom Kunden, Eingangsbestätigung bei neuer Konversation vom Kontakt
:description: Dieses Praxisbeispiel enthält gängige Beispiele, wie du Ereignisse im Messenger automatisierst.
:author: team-crm

Auf dieser Seite findest du gängige Beispiele zum Einrichten von Automatisierungen im Messenger. Diese Seite wird ständig aktualisiert und mit neuen Beispielen befüllt.

[#eingangsbestaetigung-neue-konversation]
== Eingangsbestätigung bei neuer E-Mail von Kund:innen einrichten

Im Folgenden findest du ein Beispiel mit einer Schritt-für-Schritt-Anleitung, wie du einstellst, dass deine Kund:innen automatisch eine Eingangsbestätigung per E-Mail erhalten, wenn sie dir eine E-Mail mit einer Anfrage schreiben.

[.instruction]
Eingangsbestätigung bei neuer E-Mail von Kund:innen einrichten:

. Öffne das Menü *Einrichtung » CRM » Messenger » Automatisierung*. +
icon:map-signs[] *_Oder:_* Wenn du dich bereits im Messenger befindest, klappe auf der linken Seite unterhalb des Papierkorbs den Bereich material:settings[] *Einstellungen* auf und klicke auf material:auto_mode[] *Automatisierung*, um in das Menü *Einrichtung » CRM » Messenger » Automatisierung* weitergeleitet zu werden.
. Klicke auf material:add[] *Automatisierung hinzufügen*.
. Gib der Automatisierung einen Namen, z.B. `Neue Konversation / Eingangsbestätigung`.
. Wähle als *Typ* die Einstellung *Ereignisbasiert*.
. Klicke im Bereich *Auslöser* auf *Auslöser hinzufügen* (material:add[]).
. Wähle den Auslöser *Neue Konversation vom Kontakt*.
. Klicke im Bereich *Filter* auf *Filter hinzufügen* (material:add[]).
. Wähle den Filter *Posteingang der Konversation*.
. Wähle aus der Dropdown-Liste den passenden Posteingang, z.B. `Kundenservice`.
. Wähle dann den Filter *Gruppe, Typ und Status der Konversation*.
. Wähle aus der Dropdown-Liste *Gruppe* die passende Gruppe, z.B. `Allgemein`.
. Wähle aus der Dropdown-Liste *Typ* einen Typen, z.B. `Anfrage`.
. Wähle aus der Dropdown-Liste *Status* den passenden Status, z.B. `Neu`.
. Klicke im Bereich *Aktion* auf *Aktion hinzufügen* (material:add[]).
. Wähle die Aktion *E-Mail senden*.
. Wähle aus der Dropdown-Liste die Vorlage. +
→ Die Vorlage musst du vorher im xref:crm:emailbuilder.adoc#[EmailBuilder] erstellt haben. +
→ In unserem Beispiel heißt die Vorlage _Messenger: Eingangsbestätigung - Neue Konversation_.
. Gib im Feld *E-Mail-Adressen der Empfänger:innen* weitere E-Mail-Adressen ein, wenn du weitere Empfänger:innen zu der Konversation hinzufügen möchtest. +
Bereits vorhandene Empfänger:innen, das heißt die Absender:innen der ursprünglichen E-Mail, erhalten die E-Mail automatisch. +
Wenn Nutzer:innen die Konversation abonniert haben, erhalten diese eine Benachrichtigung im Backend und keine E-Mail, wenn du weiter unten im Feld *E-Mail an alle Abonnent:innen der Konversation* die Einstellung *Ja* gewählt hast.
. Im Feld *Benutzer:innen* kannst du weitere Abonnent:innen wählen (material:check_box[role=skyBlue]) und diese zur Konversation hinzufügen.
. Klicke auf material:save[] (*Speichern*).
