= EmailBuilder: Todo nach der Migration der alten E-Mail-Vorlagen
:keywords: Migration Mail-Vorlagen, Migration alte E-Mail-Vorlagen, Migration Vorlage EmailBuilder
:description: Dieses Praxisbeispiel beschreibt, welche Einstellungen du nach der Migration der alten E-Mail-Vorlagen im EmailBuilder vornehmen musst.
:author: team-crm

// link:https://forum.plentymarkets.com/t/neue-funktionen-des-emailbuilders-inkl-migration-bestehender-vorlagen-new-features-of-emailbuilder-incl-migration-of-existing-templates/693489[Forumsbeitrag^] 

Mit dem Release der neuen Version des EmailBuilder am 07.09.2022 wurden auch alle "alten" E-Mail-Vorlagen, die du in der Vergangenheit im Menü *Einrichtung » Mandant » [Mandant wählen] » E-Mail » Vorlagen* erstellt hast, in diesem Zuge automatisch in den EmailBuilder migriert.

Auch die Struktur und die Variablen wurden aus den alten Vorlagen übernommen.

Wichtig ist, dass du sowohl den Inhalt als auch die Verknüpfungen zu Automatismen (Ereignisaktionen, Prozesse, automatischer Versand…) überprüfst.

Deine bestehenden Vorlagen stehen dir dann im Menü *CRM » EmailBuilder (Testphase)* in den jeweiligen Ordnern zur Verfügung.

_Beispiel_: Alle Vorlagen, die der Eigner Max Mustermann erstellt hat, sind nach der Migration im Ordner Max Mustermann verfügbar. Alle anderen Vorlagen, die keinem bestimmten Benutzer gehören (Allgemeine E-Mail-Vorlagen) sind im EmailBuilder dann im Ordner „Allgemein“ verfügbar.

// TODO: prüfen, wie der Ordner heißt und Screenshot einfügen

Wenn du in den alten Vorlagen für den Typ HTML oder Reiner Text xref:crm:e-mails-versenden.adoc#4100[Template-Funktionen] verwendet hast, ist es notwendig, im EmailBuilder dann die neuen xref:crm:emailbuilder.adoc#verfuegbare-variablen[EmailBuilder-Variablen] zu ergänzen.

