= Praxisbeispiel: Tracking-URL an Kund:innen senden
:keywords:
:description: Dieses Praxisbeispiel beschreibt, wie du die Tracking-URL automatisch an deine Kund:innen sendest, wenn der Warenausgang gebucht wurde.
:author: team-crm

Ich möchte eine Tracking-URL an meine Kund:innen senden, sobald der Warenausgang gebucht wurde. Wie geht das?

[discrete]
== Erforderliche Schritte (Kurzform)

* Tracking-URL speichern
* E-Mail-Vorlage einrichten
* Variable `Tracking-URL` in Vorlage einfügen
* Ereignisaktion verknüpfen, die die Vorlage versendet, wenn der Warenausgang gebucht wurde
** Der Tracking-Link funktioniert natürlich erst, wenn das Paket beim Dienstleister registriert ist und eine Paketnummer am Auftrag erstellt wurde.

// prüfen, ob der letzte Punkt stimmt.
// TODO: Info: Paketnummer und PLZ ist Teil der Tracking-URL → hier nochmal Ievgenii fragen.

[#tracking-url-speichern]
== Tracking-URL am Versanddienstleister speichern

Viele Versanddienstleister bieten eine Sendungsverfolgung mittels Tracking-URL an. Eine funktionsfähige Tracking-URL enthält die Paketnummer und oftmals die Postleitzahl der Person, die das Paket empfangen soll.
Du kannst deinen Kund:innen die Tracking-URL in einer E-Mail zur Versandmitteilung senden, damit diese den aktuellen Status ihrer Sendungen beim Versanddienstleister sowie den voraussichtlichen Zeitpunkt der Zustellung einsehen können.

Du musst also zunächst die Tracking-URL am Versanddienstleister speichern. Gehe dazu ins Menü *Einrichtung » Aufträge » Versand » Optionen* in das Tab *Versanddienstleister*. Gib dort im Feld *Tracking-URL* die Tracking-URL ein und speichere die Einstellung.

Wenn du die Tracking-URL des Versanddienstleisters nicht kennst, gehe folgendermaßen vor:

* Wirf einen Blick in unser Handbuch. Wir haben dort die aktuell gültigen, uns bekannten Tracking-URLs in den jeweiligen Unterkapiteln zum Versanddienstleister aufgelistet. Über das Kapitel xref:fulfillment:versand-vorbereiten.adoc#2500[Versanddienstleister im Überblick] gelangst du auf die Unterkapitel der Versanddienstleister und kannst nachschauen, ob dort die Tracking-URL hinterlegt ist.

* Wenn du dort die gewünschte Information nicht findest, wende dich bitte an deine Ansprechpartner:in bei dem jeweiligen Versanddienstleister und erfrage die korrekte, aktuell gültige Tracking-URL.

// TODO: Info aus der Box unterhalb der Tabelle (https://knowledge.plentymarkets.com/de-de/manual/main/fulfillment/versand-vorbereiten.html#800) auch im Praxisbeispiel ergänzen:



[#vorlage-mit-variable-erstellen]
== E-Mail-Vorlage mit Variable der Tracking-URL erstellen

//// 
hier auch die notwendigen Schritte erklären inklusive Header und Footer und welches Widget man verwenden sollte.
Ereignisaktion (am besten mit Screenshots)
Endergebnis (Screenshot der E-Mail mit unkenntlich gemachter Tracking-URL)
Das fertige Praxisbeispiel auch auf der EmailBuilder-Seite verlinken
////

Erstelle nun eine E-Mail-Vorlage, die die Variable für die Tracking-URL enthält. Du kannst auch eine der xref:crm:emailbuilder.adoc#standardvorlagen-verwenden[vorhandenen Standardvorlagen verwenden] und diese dann anschließend xref:crm:emailbuilder.adoc#vorlage-bearbeiten[anpassen]. +
*_Beachte:_* Wir erläutern im Folgenden, wie du eine neue Vorlage erstellst und nicht, wie du eine vorhandene Vorlage bearbeitest.

[.instruction]
E-Mail-Vorlage mit dem EmailBuilder erstellen:

. Öffne das Menü *CRM » EmailBuilder (Testphase)*.
. Klicke in der Zeile des Ordners, in dem du eine Vorlage erstellen möchtest, auf material:more_vert[]. +
→ Ein Fenster wird geöffnet.
. Klicke auf material:add[] *Neue Vorlage*.
. Gib einen Namen für die Vorlage ein, z.B. Versandbestätigung.
. Gib einen Betreff für die Vorlage ein.
. *Speichere* die Einstellungen.




[.collapseBox]
.E-Mail-Vorlage über den Mandanten erstellen ("alte" Vorgehensweise)
--
// TODO: Konfig ergänzen.
--


[#weiterfuehrende-links]
== Weiterführende Handbuch-Links

* xref:fulfillment:versand-vorbereiten.adoc#800[Versanddienstleister erstellen]
* xref:crm:emailbuilder.adoc#[EmailBuilder]
* xref:crm:e-mails-versenden.adoc[E-Mails versenden] (alte Vorgehensweise)