= Praxisbeispiel: Individuellen Preis im plentyShop für bestimmte Kundenklasse einrichten
:keywords: 
:description: Dieses Praxisbeispiel beschreibt, wie du für eine bestimmte Kundenklasse einen individuellen Preis in deinem plentyShop einrichtest.
:author: team-crm

Ich möchte, dass ein bestimmter Kunde in meinem plentyShop – im Gegensatz zu anderen Kunden – einen individuellen Preis für einen bestimmten Artikel sehen kann. Was muss ich tun?

[discrete]
== Erforderliche Schritte (Kurzform)

* <<#kundenklasse-erstellen, Kundenklasse erstellen>>
* <<#verkaufspreis-erstellen, Verkaufspreis erstellen>>
** *_Wichtig:_* Kundenklasse und Herkunft *Webshop* müssen aktiviert werden.
* <<#verkaufspreis-artikel, Verkaufspreis in Artikel hinzufügen>>


[#kundenklasse-erstellen]
== Kundenklasse erstellen

Erstelle zunächst eine neue Kundenklasse. Gehe dazu wie im Folgenden beschrieben vor.

[.instruction]
Kundenklasse erstellen:

. Öffne das Menü *Einrichtung » CRM » Kundenklassen*.
. Wechsele in das Tab *Neue Kundenklasse*.
. Gib im Feld *Bezeichnung* den Namen der Kundenklasse ein, z.B. `Stammkunden`.
//. TODO: Mengenrabatt ergänzen und auf Kapitel Verkaufspreis weiter unten verlinken. Andersherum genauso von Verkaufpreis auf dieses Kapitel verlinken.
. Wähle (material:radio_button_checked[role=skyBlue]), ob die Preise im Webshop in *brutto* oder *netto* angezeigt werden sollen.
. *Speichere* (material:save[]) die Einstellungen

[TIP]
Die oben beschriebenen Schritte listen die Einstellungen auf, die _mindestens_ für das Erstellen einer Kundenklasse für die Zwecke dieses Praxisbeispiels vorgenommen werden müssen. Natürlich kannst du noch weitere Einstellungen in der Kundenklasse vornehmen. Alle weiteren Einstellungen sind auf der Handbuchseite xref:crm:vorbereitende-einstellungen.adoc#[Vorbereitende Einstellungen vornehmen] im Kapitel xref:crm:vorbereitende-einstellungen.adoc#kundenklasse-erstellen[Kundenklasse erstellen] detailliert beschrieben.


[#verkaufspreis-erstellen]
== Verkaufspreis erstellen

Erstelle nun einen Verkaufspreis. Verkaufspreise definieren die Bedingungen, unter denen eine Variante zu einem bestimmten Preis verkauft wird. Zum Beispiel kannst du deine Produkte im plentyShop günstiger anbieten als auf einem Marktplatz. Oder du kannst deine Produkte günstiger an B2B-Kunden verkaufen als an B2C-Kunden. +
In dem Verkaufspreis musst du dann die <<#kundenklasse-erstellen, gerade erstellte Kundenklasse>> sowie die Herkunft *Webshop* aktivieren.

// TODO: BOX --> Wichtig: Kundenklasse und Herkunft “Webshop” aktivieren.

[.instruction]
Verkaufspreis erstellen:

. Öffne das Menü *Einrichtung » Artikel » Verkaufspreise*.
. Klicke auf icon:add[role=green] *Neu*.
. Gib im Feld *Position* eine Zahl ein. +
→ Wenn du später mehrere Verkaufspreise mit einer Variante verknüpfst, dann werden die Verkaufspreise anhand ihrer Positionsnummer im Artikeldatensatz sortiert angezeigt.
. Gib im Feld *Interner Name* einen Namen für den Verkaufspreis ein, z.B. `Stammkundenpreis`.
. Im Feld *Externer Name* kannst du denselben oder einen anderen Namen für den Verkaufspreis eingeben.
. Gib im Feld *Ab Menge* eine Zahl ein, z.B. `3`. +
→ *_Beispiel:_* Wenn ein Kunde mehrere Exemplare deines Artikel kauft (z.B. 3), kannst du bestimmen, dass der Preis ab Kauf von 3 Exemplaren reduziert wird. +
*_Wichtig:_* Mengenrabatte müssen auch in der Kundenklasse erlaubt sein. Stelle sicher, dass die Einstellung *Mengenrabatt* auf *berücksichtigen* gesetzt ist. 



[TIP]
Die oben beschriebenen Schritte listen die Einstellungen auf, die _mindestens_ für das Erstellen eines Verkaufspreises für die Zwecke dieses Praxisbeispiels vorgenommen werden müssen. Natürlich kannst du noch weitere Einstellungen im Verkaufspreis vornehmen. Alle weiteren Einstellungen sind auf der Handbuchseite xref:artikel:preise.adoc#[Verkaufspreise und Preiskalkulation] im Kapitel xref:artikel:preise.adoc#100[Verkaufspreise] detailliert beschrieben.

[TIP]
.Verkaufspreis einfach und schnell mit einem Assistenten erstellen
====
Du hast die Möglichkeit, deinen Verkaufspreis mit dem xref:artikel:preise.adoc#_mit_dem_assistenten[Assistenten *Verkaufspreise*] zu erstellen.
====

[#verkaufspreis-artikel]
== Verkaufspreis in Artikel hinzufügen

//// 
TODO: 

Es gibt Automatismen, mit denen bestimmte Kunden nun in diese Kundenklasse “rutschen”
EA
manuell geht auch

Wenn der Kunde nun in deinem Webshop bestellt, sieht er automatisch den von dir definierten Preis (für die Kundenklasse, der er angehört).
////
