= Praxisbeispiel: Individuellen Preis im plentyShop für bestimmte Kundenklasse einrichten
:keywords: 
:description: Dieses Praxisbeispiel beschreibt, wie du für eine bestimmte Kundenklasse einen individuellen Preis in deinem plentyShop einrichtest.
:author: team-crm

Ich möchte, dass ein bestimmter Kunde in meinem plentyShop – im Gegensatz zu anderen Kunden – einen individuellen Preis für einen bestimmten Artikel sehen kann. Was muss ich tun?

[discrete]
== Erforderliche Schritte (Kurzform)

* <<#kundenklasse-erstellen, Kundenklasse erstellen>>
* <<#verkaufspreis-erstellen, Verkaufspreis erstellen>>
** *_Wichtig:_* Kundenklasse und Herkunft *Mandant (Shop)* müssen aktiviert werden.
* <<#verkaufspreis-artikel, Verkaufspreis im Artikel hinzufügen>>

* Tipp: <<#ereignisaktion-einrichten, Ereignisaktion einrichten>>

[#kundenklasse-erstellen]
== Kundenklasse erstellen

Erstelle zunächst eine neue Kundenklasse, die du dann später <<#verkaufspreis-erstellen, im Verkaufspreis aktivierst>>.

[.instruction]
Kundenklasse erstellen:

. Öffne das Menü *Einrichtung » CRM » Kundenklassen*.
. Wechsele in das Tab *Neue Kundenklasse*.
. Gib im Feld *Bezeichnung* den Namen der Kundenklasse ein, z.B. `Stammkunden`.
. Stelle die Einstellung *Mengenrabatt* auf *berücksichtigen*, wenn du später im <<#verkaufspreis-erstellen, Verkaufspreis>> einen Mengenrabatt einstellen möchtest.
. Wähle (material:radio_button_checked[role=skyBlue]), ob die Preise im Webshop in *brutto* oder *netto* angezeigt werden sollen.
. *Speichere* (material:save[]) die Einstellungen.

[TIP]
Die oben beschriebenen Schritte listen die Einstellungen auf, die _mindestens_ für das Erstellen einer Kundenklasse für die Zwecke dieses Praxisbeispiels vorgenommen werden müssen. Natürlich kannst du noch weitere Einstellungen in der Kundenklasse vornehmen. Alle weiteren Einstellungen sind auf der Handbuchseite xref:crm:vorbereitende-einstellungen.adoc#[Vorbereitende Einstellungen vornehmen] im Kapitel xref:crm:vorbereitende-einstellungen.adoc#kundenklasse-erstellen[Kundenklasse erstellen] detailliert beschrieben.

In plentysystems kannst du Automatismen einrichten, wodurch bestimmte Kund:innen einer bestimmten Kundenklasse zugeordnet werden. +
Ein gängiges Beispiel für eine Ereignisaktion findest du weitere unten im Kapitel <<#ereignisaktion-einrichten, Ereignisaktion einrichten>>. 

Natürlich kannst du die Kundenklasse auch xref:crm:kontakt-bearbeiten.adoc#kontaktdetails[manuell im Kontaktdatensatz] anpassen.

[#verkaufspreis-erstellen]
== Verkaufspreis erstellen

Erstelle nun einen Verkaufspreis. Verkaufspreise definieren die Bedingungen, unter denen eine Variante zu einem bestimmten Preis verkauft wird. Zum Beispiel kannst du deine Produkte im plentyShop günstiger anbieten als auf einem Marktplatz. Oder du kannst deine Produkte günstiger an B2B-Kund:innen verkaufen als an B2C-Kund:innen. +
In dem Verkaufspreis musst du dann die <<#kundenklasse-erstellen, gerade erstellte Kundenklasse>> sowie die Herkunft *Mandant (Shop)* aktivieren.

[.instruction]
Verkaufspreis erstellen:

. Öffne das Menü *Einrichtung » Artikel » Verkaufspreise*.
. Klicke auf icon:add[role=green] *Neu*.
. Gib im Feld *Position* eine Zahl ein. +
→ *_Hinweis:_* Wenn du später mehrere Verkaufspreise mit einer Variante verknüpfst, dann werden die Verkaufspreise anhand ihrer Positionsnummer im Artikeldatensatz sortiert angezeigt.
. Gib im Feld *Interner Name* einen Namen für den Verkaufspreis ein, z.B. `Stammkundenpreis`. +
→ Das Feld *Externer Name* ist wie der interne Name ein Pflichtfeld. Hier kannst du denselben wie für den internen Namen oder einen ganz anderen Namen für den Verkaufspreis eingeben.
. Gib im Feld *Ab Menge* eine Zahl ein, z.B. `3`. +
→ *_Beispiel:_* Wenn ein Kunde mehrere Exemplare deines Artikel kauft (z.B. 3), kannst du bestimmen, dass der Preis ab Kauf von 3 Exemplaren reduziert wird. +
*_Wichtig:_* Mengenrabatte müssen auch in der <<#kundenklasse-erstellen, Kundenklasse erlaubt>> sein. Stelle sicher, dass in der Kundenklasse die Einstellung *Mengenrabatt* auf *berücksichtigen* gesetzt ist. 
. Wähle (material:check_box[role=skyBlue]) die Währung aus der Liste, z.B. `EUR`.
. Wähle (material:check_box[role=skyBlue]) den passenden Mandanten aus der Liste.
. Wähle (material:check_box[role=skyBlue]) die soeben erstellte Kundenklasse `Stammkunden` aus der Liste.
. Wähle (material:check_box[role=skyBlue]) das Land aus der Liste.
. Wähle (material:check_box[role=skyBlue]) die Herkunft aus der Liste, in unserem Fall `Mandant (Shop)`.

[TIP]
Die oben beschriebenen Schritte listen die Einstellungen auf, die _mindestens_ für das Erstellen eines Verkaufspreises für die Zwecke dieses Praxisbeispiels vorgenommen werden müssen. Natürlich kannst du noch weitere Einstellungen im Verkaufspreis vornehmen. Alle weiteren Einstellungen sind auf der Handbuchseite xref:artikel:preise.adoc#[Verkaufspreise und Preiskalkulation] im Kapitel xref:artikel:preise.adoc#100[Verkaufspreise] detailliert beschrieben.

[TIP]
.Verkaufspreis einfach und schnell mit einem Assistenten erstellen
====
Du hast die Möglichkeit, deinen Verkaufspreis mit dem xref:artikel:preise.adoc#_mit_dem_assistenten[Assistenten *Verkaufspreise*] zu erstellen.
====

[#verkaufspreis-artikel]
== Verkaufspreis im Artikel hinzufügen

Im Menü *Artikel » Artikel* musst du nun im gewünschten Artikel den soeben erstellten Verkaufspreis hinzufügen und dort auch den eigentlichen Geldbetrag des Verkaufspreises speichern.

[.instruction]
Verkaufspreis im Artikel hinzufügen:

. Öffne das Menü *Artikel » Artikel*. 
. Suche den Artikel, in dem du den Verkaufspreis aktivieren möchtest. +
→ Der Bereich der Hauptvariante ist automatisch geöffnet.
. Navigiere in den Bereich *Verkaufspreise*.
. Klicke im Bereich *Verkaufspreise* auf *Verkaufspreise hinzufügen* (material:add[]). +
→ Das Fenster *Verkaufspreise hinzufügen* öffnet sich.
. Wähle (material:check_box[role=skyBlue]) den soeben erstellten Verkaufspreis aus der Dropdown-Liste.
. Klicke auf *Übernehmen*. +
→ Der Verkaufspreis wird hinzugefügt.
. Gib in der Spalte *Preis (Brutto)* den von dir gewünschten Geldbetrag ein.
. *Speichere* (material:save[]) die Einstellungen.

Wenn du alle auf dieser Seite beschriebenen Einstellungen vorgenommen hast, sehen Kund:innen mit der zugeordneten Kundenklasse automatisch den von dir definierten Preis für einen bestimmten Artikel in deinem plentyShop.

[#ereignisaktion-einrichten]
== Tipp: Ereignisaktion einrichten

Richte eine Ereignisaktion ein, die den Wechsel der Kundenklasse auslöst, wenn ein Kunde eine von dir definierte Anzahl an Aufträgen in deinem plentyShop platziert hat. 

[.instruction]
Ereignisaktion einrichten:

. Öffne das Menü *Einrichtung » Aufträge » Ereignisse*.
. Klicke unten links auf *Ereignisaktion hinzufügen* (material:add[role=green]). +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
. Gib einen eindeutigen Namen für die Ereignisaktion ein, z.B. `Kundenklasse ändern nach x Aufträgen`.
. Wähle das Ereignis gemäß <<#table-event-procedure-customer-class-number-of-orders>>.
. *Speichere* (icon:save[role=green]) die Einstellungen.
. Nimm die Einstellungen gemäß <<#table-event-procedure-customer-class-number-of-orders>> vor.
. Aktiviere die Option *Aktiv*.
. *Speichere* (icon:save[role=green]) die Einstellungen.

[[table-event-procedure-customer-class-number-of-orders]]
.Ereignisaktion "Paketnummer generiert" einrichten
[cols="2,4,3"]
|====
|Einstellung |Option |Auswahl

|Ereignis
|Auftragsanlage > Neuer Auftrag
|

|Filter 1
|Auftrag > Herkunft
|Mandant (Shop)

|Filter 2
|Kunde > Anzahl der Aufträge
|Wähle einen Operator aus der Liste und gib eine Zahl in das Feld ein.

|Aktion
|Kunde > Kundenklasse ändern
|Wähle die von dir erstellte <<#kundenklasse-erstellen, Kundenklasse>> aus der Dropdown-Liste.

|====