= Praxisbeispiel: Messenger-Automatisierung
:keywords: Messenger Automatisierung, Ereignisse automatisieren
:description: Dieses Praxisbeispiel enthält gängige Beispiele, wie du Ereignisse im Messenger automatisierst.
:author: team-crm

// TODO: in nav. adoc einbinden


[#eingangsbestaetigung-neue-konversation]
== Eingangsbestätigung bei neuer Konversation vom Kunden

Im Folgenden findest du ein Beispiel mit einer Schritt-für-Schritt-Anleitung, wie du einstellst, dass deine Kund:innen eine Eingangsbestätigung per E-Mail erhalten, wenn sie dir eine E-Mail mit einer Anfrage schreiben.

[.instruction]
Eingangsbestätigung bei neuer Konversation vom Kunden einrichten:

. Öffne das Menü *Einrichtung » CRM » Messenger » Automatisierung*. +
icon:map-signs[] *_Oder:_* Wenn du dich bereits im Messenger befindest, klappe auf der linken Seite unterhalb des Papierkorbs den Bereich material:settings[] *Einstellungen* auf und klicke auf material:auto_mode[] *Automatisierung*, um in das Menü *Einrichtung » CRM » Messenger » Automatisierung* weitergeleitet zu werden.
. Klicke auf material:add[] *Automatisierung hinzufügen*.
. Gib der Automatisierung einen Namen, z.B. `Neue Konversation / Eingangsbestätigung`.
. Wähle als *Typ* die Einstellung *Ereignisbasiert*.
. Klicke im Bereich *Auslöser* auf *Auslöser hinzufügen* (material:add[]).
. Wähle den Auslöser *Neue Konversation*.
. Klicke im Bereich *Filter* auf *Filter hinzufügen* (material:add[]).
. Wähle den Filter *Posteingang der Konversation*.
. Wähle aus der Dropdown-Liste den passenden Posteingang, z.B. `Kundenservice`.
. Wähle dann den Filter *Status der Konversation*.
. Wähle aus der Dropdown-Liste *Typ* einen Typen, z.B. `Anfrage`.
. Wähle aus der Dropdown-Liste *Status* den passenden Status, z.B. `Neu.
. Klicke im Bereich *Aktion* auf *Aktion hinzufügen* (material:add[]).
. Wähle die Aktion *E-Mail senden*.
. Wähle aus der Dropdown-Liste die Vorlage. +
→ Die Vorlage musst du vorher im xref:crm:emailbuilder.adoc#[EmailBuilder] erstellt haben. +
→ In unserem Beispiel heißt die Vorlage _Messenger: Eingangsbestätigung - Neue Konversation_.
. Gib im Feld *Zusätzliche Empfänger:innen* weitere E-Mail-Adressen ein, wenn du weitere Empfänger:innen zu der Konversation hinzufügen möchtest. +
Bereits vorhandene Empfänger, das heißt die Absender:innen der ursprünglichen E-Mail, erhalten die E-Mail automatisch. +
Wenn Nutzer:innen die Konversation abonniert haben, erhalten diese eine Benachrichtigung im Backend und keine E-Mail, wenn du weiter unten im Feld *Alle Abonnent:innen der Konversation* die Einstellung *Ja* gewählt hast.
. Im Feld *Benutzer:innen* kannst du weitere Abonnent:innen wählen und diese zur Konversation hinzufügen.
. Speichere (material:save[]) die Einstellungen.