= Schnellsuche
:keywords: Schnellsuche, Adresssuche, Adressen suchen, DSGVO, Gastzugang, Gastbestellung, als Gast bestellen, Gast suchen, Kunde anonymisieren, anonymisieren, Kundendaten löschen, Datensatz löschen, Kunde löschen, Kontakt löschen, alle Daten vom Kunden herunterladen, Kundendaten herunterladen, Kontakt verlangt Löschung, Kontakt Löschantrag, Kunde Löschantrag, Kunde verlangt Löschung
:description: Erfahre, wie du die Schnellsuche in plentymarkets verwendest.
:id: RZPMSR4
:author: team-crm

Verwende die Schnellsuche, um alle Informationen eines Kontakts oder die Adressdaten einer Gastbestellung auf einen Blick zu erhalten. Erfahre auf dieser Handbuchseite, wie du DSGVO-gemäß <<#alle-daten-herunterladen, alle Daten zu einem Kontakt oder einer Gastbestellung herunterlädst>> und wie du <<#datensatz-anonymisieren, Datensätze anonymisierst>>.

[NOTE]
.Gastzugänge über plentyShop können nur in der Schnellsuche gefunden werden
====
Um DSGVO-konform zu arbeiten, wird bei Gastbestellungen über den plentyShop kein Kontaktdatensatz erstellt. Es werden lediglich die Adressdaten gespeichert. Diese Daten, die in deinem plentymarkets System gespeichert werden, können daher nicht über das Menü *CRM » Kontakte* gefunden werden. Die Adressdaten der Person, die als Gast bestellt hat, können nur über die Schnellsuche gefunden werden. +

Weitere Informationen zum Umwandeln von plentyShop-Gastbestellungen in reguläre Kontaktdatensätze findest du im Kapitel <<#gastzugang-umwandeln, Gastzugang in Kontaktdatensatz umwandeln>>.
====

[#benutzerrechte]
== Rechte für Backend-Benutzer:innen

:rights-purpose: mit der Schnellsuche arbeiten können
:right-one: pass:quotes[*CRM > Kontakt > Anzeigen*]

include::_includes:page$rechte.adoc[]

Weitere Informationen zu den Rechten für das Menü *CRM » Kontakte* für Backend-Benutzer:innen findest du auf der Handbuchseite xref:crm:kontakte-verwalten.adoc#50[Kontakte].

[#datensaetze-finden]
== Datensätze über die Schnellsuche finden

Gehe wie im Folgenden beschrieben vor, um Datensätze über die Schnellsuche zu finden.

[.instruction]
Datensätze über die Schnellsuche finden:

. Öffne das Menü *CRM » Schnellsuche*.
. Wähle mindestens einen Filter. Beachte dazu die Erläuterungen in <<#table-filter-quick-search>>.
. Klicke auf *Suchen* (icon:search[role="blue"]). +
→ Die Datensätze, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicke in die Zeile des Datensatzes. +
→ Die Übersicht mit den Bereichen *Rechnungsadresse*, *Stammdaten* und *Info* wird geöffnet.
. Klicke in die Zeile *Aufträge*, um die Aufträge anzuzeigen. +
→ Mit einem Klick in die Zeile des Auftrags gelangst du direkt in die Übersicht des Auftrags im Menü *Aufträge » Aufträge bearbeiten*.
. Klicke in die Zeile *Adressen*, um weitere Adressen anzuzeigen. +
→ Mit einem Klick in die Zeile der Adresse gelangst du direkt in die Adressübersicht und kannst dort Änderungen vornehmen.
. Klicke in die Zeile *Messenger*, um die Nachrichten anzuzeigen. +
→ Klicke auf *Neue Nachricht* (icon:plus-square[role="green"]). Die Stoppuhr oben rechts startet automatisch, sobald die Nachricht geöffnet wird. Klicke auf *Kostenpflichtig* icon:pay_cash[set=plenty] icon:toggle-off[role="red"], um die Zeit abzurechnen. +
*_Hinweis:_* Weitere Informationen findest du auf der Handbuchseite xref:crm:messenger.adoc#[Messenger].
. Klicke in die Zeile *Events*, um neue Events hinzuzufügen oder bestehende Events zu bearbeiten. +
→ Klicke auf *Event hinzufügen* (icon:plus-square[role="green"]), um diese Zeit zu speichern. +
→ *_Hinweis:_* Events sind nur für Kontaktdatensätze verfügbar, _nicht_ für Gastbestellungen.
. Klicke in die Zeile *Tickets*, um die Tickets anzuzeigen. +
→ Mit einem Klick in die Zeile des Tickets gelangst du direkt in das Ticket im Menü *CRM » Ticketsystem*.

// Screenshot einfügen

[[table-filter-quick-search]]
.Filter in der Schnellsuche
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Suchen*
|Mit einem Klick auf icon:search[role="blue"] werden die gefundenen Datensätze, die den Suchkriterien entsprechen, angezeigt. +
*_Hinweis:_* Mindestens ein Filter muss gewählt sein.

| *Zurücksetzen*
|Mit einem Klick auf icon:undo[role="orange"] werden die eingestellten Filterkriterien zurückgesetzt.

| *ID*
|Jeder Kontakt erhält automatisch eine fortlaufende und einzigartige ID. Dies ist unabhängig davon, ob der Kontakt manuell oder automatisch erstellt wurde. 2 Kontakte haben somit nie die selbe ID. Die ID entspricht immer einer echten Zahl. Ungültig sind daher z.B. 00521 oder ABC8354. +
*_Hinweis:_* Mit einem Klick auf die Pfeile (icon:sort[]) neben der ID in der Übersicht kannst du die gefundenen Datensätze aufsteigend oder absteigend nach ihrer ID anzeigen.

| *Name*
|Gib den Vornamen und/oder Nachnamen oder den Firmennamen ein, um den oder die Kontakte mit diesem Namen anzuzeigen. +
*_Hinweis:_* Mit einem Klick auf die Pfeile (icon:sort[]) in den Spalten *Vorname* und *Nachname* in der Übersicht kannst du die gefundenen Datensätze alphabetisch sortiert anzeigen.

| *Kontaktdaten*
|In diesem Feld kanst du nach dem Namen, der Adresse, der Firma, der Kundennummer und dem eBay-Namen suchen. +
*_Hinweis:_* Um nach dem eBay-Namen zu suchen, gib zuerst den Parameter `ebay:` gefolgt vom gesuchten eBay-Namen ein.

| *Anschrift*
|Gib den Straßennamen und/oder die Hausnummer ein. Es ist möglich, nur nach Teilen des Straßennamens und Teilen der Hausnummer zu suchen.

| *PLZ*
|Gib die Postleitzahl ein. +
*_Hinweis:_* Es wird auch nach Postleitzahlen, die in den Adressdatensätzen des Kontakts gespeichert sind, gesucht. Es ist möglich, nur nach Teilen der Postleitzahl zu suchen. Du musst mindestens 3 Ziffern eingeben.

| *Ort*
|Ort, der im Kontakt gespeichert ist, eingeben. Es wird auch nach Orten, die in den Adressdatensätzen des Kontakts gespeichert sind, gesucht. Es ist möglich, nur nach Teilen des Ortsnamens zu suchen.

| *E-Mail*
|Gib die komplette E-Mail-Adresse ein, um den Kontakt mit dieser E-Mail-Adresse anzuzeigen.

| *Telefon*
|Gib die Telefonnummer ein, um nur den Kontakt mit dieser Telefonnummer anzuzeigen. Es kann auch nach Teilen der Telefonnummer gesucht werden. Du musst mindestens 3 Ziffern eingeben.

| *Tags*
|Wähle ein Tag, um nur Kontakte mit diesem Tag anzuzeigen.

| *Land*
|Wähle das Land, um nur Kontakte aus diesem Land anzuzeigen. Das Land ist in den Kontaktdaten gespeichert. +
Wähle die Einstellung *Alle außer Deutschland*, um nur Kontakte aus allen Ländern außer Deutschland anzuzeigen.

| *Eigner*
|Wähle den Eigner, um nur Kontakte anzuzeigen, die mit diesem Eigner verknüpft sind. Der Eigner muss in den Kontaktdaten gespeichert sein. +
*_Wichtig:_* In der Dropdown-Liste werden nur Benutzer:innen angezeigt, bei denen im Konto im Tab *Eigner* die Option *Kunde* aktiviert ist.

| *Typ*
|Wähle den Typ, um nur Kontakte mit diesem Typ anzuzeigen.

| *Kundenklasse*
|Wähle die Kundenklasse, um nur Kontakte mit dieser Kundenklasse anzuzeigen.

| *Bewertung*
|Wähle die Bewertung, um nur Kontakte mit dieser Bewertung anzuzeigen. 5 gelbe Sterne stehen für die beste und 5 rote Sterne für die schlechteste Bewertung.

| *Mandant*
|Wähle den Mandanten, um nur Kontakte dieses Mandanten anzuzeigen. Der Mandant ist in den Kontaktdaten gespeichert. +
*_Wichtig:_* Backend-Benutzer:innen stehen nur Mandanten zur Auswahl, für die sie eine Berechtigung haben. Berechtigungen werden im Menü *Einrichtung » Einstellungen » Benutzer » Konten* im Tab xref:business-entscheidungen:benutzerkonten-zugaenge.adoc#90[Berechtigungen] des Benutzer:innenkontos eingestellt.

|====

[TIP]
Sobald du im Menü *CRM » Schnellsuche* einen Datensatz öffnest, startet eine Stoppuhr automatisch oben rechts in der Ecke. Mit einem Klick auf *Pause* (icon:pause-circle-o[]) hältst du die Uhr an. Mit einem weiteren Klick auf *Start* (icon:play-circle[]) läuft die Zeit weiter. Klicke auf *Zurücksetzen* (icon:undo[role="orange"]), um die Zeit auf 0 zu setzen.

[#weitere-einstellungen]
== Weitere Einstellungsmöglichkeiten

Wenn du einen Datensatz in der Schnellsuche öffnest, siehst du in der ersten Zeile des Datensatzes weitere Einstellungsmöglichkeiten, die in <<#table-settings-quick-search>> erläutert werden.

[[table-settings-quick-search]]
.Einstellungen in der Schnellsuche
[cols="2,6"]
|====
|Einstellung |Erläuterung

| *KONTAKT-ID*
|Öffnet den Kontaktdatensatz im Menü *CRM » Kontakte*. +
*_Hinweis:_* Wenn es sich bei dem Datensatz um eine Gastbestellung handelt, ist dieses Feld ausgegraut.

| *AUFTRÄGE*
|Öffnet das Menü *Aufträge » Aufträge bearbeiten*. Als Filter ist die ID des Kontakts automatisch gewählt. +
Mit einem Klick auf icon:add[set=material] *Neuer Auftrag* rechts neben *AUFTRÄGE* wird ein neuer Auftrag im Menü *Aufträge » Aufträge bearbeiten* erstellt. +
*_Hinweis:_* Wenn es sich bei dem Datensatz um eine Gastbestellung handelt, sind diese Felder ausgegraut. +

| *ANGEBOTE*
|Öffnet das Menü *Aufträge » Aufträge bearbeiten*. Als Filter ist die ID des Kontakts automatisch gewählt. +
Mit einem Klick auf icon:add[set=material] *Neues Angebot* rechts neben *ANGEBOTE* wird ein neues Angebot im Menü *Aufträge » Aufträge bearbeiten* erstellt. +
*_Hinweis:_* Wenn es sich bei dem Datensatz um eine Gastbestellung handelt, sind diese Felder ausgegraut.

| *MESSENGER*
|Öffnet weiter unten den Bereich *Messenger*. +
Mit einem Klick auf icon:add[set=material] *Neue Nachricht* rechts neben *MESSENGER* öffnet sich weiter unten das Bearbeitungsfenster zum Erstellen einer neuen Nachricht. +
*_Hinweis:_* Wenn es sich bei dem Datensatz um eine Gastbestellung handelt, sind diese Felder ausgegraut.

| *TICKETS*
|Öffnet das Menü *CRM » Ticketsystem*. Als Filter ist die ID des Kontakts automatisch gewählt. +
Mit einem Klick auf icon:add[set=material] *Neues Ticket* rechts neben *TICKETS* öffnet sich das Bearbeitungsfenster zum Erstellen eines neuen Tickets im Menü *CRM » Ticketsystem*. + 
*_Hinweis:_* Wenn es sich bei dem Datensatz um eine Gastbestellung handelt, sind diese Felder ausgegraut.

| *Alle Daten dieses Kontakts herunterladen*
|Mit einem Klick auf icon:file_download[set=material] werden alle gespeicherten Daten zu diesem Datensatz heruntergeladen. +
Weitere Informationen findest du im Kapitel <<#alle-daten-herunterladen, Alle Daten zu einem Kontakt oder einer Gastbestellung herunterladen>>.

| *Newsletter Opt-In E-Mail senden*
|Mit einem Klick auf icon:outgoing_mail[set=material] wird eine E-Mail zum Newsletter-Opt-In bzw. die Bestätigung zum Newsletter-Opt-In versendet. +
*_Hinweis:_* Wenn die Person noch nicht für den Newsletter angemeldet ist, erhält sie die automatische E-Mail für Newsletter-Opt-In. Wenn die Person bereits für den Newsletter angemeldet ist, aber noch nicht bestätigt hat, erhält sie die Bestätigung zum Newsletter-Opt-In.

| *Datensatz anonymisieren*
|Mit einem Klick auf icon:user-secret[] wird der Datensatz anonymisiert. Das Anonymisieren der Daten ist nur bei einem Kontaktdatensatz möglich, _nicht_ bei einer Gastbestellung. +
Weitere Informationen findest du im Kapitel <<#datensatz-anonymisieren, Datensatz anonymisieren>>.

| *Gast in Kontakt umwandeln*
|Mit einem Klick auf icon:swap_horiz[set=material] werden die Adressdaten aus einer Gastbestellung in einen regulären Kontaktdatensatz umgewandelt. Im neu erstellten Kontaktdatensatz wird dann im Bereich *Historie* der Eintrag *Umgewandelt von* sowie der Name der Person, die den Datensatz umgewandelt hat, hinzugefügt. +
Weitere Informationen findest du im Kapitel <<#gastzugang-umwandeln, Gastzugang in Kontaktdatensatz umwandeln>>. +
*_Hinweis:_* Wenn es sich bereits um einen Kontakt handelt, ist das Feld ausgegraut und über der Schaltfläche erscheint der Hinweis *Dieser Kontakt ist kein Gast.*

| *Daten neu laden*
|Mit einem Klick auf icon:undo[] werden die Daten in diesem Datensatz aktualisiert.

| *Pause* / *Start*
|Mit einem Klick auf icon:pause_circle[set=material] hältst du den Timer an. +
Mit einem Klick auf icon:play_circle[set=material] wird der Timer wieder gestartet.

| *Zurücksetzen*
Mit einem Klick auf icon:reset[set=plenty] setzt du den Timer zurück auf null.

|====

[#gastzugang-umwandeln]
== Gastzugang in Kontaktdatensatz umwandeln

Im Menü *CRM » Schnellsuche* kannst du mit einem Klick die Adressdaten aus einer Gastbestellung in einen regulären Zugang umwandeln.

Bei Gastbestellung über den plentyShop besteht der gespeicherte Datensatz lediglich aus der Adresse und dem zugehörigen Auftrag. Wenn in der Adresse zusätzlich ein Firmenname enthalten ist, wird beim Umwandeln des Datensatzes auch der Firmendatensatz erstellt.

[.instruction]
Gastzugang in Kontaktdatensatz umwandeln:

. Öffne das Menü *CRM » Schnellsuche*.
. Wähle mindestens einen Filter. Beachte dazu die Erläuterungen in <<#table-filter-quick-search>>.
. Klicke auf *Suchen* (icon:search[role="blue"]). +
→ Die Datensätze, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicke in die Zeile des Datensatzes. +
→ Der Datensatz wird geöffnet.
. Klicke in der Kopfzeile auf *Gast in Kontakt umwandeln* (icon:swap_horiz[set=material]). +
→ Ein Fenster mit einer Sicherheitsabfrage wird angezeigt. +
. Wenn du DGSVO-konform gearbeitet hast, klicke auf *Umwandeln*. +
→ Der Datensatz wird in einen Kontaktdatensatz umgewandelt und erhält automatisch die nächste freie Kontakt-ID. Im Bereich *Historie* des Kontaktdatensatzes wird der Eintrag *Umgewandelt von* sowie der Name der Person, die den Datensatz umgewandelt hat, hinzugefügt.

[TIP]
.Callisto-Gastbestellungen vs. plentyShop-Gastbestellungen
====
Auf der Handbuchseite xref:crm:kontakte-verwalten.adoc#[Kontakte] im Kapitel xref:crm:kontakte-verwalten.adoc#350[Gastzugang in regulären Zugang umwandeln] ist beschrieben, wie du Gastbestellungen aus deinem alten Webshop (Callisto) bzw. Gastbestellungen, die über einen Marktplatz in dein System kamen, in reguläre Zugänge umwandelst. Das Umwandeln von plentyShop-Gastbestellungen in reguläre Zugänge ist über den Kontaktdatensatz nicht möglich.

Jedoch kannst du über die Schnellsuche neben plentyShop-Gastbestellungen auch Callisto-Gastbestellungen in reguläre Kontaktdatensätze umwandeln.
====

[#alle-daten-herunterladen]
== Alle Daten zu einem Kontakt oder einer Gastbestellung herunterladen

Im Menü *CRM » Schnellsuche* kannst du mit einem Klick alle zu einem Kontakt gehörigen Daten oder die zu einer Gastbestellung gehörigen Adressdaten als ZIP-Datei herunterladen. Die ZIP-Datei enthält eine HTML-Datei sowie eine maschinenlesbare Datei im JSON-Format.

[.instruction]
Alle Daten zu einem Kontakt oder einer Gastbestellung herunterladen:

. Öffne das Menü *CRM » Schnellsuche*.
. Wähle mindestens einen Filter.
. Klicke auf *Suchen* (icon:search[role="blue"]). +
→ Die Datensätze, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicke in die Zeile des Datensatzes. +
→ Die Übersicht mit den Bereichen *Rechnungsadresse*, *Stammdaten* und *Info* wird geöffnet.
. Klicke in der oberen Zeile auf *Alle Daten dieses Kontakts herunterladen* (icon:file_download[set=material]). +
→ Ein Dialogfenster wird angezeigt. Lege den Speicherort für die ZIP-Datei auf deinem Computer fest.

Weitere Informationen zu der Download-Datei findest du in diesem link:https://forum.plentymarkets.com/t/dsgvo-button-fuer-den-datenexport-zu-einem-kunden-integriert/486915[Changelog^]-Beitrag im plentymarkets Forum.

[#datensatz-anonymisieren]
== Datensatz anonymisieren

Daten zu einem Kontakt können mit einem Klick gelöscht oder so unkenntlich gemacht werden, dass kein Bezug mehr zu dieser Person hergestellt werden kann.

[TIP]
Das Anonymisieren der Daten ist nur bei einem Kontaktdatensatz möglich, nicht bei einer Gastbestellung.

[.instruction]
Datensatz anonymisieren:

. Öffne das Menü *CRM » Schnellsuche*.
. Wähle mindestens einen Filter.
. Klicke auf *Suchen* (icon:search[role="blue"]). +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicke in die Zeile des Kontakts. +
→ Die Übersicht des Kontakts wird geöffnet.
. Klicke in der oberen Zeile auf *Datensatz anonymisieren* (icon:user-secret[]). +
→ Ein Fenster mit einer Sicherheitsabfrage wird angezeigt.
. Gib die ID des Kontakts, den du anonymisieren möchten, ein.
. Klicke auf *Anonymisieren*. +
→ Der Datensatz wird anonymisiert.

[TIP]
.Welche Daten werden anonymisiert und gelöscht?
====
Mit einem Klick auf *Anonymisieren* (icon:user-secret[]) werden die folgenden Daten im Datensatz des Kontakts anonymisiert und gelöscht:

* Diese Daten werden anonymisiert: Vorname, Nachname
* Diese Daten werden gelöscht: Kontaktoptionen, Adressoptionen, Adressen, Adressverknüpfungen, Auftragsverknüpfungen, Verknüpfungen zu einer Firma, Bankdaten
====
