= Schnellsuche
:keywords: Schnellsuche, Adresssuche, Adressen suchen, DSGVO, Gastzugang, Gastbestellung, als Gast bestellen, Gast suchen, Kunde anonymisieren, anonymisieren, Kundendaten löschen, Datensatz löschen, Kunde löschen, Kontakt löschen, alle Daten vom Kunden herunterladen, Kundendaten herunterladen, Kontakt verlangt Löschung, Kontakt Löschantrag, Kunde Löschantrag, Kunde verlangt Löschung
:description: Erfahre, wie du die Schnellsuche in plentymarkets verwendest.
:id: RZPMSR4
:author: team-crm

Verwende die Schnellsuche, um alle Informationen eines Kontakts oder die Adressdaten einer Gastbestellung auf einen Blick zu erhalten. Erfahre auf dieser Handbuchseite, wie du DSGVO-gemäß <<#alle-daten-herunterladen, alle Daten zu einem Kontakt oder einer Gastbestellung herunterlädst>> und wie du <<#datensatz-anonymisieren, Datensätze anonymisierst>>.

[NOTE]
.Gastbestellungen, die über den plentyShop ins System kommen, können nur in der Schnellsuche gefunden werden
====
Um DSGVO-konform zu arbeiten, wird bei Gastbestellungen, die über den plentyShop in dein System kommen, _kein_ Kontaktdatensatz erstellt. Es werden lediglich die Adressdaten gespeichert. Diese Daten, die in deinem plentymarkets System gespeichert werden, können daher _nicht_ über das Menü *CRM » Kontakte* gefunden werden. Die Adressdaten der Person, die als Gast in deinem plentyShop bestellt hat, können nur über die Schnellsuche gefunden werden. Daher kannst du auch nur über die Schnellsuche die Daten aus der plentyShop-Gastbestellung in einen regulären Kontaktdatensatz umwandeln.

Weitere Informationen zum Umwandeln von plentyShop-Gastbestellungen in reguläre Kontaktdatensätze findest du im Kapitel <<#gastzugang-umwandeln, plentyShop- und Marktplatz-Gastbestellung in Kontaktdatensatz umwandeln>>.
====

[#benutzerrechte]
== Rechte für Backend-Benutzer:innen

:rights-purpose: mit der Schnellsuche arbeiten können
:right-one: pass:quotes[*CRM > Kontakt > Anzeigen*]

include::_includes:partial$rights.adoc[]

Weitere Informationen zu den Rechten für das Menü *CRM » Kontakte* für Backend-Benutzer:innen findest du auf der Handbuchseite xref:crm:vorbereitende-einstellungen.adoc#rechte-vergeben[Vorbereitende Einstellungen vornehmen].

[#datensatz-suchen]
== Datensatz suchen

Gehe wie im Folgenden beschrieben vor, um Datensätze über die Schnellsuche zu suchen.

[.instruction]
Datensatz über die Schnellsuche suchen:

. Öffne das Menü *CRM » Schnellsuche*.
* *_Möglichkeit 1:_* Klicke auf material:search[] (*Suchen*), um eine Liste aller Datensätze zu sehen. 
* *_Möglichkeit 2:_* Gib einen Wert im Suchfeld ein und wähle dann den für dich passenden Filter aus der Vorschlagsliste. *_Beispiel:_* Wenn du eine Zahl eingibst, werden dir mögliche Filter mit dieser ID vorgeschlagen wie z.B. die Kontakt-ID.
* *_Möglichkeit 3:_* Klicke auf material:tune[], um die Suchergebnisse mit Hilfe von Filtern einzugrenzen.
. Beachte die Erläuterungen zu den Filtern in <<#table-filter-quick-search>>.  +
*_Tipp:_* Gib eine Kombination aus allen oder mehreren Werten und Optionen ein, um die Suche noch genauer einzugrenzen.
. Klicke auf material:search[] *Suchen*. +
→ Die Datensätze, die den eingestellten Suchkriterien entsprechen, werden in der Übersicht angezeigt. <<#table-settings-quick-search>> erläutert weitere Einstellungsmöglichkeiten im Datensatz.

[[table-filter-quick-search]]
.Filter in der Schnellsuche
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *ID*
|Jeder Kontaktdatensatz erhält automatisch eine fortlaufende und einzigartige ID. Dies ist unabhängig davon, ob der Kontakt manuell oder automatisch erstellt wurde. 2 Kontakte haben somit nie die selbe ID. Die ID entspricht immer einer echten Zahl. Ungültig sind daher z.B. 00521 oder ABC8354. +
*_Hinweis:_* Mit einem Klick auf die Pfeile (icon:sort[]) neben der ID in der Übersicht kannst du die gefundenen Datensätze aufsteigend oder absteigend nach ihrer ID anzeigen.

| *Name*
|Gib den Vornamen und/oder Nachnamen oder den Firmennamen ein, um Datensätze mit diesem Namen anzuzeigen. +
*_Hinweis:_* Mit einem Klick auf die Pfeile (icon:sort[]) in den Spalten *Vorname* und *Nachname* in der Übersicht kannst du die gefundenen Datensätze alphabetisch sortiert anzeigen.

| *Kontaktdaten*
|In diesem Feld kannst du nach dem Namen, der Adresse, der Firma, der Kundennummer und dem eBay-Namen suchen. +
*_Hinweis:_* Um nach dem eBay-Namen zu suchen, gib zuerst den Parameter `ebay:` gefolgt vom gesuchten eBay-Namen ein.

| *E-Mail*
|Gib die komplette E-Mail-Adresse ein, um den Datensatz mit dieser E-Mail-Adresse anzuzeigen.

| *Telefon*
|Gib die Telefonnummer ein, um nur den Datensatz mit dieser Telefonnummer anzuzeigen. Es kann auch nach Teilen der Telefonnummer gesucht werden. Du musst mindestens 3 Ziffern eingeben.

| *Adresse*
|Gib den Straßennamen und/oder die Hausnummer ein. Es ist möglich, nur nach Teilen des Straßennamens und Teilen der Hausnummer zu suchen.

| *PLZ*
|Gib die Postleitzahl ein. +
*_Hinweis:_* Es wird auch nach Postleitzahlen, die in den Adressdatensätzen des Kontakts gespeichert sind, gesucht. Es ist möglich, nur nach Teilen der Postleitzahl zu suchen. Du musst mindestens 3 Ziffern eingeben.

| *Ort*
|Gib den Ort, der im Datensatz gespeichert ist, ein. Es wird auch nach Orten, die in den Adressdatensätzen des Kontakts gespeichert sind, gesucht. Es ist möglich, nur nach Teilen des Ortsnamens zu suchen.

| *Land*
|Wähle das Land, um nur Datensätze aus diesem Land anzuzeigen. Das Land ist in den Kontaktdaten gespeichert. +
Wähle die Einstellung *Alle außer Deutschland*, um nur Datensätze aus allen Ländern außer Deutschland anzuzeigen.

| *Tags*
|Wähle ein Tag, um nur Datensätze mit diesem Tag anzuzeigen.

| *Eigner*
|Wähle den Eigner, um nur Datensätze anzuzeigen, die mit diesem Eigner verknüpft sind. Der Eigner muss in den Kontaktdaten gespeichert sein. +
*_Wichtig:_* In der Dropdown-Liste werden nur Benutzer:innen angezeigt, bei denen im Konto im Tab *Eigner* die Option *Kunde* aktiviert ist.

| *Typ*
|Wähle den Typ, um nur Datensätze mit diesem Typ anzuzeigen.

| *Bewertung*
|Wähle die Bewertung, um nur Datensätze mit dieser Bewertung anzuzeigen. 5 gelbe Sterne stehen für die beste und 5 rote Sterne für die schlechteste Bewertung.

| *Kundenklasse*
|Wähle die Kundenklasse, um nur Kontakte mit dieser Kundenklasse anzuzeigen.

| *Mandant*
|Wähle den Mandanten, um nur Datensätze dieses Mandanten anzuzeigen. Der Mandant ist in den Kontaktdaten gespeichert. +
*_Wichtig:_* Backend-Benutzer:innen stehen nur Mandanten zur Auswahl, für die sie eine Berechtigung haben. Berechtigungen werden im Menü *Einrichtung » Einstellungen » Benutzer » Konten* im Tab xref:business-entscheidungen:benutzerkonten-zugaenge.adoc#100[Berechtigungen] des Benutzer:innenkontos eingestellt.

| material:replay[]
|Setzt die gewählten Filterkriterien zurück.

| material:search[] *SUCHEN*
|Führt die Suche aus. Die gefundenen Datensätze werden in der Übersicht angezeigt. +
*_Tipp:_* Setze keine Filter, wenn du alle Datensätze in der Übersicht sehen möchtest.

|====

[TIP]
Wenn du im Menü *CRM » Schnellsuche* einen Datensatz öffnest, kannst du mit einem Klick auf *Start* (material:play_circle[]) den Timer starten. Mit einem Klick auf *Pause* (material:pause_circle[]) hältst du den Timer an. Klicke auf *Zurücksetzen* (terra:reset[]), um die Zeit auf 0 zu setzen.

[#datensatz-bearbeiten]
== Datensatz bearbeiten

Wenn du den gewünschten <<#datensatz-suchen, Datensatz gefunden>> hast, siehst du in der ersten Zeile des Datensatzes weitere Bearbeitungsmöglichkeiten, die in <<#table-settings-quick-search>> erläutert werden.

[[table-settings-quick-search]]
.Einstellungen in der Schnellsuche
[cols="2,6"]
|====
|Einstellung |Erläuterung

| *KONTAKT-ID*
|Öffnet den xref:crm:kontakt-bearbeiten.adoc#[Kontaktdatensatz] im Menü *CRM » Kontakte*. +
*_Hinweis:_* Wenn es sich bei dem Datensatz um eine Gastbestellung handelt, ist dieses Feld ausgegraut.

| *AUFTRÄGE*
|Öffnet das Menü *Aufträge » Aufträge bearbeiten*. Als Filter ist die ID des Kontakts automatisch gewählt. +
Mit einem Klick auf material:add[] *Neuer Auftrag* rechts neben *AUFTRÄGE* wird ein neuer xref:auftraege:auftraege-verwalten.adoc#[Auftrag] im Menü *Aufträge » Aufträge bearbeiten* erstellt. +
*_Hinweis:_* Wenn es sich bei dem Datensatz um eine Gastbestellung handelt, sind diese Felder ausgegraut.

| *ANGEBOTE*
|Öffnet das Menü *Aufträge » Aufträge bearbeiten*. Als Filter ist die ID des Kontakts automatisch gewählt. +
Mit einem Klick auf material:add[] *Neues Angebot* rechts neben *ANGEBOTE* wird ein neues Angebot im Menü *Aufträge » Aufträge bearbeiten* erstellt. +
*_Hinweis:_* Wenn es sich bei dem Datensatz um eine Gastbestellung handelt, sind diese Felder ausgegraut.

| *MESSENGER*
|Öffnet weiter unten den Bereich *Messenger*. +
Mit einem Klick auf material:add[] *Neue Nachricht* rechts neben *MESSENGER* öffnet sich weiter unten das Bearbeitungsfenster zum Erstellen einer neuen Nachricht. Die Stoppuhr oben rechts im Messenger-Bereich startet automatisch, sobald die neue Nachricht geöffnet wird. Klicke neben dem Feld *Minuten* auf *Kostenpflichtig* (material:toggle_off[] terra:pay_cash[]), um die Zeit abzurechnen. +
*_Hinweis:_* Weitere Informationen findest du auf der Handbuchseite xref:crm:messenger.adoc#[Messenger]. +
*_Hinweis:_* Wenn es sich bei dem Datensatz um eine Gastbestellung handelt, sind die Felder *MESSENGER* und *Neue Nachricht* ausgegraut.

| *TICKETS*
|Öffnet das Menü *CRM » Ticketsystem*. Als Filter ist die ID des Kontakts automatisch gewählt. +
Mit einem Klick auf material:add[] *Neues Ticket* rechts neben *TICKETS* öffnet sich das Bearbeitungsfenster zum Erstellen eines neuen xref:crm:ticketsystem-nutzen.adoc#[Tickets] im Menü *CRM » Ticketsystem*. +
*_Hinweis:_* Wenn es sich bei dem Datensatz um eine Gastbestellung handelt, sind diese Felder ausgegraut.

| *Alle Daten dieses Kontakts herunterladen*
|Mit einem Klick auf material:file_download[] werden alle gespeicherten Daten zu diesem Datensatz heruntergeladen. +
Weitere Informationen findest du im Kapitel <<#alle-daten-herunterladen, Alle Daten zu einem Kontakt oder einer Gastbestellung herunterladen>>.

| *Newsletter Opt-In E-Mail senden*
|Mit einem Klick auf material:outgoing_mail[] wird eine E-Mail zum Newsletter-Opt-In bzw. die Bestätigung zum Newsletter-Opt-In versendet. +
*_Hinweis:_* Wenn die Person noch nicht für den Newsletter angemeldet ist, erhält sie die automatische E-Mail für Newsletter-Opt-In. Wenn die Person bereits für den Newsletter angemeldet ist, aber noch nicht bestätigt hat, erhält sie die Bestätigung zum Newsletter-Opt-In. +
*_Hinweis:_* Wenn es sich bei dem Datensatz um eine Gastbestellung handelt, ist dieses Feld ausgegraut.

| *Datensatz anonymisieren*
|Mit einem Klick auf icon:user-secret[] wird der Datensatz anonymisiert. Das Anonymisieren der Daten ist nur bei einem Kontaktdatensatz möglich, _nicht_ bei einer Gastbestellung. +
Weitere Informationen findest du im Kapitel <<#datensatz-anonymisieren, Datensatz anonymisieren>>.

| *Gast in Kontakt umwandeln*
|Mit einem Klick auf material:swap_horiz[] werden die Adressdaten aus einer Gastbestellung in einen regulären Kontaktdatensatz umgewandelt. Im neu erstellten Kontaktdatensatz wird dann im Bereich *Historie* der Eintrag *Umgewandelt von* sowie der Name der Person, die den Datensatz umgewandelt hat, hinzugefügt. +
Weitere Informationen findest du im Kapitel <<#gastzugang-umwandeln, plentyShop- und Marktplatz-Gastbestellung in Kontaktdatensatz umwandeln>>. +
*_Hinweis:_* Wenn es sich bereits um einen Kontakt handelt, ist dieses Feld ausgegraut.

| *Daten neu laden*
|Mit einem Klick auf icon:undo[] werden die Daten in diesem Datensatz aktualisiert.

| *Pause* / *Start*
|Mit einem Klick auf material:pause_circle[] hältst du den Timer an. Mit einem Klick auf material:play_circle[] wird der Timer wieder gestartet.

| *Zurücksetzen*
|Mit einem Klick auf terra:reset[] setzt du den Timer zurück auf 0.

|====

[#gastzugang-umwandeln]
== plentyShop- und Marktplatz-Gastbestellung in Kontaktdatensatz umwandeln 

Im Menü *CRM » Schnellsuche* kannst du mit nur einem Klick die Adressdaten aus einer Gastbestellung, die entweder über deinen plentyShop oder über einen Marktplatz in dein System gekommen sind, in einen regulären Kontaktdatensatz umwandeln.

* Bei einer Gastbestellung über den plentyShop besteht der gespeicherte Datensatz lediglich aus der Adresse und dem zugehörigen Auftrag; eine Kontakt-ID wird _nicht_ vergeben, jedoch wird das Symbol material:done[] in der Übersicht in der Spalte *Gast* angezeigt.

* Bei einer Gastbestellung über einen Marktplatz wird eine Kontakt-ID vergeben und das Symbol material:done[] wird in der Übersicht in der Spalte *Gast* angezeigt.

Wenn in der Adresse zusätzlich ein Firmenname enthalten ist, wird beim Umwandeln des Datensatzes auch ein Firmendatensatz erstellt.

[.instruction]
plentyShop- und Marktplatz-Gastbestellung in Kontaktdatensatz umwandeln:

. Öffne das Menü *CRM » Schnellsuche*.
* *_Möglichkeit 1:_* Klicke auf material:search[] (*Suchen*), um eine Liste aller Datensätze zu sehen. 
* *_Möglichkeit 2:_* Gib einen Wert im Suchfeld ein und wähle dann den für dich passenden Filter aus der Vorschlagsliste.
* *_Möglichkeit 3:_* Klicke auf material:tune[], um die Suchergebnisse mit Hilfe von Filtern einzugrenzen.
. Beachte die Erläuterungen zu den Filtern in <<#table-filter-quick-search>>.  +
*_Tipp:_* Gib eine Kombination aus allen oder mehreren Werten und Optionen ein, um die Suche noch genauer einzugrenzen.
. Klicke auf material:search[] *Suchen*. +
→ Die Datensätze, die den eingestellten Suchkriterien entsprechen, werden in der Übersicht angezeigt. 
. Klicke in die Zeile des Datensatzes. +
→ Der Datensatz wird geöffnet.
. Klicke in der oberen Zeile auf *Gast in Kontakt umwandeln* (material:swap_horiz[]). +
→ Ein Fenster mit einer Sicherheitsabfrage wird angezeigt. +
. Wenn du DSGVO-konform gearbeitet hast, klicke auf *Umwandeln*. +
→ Der Datensatz der Gastbestellung wird in einen Kontaktdatensatz umgewandelt und erhält automatisch die nächste freie Kontakt-ID. Im Bereich *Historie* des Kontaktdatensatzes wird der Eintrag *Umgewandelt von* sowie der Name der Person, die den Datensatz umgewandelt hat, hinzugefügt.

[TIP]
.plentyShop-Gastbestellungen und Marktplatz-Gastbestellungen 
====
plentyShop-Gastbestellungen erhalten das Symbol material:done[] in der Übersicht in der Spalte *Gast*, jedoch _keine_ Kontakt-ID. Marktplatz-Gastbestellungen erhalten das Symbol material:done[] in der Übersicht in der Spalte *Gast* und zusätzlich eine Kontakt-ID.

*_Hinweise zum Umwandeln einer Gastbestellung in einen Kontaktdatensatz:_*

* Das Umwandeln einer plentyShop-Gastbestellung ist nur im Menü *CRM » Schnellsuche* möglich.

* Das Umwandeln einer Marktplatz-Gastbestellung ist sowohl im Menü *CRM » Schnellsuche* als auch über den Kontaktdatensatz im Menü *CRM » Kontakte* möglich. Wie du dazu vorgehst, ist im Kapitel xref:crm:kontakt-bearbeiten.adoc#gastzugang-in-regulaeren-zugang-umwandeln[Gastbestellung in regulären Kontaktdatensatz umwandeln] auf der Seite xref:crm:kontakt-bearbeiten.adoc#[Kontakt bearbeiten] beschrieben.
====

[#alle-daten-herunterladen]
== Alle Daten zu einem Kontakt oder einer Gastbestellung herunterladen

Im Menü *CRM » Schnellsuche* kannst du mit einem Klick alle zu einem Kontakt gehörigen Daten oder die zu einer Gastbestellung gehörigen Adressdaten als ZIP-Datei herunterladen. Die ZIP-Datei enthält eine HTML-Datei sowie eine maschinenlesbare Datei im JSON-Format.

[.instruction]
Alle Daten zu einem Kontakt oder einer Gastbestellung herunterladen:

. Öffne das Menü *CRM » Schnellsuche*.
* *_Möglichkeit 1:_* Klicke auf material:search[] (*Suchen*), um eine Liste aller Datensätze zu sehen. 
* *_Möglichkeit 2:_* Gib einen Wert im Suchfeld ein und wähle dann den für dich passenden Filter aus der Vorschlagsliste.
* *_Möglichkeit 3:_* Klicke auf material:tune[], um die Suchergebnisse mit Hilfe von Filtern einzugrenzen.
. Beachte die Erläuterungen zu den Filtern in <<#table-filter-quick-search>>.  +
*_Tipp:_* Gib eine Kombination aus allen oder mehreren Werten und Optionen ein, um die Suche noch genauer einzugrenzen.
. Klicke auf material:search[] *Suchen*. +
→ Die Datensätze, die den eingestellten Suchkriterien entsprechen, werden in der Übersicht angezeigt. 
. Klicke in die Zeile des Datensatzes. +
→ Der Datensatz wird geöffnet.
. Klicke in der oberen Zeile auf *Alle Daten dieses Kontakts herunterladen* (material:file_download[]). +
→ Ein Dialogfenster wird angezeigt. Lege den Speicherort für die ZIP-Datei auf deinem Computer fest.

Weitere Informationen zu der Download-Datei findest du in diesem link:https://forum.plentymarkets.com/t/dsgvo-button-fuer-den-datenexport-zu-einem-kunden-integriert/486915[Changelog^]-Beitrag im plentymarkets Forum.

[#datensatz-anonymisieren]
== Datensatz anonymisieren

Daten zu einem Kontakt können mit einem Klick gelöscht oder so unkenntlich gemacht werden, dass kein Bezug mehr zu dieser Person hergestellt werden kann.

[TIP]
Das Anonymisieren der Daten ist nur bei einem Kontaktdatensatz möglich, nicht bei einer Gastbestellung.

[IMPORTANT]
.Welche Daten werden anonymisiert und gelöscht?
====
Mit einem Klick auf *Anonymisieren* (icon:user-secret[]) werden die folgenden Daten im Datensatz des Kontakts anonymisiert und gelöscht:

* Diese Daten werden anonymisiert: Vorname, Nachname
* Diese Daten werden gelöscht: Kontaktoptionen, Adressoptionen, Adressen, Adressverknüpfungen, Auftragsverknüpfungen, Verknüpfungen zu einer Firma, Bankdaten
====

[.instruction]
Datensatz anonymisieren:

. Öffne das Menü *CRM » Schnellsuche*.
* *_Möglichkeit 1:_* Klicke auf material:search[] (*Suchen*), um eine Liste aller Datensätze zu sehen. 
* *_Möglichkeit 2:_* Gib einen Wert im Suchfeld ein und wähle dann den für dich passenden Filter aus der Vorschlagsliste.
* *_Möglichkeit 3:_* Klicke auf material:tune[], um die Suchergebnisse mit Hilfe von Filtern einzugrenzen.
. Beachte die Erläuterungen zu den Filtern in <<#table-filter-quick-search>>.  +
*_Tipp:_* Gib eine Kombination aus allen oder mehreren Werten und Optionen ein, um die Suche noch genauer einzugrenzen.
. Klicke auf material:search[] *Suchen*. +
→ Die Datensätze, die den eingestellten Suchkriterien entsprechen, werden in der Übersicht angezeigt. 
. Klicke in die Zeile des Datensatzes. +
→ Der Datensatz wird geöffnet.
. Klicke in der oberen Zeile auf *Datensatz anonymisieren* (icon:user-secret[]). +
→ Ein Fenster mit einer Sicherheitsabfrage wird angezeigt.
. Gib die ID des Kontakts, den du anonymisieren möchten, ein.
. Klicke auf *Anonymisieren*. +
→ Der Datensatz wird anonymisiert.
