= Vorbereitende Einstellungen vornehmen
:keywords: Adress-Layout, Adresslayout, Adresslayout Dokumente, Kundenklasse, Kontaktklasse, Kundentyp, Typ, Kundenklasse erstellen, Typ erstellen, Eigenschaften für Kontakt erstellen, Kundeneigenschaften, Kunden Eigenschaften auf Dokumenten, Tags für Kontakte, Tags für Kunden, Kontakttags, Kunden-Tags, Rabattsystem, Rabatt auf Kundenklasse, Kundenklassenrabatt, Rabattstaffel auf Nettowarenwert, Rabatt auf Zahlungsart, Verkaufspreis als Rabatt, manueller Rabatt für Kunden, manueller Rabatt für Kontakte, Rabatt für Kunden gewähren
:descriptions: Erfahre, welche vorbereitenden Einstellungen du vornehmen musst, um mit Kontaktdatensätzen in plentymarkets zu arbeiten.
:page-pagination:
:author: team-crm

Du musst einige vorbereitende Einstellungen vornehmen, damit du die Kontaktverwaltung im Menü *CRM » Kontakte* optimal nutzen kannst.

Mit einem Klick auf einen Eintrag in der folgenden Liste gelangst du direkt in das jeweilige Unterkapitel:

* <<#adress-layout, Adress-Layout für standortbezogene Auftragsdokumente einrichten>>
* <<#rechte-vergeben, Rechte für Backend-Benutzer:innen vergeben>>
** <<#rechte-freigeben-bereiche-schaltflaechen, Rechte für bestimmte Bereiche und Schaltflächen im Kontaktdatensatz freigeben>>
** <<#ansichten-freigeben-andere-benutzer, Ansichten für andere Benutzer:innen freigeben>>
* <<#kundenklasse-erstellen, Kundenklasse erstellen>>
* <<#typ-erstellen, Typ erstellen>>
* <<#tags-erstellen, Tags erstellen>>
* <<#eigenschaften-einleitung, Eigenschaften erstellen>>
* <<#rabattsystem-nutzen, Rabattsystem nutzen>> (optional)

[#adress-layout]
== Adress-Layout für standortbezogene Auftragsdokumente einrichten

Im Menü *Einrichtung » CRM » Adress-Layout* kannst du individuell Adress-Layouts für deine Lieferländer für deine xref:auftraege:auftragsdokumente-neu.adoc#[standortbezogenen Auftragsdokumente] wie xref:auftraege:lieferscheine-erzeugen-neu.adoc#[Lieferscheine], xref:auftraege:rechnungen-erzeugen-neu.adoc#[Rechnungen], xref:auftraege:gutschriften-erzeugen-neu.adoc#[Gutschriften] und xref:auftraege:ruecksendeschein-erzeugen-neu.adoc#[Rücksendescheine] einrichten. Die Adress-Layouts für die Lieferländer _Deutschland_, _Frankreich_ und das _Vereinigte Königreich_ sind bereits standardmäßig in deinem plentymarkets System vorhanden. Gehe wie im Folgenden beschrieben vor, um ein neues Adress-Layout für deine Auftragsdokumente einzurichten.

[.instruction]
Adress-Layout für standortbezogene Auftragsdokumente einrichten:

. Öffne das Menü *Einrichtung » CRM » Adress-Layout*.
. Klicke auf *Neues Layout* (material:add[]).
. Nimm die gewünschten Einstellungen vor. Beachte dazu die Erläuterungen in <<#table-set-up-address-layout>>.
. *Speichere* (material:save[]) die Einstellungen.

[[table-set-up-address-layout]]
.Adress-Layout für standortbezogene Auftragsdokumente einrichten
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+^| *Allgemeine Einstellungen*

| *Layout-Name*
|Wie lautet der Name des Layouts?

| *Als Standard-Adress-Layout verwenden*
|Soll dieses Layout als Standard verwendet werden? Dann aktiviere die Umschaltfläche (material:toggle_on[role=skyBlue]). In der Übersicht auf der linken Seite ist das Standard-Adress-Layout mit einem Sternchen (material:star[]) gekennzeichnet.

2+^| *Liste der Feldnamen* +
Wenn gewünscht, gib den englischen und den deutschen Namen für die Feldnamen ein, damit diese Namen dann beim Gestalten des Adress-Layouts angezeigt werden.

2+^| *Zum Layout-Design wechseln* +
Mit einem Klick auf material:sync_alt[] wechselst du zum Layout-Design. Die Bereiche *Länder*, *Layout* und *Felder* werden sichtbar.

| *Länder*
|Wähle ein Land oder mehrere Länder aus der Liste, für die das Adress-Layout gelten soll.

| *Layout* / +
*Felder*
|Ziehe aus dem Bereich *Felder* die Adressfelder in den Bereich *Layout* und gestalte so das Adress-Layout individuell für jedes Lieferland per Drag-and-drop. +
*_Tipp:_* Es ist möglich, weitere Reihen (maximale Anzahl der Reihen:{nbsp}6) hinzuzufügen, einzelne Felder zu entfernen und komplette Reihen zu entfernen. Auch leere Reihen sind erlaubt. Eine Beschränkung der Feldanzahl pro Reihe ist _nicht_ vorhanden.

|====

[discrete]
=== Neues Adress-Layout im standortbezogenen Auftragsdokument aktivieren

Damit deine xref:auftraege:auftragsdokumente-neu.adoc#[standortbezogenen Auftragsdokumente] für die Lieferländer automatisch in den erstellten Adress-Layouts ausgegeben werden, musst du eine Einstellung in dem jeweiligen Auftragsdokument vornehmen. Dein plentymarkets System prüft dann automatisch das Lieferland aus dem Auftrag und gibt das entsprechende Auftragsdokument in den im Menü *Einrichtung » CRM » Adress-Layout* aufgelisteten Layout aus. Gehe dazu wie im Folgenden beschrieben vor.

[.instruction]
Neues Adress-Layout im standortbezogenen Auftragsdokument aktivieren:

. Öffne das Menü *Einrichtung » Mandant » [Mandant wählen] » Standorte » [Standort wählen] » Dokumente » [Dokument wählen]*.
. Aktiviere (material:check_box[role=skyBlue]) im Bereich *Grundeinstellungen: _Dokumentenname_* die Option *Neues Adresslayout*. +
→ Die Option darüber *Aufbau der Rechnungs-/ Lieferanschrift* wird ausgeblendet und das Dokument wird in dem Adresslayout, das du im Menü *Einrichtung » CRM » Adress-Layout* gespeichert hast, ausgegeben.
. *Speichere* (material:save[]) die Einstellungen.


[discrete]
=== Rechte für das Adress-Layout für Backend-Benutzer:innen vergeben

:rights-purpose: Address-Layouts sehen und bearbeiten können
:right-one: pass:quotes[*CRM > Adress-Layout > Anzeigen*]
:right-two: pass:quotes[*CRM > Adress-Layout > Erstellen*]
:right-three: pass:quotes[*CRM > Adress-Layout > Aktualisieren*]

include::_includes:partial$rights.adoc[]

[#rechte-vergeben]
== Rechte für Backend-Benutzer:innen vergeben

:rights-purpose: pass:quotes[mit dem Menü *CRM » Kontakte* arbeiten können]
:right-one: pass:quotes[*CRM > Adresse > Anzeigen*]
:right-two: pass:quotes[*CRM > Kontakt > Anzeigen*]
:right-three: pass:quotes[*Einrichtung > Eigenschaft > Anzeigen*]
:right-four: pass:quotes[*Einrichtung > Tag > Anzeigen*]

include::_includes:partial$rights.adoc[]

[#rechte-freigeben-bereiche-schaltflaechen]
=== Rechte für bestimmte Bereiche und Schaltflächen im Kontaktdatensatz freigeben

Wenn Personen mit *Backend*-Zugriffsrechten bestimmte xref:crm:kontakt-bearbeiten.adoc#erlaeuterungen-einzelne-bereiche[Bereiche im Kontaktdatensatz] und/oder Schaltflächen und Funktionen in diesen Bereichen nicht sehen können, prüfe die Rechte im Menü *Einrichtung » Einstellungen » Benutzer » Rechte » Benutzer* im jeweiligen Benutzer:innenkonto.

[.collapseBox]
.Rechte für Bereiche, Schaltflächen und Funktionen im Kontaktdatensatz
--

<<#table-missing-areas-contact-data-record>> listet die Rechte auf, die im Benutzer:innenkonto aktiviert werden müssen, wenn eine Person mit *Backend*-Zugriffsrechten Bereiche im Kontaktdatensatz nicht sehen kann.

[[table-missing-areas-contact-data-record]]
.Rechte für Bereiche im Kontaktdatensatz
[cols="2,2"]
|====
|Fehlender Bereich im Kontaktdatensatz |Benötigtes Recht im Benutzer:innenkonto

| xref:crm:kontakt-bearbeiten.adoc#auftraege[Aufträge], xref:crm:kontakt-bearbeiten.adoc#konto[Konto]
|Aufträge > Anzeigen +
Aufträge > Auftragsstatus > Anzeigen

| xref:crm:kontakt-bearbeiten.adoc#eigenschaften[Eigenschaften]
|Einrichtung > Eigenschaft > Anzeigen +
Einrichtung > Eigenschaft > Relation > Anzeigen

| xref:crm:kontakt-bearbeiten.adoc#bankdaten[Bankdaten]
|CRM > Bankdaten > Anzeigen

| xref:crm:kontakt-bearbeiten.adoc#tickets[Tickets]
|CRM > Ticket > Anzeigen

| xref:crm:kontakt-bearbeiten.adoc#firma[Firma]
|CRM > Firma > Anzeigen

| xref:crm:kontakt-bearbeiten.adoc#messenger[Messenger]
|CRM > Nachricht > Anzeigen

|====

<<#table-missing-buttons-contact-data-record>> listet die Rechte auf, die im Benutzer:innenkonto aktiviert werden müssen, wenn eine Person mit *Backend*-Zugriffsrechten Schaltflächen und/oder Funktionen innerhalb bestimmter Bereiche im Kontaktdatensatz nicht sehen kann.

[[table-missing-buttons-contact-data-record]]
.Rechte für Schaltflächen und Funktionen im Kontaktdatensatz
[cols="2,2"]
|====
|Fehlende Schaltfläche/Funktion im Kontaktdatensatz |Benötigtes Recht im Benutzer:innenkonto

| xref:crm:kontakt-bearbeiten.adoc#plentyshop-login[plentyShop-Login], xref:crm:kontakt-bearbeiten.adoc#passwort-manuell-aendern[Passwort ändern], Eingabefeld mit Login-URL, xref:crm:kontakt-bearbeiten.adoc#link-kopieren-oeffnen[Schaltfläche zum Kopieren], xref:crm:kontakt-bearbeiten.adoc#link-kopieren-oeffnen[Link öffnen]
|CRM > Passwort > Bearbeiten

| Übersicht, xref:crm:kontakt-bearbeiten.adoc#auftraege[Aufträge], neuer Auftrag, neues Angebot etc.
|Aufträge > Erstellen

|Übersicht, Tickets, xref:crm:kontakt-bearbeiten.adoc#tickets[Schaltfläche zum Erstellen eines neuen Tickets]
|CRM > Ticket > Erstellen

|Übersicht, xref:crm:kontakt-suchen.adoc#kontextmenue-uebersicht[Messenger-Schaltfläche im Kontextmenü]
|CRM > Nachricht > Anzeigen

|Messenger, xref:crm:kontakt-bearbeiten.adoc#messenger[Schaltfläche zum Erstellen einer neuen Nachricht]
|CRM > Nachricht > Erstellen

|Bankdaten, xref:crm:kontakt-bearbeiten.adoc#bankdaten[Bankdaten hinzufügen/bearbeiten/löschen]
|CRM > Bankdaten > Erstellen +
CRM > Bankdaten > Aktualisieren +
CRM > Bankdaten > Löschen

| Firmen, xref:crm:kontakt-bearbeiten.adoc#firma-noch-nicht-verknuepft[Verknüpfung zum Kontakt erstellen], xref:crm:kontakt-bearbeiten.adoc#verknuepfung-firma-loeschen[Verknüpfung zur Firma löschen]
|CRM > Firma > Erstellen +
CRM > Firma > Aktualisieren +
CRM > Firma > Löschen

|Kontaktdetails Kontextmenü, xref:crm:kontakt-bearbeiten.adoc#kontakt-loeschen-detailansicht[Löschen-Schaltfläche]
|CRM > Kontakt > Löschen

|Übersicht, xref:crm:kontakt-bearbeiten.adoc#kontakt-loeschen-uebersicht[Kontextmenü], Schaltfläche xref:crm:kontakt-suchen.adoc#kontextmenue-uebersicht[Kontakt löschen]
|CRM > Kontakt > Löschen

|====
--

[#ansichten-freigeben-andere-benutzer]
=== Ansichten für andere Benutzer:innen freigeben

Zu einem späteren Zeitpunkt wirst du vielleicht eine xref:crm:kontakt-erstellen.adoc#ansicht-einrichten[neue Ansicht zum Erstellen eines neues Kontakts] oder eine xref:crm:kontakt-bearbeiten.adoc#ansicht-bearbeiten[neue Ansicht zum Bearbeiten eines bestehenden Kontakts] einrichten. Du kannst diese Ansichten dann auch anderen Benutzer:innen in deinem plentymarkets System freigeben, damit sie mit den Ansichten arbeiten können. +
Die Standardansicht ist für alle Benutzer:innen standardmäßig aktiviert. Du hast auch die Möglichkeit, einer Benutzer:in die Rechte für die Standardansicht zu entziehen.

Alle Einstellungen, die sich auf die Freigabe von Ansichten beziehen, nimmst du im Benutzer:innenkonto im Menü *Einrichtung » Einstellungen » Benutzer » Rechte » Benutzer* im Menüpunkt *Ansichten* vor.

* Ansichten zum Erstellen eines neuen Kontaktdatensatzes für Benutzer:innen freigeben: +
Öffne im Benutzer:innenkonto im Menüpunkt *Ansichten* den Bereich *CRM > Kontakte > Neuer Kontakt > Eigene Ansichten*. Wähle (material:check_box[role=skyBlue]) die gewünschten Ansichten aus der Liste.

* Ansichten zum Bearbeiten eines bestehenden Kontaktdatensatzes für Benutzer:innen freigeben: +
Öffne im Benutzer:innenkonto im Menüpunkt *Ansichten* den Bereich *CRM > Kontaktdetails > Eigene Ansichten*. Wähle (material:check_box[role=skyBlue]) die gewünschten Ansichten aus der Liste.

[#kundenklasse-erstellen]
== Kundenklasse erstellen

Mit Kundenklassen unterteilst du deinen Kundenstamm nach unterschiedlichen Kriterien. So kannst du eine Kundenklasse festlegen, die an Endkund:innen (B2C) angepasst ist und mit deren Einstellungen die Artikel mit Bruttopreisen im plentyShop angezeigt werden. Für Händler:innen (B2B) erstellst du eine weitere Kundenklasse, mit deren Einstellungen die Artikel mit Nettopreisen im plentyShop angezeigt werden. Weitere Optionen, die festgelegt werden können, sind z.B. Rabatte auf den Nettowarenwert, Rabatte auf die Zahlungsart oder Rabattstaffeln, die nur für eine bestimmte Kundenklasse gelten.

[IMPORTANT]
.Hinweise
====
Wenn sich ein Kontakt in deinem plentyShop registriert und die Anrede in das Feld *Firma* ändert, greift automatisch die Kundenklasse, die du für B2B-Kontakte erstellt hast. +
Datensätze aus Gastbestellungen erhalten die selbe Kundenklasse wie B2C-Kontakte nach der Registrierung, sofern eine B2C-Kundenklasse in deinem System vorhanden ist. +
Wenn keine Kundenklassen in deinem System vorhanden sind, erhalten alle Datensätze die Kundenklasse mit der ID 0.
====

Du kannst beliebig viele Kundenklassen im Menü *Einrichtung » CRM » Kundenklassen* erstellen und individuell einrichten. Kundenklassen erhalten automatisch eine ID, die in der Übersicht vor dem Namen der Kundenklasse angezeigt wird. Die ID bestimmt jedoch _keine_ Reihenfolge, diese wird durch die *Position* festgelegt.

Wenn du eine neue Kundenklasse erstellt hast, steht diese Kundenklasse in der Detailansicht des Kontakts im Menü *CRM » Kontakte » [Kontakt öffnen]* als Auswahl zur Verfügung.

[TIP]
.Tipp: Vorab Konzept für Typen und Klassen überlegen
====
Für die Einteilung deines Kundenstamms in Typen und Klassen ist es empfehlenswert, ein Konzept zu entwickeln, bevor du größere Mengen an Kontaktdaten erstellst. Dadurch vermeidest du späteren Änderungsaufwand, z.B. wenn Typen bei fehlender Einstellung automatisch zugewiesen werden. Überlege dir also am besten vorab, welche Typen und Klassen du benötigst, erstelle die Typen und Klassen und weise sie beim Erstellen deinen Kontakten zu.
====

[.instruction]
Kundenklasse erstellen:

. Öffne das Menü *Einrichtung » CRM » Kundenklassen*.
. Wechsele in das Tab *Neue Kundenklasse*.
. Nimm die gewünschten Einstellungen vor. Beachte dazu die Erläuterungen in <<#table-create-customer-class>>.
. *Speichere* (material:save[]) die Einstellungen.

[[table-create-customer-class]]
.Kundenklasse erstellen
[cols="1,3"]
|====
|Einstellung |Erläuterung

|[#intable-customer-class-minimum-order-value]*Mindestbestellmenge*
|Gib die Mindestbestellmenge ein, wenn pro Artikel eine bestimmte Anzahl bestellt werden muss oder um eine Mindestbestellmenge für die Mengenrabatte zu gewährleisten.

|[#intable-customer-class-name]*Bezeichnung*
|Gib den Namen für die neue Kundenklasse ein, z.B. *Großhändler* oder *Premiumkunde*.

|[#intable-customer-class-position]*Position*
|Wenn keine Zahl eingegeben wird, wird eine Position automatisch anschließend an die höchste vorhandene Position vergeben. In erster Linie dient die Position der Sortierung der Kundenklassen im Menü. Dies ist z.B. in Kombination mit der Gestaltung der Sichtbarkeit der Artikelpreise im plentyShop wichtig. Dies wird unter *Anzeige der Preise im Webshop* eingestellt.

|[#intable-customer-class-terms-of-payment]*Zahlungsziel, Skontosatz, Skontofrist und Valuta*
|Zahlungsziel, Skontosatz, Skontofrist und Valuta stellen die Zahlungsbedingungen dar. +
*_Wichtig:_* Die im Kontaktdatensatz gespeicherten Zahlungsbedingungen haben Priorität vor den hier eingegebenen Werten. +
Die Zahlungsbedingungen werden in den xref:auftraege:auftraege-verwalten.adoc#intable-zahlungsbedingungen-auftrag[Auftragseinstellungen] übernommen. Auch in den Auftragseinstellungen haben die Werte im Kontaktdatensatz Priorität. Im Auftrag können sie optional entweder manuell angepasst oder eingetragen werden, falls am Kontakt und in der Kundenklasse nichts hinterlegt sein sollte. Die im Auftrag gespeicherten Zahlungsbedingungen werden dann auf xref:auftraege:auftragsdokumente.adoc#intable-zahlungsbedingungen-dokumente[Dokumenten] ausgegeben. Beachte das Beispiel xref:crm:firmen.adoc#beispiel-zahlungsbedingungen[Gestaltung von Zahlungsbedingungen mit Valuta, Zahlungsziel, Skontofrist und Skontosatz] auf der Handbuchseite xref:crm:firmen.adoc#[Firmen].

|[#intable-customer-class-contact-id]*Kunden-ID*
|Gib die ID des Kontakts ein, an den Sammelrechnungen bei xref:auftraege:auftraege-verwalten.adoc#800[Sammelaufträgen] geschickt werden sollen. Die Sammelaufträge werden kundenklassenspezifisch angelegt und die Rechnung wird an den Kontakt gesendet.

|[#intable-customer-class-discount-type]*Rabattart*
|Wähle die Rabattart. Je nach Rabattart werden mehr oder weniger Optionen eingeblendet. Wenn du keinen Rabatt vergeben möchtest, wähle die Option *Kein Rabatt*. Weitere Informationen sowie Erläuterungen zu den Rabattarten in plentymarkets findest du im Kapitel <<#rabattsystem-nutzen, Rabattsystem nutzen>>.

|[#intable-customer-class-volumen-discount]*Mengenrabatt*
|Wähle, ob der im Menü *Einrichtung » Artikel » Verkaufspreise* eingegebene Wert unter *Ab Menge* berücksichtigt werden soll oder nicht.

|[#intable-customer-class-allowed-payment-methods]*Erlaubte Zahlungsarten*
|Wähle, welche der im plentyShop verfügbaren Zahlungsarten für die Kundenklasse erlaubt sein sollen. +
In der Grundeinstellung sind alle verfügbaren Zahlungsarten erlaubt. Wenn neue Zahlungsarten integriert werden, müssen diese Zahlungsarten hier erlaubt werden, weil neue Zahlungsarten nicht automatisch mit in die Liste der erlaubten Zahlungsarten aufgenommen werden. +
*_Wichtig:_* Beachte dabei die Einstellungen hinsichtlich der xref:fulfillment:versand-vorbereiten.adoc#1000[gesperrten Zahlungsarten in den Versandprofilen], die für die Kundenklasse verwendet werden. Prüfe diese Einstellung, damit es an dieser Stelle nicht zu ungewollten Überschneidungen kommt. Die Zahlungsart, die für eine Kundenklasse erlaubt sein soll, darf in den Versandprofilen _nicht_ gesperrt sein und auch die Kundenklasse darf dort _nicht_ gesperrt sein. +
*_Tipp:_* Wenn du mehrere Zahlungsarten auf einmal aktivieren möchtest, halte die cmd-Taste gedrückt und wähle mit der Maus die gewünschten Zahlungsarten aus der Liste.

|[#intable-customer-class-payment-instruction]*Zahlungshinweis*
|Ein hier eingegebener Zahlungshinweis wird auf Einzelrechnungen angezeigt. Das können z.B. besondere Angaben zur Zahlung für eine bestimmte Kundenklasse sein.

|[#intable-customer-class-display-online-shop]*Anzeige der Preise im Webshop*
|Wähle, ob die Preise im plentyShop *Brutto* oder *Netto* angezeigt werden sollen. +
*_Wichtig:_* Diese Option legt nur die Anzeige der Preise fest, nicht die Berechnung der Preise für die Kundenklasse. Einstellung besonders für die Kundenklasse der Position 1 beachten, weil diese Kundenklassen Kontakten automatisch zugewiesen wird, wenn keine Kundenklasse im Kontaktdatensatz gewählt wurde.
|====

Du kannst Verkaufspreise mit Kundenklassen verknüpfen. Wähle dazu im Menü *Einrichtung » Artikel » Verkaufspreise* unter der Einstellung *Klasse* eine von dir erstellte Kundenklasse. Weitere Informationen findest du auf der Handbuchseite xref:artikel:preise.adoc#100[Verkaufspreise und Preiskalkulation].

[#typ-erstellen]
== Typ erstellen

Typen dienen der Einordnung und Unterscheidung von Kontakten. Einige Typen sind bereits standardmäßig in deinem plentymarkets System angelegt und können _nicht_ gelöscht werden. Diese Typen sind *Kunde*, *Handelsvertreter*, *Lieferant*, *Partner*, *Hersteller* und *Interessent*. Die erstellten Typen stehen im Menü *CRM » Kontakte* in der Dropdown-Liste *Typ* zur Verfügung.

[TIP]
.Tipp: Vorab Konzept für Typen und Klassen überlegen
====
Für die Einteilung deines Kundenstamms in Typen und Klassen ist es empfehlenswert, ein Konzept zu entwickeln, bevor du größere Mengen an Kontaktdaten erstellst. Dadurch vermeidest du späteren Änderungsaufwand, z.B. wenn Typen bei fehlender Einstellung automatisch zugewiesen werden. Überlege dir also am besten vorab, welche Typen und Klassen du benötigst, erstelle die Typen und Klassen und weise sie beim Erstellen deinen Kontakten zu.
====

Beim Erstellen eines neuen Kontaktdatensatzes ist automatisch der Typ *Kunde* als Standard eingestellt. Kund:innen des Typs *Lieferant* stehen als Lieferanten zur Verfügung, z.B. im Tab *Lieferant* einer Variante.

Gehe wie im Folgenden beschrieben vor, um eigene Typen zu erstellen.

[.instruction]
Typ erstellen:

. Öffne das Menü *Einrichtung » CRM » Typen*.
. Klicke auf *Typ hinzufügen* (material:add[role=green]).
. Gib einen Namen ein.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#tags-erstellen]
== Tags für Kontakte erstellen

Du hast die Möglichkeit, deinen Kontakten Tags zuzuordnen und nach diesen Tags auch in der Übersicht zu filtern. Tags sind Schlagworte, die du deinen Kontakten zuordnen kannst.

Welche Benutzer:innenrechte notwendig sind und wie du Tags erstellst, ist nachfolgend beschrieben.

[TIP]
.Tags für den Bereich Kontakte
====
Nur Tags, für die der Bereich *Kontakte* im Menü *Einrichtung » Einstellungen » Tags* aktiviert wurde, stehen am Kontakt und in der Kontaktsuche als Auswahl zur Verfügung.
====

[#rechte-tags]
=== Rechte für Backend-Benutzer:innen vergeben

include::_includes:page$tags-rights.adoc[]

[#tag-erstellen]
=== Tags erstellen

include::_includes:page$tags-creation.adoc[]

[#tag-suchen]
=== Tags suchen

include::_includes:page$tags-search.adoc[]

[#eigenschaften-einleitung]
== Eigenschaften erstellen

Eigenschaften sind wiederholt auftretende Informationen und können für die nähere Charakterisierung deiner Kontakte verwendet werden. Beispielsweise kannst du in jedem Kontaktdatensatz speichern, auf welchem Weg der Kontakt kontaktiert werden soll und ob er die Zusendung deines neuen Produktkatalogs wünscht.

Du kannst die meisten Eigenschaften auch auf deinen <<#eigenschaften-auf-dokumenten, Auftragsdokumenten>> anzeigen.

Außerdem hast du die Möglichkeit, <<#eigenschaften-gruppieren, Eigenschaftsgruppen>> zu erstellen, um so einen besseren Überblick zu behalten, wenn du mit sehr vielen Eigenschaften arbeitest.

Die folgenden Unterkapitel beschreiben, wie du Eigenschaften <<#eigenschaften-erstellen, erstellst>>, mit dem Kontakt <<#eigenschaften-verknuepfen, verknüpfst>>, <<#eigenschaften-suchen, suchst>> und <<#eigenschaften-loeschen, löschst>> und wie du Eigenschaften <<#eigenschaften-gruppieren, gruppierst>> sowie Eigenschaften <<#eigenschaften-importieren, importierst>> und <<#eigenschaften-exportieren, exportierst>>.

[#eigenschaften-erstellen]
=== Neue Eigenschaften erstellen

Eigenschaften erstellst du im Menü *Einrichtung » Einstellungen » Eigenschaften » Konfiguration*. <<#eigenschaften-verknuepfen, Verknüpfe>> die Eigenschaft anschließend mit dem Kontakt. Gehe wie im Folgenden beschrieben vor, um eine Eigenschaft zu erstellen.

include::_includes:page$neue-eigenschaften-erstellen.adoc[]

[#property-details]
==== Details

include::_includes:page$neue-eigenschaften-erstellen-details.adoc[tag=crm]

[#property-names]
==== Namen

include::_includes:page$neue-eigenschaften-erstellen-namen.adoc[tag=crm]

[#property-selection-values]
==== Auswahlwerte

[IMPORTANT]
.Nicht für jeden Eigenschaftstyp sichtbar
====
Diesen Bereich siehst du nur, wenn du mit einer Eigenschaft vom Typ *Auswahl* oder *Mehrfachauswahl* arbeitest.
Dieser Bereich ist für alle anderen Eigenschaftstypen unsichtbar.
====

include::_includes:page$neue-eigenschaften-erstellen-auswahlwerte.adoc[]

[#property-groups]
==== Gruppen

include::_includes:page$neue-eigenschaften-erstellen-gruppen.adoc[]

[#property-visibilities]
==== Sichtbarkeiten

include::_includes:page$neue-eigenschaften-erstellen-sichtbarkeiten.adoc[tag=crm]

[#property-options]
==== Optionen

include::_includes:page$neue-eigenschaften-erstellen-optionen.adoc[tag=crm]

[#eigenschaften-verknuepfen]
=== Eigenschaften mit dem Kontakt verknüpfen

Nachdem du die Eigenschaft im Menü *Einrichtung » Einstellungen » Eigenschaften » Konfiguration* erstellt hast, kannst du die Eigenschaft mit dem Kontakt verknüpfen. Gehe dazu wie im Folgenden beschrieben vor.

[.instruction]
Eigenschaft mit dem Kontakt verknüpfen:

. Öffne das Menü *CRM » Kontakte*.
. Suche den Kontakt anhand der Filtereinstellungen. Beachte dazu die Erläuterungen zu den Filtern auf der Seite xref:crm:kontakt-suchen.adoc#[Kontakt suchen]. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicke in die Zeile des Kontakts, um den Datensatz zu öffnen.
. Klicke auf der linken Seite auf *Eigenschaften*. +
→ Alle für den Kontakt verfügbaren Eigenschaften werden angezeigt und du kannst diese dort hinzufügen.

////
letzten Satz in der Konfig prüfen.
////

[#eigenschaften-auf-dokumenten]
=== Eigenschaften auf Dokumenten ausgeben

Du kannst die Kontakteigenschaften auf deinen xref:auftraege:auftragsdokumente.adoc#[Auftragsdokumenten], wie z.B. auf deinen Angeboten, ausgeben.

Die Vorlage erstellst du im Menü *Einrichtung » Mandant » [Mandant wählen] » Standorte » [Standort wählen] » Dokumente » [Dokument wählen]*. Dort siehst du im Bereich *Kundeneigenschaften* alle verfügbaren Eigenschaften, die du für den Bereich *Kontakt* erstellt hast.

Damit die Eigenschaft genau nach deinen Wünschen auf deinen Dokumenten ausgegeben wird, musst du die Eigenschaft im Textfeld rechts daneben umbenennen. Du könntest z.B. für den Eigenschaftstyp *Kurztext* den Text _Ansprechpartner Vertrieb_ und für den Eigenschaftstyp *Ganze Zahl* deine Telefonnummer für eventuelle Rückfragen eingeben.

*_Hinweis:_* Vergiss nicht im Feld darunter, die Koordinaten für die X- und Y-Achsen einzugeben, damit die Inhalte korrekt auf deinem Dokument positioniert werden. Weitere Informationen dazu findest du auf der Handbuchseite xref:auftraege:auftragsdokumente.adoc#600[Auftragsdokumente].

[TIP]
.Positionierung der Eigenschaften auf dem Dokument prüfen
====
Ob du alle Eigenschaften korrekt und nach deinen Wünschen positioniert hast, kannst du ganz einfach prüfen:

* Öffne den Kontaktdatensatz im Menü *CRM » Kontakte*.
* Klicke auf der linken Seite auf *Aufträge*. +
→ Der Auftrag wird im Menü *Aufträge » Aufträge bearbeiten* geöffnet.
* Klicke im Auftrag auf das Tab *Belege*.
* Wähle das Dokument, für das du die Kundeneigenschaften in der Dokumentenvorlage eingerichtet hast, z.B. _Angebot_, aus der Dropdown-Liste. +
→ Die Vorlage wird geöffnet.
* Prüfe die korrekte Positionierung der Kundeneigenschaften auf dem Dokument.
====

[#eigenschaften-gruppieren]
=== Eigenschaften gruppieren

Wenn du viele Eigenschaften hast, dann kannst du sie gruppieren und somit leichter den Überblick in deinem plentymarkets Backend behalten.

[#neue-gruppe-erstellen]
==== Neue Gruppe erstellen

:crm:
include::_includes:page$neue-gruppe-erstellen.adoc[]

:!crm:

[#mit-eigenschaften-arbeiten]
=== Mit bestehenden Eigenschaften arbeiten

[#eigenschaften-suchen]
==== Eigenschaften suchen

include::_includes:page$eigenschaften-suchen.adoc[]

[#eigenschaften-importieren]
==== Eigenschaften importieren

Mit dem Import-Tool und dem Import-Typ *Eigenschaften* kannst du Eigenschaften in dein plentymarkets System importieren. Welche Felder du für den Abgleich und die Zuordnung verwenden kannst, ist auf der Handbuchseite des Import-Typs xref:daten:elasticSync-eigenschaften.adoc#[Eigenschaften] beschrieben.

Allgemeine Informationen zum Importieren von Daten in dein plentymarkets System findest du auf der Handbuchseite xref:daten:ElasticSync.adoc#[Import-Tool nutzen].

[#eigenschaften-exportieren]
==== Eigenschaften exportieren

:crm:
include::_includes:page$eigenschaften-exportieren.adoc[]

:!crm:

[#eigenschaften-loeschen]
==== Eigenschaften wieder löschen

include::_includes:page$eigenschaften-loeschen.adoc[]

[#rabattsystem-nutzen]
== Rabattsystem nutzen (optional)

[TIP]
.Einrichten des Rabattsystems ist optional
====
Das Einrichten des Rabattsystems in plentymarkets ist optional. Lies dir die Möglichkeiten zur Rabattierung in den folgenden Unterkapiteln durch und entscheide dann, ob du Rabattierungen, beispielsweise über die Kundenklassen, erlauben möchtest.
====

In plentymarkets hast du mehrere Möglichkeiten der Rabattierung. Du kannst deinen Kontakten einen <<#kundenklassenrabatt, Kundenklassenrabatt>>, einen <<#rabatt-zahlungsart, Rabatt auf die Zahlungsart>> sowie eine <<#rabbatstaffel-nettowarenwert, Rabattstaffel auf den Nettowarenwert einer Bestellung>> gewähren. Außerdem kannst du <<#rabatt-verkaufspreis, Verkaufspreise als Rabatte>> speichern und <<rabatt-manuell, manuelle Rabatte>> eingeben. Nimm die gewünschten Einstellungen für die Rabattarten im Menü *Einrichtung » CRM » Kundenklassen* vor. Wie du die Rabatte gewährst, ist in den folgenden Unterkapiteln beschrieben.

[#kundenklassenrabatt]
=== Kundenklassenrabatt einrichten

In einer Kundenklasse legst du Rabatte fest, die dann nur für diese Kundenklasse wirksam werden. Darüber hinaus bestehen hier weitere Einstellungsmöglichkeiten, z.B. das Aktivieren von Mengenrabatten der Verkaufspreise. Beachte dabei, dass sich je nach Einstellung Rabatte addieren können.

Gehe wie im Folgenden beschrieben vor, um einen Rabatt für Kundenklassen einzugeben.

[.instruction]
Kundenklassenrabatt einrichten:

. Öffne das Menü *Einrichtung » CRM » Kundenklassen*.
. Klappe die Kundenklasse, für die der Rabatt gelten soll, auf (icon:plus-square-o[]).
. Aktiviere unter *Rabattart* die Option *Kundenklassenrabatt*. +
→ Eine weitere Einstellung wird geöffnet.
. Gib unter *Rabatt in %* den Prozentwert für den Rabattabzug ein.
. Wähle, ob der *Mengenrabatt* berücksichtigt werden soll.
. Wähle, welche der im plentyShop verfügbaren Zahlungsarten für die Kundenklasse erlaubt sein sollen.
. Gib einen Zahlungshinweis ein. +
→ Dieser Zahlungshinweis wird auf Einzelrechnungen angezeigt.
. Wähle, ob die Preise im plentyShop *brutto* (inklusive Mehrwertsteuer) oder *netto* (exklusive Mehrwertsteuer) angezeigt werden sollen.
. *Speichere* (material:save[]) die Einstellungen.

[#rabbatstaffel-nettowarenwert]
=== Rabattstaffel auf Nettowarenwert einrichten

Möchtest du deine Kontakte mit Rabatten belohnen, wenn diese häufig und umsatzsteigernd in deinem plentyShop einkaufen? Dann kannst du hier Rabattwerte auf den Nettowarenwert des Auftrages festlegen.

[.instruction]
Rabattstaffel auf Nettowarenwert einrichten:

. Öffne das Menü *Einrichtung » CRM » Kundenklassen*.
. Klappe die Kundenklasse, für die die Rabattstaffel gelten soll, auf (icon:plus-square-o[]).
. Aktiviere unter *Rabattart* die Option *Rabattstaffel auf Nettowarenwert*. +
→ Eine Tabelle mit weiteren Einstellungen wird geöffnet.
. Gib unter *ab Nettowarenwert* die Betragsangaben aufsteigend ein.
. Gib unter *Rabatt in %* die Prozentwerte für den Rabattabzug aufsteigend ein. +
→ Wenn du z.B. im Feld *ab Nettowarenwert* 50 eingibst und im Feld *Rabatt in %* 2 eingibst, werden ab 50 Euro 2% Rabatt gewährt.
. Wähle, ob der *Mengenrabatt* berücksichtigt werden soll.
. Wähle, welche der im plentyShop verfügbaren Zahlungsarten für die Kundenklasse erlaubt sein sollen.
. Gib einen Zahlungshinweis ein. +
→ Dieser Zahlungshinweis wird auf Einzelrechnungen angezeigt.
. Wähle, ob die Preise im plentyShop *brutto* (inklusive Mehrwertsteuer) oder *netto* (exklusive Mehrwertsteuer) angezeigt werden sollen.
. *Speichere* (material:save[]) die Einstellungen.

[discrete]
==== Wie sehen deine Kund:innen den Rabatt in deinem plentyShop?

Der Rabatt wird berechnet und angezeigt, wenn der Kontakt seinen Einkauf beendet und zur Kasse geht. Im Warenkorb wird zunächst nur der gesamte Rabattbetrag ausgewiesen. Wenn der Kontakt die Bestellung abschließt, wird zusätzlich zum Gesamtrabatt der Rabatt auf die einzelnen Artikelpositionen berechnet und angezeigt.

[#rabatt-zahlungsart]
=== Rabatt auf Zahlungsart einrichten

Mit der Rabattart *Rabatt auf Zahlungsart* gewährst du deinen Kontakten einen Rabatt auf die Verwendung einer oder mehrerer Zahlungsarten.

[TIP]
.Rabatt auf Zahlungsart direkt hinterlegen
====
Alternativ zu der Einstellung, die du in diesem Menü vornimmst, ist es möglich, direkt bei einer Zahlungsart einen globalen Rabatt für diese Zahlungsart zu hinterlegen. Ein Beispiel ist ein prozentualer Rabatt bei der Zahlungsart *Vorkasse*. Beachte dazu die Handbuchseite xref:payment:zahlungsarten-verwalten.adoc#[Zahlungsarten verwalten]. Die Einstellung direkt bei der Zahlungsart erlaubt jedoch keine detaillierteren Einstellungen als bei der Option *Rabatt auf Zahlungsart* im Menü *Einrichtung » CRM » Kundenklassen*.
====

Gehe wie im Folgenden beschrieben vor, um einen Rabatt auf eine oder mehrere Zahlungsarten einzurichten.

[.instruction]
Rabatt auf Zahlungsart einrichten:

. Öffne das Menü *Einrichtung » CRM » Kundenklassen*.
. Klappe die Kundenklasse, für die der Rabatt gelten soll, auf (icon:plus-square-o[]).
. Gib ein *Zahlungsziel* in Tagen ein, das du dieser Kundenklasse einräumen möchtest.
. Aktiviere unter *Rabattart* die Option *Rabatt auf Zahlungsart*. +
→ Eine Tabelle mit weiteren Einstellungen wird geöffnet.
. Wähle eine oder mehrere Zahlungsarten, für die der Rabatt gelten soll.
. Gib unter *Rabatt in %* den Prozentwert für den Rabattabzug ein.
. Wähle, ob der *Mengenrabatt* berücksichtigt werden soll.
. Wähle, welche der im Webshop verfügbaren Zahlungsarten für die Kundenklasse erlaubt sein sollen.
. Gib einen Zahlungshinweis ein. +
→ Dieser Zahlungshinweis wird auf Einzelrechnungen angezeigt.
. Wähle, ob die Preise im Webshop *brutto* (inklusive Mehrwertsteuer) oder *netto* (exklusive Mehrwertsteuer) angezeigt werden sollen.
. *Speichere* (material:save[]) die Einstellungen.

[#rabatt-verkaufspreis]
=== Verkaufspreis als Rabatt speichern

Ein mengenbezogener Rabatt wird im Menü *Einrichtung » Artikel » Verkaufspreise* als eigener Preis angelegt. Dort legst du mit der Option *Ab Menge* im Bereich *Einstellungen* für den Verkaufspreis fest, ab welcher Artikelmenge der rabattierte Preis gelten soll. Eine Staffelung realisierst du durch das Erstellen entsprechender Verkaufspreise mit den gewünschten Mindestmengen.

Der rabattierte Verkaufspreis wird aktiviert, wenn du in der Kundenklasse die Option *Mengenrabatt* auf *Berücksichtigen* setzt. Ein Kontakt erhält den Rabatt, wenn der Kontakt erstens zu der betreffenden Kundenklasse gehört und zweitens mindestens die beim Verkaufspreis gespeicherte Menge bestellt.

[.instruction]
Verkaufspreis als Rabatt speichern:

. Öffne das Menü *Einrichtung » Artikel » Verkaufspreise*.
. Öffne den Verkaufspreis.
. Gib im Tab *Einstellungen* im Feld *Ab Menge* eine Ziffer ein, ab welcher Artikelmenge der rabattierte Preis gelten soll.
. Aktiviere im Bereich *Klasse* die Kundenklassen, für die der Verkaufspreis gelten soll.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

Weitere Informationen zu Verkaufspreisen findest du auf der Handbuchseite xref:artikel:preise.adoc#100[Verkaufspreise und Preiskalkulation].

[#rabatt-manuell]
=== Manuellen Rabatt eingeben

Zusätzlich zur Vergabe von automatischen Rabatten hast du die Möglichkeit, einzelnen oder allen Artikelpositionen eines Auftrags manuell einen Rabatt zuzuweisen. Du kannst manuelle Rabatte in 2 verschiedenen Ansichten eingeben: in der Listenansicht der xref:auftraege:auftraege-verwalten.adoc#1300[Auftragssuche] und im Bearbeitungsfenster eines xref:auftraege:auftraege-verwalten.adoc#1530[Auftrags].

[#rabatt-einzelner-artikel-auftragssuche]
==== Rabatt für einzelnen Artikel in der Auftragssuche eingeben

Wenn du schnell einzelnen Artikelpositionen eines Auftrags einen Rabatt zuweisen oder den Rabattwert ändern möchtest, kannst du dies direkt in der Auftragssuche tun. Gehe wie im Folgenden beschrieben vor, um einen Rabatt für einzelne Artikel in der Auftragssuche einzugeben oder zu ändern.

[.instruction]
Rabatt für einzelnen Artikel in der Auftragssuche eingeben:

. Öffne das Menü *Aufträge » Aufträge bearbeiten*. +
→ Die Auftragssuche wird angezeigt.
. Klicke rechts in der Ansicht eines Auftrags auf *Rabatt* (Standard:{nbsp}0%). +
→ Ein Fenster zur Eingabe des Prozentsatzes wird geöffnet.
. Gib den als Rabatt gewünschten Prozentsatz ein.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Der Rabattwert wird angezeigt und der Rabatt wird von der Artikelposition abgezogen.

[#rabatt-einzelner-artikel-auftrag]
==== Rabatt für einzelnen Artikel im Auftrag eingeben

In der Auftragsübersicht werden ganz unten die Artikelpositionen angezeigt. Auch hier hast du die Möglichkeit, einzelnen Artikelpositionen einen Rabattwert zuzuweisen oder den Rabattwert zu ändern. Gehe wie im Folgenden beschrieben vor, um einen Rabatt für einen Artikel im Auftrag einzugeben oder zu ändern.

[.instruction]
Rabatt für einzelnen Artikel im Auftrag eingeben:

. Öffne das Menü *Aufträge » Aufträge bearbeiten*.
. Öffne den Auftrag, auf den ein Rabatt gewährt werden soll, mit einem Klick auf die Auftragsnummer.
. Öffne im Tab *Übersicht* des Auftrags im unteren Bereich das Tab *Bearbeiten* (icon:pencil[]).
. Wähle aus der Dropdown-Liste *Rabatt* den Rabattsatz.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#rabatt-alle-artikel-im-auftrag]
==== Rabatt für alle Artikel eines Auftrags eingeben

Gehe wie im Folgenden beschrieben vor, um einen Rabatt für alle Artikelpositionen eines Auftrags einzugeben bzw. zu ändern.

[.instruction]
Rabatt für alle Artikel eines Auftrags eingeben:

. Öffne das Menü *Aufträge » Aufträge bearbeiten*.
. Öffne den Auftrag, auf den ein Rabatt gewährt werden soll, mit einem Klick auf die Auftragsnummer.
. Öffne im Tab *Übersicht* des Auftrags im unteren Bereich das Tab *Bearbeiten* (icon:pencil[]).
. Klicke unterhalb der Liste der Artikelpositionen auf den Link *Rabatt für alle Artikel vergeben*.
. Wähle aus der angezeigten Dropdown-Liste den Rabattsatz.
. Klicke rechts neben der Dropdown-Liste auf *Speichern*.
. *Speichere* (icon:save[role="green"]) die Einstellungen.
