= Automation
:author: team-docs-automation
:description: Learn how to automate your daily tasks by using the procedure manager or via event procedures and processes.

Automate your daily tasks! plentymarkets includes three different tools that help you automate your routine business processes.

Learn about the three different tools in a playful introduction:

.Automate your day-to-day tasks
video::198165819[vimeo]

== Procedure manager

In plentymarkets, you can use the xref:automation:procedure-manager.adoc#[procedure manager] to automatically complete routine tasks at a specific time every day.

For example, you can xref:automation:best-practices-automation.adoc#_practical_examples_procedure_manager[use the procedure manager] to set a time each day when non-paying eBay or store customers should receive a payment reminder or dunning letter. The reminder will then be automatically sent by email.

== Event procedures

xref:automation:event-procedures.adoc#[Event procedures] are easy to understand: specific *_events_* in your online store trigger specific *_procedures_*.

For example, you can xref:automation:best-practices-automation.adoc#_practical_examples_event_procedures[use event procedures] to send emails to your customers. Use event procedures to configure such automatic tasks and have plentymarkets complete them reliably.

== Prozesse

Use xref:automation:setting-up-processes.adoc#[processes] to automate complex tasks in plentymarkets.

For example, you can use processes to pick and pack items in your warehouse.
