= Running processes
:lang: en
:author: team-mobile
:keywords: Run processes, start process, trigger process, execute process
:position: 20
:url: automation/processes/carrying-out-processes
:id: OM8HCEJ

[IMPORTANT]
.Install plentyBase
====
You need xref:automation:installing-plentybase.adoc#[plentyBase] to create and run processes in the plentymarkets back end. You can download the installation files for plentyBase in the link:https://marketplace.plentymarkets.com/en/plugins/integration/plentyBase_5053[plentyMarketplace^]{nbsp}icon:external-link[].
====

Once you’ve finished creating a process under xref:automation:setting-up-processes.adoc#[Setup » Processes], you’ll be able to run it in the *Processes* menu.

[#10]
== Running a process

Proceed as described below to run a process. Note that you can only see those processes that have been assigned to your user account or that have been assigned to your role.

[discrete]
=== Assigning rights for back end users

:rights-purpose: see and run processes
:right-one: pass:quotes[*Processes > Edit*]
:right-two: pass:quotes[*Processes > Show*]

include::_includes:page$rights.adoc[]

[.instruction]
Running a process:

. Open the *Processes* menu. +
→ The available processes are displayed.
. Click on a process. +
→ The process is displayed and it has the status *Waiting*.
. Click on Start. +
→ The process starts. +
→ Bars in the *Work steps* tab show the progress of the individual process steps. +
→ Depending on the process, input may be required from the user.
