= Managing printers
:keywords: plentyBase printer, printer settings, print history, printer problem, print order, test print, print test
:author: team-docs-automation
:description: Learn how to add, set up and share printers. Moreover, find out how to print labels and fix errors.

You can set up local installed printers or network printers in plentymarkets in the *Setup » Settings » Printer* menu.

[IMPORTANT]
.Requirement: plentyBase
====
The tool link:https://marketplace.plentymarkets.com/en/plentybase_5053[plentyBase^] needs to be installed and running on your computer to connect plentymarkets with locally installed devices.
The *Setup » Settings » Printer* menu is only visible in the back end of your plentymarkets system once plentyBase is installed and running.
====

[#10]
== Adding a printer

Proceed as described below to add a printer.

[.instruction]
Adding a printer:

. Go to *Setup » Settings » Printer*. +
*_Note:_* The menu is only visible if link:https://marketplace.plentymarkets.com/en/plentybase_5053[plentyBase^] is installed and running on your computer. If the menu is still not visible, check if an update for plentyBase is available.
. Click on the menu entry Printer. +
→ The *New printer* button is displayed.
. Click on *New printer*. +
→ The settings menu opens.
. Carry out the settings. Pay attention to the explanations given in <<table-add-base-printer>>.
. *Save* the settings. +
→ The printer is displayed in the menu tree.
. Print a few test pages or labels and experiment with different printer plugins before using printers in productive mode.

[[table-add-base-printer]]
.Printer settings
[cols="1,3"]
|====
|Setting |Explanation

| *Test page*
|Prints out a test page for checking the printer settings.

| *Name*
|Enter a name. You can select any name you like. This way, you can add several printers of the same types and assign different names to each one.

| *Printer*
|Displays printers that are available locally or within the network.

| *Printer dialogue*
|Select if the printer dialogue should open before printing a page or not. +
*open* = Layout and additional settings have to be carried out before each printing process. +
*do not open* = Layout and additional settings are specified in this menu and will be used for every printing process.

| *Paper tray*
|Select a paper tray. The available options depend on the printer that you have selected.  +
*_Note_*: This option is only available for Windows. +
To set up different paper sizes, please refer to the following sub-chapter.  +

| *Paper size*
|Select a paper size. The paper formats are provided by your printer, so the options that are displayed may vary. +
If you select a user-defined paper size, for example *Custom*, further input fields for *width* and *height* are displayed. +
If you need additional formats, set up further printers and assign the different formats to those printers.

| *Double-sided printing*
|Double-sided printing is currently not possible.

| *Scaling*
|Select the scaling.  +
*Fit to page (ignore aspect ratio)* = Information will be scaled to fit the entire page. This setting may cause the print result to be distorted.  +
*Fit to page (preserve aspect ratio)* = Information will be scaled to the largest possible size within the print area without causing distortion.  +
*None* = Information will not be scaled.

| *Orientation*
|Select which orientation should be used when printing. The available options are provided by your printer, so the options that are displayed may vary.  +
*portrait* = Vertical format  +
*landscape* = Horizontal format  +
*_Tip:_* Select the option *Automatic page orientation* to automatically adjust the content to fit the page orientation.

| *Top, Left, Bottom, Right*
|Optionally, enter distances in mm to determine how the content will be positioned on the page.

| *Automatic page orientation*
|Activate this option to automatically adjust the content to fit the page orientation.

| *Printer plugin*
|Select the plugin that should be used with the printer. +
*_Tip:_* Print some test pages or labels to test the print quality of the different printer plugins. +
*Default* = The default for the operating system is used. +
*Cups*; *PDFBox* = Try one of these options if the print quality using the option *Default* is not appropriate. +
*ZPL* (Zebra Programming Language) = Select this option if you are using a Zebra label printer. +
*_Note on the ZPL plugin:_* The ZPL plugin has been optimised for a native resolution of 203 dpi. In case of other resolutions, the size of the labels may vary. If you label sizes are distorted, select the option *203 dpi* or use a different printer plugin. +
*_Note on the ZPL plugin:_* For optimum print quality with the ZPL plugin on MacOSx, the printer has to be integrated via the CUPS web interface in xref:automation:printer.adoc#65[RAW mode].
|====

[#20]
== Setting up printers with multiple paper trays (Windows only)

If you own a printer with multiple paper trays and want to work with different paper sizes, you can set up a separate printer profile for each paper tray.

[TIP]
.Example configuration for different formats
====
Do you want to print invoices in DIN A4 format and labels in DIN A6 format?

Set up a printer profile for the paper size DIN A4 and another printer profile for the paper size DIN A6. Select the same printer for both profiles and assign the corresponding paper tray to each paper size.
====

[#30]
== Sharing printers

Printer profiles are saved on the local computer for each individual user account. Thus, printer profiles are not available for other users who work on the same computer. If a printer profile should be available for other users as well, the profile must be shared with others. Profiles are shared on your computer, not in plentymarkets. Use your operating system's help function to find out how to share printers on your computer:

* Help for Windows e.g. link:http://windows.microsoft.com/en-us/windows/share-printer#1TC=windows-7[here^]
* Help for Mac e.g. link:https://support.apple.com/en-gb/HT204135[here^]

[#40]
== Error causes and solutions

<<table-error-message-menu-printer>> contains information on error codes that may occur when setting up the printer.

[[table-error-message-menu-printer]]
.Error messages in the *Printer* menu
[cols="1,3,3,3"]
|====
|Code |Error |Cause |Solution

|2000
|Under Mac OS X: No CUPS printer found.
|No printer is shared in the network. It is necessary to share a printer in order for printers to communicate via CUPS.
|xref:automation:printer.adoc#30[Sharing printers]

|2001
|Unter Mac OS X: Unknown CUPS printer.
|The printer was not found in the network under the specified name.
|xref:automation:printer.adoc#30[Sharing printers]

|2101
|Print error.
|Several possible causes.
|

|2102
|Printer was not found.
|The printer is no longer available in the system or the configuration is not correct any more.
|Add a new printer or use a different printer.
|====

[#50]
== Printing labels

Using special label printers, you can print large numbers of labels in no time. These printers are equipped with label reels. Some models also have an integrated cutter. Select the exact label size using the *Paper size* option in the *Setup » Settings » Printer* menu. You can either select one of the default formats or define your own sizes using the custom option. For further information, refer to <<table-add-base-printer>>.

All printing functions are compatible with label printers and are especially optimised for using label printers produced by link:https://www.zebra.com/gb/en.html[Zebra^]. For use as a desktop printer, we recommend the model link:https://www.zebra.com/gb/en/products/printers/desktop/value-desktop-printers.html[Zebra GC420d^].

[#60]
=== Installing the Zebra GC420d on your computer

//TODO: Dieses Druckermodell wird nicht mehr produziert, der Support läuft im März 2023 aus. Kapitel dann entweder entfernen oder, wenn Zeit ist, ein aktuelleres Beispiel beschreiben.

Proceed as described below to install the Zebra GC420d on the operating systems Windows or Mac OSX.

[.instruction]
Installing the Zebra GC420d:

. First, download the link:https://www.zebra.com/gb/en/support-downloads/desktop/gx430t.html#mainpartabscontainer_999b=drivers[Zebra Setup Utilities^] file to your computer.
. Install the file.
. Follow the instructions in the setup wizard. +
→ Windows: Select the ZDesigner GC420d printer. Here, the ZPL printer driver is used by default. +
→ Mac OSX: Select the printer driver ZPL. Test the driver's setting individually for every label size. To use the *ZPL* printer plugin, configure your Zebra printer for xref:automation:printer.adoc#65[RAW printing].

[#65]
=== Setting up a Zebra printer with the ZPL plugin (Mac OSX only)

To optimise print quality with the ZPL plugin on Mac OSX systems, you need to enable the Zebra printer so that it can receive print jobs in RAW format. When printing in RAW format, print data is sent in the printer's native language. The print data remains unchanged because the operating system's print driver is bypassed.

To set up RAW printing, you need to access the CUPS web interface. Proceed as described below to activate the CUPS web interface and configure the printer.

[.instruction]
ZPL plugin: Activating the CUPS web interface (Mac OSX only):

. Open the Spotlight search by pressing "cmd" \+ “space”.
. Enter the term *Terminal*.
. Press enter. +
→ The terminal opens.
. In the terminal window, enter the command *sudo cupsctl WebInterface=yes*.
. Press enter. +
→ You are asked to enter your password.
. Enter your password. +
→ The CUPS web interface is activated.

[.instruction]
ZPL plugin: Setting up Raw printing for a Zebra printer (Mac OSX only):

. In a web browser, navigate to *http://localhost:631*. +
→ The CUPS web interface is displayed.
. Switch to the *Administration* tab.
. Click on *Add Printer*. +
→ You are asked to enter your login details.
. Enter your user name and password. +
→ The *Add Printer* page is displayed.
. Select the Zebra printer from the list.
. Click on *Continue*.
. Enter a name, a description and a location for the printer.
. Select *Share This Printer* to share the printer with other users.
. Click on *Continue*.
. From the *Make* list, select the option *Raw*.
. Click on *Continue*.
. Click on *Add Printer*.
. Leave the settings for *Starting Banner* and *Ending Banner* at *none*.
. Click on *Set Default Options*. +
→ Your Zebra printer can receive RAW print jobs. +
*_Note:_* The Zebra printer is not shown in the system settings. However, it is set up and can be accessed by the system.
. In the *Setup » Settings » Printer* menu, select the printer plugin *ZPL* to add the printer.

[#70]
=== Setting up label printing

Determine the height and width of your labels in plentymarkets. First, add the label printer to your printer list. Proceed as described below. The settings are described based on the example label format of 104 x 150.

[.instruction]
Adding a printer for 104 x 150 labels:

. Go to *Setup » Settings » Printer*.
. Click on the context menu in the menu structure. +
→ The *New printer* button is displayed.
. Click on *New printer*. +
→ The settings menu opens.
. Enter a name.
. Select the label printer from the drop-down list *Printer*.
. Select *do not open** for the *Printer dialogue*.
. Select *Invalid selection* for the *Paper tray*.
. Select *Custom* for the *Paper size*.
. Enter *150* as the *Paper height*.
. Enter *104* as the *Paper width*.
. Do not change the one-sided setting for double-sided printing.
. Select *Fit to page (ignore aspect ratio)* for the *Scaling*.
. Select *portrait* for the *Orientation*.
. *Save* the settings.

[TIP]
.Tip for multiple label sizes
====
If you use different label sizes, you can either change the paper height and width in the printer dialogue when changing the label or set up an individual printer for each label size.
====

[#80]
=== Correcting label printing errors

If the printing results are slightly offset, but visible on the label, we recommend that you correct the printing position using the *Top*, *Left*, *Bottom* and *Right* fields.

If only a small part of the information is printed and the rest of the label is empty, change the printer's driver. Using the right driver is crucial for printing correctly. This is especially true for Apple computers, but it can also be a cause of errors for Windows computers.  +
For Windows, we recommend that you install the printer ZDesigner GC420d and the driver ZPL. In some cases, you may obtain better results using the printer ZDesigner GC420d (EPL) and the EPL driver.

If you were able to correct the printing results, add a printer with the right settings for the label. This way, you can reuse the settings. We recommend installing the same printer multiple times using different drivers, so that you can switch to another configuration quickly if the labels are not printed correctly.

Incorrect printing results may also occur if the process uses the label parameters of your label printer instead of the label settings in plentymarkets. In this case, it may help to add the label parameters in your printer settings.

In plentymarkets, you can also select different printer plugins. If the print quality is not satisfactory, experiment by printing test labels with different printer plugins.

[#90]
== Managing print jobs

The print history displays your print jobs that have been started from your local computer during the past 14 days.

=== Displaying the print history

[.instruction]
Displaying the print history:

. Go to *Data » Print history*. +
→ The print history opens. +
*_Note:_* The print history is saved locally. If no documents have been printed using the local computer yet, the print history is empty. +
*_Tip:_* 25 entries are displayed by default. You can change the number of entries that are displayed via the drop-down list. +
*_Note:_* Print jobs are stored temporarily in order to forward them to the printer. As soon as a print job has been saved temporarily, it is listed in the print history. This also means that print jobs that were not actually completed may be listed in the print history.

=== Reprinting documents

You can reprint the documents that are displayed in the print history. To do so, proceed as described below.

[.instruction]
Reprinting documents:

. Go to *Data » Print history*. +
→ The print history opens.
. Activate the checkboxes for the documents that should be reprinted.
. Click on *Print again*. +
→ The documents are printed.

=== Manually deleting documents from the print history

The print history displays the print jobs from the past 14 days. After 14 days, print jobs are automatically removed from the print history. Proceed as described below to manually remove documents from the print history.

[.instruction]
Manually deleting documents from the print history:

. Go to *Data » Print history*. +
→ The print history opens.
. *Delete* the documents. +
→ The documents are deleted.

[#100]
== Deleting a printer configuration

Proceed as described below to delete a printer configuration.

[.instruction]
Deleting a printer configuration:

. Go to *Setup » Settings » Printer*.
. Click on the printer. +
The settings menu opens.
. Click on *Delete*. +
→ The printer configuration is deleted.
