= Processes
:keywords: Processes overview
:author: team-docs-automation
:description: Learn why you should use processes and how you set them up.

[#100]
== Why you should use processes

Similar to xref:automation:event-procedures.adoc#[event procedures], processes help you to automate complex workflows in your plentymarkets system. However, processes allow you to automatically print order documents or shipping labels and, depending on the workflow at hand, include user dialogues including different options. To use the processes, the tool link:https://marketplace.plentymarkets.com/en/plugins/externe-tools/plentyBase_5053/[plentyBase^] has to be installed and running on your local computer.

[#200]
== How are processes set up?

As soon as you have installed and started link:https://marketplace.plentymarkets.com/en/plugins/externe-tools/plentyBase_5053/[plentyBase^] on your local computer, you are ready to go.

Go to *Setup » Processes » New process* to set up a new process. Refer to the xref:automation:setting-up-processes.adoc#[Setting up processes] page of the manual for more information on how to set up processes.

You can access and run the processes you have already set up any time. Click on *Processes* in the upper menu bar of the plentymarkets back end to do so. The manual page on xref:automation:carrying-out-processes.adoc#[running processes] describes the necessary steps to run processes.

Also note our link:https://www.youtube.com/watch?v=p5NF6rLr7ho[Deep Dive^] (from 03:52:00, German only). It shows you how to set up several processes for your shipping and fulfillment procedures. Refer to our link:https://forum.plentymarkets.com/t/plentymarkets-deep-dive-beispiel-prozesse/584693[forum^] to download the sample processes shown in the video (German only).


[#300]
== Which functions are available?

Processes provide you with a variety of different settings and options. These are represented by 3 different types of settings that you can use within the processes:

* xref:automation:work-steps.adoc#[Work steps]
* xref:automation:procedures.adoc#[Procedures/Control elements]
* xref:automation:sub-procedures.adoc#[Sub-procedures]

[#400]
== Do you need help?

Just like the workflows within your business, processes and their functions can be quite complex. On xref:automation:faq.adoc#[this manual page], you can find a list of the most common errors as well as tips on how to deal with them. In case of further questions or problems, we are always happy to assist you in our link:https://forum.plentymarkets.com/c/prozesse[forum category^].
