= Cash on delivery
:lang: en
include::{includedir}/_header.adoc[]
:keywords: payment method, payment plugin, cash on delivery, cash-on-delivery, payment integration, paying after delivery
:description: Integration of the plugin cash on delivery.
:position: 20
:url: payment/payment-plugins/cash-on-delivery
:id: 3VRD6B6
:author: team-order-payment

With the Cash on delivery plugin, you integrate the payment method Cash on delivery in your online shop and make it available to your customers. You can find the plugin in the link:https://marketplace.plentymarkets.com/en/plugins/payment/cashondelivery_5255[plentyMarketplace^]{nbsp}icon:external-link[]. You also have to carry out a few basic settings in your plentymarkets system so that the payment methods are activated in your system. +
The explanations in this section apply after adding the plugin. You can find more information on adding and installing plugins in the <<plugins#, Plugins>> section of the manual.

[IMPORTANT]
.Requirement
====
The plugin requires Ceres and IO in version 2.0.3 or higher.
====

[#10]
== Activating the payment method in a shipping profile

The payment method Cash in delivery is activated in the <<fulfilment/preparing-the-shipment#1000, shipping profiles>>. If at least one active and valid shipping profile has the option *Cash on delivery*, the payment method is displayed in the checkout and can be selected by your customers.

[.instruction]
Activation of the option *Cash on delivery* in shipping profile:

. Go to *Setup » Orders » Shipping » Settings*.
. Change into the *Shipping profiles* tab.
. Open the required shipping profile.
. Activate (icon:check-square[role="blue"]) the option *Cash on delivery*. +
→ Cash on delivery is displayed in the order process.

[#30]
== Allowing the payment method for customer classes

Make sure that the payment method is allowed in the <<crm/managing-contacts#15, customer classes>> For this, you should consider first for which customer classes the payment method should be allowed. This can be set individually.

[.instruction]
Permitting the payment method in a customer class:

. Go to *Setup » CRM » Classes*.
. Open the customer class for which you want to permit the payment method.
. Select the payment method from the list *Permitted payment methods* by clicking on it.
. *Save* (icon:save[role="green"]) the settings.

If needed, repeat these steps for other customer classes as well.

[#40]
== Displaying payment details in the online shop

The template plugin Ceres offers to have the name and logo of a payment method displayed during the order process. Proceed as follows to have the name and logo of the payment method displayed.

[.instruction]
Setting up details of the payment method:

. Go to *Plugins » Plugin set overview » [select Plugin set]*.
. Open the plugin *Cash on delivery*.
. Open the *Configuration » Settings* menu.
. Enter the name that should be displayed for the payment method in the online shop in the field *Name*.
. Enter a URL for the image of the logo in the field *logo URL*. Valid data formats are .gif, .jpg or .png. The maximum size of the image is 190 px width and 60 px height.
. Save (icon:save[role="green"]) the settings. +
→  Name and logo of the payment method are displayed in the order process of the online shop.

[#50]
== Editing text elements

You can edit texts of the plugin in the *CMS » Multilingualism* menu. The texts can be adapted into all available system languages. To do so, proceed as described below.

[.instruction]
Adapting language files:

. Go to *CMS » Multilingualism*.
. On the left side, select the *Source language* from the drop-down list.
. On the right side, select the *Target language* from the drop-down list.
. Expand the section *error messages* in the *CashOnDelivery* area.
. Enter the text for the individual text elements in the area of the target language.
. Save (icon:save[role="green"]) the settings.
. Deploy the plugin set again to apply these changes.

By selecting *German* as the *Target language*, you can adapt the German labels for your online shop. The selected labels are then also applied in the back end, only the addition _Plugin_ remains. This way, it remains traceable where a payment method comes from. Reload the back end to see the changes.
Find more information on how to edit online shop texts on the manual page <<online-store/setting-up-ceres#231, Editing online store texts>>.
