= Invoice
:keywords: payment plugin, payment method, invoice, invoice-plugin, payment-integration, payment-plugin, invoice assistant, invoice-assistant
:description: Learn more about the integration of the Invoice plugin.
:author: team-fulfillment-payment

With the Invoice plugin, you integrate the payment method *Invoice* in your online shop and make it available to your customers. To do so, download the Invoice plugin from the link:https://marketplace.plentymarkets.com/en/invoice_4760[plentyMarketplace^]. Setup of the payment method is done with an assistant. You also have to carry out a few basic settings in your plentymarkets system so that the payment method is activated in your system. +
The explanations in this section apply after adding the plugin. You can find more information on adding and installing plugins in the xref:plugins:plugins.adoc#[Plugins] section of the manual.

[#10]
== Completing the assistant

:name-assistant: Invoice
:name-payment-method: Invoice

include::_includes:partial$completing-assistant-payment-method.adoc[]

[#30]
== Customer classes and shipping profiles

include::_includes:page$customer-class-and-shipping-profile.adoc[]

[#40]
== Editing text elements

You can edit texts of the plugin in the *CMS » Multilingualism* menu. The texts can be adapted into all available system languages. To do so, proceed as described below.

[.instruction]
Adapting language files:

. Go to *CMS » Multilingualism*.
. On the left side, select the *Source language* from the drop-down list.
. On the right side, select the *Target language* from the drop-down list.
. Expand the sections *bank data*, *designated use* and *payment method* in the *Invoice* area.
. Enter the text for the individual text elements in the area of the target language.
. Save (material:save[]) the settings.
. Deploy the plugin set again to apply these changes.

By selecting *German* as the *Target language*, you can adapt the German labels for your online shop. The selected labels are then also applied in the back end, only the addition _Plugin_ remains. This way, it remains traceable where a payment method comes from. Reload the back end to see the changes.
Find more information on how to edit online shop texts on the manual page xref:online-store:setting-up-ceres.adoc#231[Editing online store texts].

[#50]
== Invoice document

You can create invoices manually or generate them with an xref:automation:event-procedures.adoc#events-documents[event procedure]. Either way, it is important to set up a xref:orders:order-documents.adoc#300[document template] first. Find more information about invoice documents in the manual section xref:orders:generating-invoices.adoc#[Invoices].
