= Managing payment methods
:description: Payment in plentymarkets: Set up and activate payment methods in your plentymarkets system.
:id: MVDQHNC
:keywords: payment, payment method, default payment method, payment-plugins, payment plugins, payment method overview
:author: team-fulfillment-payment

Payment methods are integrated with plugins. You can download the payment plugins in the payment section in the link:https://marketplace.plentymarkets.com/en/plugins/payment[plentyMarketplace^]. Instructions for setup are also in the plentyMarketplace or in the manual section xref:payment:payment-plugins.adoc#[Payment plugins]. +
On this page, you will find information on how to manage payment methods and which settings to select.  Moreover, you will find an overview of xref:payment:managing-payment-methods.adoc#65[payment methods in your plentymarkets system] as well as an overview of xref:payment:managing-payment-methods.adoc#70[marketplace payment methods]. These payment methods are automatically available in your plentymarkets system, as soon as you have an active account for the corresponding marketplace.

[#25]
== Specifying the default payment method

Proceed as follows to specify the payment method to be set by default in the order process in your online shop.

[.instruction]
Specifying the default payment method:

. Go to *Setup » Client » [Select client] » Orders*.
. Select a payment method from the *Default payment method* drop-down list.
. *Save* (icon:save[role="green"]) the settings.

[#30]
== Permitting the payment method in a customer class

You need to permit payment methods in the basic settings of your customer classes. These settings also relate to the *standard end customers*. New payment methods need to be added to the list of permitted payment methods. Vice versa, you can exclude payment methods from this list to prevent the payment methods from being used by a particular customer class. After having set up a new payment method in your system, check the settings under *Permitted payment methods* for each of your customer classes. For further information, refer to the xref:crm:preparatory-settings.adoc#create-customer-class[Creating a customer class] chapter.

[TIP]
.SSL certificate and encryption
====
We generally recommend that you use xref:business-decisions:domains.adoc#[SSL encryption] for your online shop if you work with payment data and customer data. This is required for payment methods that work with an iframe.
====

[#50]
== Offering a discount based on a payment method

You can offer your customers a discount when they use a specific payment method. This is a customer class setting which enables you to offer a discount on payment methods in the online shop. For information on how to set this up, refer to the chapter xref:crm:preparatory-settings.adoc#discount-payment-method[Setting up a discount based on the method of payment] of the manual.

[#60]
==  Shipping without payment

Some payment methods require items to be shipped before the payment was received, e.g. with payment on invoice. If the xref:stock-management:managing-stocks.adoc#[stock] is limited to net stock, then the system will check whether stock is available and will set the corresponding order in status 4 or 5. To apply this setting, go to xref:orders:basic-settings.adoc#[Setup » Orders » Settings] and select *YES* for the option *Status changes to 4 instead of 5 if stock is missing*. If you select *NO* for this setting, no stock limitation is set. The order will then be directly cleared for shipping and set to order status 5.

The following payment methods require shipping before payment:

*  Invoice
*  Debit
*  Cash on delivery
*  Amazon

For further information, refer to the xref:stock-management:managing-stocks.adoc#[Stocks] page of the manual.

[#65]
== Overview of payment methods in the system

You can find an overview of all payment methods and their IDs in your plentymarkets system in the *Setup » Orders » Payment » Methods* menu. By default, the plugin payment methods are displayed. If you want to see all the existing system payment methods, use the toggle (icon:toggle-on[role="green"]) above the table.

In this overview, payment methods cannot be activated. If you want to integrate a payment methods into your plentymarkets system and thus make it available for your customers, you have to download the corresponding plugin from the link:https://marketplace.plentymarkets.com/en/plugins/payment[plentyMarketplace^]. Instructions for setup are also in the plentyMarketplace or in the manual section xref:payment:payment-plugins.adoc#[Payment plugins].

[[table-payment-methods-overview]]
.Overview of payment methods
[cols="1,3"]
|====
|Table column |Explanation

|*ID*
|The unique ID of the payment method. +
This is a default column.

|*Payment method*
|Name of the payment method. +
This is a default column.

|*Back end searchable*
|If a payment is back end searchable, it is displayed everywhere in the system, where payment methods can be selected. For example in drop-down lists in event procedures etc. +
icon:check-square[role="green"] = The payment method is searchable in the back end. +
icon:minus-circle[role="red"] = The payment method is noch searchable in the back end. +
This is a default column.

|*Back end active*
|If a payment method is back end active, it can be assigned during manual order creation. Additionally, it is also searchable in the back end, which means that it is displayed everywhere in the system, where payment methods can be selected. For example in drop-down lists in event procedures etc. +
icon:check-square[role="green"] = The payment method is active in the back end. +
icon:minus-circle[role="red"] = The payment method is not active in the back end. +
This is a default column.

|*Subscription payment method*
|Displays whether a payment method can be used for subscriptions. The payment methods invoice, cash in advance and debit can be used in subscriptions. +
This is not a default column.

|*pluginKey* and *paymentKey*
|These are unique values used to identify a payment method system-wide. They are defined by the developer when registering the payment method. Thus, these values are mostly usable for developers, e.g. to read out the ID of a payment method from the system. +
This is not a default column.

|====

[#70]
== Payment methods for markets

Payment methods for markets are payment methods which are necessary to flag incoming payments from integrated markets. These payment methods are automatically available in your plentymarkets system, as soon as you have an active account for the corresponding marketplace.

* xref:markets:amazon-setup.adoc#4500[Amazon]
* xref:markets:bol-com.adoc#650[BOL.com]
* xref:markets:cdiscount.adoc#900[Cdiscount]
* xref:markets:check24.adoc#700[Check24]
* xref:markets:ebay-setup.adoc#2250[eBay purchase on invoice]
* xref:markets:flubit.adoc#370[Flubit]
* xref:markets:fruugo.adoc#600[Fruugo]
* xref:markets:idealo-setup.adoc#1100[idealo Checkout]
* xref:markets:real-setup.adoc#800[Kaufland.de Payment]
* xref:markets:neckermann-at-setup.adoc#1600[Neckermann.at]
* xref:markets:plus-gartenxxl.adoc#400[Netto]
* xref:markets:otto-market.adoc#425[OTTO Payment]
* xref:markets:pixmania.adoc#800[PIXmania]
* xref:markets:shopgate.adoc#600[Shopgate Payment]
* xref:markets:yatego.adoc#900[Yatego invoice]
* xref:markets:zalando.adoc#800[Zalando payment]
