= Managing payment methods
:keywords: payment method, payment methods, default payment method, plugin payment method, payment method overview, methods of payment, method of payment
:description: Set up and activate payment methods in your plentymarkets system.
:author: team-fulfillment-payment

Payment methods are integrated with plugins. You can download the payment plugins in the payment section in the link:https://marketplace.plentymarkets.com/en/plugins/payment[plentyMarketplace^]. Instructions on how to set up the payment methods can also be found in the plentyMarketplace or in the manual section xref:payment:payment-plugins.adoc#[Payment plugins].

On this page, you will find information on how to manage payment methods and which settings you need to carry out. Moreover, you will find an xref:payment:managing-payment-methods.adoc#65[overview of payment methods] in your plentymarkets system as well as an xref:payment:managing-payment-methods.adoc#70[overview of marketplace payment methods]. The marketplace payment methods are automatically available in your plentymarkets system as soon as you have an active account for the corresponding marketplace.

[#25]
== Specifying the default payment method

Proceed as follows to specify the payment method to be set by default in the order process in your online shop.

[.instruction]
Specifying the default payment method:

. Navigate to *Setup » Client » [Select client] » Orders*.
. Select a payment method from the *Default payment method* drop-down list.
. *Save* (material:save[]) the settings.

[#30]
== Permitting the payment method in a customer class

You need to permit payment methods in the basic settings of your customer classes. These settings also relate to the *standard end customers*. New payment methods need to be added to the list of permitted payment methods. And vice versa, you can exclude payment methods from this list to prevent the payment methods from being used by a particular customer class. After having set up a new payment method in your system, check the settings under *Permitted payment methods* for each of your customer classes. For further information, refer to the chapter xref:crm:preparatory-settings.adoc#[Creating customer classes] on the user manual page xref:crm:contacts.adoc#[Contacts].

[TIP]
.SSL certificate and encryption
====
We generally recommend that you use xref:business-decisions:ssl-certificate.adoc#[SSL encryption] for your online shop if you work with payment data and customer data. This is required for payment methods that work with an iframe.
====

[#50]
== Offering a discount based on the payment method

You can offer your customers a discount when they use a specific payment method.  This is a customer class setting which enables you to offer a discount on payment methods in the online shop. How to determine a discount on a payment method within a customer class is described in the xref:crm:preparatory-settings.adoc#discount-payment-method[Setting up a discount based on the method of payment] chapter on the xref:crm:contacts.adoc#[Contacts] page of the manual.

[#60]
==  Shipping without payment

Some payment methods require items to be shipped before the payment was received, e.g. with payment on invoice. If the xref:stock-management:managing-stocks.adoc#[stock] is limited to net stock, the system will check whether stock is available and will set the corresponding order in status 4 or 5. If you want to apply this setting, go to the xref:orders:basic-settings.adoc#[basic settings of the order] in the *Setup » Orders » Settings* menu and select *YES* for the option *Status changes to 4 instead of 5 if stock is missing*. If you select *NO* for this setting, _no_ stock limitation is set. The order will then be directly cleared for shipping and set to order status 5.

The following payment methods require shipping before payment:

*  Invoice
*  Debit
*  Cash on delivery
*  Amazon

For further information, refer to the xref:stock-management:managing-stocks.adoc#[Stocks] page of the manual.

[#65]
== Overview of payment methods

You can find an overview of all payment methods and their IDs in your plentymarkets system in the *Setup » Orders » Payment » Methods* menu. +
By default, all plugin payment methods are displayed (material:toggle_off[]). Do you want to see all payment methods that are available in the system? Then change the button above the table from material:toggle_off[] *All plugin payment methods are displayed* to material:toggle_on[role=skyBlue] *All system payment methods are displayed*.

*_Note:_* It is _not_ possible in the overview to activate payment methods. +
If you want to integrate payment methods into your plentymarkets system and thus make them available for your customers, you have to download the corresponding plugin from the link:https://marketplace.plentymarkets.com/en/plugins/payment[plentyMarketplace^]. Instructions on how to set up the payment methods can also be found in the plentyMarketplace or in the manual section xref:payment:payment-plugins.adoc#[Payment plugins].

[[table-payment-methods-overview]]
.Overview of payment methods
[cols="1,3"]
|====
|Table column |Explanation

| *ID*
|The unique ID of the payment method. +
This is a default column.

| *Payment method*
|Name of the payment method. +
This is a default column.

| *Back end searchable*
|If a payment is searchable in the back end, it is displayed everywhere in the system where payment methods can be selected. For example in the drop-down lists in xref:automation:event-procedures.adoc#[event procedures] or in xref:crm:preparatory-settings.adoc#[customer classes]. +
material:check_circle[role=green] = The payment method is searchable in the back end. +
material:cancel[role=red] = The payment method is _not_ searchable in the back end. +
This is a default column.

| *Back end active*
|If a payment method is active in the back end, it can be assigned during manual order creation. Additionally, the payment method is also searchable in the back end, which means that it is displayed everywhere in the system where payment methods can be selected. For example in the drop-down lists in xref:automation:event-procedures.adoc#[event procedures] or in xref:crm:preparatory-settings.adoc#[customer classes]. +
material:check_circle[role=green] = The payment method is active in the back end. +
material:cancel[role=red] = The payment method is _not_ active in the back end. +
This is a default column.

| *Subscription payment method*
|Shows whether the payment method can be used for xref:orders:subscription.adoc#[subscription]. These are the payment methods *invoice*, *cash in advance* and *debit*. +
This is _not_ a default column.

| *pluginKey* and *paymentKey*
|These are unique values used to identify a payment method system-wide. They are defined by the developer when registering the payment method. Thus, these values are mostly usable for developers, e.g. to read out the ID of a payment method from the system. +
This is _not_ a default column.

|====

[#70]
== Payment methods for markets

Payment methods for markets are payment methods which are necessary to flag incoming payments from integrated markets. The marketplace payment methods are automatically available in your plentymarkets system as soon as you have an active account for the corresponding marketplace.

* xref:markets:amazon-setup.adoc#4500[Amazon]
* xref:markets:bol-com.adoc#650[BOL.com]
* xref:markets:cdiscount.adoc#900[Cdiscount]
* xref:markets:check24.adoc#700[Check24]
* xref:markets:ebay-setup.adoc#2250[eBay purchase on invoice]
* xref:markets:fruugo.adoc#600[Fruugo]
* xref:markets:idealo-setup.adoc#1100[idealo Checkout]
* xref:markets:kaufland-setup.adoc#800[Kaufland.de]
* xref:markets:neckermann-at-setup.adoc#1600[Neckermann.at]
* xref:markets:plus-gartenxxl.adoc#400[Netto]
* xref:markets:otto-market.adoc#425[OTTO Payment]
* xref:markets:shopgate.adoc#600[Shopgate Payment]
* xref:markets:yatego.adoc#900[Yatego invoice]
* xref:markets:zalando.adoc#delivery-pdf-upload[Zalando Payment]
