= Managing bank details
:keywords: bank, bank details, bank data, EBICS, SEPA, SEPA direct debit mandate, debit, bank information, account, bank account, account holder, account number, bank code, IBAN, BIC, direct debit mandate, debit order, debit advice mandate, payments details, EBICS account, interim transaction report, business account, provision of bank statements
:description: Manage your own and your customers’ bank details. Set up EBICS and SEPA in your plentymarkets system.
:author: team-fulfillment-payment

On this page of the manual, you learn how to save your <<#own-bank-details, own bank details>> and <<#bank-details-customer, your customers’ bank details>> as well as how to set up <<#ebics, EBICS>> and <<#220, SEPA>>.

[#own-bank-details]
== Saving own bank details

The bank details saved in the basic settings are linked globally in the entire plentymarkets system. Thus, the saved bank details are valid for all clients. It is not possible to save different bank details for different clients. Corrections to the bank details can only exclusively made in this menu. If you make changes in this menu, this will have an effect on the entire system.

[.instruction]
Saving bank details:

. Go to *Setup » Settings » Bank*.
. Enter your bank details. Note <<#table-save-bank-details>>.
. *Save* (material:save[]) the settings.

[[table-save-bank-details]]
.Saving bank details
[cols="1,3"]
|====
|Setting |Explanation

| *Account holder*
|Enter the account holder’s first name and last name. +

Use the variable *Account holder (master data)* in email templates that you create via the xref:crm:emailbuilder.adoc#[EmailBuilder]. +
Use the template variable *$BankAccountOwner* in email templates that you create via the xref:crm:sending-emails.adoc#1200[client settings].

| *Account number*
|Enter the account number. +

Use the variable *IBAN (master data)* in email templates that you create via the xref:crm:emailbuilder.adoc#[EmailBuilder]. The IBAN composes of the country identifier (DE for Germany), a check digit and the former bank code and account number. +
Use the template variable *$BankAccount* in email templates that you create via the xref:crm:sending-emails.adoc#1200[client settings].

| *Bank code*
|Enter the bank code. +

Use the variable *IBAN (master data)* in email templates that you create via the xref:crm:emailbuilder.adoc#[EmailBuilder]. The IBAN composes of the country identifier (DE for Germany), a check digit and the former bank code and account number. +
Use the template variable *$BankCode* in email templates that you create via the xref:crm:sending-emails.adoc#1200[client settings].

| *Bank*
|Enter the bank name. +
Use the variable *Bank name (master data)* in email templates that you create via the xref:crm:emailbuilder.adoc#[EmailBuilder]. The IBAN composes of the country identifier (DE for Germany), a check digit and the former bank code and account number. +
Use the template variable *$BankName* in email templates that you create via the xref:crm:sending-emails.adoc#1200[client settings].

| *IBAN*
|Enter the International bank account number. +

Use the variable *IBAN (master data)* in email templates that you create via the xref:crm:emailbuilder.adoc#[EmailBuilder]. +
Use the template variable *$BankIban* in email templates that you create via the xref:crm:sending-emails.adoc#1200[client settings].

|====

[#bank-details-customer]
== Saving the customer’s bank details

You can save the xref:crm:edit-contact.adoc#bank-details[contact’s bank details] in the xref:crm:edit-contact.adoc#details-individual-areas[contact data record]. Bank details are needed, for example, for the payment method xref:payment:debit.adoc#[debit]. There is also an xref:payment:beta-managing-payments-new.adoc#intable-import-customer-bank-data[import function] for bank details in plentymarkets. Contact a legal adviser for information about the current laws in your own country as well as in other countries of delivery.

[.instruction]
Saving the customer’s bank details:

. Go to *CRM » Contacts*.
. Search for the contact by means of the filter settings. Note the explanations about the filters on the xref:crm:search-contact.adoc#[Searching for a contact] page. +
→ The contacts that correspond to the search criteria entered are displayed.
. Click in the line of the contact. +
→ The detail view of the contact opens.
. In the navigation on the left side, click on *Bank details*.
. Carry out the settings. Note <<#table-save-bank-details-customer>>.
. *Save* (material:save[]) the settings.

[[table-save-bank-details-customer]]
.Saving the customer’s bank details
[cols="1,3"]
|====
|Setting |Explanation

| *IBAN*, *BIC*, *Account holder*, *Account number*, *Bank code*
|What are the contact’s bank details? +
The fields *IBAN* and *Account holder* are mandatory fields.

| *Bank name, street, postcode and town of the bank*
|What’s the name and address of the bank?

| *Country of the bank*
|Select the country from the drop-down list.

| *SEPA direct debit mandate*
|By default, SEPA direct debit mandate is _not_ activated (material:toggle_off[]). Therefore, activate the button (material:toggle_on[role=skyBlue]) as soon as the contact has signed the SEPA direct debit mandate. +
*_Important:_* This option needs to be selected before pain.008 formats can be retrieved for SEPA payments. How to automatically export SEPA direct debits into a ZIP file using a process to provide your bank with this file is described on the xref:automation:procedures.adoc#410[Procedures/control elements] page in the xref:automation:procedures.adoc#[Processes] user manual area.

| *SEPA direct debit mandate granted on*
|Only visible when the option *SEPA direct debit mandate* has been activated (material:toggle_on[role=skyBlue]). +
The date when the contact agreed to the SEPA direct debit mandate is displayed. As an alternative, you can select the date from the calendar (material:today[]).

| *Type of mandate*
|Only visible when the option *SEPA direct debit mandate* has been activated (material:toggle_on[role=skyBlue]). +
Select an option from the drop-down list: +
*SEPA business to business direct debit* = Enables business customers (B2B) in the role of payers to make payments by direct debit. +
*SEPA core direct debit* = Allows a biller to collect funds from a payer's account, provided that a signed mandate has been granted by the payer to the biller.

| *Payment frequency*
|Only visible when the option *SEPA direct debit mandate* has been activated (material:toggle_on[role=skyBlue]). +
Select an option from the drop-down list: +
*One-time payment* = Is typically used for standard orders. +
*Recurring payment* = Is typically used for regularly occurring orders such as subscription orders, etc.

|====

[#ebics]
== EBICS

EBICS (Electronic Banking Internet Communication Standard) is a transmission protocol for banking information for usage by banking clients. With the help of the standardised EBICS procedure, retrieving payments has become even easier. You can fully integrate EBICS in your plentymarkets system using the link:https://marketplace.plentymarkets.com/en/ebics_5098[EBICS^] plugin. No third-party providers are required.

For communication via EBICS, your sales figures are saved on the bank server in a file, comparable to bank statements. This file is imported in your plentymarkets system and the sales figures are booked in plentymarkets. The linked EBICS account can be seen as a combined account of several bank accounts. A file with the sales figures of an EBICS account is generated daily (Format CAMT053 or MT940) after activation by the bank. This file can be retrieved at night and all incoming payments are available the next morning. In addition, multiple interim transaction report files are generated daily (Format CAMT052 or MT942) which can be retrieved to book interim transaction reports in your plentymarkets system.

EBICS is integrated in your system using the EBICS plugin. To do so, download the EBICS plugin from the ink:https://marketplace.plentymarkets.com/en/ebics_5098[plentyMarketplace^]. To set up EBICS, you have to carry out a few basic settings in your plentymarkets system. These settings are described in the following sub-chapters.

[#70]
=== Applying for EBICS at your bank

The first step in using EBICS in plentymarkets is registering for the procedure with your bank to receive the necessary documents to fill out and return.   Once completed, you will receive all data you need from your bank to use EBICS, e.g. the bank customer ID. +
The following details for EBICS have to be entered in the form.

[IMPORTANT]
.Existing EBICS accounts
====
It is _not_ allowed to set up existing EBICS accounts which are already in use in plentymarkets. Multiple users can be listed in an EBICS account. EBICS users are called participants (German: Teilnehmer). If you already hold an account, then apply for a new one (technical user is also possible). Only use this account for plentymarkets.
====

[#80]
==== Account numbers

Enter the account numbers for the accounts that you would like revenue to be retrieved and booked into plentymarkets from. Entering account numbers is optional because the retrieval is technically based on the user data.

[IMPORTANT]
.Only save business accounts
====
There is currently _no_ option in plentymarkets for setting up accounts individually for EBICS retrieval. This means that payment transactions can only be retrieved globally by the plentymarkets system for all accounts saved. This includes e.g. payment transactions on your private account as well, if this account was saved. For this reason, only save the account numbers of your business accounts.
====

[WARNING]
.One account for several users
====
If several different users all refer to the same account (some banks manage multiple accounts together), then problems may occur if retrieval is carried out simultaneously. This is true even if the users work with different plentymarkets systems. There is currently no solution to prevent this.
====

[#90]
==== Provision of bank statements

Provisioning of bank statements can either be done based on the date of the bookkeeping entry or based on bank statements.

[[table-provision-bank-statements]]
.Provision of bank statements
[cols="1,3"]
|====
|Setting |Explanation

| *Based on date of bookkeeping entry*
|A fictitious, consecutive number is included. This setting is activated by default.

| *Based on bank statements*
|An effective bank statement number is included. Provided that automatic bank statement retrieval is carried out on a daily basis.
|====

[#100]
==== Participants

When setting up your accounts for EBICS, you create one or more xref:business-decisions:user-accounts-access.adoc#10[users] for your accounts. EBICS users are called participants (German: Teilnehmer). You can create participants including different order types. One of these participants has to be saved in the plentymarkets system with the *participant ID* that you received from your bank.

plentymarkets only requires one participant, e.g. a user account with the lowest rights, in order to carry out the EBICS payment retrieval. Only one participant may be set up per EBICS account.

[#110]
==== Order type

plentymarkets needs the order types as explained in <<#table-order-signature-types>> in order to successfully retrieve the transactions on your EBICS account. Also pay attention to the notes about order and signature types given on your bank’s forms.

[[table-order-signature-types]]
.Order and signature types
[cols="1,3"]
|====
|Type |Explanation

| *STA*
|Statement of account *MT940* or *CAMT053*. <<#180, Retrieval of the transactions>> is done at the end of the day.

| *VMK*
|Interim transaction report *MT942* or *CAMT052*. Depending on the respective bank, interim transaction reports are created and made ready for retrieval several times a day. This <<#190, information>> is optional for plentymarkets.

| *EU Type "T"*
|Signature type that provides authorisation exclusively for the retrieval of transaction data.
|====

[#120]
=== Creating an EBICS account

To use EBICS, you have to create an account first. To do so, proceed as described below.

[.instruction]
Creating an account:

. Go to *Setup » Orders » Payment » Plugins » EBICS*.
. Click on *Create new account* (material:add_box[]). +
→ The *New account* window opens.
. Carry out the settings. Note <<#table-ebics-account-settings>>.
. *Save* (material:save[]) the settings. +
→ The account is created.

[[table-ebics-account-settings]]
.EBICS account settings
[cols="1,3"]
|====
|Setting |Explanation

| *Active*
|Activate the button to mark the account as active.

| *Account name*
|Enter the internal name under which the account appears in the overview.

| *First name*
|Enter the account holder’s first name.

| *Last name*
|Enter the account holder’s last name.

| *Bank subscriber ID*
|Enter the bank subscriber ID as submitted by the bank.

| *Bank customer ID*
|Enter the bank customer ID as submitted by the bank.

| *Bank*
|Select a bank from the list.

| *Create bank*
|Activate the button to add a bank that is not stated in the list. +
*Bank*: Enter the bank parameters as submitted by the bank. +
*URL*: Enter the bank’s URL. +
This option is only available when creating a new account.

| *Account version*
|Select from the drop-down list which account version is to be used. Details can be obtained from your bank.

| *EBICS version*
|Select from the drop-down list which EBICS version your bank is using. Details can be obtained from your bank.

| *Interim transaction report*
|Select from the drop-down list with which method the interim transaction reports are retrieved. Details can be obtained from your bank.

| *Daily account statements*
|Select from the drop-down list with which method the daily account statements are retrieved. Details can be obtained from your bank.

| *IBAN / Account number*
|Enter IBANs resp. account numbers of linked accounts separated by commas. The CAMT method requires the IBAN, the MT method requires the account number.

|====

[#130]
==== Carrying out EBICS account settings

After creating the account, you can change the settings by accessing it from the account overview. With a set up account, several functions are available to you. These are described in the following. In addition, the log next to the account lists the events for the specific account.

[.instruction]
Editing the account

. Go to *Setup » Orders » Payment » Plugins » EBICS*.
. Click on *Edit* to open the account. +
→ The window *Account settings* opens.
. Carry out the settings. Note <<#table-ebics-settings>>.
. *Save* (material:save[]) the settings.

[IMPORTANT]
.Domain transfer
====
Save the basic settings again after carrying out a xref:business-decisions:domains.adoc#[domain transfer]. This updates the EBICS data.
====

[[table-ebics-settings]]
.EBICS settings
[cols="1,3"]
|====
|Setting |Explanation

| *Account settings*
|The settings for the selected account.

| *Transactions*
|Manages the business transactions to be retrieved.

| *Manual payment retrieval*
|Retrieves all orders of a certain date in case of a technical error. +
*_Note:_* This function only retrieves the data already saved in the system. There is _no_ new synchronisation with the bank.

| *Get status*
|Retrieves the current initialisation status from the EBICS tool.

| *Get order types*
|Retrieves the order types available on the account. These are the order types currently available on the server. +
*_Note:_* Using this function too often can cause errors.

| *Initialise account*
|The keys are generated and sent to the bank via INI. HIA is activated.

| *Initialisation letter*
|Creates a PDF initialisation letter from the generated keys and downloads the document. It has to be signed and sent to the bank for initialisation. The button is inactive until the keys are successfully created. +
*_Note:_* For the download of the initialisation letter to work properly, the pop-up blocker of your browser has to be deactivated.

| *Finish initialisation (HPB)*
|Completes the initialisation with the bank.

| *Expert Mode*
|All the following buttons are exclusively intended for the case that the bank required a new execution. The buttons are only available after the activation of the toggle. +
*_Important:_* Using the expert mode can damage your EBICS account in a way it has to be reset by the bank. Use these functions only if demanded by your bank.

| *Create keys*
|Creates keys for initialisation.

| *INI*
|Initialises the EBICS account.

| *HIA*
|Activates HIA.

| *HPB*
|Activates HPB.

|====

[IMPORTANT]
.Contact your bank before making changes
====
Carry out changes only after consultation with your bank. For example, if you want to use the new CAMT formats, then ask your bank whether or not this format is supported and have the format activated. Then make any necessary changes to the account settings and interim transaction report as described here.

If an account was reset and your bank needs new keys, we recommend that you set up the EBICS account again in plentymarkets. This way new keys will be generated.
====

[#140]
==== Initialise account

After you have entered your access data into plentymarkets, the system electronically registers at your bank. Secret key values are necessary for retrieval via EBICS. They are generated by the system. +
After these key values were created and the initial electronic registration was carried out, the values have to be printed out, signed and handed in at your bank. +
*_Note:_* Only the participant saved in plentymarkets is authorised to sign this document. The bank will _not_ activate the EBICS interface if the signature was not given by the participant saved in the system.

[TIP]
.Browser pop-up blocker
====
For the download of the initialisation letter to work properly, the pop-up blocker of your browser has to be deactivated.
====

[.instruction]
Initialising the account:

. Go to *Setup » Orders » Payment » Plugins » EBICS*.
. Click on the card of the account you want to initialise on *Edit*. +
→ The *Account settings* window opens.
. Click on *Initialise account*. +
→ The keys are generated. INI and HIA are executed. +
→ Once all processes are completed successfully, the button *Create initialisation letter* is activated.
. Click on *Create initialisation letter*. +
→ The initialisation letter is downloaded as a PDF document.
. Sign the initialisation letter and submit it to your bank. +
→ The bank checks the information and approves the account. You are informed once this process is complete.
. Click on *Finish initialisation (HPB)*. +
→ The account is successfully initialised.

The electronically submitted values will be compared with the values on the printed document. Then, the EBICS interface will be activated. From this moment on, the transactions will be retrieved at the <<#150, retrieval times listed below>>.

[#150]
=== Retrieval times of transactions

Maximum twice a day, your bank provides the day’s transactions in a data format. Currently, plentymarkets retrieves this data at 6am, 1pm and 11pm. Transaction data is available in the system approximately one hour after the retrieval. In addition, the bank provides interim transaction reports in data format several times a day. These can be retrieved and include the transactions of the current day.

[#160]
=== Retrieval times of interim transaction reports

As the times when interim transaction reports are made available differ from bank to bank, plentymarkets retrieves the data from the banks, if they are available, every hour between 8:00am and 6:00pm. For EBICS postings that have unconfirmed interim transactions, the words *interim transaction* will be displayed in red. If the interim transaction has been confirmed, then the lettering will change from red to green. Additionally, the confirmed posting will be assigned to the corresponding order without having to book the payment again.  You have to activate the statement of account in order for interim transaction reports to be confirmed. Note <<#table-ebics-settings>>.

[#170]
=== Managing transactions

Business transactions are all order types you conduct with your credit institute. The plugin installation does not imbed any transactions. To automatically import and assign the most common transactions, activate the following standard business transactions:

* 005 – Direct Debit
* 006 – Other debit entry advice
* 020 - Transfer order
* 051 - Transfer credit note
* 052 – Recurring entry credit memo
* 063 – Remittance credit – EU standard remittance
* 065 – Remittance credit (cross-border remittance without reporting data)
* 070 – Cheque presentation
* 088 – Remittance credit with fixed value date
* 104 - SEPA Direct Debit (single entry – debit, B2B)
* 105 - SEPA Direct Debit (single entry – debit, Core)105 - SEPA Direct Debit (single entry – debit, B2B)
* 106 – SEPA Cards Clearing (single entry - debit)
* 107 – SEPA Direct Debit (single entry - debit, direct debit generated by debit card at the point of sale)
* 152 – SEPA Credit Transfer (credit, recurring instalment payment)
* 159 – SEPA Credit Transfer return (credit) for remittance that cannot be credited (reverse remittance)
* 166 - SEPA Credit Transfer (single entry – credit)
* 169 – SEPA Credit Transfer (single entry – credit, charity payment)
* 181 – SEPA Direct Debit (credit; recredit, Core)
* 184 – SEPA Direct Debit (credit; recredit, B2B)
* 201 – Payment order
* 202 – Cross-border payment
* 206 – Cross-border remittance
* 211 – Receipt of electronic payment

[.instruction]
Managing transactions:

. Go to *Setup » Orders » Payment » Plugins » EBICS*.
. Click on the card of the account you want to manage on *Edit*. +
→ The window *Account settings* opens.
. Click on *Transactions*.
. Carry out the settings. Note <<#table-ebics-settings-transactions>>.
. *Save* (material:save[]) the settings.

[[table-ebics-settings-transactions]]
.Managing settings for business transactions
[cols="1,3"]
|====
|Setting |Explanation

| *Code*
|Enter the code of a specific transaction and click *Search*.

| *Name*
|Enter the description of a specific transaction and click on *Search*.

| *Display*
|As a standard, only active transactions are displayed. +
*All*: Displays a list of all transactions. +
*Active only*: Displays all active transactions. +
*Inactive only*: Displays all inactive transactions.

| *Group*
| *All*: Displays a list of all transactions. +
*Credit*: Displays all transactions of type Credit. +
*Debit*: Displays all transactions of type Debit.

|====

[#180]
==== Loading inactive transactions

If you receive payments with a transaction you have not activated, the EBICS plugin cannot process them. Add these transactions to your account.

[.instruction]
Loading inactive transactions:

. Go to *Setup » Orders » Payment » Plugins » EBICS*.
. Click on the card of the account you want to initialise on *Edit*. +
→ The window *Account settings* opens.
. Click on *Transactions*.
. Click on *Load inactive transactions*. +
→The search window opens.
. Enter the date for which you want to load the transactions.
. Click on *Search*. +
→ All payments for the selected date which do not fall under the activated transactions are displayed.
. Select the transactions that you want to activate.
. *Save* (material:save[]) the settings. +
→ The transactions are activated.

To assign the payments, execute the manual payment retrieval as described in <<#table-ebics-settings>>. All future payments are automatically assigned.

[#190]
==== Adding new transactions

If you receive payments with a transaction code that has not yet been activated, it will automatically be added to the global list. From there, they can be activated as described <<#170, above>>.

[#200]
=== Migrating the old integration

If you are using the current EBICS integration, you can migrate your existing accounts to the new plugin. To do so, proceed as follows.
The migration button is displayed only if the old integration has accounts that are active and correctly initialised by the bank.

[.instruction]
Migrating data:

. Go to *Setup » Orders » Payment » Plugins » EBICS*.
. Click on *Migration of existing EBICS accounts*. +
→ All data of the existing integration are migrated to the plugin. +
→ The button is deactivated. +
→ All accounts are activated in the plugin. +
. Deactivate the accounts in the old integration.
. Activate the transactions in the accounts in the plugin as described <<#170, above>>.

[#220]
== Setting up SEPA direct debit mandate

As part of the SEPA initiative (Single Euro Payments Area), euro payments were standardized in Germany and 35 other European countries on February 1st, 2014. Bank transfers and direct debits can now only be carried out with IBAN and BIC. There are different types of debits:

* *SEPA core direct debit* → comparable to a direct debit mandate
* *SEPA business to business direct debit* → comparable to a direct debit order

Business-to-business direct debits are only permitted between companies (B2B) and they require a separate mandate. You need to receive a SEPA direct debit mandate from your customers. This replaces the previous direct debit authorisation. This mandate is the new legal authorisation for using SEPA direct debit to withdraw funds from another account.

[#230]
=== Creating a document template

Go to *Setup » Orders » Documents* and click on the *SEPA direct debit mandate* sub-menu. There is a template for configuring the SEPA direct debit mandate. Fur further information about documents, refer to the xref:orders:order-documents.adoc#[Order documents] page of the manual.

[.instruction]
Creating a document template:

. Go to *Setup » Client » [Select client] » Locations » [Select location] » Documents*.
. Click on the template *SEPA direct debit mandate*. +
→ The *Template* tab opens.
. Select a *Language* from the drop-down list.
. Carry out the settings. Note <<#table-set-up-email-templates>>.
. *Save* (material:save[]) the settings.

[[table-set-up-email-templates]]
.Setting up the document template
[cols="1,3"]
|====
|Setting |Explanation

2+^|Information about the payee

| *Name of the payee +
Street and house number; +
Postcode and town; +
Country*
|Enter the seller’s data.

| *Creditor identifier*
|Enter the creditor identifier.

| *Mandate reference*
|The mandate reference is generated from the customer ID and is automatically saved.

| *Payment method*
|Enter the payment frequency. Enter *One-time payment* or *Recurring payment*.

| *Name of the person liable to pay*
|The name is automatically taken from the saved bank details. If no data is saved in the bank details, the name is taken from the xref:crm:edit-contact.adoc#contact-details[contact data].

2+^|Formatting

| *X-axis;  +
Y-axis*
|The values are based on a coordinate system with an x-axis and a y-axis. The x-axis goes from left to right and the y-axis from top to bottom. Thus, the zero point is located on the upper left corner of the page. For further information about the coordinate system, refer to the chapter <<#230, Creating a document template>>.

| *Font size*
|Select the font size in pixels.

| *Font style*
|Select *normal* or *bold* for the font style.

| *Information about the person liable to pay*
|The information is loaded from the contact data record and saved automatically. The IBAN and BIC can only be displayed on the template for the SEPA direct debit mandate if they were also saved in the contact data record in the xref:crm:edit-contact.adoc#bank-details[Bank details] area.

| *Show all pages of this template*
|Select whether to show all pages of this template.

| *Character set*
|Select *ISO-8859-1* or *Unicode*. +
*_Note:_* Generating PDF documents in Unicode may take longer.
|====

[#240]
=== Uploading a PDF template

Upload a PDF template in the *PDF template* tab. The template should contain the layout of your letterhead including the company details and the company logo. When creating the PDF template, add field names for the elements on the template as needed. Add an area for the customer’s signature in the lower portion of the template.

[IMPORTANT]
.Saving fields in the PDF template
====
The field names, e.g. IBAN, BIC and Payment method will not be displayed on the actual template. Save the field names in the PDF template.
====

[.instruction]
Uploading the PDF template:

. Go to *Setup » Client » [Select client] » Locations » [Select location] » Documents*.
. Click on the template *SEPA direct debit mandate*. +
→ The *Template* tab opens.
. Select a *Language* from the drop-down list.
. Switch to *PDF template » Tab: New template*.
. Click on *Select file*. +
→ The window *Upload file* opens.
. Open the PDF file.
. *Save* (material:save[]) the settings.

[#250]
=== Creating an email template

It is a good idea to send your customers the SEPA direct debit mandate directly after they made a purchase in your online shop. This is done by creating an email template that has the SEPA direct debit mandate as an attachment. Create an <<#260, event procedure>> for sending the email.

[.instruction]
Creating an email template:

. Go to *Setup » Client » [Select client] » Email » Templates*.
. Switch to the *New email template* tab.
. Enter a *name* and select for the setting *PDF attachment* the option *SEPA direct debit mandate*.
. Enter a text in the *Email message* tab. This text urges the customer to sign and return the attached SEPA direct debit mandate.

[#260]
=== Sending an email template with an event procedure

The email template to your customers can be sent with an xref:automation:event-procedures.adoc#[event procedure]. The event procedure is triggered, e.g. whenever a new order is received.

:table-event-procedure: <<event-procedure-send-sepa-to-customer>>
include::_includes:partial$event-procedure.adoc[]

[[event-procedure-send-sepa-to-customer]]
.Event procedure for automatically sending SEPA direct debit mandates to customers
[cols="1,3,3"]
|====
|Setting |Option |Selection

| *Event*
| *Order generation: New order*
|

| *Filter 1*
| *Order > Order type*
| *Order*

| *Filter 2*
| *Order > Payment method*
| *Debit*

| *Procedure*
| *Customer > Send email*
| *Template for SEPA direct debit mandate; +
Customer*
|====

[#270]
=== Sending an email template with the group function

The email template can also be sent by using the group function in the *CRM » Contacts* menu.

[.instruction]
Sending an email template:

. Go to *CRM » Contacts*.
. Search for the contact by means of the filter settings. Note the explanations about the filters on the xref:crm:search-contact.adoc#[Searching for a contact] page. +
→ The contacts that correspond to the search criteria entered are displayed.
. Select (material:check_box[role=skyBlue]) the contacts that you want to send an email template to.
. Click in the toolbar on the top on *Send email* (material:forward_to_inbox[]). +
→ The *Send email template* window opens.
. Select the previously created email template about the SEPA details from the drop-down list.
. Click on *Execute*. +
→ The email template is sent to the selected contacts.

For further information, refer to the xref:crm:edit-contact.adoc#group-function[Using the group function] chapter on the xref:crm:edit-contact.adoc#[Editing a contact] page.

[#280]
=== Activating SEPA payments in the bank details

Carry out the following settings once a customer has signed and returned the SEPA direct debit mandate to activate SEPA payments and retrieve pain008 formats.

[.instruction]
Activating SEPA direct debit mandate in the bank details:

. Go to *CRM » Contacts*.
. Search for the contact by means of the filter settings. Note the explanations about the filters on the xref:crm:search-contact.adoc#[Searching for a contact] page. +
→ The contacts that correspond to the search criteria entered are displayed.
. Click in the line of the contact. +
→ The detail view of the contact opens.
. In the navigation on the left side, click on *Bank details*.
. Activate (material:toggle_on[role=skyBlue]) *SEPA direct debit mandate*.
. *Save* (material:save[]) the settings.

For further information about bank details, refer to the <<#bank-details-customer, Saving the customer’s bank details>> chapter.

[#290]
=== Automating SEPA payments

Set up processes to automate your SEPA payments. Go to *Setup » Processes* and use the procedures xref:automation:procedures.adoc#400[SEPA Pain001] and xref:automation:procedures.adoc#410[SEPA Pain008].
