= Pay upon pickup
:keywords: payment method, pay upon pickup, cash, pay-upon-pickup-plugin, pay-upon-pickup-assistant, pay-upon-pickup-integration, pay upon pickup integration, payment plugin, payment integration
:description: Learn more about the integration of the plugin Pay upon pickup.
:author: team-fulfillment-payment

With the Pay upon pickup plugin, you integrate the payment method *Cash payment* in your online shop and make it available to your customers. To do so, download the plugin Pay upon pickup from the link:https://marketplace.plentymarkets.com/en/payuponpickup_4757[plentyMarketplace^]. Setup of the payment method is done with an assistant. You also have to carry out a few basic settings in your plentymarkets system so that the payment method is activated in your system. +
The explanations in this section apply after adding the plugin. You can find more information on adding and installing plugins in the xref:plugins:plugins.adoc#[Plugins] section of the manual.

[#10]
== Completing the assistant

:name-assistant: Pay upon pickup
:name-payment-method: Pay upon pickup

include::_includes:partial$completing-assistant-payment-method.adoc[]

[#30]
== Customer classes and shipping profiles

include::_includes:page$customer-class-and-shipping-profile.adoc[]

[#40]
== Editing text elements

You can edit texts of the plugin in the *CMS » Multilingualism* menu. The texts can be adapted into all available system languages. To do so, proceed as described below.

[.instruction]
Adapting language files:

. Go to *CMS » Multilingualism*.
. On the left side, select the *Source language* from the drop-down list.
. On the right side, select the *Target language* from the drop-down list.
. Expand the section *payment method* in the *PayUponPickup* area.
. Enter the text for the individual text elements in the area of the target language.
. Save (material:save[]) the settings.
. Deploy the plugin set again to apply these changes.

By selecting *German* as the *Target language*, you can adapt the German labels for your online shop. The selected labels are then also applied in the back end, only the addition _Plugin_ remains. This way, it remains traceable where a payment method comes from. Reload the back end to see the changes.
Find more information on how to edit online shop texts on the manual page xref:online-store:setting-up-ceres.adoc#231[Editing online store texts].
