= Payment Plugins
:keywords: payment, payment-plugin, payment plugin, plugin payment method
:description: Learn more about the payment plugins in plentymarkets.
:author: team-fulfillment-payment

In this section, the payment plugins developed by plentymarkets are explained. On each individual page, you find a link to download the plugin, set-up instructions as well as relevant information. Plugins are downloaded in the link:https://marketplace.plentymarkets.com/en/plugins/payment/payment-integrations[plentyMarketplace^].

Payment integrations developed by plentymarkets:

* xref:payment:cash-in-advance.adoc#[Cash in advance]
* xref:payment:cash-on-delivery.adoc#[Cash on delivery]
* xref:payment:debit.adoc#[Debit]
* xref:payment:ebics.adoc#[EBICS]
* xref:payment:invoice.adoc#[Invoice]
* xref:payment:klarna.adoc#[Klarna]
* xref:payment:mollie.adoc#[Mollie]
* xref:payment:online-bank-transfer.adoc#[Online bank transfer]
* xref:payment:payone.adoc#[PAYONE]
* xref:payment:paypal.adoc#[PayPal]
* xref:payment:pay-upon-pickup.adoc#[Pay upon pickup]

[IMPORTANT]
.Plugins in main client
====
Plugins with back end functions, as for example event procedures, always need to be installed in the main client as well. Additionally they have to be installed in the plugin set in which the payment method is to be used. The plugin also has to be activated in this plugin set.
====

Plugin sets with a payment method should always be deployed again after adaptations or updates. How to update plugins is explained on the manual page xref:plugins:updating-installed-plugins.adoc#[Updating installed plugins]. +
If something in connection to a payment method is not displayed correctly or if there are problems, it can also help to complete the assistant again. After this as well it is recommended to deploy the plugin set again.
