Im Menü *Artikel » Artikel bearbeiten » [Artikel öffnen] » [Variante öffnen]* im Tab *Verfügbarkeit* fügst du, wenn nötig, manuell marktplatzspezifische SKUs sowie Parent-SKUs hinzu. Wenn du zum Beispiel schon auf Amazon verkaufst und nun anfangen möchtest, deine Artikel über plentymarkets auf Amazon zu verkaufen, ordne deine bestehenden SKU-Nummern in diesem Menü zu.

[.instruction]
SKU hinzufügen:

. Öffne das Menü *Artikel » Artikel bearbeiten » [Artikel öffnen] » [Variante öffnen] » Varianten-Tab: Einstellungen*.
. Wechsele in das Tab *Verfügbarkeit*.
. Klicke im Bereich *SKU* auf *Hinzufügen* (icon:plus-square[role="green"]). +
→ Das Bearbeitungsfenster *Neue SKU* wird angezeigt.
. Wähle die Herkunft *Amazon*, um die SKU hinzuzufügen.
. Wähle das dazugehörige Marktplatzkonto.
. Gib die SKU ein.
. Gib die Parent-SKU ein.
. Klicke auf *Hinzufügen* (icon:plus-square[role="green"]). +
→ Die SKUs werden gespeichert und angezeigt.

SKUs können nachträglich geändert werden. Beachte allerdings, dass SKU-Änderungen dazu führen können, dass Amazon die Artikel nicht mehr erkennen bzw. nicht mehr zuordnen kann.

[IMPORTANT]
.Parent-SKU
====
Parent-SKUs können sowohl für den Artikel als auch für Varianten gespeichert werden. Die manuelle SKU-Pflege erlaubt es, für Varianten eines Artikels die Parent-SKU komplett anderer Artikelvarianten zu vergeben. So kann zum Beispiel für einen Artikel mit 5 Varianten 5 mal die Parent-SKU einer Variante, die einem ganz anderen Artikel angehört, vergeben werden. Diese Varianten werden auf Amazon als Varianten des Artikels, mit dessen Parent-SKU sie verknüpft sind, gelistet. +
Wird bei einer Variante eine andere Parent-SKU vergeben als bei den restlichen Varianten eines Artikels, werden auf Amazon zwei verschiedene Artikel gelistet, aber in plentymarkets muss dafür nur ein Artikel gepflegt werden.
====
