[#J48KIC6T]
== Produkt-Einstellungen vornehmen

In der Ansicht *Produkt* nimmst du Einstellungen zum Artikelexport vor.

[.collapseBox]
.Was ist der Unterschied zwischen Produkten und Angeboten?
--

* *Produkte* sind die gesamten Artikeldaten inklusive Preise und Bestand, die auf den Amazon-Produktdetailseiten angezeigt werden. Die Produktdetailseite enthält alle wichtigen Informationen über ein Produkt, die für Käufer:innen relevant sind.
* Bei *Angeboten* werden nur die Preise und der Bestand eines Artikels exportiert. Das eigentliche Produkt "gehört" auf dem Marktplatz einem anderen Anbieter. Du hängst dich also nur an dieses Produkt dran und veröffentlichst deinen eigenen Preis. Bei Amazon bedeutet das auch, dass dein Angebot nicht die Buy-Box erhält, sondern weiter unten in der Box "Andere Verkäufer auf Amazon" erscheint.

--

[.instruction]
Produkt-Einstellungen vornehmen:

. Öffne das Menü *Einrichtung » Märkte » Amazon » Neue Einstellungen » [Konto öffnen]*.
. Navigiere zum Bereich *Produkte*.
. Nimm die Einstellungen vor. Beachte dabei die Erläuterungen in <<#tab-Produkt>>. +
*_Tipp:_* Fehlt eine Einstellung? Dann aktiviere die Option *Erweiterte Einstellungen*.
. Speichere (terra:save[]) die Einstellungen.

[[tab-Produkt]]
.Einstellungen im Tab *Produkte*
[cols="1,2a"]
|===
| Einstellung | Erläuterung

| *SKU-Aufbau*
| Wie sollen neue SKU erzeugt werden, wenn eine Variante beim Export noch keine SKU hat?

Die SKU (Stock Keeping Unit) ist eine eindeutige Referenznummer für alle Artikel und Artikelvarianten bei Amazon.

Eine der folgenden Optionen wählen:

* *Varianten-ID* +
* *GTIN wenn vorhanden, sonst Varianten-ID* +
* *Variantennummer wenn vorhanden, sonst Varianten-ID*

Die gewählte Option greift nur für Varianten, die zum ersten Mal zu Amazon exportiert werden und noch keine SKU haben.

[.collapseBox]
.Du verkaufst schon auf Amazon und möchtest jetzt über plentymarkets auf Amazon verkaufen?
--

Dann speichere an deinen Varianten die SKU-Nummern, die du schon auf Amazon verwendest.

[.instruction]
Vorhandene SKU hinzufügen:

. Öffne das Menü *Artikel » Artikel bearbeiten » [Artikel öffnen] » [Variante öffnen] » Varianten-Tab: Einstellungen*.
. Wechsele in das Varianten-Tab *Verfügbarkeit*.
. Klicke im Bereich *SKU* auf *Hinzufügen* (icon:plus-square[role="green"]). +
→ Das Bearbeitungsfenster *Neue SKU* wird angezeigt.
. Wähle die Herkunft *Amazon*.
. Wähle das dazugehörige Amazon-Konto.
. Gib die SKU ein.
. Klicke auf *Hinzufügen* (icon:plus-square[role="green"]). +
→ Die SKU wird gespeichert und angezeigt.

// TODO: Oder auf Varianten vorbereiten verlinken?
--

| *Verlängerte Bearbeitungszeit aktivieren*
| Gewährt Amazon dir verlängerte Bearbeitungszeiten?

[cols="1a,3a"]
!===
! material:toggle_off[role="darkGrey"] +
(Standard)
! Die Standard-Bearbeitungszeit von Amazon wird verwendet.

! material:toggle_on[role="blue"]
! Erhöht die maximale Bearbeitungszeit von Amazon-Aufträgen von 30 auf bis zu 120 Tage. +
*_Hinweis:_* Aktiviere diese Einstellung nur, wenn Amazon dich für verlängerte Bearbeitungszeiten freigeschaltet hat.
!===

| *Bestandsänderungen exportieren*
| Sollen Änderungen am Bestand alle 15 Minuten an Amazon exportiert werden? +
*_Wichtig:_* Diese Einstellung gilt für alle Channels eines Amazon-Accounts.

material:toggle_off[role="darkGrey"] (Standardeinstellung) = Bestandsänderungen werden nicht abgeglichen. +
material:toggle_on[role="blue"] = Geänderte Bestände werden alle 15 Minuten zu Amazon exportiert.

| *Vollständigen Bestand exportieren*
| Sollen Bestandsdaten einmal täglich an Amazon exportiert werden? +
*_Wichtig:_* Diese Einstellung gilt für alle Channels des Amazon-Accounts.

material:toggle_off[role="darkGrey"] (Standardeinstellung) = Bestand wird nicht abgeglichen. +
material:toggle_on[role="blue"] = Einmal täglich wird ein vollständiger Bestandsabgleich durchgeführt.
|===

[#CNQFKI]
== Fulfillment-Einstellungen vornehmen

Du kannst den Versand von Varianten, die du über Amazon verkaufst, auf verschiedene Arten organisieren:

* Amazon FBA: FBA steht für Fulfillment by Amazon. Bei diesem Service übernimmt Amazon die Lagerhaltung und die gesamte Logistik. Mit anderen Worten: Amazon lagert und versendet. <<#MTHE2U4J, So richtest du Amazon FBA ein.>>
* Amazon MFN: MFN steht für merchant-fulfilled network. Du lagerst und versendest deine Produkte selbst.
<<#LZUYXNNP, So richtst du Amazon MFN ein.>>

//tag::amazon-mfn-video[]
Weitere Informationen zum Händlerversand findest du in diesem Video-Tutorial:

.Amazon MFN
video::304534064[vimeo]
//end::amazon-mfn-video[]

[#XZK4GY]
=== Amazon MFN einrichten

// TODO: Einleitung

[.instruction]
Amazon MFN einrichten:

. Öffne das Menü *Einrichtung » Märkte » Amazon » Einstellungen*.
. Navigiere zum Bereich *MFN*.
. Nimm die Einstellungen vor. Beachte dabei die Erläuterungen in <<#tab-MFN>>. +
*_Tipp:_* Fehlt eine Einstellung? Dann aktiviere die Option *Erweiterte Einstellungen*.
. Speichere (terra:save[]) die Einstellungen.

[[tab-MFN]]
.Amazon MFN einrichten
[cols="1,2a"]
|===
| Einstellung | Erläuterung

| *MFN-Aufträge importieren*
| 
material:toggle_off[role="darkGrey"] (Standardeinstellung) = MFN-Aufträge für dieses Konto werden nicht importiert. +
material:toggle_on[role="blue"] = MFN-Aufträge für dieses Konto werden alle 15 Minuten importiert. +
*_Hinweis:_* Aufträge werden alle 15 Minuten abgerufen. Trotzdem kann es bis zu 90 Minuten dauern, bis ein in Amazon generierter Auftrag in deinem plentymarkets System angezeigt wird. Das ist keine Fehlfunktion, sondern aus technischen Gründen nicht anders möglich. Meistens wirst du aber vorher durch eine E-Mail von Amazon über den Verkauf informiert und kannst den Auftrag im Seller Central schon ansehen.

| *Auftragsstatus für übertragene Erstattungen*
| Einen xref:auftraege:auftraege-verwalten.adoc#1200[Auftragsstatus] wählen. Aufträge, für die erfolgreich eine Erstattung an Amazon übertragen wurde, werden in diesen Auftragsstatus verschoben.

| *Auftragsstatus für Erstattungen, die nicht übertragen wurden*
| Einen xref:auftraege:auftraege-verwalten.adoc#1200[Auftragsstatus] wählen. Aufträge, für die keine Erstattung an Amazon übertragen werden konnte, werden in diesen Status verschoben.

| *Ausstehende Aufträge importieren*
| Wählen, ob ausstehende Aufträge von Amazon importiert werden sollen. 

[cols="1a,3a"]
!===
! material:toggle_off[role="darkGrey"] +
(Standard)
! Ausstehende Aufträge werden nicht importiert. Es wird also kein Warenbestand reserviert.

! material:toggle_on[role="blue"] 
! Ausstehende Aufträge werden alle 15 Minuten importiert. Der Warenbestand wird reserviert.

*_Ablauf:_*

* Ausstehende Amazon-Aufträge werden mit dem Status *[1] Unvollständige Daten* importiert. Die Aufträge bleiben in diesem Status, bis Amazon den Auftrag freigibt.
* Bis zur Freigabe werden keine Adressen und keine Artikelpreise am Auftrag gespeichert.
* Nach der Freigabe durch Amazon wird der Auftrag aktualisiert und die dazugehörigen Adressen und Preise werden gespeichert.
* Wenn Amazon den Auftrag nicht freigibt, wird der Auftrag automatisch in Status *[8] Storniert* verschoben. Der Warenbestand wird wieder freigegeben.
!===

| *Versandbestätigungen aktivieren*
| Wählen, ob Versandbestätigungen an Amazon gesendet werden sollen.
// TODO: Was wenn nicht? Dann EA?
|===

[#92ZUDZ]
=== Amazon FBA einrichten

Wenn du Amazon FBA nutzt, lege nun fest, wie FBA-Aufträge, die über Amazon eingehen, behandelt werden sollen.

[#60]
==== Lager für Amazon FBA erstellen

Erstelle zuerst Lager, die für Amazon Fulfillment-Aufträge verwendet werden sollen. Dabei musst du für jedes Amazon-Logistiklager, an das du Waren sendest, auch ein Lager in plentymarkets erstellen. Nur so bleibt die komplette Funktionalität der Warenwirtschaft auch beim FBA-Programm erhalten und du behältst die Lagerbestände bei Amazon über dein plentymarkets System im Blick.

Du benötigst die folgenden Lager:

* ein Lager für deinen FBA-Bestand
* ein Lager für deinen FBA-Bestand in Großbritannien
* ein Lager für unverkäuflichen FBA-Bestand
* ein Lager für unverkäuflichen FBA-Bestand in Großbritannien

[.instruction]
Lager für Amazon FBA erstellen:

. Öffne das Menü *Einrichtung » Waren » Lager*.
. Klicke auf *Neues Lager*.
. Gib einen Namen für das Lager ein.
. Wähle einen *Lagertyp*. +
*_Hinweis:_* Wenn du dieses Lager nur für FBA-Bestände verwenden möchtest, du den Bestand dieses Lagers also nicht in deinem plentyShop oder auf anderen Marktplätzen anbieten möchtest, wähle den Lagertyp *Reparatur*.
. Wähle als *Logistiktyp* die Option *Amazon*.
. Speichere (terra:save[]) die Einstellungen. +
→ Das Lager wird alphabetisch sortiert unter Lager angezeigt und geöffnet.
. Nimm die weiteren Einstellungen gemäß der Erläuterungen auf der Handbuchseite xref:warenwirtschaft:lager-einrichten.adoc#[Lager planen] vor.
. Speichere (terra:save[]) die Einstellungen. +
→ Das Lager wird erstellt.
// TODO: Lagereinstellungen hier aufführen

[TIP]
.Separate Amazon FBA Bestandsanzeige für EU und UK
====
Seit dem Brexit wird der FBA UK Stock für Amazon.co.uk separat geführt und fällt nicht mehr unter den FBA EU Stock. Um sowohl den *FBA EU Stock* als auch den *FBA UK Stock* angezeigt zu bekommen, wird mindestens ein Konto im System benötigt, das einem europäischen Verkäuferkonto zugeordnet ist und das einen Abruf auf eine europäische Amazon-Plattform tätigen kann. Zusätzlich wird noch ein Konto im System benötigt, das einem europäischen Verkäuferkonto zugeordnet ist und das einen Abruf auf die Plattform Amazon.co.uk tätigen kann. Dieses Konto ruft dann den Bestand der gesamten FBA-UK-Bestände ab. Beachte hierzu auch das Best Practice xref:maerkte:best-practices-amazon-fba-bestandsanzeige.adoc#[Bestandsanzeige Amazon FBA für EU und UK].
====

[#92ZFDZ]
==== Amazon FBA einrichten

Wenn du Amazon FBA nutzt, lege nun fest, wie FBA-Aufträge, die über Amazon eingehen, behandelt werden sollen.

// tag::amazon-fba-settings[]
[.instruction]
Amazon FBA einrichten:

. Öffne das Menü *Einrichtung » Märkte » Amazon » Einstellungen » [Konto öffnen]*.
. Navigiere zum Bereich *FBA*.
. Nimm die Einstellungen vor. Beachte dabei die Erläuterungen in <<#tab-fba>>. +
*_Tipp:_* Fehlt eine Einstellung? Dann aktiviere die Option *Erweiterte Einstellungen*.
. Speichere (terra:save[]) die Einstellungen.

[[tab-fba]]
.Amazon FBA einrichten
[cols="1,2a"]
|===

2+^| Fulfillment by Amazon (FBA)

| *FBA-Aufträge importieren*
| Sollen FBA-Aufträge in plentymarkets importiert werden?

material:toggle_off[role="darkGrey"] (Standardeinstellung) = FBA-Aufträge für dieses Konto werden nicht importiert. +
material:toggle_on[role="blue"] = FBA-Aufträge für dieses Konto werden alle 4 Stunden importiert.

| *Auftragsstatus für importierte FBA-Aufträge*
| Mit welchem xref:auftraege:auftraege-verwalten.adoc#1200[Auftragsstatus] sollen FBA-Aufträge in plentymarkets importiert werden?

*_Hinweis:_* Wenn du die Einstellung *Aufträge mit gebuchtem Warenausgang importieren* aktivierst, musst du hier mindestens *Status 7* wählen.

| *Aufträge mit gebuchtem Warenausgang importieren*
| Soll für importierte FBA-Aufträge der Warenausgang als gebucht markiert werden?

Wenn die Option aktiviert ist, werden die Aufträge zwar als gebucht markiert. Es wird aber keine Warenbewegung ausgelöst. Der Bestand wird erst durch den Auftragsbericht von Amazon reduziert.

*_Wichtig:_* Wenn die Einstellung aktiv ist, wähle mindestens Status 7 für die Einstellung *Auftragsstatus für importierte FBA-Aufträge*.

| *Retouren importieren*
| Sollen Retouren in plentymarkets importiert werden?

[cols="1a,3a"]
!===
! material:toggle_on[role="blue"] +
(Standard)
! Retouren werden einmal täglich importiert. +
*_Wichtig:_* Retouren werden nur importiert, wenn der Auftrag mit unveränderter externer Auftragsnummer in plentymarkets vorliegt.

*_Tipp:_* Im Retourenfall senden Käufer:innen die Ware zurück an Amazon. Die Retoure wird in dein plentymarkets System importiert und mit dem Retourenstatus im Auftragsmenü erstellt, den du im Menü *Einrichtung » Aufträge » Einstellungen* gewählt hast.

! material:toggle_off[role="darkGrey"]
! Retouren werden nicht importiert.
!===

| *Gutscheine bei Retouren berücksichtigen*
| Wählen, ob Rabatte von Amazon bei Retouren berücksichtigt werden sollen oder nicht. Dabei wird kein Mindestbestellwert für den Gutschein berücksichtigt.

*_Wichtig:_* "Gutscheine" können Rabatte aus Amazon Delivery Campaigns, Amazon Campaigns oder sonstige von Amazon gewährte Rabatte sein. Es können aber auch zusätzliche Kosten sein, die Amazon erhebt. Beispiele hierfür sind Kosten für Geschenkverpackungen oder Fälle, in denen Amazon eigene Versandkosten berechnet.

[cols="1a,3a"]
!===
! material:toggle_on[role="blue"] +
(Standard)
! FBA-Retouren enthalten Artikelpositionen für Rabatte oder Zusatzkosten von Amazon. Der Gutschriftsbetrag stimmt also nicht mit dem Betrag des ursprünglichen Auftrags überein. Die Gutschrift muss ggf. über *Stornobeleg » Auftragsanpassung » Neue Gutschrift* korrigiert werden.

[.collapseBox]
.Beispiel
--

* Warenwert des ursprünglichen Auftrags: 50,00 Euro
* Von Amazon erhobene zusätzliche Portokosten: 5,00 Euro
* Betrag in der Gutschrift: 55 Euro
--

! material:toggle_off[role="darkGrey"]
! Auftragspositionen für Amazon-Gutscheine werden nicht importiert. Rabatte oder zusätzliche Kosten von Amazon werden also ignoriert und bei der Berechnung nicht berücksichtigt.

[.collapseBox]
.Beispiel
--

* Warenwert des ursprünglichen Auftrags: 50,00 Euro
* Von Amazon erhobene zusätzliche Portokosten: 5,00 Euro
* Betrag in der Gutschrift: 50 Euro
--
!===
  
| *Artikelrabatte aus Kampagnen ignorieren*
| Wähle, wie Rabatte auf Artikel beim Import von Aufträgen behandelt werden sollen.

*_Hintergrund:_* Aus Amazon-Bestellberichten geht nicht hervor, ob Artikelrabatte eines Auftrags von der Händler:in oder von Amazon gewährt wurden. Beim Import wird in beiden Fällen der Rabattbetrag vom Auftragswert abgezogen. Wenn Amazon den Rabatt gibt, weichen dann aber der Auftragswert und der von Amazon an dich ausgezahlte Betrag voneinander ab. In solchen Fällen musst du den Auftrag manuell anpassen, da du sonst zu wenig Umsatzsteuer für den Auftrag abführst.

*_Empfehlung:_* Aktiviere diese Einstellung, wenn du selbst keine Kampagnen mit Produktrabatten auf Amazon-Plattformen anbietest.

[cols="1,3a"]
!===
! material:toggle_off[role="darkGrey"] +
(Standard)
! Der Rabattbetrag wird importiert. Wenn der Rabatt von Amazon gewährt wurde, muss der Auftrag manuell angepasst werden.

[.collapseBox]
.Beispiel
--

*_Ablauf bei Rabatt von Amazon:_*

* Eine Kundin kauft einen deiner Artikel für 10,00 Euro.
* Amazon gibt der Kundin einen Rabatt von 1,00 Euro.
* Der Auftrag wird mit einem Auftragswert von 9,00 Euro importiert.
* Amazon zahlt dir 10,00 Euro aus. +
→ Den Auftragswert und der Betrag, den Amazon an dich auszahlt, stimmen nicht übereinstimmen. Der Auftrag muss manuell korrigiert werden.

*_Ablauf bei Rabatt von Händler:in:_*

* Eine Kundin kauft einen deiner Artikel für 10,00 Euro.
* Du gibst der Kundin einen Rabatt von 1,00 Euro.
* Der Auftrag wird mit einem Auftragswert von 9,00 Euro importiert.
* Amazon zahlt dir 9,00 Euro aus. +
→ Alle Summen sind korrekt.

*_Hinweis:_* Um die Beispiele zu vereinfachen werden darin die Gebühren nicht berücksichtigt, die du an Amazon zahlst.
--

! material:toggle_on[role="blue"]
! Der Rabattbetrag wird beim Import vom Auftragswert abgezogen. Diese Einstellung wird für Händler:innen empfohlen, die selbst keine Rabattkampagnen auf Amazon-Plattformen fahren. Wenn der Rabatt von der Händler:in gewährt wurde, muss der Auftrag manuell angepasst werden.

[.collapseBox]
.Beispiel
--

*_Ablauf bei Rabatt von Amazon:_*

* Eine Kundin kauft einen deiner Artikel für 10,00 Euro.
* Amazon gibt der Kundin einen Rabatt von 1,00 Euro.
* Amazon zahlt dir 10,00 Euro aus.
* Der Auftrag wird mit einem Auftragswert von 10,00 Euro importiert. +
→ Alle Summen sind korrekt.

*_Ablauf bei Rabatt von Händler:in:_*

* Eine Kundin kauft einen deiner Artikel für 10,00 Euro.
* Du gibst der Kundin einen Rabatt von 1,00 Euro.
* Der Auftrag wird mit einem Auftragswert von 10,00 Euro importiert.
* Amazon zahlt dir 9,00 Euro aus. +
→ Den Auftragswert und der Betrag, den Amazon an dich auszahlt, stimmen nicht übereinstimmen. Der Auftrag muss manuell korrigiert werden.

*_Hinweis:_* Um die Beispiele zu vereinfachen werden darin die Gebühren nicht berücksichtigt, die du Amazon zahlst.
--
!===

| *Versandrabatte aus Kampagnen ignorieren*
| Wähle, wie Rabatte auf die Versandkosten beim Import von Aufträgen behandelt werden sollen.

*_Hintergrund:_* Aus Amazon-Bestellberichten geht nicht hervor, ob Versandrabatte eines Auftrags von der Händler:in oder von Amazon gewährt wurden. Beim Import wird in beiden Fällen der Rabattbetrag vom Auftragswert abgezogen. Wenn Amazon den Rabatt gibt, weichen dann aber der Auftragswert und der von Amazon an dich ausgezahlte Betrag voneinander ab. In solchen Fällen musst du den Auftrag manuell anpassen, da du sonst zu wenig Umsatzsteuer für den Auftrag abführst.

*_Empfehlung:_* Aktiviere diese Einstellung, wenn du selbst keine Kampagnen mit Versandrabatten auf Amazon-Plattformen anbietest.

[cols="1,3a"]
!===
! *Nein* (Standardeinstellung)
! Der Rabattbetrag wird importiert. Wenn der Rabatt von Amazon gewährt wurde, muss der Auftrag manuell angepasst werden.

[.collapseBox]
.Beispiel
--

*_Ablauf bei Rabatt von Amazon:_*

* Eine Kundin kauft einen deiner Artikel für 10,00 Euro plus 3,00 Euro Versandkosten.
* Amazon schenkt der Kundin die Versandkosten.
* Der Auftrag wird mit einem Auftragswert von 10,00 Euro plus 3,00 Euro Versandkosten importiert.
* Amazon zahlt dir 13,00 Euro aus. +
→ Den Auftragswert und der Betrag, den Amazon an dich auszahlt, stimmen nicht übereinstimmen. Der Auftrag muss manuell korrigiert werden.

*_Ablauf bei Rabatt von Händler:in:_*

* Eine Kundin kauft einen deiner Artikel für 10,00 Euro plus 3,00 Euro Versandkosten.
* Du schenkst der Kundin die Versandkosten.
* Der Auftrag wird mit einem Auftragswert von 10,00 Euro plus 3,00 Euro Versandkosten importiert.
* Amazon zahlt dir 13,00 Euro aus. +
→ Alle Summen sind korrekt.

*_Hinweis:_* Um die Beispiele zu vereinfachen werden darin die Gebühren nicht berücksichtigt, die du Amazon zahlst.
--

! *Ja*
! Der Rabattbetrag wird beim Import vom Auftragswert abgezogen. Diese Einstellung wird für Händler:innen empfohlen, die selbst keine Rabattkampagnen auf Amazon-Plattformen fahren. Wenn der Rabatt von der Händler:in gewährt wurde, muss der Auftrag manuell angepasst werden.

[.collapseBox]
.Beispiel
--

*_Ablauf bei Rabatt von Amazon:_*

* Eine Kundin kauft einen deiner Artikel für 10,00 Euro plus 3,00 Euro Versandkosten.
* Amazon schenkt der Kundin die Versandkosten.
* Der Auftrag wird mit einem Auftragswert von 10,00 Euro plus 3,00 Euro Versandkosten importiert.
* Amazon zahlt dir 13,00 Euro aus. +
→ Alle Summen sind korrekt.

*_Ablauf bei Rabatt von Händler:in:_*

* Eine Kundin kauft einen deiner Artikel für 10,00 Euro plus 3,00 Euro Versandkosten.
* Du schenkst der Kundin die Versandkosten.
* Der Auftrag wird mit einem Auftragswert von 10,00 Euro plus 3,00 Euro Versandkosten importiert.
* Amazon zahlt dir 13,00 Euro aus. +
→ Den Auftragswert und der Betrag, den Amazon an dich auszahlt, stimmen nicht übereinstimmen. Der Auftrag muss manuell korrigiert werden.

*_Hinweis:_* Um die Beispiele zu vereinfachen werden darin die Gebühren nicht berücksichtigt, die du an Amazon zahlst.
--
!===

2+^| *FBA-Einstellungen: Bestand*

| *FBA-Bestand importieren*
| Sollen Bestände bei Amazon in dein FBA-Lager importiert werden?

// TODO: Warum sollte man das deaktivieren?
material:toggle_off[role="darkGrey"] (Standardeinstellung) = FBA-Bestände werden nicht mit Amazon ausgetauscht.
material:toggle_on[role="blue"] = Einmal stündlich werden FBA-Bestände in plentymarkets importiert.

| *Lager*
| Welches plentymarkets Lager soll für den FBA-Bestandsabgleich dieses Kontos verwendet werden?

Dieses Lager wird auch für die FBA-Auftragszuordnung des Kontos verwendet, wenn kein FBA-Auftrag zugeordnet werden kann, weil für das Auftragsland kein Lager eingerichtet wurde.

| *Lager UK*
| Welches plentymarkets Lager soll für den FBA-Bestandsabgleich für Großbritannien verwendet werden?

| *Lager für unverkäuflichen Bestand*
| In welches plentymarkets Lager soll unverkäuflicher Bestand des Kontos gebucht werden? Wenn du kein Lager wählst, wird der unverkäufliche Bestand nicht in plentymarkets importiert.

*_Hinweis:_* Wähle für diese Einstellung nicht das gleiche Lager wie für die Einstellung *Lager* (FBA-Lager). Sonst werden die Bestände des Lagers überschrieben.

[.collapseBox]
.Was ist unverkäuflicher Bestand?
--
Der unverkäufliche Bestand ist die Anzahl der Einheiten einer SKU, die sich in Amazon-Logistikzentren befinden und den Zustand "nicht verkaufbar" haben. Im Bericht "Lagerbestand mit Versand durch Amazon" entspricht das der Menge in der Spalte *afn-unsellable-quantity*.
--

| *Lager für unverkäuflichen Bestand UK*
| In welches plentymarkets Lager soll unverkäuflicher Bestand des Kontos in Großbritannien gebucht werden? Wenn du kein Lager wählst, wird der unverkäufliche Bestand nicht in plentymarkets importiert.

*_Hinweis:_* Wähle für diese Einstellung nicht das gleiche Lager wie für die Einstellung *Lager (UK)* (FBA-Lager). Sonst werden die Bestände des Lagers überschrieben.

[.collapseBox]
.Was ist unverkäuflicher Bestand?
--
Der unverkäufliche Bestand ist die Anzahl der Einheiten einer SKU, die sich in Amazon-Logistikzentren befinden und den Zustand "nicht verkaufbar" haben. Im Bericht "Lagerbestand mit Versand durch Amazon" entspricht das der Menge in der Spalte *afn-unsellable-quantity*.
--
//end::amazon-fba-settings[]

//tag::amazon-multi-channel-settings[]
2+^| *Multi-Channel*

| *Multi-Channel-Versand aktivieren*
| Sollen auch Aufträge von anderen Verkaufskanälen mit Amazon FBA abgewickelt werden?

*_Was ist Multi-Channel-Versand?_*

Mit Amazon FBA können auch Aufträge abgewickelt werden, die auf anderen Verkaufskanälen generiert werden, zum Beispiel auf anderen Marktplätzen oder in deinem Online-Shop. Auch für diese Aufträge übernimmt Amazon also die Lagerung und den Versand deiner Artikel.

| *Auftragsstatus für übertragene Multi-Channel-Aufträge*
| Einen xref:auftraege:auftraege-verwalten.adoc#1200[Auftragsstatus] wählen. Dieser Auftragsstatus wird Multi-Channel-Aufträgen zugewiesen, die erfolgreich an Amazon übertragen wurden.

| *Artikelpakete Multi-Channel*
| Welche Auftagspositionen sollen für FBA-Multi-Channel-Aufträge an Amazon übertragen werden? +

*_Hintergrund:_* Welche Option du wählst hängt davon ab, wie du Artikelpakete bei Amazon lagerst. Sind alle Paketbestandteile von Artikelpaketen gemeinsam verpackt bei Amazon eingelagert? Oder stellt Amazon die einzelnen Paketbestandteile selbst zu Artikelpaketen zusammen?

[cols="1,2a"]
!===
! *Alle Auftragspositionen übertragen*
! Als Auftragspositionen werden die Paketposition und die Paketbestandteile an Amazon übertragen.

*_Wichtig: Wähle diese Option nicht. Sonst versendet Amazon möglicherweise Positionen doppelt oder erfüllt den Auftrag nicht._*

! *Nur Paketposition übertragen*
! Nur die Paketposition wird an Amazon übertragen.

*_Voraussetzung:_* Alle Paketbestandteile des Artikelpakets sind in einer einzigen Verpackung bei Amazon gelagert. Das Artikelpaket hat nur eine SKU. Amazon pickt also nur eine Position.

! *Ohne Paketposition übertragen*
! Nur die Paketbestandteile werden an Amazon übertragen.

*_Voraussetzung:_* Das Artikelpaket besteht aus einzelnen Artikeln. Bei Amazon sind diese Artikel alle einzeln eingelagert. Jeder Artikel hat eine eigene SKU. Erst durch den Pick-Vorgang wird aus den Einzelartikeln ein Artikelpaket. 
!===

| *Versandkategorie*
| Wie soll Amazon deine Multi-Channel-Bestellungen versenden?

[cols="1,3a"]
!===
! *Standard*
! Normaler Versand

! *Expedited*
! Schnellversand

! *Priority*
! Bevorzugt (schnellster Versand)
!===
|===
//end::amazon-multi-channel-settings[]

[#HBN7346B]
== Channels verwalten

Channels sind die einzelnen Verkaufskanäle von Amazon in den verschiedenen Ländern.

[#HBN7446B]
=== Channels hinzufügen

Du kannst entweder Channels mit Standardeinstellungen hinzufügen oder einen vorhandenen Channel kopieren und anpassen.

[tabs]
====
Channel(s) mit Standardeinstellungen hinzufügen::
+
--

[.instruction]
Channel(s) mit Standardeinstellungen hinzufügen:

. Öffne das Menü *Einrichtung » Märkte » Amazon » Einstellungen*.
. Navigiere zum Bereich *Channels*.
. Klicke auf icon:plus[] *Channel(s) mit Standardeinstellungen hinzufügen*. +
→ Das Fenster *Channel(s) mit Standardeinstellungen hinzufügen* wird angezeigt.
. Wähle aus der Dropdown-Liste einen oder mehrere Channels.
. Klicke auf *Speichern*. +
→ Die Channels werden zur Liste der Channels hinzugefügt.
// TODO: Was sind die Standardeinstellungen?

--
 
Einstellungen eines vorhandenen Channels kopieren::
+
--

[.instruction]
Einstellungen eines vorhandenen Channels kopieren:

. Öffne das Menü *Einrichtung » Märkte » Amazon » Einstellungen*.
. Navigiere zum Bereich *Channels*.
. Klicke in der Zeile des Channels auf die weiteren Aktionen (material:more_vert[]). 
. Wähle die Option *Einstellungen für neue(n) Channel(s) übernehmen*. +
→ Das Fenster *Einstellungen für neue(n) Channel(s) übernehmen* wird angezeigt.
. Wähle aus der Dropdown-Liste *Channels* einen oder mehrere Channels.
. Klicke auf *Speichern*. +
→ Die Channels werden zur Liste der Channels hinzugefügt.

--
====

[#5T93GW10]
=== Channel-Einstellungen bearbeiten

////
In diesem Video-Tutorial erhältst du weitere Informationen zu den verschiedenen Artikeleinstellungen:

.Amazon-Artikeleinstellungen
video::199993489[vimeo]
////

[.instruction]
Channel-Einstellungen bearbeiten:

. Öffne das Menü *Einrichtung » Märkte » Amazon » Einstellungen*.
. Navigiere zum Bereich *Channels*.
. Klicke auf den Channel, den du bearbeiten möchtest.
. Nimm die Einstellungen vor. Beachte dabei die Erläuterungen in <<#tab-channels>>. +
*_Tipp:_* Fehlt eine Einstellung? Dann aktiviere die Option *Erweiterte Einstellungen*.
. Speichere (terra:save[]) die Einstellungen.

[[tab-channels]]
.Verfügbare Channel-Einstellungen
[cols="1,3a"]
|===
| Einstellung | Erläuterung

2+^| Produkte

| *Artikel exportieren*
| Sollen Artikeldaten an diesen Amazon-Channel exportiert werden?

material:toggle_off[role="darkGrey"] (Standardeinstellung) = Artikeldaten werden nicht exportiert. +
material:toggle_on[role="blue"] = Artikeldaten werden einmal täglich an diesen Amazon-Channel exportiert.

| *Exportfilter*
a| Mit den Exportfiltern kannst du Varianten anhand bestimmter Kriterien vom Export ausschließen. Die Filter sind optional. Wenn du keine Filter setzt, werden alle Varianten exportiert, die für die Herkunft freigeschaltet sind und die Exportvoraussetzungen erfüllen.

*_Wichtig:_* Wenn du mehrere Filter setzt, werden nur die Varianten exportiert, auf die _alle_ gewählten Filter zutreffen.

[cols="1a,3a"]
!===

! *Kategorien*
! Nur Varianten der gewählten Kategorien werden exportiert.

! *BMVD-Kategorien*
! Nur Varianten der gewählten Kategorien werden exportiert. +
*_Tipp:_* BMVD steht für Bücher, Musik, Video und DVD.

! *Artikelverfügbarkeit*
! Es werden nur Varianten exportiert, die die gewählten Verfügbarkeiten haben. +
*_Tipp:_* Die Variantenverfügbarkeiten werden im Menü *Einrichtung » Artikel » Verfügbarkeit* verwaltet. An den Varianten wählst du die Variantenverfügbarkeit im Menü *Artikel » Artikel bearbeiten » [Artikel öffnen] » [Variante öffnen] » Varianten-Tab: Einstellungen* im Bereich *Verfügbarkeit* ein.

! *Markierung 1*; +
*Markierung 2*
! Nur Varianten mit den gewählten Markierungen werden exportiert. Wenn du Filter für *Markierung 1* und *Markierung 2* wählst, werden nur Varianten exportiert, die beide Markierungen haben.

! *Tags*
! Nur Varianten mit den gewählten Tags werden exportiert. Du kannst einen oder mehrere Tags wählen. Wenn du mehrere Tags wählst, werden nur Varianten exportiert, die alle diese Tags haben.

! *Im Webshop des Mandanten verfügbar*
! Option aktivieren, um nur Varianten zu exportieren, die für diesen Mandanten freigegeben sind.

material:toggle_off[role="darkGrey"] (Standardeinstellung) = Alle Varianten werden exportiert, unabhängig vom gewählten Mandanten.
material:toggle_on[role="blue"] = Nur Varianten werden exportiert, die auch für den Mandanten dieses Amazon-Kontos aktiviert sind. +
*_Tipp:_* Die Mandantenverfügbarkeit aktivierst du im Menü *Artikel » Artikel bearbeiten » [Variante öffnen] » Varianten-Tab: Verfügbarkeit » Bereich: Mandant (Shop)*.
!===

| *Artikelnummer des Herstellers*
| Wählen, ob SKU, Variantennummer, GTIN, Varianten-ID, Externe Varianten-ID, Modellnummer oder kein Wert als part_number exportiert werden soll.

| *Artikelname*
| Welches plentymarkets Feld soll als Artikelname exportiert werden?

| *Artikelbeschreibung*
| Welches plentymarkets Feld soll als Artikelbeschreibung exportiert werden?

| *HTML-Tags erlauben*
| 
[cols="1a,3a"]
!===
! material:toggle_off[role="darkGrey"] +
(Standard)
! Alle HTML-Tags werden beim Export aus den Artikelbeschreibungen entfernt.

! material:toggle_on[role="blue"]
! Bestimmte HTML-Tags werden nicht aus deb Artikelbeschreibungen entfernt.

Die folgenden HTLM-Tags werden nicht entfernt: +
&lt; br &gt;, &lt; b &gt;, &lt; i &gt;, &lt; p &gt; ,&lt; ul &gt;, &lt; li &gt;, &lt; table &gt;, &lt; tr &gt;, &lt; td &gt;, &lt; th &gt;, &lt; tbody &gt; und &lt; strong &gt;
!===

2+^| *Angebote*

| *Preise aktualisieren*
| Sollen Preisänderungen an diesen Amazon-Channel exportiert werden?

material:toggle_off[role="darkGrey"] (Standardeinstellung) = Preisänderungen werden nicht exportiert. +
material:toggle_on[role="blue"] = Preisänderungen werden einmal pro Stunde an diesen Amazon-Channel exportiert.

| *Zusätzliche SKU*
| Datenaustausch für zusätzliche Amazon-SKUs aktivieren. +
*ALLE*, *Bestandsabgleich*, oder *Preisabgleich* für xref:maerkte:varianten-vorbereiten.adoc#760[zusätzliche SKUs] aktivieren.

Beim Amazon-Auftragsimport werden zusätzliche SKUs automatisch berücksichtigt. Den Bestands- und Preisabgleich für zusätzliche SKUs aktivierst du hier manuell.

* *ALLE* = Aktiviert den Bestandsabgleich und den Preisabgleich für zusätzliche SKUs.
* *Bestandsabgleich* = Der Bestand für zusätzliche SKUs wird zusammen mit dem Bestand abgeglichen.
* *Preisabgleich* = Der Preis für zusätzliche SKUs wird in dem Intervall abgeglichen, den du für die Einstellung *Preisänderungen* eingestellt hast.

Beim Bestandsabgleich für zusätzliche SKUs werden auch FBA-Bestände in plentymarkets importiert.

[.collapseBox]
.Was ist die zusätzliche SKU?
--
Zusätzliche SKUs können zusätzlich zu der SKU der Variante für den Bestandsexport und den Preisexport genutzt werden.

*_Beispiel:_* Du hast mehrere Angebote zu einer Variante in deiner Seller Central aktiv. Wenn du den Bestandsabgleich und/oder den Preisabgleich für zusätzliche SKU aktivierst, kannst über plentymarkets auch Bestand und Preis für die zusätzlichen Angebote aktualisieren.

*_Wichtig:_* Zusätzliche SKU können _nicht_ für den Artikelexport genutzt werden. Grund: Amazon erlaubt es nicht, mehrere Angebote für ein Produkt mit eindeutiger Identifizierung (EAN, ASIN etc.) zu erstellen.

Zusätzliche SKU können außerdem für die Zuordnung der Variante beim Auftragsimport genutzt werden.
--

| *Bestandsquelle*
a| Mögliche Optionen:

* *Bestandsmenge des Vertriebslagers mit höchstem Bestand*
* *Summe der Bestandsmengen aller Vertriebslager*
* *Hauptlager des Artikels*
* *Lager wählen* = Die Option *Lagerauswahl* wird eingeblendet.

*_Wichtig:_* Bei der Versandanmeldung müssen die Adressdaten des Lagers an Amazon übergeben werden. In Amazon Seller Central werden diese Adressdaten unter *Ship from* angezeigt. Achte deshalb darauf, dass für Versandlager, aus denen du Amazon-Aufträge erfüllst, im Menü *Einrichtung » Waren » Lager » [Lager öffnen] » Einstellungen* die Adressdaten des Lagers gespeichert sind.

| *Lagerauswahl* +
(nur bei *Lager wählen*)
| Ein oder mehrere Lager wählen. Die Bestände der gewählten Lager werden addiert und zu Amazon übermittelt. Dabei werden auch die Einstellungen für Bestandspuffer und Maximalbestand berücksichtigt. +

*_Wichtig:_* Wenn du für die Einstellung *Lagerauswahl* die Option *Lager wählen* einstellst, aber kein *Lager* wählst, wird der Artikel nicht exportiert, weil kein Bestand ermittelt werden kann.

| *Bestandspuffer*
| Wenn der Artikel auf Netto-Warenbestand beschränkt ist, wird der exportierte Bestand um den eingegebenen Wert verringert.

| *Maximaler Warenbestand*
| Bestimmt die obere Grenze des exportierten Bestands für alle Artikel. Diese Einstellung hat Priorität gegenüber der Einstellung *Menge für Artikel ohne Bestandsbindung*.

| *Menge für Artikel* +
*ohne Bestandsbeschränkung*
| Bei Artikeln mit der Einstellung *keine Beschränkung* wird der Maximalwert aus realem Bestand und der hier definierten Menge übermittelt. +
*_Beispiel:_* Einstellung 0, Nettowarenbestand 8. plentymarkets übermittelt 8. +
Artikel mit der Einstellung *Beschränkung auf Netto-Warenbestand* werden nicht berücksichtigt.

| *Durchschnittliche Lieferzeit in Tagen*
| Welche durchschnittliche Lieferzeit soll exportiert werden?

* *Nicht übertragen* 
* *Durchschnittliche Lieferzeit in Tagen*
* *Durchschnittliche Lieferzeit in Tagen + Bearbeitungszeit* = Öffnet ein Feld, in das du die Bearbeitungszeit eingeben kannst.

*_Tipp_*: Gib realistische Lieferzeiten ein. Diese Angaben werden als Zusage gewertet und sind wettbewerbsrechtlich relevant.

| *Bearbeitungszeit* +
(nur bei *Durchschnittliche Lieferzeit in Tagen + Bearbeitungszeit*)
| Bearbeitungszeit in Tagen eingeben. Diese Bearbeitungszeit wird zur durchschnittlichen Lieferzeit addiert.
|===

=== Channel löschen

Du möchtest einen Channel löschen? 

*_Wichtig:_* Für jedes Konto muss immer mindestens ein Channel gespeichert sein. Wenn alle Channels in der Gruppenfunktion ausgewählt sind oder das Kontextmenü des letzten verbleibenden Kanals geöffnet ist, sind die Schaltflächen zum Löschen deaktiviert.

[tabs]
====
Einen Channel löschen::
+
--
. Öffne das Menü *Einrichtung » Märkte » Amazon » Neue Einstellungen » [Konto öffnen] » Ansicht: Channels*.
. Navigiere in der Liste zu dem Channel, den du löschen möchtest. +
. Klicke auf die weiteren Aktionen (material:more_vert[]) des Channels.
. Klicke im Kontextmenü auf *Channel löschen* (material:delete[]). +
*_Wichtig:_* Für jedes Konto muss immer mindestens ein Channel gespeichert sein. Wenn du das Kontextmenü des letzten Channels öffnest, wird die Option *Channel löschen* deshalb deaktiviert. +
→ Du wirst aufgefordert, den Löschvorgang zu bestätigen.
. Bestätige die Löschung. +
→ Der Channel wird gelöscht.

--
 
Mehrere Channels löschen::
+
--
. Öffne das Menü *Einrichtung » Märkte » Amazon » Neue Einstellungen » [Konto öffnen] » Ansicht: Channels*.
. Aktiviere in der Spalte ganz links die Channels, die du löschen möchtest. +
. Klicke auf *Löschen* (material:delete[]). +
*_Wichtig:_* Für jedes Konto muss immer mindestens ein Channel gespeichert sein. Wenn du in der Gruppenfunktion alle Channels auswählst, wird die Option *Löschen* deshalb deaktiviert. +
→ Du wirst aufgefordert, den Löschvorgang zu bestätigen.
. Bestätige die Löschung. +
→ Die gewählten Channels werden gelöscht.

// TODO: Ab wann sind die Artikel dann nicht mehr auf dem Channel verfügbar?

--
====

////

| Weitere Einstellungen für FBA
a| Die folgenden Einstellungen befinden sich zwar im Bereich *Eigener Versand (MFN)* weiter oben im Menü, gelten aber auch bei Versand durch Amazon (FBA). Wähle deshalb auch für diese Einstellungen die gewünschten Optionen:

| *Auftragsimport Startdatum*
| Datum eingeben. Es werden nur Aufträge ab diesem Datum in plentymarkets importiert. +
*_Hinweis:_* Jeder in plentymarkets importierte Auftrag wird abgerechnet.

| *Auftragsposition*
| Bestimmt die Darstellung des Artikelnamens in der Auftragsposition. Eine der folgenden Optionen wählen:

* *Artikelname aus Shop übernehmen*
* *Artikelname von Amazon übernehmen - mit SKU*
* *Artikelname von Amazon übernehmen - ohne SKU*

| *Zahlungseingang*
| *Zahlungseingang gebucht* wählen, wenn der Zahlungseingang beim Import von MFN- und FBA-Aufträgen als gebucht angezeigt werden soll. +
*_Hinweis:_* Diese Einstellung greift bei eigenem Versand (MFN) und bei Versand durch Amazon (FBA).

| *Status für übertragene Retouren*
|xref:auftraege:auftraege-verwalten.adoc#1200[Auftragsstatus] für Retouren wählen, die erfolgreich an Amazon gemeldet wurden.

| *Status für nicht übertragene Retouren*
|xref:auftraege:auftraege-verwalten.adoc#1200[Auftragsstatus] für Retouren wählen, die nicht erfolgreich an Amazon gemeldet wurden.

| *Ausstehende Aufträge*
| Wählen, ob ausstehende Aufträge von Amazon alle 15 Minuten importiert werden sollen, oder nie.

| *Gutschriftenimport*
| Sollen Amazon-Gutschriften für MFN- und FBA-Aufträge in dein plentymarkets System als Auftrag des Typs *Gutschrift* importiert werden?

[cols="1,3a"]
!===
! *Nein* (Standard)
! Gutschriften werden nicht importiert.

! *Ja*
! Amazon-Gutschriften werden alle 4 Stunden in dein plentymarkets System importiert.
!===

*_Hinweis:_* Diese Einstellung greift bei eigenem Versand (MFN) und bei Versand durch Amazon (FBA).

| *Aktiv*
| Häkchen setzen, um den Versand durch Amazon zu aktivieren.

| *Herkunft*
| Wählen, ob nur Aufträge von Amazon mit FBA abgewickelt werden oder ob auch Aufträge von anderen xref:auftraege:auftragsherkunft.adoc#[Herkünften] mit FBA abgewickelt werden können.

! *Zahlungseingang*
! Option *Zahlungseingang gebucht* wählen, wenn der Zahlungseingang beim Import von MFN- und FBA-Aufträgen als gebucht angezeigt werden soll.

! *Gutschriftenimport*
! Wählen, ob Amazon-Gutschriften für MFN- und FBA-Aufträge in dein plentymarkets System importiert werden sollen.

* *Nein* (Standard) = Gutschriften werden nicht importiert. Wenn du *Nein* wählst, erstelle eine Ereignisaktion, um Retouren als Gutschriften in dein plentymarkets System zu importieren. +
* *Ja* = Amazon-Gutschriften werden alle 4 Stunden in dein plentymarkets System importiert.

!===

*_Hinweis:_* Diese Einstellungen greifen bei eigenem Versand (MFN) und bei Versand durch Amazon (FBA).
|===

////