Gehe wie unten beschrieben vor, um Amazon im Einrichtungsmenü einzurichten.

[#300]
==== Amazon-Benutzerkonto einrichten

Richte zuerst ein neues Konto für Amazon in plentymarkets ein.

[TIP]
.Amazon-Benutzerkonto mit Assistent einrichten
====
Nutze den Assistent *Amazon Grundeinstellungen* im Menü *Einrichtung » Assistenten » Omni-Channel*, um dein Amazon-Benutzerkonto schnell und einfach in plentymarkets einzurichten. Mit diesem Assistenten nimmst du außerdem Einstellungen zur Datenübertragung und zu Amazon MFN und Amazon FBA vor.
====

[.instruction]
Konto erstellen:

. Öffne das Menü *Einrichtung » Märkte » Amazon » Einstellungen*.
. Klicke auf *Neues Konto*. +
→ Das Fenster *Neues Amazon Seller Central-Konto erstellen* wird geöffnet.
. Wähle aus der Dropdown-Liste eine *Amazon-Plattform* aus.
. Gib die *E-Mail-Adresse* ein, die du für die Plattform verwendest. +
*_Wichtig:_* Alle plentymarkets E-Mail-Adressen, über die du Nachrichten an Amazon schickst, müssen vorher bei Amazon im Seller Central-Bereich autorisiert werden.
. Klicke auf *Neues Konto erstellen*. +
→ Das Konto wird erstellt.
. Klicke links in der Kontoübersicht auf das neu erstellte Konto. +
→ Das Tab *Einstellungen* für dieses Konto wird geöffnet.
. Nimm die Einstellungen im Tab *Einstellungen* vor. Beachte dabei die Erläuterungen in <<#amazon-tab-einstellungen>>. +
*_Hinweis:_* Alle Angaben im Bereich *Zugangsdaten* sind Pflichtangaben.
. Speichere (terra:save[]) die Einstellungen.

[[amazon-tab-einstellungen]]
.Einstellungen für *Zugangsdaten*
[cols="1,3a"]
|===
| Einstellung | Erläuterung

| *Amazon-Plattform*
| Eine Plattform muss direkt beim Erstellen gewählt werden und kann hier geändert werden. Wenn du ein europäisches Verkäuferkonto hast, kannst du für jede Plattform, auf der du verkaufen möchtest, eigene Einstellungen vornehmen. Weitere Informationen dazu findest du im Abschnitt <<#300, Amazon-Benutzerkonto einrichten>>.

| *Verkäufer-ID*
| Verkäufer-ID eingeben, wie von Amazon erhalten. Wenn du ein europäisches Verkäuferkonto hast, ist die Verkäufer-ID für jede Plattform gleich.

| *Zugriff erlauben*
| Über diese Schaltfläche gibst du plentymarkets Zugriff auf dein Amazon-Konto, damit Daten zwischen Amazon und plentymarkets ausgetauscht werden können. Du kannst den Zugriff entweder sofort erlauben oder erst später, wenn du das Konto aktivierst.

. Klicke auf die Schaltfläche *Zugriff erlauben*. +
→ Du wirst zu Amazon weitergeleitet.
. Gib dort die Zugangsdaten deines Amazon-Verkäuferkontos ein, um dich anzumelden. +
→ Es wird angezeigt, auf welche Amazon-Daten plentymarkets zugreifen darf.
. Klicke auf *Confirm*, um den Zugriff zu erlauben. +
→ In plentymarkets wird das Fenster *Autorisierung abschließen* geöffnet.
. Klicke auf *Abschließen*.

| *Händler-Token*
| Händler-Token eingeben, wie im Seller Central zu finden.

| *E-Mail-Adresse*
| E-Mail-Adresse eingeben, die als Benutzername zum Seller Central-Konto verwendet wird. +
*_Wichtig:_* Alle plentymarkets E-Mail-Adressen, über die du Nachrichten an Amazon schickst, müssen zuvor bei Amazon im Seller Central-Bereich autorisiert werden.

| *Aktiv*
| Häkchen setzen, um die Schnittstelle zu aktivieren. +
*_Hinweis:_* Aktiviere die Schnittstelle erst, wenn du die Amazon-Schnittstelle komplett eingerichtet hast. Sonst werden schon im Vorfeld unerwünscht Daten zu Amazon übertragen.

| *B2B*
| Durch Aktivieren wird dieses Konto für Amazon Business aktiviert.

2+^| Bereich *Basiseinstellungen*

| *Mandant*
| Mandant wählen, für den Aufträge von Amazon zugeordnet werden.

| *SKU-Aufbau*
| Die SKU (Stock Keeping Unit) ist eine eindeutige Referenznummer für alle Artikel und Artikelvarianten bei Amazon. +
Eine der folgenden Optionen wählen: +
*Varianten-ID* +
*GTIN wenn vorhanden, sonst Varianten-ID* +
*Variantennummer wenn vorhanden, sonst Varianten-ID* +
Die hier gewählte Einstellung greift nur für Artikel, die zum ersten Mal zu Amazon exportiert werden. SKUs sind die Basis, auf der Amazon und plentymarkets Daten austauschen. +
*_Wichtig:_* Wenn du bereits auf Amazon verkaufst und nun anfangen möchtest, deine Artikel über plentymarkets auf Amazon zu verkaufen, ordne deine bestehenden SKU-Nummern im Menü *Artikel » Artikel bearbeiten » [Artikel öffnen] » [Variante öffnen] » Varianten-Tab: Einstellungen » Tab: Verfügbarkeit* zu.

| *Katalog wurde mit SSW gelistet*
a| * *Ja* = Artikel werden auf Amazon mit link:https://ssw.starsellersworld.com/[starsellersworld^] gelistet. Beim Auftragsimport wird dann die SKU des Artikels nach dem letzten "-" abgeschnitten, um eine Zuordnung des Artikels im System zu ermöglichen. +
* *Nein* = Artikel werden auf Amazon nicht mit starsellersworld gelistet.

| *Rechnung erzeugen*
a| Wählen, ob Rechnungen von plentymarkets oder Amazon erzeugt werden sollen. Siehe auch <<#6800, Rechnungserzeugung für Amazon-Aufträge einrichten>>. +
*_Hinweis:_* Aktiviere die Option *VCS plentymarkets* (VCS Lite) oder *VCS Amazon*, wenn du Amazon Business nutzen möchtest. +

* *plentymarkets* = Rechnungen werden von plentymarkets erzeugt und die Umsatzsteuer von plentymarkets errechnet. Die Rechnungen lädst du mit einer Ereignisaktion über Amazon IDU bei Amazon hoch. Siehe <<#3175, Amazon IDU nutzen>>. +
* *VCS plentymarkets* (VCS Lite) = Rechnungen für Amazon-Aufträge werden automatisch von plentymarkets erzeugt und zu Amazon übertragen. Die Umsatzsteuer wird von Amazon berechnet. Amazon nennt diese Option VCS Lite. Siehe <<#3150, VCS plentymarkets nutzen>>. +
*_Hinweis:_* In Amazon Seller Central muss VCS aktiviert sein. +
* *VCS Amazon* = Rechnungen für Amazon-Aufträge werden von Amazon erzeugt. +
Rechnungen für Amazon-Aufträge und Gutschriften werden in plentymarkets importiert. Siehe <<#6900, VCS Amazon nutzen>>. +
*_Hinweis:_* In Amazon Seller Central muss VCS aktiviert sein.
|===

[TIP]
.SKU-Einstellungen und Warenbestandsabgleich
====
Wenn du bei allen Plattformen die gleichen Einstellungen für SKU-Nummern wählst, kannst du mit einem Warenbestandsabgleich alle Plattformen des europäischen Verkäuferkontos abgleichen. Wenn die Einstellungen unterschiedlich sind, muss der Abgleich für jede Plattform separat durchgeführt werden.

Der Warenbestand bei einem Europäischen Verkäuferkonto wird aber global verwaltet. Deshalb genügt es, beim Heimat-Marktplatz den Bestand zu aktivieren. Voraussetzung dafür ist die Übereinstimmung der SKU-Einstellungen.
====

[#501]
====  Artikeleinstellungen vornehmen

Im Tab *Artikeleinstellungen* nimmst du Einstellungen zum Artikelexport vor. Du legst u.a. Automatismen und Exportfilter fest. Wenn du Exportfilter einstellst, werden nur Artikel mit den gewählten Filtern exportiert.

In diesem Video-Tutorial erhältst du weitere Informationen zu den verschiedenen Artikeleinstellungen:

.Amazon-Artikeleinstellungen
video::199993489[vimeo]

[.instruction]
Artikeleinstellungen vornehmen:

. Öffne das Menü *Einrichtung » Märkte » Amazon » Einstellungen*.
. Klicke links in der Kontenübersicht auf das Konto.
. Nimm die Einstellungen im Tab *Artikeleinstellungen* vor. Beachte dabei die Erläuterungen in <<#tab-artikeleinstellungen>>.
. Speichere (terra:save[]) die Einstellungen.

[[tab-artikeleinstellungen]]
.Einstellungen im Tab *Artikeleinstellungen*
[cols="1,3a"]
|===
| Einstellung | Erläuterung

2+^| Automatismen

| *Artikelexport*; +
*Preisänderungen*; +
*Bestandsabgleich*; +
*Bestandsänderungen*
| Keine Übertragung oder je ein Intervall für die Übertragung wählen.

2+^| Exportfilter

| *Artikelverfügbarkeit*; +
*Export-Kategorien*; +
*BMVD-Export-Kategorien*; +
*Markierung 1*; +
*Markierung 2*; +
*Tags*; +
*Shop-Artikel*
a| Nur Artikel mit den gewählten Filtern werden exportiert. +

* *Artikelverfügbarkeit* = Wenn ein Parent (Hauptartikel) eine nicht freigegebene Verfügbarkeit hat, findet keine Übertragung statt. +
* *Markierung 1* und *2* = Diese Filter greifen nur für den täglichen Export. +
* *Tags* = Es können ein oder mehrere Tags gewählt werden. +
* *Shop-Artikel* = Wenn du den Filter *Nur im Webshop sichtbare Artikel* wählst, müssen die Artikel, die exportiert werden sollen, auch für den Shop aktiviert sein, der für das gewählte Amazon-Konto im Menü *Einrichtung » Märkte » Amazon » Einstellungen » Tab: Einstellungen* für die Option *Mandant* gewählt wurde. Wenn du den Filter *Alle Artikel* wählst, werden alle Artikel exportiert, unabhängig vom gewählten Shop.

2+^| Exporteinstellungen

| *Artikelname*; +
*Artikelbeschreibung*
| Die eingestellten Informationen werden exportiert.

| *HTML-Tags erlauben*
| Die folgenden Tags sind zugelassen: &lt; br &gt;, &lt; b &gt;, &lt; i &gt;, &lt; p &gt; ,&lt; ul &gt;, &lt; li &gt;, &lt; table &gt;, &lt; tr &gt;, &lt; td &gt;, &lt; th &gt;, &lt; tbody &gt; und &lt; strong &gt;.

| *Lagerauswahl*
a| *Bestandsmenge des Vertriebslagers mit aktuell größtem Bestand übertragen*, *Hauptlager des Artikels verwenden*, *Summe der Bestandsmengen aller Vertriebslager übertragen* oder *Lager wählen* für den Export wählen. Bei der Option *Lager wählen* wird direkt darunter die Einstellung *Lager* angezeigt, bei der ein oder mehrere Lager gewählt werden. +
*_Hinweis:_* Seit 19.5.2021 müssen bei Versandanmeldung die Adressdaten des Lagers an Amazon übergeben werden. In Amazon Seller Central werden diese Adressdaten unter *Ship from* angezeigt. Achte deshalb darauf, dass für die Versandlager, aus denen du Amazon-Aufträge bedienst, im Menü *Einrichtung » Waren » Lager » [Lager öffnen] » Einstellungen* die Adressdaten des Lagers gespeichert sind.

| *Lager*
| Ein oder mehrere Lager wählen. Diese Einstellung wird nur angezeigt, wenn unter Lagerauswahl die Option *Lager wählen* gewählt wurde. +
Die Bestände der gewählten Lager werden summiert und zu Amazon übermittelt. Dabei werden auch Puffer und Maximalwerte berücksichtigt. Somit können auf bestimmten Amazon-Konten oder Amazon-Plattformen gezielt die Bestände gewisser Lager angeboten werden. +
Wenn unter *Lagerauswahl* die Option *Lager wählen* gewählt wurde, aber kein Lager gewählt wurde, wird der Artikel nicht exportiert, da kein Bestand ermittelt werden kann.

| *Bestandspuffer*
| Ist der Artikel auf Netto-Warenbestand beschränkt, wird der exportierte Bestand um den eingegebenen Wert verringert.

| *Maximaler Warenbestand*
| Bestimmt die obere Grenze des exportierten Bestands für alle Artikel. Diese Einstellung hat Priorität vor der unten beschriebenen Einstellung *Menge für Artikel ohne Bestandsbindung*.

| *Menge für Artikel ohne Bestandsbindung*
| Bei Artikeln mit der Einstellung *keine Beschränkung* wird der Maximalwert aus realem Bestand und der hier definierten Menge übermittelt. +
*_Beispiel:_* Einstellung 0, Nettowarenbestand 8. plentymarkets übermittelt 8. +
Artikel mit der Einstellung *Beschränkung auf Netto-Warenbestand* werden hier nicht berücksichtigt.

| *Durchschnittliche Lieferzeit*
| *Nicht übertragen*, *"Mittlere Lieferzeit in Tagen" übermitteln* oder *"Mittlere Lieferzeit in Tagen" übermitteln + Lieferverzugsaufschlag* wählen.

| *Bearbeitungszeit*
| Lieferverzugsaufschlag in Tagen eingeben. Wird nur angezeigt, wenn bei *Durchschnittliche Lieferzeit* die Option *"Mittlere Lieferzeit in Tagen" übermitteln + Bearbeitungszeit* gewählt wurde.

| *Verlängerte Bearbeitungszeit aktivieren*
| *Ja* wählen, um die maximale Bearbeitungszeit von Amazon-Aufträgen von 30 auf bis zu 120 Tage zu erhöhen. +
*_Hinweis:_* Diese Einstellung kann nur aktiviert werden, nachdem du auf Amazon dafür freigeschaltet wurdest. +
Hier wird standardmäßig *Nein* übertragen.

| *Artikelnummer des Herstellers*
| Wählen, ob SKU, Variantennummer, GTIN, Varianten-ID, Externe Varianten-ID, Modellnummer oder kein Wert im Feld part_number der CSV-Datei übertragen werden soll.

| *Zusätzliche SKU*
| Datenaustausch für zusätzliche Amazon-SKUs aktivieren. +
*ALLE*, *Bestandsabgleich*, oder *Preisabgleich* für xref:maerkte:varianten-vorbereiten.adoc#760[zusätzliche SKUs] aktivieren.
|===

[#600]
==== Auftragseinstellungen vornehmen

Im Tab *Auftragseinstellungen* nimmst du Einstellungen zum Versand vor.

Das Kürzel MFN steht für merchant-fulfilled network, d.h. Händler:innen wickeln den Kauf ab.
//tag::amazon-mfn-video[]
Weitere Informationen zum Händlerversand findest du in diesem Video-Tutorial:

.Amazon MFN
video::304534064[vimeo]
//end::amazon-mfn-video[]

[.instruction]
Auftragseinstellungen vornehmen:

. Öffne das Menü *Einrichtung » Märkte » Amazon » Einstellungen*.
. Klicke links in der Kontenübersicht auf das Konto.
. Nimm die Einstellungen im Tab *Auftragseinstellungen* vor. Beachte dabei die Erläuterungen in <<#tab-auftragseinstellungen>>.
. Speichere (terra:save[]) die Einstellungen.

[[tab-auftragseinstellungen]]
.Einstellungen im Tab *Auftragseinstellungen*
[cols="1,3a"]
|===
| Einstellung | Erläuterung

2+^| Eigener Versand (MFN)

| *Auftragsimport*
| Keine Übertragung oder je ein Intervall für den Import wählen.

| *Auftragsimport Startdatum*
| Datum eingeben. Es werden nur Aufträge ab diesem Datum in plentymarkets importiert. +
*_Hinweis:_* Jeder in plentymarkets importierte Auftrag wird abgerechnet.

| *Versandbestätigung*
| Keine Übertragung oder je ein Intervall für den Export der Versandbestätigung an Amazon wählen.

| *Auftragsposition*
| Bestimmt die Darstellung des Artikelnamens in der Auftragsposition. Eine der folgenden Optionen wählen:

* *Artikelname aus Shop übernehmen*
* *Artikelname von Amazon übernehmen - mit SKU*
* *Artikelname von Amazon übernehmen - ohne SKU*

| *Zahlungseingang*
| *Zahlungseingang gebucht* wählen, wenn der Zahlungseingang beim Import von MFN- und FBA-Aufträgen als gebucht angezeigt werden soll. +
*_Hinweis:_* Diese Einstellung greift bei eigenem Versand (MFN) und bei Versand durch Amazon (FBA).

| *Status für übertragene Retouren*
|xref:auftraege:auftraege-verwalten.adoc#1200[Auftragsstatus] für Retouren wählen, die erfolgreich an Amazon gemeldet wurden.

| *Status für nicht übertragene Retouren*
|xref:auftraege:auftraege-verwalten.adoc#1200[Auftragsstatus] für Retouren wählen, die nicht erfolgreich an Amazon gemeldet wurden.

| *Ausstehende Aufträge*
| Wählen, ob ausstehende Aufträge von Amazon alle 15 Minuten importiert werden sollen, oder nie.

| *Gutschriftenimport*
| Wählen, ob Amazon-Gutschriften für MFN- und FBA-Aufträge in dein plentymarkets System importiert werden sollen. +

[cols="1,3a"]
!===
! *Nein* (Standard)
! Gutschriften werden nicht importiert. Wenn du *Nein* wählst, erstelle eine Ereignisaktion, um Retouren als Gutschriften in dein plentymarkets System zu importieren.

! *Ja*
! Amazon-Gutschriften werden alle 4 Stunden in dein plentymarkets System importiert.
!===

*_Hinweis:_* Diese Einstellung greift bei eigenem Versand (MFN) und bei Versand durch Amazon (FBA).

2+^| Versand durch Amazon (FBA)

| *Aktiv*
| Häkchen setzen, um den Versand durch Amazon zu aktivieren.

| *Herkunft*
| Wählen, ob nur Aufträge von Amazon mit FBA abgewickelt werden oder ob auch Aufträge von anderen xref:auftraege:auftragsherkunft.adoc#[Herkünften] mit FBA abgewickelt werden können.

| *Status*
|xref:auftraege:auftraege-verwalten.adoc#1200[Status] der Aufträge wählen, die von Amazon importiert wurden.

| *Lager*
| Wählen, welches Amazon FBA-Lager für den Bestandsabgleich des Kontos verwendet werden soll. Dieses Lager wird auch für die FBA-Auftragszuordnung des Kontos verwendet, falls kein FBA-Auftrag aufgrund eines nicht eingerichteten Lagers für das Auftragsland zugeordnet werden konnte.

| *Lager für unverkäuflichen Bestand*
| Wählen, in welches Amazon FBA-Lager unverkäuflicher Bestand des Kontos gebucht werden soll. Wenn du kein Lager wählst, wird der unverkäufliche Bestand nicht importiert. +
Der unverkäufliche Bestand ist die Anzahl der Einheiten einer SKU, die sich in Amazon-Logistikzentren befinden und den Zustand "nicht verkaufbar" haben. Im Bericht "Lagerbestand mit Versand durch Amazon" entspricht das der Menge in der Spalte *afn-unsellable-quantity*. +

*_Hinweis:_* Wähle für diese Einstellung nicht das gleiche Lager, das du bereits für die Einstellung *Lager* (FBA-Lager) gewählt hast, da die Bestände ansonsten überschrieben werden.

| *Warenausgang*
| Wählen, ob der Warenausgang als gebucht markiert werden soll oder nicht. Die Option *Als gebucht markieren* erzeugt keine Warenbewegung. Um eine Warenbewegung zu erzeugen, muss die Option *Nicht als gebucht markieren* eingestellt sein und eine Ereignisaktion eingerichtet werden.

| *Retourenimport*
| Keine Übertragung oder *täglichen* Import von Retouren wählen.

| *Gutschein bei Retouren berücksichtigen*
| Wählen, ob Gutscheine bei Retouren berücksichtigt werden sollen oder nicht. Wurde der FBA-Auftrag komplett oder teilweise mit einem Gutschein beglichen, wird der Gutschein bei der Retoure hinzugefügt und verrechnet. Dabei wird kein Mindestbestellwert für den Gutschein berücksichtigt.

| *Bestandsimport*
| Wählen, ob der Bestandsimport *stündlich* oder nie ausgeführt werden soll.

| *Status für übertragene Aufträge*
|xref:auftraege:auftraege-verwalten.adoc#1200[Auftragsstatus] für Aufträge wählen, die erfolgreich an FBA übertragen wurden.

| *Artikelrabatte aus Kampagnen beim Import ignorieren*
| Aus Amazon-Bestellberichten geht nicht hervor, ob Artikelrabatte eines Auftrags von der Händler:in oder von Amazon gewährt wurden. Beim Import wird in beiden Fällen der Rabattbetrag vom Auftragswert abgezogen. Wenn Amazon den Rabatt gibt, weichen dann aber der Auftragswert und der von Amazon an dich ausgezahlte Betrag voneinander ab. In solchen Fällen musst du den Auftrag manuell anpassen, da du sonst zu wenig Umsatzsteuer für den Auftrag abführst.

Wählen, wie Rabatte auf Artikel beim Import von Aufträgen behandelt werden sollen.

[cols="1,3a"]
!===
! *Nein* (Standardeinstellung)
! Der Rabattbetrag wird importiert. Wenn der Rabatt von Amazon gewährt wurde, muss der Auftrag manuell angepasst werden.

Ablauf bei Rabatt von Amazon:

* Eine Kundin kauft einen deiner Artikel für 10,00 Euro.
* Amazon gibt der Kundin einen Rabatt von 1,00 Euro.
* Der Auftrag wird mit einem Auftragswert von 9,00 Euro importiert.
* Amazon zahlt dir 10,00 Euro aus. +
→ Den Auftragswert und der Betrag, den Amazon an dich auszahlt, stimmen nicht übereinstimmen. Der Auftrag muss manuell korrigiert werden.

Ablauf bei Rabatt von Händler:in:

* Eine Kundin kauft einen deiner Artikel für 10,00 Euro.
* Du gibst der Kundin einen Rabatt von 1,00 Euro.
* Der Auftrag wird mit einem Auftragswert von 9,00 Euro importiert.
* Amazon zahlt dir 9,00 Euro aus. +
→ Alle Summen sind korrekt.

! *Ja*
! Der Rabattbetrag wird beim Import vom Auftragswert abgezogen. Diese Einstellung wird für Händler:innen empfohlen, die selbst keine Rabattkampagnen auf Amazon-Plattformen fahren. Wenn der Rabatt von der Händler:in gewährt wurde, muss der Auftrag manuell angepasst werden.

Ablauf bei Rabatt von Amazon:

* Eine Kundin kauft einen deiner Artikel für 10,00 Euro.
* Amazon gibt der Kundin einen Rabatt von 1,00 Euro.
* Amazon zahlt dir 10,00 Euro aus.
* Der Auftrag wird mit einem Auftragswert von 10,00 Euro importiert. +
→ Alle Summen sind korrekt.

Ablauf bei Rabatt von Händler:in:

* Eine Kundin kauft einen deiner Artikel für 10,00 Euro.
* Du gibst der Kundin einen Rabatt von 1,00 Euro.
* Der Auftrag wird mit einem Auftragswert von 10,00 Euro importiert.
* Amazon zahlt dir 9,00 Euro aus. +
→ Den Auftragswert und der Betrag, den Amazon an dich auszahlt, stimmen nicht übereinstimmen. Der Auftrag muss manuell korrigiert werden.

*_Hinweis:_* Um die Beispiele zu vereinfachen werden die Gebühren, die du an Amazon zahlst, nicht berücksichtigt.
!===

| *Rabatte aus Versandkampagnen ignorieren*
| Aus Amazon-Bestellberichten geht nicht hervor, ob Versandrabatte eines Auftrags von der Händler:in oder von Amazon gewährt wurden. Beim Import wird in beiden Fällen der Rabattbetrag vom Auftragswert abgezogen. Wenn Amazon den Rabatt gibt, weichen dann aber der Auftragswert und der von Amazon an dich ausgezahlte Betrag voneinander ab. In solchen Fällen musst du den Auftrag manuell anpassen, da du sonst zu wenig Umsatzsteuer für den Auftrag abführst.

Wählen, wie Rabatte auf die Versandkosten beim Import von Aufträgen behandelt werden sollen.

[cols="1,3a"]
!===
! *Nein* (Standardeinstellung)
! Der Rabattbetrag wird importiert. Wenn der Rabatt von Amazon gewährt wurde, muss der Auftrag manuell angepasst werden.

Ablauf bei Rabatt von Amazon:

* Eine Kundin kauft einen deiner Artikel für 10,00 Euro plus 3,00 Euro Versandkosten.
* Amazon schenkt der Kundin die Versandkosten.
* Der Auftrag wird mit einem Auftragswert von 10,00 Euro plus 3,00 Euro Versandkosten importiert.
* Amazon zahlt dir 13,00 Euro aus. +
→ Den Auftragswert und der Betrag, den Amazon an dich auszahlt, stimmen nicht übereinstimmen. Der Auftrag muss manuell korrigiert werden.

Ablauf bei Rabatt von Händler:in:

* Eine Kundin kauft einen deiner Artikel für 10,00 Euro plus 3,00 Euro Versandkosten.
* Du schenkst der Kundin die Versandkosten.
* Der Auftrag wird mit einem Auftragswert von 10,00 Euro plus 3,00 Euro Versandkosten importiert.
* Amazon zahlt dir 13,00 Euro aus. +
→ Alle Summen sind korrekt.

! *Ja*
! Der Rabattbetrag wird beim Import vom Auftragswert abgezogen. Diese Einstellung wird für Händler:innen empfohlen, die selbst keine Rabattkampagnen auf Amazon-Plattformen fahren. Wenn der Rabatt von der Händler:in gewährt wurde, muss der Auftrag manuell angepasst werden.

Ablauf bei Rabatt von Amazon:

* Eine Kundin kauft einen deiner Artikel für 10,00 Euro plus 3,00 Euro Versandkosten.
* Amazon schenkt der Kundin die Versandkosten.
* Der Auftrag wird mit einem Auftragswert von 10,00 Euro plus 3,00 Euro Versandkosten importiert.
* Amazon zahlt dir 13,00 Euro aus. +
→ Alle Summen sind korrekt.

Ablauf bei Rabatt von Händler:in:

* Eine Kundin kauft einen deiner Artikel für 10,00 Euro plus 3,00 Euro Versandkosten.
* Du schenkst der Kundin die Versandkosten.
* Der Auftrag wird mit einem Auftragswert von 10,00 Euro plus 3,00 Euro Versandkosten importiert.
* Amazon zahlt dir 13,00 Euro aus. +
→ Den Auftragswert und der Betrag, den Amazon an dich auszahlt, stimmen nicht übereinstimmen. Der Auftrag muss manuell korrigiert werden.

*_Hinweis:_* Um die Beispiele zu vereinfachen werden die Gebühren, die du an Amazon zahlst, nicht berücksichtigt.
!===

| *Artikelpakete Multi-Channel*
| Welche Auftagspositionen sollen für FBA-Multi-Channel-Aufträge an Amazon übertragen werden? +

*_Hintergrund:_* Welche Option du wählst hängt davon ab, wie du Artikelpakete bei Amazon lagerst. Sind alle Paketbestandteile von Artikelpaketen gemeinsam verpackt bei Amazon eingelagert? Oder stellt Amazon die einzelnen Paketbestandteile selbst zu Artikelpaketen zusammen?

[cols="1,2a"]
!===
! *Alle Auftragspositionen übertragen*
! Als Auftragspositionen werden die Paketposition und die Paketbestandteile an Amazon übertragen. +
*_Wichtig: Wähle diese Option nicht. Sonst versendet Amazon möglicherweise Positionen doppelt oder erfüllt den Auftrag nicht._*

! *Nur Paketposition übertragen*
! Nur die Paketposition wird an Amazon übertragen. +
*_Voraussetzung:_* Alle Paketbestandteile des Artikelpakets sind in einer einzigen Verpackung bei Amazon gelagert. Das Artikelpaket hat nur eine SKU. Amazon pickt also nur eine Position.

! *Ohne Paketposition übertragen*
! Nur die Paketbestandteile werden an Amazon übertragen. +
*_Voraussetzung:_* Das Artikelpaket besteht aus einzelnen Artikeln. Bei Amazon sind diese Artikel alle einzeln eingelagert. Jeder Artikel hat eine eigene SKU. Erst durch den Pick-Vorgang wird aus den Einzelartikeln ein Artikelpaket. 
!===

| *Versandkategorie*
| Versandkategorie wählen.

[cols="1,3a"]
!===
! *Standard*
! Normaler Versand

! *Expedited*
! Schnellversand

! *Priority*
! Bevorzugt (schnellster Versand)
!===

| Weitere Einstellungen für FBA
a| Die folgenden Einstellungen befinden sich zwar im Bereich *Eigener Versand (MFN)* weiter oben im Menü, gelten aber auch bei Versand durch Amazon (FBA). Wähle deshalb auch für diese Einstellungen die gewünschten Optionen:

[cols="1,3a"]
!===

! *Zahlungseingang*
! Option *Zahlungseingang gebucht* wählen, wenn der Zahlungseingang beim Import von MFN- und FBA-Aufträgen als gebucht angezeigt werden soll.

! *Gutschriftenimport*
! Wählen, ob Amazon-Gutschriften für MFN- und FBA-Aufträge in dein plentymarkets System importiert werden sollen.

* *Nein* (Standard) = Gutschriften werden nicht importiert. Wenn du *Nein* wählst, erstelle eine Ereignisaktion, um Retouren als Gutschriften in dein plentymarkets System zu importieren. +
* *Ja* = Amazon-Gutschriften werden alle 4 Stunden in dein plentymarkets System importiert.

!===

*_Hinweis:_* Diese Einstellungen greifen bei eigenem Versand (MFN) und bei Versand durch Amazon (FBA).
|===

[#700]
==== Konto aktivieren

Du hast alle Einstellungen vorgenommen? Dann aktiviere jetzt das Konto, um den Datenaustausch mit Amazon zu starten.

Wie du vorgehst hängt davon ab, ob du beim Einrichten des Kontos den Zugriff schon erlaubt hast.

[tabs]
====
Konto aktivieren und Zugriff erlauben::
+
--
[.instruction]
Konto aktivieren und Zugriff erlauben:

. Öffne das Menü *Einrichtung » Märkte » Amazon » Einstellungen » [Konto öffnen]*. +
→ Das Tab *Einstellungen* für dieses Konto wird geöffnet.
. Aktiviere die Option *Aktiv*.
. Klicke auf die Schaltfläche *Zugriff erlauben*. +
→ Du wirst zu Amazon weitergeleitet.
. Gib dort die Zugangsdaten deines Amazon-Verkäuferkontos ein, um dich anzumelden. +
→ Es wird angezeigt, auf welche Amazon-Daten plentymarkets zugreifen darf.
. Klicke auf *Confirm*, um den Zugriff zu erlauben. +
→ In plentymarkets wird das Fenster *Autorisierung abschließen* geöffnet.
. Klicke auf *Abschließen*.
. Speichere (terra:save[]) die Einstellungen.

--
 
Konto aktivieren, wenn Zugriff schon erlaubt wurde::
+
--
[.instruction]
Konto aktivieren, wenn Zugriff schon erlaubt wurde:

. Öffne das Menü *Einrichtung » Märkte » Amazon » Einstellungen » [Konto öffnen]*. +
→ Das Tab *Einstellungen* für dieses Konto wird geöffnet.
. Aktiviere die Option *Aktiv*.
. Speichere (terra:save[]) die Einstellungen.
--
====
