Damit deine Artikel beim Export zum Marktplatz Amazon automatisch in die dort vorhandenen Kategorien einsortiert werden, musst du in plentymarkets bestimmte Informationen in deinen Kategorien eingeben. Amazon stellt dazu Klassifikationslisten bereit, die sogenannten Browse Tree Guides (BTG). Diese Listen im Format MS Excel (.xls) enthalten eindeutige Klassifikationsnummern, die Browse Node IDs, die du deinen plentymarkets Kategorien zuweisen musst. Die Listen sind über das Hilfe-Center im Seller Central abrufbar oder über diesen link:https://sellercentral-europe.amazon.com/gp/help/help-folder.html/?ie=UTF8&itemID=1661[Link^].

Mit der Verwendung der offiziellen Amazon.de Browse Tree Guides stellst du sicher, dass deine Produkte schnell und einfach im Katalog von Amazon.de gefunden werden. Die genannten Klassifikationsnummern bilden die Grundlage für die Produktzuordnung sowohl in der Navigation als auch für die Produktsuche. Angesichts der Vielzahl der bei Amazon.de angebotenen Artikel entscheidet eine eindeutige Zuordnung deiner Artikel zu diesen Browse Node IDs darüber, ob Kund:innen deine Produkte in den entsprechenden Kategorien finden können oder nicht. Nimm dir also für den nächsten Schritt etwas Zeit und wähle die Browse Node IDs sorgfältig aus.

Die Kategorieverknüpfung führst du im Menü *Einrichtung » Märkte » Amazon » Kategorieverknüpfung* durch. In plentymarkets kannst du jeder Artikelkategorie bis zu zwei Amazon-Klassifikationsnummern aus den Browse Tree Guides zuweisen.

Die eingegebenen Werte müssen unbedingt pro Zeile separat verknüpft werden.

Die Kategorieverknüpfungen werden nur für Standard-Kategorien berücksichtigt, die im Menü *Artikel » Artikel bearbeiten » [Artikel öffnen] » Artikel-Tab: Kategorien* des Artikels gewählt wurden.

[.instruction]
Amazon-Kategorien verknüpfen:

. Rufe über diesen link:https://sellercentral-europe.amazon.com/gp/help/help-folder.html/?ie=UTF8&itemID=1661[Link^] das Hilfe-Center im Seller Central auf.
. Wähle die Klassifikationsliste, zum Beispiel Bekleidung.
. Suche in der Spalte *Kategorie* nach der Produktbezeichnung, zum Beispiel Bluse.
. Öffne das Menü *Einrichtung » Märkte » Amazon » Kategorieverknüpfung* in deinem plentymarkets Backend.
. Gib die Browse Node ID aus der Liste in die Tabelle bei der entsprechenden Kategorie ein.
. Klicke auf das *Zahnrad* in der Zeile der Kategorie, um die Verknüpfungen herzustellen.

[IMPORTANT]
.Export der Browse Node ID
====
Die bei der Kategorieauswahl zugeordnete Browse Node ID wird beim Datenexport in das Feld *RecommendedBrowseNode1* übertragen. Das Feld *RecommendedBrowseNode2* wird nur für mehrfach verknüpfte Kategorien verwendet.
====
