Im Menü *Einrichtung » Märkte » Amazon » Neue Einstellungen* richtest du den Marktplatz in plentymarkets ein. +
Du kannst mehrere Amazon-Konten mit unterschiedlichen Einstellungen hinzufügen.

// Konto vs. Amazon-Konto

[#neues-konto]
=== Neues Konto hinzufügen

Füge zuerst ein neues Konto für Amazon hinzu.

[.instruction]
Konto hinzufügen:

. Öffne das Menü *Einrichtung » Märkte » Amazon » Neue Einstellungen*.
. Klicke auf *Neues Konto hinzufügen* (material:add[]). +
→ Das Fenster *Neues Amazon-Konto hinzufügen* wird geöffnet.
. Wähle die *Region* aus der Dropdown-Liste, für die das Amazon-Konto verwendet werden soll.
. Wähle einen oder mehrere *Channels*. +
*_Hinweis:_* Channels sind die einzelnen Verkaufskanäle (Länder, zum Beispiel amazon.de) von Amazon, auf denen du deine Artikel anbietest. Welche Channels verfügbar sind, hängt von der gewählten Region ab.
. Gib einen *Kontonamen* ein. +
*_Hinweis:_* Der Name ist frei wählbar, muss aber eindeutig sein. Du kannst also nicht denselben Namen für verschiedene Konten vergeben.
. Klicke auf *Speichern*. +
→ Eine Ansicht mit weiteren Einstellungen wird geöffnet.
. Nimm die weiteren Einstellungen vor. Beachte dazu die Erläuterungen in <<#grundeinstellungen-amazon>>.
. Speichere (terra:save[]) die Einstellungen.

[[grundeinstellungen-amazon]]
.Einstellungen des Marktplatzes Amazon
[cols="1,3a"]
|===
|Einstellung |Erläuterung

| *Erweiterte Einstellungen*
| Aktivieren, um erweiterte Einstellungen anzuzeigen. +
Erweiterte Einstellungen sind Einstellungen, die du zur Grundeinrichtung deines Amazon-Kontos nicht zwingend benötigst. Diese Einstellungen sind aber dennoch sehr nützlich und wir empfehlen, dass du dir die erweiterten Einstellungen ansiehst, nachdem du die Grundeinstellungen vorgenommen hast. +
Erweiterte Einstellungen gibt es für die Bereiche *MFN*, *FBA* und für die *Channels*.

| material:link[role="blue"] *Verbinden* 
| Das Konto mit einem Amazon-Konto verbinden. +

Wenn du auf material:link[role="blue"] *Verbinden* klickst, wirst du zu Amazon weitergeleitet und in einem neuen Tab wird eine Amazon-Seite geöffnet. Melde dich mit den Zugangsdaten deines Amazon-Verkäuferkontos bei Amazon an und bestätige, dass plentymarkets auf Daten deines Amazon-Kontos zugreifen darf. Wenn der Vorgang abgeschlossen ist und alles geklappt hat, erscheint in plentymarkets die Meldung "Autorisierung erfolgreich abgeschlossen". +

Wenn das Konto mit einem Amazon-Konto verbunden ist, wird hier die Verkäufer-ID des Amazon-Kontos angezeigt. +

Wenn nötig, kann das Konto auch erneut verbunden werden.

2+^| *Konto*

| *Konto*
| Der Name deines Amazon-Kontos. Den Namen hast du beim Erstellen des Kontos eingegeben.

| *Aktiv*
| Amazon-Konto aktivieren. Der Datenaustausch mit Amazon wird gestartet. +

Wir empfehlen, das Konto erst zu aktivieren, nachdem du alle Einstellungen vorgenommen hast.

*_Hinweis:_* Damit Daten zwischen plentymarkets und Amazon ausgetauscht werden können, muss das Konto mit einem Amazon-Konto verbunden sein. Die Verbindung stellst du über die Schaltfläche material:link[role="blue"] *Verbinden* ganz oben im Fenster her.

| *Mandant*
| Mandant (plentyShop) wählen, dem die Aufträge dieses Amazon-Kontos zugeordnet werden sollen.

| *B2B aktivieren*
| Willst du B2B für dieses Amazon-Konto verwenden? Dadurch wird das Konto für Amazon Business aktiviert. Das bedeutet, dass du deine Artikel an gewerbliche Kund:innen verkaufst. +

*_Hinweis:_* Wenn du Amazon Business nutzen willst, benötigst du ein link:https://business.amazon.de/de/funktionen-entdecken/beschaffung-verwalten/kontoverwaltung[Business-Konto^] bei Amazon.

| *MFN aktivieren*
| Willst du MFN für dieses Amazon-Konto verwenden? +
MFN (= Merchant Fulfillment Network) bedeutet, dass du deine Artikel selbst lagerst und selbst an deine Kund:innen versendest.

| *FBA aktivieren*
| Willst du FBA für dieses Amazon-Konto verwenden? +
Bei FBA (= Fulfillment by Amazon) übernimmt Amazon die Lagerung und den Versand deiner Artikel. Natürlich musst du dann zumindest einen Teil deiner Waren auch bei Amazon einlagern.

| *VCS aktivieren*
| Nutzt du den Umsatzsteuer-Berechnungsservice von Amazon (VCS = Vat Calculation Service)? +

Wähle eine der folgenden Optionen: +

* *plentymarkets* = Du nutzt VCS nicht. Rechnungen werden von plentymarkets erzeugt und die Umsatzsteuer von plentymarkets errechnet. Die Rechnungen lädst du mit einer Ereignisaktion über Amazon IDU bei Amazon hoch. Siehe <<#3175, Amazon IDU nutzen>>. +
* *Ja, VCS Lite* = Du nutzt VCS. Rechnungen für Amazon-Aufträge werden automatisch von plentymarkets erzeugt und zu Amazon übertragen. Die Umsatzsteuer wird von Amazon berechnet. Siehe <<#3150, VCS plentymarkets nutzen>>. +
*_Hinweis:_* In Amazon Seller Central muss VCS aktiviert sein. +
* *Ja, VCS* = Du nutzt VCS. Rechnungen für Amazon-Aufträge werden von Amazon erzeugt. +
Rechnungen für Amazon-Aufträge und Gutschriften werden in plentymarkets importiert. Siehe <<#6900, VCS Amazon nutzen>>. +
*_Hinweis:_* In Amazon Seller Central muss VCS aktiviert sein. +

*_Hinweis:_* Aktiviere die Option *VCS Lite* oder *VCS*, wenn du Amazon Business nutzen möchtest.

2+^| *Aufträge*

| *Auftragsimport Startdatum*
| Datum im Format *DD.MM.YYYY* eingeben oder über den Kalender (material:today[]) wählen. +
Es werden nur Aufträge ab diesem Datum in plentymarkets importiert. Aufträge, die früher generiert wurden, werden nicht importiert. +
Beachte aber, dass ältere Aufträge trotzdem noch einmal in plentymarkets importiert werden, wenn sie auf Amazon aktualisiert wurden. +

Diese Einstellung greift bei eigenem Versand (MFN) und bei Versand durch Amazon (FBA).

*_Hinweis:_* Jeder in plentymarkets importierte Auftrag wird abgerechnet.

| *Auftragsimport Startzeit*
| Hier kannst du zusätzlich eine Uhrzeit eingeben oder über (material:schedule[]) wählen. +
Es werden nur Aufträge ab diesem Zeitpunkt in plentymarkets importiert. Aufträge, die früher generiert wurden, werden nicht importiert.

| *Artikelname in Aufträgen*
| Unter welchem Namen sollen Produkte in den Auftragspositionen von Amazon-Aufträgen angezeigt werden? +

*_Mögliche Optionen:_* +
*Standardartikelname des Mandanten*,+
*Artikelname von Amazon - mit SKU*, +
*Artikelname von Amazon - ohne SKU*

| *Gutschriften importieren*
| Aktivieren, um Gutschriften alle 4 Stunden zu importieren. VCS-Gutschriften werden einmal stündlich importiert. +

Diese Einstellung greift bei eigenem Versand (MFN) und bei Versand durch Amazon (FBA).

| *Produkte mit starsellersworld gelistet*
| Listest du deine Produkte mit link:https://www.starsellersworld.com/[starsellersworld^] auf Amazon? Dann aktiviere diese Einstellung. +

Beim Auftragsimport wird dann die SKU des Artikels nach dem letzten "-" abgeschnitten, um eine Zuordnung des Artikels im System zu ermöglichen.
|===

[#konto-uebersicht]
=== Konto-Übersicht

Im Menü *Einrichtung » Märkte » Amazon » Neue Einstellungen* erhältst du eine Übersicht über deine Amazon-Konten. In <<tabelle-konto-uebersicht>> sind die einzelnen Spalten und verfügbaren Aktionen der Konto-Übersicht beschrieben.

[TIP]
.Spalten konfigurieren
====
Über *Spalten konfigurieren* (material:settings[]) kannst du festlegen, welche Einstellungen in der Konto-Übersicht angezeigt werden sollen. +
Standardmäßig werden die Spalten *Kontoname*, *Aktiv*, *Verkäufer-ID*, *Verbunden*, *Mandant*, *B2B*, *MFN*, *FBA* und *VCS* in der Übersicht angezeigt.
====

*_Hinweis:_* Die Konto-Übersicht sieht unterschiedlich aus, je nachdem, welche Spalten du über *Spalten konfigurieren* (material:settings[]) in der Übersicht hinzufügst oder ausblendest. In der folgenden Tabelle sind nur die Spalten beschrieben, die standardmäßig in der Übersicht angezeigt werden.

[TIP]
.Amazon-Konten suchen
====
Wenn du viele Amazon-Konten hast und das gewünschte Konto nicht gleich findest, kannst du das Konto auch über die Suche finden. Gib dazu den *Kontonamen* ein, wähle *Verkäufer-ID* und *Region* und klicke auf *Suchen* (material:search[role="blue"]).
====

[[tabelle-konto-uebersicht]]
.Amazon Konto-Übersicht
[cols="1a,3a"]
|===
|Spalte |Erläuterung

| *Kontoname*
| Der Name deines Amazon-Kontos.

| *Aktiv*
| material:circle[role="blue"] = Das Konto ist aktiv und Daten werden mit Amazon ausgetauscht. +
material:circle[] = Das Konto ist nicht aktiv. Es werden keine Daten mit Amazon ausgetauscht. +

*_Hinweis:_* Der Datenaustausch zwischen plentymarkets und Amazon funktioniert nur, wenn das Konto mit Amazon verbunden wurde. Ob das Konto verbunden ist, siehst du in der Spalte *Verbunden*.

| *Verkäufer-ID*
| Die Verkäufer-ID deines Amazon-Kontos. Die Verkäufer-ID erhältst du von Amazon.

| *Verbunden*
| material:link[role="blue"] = Das Konto ist mit Amazon verbunden. Dadurch kann plentymarkets auf die Daten deines Amazon-Kontos zugreifen. +
material:link_off[] = Das Konto ist nicht mit Amazon verbunden. Es können keine Daten ausgetauscht werden.

| *Mandant*
| Der Mandant (plentyShop), dem die Aufträge dieses Amazon-Kontos zugeordnet werden.

| *B2B*
| material:done[] = Bei diesem Amazon-Konto nutzt du B2B (Verkauf an Geschäftskund:innen). +
material:close[] = B2B wird bei diesem Amazon-Konto nicht genutzt.

| *MFN*
| material:done[] = Bei diesem Amazon-Konto nutzt du MFN (Versand durch Händler:in). +
material:close[] =  MFN wird bei diesem Amazon-Konto nicht genutzt.

| *FBA*
| material:done[] = Bei diesem Amazon-Konto nutzt du FBA (Lagerung und Versand durch Amazon). +
material:close[] = FBA wird bei diesem Amazon-Konto nicht genutzt.

| *VCS*
| material:done[] = Für dieses Amazon-Konto ist der Amazon-Rechnungsservice VCS aktiviert. Du siehst in der Übersicht auch, ob du *VCS* oder *VCS Lite* nutzt. +
material:close[] = VCS ist für dieses Amazon-Konto nicht aktiviert.
|===