[#860]
=== Export von Grundpreisangaben vorbereiten

Die deutsche Grundpreisverordnung schreibt vor, dass für Produkte, die nach Gewicht, Volumen, Länge oder Fläche verkauft werden, der Grundpreis in unmittelbarer Nähe des Endpreises anzugeben ist.

Amazon berechnet den Grundpreis aus dem übermittelten Preis und den Angaben zu Menge und Einheit. Je nach Kategorie erwartet Amazon dabei andere Felder. Informationen dazu, welche Werte für eine Kategorie übermittelt werden müssen, findest du in der Lagerbestandsdateivorlage der Amazon-Kategorie.

* Erstelle eine Eigenschaft für jedes Feld, das Amazon für die Grundpreisangabe deiner Varianten erwartet.
* Verknüpfe die Eigenschaften mit deinen Varianten und speichere Werte für die Varianten.

[#bp-100]
==== Eigenschaften für Grundpreisangaben erstellen

* Du arbeitest zum ersten Mal mit den Eigenschaften? Dann mach dich zuerst <<artikel/einstellungen/eigenschaften#10#, mit dem Prinzip der Eigenschaften vertraut>>.

. Öffne das Menü *Einrichtung » Einstellungen » Eigenschaften » Konfiguration*.
. Klicke auf *icon:plus-square[role="darkGrey"] Eigenschaft erstellen*.
. Nimm die Einstellungen vor. Beachte dazu die Informationen in <<#table-amazon-property-base-price>>.
. Speichere (icon:save[set=plenty]) die Einstellungen.

[#table-amazon-property-base-price]
.Eigenschaft erstellen
[cols="1,2a"]
|===
| Einstellung | Erläuterung

2+| Bereich *Details*

| *Bereich*
| Option *Artikel* wählen.

| *Typ*
| * Für Mengenangaben Option *Kommazahl* wählen.
* Für Maßeinheiten Option *Auswahl* wählen.

2+| Bereich *Namen*

| *Name*
| Name des Amazon-Felds eingeben. +
*_Hinweis:_* Speichere den Namen für alle Sprachen, die für eine Amazon-Plattform genutzt werden.

2+| Bereich *Sichtbarkeiten*

| *Herkunft*
| Gewünschte Amazon-Plattformen aktivieren.

2+| Bereich *Werte*

| *Werte* (nur bei Typ *Auswahl*)
| Werte für die von Amazon erlaubten Maßeinheiten speichern.

2+| Bereich *Amazon*

| *Amazon-Plattform*; +
*Kategorie*; +
*Feld*
| Amazon-Plattform, Kategorie und Feld aus den Dropdown-Listen wählen.

|===

[#bp-200]
==== Grundpreisangaben an Variante speichern

. Öffne das Menü *Artikel » Artikel bearbeiten » [Artikel öffnen] » [Variante öffnen] » Varianten-Tab: Eigenschaften*. +
*_Tipp:_* Um alle Varianten eines Artikels zu verknüpfen, nimm diese Einstellung an der Hauptvariante vor. Die Einstellung wird an alle Varianten des Artikels vererbt.
. Klicke im Bereich *Varianteneigenschaften* in das Feld *Eigenschaften*. +
→ Eine Dropdown-Liste mit den verfügbaren Eigenschaften wird angezeigt.
. Aktiviere die Eigenschaft, die du gerade erstellt hast.
. Klicke auf *Hinzufügen* (icon:plus-square[role="green"]). +
→ Die Eigenschaft wird in der Liste der Eigenschaften angezeigt.
. Wähle in der Spalte *Wert* aus der Dropdown-Liste die Einheit, zum Beispiel *GR*.
. Speichere (icon:save[set=plenty]) die Einstellungen.

[#bp-300]
==== Beispiele für Grundpreisangaben

In den folgenden Beispielen wird beschrieben, wie du das Amazon-Feld für Mengenangaben *item_display_weight* und das Amazon-Feld für Maßeinheiten *item_display_weight_unit_of_measure* erstellst. Beachte jedoch, dass Amazon je nach Kategorie andere Felder erwartet. Informationen dazu, welche Werte für eine Amazon-Kategorie übermittelt werden müssen, findest du in der Lagerbestandsdateivorlage dieser Amazon-Kategorie.

[.collapseBox]
.*_Beispiel:_* Mengenangabe *item_display_weight*
--

* Erstelle eine Eigenschaft *item_display_weight* mit folgenden Einstellungen:
  ** Bereich = Artikel
  ** Typ = Kommazahl
  ** Name = item_display_weight +
  *_Hinweis:_* Speichere den Namen für alle Sprachen, die für eine Amazon-Plattform genutzt werden.
  ** Herkunft = gewünschte Amazon-Plattformen
  ** Amazon-Plattform = gewünschte Amazon-Plattform
  ** Kategorie = gewünschte Kategorie
  ** Feld = item_display_weight
* Verknüpfe die Eigenschaft *item_display_weight* mit den gewünschten Varianten und speichere für jede Variante ein Gewicht.
--

[.collapseBox]
.*_Beispiel:_* Maßeinheit *item_display_weight_unit_of_measure*
--

* Erstelle eine Eigenschaft *item_display_weight_unit_of_measure* mit folgenden Einstellungen:
  ** Bereich = Artikel
  ** Typ = Auswahl
  ** Werte = *KG* für Kilogramm und *GR* für Gramm
  ** Name = item_display_weight_unit_of_measure +
  *_Hinweis:_* Speichere den Namen für alle Sprachen, die für eine Amazon-Plattform genutzt werden.
  ** Herkunft = gewünschte Amazon-Plattformen
  ** Amazon-Plattform = gewünschte Amazon-Plattform
  ** Kategorie = gewünschte Kategorie
  ** Feld = item_display_weight_unit_of_measure
* Verknüpfe die Eigenschaft *item_display_weight_unit_of_measure* mit einer Variante und wähle einen Eigenschaftswert.
--
