Mit der Kennzahl *Marktplatz-Variantenvalidierung* prüfst du, ob die Variantendaten eines Katalogs wichtige Regeln des Marktplatzes {market} erfüllen. Bei der Validierung werden alle Pflichtfelder geprüft, die nicht spezifisch für den Produkttyp sind.

[IMPORTANT]
.Tarif plentyBI XS
====
Du benötigst den Tarif plentyBI *XS*, um die Kennzahl *Marktplatz-Variantenvalidierung* zu nutzen. Um plentyBI Tarife zu buchen, öffne das Menü *plentymarkets Logo (Start) » Mein Konto » Verträge*. Im Bereich *plentyBI Tarif buchen* stehen plentyBI-Tarife mit verschiedenen Umfängen zur Auswahl.
====

ifdef::more-than-one-catalogue[]

Zurzeit kannst du die Exporte für die folgenden {validated-catalogues} prüfen:

{validated-categories}

endif::[]


[IMPORTANT]
.Die Marktplatz-Variantenvalidierung ist neu!
====
Die Marktplatz-Variantenvalidierung ist ein neues Feature. Wir arbeiten mit Hochdruck daran, den Funktionsumfang zu erweitern und weitere Marktplätze validierbar zu machen.
====

:key-figure: Marktplatz-Variantenvalidierung

[#1100]
=== Kennzahl {key-figure} erstellen

include::BI-catalogue-create-key-figure.adoc[]
