Wenn du im Assistenten die Optionen *Verkaufspreis anlegen*, *Barcode anlegen* und/oder *Eigenschaft anlegen* gewählt hast, erstellt der Assistent diese Eigenschaften, Verkaufspreise und/oder Barcodes automatisch. Diese neu erstellten Datenfelder musst du nun noch mit den Varianten verknüpfen, die zum Marktplatz exportiert werden sollen. Wie das geht, ist im Bereich *Artikel* des Handbuchs beschrieben:

* So verknüpfst du <<artikel/einstellungen/preise#240, Verkaufspreise>>.
* So verknüpfst du <<artikel/einstellungen/barcodes#300, Barcodes>>.
* So verknüpfst du <<artikel/einstellungen/eigenschaften#1420, Eigenschaften und speicherst einen Eigenschaftswert>>. +
*_Tipp:_* Eigenschaften, die du über den Assistenten erstellst, werden automatisch im Menü *Einrichtung » Einstellungen » Eigenschaften » Gruppen* zu der Gruppe *{property-group}* hinzugefügt. Öffne diese Gruppe um zu sehen, welche neuen Eigenschaften verknüpft werden müssen.

////
[#quellen-verknuepfen]
== Im Assistenten erstellte Datenfelder mit Varianten verknüpfen

:property-group:

include::../../_textblocks/catalogues/instructions/catalogue-assistant-link-variations.adoc[]
////
