Im Folgenden wird beispielhaft beschrieben, wie du dem Feld *{beispiel-marktplatz-feld}* des Marktplatzes Artikeldaten aus plentymarkets zuordnest.

. Öffne das Menü *Daten » Kataloge*.
. Klicke auf den Katalog. +
→ Der Katalog wird geöffnet.
. Wähle für das Katalogfeld *{beispiel-marktplatz-feld}* ein plentymarkets Datenfeld aus der Dropdown-Liste, zum Beispiel *{beispiel-plenty-feld}*, die auf dem Marktplatz als {beispiel-marktplatz-feld} angezeigt werden soll.

. Speichere (icon:save[set=plenty]) die Einstellungen.


. Öffne das Menü *Daten » Kataloge*.
. Klicke auf den Katalog. +
→ Das Tab *Zuordnung* mit den Marktplatz-Datenfeldern wird geöffnet. +
→ In der linken Spalte werden die Datenfelder des Marktplatzes angezeigt.
. Klicke neben dem Marktplatz-Datenfeld {beispiel-marktplatz-feld} auf *Datenfeld hinzufügen*.
→ Links werden die plentymarkets Datenfelder als Gruppen angezeigt.
. Klicke auf die Gruppe {datenfeld-gruppe}, um die Datenfelder anzuzeigen. +
→ Die Datenfelder werden angezeigt.
. Klicke neben dem gewünschten Datenfeld auf das Plus. +
→ Das Datenfeld wird in der Ansicht hinzugefügt. +
. Klicke auf das X, um den Bearbeitungsmodus zu schließen.
. Nimm die weiteren Zuordnungen analog vor. Ordne mindestens alle Pflichtfelder zu.
. Speichere (icon:save[set=plenty]) die Einstellungen. +
→ Die Zuordnungen werden gespeichert.

////
=== _Beispiel:_ Feld "{beispiel-feld}" zuordnen

:beispiel-marktplatz-feld:
:beispiel-plenty-feld:
:datenfeld-gruppe:

include::../../_textblocks/catalogues/instructions/catalogue-example-fields.adoc[]
////
