Das sogenannte Attribut-Hilfetool ermöglicht es dir, nach den verschiedenen Attributen zu suchen und gibt die aktuell dafür gültigen Werte an. Um das Tool nutzen zu können, muss der Assistent *{assistant-name}* bereits eingerichtet sein.
Das Tool findest du unter der folgenden URL: `domain/{market-attribute-help-tool}_extension/attribute_values`.
Trage anstelle von `domain` deine plenty Domain ein. Würde deine plenty Domain beispielsweise `https://www.meine-plenty-domain.de` lauten, wäre die URL wie folgt aufgebaut: `https://www.meine-plenty-domain.de/{market-attribute-help-tool}_extension/attribute_values`.

Gib `SAP.TaxIndicator` in die Suche des Attribut-Hilfetools ein, um die gültigen Werte für *Umsatzsteuerklasse* und `SAP.BaseUnits`, um die gültigen Werte für *Verkaufsmengeneinheit* zu finden.

[IMPORTANT]
.Ausgabe der Attributwerte am Folgetag
====
Die Tabelle der gültigen Attributwerte wird jeweils über Nacht aktualisiert. Nach dem erstmaligen Installieren des Plugins werden die gültigen Werte erst am Folgetag ausgegeben. +
Wenn du im Assistenten die falsche API-Umgebung und/oder den falschen API-Schlüssel eingetragen hast, können die gültigen Werte nicht geladen werden.
====

Im Katalog findest du die Benennungen der Marktplatzattribute, wie zum Beispiel *Marke*. Um die für ein Attribut gültigen Werte herauszufinden, gehe vor wie folgt.

[.instruction]
Das Attribut-Hilfetool verwenden:

. Rufe die wie oben beschriebene URL auf.
. Gib den Namen des Attributes in die Suche ein oder nutze Strg+F bzw. Cmd+F, um die Ergebnisliste zu durchsuchen. +
→ In der Spalte *Attribute Label* ist das Attribut zu sehen. +
→ In der Spalte *Value Code* sind die gültigen Werte aufgeführt, die für die Attributwerte in der Spalte *Value Label* übertragen werden müssen.

=== Gültige Attributwerte zuordnen und übertragen

Hast du - je nach Variante, die übertragen werden soll - unterschiedliche Attributwerte, die gültig sein könnten, stellt sich zunächst die Frage, über welche Vorgehensweise du deine Artikeldaten aktuell hältst.
Verwaltest du deine Artikeldaten manuell, ist eine Eigenschaft vom Typ *Auswahl* empfehlenswert. Hier kannst du für die Auswahl eine Beschreibung hinterlegen. Diese wird dann in der Übersicht der Eigenschaften an der Variante angezeigt.
Wenn der Code der Eigenschaft zugeordnet wurde, kannst du den realen Namen der Variante im Feld *Beschreibung* verwenden. Das bedeutet, über den Katalog wird dann der Code übertragen und dahinter in Klammern der reale Name angezeigt. +

*_Tipp:_* Wenn du für ein Attribut immer nur einen einzigen Wert übertragen möchtest, z.B. als Marke immer *BRAND_12345678*, kannst du die Option *Eigener Wert* im Katalog verwenden.
