Im Katalog siehst du die Marktplatz-Datenfelder, die du an {market} exportieren kannst. {market} nennt diese Datenfelder auch Attribute. Der Marktplatz erwartet bei den meisten Datenfeldern spezifische Werte. Hierbei hilft dir das *Attribut-Hilfetool*. In diesem Tool gibst du die Datenfelder ein und kannst dir die aktuell gültigen Werte für diese Datenfelder ansehen. Um das Tool zu nutzen musst du den Assistenten *{assistant-name}* abgeschlossen haben.

Das Attribut-Hilfetool findest du unter der URL `[deine-domain]/{market-attribute-help-tool}/attribute_values`. +
Gib anstelle von `[deine-domain]` deine plentymarkets Domain ein. +
*_Beispiel:_* Bei der plentymarkets Domain `\https://www.meine-plenty-domain.de` lautet die vollständige URL `\https://www.meine-plenty-domain.de/{market-attribute-help-tool}_extension/attribute_values`. +
*_Fehlerbehebung:_* Du kannst nicht auf das Attribut-Hilfetool zugreifen und sieht stattdessen *Hier entsteht dein plentymarkets Shop*? +
Wahrscheinlich ist dein plentyShop gesperrt. Entsperre den plentyShop im Menü *Einrichtung » Mandant » Global » Webshop » Shop sperren*. Vergiss nicht, den plentyShop danach wieder zu sperren.

* Gib `SAP.TaxIndicator` in die Suche des Attribut-Hilfetools ein, um die gültigen Werte für *Umsatzsteuerklasse* zu finden. +
* Gib `SAP.BaseUnits` in die Suche des Attribut-Hilfetools ein, um die gültigen Werte für *Verkaufsmengeneinheit* zu finden.

Um die gültigen Werte für ein Datenfeld herauszufinden, gehe wie unten beschrieben vor.

[.instruction]
Attribut-Hilfetool nutzen:

. Gib die folgende URL in deinen Browser ein: +
  * `[deine-domain]/{market-attribute-help-tool}_extension/attribute_values`
. Ersetze `[deine-domain]` durch deine plentymarkets Domain. +
*_Beispiel:_* Bei der plentymarkets Domain `\https://www.meine-plenty-domain.de` lautet die URL `\https://www.meine-plenty-domain.de/{market-attribute-help-tool}_extension/attribute_values`.
. Gib den Namen des Datenfelds in die Suche ein oder nutze Strg+F oder Cmd+F, um die Ergebnisliste zu durchsuchen. +
→ In der Spalte *Attribute Label* steht das Datenfeld. +
→ In der Spalte *Value Code* stehen die Werte, die für das Datenfeld übertragen werden können.

=== Tipp: Gültige Werte zuordnen

Die meisten Attributwerte von {market} sind Codes und deshalb eher kryptisch. Ein gutes Beispiel sind die Marken. Hier wird der Code nach dem Muster `BRAND_12345678` gebildet. Damit du trotzdem den Überblick behältst und die Werte bequem mit deinen Varianten verknüpfen kannst, empfehlen wir dir das folgende Vorgehen:

* Erstelle eine Eigenschaft vom Typ *Auswahl*.
* Speichere die Codes als Auswahlwerte.
* Speichere den Klarnamen des Codes im Feld *Beschreibung* des Werts.
* Verknüpfe die Eigenschaft mit der Variante.
* Klicke in der Spalte *Wert* auf die Dropdown-Liste. +
→ In der Liste der Werte wird hinter dem Code die Beschreibung in Klammern angezeigt. +
→ Über den Katalog wird nur der Code übertragen.

*_Tipp:_* Wenn du für jede Variante denselben Wert übertragen möchtest, kannst du statt einer Eigenschaft auch die Option *Eigener Wert* im Katalog verwenden.
