Nachdem du mit dem Assistenten *{assistant-name} Catalog* oder manuell ein Marktplatz-Format für {market} erstellt hast, wird in deinem plentymarkets System die Eigenschaft *{market}* erstellt. Für jede Kategorie, die du im ersten Schritt *Einstellungen* des Assistenten wählst, wird die gewählte Kategorie als neuer Auswahlwert zur Eigenschaft *{market} Kategoriegruppe* hinzugefügt. Damit deine Varianten im gewünschten Katalog exportiert werden, müssen sie im Tab *Eigenschaften* einer Variante mit der Eigenschaft *{market} Kategoriegruppe* verknüpft werden.

[.instruction]
Variante mit Kategorie verknüpfen:

. Öffne das Menü *Artikel » Artikel bearbeiten » [Artikel öffnen]*.
. Wechsele in das *Tab: Varianten*.
. Öffne die Variante, die du verknüpfen möchtest.
. Wechsele in das *Tab: Eigenschaften*.
. Wähle im Bereich *Varianteneigenschaften* aus der Dropdown-Liste *Eigenschaften* die Eigenschaft *{market} Kategoriegruppe* und klicke auf *Hinzufügen* (icon:plus-square[role="green"]). +
→ Die Eigenschaft wird hinzugefügt.
. Wähle für die Eigenschaft *{market} Kategoriegruppe* aus der Dropdown-Liste *Wert* die gewünschte Kategorie. +
→ Die Variante wird im zugehörigen Katalog exportiert. +
*_Beispiel:_* Wählst du den Wert *{category-example}*, wird die Variante im Katalog für die Kategorie *{category-example}* exportiert.
. Wiederhole die Schritte 5 und 6 für alle Kategorien, in denen du die Variante verkaufen willst.
. Speichere (icon:save[set=plenty]) die Einstellungen.

[discrete]
=== Weitere Möglichkeiten zum Verknüpfen

* per Import: Über *Einrichtung » Einstellungen » Eigenschaften » Konfiguration* die Eigenschaft *{assistant-name} Kategoriemapping* aufrufen und auf *Werte* klicken. Dort sind die Auswahlwert-IDs, die für den Import notwendig sind, zu finden.
* per REST-API: Verwende dazu die REST-Routen aus den Bereichen link:https://developers.plentymarkets.com/en-gb/plentymarkets-rest-api/index.html#/Property[Property^]{nbsp}icon:external-link[] und link:https://developers.plentymarkets.com/en-gb/plentymarkets-rest-api/index.html#/Item[Item^]{nbsp}icon:external-link[], um den Katalog mit der Variante zu verknüpfen. +
*_Hinweis_*: Steht im Assistenten *{assistant-name} Catalog* keine Marktplatzkategorie zur Auswahl, dann ist im Assistenten *{assistant-name}* im Schritt *Authentifizierung* ggf. die falsche API-Umgebung ausgewählt.
