Die Aufträge werden alle 15 Minuten in dein plentymarkets System importiert.
ifdef::voelkner[]
Nachdem Voelkner den Auftrag akzeptiert hat, wird die Zahlung von Voelkner eingezogen.
endif::voelkner[]
ifdef::conrad,mediamarkt[]
Der Auftrag wird vom Händler über eine Ereignisaktion akzeptiert. Die Zahlung wird von {market} eingezogen.
endif::conrad,mediamarkt[]
Mit der Zahlungszusicherung werden die Rechnungs- und Lieferadresse am Auftrag in deinem plentymarkets System aktualisiert. Über eine Ereignisaktion wird der Versanddienstleister sowie die Paketnummer am Auftrag in Mirakl aktualisiert.
ifdef::conrad,voelkner[]
Im nächsten Schritt wird über eine weitere Ereignisaktion die Versandbenachrichtigung an {market} gemeldet. Die von {market} erstellte Rechnung wird zum Auftrag in dein plentymarkets System importiert.
endif::conrad,voelkner[]
ifdef::mediamarkt,voelkner[]
Über eine Ereignisaktion wird eine Rechnung an {market} gesendet.
endif::mediamarkt,voelkner[]
ifdef::conrad,mediamarkt[]
Du kannst dir ebenfalls Ereignisaktionen für Rückerstattungen und Stornierung von Aufträgen einrichten.
endif::conrad,mediamarkt[]
ifdef::voelkner[]
Du kannst dir ebenfalls Ereignisaktionen für Rückerstattungen von Aufträgen einrichten.
endif::voelkner[]

[#ereignisaktionen]
== Ereignisaktionen einrichten

Richte eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um den Auftragsstatus bei {market} automatisch zu aktualisieren, wenn bestimmte Ereignisse eintreten. Folgende Ereignisaktionen können eingerichtet werden:

ifdef::EP-order-confirmation[]
* Auftragsbestätigung an {market} melden
endif::EP-order-confirmation[]
ifdef::EP-order-rejection[]
* Auftragsablehnung an {market} melden
endif::EP-order-rejection[]
ifdef::EP-shipping-confirmation[]
* Versandbestätigung an {market} melden
endif::EP-shipping-confirmation[]
ifdef::EP-cancellation[]
* Auftragsstornierung an {market} melden
endif::EP-cancellation[]
ifdef::EP-refund[]
* Rückerstattung an {market} melden
endif::EP-refund[]
ifdef::EP-send-invoice[]
* Rechnung an {market} senden
endif::EP-send-invoice[]

In den folgenden Kapiteln wird beschrieben, wie du die Ereignisaktionen in plentymarkets einrichtest.

[IMPORTANT]
.Weitere Aktionen vorhanden
====
Zusätzlich zu den oben genannten Ereignisaktionen werden durch das {market}-Plugin noch weitere Ereignisaktionen zu Verfügung gestellt. Es gibt diese Aktionen, da sich die Auftragsverarbeitung in plentymarkets und Mirakl voneinander unterscheiden.

Wir empfehlen allerdings, nur die Aktionen zu verwenden, die hier im Detail beschrieben sind.
====
