Beim Katalogexport werden Eigenschaften verwendet, um Datenfelder an den Marktplatz zu übergeben, für die es in plentymarkets keine eigene Einstellung gibt. Dazu erstellst du eine Eigenschaft und verknüpfst diese anschließend im Katalog mit dem Datenfeld des Marktplatzes.

[.collapseBox]
.Was ist eine Eigenschaft?
--
Mit Eigenschaften kannst du deine Varianten detailliert beschreiben. Du kannst beispielweise technische Details einer Variante angeben, indem du eine Eigenschaft dafür anlegst, wie zum Beispiel die Eigenschaft _Bluetooth_ für Kopfhörer. +
Außerdem kannst du Eigenschaften verwenden, um Informationen an einer Variante zu speichern, die ein Marktplatz verlangt, für die es aber keine eigene Einstellung in plentymarkets gibt. So kannst du beim Artikelexport über Kataloge für alle Datenfelder des Marktplatzes, für die es in plentymarkets keine eigene Einstellung gibt, Eigenschaften anlegen und mit den Datenfeldern verknüpfen. Wenn der Marktplatz zum Beispiel bestimmte Spezifikationen für Kontaktlinsen verlangt, kannst du diese mit Eigenschaften angeben. +
Du willst noch mehr über Eigenschaften wissen? Weitere Informationen findest du auf der Seite xref:artikel:eigenschaften.adoc#500[Merkmale und Eigenschaften].
--

ifdef::conrad,voelkner[]
Bei {market} sind die folgenden Eigenschaften automatisch in deinem plentymarkts System vorhanden und werden im Assistenten zugeordnet:

* Logistikklasse
* Versandvorlaufzeit
* Abzugsverfahren
* update-delete
endif::conrad,voelkner[]

ifdef::mediamarkt[]
Im Menü *Einrichtung » Einstellungen » Eigenschaften » Konfiguration* erstellst du die Eigenschaften, die MediaMarkt vorgibt.
Du benötigst die folgenden Eigenschaften für MediaMarkt:

* Logistikklasse
* Versandvorlaufzeit
* update-delete
endif::mediamarkt[]

ifdef::mediamarkt[]
[#property-logistic-class]
=== Eigenschaft Logistikklasse erstellen

Für jede Variante muss ein Versandprofil-Code an {market} exportiert werden. Versandprofile erstellst du im Mirakl-Backend. Die Liste der Versandprofile wird im Mirakl-Backend im Bereich *Plattformeinstellungen > Versand* angezeigt. Der Code wird in der Spalte *Logistikklasse* in Klammern hinter dem Namen der Logistikklasse angezeigt.

:property: Logistikklasse

include::partial$properties-creation.adoc[]

:property: Logistikklasse
:property-area: Artikel
:property-type: Text
:property-name: {market} Logistikklasse

include::partial$properties-creation-table.adoc[]
endif::mediamarkt[]

ifdef::mediamarkt[]
[#property-leadtime-to-ship]
=== Eigenschaft Versandvorlaufzeit erstellen

Du kannst für jede Variante eine Versandvorlaufzeit angeben. Die Versandvorlaufzeit wird auch leadtime-to-ship bezeichnet und ist die Zeit in Tagen, die Händler:innen von der Auftragsannahme bis zur Versandanmeldung benötigen. +
*_Hinweis:_* Du musst für die Versandvorlaufzeit eine ganze Zahl zwischen 1 und 45 angeben.

:property: Versandvorlaufzeit

include::partial$properties-creation.adoc[]

:property: Versandvorlaufzeit
:property-area: Artikel
:property-type: Ganze Zahl
:property-name: {market} Versandvorlaufzeit

include::partial$properties-creation-table.adoc[]
endif::mediamarkt[]

[#weitere-eigenschaften]
=== Weitere Eigenschaften erstellen

Wenn du für eine oder alle deine Varianten mehrere xref:artikel:attribute.adoc#[Attribute] definiert hast, erstelle eine Eigenschaft, die diese Attribute vereint. Unterscheidest du bei einer Variante z.B. sowohl nach Farbe als auch nach Größe, legst du eine Eigenschaft mit der Benennung "Grau XL" an. xref:artikel:eigenschaften.adoc#1400[Ordne diese Eigenschaften] den entsprechenden Varianten zu.

Zusätzlich zu den zuvor beschriebenen Eigenschaften benötigst du Eigenschaften für alle Datenfelder des Marktplatzes, für die du Daten übergeben möchtest, für die es keine eigene Einstellung in plentymarkets gibt. Welche Eigenschaften du benötigst, siehst du anhand der Datenfelder im Katalog des Marktplatzes. Pflichtfelder, die an den Marktplatz übertragen werden müssen, sind mit *** gekennzeichnet.

[discrete]
=== Eigenschaften Datenfeldern im Katalog zuordnen

Wenn du alle Eigenschaften erstellt hast, die du für {market} benötigst, ordnest du diese anschließend im Katalog den entsprechenden Datenfeldern des Marktplatzes zu. Wie du Datenfelder zuordnest, ist im Kapitel <<#datenfelder-zuordnen, Datenfelder im Katalog zuordnen>> beschrieben.
