[#auftraege-archivieren]
== Nicht bestätigte Aufträge archivieren

Wenn ein Auftrag abgelehnt oder storniert wurde, oder für einen Auftrag eine Gutschrift ausgeschrieben wurde, solltest du den Auftrag archivieren. Dies kannst du automatisch über den Aktionsmanager machen.

Du musst für jeden Status eine eigene Aktion einrichten.

[#1110]
=== Abgelehnte Aufträge archivieren

[.collapseBox]
.Aktion einrichten
--
[.instruction]
Aktion einrichten:

. Öffne das Menü *Einrichtung » Aufträge » Aktionen*.
. Öffne das Tab *Neue Aktion*.
 Nimm die gewünschten Einstellungen anhand der Informationen in <<#{market}-aktionsmanager-abgelehnte-auftraege>> vor.
. Öffne das Tab *Filter*.
. Nimm die gewünschten Einstellungen anhand der Informationen in <<#{market}-aktionsmanager-abgelehnte-auftraege>> vor.
. Öffne das Tab *Aktion*.
. Nimm die gewünschten Einstellungen anhand der Informationen in <<#{market}-aktionsmanager-abgelehnte-auftraege>> vor.
. Speichere (icon:save[set=plenty]) die Einstellungen. +
→ Die Aktion wird erstellt.

--

[#{market}-aktionsmanager-abgelehnte-auftraege]
.Einstellungen Aktionsmanager
[cols="1,3a"]
|===
|Tab |Einstellung

| *Status*
| Aktiviere die Option *Aktiv*. +
Stelle ein, wann die Aktion jeden Tag ausgeführt werden soll. +
Gib einen Namen ein.

| *Auftragstyp*
| Wähle aus der Dropdown-Liste *Status* die Option *[7] Warenausgang gebucht*. +
Wähle aus der Dropdown-Liste *Letzter Statuswechsel* die Option *Tage eingeben*. Gib den Wert `2` in das neue Textfeld ein. +
Wähle aus der Liste *Auftragsherkunft* die Option {market}.

| *Aktion*
| Wähle aus der Dropdown-Liste *Ändere Auftragsstatus* einen endgültigen Status, zum Beispiel *[7.99]*.

|===

[#1120]
=== Stornierte Aufträge archivieren

[.collapseBox]
.Aktion einrichten
--
[.instruction]
Aktion einrichten:

. Öffne das Menü *Einrichtung » Aufträge » Aktionen*.
. Öffne das Tab *Neue Aktion*.
. Nimm die gewünschten Einstellungen anhand der Informationen in <<#{market}-aktionsmanager-stornierte-auftraege>> vor.
. Öffne das Tab *Filter*.
. Nimm die gewünschten Einstellungen anhand der Informationen in <<#{market}-aktionsmanager-stornierte-auftraege>> vor.
. Öffne das Tab *Aktion*.
. Nimm die gewünschten Einstellungen anhand der Informationen in <<#{market}-aktionsmanager-stornierte-auftraege>> vor.
. Speichere (icon:save[set=plenty]) die Einstellungen. +
→ Die Aktion wird erstellt.

--

[#{market}-aktionsmanager-stornierte-auftraege]
.Einstellungen Aktionsmanager
[cols="1,3a"]
|===
|Tab |Einstellung

| *Status*
| Aktiviere die Option *Aktiv*. +
Stelle ein, wann die Aktion jeden Tag ausgeführt werden soll. +
Gib einen Namen ein.

| *Auftragstyp*
| Wähle aus der Dropdown-Liste *Status* die Option *[8] Storniert*. +
Wähle aus der Dropdown-Liste *Letzter Statuswechsel* die Option *Tage eingeben*. Gib den Wert `2` in das neue Textfeld ein. +
Wähle aus der Liste *Auftragsherkunft* die Option {market}.

| *Aktion*
| Wähle aus der Dropdown-Liste *Ändere Auftragsstatus* einen endgültigen Status, zum Beispiel 8.99.

|===

[#1130]
=== Aufträge mit Gutschriften archivieren

[.collapseBox]
.Aktion einrichten
--
[.instruction]
Aktion einrichten:

. Öffne das Menü *Einrichtung » Aufträge » Aktionen*.
. Öffne das Tab *Neue Aktion*.
. Nimm die gewünschten Einstellungen anhand der Informationen in <<#{market}-aktionsmanager-gutschriften>> vor.
. Öffne das Tab *Filter*.
. Nimm die gewünschten Einstellungen anhand der Informationen in <<#{market}-aktionsmanager-gutschriften>> vor.
. Öffne das Tab *Aktion*.
. Nimm die gewünschten Einstellungen anhand der Informationen in <<#{market}-aktionsmanager-gutschriften>> vor.
. Speichere (icon:save[set=plenty]) die Einstellungen. +
→ Die Aktion wird erstellt.

--

[#{market}-aktionsmanager-gutschriften]
.Einstellungen Aktionsmanager
[cols="1,3a"]
|===
|Tab |Einstellung

| *Status*
| Aktiviere die Option *Aktiv*. +
Stelle ein, wann die Aktion jeden Tag ausgeführt werden soll. +
Gib einen Namen ein.

| *Auftragstyp*
| Wähle aus der Dropdown-Liste *Status* die Option *[11] Gutschrift*. +
Wähle aus der Dropdown-Liste *Letzter Statuswechsel* die Option *Tage eingeben*. Gib den Wert `2` in das neue Textfeld ein. +
Wähle aus der Liste *Auftragsherkunft* die Option {market}.

| *Aktion*
| Wähle aus der Dropdown-Liste *Ändere Auftragsstatus* einen endgültigen Status, zum Beispiel 11.99.

|===
