[#registrieren]
== Bei {market} registrieren

Erstelle zuerst bei link:{registration-url}[{market}^] ein Mitgliedskonto. Nach der Registrierung erhältst du Zugangsdaten für {market}. Diese Zugangsdaten benötigst du, um {market} in plentymarkets einzurichten.

//TODO: Häufigkeit des Datenaustauschs einfügen

[#plugins-herunterladen]
== Plugins herunterladen und installieren

Um Artikeldaten zu {market} zu exportieren benötigst du die folgenden Plugins:

[.collapseBox]
.Warum benötige ich zwei Plugins?
--
{market} ist über die Plattform Mirakl mit plentymarkets verbunden. Um mit plentymarkets auf dem {type-of-market} {market} verkaufen zu können, benötigst du also zum Marktplatz-Plugin auch das Plugin *Mirakl Connector*. Über den *Mirakl Connector* können {market} und plentymarkets automatisch Artikeldaten und Auftragsdaten austauschen und du kannst deine Artikel auf {market} listen.
--

* link:https://marketplace.plentymarkets.com/mirakl_6917[Mirakl Connector^]
* link:{plugin-link}[{plugin-name}^]

:plugin: Mirakl Connector
:priority: 0
:main-client:

include::partial$plugin-installation.adoc[]
:!plugin:

:plugin: {plugin-name}
:priority: 1
:main-client:

include::partial$plugin-installation.adoc[]
:!plugin:

ifdef::video-id[]
[#webinar]
== Einrichtung: Webinar

Um {market} in plentymarkets einzurichten, kannst du entweder der Anleitung auf dieser Seite folgen oder dir folgendes Webinar ansehen:

video::{video-id}[youtube]

endif::video-id[]
