ifdef::voelkner[]
== Fehlerberichte

Im plentymarkets Backend findest du folgende Berichte:

* Zu Produktübertragungen im Menü *Daten » Voelkner Artikelexport-Berichte*
* Zu Angebotsübertragungen im Menü *Daten » Voelkner Angebotsexport-Berichte*
endif::voelkner[]

[#mirakl-faq]
== FAQ und Fehlerbehebung

[.collapseBox]
.Für eine oder mehrere Varianten wurde ein falscher Bestand übertragen. Was kann ich tun?
--

Prüfe als erstes die Bestandseinstellungen: Betrifft das Problem nur Varianten ohne Bestandsbindung?

*_Woran erkenne ich Varianten ohne Bestandsbindung?_*

. Öffne die betroffene Variante: *Artikel » Artikel bearbeiten » [Variante öffnen] » Tab: Einstellungen » Bereich: Verfügbarkeit*.
. Prüfe die Einstellung in der Dropdown-Liste *Beschränkung*.
. Wenn *Keine* oder *Keinen WB für diese Variante führen* eingestellt ist, ist es eine Variante ohne Bestandsbindung. +
*_Tipp:_* Du kannst auch in der Artikelübersicht links den Filter *WB-Beschränkung* erst auf *keine Beschränkung* und dann auf *Keinen Warenbestand führen* setzen. So werden dir Varianten ohne Bestandsbindung angezeigt und du kannst nach Mustern suchen.


*_Wie prüfe ich, ob die Einstellungen für Varianten ohne Bestandsbindung korrekt sind?_*

. Öffne den Assistenten *Einrichtung » Assistenten » Plugins » [Plugin-Set wählen] » Assistent: {assistant-name}*.
. Navigiere zum Schritt *Optionen für Angebots-Export*.
. Prüfe, dass die folgenden Einstellungen korrekt sind:
  * Die Einstellung *Bestandsmenge für Varianten ohne Bestandsbindung ersetzen* ist aktiviert.
  * Das Feld *Menge für Artikel (Varianten) ohne Bestandsbindung* enthält eine Zahl, die größer 0 ist.
. Passe die Einstellungen bei Bedarf an.

*_Wichtig:_* Angebote für Varianten ohne Bestandsbindung werden einmal pro Nacht zu {market} exportiert. Wenn du die Einstellungen korrigierst, werden die Varianten also nicht sofort exportiert.

--

[.collapseBox]
.Du kannst nicht auf das Attribut-Hilfetool zugreifen.
--
*_Mögliche Ursachen:_*

* Du hast den Assistenten *{assistant-name}* noch nicht abgeschlossen.
* Du sieht stattdessen *Hier entsteht dein plentymarkets Shop*? Wahrscheinlich ist dein plentyShop gesperrt. Entsperre den plentyShop im Menü *Einrichtung » Mandant » Global » Webshop » Shop sperren*. Vergiss nicht, den plentyShop danach wieder zu sperren.
* Die Tabelle der gültigen Attributwerte wird immer über Nacht aktualisiert. Nach dem Installieren des Plugins in deinem plentymarkets System werden die gültigen Werte also erst am nächsten Tag ausgegeben.
* Wenn du im Assistenten die falsche API-Umgebung und/oder den falschen API-Schlüssel eingetragen hast, können die gültigen Attributwerte nicht geladen werden.
--

[.collapseBox]
.Du kannst nicht auf das Attribut-Hilfetool zugreifen und sieht stattdessen "Hier entsteht dein plentymarkets Shop"
--
Wahrscheinlich ist dein plentyShop gesperrt. Entsperre den plentyShop im Menü *Einrichtung » Mandant » Global » Webshop » Shop sperren*. Vergiss nicht, den plentyShop danach wieder zu sperren.
--
