Ab sofort kannst du Artikeldaten über Kataloge zu Zalando exportieren. Pro Zalando-Kategorie benötigst du einen eigenen Katalog.

include::partial$catalogue-new-to-text.adoc[]

[#HFLYG38M]
=== Eigenschaften für Pflichtfelder vorbereiten

include::partial$mirakl-creating-properties.adoc[tag=create-properties]

//tag::prepare-properties-zalando[]
Für bestimmte Pflichtfelder von {market} gibt es in plentymarkets keine geeigneten Datenfelder. Für diese Pflichtfelder benötigst du deshalb Eigenschaften.

Wenn du für die folgenden Angaben noch keine passenden Eigenschaften hast, erstelle diese Eigenschaften jetzt. Eigenschaften erstellst du im Menü *Einrichtung » Einstellungen » Eigenschaften » Konfiguration*.

* Altersgruppe(n) 
* Geschlecht
* Hersteller-Code
* Herstellerfarbe
* Jahreszeiten-Code
* Silhouetten-Typ

Sind Farben und Größen nicht über Attribute an deinen Varianten gespeichert? Dann erstelle auch für diese Angaben Eigenschaften:

* 1. Farbcode
* Größenregister

NOTE: Du arbeitest zum ersten Mal mit den Eigenschaften? Dann mach dich zuerst xref:artikel:eigenschaften.adoc#500[mit dem Prinzip der Eigenschaften vertraut].
//end::prepare-properties-zalando[]

[#A9A9ABH5]
=== Katalog erstellen

Artikeldaten werden über das Marktplatz-Format *Zalando* zu Zalando exportiert. Um deine Artikel zu Zalando zu übertragen, erstellst du im Menü *Daten » Kataloge* einen Katalog. Ordne dann im Marktplatz-Format die von Zalando vorgegebenen Felder den in plentymarkets gespeicherten Artikeldaten zu.

*_Hinweis:_* Für jede Zalando-Kategorie benötigst du einen eigenen Katalog.

:catalogue-template-name: Zalando
:format-item-new:

include::partial$catalogue-creation.adoc[]

[#GATJV2EG]
=== Datenfelder im Katalog zuordnen

//tag::zalando-catalogue-mapping[]
Nachdem du einen Katalog erstellt hast, ordnest du die Datenfelder des Marktplatzes den in plentymarkets gespeicherten Artikeldaten zu. Informationen dazu, welche Daten für welches Datenfeld des Marktplatzes übertragen werden müssen, findest du in der Dokumentation des Marktplatzes.

include::partial$catalogue-mapping.adoc[]
//end::zalando-catalogue-mapping[]

[#filter-export]
=== Nur bestimmte Artikel exportieren (_optional_)

include::partial$catalogue-filters.adoc[]

[#preview]
=== Vorschau der Exportdaten erstellen (_optional_)

Nachdem du alle Datenfelder zugeordnet hast, kannst du die ersten fünf Produkte des Exports über die Vorschaufunktion prüfen.

include::partial$catalogue-preview.adoc[]