Für Zalando stehen verschiedene Berichte zur Verfügung. Im Menü *Einrichtung » Märkte » Zalando » Einstellungen » Tab: Verarbeitungsberichte* kannst du die folgenden Berichte herunterladen:

[cols="1,3a"]
|===
|Bericht |Erläuterung

2+^| *Export-Log*

| *zalandoArticleExportLog.txt*
a| Das Export-Log *zalandoArticleExportLog.txt* enthält Log-Einträge für Varianten. Das Export-Log wird einmal pro Nacht automatisch generiert. Die Datei enthält Einträge für erfolgreich exportierte Varianten und für Varianten, die nicht zu Zalando exportiert werden konnten.

<<#905, So lädst du das Export-Log herunter>>

2+^| *Berichte*

| *Artikelstatusberichte*
a| Die Artikelstatusberichte werden einmal täglich über Nacht von Zalando generiert. Die Berichte enthalten nur Informationen zu Varianten, die erfolgreich zu Zalando exportiert wurden.

[cols="1,3"]
!===
! *_ProductErrorReport.csv_*
! Enthält Varianten, die seit dem letzten Export nicht auf Zalando verkauft werden können. Der Bericht wird einmal pro Nacht automatisch generiert.

! *_ProductLiveReport.csv_*
! Enthält Varianten, die seit dem letzten Export auf Zalando verkauft werden können sowie Bestand und Preis jeder Variante auf den Zalando-Channels (DE, FR usw.) zu dem Zeitpunkt, zu dem die Datei generiert wurde. Der Bericht wird einmal pro Nacht automatisch generiert.
!===

<<#910, So lädst du Produkt-Status-Berichte herunter>>

| *Preis-Berichte*
a| Die Preis-Berichte werden einmal täglich über Nacht pro aktiven Channel von Zalando generiert. Diese Berichte enthalten Informationen zum Verarbeitungsstatus aller Preis-Updates, die in den letzten sieben Tagen bei Zalando eingegangen sind.

<<#915, So lädst du Preis-Berichte herunter>>
|===

[#905]
=== Export-Log herunterladen

Das Export-Log enthält plentymarkets Log-Einträge. Die Datei enthält Einträge für erfolgreich exportierte Varianten und für Varianten, die nicht zu Zalando exportiert werden konnten.

[.instruction]
Export-Log herunterladen:

. Öffne das Menü *Einrichtung » Märkte » Zalando » Einstellungen*.
. Wechsele in das Tab *Verarbeitungsberichte*.
. Klicke im Bereich *Export-Log* auf *Datei herunterladen* (icon:eye[role="blue"]). +
→ Die CSV-Datei wird generiert.
. Speichere die CSV-Datei auf deinem Rechner.
. Filtere die Einträge nach dem Status *error*.
. Prüfe die Einträge und korrigiere die betroffenen Varianten im plentymarkets Backend. +
*_Tipp:_* Einträge mit dem Status *Warning* kannst du ignorieren.

[[zalando-errors]]
.Fehlermeldungen aus dem Export-Log (zalandoArticleExportLog.txt)
[cols="1,3a"]
|===
|Einstellung |Erläuterung


| specialDescriptions
| Technische Daten

| brand
| Merkmal *Zalando » Hersteller-Code*

| season
| Merkmal *Zalando » Jahreszeiten-Code*

| genders
| Merkmal *Zalando » Geschlecht*

| ageGroups
| Merkmal *Zalando » Altersgruppe(n)*

| sizeRegister
| Merkmal *Zalando » Größen-Register*

| mainColorCode
| Kommt aus dem Merkmal *Zalando » 1. Farbcode* +
*_Ausnahme:_* Die Variante hat ein Farbattribut. Dann wird die Farbe über Attributverknüpfungen gepflegt.

| supplierColor
| Merkmal *Zalando » Hersteller-Farbe* oder optional 2. Attributsverknüpfung

| images
| Die Variante muss mindestens ein Bild haben.

| ean
| Die Variante benötigt eine GTIN 13.

| lengthRegister
| Merkmal *Zalando » Längen-Register*

| Keywords
| Meta-Keywords (Artikel-Tab: Texte)
|===

[#910]
=== Produkt-Status-Berichte herunterladen

Produkt-Status-Berichte enthalten Informationen zu den Artikeln, die zu Zalando exportiert wurden. Diese Berichte werden von Zalando generiert. Deshalb enthalten die Berichte nur Informationen zu Varianten, die erfolgreich zu Zalando exportiert wurden. Folgende Berichte sind verfügbar:

* *_ProductErrorReport.csv_*: Enthält Varianten, die seit dem letzten Export nicht auf Zalando verkauft werden können. Der Bericht enthält außerdem die ersten fünf Fehlercodes und eine Fehlerbeschreibung. Der Bericht wird einmal pro Nacht automatisch generiert. Wenn du neuere Daten benötigst, klicke vor dem Herunterladen auf *Datei aktualisieren* (icon:cog[]), um aktuelle Daten bei Zalando abzurufen.
* *_ProductLiveReport.csv_*: Enthält Varianten, die seit dem letzten Export auf Zalando verkauft werden können. Der Bericht enthält außerdem Informationen zum Bestand und Preis jeder Variante auf den Zalando-Channels (DE, FR usw.) zu dem Zeitpunkt, zu dem die Datei generiert wurde. Der Bericht wird einmal pro Nacht automatisch generiert. Wenn du neuere Daten benötigst, klicke vor dem Herunterladen auf *Datei aktualisieren* (icon:cog[]), um aktuelle Daten bei Zalando abzurufen.

[.instruction]
Produkt-Status-Bericht herunterladen:

. Öffne das Menü *Einrichtung » Märkte » Zalando » Einstellungen*.
. Wechsele in das Tab *Verarbeitungsberichte*. +
→ Im Bereich *Produkt-Status-Berichte - Account ID* sind die folgenden Dateien verfügbar:

  * *_ProductErrorReport.csv_* enthält die Varianten, die seit dem letzten Export nicht auf Zalando verkauft werden können.
  * *_ProductLiveReport.csv_* enthält die Varianten, die seit dem letzten Export auf Zalando verkauft werden können.

. *_Optional:_* Standardmäßig wird die Datei einmal pro Nacht aktualisiert. Klicke im Bereich *Produkt-Status-Berichte - Account ID* auf *Datei aktualisieren* (icon:cog[]), um vor dem Herunterladen aktuelle Daten bei Zalando abzurufen.
. Klicke im Bereich *Produkt-Status-Berichte - Account ID* in der Zeile eines Verarbeitungsberichts auf *Datei herunterladen* (icon:eye[role="blue"]). +
→ Die CSV-Datei wird generiert.
. Speichere die CSV-Datei auf deinem Rechner.

[#915]
=== Preis-Berichte herunterladen

Zalando generiert einmal täglich über Nacht einen Preis-Bericht pro aktiven Channel. Diese Berichte enthalten Informationen zum Verarbeitungsstatus aller Preis-Updates, die in den letzten sieben Tagen bei Zalando eingegangen sind. Die Berichte können also für dieselbe EAN mehrere Einträge enthalten.

[.instruction]
Preis-Berichte herunterladen:

. Öffne das Menü *Einrichtung » Märkte » Zalando » Einstellungen*.
. Wechsele in das Tab *Verarbeitungsberichte*. +
→ Im Bereich *Preis-Berichte* sind Dateien für alle aktiven Channels verfügbar.
. *_Optional:_* Standardmäßig wird die Datei einmal pro Nacht aktualisiert. Klicke in der Spalte *Aktionen* auf *Datei aktualisieren* (icon:cog[]), um vor dem Herunterladen aktuelle Daten bei Zalando abzurufen.
. Klicke im Bereich *Preis-Berichte* in der Zeile eines Verarbeitungsberichts auf *Datei herunterladen* (icon:eye[role="blue"]). +
→ Die CSV-Datei wird generiert.
. Speichere die CSV-Datei auf deinem Rechner.

[.collapseBox]
.Welche Informationen sind in Preis-Berichten enthalten?
--
[cols="1,3"]
|===
| Timestamp
| Entspricht dem aktuellsten Zeitstempel aus den Spalten *Status History* und *Scheduled Price (1-3) - Status History*.

| EAN
| Die EAN der Variante, deren Preis aktualisiert wurde.

| Ignore Warnings?
| Entspricht der Einstellung *Ignoriere Warnungen* unter *Einrichtung » Assistenten » Omni-Channel » Zalando Kontoeinstellungen » [Konto öffnen] » Schritt: Preise für [Zielland]* zum Zeitpunkt der Übertragung des Updates.

| Regular Price
| Übertragener Wert des normalen Preises.

| Regular Price Currency
| Übertragene Währung des normalen Preises.

| Promotional Price
| Übertragener Wert des reduzierten Preises.

| Promotional Price Currency
| Übertragene Währung des reduzierten Preises.

| Status
a| Status der Verarbeitung. Mögliche Status:

[cols="1,3"]
!===
! RECEIVED
! Der Preis ist eingegangen.

! ACCEPTED
! Der Preis wurde akzeptiert und zur weiteren Validierung weitergeleitet.

! REJECTED
! Der Preis hat die Validierung nicht bestanden. Siehe die Statusmeldungen in *Status History* für weitere Informationen.

! FAILED
! Bei der Preisaktualisierung ist ein unerwarteter Fehler aufgetreten. Siehe die Statusmeldungen in *Status History* für weitere Informationen.

! SCHEDULED
! Der Preis wurde erfolgreich validiert und wartet auf die Übermittlung.

! SUBMITTED
! Der Preis wurde eingereicht und wird in Kürze im Shop angezeigt.

! AWAITING_ONBOARDING
! Der Preis wurde akzeptiert, aber der Artikel wurde noch nicht aktiviert. Der Preis wird angewendet, wenn das Onboarding abgeschlossen ist.
!===

| Status History
a| Verlauf der Statusänderung. Je Änderung gibt es einen Absatz in der Zelle mit dem folgenden Schema (Platzhalter in eckigen Klammern):

* [Zeitstempel]: FROM [Ursprungsstatus] TO [Neuer Status] - Code: [Code] [Schweregrad] [Nachricht]

| Scheduled Price (1-3) - Start
| Startdatum des geplanten Preises.

| Scheduled Price (1-3) - End
| Enddatum des geplanten Preises.

| Scheduled Price (1-3) - Regular Price
| Übertragener Wert des normalen Preises für den geplanten Preis.

| Scheduled Price (1-3) - Regular Price Currency
| Übertragene Währung des normalen Preises.

| Scheduled Price (1-3) - Promotional Price
| Übertragener Wert des reduzierten Preises.

| Scheduled Price (1-3) - Promotional Price Currency
| Übertragene Währung des reduzierten Preises.

| Scheduled Price (1-3) - Status
a| Status der Verarbeitung des geplanten Preises. Mögliche Status:

[cols="1,3"]
!===
! RECEIVED
! Der Preis ist eingegangen.

! ACCEPTED
! Der Preis wurde akzeptiert und zur weiteren Validierung weitergeleitet.

! REJECTED
! Der Preis hat die Validierung nicht bestanden. Siehe die Statusmeldungen in *Scheduled Price (1-3) - Status History* für weitere Informationen.

! FAILED
! Bei der Preisaktualisierung ist ein unerwarteter Fehler aufgetreten. Siehe die Statusmeldungen in *Scheduled Price (1-3) - Status History* für weitere Informationen.

! SCHEDULED
! Der Preis wurde erfolgreich validiert und wartet auf die Übermittlung.

! OVERRIDDEN
! Der Preis wurde geplant, aber durch eine neue Preisaktualisierung überschrieben, bevor er übermittelt werden konnte.

! SUBMITTED
! Der Preis wurde eingereicht und wird in Kürze im Shop angezeigt.

! AWAITING_ONBOARDING
! Der Preis wurde akzeptiert, aber der Artikel wurde noch nicht aktiviert. Der Preis wird angewendet, wenn das Onboarding abgeschlossen ist.
!===

| Scheduled Price (1-3) - Status History
a| Verlauf der Statusänderung des geplanten Preises. Je Änderung gibt es einen Absatz in der Zelle mit dem folgenden Schema (Platzhalter in eckigen Klammern):

* [Zeitstempel] from [Ursprungsstatus] to [Neuer Status] - Code: [Code] Severity: [Schweregrad] Message: [Nachricht]
|===
--

[#1010]
== Daten-Log abrufen

:market: Zalando
include::partial$logs_abrufen.adoc[tag=data-log-intro]

* *Identifikator* » *Zalando*

include::partial$logs_abrufen.adoc[tag=data-log-config]

Nutze optional die in <<#RNJ1TOBX>> aufgeführten Filter, um die Suchergebnisse weiter einzugrenzen:

[[RNJ1TOBX]]
.Filter
[cols="1a,2a,2a"]
|===
|Log-Einträge |Empfohlene Filter |Erläuterung

| Preis-Updates
| * Identifikator » Zalando
* Level: Error
* Referenzen:
    ** Referenztyp » action +
    Referenzwert » PriceUpdate
    ** Referenztyp » ean +
    Referenzwert » EAN der Variante
| Beim Generieren der <<#915, Preis-Berichte>> wird für alle Einträge ein Fehler-Log geschrieben, die seit dem letzten Generieren der Datei (minus einer Stunde als Puffer) in den Status REJECTED, FAILED oder OVERRIDDEN geschoben wurden.

| Preis-Berichte
| * Identifikator » Zalando
* Referenzen:
  ** Referenztyp » action +
  Referenzwert » PriceReporting
| Log-Einträge zu Fehlern beim Generieren der Preis-Berichte

| Bestandsabgleich
| * Identifikator » Zalando
* Referenzen:
  ** Referenztyp » action +
  Referenzwert » StockUpdate
  ** Referenztyp » variationId
  ** Referenztyp » ean
  ** Referenztyp » accountId
  ** Referenztyp » salesChannel
  ** Referenztyp » jobUniqueId
| Log-Einträge zu Fehlern beim Bestandsabgleich

|===