Wenn du die plentyWarehouse App für die Warenwirtschaft im Lager nutzen möchtest, benötigst du lediglich ein mobiles Gerät mit Android-Betriebssystem. Ein reguläres Smartphone kann zum Testen bereits ausreichend sein. Für die alltäglichen Aufgaben in größeren Lagern empfehlen wir jedoch dringend, professionelle Geräte mit integrierten Barcode-Scannern zu verwenden. <<table-requirements-plentywarehouse>> enthält eine Liste so genannter MDE-Geräte, die wir für den Einsatz der plentyWarehouse App empfehlen.

[IMPORTANT]
.Android-Mindestversion beachten
====
Egal, ob du die plentyWarehouse App auf einem Smartphone oder der unten genannten Hardware nutzen möchtest: Auf deinem mobilen Gerät muss *mindestens Version 7.0 des Android-Betriebssystems* installiert sein. Wir behalten uns vor, diese Mindestanforderung jährlich zu erhöhen, um die Kompabilität mit Android zu garantieren.
====

[[table-requirements-plentywarehouse]]
.Warenwirtschaft mit der plentyWarehouse App
[cols="1,3"]
|====
|Hardware |Bezugsquelle

|M3 SM15 Mobile Computer
|link:https://www.sundsits.de/produkt/m3-sm15-mobile-computer-wifi-und-lte/[Angebot bei SundS ITS ansehen^] +

SundS ITS +
Beselerstr. 2-6 +
50354 Hürth +
info@sundsits.de +
Tel.: +49(0)2233-7064010 +
Fax: +49(0)2233-7064011 +
link:https://www.sundsits.de[www.sundsits.de^]

|Zebra TC 21
|link:https://www.sundsits.de/produkt/zebra-tc21/[Angebot bei SundS ITS ansehen^] +

SundS ITS +
Beselerstr. 2-6 +
50354 Hürth +
info@sundsits.de +
Tel.: +49(0)2233-7064010 +
Fax: +49(0)2233-7064011 +
link:https://www.sundsits.de[www.sundsits.de^]

|Zebra TC 26
|link:https://www.sundsits.de/produkt/zebra-tc26/[Angebot bei SundS ITS ansehen^] +

SundS ITS +
Beselerstr. 2-6 +
50354 Hürth +
info@sundsits.de +
Tel.: +49(0)2233-7064010 +
Fax: +49(0)2233-7064011 +
link:https://www.sundsits.de[www.sundsits.de^]

|====
