= Artikel unter Meldebestand (Live)
:keywords: Meldebestand, Artikel unter Meldebestand, Meldebestand (Live), Business Intelligence, Statistik, Statistiken, Kennzahl, Kennzahlen, Dashboard
:description: Diese Seite erläutert die Berechnungen, Dimensionen und Filter, die dir für die Kennzahl Artikel unter Meldebestand (Live) zur Verfügung stehen.
:author: team-app-bi

:kennzahl: Artikel unter Meldebestand (Live)

include::partial$kennzahlen-einleitung.adoc[]

plentymarkets berechnet die Liveanzahl der Artikel pro Lager, die den festgelegten Meldebestand unterschritten haben, indem die Artikel und deren festgelegter Meldebestand in Echtzeit anhand der Datenbank überprüft und geladen werden.

[IMPORTANT]
.Standard-Kennzahl nutzen
====
Die Kennzahl *Artikel unter Meldebesntand (Live)* ist eine so genannte Standard-Kennzahl. Das bedeutet, dass sie in deinem plentymarkets System bereits mit einigen Voreinstellungen eingerichtet ist. Du musst also nicht zwingend eine zusätzliche Kennzahl erstellen. Du findest die Kennzahlkonfiguration im Menü *Einrichtung » plentyBI » Kennzahlen*. Dort wird der Eintrag zur Kennzahl *Artikel unter Meldebestand (Live)*, die von `plentymarkets` erstellt wurde, angezeigt.
====

[#100]
== Berechnung

=== Gesamt

:kennzahl: Die Kennzahl Artikel unter Meldebestand (Live)
:das-bedeutet: Das bedeutet, dass die Artikel gemäß der gewählten Dimension und den Filtern zusammengerechnet und in Echtzeit dargestellt werden.

include::partial$gesamt.adoc[]

[#200]
== Dimension

=== Lager

Die Artikelanzahl wird in Echtzeit pro Lager angezeigt.
Die Daten werden live der Datenbank entnommen.
