= Benutzer:innen-Konten und Zugänge
:keywords: Eigner, Benutzer, Benutzerkonto, Benutzer verwalten, Benutzerverwaltung, Benutzerkonto verwalten, Rolle, Berechtigungen, Berechtigungen zuordnen, Rechte, Rechte vergeben, Menü- und REST-API Rechte, Sichtbarkeiten festlegen, Zugang, Benutzerzugang, Benutzerzugänge, CUL-Benutzerlizenz, Benutzerlizenz, Limit, Limitierung, Passwortsicherheit, Admin, Backend, REST-API, Stammdaten, Postfach erstellen, plentymarkets Forum, Session-Verwaltung, Adminrechte
:description: Arbeiten mit plentymarkets: Verwalte Benutzer:innen-Konten, lege neue Benutzer:innen-Konten an und bearbeite bestehende Benutzer:innen-Konten im plentymarkets System.
:id: CHBIF6G
:author: team-plenty-channel

:benutzerzugang: pass:quotes[Wähle einen **Benutzer:innen-Zugang**.]
:tabelle: Beachte dazu die Erläuterungen in <<tabelle-benutzerzugänge>>.

In der Benutzer:innen-Verwaltung erstellst du neue Benutzer:innen-Konten und bearbeitest bestehende Benutzer:innen-Konten. Darüber hinaus verknüpfst du Benutzer:innen-Konten mit Rollen und Zugängen.

* Mit Rollen gruppierst du Benutzer:innen-Konten und ordnest mehreren Konten dieselben Berechtigungen zu.
* In den Rollen verteilst du Menü- und Plugin-Sichtbarkeiten sowie REST-API Berechtigungen.

In jedem plentymarkets System sind kostenfrei fünf CUL-Lizenzen für Benutzer:innen enthalten. Weitere Benutzer:innen-Konten buchst du im link:http://www.plentymarkets.eu/preise/[Konfigurator] hinzu.

[NOTE]
.Was ist eine CUL-Benutzerlizenz?
====
CUL steht für Concurrent-User-Lizenzmodell. Über die Lizenz wird festgelegt, wie viele Benutzer:innen-Konten gleichzeitig auf das plentymarkets Backend, die REST-API und die plentymarkets App zugreifen dürfen. Wir limitieren also nur die gleichzeitige Nutzung und nicht die Anzahl der Benutzer:innen-Konten, die du erstellen kannst.
====

[#35]
== Sicherheitseinstellungen

Im Menü *Einrichtung » Kontverwaltung » Sicherheit* stellst du die Anforderungen an neue Passwörter ein, die Benutzer:innen erfüllen müssen.

[.instruction]
Sicherheitseinstellungen vornehmen:

. Öffne das Menü *Einrichtung » Kontoverwaltung » Sicherheit*.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<#tabelle-sicherheit-einstellen>>.
. *Speichere* (material:save[]) die Einstellungen.

[[tabelle-sicherheit-einstellen]]
.Passwortsicherheit und automatische Abmeldung
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+^| *Passwortsicherheit*

| *Passwortsicherheit aktivieren*
|Wird diese Option aktiviert, muss jedes neu eingegebene Passwort die eingestellten Anforderungen erfüllen.

| *Mindestlänge*
|Mindestanzahl an Zeichen für neue Passwörter eingeben. +
*_Hinweis:_* Aus Sicherheitsgründen muss die Mindestlänge 8 oder mehr Zeichen betragen.

| *Passwortkriterien*
|Kriterien aktivieren, die für neue Passwörter gelten sollen. +
*_Hinweis:_* Aus Sicherheitsgründen müssen mindestens 3 Kriterien aktiviert sein.

| *Mindestanzahl erfüllter Kriterien*
|Anzahl der Kriterien einstellen, die neue Passwörter mindestens erfüllen müssen. +
*_Hinweis:_* Aus Sicherheitsgründen müssen mindestens 3 Kriterien aktiviert sein.

| *Anzahl zuletzt benutzter Passwörter*
|Anzahl der zuletzt benutzten Passwörter einstellen, die nicht erneut verwendet werden dürfen. Die Nutzer:innen werden darauf hingewiesen, wenn sie versuchen, eines der zuletzt benutzten Passwörter erneut einzugeben. Wenn diese Funktion nicht gewünscht ist, lasse den Regler bei 0 stehen. +
*_Hinweis:_* Die Anzahl der zu speichernden Passwörter muss 20 oder weniger betragen.

| *Maximaler Zeitraum der Passwortgültigkeit (Tage)*
|Nach Ablauf des Gültigkeitszeitraums in Tagen wird das Benutzer:innen-Konto gesperrt. Wenn diese Funktion nicht gewünscht ist, lasse den Regler bei 0 stehen.

| *Passwort-Ablaufbenachrichtigung (Tage)*
|Gib mit dem Regler die Anzahl an Tagen an.
So viele Tage vor Ablauf des Passworts erhält der:die Benutzer:in eine tägliche Erinnerung zur Änderung des Passworts.
Wenn diese Funktion nicht gewünscht ist, lasse den Regler bei 0 stehen.
|====

[#10]
== Benutzer:innen-Konto erstellen

Bei der Erstverwendung deines Systems ist bereits ein Standardbenutzer:innen-Konto des Zugangs *Administrator*, also ein Konto mit Administratorrechten, vorhanden. Du benötigst mindestens ein Benutzer:innen-Konto des Typs Administrator. Erstelle deshalb entweder ein neues Benutzer:innen-Konto des Zugangs *Administrator* und lösche danach das Standardbenutzer:innen-Konto oder bearbeite das vorhandene Benutzer:innen-Konto. Im Folgenden wird beschrieben, wie du ein Benutzer:innen-Konto eines beliebigen Zugangs erstellst.

include::partial$benutzerkonto-erstellen.adoc[]

Der Benutzername darf kein Leerzeichen enthalten und muss mindestens 5 Zeichen lang sein.

Die Benutzer:innen-Zugänge sind vorgegeben und die Einstellungen der Zugänge sind nicht änderbar. Welche Berechtigungen bei Zugängen voreingestellt sind und welche du noch individuell am Benutzer:innen-Konto einstellen kannst, findest du in dieser Tabelle:

[[tabelle-benutzerzugänge]]
.Übersicht der verfügbaren Benutzerzugänge
[cols="1,3"]
|====
|Zugang |Erläuterung

| *Administrator*
|Zugang, der über alle Berechtigungen ohne Einschränkung verfügt und mindestens einem Benutzer:innen-Konto zugeordnet werden muss, da nur ein Administrator weitere Benutzer:innen-Konten uneingeschränkt erstellen, verwalten und bearbeiten kann. Bei Verwendung mehrerer Administratorkonten sind diese gleichberechtigt.

| *Nur API-Benutzer*
|Zugang, für die in der Rolle xref:business-entscheidungen:benutzerkonten-zugaenge.adoc#120[REST-Calls] freigeschaltet werden. Die REST-Calls werden dann einzeln aktiviert. Es werden der Rolle also nicht pauschal alle REST-Calls freigeschaltet. +

*Achtung*: Nutzer:innen mit diesem Benutzer:innen-Zugang wird der Zugriff auf das Backend verweigert.
|====


[NOTE]
Die Zugänge *Callcenter*, *Logistik*, *Blog* und *Newsletter2Go* existieren nicht mehr und wurden in das Standard-Benutzer:innen-Konto migriert.


[#20]
== Benutzer:innen-Konto bearbeiten

Nachdem ein Benutzer:innen-Konto erstellt wurde, wird das Konto in der Benutzer:innen-Kontoübersicht hinzugefügt. Wähle ein Benutzer:innen-Konto, um Einstellungen an dessen Konto vorzunehmen. Die Anzahl der Einstellungen hängt zum einen von deinem Benutzer:innen-Zugang und zum anderen von dem Benutzer:innen-Zugang des zu bearbeitenden Benutzer:innen-Kontos ab.

[.instruction]
Benutzer:innen-Konto bearbeiten:

. Öffne das Menü *Einrichtung » Kontoverwaltung » Konten*.
. Klicke auf *Suchen* (material:search[]). +
→ Alle Benutzer:innen-Konten werden angezeigt.
. Nimm Änderungen und Einstellungen gemäß <<#tabelle-benutzer:innen-daten>> vor.
. *Speichere* (material:save[]) die Einstellungen.

[TIP]
.Passwort ist gespeichert
====
Das beim Erstellen des Benutzer:innen-Kontos eingegebene Passwort ist im Bearbeitungsmodus nicht sichtbar, ist aber gespeichert. Du musst es beim Bearbeiten des Benutzer:innen-Kontos nicht erneut eingeben.
====

[#30]
=== Benutzer:innen-Daten pflegen

Im Benutzer:innen-Konto nimmst du Änderungen und Einstellungen an den Benutzer:innen-Daten eines Kontos vor. *Benutzername*, *IP-Beschränkung*, *Benutzerzugang* und *Rollen* können nur von Personen mit Administratorrechten geändert werden. Alle anderen Benutzer:innen-Daten können Personen auch in ihrem eigenen Konto anpassen. Zudem ist das Sperren eines Benutzer:innen-Kontos in diesem Bereich möglich.

[[tabelle-benutzer:innen-daten]]
.Daten eines Benutzer:innen-Kontos
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Benutzer*
|Name ohne Leerzeichen eingeben. Der Name ist eine Pflichtangabe, die für den Login benötigt wird. Der Benutzername darf kein Leerzeichen enthalten und muss mindestens 5 Zeichen lang sein.

| *Name*
|Realer Name der Benutzer:in, die in der Kopfzeile des plentymarkets Administrationsbereichs angezeigt wird.

| *E-Mail*
|E-Mail-Adresse des Benutzer:innen-Kontos eingeben. Diese ist u.a. für Benachrichtigungen des Systems, Benachrichtigungen aus Ereignisaktionen, zur Erstellung eines Forumkontos und auch für die Gruppenkommunikation innerhalb des Systems wichtig.

| *Zeitzone*
|Zeitzone des Benutzer:innen-Kontos wählen.

| *Sprache*
|Sprache für den Administrator-Bereich. Diese Sprache wird als Standard beim Login verwendet.

| *Passwort*
|Neues Passwort eingeben, um dem Benutzer:innen-Konto ein neues Passwort zu erteilen.

| *Passwort wiederholen*
|Passwort noch einmal eingeben.

| *App-Pin*
|include::app:partial$app-pin.adoc[]

| *App-Pin wiederholen*
|PIN noch einmal eingeben.

| *IP beschränken*
|IP-Adresse des Rechners der Person des Benutzer:innen-Kontos eingeben, damit sich die Person mit diesem Benutzer:innen-Konto nur über diese IP-Adresse in das plentymarkets System einloggen kann.

|*Aktiviere Forum-Konto*
|Klicken, wenn für das Benutzer:innen-Konto ein Forum-Konto erstellt werden soll. Dafür muss eine E-Mail-Adresse hinterlegt sein.

| *Benutzer deaktiviert*
|Aktivieren, um das Benutzer:innen-Konto zu deaktivieren. Deaktivierte Personen können sich nicht mehr in das System einloggen.

| *Benutzer:innen-Zugang*
|Benutzer:innen-Zugang des Benutzer:innen-Kontos wählen. Es stehen die Zugänge *Administrator*, und *Nur API-Benutzer* zur Verfügung. +
 Ein *Administrator* hat alle Menü-Sichtbarkeiten, Rollendefinierte Ansichten, Zugriffsrechte und Berechtigungen, kann Benutzer:innen-Konton erstellen, deaktvieren und Logins entsperren. Außerdem kann er Rollen erstellen, bearbeiten, löschen und zuweisen. +
 *Nur API-Benutzer* können nur REST-API Calls nutzen, sie erhalten keine Menü- und Plugin-Sichtbarkeiten.

| *Zugewiesene Rollen*
|Rollen des Benutzer:innen-Kontos wählen. Damit Rollen zur Auswahl stehen, müssen zuvor xref:business-entscheidungen:benutzerkonten-zugaenge.adoc#70[Rollen] erstellt werden.

| *Signatur*
| Text, der Nachrichten und Kommentaren der Benutzer:innen im Ticketsystem automatisch als xref:crm:ticketsystem-nutzen.adoc#300[Signatur] angefügt wird.

| *Ticket-Grußformel*
| Text, der Nachrichten und Kommentaren der Benutzer:innen im Ticketsystem automatisch als xref:crm:ticketsystem-nutzen.adoc#300[Grußformel] angefügt wird.

|====

[#40]
=== Eigner:innen aktivieren

Ob und in welchen Bereichen das Benutzer:innen-Konto als Eigner:in verfügbar sein soll, wird in den Sichtbarkeiten im einfachen Modus der Rollen über *Bearbeiten* und *Erstellen* bestimmt. Wenn du zum Beispiel eine Rolle erstellst, die Eignerrechte für Aufträge haben soll, musst du im einfachen Modus in der Spalte *Aufträge* die Optionen *Bearbeiten* oder *Erstellen* aktivieren.

[TIP]
.Bearbeiten und Erstellen nicht vorhanden
====
Es gibt Sichtbarkeiten, bei denen nur *Betrachten* aktiviert werden kann. In diesem Fall wird bei der Aktivierung von *Betrachten* auch die Rolle als Eigner aktiviert.
====

[.instruction]
Benutzer:innen als Eigner:in aktivieren:

. Öffne das Menü *Einrichtung » Kontoverwaltung » Rollen*.
. Öffne eine Rolle. +
→ Die Rechteübersicht der Rolle öffnet sich im einfachen Modus.
. Aktiviere *Bearbeiten* oder *Erstellen* bei den Sichtbarkeiten, bei der die Rolle als Eigner:in verfügbar sein soll.
. *Speichere* (material:save[]) die Einstellungen.

// ACHTUNG!!!! Aus der GUI wird auf die Kapitel zu E-Mail-Postfächern verlinkt. Falls diese Inhalte verschoben werden, bitte Ziyad oder einem anderen Mitglied des Cloud-Teams Bescheid sagen, damit der Link angepasst wird. Danke.

[#50]
=== Persönliche Einstellungen

Unter dem plentymarkets Logo oben links und deinem Profilbild oben rechts (material:account_circle[]) findest du die *persönlichen Einstellungen*. Hier nimmst du Einstellungen vor, die nur für das im System angemeldete Benutzer:innen-Konto gelten. Deshalb ist der Bereich für dich auch nur in deinem eigenen Benutzer:innen-Konto sichtbar. Die persönlichen Einstellungen unterteilen sich in die Tabs xref:willkommen:system-personalisieren.adoc#70[Allgemein], und xref:willkommen:system-personalisieren.adoc#80[Shortcuts] die nur dich persönlich betreffen.

[#85]
== Mehrere Benutzer:innen-Konten bearbeiten

Mehrere Benutzer:innen-Konten bearbeitest du über *Mehr* (material:more_vert[]) im Menü *Konten*. Hierbei werden zuvor gewählte Benutzer:innen-Konten bearbeitet.

[.instruction]
Gruppenfunktion ausführen:

. Öffne das Menü *Einrichtung » Kontoverwaltung » Konten*.
. Wähle die zu bearbeitenden Benutzer:innen.
. Klicke auf material:more_vert[] *Mehr*.
. Nimm die Einstellungen vor. Beachte die Erläuterungen in <<#tabelle-mehr>>.
. Klicke auf *Anwenden*. +
→ Die Benutzer:innen-Konten werden geändert.

[[tabelle-mehr]]
.Benutzer:innen-Konten per *Mehr* bearbeiten
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Rollen zuweisen*
|Aktivieren, um ausgewählten Benutzer:innen-Konten eine oder mehrere Rollen zuzuweisen. Ein Dialogfenster öffnet sich. Wähle im Dropdown-Menü eine oder mehrere Rollen aus. Bestätige deine Auswahl mit einem Klick auf *Rollen zuweisen*. Die Rollen werden den ausgewählten Benutzer:innen-Konten zugewiesen.

|*Rollen entziehen*
|Aktivieren, um ausgewählten Benutzer:innen-Konten eine oder mehrere Rollen zu entziehen. Ein Dialogfenster öffnet sich. Wähle im Dropdown-Menü eine oder mehrere Rollen aus. Bestätige deine Auswahl mit einem Klick auf *Rollen entziehen*. Die Rollen werden den ausgwählten Benutzer:innen-Konten entzogen.

| *E-Mail senden*
|Aktivieren, um eine E-Mail an die gewählten Benutzer:innen-Konten zu senden. Das E-Mail-Programm wird geöffnet. Die Benutzer:innen-Konten sind als Empfänger:in eingetragen.

| *Angefangene Box-Kommissionierungen zurücksetzen*
| Aktivieren, um die angefangene Box-Kommissionierung der ausgewählten Benutzer:innen-Kontos zurückzusetzen.

| *Ausloggen*
|Aktivieren, um ausgewählte Benutzer:innen aus dem System auszuloggen.
|====

[#105]
== Rechte verwalten

In plentymarkets werden Rechte über Rollen an Benutzer:innen vergeben. Dies beinhaltet Menü- und Plugin-Sichtbarkeiten sowie REST-API-Berechtigungen. Ein:e Benutzer:in hat also immer die Rechte, die von der Rolle zugewiesen werden. Die einzige Ausnahme dabei bilden Administratoren, die unabhängig von ihrer Rolle alle Rechte im System besitzen.
Im Menü *Einrichtung » Kontoverwaltung » Rollen* kannst du neue Rollen erstellen oder existierende Rollen angepassen. Beim Erstellen oder Bearbeiten einer Rolle kannst du im Menüpunkt *Zugriffsrechte* die Auftragsherkünfte freigeben, die für die Benutzer:innen sichtbar sein sollen. Rollen können von Benutzer:innen des Zugangs *Administrator* erstellt werden oder von Nutzer:innen, die eine Rolle mit den notwendigen Rechten haben. +
Ordne einem Benutzer:innen-Konto nur die Rolle zu, die die Person für ihren Aufgabenbereich benötigt. Diese Einschränkung erhöht die Sicherheit und beugt Fehlern in deinem System vor.

Die Tabelle der Benutzer:innenrechte gliedert sich in vier Spalten. In diesen Spalten kannst du Rechte vergeben, indem du die Optionen *Betrachten*, *Bearbeiten*, *Erstellen* oder *Löschen* aktivierst. Zwei dieser vier Optionen ändern im erweiterten Modus ihre Namen: Aus *Betrachten* wird *Lesen* und aus *Bearbeiten* wird *Aktualisieren*.

[#106]
=== Einfacher und erweiterter Modus

Beim Erstellen und Bearbeiten von Rollen gibt es zwei Modi: Den einfachen und den erweiterten Modus. Welcher Modus für welche Rolle relevant ist, kommt auf die Rechte an, die du an die Rolle vergeben willst. Der einfache Modus und der erweiterte Modus sind miteinander verknüpft. Wenn du also Menü-Sichtbarkeiten im einfachen Modus aktivierst, sind dazugehörige Berechtigungen auch im erweiterten Modus automatisch aktiv. Diese Verknüpfung existiert allerdings nur in diese Richtung. Wenn du also im erweiterten Modus Berechtigungen vergibst, werden keine Menü- oder Plugin-Sichtbarkeiten automatisch aktiviert. +

Du musst nur in den erweiterten Modus wechseln, wenn du mit der Rolle die plentymarkets API über eigene Apps ansprechen möchtest. Für die reine Nutzung der plentymarkets Apps solltest du den einfachen Modus verwenden.



**Einfacher Modus** = Im einfachen Modus kannst du die Sichtbarkeiten für Menüs und Plugins der plentymarkets Apps vergeben. Die Tabelle des einfachen Modus ist genauso aufgebaut wie die Navigation und bildet zudem individuelle Plugins ab.

**Erweiterter Modus** = Im erweiterten Modus vergibst du Berechtigungen. Das sind REST-API-Rechte, die für das Laden und Schreiben von Daten benötigt werden.

[#110]
=== Rollen vergeben

Gehe wie folgt vor, um eine Rolle zu vergeben:

. Öffne das Menü *Einrichtung » Kontoverwaltung » Konten*. +
→ Die Übersicht wird geöffnet.
. Wähle ein Konto. +
→ Die Konto-Detailansicht wird geöffnet.
. Klicke im Bereich *Rechte* auf die Dropdown-Liste *Zugewiesene Rollen*. +
→ Die Dropdown-Liste klappt aus.
. Wähle eine vorhandene Rolle. +
*_Oder:_* Erstelle eine neue Rolle. Klicke dazu auf *Neue Rolle erstellen ...* (material:add[]). +

→ Das Konto erhält die Rechte der Rolle.

[#115]
=== Rechte für Rollen vergeben

[.instruction]
Rechte für Rollen vergeben:

. Öffne das Menü *Einrichtung » Kontoverwaltung » Rollen*. +
→ Die Übersicht wird geöffnet.
. Klicke auf *Suchen* (material:search[]), um alle Rollen zu sehen.
. Wähle eine Rolle. +
→ Die Rechteübersicht der Rolle öffnet sich im einfachen Modus.
. Vergib die Rechte für Rollen in dem jeweiligen Bereich durch Anklicken der Checkboxen. Aktiviere komplette Bereiche oder klappe Bereiche auf, um einzelne Berechtigungen zu aktivieren, die dem Benutzer:innen-Konto zur Verfügung stehen sollen.
. *Speichere* (material:save[]) die Einstellungen.

[#116]
=== Rechte für rollendefinierte Ansichten vergeben

In der Rollen-Detailansicht kannst du im Bereich *Rollendefinierte Ansichten* bestimmen, welche Ansichten Benutzer:innen einer Rolle sehen und verwenden dürfen. Am Anfang ist immer die Standardansicht vorausgewählt. Existiert eine weitere Ansicht, kannst du die Standardansicht für eine Rolle deaktivieren und Rechte für eine andere Ansicht vergeben. Beachte, dass immer mindestens eine Ansicht ausgewählt sein muss.

[.instruction]
Rechte für rollendefinierte Ansichten vergeben:

. Öffne das Menü *Einrichtung » Kontoverwaltung » Rollen*. +
→ Die Übersicht wird angezeigt.
. Klicke auf *Suchen* (material:search[]), um nach Rollen zu suchen. +
→ Alle vorhandenen Rollen werden angezeigt.
. Wähle eine Rolle. +
→ Die Übersicht wird geöffnet.
. Klicke auf den Bereich *Rollendefinierte Ansichten*. +
→ Alle rollendefinierten Ansichten werden angezeigt.
. Vergib die Rechte für Ansichten durch Anklicken der Checkboxen.
. *Speichere* (material:save[]) die Einstellungen. +
→ Die Rechte für die gewählten Ansichten werden der Rolle zugewiesen.

[#100]
=== Zugriffsrechte festlegen

Unter *Einrichtung » Kontoverwaltung » Rollen » [Rolle auswählen]* legst du fest, welche Bereiche und Einstellungen Personen mit dieser Rolle sehen können, wenn sie ein Menü öffnen. Wenn die Rolle zum Beispiel keine Berechtigungen für einen Lagertyp oder bestimmte Auftragsstatus hat, sind der Lagertyp oder Aufträge in diesem Status für diese Person nicht sichtbar.

.Einstellbare Zugriffsrechte
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Vertriebslager*; +
*Reparaturlager*; +
*Vorratslager*; +
*Umschlagslager*; +
*Verteilerlager*; +
*Sonderlager* (Typ *Sonstiges*) +
|Benutzer:innen Berechtigungen für Lager erteilen. Nur erstellte xref:warenwirtschaft:lager-einrichten.adoc#300[Lagertypen] stehen zur Verfügung. +
*Alle* = Die Person mit diesem Benutzer:innen-Konto hat Zugriff auf alle Lager. +
*Keine* = Die Person mit dieser Rolle hat Zugriff auf keines der Lager.

| *Sichtbare Auftragsstatus*
|Auftragsstatus festlegen, die *sichtbar* sein sollen. Personen mit dieser Rolle sehen nur die Aufträge, die in diesen Status sind.

| *Setzbare Auftragsstatus*
|Auftragsstatus festlegen, die Personen mit dieser Rolle sehen dürfen.

| *Mandanten (Shops)*
|Einzelne, mehrere oder alle Mandanten (Shops) festlegen, die die Person mit dieser Rolle sehen darf. Die Person mit dieser Rolle hat nur auf die hier festgelegten Bereiche Zugriff. Wenn kein Mandant gewählt wurde, greifen auch weitere Berechtigungen nicht, da die Person mit diese Rolle generell keinen Mandanten sieht. +
*Alle* = Die Person mit dieser Rolle hat Zugriff auf alle Mandanten. +
*Standard* = Die Person mit dieser Rolle hat Zugriff auf den Standard-Webshop.

| *Ticketstatus*
|Ticketstatus wählen, um festzulegen, welche Tickets mit welchem Status die Person mit dieser Rolle ansehen und bearbeiten darf. +
*Unsichtbar* = Die Person mit dieser Rolle sieht kein Ticket, das in diesem Status ist. +
*Sichtbar* = Die Person mit dieser Rolle sieht jedes Ticket, das in diesem Status ist. +
*Nur eigene* = Die Person mit dieser Rolle sieht nur Tickets, die in diesem Status sind und von denen sie Eigner ist. +
In der Ticketübersicht werden alle Tickets aufgeführt, also auch für die Rolle unsichtbare Tickets. Die Person mit dieser Rolle kann unsichtbare Tickets jedoch nicht öffnen.
|====

[#120]
=== Menü- und REST-API-Rechte verwalten

Im erweiterten Modus legst du fest, welche Berechtigungen ein Benutzer:innen-Konto für die REST-API erhält. Benutzer:innen-Konten des Zugangs *Administrator* verfügen über alle Berechtigungen.

[.instruction]
Menü- und REST-API-Rechte verwalten:

. Öffne das Menü *Einrichtung » Kontoverwaltung » Rollen*.
. Öffne eine Rolle. +
→ Oder erstelle eine neue Rolle.
. Wechsele auf *Erweitert* (material:toggle_on["role=skyBlue"]). +
→ Die Tabelle des erweiterten Modus wird angezeigt.
. Vergib die Berechtigungen in dem jeweiligen Bereich durch Anklicken der Checkboxen. Aktiviere komplette Bereiche oder klappe Bereiche auf, um einzelne Berechtigungen zu aktivieren, die der Rolle zugewiesen werden sollen.
. *Speichere* (material:save[]) die Einstellungen.

[#125]
=== App-Berechtigungen aktivieren

Unter dem Punkt *Mobile* im einfachen Modus der Rollen legst du fest, welche Bereiche und Kennzahlen für die Rolle in der plentymarkets App sichtbar sein sollen.

[.instruction]
App-Berechtigungen aktivieren:

. Öffne das Menü *Einrichtung » Kontoverwaltung » Rollen*.
. Öffne eine Rolle.
. Öffne im einfachen Modus den Punkt *Mobile*.
. Aktiviere Funktionen oder Kennzahlen, die der Rolle in der App zur Verfügung stehen sollen.
. *Speichere* (material::save[]) die Einstellungen.

[#145]
=== Benutzer:innen-Konto entsperren

Die maximale Anzahl der Login-Versuche beträgt 5 pro Benutzer:innen-Konto oder 25 pro IP-Adresse. Wenn die maximale Anzahl der Login-Versuche überschritten wird, wird das Konto für 24 Stunden gesperrt. Personen mit Administratorrechten können ein Benutzer:innen-Konto vor Ablauf dieser 24 Stunden manuell entsperren.

[.instruction]
Benutzer:innen-Konto entsperren:

. Öffne das Menü *Einrichtung » Kontoverwaltung » Konten*. +
→ Die Benutzer:innen-Konten werden angezeigt.
. Doppelklicke auf das gesperrte Benutzer:innen-Konto. +
→ Das Benutzer:innen-Konto wird geöffnet.
. Klicke auf *Login entsperren*. +
→ Das Benutzer:innen-Konto wird entsperrt.

[#70]
== Rollen erstellen

Mit Rollen gruppierst du Benutzer:innen-Konten und erteilst mehreren Benutzer:innen die gleichen Berechtigungen, ohne jedes Benutzer:innen-Konto einzeln bearbeiten zu müssen.

[.instruction]
Neue Rolle erstellen:

. Öffne das Menü *Einrichtung » Kontoverwaltung » Rollen*.
. Klicke auf *Neu* (material:add[]). +
→ Das Fenster *Neue Rolle* wird geöffnet.
. Gib einen *Namen* für die Rolle ein.
. *Speichere* (material:save[]) die Einstellungen. +
→ Die Rolle wird in einem neuen Tab zur Bearbeitung geöffnet.

Erst beim Bearbeiten der Rolle legst du die Berechtigungen fest, die Benutzer:innen-Konten mit dieser Rolle haben. Bearbeite die Rolle deshalb nach dem Erstellen.

[#80]
== Rollen bearbeiten

Nachdem du eine Rolle erstellt hast, wird sie zur Bearbeitung geöffnet und der Rollenübersicht hinzugefügt, sodass du die Rolle auch später wieder öffnen und bearbeiten kannst. Rollen werden in der Übersicht nach ID gelistet. Jede Rolle gliedert sich in vier Bereiche. Im Bereich *Einstellungen* kannst du den Namen der Rolle ändern. Im Bereich *Rechte* ordnest du der Rolle im Einfachen Modus Menü-Sichtbarkeiten sowie Plugin-Sichtbarkeiten zu, im Erweiterten Modus die REST-API Berechtigungen. Im Bereich *Rollendefinierte Ansichten* kannst du die verfügbaren MyView-Ansichten für eine Rolle anpassen. Es ist automatisch immer die Standardansicht ausgewählt. Im Bereich *Zugrifssrechte* lassen sich die Ressourcen aktivieren, auf die eine Rolle Zugriff haben soll. Details zu den Berechtigungen findest du hier auf der Seite im Kapitel xref:business-entscheidungen:benutzerkonten-zugaenge.adoc#105[Rechte verwalten]. +

[.instruction]
Rolle bearbeiten:

. Öffne das Menü *Einrichtung » Kontoverwaltung » Rollen*.
. Öffne die Rolle, die du bearbeiten willst. +
→ Die Rechteübersicht der Rolle öffnet sich im einfachen Modus.
. Ändere die Rolle in den unterschiedlichen Bereichen durch das Setzen oder Entfernen von Haken in den Boxen.
. *Speichere* (material:save[]) die Einstellungen.

[.instruction]
Rollen mit einem Benutzer:innen-Konto verknüpfen:

. Öffne das Menü *Einrichtung » Kontoverwaltung » Konten*.
. Öffne ein Benutzer:innen-Konto.
. Klicke auf die Dropdown-Liste *Zugewiesene Rollen*.
. Wähle eine, mehrere oder alle Rollen.
. *Speichere* (material:save[]) die Einstellungen.

[.subhead]
Anwendungsbeispiel

Der Administrator der Firma MeinShop erstellt verschiedene Rollen. Die Rolle Mitarbeiter ist für alle Benutzer:innen-Konten gedacht und enthält sämtliche Berechtigungen, die jedem Benutzer:innen-Konto zugeordnet werden. Die individuelle Zuordnung dieser Berechtigungen entfällt. Auch Änderungen an den Berechtigungen, die alle Benutzer:innen-Konten betreffen, werden zentral in dieser Rolle vorgenommen. Zusätzlich zur Rolle Mitarbeiter erstellt der Administrator die spezifischen Rollen Lagerist und Buchhaltung mit weiteren Berechtigungen, die nur eine kleine Benutzergruppe benötigt.

.Beispiel für Rollen
[cols="1,3,3"]
|====
|Rolle |Berechtigungen |Menü-Sichtbarkeiten

| *Mitarbeiter*
|Mandanten (Shops) » Standard
|Start » Webmail +
Start » Forum

| *Lagerist*
|Lager
|Einrichtung » Waren » Lager +
Waren +
Aufträge » Fulfillment

| *Buchhaltung*
|
|Start » Urlaubsverwaltung +
Einrichtung » Mandant » Mandant wählen » Buchhaltung
|====

Herr Mustermann ist Logistiker bei MeinShop und erhält die Benutzerrollen Mitarbeiter und Lagerist. Wenn einem Benutzer:innen-Konto mehrere Rollen zugeordnet werden, addieren sich die Berechtigungen. Herr Mustermann erhält also die Berechtigungen *Mandanten (Shops)*, *Webmail* und *Forum* der Rolle Mitarbeiter sowie die Berechtigungen *Lager*, *Waren* und *Fulfillment* der Rolle Lagerist. Er verfügt aber nicht über die Berechtigungen *Urlaubsverwaltung* und *Buchhaltung*, da ihm die Rolle Buchhaltung nicht zugeordnet wurde.

== Rollen kopieren

Wenn du eine weitere Rolle benötigst, die sich von einer bestehenden Rolle nur minimal unterscheidet, dann kopiere die bestehende Rolle und nimm an der Kopie die Änderungen in den jeweiligen Bereichen vor.

[.instruction]
Rolle kopieren:

. Öffne das Menü *Einrichtung » Kontoverwaltung » Rollen*.
. Wähle eine Rolle.
. Klicke in der Zeile der Rolle auf *Mehr* (material:more_vert[]). +
→ Ein Optionsfenster wird angezeigt.
. Wähle *Rolle duplizieren*. +
→ Die Rolle wird kopiert und mit dem Namen *Kopie von [Name der kopierten Rolle]* erstellt .

[#60]
== Benutzer:innen-Konto suchen

Filter helfen dir bei der Suche nach Benutzer:innen-Konten. Ohne Filter werden in der Übersicht alle Benutzer:innen-Konten angezeigt.

[.instruction]
Benutzer:innen-Konten suchen:

. Öffne das Menü *Einrichtung » Kontoverwaltung » Konten*.
. Gib in der Navigation *Filter* die gewünschten Filter ein.
. Klicke auf *Suchen* (material:search[]). +
→ Die Ansicht wird gefiltert.


.Filteroptionen für Benutzer:innen
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Suchen*
|Suche ausführen. Zuvor Filteroptionen zur Suche eingeben oder wählen.

| *Zurücksetzen* (material:refresh[])
|Filtereinstellungen auf Standardwerte zurücksetzen.

| *ID*
|ID eingeben, um gezielt nach einem Benutzer:innen-Konto mit dieser ID zu suchen.

| *Name*
|Name eingeben, um gezielt nach Benutzer:innen-Konten mit diesem realen Namen zu suchen.

|*Benutzer*
| Benutzernamen eingeben, um gezielt nach Benutzer:innen-Konten mit diesem Benutzernamen zu suchen.

| *E-Mail*
|E-Mail wählen, um gezielt nach Benutzer:innen-Konten mit dieser E-Mail zu suchen.
|====

[#150]
== Rollen und Prozesse verknüpfen

Verwende Rollen zum Beispiel auch bei xref:automatisierung:prozesse-einrichten.adoc#[Prozessen].

[.instruction]
Rollen und Prozesse verknüpfen:

. Öffne das Menü *Einrichtung » Prozesse » Pro Rolle*.
. Klicke in der Zeile einer *Rolle* auf den *Pfeil* und dann auf *Neuer Prozess* (Bild 1).
. Gib einen *Namen* für die Rolle ein.
. Wähle für die *Sichtbarkeit* die Einstellung *Rolle*. +
→ Die Option *Rolle* wird eingeblendet.
. Wähle eine *Rolle* aus der Dropdown-Liste.
. Wähle, ob die Einstellungen durch einen Eigner mit dieser Rolle *änderbar* sein sollen.
. Wähle das *Lager* für den Prozess und eine *Farbe*.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

Die Prozesse werden für die gewählte Rolle angezeigt. Aufgrund der Sichtbarkeit sieht nur ein Benutzer:innen-Konto mit passender Rolle den Prozess.

[#153]
== Konto für das plentymarkets Forum erstellen

include::partial$forum-konto.adoc[]

[#160]
== Anzahl eingeloggter Benutzer:innen-Konten verwalten

Abhängig von deiner plentymarkets Edition ist die Anzahl der Benutzer:innen-Konten, die gleichzeitig in plentymarkets eingeloggt sein dürfen, möglicherweise beschränkt. Dieses Limit gilt für das plentymarkets Backend, die REST-API und die plentymarkets App.

Das kannst du tun, wenn du das Benutzerlimit erreichst:

* Eingeloggte Personen auffordern, sich manuell auszuloggen
* <<#170, Benutzerkonten über die Session-Verwaltung ausloggen>>
* <<#190, Benutzerlimit deines plentymarkets Vertrags erhöhen>>


[#170]
=== Benutzer:innen-Konten ausloggen

Gehe wie unten beschrieben vor, um Benutzer:innen-Konten auszuloggen.

[NOTE]
.Administratorrechte erforderlich
====
Du benötigst Administratorrechte, um Benutzer:innen-Konten über die Session-Verwaltung auszuloggen.
====

[.instruction]
Benutzer:innen-Konten ausloggen:

. Öffne das Menü *Einrichtung » Kontoverwaltung » Konten*.
. Klicke auf *Suchen* (material:search[]).
→ Alle Benutzer:innen-Konten werden angezeigt. +
. Aktiviere die Kontrollkästchen der Benutzer:innen-Konten, deren Session du beenden möchtest, um sie auszuloggen.
. Klicke auf *Mehr* (material:more_vert[]). +
→ Ein Dropdown-Menü klappt aus.
. Klicke auf *Logout*. +
→ Die gewählten Benutzer:innen-Konten werden ausgeloggt.

[#180]
=== Benutzer:innen-Konten ausloggen, wenn Benutzerlimit überschritten ist

Wenn die zulässige Anzahl gleichzeitig eingeloggter Benutzer:innen-Konten bereits erreicht oder überschritten ist, können nicht eingeloggte Administratoren das Menü *Einrichtung » Kontoverwaltung » Konten* über einen Link in der eingeblendeten Fehlermeldung erreichen.

[.instruction]
Benutzer:innen-Konten ausloggen, wenn Benutzerlimit überschritten ist:

. Logge dich in das plentymarkets Backend ein. +
→ Eine Fehlermeldung wird angezeigt.
. Klicke auf den Link in der Fehlermeldung. +
→ Das Menü *Einrichtung » Kontoverwaltung » Konten* wird geöffnet. +
→ Alle Benutzer:innen-Konten werden angezeigt.
. Aktiviere die Kontrollkästchen der Benutzer:innen-Konten, deren Session du beenden möchtest, um sie auszuloggen.
. Klicke auf *Mehr* (material:more_vert[]). +
→ Ein Dropdown-Menü klappt aus.
. Klicke auf *Logout*. +
→ Die gewählten Benutzer:innen-Konten werden ausgeloggt. +
*_Hinweis:_* Der Login über die Fehlermeldung ist 10 Minuten gültig. Danach wirst du automatisch ausgeloggt.

[#190]
=== Weitere Benutzerlizenzen buchen

Du kannst zusätzliche Benutzerlizenzen im xref:business-entscheidungen:dein-vertrag.adoc#[Bereich "Mein Konto"] buchen.

[.instruction]
Weitere Benutzerlizenzen buchen:

include::partial$konfigurator-aufrufen.adoc[]
