= Cloud-Verbrauch
:keywords: Verbrauch, Verbrauchsdaten, Cloud-Verbrauch, Cloud
:author: team-app-bi
:description: Diese Seite erläutert die Berechnungen, Dimensionen und Filter, die dir für die Kennzahl Cloud-Verbrauch zur Verfügung stehen.

Artikelbilder, Belege, Auftragsdokumente und viele andere Daten deines plentymarkets Systems werden in der Cloud gespeichert. Diese Art von Speicherplatz ist je nach gebuchter plentymarkets Edition begrenzt. Überschreitungen werden separat in Rechnung gestellt. plentymarkets bietet dir daher die Möglichkeit, deinen Cloud-Verbrauch jederzeit nachzuvollziehen.

:kennzahl: Cloud-Verbrauch

include::partial$kennzahlen-einleitung.adoc[]

[#100]
== plentyBI Edition

Dies ist eine kostenlose Kennzahl.
Du kannst die Kennzahl verwenden, ohne vorher eine plentyBI Edition gebucht zu haben.

Beachte jedoch, dass _andere Funktionen und Kennzahlen_ des plentyBI-Tools kostenpflichtig sind.

Buche ganz einfach die passende plentyBI Edition mit Hilfe des plentymarkets Konfigurators.

* *_Neukunden_*: Buche die passende plentyBI Edition link:https://get.plentymarkets.com/[während du plentymarkets bestellst^].
* *_Bestandskunden_*: Buche die passende plentyBI Edition xref:business-entscheidungen:dein-vertrag.adoc#30[im "Mein Konto"-Bereich].

[#150]
== Berechnung

=== Anzahl Artikel

Die Berechnung des Cloud-Verbrauchs basiert auf der Anzahl der Artikel, die in deinem plentymarkets System angelegt sind.

=== Anzahl Varianten

Die Berechnung des Cloud-Verbrauchs basiert auf der Anzahl der Varianten, die in deinem plentymarkets System angelegt sind.

=== CDN-Traffic

Die Berechnung des Cloud-Verbrauchs basiert auf dem CDN-Traffic, der generiert wird, wenn Kund:innen beispielsweise Inhalte in deinem Webshop aufrufen.

=== Datenbank-Speicher

Die Berechnung des Cloud-Verbrauchs basiert auf der Auslastung des Datenbank-Speichers, der von deinem plentymarkets Systems belegt wird.

=== Dokumenten-Speicher

Die Berechnung des Cloud-Verbrauchs basiert auf der Auslastung des Dokumenten-Speichers, der von Auftragsdokumenten und Belegen deines plentymarkets Systems belegt wird.

=== Webinhalte-Speicher

Die Berechnung des Cloud-Verbrauchs basiert auf den von deinem plentymarkets System gespeicherten Webinhalten.

[#200]
== Dimension

=== Erstellungsdatum

:kennzahl: Der Cloud-Verbrauch
:das-bedeutet: Die Verbrauchsdaten werden also nach dem Datum gruppiert, an dem der Verbrauch angefallen ist.

include::partial$erstellungsdatum.adoc[]

[#300]
== Filter

include::partial$filter-einleitung.adoc[]

=== Erstellungsdatum

Verwende diesen Filter, um den Cloud-Verbrauch anhand des Datums oder des Zeitraums zu gruppieren, in dem der Verbrauch angefallen ist.

Wähle einen der folgenden Vergleichsoperatoren aus und wähle dann rechts das gewünschte Datum oder einen Zeitraum.


[.collapseBox]
.Vergleichsoperatoren für diesen Filter
--

:filter-endung: gewählten Terminen
:filter: gewählten Termine
:kommas:

[cols="1,3"]
|====
| Vergleichsoperator | Erklärung

include::partial$ist-gleich.adoc[]

include::partial$liegt-zwischen.adoc[]

include::partial$groesser-als-oder-gleich.adoc[]

include::partial$kleiner-als-oder-gleich.adoc[]

include::partial$groesser-als.adoc[]

include::partial$kleiner-als.adoc[]


|====

--

//Praxisbeispiel (mit Kachel) hinzufügen
