= Cloud-Verbrauch
:keywords: Verbrauch, Verbrauchsdaten, Cloud-Verbrauch, Cloud
:author: team-bi
:description: Diese Seite erläutert die Berechnungen, Dimensionen und Filter, die dir für die Kennzahl Cloud-Verbrauch zur Verfügung stehen.

Artikelbilder, Belege, Auftragsdokumente und viele andere Daten deines plentysystems Systems werden in der Cloud gespeichert. Diese Art von Speicherplatz ist je nach gebuchter plentysystems Edition begrenzt. Überschreitungen werden separat in Rechnung gestellt. plentysystems bietet dir daher die Möglichkeit, deinen Cloud-Verbrauch jederzeit nachzuvollziehen.

:kennzahl: Cloud-Verbrauch

include::partial$kennzahlen-einleitung.adoc[]

[IMPORTANT]
.Standard-Kennzahl nutzen
====
Die Kennzahl *Cloud-Verbrauch* ist eine so genannte Standard-Kennzahl. Das bedeutet, dass sie in deinem plentysystems System bereits mit einigen Voreinstellungen eingerichtet ist. Du musst also nicht zwingend eine zusätzliche Kennzahl erstellen. Öffne das Menü *Einrichtung » plentyBI » Kennzahlen* und klicke auf die Kennzahl *Cloud-Verbrauch*, die von `plentymarkets` erstellt wurde. Passe bei Bedarf die voreingestellten Optionen an und ergänze die gewünschten <<#300, Filter>>.
====

[#100]
== plentyBI Edition

Dies ist eine kostenlose Kennzahl.
Du kannst die Kennzahl verwenden, ohne vorher eine plentyBI Edition gebucht zu haben.

Beachte jedoch, dass _andere Funktionen und Kennzahlen_ des plentyBI-Tools kostenpflichtig sind.

Buche ganz einfach die passende plentyBI Edition mit Hilfe des plentysystems Konfigurators.

* *_Neukunden_*: Buche die passende plentyBI Edition link:https://get.plentymarkets.com/[während du plentysystems bestellst^].
* *_Bestandskunden_*: Buche die passende plentyBI Edition xref:business-entscheidungen:dein-vertrag.adoc#30[im "Mein Konto"-Bereich].

[#150]
== Berechnung

=== Anzahl Artikel

Die Berechnung des Cloud-Verbrauchs basiert auf der Anzahl der Artikel, die in deinem plentysystems System angelegt sind.

=== Anzahl Varianten

Die Berechnung des Cloud-Verbrauchs basiert auf der Anzahl der Varianten, die in deinem plentysystems System angelegt sind.

=== CDN-Traffic

Die Berechnung des Cloud-Verbrauchs basiert auf dem CDN-Traffic, der generiert wird, wenn Kund:innen beispielsweise Inhalte in deinem Webshop aufrufen.

=== Datenbank-Speicher

Die Berechnung des Cloud-Verbrauchs basiert auf der Auslastung des Datenbank-Speichers, der von deinem plentysystems Systems belegt wird.

=== Dokumenten-Speicher

Die Berechnung des Cloud-Verbrauchs basiert auf der Auslastung des Dokumenten-Speichers, der von Auftragsdokumenten und Belegen deines plentysystems Systems belegt wird.

=== Webinhalte-Speicher

Die Berechnung des Cloud-Verbrauchs basiert auf den von deinem plentysystems System gespeicherten Webinhalten.

[#200]
== Dimension

=== Erstellungsdatum

:kennzahl: Der Cloud-Verbrauch
:das-bedeutet: Die Verbrauchsdaten werden also nach dem Datum gruppiert, an dem der Verbrauch angefallen ist.

include::partial$erstellungsdatum.adoc[]

[#300]
== Filter

include::partial$filter-einleitung.adoc[]

=== Erstellungsdatum

Verwende diesen Filter, um den Cloud-Verbrauch anhand des Datums oder des Zeitraums zu gruppieren, in dem der Verbrauch angefallen ist.

Wähle einen Vergleichsoperator aus und wähle dann rechts das gewünschte Datum oder einen Zeitraum.

//TODO: Praxisbeispiel (mit Kachel) hinzufügen
