= E-Mail-Postfächer verwalten
:keywords: E-Mail, Postfach, Postfach erstellen, Grundtarif, Postfach verwalten
:description: Arbeiten mit plentymarkets: Verwalte E-Mail-Postfächer, lege neue E-Mail-Postfächer an und bearbeite bestehende E-Mail-Postfächer im plentymarkets System.
:author: Dennis Schulze

[#10]
== E-Mail-Postfächer verwalten

Wenn du deine Domains von plentymarkets verwalten lässt, kannst du als Person mit Admin-Rechten im Menü *Einrichtung » Einstellungen » E-Mail* E-Mail-Postfächer für Systembenutzer:innen erstellen und verwalten. Diese E-Mail-Postfächer werden bei einem Drittanbieter, dem externen E-Mail-Provider link:https://mailbox.org/business/[mailbox.org^], angelegt und von diesem Drittanbieter gehostet. Nachfolgend wird beschrieben, wie du E-Mail-Postfächer und zusätzliche E-Mail-Adressen pro Postfach (Alias) erstellst.

[IMPORTANT]
.E-Mail-Postfächer anderer Provider
====
Die hier beschriebene Einrichtung gilt nur für plentymarkets Kund:innen, die ihre Domains von plentymarkets verwalten lassen und die den externen Dienstleister link:https://mailbox.org/business/[mailbox.org^] nutzen möchten. Wenn du deine E-Mail-Konten über einen anderen Provider verwaltest und darüber E-Mails durch dein plentymarkets System versenden möchtest, ist diese Einrichtung nicht erforderlich. Beachte aber auch dann das Kapitel xref:crm:emailbuilder.adoc#e-mail-server-zugangsdaten[E-Mail-Server-Zugangsdaten speichern] auf der Handbuchseite xref:crm:emailbuilder.adoc#[EmailBuilder].
====

[#20]
=== Postfach erstellen

Lege für Benutzer:innen, die ein eigenes Postfach bei mailbox.org erhalten sollen, wie unten beschrieben ein Postfach an. Du benötigst Admin-Rechte, um Postfächer und Alias anzulegen.

[.instruction]
Neues Postfach erstellen:

. Öffne das Menü *Einrichtung » Einstellungen » E-Mail*.
. Klicke auf *Postfach erstellen* (material:add[role=green]). +
→ Das Fenster *Postfach erstellen* wird angezeigt.
. Wähle als E-Mail-Adresstyp *Postfach*.
. Nimm die weiteren Einstellungen vor. Beachte dazu die Erläuterungen in <<tabelle-postfach>>.
. Klicke auf *Postfach erstellen*. +
→ Das E-Mail-Postfach wird beim externen Dienstleister mailbox.org erstellt.

[[tabelle-postfach]]
.Postfach erstellen
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *E-Mail-Adresstyp*
|E-Mail-Adresstyp *Postfach* wählen. +
*Postfach* = Legt ein neues E-Mail-Postfach an. +
*Alias* = Legt eine zusätzliche E-Mail-Adresse für ein bestehendes Postfach an. Die Auswahl des Postfachs erfolgt über die Option *Zielpostfach*.

| *E-Mail-Adresse*
|E-Mail-Adresse eingeben, die dem Postfach zugeordnet werden soll. Lokalen Teil der E-Mail-Adresse vor dem @ eingeben. Domain-Teil aus der Dropdown-Liste wählen. +
*_Hinweis:_* Für Testdomains, zum Beispiel @plenty-test-drive, sowie für externe Domains, die nicht über plentymarkets verwaltet werden, können keine Postfächer angelegt werden. +
*_Hinweis:_* Nach dem Löschen einer E-Mail-Adresse ist diese Adresse 48 Stunden gesperrt. Erst nach Ablauf dieser Frist kann diese E-Mail-Adresse erneut vergeben werden.

| *Vorname* +
*Nachname*
|Vornamen und Nachnamen der Person mit diesem Benutzer:innen-Konto eingeben. Dieser Name wird mit der E-Mail-Adresse als Absender angezeigt.

| *Systembenutzer*
|Benutzer:innen-Konto wählen, dem das Postfach zugewiesen werden soll.

| *Weiterleitungen*
|Wenn E-Mails, die an dieses Postfach gesendet werden, an ein anderes Postfach weitergeleitet werden sollen, eine oder mehrere E-Mail-Adressen eingeben. Mehrere E-Mail-Adressen durch Komma getrennt hinterlegen, zum Beispiel kunde@ihredomain.de,consultant@ihredomain.de.

| *E-Mails in Postfach speichern*
|Option wird wählbar, wenn eine Weiterleitung eingerichtet wird. +
Aktiviert = E-Mails werden an die Ziel-E-Mail-Adressen weitergeleitet. Kopien der weitergeleiteten E-Mails werden auch in diesem Postfach gespeichert. +
Nicht aktiviert = E-Mails werden direkt an die Ziel-E-Mail-Adressen weitergeleitet. In diesem Postfach werden keine E-Mails gespeichert.

| *Passwort*; +
*Passwort wiederholen*
|Passwort eingeben und durch erneute Eingabe bestätigen. +
*_Hinweis:_* Passwort muss aus mindestens 8 Zeichen und einer Kombination aus Großbuchstaben, Kleinbuchstaben und Zahlen bestehen.

| *Tarif*
|Tarif wählen. Preise gelten zzgl. MwSt. Dein plentymarkets Vertrag wird nach dem Erstellen des Postfachs angepasst.
|====

==== Zugangsdaten für mailbox.org-Server in plentymarkets hinterlegen

Damit plentymarkets E-Mails, zum Beispiel Auftragsbestätigungen, für dich versenden kann, speichere im Assistenten xref:crm:emailbuilder.adoc#e-mail-server-zugangsdaten[E-Mail-Konten] im Menü *Einrichtung » Assistenten » Grundeinrichtung* die link:https://kb.mailbox.org/de/privat/e-mail-artikel/e-mail-einrichtung-allgemein[Zugangsdaten^] zu dem mailbox.org-Postfach, über das du diese E-Mails versenden möchtest.

[#30]
=== Zusätzliche E-Mail-Adresse (Alias) für ein Postfach erstellen

Wenn ein Postfach über mehr als eine E-Mail-Adresse erreichbar sein soll, erstelle ein Alias für das Postfach. Die Anzahl der möglichen E-Mail-Adressen pro Postfach ist vom gewählten Tarif abhängig. Gehe wie unten beschrieben vor, um eine zusätzliche E-Mail-Adresse für ein Postfach zu erstellen.

[.instruction]
Zusätzliche E-Mail-Adresse für ein Postfach erstellen:

. Öffne das Menü *Einrichtung » Einstellungen » E-Mail*.
. Klicke auf *Postfach erstellen* (material:add[role=green]). +
→ Das Fenster *Postfach erstellen* wird angezeigt.
. Wähle als E-Mail-Adresstyp *Alias*.
. Nimm die weiteren Einstellungen vor. Beachte dazu die Erläuterungen in <<#tabelle-e-mail-adresssen>>.
. Klicke auf *Postfach erstellen*. +
→ Die zusätzliche E-Mail-Adresse wird erstellt.

[[tabelle-e-mail-adresssen]]
.Zusätzliche E-Mail-Adresse für ein Postfach erstellen
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *E-Mail-Adresstyp*
|E-Mail-Adresstyp *Alias* wählen. +
*Postfach* = Legt ein neues E-Mail-Postfach an. +
*Alias* = Legt eine zusätzliche E-Mail-Adresse für ein bestehendes Postfach an. Die Auswahl des Postfachs erfolgt über die Option *Zielpostfach*.

| *E-Mail-Adresse*
|E-Mail-Adresse eingeben, die dem Postfach zugeordnet werden soll: Lokalen Teil der E-Mail-Adresse vor dem @ eingeben. Den Domain-Teil aus der Dropdown-Liste wählen. +
*_Hinweis:_* Nach dem Löschen einer E-Mail-Adresse ist diese Adresse 48 Stunden gesperrt. Erst nach Ablauf dieser Frist kann diese E-Mail-Adresse erneut vergeben werden.

| *Zielpostfach*
|Das Postfach wählen, in das E-Mails an diese Alias-Adresse eingehen sollen.
|====

[#40]
=== Grundtarif ändern

Standardmäßig gilt für das Hosting von Postfächern bei mailbox.org über plentymarkets der mailbox.org-Grundtarif *Business Reseller*. Dieser Grundtarif ist für dich kostenlos, umfasst jedoch keinen Support von mailbox.org. Den Grundtarif kannst du jederzeit anpassen. Wenn du Support von mailbox.org wünschst oder den Leistungsumfang erweitern möchtest, passe deinen Grundtarif an. Der gewählte Grundtarif gilt für alle Postfächer deines gesamten plentymarkets Systems inklusive aller Mandaten.

[.instruction]
Grundtarif ändern:

. Öffne das Menü *Einrichtung » Einstellungen » E-Mail*.
. Klicke auf *Grundtarif ändern* (material:edit[]). +
→ Das Fenster *Grundtarif wählen* wird angezeigt.
. Prüfe den Leistungsumfang der angebotenen Grundtarife.
. Wähle den gewünschten Grundtarif.
. Klicke auf *Grundtarif ändern*. +
→ Der Tarif wird übernommen und dein plentymarkets Vertrag wird angepasst. Du erhältst außerdem eine E-Mail mit weiteren Informationen von mailbox.org.

[#50]
=== Postfach löschen

Gehe wie unten beschrieben vor, um ein Postfach zu löschen. Du benötigst Admin-Rechte, um Postfächer/Alias zu löschen. Nach dem Löschen eines Postfachs/Alias kannst du erst nach 48 Stunden wieder ein neues Postfach/Alias mit der gelöschten E-Mail-Adresse erstellen.

[WARNING]
.E-Mails nach dem Löschen des Postfachs nicht mehr zugänglich
====
Nach dem Löschen eines Postfachs kannst du über mailbox.org nicht mehr auf die in diesem Postfach gespeicherten E-Mails zugreifen. Stelle sicher, dass von allen benötigten E-Mails eine lokale Kopie vorhanden ist.
====

[.instruction]
Postfach löschen:

. Öffne das Menü *Einrichtung » Einstellungen » E-Mail*. +
→ Eine Liste der Postfächer wird angezeigt.
. Klicke in der Liste auf das Postfach, das du löschen möchtest.
. Klicke auf *Löschen* (material:remove[role="red"]). +
→ Das Postfach und alle damit verbundenen Alias werden bei mailbox.org gelöscht. +
→ Dein plentymarkets Vertrag wird angepasst.