= Verbrauchsdaten
:keywords: Host, Hosting, Hoster, Webhosting, Hosting-Daten, Datenvolumen, Datenmenge, Traffic, Verbrauchsdaten, Speicherverbrauch, Ressourcen
:description: Erfahre mehr über Verbrauchsdaten und wie Traffic entsteht.
:author: team-cloud

Das Datenvolumen und der zulässige Traffic sind je nach gebuchter plentysystems Edition begrenzt. Überschreitungen werden separat in Rechnung gestellt. plentysystems bietet dir daher die Möglichkeit, deinen Verbrauch jederzeit nachzuvollziehen.

Die Verbrauchsdaten werden im Menü *plentysystems Logo (Start) » Hosting* angezeigt.
Klicke auf eines der Untermenüs links, um die entsprechenden Daten aufzurufen.

[TIP]
.Verbrauchsdaten im Dashboard anzeigen
====
Wusstest du schon, dass du die Verbrauchsdaten deines Systems auch auf dem Dashboard anzeigen kannst?
Richte dazu zunächst die kostenlose Kennzahl xref:business-entscheidungen:traffic-usage.adoc#[Traffic-Verbrauch] ein. Platziere danach ein Element vom Typ xref:business-entscheidungen:myview-dashboard.adoc#500[Kachel] auf dem Dashboard, um die Kennzahl und damit den Verbrauch jederzeit bequem einzusehen.
====

[#100]
[discrete]
=== Wissenswertes zum Thema Traffic

Traffic entsteht, wenn Personen deinen Webshop besuchen und dort zum Beispiel Artikel anklicken, Bilder vergrößern oder Dateien herunterladen.

Zusätzlicher Traffic entsteht außerdem in den folgenden Fällen:

* Beim Austausch von Daten mit Marktplätzen.
* Bei REST-Abfragen, da bei diesen Abfragen Verbindungen zum Server aufgebaut werden. +
*_Tipp:_* Je nach Art der Abfrage ist das Datenvolumen beträchtlich. Optimiere daher deine Calls, indem du zum Beispiel nicht ständig alle Bestände abfragen, sondern die Abfrage auf Änderungen beschränkst.
* Beim Scannen deiner Website durch link:http://de.wikipedia.org/wiki/Webcrawler[Bots^]. Diese Bots speichern deine Seiten, wodurch Traffic entsteht. Wenn zum Beispiel der Google-Bot deine Seite erfasst hat, werden bei einer Google-Suche Artikel aus deinem Shop mit Beschreibung etc. angezeigt. Wann solche Bots deine Seite besuchen, ist nicht vorhersehbar, da Bots nach proprietären Algorithmen gesteuert werden. +
*_Tipp:_* Um dieses Verhalten von Bots zumindest teilweise zu steuern, kannst du die xref:webshop:ceres-einrichten.adoc#203[Sperrung von Bots] per robots.txt-Datei veranlassen.
* Bei Erweiterungen deines Sortiments und damit einer Vergrößerung des Bild- und Datenaufkommens. Dadurch werden mehr Bots auf deine Seite aufmerksam.
