= Listings (Live)
:keywords: Listings, Marktplatz-Listings, Listing Lives, Listings live überprüfen, Listing Status, Listing Kennzahl, Business Intelligence, Statistik, Statistiken, Kennzahl, Kennzahlen, Dashboard
:description: Diese Seite erläutert die Berechnungen, Dimensionen und Filter, die dir für die Kennzahl Listings (Live) zur Verfügung stehen.
:author: team-bi

:kennzahl: Listings (Live)

include::partial$kennzahlen-einleitung.adoc[]

plentysystems berechnet die Liveanzahl der Listings, indem die Listings und deren Status auf den jeweiligen Marktplätzen in Echtzeit anhand der Datenbank überprüft und geladen werden. 

[IMPORTANT]
.Begrenzte Datenverfügbarkeit
====
Die Ergebnisse der Kennzahl sind auf den Zeitraum des Vortages bis zum aktuellen Tag beschränkt. Es ist also nicht möglich, weiter zurückliegende Daten zu Listings auszuwerten.

====

[#100]
== Berechnung

=== Gesamt

:kennzahl: Die Kennzahl Listings (Live)
:das-bedeutet: Das bedeutet, dass die Listings gemäß der gewählten Dimension und den Filtern zusammengerechnet und in Echtzeit dargestellt werden.

include::partial$gesamt.adoc[]

[#200]
== Dimension

=== Listings

Die Anzahl der Listings wird live der Datenbank entnommen.

[#300]
== Filter

Mithilfe der folgenden drei Filter kannst du die Ergebnisse der Kennzahl Listings (Live) weiter nach deinen Bedürfnissen einschränken.

=== Erfolgreich

Wähle den Filter *Erfolgreich* mit dem Vergleichsoperator *Ist gleich* und der Option *Erfolgreich*, um nach Listings zu filtern, die erfolgreich veröffentlicht wurden. Nutze alternativ die Option *Nicht erfolgreich*, um gezielt nach fehlgeschlagenen Listings zu filtern.

=== Marktplatz

Wähle den Filter *Marktplatz* in Verbindung mit dem Vergleichsoperator *Entspricht einem dieser Werte*, um mithilfe der Option *Martkplatz* nach einem, mehreren oder allen Marktplätzen zu filtern, auf denen du mit Listings arbeitest. Nutze alternativ den Vergleichsoperator *Entspricht keinem dieser Werte*, um ausgewählte Marktplätze von der Auswertung der Listings auszuschließen.

=== Prüfung

Wähle den Filter *Prüfung* mit dem Vergleichsoperator *Ist gleich* und der Option *Erfolgreich*, um nach Listings zu filtern, deren Prüfung beim Marktplatz erfolgreich durchlaufen wurde. Nutze alternativ die Option *Fehlgeschlagen*, um gezielt nach fehlgeschlagenenen Listing-Prüfungen zu filtern.




