= Aufträge (Live)
:keywords: Aufträge, Auftragsanzahl, Aufträge in Echtzeit, Auftragsstatus, Anzahl Aufträge, eingegangene Aufträge, Business Intelligence, Statistik, Statistiken, Kennzahl, Kennzahlen, Dashboard
:page-aliases: auftraege-live.adoc
:description: Diese Seite erläutert die Berechnungen, Dimensionen und Filter, die dir für die Kennzahl Aufträge (Live) zur Verfügung stehen.
:author: team-bi

:kennzahl: Aufträge (Live)

include::partial$kennzahlen-einleitung.adoc[]

plentysystems berechnet die Liveanzahl der Aufträge, indem die Aufträge und der Auftragsstatus in Echtzeit anhand der Datenbank überprüft und geladen werden. +
Wähle zusätzlich eine xref:business-entscheidungen:auftraege-live.adoc#200[Dimension] um festzulegen, wie das Ergebnis aufgeschlüsselt werden soll.
Setze außerdem xref:business-entscheidungen:auftraege-live.adoc#300[Filter] um zu konkretisieren, nach welchen Kriterien die Aufträge berechnet und dargestellt werden sollen.
Beachte, dass die Aufträge gezählt werden, die du im Filter *Auftragstyp* definierst. Setzt du diesen Filter nicht, werden alle Auftragstypen genommen.

[IMPORTANT]
.Standard-Kennzahl nutzen
====
Die Kennzahl *Aufträge (Live)* ist eine so genannte Standard-Kennzahl. Das bedeutet, dass sie in deinem plentysystems System bereits mit einigen Voreinstellungen eingerichtet ist. Du musst also nicht zwingend eine zusätzliche Kennzahl erstellen. Öffne das Menü *Einrichtung » plentyBI » Kennzahlen* und klicke auf die Kennzahl *Aufträge (Live)*, die von `plentymarkets` erstellt wurde. Passe bei Bedarf die voreingestellten Optionen an und ergänze die gewünschten <<#300, Filter>>.
====

[#400]
== plentyBI Edition

include::partial$kennzahlen-voraussetzungen-edition.adoc[]

[#100]
== Berechnung

=== Gesamt

:kennzahl: Die Kennzahl Aufträge (Live)
:das-bedeutet: Das bedeutet, dass die Aufträge gemäß der gewählten Dimension und den Filtern zusammengerechnet und in Echtzeit dargestellt werden.

include::partial$gesamt.adoc[]

[#200]
== Dimension

=== Auftrag

Die Auftragsanzahl wird in Echtzeit angezeigt. Die Daten werden live der Datenbank entnommen. Es werden alle Auftragstypen eingerechnet, wenn du den Filter *Auftragstyp* nicht setzt und keine Auswahl triffst.

=== Auftragsstatus, Auftrag

Es wird in Echtzeit angezeigt, wie viele Aufträge sich in den verschiedenen Auftragsstatus befinden. Die Daten werden der Datenbank entnommen. Es werden alle Auftragsstatus eingerechnet, wenn du den Filter *Auftragsstatus* nicht setzt und keine Auswahl triffst.

[#300]
== Filter

include::partial$filter-einleitung.adoc[]

// Auftragsherkunft

include::partial$auftragsherkunft.adoc[]

// Auftragsstatus

include::partial$auftragsstatus.adoc[]

_Beachte_, dass alle Auftragsstatus angezeigt werden, wenn du hier keine Auswahl triffst.

// Auftragstyp

include::partial$auftragstyp.adoc[]

// Erstellt

include::partial$erstellt.adoc[]

// Lager

include::partial$lager.adoc[]

Beachte, dass beim Setzen dieses Filters Hauptaufträge herausgefiltert werden.

// Mandant

include::partial$mandant.adoc[]

// Warenausgang gebucht

include::partial$warenausgang-gebucht.adoc[]

// Zahlungsstatus

include::partial$zahlungsstatus.adoc[]

