= Kennzahlen anlegen und verwalten
:keywords: 
:author: team-app-bi
:description: Erfahre, wie du in plentymarkets Kennzahlen anlegen und verwalten kannst.

////
TODO: Einleitung: Was sind Kennzahlen, wozu brauche ich sie, wann sollte ich sie erstellen? Am besten mit Beispiel. Zusammenhang mit BI Dashboard darstellen.
////

////
TODO: #200 und #300 aus myview-dashboard.adoc entfernen. Verlinkungen überprüfen
////

[#100]
== Kennzahlen anlegen

[IMPORTANT]
.Kennzahlen je nach plentyBI Edition verfügbar
====
Manche Kennzahlen können nur angelegt werden, wenn du zuvor eine bestimmte plentyBI Edition gebucht hast. Öffne dazu das Menü *plentymarkets Logo (Start) » Mein Konto » Verträge*. Klicke auf *Vertrag bearbeiten* und gehe zum Schritt *plentyBI Edition wählen*. Hier stehen dir plentyBI Editionen mit verschiedenen Umfängen zur Auswahl. Zusätzlich wird auch beim Anlegen einer neuen Kennzahl im Menü *Einrichtung » plentyBI » Kennzahlen* pro Kennzahl angezeigt, in welcher plentyBI Edition sie enthalten ist.
====

Damit Daten im Dashboard angezeigt werden können, musst du zuerst entsprechende Kennzahlen anlegen.

Kennzahlen erlauben dir, verschiedene Datensätze zusammenzustellen. Kennzahlen liefern somit die Basis für die Werte und Daten, die du später auf dem Dashboard anzeigen und nachverfolgen kannst. Pro Kennzahl werden von deinem plentymarkets System sogenannte Dimensionen bereitgestellt. Dimensionen bestimmen, nach welchen Kriterien die Daten der Kennzahl gruppiert werden.
So kannst du pro Kennzahl genau eingrenzen, wie die Daten pro Kennzahl berechnet werden sollen.

Kennzahlen legst du entweder im Menü *Einrichtung » plentyBI » Kennzahlen* oder direkt aus dem Dashboard heraus an. Im Folgenden werden beide Vorgehensweisen erklärt.

[NOTE]
.Benutzerrechte beachten
====
Falls Benutzer:innen ohne Admin-Zugang zu deinem plentymarkets System Kennzahlen anlegen sollen, vergib zuerst die <<#300, notwendigen Benutzerrechte>>.
====

[tabs]
====
Kennzahlen im Einrichtungsmenü anlegen::
+
--

Diese Vorgehensweise bietet sich an, wenn du viele verschiedene Kennzahlen auf einmal anlegen möchtest. <<table-create-key-figures>> enthält eine Auflistung der verfügbaren xref:business-entscheidungen:myview-dashboard.adoc#intable-keyfigure[Kennzahlen]. Klicke auf den jeweiligen Link, um detaillierte Informationen zur Einrichtung der Kennzahl und den verfügbaren Einstellungen zu erhalten.

[.instruction]
Kennzahlen im Einrichtungsmenü anlegen:

. Öffne das Menü *Einrichtung » plentyBI » Kennzahlen*.
. Nimm die Einstellungen gemäß <<table-create-key-figures>> vor.
. Speichere (terra:save[]) die Einstellungen.

[[table-create-key-figures]]
.Kennzahlen anlegen
[cols="1,3"]
|======
|Einstellung |Erläuterung

| *Name*
| Gib einen Namen für die Kennzahl an.

| [#intable-keyfigure]*Kennzahl*
| Wähle die Kennzahl, die du anlegen möchtest. Eine Liste mit verfügbaren Kennzahlen findest du auf der Handbuchseite xref:business-entscheidungen:kennzahlen.adoc#[Kennzahlen].

| *ID*
| Nachdem du eine Kennzahlkonfiguration angelegt hast, wird in diesem Feld eine vom System vergebene ID angezeigt. Diese kannst du nicht bearbeiten.

| *Aktualisiert am*
| Zeitpunkt der letzten Bearbeitung der Kennzahlkonfiguration.

| *Erstellt am*
| Zeitpunkt der Erstellung der Kennzahlkonfiguration.

| *Erstellt von* 
| Benutzername der Ersteller:in der Kennzahlkonfiguration. Klicke auf das Schloss neben dem Namen, um die Kennzahlkonfiguration zu sperren. So kann nur der Benutzer, der die Konfiguration erstellt hat, Änderungen an dieser vornehmen.

| *Kommentar*
| Gib hier bei Bedarf einen Kommentar zur Kennzahl ein. Der Kommentar wird an der Kennzahl gespeichert und gibt dir und deinen Mitarbeiter:innen schnell Einblick in eventuelle Besonderheiten oder Vermerke für die Kennzahl.

2+^| Bereich *Zielwerte*

| [#intable-targetvalue]*für Tage und Wochen*, *für Monate*, *für Quartale*, *für Jahre*
| Trage Zielwerte ein, die von der Kennzahl erreicht werden sollen. Je nach gewünschtem Zeitraum kannst du hier flexibel die Zielwerte eintragen, die du für die Kennzahl planst.

|======
--

Kennzahlen im Dashboard anlegen::
+
--

Möchtest du direkt in einem neuen oder bereits eingerichteten Dashboard Kennzahlen hinzufügen? Dann gehe wie unten beschrieben vor.

[.instruction]
Kennzahlen im Dashboard anlegen:

. Öffne das Menü *plentymarkets Logo (Start) » Dashboard*.
. Klicke auf *Ansicht bearbeiten* (terra:design_inline_edit[]). +
→ Das Einstellungsmenü öffnet sich.
. Platziere per Drag-and-drop ein Element aus dem Einstellungsmenü auf dem Dashboard.
. Bewege den Mauszeiger über das Element und klicke auf (terra:design_inline_edit[]). +
→ Das Einstellungsmenü für das Element öffnet sich.
. Platziere per Drag-and-drop ein Element innerhalb der blau umrandeten Fläche.
. Bewege den Mauszeiger über das Element und klicke auf (terra:design_inline_edit[]).
. Klicke im Einstellungsmenü auf *Kennzahl* und wähle die Option *Neue Kennzahl erstellen*. +
→ Ein Fenster zur Einrichtung der neuen Kennzahl öffnet sich.
. Gib einen *Namen* für die Kennzahl ein.
. Nimm die Einstellungen wie in <<table-create-key-figures>> beschrieben vor.
. Klicke auf *Speichern* (terra:save[]).

IMPORTANT: Beim Anlegen neuer Kennzahlen über das Dashboard ist es nicht möglich, xref:business-entscheidungen:myview-dashboard.adoc#intable-targetvalue[Zielwerte] für diese Kennzahlen einzugeben. Diese Einstellungen kannst du jedoch im Nachhinein im Menü *Einrichtung » plentyBI » Kennzahlen* für die entsprechende Kennzahl ergänzen.
--
====

[#300]
=== Berechtigungen vergeben

Bei der Arbeit mit Kennzahlen solltest du entscheiden, welche Mitarbeiter:innen welche Kennzahlen einsehen dürfen. Benutzer:innen mit Admin-Zugang zu deinem plentymarkets System können alle Kennzahlen einsehen sowie neue Kennzahlen anlegen.
Benutzer:innen mit einem Zugang vom Typ *Backend* muss diese Berechtigung durch eine:n Benutzer:in mit Admin-Zugang erteilt werden.

Gehe wie unten beschrieben vor, um festzulegen, welche Kennzahlen für welche Benutzer:innen sichtbar sein sollen.

[.instruction]
Berechtigungen zur Ansicht von Kennzahlen erteilen:

. Öffne das Menü *Einrichtung » Einstellungen » Benutzer » Rechte » Benutzer*. +
→ Die Übersicht wird geöffnet. +
*_Optional:_* Gib in den Filtereinstellungen links eine ID oder einen Namen ein, um die Suche einzuschränken.
. Klicke auf *Suchen* (icon:search[role="blue"]). +
→ Die gefundenen Konten werden angezeigt. +
*_Tipp:_* Ausgegraute Konten haben Admin-Rechte.
. Klicke auf das gewünschte Konto.
. Klicke auf *Ressourcen*.
. Klicke auf *Kennzahlen*.
. Aktiviere alle Kennzahlen, die für das Benutzerkonto sichtbar sein sollen. +
*_Optional:_* Klicke auf *Alle Kennzahlen*, wenn sämtliche Kennzahlen für das Benutzerkonto sichtbar sein sollen.
. *Speichere* (terra:save[]) die Einstellungen.

Du möchtest Mitarbeiter:innen ohne Admin-Zugang zum System erlauben, Kennzahlen anzulegen? Dann nimm zusätzlich noch die folgenden Einstellungen vor.

////
TODO: Einstellungen zum Import externer Kennzahlen aus Google Tabellen. Welche Berechtigungen? Welcher Login? PID- und nutzerbasierte Einschränkungen/Freigaben. Erklärungen der Optionen und Empfehlungen für Einstellungen, z.B. Datumsformat im Google Sheet
////

////
TODO: Liste mit Anwendungsbeispielen, z.B. Live-Aufträge, Umsatz des letzten Monats, Absatz nach Marktplatz, Retourenquote nach Artikelkategorie
////
