= Zahlungen (Live)
:keywords: Zahlungen, Zahlungen in in Echtzeit, Zahlungseingänge in Echtzeit, Anzahl Zahlungen, eingegangene Zahlungen, Business Intelligence, Statistik, Statistiken, Kennzahl, Kennzahlen, Dashboard
:description: Diese Seite erläutert die Berechnungen, Dimensionen und Filter, die dir für die Kennzahl Zahlungen (Live) zur Verfügung stehen.
:author: team-app-bi

:kennzahl: Zahlungen (Live)

include::partial$kennzahlen-einleitung.adoc[]

plentymarkets berechnet die Liveanzahl der Zahlungen, indem die Zahlungseingänge, der Zahlungsstatus und die Zahlugnsart in Echtzeit anhand der Datenbank überprüft und geladen werden. +
Wähle zusätzlich eine xref:business-entscheidungen:auftraege-live.adoc#200[Dimension] um festzulegen, wie das Ergebnis aufgeschlüsselt werden soll.
Setze außerdem xref:business-entscheidungen:auftraege-live.adoc#300[Filter] um zu konkretisieren, nach welchen Kriterien die Zahlungen berechnet und dargestellt werden sollen.

[IMPORTANT]
.Standard-Kennzahl nutzen
====
Die Kennzahl *Zahlungen (Live)* ist eine so genannte Standard-Kennzahl. Das bedeutet, dass sie in deinem plentymarkets System bereits mit einigen Voreinstellungen eingerichtet ist. Du musst also nicht zwingend eine zusätzliche Kennzahl erstellen. Öffne das Menü *Einrichtung » plentyBI » Kennzahlen* und klicke auf die Kennzahl *Zahlungen (Live)*, die von `plentymarkets` erstellt wurde. Passe bei Bedarf die voreingestellten Optionen an und ergänze die gewünschten <<#300, Filter>>.
====

[#100]
== plentyBI Edition

include::partial$kennzahlen-voraussetzungen-edition.adoc[]

[#200]
== Dimension

=== Zahlung

Die Zahlungen werden in Echtzeit angezeigt. Die Daten werden live der Datenbank entnommen.

=== Zahlung, Zahlungsart

Es wird in Echtzeit angezeigt, welche Zahlungen mit welchen Zahlungsarten eingegangen sind. Die Daten werden der Datenbank entnommen.

[#300]
== Filter

include::partial$filter-einleitung.adoc[]

// Zugeordnet

// Erhalten am

// Importiert am

// Zugeordnet am

// Zahlungsart

////

ToDO: Filterbeschreibungen ergänzen / Übersetzung / UI Texte / nav.adoc aktualisieren

Azure:

https://dev.azure.com/plentymarkets/plentymarkets/_workitems/edit/35169

https://dev.azure.com/plentymarkets/plentymarkets/_workitems/edit/42017

////