= plentyBI
:keywords: BI, Business Intelligence, plentyBI Übersicht, plentyBI Funktionen, plenty BI
:description: Erfahre mehr über die Tools in plentymarkets, die dir helfen, clevere Geschäftsentscheidungen zu treffen.
:id: CC4EFZF
:author: team-app-bi

[#100]
== Was ist plentyBI?

Bei plentyBI handelt es sich um ein Business Intelligence Tool, das direkt in deinem plentymarkets System integriert ist. Mit plentyBI verfolgst du jederzeit den Stand wichtiger Kennzahlen und Daten deines Unternehmens. Vielfältige Einstellungsmöglichkeiten erlauben dir, jederzeit für Transparenz zu sorgen und clevere Geschäftsentscheidungen zu treffen. 

[#200]
== Welche Schritte gehören zur Einrichtung?

Die Einrichtung von plentyBI besteht aus zwei zentralen Schritten. Durch die Einrichtung von Kennzahlen schaffst du zuerst eine Datengrundlage, die du dann auf deinem individuellen Dashboard anzeigst und auswertest.

** xref:business-entscheidungen:myview-dashboard.adoc#200[Kennzahlen anlegen]
** xref:business-entscheidungen:myview-dashboard.adoc#400[Dashboard einrichten]

[#300]
== Welche Funktionen stehen dir zur Verfügung?

plentyBI bietet dir einen großen Funktionsumfang. Du entscheidest für jede Kennzahl flexibel, wie detailliert und nach welchen Kriterien sie berechnet wird. Auch bei der Einrichtung deines individuellen Dashboards stehen zahlreiche Optionen zur Verfügung. So kannst du deine Daten genau nach deinen Wünschen anzeigen lassen und alle wichtigen Entwicklungen nachverfolgen.

** xref:business-entscheidungen:kennzahlen.adoc#[Liste verfügbarer Kennzahlen]
** xref:business-entscheidungen:myview-dashboard.adoc#408[Benutzerrechte für das Dashboard vergeben]
** xref:business-entscheidungen:myview-dashboard.adoc#405[Funktionen im Bearbeitungsmodus des Dashboards]
** xref:business-entscheidungen:myview-dashboard.adoc#410[Verschiedene Diagrammtypen, Kacheln und Tabellen auf dem Dashboard verwenden]
** xref:business-entscheidungen:myview-dashboard.adoc#900[Benachrichtigungen auf dem Dashboard anzeigen]


[#400]
== Auf dem Laufenden bleiben

Wartest du sehnsüchtig auf ein neues Feature für plentyBI? Wir informieren dich gerne über Änderungen an der Software! Änderungen werden link:https://forum.plentymarkets.com/c/changelog/[in einem Changelog^] veröffentlicht. Abonniere den Changelog und bleibe immer auf dem Laufenden.

