= Prohandel-Anbindung
:keywords: Prohandel, Prohandel-Anbindung, Prohandel-Connector, Prohandel-Erweiterung
:description: Lerne, wie du dein Prohandel-System mit plentymarkets verbindest.
:page-index: false
:id: NCUBFL8
:author: team-plenty-channel

////
zuletzt bearbeitet 07.04.2022

Interner Hinweis zur Seite:
Diese Seite richtet sich in erster Linie am plenty-Einrichtungs-Team.
Es ist sehr unwahrscheinlich, dass ein bestehender plenty-Kunde sich spontan entscheidet Prohandel zu nutzen und versucht das Plugin selbst einzurichten.
Viel eher ist der Anwendungsfall, dass ein Händler schon Prohandel nutzt (z.B. für sein Mode-Einzelhandel).
Der Händler möchte seine Ware zukünftig auch online verkaufen und entscheidet sich für plenty (u.a. weil wir diese Schnittstelle haben).
Der Händler wäre also ganz neu bei plenty und würde sein System samt Prohandel-Plugin zusammen mit dem Einrichtungs-Team einrichten.
////

//ToDo when the page can be made visible in the left navigation - remove the attribute :page-index: false from the header and add the page to the navigation file in the ROOT folder

////
offene Fragen:
-bei "Optionen für den Artikelimport > Gruppierungsschema > Beispiel supplierNumber-categoryNumber-supplierArticleNumber": Hier wäre es schön, wenn es eine Liste mit den möglichen Datenfeldern gäbe, die man eingeben kann. Zudem wäre eine Info zur Syntax nicht schlecht. Team Prohandel müsste uns diese Infos liefern.
-bei "Neu importierte Artikeldaten öffnen": Klären, ob das so bleiben wird (also, dass die Versandprofile nicht automatisch aktiviert werden, weil die API per REST arbeitet). Falls ja, dann ein Hinweis hier in diesem Kapitel einbauen, dass der Händler seine Versandprofile prüfen und aktivieren soll.
https://forum.plentymarkets.com/t/api-prohandel-versandprofil-e-bei-neuen-artikeln-aktivieren/652140/7
////

Prohandel und plentymarkets – eine unschlagbare Kombination.
Nutzt du schon Prohandel als Warenwirtschaftslösung für den Mode-Einzelhandel?
Und bist du bereit, mit plentymarkets im Online-Handel durchzustarten?
Das Prohandel-Plugin stellt die Verbindung zwischen deinem Prohandel-System und plentymarkets her.

* Nutze Prohandel weiterhin für deine Offline-Verkäufe.
* Übertrage deine in Prohandel gespeicherten Artikeldaten an plentymarkets.
* Ergänze bei Bedarf die Artikeldaten in plentymarkets und vertreibe sie anschließend auf verschiedenen Marktplätzen, Vertriebskanälen und Webshops.

[#10]
== Voraussetzungen

Diese Seite geht davon aus, dass du schon Kunde von link:https://www.prohandel.de/[Prohandel] und link:https://www.plentymarkets.com/[plentymarkets] bist.
Halte deine Zugangsdaten für beide Systeme bereit.
Während du die Schnittstelle einrichtest, musst du deine Zugangsdaten eingeben, um die Verbindung herzustellen.

Ferner wirst du deine Prohandel Barcodes, Verkaufspreise, Kategorien usw. denen in plentymarkets zuordnen.
Das heißt, falls du dein plentymarkets System noch nicht eingerichtet hast, solltest du folgende Daten anlegen, bevor du fortfährst:

* xref:warenwirtschaft:lager-einrichten.adoc#[Lager]
* xref:auftraege:auftragsherkunft.adoc#[Auftragsherkünfte]
* xref:artikel:markierungen.adoc#400[Tags]
* xref:artikel:barcodes.adoc#[Barcodes]
* xref:artikel:attribute.adoc#[Attribute]
* xref:artikel:eigenschaften.adoc#[Eigenschaften]
* xref:artikel:preise.adoc#[Verkaufspreise]
* xref:artikel:kategorien.adoc#[Kategorien]

[#20]
== Plugin herunterladen und installieren

Das Prohandel-Plugin steht auf plentyMarketplace zur Verfügung.
Es stellt die Verbindung zwischen deinem Prohandel-System und plentymarkets her.

Das Prohandel-Plugin kann:

* *_Artikel importieren_*:
Artikeldaten werden von Prohandel nach plentymarkets übertragen.
Du entscheidest, welche Artikeldaten an plentymarkets gesendet und wie die Artikel dort strukturiert werden sollen.
* *_Aufträge exportieren_*:
Auftragsdaten werden von plentymarkets nach Prohandel übertragen.
plentymarkets meldet den Umsatz an Prohandel und bucht den Umsatz automatisch in die richtige Prohandel-Umsatzfiliale.
* *_Bestände und Preise aktualisieren_*:
Wenn in Prohandel Bestände oder Preise aktualisiert werden, dann wird diese Information an plentymarkets übermittelt.

[.collapseBox]
.*Schritt-für-Schritt-Anleitung*
--

. Lade das Prohandel-Plugin von plentyMarketplace herunter. +
→ Falls aufgefordert, melde dich bei plentyMarketplace an.
Verwende die gleichen Zugangsdaten wie für den Bereich "Mein Konto".
. Öffne das Menü *Plugins » Plugin-Set-Übersicht*.
Plugins können nur als Teil eines Plugin-Sets genutzt werden. Daher:
.. *_Option A_*: Erstelle ein komplett neues Plugin-Set.
Klicke dazu auf icon:plus[role="darkGrey"] *Plugin-Set hinzufügen* und gib einen Namen ein.
.. *_Option B_*: Erstelle eine Kopie eines vorhandenen Plugin-Sets.
Klicke dazu in der Spalte *Aktionen* auf die Schaltfläche *Plugin-Set kopieren* (terra:copy[]).
.. *_Option C_*: Entscheide, in welches bestehende Plugin-Set du das Prohandel-Plugin installieren willst.
. Öffne das Plugin-Set, indem du auf die Zeile in der Tabelle klickst. +
→ Das Plugin-Set wird geöffnet.
. Klicke auf icon:plus[role="darkGrey"] *Plugin hinzufügen*.
. Wähle das Prohandel-Plugin aus der Liste. +
→ Es werden Informationen zu dem Plugin angezeigt.
. Wähle aus der Dropdown-Liste *Version auswählen* die Version des Plugins, die du installieren möchtest.
Die aktuelle Version ist vorausgewählt.
. Um das Plugin zu installieren, klicke auf icon:arrow-down[role="darkGrey"] *Installieren*. +
→ Das Plugin wird installiert. +
→ Nachdem das Installieren abgeschlossen ist, wird das Plugin-Set angezeigt.
. Ändere den Zustand des Plugins zu aktiv (icon:toggle-on[role="blue"]).
. Stelle das Plugin-Set bereit (icon:cloud-upload[role="darkGrey"]).

Ist das Thema Plugins neu für dich?
Im xref:plugins:plugins.adoc#[Plugins-Kapitel] des Handbuchs erfährst du mehr über Plugins und wie sie in plentymarkets funktionieren.

--

[TIP]
.Konfiguration erfolgt im Assistenten
====
Du musst keine Einstellungen direkt im Plugin vornehmen.
Durchlaufe stattdessen den Assistenten.
Er führt dich durch den Einrichtungsprozess.
====

[#30]
== Assistent durchlaufen

Mit Hilfe des Assistenten legst du fest, wie plentymarkets und Prohandel miteinander kommunizieren sollen.
Im Assistenten entscheidest du zum Beispiel, welche Artikeldaten an plentymarkets gesendet und wie die Artikel dort strukturiert werden sollen.

[.instruction]
Einstellungen im Assistenten konfigurieren:

. Öffne das Menü *Einrichtung » Assistenten » Plugins » [Plugin-Set öffnen]*.
. Klicke auf *Prohandel-Assistent*.
. Folge den Anweisungen auf dem Bildschirm.
Informationen zu den einzelnen Schritten findest du weiter unten auf dieser Seite.
. Prüfe im Schritt *Zusammenfassung* deine Einstellungen noch einmal auf mögliche Fehler.
. Wenn alle Einstellungen korrekt vorgenommen wurden, klicke auf icon:check[role="green"] *Abschließen*. +
→ Die Einstellungen werden gespeichert.

[#40]
=== Verbindung

In diesem Schritt stellst du die Verbindung zwischen plentymarkets und Prohandel her.
Das heißt, du gibst deine Zugangsdaten ein, damit plentymarkets und Prohandel miteinander kommunizieren können.

[[table-connection-settings]]
.Verbindung
[cols="1,3"]
|===
|Einstellung |Erläuterung

| *URL*
|Gib die URL ein, die du von Prohandel erhalten hast.
Beispiel: `dein-shop.prohandel.de`

| *Benutzername*
|Gib den Benutzernamen deines Prohandel-Kontos ein.
Der Benutzername ist eine E-Mail-Adresse.

| *Passwort*
|Gib das Passwort deines Prohandel-Kontos ein.
|===

[#43]
=== Standorte im Lager berücksichtigen

In diesem Schritt entscheidest du, ob plentymarkets den genauen Standort jedes Artikels im Lager erfassen soll.

*_Hintergrund-Wissen_*:

* Mit plentymarkets kannst du nicht nur den Bestand eines Artikels nachverfolgen, sondern auch, wo sich der Artikel im Lager befindet.
** In plentymarkets wird der Standort des Artikels als "Lagerort" bezeichnet.
** In Prohandel wird der Standort des Artikels als "Shop" bezeichnet.

[[table-storage-location-function]]
.Standorte im Lager berücksichtigen
[cols="1,3a"]
|===
|Einstellung |Erläuterung

| *Standorte berücksichtigen*
|Soll plentymarkets den genauen Standort jedes Artikels im Lager erfassen?

icon:toggle-on[role="blue"] = Der genaue Lagerort des Artikels wird erfasst.
Wenn sich der Lagerbestand ändert, d.h. wenn ein Artikel ein- oder ausgebucht wird, dann wird der spezifische Lagerort berücksichtigt.
Hast du diese Funktion aktiviert, dann musst du auch die Einstellungen in Schritt *Zuordnung der Standorte* vornehmen.

icon:toggle-off[role="darkGrey"] = Der Lagerort des Artikels wird nicht erfasst.
In plentymarkets wird der Lagerort immer als "Standard" angegeben.

|===

[#46]
=== Zuordnung der Standorte

In diesem Schritt ordnest du deine Prohandel-Shops deinen plentymarkets Lagerorten zu.
Die Lagerorte in plentymarkets werden dabei automatisch generiert.

*_Beispiel_*:

* Über den Artikelimport erhält plentymarkets die Information, dass ein Artikel im Prohandel-Shop 1234 liegt.
* Daraus erstellt das Plugin automatisch einen passenden plentymarkets-Lagerort im Menü *Einrichtung » Waren » Lager » [Lager öffnen] » Lagerorte* und verknüpft ihn in diesem Schritt des Assistenten.

[[table-storage-location-mapping]]
.Zuordnung der Standorte
[cols="1,3a"]
|===
|Einstellung |Erläuterung

| *Prohandel-Filiale*
|Dies sind die bestandsführenden Filialen in Prohandel.
Wähle die passende Filiale aus der Dropdown-Liste aus.

| *Prohandel-Shop*
|Dies sind die Shop-Namen in Prohandel.
Wähle den passenden Shop aus der Dropdown-Liste aus.

| *plentymarkets-Lagerort*
|Dies sind die Lagerort-IDs im plentymarkets-Menü *Einrichtung » Waren » Lager » [Lager öffnen] » Lagerorte*.

|===

[TIP]
.Logik der Namensgebung
====
Deine automatisch generierten Lagerorte findest du im Menü *Einrichtung » Waren » Lager » [Lager öffnen] » Lagerorte*.
Der Name des Lagerorts folgt immer einer bestimmten Logik.
Die Lagerorte heißen: `Prohandel level:Prohandel SL for shop 1234`.
Dabei steht `1234` für die Prohandel-Shopnummer.
Diese Benennung kann man nicht anpassen.
Sie ist fest vorgegeben.
====

[#50]
=== Zuordnung der Bestandsfilialen

In diesem Schritt ordnest du deine bestandsführenden Prohandel-Filialen deinen plentymarkets Lagern zu.
So werden deine Bestände in Prohandel und plentymarkets miteinander abgeglichen und aktualisiert.
Sinkt zum Beispiel der Bestand in Prohandel, dann wird plentymarkets auch über diese Änderung informiert.

[[table-stock-branch-matching]]
.Zuordnung der bestandsführenden Filialen
[cols="1,3"]
|===
|Einstellung |Erläuterung

| *Prohandel-Filiale*
|Dies sind die bestandsführenden Filialen in Prohandel.
Wähle die passende Filiale aus der Dropdown-Liste aus.

| *plentymarkets Lager*
|Dies sind die Lager, die du in plentymarkets eingerichtet hast.
Wähle das passende Lager aus der Dropdown-Liste aus.

*_Voraussetzung_*:
Hast du schon xref:warenwirtschaft:lager-einrichten.adoc#[Lager in plentymarkets angelegt]?
Diese Dropdown-Liste enthält nur die Lager, die schon in plentymarkets vorhanden sind.

| icon:plus[role="green"]
|Fügt eine weitere Zeile hinzu.
Auf diese Weise kannst du mehrere Filialen und Lager zuordnen.

| icon:minus-circle[role="red"]
|Löscht eine Zeile.
Auf diese Weise kannst du eine nicht mehr benötigte Zuordnung löschen.
|===

[TIP]
.Eine 1:1-Zuordnung ist am besten
====
* Im Idealfall solltest du eine 1:1-Zuordnung erstellen.
* Es macht keinen Sinn, mehrere plentymarkets Lager mit ein und derselben Prohandel-Filiale zu verknüpfen.
In diesem Fall würden deine Daten mehrfach von Prohandel nach plentymarkets übertragen werden.
Die Daten werden nicht aufgesplittet.
====

[#60]
=== Zuordnung der Umsatzfilialen

In diesem Schritt ordnest du deine plentymarkets Verkaufskanäle den passenden Prohandel-Umsatzfilialen zu.
Stell dir vor, du hast gerade ein Produkt auf einem Markt wie eBay, Amazon oder Check24 verkauft.
In welcher Filiale sollen die Umsätze gebucht und die Auftragsdaten übermittelt werden?

[[table-sales-branch-matching]]
.Zuordnung der Umsatzfilialen
[cols="1,3"]
|===
|Einstellung |Erläuterung

| *Prohandel-Filiale*
|Dies sind die Umsatzfilialen in Prohandel.
Wähle die passende Filiale aus der Dropdown-Liste aus.

| *Mandant (Shop)*
|Dies sind die Mandanten, die du mit plentymarkets betreibst.
Wähle den passenden Mandanten aus der Dropdown-Liste aus.

Wenn ein Auftrag an Prohandel übertragen wird, enthält er Informationen darüber, auf welchen Mandanten er sich bezieht.

| *Auftragsherkünfte*
|Dies sind die Auftragsherkünfte, die du in plentymarkets nutzt.
Wähle die passenden Herkünfte aus (icon:check-square[role="blue"]).

Wenn ein Auftrag an Prohandel übertragen wird, enthält er Informationen darüber, aus welchem Verkaufskanal er stammt.
So kannst du auf Prohandel-Seite statistisch festhalten, welche Vertriebskanäle besonders gewinnbringend sind oder welche die meisten Retouren verursachen.

*_Voraussetzung_*:
Hast du schon die passenden xref:auftraege:auftragsherkunft.adoc#[Herkünfte in plentymarkets aktiviert]?
Diese Dropdown-Liste enthält nur die aktivierten Herkünfte.

| icon:plus[role="green"]
|Fügt eine weitere Zeile hinzu.
Auf diese Weise kannst du mehrere Filialen und Verkaufskanäle zuordnen.

| icon:minus-circle[role="red"]
|Löscht eine Zeile.
Auf diese Weise kannst du eine nicht mehr benötigte Zuordnung löschen.
|===

[#70]
=== Optionen für den Artikelimport

In diesem Schritt legst du fest, welche Artikeldaten von Prohandel an plentymarkets übertragen werden sollen und wie die Artikel dort strukturiert werden sollen.

[[table-item-import-options]]
.Optionen für den Artikelimport
[cols="1,3a"]
|===
|Einstellung |Erläuterung

2+^| *Artikelfilter*

| *Filtergrundlage*; +
*Ab Datum*
|Welche Artikel sollen in plentymarkets importiert werden?

. Wähle eine Grundlage aus der Dropdown-Liste aus.
. Gib ein Datum in das Feld ein.

[cols="1,3a"]
!===

! *Erstes Wareneingangsdatum*
!Dies ist ein Zeitstempel für Artikel in Prohandel.
Der Zeitstempel wird erzeugt, wenn der Artikel erstmalig in Prohandel angelegt wird.
Dieser Zeitstempel ändert sich nie.

*_Hinweis_*:
Dieser Zeitstempel ist nicht zu verwechseln mit dem zweiten Wareneingangsdatum, welcher sich aktualisiert, sobald neuer Wareneingang auf den Artikel gebucht wird.

! *Zweites Verkaufsdatum*
!Dies ist ein Zeitstempel für Artikel in Prohandel.
Der Zeitstempel gibt an, wann der Artikel zuletzt verkauft wurde.
Dieser Zeitstempel wird fortlaufend in Prohandel aktualisiert, wenn ein neuer Verkauf getätigt wird.

!===

*_Beispiel_*:
Stell dir vor, du verwendest das erste Wareneingangsdatum als Filtergrundlage und du gibst das Datum 01.01.2020 ein.
In diesem Fall werden nur die Artikel importiert, die am oder nach dem 1. Januar 2020 erstmalig bezogen wurden.

2+^| *Gruppierungsschema*

| *Gruppierungsschema*
|Artikel sind unterschiedlich strukturiert in Prohandel und in plentymarkets.

* *_Prohandel_*: In Prohandel kann man einen Artikel als eine Farbvariante verstehen.
Ein Artikel ist zum Beispiel ein T-Shirt in der Farbe Blau.
Ein zweiter Artikel ist das T-Shirt in der Farbe Rot.
Beide Artikel haben Größenvariationen.
Zum Beispiel Blau S, Blau M, Blau L und Rot S, Rot M, Rot L.
* *_plentymarkets_*: In plentymarkets kann man einen Artikel als ein Datencontainer verstehen.
Ein Artikel beinhaltet immer eine oder mehrere Varianten, d.h. eine oder mehrere verkaufbare Ausführungen des Produkts.
Wird zum Beispiel ein T-Shirt in den Farben Blau und Rot und den Größen S, M, L angeboten, dann bilden alle Farben und Größen zusammen den Artikel.
Jede einzelne Kombination (Blau S, Blau M, Blau L, Rot S, Rot M, Rot L) ist eine Variante dieses Artikels.

In diesem Schritt legst du ein Gruppierungsschema fest, damit deine Prohandel-Artikel beim Import in plentymarkets korrekt strukturiert werden.
Dies ist ein Textfeld, d. h. du kannst jedes beliebige Gruppierungsschema eingeben.

*_Beispiel_*:
Wenn du das Gruppierungsschema `supplierNumber-categoryNumber-supplierArticleNumber` eingibst, werden alle Prohandel-Artikel, die dieselbe Lieferantennummer, Kategorienummer und Lieferantenartikelnummer haben, in einem einzigen plentymarkets Artikel zusammengefasst.

2+^| *Tag für importierte Artikel*

| *plentymarkets Tag*
|Möchtest du alle neu importierten Artikel mit einem bestimmten Tag versehen?
Falls ja, dann wähle den passenden Tag aus der Dropdown-Liste aus.
Indem du die Artikel mit einem Tag versiehst, kannst du leicht erkennen, welche Artikel vor Kurzem importiert wurden, die Datensätze öffnen und die in plentymarkets gespeicherten Artikeldaten ergänzen.

*_Voraussetzung_*:
Hast du schon die nötigen xref:artikel:markierungen.adoc#400[Tags in plentymarkets angelegt]?
Diese Dropdown-Liste enthält nur Tags, die schon erstellt und für den Bereich "Variante" aktiviert wurden.

2+^| *Verhalten von Artikeln mit einem bestimmten Wert*

| *Feldname*; +
*Feldwert*; +
*Importverhalten*
|Möchtest du nur bestimmte Artikel importieren?
Oder möchtest du bestimmte Artikel vom Import ausschließen?

. Um welche Artikel geht es?
Wähle den Feldnamen und Feldwert.
. Entscheide, was mit diesen Artikeln passieren soll.
Wähle dazu das Importverhalten.

[cols="1,3a"]
!===

! *Nur Artikel mit angegebenem Wert importieren*
!Es werden nur die Artikel importiert, die den angegebenen Feldwert und Feldnamen enthalten.
Alle anderen Artikel werden ignoriert.

! *Alle Artikel mit angegebenem Wert überspringen*
!Die Artikel, die den angegebenen Feldwert und Feldnamen enthalten, werden übersprungen.
Das heißt, sie werden nicht importiert.

!===

*_Beispiel_*:
Stell dir vor, du verkaufst Kleidung in vielen verschiedenen Mustern.
Auf Prohandel wird jedes Muster durch eine eindeutige ID gekennzeichnet.
Du willst nur die Produkte mit Musternummer 5 in plentymarkets importieren.
Dazu wählst du den Feldnamen *patternNumber*, den Feldwert *5* und das Importverhalten *Nur Artikel mit angegebenem Wert importieren*.

|===

[#80]
=== Zuordnung der Artikeldatenfelder

In diesem Schritt entscheidest du, wie die Daten, die aus Prohandel kommen, in plentymarkets aussehen sollen.
Das heißt, wo die Daten in plentymarkets gespeichert werden sollen.

[[table-item-import-field-mappings]]
.Zuordnung der Artikeldatenfelder
[cols="1,3a"]
|===
|Einstellung |Erläuterung

2+^| *Zuordnung des Barcodes*

| *EAN*
|Welcher plentymarkets Barcode-Typ passt zu deiner Prohandel-EAN?
Wähle den Barcode-Typ aus der Dropdown-Liste aus.

*_Voraussetzung_*: Hast du schon xref:artikel:barcodes.adoc#100[Barcode-Typen in plentymarkets konfiguriert]?
Diese Dropdown-Liste enthält nur die Barcode-Typen, die schon in plentymarkets vorhanden sind.

| *Nummer*
|Welcher plentymarkets Barcode-Typ passt zu deiner internen Nummer zur Identifikation der Größe in Prohandel?
Wähle den Barcode-Typ aus der Dropdown-Liste aus.

*_Voraussetzung_*: Hast du schon xref:artikel:barcodes.adoc#100[Barcode-Typen in plentymarkets konfiguriert]?
Diese Dropdown-Liste enthält nur die Barcode-Typen, die schon in plentymarkets vorhanden sind.

| *Artikelnummer*
|Welcher plentymarkets Barcode-Typ passt zu deiner Prohandel-Artikelnummer?
Wähle den Barcode-Typ aus der Dropdown-Liste aus.

*_Voraussetzung_*: Hast du schon xref:artikel:barcodes.adoc#100[Barcode-Typen in plentymarkets konfiguriert]?
Diese Dropdown-Liste enthält nur die Barcode-Typen, die schon in plentymarkets vorhanden sind.

2+^| *Zuordnung der Attribute*

| *Lief.-Farbe*
|Welches plentymarkets Attribut passt zu deiner Prohandel-Lieferantenfarbe?
Wähle das Attribut aus der Dropdown-Liste aus.

*_Voraussetzung_*: Hast du schon xref:artikel:attribute.adoc#[Attribute in plentymarkets konfiguriert]?
Diese Dropdown-Liste enthält nur die Attribute, die schon in plentymarkets vorhanden sind.

| *Größe*
|Welches plentymarkets Attribut passt zu deiner Prohandel-Größe?
Wähle das Attribut aus der Dropdown-Liste aus.

*_Voraussetzung_*: Hast du schon xref:artikel:attribute.adoc#[Attribute in plentymarkets konfiguriert]?
Diese Dropdown-Liste enthält nur die Attribute, die schon in plentymarkets vorhanden sind.

2+^| *Zuordnung der Eigenschaften*

| *Eigene Artikel-Nr.*
|Welches plentymarkets Datenfeld passt zu deiner eigenen Artikel-Nummer in Prohandel?
Wähle die passende Option aus der Dropdown-Liste aus.

[cols="1,3a"]
!===

! *Keine*
!Die eigene Artikel-Nummer wird nicht übertragen.

! *Name 1*
!Die eigene Artikel-Nummer wird gespeichert unter: xref:artikel:artikel-verwalten.adoc#50[Artikel » Artikel bearbeiten » [Artikel öffnen\] » Tab: Texte » Eingabefeld: Name 1]
//ToDo - sobald die neue Artikel-UI standard ist, dann diesen Satz einblenden und dafür den alten Satz löschen
//Die eigene Artikel-Nummer wird gespeichert unter: xref:artikel:verzeichnis.adoc#50[Artikel » Artikel » [Artikel öffnen\] » Element: Texte » Eingabefeld: Name 1]

! *Eigenschaft der Variante*
!Eine zweite Dropdown-Liste wird angezeigt.
Sie enthält eine Liste von Eigenschaften, die in plentymarkets vorhanden sind.
Wähle eine Eigenschaft aus dieser Liste aus, wenn du die Prohandel-eigene Artikelnummer als diese Eigenschaft in plentymarkets speichern willst.

*_Voraussetzung_*: Hast du schon xref:artikel:eigenschaften.adoc#[Eigenschaften in plentymarkets konfiguriert]?
Diese Dropdown-Liste enthält nur die Eigenschaften, die schon in plentymarkets vorhanden sind.
!===

| *Lief.-Art-Nr.*
|Welches plentymarkets Datenfeld passt zu deiner Prohandel-Lieferanten-Artikelnummer?
Wähle die passende Option aus der Dropdown-Liste aus.

[cols="1,3a"]
!===

! *Keine*
!Die Lieferanten-Artikelnummer wird nicht übertragen.

! *Externe Varianten-ID*
!Die Lieferanten-Artikelnummer wird gespeichert unter: xref:artikel:artikel-verwalten.adoc#190[Artikel » Artikel bearbeiten » [Variante öffnen\] » Tab: Einstellungen » Bereich: Grundeinstellungen » Eingabefeld: Ext. Varianten-ID]
//ToDo - sobald die neue Artikel-UI standard ist, dann diesen Satz einblenden und dafür den alten Satz löschen
//Die Lieferanten-Artikelnummer wird gespeichert unter: xref:artikel:artikel-verwalten.adoc#170[Artikel » Artikel » [Variante öffnen\] » Element: Einstellungen » Eingabefeld: Externe ID]

! *Eigenschaft der Variante*
!Eine zweite Dropdown-Liste wird angezeigt.
Sie enthält eine Liste von Eigenschaften, die in plentymarkets vorhanden sind.
Wähle eine Eigenschaft aus dieser Liste aus, wenn du die Prohandel-Lieferanten-Artikelnummer als diese Eigenschaft in plentymarkets speichern willst.

*_Voraussetzung_*: Hast du schon xref:artikel:eigenschaften.adoc#[Eigenschaften in plentymarkets konfiguriert]?
Diese Dropdown-Liste enthält nur die Eigenschaften, die schon in plentymarkets vorhanden sind.
!===

| *Saison-Nr.*; +
*Erstes Wareneingangsdatum*; +
*Zweites Wareneingangsdatum*; +
*NOS*; +
*Ident-Nr.*; +
*Erstes Verkaufsdatum*; +
*Zweites Verkaufsdatum*
|Welche plentymarkets Eigenschaft passt zu dem Prohandel-Datenfeld?
Wähle die passende Option aus der Dropdown-Liste aus.

[cols="1,3a"]
!===

! *Keine*
!Das Prohandel-Datenfeld wird nicht übertragen.

! *Eigenschaft der Variante*
!Eine zweite Dropdown-Liste wird angezeigt.
Sie enthält eine Liste von Eigenschaften, die in plentymarkets vorhanden sind.
Wähle eine Eigenschaft aus dieser Liste aus, wenn du das Prohandel-Datenfeld als diese Eigenschaft in plentymarkets speichern willst.

*_Voraussetzung_*: Hast du schon xref:artikel:eigenschaften.adoc#[Eigenschaften in plentymarkets konfiguriert]?
Diese Dropdown-Liste enthält nur die Eigenschaften, die schon in plentymarkets vorhanden sind.
!===

2+^| *Besonderheiten*

| *Prohandel-Lieferanten als plentymarkets Hersteller importieren*
|Soll der Prohandel-Lieferant als Hersteller in plentymarkets hinterlegt werden?
In plentymarkets findest du den Hersteller eines Artikels im Menü *Artikel » Artikel bearbeiten » [Artikel öffnen] » Tab: Global » Dropdown-Liste: Hersteller*.
//ToDo - sobald die neue Artikel-UI standard ist, dann diesen Satz einblenden und dafür den alten Satz löschen
//In plentymarkets findest du den Hersteller eines Artikels im Menü *Artikel » Artikel » [Artikel öffnen] » Element: Einstellungen » Dropdown-Liste: Hersteller*.

| *Prohandel-Muster als plentymarkets Tags importieren*
|Soll das Prohandel-Muster als Tag in plentymarkets hinterlegt werden?
In plentymarkets findest du die Tags eines Artikels im Menü *Artikel » Artikel bearbeiten » [Variante öffnen] » Tab: Einstellungen » Bereich: Tags*.
//ToDo - sobald die neue Artikel-UI standard ist, dann diesen Satz einblenden und dafür den alten Satz löschen
//In plentymarkets findest du die Tags eines Artikels im Menü *Artikel » Artikel » [Variante öffnen] » Element: Tags*.

|===

[#90]
=== Zuordnung der Verkaufspreise

* Im oberen Bereich ordnest du deine in Prohandel verwendeten Verkaufspreise den Verkaufspreisen in plentymarkets zu.
* Im unteren Bereich ordnest du den in Prohandel verwendeten Aktionspreis einem Verkaufspreis in plentymarkets zu.

[[table-sales-prices]]
.Zuordnung der Verkaufspreise
[cols="1,3"]
|===
|Einstellung |Erläuterung

2+^| *Verkaufspreise*

| *VK-Preis*
|Welchen plentymarkets Verkaufspreis möchtest du für den VK-Preis in Prohandel verwenden?
Wähle den passenden plentymarkets Verkaufspreis aus der Dropdown-Liste aus.

*_Voraussetzung_*: Hast du schon xref:artikel:preise.adoc#[Verkaufspreise in plentymarkets eingerichtet]?
Diese Dropdown-Liste enthält nur die Verkaufspreise, die schon in plentymarkets vorhanden sind.

| *VK-Preis (Etikett)*
|Welchen plentymarkets Verkaufspreis möchtest du für den VK-Preis (Etikett) in Prohandel verwenden?
Wähle den passenden plentymarkets Verkaufspreis aus der Dropdown-Liste aus.

*_Voraussetzung_*: Hast du schon xref:artikel:preise.adoc#[Verkaufspreise in plentymarkets eingerichtet]?
Diese Dropdown-Liste enthält nur die Verkaufspreise, die schon in plentymarkets vorhanden sind.

2+^| *Prohandel-Aktionspreis*

| *ID des Prohandel-Aktionspreises*
|Wie lautet die ID deines Aktionspreises in Prohandel?
Gib die ID in dieses Feld ein.

| *VK-Preis (Aktionspreis)*
|Welchen plentymarkets Verkaufspreis willst du deinem Prohandel Aktionspreis zuordnen?
Wähle den passenden plentymarkets Verkaufspreis aus der Dropdown-Liste aus.

*_Voraussetzung_*: Hast du schon xref:artikel:preise.adoc#[Verkaufspreise in plentymarkets eingerichtet]?
Diese Dropdown-Liste enthält nur die Verkaufspreise, die schon in plentymarkets vorhanden sind.

| *Von*; +
*Bis*
|In welchem Zeitraum soll dieser Verkaufspreis gelten?
Wähle die Eigenschaften aus den Dropdown-Listen, mit denen du das Startdatum und das Enddatum von Aktionspreisen an der Variante speicherst.

*_Voraussetzung_*: Hast du schon xref:artikel:eigenschaften.adoc#[Eigenschaften in plentymarkets konfiguriert]?
Diese Dropdown-Liste enthält nur die Eigenschaften, die schon in plentymarkets vorhanden sind.
Es ist sinnvoll, die Von- und Bis-Daten mit Eigenschaften vom Typ "Datum" umzusetzen.

|===

[TIP]
.Keine Zuordnung für EK nötig
====
Der Prohandel-Einkaufspreis wird statisch dem plentymarkets Netto-Einkaufspreis zugeordnet.
Das bedeutet, dass du den Prohandel-EK nicht mit dem plentymarkets EK verknüpfen musst.
Er ist schon zugeordnet.
====

[#100]
=== Zuordnung der Kategorien

In diesem Schritt ordnest du deine in Prohandel verwendeten Warengruppen den Kategorien in plentymarkets zu.
So werden deine Artikel schon in die richtigen plentymarkets Kategorien einsortiert, wenn sie von Prohandel importiert werden.

[[table-category-mapping]]
.Zuordnung der Kategorien
[cols="1,3"]
|===
|Einstellung |Erläuterung

| *Standard Artikelkategorie*
|Stell dir vor, du hast eine neue Prohandel-Warengruppe erstellt.
Du hast aber vergessen, die Warengruppe einer Kategorie in plentymarkets zuzuordnen.
Wenn Artikel aus der nicht zugeordneten Warengruppe importiert werden, landen sie in der Standardkategorie.

| *Prohandel-Warengruppe*
|Dies sind deine Warengruppen in Prohandel.
Wähle die passende Warengruppe aus der Dropdown-Liste aus.

| *plentymarkets Kategorie*
|Dies sind die Kategorien, die du in plentymarkets eingerichtet hast.
Wähle die passende Kategorie aus der Dropdown-Liste aus.

*_Voraussetzung_*: Hast du schon xref:artikel:kategorien.adoc#[Kategorien in plentymarkets angelegt]?
Diese Dropdown-Liste enthält nur die Kategorien, die schon in plentymarkets vorhanden sind.

| icon:plus[role="green"]
|Fügt eine weitere Zeile hinzu.
Auf diese Weise kannst du mehrere Kategorien zuordnen.

| icon:minus-circle[role="red"]
|Löscht eine Zeile.
Auf diese Weise kannst du eine nicht mehr benötigte Zuordnung löschen.
|===

[TIP]
.Alternativer Ablauf ohne Kategoriezuordnung
====
Technisch gesehen kannst du auch nur eine Standard-Artikelkategorie wählen und den Rest der Kategoriezuordnung überspringen.
Als Folge würden deine Artikel beim Import immer nur in der Standardkategorie landen.
Bei Bedarf musst du dann manuell Artikel in andere plentymarkets Kategorien verschieben.
====

[#110]
=== Cron-Einstellungen

Der Datenaustausch zwischen Prohandel und plentymarkets erfolgt mit Hilfe von sogenannten Crons.

In diesem Schritt aktivierst du die Cron-Jobs, die automatisch ausgeführt werden sollen (icon:check-square[role="blue"]).

include::_includes:partial$crons.adoc[]

[[table-cron-settings]]
.Wann werden die Crons ausgeführt?
[cols="1,1,3a"]
|===
|Cron |Intervall |Erläuterung

| *Artikelimport*
|Täglich
|
* Nachdem du den Assistenten abgeschlossen hast, werden alle Artikel erstmalig von Prohandel nach plentymarkets übertragen.
Dieser erstmalige vollständige Import kann, je nach Anzahl der Produkte, einige Tage in Anspruch nehmen.
* Danach werden nur noch Teilimporte durchgeführt, die auf den zuvor gewählten xref:business-entscheidungen:prohandel.adoc#70[Importeinstellungen] basieren.
* Es werden nur neue Artikel importiert und neue Varianten zu bestehenden Artikeln.
Bestehende Artikel werden nicht über diesen Cron aktualisiert.
* Der Artikelimport erfolgt am Ende des Tages bzw. in der Nacht.

| *Artikelaktualisierung*
|Stündlich
|Bestehende Artikel und Varianten werden aktualisiert.
Folgende Daten werden über diesen Cron aktualisiert:

* Verknüpfte Varianteneigenschaften
* Tags (sofern das Prohandel-Muster als Tag importiert wird)
* Hersteller (sofern der Hersteller importiert wird)
* EAN

| *Preisaktualisierung*
|Stündlich
|

| *Bestandsaktualisierung*
|Alle 15 Minuten
|
|===

[#120]
== Neu importierte Artikeldaten öffnen und ergänzen

Deine Artikeldaten werden bei der nächsten Ausführung des Cron-Jobs von Prohandel nach plentymarkets übertragen.
Dies setzt voraus, dass du:

* den Cron *Artikelimport* aktiviert hast (icon:check-square[role="blue"]).
* den Assistenten abgeschlossen hast.
* das Plugin im Set aktiviert hast.

[#130]
=== Neu importierte Artikel öffnen

Öffne einige Artikeldatensätze und prüfe stichprobenartig, ob deine Artikeldaten korrekt importiert wurden.

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Lege mit den xref:artikel:suche.adoc#[Suchfiltern] in der linken Spalte fest, welche Artikel du abrufen willst.
Zum Beispiel:
.. Setze den Filter *Aktiv* auf *ALLE* oder *Nein*, da Artikel beim Import inaktiv sind.
.. Setze den Filter *Tag* auf den im Assistant gewählten xref:business-entscheidungen:prohandel.adoc#70[Tag für neu importierte Artikel].
. Klicke auf *Suchen* (icon:search[role="blue"]). +
→ Die Suchergebnisse werden in der Übersicht rechts angezeigt.
. Klicke auf einen Artikel in der Übersicht, um den Artikeldatensatz zu öffnen.

//ToDo - sobald die neue Artikel-UI standard ist, dann diesen Konfig einblenden und dafür den alten Konfig löschen
//. Öffne das Menü *Artikel » Artikel*.
//. Lege mit den Suchfiltern (material:tune[role="darkGrey"]) fest, welche Artikel du abrufen willst.
//Zum Beispiel:
//.. Setze den Filter *Aktiv* auf *Nein*, da Artikel beim Import inaktiv sind.
//.. Setze den Filter *Tags* auf den im Assistant gewählten xref:business-entscheidungen:prohandel.adoc#70[Tag für neu importierte Artikel].
//. Klicke auf icon:search[role="blue"] *Suchen*. +
//→ Die Suchergebnisse werden in der Übersicht angezeigt.
//. Klicke auf einen Artikel in der Übersicht, um den Artikeldatensatz zu öffnen.

[TIP]
.Hauptvariante vs. Untervariante
====
Prüfe die übertragenen Daten sowohl für die Hauptvariante als auch für die Untervarianten:

* *_Hauptvariante_*: Die erste Variante eines Artikels wird als Hauptvariante bezeichnet.
Sie steht nicht zum Verkauf, sondern ist rein virtuell und dient dazu, die weiteren Untervarianten des Artikels anhand von xref:artikel:vererbung.adoc#[Vererbung] zu verwalten.
Wenn du einen Artikeldatensatz öffnest, öffnet sich automatisch auch die Hauptvariante.
* *_Untervariante_*: Die Untervarianten sind die verkaufbaren Ausführungen des Produkts.
Wird zum Beispiel ein T-Shirt in den Farben Blau und Rot und den Größen S, M, L angeboten, dann ist jede einzelne Kombination (Blau S, Blau M, Blau L, Rot S, Rot M, Rot L) eine Untervariante.
Um eine Untervariante zu öffnen, klicke auf den Tab *Varianten* und dann auf *Suchen* (icon:search[role="blue"]).
Klicke anschließend in der Übersicht auf eine Untervariante.
====

[#140]
=== Artikeldaten ergänzen

Wenn du mit den übertragenen Artikeldaten zufrieden bist, dann kannst du deine Artikel für den Online-Verkauf vorbereiten.
Zum Beispiel kannst du:

* xref:artikel:artikel-verwalten.adoc#50[Beschreibungstexte], xref:artikel:artikel-verwalten.adoc#90[Produktbilder] und relevante xref:artikel:artikel-verwalten.adoc#50[Metadaten] hinzufügen.
* angeben, wo deine Produkte verkauft werden sollen, d.h. xref:artikel:artikel-verwalten.adoc#340[Auftragsherkünfte] und xref:artikel:artikel-verwalten.adoc#340[Mandanten] wählen.
* deine Varianten xref:artikel:artikel-verwalten.adoc#200[aktivieren], sobald sie veröffentlicht werden sollen.

Eine vollständige Liste aller Artikeldatenfelder in plentymarkets findest du auf der Handbuchseite xref:artikel:artikel-verwalten.adoc#[Verzeichnis der Datenfelder].

[#150]
== Aufträge abwickeln

Wenn ein Produkt verkauft wird, landen die Auftragsdaten zunächst im plentymarkets Menü *Aufträge » Aufträge bearbeiten*.
Hier kann der Auftrag abgewickelt werden und sein Fortschritt mit Hilfe eines Status verfolgt werden.

Weitere Informationen zur Auftragsbearbeitung in plentymarkets findest du auf der Handbuchseite xref:auftraege:auftraege-verwalten.adoc#[Aufträge verwalten].

[#160]
== Ereignisaktionen einrichten

Natürlich sollen die Auftragsdaten nicht nur in plentymarkets bleiben, sondern auch nach Prohandel übertragen werden.
Dazu musst du vier sogenannte Ereignisaktionen einrichten.
Diese müssen nur einmalig im Voraus eingerichtet werden, damit der Auftragsexport korrekt funktioniert.

[.instruction]
Ereignisaktion einrichten:

. Öffne das Menü *Einrichtung » Aufträge » Ereignisse*.
. Klicke auf *Ereignisaktion hinzufügen* (icon:plus[role="green"]). +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
. Gib einen eindeutigen Namen für die Ereignisaktion ein.
. Wähle das Ereignis gemäß den folgenden Tabellen.
. Klicke auf terra:save[role="green"] *Speichern*. +
→ Die Ereignisaktion wird angelegt und kann weiter bearbeitet werden.
. Klicke auf *Aktion hinzufügen* (icon:plus[role="green"]) und wähle die Aktion gemäß den folgenden Tabellen.
. Optional: Klicke auf *Filter hinzufügen* (icon:plus[role="green"]) und wähle Filter, wenn die Ereignisaktion nur in bestimmten Szenarien gelten soll.
Beispielsweise wenn die Ereignisaktion nur für bestimmte Verkaufskanäle oder Mandanten gelten soll.
. Aktiviere die Ereignisaktion (icon:check-square[role="blue"]), sobald sie in Kraft treten soll.
Ab dem Zeitpunkt der Aktivierung greift die Ereignisaktion mit den von dir gewählten Einstellungen.
. Speichere (terra:save[role="green"]) die Einstellungen.

Weitere Informationen zur allgemeinen Verwendung von Ereignisaktionen findest du auf der Handbuchseite xref:automatisierung:ereignisaktionen.adoc#[Ereignisaktionen].

[#170]
=== Prohandel über neue Aufträge benachrichtigen

Sobald ein neuer Auftrag in plentymarkets landet, soll Prohandel über den Auftrag informiert werden.
So wird der nötige Bestand in Prohandel reserviert, damit es nicht zu einem Überverkauf kommt.

[[table-event-procedure-one]]
[cols="1,2"]
|===

|Ereignis
|Neuer Auftrag

|Filter (optional)
|Auftrag > Herkunft +
Auftrag > Mandant (Shop)

|Aktion
|Plugins > Prohandel: Bestand reservieren
|===

[#180]
=== Prohandel über Zahlung und Versand benachrichtigen

Fertig abgewickelte Aufträge befinden sich im Status 7.
Dieser Status bedeutet, dass die Zahlung eingegangen ist und der Warenausgang gebucht wurde.
Zu diesem Zeitpunkt soll Prohandel auch über die Änderungen am Auftrag informiert werden.

[[table-event-procedure-two]]
[cols="1,2"]
|===

|Ereignis
|Warenausgang gebucht

|Filter (optional)
|Auftrag > Herkunft +
Auftrag > Mandant (Shop)

|Aktion
|Plugins > Prohandel: Versand und Zahlung an Prohandel melden
|===

[#190]
=== Prohandel über Stornierungen benachrichtigen

Eine Stornierung:

* bedeutet, dass der:die Kund:in es sich anders überlegt hat und den gekauften Artikel doch nicht haben möchte.
* erfolgt, bevor du die Zahlung erhalten und die Ware verschickt hast.
* kann als Aufhebung der Bestandsreservierung verstanden werden.
plentymarkets teilt Prohandel mit, dass die erhaltene Bestandsreservierung nichtig ist.

Um einen Auftrag zu stornieren, änderst du seinen Status auf 8.
Zu diesem Zeitpunkt soll Prohandel über die Stornierung informiert werden, damit der Bestand nicht länger reserviert wird.

[[table-event-procedure-three]]
[cols="1,2"]
|===

|Ereignis
|Statuswechsel auf 8

|Filter (optional)
|Auftrag > Herkunft +
Auftrag > Mandant (Shop)

|Aktion
|Plugins > Prohandel: Auftragsstornierung an Prohandel melden
|===

[#200]
=== Prohandel über Retouren benachrichtigen

Eine Retoure:

* bedeutet, dass der:die Kund:in es sich anders überlegt hat und den gekauften Artikel doch nicht haben möchte.
* erfolgt, nachdem du die Zahlung erhalten und die Ware verschickt hast.

Die Zahlung ist schon eingegangen. Deshalb muss in diesem Fall eine Rückzahlung erfolgen.
Das bedeutet, dass du Prohandel über die Retoure informieren musst, damit die Umsätze wieder aus der Umsatzfiliale ausgebucht werden können.

[[table-event-procedure-four]]
[cols="1,2"]
|===

|Ereignis
|Neue Retoure

|Filter (optional)
|Auftrag > Herkunft +
Auftrag > Mandant (Shop)

|Aktion
|Plugins > Prohandel: Retoure an Prohandel melden
|===
