= Reports verwalten
:keywords: Report, Rohdaten, Rohdaten auswerten, Rohdaten anlegen, Rohdatenformat
:description: Ein Report ist eine Datenanalyse, die als Ergebnis eine einzelne Kennzahl (KPI) oder eine Ergebnisliste ermittelt. Auf dieser Seite lernst du, wie du auf Reports zugreifst und sie verarbeitest.
:author: team-app-bi

Ein Report ist eine Datenanalyse, die als Ergebnis eine einzelne Kennzahl (KPI) oder eine Ergebnisliste ermittelt. Als Datenbasis für diese Analyse werden regelmäßig Rohdaten aus plentymarkets exportiert und auf einem sicheren Cloud-Speicher abgelegt.

== Rohdaten

Rohdaten werden im Hintergrund und im Regelfall nachts ermittelt. Welche Rohdaten abgelegt werden, legst du im Menü *Einrichtung » plentyBI » Rohdaten* fest. Die generierten Dateien kannst du per REST-API abrufen und extern verarbeiten.

=== Für Endanwender

Wir beobachten, dass Geschäftsentscheidungen oft nicht auf Basis von Kennzahlen, sondern eher aus dem Bauch heraus getroffen werden. Um dies zu verändern, empfehlen wir den Einsatz eines Business-Intelligence-Tools. Bestenfalls werden darin unterschiedliche Daten aus mehreren Quellen analysiert, um daraus konkrete Handlungsempfehlungen ableiten zu können. Lege jetzt los und nutze unser eigens entwickeltes plentyBI-Dashboard, um stets den Überblick über relevante Daten und Kennzahlen zu behalten. Alle weiteren Informationen findest du im Bereich xref:business-entscheidungen:plenty-bi.adoc#[plentyBI] des Handbuchs.

=== Für Entwickler

Rohdaten liegen im Format CSV vor und können somit einfach weiter verarbeitet werden. Alle plentymarkets Systeme verfügen über eine einheitliche REST-API. Die Dokumentation findest du auf link:https://developers.plentymarkets.com/[dieser Seite^].

Der Abruf von Rohdaten erfolgt in zwei Schritten. Wir empfehlen, den Abruf einmal pro Tag ab Mittag durchzuführen, da bis dahin für alle Systeme die Generierung der Rohdaten abgeschlossen ist.

1.	Zuerst wird über diese link:https://developers.plentymarkets.com/en-gb/plentymarkets-rest-api/index.html#/BI/get_rest_bi_raw_data[Route^] eine Liste der vorhandenen Rohdatendateien abgefragt. Der Erstellungszeitpunkt der beim letzten Abruf jüngsten Datei dient für die nächste Anfrage als Filter, um Dateien nicht wiederholt abzufragen. Die Anzahl der pro Tag generierten Dateien kann variieren, je nachdem wie viele Creator-Prozesse für ein plentymarkets System aktiviert wurden. Zudem wird in jede Datei nur eine bestimmte Anzahl an Datenzeilen geschrieben und im Bedarfsfall eine weitere Datei angelegt. Je nach Bedarf können mit dieser Route alle Dateien nur eines Creators oder alle Dateien die im Abfragezeitraum erstellt wurden, zurückgeliefert werden.
2.	Mit dieser link:https://developers.plentymarkets.com/en-gb/plentymarkets-rest-api/index.html#/BI/get_rest_bi_raw_data_file[Route^] wird eine Rohdatendatei zurückgeliefert. Der dafür nötige Dateipfad ist in der Ergebnismenge der unter Punkt 1 benannten REST-Route. Rohdatendateien werden als per GZIP (RFC 1952) komprimierte CSV-Dateien geliefert, wobei als Spaltentrennzeichen ein Komma verwendet wird.

[TIP]
.Standardzeitstempelformat
====
Das Standarddatumsformat ist MM/DD/YYYY HH:MI:SS TZ, da dies unverändert in eine AWS Redshift Spalte vom Typ TIMESTAMPTZ per copy-Befehl übernommen werden kann. Beispiel: 01/30/2019 05:14:57 Europe/Berlin
====

=== Datenformat-Creator

Mit Creator bezeichnen wir einen bestimmten Prozess, der ein Rohdatenformat bereitstellt. Jeder Creator legt erst dann Daten ab, wenn dieser zuvor im Menü *Einrichtung » plentyBI » Rohdaten* aktiviert wurde.

[NOTE]
.Automatische Aktivierung von Rohdatenformaten
====
Werden lediglich Kennzahlen im Menü *Einrichtung » plentyBI » Kennzahlen* erstellt, müssen die Rohdatenformate nicht manuell aktiviert werden. Die benötigten Datenformate werden automatisch im Hintergrund aktiviert, sobald die Konfiguration der Kennzahl gespeichert wird.
====

Die einzelnen Datenformate haben englische Bezeichnungen. Die Bedeutung sowie Links zu weiterführenden Informationen sind in <<table-reports-data-formats>> aufgelistet.


[IMPORTANT]
.Begrenzte Speicherung von Rohdaten und Berechungsergebnissen
====
Rohdaten stellen in plentymarkets die Datengrundlage für die Kennzahlen bereit, die im Modul xref:business-entscheidungen:plenty-bi.adoc#[plentyBI] zur Verfügung stehen. Je nach gebuchter plentyBI Edition werden Rohdaten unterschiedlich lang im System gespeichert und vorgehalten.
Folgende Speicherzeiträume gelten pro plentyBI Edition: +

* plentyBI XS: 6 Monate
* plentyBI S: 12 Monate
* plentyBI M: 24 Monate
* plentyBI L: 48 Monate

Die Berechnungsergebnisse, die sich aus den abgelegten Rohdaten ergeben, stehen pro plentyBI Edition unterschiedlich lang zur Verfügung: +

* plentyBI XS: 12 Monate
* plentyBI S: 24 Monate
* plentyBI M: 36 Monate
* plentyBI L: 120 Monate

Detailliertere Informationen pro Rohdatenformat sind per Klick auf die Links in <<table-reports-data-formats>> verfügbar.
====


[[table-reports-data-formats]]
.Verfügbare Rohdatenformate
[cols="1,3"]
|====
|Datenformat |Erläuterung

|accountContacts
|Kontakt +
Weitere Informationen findest du auf der Unterseite xref:business-entscheidungen:accountcontacts.adoc#[accountContacts].

|accounts
|Firma +
Weitere Informationen findest du auf der Unterseite xref:business-entscheidungen:accounts.adoc#[accounts].

|categories
|Kategorien +
Weitere Informationen findest du auf der Unterseite xref:business-entscheidungen:categories.adoc#[categories].

|feedbacks
|Feedbacks +
Weitere Informationen findest du auf der Unterseite xref:business-entscheidungen:feedbacks.adoc#[feedbacks].

|itemManufacturer
|Hersteller +
Weitere Informationen findest du auf der Unterseite xref:business-entscheidungen:itemmanufacturer.adoc#[itemManufacturer].

|itemVariations
|Variante +
Weitere Informationen findest du auf der Unterseite xref:business-entscheidungen:itemvariations.adoc#[itemVariations].

|itemVariationSuppliers
|Verknüpfungen zwischen Lieferanten und Varianten +
Weitere Informationen findest du auf der Unterseite xref:business-entscheidungen:itemvariationsuppliers.adoc#[itemVariationSuppliers].

|marketplaceStockMovement
|Warenbestandsinformationen, die zu Marktplätzen exportiert wurden +
Weitere Informationen findest du auf der Unterseite xref:business-entscheidungen:marketplaceStockMovement.adoc#[marketplaceStockMovement].

|messages
|Nachrichten +
Weitere Informationen findest du auf der Unterseite xref:business-entscheidungen:messages.adoc#[messages].

|messageTagRelations
|Tag-Verknüpfungen von Nachrichten +
Weitere Informationen findest du auf der Unterseite xref:business-entscheidungen:messageTagRelations.adoc#[messageTagRelations].

|orderDocuments
|Auftragsdokumente +
Weitere Informationen findest du auf der Unterseite xref:business-entscheidungen:orderdocuments.adoc#[orderDocuments].

|orderItemAmounts
|Wert der Auftragspositionen +
Weitere Informationen findest du auf der Unterseite xref:business-entscheidungen:orderitemamounts.adoc#[orderItemAmounts].

|orderItemProperties
|Eigenschaft der Auftragsposition +
Weitere Informationen findest du auf der Unterseite xref:business-entscheidungen:orderitemproperties.adoc#[orderItemProperties].

|orderItems
|Auftragsposition +
Weitere Informationen findest du auf der Unterseite xref:business-entscheidungen:orderitems.adoc#[orderItems].

|orderProperties
|Auftragseigenschaft +
Weitere Informationen findest du auf der Unterseite xref:business-entscheidungen:orderproperties.adoc#[orderProperties].

|orders
|Auftrag +
Weitere Informationen findest du auf der Unterseite xref:business-entscheidungen:orders.adoc#[orders].

|orderStatuses
|Auftragsstatus +
Weitere Informationen findest du auf der Unterseite xref:business-entscheidungen:orderstatuses.adoc#[orderStatuses].

|paymentOrderRelations
|Verknüpfungen zwischen Zahlungen und Aufträgen +
Weitere Informationen findest du auf der Unterseite xref:business-entscheidungen:paymentorderrelations.adoc#[paymentOrderRelations].

|payments
|Zahlungen +
Weitere Informationen findest du auf der Unterseite xref:business-entscheidungen:payments.adoc#[payments].

|properties
|Eigenschaften +
Weitere Informationen findest du auf der Unterseite xref:business-entscheidungen:properties.adoc#[properties].

|propertyRelations
|Verknüpfungen zwischen Eigenschaften und anderen Daten +
Weitere Informationen findest du auf der Unterseite xref:business-entscheidungen:propertyrelations.adoc#[propertyRelations].

|stockManagementStock
|Bestand +
Weitere Informationen findest du auf der Unterseite xref:business-entscheidungen:stockmanagementstock.adoc#[stockManagementStock]

|stockManagementStockMovements
|Warenbewegungen +
Weitere Informationen findest du auf der Unterseite xref:business-entscheidungen:stockmanagementstockmovements.adoc#[stockManagementStockMovements]

|stockManagementWarehouses
|Lager +
Weitere Informationen findest du auf der Unterseite xref:business-entscheidungen:stockmanagementwarehouses.adoc#[stockManagementWarehouses]

|tags
|Tags +
Weitere Informationen findest du auf der Unterseite xref:business-entscheidungen:tags.adoc#[tags].

|tagRelations
|Tag-Verknüpfungen +
Weitere Informationen findest du auf der Unterseite xref:business-entscheidungen:tagrelations.adoc#[tagRelations].

|users
|Benutzer +
Weitere Informationen findest du auf der Unterseite xref:business-entscheidungen:users.adoc#[users].

|variationValidation
|Artikelvarianten, die zu Marktplätzen exportiert, aber abgelehnt wurden +
Weitere Informationen findest du auf der Unterseite xref:business-entscheidungen:VariationValidation.adoc#[variationValidation].

|====

Weitere Datenformate werden sukzessive ergänzt und in dieser Tabelle hinzugefügt.
