= Traffic-Verbrauch
:keywords: Verbrauch, Verbrauchsdaten, Traffic-Verbrauch, Traffic
:author: team-app-bi
:description: Diese Seite erläutert die Berechnungen, Dimensionen und Filter, die dir für die Kennzahl Traffic-Verbrauch zur Verfügung stehen.

Das Datenvolumen und der zulässige Traffic sind je nach gebuchter plentymarkets Edition begrenzt. Überschreitungen werden separat in Rechnung gestellt. plentymarkets bietet dir daher die Möglichkeit, deinen Verbrauch jederzeit nachzuvollziehen.

:kennzahl: Traffic-Verbrauch

include::partial$kennzahlen-einleitung.adoc[]

[TIP]
.Was ist Traffic?
====
Wünscht du dir weitere Informationen zum Thema oder bist nicht sicher, welche Aktionen so genannten Traffic verursachen? Schau dir die Handbuchseite xref:business-entscheidungen:hosting-daten.adoc#100[Verbrauchsdaten] an.
====

[IMPORTANT]
.Standard-Kennzahl nutzen
====
Die Kennzahl *Traffic-Verbrauch* ist eine so genannte Standard-Kennzahl. Das bedeutet, dass sie in deinem plentymarkets System bereits mit einigen Voreinstellungen eingerichtet ist. Du musst also nicht zwingend eine zusätzliche Kennzahl erstellen. Öffne das Menü *Einrichtung » plentyBI » Kennzahlen* und klicke auf die Kennzahl *Traffic-Verbrauch*, die von `plentymarkets` erstellt wurde. Passe bei Bedarf die voreingestellten Optionen an und ergänze die gewünschten <<#300, Filter>>.
====

[#100]
== plentyBI Edition

Dies ist eine kostenlose Kennzahl.
Du kannst die Kennzahl verwenden, ohne vorher eine plentyBI Edition gebucht zu haben.

Beachte jedoch, dass _andere Funktionen und Kennzahlen_ des plentyBI-Tools kostenpflichtig sind.

Buche ganz einfach die passende plentyBI Edition mit Hilfe des plentymarkets Konfigurators.

* *_Neukunden_*: Buche die passende plentyBI Edition link:https://get.plentymarkets.com/[während du plentymarkets bestellst^].
* *_Bestandskunden_*: Buche die passende plentyBI Edition xref:business-entscheidungen:dein-vertrag.adoc#30[im "Mein Konto"-Bereich].

[#200]
== Dimension

=== Erstellungsdatum

:kennzahl: Der Traffic-Verbrauch
:das-bedeutet: Die Verbrauchsdaten werden also nach dem Datum gruppiert, an dem der Verbrauch angefallen ist.

include::partial$erstellungsdatum.adoc[]

[#300]
== Filter

include::partial$filter-einleitung.adoc[]

=== Erstellungsdatum

Verwende diesen Filter, um den Träffic-Verbrauch anhand des Datums oder des Zeitraums zu gruppieren, in dem der Verbrauch angefallen ist.

Wähle einen der folgenden Vergleichsoperatoren aus und wähle dann rechts das gewünschte Datum oder einen Zeitraum.


[.collapseBox]
.Vergleichsoperatoren für diesen Filter
--

:filter-endung: gewählten Terminen
:filter: gewählten Termine
:kommas:

[cols="1,3"]
|====
| Vergleichsoperator | Erklärung

include::partial$ist-gleich.adoc[]

include::partial$liegt-zwischen.adoc[]

include::partial$groesser-als-oder-gleich.adoc[]

include::partial$kleiner-als-oder-gleich.adoc[]

include::partial$groesser-als.adoc[]

include::partial$kleiner-als.adoc[]


|====

--

//Praxisbeispiel (mit Kachel) hinzufügen
