= Traffic-Verbrauch
:keywords: Verbrauch, Verbrauchsdaten, Traffic-Verbrauch, Traffic
:author: team-app-bi

////
TODO: Einleitung, was macht die Kennzahl?
Um zu wissen, wie viel dich die Änderungshistorie kostet, musst du also zuerst deinen Verbrauch kennen.
Mithilfe der kostenlosen Kennzahl *Service-Verbrauch* kannst du deinen Verbrauch jederzeit tagesaktuell einsehen.

Vermutlich ist das hier gemeint: https://knowledge.plentymarkets.com/de-de/manual/main/business-entscheidungen/hosting-daten.html
////

:kennzahl: Traffic-Verbrauch

include::partial$kennzahlen-einleitung.adoc[]

[#500]
== plentyBI Edition

Dies ist eine kostenlose Kennzahl.
Du kannst die Kennzahl verwenden, ohne vorher eine plentyBI Edition gebucht zu haben.

Beachte jedoch, dass _andere Funktionen und Kennzahlen_ des plentyBI-Tools kostenpflichtig sind.

Buche ganz einfach die passende plentyBI Edition mit Hilfe des plentymarkets Konfigurators.

* *_Neukunden_*: Buche die passende plentyBI Edition link:https://get.plentymarkets.com/[während du plentymarkets bestellst^].
* *_Bestandskunden_*: Buche die passende plentyBI Edition xref:business-entscheidungen:dein-vertrag.adoc#30[im "Mein Konto"-Bereich].

[#100]
== Berechnung

=== Traffic-Verbrauch

//TODO

[#200]
== Dimension

=== Erstellungsdatum

:kennzahl: Der Traffic-Verbrauch
:das-bedeutet: Bei der Berechnung wird dementsprechend 
//TODO

include::partial$erstellungsdatum.adoc[]

[#300]
== Filter

include::partial$filter-einleitung.adoc[]

=== Erstellungsdatum

////
Willst du wissen, ...
Verwende diesen Filter, um den Träffic-Verbrauch anhand des Erstellungsdatums der Änderung zu analysieren.

Wähle einen der folgenden Vergleichsoperatoren aus und wähle dann rechts das gewünschte Datum oder einen Zeitraum.
////


[.collapseBox]
.Vergleichsoperatoren für diesen Filter
--


:filter-endung: gewählten Terminen
:filter: gewählten Termine
:kommas:

[cols="1,3"]
|====
| Vergleichsoperator | Erklärung

include::partial$ist-gleich.adoc[]

include::partial$liegt-zwischen.adoc[]

include::partial$groesser-als-oder-gleich.adoc[]

include::partial$kleiner-als-oder-gleich.adoc[]

include::partial$groesser-als.adoc[]

include::partial$kleiner-als.adoc[]


|====

--

[#400]
== Praxisbeispiel




