= Service-Verbrauch
:keywords: Verbrauch, Verbrauchsdaten, Service-Verbrauch, Nutzung, Nutzungsdaten, Usage, Änderungshistorie, Historie
:description: Erfahre mehr über Verbrauchsdaten und wie Traffic entsteht.
:author: team-item
//zuletzt bearbeitet 04.11.2022

Wenn du die xref:daten:aenderungshistorie.adoc#100[Änderungshistorie] verwendest, fallen verbrauchsabhängig die folgenden Kosten an:

* 15 Cent pro angefangenen 10.000 geloggten Änderungen.
* 15 Cent pro angefangenen 10.000 archivierten Änderungen.
* 1 Euro für das Anfordern einer Datei aus dem Archiv.

Um zu wissen, wie viel dich die Änderungshistorie kostet, musst du also zuerst deinen Verbrauch kennen.
Mithilfe der kostenlosen Kennzahl *Service-Verbrauch* kannst du deinen Verbrauch jederzeit tagesaktuell einsehen.

:kennzahl: Service-Verbrauch

include::partial$kennzahlen-einleitung.adoc[]

.Lerne die Kennzahl "Service-Verbrauch" kennen
video::521383716[vimeo]

[#400]
== Benötigte Einstellungen

Da diese Kennzahl den Verbrauch der Änderungshistorie ermittelt, wirst du nur Daten sehen, wenn du die xref:daten:aenderungshistorie.adoc#1100[Änderungshistorie für dein System aktiviert] hast.

[#500]
== plentyBI Edition

Dies ist eine kostenlose Kennzahl.
Du kannst also die Kennzahl verwenden, ohne vorher eine plentyBI Edition gebucht zu haben.

Beachte jedoch, dass _andere Funktionen und Kennzahlen_ des plentyBI-Tools kostenpflichtig sind.
Buche ganz einfach die passende plentyBI Edition mit Hilfe des plentysystems Konfigurators.

* *_Neukunden_*: Buche die passende plentyBI Edition link:https://get.plentymarkets.com/[während du plentysystems bestellst^].
* *_Bestandskunden_*: Buche die passende plentyBI Edition xref:business-entscheidungen:dein-vertrag.adoc#30[im "Mein Konto"-Bereich].

[#100]
== Berechnung

=== Durchschnitt
//Durchschnitt wird wohl erst für andere Anwendungsfälle außer Änderungshistorie Sinn machen - ist nur als Vorbereitung da

:kennzahl: Der Verbrauch
:das-bedeutet: Das heißt, die Kennzahl gibt die durchschnittliche Anzahl der loggbaren Änderungen aus.

include::partial$durchschnitt.adoc[]

////
[discrete]
===== Anwendungsbeispiel

Bist du neugierig, wie viel dich die Änderungshistorie _im Durchschnitt_ jeden Monat kostet?
Gehe wie folgt vor:

. Erstelle eine Service-Verbrauch-Kennzahl und wähle die Durchschnittsberechnung.
. Erstelle im xref:business-entscheidungen:myview-dashboard.adoc#400[Dashboard] z.B. ein Balkendiagramm, um die durchschnittlichen Verbrauchswerte über die letzten 12 Monate zu visualisieren.
. xref:business-entscheidungen:verbrauch.adoc#600[Berechne] deine durchschnittlichen monatlichen Kosten anhand dieser Verbrauchsdaten.
////

=== Maximum
//Maximum wird wohl erst für andere Anwendungsfälle außer Änderungshistorie Sinn machen - ist nur als Vorbereitung da

:kennzahl: Der Verbrauch
:das-bedeutet: Das heißt, die Kennzahl gibt die bisher höchste Anzahl an loggbaren Änderungen aus.

include::partial$maximum.adoc[]

=== Summe

:kennzahl: Der Verbrauch
:das-bedeutet: Das heißt, die Kennzahl gibt die Gesamtzahl aller loggbaren Änderungen aus.

include::partial$summe.adoc[]

[discrete]
===== Anwendungsbeispiel

Bist du neugierig, wie viel dich die Änderungshistorie diesen Monat kosten wird?
Gehe wie folgt vor:

. Erstelle eine Service-Verbrauch-Kennzahl und wähle die Summenberechnung.
. Erstelle im xref:business-entscheidungen:myview-dashboard.adoc#400[Dashboard] z.B. eine Kachel, die die Gesamtzahl der Änderungen in diesem Monat anzeigt.
. xref:business-entscheidungen:verbrauch.adoc#600[Berechne] entsprechend deine Gesamtkosten für diesen Monat.


[#200]
== Dimension

=== Erstellungsdatum

:kennzahl: Der Verbrauch
:das-bedeutet: Bei der Berechnung wird dementsprechend das Datum, an dem die Änderung geloggt wurde, einbezogen.

include::partial$erstellungsdatum.adoc[]

[#300]
== Filter

include::partial$filter-einleitung.adoc[]

=== Erstellungsdatum

Willst du wissen, wie viele Änderungen an einem bestimmten Datum oder während eines bestimmten Zeitraums geloggt wurden?
Verwende diesen Filter, um deinen Verbrauch anhand des Erstellungsdatums der Änderung zu analysieren.

Wähle einen Vergleichsoperatoren aus und wähle dann rechts das gewünschte Datum oder einen Zeitraum.

=== Service

Willst du nur einen bestimmten Aspekt der Änderungshistorie untersuchen?

[cols="1,3"]
|====
| Service | Erklärung

| *Änderungshistorie - Live Änderungen*
|Verwende diesen Filter, um die Anzahl der geloggten Änderungen in der xref:daten:aenderungshistorie.adoc#200[Live-Suche] zu ermitteln.

*_Hinweis_*:
Die Verbrauchsdaten werden einmal pro Tag berechnet.
Dies passiert jeden Abend für den Vortag.
Also heute Abend für gestern.

| *Änderungshistorie - Archiv Änderungen*
|Verwende diesen Filter, um die Anzahl der geloggten Änderungen im xref:daten:aenderungshistorie.adoc#1000[Archiv] zu ermitteln.

*_Hinweis_*:
Die Verbrauchsdaten werden einmal im Monat berechnet.
Wenn du also deinen Verbrauch z.B. mit Hilfe eines Balkendiagramms verfolgst, siehst du einmal im Monat eine Spitze, wenn die Archivdaten gezählt werden.

| *Änderungshistorie - Archiv Anforderung*
|Verwende diesen Filter, um zu sehen, wie oft jemand eine kostenpflichtige xref:daten:aenderungshistorie.adoc#1000[Archivdatei] angefordert hat.
|====

Wähle einen Vergleichsoperatoren aus der ersten Dropdown-Liste aus. Wähle den gewünschten Dienst aus der zweiten Dropdown-Liste aus.

[#600]
== Beispielrechnung

Wenn du die xref:daten:aenderungshistorie.adoc#100[Änderungshistorie] verwendest, fallen verbrauchsabhängig die folgenden Kosten an:

* 15 Cent pro angefangenen 10.000 geloggten Änderungen.
* 15 Cent pro angefangenen 10.000 archivierten Änderungen.
* 1 Euro für das Anfordern einer Datei aus dem Archiv.

Wenn du also plentysystems GoBD-konform nutzen willst, indem du relevante Änderungen bis zu 11 Jahre in plentysystems speicherst, fallen 30 Cent pro angefangenen 10.000 Änderungen an.
Die Kosten für ein Daten-Paket werden nur in dem Monat berechnet, in dem sie geloggt wurden.


In einem Monat werden durchschnittlich 177.000 loggbare Änderungen pro System gemacht.
Das entspricht im Schnitt 18 Paketen (177.000 / 10.000 aufgerundet).
Bei aktivierter Änderungshistorie samt Archiv ergibt das durchschnittliche Kosten im Monat von 18 * 0,15 * 2 = 5,40 €.
