= Verfahrensdokumentation
:description: Lade über diese Seite die technische Systemdokumentation von plentysystems herunter, die den Anwendern der plentysystems Software jedoch lediglich als Grundlage zur Erstellung deiner Verfahrensdokumentation dient.
:keywords: GoBD, rechtlich, steuerrechtlich, Steuerrecht, Systemdokumentation, technische Systemdokumentation, Verfahrensdokumentation, Verfahrensweise, verwendete Software, rechtssicher arbeiten, Steuerprüfung, Arbeitsweise, Verfahren
:id: JMGHYFQ
:author: team-plenty-channel

Auf dieser Handbuchseite stellen wir dir die technische Systemdokumentation von plentysystems zur Verfügung. Diese Systemdokumentation dient als Grundlage zur Erstellung deiner eigenen Verfahrensdokumentation.

== Rechtssicher arbeiten mit plentysystems

Nach GoBD müssen Händler:innen unter anderem die Verfahrensweise der von ihnen verwendeten Software in Form einer Verfahrensdokumentation beschreiben und im Falle einer Steuerprüfung vorlegen. Wir unterstützen Nutzer:innen von plentysystems bei der Erstellung einer Verfahrensdokumentation durch die Bereitstellung einer technischen Systemdokumentation. In dieser Systemdokumentation werden die steuerrechtlich relevanten Arbeitsweisen von plentysystems aufgeschlüsselt, die als Grundlage für eine Verfahrensdokumentation verwendet werden können.

Beachte, dass die hier bereitgestellte Systemdokumentation lediglich eine *Vorlage* zur Erstellung der Verfahrensdokumentation ist. Lies die Dokumentation aufmerksam und ergänze spezifische Informationen über dein Unternehmen und deine Arbeitsweise mit deinem System.

== Link zum Download

Lade die aktuelle Version der technischen Systemdokumentation von plentysystems link:https://cdn02.plentymarkets.com/pmsbpnokwu6a/frontend/plentymarkets_Rechtliches/Verfahrensdokumentation_8.0.pdf[hier herunter^]. Ältere Versionen findest du link:https://github.com/plentymarkets/template-procedure-document/releases[hier^].

[IMPORTANT]
.Andere Softwarelösungen
====
plentysystems ist in der Regel nur ein Teil der in der Verfahrensdokumentation zu beschreibenden (Software-)Lösungen. Kläre mit deinem Steuerbüro, welche für deinen individuellen Fall relevanten Informationen zusätzlich in der Verfahrensdokumentation beschrieben werden müssen.
====
