= Version (Beta, Early, Stable)
:keywords: Entwicklungsstand, Entwicklungsstadium, Entwicklungsstadien, Version, Versionszyklus, Versionierung, Softwarerelease, Software-Release, Release-Zyklus, Beta, Early, Stable
:id: 4YXZVNG
:author: team-cloud

////
zuletzt bearbeitet 21.07.2022
////

plentymarkets wird ständig verbessert und weiterentwickelt.
Wenn eine neue Funktion veröffentlicht wird, durchläuft sie drei Entwicklungsstadien: Beta, Early und Stable.

[#10]
== Release-Zyklus verstehen

[discrete]
=== Beta

Entwicklungsteams überführen fertiggestellte Funktionen in die Version Beta.
In dieser Version können die Funktionen getestet werden.
Gemeldete Fehler werden behoben.

[cols="1a,1a", width=100%]
|===
|Vorteile |Nachteile

|
* Besonders früher Zugang zu neuen Funktionen
* Besonders hohes Maß an Gestaltungspotenzial und Einflussnahme
* Möglichkeit, eigene Plugins frühzeitig zu testen

|
* Fehler können auftreten

|===

---

[discrete]
=== Early

Wenn in der Beta-Phase keine kritischen Mängel gefunden oder diese Mängel in der Beta-Phase korrigiert wurden, wird der Beta-Stand nach frühestens 7 Tagen in die Version Early überführt.

[cols="1a,1a", width=100%]
|===
|Vorteile |Nachteile

|
* Früher Zugang zu neuen Funktionen
* Schnellere Hilfe im Forum: Anfragen werden priorisiert bearbeitet
* Hohes Maß an Gestaltungspotenzial und Einflussnahme

|
* Kann noch vereinzelte Fehler enthalten

|===

---

[discrete]
=== Stable

Wenn während der Early-Phase keine gravierenden Mängel mehr auffallen, wird der Early-Zustand nach frühestens 7 Tagen in die Version Stable überführt.


[cols="1a,1a", width=100%]
|===
|Vorteile |Nachteile

|
* Stabilität

|
* Später Zugang zu neuen Features und Verbesserungen
* Weniger Gestaltungspotenzial

|===

[#20]
== Version wechseln

Standardmäßig werden Systeme in der Version Stable bereitgestellt.
Wenn du jedoch früher von Verbesserungen und neuen Features profitieren möchtest, kannst du dein System auf eine frühere Version umstellen.

[IMPORTANT]
.Umstellung kann nicht rückgängig gemacht werden
====
Wir freuen uns, dass du plentymarkets noch besser machen willst, indem du eine frühere Version nutzt und gefundene Bugs meldest.
Beachte jedoch, dass die Umstellung auf eine frühere Version nicht rückgängig gemacht werden kann.
Wäge daher die Vorteile und Nachteile der Versionen ab, bevor du dein System umstellst.
====

[.instruction]
System auf eine frühere Version umstellen:

. Öffne das Menü *Einrichtung » Mandant » Global » Version*. +
*_Hinweis:_* Alle Mandanten haben dieselbe Version.
Wenn du also mit mehreren Mandanten arbeitest, werden sie alle auf die neue Version umgestellt.
. Wähle in der Dropdown-Liste die Version, auf die du das System umstellen möchtest. +
*_Wichtig:_* Du kannst das System nur auf eine frühere Version umstellen.
Eine Umstellung auf eine spätere Version ist nicht möglich.
. *Speichere* (terra:save[role="darkGrey"]) die Einstellung. +
→ Das System wird auf die gewählte Version umgestellt.
Dies kann bis zu 30 Minuten dauern.

[#30]
== Auf dem Laufenden bleiben

Du möchtest über kürzlich entwickelte Funktionen und behobene Fehler informiert werden?
Wirf einen Blick auf den xref:ROOT:changelog.adoc[Changelog].
Er bietet einen Überblick über die Änderungen, die im Laufe der Woche in Stable und Early eingeflossen sind.
