= Version (Beta, Early, Stable)
:keywords: Entwicklungsstand, Entwicklungsstadium, Entwicklungsstadien, Version, Versionszyklus, Versionierung, Softwarerelease, Software-Release, Release-Zyklus, Beta, Early, Stable
:description: Erfahre mehr über unsere Systemversionen, ihre Vor- und Nachteile und wie du dein System auf eine andere Version umstellst.
:author: team-cloud

////
zuletzt bearbeitet 22.07.2022
////

plentymarkets wird ständig verbessert und weiterentwickelt.
Wenn eine neue Funktion veröffentlicht wird, durchläuft sie drei Entwicklungsstadien: Beta, Early und Stable.

[#10]
== Release-Zyklus verstehen

[discrete]
=== Beta

Entwicklerteams überführen neu entwickelte Funktionen in die Beta-Version.
In dieser Version wird die Funktion getestet und gemeldete Fehler werden behoben.
Die Beta-Phase dauert mindestens 7 Tage.

[cols="1a,1a", width=100%]
|===
|Vorteile von Beta |Nachteile von Beta

|
* Besonders früher Zugang zu neuen Funktionen
* Besonders hohes Maß an Gestaltungspotenzial und Einflussnahme
* Möglichkeit, eigene Plugins frühzeitig zu testen

|
* Fehler können auftreten

|===

---

[discrete]
=== Early

Nach frühestens 7 Tagen wird die Beta-Version in die Early-Version überführt.
Dies setzt voraus, dass während der Beta-Phase keine kritischen Mängel gefunden wurden oder diese Mängel behoben wurden.
Die Early-Phase dauert ebenfalls mindestens 7 Tage.

[cols="1a,1a", width=100%]
|===
|Vorteile von Early |Nachteile von Early

|
* Früher Zugang zu neuen Funktionen
* Schnellere Hilfe im Forum: Anfragen werden priorisiert bearbeitet
* Hohes Maß an Gestaltungspotenzial und Einflussnahme

|
* Kann noch vereinzelte Fehler enthalten

|===

---

[discrete]
=== Stable

Nach frühestens 7 Tagen wird die Early-Version in die Stable-Version überführt.
Dies setzt voraus, dass während der Early-Phase keine gravierenden Mängel mehr auffallen.

[cols="1a,1a", width=100%]
|===
|Vorteile von Stable |Nachteile von Stable

|
* Stabilität

|
* Später Zugang zu neuen Features und Verbesserungen
* Weniger Gestaltungspotenzial

|===

[#20]
== Version wechseln

Standardmäßig werden Systeme in der Version Stable bereitgestellt.
Wenn du jedoch früher von Verbesserungen und neuen Features profitieren möchtest, kannst du dein System auf eine frühere Version umstellen.

[IMPORTANT]
.Umstellung kann nicht rückgängig gemacht werden
====
Wir freuen uns, dass du plentymarkets noch besser machen willst, indem du eine frühere Version nutzt und gefundene Bugs meldest.
Beachte jedoch, dass die Umstellung auf eine frühere Version nicht rückgängig gemacht werden kann.
Wäge daher die Vorteile und Nachteile der Versionen ab, bevor du dein System umstellst.
====

[.instruction]
System auf eine frühere Version umstellen:

. Öffne das Menü *Einrichtung » Mandant » Global » Version*. +
*_Hinweis_*: Alle Mandanten haben dieselbe Version.
Wenn du also mit mehreren Mandanten arbeitest, werden sie alle auf die neue Version umgestellt.
. Wähle in der Dropdown-Liste die Version, auf die du das System umstellen möchtest. +
*_Wichtig_*: Du kannst das System nur auf eine frühere Version umstellen.
Eine Umstellung auf eine spätere Version ist nicht möglich.
. *Speichere* (terra:save[role="darkGrey"]) die Einstellung. +
→ Das System wird auf die gewählte Version umgestellt.
Dies kann bis zu 30 Minuten dauern.

[#30]
== Auf dem Laufenden bleiben

Du möchtest über kürzlich entwickelte Funktionen und behobene Fehler informiert werden?
Wirf einen Blick auf den xref:ROOT:changelog.adoc[Changelog].
Er bietet einen Überblick über die Änderungen, die im Laufe der Woche in Stable und Early eingeflossen sind.
