= Zentraler Login
:keywords: login, plentysystems, MFA, Multi-Faktor-Authentifizierung, Zeitzone, Sprache, Passwort ändern, neues Passwort
:description: Erfahre mehr über den zentralen Login, die Multi-Faktor-Authentifizierung und wie du plentysystems Konten in dein System einlädst.
:author: team platform

Im zentralen Login deines plentysystems Kontos kannst du dich in alle Systeme einloggen, in die du eingeladen wurdest und deine Sprache sowie Zeitzone angeben. Zusätzlich hast du hier die Möglichkeit ein neues Passwort für dein plentysystems Konto zu vergeben und du kannst die Multi-Faktor-Authentifizierung aktvieren.

Um den zentralen Login effektiv zu nutzen, brauchst du ein plentysystem Konto, damit du Zugriff auf die Systemübersicht und Multi-Faktor-Authentifizierung hast.

[IMPORTANT]
.End of Life des alten Logins
====
Das End of Life des alten Logins wurde für das erste Quartal 2024 angesetzt. Solange ist der alte Login für Administrator sowie Nicht-Administrator nutzbar.

Wenn du dich als Nicht-Administrator im alten Login anmeldest, wirst du auf den zentralen Login ohne Mailadresse weitergeleitet. Hier musst du dann erneut das Passwort eintragen und anschließend wirst in das entsprechende System eingeloggt.

Die zweifache Passworteingabe entfällt, wenn du dich direkt im link:account.plentysystems.com[zentralen Login^] mit deinem bestehenden Anmeldedaten im System anmeldest.
====

[#50]
== ein plentysystems Konto erstellen

Gehe wie folgt vor, um ein plentysystems Konto zu erstellen:

. Geh auf die Seite https://account.plentysystems.com/login.
. Klicke auf *Account erstellen*.
. Gib eine E-Mail-Adresse ein.
. Gib ein Passwort ein und bestätige dieses.
. Klicke auf *Neues Konto erstellen*.

Wenn du eine Einladungs-E-Mail erhalten hast und noch kein plentysystems Konto erstellt hast, kannst du das plentysystems Konto über den Link in der Einladung erstellen.

[#100]
== Login

Du kannst dich im zentralen Login über zwei Wege anmelden:

* mit E-Mail-Adresse und Passwort
* mit plenty ID, Benutzer:innen-Name und Passwort

[NOTE]
.Login mit PID, Benutzer:innen-Konto und Passwort
====
Meldest du dich mit plenty ID, Benutzer:innen-Konto und Passwort ein, wirst du direkt in das System weitergeleitet und überspringst die Systemübersicht. Über diesen Weg hast du keinen Zugriff auf die Multi-Faktor-Authentifizierung.
====

[#200]
== Systemübersicht

In der Systemübersicht werden dir alle Systeme angezeigt, die mit deinem plentysystems Konto verknüpft sind sowie ihre plenty ID (PID) und die Systemversion. Von hier aus kannst du dich dann in einem System deiner Wahl anmelden. Außerdem erreichst du hierüber auch die *Kontoeinstellungen* (material:settings[]).

Über *plenty ID suchen* (material:search[]) kannst du ein bestimmtes System suchen, indem du die plenty ID eingibst. Außerdem hast du die Möglichkeit, die Systeme absteigend oder aufsteigend nach plenty ID zu sortieren. Klicke dafür auf material:arrow_downward[].

[#300]
== Kontoeinstellungen

Im Menü *Kontoeinstellungen* kannst du Einstellungen vornehmen, die für dein plentysystems Konto gelten und für jedes System , das mit deinem plentysystems Konto verknüpft ist. Die Kontoeinstellungen unterteilen sich in die Menüs *Konto* und *Sicherheit*

[#330]
=== Konto

Im Menü *Kontoeinstellungen » Konto* kannst du den Vor- und Nachnamen deines plentysystems Konto angeben, sowie die Zeitzone und Sprache.

*Kontoeinstellungen vornehmen*:

. Öffne das Menü *Login » Kontoeinstellungen » Konto*.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<tabelle-konto-einstellen>>.
. Speichere (material:save[]) die Einstellungen.

[[tabelle-konto-einstellen]]
.Einstellungen im Bereich Konto
[cols="1,2"]
|===
|Einstellung |Erläuterung

|Vorname
|Realer Vorname der Benutzer:innen, der im jeden verknüpften System angezeigt wird.

|Nachname
|Realer Nachname der Benutzer:innen, der im jeden verknüpften System angezeigt wird.

|Zeitzone
|Zeitzone, die in jedem verknüpften System verwendet wird.

|Sprache
|Sprache, die in jedem verknüpften System verwendet wird. Die Browsersprache ist als Srandard vorausgewählt.
|===

[#360]
=== Sicherheit

Im Menü *Kontoeinstellungen » Sicherheit* kannst du das Passwort deines plentysystems Kontos ändern und die Multi-Faktor-Authentifizierung aktivieren.

*Passwort ändern*:

. Öffne das Menü *Login » Kontoeinstellungen » Sicherheit*.
. Gib unter *Aktuelles Passwort* dein jetziges Passwort ein.
. Gib unter *Neues Passwort* dein neues Passwort ein.
. Wiederhole das neue Passwort.
. Speichere (material:save[]) deine Einstellungen.

[#380]
==== Multi-Faktor-Authentifizierung aktivieren

Du kannst die Multi-Faktor-Authentifizierung aktivieren, um die Sicherheit deines Systems zu erhöhen. Mit dieser zusätzlichen Verifizierungsmethode erschwerst du es Unbefugten auf dein plentysystems Konto und die verknüpften Systeme zuzugreifen.

*Multi-Faktor-Authentifizierung aktivieren*:

. Öffne das Menü *Login » Kontoeinstellungen » Sicherheit*.
. Aktiviere die Multi-Faktor-Authentifizierung. +
→ Der QR-Code für die Authenticator App öffnet sich.
. Scanne den QR-Code mit deiner Authenticator-App.
. Gib den Code, den du in deiner Authenticator-App siehst, unter *MFA-Code* ein.
. Klicke auf *MFA aktivieren*.

[#400]
== Allgemeine Fragen

[.collapseBox]
.*Wie verknüpfe ich ein neues Benutzer:innen-Konto mit einem plentysystems Konto?*
--
include::page$benutzerkonten-zugaenge.adoc[tag=create-and-connect-user-with-plentysystems-account]

[[tabelle-benutzer:innen-daten]]
.Einstellungen in der Einladungs-Detailansicht
[cols="1,2"]
|===
|Einstellung |Erläuterung

| *App-Pin*
|include::app:partial$app-pin.adoc[]

| *App-Pin wiederholen*
|PIN noch einmal eingeben.

| *IP beschränken*
|IP-Adresse des Rechners der Person des Benutzer:innen-Kontos eingeben, damit sich die Person mit diesem Benutzer:innen-Konto nur über diese IP-Adresse in das  System einloggen kann.

| *Benutzer:innen-Zugang*
|Benutzer:innen-Zugang des Benutzer:innen-Kontos wählen. Es stehen die Zugänge *Administrator*, und *Nur API-Benutzer* zur Verfügung. +
 Ein *Administrator* hat alle Menü-Sichtbarkeiten, Rollendefinierte Ansichten, Zugriffsrechte und Berechtigungen, kann Benutzer:innen-Konton erstellen, deaktvieren und Logins entsperren. Außerdem kann er Rollen erstellen, bearbeiten, löschen und zuweisen. +
 *Nur API-Benutzer* können nur REST-API Calls nutzen, sie erhalten keine Menü- und Plugin-Sichtbarkeiten.

| *Zugewiesene Rollen*
|Rollen des Benutzer:innen-Kontos wählen. Damit Rollen zur Auswahl stehen, müssen zuvor xref:business-entscheidungen:benutzerkonten-zugaenge.adoc#70[Rollen] erstellt werden.

| *Signatur*
| Text, der Nachrichten und Kommentaren der Benutzer:innen im Ticketsystem automatisch als xref:crm:ticketsystem-nutzen.adoc#300[Signatur] angefügt wird.

| *Ticket-Grußformel*
| Text, der Nachrichten und Kommentaren der Benutzer:innen im Ticketsystem automatisch als xref:crm:ticketsystem-nutzen.adoc#300[Grußformel] angefügt wird.

|===

--

[.collapseBox]
.*Wie verknüpfe ich bestehende Benutzer:innen-Konten mit einem plentysystems Konto?*
--
include::page$benutzerkonten-zugaenge.adoc[tag=connect-user-with-plentysystems-account]
--

[.collapseBox]
.*Lassen sich Benutzer:innen-Konten erneute einladen?*
--
Du kannst jederzeit eine:n Benutzer:in nochmals eine Einladung zu deinem System schicken. Entweder im Menü Einrichtung » Kontoverwaltung » Konten oder in der Detail-Ansicht des Kontos. Gehe wie folgt vor:

. Gehe entweder in das Menü *Einrichtung » Kontoverwaltung » Konten* oder in die Detail-Ansicht des Kontos.
. Klicke auf das *Mehr* (material:more_vert[])
. Klicke auf *Benutzer erneut einladen* (material:send[])
--