= Adjustment form
:page-aliases: generate-adjustment-forms.adoc
:keywords: adjustment form, generating adjustment form, creating adjustment form, order documents, document template, credit note order, document type, document
:author: team-docs-automation
:description: In order to correct existing orders, you can create an adjustment form for the order type credit note. Learn how to set up a document template for adjustment forms and how to generate adjustment forms.

Use an adjustment form when you need to correct an order. Imagine, for example, a customer ordered three items but you can only send two of those items. You tell your customer and since s/he already paid for the three items, s/he wants a refund. What do you do? You create an order of the type xref:orders:order-type-credit-note.adoc#[credit note]. Only after doing this you can create an adjustment form in this credit note order. You can either create a single adjustment form or generate multiple ones. Generate PDF files to print them or to send them to your customers as an email attachment.

[#100]
== Setting up a document template for adjustment forms

Before generating adjustment forms, you have to set up a document template. Go to *Setup » Client » [select client] » Locations » [Select location] » Documents » Adjustment form* to set up the template. +
Further information and instructions on setting up the document template are available on the xref:orders:order-documents-new.adoc#[Order documents] page of the manual.

[#200]
== Creating a single adjustment form

Adjustment forms can only be created from the order type *Credit note*. To create a single adjustment form for a specific credit note order, proceed as follows.

[.instruction]
Creating a single adjustment form:

. Go to *Orders » Orders (Test phase)*. +
→ The order overview opens.
. Carry out the search (material:search[]) to display orders.
. Open the order of the type credit note for which you want to generate a credit note. Note that orders can only be opened in the list view.
. Go to the *Documents* area.
. At the top left, click on *Create document* (material:add[]).
. Select the *Adjustment form* document from the drop-down list. +
→ The window *Create document: Adjustment form* opens.
. Select a date that should be displayed on the adjustment form.
. Optionally enter a comment that should be displayed on the adjustment form.
. Click on *Create* (material:add[role=”green”]). +
→ The adjustment form is created and added to the *Documents* area.

[#300]
== Generating multiple adjustment forms

If you want to generate several adjustment forms at once, use the search filters in the *Orders » Fulfilment* menu to determine the orders for which adjustment forms are to be generated. In addition, you can determine whether a status change should take place after the adjustment forms have been generated.

[.instruction]
Generating multiple adjustment forms:

. Go to *Orders » Fulfilment*.
. In the line *Generate credit notes / adjustment forms*, click on the small plus.
. Carry out the settings according to <<table-settings-fulfillment-adjustment-forms>>. +
_Note_ that the settings comprise *Search filters* as well as *Procedures*.
. Click on the gear-wheel (icon:cog[]) to generate the adjustment form. +
→ A PDF file containing the adjustment forms for the previously selected credit note orders opens.

[[table-settings-fulfillment-adjustment-forms]]
.Options in the *Generate credit notes / adjustment forms menu*
[cols="1,3"]
|====
|Setting |Explanation

2+^| *Search filter*

|*Document type*
|Select the *Adjustment form* document from the drop-down list.

| *Order status*
|Select the status of the credit note orders for which the adjustment forms should be generated from the drop-down list.

| *Owner*
|Select the owner of the orders from the drop-down list for which the adjustment forms should be generated or select *ALL* if adjustment forms should be generated for all owners.

| *Location*
|Select a location from the drop-down list for which the adjustment forms should be generated.

| *Warehouse*
|Select a warehouse from the drop-down list for which the adjustment forms should be generated. Alternatively, select the option *ALL*.

| *Payment method*
|Select a payment method from the drop-down list for which the adjustment forms should be generated. Alternatively, select the option *ALL*.

| *Sorting*
|Determine how the generated adjustment forms are sorted. The options *Credit note number*, *Order ID*, *Customer ID* and *Item ID* are available for different sorting methods.

| *Limit*
|Determine the maximum number of adjustment forms that should be generated at once. The maximum is *200*.

2+^| *Procedure*

| *Change order status*
|Choose an order status to which the orders are to be changed after the adjustment forms are created. +
The status change is an important tool to make sure that the process is not carried out twice for orders that have already been processed.

| *Comment*
|Optionally enter a comment that should be displayed on the adjustment forms below the order items.
|====
