= Credit notes
:keywords: credit note, generating credit notes, adjustment form, document, order document, document type, credit note document, document template
:author: team-docs-automation
:description: Learn how to set up a document template for credit notes, how to generate credit notes and how to send them to your customers.

In plentymarkets, you can generate credit notes as PDF files, for example if you want to print them or send them to your customers as an email attachment. +
Use credit notes to grant customers additional discounts for orders that have already been paid or if you want to refund customers for returned items.

[TIP]
.Default settings for credit notes
====
Carry out the default settings once in the menu Setup » Orders » Settings and save them before generating credit notes. This is required for the correct application of your desired default settings for the Standard status for credit notes and the inclusion of shipping costs in credit notes.  For further information on carrying out basic settings for orders, refer to the xref:orders:preparatory-settings.adoc#[basic settings].
====

[#200]
== Setting up a document template for credit notes

Before generating credit notes, you have to set up a document template. Go to *Setup » Client » [Select client] » Locations » [Select location] » Documents » Offer* to set up the template. +
Further information and instructions on setting up the document template are available on the xref:orders:order-documents-new.adoc#[Order documents] page of the manual.

[#300]
== Creating a single credit note

You can manually create a single credit note in the corresponding credit note order. For further information and instructions on generating credit note orders, refer to the xref:orders:order-type-credit-note.adoc#[Order type credit note] page of the manual.

[.instruction]
Creating a single credit note:

. Go to *Orders » Orders (Test phase)*. +
→ The order overview opens.
. Carry out the search (material:search[]) to display orders.
. Open the order of the type credit note for which you want to generate a credit note.
. Go to the *Documents* area.
. At the top left, click on *Create document* (material:add[]).
. Select the *Credit note* document from the drop-down list. +
→ The window *Create document: Credit note* opens.
. Enter a date that should be displayed on the credit note.
. Optionally enter a comment that should be displayed on the credit note.
. Click on *Create* (material:add[role=”green”]). +
→ The credit note is created and added to the *Documents* area.

*_Tip:_* The corresponding invoice is displayed in the *Reference* column.

[#400]
== Generating multiple credit notes

If you want to generate several credit notes at once, use the search filters in the *Orders » Fulfilment* menu to determine the orders for which credit notes should be generated. In addition, you can determine whether a status change should take place after the credit notes have been generated.

[.instruction]
Generating multiple credit notes:

. Go to *Orders » Fulfilment*.
. In the line *Generate credit notes / adjustment forms*, click on the small plus.
. Carry out the settings according to <<table-settings-fulfillment-credit-notes>>. +
_Note_ that the settings comprise *Search filters* as well as *Procedures*.
. Click on the gear-wheel (icon:cog[]) to generate the credit notes. +
→ A PDF file containing the credit notes for the previously selected orders opens.

[[table-settings-fulfillment-credit-notes]]
.Options in the *Create credit notes / adjustment forms* menu
[cols="1,3"]
|====
|Setting |Explanation

2+^| *Search filter*

| *Document type*
|Select the document type *Credit note* from the drop-down list.

| *Order status*
|Select the status of the orders from the drop-down list for which credit notes should be generated.

| *Owner*
|Select the owner of the orders from the drop-down list for which the credit notes should be generated or select *ALL* if credit notes should be generated for all owners.

| *Location*
|Select a location from the drop-down list for which the credit notes should be generated.

| *Warehouse*
|Select the warehouse from the drop-down list for which the credit notes should be generated or select *ALL* if credit notes should be generated for all warehouses.

| *Payment method*
|Select the payment method of the orders from the drop-down list for which the credit notes should be generated or select *ALL* if credit notes should be generated for all payment methods.

| *Sorting*
|Determine how the generated credit notes are sorted. The options *Credit note number*, *Order ID*, *Customer ID* and *Item ID* are available for different sorting methods.

| *Limit*
|Determine the maximum number of credit notes that should be generated at once. The maximum is *200*.

2+^| *Procedure*

| *Change order status*
|Choose an order status to which the orders should to be changed after the credit notes have been created. +
The status change is an important tool to make sure that the process is not carried out twice for orders that have already been processed.

| *Comment*
|Optionally enter a comment that should be displayed below the order items on all credit notes.
|====
