= Defining number ranges

:keywords: number range, documents, start value, prefix, delivery country, invoice country
:author: team-docs-automation
:description: Learn on this page how to set up and manage number ranges.

In order not to lose track of the multitude of documents and their numbers, the *Setup » Documents » Number ranges* menu provides settings for number ranges. Here, you can define number ranges for your documents and thus e.g. automate the assignment of unique invoice numbers. +
A number range can have a maximum of 5 digits and may contain numbers, letters and characters.

[#grant-user-rights]
== Assigning user rights

*Back end* type users xref:business-decisions:user-accounts-access.adoc#105[can only see certain areas and menus] in plentymarkets. This means they only have limited access to the system. If you want *back end* type users to work with number ranges, you have to grant them at least the following rights: +

* *Documents > Number ranges > Show*
* *Documents > Number ranges > Update*
* *Documents > Number ranges > Delete*
* in the menu visibilities section: *Setup > Documents > Number ranges*

[#configure-columns]
== Configuring columns in the overview

In the overview of the number ranges, you can configure the table columns according to your needs. When opening the menu for the first time, the default view of the table is shown. By clicking on *Configure columns* (material:settings[]) at the top right, the table with the available columns opens. Here, you can select the columns that you want to be displayed and also define the order in which they are shown. To do so, proceed as follows.

[.instruction]
Configuring columns in the overview:

. Go to *Setup » Documents » Number ranges*.
. At the top right, click on *Configure columns* (material:settings[]). +
→ The window *Configure columns* opens.
. Select (material:check_box[role=skyBlue]) the columns that should be displayed. Pay attention to the explanations given in <<table-columns-number-ranges>>.
. Move (material:drag_indicator[]) the columns via drag-and-drop to the desired position until they are displayed in the desired order.
. Add or remove columns according to your needs.
. Click on *Confirm*. +
→ The settings are saved.

[[table-columns-number-ranges]]
.Table columns for number ranges
[cols="1,3"]
|===
|Setting |Explanation

| *Selection*
|By using the selection box, you can select the number range in order to carry out actions such as editing or deleting the number range. +
This is a default column.

| *Active*
|Shows whether the number range is active (material:circle[role=green]) or inactive (material:circle[]). If a number range is active, it is automatically used for new documents of this type. Note that active number ranges cannot be edited or deleted. +
*_Tip:_* When searching for number ranges, you can sort the search results in ascending or descending order according to the type of activation. To do so, click on the arrow that appears next to the column title. +
This is a default column.

| *Name*
|Shows the name of the number range. +
*_Tip:_* When searching for number ranges, you can sort the search results in ascending or descending order according to the name. To do so, click on the arrow that appears next to the column title. +
This is a default column.

| *Document type*
|Shows the document type of the number range. +
This is a default column.

| *Prefix*
|Shows the prefix of the number range (e.g. *EN-INV*). +
This is a default column.

| *Last (de)activation*
|Shows the date on which the number range was last activated or deactivated. +
*_Tip:_* When searching for number ranges, you can sort the search results in ascending or descending order according to the date of the last (de)activation. To do so, click on the arrow that appears next to the column title. +
This is a default column.

| *Start value*
|Shows the start value of the number range. +
The start value is the number that should be used as first value. Note that a maximum of 9 characters is possible here. +
This does not necessarily have to be `1`. For example, if you already have numbered invoices in your system, you can start from the existing values and continue the numbering. If you want the number to consist of a certain amount of digits, enter the starting value with leading zeros (e.g. 00001). +
This is an optional column.

| *Location*
|Shows the location for which the number range is used. +
This is an optional column.

| *Referrer*
|Shows the referrer for which the number range is used. +
This is an optional column.

| *Invoice country*
|Shows the invoice country for which the number range is used. +
This is an optional column.

| *Delivery country*
|Shows the delivery country for which the number range is used. +
This is an optional column.

| *Number range ID*
|Shows the ID of the number range. +
This is an optional column.

| *Actions*
|Allows to *activate* (material:task[]) and *delete* (material:delete[]) the number ranges via the context menu (material:more_vert[]).

|===

[TIP]
.Adjust size of table columns
====
In the overview table of the number ranges, you can adjust the size of the columns according to your needs. To do so, move your mouse over the respective table column and use the blue lines in order to drag it to the desired width.
====

[#search-for-number-ranges]
== Searching for number ranges

Use one of the following methods to search for number ranges.

[.instruction]
Searching for number ranges:

. Go to *Setup » Documents » Number ranges*.
.. *_Option 1:_* Click on icon:search[role="darkGrey"] to see a list of all number ranges.
.. *_Option 2:_* Enter a number into the search field and click on one of the automatic suggestions.
Then click on icon:search[role="darkGrey"] to start the search.
.. *_Option 3:_* Click on icon:tune[set=material] to narrow down the search results with filters.

[#filter-for-number-ranges]
== Filtering for number ranges

With the help of filters you can narrow down the search and only search for specific number ranges. The following table lists all available filters.

[[filters-number-ranges]]
.Filters for number ranges
[cols="1,3"]
|===
|Filter |Explanation

| *Name*
|Enter a name to filter for number ranges with this name.

| *Document type*
|Select a document type from the drop-down list in order to filter for number ranges of this document type.

| *Referrer*
|Select one or several referrers from the drop-down list in order to filter for number ranges with these referrers.

| *Location*
|Select one or several locations from the drop-down list in order to filter for number ranges with these locations.

| *Invoice country*
|Select one or several invoice countries from the drop-down list in order to filter for number ranges with these invoice countries.

| *Delivery country*
|Select one or several delivery countries from the drop-down list in order to filter for number ranges with these delivery countries.

|===

[#create-number-ranges]
== Creating a new number range

In order to create new number ranges for your documents, proceed as follows.

[.instruction]
Creating a number range:

. Go to *Setup » Documents » Number ranges*. +
→ The overview of the number ranges opens.
. At the top, click on *Add new number range* (material:add[]). +
icon:map-signs[] *_Or:_* On the left in the side navigation, click on  *+ Add new number range*. +
→ The overview with the settings for the new number range opens.
. Carry out the settings. Pay attention to the explanations given in <<table-create-number-range>>.

[[table-create-number-range]]
.Creating a number range
[cols="1,3"]
|===
|Setting |Explanation

2+^| *Basic settings*

| *Name*
|Enter a name for the number range. +
This is a mandatory field.

| *Description*
|Optionally enter a description for the number range. The description can have up to 256 characters.

| *Document type*
|Select the document type from the drop-down list for which the number range should be used for. +
This is a mandatory field.

| *Location*
|Select one or several locations from the drop-down list for which the number range should be used. +
*_Note:_* Select a location in order to enable the referrer selection.

| *Referrer*
|Select one or several referrers from the drop-down list for which the number range should be used. +
*_Note:_* Select a referrer in order to enable the invoice country selection.

| *Invoice country*
|Select one or several invoice countries from the drop-down list for which the number range should be used. +
*_Note:_* Select an invoice country in order to enable the delivery country selection.

| *Delivery country*
|Select one or several delivery countries from the drop-down list for which the number range should be used.

2+^| *Settings*

| *Prefix*
|Enter a prefix that should be added in front of the number. By default, the prefix starts with the year (e.g. `2023-`). +
This is a mandatory field.

| *Digit count*
|Define the number of digits that should be used for the number range. You can select a digit count between 2 and 9. The default digit count is 5.

| *Start value*
|Enter a value from which the number range should start. The start value depends on the selected digit count for the number range. If you selected the digit count 3, the start value can be any number between 1 and 999.
The default start value is 1.

| *Preview with current settings*
|Displays the preview of the number range with the current settings.

| *Last generated number*
|On the right, click on *Last generated number* (material:refresh[]) in order to see the number that was generated last.

|===

[TIP]
.Asterisk shows unsaved changes
====
An asterisk on the left in the side navigation indicates unsaved changes. As soon as you saved your changes, the asterisk disappears.
====

[#deactivate-number-ranges]
== (De)activating number ranges

In order to activate or deactivate number ranges, proceed as follows. Note that active number ranges cannot be edited or deleted.

[.instruction]
Activating/deactivating number ranges:

. Go to *Setup » Documents » Number ranges*. +
→ The overview of the number ranges opens.
. Carry out the search (material:search[]) to display number ranges.
. Select (material:check_box[role=skyBlue]) the number range that you want to activate or deactivate.
. Click on the context menu (material:more_vert[]) on the right.
. Select the option *Activate number range* (material:task[]) or *Deactivate number range* (material:task[]).
. Confirm your decision. +
→ The number range is activated and will be used for new documents of this type or it is deactivated and will no longer be used for new documents. +
icon:map-signs[] *_Or:_* Click on the number range that you want to activate or deactivate. +
→ The settings of the number range open.
. Click on the toggle button at the top in order to activate (material:toggle_on[role=skyBlue]) or deactivate (material:toggle_off[role=skyBlue]) the number range.
. Confirm your decision. +
→ The number range is activated or deactivated.

[#delete-number-ranges]
== Deleting number ranges

In order to delete number ranges, proceed as follows. Note that active number ranges cannot be deleted.

[.instruction]
Deleting number ranges:

. Go to *Setup » Documents » Number ranges*. +
→ The overview of the number ranges opens.
. Carry out the search (material:search[]) to display number ranges.
. Select (material:check_box[role=skyBlue]) the number range that you want to delete.
. At the top in the toolbar, click on *Delete number range* (material:delete[]). +
icon:map-signs[] *_Or:_* In the line of the number range that you want to delete, click on the context menu (material:more_vert[]).
. Select the option *Delete number range* (material:delete[]).
. Confirm your decision. +
→ The number range is deleted.

[TIP]
.Using group functions
====
By using the group function *Open number ranges* (material:edit[]) or *Delete number ranges* (material:delete[]), you can open or delete all number ranges at once that you selected (material:check_box[role=skyBlue]) in the overview. Note however that active number ranges cannot be deleted.
====
