= Using default templates
:keywords: DocumentBuilder standard templates, default templates, standard template, delete default templates, deactivate default templates, activate default templates, using default templates,
:author: team-docs-automation
:description: This page explains the standard templates and how they are used.

////
TODO: Keywords ändern; description ergänzen; Seiten einkopieren
////


DocumentBuilder contains a range of preconfigured default templates. These are available for order confirmations and delivery notes as well as for documents required for tax compliance. The default templates are active by default and serve as *“fallbacks”*. This means that if no other template matches an order, the system will use the corresponding default template. 

*The default templates cannot be edited, deleted or individually deactivated/activated*. If you want to deactivate/activate the default templates collectively, use the toggle button in the DocumentBuilder overview. +
*_Note:_*If you collectively deactivate the default templates, they can no longer serve as fallbacks.


You can use default templates <<#use-standard-templates-directly, directly>> or xref:auftraege:documentbuilder-template-create.adoc#template-copy[copy them] and adapt the resulting copies to suit your needs.

DocumentBuilder contains default templates for the following document types: 

* Invoice
* Delivery note
* Dunning letter
* Adjustment form
* Order confirmation
* Reversal invoice
* Reversal credit note
* Reversal dunning letter

Each default template has four versions: German and English; gross and net.



[#using-default-templates-directly]
== Using default templates directly 

The default templates in DocumentBuilder are activated by default. The are also preconfigured, containing all mandatory input for the respective document type. To use them directly, you don’t need to do anything. 

*_Note:_*If you decide to use default templates directly, note that, in the system hierarchy, default templates are subordinate to your own custom templates. As soon as you activate a custom template that is configured to match the same order settings as a default template, the default template will no longer be used. 

[#Copying a default template]
== Copying a default template

The default templates in DocumentBuilder provide a  basis for creating new templates that you can then adapt to suit your needs.

To find out how to copy a template in DocumentBuilder, go to the manual page xref:orders:documentbuilder-create-template.adoc[Creating a new template].
where you will find detailed instructions on creating and copying templates, and on adjusting the different template settings.

