= Dunning letters
:keywords: dunning letter, generating dunning letters, order documents, order template, dunning charge, reversal dunning letter, dunning level, dunning fee, dunning surcharge
:author: team-docs-automation
:description: Learn how to set up a document template for dunning letters in order to create dunning letters and send them to your customers. You can use dunning letters to remind your customers of outstanding payments once the payment period has expired. Moreover, find out how to create a reversal dunning letter in order to cancel dunning letters.

In plentymarkets, you can generate dunning letters as PDF files, for example if you want to print them or send them to your customers as an email attachment. +
You can use dunning letters to remind your customers of outstanding payments after the payment period has expired. Dunning letters can only be created when an invoice already exists since these document types are interdependent. That is also why an invoice can only be reversed if already existing dunning letters are reversed first. Use the document type <<#400, reversal dunning letter>> for this. +
There are 4 dunning letter levels available. Thus, you can remind customers several times of the outstanding payments with a new dunning letter with distinct dunning charges for each level. To do so, set up dunning charges for each dunning level by creating corresponding variation IDs. After this you can enter the variation ID when you are creating the document, as described in <<table-orders-receipts-dunning-letter>>. +
These functions follow fiscal statutes and are in place to help you working according to GoBD (German taxation directive) regulations.

[#100]
== Setting up a document template for dunning letters

Before generating dunning letters, you have to set up a document template. Go to *Setup » Client » [Select client] » Locations » [Select location] » Documents » Dunning letter* to set up the template. +
Further information and instructions on setting up the document template are available on the xref:orders:order-documents-new.adoc#[Order documents] page of the manual.

[#200]
== Generating a single dunning letter

In plentymarkets, you can manually create a single dunning letter directly in the order.

[.instruction]
Generating a single dunning letter:

. Go to *Orders » Orders (Test phase). +
→ The order overview opens.
. Carry out the search (material:search[]) to display orders.
. Open the order for which you want to generate a dunning letter.
. Go to the *Documents* area.
. At the top left, click on *Create document* (material:add[]).
. Select the *Dunning letter* document from the drop-down list. +
→ The window *Create document: Dunning letter* opens.
. Carry out the settings. Pay attention to the explanations given in <<table-create-dunning-letter>>.
. Click on *Create* (icon:save[role="green"]). +
→ The dunning letter is created and added to the *Documents* area.

[[table-create-dunning-letter]]
.Settings for the dunning letter document
[cols="1,3"]
|===
|Setting |Explanation

| *Date*
|Enter a date that should be displayed on the dunning letter. The current date is preselected by default.

| *Variation ID for dunning charge*
|Adding a *Dunning charge* requires creating a corresponding item including an item price. This item is then included as a separate entry on the dunning letter and displays the dunning charge. After having created this item, enter the ID of the main variation into this field. This variation is automatically added to all generated dunning letters. +
For further information about creating items, refer to the xref:item:new-item.adoc#[Manually creating items] page of the manual.

| *Comment*
|Optionally enter a comment that should be displayed on the dunning letter below the order items.

|===

[#300]
== Generating multiple dunning letters

If you want to generate several dunning letters at once, use the search filters in the *Orders » Fulfilment* menu to determine the orders for which dunning letters should be generated. In addition, you can determine whether a status change should take place after the dunning letters have been generated.

[.instruction]
Generating multiple dunning letters:

. Go to *Orders » Fulfilment*.
. In the line *Generate dunning letters* click on the small plus.
. Carry out the settings according to <<table-settings-fulfilment-dunning-letters>>. +
_Note_ that the settings comprise *Search filters* as well as *Procedures*.
. Click on the gear-wheel (icon:cog[]) to generate the dunning letters. +
→ A PDF file containing the dunning letters for the previously selected orders opens.

[[table-settings-fulfilment-dunning-letters]]
.Options in the *Generate dunning letters* menu
[cols="1,3"]
|====
|Setting |Explanation

2+^| *Search filter*

| *Order date from / to*
|Limit the orders for which dunning letters should be generated by selecting a start and end date from the calendar. The orders from the chosen period of time are displayed.

| *Order status*
|Select the status of the orders from the drop-down list for which dunning letters should be generated.

| *Country*
|Select a country to which the search should be limited or select the option *ALL* if dunning letters should be generated for all countries.

| *Owner*
|Select the owner from the drop-down list for which the dunning letters should be generated or select *ALL* if dunning letters should be generated for all owners.

| *Location*
|Select a location from the drop-down list for which the dunning letters should be generated.

| *Warehouse*
|Select a warehouse from the drop-down list for which the dunning letters should be generated or select *ALL* if dunning letters should be generated for all warehouses.

| *Payment method*
|Select a payment method from the drop-down list for which the dunning letters should be generated or select *ALL* if dunning letters should be generated for all payment methods.

| *Sorting*
|Determine how the generated invoices should be sorted. The options *Order ID* and *Customer ID* are available for different sorting methods.

2+^| *Procedure*

| *Change order status*
|Choose an order status to which the orders should be changed after the dunning letters are created. +
The status change is an important tool to make sure that the process is not carried out twice for orders that have already been processed.

| *Variation ID*
|Adding a *Dunning charge* requires creating a corresponding item including an item price. This item is then included as a separate entry on the dunning letter and displays the dunning charge. After having created this item, enter the ID of the main variation into this field. This variation is automatically added to all generated dunning letters. +
For further information about creating items, refer to the xref:item:new-item.adoc#[Manually creating items] page of the manual.

| *Comment*
|Optionally enter a comment that should be displayed on the dunning letters below the order items.
|====

[#400]
== Creating reversal dunning letters

A *reversal dunning letter* is used to reverse a dunning letter. You need this for example when you need to reverse an invoice and a dunning letter already exists. In this case, the dunning letter has to be reversed before the invoice can be reversed as well.

As with other document types, you first need to set up a document template. Go to *Setup » Client » [Select client] » Locations » [Select location] » Documents » Reversal dunning letter* to set up the template. Further information and instructions on setting up the document template are available on the xref:orders:order-documents-new.adoc#[Order documents] page of the manual.

After setting up the document template, reversal dunning letters can be created directly within an order. To do so, proceed as follows.

[.instruction]
Creating reversal dunning letters:

. Go to *Orders » Orders (Test phase)*. +
→ The order overview opens.
. Carry out the search (material:search[]) to display orders.
. Open the order for which you want to generate a *reversal dunning letter*.
. Go to the *Documents* area.
. At the top left, click on *Create document* (material:add[]).
. Select the *Reversal dunning letter* document from the drop-down list. +
→ The window *Create document: Reversal dunning letter* opens.
. Enter a date that should be displayed on the reversal dunning letter.
. Optionally enter a comment that should be displayed on the reversal dunning letter below the order items.
. Click on *Create* (icon:save[role="green"]). +
→ The dunning letter is created and added to the *Documents* area.
