= Entry certificates
:keywords: Entry certificate, order documents, document, document template, accounting, document type
:author: team-docs-automation
:description: An entry certificate confirms the receipt of items in other EU countries. Learn on this page how to generate entry certificates as a PDF file, how to print it and how to send it to your customers via email.

In plentymarkets, you can generate entry certificates as PDF files, for example if you want to print them or send them to your customers as an email attachment. +
An entry certificate is required for deliveries from Germany to another EU country. Recipients confirm the receipt of the incoming items in the respective EU country e.g. by signing the entry certificate and sending it back to the sender. +
Thus, an entry certificate is not only a document that accompanies export deliveries, but may also be a receipt relevant for taxes and accounting.

[#100]
== Setting up a document template for entry certificates

Before generating entry certificates, you have to set up a document template. To do so, go to *Setup » Client » [select client] » Locations » [select location] » Documents » Entry certificate*. +
Further information and instructions on setting up the document template are available on the xref:orders:order-documents-new.adoc#[Order documents] page of the manual.

[#200]
== Creating a single entry certificate

In plentymarkets, you can manually create a single entry certificate directly in the order.

[.instruction]
Creating a single entry certificate:

. Go to *Orders » Orders (Test phase)*. +
→ The order overview opens.
. Carry out the search (material:search[]) to display orders.
. Open the order for which you want to generate an entry certificate. Note that orders can only be opened in the list view.
. Go to the *Documents* area.
. At the top left, click on *Create document* (material:add[]).
. Select the document *Entry certificate* from the drop-down list. +
→ The window *Create document: Entry certificate* opens.
. Enter a date that should be displayed on the entry certificate.
. Optionally enter a comment that should be displayed on the entry certificate.
. Click on *Create* (material:add[role=green]). +
→ The entry certificate is created and added to the *Documents* area.

[#300]
== Generating several entry certificates

If you want to generate several entry certificates at once, use the search filters in the *Orders » Fulfilment* menu to determine the orders for which entry certificates should be generated.  In addition, you can determine whether a status change should take place after the entry certificates have been generated.

[.instruction]
Generating several entry certificates:

. Go to *Orders » Fulfilment*.
. In the line *Generate entry certificate (Gelangensbestätigung)*, click on the small plus.
. Carry out the settings according to <<table-settings-fulfillment-entry-certificate>>. +
_Note_ that the settings comprise *Search filters* as well as *Procedures*.
. Click on the gear-wheel (icon:cog[]) to generate the entry certificates. +
→ A PDF file containing the entry certificates for the previously selected orders opens.

[[table-settings-fulfillment-entry-certificate]]
.Options in the *Generate entry certificate (Gelangensbestätigung)* menu
[cols="1,3"]
|====
|Setting |Explanation

2+^| *Search filter*

| *Order status*
|Select the status of the orders from the drop-down list for which entry certificates should be generated.

| *Owner*
|Select the owner of the orders from the drop-down list for which the entry certificates should be generated or select *ALL* if entry certificates should be generated for all owners.

| *Location*
|Select a location from the drop-down list for which the entry certificates should be generated.

| *Warehouse*
|Select a warehouse from the drop-down list for which the entry certificates should be generated or select *ALL* if entry certificates should be generated for all warehouses.

| *Payment method*
|Select the payment method of the orders from the drop-down list for which the entry certificates should be generated or select *ALL* if entry certificates should be generated for all owners.

| *Sorting*
|Determine how the generated entry certificates should be sorted. The options *Order ID*, *Customer ID* and *Item ID* are available for different sorting methods.

| *Limit*
|Determine the maximum number of entry certificates that should be generated at once. The maximum is *200*.

2+^| *Procedure*

| *Change order status*
|Choose an order status to which the orders are to be changed after the entry certificates are created. +
The status change is an important tool to make sure that the process is not carried out twice for orders that have already been processed.

| *Comment*
|Optionally enter a comment that should be displayed below the order items on all entry certificates.
|====
