= Pick-up delivery
:lang: en
include::{includedir}/_header.adoc[]
:position: 90
:url: orders/order-documents/generating-pick-up-delivery
:id: H3CIPCV
:keywords: pick-up delivery, pick-up/delivery note, delivery note, order documents, document template, document type, document
:author: team-order-payment

Goods are picked up? Use the document pick-up delivery, also called pick-up/delivery note, for this. You can generate this as a PDF file, for example to print it or to send it as an email attachment to your customers.

[#100]
== Setting up a document template for pick-up deliveries

Before generating the document pick-up delivery, you have to set up a document template. Go to *Setup » Client » [Select client] » Locations » [Select location] » Documents » Pick-up/Delivery note* to set up the template. +
Further information and instructions on setting up the document template are available on the <<orders/order-documents#, Order documents>> page of the manual.

[#200]
== Generating a single pick-up delivery document

You can generate pick-up delivery documents manually for different order types. To do so, proceed as follows.

[.instruction]
Generating a single pick-up delivery document:

. Go to *Orders » Edit orders*. +
→ The *Order overview* opens.
. Use the filters to search (icon:search[role="blue"]) for the order for which you want to generate a pick-up delivery document.
. Open the required order.
. Go to the *Receipts* tab.
. Select the option *Pick-up delivery* from the *Create receipt* drop-down list. +
. Carry out the settings according to <<table-generate-pick-up-delivery-document>>.
. *Save* (icon:save[role="green"]) the settings to generate the pick-up delivery document. +
→ A *PDF file* of the just generated pick-up delivery document opens.

[[table-generate-pick-up-delivery-document]]
.Settings for pick-up delivery document in *Create receipt* menu
[cols="1,3"]
|====
|Setting |Explanation

| *Date*
|Enter a date to be displayed on the pick-up delivery document. The present date is set by default.

|*Number*
|The document number is assigned automatically. No entry is required in this field.

| *Book outgoing items*
|Select by choosing *YES* or *NO* whether outgoing items should be booked when the pick-up delivery document is generated.

| *Change order status to status*
|Choose an order status to which the order is changed after the pick-up delivery document is generated. If you don’t want the order status to change, select *No change* .

| *Comment*
|The text entered here is displayed below the order items. The entry of a text is optional.
|====
