= Return slips
:lang: en
include::{includedir}/_header.adoc[]
:position: 100
:url: orders/order-documents/generating-return-slips
:id: S938BDY
:keywords: return slip, generating return slips, order documents, document, document type, document template, return document
:author: team-order-payment

In plentymarkets, you can generate return slips as PDF files, for example if you want to print them or send them to your customers as an email attachment. +
This way, customers can enclose the return slips to their shipments when returning or exchanging items.

[#200]
== Setting up a document template for return slips

Before generating return slips, you have to set up a document template. This is done in the menu *Setup » Client » [Select client] » Locations » [Select location] » Documents » Return slip*. +
For further information and instructions on setting up the document template, refer to the <<orders/order-documents#, Order documents>> page of the manual.

[#300]
== Generating a single return slip

In some cases, it makes sense to manually generate return slip for particular orders. This is done in the order overview for original main orders and return orders alike.

In plentymarkets, you can manually generate a single return slip for an order. The generated return slip then lists all items contained in the order. Use this method to add a blank return slip to every order shipped to your customers. For further information about this method, refer to the *<<orders/managing-orders#450, Creating a return slip>>* chapter of the manual.

[.instruction]
Generating a single return slip:

. Go to *Orders » Edit orders*. +
→ The order overview opens.
. Use the filters to search (icon:search[role="blue"]) for the order for which you want to generate a return slip.
. Open the required order.
. Go to the *Receipts* tab.
. Select the document *Return slip* from the *Create receipt* drop-down list.
. Carry out the settings according to <<table-orders-receipts-return-slip>>. +
. *Save* (icon:save[role="green"]) the settings to generate the return slip. +
→ A *PDF file* containing the generated return slip opens.

[[table-orders-receipts-return-slip]]
.Settings for return slips in *Create receipt* menu
[cols="1,3"]
|====
|Setting |Explanation

| *Date*
|Select the date that is displayed on the return slip. The present date is set by default.

| *Number*
|The document number is assigned automatically. No entry is required in this field.

| *Change order status to status*
|Choose an order status to which the repair order is to be changed after the return slip is created. Choose the option *No change* if a status change is not desired.

| *Comment*
|Enter a text that is displayed below the item list on the return slip. This step is optional.
|====

[#600]
== Generating multiple return slips

If you wish to generate return slips for multiple orders at a time, use the search filter in the *Orders » Fulfilment* menu to determine the orders for which return slips should be generated. In addition, a status change can take place for the order after the return slips have been generated.

[.instruction]
Generating multiple return slips:

. Go to *Orders » Fulfilment » Generate return slips*.
. Carry out the settings according to <<table-settings-fulfillment-return-slip>>. +
_Note_ that the settings comprise *Search filters* as well as *Procedures*.
. Click on the *gear-wheel* (icon:cog[]) to generate the return slips. +
→ A *PDF file* containing the return slips for the previously selected orders opens.

[[table-settings-fulfillment-return-slip]]
.Options in the *Generate return slips* menu
[cols="1,3"]
|====
|Setting |Explanation

| *Order status*
|Select the status of the orders from the dropdown-list for which return slips should be generated.

| *Owner*
|Select the owner of the orders from the dropdown-list for which the return slips should be generated. Select *ALL* if return slips should be generated for all owners.

| *Location*
|Select a location from the dropdown-list for which the return slips should be generated.

| *Warehouse*
|From the dropdown-list, select one of the warehouses or select the option ALL.

| *Payment method*
|From the dropdown-list, select a payment method or select the option *ALL*.

| *Sorting*
|Determine how the generated return slips should be sorted. The options *Order ID*, *Customer ID* and *Item ID* are available for different sorting methods.

| *Limit*
|Determine the maximum number of return slips generated at a time. There is a maximum of *200*.

| *Change order status*
|Choose an order status to which the orders are to be changed after the return slips are generated. +
The status change is an important tool to make sure that the process is not carried out twice for orders that have already been handled.

| *Comment*
|Enter a text that is displayed below the item list on all return slips. This step is optional.
|====
