= Credit notes
:lang: en
include::{includedir}/_header.adoc[]
:position: 40
:url: orders/order-documents/generating-credit-notes
:id: GHUUQJS
:keywords: credit note, generating credit notes, adjustment form, document, order document, document type, credit note document, document template
:author: team-order-payment

In plentymarkets, you can generate credit notes as PDF files, for example if you want to print them or send them to your customers as an email attachment. +
Use credit notes to grant customers additional discounts for orders that have already been paid or if you want to refund customers for returned items.

[TIP]
.Default settings for credit notes
====
Carry out the desired default settings once in the menu *Setup » Orders »Settings* and save them before generating credit notes. This is required for the correct application of your desired default settings for the *Standard status for credit notes* and the inclusion of shipping costs in credit notes. For further information on carrying out standard settings for orders, refer to the <<orders/basic-settings#, Basic settings>> page of the manual.
====

[#200]
== Setting up a document template for credit notes

Before generating credit notes, you have to set up a document template. This is done in the menu *Setup » Client » [Select client] » Locations » [Select location] » Documents » Credit note*. +
For further information and instructions on setting up the document template, refer to the <<orders/order-documents#, Order documents>> page of the manual.

[#300]
== Generating a single credit note

You can manually generate a single credit note in the corresponding credit note order, if necessary. For further information and instructions on generating credit note orders, refer to the <<orders/managing-orders#530, Generating a credit note>> chapter of the manual.

[.instruction]
Generating a single credit note:

. Go to *Orders » Edit orders*. +
→ The *order overview* opens.
. Use the filters to search (icon:search[role="blue"]) for the credit note order for which you want to generate a credit note.
. Open the required order.
. Go to the *Receipts* tab.
. Select the document *Credit note* from the *Create receipt* drop-down list. +
. Carry out the settings according to <<table-credit-note-order-receipts-credit-note>>.
. *Save* the settings to generate the credit note. +
→ A *PDF file* containing the generated credit note opens.

Created credit notes show a reference to the invoice of the corresponding order. In the *Dcouments* tab of an order, this is shown in the naming of the credit note.

[[table-credit-note-order-receipts-credit-note]]
.Settings for credit notes in *Create receipt* menu
[cols="1,3"]
|====
|Setting |Explanation

| *Date*
|Enter a date to be displayed on the credit note. The present date is set by default.

| *Number*
|The document number is assigned automatically. No entry is required in this field.

| *Change order status to status*
|Choose an order status to which the order is to be changed after the credit note is generated. If you don’t want the order status to change, select *No change* .

| *Comment*
|Enter a text that is displayed below the order item on the credit note. This step is optional.
|====

[#400]
== Generating multiple credit notes

If you want to generate multiple credit notes at a time, use the search filter in the *Orders » Fulfilment* menu to determine the orders for which credit notes should be generated. In addition, you can determine whether a status change should take place after the credit notes have been generated.

[.instruction]
Generating multiple credit notes:

. Go to *Orders » Fulfilment » Create credit notes / adjustment forms*.
. Carry out the settings according to <<table-settings-fulfillment-credit-notes>>. +
_Note_ that the settings comprise *Search filters* as well as *Procedures*.
. Click on the *gear-wheel* (icon:cog[]) to generate the credit notes. +
→ A *PDF file* containing the credit notes for the previously selected orders opens.

[[table-settings-fulfillment-credit-notes]]
.Options in the *Create credit notes / adjustment forms* menu
[cols="1,3"]
|====
|Setting |Explanation

| *Document type*
|Select the document type *Credit note* from the dropdown-list.

| *Order status*
|Select the status of the orders for which credit notes are to be generated from the drop-down list.

| *Owner*
|Select the owner of  the orders from the drop-down list for which the credit notes are to be be generated. Select *ALL* if credit notes are to be generated for all owners.

| *Location*
|Select a location from the drop-down list for which the credit notes should be generated.

| *Warehouse*
|From the drop-down list, select one of the warehouses or select the option ALL.

| *Payment method*
|From the drop-down list, select a payment method or select the option *ALL*.

| *Sorting*
|Determine how the generated credit notes should be sorted. The options *Credit note number*, *Order ID*, *Customer ID* and *Item ID* are available for different sorting methods.

| *Limit*
|Determine the maximum number of credit notes generated at a time. The maximum is 200.

| *Change order status* (Procedure)
|hoose an order status to which the orders are to be changed after the credit notes are generated. +
The status change is an important tool to make sure that the process is not carried out twice for orders that have already been processed.

| *Comment*
|Enter a text that is later displayed below the order items on all credit notes. This step is optional.
|====
