= Adjustment form
:lang: en
include::{includedir}/_header.adoc[]
:position: 20
:url: orders/order-documents/generating-adjustment-forms
:id: U8ZHVGR
:keywords: adjustment form, generating adjustment form, creating adjustment form, order documents, document template, credit note order, document type, document
:author: team-order-payment

Use an adjustment form when you need to correct an order. Imagine, for example, a customer ordered three items but you can only send him two of those items. You tell the customer and since he already paid for the three items, he wants a refund. What do you do? You create an order of the type <<orders/managing-orders#500, credit note order>>. Only after doing this you can create an adjustment form in this credit note order. You can either create a single adjustment form or generate multiple ones. Generate PDF files to print them or to send them to your customers as an email attachment.

[#100]
== Setting up a document template for adjustment forms

Before generating adjustment forms, you have to set up a document template. Go to *Setup » Client » [Select client] » Locations » [Select location] » Documents » Adjustment form* to set up the template. +
Further information and instructions on setting up the document template are available on the <<orders/order-documents#, Order documents>> page of the manual.

[#200]
== Generating a single adjustment form

Adjustment forms can only be generated in the order type *Credit note order*. To generate a single adjustment form for a specific credit note order, proceed as follows.

[.instruction]
Generating a single adjustment form:

. Go to *Orders » Edit orders*. +
→ The order overview opens.
. Use the filters to search (icon:search[role="blue"]) for the credit note order for which you want to generate an adjustment form.
. Open the required order.
. Go to the *Receipts* tab.
. Select the document *Adjustment form* from the *Create receipt* drop-down list. +
. Carry out the settings according to <<table-creating-adjustment-form>>. +
. *Save* (icon:save[role="green"]) the settings to generate the adjustment form. +
→ A *PDF file* of the just generate adjustment form opens.

[[table-creating-adjustment-form]]
.Settings for adjustment forms in *Create receipt* menu
[cols="1,3"]
|====
|Setting |Explanation

| *Date*
|Enter a date to be displayed on the adjustment form. The present date is set by default.

| *Number*
|The document number is assigned automatically. No entry is required in this field.

| *Change order status to status*
|Choose an order status to which the credit note order is to be changed after the adjustment form is generated. If you don’t want the order status to change, select *No change* .

| *Comment*
|The text entered here is displayed below the order items. The entry of a text is optional.
|====

[#300]
== Generating multiple adjustment forms

If you want to generate several adjustment forms at once, use the search filters in the *Orders » Fulfilment* menu to determine the orders for which adjustment forms are to be generated. In addition, you can determine whether a status change should take place after the adjustment forms have been generated.

[.instruction]
Generating multiple adjustment forms:

. Go to *Orders » Fulfilment » Generate credit notes / adjustment forms.*
. Carry out the settings according to <<table-settings-fulfillment-adjustment-forms>>. +
_Note_ that the settings comprise *Search filters* as well as *Procedures*.
. Click on the gear-wheel (icon:cog[]) to generate the adjustment forms. +
→ A PDF file containing the adjustment forms for the previously selected orders opens.

[[table-settings-fulfillment-adjustment-forms]]
.Options in the *Generate credit notes / adjustment forms menu*
[cols="1,3"]
|====
|Setting |Explanation

|**Document type*
|Select *Adjustment forms* from the drop-down list.

| *Order status*
|Select the status of the credit note orders from the dropdown-list for which the adjustment forms are to be generated.

| *Owner*
|Select the owner of the orders from the drop-down list for which the adjustment forms are to be be generated. Select *ALL* if adjustment forms should be generated for all owners.

| *Location*
|Select a location from the drop down list for which the adjustment forms are to be generated.

| *Warehouse*
|From the drop-down list, select one of the warehouses or select the option ALL.

| *Payment method*
|From the drop down list, select a payment method or select the option *ALL*.

| *Sorting*
|Determine how the generated adjustment forms are sorted. The options *Order ID*, *Customer ID* and *Item ID* are available for different sorting methods.

| *Limit*
|Determine the maximum number of adjustment forms generated at once. The maximum is *200*.

| *Change order status* (Procedure)
|Choose an order status to which the credit note orders are to be changed after the adjustment forms are generated. +
The status change is an important tool to make sure that the process is not carried out twice for orders that have already been processed.

| *Comment*
|The text entered here is displayed below the order items. The entry of a text is optional.
|====
