= Offers
:page-aliases: generate-offer-document.adoc
:keywords: offer, offers, order document, document template, document, document type, offer document
:author: team-docs-automation
:description: Learn how you inform your customers about offers by using an offer document. As soon as you have set up a document template, you can generate offers as a PDF or send them as an email attachment.

You can create individual offers for your customers and send it to them. Use the document Offer which you can generate as a PDF file, for example if you want to print it or send it to your customers as an email attachment.

[#100]
== Setting up a document template for offers

Before generating the document *Offer*, you have to set up a document template. Go to *Setup » Client » [Select client] » Locations » [Select location] » Documents » Offer* to set up the template. +
Further information and instructions on setting up the document template are available on the xref:orders:order-documents-new.adoc#[Order documents] page of the manual.

[#200]
== Generating a single offer document

Offers are created individually for a customer. This is why the corresponding documents are directly linked with this order of the type *Offer*. This also means that the document can only be generated for the order type *Offer*. Therefore, if you want to generate a PDF file for an *offer*, for example, you have to create the order type offer first. You can generate the corresponding document as follows.

[.instruction]
Generating an offer (document) manually:

. Go to *Orders » Orders*. +
→ The order overview opens.
. Carry out the search (material:search[]) to display orders.
. Open the order of the type offer for which you want to generate an offer.
. Go to the *Documents* area.
. At the top left, click on *Create document* (material:add[]).
. Select the *Offer* document from the drop-down list. +
→ The window *Create document: Offer* opens.
. Enter a date that should be displayed on the offer.
. Enter an optional comment that should be displayed on the offer.
. Click on *Create* (material:add[role=green]). +
→ The offer is created and added to the *Documents* area.

[#300]
== Automating sending offer documents

You created individual offers for customers, generated the corresponding documents and want to send them to your customers now? You can automate the process of sending offer documents by setting up the appropriate event procedure. To send the document offer as an email attachment, we recommend the event procedure described in <<table-event-procedure-sending-offer-document>>. Proceed as described in the following to set up the event procedure.

:table-event-procedure: <<table-event-procedure-sending-offer-document>>
include:_includes:partial$event-procedure.adoc[]

[[table-event-procedure-sending-offer-document]]
.Setting up event action “Sending offer as PDF”
[cols="1,3,3"]
|====
|Setting |Option |Selection

| *Event*
| *Documents > Offer generated*
|

| *Filter*
| *Order > Order type*
| *Offer*

| *Action*
| *Customer > Send email*
|Click on *Add* (icon:plus-square[role="green"]) to select the corresponding email template for sending the offer to the customer (e.g. "Send offer as PDF").
|====

[TIP]
.You don’t see the corresponding email template?
====
You don’t see the corresponding email template for the event procedure “Send offer as PDF”? That’s probably because you haven’t created it yet. You can do this in the *Setup » Client » _Select client_ » Email » Templates* menu. Click on *New email template* (icon:plus-square[role="green"]) and create the template according to your requirements. The name you enter here for the email template is then displayed in the event procedures. For further information about setting up email templates, refer to the xref:crm:sending-emails.adoc#1200[Sending emails] page of the manual.
====
