= Invoices
:lang: en
include::{includedir}/_header.adoc[]
:position: 10
:url: orders/order-documents/generating-invoices
:id: I75PCMI
:keywords: invoice, generating invoices, order documents, document template, invoice date, billing, payment terms, invoice cancellation, document type, document, invoice data
:author: team-order-payment

In plentymarkets, you can generate invoices as PDf files, for example if you want to print them or send them to your customers as an email attachment. +
Depending on the country of delivery and the location of your business, invoices are subject to different legal requirements. Familiarise yourself with these requirements and make sure that all required invoice data is displayed on your invoice.

[#100]
== Setting up a document template for invoices

Before generating invoices, you have to set up a document template. Go to *Setup » Client » [Select client] » Locations » [Select location] » Documents » Invoice* to set up these documents. +
Further information and instructions on setting up the document template are available on the <<orders/order-documents#, Order documents>> page of the manual.

[TIP]
.Displaying Payment due and early payment discount on the invoice
====
In order for the payment terms (value date, payment due and early payment discount) to be displayed on invoices, they have to be activated when setting up the <<orders/order-documents#intable-payment-terms-documents, document template>> for invoices.
====

[#200]
== Generating a single invoice

In plentymarkets, you can manually generate a single invoice for an order in the *Edit orders* menu.

[.instruction]
Generating a single invoice:

. Go to *Orders » Edit orders*. +
→ The order overview opens.
. Use the filters to search (icon:search[role="blue"]) for the order for which you want to generate an invoice.
. Open the required order.
. Go to the *Receipts* tab.
. Select the document *Invoice* from the *Create receipt* drop-down list. +
. Carry out the settings according to <<table-orders-receipts-invoice>>. +
. *Save* (icon:save[role="green"]) the settings to generate the invoice. +
→ A *PDF file* of the just generated invoice opens.

[[table-orders-receipts-invoice]]
.Settings for invoices in Create receipt menu.
[cols="1,3"]
|====
|Setting |Explanation

| *Date*
|Enter a date to be displayed on the invoice. The present date is set by default.

| *Book outgoing items*
|Select by choosing *YES* or *NO* whether outgoing items should be booked when the invoice is created.

| *Change order status to status*
|Choose an order status to which the order is to be changed after the invoice is created. If you don’t want the order status to change, select *No change* .

| *Comment*
|The text entered here is displayed below the order items. The entry of a text is optional.
|====

[IMPORTANT]
.Locked orders
====
After an invoice is created, the corresponding order is automatically locked. This means that editing options are limited, for example no order items can be added any more. If required you can create a <<orders/managing-orders#1670, reversal document>> for the invoice.
====

[#300]
== Generating multiple invoices

If you want to generate several invoices at once, use the search filters in the *Orders » Fulfilment* menu to determine the orders for which invoices are to be generated. In addition, you can determine whether a status change should take place after the invoices have been generated.

[.instruction]
Generating multiple invoices:

. Go to *Orders » Fulfillment » Generate invoices*.
. Carry out the settings according to <<table-settings-fulfillment-invoices>>. +
_Note_ that the settings comprise *Search filters* as well as *Procedures*.
. Click on the gear-wheel (icon:cog[]) to generate the invoices. +
→ A PDF file containing the invoices for the previously selected orders opens.

[[table-settings-fulfillment-invoices]]
.Options for *Generating invoices*
[cols="1,3"]
|====
|Setting |Explanation

| *Order status*
|Select the status of the orders for which invoices are to be generated from the drop-down list. +
_Note_: If you search for orders with the status *Outgoing items booked* (status 7), all orders for which the outgoing items were booked today, on the current date, are filtered in the background. The hint *Outgoing items: TODAY* is displayed to clarify this.

| *Owner*
|Select the owner of the orders from the drop-down list for which the invoices are to be be generated. Select *ALL* if invoices are to be generated for all owners.

| *Location*
|Select a location from the drop-down list for which the invoices should be generated.

| *Warehouse*
|From the drop-down list, select one of the warehouses or select the option ALL.

| *Customer class*
|Select the customer class of the orders from the drop-down list for which the invoices are to be be generated. Select *ALL* if invoices are to be generated for all customer classes.

| *Payment method*
|From the drop down list, select a payment method or select the option *ALL*.

| *Sorting*
|Determine how the generated invoices are sorted. The options *Order ID*, *Customer ID* and *Item ID* are available for different sorting methods.

| *Limit*
|Determine the maximum number of invoices generated at once. The maximum is *200*.

| *Invoice date* (Procedure)
|Select a date from the calendar which is to appear as the invoice date on the invoices.

| *Change order status* (Procedure)
|Choose an order status to which the orders are to be changed after the invoices are created. +
The status change is an important tool to make sure that the process is not carried out twice for orders that have already been processed.
|====
