= Pro forma invoice
:lang: en
include::{includedir}/_header.adoc[]
:position: 120
:url: orders/order-documents/generating-pro-forma-invoice
:id: 82PZJ1F
:keywords: pro forma invoice, generate pro forma invoice, order documents, document template, document, document type, 
:author: team-order-payment

In plentymarkets, you can generate pro forma invoices as PDF files, for example if you want to print them or send them to your customers as an email attachment. Pro forma invoices are usually used as a preliminary invoice or as the basis for tax purposes, for example for customs when you import or export goods.

[#100]
== Setting up a document template for pro forma invoices

Before generating pro forma invoices, you have to set up a document template. Go to *Setup » Client » [Select client] » Locations » [Select location] » Documents » Pro forma invoice* to set up the template. +
Further information and instructions on setting up the document template are available on the <<orders/order-documents#, Order documents>> page of the manual.

[TIP]
.Displaying Payment due and early payment discount on the pro forma invoice
====
In order for the payment terms (value date, payment due and early payment discount) to be displayed on pro forma invoices, they have to be activated when setting up the <<orders/order-documents#intable-payment-terms-documents, document template>> for pro forma invoices.
====

[#200]
== Generating a single pro forma invoice

You can create pro forma invoices manually for different order types. The pro forma invoice is available for orders, offers, advance orders, repairs, warranties and for delivery orders. To do so, proceed as follows.

[.instruction]
Creating a pro forma invoices manually:

. Go to *Orders » Edit orders*. +
→ The *Order overview* opens.
. Use the filters to search (icon:search[role="blue"]) for the order for which you want to create a pro forma invoice.
. Open the required order.
. Go to the *Receipts* tab.
. Select the option *Pro forma invoice* from the *Create receipt* drop-down list.
. Carry out the settings according to <<table-generating-pro-forma-invoice>>.
. *Save* (icon:save[role="green"]) the settings to generate the pro forma invoice. +
→ A *PDF file* of the just generated pro forma invoice opens.

[[table-generating-pro-forma-invoice]]
.Settings for pro forma invoices in *Create receipt* menu.
[cols="1,3"]
|====
|Setting |Explanation

| *Date*
|Enter a date to be displayed on the pro forma invoice. The present date is set by default.

|*Number*
|The document number is assigned automatically. No entry is required in this field.

| *Value date/payment due/early payment discount* (old logic)
|_Attention_: This field is only displayed if you are using the old logic. The old logic will be switched off on 01.01.2020. Therefore, we recommend to switch to the new logic as soon as possible.
Select by choosing *YES* or *NO* whether value date, payment due or early payment discount are displayed on the pro forma invoice. +
*Note*: In order for these information to be displayed correctly on the pro forma invoice, they have to be deposited for the corresponding customer in the *Account* area in the *CRM » Contacts* menu.

| *Payment due date* (old logic)
|_Attention_: This field is only displayed if you are using the old logic. The old logic will be switched off on 01.01.2020. Therefore, we recommend to switch to the new logic as soon as possible.
If this information is not already deposited in the customer data, enter a number of days in this field to define the payment due date which is displayed on the pro forma invoice.

| *Early payment discount from X % if paid within X days* (old logic)
|_Attention_: This field is only displayed if you are using the old logic. The old logic will be switched off on 01.01.2020. Therefore, we recommend to switch to the new logic as soon as possible.
If this information is not already deposited in the customer data, enter a percentage and a number of days in these fields to define the early payment discount conditions.

| *Book outgoing items*
|Select by choosing *YES* or *NO* whether outgoing items should be booked when the pro forma invoice is generated.

| *Change order status to status*
|Choose an order status to which the order is to be changed after the pro forma invoice is generated. If you don’t want the order status to change, select *No change* .

| *Comment*
|The text entered here is displayed below the order items. The entry of a text is optional.
|====
