= Invoices
:keywords: invoice, generating invoices, order documents, document template, invoice date, billing, payment terms, invoice cancellation, document type, document, invoice data
:author: team-docs-automation
:description: Learn how to generate either single invoices or several invoices at once as PDF files and how you send them to your customers. Moreover, find out how to correct and cancel invoices.

In plentymarkets, you can generate invoices as PDF files, for example if you want to print them or send them to your customers as an email attachment. +
Depending on the country of delivery and the location of your business, invoices are subject to different legal requirements. Familiarise yourself with these requirements and make sure that all required invoice data is displayed on your invoice.

[#100]
== Setting up a document template for invoices

Before generating invoices, you have to set up a document template. Go to *Setup » Client » [Select client] » Locations » [Select location] » Documents » Invoice* to set up these documents. +
Further information and instructions on setting up the document template are available on the xref:orders:order-documents-new.adoc#[Order documents] page of the manual.

[TIP]
.Displaying Payment due and early payment discount on the invoice
====
In order for the payment terms (value date, payment due and early payment discount) to be displayed on invoices, they have to be activated when setting up the xref:orders:order-documents-new.adoc#intable-payment-terms-documents[document template] for invoices.
====

[#200]
== Creating a single invoice

In plentymarkets, you can manually create a single invoice for an order in the *Edit orders* menu.

[.instruction]
Creating a single invoice:

. Go to *Orders » Orders (Test phase)*. +
→ The order overview opens.
. Carry out the search (material:search[]) to display orders.
. Open the order for which you want to generate an invoice.
. Go to the *Documents* area.
. At the top left, click on *Create document* (material:add[]).
. Select the *Invoice* document from the drop-down list. +
→ The window *Create document: Invoice* opens.
. Enter a date that should be displayed as invoice date on the invoice.
. Optionally enter a comment that should be displayed on the invoice.
. Click on *Create* (material:add[role=green]). +
→ The invoice is created and added to the *Documents* area.

[IMPORTANT]
.Locked orders
====
After an invoice is created, the corresponding order is automatically locked. This means that editing options are limited, for example no order items can be added any more. If required you can create a xref:orders:invoice-new.adoc#400[reversal document] for the invoice.
====

[#300]
== Generating multiple invoices

If you want to generate several invoices at once, use the search filters in the *Orders » Fulfilment* menu to determine the orders for which invoices are to be generated. In addition, you can determine whether a status change should take place after the invoices have been generated.

[.instruction]
Generating multiple invoices:

. Go to *Orders » Fulfilment*.
. In the line *Generate invoices* click on the small plus.
. Carry out the settings according to <<table-settings-fulfillment-invoices>>. +
_Note_ that the settings comprise *Search filters* as well as *Procedures*.
. Click on the gear-wheel (icon:cog[]) to generate the invoices. +
→ A PDF file containing the invoices for the previously selected orders opens.

[[table-settings-fulfillment-invoices]]
.Options for generating invoices
[cols="1,3"]
|====
|Setting |Explanation

2+^| *Search filter*

| *Order status*
|Select the status of the orders for which invoices are to be generated from the drop-down list. +
_Note_: If you search for orders with the status *Outgoing items booked* (status 7), all orders for which the outgoing items were booked today, on the current date, are filtered in the background. The hint *Outgoing items: TODAY* is displayed to clarify this.

| *Owner*
|Select the owner of the orders from the drop-down list for which the invoices are to be generated. Select *ALL* if invoices are to be generated for all owners.

| *Location*
|Select a location from the drop-down list for which the invoices should be generated.

| *Warehouse*
|From the drop-down list, select one of the warehouses or select the option *ALL*.

| *Customer class*
|Select the customer class of the orders from the drop-down list for which the invoices are to be generated. Select *ALL* if invoices are to be generated for all customer classes.

| *Payment method*
|From the drop down list, select a payment method or select the option *ALL*.

| *Sorting*
|Determine how the generated invoices are sorted. The options *Order ID**, *Customer ID* and *Item ID* are available for different sorting methods.

| *Limit*
|Determine the maximum number of invoices generated at once. The maximum is *200*.

2+^| *Procedure*

| *Invoice date*
|Select a date from the calendar which is to appear as the invoice date on the invoices.

| *Change order status*
|Choose an order status to which the orders are to be changed after the invoices are created. +
The status change is an important tool to make sure that the process is not carried out twice for orders that have already been processed.
|====

[#400]
== Reversing and correcting an invoice

Create a reversal document if you or your customer notice an incorrect information on an invoice and you subsequently want to correct it. Create a new invoice after this.
Reversing an order makes it easy to see the changes, because you will have the old invoice, the reversal document for the invoice and a new invoice. Use the order status *cancelled* if you want to cancel the entire order. Use the reversal document if you want to edit the order and want to correct some of the information. +
Note that an invoice can only be reversed if no dunning letter exists for the corresponding order. In this case, the dunning letter has to be reversed first. To do so, use the xref:orders:dunning-letter-new.adoc#400[reversal dunning letter].

[#600]
=== Creating an invoice reversal document

You can correct an invoice by reversing it. The reversing of an invoice allows to see the changes once a new invoice is generated, but reversing an invoice will not cancel an order. Once the reversal document was generated, the order settings are unlocked and can be edited and a new invoice can be generated as well.

[.instruction]
Creating an invoice reversal document:

. Go to *Orders » Orders (Test phase)*.
. Carry out the search (material:search[]) to display orders.
. Open the order of which you want to reverse the invoice.
. Go to the *Documents* area.
. At the top left, click on *Create document* (material:add[]).
. Select the *Reversal invoice* document from the drop-down list. +
→ The window *Create document: Reversal invoice* opens.
. Enter a date that should be displayed as cancellation date.
. Optionally enter a comment that should be displayed on the reversal document.
. Click on *Create* (material:add[role=green]). +
→ The invoice is created and added to the *Documents* area.

[#700]
=== Creating a new invoice

Once you have created a reversal document for the invoice and adjusted the order accordingly, you can now create a new invoice.

[.instruction]
Creating a new invoice:

. Go to *Orders » Orders (Test phase)*. +
→ The order overview opens.
. Use the filters to search for the order for which you want to generate a new invoice.
. Open the required order.
. Go to the *Documents* area.
. At the top left, click on *Create document* (material:add[]).
. Select the *Invoice* document from the drop-down list. +
→ The window *Create document: Invoice* opens.
. Enter a date that should be displayed as invoice date on the new invoice.
. Optionally enter a comment that should be displayed on the new invoice.
. Click on *Create* (material:add[role=green]). +
→ The invoice is created and added to the *Documents* area.
