= Managing orders
:keywords: order, order, order, orders, orders, order ID, order processing, order, orders, order status, order types, delivery order, delivery orders, manual order creation, return, returns, credit note, credit notes, warranty, warranties, repair, repairs, multi-order, multi-orders, advance order, order search, order overview, edit orders, editing orders, generate order, create order, searching an order, order document, status, statuses, order item, order item list, incoming order, new order, status change, invoice, default status, return reason, item quantity, reversing stock, refund, credit note order, repair order, cancellation, order cancellation, correction, multi invoice, multi-invoice, multi credit note, outgoing items, delivery country, order confirmation, order history, status history, main order, order details, payment terms
:author: team-order-core
:description: Learn everything about managing orders and find out how to create orders and order documents and how to work with order types and order statuses. Note that this page describes the deprecated Order UI which will soon be replaced by the new Order UI.

Orders depict your sales and the business transactions connected to them. Those different business transactions are represented by order types. Progress during order processing is made visible by xref:orders:managing-orders.adoc#1200[order statuses]. The following descriptions will show you how to use order types and order status and thus process orders efficiently. All orders are registered in one central menu and in the same format. The xref:orders:managing-orders.adoc#1400[order overview] provides you with access to all important information and enables you to edit orders.

[#100]
== General information on creating orders in plentymarkets

In plentymarkets, an order is automatically created when customers place orders in your plentyShop or on one of your implemented markets. Separate orders with different order types are created for business transactions such as xref:orders:managing-orders.adoc#300[delivery orders], xref:orders:managing-orders.adoc#400[returns], xref:orders:managing-orders.adoc#500[credit notes], xref:orders:managing-orders.adoc#600[warranties] and xref:orders:managing-orders.adoc#700[repairs]. These orders are always linked to the main orders. The xref:orders:managing-orders.adoc#1400[order overview] allows you to open and edit orders regardless of the xref:orders:order-referrer.adoc#[referrer]. For many order types, such as xref:orders:managing-orders.adoc#300[delivery orders], it makes sense to set up xref:automation:event-procedures.adoc#[event procedures] that allow you to automate part of your order processing. You will find some examples for using event procedures during order processing in the following chapters. +
Orders that were not generated in the online shop or on a market can be created xref:orders:managing-orders.adoc#200[manually] in your system. This can be the required for orders via telephone, email or cash sales.

Before processing the first orders in your plentymarkets system, adjust the xref:orders:basic-settings.adoc#[basic settings] in the *Setup » Orders » Settings* menu. Save those settings once even if you have not changed the default values.

[#200]
== Creating orders manually

You can manually create orders directly in the plentymarkets system, e.g. when an order is telephoned in. There are several options available to manually create orders:

* Via a <<#create-order-via-cash-sale, cash sale>>
* Via <<#create-order-via-order, orders>>
* Via <<#create-order-via-contact, contacts>>

*_Tip:_* The approach for offers is identical. In the first step of the order creation, select the option *offer* in the *order type* setting to create an offer.

[NOTE]
.Order creation via new Order UI
======
As the order creation via the *Orders » Editing orders* menu is deprecated, this page explains how to create orders via the *Orders » Orders (Test phase)* menu.
======

[IMPORTANT]
.Sending emails
====
When you manually create orders, no emails will automatically be sent to the customer. The reason that no emails will be sent is that your system does not know when you are done with all settings for a manual order. Send xref:crm:emailbuilder.adoc#[emails] manually by using the *Email service* function in an order.
====

[#create-order-via-cash-sale]
=== Creating an order or an offer for a cash sale

When you open the *CRM » Contacts* menu you can register cash sales using the customer profile *Cash sale*. The customer profile named *Cash sale* allows you to assign orders without having to assign them to a customer. The customer profile *Cash sale* is set up in your system by default.

[WARNING]
.Payment method and order documents for cash sale
====
Make sure to select the correct *payment method* in the *order data* when creating an order for a cash sale. When manually creating a cash sale order the order will not be assigned to a customer saved in your system. This is why you should manually generate the required xref:orders:order-documents.adoc#[order documents] such as the invoice right away while entering and processing the cash sale. Order documents can be generated in the *Documents* tab of the order.
====

[.instruction]
Creating an order or an offer for a cash sale:

. Go to *CRM » Contacts*.
. Enter the desired ID in the *ID* search field. +
→ A list of all search results is displayed.
. Select *Cash sale* from the *results*. +
→ The customer profile for cash sale opens.
. Go to the *Orders* area.
. On the right, click on *Options* (material:add[]).
. Select the option *New order* or *New offer*. +
→ The overview for creating a new order or a new offer opens.
. Carry out the settings. Pay attention to the information about <<#create-order-or-offer, creating orders or offers>>.

[#create-order-via-order]
=== Creating an order or an offer via orders

In the *Orders » Orders (Test phase)* menu, you can create new orders or offers in the order overview as well as in the detail view of an order. To do so, proceed as follows.

[.instruction]
Creating an order or an offer via orders:

. Go to *Orders » Orders (Test phase)*.
. Carry out the search (material:search[]) to display orders.
. In the side navigation on the left, click on (material:add[role=skyBlue]) *New order*. +
*_Tip:_* If you want to create an offer instead of an order, select the *order type* *offer* in the first step. +
icon:map-signs[] *_Or:_* In the order overview, open the order of the customer for which you want to create a new order.
. Click on the *Contact ID* at the bottom of the page navigation. +
The order opens in the *CRM » Contacts* menu.
. Go to the *Orders* area.
. On the right, click on *Options* (material:add[]).
. Select the option *New order* or *New offer*. +
→ The overview for creating a new order or a new offer opens.
. Carry out the settings. Pay attention to the information about <<#create-order-or-offer, creating orders or offers>>.

[#create-order-via-contact]
=== Creating an order or an offer via contacts

You can also create orders or offers via the contact overview or the detail view of a contact in the *CRM » Contacts* menu. To do so, first carry out the <<#carrying-out-standard-settings, default settings>>.

[.instruction]
Creating an order or an offer via contacts:

. Go to *CRM » Contacts*.
. Search for the contact by means of the filter settings. Note the explanations about the filters on the xref:crm:search-contact.adoc#[Searching for a contact] page. +
→ The contacts that match the search criteria are displayed.
. On the right in the line of the contact, click on material:more_vert[].
. Navigate to material:shopping_cart[] *Orders* > *New order* or *New offer*. +
icon:map-signs[] *_Or:_* Open a contact.
. In the *Orders* section on the right, click on material:add[] *Options*.
. Navigate to *New order* or *New offer*. +
→ You are automatically redirected to the order details of the new order or offer.
. Carry out the settings. Pay attention to the information about <<#create-order-or-offer, creating orders or offers>>.

[#carrying-out-standard-settings]
==== Carrying out default settings

When creating orders or offers via the contact overview, data such as addresses or clients are taken directly from the contact data if they are deposited there. Thus, in most cases contact data have priority. Additionally, some default settings, which are a fallback if the data are not deposited in the contact, are available. +
In order to optimise the order creation, these default settings should be determined first. +
*_Note:_* The default settings also apply to offers that are created via the contact UI.

[.instruction]
Carrying out default settings:

. Go to *Setup » Orders » Order types » Sales order*.
. Carry out the settings. Pay attention to the explanations given in <<table-default-settings-order-contact>>.
. *Save* (material:save[role=green]) the settings.

[[table-default-settings-order-contact]]
.Default settings for the order creation
[cols="1,3"]
|===
|Setting |Explanation

|[#intable-default-owner]*Default owner*
|Select a default owner to be preselected in the order details when creating a new order or a new offer. The owner is not taken from the contact data.

|[#intable-default-client]*Default client*
|The default client selected here is preselected in the order details when creating an order or an offer if no client is set in the contact. If a client is set in the contact data, this client takes priority.

|[#intable-default-referrer]*Default referrer*
|The default referrer selected here is preselected in the order details when creating a new order or a new offer if no referrer is set in the contact. If a referrer is set in the contact data, this referrer takes priority.

|[#intable-default-warehouse]*Default warehouse*
|The default warehouse selected here is preselected in the order details when creating an order or an offer if no warehouse is set in the contact. If a warehouse is set in the contact data, it has priority.

|[#intable-default-template]*Default order template*
|If you select an <<#create-and-apply-order-templates, order template>> as the default order template, this template is preselected for the new order or offer by default. The values of the selected order template are automatically applied to the order or offer. You can only select order templates that have already been created. +
The option *No order template preselected* is set by default. If you select an order template as the default and this template is deleted at some point, the default setting returns to *None*.

|[#intable-endpoint-after-completion]*Endpoint after completing an order*
|Select the location in the system you want to be directed to after creating the order. You can choose between: +
*Current overview* = Forwards you to the order overview in the contact data record of the contact for which you created the order. This is the default setting. +
*Order overview* = Forwards you to the general order overview. +
*Detail view of the new order* = Forwards you to the detail view of the order you have just created.

|*Filter option ‘Only display items in stock’ is preselected in item search*
|Activate this option if you want it to be preselected in the item search. It means that only items with physical stock are displayed in the item search.

|*Filter option ‘Only display sales warehouses’ is preselected for the item search*
|Activate this option if you want it to be preselected in the item search. It means that only items stored in sales warehouses are displayed in the item search.

|*Filter option ‘Only display active items’ is preselected in item search*
|Activate this option if you want it to be preselected in the item search. It means that only xref:item:checklist-items-visibility.adoc#100[activated items] are displayed in the search results.

|*Filter option ‘Only display items with valid price’ is preselected in item search*
|Activate this option if you want it to be preselected in the item search. This means that only items for which a valid price is saved are displayed in the item search.

|*Allow changing the VAT rates in the items overview table in the last step of the order creation*
|By activating this option, you allow that VAT rates can be changed before finishing creating the order in the last step of the order creation. The VAT rates depend on the delivery address of the order. +
This option is deactivated by default. If you only want to display the VAT rates in the overview and not edit them, do not activate the toggle.

|*Display of added items in the shopping cart*
|Select how items are added to the shopping cart. The default setting is *As one order position, quantities of order items are increased*. +
*As separate order positions* = Identical items are added separately, meaning that each item is displayed in a separate row. +
*As one order position, quantities of order items are increased* = Identical items are added as one order item, only the quantities are changed accordingly.

|*Redetermine prices only in the shopping cart in the order creation*
|By activating this option, you determine that item prices are only recalculated when they are placed in the shopping cart. By default, prices are already determined during the item search when creating an item and can be selected there.

|===

[#create-order-or-offer]
=== Creating an order or an offer

No matter which of the described options you choose - the creation of a new order or offer is always carried out in three steps. In a first step, <<#step-one-basics, order details are entered>>, in the second step, <<#step-two-add-items, order items are added>> and in the third step, the <<#step-three-summary, order is completed>>. First of all, select the contact for which the order or offer is to be created.

Above the order details, you can also choose between an order or an offer afterwards. In addition, you can select an optional <<#create-and-apply-order-templates, order template>> from the drop-down list to apply the template to this order. By default, no order template is selected.

The steps described in the following chapters are the same for orders and offers.

The user interface is designed so that orders can be created quickly and easily. This is especially helpful when orders are telephoned in. First, the order details such as addresses and payment method are entered. After that, order items are added and the last step is the final check and completion of the order.

[TIP]
.Contact name, ID and rating at a glance
======
At the bottom left in the order creation's footer, you can see the name, the ID and the rating of the contact.
======

[#step-one-basics]
==== Step 1: Order details / Offer details

If the new order or the new offer is created from the contact overview, some information are transferred from the contact data to the order or offer details. Which information is transferred depends on the data saved in the contact. Otherwise, the <<#carrying-out-standard-settings, default settings>> apply. Also note <<#table-order-details-new-order, this table>>.

[[table-order-details-new-order]]
.General settings
[cols="1,3"]
|====
|Setting |Explanation

| *Order type*
|Select from the drop-down list whether you want to create an *order* or an *offer*.

| *Order template*
|Select a template from the drop-down list.

| *Contact*
|If you create the order from the *CRM » Contacts* meu, the name of the contact is already preselected. If you want to select another contact, enter at least 3 letters in order to see suggestions. Alternatively, you can also enter the contact’s email address. All data that is saved on the contact will be automatically added to the input fields. +
*_Tip:_* If you want to create a guest order, select the option *Guest* from the drop-down list and add a new *invoice address* as well as a new *delivery address*.

2+^| *Order details*

| *Invoice address*
|The invoice address is taken from the contact data. If there is more than one address, the one saved as the primary invoice address is taken. If no invoice address is saved as the primary address, you can select the right address from the drop-down list. +
Use the preview (material:visibility[]) to access the contact data record directly. The already carried out settings in the order details will remain. +
If you create a *guest order*, add a new invoice address.

| *Delivery address*
|If you select the option *As invoice*, the invoice address is automatically entered as the delivery address as well. Otherwise, the delivery address is taken from the contact data. If there is more than one delivery address, the one saved as the primary delivery address is taken. If no delivery address is saved as the primary address, you can select the right address from the drop-down list. +
The dropdown-list also offers the possibility to create a new delivery address which is then saved in the contact data. For further information, see the expandable box at the end of this section. +
Use the preview (material:visibility[]) to access the contact data record directly. The already carried out settings in the order details will remain. +
If you create a *guest order*, add a new delivery address.

| *Payment method*
|If a payment method is defined for the contact, for example in a xref:crm:preparatory-settings.adoc#create-customer-class[customer class], this is preselected. Otherwise you can enter a payment method and select it. All payment methods integrated in your plentymarkets system are available. +
If you use an <<#create-and-apply-order-templates, order template>>, the payment method selected in the template is taken over as soon as you select the template for an order. After applying the template, the payment method can be changed manually if required.

| *Currency*
|The xref:payment:currencies.adoc#30[system currency] is preselected. You can change the currency for the order in the drop-down list.

| *Discount in %*
|You can manually enter a percentage discount which is then applied to all order items of the order. The value entered has to be between 0 and 100, negative values are not allowed. +
A discount is already filled in if the contact is assigned to a customer class in which a value has been entered for the option *Default discount for manual order*. You can find this option in the xref:crm:preparatory-settings.adoc#intable-customer-class-discount-type[Discount type] area in the *Setup » CRM » Classes* menu. You can adjust the prefilled value in the order details.

| *Warehouse*
|Which options are available depends on the settings you set for xref:orders:preparatory-settings.adoc#intable-warehouse-assignment[assignment of warehouses]: +
- Is *a) a warehouse can be assigned for each order* set, you can select a warehouse for the order in the order details or enter the name of a warehouse to search for it. +
If you selected a default warehouse in the *Setup » Orders » Order types » Sales order [Beta]* menu, this warehouse will be preselected.
- Is *b) a warehouse can be assigned for each order item* set, *Depending on the order items* is displayed. In the next step, items are added to the order. This means that you can select a warehouse for each variation from the drop-down list. +
If you selected a default warehouse in the *Setup » Orders » Order types » Sales order [Beta]* menu, this warehouse will be preselected in the item table of the next step.

| *Client*
|Select the client for this order from the drop-down list. Preselected is either the client set in the contact data or as a next option the <<#intable-default-client, default client>> if it is set.

| *Owner*
|Select the owner for this order from the drop-down list. If you set a <<#intable-default-owner, default owner>>, it is preselected. Otherwise, owners with the user rights to create orders can be selected from the drop-down list.

| *Order referrer*
|Select the referrer for this order from the drop-down list. Preselected is either the referrer set in the contact data or as a next option the <<#intable-default-referrer, default referrer>> if it is set. Otherwise the activated xref:orders:order-referrer.adoc#[referrers] can be selected from the drop-down list.

| *Early payment discount (%)*
|Enter the early payment discount, i.e. the value in percent that is subtracted if the payment is made within the defined early payment discount days. +
This setting is only available for the payment methods *Invoice* and *Cash in advance*.

| *Early payment (days)*
|Enter the early payment days, i.e. the number of days starting when the invoice is created. The pending amount can be paid at a discounted price during this time period. +
This setting is only available for the payment methods *Invoice* and *Cash in advance*.

| *Value date (days)*
|Enter the value date, i.e. the period from the invoice creation up to the payment due date. +
This setting is only available for the payment methods *Invoice* and *Cash in advance*.

| *Payment due (days)*
|Enter the payment due date in days, i.e. the days until the payment is due. +
This setting is only available for the payment methods *Invoice* and *Cash in advance*.

|====

[.collapseBox]
.*Creating a new delivery address*
--

You can create a new delivery address from the dropdown-list in the field *Delivery address*. Proceed as described below to create a new delivery address. +
*_Tip:_* The settings for creating a new invoice address are identical.

[.instruction]
Creating a new delivery address:

. Select the option (material:add[]) *Add new delivery address* from the dropdown-list *Delivery address*. +
→ The *Add new delivery address* window opens.
. Select if it is a *primary* address.
. Enter the data. Note <<#table-new-delivery-address>>.
. *Save* the new address.

After saving the new delivery address it will be added to the contact data of the corresponding contact. The new delivery address is selected for the new order.

[[table-new-delivery-address]]
.Order details: Creating a new delivery address
[cols="1,3"]
|====
|Setting |Explanation

|*Primary*
|Activate the option if the new address is the primary delivery address. With the activation, this delivery address is automatically preselected for the creation of new orders.

|*Form of address*
|If required, select a form of address from the drop-down list.

|*Company (Name 1)*
|Enter the company name. If there is no entry for *First name* and *Last name*, this is a mandatory field.

|*First name (Name 2)*
|Enter the contact’s first name. If there is no entry for *Company* and *Last name*, this is a mandatory field.

|*Last name (Name 3)*
|Enter the contact’s last name. If there is no entry for *Company* and *First name*, this is a mandatory field.

|*Additional information (Name 4)*
|If required, enter additional information, e.g. _c/o Mr. John Doe_.

|*Address 1 (Street)* +
*Address 2 (House number)*
|Enter the street and house number. +
*Street* is a mandatory field if there is no entry for *House number* and *Additional address information*. *House number* is a mandatory field if there is no entry for *Street* and *Additional address information*.

|*Address 3 (Additional address information)*
|If required, enter additional address information, e.g. _apartment 12a_. If there is no entry for *Street* and *House number*, this is a mandatory field.

|*Address 4 (Free)*
|This field can be freely used.

|*Postcode* +
*Town*
|Enter the postcode, if available, and the town of the contact. *Town* is a mandatory field. +
The order of the options *Postcode* and *Town* is reversed for certain countries, e.g. Germany.

|*Country* +
*Region/County*
|Select the values from the drop-down list. +
*_Note:_* The drop-down list *Region/County* is not available for all countries.

|*Email*
|Optionally enter an email address.

|*Telephone*
|Optionally enter a telephone number.

|*Type* and *Value*
|Select a type from the drop-down list. The following types are available: VAT number, External address ID, Entry certificate, Post number, Personal ID, age rating, Birthday, Title, Contact person, External contact ID. Enter the corresponding *Value* for the selected type. +
Click on *Add address option* to add further *Types* and the corresponding *Values*.

|====

--

After you carried out all settings, go to the next step by clicking on *Add items*. Alternatively, you can click on the *Add items* step at the top. The order details are saved and you are redirected to the next step. In this step, you add items to the order.

[#step-two-add-items]
==== Step 2: Add items

Once you entered all order details in step 1, you can now add the desired items to the order. In this step, the order details are not displayed. They are available again in the third step where you finalise the order or the offer. *_Note_* however that only a few settings are editable in the last step.

[.collapseBox]
.*Customising the item table*
--

The item table can be customised according to your needs. This means that you can decide which information is displayed in the table columns and in which order they are shown. In order to adjust the table, proceed as follows.

[.instruction]
Customising the table:

. Click on *Configure columns* (material:settings[]). +
→ The window *Configure columns* opens.
. Select which columns you want to be displayed. Pay attention to the information given in <<table-overview-item-search>>.
. Move (material:drag_indicator[]) the columns so they are displayed in the desired order.
. Click on *Confirm* to save your settings.

When you have adapted the table once, these settings are saved. The table remains like this even when you finalised this order and create a new one. You can change the layout any time. A list of the available columns can be found in <<table-overview-item-search>>. There, it is also stated whether the column is a default column. Default columns are shown when tables are not customised.

[[table-overview-item-search]]
.Item table columns
[cols="1,3"]
|===
|Setting |Explanation

|*Stock status*
|In this column, a red status bar indicates that no net stock is available for an item. The red status bar is not displayed when the item is in stock. If you selected the option *Only display items in stock*, for example, none of the status bars are displayed in red at first. The status bar only turns red when stock units go below 0 while adding items to the shopping cart. +
This is a default column.

|*Status*
|This column shows whether the variation is set as active or inactive in the online shop. Information about activating or deactivating a variation can be found on the manual page xref:item:checklist-items-visibility.adoc#100[Have you activated the variation?]. +
This is a default column.

|*Item ID*
|Shows the ID of the item. You are redirected to the item data when clicking on the item ID. +
This is a default column.

|*Variation ID*
|Shows the variation ID. You are redirected to the variation data when clicking on the variation ID. +
This is a default column.

|*Item ID/Variation ID*
|This column displays the item ID and the variation ID next to each other and not in two separate columns. You are redirected to the item or variation data when you click on the item ID or the variation ID. +
This is a default column.

|*Variation number*
|Shows the variation number. You are redirected to the variation data when clicking on the variation number. +
This is an optional column.

|*Item name*
|Shows the name that is saved on the item. +
This is a default column.

|*Attributes*
|Shows the attributes that are saved on the item. +
This is a default column.

|*Variation name*
|Shows the variation name that is saved on the variation. +
This is a default column.

|*Barcode*
|Shows the barcode of the item. +
This is a default column.

| *System purchase price*
|Shows the system purchase price. +
This is a default column.

|[#intable-item-search-price-selection]*Price selection*
|All valid sales prices that are determined for this order are displayed in a drop-down list. You can select one of the displayed sales prices, which is then taken as the basis for the order calculation. If the price includes a discount, this is shown behind the price name and amount. The columns *Customer class discount* and *Category discount* show the percentage of the applied discount. +
In the <<#shopping-cart, shopping cart>>, you can manually adjust the price. If you select a different sales price than the one that was determined first, the sales price needs to be updated. To do so, click on *Refresh sales price* (material:refresh[]). After the update, the shopping cart button (material:add_shopping_cart[]) is available again and the items can be added to the shopping cart. This also applies to quantity changes. +
If no valid sales price could be detected, *No valid sales price* is displayed in the drop-down list. The order cannot be completed without a valid sales price. Therefore, add the item to the shopping cart and adapt the price manually in there. +
This is a default column.

| *Category discount*
|Shows the category discount in per cent as applied to the selected sales price. +
This is a default column.

| *Customer class discount*
|Shows the customer class discount in per cent as applied to the selected sales price. +
This is a default column.

| *Availability*
|Shows the availability of the item. +
This is a default column.

| *Net stock*
|Shows the net stock of the item. +
This is a default column.

| *Warehouse*
|Shows the warehouse of the item. Select another warehouse from the drop-down list if required or enter the name of a warehouse to search for it. Note that this is only possible if you selected the setting *b) A warehouse can be assigned for each order item* for the *assignment of warehouses*. +
If you selected a default warehouse in the *Setup » Orders » Order types » Sales order [Beta]* menu, this warehouse will be preselected. +
This is a default column.

|*Quantity*
|Enter the quantity to be added to the shopping cart. You can only enter whole numbers. Negative quantities or quantities which exceed the net stock are not allowed. If you enter such quantities, an error message is displayed.  If the quantity added sets the stock in the warehouse to 0 or lower, the row is displayed in red. +
If you change the quantity, the sales price changes as well and needs to be updated. To do so, click on *Refresh sales price* (material:refresh[]). After the update, the shopping cart button (material:add_shopping_cart[]) is available again and the items can be added to the shopping cart. +
This is a default column.

|*Cart icon*
|By clicking on the shopping cart (material:add_shopping_cart[]), the item is added to the shopping cart in the selected quantity. +
This is a default column.

|===

--

[#search-items]
===== Searching for items

By using the search (material:search[]), you can find the desired items and add them to the order. When you start a search, your search settings are displayed at the top as chips. You can save these search settings to apply them again more quickly and easily in the future. +
Use one of the following methods to search for items.

[.instruction]
Searching for items:

.. *_Option 1_*: Click on material:search[] to see a list of all items.
.. *_Option 2:_* Enter something into the search field and click on one of the automatic suggestions.
.. *_Option 3:_* Click on material:tune[] to narrow down the search results with filters.

Carry out the <<#search-items, search>> (material:search[]) to find and add the required items. You can also use the filters listed in the following table to narrow down the search results. Note that the <<#carrying-out-standard-settings, default settings>> are applied in the search.

[[table-order-filters]]
.Filters for order items
[cols="1,3"]
|===
|Filter |Explanation

| *Full text*
|Enter something into the input field to start a full text search.

| *Item ID*
|Enter an ID to filter for items with this ID.

| *Item name*
|Enter a name to filter for items with this name.

| *Variation no.*
|Enter a variation number to filter for items with this variation number. +
*_Tip:_* For this filter, a partial search is also possible. This means that you only need to enter the first characters of the variation number in order to search for it.

| *Variation ID*
|Enter a variation ID in order to filter for items with this variation ID.

| *Barcode*
|Enter a barcode to filter for items with this barcode.

| *Manufacturer*
|Enter a manufacturer to filter for items with this manufacturer.

| *Item tag*
|Enter a tag to filter for items with this tag.

| *Only display items in stock*
|Activate this option (material:done[role=skyBlue]) to filter only for items with physical stock.

| *Only display active items*
|Activate this option (material:done[role=skyBlue]) to filter only for activated items.

| *Only display sales warehouses*
|Activate this option (material:done[role=skyBlue]) to filter only for items that are stored in sales warehouses. +
*_Note:_* If you set *a) a warehouse can be assigned for each order* in the basic settings you can only select the option *Only display sales warehouses* for the search because the warehouse is already determined by the setting.

| *Only display items with valid price*
|Activate this option (material:done[role=skyBlue]) to filter only for items with a valid sales price.

|===

[#save-current-filter]
===== Saving the current filter

. Start a search.
. Click on *Saved filters* (material:bookmarks[role=darkGrey]).
. Click on material:bookmark_border[role=darkGrey] *Save current filter*.
. Enter a name and toggle the optional settings as needed (material:toggle_on[role=skyBlue]).
. Click on *Save*. +
→ The filter settings now appear under *Saved filters* (material:bookmark[role=darkGrey]).


[#use-saved-filters]
===== Applying saved filters

. Click on *Saved filters* (material:bookmarks[role=darkGrey]).
. Click on an existing filter setting. +
→ The search is started and the filter settings are displayed at the top as chips.

[#adding-items]
==== Adding items

Once you found all desired items by using the search or applying filters, you can now add them to the order. To do so, proceed as follows.

[.instruction]
Adding items:

. Search (material:search[]) for the desired item.
. Select the appropriate sales price from the *Price selection* drop-down list.
. Enter the quantity of the item you want to add to the order. If you adjust any prices or quantities, open the context menu (material:more_vert[]) on the right of the respective line and update the sales price by clicking on *Refresh sales prices* (material:refresh[]). +
*_Tip:_* On the top left of the table, you can update all changes for prices or quantities at once by clicking on *Refresh sales prices* (material:refresh[]).
. At the end of the respective line, click on *Add items to shopping cart* in order to add the item to the shopping cart.
. Repeat these steps to add further items.
. When all items are added, go to the next step by clicking on *Create order* or *Create offer*. +
→ The shopping cart is saved and you are forwarded to the last step.

[#shopping-cart]
==== Editing the shopping cart

In the shopping cart table, you can adjust the *item name*, the *quantity* and the *sales price*. As soon as these entries are changed, updates have to be carried out. You can do this by either clicking on *Refresh sales price* (material:refresh[]) in the context menu (material:more_vert[]) directly next to the item. Or you use the button *Refresh sales prices* at the top left in the shopping cart table. Only after updating the prices you can move on to the next step of the order creation.

The following applies to sales prices:

* If you manually enter a price, this price will remain in the drop-down list and can be selected for this order, even if you navigate back and forth or select a different sales price in between.
* If no valid sales price could be detected, a sales price has to be entered manually. Completing an order is only possible with valid sales prices.
* It is allowed to enter the price 0.00.
* If a sales price is entered that is lower than the purchase price, an error message is displayed. However, you can still enter a lower sales price if you want to.
* Carry out all changes for the order items in this step of the order creation, as this is not possible in the third and last step. Navigating back and forth through the steps remains possible.

Moreover, you can also delete order items in the shopping cart. To do so, click on *Delete* (material:delete[]). Another option for editing order items are the properties. To do so, pay attention to the chapter <<#edit-order-item-properties, Editing order item properties>>.

Once you added all the items in the required quantity and with the right prices to the shopping cart, click on *Create order* or *Create offer*. You can also go back to the order details by clicking on *Order details*. Items in the shopping cart are saved when you go back and forth.

[.collapseBox]
.*Customising the shopping cart table*
--
The shopping cart table is customisable. This means that you can decide which table columns are displayed in which order. When you have adapted the table, these settings are saved.

[.instruction]
Customising the table:

. Click on *Configure columns* (material:settings[]). +
→ The window *Configure columns* opens.
. Select which columns you want to be displayed.
. Move (material:drag_indicator[]) the columns so they are displayed in the order you need them in.
. Click on *Confirm* to save your settings.

[[table-shopping-cart]]
.Shopping cart table columns
[cols="1,3"]
|===
|Setting |Explanation

| *Expand*
|Allows you to expand the order items table and shows the properties.

| *Quantity*
|Shows the item quantity. If needed, adjust the quantity. +
This is a default column.

| *Item ID*
|Shows the item ID. You can open the item by clicking on the ID. +
This is a default column.

| *Variation ID*
|Shows the variation ID of this order item. You can open the variation by clicking on the ID. +
This is a default column.

| *Item ID* / *Variation ID*
|This column displays the item ID and the variation ID next to each other and not in two separate columns. You are redirected to the item or variation data when you click on the item ID or the variation ID. +
This is not a default column.

| *Variation no.*
|Shows the number of the variation. You are redirected to the variation data when clicking on the variation number. +
This is an optional column.

| *Item name*
|Shows the name that is saved on the item. You can edit (material:edit[]) the item name if needed. +
This is a default column.

| *Attributes*
|Shows the attributes. +
This is a default column.

| *Variation name*
|Shows the name of the variation. +
This is a default column.

| *Barcode*
|Shows the barcode of the item. +
This is not a default column.

| *System purchase price*
|Shows the system purchase price. +
This is not a default column.

| *Price selection*
|Shows the price selection. If needed, select another price selection from the drop-down list. +
This is a default column.

| *Category discount*
|Shows the category discount in per cent as applied to the selected sales price. +
This is not a default column.

| *Customer class discount*
|Shows the customer class discount in per cent as applied to the selected sales price. +
This is not a default column.

| *Net price*
|Shows the net price of the item. If you applied a discount, this has already been deducted. The gross price will also be adjusted automatically. +
This is a default column.

| *Original net price*
|Shows the original net price of the item before a discount was applied. You can adjust (material:edit[]) the original net price if required. +
This is a default column.

| *Gross price*
|Shows the gross price of the item. If you applied a discount, this has already been deducted. The net price will also be adjusted automatically. +
This is a default column.

| *Original gross price*
|Shows the original gross price of the item before a discount was applied. You can adjust (material:edit[])
 the original gross price if required. +
 This is a default column.

| *Surcharge total*
|Shows the sum of the order item properties’ surcharges. +
This is not a default column.

| *Discount [%]*
|Shows the discount in percent that was entered in the order details in the first step of the order creation.
If you want to display the discount as amount, select the option *Amount* from the drop-down list. +
*_Note:_* The amount is displayed in the currency of the order. +
This is a default column.

|*Total amount (net)*
|Shows the total net amount of the item. +
This is a default column.

| *Total amount (gross)*
|Shows the total gross amount of the item. +
This is a default column.

| *Warehouse*
|Shows the warehouse of the item. Select another warehouse from the drop-down list, if required. Note that this is only possible if you selected the setting *b) A warehouse can be assigned for each order item* for the *assignment of warehouses*. +
This is a default column.

| *VAT (%)*
|The VAT is shown in %. 19.00 % are preset for the VAT. You can change the VAT rate in the drop-down list. +
This is a default column.

| *Weight [g]*
|Shows the item weight in grams. Edit the weight in the input field if needed. +
This is not a default column.

| *Length [mm]*
|Shows the length of the item in mm. Edit the length in the input field if needed. +
This is not a default column.

| *Width [mm]*
|Shows the width of the item in mm. Edit the width in the input field if needed. +
This is not a default column.

| *Actions*
|If this field is selected, the actions for editing (material:edit[]) and deleting (material:delete[]) the item are available.
|===

--

[#edit-order-item-properties]
==== Editing order item properties

You can edit the order item properties in the shopping cart. Any changes made here only apply to the order items of this order. The properties themselves stay as they are configured in the system. Only the properties that have already been created and configured in the system are available in the order creation. +
If you want to create and edit properties or are not yet familiar with the structure of properties, refer to the manual chapter xref:item:properties.adoc#500[Properties] first.

In order to link a property with an order item, the property has to be marked as *Order property* in the *Options* area of the property settings. Also set possible surcharges and VAT rates for the property in the xref:item:properties.adoc#property-options[Options] area. The values added here will be included in the order calculations. If a property is already linked with an order item, it will be displayed on the corresponding order item.

The properties are displayed in a second row of the table underneath the corresponding order item. Here, you can find information about the *Name*, *Value*, *Surcharge* and *VAT %* of the property. You can edit the *VAT %*, i.e. the saved VAT rate of the property, directly in the table if the property type allows for that. Moreover, you can *delete* (material:delete[]) order item properties in the table. Deleted properties are not included in this order and the calculations. +
To edit the properties or to add more already existing properties, click on *Edit properties* (material:edit[]) in the context menu (material:more_vert[]) on the right.

In the editing window, you will find the following information about an order item’s property:

* *Name* = The name of the property is displayed. A red asterisk marks the property as a required property. Whether a property is required is determined in the xref:item:properties.adoc#property-options[Options] area of the property settings. Select *Required* from the *Order options* drop-down list.
* *Value* = The value of the property is displayed. You can edit the value. Depending on the property type, you can either make a selection, edit the value, add a value or upload a file. The changes are only valid for this order.
* *Surcharge* = The surcharge of the property is displayed, if a surcharge is set for the property. You can edit the surcharge. The changes are only valid for this order.

There are also further editing options are available here. By clicking on *Delete* (material:delete[]), you remove the property from this order item. This property is then not included in the order and the order calculations. +
You can also add more already existing properties. Select a property from the drop-down list *Select property* and add it to the order item by clicking on *Add property* (material:add[]). +
Once you are done with all adaptations, click on *Save properties*. By clicking on *Cancel*, none of the changes are saved. he editing window is closed and you can edit the properties of other order items in the same way.

If you want to have the properties displayed on documents, you have to set this in the configurations of the property itself. Make sure that the following options are selected in the xref:item:properties.adoc#property-visibilities[Visibilities] area of each property:

* *Display on documents* from the *Display everywhere* drop-down list as well as
* the correct clients from the *Clients* drop-down list.

Where the properties are displayed on the document depends on each property and its configuration. Properties for which no VAT rate was set in the *Options* area of the configuration or for which the option *Display as additional costs* in the *Order property* drop-down list was selected are displayed underneath the totals. Other properties are displayed in the order item table.

When you are done with editing the order item properties and the shopping cart, the last step of the order creation follows. In this step, the order item properties are not displayed again. Thus, make sure that you carried out all relevant settings. Click on *Create order* or *Create offer*.

[#step-three-summary]
==== Step 3: Create order / Create offer

In the last step, the order or the offer is completed. Different amounts of the order or the offer are displayed in info boxes above the order details:

* Total amount (gross): Shows the calculated total gross amount of the order. The status bar is green when the order is a gross order. Otherwise the status bar is grey.
* Total amount (net): Shows the calculated total net amount of the order. The status bar is green when the order is a net order. Otherwise the status bar is grey.
* Total number of items: Shows the total number of order items of this order. The status bar is always grey.
* Coupon amount: Shows the granted discount from promotional coupons. The status bar is orange when a promotional coupon was used in this order. Otherwise the status bar is grey.
* Order discount: Shows the discount amount resulting from the discount granted in the first step of the order creation. The summed up discount amount of all the order items is calculated. The status bar is orange when a discount was set in the first step. Otherwise the status bar is grey.
* Open amount: Shows the open invoice amount the customer has to pay. The status bar is green when the amount is zero, i.e. if the customer has already paid the full invoice amount. Red means that the full invoice amount is still open. Orange means that the invoice amount is still partially open.

In the order details, you can adjust the *Payment method*, the *Shipping costs*, the *Shipping method* as well as the *Owner* if required. +

Moreover, you can enter one or more coupon codes in the *Coupon codes* field to redeem these with this order. The values of the coupons are set off against the order value. Coupons are not added as an order position in the shopping cart. Coupons cannot be redeemed for offers.  This means that the input field *Coupon codes* is only available for the order creation, but not for creating offers. For coupons, it is differentiated between the types *plentymarkets campaign* and *External campaign*. In order to redeem coupon codes proceed as follows.

[tabs]
====
Redeeming coupon codes of a plentymarkets campaign::
+
--
[.instruction]
Redeeming coupon codes of a plentymarkets campaign:

. In the field *coupon codes*, enter the code of a plentymarkets campaign.
. Then click on _Enter_ or outside the field. +
→ It is checked whether the coupon code is valid. If the coupon is redeemable, it is displayed in green with the coupon’s value. If a coupon code is however invalid, it is displayed in red with the info *Not redeemable*. +
*_Tip:_* A tooltip shows which kind of coupon it is.
. Enter additional coupon codes if required. +
icon:map-signs[] *_Or:_* On the right in the field *Coupon codes* click on *Add coupon code* (material:add[]). +
→ The window *Redeem coupon* opens.
. Select the campaign type *plentymarkets campaign* from the drop-down list.
. Enter the coupon code of the plentymarkets campaign.
. Click on *Redeem*. +
→ The coupon code is added and will be redeemed with this order.
--

Redeeming coupon codes of an external campaign::
+
--

[.instruction]
Redeeming coupon codes of an external campaign:

. On the right in the field *Coupon codes* click on *Add coupon code* (material:add[]). +
→ The window *Redeem coupon* opens.
. Carry out the settings. Pay attention to the information given in <<table-redeem-coupon-codes>>.
. Click on *Redeem*. +
→ The coupon code is added in blue together with the coupon’s value and will be redeemed with this order.

[[table-redeem-coupon-codes]]
.Redeeming coupon codes
[cols="1,3"]
|===
|*Setting* |*Explanation*

| *Campaign type*
|Select the type *External campaign* from the drop-down list.

| *Code*
|Enter a coupon code.

| *Type*
|Select whether it is a *Promotional coupon* or a *Multipurpose coupon*.

| *Value in €*
|Enter the coupon’s value in the respective currency.

|===
--
====

Below the order details, a table with the added order items is displayed. In addition to the information given in the previous view, further prices and the VAT rate are shown. The VAT rates are editable if you allowed this in the <<#carrying-out-standard-settings, default settings>>.

[.collapseBox]
.*Customising the table*
--

The table in the last step of the order create is customisable. This means that you can decide which table columns are displayed in which order. When you have adapted the table, these settings are saved.

[.instruction]
Customising the table:

. Click on *Configure columns* (material:settings[]). +
→ The window *Configure columns* opens.
. Select which columns you want to be displayed.
. Move (material:drag_indicator[]) the columns so they are displayed in the order you need them in.
. Click on *Confirm* to save your settings.

The following columns are available: .

* Expand
* Quantity
* Item ID
* Variation no.
* Variation name
* Variation ID
* Item name
* Attributes
* Net price
* Original net price
* Gross price
* Discount
* Surcharge total
* Total amount (net)
* Total amount (gross)
* Warehouse
* VAT
* External item ID
* External order item ID
* Property ID
* Storage locations
* Net profit margin
* Reorder ID

--

If you carry out changes on the shipping costs or the shipping method or in case you add coupons, the total amounts are automatically recalculated. To complete the order, click on material:save[role=green]*Create order*. The order has now been created and depending on your settings, you are forwarded to the respective view. The order is now available in the order overview of the *Orders » Orders (Test phase)* menu.


[#create-and-apply-order-templates]
=== Creating and applying order templates

Order templates are created in the *Setup » Orders » Order template* menu. You can select them when you manually create a new order or you can apply an order template via an xref:automation:event-procedures.adoc#intable-order-template[event procedure]. If you select an order template for an order, the order template data is applied to the order. After using an order template, you can edit an order as usual as well as change and adapt order information.

To create an order template proceed as follows:

[.instruction]
Creating an order template:

. Go to the *Setup » Orders » Order template* menu.
. Click on the *New template* tab.
. Enter a unique *Name*.
. Select a *Payment method* and an *Order status* from the corresponding drop-down list.
. Optionally add items by clicking on *Add item*.
. Save (material:save[role=green]) the order template.

[[table-order-templates]]
.Order template fields
[cols="1,3"]
|===
|Setting |Explanation

| *Name*
|Enter a name for the order template. This name is displayed in drop-down lists for selecting the order template.

| *Payment method*
|Select a payment method from the drop-down list. When applying the order template to an order, this payment method is added to the order.

| *Order status*
|Select an order status from the drop-down list. When applying the order template to an order, the order is moved to this order status.

| *Item*
|If you already added items to the order template, they are displayed in this table. Adding items is optional. The items that are displayed here will be added to the order when using this order template. The quantity and the item text are displayed for each item. Moreover, you can delete items from the order template in this table. +
*_Note:_* When you apply an order template with items, the order you want to apply it to should not have any items added yet. Items that have already been added to the order are overwritten. However, you can add more items to an order after applying the order template.

| *Adding items*
|Optionally, you can add items to the order template in this tab. These items are added to the order when the order template is applied. +
Set filters and execute a search (material:serach[role=skyBlue]) to display items. Add (material:add_shopping_cart[role=green]) the desired items to the order template. The added items are displayed in the *Item* tab. +
*Quantity* = You can add an item more than once. Each item is displayed in a new table row. Alternatively, you can adapt the *Quantity* column of an item in the *Item* tab of the table.

|===

You can edit and adapt order templates at any time. After editing an order template, you have to save (material:save[role=green]) the order template again. Adaptations to order templates are not retroactively applied to orders but are valid from the moment of adaptation on.

Order templates are only applied to orders if you decide so. If you always want to apply an order template to specific orders, we recommend using an xref:automation:event-procedures.adoc#intable-order-template[event procedure]. Determine in the event procedure by the selection of the event and the filters, when and to which orders which order template should be applied.

To apply an order template when manually creating an order, select the required order template from the drop-down list *Use template* in the *Order data* area. In the order creation, you can select an order template in the first step of the order creation from the *Order template* drop-down list.

[#300]
== Working with delivery orders

*Delivery orders* enable you to create multiple delivery orders for the items included in the main order. This way, items from the main order can be shipped individually or in parts. Thus, delivery orders allow you to immediately ship items that are in stock and ship unavailable items later. Delivery orders can be shipped using one or several shipping providers. +
You can create delivery orders *manually*, *automatically* or using an *event procedure*.

[WARNING]
.Transfer all order items to delivery orders
====
When you create delivery orders from a main order, make sure to transfer _all_ order items into delivery orders. If you do not and leave order items on the main order, stock and warehouse errors will occur.
====

[#310]
=== Characteristics of delivery orders

In general, delivery orders have the following characteristics:

* It is *not* possible to modify the order items included in a delivery order after the delivery order has been created.
* The *price* and *weight* of an order are taken from the main order.
* The order language os taken from the main order.
* *Address label*, *delivery note*, *pro forma invoice* and *entry certificate (Gelangensbestätigung)* can be created in the *Receipts* tab of the respective order.
* The *invoice* and all other documents are created centrally in the main order.
* When creating a delivery order, the stock reservation for the quantity included in the delivery order is transferred from the main order to the delivery order.

[IMPORTANT]
.Same order status
====
The status of the main order is always identical to the status of the delivery order with the lowest status. For example, if a main order with the status *5.0* has two delivery orders, of which one changes to status *6.5*, the status of the main order is not changed to *6.5* until the second delivery order has also moved to status 6.5.
====

[#320]
=== Carrying out basic settings for delivery orders

[WARNING]
.Assigning a warehouse for each order item
====
To use delivery orders, you have to select the option *b) a warehouse can be assigned for each order item* for the xref:orders:basic-settings.adoc#intable-warehouse-assignment[Assignment of warehouses] in the menu *Setup » Orders » Settings*.
====

Before working with delivery orders, go to *Setup »Orders »Order types » Delivery order* to select an option for splitting up main orders into delivery orders.

[.instruction]
Selecting an option for splitting up orders into delivery orders:

. Go to *Setup » Orders » Order types » Delivery order*.
. Carry out the settings according to <<table-order-types-delivery-order-options>>.
. Save (icon:save[role="green"]) the settings.

[[table-order-types-delivery-order-options]]
.Options for splitting up orders into delivery orders:
[cols="1,3"]
|====
|Setting|Explanation

2+^| *Split up orders into delivery orders by*

| *Off*
|Orders are not split up into delivery orders. +
*_Note_*: If this option is activated, delivery orders can only be created manually. Automatically creating delivery orders or using event procedures to create delivery orders is not possible with this setting.

| *Warehouse*
|The delivery orders are created according to the different *Warehouses* of the items included in the order.

| *Shipping profile*
|The delivery orders are created according to the different *Shipping profiles* of the items included in the main order.

| *Warehouse and shipping profile*
|The delivery orders are created according to the different *Warehouses and shipping profiles* of the items included in the main order.

| *Warehouse stock and net stock*
|The delivery orders are created according to the different *Warehouse stock and net stock* of the items included in the main order.
|====

[#330]
=== Manually creating delivery orders

If necessary, you can manually create delivery orders via the main order. When you do so, you need to select the item orders and quantities for each delivery order.

We recommend to generally create delivery orders for *all* order items in the main order. If one or several items remain in the main order without being assigned to a delivery order, problems may be caused in your plentymarkets system.

In addition, the quantity you indicate for *DelOrdQua* (quantity to be transferred to the delivery order) must not exceed the quantity indicated for *Unass.Quantity* (unassigned quantity).

[.instruction]
Manually creating delivery orders:

. Go to *Orders » Edit orders*.
. Open the order for which delivery orders should be created.
. Open the *Delivery* tab.
. Enter the *Quantity* that should be transferred to the delivery order in the field *DelOrdQua* (quantity to be transferred to the delivery order).
. Click on the *gear-wheel icon* (icon:cog[]) to create the delivery order. +
→ The delivery order is created.
. Repeat the process to create further delivery orders.

[#340]
=== Automatically creating delivery orders

[IMPORTANT]
.Requirement for automatically creating delivery orders
====
This function can only be used if no delivery order has ben created for the main order yet.
====

When automatically creating delivery orders, the criteria for splitting up orders into delivery orders described in <<table-order-types-delivery-order-options>>. apply. Thus, the items and quantities to be included in the delivery orders to not have to be selected manually. Instead, the system applies the selected option and transfers the items and quantities from the main order to the delivery orders.

[.instruction]
Automatically creating delivery orders

. Go to *Orders » Edit orders*.
. Open the order for which delivery orders should be generated.
. Open the *Delivery* tab.
. Click on *Generate delivery orders automatically* (icon:cog[]). +
→ The delivery orders are created.

[#350]
=== Creating delivery orders with an event procedure

An ideal way to create delivery orders is using an event procedure. This way, you can determine when and how delivery orders are created from a main order. Below, three examples for creating delivery orders with an event procedure are described.

Set up one or all of the following event procedures and carry out the described settings.

==== Example A: Event procedure “Create delivery order when order is received”

Use the following settings if you want delivery orders to be generated as soon as a new order enters your plentymarkets system.

Because this event procedure comes into effect directly upon reception of a new order, the status of the main order is not taken into consideration. Thus, delivery orders will also be created for main orders that are in status *3.0* (or *1.0* if you work with auction platforms such as eBay) and will adopt the status of the main order.

:table-event-procedure: <<table-event-procedure-delivery-order-when-new-order>>
include::_includes:partial$event-procedure.adoc[]

[[table-event-procedure-delivery-order-when-new-order]]
.Options for the event procedure “Create delivery order when order is received”
[cols="1,3,3"]
|====
|Setting |Option |Selection

| *Event*
| *New order*
|

| *Filter 1*
| *Order > Order type*
| *Order*

| *Filter 2*
| *Order > Order warehouse*
| *Multiple warehouses per order*

| *Procedure*
| *Order > Generate delivery orders*
|

|====

==== Example B: Event Procedure “Create delivery order when order changes to status 5”

Use the following settings if you want delivery orders to be created as soon as an order changes to status 5.

Don't change anything at the main order when working with this event procedure. Otherwise, the total item quantities included in the delivery orders will not match the item quantity included in the main order.

:table-event-procedure: <<table-event-procedure-delivery-order-status-5>>
include::_includes:partial$event-procedure.adoc[]

[[table-event-procedure-delivery-order-status-5]]
.Options for the event procedure “Create delivery order when order changes to status 5”
[cols="1,3,3"]
|====
|Setting |Option |Selection

| *Event*
| *Order change > Status change*
| *Cleared for shipping*

| *Filter 1*
| *Order > Order type*
| *Order*

| *Filter 2*
| *Order > Order warehouse*
| *Multiple warehouses per order*

| *Procedure*
| *Order > Generate delivery orders*
|

|====

==== Example C: Event procedure “Create delivery order when generating an invoice”

Use the following settings if you want delivery orders to be created as soon as an invoice is generated for the main order. +
This allows you to edit the main order as necessary until an invoice is created and the order is cleared for shipping. The following settings are required:

:table-event-procedure: <<table-event-procedure-invoice-generated>>
include::_includes:partial$event-procedure.adoc[]

[[table-event-procedure-invoice-generated]]
.Options for the event procedure “Create delivery order when generating an invoice”
[cols="1,3,3"]
|====
|Setting |Option |Selection

| *Event*
| *Documents > Invoice generated*
|

| *Filter 1*
| *Order > Order type*
| *Order*

| *Filter 2*
| *Order > Order warehouse*
| *Multiple warehouses per order*

| *Procedure*
| *Order > Generate delivery orders*
|

|====

[#360]
=== Editing main orders and delivery orders

To open main orders, variable users have to be xref:business-decisions:user-accounts-access.adoc#100[authorised] to view all warehouses linked to the delivery orders of the main order. Check the settings in the menu *Setup» Settings » User »Accounts » Tab: Rights* for this.

If you want to delete a main order, the respective delivery orders have to be deleted first. Delivery orders can be deleted individually or with the group function in the order search. The main order can only be deleted after this is done. But note that as soon as tax relevant documents exist, orders cannot be deleted any more.

Further order items can be added or deleted from the main order. However, you can only delete order items from the main order if they are not included in the delivery orders. Thus, you can increase or reduce the item quantity included in the main order. Make sure to only delete quantities that are not assigned to delivery orders.

[WARNING]
.Deleting order items of a delivery order
====
It is technically possible to delete order items that are already included in a delivery order. But you should avoid this in order to prevent errors.
====

[#400]
== Working with return orders

The order type return depicts the business transaction of receiving returned goods. You and your staff can create return orders manually. In addition, you can allow customers in your online shop to register returns in the *My account* area. Registering the return does not book the returned items back into your stock. First, you register the returned items and then you decide whether they should be booked back into the stock or if further steps, for example a repair, are necessary. Return orders are subordinated orders because they are always linked to a main order or a warranty.
Before returns can be registered in your system, you have to set up xref:orders:managing-orders.adoc#410[reasons for returns] and xref:orders:managing-orders.adoc#420[item statuses] for returned items.

The default status for returns is status 9. Every registered return is automatically assigned this status. However, you can change the default status according to your requirements in the menu *Setup » Orders » Settings* by selecting another xref:orders:basic-settings.adoc#intable-default-status-return[default status for returns].

[#410]
=== Creating reasons for returns

In plentymarkets, you can create up to 20 reasons for returns. When registering returns, you can choose a reason for each returned item. Reasons for returns can help you later to determine whether an item was frequently returned for the same reason.
You can add return reasons for several languages.

[.instruction]
Creating reasons for returns:

. Go to the menu *Setup » Orders » Order types » Return*.
. Select a *Language* from the drop-down list.
. Enter *Reasons for returns* for the selected language.
. *Save* (icon:save[role="green"]) the settings.
. If needed, repeat this for other languages.

[#420]
=== Creating statuses for returned items

You can create up to 12 statuses for returned items. You can use these statuses, for example, to display the state of the returned items or the progress of the return process The item statuses are available in the *Overview* tab in a return order. Create the necessary statuses according to your requirements to depict the progress. You can add statuses for several languages.

[.instruction]
Creating statuses for returned items:

. Go to the menu *Setup » Orders » Order types » Return*.
. Select a *Language* from the drop-down list.
. Enter the *statuses* that should be assigned to returned items for the selected language.
. Save (icon:save[role="green"]) the settings.
. If needed, repeat this for other languages.

[#440]
=== Creating and editing returns

You can either manually create a return once you receive the returned goods or you can allow your customers to register returns directly in the My account are of the online shop. After a return has been registered, more options for editing become available. For example, the status of the returned items can only be entered after registration.

==== Creating a return

[.instruction]
To create a return, proceed as described:

. Go to *Orders » Edit orders*.
. Open the order or the warranty for which the return is to be created.
. In the table-settings-return Overview tab, click on *Return* and select the option *create*. +
→ A window for creating the return opens.
. Carry out the settings according to <<table-settings-return>>.
. Save (icon:save[role="green"]) the settings. +
→ The return is created and opens in a new tab.

[[table-settings-return]]
.Options for creating a return
[cols="1,3"]
|====
|Setting |Explanation

2+^| *Settings*

| *Status*
|Select a status for the return. The xref:orders:basic-settings.adoc#intable-default-status-return[default status for returns] defined in the menu *Setup » Orders » Settings* is displayed here by default.

| *Owner*
|Select an owner to be assigned to the return.

| *Package code of the return*
|Enter the package code of the return delivery.

2+^| *Item*

| *Transfer return reason*
|Select a reason for return to be applied to all returned items. +
If a reason is selected here, it has priority over all reasons for returns assigned to individual items.

| *Accept*
|Select the items to be included in the return.

| *Quantity*
|Select the item quantity to be included in the return.

| *Reason for return*
|Select an individual reason for return from the drop-down list. +
*_Note_*: If a reason is selected, it has priority.

| *Item*
|Change the item name, if necessary.
|====

After having created a return, you can select an item status in the Stock units tab of the return. In addition, more editing options become available.

[#450]
=== Creating a return slip

You can include a return slip in every shipment of items sent to your customers. In this case, the return slip should contain blank fields for the reasons of return. Alternatively, you can allow your customers to fill out the return slip in the *My account* area of the online shop and to print it after having filled in the reasons for the return. The return slip can then be included in the return delivery.
Before creating return slips, the document template xref:orders:generating-return-slips.adoc#[Return slip] has to be set up in the menu *Setup » Client » [Select client] » Locations » [Select location] » Documents » Return slip*.

[TIP]
.Displaying reasons for returns on the document template
====
To include a blank return slip in every shipment regardless whether items will be returned or not, create a return slip directly in the main order. You can also allow your customers to register returns and select reasons for those returns in the My account area of the online shop. Your customer can then print the filled in return slip. No matter which of these options you use: in order to be able to insert reasons for a return, the column including those reasons has to be placed below the list of items.
====

Check the list of returned items and change data if necessary, for example the quantities, *before* creating a return slip in the *Receipts* tab of the return order.

[.instruction]
Creating a return slip manually:

. Open the return order and then the *Receipts* tab.
. Select the option *Return slip* from the drop-down list *Create receipt*. +
→ A new window opens.
. Carry out the settings for the return slip.
. *Save* the settings to create the return slip.

[TIP]
.Generating a return slip automatically
====
Set up an event procedure that automatically generates return slips. If you select the event *New return (by customer)* and the filter *Client (shop)*, blank return slips are generated with each incoming return and only have to be provided for downloading.
====

[#460]
=== Reversing stock

Once returned items reach you, you can partly or completely reverse the stock. Alternatively, it is also possible to completely reset the outgoing items that have been booked while processing the main order.

[.instruction]
Reversing stock:

. Go to *Orders » Edit orders*.
. Select the option *Return* from the filter called *type*.
. Click on *Search* (icon:search[role="blue"]). +
→ The return orders are listed.
. Open the return for which you want to reverse stock.
. Open the *Settings* tab.
. Click on *Add items to stock* next to the option *Stock*. +
→ A window for editing opens.
. Carry out the settings according to <<table-reversing-stock-return>>.
. *Save* (icon:search[role="blue"]) the settings.

The procedure for reversing stock of returns belonging to orders with delivery orders is the same. The window for editing the stock reversal also shows whether there are delivery orders.

[[table-reversing-stock-return]]
.Options for reversing stock
[cols="1,3"]
|====
|Setting |Explanation

| *Reset outgoing items completely*
|Resets outgoing items completely. The date on which the outgoing items were booked is deleted as well.

2+^| *Reverse stock*

| *Select entire quantity*
|Transfers the entire quantity of items included in the order to the column *Reverse*.

| *Deselect entire quantity*
|Sets the item quantities in the column *Reversed* to 0.

| *Reverse*
|If items are only to be booked partly, manually enter the item quantities to be booked here.

| *Warehouse*
|Select the warehouse for the items.

| *Storage location*
|Select the storage location for the items.

| *Quantity in the order*
|Displays the item quantity of the order.

| *Reversed*
|Displays already booked item quantities.

| *Batch*
|Displays the batch number of the item.

| *BBF*
|Displays the best before date.

| *ID*
|Displays the ID of the item.

| *Item*
| Displays the item name.
|====

[TIP]
.Incoming items from returns
====
An overview of all incoming items for which returns have already been announced is available in the menu xref:stock-management:managing-backlog-lists.adoc#400[Stock » Returns » Supply].
====

[#500]
== Working with credit note orders

Credit note orders are used for reimbursing your customers, for example after a xref:orders:managing-orders.adoc#400[return order]. A credit note in plentymarkets does not represent a reverse invoice but a refund. Credit note orders are created from an existing main order in the menu *Orders » Edit orders*. Thus, a credit note is always linked to a main order. The credit notes created in a credit note order are included in your financial accounting such as the *DATEV* export.

[#510]
=== Setting a default status for credit notes

Before creating credit note orders, check the xref:orders:basic-settings.adoc#intable-default-status-credit-note[default status for credit notes] in the *Setup » Orders » Settings* menu. Change the default status when necessary and then save your settings.

[#520]
=== Creating a credit note order

A credit note order is always linked to an already existing order in your plentymarkets system. That is why you have to open the main order in the overview first, before creating a credit note order.

[TIP]
.Creating a credit note order in the main order or in a return order
====
If a customer has already paid for an order and then decides against the purchase before you have shipped the goods and booked outgoing items, we recommend creating a credit note including all order items in the main order and to cancel the original main order.

In case payment, outgoing items and delivery have already taken place and a xref:orders:managing-orders.adoc#400[return order] or a xref:orders:managing-orders.adoc#700[repair] is created, the credit note order is generated directly in the corresponding return order or repair.
====

[.instruction]
Opening an order:

. Go to *Orders » Edit orders*.
. Search (icon:search[role="blue"]) for the order.
. Open the order for which a credit note order should be created. +
→ The order opens in a separate tab.

[.instruction]
Creating a credit note order:

. Open the *Overview* tab of the order for which a credit note order is to be created.
. Click on the *Credit note* drop-down list.
. Select an option according to the explanations given in <<table-options-credit-note-order>>. +
→ The credit note order is created and opened in a separate window.

[[table-options-credit-note-order]]
.Options when creating a credit note order
[cols="1,3"]
|====
|Setting|Explanation

| *from all positions*
|All item positions of the selected order are assigned to the credit note order.

| *from individual items*
|A window to select individual item positions opens.
|====

If a credit note order already exists for an order, there will be a note on the right-hand side of the *Overview* tab notifying you that there is a *Credit note available*. In addition, the credit note order is linked in the *Overview* tab and can be found by using the *Credit note / search* drop-down list.

[#530]
=== Generating a credit note

[IMPORTANT]
.Setting up a document template
====
Before generating credit notes, you have to set up the xref:orders:generating-credit-notes.adoc#[document template for credit notes]. This is done in the *Setup » Client » [Select client] » Location » [Select location] » Documents » Credit note* menu.
====

After creating a credit note order, a credit note has to be created directly in the credit note order. Check the items included in the credit note order and, when necessary, carry out changes before creating the credit note in the *Receipts* tab of the credit note order.

[.instruction]
Generating a credit note:

. Open the credit note order for which a credit note is to be created.
. Select the option *Credit note* from the drop-down list Create receipt.
. Click on *Create receipt*. +
→ The credit note order is created and opened in a separate tab.

Created credit notes show a reference to the invoice of the corresponding order. In the *Documents* tab of an order, this is shown in the naming of the credit note.

[#540]
=== Reversing and correcting a credit note

Once you have generated the credit note for a credit note order, the credit note order will be locked and can no longer be edited. The lock ensures that tax relevant information cannot be changed. If you discover an error in your credit note after the document was created and you wish to correct it, a *Reversal document refund* has to be generated.

[#543]
==== Setting up a reversal document template

First set up a template for the reversal document. The fastest way to fill all required settings is to apply the settings from the default document template. +
The following steps describe how to apply the settings from a default document template.

[.instruction]
Setting up a reversal document template:

. Go to *Setup » Client » [Select client] » Locations » [Select location] » Documents » Refund reversal*.
. Click on the *Transfer* tab.
. Click on *Accept* to *Apply the settings from default document template*.

Because the information in a reversal document is identical with the information included in an invoice, further information on the required settings can be found on the xref:orders:generating-invoices.adoc#[invoice] manual page.

[#547]
==== Correcting a credit note

Correct a credit note by generating a *refund reversal document* first. The reversal of a credit note allows you to make the required changes in the credit note order and a new credit note can be generated. Generating a reversal document does not cancel the credit note order itself.

[IMPORTANT]
.Correcting a credit note
====
The reversal of a credit note is used for a transparent correction of tax relevant data and *not* for the reversal of the credit note order itself.
====

[.instruction]
Correcting a credit note:

. Go to *Orders » Edit orders*.
. Open the order that contains the credit note you want to reverse.
. Click on the *Receipts* tab.
. Select the option *Refund reversal* from the *Create receipt* drop-down list. +
→ A new window with optional settings opens.
. *Save* (icon:save[role="green"]) the settings. +
→ The reversal document is generated and the settings of the credit note order are unlocked.
. Edit the data.
. Click on the *Receipts* tab.
. Select the option *Credit note* from the *Create receipt* drop-down list. +
→ A window with optional settings opens.
. *Save* (icon:save[role="green"]) the settings. +
→ The reversal document is generated and the settings of the credit note order are locked again.

[#550]
=== Booking refunds

After creating a credit note, the refund of the credited amount has to be booked in your plentymarkets system. Refunds that are transferred via one of the payment providers you have integrated in your system are booked directly in the *Settings* tab of the credit note order. The *Refund to customer* option is only displayed for the payment methods *PayPal*, *ClickandBuy* and *heidelpay*.

[IMPORTANT]
.Requirements for PayPal
====
*PayPal* does not allow you to enter an amount higher than the amount paid for the original order.
====

[.instruction]
Booking a refund in the *Settings* tab:

. Go to *Orders » Edit orders*.
. Open the credit note for which you want to book a refund.
. Open the *Settings* tab.
. Click on the *payment icon* next to the *Refund* option.
. Check the *Amount* of the refund and adjust it when necessary.
. Click on the *gearwheel* (icon:cog[]) to book the refund. +
→ The refund is booked.

The refund can also be booked in the *Payment* tab of the credit note order. Click on the *Payment* tab to see all payments and partial payments belonging to the order. Using this tab for booking a refund is necessary when the original order has not been paid with a payment provider integrated in your plentymarkets system.

[.instruction]
Booking a refund in the *Payment* tab:

. Go to *Orders » Edit orders*.
. Open the credit note for which you want to book a refund.
. Open the *Payment* tab.
. Click on the icon *Book payment*.
. Enter the *Amount* (Debit) and, if necessary, the *Currency* and the *Designated use*.
. Click on *Book payment*. +
→ The refund is booked and displayed in the *Payment* tab.

[#560]
=== Reversing stock

If outgoing items included in a main order have already been booked and have to be booked back into the warehouse, stock has to be reversed in the *Settings* tab of the credit note order.

[.instruction]
Reversing stock:

. Go to *Orders » Edit orders*.
. Open the credit note order for which you want to reverse stock.
. Open the *Settings* tab.
. Click on the reset link next to the option Outgoing items.
. A separate window opens. Select the required option as described in <<table-settings-reverse-stock>>.
. *Save* (icon:save[role="green"]) the settings to carry out the process.

[[table-settings-reverse-stock]]
.Options for reversing stock for credit notes
[cols="1,3"]
|====
|Setting |Explanation

| *Reset outgoing items completely*
|Completely resets the outgoing items. This option also deletes the date of the outgoing items.

| *Reverse stock*
|In this section, items are completely or partially reversed. Outgoing items are *not* reset with this option.

| *Select entire quantity*
|Enters the complete quantity of items into the field *Reverse*.

| *Deselect entire quantity*
|Sets the item quantity listed under *Reverse* to 0.

| *Reverse*
|If reversal should only be carried out for a partial quantity, enter the item quantity that is to be reversed.

| *Warehouse*
|Select the warehouse for the items.

| *Storage location*
|Select the storage location for the items.

| *Quantity in the order*
|Displays the number of items included in the order.

| *Reversed*
|Displays the quantity of items already reversed.

| *Batch*
|Displays the batch number of the items included in the order.

| *BBF*
|Displays the best before date of the items included in the order.

| *ID*
|Displays the the item's ID.

| *Item*
|Displays the item name.
|====

[#600]
== Working with warranties

Warranties are quite similar to xref:orders:managing-orders.adoc#400[returns]. In both cases, the items of an order in *status 7* will be sent back to you. In contrast to a return, customers expect a new delivery or a refund in the form of a xref:orders:managing-orders.adoc#500[credit note].

[TIP]
.Guarantee vs. Warranty
====
In contrast to a guarantee voluntarily provided by the seller, the warranty represents the *legal obligation* of the seller to eliminate defects and damages that already existed when the item was delivered to the customer free of charge. Depending on the characteristics of the items and the legislation that applies, customers can have a right to claim a warranty up to 2 or 3 years after the purchase of the item. If damages appear more than 6 months after the receipt of the items, the customer has to prove that they already existed upon delivery.
====

If the conditions for a warranty apply, you can decide whether to refund the customer’s costs or to exchange the damaged item with a new one. Create a *warranty* to replace the damaged item. For refunding the customer, create a refund in the *Overview* tab of the warranty. Determine in the basic settings *Setup » Orders » Settings* menu whether the xref:orders:basic-settings.adoc#intable-shipping-costs-in-warranty[shipping costs should be covered in the warranty].

[TIP]
.Warranty settings
====
If you create a warranty directly within an order, the *shipping profile* of the main order is automatically adopted. However, the settings can be changed in the warranty’s editing window. For *delivery orders*, the correct warehouse is automatically selected as well. The *payment method* for a warranty can be changed.
====

[#610]
=== Creating a warranty

In general, a warranty is created out of a return order. However, it is also possible to create it out of the original main order.

We recommend creating the warranty directly in the main order if the customer finds fault with the ordered items after delivery and you decide against proceeding with a return order.

If you wish to proceed with a return order to examine the damaged items, create a return order first and create the warranty in the return order.

[.instruction]
Creating a warranty:

. Go to *Orders » Edit orders*.
. Open the *return* or the original main *order* for which you want to create a warranty.
. Click on the *Warranty* drop-down list.
. Select an option according to the explanations given in <<table-options-warranty>>.
. Save (icon:save[role="green"]) the settings. +
→ The warranty is created and opens in a new tab.

[[table-options-warranty]]
.Options when creating a warranty
[cols="1,3"]
|====
|Setting|Explanation

| *from all positions*
|All item positions of the selected order are assigned to the credit note order.

| *from individual items*
|A window to select individual item positions opens.
|====

[#620]
=== Editing a warranty

Existing warranties are displayed in the overview. Open the warranty to enter an additional *price* if you decide to replace the damaged item by providing the customer with a similar but more expensive one. The quantities of the items included in the warranty can be changed here as well. Proceed as described below to edit a warranty.

[.instruction]
Editing a warranty

. Go to *Orders » Edit orders*.
. In the *Filter* tab, select the option *Warranty* as the *Type*.
. Click on *Search* (icon:search[role="blue"]). +
→ Only warranties are listed.
. Click on the warranty you want to edit. +
→ The warranty opens and can be edited in the *Edit* tab.


[#630]
=== Completing a warranty

In order to complete a warranty for which an additional charge is billed for the replacement, an invoice has to be created within the warranty. In case the customer agrees to a discount on the damaged item instead of proceeding with a return order, you have to create a credit note in the original main order.

Proceed as described below to complete a warranty by replacing items:

[.instruction]
Completing a warranty with a replacement:

. Click on the *Receipts* tab within the warranty.
. Select the option *Invoice* from the *Create receipt* drop-down list. +
→ A window for editing opens.
. Adjust the settings as needed.
. Save (icon:save[role="green"]) the settings. +
→ The invoice is created and opened in a separate tab.
. Open the *Settings* tab.
. Click on the icon *Book outgoing items* in the column *Outgoing items.* +
→ The outgoing items are booked and the *status* automatically changes to *[7] Outgoing items booked.*
. Go to *Orders » Edit orders*.
. Change the status manually to *[10] warranty*.
. Save (icon:save[role="green"]) the settings.

[TIP]
.Booking incoming payments for warranties
====
Generally, incoming payments for warranties only have to be booked it an additional charge has been negotiated with the customer. In this case, book the incoming payment after the customer has made it in the *Payment* tab of the warranty.
====

Proceed as described below to complete a warranty by creating a credit note order and the corresponding receipt.

[.instruction]
Completing a warranty with a credit note:

. Open the main order or the return order for which you want to create a credit note.
. Open the Overview tab.
. Click on the *Credit note* drop-down list and select *create*. +
→ The credit note order is created and opened in a separate window.

All further steps necessary to complete the credit note order are identical to the regular procedure for credit note orders. This is described in detail in the xref:orders:managing-orders.adoc#500[credit note] chapter on this manual page.

[#700]
== Working with repairs

In plentymarkets, repairs are represented by a separate order type. Repairs consist of returned items that need to be repaired. Thus, repairs can only be created from xref:orders:managing-orders.adoc#400[returns].

[#710]
=== Creating statuses for repairs

Before using repairs you should set *statuses* for the different steps of the repair process in order to monitor the process in your plentymarkets system in detail. You can add statuses for several languages.

[.instruction]
Creating statuses for repairs:

. Go to the menu *Settings » Sales orders » Sales order types » Repair*.
. Select a *Language* from the drop-down list.
. Enter the statuses you require for processing repairs for the selected language. +
. *Save* (icon:save[role="green"]) the settings.
. If needed, repeat this for other languages.

[#720]
=== Creating conditions for repairs

*Conditions* are used to precisely describe the items themselves, e.g. if an item needs to be repaired or if it is beyond repair. You can add conditions for several languages.

[.instruction]
Creating conditions for repairs:

. Go to the menu *Settings » Sales orders » Sales order types » Repair*.
. Select a *Language* from the drop-down list.
. Enter the different *conditions* you will need for assigning stock units for the selected language.
. *Save* (icon:save[role="green"]) the settings.
. If needed, repeat this for other languages.

[#730]
=== Creating a repair

[.instruction]
Proceed as described to create a repair:

. Go to *Orders » Edit orders*.
. Open the return order for which you want to create a repair.
. Open the *Overview* tab.
. Click on the *Repair* drop-down list and select *create*. +
→ A window for editing opens.
. Enter the *status* and the *condition* of the repair.
. Select the *Item*.
. Optionally enter a *Note*, if you require it.
. *Save* (icon:save[role="green"]) the settings. +
→ The return is created and opened in a separate tab.

[#740]
=== Editing a repair

Depending on the reasons for return and the condition of the items that need repairing, different steps have to be carried out. +
Since repairs constitute a separate order type, you can use the *Overview* tab to proceed with a credit note, a warranty or a return order. The necessary steps for each of these order types such as creating the necessary documents, booking outgoing or incoming items or booking payments are identical to the order types xref:orders:managing-orders.adoc#500[credit note], xref:orders:managing-orders.adoc#600[warranty] and xref:orders:managing-orders.adoc#400[return].

[#800]
== Working with multi-orders

You can combine unpaid orders in a multi-order. There are two options for creating multi-orders, both are described below. With both options, unpaid orders are combined in a multi-order in the menu *Orders » Multi-orders*. Multi-invoices are then created in the *Receipts* tab of a multi-order.

[#810]
=== Carrying out basic settings for multi-orders

Carry out the basic settings for multi-orders the *Setup » Orders » Order types » Multi-order*. In this menu, you define such details as the order types and order statuses for which multi-orders are to be created.

[.instruction]
Carrying out basic settings for multi-orders:

. Go to *Setup » Orders » Order types » Multi-order*.
. Carry out the settings as described in <<table-multi-order-settings>>.
. *Save* (icon:save[role="green"]) the settings.

[[table-multi-order-settings]]
.Basic settings for multi-orders
[cols="1,3"]
|====
|Setting|Explanation

| *Order types*
|Select which order types are to be available for multi-orders. Multiple selections are possible. Only the listed order types *Order*, *Warranty* and *Repair* can be combined in multi-orders.

| *Item text*
|Select which options are used for the *item text* column of the stock units that belong to a multi-order. Multiple selections are possible. The selected options will be listed separately for each individual order within the multi-order. This ensures that the options can easily be connected to the correct customers and orders.

| *Sort orders by*
|Select how individual orders are sorted within a multi-order. Only one selection is possible. Orders can be sorted by their order ID (*Order ID ascending* or *Order ID descending*) or their date of outgoing items (*Outgoing items ascending* or *Outgoing items descending*).

| *Order status of orders*
|Select the status orders have to be in to be considered for multi-orders. Multiple selections are possible. Depending on your workflow, we recommend creating an individual order status to target specific order that are intended for multi-orders.

| *Order status of credit notes*
|Select the status xref:orders:managing-orders.adoc#510[credit note orders] have to be in to be considered for multi-orders. Multiple selections are possible.
|====

Furthermore, go to xref:orders:basic-settings.adoc#[Setup » Orders » Settings] and use the option *Standard status for multi-order* to specify which order status should be given to multi-orders when they are generated. The status *[13] Multi-order* is available by default. In addition, select a status for multi credit notes. The status *[14] Multi credit note* is available by default.

[#820]
=== Creating a multi-order per customer class

Example: A company may not want to receive an invoice every time one of their employees make a purchase in your online shop. Rather, the company prefers one monthly invoice for all of its employees’ purchases. Set up a customer class for this situation. The invoice recipient is specified by saving a customer ID in the customer class. The multi-invoice is generated directly within the corresponding multi-order and sent to this invoice recipient. +

Go to *Orders »Multi-orders* to create a multi-order for a specific customer class and a fixed time period. This way, all unpaid orders belonging to the customer class are combined in one multi-order. Use the option *Customer ID* in the customer class settings to determine a customer who is listed as the owner as well as as the recipient of the multi-invoice for a customer class. According to your workflow, we recommend creating specific xref:crm:preparatory-settings.adoc#create-customer-class[customer classes] for multi-orders.

[.instruction]
Creating a multi-order for a customer class:

. Go to *Orders » Multi-orders*.
. Open the submenu *Generate multi-orders*
. Select the *Customer class* and an optional *Period*. The time period refers to the date of the incoming order.
. Click on terra:execute[]. +
→ The multi-order is created.

[#830]
=== Creating a multi-order per customer

Customers prefer to pay for their orders once a month or once per quarter instead of paying several separate invoices. +
For these cases, go to *CRM » Contacts* to create a multi-order in the contact data. Open the contact and click on *New multi-order* in the menu on the left. A multi-order including all unpaid orders of the contact is then automatically created.

[TIP]
.Checking orders
====
In order to make sure that appropriate orders for creating a multi-order are available, use the *Orders* tab in the contact data to look for unpaid orders.
====

[#840]
=== Generating a multi-invoice

Multi-invoices can only be generated in the corresponding multi-order. The first step consists of setting up a document template for multi-invoices in the menu *Setup » Client » [Select client] » Locations » [Select location] » Documents » Multi-invoice*. Here, you can specify detailed settings for the document and also save a xref:orders:order-documents.adoc#[document template] as a PDF file. Customise the template as required. Default values are set in the basic settings of the document template. You can also transfer further settings, e.g. from the document template *invoice*, to complete the values.

After having set up a document template for multi-invoices, you can generate a multi-invoice in the *Receipts* tab of a multi-order. To do so, proceed as follows.

[.instruction]
Generating a multi-invoice:

. Go to *Orders » Edit orders*. +
→ The order overview opens.
. Use the filters to search (icon:search[role="blue"]) for the multi-order for which you want to generate a multi-invoice.
. Open the multi-order.
. Go to the *Receipts* tab.
. Select the document *Multi-invoice* from the *Create receipt* drop-down list. +
. Carry out the settings according to <<table-orders-receipts-multi-invoice>>. +
. *Save* (icon:save[role="green"]) the settings to generate the multi-invoice. +
→ A *PDF file* of the just generated multi-invoice opens.

[[table-orders-receipts-multi-invoice]]
.Settings for multi-invoices in Create receipt menu.
[cols="1,3"]
|====
|Setting |Explanation

| *Date*
|Enter a date to be displayed on the multi-invoice. The present date is set by default.

|*Number*
|	The document number is assigned automatically. No entry is required in this field.

|*Integrate the invoices of these orders*
|Select by choosing *YES* or *NO* whether the invoices of the individual orders of the multi-order are generated as well.

| *Book outgoing items*
|Select by choosing *YES* or *NO* whether outgoing items should be booked when the multi-invoice is created.

| *Change order status to status*
|Choose an order status to which the order is to be changed after the multi-invoice is created. If you don’t want the order status to change, select *No change* .

| *Comment*
|The text entered here is displayed below the order items. The entry of a text is optional.
|====

[IMPORTANT]
.Incoming payments for multi-orders
====
If a customer pays a multi-invoice and the multi-order is marked as paid, the incoming payment is *not* automatically booked in the separate orders which are combined in the multi-order. You have to book incoming payments manually in the respective orders.
====

[.discrete]
==== Generating multi-invoices with an event procedure

Use the event procedures available in your plentymarkets system to automatically generate a multi-invoice as soon as a multi-order is created. To do so, proceed as described below:

:table-event-procedure: <<table-event-procedure-multi-invoice-automatic>>
include::_includes:partial$event-procedure.adoc[]

[[table-event-procedure-multi-invoice-automatic]]
.Event procedure “Automatically generating a multi-invoice”
[cols="1,3"]
|====
|Setting |Selection

| *Event*

| *Order generation > New multi-order*

| *Procedure*

| *Documents > Generate multi-invoice* +

|====

[#850]
=== Generating a multi credit note

Multi credit note are generated in the menu *Orders » Multi-orders*. +
All credit notes for a customer class are combined in one multi credit note. Depending on your workflow, we recommend creating specific xref:crm:preparatory-settings.adoc#create-customer-class[customer classes] for multi credit notes.

[.instruction]
Generating a multi credit note for a customer class:

. Go to *Orders » Multi-orders*.
. Open the submenu *Generate multi credit notes*.
. Select the *Customer class*.
. Optionally, select a *Period*. The time period refers to the date of the order income.
. Click on terra:execute[]. +
→ The multi credit note is generated.

[#860]
=== Generating a multi credit note document

Multi credit note documents can only be generated in the corresponding order type multi credit note. The first step consists of setting up a document template for multi credit note documents in the menu *Setup » Client » [Select client] » Locations » [Select location] » Documents » Multi credit note*. Here, you can specify detailed settings for the document and also save a xref:orders:order-documents.adoc#[document template] as a PDF file. Customise the template as required. Default values are set in the basic settings of the document template. You can also transfer further settings, e.g. from the document template *Credit note*, to complete the values.

After having set up a document template for multi credit note documents, you can generate a multi credit note document in the *Receipts* tab of a multi credit note. To do so, proceed as follows.

[.instruction]
Generating a multi credit note document:

. Go to *Orders » Edit orders*. +
→ The order overview opens.
. Use the filters to search (icon:search[role="blue"]) for the multi credit note for which you want to generate a multi cedit note document.
. Open the multi credit note.
. Go to the *Receipts* tab.
. Select the document *Multi credit note* from the *Create receipt* drop-down list. +
. Carry out the settings according to <<table-orders-generate-document.multi-credit-note>>. +
. *Save* (icon:save[role="green"]) the settings to generate the multi credit note document. +
→ A *PDF file* of the just generated multi credit note opens.

[[table-orders-generate-document.multi-credit-note]]
.Settings for multi credit note documents in *Create receipt* menu.
[cols="1,3"]
|====
|Setting |Explanation

| *Date*
|Enter a date to be displayed on the multi credit note document. The present date is set by default.

|*Number*
|	The document number is assigned automatically. No entry is required in this field.

| *Book outgoing items*
|Select by choosing *YES* or *NO* whether outgoing items should be booked when the multi credit note document is created.

| *Change order status to status*
|Choose an order status to which the order is to be changed after the multi credit note document is created. If you don’t want the order status to change, select *No change* .

| *Comment*
|The text entered here is displayed below the order items. The entry of a text is optional.
|====

[#1100]
== Working with advance orders

Advance orders are an important tool in the marketing mix for e-commerce. Often, items can be ordered at a reduced, introductory price before they actually become available. This represents an unusual case for stock management since items that are not available yet cannot be allocated to a warehouse.

Advance orders are very easily set up in plentymarkets. Just use the order type *advance order* for manually created orders.

To be able to receive advance orders, two requirements must be met: the release date and the stock limitation setting.

[IMPORTANT]
.Manual order input
====
The order type *advance order* can only be selected when manually entering orders.
====

[#1110]
=== Release date

In the first step, specify when the item will become available.

[.instruction]
Entering the release date:

. Go to *Item » Edit item » [Open variation] » Tab: Settings » Area: Availability*.
//ToDo - sobald die neue Artikel-UI standard ist, dann diesen Satz einblenden und dafür den alten Pfad löschen
//. Go to *Item » Item UI » [Open variation] » Element: Availability and visibility*.
. Enter the date on which the item is to be available in the field *Release date*.
. *Save* (icon:save[role="green"]) the settings.

---

In the second step, make the release data visible to your customers in the plentyShop.

[.instruction]
Displaying the release date in the plentyShop:

. Go to *CMS » ShopBuilder » [Open item view]*.
. Add the widget xref:online-store:shop-builder.adoc#_text[Text » Text] to the item details page.
. Click on the text widget's pencil icon.
. Add the release date to the text field.
To do so, click on *Availability » Release date*.
. *Save* the settings.

[#1120]
=== Stock limitation

In the first step, allow the item to be purchased, i.e. pre-ordered, without actually being in stock.

[.instruction]
Setting no stock limitation:

. Go to *Item » Edit item » [Open variation] » Tab: Settings » Area: Availability*.
. Find the option *Limitation* and select the setting *None*.
//ToDo - sobald die neue Artikel-UI standard ist, dann diese 2 Sätze einblenden und dafür den alten Sätzen löschen
//. Go to *Item » Item UI » [Open variation] » Element: Availability and visibility*.
//. Find the option *Stock limitation* and select the setting *None*.
. *Save* the settings. +
→ The item can now be purchased, i.e. pre-ordered, without actually being in stock.

---

In the second step, specify the maximum order quantity.
For example, this prevents the competition from buying out your entire stock at a reduced, introductory price.

[.instruction]
Setting the maximum order quantity:

. Go to *Item » Edit item » [Open variation] » Tab: Settings » Area: Availability*.
. Enter a value into the field *Max. order quantity*.
//ToDo - sobald die neue Artikel-UI standard ist, dann diese 2 Sätze einblenden und dafür den alten Sätzen löschen
//. Go to *Item » Item UI » [Open variation] » Element: Availability and visibility*.
//. Enter a value into the field *Maximum order quantity*.
* Example: if you enter the value 1, then customers will only be able to buy one copy of the item with their order.
* If you enter the value 0 or leave this field empty, then there is no limitation.
. *Save* the settings.

[#1130]
=== Setting up a payment request for advance orders

Usually, the option *shipping date* is not used for ordinary orders. However, it can be helpful to use this option for advance orders. If the release date of an item is in the future, the release date will then be saved as the order’s shipping date since deliveries can only take place once the item is released. You can use the shipping date as a filter option in the order search and in the procedure manager.

Advance orders are usually generated some time before an item appears and are not paid for by the customers at the time when they are ordered. That’s why it is useful to inform your customers a few days in advance about the upcoming shipment and request payment from them. Use the procedure manager to automate this process. A few days before shipping takes place, the procedure manager will automatically send the customers a reminder email stating your bank details and providing a link to the checkout. Proceed as described below to set up the automatic payment request.

[.instruction]
Setting up a payment request via email:

. Create an xref:crm:sending-emails.adoc#1200[Email template].
. Go to *Setup » Orders » Procedures*.
. Open the New procedure tab.
. Enter a *name* in the *Settings* tab.
. Select a time from the drop-down list next to the option *Execute every day at*.
. Activate the option *Active* to activate the procedure.
. Click on the *Filter* tab.
. Set the *status* to *[3] Waiting for payment*.
. Select an option for *Shipped on*, e.g. *in 4 days*.
. Click on the *Procedure* tab.
. Select the previously created email template for the option *Send email template*. With this procedure, this template will automatically be sent to the customer.
. *Save* (icon:save[role="green"]) the procedure.

[#1200]
== Using order statuses

The order statuses visualise the progress of orders during order processing. 19 statuses with 4 decimal places each, so a total of 199999, are available in your plentymarkets system. 28 statuses are set by default. These statuses represent a basis for usual steps of order processing. Some of these 28 statuses are linked to automatic processes in the system. You should only use them for these designated purposes within the system. The status of an order changes because of these automatic processes in the system, through automatic processes set up by you or can be changed manually. Order statuses also improve the order search.

Roughly go through your order processes and determine when you want to assign a different status to orders to depict the progress of your processing. Set up your statuses after this by entering names for them. But take into account the default statuses which are already set up for a specific purpose, mentioned in <<table-default-statuses>>.

[TIP]
.Pay attention to the user rights
======
Note that elements such as drop-down lists only display those *online stores* and *order statuses* for which the current user was given rights to. If you do not see a status, it is most likely that you do not have the rights needed for this. Rights can be assigned by admin users.
======

[#preselected-statuses]
=== Comprehending default order statuses

The following 28 status entries are available by default in your plentymarkets system and some of them are linked to automatic processes in the system. It is not possible to delete statuses that are linked to an automatic process.

[[table-default-statuses]]
.Default statuses and automatic processes within the system
[cols="1,3"]
|===
|Order status |Explanation

| *[1]* Incomplete data
|This status is automatically assigned when the data of an order is incomplete, e.g. missing address details. Incomplete data can sometimes occur when they are imported from markets. Orders with this status are not to be processed further. The data will be completed by subsequent imports. The incomplete data are useful for a timely booking of stock.

| *[1.1]* Waiting for payment & activation
.3+^|Are not assigned automatically. A use case is the shopping cart which was filled in advance. An order is generated and a link to the shopping cart of the order is sent to the customer for confirmation.

| *[1.2]* Activated, waiting for payment

| *[2]* Waiting for activation

| *[3]* Waiting for payment
|This status is automatically assigned to every unpaid order of the type *Order*.

| *[3.2]* In waiting position
a|This status is automatically assigned in the following cases: +

* If a partial payment for an order is booked and items are not in stock. +
* If a down payment for an order is booked and items are not in stock. +
* If an order is overpaid, not matter whether items are in stock or not.

| *[3.3]* Ready for shipping; waiting for payment
|This status is automatically assigned to an order of the type *Order* if a partial payment or a down payment for the order is booked and the items are in stock.

| *[3.4]* Dunning letter sent
|We recommend this status to indicate that a dunning letter was sent. Set up an automatic process for this by using an event procedure or a process. However, the status is not set by an automatic process within the system.

| *[4]* In preparation for shipping
|Is connected to the stock limitation. If you are not keeping stock and do not use the stock limitation, the status is available to be reassigned. +
When the stock limitation is used, the status is automatically assigned as soon as an order of the type *Order* is fully paid but the item is not in stock in sufficient number. The item limitation as to be set to net stock. +
If you use stock limitation and this status for insufficient stock, it is possible to have only those delivery notes and invoices generated which can be processed further.

| *[5]* Cleared for shipping
|This status is automatically assigned when an order of the type *Order* is paid or the payment method is invoice or cash in advance and the item is either in stock or stock is unlimited.

| *[5.1]* External processing
|We recommend to use this status to indicate that the items are compiled and sent by a fulfilment provider. However, the status is not set by an automatic process within the system.

| *[6]* Currently being shipped
|We recommend to use this status to indicate that orders are transferred to the warehouse to be picked and packed. Set up an automatic process for this by using an event procedure or a process.

| *[7]* Outgoing items booked
|This status is automatically assigned when outgoing items of an order were booked. Manually setting this status for an order does not cause the actual booking of outgoing items or the reduction of stock. This is why this status should not be set manually, but via an event procedure or an automated process.

| *[7.1]* Order exported
|This status can be used as required. A possible use case is to assign this status after items are exported for analysing purposes.

| *[8]* Cancelled
|We recommend to use this status to indicate that an order of the type *Order* was cancelled. Status 8 is the default status for cancelled orders. However, if required, you can adjust the default statuses in the *Setup » Orders » Settings* menu. This setting is called xref:orders:preparatory-settings.adoc#[intable-default-status-cancelled-orders[default status for cancelled orders]. If you assigned a different status to cancelled orders, you can reassign status 8 as required.

| *[8.1]* Cancelled by customer
|We recommend to use this status to indicate that an order was cancelled by a customer.

| *[9]* Return
|This status is automatically preselected when an order of the type *Return* is created. You can change the xref:orders:preparatory-settings.adoc#intable-default-status-return[default status for returns], if required. You can find this setting under *Setup » Orders » Settings*.

| *[9.1]* Items are checked
|We recommend to use this status to indicate that returned items are checked.

| *[9.2]* Waiting for return from wholesale dealer
|This status can be used as required.

| *[9.3]* Warranty initiated
|We recommend to use this status to indicate that a warranty of a return has been initiated.

| *[9.4]* Exchange initiated
|We recommend to use this status to indicate that an exchange of returned items has been initiated.

| *[9.5]* Credit note created
|We recommend to use this status to indicate that a credit note for a return was created.

| *[10]* Warranty
|This status can be used as required. This status can be used to identify a completed warranty. When creating a warranty, the corresponding order is switched either to status 4 or 5, depending on your workflow.

| *[11]* Credit note
|This status is automatically assigned to an order of the type *Credit note* when a credit note is generated. You can change the xref:orders:preparatory-settings.adoc#intable-default-status-credit-note[default status for credit notes], if required. You can find this setting under *Setup » Orders » Settings*.

| *[11.1]* Credit note disbursed
|We recommend to use this status to indicate that a credit note was disbursed and is completed.

| *[12]* Repair
|This status is automatically preselected when an order of the type *Repair* is created. You can change the xref:orders:preparatory-settings.adoc#intable-default-status-repairs[default status for repairs], if required. You can find this setting under *Setup » Orders » Settings*.

| *[13]* Multi-order
|This status is automatically assigned to an order of the type *Multi-order* when a multi-order is created. You can change the xref:orders:preparatory-settings.adoc#intable-default-status-multi-order[default status for multi-orders], if required. You can find this setting under *Setup » Orders » Settings*.

| *[14]* Multi credit note
|This status is automatically assigned to an order of the type *Multi credit note* when a multi credit note is created. You can change the xref:orders:preparatory-settings.adoc#intable-default-status-multi-credit-note[default status for multi credit notes], if required. You can find this setting under *Setup » Orders » Settings*.
|===

[TIP]
.Show status ID in status name
======
Use the toggle button *Show status ID in status name* to decide whether only the given status name or also the status ID should be displayed.
======

[#search-for-order-statuses]
=== Searching for order statuses

Use one of the following methods to search for order statuses.

[.instruction]
Searching for order statuses:

. Go to the *Setup » Orders » Order status* menu.
.. *_Option 1_*: Click on material:search[] to see a list of all statuses.
.. *_Option 2:_* Enter something into the search field and click on one of the automatic suggestions.
.. *_Option 3:_* Click on material:tune[] to narrow down the search results with filters.

[#use-filters]
==== Using filters

In order to search for specific order statuses, you can use the following filters.

[[table-filters-order-status]]
.Filters for order statuses
[cols="1,3"]
|===
|Setting |Explanation

| *Status from*
|Filters by statuses from this status number onwards.

| *Status to*
|Filters by statuses up to this status number.

| *Language*
|Filters by statuses with this language.

|===

[#configure-columns]
=== Configuring columns in the overview

In the overview, you can decide which columns should be displayed in the table and also define the order in which they are shown. In order to configure the columns, proceed as follows.

[.instruction]
Configuring columns:

. Go to the *Setup » Orders » Order status* menu.
. At the top right, click on *Configure columns* (material:settings[]). +
→ The window *Configure columns* opens.
. Select (material:done[]) the columns you want to be displayed. Pay attention to the explanations given in <<table-order-status-columns>>.
. Move (material:drag_indicator[]) the columns via drag-and-drop to the desired position until they are displayed in the desired order.
. Add or remove columns according to your needs.
. Click on *Confirm*. +
→ The settings are saved.

[[table-order-status-columns]]
.Columns in the status overview
[cols="1,3"]
|===
|Column |Explanation

| *Checkbox*
|Shows a checkbox at the beginning of the line. Tick the checkbox in order to use one of the available <<#order-status-group-functions, group functions>> for this status.

| *Status*
|Shows the status of the order.

| *Colour*
|Shows the colour of the order status.

| *Name*
|Shows the name of the order status. In case you activated the toggle button *Show status ID in status name* (material:toggle_on[]), the ID is also shown.

| *Name (language)*
|Shows the status name for the language that is shown in brackets. Select all the languages that you need.

| *Delete*
|Shows the delete function for deleting the status (material:delete[]) at the end of the line. +
*_Note:_* Statuses that originate from the system cannot be deleted.

|===

[#order-status-group-functions]
=== Using group functions:

There are some group functions that you can use in order to carry out actions for multiple statuses at once. You can use a group function to <<#change-visibility, change the visibility>>, <<#change-colour, change the colour>> or <<#delete-status, delete specific statuses>>.

[#change-visibility]
==== Changing the visibility

The visibility of order statuses can be determined for different areas. In order to change the visibility for one or several statuses, proceed as follows.

[.instruction]
Changing the visibility:

. Go to the *Setup » Orders » Order status* menu.
. Carry out the search (material:search[]) to display order statuses.
. Place a check mark for one or several statuses (material:check_box[]).
. At the top, click on the *Change visibility* (material:remove_red_eye[]) function. +
→ The *Change visibility* window opens.
. Carry out the settings. Pay attention to the explanations given in <<table-change-visibility>>.
. Click on *Change visibility* (material:remove_red_eye[role=skyBlue]). +
→ The visibility is changed.

[[table-change-visibility]]
.Visibility for order statuses
[cols="1,3"]
|===
|Setting |Explanation

| *Visibility in online store*
|Select from the drop-down list whether the order status should be visible in the online store.

| *Visibility in reorders*
|Select from the drop-down list whether the order status should be visible in reorders.

| *Visibility in redistributions*
|Select from the drop-down list whether the order status should be visible in redistributions.

|===

[#change-colour]
==== Changing the colour

You can adjust the colour of an order status at any time. In order to change the colour for one or several statuses, proceed as follows.

[.instruction]
Changing the colour:

. Go to the *Setup » Orders » Order status* menu.
. Carry out the search (material:search[]) to display order statuses.
. Place a check mark for one or several statuses (material:check_box[]).
. At the top, click on the *Change colour* (material:color_lens[]) function. +
→ The *Change colour* window opens.
. Select a new colour. To do so, either enter a HEX code or select values for RGB (Red, Green, Blue) or HSL (Hue, Saturation, Lightness).
. Click on *Change colour* (material:color_lens[role=skyBlue]). +
→ The colour is changed.

[#delete-status]
==== Deleting an order status

Order statuses can also be deleted. However, note that this is not possible for statuses that originate from the system. In order to delete order statuses, proceed as follows.

[.instruction]
Deleting an order status:

. Go to the *Setup » Orders » Order status* menu.
. Carry out the search (material:search[]) to display order statuses.
. Place a check mark for one or several statuses (material:check_box[]).
. At the top, click on the *Delete status* (material:delete[]) function. +
icon:map-signs[] *_Or:_* On the right in the line of a status, click on *Delete* (material:delete[]) in order to delete this status only. +
→ The window *Delete status* opens.
. If you are sure that you want to delete all selected statuses, confirm the confirmation message by clicking on *Delete status* (material:delete[role=red]). +
→ The statuses are deleted.

[#create-status]
=== Creating a new status

In the *Setup » Orders » Order status* menu, you can add your own statuses in addition to those listed in <<table-default-statuses>>. You can edit the available statuses. Maintain statuses in different languages in order to inform your customers about the progress via email or in the customer account of the online shop. Status related to system automatisms can be renamed. However you should make sure to not misuse the status related to system automatisms. To create a new status, proceed as follows.

[.instruction]
Creating a new status:

. Go to the *Setup » Orders » Order status* menu.
. Click on *Create new status* (material:add[]). +
→ The *Create new status* window opens.
. Carry out the settings. Pay attention to the explanations given in <<table-create-new-status>>.
. Click on *Create* (material:add[role=green]). +
→ The new status is created.

[[table-create-new-status]]
.Creating a new status
[cols="1,3"]
|===
|Setting |Explanation

| *New status*
|Enter a status number (e.g. 2.5). Make sure that this status is unique. If the entered status already exists, en error message is displayed. +
This is a mandatory field.

| *Name in system language (language)*
|Enter a name for the new status. The language in which you are logged in is shown in the input field. +
This is a mandatory field.

| *Colour*
|Select a colour for the new status. To do so, either enter a HEX code or select values for RGB (Red, Green, Blue) or HSL (Hue, Saturation, Lightness).

| *Visibility*
|Select whether the new status should be visible in the online store, in reorders or in redistributions.

|===

[TIP]
.Pay attention to decimal places
======
When assigning numbers to new statuses, make sure that they do not end with 0. If the last decimal place is a 0, the system automatically deletes it. Thus, plentymarkets makes no distinction between a status with the number 1.1 and a status with the number 1.10.
======

[#edit-status]
=== Editing a status

Statuses can be edited at any time. Via the group function, you can also open several statuses at once and edit one after the other. In order to edit statuses, proceed as follows.

[.instruction]
Editing a status:

. Go to the *Setup » Orders » Order status* menu.
. Carry out the search (material:search[]) to display orders.
. Place a check mark (material:check_box[]) for all statuses that you want to edit.
. Click in the line of a selected status. +
*_Tip:_* If you select several statuses at once, they are all opened and you can edit them one after the other. +
→ The detail view of the status opens. If you have selected several statuses, they are displayed underneath each other and you can switch between the detail views.
. Carry out the desired changes for the *names*, the *colour* or the *visibility*.
. *Save* (material:save[]) the settings. +
→ The changes are applied.


[#1300]
== Searching for orders

The search can either be used to compile all the orders or to find specific orders. A search is not automatically conducted as soon as the menu is opened. The filter for date is set by default to *Order received* and shows the received orders of the last 2 months. All other filter options are initially set to *ALL*. Adapt the filter settings to refine your search. Then conduct the search.

[.instruction]
Searching for orders:

. Go to *Orders » Edit orders*.
. Adapt the filter settings.
. Check, whether the standard setting of the option *Date* and the time period *from to* meet your requirements.
. Click on *Search* (icon:search[role="blue"]) to have the corresponding orders listed.

For example, all orders which are not yet completed will be listed when you search for orders with a status smaller than (<) 7 (outgoing items are not booked yet) and do not set filter for date.

Click on *Reset* (icon:undo[role="orange"]) to reset your filter settings to the default values. Then click on *Search* (icon:search[role="blue"]) again in order to reset the search result as well.

[TIP]
.Search results after changing the order status
====
When you change the order status of orders it can happen that these are not immediately listed in the search results. For example, the status is changed from 6.9 to 7 and when you then search for all orders with status 7 immediately after this, those recently changed might mot be listed. Because of the synchronisation in the background this could take a short time. Just repeat the search after some time to have all orders listed correctly.
====

[#1310]
=== Filtering by IDs and numbers

In order to filter by IDs or numbers, enter a value in the corresponding field. By entering a *Customer-ID* in the corresponding field, only orders of this customer will be shown, for example.

Or, for example, by entering the number 3 in the field *Order ID* only the order with the ID 3 will be displayed. Accordingly, it is an exact and not a fuzzy search . But it is possible to enter several IDs in the field Order ID and thus to search for several orders at once. Only separate the IDs by commas.

[TIP]
.Status search filter
====
If you are searching for numbers or IDs it makes sense not to narrow down the status but set it to *All*. Only those orders are displayed which fulfill all the set criteria. If you cannot find an order despite having entered the exact ID, you might have forgotten to set the filter for *Status* to *ALL*.
====

[#1320]
=== Filtering by customer data, item data or invoice numbers

Using the fields *Customer data* and *Item data* is recommended, when you are looking for a specific customer or item. You can either enter terms or numbers, both is allowed. Besides names, you can also enter postcodes but no telephone numbers, into the *Customer data* field. For a search with *Item data*, the fields item ID, item number as well as name are taken into account, but not the descriptive fields like short description, for example. A search for external invoice numbers is also possible when searching for *Invoice numbers*.

[TIP]
.Only shorten the end of search terms and numbers
====
Quite often it is sufficient to enter only the stem of the word when searching for customers or item data. Just bear in mind that search terms may be truncated almost freely at the end but not the beginning. For example, if you are searching for items with the term packages, you could also enter package or pack. However, searching for ackage would not yield any results. It is the same for all numbers, e.g. postcodes.
====

[#1330]
=== Filtering by order type

Use the filter *Type* to search for the following order types:

* Order
* Credit note order
* Multi credit note
* Return
* Warranty
* Offer
* Advance order
* Delivery order
* Repair
* Multi-order
* Orders, warranties, delivery orders and repairs
* Orders and delivery orders

It is searched only for the selected order type or combination thereof. The filter is set to *ALL* by default, meaning that it will be searched for all order types.

[#1340]
=== Filtering by date

Use the filter *Date* to search for orders that already passed through a specific step of the order processing during the period of time you selected. For this step you can either select *Orders received*, *Incoming payment* or *Outgoing items* in the filter *Date*. After this, choose the start date under *from* and the end date under *to*.
All orders which already went through the chosen step during the selected period of time are displayed. The filter is set by default to *Orders received* and the time period to the last 2 months.
If you do not want to search for orders within the last 2 months, set the required period of time as described above.

[#1350]
=== Filtering by flags

Irrespective of order statuses, you can also assign flags to orders. You can also search for orders by these flags. Flags could be assigned, for example, to problematic orders. This way, someone in charge has to clear them before shipping. This person can search for these orders e.g. once a day by using the filter *Flag*, add information and then reset the flag.

[#1360]
=== Filtering by documents

Use the filter *Document* to search for orders for which a specific xref:orders:order-documents.adoc#[order document] has already been created. You can either search for a specific *document type* or for a document number.
You can also combine these two search criteria and search for an order for which a specific document type with a specific document number has been created. +
The search for *document type* results in an overview of those orders for which this document type has already been created. The search for specific *document numbers* yields more distinct results, i.e. specific documents and their corresponding orders.

[.instruction]
To search for all orders with a specific document, proceed as described:

. Go to *Orders » Edit orders*.
. Select a *document* from the drop-down list in the *Filter*.
. Take into account the *Date* filter, this is set to the last 2 months by default and might need adjustment.
. Click on *Search* (icon:search[role="blue"]). +
→ All orders, for which the chosen document type has already been generated, are displayed in the search results.

[.instruction]
To search for an order which contains a document with a specific number, proceed as described:

. Go to *Orders » Edit orders*.
. Select a *document* from the drop-down list in the *Filter* tab, e.g. *Delivery note*.
. Enter the number of the delivery note into the field *Number*.
. Take into account the *Date* filter, this is set to the last 2 months by default and might need adjustment.
. Click on *Search* (icon:search[role="blue"]). +
→ Only the order to which the delivery note belongs is displayed.

[TIP]
.Selecting a document type not obligatory when searching by number
====
The search for a document number also works when the standard setting for *Document* is not changed, i.e. when no document type is selected. However, if the numbers of different document types are identical, all orders including a document with this number are displayed. This can be the case, if you did not xref:orders:order-documents.adoc#1800[define number ranges], for example.
====

[#1370]
=== Filtering by coupon codes

Search for orders containing coupons by entering the *Coupon code* into the corresponding field. Additionally, you can choose between the options *ALL*, *Redeemed* and *Sold*. *ALL* is set by default. Select *Redeemed* if you only want to search for orders containing already redeemed coupons. When you select *Sold*, you are only searching for orders with which a coupon with integrated coupon codes was sold. Select *ALL* to search for orders containing both, sold and redeemed coupons. The filter only works when a coupon code is entered, even if it is set to *ALL*. In other words, you cannot use this filter to search for all orders containing coupons.

[#1400]
== Setting up the order overview

The following tools help you to easily keep track of and manage the search results. All of your orders are displayed in the menu *Orders » Edit orders*. Here you can see the most important information about each order. You are provided with information about the customer, the order status and the payment status. You can also tell which items are included in the order, whether the outgoing items were booked and whether an invoice was generated. In other words, you can easily keep track of the most important processes without having to open the order. Move the cursor over the icons to see tooltips with additional information. You can find a list of all the symbols with the corresponding explanantions in <<table-symbols-order-overview>>.

Click on an *icon* to open further areas within the order. For example, click on *Calculate stock* to check the current stock of the item or to reorder stock.
Additionally, you can specify how many orders are displayed per page in the order overview. The maximum amount of orders per page is 400, the lowest is 50. +
Use the arrows to switch between pages. You can also enter the required page number directly and press Enter.

Furthermore, use the order overview to change the *status*, the *shipping charges*, the *item data* or the *discount* if required. The information below shows you how to proceed by using the example of how to change the status.

[.instruction]
Changing the order status in the order overview:

. Click on Status. +
→ A drop-down list with all available statuses is displayed.
. Select the required status. +
. *Save* (icon:save[role="green"]) the settings. +
→ The status is updated.

[#1410]
=== Item list in the order overview

The item list is displayed by default in the order overview. Thus, the items included in an order and their most important parameters such as *name*, *size* and *price* are immediately available to you. However, the item list can also be hidden, either for individual or for all orders. To hide the item list of an individual order, use the arrow icon *close item list.* To hide the item list for all orders, proceed as described below.

[.instruction]
Hiding the item lists for all orders:

. Go to *Orders » Edit orders*.
. In the *Filter* tab, select the setting *Do not show* for the option *Stock unit*.
. Click on *Search* (icon:search[role="blue"]). +
→ The item lists will close for all displayed orders.

[#1420]
=== Information and icons in the order overview

Depending on the order’s condition, different icons are displayed in the order overview.
The following table contains an overview of all possible information that could be displayed. Some icons also allow you to perform actions directly. Note, that only those icons are displayed that correspond with the state the order is in.

[[table-symbols-order-overview]]
.Possible icons in the order overview
[cols="1,3a"]
|====
|Tooltip of the icon|Explanation

| *Order status*
|Shows the status the order is currently in. The order status can be adjusted here. In order to do so, click on the status and select the required one. +
*_Important_*: When an order has the status >= 7, the status cannot be changed into a status lower than this without reversing the booking of the outgoing items.

| *Shipping service provider*
|This is an individual icon of the assigned provider. However, an icon is only displayed if you set up flags while creating the xref:fulfilment:preparing-the-shipment.adoc#1000[shipping profile].

| *DHL Packstation*
|This icon is only displayed when the data for the packstation are correctly recorded within the order. When orders originate from markets, it can happen that data for the packstation are incorrect, e.g. if the market does not provide validation. In this case the icon is not displayed because delivery to a packstation cannot take place due to the incorrect data.

| *Shipping method* or +
 *Shipping service provider*
| *Express shipping* is a service which is displayed by an extra icon.

| *Payment method*
|Customised icon of the payment method.

| *Outgoing items booked*
|Is only displayed, when the outgoing items are booked. If only the status was changed to status 7, the icon is not displayed.

| *Dunning level*
|xref:automation:procedure-manager.adoc#intable-dunning-level-procedure-manager[Dunning levels] can be allocated with the procedure manager.

| *Flag*
|Customised mrking of orders.

| *Country of delivery*
|ISO-Code for a country of delivery according to ISO-3166 Alpha 2.

| *Currency*
|ISO-Code of the currency according to ISO 4217.

| *Payment status*
|Corresponding with the status of the payment this is displayed as a coloured bar with an additional tooltip showing the percentage value.

| *Create order confirmation*
|Immediately creating an order confirmation.

| *Generate invoice*
|Immediately creating an invoice.

| *Book incoming payment directly*
|Directly booking the payment of an order. The amount is freely adjustable. The amount still to be paid for the order is preset.

| *Create delivery note*
|immediately creating a delivery note.

| *Book outgoing items*
|Allows to immediately book the outgoing items. This leads to a reduction of stock, if you are keeping stock. The order status automatically changes to status 7.

| *Display tracking URL*
|The tracking URL is used to track a shipment. The xref:fulfilment:preparing-the-shipment.adoc#840[tracking URL] has to be entered and saved when setting up the shipment providers.

| *Create order note*
|Allows you to write a note about an order as well as to read already existing notes. If there is an icon without a plus, there already is a note.

| *Customer notes*
|Allows you to write a note about a customer as well as to read already existing notes.

| *The email address of the customer*
|Allows you to directly write an email to the customer via your email provider.

| *Email service*
|This icon opens the Email templates tab and thus allows you to directly send emails to customers or to read already sent templates.

| *Show existing processes*
|Displays among others a list with returns and credit notes with dates and values.

| *Calculate stock*
|Calculates and opens an overview of your stock of the variations contained in an order. +
Reorders can be done via the shopping cart.

| *Open item list* or *Close item list*
|You can display or hide the item list.

| *Show reorders*
|Opens the reorders for this order in the *Reorder* menu.

| *Invoice number*
|Opens the invoice.

| *Item ID* or *Variation ID*
|Opens the item or the variation in the menu *Item » Edit item*.
|====

[#1500]
== Editing orders

In the menu *Orders » Edit orders*, your orders are listed in the xref:orders:managing-orders.adoc#1400[order overview] as described in the last chapter. As also explained there, some editing options are already available in the overview in order to ensure quick access to often needed functions. In addition, the basic information of an order are accessible at a glance. +
The complete and comprehensive editing options are available when you click on the order ID of the order you want to edit. The selected order opens and the order settings, which are arranged in sub-tabs, are at your disposal. You can edit orders until the first document is created. After this, the order is locked due to legal requirements. +
The settings sub-tabs and their different functions and options are explained in the following subchapters.

[#1520]
=== Opening and editing an order

You open the menu for editing an order by clicking on the header of an order in the overview. The order opens in a new tab. As mentioned above, every order has several sub-tabs that contain data and information. The tabs are described on this page of the manual. Orders that are open can be identified by their *ID* in the tab's title.
Most of the order's tabs do not include a save icon. Settings made in these tabs are saved automatically, e.g. changing the flag or dunning level in the *Overview* tab. You can switch to a different tab or close the order and open it again without losing the changes. However, some tabs include a save icon, e.g. the *Settings* tab. Here, you can switch to a different tab without losing the changes. But you have to save all your changes before closing the order.

[IMPORTANT]
.Default settings for editing orders by variable users
====
In order for variable users to be able to open orders, go to the menu *Setup » Orders » Settings* and save xref:orders:basic-settings.adoc#intable-default-status-return[default statuses] for *returns* and credit notes. No status is saved here as the default setting. Variable users also need to be given the xref:business-decisions:user-accounts-access.adoc#105[right] to edit orders. Go to *Setup » Settings » User » Accounts* in order to carry out the required settings.
====

[TIP]
.Restricted editing options for plentyPOS orders
====
The editing options for xref:pos:pos.adoc#[plentyPOS] orders are restricted to comply with legal requirements. Only a few settings are editable.
====

[#1530]
=== Tab: Overview

The most important order parameters are found in the *Overview* tab. At a glance, you get information about prices, shipping costs, VAT, status, etc.

[TIP]
.Tip: Changing values
====
You can recognise changeable values by a drop-down list or by the appearing *pencil* icon. Click on the pencil icon to edit the required parameters (e.g. image 16, the *Weight* entry in the top left corner).
====

[[table-options-tab-overview]]
.Options in the *Overview* tab of an order
[cols="1,2"]
|====
|Setting|Explanation

| *Order ID*
|ID of the order. The ID is automatically assigned and cannot be changed.

| *Customer ID*
|ID of the customer.

| *Checkout*
|Opens the order in the *My account* area of the online shop.

| *Input*
|The date the order was received, i.e. the date the order was created or imported into the system. The input date can be edited manually as long as no document exists for the order.

| *IP address*
|Displays the customer's IP address if required. +
Go to *Setup » Client » [Select client\] » Order process » Settings* to activate or deactivate the *Purchaser's IP address* option.

| *Flag*
|Assign a flag to an order, if required. Flags are used to categorise orders. This helps you e.g. to find orders with the search filter or to apply automatic functions to them with event procedures.

| *Dunning level*
|Various dunning levels are set here if a customer does not pay for the order. These dunning levels are used for automatic processes within the dunning procedure.

| *Estimated shipping*
|The date for estimated shipping is calculated based on the delivery date for a xref:stock-management:working-with-reorders.adoc#[reorder]. In order for the estimated shipping date to be displayed, both the reorder and the item's delivery date have to be confirmed and the order has to be in *status 4*. +
*_Important_* The option <<#intable-shipped-on, Shipped on>> in the *Settings* tab has a different function.

| *Copy*
|Copies the order and creates a new order with a distinctive ID in a separate tab.

| *Delete*
|Deletes the order. You are asked to confirm your decision. +
The delete icon (icon:minus-square[role="red"]) is not displayed when: +
- Tax relevant documents were already generated for the order. +
- The user is not xref:business-decisions:user-accounts-access.adoc#105[authorised] to delete orders. +
- After outgoing items are booked. +
- A delivery order was created. +
- Child orders exist. +
Generally, orders should not be deleted. Errors can occur when orders are deleted because the orders are linked to items, shipping settings and other functions such as cancellations and returns. However, it is possible to delete newly created orders. If you want to delete an order that has child orders, the child orders have to be deleted first.

| [#intable-splitting-orders]*Split up*
|Splits the order. The behaviour during splitting depends on your xref:orders:basic-settings.adoc#intable-behaviour-after-splitting[basic setting] for this. +
The standard behaviour is that 2 new orders are created when an order is split. The original order is deleted. The shipping costs are recalculated for the new orders. Before splitting the order you are asked how the order items are to be distributed. +
An order can be split when: +
- It is not locked, +
- outgoing items have not been booked yet, +
- no child orders have been created (e.g. returns, delivery orders) +
- no tax-relevant documents have been created and +
- no payments have been assigned to the order yet.+
If you selected the other option *Change of order status* , 2 new orders are created as well. But the original order remains and is assigned a new order status defined by you. With this setting, it is also allowed to split orders with a payment already assigned to it and for which tax-relevant documents (important: invoice as well as reversal document) have been created. The assigned payment as well as the documents remain with the original order and are not transferred to the split orders. +
If you want a different xref:orders:basic-settings.adoc#intable-splitting-behaviour-shipping-costs[behaviour of shipping costs] than the standard described above, you can select a different setting in the basic settings for orders.

| *Return; Credit note; Warranty*
|Click on the drop-down list to create or search for the order document.

| *New order*
|Creates a new order for the customer. Default settings will automatically be used for the order. You may need to change these settings.

| *Invoice address*
|Click on the *small plus* icon to display the invoice address. Additional customer information such as the telephone number, email address and eBay account name are displayed as well.

| *Delivery address*
|Click on the *small plus* icon to display the delivery address. The *delivery address* will be crossed out if it is identical to the invoice address. +
* Click on *New delivery address* to create a new delivery address. Click on *List all delivery addresses* to select a delivery address. +
*Export delivery address* = Exports the delivery address in the format used by the selected shipping service provider.

| *Bank details*
|Click on the *small plus* icon to display and edit the xref:payment:managing-bank-details.adoc#bank-details-customer[customer’s bank details].

| *Customer notes*
|Displays the notes that were saved for this customer. Click on *New note* to create a note about the customer. Existing notes are displayed in yellow in the editing window. New notes are formatted with the familiar editor functions. Notes that are saved here will be displayed in other orders placed by this customer. They will also be displayed in the *Notes* tab within the customer data record.

| *Order note*
|Displays the notes that were saved for this order. Click on *New note* to create a note about the order. New notes are formatted with the familiar editor functions.

| *Status history*
|Displays a list of all the changes of the order's status.

| *Payment history*
|Shows details about payments such as payment method, currency, payment ID or date.

| *Stock units*
|Displays information about the stock units included in the order.

| *Edit*
|Allows you to edit the item data if required, e.g. item quantity, item details, prices, discounts and VAT rates.

| *Add*
|Use the integrated item search to add other items to the order as required.

| *Assign storage location*
|Assigns a storage location to the stock units. If more than one storage location is saved for an item, then the storage locations will be given priority based on their positions. If no storage location was saved, then the *standard storage location* will be assigned. +
The assignment of a storage location is especially important for pick lists and packing lists. +
_Tip_: You can also use xref:automation:event-procedures.adoc#[event procedures] to assign storage locations to items.

| *Delete assignment*
|Deletes the current storage location assignment. Click on *Assign storage location* again (see above) to create a new assignment that is better suited to the current warehouse situation.
|====

[#1540]
=== Tab: Settings

An order’s basic parameters are saved in the *Settings* tab, e.g. the *Status*, *Referrer* or the *Payment method*.

[[table-options-tab-settings]]
.Options in the *Settings* tab of an order
[cols="1,2"]
|====
|Setting |Explanation

| *Status+*
|The status of the order. If required, the status can be adapted by using the dropdown list. +
Note that the order status *[7] Outgoing items booked* cannot be changed to a lower status. This is because the items have already been shipped. However, if you still want to do this, then you first need to reset the outgoing items that were booked. It is possible to switch to a lower order status afterwards.

|*Order type*
|The order type of the order is displayed. You can change the order type manually by using the drop-down list.

|*Owner*
|The owner of the order is displayed. You can change the owner type manually by using the drop-down list. +
The note *Missing owner right order* is displayed if the owner does not have the needed xref:business-decisions:user-accounts-access.adoc#40[owner rights]. Go to the menu *Setup » Settings » User » Account* and select that the module Order is available to this user as an owner. +
In case the owner of the order does not have a plentymarkets user account, the note *Unkown user* is displayed. If needed, you can create a xref:business-decisions:user-accounts-access.adoc#10[user account] for this user.

|*Referrer*
|The referrer of the order is displayed. You can change the order referrer manually by using the drop-down list.

|*Location*
|The location of the order is displayed.

|*Language*
|The language of the order is displayed. Order documents as well as emails are generated in the order language. The language is editable. +
Note that for the generation of order documents and emails in different languages, the corresponding templates have to be created first.

| *Warehouse*
|The warehouse or main warehouse of the order item. If required, click on *Stock correction* to change the warehouse. +
*_Important_*: The option *Stock correction* synchronises the data displayed in the *Settings* tab of the order with the warehouse saved for the order items included in the order. The option is only available when you selected *b) a warehouse can be assigned for each order item* as a xref:orders:basic-settings.adoc#intable-warehouse-assignment[basic order setting] in the *Setup » Orders » Settings* menu. If you manually change the warehouse assigned to an order item and the changed warehouse is not automatically visible in the *Settings* tab of the order, click on *Stock correction* to update the display of the warehouse.

| *Outgoing items*
|Indicates whether outgoing items were booked and displays the corresponding date. +
Click on *Book outgoing items* (terra:order_sent[]) to manually book the outgoing items, if required.

| [#intable-shipped-on]*Shipped on*
|This is the *shipping date* that was saved in the item data record. As such, this option is relevant for xref:orders:managing-orders.adoc#1100[advance orders]. If the order includes several items that were all ordered in advance, then the date that is farthest in the future will be displayed here. The date can be changed manually.

| *Return date*
|Save the date of a return if an item was returned. Serves as information about a return, so that the return does not have to be opened separately.

| *Currency*
|The currency of the order. By clicking on *Edit* (icon:pencil[role="yellow-background"]) you can change the currency and enter an exchange rate if needed.

| [#intable-payment-terms-order]*Terms of payment*
|Enter values for *Payment due (days)*, *Value date (days)*, *Early payment discount (days)* and *Early payment discount (%)* to create your terms of payment. *_Important_*: If you want to use value date and early payment discount, you must enter a payment due. If there is nothing or the value 0 entered for payment due, the payment terms will not be transferred to documents. +
If the values were already saved in the xref:crm:edit-contact.adoc#details-individual-areas[customer data], they will be taken from there and automatically be displayed here. The customer data have priority. If nothing is saved in the customer data, the customer classes are checked. If values are defined in a xref:crm:preparatory-settings.adoc#create-customer-class[customer class], these are then transferred to the payment terms of the order. If no values are defined in either the customer data or the customer class, the payment terms fields of the order are left empty. +
On the order, the payment terms can manually be entered or updated. This can be done regardless of where they are taken from or of whether there are values preselected at all. +
The values entered on the corresponding order are transferred to the order documents. Note also the xref:orders:order-documents.adoc#intable-payment-terms-documents[document settings] for this. The payment terms can be displayed on the order documents xref:orders:generating-invoices.adoc#[invoice], <<orders/order-documents/generating-pro-forma-invoice#, pro forma invoice><, xref:orders:generating-order-confirmations.adoc#[order confirmations] as well as xref:orders:generate-offer.adoc#[offer]. +
*_Important_*: The payment terms will only be displayed on these documents if the corresponding order was paid with the payment method xref:payment:invoice.adoc#[Invoice] or the payment method xref:payment:cash-in-advance.adoc#[Cash in advance].

| *Shipping service provider*
|The shipping service provider that will ship the items for this order is displayed. The shipping service provider is determined via the shipping profile and entered automatically. Changes can be done by adapting the shipping profile.

| *Shipping profile & shipping charges*
|The shipping profile and shipping costs for the order are displayed. To edit the shipping profile, click on *Edit and recalculate* (icon:cog[]). If required, the shipping charges can also be edited manually.

| *Ext. order number*
|Enter the external order number for orders that are imported from an external system.

| *Customer reference*
|If the *Your reference* field is visible to customers during the order process, then any text that a customer entered into this field will appear here.

| *Packages*
|Number of packages belonging to this order. +
*_Important_*: This entry is not linked to the number of packages set in the Shipping centre. If you want to edit the number of packages, do so in the Shipping centre.

| *Package number*
|Package number of the shipping package. By clicking on *Add* (icon:plus-square[role="green"]), you can enter a package number. +
If a package number was saved, then the *preview* (icon:eye[role="blue"]) can be used for tracking the package. However, this can only be done if a corresponding tracking URL was saved in the *Setup » Orders » Shipping » Shipping options » Tab: Shipping service provider* menu for this xref:fulfilment:preparing-the-shipment.adoc#[shipping provider]. Otherwise, the preview icon will not be visible.
|====

[#1550]
=== Tab: Email

The *Email* tab contains all of the xref:crm:sending-emails.adoc#[email templates] that were configured in the menu *Setup » Client » [Select client] » Email » Templates* and that were set up as a type of template that is visible for orders. You can manually send these email templates to customers. This is useful if you unexpectedly need to send an email to a customer, i.e. an email that is not sent with an automatic procedure. Proceed as described below to send an email template.

[.instruction]
Sending an email template:

. Go to *Orders » Edit orders*.
. Open the order.
. Click on the Email tab.
. If required, select the language.
. Click on the *Email templates* tab and select the tab that contains the required email template.
. Select the required template.
. Click on *Direct Emailing*. +
→ The email is sent.
. Wait until you see a message confirming that the process was completed.

Check the xref:crm:sending-emails.adoc#100[login details] if the email was not sent correctly. Go to *Data » API log (deprecated)* and use the *Email* process to see the corresponding error messages.

[IMPORTANT]
.Sending customers a new password
====
The email template *Send customer a new password* cannot be sent from within an order. If you want to send this email template, then do so from within the customer's data record. Click on the *Settings* tab there. You will be able to see the *Password* tab when a customer has registered in the online shop. This is where you can send the email template.
====

The *Emails sent* tab provides an overview of all the email templates that were sent. You can see the *date*, *recipient* and name of the *email template* as well as the *order ID*. You can see all of the emails sent to the customer, even those from other orders.

[#1560]
=== Tab: Payment

Click on the Payment tab to see all payments and partial payments belonging to the order. Use the filters to search for specific payments of the order. In the *Payments* tab you can see the total invoice amount, the amount paid and the amount that is still pending. Thus, you get a comprehensive overview. Moreover, you can use the *Book payment* icon in this tab to manually book payments.

[TIP]
.Missing incoming payments
====
If there are payments missing in the overview, change the *Received from* filter to adjust the point of time from which on payments should be displayed.
====

Find more detailed information about how to xref:payment:beta-managing-payments.adoc#[manage payments] in the manual.

[#1570]
=== Tab: Receipts

Create receipts in the *Receipts* tab, e.g. an order confirmation, a delivery note or an invoice.
Once you have created documents for an order you can no longer edit the input date of the order.
The documents are created with the help of xref:orders:order-documents.adoc#[document templates]. Check the document templates to make sure that the settings are right before you create receipts. Check the templates also if you receive an error message.

[TIP]
.Tip: Copying document templates
====
If you want to create a xref:orders:order-documents.adoc#300[document template] quickly, then simply copy a previously configured document template and make changes to the template as needed.
====

The receipts are configured before they are created. You can specify different parameters for each receipt. For example, for an invoice, you can enter the date or decide whether the outgoing items should be booked when the invoice is created. Furthermore, you can decide whether the status of the corresponding order is changed as soon as the receipt is created.

*_Note_* that created documents cannot be deleted, only external documents. You cannot reverse the creation of a document. For some documents, for example invoices, credit notes or dunning letters, reversal documents can be created. This ensures the traceability and unalterability of invoice documents. +
However, it is possible to archive documents. Archiving documents enables you to create these documents again. To do so, click on *Archive* (terra:receipt_archive[]). The archived documents can be found in the *Archived documents* tab within the *Receipts* tab. Exempt from this are documents for which a reversal document has to be created, as mentioned above. Archiving documents cannot be reversed. Once a document is transferred to the archive tab, they cannot be moved back.

[IMPORTANT]
.Obligation to keep records
====
Note that there is an obligation to keep records. Therefore, make sure that all your documents and recored are saved and stored at regular intervals.
====

[#1580]
=== Tab: Customer

By clicking on the *Customer* tab, the xref:crm:edit-contact.adoc#details-individual-areas[contact data record] opens. These information are editable.

[#1590]
=== Tab: Tickets

The customer's xref:crm:using-the-ticket-system.adoc#[tickets] are displayed in the *Tickets* tab. You can edit these tickets directly without having to switch to the ticket system.

[#1600]
=== Tab: Orders

Other orders that were also placed by this customer are displayed in the *Orders* tab. All the customer’s orders can be edited here.

[#1610]
=== Tab: Stock

The *Stock* tab displays the xref:stock-management:managing-stocks.adoc#[stock data] for all of the items that are included in the order. All of the functions of the *Stock* menu are available in this tab with the exception of the filter functions. You can view stocks and configure them as needed.

[#1620]
=== Tab: Reorder

Select the order items for a reorder in the *Reorder* tab (image 7). Choose whether a reorder is only created for this specific order or whether you want to create a reorder to which items can be added from other orders as well. +
In both cases, the items have to have the same supplier and warehouse. If this does not apply, a separate reorder will be generated for each supplier/warehouse combination.

A supplier has to be saved for every variation. Otherwise it is not possible to place a reorder.

[#1630]
==== Selecting order items

Proceed as described below to select individual items or all items from an order for the reorder.

[.instruction]
Selecting specific items for the reorder:

. Go to *Orders » Edit orders*.
. Open the required order.
. Click on the *Reorder* tab.
. Select the *variations* you want to reorder.
. Click on *Reorder selected items*. +
→ A general, extendible reorder is generated into which the selected items from the current order as well as those from other orders are transferred if they were selected via this button. The quantity of each variation is displayed in the *Quantity* column.

If you selected specific items for the reorder, the *Reorder all items* button is deactivated and can no longer be selected.

[.instruction]
Selecting all items for a reorder:

. Go to *Orders » Edit orders*.
. Open the required order.
. Click on the *Reorder* tab.
. Click on *Reorder all items*. +
→ A reorder containing all items from this order is generated only for this order. The quantity of each variation is displayed in the *Quantity* column.

[#1640]
==== Placing a reorder

[TIP]
.Information listed under Quantity
====
Listed in the *Quantity* column are the delivered quantity (green numbers), the pending quantity (red numbers) as well as the ordered quantity (white numbers). +
Partial quantities are displayed as *delivered* if they are booked as a partial delivery in the reorder under *Status*. +
====

Place the reorder after you have selected the order items. Proceed as follows:

[.instruction]
Placing a reorder:

. Click on the *shopping cart* (icon:cart-plus[role="green"]) in the *reorder* tab of the order. +
→ The *Reorder* menu opens. Find out which items are included in a reorder by clicking on the *Base* tab and then opening the *Item data* submenu.
. Open the *Basic date* submenu and click on the *gear-wheel icon* (icon:gear[role="darkGrey", stack="long-arrow-right,darkGrey", , stackPosition="lr"]) next to the *Order* option. +
→ The order is placed. The order data are also displayed the *Reorder* tab of the order.

[TIP]
.Adjust the purchase price and quantity
====
Open the *Item data* submenu within the *Base* tab and make changes to the options *Purchase price* and *Quantity* before placing the reorder.
====

For further information about editing a reorder, e.g. booking partial quantities, refer to the xref:stock-management:working-with-reorders.adoc#[Reorders] page of the manual.

[#1650]
==== Increasing the number of variations in a reorder

You can increase the quantities of variations in reorders as long as the reorder is still open. This is possible for values where percentages were saved during the xref:item:attributes.adoc#200[distribution]. Proceed as follows to increase the quantities of variations:

[.instruction]
Increasing the quantities for variations:

. Select the order for which you want to edit the reorder.
. Open the order's *Reorder* tab.
. Click on *Increase quantities for variations*.
. Select the *reorder ID* and the *item* from the drop-down lists.
. Select the *attribute* and the *value*.
. Enter the *quantity*.
. Click on *Increase quantity*.
. Repeat these steps for every variation for which you want to increase the quantity.

[#1660]
=== Tab: Delivery

xref:orders:managing-orders.adoc#300[Delivery orders] are created in the *Delivery* tab. There you can see the order's stock units, which were not yet transferred to delivery orders.

[.instruction]
Creating delivery orders manually:

. Go to *Orders » Edit orders*.
. Open the required order.
. Click on the Delivery tab.
. Enter the quantity that should be transferred to the delivery order in the field DelOrdQua (quantity to be transferred to the delivery order). +
→ The quantity entered for *DelOrdQua* must not exceed the quantity entered for *Unass.Quantity* (unassigned quantity).
. Click on *Create delivery order* (terra:execute[]) to create the delivery order.

[TIP]
.Automatically generating delivery orders
====
Click on *Generate delivery orders automatically* to create the delivery orders. They will be created according to the selected settings under *Settings » Orders » Order types » Delivery order* in the Split up orders into delivery orders by drop-down list. All of the order items will be transferred and distributed to delivery orders. You can only use this function if no delivery order exists for the order yet.
====

When creating a delivery order, the stock reservation for the quantity included in the delivery order is transferred from the main order to the delivery order. If delivery orders are created individually and items are still available in the main order, then these items are also reserved.

[TIP]
.Tip: Editing order items in the main order
====
Order items can be added to or deleted from the main order. However, you can only delete order items from the main order if they are not included in the delivery orders. Thus, you can increase or reduce the item quantity included in the main order. However, you should only delete quantities that are not assigned. It is technically possible to delete order items that are already included in a delivery order, but you should avoid doing so.
====

[#1670]
=== Reversing and correcting an invoice

Create a reversal document if you or your customer notice an incorrect information on an invoice and you subsequently want to correct it. Create a new invoice after this.
Reversing an order makes it easy to follow up on changes because the old invoice, the reversal document for the invoice and the new invoice are all available. Use the order status *cancelled* if you want to cancel the entire order. Use the reversal document if you want to edit the order and want to correct some of the information. +
Note that an invoice can only be reversed if no dunning letter exists for the corresponding order. In this case, the dunning letter has to be reversed first. To do this, use the xref:orders:generating-dunning-letters.adoc#400[reversal dunning letter].

[#1680]
==== Setting up a reversal document template

Set up a template for the reversal document first. The fastest way to set up the template is to apply the settings from the default document template or to copy the settings from the invoice document template. +
The following steps briefly describe how to apply the settings from the default document template.

[.instruction]
Setting up the template:

. Go to *Setup » Client » [Select client] » Locations » [Select location] » Documents » Reversal document invoice*.
. Click on the *Transfer* tab.
. Click on *Accept* under *Apply the settings from default document template* (icon:gear[role="darkGrey", stack="long-arrow-right,darkGrey", stackPosition="lr"]).

Since the information in a reversal document is identical with the information included in an invoice, further information on the required settings can be found on the xref:orders:generating-invoices.adoc#[invoice] manual page.

[#1690]
==== Correcting an invoice:

You correct an invoice by reversing it. The reversal of an invoice is used for a transparent correction of relevant invoice data and not for the reversal of the order itself. Once the reversal document was created, the order settings are unlocked and can be edited and a new invoice can be created as well.

[.instruction]
Correcting an invoice:

. Go to *Orders » Edit orders*.
. Open the order of which you want to reverse the invoice.
. Click on the *Receipts* tab.
. Select the option *Reversal document* from the *Create receipt* drop-down list. +
→ A new window with optional settings opens.
. *Save* (icon:save[role="green"]) the settings. +
→ The reversal document is generated and the settings unlocked.
. Edit the data you want to correct. +
→ For example, add a VAT number.
. Click on the *Receipts* tab.
. Select the option *Invoice* from the *Create receipt* drop-down list. +
→ A new window with optional settings opens.
. *Save* (icon:save[role="green"]) the settings. +
→ The invoice is generated and the settings are locked.

[#1700]
=== Using group functions

You can use the *Group function* to carry out processes for several orders at the same time. This means that processes, such as a status change or an email service, will be applied to all selected orders. The group function is particularly recommended if you need to edit a large number of orders and it would be too time consuming to edit each one individually. Proceed as follows to process several orders at once with the group function.

[.instruction]
Applying the group function:

. Use the xref:orders:managing-orders.adoc#1300[search] to search for the orders you want to process with the group function.
. Select (icon:check-square[role="blue"]) orders.
. Click on *Group function* above the order overview. +
→ The window *Group function* wit further settings opens.
. Select (icon:check-square[role="blue"]) the group function you want to apply to the selected orders.
. If needed, set further settings for the group function.
. Click on *Anwenden* (terra:execute[]) above the group functions. +
→ The selected group function is applied to the selected orders.

[[table-group-functions]]
.Group functions for orders
[cols="1,2"]
|====
|Setting |Explanation

| *Group orders*
| By using this group function you group the selected separate orders into one new order. The behaviour for grouping depends on your xref:orders:basic-settings.adoc#intable-behaviour-after-grouping[basic setting] for this. The standard behaviour is that the original orders are deleted. Shipping costs are recalculated for the new order. Orders can be grouped when: +
- They are not locked, +
- outgoing items have not been booked yet, +
- no payments have been assigned to the order yet, +
- it has no tax-relevant documents, +
- they have the same plentyID, +
- they are of the same order type, +
- they have the same referrer, +
- they have the same owner, +
- they have the same  contact, +
- they have the same address, +
- they have the same payment method, +
- they have the same currency and exchange rate. +
If you selected the other option *Change of order status* , a new order is created by grouping as well. But the original orders remain and are assigned a new order status defined by you. With this setting, it is also allowed to group orders with payments already assigned to them and for which tax-relevant documents (important: invoice as well as reversal document) have been created. The assigned payments as well as the documents remain with the original orders and are not transferred to the split orders. +
Regardless of the chosen setting, shipping costs are recalculated for grouped orders and order notes are copied to the new order as well.

| *Email service*
| By using this group function you send an email to either customers or the warehouses of the selected orders. To do so, select a *Recipient*, a *Template* and optionally a *Flag* from the drop-down lists. Make sure that you have set up an xref:crm:sending-emails.adoc#1200[email template].

| *Change flag*
| By using this group function you change the flag of the selected orders. To do so, select the flag to be assigned to the orders from the drop-down list.

| *Change status*
| By using this group function you change the order status of the selected orders. To do so, select the xref:orders:managing-orders.adoc#1200[order status] to be assigned to the orders from the drop-down list.

| *Change shipping profile*
| By using this group function you change the shipping profile of the selected orders. To do so, select the xref:fulfilment:preparing-the-shipment.adoc#1000[shipping profile] to be assigned to the orders from the drop-down list. You can also set and activate (icon:check-square[role="blue"]) additional *Shipping costs*.

| *Change owner*
| By using this group function you change the owner of the selected orders. To do so, select the owner to be assigned to the orders from the drop-down list.

| *Book outgoing items*
| By using this group function you book the outgoing items for the selected orders. To do so, select the date and the time when the booking is to take place. As soon as the items are booked, the order status of those orders changes to *7 - Outgoing items booked*.

| *Set delivery date*
| By using this group function you set the delivery date for order items. Set the delivery date with the date picker.

| *Set shipping date*
| By using this group function you set the shipping date for an order. Use the date picker to set this date. You can find the date *Shipped on* in the *Settings* tab of the detail view of an order.

| *Newsletter*
| By using this group function you can add a newsletter to an order. This newsletter is then sent to the customers of these orders. Make sure that you've set up a xref:crm:sending-newsletters.adoc#[newsletter] beforehand.

| *Transmit to atriga (debt collection)*
| This group function is no longer usable.

| *Create leads*
| This group function is no longer usable.

| *Reverse outgoing items*
| By using this group function you can reverse the already booked outgoing items for the selected orders, e.g. for returns. Note that the order status also changes by reversing the booking.

| *Delete*
| By using this group function you delete the selected orders. Make sure to check whether the selected orders should and can really be deleted. Generally, orders should not be deleted. Errors can occur when orders are deleted because the orders are linked to items, shipping settings and other functions such as cancellations and returns. However, it is possible to delete newly created orders. The following points prevent deletion of orders:  +
- Tax relevant documents were already generated for the order. +
- The user is not authorised to delete orders. +
- After outgoing items are booked. +
- A delivery order was created. +
- Child orders exist. Before a main order with child orders can be deleted, the child orders have to be deleted first.

|====

[IMPORTANT]
.Applying group functions
====
Always make sure that you've selected the right orders before applying any of the group functions. Also note that some of the changes to orders can affect the further order processing or that automatisms such as event procedures or processes could be triggered, e.g. an order status change.
====

[.discrete]
==== Examples

Below, you can find two examples how to work with group functions. Example A describes how to book outgoing items for several orders at once. Example B describes how to inform customers about the availability of an item.

[.instruction]
*Example A*: Booking outgoing items with a group function

. Go to *Orders » Edit orders*.
. Select the *orders* for which you want to book outgoing items with a group function.
. Click on *Group function*.
. Select the option *Book outgoing items*.
. Select the *date* and the *time*. +
→ The current date and time are selected by default. However, both, date and time are adaptable. You are required to select a date and time to use this group function.
. Click on *Apply* (terra:execute[]) to carry out the procedure.

[TIP]
.Default settings for editing orders by variable users
====
In order for variable users to be able to open orders, go to the menu *Setup » Orders » Settings* and save xref:orders:basic-settings.adoc#200[default statuses] for *returns* and credit notes. There is no default status saved for *returns* and *credit notes*.
Variable users also need to be given the xref:business-decisions:user-accounts-access.adoc#105[right to edit orders]. Go to *Setup » Settings » User » Accounts* in order to carry out the required settings.
====

[.instruction]
*Example B*: Informing customers about item availability with a group function

*Initial situation*: A highly demanded item in your plentyShop is temporarily out of stock but you you already received quite a few orders for this particular item. Usually, there is nothing sellers can do about such delivery delays, but the customers have to be informed as soon as possible about the delay.

. Go to *Orders » Edit orders*.
. Search (icon:search[role="blue"]) for the *orders* about which you want to send information to customers. +
→ Search with the help of the *Item ID* or the *Item name* all orders with the status *ALL < 7* because your process is only relevant for orders which have not outgoing items booked yet.
. Select the orders which are displayed after the search.
. Click on *Group function*.
. Select the option *Email service*.
. Select a *Recipient*, a *Template* and optionally a *Flag*. +
→ Make sure that you set up an xref:crm:sending-emails.adoc#1200[email template] first. That way you can now select it here for the group function.
. Click on *Apply* (terra:execute[]) to carry out the procedure. +
→ The email is sent to the customers.

[TIP]
.Status &gt;= 7
====
Note that an *order status &gt;= 7* cannot be set to a lower status without reversing the booking of outgoing items first. For orders with status 7 or higher, you first have to reverse the *outgoing items* by using a group function.
====

[#1800]
=== Check list for sales prices

Use this check list if you want to edit order items and encounter problems. In most cases this is because the details of the order don’t match the settings of the sales prices.

Therefore, check if the following settings in the *Setup » Item » Sales prices* menu are selected for the respective price:

[%interactive]

* [ ] *1* is set for *Minimum quantity*.
* [ ] The *Currency* the order is in is activated for this price.
* [ ] No *Price type* is activated for this price, i.e. neither RRP, Special offer nor Set price is selected.
* [ ] The *Client* of the order is activated.
* [ ] The required *Customer class* is activated if it is set in the system.
* [ ] The *Country* where the order originated is activated.
* [ ] In the *Referrer* list, *Manuelle Eingabe* (manual input) is activated.
* [ ] The corresponding *Referrer* of the order is activated.

If you could place a check mark next to these options, you should be able to edit the order items. In case you are still encountering problems, you can find more detailed information about sales prices in the manual under xref:item:prices.adoc#[Sales prices and price calculation] or you can ask our supporters in the link:https://forum.plentymarkets.com/[Forum].
