= Manually creating orders
:keywords: create orders manually, create orders from contact, manual order entry
:author: team-order-core
:description: Learn how to manually create orders or offers in three steps. You can do this via cash sales, orders or contacts.

//adjust links to new pages where possible (auftragsdokumente once this has been moved)

This page describes how you can create orders in the system, e.g. if an order is placed during a phone call. In plentymarkets, the following methods are available for creating orders:

* Via a <<#create-order-via-cash-sale, cash sale>>
* Via <<#create-order-via-order, orders>>
* Via <<#create-order-via-contact, contacts>>

*_Tip:_* The approach for offers is identical. In the first step of the order creation, select the option *offer* in the *order type* setting to create an offer.

[IMPORTANT]
.Sending emails
====
When you manually create orders, no emails will automatically be sent to the customer. The reason that no emails will be sent is that your system does not know when you are done with all settings for a manual order. Send xref:crm:emailbuilder.adoc#[emails] manually by using the *Email service* function in an order.
====

[#create-order-via-cash-sale]
== Creating an order or an offer for a cash sale

When you open the *CRM » Contacts* menu you can register cash sales using the customer profile *Cash sale*. The customer profile named *Cash sale* allows you to assign orders without having to assign them to a customer. The customer profile *Cash sale* is set up in your system by default.

[WARNING]
.Payment method and order documents for cash sale
====
Make sure to select the correct *payment method* in the *order data* when creating an order for a cash sale. When manually creating a cash sale order the order will not be assigned to a customer saved in your system. This is why you should manually generate the required xref:orders:order-documents.adoc#[order documents] such as the invoice right away while entering and processing the cash sale. Order documents can be generated in the *Documents* tab of the order.
====

[.instruction]
Creating an order or an offer for a cash sale:

. Go to *CRM » Contacts*.
. Enter the desired ID in the *ID* search field. +
→ A list of all search results is displayed.
. Select *Cash sale* from the *results*. +
→ The customer profile for cash sale opens.
. Go to the *Orders* area.
. On the right, click on *Options* (material:add[]).
. Select the option *New order* or *New offer*. +
→ The overview for creating a new order or a new offer opens.
. Carry out the settings. Pay attention to the information about <<#create-order-or-offer, creating orders or offers>>.

[#create-order-via-order]
== Creating an order or an offer via orders

In the *Orders » Orders (Test phase)* menu, you can create new orders or offers in the order overview as well as in the detail view of an order. To do so, proceed as follows.

[.instruction]
Creating an order or an offer via orders:

. Go to *Orders » Orders (Test phase)*.
. Carry out the search (material:search[]) to display orders.
. In the side navigation on the left, click on (material:add[role=skyBlue]) *New order*. +
*_Tip:_* If you want to create an offer instead of an order, select the *order type* *offer* in the first step. +
icon:map-signs[] *_Or:_* In the order overview, open the order of the customer for which you want to create a new order.
. Click on the *Contact ID* at the bottom of the page navigation. +
The order opens in the *CRM » Contacts* menu.
. Go to the *Orders* area.
. On the right, click on *Options* (material:add[]).
. Select the option *New order* or *New offer*. +
→ The overview for creating a new order or a new offer opens.
. Carry out the settings. Pay attention to the information about <<#create-order-or-offer, creating orders or offers>>.

[#create-order-via-contact]
== Creating an order or an offer via contacts

You can also create orders or offers via the contact overview or the detail view of a contact in the *CRM » Contacts* menu. To do so, first carry out the <<#carrying-out-standard-settings, default settings>>.

[.instruction]
Creating an order or an offer via contacts:

. Go to *CRM » Contacts*.
. Search for the contact by means of the filter settings. Note the explanations about the filters on the xref:crm:search-contact.adoc#[Searching for a contact] page. +
→ The contacts that match the search criteria are displayed.
. On the right in the line of the contact, click on material:more_vert[].
. Navigate to material:shopping_cart[] *Orders* > *New order* or *New offer*. +
icon:map-signs[] *_Or:_* Open a contact.
. In the *Orders* section on the right, click on material:add[] *Options*.
. Navigate to *New order* or *New offer*. +
→ You are automatically redirected to the order details of the new order or offer.
. Carry out the settings. Pay attention to the information about <<#create-order-or-offer, creating orders or offers>>.

[#carrying-out-standard-settings]
=== Carrying out default settings

When creating orders or offers via the contact overview, data such as addresses or clients are taken directly from the contact data if they are deposited there. Thus, in most cases contact data have priority. Additionally, some default settings, which are a fallback if the data are not deposited in the contact, are available. +
In order to optimise the order creation, these default settings should be determined first. +
*_Note:_* The default settings also apply to offers that are created via the contact UI.

[.instruction]
Carrying out default settings:

. Go to *Setup » Orders » Order types » Sales order*.
. Carry out the settings. Pay attention to the explanations given in <<table-default-settings-order-contact>>.
. *Save* (material:save[role=green]) the settings.

[[table-default-settings-order-contact]]
.Default settings for the order creation
[cols="1,3"]
|===
|Setting |Explanation

|[#intable-default-owner]*Default owner*
|Select a default owner to be preselected in the order details when creating a new order or a new offer. The owner is not taken from the contact data.

|[#intable-default-client]*Default client*
|The default client selected here is preselected in the order details when creating an order or an offer if no client is set in the contact. If a client is set in the contact data, this client takes priority.

|[#intable-default-referrer]*Default referrer*
|The default referrer selected here is preselected in the order details when creating a new order or a new offer if no referrer is set in the contact. If a referrer is set in the contact data, this referrer takes priority.

|[#intable-default-warehouse]*Default warehouse*
|The default warehouse selected here is preselected in the order details when creating an order or an offer if no warehouse is set in the contact. If a warehouse is set in the contact data, it has priority.

|[#intable-default-template]*Default order template*
|If you select an <<#create-and-apply-order-templates, order template>> as the default order template, this template is preselected for the new order or offer by default. The values of the selected order template are automatically applied to the order or offer. You can only select order templates that have already been created. +
The option *No order template preselected* is set by default. If you select an order template as the default and this template is deleted at some point, the default setting returns to *None*.

|[#intable-endpoint-after-completion]*Endpoint after completing an order*
|Select the location in the system you want to be directed to after creating the order. You can choose between: +
*Current overview* = Forwards you to the order overview in the contact data record of the contact for which you created the order. This is the default setting. +
*Order overview* = Forwards you to the general order overview. +
*Detail view of the new order* = Forwards you to the detail view of the order you have just created.

|*Filter option ‘Only display items in stock’ is preselected in item search*
|Activate this option if you want it to be preselected in the item search. It means that only items with physical stock are displayed in the item search.

|*Filter option ‘Only display sales warehouses’ is preselected for the item search*
|Activate this option if you want it to be preselected in the item search. It means that only items stored in sales warehouses are displayed in the item search.

|*Filter option ‘Only display active items’ is preselected in item search*
|Activate this option if you want it to be preselected in the item search. It means that only xref:item:checklist-items-visibility.adoc#100[activated items] are displayed in the search results.

|*Filter option ‘Only display items with valid price’ is preselected in item search*
|Activate this option if you want it to be preselected in the item search. This means that only items for which a valid price is saved are displayed in the item search.

|*Allow changing the VAT rates in the items overview table in the last step of the order creation*
|By activating this option, you allow that VAT rates can be changed before finishing creating the order in the last step of the order creation. The VAT rates depend on the delivery address of the order. +
This option is deactivated by default. If you only want to display the VAT rates in the overview and not edit them, do not activate the toggle.

|*Display of added items in the shopping cart*
|Select how items are added to the shopping cart. The default setting is *As one order position, quantities of order items are increased*. +
*As separate order positions* = Identical items are added separately, meaning that each item is displayed in a separate row. +
*As one order position, quantities of order items are increased* = Identical items are added as one order item, only the quantities are changed accordingly.

|*Redetermine prices only in the shopping cart in the order creation*
|By activating this option, you determine that item prices are only recalculated when they are placed in the shopping cart. By default, prices are already determined during the item search when creating an item and can be selected there.

|===

[#create-order-or-offer]
== Creating an order or an offer

No matter which of the described options you choose - the creation of a new order or offer is always carried out in three steps. In a first step, <<#step-one-basics, order details are entered>>, in the second step, <<#step-two-add-items, order items are added>> and in the third step, the <<#step-three-summary, order is completed>>. First of all, select the contact for which the order or offer is to be created.

Above the order details, you can also choose between an order or an offer afterwards. In addition, you can select an optional <<#create-and-apply-order-templates, order template>> from the drop-down list to apply the template to this order. By default, no order template is selected.

The steps described in the following chapters are the same for orders and offers.

The user interface is designed so that orders can be created quickly and easily. This is especially helpful when orders are telephoned in. First, the order details such as addresses and payment method are entered. After that, order items are added and the last step is the final check and completion of the order.

[TIP]
.Contact name, ID and rating at a glance
======
At the bottom left in the order creation's footer, you can see the name, the ID and the rating of the contact.
======

[#step-one-basics]
=== Step 1: Order details / Offer details

If the new order or the new offer is created from the contact overview, some information are transferred from the contact data to the order or offer details. Which information is transferred depends on the data saved in the contact. Otherwise, the <<#carrying-out-standard-settings, default settings>> apply. Also note <<#table-order-details-new-order, this table>>.

[[table-order-details-new-order]]
.General settings
[cols="1,3"]
|====
|Setting |Explanation

| *Order type*
|Select from the drop-down list whether you want to create an *order* or an *offer*.

| *Order template*
|Select a template from the drop-down list.

| *Contact*
|If you create the order from the *CRM » Contacts* meu, the name of the contact is already preselected. If you want to select another contact, enter at least 3 letters in order to see suggestions. Alternatively, you can also enter the contact’s email address. All data that is saved on the contact will be automatically added to the input fields. +
*_Tip:_* If you want to create a guest order, select the option *Guest* from the drop-down list and add a new *invoice address* as well as a new *delivery address*.

2+^| *Order details*

| *Invoice address*
|The invoice address is taken from the contact data. If there is more than one address, the one saved as the primary invoice address is taken. If no invoice address is saved as the primary address, you can select the right address from the drop-down list. +
Use the preview (material:visibility[]) to access the contact data record directly. The already carried out settings in the order details will remain. +
If you create a *guest order*, add a new invoice address.

| *Delivery address*
|If you select the option *As invoice*, the invoice address is automatically entered as the *delivery address* as well. Otherwise, the delivery address is taken from the contact data. If there is more than one delivery address, the one saved as the primary delivery address is taken. If no delivery address is saved as the primary address, you can select the right address from the drop-down list. +
The dropdown-list also offers the possibility to create a new delivery address which is then saved in the contact data. For further information, see the expandable box at the end of this section. +
Use the preview (material:visibility[]) to access the contact data record directly. The already carried out settings in the order details will remain. +
If you create a *guest order*, add a new delivery address.

| *Payment method*
|If a payment method is defined for the contact, for example in a xref:crm:preparatory-settings.adoc#create-customer-class[customer class], this is preselected. Otherwise you can enter a payment method and select it. All payment methods integrated in your plentymarkets system are available. +
If you use an <<#create-and-apply-order-templates, order template>>, the payment method selected in the template is taken over as soon as you select the template for an order. After applying the template, the payment method can be changed manually if required.

| *Currency*
|The xref:payment:currencies.adoc#30[system currency] is preselected. You can change the currency for the order in the drop-down list.

| *Discount in %*
|You can manually enter a percentage discount which is then applied to all order items of the order. The value entered has to be between 0 and 100, negative values are not allowed. +
A discount is already filled in if the contact is assigned to a customer class in which a value has been entered for the option *Default discount for manual order*. You can find this option in the xref:crm:preparatory-settings.adoc#intable-customer-class-discount-type[Discount type] area in the *Setup » CRM » Classes* menu. You can adjust the prefilled value in the order details.

| *Warehouse*
|Which options are available depends on the settings you set for xref:orders:preparatory-settings.adoc#intable-warehouse-assignment[assignment of warehouses]: +
- Is *a) a warehouse can be assigned for each order* set, you can select a warehouse for the order in the order details or enter the name of a warehouse to search for it. +
If you selected a default warehouse in the *Setup » Orders » Order types » Sales order [Beta]* menu, this warehouse will be preselected.
- Is *b) a warehouse can be assigned for each order item* set, *Depending on the order items* is displayed. In the next step, items are added to the order. This means that you can select a warehouse for each variation from the drop-down list. +
If you selected a default warehouse in the *Setup » Orders » Order types » Sales order [Beta]* menu, this warehouse will be preselected in the item table of the next step.

| *Client*
|Select the client for this order from the drop-down list. Preselected is either the client set in the contact data or as a next option the <<#intable-default-client, default client>> if it is set.

| *Owner*
|Select the owner for this order from the drop-down list. If you set a <<#intable-default-owner, default owner>>, it is preselected. Otherwise, owners with the user rights to create orders can be selected from the drop-down list.

| *Order referrer*
|Select the referrer for this order from the drop-down list. Preselected is either the referrer set in the contact data or as a next option the <<#intable-default-referrer, default referrer>> if it is set. Otherwise the activated xref:orders:order-referrer.adoc#[referrers] can be selected from the drop-down list.

| *Early payment discount (%)*
|Enter the early payment discount, i.e. the value in percent that is subtracted if the payment is made within the defined early payment discount days. +
This setting is only available for the payment methods *Invoice* and *Cash in advance*.

| *Early payment (days)*
|Enter the number of days (starting when the invoice is created) in which the pending amounts can be paid at a discounted price. +
This setting is only available for the payment methods *Invoice* and *Cash in advance*.

| *Value date (days)*
|Enter the value date, i.e. the period from the invoice creation up to the payment due date. +
This setting is only available for the payment methods *Invoice* and *Cash in advance*.

| *Payment due (days)*
|Enter the payment due date in days, i.e. the days until the payment is due. +
This setting is only available for the payment methods *Invoice* and *Cash in advance*.

|====

[.collapseBox]
.*Creating a new delivery address*
--

You can create a new delivery address from the dropdown-list in the field *Delivery address*. Proceed as described below to create a new delivery address. +
*_Tip:_* The settings for creating a new invoice address are identical.

[.instruction]
Creating a new delivery address:

. Select the option (material:add[]) *Add new delivery address* from the dropdown-list *Delivery address*. +
→ The *Add new delivery address* window opens.
. Select if it is a *primary* address.
. Enter the data. Note <<#table-new-delivery-address>>.
. *Save* the new address.

After saving the new delivery address it will be added to the contact data of the corresponding contact. The new delivery address is selected for the new order.

[[table-new-delivery-address]]
.Order details: Creating a new delivery address
[cols="1,3"]
|====
|Setting |Explanation

|*Primary*
|Activate the option if the new address is the primary delivery address. With the activation, this delivery address is automatically preselected for the creation of new orders.

|*Form of address*
|If required, select a form of address from the drop-down list.

|*Company (Name 1)*
|Enter the company name. If there is no entry for *First name* and *Last name*, this is a mandatory field.

|*First name (Name 2)*
|Enter the contact’s first name. If there is no entry for *Company* and *Last name*, this is a mandatory field.

|*Last name (Name 3)*
|Enter the contact’s last name. If there is no entry for *Company* and *First name*, this is a mandatory field.

|*Additional information (Name 4)*
|If required, enter additional information, e.g. _c/o Mr. John Doe_.

|*Address 1 (Street)* +
*Address 2 (House number)*
|Enter the street and house number. +
*Street* is a mandatory field if there is no entry for *House number* and *Additional address information*. *House number* is a mandatory field if there is no entry for *Street* and *Additional address information*.

|*Address 3 (Additional address information)*
|If required, enter additional address information, e.g. _apartment 12a_. If there is no entry for *Street* and *House number*, this is a mandatory field.

|*Address 4 (Free)*
|This field can be freely used.

|*Postcode* +
*Town*
|Enter the postcode, if available, and the town of the contact. *Town* is a mandatory field. +
The order of the options *Postcode* and *Town* is reversed for certain countries, e.g. Germany.

|*Country* +
*Region/County*
|Select the values from the drop-down list. +
*_Note:_* The drop-down list *Region/County* is not available for all countries.

|*Email*
|Optionally enter an email address.

|*Telephone*
|Optionally enter a telephone number.

|*Type* and *Value*
|Select a type from the drop-down list. The following types are available: VAT number, External address ID, Entry certificate, Post number, Personal ID, age rating, Birthday, Title, Contact person, External contact ID. Enter the corresponding *value* for the selected type. +
Click on *Add address option* to add further *Types* and the corresponding *Values*.

|====

--

After you carried out all settings, go to the next step by clicking on *Add items*. Alternatively, you can click on the *Add items* step at the top. The order details are saved and you are redirected to the next step. In this step, you add items to the order.

[#step-two-add-items]
=== Step 2: Add items

Once you entered all order details in step 1, you can now add the desired items to the order. In this step, the order details are not displayed. They are available again in the third step where you finalise the order or the offer. *_Note_* however that only a few settings are editable in the last step.

[.collapseBox]
.*Customising the item table*
--

The item table can be customised according to your needs. This means that you can decide which information is displayed in the table columns and in which order they are shown. In order to adjust the table, proceed as follows.

[.instruction]
Customising the table:

. Click on *Configure columns* (material:settings[]). +
→ The window *Configure columns* opens.
. Select which columns you want to be displayed. Pay attention to the information given in <<table-overview-item-search>>.
. Move (material:drag_indicator[]) the columns so they are displayed in the desired order.
. Click on *Confirm* to save your settings.

When you have adapted the table once, these settings are saved. The table remains like this even when you finalised this order and create a new one. You can change the layout any time. A list of the available columns can be found in <<table-overview-item-search>>. There, it is also stated whether the column is a default column. Default columns are shown when tables are not customised.

[[table-overview-item-search]]
.Item table columns
[cols="1,3"]
|===
|Setting |Explanation

|*Stock status*
|In this column, a red status bar indicates that no net stock is available for an item. The red status bar is not displayed when the item is in stock. If you selected the option *Only display items in stock*, for example, none of the status bars are displayed in red at first. The status bar only turns red when stock units go below 0 while adding items to the shopping cart. +
This is a default column.

|*Status*
|This column shows whether the variation is set as active or inactive in the online shop. Information about activating or deactivating a variation can be found on the manual page xref:item:checklist-items-visibility.adoc#100[Have you activated the variation?]. +
This is a default column.

|*Item ID*
|Shows the ID of the item. You are redirected to the item data when clicking on the item ID. +
This is a default column.

|*Variation ID*
|Shows the variation ID. You are redirected to the variation data when clicking on the variation ID. +
This is a default column.

|*Item ID/Variation ID*
|This column displays the item ID and the variation ID next to each other and not in two separate columns. You are redirected to the item or variation data when you click on the item ID or the variation ID. +
This is a default column.

|*Variation number*
|Shows the variation number. You are redirected to the variation data when clicking on the variation number. +
This is an optional column.

|*Item name*
|Shows the name that is saved on the item. +
This is a default column.

|*Attributes*
|Shows the attributes that are saved on the item. +
This is a default column.

|*Variation name*
|Shows the variation name that is saved on the variation. +
This is a default column.

|*Barcode*
|Shows the barcode of the item. +
This is a default column.

| *System purchase price*
|Shows the system purchase price. +
This is a default column.

|[#intable-item-search-price-selection]*Price selection*
|All valid sales prices that are determined for this order are displayed in a drop-down list. You can select one of the displayed sales prices, which is then taken as the basis for the order calculation. If the price includes a discount, this is shown behind the price name and amount. The columns *Customer class discount* and *Category discount* show the percentage of the applied discount. +
You can manually set a sales price in the <<#shopping-cart, shopping cart>>. If you select a different sales price than the one that was determined first, the sales price needs to be updated. To do so, click on *Refresh sales price* (material:refresh[]). After the update, the shopping cart button (material:add_shopping_cart[]) is available again and the items can be added to the shopping cart. This also applies to quantity changes. +
If no valid sales price could be detected, *No valid sales price* is displayed in the drop-down list. The order cannot be completed without a valid sales price. Therefore, add the item to the shopping cart and adapt the price manually in there. +
This is a default column.

| *Category discount*
|Shows the category discount in per cent as applied to the selected sales price. +
This is a default column.

| *Customer class discount*
|Shows the customer class discount in per cent as applied to the selected sales price. +
This is a default column.

| *Availability*
|Shows the availability of the item. +
This is a default column.

| *Net stock*
|Shows the net stock of the item. +
This is a default column.

| *Warehouse*
|Shows the warehouse of the item. Select another warehouse from the drop-down list if required or enter the name of a warehouse to search for it. Note that this is only possible if you selected the setting *b) A warehouse can be assigned for each order item* for the *assignment of warehouses*. +
If you selected a default warehouse in the *Setup » Orders » Order types » Sales order [Beta]* menu, this warehouse will be preselected. +
This is a default column.

|*Quantity*
|Enter the quantity to be added to the shopping cart. You can only enter whole numbers. Negative quantities or quantities which exceed the net stock are not allowed. If you enter such quantities, an error message is displayed. If the added quantity sets the stock in the warehouse to 0 or lower, the row is displayed in red. +
If you change the quantity, the sales price changes as well and needs to be updated. To do so, click on *Refresh sales price* (material:refresh[]). After the update, the shopping cart button (material:add_shopping_cart[]) is available again and the items can be added to the shopping cart. +
This is a default column.

|*Cart icon*
|By clicking on the shopping cart (material:add_shopping_cart[]), the item is added to the shopping cart in the selected quantity. +
This is a default column.

|===

--

[#search-items]
==== Searching for items

By using the search (material:search[]), you can find the desired items and add them to the order. When you start a search, your search settings are displayed at the top as chips. You can save these search settings to apply them again more quickly and easily in the future. +
Use one of the following methods to search for items.

[.instruction]
Searching for items:

.. *_Option 1_*: Click on material:search[] to see a list of all items.
.. *_Option 2:_* Enter something into the search field and click on one of the automatic suggestions.
.. *_Option 3:_* Click on material:tune[] to narrow down the search results with filters.

Carry out the <<#search-items, search>> (material:search[]) to find and add the required items. You can also use the filters listed in the following table to narrow down the search results. Note that the <<#carrying-out-standard-settings, default settings>> are applied in the search.

[[table-order-filters]]
.Filters for order items
[cols="1,3"]
|===
|Filter |Explanation

| *Full text*
|Enter something into the input field to start a full text search.

| *Item ID*
|Enter an ID to filter for items with this ID.

| *Item name*
|Enter a name to filter for items with this name.

| *Variation no.*
|Enter a variation number to filter for items with this variation number. +
*_Tip:_* For this filter, a partial search is also possible. This means that you only need to enter the first characters of the variation number in order to search for it.

| *Variation ID*
|Enter a variation ID in order to filter for items with this variation ID.

| *Barcode*
|Enter a barcode to filter for items with this barcode.

| *Manufacturer*
|Enter a manufacturer to filter for items with this manufacturer.

| *Item tag*
|Enter a tag to filter for items with this tag.

| *Only display items in stock*
|Activate this option (material:done[role=skyBlue]) to filter only for items with physical stock.

| *Only display active items*
|Activate this option (material:done[role=skyBlue]) to filter only for activated items.

| *Only display sales warehouses*
|Activate this option (material:done[role=skyBlue]) to filter only for items that are stored in sales warehouses. +
*_Note:_* If you set *a) a warehouse can be assigned for each order* in the basic settings you cannot select the option *Only display sales warehouses* for the search because the warehouse is already determined by the setting.

| *Only display items with valid price*
|Activate this option (material:done[role=skyBlue]) to filter only for items with a valid sales price.

|===

[#save-current-filter]
==== Saving the current filter

. Start a search.
. Click on *Saved filters* (material:bookmarks[role=darkGrey]).
. Click on material:bookmark_border[role=darkGrey] *Save current filter*.
. Enter a name and toggle the optional settings as needed (material:toggle_on[role=skyBlue]).
. Click on *Save*. +
→ The filter settings now appear under *Saved filters* (material:bookmark[role=darkGrey]).


[#use-saved-filters]
==== Applying saved filters

. Click on *Saved filters* (material:bookmarks[role=darkGrey]).
. Click on an existing filter setting. +
→ The search is started and the filter settings are displayed at the top as chips.

[#adding-items]
=== Adding items

Once you found all desired items by using the search or applying filters, you can now add them to the order. To do so, proceed as follows.

[.instruction]
Adding items:

. Search (material:search[]) for the desired item.
. Select the appropriate sales price from the *Price selection* drop-down list.
. Enter the quantity of the item you want to add to the order.
. If you adjust any prices or quantities, open the context menu (material:more_vert[]) on the right of the respective line and update the sales price by clicking on *Refresh sales prices* (material:refresh[]). +
*_Tip:_* On the top left of the table, you can update all changes for prices or quantities at once by clicking on *Refresh sales prices* (material:refresh[]).
. At the end of the respective line, click on *Add items to shopping cart* in order to add the item to the shopping cart.
. Repeat these steps to add further items.
. When all items are added, go to the next step by clicking on *Create order* or *Create offer*. +
→ The shopping cart is saved and you are forwarded to the last step.

[#shopping-cart]
=== Editing the shopping cart

In the shopping cart table, you can adjust the *item name*, the *quantity* and the *sales price*. As soon as these entries are changed, updates have to be carried out. You can do this by either clicking on *Refresh sales price* (material:refresh[]) in the context menu (material:more_vert[]) directly next to the item. Or you use the button *Refresh sales prices* at the top left in the shopping cart table. Only after updating the prices you can move on to the next step of the order creation.

The following applies to sales prices:

* If you manually enter a price, this price will remain in the drop-down list and can be selected for this order, even if you navigate back and forth or select a different sales price in between.
* If no valid sales price could be detected, a sales price has to be entered manually. Completing an order is only possible with valid sales prices.
* It is allowed to enter the price 0.00.
* If a sales price is entered that is lower than the purchase price, an error message is displayed. However, you can still enter a lower sales price if you want to.
* Carry out all changes for the order items in this step of the order creation, as this is not possible in the third and last step. Navigating back and forth through the steps remains possible.

Moreover, you can also delete order items in the shopping cart. To do so, click on *Delete* (material:delete[]). Another option for editing order items are the properties. To do so, pay attention to the chapter <<#edit-order-item-properties, Editing order item properties>>.

Once you added all the items in the required quantity and with the right prices to the shopping cart, click on *Create order* or *Create offer*. You can also go back to the order details by clicking on *Order details*. Items in the shopping cart are saved when you go back and forth.

[.collapseBox]
.*Customising the shopping cart table*
--
The shopping cart table is customisable. This means that you can decide which table columns are displayed in which order. When you have adapted the table, these settings are saved.

[.instruction]
Customising the table:

. Click on *Configure columns* (material:settings[]). +
→ The window *Configure columns* opens.
. Select which columns you want to be displayed.
. Move (material:drag_indicator[]) the columns so they are displayed in the order you need them in.
. Click on *Confirm* to save your settings.

[[table-shopping-cart]]
.Shopping cart table columns
[cols="1,3"]
|===
|Setting |Explanation

| *Expand*
|Allows you to expand the order items table and shows the properties.

| *Quantity*
|Shows the item quantity. If needed, adjust the quantity. +
This is a default column.

| *Item ID*
|Shows the item ID. You can open the item by clicking on the ID. +
This is a default column.

| *Variation ID*
|Shows the variation ID of this order item. You can open the variation by clicking on the ID. +
This is a default column.

| *Item ID* / *Variation ID*
|This column displays the item ID and the variation ID next to each other and not in two separate columns. You are redirected to the item or variation data when you click on the item ID or the variation ID. +
This is not a default column.

| *Variation no.*
|Shows the number of the variation. You are redirected to the variation data when clicking on the variation number. +
This is an optional column.

| *Item name*
|Shows the name that is saved on the item. You can edit (material:edit[]) the item name if needed. +
This is a default column.

| *Attributes*
|Shows the attributes. +
This is a default column.

| *Variation name*
|Shows the name of the variation. +
This is a default column.

| *Barcode*
|Shows the barcode of the item. +
This is not a default column.

| *System purchase price*
|Shows the system purchase price. +
This is not a default column.

| *Price selection*
|Shows the price selection. If needed, select another price selection from the drop-down list. +
This is a default column.

| *Category discount*
|Shows the category discount in per cent as applied to the selected sales price. +
This is not a default column.

| *Customer class discount*
|Shows the customer class discount in per cent as applied to the selected sales price. +
This is not a default column.

| *Net price*
|Shows the net price of the item. You can edit the data field net price via material:edit[]. The gross price will be adjusted automatically. +
This is a default column.

| *Regular net price*
|Shows the regular net price of the item. +
This is not a default column.

| *Gross price*
|Shows the gross price of the item. You can edit the data field gross price via material:edit[]. The net price will be adjusted automatically. +
This is a default column.

| *Surcharge total*
|Shows the sum of the order item properties’ surcharges. +
This is not a default column.

| *Discount*
|Shows the discount that was entered in the order details in the first step of the order creation. +
This is a default column.

| *Total amount of the order (gross)*
|Shows the total gross amount of the item. +
This is a default column.

| *Warehouse*
|Shows the warehouse of the item. Select another warehouse from the drop-down list, if required. Note that this is only possible if you selected the setting *b) A warehouse can be assigned for each order item* for the *assignment of warehouses*. +
This is a default column.

| *VAT (%)*
|The VAT is shown in %. 19.00 % are preset for the VAT. You can change the VAT rate in the drop-down list. +
This is a default column.

| *Weight [g]*
|Shows the item weight in grams. Edit the weight in the input field if needed. +
This is not a default column.

| *Length [mm]*
|Shows the length of the item in mm. Edit the length in the input field if needed. +
This is not a default column.

| *Width [mm]*
|Shows the width of the item in mm. Edit the width in the input field if needed. +
This is not a default column.

| *Actions*
|If this field is selected, the actions for editing (material:edit[]) and deleting (material:delete[]) the item are available.
|===

--

[#edit-order-item-properties]
=== Editing order item properties

You can edit the order item properties in the shopping cart. Any changes made here only apply to the order items of this order. The properties themselves stay as they are configured in the system. Only the properties that have already been created and configured in the system are available in the order creation. +
If you want to create and edit properties or are not yet familiar with the structure of properties, refer to the manual chapter xref:item:properties.adoc#500[Properties] first.

In order to link a property with an order item, the property has to be marked as *Order property* in the *Options* area of the property settings. Also set possible surcharges and VAT rates for the property in the xref:item:properties.adoc#property-options[Options] area. The values added here will be included in the order calculations. If a property is already linked with an order item, it will be displayed on the corresponding order item.

The properties are displayed in a second row of the table underneath the corresponding order item. Here, you can find information about the *Name*, *Value*, *Surcharge* and *VAT %* of the property. You can edit the *VAT %*, i.e. the saved VAT rate of the property, directly in the table if the property type allows for that. Moreover, you can *delete* (material:delete[]) order item properties in the table. Deleted properties are not included in this order and the calculations. +
To edit the properties or to add more already existing properties, click on *Edit properties* (material:edit[]) in the context menu (material:more_vert[]) on the right.

In the editing window, you will find the following information about an order item’s property:

* *Name* = The name of the property is displayed. A red asterisk marks the property as a required property. Whether a property is required is determined in the xref:item:properties.adoc#property-options[Options] area of the property settings. Select *Required* from the *Order options* drop-down list.
* *Value* = The value of the property is displayed. You can edit the value. Depending on the property type, you can either make a selection, edit the value, add a value or upload a file. The changes are only valid for this order.
* *Surcharge* = The surcharge of the property is displayed, if a surcharge is set for the property. You can edit the surcharge. The changes are only valid for this order.

There are also further editing options are available here. By clicking on *Delete* (material:delete[]), you remove the property from this order item. This property is then not included in the order and the order calculations. +
You can also add more already existing properties. Select a property from the drop-down list *Select property* and add it to the order item by clicking on *Add property* (material:add[]). +
Once you are done with all adaptations, click on *Save properties*. By clicking on *Cancel*, none of the changes are saved. he editing window is closed and you can edit the properties of other order items in the same way.

If you want to have the properties displayed on documents, you have to set this in the configurations of the property itself. Make sure that the following options are selected in the xref:item:properties.adoc#property-visibilities[Visibilities] area of each property:

* *Display on documents* from the *Display everywhere* drop-down list as well as
* the correct clients from the *Clients* drop-down list.

Where the properties are displayed on the document depends on each property and its configuration. Properties for which no VAT rate was set in the *Options* area of the configuration or for which the option *Display as additional costs* in the *Order property* drop-down list was selected are displayed underneath the totals. Other properties are displayed in the order item table.

When you are done with editing the order item properties and the shopping cart, the last step of the order creation follows. In this step, the order item properties are not displayed again. Thus, make sure that you carried out all relevant settings. Click on *Create order* or *Create offer*.

[#step-three-summary]
=== Step 3: Create order / Create offer

In the last step, the order or the offer is completed. Different amounts of the order or the offer are displayed in info boxes above the order details:

* Total amount (gross): Shows the calculated total gross amount of the order. The status bar is green when the order is a gross order. Otherwise the status bar is grey.
* Total amount (net): Shows the calculated total net amount of the order. The status bar is green when the order is a net order. Otherwise the status bar is grey.
* Total number of items: Shows the total number of order items of this order. The status bar is always grey.
* Coupon amount: Shows the granted discount from promotional coupons. The status bar is orange when a promotional coupon was used in this order. Otherwise the status bar is grey.
* Order discount: Shows the discount amount resulting from the discount granted in the first step of the order creation. The summed up discount amount of all the order items is calculated. The status bar is orange when a discount was set in the first step. Otherwise the status bar is grey.
* Open amount: Shows the open invoice amount the customer has to pay. The status bar is green when the amount is zero, i.e. if the customer has already paid the full invoice amount. Red means that the full invoice amount is still open. Orange means that the invoice amount is still partially open.

In the order details, you can adjust the *Payment method*, the *Shipping costs*, the *Shipping method* as well as the *Owner* if required. +

Moreover, you can enter one or more coupon codes in the *Coupon codes* field to redeem these with this order. The values of the coupons are set off against the order value. Coupons are not added as an order position in the shopping cart. Coupons cannot be redeemed for offers.  This means that the input field *Coupon codes* is only available for the order creation, but not for creating offers. For coupons, it is differentiated between the types *plentymarkets campaign* and *External campaign*. In order to redeem coupon codes proceed as follows.

[tabs]
====
Redeeming coupon codes of a plentymarkets campaign::
+
--
[.instruction]
Redeeming coupon codes of a plentymarkets campaign:

. In the field *coupon codes*, enter the code of a plentymarkets campaign.
. Then click on _Enter_ or outside the field. +
→ It is checked whether the coupon code is valid. If the coupon is redeemable, it is displayed in green with the coupon’s value. If a coupon code is however invalid, it is displayed in red with the info *Not redeemable*. +
*_Tip:_* A tooltip shows which kind of coupon it is.
. Enter additional coupon codes if required. +
icon:map-signs[] *_Or:_* On the right in the field *Coupon codes* click on *Add coupon code* (material:add[]). +
→ The window *Redeem coupon* opens.
. Select the campaign type *plentymarkets campaign* from the drop-down list.
. Enter the coupon code of the plentymarkets campaign.
. Click on *Redeem*. +
→ The coupon code is added and will be redeemed with this order.
--

Redeeming coupon codes of an external campaign::
+
--

[.instruction]
Redeeming coupon codes of an external campaign:

. On the right in the field *Coupon codes* click on *Add coupon code* (material:add[]). +
→ The window *Redeem coupon* opens.
. Carry out the settings. Pay attention to the information given in <<table-redeem-coupon-codes>>.
. Click on *Redeem*. +
→ The coupon code is added in blue together with the coupon’s value and will be redeemed with this order.

[[table-redeem-coupon-codes]]
.Redeeming coupon codes
[cols="1,3"]
|===
|*Setting* |*Explanation*

| *Campaign type*
|Select the type *External campaign* from the drop-down list.

| *Code*
|Enter a coupon code.

| *Type*
|Select whether it is a *Promotional coupon* or a *Multipurpose coupon*.

| *Value in €*
|Enter the coupon’s value in the respective currency.

|===
--
====

Below the order details, a table with the added order items is displayed. In addition to the information given in the previous view, further prices and the VAT rate are shown. The VAT rates are editable if you allowed this in the <<#carrying-out-standard-settings, default settings>>.

[.collapseBox]
.*Customising the table*
--

The table in the last step of the order create is customisable. This means that you can decide which table columns are displayed in which order. When you have adapted the table, these settings are saved.

[.instruction]
Customising the table:

. Click on *Configure columns* (material:settings[]). +
→ The window *Configure columns* opens.
. Select which columns you want to be displayed.
. Move (material:drag_indicator[]) the columns so they are displayed in the order you need them in.
. Click on *Confirm* to save your settings.

The following columns are available: +

* Expand
* Quantity
* Item ID
* Variation no.
* Variation name
* Variation ID
* Item name
* Attributes
* Net price
* Regular net price
* Gross price
* Discount
* Surcharge total
* Total amount of the order (net)
* Total amount of the order (gross)
* Warehouse
* VAT
* External item ID
* External order item ID
* Property ID
* Storage locations
* Net profit margin
* Reorder ID

--

If you carry out changes on the shipping costs or the shipping method or in case you add coupons, the total amounts are automatically recalculated. To complete the order, click on material:save[role=green]*Create order*. The order has now been created and depending on your settings, you are forwarded to the respective view. The order is now available in the order overview of the *Orders » Orders (Test phase)* menu.


[#create-and-apply-order-templates]
== Creating and applying order templates

Order templates are created in the *Setup » Orders » Order template* menu. You can select them when you manually create a new order or you can apply an order template via an xref:automation:event-procedures.adoc#intable-order-template[event procedure]. If you select an order template for an order, the order template data is applied to the order. After using an order template, you can edit an order as usual as well as change and adapt order information.

To create an order template proceed as follows:

[.instruction]
Creating an order template:

. Go to the *Setup » Orders » Order template* menu.
. Click on the *New template* tab.
. Enter a unique *Name*.
. Select a *Payment method* and an *Order status* from the corresponding drop-down list.
. Optionally add items by clicking on *Add item*.
. Save (material:save[role=green]) the order template.

[[table-order-templates]]
.Order template fields
[cols="1,3"]
|===
|Setting |Explanation

| *Name*
|Enter a name for the order template. This name is displayed in drop-down lists for selecting the order template.

| *Payment method*
|Select a payment method from the drop-down list. When applying the order template to an order, this payment method is added to the order.

| *Order status*
|Select an order status from the drop-down list. When applying the order template to an order, the order is moved to this order status.

| *Item*
|If you already added items to the order template, they are displayed in this table. Adding items is optional. The items that are displayed here will be added to the order when using this order template. The quantity and the item text are displayed for each item. Moreover, you can delete items from the order template in this table. +
*_Note:_* When you apply an order template with items, the order you want to apply it to should not have any items added yet. Items that have already been added to the order are overwritten. However, you can add more items to an order after applying the order template.

| *Adding items*
|Optionally, you can add items to the order template in this tab. These items are added to the order when the order template is applied. +
Set filters and execute a search (material:serach[role=skyBlue]) to display items. Add (material:add_shopping_cart[role=green]) the desired items to the order template. The added items are displayed in the *Item* tab. +
*Quantity* = You can add an item more than once. Each item is displayed in a new table row. Alternatively, you can adapt the *Quantity* column of an item in the *Item* tab of the table.

|===

You can edit and adapt order templates at any time. After editing an order template, you have to save (material:save[role=green]) the order template again. Adaptations to order templates are not retroactively applied to orders but are valid from the moment of adaptation on.

Order templates are only applied to orders if you decide so. If you always want to apply an order template to specific orders, we recommend using an xref:automation:event-procedures.adoc#intable-order-template[event procedure]. Determine in the event procedure by the selection of the event and the filters, when and to which orders which order template should be applied.

To apply an order template when manually creating an order, select the required order template from the drop-down list *Use template* in the *Order data* area. In the order creation, you can select an order template in the first step of the order creation from the *Order template* drop-down list.
