= Manually creating orders
:keywords: create orders manually, create orders from contact, manual order entry
:author: team-order-core

//adjust links to new pages where possible (auftragsdokumente once this has been moved)

In contrast to what you probably suspect, orders are not created directly in the *Orders » Orders (Test phase)* menu. This page describes how you can create orders in the system, e.g. if an order is placed during a phone call. In plentymarkets, the following methods are available for creating orders:

* Via the <<#create-order-in-contact-overview, Contact overview>>
* Via the <<#create-order-via-contact, contact data>>
* In an existing <<#create-order-via-existing-order, order>>
* Via a <<#create-order-via-cash-sale, cash sale>>

The different methods are described in the following.

[IMPORTANT]
.Sending emails
====
When you manually create orders, no emails will automatically be sent to the customer. The reason that no emails will be sent is that your system does not know when you are done with all settings for a manual order. Send xref:crm:emailbuilder.adoc#[emails] manually by using the *Email service* function in an order.
====

[#create-order-via-contact]
== Creating an order in the contact overview

The description below shows you how to create an order via the *CRM » Contacts* menu.

[.instruction]
Creating an order via the contact:

//ggf. noch anpassen, wohin man genau gelangt, wenn man auf aufträge > neuer auftrag beta klickt (neue UI)

. Go to *CRM » Contacts*.
. Search for the contact by means of the filter settings. Note the explanations about the filters on the xref:crm:search-contact.adoc#[Searching for a contact] page. +
→ The contacts that match the search criteria are displayed.
. On the right in the row of the contact, click on the additional optiions (material:more_vert[]). +
→ The available options open.
. Select the option material:shopping_cart[] *Orders* > *New order [Beta]*. +
→ The overview for creating a new order opens.
. Select the items and the quantities that you want to add to the order.
. *Save* (material:save[]) the settings. +
→ The order is created.

[#create-order-via-existing-order]
== Creating an order from an existing order

Thanks to the connection between the order UI and the contacts UI, it only takes you a few clicks to create a new order from an existing order. Proceed as described below to create a new order.

[.instruction]
Creating an order from an existing order:

. Go to *Orders » Orders (Test phase)*.
. Carry out the search (material:search[]) to display orders.
. Open the order of the customer for which you want to create a new order.
. Click on the *Contact ID* at the bottom of the page navigation. +
→ The order opens in the *CRM » Contacts* menu.
. Go to the *Orders* area.
. On the right, click on *Options* (material:add[]).
. Select the option *New order*. +
→ The overview for creating a new order opens.
. Select the items and the quantities that you want to add to the order.
. *Save* (material:save[]) the settings. +
→ The order is created.

[#create-order-via-cash-sale]
== Creating an order for a cash sale

When you open the *CRM » Contacts* menu you can register cash sales using the customer profile *Cash sale*. The customer profile named *Cash sale* allows you to assign orders without having to assign them to a customer. The customer profile *Cash sale* is set up in your system by default.

[WARNING]
.Payment method and order documents for cash sale
====
Make sure to select the correct *payment method* in the *order data* when creating an order for a cash sale. When manually creating a cash sale order the order will not be assigned to a customer saved in your system. This is why you should manually generate the required xref:orders:order-documents.adoc#[order documents] such as the invoice right away while entering and processing the cash sale. Order documents can be generated in the *Documents* tab of the order.
====

[.instruction]
Creating a new order for a cash sale:

. Go to *CRM » Contacts*.
. Enter the desired ID in the *ID* search field. +
→ A list of all search results is displayed.
. Select *Cash sale* from the *results*. +
→ The customer profile for cash sale opens.
. Click on *New order* to create a cash sale order. +
→ The overview for creating a new order opens.
. Select the items and the quantities that you want to add to the order.
. *Save* (material:save[]) the settings. +
→ The order is created.

[#create-order-in-contact-overview]
== beta: Creating an order or an offer in the contact overview

This chapter describes hot to create an order or an offer in the contact overview in the *CRM » Contacts* menu.

[#carrying-out-standard-settings]
=== Carrying out default settings

When creating orders or offers via the contact overview, data such as addresses or clients are taken directly from the contact data if they are deposited there. Thus, in most cases contact data have priority. Additionally, some default settings, which are a fallback if the data are not deposited in the contact, are available. +
In order to optimise the order creation, these default settings should be determined first. +
*_Note:_* The default settings also apply to offers that are created via the contact UI.

[.instruction]
Carrying out default settings:

. Go to *Setup » Orders » Order types » Sales Order [Beta]*.
. Carry out the settings. Pay attention to the explanations given in <<table-default-settings-order-contact>>.
. *Save* (material:save[role="green"]) the settings.

[[table-default-settings-order-contact]]
.Default settings for the new order creation (beta)
[cols="1,3"]
|===
|Setting |Explanation

|[#intable-default-owner]*Default owner*
|Select a default owner to be preselected in the order details when creating an order or an offer. The owner is not taken from the contact data.

|[#intable-default-client]*Default client*
|The default client selected here is preselected in the order details when creating an order or an offer if no client is set in the contact. If a client is set in the contact data, this client takes priority.

|[#intable-default-referrer]*Default referrer*
|The default referrer selected here is preselected in the order details when creating an order or an offer if no referrer is set in the contact. If a referrer is set in the contact data, this referrer takes priority.

|[#intable-endpoint-after-completion]*Endpoint after completing an order*
|Select the location in the system you want to be directed to after creating the order. You can choose between: +
*Order overview of the contact* = Forwards you to the order overview in the contact data record of the contact for which you have just created an order. This is the default setting. +
*Order overview* = Forwards you to the general order overview. +
*Detail view of the new order* = Forwards you to the detail view of the order you have just created.

|[#intable-shopping-cart-type]*Type of shipping cart used in order creation*
|Select which type of shopping cart you want to use during order creation. The side cart is selected by default. The functions of both shopping carts is identical. +
*Side cart* = The shopping cart is opened as an overlay on the side. +
*Shopping cart table (below search results)* The shopping cart is displayed as a table before the table of order items (generated by the item search).

|[#intable-default-template]*Default order template*
|If you select an <<#create-and-apply-order-templates, order template>> as the default order template, this template is preselected for the new order or offer by default. The values of the selected order template are automatically applied to the order or offer. You can only select order templates that have already been created. +
The option *No order template preselected* is set by default. If you select an order template as the default and this template is deleted at some point, the default setting returns to *None*.

|*Filter option ‘Only display items in stock’ is preselected in item search*
|Activate this option for it to be preselected in the item search. It means that only items with physical stock are displayed in the item search.

|*Filter option ‘Only display sales warehouses’ is preselected for the item search*
|Activate this option for it to be preselected in the item search. It means that only items stored in sales warehouses are displayed in the item search.

|*Filter option ‘Only display active items’ is preselected in item search*
|Activate this option for it to be preselected in the item search. It means that only xref:item:checklist-items-visibility.adoc#100[activated items] are displayed in the search results.

|*Filter option ‘Only display items with valid price’ is preselected in item search*
|Activate this option for it to be preselected in the item search. It means that only items for which a valid price is saved are displayed in the item search.

|*Allow changing the VAT rates in the items overview table in the last step of the order creation*
|By activating this option, you allow that VAT rates can be changed before finishing creating the order in the last step of the order creation. The VAT rates depend on the delivery address of the order. +
This option is deactivated by default. If you only want to display the VAT rates in the overview and not edit them, do not activate the toggle.

|*Display of added items in the shopping cart*
|Select how items are added to the shopping cart. The default setting is *As one order position, quantities of order items are increased*. +
*As separate order positions* = Identical items are added separately, meaning that each item is displayed in a separate row. +
*As one order position, quantities of order items are increased* = Identical items are added as one order item, only the quantities are changed accordingly.

|*Redetermine prices only in the shopping cart in the order creation*
|By activating this option, you determine that item prices are only recalculated when they are placed in the shopping cart. By default, prices are already determined during the item search when creating an item and can be selected there.

|===

[#create-order-or-offer]
=== Creating an order or an offer

The order or the offer is created individually for a customer from the *CRM » Contacts* menu. The creation consists of three steps. As a first step, order details are entered. In the second step, order items are added and in the third step, the order is completed. First of all, select the contact for which the order or offer is to be created. To do so, proceed as follows.

[.instruction]
Creating order or offer via contact:

. Go to *CRM » Contacts*.
. Search for the contact by means of the filter settings. Note the explanations about the filters on the xref:crm:search-contact.adoc#[Searching for a contact] page. +
→ The contacts that match the search criteria are displayed.
. On the right in the row of the contact, click on material:more_vert[]. +
→ The available options open.
. Select the option material:shopping_cart[] *Orders* > *New order [Beta]* or *New offer [Beta]*. +
→ You are automatically redirected to the order details of the new order or offer.

Above the order details, you can also choose between an order or an offer afterwards. In addition, you can select an optional <<#create-and-apply-order-templates, order template>> from the drop-down list to apply the template to this order. By default, no order template is selected.

The steps described in the following chapters are the same for orders and offers.

The user interface is designed so that orders can be created quickly and easily. This is especially helpful when orders are telephoned in. First, the order details such as addresses and payment method are entered. After that, order items are added and the last step is the final check and completion of the order.

[#order-details]
=== Order details

As the new order or the new offer is created from the contact overview, some information are transferred from the contact data to the order details. Which information is transferred depends on the data saved in the contact. Otherwise, the <<#carrying-out-standard-settings, default settings>> apply. Also note <<#table-order-details-new-order, this table>>. All fields in the order details are mandatory fields.

[[table-order-details-new-order]]
.New order: Order details
[cols="1,3"]
|===
|Setting |Explanation

|*Invoice address*
|The invoice address is taken from the contact data. If there is more than one address, the one saved as the primary invoice address is taken. If no invoice address is saved as the primary address, you can select the right address from the drop-down list. +
Use the preview (material:visibility[]) to access the contact data record directly. The already carried out settings in the order details will remain.

|*Delivery address*
|If you select the option *As invoice*, the invoice address is entered automatically as the delivery address as well. Otherwise, the delivery address is taken from the contact data. If there is more than one address, the one saved as the primary delivery address is taken. If no delivery address is saved as the primary one you can select the right address from the drop-down list. +
The dropdown-list also offers the possibility to create a new delivery address which is then saved in the contact data. For further information, see the expandable box at the end of this section. +
Use the preview (material:visibility[]) to access the contact data record directly. The already carried out settings in the order details will remain.

|*Payment method*
|If a payment method is defined for the contact, for example in a xref:crm:preparatory-settings.adoc#create-customer-class[customer class], this is preselected. Otherwise you can enter a payment method and select it. All payment methods integrated in your plentymarkets system are available. +
If you use an <<#create-and-apply-order-templates, order template>>, the payment method selected in the template is taken over as soon as you select the template for an order. After applying the template, the payment method can be changed manually if required.

|*Discount in %*
|You can manually enter a percentage discount which is then applied to all order items of the order. The value entered has to be between 0 and 100, negative values are not allowed. +
A discount is already filled in if the contact is assigned to a customer class in which a value has been entered for the option *Default discount for manual order*. You can find this option in the xref:crm:preparatory-settings.adoc#intable-customer-class-discount-type[Discount type] area in the *Setup » CRM » Classes* menu. The prefilled value in the order details is editable.

|*Currency*
|The xref:payment:currencies.adoc#30[system currency] is preselected. You can change the currency for the order in the drop-down list.

|*Warehouse*
|Which options are available depends on the settings you set for xref:orders:preparatory-settings.adoc#intable-warehouse-assignment[assignment of warehouses]: +
- Is *a) a warehouse can be assigned for each order* set, you can select a warehouse for the order in the order details. +
- Is *b) a warehouse can be assigned for each stock unit* set, *Depending on the stock units* is displayed. In the next step, order items are added. This selection means that you can select a warehouse for each variation from the drop-down list.

|*Client*
|Select the client for this order from the drop-down list. Preselected is either the client set in the contact data or as a next option the <<#intable-default-client, default client>> if it is set.

|*Owner*
|Select the owner for this order from the drop-down list. If you set a <<#intable-default-owner, default owner>>, it is preselected. Otherwise, owners with the user rights to create orders can be selected from the drop-down list.

|*Referrer*
|Select the referrer for this order from the drop-down list. Preselected is either the referrer set in the contact data or as a next option the <<#intable-default-referrer, default referrer>> if it is set. Otherwise the activated xref:orders:order-referrer.adoc#[referrers] can be selected from the drop-down list.

|===

After you carried out all these settings, go to the next step and add the desired items to the order.


[.collapseBox]
.*Creating a new delivery address*
--

You can create a new delivery address from the dropdown-list in the field *Delivery address*.

[.instruction]
Creating a new delivery address:

. Select the option (material:add[]) *Add new delivery address* from the dropdown-list *Delivery address*. +
→ The *Add new delivery address* window opens.
. Select if it is a *primary* address.
. Enter the data. Note <<#table-new-delivery-address>>.
. *Save* the new address.

After saving the new delivery address it will be added to the contact data of the corresponding contact. The new delivery address is selected for the new order.

[[table-new-delivery-address]]
.Order details: Creating a new delivery address
[cols="1,3"]
|====
|Setting |Explanation

|*Primary*
|Activate the option if the new address is the primary delivery address. With the activation, this delivery address is automatically preselected for the creation of new orders.

|*Form of address*
|If required, select a form of address from the drop-down list.

|*Company (Name 1)*
|Enter the company name. This is a mandatory field when there is no entry for *First name* and *Last name*.

|*First name (Name 2)*
|Enter the contact’s first name. This a mandatory field when there is no entry under *Company* and *Last name*.

|*Last name (Name 3)*
|Enter the contact’s last name. This is a mandatory field when there is no entry under *Company* and *First name*.

|*Additional information (Name 4)*
|If required, enter additional information, e.g. c/o Mr. John Doe.

|*Address 1 (Street)* +
*Address 2 (House number)*
|Enter the street and house number. +
*Street* is a mandatory field when there is no entry for *House number* and *Additional address information*. *House number* is a mandatory field when there is no entry for *Street* and *Additional address information*.

|*Address 3 (Additional address information)*
|If required, enter additional address information, e.g. apartment 12a. This is a mandatory field when there is no entry for *Street* and *House number*.

|*Address 4 (Free)*
|This field can be freely used.

|*Postcode* +
*Town*
|Enter the postcode, if available, and the town of the contact. *Town* is a mandatory field. +
The order of the options *Postcode* and *Town* is reversed for certain countries, e.g. Germany.

|*Country* +
*Region/County*
|Select the values from the drop-down list. +
*_Note:_* The drop-down list *Region/County* is not available for all countries.

|*Email*
|Optionally enter an email address.

|*Telephone*
|Optionally enter a telephone number.

|*Type* and *Value*
|Select a type from the drop-down list. The following types are available: VAT number, External address ID, Entry certificate, Post number, Personal ID, age rating, Birthday, Title, Contact person, External contact ID. Enter the corresponding *Value* for the selected type. +
Click on *Add address option* to add further *Types* and the corresponding *Values*.

|====

--

[#add-items]
=== Adding items

In this step, the order details are not displayed. They are available again in the third step where you finalise the order. Note that only the shipping method and costs can be edited in the third step.

To complete an order, order items have to be added. Carry out the search to find and add the required items. You can choose between different filters for the item search:

* Item ID
* Item name
* Variation number
* Variation ID
* Barcode
* Manufacturer
* Item tag

Additionally, you can activate the options *Only display active items*, *Only display items in stock*, *Only display sales warehouses* and *Only display items with valid sales prices*. If you set *a) a warehouse can be assigned for each order* in the basic settings you can only select the option *Only display items in stock* for the search because the warehouse is already determined by the setting. Moreover, the <<#carrying-out-standard-settings, default settings>> are preselected if you set them.

Execute the search (material:search[]) to find the required items and to add them to the order.

[.collapseBox]
.*Search functions*
--
There are several ways of using the search. You can enter a value in the search field and then select the required filter. When you enter a number or a letter, available filters are suggested, e.g. order ID or variation number. Enter the value in full and then select the required filter from the suggestions. Repeat this to combine filters. Click on *Search* (material:search[]) to carry out the search. +
If you first want to select a filter from the filter list, click on *Filter* (material:tune[]). → The available filters are shown. Enter a value in the desired filter. Click on *Search* once you have set all needed filters. +
Remove the chip if you want to delete a set filter.

Additionally, you can save selected filters in the UI by using the *Saved filters* (material:bookmarks[]) component. The saved filters can then be selected from this component every time you open or work with this menu, similar to bookmarks. Every user can save own filter sets.

[.instruction]
Saving filters:

. Set the filters with the required values.
. Carry out the search.
. Click on *Saved filters* (material:bookmarks[]).
. Click on *Save current filter* (material:bookmark_border[]). +
→ The window *Save filter* opens.
. Enter a *Filter name*.
. Decide if this filter set should be used as default.
. Decide if this filter set should be available to all users.
. Click on *Save*.

--

The add items table is customisable. This means that you can decide which information is displayed in the table columns. To do so, proceed as follows:

[.instruction]
Customising the table:

. Click on *Configure columns* (material:settings[]). +
→ The window *Configure columns* opens.
. Select which columns you want to be displayed. Note <<table-overview-item-search>>.
. Move (material:sort[]) the columns so they are displayed in the order you need them in.
. Click on *Confirm* to save your settings.

When you have adapted the table once, these settings are saved. The table remains like this even when you finalised this order and are creating a new one. You can change the layout any time. A list of the available columns can be found in <<table-overview-item-search>>. There, it is also stated whether the column is a default column. Default columns are shown when tables are not customised.

[[table-overview-item-search]]
.Columns table item search
[cols="1,3"]
|====
|Setting |Explanation

|*Stock status*
|In this column, a red status bar indicates that no net stock is available for an item. The red status bar is not displayed when the item is in stock. If you selected the option *Only display items in stock*, for example, none of the status bars are displayed in red at first. The status bar only turns red when stock units go below 0 while adding items to the shopping cart. +
This is a default column.

|*Status*
|This column shows whether the variation is set as active or inactive in the online shop. Information about activating or deactivating a variation can be found on the manual page xref:item:checklist-items-visibility.adoc#100[Have you activated the variation?]. +
This is a default column.

|*Item ID*
|You are redirected to the item data when clicking on the item ID. +
This is not a default column.

|*Variation ID*
|You are redirected to the variation data when clicking on the variation ID. +
This is not a default column.

|*Item ID/Variation ID*
|This column displays the item ID and the variation ID together and not in two separate columns. You are redirected to the item or variation data when you click on the item ID or the variation ID. +
This is not a default column.

|*Variation number*
|You are redirected to the variation data when clicking on the variation number. +
This is a default column.

|*Item name*
|The item description is displayed. +
This is a default column.

|*Attributes*
|Attributes of the item are displayed. +
This is a default column.

|*Variation name*
|The variation name is displayed. +
This is a default column.

|*Barcode*
|Barcodes are displayed. +
This is not a default column.

|*Quantity*
|Enter the quantity to be added to the shopping cart. You can only enter whole numbers. Negative quantities or quantities which exceed the net stock are not allowed. If you enter such quantities, an error message is displayed. If the added quantity sets the stock in the warehouse to 0 or lower, the row is displayed in red. +
If you change the quantity, the sales price changes as well and needs to be updated. To do so, click on *Refresh sales price* (material:refresh[]). After the update, the shopping cart button (material:add_shopping_cart[]) is available again and the items can be added to the shopping cart. +
This is a default column.

|*Sales price*
|The sales price you selected from the <<#intable-item-search-price-selection, Price selection>> for this item is displayed. +
This is a default column.

|[#intable-item-search-price-selection]*Price selection*
|All valid sales prices that are determined for this order are displayed in a drop-down list. You can select one of the displayed sales prices, which is then taken as the basis for the order calculation. If the price includes a discount, this is shown behind the price name and amount. The columns *Customer class discount* and *Category discount* show the percentage of the applied discount. +
You can manually set a sales price in the <<#shopping-cart, shopping cart>>. If you select a different sales price than the one that was determined first, the sales price needs to be updated. To do so, click on *Refresh sales price* (material:refresh[]). After the update, the shopping cart button (material:add_shopping_cart[]) is available again and the items can be added to the shopping cart. This also applies to quantity changes. +
If no valid sales price could be detected, *No valid sales price* is displayed in the drop-down list. The order cannot be completed without a valid sales price. Therefore, add the item to the shopping cart and adapt the price manually in there. +
This is a default column.

|*Availability*
|This column displays the availability of a variation. Which symbol is displayed depends on your settings in the *Setup » Items » Availability* menu. For further information about these settings refer to the chapter xref:item:availabilities.adoc#[Availabilities] of the manual. +
This is a default column.

|*Net stock*
|The net stock of this item in the selected warehouse is displayed. +
This is a default column.

|*Warehouse*
|The warehouse of the item is displayed. +
This is a default column.

|*Shopping cart icon*
|By clicking on the shopping cart icon (material:add_shopping_cart[]), the item is added to the shopping cart in the selected quantity. +
This is a default column.

|====

[.instruction]
Adding items:

. Search (material:search[]) for the desired item.
. Select the appropriate sales price from the *Price selection* drop-down list.
. Enter the quantity of the item you want to add to the order. +
→ Whenever prices and quantities are changed, the sales price has to be updated by clicking on *Refresh sales price* (material:refresh[]).
. Add the items to the order by clicking on the shopping cart (material:add_shopping_cart[]]) at the end of the row. +
→ When an item was successfully added, the shopping cart icon (material:add_shopping_cart[]) briefly changes size and colour.
. Repeat these steps to add further items.
. When all items are added, go to the next step by clicking on *Overview*. +
→ The cart is saved.

[#shopping-cart]
=== Shopping cart

The number of items that was added is displayed on the shopping cart icon (material:shopping_cart[]) which is located above the table. If you want to check or delete the added items, open this shopping cart (material:shopping_cart[]).

Depending on the <<#intable-shopping-cart-type, shopping cart type>> you selected in the default settings, a sideward overlay opens or the view jumps directly to the shopping cart table. Regardless of the shopping cart type, you can edit the *Quantity* as well as the *Sales price*. As soon as field entries are adapted, updates have to be carried out. You can do these either by clicking on *Refresh sales price* (material:refresh[]) directly next to the item. Or you use the button *Refresh sales prices* below the shopping cart. Only after updating the prices you can move on to the next step of the order creation.

The following applies to the sales prices:

* If you manually enter a price, this price will remain in the drop-down list and can be selected for this order, even if you navigate back and forth or select a different sales price in between.
* If no valid sales price could be detected, a sales price has to be entered manually. Completing an order is only possible with valid sales prices.
* It is allowed to enter the price 0.00.
* If a price is entered that is lower than the purchase price, an error message is displayed. You can still enter this lower price if you want to.
* Carry out all changes for order items in this step of the order creation, in the third and last step this is not possible. Navigating back and forth through the steps remains possible.

Moreover, you can also delete items in the shopping cart. To do so, click on *Delete* (material:delete[]). Another option for editing order items are the properties. To do so, take note of the following chapter <<#order-item-properties, Order item properties>>.

Once you added all the items in the required quantity and with the right prices to the shopping cart, click on *Overview*. You can also go back to the order details by clicking on *Order details*. Items in the shopping cart are saved when you go back and forth.

[.collapseBox]
.*Customising the shopping cart table*
--
The shopping cart table is customisable. This means that you can decide which table columns are displayed in which order.  The following table columns are selected by default before the table is customised:

* Item ID/Variation ID
* Variation no.
* Item name
* Attributes
* System purchase price
* Price
* Surcharge total = The sum of the order item properties’ surcharges.
* Total amount = The item price plus the order item properties’ surcharges.
* Discount = Includes the discount that was entered in the order details in the first step of the order creation.
* Warehouse
* Quantity
* Action

The following table columns can be displayed but are not shown by default:

* Item ID
* Variation ID
* Price selection
* Customer class discount = The customer class discount in per cent as applied to the selected sales price.
* Category discount = The category discount in per cent as applied to the selected sales price.

Adapt the table according to your requirements and your workflow.  When you have adapted the table, these settings are saved. The table remains editable, you can change it any time.

[.instruction]
Customising the table:

. Click on *Configure columns* (material:settings[]). +
→ The window *Configure columns* opens.
. Select which columns are to be displayed.
. Move (material:sort[]) the columns so they are displayed in the order you need them in.
. Click on *Confirm* to save your settings.

--

[#order-item-properties]
=== Order item properties

You can edit the order item properties in the shopping cart. Any changes made here only apply to the order items of this order. The properties themselves stay as they are configured in the system. Only the properties that have already been created and configured in the system are available in the order creation. +
If you want to create and edit properties or are not yet familiar with the structure of properties, refer to the manual chapter xref:item:properties.adoc#500[Properties] first.

In order to link a property with an order item, the property has to be marked as *Order property* in the *Options* area of the property settings. Also set possible surcharges and VAT rates for the property in the xref:item:properties.adoc#property-options[Options] area. The values added here will be included in the order calculations.

If a property is already linked with an order item, it will be displayed on the corresponding order item. How the order item properties are displayed depends on your <<#intable-shopping-cart-type, Shopping cart type>> selection.

[tabs]
====
Shopping cart as side cart::
+
--
The value of a property is displayed as a chip under the corresponding order item. Removing a chip deletes the order item property, which means that the property is not included in this order and the order calculations. +
To edit the properties or to add more already existing properties, click on material:edit[]underneath *Order item properties*. The same editing window as from the shopping cart as table opens.

--

Shopping cart as table::
+
--
The properties are displayed in a second row of the table underneath the corresponding order item. There, you can find information about the *Name*, *Value*, *Surcharge* and *VAT %* of the property. You can edit the *VAT %*, i.e. the saved VAT rate of the property, directly in the table if the property allows for that. Moreover, you can *delete* (material:delete[]) order item properties in the table. Deleted properties are not included in this order and the calculations. +
To edit the properties or to add more already existing properties, click on *Edit properties* (material:edit[]). The same editing window as from the shopping cart as side cart opens.

--
====

The following information about order item properties can be found in the editing window *Edit properties of [selected order item with ID]*:

* *Name* = The name of the property is displayed. A red asterisk marks the property as a *required* property. Whether a property is *required* is determined in the xref:item:properties.adoc#property-options[Options] area of the property settings. Select *Required* from the *Order options* drop-down list.
* *Value* = The value of the property is displayed. The value is editable. Depending on the property type, you can either make a selection, edit the value, add a value or upload a file. The changes are only valid for this order.
* *Surcharge* = The surcharge of the property is displayed, if a surcharge is set for the property. The surcharge is editable. The changes are only valid for this order.

Moreover, some further editing options are available to you here. By clicking on *Delete* (material:delete[]), you remove the property from this order item. This property is then not included in the order and the order calculations. +
You can also add more already existing properties. Select a property from the drop-down list *Select property* and add it to this order item by clicking on *Add property* (icon:plus-square[role="green"]). +
Once you are done with all adaptations, click on *Save properties*. By clicking on *Cancel*, none of the changes are saved. he editing window is closed and you can edit the properties of other order items in the same way.

If you want to have the properties displayed on documents, you have to set this in the configurations of the property itself. Make sure that the following options are selected in the xref:item:properties.adoc#property-visibilities[Visibilities] area of each property:

* *Display on documents* from the *Display everywhere* drop-down list as well as
* the correct clients from the *Clients* drop-down list.

Where on the document the properties are displayed depends on each property and its configurations. Properties for which no VAT rate was set in the *Options* area of the configuration or for which the option *Display as additional costs* in the *Order property* drop-down list was selected are displayed underneath the totals. Other properties are displayed in the order item table.

When you are done with editing the order item properties and the shopping cart, the next step in the order creation is the *Overview*. In this step, the order item properties are not displayed again. Therefore, make sure that you are done with all changes before you move forward with the order creation.

[#complete-order]
=== Overview: Completing the order

In this last step, the order is completed. Different amounts of the order are displayed in info boxes above the order details:

* Total amount (gross): Shows the calculated total gross amount of the order. The status bar is displayed in green when the order is a gross order. Otherwise the status bar is grey.
* Total amount (net): Shows the calculated total net amount of the order. The status bar is displayed in green when the order is a net order. Otherwise the status bar is grey.
* Total number of items: Shows the total number of order items of this order. The status bar is always displayed in grey.
* Coupon amount: Shows the granted discount from promotional coupons.  The status bar is displayed in orange when a promotional coupon was used in this order.  Otherwise the status bar is grey.
* Order discount: Shows the discount amount resulting from the discount granted in the first step of the order creation. The summed up discount amount of all the order items is calculated. The status bar is displayed in orange when a discount was set in the first step. Otherwise the status bar is grey.
* Open amount: Shows the open invoice amount the customer has to pay. The status bar is displayed in green when the amount is zero, i.e. the customer has already paid the full invoice amount. Red means the full invoice amount is still open. Orange means the invoice amount is still partially open.

In the order details, the *Shipping method* and the *Shipping costs* can be adapted if required. +
Moreover, you can enter one or more coupon codes in the *Coupon codes* field to redeem these with this order. Enter a coupon code and press _enter_ or click outside the field. It is checked whether the coupon can be redeemed. Redeemable coupons turn green, display the value of the coupon and show with a tooltip what type of coupon it is. Irredeemable coupon codes turn red and display *Not redeemable* instead of the entered code. Repeat this with more coupon codes, if needed. +
The values of the coupons are set off against the order value. Coupons are not added as an order position in the shopping cart. Coupons cannot be redeemed for offers.  This means that the input field *Coupon codes* is only available for order creation and not for offer creation.

Below the order details, a table with the added order items is displayed. In addition to the information given in the previous view, more prices and the VAT % rate are shown. The VAT rates are editable if you allowed this in the <<#carrying-out-standard-settings, default settings>>. +
Moreover, you can adapt the *item description* in this table. The adapted item description is only taken over for this individual order. This means that the changed description is added to the order data and also the order documents of this particular order. Outside this order, the item description already saved in the system remains. The limit for the *Description* is 1,500 characters.

[.collapseBox]
.*Customising the table*
--
The table in the last step of the order create is customisable. This means that you can decide which table columns are displayed in which order. The following table columns are selected by default before the table is customised:

* Item ID/Variation ID
* Variation no.
* Item name
* Attributes
* Variation name
* System purchase price
* Price selection
* Net price
* Gross price
* Total amount = The item price plus the order item properties’ surcharges.
* Discount = Includes the discount that was entered in the order details in the first step of the order creation.
* Warehouse
* VAT %
* Delete icon

The following table columns can be displayed but are not shown by default:

* Quantity
* Item ID
* Variation ID
* Barcode
* Surcharge total = The sum of the order item properties’ surcharges.
* Customer class discount = The customer class discount in per cent as applied to the selected sales price.
* Category discount = The category discount in per cent as applied to the selected sales price.

Adapt the table according to your requirements and your workflow.  When you have adapted the table, these settings are saved. The table remains editable, you can change it any time.

[.instruction]
Customising the table:

. Click on *Configure columns* (material:settings[]). +
→ The window *Configure columns* opens.
. Select which columns are to be displayed.
. Move (material:sort[]) the columns so they are displayed in the order you need them in.
. Click on *Confirm* to save your settings.

--

If you change shipping costs or the shipping method, the order has to be recalculated because the price calculation depends on these factors. Therefore, you have to click on *Recalculate order* before you can complete the order. By carrying out a recalculation, the total amounts are updated. To complete the order, click on *Complete order*. The order is now created and you are redirected to the order overview of the contact. The order is now also available in the order overview in the *Orders » Orders (Test phase)* menu.

[#create-and-apply-order-templates]
== Creating and applying order templates

Order templates are created in the *Setup » Orders » Order template* menu. You can select them when you manually create a new order or you can apply an order template via an xref:automation:event-procedures.adoc#intable-order-template[event procedure]. If you select an order template for an order, the order template data is applied to the order. After using an order template, you can edit an order as usual as well as change and adapt order information.

To create an order template proceed as follows:

[.instruction]
Creating an order template:

. Go to the *Setup » Orders » Order template* menu.
. Click on the *New template* tab.
. Enter a unique *Name*.
. Select a *Payment method* and an *Order status* from the corresponding drop-down list.
. Optionally add items by clicking on *Add item*.
. Save (icon:save[role="green"]) the order template.

[[table-order-templates]]
.Order template fields
[cols="1,3"]
|====
|Setting |Explanation

|*Name*
|Enter a name for the order template. This name is displayed in drop-down lists for selecting the order template.

|*Payment method*
|Select a payment method from the drop-down list. When applying the order template to an order, this payment method is added to the order.

|*Order status*
|Select an order status from the drop-down list. When applying the order template to an order, the order is moved to this order status.

|*Item*
|If you already added items to the order template, they are displayed in this table. Adding items is optional. The items that are displayed here will be added to the order when using this order template. The quantity and the item text are displayed for each item. Moreover, you can delete items from the order template in this table. +
*_Note:_* When you apply an order template with items, the order you want to apply it to should not have any items added yet. Already added items to the order are overwritten. But you can add more items to an order after applying an order template.

|*Add item(s)*
|Optionally, you can add items to the order template in this tab. These items are added to the order when the order template is applied. +
Set filters and execute a search (icon:search[role="blue"]) to display items. Add (icon:cart-plus[role="green"]) the desired items to the order template. The added items are displayed in the *Item* tab. +
*Quantity* = You can add an item more than once. Each item is displayed in a new table row. Alternatively, you can adapt the *Quantity* column of an item in the *Item* tab of the table.

|====

You can edit and adapt order templates at any time. After editing an order template, you have to save (icon:save[role="green"]) the order template again. Adaptations to order templates are not retroactively applied to orders but are valid from the moment of adaptation on.

Order templates are only applied to orders if you decide so. If you always want to apply an order template to specific orders, we recommend using an xref:automation:event-procedures.adoc#intable-order-template[event procedure]. Determine in the event procedure by the selection of the event and the filters, when and to which orders which order template should be applied.

To apply an order template when manually creating an order, select the required order template from the drop-down list *Use template* in the *Order data* area. In the new order creation (Beta), you can select an order template in the first step of the order creation from the *Order template* drop-down list above the order details.
