= Order type: Repair

:keywords: repair, repair status, repair condition
:author: team-order-core
:description: Learn how to use the order type repair to create repairs for items that have been returned or are in need of repair. Moreover, find out how to create statuses and conditions for repairs.

In plentymarkets, repairs are represented by a separate order type. Repairs include items that have been returned and are in need of repair. Thus, repair orders can only be created from xref:orders:order-type-return.adoc#[return orders].

[#repair-standard-status]
== Defining standard statuses for repairs

At first, define standard statuses for working with repairs. Pay attention to the information given in the following table.

[[table-standard-status]]
.Standard statuses for repairs
[cols="1,3"]
|===
|Column |Explanation

| [#intable-default-status-repairs]*Standard status*
|Select which status should be automatically set for repairs.

| [#intable-default-status-reversal]*Standard status for resetting outgoing items*
|Select which status should be automatically set for resetting outgoing items. +
Select the status *Last status* if you do not need a specific status. This setting returns the status to what it was before outgoing items were booked.

|===

[#repair-statuses]
== Creating repair statuses

Before creating returns, create different *Statuses* representing the individual steps of the repair process. This allows you to precisely track the repair process in your plentymarkets system. You can save return statuses in multiple languages.

[.instruction]
Creating repair statuses:

. Go to *Setup » Orders » Order types » Repair*.
. At the top left, click on *Add new repair status* (material:add[]). +
→ The *Add new repair status* window opens.
. Enter a *Repair status ID*.
. Enter a name for the respective language. +
*_Tip:_* Click on *Add language* (material:add[]) to add further languages and enter a name for all selected languages. +
. Click on *Create* (material:add[role=green]) to create the repair status.

[#configure-columns-repair-statuses]
== Configuring columns for repair statuses

In the overview, you can decide which columns should be displayed in the table for repair statuses and also define the order in which they are shown. In order to configure the columns, proceed as follows.

[.instruction]
Configuring columns for repair statuses:

. Go to *Setup » Orders » Order types » Repair*.
. At the top right in the table of the repair statuses, click on *Configure columns* (material:settings[]). +
→ The window *Configure columns* opens.
. Select (material:done[]) the columns you want to be displayed. Pay attention to the explanations given in <<table-repair-statuses-columns>>.
. Move (material:drag_indicator[]) the columns via drag-and-drop to the desired position until they are displayed in the desired order.
. Add or remove columns according to your needs.
. Click on *Confirm*. +
→ The settings are saved.

[[table-repair-statuses-columns]]
.Columns for repair statuses
[cols="1,3"]
|===
|Column |Explanation

| *Repair status ID*
|Displays the ID of the repair status.

| *Name*
|Displays the name of the repair status.

| *Name (language)*
|Displays the name of the repair status for the language that is shown in brackets. Select all the languages that you need.

| *Actions*
|Displays the functionalities for editing (material:edit[]) and deleting (material:delete[]) the repair status at the end of the line.

|===

[#edit-repair-status]
=== Editing a repair status

In order to edit a repair status, proceed as follows. Note that only the name, but not the ID of the repair status can be changed.

[.instruction]
Editing a repair status:

. Go to *Setup » Orders » Order types » Repair*.
. On the right in the line of the repair status that you want to edit, click on *Edit repair status* (material:edit[]). +
→ The settings of the repair status open.
. Edit the name for one or several languages.
. *Save* (material:save[role=skyBlue]) the changes.

[#delete-repair-status]
=== Deleting a repair status

In order to delete a repair status, proceed as follows.

. Go to *Setup » Orders » Order types » Repair*.
. On the right in the line of the repair status that you want to delete, click on *Delete repair status* (material:delete[]). +
→ The repair status is deleted.

[#repair-conditions]
== Creating item conditions

You can use a *condition* to describe an item in more detail, e.g. if the item needs a repair after all or if you want to determine that a repair is not possible for the item. Conditions can be entered in multiple languages.

[.instruction]
Creating item conditions:

. Go to *Setup » Orders » Order types » Repair*.
. At the top left, click on *Add new item condition* (material:add[]). +
→ The *Add new item condition* window opens.
. Enter an *Item condition ID*.
. Enter a name for the respective language. +
*_Tip:_* Click on *Add language* (material:add[]) to add further languages and enter a name for all selected languages. +
. Click on *Create* (material:add[role=green]) to create the item condition.

[#configure-columns-item-conditions]
== Configuring columns for item conditions

In the overview, you can decide which columns should be displayed in the table for item conditions and also define the order in which they are shown. In order to configure the columns, proceed as follows.

[.instruction]
Configuring columns for item conditions:

. Go to *Setup » Orders » Order types » Repair*.
. At the top right in the table of the item conditions, click on *Configure columns* (material:settings[]). +
→ The window *Configure columns* opens.
. Select (material:done[]) the columns you want to be displayed. Pay attention to the explanations given in <<table-item-conditions-columns>>.
. Move (material:drag_indicator[]) the columns via drag-and-drop to the desired position until they are displayed in the desired order.
. Add or remove columns according to your needs.
. Click on *Confirm*. +
→ The settings are saved.

[[table-item-conditions-columns]]
.Columns for item conditions
[cols="1,3"]
|===
|Column |Explanation

| *Item condition ID*
|Displays the ID of the item condition.

| *Name*
|Displays the name of the item condition.

| *Name (language)*
|Displays the name of the item condition for the language that is shown in brackets. Select all the languages that you need.

| *Actions*
|Displays the functionalities for editing (material:edit[]) and deleting (material:delete[]) the item condition at the end of the line.

|===

[#edit-item-condition]
=== Editing an item condition

In order to edit an item condition, proceed as follows. Note that only the name, but not the ID of the item condition can be changed.

[.instruction]
Editing an item condition:

. Go to *Setup » Orders » Order types » Repair*.
. On the right in the line of the item condition that you want to edit, click on *Edit item condition* (material:edit[]). +
→ The settings of the item condition open.
. Edit the name for one or several languages.
. *Save* (material:save[role=skyBlue]) the changes.

[#delete-item-condition]
=== Deleting an item condition

In order to delete an item condition, proceed as follows.

. Go to *Setup » Orders » Order types » Repair*.
. On the right in the line of the item condition that you want to delete, click on *Delete item condition* (material:delete[]). +
→ The item condition is deleted.

[TIP]
.Refresh data
====
Above the respective table, click on *Refresh data* (material:refresh[]) in order to update the table’s data.
====

[#create-repair]
== Creating a repair

[.instruction]
Proceed as described below to create a repair:

. Go to *Orders » Orders*.
. Carry out the search (material:search[]) to display orders.
. Open the return for which you want to create a repair. Note that returns can only be opened in the list view.
. In the tool bar at the top, click on *Create orders* > *Repair*.
. Select the option *For specific order items*. +
→ The overview for creating the repair opens.
. Carry out the settings. Pay attention to the explanations given in <<table-settings-repair>>.
. *Save* (material:save[]) the settings. +
→ The repair is created.

[[table-settings-repair]]
.Settings for registering a repair
[cols="1,3"]
|===
|Setting |Explanation

| *Status*
|Select a status from the drop-down list. The default status that was saved in the *Setup » Orders » Settings* menu is selected by default.

| *Owner*
|Select an owner to the drop-down list to assign this owner to the repair.

| *Repair status*
|Select a repair status from the drop-down list. The status will apply for all items included in the repair. +

2+^| *Item information*

| *Add all open order items into the cart* (material:playlist_add[])
|Adds all open order items to the shopping cart.

| *Item ID*
|Shows the item ID.

| *Variation ID*
|Displays the variation ID.

| *Variation no.*
|Shows the variation number.

| *Quantity*
|Displays the item quantity. If needed, adjust the quantity.

| *Remaining quantity*
|Displays the remaining quantity of the item.

| *Open quantity*
|Displays the open quantity of the item.

| *Item name*
|Displays the name of the item.

| *Add items to shopping cart* (material:add_shopping_cart[])
|Only adds specific items to the repair. This button is only displayed if at least 1 item is available. +
*_Tip:_* If needed, adjust the item quantity in the *Quantity* field.

2+^| *Shopping cart*

| *Remove items from shopping cart* (material:delete[])
|Removes all items from the shopping cart. If you only want to remove specific items, click on *Remove item from shopping cart* (material:delete[]) on the right of the respective item.

| *Item ID*
|Shows the item ID.

| *Variation ID*
|Displays the variation ID.

| *Quantity*
|Displays the item quantity. If needed, adjust the quantity.

| *Item name*
|Displays the item name. If needed, adjust the name.

| *Item status*
|Displays the item status. If needed, select another status from the drop-down list.

|===

[#edit-repair]
== Editing a repair

Depending on the return reason or the condition of the items that need to be repaired, different steps have to be carried out during the process. +
Due to the fact that repairs are a separate order type, you can click on *Create orders* in the toolbar at the top of a repair and directly create a xref:orders:order-type-credit-note.adoc#[credit note], a xref:orders:order-type-warranty.adoc#[warranty] or a xref:orders:order-type-return.adoc#[return].
