= Order type: Warranty

:keywords: warranty, replacement, new delivery, refund
:author: team-order-core
:description: Learn how to create warranties with the order type warranty in order to send a new item to your customer or to refund the customer's costs. Moreover, find out how to determine the shipping costs for refunds.

Warranties are quite similar to xref:orders:order-type-return.adoc#[returns]. In both cases, the items of an order in *status 7* will be sent back to you. In contrast to a return, customers expect a new delivery or a refund in the form of a xref:orders:order-type-credit-note.adoc#[credit note].

[TIP]
.Guarantee vs. warranty
======
In contrast to a guarantee voluntarily provided by the seller, the warranty represents the *legal obligation* of the seller to eliminate defects and damages that already existed when the item was delivered to the customer free of charge. Depending on the characteristics of the items and the legislation that applies, customers can have a right to claim a warranty up to 2 or 3 years after the purchase of the item. If damage occurs more than 6 months after receipt of the items, the customer has to prove that they already existed upon delivery.
======

If the conditions for a warranty apply, you can decide whether to refund the customer’s costs or to replace the damaged item with a new one. Create a *warranty* to replace the damaged item. To refund the customer, create a xref:orders:order-type-credit-note.adoc#[credit note] for the warranty. Go to *Setup » Orders » Settings* to determine whether the *Shipping costs* should be covered xref:orders:basic-settings.adoc#intable-shipping-costs-in-warranty[in the warranty].

[TIP]
.Warranty settings
======
If you create a warranty directly within an order, the *shipping profile* of the main order is automatically adopted. However, the settings can be changed in the warranty’s editing window. For *delivery orders*, the correct warehouse is automatically selected as well. The *payment method* for a warranty can be changed.
======

[#create-warranty]
== Creating a warranty

In general, a warranty is created out of a return order. However, it is also possible to create it out of the original main order.

We recommend creating the warranty directly in the main order if the customer finds fault with the ordered items after delivery and you decide against proceeding with a return order.

If you wish to proceed with a return order to examine the damaged items, create a return order first and create the warranty in the return order.

:ordertype: warranties

[.instruction]
Creating a warranty:

. Go to *Orders » Orders (Test phase)*.
. Carry out the search (material:search[]) to display orders.
. Open the main order or the return order for which you want to create a warranty.
. At the top, click on *Create orders* (material:shopping_cart[]).
. Select an option. Note <<table-create-{ordertype}>>.
. In case you selected the option *For specific order items*, carry out the settings. Pay attention to the explanations given in <<table-create-warranty>>.
. *Save* (material:save[]) the settings. +
→ The warranty is created.

include::partial$create-order-type.adoc[]

[[table-create-warranty]]
.Settings for warranties
[cols="1,3"]
|===
|Setting |Explanation

| *Status*
|Select a status from the drop-down list.

| *Owner*
|Select the owner from the drop-down list.

| *Copy shipping costs*
|In the drop-down list, determine if the shipping costs should be included in the warranty.

2+^| *Item information*

| *Add all open order items into the cart* (material:playlist_add[])
|Adds all open order items to the shopping cart.

| *Item ID*
|Shows the item ID.

| *Variation ID*
|Shows the variation ID.

| *Variation no.*
|Shows the variation number.

| *Quantity*
|Shows the item quantity. If needed, adjust the quantity.

| *Remaining quantity*
|Shows the remaining quantity of the item.

| *Open quantity*
|Shows the open quantity of the item.

| *Item name*
|Shows the name of the item.

| *Add items to shopping cart* (material:add_shopping_cart[])
|Only adds specific items to the warranty. This button is only displayed if at least 1 item is available. +
*_Tip:_* If needed, adjust the item quantity in the *Quantity* field.

2+^| *Shopping cart*

| *Remove items from shopping cart* (material:delete[])
|Removes all items from the shopping cart. If you only want to remove specific items, click on *Remove item from shopping cart* (material:delete[]) on the right of the respective item.

| *Item ID*
|Shows the item ID.

| *Variation ID*
|Shows the variation ID.

| *Quantity*
|Shows the item quantity. If needed, adjust the quantity.

| *Item name*
|Shows the item name. If needed, adjust the name.

|===

[#determine-shipping-costs]
== Determining shipping costs for refunds

For child orders of the type *credit note* or *warranty*, you can define the shipping costs for customers in case of a refund. In order to determine the shipping costs, proceed as follows.

[TIP]
.Settings for shipping cost refunds for warranties or credit notes
======
Define in the *Setup » Orders » Settings* menu whether shipping costs should be refunded retroactively for warranties and credit notes. To do so, go to the settings *Include shipping costs in warranty* and *Include shipping costs in credit note* and select *Yes* to refund shipping costs or *No* if you want the customer to pay the shipping costs.
======

[.instruction]
Determining shipping costs for refunds:

. Go to *Orders » Orders (Test phase)*.
. Carry out the search (material:search[]) to display orders.
. Open the order for which you want to define the shipping costs.
. Click on *Create orders* (material:shopping_cart[]) and select the option *Warranty or Credit note > For specific order items*. +
→ The child order of the type *Warranty* or *Credit note* opens.
. In the *Copy shipping costs* field of the item, select the option *Yes* in order to apply the shipping costs. +
→ The *Shipping cost in £* field becomes visible. +
*_Note:_* The shipping costs of the main order are preset.
. In case you want to adjust the amount of shipping costs that should be refunded for customers, enter another amount into the *Shipping costs in £* field.
. On the right, click on *Add items to shopping cart* (material:add_shopping_cart[]). +
→ The item is added to the shopping cart.
. *Save* (material:save[]) the settings. +
→ The shipping costs for the item’s refund are saved.

[#edit-warranty]
== Editing a warranty

Existing warranties are displayed in the overview. Open the warranty to enter an additional *price* if you decide to replace the damaged item by providing the customer with a similar but more expensive one. The quantities of the items included in the warranty can be changed here as well. Proceed as described below to edit a warranty.

[.instruction]
Editing a warranty:

. Go to *Orders » Orders (Test phase)*.
. At the top, click on *Filter* (material:tune[]).
. Select the option *Warranty* for the filter *Order type*.
. Click on *Search* (material:search[]). +
→ All warranties are listed.
. Click on the row of the warranty that you want to edit. +
→ The warranty is opened.
. In the *Order items* area, click on *Edit* (material:edit[]). +
→ The item view is opened and you can adjust the settings.
. *Save* (material:save[]) the settings.

[#finalise-warranty]
== Completing a warranty

In order to complete a warranty for which an additional charge is billed for the replacement, an invoice has to be created within the warranty. In case the customer agrees to a discount on the damaged item instead of proceeding with a return order, you have to create a credit note in the original main order.

Proceed as described below to complete a warranty by replacing items.

[.instruction]
Completing a warranty with a replacement:

. Go to *Orders » Orders (Test phase)*.
. Carry out the search (material:search[]) to display orders.
. On the right in the row of the warranty, click on the context menu (material:more_vert[]).
. Select *Create document* > *Invoice*. +
icon:map-signs[] *_Or:_* Open the warranty that you want to complete.
. Go to the *Documents* area.
. Click on *Create document* (material:add[]).
. Select the option *Invoice*. +
→ The window to create the invoice opens.
. Carry out the settings, if required.
. Click on *Create*. +
→ The invoice is generated.
. Then, click on *Book outgoing items* (material:input) in the toolbar at the top.
. If needed, change the date of outgoing items.
. Click on *Book*. +
→ Outgoing items are booked and the *Status* automatically changes to *[7] Outgoing items booked*.
. Then, go to the *Status and tags* area.
. Manually set the status of the warranty to status *[10] Warranty*.
. *Save* (material:save[]) the settings.

[TIP]
.Booking incoming payments for warranties
======
Generally, incoming payments for warranties only have to be booked it an additional charge has been negotiated with the customer. In this case, book the incoming payment after the customer has made it in the *Payment* area of the warranty.
======
