= Order type: Advance order

:keywords: advance order, payment request, release date
:author: team-order-core

Advance orders are an important tool in the marketing mix for e-commerce. Often, items can be ordered at a reduced introductory price before they actually become available. This represents an unusual case for stock management since items that are not available yet cannot be allocated to a warehouse.

In plentymarkets, advance orders are easily set up. Just use the order type *Advance order* for manually created orders.

To be able to receive advance orders via your online shop, you have to enter the release date and availability for the items. Carry out the settings for the items as described below.

[IMPORTANT]
.Manual order entry
======
The order type *Advance order* can only be selected when manually entering orders.
======

[#release-date]
== Release date

You can find the option *Release date* within the area for editing items, listed in the *Available* tab. Here, you can use the calendar to enter the date on which the item will become available. To do so, proceed as described below.

[.instruction]
Entering the release date:

. Go to *Item » Edit item*.
. Open the item you want to offer in advance.
. Open the variation you want to offer in advance.
. Go to the *Settings* tab of the variation and scroll down to the section *Availability*.
. Enter the date on which the item is to be available in the field *Release date*.
. *Save* (icon:save[role="green"]) the settings.

Next, make sure that this date will also be displayed to your customers. Proceed as described below.

[.instruction]
Displaying the release date in the online shop:

. Go to *CMS » Web design » Folder: Layout » Folder: ItemView*.
. Open the template *ItemViewSingleItem*.
. Insert the template variable *$ReleaseDate*.
. *Save* the settings.

[#item-availability]
== Item availability

Another requirement is to correctly set the *Item availability*. Proceed as described below.

[.instruction]
Setting up item availability for advance orders:

. Go to *Item » Edit item*.
. Open the item you want to offer in advance.
. Open the *Settings* tab.
. Select *No limitation* for the *Limitation* option. +
→ The item can now be ordered and thus purchased, even without actually being in stock yet.

[TIP]
.Maximum order quantity
====
In order to prevent other online sellers from misusing your advance orders to completely buy out your item a reduced price, enter a value for the option *Maximum order quantity* in the *Available* tab. If you enter the value *1* there, the item can only be purchased once per order. If you set the maximum order quantity to *0*, the item will be sold without limitation.
====

[#payment-request-advance-orders]
== Setting up a payment request for advance orders

Usually, the option *Shipping date* is not used for ordinary orders. However, it can be helpful to use this option for advance orders. If the release date of an item is in the future, the release date will then be saved as the order’s shipping date since deliveries can only take place once the item is released. You can use the shipping date as a filter option in the order search and in the procedure manager.

Advance orders are usually generated some time before an item appears and are not paid for by the customers at the time when they are ordered. That’s why it is useful to inform your customers a few days in advance about the upcoming shipment and request payment from them. Use the *Procedure manager* to automate this process. A few days before shipping takes place, the procedure manager will automatically send the customers a reminder email stating your bank details and providing a link to the checkout. Proceed as described below to set up the automatic payment request.

[.instruction]
Setting up a payment request via email:

. Create a suitable xref:crm:sending-emails.adoc#1200[email template].
. Go to *Setup » Orders » Procedures*.
. Click on the New procedure tab.
. Enter a *name* in the *Settings* tab.
. Select a time from the drop-down list next to the option *Execute every day at*.
. Activate the option *Active* (icon:check-square[role="blue"]) to activate the procedure.
. Click on the *Filter* tab.
. Set the *Status* to *[3] Waiting for payment*.
. Select an option for *Shipped on*, e.g. *in 4 days*.
. Click on the *Procedure* tab.
. Select the previously created email template for the option *Send email template*. With this procedure, this template will automatically be sent to the customer.
. Click on *Save* (icon:save[role="green"]) to save the procedure.
