= Order type: Advance order

:keywords: advance order, payment request, release date
:author: team-order-core
:description: Learn how to create advance orders with the order type advance order. Moreover, find out how to add a release date, set the item availability and set up a payment request for advance orders.

Advance orders are an important tool in the marketing mix for e-commerce. Often, items can be ordered at a reduced introductory price before they actually become available. This represents an unusual case for stock management since items that are not available yet cannot be allocated to a warehouse.

In plentymarkets, advance orders are easily set up. Just use the order type *Advance order* for manually created orders.

To be able to receive advance orders, two requirements must be met: the release date and the stock limitation setting.

[IMPORTANT]
.Manual order entry
======
The order type *Advance order* can only be selected when manually entering orders.
======

[#release-date]
== Release date

In the first step, specify when the item will become available.

[.instruction]
Entering the release date:

. Go to *Item » Edit item » [Open variation] » Tab: Settings » Area: Availability*.
//ToDo - sobald die neue Artikel-UI standard ist, dann diesen Satz einblenden und dafür den alten Pfad löschen
//. Go to *Item » Item UI » [Open variation] » Element: Availability and visibility*.
. Enter the date on which the item is to be available in the field *Release date*.
. *Save* (icon:save[role="green"]) the settings.

---

In the second step, make the release data visible to your customers in the plentyShop.

[.instruction]
Displaying the release date in the plentyShop:

. Go to *CMS » ShopBuilder » [Open item view]*.
. Add the widget xref:online-store:shop-builder.adoc#_text[Text » Text] to the item details page.
. Click on the text widget's pencil icon.
. Add the release date to the text field.
To do so, click on *Availability » Release date*.
. *Save* the settings.

[#item-availability]
== Stock limitation

In the first step, allow the item to be purchased, i.e. pre-ordered, without actually being in stock.

[.instruction]
Setting no stock limitation:

. Go to *Item » Edit item » [Open variation] » Tab: Settings » Area: Availability*.
. Find the option *Limitation* and select the setting *None*.
//ToDo - sobald die neue Artikel-UI standard ist, dann diese 2 Sätze einblenden und dafür den alten Sätzen löschen
//. Go to *Item » Item UI » [Open variation] » Element: Availability and visibility*.
//. Find the option *Stock limitation* and select the setting *None*.
. *Save* the settings. +
→ The item can now be purchased, i.e. pre-ordered, without actually being in stock.

---

In the second step, specify the maximum order quantity.
For example, this prevents the competition from buying out your entire stock at a reduced, introductory price.

[.instruction]
Setting the maximum order quantity:

. Go to *Item » Edit item » [Open variation] » Tab: Settings » Area: Availability*.
. Enter a value into the field *Max. order quantity*.
//ToDo - sobald die neue Artikel-UI standard ist, dann diese 2 Sätze einblenden und dafür den alten Sätzen löschen
//. Go to *Item » Item UI » [Open variation] » Element: Availability and visibility*.
//. Enter a value into the field *Maximum order quantity*.
* Example: if you enter the value 1, then customers will only be able to buy one copy of the item with their order.
* If you enter the value 0 or leave this field empty, then there is no limitation.
. *Save* the settings.

[#payment-request-advance-orders]
== Setting up a payment request for advance orders

Usually, the option *Shipping date* is not used for ordinary orders. However, it can be helpful to use this option for advance orders. If the release date of an item is in the future, the release date will then be saved as the order’s shipping date since deliveries can only take place once the item is released. You can use the shipping date as a filter option in the order search and in the procedure manager.

Advance orders are usually generated some time before an item appears and are not paid for by the customers at the time when they are ordered. That’s why it is useful to inform your customers a few days in advance about the upcoming shipment and request payment from them. Use the *Procedure manager* to automate this process. A few days before shipping takes place, the procedure manager will automatically send the customers a reminder email stating your bank details and providing a link to the checkout. Proceed as described below to set up the automatic payment request.

[.instruction]
Setting up a payment request via email:

. Create a suitable xref:crm:sending-emails.adoc#1200[email template].
. Go to *Setup » Orders » Procedures*.
. Click on the New procedure tab.
. Enter a *name* in the *Settings* tab.
. Select a time from the drop-down list next to the option *Execute every day at*.
. Activate the option *Active* (icon:check-square[role="blue"]) to activate the procedure.
. Click on the *Filter* tab.
. Set the *Status* to *[3] Waiting for payment*.
. Select an option for *Shipped on*, e.g. *in 4 days*.
. Click on the *Procedure* tab.
. Select the previously created email template for the option *Send email template*. With this procedure, this template will automatically be sent to the customer.
. Click on *Save* (icon:save[role="green"]) to save the procedure.
