= Order type: Credit note

:keywords: credit note, credit note order, credit note receipt, cancel credit note receipt, refund, book back items
:author: team-order-core

Credit note orders are used for reimbursing your customers, for example after a xref:orders:order-type-return.adoc#[return order].  A credit note in plentymarkets does not represent a reverse invoice but a refund. Credit note orders are created from an existing main order in the *Orders » Orders (Test phase)* menu. Thus, a credit note is always linked to a main order. The credit note receipts created in a credit note order are included in your financial accounting such as the xref:orders:accounting.adoc#650[DATEV export].

[#saving-standard-status]
== Saving a default status for credit notes

Before you create a credit note, check the xref:orders:preparatory-settings.adoc#intable-default-status-credit-note[default status for credit notes]. You can find the status in the *Setup » Orders » Settings* menu. Adjust the default status, if required and save the settings.

[#create-credit-note]
== Creating a credit note

A credit note is always linked to an already existing order in your plentymarkets system. This is why you have to open the main order in the order overview first before being able to create a credit note.

[TIP]
.Creating a credit note in the main order or child order
======
If a customer has already paid for an order, for example via cash in advance and then decides against the purchase before you have shipped the items and booked outgoing items, we recommend to cancel the order and to create a credit note including all order items.

If payment, outgoing items and delivery have already taken place for one or all order items and it results in a xref:orders:order-type-return.adoc#[return] or a xref:orders:order-type-repair.adoc#[repair order], you should create the credit note directly in the corresponding return or repair order.
======

:ordertype: credit notes

[.instruction]
Creating a credit note order:

. Go to *Orders » Orders (Test phase)*.
. Carry out the search (material:search[]) to display orders.
. Open the order for which a credit note should be created.
. At the top, click on *Create orders* (material:shopping_cart[]) > *Credit note*.
. Select an option. Note <<table-create-{ordertype}>>.
. In case you selected the option *For specific items*, carry out the settings. Pay attention to the explanations given in <<table-create-credit-note>>.
. *Save* (material:save[]) the settings. +
→ The credit note order is created.

include::partial$create-order-type.adoc[]

[[table-create-credit-note]]
.Settings for credit notes
[cols="1,3"]
|===
|Setting |Explanation

| *Status*
|Select a status from the drop-down list.

| *Owner*
|Select the owner from the drop-down list.

| *Copy shipping costs*
|Select an option from the drop-down list to determine if the shipping costs should be copied.

2+^| *Item information*

| *Add all open order items into the cart* (material:playlist_add[])
|Adds all open order items to the shopping cart.

| *Item ID*
|Displays the item ID.

| *Variation ID*
|Displays the variation ID.

| *Variation number*
|Displays the variation number.

| *Quantity*
|Displays the item quantity. If needed, adjust the quantity.

| *Remaining quantity*
|Displays the remaining quantity of the item.

| *Open quantity*
|Displays the open quantity of the item.

| *Item name*
|Displays the name of the item.

| *Add items to shopping cart* (material:add_shopping_cart[])
|Only adds specific items to the return. This button is only displayed if at least 1 item is available. +
*_Tip:_* If needed, adjust the item quantity in the *Quantity* field.

2+^| *Shopping cart*

| *Remove items from shopping cart* (material:delete[])
|Removes all items from the shopping cart. If you only want to remove specific items, click on *Remove item from shopping cart* (material:delete[]) on the right of the respective item.

| *Item ID*
|Displays the item ID.

| *Variation ID*
|Displays the variation ID.

| *Quantity*
|Displays the item quantity. If needed, adjust the quantity.

| *Item name*
|Displays the item name. If needed, adjust the name.

|===

[#create-document-credit-note]
== Creating the credit note document

After creating a credit note order, the document *Credit note* has to be created directly in the credit note order. Before creating this document for the first time, you have to set up the document template in the *Setup » Client » [Select client] » Locations » [Select location] » Documents » Credit note* menu.

Before you generate the document in the credit note order, you should check all order items included in the credit note order and adjust them, if needed.

[.instruction]
Creating the document *Credit note*:

. Go to *Orders » Orders (Test phase)*.
. Carry out the search (material:search[]) to display orders.
. Open the credit note order for which the document *Credit note* is to be created.
. Go to the *Documents* area.
. On the right, click on *Create document* (material:note_add[]).
. Select the option *Credit note*. +
→ The window to create the document opens.
. Carry out the settings, if required.
. Click on *Execute*. +
→ The document *Credit note* is generated.

[#correct-and-cancel-credit-note-document]
== Correcting and reversing the credit note document

In order to correct a credit note and the respective document, you need to generate a *reversal credit note* first. Afterwards, the credit note order is unlocked again. Once a credit note document is created, the credit note order itself is locked for editing, so that tax relevant data cannot be changed. Afterwards, the credit note order can be edited again. You can now correct the data and create a new document for the credit note.

Before the initial generation of the document, go to the *Setup » Client » [Select client] » Location » [Select location] » Documents » Reversal credit note* menu and setup the xref:orders:order-documents.adoc#300[template] for the *reversal credit note* document.

[IMPORTANT]
.Reversing a credit note document
====
The reversing of a credit note is used to correct tax relevant data in a transparent way, but*not* to reverse the credit note order itself.
====

To correct a credit note order by creating a *Reversal credit note*, proceed as follows.

// adjust note_add icon to add once the changes are merged

[.instruction]
Correcting a credit note order:

. Go to *Orders » Orders (Test phase)*.
. Carry out the search (material:search[]) to display orders.
. Open the order that contains the credit note you want to reverse.
. In the *Documents* area, click on *Create document* (material:note_add[]).
. Select the option *Reversal credit note*. +
*_Note:_* This option is only available if you have already created a credit note document.
. Carry out the settings, if required.
. Afterwards, click on *Create*. +
→ The reversal document is created.
. Click on *Create document* (material:note_add[]) once again.
. Select the option *Credit note* in order to generate a new credit note document.
. Carry out the settings, if required.
. Afterwards, click on *Create*. +
→ The new credit note document is generated.

[#booking-refunds]
== Booking refunds

After creating a credit note, the refund of the credited amount has to be booked in your plentymarkets system. Refunds that are transferred via one of the payment providers you have integrated in your system are booked directly in the *Assigned payments* area of the credit note order.

[IMPORTANT]
.Requirements for PayPal
====
*PayPal* does not allow you to enter an amount higher than the amount paid for the original order.
====

[.instruction]
Booking a refund:

. Go to *Orders » Orders (Test phase)*.
. Carry out the search (material:search[]) to display orders.
. Open the credit note order for which you want to book the refund.
. Go to the *Assigned payments* area.
. Click on *Create payment* (material:add[]).
. Carry out the settings. Pay attention to the explanations given in <<table-booking-refunds>>.
. Click on *Book*. +
→ The refund is booked.

[[table-booking-refunds]]
.Settings for booking refunds
[cols="1,3"]
|===

| *Order ID*
|Displays the order ID.

| *Amount*
|Displays the amount that will be refunded. If needed, adjust the amount.

| *Credit/Debit*
|Select from the drop-down list whether it is credit or debit.

| *Currency*
|Select a currency from the drop-down list.

| *Exchange rate*
|Displays the exchange rate.

| *Designated use*
|Enter a designated use.

| *Incoming payment*
|Enter a date for the incoming payment or use the calendar (material:today[]) to select a date. The current date is preset.

|===
