= Order referrer
:keywords: referrer, order referrer, referrers, order origin, sub-referrer, activate referrer, new referrer, create referrer, delete referrer, referrer ID
:author: team-order-core
:description: Learn how to work with order referrers and how to create new referrers. Order referrers help you to assign orders to a specific source. An order referrer is also required for cooperation with affiliate partners.

Omni-channel sale with plentymarkets means that you can use many different channels to offer your items to customers and, therefore, generate orders from many different sources.
Some referrers in the system are set up by default and are fixed entries that cannot be changed. Other referrers are automatically added e.g. when you integrate a plugin or xref:pos:pos.adoc#[plentyPOS].
Referrers from plugins can not be deleted. You can also add referrers manually.

Each referrer has a unique ID. Some referrers have sub-referrers. The ID for a sub-referrer is composed of the ID of the main referrer followed by two decimal numbers. *Amazon*, *eBay* and plentyPOS are examples for main referrers that have sub-referrers.
Each country platform of eBay and Amazon has a sub-referrer just like every till registered with plentyPOS will have a sub-referrer.

Regardless of their referrer, all orders are listed and can be edited in the *Orders » Edit orders* menu. There, the referrer is displayed on every order. The ID of a referrer is displayed in line with further order details. Additionally, the referrer is displayed in the *Settings* tab of an order.
The referrer can be changed but only if it is a manually created referrer and only as long as no invoice was created yet.

[#configure-columns]
== Configuring columns in the overview

The table columns in the overview of the order referrers are configurable. When opening the *Setup » Orders » Order referrer* menu for the first time, the default view of the table is shown. By clicking on *Configure columns* (material:settings[]), you can select the columns that you want to be displayed and also define the order in which they are shown.

[.collapseBox]
.*Configuring columns*
--
When you have adapted the table once, these settings are saved. You can change the layout any time. A list of the available columns can be found in <<table-order-referrer>>. Proceed as follows to adjust the table.

[.instruction]
Configuring columns:

. Go to *Setup » Orders » Order referrer*.
. At the top right, click on *Configure columns* (material:settings[]). +
→ The window *Configure columns* opens.
. Select (material:done[]) the columns you want to be displayed. Pay attention to the explanations given in <<table-order-referrer>>.
. Move (material:drag_indicator[]) the columns via drag-and-drop to the desired position until they are displayed in the desired order.
. Add or remove columns according to your needs.
. Click on *Confirm*. +
→ The settings are saved.
--

The following columns are available for the overview of the order referrers.

[#area-order-referrer]
.Overview of order referrers
[cols="1,3"]
|===
|Setting |Explanation

| *Selection*
|Allows you to select the referrers via a check box so you can carry out the available <<#group-functions, group functions>>.

| *ID*
|Shows the ID of the referrer. Each referrer is given a unique ID. It is automatically assigned by the system and cannot be changed. The IDs 9-100 are available for manually created order referrers. The IDs 1-8 as well as from 101 and higher are reserved for predefined order referrers in the system. Sub-referrers are represented by a decimal ID, for example 2.08 for eBay Germany. +
*_Tip:_* By clicking on the arrow in the table header, you can sort all referrers by ID in ascending or descending order.

| *Name*
|Shows the name of the referrer. The name will be shown in the system, for example in the order search. The name can be changed at any time. +
*_Tip:_* By clicking on the arrow in the table header, you can sort all referrers by name in alphabetical order.

| *Internal name*
|Shows the internal name of the referrer. The internal name cannot be changed and is not displayed in the system. Only predefined order referrers are given an internal name, manually created order referrers not.

| *Owner*
|Shows the owner of the referrer that will be automatically entered as an order’s owner. You can choose from all xref:business-decisions:user-accounts-access.adoc#[users who were given these rights] in the *Setup » Settings » User » Accounts* menu.

| *Visible in selection*
|Shows whether the referrer is visible in the selection. If the referrer is activated (material:done[]), it will be shown in other menus. If the referrer is deactivated, it will not be shown in other menus.

| *Actions*
|On the right of a referrer’s line, <<#further-actions, further actions>> will be available for the referrer.

|===

[TIP]
.Refresh data
======
By clicking on *Refresh data* (material:refresh[]) on the top right, the view is updated.
======

[#search-referrers]
== Searching for referrers

Use one of the following methods to search for referrers. When you start a search, your search settings are displayed at the top as chips.

[.instruction]
Searching for referrers:

. Go to *Setup » Orders » Order referrer*.
.. *_Option 1:_* Click on material:search[] to see a list of all referrers.
.. *_Option 2:_* Enter something into the search field and click on one of the automatic suggestions.
.. *_Option 3:_* Click on material:tune[] to narrow down the search results with filters.

[#using-filters]
=== Using filters

Use filters in order to narrow down the search results for referrers. Your selected filters will be displayed as chips at the top. The following table lists all available filters.

[[table-filters-referrer]]
.Filters for referrers
[cols="1,3"]
|===
|Filter |Explanation

| *Referrer from*
|Enter the lowest referrer you want to filter for.

| *Referrer to*
|Enter the highest referrer you want to filter for.

| *Name*
|Enter a name to filter for referrers with this name.

| *Show main referrers only*
|Place a check mark in order to filter for main referrers only.

| *Own referrers only*
|Place a check mark in order to filter for own referrers only.

|===

.Functions
[cols="1,4a"]
|===
|Element |Explanation

|material:undo[role=darkGrey]
|Resets the selected filter criteria.

|material:search[role=skyBlue] *SEARCH*
|Starts the search.
|===

[#further-actions]
== Carrying out further actions

On the right of a referrer’s line, further actions are available. Here, you can <<#edit-referrer, edit referrers>>, <<copy-client-url, copy client URLs>> and <<delete-referrer, delete referrers>>. In the following chapters, these functions will be further explained.

[#edit-referrer]
=== Editing a referrer

You can edit referrers at any time. To do so, proceed as described below.

[.instruction]
Editing a referrer:

. Go to *Setup » Orders » Order referrer*.
. Carry out the search (material:search[]) to display referrers.
. On the right of the referrer’s line, click on *Edit* (material:edit[]). +
→ A window for editing the referrer opens.
. Carry out the settings. Pay attention to the settings in <<#table-edit-referrer>>.
. Click on *Save* (material:save[role=skyBlue]). +
→ The changes are applied.

[[table-edit-referrer]]
.Editing a referrer
[cols="1,3"]
|===
|Setting |Explanation

| *Name*
|If required, enter a new name.

| *Owner*
|Select another owner’s name from the drop-down list, if required. +
*_Tip:_* Use the <<#group-functions, group function>> *change owner* to change the owner for several referrers at once. In addition, the option *select all* in the table header allows you to change the owner of all referrers at once.

| *Visible in selection*
|If required, change the visibility in the selection. If the toggle button is activated (material:toggle_on[role=skyBlue]), the referrer will be shown in other menus. If the referrer is deactivated, it will not be shown in other menus. +
*_Tip:_* Use the <<#group-functions, group function>> *change visibility* in order to activate or deactivate several referrers for the selection at once. In addition, the option *select all* in the table header allows you to activate or deactivate all referrers for this at once.

|===

[#copy-client-url]
=== Copying a client URL

The client URL is required for affiliate services, for example. It contains the corresponding ID as the so-called Referrer ID. In order to copy a client URL to the clipboard, proceed as follows.

[.instruction]
Copying a client URL:

. Go to *Setup » Orders » Order referrer*.
. Carry out the search (material:search[]) to display referrers.
. On the right of the referrer’s line, click on *Client URLs* (material:remove_red_eye[]). +
→ A window with all client URLs that are available for the referrer opens.
. Click on (terra:copy_clipboard[]) in order to copy the client URL to the clipboard. +
*_Note:_* In case you have more than one client, all client URLs will be displayed underneath each other.

[#delete-referrer]
=== Deleting a referrer

Referrers that you created yourself can be deleted. System referrers however are not deletable. In order to delete a referrer proceed as follows. +
*_Tip:_* Use the <<#group-functions, group function>> *Delete referrer* in order to delete several referrers at once.

[.instruction]
Deleting a referrer:

. Go to *Setup » Orders » Order referrer*.
. Carry out the search (material:search[]) to display referrers.
. On the right of the referrer’s line, click on *Delete* (material:delete[]). +
*_Note:_* The delete icon can only be clicked for deletable referrers.
. Confirm the confirmation message by clicking on *Delete* (material:delete[role=red]). +
→ The referrer is deleted.

[#create-new-referrer]
== Creating a new referrer

You can add referrers to the system at any time. Proceed as described below to manually create an order referrer.

[.instruction]
Creating a new referrer:

. Go to *Setup » Orders » Order referrer*. +
→ The overview of the order referrers opens.
. At the top, click on *Create new referrer* (material:add[]). +
→ The window for creating a new referrer opens.
. Carry out the settings. Pay attention to the information given in <<#table-create-referrer>>.
. Click on *Create* (material:add[role=green]). +
→ The referrer is created.

[[table-create-referrer]]
.Creating a referrer
[cols="1,3"]
|===
|Setting |Explanation

| *Referrer ID*
|The next available ID is already entered. Adjust the ID if required, but note that only the IDs 9-100 can be used for manually created referrers.

| *Name*
|Enter a name for the referrer.

| *Owner*
|Select an owner for the referrer.

| *Visible in selection*
|Activate the toggle button to make the referrer visible in the selection. If the toggle button is activated (material:toggle_on[role=skyBlue]), the referrer will be shown in other menus. If the referrer is deactivated, it will not be shown in other menus.

|===

[#group-functions]
== Using group functions

By using a group function, you can carry out a specific action for all selected order referrers at once. The following table lists and explains all group functions that are available for order referrers.

[[table-group-functions-order-referrer]]
.Group functions for order referrers
[cols="2,1,6a"]
|===
|Group function |Symbol |Explanation

| *Changing the visibility*
|material:remove_red_eye[]
|Changes the visibility in the selection for all selected order referrers. Depending on the setting, the referrers are *visible* or *invisible* in other menus.

| *Change owner*
|material:people_alt[]
|Changes the owner of all selected order referrers. Select another owner from the drop-down list.

| *Delete referrer*
|material:delete[]
|Deletes all selected order referrers. Note that only order referrers that you created yourself can be deleted. Default order referrers in the system cannot be deleted.

|===

[TIP]
.Referrers are required for affiliate service providers
====
The referrer option is also required for cooperation with affiliate partners. These partners will forward potential customers to you via defined tracking URLs and expect a commission in return when the customer purchases something.
====

[#analyse-orders]
== Filtering and evaluating orders by order referrer

The order search in the *Order » Edit orders* menu offers many filters to narrow down the number of results. The *Referrer* filter searches for orders with a specific referrer (for example Client (store), Amazon, eBay etc.). Amazon and eBay have both general referrers and sub-referrers for each of the country platforms.

For monthly overviews, it makes sense to combine filters and to use a date as an additional filter, for example the date when orders were received.

The referrer is important for measuring how well your items sell on different platforms. This information tells you which platforms are most profitable. In addition to the search function in the *Orders » Edit orders* menu, further evaluation options are available in the xref:business-decisions:plenty-bi.adoc#[plentyBI] tool. There, you can select an order referrer and see the revenue that was generated by each referrer. Based on this, you can make well-informed decisions on how to use your advertising budget in the future in an efficient manner.
