= Orders
:id: QV9OPKI
:keywords: Managing orders, order, orders, order processing
:author: team-order-core, team-docs-automation
:description: Learn everything about orders and how to manage orders. Moreover, get to know the different order types.

This area contains all information about incoming orders and how to proceed after receiving orders. Depending on the sales strategy and markets you choose, orders from different xref:orders:order-referrer.adoc#[referrers] are transferred to your plentymarkets system. Apart from your own online shop, order referrers are primarily the different xref:markets:markets.adoc#[markets and price search engines].

Among others, plentymarkets offers you an extensive interface to xref:markets:amazon-setup.adoc#[Amazon]. This interface does not only include automatic synchronisation with Seller Central, but also further services offered by Amazon such as for example xref:markets:amazon-fulfilment.adoc#[Fulfilment by Amazon].

Thanks to the comprehensive xref:markets:ebay-setup.adoc#[eBay] interface integrated in plentymarkets, you can start listings and display eBay shop items on eBay, retrieve orders, automatically post feedback and start dunning procedures for customers ordering via eBay.

Incoming orders are collected in one menu and displayed in a consistent format so that you can easily xref:orders:managing-orders.adoc#1500[manage these orders]. Each order receives an individual *order ID*. Additional steps taking place after incoming orders, such as sending the order confirmation, sending emails or generating xref:orders:order-documents.adoc#[order documents], can be automated. In addition to main orders representing orders placed by customers, several other *order types* exist in plentymarkets. Order types represent different business transactions.

The following order types are available in plentymarkets:

 * xref:orders:managing-orders.adoc#[Order]
 * xref:orders:managing-orders.adoc#240[Offer]
 * xref:orders:managing-orders.adoc#1100[Advance order]
 * xref:orders:managing-orders.adoc#600[Warranty]
 * xref:orders:managing-orders.adoc#500[Credit note order]
 * xref:orders:managing-orders.adoc#300[Delivery order]
 * <<xref:orders:managing-orders.adoc#700[Repair]
 * xref:orders:managing-orders.adoc#400[Return]
 * xref:orders:managing-orders.adoc#800[Multi-order]
 * xref:orders:managing-orders.adoc#850[Multi credit note]

Documents necessary for a quick fulfilment process, such as xref:orders:pick-list.adoc#[pick list] and xref:orders:packing-list.adoc#[packing list] are available in plentymarkets as well.

Use the xref:fulfilment:shipping-centre-2-0.adoc#register-order[Shipping centre] to register shipping orders, edit them if needed of search for particular shipping orders.

In order to manage orders and business transactions efficiently in your plentymarkets system, you can also create xref:automation:setting-up-processes.adoc#[processes] and have them run automatically. Processes offer the highest potential of automation for your plentymarkets system. Moreover, there are also xref:automation:event-procedures.adoc#[event procedures] as well as the xref:automation:procedure-manager.adoc#[procedure manager] available to you to facilitate your order processing with automatisms.
