= Orders
:lang: en
:description: Learn how to set up your accounting and document templates and how to manage orders in plentymarkets.
:position: 60
:url: orders
:id: QV9OPKI
:nav-alias: Overview
:keywords: Managing orders, order, orders, order processing
:author: team-order-payment

This area contains all information about incoming orders and how to proceed after receiving orders. Depending on the sales strategy and markets you choose, orders from different xref:orders:order-referrer.adoc#[referrers>> are transferred to your plentymarkets system. Apart from your own online shop, order referrers are primarily the different <<markets#, markets and price search engines].

Among others, plentymarkets offers you an extensive interface to xref:markets:amazon-fulfilment.adoc#[Fulfilment by Amazon].

Thanks to the comprehensive xref:markets:ebay-setup.adoc#[eBay] interface integrated in plentymarkets, you can start listings and display eBay shop items on eBay, retrieve orders, automatically post feedback and start dunning procedures for customers ordering via eBay.

Incoming orders are collected in one menu and displayed in a consistent format so that you can easily xref:orders:order-documents.adoc#[order documents], can be automated. In addition to main orders representing orders placed by customers, several other *order types* exist in plentymarkets. Order types represent different business transactions.

The following order types are available in plentymarkets:

 * xref:orders:managing-orders.adoc#[Order]
 * xref:orders:managing-orders.adoc#240[Offer]
 * xref:orders:managing-orders.adoc#1100[Advance order]
 * xref:orders:managing-orders.adoc#600[Warranty]
 * xref:orders:managing-orders.adoc#500[Credit note order]
 * xref:orders:managing-orders.adoc#300[Delivery order]
 * <<xref:orders:managing-orders.adoc#700[Repair]
 * xref:orders:managing-orders.adoc#400[Return]
 * xref:orders:managing-orders.adoc#800[Multi-order]
 * xref:orders:managing-orders.adoc#850[Multi credit note]

Documents necessary for a quick fulfilment process, such as xref:orders:packing-list.adoc#[packing list] are available in plentymarkets as well.

Use the xref:fulfilment:shipping-centre.adoc#register-shipping-order[Shipping centre] to register shipping orders, edit them if needed of search for particular shipping orders.

In order to manage orders and business transactions efficiently in your plentymarkets system, you can also create xref:automation:procedure-manager.adoc#[procedure manager] available to you to facilitate your order processing with automatisms.
