= Order type: Return

:keywords: return, return reason, returned items, return slip, book back items, book back stock
:author: team-order-core
:description: Learn how to create returns with the order type return. Moreover, find out how to create return reasons, generate return slips and book back items.

The order type *Return* represents the business case of items being returned. Returns can be registered manually. You can also allow your customers to register returns in the *My account* area of the online shop. Returned items are not booked back into the stock by registering a return. Thus, you first register the returned items and then decide if the items should be booked back or if additional steps such as a repair are needed. A return is a sub-type of an order, because returns are either assigned to a sales order or to a warranty.
Before you register returns, create xref:orders:order-type-return.adoc#enter-return-reasons[return reasons] and <<#status-returned-items, item statuses for returned items>>.

The default status for returns is status 9. This status is automatically assigned to every return that is registered. However, you can always determine another xref:orders:preparatory-settings.adoc#intable-default-status-return[default status for returns] in the *Setup » Orders » Settings* menu.

[#enter-return-reasons]
== Creating reasons for returns

You can create up to 20 return reasons. When registering a return, you select a reason for each order item. Return reasons allow you to see if an item has been returned exceptionally often for the same reason. You can save return reasons in multiple languages.

[.instruction]
Creating reasons for returns

. Go to *Setup » Orders » Order types » Return*.
. Select the *Language* from the drop-down list.
. Enter return *reasons* for the selected language.
. *Save* (icon:save[role="green"]) the settings.
. If needed, repeat these steps for other languages.

[#status-returned-items]
== Entering statuses for returned items

You can enter up to 12 item statuses. You can use these statuses to determine the condition of the returned items and also to track the processing of returned items. In a return, the statuses can be selected in the *Status and tags* area. Create the required statuses to assign them based on different steps of processing. You can save return statuses in multiple languages.

[.instruction]
Entering statuses for returned items:

. Go to *Setup » Orders » Order types » Return*.
. Select the *Language* from the drop-down list.
. Enter the desired *statuses* for assigning returned items for the selected language.
. *Save* (icon:save[role="green"]) the settings.
. If needed, repeat these steps for other languages.

[#create-and-edit-return]
== Registering and editing a return

You register a return manually when a package reaches you or you allow the customers that have a user account at your online shop to register returns in their account. After a return is registered, more possibilities for editing the return appear. For example, you can enter the status of the returned items after registering the return itself.

[#create-return]
=== Registering a return

[.instruction]
Proceed as follows to register a return:

. Go to *Orders » Orders (Test phase)*.
. Carry out the search (material:search[]) to display orders.
. Open the sales order or the warranty for which a return should be created.
. At the top, click on *Create orders* (material:shopping_cart[]) > *Return*.
. Select the option *For specific order items*. +
→ The overview for creating the return opens.
. Carry out the settings. Pay attention to the explanations given in <<table-settings-return>>.
. *Save* (material:save[]) the settings. +
→ The return is registered.

[[table-settings-return]]
.Settings for registering a return
[cols="1,3"]
|===
|Setting |Explanation

| *Status*
|Select a status from the drop-down list. The default status that was saved in the *Setup » Orders » Settings* menu is selected by default.

| *Owner*
|Select an owner to the drop-down list to assign this owner to the return.

| *Transfer reason for return*
|Select a return reason from the drop-down list. The status will apply for all items included in the return. +
If you select a reason here, this reason takes priority over the reasons that can be selected for separate order items.

| *Package code of the return*
|Enter the package code of the return.

2+^| *Item information*

| *Add all open order items into the cart* (material:playlist_add[])
|Adds all open order items to the shopping cart.

| *Item ID*
|Shows the item ID.

| *Variation ID*
|Shows the variation ID.

| *Variation no.*
|Shows the variation number.

| *Quantity*
|Shows the item quantity. If needed, adjust the quantity.

| *Remaining quantity*
|Shows the remaining quantity of the item.

| *Open quantity*
|Shows the open quantity of the item.

| *Item name*
|Shows the name of the item.

| *Add items to shopping cart* (material:add_shopping_cart[])
|Only adds specific items to the return. This button is only displayed if at least 1 item is available. +
*_Tip:_* If needed, adjust the item quantity in the *Quantity* field.

2+^| *Shopping cart*

| *Remove items from shopping cart* (material:delete[])
|Removes all items from the shopping cart. If you only want to remove specific items, click on *Remove item from shopping cart* (material:delete[]) on the right of the respective item.

| *Item ID*
|Shows the item ID.

| *Variation ID*
|Shows the variation ID.

| *Quantity*
|Shows the item quantity. If needed, adjust the quantity.

| *Item name*
|Shows the item name. If needed, adjust the name.

| *Return reason*
|Shows the return reason. If needed, select another return reason from the drop-down list.

| *Item status*
|Shows the item status. If needed, select another status from the drop-down list.

| *Remaining item value [%]*
|Shows the remaining item value in %. If needed, adjust the value.

|===


[#create-return-label]
== Generating a return slip

//link für Rücksendeschein nach Umzug anpassen

You can add a return slip for your customers so that it is delivered in the package along with the items. In this case, the return slip should contain blank fields for the return reasons. You can also allow customers to fill in and print the return slip in the *My account* area so that they can send it to you along with the items they return.
Before you can generate return slips, the document template xref:orders:generating-return-slips.adoc#[return slip] has to be set up in the *Setup » Client » [Select client] » Locations » [Select location] » Documents » Return slip* menu.

[TIP]
.Setting up return slips on the template
======
It’s possible add a blank return slip to every order shipped to your customers. To do so, the return slip can be generated directly in the order. A return does not have to be created for this. Another way to do this is to allow customers in the online shop to register returns in the My account area, where they can also indicate return reasons. Afterwards, the filled-in return slip can be printed. No matter how you provide your customers with return slips: The column *return reasons* has to be positioned below the list of order items so that return reasons can be entered.
======

Check the order items included in the return and change the options if needed, such as the item quantity, before generating a return slip.

[.instruction]
Manually generating a return slip:

. Go to *Orders » Orders (Test phase)*.
. Carry out the search (material:search[]) to display orders.
. On the right in the row of the return, click on the context menu (material:more_vert[]).
. Select *Create document* > *Return slip*. +
icon:map-signs[] *_Or:_* Open the return for which you want to create a return slip.
. Go to the *Documents* area.
. Click on *Create document* (material:add[]).
. Select the option *Return slip*.
. Carry out the settings for the return slip. Pay attention to the explanations given in <<table-generate-return-slip>>.
. Then, click on *Create*.

[[table-generate-return-slip]]
.Settings for return slips
[cols="1,3"]
|===
|Setting |Explanation

| *Date*
|Enter a delivery date or select a date via the calendar (material:today[]). This date will be displayed on the return slip. The current date is preset.

| *Comment*
|Enter an optional comment that will be displayed on the return slip.

|===

[TIP]
.Automatically creating a return slip
======
Set up an event procedure to create a return slip automatically. If you select *New return (from customer)* and filter for the referrer *Webshop*, you can generate pre-filled return slips. Then, simply provide the return slips to your customers via download.
======

[#book-back-items]
== Booking back items

If you receive an item from a return, you can book back the stock completely or partially. You can even reset all outgoing items that were previously booked.

[.instruction]
Booking back items:

//Booking back order items vs. booking back items? Terminologie klären \+ in Konfig und Tabelle ggf. anpassen

. Go to *Orders » Orders (Test phase)*.
. Carry out the search (material:search[]) to display orders.
. Open the return for which you want to book back items.
. Click on the context menu (material:more_vert[]) at the top and select *Book back items* (material:input[]).
. Select *Book back selected positions* to only book back specific positions or *Book back all positions* to book back all positions. Pay attention to the explanations given in <<table-book-back-items>>.
. *Save* (material:save[]) the settings. +
→ The items are booked back.

The method for booking back stock is identical for returns that belong to orders with delivery orders.

[[table-book-back-items]]
.Options for booking back items
[cols="1,3"]
|===
|Setting |Explanation

| *Book back all positions*
|Fully resets outgoing items. The date of outgoing items will be deleted as well.

2+^| *Book back selected positions*

| *Add all open order items into the cart* (material:playlist_add[])
|Adds all open order items to the shopping cart.

| *Quantity*
|Shows the item quantity.

| *Open quantity*
|Shows the open quantity of the item.

| *Remaining quantity*
|Shows the remaining quantity of the item.

| *Batch*
|Shows the batch number of the item.

| *BBD*
|Shows the best before date of the item.

| *Item ID*
|The item's ID

| *Attributes*
|Attributes of the item

| *Variation ID*
|ID of the variation

| *Item name*
|Item name

2+^| *Shopping cart*

| *Item ID*
|The item's ID

| *Item name*
|Item name

| *Variation ID*
|ID of the variation

| *BBD*
|Shows the best before date of the item.

| *Batch*
|Shows the batch number of the item.

| *Warehouse*
|Select the warehouse into which the items should be booked back.

| *Quantity in order*
|Shows the quantity of the items included in the order.

| *Reversal*
|If you wish to book back partial quantities, enter the item quantities manually in this field.

| *Storage location*
|Select the storage location into which the items should be booked back.

|===

[TIP]
.Incoming items from returns
======
An overview of all incoming items for which returns have already been announced is available in the menu xref:stock-management:managing-backlog-lists.adoc#400[Stock » Returns » Supply].
======
