= Order type: Credit note

:keywords: credit note, credit note order, credit note document, credit note receipt, cancel credit note receipt, refund, book back items
:author: team-order-core
:description: Learn how to create credit notes via a credit note order in order to refund your customers with a specific amount. Moreover, find out how to create, correct and cancel the credit note document or how to determine the shipping costs for a refund.

With a credit note, your customers are refunded with an amount. For example, this can be the case after a xref:orders:order-type-return.adoc#[return]. A credit note in plentymarkets does not represent a reverse invoice but a refund. Credit note orders are created from an existing main order in the *Orders » Orders (Test phase)* menu. Thus, a credit note is always linked to a main order. The credit note receipts created in a credit note order are also included in your accounting exports, such as the xref:orders:accounting.adoc#650[DATEV export].

[#saving-standard-status]
== Saving a default status for credit notes

Before you create a credit note, check the *standard status* for credit notes in the *Setup » Orders » Order types » Credit note* menu. Adjust the standard status if required and save the settings. In this menu, you can also define via the option *Copy shipping costs* whether the shipping costs from the order should be copied to the credit note.

[#create-credit-note]
== Creating a credit note

A credit note is always linked to an already existing order in your plentymarkets system. This is why you have to open the main order in the order overview first before being able to create a credit note.

[TIP]
.Creating a credit note in the main order or child order
======
If a customer has already paid for an order, for example via cash in advance and then decides against the purchase before you have shipped the items and booked outgoing items, we recommend to cancel the order and to create a credit note including all order items.

In case payment, outgoing items and delivery have already taken place for one or all order items and it results in a xref:orders:order-type-return.adoc#[return] or a xref:orders:order-type-repair.adoc#[repair order], you should create the credit note directly in the corresponding return or repair order.
======

:ordertype: credit notes

[.instruction]
Creating a credit note order:

. Go to *Orders » Orders (Test phase)*.
. Carry out the search (material:search[]) to display orders.
. Open the order for which a credit note should be created.
. At the top, click on *Create orders* (material:shopping_cart[]) > *Credit note*.
. Select an option. Note <<table-create-{ordertype}>>.
. In case you selected the option *For specific order items*, carry out the settings. Pay attention to the explanations given in <<table-create-credit-note>>.
. *Save* (material:save[]) the settings. +
→ The credit note order is created.

include::partial$create-order-type.adoc[]

[[table-create-credit-note]]
.Settings for credit notes
[cols="1,3"]
|===
|Setting |Explanation

| *Status*
|Select a status from the drop-down list.

| *Owner*
|Select the owner from the drop-down list.

| *Copy shipping costs*
|Select an option from the drop-down list to determine if the shipping costs should be copied.

2+^| *Item information*

| *Add all open order items into the cart* (material:playlist_add[])
|Adds all open order items to the shopping cart.

| *Item ID*
|Shows the item ID.

| *Variation ID*
|Shows the variation ID.

| *Variation no.*
|Shows the variation number.

| *Quantity*
|Shows the item quantity. If needed, adjust the quantity.

| *Remaining quantity*
|Shows the remaining quantity of the item.

| *Open quantity*
|Shows the open quantity of the item.

| *Item name*
|Shows the name of the item.

| *Add items to shopping cart* (material:add_shopping_cart[])
|Only adds specific items to the credit note. This button is only displayed if at least 1 item is available. +
*_Tip:_* If needed, adjust the item quantity in the *Quantity* field.

2+^| *Shopping cart*

| *Remove items from shopping cart* (material:delete[])
|Removes all items from the shopping cart. If you only want to remove specific items, click on *Remove item from shopping cart* (material:delete[]) on the right of the respective item.

| *Item ID*
|Shows the item ID.

| *Variation ID*
|Shows the variation ID.

| *Quantity*
|Shows the item quantity. If needed, adjust the quantity.

| *Item name*
|Shows the item name. If needed, adjust the name.

|===

[#determine-shipping-costs]
== Determining shipping costs for refunds

For child orders of the type *credit note* or *warranty*, you can define the shipping costs for customers in case of a refund. In order to determine the shipping costs, proceed as follows.

[TIP]
.Settings for shipping cost refunds for warranties or credit notes
======
Define in the *Setup » Orders » Settings* menu whether shipping costs should be refunded retroactively for warranties and credit notes. To do so, go to the settings *Include shipping costs in warranty* and *Include shipping costs in credit note* and select *Yes* to refund shipping costs or *No* if you want the customer to pay the shipping costs.
======

[.instruction]
Determining shipping costs for refunds:

. Go to *Orders » Orders (Test phase)*.
. Carry out the search (material:search[]) to display orders.
. Open the order for which you want to define the shipping costs.
. Click on *Create orders* (material:shopping_cart[]) and select the option *Warranty or Credit note > For specific order items*. +
→ The child order of the type *Warranty* or *Credit note* opens.
. In the *Copy shipping costs* field of the item, select the option *Yes* in order to apply the shipping costs. +
→ The *Shipping cost in £* field becomes visible. +
*_Note:_* The shipping costs of the main order are preset.
. In case you want to adjust the amount of shipping costs that should be refunded for customers, enter another amount into the *Shipping costs in £* field.
. On the right, click on *Add items to shopping cart* (material:add_shopping_cart[]). +
→ The item is added to the shopping cart.
. *Save* (material:save[]) the settings. +
→ The shipping costs for the item’s refund are saved.

[#create-document-credit-note]
== Creating the credit note document

After creating a credit note order, the document *Credit note* has to be created directly in the credit note order. Before creating this document for the first time, you have to set up the document template in the *Setup » Client » [Select client] » Locations » [Select location] » Documents » Credit note* menu.

Before you generate the document in the credit note order, you should check all order items included in the credit note order and adjust them, if needed.

[.instruction]
Creating the document *Credit note*:

. Go to *Orders » Orders (Test phase)*.
. Carry out the search (material:search[]) to display orders.
. On the right in the row of the credit note, click on the context menu (material:more_vert[]).
. Select *Create document* > *Credit note*. +
icon:map-signs[] *_Or:_* Open the credit note order for which the document *Credit note* is to be created.
. Go to the *Documents* area.
. Click on *Create document* (material:add[]).
. Select the option *Credit note*. +
→ The window to create the document opens.
. Carry out the settings, if required.
. Click on *Create*. +
→ The document *Credit note* is generated.

[#correct-and-cancel-credit-note-document]
== Correcting and reversing the credit note document

In order to correct a credit note and the respective document, you need to generate a *Reversal credit note* first. Afterwards, the credit note order is unlocked again. Once a credit note document is created, the credit note order itself is locked for editing, so that tax relevant data cannot be changed. Afterwards, the credit note order can be edited again. You can now correct the data and create a new document for the credit note.

Before the initial generation of the document, go to the *Setup » Client » [Select client] » Location » [Select location] » Documents » Reversal document credit note* menu and setup the xref:orders:order-documents-new.adoc#300[template] for the *Reversal credit note* document.

[IMPORTANT]
.Reversing a credit note document
====
The reversing of a credit note is used to correct tax relevant data in a transparent way, but*not* to reverse the credit note order itself.
====

To correct a credit note order by creating a *Reversal credit note*, proceed as follows.

[.instruction]
Correcting a credit note order:

. Go to *Orders » Orders (Test phase)*.
. Carry out the search (material:search[]) to display orders.
. On the right in the row of the credit note, click on the context menu (material:more_vert[]).
. Select *Create documents* > *Reversal credit note*. +
icon:map-signs[] *_Or:_* Open the credit note order for which the document *Reversal credit note* is to be created.
. In the *Documents* area, click on *Create document* (material:add[]).
. Select the option *Reversal credit note*. +
*_Note:_* This option is only available if you have already created a credit note document.
. Carry out the settings, if required.
. Afterwards, click on *Create*. +
→ The reversal document is created.
. Click on *Create document* (material:add[]) once again.
. Select the option *Credit note* in order to generate a new credit note document.
. Carry out the settings, if required.
. Afterwards, click on *Create*. +
→ The new credit note document is generated.

[#booking-refunds]
== Booking refunds

After creating a credit note, the refund of the credited amount has to be booked in your plentymarkets system. Refunds that are transferred via one of the payment providers you have integrated in your system are booked directly in the *Assigned payments* area of the credit note order.

[IMPORTANT]
.Requirements for PayPal
====
*PayPal* does not allow you to enter an amount higher than the amount paid for the original order.
====

[.instruction]
Booking a refund:

. Go to *Orders » Orders (Test phase)*.
. Carry out the search (material:search[]) to display orders.
. Open the credit note order for which you want to book the refund.
. Go to the *Assigned payments* area.
. Click on *Create payment* (material:add[]).
. Carry out the settings. Pay attention to the explanations given in <<table-booking-refunds>>.
. Click on *Book*. +
→ The refund is booked.

[[table-booking-refunds]]
.Settings for booking refunds
[cols="1,3"]
|===

| *Order ID*
|Shows the order ID.

| *Amount*
|Shows the amount that will be refunded. If needed, adjust the amount.

| *Credit/Debit*
|Select from the drop-down list whether it is credit or debit.

| *Currency*
|Select a currency from the drop-down list.

| *Exchange rate*
|Shows the exchange rate.

| *Reason for payment*
|Enter a designated use.

| *Incoming payment*
|Enter a date for the incoming payment or use the calendar (material:today[]) to select a date. The current date is preset.

|===
