= Order type: Offer

:keywords: offer, offers, create, offer, offer document, document template offer
:author: team-order-core, team-docs-automation

You can create individual offers for your customers and send it to them. Use the document *Offer* which you can generate as a PDF file, for example if you want to print it or send it to your customers as an email attachment.

[#document-template-offer]
== Setting up a document template for offers

Before generating the document *Offer*, you have to set up a document template. Go to *Setup » Client » [Select client] » Locations » [Select location] » Documents » Offer* to set up the template. +
Further information and instructions on setting up the document template are available on the xref:orders:order-documents.adoc#[Order documents] page of the manual.

[#create-document-offer]
== Generating a single offer document

Offers are created individually for a customer. This is why the corresponding documents are directly linked with this order of the type *Offer*. This also means that the document offer can only be generated for the order type *Offer*. Therefore, if you want to generate a PDF file for an *offer*, for example, you have to create the order type offer first. You generate the corresponding document as follows.

[.instruction]
Generating an offer (document) manually:

. Go to *Orders » Orders (Test phase)*. +
. Use the filters to search (material:search[]) for the order type offer for which you want to create the document.
. Open the required offer.
. Open the *Documents* area.
. On the right, click on *Create document* (material:note_add[]).
. Select the option *Offer*.
. Carry out the settings. Pay attention to the explanations given in <<table-generate-offer-document>>.
. Click on *Execute* to create the offer document.

[[table-generate-offer-document]]
.Settings for the offer document
[cols="1,3"]
|===
|Setting |Explanation

| *Date*
|Enter a date to be displayed on the offer document or select a date from the calendar (material:today[]). The present date is set by default.

|*Comment*
|The text entered here is displayed below the order items. Entering a text is optional.

|===

[#automate-shipping-offer-doc]
== Automating sending offer documents

You created individual offers for customers, generated the corresponding documents and want to send them to your customers now? You can automate the process of sending offer documents by setting up the appropriate event procedure. To send the document offer as an email attachment, we recommend the event procedure described in <<table-event-procedure-sending-offer-document>>. Proceed as described in the following to set up the event procedure.

:table-event-procedure: <<table-event-procedure-sending-offer-document>>
include::_includes:partial$event-procedure.adoc[]

[[table-event-procedure-sending-offer-document]]
.Setting up event action “Sending offer as PDF”
[cols="1,3,3"]
|===
|Setting |Option |Selection

| *Event*
| Documents > Offer generated
|

| *Filter*
| *Order > Order type*
| *Offer*

| *Procedure*
| *Customer > Send email*
|Click on Add (icon:plus-square[role="green"]) to add the corresponding email template for sending the offer to the *Customer* (e.g.  “Send offer as PDF”).
|===

[TIP]
.You don’t see the corresponding email template?
======
You don’t see the corresponding email template for the event procedure “Send offer as PDF”? That’s probably because you haven’t created it yet. You can do this in the *Setup » Client* » _Select client_ » Email » Templates menu. Click on *New email template* (icon:plus-square[role="green"]) and create the template according to your requirements. The name you enter here for the email template is then displayed in the event procedures. For further information about setting up email templates, refer to the xref:crm:sending-emails.adoc#1200[Sending emails] page of the manual.
======
