= Pick-up delivery
:page-aliases: generate-pick-up-delivery-document.adoc
:keywords: pick-up delivery, pick-up/delivery note, delivery note, order documents, document template, document type, document
:author: team-docs-automation
:description: Learn how to create a document template for pick-up deliveries in order to generate a document for a pick-up delivery. In plentymarkets, this document is also called pick-up/delivery note.

Goods are picked-up? Use the document pick-up delivery, also called pick-up/delivery note, for this. You can generate this as a PDF file. for example to print it or to send it as an email attachment to your customers.

[#100]
== Setting up a document template for pick-up deliveries

Before generating pick-up deliveries, you have to set up a document template. Go to *Setup » Client » [Select client] » Locations » [Select location] » Documents » Pick-up/Delivery note* to set up the template. +
Further information and instructions on setting up the document template are available on the xref:orders:order-documents-new.adoc#[Order documents] page of the manual.

[#200]
== Generating a single pick-up delivery

You can generate a pick-up delivery document manually for different order types. To do so, proceed as follows.

[.instruction]
Generating a pick-up delivery document manually:

. Go to *Orders » Orders (Test phase)*.
→ The order overview opens.
. Carry out the search (material:search[]) to display orders.
. Open the order for which you want to generate a pick-up delivery.
. Go to the *Documents* area.
. On the right, click on *Create document* (material:add[]).
. Select the *Pick-up delivery* document from the drop-down list. +
→ The window *Create document: Pick-up delivery* opens.
. Enter a date that should be displayed on the pick-up delivery.
. Optionally enter a comment that should be displayed on the pick-up delivery.
. Click on *Create* (material:add[role=green]). +
→ The pick-up delivery is created and added to the *Documents* area.
