= Pro forma invoice
:page-aliases: generate-pro-forma-invoice-document.adoc
:keywords: pro forma invoice, generate pro forma invoice, order documents, document template, document, document type
:author: team-docs-automation
:description: Learn how to create pro forma invoices via a document template and how to generate it as a PDF file in order to use it as a preliminary invoice or as the basis for tax purposes.

In plentymarkets, you can generate pro forma invoices as PDF files, for example if you want to print them or send them to your customers as an email attachment. Pro forma invoices are usually used as a preliminary invoice or as the basis for tax purposes, for example for customs when you import or export goods.

[#100]
== Setting up a document template for pro forma invoices

Before generating pro forma invoices, you have to set up a document template. Go to *Setup » Client » [select client] » Locations » [select location] » Documents » Pro forma invoice* to set up the template. +
Further information and instructions on setting up the document template are available on the xref:orders:order-documents-new.adoc#[Order documents] page of the manual.

[TIP]
.Displaying Payment due and early payment discount on the invoice
====
In order for the payment terms (value date, payment due and early payment discount) to be displayed on pro forma invoices, they have to be activated when setting up the xref:orders:order-documents-new.adoc#intable-payment-terms-documents[document template] for pro forma invoices.
====

[#200]
== Generating a single pro forma invoice

You can create pro forma invoices manually for different order types. The pro forma invoice is available for orders, offers, advance orders, repairs, warranties and for delivery orders. To do so, proceed as follows.

[.instruction]
Creating a pro forma invoices manually:

. Go to *Orders » Orders*. +
→ The order overview opens.
. Carry out the search (material:search[]) to display orders.
. Open the order for which you want to generate a pro forma invoice. Note that orders can only be opened in the list view.
. Go to the *Documents* area.
. At the top left, click on *Create document* (material:add[]).
. Select the *Pro forma invoice* document from the drop-down list. +
→ The window *Create document: Pro forma invoice* opens.
. Enter a date that should be displayed on the pro forma invoice.
. Optionally enter a comment that should be displayed on the pro forma invoice.
. Click on *Create* (material:add[role=”green”]). +
→ The pro forma invoice is created and added to the *Documents* area.
