= Repair slip
:page-aliases: generate-repair-slips.adoc
:keywords: repair slip, generate repair slip, order documents, document template, document type, document, repair document
:author: team-docs-automation
:description: Learn how to create repair slips for returned items or items that need to be repaired.

Repair slips can only be used in connection with the xref:orders:order-type-repair.adoc#[order type repair]. Thus, repairs and repair slips are always linked to returned items which are in need of repair. This is why repair slips can only be created for an repair order.

[#100]
== Setting up a document template for repair slips

Before generating repair slips, you have to set up a document template. Go to *Setup » Client » [select client] » Locations » [select location] » Documents » Repair slip* to set up the template. +
Further information and instructions on setting up the document template are available on the xref:orders:order-documents-new.adoc#[Order documents] page of the manual.

[#200]
== Generating a single repair slip

Repair slips can only be created for orders of the type *repair*. To create a single repair slip in a specific repair order, proceed as follows.

[.instruction]
Generating a single repair slip:

. Go to *Orders » Orders (Test phase)*. +
→ The order overview opens.
. Carry out the search (material:search[]) to display orders.
. Open the order of the type repair for which you want to generate a repair slip.
. Go to the *Documents* area.
. At the top left, click on *Create document* (material:add[]).
. Select the *Repair slip* document from the drop-down list. +
→ The window *Create document: Repair slip* opens.
. Enter a date that should be displayed on the repair slip.
. Optionally enter a comment that should be displayed on the repair slip.
. Click on *Create* (material:add[role=green]). +
→ The repair slip is created and added to the *Documents* area.
