= Return slips
:keywords: return slip, generating return slips, order documents, document, document type, document template, return document
:author: team-docs-automation
:description: Learn how to generate return slips as PDF files and how to send them to your customers so they can enclose it to their shipments when returning or exchanging items.

In plentymarkets, you can generate return slips as PDF files, for example if you want to print them or send them to your customers as an email attachment. This way, customers can enclose the return slips to their shipments when returning or exchanging items.

[#200]
== Setting up a document template for repair slips

Before generating repair slips, you have to set up a document template. Go to *Setup » Client » [select client] » Locations » [select location] » Documents » Return slip* to set up a document template. +
Further information and instructions on setting up the document template are available on the xref:orders:order-documents-new.adoc#[Order documents] page of the manual.

[#300]
== Generating a single return slip

In some cases it makes sense to generate a return slip for a particular order manually. This is done in the order overview for original main orders and return orders alike.

In plentymarkets, you can manually generate a single return slip directly in the order. The generated return slip then lists all items contained in the order. Use this method to add a blank return slip to every order shipped to your customers. Further information can be found in the xref:orders:order-type-return.adoc#create-return-label[create return label] chapter.

[.instruction]
Generating a single return slip:

. Go to *Orders » Orders*. +
→ The order overview opens.
. Carry out the search (material:search[]) to display orders.
. Open the order for which you want to generate a return slip. Note that orders can only be opened in the list view.
. Go to the *Documents* area.
. At the top left, click on *Create document* (material:add[]).
. Select the *Return slip* document from the drop-down list. +
→ The window *Create document: Return slip* opens.
. Enter a date that should be displayed on the return slip.
. Enter an optional comment that will be displayed on the return slip.
. Click on *Create* (material:add[role=green]). +
→ The return slip is created and added to the *Documents* area.

[#600]
== Generating multiple return slips

If you want to generate several return slips at once, use the search filters in the *Orders » Fulfilment* menu to determine the orders for which return slips should be generated. In addition, you can determine whether a status change should take place after the return slips have been generated.

[.instruction]
Generating multiple return slips:

. Go to *Orders » Fulfilment*.
. In the line *Generate return slips* click on the small plus.
. Carry out the settings according to <<table-settings-fulfillment-return-slip>>. +
_Note_ that the settings comprise *Search filters* as well as *Procedures*.
. Click on the gear-wheel (icon:cog[]) to generate the return slips. +
→ A PDF file containing the return slips for the previously selected orders opens.

[[table-settings-fulfillment-return-slip]]
.Options for *Generate return slips*
[cols="1,3"]
|====
|Setting |Explanation

2+^| *Search filter*

| *Order status*
|Select the status of the orders for which return slips should be generated from the drop-down list.

| *Owner*
|Select the owner of the orders from the drop-down list for which the return slips should be generated or select *ALL* if return slips should be generated for all owners.

| *Location*
|Select a location from the drop-down list for which the return slips should be generated.

| *Warehouse*
|Select a warehouse from the drop-down list for which the return slips should be generated or select *ALL* if return slips should be generated for all warehouses.

| *Payment method*
|Select a payment method from the drop-down list for which the return slips should be generated or select *ALL* if return slips should be generated for all payment methods.

| *Sorting*
|Determine how the generated return slips are sorted. The options *Order ID**, *Customer ID* and *Item ID* are available for different sorting methods.

| *Limit*
|Determine the maximum number of return slips that should be generated at once. The maximum is *200*.

2+^| *Procedure*

| *Change order status*
|Choose an order status to which the orders are to be changed after the return slips are created. +
The status change is an important tool to make sure that the process is not carried out twice for orders that have already been processed.

| *Comment*
|Optionally enter a comment that should be displayed on the return slips below the order items.
|====
