= Subscription
:keywords: subscription overview, scheduler, subscription, subscription module, subscription order, run, runs, run preview, subscription run preview, last run, subscription settings, due subscriptions, automatic run, manual run, interval, subscription function, subscription interval, locked subscription
:author: team-order-core
:description: Learn how to create and manage subscriptions. Moreover, find out how to generate a list of all due subscriptions via the subscription run preview and how to lock and unlock subscriptions.

The *Orders » Subscription* menu allows you to generate orders that are automatically sent to your customers at your preferred intervals. By using the subscription, you do not have to create each order separately because the selected items are automatically and regularly sent to your customers. Thus, you can create individual subscriptions for customers and configure the settings as required. +
You can conveniently create and edit subscriptions in an own menu in your plentymarkets system. Subscriptions can also be created from orders of the type *Offer*. Orders generated through subscriptions are editable in the order overview, just like other orders. In the following chapters, we explain how you <<#200, create a subscription>>, how you <<#300, carry out the settings>> and which editing options are available.

[#100]
== Preparatory settings

New settings
You should take note of and decide on some preparatory settings. Having set those, you can work with subscriptions more conveniently. On the one hand, you can select <<#110, default settings>> for subscriptions, so that these settings are preselected when creating a new subscription and do not have to be carried out every time. Deciding on those settings beforehand saves time when you create new subscriptions. On the other hand, you should assign <<#120, user rights>> if users of the type *back end* should also be able to work with subscriptions. The default settings as well as the settings for assigning the required user rights are described in the following two chapters.

Moreover, you can customise the tables according to your needs. This means that you can decide which information is displayed in the table columns. To do so, proceed as follows:

[.instruction]
Customising the table:

. Click on *Configure columns* (material:settings[]). +
→ The window *Configure columns* opens.
. Select which columns you want to be displayed.
. Move (material:drag_indicator[]) the columns so they are displayed in the order you need them in.
. Click on *Confirm* to save your settings.

When you have adapted the table, these settings are saved. You can edit the tables at any time.

[#110]
=== Determining default settings

Go to the *Setup » Orders » Order types » Subscription* menu to decide on default settings for your subscriptions. +
Settings chosen here are preselected for your new subscriptions and can accelerate your workflow if you regularly need the same settings for subscriptions.
It can speed up your work if you regularly choose the same settings when creating subscriptions. However, it is still possible to decide on different settings when creating a new subscription.

[.instruction]
Carrying out default settings:

. Go to *Setup » Orders » Order types » Subscription*.
. Carry out the settings. Pay attention to the information given in <<#table-subscription-default-settings>>.
. *Save* (material:save[]) the settings.

[[table-subscription-default-settings]]
.Subscription default settings
[cols="1,3"]
|===
|Setting |Explanation

|[#intable-subscription-automatic-orders]*Automatically generate orders for any due subscriptions*
|Select whether orders should be automatically generated for subscriptions when they are due. These orders are automatically added to the order overview and can be edited there. +
*_Note:_* The orders are _not_ generated automatically. Thus, they need to be triggered manually when you don’t activate this option.

|[#intable-subscription-default-status]*Default status*
|Select a default status for subscriptions. This status is then preselected for new subscriptions, but can still be adjusted if required. All xref:orders:order-statuses.adoc#[statuses] you have created in your plentymarkets system are available.

|[#intable-subscription-default-owner]*Default owner*
|Select a default owner. Make sure that the assigned owner has the required <<#120, user rights>> for subscriptions.

|[#intable-subscription-default-interval]*Default interval*
|You can optionally set a default time period at which the items of a subscription are shipped regularly. This interval is then preselected for new subscriptions, but can still be adjusted if required.

|[#intable-subscription-default-client]*Default client*
|Select a default client that should be preselected for new subscriptions.

|[#intable-subscription-default-referrer]*Default referrer*
|Select a default referrer that should be preselected for new subscriptions.

|*Display of added items in the shopping cart*
|Select how items are added to the shopping cart. +
*As one order position, quantities of order items are increased* = Identical items are added as one order item, only the quantities are changed accordingly. This is the default setting. +
*As separate order positions* = Identical items are added separately, meaning that each item is displayed in a separate row.

|===

[.discrete]
==== Subscription run preview

The *Subscription run preview* is also available in the *Setup » Orders » Order types » Subscription* menu.
Click on the *Subscription run preview* button to open a list of all *Due subscriptions*. These are sorted in ascending order by order IDs.
Additionally, the duration of the subscriptions as well as the last and the next run are displayed.

The information which subscriptions are due is retrieved _once a day_ by the system. The *Subscription run preview* does not only offer you an overview and the option to review due subscriptions, you can also trigger due subscriptions immediately. Note that _all due subscriptions are triggered at once_. A selection of individual subscriptions is not possible in this view.
How you can trigger manual runs for individual subscriptions in the detail view of each subscription is explained further below in the chapter <<#800, Fulfilled orders: Runs>>.

So when due subscriptions are displayed, click on *Subscription run preview* at the bottom right of the window to trigger an immediate manual run and wait for a moment.
The message *Run executed* is displayed after completion. You can see the generated orders in the *Order overview* as well as in the <<#800, Fulfilled orders>> section of the detail view of the corresponding subscription.

[IMPORTANT]
.Using the Subscription run preview
====
Triggering the due subscriptions cannot be reverted. If required, you can cancel the generated orders in the order overview.
====

[#120]
=== Assigning user rights

:rights-purpose: see and edit subscriptions
:right-one: pass:quotes[*Items > Item > Variation > Read*]
:right-two: pass:quotes[*Items > Item > Variation > Price > Read*]
:right-three: pass:quotes[*Items > Sales price > Read*]
:right-four: pass:quotes[*Orders > Read*]
:right-five: pass:quotes[*CRM > Message > Read*]
:right-six: pass:quotes[*Setup > Tag > Read*]

include::_includes:partial$rights.adoc[]

If employees without admin rights are also to be able to create subscriptions, these employees also need the following rights:

* *CRM > Address > Read*
* *CRM > Contact > Read*
* *Setup > Property > Read*
* *Setup > Tag > Tag relationship > Delete*
* *POS > POS > Read*

[#subscription-myview]
== Using the MyView

The user interface of the detail view of subscriptions is available as MyView. This means that users can create their own views with the available elements. This way, everyone can individually determine which information are needed where. Because of this customisation, working with payments is not only more comfortable but also faster. This chapter explains how to work with the MyView and how to create your own views. The editing of subscriptions, such as <<#400, adding order items>> or <<#600, editing the shipping method and costs>> is explained in the following chapters.

You can access the detail view of a subscription from the overview table in the *Orders » Subscription* menu. Click on the row of the subscription to open the detail view of this subscription. +
If you haven’t created an own view yet, the *Default view* is displayed. You can use this default view when you are working with payments or you can create your own view. The views you create are saved and can then be selected together with the default view from the list of views (icon:caret-down[role="darkGrey"]). Thus, you can switch between different views, if needed. The selected view is always applied when opening a subscription.

[#create-new-view]
=== Creating a new view

. Click on the list of views (icon:caret-down[role="darkGrey"]).
. Click on icon:plus[role="darkGrey"] *Create new preset ...*.
. Enter a name.
. Click on *Create view*. +
→ The new view is created and opens automatically, i.e. it is applied.
It’s now possible to switch between different views.

[#create-grid]
=== Creating a grid

. Click on *Edit view* (terra:design_inline_edit[]).
. Add rows and columns to create a grid.
.. Click on icon:ellipsis-v[role="blue"] and then on icon:plus[role="darkGrey"] *Add row*.
.. Click on *Add column* (icon:plus[role="darkGrey"]).
.. Drag the columns to make them larger or smaller.

[#place-elements]
=== Placing elements

. Add elements via drag & drop.
. Click on icon:pencil[role="blue"] and edit the element’s settings.
.. Change the name.
.. Decide which data fields the element should contain.
.. Use drag & drop to arrange the data fields in a specific order.
. Click on icon:close[role="blue"].

[cols="1,4a"]
|====
|Symbol |Explanation

| icon:pencil[role="blue"]
|Leads down one level.

| icon:trash[role="blue"]
|Deletes the element.

| icon:close[role="blue"]
|Leads up one level.
|====

[TIP]
.Can I add elements multiple times?
======
The number on the element indicates how many times you can use the element. Most elements can only be added once.
======

[#finalise-editing]
=== Finalising your work

. Save the view (terra:save[role="darkGrey"]) and close the editing mode (icon:close[role="darkGrey"]).
. Check the result in the main window.
. If necessary:
.. Click on *Edit view* (terra:design_inline_edit[]) again to further edit the view.
.. Allow other users to see the view.

[#editing-functions]
==== Functions in the editing mode

[cols="1,4"]
|====
|Symbol |Explanation

| icon:reply[role=darkGrey]
|Undoes the last change, unless this change has already been saved.

| icon:share[role=darkGrey]
|Restores the previously undone change.

| icon:caret-down[role="darkGrey"]
|Opens the list of views.
You see the name of whichever view is currently open.
Click on icon:caret-down[role="darkGrey"] to switch to another view or <<#create-new-view, create a new view>>.

| terra:items_incoming_history[]
|Resets the view to the state that was last saved.

| terra:save[role="darkGrey"]
|Saves the changes made to the view.

| terra:close[]
|Closes the editing mode.
In case of unsaved changes, a confirmation message is displayed.
|====


[#200]
== Creating subscriptions

You create a new subscription via the menu *<<#250, CRM " Contacts>>* or from an order of the type *<<#610, Offer>>*.

[#250]
=== Creating subscriptions via contacts

[.instruction]
Creating a new subscription via the contact overview:

. Go to *CRM » Contacts*.
. Search for the contact by means of the filter settings. Note the explanations about the filters on the xref:crm:search-contact.adoc#[Searching for a contact] page. +
→ The contacts that match the search criteria are displayed.
. On the left in the row of the contact, click on material:more_vert[]. +
→ The available options open.
. Navigate to material:shopping_cart[] *Orders* > *New subscription*. +
→ You are automatically redirected to the editing options of the new subscription.

[#300]
==== Carrying out settings

Existing data is already taken over from the contact data record of the selected contact. Among these are for example addresses or the assigned payment method. Basic settings of the subscription are explained in <<#table-basic-settings-subscription>>.

[[table-basic-settings-subscription]]
.Explanations of the subscription settings
[cols="1,3"]
|====
|Setting|Explanation

|[#intable-subscription-status]*Status*
|If you set a <<#intable-subscription-default-status, default status>>, it is preselected here. All xref:orders:order-statuses.adoc#[statuses] you have created in your plentymarkets system are available. Manually select the desired status from the drop-down list.

|[#intable-subscription-tags]*Tags*
|Available are all tags you have created in your plentymarkets system. Select the required tag from the drop-down list.

|[#intable-subscription-invoice-address]*Invoice address*
|Select the invoice address of the selected contact from the drop-down list. Available are the addresses saved in the corresponding contact data record. The address ID is also displayed in order to differentiate between addresses, if more than one is saved for a contact. If an address is selected as the primary invoice address, it is marked by a star. +
_This is a mandatory field._

|[#intable-subscription-delivery-address]*Delivery address*
|Select the delivery address of the selected contact from the drop-down list. Available are the addresses saved in the corresponding contact data record. The address ID is also displayed in order to differentiate between addresses, if more than one is saved for a contact. If an address is selected as the primary delivery address, it is marked by a star. +
_This is a mandatory field._

|[#intable-subscription-interval]*Subscription interval*
|The interval chosen here determines the regularly recurrent times at which the items are sent to the customers. If you set a <<#intable-subscription-default-interval, default interval>>, it is preselected here. The interval can be adapted by selecting a different one from the drop-down list. +
_This is a mandatory field._

|[#intable-subscription-currency]*Currency*
|Select a currency for the subscription. The xref:payment:currencies.adoc#30[system currency] you set in the back end is preselected.

|[#intable-subscription-start]*Start of subscription*
|Select the start date (material:today[]) for the subscription. Note that you have to select a start date that is before the end date. If the start date is in the past, the first automatic run of the subscription will be on the chosen start date _plus_ the selected interval. No automatic run will be executed before this date. However, it is always possible to trigger a <<#800, manual run>>. +
_This is a mandatory field._

|[#intable-subscription-end]*End of subscription*
|Select the end date (material:today[]) for the subscription. Note that the end date of the subscription has to be after the start date. No more runs are executed for the subscription after the end date. +
_This is a mandatory field._

|[#intable-subscription-cancelled]*Subscription cancelled*
|Select a cancellation date (material:today[]) for the subscription, if it was cancelled. The cancellation date can be before the start date of the subscription but not later than the end date. No more runs are executed for the subscription after the cancellation date. No more runs are executed for the subscription after the cancellation date.

|[#intable-subscription-payment-method]*Payment method*
|Select the payment method for the subscription. If a payment method is assigned to the contact in the contact data record, it is preselected here but remains editable. +
_This is a mandatory field._

|[#intable-subscription-shipping-costs]*Shipping costs*
|This field is available once the subscription has been created. +
After creating the subscriptions, you can edit the shipping costs if required. The net and the gross order value will automatically be calculated again and be displayed after the adaption.

|[#intable-subscription-shipping-method]*Shipping method*
|This field is available once the subscription has been created. +
To edit the <<#600, shipping method>>, click on *Recalculate shipping profile combinations* (terra:execute[]) after the subscription has been created and saved. The net and the gross order value will automatically be calculated again and be displayed after the adaption.

|[#intable-subscription-client]*Client*
|Select the client for the subscription. If you set a <<#intable-subscription-default-client, default client>>, it is preselected here. +
_This is a mandatory field._

|[#intable-subscription-owner]*Owner*
|If you set a <<#intable-subscription-default-owner, default owner>>, it is preselected here. The owner can be adapted by selecting a different one from the drop-down list.

|[#intable-subscription-referrer]*Referrer*
|Define the order referrer for subscriptions. The referrer *Manuelle Eingabe* (manual entry) is preselected. Only xref:orders:order-referrer-new.adoc#[referrers] that are set to active in the back end are displayed here. +
_This is a mandatory field._

|====

As soon as all of the mandatory fields in the *Details* area are filled out, items can be added to the subscription.

[#400]
==== Adding order items

To complete the creation of the subscription, items have to be added. Only then will the subscription be saved and created. Carry out a search (material:search[]) to find the required items and add them to the subscription.

[.collapseBox]
.*Search functions*
--
There are several possibilities to search for items. You can enter a value into the search field and select the required filter. Repeat this to combine filters. Click on material:search[] to start the search. +
If you want to select a filter from the available filter list, click on the list and enter a value into the required filter. Once you have set all required filters, click on *Search*. +
Remove the chip if you want to delete a set filter. The available filters are explained in <<#table-filters-item-search-subscription>>.

Additionally, you can save selected filters in the menu by using the *Saved filters* (material:bookmarks[]) component. The saved filters can then be selected from this component every time you open or work with this menu, similar to bookmarks. Every user can save own filter sets.

[.instruction]
Saving filters:

. Set the filters with the required values.
. Carry out the search.
. Click on *Saved filters* (material:bookmarks[]).
. Click on *Save current filter*. +
→ The window *Save filter* opens.
. Enter a *Filter name*.
. Decide if this filter set should be available to all users.
. Click on *Save*.

[[table-filters-item-search-subscription]]
.Available filters in the item search
[cols="1,3"]
|====
|Setting |Explanation

|*Variation number*
|Enter a variation number to search for the variation with this number.

|*Variation ID*
|Enter an ID to search for the variation with this ID.

|*Item name*
|Enter a name to filter for items with this name.

|*Item ID*
|Enter an ID to filter for items with this ID.

|*Barcode*
|Enter a barcode to filter for items with this barcode.

|====

--

[.instruction]
Adding items to the shopping cart:

. In the area *Order items*, click on *Add* (material:add[]). +
→ You are redirected to the *Order items*.
. Search for the required items or variations.
. Select the appropriate sales price from the *Price selection* drop-down list.
. Enter the quantity of the item you want to add to the subscription. +
→ Whenever prices and quantities are changed, the sales price has to be updated by clicking on *Refresh sales price* (material:refresh[]).
. Add the items to the shopping cart (material:add_shopping_cart[]). +
→ The shopping cart table is displayed underneath the item table.
. Carry out further <<#425, changes in the shopping cart table>> if required.
. *Save* (material:save[]) the shopping cart. +
→ The order items are added and you are redirected again to the settings of the subscription.
. *Save* (material:save[]) the subscription. +
→ The subscription is created.

[TIP]
.Price selection
====
All valid sales prices that are determined for this subscription are displayed in a drop-down list. You can select one of the displayed prices, which is then taken as the basis for the order calculation. If the price includes a discount, this is shown behind the price name and amount. The optional columns *Customer class discount* and *Category discount* show the percentage of the applied discount. +
If no valid sales price could be detected, *No valid sales price* is displayed in the drop-down list. You can still add the item to the shopping cart. You can manually adjust the price in the shopping cart. However, it is possible to create a subscription without valid sales prices, if desired.

You can manually adjust the price in the shopping cart. For more information refer to the <<#425, Cart: chapter: Price selection>>.
====

[.collapseBox]
.*Customising the order items table*
--

The table for adding order items is customisable. This means that you can decide which table columns are displayed in which order. When opening the menu, the following table columns are displayed by default:

* Item name
* Variation ID / no.
* Attributes
* Quantity
* Price selection

The following table columns can be added optionally:

* Item ID
* Variation ID
* Variation number
* Variation name
* Barcode
* Customer class discount = the customer class discount in per cent as applied to the selected sales price
* Category discount = the category discount in per cent as applied to the selected sales price

Adapt the table according to your requirements and your workflow. When you have adapted the table, these settings are saved. You can edit the table at any time.

[.instruction]
Customising the table:

. Click on *Configure columns* (material:settings[]). +
→ The window *Configure columns* opens.
. Select which columns you want to be displayed.
. Move (material:drag_indicator[]) the columns so they are displayed in the order you need them in.
. Click on *Confirm* to save your settings.

--

[.collapseBox]
.*Customising the shopping cart table*
--

The shopping cart table is customisable. This means that you can decide which table columns are displayed in which order. The following table columns are selected by default before the table is customised:

* Item name
* Variation ID / no.
* Attributes
* Sales price original
* Quantity
* Surcharge total = the sum of the order item properties’ surcharges
* Total amount = the item price plus the order item properties’ surcharges

The following table columns can be displayed but are not shown by default:

* Item ID
* Variation ID
* Variation number
* Variation name
* Barcode

Adapt the table according to your requirements and your workflow. When you have adapted the table, these settings are saved. You can edit the table at any time.

[.instruction]
Customising the table:

. Click on *Configure columns* (material:settings[]). +
→ The window *Configure columns* opens.
. Select which columns you want to be displayed.
. Move (material:drag_indicator[]) the columns so they are displayed in the order you need them in.
. Click on *Confirm* to save your settings.

--

[#425]
==== Shopping cart: Price selection

While adding items, valid sales prices that were determined for this subscription were displayed in a drop-down list of the *Price selection* column. The price selected there is taken as the basis for further calculations.

You can manually adjust the price in the shopping cart. To do so, select a price from the *Price selection* drop-down list. You can also manually enter another price in the shopping cart. This price is then shown as *Manual price* in the selection. +
If you select a different sales price than the one that was determined first or you change quantities, the sales price needs to be updated. To do so, click on *Refresh sales price* (material:refresh[]). You can update each item individually or use the button above the shopping cart table to update all order items at once. After updating the save button (material:save[]) is available again.

The following applies to the sales prices:

* If you manually enter a price, this price will remain in the drop-down list and can be selected for this order, even if you select a different price in between.
* If no valid sales price could be determined, you can manually enter a price in the shopping cart. Completing the subscription is also possible without a valid sales price, if required.
* It is allowed to enter the price 0.00.

[#450]
==== Shopping cart: Order item properties

You can edit the order item properties of a subscription in the shopping cart. Any changes made here only apply to the subscription in which they are edited. The properties themselves stay as they are configured in the system. Only the properties already created and configured in the system are available in the subscription. +
If you want to create and edit properties or are not yet familiar with the structure of properties, refer to the manual page xref:item:properties.adoc#500,[Properties] first.

In order to link a property with an order item, the property has to be marked as *Order property* in the *Options* area of the property settings. Also set possible surcharges and VAT rates for the property in the xref:item:properties.adoc#property-options[Options] area. The values added here will be included in the calculations.

If a property is already linked with an order item, it will be displayed in a second row of the table underneath the corresponding order item. By clicking on material:expand_more[], the second table row is displayed. There, you can find information about the *Name*, *Value* and *Surcharge* of the property. Moreover, you can *delete* (material:delete[]) order item properties in the table. Deleted properties are not included in this subscription and the calculations. +
To edit the properties or to add more already existing properties, click on *Edit properties* (material:edit[]). The editing window *Edit properties of [selected order item with ID]* opens and you can make further adaptations.
The following information about order item properties can be found in the editing window:

* *Name* = Displays the name of the property. A red asterisk marks the property as a *required* property. Whether a property is *required* is determined in the xref:item:properties.adoc#property-options[Options] area of the property settings. To do this, select the *Mandatory setting* in the *Order Options* drop-down list.
* *Value* = Displays the value of the property. You can edit the value. Depending on the property type, you can either make a selection, edit the value, add a value or upload a file. The changes are only valid for this subscription.
* *Surcharge* = Displays the surcharge of the property, if a surcharge is set for the property. You can edit the surcharge. The changes are only valid for this subscription.

Moreover, further editing options are available here. By clicking on *Delete* (material:delete[]), you remove the property from this order item. In this case, the property will not be included in the subscription and the order calculations. +
You can also add more already existing properties. Select a property from the *Select property* drop-down list and add it to the order item by clicking on *Add property* (material:add[]). +
Once you are done with all adaptations, click on *Save properties*. The editing window is closed and you can edit the properties of other order items in the same way.

If you want to have the properties displayed on documents, you have to set this in the configurations of the property itself. Make sure that the following options are selected in the xref:item:properties.adoc#property-visibilities[Visibilities] area of each property:

* *Display on documents* from the *Display everywhere* drop-down list as well as
* the correct client from the *Client* drop-down list.

Where on the document the properties are displayed depends on each property and its configurations. Properties for which no VAT rate was set in the *Options* area of the configuration or for which the option *Display as additional costs* was selected in the *Order property* drop-down list are displayed underneath the totals. Other properties are displayed in the order item table.

Save (material:save[]) the shopping cart when you are done with editing the order item properties and the shopping cart. After saving, you are redirected to the detail view of the subscription.

[#500]
==== Editing the item list

You can still edit the item list after the creation of the subscription. This is possible until the first order is generated by a run. Afterwards, the editing options of the subscription are restricted. It is possible to <<#850, unlock>> the subscription. The item list can be edited after unlocking.

[.collapseBox]
.*Customising the order items table*
--

The items table is customisable. This means that you can decide which table columns are displayed in which order. When opening the menu, the following table columns are displayed by default:

* Item name
* Variation ID / no.
* Attributes
* Price
* Quantity

The following table columns can be added optionally:

* Item ID
* Variation ID
* Variation number
* Variation name

Adapt the table according to your requirements and your workflow. When you have adapted the table, these settings are saved. You can edit the table at any time.

[.instruction]
Customising the table:

. Click on *Configure columns* (material:settings[]). +
→ The window *Configure columns* opens.
. Select which columns you want to be displayed.
. Move (material:drag_indicator[]) the columns so they are displayed in the order you need them in.
. Click on *Confirm* to save your settings.

--

By clicking on *Add* (material:add[]), you are redirected directly to the item search and can add items as described in <<#400, Creating order items>>. The editing options explained below are available to you as well.

Or you can click on *Edit* (material:edit[]) in the *item list* of a subscription to be redirected directly to the existing *shopping cart* of the selected subscription. The following editing options are available to you there:

[[table-editing-order-items-subscription]]
.Editing options of the order items
[cols="1,3"]
|====
|Setting|Explanation

|[#intable-subscription-adding-items]*Adding items*
|Add more items to the shopping cart of the subscription (material:add_shopping_cart[]). Proceed as described in <<#400, Creating order items>>.

|[#intable-subscription-delete-items]*Delete items*
|Delete items from the shopping cart of the subscription by clicking on *Delete item* (material:delete[]).

|[#intable-subscription-change-items]*Change quantity*
|Change the quantity of an item in the shopping cart of the subscription by directly clicking on the line of the item in the shopping cart. +
*_Note:_* Note that changing quantities requires a price update before the shopping cart can be saved. To do so, click on *Refresh sales price* (material:refresh[]).

|[#intable-subscription-change-prices]*Change price*
|Change the price of an item in the shopping cart of the subscription. Note that the change of the price only applies to the price in the subscription. +
*_Note:_* Changing prices requires an update before the shopping cart can be saved. To do so, click on *Refresh sales price* (material:refresh[]).

|====

*Save* (material:save[]) the shopping cart after you carried out the desired changes. Afterwards, you are redirected back to the settings of the subscription.
The *Net order value* as well as the *Gross order value* are automatically recalculated and displayed. +

Additionally, you can edit the *item name* in the detail view of the subscription. This change also only applies to the subscription.

[TIP]
.Changes on items only for selected subscription
====
The item changes only apply to the subscriptions they were made in. For permanent changes to items, the adaptations need to be carried out either in the *Item » Item UI (Test phase)* or the *Setup » Item* menu.
//ToDo - as soon as the new article UI is standard, then show this sentence and delete the old path for it
//For permanent changes to items, the adaptions have to be made either in the menu *Items » Edit item* or the menu *Setup » Item*.
How to edit items is described on the xref:item:item.adoc#[Item] page of the manual.
====

[#600]
==== Editing the shipping method and the shipping costs

The *Net order value* as well as the *Gross order value* were automatically calculated after adding the order items and saving the subscription. After saving, you can edit the shipping method and the shipping costs.

[.instruction]
Recalculating shipping profile combinations:

. Click on *Recalculate shipping profile combinations* (terra:execute[]). +
→ During the recalculation, the editing options are briefly locked.
. Select the desired *Shipping method*. All xref:fulfilment:preparing-the-shipment.adoc#[shipping methods] already integrated in your plentymarkets system are available in the drop-down list. +
→ The *shipping costs* are added automatically.
. Edit the *shipping costs* if required. +
. *Save* (material:save[]) the subscription. +
→ The Net order value as well as the Gross order value are automatically recalculated.

[#610]
=== Creating subscriptions via offer orders

First, make sure that you have made your desired basic settings for subscriptions in the menu *Setup » Order » Order types » Subscription*.
Then, to create a subscription from an offer order, the offer order must already exist in the system.

[.instruction]
Creating a subscription:

. Go to *Orders » Orders*.
. Carry out the search to display orders.
. Open the offer order for which you want to create a subscription.
. At the top, click on *Create orders (material:shopping_cart[]) > Subscription*.
. Select one of the options *For all order items* or *For specific order items*.
. If you select the option *For all order items*, see the explanations in <<#table-all-order-items>>.
. If you select the option *For specific order items*, see the explanations in <<#table-specific-order-items>>.
. *Save* (icon:save[role="green"]) the settings. +
→ The subscription is created.


[[table-all-order-items]]
.All order items
[cols="1,3"]
|====
|Setting|Explanation

|[#intable-subscription-status]*Status*
|Status of the subscription

| *Owner*
|The owner of the subscription.

| *Start of subscription*
|The subscription’s start date.

| *Subscription interval*
|The interval of the subscription.

|==== 


[[table-specific-order-items]]
.Specific order items
[cols="1,3"]
|====
|Setting|Explanation

|[#intable-subscription-status]*Status*
|The status of the subscription

| *Owner*
|The owner of the subscription.

| *Start of subscription*
|The subscription’s start date.

| *Subscription interval*
|The interval of the subscription.

| *Shopping cart*
|The items you can select from the shopping cart.

|==== 

[#700]
== Further areas in the detail view

In the detail view of a subscription, the functions <<#800, Fulfilled orders>>, <<#900, Messenger>> as well as the <<#1000, History>> are also available. Access these areas either via the menu on the left or by scrolling down in the detail view. You can decide how the elements are structured in the detail view by using the <<#subscription-myview, MyView>>.

Moreover, the detail view of a subscription provides info boxes with basic information about the subscription:

* Net order value: The net order value of the ordered items is displayed. Grey means that the value is zero. Green means that the value is above zero.
* Gross order value: The gross order value of the ordered items is displayed. Grey means that the value is zero. Green means that the value is above zero.
* Last run: The date of the last executed run is displayed. If no date is displayed, no run has been executed yet.

[#800]
=== Fulfilled orders: Runs

In this area, already fulfilled orders belonging to a subscription are displayed. These orders can be generated by either manual or automatic runs. +
*Automatic runs* are regularly carried out at the intervals you selected for the subscription. When the subscription has reached the end date or when it is cancelled, no automatic runs are carried out any more.

Additionally to the automatic runs, you can trigger a *manual run* (material:subscriptions[]). Note that a manual run is always carried out _immediately_. To trigger a manual run, proceed as follows.

[.instruction]
Triggering a manual run:

. Go to the *Orders » Subscription* menu.
. Click in the line of a subscription. +
→ The detail view of the subscription opens.
. Go to the *Fulfilled orders* area.
. Click on *Start manual run* (material:subscriptions[]).
. You are asked whether you want to skip the next automatic run. +
→ When the next automatic run is executed depends on the selected interval. +
→ The manual run is executed. +
→ The order generated by this is assigned an *order ID* and is displayed in the section *Fulfilled orders* as well as in the *order overview*.

Other information displayed in the section *Fulfilled orders* are for example the date of the order generation or the selected payment method.
Moreover, you can also delete (material:remove_circle[]) individual orders of a subscription. When deleting an order, it will also be deleted from the order overview in the *Orders » Orders (Test phase)* menu. Note that orders _cannot_ be deleted when tax-relevant documents, e.g. invoices, have already been generated.

[WARNING]
.Skipping an automatic run
====
When you chose *Skip the next automatic run* while triggering a manual run, the next automatic run is also skipped when the order generated by the manual run is deleted.
====

[.collapseBox]
.*Customising the fulfilled orders table*
--

You can customise the *Fulfilled orders* table and select which columns should be displayed in which order. Adapt the table according to your requirements and your workflow. When you have adapted the table, these settings are saved. You can edit the table at any time.

[.instruction]
Customising the table:

. Click on *Configure columns* (material:settings[]). +
→ The window *Configure columns* opens.
. Select which columns you want to be displayed.
. Move (material:drag_indicator[]) the columns so they are displayed in the order you need them in.
. Click on *Confirm* to save your settings.

--

[#850]
[.discrete]
==== Locking and unlocking subscriptions

Once the first order is generated, the subscription is locked and the editing options in the detail view are restricted. The end date as well as the date of the subscription’s cancellation are still editable. If the order is deleted, the subscription is unlocked. However, note that as soon as tax-relevant documents exit, orders _cannot_ be deleted any more.

Moreover, you can unlock the subscription by clicking on *Unlock subscription* (material:lock[]). All editing options are available again. Which user executed this step at which time can be seen in the <<#1000, history>>. Click on *Lock subscription* (material:lock_open[]) to lock the subscription again. If this is not done the subscription will automatically be locked again after the next run is executed. However, it is recommended to lock the subscription again after editing, as this action is also added to the history.  This way, transparency and traceability are ensured.

[#900]
=== Using the messenger

Use the messenger to create notes about your contacts in the back end. These notes are only visible in your plentymarkets back end and cannot be accessed by your contacts.

[.instruction]
Proceed as follows to create a new note:

. Go to the *Orders » Subscription* menu.
. Open the subscription.
. On the left side, click on *Messenger*.
. Click on *New message* (material:add[]). +
→ An input field opens.
. Select one ore multiple recipients. +
*_Note:_* The ID of the subscription is already prefilled.
. Enter a subject.
. Enter the text. +
→ Double-click on the word to use formatting options for your message.
. Click on material:attach_file[] *Add attachments* to add a file, if needed.
. Click on material:visibility_off[] *WHISPER* to whisper the message.

You can open the note either in the *Messenger* section of the subscription detail view or you can view the note in the Messenger section of the contact. To see it there, go to the selected contact in the contact overview. For further information, refer to the xref:crm:messenger-testphase.adoc#[Messenger] page.

[#1000]
=== History

The history offers you an overview over the executed steps and functions of a subscription. Included are for example updates of orders or the creation of new orders. These changes are sorted by date in this overview. The table shows when the step was executed, by which owner, what the step was and the status of the subscription at that time.

[#1100]
== Subscription overview

Go to *Orders » Subscription* to access the subscription overview. Here, are all created subscriptions are displayed sorted in ascending order by the order ID. Additionally, you can see the following information for each subscription:

* Order ID
* Contact
* Interval
* Payment
* Status
* Start
* End
* Cancelled
* Last run

If you want to change the status of a subscription, you can do so directly in the overview. Click on the *status* and select the required status from the drop-down list. +
For any other changes to the subscription, click on the row of the subscription you want to edit. The detail view opens and you can edit the subscription. +
As long as there is no generated order, all editing options are still available. if an order has already been generated, the editing options are restricted. However, you can still edit the end date and the cancellation of the subscription. You can also trigger a manual run.

[.collapseBox]
.*Customising the overview table*
--

The overview table is customisable. This means that you can decide which table columns are displayed in which order. Adapt the table according to your requirements and your workflow. When you have adapted the table, these settings are saved. You can edit the table at any time.

[.instruction]
Customising the table:

. Click on *Configure columns* (material:settings[]). +
→ The window *Configure columns* opens.
. Select which columns you want to be displayed.
. Move (material:drag_indicator[]) the columns so they are displayed in the order you need them in.
. Click on *Confirm* to save your settings.

--

[#1200]
=== Searching for subscriptions

You want to change the subscription of a specific customer or want to check all subscriptions without an initial run? Then execute a search in the subscriptions overview in the *Orders » Subscription* menu.

There are several ways of using the search. You can enter a value into the search field and select the required filter. When you enter a number or a letter, available filters are suggested, such as the order ID or the variation number. Repeat this to combine filters. Click on *Search* (material:search[]) to carry out the search. +
If you first want to select a filter from the filter list, click on *Filter* (material:tune[]). → The available filters are shown. Enter a value in the desired filter. Once you have set all required filters, click on *Search*. +
Remove the chip if you want to delete a set filter. The available filters are explained in <<#table-search-subscriptions>>.

Additionally, you can save selected filters in the UI by using the *Saved filters* (material:bookmarks[]) component. The saved filters can then be selected from this component every time you open or work with this menu, similar to bookmarks. Every user can save own filter sets.

[.instruction]
Saving filters:

. Set the filters with the required values.
. Carry out the search.
. Click on *Saved filters* (material:bookmarks[]).
. Click on *Save current filter* (material:bookmark_border[]). +
→ The window *Save filter* opens.
. Enter a *Filter name*.
. Decide if this filter set should be used as default.
. Decide if this filter set should be available to all users.
. Click on *Save*.

[[table-search-subscriptions]]
.Searching for subscriptions
[cols="1,3"]
|====
|Setting|Explanation

|[#intable-subscription-search-order-id]*Order ID*
|Enter an ID to search for the subscription with this ID.  You can enter several IDs, separated by comma.

|[#intable-subscription-search-interval]*Interval*
|Select an interval to display all orders for which this interval was chosen.

|[#intable-subscription-search-no-initial-run]*No initial run yet*
|Activate this option if you are searching for subscriptions for which no run, neither manual or automatic, has been executed yet. When you select this option, the date picker is disabled because a date limitation is not needed for this search filter and there is no possibility to combine these search filters.

|[#intable-subscription-search-date]*Date type*
|Select either start date, end date, cancellation date or date of last. In combination with *from* and *to*, all subscriptions are displayed for which the start date, end date or cancellation falls within the chosen period of time (material:calendar[]).

|[#intable-subscription-search-date-from]*Date from*
|In combination with *to*, define a time period and select the type of date you want to use for the search. Those subscriptions are displayed for which the start date, end date or cancellation falls within this period of time (material:calendar[]).

|[#intable-subscription-search-date-to]*Date to*
|In combination with *from*, define a time period and select the type of date you want to use for the search. All subscriptions whose start date, end date or cancellation falls within this time period (material:calendar[]) are displayed.

|[#intable-subscription-search-client]*Client*
|Select a client to show only subscriptions of this client.

|[#intable-subscription-search-contact]*Contact ID*
|Search for subscriptions of a specific customer via the contact ID. You can enter several IDs, separated by comma.

|[#intable-subscription-search-owner]*Owner*
|Select an owner to search for the subscriptions of this owner.

|[#intable-subscription-search-status-from]*Status from*
|In combination with *Status to*, define a status range. The subscriptions with a status in this range are shown.

|[#intable-subscription-search-status-to]*Status to*
|In combination with *Status from*, define a status range. The subscriptions with a status in this range are shown.

|[#intable-subscription-search-payment-method]*Payment method*
|Select a payment method. All subscriptions for which this payment method was selected are shown.

|[#intable-subscription-search-reset]*Reset*
|Resets all selected filters.

|[#intable-subscription-search]*Search*
|Starts the search.

|====

[#1300]
=== Group function: Manual run

The group function *Start manual run* (material:subscriptions[]) is available in the subscription overview. Once you have selected at least one subscription, the group function is shown above the table. With this function, you can trigger a manual run for up to 20 subscriptions at the same time. Same as with triggering a manual run in the detail view of a subscription, the group function manual run is carried out _immediately_. To use the group function, proceed as follows.

[.instruction]
Carrying out the group function:

. Go to the *Orders » Subscription* menu.
. Search for those subscriptions for which you want to trigger a manual run.
. Select (material:check_box[role=skyBlue]) the respective subscriptions.
. Click on *Start manual run* (material:subscriptions[]). +
→ A manual run is carried out for the selected subscriptions. If a manual run could not be carried out for one or several subscriptions, e.g. because a subscription has already ended, an error message is displayed.

[#1400]
=== Subscriptions in the order overview

Orders that were generated from subscriptions are displayed in the order overview of the *Orders » Orders (Test phase)* menu. +
The information to which subscription an order belongs can be found in the row of the order. You are redirected to the detail view of a subscription when you click on the ID of the subscription. You can edit the selected subscription in the detail view.

Orders that were generated by a subscription can be edited in the order overview.
