= Working with orders

:keywords: order creation, creating orders, create orders, group function for orders, dividing orders, redeeming coupons, redeeming vouchers, sales prices, order areas
:author: team-order-core
:description: Learn how to work with orders, use group functions and carry out the settings in the different areas of an order. Moreover, find out how to redeem coupons.

//menü artikel bearbeiten (im bereich auftragspositionen) hinzufügen

Orders depict your sales and the business transactions connected to them. Those different business transactions are represented by xref:orders:order-types.adoc#[order types]. Progress during order processing is made visible by xref:orders:order-statuses.adoc#[order statuses]. All orders are registered in one central menu and in the same format. The order overview provides you with access to all important information and enables you to edit orders.

[#basic-info-create-orders]
== General information on creating orders in plentymarkets

In plentymarkets, an order is automatically created when customers place orders in your online store or on one of your implemented markets. Separate orders with different order types are created for business transactions such as xref:orders:order-type-delivery-order.adoc#[delivery orders], xref:orders:order-type-return.adoc#[returns], xref:orders:order-type-credit-note.adoc#[credit notes], xref:orders:order-type-warranty.adoc#[warranties], and xref:orders:order-type-repair.adoc#[repairs]. These orders are always linked to the main orders. The order overview allows you to open and edit orders regardless of the xref:orders:order-referrer.adoc#[order referrer]. For many order types, such as xref:orders:order-type-delivery-order.adoc#[delivery orders], it makes sense to set up xref:automation:event-procedures.adoc#[event procedures] that allow you to automate part of your order processing. You will find some examples for using event procedures during order processing in the following chapters. +
Orders that were not generated in the online shop or on a market can be created xref:orders:manually-create-orders.adoc#[manually] in your system. This can be the required for orders via telephone, email or cash sales.

Before processing the first orders in your plentymarkets system, adjust the xref:orders:preparatory-settings.adoc#[preparatory settings] in the *Setup » Orders » Settings* menu. Save those settings once even if you have not changed the default values.

[#order-group-functions]
== Using group functions

Use the group function to edit multiple orders at once. The group functions in the table below are available for orders. +
In the list view as well as in the compact view you can select all orders of the current page at once by clicking on the checkbox *Select all* (material:check_box[role=skyBlue]) on the top left.

[.instruction]
Using group functions:

. Go to *Orders » Orders (Test phase)*.
. Carry out the search (material:search[]) to display orders.
. Select (material:check_box[role=skyBlue]) all orders for which you want to carry out a certain action at once.
. Select one of the available group functions. Pay attention to the explanations given in <<table-order-group-functions>>.

[TIP]
.Select default group functions
======
In the editing mode (terra:design_inline_edit[role="darkGrey"]) of the order overview, you can determine *default group functions* that become directly visible when selecting orders. All remaining group functions will automatically be added to the context menu (material:more_vert[]).
======

[[table-order-group-functions]]
.Group functions for orders
[cols="2,1,6a"]
|===
|Setting |Symbol |Explanation

| *Group orders*
|material:library_add_check[]
|Groups the selected orders.

| *Change status*
|material:repeat_one[]
|Changes the status of the selected orders. Select another status from the drop-down list.

| *Change tag*
|material:label[]
|Changes the tag of the selected orders. It is possible to add or remove tags. Select the desired tags from the drop-down list.

| *Book outgoing items*
|material:book[]
|Books the outgoing items for all selected orders. Select a date for the outgoing items.

| *Delete orders*
|material:delete[]
|Deletes all selected orders.

3+^| *Context menu* (material:more_vert[])
| *Reverse outgoing items*
|material:book[]
|Reverses the outgoing items of all selected orders.

| *Change owner*
|material:people_alt[]
|Changes the owner of all selected orders. Select the owner from the drop-down list.

| *Change shipping profile*
|material:local_shipping[]
|Changes the shipping profile of all selected orders. Select a shipping profile from the drop-down list.

| *Set order delivery date*
|material:schedule_send[]
|Sets a delivery date for all selected orders. Enter a delivery date or selected a date via the calendar (material:today[]).

| *Set order item shipping date*
|material:pending_actions[]
|Sets a shipping date for the order item of all selected orders. Enter a shipping date or selected a date via the calendar (material:today[]).

| *Create document*
|material:note_add[]
|Creates a document for all selected orders. Select a document type from the drop-down list. Enter a creation date for the document or select a date from the calendar (material:today[]).

| *Send email*
|material:mail[]
|Sends an email for all selected orders. First, select the *Receiver* and a *Template* for the email. As soon as the email has been sent, a success message will be displayed. Afterwards, you can see the sent emails in the email service (material:mail[]) at the top of the detail view and in the *Messenger* area. *_Note:_* In order to see the email in the *Messenger* area, you first need to have it activated in the *Messenger configuration* assistant.

|===

== Using further functions in the order overview

On the right-hand side of the order overview, further functions are available. Those functions can be accessed via the context menu (material:more_vert[]). Which functions are available here depends on the order type. For example, you can create documents or book payments.

[[table-context-menu-functions]]
.Further functions for orders
[cols="2,1,6a"]
|===

|Setting |Symbol |Explanation

| *Create document*
|material:add[]
|Creates documents for the order. Depending on the order type, different documents can be created.

| *Change status*
|material:repeat_one[]
|Changes the status of an order. The current status is preselected. Select another status from the drop-down list.

| *Book outgoing items*
|material:output[]
|Books outgoing items. The current date and time of the booking is shown. If needed, select another date or time for the booking via the calendar (material:today[]).

| *Show referenced orders*
|material:account_tree[]
|Shows the order references. Configure (material:settings[]) the table columns if needed.

| *Book payment*
|material:payment[]
|Books a payment for the order. Enter the data for the payment that you want to book.

| *Show stock*
|material:warehouse[]
|Shows the stock and possible reorders for the order item's warehouse. Expand (material:chevron_right[]) the columns to see further information on the stock. +
*_Tip:_* By clicking on the number in the *Reordered* column, the *Stock » Purchase order* menu opens. Here, all open reorders containing the order item are displayed. +
By clicking on the number in the *Reserved stock* column, all orders that have reserved this order item will be displayed.

| *Open tracking link*
|terra:shipment_tracking[]
|Opens the tracking link of the package numbers.

| *Open order in shipping centre*
|terra:outgoing_items[]
|Opens the order in the shipping centre 2.0.

| *Delete order*
|material:delete[]
|Deletes the order. Note that some orders cannot be deleted.

|===

[TIP]
In the side navigation on the bottom left of an order, you can click on the order ID (material:content_copy[]) to copy the ID of the order to the clipboard.

[#order-areas]
== Details about the individual areas

All areas and their functions that are available for an order are described in the following sub-chapters. Use the xref:design-order-view.adoc#editing-mode[editing mode] and decide which fields are displayed in a respective area. You can also define in which order the fields should be arranged. This way, you can individually design your order view and adapt it to suit your needs. Note that different fields are available, depending on the order type. As soon as you open an order, all areas will be shown in the navigation on the left-hand side. *_Note:_* Orders can only be opened in the list view. +
By clicking on an entry in the following list, you will be directly forwarded to the corresponding sub-chapter where you find further details.

* <<#area-overview, Overview>>
* <<#area-status-tags, Status and tags>>
* <<#area-general, General>>
* <<#area-addresses, Addresses>>
* <<#area-order-items, Order items>>
* <<#area-payment-terms, Payment terms>>
* <<#area-bank-data, Bank details>>
* <<#area-assigned-payments, Assigned payments>>
* <<#area-order-references, Order references>>
* <<#area-properties, Properties>>
* <<#area-documents, Documents>>
* <<#area-history, History>>
* <<#area-notes, Notes>>
* <<#area-messenger, Messenger>>
* <<#area-tickets, Tickets>>

[TIP]
.How is data being loaded in the individual areas?
======
If you click on the area that you want to edit on the left-hand side of the navigation, this area will shortly be highlighted in blue, the available data for this area will be loaded and you can directly start editing it. +
*_Note:_* The following areas will be loaded and opened when you first open the order: *Overview*, *Status and tags*, *Addresses*, *General*, *Order items*, *Payment terms*, *Assigned payments*, *Documents*, *History*, *Notes*, *Messenger*, *Tickets*. +
The following areas will only be loaded and opened after you click on them in the left-hand side of the navigation: *Bank details*, *Order references*, *Properties*.
======

[IMPORTANT]
.Missing rights for certain areas, buttons and functions in the order?
====
If a person without admin rights is not able to see certain areas and/or buttons and functions contained in the order, a person with *Admin* access rights needs to activate further rights in the *Setup » Account management » Roles* menu. +
All rights that are necessary for each area, button and function in an order are described on the page xref:orders:preparatory-settings.adoc#[Carrying out the preparatory settings] in the chapter xref:orders:preparatory-settings.adoc#grant-user-rights[Assigning rights].
====

[#area-overview]
=== Area: Overview

The *Overview* area provides all basic information about an order. <<#table-tab-overview>> lists all fields that are available in the *Overview* area of an order.

[[table-tab-overview]]
.Settings in the *Overview* area
[cols="1,3"]
|===

| *Gross value of items*
|Shows the gross value of items.

| *Net value of items*
|Shows the net value of items.

| *VAT*
|Shows the VAT.

| *Invoice amount*
|Shows the invoice amount.

| *Amount paid*
|Shows the amount that was paid for the order. +
For this field, you can use the *Amount display format* setting in the editing mode to decide whether the amount should be displayed in *percentage* or *absolute*.

| *Gross shipping costs*
|Shows the gross shipping costs.

| *Net shipping costs*
|Shows the net shipping costs.

| *Item quantity*
|Shows the amount of items.

| *Item weight*
|Shows the item weight.

| *Net profit margin*
|Shows the net profit margin.

| *Coupon payment*
|Shows the coupon payment.

| *Taxless amount*
|Shows the taxless amount.

| *Gross coupon discount*
|Shows the gross coupon discount.

| *Net coupon discount*
|Shows the net coupon discount.

| *Dunning level*
|Shows the dunning level.

| *VAT rates*
|Shows the VAT rates that have been used for this order.

|===

[#area-status-tags]
=== Area: Status and tags

The *Status and tags* area provides information about the order status and the selected tags.

[[table-area-status-tags]]
.Settings in the *Status and tags* area
[cols="1,3"]
|===
|Setting |Explanation

| *Status*
|Shows the status the order is in. +
If needed, select another order status from the drop-down list. +
*_Note:_* The order status *[7] Outgoing items booked* cannot be changed to a lower status because the items have already been shipped. However, if you still want to change the status, then you first need to reset the outgoing items that were booked.

| *Tags*
a|Shows the selected tags. +
The drop-down list contains all tags that you have created.

|===

[#area-general]
=== Area: General

The *General* area provides basic information about your order. Use the editing mode to decide which settings should be displayed in this area.

[[table-area-general]]
.Settings in the *General* area
[cols="1,3"]
|===
|Setting |Explanation

| *Order type*
|Shows the order type. The standard setting for the order type is *Order*. +
*_Tip:_* You can change an order to an advance order with only a few clicks, and vice versa. To do so, click on material:change_circle[] on the right-hand side and confirm the pop-up.

| *Language*
|Shows the language of the order. The default setting is *German*. +
Order documents as well as emails are generated in the language of the order. You can adjust the language via the drop-down list. +
Note that you need to have created templates in order to generate documents and emails in different languages.

| *Owner*
|Select an owner from the drop-down list.

| *Custom date*
|Select a customized date. +
*_Note:_* You can add a maximum of 5 dates.

| *Client*
|The client that was saved is displayed here.

| *Location*
|Shows the location saved for the order. +
The default setting is *Germany*.

| *Warehouse*
|Shows the warehouse, or the main warehouse, of the order items. +
*_Note:_* The option *Stock correction* synchronises the data in the settings of the order with the warehouse saved in the *Order items* area. The option is only available when you selected *b) a warehouse can be assigned for each stock unit* as a basic order setting for the *Assignment of warehouses* in the *Setup » Orders » Settings* menu. If you manually change the warehouse assigned to an order item and the changed warehouse is not automatically visible in the Settings tab of the order, click on *Stock correction* to update the display of the warehouse.

| *Shipping profile and costs*
|Shows the shipping profile and shipping costs for the order.

| *Custom property*
|Select a custom property. +
*_Note:_* You can add a maximum of 3 properties.

| *Referrer*
|Shows the order referrer. You can change the referrer in the drop-down list. +
The default setting for the referrer is *0.00 Manual entry*.

| *Payment method*
|Shows the payment method. Select the desired payment method from the drop-down list. The option *Cash in advance* is selected by default.

| *External order ID*
|Shows the external ID of the order.

| *Currency*
|Shows the currency. +
The default setting for the currency is *Euro (EUR)*.

| *Entry date*
|Enter an entry date or select a date via the calendar (material:today[]).

| *Customer reference*
|Shows the customer reference.

| *Shipped on*
|Enter a shipping date or selected a date via the calendar (material:today[]).

| *Return date*
|Enter a return date or select a date via the calendar (material:today[]).

| *Package numbers*
|Shows the package numbers separated by comma.
By clicking on *Open tracking link* (terra:shipment_tracking[]), the tracking link of the package numbers opens. +
By clicking on *Open shipping centre* (terra:outgoing_items[]), the order is opened in the xref:fulfilment:shipping-centre-2-0.adoc#[shipping centre 2.0].

| *Flag (not changeable)*
|Shows the flag of the order. +
Note that the flag cannot be changed.

| *Dunning level*
|Shows the dunning level. +
You can select from *None* and *Level 1* to *Level 4* from the drop-down list.

| *Main document*
|Shows the main document of the order.

| *Exchange rate*
|Shows the exchange rate of the selected currency.

| *Outgoing items date*
|Shows the date and the time of the outgoing items.

| *Currency*
|Shows the currency.

| *Return package numbers*
|Shows the package numbers of a return separated by comma. This field is only available for the order type *Return*. By clicking on terra:order_return[] you are redirected to the Shipping Centre 2.0.

| *Sales representative*
|Enter the name of the sales representative that you want to select for the order. Alternatively, you can also enter the ID or the email address of the sales representative.

| *Status*
|Select a status from the drop-down list.

| *Loyalty program*
|Shows the respective loyalty programme of Amazon Prime or eBay Plus.

|===

==== Tracking packages via tracking link

Via the tracking link on the package number, you can track the packages of your orders and thus see where your items are at the moment. To track packages, proceed as follows.

[.instruction]
Tracking packages via tracking link:

. Go to *Orders » Orders (Test phase)*.
. Carry out the search (material:search[]) to display orders.
. At the top right, click on *Configure columns* (material:settings[]).
. Select the option *Order overview table*.
. Select (icon:check[]) the *Package numbers* column.
. Click on *Confirm*. +
→ The *Package numbers* column is shown in the order overview and displays the package numbers separated by comma.
. In the line of the order, click on a package number. +
icon:map-signs[] *_Or:_* In the line of the order, click on the context menu (material:more_vert[]) and select the option *Open tracking link* (terra:shipment_tracking[]).
→ The tracking link opens.

[TIP]
.Split tracking link for several package numbers
======
Open the *Shipping service provider* tab in the *Setup » Orders » Shipping » Settings* menu and activate the option *Split URLs* to split a tracking link for several package numbers. In this case, a separate link is used for each package number. If the option is not activated, there is only one tracking link for all package numbers.
======

[#area-addresses]
=== Area: Addresses

The *Addresses* area provides information about the invoice address and delivery address.
You can adjust the settings in the context menu (material:more_vert[]).

[[table-area-addresses]]
.Settings in the *Addresses* area
[cols="1,3"]
|===
|Setting |Explanation

| *Invoice*
a|Shows the invoice address and the ID of the address. The default setting contains this information: name, street, postcode and town, country, email address, and ID. +
*_Tip:_* Click on *Show more* in order to see further address details. +
The following fields are available: +

* Address details +
** Form of address +
** Company (Name 1) +
** First name (Name 2) +
** Last name (Name 3) +
** Additional information (Name 4) +
** Address 1 (Street) +
** Address 2 (House number) +
** Address 3 (Additional address information) +
** Address 4 (Free) +
** Postcode +
** Town +
** Country +
** Region/County +
* Address options: +
** Email +
** Telephone +
** Type +
** Value

| *Delivery*
a|Shows the delivery address and the ID of the address. The default setting contains this information: name, street, postcode and town, country, email address, and ID. +
*_Tip:_* Click on *Show more* in order to see further address details. +
*_Note:_* If you selected the option _DHL Packstation_ or _DHL post office_ at the top in the address details, the field *DHL Packstation* or *DHL post office* will be visible. In this case, enter the address of the Packstation or the post office and pay attention to the information given in this xref:crm:create-contact.adoc#dhl-packstation-dhl-post-office[chapter]. +
The following fields are available: +

* Address details +
** Form of address +
** Company (Name 1) +
** First name (Name 2) +
** Last name (Name 3) +
** Additional information (Name 4) +
** Address 1 (Street) +
** Address 2 (House number); (for *DHL Packstation* or *DHL post office*, this field is available for the address of the Packstation/post office) +
** Address 3 (Additional address information) +
** Address 4 (Free) +
** Postcode +
** Town +
** Country +
** Region/County +
* Address options: +
** Email +
** Telephone +
** Type +
** Value

|===

==== Changing an address

In addresses, you can either change single fields of the current address or you can assign an already existing address that replaces the current address. Proceed as described below to change an address.

[.instruction]
Changing single fields of an address:

. Go to *Orders » Orders (Test phase)*.
. Carry out the search (material:search[]) to display orders.
. Open the order in which you want to change an address. Note that orders can only be opened in the list view.
. Go to the *Addresses* area.
. On the invoice or delivery address, click on the context menu (material:more_vert[]).
. Select the option *Edit address* (material:edit[]). +
→ The address settings open.
. Carry out the changes.
. *Save* (material:save[]) the settings. +
→ The address is updated according to your settings.


[.instruction]
Assigning another address:

. Go to *Orders » Orders (Test phase)*.
. Carry out the search (material:search[]) to display orders.
. Open the order in which you want to change an address. Note that orders can only be opened in the list view.
. Go to the *Addresses* area.
. On the invoice or delivery address, click on the context menu (material:more_vert[]).
. Select the option *Change address* (material:social_distance[]). +
→ A window with the already existing addresses of the contact opens.
. On the right in the line of the desired address, click on *Assign address* (material:add_link[]). +
→ The selected address is assigned.

*_Note:_* If an order is locked, only the following fields can be changed: +

* Invoice address: *Email address* and *Telephone number*
* Delivery address: all fields except for *VAT number* and *Country*

[#area-messenger]
=== Area: Messenger

In the *Messenger* area, you can see all messages that belong to the order. You can <<#whisper-message, whisper>> messages so that they are only internally visible and _not_ for your customers. You can <<#send-message, send>> messages and you can <<#message-capture-minutes, capture minutes for the message>> and save these minutes as free minutes or paid minutes.

Click on the already created message to open the conversation in the messenger. You can carry out further settings there. In case you want to add a new message, click on *New message* (material:add[]) at the top right. Afterwards, you will be directed to the Messenger in order to create the new message. For further information, refer to the xref:crm:messenger-testphase.adoc#[Messenger (Test phase)] page.

[#whisper-message]
==== Whispering a message

Proceed as described below to whisper a message.

[.instruction]
Whispering a message:

. Go to *Orders » Orders (Test phase)*.
. Carry out the search (material:search[]) to display orders.
. Open the order in which you want to whisper a message. Note that orders can only be opened in the list view.
. On the left side, click on *Messenger*.
. Click on *New message* (material:add[]). +
→ The messenger opens.
. Select one ore multiple recipients. +
*_Note:_* The ID of the order is already prefilled as recipient. This way, the email will be sent to the email address that is saved in the invoice address.
. Enter more recipients, if needed.
. Enter a subject.
. Enter the text. +
→ Double-click on the word to use formatting options for your message.
. Click on material:attach_file[] *Add attachments* to add a file, if needed.
. Click on material:visibility_off[] *WHISPER* to whisper the message.

[#send-message]
==== Sending a message

Proceed as described below to send a message.

[.instruction]
Sending a message:

. Go to *Orders » Orders (Test phase)*.
. Carry out the search (material:search[]) to display orders.
. Open the order in which you want to send a message. Note that orders can only be opened in the list view.
. On the left side, click on *Messenger*.
. Click on *New message* (material:add[]). +
→ The messenger opens.
. Select one ore multiple recipients. +
*_Note:_* The ID of the order is already prefilled as recipient. This way, the email will be sent to the email address that is saved in the invoice address.
. Enter more recipients, if needed.
. Enter a subject.
. Enter the text. +
→ Double-click on the word to use formatting options for your message.
. Click on material:attach_file[] *Add attachments* to add a file, if needed.
. Click on material:visibility_off[] *Whisper mode* to switch off the whisper mode. +
*_Note:_* The button changes from material:visibility_off[] *WHISPER* to material:forward_to_inbox[role=skyBlue] *SEND*.
. Click on material:forward_to_inbox[role=skyBlue] *SEND* to send the message.

[#message-capture-minutes]
==== Capturing minutes for the message

Proceed as described below to capture minutes for the message. You can then decide whether the minutes are free minutes or paid minutes.

Capturing minutes is only possible for whispered messages.

[.instruction]
Capturing minutes for the message:

. Go to *Orders » Orders (Test phase)*.
. Carry out the search (material:search[]) to display orders.
. Open the order in which you want to create a message with captured minutes. Note that orders can only be opened in the list view.
. On the left side, click on *Messenger*.
. Click on *New message* (material:add[]). +
→ The messenger opens.
. Select one ore multiple recipients. +
*_Note:_* The ID of the order is already prefilled as recipient. This way, the email will be sent to the email address that is saved in the invoice address.
. Enter more recipients, if needed.
. Enter a subject.
. Enter the text. +
→ Double-click on the word to use formatting options for your message.
. Click on material:attach_file[] *Add attachments* to add a file, if needed.
. Click on material:more_vert[] and then activate (material:toggle_on[role=skyBlue]) the option *Capture minutes*. +
*_Note:_* The button changes to material:visibility_off[role=skyBlue] *CAPTURE MINUTES*.
. Click on material:visibility_off[role=skyBlue] *CAPTURE MINUTES* to capture the minutes for the message. +
→ The *Capture minutes* window opens.
. Adjust the minutes, if necessary.
. Select (material:radio_button_checked[role=skyBlue]) whether the minutes are *Free minutes* or *Paid minutes*.
. Assign tags to the message, if needed.
. Click on *CAPTURE AND SAVE*.

Information on the different table columns in the *Messenger* area can be found on xref:crm:messenger-testphase.adoc#configure-columns[this chapter].

[#area-order-items]
=== Area: Order items

The *Order items* area provides detailed information about the order items.

[[table-order-items]]
.Area: Order items
[cols="1,3"]
|===
|Setting |Explanation

| *Quantity*
|Shows the amount that was ordered of this order item. +
This is a default column.

| *Item ID*
|Shows the item ID of this order item. You can open the item by clicking on the ID. +
This is an optional column.

| *Variation no.*
|Shows the variation number of this order item. +
This is an optional column.

| *Variation name*
|Shows the variation name of this order item. +
This is an optional column.

| *Variation ID*
|Shows the variation ID of this order item.  You can open the variation by clicking on the ID. +
This is a default column.

| *Item name*
|Shows the item name of this order item. +
This is an optional column.

| *Attributes*
|Shows the attributes of this order item. +
This is a default column.

| *Net price*
|Shows the net price of this order item. +
This is a default column.

| *Original net price*
|Shows the original net price of this order item. +
This is a default column.

| *Gross price*
|Shows the gross price of this order item. +
This is a default column.

| *Original gross price*
|Shows the original gross price of this order item. +
This is a default column.

| *Discount [%]*
|Shows the discount that was selected for this order item. +
This is a default column.

| *Surcharge total*
|Shows the sum of the surcharges of the order item. +
This is a default column.

| *Total amount (net)*
|Shows the total net amount of the order item. +
This is a default column.

| *Total amount (gross)*
|Shows the total gross amount of the order item. +
This is a default column.

| *Warehouse*
|Shows the *warehouse* of the order item. +
This is a default column.

| *VAT [%]*
|Shows the VAT rate of the order item in percent. +
This is a default column.

| *External item ID*
|Shows the external *item ID*.

| *External order item ID*
|Shows the *external order item ID* transferred by the market.

| *Property ID*
|Shows the ID of the property.

| *Storage locations*
|Shows the storage location of this order item.

| *Net profit margin*
|Shows the net profit margin.

| *Reorder ID*
|Shows the ID of the reorder.

|===

[#edit-items]
[discrete]
==== Editing items

In the *Order items* area, you can edit the items of the orders. Note that this depends on the order type. To do so, click on *Edit items* (material:edit[]) on the left. The following table lists the available fields. Note that there are different fields available, depending on the order type.

[[table-edit-items]]
.Editing items
[cols="1,3"]
|===
|Setting |Explanation
2+^| *Item*

| *Item ID*
|Shows the item ID.

| *Variation ID*
|Shows the variation ID. +
This is a default column.

| *Variation no.*
|Shows the variation number.

| *Item name*
|Shows the item name.

| *Attributes*
|Shows the attributes.

| *Variation name*
|Shows the variation name.

| *Barcode*
|Shows the barcode.

| *System purchase price*
|Shows the system purchase price.

| *Price selection*
|Shows the price selection.

| *Category discount*
|Shows the category discount.

| *Customer class discount*
|Shows the discount of this customer class.

| *Availability*
|Shows the availability.

| *Net stock*
|Shows the net stock.

| *Warehouse*
|Shows the warehouse.

| *Quantity*
|Shows the quantity.

2+^| *Shopping cart*

| *Quantity*
|Shows the item quantity. If needed, adjust the quantity.

| *Item ID*
|Shows the item ID. +
You can open the item by clicking on the ID.

| *Variation ID*
|Shows the variation ID of this order item. +
You can open the variation by clicking on the ID.

| *Item ID* / *Variation ID*
|Shows both the item ID and the variation ID.

| *Variation no.*
|Shows the number of the variation.

| *Item name*
|Shows the name of the item. +
Edit the name in the input field if needed.

| *Attributes*
|Shows the attributes.

| *Variation name*
|Shows the name of the variation.

| *Barcode*
|Shows the barcode.

| *System purchase price*
|Shows the system purchase price.

| *Price selection*
|Shows the price selection. If needed, select another price selection from the drop-down list.

| *Category discount*
|Shows the discount of this category.

| *Customer class discount*
|Shows the discount of this customer class.

| *Net price*
|Shows the net price of the item. If you applied a discount, this has already been deducted. The gross price will also be adjusted automatically.

| *Original net price*
|Shows the original net price of the item before a discount was applied. You can adjust (material:edit[]) the original net price if required.

| *Gross price*
|Shows the gross price of the item. If you applied a discount, this has already been deducted. The net price will also be adjusted automatically.

| *Original gross price*
|Shows the original gross price of the item before a discount was applied. You can adjust (material:edit[]) the original gross price if required.

| *Surcharge total*
|Shows the total sum of the surcharge.

| *Discount [%]*
|Shows the discount in percent. If you want to display the discount as amount, select the option *Amount* from the drop-down list. +
*_Note:_* The amount is displayed in the currency of the order.

| *Total amount (net)*
|Shows the total net amount of the order.

| *Total amount (gross)*
|Shows the total gross amount of the order.

| *Warehouse*
|Shows the warehouse. Select another warehouse from the drop-down list if required or enter the name of a warehouse to search for it.

| *VAT [%]*
|The VAT is shown in %. +
19.00 % are preset for the VAT. You can change the VAT rate in the drop-down list.

| *Weight [g]*
|Shows the item weight in grams. +
Edit the weight in the input field if needed.

| *Length [mm]*
|Shows the length of the item in mm. +
Edit the length in the input field if needed.

| *Width [mm]*
|Shows the width of the item in mm. +
Edit the width in the input field if needed.

| *Actions*
|Provides further actions for the items in the context menu (material:more_vert[]) on the right.

2+^| *Delete order items*

| *Delete* (material:delete[])
|You can delete an order item by clicking on material:delete[] on the right-hand side.

2+^| *Context menu* (material:more_vert[])

| *Update sales prices* (material:refresh[])
|Updates the sales prices.

| *Remove variations* (material:link_off[])
|Deletes the assigned variation from the order item.

| *Edit properties* (material:edit[])
|Edit the property. It is possible to edit the fields *Name*, *Value* and *Surcharge* in the editing mode.
|===

[#order-item-properties]
[discrete]
==== Displaying and editing order item properties

Click on the arrow symbol (material:chevron_right[]) in any desired line in the *Edit items* area in order to display the order item properties. If you saved order item properties, then you can edit them (material:edit[]) via the context menu (material:more_vert[]).

[#area-payment-terms]
=== Area: Payment terms

In the *Payment terms* area, information about *Payment due date*, *Early payment discount (%)*, and *Value date (days)* is displayed.

[IMPORTANT]
.Add payment due date
======
If you want to use value date and early payment discount, you need to enter a payment due date. If there no entry is made or the value 0 is entered for the payment due date, the payment terms will not be transferred to documents.
======

If the values were already saved in the xref:crm:edit-contact.adoc#contact-details[contact data], they will automatically be displayed here. Thus, contact data have priority. If nothing is saved in the contact data, it is checked whether the payment terms are defined in a xref:crm:preparatory-settings.adoc#create-customer-class[customer class]. If this is the case, these data are entered in the order. If the values do neither exist in the contact data nor in the customer class, the fields for the payment terms in the order remain empty. +
In an order, the payment terms can be manually entered and edited. This is regardless of the fact where the values were taken from or whether no values were transferred. +
Documents will show the values that are saved in the corresponding order. For this, also note the xref:orders:order-documents-new.adoc#intable-payment-terms-documents[document settings]. The payment terms are displayed on the order documents xref:orders:generating-invoices.adoc#[invoice], xref:orders:generating-pro-forma-invoice.adoc#[pro forma invoice], xref:orders:generating-order-confirmation.adoc#[order confirmation], and xref:orders:generating-offer.adoc#[offer]. +
*_Note:_* The payment terms will only be displayed on documents if the corresponding order was paid with the payment method xref:payment:invoice.adoc#[Invoice] or the payment method xref:payment:cash-in-advance.adoc#[Cash in advance].

[[table-payment-terms]]
.Settings in the *Payment terms* area
[cols="1,3"]
|===
|Setting |Explanation

| *Payment due date*
|Enter the payment due date in days.

| *Early payment discount (%)*
|Displays the early payment discount expressed as a percentage.

| *Value date (days)*
|Displays the value date in days.
|===

[#area-bank-data]
=== Area: Bank details

The *Bank details* area gives you an overview of the bank details. Click on *New bank details* (material:add[]) to add data.

[[table-bank-data]]
.Settings in the *Bank details* area
[cols="1,3"]
|===
|Setting |Explanation

| *IBAN*
|Enter the *IBAN*. +
This field is a mandatory field.

| *BIC*
|Enter the *BIC*. +
This is an optional field.

| *Account holder*
|Enter the *Owner*. +
This field is a mandatory field.

| *Account number*
|Enter the *Account number*. +
This is an optional field.

| *Bank code*
|Enter the *bank code*. +
This is an optional field.

| *Bank*
|Enter the name of the *bank*. +
This is an optional field.

| *Street of the bank*
|Enter the *street of the bank*. +
This is an optional field.

| *Postcode and town of the bank*
|Enter the *postcode and town of the bank*. +
This is an optional field.

| *Country of the bank*
|Select the *country* from the drop-down list. +
This is an optional field.

| *SEPA direct debit mandate*
|Activate the *SEPA direct debit mandate* via the toggle material:toggle_on[role=skyBlue]. Afterwards, further fields will be displayed. Carry out the respective settings. You can change the date via the calendar (material:today[]).

| *Type of mandate*
|Select between *SEPA business to business direct debit* or *SEPA core direct debit*. +
This field is only visible if the option *SEPA direct debit mandate* has been activated.

| *Payment frequency*
|Select between *One-off payment* and *Recurring payment*. +
This field is only visible if the option *SEPA direct debit mandate* has been activated.

|===

[#area-assigned-payments]
=== Area: Assigned payments

In the *Assigned payments* area, you can see all information about the payments that are assigned to an order. You can configure the columns (material:settings[]) as well as create new payments (material:add[]).

[[table-assigned-payments]]
.Settings in the *Assigned payments* area
[cols="1,3"]
|===
|Setting |Explanation

| *Total order amount*
|Displays the total amount of the order.

| *Paid*
|Shows the amount that was paid for the order.

| *Open*
|Shows the open amount.
|===

[[table-assigned-payments-available-columns]]
.Available columns for assigned payments
[cols="1,3"]
|===
|Setting |Explanation

| *Payment ID*
|Displays the ID of the payment.

| *Parent ID*
|Displays the parent ID.

| *Order ID*
|Shows the ID of the order.

| *Contact ID*
|Displays the ID of the contact.

| *Payment method*
|Shows the payment method.

| *Credit/Debit*
|Displays the credit/debit.

| *Amount*
|Shows the amount.

| *Status*
|Displays the current status.

| *Reason for payment*
|Shows the purpose of the payment.

| *Sender of payment*
|Shows the sender of the payment.

| *Date of receipt*
|Shows the date on which the payment was received.

| *Import date*
|Displays the date and the time of the payment’s import.

|===



[#area-order-references]
=== Area: Order references

The area *Order references* provides information that are related to the order. Via *Configure columns* (material:settings[]) you can adjust the columns as desired.

[TIP]
Define in the editing mode whether the currency is the *System currency* or the *Order currency*.

[[table-order-references]]
.Settings in the *Order references* area
[cols="1,3"]
|===
|Setting |Explanation

| *Relationship*
|Shows the relationship to this order. This column does not only show the direct parent and child orders, but all related orders. The latter are defined as _Other_.

| *ID*
|Shows the ID of the order.

| *Type*
|Shows the order type.

| *Document*
|Displays the number of the main document.

| *Status*
|Displays the status of the editing process.

| *Created*
|Displays the creation date.

| *Amount*
|Shows the amount.

| *Payment method*
|Shows the selected payment method.

| *Invoice address*
|Displays the invoice address. The invoice address is taken from the contact data record. If there is more than one address, the one saved as the primary invoice address is taken.

| *Delivery address*
|Displays the delivery address. If you select the option *As invoice*, the invoice address is entered automatically as the delivery address as well. Otherwise, the delivery address is taken from the contact data.
|===

[#area-properties]
=== Area Properties

In the *Properties* area, you can see the properties of the order items. Via *Configure columns* (material:settings[]) you can adjust the columns as desired.

[[table-properties]]
.Settings in the *Properties* area
[cols="1,3"]
|===
|Setting |Explanation

| *Type ID*
|Displays the ID of the type.

| *Name*
|Displays the name of the order item property.

| *Value*
|Displays the value of the order item property.

| *Creation date*
|Displays the date and time of the order item property’s creation.

| *Last change*
|Displays the date and time of the last changes.
|===

[#area-documents]
=== Area: Documents

In the *Documents* area you can see all available and archived documents of your orders. You can configure the columns (material:settings[]), create new documents (material:add[]) and upload external documents (material:file_upload[]).

[[table-documents]]
.Settings in the *Documents* area
[cols="1,3"]
|===
|Setting |Explanation

| *All documents*
|Displays all available documents. Depending on the order type, different documents can be created.

| *Archived documents*
|Displays all archived documents. Depending on the order type, different documents can be created.

| *Name*
|Displays the name of the document.

| *Number*
|Displays the number of the document.

| *Type*
|Displays the type of the document.

| *Reference*
|Displays the reference.

| *Warehouse*
|Displays the warehouse.

| *Owner*
|Displays the owner.

| *Last change*
|Displays the date of the last changes.

| *Display date*
|The date that is shown on the document.

| *Actions*
|Allows you to *archive* or *download* a document via the context menu (material:more_vert[]).
|===

[NOTE]
.Coupon documents
======
In case there are sold coupons or vouchers, they are also displayed in the documents. Thus, documents of the type *Coupon* are not coupons that have been redeemed in the order, but coupons that have been sold with this order. Via the context menu (material:more_vert[]), you can *Recreate* (material:restore_page[]) a coupon.
======

[#area-history]
=== Area: History

In the *History* area you get an overview of all previous actions as well as the respective status and date. You can configure the columns (material:settings[]) as desired.

[[table-history]]
.Settings in the *History* area
[cols="1,3"]
|===
|Setting |Explanation

| *Date*
|Displays the date and time.

| *User*
|Displays the user.

| *Action*
|Displays the procedure that was carried out.

| *Status*
|Displays the current status.

|===

[#area-notes]
=== Area: Notes

In the *Notes* area you can see internal order notes as well as notes from customers with the respective date and time of the creation. The most recent note is always displayed at the top. You can also add further notes (material:add[]) and edit or delete internal notes via the context menu (material:more_vert[]). Customer notes can only be deleted, but not be edited. If there is a customer wish, a corresponding tag is automatically shown on the note.

[#area-tickets]
=== Area: Tickets

In the *Tickets* area, you can see all existing tickets of the customer. The following table lists the fields that are available in the *Tickets* area of the order. Via *Configure columns* (material:settings[]) you can adjust the columns as desired.

[[table-tab-tickets]]
.Settings in the *Tickets* area
[cols="1,3"]
|===

| *ID*
|Displays the ticket ID. The ID is automatically assigned by the system and cannot be changed.

| *Type*
|Displays the type of the ticket. Ticket types are created in the *Setup » CRM » Ticket system » Settings* menu in the *Types & Status* tab.

| *Title*
|Displays the title of the ticket.

| *Status*
|Displays the current status of the ticket. Ticket statuses are created in the *Setup » CRM » Ticket system » Settings* menu in the *Types & Status* tab.

| *Created at*
|Displays the creation date of the ticket.

| *Last changes*
|Displays the date of the ticket's last changes.

| *Progress*
|Displays the progress in percent by means of a bar. The percentage is displayed in the bar.

| *Prio*
|Displays the priority of the ticket. There are 6 priority levels. +
Grey star = lowest priority (default priority) +
2 yellow stars = highest priority

| *Age*
|The age of the tickets in days is displayed here. Depending on the age, the ticket is displayed in a different colour: +
Green = The ticket is 0 to 3 days old. +
Yellow = The ticket is 4 to 5 days old. +
Orange = The ticket is 6 to 7 days old. +
Red = The ticket is at least 8 days old.

|===

In order to add a new ticket, click on *Add new ticket* (material:add[]) at the top right. You will automatically be redirected to the *CRM » Ticket system* menu where you can carry out the settings for the new ticket. For more information refer to the xref:crm:using-the-ticket-system.adoc#1600[Ticket system] manual page.

[#splitting-orders]
== Splitting orders

The function for splitting orders can be found in the toolbar of an opened order in the *Orders » Orders (Test phase)* menu. The behaviour when splitting orders depends on your xref:orders:preparatory-settings.adoc#intable-behaviour-after-splitting[basic settings] for this. +
The standard behaviour is that 2 new orders are created when an order is split. The original order is deleted. The shipping costs are recalculated for the new orders. Before splitting the order you are asked how the order items are to be distributed. +
An order can be split when: +

* it is not locked, +
* outgoing items have not been booked yet, +
* no child orders have been created (e.g. returns, delivery orders), +
* no tax-relevant documents have been created and +
* no payments have been assigned to the order yet. +

If you selected the other option *Change of order status*, 2 new orders are created as well. But the original order remains and is assigned a new order status defined by you. With this setting, it is also allowed to split orders with payments that have already assigned to it and for which tax-relevant documents (important: invoice as well as reversal document) have been created. The assigned payment as well as the documents remain with the original order and are not transferred to the split orders. +
If you want a different xref:orders:basic-settings.adoc#intable-splitting-behaviour-shipping-costs[behaviour of shipping costs] than the standard one described above, you can select a different setting in the basic settings for orders.

[#redeem-coupon]
== Redeem coupons

You have already created an order and now you want to add a coupon code? With the *Redeem coupon* function, this is easily possible for orders and advance orders. Depending on whether it is a plentymarkets campaign or an external campaign, different settings are available. To redeem a coupon, proceed as follows.

[.instruction]
Redeeming coupons:

. Go to *Orders » Orders (Test phase)*. +
→ The order overview opens.
. Carry out the search and use filters to display orders.
. Click in the line of the order to open the order. Note that orders can only be opened in the list view.
. At the top, click on *Redeem coupon* (material:redeem[]). +
→ The window *Redeem coupon* opens.
. Select whether this is a plentymarkets campaign or an external campaign.
. Carry out the additional settings. Note <<table-redeem-coupon>>.
. Click on *Redeem*. +
→ The coupon is redeemed.

[[table-redeem-coupon]]
.Redeem coupons
[cols="1,3"]
|===
|*Setting* |*Explanation*

2+^| *plentymarkets campaign*

|*Code*
|Enter the coupon code and click on *Validate*. Afterwards, further fields become visible that can however not be edited.

|*Type*
|The type of the coupon is displayed. This field cannot be edited.

|*Value in €*
|The coupon’s value is displayed in €. This field cannot be edited.

2+^| *External campaign*

|*Code*
|Enter the coupon code.

|*Type*
|Select the type of the coupon.

|*Value in €*
|Enter the coupon’s value in €.

|===

[#checklist-sales-prices]
== Check list for sales prices

Use this check list if you want to edit order items and encounter problems. In most cases this is because the details of the order don’t match the settings of the sales prices.

Therefore, check if the following settings in the *Setup » Item » Sales prices* menu are selected for the respective price:

[%interactive]

* [ ] *1* is set for *Minimum quantity*.
* [ ] The *Currency* the order is in is activated for this price.
* [ ] No *Price type* is activated for this price, i.e. neither RRP, Special offer nor Set price is selected.
* [ ] The *Client* of the order is activated.
* [ ] The required *Customer class* is activated if it is set in the system.
* [ ] The *Country* where the order originated is activated.
* [ ] In the *Referrer* list, *Manuelle Eingabe* (manual input) is activated.
* [ ] The corresponding *Referrer* of the order is activated.

If you can place a check mark next to these options, you should be able to edit the order items. For further information, refer to the xref:item:prices.adoc#[Sales prices and price calculation] page. If you’re still looking for a specific information, you can also ask our supporters in the link:https://forum.plentymarkets.com/[Forum].

[discrete]
== Assigning rights for prices

:rights-purpose: see and edit prices
:right-one: pass:quotes[*Items > Item > Variation > Price > Read*]
:right-two: pass:quotes[*Items > Item > Variation > Price > Update*]
:right-three: pass:quotes[*Orders > Order items > Contribution margin > Read*]

include::_includes:partial$rights.adoc[]
