= Setting up Amazon
:keywords: Amazon, Amazon setup, setting up Amazon, FBA, Amazon FBA, Fulfillment by Amazon, MFN, Amazon MFN, Merchant Fulfillment Network, Prime, SameDay, NextDay, SecondDay, Market, Marketplace, Multi-Channel, Multichannel, Multi-Channel Amazon, Amazon Multi-Channel, Amazon Business, Amazon B2B, Amazon VCS, VCS, VCS Lite, IDU, Invoice Document Uploader, Amazon invoice, VAT calculation service, Amazon Pay, Amazon product type, flat file, flatfile, ASIN, ASIN matching, Amazon platform, amazon.de, authorisation, authentication, credit note import, VCS plentymarkets, VCS Amazon
:description: Learn how to set up Amazon in plentymarkets to start selling your items on the market.
:page-pagination:
:author: team-plenty-channel

link:https://www.amazon.co.uk/[Amazon^] has gone from being the largest internet book store to one of the leading universal shopping centres. Many customers appreciate the large portfolio, rely on the high product quality and expect best service such as fast delivery. With plentymarkets, you have full access to Amazon. Learn how to make items available, activate the interface for data exchange, use the FBA service by Amazon and many more. The abbreviation FBA stands for Fulfilment by Amazon, a service from Amazon where Amazon takes care of the entire stock management and logistics.

[#100]
== Registering with Amazon

Before carrying out the settings in plentymarkets, you have to register as a seller on Amazon. Amazon Seller Central is the central Amazon interface for sellers. On the Amazon UK platform, sellers who sell more than 35 items per month are considered Pro sellers and only have the possibility to upload item lists from this amount on. plentymarkets users need to select the Pro option. It is only possible to use automatic procedures and APIs to manage stock and offers with the Pro option. This option includes a monthly subscription fee as well as additional fees for each item sold. For further information, refer to the link:https://services.amazon.co.uk/services/sell-online/pricing.html[Amazon website^].

== Notes on Amazon accounts

// Add Belgium

Amazon has unified its European marketplaces. This allows you to create and manage product offers on any and all of our Amazon marketplaces in the UK, France, Germany, Spain, Italy and Sweden. You decide which products you want to sell in which country. You manage your business from a single seller account interface. Your seller account is automatically enabled to allow you to sell on the following Amazon platforms:

* Amazon.ae
// * Amazon.bel
* Amazon.de
* Amazon.co.uk
* Amazon.es
* Amazon.fr
* Amazon.it
* Amazon.nl
* Amazon.pl
* Amazon.se
* Amazon.tr

When you sign up, you will be asked to define your home marketplace. You can select any of the marketplaces listed above. However, Amazon recommends that you choose your home marketplace as the country from where you will be operating and fulfilling your orders. Refer to Amazon’s link:https://services.amazon.co.uk/services/sell-online/international-selling.html[information^] about the European Marketplaces Account.

[#350]
[discrete]
===== Amazon platform

If you sell on multiple Amazon platforms with a European Marketplaces Account, then set up a new account for each platform in plentymarkets, depending on which options you want to use, and configure each platform separately. Set up separate accounts for the price synchronisation, the item data export and the import of pending orders. For example, if you only want to use stock synchronisation, do not create a separate account for each country platform. +
The same access data is used for all platforms.

// Add Amazon.bel

[TIP]
.Amazon platforms
====
With plentymarkets, you can sell on the platforms Amazon.de, Amazon.ae, Amazon.ca, Amazon.co.uk, Amazon.com, Amazon.com.mx, Amazon.es, Amazon.fr, Amazon.it, Amazon.nl, Amazon.pl, Amazon.se, and Amazon.tr.
====

[#10]
== Setting up Amazon

There are two ways to set up the Amazon interface:

* In the assistant *Base settings - Amazon* (<<#500, How?>>)
* *_Or:_* In the *Setup* menu (<<#550, How?>>)

[#500]
=== _Alternative 1:_ Setting up Amazon in the assistant

include::partial$amz-basic-assistant.adoc[]

[#550]
=== _Alternative 2:_ Setting up Amazon in the Setup menu

include::partial$amz-setup-menu.adoc[]

[#660]
== Activating the order referrer

:market: Amazon platforms
:referrer: Amazon
:referrer-option: Amazon platforms

include::partial$activate-referrer.adoc[]

[#6900]
== Carrying out Amazon specific shipping profile settings

Since 19/4/2021, the names of shipping service providers and shipping services that are communicated to Amazon to register a shipping must be identical to the names used in Seller Central. To ensure that the names are identical, you need to link your shipping service providers and shipping services with the values that Amazon accepts. This is done in your shipping profiles.

[.instruction]
Carrying out Amazon specific shipping profile settings:

. Go to *Setup » Orders » Shipping » Settings*.
. Click on the *Shipping profiles* tab.
. Open the shipping profile.
. Click on the *Table of shipping charges* tab.
. Expand the region (icon:angle-down[]).
. Navigate to the area *Amazon shipping settings*.
. Select the drop-down list *Transport service*, select the shipping service provider.
. From the drop-down list *Shipping service*, select the type of shipping. +
*_Note:_* The drop-down lists contain values for most common services. If you want to send other values, select the option *Other* and enter the value in the input field.
. Save (terra:save[]) the settings. +
→ When registering the shipping, the selected values are sent to Amazon for this shipping profile. +
*_Note:_* If you do not select any values from the drop-down lists, the shipping profile’s default values are sent to Amazon.
. *_Optional:_* Repeat these settings for all shipping profiles that you use for Amazon.

[#1500]
== Activating the data exchange

This chapter describes the settings that need to be configured in order to exchange data between your plentymarkets system and Amazon. You can import Amazon orders manually via a CSV file. You will also learn how to send shipping confirmations to Amazon, how to synchronise FBA stock and how to reset order reports from Amazon.

[#1900]
=== Importing Amazon orders

Go to *Setup » Markets » Amazon » Data exchange » Order import* to set up the import of Amazon orders. Here, you can import orders manually via a CSV file.

Proceed as follows to set up the manual import of Amazon orders.

[.instruction]
Setting up the manual order import:

. Go to *Setup » Markets » Amazon » Data exchange » Order import*.
. Select the option *Import CSV file* from the *Process for order import* drop-down list. +
→ The *Settings* area opens.
. Carry out the settings. Pay attention to the explanations given in <<#order-import-amazon>>.
. Click on *Preview* (icon:search[role="blue"]) to show a preview of the import.

[[order-import-amazon]]
.Order import for Amazon
[cols="1,3a"]
|===
| Setting | Explanation

| *Book incoming payment*
| The payment is automatically booked when importing the order.

| *Use old format*
| Activate if you still use the old Amazon import format.

| *Client*
| Select the client for the order import.

| *Amazon account*
| Select the Amazon account.

| *CSV file*
| Select the CSV file for the order import.
|===

[.instruction]
Selecting the CSV file for the order import:

. Click on *Select file*.
. Select the CSV file for the import.
. Click on *Open*.
. Click on *Preview* (icon:search[role="blue"]). +
→ The available orders are displayed.
. For the orders that are to be exported, activate the option *Import*.
. Click on the *gear-wheel icon* to carry out the import.

[TIP]
.Tip: Imported orders
====
If orders are imported from Amazon that you did not upload with plentymarkets and/or that contain items which have not yet been created in plentymarkets, then you can manually assign the items for these orders and set the corresponding status.
====

[IMPORTANT]
.Missing invoice address
====
If the invoice address is missing from the orders that were retrieved from Amazon, then contact the Amazon support. Amazon has to carry out this setting.
====

[TIP]
.Original currency and standard currency are different
====
Additional information is saved for orders that are imported with a different currency than the standard currency saved in plentymarkets. In this case, both the original currency and the original gross and net amounts are saved for every item included in the order.
====

[#2200]
=== Sending shipping confirmations to Amazon

As soon as the Amazon order was processed in your plentymarkets system and the goods were shipped, you have to inform Amazon of the new status so that the sales figures can be credited to your account. Your plentymarkets system automatically takes care of this important step via the interface as well.

Orders have to meet the following requirements in order for the shipping confirmation to be sent to Amazon:

*  *Referrer:* Amazon or an Amazon sub-referrer
*  Status range 7 (less than 8)
*  External order number
*  Imported order (not created manually)
*  Outgoing items booked (time must not be in the future)

If the shipping confirmation is not automatically transferred, for example because the servers are temporarily unavailable, or if you want orders to be manually confirmed shortly before an accounting deadline, so that they will still be taken into consideration during the next payment, then you can also transfer shipping confirmations manually to Amazon. No shipping confirmation is sent to Amazon for Prime orders (Amazon_Prime, Amazon_PrimeSame_Day, Amazon_Prime_NextDay, and Amazon_Prime_SecondDay).

[.instruction]
Manually sending shipping confirmations to Amazon:

. Go to *Setup » Markets » Amazon » Data exchange » Shipping confirmation*.
. Select an Amazon account from the drop-down list.
. Enter a date next to *Items shipped on*. +
→ All of the outgoing items from this date are transmitted to Amazon.
. Click on *Send shipping confirmation*.

[#managing-amazon-reports]
=== Managing Amazon reports

The *Setup » Markets » Amazon » Reports » Processing* menu provides an overview of the processing status of your Amazon reports. In this menu, you can see which reports have already been processed and which reports are still in the queue. +
You can also reset or skip your Amazon reports here. That way, you can define which reports should be processed first. Or you can reduce your system’s workload by skipping reports. +
Besides that, you can also download your Amazon reports in this menu.

<<#table-amazon-reports>> contains an overview of the Amazon reports in the *Setup » Markets » Amazon » Reports » Processing* menu.

[[table-amazon-reports]]
.Reports in the *Setup » Markets » Amazon » Reports » Processing* menu
[cols="1,3a"]
|===
| Column | Explanation

| *Seller ID*
| The seller ID of your Amazon seller account.

| *Report ID*
| The report ID of the Amazon report.

| *Processing status*
| The processing status of the report. +
Reports can have the following statuses: +
*Pending* (material:circle[role=blue]) = The report has not been processed yet. +
*Skipped* (material:circle[]) = The report was skipped and has not been processed. +
*Done* (material:circle[role=green]) = The report was processed.

| *Report type*
| The report type. An overview of all Amazon report types is available <<#amazon-report-types, here>>. +
If you hover over a report type, a tooltip with information about this report type is shown.

| *Report created on*
| Shows the date and the time when the report was created.

| *Report updated on*
| Shows the date and the time when the report was last updated.

| *Actions*
| *_Note:_* Some report types cannot be reset or skipped. +

* *Download report* (material:file_download[]): The report is downloaded. +
* *Reset report* (material:history[]): The report is reset. If you reset a report, it will be processed once again. For example, this might be helpful if the report does not contain data of a new order. When the report is processed again, it will also contain new order data. +
However, note that resetting too many or too large reports might affect your system’s capacity. This might result in new reports being processed later. +
* *Skip report* (material:skip_next[]): The report is skipped. If you skip a report, it will not be processed. It is not possible to download the report if it was skipped. +
Skipping reports might be useful if you want to reduce your system’s workload. Besides that, you can define which reports should be processed next, as the next reports in the queue will be processed if you skip reports. +
However, note that reports that are already being processed in the background cannot be skipped. +

*_Note:_* Reports which are older than 31 days (minus 6h) cannot be downloaded, reset, or skipped.
|===

[#amazon-report-types]
[.collapseBox]
.Which Amazon report types are available?
--
The table below contains an overview of all Amazon report types.

[[table-amazon-report-types]]
.Report types
[cols="2,2a"]
|===
| Report type | What does the report do?

| Manage FBA Inventory
| * Stock synchronization for FBA stock

| GET_FBA_MYI_ALL_INVENTORY_DATA
| * Stock synchronization for FBA stock

| GET_ORDER_REPORT_DATA_INVOICING
| * Importing Amazon MFN orders +
*_Important:_* This report does not contain information regarding the Amazon gift service. As such, the following information is imported in a separate process every 5 minutes:

* Type of gift wrap
* Price of gift wrap
* Gift message (optional)

| Amazon Fulfilled Inventory
| * Stock synchronization for FBA stock

| FBA customer returns
| * Importing FBA returns

| Amazon Fulfilled Shipments – Tax Invoicing - EU
| * Importing FBA orders for EU sellers

| Amazon Fulfilled Shipments – Tax Invoicing - NA
| * Importing FBA orders for North American sellers

| GET_FLAT_FILE_VAT_INVOICE_DATA_REPORT
| * Correcting orders  for VCS Lite and VCS plentymarkets +
* Generating missing invoices

| GET_VAT_TRANSACTION_DATA
| * monthly report +
* Correcting orders +
* Importing external invoices and credit notes based on VCS/VCS Amazon

| SC_VAT_TAX_REPORT
| * Correcting and importing external invoices and credit notes based on VCS/VCS Amazon

| MFN XML Order Report - Tax Invoicing - EU
| * Importing FBM orders for EU sellers

| MFN XML Order Report - Tax Invoicing- NA
| * Importing FBM orders for North American sellers

| GET_ORDER_REPORT_DATA_SHIPPING
| * Importing FBM orders for North American sellers
|===
--

[#filter-amazon-reports]
==== Applying search filters

If you only want to take a look at certain reports, then you can apply filters and narrow down the reports which are displayed. To do so, click on *Filters* (material:tune[]) at the top of the menu.
<<#filters-amazon-reports>> contains an overview of all available filters.

[.instruction]
Applying filters:

. Go to *Setup » Markets » Amazon » Reports » Processing*.
. Click on *Filters* (material:tune[]) at the top of the menu.
. Select one or multiple filters. All available filters are listed in <<#filters-amazon-reports>>.
. Click on *Search* (material:search[role=blue]). +
→ The selected filters are applied and the appropriate reports are displayed. +
→ The filters that were applied are displayed at the top of the menu.

*_Tip:_* You can also *reset* (material:refresh[]) the selected filters. Then all Amazon reports will be displayed again.

[[filters-amazon-reports]]
.Filters for Amazon reports
[cols="1,3a"]
|===
| Filter | Explanation

| *Seller ID*
| Select a seller ID from the drop-down list to only display reports with this seller ID. +

*_Note:_* You have to select a seller ID. If you do not select a seller ID, no reports will be displayed.

| *Report ID*
| Enter a report ID to search for a specific report. +
*_Note:_* You can only enter one report ID here.

| *Processing status*
| Select *Skipped*, *Pending*, or *Done* from the drop-down list. Only reports in this status will be displayed.

| *Report type*
| Select a report type from the drop-down list to only display reports of this type.

| *Added from*
| Enter a date in the format *D.M.YYYY* or select a date via the calendar (material:today[]). You can also enter a time in the *Added time from* line or select a time via (material:schedule[]). +
Only reports which were created starting from this date and time will be displayed. Reports which were created earlier will not be displayed.

| *Added to*
| Enter a date in the format *D.M.YYYY* or select a date via the calendar (material:today[]). You can also enter a time in the *Added time to* line or select a time via (material:schedule[]). +
Only reports which were created up until this date and time will be displayed. Reports which were created later will not be displayed.

| *Updated from*
| Enter a date in the format *D.M.YYYY* or select a date via the calendar (material:today[]). You can also enter a time in the *Updated time from* line or select a time via (material:schedule[]). +
Only reports which were updated starting from this date and time will be displayed. Reports which were updated earlier will not be displayed.

| *Updated to*
| Enter a date in the format *D.M.YYYY* or select a date via the calendar (material:today[]). You can also enter a time in the *Updated time to* line or select a time via (material:schedule[]). +
Only reports which were updated up until this date and time will be displayed. Reports which were updated later will not be displayed.
|===

[#request-reports]
==== Requesting reports

In the *Setup » Markets » Amazon » Reports » Request* menu, you can request the creation of Amazon reports.
For example, this can be useful if data is missing in your Amazon reports and you want to request a new report.

*_Notes on requesting reports:_*

* You can only request reports of a time frame of a maximum of one week.

* The timeframe of the requested report should be as short as possible, as processing big reports can cause issues due to the amount of data.

* The number of requests is limited. For example, you can only request certain report types 2 or 5 times per day.

[IMPORTANT]
.Reports without data cannot be created
====
If no data exists for the requested time frame of the report, then Amazon will not create the report. Currently, it is not possible for plentymarkets to inform customers that a report could not be created.
====

[.instruction]
Requesting a report:

. Go to *Setup » Markets » Amazon » Reports » Request*.
. Carry out the settings. Pay attention to the explanations given in <<#table-request-report>>.
. Click on *Request*. +
→ The requested report is created by Amazon. As soon as the report is available, you can retrieve it in the *Setup » Markets » Amazon » Reports » Processing* menu in your plentymarkets system. +
→ It can take several minutes until the report is available in your system.

[[table-request-report]]
.Requesting the creation of a report
[cols="1,3a"]
|===
| Setting | Explanation

| *Start date* (mandatory)
| Enter a date in the format *DD.MM.YYYY* or select a date via the calendar (material:today[]).

| *Start time* (mandatory)
| Enter a time or select it via (material:schedule[]).

| *End date*
| Enter a date in the format *DD.MM.YYYY* or select a date via the calendar (material:today[]).

| *End time*
| Enter a time or select it via (material:schedule[]).

| *Seller ID* (mandatory)
| Select the seller ID of the Amazon seller account that you want to request reports for.

| *Report type* (mandatory)
| Select the report type. If you hover over a report type in the drop-down list, a tooltip with information about this report type is shown. +
*_Note:_* The number of requests is limited. After you selected a report type, you will see how often per day you can request it.
|===

[#2700]
== Retrieving Amazon orders

Anyone who has worked with another shop system in the past can certainly remember just how time-consuming daily order processing in the Seller Central portal can be. All that is made significantly easier with plentymarkets. Here, all orders from all connected markets are collected together into one order folder. Amazon orders automatically become plentymarkets orders, which you can quickly and effectively work with according to the fulfilment procedure that you are accustomed to. You do not even have to worry about the order import. The interface takes care of that for you in the background. A few requirements have to be fulfilled so that everything works correctly. These are summarised in the following.

Orders are retrieved every 15 minutes. However, in some cases it can take up to 90 minutes until an order that was generated in Amazon will appear in your plentymarkets system. That is not a malfunction, but rather is the only possibility due to technical reasons. Usually, an email from Amazon informs you about the sale beforehand and you can already see the order in Seller Central.

[IMPORTANT]
.Discounts on invoices
====
The invoices that plentymarkets generates for Amazon orders only show the amount that customers were billed for by Amazon. Due to technical reason, it is not possible to differentiate between discounts granted by Amazon and discounts granted by sellers.
====

[#2800]
=== Carrying out settings for the interface in plentymarkets

The basic settings *Incoming payment* and *Shipping confirmation* are relevant for importing orders. We assume that you transfer orders with the status *[5] cleared for shipping* and that you let the daily shipping confirmation be generated automatically by your plentymarkets system. Check these settings once again.

=== Editing returns for Amazon orders

Even with Amazon, you have to anticipate the occasional order cancellation after a shipment has taken place. The customer then has to send the items back to you directly. For further information about creating a return in plentymarkets and resetting the outgoing items again, refer to the xref:stock-management:outgoing-items.adoc#[Booking items out] page of the manual.

Amazon received the customer’s payment on your behalf. As such, the reversal also has to take place via Amazon. You also have to take care of this in the order folder in Seller Central.

[IMPORTANT]
.Carrying out a reversal manually or with the help of an event procedure
====
The interface does not automatically trigger the refund of the purchase price with Amazon. Rather, this has to be carried out manually or automatically with the help of an event procedure. If you forget to manually refund the sum or if you forget to set up an event procedure for automatically refunding the purchase price, you risk a customer complaint with Amazon and negative feedback.
====

MFN returns (= shipment by the seller) can be reported to Amazon in form of credit notes with an event procedure. Returns for Amazon can only be created for orders of the type credit note. Proceed as described below.

==== Creating order statuses

First, create an order status for Amazon returns in the *Setup » Orders » Order status* menu, for example *[9.6] Return sent to Amazon*. You need this order status for the Amazon settings.

==== Setting the order status

Set this order status in the Amazon settings as described below.

[.instruction]
Setting an order status for returns:

. Go to *Setup » Markets » Amazon » Settings*.
. Select the Amazon account.
. Click on the *Order settings* tab.
. For the setting *Status for transmitted returns*, select the order status that you previously created for Amazon returns.
. Save (terra:save[]) the settings.

==== Sending returns to Amazon automatically

Set up an xref:automation:event-procedures.adoc#[event procedure] to automatically send returns in form of credit notes to Amazon. As soon as the event procedure *Create a return at Amazon* is triggered in plentymarkets, the credit note created at Amazon is repayed.

:table-event-procedure: <<#event-procedure-automatic-return>>

include::_includes:partial$event-procedure.adoc[]

[TIP]
.Event procedures and credit note import
====
Use event procedures to initiate refunds in plentymarkets. The automatic credit note import (option "Credit note import" in the order settings) ensures that credit notes are not duplicated in your system. If you manually create credit notes or have them created by a third-party system and there are no credit notes in your plentymarkets system, a credit note is created during the import.
====

[[event-procedure-automatic-return]]
.Event procedure for automatically sending returns to Amazon
[cols="1,3,3"]
|===
| Setting | Option | Selection

| *Event*
| Select an event. +
*_Important:_* Do not select the event *Order generation: New credit note*. This may lead to credit notes being created multiple times at Amazon.
|

| *Filter*
| *Order > Referrer*
| *Amazon* or a suitable Amazon sub-referrer, for example Amazon France. +
*_Note:_* Do not select an Amazon FBA referrer such as Amazon FBA Germany for the *Order > Referrer* filter if you use the automatic credit note import.

| *Procedure*
| *Return > Create a return at Amazon*
|
|===

[#3100]
[#3110]
=== Reserving stock for pending orders

Pending orders are imported in status *[1] Incomplete data* into your plentymarkets system and remain there until Amazon approves the orders. Until the approval, no addresses or prices will be saved for the order. After the approval by Amazon, the order is updated and addresses and prices are saved. The automatic stock update decides in which status the order is placed.

If Amazon does not approve the order, the order is not updated, but instead automatically set to status *[8] Cancelled*.

There are two ways to reserve stock for pending orders in plentymarkets: either with an event procedure or in the basic order settings.

[tabs]
====
Setting up the event procedure::
+
--
The following event procedure is used to put the order from status 1 to a status where stock is reserved.

:table-event-procedure: <<#event-procedure-update-order-status>>

include::_includes:partial$event-procedure-tabbed.adoc[]

[[event-procedure-update-order-status]]
.Event procedure for automatically updating order statuses
[cols="1,3,3"]
|===
|Setting |Option |Selection

| *Event*
| *New incomplete order*
|

| *Filter 1*
| *Order > Order type*
| *Order*

| *Filter 2*
| *Order > Referrer*
| *Amazon referrers*

| *Procedure*
| *Order > Change status*
| Select the status in which stock is reserved.
|===
--

Order base settings::
+
--
In the basic settings of the order you can define in which order statuses stock is reserved with the setting *Status for order reservation*.

[.instruction]
Defining order status for stock reservation:

. Go to *Setup » Orders » Settings*.
. For *Status for order reservation*, select the statuses for which stock should be reserved.
. Save (terra:save[]) the settings.
--
====

[#6800]
== Setting up invoice generation for Amazon orders

include::partial$invoice-creation.adoc[]

[#4500]
== Permitting payment method in customer classes

As soon as an active Amazon account exists, the *Amazon* payment method is automatically available in your plentymarkets system. No separate configurations are needed for this. You just need to permit the payment method in one or more customer classes.

:payment-method: Amazon
include::partial$activate-payment-method.adoc[tag=mop-customer-class]


[#6600]
== Viewing the API log

The *Data » API log* menu contains a history of processes that run via the Amazon interface. The following formats are available for Amazon:

* *Amazoncatalog*
* *AmazonControllerOrders*
* *AmazonFBAOrders*
* *AmazonOrder*
* *AmazonOrderFulfillment*
* *AmazonPayments*
* *AmazonPaymentsAdvanced*
* *AmazonPaymentsFulfillment*
* *AmazonPriceUpdate*
* *AmazonRequestReport*
* *AmazonOrderRefund*
* *AmazonStock*
* *ArticleAmazonCSV*
* *Reader_ArticleAmazonCSV_Execution*

[.instruction]
Viewing the API log:

. Go to *Data » API log » Tab: API log*.
. Select a format from the *Process* drop-down list.
. *_Optional:_* Select a *date* if you only want to see entries for a specific day.
. Click on *Search* (icon:search[role="blue"]) to carry out the search. +
→ The processes are displayed.

[#1400]
[discrete]
=== Preparing variations

Information on how to prepare variations for exporting them to Amazon have moved. You can now find this information on the xref:markets:preparing-variations.adoc#[Preparing variations] page of the manual.

[discrete]
=== FAQ

The FAQ about price and stock synchronisation have moved. You can now find this information on the xref:markets:preparing-variations.adoc#6700[Preparing variations] page of the manual.

[#next-steps]
== Next steps

After you have set up the interface to Amazon, it is now time to xref:markets:preparing-variations.adoc#[prepare your variations for the export to Amazon].
