= Automatic product and offer data exchange
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Mediamarkt, Mediamarkt.de, media markt
:description: Multi-Channel in plentymarkets: Set up the interface to the market Mediamarkt in your plentymarkets system.
:position: 0
:url: markets/mediamarkt/automatic-data-exchange
:id: M5YQMBY
:author: team-multi-channel

:mediamarkt:
:market: Mediamarkt
:marketplace-url: https://marketplace.plentymarkets.com/en/mediamarkt_6918
:assistant-name: Mediamarkt
:category-example: VIDEO CASSETTES

[.previous-next-navigation]
<<markets/mediamarkt/mediamarkt-setup#, Setting up Mediamarkt icon:long-arrow-right[]>>
<<markets/mediamarkt/automated-order-processing#, Setting up automated order processing icon:long-arrow-right[]>>

'''

include::../_textblocks/mirakl/mirakl-synchronisation/mirakl-data-intro.adoc[]

[#general-information]
== About automatic data exchange

include::../_textblocks/mirakl/mirakl-synchronisation/mirakl-data-exchange-table.adoc[]

[#item-export-catalogue]
== Setting up the item export

include::../_textblocks/mirakl/mirakl-synchronisation/mirakl-data-catalogue-intro.adoc[]

[#catalogue-in-assistant]
=== Creating a catalogue in the assistant

Proceed as described below to create a catalogue in the assistant.

:catalogue-assistant-name: {market} Catalogue
:number-of-boxes: Info box
:mapping-fields: the
:catalogue-path: pass:quotes[*Setup » Assistants » Plugins » [select plugin set]*]
:catalogue-note: pass:quotes[Only select bottom level categories. You can find a better overview of the category hierarchy on Miracle by going to *My account » My product data settings*.]

include::../_textblocks/catalogues/instructions/catalogue-assistant-config.adoc[]

[#map-data-fields]
=== Mapping data fields in the catalogue

After you have created a catalogue, map the market's data fields to item data saved in plentymarkets. Check the documentation of the sales channel to find out what data the market expects for the individual data fields.

[TIP]
.Using properties
====
Use <<item/settings/properties#500, properties>> to export values for marketplace data fields that have no corresponding field in plentymarkets.
====

include::../_textblocks/catalogues/instructions/catalogue-mapping.adoc[]

[IMPORTANT]
====
Do not map plentymarkets data fields to the following marketplace data fields for the market {market}:

* Main Product Image
* Additional Product Image 1
* Additional Product Image 2

You can ignore the warning shown when you save the mapping.

_*Note:*_ Do not map any attributes “xy (ES)” when creating items. The items will be exported to MIRAKL anyway.
====


[[catalogue-mirakl-mappings]]
.{market} mappings
[cols="1,2a"]
|====
|Marketplace data field |plentymarkets data field

| *Brand*
a| Create a property of type *Text* for this marketplace data field. Create a property value for each type of unit that you use for your products. Be sure to enter the code, not the label. +

*_Tip:_* You can find all possible values in the respective CSV file. +

*_Note:_* For this marketplace data field, you _cannot_ use properties of the type *Multiple selection*. Mapping a property of the type *Multiple selection* in the catalogue will cause an incorrect transfer.

| *Title*
a| Map one or more of the following plentymarkets data fields to this marketplace data field. Use at least 20 and not more than 100 characters. +
*_Note:_* You can only transfer plain text. HTML tags are _not_ allowed.

* Name 1

_or_

* Name 2

_or_

* Name 3

_or_

* Property

| *SHOP_SKU*
a| Map the following plentymarkets data field to this marketplace data field:

* SKU

Map the following plentymarkets data field as fallback data field:

* Variation ID

| *EAN*
a| Map the following plentymarkets data field to this marketplace data field:

* GTIN 13

| *Seller Product ID*
a| Map the following plentymarkets data field to this marketplace data field:

* SKU

Map the following plentymarkets data field as fallback data field:

* Variation ID

| *Weight (according to the manufacturer)**
a| Map the following plentymarkets data field to this marketplace data field:

* Gross weight in g

_or_

* Net weight in g

| *Width**
a| Map the following plentymarkets data field to this marketplace data field:

* Width in mm

| *Height**
a| Map the following plentymarkets data field to this marketplace data field:

* Height mm

| *Depth**
a| Map the following plentymarkets data field to this marketplace data field:

* Length in mm
|====


[#additional-properties]
=== Creating additional properties

include::../_textblocks/mirakl/mirakl-synchronisation/mirakl-data-additional-properties.adoc[]

[#link-variation-to-catalogue-category]
== Linking variations to a {market} catalogue category

include::../_textblocks/mirakl/mirakl-synchronisation/mirakl-data-link-categories.adoc[]

[#link-properties-with-variations]
==== Linking properties with variations and saving values

include::../_textblocks/properties/instructions/properties-link.adoc[]

[#{market}]
== Activating the catalogue export

:interval: daily
:market: {market}
:if-active:

include::../_textblocks/catalogues/instructions/catalogue-activation.adoc[]

[#marketplace-specific-values]
=== Transferring marketplace-specific values

The marketplace requires specific values for most of the attributes in order to be able to transfer product data. Currently, these values are, however, not yet saved at the variation. +
*_Example:_* For example, it is not allowed to enter *test* for the attribute *Brand*. You have to transfer the corresponding code in this case - in this example *BRAND_12345678*.

The parameters valid for market attributes are displayed in parentheses behind the attribute. Ask your Mediamarkt contact person for more information about the valid attribute values.

=== Mapping and transferring valid attribute values

In case there are different attribute values that might be valid depending on the variation that you want to transfer, the first question is how you keep your item data up-to-date.
If you manage your item data manually, it is recommended to use a property of the type *Selection*. You can save a description for the selection here. This description will then be shown in the property overview at the variation.
Once the code was mapped to the property, you can use the real name of the variation in the field *Description*. This means the code is transferred via the catalogue and the real name is shown in brackets behind. +

*_Tip:_* If you always want to transfer only one single value for an attribute, e.g. you want to use always *BRAND_12345678* for the brand, you can use the option *Own value* in the catalogue.

[discrete]
=== Do not overwrite existing offers on Mediamarkt

If you are already selling items on Mediamarkt, you have to save ProductIDs at the variations in plentymarkets. By doing so, you make sure that the existing product data will not be overwritten and only new offers are created for the products. When transferring product data, a ProductID will be transferred to Mediamarkt. The ProductID is important to establish a connection between offer and product during the data transfer.

When a product that does not have a marketplace SKU yet is transferred, the variation ID will be saved automatically as marketplace SKU by default. Later during the offer transfer, the value that is saved as marketplace SKU will be used for *sku* and *product-id*.

Enter a valid EAN in the catalogue and transfer it to Mediamarkt.

[#product-and-offer-data]
== Transferring product and offer data

:profile-free-shipping: Free Shipping (FS)
:market-backend-shipping: Platform Settings » Shipping

include::../_textblocks/mirakl/mirakl-synchronisation/mirakl-data-product-data-export.adoc[]

[#variation-availability]
== Setting the variation availability

:market-availability: {market}
:option-availability: {market}
:mirakl-activate-variation-availability:
:mirakl-referrer:

include::../_textblocks/instructions/variation-availability.adoc[]

'''

[.previous-next-navigation]
<<markets/mediamarkt/mediamarkt-setup#, Setting up Mediamarkt icon:long-arrow-right[]>>
<<markets/mediamarkt/automated-order-processing#, Setting up automated order processing icon:long-arrow-right[]>>
