= Amazon Best practice: Error Request is throttled
:lang: en
include::{includedir}/_header.adoc[]
:author: team-multi-channel
:keywords: Amazon errors, Amazon throttling, Error Request is throttled, Request is throttled
:position: 300
:url: markets/amazon/best-practices-amazon-error-request-throttled
:id: ASBZ4BY

This best practice deals with the error “Request is throttled” and how to solve it.

[#100]
== What does the error message “Request is throttled” mean?

The number of requests for each process, such as order import, stock synchronisation, shipping confirmations etc., is limited by Amazon (Maximum Request Quota). If the maximum number of requests is exceeded, the process is blocked and further requests are rejected by Amazon. After a while, new capacities are unlocked a bit at a time (The Leaky Bucket Algorithm), and data transfer is enabled once again.

For further information, refer to link:http://docs.developer.amazonservices.com/en_DE/dev_guide/DG_Throttling.html[Throttling: Limits to how often you can submit requests^]{nbsp}icon:external-link[].

[#200]
==  Major cause of the error

If you use a European or North American marketplace account at Amazon, this error often occurs because a configuration in plentymarkets results in too many requests being sent to this Amazon account at once.

*_Background:_* In the *Setup » Markets » Amazon » Settings* menu, several Amazon accounts were linked to different platforms. However, those platforms all "access" the same European or North American marketplace account. The accounts always have the same merchant ID. Various processes were activated in one/some of these accounts.

Amazon platforms which are usually summarised in one European marketplace account (as of 3 March 2021):

* Amazon.de
* Amazon.fr
* Amazon.it
* Amazon.es
* Amazon.co.uk
* Amazon.nl
* Amazon.pl
* Amazon.se
* Amazon.tr
* Amazon.ae

Amazon platforms which are usually summarised in one North American marketplace account (as of 1 January 2021):

* Amazon.com
* Amazon.com.mx
* Amazon.ca

[IMPORTANT]
====
This error can also occur if you use further external programs which access your Amazon account and “overflow” it in combination with plentymarkets.
====

[#300]
== How to solve the error:

If you use a European or North American Amazon marketplace account, it is useful to activate the processes only for one marketplace account in the *Setup » Markets » Amazon » Settings* menu. Otherwise, the data traffic of those processes will be transferred for every single Amazon account with the same merchant ID.

[TIP]
.Processes which often cause this error and which should therefore not be activated twice:
====
- Order import
- Stock synchronisation
- Stock changes
- Shipping confirmations
====

*P.S.:* An Amazon.com account does not belong to a European marketplace account.
