= Best practice: Reporting partial deliveries to limango
:author: team-plenty-channel
:keywords: limango, shipping items, partial delivery, part delivery, shipping limango orders, limango partial delivery
:description:

A customer ordered several items at limango, but you do not have all of the order items in stock. However, now you already want to send two items which you have in stock to your customer. This best practice teaches you how to do this and how to inform limango that one or more order items have already been shipped.

In order to ship one or more order items, you first create a delivery order for the order item(s) that should be shipped. Afterwards, create the event procedure *Send shipping confirmation to limango*.

[#create-delivery-order]
== Creating a delivery order

First, create a delivery order for the order items that should be shipped.

[.instruction]
Creating a delivery order:

. Go to *Orders » Edit orders*.
. Open the order you want to create a delivery order for. +
→ This is the order from which one or more order items should be shipped.
. Open the *Delivery* tab.
. Enter the *Quantity* that should be transferred to the delivery order in the field *DelOrdQua* (quantity to be transferred to the delivery order).
. Click on *Create delivery order* (terra:execute[]). +
→ The delivery order is created.

*_Note:_* If you want to ship all order items contained in an order - that is, the whole order - then you do not have to create a delivery order. You can simply mark the order as shipped instead. +
Delivery orders help you extract individual order items from an order, for example if you want to ship items that are in stock or if you want to cancel individual order items.

[#event-procedure-partial-delivery]
== Setting up an event procedure

Now set up an xref:automation:event-procedures.adoc#[event procedure] to inform limango that one or more order items were shipped.

*_Note:_* Make sure that you include delivery orders when you create the event procedure, as you created delivery orders for the order items which should be shipped.

:table-event-procedure: <<#event-procedure-partial-delivery-limango>>

include::_includes:partial$event-procedure.adoc[]

*_Note:_* The status in the event procedure below was selected as an example. Select the status that best suits your workflow. To do so, select an already existing status or xref:orders:managing-orders.adoc#1220[create] a new status. +
Note that all order items contained in main orders will also be marked as shipped if you use the recommended events and filters.

[[event-procedure-partial-delivery-limango]]
.Event procedure for automatically reporting partial deliveries to limango
[cols="1,3,3"]
|===
|Setting |Option |Selection

| *Event*
| *Order change: Outgoing items booked*
| 

| *Filter 1*
| *Order > Referrer*
| *Limango*

| *Action*
| *Plugins*
| *Send shipping confirmation to limango*
|===