= Amazon Best practice: MFN order import
:author: team-plenty-channel
:keywords: Merchant Fulfilment Network, Merchant Fulfillment Network, MFN
:description: In this best practice you will learn why Amazon MFN orders were not imported into your plentymarkets system and which settings you need to carry out so that the orders will be imported.

This best practice deals with MFN orders (MFN = Merchant Fulfillment Network, i.e. shipment by the seller) that are not imported. We assume that the order import is activated in the basic settings for Amazon.

[#100]
== Authorisation has expired or is missing

For plentymarkets and Amazon to exchange data, you need to allow plentymarkets access to your Amazon account. You grant this access in the menu *Setup » Markets » Amazon » Settings* when you create a new account. When the registration is finished, the access rights are displayed in your seller central within *Settings » User permissions* in the *Amazon MWS Developer Permissions* area. If we are not granted access rights, Amazon blocks all requests. As such, we can neither retrieve data from nor send data to Amazon.

[IMPORTANT]
====
Check whether developer permissions are set up. To do so, go to *Settings » User permissions* in the Amazon seller central.
Another indicator that there are no developer permissions is this error message: _Error:Access to Reports. (GetReportScheduleList) is denied_. You will receive this error message for almost all requests if you did not set up any developer permissions. If you set up _scheduled reports_, then error messages are displayed in the logs or within *Setup » Markets » Amazon » Data exchange » Reports*. How to set up scheduled reports is described below.
====

How to allow access is described in our xref:markets:amazon-setup.adoc#300[manual].

[#200]
== Access rights expired

You can update the access rights in the *Amazon - Base settings* assistant in the *Setup » Assistants » Omni-Channel* menu. To do so, click on *Allow access* in the step *Allow access to Amazon* of the assistant. You are then forwarded to Amazon and have to login with your Amazon access data. On the Amazon page, click on *Confirm* to renew the access rights.

[#300]
== Wrong access data

In order to enable contact between our system and your Amazon account, the access data saved in the basic settings must be correct.

[IMPORTANT]
====
If the seller token is not saved correctly within the basic settings, the error message _ERROR: AuthToken is not valid for SellerId and AWSAccountId_ is issued.
====

[#500]
== Further error messages

If you receive the error message _The seller does not have an eligible Amazon account to call Amazon MWS._, it may be that our system is not authorised to access Amazon. Check the access rights as described above. If they are not available, add the permissions via the assistant.
If this does not help, contact Amazon. Either your seller account is not a power seller account or your account is not properly activated.
