= Best practice: Set up eBay Seller Managed Services
:author: team-plenty-channel
:keywords: eBay SMS, eBay shipping service, eBay shipping methods, eBay shipping profile, bulky deliveries, bulky items, bulky goods, delivery service, eBay shipping
:description: This best practice teaches you how to set up shipping methods for bulky items for eBay in plentymarkets.

eBay Seller Managed Services (SMS) allows you to set up new shipping services for bulky items in eBay. For example, you can offer delivery to a room of choice, assembly of the item, and removal of the old item. +
This best practice teaches you which settings you have to carry out in plentymarkets in order to use the new shipping methods for bulky deliveries on eBay. 

[.collapseBox]
.Which services for bulky deliveries are available?
--
You can offer the following shipping services for bulky deliveries to your customers on eBay:

* Kerbside
* Doorstep
* Room of choice
* Room of choice plus unpackaging
* Room of choice and old item removal
* Room of choice plus old item and packaging removal
* Room of choice plus assembly
* Room of choice plus assembly and unpackaging
* Room of choice plus assembly and old item removal
* Room of choice plus assembly, unpackaging and old item removal

For further information about the new shipping services for bulky deliveries, refer to link:https://www.ebay.co.uk/sellercentre/postage/seller-managed-services[eBay^].
--

*_Note:_* The new shipping services for bulky deliveries can currently only be used for the eBay platforms *Germany* and *UK*.

== Conditions and settings on eBay

In order to use eBay Seller Managed Services, you have to be whitelisted by eBay for the service. Contact your contact persons at eBay for more information.

You have to carry out a few settings on eBay prior to setting up the new shipping services for eBay in plentymarkets.

* Create new rate tables with the new shipping services for bulky deliveries on eBay. Enter the costs and the delivery times for each shipping service in the rate tables. +
Further information on how to set up rate tables is available on link:https://www.ebay.co.uk/help/shipping-items/selling/setting-shipping-options/seller-managed-services?id=5386[eBay^].

* Add the new rate tables to your listings on eBay that you want to offer bulky delivery services for. To do so, create new shipping policies on eBay which include the new rate tables and link those shipping policies with your listings.

== Which settings do I need to carry out in plentymarkets?

After you have carried out all settings on eBay and have set up the new rate tables and shipping policies, import the new rate tables and shipping policies into your plentymarkets system.

[.instruction]
Synchronising rate tables:

. Go to *Setup » Markets » eBay » Data exchange » Tab: Other*.
. In the *Synchronise rate tables* area, select the eBay account from the drop-down list that you want to synchronise the rate tables for.
. Click on *Start* (terra:execute[]). +
→ The new rate tables are imported into plentymarkets.

Next, import the shipping policies into plentymarkets, so that the changes that you made on eBay will also be available in plentymarkets.

[.instruction]
Importing shipping policies:

. Go to *Setup » Markets » eBay » Business policies*.
. Select the eBay account from the drop-down list.
. Select the eBay platform from the drop-down list.
. Click on *Import*.
→ The shipping policies with the new rate tables are imported into plentymarkets. The newly imported shipping policies are also saved in the shipping profiles in plentymarkets.

*_Note:_* If you want to use a specific shipping profile in plentymarkets for the bulky deliveries shipping services, then you can map the shipping services to a specific plentymarkets shipping profile in the *Setup » Markets » eBay » Settings » Shipping profile links* menu. To do so, open the *Setup » Markets » eBay » Settings » Shipping profile links* menu, select the eBay platform and map the eBay shipping profiles with bulky deliveries shipping services with your plentymarkets shipping profiles.