= FAQ
:lang: en
include::{includedir}/_header.adoc[]
:author: team-multi-channel
:keywords: eBay FAQ, eBay help, eBay sales price, eBay Plus order, eBay cross border trade, eBay errors, eBay error codes
:position: 40
:url: markets/ebay/best-practices-ebay-faq
:id: VDXOOCT

This best practice provides some useful tips for eBay.

[#100]
== Why are orders not imported into my system?

In this case, it can be useful to check the log. If orders are not imported, the process *AuctionControllerOrders* is helpful.

A. Has your eBay token expired?
You can check if your eBay token has expired within the *Setup » Markets » eBay » Accounts » Auth'n'Auth* menu.

B. Has the order been stored in the data exchange?
This happens if a customer has not completed the checkout and has eBay calculate the shipping costs.
You can view those orders within *Setup » Markets » eBay » Data exchange*.

[#200]
== Invalid selection of a variation in a market listing

[TIP]
.Has the variation been released for export?
====
First check whether the variations have been released for the export. +
For further information, refer to the corresponding best practice.
====

If the export settings of the variation are correct, the cause may be changes in the content of the variation. +
Whenever you change the content of a variation after creating the listing, these changes also have to be applied to the listing.

. Open the corresponding listing’s LID.
. Adjust the content within the listing’s settings and save the settings.

[#300]
== Why is a listing not ended or restarted automatically?

A. Has the option *End/hide offers automatically* been activated?
This option is activated in the *Setup » Listings » Stock* menu.

B. Has the automatic stock update been activated?
The automatic stock update is activated in the *Setup » Markets » eBay » Settings » Initial settings* menu.
The stock dependence has to be set to *limited (without reservation)*.

C. Has the option *Use out of stock control* been activated?
The *Use out of stock control* option is activated in the *Setup » Markets » eBay » Settings » Account settings* menu.

[#400]
== Which price is prioritised if there is more than one sales price?

[TIP]
.More than one sales price
====
You can create as many prices as desired within *Setup » Item » Sales prices*. +
Therefore, you can create individual prices for each eBay account and each eBay platform if the prices differ.
====

If there is more than one sales price with similar settings, the prices will be prioritised according to fixed criteria. +
For further information on the priorities, refer to the following list.

* Sales prices which are only released for one *market* are prioritised over sales prices which are released for several or all *markets*. +
* Sales prices which are only released for one *country* are prioritised over sales prices which are released for several or all *countries*. +
* Sales prices which are only released for one *eBay account* are prioritised over sales prices which are released for several or all *eBay accounts*. +
* Sales prices which are only released for one *currency* are prioritised over sales prices which are released for several or all *currencies*. +
* Sales prices which have a higher *minimum quantity* are prioritised over sales prices which have a *minimum quantity* of 1. +
* Sales prices which are only released for one *customer class* are prioritised over sales prices which are released for several or all *customer classes*. +

[IMPORTANT]
====
Only sales prices which meet the respective search criteria will be checked.
The referrer and the eBay accounts are relevant for eBay.
====

[#500]
== Why is the order marked as eBay Plus on eBay but not in my plentymarkets system?

The flag for eBay Plus is only transferred to us after the customer has completed the checkout on eBay.

If the shipping costs are calculated by eBay, orders with unfinished checkout will be stored within *Setup » Markets » eBay » Data exchange*. +
The option *Automatically combine open eBay orders* is activated within *Setup » Listings » Checkout*. +
If a duration of e.g. one hour is defined in this menu, orders will be imported into plentymarkets after one hour, regardless of whether the checkout has been completed or not. +

The eBay Plus flag will *not* be checked afterwards.

[#600]
== Which data can be changed at active listings and when?

For information about which data you can change in an active listing and when you can apply changes to an active listing, refer to this link:http://pages.ebay.de/help/sell/listing-variations.html[eBay page^]{nbsp}icon:external-link[]. +

[IMPORTANT]
====
If you have already sold your offer, you can only change your listing to a certain extent. For further information, refer to the link above.
====

[#700]
== What do the error messages mean?

Many errors which occur when setting up listings are issued by eBay and then displayed in your plentymarkets system.
For an overview of error messages, refer to the following list of link:http://developer.ebay.com/devzone/xml/docs/reference/ebay/errors/errormessages.htm[eBay error messages^]{nbsp}icon:external-link[].

[#710]
=== Variation specifics cannot be changed. Variation specifics cannot be changed in restricted revise.

Refer to the chapter *Which data can be changed at active listings and when?* +
If this error message occurs, the variations in plentymarkets do not match the variations on eBay any longer. +
Therefore, the variations, including attribute name and values, have to be changed so that they correspond with the listing.

*Solution:* +
Compare the eBay attributes and attribute names to the attributes and attribute names in plentymarkets. Also bear in mind the attribute link in the *Setup » Item » Attributes* menu if you use an attribute link for this category. +

[#720]
=== Variation Specifics Mismatch. Variation Specifics provided does not match with the variation specifics of the variations on the item.

This error message is either issued during the automatic relisting process or if you select the option *End and restart*. +

In these cases it is possible to keep the old listing's ranking and to transfer the ranking to the new listing. +
eBay expects that the variations which have already been sold are *not changed*. +
If this happens, the aforementioned error message will be issued and restarting the listing will fail. +

*Solution*: +
A.
Restore the variations to their state in the old listing.
This means that if you removed variations, you have to add them again. If you changed the variations' names, you have to undo the change or create an attribute link for the corresponding attribute within *Setup » Item » Attributes*.

B.
End the listing with the *End and delete* option and restart it with the group function.
However, the ranking of your listing will be lost during this process.

[#800]
== How does eBay Picture Services work and how is it used?

With eBay Picture Services, listing images are uploaded to eBay and retrieved by the eBay servers. Without eBay Picture Services, the image is retrieved by the plentymarkets servers.

If and how you should use eBay Picture Services is described below:

[#810]
=== Listing a single item
*One image*: +
The setting within *Setup » Markets » eBay » Settings » Initial settings* is applied.

- *Activated*: The image is uploaded to eBay.

- *Deactivated*: The listing’s image is provided by our servers.

*More than one image*: +
eBay Picture Services is used automatically. In this case, the initial settings are ignored.

[#820]
=== Listing a variation
*One image*: +
The setting within *Setup » Markets » eBay » Settings » Initial settings* is applied.

*Activated*: The image is uploaded to eBay.

*Deactivated*: The listing’s image is provided by our servers. In this case, you can link every variation to a different image. +
For example, if you have 10 variations, you can upload 11 different images without using eBay Picture Services: 1 gallery image and 10 variation images.

*More than one image*: +
eBay Picture Services is used automatically. In this case, the initial settings are ignored.

[#900]
== Why is the telephone number not transferred when orders are imported?

In the field of the telephone number, eBay transfers “Invalid Request” to plentymarkets by default.

*Solution:* +
Log into eBay. Go to *Account Settings » Site Preferences » Shipping preferences* and activate the option *Require phone number for shipping*.

[#1000]
== Cross border trade agreement

The cross border trade agreement must be accepted once you want to list an item on an international platform.
You can accept the agreement link:https://scgi.ebay.de/ws/ebayISAPI.dll?UserAgreementV2&isemail=1&agrid=7&aid=1&UserAgreement=&guest=1[on eBay^]{nbsp}icon:external-link[].
