= bol.com
:author: team-plenty-channel
:keywords: bol.com, bol.com, bol, bol, blo, blo.com, BolItemExport, setting up bol.com, bol.com, bol, Netherlands, Holland, bol.nl, bol.com setup, set up bol.com
:description: Learn how to set up the market bol.com in plentymarkets to start selling your items on bol.com.
:bol.com:
:market: bol.com

The Dutch market link:http://bol.com[bol.com^] is the leading online market in Benelux and offers many different products, including multimedia, electronics, toys, etc. On bol.com, you can sell your items in the Netherlands and Belgium.

[#210]
== Frequency of data exchange

After you have set up the interface to bol.com, the automatic processes described in <<#data-exchange>> are available.

[[data-exchange]]
.Frequency of data exchange
[cols="1,1a"]
|===
|Data |Interval

| Item export
| once a day

| Stock synchronisation
| Every 15 minutes

| Price synchronisation
| Hourly

| Synchronisation of delivery times, visibility of offers etc.
| Hourly

| Deletion of offers for deleted or deactivated variations
| daily

| Order import
| Every 15 minutes

| Import of returns registered on bol.com
| Hourly +
*_Note:_* Returns are imported with the status [9.00] by default.
|===

[#100]
== Registering with bol.com

Before setting up bol.com in plentymarkets, you have to register with link:https://bol.com[bol.com^].

[[setup]]
== Setting up the market in plentymarkets

The basic settings for bol.com are carried out in the *Setup » Assistants » Omni-Channel* menu with the *Basic settings - bol.com* assistant. With this assistant, you set up your bol.com account in plentymarkets. You also carry out settings for warehouses and map plentymarkets delivery times with bol.com delivery times.

:menu-path: pass:quotes[*Setup » Assistants » Omni-Channel*]
:assistant-name: Base settings - bol.com
:number-of-boxes: info box

include::partial$assistant-basic-instructions.adoc[]

[.collapseBox]
.Options in the assistant
--
[[table-bol-basic-settings-assistant]]
[width="100%"]
[cols="1,2a"]
|======
|Setting |Explanation

2+^|Step *Settings*

| *Select the client that should be used to sell your items.*
a| From the drop-down list *Client*, select a client. This client is used to generate the item URL in the catalogue and bol.com orders are assigned to this client.

| *Would you like to activate your bol.com user account?*
a| material:check_box_outline_blank[] = The settings are saved but the data exchange with bol.com is not started. +
material:check_box[] = Data exchange with bol.com is started once the assistant is completed. +
*_Recommendation:_* Check all settings before activating the user account.

2+^|Step *Access data*

| *Enter the API access data.*
a| The API access data can be generated in the seller section at bol.com.

* *Client ID* (mandatory) = Enter the user ID for the API interface you received from bol.com.
* *Client Secret* (mandatory) = Enter the password for the API interface that you received from bol.com.

2+^|Step *Validating access data*

| *Is the access data correct?*
a| It is checked whether your API access data for bol.com is correct. The field *Status of validation* shows whether the access data is correct. If the access data is invalid, then enter it once again in the step *Access data*.

2+^|Step *Event procedure status changes*

| _Select an order status after an event procedure was executed_
a| Select an order status that orders should move to after an event procedure was executed. Select two order statuses for each event procedure: one status that orders should move to after a successful event procedure and one status that orders should move to after an event procedure has failed. If orders should not change their statuses after an event procedure, then select *No status change*. +

Select statuses for the following event procedures: +

* *Send order cancellation to bol.com*
* *Send order shipping confirmation to bol.com*
* *Send return status to bol.com*
* *Create a return at bol.com*

2+^|Step *Warehouse*

| *Select how stock for bol.com should be calculated.*
a| Select the stock quantity for the offer export. Select one of the following options:

* *Use stock quantity sum of all sales warehouses* +
* *Use main warehouse of item* +
* *Select warehouses* = Select one or more warehouses. +
→ The warehouses listed under *Warehouses* can be selected. Place a check mark to select a warehouse.

*_Important:_* The option *Warehouse selection* affects the item export. If an item is not linked to the warehouses selected here, then this item will not be exported.

2+^|Step *Delivery times*

| _Link bol.com delivery times_
| Link one or more bol.com delivery times with delivery times saved in plentymarkets. The linked delivery times will be shown with your items on bol.com.
|======
--

[#250]
=== Activating an order referrer

:market: bol.com
:referrer: bol.com
:referrer-option: pass:quotes[option *bol.com* with ID *152*]

include::partial$activate-referrer.adoc[]

[#500]
=== Selecting the sales price

:referrer-price: bol.com

include::partial$define-sales-price.adoc[]

[#650]
=== Permitting the payment method in a customer class

:market: bol.com
:payment-method: Bol.com

include::partial$activate-payment-method.adoc[]

[#shipping-settings-bol-com]
=== Preparing shipping settings

Next, carry out settings for shipping. For bol.com, you have to save the shipping provider names in Dutch and activate the order referrer *bol.com* in the shipping profiles that you want to use for bol.com.

[#shipping-service-providers-bol-com]
==== Saving names for shipping service providers in Dutch

For bol.com, you have to enter an link:https://api.bol.com/retailer/public/Retailer-API/v6/functional/orders-shipments.html#_transporters[API transporter code^] as name for the xref:fulfilment:preparing-the-shipment.adoc#800[shipping service provider]. In addition, the name of the shipping service provider has to be saved in Dutch. These settings are carried out in the *Setup » Orders » Shipping » Settings* menu.

[.instruction]
Saving names for shipping service providers:

. Go to *Setup » Orders » Shipping » Settings*.
. Click on the *Shipping service provider* tab.
. In the *Filters* section, select the language *nl* from the *Language* drop-down list.
. Click on *Search* (icon:search[role="blue"]). +
→ The shipping service providers are displayed.
. In the input field *Name (nl)*, enter the *API transporter code* for every shipping service provider that you want to use for bol.com. +
*_Tip:_* The *API transporter codes* for the shipping service providers can be found in the link:https://api.bol.com/retailer/public/Retailer-API/v6/functional/orders-shipments.html#_transporters[developer documentation for bol.com^].
. Save (terra:save[]) the settings. +
→ The Dutch names for bol.com shipping service providers were saved.

[#550]
==== Activating the referrer in shipping profiles

:referrer: bol.com

include::partial$shipping-profile-activate.adoc[]

[TIP]
.Saving shipping service provider names in Dutch
====
Make sure that the <<#shipping-service-providers-bol-com, names for the shipping service providers>> in the shipping profiles for bol.com are saved in Dutch with the link:https://api.bol.com/retailer/public/Retailer-API/v6/functional/orders-shipments.html#_transporters[API transporter codes^] required by bol.com.
====

[#600]
== Setting up the item export

Item data is exported to bol.com using catalogues. Use the assistant *Create catalogues - bol.com* to create a marketplace format for every bol.com category.

include::partial$catalogue-new-to-text.adoc[]

[#create-catalogue]
=== Creating a catalogue in the assistant

You need to create a separate catalogue for each combination of a bol.com category and a language. +
*_Tip:_* In the catalogue, the language is shown in brackets behind the category name.

:catalogue-assistant-name: Create catalogues - bol.com
:number-of-boxes: info box
:catalogue-path: pass:quotes[*Setup » Assistants » Omni-Channel*]
:catalogue-note: You need a separate catalogue for each combination of bol.com category and language.
:mapping-fields: the marketplace data fields with plentymarkets data fields

include::partial$catalogue-assistant-config.adoc[]

[.collapseBox]
.Settings in the assistant
--
[[table-catalogue-assistant]]
[width="100%"]
[cols="1,2a"]
|===
| Setting | Explanation

| *Select a category for your catalogue.*
| Select a product category from the drop-down list. +
→ The catalogue is created with the name of the category and shown in the *Data » Catalogues* menu. +
*_Tip:_* Enter a few names of the category name to get suggestions. +
→ In the menu *Data » Catalogues*, the catalogue is shown with the name of the category. +
*_Note:_* You need to create a separate catalogue for each combination of a bol.com category and a language.
|===
--

[#data-field-mappings]
=== Mapping data fields in the catalogue

After you have created a catalogue, map the market's data fields to item data saved in plentymarkets. Check the documentation of the sales channel to find out what data the market expects for the individual data fields.

include::partial$catalogue-mapping.adoc[]

////
[#special-mappings]
=== Besonderheiten bei der Zuordnung von Datenfeldern

Every market structures item data differently. As such, there are some particularities for each market when mapping data fields. <<#special-mappings>> contains mapping information for important data fields for this market.

[[special-mappings]]
.Notes on mapping data fields
[cols="1,3a"]
|===
| Marketplace data field | plentymarkets data field

| *bol_used*
| If you want to sell used products on bol.com, you have to indicate the used condition of your properties by using the property *bol_used*.

* _Property is not linked to the variation_ = The variation is new.
* _Property is linked to the variation_ = The variation is used.

*_Tip:_* Do you only offer used products or only new products? Then you can also specify the condition as an own value. To do so, instead of mapping the property *bol_used*, map the field *Own value* and enter a value in the field that opens.

* Own value `0` or `false` or `n` = All variations are new.
* Own value `1` or `true` or `y` = All variations are used.

|===
////

[#prepare-variations]
== Preparing variations

Continue with preparing your variations.

[#mandatory-info]
=== Saving mandatory item information

In order to list a variation as an offer on bol.com, you need to save at least the settings described in <<#table-bol-variation-checklist>> for this variation.

[[table-bol-variation-checklist]]
.Mandatory fields for the variation
[cols="1,3a"]
|===
| Mandatory data | Explanation

| EAN or ISBN
a| An EAN or an ISBN must be saved for the variation.

* In the *Setup » Item » Barcode* menu, an EAN or ISBN must be created and linked to the referrer bol.com.
* The EAN/ISBN must be added to the *Settings* tab of the variation in the *Barcode* area and a barcode code must be entered.

| Price
a| A price must be saved for the variation.

* The sales price must be activated for the referrer bol.com in the *Setup » Item » Sales prices*.
* The sales price must be added in the *Settings* tab in the *Sales price* area of the variation.
* A price must be saved for the sales price in the *Settings* tab in the *Sales price* area of the variation.

| Name
a| A name in the language of the target country must be saved for the variation. +
*_Example:_* If you want to sell your items in the Netherlands, a name in the language Dutch must be saved for the variation.

* A name must be saved in the plentymarkets data field that you mapped to the marketplace data field for the name.

| Item description
a| A description in the language of the target country must be saved for the variation. +
*_Example:_* If you want to sell your items in the Netherlands, a description in the language Dutch must be saved for the variation.

* A description must be saved in the plentymarkets data field that you mapped to the marketplace data field for the description.

| Manufacturer
a| A manufacturer must be saved for the variation.

* A manufacturer must be saved in the plentymarkets data field that you mapped to the marketplace data field for the manufacturer.

| Image
a| The variation must have at least one image.

* At least one image must be linked in the *Image* tab of the variation.
* in the *Images* tab of the item, the option *{market}* must be selected from the drop-down list *Availability*.

| Property value for bol.com category
a| The variation must be linked to the property value for the bol.com category. The property *bol.com category* is created automatically when you complete the assistant.

* In the *Properties* tab of the variation, the property for the bol.com category must be linked in the *Variation properties* area. The property value has the same name as the bol.com category and the catalogue.

| Availability
a| The variation must be available for the market.

* In the *Availability* tab of the variation in the *Markets* area, the marketplace availabilities *bol.com* or *bol.com FBB* must be activated. +
  ** Referrer *bol.com* = You ship orders yourself. +
  ** Referrer *bol.com FBB* = bol.com ships the order.

| Condition
| * In the tab *Global* of the item, a *Condition for API* must be saved. This condition for API is automatically exported during the offer export.

The plentymarkets conditions are mapped to the bol.com API conditions like this:

* *0 New* = NEW
* *1 Used but as new* = AS_NEW
* *2 Used but very good* = GOOD
* *3 Used but good* = MODERATE
* *4 Used but acceptable* = REASONABLE

|===

[#link-category-property]
=== Linking variations to the property value of the bol.com category

After you created the first marketplace format for bol.com with the assistant, the property *bol.com category* is created in your plentymarkets system. For each bol.com category that you create a catalogue for, a new selection value is added to this property *bol.com category*. This property value has the same name as the bol.com category and the catalogue.

In order for your variations to be exported in the appropriate catalogue, they have to be linked to the *bol.com category* property in the *Properties* tab of a variation.

[.instruction]
Linking variation to bol.com category:

. Go to *Item » Edit item » [Open item]*.
. Click on the *Variations* tab.
. Open the variation that should be linked.
. Open the *Properties* tab.
. In the *Variation properties* area, select the property *bol.com category* from the *Properties* drop-down list and click on *Add* (icon:plus-square[role="green"]). +
→ The property is added.
. Select a category from the drop-down list *Value* for the property *bol.com category*. +
→ The variation will be exported in this catalogue.
. Save (terra:save[]) the settings.

[#300]
=== Activating variations for the market

:market-availability: bol.com
:option-availability: bol.com

include::partial$variation-availability.adoc[]

// Web API NOT required!

[#211]
=== _Optional:_ Activating variations for Fulfillment by bol.com (FBB/LVB)

bol.com orders can be fulfilled in two different ways:

* Fulfilment by Retailer (FBR) = You ship the order yourself.
* Fullfilment by bol.com (FBB/LVB) = bol.com ships your products.

Note that plentymarkets does not fully support Fulfilment by bol.com. You can flag your item data for Fulfilment by bol.com when you export item data to the market. However, FBB orders and returns are not imported into plentymarkets. In addition, stock information cannot be retrieved from the bol.com fulfilment warehouse.

To sell a variation with Fulfilment by bol.com (FBB or LVB), you need to activate the market availability *bol.com FBB*.

[.collapseBox]
.Activate the market availability *bol.com FBB* for the variation
--
. Go to *Item » Edit item » [Open item] » [Open variation]*. +
→ The *Settings* tab of the variation opens.
. Click on the *Availability* tab.
. In the *Markets* area, click in the selection field. +
→ A list of all available markets is displayed.
. Activate the option *bol.com FBB*.
. Save (terra:save[]) the settings.
--

[#automate-orders]
== Automating order processing

Set up xref:automation:event-procedures.adoc#[event procedures] to automatically inform bol.com about changes to the order status. The following event procedures are available for bol.com:

* Send shipping confirmation to bol.com (<<#700, How?>>)
* Send order cancellation to bol.com (<<#900, How?>>)
* Send return status to bol.com (<<#800, How?>>)
* Create a return at bol.com (<<#810, How?>>)

[#700]
=== Automatically sending shipping confirmations

Set up an xref:automation:event-procedures.adoc#[event procedure] to automatically send shipping confirmations to bol.com when the outgoing items have been booked.

:table-event-procedure: <<#event-procedure-shipping-confirmation-bol>>

include::_includes:partial$event-procedure.adoc[]

[[event-procedure-shipping-confirmation-bol]]
.Event procedure for automatically sending shipping confirmations to bol.com
[cols="1,3,3"]
|===
|Setting |Option |Selection

| *Event*
| *Order change: Outgoing items booked*
|

| *Filter 1*
| *Order > Order type*
| *Order*

| *Filter 2*
| *Order > Referrer*
| *bol.com*

| *Procedure*
| *Shipping > Send shipping confirmation to bol.com*
|
|===

[#900]
=== Automatically sending cancellations

Set up an xref:automation:event-procedures.adoc#[event procedure] to automatically inform bol.com of cancellations. Whenever you are dealing with cancellations, you need to send bol.com a reason for the cancellation. Open the *Setup » Orders » Status* menu and create additional order statuses as needed. The following cancellation reasons can be transferred to bol.com:

* *Out of stock*
* *Cancellation requested by customer*
* *Item is in a bad condition*
* *Higher shipping costs*
* *Incorrect price*
* *Item not available in time*
* *No bol.com warranty*
* *Item ordered twice*
* *Item retained*
* *Technical issue*
* *Item untraceable*
* *Other*

:table-event-procedure: <<#event-procedure-cancellations-bol>>

include::_includes:partial$event-procedure.adoc[]

[[event-procedure-cancellations-bol]]
.Event procedure for automatically sending cancellations to bol.com
[cols="1,3,3"]
|===
|Setting |Option |Selection

| *Event*
| *Order change: Status change*
| *[8.1] Cancelled by customer*

| *Filter 1*
| *Order > Order type*
| *Order*

| *Filter 2*
| *Order > Referrer*
| *bol.com*

| *Procedure*
| *Order > Send cancellation to bol.com*
| *Customer cancellation*
|===

[#800]
=== Automatically sending the return status

Set up an xref:automation:event-procedures.adoc#[event procedure] to automatically inform bol.com of the status of a return. bol.com requests the status of returns. The following return statuses can be sent to bol.com:

* *Return received*
* *Item will be exchanged*
* *Return does not meet conditions*
* *Item must be repaired*
* *Customer keeps item*
* *Return accepted after consultation with customer*

:table-event-procedure: <<#event-procedure-return-status-bol>>
:ea-queue:

include::_includes:partial$event-procedure.adoc[]
:!ea-queue:

[[event-procedure-return-status-bol]]
.Event procedure for automatically sending return statuses to bol.com
[cols="1,3,3"]
|===
|Setting |Option |Selection

| *Event*
| *New return*
|

| *Filter 1*
| *Order > Order type*
| *Return*

| *Filter 2*
| *Order > Referrer*
| *bol.com*

| *Procedure*
| *Order > Send return status to bol.com*
|Select a status.
|===

[#810]
=== Sending information on direct returns to bol.com

In addition, set up an xref:automation:event-procedures.adoc#[event procedure] to automatically inform bol.com about returns that customers sent back to you directly without registering the return with bol.com first. bol.com requests the status of returns. The following return statuses can be sent to bol.com:

* Return received
* Item will be exchanged
* Return does not meet conditions
* Item must be repaired
* Customer keeps item
* Return accepted after consultation with customer

:table-event-procedure: <<#event-procedure-return-bol>>

include::_includes:partial$event-procedure.adoc[]

[[event-procedure-return-bol]]
.Event procedure to inform bol.com about returns
[cols="1,3,3"]
|===
|Setting |Option |Selection

| *Event*
| *Order change: Status change*
| *[9.5] Credit note created*

| *Filter 1*
| *Order > Order type*
| *Return*

| *Filter 2*
| *Order > Referrer*
| *bol.com*

| *Procedure*
| *Order > Create a return at bol.com*
| Select a status.
|===

[#activate-catalogue]
== Starting the item export: Activating catalogue export

:interval: once a day during the night

include::partial$catalogue-activation.adoc[]

[#troubleshooting]
== Troubleshooting

[#1200]
=== _Check list:_ Why is my variation not exported?

include::partial$checklist-variations.adoc[tag=checklist-intro]

include::partial$checklist-variations.adoc[tag=checklist-variation-referrer]

include::partial$checklist-variations.adoc[tag=checklist-variation-active]

include::partial$checklist-variations.adoc[tag=checklist-availability-active]

include::partial$checklist-variations.adoc[tag=checklist-net-stock]

include::partial$checklist-variations.adoc[tag=checklist-sales-price]

:anchor-catalogue-mapping: #map-data-fields

include::partial$checklist-variations.adoc[tag=checklist-catalogue-mapped-multi]

include::partial$checklist-variations.adoc[tag=checklist-categories-bol]

include::partial$checklist-variations.adoc[tag=checklist-catalogue-active]

:checklist-log-integration: pass:quotes[*bol.com*]
:checklist-log-reference: pass:quotes[*Plenty\\Modules\\bol.com\\Item\\Services\\ItemExportService*]

include::partial$checklist-variations.adoc[tag=checklist-check-log]

[#1000]
=== Viewing log entries

:market: bol.com
include::partial$viewing_logs.adoc[tag=data-log-intro]

* *Identifier* » *bol.com*

include::partial$viewing_logs.adoc[tag=data-log-config]

Use the reference types and reference values listed in <<#table-reference-types>> to limit the search results:

[[table-reference-types]]
.Reference types and reference values for bol.com
[cols="1,1,3"]
|===
|Reference type |Explanation |Reference value

| *action*
| Filters by events.
a| Select a reference type to filter for specific events. +

* *orderImport* = Order import +
* *CreateOffer* = Creation of offers +
* *CheckOfferStatus* = Checking the successful creation of offers +
* *DeleteOffer* = Deletion of offers +
* *UpdateOffer* = Updating delivery time, delivery type (FBB, FBR), SKU and activity state of offers +
* *UpdateOfferPrices* = Updating prices of offers +
* *UpdateOfferStock* = Updating stock of offers +
* *CancelOrder* = Cancellation of the order +
* *ShipOrder* = Shipping of the order +
* *HandleReturn* = Confirmation of receipt of a return announced on bol.com +
* *CreateReturn* = Report receipt of a return not announced on bol.com

| *orderId*
| Filters by the order ID of the order in plentymarkets.
|

| *externalOrderId*
| Filters by the bol.com order number of the order.
|

| *externalOrderItemId*
| Filters by the ID of the bol.com order item.
|
|===
