= Decathlon
:keywords: Decathlon, Decatlon, Dekatlon, Decathlom
:description: Learn how to set up the market Decathlon in plentymarkets to start selling your items on Decathlon. Decathlon is a market for sportswear and sports gear.
:author: team-plenty-channel

:market: Decathlon
:decathlon:

:page-index: false

link:https://www.decathlon.de/[Decathlon^] is a market for sportswear, sports gear, and accessories.

[#partner-program]
== Becoming a Decathlon partner

First, register with the Decathlon link:https://www.decathlon.de/landing/marketplace-marktplatz-partnerprogramm/_/R-a-marketplace[partner program^] so that you can start selling your items on the market.

After registering, you will receive login details from Decathlon. You need these login details to set up Decathlon in plentymarkets.

[#interval-data-exchange]
== Frequency of data exchange

After you have set up Decathlon in plentymarkets, data is exchanged with the market in the intervals described in <<#table-interval-data-exchange>>.

[#table-interval-data-exchange]
.Frequency of data exchange
[cols="2,3a"]
|===
|Data |Interval

| Item export
| once a day

| Full offer export (creating + updating offers)
| once a day

| Stock synchronisation
| every 15 minutes

| Price synchronisation
| Hourly

| Order import
| every 15 minutes

| Importing refunds
| every 15 minutes
|===

[#order]
== Workflow of an order

* Your items are listed on Decathlon. The name of your company is shown with your items.
* Customers place an order on Decathlon.
* Customers make their payments to Decathlon.
* → The order is imported to plentymarkets.

[#setup]
== Setting up the market in plentymarkets

Now set up the market in plentymarkets.

[TIP]
.In which countries can I offer my items?
====
With Decathlon, you can offer your items in Germany, Belgium, Czech Republic, France, Hungary, Italy, the Netherlands, Poland, Portugal, Romania, Spain, Switzerland, and the UK. To do so, activate the <<#order-referrer, order referrers>> for all the Decathlon country platforms on which you want to offer your items.
====

[#account-overview]
=== Account overview

The *Setup » Markets » Decathlon » Settings* menu provides an overview of your Decathlon accounts. <<tabelle-konto-uebersicht>> lists the columns and available actions in the account overview.

[TIP]
.Configuring columns
====
Click on *Configure columns* (material:settings[]) to define which settings should be displayed in the account overview. +
The columns *ID*, *Name*, *Active*, *Client*, *Order import*, *Item export*, and *Offer export* are displayed in the overview by default.
====

*_Note:_* The account overview looks different depending on which columns you add or hide via *Configure columns* (material:settings[]). The following table only lists the columns which are displayed in the overview by default.

[[table-account-overview]]
.Decathlon account overview
[cols="1a,3a"]
|===
|Column |Explanation

| *ID*
| The ID of your Decathlon account. The ID is assigned automatically when you create a new account.

| *Name*
| The name of your Decathlon account.

| *Active* 
| material:circle[role="blue"] = The account is active and data is exchanged with Decathlon. +
material:circle[] = The account is not active. Data is not exchanged with Decathlon. +

*_Note:_* Data is only exchanged with Decathlon if the account is both connected with Decathlon and *active*. In addition, an *API key* must be saved for the account. Click on *Test connection* in order to connect to Decathlon.

| *Client*
| The client (shop) that orders of this Decathlon account are assigned to.

| *Order import*
| material:done[role="blue"] = The order import for this account is active. Orders are imported into plentymarkets every 15 minutes. +

material:close[] = Orders are not imported.

| *Item export*
| material:done[role="blue"] = The item export for this account is active. Items are exported to Decathlon once per day.

material:close[] = Items are not exported.

| *Offer export*
| material:done[role="blue"] = The offer export for this account is active. A full offer export is carried out once per day. This means that new offers are created and existing offers are updated. +
Stock is updated every 15 minutes. +
Prices are updated every hour. +

material:close[] = Offers are not exported.

| material:more_vert[] *More*
| Click here to display more actions. +

[cols="1,3a"]
!===
! material:delete[] *Delete account*
! Delete the account.
!===
|===

[#basic-settings]
=== Carrying out the basic settings

Carry out the basic settings for the market in the *Setup » Markets » Decathlon » Settings* menu.

First, add a new account for Decathlon.

[.instruction]
Adding a new account:

. Go to *Setup » Markets » Decathlon » Settings*.
. Click on *Add account* (material:add[]). +
→ The *Add account* window opens.
. Enter an *account name*.
. Save (terra:save[]) the settings. +
→ A view with account settings opens.
. Carry out the additional settings. Pay attention to the explanations given in <<#settings-decathlon>>.
. Save (terra:save[]) the settings.

[[settings-decathlon]]
.Settings for the market Decathlon
[cols="1,3a"]
|===
|Setting |Explanation

| *Test connection*
| Click here to test whether a connection to Decathlon could be established. In this step, the API key is checked. +

You have to test the connection again if you change the API key.

2+| General

| *Account*
| The name of your Decathlon account. You entered the name when you created the account.

| *Active* 
| Activate the Decathlon account. The data exchange with Decathlon is started. +

We recommend to only activate the account after you carried out all settings.

*_Note:_* The account has to be connected to a Decathlon account so that data can be exchanged between plentymarkets and Decathlon. The *Decathlon API key* must be saved in plentymarkets.

| *Decathlon API key*
| Enter the API key. You have received the API key from Decathlon.

| *Client*
| Select a client (shop). The orders of this Decathlon account will be assigned to this client.

2+| Item

| *Item export*
| Activate to export items to Decathlon once per day.

| *Map shipping profiles*
| Map your plentymarkets shipping profiles with shipping profiles from Decathlon.

[.instruction]
Mapping shipping profiles:

. Select the *shipping zone* from the drop-down list.
. Click on *Show mappings for the selected zone*. +
→ A new view for mapping shipping profiles opens. +
*_Note:_* Your changes will not be saved. In order to save your changes first, click on *Save* (terra:save[]) in the top left corner before mapping the shipping profiles.
. Click on *Add mapping*. +
→ The window *Add new shipping profile mapping* opens.
. Select the *Decathlon shipping method*.
. Select the *plentymarkets shipping profile*.
. Select the *Decathlon shipping service provider*.
. Click on terra:save[] *Save*. +
→ The new mapping is shown in the menu. +
*_Tip:_* You can edit the shipping profile mappings later on. To do so, click on *More* (material:more_vert[]) and then on *Edit mapping* (material:edit[]).

2+| Orders

| *Order import*
| Activate to import Decathlon orders into plentymarkets every 15 minutes. +

*_Note:_* Every order that was imported into plentymarkets will be billed.

| *Order import start date*
| Enter a date in the format *D.M.YYYY* or select a date via the calendar (material:today[]). +
Only orders starting from this date will be imported into plentymarkets. Orders which were generated before this time will not be imported.

| *Allow cancellations for orders with invoice*
| Should customers be able to cancel an order if an invoice was already created?

| *Automatically cancel refunded orders until order status*
| Select an order status until which orders that were fully refunded should be automatically cancelled. Orders will automatically be cancelled if they have this status or a lower status. If the order has a higher status, then it will be refunded. +

*_Tip:_* Select a status in which you can make sure that the item will not be shipped. Orders which have already been shipped cannot be cancelled.

| *Status for shipped orders*
| Select the xref:orders:order-statuses.adoc#preselected-statuses[order status] for orders that were shipped.

| *Status for credit notes*
| Select the xref:orders:order-statuses.adoc#preselected-statuses[order status] for orders that were refunded by Decathlon.

| *Status for cancelled orders*
| Select the xref:orders:order-statuses.adoc#preselected-statuses[order status] for orders that were cancelled. +

*_Tip:_* Select a status higher than *status 8*.

2+| Offers

| *Offer export*
| Activate to export items to Decathlon once per day. +
A full offer export is carried out once per day. This means that new offers are created and existing offers are updated. +
Stock is updated every 15 minutes. +
Prices are updated every hour. +

| *Fulfillment by Decathlon*
| *_Note:_* This service can currently not be used, as the feature is still being developed by Decathlon.
|===

[#order-referrer]
=== Activating the order referrer

:decathlon:

:referrer: Decathlon
:referrer-option: pass:quotes[desired Decathlon platform, for example *Decathlon Germany*]

include::partial$activate-referrer.adoc[]

[#prepare-variations]
== Preparing variations

Now, prepare your variations.

[#variation-availability]
=== Setting the variation availability

:market-availability: Decathlon
:option-availability: Decathlon

include::partial$variation-availability.adoc[]

[#export-items]
== Exporting item data

Item data is exported to Decathlon using catalogues. Go to *Data » Catalogues* to create catalogues for Decathlon.

include::partial$catalogue-new-to-text.adoc[]

[#add-product-categories]
=== Adding product categories

Before you can create catalogues for Decathlon, you have to add the product categories in which you want to offer your items on Decathlon. This is done in the *Setup » Markets » Decathlon » Add catalogue templates* menu. +
After you added a product category in the *Add catalogue templates* menu, you can create a catalogue for this product category in the *Data » Catalogues* menu.

[.instruction]
Adding product categories:

. Go to *Setup » Markets » Decathlon » Add catalogue templates*.
. Click on *Add categories* (material:add[]).
. Select a category for offering your items. +
*_Tip:_* You can either search the category by entering the name in the input field or you can expand the category tree to browse the available categories.
. Save (terra:save[role="blue"]) the settings. +
→ The category was added. You can now create a catalogue for this category in the *Data » Catalogues* menu.

[#link-product-category]
=== Linking variations to a Decathlon product category

[TIP]
.Which variations are exported to Decathlon?
====
You can use catalogue filters in the menu *Data » Catalogues » [Open catalogue] » Filters* to define which variations should be exported to Decathlon. The filters *Decathlon* and *Active* are already set by default. This means that all variations which are *active* and which have the market availability for Decathlon in the *Availability* tab will be exported to Decathlon. +
You can use the *custom filters* in the catalogue to define in detail which variations should be exported to Decathlon.
====

You can use properties to define in which product category on Decathlon a variation should be listed. For example, you can create the property *Decathlon product categories* of the type selection and use the Decathlon product categories as selection values. You can then use the filters in the catalogue and filter for the property to define into which product category on Decathlon the variations should be exported.

[.instruction]
Create a property of the type selection:

. Go to *Setup » Settings » Properties » Configuration*.
. Click on material:add[] *Create property*. +
→ The settings for the new property are displayed.
. In the area *Details*, select the *type* *selection*.
. In the area *Details*, select the *section* *Items*.
. Carry out the additional settings. +
→ *_Tip:_* For example, you can use *Decathlon product category* as name for the property.
. Save (material:save[]) the settings. +
→ The property is created.
. In the area *Selection values*, click on *Create selection value*.
. Enter a name for the selection value. +
→ *_Tip:_* You can enter the different Decathlon product categories as names for the selection values, for example *Trail shoes* or *Running shoes*.
. Save (material:save[]) the settings. +
→ The selection value is created and displayed in the overview. The value automatically receives a consecutive and unique ID that cannot be changed. You need this ID to only export specific variations in a catalogue.

Next, link the desired variations with the selection property that you created.

[.instruction]
Link variation with property:

. Go to *Item » Edit item » [Open item]*.
. Click on the *Variations* tab.
. Open the variation that should be linked.
. Open the *Properties* tab.
. In the *Variation properties* area, select the property you created from the *Properties* drop-down list and click on *Add* (icon:plus-square[role="green"]). +
→ The property is added.
. Select the desired product category from the drop-down list *Value*.
. Save (terra:save[]) the settings.

Afterwards, add the ID of the selection value as filter in the desired Decathlon catalogue.

*_Tip:_* Open the property in the menu *Setup » Settings » Properties » Configuration* to see the IDs of the selection values.

[.instruction]
Apply filters in the catalogue:

. Go to *Data » Catalogues*.
. Open the Decathlon catalogue.
. On the left-hand side, open the tab *Filters*.
. In the area *Custom filters*, select the filter *Linked to at least one property selection value*.
. Enter the ID of the selection value of the property. +
*_Tip:_* Open the property in the menu *Setup » Settings » Properties » Configuration* to see the IDs of the selection values.
. Save (material:save[]) the settings.

[#create-catalogue]
=== Creating a catalogue

Item data is exported to Decathlon using catalogues. To export your items to Decathlon, create a catalogue in the *Data » Catalogues* menu. Afterwards, link the Decathlon data fields with item data saved in plentymarkets in the catalogue. +
After you activate the catalogue, the catalogue data is automatically exported to Decathlon in regular intervals.

*_Note:_* There is a separate catalogue format for each Decathlon product category. Different item data is exported in the different catalogue formats, depending on which information Decathlon requires for each product category. +
This means that you have to create a separate catalogue for each Decathlon product category that you want to sell your items in. Go to *Setup » Markets » Decathlon » Add catalogue templates* to add product categories.

[IMPORTANT]
.Create a catalogue for offers
====
For Decathlon, you always have to create a catalogue for offers. To do so, select the format *Offer* when you create a catalogue in the *Data » Catalogues* menu. +
The offer catalogue is required in addition to the catalogues for the different Decathlon product categories so that offers can be created on Decathlon. 
====

:catalogue-template-name: Decathlon
:format-item-new:
:one-per-category:
:decathlon:

include::partial$catalogue-creation.adoc[]

[#map-data-fields]
==== Mapping data fields in the catalogue

After you have created a catalogue, map the market's data fields to item data saved in plentymarkets. This chapter describes how you map data fields and what particularities apply for item exports to {market}.

include::partial$catalogue-mapping.adoc[]

[#recommended-mappings]
==== Recommendations for data field mappings

include::partial$recommendation-text.adoc[]

*_Note:_* You have to create a separate catalogue for each Decathlon product category that you want to offer your items in. +
Catalogues for different product categories contain different data fields. This is because different item data has to be specified in each Decathlon product category. +
Here, we will therefore only recommend the mappings for the offer catalogue.

[.collapseBox]
.List of recommended data field mappings for the format *Offer*
--
include::partial$decathlon-recommended-mappings.adoc[]
--

[#particularities-data-fields]
==== Notes on mapping data fields

Every market structures item data differently. As such, there are some particularities for each market when mapping data fields. This chapter contains mapping information for important data fields for Decathlon.

[#html]
===== Do not use HTML formatting

Description texts containing HTML formatting cannot be exported to Decathlon. If you want to use formatting for your Decathlon texts, then use the markup language markdown instead. +
Take care not to use HTML formatting especially for item and offer descriptions so that the texts will be displayed correctly on Decathlon.

[#activate-catalogue]
==== Activating the catalogue export

:interval: once a day
:decathlon:

include::partial$catalogue-activation.adoc[]

[#menu-data-exchange]
== Manually managing the data exchange

In the menu *Setup » Markets » Decathlon » Data exchange* you can import and export data manually. This menu is mainly meant to test the export. For example, you can only export specific item and offer data or only import individual orders to plentymarkets. This can be helpful if you want to test the export or if you have to import missing orders.

[#item-data-export]
=== Manually exporting item data:

In the *Setup » Markets » Decathlon » Data exchange » Data export* menu, you can export individual items and offers to Decathlon. For example, this can be helpful if you want to test the export to Decathlon or if you only want to export individual items.

*_Note:_* In the *Data export* menu, you can already export data even if the account has not been activated yet. This way, you can test the export with individual items and offers before you activate the account.

[.instruction]
Manually exporting an item:

. Go to *Setup » Markets » Decathlon » Data exchange » Data export*.
. Select the *Account* from the drop-down list.
. Select a *catalogue* from the drop-down list.
. Enter one or more *item IDs* separated by comma. Those items will then be exported to Decathlon.
. Click on material:file_upload[role="blue"] *Export*. +
*_Note:_* You can run this process every 30 minutes. Items cannot be exported manually between 24.00 - 6.00 CET. +
*_Tip:_* Click on *Preview* to generate e preview of the export.

[.instruction]
Manually exporting offers:

. Go to *Setup » Markets » Decathlon » Data exchange » Data export*.
. Select the *Account* from the drop-down list.
. Select a *catalogue* from the drop-down list.
. Enter one or more *item IDs* separated by comma. The offers for those items will then be exported to Decathlon.
. Click on material:file_upload[role="blue"] *Export*. +
*_Note:_* You can run this process every 15 minutes. +
*_Tip:_* Click on *Preview* to generate e preview of the export.

[#order-import]
=== Manually importing orders

In the *Setup » Markets » Decathlon » Data exchange » Order import* menu, you can manually import individual orders into plentymarkets. +
You can either enter the order IDs of the orders you want to import, or you can import orders from a specific time frame.

*_Note:_* You can run this process every 15 minutes.

[tabs]
====
Entering order IDs::
+
--
[.instruction]
Import orders by ID:

. Go to *Setup » Markets » Decathlon » Data exchange » Order import*.
. Open the tab *Import orders by order ID*.
. Enter one or more order IDs into the input field *Order IDs*. Separate the IDs by comma if you enter more than one ID.
. Click on *Import*. +
→ The orders are imported into plentymarkets.
--
 
Selecting a time frame::
+
--
[.instruction]
Import orders by date:

. Go to *Setup » Markets » Decathlon » Data exchange » Order import*.
. Open the tab *Import orders by date*.
. Enter an *Order import start date* in the format *DD.MM.YYYY* or select a date via the calendar (material:today[]).
. Enter an *Order import end date* in the format *DD.MM.YYYY* or select a date via the calendar (material:today[]).
. Click on *Import*. +
→ Orders from the selected time frame are imported into plentymarkets.
--
====

[#set-up-event-procedures]
== Automating order processing

Set up xref:automation:event-procedures.adoc#[event procedures] to automatically inform {market} about changes to the order status. The following event procedures are available for {market}:

* Automatically inform Decathlon that the items have been shipped. (<<#send-shipping-confirmations, How?>>)
* Automatically upload invoices to Decathlon. (<<#upload-invoices, How?>>)
* Automatically inform Decathlon that an item was refunded. (<<#create-refunds, How?>>)

[#send-shipping-confirmations]
=== Automatically sending shipping confirmations

Set up an xref:automation:event-procedures.adoc#[event procedure] to automatically inform {market} when you have shipped the items of an order.

:table-event-procedure: <<#shipping-confirmation-decathlon>>

include::_includes:partial$event-procedure.adoc[]

*_Note:_* The selected statuses and filters in <<#shipping-confirmation-decathlon>> only serve as an example. Select filters and statuses for the event procedure which best suit your workflow.

[[shipping-confirmation-decathlon]]
.Event procedure for sending shipping confirmations
[cols="1a,3a,3a"]
|===
|Setting |Option |Selection

| *Event*
| Select an event, for example:

* *Order change: Status change*

| Select an event, for example *[7] Shipped*.

| *Filter 1*
| *Order > Order type*
| *Order*

| *Filter 2*
| *Order > Referrer*
| *Decathlon*

| *Procedure*
| *Plugin*
| *Send shipping confirmation to Decathlon*
|===

[#upload-invoices]
=== Automatically uploading invoices to Decathlon

Set up an xref:automation:event-procedures.adoc#[event procedure] to automatically upload invoices to Decathlon.

:table-event-procedure: <<#invoice-decathlon>>

include::_includes:partial$event-procedure.adoc[]

*_Note:_* The selected statuses and filters in <<#invoice-decathlon>> only serve as an example. Select filters and statuses for the event procedure which best suit your workflow.

[[invoice-decathlon]]
.Event procedure for uploading invoices to Decathlon
[cols="1a,3a,3a"]
|===
|Setting |Option |Selection

| *Event*
| Select an event, for example:

* *Documents: Invoice generated* +

*_Note:_* Select an event after which the items have already been shipped.

| 

| *Filter*
| *Order > Referrer*
| *Decathlon*

| *Procedure*
| *Plugin*
| *Upload invoices to Decathlon*
|===

[#create-refunds]
=== Reporting refunds to Decathlon

Set up an xref:automation:event-procedures.adoc#[event procedure] to automatically inform Decathlon that an item was refunded.

Different event procedures can be created, depending on the reason for the refund. The following event procedures are available for Decathlon to report a refund:

* *Report refund to Decathlon: Agreement with vendor*
* *Report refund to Decathlon: Cancelled before shipping*
* *Report refund to Decathlon: Item not received*
* *Report refund to Decathlon: Item returned*
* *Report refund to Decathlon: Out of stock*
* *Report refund to Decathlon: Item sent too late*

:table-event-procedure: <<#refund-decathlon>>

include::_includes:partial$event-procedure.adoc[]

*_Note:_* The selected statuses and filters in <<#refund-decathlon>> only serve as an example. Select filters and statuses for the event procedure which best suit your workflow.

[[refund-decathlon]]
.Event procedure for reporting a refund to Decathlon
[cols="1a,3a,3a"]
|===
|Setting |Option |Selection

| *Event*
| Select an event, for example:

*Order generation: New credit note*

| 

| *Filter*
| *Order > Referrer*
| *Decathlon*

| *Procedure*
| *Plugin*
| Select an event procedure for *Report refund to Decathlon* with the appropriate reason.
|===