= Amazon: FAQ collection
:lang: en
include::{includedir}/_header.adoc[]
:keywords:
:description: Multi-Channel in plentymarkets: FAQs for Amazon.
:position: 10
:url: markets/amazon/faq/faq-collection
:id: 8WP3B0P
:author: team-multi-channel

plentymarkets is packed with functionalities for listing your products on Amazon. But with great power comes the odd error message. Below is a list of the FAQ, best practices and solutions we offer in the manual for selling your products on Amazon. If you can’t find what you’re looking for in the manual, our support team will be happy to help.

== FAQ on variation exports

* <<markets/amazon/best-practices-amazon-item-data-export#, Why is my item not exported to Amazon?>>
  ** <<markets/amazon/best-practices-amazon-item-data-export#100, How to find out if an item was not exported>>
  ** <<markets/amazon/best-practices-amazon-item-data-export#260, How to test if the item was exported>>

== FAQ for Amazon MFN

* <<markets/amazon/best-practices-amazon-mfn-order-import#, MFN orders are not imported>>.

== FAQ for invoice imports

* <<markets/amazon/amazon-setup#7010, Not all invoices for Amazon orders were uploaded to Amazon>>

== FAQ for price synchronisations

* <<markets/amazon/preparing-variations#67001, Which settings do I have to activate so that prices are exported to Amazon?>>

== FAQ for stock synchronisations

* <<markets/amazon/preparing-variations#67002, Which settings do I have to activate so that stock is exported to Amazon?>>


== Frequent error messages

[[amazon-faq-error-messages]]
.Frequent error messages
[cols="1,1"]
|====
|Error message |Link to solution

a| * Error:TermsAndConditionsNotAccepted, Type: Sender
* Error:InvalidRequest, Type: Sender
* Error:ShipmentAlreadyExists, Type: Sender
* Error:no AmazonPrime Service selected
* Error:ShippingServiceNotAvailable, Type: Sender
* Error:ResourceNotFound, Type: Sender
* No Valid Warehouse Address
| <<markets/amazon/best-practices-amazon-prime#200, Amazon Prime: Errors and how to solve them>>

a| * Error:Access to Reports. (GetReportScheduleList) is denied
* ERROR: AuthToken is not valid for SellerId and AWSAccountId
* Access denied.
* The seller does not have an eligible Amazon account to call Amazon MWS
| <<markets/amazon/best-practices-amazon-mfn-order-import#, MFN orders are not imported>>.

a| * Request is throttled
| <<markets/amazon/best-practices-amazon-error-request-throttled#, Error: Request is throttled>>
|====

== List of best practices

* <<markets/amazon/best-practices-amazon-vcs: Using Amazon’s VAT calculation service VCS>>
* <<markets/amazon/best-practices-amazon-prime#, Best Practice: Amazon Prime>>
    ** <<markets/amazon/best-practices-amazon-prime#100, How are Prime orders processed in plentymarkets?>>
    ** <<markets/amazon/best-practices-amazon-prime#200, Amazon Prime: Errors and how to solve them>>
