= idealo: Changing to the catalogue export
:author: team-plenty-channel
:keywords: idealo, idialo, idealo price portal, idealo price comparison, idealo catalogue, idealo catalogue export, idealo catalogue setup
:description: Learn how to switch from the old item export to the catalogue export for idealo.

:market: idealo
:idealo:
:catalogue:

You already list your items on idealo and want to switch to the catalogue export? Here are some recommendations for the switch to the catalogue.

[IMPORTANT]
.Haven’t worked with catalogues yet?
====
Is this your first time working with catalogues? Then read up on the xref:data:managing-catalogues.adoc#[basic concept of catalogues first].
====

[#create-catalogue]
== Creating catalogues

Use the template *idealo* to create a catalogue.

xref:page$idealo-setup.adoc#catalogue-export[How?]

[#check-data-fields]
== Check the marketplace data fields

Take a look at the catalogue to find out whether you need to create additional properties. Scroll through the catalogue and check the data fields for idealo. Can all data fields that should be transferred to idealo be assigned in the catalogue?

If not, create additional properties to map the data fields.

→ *_Tip:_* Check the xref:page$idealo-setup.adoc#recommended-mappings[recommended data field mappings] for idealo to see for which data fields properties should be mapped.

* Is this your first time working with properties? Then read up on the xref:item:properties.adoc#500[principles of properties first].

[#map-data-fields]
== Mapping data fields in the catalogue

You created a catalogue and properties, if required. Great. Now, assign the marketplace data fields to the appropriate plentymarkets data fields.

xref:page$idealo-setup.adoc#data-field-mappings[How?]

[#link-category]
== Linking variations with the idealo category

:category-property-name: idealo category group

include::partial$catalogue-link-property-for-market-category.adoc[]

[#additional-properties]
== Linking variations with additional properties

Now, link your variations with additional properties that you need for idealo. As described above, you have to at least export the mandatory fields to idealo.

[#activate-catalogue]
== Activating the catalogue

:interval: once a day
:market: idealo

include::partial$catalogue-activation.adoc[]