= OTTO OAuth
:keywords: OTTO Market, OTTO OAuth, OTTO
:description: On this page you learn how to activate the OTTO OAuth.
:author: team-plenty-channel

The OTTO OAuth gives your system access to the OTTO REST-API. This way, your system can transfer data to OTTO in specific intervals. xref:otto-market.adoc#100[Here] you can read up on which data is transmitted in which intervals. You activate the OTTO OAuth in the *Base settings - OTTO Market* assistant. After activation, your system automatically receives the necessary authentication data. +

Unlike before, you now do not have to manage any additional login details for the OTTO REST API yourself, which also eliminates the loss or change of login details.

[.instruction]
[TIP]
.Necessary rights in the OTTO market portal OPC
====
Note, that only OTTO Market users with admin rights can configure the OAuth. Users also need the *Dienstleister Freigaben* permission in the OTTO Market Portal *OPC*.
====

[WARNING]
.OTTO OAuth deadline
====
The activation of OTTO OAuth is mandatory. You have time until 31st March 2024 to switch to OTTO OAuth.
====

== Activating OTTO OAuth

Proceed as follows to activate the OTTO-OAuth in your system:

. Go to *Setup » Assistants » Omni-Channel*.
. Click on the assistant *Base settings - OTTO Market*.
. Click on the second point *Allow access to OTTO*.
. Click on *Allow Access* to give plentysystems access to OTTO Market. +
→ You are redirected to OTTO Markets.
. Here, you have to enter your login details of your vendor account, to login to OTTO Market. +
→ The data that plentysystems will get access to are displayed.
. Click on *Confirm* to complete the authorization. +
*Note*: In this step you will give plentysystems access to OTTO. For that a plentysystems app is created in your OTTO system. Then, authentication tokens for data exchange are frequently created.
. Click on *Summary* within the assistant.
. Click on *Finalise* to save your changes.

After you successfully authorised OTTO Market and created a plentysystems app, the note "authorization completed" is shown in the assistant step *Allow access to OTTO*.

More information about what to do in the OTTO menus yo will find link:https://account.otto.market/s/article/Als-Haendler-die-App-eines-Dienstleisters-nutzen[here^].

[TIP]
.Removing the data exchange
====
To remove the data exchange of the OAuth you have to remove the plentysystems app in the Dienstleister tab in the OTTO Market Portal *OPC*. User need the *Dienstleister-Freigaben* permission to see and edit apps.  
Hover with your mouse on name of *plentysystems* app and click on *Zugriff entziehen* Confirm the removal and the OAuth workflow is deactivated.
====