= Amazon: Setting up old variation export
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Amazon, Export Amazon, Amazon Export, exporting item data to Amazon, exporting variation data to Amazon
:description: Multi-Channel in plentymarkets: Export your variation data to the market Amazon.
:position: 10
:url: markets/amazon/variation-export-old
:id: 0ZI4W16
:author: team-multi-channel

[.previous-next-navigation]
<<markets/amazon/preparing-variations#, icon:long-arrow-left[] Preparing variations>>
<<markets/amazon/amazon-fulfilment/fulfilment#, Setting up fulfilment icon:long-arrow-right[]>>

'''

This page shows you how to set up and start the export of variations if you do not want to use the new catalogues.

* Have you set up Amazon in plentymarkets? (<<markets/amazon/amazon-setup#, How?>>)
* Have you prepared your variations? (<<markets/amazon/preparing-variations#, How?>>)
* Have you decided not to use the <<markets/amazon/variation-data-export#, catalogue export>>?

Then let’s get started with activating the export of your variations to Amazon.

[#1000]
== Activating the export

Either activate the export in the assistant *Basic settings - Amazon* or in the Setup menu.

[.tabs]
====
In the assistant::
+
--

Carry out the following settings in the assistant *Basic settings - Amazon* to activate the export.

[.instruction]
Activating the export in the assistant Basic settings - Amazon:

. Go to *Setup » Assistants » Omni-Channel*.
. Click on *Base settings - Amazon*.
. Open the assistant for the Amazon account. +
→ The assistant opens.
. Carry out the settings as described in <<#assistant-base-settings>>.
. Complete the assistant.

[[assistant-base-settings]]
.Settings for item export in the assistant
[cols="1,3"]
|======
|Setting |Explanation

2+| Step *Basic settings*

| *Select the Amazon platforms that you would like to sell your items on.*
| Activate the platforms.

2+| Step *Activate Amazon user account*

| *Activate user account*
| Activate the Amazon user account.

2+| Step *Automatic data transfer*

| *Select the Amazon platforms that your item data should be transferred to.*
| Activate the variation export for the Amazon platform. +
*_Note:_* The step *Automatic data transfer* is only visible after you activate the option *Show extended settings* in the step *Marketplace setup*.
|======

--

In the Setup menu::
+
--

Carry out the following settings in the *Setting » Markets » Amazon* menu to activate the export.

[.instruction]
Settings in the Setup menu:

. Go to *Setup » Markets » Amazon » Settings*.
. Select the Amazon account.
. Carry out the settings described in <<#export-menu>>.
. Save (icon:save[set=plenty]) the settings.

[[export-menu]]
.Export settings in the menu
[cols="1,3"]
|======
|Setting |Explanation

2+| Tab *Settings*

| *Active*
| In the *Access data* area, place a check mark for the option *Active*.

2+| Tab *Item settings*

| *Item export*
| From the drop-down list, select the option *Daily*.

| *Export categories*; +
*BMVD export categories*
| Activate the flatfiles.
|======

--
====

[#1600]
== Manually exporting variation data

In the *Setup » Markets » Amazon » Data exchange » Data export* menu, two data exports can be generated. On the one hand, the data export Seller Central which contains all relevant information about your items and stock and which can then be uploaded directly into Seller Central. On the other hand, the data export Marketplace which you can use to export item data for the BMVD categories on Amazon.

[#1700]
=== Exporting data for Seller Central

Use the *Seller Central* area of the *Setup » Markets » Amazon » Data exchange » Data export* menu to manually generate a data export that contains all relevant information about items and stock and that can be uploaded directly to Amazon Seller Central. To do so, proceed as described below.

[IMPORTANT]
.Listing items in several categories
====
If you wish to offer items in several categories, you have to generate the different catalogues as export files one after the other.
====

[.instruction]
Exporting data for Seller Central:

. Go to *Setup » Markets » Amazon » Data exchange » Data export*.
. Carry out the settings in the *Seller Central* area. Pay attention to the explanations given in <<#data-export-seller-central>>.
. Click on *Load file* to export the data. +
→ The data export is in CSV format.
. *Save* the CSV file on your computer so that you can use it later.

[[data-export-seller-central]]
.Data export Seller Central
[cols="1,3a"]
|====
| Setting | Explanation

| *Amazon account*
| Select the Amazon account.

| *Export the item catalogue*
| Select the item catalogue for the export. When exporting the item catalogue to Amazon, only those items are taken into consideration that were edited during the last 24 hours. Stock and prices will continue to be synchronised automatically.

| *Tag IDs*
|Enter one or more tag IDs. Separate multiple IDs using commas. Only items are exported that are linked to at least one of the selected tags.


| *Items with flags only*
| Select which items should be exported: *all items*, *all items with flags*, *all items without flags* or only items with a specific flag.

| *Number of variations*
| Enter the number of variations that should be exported. The more variations are exported, the longer the export will take. You can export a maximum of 5,000 variations at once. +
*_Example:_* If you have 20,000 Amazon variations and want to export all of them, then enter 1-5000 in the *from* and *to* fields (without commas or full stops). The first 5,000 Amazon variations will then be exported. Next, enter 5000-10000, then enter 10000-15000 etc. +
*_Note:_* Even if only a maximum of 5,000 variations can be exported at once, an export file might include more than 5,000 data sets. This is because the parents of variations are also included in the export file.

| *Date (from)*
a| Enter a date. +

* *New:* = Newly listed items are only exported starting from this date. +
* *Changed:* = Changed or updated items are exported.

| *Manufacturer*
| Select *ALL* or a specific manufacturer.
|====

[#1800]
=== Exporting data for Marketplace

Go to the area *Marketplace* of the *Setup » Markets » Amazon » Data exchange » Data export* to export item data of BMVD categories to exchange with Amazon. To do so, proceed as described below.

[.instruction]
Exporting data for Marketplace:

. Go to *Setup » Markets » Amazon » Data exchange » Data export*.
. Pay attention to the explanations given in <<#data-export-marketplace>> and carry out the settings in the *Marketplace* area.
. Click on *Load file* to export the data. +
→ The data export is in CSV format.
. *Save* the CSV file on your computer so that you can use it later.

[[data-export-marketplace]]
.Data export Marketplace
[cols="1,3a"]
|====
| Setting | Explanation

| *Amazon account*
| Select the Amazon account.

| *Genre*
| Select one of the following BMVD categories: *Books*, *Music*, *Video* or *DVD*.

| *Items with flags only*
| Select which items should be exported: *all items*, *all items with flags*, *all items without flags* or only items with a specific flag.

| *Procedure*
a| Select the procedure for the export. +

* *Update/add item* = The data transmitted in the CSV file is added/updated on Amazon. +
* *Remove offers* = The offers transmitted in the CSV file are removed from Amazon. +
* *Delete data completely from the system* = The data transmitted in the CSV file is completely deleted from Amazon.

| *Delivery*
| Select the shipping method.
|====

[IMPORTANT]
.Uploading a stock file to Seller Central
====
When uploading BMVD product data to Seller Central, select the option *Inventory loader file* instead of the option *Inventory files for non-media categories*.
====

== FAQ

[.collapseBox]
.One or more items were not exported. What can I do?
--
Our <<markets/amazon/best-practices-amazon-item-data-export#, Best practice: Item data export>> provides a check list to help you find out why an item was not exported to Amazon.
--

== Next steps

You have set up the interface to Amazon and have prepared your variations and the export. What to do next depends on the additional Amazon services that you want to use:

If you want to use the FBA service by Amazon:

* <<markets/amazon/amazon-fba#, Using the FBA service by Amazon>>

If you want to use additional Amazon services:

* <<markets/amazon/amazon-gift-service#, Using the Amazon gift service>>
* <<markets/amazon/amazon-business#, Setting up Amazon Business>>
* <<markets/amazon/amazon-pay#, Setting up Amazon Pay>>
* <<markets/amazon/AmazonVCSDashboard#, Using the AmazonVCSDashboard plugin>>

If something went wrong:

* <<markets/amazon/faq/faq-collection#, List of FAQs and solutions>>

'''

[.previous-next-navigation]
<<markets/amazon/preparing-variations#, icon:long-arrow-left[] Preparing variations>>
<<markets/amazon/amazon-fba#, Using the FBA service by Amazon icon:long-arrow-right[]>>
