= Zalando
:author: team-plenty-channel
:keywords: Zalando, Zalando, zalando.de, zalando.de, salando, zalando.com
:description: Learn how to set up the market Zalando in plentymarkets to start selling your items on Zalando.

:ea-queue:
:market: Zalando
:zalando:

Thanks to the Zalando partner programme, online sellers and manufacturers can use Zalando as an additional distribution channel for selling their high-quality products and take advantage of the well-known brand name Zalando.

//tag::zalando-countries[]
Which countries you can sell in with Zalando depends on your contract with Zalando. You can import orders from the following countries into plentymarkets:

*_Important:_* plentymarkets only supports own shipping by sellers. Zalando calls this *Partner Fulfillment (own logistics)*. Shipping by Zalando, also called Zalando Fulfillment Solutions (ZFS), is not supported yet.

* Germany
* Belgium
* Estonia
* Finland
* France
* Ireland
* Latvia
* Lithuania
* Netherlands
* Austria
* Portugal
* Slovakia
* Slovenia
//end::zalando-countries[]

[#200]
== Frequency of data exchange

Connecting to this market allows for the following automatic functions to take place:

[[data-exchange]]
[cols="1,1"]
|===
|Data |Interval

| Item export
| Once a day +
plentymarkets generates an XML file with the item data once daily during the night. This file is called *artikel.xml*. Zalando usually retrieves this XML once per day.

| Stock synchronisation
| Every 15 minutes, asynchronous +
Stock for 1,000 variations is updated per minute. If the API limit set by Zalando is reached, the remaining stock details are sent once the API is unlocked after one minute.

| Price synchronisation
| Every 15 minutes

| Order import
| Every 5 minutes
|===

[#100]
== Registering with Zalando

Do you want to join the Zalando partner programme? Then link:https://www.zalando.co.uk/partner-programme/[contact Zalando directly^].

[#150]
== Overview of the necessary steps

There are two ways to proceed. This depends on if you set up Zalando for the first time or already sell on Zalando and want to sell on another Zalando platform.

[tabs]
====
Steps after registration::
+
--
You have signed a contract with Zalando. Great. What happens now?

This is a list of the steps you are going to take.

. <<#api-user, Create a REST API account>>.
<<#setup, Carry out the basic settings in the *Setup » Markets » bol.com » Settings* menu.>>
. <<#zalando-csv-form, Request the CSV form for matching items/silhouettes in the plentymarkets forum.>>
  ** Enter your user credentials in the CSV file.
  ** Send this form to your Zalando contact person.
. YY#1400, Complete the assistant *Account settings - Zalando* for the first time.>> +
*_Important:_* When you complete the assistant for the first time, you cannot carry out all the settings of the assistant.
. <<#link-zDirect, Ask our supporters to link your account with your zDirect account.>> +
*_Important:_* This is only possible after you have completed the assistant for the first time.
. <<#assistant-2, Complete the assistant *Account settings - Zalando* again to complete the remaining settings.>>
. <<#more-setup, Carry out the additional settings.>>
. <<#order-documents, Prepare the order documents.>>
. <<#prepare-variations, Prepare your variations.>>
. <<#1200-1, Automate the order processing.>>
. <<#1500, Activate your Zalando account in the assistant to start exchanging data with Zalando.>>
--
 
Steps for adding more sales channels::
+
--
You already sell on Zalando and now want to offer your products on another country platform? No problem.

As soon as you signed a contract with Zalando for the additional sales channels, the process continues with the following steps:

. In the plentymarkets forum, request the link:https://forum.plentymarkets.com/t/sammelthema-collective-thread-csv-formular-zum-abgleichen-von-artikeln-silhouetten-csv-form-for-synchronization-of-articles-silhouettes/669460[API route for the new sales channel]. +
*_Important:_* User and password are the same for all Zalando sales channels. As such, Zalando only needs the API route.
. You send the new API route to your Zalando contact with the additional information that all other data is to be sourced from the first sales channel. +
→ Zalando activates the new sales channel.
. Go to *Setup » Orders » Order referrer* and activate the order referrer for the new country.
. Create a new sales price. Remember to correctly save the *currency* and the *country*. Or activate the referrer *Zalando* in an existing sales price for the country. +
*_Important:_* Activate the referrer *Zalando*. The sub-referrers for each Zalando platform (Zalando DE, Zalando NL etc.) will be ignored.
. Prepare the order documents for the country.
. Activate the sales price for the variations. +
*_Important:_* In the variation settings, the sub-referrers for each Zalando platform (Zalando DE, Zalando NL etc.) will be ignored. That is why you do not change the availability settings.
. <<#assistant-2, Complete the assistant to activate the country and to save the settings for prices and stock.>>
--
====


[#setup]
== Carrying out account and country settings

As soon as Zalando has accepted you into their partner programme, you will receive a user guide from Zalando which helps you setting up the interface. In plentymarkets, carry out the basic settings described here.

[#api-user]
=== Creating REST API access

Now, create a REST API account.

[.instruction]
Creating REST API access:

. Go to *Setup » Settings » User » Accounts*.
. Click on *New*. +
→ The *Create new user* window opens.
. Enter a *user name*.
. Enter the *real name* into the field.
. Enter a *password*.
. Repeat the password.
. For the setting *Access*, select the option *REST API*.
. *Save* the settings. +
→ The account is created. +
*_Tip:_* You do not need to grant any rights for this account. It is enough that the account exists in the system.

[#base-settings]
=== Carrying out the basic settings

[.instruction]
Carrying out the basic settings:

. Go to *Setup » Markets » Zalando » Settings*. +
→ The *Settings* tab opens.
. Carry out the settings as described in <<#basic-settings-zalando>>.
. Save (terra:save[]) the settings.

[[basic-settings-zalando]]
.Basic settings for the market Zalando
[cols="1,3a"]
|===
|Setting |Explanation

2+^|Basic configuration

| *User*
| Select the API account that you <<#api-user, created for Zalando>>.

| *Item name*
| Select *Name 1*, *Name 2*, or *Name 3*. The name you select will be exported to Zalando.

2+^|Advanced options

| *Standard tax rate*
| Select *19%* or *7%*.

| *Reduced tax rate*
| Select *19%* or *7%*.
|===

[#zalando-csv-form]
=== Request the CSV form for matching items/silhouettes

Now, request the FTP credentials and API data in the plentymarkets forum. Zalando needs this data to set up a sales channel for you.

. Contact our support team in the forum thread link:https://forum.plentymarkets.com/t/sammelthread-anfrage-des-csv-formulars-zum-abgleich-der-artikel-silhouetten/669460[Request CSV form for matching items and silhouettes^]. +
→ Our support team will provide you with a CSV file that contains a form. This file contains the following information:
  * Routes for items
  * Login details for the plentymarkets FTP server for silhouettes +
  *_Tip:_* Zalando sends your silhouettes to this FTP server for import into your system. plentymarkets imports these silhouettes every Wednesday.
. In row 5 of the file, enter the user name that you selected in the menu *Setup » Markets » Zalando » Settings*.
. In row 6 of the file, enter the password that you set in the menu *Setup » Markets » Zalando » Settings*.
. Forward the completed form to your Zalando contact. +
→ Zalando activates the sales channel for you.

[#1400]
=== Assistant part 1: account settings

Now, save details of your Zalando account in the assistant *Account settings - Zalando*

*_Important:_* You need to complete the assistant two times. Only part 1 is described here.

:menu-path: pass:quotes[*Setup » Assistants » Omni-Channel*]
:assistant-name: Account settings - Zalando
:number-of-boxes: info boxes

include::partial$assistant-basic-instructions.adoc[]

[.collapseBox]
.Step *Orders*
--

[[table-assistant-zalando-orders]]
[cols="1,3a"]
|===
|Setting |Explanation

| *Would you like to import your Zalando orders into plentymarkets?*
| Activate to automatically import orders every five minutes. +
*_Note:_* You need to activate this option to export item data and stock information to Zalando.

| *From which countries do you want to import orders?*
| _When you complete the assistant for the first time, you cannot select any countries yet._

| *Select an environment for the order import.*
a| Select if real or test data is to be imported.

* *Sandbox* = Test data is imported from Zalando.
* *Productive* = Real orders are imported from Zalando.

| *Select the client that should be used to sell your items.*
|Select a client (store). Zalando orders will be assigned to this client.

| *Do you also want to import reservations?*
|tems are considered reserved if a customer has placed an order which has either not been paid for or has not been released for shipping by Zalando. +
If this option is activated, reservations will be imported into plentymarkets with the status *[3] Waiting for payment*. +
If Zalando confirms the payment of the order and it changes to the status *approved* on Zalando, the order changes to status *[5] Cleared for shipping* in plentymarkets. As soon as an order is moved into status *[5]*, it can be shipped. +
*_Note:_* Orders can only be shipped in status *[5] Cleared for shipping*. An order which is still in status *[3] Waiting for payment* must not be shipped.

|*What order status do you want to assign to reservations?*
|Reservations are imported with status *[3] Waiting for payment* by default and have to be moved into another status *[8.X]* after they were cancelled by the customer or by Zalando. In this step, you decide which status cancelled reservations should be moved to. +
*_Note:_* Select a status that does not trigger an event procedure to Zalando as a result of the status change. Any orders that customers cancel before the import of reservations is started are not imported.

| *Map plentymarkets reason for return with*
a|From the drop-down list, select a Zalando return reason for each return reason saved in plentymarkets. The return reasons are only transmitted for the order type *Return* and if they are saved in the order items of the return.

Zalando currently has the following reasons for return:

* *Unknown reason*
* *Do not like the item*
* *Too big*
* *Too small*
* *Bad value for money*
* *Not delivered on time*
* *Item not as expected*
* *Wrong item sent*
* *Item defective*

*_Note:_* Sending reasons of return to Zalando is optional. However, Zalando recommends that you send a reason.
|===
--

[.collapseBox]
.Step *Stock*
--

_When you complete the assistant for the first time, you cannot carry out any settings in this step._
--

[.collapseBox]
.Step *Prices*
--
_When you complete the assistant for the first time, you cannot carry out any settings in this step._
--

[.collapseBox]
.Step *Account activation*
--

_When you complete the assistant for the first time, you cannot carry out any settings in this step._
--

[#link-zDirect]
=== Linking account with zDirect account

You have completed the assistant for the first time. Ask our support staff to activate your account: link:https://forum.plentymarkets.com/t/sammelthema-aktivierung-neuer-zalando-konten/600409[Open this forum thread. Ask our supporters to activate your account.]

In the forum post, provide the following information:

* The company/brand name you used to register with Zalando
* Your plenty ID
* The ID of the Zalando account (accountId) in plentymarkets that you want to activate for the Zalando interface +
*_Note:_* Only one account can be linked in plentymarkets for each Zalando seller account.

[#assistant-2]
=== Assistant part 2: country settings

The plentymarkets support linked your account to your zDirect account? Great. Then you are ready for the next step.

:menu-path: pass:quotes[*Setup » Assistants » Omni-Channel*]
:assistant-name: Account settings - Zalando
:number-of-boxes: info boxes

include::partial$assistant-basic-instructions.adoc[]

[.collapseBox]
.Step *Orders*
--

[[assistant-zalando-orders]]
[cols="1,3a"]
|===
|Setting |Explanation

| *From which countries do you want to import orders?*
| include::page$zalando.adoc[tag=zalando-countries]

*_Cannot select any countries?_* Then your account has not been linked to the zDirect account yet. (<<#link-zDirect, What do I need to do?>>)
|===
--

[.collapseBox]
.Steps *Stock*
--

For each country that you select in the step *Orders*, a separate step *Stock* is added to the assistant. The settings are the same for all countries:

[[assistant-zalando-stock]]
[cols="1,3a"]
|===
|Setting |Explanation

| *Do you want to export stock information to Zalando?*
| *Activate stock export* = Activate option to export your stock to Zalando every 15 minutes.

| *To which Zalando interface environment do you want to export stock information?*
a| Select if real or test data is to be exported.

* *Sandbox* = Test data is exported to Zalando.
* *Productive* = Real stock data is exported to Zalando.

| *From which sales warehouses do you want to export stock information to Zalando?*
a| Select one or more sales warehouses. The totalled net stock of these sales warehouses is exported. +
*_Tip:_* You can also select a *Stock buffer* in this step of the assistant. The totalled net stock of the sales warehouses you selected is then reduced by the quantity you entered as the stock buffer.

| *How much stock should be exported at maximum?*
a| If a variation has a higher stock, the value you entered in the *Maximum stock* field will be exported instead.

| *Which stock buffer should be deducted from the exported stock?*
a| The quantity you enter in the * Stock buffer*field is deducted from the net stock of each variation before export.

| *How much stock should be exported for variations without limitation to net stock that have no positive net stock?*
a| In the field *Stock without stock limitation*, enter the stock to be exported for variations that have no positive net stock. Variations that have no positive net stock are variations with the setting *Tab: Settings, Setting: Limitation, Option: None* that have no positive net stock.

| *How much stock should be exported for variations without stock administration?*
a| In the field *Stock without stock administration*, enter the stock to be exported for variations for which no stock is administered. Variations for which no stock is administered are variations with the setting *Tab: Settings, Dropdown list: Limitation, Option: Do not administer stock for this variation*. The entered value is exported for these variations.

|===
--

[.collapseBox]
.Steps *Prices*
--

For each country that you select in the step *Orders*, a separate step *Prices* is added to the assistant. The settings are the same for all countries:

[[assistant-zalando-prices]]
[cols="1,3a"]
|===
|Setting |Explanation

| *Do you want to export prices to Zalando?*
| *Activate price update* = Activate option to export your prices to Zalando every 15 minutes. +
*_Tip:_* The price reports contain information on the status of price updates.

<<#915, How to download price reports>>

| *To which interface environment should prices be exported?*
a| Select if real or test data is to be exported.

* *Sandbox* = Test data is exported to Zalando.
* *Productive* = Real price data is exported to Zalando.

| *Should warnings by Zalando for price updates be ignored?*
a| During price updates, Zalando checks the plausibility of your prices based on specific criteria. For example, Zalando compares the prices of the same variations on different platforms and compares the regular price with the reduced price. If any significant differences are detected, Zalando triggers a warning. Select if such warnings should be ignored when prices are updated.

* icon:toggle-on[role="green"] = The new prices are published even if Zalando sends a warning.
* icon:toggle-off[role="darkGrey"] (default setting) = Zalando rejects new prices if they do not pass the plausibility checks. +
*_Tip:_* Check the *Data » Log* menu and the price reports for warnings.

| *Which sales price should be exported as the regular price for Zalando?*
| Select the sales price from the drop-down list that you want to export to Zalando as the *Regular price*. You can select from sales prices of the types *Default* or *RRP* for which the referrer Zalando, the country and the currency of the country are activated. +
*_Note:_* If you specify a *reduced price* for a variation, the *regular price* is exported to Zalando as the strikethrough price.

|*Which sales price should be exported as the reduced price for Zalando?*
|Select the sales price from the drop-down list that you want to export to Zalando as the *Reduced price*. You can select from sales prices of the types *Offer price* or *Default* for which the referrer Zalando, the country and the currency of the country are activated. +
*_Note:_* If you specify a *reduced price* for a variation, the *regular price* is exported to Zalando as the strikethrough price.

| *Use scheduled prices to announce any temporary or permanent price changes to Zalando ahead of time.*
a|
Define up to three scheduled prices. Scheduled prices ensure that Zalando really changes your prices at the specified time. To export scheduled prices to Zalando, you need at least a sales price for the regular price and a property that contains the start date and time for the new price. The start date for scheduled prices must be in the future. You can also select a property for an end date for a scheduled price.

* *Property for start date* = Select the property from the drop-down list that you use to manage the start time for your variations. You can only select properties of the types *Date* or *Text*. +
*_Note:_* The start times of more than one scheduled prices must be separated by at least 60 minutes.
* *Property for end date* (optional) = Select the property from the drop-down list that you use to manage the end time for your variations. You can only select properties of the types *Date* or *Text*.
* *Select price* = Select the sales price from the drop-down list that you want to export to Zalando as the *Scheduled price*.

|===
--

[.collapseBox]
.Step *Account activation*
--
*Would you like to activate your Zalando account now?*

You have not completed the setup. As such, do not activate the Zalando account yet.
--

[#more-setup]
== Continuing the setup

[#400]
=== Linking categories

Link your plentymarkets categories to the Zalando categories in order to display your variations in these categories.

[.instruction]
Linking categories:

. Go to *Setup » Markets » Zalando » Category link*. +
→ A list of your categories is shown in the column *Category*. +
→ In the column *Zalando category*, you can link a Zalando category to each of your plentymarkets categories.
. In the column *Zalando category*, select a Zalando category from the drop-down list for all categories that you need.
. Save (terra:save[]) the settings. +
→ The categories are linked to the selected Zalando categories. +
→ New variations that you create for the plentymarkets category are also assigned to the linked Zalando category.

[#250]
=== Activating an order referrer

:market: Zalando
:referrer: Zalando
:referrer-option: pass:quotes[Zalando platforms, for example *Zalando DE*]

include::partial$activate-referrer.adoc[]


[.collapseBox]
.List of referrer IDs
--
118 = Zalando +
118.01 = Zalando DE +
118.02 = Zalando NL +
118.03 = Zalando FR +
118.04 = Zalando IT +
118.05 = Zalando UK +
118.06 = Zalando AT +
118.07 = Zalando CH +
118.08 = Zalando PL +
118.09 = Zalando BE +
118.1 = Zalando SE +
118.11 = Zalando FI +
118.12 = Zalando DK +
118.13 = Zalando ES +
118.14 = Zalando NO +
118.15 = Zalando CZ +
118.16 = Zalando IE +
118.17 = Zalando PT +
118.18 = Zalando SK +
118.19 = Zalando SI +
118.2 = Zalando LT +
118.21 = Zalando LV +
118.22 = Zalando EE +
118.23 = Zalando HR +
--

[#350]
=== Defining a sales price

:referrer-price: Zalando

include::partial$define-sales-price.adoc[]

[#700]
=== Linking attributes to Zalando

If you have created attributes in your plentymarkets system, you need to link these attributes with Zalando. The following example describes how you can link the attribute “colour” with Zalando. Link further attributes in the same way.

Link at least the following attributes to export your variations to Zalando:

* Größe (size register)

_and/or_

* A colour for the 1st Farbcode (colour code)/Herstellerfarbe (manufacturer colour)

_and/or_

* Länge (length register) for length information (e.g. skirt length)

NOTE: You can only link one size register or one length register to each attribute.

:attribute-option: Zalando
:attribute: Colour
:attribute-dropdown:
:select-attribute-values:
:attribute-example: pass:quotes[*_Example:_* For the colour Purple, from the first drop-down list select the option *dark purple* and from the second drop-down list select the option *Purple*.]

include::partial$link-attributes.adoc[]

[#500]
=== Converting silhouettes to characteristics

Zalando groups products into "silhouettes". Zalando also calls these silhouettes "article types". For example, "skirts", "dresses", and "trousers" are all silhouettes. In the *Setup » Markets » Zalando » Settings » Tab: Silhouettes* menu, you convert Zalando silhouettes to item characteristics. Silhouettes are imported into plentymarkets when Zalando is first set up. When Zalando publishes new silhouettes, plentymarkets updates these silhouettes on the following Wednesday. After that, you can convert new silhouettes into characteristics if necessary.

[.instruction]
Converting silhouettes to characteristics:

. Go to *Setup » Markets » Zalando » Settings*.
. Click on the *Silhouettes* tab.
. Select the *Groups* for the characteristics that you want to convert. +
*_Note:_* No groups? Either Zalando has not provided the silhouettes or you have not sent the FTP credentials to Zalando (see <<#zalando-csv-form, Requesting the CSV form for matching items/silhouettes>>).
. Save (terra:save[]) the settings. +
→ Characteristics are created in your plentymarkets system based on the silhouettes.

[#prepare-variations]
== Preparing variations

Continue with preparing your variations.

[#300]
=== Setting the variation availability

:market-availability: Zalando
:option-availability: Zalando
:web-api:

include::partial$variation-availability.adoc[]

// Web API required!

[#330]
=== _Optional:_ Saving SKU

:referrer-sku: Zalando
:referrer-id: 118
:sku-others:

include::partial$sku-manually.adoc[]

// Marketplace account not required!

[#600]
=== Linking characteristics to items

Link the Zalando characteristics with the items that you want to sell on Zalando.

Link at least the following mandatory characteristics to export your variations to Zalando:

* 1. Farbcode (colour code)
* Altersgruppe(n) (age group(s))
* Form of address (Geschlecht)
* Größenregister (size list)
* Hersteller-Code (manufacturer code)
* Manufacturer colour
* Jahreszeiten-Code (Seasonal code)
* Silhouetten-Typ (silhouette type)

[.collapseBox]
.*_Tip:_* Exporting a file with Zalando item characteristics
--
Several hundred characteristics are created in plentymarkets when you convert the Zalando silhouettes to characteristics. To make it easier to work with these characteristics, you can export the characteristics to a file. This gives you quick access to the IDs of your Zalando characteristics. This gives you easy access to the IDs of the Zalando characteristics. For example, this will help you to link the characteristics to your items xref:data:best-practices-elasticsync-property-links.adoc#import_property_links[using the import tool].

[.instruction]
Exporting Zalando item characteristics:

. Go to *Setup » Markets » Zalando » Settings*.
. Click on the *Silhouettes* tab.
. Click on *Export Zalando item characteristics*. +
→ A file that contains the Zalando characteristics is exported.
. Save the file on your computer.
*_Tip:_* <<#zalando-characteristics>> explains the file’s columns. For more information about characteristics, refer to the xref:item:properties.adoc#100[Characteristics and properties] page of the manual.

[[zalando-characteristics]]
.Zalando characteristics
[cols="1,3a"]
|===
|Column |Explanation

| *Group name*
|Names of the characteristic groups

| *Silhouette*
|Values of all silhouettes

| *Characteristic ID*
|IDs of the characteristics, see also *Setup » Items » Characteristics*

| *Characteristics type*
a|Characteristic type

* *empty* = No type +
* *text* = Text +
* *int* = Whole number +
* *selection* = Selection ID

| *Mandatory entry*
a|
*0* = The characteristic is optional.
*1* = The characteristic must be exported. Items that are not linked to this characteristic cannot be exported to Zalando. +
*_Note:_* Characteristics may also contain the value *1* because links to other selected characteristics exist. Observe the documentation provided by Zalando.

| *Language*
| The xref:data:internal-IDs.adoc#10[language] of the characteristic. Currently, only German is available.
|===
--

[.instruction]
Linking a characteristic to an item:

. Go to *Item » Edit item*.
. Open the item.
. Click on the *Characteristics* tab.
. Activate the characteristic in the *Activate further characteristics* area.
. Save (terra:save[]) the settings. +
→ The characteristics are displayed in the *Characteristics* area.
. *_Optional:_* Carry out additional settings. Pay attention to the explanations regarding xref:item:managing-items.adoc#80[characteristics].
. Save (terra:save[]) the settings.

[#1100]
=== Check list for exporting variations

Zalando expects some mandatory product information. As a result, variations can only be exported to the market if this mandatory information is saved for the variation. The information listed in <<#zalando-variations-mandatory>> must be saved for all variations that you want to export to Zalando.

[[zalando-variations-mandatory]]
.Mandatory fields for the variation
[cols="1,3a"]
|===
|Mandatory data |Explanation

| EAN
a| An EAN must be saved for the variation.

* In the *Setup » Item » Barcode* menu, an EAN must be created and linked to the referrer Zalando.
* The EAN must be added to the *Settings* tab of the variation in the *Barcode* area and a barcode code must be entered.

| Technical data
a| Technical data must be saved for the item.

* In the *Texts* tab of the item, text must be saved in the *Technical data* field.

| Images
a| An image must be saved for the variation.

* in the *Images* tab of the item, the option *Zalando* must be selected from the drop-down list *Availability*.

| Price
a| A price must be saved for the variation.

* The sales price must be activated for the referrer Zalando in the *Setup » Item » Sales prices*.
* The sales price must be added in the *Settings* tab in the *Sales price* area of the variation.
* A price must be saved for the sales price.

| Supplier SKU
a| An supplier SKU must be saved for each variation. Save this supplier SKU in the *Model* field of your variations.

| Properties
a| As a minimum, the following mandatory characteristics need to be linked to an item:

* 1. Farbcode (colour code)
* Altersgruppe(n) (age group(s))
* Form of address (Geschlecht)
* Größenregister (size list)
* Hersteller-Code (manufacturer code)
* Manufacturer colour
* Jahreszeiten-Code (Seasonal code)
* Silhouetten-Typ (silhouette type)

| Attributes
a| As a minimum, the following attributes must be linked to the variation:

* Größe (size register)

_and/or_

* A colour for the 1st Farbcode (colour code)/Herstellerfarbe (manufacturer colour)

_and/or_

* Länge (length register) for length information (e.g. skirt length)

NOTE: You can only link one size register or one length register to each attribute.
|===

[#removing-items]
== No longer offering items on Zalando

Variations cannot be sold on Zalando if they do not have stock in plentymarkets. As stock data is transferred to Zalando every 15 minutes, variations without stock are deleted automatically. If a variation has stock again in plentymarkets, it is offered again on Zalando with the next stock export.

If you do not want to sell a variation which is in stock in plentymarkets on Zalando, then you have to delete the availability for the market and update the timestamp for market exports.

*_Note:_* Items cannot be deleted on Zalando. Thus, if you remove the availability and update the timestamp for market exports, your variation will not be deleted on Zalando. It will only be displayed as not in stock.

[.instruction]
Deleting the availability:

. Go to *Item » Edit item » [Open item] » [Open variation] » Variation tab: Availability*.
. *Delete* (icon:minus-circle[role="red"]) the availability *Zalando*.
. *Save* (terra:save[]) the settings.

After you removed the availability, you have to *Update the timestamp for market exports* using the *Item group function*. This ensures that a stock of *0* is transferred to Zalando.

[.instruction]
Updating the timestamp for market exports:

. Go to *Item » Edit item » Tab: Item group function*.
. Place a check mark next to *Update timestamp for market exports*.
. Click on terra:execute[] *Execute*. +
→ A stock of *0* is transferred to Zalando. +
→ The variation is displayed as not in stock on Zalando and cannot be bought any longer.

[#order-documents]
== Preparing order documents

include::partial$zalando-order-documents.adoc[]

[#1200-1]
== Automating order processing

The following event procedures are available for automating order processing:

* Automatically send shipping confirmations (<<#1200, How?>>)
* Automatically sending cancellations (<<#1300, How?>>)
* Automatically sending returns (<<#1600, How?>>)

[#1200]
=== Automatically sending shipping confirmations

A shipping confirmation can only be sent if an order meets the following conditions:

* A package number must be saved for the order. +
*_Note:_* Only one package number can be exported per order. If more than one package number is associated with an order, only the first package number is exported.
* The tracking ID of the return label must be saved for the order.

[.collapseBox]
.*_Tip:_* How to save the tracking ID
--
You can save the tracking ID in several different ways:

* xref:fulfilment:shipping-centre.adoc#retrieve-return-label-main-order[Create a return label via the shipping centre.]
* xref:automation:procedures.adoc#380[Create a return label with a process procedure.]
* link:https://developers.plentymarkets.com/rest-doc#/Returns/put_rest_orders__orderId__shipping_returns_assign_label__returnsId_[Add the return label via REST.^]
* link:https://developers.plentymarkets.com/rest-doc#/Order/put_rest_orders__orderId__shipping_packages__orderShippingPackageId_[Add the tracking ID of the return to a package at the order via REST.^]
--

Set up an xref:automation:event-procedures.adoc#[event procedure] to automatically send shipping confirmations to Zalando when the outgoing items are booked.

:table-event-procedure: <<#event-procedure-shipping-confirmation-zalando>>

include::_includes:partial$event-procedure.adoc[]

[[event-procedure-shipping-confirmation-zalando]]
.Event procedure for automatically sending shipping confirmations to Zalando
[cols="1,3,3"]
|===
|Setting |Option |Selection

| *Event*
| *Order change: Outgoing items booked* +
*_Note:_* You can select a different event. However, ensure that the selected event is only triggered once the order contains all information necessary to send a shipping confirmation.
|

| *Filter 1*
| *Order > Order type*
| *Order*

| *Filter 2*
| *Order > Referrer*
| *Zalando*

| *Action*
| *Plugins > Send shipping confirmation to Zalando*
|
|===

[#1300]
=== Automatically sending cancellations

Set up an xref:automation:event-procedures.adoc#[event procedure] to automatically inform Zalando of cancellations. Note that orders marked as shipped can no longer be cancelled.

:table-event-procedure: <<#event-procedure-cancellations-zalando>>

include::_includes:partial$event-procedure.adoc[]

[[event-procedure-cancellations-zalando]]
.Event procedure for automatically sending cancellations to Zalando
[cols="1,3,3"]
|===
|Setting |Option |Selection

| *Event*
| *Order change: Status change* +
*_Note:_* You can select a different event. However, ensure that the selected event is not triggered for orders that are flagged as shipped or that are cancelled by customers.
| Select a status, for example *[8.0] Cancelled*

| *Filter 1*
| *Order > Order type*
| *Order*

| *Filter 2*
| *Order > Referrer*
| *Zalando*

| *Action*
| *Plugins > Send cancellation to Zalando*
|
|===

[#1600]
=== Automatically sending returns

Set up an xref:automation:event-procedures.adoc#[event procedure] to automatically inform Zalando about returns. Note that the order must be flagged as shipped.

IMPORTANT: Return reasons will only be transmitted if the event procedure is used in combination with a return order and if <<#1400, the return reasons were mapped in the assistant>>.

:table-event-procedure: <<#event-procedure-returns-zalando>>

include::_includes:partial$event-procedure.adoc[]

[[event-procedure-returns-zalando]]
.Event procedure for automatically sending returns to Zalando
[cols="1,3,3"]
|===
| Setting | Option | Selection

| *Event*
| *Order generation: New return* +
*_Note:_* You can select a different event. However, if you also want to communicate the return reason to Zalando, ensure that the return reasons are saved for the return.
|

| *Filter 1*
| *Order > Order type*
| *Return*

| *Filter 2*
| *Order > Referrer*
| *Zalando*

| *Action*
| *Plugins > Send return to Zalando*
|
|===

// include::partial$zalando-order-documents.adoc[]

[#1500]
== Starting data exchange: Activating the Zalando account

Have you completed all the settings? Great. Then you are ready for the next step.
Activate your Zalando account in the assistant *Account settings - Zalando* to start exchanging data with Zalando.

[.collapseBox]
.What to do if "This account cannot be activated."
--
Data is not exchanged with Zalando. To activate Zalando’s zDirect API interface, your Zalando account must be linked to the plentymarkets developer account. This link is established automatically during the integration. However, plentymarkets also needs to generate additional credentials for the API and then save these credentials in your system. We cannot give you access to these credentials. As such, plentymarkets is not allowed to give you access to these credentials. Ask our support staff to activate your account in link:https://forum.plentymarkets.com/t/sammelthema-aktivierung-neuer-zalando-konten/600409[this thread^] of the plentymarkets forum.

In the forum post, provide the following information:

* The company/brand name you used to register with Zalando
* Your plenty ID
* The ID of the Zalando account (accountId) in plentymarkets that you want to activate for the Zalando interface +
*_Note:_* Only one account can be linked in plentymarkets for each Zalando seller account.
--

[.instruction]
Activating the Zalando account:

. Go to *Setup » Assistants » Omni-Channel*.
. Click on the assistant *Account settings - Zalando*.
. Navigate to the step *Account activation*.
. Activate the option *Activate user account*.
. Complete the assistant. +
→ The data exchange with Zalando is activated.



[#900]
== Download reports

There are a number of reports available for Zalando. Go to the *Setup » Markets » Zalando » Settings » Tab: processing reports* menu to download the following reports:

[cols="1,3a"]
|===
|Report |Explanation

2+^| *Export-Log*

| *zalandoArticleExportLog.txt*
a| The export log *zalandoArticleExportLog.txt* contains log entries for variations. The export log is generated once every night. The file contains entries for variations that were exported successfully and for variations that could not be exported to Zalando.

<<#905, How to download the export log>>

2+^| *Reports*

| *Product status reports*
a| Zalando generates the product status reports are generated once daily during the night. These reports only contain information regarding variations that were successfully exported to Zalando.

[cols="1,3"]
!===
! *_ProductErrorReport.csv_*
! Contains variations that cannot be sold on Zalando since the last export. The report is generated once every night.

! *_ProductLiveReport.csv_*
! Contains variations that can be sold on Zalando since the last export as well as stock and price of each variation on the different Zalando channels (DE, FR, etc.) at the time that the file was generated. The report is generated once every night.
!===

<<#910, How to download product status reports>>

| *Price reports*
a| Zalando generates a price report for each active channel once daily during the night. These reports contain information on the processing status of all price updates that Zalando received in the last seven days.

<<#915, How to download price reports>>
|===

[#905]
=== Downloading the export log

The export log contains plentymarkets log entries. The file contains entries for variations that were exported successfully and for variations that could not be exported to Zalando.

[.instruction]
Downloading the export log:

. Go to *Setup » Markets » Zalando » Settings*.
. Click on the *Processing reports* tab.
. In the *Export log* area, click on *Download file* (icon:eye[role="blue"]). +
→ The CSV file is generated.
. Save the CSV file on your computer.
. Filter the entries to only see the status *error*.
. Check the entries. Correct any variation data in the plentymarkets back end. +
*_Tip:_* You can ignore any entries with the status *warning*.

[[zalando-errors]]
.Error messages in the export log (zalandoArticleExportLog.txt)
[cols="1,3a"]
|===
|Setting |Explanation


| specialDescriptions
| Technical data

| brand
| Characteristic *Zalando » Hersteller-Code* (manufacturer code)

| season
| Characteristic *Zalando » Jahreszeiten-Code* (season code)

| genders
| Characteristic *Zalando » Geschlecht* (gender)

| ageGroups
| Characteristic *Zalando » Altersgruppe(n)* (age groups)

| sizeRegister
| Characteristic *Zalando » Größen-Register* (size register)

| mainColorCode
| From the Characteristic *Zalando » 1. Farbcode* (Zalando » 1st colour code) +
*_Exception:_* The variation has a colour attribute. In that case, attribute links are used to manage colours.

| supplierColor
| Characteristic *Zalando » Hersteller-Farbe* (Zalando » Manufacturer colour) or an optional 2nd attribute link

| images
| The variation must have at least one image.

| ean
| The variation needs a GTIN 13.

| lengthRegister
| Characteristic *Zalando » Längen-Register* (length register)

| Keywords
| Meta keywords (item tab: Texts)
|===

[#910]
=== Downloading product status reports

Product status reports contain information regarding the items that were exported to Zalando. These reports are generated by Zalando. As such, these reports only contain information regarding variations that were successfully exported to Zalando. The following reports are available:

* *_ProductErrorReport.csv_*: Contains variations that cannot be sold on Zalando since the last export. The report also contains the first five error codes and an error description. The report is generated once every night. Click on *Update file* (icon:cog[]) before downloading the file to get current data from Zalando.
* *_ProductLiveReport.csv_*: Contains variations that can be sold on Zalando since the last export. The report also contains information on the stock and price of the variations on the different Zalando channels (DE, FR, etc.) at the time the file was generated. The report is generated once every night. Click on *Update file* (icon:cog[]) before downloading the file to get current data from Zalando.

[.instruction]
Downloading a product status report:

. Go to *Setup » Markets » Zalando » Settings*.
. Click on the *Processing reports* tab. +
→ The following files can be downloaded in the *Product status reports - Account ID* area:

  * *_ProductErrorReport.csv_* contains the variations that cannot be sold on Zalando since the last export.
  * *_ProductLiveReport.csv_* contains the variations that can be sold on Zalando since the last export.

. *_Optional:_* By default, the file is updated once every night. To get current data from Zalando before downloading the file, go to the *Product status-reports - Account ID* area and click on *Update file* (icon:cog[]).
. Go to the *Product status reports - Account ID* area. In the row of a processing report click on *Download file* (icon:eye[role="blue"]). +
→ The CSV file is generated.
. Save the CSV file on your computer.

[#915]
=== Downloading price reports

Zalando generates a price report for each active channel once daily during the night. These reports contain information on the processing status of all price updates that Zalando received in the last seven days. As such, the reports may contain several entries for the same EAN.

[.instruction]
Downloading price reports:

. Go to *Setup » Markets » Zalando » Settings*.
. Click on the *Processing reports* tab. +
→ In the area *Price reports*, files are available for all active channels.
. *_Optional:_* By default, the file is updated once every night. In the column *Actions*, click on *Update file* (icon:cog[]) to get current data from Zalando before downloading the file.
. Go to the *Price reports* area. In the row of a processing report, click on *Download file* (icon:eye[role="blue"]). +
→ The CSV file is generated.
. Save the CSV file on your computer.

[.collapseBox]
.What information do the price reports contain?
--
[cols="1,3"]
|===
| Timestamp
| Corresponds to the latest timestamp from the columns *Status History* and *Scheduled Price (1-3) - Status History*.

| EAN
| The EAN of the variation whose price has been updated.

| Ignore Warnings?
| Corresponds to the setting *Ignore Warnings* in the *Setup » Assistants » Omni-Channel » Zalando account settings » [Open account] » Step: Prices for [target country]* menu at the time the update was transferred.

| Regular Price
| Transferred value of the regular price.

| Regular Price Currency
| Transferred currency of the regular price.

| Promotional Price
| Transferred value of the reduced price.

| Promotional Price Currency
| Transferred currency of the reduced price.

| Status
a| Status of the processing. Possible statuses:

[cols="1,3"]
!===
! RECEIVED
! The price has been received.

! ACCEPTED
! The price has been accepted and forwarded for further validation.

! REJECTED
! The price has not passed validation. See the status messages in *Status History* for more information.

! FAILED
! An unexpected error occurred during the price update. See the status messages in *Status History* for more information.

! SCHEDULED
! The price has been successfully validated and is awaiting submission.

! SUBMITTED
! The price has been submitted and will be shown in the shop shortly.

! AWAITING_ONBOARDING
! The price has been accepted but the item has not yet been activated. The price will be applied once onboarding is complete.
!===

| Status History
a| Status change history. For each change, the cell contains a paragraph with the following pattern (placeholders in square brackets):

* [timestamp]: FROM [original status] TO [new status] - code: [code] [severity] [message]

| Scheduled Price (1-3) - Start
| Start date of the scheduled price.

| Scheduled Price (1-3) - End
| End date of the scheduled price.

| Scheduled Price (1-3) - Regular Price
| Transferred value of the regular price for the scheduled price.

| Scheduled Price (1-3) - Regular Price Currency
| Transferred currency of the regular price.

| Scheduled Price (1-3) - Promotional Price
| Transferred value of the reduced price.

| Scheduled Price (1-3) - Promotional Price Currency
| Transferred currency of the reduced price.

| Scheduled Price (1-3) - Status
a| Status of the processing of the scheduled price. Possible statuses:

[cols="1,3"]
!===
! RECEIVED
! The price has been received.

! ACCEPTED
! The price has been accepted and forwarded for further validation.

! REJECTED
! The price has not passed validation. See the status messages in *Scheduled Price (1-3) - Status History* for more information.

! FAILED
! An unexpected error occurred during the price update. See the status messages in *Scheduled Price (1-3) - Status History* for more information.

! SCHEDULED
! The price has been successfully validated and is awaiting submission.

! OVERRIDDEN
! The price was scheduled but overwritten by a new price update before it could be submitted.

! SUBMITTED
! The price has been submitted and will be shown in the shop shortly.

! AWAITING_ONBOARDING
! The price has been accepted but the item has not yet been activated. The price will be applied once onboarding is complete.
!===

| Scheduled Price (1-3) - Status History
a| History of the status change of the scheduled price. For each change, the cell contains a paragraph with the following pattern (placeholders in square brackets):

* [Timestamp] from [Original Status] to [New Status] - Code [code] Severity [severity] Message [message]
|===
--

[#1010]
== Viewing the data log

:market: Zalando
include::partial$viewing_logs.adoc[tag=data-log-intro]

* *Identifier* » *Zalando*

include::partial$viewing_logs.adoc[tag=data-log-config]

Use any filters listed in <<#table-reference-types>> to limit the search results.

[[table-reference-types]]
.Filters
[cols="1a,2a,2a"]
|===
|Log entries |Recommended filters |Explanation

| Price updates
| * Identifier » Zalando
* Level: Error
* References:
    ** Reference type » action +
    Reference value » PriceUpdate
    ** Reference type » ean +
    Reference value » EAN of variation
| While the <<#915, price reports>> are generated, an error log is also written for all entries that have been in the REJECTED, FAILED or OVERRIDDEN status since the file was last generated (minus one hour as a buffer).

| Price reports
| * Identifier » Zalando
* References:
  ** Reference type » action +
  Reference value » PriceReporting
| Log entries for errors during generation of price reports

| Stock synchronisation
| * Identifier » Zalando
* References:
  ** Reference type » action +
  Reference value » StockUpdate
  ** Reference type » variationId
  ** Reference type » ean
  ** Reference type » accountId
  ** Reference type » salesChannel
  ** Reference type » jobUniqueId
| Log entries for errors during stock updates

|===

[#zalando-faq]
== FAQ

include::partial$zalando-faq.adoc[]
