= Amazon einrichten
:keywords: Amazon, Amazon einrichten, FBA, Amazon FBA, Fulfillment by Amazon, MFN, Amazon MFN, Merchant Fulfillment Network, Prime, SameDay, NextDay, SecondDay, Marktplatz, Multi-Channel, Multichannel, Amazon Multi-Channel, Multi-Channel Amazon, Amazon Business, Amazon B2B, Amazon VCS, VCS, VCS Lite, IDU, Invoice Document Uploader, Amazon Rechnung, Umsatzsteuerservice, Amazon Pay, Amazon Produkttyp, Flat File, Flatfile, Lagerbestandsdatei, ASIN, ASIN-Verknüpfung, Amazon-Plattform, amazon.de, Autorisierung, Gutschriftenimport, VCS plentymarkets, VCS Amazon
:description: Auf dieser Seite erfährst du, wie du Amazon in plentymarkets einrichtest, um deine Artikel auf Amazon zu verkaufen.
:page-pagination:
:author: team-plenty-channel

link:https://www.amazon.de/[Amazon^] hat sich von der größten Online-Buchhandlung zum führenden Universalkaufhaus entwickelt. Unzählige Kund:innen schätzen die große Auswahl, vertrauen auf eine hohe Warenqualität und erwarten besten Service wie zum Beispiel eine sehr zeitnahe Warenlieferung. plentymarkets ermöglicht dir die komplette und integrierte Anbindung an Amazon. Erfahre, wie du Artikel verfügbar machst, den Datenaustausch über die Schnittstelle aktivierst, den FBA-Service von Amazon nutzt und vieles mehr. FBA ist das Kürzel für Fulfillment by Amazon, einem Service von Amazon, bei dem Amazon die Lagerhaltung sowie die gesamte Logistik übernimmt.

[#100]
== Bei Amazon registrieren

Bevor du Einstellungen in plentymarkets vornimmst, registriere dich bei Amazon als Verkäufer:in. Die zentrale Anlaufstelle für Verkäufer:innen bei Amazon ist die Amazon Seller Central. Händler:innen, die mehr als 40 Artikel im Monat verkaufen, werden bei Amazon als sogenannte Power-Anbieter:innen geführt und haben auch erst ab dieser Stufe die Möglichkeit zum Upload von Artikellisten. Wähle als plentymarkets Nutzer:in die Option Power-Anbieter, da nur mit diesem Konto Lagerbestand und Angebote durch Automatismen und APIs verwaltet werden können. Bei dieser Option fällt eine monatliche Grundgebühr sowie weitere Gebühren beim Verkauf an. Weitere Informationen dazu findest du auf der link:http://www.amazon.de/b/ref=nav_cs_sell/279-9008302-8223762?ie=UTF8&node=2383621031[Website von Amazon^].

== Informationen zu Amazon-Konten

// Belgien einfügen

Amazon hat seine europäischen Marktplätze vereint. So kannst du Produktangebote für alle Amazon-Marktplätze in Deutschland, Frankreich, Großbritannien, Spanien, Italien und Schweden erstellen und verwalten. Du steuerst, was du wo verkaufst. Alle Geschäfte wickelst du bequem über ein einziges Verkäuferkonto ab. Dein Verkäuferkonto ermöglicht dir automatisch, deine Angebote auf den folgenden Amazon-Plattformen zu verkaufen:

* Amazon.ae
// * Amazon.bel
* Amazon.de
* Amazon.co.uk
* Amazon.es
* Amazon.fr
* Amazon.it
* Amazon.nl
* Amazon.pl
* Amazon.se
* Amazon.tr

Beim Einrichten des Kontos wirst du aufgefordert, einen Heimat-Marktplatz zu bestimmen. Du kannst jeden der oben aufgeführten Marktplätze wählen. Amazon empfiehlt aber, als Heimat-Marktplatz das Land zu wählen, von dem aus du operierst und deine Bestellungen erfüllst. Beachte die weiteren link:http://services.amazon.de/programme/verkaufen-bei-amazon/ein-europisches-konto/[Informationen zum europäischen Verkäuferkonto^] sowie die link:https://services.amazon.de/programme/online-verkaufen/faq.html[FAQ^] von Amazon.

[#350]
[discrete]
===== Amazon-Plattform

Wenn du mit einem europäischen Verkäuferkonto mehrere Amazon-Plattformen nutzt, richte, je nachdem, welche Optionen du nutzen möchtest, für jede Plattform ein neues Konto mit plattformspezifischen Einstellungen in plentymarkets ein. Richte einzelne Konten für den Preisabgleich, den Artikeldatenexport und den Import von ausstehenden Aufträgen ein. Wenn du beispielsweise nur den Bestandsabgleich nutzen möchtest, erstelle kein eigenes Konto für die unterschiedlichen Länderplattformen. +
Die Zugangsdaten sind für alle Plattformen gleich.

// Amazon.bel einfügen

[TIP]
.Amazon-Plattformen
====
Mit plentymarkets kannst du auf den Amazon-Plattformen Amazon.de, Amazon.ae, Amazon.ca, Amazon.co.uk, Amazon.com, Amazon.com.mx, Amazon.es, Amazon.fr, Amazon.it, Amazon.nl, Amazon.pl, Amazon.se und Amazon.tr verkaufen.
====

//[#10]
//== Amazon-Grundeinstellungen vornehmen

include::partial$amz-einrichtungsmenue-kathrin.adoc[]

// Diese Infos könnten auf eine eigene MFN-Seite?
[#6900]
== Amazon-spezifische Einstellungen in Versandprofil vornehmen

Die Namen von Versanddienstleister und Versandservice, die mit der Versandanmeldung an Amazon gesendet werden, müssen exakt mit den von Amazon erlaubten Namen übereinstimmen. In deinen Versandprofilen verknüpfst du deshalb deine Versanddienstleister und Versandservices mit den von Amazon erlaubten Werten.

[.instruction]
Amazon-spezifische Einstellungen in Versandprofil vornehmen:

. Öffne das Menü *Einrichtung » Aufträge » Versand » Optionen*.
. Wechsele in das Tab *Versandprofile*.
. Öffne das Versandprofil.
. Wechsele in das Tab *Portotabelle*.
. Klappe die Region auf (icon:angle-down[]).
. Navigiere zum Bereich *Amazon Versandeinstellungen*.
. Wähle aus der Dropdown-Liste *Transportservice* den Versanddienstleister.
. Wähle aus der Dropdown-Liste *Versandservice* die Versandart. +
*_Hinweis:_* Die Dropdown-Listen enthalten die gängigsten Services. Wenn du andere Werte übertragen möchtest, wähle die Option *Andere* und gib den Wert in das Eingabefeld ein.
. Speichere (terra:save[]) die Einstellungen. +
→ In Versandanmeldungen werden für dieses Versandprofil die gewählten Werte als Versanddienstleister und Versandservice an Amazon übertragen. +
*_Hinweis:_* Wenn du keine Werte aus den Dropdown-Listen wählst, werden die Standardwerte aus dem Versandprofil übertragen.
. *_Optional:_* Wiederhole diese Einstellungen für alle Versandprofile, die du für Amazon verwendest.

[#1500]
== _Optional:_ Manuellen Datenaustausch aktivieren

In diesem Bereich werden die Einstellungen für den manuellen Datenaustausch zwischen deinem plentymarkets System und dem Marktplatz Amazon beschrieben. Du kannst Amazon-Aufträge manuell über eine CSV-Datei importieren. Du erfährst außerdem, wie du Versandbestätigungen an Amazon sendest, FBA-Bestände synchronisierst und Auftragsberichte von Amazon zurücksetzt.

[#1900]
=== _Optional:_ Amazon-Aufträge manuell importieren

Im Menü *Einrichtung » Märkte » Amazon » Datenaustausch » Auftragsimport* richtest du den manuellen Import von Amazon-Aufträgen ein. Aufträge können so manuell über eine CSV-Datei importiert werden.

*_Tipp:_* Beim Auftragsimport wird zusätzlich die ursprüngliche Währung sowie der ursprüngliche Brutto- und Netto-Betrag an der Artikelposition gespeichert, wenn die Währung nicht die in plentymarkets eingestellte Standardwährung ist.

[.instruction]
Manuellen Auftragsimport einrichten:

. Öffne das Menü *Einrichtung » Märkte » Amazon » Datenaustausch » Auftragsimport*.
. Wähle aus der Dropdown-Liste *Verfahren für Auftragsimport* die Option *CSV-Datei importieren*. +
→ Der Bereich *Einstellungen* wird geöffnet.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<#auftragsimport-amazon>>.
. Klicke auf *Vorschau* (icon:search[role="blue"]), um eine Vorschau des Imports anzuzeigen.

[[auftragsimport-amazon]]
.Manueller Auftragsimport des Marktplatzes Amazon
[cols="1,3a"]
|===
| Einstellung | Erläuterung

| *Buche Zahlungseingang*
| Beim Auftragsimport automatisch den Zahlungseingang buchen.

| *Altes Format verwenden*
| Wenn noch das alte Amazon-Importformat verwendet wird, diese Option aktivieren.

| *Mandant*
| Mandanten für den Auftragsimport wählen.

| *Amazon-Account*
| Amazon-Konto wählen.

| *CSV-Datei*
| CSV-Datei für den Auftragsimport wählen.
|===

[.instruction]
Aufträge aus CSV-Datei importieren:

. Klicke auf *Datei auswählen*.
. Wähle die CSV-Datei für den Import.
. Klicke auf *öffnen*.
. Klicke dann auf *Vorschau* (icon:search[role="blue"]). +
→ Die verfügbaren Aufträge werden angezeigt.
. Aktiviere bei den Aufträgen, die importiert werden sollen, die Option *Importieren*.
. Klicke auf das *Zahnrad*, um die Aufträge zu importieren. +
*_Tipp:_* Wurden Aufträge von Amazon in dein System importiert, die du nicht mit plentymarkets eingestellt hast? Oder Aufträge, für die in plentymarkets noch keine Artikel gespeichert sind? Bei diesen Aufträgen kannst du manuell die Artikel zuordnen und den Status einstellen.

[IMPORTANT]
.Fehlende Rechnungsanschrift
====
Wenn bei den von Amazon abgerufenen Aufträgen die Rechnungsanschrift fehlt, wende dich an den Amazon-Support. Die Einstellung muss von Amazon vorgenommen werden.
====

[#2200]
=== _Optional:_ Versandbestätigungen manuell senden

Sobald der Amazon-Auftrag in deinem plentymarkets System bearbeitet und die Ware verschickt wurde, musst du Amazon über den neuen Status informieren. Nur so schreibt Amazon die Umsätze deinem Konto gut. Auch diesen wichtigen Schritt erledigt dein plentymarkets System automatisch über die Schnittstelle.

Die Versandbestätigung eines Auftrags wird unter den folgenden Bedingungen automatisch an Amazon gemeldet:

*  Herkunft *Amazon* oder eine Unterherkunft von Amazon
*  Statusbereich 7 (kleiner als 8)
*  Externe Auftragsnummer
*  Importierter Auftrag (nicht manuell erstellt)
*  Warenausgang gebucht (Uhrzeit darf nicht in der Zukunft liegen)

Du kannst Versandbestätigungen aber auch manuell an Amazon senden. Das kann zum Beispiel sinnvoll sein, wenn die automatische Übermittlung der Versandbestätigung nicht funktioniert, zum Beispiel weil Server kurzfristig nicht erreichbar sind. Oder einzelne Auftäge sollen kurz vor einem Abrechnungsstichtag manuell bestätigt werden, damit soe bei der nächsten Auszahlung berücksichtigt werden. Beachte aber, dass für Prime-Aufträge manuell keine Versandbestätigung an Amazon gesendet werden kann. Prime-Aufträge bedeutet Amazon_Prime, Amazon_Prime_SameDay, Amazon_Prime_NextDay und Amazon_Prime_SecondDay.

[.instruction]
Versandbestätigung manuell an Amazon senden:

. Öffne das Menü *Einrichtung » Märkte » Amazon » Datenaustausch » Versandbestätigung*.
. Wähle ein Amazon-Konto aus der Dropdown-Liste.
. Gib ein Datum bei der Option *Datum Warenausgang* ein. +
→ Der gesamte Warenausgang des eingestellten Datums wird an Amazon übertragen.
. Klicke auf *Versandbestätigung senden*.

[#amazon-berichte-verwalten]
== Amazon-Berichte verwalten

Im Menü *Einrichtung » Märkte » Amazon » Berichte » Verarbeitung* erhältst du einen Überblick über den Verarbeitungsstand deiner Amazon-Berichte.

* Du siehst, welche Berichte bereits verarbeitet wurden und welche Berichte sich noch in der Warteschlange befinden.
* Du kannst Amazon-Berichte zurücksetzen oder überspringen. So kannst du festlegen, welche Berichte zuerst verarbeitet werden sollen oder auch die Auslastung deines Systems reduzieren, indem du Berichte überspringst.
* Du kannst Amazon-Berichte herunterladen.

[#27OXO0IL]
=== Amazon-Berichte anzeigen

[.instruction]
Amazon-Berichte anzeigen:

. Öffne das Menü *Einrichtung » Märkte » Amazon » Berichte » Verarbeitung*. +
*_Wichtig:_* Die Liste ist leer, wenn du das Menü öffnest. +
. *_Optional:_* Setze Filter, um nur bestimmte Berichte anzuzeigen. Die verfügbaren Filter findest du in <<#tabelle-amazon-berichte>>.
. Klicke auf *Suchen* material:search[]. +
→ Alle verfügbaren Berichte werden in der Liste angezeigt. +
*_Tipp:_* Informationen zu den Spalten und den verfügbaren Aktionen findest du in <<#tabelle-amazon-berichte>>.

[[tabelle-amazon-berichte]]
.Spalten im Menü *Einrichtung » Märkte » Amazon » Berichte » Verarbeitung*
[cols="1,3a"]
|===
| Spalte | Erläuterung

| material:tune[]
|
[#amazon-berichte-filtern]
Wenn du dir nur bestimmte Berichte ansehen willst, kannst du Filter anwenden und damit die angezeigten Berichte eingrenzen.

. Klicke im oberen Bereich des Menüs auf *Filter* (material:tune[]).
. Wähle einen oder mehrere Filter. +
*_Tipp:_* Klappe die Info-Box *Filter für Amazon-Berichte* auf, um die verfügbaren Filter zu sehen.
. Klicke auf *Suchen* (material:search[role=blue]). +
→ Die passenden Berichte werden angezeigt. +
→ Die aktiven Filter werden oben im Menü angezeigt. +
*_Tipp:_* Du kannst die gewählten Filter auch *zurücksetzen* (material:refresh[]). Dann werden wieder alle Amazon-Berichte angezeigt.

[.collapseBox]
.Welche Filter gibt es für Amazon-Berichte?
--

[cols="1,4a"]
!===
! Filter ! Erläuterung

! *Verkäufer-ID*
! Verkäufer-ID aus der Dropdown-Liste wählen, um nur Berichte mit dieser Verkäufer-ID anzuzeigen. +

*_Hinweis:_* Du musst eine Verkäufer-ID wählen. Wenn du keine Verkäufer-ID wählst, werden auch keine Berichte angezeigt.

! *Berichts-ID*
! Berichts-ID eingeben, um einen bestimmten Bericht zu suchen. +
*_Hinweis:_* Du kannst hier nur eine Berichts-ID eingeben.

! *Bearbeitungsstatus*
! *Übersprungen*, *Ausstehend* oder *Abgeschlossen* aus der Dropdown-Liste wählen. Nur Berichte mit diesem Status werden angezeigt.

! *Berichtstyp*
! Berichtstyp aus der Dropdown-Liste wählen, um nur Berichte dieses Typs anzuzeigen.

! *Hinzugefügt von*
! Datum im Format *D.M.YYYY* eingeben oder über den Kalender (material:today[]) wählen. In der Zeile *Uhrzeit Hinzufügung von* kannst du zusätzlich eine Uhrzeit eingeben oder über (material:schedule[]) wählen. +
Nur Berichte, die ab diesem Datum und zu dieser Uhrzeit erstellt wurden, werden angezeigt. Berichte, die früher erstellt wurden, werden nicht angezeigt.

! *Hinzugefügt bis*
! Datum im Format *D.M.YYYY* eingeben oder über den Kalender (material:today[]) wählen. In der Zeile *Uhrzeit Hinzufügung bis* kannst du zusätzlich eine Uhrzeit eingeben oder über (material:schedule[]) wählen. +
Nur Berichte, die bis zu diesem Datum und zu dieser Uhrzeit erstellt wurden, werden angezeigt. Berichte, die später erstellt wurden, werden nicht angezeigt.

! *Aktualisiert von*
! Datum im Format *D.M.YYYY* eingeben oder über den Kalender (material:today[]) wählen. In der Zeile *Uhrzeit Aktualisierung von* kannst du zusätzlich eine Uhrzeit eingeben oder über (material:schedule[]) wählen. +
Nur Berichte, die ab diesem Datum und zu dieser Uhrzeit aktualisiert wurden, werden angezeigt. Berichte, die früher aktualisiert wurden, werden nicht angezeigt.

! *Aktualisiert bis*
! Datum im Format *D.M.YYYY* eingeben oder über den Kalender (material:today[]) wählen. In der Zeile *Uhrzeit Aktualisierung bis* kannst du zusätzlich eine Uhrzeit eingeben oder über (material:schedule[]) wählen. +
Nur Berichte, die bis zu diesem Datum und zu dieser Uhrzeit aktualisiert wurden, werden angezeigt. Berichte, die später aktualisiert wurden, werden nicht angezeigt.
!===
--

| *Verkäufer-ID*
| Die Verkäufer-ID deines Amazon-Verkäuferkontos

| *Berichts-ID*
| Die Berichts-ID des Berichts

| *Verarbeitungsstatus*
| Der Verarbeitungsstatus des Berichts +
Berichte können sich in den folgenden Status befinden:

*Ausstehend* (material:circle[role=blue]) = Der Bericht wurde noch nicht verarbeitet. +
*Übersprungen* (material:circle[]) = Der Bericht wurde übersprungen und nicht verarbeitet. +
*Abgeschlossen* (material:circle[role=green]) = Der Bericht wurde verarbeitet.

| *Berichtstyp*
| Der Berichtstyp +
*_Tipp:_* Wenn du mit der Maus auf einen Berichtstyp zeigst, wird ein Tooltip mit Informationen zu diesem Berichtstyp angezeigt.

//tag::amazon-report-types[]
[.collapseBox]
.Welche Berichtstypen für Amazon gibt es?
--

Die folgende Tabelle zeigt eine Übersicht aller Berichtstypen.

[cols="2,2a"]
!===
! Berichtstyp ! Wozu dient der Bericht?

! Lagerbestand mit Versand durch Amazon
! * Bestandsabgleich für FBA-Bestand

! GET_FBA_MYI_ALL_INVENTORY_DATA
! * Bestandsabgleich für FBA-Bestand

! Von Amazon versandter Lagerbestand
! * Bestandsabgleich für FBA-Bestand

! „Versand durch Amazon“-Kundenrücksendungen
! * Importieren von FBA-Retouren

! Von Amazon versandte Sendungen – Steuerabrechnung - EU
! * Importieren von FBA-Aufträgen für EU-Verkäufer

! Von Amazon versandte Sendungen – Steuerabrechnung - NA
! * Importieren von FBA-Aufträgen für nordamerikanische Verkäufer

! GET_FLAT_FILE_VAT_INVOICE_DATA_REPORT
! * Korrigieren von Aufträgen für VCS Lite und VCS plentymarkets +
* Erzeugung von fehlenden Rechnungen

! GET_VAT_TRANSACTION_DATA
! * monatlicher Bericht +
* Korrigieren von Aufträgen +
* Importieren von externen Rechnungen und Gutschriften auf Basis von VCS/VCS Amazon

! SC_VAT_TAX_REPORT
! * Korrigieren und Importieren externer Rechnungen und Gutschriften auf Basis von VCS/VCS Amazon

! MFN XML Auftragsbericht - Steuerabrechnung - EU
! * Importieren von FBM-Aufträgen für EU-Verkäufer

! MFN XML Auftragsbericht - Steuerabrechnung - NA
! * Importieren von FBM-Aufträgen für nordamerikanische Verkäufer

! GET_ORDER_REPORT_DATA_SHIPPING
! * Importieren von FBM-Aufträgen für nordamerikanische Verkäufer
!===
--
//end::amazon-report-types[]

| *Bericht erstellt am*
| Das Datum und die Uhrzeit, an dem der Bericht erstellt wurde.

| *Bericht aktualisiert am*
| Das Datum und die Uhrzeit, an dem der Bericht zuletzt aktualisiert wurde.

| *Aktionen*
| *_Hinweis:_* Einige Berichtstypen können nicht zurückgesetzt oder übersprungen werden. +

* *Bericht herunterladen* (material:file_download[]) =  Der Bericht wird heruntergeladen. +
* *Bericht zurücksetzen* (material:history[]) = Der Bericht wird zurückgesetzt. Wenn du einen Bericht zurücksetzt, wird der Bericht neu verarbeitet. Das kann zum Beispiel hilfreich sein, wenn der Bericht Auftragsdaten eines neuen Auftrags noch nicht enthält. Wenn der Bericht neu verarbeitet wird, sind darin auch Daten neuer Aufträge enthalten. +
Achte jedoch darauf, dass die Leistungsfähigkeit deines Systems beeinträchtigt wird, wenn du zu viele oder zu große Berichte zurücksetzt. Neue Berichte werden dann unter Umständen erst später verarbeitet. +
* *Bericht überspringen* (material:skip_next[]) = Der Bericht wird übersprungen. Wenn du einen Bericht überspringst, wird er zunächst nicht verarbeitet. Du kannst den Bericht dann auch nicht herunterladen. +
Berichte zu überspringen kann sinnvoll sein, wenn du die Auslastung deines Systems reduzieren willst. Außerdem kannst du so bestimmen, welche Berichte als nächstes verarbeitet werden sollen. Denn wenn du Berichte überspringst, werden die nächsten Berichte in der Warteschlange verarbeitet. +
Beachte jedoch, dass Berichte, die im Hintergrund bereits von einem Prozess aufgegriffen wurden, nicht mehr übersprungen werden können. +

*_Hinweis:_* Berichte, die älter als 31 Tage minus 6 Stunden sind, können nicht mehr heruntergeladen, zurückgesetzt oder übersprungen werden.
|===

[#27OXO8OL]
=== Amazon-Berichte herunterladen

Du kannst Berichte herunterladen.

*_Wichtig:_* Berichte, die älter als 31 Tage minus 6 Stunden sind, können nicht mehr heruntergeladen werden.

[.instruction]
Amazon-Berichte herunterladen:

. Öffne das Menü *Einrichtung » Märkte » Amazon » Berichte » Verarbeitung*. +
*_Wichtig:_* Die Liste ist leer, wenn du das Menü öffnest. +
. Klicke auf *Suchen* material:search[]. +
→ Alle verfügbaren Berichte werden in der Liste angezeigt.
. Navigiere zu dem Bericht, den du herunterladen möchtest.
. Klicke in der Spalte *Aktionen* auf *Bericht herunterladen*. +
→ Der Bericht wird heruntergeladen.

[#27OXO4IL]
=== Amazon-Berichte zurücksetzen

Wenn du einen Bericht zurücksetzt, wird der Bericht neu verarbeitet. Das kann zum Beispiel hilfreich sein, wenn der Bericht Auftragsdaten eines neuen Auftrags noch nicht enthält. Wenn der Bericht neu verarbeitet wird, sind darin auch Daten neuerer Aufträge enthalten. Berichte, die älter als 31 Tage minus 6 Stunden sind, können nicht mehr zurückgesetzt oder übersprungen werden.

*_Wichtig:_* Die Leistungsfähigkeit deines Systems wird beeinträchtigt, wenn du zu viele oder zu große Berichte zurücksetzt. Neue Berichte werden dann unter Umständen erst später verarbeitet.

[.instruction]
Amazon-Berichte zurücksetzen:

. Öffne das Menü *Einrichtung » Märkte » Amazon » Berichte » Verarbeitung*. +
*_Wichtig:_* Die Liste ist leer, wenn du das Menü öffnest. +
. Klicke auf *Suchen* material:search[]. +
→ Alle verfügbaren Berichte werden in der Liste angezeigt.
. Navigiere zu dem Bericht, den du zurücksetzen möchtest.
. Klicke in der Spalte *Aktionen* auf *Bericht zurücksetzen*. +
→ Der Bericht wird zurückgesetzt und neu verarbeitet.

[#27OX34IL]
=== Amazon-Berichte überspringen

Wenn du einen Bericht überspringst, wird der Bericht zunächst nicht verarbeitet. Du kannst den Bericht dann auch nicht herunterladen.

Berichte zu überspringen kann sinnvoll sein, wenn du die Auslastung deines Systems reduzieren willst. Außerdem kannst du so bestimmen, welche Berichte als nächstes verarbeitet werden sollen. Denn wenn du Berichte überspringst, werden die nächsten Berichte in der Warteschlange verarbeitet.

*_Wichtig:_* Berichte, die im Hintergrund bereits von einem Prozess aufgegriffen wurden, können nicht mehr übersprungen werden.

[.instruction]
Amazon-Berichte überspringen:

. Öffne das Menü *Einrichtung » Märkte » Amazon » Berichte » Verarbeitung*. +
*_Wichtig:_* Die Liste ist leer, wenn du das Menü öffnest. +
. Klicke auf *Suchen* material:search[]. +
→ Alle verfügbaren Berichte werden in der Liste angezeigt.
. Navigiere zu dem Bericht, den du überspringen möchtest.
. Klicke in der Spalte *Aktionen* auf *Bericht überspringen*. +
→ Der Bericht wird übersprungen.

[#berichte-anfordern]
=== Amazon-Berichte anfordern

Im Menü *Einrichtung » Märkte » Amazon » Berichte » Anfordern* kannst du die Erstellung von Amazon-Berichten anfordern.
Das kann zum Beispiel hilfreich sein, wenn Daten in deinen Amazon-Berichten fehlen und du deshalb einen neuen Bericht benötigst.

*_Hinweise zum Anfordern von Berichten:_*

* Der Zeitraum, über den du Berichte anfordern willst, darf maximal eine Woche sein.
* Der Zeitraum, über den du Berichte anfordern willst, sollte so klein wie möglich sein. Die Verarbeitung sehr großer Berichte aufgrund der Datenmenge kann zu Problemen führen.
* Berichte können nicht beliebig oft angefordert werden. Wenn du den Berichtstyp gewählt hast, wird dir darunter angezeigt, wie oft pro Tag du einen Bericht dieses Typs anfordern kannst. 

[IMPORTANT]
.Leere Berichte werden nicht erstellt
====
Wenn für den angeforderten Zeitraum des Berichts keine Daten vorliegen, erstellt Amazon auch keinen Bericht. Derzeit kann plentymarkets leider keine Rückmeldung darüber geben, dass ein Bericht nicht generiert werden konnte.
====

[.instruction]
Amazon-Bericht anfordern:

. Öffne das Menü *Einrichtung » Märkte » Amazon » Berichte » Anfordern*.
. Nimm die Einstellungen vor. Beachte die Erläuterungen in <<#tabelle-bericht-anfordern>>.
. Klicke auf *Anfordern*. +
→ Der angeforderte Bericht wird bei Amazon generiert. +
→ Sobald der Bericht verfügbar ist, kannst du ihn in deinem plentymarkets System im Menü *Einrichtung » Märkte » Amazon » Berichte » Verarbeitung* abrufen. +
*_Wichtig:_* Es kann mehrere Minuten dauern, bis der angeforderte Bericht in deinem System verfügbar ist.

[[tabelle-bericht-anfordern]]
.Berichtserstellung anfordern
[cols="1,3a"]
|===
| Einstellung | Erläuterung

| *Startdatum* (Pflichtfeld)
| Datum im Format *DD.MM.YYYY* eingeben oder über den Kalender (material:today[]) wählen.

| *Startzeitpunkt* (Pflichtfeld)
| Uhrzeit eingeben oder über (material:schedule[]) wählen.

| *Enddatum*
| Datum im Format *DD.MM.YYYY* eingeben oder über den Kalender (material:today[]) wählen.

| *Endzeitpunkt*
| Uhrzeit eingeben oder über (material:schedule[]) wählen.

| *Verkäufer-ID* (Pflichtfeld)
| Verkäufer-ID des Amazon-Verkäuferkontos wählen, für das Berichte angefordert werden sollen.

| *Berichtstyp* (Pflichtfeld)
| Berichtstyp wählen. Wenn du mit der Maus auf einen Berichtstyp in der Dropdown-Liste zeigst, wird ein Tooltip mit Informationen zu diesem Berichtstyp angezeigt. +
*_Hinweis:_* Berichte können nicht beliebig oft angefordert werden. Wenn du den Berichtstyp gewählt hast, wird dir darunter angezeigt, wie oft pro Tag du einen Bericht dieses Typs anfordern kannst. 

[#amazon-berichtstypen]
include::page$amazon-einrichten.adoc[tag=amazon-report-types]
|===

[#2700]
== Amazon-Aufträge abrufen

Wenn du schon mit einem anderen Shopsystem gearbeitet hast, weißt du bestimmt sehr genau, wie zeitaufwändig die tägliche Auftragsbearbeitung im Seller Central-Portal sein kann. Mit plentymarkets wird alles erheblich vereinfacht. Denn hier werden alle Aufträge aus allen angeschlossenen Märkten in einem einzigen Auftragsordner für dich gesammelt. Aus Amazon-Aufträgen werden automatisch plentymarkets Aufträge, die du nach dem gewohnten Fulfillment-Schema schnell und effektiv bearbeiten kannst. Nicht einmal um den Import der Aufträge musst du dich noch kümmern. Das macht die Schnittstelle im Hintergrund für dich. Damit alles korrekt funktioniert, sind ein paar Voraussetzungen und Einstellungen nötig, die hier zusammengefasst sind.

Aufträge werden im Viertelstundentakt abgerufen. Trotzdem kann es unter Umständen bis zu 90 Minuten dauern, bis ein in Amazon generierter Auftrag in deinem plentymarkets System angezeigt wird. Das ist keine Fehlfunktion, sondern aus technischen Gründen nicht anders möglich. Meistens wirst du vorher durch eine E-Mail von Amazon über den Verkauf informiert und kannst den Auftrag im Seller Central schon ansehen.

[IMPORTANT]
.Rabatte auf Rechnungen
====
Die Rechnungen, die plentymarkets für Amazon-Aufträge generiert, enthalten nur den Betrag, den Amazon Endkund:innen in Rechnung gestellt hat. Technisch kann nicht unterschieden werden, welche Rabatte von Amazon und welche Rabatte von Händler:innen gewährt werden.
====
// TODO: Woanders hin?

[#2800]
=== Einstellungen der Schnittstelle in plentymarkets vornehmen

Für den Import der Aufträge sind die Einstellungen *Zahlungseingang* sowie *Versandbestätigung* in den Grundeinstellungen relevant. Wir gehen davon aus, dass du Aufträge mit dem Status *[5] Freigabe Versand* übernehmen und die stündliche Versandbestätigung automatisch von deinem plentymarkets System erzeugen lässt. Kontrolliere diese Einstellungen nochmals.

=== Retouren von Amazon-Aufträgen bearbeiten

Natürlich musst du auch bei Amazon gelegentlich mit einem Widerruf nach erfolgter Auslieferung rechnen. Die Artikel müssen Kund:innen direkt an dich zurücksenden. Wie du in plentymarkets eine Retoure erstellst und den Warenausgang wieder zurücksetzt, erfährst du auf der Handbuchseite xref:warenwirtschaft:waren-ausbuchen.adoc#[Waren ausbuchen].

Amazon hat für dich die Zahlung für den Auftrag in Empfang genommen. Deshalb muss die Rückbuchung ebenfalls über Amazon erfolgen. Das musst du im Auftragsordner in der Seller Central erledigen.

[IMPORTANT]
.Rückbuchung manuell oder per Ereignisaktion ausführen
====
Die Erstattung des Kaufpreises durch Amazon wird nicht automatisch über die Schnittstelle angestoßen, sondern muss manuell oder über eine Ereignisaktion automatisch ausgeführt werden. Wenn du die manuelle Erstattung oder das Erstellen einer Ereignisaktion zum Erstatten des Kaufpreises vergisst, riskierst du eine Beschwerde bei Amazon und eine schlechte Bewertung.
====

MFN Retouren (= Händlerversand) kannst du in Form von Gutschriften per Ereignisaktion an Amazon melden. Nur mit Hilfe eines Auftrags vom Typ Gutschrift kann die Rückzahlung der Artikelsumme und den Versandkosten garantiert werden. Gehe dazu wie im Folgenden beschrieben vor.

==== Auftragsstatus erstellen

Erstelle zunächst einen Auftragsstatus für Amazon-Retouren im Menü *Einrichtung » Aufträge » Status*, zum Beispiel *[9.6] Retoure an Amazon gesendet*. Diesen Auftragsstatus benötigst du für die Amazon-Einstellungen.

==== Auftragsstatus einstellen

Stelle den Auftragsstatus nun in den Amazon-Einstellungen ein wie folgend beschrieben.

[.instruction]
Auftragsstatus für Retoure einstellen:

. Öffne das Menü *Einrichtung » Märkte » Amazon » Einstellungen*.
. Öffne das Amazon-Konto.
. Wechsele in das Tab *Auftragseinstellungen*.
. Wähle für die Einstellung *Status für übertragene Retouren* den eben eingerichteten Auftragsstatus für Amazon-Retouren.
. Speichere (terra:save[]) die Einstellungen.

==== Retouren automatisch an Amazon melden

Richte eine xref:automatisierung:ereignisaktionen.adoc#[Ereignisaktion] ein, um Retouren in Form von Gutschriften automatisch an Amazon zu senden. Wenn die Ereignisaktion *Retoure bei Amazon anlegen* in plentymarkets ausgelöst wird, wird die bei Amazon erzeugte Gutschrift erstattet.

:table-event-procedure: <<#ereignisaktion-automatische-retoure>>

include::_includes:partial$event-procedure.adoc[]

[TIP]
.Ereignisaktion und Gutschriftenimport
====
Nutze Ereignisaktionen, um Erstattungen aus plentymarkets auszulösen. Der automatische Gutschriftenimport (Option "Gutschriftenimport" in den Auftragseinstellungen) stellt sicher, dass eine Gutschrift nicht zweimal im System existiert. Wenn du aktuell Gutschriften noch manuell oder durch ein Drittsystem auslöst und keine Gutschriften in plentymarkets existieren, wird eine Gutschrift durch den Import erstellt.
====

[[ereignisaktion-automatische-retoure]]
.Ereignisaktion zum automatischen Senden von Retouren an Amazon
[cols="1,3,3"]
|===
| Einstellung | Option | Auswahl

| *Ereignis*
| Ereignis wählen +
*_Wichtig:_* Als Ereignis nicht *Auftragsanlage: Neue Gutschrift* wählen. Dadurch kann es passieren, dass Gutschriften mehrfach bei Amazon erstellt werden.
|

| *Filter*
| *Auftrag &gt; Herkunft*
| *Amazon* oder eine geeignete Amazon-Unterherkunft, zum Beispiel Amazon France. +
*_Hinweis:_* Wähle für den Filter *Auftrag > Herkunft* keine Amazon FBA-Herkunft, wie zum Beispiel Amazon FBA Germany, wenn du den automatischen Gutschriftenimport nutzt.

| *Aktion*
| *Retoure &gt; Retoure bei Amazon anlegen*
|
|===

[#3100]
[#3110]
=== Warenbestand für ausstehende Aufträge reservieren

Ausstehende Amazon-Aufträge werden in Status *[1] Unvollständige Daten* in dein plentymarkets System importiert und verbleiben in diesem Status bis Amazon den Auftrag freigibt. Bis zur Freigabe werden weder die Rechnungs-/Lieferadresse noch Artikelpreise am Auftrag gespeichert. Nach der Freigabe durch Amazon wird der Auftrag aktualisiert und die dazugehörigen Adressen und Preise werden gespeichert. Die Warenbestandsautomatik entscheidet, in welchen Status der Auftrag rutscht.

Falls Amazon den Auftrag nicht freigibt, wird der Auftrag nicht aktualisiert, sondern automatisch in Status *[8] Storniert* verschoben.

Es gibt zwei Möglichkeiten, den Warenbestand für ausstehende Aufträge in plentymarkets zu reservieren: mit einer Ereignisaktion oder direkt in den Auftragsgrundeinstellungen.

[tabs]
====
Ereignisaktion einrichten::
+
--
Mit der folgenden Ereignisaktion wird der Auftrag von Status 1 in einen Status verschoben, bei dem Warenbestand reserviert wird.

:table-event-procedure: <<#ereignisaktion-auftragsstatus-aktualisieren>>

include::_includes:partial$event-procedure-tabbed.adoc[]

[[ereignisaktion-auftragsstatus-aktualisieren]]
.Ereignisaktion zum automatischen Aktualisieren von Auftragsstatus
[cols="1,3,3"]
|===
|Einstellung |Option |Auswahl

| *Ereignis*
| *Neuer unvollständiger Auftrag*
|

| *Filter 1*
| *Auftrag &gt; Auftragstyp*
| *Auftrag*

| *Filter 2*
| *Auftrag &gt; Herkunft*
| *Amazon-Herkünfte*

| *Aktion*
| *Auftrag &gt; Status ändern*
| Status wählen, in dem der Bestand reserviert wird.
|===
--

Auftragsgrundeinstellungen::
+
--
In den Auftragsgrundeinstellungen wird über die Einstellung *Status Auftragsreservierung* definiert, in welchen Auftragsstatus Warenbestände reserviert werden.

[.instruction]
Auftragsstatus für Warenbestandsreservierung festlegen:

. Öffne das Menü *Einrichtung » Aufträge » Einstellungen*.
. Wähle bei der Einstellung *Status Auftragsreservierung* die Status, damit für Aufträge, die in diesen Status kommen, Bestand reserviert wird.
. Speichere (terra:save[]) die Einstellungen.
--
====

[#6800]
== Rechnungserzeugung für Amazon-Aufträge einrichten

include::partial$rechnungserzeugung.adoc[]

[#4500]
== Zahlungsart in Kundenklasse erlauben

Sobald ein aktives Konto für Amazon existiert, ist die Zahlungsart *Amazon* automatisch im System verfügbar. Es sind keine eigenen Konfigurationen dafür notwendig. Du musst nur noch die Zahlungsart in einer oder mehreren Kundenklassen erlauben.

:payment-method: Amazon
include::partial$zahlungsart_aktivieren.adoc[tag=mop-customer-class]


[#6600]
== API-Log abrufen

Im Menü *Daten » API-Log* findest du eine Historie über Vorgänge, die über die Amazon-Schnittstelle ausgeführt wurden. Folgende Formate stehen dir für Amazon zur Auswahl:

* *Amazoncatalog*
* *AmazonControllerOrders*
* *AmazonFBAOrders*
* *AmazonOrder*
* *AmazonOrderFulfillment*
* *AmazonPayments*
* *AmazonPaymentsAdvanced*
* *AmazonPaymentsFulfillment*
* *AmazonPriceUpdate*
* *AmazonRequestReport*
* *AmazonOrderRefund*
* *AmazonStock*
* *ArticleAmazonCSV*
* *Reader_ArticleAmazonCSV_Execution*

[.instruction]
API-Log abrufen:

. Öffne das Menü *Daten » API-Log » Tab: API-Log*.
. Wähle ein Format aus der Dropdown-Liste *Vorgang*.
. *_Optional:_* Wähle ein *Datum*, um nur Einträge eines bestimmten Tages zu erhalten.
. Klicke auf *Suchen* (icon:search[role="blue"]), um die Suche auszuführen. +
→ Die Vorgänge werden angezeigt.

[#1400]
[discrete]
=== Varianten vorbereiten

Die Informationen dazu, wie du Varianten für den Export zu Amazon vorbereitest, sind umgezogen. Du findest diese Informationen jetzt auf der Handbuchseite xref:maerkte:varianten-vorbereiten.adoc#[Varianten vorbereiten].

[discrete]
=== FAQ

Die FAQ zum Thema Preis- und Bestandsabgleich sind umgezogen. Du findest diese Informationen jetzt auf der Handbuchseite xref:maerkte:varianten-vorbereiten.adoc#6700[Varianten vorbereiten].

[#next-steps]
== Nächste Schritte

Nachdem du nun die Schnittstelle zu Amazon in plentymarkets eingerichtet hast, bereitest du als Nächstes xref:maerkte:varianten-vorbereiten.adoc#[deine Varianten für den Export zu Amazon vor].
