= Amazon: FBA vs. MFN
:keywords: Amazon FBA, FBA, FBA-Aufträge, FBA-Auftrag, MFN, Versand von Amazon-Aufträgen, Amazon Versand
:description: Auf dieser Seite erhältst du Informationen zu Amazon MFN und Amazon FBA. Infos zu Auftragsablauf und Vor- und Nachteilen sollen dir eine Entscheidungshilfe bieten.
:page-aliases: fulfillment.adoc
:page-pagination:
:author: team-plenty-channel

Den Versand von Varianten, die du über Amazon verkaufst, kannst du auf verschiedene Arten organisieren:

* <<#100, Amazon FBA: Amazon lagert und versendet>> +
*_Tipp:_* Schon für Amazon FBA entschieden? Dann gleich weiter zu xref:maerkte:amazon-fba-nutzen.adoc#[FBA-Service von Amazon nutzen].
* <<#200, Amazon MFN: Du lagerst und versendest>>

Du bist dir noch unsicher? Einige der Vor- und Nachteile haben wir in unserer <<#300, Entscheidungshilfe>> für dich zusammengestellt.

[#100]
== Amazon FBA: Amazon lagert und versendet

//tag::amazon-fba-description[]
Das Kürzel FBA steht für Fulfillment by Amazon. Statt die Aufträge selbst zu bearbeiten, die Ware zu verpacken und zu versenden, überlässt du beim FBA-Programm Amazon diese Aufgabe. Natürlich musst du dann zumindest einen Teil deiner Waren auch bei Amazon einlagern. Die Multi-Channel-Funktion ermöglicht dir außerdem, Artikel bei Amazon zu lagern und von Amazon verschicken zu lassen, die du nicht bei Amazon, sondern auf anderen externen Marktplätzen verkaufst.
//end::amazon-fba-description[]

//tag::amazon-fba-workflow[]
FBA-Bestellungen laufen wie folgt ab:

* Deine Produkte werden bei Amazon gelistet. Der Name deines Unternehmens wird an deinen Produkten angezeigt.
* Kund:innen geben eine Bestellung auf Amazon auf.
* Kund:innen zahlen an Amazon.
* Amazon verschickt die Ware.
* plentymarkets fordert einen Bericht an.
* Amazon erstellt den Bericht.
* Am nächsten Tag prüft plentymarkets automatisch, ob Berichte bei Amazon vorliegen. Wenn ja, werden die Berichte importiert.
* Aus den Berichten werden in plentymarkets Aufträge und Kontakte erzeugt.
* Die Kontakte werden 30 Tage nach dem Erstellen des Auftrags anonymisiert. Dabei werden nur die Daten von Kund:innen im Kontakt anonymisiert und die Verknüpfung des Auftrags zum Kontaktdatensatz entfernt. Die Kontaktdaten im Auftrag bleiben erhalten. +
  ** Vorname und Nachname des Kontakts werden anonymisiert.
  ** Folgenden Daten werden gelöscht:
      *** Adressen und Adressverknüpfungen
      *** Adressoptionen
      *** Auftragsverknüpfungen
      *** Kontaktoptionen
      *** Verknüpfung zu einer Firma
      *** Bankdaten
//end::amazon-fba-workflow[]


'''

Überzeugt? Dann weiter zu xref:maerkte:amazon-fba-nutzen.adoc#[FBA-Service von Amazon nutzen]

'''

[#200]
== Amazon MFN: Du lagerst und versendest

//tag::amazon-mfn-description[]
MFN steht für Merchant Fulfillment Network. Das bedeutet: Du bearbeitest deine Amazon-Aufträge selbst und verpackst und versendest die Ware. Zu diesem Thema findest du im Best Practice xref:maerkte:best-practices-amazon-mfn-auftragsimport.adoc#[MFN-Auftragsimport] weitere Informationen.
//end::amazon-mfn-description[]

//tag::amazon-mfn-workflow[]
MFN-Bestellungen laufen wie folgt ab:

* Deine Produkte werden bei Amazon gelistet. Der Name deines Unternehmens wird an deinen Produkten angezeigt.
* Kund:innen geben eine Bestellung auf Amazon auf.
* Kund:innen zahlen an Amazon.
* Der Auftrag wird in plentymarkets importiert.
* Für den Auftrag wird ein Kontakt erstellt.
* Du versendest die Ware (Dropshipping).
* Der Kontakt wird 30 Tage nach Versandbestätigung anonymisiert. Dabei werden nur die Daten von Kund:innen im Kontakt anonymisiert und die Verknüpfung des Auftrags zum Kontaktdatensatz entfernt. Die Kontaktdaten im Auftrag bleiben erhalten. +
  ** Vorname und Nachname des Kontakts werden anonymisiert.
  ** Folgenden Daten werden gelöscht:
      *** Adressen und Adressverknüpfungen
      *** Adressoptionen
      *** Auftragsverknüpfungen
      *** Kontaktoptionen
      *** Verknüpfung zu einer Firma
      *** Bankdaten
//end::amazon-mfn-workflow[]

'''

Du hast die Schnittstelle zu Amazon eingerichtet, deine Varianten und den Export vorbereitet und möchtest nur Amazon MFN nutzen? Dann sind keine weiteren Einstellungen nötig.

'''

[#300]
== Entscheidungshilfe: FBA oder MFN?

Ob die mit dem FBA-Service verbundenen Vorteile oder die Nachteile für deine persönliche Situation als Online-Händler:in überwiegen, kannst du nur selbst einschätzen. Wir möchten hier nur auf einige wichtige Punkte hinweisen:

*  Amazon bearbeitet Aufträge schnell und zuverlässig. Spitzenzeiten vor Weihnachten sind für den Shopbetreiber genauso problemlos wie das Sommerloch während der Urlaubszeit.
*  Dein Listing auf dem Marktplatz verbessert sich, d.h. du kannst mit höheren Verkaufszahlen rechnen.
*  Der FBA-Service ist mit Kosten verbunden, d.h. deine Brutto-Marge sinkt. Für einen umfassenden Vergleich der Kosten bedenke jedoch, dass im FBA-Service der Aufwand für die Lagerhaltung, das Auftragshandling, den Kundenservice etc. enthalten ist und du so von diesem Aufwand entlastet wirst.
*  Ware, die bei Amazon gelagert ist, kann in erster Linie auch nur dort angeboten werden. Für andere Marktplätze benötigst du gesonderte Warenbestände. Mit dem Service Multi-Channel-Fulfillment stellt Amazon jedoch auch eine Variante zur Verfügung, die deine Möglichkeiten diesbezüglich erweitert.
*  Du hast deutlich weniger Ärger mit nicht zustellbaren Sendungen oder verzögerten Auslieferungen. Pakete mit Amazon-Logo werden in der Regel bevorzugt behandelt.

[#next-steps]
[#400]
== Nächste Schritte

Du hast die Schnittstelle zu Amazon eingerichtet und deine Varianten und den Export vorbereitet. Wie es jetzt weitergeht kommt darauf an, ob du dich für den FBA-Service von Amazon entschieden hast.

Wenn du den FBA-Service von Amazon nutzen möchtest:

* xref:maerkte:amazon-fba-nutzen.adoc#[FBA-Service von Amazon nutzen]

TIP: Du hast die Schnittstelle zu Amazon eingerichtet, deine Varianten und den Export vorbereitet und möchtest nur Amazon MFN nutzen? Dann sind keine weiteren Einstellungen nötig.

Wenn du weitere Amazon-Services nutzen möchtest:

* xref:maerkte:amazon-geschenkservice-nutzen.adoc#[Amazon-Geschenkservice nutzen]
* xref:maerkte:amazon-business-einrichten.adoc#[Amazon Business einrichten]
* xref:maerkte:amazon-pay-einrichten.adoc#[Amazon Pay einrichten]
* xref:maerkte:AmazonVCSDashboard.adoc#[Plugin AmazonVCSDashboard nutzen]
