= Amazon-Geschenkservice nutzen
:keywords: Amazon Geschenkservice, Amazon-Geschenkservice, Amazon Geschenkoptionen
:description: Informationen zum Geschenkservice von Amazon.
:page-aliases: amazon-geschenkservice-nutzen.adoc
:author: team-plenty-channel

Mit der Aktivierung des Amazon-Geschenkservices können deine Kund:innen optional während des Bestellprozesses auf Amazon einen Geschenkpapierservice nutzen und eine Grußbotschaft eingeben. Diese Optionen werden beim automatischen Auftragsabruf übernommen, ohne dass weitere Einstellungen erforderlich sind. Für jede Auftragsposition mit Geschenkoption wird eine zusätzliche Auftragsposition mit der ID *-2* und Informationen direkt hinter dem bestellten Artikel angefügt. Dazu gehören die Verpackungsart sowie eine optionale Grußbotschaft.

Aktiviere die Geschenkoptionen in der Amazon Seller Central, um den Geschenkservice zu nutzen.

[TIP]
.Tipp: Mehrere Verpackungsarten und Aufpreise
====
Du kannst mehrere Verpackungsarten hinzufügen und Aufpreise definieren.
====
