= Amazon Prime-Aufträge bearbeiten
:keywords: Amazon Prime, Prime, Prime Aufträge, Amazon Prime Aufträge
:description: Erfahre, wie du Amazon Prime-Aufträge in deinem plentymarkets System suchst, zum Versand anmeldest und das Versandetikett erstellst.
:page-aliases: amazon-prime-auftraege-bearbeiten.adoc
:author: team-plenty-channel

Mit Filtern in den Bereichen Auftragssuche und Ereignisaktionen werden Aufträge mit den Versandbedingungen von Amazon Prime gesondert in plentymarkets behandelt. Versandetiketten für Amazon Prime-Aufträge werden über die Amazon Merchant Fulfillment API generiert.

[IMPORTANT]
.Pflichtfelder für die Anmeldung von Amazon Prime-Aufträgen
====
Damit Amazon Prime-Aufträge bearbeitet werden können, müssen bestimmte Informationen im Menü *Einrichtung » Aufträge » Versand » Dienstleister » Einstellungen* gespeichert sein. Amazon definiert folgende Pflichtfelder: *Firma*, *Straße*, *Hausnummer*, *PLZ*, *Ort*, *Land*, *Telefon* und *E-Mail*. Diese Pflichtfelder müssen gefüllt sein, damit die Anmeldung deiner Amazon Prime-Aufträge ausgeführt werden kann.
====

[#4300]
== Amazon Prime-Aufträge filtern

Im Menü *Aufträge » Aufträge bearbeiten* werden alle deine Aufträge angezeigt. Diese Aufträge kannst du über xref:auftraege:auftraege-verwalten.adoc#1300[Filter] eingrenzen und zum Beispiel nur Amazon Prime-Aufträge anzeigen lassen.

Innerhalb des Filters *Amazon* stehen dir zehn Optionen zur Auswahl:

* *ALLE* filtert alle Amazon-Aufträge.
* *Prime* filtert alle Amazon Prime-Aufträge, außer Prime SameDay, Prime NextDay und Prime SecondDay.
* *Prime (alle)* filtert alle Amazon Prime-Aufträge, auch Prime SameDay, Prime NextDay und Prime SecondDay.
* *Nein* = Amazon Prime-Aufträge werden nicht berücksichtigt.
* *Prime SameDay* nur Prime SameDay-Aufträge werden in der Auftragsübersicht gelistet.
* *Prime NextDay* nur Prime NextDay-Aufträge werden in der Auftragsübersicht gelistet.
* *Prime SecondDay* nur Prime SecondDay-Aufträge werden in der Auftragsübersicht gelistet.
* *SameDay* Amazon-Aufträge werden in der Auftragsübersicht gelistet, die nicht zu Amazon-Prime gehören, aber bei denen die Zustellung dennoch am gleichen Tag erfolgen muss.
* *NextDay* Amazon-Aufträge werden in der Auftragsübersicht gelistet, die nicht zu Amazon-Prime gehören, aber bei denen die Zustellung dennoch am nächsten Tag erfolgen muss.
* *SecondDay* Amazon-Aufträge werden in der Auftragsübersicht gelistet, die nicht zu Amazon-Prime gehören, aber bei denen die Zustellung dennoch am übernächsten Tag erfolgen muss.

[#4400]
== Versandetikett für Amazon Prime-Aufträge generieren

Amazon schreibt vor, dass du Versandetiketten für Amazon Prime-Aufträge über die Amazon Merchant Fulfillment API generierst. Dafür stellt Amazon Versanddienstleister mit vergünstigten Konditionen zur Verfügung. Im Folgenden wird beschrieben, wie du zunächst die Versandprofile mit Amazon Prime verknüpfst.

[.instruction]
Versandprofile mit Amazon Prime verknüpfen:

. Öffne das Menü *Einrichtung » Aufträge » Versand » Optionen » Tab: Versandprofile*.
. Wähle das Versandprofil, das du mit Amazon Prime verknüpfen möchtest. 
. Wähle den Filter *Amazon Prime* im Bereich *Treueprogramm*.
. Wechsele in das Tab *Portotabelle*. 
. Wähle bei der Option *Amazon Prime Service* im Bereich *Amazon Prime* die Versandart. +
→ *_Wichtig:_* Du kannst den Bereich *Amazon Prime* hier nur sehen, wenn du den Versanddienstleister *DHL* oder *DPD* wählst.
. Speichere (terra:save[]) die Einstellungen.

[TIP]
.Tipp: Versandpaket beachten
====
Beachte das am Versandprofil gespeicherte Versandpaket, damit keine überteuerten Labels generiert werden. +
Beachte außerdem, dass im verknüpften Versandpaket die Maße *Länge*, *Breite* und *Höhe* angegeben sein müssen.
====

Anschließend meldest du im Menü *Aufträge » Versand-Center » Tab: Anmelden* deine Amazon Prime-Aufträge bei dem von dir gewählten Amazon-Versanddienstleister an. Voraussetzung für die Anmeldung ist, dass du zuvor im Tab *Suche* Amazon Prime-Aufträge gesucht hast, die jetzt hier angezeigt werden.

[TIP]
.Tipp: Versanddienstleister beachten
====
Beachte, dass der passende Versanddienstleister eingestellt ist, da sonst die korrekten Amazon Services in den Portotabellen nicht eingestellt werden können. Wähle für Amazon Prime die Versanddienstleister *DHL* oder *DPD*.
====

[.instruction]
Amazon Prime-Aufträge anmelden:

. Öffne das Menü *Aufträge » Versand-Center » Tab: Suchen*.
. Suche den Amazon Prime-Auftrag, den du anmelden möchtest.
. Wechsele in das Tab *Anmelden*.
. Wähle aus der Dropdown-Liste *Versanddienstleister* die Option *Amazon Prime*.
. Klicke auf *Anmelden*.
. Öffne den Auftrag. +
→ Nach erfolgreicher Anmeldung wird im Bereich *Übersicht* ein PDF-Symbol angezeigt, über das du das Versandetikett herunterladen kannst.
