= Praxisbeispiel: Teilstornierungen an MyToys senden
:author: team-plenty-channel
:keywords: MyToys, Teilstornierung, Stornierung, MyToys Stornierung, Stonierung
:description:

Eine oder mehrere Positionen eines Auftrags sollen storniert werden? In diesem Praxisbeispiel erfährst du, wie du MyToys darüber informieren kannst, dass eine oder mehrere Positionen eines Auftrags stoniert werden.

Um eine oder mehrere Positionen eines Auftrags zu stornieren, erstellst du einen Lieferauftrag für die Positionen, die storniert werden sollen. Danach erstellst du die Ereignisaktion *Auftragsstornierung an MyToys melden*. Achte darauf, in der Ereignisaktion Lieferaufträge zu berücksichtigen.

*_Hinweis:_* Eine Teilstornierung eines oder mehrerer Artikel kann nur erfolgen, wenn die Artikel aus dem Auftrag, die storniert werden sollen, noch nicht versendet wurden.

[#lieferauftrag-erstellen]
== Lieferauftrag erstellen

Erstelle als Erstes einen Lieferauftrag für die Auftragspositionen, die storniert werden sollen.

[.instruction]
Lieferauftrag erstellen:

. Öffne das Menü *Aufträge » Aufträge bearbeiten*.
. Öffne den Auftrag, für den ein Lieferauftrag erstellt werden soll. +
→ Es handelt sich um den Auftrag, bei dem ein oder mehrere Auftragspositionen stoniert werden sollen.
. Wechsele in das Tab *Lief*.
. Trage in das Feld *LiefAufMenge* (Menge für den Lieferauftrag) die *Menge* ein, die in den Lieferauftrag überführt werden soll.
. Klicke anschließend auf *Lieferauftrag anlegen* (terra:execute[]). +
→ Der Lieferauftrag wird angelegt.

[#ereignisaktion-teilstornierung]
== Ereignisaktion einrichten

Erstelle nun eine xref:automatisierung:ereignisaktionen.adoc#[Ereignisaktion], um MyToys über die Stornierung des Artikels zu informieren.

:table-event-procedure: <<#ereignisaktion-teilstornierung-myToys>>

include::_includes:partial$event-procedure.adoc[]

[[ereignisaktion-retouren-myToys]]
.Ereignisaktion zum automatischen Melden von Teilstornierungen an MyToys
[cols="1,3,3"]
|===
|Einstellung |Option |Auswahl

| *Ereignis*
| *Auftragsänderung: Statuswechsel*
| Status wählen, zum Beispiel *[8] Storniert*

| *Filter 1*
| *Auftrag > Auftragstyp*
| *Lieferauftrag*

| *Filter 2*
| *Auftrag > Herkunft*
| *myToys*

| *Aktion*
| *Plugins*
| *Auftragsstornierung an MyToys melden*
|===