= Praxisbeispiel: eBay Seller Managed Services einrichten
:author: team-plenty-channel
:keywords: eBay SMS, eBay Versandservice, eBay Versandarten, eBay Versandprofile, Sperrgutversand, Sperrgut, Lieferservices, eBay Versand
:description: In diesem Praxisbeispiel erfährst du, wie du Versandarten für Sperrgut für eBay in plentymarkets einrichtest.

eBay Seller Managed Services (SMS) bietet dir die Möglichkeit, neue Versandarten für Sperrgut in eBay einzurichten. In diesem Praxisbeispiel erfährst du, welche Einstellungen du in plentymarkets vornehmen musst, um die neuen Versandarten für Sperrgut für eBay nutzen zu können.

[.collapseBox]
.Welche Versandarten für Sperrgut gibt es?
--
Die folgenden Versandarten für Sperrgut gibt es bei eBay:

* Bordsteinkante
* Haustür
* Wunschzimmer
* Wunschzimmer & Verpackungsmitnahme
* Wunschzimmer & Rücknahme des alten Produkts
* Wunschzimmer & Verpackungsmitnahme & Rücknahme des alten Produkts
* Wunschzimmer & Montage
* Wunschzimmer, Montage & Verpackungsmitnahme
* Wunschzimmer, Montage & Rücknahme des alten Produkts
* Wunschzimmer, Montage, Verpackungsmitnahme & Rücknahme des alten Produkts
--

*_Hinweis:_* Die neuen Versandarten für Sperrgut können momentsn nur für die eBay-Plattformen *Deutschland* und *UK* verwendet werden.

== Voraussetzungen und Einstellungen bei eBay

Um eBay Seller Managed Services nutzen zu können, musst du von eBay für den Service freigeschaltet werden. Wende dich dazu an deine Ansprechpartner:innen bei eBay.

Bevor du die neuen Versandarten für eBay in plentymarkets einrichtest, musst du einige Einstellungen auf eBay vornehmen:

* Erstelle bei eBay neue Versandkostentabellen mit den neuen Versandarten. Gib in den Versandkostentabellen die Kosten für die jeweilige Versandart und die Lieferzeit ein. +
Weitere Informationen zum Erstellen von Versandkostentabellen findest du hier.

* Verknüpfe die neuen Versandkostentabellen mit deinen Versandprofilen auf eBay oder erstelle neue Versandprofile mit den neuen Versandkostentabellen.

== Welche Einstellungen muss ich in plentymarkets vornehmen?

Wenn du alle Einstellungen bei eBay vorgenommen und die neuen Versandprofile eingerichtet hast, kannst du die auf eBay erstellten Versandkostentabellen und Versandprofile in plentymarkets importieren.

[.instruction]
Versandkostentabellen synchronisieren:

. Öffne das Menü *Einrichtung » Märkte » eBay » Datenaustausch » Tab: Sonstiges*.
. Wähle das Konto aus der Dropdown-Liste, für das die Versandkostentabellen synchronisiert werden sollen.
. Klicke auf *Start* (terra:execute[]). +
→ Die Versandkostentabellen werden in plentymarkets importiert.

Als nächstes musst du die Rahmenbedingungen in plentymarkets importieren, damit deine auf eBay vorgenommenen Änderungen an den eBay-Versandprofilen auch in plentymarkets verfügbar sind.

[.instruction]
Rahmenbedingungen importieren:

. Öffne das Menü *Einrichtung » Märkte » eBay » Rahmenbedingungen*.
. Wähle das eBay-Konto aus der Dropdown-Liste.
. Wähle die eBay-Plattform aus der Dropdown-Liste.
. Klicke auf *Importieren*.
→ Die Versandbedingungen, in denen du auf eBay die neuen Versandkostentabellen gespeichert hast, werden importiert. In plentymarkets sind in den Versandbedingungen nun auch die neuen Versandkostentabellen mit den Versandprofilen verknüpft.

*_Hinweis:_* Wenn du in plentymarkets ein bestimmtes Versandprofil für die neuen Versandarten verwenden willst, kannst du die Versandarten einem bestimmten Versandprofil in plentymarkets zuordnen. Öffne dazu das Menü *Einrichtung » Märkte » eBay » Einstellungen » Versandprofilverknüpfungen*, wähle dort die eBay-Plattform und verknüpfe die eBay-Versandprofile mit den neuen Versandarten mit den in plentymarkets gespeicherten Versandprofilen.