= Amazon Best Practice: MFN-Auftragsimport
:author: team-plenty-channel
:keywords: Amazon Händlerversand, MFN, Merchant Fulfillment Network, MFN-Auftragsimport
:description: In diesem Praxisbeispiel erfährst du, warum Amazon-MFN-Aufträge nicht in dein plentymarkets System importiert wurden und welche Einstellungen du vornehmen musst, damit die Aufträge importiert werden.

In diesem Best Practice werden unterschiedliche Lösungswege für Probleme aufgezeigt, welche dazu führen können, dass eure MFN-Aufträge (MFN = merchant fulfillment network, also Händlerversand) nicht importiert werden. Dabei gehen wir davon aus, dass in den Amazon-Grundeinstellungen der Auftragsimport bereits aktiviert wurde.

[#100]
== Autorisierung ist abgelaufen oder fehlt

Damit plentymarkets mit Amazon Daten austauschen kann, müsst ihr plentymarkets erlauben, auf euer Amazon-Konto zuzugreifen. Den Zugriff auf euer Konto erlaubt ihr im Menü *Einrichtung » Märkte » Amazon » Einstellungen* beim Erstellen eines neuen Kontos. Wenn ihr den Zugriff erlaubt habt, ist dies auch im Seller Central unter *Einstellungen » Benutzerberechtigungen* im Bereich *Amazon MWS Entwicklerberechtigungen* sichtbar. Ist die Berechtigung nicht vorhanden, werden Anfragen von Amazon blockiert. plentymarkets kann also weder Daten von Amazon abrufen, noch Daten zu Amazon senden.

[IMPORTANT]
====
Ihr könnt diesen Fall erkennen, indem ihr im Seller Central prüft, ob die Berechtigung vorliegt. Diese Einstellung findet ihr im Menü *Einstellungen » Benutzerberechtigungen* im Bereich *Amazon MWS Entwicklerberechtigungen*.
Ein weiteres Anzeichen dafür ist die Fehlermeldung: _Error:Access to Reports. (GetReportScheduleList) is denied_ die ihr dann bei fast allen Anfragen bekommt. Zu finden ist diese Fehlermeldung in den Logs oder im Menü *Einrichtung » Märkte » Amazon » Datenaustausch » Berichte*, wenn ihr, wie im nächsten Punkt beschrieben, die _scheduled reports_ setzt.
====

In unserem xref:maerkte:amazon-einrichten.adoc#300[Handbuch] wird beschrieben, wie ihr den Zugriff erteilt.

[#200]
== Zugriffsberechtigung abgelaufen

Ihr könnt die Zugriffsberechtigung über den Assistenten *Amazon - Grundeinstellungen* im Menü *Einrichtung » Assistenten » Omni-Channel* aktualisieren. Klickt dazu im Schritt *Zugriff auf Amazon erlauben* auf *Zugriff erlauben*. Ihr werdet zu Amazon weitergeleitet und müsst euch dort mit euren Amazon-Zugangsdaten einloggen. Klickt dort auf *Confirm*, um die Zugriffsberechtigung zu erneuern.

[#300]
== Zugangsdaten nicht korrekt

Selbstverständlich müssen die Zugangsdaten in den Grundeinstellungen korrekt sein, damit plentymarkets Kontakt mit eurem Amazon-Konto aufnehmen kann.

[IMPORTANT]
====
Die Fehlermeldung dazu lautet _ERROR: AuthToken is not valid for SellerId and AWSAccountId_, wenn der Händler-Token in den Grundeinstellungen nicht korrekt eingetragen ist.
====

[#500]
== Weitere Fehlermeldung

Bei der Fehlermeldung _The seller does not have an eligible Amazon account to call Amazon MWS._ kann es ebenfalls sein, dass keine Berechtigung für den Zugriff von plentymarkets auf Amazon vorliegt. Dazu einmal wie oben beschrieben die Entwicklerberechtigungen prüfen und wenn nicht vorhanden diese über den Assistenten hinzufügen.
Sollte dies nicht helfen, kontaktiere Amazon. Entweder ist euer Seller-Account kein Power-Anbieter oder euer Account ist noch nicht komplett freigeschaltet.
