= Praxisbeispiel: eBay Seller Managed Services einrichten
:author: team-plenty-channel
:keywords: eBay SMS, eBay Versandservice, eBay Versandarten, eBay Versandprofile, Sperrgutversand, Sperrgut, Lieferservices, eBay Versand
:description: In diesem Praxisbeispiel erfährst du, wie du Versandarten für Sperrgut für eBay in plentymarkets einrichtest.

eBay Seller Managed Services (SMS) bietet dir die Möglichkeit, neue Versandarten für Sperrgut in eBay einzurichten. Du kannst beispielsweise die Lieferung in ein Wunschzimmer, die Montage des Artikels und die Rücknahme des alten Produkts anbieten. +
In diesem Praxisbeispiel erfährst du, welche Einstellungen du in plentymarkets vornehmen musst, um die neuen Versandarten für Sperrgut für eBay nutzen zu können.

[.collapseBox]
.Welche Versandarten für Sperrgut gibt es?
--
Die folgenden Versandarten für Sperrgut kannst du deinen Kund:innen auf eBay anbieten:

* Bordsteinkante
* Haustür
* Wunschzimmer
* Wunschzimmer & Verpackungsmitnahme
* Wunschzimmer & Rücknahme des alten Produkts
* Wunschzimmer & Verpackungsmitnahme & Rücknahme des alten Produkts
* Wunschzimmer & Montage
* Wunschzimmer, Montage & Verpackungsmitnahme
* Wunschzimmer, Montage & Rücknahme des alten Produkts
* Wunschzimmer, Montage, Verpackungsmitnahme & Rücknahme des alten Produkts

Weitere Informationen zu den Versandservices für Sperrgut findest du bei link:https://www.ebay.de/verkaeuferportal/versand/gewerblich/sperrgutversand-services[eBay^].
--

*_Hinweis:_* Die neuen Versandarten für Sperrgut können momentan nur für die eBay-Plattformen *Deutschland* und *UK* verwendet werden.

== Voraussetzungen und Einstellungen bei eBay

Um eBay Seller Managed Services nutzen zu können, musst du von eBay für den Service freigeschaltet werden. Wende dich dazu an deine Ansprechpartner:innen bei eBay.

Bevor du die neuen Versandarten für eBay in plentymarkets einrichtest, musst du einige Einstellungen auf eBay vornehmen:

* Erstelle bei eBay neue Versandkostentabellen mit den Versandarten für Sperrgut. Gib in den Versandkostentabellen jeweils die Kosten für die Versandart und die Lieferzeit ein. +
Weitere Informationen zum Erstellen von Versandkostentabellen findest du bei link:https://www.ebay.de/help/shipping-items/selling/setting-shipping-options/seller-managed-services?id=5386[eBay^]. Außerdem findest du in diesem link:https://cdn02.plentymarkets.com/pmsbpnokwu6a/frontend/Seller_Managed_Services_setup_guide.pdf[Setup Guide^] detaillierte Informationen zu den Einstellungen auf eBay. Beachte aber, dass dieser Setup Guide nur auf Englisch verfügbar ist.

* Füge die neuen Versandkostentabellen deinen Listings auf eBay hinzu, für die du Sperrgutversand anbieten möchtest. Erstelle dazu auf eBay Versandbedingungen mit den neuen Versandkostentabellen und verknüpfe diese Versandbedingungen mit deinen Listings.

== Welche Einstellungen muss ich in plentymarkets vornehmen?

Wenn du alle Einstellungen bei eBay vorgenommen und die neuen Versandkostentabellen und Versandbedingungen eingerichtet hast, importierst du die auf eBay erstellten Versandkostentabellen und Versandbedingungen in dein plentymarkets System.

[.instruction]
Versandkostentabellen synchronisieren:

. Öffne das Menü *Einrichtung » Märkte » eBay » Datenaustausch » Tab: Sonstiges*.
. Wähle im Bereich *Versandkostentabellen synchronisieren* das eBay-Konto aus der Dropdown-Liste, für das die Versandkostentabellen synchronisiert werden sollen.
. Klicke auf *Start* (terra:execute[]). +
→ Die neuen Versandkostentabellen werden in plentymarkets importiert.

Als nächstes musst du die Versandbedingungen in plentymarkets importieren, damit deine auf eBay vorgenommenen Änderungen an den eBay-Versandbedingungen auch in plentymarkets verfügbar sind.

[.instruction]
Versandbedingungen importieren:

. Öffne das Menü *Einrichtung » Märkte » eBay » Rahmenbedingungen*.
. Wähle das eBay-Konto aus der Dropdown-Liste.
. Wähle die eBay-Plattform aus der Dropdown-Liste.
. Klicke auf *Importieren*.
→ Die Versandbedingungen, in denen du auf eBay die neuen Versandkostentabellen gespeichert hast, werden importiert. Die neu importierten Versandbedingungen sind in plentymarkets nun auch in den Versandprofilen gespeichert.

*_Hinweis:_* Wenn du in plentymarkets ein bestimmtes Versandprofil für die Sperrgut-Versandarten verwenden willst, kannst du im Menü *Einrichtung » Märkte » eBay » Einstellungen » Versandprofilverknüpfungen* die Versandarten einem bestimmten Versandprofil in plentymarkets zuordnen. Öffne dazu das Menü *Einrichtung » Märkte » eBay » Einstellungen » Versandprofilverknüpfungen*, wähle dort die eBay-Plattform und verknüpfe die eBay-Versandprofile, in denen du Sperrgutversand anbietest, mit deinen plentymarkets Versandprofilen.