= Praxisbeispiel: Teillieferungen an limango melden
:author: team-plenty-channel
:keywords: limango, Artikel verschicken, Teillieferung, einen Artikel an limango schicken, limango Teillieferung, Teil Lieferung
:description:

Eine Kundin hat etwas bei limango bestellt, du hast jedoch nicht alle Artikel des Auftrags auf Lager. Nun möchtest du zwei Artikel, die auf Lager sind, bereits an deine Kundin verschicken. In diesem Praxisbeispiel erfährst du, wie das geht und wie du limango darüber informieren kannst, dass eine oder mehrere Positionen eines Auftrags bereits verschickt wurden.

Um nur eine oder mehrere Positionen eines Auftrags zu versenden, erstellst du einen Lieferauftrag für die Positionen, die versendet werden sollen. Danach erstellst du die Ereignisaktion *Versandinformation an limango melden*.

[#lieferauftrag-erstellen]
== Lieferauftrag erstellen

Erstelle als Erstes einen Lieferauftrag für die Auftragspositionen, die versendet werden sollen.

[.instruction]
Lieferauftrag erstellen:

. Öffne das Menü *Aufträge » Aufträge bearbeiten*.
. Öffne den Auftrag, aus dem ein Lieferauftrag erstellt werden soll. +
→ Es handelt sich hierbei um den Auftrag, aus dem eine oder mehrere Auftragspositionen versendet werden sollen.
. Wechsele in das Tab *Lief*.
. Trage in das Feld *LiefAufMenge* (Menge für den Lieferauftrag) die *Menge* ein, die in den Lieferauftrag überführt werden soll.
. Klicke anschließend auf *Lieferauftrag anlegen* (terra:execute[]). +
→ Der Lieferauftrag wird angelegt.

*_Hinweis:_* Wenn alle Positionen eines Auftrags - also der gesamte Auftrag - versendet werden sollen, musst du keinen Lieferauftrag anlegen, sondern kannst einfach den gesamten Auftrag als versendet markieren. +
Lieferaufträge dienen nur dazu, einzelne Positionen eines Auftrags herauszulösen, zum Beispiel wenn einzelne Artikel bereits verschickt oder storniert werden sollen.

[#ereignisaktion-teillieferung]
== Ereignisaktion einrichten

Erstelle nun eine xref:automatisierung:ereignisaktionen.adoc#[Ereignisaktion], um limango über den Versand der Auftragspositionen zu informieren.

*_Hinweis:_* Achte darauf, dass auch Lieferaufträge in der Ereignisaktion berücksichtigt werden, da du zuvor für die Positionen, die versendet werden sollen, Lieferaufträge erstellt hast.

:table-event-procedure: <<#ereignisaktion-teillieferung-limango>>

include::_includes:partial$event-procedure.adoc[]

*_Hinweis:_* Der Status für die Ereignisaktion wurde beispielhaft gewählt. Wähle einen Status, der am besten zu deinem Arbeitsablauf passt. Dazu kannst du einen bereits vorhandenen Status wählen oder einen eigenen Status xref:auftraege:auftraege-verwalten.adoc#1220[erstellen]. +
Beachte, dass mit den hier vorgeschlagenen Ereignissen und Filtern auch alle Positionen in Hauptaufträgen als versendet gekennzeichnet werden.

[[ereignisaktion-teillieferung-limango]]
.Ereignisaktion zum automatischen Melden von Teillieferungen an limango
[cols="1,3,3"]
|===
|Einstellung |Option |Auswahl

| *Ereignis*
| *Auftragsänderung: Warenausgang gebucht*
| 

| *Filter 1*
| *Auftrag > Herkunft*
| *Limango*

| *Aktion*
| *Plugins*
| *Versandinformation an limango melden*
|===