= bol.com
:author: team-plenty-channel
:keywords: bol.com, bol.com, bol, bol, blo, blo.com, BolItemExport, bol.com einrichten, bol.com, bol, Niederlande, Holland, bol.nl
:description: Auf dieser Seite erfährst du, wie du den Marktplatz bol.com in plentymarkets einrichtest, damit du deine Artikel auf bol.com verkaufen kannst.
:bol.com:
:market: bol.com

Der niederländische Online-Marktplatz link:http://bol.com[bol.com^] hat sich zum führenden Online-Marktplatz der Benelux entwickelt und vertreibt eine breite Angebotspalette inklusive Elektronik, Multimedia, Spielzeug etc. Auf bol.com kannst du deine Artikel in den Niederlanden und Belgien verkaufen.

[#210]
== Häufigkeit des Datenaustauschs

Nachdem du die Schnittstelle zu bol.com in plentymarkets eingerichtet hast, stehen die in <<#data-exchange>> gelisteten automatisierten Abläufe bereit.

[[data-exchange]]
.Häufigkeit des Datenaustauschs
[cols="1,1a"]
|===
|Daten |Intervall

| Artikelexport
| einmal täglich

| Bestandsabgleich
| viertelstündlich

| Preisabgleich
| stündlich

| Aktualisieren von Lieferzeiten, Sichtbarkeit der Angebote etc.
| stündlich

| Löschen von Angeboten für gelöschte oder deaktivierte Varianten
| täglich

| Auftragsimport
| viertelstündlich

| Import von auf bol.com angemeldeten Retouren
| stündlich +
*_Hinweis:_* Retouren werden automatisch mit dem Status [9.00] importiert.
|===

[#100]
== Bei bol.com registrieren

Bevor du bol.com in plentymarkets einrichtest, musst du dich auf link:https://bol.com.[bol.com^] als Händler:in registrieren.

[[setup]]
== Marktplatz in plentymarkets einrichten

Die Grundeinstellungen für bol.com nimmst du im Menü *Einrichtung » Assistenten » Omni-Channel* mit dem Assistenten *Grundeinstellungen - bol.com* vor. Mit diesem Assistenten richtest du dein bol.com-Konto in plentymarkets ein. Außerdem nimmst du Einstellungen zu Lagern vor und verknüpfst plentymarkets Lieferzeiten mit Lieferzeiten von bol.com.

:menu-path: pass:quotes[*Einrichtung » Assistenten » Omni-Channel*]
:assistant-name: Grundeinstellungen - bol.com
:number-of-boxes: Info-Box

include::partial$assistant-basic-instructions.adoc[]

[.collapseBox]
.Erläuterungen zu den Optionen des Assistenten
--
[[table-bol-basic-settings-assistant]]
[width="100%"]
[cols="1,2a"]
|======
|Einstellung |Erläuterung

2+^|Schritt *Einstellungen*

| *Unter welchem Mandanten möchtest du deine Artikel verkaufen?*
a| Wähle aus der Dropdown-Liste *Mandant* den Mandanten, der genutzt werden soll, um die Artikel-URL im Katalog zu erzeugen und dem bol.com-Aufträge zugeordnet werden sollen.

| *Möchtest du dein bol.com-Benutzerkonto aktivieren?*
a| material:check_box_outline_blank[] = Die Einstellungen werden gespeichert, der Datenaustausch mit bol.com wird aber noch nicht gestartet. +
material:check_box[] = Der Datenaustausch mit bol.com wird nach Abschluss des Assistenten gestartet. +
*_Empfehlung:_* Aktiviere das Benutzerkonto erst, nachdem du alle Einstellungen geprüft hast.

2+^|Schritt *Zugangsdaten*

| *Wie lauten die API-Zugangsdaten?*
a| Die API-Zugangsdaten erzeugst du im Händlerbereich bei bol.com.

* *Client-ID* (Pflichtangabe) = Gib die Benutzer-ID für die API-Schnittstelle ein, die du von bol.com erhalten hast.
* *Client Secret* (Pflichtangabe) = Gib das Passwort für die API-Schnittstelle ein, das du von bol.com erhalten hast.

2+^|Schritt *Prüfung der Zugangsdaten*

| *Sind die Zugangsdaten korrekt?*
a| Es wird geprüft, ob deine API-Zugangsdaten für bol.com korrekt sind. Im Feld *Status der Zugangsdaten* wird angezeigt, ob die Zugangsdaten korrekt sind. Wenn die Zugangsdaten ungültig sind, gib die Zugangsdaten erneut im Schritt *Zugangsdaten* ein.

2+^|Schritt *Status nach Ereignisaktionen*

| _Auftragsstatus nach Ausführung einer Ereignisaktion wählen_
a| Auftragsstatus festlegen, in den Aufträge wechseln sollen, nachdem eine Ereignisaktion ausgeführt wurde. Wähle jeweils zwei Auftragsstatus: einen Status, in den Aufträge nach einer erfolgreichen Ereignisaktion wechseln sollen und einen Status, in den Aufträge wechseln sollen, wenn die Ereignisaktion fehlgeschlagen ist. Wenn Aufträge ihren Status nach einer Ereignisaktion nicht wechseln sollen, dann wähle *Kein Statuswechsel*. +

Wähle Status für die folgenden Ereignisaktionen: +

* *Stornierung an bol.com senden*
* *Versandbestätigung an bol.com senden*
* *Retourenstatus an bol.com senden*
* *Retoure bei bol.com anlegen*

2+^|Schritt *Lager*

| *Wie sollen die Bestände berechnet werden, welche an bol.com übertragen werden?*
a| Bestandsmenge für den Angebotsexport wählen. Eine der folgenden Optionen wählen:

* *Summe der Bestandsmengen aller Vertriebslager verwenden* +
* *Hauptlager des Artikels verwenden* +
* *Lager auswählen* = Ein oder mehrere Lager wählen. +
→ Die unter *Lager* aufgelisteten Lager können gewählt werden. Häkchen setzen, um ein Lager zu wählen.

*_Wichtig:_* Die Option *Lagerauswahl* beeinflusst den Artikelexport. Wenn ein Artikel nicht mit den hier gewählten Lagern verknüpft ist, wird dieser Artikel nicht exportiert.

2+^|Schritt *Lieferzeiten*

| _bol.com-Lieferzeiten verknüpfen_
| Einer oder mehreren bol.com-Lieferzeiten in plentymarkets gespeicherte Lieferzeiten zuordnen. Die zugeordneten Lieferzeiten werden an deinen Artikeln auf bol.com angezeigt.
|======
--

[#250]
=== Auftragsherkunft aktivieren

:market: bol.com
:referrer: bol.com
:referrer-option: pass:quotes[Option *bol.com* mit der ID *152*]

include::partial$auftragsherkunft-aktivieren.adoc[]

[#500]
=== Verkaufspreis wählen

:referrer-price: bol.com

include::partial$verkaufspreis-festlegen.adoc[]

[#650]
=== Zahlungsart in Kundenklasse erlauben

:market: bol.com
:payment-method: Bol.com

include::partial$zahlungsart_aktivieren.adoc[]

[#versandeinstellungen-bol-com]
=== Einstellungen zum Versand vornehmen

Als Nächstes nimmst du Versandeinstellungen für bol.com vor. Dazu speicherst du die Namen der Versanddienstleister für bol.com auf Niederländisch und aktivierst die Auftragsherkunft *bol.com* in den Versandprofilen, die du für bol.com nutzen möchtest.

[#versanddienstleister-bol-com]
==== Namen für Versanddienstleister auf Niederländisch hinterlegen

Bei bol.com muss als Name des xref:fulfillment:versand-vorbereiten.adoc#800[Versanddienstleisters] ein von bol.com vorgegebener link:https://api.bol.com/retailer/public/Retailer-API/v6/functional/orders-shipments.html#_transporters[API transporter code^] eingegeben werden. Außerdem muss der Name des Versanddienstleisters auf Niederländisch gespeichert werden. Diese Einstellungen nimmst du im Menü *Einrichtung » Aufträge » Versand » Optionen* vor.

[.instruction]
Namen für Versanddienstleister hinterlegen:

. Öffne das Menü *Einrichtung » Aufträge » Versand » Optionen*.
. Wechsele in das *Tab: Versanddienstleister*.
. Wähle im Bereich *Filter* aus der Dropdown-Liste *Sprache* die Sprache *nl*.
. Klicke auf *Suchen* (icon:search[role="blue"]). +
→ Die Versanddienstleister werden angezeigt.
. Gib im Eingabefeld *Name (nl)* den *API transporter code* für alle Versanddienstleister ein, die du für bol.com verwenden möchtest. +
*_Tipp:_* Die *API transporter codes* für die Versanddienstleister findest du in der link:https://api.bol.com/retailer/public/Retailer-API/v6/functional/orders-shipments.html#_transporters[Entwicklerdokumentation von bol.com^].
. Speichere (terra:save[]) die Einstellungen. +
→ Die niederländischen Namen der Versanddienstleister für bol.com wurden hinterlegt.

[#550]
==== Herkunft in Versandprofilen aktivieren

:referrer: bol.com

include::partial$shipping-profile-activate.adoc[]

[TIP]
.Versanddienstleister auf Niederländisch hinterlegen
====
Achte darauf, dass die <<#versanddienstleister-bol-com, Namen der Versanddienstleister>> in den Versandprofilen für bol.com auf Niederländisch mit den von bol.com vorgegebenen link:https://api.bol.com/retailer/public/Retailer-API/v6/functional/orders-shipments.html#_transporters[API transporter codes^] gespeichert sind.
====

[#600]
== Artikelexport einrichten

Artikeldaten werden über Kataloge zu bol.com exportiert. Mit dem Assistenten *Kataloge erstellen - bol.com* erstellst du ein Marktplatz-Format pro bol.com-Kategorie.

include::partial$catalogue-new-to-text.adoc[]

[#create-catalogue]
=== Katalog mit dem Assistenten erstellen

Pro Kombination aus bol.com-Kategorie und Sprache benötigst du einen eigenen Katalog. +
*_Tipp:_* Im Katalog wird die Sprache in Klammern hinter der Kategorie angezeigt.

:catalogue-assistant-name: Kataloge erstellen - bol.com
:number-of-boxes: Info-Box
:catalogue-path: pass:quotes[*Einrichtung » Assistenten » Omni-Channel*]
:catalogue-note: Pro Kombination aus bol.com-Kategorie und Sprache benötigst du einen eigenen Katalog.
:mapping-fields: die

include::partial$catalogue-assistant-config.adoc[]

[.collapseBox]
.Einstellungen im Assistenten
--
[[table-catalogue-assistant]]
[width="100%"]
[cols="1,2a"]
|===
| Einstellung | Erläuterung

| *Wähle eine Kategorie für deinen Katalog aus.*
| Eine Produktkategorie aus der Dropdown-Liste wählen. +
*_Tipp:_* Gib ein paar Buchstaben des Kategorienamens ein, um Vorschläge zu erhalten. +
→ Im Menü *Daten » Kataloge* wird der Katalog unter dem Namen der Kategorie angezeigt. +
*_Hinweis:_* Für jede Kombination aus bol.com-Kategorie und Sprache benötigst du einen eigenen Katalog.
|===
--

[#data-field-mappings]
=== Datenfelder im Katalog zuordnen

Nachdem du einen Katalog erstellt hast, ordnest du die Datenfelder des Marktplatzes den in plentymarkets gespeicherten Artikeldaten zu. Informationen dazu, welche Daten für welches Datenfeld des Marktplatzes übertragen werden müssen, findest du in der Dokumentation des Marktplatzes.

include::partial$catalogue-mapping.adoc[]

////
[#special-mappings]
=== Besonderheiten bei der Zuordnung von Datenfeldern

Jeder Marktplatz strukturiert Artikeldaten anders. Deshalb treten beim Zuordnen von Datenfeldern bestimmte Sonderfälle auf. In <<#special-mappings>> findest du Hinweise dazu, was du beim Zuordnen von Datenfeldern für diesen Marktplatz beachten solltest.

[[special-mappings]]
.Besonderheiten bei der Katalogzuordnung
[cols="1,3a"]
|===
| Marktplatz-Datenfeld | plentymarkets Datenfeld

| *bol_used*
| Wenn du gebrauchte Produkte über bol.com verkaufen möchtest, gibst du den gebrauchten Zustand von Varianten über die Eigenschaft *bol_used* an.

* _Eigenschaft ist nicht mit Variante verknüpft_ = Variante ist neu.
* _Eigenschaft ist mit Variante verknüpft_ = Variante ist gebraucht.

*_Tipp:_* Du bietest nur gebrauche Ware oder nur neue Ware an? Dann kannst du den Zustand auch als eigenen Wert eingeben. Ordne dazu statt der Eigenschaft *bol_used* das Feld *Eigener Wert* zu und gib einen Wert in das Feld ein.

* Eigener Wert `0` oder `false` oder `n` = Alle Varianten sind neu.
* Eigener Wert `1` oder `true` oder `y` = Alle Varianten sind gebraucht.

|===
////

[#prepare-variations]
== Varianten vorbereiten

Bereite nun deine Varianten vor.

[#mandatory-info]
=== Pflichtangaben ergänzen

Damit deine Varianten als Angebote auf bol.com gelistet werden können, musst du mindestens die in <<#table-bol-variation-checklist>> beschriebenen Einstellungen an den Varianten pflegen.

[[table-bol-variation-checklist]]
.Pflichtfelder an der Variante
[cols="1,3a"]
|===
| Pflichtdaten | Erläuterung

| EAN oder ISBN
a| Für die Variante muss eine EAN oder eine ISBN gespeichert sein.

* Im Menü *Einrichtung » Artikel » Barcode* muss eine EAN oder ISBN eingerichtet und mit der Herkunft bol.com verknüpft sein.
* Die EAN/ISBN muss im Tab *Einstellungen* der Variante im Bereich *Barcode* hinzugefügt und ein Barcode-Code eingegeben werden.

| Preis
a| Für die Variante muss ein Preis gespeichert sein.

* Der Verkaufspreis muss im Menü *Einrichtung » Artikel » Verkaufspreise* für die Herkunft bol.com aktiviert sein.
* Der Verkaufspreis muss im Tab *Einstellungen* einer Variante im Bereich *Verkaufspreise* hinzugefügt werden.
* Für den Verkaufspreis muss im Tab *Einstellungen* einer Variante im Bereich *Verkaufspreise* ein Preis gespeichert sein.

| Name
a| An der Variante muss ein Name in der Sprache des Ziellandes gespeichert sein. +
*_Beispiel:_* Wenn du deine Artikel in den Niederlanden verkaufen möchtest, muss ein Name in der Sprache Niederländisch gespeichert sein.

* Für die Variante muss ein Name in dem plentymarkets Datenfeld gespeichert sein, das du dem Marktplatz-Datenfeld für den Namen zugeordnet hast.

| Artikelbeschreibung
a| An der Variante muss eine Beschreibung in der Sprache des Ziellandes gespeichert sein. +
*_Beispiel:_* Wenn du deine Artikel in den Niederlanden verkaufen möchtest, muss eine Beschreibung in der Sprache Niederländisch gespeichert sein.

* Für die Variante muss eine Beschreibung in dem plentymarkets Datenfeld gespeichert sein, das du dem Marktplatz-Datenfeld für die Beschreibung zugeordnet hast.

| Hersteller
a| An der Variante muss eine Hersteller:in gespeichert sein.

* Für die Variante muss eine Hersteller:in in dem plentymarkets Datenfeld gespeichert sein, das du dem Marktplatz-Datenfeld für die Hersteller:in zugeordnet hast.

| Bild
a| Die Variante muss mindestens ein Bild haben.

* Im Tab *Bilder* der Variante muss mindestens ein Bild verknüpft sein.
* Im Tab *Bilder* des Artikels muss in der Dropdown-Liste *Verfügbarkeit* die Option *{market}* aktiviert sein.

| Eigenschaftswert für bol.com-Kategorie
a| Die Variante muss mit dem Eigenschaftswert für die bol.com-Kategorie verknüpft sein. Die Eigenschaft *bol.com-Kategorie* wird automatisch erstellt, wenn du den Assistenten abschließt.

* Im Tab *Eigenschaften* der Variante muss im Bereich *Varianteneigenschaften* der Eigenschaftswert für die bol.com-Kategorie verknüpft sein. Der Eigenschaftswert hat denselben Namen wie die bol.com-Kategorie und der Katalog.

| Verfügbarkeit
a| Die Variante muss für den Marktplatz freigegeben sein.

* Im Tab *Verfügbarkeit* der Variante muss im Bereich *Märkte* die Marktplatzverfügbarkeiten *bol.com* oder *bol.com FBB* aktiviert werden. +
  ** Herkunft *bol.com* = Du versendest deine Artikel selbst. +
  ** Herkunft *bol.com FBB* = Der Versand erfolgt durch bol.com.

| Zustand
| * Im Tab *Global* des Artikels muss im Bereich *Grundeinstellungen* der *Zustand API* gespeichert sein. Dieser *Zustand API* wird beim Export der Angebotsdaten automatisch übertragen.

Die plentymarkets Zustände werden wie folgt den bol.com-API-Zuständen zugeordnet:

* *0 Neu* = NEW
* *1 Gebraucht wie neu* = AS_NEW
* *2 Gebraucht sehr gut* = GOOD
* *3 Gebraucht gut* = MODERATE
* *4 Gebraucht annehmbar* = REASONABLE

|===

[#link-category-property]
=== Varianten mit Eigenschaftswert der bol.com-Kategorie verknüpfen

Nachdem du mit dem Assistenten das erste Marktplatz-Format für bol.com erstellt hast, wird in deinem plentymarkets System die Eigenschaft *bol.com-Kategorie* erstellt. Für jede bol.com-Kategorie, für die du einen Katalog erstellst, wird ein neuer Auswahlwert zu dieser Eigenschaft *bol.com-Kategorie* hinzugefügt. Dieser Auswahlwert hat denselben Namen wie die bol.com-Kategorie und der Katalog.

Damit deine Varianten im gewünschten Katalog exportiert werden, müssen sie im *Tab: Eigenschaften* einer Variante mit der Eigenschaft *bol.com-Kategorie* verknüpft werden.

[.instruction]
Variante mit bol.com-Kategorie verknüpfen:

. Öffne das Menü *Artikel » Artikel bearbeiten » [Artikel öffnen]*.
. Wechsele in das *Tab: Varianten*.
. Öffne die Variante, die du verknüpfen möchtest.
. Wechsele in das *Tab: Eigenschaften*.
. Wähle im Bereich *Varianteneigenschaften* aus der Dropdown-Liste *Eigenschaften* die Eigenschaft *bol.com-Kategorie* und klicke auf *Hinzufügen* (icon:plus-square[role="green"]). +
→ Die Eigenschaft wird hinzugefügt.
. Wähle für die Eigenschaft *bol.com-Kategorie* aus der Dropdown-Liste *Wert* die gewünschte Kategorie. +
→ Die Variante wird im zugehörigen Katalog exportiert.
. Speichere (terra:save[]) die Einstellungen.

[#300]
=== Varianten für Marktplatz freigeben

:market-availability: bol.com
:option-availability: bol.com

include::partial$variantenverfuegbarkeit.adoc[]

// Web-API NICHT erforderlich!

[#211]
=== _Optional:_ Varianten für Fulfillment by bol.com (FBB/LVB) freigeben

Das Fulfillment kann für Bestellungen auf bol.com auf zwei Arten abgewickelt werden:

* Fullfilment by Retailer (FBR) = Du versendest deine Ware selbst.
* Fullfilment by bol.com (FBB/LVB) = bol.com versendet deine Ware.

Beachte, dass plentymarkets Fullfilment by bol.com nur eingeschränkt unterstützt. Du kannst deine Artikeldaten zwar für Fullfilment by bol.com zu dem Marktplatz exportieren. FBB-Aufträge und FBB-Retouren werden aber nicht in plentymarkets importiert. Auch ein Bestandsableich zwischen dem bol.com-Fulfillment-Lager und plentymarkets ist nicht möglich.

Um eine Variante über Fullfilment by bol.com (FBB oder LVB) zu verkaufen, muss die Marktplatzverfügbarkeit *bol.com FBB* an der Variante aktiviert sein.

[.collapseBox]
.Marktplatzverfügbarkeit *bol.com FBB* an der Variante aktivieren
--
. Öffne das Menü *Artikel » Artikel bearbeiten » [Artikel öffnen] » [Variante öffnen]*. +
→ Das Tab *Einstellungen* der Variante wird geöffnet.
. Wechsele in das Tab *Verfügbarkeit*.
. Klicke im Bereich *Märkte* in das Auswahlfeld. +
→ Eine Liste mit allen verfügbaren Märkten wird angezeigt.
. Aktiviere die Option *bol.com FBB*.
. Speichere (terra:save[]) die Einstellungen.
--

[#automate-orders]
== Auftragsabwicklung automatisieren

Richte xref:automatisierung:ereignisaktionen.adoc#[Ereignisaktionen] ein, um bol.com automatisch über Änderungen des Auftragsstatus zu informieren. Für bol.com sind die folgenden Ereignisaktionen stehen verfügbar:

* Versandbestätigungen an bol.com senden (<<#700, Wie?>>)
* Stornierung an bol.com senden (<<#900, Wie?>>)
* Retourenstatus an bol.com senden (<<#800, Wie?>>)
* Retoure bei bol.com anlegen (<<#810, Wie?>>)

[#700]
=== Versandbestätigungen automatisch senden

Richte eine xref:automatisierung:ereignisaktionen.adoc#[Ereignisaktion] ein, um Versandbestätigungen automatisch an bol.com zu senden, nachdem ein Warenausgang gebucht wurde.

:table-event-procedure: <<#ereignisaktion-versandbestätigung-bol>>

include::_includes:partial$event-procedure.adoc[]

[[ereignisaktion-versandbestätigung-bol]]
.Ereignisaktion zum automatischen Senden von Versandbestätigungen an bol.com
[cols="1,3,3"]
|===
|Einstellung |Option |Auswahl

| *Ereignis*
| *Auftragsänderung: Warenausgang gebucht*
|

| *Filter 1*
| *Auftrag &gt; Auftragstyp*
| *Auftrag*

| *Filter 2*
| *Auftrag &gt; Herkunft*
| *bol.com*

| *Aktion*
| *Versand &gt; Versandbestätigung an bol.com senden*
|
|===

[#900]
=== Stornierungen automatisch senden

Richte eine xref:automatisierung:ereignisaktionen.adoc#[Ereignisaktion] ein, um bol.com automatisch über Stornierungen zu informieren. Bei Stornierungen muss ein Grund für die Stornierung an bol.com übertragen werden. Erstelle im Menü *Einrichtung » Aufträge » Auftragsstatus* bei Bedarf zusätzliche Auftragsstatus. Folgende Stornierungsgründe können an bol.com übertragen werden:

* *Nicht vorrätig*
* *Stornierung von Kunde angefragt*
* *Artikel in schlechtem Zustand*
* *Höhere Versandkosten*
* *Falscher Preis*
* *Nicht rechtzeitig lieferbar*
* *Keine Garantie durch bol.com*
* *Artikel doppelt bestellt*
* *Artikel züruckbehalten*
* *Technisches Problem*
* *Artikel nicht auffindbar*
* *Sonstiges*

:table-event-procedure: <<#ereignisaktion-stornierungen-bol>>

include::_includes:partial$event-procedure.adoc[]

[[ereignisaktion-stornierungen-bol]]
.Ereignisaktion zum automatischen Senden von Stornierungen an bol.com
[cols="1,3,3"]
|===
|Einstellung |Option |Auswahl

| *Ereignis*
| *Auftragsänderung: Statuswechsel*
| *[8.1] Storniert durch Kunden*

| *Filter 1*
| *Auftrag &gt; Auftragstyp*
| *Auftrag*

| *Filter 2*
| *Auftrag &gt; Herkunft*
| *bol.com*

| *Aktion*
| *Auftrag &gt; Stornierung an bol.com senden*
| *Stornierung durch Kunden*
|===

[#800]
=== Retourenstatus automatisch senden

Richte eine xref:automatisierung:ereignisaktionen.adoc#[Ereignisaktion] ein, um bol.com automatisch über den Status einer Retoure zu informieren. Bei Retouren muss ein Status an bol.com übertragen werden. Folgende Retourenstatus können an bol.com übertragen werden:

* *Retoure erhalten*
* *Artikel wird umgetauscht*
* *Retoure entspricht nicht den Anforderungen*
* *Artikel muss repariert werden*
* *Kunde behält Ware*
* *Retoure in Rücksprache mit Kunde angenommen*

:table-event-procedure: <<#ereignisaktion-retourenstatus-bol>>
:ea-queue:

include::_includes:partial$event-procedure.adoc[]
:!ea-queue:

[[ereignisaktion-retourenstatus-bol]]
.Ereignisaktion zum automatischen Senden von Retourenstatus an bol.com
[cols="1,3,3"]
|===
|Einstellung |Option |Auswahl

| *Ereignis*
| *Neue Retoure*
|

| *Filter 1*
| *Auftrag &gt; Auftragstyp*
| *Retoure*

| *Filter 2*
| *Auftrag &gt; Herkunft*
| *bol.com*

| *Aktion*
| *Auftrag &gt; Retourenstatus an bol.com senden*
|Wähle einen Status.
|===

[#810]
=== bol.com über direkte Retouren informieren

Richte zusätzlich eine xref:automatisierung:ereignisaktionen.adoc#[Ereignisaktion] ein, um bol.com automatisch über Retouren zu informieren, die Kund:innen direkt an dich zurückgesendet haben, ohne die Retoure vorher bei bol.com angemeldet zu haben. Bei Retouren muss ein Status an bol.com übertragen werden. Folgende Retourenstatus können an bol.com übertragen werden:

* Retoure erhalten
* Artikel wird umgetauscht
* Retoure entspricht nicht den Anforderungen
* Artikel muss repariert werden
* Kunde behält Ware
* Retoure in Rücksprache mit Kunde angenommen

:table-event-procedure: <<#ereignisaktion-retouren-bol>>

include::_includes:partial$event-procedure.adoc[]

[[ereignisaktion-retouren-bol]]
.Ereignisaktion, um bol.com über Retouren zu informieren
[cols="1,3,3"]
|===
|Einstellung |Option |Auswahl

| *Ereignis*
| *Auftragsänderung: Statuswechsel*
| *[9.5] Gutschrift angelegt*

| *Filter 1*
| *Auftrag &gt; Auftragstyp*
| *Retoure*

| *Filter 2*
| *Auftrag &gt; Herkunft*
| *bol.com*

| *Aktion*
| *Auftrag &gt; Retoure bei bol.com anlegen*
| Wähle einen Status.
|===

[#activate-catalogue]
== Artikelexport starten: Katalogexport aktivieren

:interval: einmal täglich nachts

include::partial$catalogue-activation.adoc[]

[#troubleshooting]
== Fehlersuche

[#1200]
=== _Checkliste:_ Warum wird meine Variante nicht exportiert?

include::partial$checklist-variations.adoc[tag=checklist-intro]

include::partial$checklist-variations.adoc[tag=checklist-variation-referrer]

include::partial$checklist-variations.adoc[tag=checklist-variation-active]

include::partial$checklist-variations.adoc[tag=checklist-availability-active]

include::partial$checklist-variations.adoc[tag=checklist-net-stock]

include::partial$checklist-variations.adoc[tag=checklist-sales-price]

:anchor-catalogue-mapping: #map-data-fields

include::partial$checklist-variations.adoc[tag=checklist-catalogue-mapped-multi]

include::partial$checklist-variations.adoc[tag=checklist-categories-bol]

include::partial$checklist-variations.adoc[tag=checklist-catalogue-active]

:checklist-log-integration: pass:quotes[*bol.com*]
:checklist-log-reference: pass:quotes[*Plenty\Modules\bol.com\Item\Services\ItemExportService*]

include::partial$checklist-variations.adoc[tag=checklist-check-log]

[#1000]
=== Log-Einträge abrufen

:market: bol.com
include::partial$logs_abrufen.adoc[tag=data-log-intro]

* *Identifikator* » *bol.com*

include::partial$logs_abrufen.adoc[tag=data-log-config]

Nutze optional die in <<#tabelle-referenztypen>> aufgeführten Referenztypen und Referenzwerte, um die Suchergebnisse weiter einzugrenzen:

[[tabelle-referenztypen]]
.Referenztypen und Referenzwerte für bol.com
[cols="1,1,3"]
|===
|Referenztyp |Erläuterung |Referenzwerte

| *action*
| Filtert nach Ereignissen.
a| Wähle einen Referenzwert, um nach bestimmten Ereignissen zu suchen. +

* *orderImport* = Auftragsimport +
* *CreateOffer* = Angebotserstellung +
* *CheckOfferStatus* = Prüfung des erfolgreichen Erstellens von Angeboten +
* *DeleteOffer* = Löschung von Angeboten +
* *UpdateOffer* = Aktualisierungen der Lieferzeit, des Liefertyps (FBB, FBR), der SKU und des Aktivitätsstatus von Angeboten +
* *UpdateOfferPrices* = Aktualisierungen von Preisen der Angebote +
* *UpdateOfferStock* = Aktualisierungen von Beständen der Angebote +
* *CancelOrder* = Stornierung des Auftrags +
* *ShipOrder* = Versand des Auftrags +
* *HandleReturn* = Eingang einer auf bol.com gemeldeten Retoure bestätigen +
* *CreateReturn* = Eingang einer nicht auf bol.com gemeldeten Retoure melden

| *orderId*
| Filtert nach der Auftrags-ID des Auftrags in plentymarkets.
|

| *externalOrderId*
| Filtert nach der Auftragsnummer des Auftrags bei bol.com.
|

| *externalOrderItemId*
| Filtert nach der ID der Auftragsposition bei bol.com.
|
|===
