= Decathlon
:keywords: Decathlon, Decatlon, Dekatlon, Decathlom
:description: Auf dieser Seite erfährst du, wie du Decathlon in plentysystems einrichtest, damit du deine Artikel auf Decathlon verkaufen kannst. Decathlon ist ein Marktplatz für Sportbekleidung und -ausrüstung.
:author: team-plenty-channel

:market: Decathlon
:decathlon:

link:https://www.decathlon.de/[Decathlon^] ist ein Marktplatz, auf dem Produkte rund um Sport und Fitness angeboten werden, wie Sportbekleidung, Sportausrüstung und Accessoires.

[#partnerprogramm]
== Partner:in bei Decathlon werden

Registriere dich zunächst für das link:https://www.decathlon.de/landing/marketplace-marktplatz-partnerprogramm/_/R-a-marketplace[Partnerprogramm^] von Decathlon, um Artikel auf dem Marktplatz anbieten zu können.

Nach der Registrierung erhältst du Zugangsdaten für Decathlon. Diese Zugangsdaten benötigst du, um Decathlon in plentysystems einzurichten.

[#datenaustausch-intervall]
== Häufigkeit des Datenaustauschs

Nachdem du Decathlon in plentysystems eingerichtet hast, findet der Datenaustausch in den in <<#tabelle-datenaustausch-intervall>> beschriebenen Intervallen statt:

[[tabelle-datenaustausch-intervall]]
.Häufigkeit des Datenaustauschs
[cols="2,3a"]
|===
|Daten |Intervall

| Artikelexport
| einmal täglich

| vollständiger Angebotsexport (Anlegen + Aktualisieren von Angeboten)
| einmal täglich

| Bestandsabgleich
| alle 15 Minuten

| Preisabgleich
| stündlich

| Auftragsimport
| alle 15 Minuten

| Importieren von Erstattungen
| alle 15 Minuten
|===

[#bestellung]
== Ablauf einer Bestellung

* Deine Artikel werden bei Decathlon gelistet. Der Name deines Unternehmens wird an deinen Artikeln angezeigt.
* Kund:innen geben eine Bestellung auf Decathlon auf.
* Kund:innen zahlen an Decathlon.
* Der Auftrag wird in plentysystems importiert.

[#marktplatz-einrichten]
== Marktplatz in plentysystems einrichten

Richte nun den Marktplatz in plentysystems ein.

[TIP]
.In welchen Ländern kann ich meine Artikel anbieten?
====
Auf Decathlon kannst du deine Artikel in Deutschland, Belgien, Frankreich, Großbritannien, Italien, den Niederlanden, Polen, Portugal, Rumänien, der Schweiz, Spanien, Tschechien und Ungarn verkaufen. Aktiviere dazu die <<#auftragsherkunft, Auftragsherkünfte>> für alle Decathlon-Länderplattformen, auf denen du verkaufen willst.
====

[#konto-uebersicht]
=== Konto-Übersicht

Im Menü *Einrichtung » Märkte » Decathlon » Einstellungen* erhältst du eine Übersicht über deine Decathlon-Konten. In <<tabelle-konto-uebersicht>> sind die einzelnen Spalten und verfügbaren Aktionen der Konto-Übersicht beschrieben.

[TIP]
.Spalten konfigurieren
====
Über *Spalten konfigurieren* (material:settings[]) kannst du festlegen, welche Einstellungen in der Konto-Übersicht angezeigt werden sollen. +
Standardmäßig werden die Spalten *ID*, *Name*, *Aktiv*, *Mandant*, *Auftragsimport*, *Artikelexport* und *Angebotsexport* in der Übersicht angezeigt.
====

*_Hinweis:_* Die Konto-Übersicht sieht unterschiedlich aus, je nachdem, welche Spalten du über *Spalten konfigurieren* (material:settings[]) in der Übersicht hinzufügst oder ausblendest. In der folgenden Tabelle sind nur die Spalten beschrieben, die standardmäßig in der Übersicht angezeigt werden.

[[tabelle-konto-uebersicht]]
.Decathlon Konto-Übersicht
[cols="1a,3a"]
|===
|Spalte |Erläuterung

| *ID*
| Die ID deines Decathlon-Kontos. Die ID wird automatisch vergeben, wenn du ein neues Konto erstellst.

| *Name*
| Der Name deines Decathlon-Kontos.

| *Aktiv*
| material:circle[role="blue"] = Das Konto ist aktiv und Daten werden mit Decathlon ausgetauscht. +
material:circle[] = Das Konto ist nicht aktiv. Es findet kein Datenaustausch mit Decathlon statt. +

*_Hinweis:_* Der Datenaustausch mit Decathlon funktioniert nur, wenn das Konto mit Decathlon verbunden und *aktiv* geschaltet ist. Dazu muss ein *API-Schlüssel* gespeichert sein. Um eine Verbindung zu Decathlon herzustellen, klicke auf *Verbindung testen*.

| *Mandant*
| Der Mandant (plentyShop), dem die Aufträge dieses Decathlon-Kontos zugeordnet werden.

| *Auftragsimport*
| material:done[role="blue"] = Der Auftragsimport ist für dieses Konto aktiviert. Aufträge werden alle 15 Minuten in plentysystems importiert. +

material:close[] = Aufträge werden nicht importiert.

| *Artikelexport*
| material:done[role="blue"] = Der Artikelexport ist für dieses Konto aktiviert. Artikel werden einmal täglich zu Decathlon exportiert.

material:close[] = Artikel werden nicht exportiert.

| *Angebotsexport*
| material:done[role="blue"] = Der Angebotsexport ist für dieses Konto aktiviert. Einmal täglich findet ein vollständiger Angebotsexport statt, d.h. neue Angebote werden erstellt und bestehende Angebote werden aktualisiert. +
Bestände werden alle 15 Minuten exportiert. +
Preise werden stündlich aktualisiert. +

material:close[] = Angebote werden nicht exportiert.

| material:more_vert[] *Mehr*
| Hier klicken, um weitere Aktionen anzuzeigen. +

[cols="1,3a"]
!===
! material:delete[] *Konto löschen*
! Konto löschen.
!===
|===

[#grundeinstellungen]
=== Grundeinstellungen vornehmen

Nimm zunächst im Menü *Einrichtung » Märkte » Decathlon » Einstellungen* die Grundeinstellungen für den Marktplatz vor.

Füge als erstes ein neues Konto für Decathlon hinzu.

[.instruction]
Konto hinzufügen:

. Öffne das Menü *Einrichtung » Märkte » Decathlon » Einstellungen*.
. Klicke auf *Konto hinzufügen* (material:add[]). +
→ Das Fenster *Konto hinzufügen* wird geöffnet.
. Gib einen *Kontonamen* ein.
. Speichere (terra:save[]) die Einstellungen. +
→ Eine Ansicht mit Kontoeinstellungen wird geöffnet.
. Nimm die weiteren Einstellungen vor. Beachte dazu die Erläuterungen in <<#einstellungen-decathlon>>.
. Speichere (terra:save[]) die Einstellungen.

[[einstellungen-decathlon]]
.Einstellungen des Marktplatzes Decathlon
[cols="1,3a"]
|===
|Einstellung |Erläuterung

| *Verbindung testen*
| Klicke hier, um zu testen, ob die Verbindung zu Decathlon hergestellt werden konnte. In diesem Schritt wird der API-Schlüssel überprüft. +

Wenn der API-Schlüssel geändert wird, muss die Verbindung erneut getestet werden.

2+| Allgemein

| *Konto*
| Der Name deines Decathlon-Kontos. Den Namen hast du beim Erstellen des Kontos eingegeben.

| *Aktiv*
| Decathlon-Konto aktivieren. Der Datenaustausch mit Decathlon wird gestartet. +

Wir empfehlen, das Konto erst zu aktivieren, nachdem du alle Einstellungen vorgenommen hast.

*_Hinweis:_* Damit Daten zwischen plentysystems und Decathlon ausgetauscht werden können, muss das Konto mit einem Decathlon-Konto verbunden sein. Dazu muss der *Decathlon API-Schlüssel* in plentysystems eingetragen sein.

| *Decathlon API-Schlüssel*
| API-Schlüssel eintragen. Den API-Schlüssel erhältst du von Decathlon.

| *Mandant*
| Mandant (plentyShop) wählen, dem die Aufträge dieses Decathlon-Kontos zugeordnet werden sollen.

2+| Artikel

| *Artikelexport*
| Aktivieren, um Artikel einmal täglich zu Decathlon zu exportieren. +
*Hinweis:_* Informationen zum Einrichten überzeugender, qualitativ hochwertiger und konsistenter Artikellistings findest Du unter *Decathlon Produkt-Vorgaben ansehen* mit Klick auf (material:more_vert[]) neben (material:save[])
| *Versandprofile verknüpfen*
| Ordne deinen Versandprofilen in plentysystems die Versandprofile von Decathlon aus der Dropdown-Liste zu. +
*Hinweis:_* Klicke auf (material:refresh[]) um die Versandregionen zu aktualisieren.


[.instruction]
Versandprofile verknüpfen:

. Wähle die *Versandregion* aus der Dropdown-Liste. +
*Hinweis:_* Die Erstellung einer *Standardzuordnung* ist Pflicht um Auftragbezogene Störungen zu vermeiden. Definiere einen Fallback für nicht zugeordnete Versandregionen.
. Klicke auf *Verknüpfungen für die gewählte Versandregion anzeigen*. +
→ Eine neue Ansicht zum Verknüpfen von Versandprofilen wird geöffnet. +
*_Hinweis:_* Deine Änderungen an den Einstellungen werden nicht gespeichert. Um deine Änderungen zu speichern, klicke links oben im Fenster auf *Speichern* (terra:save[]), bevor du die Versandprofile verknüpfst.
. Klicke auf *Verknüpfung hinzufügen*. +
→ Das Fenster *Neue Versandprofilverknüpfung hinzufügen* wird geöffnet.
. Wähle die *Decathlon-Versandmethode*.
. Wähle das *plentysystems Versandprofil*.
. Wähle den *Decathlon-Versanddienstleister*.
. Klicke auf terra:save[] *Speichern*. +
→ Die neue Verknüpfung wird im Menü angezeigt. +
*_Tipp:_* Du kannst die Versandprofilverknüpfungen später noch bearbeiten. Klicke dazu auf *Mehr* (material:more_vert[]) und dann auf *Verknüpfung bearbeiten* (material:edit[]).

2+| Aufträge

| *Auftragsimport*
| Aktivieren, um Aufträge von Decathlon alle 15 Minuten in plentysystems zu importieren. +
*_Hinweis:_* Jeder in plentysystems importierte Auftrag wird abgerechnet. +
*Hinweis:_* Wenn der Toggle *Auftragsimport* auf *An* ist, sind Statuszuordnungen für *bereits versendete Aufträge, Gutschriften* und *Stornierte Aufträge* Pflicht. +

| *Auftragsimport Startdatum*
| Datum im Format *D.M.YYYY* eingeben oder über den Kalender (material:today[]) wählen. +
Es werden nur Aufträge ab diesem Datum in plentysystems importiert. Aufträge, die früher generiert wurden, werden nicht importiert. +
*Hinweis:_* Bei der Kontoerstellung wird das *Auftragsimport Startdatum* automatisch mit dem aktuellen Datum befüllt. Um alte Aufträge zu importieren, gib ein benutzerdefiniertes Startdatum an.

| *Stornierungen für Aufträge mit Rechnung erlauben*
| Sollen Stornierungen auch noch möglich sein, wenn bereits eine Rechnung für den Auftrag generiert wurde?

| *Erstattete Aufträge automatisch stornieren bis Status*
| Auftragsstatus wählen, bis zu dem Aufträge, die vollständig erstattet wurden, automatisch storniert werden sollen. Aufträge werden nur bis zu diesem Status oder einem niedrigeren Status storniert. Ab einem höheren Status wird eine Erstattung für den Auftrag angelegt. +

*_Tipp:_* Wähle hier einen Status, in dem du sicherstellen kannst, dass der Auftrag nicht mehr verschickt wird. Aufträge, die bereits verschickt wurden, können nicht mehr storniert werden.

| *Auftragsstatus für bereits versendete Aufträge*
| Mit welchem xref:auftraege:order-statuses.adoc#preselected-statuses[Auftragsstatus] sollen Aufträge importiert werden, die bereits versendet wurden?

| *Auftragsstatus für Gutschriften*
| Mit welchem xref:auftraege:order-statuses.adoc#preselected-statuses[Auftragsstatus] sollen Aufträge importiert werden, die von Decathlon erstattet wurden?

| *Auftragsstatus für stornierte Aufträge*
| Mit welchem xref:auftraege:order-statuses.adoc#preselected-statuses[Auftragsstatus] sollen Aufträge importiert werden, die storniert wurden? +

*_Tipp:_* Wähle einen Status höher als *Status 8*.

2+| Angebote

| *Angebotsexport*
| Aktivieren, um Angebote einmal täglich zu Decathlon zu exportieren. +
Ein vollständiger Angebotsexport findet einmal täglich statt, d.h. es werden neue Angebote erstellt und bestehende Angebote auf Decathlon aktualisiert. +
Bestände werden alle 15 Minuten exportiert. +
Preise werden stündlich aktualisiert. +

2+| Fulfillment by Decathlon

| *FBD*
| Lagere die Auftragsabwicklung an Decathlon aus. Deine Produkte werden von Decathlon gelagert und versendet.

| *FBD aktivieren* anschalten 
| Wenn der Toggle *FBD aktivieren* Schalter auf *An* steht werden der Warenbestandsabgleich und die Auftragsabwicklung von Decathlon verwaltet. Das zugewiesene Lager wird zur Synchronisierung Deines Warenbestands verwendet (Decathlon &rarr; plentysystems).

| *FBD Aktivieren* ausschalten
| Durch Deaktivieren dieser Option ändert sich das Verhalten aller Decathlon-bezogenen Importe und Exporte. Fahre nur fort, wenn du dir sicher bist, dass deine Vereinbarung mit Decathlon diesen Schritt ermöglicht.
|===

[#auftragsherkunft]
=== Auftragsherkunft aktivieren

:decathlon:

:referrer: Decathlon
:referrer-option: pass:quotes[gewünschten Decathlon-Plattform, zum Beispiel *Decathlon Germany*]

include::partial$auftragsherkunft-aktivieren.adoc[]

[#varianten-vorbereiten]
== Varianten vorbereiten

Bereite nun deine Varianten vor.

[#varianten-verfuegbarkeit]
=== Variantenverfügbarkeit einstellen

:market-availability: Decathlon
:option-availability: Decathlon

include::partial$variantenverfuegbarkeit.adoc[]

[#artikel-exportieren]
== Artikeldaten exportieren

Artikeldaten werden über Kataloge zu Decathlon exportiert. Kataloge für Decathlon erstellst du im Menü *Daten » Kataloge*.

include::partial$catalogue-new-to-text.adoc[]

[#produktkategorien-hinzufuegen]
=== Produktkategorien hinzufügen

Bevor du Kataloge für Decathlon erstellst, musst du im Menü *Einrichtung » Märkte » Decathlon » Katalog-Vorlagen hinzufügen* die Produktkategorien hinzufügen, in denen du deine Artikel auf Decathlon anbieten möchtest. +
Wenn du im Menü *Katalog-Formate hinzufügen* eine Decathlon-Produktkategorie hinzugefügt hast, kannst du anschließend im Menü *Daten » Kataloge* einen Katalog für diese Produktkategorie erstellen.

[.instruction]
Produktkategorien hinzufügen:

. Öffne das Menü *Einrichtung » Märkte » Decathlon » Katalog-Vorlagen hinzufügen*.
. Klicke auf *Kategorien hinzufügen* (material:add[]).
. Wähle die Kategorie, in der du deine Artikel anbieten möchtest. +
*_Tipp:_* Du kannst die Kategorie entweder über das Eingabefeld suchen oder den Kategoriebaum ausklappen, um dir die verfügbaren Kategorien anzusehen.
. Speichere (terra:save[role="blue"]) die Einstellungen. +
→ Die Kategorie wurde hinzugefügt. Du kannst nun im Menü *Daten » Kataloge* einen Katalog für diese Kategorie erstellen.

[#produktkategorie-verknuepfen]
=== Varianten mit Decathlon-Produktkategorie verknüpfen

[TIP]
.Welche Varianten werden zu Decathlon übertragen?
====
Welche Varianten zu Decathlon exportiert werden, legst du über die Filter des Katalogs im Menü *Daten » Kataloge » [Katalog öffnen] » Filter* fest. Standardmäßig sind bereits die Filter *Decathlon* und *Aktiv* gesetzt, das heißt, alle Varianten, die *aktiv* sind und im Tab *Verfügbarkeit* für Decathlon freigegeben sind, werden zu Decathlon exportiert. +
Mit den *benutzerdefinierten Filtern* im Katalog kannst du detaillierter festlegen, welche Varianten exportiert werden sollen.
====

Um deine Varianten nur in einer bestimmten Produktkategorie auf Decathlon zu listen, kannst du Eigenschaften verwenden. Dazu kannst du beispielsweise eine Auswahleigenschaft *Decathlon-Produktkategorien* mit den Decathlon-Produktkategorien als Auswahlwerten erstellen. Über die Filter des Katalogs kannst du danach mit der Auswahleigenschaft festlegen, in welche Decathlon-Produktkategorie die Varianten übertragen werden sollen.

[.instruction]
Auswahleigenschaft erstellen:

. Öffne das Menü *Einrichtung » Einstellungen » Eigenschaften » Konfiguration*.
. Klicke auf material:add[] *Eigenschaft erstellen*. +
→ Die Einstellungen für die neue Eigenschaft werden angezeigt.
. Wähle im Bereich *Details* den *Typ* *Auswahl*.
. Wähle im Bereich *Details* den *Bereich* *Artikel*.
. Nimm die weiteren Einstellungen vor. +
→ *_Tipp:_* Du kannst als Name für die Eigenschaft zum Beispiel *Decathlon-Produktkategorie* verwenden.
. Speichere (material:save[]) die Einstellungen. +
→ Die Eigenschaft wird erstellt.
. Klicke im Bereich *Auswahlwerte* auf *Auswahlwert anlegen*.
. Gib einen Namen für den Auswahlwert an. +
→ *_Tipp:_* Als Namen für die Auswahlwerte der Eigenschaft kannst du die verschiedenen Decathlon-Produktkategorien eingeben, zum Beispiel *Wanderschuhe* oder *Laufschuhe*.
. Speichere (material:save[]) die Einstellungen. +
→ Der Auswahlwert wird erstellt und in der Übersicht angezeigt. Der Wert erhält automatisch eine fortlaufende und einzigartige ID, die nicht geändert werden kann. Diese ID benötigst du, um nur bestimmte Varianten in einem Katalog zu übertragen.

Als nächstes verknüpfst du die gewünschten Varianten mit der neu erstellten Auswahleigenschaft.

[.instruction]
Variante mit Eigenschaft verknüpfen:

. Öffne das Menü *Artikel » Artikel bearbeiten » [Artikel öffnen]*.
. Wechsele in das *Tab: Varianten*.
. Öffne die Variante, die du verknüpfen möchtest.
. Wechsele in das *Tab: Eigenschaften*.
. Wähle im Bereich *Varianteneigenschaften* aus der Dropdown-Liste *Eigenschaften* die neu erstellt Eigenschaft und klicke auf *Hinzufügen* (icon:plus-square[role="green"]). +
→ Die Eigenschaft wird hinzugefügt.
. Wähle für die Eigenschaft aus der Dropdown-Liste *Wert* die gewünschte Produktkategorie.
. Speichere (terra:save[]) die Einstellungen.

Füge die ID des Auswahlwertes der Eigenschaft anschließend als Filter im gewünschten Decathlon-Katalog hinzu.

*_Tipp:_* Die IDs der Auswahlwerte siehst du, wenn du die Eigenschaft im Menü *Einrichtung » Einstellungen » Eigenschaften » Konfiguration* öffnest.

[.instruction]
Filter im Katalog setzen:

. Öffne das Menü *Daten » Kataloge*.
. Öffne den Decathlon-Katalog.
. Öffne auf der linken Seite das Tab *Filter*.
. Wähle im Bereich *Benutzerdefinierte Filter* den Filter *Mit mindestens einem Auswahleigenschaftswert verknüpft*.
. Trage als Filter die ID des Auswahlwertes der Eigenschaft ein. +
*_Tipp:_* Die IDs der Auswahlwerte siehst du, wenn du die Eigenschaft im Menü *Einrichtung » Einstellungen » Eigenschaften » Konfiguration* öffnest.
. Speichere (material:save[]) die Einstellungen.

[#katalog-erstellen]
=== Katalog erstellen

Artikeldaten werden über Kataloge zu Decathlon exportiert. Um deine Artikel zu Decathlon zu exportieren, erstellst du im Menü *Daten » Kataloge* einen Katalog. Verknüpfe dann im Katalog die von Decathlon vorgegebenen Felder mit in plentysystems gespeicherten Artikeldaten. +
Wenn du den Katalog aktivierst hast, werden die Katalogdaten in regelmäßigen Abständen automatisch zu Decathlon exportiert.

*_Hinweis:_* Für jede Produktkategorie auf Decathlon gibt es ein eigenes Katalog-Format. In jedem Format werden unterschiedliche Artikeldaten exportiert, je nachdem, welche Informationen Decathlon für eine Produktkategorie benötigt. +
Du musst also für jede Produktkategorie von Decathlon, in der du Artikel verkaufen möchtest, einen eigenen Katalog erstellen. Produktkategorien fügst du im Menü *Einrichtung » Märkte » Decathlon » Katalog-Vorlagen hinzufügen* hinzu.

[IMPORTANT]
.Katalog für Angebote erstellen
====
Bei Decathlon musst du immer einen Katalog für Angebote erstellen. Dazu wählst du im Menü *Daten » Kataloge* beim Erstellen des Katalogs das Format *Angebot*. +
Der Angebotskatalog wird immer zusätzlich zu den Katalogen für die verschiedenen Decathlon-Produktkategorien benötigt, damit Angebote auf Decathlon erstellt werden können. 
====

:catalogue-template-name: Decathlon
:format-item-new:
:one-per-category:
:decathlon:

include::partial$catalogue-creation.adoc[]

[#datenfelder-zuordnen]
==== Datenfelder im Katalog zuordnen

Nachdem du einen Katalog erstellt hast, ordnest du die Datenfelder des Marktplatzes den in plentysystems gespeicherten Artikeldaten zu. In diesem Kapitel erfährst du, wie du Datenfelder zuordnest und welche Besonderheiten es bei {market} gibt.

include::partial$catalogue-mapping.adoc[]

[#empfohlene-zuordnungen]
==== Empfehlungen für Datenfeld-Zuordnungen

include::partial$recommendation-text.adoc[]

include::partial$decathlon-recommended-item-mappings.adoc[]

*_Hinweis:_* Für jede Produktkategorie, in der du deine Artikel auf Decathlon anbieten möchtest, muss ein eigener Katalog erstellt werden. +
Kataloge für verschiedene Produktkategorien haben unterschiedliche Datenfelder, da in jeder Decathlon-Produktkategorie andere Artikeldaten angegeben werden müssen. +
Deshalb werden hier nur Empfehlungen zur Zuordnung für den Angebotskatalog gegeben.

[.collapseBox]
.Liste mit empfohlenen Datenfeld-Zuordnungen für das Format *Angebot*
--
include::partial$decathlon-recommended-mappings.adoc[]
--

[#besonderheiten-datenfelder]
==== Besonderheiten bei der Zuordnung von Datenfeldern

Jeder Marktplatz strukturiert Artikeldaten anders. Deshalb treten beim Zuordnen von Datenfeldern bestimmte Sonderfälle auf. In diesem Kapitel findest du Hinweise dazu, was du beim Zuordnen von Datenfeldern für Decathlon beachten solltest.

[#html]
===== Keine HTML-Formatierungen verwenden

Texte mit HTML-Formatierung können nicht zu Decathlon übertragen werden. Wenn du in deinen Texten für Decathlon Formatierungen verwenden willst, dann nutze stattdessen die Auszeichnungssprache markdown. +
Achte besonders bei den Artikel- und Angebotsbeschreibungen darauf, kein HTML zu verwenden, damit die Texte korrekt auf Decathlon angezeigt werden.

[#katalog-aktivieren]
==== Katalogexport aktivieren

:interval: einmal täglich
:decathlon:

include::partial$catalogue-activation.adoc[]

[#menue-datenaustausch]
== Datenaustausch manuell verwalten

Im Menü *Einrichtung » Märkte » Decathlon » Datenaustausch* hast du die Möglichkeit, Daten manuell zu im- und exportieren. Dieses Menü ist vor allem für Testzwecke gedacht. Du kannst beispielsweise nur bestimmte Artikel- und Angebotsdaten exportieren oder einzelne Aufträge in plentysystems importieren. Das kann nützlich sein, wenn du den Export testen willst oder wenn du fehlende Aufträge noch einmal importieren musst.

[#artikeldatenexport]
=== Artikeldaten manuell exportieren

Im Menü *Einrichtung » Märkte » Decathlon » Datenaustausch » Datenexport* kannst du einzelne Artikel und Angebote zu Decathlon exportieren. Dies kann zum Beispiel nützlich sein, wenn du den Export zu Decathlon testen willst oder wenn du nur einzelne Artikel übertragen willst.

*_Hinweis:_* Im Menü *Datenexport* kannst du auch schon Daten exportieren, wenn das Konto noch nicht aktiv ist. So kannst du den Export mit einzelnen Artikeln und Angeboten testen, bevor du das Konto aktivierst und deine Artikeldaten zu Decathlon exportierst.

[.instruction]
Artikel manuell exportieren:

. Öffne das Menü *Einrichtung » Märkte » Decathlon » Datenaustausch » Datenexport*.
. Wähle das *Konto* aus der Dropdown-Liste.
. Wähle den *Katalog* aus der Dropdown-Liste.
. Gib eine oder mehrere *Artikel-IDs* kommagetrennt ein. Diese Artikel werden zu Decathlon exportiert.
. Klicke auf material:file_upload[role="blue"] *Exportieren*. +
*_Hinweis:_* Du kannst diesen Prozess alle 30 Minuten ausführen. Artikel können nicht zwischen 24.00 - 6.00 Uhr MEZ manuell exportiert werden. +
*_Tipp:_* Klicke auf *Vorschau*, um dir eine Vorschau des Exports anzusehen.

[.instruction]
Angebote manuell exportieren:

. Öffne das Menü *Einrichtung » Märkte » Decathlon » Datenaustausch » Datenexport*.
. Wähle das *Konto* aus der Dropdown-Liste.
. Wähle den *Katalog* aus der Dropdown-Liste.
. Gib eine oder mehrere *Artikel-IDs* kommagetrennt ein. Die Angebote zu diesen Artikeln werden zu Decathlon exportiert.
. Klicke auf material:file_upload[role="blue"] *Exportieren*. +
*_Hinweis:_* Du kannst diesen Prozess alle 15 Minuten ausführen. +
*_Tipp:_* Klicke auf *Vorschau*, um dir eine Vorschau des Exports anzeigen zu lassen.

[#auftragsimport]
=== Aufträge manuell importieren

Im Menü *Einrichtung » Märkte » Decathlon » Datenaustausch » Auftragsimport* hast du die Möglichkeit, manuell einzelne Aufträge in plentysystems zu importieren. +
Du kannst entweder die Auftrags-IDs der Aufträge eingeben, die du importieren willst, oder Aufträge aus einem bestimmten Zeitraum importieren.

*_Hinweis:_* Du kannst diesen Prozess alle 15 Minuten ausführen.

[tabs]
====
Auftrags-IDs eingeben::
+
--
[.instruction]
Aufträge anhand der Auftrags-ID importieren:

. Öffne das Menü *Einrichtung » Märkte » Decathlon » Datenaustausch » Auftragsimport*.
. Klicke auf das Tab *Aufträge anhand von Auftrags-IDs importieren*.
. Gib in der Zeile *Auftrags-IDs* eine oder mehrere Auftrags-IDs kommagetrennt ein.
. Klicke auf *Importieren*. +
→ Die Aufträge werden in plentysystems importiert.
--
 
Zeitraum wählen::
+
--
[.instruction]
Aufträge eines bestimmten Zeitraums importieren:

. Öffne das Menü *Einrichtung » Märkte » Decathlon » Datenaustausch » Auftragsimport*.
. Klicke auf das Tab *Aufträge eines bestimmten Zeitraums importieren*.
. Gib ein *Startdatum* im Format *D.M.YYYY* ein oder wähle ein Datum über den Kalender (material:today[]).
. Gib ein *Enddatum* im Format *D.M.YYYY* ein oder wähle ein Datum über den Kalender (material:today[]).
. Klicke auf *Importieren*. +
→ Aufträge aus dem gewählten Zeitraum werden in plentysystems importiert.
--
====

[#ereignisaktionen-einrichten]
== Auftragsabwicklung automatisieren

Richte xref:automatisierung:ereignisaktionen.adoc#[Ereignisaktionen] ein, um {market} automatisch über Änderungen des Auftragsstatus zu informieren. Für {market} sind die folgenden Ereignisaktionen verfügbar:

* Informiere Decathlon automatisch darüber, dass die Ware versendet wurde. (<<#versandbestaetigung-senden, Wie?>>)
* Lade Rechnungen automatisch zu Decathlon hoch. (<<#rechnungen-hochladen, Wie?>>)
* Informiere Decathlon automatisch darüber, dass ein Artikel erstattet wurde. (<<#gutschriften-erstellen, Wie?>>)

[#versandbestaetigung-senden]
=== Versandbestätigungen automatisch senden

Richte eine xref:automatisierung:ereignisaktionen.adoc#[Ereignisaktion] ein, um {market} darüber zu informieren, dass die Artikel eines Auftrags versendet wurden.

:table-event-procedure: <<#versandbestaetigung-decathlon>>

include::_includes:partial$event-procedure.adoc[]

*_Hinweis:_* Die in <<#versandbestaetigung-decathlon>> gewählten Status und Filter dienen nur als Beispiel. Wähle für die Ereignisaktion die Filter und Status, die am besten zu deinem Arbeitsablauf passen.

[[versandbestaetigung-decathlon]]
.Ereignisaktion, um eine Versandbestätigung zu senden
[cols="1a,3a,3a"]
|===
|Einstellung |Option |Auswahl

| *Ereignis*
| Ereignis wählen, zum Beispiel:

* *Auftragsänderung: Statuswechsel*

| Status wählen, zum Beispiel *[7] Warenausgang gebucht*

| *Filter 1*
| *Auftrag &gt; Auftragstyp*
| *Auftrag*

| *Filter 2*
| *Auftrag &gt; Herkunft*
| *Decathlon*

| *Aktion*
| *Plugin*
| *Versandbestätigung an Decathlon senden*
|===

[#rechnungen-hochladen]
=== Rechnungen automatisch zu Decathlon hochladen

Richte eine xref:automatisierung:ereignisaktionen.adoc#[Ereignisaktion] ein, um Rechnungen automatisch zu {market} hochzuladen.

:table-event-procedure: <<#rechnung-decathlon>>

include::_includes:partial$event-procedure.adoc[]

*_Hinweis:_* Die in <<#rechnung-decathlon>> gewählten Status und Filter dienen nur als Beispiel. Wähle für die Ereignisaktion die Filter und Status, die am besten zu deinem Arbeitsablauf passen.

[[rechnung-decathlon]]
.Ereignisaktion, um eine Rechnung hochzuladen
[cols="1a,3a,3a"]
|===
|Einstellung |Option |Auswahl

| *Ereignis*
| Ereignis wählen, zum Beispiel:

* *Dokumente: Rechnung generiert* +

*_Hinweis:_* Wähle hier ein Ereignis, nach dem die Artikel bereits versendet wurden.

| 

| *Filter*
| *Auftrag &gt; Herkunft*
| *Decathlon*

| *Aktion*
| *Plugin*
| *Rechnungen zu Decathlon hochladen*
|===

[#gutschriften-erstellen]
=== Erstattungen an Decathlon melden

Richte eine xref:automatisierung:ereignisaktionen.adoc#[Ereignisaktion] ein, um Erstattungen automatisch an Decathlon zu melden.

Je nach Grund für die Erstattung können verschiedene Ereignisaktionen erstellt werden. Für Decathlon gibt es die folgenden Ereignisaktionen, um Erstattungen zu melden:

* *Erstattung an Decathlon melden: Einigung mit Händler*
* *Erstattung an Decathlon melden: Vor Versand storniert*
* *Erstattung an Decathlon melden: Artikel nicht erhalten*
* *Erstattung an Decathlon melden: Artikel zurückgegeben*
* *Erstattung an Decathlon melden: Nicht mehr auf Lager*
* *Erstattung an Decathlon melden: Artikel zu spät gesendet*

:table-event-procedure: <<#erstattung-decathlon>>

include::_includes:partial$event-procedure.adoc[]

*_Hinweis:_* Die in <<#erstattung-decathlon>> gewählten Status und Filter dienen nur als Beispiel. Wähle für die Ereignisaktion die Filter und Status, die am besten zu deinem Arbeitsablauf passen.

[[erstattung-decathlon]]
.Ereignisaktion, um eine Erstattung an Decathlon zu melden
[cols="1a,3a,3a"]
|===
|Einstellung |Option |Auswahl

| *Ereignis*
| Ereignis wählen, zum Beispiel:

*Auftragsanlage: Neue Gutschrift*

| 

| *Filter*
| *Auftrag &gt; Herkunft*
| *Decathlon*

| *Aktion*
| *Plugin*
| Ereignisaktion *Erstattung an Decathlon melden* mit passendem Grund wählen
|===
