= Galaxus
:author: team-plenty-channel
:keywords: Galaxus
:description: Multi-Channel in plentymarkets: Richte die Schnittstelle zum Marktplatz Galaxus in deinem plentymarkets System ein.

:galaxus:
:market: Galaxus
:price-search-engine: Galaxus
:plugin-name: Galaxus
:main-client:
:plugin-link: https://marketplace.plentymarkets.com/galaxus_4788

Der Schweizer Onlinemarktführer Galaxus ist Spezialist für IT, Unterhaltungselektronik und Telekommunikation. Als größtes Online-Warenhaus der Schweiz verfügt Galaxus über ein stetig wachsendes Sortiment. Immer zu günstigen Preisen und zuverlässig und schnell geliefert.

[#register]
== Bei Galaxus registrieren

Registriere Dich online für das link:https://www.galaxus.ch/de/page/werden-sie-haendler-12462[Digitec Galaxus Händler Programm^] oder kontaktiere Galaxus über die E-Mail-Adresse mailto:haendlerprogramm@digitecGalaxus.ch[haendlerprogramm@digitecGalaxus.ch].

[#order-workflow]
== Bestellungen über Galaxus

Du hast deinen Firmensitz in Deutschland und lieferst an Galaxus-Endkund:innen in die Schweiz.
Daraus ergeben sich drei mögliche Szenarien:

. Du sendest die Ware direkt an die Adresse der Endkund:in in der Schweiz.
. Du nutzt den EU-Hub von Galaxus und hast _keine_ Fiskalvertretung in der Schweiz.
. Du nutzt den EU-Hub von Galaxus und hast eine Fiskalvertretung in der Schweiz.

[.collapseBox]
.Was ist der EU-Hub?
--
Der EU-Hub ist eine Cross-Border-Verzollungslösung von Galaxus für unkomplizierten Zugang zum schweizerischen Markt.
Als EU-Händler:in kannst du den EU-Hub unabhängig davon nutzen, ob du eine Fiskalvertretung in der Schweiz hast oder nicht.
Die Digitec Galaxus AG tritt dabei als Serviceprovider für die Logistik und die Deklaration, Verzollung und Mehrwertsteuerabführung auf.

https://partner.digitecgalaxus.ch/hc/de/articles/360016297139-Wie-kann-ich-die-Verzollungs-L%C3%B6sung-der-Digitec-Galaxus-AG-nutzen-[Weitere Informationen und Voraussetzungen für die Nutzung des EU-Hubs findest du bei Galaxus].
--

[.collapseBox]
.Was bedeutet Fiskalvertretung?
--
Ausländische Versandhändler:innen sind in der Schweiz mehrwertsteuerpflichtig, wenn sie mit Kleinsendungen an Kund:innen in der Schweiz einen Jahresumsatz von mindestens 100.000,00 CHF erzielen.
Kleinsendungen sind definiert als Sendungen mit einem Warenwert von bis zu 65 CHF.

Diese Händler:innen müssen eine Person mit Wohnsitz in der Schweiz als Mehrwertsteuer-Fiskalvertretung bestimmen. Die Fiskalvertretung registriert die Händler:innen im Schweizer Mehrwertsteuerregister.
--

[.collapseBox]
.Wie laufen Bestellungen über den EU-Hub ab?
--

Wenn du den EU-Hub nutzt, läuft eine Bestellung so ab:

. Kund:in in der Schweiz bestellen und zahlt ein Produkt über Galaxus.
. Du bestätigst Galaxus, dass die Bestellung eingegangen ist.
. Du sendest das Paket an den EU-Hub.
. Du informierst Galaxus darüber, dass das Paket unterwegs ist.
. Das Paket wird im EU-Hub logistisch und zollrechtlich verarbeitet:
  * Paket wird mit Versandetiketten für die Schweizer Post versehen.
  * Die rechtlich notwendigen Ausfuhrschritte werden erledigt.
. Das Paket wird in das Schweizer Zentrallager transportiert.
. Das Zentrallager erledigt die für die Einfuhr nötigen Schritte.
. Das Paket wird an die Schweizer Post übergeben.
. Kund:in nimmt das Paket in Empfang.

https://partner.digitecgalaxus.ch/hc/de/articles/360016297139-Wie-kann-ich-die-Verzollungs-L%C3%B6sung-der-Digitec-Galaxus-AG-nutzen-[Weitere Informationen und Vorraussetzungen für die Nutzung des EU-Hubs findest du bei Galaxus].
--

[.collapseBox]
.Wie laufen Retouren über den EU-Hub ab?
--

Wenn du den EU-Hub nutzt, läuft eine Retoure so ab:

. Kund:in gibt im Galaxus-Shop an, dass sie eine Retoure wünscht.
. Du wirst von Galaxus über die Retoure informiert.
. Kund:in sendet die Retoure an Digitec Galaxus AG in der Schweiz.
. Das Paket wird im Schweizer Zentrallager logistisch und zollrechtlich verarbeitet:
  * Paket wird mit Versandetiketten für die UHL versehen.
  * Die rechtlich notwendigen Ausfuhrschritte werden erledigt.
. Das Pake