= Hood
:author: team-plenty-channel
:keywords: Hood, Hood, hood.de, hood.de
:description: Hier erfährst du, wie du den Marktplatz Hood in plentymarkets einrichtest, damit du deine Artikel auf Hood verkaufen kannst. Auf Hood kannst du deine Produkte als Auktion oder als Festpreisartikel anbieten.

:hood:
:listings-sales-planner: 1600
:listings-edit: 2700

Auf dem Marktplatz Hood kannst du deine Produkte als Auktion, Festpreisartikel oder im eigenen Shop einstellen. plentymarkets ermöglicht dir die komplette und integrierte Anbindung an Hood. Erfahre, wie du Artikel einstellst, einen Hood-Shop einrichtest und deine Listings bearbeitest. Käufe werden über dein plentymarkets System abgewickelt.

[#100]
== Bei Hood registrieren

Registriere dich zunächst auf link:https://www.hood.de/kostenlos-registrieren.htm?sec=1[Hood^]. Lege dort ein API-Passwort fest, das du für die Einrichtung in plentymarkets benötigst.

[#200]
== Hood in plentymarkets einrichten

Führe die im Folgenden beschriebenen Schritte durch, um Hood in plentymarkets einzurichten.

[.instruction]
Hood-Zugangsdaten eingeben:

. Öffne das Menü *Einrichtung » Märkte » Hood*.
. Gib die Zugangsdaten gemäß <<#zugangsdaten>> ein.
. Speichere (terra:save[]) die Einstellungen.

[[zugangsdaten]]
.Zugangsdaten des Marktplatzes Hood
[cols="1,3a"]
|===
|Einstellung |Erläuterung

| *Benutzername*
|Benutzername des Hood-Kontos eingeben.

| *API-Passwort*
|Passwort eingeben, wie von Hood erhalten.

| *Konto-Status*
|Zeigt an, ob die Schnittstelle aktiv ist.

| *Shop-Typ*
|Zeigt das gebuchte Shop-Paket bei Hood an, zum Beispiel link:https://www.hood.de/hood-shop-einrichten.htm[Platin^].
|===

Die Anbindung des Marktplatzes stellt folgende automatisierte Prozesse bereit:

* Auftragsimport (stündlich)
* Bestandsabgleich (alle 20 Minuten)
* Listing-Synchronisierung (stündlich)
* automatisches Beenden der Listings, die keinen Bestand mehr haben (alle 15 Minuten)
* automatisches Neustarten der Listings, die wieder Bestand haben (alle 15 Minuten)
* automatisches Erstellen eines neuer Kund:innen beim Auftragsimport, wenn diese noch nicht in der Datenbank vorhanden sind

[TIP]
.Automatischer Auftragsimport
====
Die Aufträge von Hood werden stündlich in dein plentymarkets System importiert und sind dann im Menü *Aufträge* verfügbar. Du erkennst die Aufträge von Hood an den Informationen in der Spalte *Herkunft*. Aus Platzgründen wird hier nur die ID 125 angezeigt. Zeige mit der Maus auf die ID, um die Herkunft anzuzeigen.
====

[#400]
=== Versandprofile einrichten

Gehe wie im Folgenden beschrieben vor, um die Versandprofile für Hood einzurichten.

[.instruction]
Versandprofile einrichten:

. Öffne das Menü *Einrichtung » Märkte » Hood*.
. Öffne das Tab *Neu* im Abschnitt *Versandprofile*.
. Gib einen *Namen* für das Versandprofil ein.
. Wähle eine *Region* aus der Dropdown-Liste.
. Wähle eine *Versandart* aus der Dropdown-Liste.
. Gib die *Versandkosten* ein. +
→ Gib weitere Versandarten und die Versandkosten für diese Region ein.
. Speichere (terra:save[]) die Einstellungen. +
→ Das Versandprofil wird im Tab *Übersicht* angezeigt und kann dort bearbeitet oder gelöscht werden.

Richte nach diesem Schema weitere Versandprofile ein. Die Versandprofile stehen dann im Listing im Tab *Base* zur Verfügung.

[#450]
=== Versandprofile verknüpfen

Im Menü *Einrichtung » Märkte » Hood » Versandprofilverknüpfungen* verknüpfst du Versandarten mit einem Versandprofil. Während des Auftragsimports werden die in dem Menü gespeicherten Einstellungen berücksichtigt. Wenn eine Versandart nicht verknüpft wurde, findet die Versandprofilberechnung automatisch statt. Gehe wie im Folgenden beschrieben vor, um Versandarten mit einem Versandprofil zu verknüpfen.

[.instruction]
Versandprofile verknüpfen:

. Öffne das Menü *Einrichtung » Märkte » Hood » Versandprofilverknüpfungen*.
. Wähle für die gewünschte Versandart ein *Versandprofil* aus der Dropdown-Liste.
. Speichere (terra:save[]) die Einstellungen.

[#500]
=== Zahlungsarten einrichten

Die Zahlungsarten, die du für den Marktplatz benötigst, richtest du zuerst in deinem Konto bei Hood ein. Wähle zwischen mehreren Optionen wie zum Beispiel Vorkasse per Überweisung, Kauf auf Rechnung oder PayPal. Die Zahlungsarten stehen im Listing zur Verfügung.

Seit 1. August 2022 bietet Hood auch einen eigenen Zahlungsdienst an. Wenn du HoodPay nutzt, laufen alle Zahlungen über Hood. Diesen Zahlungsdienst aktivierst du in deinem Konto bei Hood. In plentymarkets werden HoodPay-Aufträge mit der Zahlungsart *Hood Pay* und dem Status [5] importiert.

[#600]
=== Bewertungen automatisch abgeben

Gib zunächst Bewertungstexte ein. Richte anschließend eine xref:automatisierung:ereignisaktionen.adoc#[Ereignisaktion] ein, um diese Bewertungstexte automatisch an deine Käufer:innen zu senden. Alle Käufer:innen, die du bewertet hast, erhalten automatisch nach dem Zufallsprinzip ebenfalls eine Bewertung.

[.instruction]
Bewertungstexte eingeben:

. Öffne das Menü *Einrichtung » Märkte » Hood*.
. Gib im Bereich *Automatische Bewertungen* die Bewertungstexte ein.  +
→ Die Texte werden nach dem Zufallsprinzip gewählt und verwendet.
. Speichere (terra:save[]) die Einstellungen.

:table-event-procedure: <<#automatische-bewertungen>>

include::_includes:partial$event-procedure.adoc[]

[[automatische-bewertungen]]
.Ereignisaktion zum automatischen Abgeben von Bewertungen für Hood
[cols="1,3,3"]
|===
| Einstellung | Option | Auswahl

| *Ereignis*
| *Auftragsänderung: Warenausgang gebucht*
|

| *Filter*
| *Auftrag &gt; Herkunft*
| *Hood*

| *Aktion*
| *Market-Listings &gt; Bewertung für Hood abgeben*
|
|===

[#700]
=== Versandbestätigungen automatisch senden

Richte eine xref:automatisierung:ereignisaktionen.adoc#[Ereignisaktion] ein, um automatisch eine Versandbestätigung an Hood zu senden, nachdem ein Warenausgang gebucht wurde.

:table-event-procedure: <<#automatische-versandbestätigung>>

include::_includes:partial$event-procedure.adoc[]

[[automatische-versandbestätigung]]
.Ereignisaktion zum automatischen Senden von Versandbestätigungen an Hood
[cols="1,3,3"]
|===
| Einstellung | Option | Auswahl

| *Ereignis*
| *Auftragsänderung: Warenausgang gebucht*
|

| *Filter 1*
| *Auftrag &gt; Herkunft*
| *Hood*

| *Aktion*
| *Versand &gt; Versandbestätigung an Hood senden*
|
|===

[#800]
=== Zahlungsbestätigungen automatisch senden

Richte eine xref:automatisierung:ereignisaktionen.adoc#[Ereignisaktion] ein, um Zahlungsbestätigungen automatisch an Hood zu senden.

:table-event-procedure: <<#automatische-zahlungsbestätigung>>

include::_includes:partial$event-procedure.adoc[]

[[automatische-zahlungsbestätigung]]
.Ereignisaktion zum automatischen Senden von Zahlungsbestätigungen an Hood
[cols="1,3,3"]
|===
| Einstellung | Option | Auswahl

| *Ereignis*
| *Zahlung: Vollständig*
|

| *Filter 1*
| *Auftrag &gt; Herkunft*
| *Hood*

| *Aktion*
| *Market-Listings &gt; Zahlungsbestätigung an Hood senden*
|
|===

[#900]
== Artikel für Hood-Shop einstellen

Das Einstellen von Artikeln und Abrufen von Aufträgen ist ohne aktiven Shop bei Hood möglich. Für einige Optionen, zum Beispiel wenn du Variantenartikel einstellen möchtest, ist jedoch ein Shop nötig, den du in verschiedenen Ausführungen bei Hood link:https://www.hood.de/hood-shop-einrichten.htm[buchen^] kannst.

[#1000]
=== Variantenartikel einstellen

Wenn du Variantenartikel bei Hood einstellen möchtest, benötigst du einen gebuchten Shop. Wenn du einen Shop bei Hood gebucht hast, werden die Artikel für Hood über eine Kategorieverknüpfung dort eingebunden. Die Shop-Kategorien selbst richtest du direkt im link:https://www.hood.de/mein-shop.htm[Hood-Backend^] im Menü *Mein Shop > Shop-Einstellungen > Kategorien* ein. Lade die Kategorien anschließend in plentymarkets, damit du diese im Listing wählen kannst.

[.instruction]
Shop-Kategorien für Hood laden:

. Öffne das Menü *Einrichtung » Märkte » Hood*.
. Klicke im Bereich *Shop-Kategorien* auf *Aktualisieren* (icon:undo[]). +
→ Die Shop-Kategorien werden angezeigt.
. Wiederhole den Aktualisierungsvorgang, wenn du weitere Shop-Kategorien bei Hood hinzugefügt hast.

[IMPORTANT]
.Hood unterstützt keine HTML-Tags in der Kurzbeschreibung für Listings vom Typ Shop-Artikel
====
Bei der Übertragung von Hood-Listings vom Typ *Shop-Artikel* werden für die Kurzbeschreibung keine HTML-Tags übertragen, da Hood HTML-Tags nicht unterstützt. Als Kurzbeschreibung bei Hood wird der *Vorschautext* des Artikels im Menü *Artikel » Artikel bearbeiten* im Tab *Texte* aus plentymarkets übertragen. Vorhandene HTML-Tags werden entfernt und nur der reine Text wird übertragen.  +
In der eigentlichen Listing-Beschreibung sind HTML-Tags erlaubt.
====

[#1100]
=== Status des Warenbestands anzeigen

Hood-Listings des Typs *Shop-Artikel* werden bei fehlendem Warenbestand von Hood in den Status *Ausgeblendet* gesetzt und nicht beendet.
Dies betrifft Hood-Listings des Typs *Shop-Artikel* mit Bestandsabhängigkeit *beschränkt (ohne Reservierung)* und *beschränkt (mit Reservierung)*. Diese Listings werden auch im plentymarkets System nicht beendet, sondern mit dem Status *Ausgeblendet* angezeigt. Sobald wieder Bestand in plentymarkets vorhanden ist, wird das Listing bei Hood durch eine automatische Bestandsaktualisierung wieder aktiviert.

[#1160]
===  Eigene Merkmale aktivieren

Um eigene Merkmale für den Marktplatz Hood nutzen zu können, müssen die Merkmale im Menü *Einrichtung » Artikel » Merkmale* für Hood aktiviert werden. Maximal sind 12 Merkmale pro Artikel und maximal 16 Zeichen pro Name erlaubt.

[.instruction]
Eigenes Merkmal aktivieren:

. Öffne das Menü *Einrichtung » Artikel » Merkmale*.
. Klappe ein Merkmal auf (icon:plus-square-o[]).
. Aktiviere die Option *Anzeige als Hood-Merkmal*.
. Speichere (terra:save[]) die Einstellungen. +
→ Das Merkmal wird auf Hood auf der Angebotsseite in der Merkmalliste angezeigt.

[TIP]
.Platzhalter in Layout-Vorlage (Hood)
====
Wenn die Option *Platzhalter in Layout-Vorlage (Hood)* aktiviert ist, wird das Merkmal auch in der Layout-Vorlage des Listings erscheinen, sofern der Platzhalter benutzt wird.
====

[#1200]
== Listings vorbereiten

include::partial$manage-listings.adoc[tag=listing-definition]

[#1300]
=== Grundeinstellungen für Listings vornehmen

include::partial$manage-listings.adoc[tag=listing-basic-settings]

[#1400]
=== Warenbestand für Listings einstellen

include::partial$manage-listings.adoc[tag=listings-stock]

[IMPORTANT]
.Einstellungen für Artikel ohne Warenbestand bei Hood beachten
====
Wenn eine Variante keinen Bestand mehr hat und du die Einstellung *Angebote automatisch beenden/ausblenden* in plentymarkets *aktiviert* hast, überträgt plentymarkets den Bestand *0* an Hood. Damit Varianten ohne Bestand nicht mehr auf Hood gelistet werden, musst du aber zusätzlich Einstellungen bei Hood vornehmen. +

Es handelt sich hierbei um die Einstellung *Nicht lagernde Artikel* im Hood-Backend. Öffne dazu bei Hood das Menü *Mein Shop » Shop-Einstellungen » Versandkosten, Mehrwertsteuer und Zahlungsarten bearbeiten*. Wähle für die Einstellung *Nicht lagernde Artikel* die Option *...können in der Regel nicht weiter gekauft werden.*, damit Varianten ohne Bestand nicht mehr auf Hood angezeigt werden.
====

[#1500]
=== Kaufabwicklung einrichten

include::partial$manage-listings.adoc[tag=listings-checkout]

[#1600]
=== Verkaufsplaner einrichten

include::partial$manage-listings.adoc[tag=listings-sales-planner]

[#2100]
=== Verzeichnisse zum Gruppieren von Listings erstellen

include::partial$manage-listings.adoc[tag=group-listings]

[#1700]
===  Layout-Vorlagen verwalten

include::partial$manage-listings.adoc[tag=manage-layout-templates]

[#2905]
====  Layout-Vorlagen erstellen

include::partial$manage-listings.adoc[tag=create-layout-templates]

[#1750]
==== Beispiel-Code für eine Layout-Vorlage

include::partial$manage-listings.adoc[tag=layout-example-code]

[#1800]
====  Layout-Vorlagen importieren

include::partial$manage-listings.adoc[tag=import-layout]

[#1850]
====  Layout-Vorlage verknüpfen

include::partial$manage-listings.adoc[tag=link-layout]

[#1900]
====  Template-Variablen und -Funktionen

include::partial$template-variables.adoc[]

[#2300]
== Listings erstellen

include::partial$manage-listings.adoc[tag=listings-creation]

[IMPORTANT]
.Listing dauerhaft bei Hood listen
====
Die maximale Laufzeit für ein Listing bei Hood beträgt 14 Tage. Um ein Listing dauerhaft zu listen, müssen die folgenden Voraussetzungen erfüllt sein:

* Du besitzt einen Hood-Shop (unabhängig vom gebuchten Shop-Paket).
* Der Listing-Typ steht auf Shop-Artikel.
* Im Tab *Marktplatz* des Listings ist eine Shop-Kategorie verknüpft.
====

[#2400]
=== Listing erstellen

include::partial$manage-listings.adoc[tag=create-listing]

[IMPORTANT]
.Fehlermeldung und Lösung
====
Für ein besseres Google-Ranking verlangt Hood die Angabe der EAN. Wenn du eingestellt hast, dass weder die EAN noch eine andere Artikelnummer übertragen wird, wird die Fehlermeldung *Hood: Error #0 Bitte geben Sie eine Marke oder einen Hersteller ein.* angezeigt. +
Wähle daher für die Einstellung *Als Artikelnummer übertragen* nicht die Option *nicht übertragen*. Wenn die EAN nicht verfügbar ist oder nicht übertragen werden soll, wähle die Option *Sonderanfertigung oder No-Name-Produkt*.
====

[#2500]
=== Market-Listing zu vorhandenem Listing hinzufügen

include::partial$manage-listings.adoc[tag=add-market-listing]

[#2600]
===  Mehrere Listings erstellen

include::partial$manage-listings.adoc[tag=create-multiple-listings]

[#2700]
==  Listings bearbeiten

include::partial$manage-listings.adoc[tag=edit-listings]

[#2800]
===  Einzelnes Listing bearbeiten

include::partial$manage-listings.adoc[tag=edit-one-listing]

[#2900]
==== Grundeinstellungen für Market-Listings vornehmen

include::partial$manage-listings.adoc[tag=market-listing-base-settings]

[#3000]
====  Beschreibung und Layout anpassen

include::partial$manage-listings.adoc[tag=description-layout]

[#3100]
====  Marktplatzeinstellungen bearbeiten

include::partial$manage-listings.adoc[tag=edit-market-settings]

[#3200]
===  Mehrere Listings bearbeiten

include::partial$manage-listings.adoc[tag=edit-multiple-listings]

[#3300]
== Listings kopieren

include::partial$manage-listings.adoc[tag=copy-listings]

[#3400]
===  Einzelnes Listing kopieren

include::partial$manage-listings.adoc[tag=copy-one-listing]

[#3500]
===  Mehrere Listings kopieren

include::partial$manage-listings.adoc[tag=copy-several-listings]

[#3600]
==  Listings suchen

include::partial$manage-listings.adoc[tag=find-listings]

[#3700]
===  Nach Einstellungen filtern

include::partial$manage-listings.adoc[tag=filter-by-settings]

[#3800]
===  Nach Kategorien filtern

include::partial$manage-listings.adoc[tag=filter-by-categories]

[#3900]
===  Nach Verzeichnissen filtern

include::partial$manage-listings.adoc[tag=filter-by-groups]

[#4000]
==  Listings starten

include::partial$manage-listings.adoc[tag=start-listings]

[#4100]
===  Listings manuell starten

include::partial$manage-listings.adoc[tag=manually-start-listings]

[#4200]
===  Listings automatisch per Verkaufsplaner starten

include::partial$manage-listings.adoc[tag=start-listings-sales-planner]

[#4300]
===  Listings automatisch per Endloslister starten

include::partial$manage-listings.adoc[tag=start-listings-endless-lister]

[#4400]
===  Zukünftige Listings

include::partial$manage-listings.adoc[tag=future-listings]

[#4500]
==  Listing-Vorlagen erstellen

include::partial$manage-listings.adoc[tag=create-listing-template]

[#4600]
==  Aktive Listings

include::partial$manage-listings.adoc[tag=active-listings]

[#4700]
===  Aktive Listings suchen

include::partial$manage-listings.adoc[tag=search-active-listings]

[#4800]
===  Aktive Listings per Gruppenfunktion bearbeiten

include::partial$manage-listings.adoc[tag=group-edit-active-listings]

[#4900]
===  Aktive Listings per Stapelverarbeitung bearbeiten

include::partial$manage-listings.adoc[tag=batch-edit-active-listings]

[#5000]
== Fehlerberichte von Hood abrufen

Im Menü *Daten » API-Log* kannst du Fehlerberichte von Hood abrufen.

[.instruction]
Fehlerbericht abrufen:

. Öffne das Menü *Daten » API-Log » Tab: API-Log*.
. Wähle aus der Dropdown-Liste *Vorgang* die Option *ItemListingControllerHood* oder *LeaveFeedback*.
. Wähle ein Datum aus dem Kalender.
. Wähle die Anzahl der Ergebnisse pro Seite.
. Klicke auf *Suchen* (icon:search[role="blue"]), um die Ergebnisse anzuzeigen.

[#5100]
== Daten mit dem Import-Tool abgleichen

Für den Austausch von Daten zwischen plentymarkets und Hood steht dir das Import-Tool im Menü *Daten » Import* zur Verfügung. Verwende den Import-Typ xref:daten:elasticsync-market-listing.adoc#[Market-Listing], um Listing-Daten in plentymarkets zu importieren.
