= idealo: Wechsel zum Katalogexport
:author: team-plenty-channel
:keywords: idealo, idialo, idealo Preisportal, idealo Preisvergleich, idealo Katalog, idealo Katalogexport, idealo Katalog einrichten
:description: Auf dieser Seite erfährst du, wie du vom alten Artikelexport von idealo zum neuen Katalogexport wechselst.

:market: idealo
:idealo:
:catalogue:

Du listest deine Artikel bereits auf idealo und möchtest zum Katalogexport wechseln? Dann findest du hier Empfehlungen für den Wechsel.

[IMPORTANT]
.Noch keine Erfahrung mit den Katalogen?
====
Du arbeitest zum ersten Mal mit den Katalogen? Dann mache dich zuerst xref:daten:kataloge-verwalten.adoc#[mit dem Prinzip der Kataloge vertraut].
====

[#katalog-erstellen]
== Katalog erstellen

Erstelle einen Katalog mit dem Template *idealo*.

xref:page$idealo-einrichten.adoc#catalogue-export[Wie geht das?]

[#datenfelder-pruefen]
== Marktplatz-Datenfelder prüfen

Prüfe im Katalog, ob du weitere Eigenschaften benötigst. Scrolle durch den Katalog und prüfe die idealo-Datenfelder. Kannst du alle Felder zuordnen, für die du Daten zu idealo exportieren möchtest?

Wenn nicht, erstelle die Eigenschaften, die du benötigst.

→ *_Tipp:_* In den xref:page$idealo-einrichten.adoc#recommended-mappings[Empfehlungen für Datenfeld-Zuordnungen] für idealo kannst du sehen, für welche idealo-Datenfelder wir empfehlen, Eigenschaften zu verknüpfen.

* Du arbeitest zum ersten Mal mit den Eigenschaften? Dann mach dich zuerst xref:artikel:eigenschaften.adoc#500[mit dem Prinzip der Eigenschaften vertraut].

[#datenfelder-zuordnen]
== Datenfelder im Katalog zuordnen

Du hast einen Katalog erstellt und wenn nötig Eigenschaften erstellt. Super. Dann ordne die Datenfelder des Marktplatzes jetzt passenden plentymarkets Datenfeldern zu.

xref:page$idealo-einrichten.adoc#data-field-mappings[Wie geht das?]





[#kategorie-verknuepfen]
== Varianten mit der idealo-Produktkategorie verknüpfen

Verknüpfe als nächstes die Varianten, die in einem Katalog übertragen werden sollen, mit der gewünschten idealo-Produktkategorie. Um eine Variante mit einer Produktkategorie zu verknüpfen, verwendest du Eigenschaften.

*_Hinweis:_* Du musst deine Varianten nur mit idealo-Produktkategorien verknüpfen, wenn du Artikel per <<#catalogue-export, Katalogexport>> an idealo überträgst.

Wenn du ein Katalog-Format für Kaufland erstellt hast, wird in deinem plentymarkets System die Eigenschaft *Kaufland.de-Kategorie* erstellt. Mit dieser Eigenschaft legst du fest, in welcher Kategorie deine Varianten auf Kaufland angeboten werden.

Im Assistenten *Kaufland - Kataloge erstellen* wählst du für jeden Katalog eine Kaufland-Produktkategorie. Jede dieser Produktkategorien wird als Auswahlwert zu der Eigenschaft *Kaufland.de-Kategorie* hinzugefügt.

Damit deine Varianten in der gewünschten Kategorie auf Kaufland angeboten werden, müssen sie im Tab *Eigenschaften* der Variante mit der Eigenschaft *Kaufland.de-Kategorie* verknüpft werden. Für diese Eigenschaft wählst du dann die Produktkategorie, in der deine Varianten angeboten werden sollen.

[.instruction]
Variante mit Produktkategorie verknüpfen:

. Öffne das Menü *Artikel » Artikel bearbeiten » [Artikel öffnen]*.
. Wechsele in das *Tab: Varianten*.
. Öffne die Variante, die du verknüpfen möchtest.
. Wechsele in das *Tab: Eigenschaften*.
. Wähle im Bereich *Varianteneigenschaften* aus der Dropdown-Liste *Eigenschaften* die Eigenschaft *Kaufland.de-Kategorie* und klicke auf *Hinzufügen* (icon:plus-square[role="green"]). +
→ Die Eigenschaft wird hinzugefügt.
. Wähle für die Eigenschaft *Kaufland.de-Kategorie* aus der Dropdown-Liste *Wert* die gewünschte Kategorie. +
→ Die Variante wird im zugehörigen Katalog exportiert. +
*_Beispiel:_* Wählst du den Wert *T-Shirts*, wird die Variante auf Kaufland in der Kategorie *T-Shirts* angeboten.
. Wiederhole die Schritte 5 und 6 für alle Kategorien, in denen du die Variante verkaufen möchtest.
. Speichere (terra:save[]) die Einstellungen.








[#weitere-eigenschaften]
== Varianten mit weiteren Eigenschaften verknüpfen

Verknüpfe jetzt deine Varianten mit den weiteren Eigenschaften, die du für idealo benötigst. Wie oben beschrieben musst du mindestens die Pflichtfelder zu idealo exportieren.

[#katalog-aktivieren]
== Katalog aktivieren

:interval: einmal täglich
:market: idealo

include::partial$catalogue-activation.adoc[]