= idealo: Wechsel zum Katalogexport
:author: team-plenty-channel
:keywords: idealo, idialo, idealo Preisportal, idealo Preisvergleich, idealo Katalog, idealo Katalogexport, idealo Katalog einrichten
:description: Auf dieser Seite erfährst du, wie du vom alten Artikelexport von idealo zum neuen Katalogexport wechselst.

:market: idealo
:idealo:
:catalogue:

Du listest deine Artikel bereits auf idealo und möchtest zum Katalogexport wechseln? Dann findest du hier Empfehlungen für den Wechsel.

[IMPORTANT]
.Noch keine Erfahrung mit den Katalogen?
====
Du arbeitest zum ersten Mal mit den Katalogen? Dann mache dich zuerst xref:daten:kataloge-verwalten.adoc#[mit dem Prinzip der Kataloge vertraut].
====

[#voraussetzungen]
== Voraussetzungen

Damit du einen Katalog für idealo erstellen kannst, muss das idealo-Plugin in der Version *3.3.41* in deinem plentymarkets System installiert sein. Der Katalog für idealo ist erst ab dieser Plugin-Version verfügbar. +

Das idealo-Plugin aktualisierst du im Menü *Plugins » Plugin-Set Übersicht » [Plugin-Set, in dem idealo installiert ist, öffnen]* auf die neueste Version.

Du hast das idealo-Plugin noch nicht installiert? Dann kannst du es im link:https://marketplace.plentymarkets.com/elasticexportidealode_4723[plentyMarketplace^] herunterladen.

[#katalog-erstellen]
== Katalog erstellen

Erstelle einen Katalog mit dem Template *idealo*.

xref:page$idealo-einrichten.adoc#catalogue-export[Wie geht das?]

[#datenfelder-pruefen]
== Marktplatz-Datenfelder prüfen

Prüfe im Katalog, ob du weitere Eigenschaften benötigst. Scrolle durch den Katalog und prüfe die idealo-Datenfelder. Kannst du alle Felder zuordnen, für die du Daten zu idealo exportieren möchtest?

Wenn nicht, erstelle die Eigenschaften, die du benötigst.

→ *_Tipp:_* In den xref:page$idealo-einrichten.adoc#recommended-mappings[Empfehlungen für Datenfeld-Zuordnungen] für idealo kannst du sehen, für welche idealo-Datenfelder wir empfehlen, Eigenschaften zu verknüpfen.

* Du arbeitest zum ersten Mal mit den Eigenschaften? Dann mach dich zuerst xref:artikel:eigenschaften.adoc#500[mit dem Prinzip der Eigenschaften vertraut].

[#datenfelder-zuordnen]
== Datenfelder im Katalog zuordnen

Du hast einen Katalog erstellt und wenn nötig Eigenschaften erstellt. Super. Dann ordne die Datenfelder des Marktplatzes jetzt passenden plentymarkets Datenfeldern zu.

xref:page$idealo-einrichten.adoc#data-field-mappings[Wie geht das?]

[#weitere-eigenschaften]
== Varianten mit weiteren Eigenschaften verknüpfen

Verknüpfe jetzt deine Varianten mit den weiteren Eigenschaften, die du für idealo benötigst. Wie oben beschrieben musst du mindestens die Pflichtfelder zu idealo exportieren.

[#katalog-aktivieren]
== Katalog aktivieren

:interval: einmal täglich
:market: idealo

include::partial$catalogue-activation.adoc[]