= MediaMarkt
:author: team-plenty-channel
:page-index: false

:mediamarkt:
:market: MediaMarkt
:mirakl:
:plugin-name: MediaMarkt
:plugin-link: https://marketplace.plentymarkets.com/mediamarkt_6918
:type-of-market: Marktplatz
:registration-url: https://www.mediamarkt.de/de/about-us/marketplace
:marketplace-url: https://marketplace.plentymarkets.com/mediamarkt_6918
:assistant-name: MediaMarkt
:valid-values-zip: https://drive.google.com/file/d/1a_QY4VOIuC2-A-9jerGDAOmYP72907Xt/view?usp=sharing
:mirakl-menu-shipping: Platform Settings » Shipping
:referrer-name: pass:quotes[Herkunft *MediaMarkt*]
:category-example: VIDEO CASSETTES

Auf MediaMarkt finden Kund:innen eine große Produktauswahl rund um Technik, Elektronik und Multimedia.

Auf dieser Seite erfährst du, wie du die Schnittstelle zu {market} in plentymarkets einrichtest.

include::partial$mirakl-first-steps.adoc[]

[#order-process]
== Ablauf der Auftragsabwicklung

Aufträge, die auf MediaMarkt erzeugt wurden, werden alle 15 Minuten in dein plentymarkets System importiert.

So läuft die Auftragsabwicklung bei MediaMarkt ab:

* Die Händler:in akzeptiert den Auftrag über eine Ereignisaktion.
* Die Zahlung wird von MediaMarkt eingezogen.
* Mit der Zahlungszusicherung werden die Rechnungs- und Lieferadresse am Auftrag in deinem plentymarkets System aktualisiert.
* Über eine Ereignisaktion werden Versanddienstleister und Paketnummer am Auftrag in Mirakl aktualisiert.
* Über eine Ereignisaktion wird eine Rechnung an MediaMarkt gesendet.

[#allgemeine-informationen]
== Häufigkeit des Datenaustauschs

include::partial$mirakl-data-exchange-table.adoc[]

[#api-schluessel]
== API-Schlüssel erzeugen

include::partial$mirakl-api-key.adoc[]

[#300]
== Marktplatz in plentymarkets einrichten

Du hast die Plugins *Mirakl Connector* und *Mediamarkt* installiert und einen API-Schlüssel erzeugt? Super. Nun richtest du den Marktplatz in plentymarkets ein.

[#marktplatz-assistent-durchlaufen]
=== Einrichtungsassistenten durchlaufen

include::partial$mirakl-market-assistant.adoc[]

[#auftragsherkunft]
=== Auftragsherkunft aktivieren

:market: {market}
:referrer: {market}
:referrer-option: {referrer-name}
:mirakl-auftragsherkunft:

include::partial$auftragsherkunft-aktivieren.adoc[]

[#verkaufspreis]
=== Verkaufspreis festlegen

:referrer-price: {market}
:mirakl-verkaufspreis:

include::partial$verkaufspreis-festlegen.adoc[]

[#volume-discount]
=== _Optional:_ Staffelpreise festlegen

include::partial$mirakl-volume-discounts.adoc[]

[#eigenschaften-erstellen]
== Eigenschaften erstellen

include::partial$mirakl-creating-properties.adoc[]

[#artikelexport-katalog]
== Artikelexport einrichten

include::partial$mirakl-data-catalogue-intro.adoc[]

[#katalog-im-assistenten]
=== Katalog im Assistenten erstellen

Gehe wie im Folgenden beschrieben vor, um einen Katalog im Assistenten zu erstellen.

:catalogue-assistant-name: {market}-Katalog
:number-of-boxes: Info-Box
:mapping-fields: die
:catalogue-path: pass:quotes[*Einrichtung » Assistenten » Plugins » [Plugin-Set wählen]*]
:catalogue-note: pass:quotes[Achte darauf, eine Kategorie der untersten Ebene zu wählen. Eine bessere Übersicht findest du auf Mirakl im Menü *Mein Konto » Meine Produktdaten-Einstellungen*.]

include::partial$catalogue-assistant-config.adoc[]

[#datenfelder-zuordnen]
=== Datenfelder im Katalog zuordnen

Ordne nun die Marktplatz-Datenfelder im Katalog den in plentymarkets gespeicherten Artikeldaten zu.

Informationen dazu, welche Daten für welches Datenfeld des Marktplatzes übertragen werden müssen, findest du in der Dokumentation des Marktplatzes.

include::partial$catalogue-mapping.adoc[]

[#recommended-mappings]
=== Empfehlungen für Datenfeld-Zuordnungen

include::partial$recommendation-text.adoc[]

[[katalog-mirakl-zuordnungen]]
.{market}-Zuordnungen
[cols="1,2a"]
|===
|Marktplatz-Datenfeld |plentymarkets Datenfeld

| *Brand*
a| Erstelle für dieses Marktplatz-Datenfeld eine Eigenschaft vom Typ *Text*.

*_Tipp:_* Alle möglichen Werte findest du in der entsprechenden CSV-Datei. +

| *Title*
a| Ordne für dieses Marktplatz-Datenfeld eines oder mehrere der folgenden plentymarkets Datenfelder zu. Verwende mindestens 20 und maximal 100 Zeichen. +
*_Hinweis:_* Du kannst nur reinen Text übertragen. HTML-Tags sind _nicht_ zulässig.

* *Artikeltext » Name 1*

_oder_

* *Artikeltext » Name 2*

_oder_

* *Artikeltext » Name 3*

_oder_

* Eigenschaft

| *SHOP_SKU*
a| Ordne für dieses Marktplatz-Datenfeld das folgende plentymarkets Datenfeld zu:

* *SKU » SKU*

Ordne das folgende plentymarkets Datenfeld als Ausweich-Datenfeld zu:

* *Variante » Varianten-ID*

| *EAN*
a| Ordne für dieses Marktplatz-Datenfeld das folgende plentymarkets Datenfeld zu:

* *Barcode » GTIN 13*

| *Seller Product ID*
a| Ordne für dieses Marktplatz-Datenfeld das folgende plentymarkets Datenfeld zu:

* *SKU » SKU*

Ordne das folgende plentymarkets Datenfeld als Ausweich-Datenfeld zu:

* *Variante » Varianten-ID*

| *Weight (according to the manufacturer)*
a| Ordne für dieses Marktplatz-Datenfeld das folgende plentymarkets Datenfeld zu:

* *Variante » Gewicht Brutto g*

_oder_

* *Variante » Gewicht netto g*

| *Width**
a| Ordne für dieses Marktplatz-Datenfeld das folgende plentymarkets Datenfeld zu:

* *Variante » Breite mm*

| *Height**
a| Ordne für dieses Marktplatz-Datenfeld das folgende plentymarkets Datenfeld zu:

* *Variante » Höhe mm*

| *Depth**
a| Ordne für dieses Marktplatz-Datenfeld das folgende plentymarkets Datenfeld zu:

* *Variante » Länge mm*

| _Datenfelder für Bilder_
| Beim Marktplatz {market} werden Katalogzuordnungen für Produktbilder aktuell ignoriert. Variantenbilder werden automatisch exportiert. Die Bilder werden anhand der Bildposition priorisiert.

*_Beispiel:_* Für das Marktplatz-Datenfeld *Main Product Image* wird das Bild der Variante mit der niedrigsten Position exportiert.

Die folgenden Marktplatz-Datenfeld werden also automatisch befüllt, egal welches plentymarkets Datenfeld du zuordnest:

* Main Product Image
* Additional Product Image 1
* Additional Product Image 2

| _Datenfelder mit Zusatz *(ES)*_
|
Ordne Marktplatz-Datenfelder mit dem Zusatz *(ES)* kein plentymarkets Datenfeld zu. Deine Produkte werden trotzdem zu MIRAKL exportiert.
|===

[#marktplatzspezifische-werte]
=== Markplatzspezifische Werte übertragen

Der Marktplatz verlangt für die Übertragung von Produktdaten bei den meisten Attributen spezifische Werte. Diese sind derzeit allerdings noch nicht in dieser Form an der Variante hinterlegt. +
*_Beispiel:_* Für das Attribut *Brand* ist beispielsweise *test* nicht erlaubt. Hier muss der entsprechende Code übergeben werden - in diesem Beispiel *BRAND_12345678*.

Im Katalog werden die für Marktplatzattribute gültigen Parameter in Klammern hinter dem Attribut angezeigt. Kontaktiere dein:e Ansprechpartner:in bei MediaMarkt für Informationen zu den gültigen Attributwerten.

=== Gültige Attributwerte zuordnen und übertragen

Hast du - je nach Variante, die übertragen werden soll - unterschiedliche Attributwerte, die gültig sein könnten, stellt sich zunächst die Frage, über welche Vorgehensweise du deine Artikeldaten aktuell hältst.
Verwaltest du deine Artikeldaten manuell, ist eine Eigenschaft vom Typ *Auswahl* empfehlenswert. Hier kannst du für die Auswahl eine Beschreibung hinterlegen. Diese wird dann in der Übersicht der Eigenschaften an der Variante angezeigt.
Wenn der Code der Eigenschaft zugeordnet wurde, kannst du den realen Namen der Variante im Feld *Beschreibung* verwenden. Das bedeutet, über den Katalog wird dann der Code übertragen und dahinter in Klammern der reale Name angezeigt. +

*_Tipp:_* Wenn du für ein Attribut immer nur einen einzigen Wert übertragen möchtest, z.B. als Marke immer *BRAND_12345678*, kannst du die Option *Eigener Wert* im Katalog verwenden.

[discrete]
=== Vorhandene Angebote auf MediaMarkt nicht überschreiben

Wenn du bereits Artikel bei MediaMarkt verkaufst, musst du die Varianten in plentymarkets mit ProductIDs versehen. Dies stellt sicher, dass die vorhandenen Produktdaten nicht überschrieben und nur neue Angebote zu den Produkten erstellt werden. Beim Übertragen von Produktdaten wird also eine ProductID an MediaMarkt übermittelt. Die ProductID ist wichtig, um bei der Übertragung von Angebotsdaten eine Verbindung zwischen Angebot und Produkt herzustellen.

Standardmäßig wird bei der Übertragung eines Produktes, für das noch keine Marktplatz-SKU hinterlegt wurde, automatisch die Varianten-ID als Marktplatz-SKU gespeichert. Später bei der Angebotsübertragung wird der Wert, der als Marktplatz-SKU hinterlegt ist, für *sku* und *product-id* verwendet.

Gib im Katalog eine gültige EAN an und übertrage diese an MediaMarkt.

[#prepare-variations]
== Varianten vorbereiten

Bereite nun deine Varianten für {market} vor.

[#variantenverfuegbarkeit]
=== Variantenverfügbarkeit einstellen

:market-availability: {market}
:option-availability: {market}
:mirakl-variantenverfuegbarkeit-aktivieren:
:mirakl-herkunft:

include::partial$variantenverfuegbarkeit.adoc[]

[#varianten-mit-katalog-kategorie-verknüpfen]
=== Varianten mit {market} Katalog-Kategorie verknüpfen

:catalogue-assistant-name: MediaMarkt Catalog
:category-property-name: MediaMarkt Kategoriegruppe

include::partial$catalogue-link-property-for-market-category.adoc[]

[#eigenschaften-mit-varianten-verknuepfen]
=== Eigenschaften mit Varianten verknüpfen und Werte speichern

include::partial$properties-link.adoc[]

[#produkt-und-angebotsdaten]
== Produkt- und Angebotsdaten übertragen

:profile-free-shipping: Free Shipping (FS)
:market-backend-shipping: Platform Settings » Shipping

include::partial$mirakl-data-product-data-export.adoc[]

[#catalogue-activation]
== Katalogexport aktivieren

:interval: täglich
:market: {market}

include::partial$catalogue-activation.adoc[]


[#auftragsabwicklung-automatisieren]
== Auftragsabwicklung automatisieren

Die folgenden Schritte der Auftragsabwicklung kannst du mit Ereignisaktionen automatisieren:

* Informiere MediaMarkt darüber, dass der Auftrag bestätigt wurde. <<#auftragsbestaetigung-mediamarkt, Wie?>>

* Informiere MediaMarkt darüber, dass der Auftrag abgelehnt wurde. <<#auftragsablehnung-mediamarkt, Wie?>>

* Informiere MediaMarkt darüber, dass der Versand bestätigt wurde. <<#versandbestaetigung-mediamarkt, Wie?>>

* Informiere MediaMarkt darüber, dass der Auftrag storniert wurde. <<#auftragsstornierung-mediamarkt, Wie?>>

* Informiere MediaMarkt darüber, dass eine Erstattung für den Auftrag gezahlt wurde. <<#rueckerstattung-mediamarkt, Wie?>>

* Sende die Rechnung an MediaMarkt. <<#rechnung-mediamarkt, Wie?>>

include::partial$mirakl-further-EPs.adoc[]

[#auftragsbestaetigung-mediamarkt]
=== Auftragsbestätigung an MediaMarkt melden

include::partial$mirakl-EP-order-confirmation.adoc[]

[#auftragsablehnung-mediamarkt]
=== Auftragsablehnung an MediaMarkt melden

include::partial$mirakl-EP-order-rejection.adoc[]

[#versandbestaetigung-mediamarkt]
=== Versandbestätigung an MediaMarkt melden

include::partial$mirakl-EP-shipping-confirmation.adoc[]

[#auftragsstornierung-mediamarkt]
=== Auftragsstornierung an MediaMarkt melden

include::partial$mirakl-EP-cancellation.adoc[]

[#rueckerstattung-mediamarkt]
=== Rückerstattung an MediaMarkt melden

include::partial$mirakl-EP-refund.adoc[]

[#rechnung-mediamarkt]
=== Rechnung an MediaMarkt senden

include::partial$mirakl-EP-send-invoice.adoc[]

//FAQ
include::partial$mirakl-markets-faq.adoc[]
