= MyToys FAQ
:author: team-plenty-channel
:keywords: 
:description: Hier erhältst du Antworten zu häufigen Fragen rund um MyToys.

Auf dieser Seite findest du eine Liste der häufig gestellten Fragen zu MyToys.
Die Liste der Fragen wird laufend aktualisiert.
Vermisst du eine Information oder ist etwas unklar?
Dann sende uns gern eine Nachricht über die Feedback-Funktion unten auf dieser Seite.

[#artikeldatenexport]
== Artikeldatenexport

[.collapseBox]
.*Warum werden meine Artikel nicht zu MyToys exportiert?*
--
Damit deine Varianten zu MyToys exportiert werden, müssen folgende Voraussetzungen erfüllt sein:

* Im *Tab: Verfügbarkeit* der Variante muss die Marktplatzverfügbarkeit *myToys* hinzugefügt sein.

* Im *Tab: Eigenschaften* der Variante muss die Eigenschaft *myToys Kategoriegruppe* verknüpft sein. Als Wert wird der Formatname des jeweiligen myToys-Katalogs erwartet. Durch diese Verknüpfung erfolgt die Zuordnung zum myToys-Katalog (dieser entspricht der myToys-Kategoriegruppe). Es wird _nicht_ der von dir gewählte Name des Katalogs, sondern der Name des Formats erwartet! +
Beachte, dass die Auswahleigenschafts-ID im Katalog mit der Eigenschaft *myToys Kategoriegruppe* (im Menü *Einrichtung » Einstellungen » Eigenschaften » Konfiguration*) übereinstimmen muss.

* Der Katalog, der exportiert werden soll, ist *aktiv*.

* Die Variante ist *aktiv* (*Tab: Einstellungen*, im Bereich *Verfügbarkeit*).

* Der Zeitstempel der Variante darf nicht älter als 24 Stunden sein. +
Wie du den Zeitstempel einer Variante aktualisieren kannst, erfährst du hier.
// LINK EINFÜGEN!!!

* Außerdem muss die Variante mindestens mit allen Pflichtfeldern des jeweiligen Katalogs verknüpft sein. Pflichtfelder sind im Katalog mit einem Sternchen (*) gekennzeichnet.
// LINK EINFÜGEN!!!
--

[.collapseBox]
.*Wie finde ich heraus, ob an meinen Varianten oder Artikeln Pflichtfelder fehlen?*
--
Wenn deine Artikel zu MyToys übertragen werden sollen, kannst du im Log prüfen, welche Pflichtfelder für deine Varianten noch fehlen. +

Wie das geht, erfährst du hier.
//LINK EINFÜGEN!!!
--

[.collapseBox]
.*Wie deaktiviere ich meine Artikel auf MyToys?*
--
Wenn ein Artikel bereits an MyToys übertragen wurde, du diesen Artikel aber nicht weiter bei MyToys listen willst, dann reicht es nicht aus, den Artikel vom Export auszuschließen. Der Artikel muss stattdessen einmalig als inaktiv übertragen werden. Gehe dazu wie folgt vor:

* Entferne im *Tab: Verfügbarkeit* der jeweiligen Variante die Marktplatzverfügbarkeit *myToys*.

*_Wichtig!_* Damit der Artikel als inaktiv übertragen wird, muss im *Tab: Eigenschaften* der jeweiligen Variante die Eigenschaft *myToys Kategoriegruppe* hinterlegt bleiben. Bitte lösche keine SKUs!
--

[.collapseBox]
.*Wie kann ich prüfen, welche Artikel zu MyToys übertragen wurden?*
--
Du kannst dich mit deinen SFTP-Anmeldedaten (zum Beispiel aus dem MyToys-Einrichtungsassistenten) auf dem FTP-Server anmelden. Nutze dazu zum Beispiel ein Programm wie FileZilla.

Hier findest du die SFTP-Anmeldedaten:

* im Menü *Einrichtung » Assistenten » Plugins » [Plugin-Set für MyToys auswählen] » MyToys-Grundeinstellungen » SFTP-Einstellungen* findest du diese Daten (anbei Beispieldaten von Anmeldedaten):

// BILD EINFÜGEN!!!

Die Daten gibst du in ein dafür geeignetes Programm ein.

Wenn du dich angemeldet hast, kannst du den Inhalt der Ordner prüfen.

Die für dich relevanten Ordner kurz erklärt:

* *Archiv*
Hier liegen die erfolgreich an MyToys übergebenen Artikel im XML-Format. Wenn du den Ordner öffnest und eine Datei herunterlädst, kannst du mithilfe deiner Varianten-ID/EAN nach deinen Artikeln suchen.

* *Error*
Hier findest du Dateien, die auf einen Fehler gelaufen sind. Meist sind hier Stock-Dateien (also Bestandsdateien) zu finden. Gerade am Anfang deiner Einrichtung werden hier aufgrund von fehlenden Artikeln diese Bestandsfehler ausgegeben. +
Außerdem findest du fehlerhafte Artikelübertragungen (wenn vorhanden). Für diese Dateien gibt es jedoch in der Regel auch Log-Meldungen in deinem plentymarkets System. +
Siehe dazu: Wie überprüfe ich das Log nach möglichen Fehlern?
// LINK EINFÜGEN!!!

Daneben findest du dort auch Fehlermeldungen für fehlgeschlagene Versandmeldungen an Mytoys. Siehe auch hier.
// LINK EINFÜGEN!!!
--




[#200]
== 

[.collapseBox]
.**
--


--

[.collapseBox]
.**
--


--