= OTTO OAuth
:keywords: OTTO Market, OTTO OAuth, OTTO
:description: Auf dieser Seite erfährst du, wie du die OTTO OAuth aktivierst.
:author: team-plenty-channel

Mit der OTTO OAuth erhält dein System Zugang zur REST-API von OTTO. Dadurch kann dein System Daten an OTTO in bestimmten zeitlichen Abständen übermitteln. Welche Daten in welchen Zeitabständen übermittelt werden findest du xref:otto-market.adoc#100[hier]. Die OTTO OAUth aktivierst du über den Assistenten *Grundeinstellungen - OTTO Market*. Nach der Aktivierung erhält dein System die notwendigen Daten zur Authentifizierung automatisch. +

Im Gegensatz zu vorher, musst du nun keine zusätzlichen Zugangsdaten für die REST-API von OTTO selbst verwalten, wodurch auch der Verlust oder die Änderung der Zugangsdaten ausbleibt.

[.instruction]
[TIP]
.Notwendige Rechte
====
Beachte, dass nur OTTO Market Nutzer:innen mit Admin-Rechten die OAuth konfigurieren können. Die Nutzer:innen benötigt ebenso das Recht *Dienstleister Freigaben* im OTTO Market Portal *OPC*.
====

[WARNING]
.Umstellungsfrist auf OTTO OAuth
====
Die Aktivierung der OTTO OAuth ist verpflichtend. Du hast bis zum 31.03.2024 Zeit für die Umstellung auf OTTO OAuth.
====

== OTTO OAuth aktivieren

Gehe wie folgt vor, um die OTTO-OAuth in deinem System zu aktivieren:

. Öffne das Menü *Einrichtung » Assistenten » Omni-Channel*.
. Klicke auf den Assistenten *Grundeinstellungen - OTTO Market*.
. Klicke auf den zweiten Punkt *Zugriff auf OTTO Market erlauben*.
. Klicke auf *Zugriff erlauben*, um plentysystems den Zugriff auf OTTO Market zu ermöglichen. +
→ Es öffnet sich eine Weiterleitung zu OTTO Markets.
. Gib hier die Zugangsdaten deines Verkäufer:innen-Kontos ein, um dich bei OTTO Market anzumelden. +
→ Es öffnet sich eine Seite mit Daten, auf die plentysystems Zugriff haben wird.
. Klicke auf *Bestätigen*, um die Autorisierung abzuschließen. +
*Hinweis*: In diesem Schritt gibst du plentysystems Zugriff auf OTTO, dafür wird bei OTTO die *plentysystems* App erstellt. Dann werden immer wieder Authentifizierungstoken für den Datenaustausch erstellt.
. Klicke im Assistenten auf den Schritt *Zusammenfassung*
. Klicke auf *Abschließen*, um deine Änderungen zu speichern.


Nachdem du dich erfolgreich bei OTTO Market autorisiert hast und die App in plentysystems angelegt werden konnte, erscheint der Hinweis "Autorisierung abgeschlossen" im Assistentenschritt *Zugriff auf OTTO Market erlauben*.

Mehr Informationen über das Vorgehen in den Menüs von OTTO findest du link:https://account.otto.market/s/article/Als-Haendler-die-App-eines-Dienstleisters-nutzen[hier^].

[TIP]
.Entfernen des Datenabgleichs
====
Zum Entfernen des Datenabgleichs über OAuth muss die App *plentysystems* im Reiter *Dienstleister* im OTTO Market Portal *OPC* entfernt werden. User:innen benötigen das Recht *Dienstleister-Freigaben*, um Apps einsehen und bearbeiten zu können.  
Gehe mit der Maus über die Bezeichnung der App *plentysystems* und klicke auf *Zugriff entziehen*. Bestätige die Entfernung und der OAuth Workflow ist wieder deaktiviert.
====