= OTTO OAuth
:keywords: OTTO Market, OTTO OAuth, OTTO
:description: Auf dieser Seite erfährst du, wie du die OTTO OAuth aktivierst.
:author: team-plenty-channel

[.instruction]
[TIP]
.Notwendige Rechte
====
Beachte, dass nur OTTO Market Nutzer:innen mit Admin-Rechten die OAuth konfigurieren können. Die Nutzer:innen benötigt ebenso das Recht *Dienstleister Freigaben*.
====

[WARNING]
.Umstellungsfrist auf OTTO OAuth
====
Die Aktvierung der OTTO OAuth ist verpflichtend. Du hast bis zum 31.03.2024 Zeit für die Umstellung auf OTTO OAuth.
====

== OTTO OAuth aktivieren

Gehe wie folgt vor, um die OTTO-OAuth in deinem System zu aktivieren:

. Öffne das Menü *Einrichtung » Assistenten » Omni-Channel*.
. Klicke auf den Assistenten *Grundeinstellungen - OTTO Market*.
. Klicke auf den zweiten Punkt *Zugriff auf OTTO Market erlauben*.
. Klicke auf *Zugriff erlauben*, um plentysystems den Zugriff auf OTTO Market zu ermöglichen. +
→ Es öffnet sich eine Weiterleitung zu OTTO Markets.
. Gib hier die Zugangsdaten deines Verkäufer:innen-Kontos ein, um dich bei OTTO Market anzumelden. +
→ Es öffnet sich eine Seite mit Daten, auf die plentysystems Zugriff haben wird.
. Klicke auf *Bestätigen*, um die Autorisierung abzuschließen. +
*Hinweis*: In diesem Schritt werden Authentifizierungstokens erstellt. Diese Tokens werden für den Datenaustausch zwischen OTTO Market und plentysystems benötigt.
. Klicke im Assistenten auf den Schritt *Zusammenfassung*
. Klcke aud *Abschließen*, um deine Änderungen zu speichern.

Mehr Informationen über das Vorgehen in den Menüs von OTTO findest du link:https://account.otto.market/s/article/Als-Haendler-die-App-eines-Dienstleisters-nutzen[hier^].

[TIP]
.Entfernen des Datenabgleichs
====
Zum Entfernen des Datenabgleichs über OAuth muss die App *plentysystems* im Reiter *Dienstleister* im OTTO Market Portal *OPC* entfernt werden. User:innen benötigen das Recht *Dienstleister-Freigaben*, um Apps einsehen und bearbeiten zu können.  
Gehe mit der Maus über die Bezeichnung der App *plentysystems* und klicke auf *Zugriff entziehen*. Bestätige die Entfernung und der OAuth Workflow ist wieder deaktiviert.
====