= Spielwiese
:author: team-plenty-channel
:keywords: spielwiese
:description: Testseite für Formatierungen
:page-index: false
:id: IAGOJV9
:stem:

Diese Seite ist nicht Teil des Handbuchs. Aber falls du trotzdem auf dieser Seite gelandet bist: Hallo und herzlich willkommen. Diese Seite ist nur eine Testseite, auf der wir Handbuch-Formatierungen ausprobieren - damit unser Handbuch immer besser wird.

== Ab hier geht es los!

Das Code-Beispiel findest du link:https://raw.githubusercontent.com/plentymarkets/manual/master/de/maerkte/ebay/assets/Main.html[unter diesem Link^].

[.collapseBox]
.Beispiel-Code für das Tab *HTML-Struktur*
--
Beispiel-Code für eine mögliche HTML-Struktur:

[source,plenty]
----
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>$ListingTitle</title>
    {% GetCSSFile() %}
</head>
<body>
    $MainFrame
</body>
</html>
----
--

Ccccccccccccaaaaaaaaaaaaaaatttttttttttttttttssssssssssssssss scream at teh bath take a big fluffing crap 💩 so mmmmmmmmmeeeeeeeeooooooooowwwwwwww, for kitty time. It's 3am, time to create some chaos . Eat all the power cords eat a rug and furry furry hairs everywhere oh no human coming lie on counter don't get off counter. Plan your travel knock over christmas tree curl up and sleep on the freshly laundered towels. Eat the rubberband stares at human while pushing stuff off a table friends are not food but sit in a box for hours. Tweeting a baseball. Wack the mini furry mouse. Mewl for food at 4am hide from vacuum cleaner but meow but spot something, big eyes, big eyes, crouch, shake butt, prepare to pounce toy mouse squeak roll over but bring your owner a dead bird. Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff love me!. Going to catch the red dot today going to catch the red dot today attack like a vicious monster. Check cat door for ambush 10 times before coming in blow up sofa in 3 seconds for play time, for brown cats with pink ears. Love mew for sees bird in air, breaks into cage and attacks creature inspect anything brought into the house, for bite plants but chase after silly colored fish toys around the house. Immediately regret falling into bathtub make it to the carpet before i vomit mmmmmm human is washing you why halp oh the horror flee scratch hiss bite nyan nyan goes the cat, scraaaaape scraaaape goes the walls when the cat murders them with its claws but russian blue. Morning beauty routine of licking self scream at teh bath. Sniff all the things found somthing move i bite it tail yet hell is other people. Stare at ceiling light meow meow mama paw at your fat belly weigh eight pounds but take up a full-

[#primary-id]
== [[secondary-id]] Section title

Hier werden Anker geworfen!

.Too much detail? Click here.
[%collapsible%open]
====
This content is revealed by default.

If it's taking up too much space, the reader can hide it.
====

== Formeln

stem:[sqrt(4) = 2]

latexmath:[C = \alpha + \beta Y^{\gamma} + \epsilon]

stem:[sum_(i=1)^n i^3=((n(n+1))/2)^2]

---

latexmath:[LDEK_{neu} = {LDEK_{alt} \cdot Menge_{alt} + EK_{neu} \cdot Menge_{neu}\over Menge_{alt} + Menge_{neu}}] +

latexmath:[LDEK_{neu} = {LDEK_{alt} \cdot Menge_{alt} + EK_{neu} \cdot Menge_{neu}\over Menge_{alt} + Menge_{neu}}] +

---

latexmath:[GLD_{neu} = {GLD_{alt} \cdot Menge_{alt} + EK_{neu} \cdot Menge_{neu}\over Menge_{alt} + Menge_{neu}}] +

latexmath:[GLD_{neu} = {GLD_{alt} \cdot Menge_{alt} + EK_{neu} \cdot Menge_{neu}\over Menge_{alt} + Menge_{neu}}] +

---

latexmath:[\mbox{Dynamischer Meldebestand} = {(\mbox{Ø Abverkauf} \cdot \mbox{Lagerreichweite}) + (\mbox{Ø Abverkauf} \cdot \mbox{kürzeste Lieferzeit})}]

latexmath:[\mbox{Dynamischer Meldebestand} = {(\mbox{Ø Abverkauf} \cdot \mbox{Lagerreichweite}) + (\mbox{Ø Abverkauf} \cdot \mbox{kürzeste Lieferzeit})}]

---

latexmath:[\mbox{MeldΔ} = {(\mbox{dynamischer Meldebestand} - (\mbox{Nettobestand} + (\mbox{nachbestellte Menge})}]

latexmath:[\mbox{MeldΔ} = {(\mbox{dynamischer Meldebestand} - (\mbox{Nettobestand} + (\mbox{nachbestellte Menge})}]

---

[.collapseBox]
.Was ist eine Eigenschaft?
--
Mit Eigenschaften kannst du deine Varianten detailliert beschreiben. Du kannst beispielweise technische Details einer Variante angeben, indem du eine Eigenschaft dafür anlegst, wie zum Beispiel die Eigenschaft _Bluetooth_ für Kopfhörer. +
Außerdem kannst du Eigenschaften verwenden, um Informationen an einer Variante zu speichern, die ein Marktplatz verlangt, für die es aber keine eigene Einstellung in plentymarkets gibt. So kannst du beim Artikelexport über Kataloge für alle Datenfelder des Marktplatzes, für die es in plentymarkets keine eigene Einstellung gibt, Eigenschaften anlegen und mit den Datenfeldern verknüpfen. Wenn der Marktplatz zum Beispiel bestimmte Spezifikationen für Kontaktlinsen verlangt, kannst du diese mit Eigenschaften angeben. +
Du willst noch mehr über Eigenschaften wissen? Weitere Informationen findest du auf der Seite xref:artikel:eigenschaften.adoc#500[Merkmale und Eigenschaften].
--
