= Wayfair
:author: team-plenty-channel
:keywords: Wayfair
:description: Hier erfährst du, wie du den Marktplatz Wayfair in plentymarkets einrichtest, damit du deine Artikel auf Wayfair verkaufen kannst. 
:wayfair:
:market: Wayfair
:plugin: Wayfair
//:main-client:
:plugin-link: https://marketplace.plentymarkets.com/wayfair_6273
:page-index: false

Mit dem Wayfair-Plugin verkaufst du deine Varianten über plentymarkets auf dem Marktplatz Wayfair. Das Plugin bietet mehrere Integrationen in die Schnittstellen von Wayfair, einschließlich die folgenden Vorgänge:

* Automatisches Abrufen von Wayfair-Bestellungen mit Umstellung auf plentymarkets Bestellungen​
* Automatisches Senden von plentymarkets Bestandsinformationen an Wayfair, um die Artikelverfügbarkeit aktuell zu halten​
* Automatisches Übertragen von Wayfair-generierten Versanddokumenten an plentymarkets
* Änderungen des Bestellstatus in plentymarkets an Wayfair senden, um Wayfair-Kund:innen und den Wayfair-Kundensupport auf dem neuesten Stand zu halten

== Bei Wayfair registrieren

Wayfair ist ein geschlossener Marktplatz. Die Verwendung des Wayfair Plugins ist auf Organisationen beschränkt, die sich als Wayfair-Lieferant:in registriert haben. ​Wenn du noch nicht auf Wayfair verkaufst, regisitriere dich als Partner:in auf der Website von Wayfair, um loszulegen.

//TODO: Link zur Registrierung

== Vorbereitungen

Für die Verwendung des Wayfair-Plugins sind Wayfair-API-Anmeldeinformationen erforderlich, denen die entsprechenden Rechte erteilt wurden.

Befolge vor der Installation diese Anweisungen, um Wayfair zu kontaktieren und die API-Schnittstelle einzurichten.​

=== API-Anmeldeinformationen abrufen

Damit das Wayfair-Plugin eine Verbindung zu Wayfair-Systemen herstellen kann, musst du deine eindeutigen API-Anmeldeinformationen angeben.

Gehe folgendermaßen vor, um die API-Anmeldeinformationen für deine Organisation zu erhalten:

==== E-Mail an Wayfair senden

Sende eine E-Mail an deine Wayfair-Account-Manager:in, um Unterstützung anzufordern. Setze außerdem johara1@wayfair.com auf CC.

Die E-Mail muss die folgenden Informationen enthalten:

[cols="1,3a"]
|===
| *Betreff*
| Zugriff auf das plentymarkets Plugin / [Name deines Unternehmens] [deine Wayfair-Lieferanten-ID]

| *Inhalt*
|
* Deine Kontaktinformationen
* Eine kurze Beschreibung, wie du das Wayfair-Plugin von plentymarkets verwenden möchtest
* Datum, ab dem du bereit bist, das Wayfair-Plugin von plentymarkets zu verwenden
|===

Du erhältst umgehend eine Antwort mit den folgenden Angaben: 

* Bestätigung deines eingerichteten API-Zugriffs 
* Lieferanten-ID(s) für deine Lager

==== Anmeldedaten generieren

[.instruction]
Anmeldeinformationen generieren:

. Gehe zu link:https://partners.wayfair.com/developer/applications[https://partners.wayfair.com/developer/applications].
. Gib deine Anmeldedaten für Wayfair Partner Home ein. +
→ Du wirst zur Wayfair-Anwendungsverwaltung weitergeleitet.
. Klicke auf der Seite *Anwendungsverwaltung* unten auf die Schaltfläche *+ Neue Anwendung*. +
→ Das Formular *Neue Anwendung* wird angezeigt.
. Gib einen nützlichen *Name* für die Anwendung ein, zum Beispiel `[Name deines Unternehmens] plentymarkets Plugin`.
. Gib eine nützliche *Beschreibung* für die Anwendung ein, zum Beispiel `plentymarkets Plugin-Anwendung für [Name deines Unternehmens] Go-Live im Herbst 2023`.
. Setze den Schieberegler am unteren Rand des Dialogfelds auf *Produktion*, wenn Wayfair nichts anderes anordnet.
. Klicke im Dialogfeld auf *Speichern*, um die Anmeldeinformationen der Anwendung anzuzeigen. +
→ Die *Kunden-ID* und das *Kundengeheimnis* werden angezeigt.
. Kopiere die *Kunden-ID* und das *Kundengeheimnis*. Diese Anmeldedaten benötigst du, um das Wayfair-Plugin für die Verwendung der Wayfair-Systeme zu autorisieren. +
*_Wichtig:_* Das *Kundengeheimnis* kann nach diesem Zeitpunkt nicht mehr abgerufen werden. Wenn das Original verloren geht, muss ein neues Kundengeheimnis generiert werden.
. Schließe das Dialogfeld mit den Anmeldedaten, um die Informationen zu schützen.

== Wayfair-Plugin installieren

Jetzt installierst du das Wayfair-Plugin in deinem plentymarkets System.

=== Voraussetzungen

Die folgenden Voraussetzungen müssen erfüllt sein, damit du das Plugin installieren kannst:

* Du hast ein plentymarkets System.
* Du hast Administratorrechte für das plentymarkets System, in dem das Wayfair-Plugin installiert werden soll.
* Du hast wie oben beschrieben die Wayfair API-Anmeldedaten generiert und zur Hand.

[#plugin-download]
=== Plugin installieren

Um Wayfair in plentymarkets nutzen zu können, musst du das Wayfair-Plugin in deinem plentymarkets System installieren.

include::partial$plugin-installation.adoc[]

=== Zugriff auf Wayfair-Schnittstellen autorisieren

Nachdem du das Plugin in deinem plentymarkets Plugin-Set installiert und bereitgestellt hast, muss das Plugin so konfiguriert werden, dass beim Herstellen einer Verbindung zu den Wayfair-Schnittstellen die richtigen Anmeldedaten verwendet werden.

* *Das Autorisierungsverfahren muss für jedes Plugin-Set durchgeführt werden, das das Wayfair-Plugin enthält.*

[.instruction]
Zugriff auf Wayfair-Schnittstelle autorisieren:

. Öffne das plentymarkets Menü *Plugins » Plugin-Set-Übersicht*.
. Suche das Plugin-Set, das mit dem Mandanten verknüpft ist, mit dem Wayfair verwendet wird. 
. Klicke auf das gewünschte Plugin-Set.
. Klicke in der Wayfair-Zeile des Plugin-Sets auf die Schaltfläche *Einstellungen*.
. Gehe im Menü auf der linken Seite zu *Konfiguration » Globale Einstellungen*.
. Gib im Bereich *Lieferanteneinstellungen* die Werte *Client ID* und *Client Secret* ein, die deinen Wayfair-API-Anmeldedaten entsprechen.
. Ändere die Einstellung *Modus* zu *Live*.
. Klicke in der Symbolleiste über den Einstellungen auf die Schaltfläche *Speichern*.
. Wiederhole diese Schritte für jedes Plugin-Set, in dem du das Wayfair-Plugin nutzt.

== Marktplatz in plentymarkets einrichten

Du hast das Wayfair-Plugin installiert? Super. Nun richtest du den Marktplatz in plentymarkets ein.

=== Auftragsherkunft aktivieren

:referrer: Wayfair
:referrer-option: pass:quotes[Option *Wayfair*]

include::maerkte:partial$auftragsherkunft-aktivieren.adoc[]

=== Versanddienstleister erstellen

Führe die folgenden Schritte aus, um einen Wayfair-Versanddienstleister zu erstellen.

[.instruction]
Versanddienstleister erstellen:

. Öffne das plentymarkets Menü *Einrichtung » Aufträge » Versand » Optionen*.
. Wechsele in das Tab *Versanddienstleister*.
. Klicke auf *+ Neu*. +
→ Eine neue Zeile wird eingeblendet.
. Fülle in dieser Zeile das Feld *Name* aus. +
*_Tipp:_* Wir empfehlen den Namen *WayfairShipping*.
. Wähle in der Dropdown-Liste *Versanddienstleister* die Option *WayfairShipping* Alle anderen Felder der Zeile können leer bleiben. +
*_Tipp:_* Die Option *WayfairShipping* ist nicht verfügbar? Dieser Typ wird vom Wayfair-Plugin bereitgestellt. Stelle also sicher, dass du das Plugin korrekt installiert und bereitgestellt hast.
. Klicke auf *Speichern*.

=== Versandprofil erstellen

Jede Bestellung verfügt über ein Versandprofil, das verwendet wird, um Artikel aus einer Bestellung zu versenden. Führe diese Schritte aus, um ein Versandprofil für Wayfair zu erstellen.

[.instruction]
Versandprofil erstellen:

. Öffne das plentymarkets Menü *Einrichtung » Aufträge » Versand » Optionen*.
. Wähle die Registerkarte *Versandprofile*.
. Wenn bereits eine Zeile *Wayfair* vorhanden ist, klicke auf diese Zeile. Andernfalls klicke auf die Schaltfläche *Neu*. Die Einstellungen des Versandprofils werden angezeigt.
. Wähle deinen Wayfair-Versanddienstleister aus dem bereitgestellten Menü. +
*_Tipp:_* Dieser Veranddienstleister heißt *WayfairShipping*, wenn du den Versanddienstleister wie empfohlen erstellt hast.
. Fülle die Felder aus, die sich auf *Name* beziehen. +
*_Tipp:_* Eer Einfachheit halber empfehlen wir *WayfairShipping* für alle Namen.
. Stelle die Sprache über das Menü rechts neben dem Feld *Name*
ein.
. Wähle im Feld *Markierung* das Symbol für Wayfair-Bestellungen (*6* und *126* sind gute Optionen, da sie das Wayfair-Farbschema widerspiegeln).
. Ändere im Feld *Priorität* optional die Priorität (wir empfehlen, sie als Standardpriorität *höchste* zu belassen).
. Stelle im Feld Clients (Stores) sicher, dass du alle Stores auswählst, die für Wayfair eingerichtet werden können.
. Setze in der Liste *Auftragsherkunft* ein Häkchen neben alle *Wayfair* bezogenen Einträge.
. Klicke oben auf der Seite auf die Schaltfläche *Speichern*.
. Beachte, dass das neue (oder aktualisierte) Versandprofil aufgeführt ist.

==== Optional: Versandprofil für Wayfair-Bestellungen automatisch festlegen

[.instruction]
[Optional] Versandprofil automatisch für Wayfair-Bestellungen festlegen:

. Öffne das plentymarkets Menü *Einrichtung » Aufträge » Ereignisse*.
. Klicke auf *Ereignisaktion hinzufügen* (die Schaltfläche *+*
unten links auf der Seite), um das Dialogfeld
*Neue Ereignisaktion erstellen* zu öffnen.
. Gib einen Namen ein, z.B. *Wayfair order Shipping Mapping*.
. Wähle das Ereignis *Neuer Auftrag* dem Dropdown-Menü.
. Klicke im Dialogfeld auf die Schaltfläche *Speichern* Das neue
Verfahren wird nun ausgewählt, wobei der Abschnitt *Einstellungen*
angezeigt wird.
. Aktiviere im Abschnitt *Einstellungen* der Ereignisaktion das
Kontrollkästchen *Aktiv*.
. Klicke auf die Schaltfläche *Filter hinzufügen* (die Schaltfläche
*+* oben im Abschnitt *Filter*), um das Dialogfeld *Filter hinzufügen*
zu öffnen.
. Wähle *Auftrag » Herkunft*.
. Klicke auf die Schaltfläche *Hinzufügen*, um den Dialog
abzuschließen. Auf dem Formular wird nun ein *Herkunft*-Filter
angezeigt.
. Aktiviere in der Liste *Herkunft* das Kontrollkästchen für alle
*Wayfair* bezogenen Herkunft.
. Klicke auf die Schaltfläche *Aktion hinzufügen* (die Schaltfläche
*+* oben im Abschnitt *Aktionen*), um das Dialogfeld
*Aktion hinzufügen* zu öffnen.
. Wähle *Auftrag » Versandprofil ändern*.
. Klicke auf die Schaltfläche *Hinzufügen*, um den Dialog
abzuschließen. Im Bereich *Aktionen* wird eine Aktion
*Versandprofil ändern* angezeigt.
. Klicke auf das Symbol Karat ganz links in der Zeile
*Versandprofil ändern* *- dies ist NICHT die große quadratische
Schaltfläche, auf der sich auch ein Hochzeichen befindet -* um die
Details der Prozedur zu erweitern.
. Wähle im Dropdown-Menü der Aktion das für *Wayfair* erstellte
Versandprofil
. Klicke oben auf der Seite auf die Schaltfläche *Speichern*

==== Wayfair-Bestellartikel mit plentymarkets Artikeln verknüpfen

Um eingehende Bestellungen von Wayfair ordnungsgemäß verarbeiten zu
können, muss das Wayfair-Plugin die Lieferanten-Teilenummern aus
Wayfairs Systemen mit einem bestimmten Feld von Artikel varianten in
plentymarkets abgleichen. Standardmäßig geht das Wayfair-Plugin davon
aus, dass die *Variantennummer* *(nicht die ID der Varianten)* der
Varianten eines Artikels in plentymarkets mit der Teilenummer des
Wayfair-Lieferanten übereinstimmt.

Wenn die Lieferanten-Teilenummern für deine Organisation in einem
alternativen Feld in deinen plentymarkets Artikelvarianten angezeigt
werden, ändere den Wert von *Methode zur Artikelzuweisung*

==== Artikel auf Wayfair zum Verkauf anbieten

Artikel, die du auf Wayfair verkaufen möchtest, müssen in plentymarkets
als aktiv markiert werden. Der Benutzer von plentymarkets kann auch
festlegen, welche Artikel auf Wayfair zum Verkauf stehen. *Beachte,
dass der Lagerbestand und die bestellten Artikel auf der Ebene der
Varianten gesteuert werden.*

==== plentymarkets zum Senden von Versandsbestätigungen (ASN) an Wayfair konfigurieren

===== Wayfair-Plugins einstellen, um die richtigen Versandinformationen an Wayfair zu senden

Lieferanten, die Bestellungen über ihre eigenen Konten versenden möchten (statt die Versanddienste von Wayfair zu nutzen), müssen die Konfigurationseinstellungen für Versandbestätigung (ASN)

Wenn die Versanddienste von Wayfair verwendet werden sollen, sollten die ASN-Einstellungen des Wayfair-Plugins in ihren Standardeinstellungen (*Wayfair-Versand*) belassen werden.

===== Ereignis für plentymarkets Bestellungen erstellen, das Versandinformationen an Wayfair sendet

[.instruction]
Ereignis für plentymarkets Bestellungen erstellen, das Versandinformationen an Wayfair sendet:

. Öffne das plentymarkets Menü *Einrichtung » Aufträge » Ereignisse*.
. Klicke auf *Ereignisaktion hinzufügen* (die Schaltfläche *+*
links am Seitenende).
. Gib  einen beliebigen *Name* ein
. Wähle im Feld *Ereignis* die Option *Statuswechsel* (in der
Kategorie *Auftragsänderung*).
. Wähle im Feld unter *Ereignis* die Statusänderung, die das Senden einer ASN an Wayfair auslösen soll, z.B. *In Versandvorbereitung*.
. Klicke auf die Schaltfläche *Speichern*. +
→ Du wirst automatisch zur neu erstellten Ereignisaktion umgeleitet. 
. Setze im Abschnitt *Einstellungen* der Ereignisprozedur ein Häkchen neben *Aktiv*.
. Klicke auf *Filter hinzufügen* und gehe zu *Auftrag* »
*Herkunft*, um die Herkunft als Filter hinzuzufügen.
. Klicke auf *+ Hinzufügen*. +
→ Im Abschnitt *Filter* wird ein Feld mit einer Liste aller
verfügbaren Auftragsverweise angezeigt. 
. Setze ein Häkchen neben allen *Wayfair*-Auftragsempfängern.
. Klicke auf das *+* neben *Aktionen*.
. Wähle *Versandbestätigungen (ASN) an Wayfair senden* in der
Kategorie *Plugins*:
. Klicke auf die Schaltfläche *Hinzufügen*.
. Klicke auf die Schaltfläche *Speichern*.

==== 7. Erster Warenbestandabgleich

Sobald alles eingerichtet ist, ist es an der Zeit, dass das Wayfair-Plugin Artikel auf Wayfair zum Verkauf anbietet.

* Navigiere zur Inventarseite in den Wayfair-Markteinstellungen.
* Warte eine Minute, während das System die Inventarinformationen aktualisiert.
* Überprüfe die auf der Seite angezeigten Informationen.
* Wenn Probleme für die vollständige Inventarsynchronisierung gemeldet
werden, versuche, diese Probleme zu beheben, indem du die Anweisungen für
die Inventarseite liest, die plentymarkets Protokolle anzeigst und den
Leitfaden zur Fehlerbehebung verwendest.

== Anpassung und Überwachung

Das Wayfair-Plugin bietet Nutzern von plentymarkets die Möglichkeit,
sein Verhalten anzupassen und zu überwachen.

=== Die Home Seite

Die Home Seite wird durch Klicken auf *Startseite* im Menü auf der
linken Seite oder durch Klicken auf *Wayfair* in der
Wayfair-Navigationsleiste aktiviert. Derzeit werden keine Informationen
bereitgestellt.

=== Die Lager Seite

Die Lager Seite wird verwendet, um die Lager, die der Lieferant in
plentymarkets verwendet, mit den Wayfair Lieferanten IDs zu verknüpfen,
die dem Lieferanten ausgestellt wurden. Die Zuordnungen werden vom
Wayfair-Plugin verwendet, wenn es Inventar an Wayfair meldet und
Wayfair-Bestellungen verarbeitet, die bei plentymarkets eingehen.

==== Hinweise zu mehreren Lagern pro Wayfair-Lieferanten-ID

Die Seite Lager wird verwendet, um die LAger, die der Lieferant in
plentymarkets nutzt, den Wayfair-Lieferanten-IDs zuzuordnen, die dem
Lieferanten zugewiesen wurden. Die Zuordnungen werden vom Wayfair-Plugin
verwendet, wenn es den Bestand an Wayfair meldet und auch bei der
Verarbeitung von Wayfair-Bestellungen, die bei plentymarkets eingehen.

Wenn du eine Beziehung zwischen Lagerorten und Lieferanten-IDs
auswählst, die nicht eins zu eins ist, überprüfe das Verhalten der
Einstellung Lagerpuffer. Wenn einer Wayfair-Lieferanten-ID mehr als ein
Lager zugewiesen wurde, wird die Artikel-Lager-Zuordnung basierend auf
dem Lagerbestand und dem Land des Lagers priorisiert.

==== Lager-Zuordnung hinzufügen

[.instruction]
Lager-Zuordnung hinzufügen:

. Klicke auf die Schaltfläche *Zuordnung hinzufügen*
. Verwende die linke Spalte, um ein plentymarkets Lager nach Namen
auszuwählen.
* Wenn dem plentymarkets System kürzlich ein Warehouse hinzugefügt
wurde, kann es bis zu fünf Minuten dauern, bis es auf dieser Seite
verfügbar ist.
* Versuche nicht, dasselbe plentymarkets Warehouse für mehr als
eine Zeile auf dieser Seite zu verwenden, da dies eine nicht
unterstützte Konfiguration ist.
. Gib  in der rechten Spalte eine numerische Lieferanten-ID ein.
. Klicke auf die Schaltfläche *Speichern*, sobald die neuen Zeilen
abgeschlossen sind.

==== Lager-Zuordnung entfernen

[.instruction]
Lager-Zuordnung entfernen:

. Suche die zu entfernende Zeile.
. Klicke in der Zeile auf die Schaltfläche *Löschen*.
. Klicke auf die Schaltfläche *Speichern*, sobald die gewünschten Zeilen entfernt wurden.

=== Die Einstellungen-Seite

Diese Seite enthält allgemeine Einstellungen für den Betrieb des Wayfair-Plugins. Einstellungen werden bei Änderungen nicht automatisch gespeichert. Verwende die Schaltfläche *Speichern* unten auf der Seite.

==== Lagerpuffer

Die Einstellung *Lagerpuffer* ist eine nicht negative Ganzzahl, die für
jede Artikelvariante für jede Wayfair Lieferanten ID eine reservierte
Lagermenge festlegt. Der Pufferbetrag wird abgezogen, nachdem alle
anderen Bestandsberechnungen durchgeführt wurden, einschließlich der
Aggregation der Bestände für mehrere plentymarkets Lager, denen dieselbe
Wayfair Lieferanten ID zugewiesen wurde.

Um den *Lagerpuffer* zu deaktivieren, lasse diese Einstellung leer
oder setze sie auf *0*.

=== Standard-Bestellstatus

Die Einstellung *Standard-Bestellstatus* bestimmt, in welchem ​​Status
sich eine neue plentymarkets Bestellung nach der Erstellung durch das
Wayfair-Plugin befinden soll.

*Hinweis:* Die Auftragserstellung gilt nicht als Änderung des
Auftragsstatus. Wenn du den Standardbestellstatus auf einen höheren als
die Statuswerte für konfigurierten plentymarkets Ereignisse setzt,
können einige Ereignisse fehlschlagen.

=== Standardversandanbieter *(nicht genutzt)*

Die Einstellung *Standardversandanbieter* ist eine veraltete Einstellung,
die das Verhalten des Plugins nicht mehr beeinflusst. 
*Wenn diese
Einstellung in deinem System angezeigt wird, empfiehlt Wayfair dringend,
dass du dein Plugin auf eine neuere Version aktualisierst.*

=== Methode zur Artikelzuweisung

Die Einstellung *Methode zur Artikelzuweisung* bestimmt das Verhalten
beim Abgleichen der Artikelvarianten von plentymarkets mit den
Wayfair-Produkten. Es wird verwendet, wenn die Bestandslisten an Wayfair
gesendet werden und um die angeforderten Produkte in einer
Wayfair-Bestellung auszuwählen. Der Benutzer von plentymarkets sollte
diese Einstellung so konfigurieren, dass sie der Art und Weise
entspricht, in der die Elementvarianten ausgefüllt werden.

==== Verwenden der Variantennummer als Elementzuordnungsfeld

Standardmäßig wird das Feld *Variantennummer* für die Zuordnung der
Artikel von Wayfair-Bestellungen zu Artikelvarianten von plentymarkets
verwendet. Die anderen Optionen sind *EAN* (Barcode) und *SKU*.

==== Verwenden von EAN (Barcode) als Elementzuordnungsmethode

Wenn die *Methode zur Artikelzuweisung* auf *EAN* eingestellt ist,
sollte jede Artikelvariante in plentymarkets so eingerichtet werden,
dass sie einen Barcode enthält, der die Wayfair-Lieferanten-Teilenummer
widerspiegelt, die Wayfair in eingehenden Bestelldaten sendet.

==== Verwenden der SKU als Elementzuordnungsmethode

Wenn die *Artikelzuordnungsmethode* auf *SKU* eingestellt ist,
sollte jede Artikelvariante in plentymarkets so eingerichtet werden,
dass sie eine Wayfair-spezifische SKU enthält, die die
Wayfair-Lieferanten-Teilenummer widerspiegelt, die Wayfair in
eingehenden Bestelldaten sendet.

=== Aufträge importieren ab

Die optionale Einstellung *Aufträge importieren ab* bestimmt ein Datum,
ab dem neue Wayfair-Bestellungen als für den Import in das plentymarkets
System berechtigt gelten. Diese Einstellung kann die Leistung
verbessern, indem verhindert wird, dass das Wayfair-Plugin Bestellungen
anfordert, die vor dem angegebenen Datum erstellt wurden. Es kann auch
verwendet werden, um zu verhindern, dass das plentymarkets System
Bestellungen vor einem gewünschten *Go-Live-Datum* annimmt.

=== Die Seite Inventar

Die Seite *Inventar* enthält keine zu konfigurierenden Einstellungen. Es
wird verwendet, um den Status der Synchronisierung des plentymarkets
Inventars mit Wayfair zu überprüfen. Die Daten der Seite werden
regelmäßig aktualisiert, wie durch den Zeitstempel unten angegeben.

=== Hauptstatusanzeige

Oben auf der Seite *Inventar* werden immer ein Symbol und eine Meldung
angezeigt, um den allgemeinen Zustand des
Inventarsynchronisierungsprozesses zu beschreiben.

* Ein Kalendersymbol wird angezeigt, wenn das Wayfair-Plugin noch keine
Inventarsynchronisierung versucht hat.
* Dies geschieht direkt nach der Installation des Plugins.
* Dies kann passieren, wenn das Plugin kürzlich aktualisiert wurde.
* Die Seite ändert sich innerhalb von 15 bis 30 Minuten, sobald das
Synchronisationssystem initialisiert wird.
* Ein Symbol mit einem Häkchen wird angezeigt, wenn das Wayfair Plugin
das Inventar regelmäßig synchronisiert, ohne dass Probleme festgestellt
werden.
* Ein Symbol mit einer durchgestrichenen Wolke wird angezeigt, wenn das
Wayfair-Plugin Unregelmäßigkeiten bei der Inventarsynchronisierung
feststellt.
* Fehler werden erwartet, wenn das Wayfair-Plugin kürzlich installiert
wurde und die Ersteinrichtungnoch nicht abgeschlossen wurde. Beende die Einrichtung des Plugins, bevor du die Seite *Inventar* erneut verwendest.
* Details werden möglicherweise weiter unten auf der Seite angezeigt, um zu erklären, was falsch ist.
* Konsultiere die plentymarkets Logs, um Fehlerdetails zu erhalten.
* Im Handbuch zur Fehlerbehebung des Wayfair-Plugins findest du Ideen
zur Lösung von Problemen bei der Bestandssynchronisierung.

=== Details zur Inventarsynchronisierung

Wenn dies möglich ist, enthält die Seite *Inventar* Details zur
Unterstützung des Hauptstatus, der oben auf der Seite angezeigt wird.

* Ein Kalendersymbol zeigt an, dass eine Information noch nicht
verfügbar ist.
* Ein Symbol mit einem Häkchenzeigt ein positives Ereignis an.
* Ein Symbol mit einer durchgestrichenen Wolke zeigt ein negatives
Ereignis an.
* Ein Symbol mit einem Pfeil nach oben zu einer Wolke !zeigt an, dass
ein Ereignis gerade stattfindet und wird beschrieben, sobald es
abgeschlossen ist.

=== Die Seite Versandsbestätigung (ASN)

Die Seite *Versandsbestätigung (ASN)* wird zum Konfigurieren der
Versandinteraktionen zwischen plentymarkets, dem Wayfair Plugin und
Wayfair verwendet. Die hier bereitgestellten Informationen legen das
Verhalten für den *Versandsbestätigung (ASN) an Wayfair senden*-Prozess
für Bestellungen fest.

=== Versandart

Das Optionsfeld oben auf der Seite enthält diese Optionen. Wayfair gibt
Lieferanten Anweisungen zur Auswahl des richtigen Werts.

* *Wayfair Versand*
* Die Sendungen deiner Bestellungen werden von Wayfair arrangiert und
von einem von Wayfair ausgewählten Spediteur versendet.
* Das plentymarkets System muss Wayfair mitteilen, wann die Bestellung
versandbereit ist.
* Das plentymarkets System muss Tracking-Informationen von Wayfair in
Ihre plentymarkets Bestellungen zurückerhalten.
* *Selbst Versenden*
* Du versendest deine eigenen Bestellungen über deine eigenen Spediteure.
* Das plentymarkets System muss Wayfair mitteilen, wenn du eine
Bestellung versendest.
* Das plentymarkets System muss Wayfair die Tracking-Informationen
mitteilen (Spediteur und Tracking-Nummer).

=== plentymarkets Speditionen zu Wayfair-Speditionen zuordnen

Wenn du die Option *Selbst Versende* auswählst, muss Wayfair die
Versandinformationen von plentymarkets in Daten übersetzen, die es
versteht.

[.instruction]
plentymarkets Speditionen zu Wayfair-Speditionen zuordnen:

. Suche die von Wayfair bereitgestellten Spediteurinformationen.
Wende dich bei Bedarf an johara1@wayfair.com.
. Gib für jeden in der linken Spalte aufgeführten plentymarkets
*Versanddienstleister* den von Wayfair bereitgestellten *SCAC Code* in
die rechte Spalte *Wayfair-Kennziffer des Versanddienstleisters* ein.
. Klicke unten auf der Seite auf *Speichern*

=== Troubleshooting: Häufige Probleme

Bevor du sich an Wayfair wendest, verwende die folgende Tabelle, um Probleme im Wayfair-Plugin selbst zu diagnostizieren.

[[troubleshooting-wayfair]]
.Troubleshooting für Wayfair
[cols="1,2a"]
|===
|Problem |Mögliche Ursachen

|Allgemeiner Mangel an Daten, die von Wayfair stammen oder zu Wayfair
gehen
|* link:initial_setupmd#1-autorisierung-des-wayfair-plugins-f%C3%BCr-den-zugriff-auf-wayfair-schnittstellen[Anmeldeinformationen für das Plugin] fehlen oder sind im aktiven Plugin-Set falsch.
* Probleme mit der Internetverbindung.
* Vorübergehende Ausfallzeiten bei Wayfair.

|In dem an Wayfair gesendeten Inventar fehlt ein Artikel
|
* Die Einstellung link:settings_guide.md#methode-zur-artikelzuweisung[*Methode zur Artikelzuweisung*] in den Einstellungen von Wayfair Plugin ist nicht auf den gewünschten Wert eingestellt.
* Die Einstellung link:settings_guide.md#vollst%C3%A4ndigen-bestand-an-wayfair-senden[*Vollständigen Bestand an Wayfair senden*] ist *deaktiviert* und die Artikelvariante in plentymarkets ist nicht link:initial_setupmd#5-artikel-auf-wayfair-zum-verkauf-anbieten[als für den Wayfair-Marktplatz verfügbar markiert].
* Die Artikelvariante in plentymarkets ist einem plentymarkets Lager zugeordnet, das keiner Wayfair Lieferanten ID auf der link:settings_guide.md#die-lager-seite[Lager Seite] der Wayfair Plugin Einstellungen zugeordnet ist.
* Die Artikelvariante in plentymarkets hat einen leeren oder falschen Wert in dem Feld, das der Einstellung link:settings_guide.md#methode-zur-artikelzuweisung[*Methode zur Artikelzuweisung*] der Wayfair Plugin Einstellungen ausgewählt ist.

|Ein an Wayfair gesendeter Inventarbetrag für einen Artikel liegt unter dem erwarteten Wert
|
* Keines der link:settings_guide.md#die-lager-seite[plentymarkets Lager abgestimmt auf Wayfair] hat positive Lagerbestände für die plentymarkets Artikelvariante.
* Der Wert der link:settings_guide.md#lagerpuffer[Lagerpuffer] ist größer oder gleich der Bestandsmenge für die plentymarkets Artikelvariante in link:settings_guide.md#die-lager-seite[plentymarkets Lager abgestimmt auf Wayfair].

|Es kommen keine Bestellungen von Wayfair
|
* Die Wayfair Lieferanten ID für die Wayfair-Bestellung nicht ist einem plentymarkets Lager zugeordnet auf der link:settings_guide.md#die-lager-seite[Lager Seite] der Wayfair Plugin Einstellungen.

|Bestellungen von Wayfair werden nicht ordnungsgemäß mit Artikeln in plentymarkets verknüpft
|
* Die Einstellung link:settings_guide.md#methode-zur-artikelzuweisung[*Methode zur Artikelzuweisung*] in den Einstellungen von Wayfair Plugin ist nicht auf den gewünschten Wert eingestellt.
* Die Artikelvariante in plentymarkets hat einen leeren oder falschen Wert in dem Feld, das der Einstellung link:settings_guide.md#methode-zur-artikelzuweisung[*Methode zur Artikelzuweisung*] der Wayfair Plugin Einstellungen ausgewählt ist.

|Lager zuordnungen fehlen oder sind für Bestellungen von Wayfair falsch
|
* Probleme in Lager verbänden auf der link:settings_guide.md#die-lager-seite[Lager Seite] der Wayfair Plugin Einstellungen.
* Derzeit sind einer Wayfair Lieferanten ID mehrere Lager zugeordnet auf der link:settings_guide.md#die-lager-seite[Lager Seite] der Wayfair Plugin Einstellungen.

|Die Schaltfläche zum Herunterladen von Versandetiketten wird nicht auf der Registerkarte *Übersicht* einer Bestellung im *Versand-Center* von plentymarkets angezeigt
|
* Der Versand der Bestellung wurde nicht registriert.
* Die Seite des *Versand-Center* wurde noch nicht neu geladen, nachdem die Versandregistrierung durchgeführt wurde.
* Das Herunterladen von Dokumenten ist während der Versand Registrierung fehlgeschlagen.

|Inventar Aktualisierungen werden nicht an Wayfair gesendet
|
* Das Wayfair-Plugin wurde gerade installiert oder aktualisiert. Verwende die link:settings_guide.md[Wayfair Einstellungen], um link:initial_setup.md#8-ersten-inventar-synchronisation[die erste vollständige Inventarsynchronisierung] zu starten, da Wayfair dies in den ersten 24 Stunden nicht automatisch tun darf.
* link:settings_guide.md[Wayfair Einstellungen] stimmen nicht mit dem plentymarkets Setup überein. Siehe *In dem an Wayfair gesendeten Inventar fehlt ein Artikel*.
* Konnektivitätsprobleme - siehe *Allgemeiner Mangel an Daten, die von Wayfair stammen oder zu Wayfair gehen.* oben.
|===
