= Wayfair
:author: team-plenty-channel
:keywords: Wayfair
:description: Hier erfährst du, wie du den Marktplatz Wayfair in plentymarkets einrichtest, damit du deine Artikel auf Wayfair verkaufen kannst. 
:wayfair:
:market: Wayfair
:plugin-name: Wayfair
//:main-client:
:plugin-link: https://marketplace.plentymarkets.com/wayfair_6273

Das Wayfair-Plugin ist das offizielle Plugin für die Verwendung von plentymarkets zum Verkauf von Artikeln auf dem Wayfair-Marktplatz. Das Plugin bietet mehrere Integrationen in die Schnittstellen von Wayfair, einschließlich - aber nicht beschränkt auf - die folgenden Vorgänge:

* Automatischer Abruf von Wayfair-Bestellungen mit Umstellung auf plentymarkets Bestellungen​
* Automatisches Senden von plentymarkets Inventarinformationen an Wayfair, um die Artikelverfügbarkeit genau zu halten​
* Automatische Übertragung von Wayfair-generierten Versanddokumenten an plentymarkets
* Änderungen des Bestellstatus von plentymarkets an Wayfair senden, um Wayfair-Kunden und den Wayfair-Kundensupport auf dem neuesten Stand zu halten.

== Verkauf auf Wayfair 

Wayfair ist ein geschlossener Marktplatz. Die Verwendung der Wayfair Plugin ist auf Organisationen beschränkt, die sich als Wayfair-Lieferanten registriert haben. ​Wenn Sie derzeit nicht auf Wayfair verkaufen, regisitrieren Sie sich als Partner:in, um loszulegen.

== Vorbereitung zur Verwendung des Wayfair-Plugins

Für die Verwendung des Wayfair-Plugins sind Wayfair-API-Anmeldeinformationen erforderlich, denen die entsprechenden Rechte erteilt wurden.

Verwenden Sie vor der Installation diese Anweisungen, um Wayfair zu kontaktieren und sich einzurichten.​

=== Wayfair-Plugin: API-Anmeldeinformationen abrufen

Damit das Wayfair-Plugin eine Verbindung zu Wayfair-Systemen herstellen kann, müssen Sie Ihre eindeutigen API-Anmeldeinformationen angeben.

Gehen Sie folgendermaßen vor, um die API-Anmeldeinformationen für Ihre Organisation zu erhalten:

=== 1. Senden Sie eine E-Mail an Wayfair

Bitte senden Sie eine E-Mail an Ihren Wayfair-Account Manager und kopieren Sie (CC) johara1@wayfair.com, um Unterstützung anzufordern:

* Betreff: Zugriff auf das plentymarkets Plugin / (Name Ihres Unternehmens) (Wayfair-Lieferanten-ID)
* Inhalt:
* Ihre Kontaktinformationen
* kurze Beschreibung, wie Sie das plentymarkets Plugin verwenden möchten
* Datum, an dem Sie bereit sind das Wayfair plentymarkets Plugin zu verwenden

Sie erhalten umgehend eine Antwort mit folgenden Angaben: - Bestätigung Ihres eingerichteten API-Zugriffs. - Lieferanten-ID(s) für Ihre Lager.

=== 2. Anmeldeinformationen für die Anwendung generieren

[.instruction]
Anmeldeinformationen für die Anwendung generieren:

. Gehen Sie zu https://partners.wayfair.com/developer/applications
. Geben Sie Ihre Wayfair Partner Home-Anmeldeinformationen ein. Sie sollten zur Seite *Anwendungsverwaltung* für Wayfair weitergeleitet werden.
. Klicken Sie auf der Seite *Anwendungsverwaltung* unten auf die Schaltfläche *+ Neue Anwendung*.
. Geben Sie auf dem Formular *Neue Bewerbung* die Details der neuen Bewerbung an:
* *Name*: Eine nützliche Kennung wie *[Name des Lieferanten] plentymarkets Plugin*.
* *Description*: so etwas wie *plentymarkets Plugin-Anwendung für [Name des Lieferanten] Go-Live im Herbst 2020*.
. Verwenden Sie den Schieberegler am unteren Rand des Dialogfelds, um ihn auf *Produktion* zu setzen, sofern Wayfair nichts anderes anordnet.
. Klicken Sie im Dialogfeld auf *Speichern*, um die Anmeldeinformationen der Anwendung anzuzeigen - *Kunden-ID* und *Kundengeheimnis*.
. Kopieren Sie die *Kunden-ID* und das *Kundengeheimnis*
* Das *Kundengeheimnis* kann nach diesem Zeitpunkt nicht mehr abgerufen werden und es muss ein neues generiert werden, wenn das Original verloren geht.
* Diese Anmeldeinformationen werden für die Autorisierung des Wayfair-Plugins für die Verwendung der Wayfair-Systeme verwendet.
. Schließen Sie das Dialogfeld mit den Anmeldeinformationen, um die Informationen zu schützen.

== Installieren des Wayfair-Plugins

=== Voraussetzungen

* Ein plentymarkets System
* Administratorrechte für das plentymarkets System, auf dem das Wayfair-Plugin verwendet wird
* Die Einstellung *Zugang* des plentymarkets Benutzers muss *Admin* sein
* Der plentymarkets Benutzer muss in der Lage sein, Plugin-Sets zu ändern
* Wayfair API-Anmeldeinformationen

=== 1. Autorisierung des Wayfair-Plugins für den Zugriff auf Wayfair-Schnittstellen

Nachdem das Plugin in Ihrem plentymarkets Plugin-Set installiert wurde, muss das Plugin so konfiguriert werden, dass beim Herstellen einer Verbindung zu den Wayfair-Schnittstellen die richtigen Anmeldeinformationen verwendet werden.

* *Das Autorisierungsverfahren muss für jedes Plugin-Set durchgeführt werden, das das Wayfair-Plugin enthält.*

Die Autorisierungsschritte sind wie folgt: 

1. Gehen Sie auf der Hauptseite von plentymarkets zu *Plugins » Plugin-Set-Übersicht*.
2. Suchen Sie das Plugin-Set, das mit dem Client verknüpft ist, mit dem Wayfair verwendet wird. 
3. Klicken Sie auf das gewünschte Plugin-Set.

[arabic, start=4]
. Klicken Sie in der Wayfair-Zeile des Plugin-Sets auf die Schaltfläche *Einstellungen*.
. Gehen Sie im Menü auf der linken Seite zu *Konfiguration » Globale Einstellungen*.
. Geben Sie im Bereich *Lieferanteneinstellungen* die Werte *Client ID* und *Client Secret* ein, die Ihren Wayfair API-Anmeldeinformationen entsprechen.
. Ändern Sie die Einstellung *Modus* in *Live*.
. Klicken Sie in der Symbolleiste über den Einstellungen auf die Schaltfläche *Speichern*.

=== 2. Auftragsherkunft aktivieren

[.instruction]
Auftragsherkunft aktivieren:

. Gehen Sie auf der Hauptseite von plentymarkets zu *Einrichtung » Aufträge » Auftragsherkunft*.
. Setzen Sie ein Häkchen neben dem Bestellempfänger *Wayfair*.
. Klicken Sie auf *Speichern*

==== 1. Versanddienstleister erstellen 

Um ein Versandprofil für Bestellungen zu erstellen, muss zunächst ein Versanddienstleisterobjekt eingerichtet werden, das das Versandprofil einem Spediteur zuordnet. Führen Sie die folgenden Schritte aus, um den Wayfair-Versanddienstleister zu erstellen:

[.instruction]
Versanddienstleister erstellen:

. Gehen Sie auf der Hauptseite von plentymarkets zu *Einrichtung » Aufträge » Versand » Optionen*.
. Wählen Sie die Registerkarte *Versanddienstleister*.
. Klicken Sie auf die Schaltfläche *+ Neu*
. Füllen Sie in der neu erstellten Zeile das Feld *Name* aus (der Einfachheit halber empfehlen wir *WayfairShipping* für alle Namen).
. Wählen Sie im Feld *Versanddienstleister* für die Zeile die Option *WayfairShipping* aus. Dies entspricht dem Typ, der vom Wayfair-Plugin bereitgestellt wird. *Alle anderen Felder in der Zeile können leer bleiben.*
. Stellen Sie sicher, dass die neue Zeile folgendermaßen aussieht:
. Klicken Sie auf *Speichern*

==== 2. Versandprofil erstellen

Jede Bestellung verfügt über ein Versandprofil, das für die Zusammenarbeit mit dem Versanddienstleister verwendet wird, um Artikel aus einer Bestellung zu versenden. Führen Sie diese Schritte aus, um das Wayfair-spezifische Versandprofil einzurichten.

[.instruction]
Versandprofil erstellen:

. Gehen Sie auf der Hauptseite von plentymarkets zu *Einrichtung » Aufträge » Versand » Optionen*.
. Wählen Sie die Registerkarte *Versandprofile*.
. Wenn bereits eine *Wayfair*-Zeile vorhanden ist, klicken Sie auf diese Zeile. Andernfalls klicken Sie auf die Schaltfläche *Neu*. Die Einstellungen des Versandprofils werden angezeigt.
. Wählen Sie Ihren Wayfair-Versanddienstleister aus dem bereitgestellten Menü aus (es wird wahrscheinlich *WayfairShipping* sein, wenn Sie den vorgeschlagenen Versanddienstleister.
. Füllen Sie die Felder aus, welche sich auf *Name* beziehen. (der Einfachheit halber empfehlen wir *WayfairShipping* für alle Namen).
. Stellen Sie die Sprache über das Menü rechts neben dem Feld *Name*
ein.
. Wählen Sie im Feld *Markierung* das Symbol für Wayfair-Bestellungen aus (*6* und *126* sind gute Optionen, da sie das Wayfair-Farbschema widerspiegeln).
. Ändern Sie im Feld *Priorität* optional die Priorität (wir empfehlen, sie als Standardpriorität *höchste* zu belassen).
. Stellen Sie im Feld Clients (Stores) sicher, dass Sie alle Stores auswählen, die für Wayfair eingerichtet werden können.
. Setzen Sie in der Liste *Auftragsherkunft* ein Häkchen neben alle *Wayfair* bezogenen Einträge.
. Klicken Sie oben auf der Seite auf die Schaltfläche *Speichern*.
. Beachten Sie, dass das neue (oder aktualisierte) Versandprofil aufgeführt ist.

==== 3. Optional: Versandprofil für Wayfair-Bestellungen automatisch festlegen

[.instruction]
[Optional] Versandprofil automatisch für Wayfair-Bestellungen festlegen:

. Gehen Sie auf der Hauptseite von plentymarkets zu *Einrichtung*
»*Aufträge » Ereignisse*.
. Klicken Sie auf *Ereignisaktion hinzufügen* (die Schaltfläche *+*
unten links auf der Seite), um das Dialogfeld
*Neue Ereignisaktion erstellen* zu öffnen.
. Geben Sie einen Namen ein, z.B. *Wayfair order Shipping Mapping*.
. Wählen Sie das Ereignis *Neuer Auftrag* aus dem Dropdown-Menü.
. Klicken Sie im Dialogfeld auf die Schaltfläche *Speichern* Das neue
Verfahren wird nun ausgewählt, wobei der Abschnitt *Einstellungen*
angezeigt wird.
. Aktivieren Sie im Abschnitt *Einstellungen* der Ereignisaktion das
Kontrollkästchen *Aktiv*.
. Klicken Sie auf die Schaltfläche *Filter hinzufügen* (die Schaltfläche
*+* oben im Abschnitt *Filter*), um das Dialogfeld *Filter hinzufügen*
zu öffnen.
. Wählen Sie *Auftrag* »*Herkunft*.
. Klicken Sie auf die Schaltfläche *Hinzufügen*, um den Dialog
abzuschließen. Auf dem Formular wird nun ein *Herkunft*-Filter
angezeigt.
. Aktivieren Sie in der Liste *Herkunft* das Kontrollkästchen für alle
*Wayfair* bezogenen Herkunft.
. Klicken Sie auf die Schaltfläche *Aktion hinzufügen* (die Schaltfläche
*+* oben im Abschnitt *Aktionen*), um das Dialogfeld
*Aktion hinzufügen* zu öffnen.
. Wählen Sie *Auftrag » Versandprofil ändern*.
. Klicken Sie auf die Schaltfläche *Hinzufügen*, um den Dialog
abzuschließen. Im Bereich *Aktionen* wird eine Aktion
*Versandprofil ändern* angezeigt.
. Klicken Sie auf das Symbol Karat ganz links in der Zeile
*Versandprofil ändern* *- dies ist NICHT die große quadratische
Schaltfläche, auf der sich auch ein Hochzeichen befindet -* um die
Details der Prozedur zu erweitern.
. Wählen Sie im Dropdown-Menü der Aktion das für *Wayfair* erstellte
Versandprofil
. Klicken Sie oben auf der Seite auf die Schaltfläche *Speichern*

==== 4. Verknüpfen Sie Wayfair-Bestellartikel mit plentymarkets Artikeln:

Um eingehende Bestellungen von Wayfair ordnungsgemäß verarbeiten zu
können, muss das Wayfair-Plugin die Lieferanten-Teilenummern aus
Wayfairs Systemen mit einem bestimmten Feld von Artikel varianten in
plentymarkets abgleichen. Standardmäßig geht das Wayfair-Plugin davon
aus, dass die *Variantennummer* *(nicht die ID der Varianten)* der
Varianten eines Artikels in plentymarkets mit der Teilenummer des
Wayfair-Lieferanten übereinstimmt.

Wenn die Lieferanten-Teilenummern für Ihre Organisation in einem
alternativen Feld in Ihren plentymarkets ArtikelVarianten angezeigt
werden, ändern Sie den Wert von *Methode zur Artikelzuweisung*

==== 5. Artikel auf Wayfair zum Verkauf anbieten

Artikel, die Sie auf Wayfair verkaufen möchten, müssen in plentymarkets
als aktiv markiert werden. Der Benutzer von plentymarkets kann auch
festlegen, welche Artikel auf Wayfair zum Verkauf stehen. *Beachten Sie,
dass der Lagerbestand und die bestellten Artikel auf der Ebene der
Varianten gesteuert werden.*

==== 6. Konfigurieren von plentymarkets zum Senden von Versandsbestätigungen (ASN) an Wayfair

===== 6.1 Einstellen des Wayfair-Plugins, um die richtigen Versandinformationen an Wayfair zu senden

Lieferanten, die Bestellungen über ihre eigenen Konten versenden möchten (statt die Versanddienste von Wayfair zu nutzen), müssen die Konfigurationseinstellungen für Versandbestätigung (ASN)

Wenn die Versanddienste von Wayfair verwendet werden sollen, sollten die ASN-Einstellungen des Wayfair-Plugins in ihren Standardeinstellungen (*Wayfair-Versand*) belassen werden.

===== Ereigniss für plentymarkets Bestellungen erstellen, das Versandinformationen an Wayfair sendet

[.instruction]
Ereigniss für plentymarkets Bestellungen erstellen, das Versandinformationen an Wayfair sendet:

. Gehen Sie auf der Hauptseite von plentymarkets zu *Einrichtung » Aufträge » Ereignisse*.
. Klicken Sie auf *Ereignisaktion hinzufügen* (die Schaltfläche *+*
links am Seitenende).
. Geben Sie einen beliebigen *Name* ein
. Wählen Sie im Feld *Ereignis* die Option *Statuswechsel* (in der
Kategorie *Auftragsänderung*).
. Wählen Sie im Feld unter *Ereignis* die Statusänderung aus, die das
Senden einer ASN an Wayfair auslösen soll, Z.b.
*In Versandvorbereitung*.
. Klicken Sie auf die Schaltfläche *Speichern*
. Sie sollten automatisch zur neu erstellten Ereignisaktion umgeleitet
werden. Setzen Sie im Abschnitt *Einstellungen* der Ereignisprozedur ein
Häkchen neben *Aktiv*.
. Klicken Sie auf *Filter hinzufügen* und gehen Sie zu *Auftrag* »
*Herkunft*, um die Herkunft als Filter hinzuzufügen.
. Klicken Sie auf *+ Hinzufügen*.
. Im Abschnitt *Filter* sollte ein Feld mit einer Liste aller
verfügbaren Auftragsverweise angezeigt werden. Setzen Sie ein Häkchen
neben alle *Wayfair* -Auftragsempfänger:
. Klicken Sie auf das *+* neben *Aktionen*:
. Wählen Sie *Versandbestätigungen (ASN) an Wayfair senden* in der
Kategorie *Plugins*:
. Klicken Sie auf die Schaltfläche *Hinzufügen*
. Klicken Sie auf die Schaltfläche *Speichern*

==== 7. Erster Warenbestandabgleich

Sobald alles eingerichtet ist, ist es an der Zeit, dass das
Wayfair-Plugin Artikel auf Wayfair zum Verkauf anbietet.

* Navigieren Sie zur Inventarseite in den Wayfair-Markteinstellungen
* Warten Sie eine Minute, während das System die Inventarinformationen
aktualisiert.
* Überprüfen Sie die auf der Seite angezeigten Informationen.
* Wenn Probleme für die vollständige Inventarsynchronisierung gemeldet
werden, versuchen Sie, diese zu beheben, indem Sie die Anweisungen für
die Inventarseite lesen, die plentymarkets Protokolle anzeigen und den
Leitfaden zur Fehlerbehebung verwenden.

== Anpassung und Überwachung

Das Wayfair-Plugin bietet Nutzern von plentymarkets die Möglichkeit,
sein Verhalten anzupassen und zu überwachen.

=== Die Home Seite

Die Home Seite wird durch Klicken auf *Startseite* im Menü auf der
linken Seite oder durch Klicken auf *Wayfair* in der
Wayfair-Navigationsleiste aktiviert. Derzeit werden keine Informationen
bereitgestellt.

=== Die Lager Seite

Die Lager Seite wird verwendet, um die Lager, die der Lieferant in
plentymarkets verwendet, mit den Wayfair Lieferanten IDs zu verknüpfen,
die dem Lieferanten ausgestellt wurden. Die Zuordnungen werden vom
Wayfair-Plugin verwendet, wenn es Inventar an Wayfair meldet und
Wayfair-Bestellungen verarbeitet, die bei plentymarkets eingehen.

==== Hinweise zu mehreren Lagern pro Wayfair-Lieferanten-ID

Die Seite Lager wird verwendet, um die LAger, die der Lieferant in
plentymarkets nutzt, den Wayfair-Lieferanten-IDs zuzuordnen, die dem
Lieferanten zugewiesen wurden. Die Zuordnungen werden vom Wayfair-Plugin
verwendet, wenn es den Bestand an Wayfair meldet und auch bei der
Verarbeitung von Wayfair-Bestellungen, die bei plentymarkets eingehen.

Wenn Sie eine Beziehung zwischen Lagerorten und Lieferanten-IDs
auswählen, die nicht eins zu eins ist, überprüfen Sie das Verhalten der
Einstellung Lagerpuffer. Wenn einer Wayfair-Lieferanten-ID mehr als ein
Lager zugewiesen wurde, wird die Artikel-Lager-Zuordnung basierend auf
dem Lagerbestand und dem Land des Lagers priorisiert.

==== Lager-Zuordnung hinzufügen

[.instruction]
Lager-Zuordnung hinzufügen:

. Klicken Sie auf die Schaltfläche *Zuordnung hinzufügen*
. Verwenden Sie die linke Spalte, um ein plentymarkets Lager nach Namen
auszuwählen.
* Wenn dem plentymarkets System kürzlich ein Warehouse hinzugefügt
wurde, kann es bis zu fünf Minuten dauern, bis es auf dieser Seite
verfügbar ist.
* Versuchen Sie nicht, dasselbe plentymarkets Warehouse für mehr als
eine Zeile auf dieser Seite zu verwenden, da dies eine nicht
unterstützte Konfiguration ist.
. Geben Sie in der rechten Spalte eine numerische Lieferanten-ID ein.
. Klicken Sie auf die Schaltfläche *Speichern*, sobald die neuen Zeilen
abgeschlossen sind.

==== Lager-Zuordnung entfernen

[.instruction]
Lager-Zuordnung entfernen:

. Suchen Sie die zu entfernende Zeile
. Klicken Sie in der Zeile auf die Schaltfläche *Löschen*
. Klicken Sie auf die Schaltfläche *Speichern*, sobald die gewünschten
Zeilen entfernt wurden

=== Die Einstellungen-Seite

Diese Seite enthält allgemeine Einstellungen für den Betrieb des Wayfair-Plugins. Einstellungen werden bei Änderungen nicht automatisch gespeichert. Verwenden Sie die Schaltfläche *Speichern* unten auf der Seite.

==== Lagerpuffer

Die Einstellung *Lagerpuffer* ist eine nicht negative Ganzzahl, die für
jede Artikelvariante für jede Wayfair Lieferanten ID eine reservierte
Lagermenge festlegt. Der Pufferbetrag wird abgezogen, nachdem alle
anderen Bestandsberechnungen durchgeführt wurden, einschließlich der
Aggregation der Bestände für mehrere plentymarkets Lager, denen dieselbe
Wayfair Lieferanten ID zugewiesen wurde.

Um den *Lagerpuffer* zu deaktivieren, lassen Sie diese Einstellung leer
oder setzen Sie sie auf *0*.

=== Standard-Bestellstatus

Die Einstellung *Standard-Bestellstatus* bestimmt, in welchem ​​Status
sich eine neue plentymarkets Bestellung nach der Erstellung durch das
Wayfair-Plugin befinden soll.

*Hinweis:* Die Auftragserstellung gilt nicht als Änderung des
Auftragsstatus. Wenn Sie den Standardbestellstatus auf einen höheren als
die Statuswerte für konfigurierten plentymarkets Ereignisse setzen,
können einige Ereignisse fehlschlagen.

=== Standardversandanbieter *(nicht genutzt)*

Die Einstellung *Standardversandanbieter* ist eine Legacy-Einstellung,
die das Verhalten des Plugins nicht mehr beeinflusst. *Wenn diese
Einstellung in Ihrem System angezeigt wird, empfiehlt Wayfair dringend,
dass Sie Ihr Plugin auf eine neuere Version aktualisieren.*

=== Methode zur Artikelzuweisung

Die Einstellung *Methode zur Artikelzuweisung* bestimmt das Verhalten
beim Abgleichen der Artikelvarianten von plentymarkets mit den
Wayfair-Produkten. Es wird verwendet, wenn die Bestandslisten an Wayfair
gesendet werden und um die angeforderten Produkte in einer
Wayfair-Bestellung auszuwählen. Der Benutzer von plentymarkets sollte
diese Einstellung so konfigurieren, dass sie der Art und Weise
entspricht, in der die Elementvarianten ausgefüllt werden.

==== Verwenden der Variantennummer als Elementzuordnungsfeld

Standardmäßig wird das Feld *Variantennummer* für die Zuordnung der
Artikel von Wayfair-Bestellungen zu Artikelvarianten von plentymarkets
verwendet. Die anderen Optionen sind *EAN* (Barcode) und *SKU*.

==== Verwenden von EAN (Barcode) als Elementzuordnungsmethode

Wenn die *Methode zur Artikelzuweisung* auf *EAN* eingestellt ist,
sollte jede Artikelvariante in plentymarkets so eingerichtet werden,
dass sie einen Barcode enthält, der die Wayfair-Lieferanten-Teilenummer
widerspiegelt, die Wayfair in eingehenden Bestelldaten sendet.

==== Verwenden der SKU als Elementzuordnungsmethode

Wenn die *Artikelzuordnungsmethode* auf *SKU* eingestellt ist,
sollte jede Artikelvariante in plentymarkets so eingerichtet werden,
dass sie eine Wayfair-spezifische SKU enthält, die die
Wayfair-Lieferanten-Teilenummer widerspiegelt, die Wayfair in
eingehenden Bestelldaten sendet.

=== Aufträge importieren ab

Die optionale Einstellung *Aufträge importieren ab* bestimmt ein Datum,
ab dem neue Wayfair-Bestellungen als für den Import in das plentymarkets
System berechtigt gelten. Diese Einstellung kann die Leistung
verbessern, indem verhindert wird, dass das Wayfair-Plugin Bestellungen
anfordert, die vor dem angegebenen Datum erstellt wurden. Es kann auch
verwendet werden, um zu verhindern, dass das plentymarkets System
Bestellungen vor einem gewünschten *Go-Live-Datum* annimmt.

=== Die Seite Inventar

Die Seite *Inventar* enthält keine zu konfigurierenden Einstellungen. Es
wird verwendet, um den Status der Synchronisierung des plentymarkets
Inventars mit Wayfair zu überprüfen. Die Daten der Seite werden
regelmäßig aktualisiert, wie durch den Zeitstempel unten angegeben.

=== Hauptstatusanzeige

Oben auf der Seite *Inventar* werden immer ein Symbol und eine Meldung
angezeigt, um den allgemeinen Zustand des
Inventarsynchronisierungsprozesses zu beschreiben.

* Ein Kalendersymbol wird angezeigt, wenn das Wayfair-Plugin noch keine
Inventarsynchronisierung versucht hat.
* Dies geschieht direkt nach der Installation des Plugins.
* Dies kann passieren, wenn das Plugin kürzlich aktualisiert wurde.
* Die Seite ändert sich innerhalb von 15 bis 30 Minuten, sobald das
Synchronisationssystem initialisiert wird.
* Ein Symbol mit einem Häkchen wird angezeigt, wenn das Wayfair Plugin
das Inventar regelmäßig synchronisiert, ohne dass Probleme festgestellt
werden.
* Ein Symbol mit einer durchgestrichenen Wolke wird angezeigt, wenn das
Wayfair-Plugin Unregelmäßigkeiten bei der Inventarsynchronisierung
feststellt.
* Fehler werden erwartet, wenn das Wayfair-Plugin kürzlich installiert
wurde und die Ersteinrichtungnoch nicht abgeschlossen wurde. Beenden Sie
die Einrichtung des Plugins, bevor Sie die Seite *Inventar* erneut
verwenden.
* Details werden möglicherweise weiter unten auf der Seite angezeigt,
um zu erklären, was falsch ist.
* Konsultieren Sie die plentymarkets Logs, um Fehlerdetails zu
erhalten.
* Im Handbuch zur Fehlerbehebung des Wayfair-Plugins finden Sie Ideen
zur Lösung von Problemen bei der Inventarsynchronisierung.

=== Details zur Inventarsynchronisierung

Wenn dies möglich ist, enthält die Seite *Inventar* Details zur
Unterstützung des Hauptstatus, der oben auf der Seite angezeigt wird.

* Ein Kalendersymbol zeigt an, dass eine Information noch nicht
verfügbar ist.
* Ein Symbol mit einem Häkchenzeigt ein positives Ereignis an.
* Ein Symbol mit einer durchgestrichenen Wolke zeigt ein negatives
Ereignis an.
* Ein Symbol mit einem Pfeil nach oben zu einer Wolke !zeigt an, dass
ein Ereignis gerade stattfindet und wird beschrieben, sobald es
abgeschlossen ist.

=== Die Seite Versandsbestätigung (ASN)

Die Seite *Versandsbestätigung (ASN)* wird zum Konfigurieren der
Versandinteraktionen zwischen plentymarkets, dem Wayfair Plugin und
Wayfair verwendet. Die hier bereitgestellten Informationen legen das
Verhalten für den *Versandsbestätigung (ASN) an Wayfair senden*-Prozess
für Bestellungen fest.

=== Versandart

Das Optionsfeld oben auf der Seite enthält diese Optionen. Wayfair gibt
Lieferanten Anweisungen zur Auswahl des richtigen Werts.

* *Wayfair Versand*
* Die Sendungen Ihrer Bestellungen werden von Wayfair arrangiert und
von einem von Wayfair ausgewählten Spediteur versendet.
* Das plentymarkets System muss Wayfair mitteilen, wann die Bestellung
versandbereit ist.
* Das plentymarkets System muss Tracking-Informationen von Wayfair in
Ihre plentymarkets Bestellungen zurückerhalten.
* *Selbst Versenden*
* Sie versenden Ihre eigenen Bestellungen über Ihre eigenen Spediteure.
* Das plentymarkets System muss Wayfair mitteilen, wenn Sie eine
Bestellung versenden.
* Das plentymarkets System muss Wayfair die Tracking-Informationen
mitteilen (Spediteur und Tracking-Nummer).

=== plentymarkets Speditionen zu Wayfair-Speditionen zuordnen

Wenn Sie die Option *Selbst Versende* auswählen, muss Wayfair die
Versandinformationen von plentymarkets in Daten übersetzen, die es
versteht.

[.instruction]
plentymarkets Speditionen zu Wayfair-Speditionen zuordnen:

. Suchen Sie die von Wayfair bereitgestellten Spediteurinformationen.
Wenden Sie sich bei Bedarf an johara1@wayfair.com.
. Geben Sie für jeden in der linken Spalte aufgeführten plentymarkets
*Versanddienstleister* den von Wayfair bereitgestellten *SCAC Code* in
die rechte Spalte *Wayfair-Kennziffer des Versanddienstleisters* ein.
. Klicken Sie unten auf der Seite auf *Speichern*

=== Troubleshooting: Häufige Probleme

Bevor Sie sich an Wayfair wenden, verwenden Sie bitte die folgende
Tabelle, um Probleme im Wayfair-Plugin selbst zu diagnostizieren.

[[troubleshooting-wayfair]]
.Troubleshooting für Wayfair
[cols="1,2a"]
|===
|Problem |Mögliche Ursachen

|Allgemeiner Mangel an Daten, die von Wayfair stammen oder zu Wayfair
gehen
|* link:initial_setupmd#1-autorisierung-des-wayfair-plugins-f%C3%BCr-den-zugriff-auf-wayfair-schnittstellen[Anmeldeinformationen für das Plugin] fehlen oder sind im aktiven Plugin-Set falsch.
* Probleme mit der Internetverbindung.
* Vorübergehende Ausfallzeiten bei Wayfair.

|In dem an Wayfair gesendeten Inventar fehlt ein Artikel
|
* Die Einstellung link:settings_guide.md#methode-zur-artikelzuweisung[*Methode zur Artikelzuweisung*] in den Einstellungen von Wayfair Plugin ist nicht auf den gewünschten Wert eingestellt.
* Die Einstellung link:settings_guide.md#vollst%C3%A4ndigen-bestand-an-wayfair-senden[*Vollständigen Bestand an Wayfair senden*] ist *deaktiviert* und die Artikelvariante in plentymarkets ist nicht link:initial_setupmd#5-artikel-auf-wayfair-zum-verkauf-anbieten[als für den Wayfair-Marktplatz verfügbar markiert].
* Die Artikelvariante in plentymarkets ist einem plentymarkets Lager zugeordnet, das keiner Wayfair Lieferanten ID auf der link:settings_guide.md#die-lager-seite[Lager Seite] der Wayfair Plugin Einstellungen zugeordnet ist.
* Die Artikelvariante in plentymarkets hat einen leeren oder falschen Wert in dem Feld, das der Einstellung link:settings_guide.md#methode-zur-artikelzuweisung[*Methode zur Artikelzuweisung*] der Wayfair Plugin Einstellungen ausgewählt ist.

|Ein an Wayfair gesendeter Inventarbetrag für einen Artikel liegt unter dem erwarteten Wert
|
* Keines der link:settings_guide.md#die-lager-seite[plentymarkets Lager abgestimmt auf Wayfair] hat positive Lagerbestände für die plentymarkets Artikelvariante.
* Der Wert der link:settings_guide.md#lagerpuffer[Lagerpuffer] ist größer oder gleich der Bestandsmenge für die plentymarkets Artikelvariante in link:settings_guide.md#die-lager-seite[plentymarkets Lager abgestimmt auf Wayfair].

|Es kommen keine Bestellungen von Wayfair
|
* Die Wayfair Lieferanten ID für die Wayfair-Bestellung nicht ist einem plentymarkets Lager zugeordnet auf der link:settings_guide.md#die-lager-seite[Lager Seite] der Wayfair Plugin Einstellungen.

|Bestellungen von Wayfair werden nicht ordnungsgemäß mit Artikeln in plentymarkets verknüpft
|
* Die Einstellung link:settings_guide.md#methode-zur-artikelzuweisung[*Methode zur Artikelzuweisung*] in den Einstellungen von Wayfair Plugin ist nicht auf den gewünschten Wert eingestellt.
* Die Artikelvariante in plentymarkets hat einen leeren oder falschen Wert in dem Feld, das der Einstellung link:settings_guide.md#methode-zur-artikelzuweisung[*Methode zur Artikelzuweisung*] der Wayfair Plugin Einstellungen ausgewählt ist.

|Lager zuordnungen fehlen oder sind für Bestellungen von Wayfair falsch
|
* Probleme in Lager verbänden auf der link:settings_guide.md#die-lager-seite[Lager Seite] der Wayfair Plugin Einstellungen.
* Derzeit sind einer Wayfair Lieferanten ID mehrere Lager zugeordnet auf der link:settings_guide.md#die-lager-seite[Lager Seite] der Wayfair Plugin Einstellungen.

|Die Schaltfläche zum Herunterladen von Versandetiketten wird nicht auf der Registerkarte *Übersicht* einer Bestellung im *Versand-Center* von plentymarkets angezeigt
|
* Der Versand der Bestellung wurde nicht registriert.
* Die Seite des *Versand-Center* wurde noch nicht neu geladen, nachdem die Versandregistrierung durchgeführt wurde.
* Das Herunterladen von Dokumenten ist während der Versand Registrierung fehlgeschlagen.

|Inventar Aktualisierungen werden nicht an Wayfair gesendet
|
* Das Wayfair-Plugin wurde gerade installiert oder aktualisiert. Verwenden Sie die link:settings_guide.md[Wayfair Einstellungen], um link:initial_setup.md#8-ersten-inventar-synchronisation[die erste vollständige Inventarsynchronisierung] zu starten, da Wayfair dies in den ersten 24 nicht automatisch tun darf.
* link:settings_guide.md[Wayfair Einstellungen] stimmen nicht mit dem plentymarkets Setup überein. Überprüfen Sie "In dem an Wayfair gesendeten Inventar fehlt ein Artikel.
* Konnektivitätsprobleme - siehe *Allgemeiner Mangel an Daten, die von Wayfair stammen oder zu Wayfair gehen.* oben.
|===
