= Zalando
:author: team-plenty-channel
:keywords: Zalando, Zalando, zalando.de, zalando.de, salando, zalando.com
:description: Auf dieser Seite erfährst du, wie du Zalando in plentymarkets einrichtest, damit du deine Artikel auf Zalando verkaufen kannst.
:page-index: false

:ea-queue:
:market: Zalando
:zalando:
:catalogue:

Durch das Zalando-Partnerprogramm können Online-Händler:innen und Hersteller:innen Zalando als zusätzlichen Absatzkanal für hochwertige Produkte nutzen und von der großen Markenbekanntheit von Zalando profitieren.

//tag::zalando-countries[]
In welchen Ländern du über Zalando verkaufen kannst, hängt von deinem Vertrag mit Zalando ab. Zurzeit können Aufträge aus den folgenden Ländern in plentymarkets importiert werden:

*_Wichtig:_* Mit plentymarkets ist nur Eigenversand durch Händler:innen möglich. Zalando nennt das *Partner Fulfillment (own logistics)*. Der Versand durch Zalando, also Zalando Fulfillment Solutions (ZFS), wird noch nicht unterstützt.

* Deutschland
* Belgien
* Estland
* Finnland
* Frankreich
* Irland
* Lettland
* Litauen
* Niederlande
* Österreich
* Portugal
* Slowakei
* Slowenien
//end::zalando-countries[]

[#200]
== Häufigkeit des Datenaustauschs

Die Anbindung des Marktplatzes stellt die folgenden automatisierten Funktionen bereit:

[[data-exchange]]
[cols="1,2"]
|===
|Daten |Intervall

| Artikelexport
| Einmal täglich +
plentymarkets generiert die Artikeldaten einmal täglich nachts als XML-Datei. Diese Datei heißt *artikel.xml*. Zalando ruft diese XML normalerweise einmal pro Tag ab.

| Bestandsabgleich
| Alle 15 Minuten, asynchron +
Normalerweise werden pro Minute 1.000 Bestände aktualisiert. Wenn die von Zalando vorgegebene API-Limitierung erreicht wird, werden die übrigen Bestände gesendet, sobald die API nach spätestens einer Minute wieder entsperrt ist.

| Preisabgleich
| Alle 15 Minuten

| Auftragsimport
| Alle 5 Minuten
|===

[#100]
== Bei Zalando registrieren

Du möchtest am Partnerprogramm von Zalando teilnehmen? Dann link:https://www.zalando.de/partner-programm/[wende dich direkt an Zalando^].

[#150]
== Übersicht der notwendigen Schritte

Wie du vorgehst hängt davon ab, ob du Zalando zum ersten Mal in plentymarkets einrichtest oder schon auf Zalando verkaufst und eine weitere Zalando-Plattform nutzen möchtest.

[tabs]
====
Schritte nach der Registrierung::
+
--
Du hast einen Vertrag mit Zalando abgeschlossen. Super. Wie geht es jetzt weiter?

Hier siehst du eine Übersicht der Schritte, die dich erwarten.

. <<#api-user, Erstelle einen REST-API-Zugang>>.
. <<#setup, Nimm die Grundeinstellungen im Menü *Einrichtung » Märkte » Zalando » Einstellungen* vor.>>
. <<#zalando-csv-form, Fordere im plentymarkets Forum das CSV-Formular zum Abgleichen von Artikeln/Silhouetten an.>>
  ** Trage deine Benutzerdaten in die CSV-Datei ein.
  ** Leite das ausgefüllte Formular an deine:n Zalando-Ansprechpartner:in weiter.
. <<#1400, Durchlaufe den Assistenten *Kontoeinstellungen - Zalando* zum ersten Mal.>> +
*_Wichtig:_* Beim ersten Durchlauf kannst du nicht alle Einstellungen des Assistenten vornehmen.
. <<#link-zDirect, Bitte unseren Support, dein Konto mit deinem zDirect-Konto zu verknüpfen.>> +
*_Wichtig:_* Das geht erst, nachdem du den Assistenten zum ersten Mal durchlaufen hast.
. <<#assistant-2, Durchlaufe den Assistenten *Kontoeinstellungen - Zalando* noch einmal, um die fehlenden Einstellungen vorzunehmen.>>
. <<#more-setup, Nimm die weitere Einrichtung vor.>>
. <<#order-documents, Bereite die Auftragsdokumente vor.>>
. <<#prepare-variations, Bereite deine Varianten vor.>>
. <<#1200-1, Automatisiere die Auftragsabwicklung.>>
. <<#1500, Aktiviere dein Zalando-Konto im Assistenten, um den Datenaustausch mit Zalando zu starten.>>
--
 
Schritte, um weiteren Verkaufskanal hinzuzufügen::
+
--
Du verkaufst schon auf Zalando, möchtest deine Produkte jetzt aber auf einer weiteren Länderplattform anbieten? Kein Problem.

Sobald du mit Zalando einen Vertrag über den zusätzlichen Verkaufskanal abgeschlossen hast, geht es so weiter:

. Du forderst im Forum link:https://forum.plentymarkets.com/t/sammelthema-collective-thread-csv-formular-zum-abgleichen-von-artikeln-silhouetten-csv-form-for-synchronization-of-articles-silhouettes/669460[die API-Route für den neuen Verkaufskanal an]. +
*_Wichtig:_* Benutzer und Kennwort sind für alle Zalando-Verkaufskanäle gleich. Zalando benötigt also nur die API-Route.
. Du sendest deiner Zalando-Ansprechpartner:in die neue API-Route mit der Zusatzinformation, dass alle anderen Daten vom ersten Verkaufskanal übernommen werden sollen. +
→ Zalando schaltet den neuen Verkaufskanal frei.
. Aktiviere die Auftragsherkunft für das neue Land im Menü *Einrichtung » Aufträge » Auftragsherkunft*.
. Erstelle einen neuen Verkaufspreis. Vergiss nicht, die *Währung* und das *Land* korrekt zu speichern. Oder aktiviere die Herkunft *Zalando* in einem vorhandenen Verkaufspreis für das Land. +
*_Wichtig:_* Aktiviere die Herkunft *Zalando*. Die Unterherkünfte für die einzelnen Zalando-Plattformen (Zalando DE, Zalando NL usw.) werden ignoriert.
. Bereite die Auftragsdokumente für das Land vor.
. Aktiviere den Verkaufspreis an den Varianten. +
*_Wichtig:_* An den Varianten wird die Verfügbarkeit für die einzelnen Zalando-Plattformen (Zalando DE, Zalando NL usw.) ignoriert. Deshalb änderst du die Einstellungen für die Verfügbarkeit nicht.
. <<#assistant-2, Durchlaufe den Assistenten, um das Land zu aktivieren und die Einstellungen für Preise und Bestände zu speichern.>>
--
====


[#setup]
== Konto- und Ländereinstellungen vornehmen

Nachdem Zalando dich als Partner:in in das Programm aufgenommen hat, stellt dir Zalando ein Handbuch und Hilfestellung beim Einrichten der Schnittstelle zur Verfügung. In plentymarkets nimmst du die hier beschriebenen Einstellungen vor.

[#api-user]
=== REST-API-Zugang erstellen

Erstelle nun einen REST-API-Zugang.

[.instruction]
REST-API-Zugang erstellen:

. Öffne das Menü *Einrichtung » Einstellungen » Benutzer » Konten*.
. Klicke auf *Neu*. +
→ Das Fenster *Neuen Benutzer anlegen* wird geöffnet.
. Gib einen *Benutzernamen* ein.
. Gib in das Feld *realen Namen* ein.
. Gib ein *Passwort* ein.
. Wiederhole das Passwort.
. Wähle für die Einstellung *Zugang* die Option *REST-API*.
. *Speichere* die Einstellungen. +
→ Das Konto wird erstellt. +
*_Tipp:_* Für das Konto müssen keine Rechte freigegeben werden. Es reicht, dass das Konto im System existiert.

[#base-settings]
=== Grundeinstellungen vornehmen

[.instruction]
Grundeinstellungen vornehmen:

. Öffne das Menü *Einrichtung » Märkte » Zalando » Einstellungen*. +
→ Das Tab *Einstellungen* wird geöffnet.
. Nimm die Einstellungen gemäß <<#UABFSCS3>> vor.
. Speichere (terra:save[]) die Einstellungen.

[[UABFSCS3]]
.Grundeinstellungen des Marktplatzes Zalando
[cols="1,3a"]
|===
|Einstellung |Erläuterung

2+^|Grundkonfiguration

| *Benutzer*
| Das API-Konto wählen, das du <<#api-user, für Zalando erstellt hast>>.

| *Artikelname*
| *Name 1*, *Name 2* oder *Name 3* wählen. Der gewählte Name wird zu Zalando exportiert.

2+^|Erweiterte Optionen

| *Regelsteuersatz*
| *19 %* oder *7 %* wählen.

| *Ermäßigter Steuersatz*
| *19 %* oder *7 %* wählen.
|===

[#zalando-csv-form]
=== CSV-Formular zum Abgleichen von Artikeln/Silhouetten anfordern

Fordere nun im plentymarkets Forum die FTP-Zugangsdaten und API-Daten an. Diese Daten benötigt Zalando, um einen Verkaufskanal für dich einzurichten.

. Melde dich im Foren-Thread link:https://forum.plentymarkets.com/t/sammelthread-anfrage-des-csv-formulars-zum-abgleich-der-artikel-silhouetten/669460[CSV-Formular zum Abgleichen von Artikeln/Silhouetten anfordern^]. +
→ Du erhältst von unserem Support-Team ein Formular im CSV-Format. Dieses Formular enthält die folgenden Informationen:
  * Routen für Artikel
  * Zugangsdaten zum plentymarkets FTP-Server für Silhouetten +
  *_Tipp:_* Auf diesen FTP-Server sendet Zalando deine Silhouetten, damit sie in dein System importiert werden können. plentymarkets importiert die Silhouetten jeden Mittwoch.
. Trage in Zeile 5 der Datei den Benutzernamen ein, den du im Menü *Einrichtung » Märkte » Zalando » Einstellungen* gewählt hast.
. Trage in Zeile 6 der Datei das Kennwort ein, das du im Menü *Einrichtung » Märkte » Zalando » Einstellungen* gewählt hast.
. Leite das ausgefüllte Formular an deine Kontaktperson bei Zalando weiter. +
→ Zalando schaltet den Verkaufskanal für dich frei.

[#1400]
=== Assistent Teil 1: Kontoeinstellungen

Im Assistenten *Kontoeinstellungen - Zalando* speicherst du nun Angaben zu deinem Zalando-Konto

*_Wichtig:_* Du musst den Assistenten zweimal durchlaufen. Hier wird nur Teil 1 beschrieben.

:menu-path: pass:quotes[*Einrichtung » Assistenten » Omni-Channel*]
:assistant-name: Kontoeinstellungen - Zalando
:number-of-boxes: Info-Boxen

include::partial$assistant-basic-instructions.adoc[]

[.collapseBox]
.Schritt *Aufträge*
--

[[table-assistant-zalando-orders]]
[cols="1,3a"]
|===
|Einstellung |Erläuterung

| *Möchtest du Zalando-Aufträge in plentymarkets importieren?*
| Aktivieren, um Aufträge automatisch alle fünf Minuten zu importieren. +
*_Hinweis:_* Artikeldaten und Bestandsinformationen können nur zu Zalando übertragen werden, wenn diese Option aktiviert ist.

| *Aus welchen Ländern sollen Aufträge importiert werden?*
| _Wenn du den Assistenten zum ersten Mal durchläufst, kannst du noch keine Länder wählen._

| *Wähle eine Umgebung für den Auftragsimport.*
a| Wählen, ob echte Daten oder Testdaten importiert werden sollen.

* *Sandbox* = Von Zalando werden Testdaten importiert.
* *Productive* = Von Zalando werden echte Auftragsdaten importiert.

| *Unter welchem Mandanten möchtest du deine Artikel verkaufen?*
|Mandant (Shop) wählen. Zalando-Aufträge werden diesem Mandanten zugeordnet.

| *Sollen auch Reservierungen importiert werden?*
|Artikel gelten als reserviert, wenn Kund:innen eine Bestellung aufgegeben haben, die Ware aber entweder noch nicht bezahlt haben oder der Auftrag noch nicht von Zalando für den Versand freigegeben wurde. +
Wenn diese Option aktiviert wird, werden Reservierungen mit Status *[3] Warten auf Zahlung* in plentymarkets importiert. +
Wenn die Zahlung des Auftrags von Zalando bestätigt und der Auftrag auf Zalando in den Status *approved* verschoben wird, wird der Auftrag in plentymarkets in Status *[5] Freigabe Versand* verschoben. Sobald ein Auftrag in Status *[5]* ist, kann er versendet werden. +
*_Hinweis:_* Aufträge können erst in Status *[5] Freigabe Versand* versandt werden. Ein Auftrag, der noch in Status *[3] Warten auf Zahlung* ist, darf nicht versandt werden.

|*Welcher Auftragsstatus soll Reservierungen zugewiesen werden?*
|Reservierungen werden standardmäßig mit Status *[3] Warten auf Zahlung* importiert und müssen nach der Stornierung durch Kund:innen oder durch Zalando in einen anderen Status *[8.X]* verschoben werden. In diesem Schritt entscheidest du, in welchen Status stornierte Reservierungen verschoben werden sollen. +
*_Hinweis:_* Wähle einen Status, bei dem durch den Statuswechsel keine Ereignisaktion an Zalando ausgelöst wird. Aufträge, die vor dem Import der Reservierung von Käufer:innen storniert werden, werden nicht importiert.

| *plentymarkets Retourengrund verknüpfen mit*
a|Für jeden in plentymarkets gespeicherten Retourengrund einen Retourengrund von Zalando aus der Dropdown-Liste wählen. Die Retourengründe werden nur für den Auftragstyp *Retoure* übertragen und müssen an den Artikelpositionen der Retouren  gepflegt werden.

Zalando hat zurzeit die folgenden Retourengründe:

* *Unbekannter Grund*
* *Gefällt nicht*
* *Zu groß*
* *Zu klein*
* *Schlechtes Preis-Leistungs-Verhältnis*
* *Lieferung zu spät*
* *Artikel nicht wie erwartet*
* *Falscher Artikel gesendet*
* *Defekt*

*_Hinweis:_* Das Übermitteln von Retourengründen an Zalando ist optional, wird aber von Zalando empfohlen.
|===
--

[.collapseBox]
.Schritt *Bestände*
--

_Wenn du den Assistenten zum ersten Mal durchläufst, kannst du in diesem Schritt noch keine Einstellungen vornehmen._
--

[.collapseBox]
.Schritt *Preise*
--
_Wenn du den Assistenten zum ersten Mal durchläufst, kannst du in diesem Schritt noch keine Einstellungen vornehmen._
--

[.collapseBox]
.Schritt *Konto-Aktivierung*
--

_Wenn du den Assistenten zum ersten Mal durchläufst, kannst du in diesem Schritt noch keine Einstellungen vornehmen._
--

[#link-zDirect]
=== Konto mit zDirect-Konto verknüpfen lassen

Du hast den Assistenten zum ersten Mal durchlaufen und abgeschlossen. Lass nun dein Zalando-Konto freischalten: +
link:https://forum.plentymarkets.com/t/sammelthema-aktivierung-neuer-zalando-konten/600409[Melde dich in diesem Forum-Thread. Bitte unseren Support, dein Konto freizuschalten.]

Gib in deinem Foren-Post die folgenden Informationen an:

* Den Firmen-/ Markennamen, unter dem Du bei Zalando registriert bist
* Deine plenty-ID
* Die ID des Zalando-Kontos (accountId) in plentymarkets, das für die Zalando-Schnittstelle freigeschaltet werden soll +
*_Hinweis:_* Pro Händler:innenkonto bei Zalando kann nur ein Konto bei plentymarkets verknüpft werden.

[#assistant-2]
=== Assistent Teil 2: Ländereinstellungen

Der plentymarkets Support hat dein Konto mit deinem zDirect-Konto verknüpft? Dann kann es jetzt weitergehen.

:menu-path: pass:quotes[*Einrichtung » Assistenten » Omni-Channel*]
:assistant-name: Kontoeinstellungen - Zalando
:number-of-boxes: Info-Boxen

include::partial$assistant-basic-instructions.adoc[]

[.collapseBox]
.Schritt *Aufträge*
--

[[assistant-zalando-orders]]
[cols="1,3a"]
|===
|Einstellung |Erläuterung

| *Aus welchen Ländern sollen Aufträge importiert werden?*
| include::page$zalando.adoc[tag=zalando-countries]

*_Du kannst keine Länder wählen?_* Dann wurde dein Konto noch nicht mit mit dem zDirect-Konto verknüpft. (<<#link-zDirect, Was muss ich tun?>>)
|===
--

[.collapseBox]
.Schritte *Bestände*
--

Für jedes Land, das du im Schritt *Aufträge* gewählt hast, wird ein eigener Schritt *Bestände* zum Assistenten hinzugefügt. Die Einstellungen sind für alle Länder gleich:

[[assistant-zalando-stock]]
[cols="1,3a"]
|===
|Einstellung |Erläuterung

| *Möchtest du Bestandsdaten zu Zalando exportieren?*
| *Bestandsexport aktivieren* = Option aktivieren, um alle 15 Minuten deinen Bestand zu Zalando zu exportieren.

| *In welche Schnittstellenumgebung sollen die Bestandsdaten exportiert werden?*
a| Wählen, ob echte Daten oder Testdaten exportiert werden sollen.

* *Sandbox* = Testdaten werden an Zalando exportiert.
* *Productive* = Echte Bestandsdaten werden an Zalando exportiert.

| *Aus welchen Vertriebslagern sollen Bestandsdaten exportiert werden?*
a| Ein oder mehrere Vertriebslager wählen. Die Summe des Nettobestands dieser Vertriebslager wird exportiert. +
*_Tipp:_* Du kannst in diesem Schritt des Assistenten einen *Bestandspuffer* festlegen. Die Summe des Nettobestands der gewählten Vertriebslager wird dann um die als Bestandspuffer eingegebenen Stückzahl reduziert.

| *Wie viel Bestand soll maximal exportiert werden?*
a| Wenn eine Variante einen höheren Bestand hat, wird stattdessen der im Feld *Maximaler Bestand* eingegebene Wert exportiert.

| *Welcher Bestandspuffer soll vom exportierten Bestand abgezogen werden?*
a| Die im Feld *Bestandspuffer* eingegebene Stückzahl wird vor dem Export vom Nettowarenbestand jeder Variante abgezogen.

| *Wie viel Bestand soll für Varianten ohne Beschränkung auf den Nettowarenbestand exportiert werden, wenn diese Varianten keinen positiven Nettowarenbestand haben?*
a| In das Feld *Bestand ohne Bestandsbeschränkung* den Bestand eingeben, der für Varianten ohne Beschränkung auf den Nettowarenbestand exportiert werden soll. Varianten ohne Bestandsbeschränkung sind Varianten, bei denen im Tab *Einstellungen* der Variante für die Einstellung *Beschränkung* die Option *Keine* gewählt ist und der Nettowarenbestand nicht positiv ist.

| *Wie viel Bestand soll für Varianten ohne Warenbestandsführung exportiert werden?*
a| In das Feld *Bestand ohne Bestandsführung* den Bestand eingeben, der für Varianten ohne Warenbestandsführung exportiert werden soll. Varianten ohne Warenbestandsführung sind Varianten, bei denen im Tab *Einstellungen* für die Einstellung *Beschränkung* die Option *Keinen WB für diese Variante führen* gewählt wurde. Für diese Varianten wird der eingetragene Wert exportiert.

|===
--

[.collapseBox]
.Schritte *Preise*
--

Für jedes Land, das du im Schritt *Aufträge* gewählt hast, wird ein eigener Schritt *Preise* zum Assistenten hinzugefügt. Die Einstellungen sind für alle Länder gleich:

[[assistant-zalando-prices]]
[cols="1,3a"]
|===
|Einstellung |Erläuterung

| *Möchtest du Preise zu Zalando exportieren?*
| *Preisexport aktivieren* = Option aktivieren, um alle 15 Minuten deine Preise zu Zalando zu exportieren. +
*_Tipp:_* Informationen zu den Preis-Updates findest du in den Preis-Berichten.

<<#915, So lädst du Preis-Berichte herunter>>

| *In welche Schnittstellenumgebung sollen die Preise exportiert werden?*
a| Wählen, ob echte Daten oder Testdaten exportiert werden sollen.

* *Sandbox* = Testdaten werden an Zalando exportiert.
* *Productive* = Echte Preisdaten werden an Zalando exportiert.

| *Sollen Warnungen zu Preisaktualisierungen von Zalando ignoriert werden?*
a| Bei Preisaktualisierungen prüft Zalando die Plausibilität deiner Preise anhand von bestimmten Kriterien. Zalando vergleicht zum Beispiel die Preise der Varianten auf den verschiedenen Plattformen miteinander und gleicht den normalen Preis mit dem reduzierten Preis ab. Bei Auffälligkeiten gibt Zalando eine Warnung aus. Wähle, ob solche Warnungen bei Preisaktualisierungen ignoriert werden sollen.

* icon:toggle-on[role="green"] = Die neuen Preise gehen trotz Warnung live.
* icon:toggle-off[role="darkGrey"] (Standardeinstellung) = Zalando lehnt neue Preise ab, wenn sie die Plausibilitätsprüfung nicht bestehen. +
*_Tipp:_* Warnungen findest du im Menü *Daten » Log* und in den Preis-Berichten.

| *Welcher Verkaufspreis soll als normaler Preis zu Zalando exportiert werden?*
| Verkaufspreis aus der Dropdown-Liste wählen, der als *Normaler Preis* zu Zalando exportiert werden soll. Es stehen nur Verkaufspreise des Typs *Standard* oder *UVP* zur Auswahl, für die die Herkunft Zalando, das Land und die Währung des Landes aktiviert sind. +
*_Hinweis:_* Wenn du für eine Variante einen *reduzierten Preis* angibst, wird der *normale Preis* als Streichpreis zu Zalando übertragen.

|*Welcher Verkaufspreis soll als reduzierter Preis zu Zalando exportiert werden?*
|Verkaufspreis aus der Dropdown-Liste wählen, der als *Reduzierter Preis* zu Zalando exportiert werden soll. Es stehen nur Verkaufspreise des Typs *Aktionspreis* oder *Standard* zur Auswahl, für die die Herkunft Zalando, das Land und die Währung des Landes aktiviert sind. +
*_Hinweis:_* Wenn du für eine Variante einen *reduzierten Preis* angibst, wird der *normale Preis* als Streichpreis zu Zalando übertragen.

| *Mit geplanten Preisen kannst du zeitlich begrenzte oder auch dauerhafte Preisänderungen bei Zalando vorab ankündigen.*
a|
Definiere bis zu drei geplante Preise. Geplante Preise geben dir mehr Sicherheit, dass deine Preise zum gewünschten Zeitpunkt auf Zalando geändert werden. Um geplante Preise an Zalando zu übertragen, benötigst du mindestens einen Verkaufspreis für den normalen Preis und eine Eigenschaft, die Startdatum und Startzeit für den neuen Preis enthält. Das Startdatum für geplante Preise muss in der Zukunft liegen. Optional kannst du auch eine Eigenschaft für ein Enddatum für den geplanten Preis wählen.

* *Eigenschaft für Startdatum* = Eigenschaft aus der Dropdown-Liste wählen, mit der der Startzeitpunkt des geplanten Preises an der Variante gepflegt wird. Nur Eigenschaften vom Typ *Datum* oder *Text* können gewählt werden. +
*_Hinweis:_* Die Startzeitpunkte mehrerer geplanter Preise müssen mindestens 60 Minuten auseinanderliegen.
* *Eigenschaft für Enddatum* (optional) = Eigenschaft aus der Dropdown-Liste wählen, mit der der Endzeitpunkt des geplanten Preises an der Variante gepflegt wird. Nur Eigenschaften vom Typ *Datum* oder *Text* können gewählt werden.
* *Preis wählen* = Verkaufspreis aus der Dropdown-Liste wählen, der als *Geplanter Preis* zu Zalando exportiert werden soll.

|===
--

[.collapseBox]
.Schritt *Konto-Aktivierung*
--
*Möchtest du dein Zalando-Konto jetzt aktivieren?*

Du hast die Einrichtung noch nicht abgeschlossen. Aktiviere das Zalando-Konto deshalb noch nicht.
--

[#more-setup]
== Weitere Einrichtung vornehmen

[#250]
=== Auftragsherkunft aktivieren

:market: Zalando
:referrer: Zalando
:referrer-option: pass:quotes[Zalando-Plattformen, zum Beispiel *Zalando DE*]

include::partial$auftragsherkunft-aktivieren.adoc[]


[.collapseBox]
.Liste der Auftragsherkünfte
--
118 = Zalando +
118.01 = Zalando DE +
118.02 = Zalando NL +
118.03 = Zalando FR +
118.04 = Zalando IT +
118.05 = Zalando UK +
118.06 = Zalando AT +
118.07 = Zalando CH +
118.08 = Zalando PL +
118.09 = Zalando BE +
118.1 = Zalando SE +
118.11 = Zalando FI +
118.12 = Zalando DK +
118.13 = Zalando ES +
118.14 = Zalando NO +
118.15 = Zalando CZ +
118.16 = Zalando IE +
118.17 = Zalando PT +
118.18 = Zalando SK +
118.19 = Zalando SI +
118.2 = Zalando LT +
118.21 = Zalando LV +
118.22 = Zalando EE +
118.23 = Zalando HR +
--

[#350]
=== Verkaufspreis festlegen

:referrer-price: Zalando

include::partial$verkaufspreis-festlegen.adoc[]

[#600]
== Artikelexport per Katalog einrichten

include::partial$zalando-to-catalogue.adoc[]

[#prepare-variations]
== Varianten vorbereiten

Bereite nun deine Varianten vor.

[#300]
=== Variantenverfügbarkeit einstellen

:market-availability: Zalando
:option-availability: Zalando
:web-api:

include::partial$variantenverfuegbarkeit.adoc[]

// Web-API erforderlich!

[#330]
=== _Optional:_ SKU speichern

:referrer-sku: Zalando
:referrer-id: 118
:sku-others:

include::partial$sku-manuell.adoc[]

// Marktplatzkonto nicht erforderlich!

[#600]
=== Eigenschaften mit Artikeln verknüpfen

Verknüpfe nun die Zalando-Eigenschaften mit den Varianten, die du auf Zalando verkaufen möchtest.

Verknüpfe mindestens die folgenden Eigenschaften, damit deine Varianten an Zalando übertragen werden können:

* 1. Farbcode
* Altersgruppe(n)
* Geschlecht
* Größenregister
* Hersteller-Code
* Herstellerfarbe
* Jahreszeiten-Code
* Silhouetten-Typ

// TODO: Anleitung einfügen.

[#1100]
=== Checkliste für den Variantenexport

Zalando erwartet bestimmte Pflichtangaben. Nur Varianten werden also an den Marktplatz exportiert, für die diese Angaben gespeichert sind. Die in <<#zalando-varianten-pflicht>> aufgeführten Angaben müssen an allen Varianten gespeichert sein, die an Zalando exportiert werden sollen.

[[zalando-varianten-pflicht]]
.Pflichtfelder an der Variante
[cols="1,3a"]
|===
|Pflichtdaten |Erläuterung

| EAN
a| Für jede Variante muss eine EAN gespeichert sein.

* Im Menü *Einrichtung » Artikel » Barcode* muss eine EAN eingerichtet und mit der Herkunft Zalando verknüpft sein.
* Die EAN muss im Tab *Einstellungen* der Variante im Bereich *Barcode* hinzugefügt und ein Barcode-Code eingegeben werden.

| Technische Daten
a| Für jeden Artikel müssen technische Daten gespeichert sein.

* Im Tab *Texte* des Artikels muss im Feld *Technische Daten* Text gespeichert sein.

| Bilder
a| Für jede Variante muss ein Bild gespeichert sein.

* Im Tab *Bilder* des Artikels muss in der Dropdown-Liste *Verfügbarkeit* die Option *Zalando* aktiviert sein.

| Preis
a| Für jede Variante muss ein Preis gespeichert sein.

* Der Verkaufspreis muss im Menü *Einrichtung » Artikel » Verkaufspreise* für die Herkunft Zalando aktiviert sein.
* Der Verkaufspreis muss im Tab *Einstellungen* einer Variante im Bereich *Verkaufspreise* hinzugefügt werden.
* Ein Preis muss für den Verkaufspreis gespeichert sein.

| Supplier-SKU
a| Für jede Variante muss eine Supplier-SKU gespeichert sein. Speichere diese Supplier-SKU im Feld *Modell* der Variante.

| Eigenschaften
a| Mindestens die folgenden Daten müssen als Eigenschaften mit der Variante verknüpft sein:

* 1. Farbcode
* Altersgruppe(n)
* Geschlecht
* Größenregister
* Hersteller-Code
* Herstellerfarbe
* Jahreszeiten-Code
* Silhouetten-Typ

| Attribute
a| Mindestens die folgenden Attribute müssen mit der Variante verknüpft sein:

* Größe (size register)

_und/oder_

* Farbe für 1. Farbcode / Herstellerfarbe

_und/oder_

* Länge (length register) bei Längenangaben (z.B. Hosenlänge)

*_Hinweis:_* Pro Attribut kann nur ein Größenregister oder ein Längenregister verknüpft werden.
|===

[#artikel-entfernen]
== Artikel nicht mehr auf Zalando verkaufen

Varianten können nicht mehr auf Zalando gekauft werden, wenn sie in plentymarkets keinen Bestand mehr haben. Dies passiert automatisch, denn Bestandsdaten werden alle 15 Minuten zu Zalando übertragen. Wenn die Variante in deinem plentymarkets System wieder Bestand hat, wird sie mit der nächsten Bestandsübertragung also auch wieder auf Zalando zum Verkauf angeboten.

Wenn du eine Variante, die in plentymarkets Bestand hat, nicht mehr auf Zalando verkaufen möchtest, musst du an der Variante die Verfügbarkeit für den Marktplatz entfernen und den Zeitstempel für Marktplatzexporte aktualisieren.

*_Hinweis:_* Auf Zalando können Artikel nicht gelöscht werden. Wenn du die Verfügbarkeit entfernst und den Zeitstempel für Marktplatzexporte aktualisierst, wird deine Variante auf Zalando also nicht gelöscht, sondern nur als nicht mehr auf Lager angezeigt.

[.instruction]
Verfügbarkeit entfernen:

. Öffne das Menü *Artikel » Artikel bearbeiten » [Artikel öffnen] » [Variante öffnen] » Varianten-Tab: Verfügbarkeit*.
. *Lösche* (icon:minus-circle[role="red"]) die Verfügbarkeit *Zalando*.
. *Speichere* (terra:save[]) die Einstellungen.

Nachdem du die Verfügbarkeit entfernt hast, musst du über die *Artikel-Gruppenfunktion* den *Zeitstempel für Marktplatzexporte aktualisieren*, damit der Bestand *0* an Zalando übertragen wird.

[.instruction]
Zeitstempel für Marktplatzexporte aktualisieren:

. Öffne das Menü *Artikel » Artikel bearbeiten » Tab: Artikel-Gruppenfunktion*.
. Setze ein Häkchen bei *Zeitstempel für Marktplatzexporte aktualisieren*.
. Klicke auf terra:execute[] *Ausführen*. +
→ Der Bestand *0* wird an Zalando übertragen. +
→ Die Variante wird auf Zalando als momentan nicht auf Lager angezeigt und kann nicht mehr gekauft werden.

[#order-documents]
== Auftragsdokumente vorbereiten

include::partial$zalando-order-documents.adoc[]

[#1200-1]
== Auftragsabwicklung automatisieren

include::partial$zalando-order-processing.adoc[]

[#1500]
== Datenaustausch starten: Zalando-Konto aktivieren

Du hast alle Einstellungen vorgenommen? Dann kann es jetzt losgehen!
Aktiviere dein Zalando-Konto im Assistenten *Kontoeinstellungen - Zalando*, um den Datenaustausch mit Zalando zu starten.

[.collapseBox]
.Vorgehen bei "Dieses Konto kann nicht aktiviert werden."
--
Der Datenaustausch mit Zalando ist nicht aktiv. Um die zDirect-API-Schnittstelle von Zalando zu aktivieren, muss dein Zalando-Konto mit dem plentymarkets Entwicklungskonto verknüpft werden. Diese Verknüpfung passiert im Verlauf der Integration automatisch. Allerdings muss plentymarkets in einem zusätzlichen Schritt Zugangsdaten für die API generieren und diese Zugangsdaten in deinem System hinterlegen. Diese Zugangsdaten dürfen nicht von dir einsehbar sein. Deshalb kann plentymarkets dir die Zugangsdaten nicht bereitstellen. Melde dich in link:https://forum.plentymarkets.com/t/sammelthema-aktivierung-neuer-zalando-konten/600409[diesem Forum-Thread^], um die Freischaltung deines Kontos zu erbitten.

Gib in deinem Foren-Post die folgenden Informationen an:

* Den Firmen-/ Markennamen, unter dem Du bei Zalando registriert bist
* Deine Plenty-ID
* Die ID des Zalando-Kontos (accountId) in plentymarkets, das für die Zalando-Schnittstelle freigeschaltet werden soll +
*_Hinweis:_* Pro Händler:innenkonto bei Zalando kann nur ein Konto bei plentymarkets verknüpft werden.
--

[.instruction]
Zalando-Konto aktivieren:

. Öffne das Menü *Einrichtung » Assistenten » Omni-Channel*.
. Klicke auf den Assistenten *Kontoeinstellungen - Zalando*.
. Navigiere zum Schritt *Konto-Aktivierung*.
. Aktiviere die Option *Benutzerkonto aktivieren*.
. Schließe den Assistenten wie gewohnt ab. +
→ Der Datenaustausch mit Zalando wird aktiviert.

[#900]
== Berichte herunterladen

include::partial$zalando-reports.adoc[]



[#zalando-faq]
== FAQ

include::partial$zalando-faq.adoc[]
