= Zalando: Wechsel zum Katalogexport
:author: team-plenty-channel
:keywords: Zalando, Zalando, zalando.de, zalando.de, salando, zalando.com
:description: Auf dieser Seite erfährst du, wie du vom alten Artikelexport von Zalando zum neuen Katalogexport wechselst.
:page-index: false

:market: Zalando
:zalando:
:catalogue:

Du verkaufst schon auf Zalando mit plentymarkets und möchtest zum Katalogexport wechseln? Dann findest du hier Empfehlungen für den Wechsel.

[IMPORTANT]
.Noch keine Erfahrung mit den Katalogen?
====
Du arbeitest zum ersten Mal mit den Katalogen? Dann mache dich zuerst xref:daten:kataloge-verwalten.adoc#[mit dem Prinzip der Kataloge vertraut].
====

[#8H7KSOJK]
== Ablauf

Hier siehst du eine Übersicht der erforderlichen Schritte, um deinen Artikelexport für Zalando auf die Kataloge umzuziehen:

[cols="1,5a", grid=none, frame=none, stripes=none]
|===

|*Schritt 1*
| <<#WW6M57OM, Eigenschaften für Pflichtfelder vorbereiten>>

|*Schritt 2*
| <<#WY11C9A9, Katalog erstellen>>

|*Schritt 3*
| <<#B6YW0S6N, Marktplatz-Datenfelder im Katalog prüfen>>

|*Schritt 4*
| <<#AB4Q5APB, Datenfelder im Katalog zuordnen>>

| *Schritt 5*
| <<#07HJGHIE, Varianten mit Eigenschaften verknüpfen>>

| *Schritt 6*
| <<#AB4Q5ABB, Katalog aktivieren>>

| *Schritt 7*
| <<#AC4Q5ABB, Katalogexport im Assistenten aktivieren>>
|===

[#WW6M57OM]
== Eigenschaften für die Pflichtfelder vorbereiten

include::partial$zalando-to-catalogue.adoc[tag=prepare-properties-zalando]

[#WY11C9A9]
== Katalog erstellen

Erstelle einen Katalog mit dem Template *Zalando*.

[.collapseBox]
.Wie geht das?
--
Artikeldaten werden über das Marktplatz-Format *Zalando* zu Zalando exportiert. Um deine Artikel zu Zalando zu übertragen, erstellst du im Menü *Daten » Kataloge* einen Katalog. Ordne dann im Marktplatz-Format die von Zalando vorgegebenen Felder den in plentymarkets gespeicherten Artikeldaten zu.

*_Hinweis:_* Für jede Zalando-Kategorie benötigst du einen eigenen Katalog.

:catalogue-template-name: Zalando
:format-item-new:

include::partial$catalogue-creation.adoc[]
--

[#B6YW0S6N]
== Marktplatz-Datenfelder prüfen

Prüfe im Katalog, ob du weitere Eigenschaften benötigst. Scrolle durch den Katalog und prüfe die Zalando-Datenfelder. Kannst du alle Felder zuordnen, für die du Daten an Zalando exportieren möchtest?

Wenn nicht, erstelle die Eigenschaften, die du benötigst.

* Du arbeitest zum ersten Mal mit den Eigenschaften? Dann mach dich zuerst xref:artikel:eigenschaften.adoc#500[mit dem Prinzip der Eigenschaften vertraut].

[#AB4Q5APB]
== Datenfelder im Katalog zuordnen

Du hast einen Katalog erstellt und wenn nötig Eigenschaften erstellt. Super. Dann ordne die Datenfelder des Marktplatzes jetzt passenden plentymarkets Datenfeldern zu.

[.collapseBox]
.Wie geht das?
--
Nachdem du einen Katalog erstellt hast, ordnest du die Datenfelder des Marktplatzes den in plentymarkets gespeicherten Artikeldaten zu. Informationen dazu, welche Daten für welches Datenfeld des Marktplatzes übertragen werden müssen, findest du in der Dokumentation des Marktplatzes.

include::partial$catalogue-mapping.adoc[]
--

[#AB4Q5APQ]
== Varianten mit Eigenschaften verknüpfen

Verknüpfe jetzt deine Varianten mit den Eigenschaften, die du für Zalando benötigst. Wie oben beschrieben musst du mindestens die Pflichtfelder an Zalando exportieren.

[#AB4Q5ABB]
== Katalog aktivieren

:interval: einmal täglich nachts
:market: Zalando

include::partial$catalogue-activation.adoc[]

[#AC4Q5ABB]
== Katalogexport im Assistenten aktivieren

Nun ist es Zeit, den alten Export abzuschalten und den neuen Katalogexport zu aktivieren. Diese Einstellung nimmst du im Assistenten vor.

[.instruction]
Katalogexport im Assistenten aktivieren:

. Öffne das Menü *Einrichtung » Assistenten » Omni-Channel*.
. Klicke auf den Assistenten *Kontoeinstellungen - Zalando*.
. Wechsle in den Schritt *Artikelexport*.
. Aktiviere die Option *Katalog nutzen*.
. Klicke auf *Abschließen*. +
→ Die Einstellungen werden gespeichert. +
→ Artikeldaten werden ab jetzt über den Katalog exportiert.