The plentymarkets forum is a knowledge base that keeps on growing. It already contains many solved support queries.
Our developers and other plentymarkets sellers will help you solve technical queries you might have.
In addition, you will find tips for working with plentymarkets and can exchange ideas with other plentymarkets sellers.

[TIP]
.Who is allowed to create an account for the forum?
====
* You can create a forum account for yourself, i.e. for your own plentymarkets account.
* Admins can create forum accounts for other users, i.e. for other plentymarkets accounts within their system.
====

You've never used the plentymarkets forum?
No problem!
Simply create a user account and you'll be ready to go.

[#155]
[.instruction]
Creating a new account for the plentymarkets forum:

. Go to *Setup » Account management » Accounts*.
. Click on the appropriate user account. +
→ The user account opens in a new tab.
. Go to the area *Login data* and click on *Enable Forum Account*. +
→ The forum account is created.
