The plentymarkets forum is a knowledge base that keeps on growing. It already contains many solved support queries.
Our developers and other plentymarkets sellers will help you solve technical queries you might have.
In addition, you will find tips for working with plentymarkets and can exchange ideas with other plentymarkets sellers.

[TIP]
.Who is allowed to create an account for the forum?
====
* You can create a forum account for yourself, i.e. for your own plentymarkets account.
* Admins can create forum accounts for other users, i.e. for other plentymarkets accounts within their system.
====

[#155]
=== Creating a new forum account

You’ve never used the plentymarkets forum?
No problem!
Simply create a user account and you’ll be ready to go.

[.instruction]
Creating a new account for the plentymarkets forum:

. Go to *Setup » Settings » User » Accounts*.
. Click on the appropriate user account. +
→ The user account opens in a new tab.
. Scroll down to the *plentymarkets Forum* area and click on icon:plus[role="green"] *Create account*. +
→ The forum account is created.

[#157]
=== Transferring an existing forum account

It’s possible to migrate an existing forum account.
This is useful, for example:

* if you will soon switch from one plentymarkets system to another.
This way you can take your existing forum account with you.
* if your forum supporter has left the company and his successor should be given the account.

The migration prevents previous badges, posts and contacts from being lost.

[IMPORTANT]
.Are you allowed to transfer the forum account?
====
First, get permission to transfer the forum account.
Avoid future conflicts by informing all parties about the planned transfer and obtaining their consent.
plentymarkets ensures that all parties have agreed to the transfer by generating an auth code.
====

[.instruction]
Step 1: The first account agrees to the transfer:

. Go to *Setup » Settings » User » Accounts*.
. Click on whichever user account should be transferred. +
→ The user account opens in a new tab.
. Scroll down to the *plentymarkets Forum* area and click on icon:execute[set=plenty] *Generate migration auth code*. +
→ The auth code will be displayed in the plentymarkets back end. +
→ The auth code will be displayed in the *AuthCode* field within the forum profile.
. Copy the auth code and give it to the person who should receive the forum account.

[.instruction]
Step 2: The second account completes the transfer:

. Go to *Setup » Settings » User » Accounts*.
. Click on whichever user account should receive the forum account. +
→ The user account opens in a new tab.
. Scroll down to the *plentymarkets Forum* area and enter the code into the text field between the two buttons.
. Click on icon:execute[set=plenty] *Migrate user from another system*. +
→ The forum account will be transferred.
