////
zuletzt bearbeitet 01.04.2022
////

//tag::pim-preamble[]
PIM steht für [.underline]##P##roduct [.underline]##I##nformation [.underline]##M##anagement.
Mit dem PIM von plentysystems verwaltest du alle Informationen deiner Artikel in einem zentralen System.
Das heißt, du pflegst deine Produktdaten in plentysystems ein.
Daraufhin kannst du deine Ware auf diversen xref:maerkte:maerkte.adoc#[Marktplätzen], im eigenen xref:webshop:webshop.adoc#[plentyShop] und im xref:pos:pos.adoc#[stationären Laden] verkaufen.

Müssen Daten, wie z.B. die Beschreibung oder der Preis eines Artikels, zu einem späteren Zeitpunkt geändert werden, musst du diese Daten lediglich zentral in plentysystems ändern.
Die Änderung kann automatisch auf allen genutzten Vertriebskanälen angezeigt werden.
//end::pim-preamble[]

[#100]
== Einführung in die Artikelstruktur

//tag::intro[]
Du bist neu bei plentysystems?
Bevor du deine Daten einpflegst, lerne die Artikelstruktur kennen!
Die Einführung bietet dir einen Überblick über das Thema und beantwortet deine grundlegenden Fragen:

* Was ist der Unterschied zwischen xref:artikel:struktur.adoc#[Artikeln und Varianten]?
* Wie funktioniert die xref:artikel:vererbung.adoc#[Vererbung]?
* Wo finde ich meine xref:artikel:suche.adoc#100[Artikel im Backend]?
* Kann ich auch ein paar xref:artikel:suche.adoc#900[Beispielartikel] sehen?
//end::intro[]

[#200]
== Vorbereitende Einstellungen

//tag::vorbereitung[]
Zu deinen Artikeldaten gehören diverse Angaben, wie z.B. Kategorien, Preise und Hersteller.
Bevor du aber einen Artikel in eine bestimmte Kategorie einsortieren kannst, muss die Kategorie erst einmal in plentysystems existieren.
Bevor du den Hersteller eines Artikels auswählen kannst, müssen die Herstellerdaten in plentysystems vorhanden sein.
//end::vorbereitung[]

Nachdem du solche vorbereitenden Einstellungen einmalig in plentysystems gespeichert hast, kannst du sie daraufhin auf alle zutreffenden Artikel und Varianten anwenden.

include::page$struktur.adoc[tag=systemeinstellungen-liste]

[#300]
== Import, Export und manuelle Bearbeitung

//tag::import-export-anlage[]

Bist du bereit, deine Artikeldaten in plentysystems einzupflegen?
Oder willst du Produktdaten zwischen deinem System und anderen, externen Systemen austauschen?
Es gibt viele Möglichkeiten, Artikeldaten zu importieren, zu exportieren und manuell zu bearbeiten.

[.collapseBox]
.*Import*
--

[cols="2*", width=100%, grid=cols, frame=none, stripes=none]
|===

a| *_Import-Tool_*:

* xref:daten:ElasticSync.adoc#[Allgemeine Infos zum Import-Tool]
* xref:daten:best-practices-elasticsync-variantenanlage.adoc#[Praxisbeispiel: Import von Artikeln und Varianten]
* xref:daten:elasticSync-artikel.adoc#[Verzeichnis aller Datenfelder für den Artikelimport]

a| *_Sonstige Imports_*:

* xref:willkommen:assistenten.adoc#[Artikel mit Hilfe des "Artikelimport" Assistenten importieren].
* xref:maerkte:ebay-einrichten.adoc#11000[Artikel aus vorhandenen eBay-Listings importieren].
* xref:daten:rest-api.adoc#[Artikel aus externen Systemen mit der REST-API importieren].
|===

--

[.collapseBox]
.*Export*
--

[cols="2*", width=100%, grid=cols, frame=none, stripes=none]
|===

a| *_Katalog-Tool_*:

* xref:daten:kataloge.adoc#[Allgemeine Infos zum Katalog-Tool]
* xref:daten:katalog-artikel.adoc#[Verzeichnis aller Datenfelder für den Artikelexport (Katalog)]

a| *_FormatDesigner + Elastischer Export_*:

* xref:daten:elastischer-export.adoc#[Allgemeine Infos zum Elastischen Export]
* xref:daten:formatdesigner-artikel.adoc#[Verzeichnis aller Datenfelder für den Artikelexport (FormatDesigner)]
|===

--

[.collapseBox]
.*Manuelle Bearbeitung*
--

[cols="2*", width=100%, grid=cols, frame=none, stripes=none]
|===

a| *_Neue Artikel-UI (open beta)_*:

* xref:artikel:suchen.adoc#[Artikel suchen]
* xref:artikel:detailansicht.adoc#[Detailansicht: Gestaltung]
* xref:artikel:artikel-manuell-anlegen.adoc#[Artikel und Varianten manuell anlegen]

a| *_Alte Artikel-UI_*:

* xref:artikel:neue-artikel.adoc#[Neue Artikel manuell anlegen]
* xref:artikel:artikel-verwalten.adoc#[Verzeichnis aller Artikeldatenfelder]
* xref:artikel:massenbearbeitung.adoc#[Mehrere Artikel gleichzeitig bearbeiten]
|===

--

//end::import-export-anlage[]

[#500]
== Anwendungsfälle

//tag::anwendungsfaelle[]
Hast du einen bestimmten Anwendungsfall im Sinn?
In diesem Themenbereich lernst du:

* xref:artikel:multipacks-pakete-sets.adoc#[Produkte zu kombinieren] und als Verkaufseinheit anzubieten
* xref:artikel:personalisierte-artikel.adoc#[Personalisierte Artikel] in deinem plentyShop zu verkaufen
* xref:artikel:gratiszugaben.adoc#[Gratisartikel und Werbegeschenke] zu einer Bestellung hinzuzufügen
* Mit Artikeln zu arbeiten, die xref:artikel:seriennummern.adoc#[Seriennummern oder Lizenzschlüssel] haben
* xref:artikel:aenderungen.adoc#[Änderungen an Artikeln nachzuvollziehen], d.h. den ganzen Lebensweg eines Artikels zu verfolgen
* Das xref:artikel:suchverhalten.adoc#[vordefinierte Artikelsuchverhalten] im plentysystems Backend zu modifizieren
//end::anwendungsfaelle[]

[#400]
== Darstellung im plentyShop

//tag::darstellung-webshop[]
Sobald deine Artikeldaten in plentysystems vorhanden sind, geht es mit dem Verkauf weiter.
plentysystems enthält einen kostenlosen xref:webshop:webshop.adoc#[Webshop], aus dem du deine Artikel vertreiben kannst.

In diesem Themenbereich findest du schnelle Hilfe, falls deine Artikel oder Kategorien nicht im plentyShop angezeigt werden.
Du lernst außerdem, wie du zusätzliche Funktionen einrichtest, um Artikel genau nach deiner Vorstellung zu präsentieren:

* xref:artikel:checkliste-kategorien-anzeige.adoc#[Kategorie ist nicht im plentyShop sichtbar]
* xref:artikel:checkliste-artikel-anzeige.adoc#[Artikel ist nicht im plentyShop sichtbar]
* xref:artikel:suchleiste.adoc#[Suchleiste]
* xref:artikel:frontend-artikelsuche-verwalten.adoc#[Suchfilter]
* xref:artikel:cross-selling.adoc#[Cross-Selling]
* xref:artikel:shop-aktionen.adoc#[Shop-Aktionen]
//end::darstellung-webshop[]

[#600]
== Neue Artikel-UI (open beta)

Dieses Kapitel beschreibt die neue Artikel-UI, die im März 2022 in einer offenen Betaphase veröffentlicht wurde.

* UI steht für [.underline]##U##ser [.underline]##I##nterface (auf Deutsch: Benutzeroberfläche).
Mit der Formulierung "neue Artikel-UI" meinen wir also, dass es in plentysystems jetzt ein neues Menü zur Verwaltung von Artikeldaten gibt.
* "Offene Beta" bedeutet, dass du die neue Artikel-UI sehen und ausprobieren kannst.
Die neue UI hat allerdings noch nicht den vollen Funktionsumfang.

In diesem Themenbereich lernst du:

* xref:artikel:suchen.adoc#[nach Artikeln und Varianten zu suchen]
* xref:artikel:detailansicht.adoc#[die Detailansicht an deine Bedürfnisse anzupassen]
* xref:artikel:artikel-manuell-anlegen.adoc#[Artikel und Varianten manuell anzulegen]
