////
zuletzt bearbeitet 30.07.2021
////

Artikeldaten werden in plentymarkets zentral verwaltet.
Das heißt, dass du deine Produktdaten in plentymarkets einpflegst.
Daraufhin kannst du deine Ware anschließend auf diversen <<maerkte#, Marktplätzen>>, im eigenen <<webshop#, plentyShop>> und im <<pos#, stationären Laden>> verkaufen.

Müssen Daten, wie z.B. die Beschreibung oder der Preis eines Artikels, zu einem späteren Zeitpunkt geändert werden, musst du diese Daten lediglich zentral in plentymarkets ändern.
Die Änderung kann automatisch auf allen genutzten Vertriebskanälen angezeigt werden.

[#100]
== Einführung in die Artikelstruktur

Du bist neu bei plentymarkets?
Bevor du deine Daten einpflegst, lerne die Artikelstruktur kennen!
Die Einführung bietet dir einen Überblick über das Thema und beantwortet deine grundlegenden Fragen:

* Was ist der Unterschied zwischen xref:artikel:struktur.adoc#[Artikeln und Varianten]?
* Wie funktioniert die xref:artikel:vererbung.adoc#[Vererbung]?
* Wo finde ich meine xref:artikel:suche.adoc#100[Artikel im Backend]?
* Kann ich auch ein paar xref:artikel:suche.adoc#900[Beispielartikel] sehen?

[#200]
== Vorbereitende Einstellungen

//tag::vorbereitung[]
Zu deinen Artikeldaten gehören diverse Angaben, wie z.B. Kategorien, Preise und Hersteller.
Bevor du aber einen Artikel in eine bestimmte Kategorie einsortieren kannst, muss die Kategorie erst einmal in plentymarkets existieren.
Bevor du den Hersteller eines Artikels auswählen kannst, müssen die Herstellerdaten in plentymarkets vorhanden sein.
//end::vorbereitung[]

Nachdem du solche xref:artikel:einstellungen.adoc#[vorbereitenden Einstellungen] einmalig in plentymarkets gespeichert hast, kannst du sie daraufhin auf alle zutreffenden Artikel und Varianten anwenden.

include::page$struktur.adoc[tag=systemeinstellungen-liste]

[#300]
== Import, Export und manuelle Bearbeitung

//tag::import-export-anlage[]

////
Zukunftsmusik - irgendwann bei Gelegenheit den Artikel-Assistenten im Handbuch beschreiben - ab dem Zeitpunkt, den Bulletpoint auch einblenden - Link soll dann aber auf diese Seite sein und nicht die Assistenten-Übersicht.
////

Bist du bereit, deine Artikeldaten in plentymarkets einzupflegen?
Oder willst du Produktdaten zwischen deinem plentymarkets System und anderen, externen Systemen austauschen?
Es stehen dir mehrere Tools zur Verfügung.
Du kannst Artikeldatensätze z.B.:

* xref:artikel:neue-artikel.adoc#[manuell] in plentymarkets erstellen.
* in CSV-Dateien pflegen und anschließend xref:artikel:import.adoc#[importieren].
//* mit Hilfe eines xref:willkommen:assistenten.adoc#[Assistenten] importieren.
* aus vorhandenen xref:maerkte:ebay-einrichten.adoc#11000[eBay-Listings] importieren.
* aus externen Systemen mit der xref:daten:rest-api.adoc#[REST-API] importieren.
* aus deinem plentymarkets-System xref:artikel:export.adoc#[exportieren].
//end::import-export-anlage[]

[#500]
== Anwendungsfälle

//tag::anwendungsfaelle[]
Hast du einen bestimmten Anwendungsfall im Sinn?
In diesem Themenbereich lernst du:

//* Artikeldaten in mehreren Sprachen zu pflegen
* xref:artikel:multipacks-pakete-sets.adoc#[Produkte zu kombinieren] und als Verkaufseinheit anzubieten
* xref:artikel:personalisierte-artikel.adoc#[Personalisierte Artikel] in deinem plentyShop zu verkaufen
* xref:artikel:gratiszugaben.adoc#[Gratisartikel und Werbegeschenke] zu einer Bestellung hinzuzufügen
* Mit Artikeln zu arbeiten, die xref:artikel:seriennummern.adoc#[Seriennummern oder Lizenzschlüssel] haben
* xref:artikel:aenderungen.adoc#[Änderungen an Artikeln nachzuvollziehen], d.h. den ganzen Lebensweg eines Artikels zu verfolgen
* Das xref:artikel:suchverhalten.adoc#[vordefinierte Artikelsuchverhalten] im plentymarkets Backend zu modifizieren
//end::anwendungsfaelle[]

[#400]
== Darstellung im plentyShop

//tag::darstellung-webshop[]
Sobald deine Artikeldaten in plentymarkets vorhanden sind, geht es mit dem Verkauf weiter.
plentymarkets enthält einen kostenlosen <<webshop#, Webshop>>, aus dem du deine Artikel vertreiben kannst.

In diesem Themenbereich findest du schnelle Hilfe, falls deine Artikel oder Kategorien nicht im plentyShop angezeigt werden.
Du lernst außerdem, wie du zusätzliche Funktionen einrichtest, um Artikel genau nach deiner Vorstellung zu präsentieren:

* xref:artikel:checkliste-kategorien-anzeige.adoc#[Kategorie ist nicht im plentyShop sichtbar]
* xref:artikel:checkliste-artikel-anzeige.adoc#[Artikel ist nicht im plentyShop sichtbar]
* xref:artikel:suchleiste.adoc#[Suchleiste]
* xref:artikel:frontend-artikelsuche-verwalten.adoc#[Suchfilter]
* xref:artikel:cross-selling.adoc#[Cross-Selling]
* xref:artikel:shop-aktionen.adoc#[Shop-Aktionen]
//end::darstellung-webshop[]
