Das plentymarkets Forum ist eine ständig wachsende Wissensdatenbank, die viele Antworten auf bereits gestellte Support-Fragen enthält.
Im Forum helfen dir unsere Entwickler:innen und andere plentymarkets Händler:innen bei technischen Fragen gern weiter.
Außerdem findest du dort Tipps für das Arbeiten mit plentymarkets und du tauschst dich mit anderen plentymarkets Händler:innen aus.

[TIP]
.Wer darf ein Konto für das Forum erstellen?
====
* Du kannst ein Forum-Konto für dich selbst erstellen, d.h. für dein eigenes plentymarkets-Konto.
* Admins können Forum-Konten für andere Benutzer:innen erstellen, d.h. für andere plentymarkets-Konten innerhalb ihres Systems.
====

Du hast das plentymarkets Forum noch nie benutzt?
Kein Problem!
Erstelle ganz einfach ein Benutzerkonto und schon kann es losgehen.

[#155]
[.instruction]
Neues Konto für plentymarkets Forum erstellen:

. Öffne das Menü *Einrichtung » Kontoverwaltung » Konten*.
. Klicke auf das betreffende Benutzerkonto. +
→ Das Benutzerkonto wird in einem neuen Tab geöffnet.
. Klicke im Bereich *Anmeldedaten* auf *Aktiviere Forum-Konto*. +
→ Das Forum-Konto wird erstellt.