Das plentymarkets Forum ist eine ständig wachsende Wissensdatenbank, die viele Antworten auf bereits gestellte Support-Fragen enthält.
Im Forum helfen dir unsere Entwickler:innen und andere plentymarkets Händler:innen bei technischen Fragen gern weiter.
Außerdem findest du dort Tipps für das Arbeiten mit plentymarkets und du tauschst dich mit anderen plentymarkets Händler:innen aus.

[TIP]
.Wer darf ein Konto für das Forum erstellen?
====
* Du kannst ein Forum-Konto für dich selbst erstellen, d.h. für dein eigenes plentymarkets-Konto.
* Admins können Forum-Konten für andere Benutzer:innen erstellen, d.h. für andere plentymarkets-Konten innerhalb ihres Systems.
====

[#155]
=== Ein neues Forum-Konto erstellen

Du hast das plentymarkets Forum noch nie benutzt?
Kein Problem!
Erstelle ganz einfach ein Benutzerkonto und schon kann es losgehen.

[.instruction]
Neues Konto für plentymarkets Forum erstellen:

. Öffne das Menü *Einrichtung » Einstellungen » Benutzer » Konten*.
. Klicke auf das betreffende Benutzerkonto. +
→ Das Benutzerkonto wird in einem neuen Tab geöffnet.
. Scrolle unten bis zum Abschnitt *plentymarkets Forum* und klicke auf icon:plus[role="green"] *Konto erstellen*. +
→ Das Forum-Konto wird erstellt.

[#157]
=== Ein bestehendes Forum-Konto übertragen

Es ist möglich, ein bestehendes Forum-Konto zu migrieren.
Dies ist zum Beispiel sinnvoll, wenn:

* du bald von einem plentymarkets-System auf ein anderes wechseln wirst.
So kannst du dein bestehendes Forum-Konto mitnehmen.
* dein Forum-Supporter das Unternehmen verlassen hat und sein Nachfolger das Konto erhalten soll.

Die Migration verhindert, dass frühere Beiträge, Abzeichnungen und Kontakte verloren gehen.

[IMPORTANT]
.Darfst du das Forum-Konto übertragen?
====
Hol dir zuerst die Erlaubnis, das Forum-Konto zu übertragen.
Um spätere Konflikte zu vermeiden, sollen alle Beteiligten über den geplanten Wechsel informiert werden und ihm zustimmen.
plentymarkets stellt durch die Generierung eines Auth-Codes sicher, dass alle Beteiligten der Weitergabe zugestimmt haben.
====

[.instruction]
Schritt 1: Erstes Konto stimmt der Übertragung zu:

. Öffne das Menü *Einrichtung » Einstellungen » Benutzer » Konten*.
. Klicke auf das Benutzerkonto, das übertragen werden soll. +
→ Das Benutzerkonto wird in einem neuen Tab geöffnet.
. Scrolle unten bis zum Abschnitt *plentymarkets Forum* und klicke auf icon:execute[set=plenty] *Auth Code für die Migration generieren*. +
→ Der Auth-Code wird im plentymarkets Backend angezeigt. +
→ Der Auth-Code wird im Feld *AuthCode* innerhalb des Forum-Profils angezeigt.
. Kopiere den Auth-Code und leite ihn an die Person weiter, die das Forum-Konto erhalten soll.

[.instruction]
Schritt 2: Zweites Konto führt die Übertragung durch:

. Öffne das Menü *Einrichtung » Einstellungen » Benutzer » Konten*.
. Klicke auf das Benutzerkonto, das das Forum-Konto erhalten soll. +
→ Das Benutzerkonto wird in einem neuen Tab geöffnet.
. Scrolle unten bis zum Abschnitt *plentymarkets Forum* und gib den Code in das Textfeld zwischen den beiden Schaltflächen ein.
. Klicke auf icon:execute[set=plenty] *Benutzer von einem anderen System migrieren*. +
→ Das Forum-Konto wird übertragen.
