[.collapseBox]
.*Tipp: So filterst du Einträge im API-Log*
--

Standardmäßig werden die Einträge absteigend nach ihrer ID aufgelistet. Die Einträge lassen sich filtern, sodass die Anzahl der aufgelisteten Einträge verringert wird. Zur Verfügung stehen dir ein API-Namensfilter und ein Datumsfilter. Du kannst auch beide Filter kombinieren, um nur Einträge eines Formates für einen spezifischen Tag zu erhalten.

[.instruction]
Log-Einträge nach Name filtern:

. Öffne das Menü *Daten » API Log*.
. Wähle ein Format aus der Dropdown-Liste *Vorgang*.
. Klicke auf *Suchen* (icon:search[role="darkGrey"]).

[IMPORTANT]
.Das gewünschte Format wird nicht angezeigt?
======
Die Formate stehen in der Dropdown-Liste *Vorgang* erst dann zur Verfügung, wenn der Prozess ausgeführt und protokolliert wurde. Wenn du neue Formate hier nicht findest, wurde der Prozess noch nicht ausgeführt oder der gesuchte Fehler ist noch nicht aufgetreten.
======

[.instruction]
Log-Einträge nach Datum filtern:

. Öffne das Menü *Daten » API Log*.
. Wähle ein *Datum* aus dem Kalender.
. Klicke auf *Suchen* (icon:search[role="darkGrey"]).

--
