
[cols="1,4a"]
|===
|Einstellung |Erläuterung

| *Gruppen* +
([red]#Pflichtfeld#)
|Jede Eigenschaft muss zu mindestens einer Gruppe gehören.
Wähle die passende Gruppe aus der Dropdown-Liste aus.
Die gewählten Gruppen werden hier als sogenannte "Chips" dargestellt.
Klicke auf icon:close[set=darkGrey], um eine Gruppe wieder zu entfernen.

*_Hinweis_*: Diese Dropdown-Liste enthält nur xref:artikel:eigenschaften.adoc#1200[Eigenschaftsgruppen, die bereits angelegt wurden].
|===

[TIP]
.Mehrere Eigenschaften einer Gruppe zuordnen
====
plentysystems enthält eine Funktion, mit der du mehrere Eigenschaften gleichzeitig einer Gruppe zuordnen kannst.

. Öffne das Menü *Einrichtung » Einstellungen » Eigenschaften » Konfiguration*.
. Wähle die Eigenschaften (icon:check-square[role="blue"]), die du der Gruppe zuordnen möchtest.
. Klicke auf *Gruppen verknüpfen* (material:link[]). +
→ Das Fenster *Gruppen verknüpfen* wird geöffnet.
. Wähle eine oder mehrere Eigenschaftsgruppen (icon:check-square[role="blue"]).
. Klicke auf *Link*. +
→ Die gewählten Eigenschaften werden den Gruppen zugeordnet.
====
