////
Nutzung:

:rights-purpose: Wofür werden die Rechte benötigt?
:right-one: *CRM > Kampagne > Code > Anzeigen*

include::PFAD_ZUR_DATEI/rechte.adoc[]

Die Attribute :right-one: bis :right-nine: enthalten die Pfade für die benötigten Rechte.
Wenn weniger als neun Rechte benötigt werden, gib das Attribut nicht an.
////

Personen mit *Backend*-Zugriffsrechten können <<business-entscheidungen/benutzerkonten-zugaenge#105, nur bestimmte Bereiche und Menüs>> in plentymarkets sehen. Sie können also nur eingeschränkt im System arbeiten. Sollen Mitarbeiter:innen mit dem Zugang *Backend* {rights-purpose}, benötigen sie mindestens die folgenden Rechte:

ifdef::right-one[]
* {right-one}
endif::[]
ifdef::right-two[]
* {right-two}
endif::[]
ifdef::right-three[]
* {right-three}
endif::[]
ifdef::right-four[]
* {right-four}
endif::[]
ifdef::right-five[]
* {right-five}
endif::[]
ifdef::right-six[]
* {right-six}
endif::[]
ifdef::right-seven[]
* {right-seven}
endif::[]
ifdef::right-eight[]
* {right-eight}
endif::[]
ifdef::right-nine[]
* {right-nine}
endif::[]

[.collapseBox]
.*Tipp: So vergibst du Rechte*
--

Beachte, dass nur *Admins* Rechte vergeben können.

[.instruction]
Rechte vergeben:

. Öffne das Menü *Einrichtung » Einstellungen » Benutzer » Rechte » Benutzer*. +
→ Die Benutzerkonten werden in einer Übersicht angezeigt.
. Klicke auf ein Benutzerkonto. +
→ Der Menüpunkt *Rechte* mit den Sichtbarkeiten wird geöffnet.
. Vergib die Rechte für den jeweiligen Bereich durch Anklicken der Checkboxen, die oben angegeben sind. +
*_Hinweis_*: Du kannst entweder Rechte für einen kompletten Bereich vergeben oder dem Konto nur eingeschränkt Rechte gewähren. Klappe für diese Option den Bereich auf.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[TIP]
======
Die Bereiche *Berechtigungen* und *Menü-Sichtbarkeiten* sind verknüpft. Wenn du also Rechte in einem der beiden Bereiche aktivierst, sind sie automatisch auch für den anderen Bereich aktiv.
======

--

:!right-one:
:!right-two:
:!right-three:
:!right-four:
:!right-five:
:!right-six:
:!right-seven:
:!right-eight:
:!right-nine:
