////
Titel: Filter speichern und anwenden (je nach Ebene der Überschrift selbst einfügen)
Unterüberschrift davon: Aktuellen Filter speichern
////

// <<#filter-als-standard, Filter als Standard>> als Anker für include-Datei NAME verwenden.


[.instruction]
Aktuellen Filter speichern:

. Führe eine Suche aus.
. Klicke auf *Gespeicherte Filter* (icon:bookmarks[set=material]).
. Klicke auf icon:bookmark_border[set=material] *Aktuellen Filter speichern*.
. Gib einen Namen für den Filter ein.
. Entscheide, ob
** dieser <<#filter-als-standard, Filter als Standard>> festgelegt werden soll (icon:toggle_on[set=material, role=skyBlue])
** dieser Filter für alle Benutzer:innen erstellt werden soll (icon:toggle_on[set=material, role=skyBlue]).
. Klicke auf *SPEICHERN*. +
→ Der Filter erscheint nun unter *Gespeicherte Filter* (icon:bookmarks[set=material]).


[cols="1,4a"]
|====
|Element |Erläuterung

| *Als Standard festlegen*
|icon:toggle_on[set=material, role="blue"] = Wenn du das Menü *Artikel » Artikel-UI* öffnest, sind die Filtereinstellungen bereits vorausgewählt und die Suche wird automatisch mit diesen Einstellungen gestartet.

icon:toggle_off[set=material] = Die Filtereinstellungen werden nicht bereits vorausgewählt sein.

| *Filter für alle Benutzer erstellen*
|
icon:toggle_on[set=material, role="blue"] = Die Filtereinstellungen werden für alle Benutzer:innenkonten sichtbar sein.

icon:toggle_off[set=material] = Die Filtereinstellungen werden nur für dein eigenes Benutzer:innenkonto sichtbar sein.

|====

[TIP]
.Filter können auch nachträglich bearbeitet werden
======
Wenn du auf *Gespeicherte Filter* (icon:bookmarks[set=material]) klickst, siehst du Optionen zum nachträglichen Bearbeiten des Filters:

icon:drag_indicator[set=material] = Legt die Reihenfolge der Filtereinstellungen per Drag & Drop fest.

icon:delete[set=material] = Löscht die Filtereinstellung.

icon:star-o[role="darkGrey"] = Legt den Filter als Standard fest.
======
