
Erstelle zunächst die Tags, die du verwenden möchtest.

[.instruction]
Tag erstellen:

. Öffne das Menü *Einrichtung » Einstellungen » Tags*.
. Klicke auf *Neues Tag erstellen* (icon:plus[role="green"]). +
→ Rechts wird ein Fenster geöffnet.
. Nimm die Einstellungen vor. +
*_Tipp:_* Klappe die Info-Box unten auf (icon:chevron-down[role="darkGrey"]), um mehr über die Einstellungen zu erfahren.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Das Tag wird erstellt und zur Liste hinzugefügt.

[.collapseBox]
.*Mehr über die Einstellungen*
--
[[table-tag-settings]]
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *ID*
| Die Tag-ID wird automatisch vergeben und ist nicht änderbar.
Sie dient zur eindeutigen Kennzeichnung deiner Tags.

*_Anwendungsfall_*: Tag-Verknüpfungen können importiert werden.
Während du also z.B. Artikel- und Variantendaten importierst, kannst du die passenden Tags auch direkt verknüpfen.
Dies geschieht z.B. durch Angabe der Tag-ID.

| *Name DE* +
[red]#(Pflichtfeld)#
| Gib einen Namen für das Tag ein.
Der Name ist das Schlagwort, das den Datensatz hervorhebt.

*_Tipp_*: Der Name darf Leerzeichen enthalten. Der Name kann also auch aus mehreren Wörtern bestehen.

| *Farbe*
a| Welche Hintergrundfarbe soll der Tag-Text haben?
Es gibt drei Möglichkeiten, die Farbe zu wählen:

* Gib die Farbe als Hexadezimalwert ein.
* Gib die englische Bezeichnung einer der 16 Grundfarben ein (black, red, silver, white etc.)
* Klicke auf das Quadrat rechts und klicke in das Farbspektrum.

|[#intable-bereich]*Bereich*
a| Welche Arten von Datensätzen wirst du mit diesem Tag verknüpfen?
Wähle alle zutreffenden Bereiche (icon:check-square[role="blue"]).

[cols="1,3"]
!===
! Bereich ! Anwendungsbeispiel

! *Board*
! Willst du bestimmte Aufgabenkarten auf Boards markieren? +
*_Beispiel:_* Gib an, dass manche Aufgaben eine hohe oder niedrige Priorität haben.

! *Kategorie*
! Willst du bestimmte Kategorien im Backend markieren? +
*_Beispiel:_* Gib an, dass eine Kategorie nur für saisonale Angebote verwendet werden soll.

*_Hinweis_*: Kategorie-Tags sind für Kund:innen im Webshop _nicht sichtbar_.

! *Ticket*
! Willst du bestimmte Tickets im Ticketsystem markieren? +
*_Beispiel:_* Gib an, dass sich das Ticket auf einen bestimmten Verkaufskanal bezieht, zum Beispiel Amazon oder eBay.

! *Kontakt*
! Willst du bestimmte Kontakte markieren? +
*_Beispiel:_* Gib die vom Kunden bevorzugte Kommunikationsmethode an.

! *Variante*
! Willst du bestimmte Varianten markieren? +
*_Beispiel:_* Wenn du z.B. Leitern verkaufst, kannst du angeben, dass einige Leitern TÜV-zertifiziert sind.

*_Hinweis_*: Varianten-Tags können für Kunden im Webshop _sichtbar_ gemacht werden.
<<#intable-mandant, Wähle dazu den entsprechenden Mandanten>> weiter unten.

! *Auftrag*
! Willst du bestimmte Nachbestellungen und Umbuchungen markieren? +
*_Beispiel_*: Gib an, welche Art von Waren umgebucht oder nachbestellt worden sind.

*_Hinweis_*: Tags können derzeit nur für Nachbestellungen und Umbuchungen genutzt werden. Für andere Auftragstypen sind Tags noch nicht nutzbar.

! *Nachrichten*
! Willst du bestimmte Nachrichten im Messenger markieren? +
*_Beispiel:_* Gib an, dass sich die Nachricht auf einen bestimmten Vertriebskanal bezieht, zum Beispiel Amazon oder eBay.

! *Nachrichten (kostenpflichtig)*
! Schreibst du manchmal kostenpflichtige Nachrichten im Messenger?
Sollen also die Minuten, die beim Schreiben der Nachricht verstrichen sind, in Rechnung gestellt werden?

Beim Schreiben einer kostenpflichtigen Nachricht musst du mindestens ein Tag dieses Bereichs wählen.
Sonst kann die Nachricht nicht erstellt werden.
!===

|[#intable-mandant]*Mandant* +
(ab plentyShop LTS 5.0 wirksam)
| In welchen plentyShops soll das Tag für Kund:innen sichtbar sein?
Wähle alle zutreffenden Webshops (icon:check-square[role="blue"]).

*_Hinweis_*: Diese Option wird nur angezeigt, wenn du oben <<#intable-bereich, den Bereich Variante gewählt>> hast.

| *Name EN* +
*Name FR* +
*Name IT* +
usw.
| Übersetze den Tag-Namen in weitere Sprachen.

*_Anwendungsbeispiel_*: Varianten-Tags können für Kund:innen im Webshop sichtbar gemacht werden.
Wenn dein Webshop in mehreren Sprachen verfügbar ist, sollten auch die Tag-Namen in diesen Sprachen erscheinen.
|====
--

[TIP]
.Tags können jederzeit bearbeitet werden
====
Verwende die Suche, um Tags zu finden.
Mit den optionalen Filtern grenzt du das Suchergebnis ein:

* *Name* = Gib den Namen des Tags in der Hauptsprache deines plentymarkets Systems ein.
* *Bereich* = Wähle einen oder mehrere Bereiche. In den Suchergebnissen werden nur die Tags angezeigt, die für diesen Bereich aktiviert wurden.
* *Sprache* = Wähle eine oder mehrere Sprachen. In den Suchergebnissen werden nur die Tags angezeigt, deren Name in dieser Sprache gespeichert ist.
====
