
Tags sind Texte, wie Keywords oder Phrasen.
Erstelle zunächst alle benötigten Tags.

. Öffne das Menü *Einrichtung » Einstellungen » Tags*.
. Klicke auf icon:plus[role="darkGrey"]. +
→ Ein Pop-Up Fenster wird geöffnet. Dieses Fenster ist in mehrere Schritte unterteilt.
. Nimm die Einstellungen in jedem Schritt vor.

[TIP]
.Tags können nicht per Import erstellt werden
====
Es ist nur möglich, Tags manuell zu erstellen, wie hier in der Anleitung beschrieben.
Es ist nicht möglich, Tags mit Hilfe des Import-Tools zu erstellen.
====

---

[discrete]
==== Schritt: Name

[cols="1,4a"]
|===
|Einstellung |Erläuterung

| *Name des Tags* +
[red]#(Pflichtfeld)#
|Gib einen Namen für das Tag ein.
Der Name ist das Keyword oder die Phrase, die den Datensatz hervorhebt.

*_Tipp_*: Der Name darf Leerzeichen enthalten. Der Name kann also auch aus mehreren Wörtern bestehen.

*_Hinweis_*:
Nachdem du das Tag erstellt hast, kannst du den Namen auch in weitere Sprachen übersetzen.

| *Farbe des Tags* +
[red]#(Pflichtfeld)#
|Welche Hintergrundfarbe soll der Tag-Text haben?
Klicke auf material:square[role="darkGrey"] und wähle die Farbe aus.

*_Wie wählt man eine Farbe_*?

* Gib die Farbwerte direkt ein. Klicke auf material:unfold_more[role="darkGrey"], um zwischen den Optionen zu wechseln:
** Gib die RGB-Werte für die Farbe ein.
** Gib die HSL-Werte für die Farbe ein.
** Gib die Farbe als Hexadezimalwert ein.
* Klicke in das Farbspektrum und nutze die Schieberegler.
* Klicke auf icon:eyedropper[role="darkGrey"] und wähle die Farbe von einer beliebigen Stelle deines Bildschirms.

|===

---

[discrete]
==== Schritt: Bereich

[cols="1,4a"]
|===
|Einstellung |Erläuterung

|[#intable-bereich]*Bereich* +
[red]#(Pflichtfeld)#
| Wofür möchtest du das Tag verwenden?
Das heißt, welche Arten von Datensätzen wirst du mit dem Tag verknüpfen?
Wähle alle zutreffenden Bereiche (icon:check-square[role="blue"]).

[cols="1,4"]
!===

! *Kategorie*
! Willst du bestimmte Kategorien im Backend markieren?

*_Beispiel:_* Gib an, dass eine Kategorie nur für saisonale Angebote verwendet werden soll.

*_Hinweis_*: Kategorie-Tags sind für Kunden im Webshop _nicht sichtbar_.

! *Ticket*
! Willst du bestimmte Tickets im Ticketsystem markieren?

*_Beispiel:_* Gib an, dass sich das Ticket auf einen bestimmten Verkaufskanal bezieht, zum Beispiel Amazon oder eBay.

! *Kontakt*
! Willst du bestimmte Kontakte markieren?

*_Beispiel:_* Gib die vom Kunden bevorzugte Kommunikationsmethode an.

! *Variante*
! Willst du bestimmte Varianten markieren?

*_Beispiel:_* Wenn du z.B. Leitern verkaufst, kannst du angeben, dass einige Leitern TÜV-zertifiziert sind.

*_Hinweis_*: Varianten-Tags können für Kunden im Webshop _sichtbar_ gemacht werden.
Nachdem du das Tag fertig erstellt hast, öffnest du die erweiterten Einstellungen und wählst den entsprechenden Mandanten aus.

! *Auftrag*
! Willst du bestimmte Nachbestellungen und Umbuchungen markieren?

*_Beispiel_*: Gib an, welche Art von Waren umgebucht oder nachbestellt worden sind.

*_Hinweis_*: Tags können derzeit nur für Nachbestellungen und Umbuchungen genutzt werden. Für andere Auftragstypen sind Tags noch nicht nutzbar.

! *Nachrichten*
! Willst du bestimmte Nachrichten im Messenger markieren?

*_Beispiel:_* Gib an, dass sich die Nachricht auf einen bestimmten Vertriebskanal bezieht, zum Beispiel Amazon oder eBay.

! *Nachrichten (kostenpflichtig)*
! Schreibst du manchmal kostenpflichtige Nachrichten im Messenger?
Sollen also die Minuten, die beim Schreiben der Nachricht verstrichen sind, in Rechnung gestellt werden?

Beim Schreiben einer kostenpflichtigen Nachricht musst du mindestens ein Tag dieses Bereichs wählen.
Sonst kann die Nachricht nicht erstellt werden.
!===

|===

---

[discrete]
==== Schritt: Fertig

[cols="1,4"]
|===
|Einstellung |Erläuterung

| *Zusammenfassung*
a|Hier siehst du eine Zusammenfassung deiner gewählten Einstellungen.
Klicke auf *Tag erstellen*, wenn du mit den Angaben einverstanden bist.

Nach der Erstellung hast du folgende Möglichkeiten:

[cols="1,4a"]
!===

! *Zum Tag*
!Das Pop-up-Fenster wird geschlossen und das neu erstellte Tag wird zur weiteren Bearbeitung geöffnet.

! *Weiteres Tag erstellen*
!Das Pop-up-Fenster wird für das nächste Tag neu gestartet.

! *Schliessen*
!Das Pop-up-Fenster wird geschlossen.

!===

|===

[.collapseBox]
.*Zum Tag: Welche erweiterte Einstellungen gibt es?*
--

[cols="1,3a"]
|===
|Einstellung |Erläuterung

| *ID*
| Die Tag-ID wird automatisch vergeben und ist nicht änderbar.
Sie dient zur eindeutigen Kennzeichnung deiner Tags.

*_Anwendungsfall_*: Tag-Verknüpfungen können importiert werden.
Während du also z.B. Artikel- und Variantendaten importierst, kannst du die passenden Tags auch direkt verknüpfen.
Dies geschieht z.B. durch Angabe der Tag-ID.

|[#intable-mandant]*Mandant* +
| In welchen plentyShops soll das Tag für Kunden sichtbar sein?
Wähle alle zutreffenden Webshops (icon:check-square[role="blue"]).

*_Hinweis_*: Diese Option wird nur angezeigt, wenn du die Verfügbarkeit <<#intable-bereich, Variante>> gewählt hast.

| *Name EN* +
*Name FR* +
*Name IT* +
usw.
|Ist dein plentyShop in mehreren Sprachen verfügbar?
Varianten-Tags können für Kunden im Webshop sichtbar gemacht werden.
Wenn dein Webshop in mehreren Sprachen verfügbar ist, sollten auch die Tag-Namen in diesen Sprachen erscheinen.

. Klicke auf icon:plus[role="darkGrey"] und wähle eine Sprachversion aus der Dropdown-Liste.
. Gib eine Übersetzung des Namens in dieser Sprache ein.

|===

--
