= FAQ
:keywords: Frequently asked questions, comparison, shipping centre 2.0
:description: Here you find answers to frequently asked questions.
:author: team-fulfillment-payment

On this page, you can find questions and answers about the Fulfilment area. We are continuously adding more questions and answers to this list.

[#faq-section-comparison-shipping-centre]
== Comparison: Shipping centre and Shipping centre 2.0

One of the objectives of developing a new version of the Shipping Centre was the adaptation to other new UIs in plentymarkets. The new Shipping Centre 2.0 also provides a variety of new and handy features:

* When registering an order, select an order status in case of successful registration and in case of a failed registration.
* Group function to reset orders
* Group function to download return labels
* Checkbox to automatically download the shipping labels when registering the orders
* A column with registered returns can be displayed in the overview
* New filters: Order date, Order type, Country
* Shipments can be tracked directly from the Shipping Centre, if the shipping provider enables this.
* You can see more and make more adaptations.
* You can save the selected filters so you do not have to select them again at your next visit.
* The width of table columns is now resizable so the tables provide a better overview.


A significant difference is that the new Shipping Centre is not using tabs anymore, but the features are available in icons which appear when you select one or more orders.

To assist you with the switchover from the old to the new Shipping Centre we would like to compare some of the most common use cases.

[#faq-registering-a-shipping-order]
[.collapseBox]
.Registering a shipping order (example: DHL)
--
[cols="1,1"]
|===
|_old_
|_new_

a|. Go to *Orders » Shipping centre*.
. Select the option *open* from the drop-down list *Shipping status*.
. Select the option *DHL* from the drop-down list *Shipping service provider*.
. Click on the magnifying glass.
→ You see a list of open shipping orders for DHL.
. Click on the *Register* tab.
. Select the option *DHL Shipping* from the drop-down list *Shipping service provider*.
. Select the order status from the drop-down list *Change order status*. 
. Select the status that you want the orders to receive after they are registered.
. Select the orders that you want to register with DHL Shipping.
. Click on *Register* to transfer the orders.

a|. Go to *Orders » Shipping centre 2.0*.
. Search for the order that you want to register by using the filter settings.
→ The orders that correspond to the search criteria entered are shown in the overview.
. Search for the order(s) that you would like to register.
. In the toolbar on the top, click on *Register order*.
→ The *Register order* window opens.
. Select the shipping service provider which you want to register the order with from the drop-down list.
. Select the order status from the drop-down list which the order should switch to after having it successfully registered with the shipping service provider.
. Select the order status from the drop-down list which the order should switch to when the registration with the shipping service provider failed.
. Click on *Register*.
→ The order is registered with the shipping service provider.
→ The registered order receives a package number in the *Packages* area.
|===
--
[#faq-resetting-a-shipping-order]
[.collapseBox]
.Resetting a shipping order
--
[cols="1,1"]
|===
|_old_
|_new_

a|. Go to *Orders » Shipping centre*.
. Search for the shipping order.
. Expand the shipping order.
. Click on the *Reset* tab.
. Click on *Reset shipping*.

a|. Go to *Orders » Shipping centre 2.0*.
. Search for the order that you want to reset by using the filter settings.
→ The orders that correspond to the search criteria entered are shown in the overview.
. Select the order(s).
. In the toolbar on the top, click on *Reset order*.
→ A window opens and you need to confirm your decision. 
. Confirm your decision by clicking on *Reset order*.
→ The order is reset.
|===
--
[#faq-cancelling-a-shipping-order]
[.collapseBox]
.Cancelling a shipping order
--
[cols="1,1"]
|===
|_old_
|_new_

a|. Go to *Orders » Shipping centre*.
. Search for the registered shipping order.
. Expand the registered shipping order.
. Click on the *Cancellation* tab.
. Click on *Cancel shipping*.
a|. Go to *Orders » Shipping centre 2.0*.
. Search for the order that you want to cancel by using the filter settings.
→ The orders that correspond to the search criteria entered are shown in the overview.
. Select the order(s).
. In the toolbar on the top, click on *Cancel order*.
→ A window opens and you need to confirm your decision. 
. Confirm your decision by clicking on *Reset order*.
→ The order is reset.
|===
--
[#faq-editing-data-on-shipping-orders]
[.collapseBox]
.Editing data on shipping orders
--
[cols="1,1"]
|===
|_old_
|_new_

a|. Expand the registered order in the *Orders » Shipping centre* menu.
. Click on one of the pencils in the *Shipping packages* tab to make the desired changes.
. Save the settings.
a|You can configure individual packages by clicking on the line of the package. A window opens for you to configure the values for package type, packing unit type, package weight, package volume and package number. Your settings are saved and applied to the package when you click on the button *Configure package*.
|===
--
[#faq-registering-a-return]
[.collapseBox]
.Registering a return
--
[cols="1,1"]
|===
|_old_
|_new_

a|In the *Orders » Shipping centre* menu in the *Return* tab, you can register returns with a shipping service provider. After you register a return, the return labels are available as PDF files. You can register a return via the main order or via the return.
a|. Go to *Orders » Shipping centre 2.0*.
Search for the order that you want to register a return for by using the filter settings.
→ The orders that correspond to the search criteria entered are shown in the overview.
. Select the order(s).
. In the toolbar on the top, click on *Register return*.
→ The *Register return* window opens.
. Select the return service provider from the drop-down list.
. Click on *Register return*.
→ The return for the order is registered and the package number is saved at the order.
|===
--
[#faq-creating-a-polling-file]
[.collapseBox]
.Creating a polling file
--
[cols="1,1"]
|===
|_old_
|_new_

a|. Go to *Orders » Shipping centre*.
. Select the search criteria for the order. 
. Activate the order.
. Click on the Polling tab.
. Select the shipping service provider.
. Select the order status that you want the orders to switch to.
. Activate all of the orders that you want to ship with the selected shipping service provider.
. Click on *Register* to generate the polling file.
→ The polling file is generated. Save this file on your computer.
a|. Go to *Orders » Shipping centre 2.0*.
. Search for the order by using the filter settings.
→ The orders that correspond to the search criteria entered are shown in the overview.
. Open the order.
. In the toolbar on the top, click on *Polling*.
. Select the service provider from the drop-down list.
. Select the order status that you want the order to switch to.
. Click on *Create polling file*.
→ The polling file is generated.
. Save the file to your computer and send it to the shipping service provider.

|===
--
