= DHL Retoure Online
:lang: en
include::{includedir}/_header.adoc[]
:keywords: DHL Retoure Online, DHL Retoure, DHL return, register returns, DHL return plugin, DHL return label
:description: Learn how to set up the “DHL Retoure Online” plugin in plentymarkets.
:position: 300
:url: fulfilment/shipping-service-provider-plugins/plugin-dhl-retoure-online
:id: QDSZAQP
:author: team-fulfillment

[IMPORTANT]
.Download the DHL Retoure Online plugin
====
You need a plugin to link plentymarkets to DHL Retoure Online. Visit the link:https://marketplace.plentymarkets.com/en/dhlretoureonline_6714[plentyMarketplace^]{nbsp}icon:external-link[] to download the DHL Retoure Online plugin.
====

[#register-with-dhl]
== Registering with DHL

DHL Retoure Online allows you to generate return labels for orders with various countries of delivery. You can generate the labels automatically with an event procedure or a process. As an alternative, you can generate and download the labels in the shipping centre. Afterwards, you can set up an event procedure that sends the labels as email attachment to your customers in an automated way.

To set up and use the interface for DHL Retoure Online in your plentymarkets system, you have to register with link:https://www.dhl.de/en/geschaeftskunden/paket/versandsoftware/dhl-geschaeftskundenportal-anmeldung.html[DHL^]{nbsp}icon:external-link[] and your account has to be activated for DHL Retoure. The new DHL Retoure Online interface is completely integrated in the DHL business customer portal. You receive the data from DHL that you need for the settings in plentymarkets.

[#set-up-dhl-retoure-online]
== Setting up DHL Retoure Online in plentymarkets

Once your account is activated for DHL Retoure and DHL sent you the appropriate data, you can start with the setup. To do so, proceed as described below.

[#preparatory-settings]
== Carrying out the preparatory settings

First, you have to carry out some preparatory settings in the plentymarkets back end:

[#set-up-warehouse]
=== Setting up a warehouse

You need to have a warehouse in order to save the information about returns that you receive from DHL. The warehouse is then selected in the assistant.

[TIP]
Each item is assigned to a warehouse. It is important that you select this warehouse also in the assistant. Otherwise, an error message occurs saying that there no connection exists between the warehouse and the country: `No settings found for the warehouse x and the country y`.

For further information about creating warehouses, refer to the <<stock-management/setting-up-a-warehouse#, Setting up a warehouse>> page of the manual.

[#activate-countries]
=== Activating countries of delivery

Activate the countries of delivery for which you want to offer return shipments.

The countries of delivery have to have the setting *Active* or *Backoffice is active*. You can activate countries of delivery in the *Setup » Orders » Shipping » Settings* menu in the *Countries of delivery* tab.

For further information, refer to the <<fulfilment/preparing-the-shipment#100, Preparing the shipment>> page.

[#complete-assistant]
== Completing the assistant

Once you have <<plugins/installing-added-plugins#installing-plugins, installed the plugin in a plugin set>>, the assistant is visible in the *Setup » Assistants » Plugins* menu in the relevant plugin set and you can start with the setup.

*_Important_:* You have to complete the assistant for each warehouse that you want to use for DHL Retoure Online.

[TIP]
If you have already used the “old” DHL Retoure Online integration in combination with processes, in event procedures or in the shipping centre, to-do lists are available in the assistant. Work through these lists to make sure that you can use the new interface smoothly and without any problems.

This assistant has several steps to complete. These steps are explained in the following.

[#new-configuration]
=== New configuration for DHL Retoure Online

Open the *DHL Retoure Online* assistant and add a new configuration for DHL Retoure Online by clicking on icon:plus-square[role="green"] and select an existing warehouse from the drop-down list.

[#login-details]
=== Login details

In this step, enter the login details of the user who is activated for returns in the DHL business customer portal.

Activate the button (icon:toggle_on[set=material, role=skyBlue]) if you want that the password will be changed for all warehouse configurations with the same user.

[#recipient-return]
=== Recipient of return

In this step, assign the recipients of return (receiver IDs) to the different countries of delivery. The countries of delivery that have the setting *Active* or *Backoffice is active* are shown here. You can activate missing countries of delivery in the *Setup » Orders » Shipping » Settings* menu in the *Countries of delivery* tab.

[TIP]
You can find the receiver IDs in the DHL business customer portal in the area *Returns > Settings > Recipient and country overview*.

In the *Referrer combination* area at the bottom of this step, you can add a new combination by clicking on  icon:plus-square[role="green"]. You can combine multiple referrers with a country and the receiver ID for each entry. To do so, select the desired referrers (icon:check-square[role="blue"]). Afterwards, select the country from the drop-down list and enter the receiver ID in the corresponding field. Add further combinations by clicking on icon:plus-square[role="green"].

[#validity-labels]
=== Validity of labels

In this step, determine how long the labels are available for download to your customers in your online shop. _Assigned_ labels are those that have already been assigned to a return.

[IMPORTANT]
The settings that you carry out in this step are global and apply to each warehouse in your plentymarkets system.

[#to-do-lists]
=== To-do list

If you have already used DHL Retoure Online and saved your data in the *Setup » Orders » Shipping service provider » DHL Retoure Online* menu, you have to carry out a few tasks to use the new interface.

In this step, select the areas in plentymarkets where you are using DHL Retoure Online. Select the areas by activating the buttons (icon:toggle_on[set=material, role=skyBlue]). Based on this selection, further steps are shown that explain your to-dos in detail.

[#to-do-event-procedures]
=== To-do event procedures

In this step, we describe the required changes that you have to carry out in the event procedures.

[#to-do-processes]
=== To-do processes

In this step, we describe the required changes that you have to carry out in the processes.

[#to-do-shipping-centre]
=== To-do shipping centre

In this step, we describe the required changes that you have to carry out in the shipping centre.

[#summary]
=== Summary

In this step, a summary of all entries that you made in the single steps is listed. You can check the settings, adjust them in the single steps, if needed, and complete the assistant afterwards.

[#completed-assistant]
[discrete]
=== Completed *DHL Retoure Online* assistant

[.collapseBox]
.Which data is shown when the *DHL Retoure Online* assistant has been completed?
--

When you completed the *DHL Retoure Online* assistant and open it again, the following information is displayed:

* In the tile view:

** Warehouse name
** User name


* In the table overview:

** Warehouse name
** User name

--


[#options-generate-return-labels]
== Generating return labels

You have the following options to generate return labels and register the return with DHL Retoure Online:

* *Generate DHL Retoure Online label* +
Registers the return with DHL Retoure Online. One label per order is generated, regardless of the number of packages.

* *Generate DHL Retoure Online label (1 label per package / 1 file)* +
Registers the return with DHL Retoure Online. One label per package is generated. If multiple packages are available, _one PDF file that contains all return labels_ is generated. +
*_Example:_* In a return order with 3 packages, one PDF is generated for each package that each contains _all 3_ return labels. +
icon:exclamation-triangle[role="red"] In this case, note that you have to print the PDF file with the return labels only once and not three times.

* *Generate DHL Retoure Online label (1 label per package / multiple files)* +
Registers the return with DHL Retoure Online. One label per package is generated. If multiple packages are available, one PDF file per return label is generated.

You can select the options mentioned above in the following areas of the plentymarkets back end:

* in the procedure group *Plugins* of the event procedures
* as *Return type* in the procedure *Return label* in the processes
* in the *Return* tab of the shipping centre

[discrete]
=== International returns

It is possible to generate DHL Retoure Online labels not only for returns from Germany, but also for returns from Switzerland. The CN23 form is added as PDF file when the return is registered.

Furthermore, you can generate DHL enclosed return labels for international returns in the processes and in the event procedures:

* In the processes, use the option *DHL Retoure enclosed label international*.
* In the event procedures, select the procedure *Generate DHL Retoure enclosed label international*.

[#e-mail-qr-code]
== Adding a mobile return code to the email template

Insert the template variable `$DHLRetoureOnlineQRCodeURL` in your email templates to send your customers a QR code within the email. If your customers want to send back an item, they have to show the QR code on their smartphone to one of the employees in the post office and they will print the return label and attach it to the parcel.

Thus, your customers do no longer need a printer at home and you do no longer have to send the return label attached as PDF.

Go to the *Setup » Client » [Select client] » Email » Templates* menu to create the email template. Note:

* In an email template of the type *Plain text*, the link to the QR code is displayed that your customer can click. To do so, insert the template variable `$DHLRetoureOnlineQRCodeURL` directly in the text.

* In an email template of the type *HTML-formatted text*, the QR code is displayed as an image. To do so, insert an image and enter the template variable `$DHLRetoureOnlineQRCodeURL` as an URL in the image properties in the tabs *Image info* and *Link*.

For further information about how to create email templates, refer to the <<crm/sending-emails#1200, Emails>> page.
