= DPD Shipping UK
:lang: en
include::{includedir}/_header.adoc[]
:keywords: DPD Shipping UK, DPD Shipping, DPD UK
:description: Learn how to set up the “DPD Shipping UK” plugin in plentymarkets.
:position: 500
:url: fulfilment/shipping-service-provider-plugins/plugin-dpd-shipping-uk
:id: 0PL7WV9
:author: team-fulfillment

[IMPORTANT]
.Download the DPD Shipping UK plugin
====
You need a plugin to link plentymarkets to DPD UK. Visit the link:https://marketplace.plentymarkets.com/en/plugins/integration/dpdshippinguk_5121[plentyMarketplace^]{nbsp}icon:external-link[] to download the DPD Shipping UK plugin.
====

[#register-with-dpd-uk]
== Registering with DPD UK

In order to set up the interface for DPD Shipping UK in your plentymarkets system and use the DPD services, you have to register with link:https://www.dpd.co.uk/content/products_services/uk_services.jsp[DPD UK^]{nbsp}icon:external-link[]. You receive the data from DPD UK that you need for the settings in plentymarkets.

[#set-up-dpd-shipping-uk]
== Setting up DPD Shipping UK in plentymarkets

[#preparatory-settings]
=== Carrying out the preparatory settings

First, you have to carry out some preparatory settings in the plentymarkets back end:

* set up <<fulfilment/preparing-the-shipment#100, countries of delivery>>
* create a <<fulfilment/preparing-the-shipment#400, region>>
* create the <<fulfilment/preparing-the-shipment#800, shipping service provider>> *DPD Shipping UK*
* create a <<fulfilment/preparing-the-shipment#1000, shipping profile>> and the <<fulfilment/preparing-the-shipment#1500, table of shipping charges>> for *DPD Shipping UK*

Afterwards, carry out shipping service provider-specific settings to set up the interface in the plentymarkets back end via the user interface of the plugin in the *Setup » Orders » Shipping » DPD Shipping UK* menu.

[#set-up-interface]
=== Setting up the interface

Once you have <<plugins/installing-added-plugins#installing-plugins, installed the plugin in a plugin set>>, the plugin is visible in the *Setup » Orders » Shipping* menu.

Proceed as described in the following sub-chapters to set up the interface in plentymarkets.

[#dpd-uk-basic-settings]
==== Carrying out the basic settings

In the *Basic settings* menu, enter your login details.

[.instruction]
Carrying out the basic settings:

. Go to *Setup » Orders » Shipping » DPD Shipping UK » Basic settings*.
. Select the product from the drop-down list.
. Enter the user name and the password that you received from DPD.
. *Save* (icon:save[role="green"]) the settings.

[#dpd-uk-shipper-information]
==== Entering shipper information

In the *Shipper information* menu, enter the shipper address as well as information related to the contact person.

[.instruction]
Entering shipper information:

. Go to *Setup » Orders » Shipping » DPD Shipping UK » Shipper information*.
. Click on *New address* (icon:plus-square[role="green"]).
. Carry out the settings. Note the explanations in <<#table-dpd-shipping-uk-shipper-information>>.
. *Save* (icon:save[role="green"]) the settings.

[[table-dpd-shipping-uk-shipper-information]]
.Entering shipper information for DPD Shipping UK
[cols="1,3"]
|====
|Setting |Explanation

2+| *Company*

| *Name*
|Enter the company name.

2+| *Shipper address*

| *Street*, *House number*, *Postcode*, *Town*
|Enter the data of the shipper.

| *Country*
|Select the country from the drop-down list.

2+| *Contact person*

| *Name*, *Email address*, *Telephone number*
|Enter the data of the contact person that should be contacted by DPD in case of questions.

|====

[#dpd-uk-shipping-settings]
==== Carrying out shipping settings

In the *Shipping settings* menu, you link the shipping profile, the shipping region, the shipper address and the DPD services.

[.instruction]
Carrying out the shipping settings:

. Go to *Setup » Orders » Shipping » DPD Shipping UK » Shipping settings*.
. Click on *Add shipping setting* (icon:plus-square[role="green"]).
. Carry out the settings. Note the explanations in <<#table-dpd-shipping-uk-shipping-settings>>.
. *Save* (icon:save[role="green"]) the settings.

[[table-dpd-shipping-uk-shipping-settings]]
.Carrying out shipping settings for DPD Shipping UK
[cols="1,3"]
|====
|Setting |Explanation

| *Login details*
|Select the login details from the drop-down list.

| *Shipping service provider*
| Select *DPD Shipping UK* from the drop-down list.

| *Shipping profile*
|Select the shipping profile from the drop-down list.

| *Shipping region*
|Select the shipping region from the drop-down list.

| *Shipper address*
|Select the sender from the drop-down list.

| *Shipping services*
|Select the shipping service from the drop-down list. The services may vary depending on your DPD contract.

|====

[#dpd-uk-user-rights]
=== Assigning rights for back end users

In order to use the DPD Shipping UK plugin, an *Admin* user has to activate some rights for users with *Back end* access in their user account.

[.instruction]
Assigning rights for back end users:

. Go to *Setup » Settings » User » Rights » User*.
. Use the search function (icon:search[role="blue"]) and open the account that should be edited.
. In the *Authorisations* area, activate the rights as listed in <<#table-user-rights-back-end-user>>.
. *Save* (icon:save[role="green"]) the settings.

[[table-user-rights-back-end-user]]
.Assigning rights for back end users
[cols="1,3"]
|====
|Setting |Explanation

| *DPDShippingUK > Basic settings*
|Authorises back end users to edit the basic settings.

| *DPDShippingUK > Addresses*
|Authorises back end users to edit addresses.

| *DPDShippingUK > Shipping settings*
|Authorises back end users to edit the shipping settings.

|====
