= Using the shipping centre
:lang: en
include::{includedir}/_header.adoc[]
:keywords: shipping centre, registering shipping order, polling file, shipping package, label, order summary, return label, register order, cancel order, reset order
:description: Learn how to register shipping orders and how to generate polling files and labels.
:position: 20
:url: fulfilment/shipping-centre
:id: YX8GNS9
:author: team-fulfillment

In the *Orders » Shipping centre* menu, you can use the integrated interfaces to control all of the processes that are related to shipping your items. You cannot only search for and edit shipping orders but also <<fulfilment/shipping-centre#register-shipping-order, register shipping orders>> directly with a shipping service provider or alternatively create a <<fulfilment/shipping-centre#generate-polling-file, polling file>> to hand over to a shipping service provider. The appropriate action depends on the shipping service provider and the software used by these providers.

On this page of the manual, you also learn how to generate an <<fulfilment/shipping-centre#generate-order-summary, order summary>> of the <<fulfilment/preparing-the-shipment#2500, shipping service providers>> set up in plentymarkets. Furthermore, it is also described how to <<fulfilment/shipping-centre#retrieve-return-label, register returns>> and <<fulfilment/shipping-centre#generate-label, generate labels>>.

[#search-shipping-order]
== Searching for a shipping order

The *Search* tab is automatically displayed when you open the shipping centre. Various search filters are available to help you search shipping orders.

[.instruction]
Searching for a shipping order:

. Go to *Orders » Shipping centre*.
. Select filters. Note the explanations in <<#table-search-shipping-order>>.
. Click on Search (icon:search[role="blue"]) to carry out the search. +
→ The results are listed depending on the selected filters.

[[table-search-shipping-order]]
.Filter options for searching in the shipping centre
[cols="1,3"]
|====
|Setting |Explanation

| *Order ID*
|Enter an order ID to search for shipping orders with this ID. Separate multiple IDs using commas.

| *Customer ID*
|Enter the customer ID to search for shipping orders with this customer ID.

| *Shipping status*
|Select a shipping status to search for shipping orders with this status only.

| *Shipping service provider*
|Select a shipping service provider to search for shipping orders of this shipping service provider only.

| *Shipping profile*
|Select a shipping profile to search for shipping orders with this profile only.

| *per page*
|Select how many shipping orders should be displayed per page.

| *Order status*
|Select an order status to search for orders with this status only. +

| *Owner*
|Select an owner to search for orders that this owner is responsible for only.

| *Client (store)*
|Select a client (store) to search for shipping orders of this store only.

| *Warehouse*
|Select a warehouse to search for shipping orders for this warehouse only.

| *Payment method*
|Select a payment method to search for shipping orders that were paid using this payment method only.
|====

Once you have found the shipping orders you are looking for, you can edit these shipping orders or register them with the shipping service provider. Proceed as follows to edit shipping orders. Refer to the chapters <<fulfilment/shipping-centre#register-shipping-order, Registering a shipping order>> and <<fulfilment/shipping-centre#generate-polling-file, Generating a polling file>> on this page of the manual to learn how to register shipping orders.

[#shipping-package-pending-shipping-order]
== Editing a shipping package in a pending shipping order

It is possible to edit shipping packages in a pending shipping order. You can also add shipping packages to or delete them from a pending shipping order. You can change the <<crm/managing-contacts#300, customer data of the recipient>> in the *CRM » Contacts* menu. Open the contact data record by clicking on the contact ID in the shipping order.

[TIP]
.Return labels in a shipping order
====
In the *Return tab* of a shipping order, return labels are displayed. You can also link orders of the type Return to the registered returns. A return is usually only created after the item was shipped. Therefore, the tab of any pending orders that are not yet registered is empty.
====

[#edit-shipping-package]
=== Editing a shipping package

Proceed as described below to edit a shipping package. The parameters such as weight and volume are calculated based on the item data. Therefore, check the shipping package information and correct it if necessary.

[.instruction]
Editing a shipping package:

. Go to *Orders » Shipping centre*.
. Select the search criteria. Pay attention to the information given in the <<fulfilment/shipping-centre#search-shipping-order, Searching for a shipping order>> chapter.
. Click on the magnifying glass (icon:search[role="blue"]). +
→ The shipping orders that match the search criteria you selected are displayed.
. Expand the shipping order (icon:plus-square-o[]).
. In the *Shipping packages* tab, click on the pencil (icon:pencil[role="yellow"]) to edit the shipping order.
. Carry out the desired settings. Note <<#table-edit-shipping-package>>.
. *Save* (icon:save[role="green"]) the settings.

[[table-edit-shipping-package]]
.Editing a shipping package
[cols="1,3"]
|====
|Setting |Explanation

| *Shipping package*
|Select a shipping package to assign a package size to the shipping order. +
If you have not yet configured shipping packages in the *Orders » Shipping » Shipping packages* menu, standard packages are assigned to the shipping order. +
*_Important:_* The number of shipping packages entered in the *Orders » Edit orders* » _Open order_ menu in the *Settings* tab does not influence the packages saved here, i.e. changes you make in that menu are not updated here. This is why you should change the number of packages in the shipping centre only.

| *Weight*
|Enter the weight of the shipping package. +
If a weight was saved for the item, this weight is carried over to the shipping order. If no weight was saved for the item, a weight of 100 g is entered automatically as standard. If the item consists of more than one packing unit, the weight is distributed between the number of packages it consists of.

| *Packing unit type*
|Select or edit the packing unit type. +
If a packing unit type was saved for the item, this is displayed here.

| *Volume*
|Enter or edit the volume. +
If the length, width and height was saved for the item, the volume is calculated automatically based on these values.
|====

[#add-shipping-package]
=== Adding a shipping package

Proceed as described below to add a shipping package.

[.instruction]
Adding a shipping package:

. Go to *Orders » Shipping centre*.
. Select the search criteria. Pay attention to the information given in the <<fulfilment/shipping-centre#search-shipping-order, Searching for a shipping order>> chapter.
. Click on the magnifying glass (icon:search[role="blue"]). +
→ The shipping orders that match the search criteria you selected are displayed.
. Expand the shipping order (icon:plus-square-o[]).
. Click on the *Add* tab.
. Carry out the desired settings. Note <<#table-edit-shipping-package>>.
. *Save* (icon:save[role="green"]) the settings. +
→ The shipping package is added and the *Shipping package* tab opens.

[#delete-shipping-package]
=== Deleting a shipping package

Proceed as described below to create a shipping package.

[.instruction]
Deleting a shipping package:

. Go to *Orders » Shipping centre*.
. Select the search criteria. Pay attention to the information given in the <<fulfilment/shipping-centre#search-shipping-order, Searching for a shipping order>> chapter.
. Click on the magnifying glass (icon:search[role="blue"]). +
→ The shipping orders that match the search criteria you selected are displayed.
. Expand the shipping order (icon:plus-square-o[]).
. In the *Shipping packages* tab, click on *Delete* (icon:minus-square[role="red"]). +
→ The shipping package is deleted.
. *Save* (icon:save[role="green"]) the settings.

[#orders-delivery-orders]
== Splitting up orders into delivery orders

Here you can define which criteria is used to split orders into delivery orders. *Warehouse*, *shipping profile*, *warehouse and shipping profile*, or *stock and net stock* can be selected.

For further information, refer to the <<orders#, Orders>> area.

[#register-shipping-order]
== Registering a shipping order

In the *Orders » Shipping centre* menu in the *Register* tab, you can register your orders with a shipping service provider and simultaneously transmit the orders to the service provider. You have to <<fulfilment/shipping-centre#search-shipping-order, search for orders>> in the *Search* tab before you can register them. The orders that were found are displayed here. You can use the search function's filter settings in the shipping centre to display orders for a specific shipping service provider or for all shipping service providers. During the registration process, you receive messages from the shipping service provider informing you of both success and errors.

[IMPORTANT]
.Transferring shipment numbers to Hermes ProfiPaketService
====
If you register shipping orders at Hermes ProfiPaketService and wish to transfer the shipment numbers, you have to activate the option *Request labels*.
====

The following information gives an example of registering orders with the shipping service provider *DHL Freight*.

[.instruction]
Registering a shipping order at DHL Freight:

. Go to *Orders » Shipping centre*.
. Select the option *open* from the drop-down list *Shipping status*.
. Select the option *DHL* from the drop-down list *Shipping service provider*.
. Click on the magnifying glass (icon:search[role="blue"]). +
→ You see a list of open shipping orders for DHL.
. Click on the *Register* tab.
. Select the option *DHL Freight* from the drop-down list *Shipping service provider*.
. Select the order status from the drop-down list *Change order status*. Select the status that you want the orders to receive after they are registered.  +
→ You can combine this function using an <<automation/event-procedures#, event procedure>> which, for example, automatically books outgoing items.
. Select the orders that you want to register with DHL Freight.
. Click on *Register* to transfer the orders.

Choosing the option *Select all* selects all of the orders on the current page.

[TIP]
.Some shipping service providers have additional options
====
Depending on which service provider was selected, additional options are displayed on the right side in the *Register* tab. Most of the shipping service providers do not offer additional services, meaning that the right side usually remains blank. The additional options allow you to change the shipping profile for selected orders after they have been registered. They also allow you to change the shipping date so it is predated or postdated.
====

Also note the chapter <<fulfilment/shipping-centre#errors-register-shipping-order, Possible errors when registering a shipping order>> on this page of the manual.

[#edit-registered-shipping-order]
== Editing a registered shipping order

Once you have registered a shipping order with a shipping service provider, this shipping service provider is displayed behind the *registered* status, e.g. *registered DHL Shipping (Versenden)*.

Registered shipping orders receive a package number and usually also a transaction number from the shipping service provider. Furthermore, they include a file that contains the shipping label for printing. The shipping costs are also displayed if the shipping service provider supports this function. The tabs that are displayed depend on the shipping service provider, e.g. the tabs *Cancellation* and *Reset* for DHL Shipping (Versenden). Different or additional tabs might be available for other shipping service providers.

[WARNING]
.Cancelling a shipping order vs. Resetting a shipping order
====
If you cancel a shipping order, the registration is cancelled in plentymarkets and with the shipping service provider. This means that the order is not collected.

If you reset an order, it is available as a pending order in plentymarkets. However, it is still registered with the shipping service provider and you are billed for it. The *Reset* function simply resets the registrations. The shipping order itself is not cancelled with the service provider. Therefore, we recommend that you always cancel the order.
====

[#display-registered-order]
=== Displaying a registered order

In the following, it is described how to display registered orders that were registered with a certain shipping service provider.

[.instruction]
Displaying a registered order:

. Go to *Orders » Shipping centre*.
. Select the option *registered* _(Name of the shipping service provider)_ from the drop-down list *Shipping status*.
. Click on the magnifying glass (icon:search[role="blue"]). +
→ The orders that were registered with this shipping service provider are displayed.

[#edit-package-number]
=== Editing the package number

This section teaches you how to edit the package number once you have found the order that was registered.

[.instruction]
Editing the package number:

. Expand the registered order in the *Orders » Shipping centre* menu (icon:plus-square-o[]). +
→ *_Note:_* How to display the registered order is described in the <<fulfilment/shipping-centre#display-registered-order, Displaying a registered order>> chapter.
. Click on the pencil in the *Shipping packages* tab (icon:pencil[role="yellow"]. +
→ The package number opens.
. Enter a different package number.
. *Save* (icon:save[role="green"]) the settings.

For further information about importing package numbers, refer to the <<fulfilment/generating-documents#import-package-numbers, Importing package numbers>> chapter on the <<fulfilment/generating-documents#, Generating documents>> page of the manual.

[#cancel-shipping-order]
=== Cancelling a shipping order

Cancel the shipping order if something about the shipment is incorrect or has been changed, e.g. if items were added or removed. Afterwards, the order can be re-registered for shipping.

[.instruction]
Cancelling a shipping order:

. Go to *Orders » Shipping centre*.
. Search for the registered shipping order (icon:search[role="blue"]).
. Expand the registered shipping order (icon:plus-square-o[]).
. Click on the *Cancellation* tab.
. Click on *Cancel shipping*.

[#reset-shipping-order]
=== Resetting a shipping order

The *Reset* function simply resets the registration. The shipping order itself is not cancelled with the service provider. This is why we recommend cancelling the order as described in the <<fulfilment/shipping-centre#cancel-shipping-order, Cancelling a shipping order>> chapter.

[.instruction]
Resetting a shipping order:

. Go to *Orders » Shipping centre*.
. Search for the shipping order (icon:search[role="blue"]).
. Expand the shipping order (icon:plus-square-o[]).
. Click on the *Reset* tab.
. Click on *Reset shipping*.

[#print-shipping-label]
=== Printing the shipping label

A shipping label is available in the *Orders » Shipping centre* menu in the registered shipping order. Alternatively, the <<fulfilment/shipping-centre#generate-label, Label tab>> in the shipping centre allows you to generate and print one PDF file that contains labels for all of the shipping orders registered with a certain service provider.

[.instruction]
Printing the shipping label in the shipping order:

. Go to *Orders » Shipping centre*.
. Select the search criteria. Pay attention to the information given in the <<fulfilment/shipping-centre#search-shipping-order, Searching for a shipping order>> chapter.
. Click on the magnifying glass (icon:search[role="blue"]).
. Expand the registered shipping order (icon:plus-square-o[]).
. Click on the PDF symbol in the *Overview* tab. +
→ The shipping label opens in a separate window and can be printed.

[#generate-polling-file]
== Generating a polling file

In the *Orders » Shipping centre* menu in the *Polling* tab, you can generate a polling file containing the selected orders. This file is generated for the software that is used by a shipping service provider. A polling file is necessary if no direct interface to the shipping service provider's software exists, i.e. if shipping orders cannot be registered in the *Register* tab. The polling file generated in plentymarkets is usually a CSV file.

[.instruction]
Generating a polling file:

. Go to *Orders » Shipping centre*.
. Select the search criteria for the order. Pay attention to the information given in the <<fulfilment/shipping-centre#search-shipping-order, Searching for a shipping order>> chapter.
. Activate the order.
. Click on the *Polling* tab.
. Select the *shipping service provider*.
. Select the *order status* that you want the orders to switch to.
. Activate all of the orders that you want to ship with the selected shipping service provider.
. Click on *Register* (icon:cog[]) to generate the polling file. +
→ The polling file is generated. Save this file on your computer.

[IMPORTANT]
.DHL Easylog header
====
You also see the option *Header* if you selected the shipping service provider *DHL Easylog*. Use this option to choose whether the header should be displayed in the CSV file. For further information, refer to the <<fulfilment/preparing-the-shipment#2700, DHL Easylog>> chapter on the <<fulfilment/preparing-the-shipment#, Preparing the shipment>> page of the manual.
====

[#generate-order-summary]
== Generating an order summary

In the *Orders » Shipping centre* menu in the *Summary* tab, you can generate an order summary or a manifest for the shipping service providers that are set up in your plentymarkets system.

[.instruction]
Generating an order summary:

. Go to *Orders » Shipping centre*.
. Click on the *Summary* tab.
. Select the shipping service provider for the summary from the drop-down list. +
→ *_Note:_* Additional options for the shipping service provider are displayed, if available.
. Carry out the desired settings for the options.
. Click on *Execute* (icon:cog[]). +
→ A PDF file is generated.

[TIP]
.Using the elastic export to export order summaries
====
As an alternative to the order summary of one day in the *Orders » Shipping centre* menu in the *Summary* tab, you can also carry out an <<data/exporting-data/elastic-export#, elastic export>>. To do so, create an export format with the <<data/exporting-data/FormatDesigner#, FormatDesigner>>.
====

[#retrieve-return-label]
== Retrieving a return label

In the *Orders » Shipping centre* menu in the *Return* tab, you can register returns with a shipping service provider. After you registered a return, the return labels are available as PDF files. You can register a return via the main order or via the return.

To retrieve return labels, you register the return with a shipping service provider in the shipping centre.

[#retrieve-return-label-main-order]
=== Retrieving a return label via the main order

Proceed as described below to retrieve a return label in the main order. The process for assigning *returns* varies depending on whether you have already created a return for the order in the *Orders* menu. First retrieve the label and then assign it to the order of the type *Return*.

[.instruction]
Retrieving a return label via the main order:

. Go to *Orders » Shipping centre*.
. Select the search criteria for the order. Pay attention to the information given in the <<fulfilment/shipping-centre#search-shipping-order, Searching for a shipping order>> chapter.
. Click on the magnifying glass (icon:search[role="blue"]).
. Click on the *Return* tab.
. Activate the order.
. Select the *Return service provider*.
. Click on *Register* (icon:cog[]) to transfer the orders. +
→ Click on the PDF icon to view the label as a PDF file.

If you have already created a return order in the *Orders* menu, you can now assign this return to the label. This is done by selecting the *Return ID*.

If you have not created a return order in the *Orders* menu, do so now by opening the main order and creating a return. When creating an order of the type *Return* at this point, the return order is automatically assigned to the return label in the shipping order.

[#retrieve-return-label-via-return]
=== Retrieving a return label via the return

If you have already created a return order in the *Orders* menu, you can also retrieve the return label directly via this return order. You need the return ID to do so. Returns can only be found in the shipping centre by specifying the return ID.

[.instruction]
Retrieving a return label via the return:

. Go to *Orders » Shipping centre*. +
. Enter the return ID into the *Order ID* field.
. Click on the magnifying glass (icon:search[role="blue"]).
. Click on the *Return* tab.
. Activate the return.
. Select the *Return service provider*.
. Click on *Register* (icon:cog[]).
. Expand the shipping order (icon:plus-square-o[]). +
→ In the *Return labels* tab, click on the PDF icon to view the label as a PDF file.

You can provide the labels to end customers for download in the My account area of the online shop. For further information, refer to the <<fulfilment/preparing-the-shipment#, Preparing the shipment>> page of the manual. Specifically, refer to the <<fulfilment/preparing-the-shipment#3200, DHL Retoure Online>> chapter.

The returns that you register here in the *Return* tab of the shipping centre and then receive the return label for are orders that the customer has already received. For <<fulfilment/preparing-the-shipment#3100, DHL Retoure with enclosed return label>>, you already enclose return labels in packages before sending them to customers. These enclosed return labels are also displayed in the *Return labels* tab of the shipping order.

[TIP]
.Send return labels of all available shipping service providers as email attachment via an event procedure
====
With the setting *Return label* in the drop-down list *PDF attachment* in the email template, the return labels of all shipping service providers available in plentymarkets - be it via a plugin or an integration in the back end- can be sent as email attachment. If you link the email template with this setting to an event procedure, the email template will be automatically sent once the event happens.
====

[#generate-label]
== Generating a label

In the *Orders » Shipping centre* menu in the *Label* tab, you can generate address labels for your shipping orders based on the shipping service provider. These labels are made available as download files in PDF format. A PDF file is generated for each shipping service provider.

[.instruction]
Generating labels:

. Go to *Orders » Shipping centre*.
. By selecting filters, search for the orders that you want to create a collection PDF of the labels for.
. Activate the orders.
. Click on the *Label* tab.
. Click on *Generate* (icon:cog[]). +
→ The labels are shown as PDF files and can be downloaded and printed.

[#errors-register-shipping-order]
== Possible errors when registering a shipping order

In this section, we describe possible errors that may result in data not being transferred to the shipping service provider. An error message is displayed if an order cannot be registered.

Refer to the menu *Data » Log* when searching for errors. Entries are saved in this menu for 4 weeks. For further information, refer to the <<data/datalog#, Data log>> page.

[#character-set]
=== Character set

Some shipping interfaces (APIs) only allow Latin character sets (ISO-8859-X), but no Unicode. Therefore, delivery addresses should not contain Unicode signs. For example, you cannot register orders with DHL if the address was saved in Greek letters.

[#additional-address-information]
=== Additional address information

Some shipping service providers do not process *additional address information* saved with the delivery address. Therefore, shipping service providers might in some rare cases be unable to deliver packages. +
Additional address information is not transmitted to the following shipping service providers at the moment:

* DHL Freight
* DHL Supply Chain
* Swiss Post

Check if the additional address information is transmitted to your shipping service provider correctly. If the additional address information is not transmitted, adjust your online shop design in such way that the field for entering additional address information is shown or hidden depending on the shipping service provider selected. Alternatively, you can adjust your design so a note is displayed to customers.

[#shipping-profile]
=== Shipping profile

Error message: `Code 1: The process could not be carried out correctly. Check data entered. Invalid parameter value passed: DHLFreightDataSet_ShippingInformation.`

*Solution*: The shipping profile was not correctly set up or a shipping service provider was selected that does not fit to the shipping profile.

////
[#shipping-packages]
=== Shipping packages

It is not possible to add packages in the <<orders/managing-orders#1540, Settings>> tab. If you want to add further packages to an order or change the quantity, open the order in the shipping centre and make the changes in the <<fulfilment/shipping-centre#add-shipping-package, Add>> tab.
////
