= Zalando Fulfillment Solutions
:keywords: ZFS, Zalando Fulfillment Solutions
:description: Learn more about ZFS.
:author: team-fulfillment-payment

On this page, you find an overview of Zalando Fulfillment Solutions as well as the most important links that you need to set up ZFS.

== What is ZFS?

ZFS stands for Zalando Fulfillment Solutions and provides sellers with the option to use Zalando's logistics network for items that are sold via Zalando: You send your items to Zalando and Zalando takes care of their storage and of shipping them to your customers.

== How can I use ZFS?

You can use ZFS if you have a contract with Zalando for Zalando Fulfillment Solutions. +
Perform the relevant settings in the Zalando assistant:

1. Go to *Setup » Assistants » Omni-Channel*.

2. Click on the assistant *Account settings - Zalando*.

3. Follow the instructions on the screen.. 

4. In the step *Summary*, check your settings to make sure they are correct. +
_Important:_ You have not completed the setup. Therefore, in the step *Account activation*, do not activate the Zalando account yet.

5. If everything looks good, click *Finalise*.
→ The settings are saved. +
_Tip:_ You can run through the assistant again at any time to update settings.

6. Activate the toggle button to use Zalando Fulfillment Solutions.

7. Now assign plentymarkets warehouses to the different Zalando locations (countries). + 
There is a Zalando Fulfillment warehouse your items can be stored in each country that you can select here. Assign plentymarkets warehouses to these Zalando warehouses. This provides an overview of the Zalando locations your items are stored in. The stock from the Zalando locations is transferred to your plentymarkets warehouses.

You can find more information about Zalando and ZFS xref:markets:zalando.adoc[here].