= Zalando Fulfillment Solutions
:keywords: ZFS, Zalando Fulfillment Solutions
:description: Learn more about ZFS.
:author: team-fulfillment-payment

On this page, you find an overview of Zalando Fulfillment Solutions as well as the most important links that you need to set up ZFS.

== What is ZFS?

ZFS stands for Zalando Fulfillment Solutions and provides sellers with the option to use Zalando's logistics network for items that are sold via Zalando: You send your items to Zalando and Zalando takes care of their storage and of shipping them to your customers.

== How can I use ZFS?

You can use ZFS if you have a contract with Zalando for Zalando Fulfillment Solutions and have set up Zalando in plentymarkets. +

_You can find more information about Zalando and ZFS xref:markets:zalando.adoc[here]._

1. Activate the toggle button to use Zalando Fulfillment Solutions.

2. Now assign plentymarkets warehouses to the different Zalando locations (countries). + 
There is a Zalando Fulfillment warehouse your items can be stored in each country that you can select here. Assign plentymarkets warehouses to these Zalando warehouses. This provides an overview of the Zalando locations your items are stored in. The stock from the Zalando locations is transferred to your plentymarkets warehouses.

[IMPORTANT]
To show Zalando ZFS stock in plentymarkets, you need one or more repair warehouses.

[TIP]
Create new warehouses for Zalando Fulfilment Solutions. You can either specify a default warehouse only or a default warehouse and additional warehouses for each Zalando channel.

*Possibility 1:* _Only specify a default warehouse_

1. For the setting *Default warehouse for Zalando ZFS*, select a plentymarkets repair warehouse from the drop-down list. +
→ Stock data for all Zalando ZFS warehouses are imported to this repair warehouse.

[IMPORTANT]
If you do not assign any other warehouses, the stock data from all Zalando locations will be imported to this warehouse.

*Possibility 2:* _Specify a default warehouse and additional warehouses for each Zalando channel_

1. For the setting *Default warehouse for Zalando ZFS*, select a plentymarkets repair warehouse.
2. At the bottom right, click on (material:add[]) to assign further warehouses.
3. From the *Zalando* drop-down list, select a country.
4. From the drop-down list *plentymarkets warehouses*, select a repair warehouse. +
→ Stock data from this country are imported to the selected warehouse.
[TIP]
You can only assign one plentymarkets warehouse to each Zalando location.

5. If necessary, click on (material:add[]) at the bottom right again to map additional warehouses. +
→ Stock data for Zalando locations that are not mapped to a plentymarkets warehouse are imported to the default warehouse.

_Example:_ Create a warehouse *Zalando Germany*. To this warehouse, map the Zalando location *Deutschland*. This allows you to check the stock that Zalando holds for you in Germany at any time.
