= ItemCrossSelling
:lang: en
include::{includedir}/_header.adoc[]
:position: 10140

The data format **ItemCrossSelling** is used to export, edit and import <<item/managing-items#950, cross-selling items>>. Create and export the data format in the **Data » Dynamic export** menu. Import the data format in the **Data » Dynamic import** menu. The <<data/export-import/exporting-data#, Exporting data>> and <<data/export-import/importing-data#, Importing data>> pages of the manual describe how you export and import the data format.

Pay close attention to the exact spelling of the data fields. The data cannot be processed if the data fields are spelled incorrectly.

== Overview of the data fields

Table 1 explains the data fields for the **ItemCrossSelling** data format in alphabetical order as well as filter options that you set in the **Filter** tab of the data format.

.Data fields of the data format **ItemCrossSelling**
[cols="1,3,3"]
|====
|Field name |Explanation |Filter

| **CrossItemID**
|Item ID of the cross-selling item
|

| **CrossPrimaryVariationCustomNumber**
|Number of the main variation of the cross-selling item
|

| **CrossSellingDelete**
|Delete cross-selling item +
**0** = No +
**1** = Yes
|

| **ItemID**
|Item ID
|

| **PrimaryVariationCustomNumber**
|Number of the main variation
|

| **Relationship**
|Relationship between item and its corresponding cross-selling item. +
**Accessory** = accessories +
**ReplacementPart** = replacement part +
**Similar** = similar item +
**Bundle** = item bundle
|Activate the filter and select the operator and a value from the drop-down list.
|====

== Overview of the mandatory fields

One of the following mandatory fields must be available for the data format **ItemCrossSelling** and needs to have a valid value saved for it:

* **ItemID** or **PrimaryVariationCustomNumber**
* **CrossItemID** or **CrossPrimaryVariationCustomNumber**

== Overview of the synchronisation fields

The data fields that are listed in table 2 are available for <<data/export-import/importing-data#25, data synchronisation>>. For mandatory synchronisation fields (M), select the option **Synchronisation** as **Import procedure**.

.Data fields with the import procedure set to **Synchronisation**
[cols="1,3,3"]
|====
|Field name |Explanation |Synchronisation field

| **CrossItemID**
|Item ID of the cross-selling item
|M

| **CrossPrimaryVariationCustomNumber**
|Number of the main variation of the cross-selling item
|Alternative to **CrossItemID**

| **ItemID**
|Item ID
|M

| **PrimaryVariationCustomNumber**
|Number of the main variation
|Alternative to **ItemID**
|====
