= ItemProperties
:lang: en
include::{includedir}/_header.adoc[]
:position: 10175

The data format **ItemProperties** is used for editing item characteristic links via data exchange. You can use it to import, edit and/or export item characteristic links. Create and export the data format in the **Data » Dynamic export** menu. Import the data format in the **Data » Dynamic import** menu. The <<data/export-import/exporting-data#, Exporting data>> and <<data/export-import/importing-data#, Importing data>> pages of the manual describe how you export and import the data format.

Pay close attention to the exact spelling of the data fields. The data cannot be processed if the data fields are spelled incorrectly.

== Overview of the data fields

Table 1 explains the data fields for the **ItemProperties** data format in alphabetical order as well as filter options that you set in the **Filter** tab of the data format.

.Data fields of the data format **ItemProperties**
[cols="1,3,3"]
|====
|Field name |Explanation |Filter

| **DeleteProperty**
|Delete characteristic +
**1** = delete +
**0** = do not delete
|

| **ItemID**
|Item ID
|Activate the filter, select the operator and enter the value.

| **ItemMarking1**
|Flag 1 of the item
|Activate the filter and select the operator and the flag.

| **ItemMarking2**
|Flag 2 of the item
|Activate the filter and select the operator and the flag.

| **PrimaryVariationCustomNumber**
|Number of the main variation
|

| **Lang**
|Language +
de / en / fr / it / es / tr / nl / pl / nn / da / se / cz / ru (German, English, French, Italian, Spanish, Turkish, Dutch, Polish, Norwegian (Nynorsk), Danish, Swedish, Czech, Russian).
|

| **PropertyItemID**
|ID of the characteristic
|

| **Value**
|The unit's value
|
|====

== Overview of the mandatory fields

The following mandatory fields must be available for the data format **ItemPrice** and need to have a valid value saved for them:

* **ItemID** or alternatively **PrimaryVariationCustomNumber**
* If the data import contains text, the data fields **Lang** and **Value** are mandatory fields.
