= VariationMarketIdentNumber
:lang: en
include::{includedir}/_header.adoc[]
:position: 10270

The data format **VariationMarketIdentNumber** is used to save ASINs and EPIDs. ASIN stands for Amazon Standard Identification Number. ePID stands for eBay Product ID. +
Create and export the data format in the **Data » Dynamic export** menu. Import the data format in the **Data » Dynamic import** menu. The <<data/export-import/exporting-data#, Exporting data>> and <<data/export-import/importing-data#, Importing data>> pages of the manual describe how you export and import the data format.

Pay close attention to the exact spelling of the data fields. The data cannot be processed if the data fields are spelled incorrectly.

== Overview of the data fields

Table 1 explains the data fields for the **VariationMarketIdentNumber** data format in alphabetical order as well as filter options that you set in the **Filter** tab of the data format.

[cols="1,3,3"]
|====
|Field name |Explanation |Filter

| **ASIN**
|Amazon Standard Identification Number +
. Product identification number assigned by Amazon.
|

| **VariationNumber**
|Variation number
|

| **ePID**
|eBay product ID +
Product ID from eBay that lets items be found more easily on eBay. It is provided by eBay.
|

| **ItemFlag1**
|Flag 1
|Activate the filter and select the operator and a value from the drop-down list.

| **ItemFlag2**
|Flag 2
|Activate the filter and select the operator and a value from the drop-down list.

| **MarketplaceCountry**
|The market's country +
IDs are defined as follows for the ASIN and ePID: +
**ASIN** +
**0**: All +
**1**: Amazon.de +
**8**: Amazon.es +
**10**: Amazon.fr +
**12**: Amazon.co.uk +
**15**: Amazon.it +
**28**: Amazon.com  +
**ePID** +
**1**: Germany +
**2**: Austria +
**3**: Belgium (FR), Belgium (NL) +
**4**: Switzerland +
**8**: Spain +
**10**: France +
**12**: England +
**15**: Italy +
**16**: Ireland +
**21**: Netherlands +
**23**: Poland +
**28**: USA, Motors +
**29**: Australia +
**30**: Canada, Canada (FR) +
**38**: India +
**57**: Hong Kong +
**56**: Malaysia +
**200**: Philippines +
**25**: Singapore
|

| **Position**
|The ASIN or ePID's position
|

| **RSIN**
|Redoute Standard Identification Number +
Product identification number, which was established by La Redoute.
|

| **VariationID**
|Variation ID
|Activate the filter, select the operator and enter the value.
|====

__Table 1: data fields of the data format **VariationMarketIdentNumber**__

[WARNING]
.ASIN and ePID
====
The data fields **ASIN** and **ePID** may not be left empty. If you leave the field empty and your variation currently has data saved for one of these fields, then this data will be deleted. Before carrying out the data import, be sure to carefully check which entries are available for the variations that you want to assign values to.
====

== Overview of the synchronisation fields

The data fields that are listed in table 2 are available for <<data/export-import/importing-data#25, data synchronisation>>. These data fields are mandatory synchronisation fields. For mandatory synchronisation fields, select the option **Synchronisation** as **Import procedure**.

[cols="1,3"]
|====
|Field name |Explanation

| **VariationNumber**
|Variation number

| **MarketplaceCountry**
|The market's country

| **Position**
|The ASIN or ePID's position

| **VariationID**
|Variation ID
|====

__Table 2: data fields with the import procedure set to **Synchronisation**__

[NOTE]
.Import: What to do if there is no match
====
When importing data, make sure that the setting **If there is no match during the synchronisation** is set to **Create a new data record**. If you select **Skip data record**, then the corresponding information will be lost if there is no match.
====
