= Database backup
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Backup, back up data, data backup, restore, import backup, backup types, backup logs
:description: Find out how to create backups and import backed up plentymarkets data.
:position: 60
:url: data/backup
:id: XCMTBYE
:author: team-import-export

Use the backup function in the **Setup » Settings » Hosting » Backup** menu to reset data in the database to a previous state or restore deleted data.

[IMPORTANT]
.Limitations
====
You can only use the backup function within the same version of plentymarkets. This means that it is not possible to import a backup of an older version of plentymarkets. In addition, this function is not a regular data backup, but a database backup. Thus, this function can *not* be used to restore content saved in the cloud storage, such as order documents or item images.
====

== Backing up and restoring data

The **Setup » Settings » Hosting » Backup** menu offers an overview of the existing backups with the corresponding dates. They are automatically created on a daily basis.

=== Storing a backup locally

As an additional safeguard, you can save backup files locally. To do so, proceed as follows.

[.instruction]
Storing a backup locally:

. Go to **Setup » Settings » Hosting » Backup**.
. Select the backup you want to download.
. Click on **Download backup** (icon:download[role="purple"]). +
The backup is downloaded in compressed form.

[TIP]
.Waiting for backup
====
The download of large files will take some time. Once the process is complete, the download button is activated.
====

=== Importing a backup

You can reset your system to the status of any backup.

[WARNING]
.Possible data loss:
====
Note that importing a backup can overwrite current data. Data that have changed since the last backup creation can be lost irreversibly.
====

[.instruction]
Importing a backup:

. Go to **Setup » Settings » Hosting » Backup**.
. Click on **Import backup** (icon:upload[role="purple"]). +
→ The window for the backup import opens.
. Carry out the settings. Pay attention to the information given in <<table-import-options>> and <<table-backup-types>>.
. Click on **Import backup** to import the backup. +
→ The backup is imported.

The dropdown menu offers two different import options.

[[table-import-options]]
.Import options
[cols="1,2"]
|====
|Import option |Explanation

| **Partially import data base**
|Here you can select the areas that you want to import.

| **Completely import data base**
|This option considers and restores all available data.
|====


Select the area of the system that you want to reset or in which you want to restore data.

[[table-backup-types]]
.Backup types
[cols="1,2"]
|====
|Backup type |Explanation

| **Account** +
|Restores company data records including addresses, their relation to the company, address options, contacts, their relation to the company, contact options, contact type, bank details, contact properties, allowed payment methods, events and the order overview. +
Messages (previously notes) are not considered.

| **Category** +
|Restores categories and the structure of the category tree in the *Item » Categories* menu. +
In this process, the categories are not linked to the individual variations. Use the backup type *ItemVariationCategoryValues* in order to solely restore the category links. Alternatively, use the backup type *ItemVariation* in order to restore the category links together with further variation data.

| **Listing** +
|Restores information about listings and market listings (title, subtitle, description), all information in the *Marketplace* tab of a listing, eBay properties, options templates, listing schedulers, listing directories, active listings and the list of future listings.

| **Order**
|Restores all orders and the corresponding order information (plus reorders).

| **Process**
|Restores processes in the *Setup » Processes* menu including work steps, procedures, sub-procedures and control elements. +
You may need to set <<automation/processes/setting-up-processes#220, system- specific settings>> such as those for printer or status once again.

| **Ticket**
|Restores ticket data, files, owners, questions, roles, types, references, statuses and templates.

| **User**
|Restores users registered in the system and the settings they have carried out (rights, roles etc.).

| **Warehouse**
|Restores warehouses and the warehouse structure, such as dimensions and storage locations. +
Does not include the stock. However, you can save your stock on a daily basis by creating a backup.

| **FacetDefinition**
|Restores facets, values and settings in the *Setup » Client » Settings » Services » Faceted search* menu.

| **Item**
|Restores item data records including descriptions, shipping profile links, cross-selling settings, FBA settings and item sets.

| **ItemAttribute**
|Restores attributes and attribute values in the *Setup » Item » Attributes* menu. +
In this process, the categories are not linked to the individual variations. Use the backup type *ItemVariation* in order to restore the links together with further variation data.

| **ItemBarCodeDefinition**
|Restores the barcodes in the *Setup » Item » Barcode* menu. +
In this process, the barcodes are not linked to the individual variations. Use the backup type *ItemVariation* in order to restore the links together with further variation data.

| **ItemCharacterDefinition**
|Restores the characteristics and characteristic groups in the *Setup » Item » Characteristics* menu. +
In this process, the characteristics are not linked to the individual items. Use the backup type *ItemCharacterValues* in order to restore the values of the characteristic links.

| **ItemCharacterValues**
|Restores the values of the characteristic links that are directly saved on the item in the *Characteristics* tab. +
Assumes that the characteristics and characteristic groups already exist or have been restored with the backup type *itemCharacterDefinition*.

| **ItemPriceCalculation**
|Restores the price calculations in the *Setup » Item » Calculation* menu. +
In this process, the price calculations are not linked to the individual variations. Use the backup type *ItemVariation* in order to restore the links together with further variation data.

| **ItemManufacturer**
|Restores the manufacturer data in the *Setup » Item » Manufacturers* menu. +
In this process, the manufacturers are not linked to the individual variations. Use the backup type *ItemVariation* in order to restore the links together with further variation data.

| **ItemSalesPriceDefinition**
|Restores the sales prices in the *Setup » Item » Sales prices* menu. +
In this process, the sales prices are not linked to the individual variations, nor are the monetary prices entered. Use the backup type *itemVariationSalesPriceValues* in order to solely restore the links and prices. Alternatively, use the backup type *ItemVariation* in order to restore the links and prices together with further variation data.

| **ItemUnit**
|Restores the units in the *Setup » Item » Units* menu. +
In this process, the units are not linked to the individual variations. Use the backup type *ItemVariation* in order to restore the links together with further variation data.

| **ItemVariation**
|Restores variation data records.
This also includes the _links_ between variations and other data, such as barcodes, categories, standard categories, images, ASINs, prices, suppliers, warehouses etc.

*_Note_*: The links can only be restored if the data that should be linked (i.e. the actual barcodes, categories, images, etc.) still exist or have already been restored with a corresponding backup type.

Item bundles are restored, too.
Tags are not restored.

| **ItemVariationCategoryValues**
|Restores the category links that are directly saved on the variation in the *Categories* tab. +
Alternatively, use the backup type *ItemVariation* in order to restore the category links together with further variation data. Assumes that the categories and the structure of the category tree already exist or have been restored with the backup type *Category*.

| **ItemVariationSalesPriceValues**
|Restores the sales price links and monetary prices that are directly saved on the variation in the *Settings* tab.
Alternatively, use the backup type *ItemVariation* in order to restore the links and prices together with further variation data. +
Assumes that the sales prices already exist or have been restored with the backup type *ItemSalesPriceDefinition*.
|====

=== Showing backup logs

By clicking the button in the toolbar, backup logs and possible error messages are shown.

[.instruction]
Showing backup logs:

. Go to *Setup » Settings » Hosting » Backup*.
. Click on *Show backup logs*. +
→ The window with the backup logs opens.

For further information, refer to the <<data/datalog#, Data log>> manual page.
