= CampaignCoupon
:lang: en
:description: CampaignCoupon
:position: 10030
:url: data/export-import/data-formats/campaigncoupon
:id: KNP2JHY
:author: team-crm

The data format *CampaignCoupon* is used to export and edit the coupon codes that were saved for coupon campaigns in the xref:orders:exporting-data.adoc#[Exporting data] page of the manual describes how you export the data format.

Pay close attention to the exact spelling of the data fields. The data cannot be processed if the data fields are spelled incorrectly.

== Overview of the data fields

Table 1 explains the data fields for the *CampaignCoupon* data format in alphabetical order as well as filter options that you set in the *Filter* tab of the data format.

[cols="1,3,3"]
|====
|Field name |Explanation |Filter

| *CampaignID*
|Campaign ID
|Activate the filter and select the campaign from the drop-down list for which you want to edit the coupon codes. +
*_Important_*: If no filter is selected here, then the data from the first campaign will be exported.

| *CouponCode*
|Coupon code +
It is possible to save additional xref:orders:coupons.adoc#5[coupon codes]. Enter the coupon codes into this column and enter the campaign ID into the *CampaignID* column.
|
|====

_Table 1: data fields of the data format *CampaignCoupon*_

== Overview of the mandatory fields

The following mandatory fields must be available for the data format *CampaignCoupon* and need to have a valid value saved for them:

* *CampaignCoupon*
* *CouponCode*
