= Understanding catalogues
:keywords:
:description: Are you just starting out using catalogues? Then you’re in the right place.
:page-index:
:author: team-plenty-channel

Are you just starting out using catalogues? Then you’re in the right place.

* <<#catalogue-formats, Which types of catalogues are available?>>
* <<#catalogue-overview, Get to know the catalogue overview.>>

include::_includes:page$new-page-info-box.adoc[]

[#catalogue-formats]
== Which types of catalogues are available?

Catalogues are used to export data from your plentymarkets system. There are catalogues with marketplace formats and catalogues with standard formats.

[cols="1,4a"]
|===

| *Default formats*
| Use standard formats to *_export data from your plentymarkets system to a CSV, JSON, TXT or XML file_*.

Which standard format you choose depends on the type of data you want to export. For example, to export stock information, use the standard format xref:data:catalogues-stocks.adoc#[Stocks]. To export item data, the standard format xref:data:catalogues-item.adoc#[Item] is available.

Not all types of data can currently be exported using catalogues. Until standard formats are available for all types of data, you can still use the xref:page$FormatDesigner.adoc#[ FormatDesigner].

* Find out how to create catalogues with standard formats on the xref:export-standard-formats.adoc#[Creating standard formats].

| *Marketplace format*
| The marketplace formats are used to *_export variation data to markets and other sales channels._*

Each sales channel requires different product data. Often, different product information have to be exported to the same sales channel for different product categories. For example, when selling cat food, you may need to specify the unit price. To sell clothing or shoes, you may have to specify the product’s material composition.

A marketplace format provides a framework of the data a sales channel can accept. Catalogues allow you to customise information regarding your product portfolio to meet the requirements of each sales channel and target audience.

* An introduction to marketplace formats lives on the manual page xref:data:export-marketplace-formats.adoc#[Using marketplace formats].
* Check the manual pages of xref:markets:markets.adoc#[the individual sales channels] to find out how to create a catalogue for each market.

|===

[#catalogue-overview]
== Understanding the catalogue overview

include::partial$catalogue-overview.adoc[]

[#faq]
== FAQ: Questions and answers

include::partial$catalogues-faq.adoc[tag=faq-which-format]

include::partial$catalogues-faq.adoc[tag=rights]
