= CustomerNote
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Data format CustomerNote, notes
:description: Use the data format CustomerNote to export notes that are saved in the customer data.
:position: 10070
:url: data/export-import/data-formats/customernote
:id: LX4Y5WC
:author: team-crm

The data format *CustomerNote* is used to export notes that are saved in the customer data. Notes can be found in the corresponding tab in the customer data record. Create and export the data format in the *Data » Dynamic export* menu. The <<data/export-import/exporting-data#, Exporting data>> page of the manual describes how you export the data format.

Pay close attention to the exact spelling of the data fields. The data cannot be processed if the data fields are spelled incorrectly.

== Overview of the data fields

Table 1 explains the data fields for the *CustomerNote* data format in alphabetical order as well as filter options that you set in the *Filter* tab of the data format. The data format may vary depending on your plentymarkets version.

.Data fields of the data format *CustomerNote*
[cols="1,3,3"]
|====
|Field name |Explanation |Filter

| *CustomerID*
|ID of the customer
|Activate the filter, select the operator and enter the value.

| *Delete*
|Delete note
|

| *NoteID*
|ID of the note
|

| *NoteText*
|Note in the customer data record
|

| *NoteUserID*
|ID of the user who created the note
|Activate the filter, select the operator and enter the value.

| *Export for customer class*
| *_Note_*: filter setting only
|Activate the filter and select the customer class from the drop-down list. In order to export data for all customer classes, do not activate the filter. Go to <<crm/managing-contacts#15, Setup » CRM » Classes>> to create customer classes.
|====

== Overview of the mandatory fields

The following mandatory fields must be available for the data format *CustomerNote* and need to have a valid value saved for them:

* *CustomerID*
* *NoteText*
* *NoteUserID*

////
== Overview of the synchronisation fields

The following data field is available for <<data/export-import/importing-data#25, data synchronisation>>. For mandatory synchronisation fields, select the option *Synchronisation* as *Import procedure*.

* *NoteID*

////
