= CustomerPropertyLink
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Data format CustomerPropertyLink, customer properties and values
:description: Use the data format CustomerPropertyLink to export customer properties and the values saved for your customers.
:position: 10077
:url: data/export-import/data-formats/customerpropertylink
:id: RWENFES
:author: team-crm

The data format *CustomerPropertyLink* is used to export <<crm/managing-contacts#4000, customer properties>> and values saved in the customer data. Use this data format to quickly link customer properties with certain customers. Create and export the data format in the *Data » Dynamic export* menu. The <<data/export-import/exporting-data#, Exporting data>> page of the manual describes how you export the data format.

Pay close attention to the exact spelling of the data fields. The data cannot be processed if the data fields are spelled incorrectly.

== Overview of the data fields

Table 1 explains the data fields for the *CustomerPropertyLink* data format in alphabetical order as well as filter options that you set in the *Filter* tab of the data format. The data format may vary depending on your plentymarkets version.

.Data fields of the data format *CustomerPropertyLink*
[cols="1,3,3"]
|====
|Field name |Explanation |Filter

| *CustomerID*
|The ID of the customer
|

| *CustomerPropertyID*
|The ID of the customer property
|Activate the filter, select the operator and enter the value.

| *CustomerPropertyValue*
|The value saved for the customer within the customer property.
|Enter a value to link a property with a customer. +
*_Note_*: If you leave the field *CustomerPropertyValue* blank or do not activate it, then the property will be deactivated for the customer. +
Go to *Setup » CRM » Characteristics* to create properties.

| *Export for customer class*
| *_Note_*: filter setting only
|Activate the filter and select the customer class from the drop-down list. In order to export data for all customer classes, do not activate the filter. Go to <<crm/managing-contacts#15, Setup » CRM » Classes>> to create customer classes.
|====

== Overview of the mandatory fields

The following mandatory fields must be available for the data format *CustomerPropertyLink* and need to have a valid value saved for them:

* *CustomerPropertyID*
* *CustomerID*
