= CustomerNewsletter
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Data format CustomerNewsletter
:description: Use the data format CustomerNewsletter to export customer data that was entered for the newsletter.
:position: 10060
:url: data/export-import/data-formats/customernewsletter
:id: 0EUDZWC
:author: team-crm

The data format *CustomerNewsletter* is used to export customer data that was entered for the newsletter. Create and export the data format in the *Data » Dynamic export* menu. The <<data/export-import/exporting-data#, Exporting data>> page of the manual describes how you export the data format.

Pay close attention to the exact spelling of the data fields. The data cannot be processed if the data fields are spelled incorrectly.

== Overview of the data fields

Table 1 explains the data fields for the *CustomerNewsletter* data format in alphabetical order as well as filter options that you set in the *Filter* tab of the data format. The data format may vary depending on your plentymarkets version.

.Data fields of the data format *CustomerNewsletter*
[cols="1,3,3"]
|====
|Field name |Explanation |Filter

| *Birthday*
|The customer's date of birth
|

| *ConfirmedTimestamp*
|The date of the opt-in confirmation
|

| *CustomerID*
|ID of the customer
|

| *CustomerNewsletterID*
|The ID of the data record saved in the *Setup » CRM » Newsletter » plentymarkets » Emails*menu
|

| *Directory*
|The email folder that contains the customer's email address; saved in the system in the *Setup » CRM » Newsletter » plentymarkets » Emails* menu
|Activate the filter and select the email folder from the drop-down list.

| *Email*
|The customer's email address
|

| *FirstName*
|The customer's first name
|

| *Gender*
|The customer's gender
|

| *LastName*
|The customer's surname
|

| *Export for customer class*
| *_Note_*: filter setting only
|Activate the filter and select the customer class from the drop-down list. In order to export data for all customer classes, do not activate the filter. Go to <<crm/managing-contacts#15, Setup » CRM » Classes>> to create customer classes.
|====

[TIP]
.Data export
====
The export does not include data from all of the email folders. If no filter is activated in the data format, then data will be exported from the first folder that is found in the *Setup » CRM » Newsletter » plentymarkets » Emails* menu.
====

== Overview of the mandatory fields

The following mandatory fields must be available for the data format *CustomerNewsletter* and need to have a valid value saved for them:

* *CustomerID*
