= Data log
:lang: en
include::{includedir}/_header.adoc[]
:keywords: log, data log, log entries
:description: Find out how to search for log entries.
:position: 40
:url: data/datalog
:id: 8PM1DPV
:author: team-import-export

The menu *Data » Log* contains all log entries. These are available for 4 weeks before they are deleted. Logs can be activated individually and in addition, for every log entry you can set the duration for which you want the log entry to stay active.

[[table-information-table-header]]
.Information in the table header
[cols="1,2"]
|====
|Title |Info

| *Timestamp*
|Timestamp of the corresponding log entry

| *Level*
|Display of the log level such as *Info*, *Error* etc.

| *Integration*
|Area in which the log entry is located in the code

| *Identifier*
|Sub-area to which the log belongs

| *Reference*
|Reference type with the corresponding ID

| *Message*
|Explanation of the log. If an error occurred, explanation of the error.
|====

By clicking on a line, the detail view opens and further info regarding the log is displayed. This window enables you to switch from one entry to the next and you can fold in or fold out the view.

[#10]
== Configuring logs

In order to see notifications of the corresponding log areas, you have to activate them first. To do so, go to *Configure logs » Settings*. They are saved on the server for a maximum of 4 weeks. The drop-down menu lists the different levels with increasing priority. You can also set the duration for which you want the log entry to stay active.

[IMPORTANT]
.Activation necessary
While the log levels Error, Critical, Alert and Emergency are automatically displayed, Debug, Info, Notice and Warning have to be activated first.

[.instruction]
Configuring logs:

. Go to *Data » Log*.
. In the toolbar, click on *Configure logs* (icon:cog[]). +
→ The window *Log configuration* opens. On the left you can see the plugins that are already installed as well as the standard areas. On the right you can carry out the settings.
. Select the area in which you want to configure logs.
. On the right, check the box *Active*.
. Select the duration for which you want the log level to stay active in this area.
. Select the log level. Pay attention to the information given in <<table-meaning-of-log-levels>>.
. Save (icon:save[role="green"]) the settings.

[[table-meaning-of-log-levels]]
.Meaning of the different log levels
[cols="1,4,1"]
|====
|Log level |Description |Activated by default

| *Debug*
|Detailed status messages
|No

| *Info*
|General information about the system
|No

| *Notice*
|An error message that should be dealt with, but is not urgent.
|No

| *Warning*
|Something is not working as intended. However, it does not necessarily have to be an error.
|No

| *Error*
|Standard system error; when errors occur, the system usually keeps running.
|Yes

| *Critical*
|These errors can cause a system crash (runtime errors).
|Yes

| *Alert*
|It is necessary to take action immediately (the online store or the database may not be available).
|Yes

| *Emergency*
|Absolute emergency. The system is unusable.
|Yes
|====

[#20]
== Searching for log entries

On the left you can set different filters that allow you to reduce a large number of log entries to specific matches. The entries in the drop-down menus are reduced to the keywords that actually exist in the search results.

[IMPORTANT]
.Filtering by client
====
The log only displays entries from the main client. The logs of other clients are saved, but cannot be displayed here.

To access logs from other clients, you have to use the <<data/rest-api#, REST API>>. To access the logs from a particular client, you have to call link:https://developers.plentymarkets.com/en-gb/plentymarkets-rest-api/index.html#/Log/get_rest_logs[the route] `/rest/logs` with the domain of that client.
====

[#30]
== Filtering by integration

Here you can see the area from which the log call was made.

[.instruction]
Filtering by the variable *Integration*:

. Go to *Data » Log*.
. Click on *Integration*. +
→ A list with different options opens.
. Select an area.
. Click on *Search* (icon:search[role="blue"]). +
→ The corresponding log entries are shown.

[#40]
== Filtering by identifier

The identifier indicates to which sub-area the log belongs.

[.instruction]
Filtering by the variable *Identifier*:

. Go to *Data » Log*.
. Click on *Identifier*. +
→ A list with different options opens.
. Select an identifier.
. Click on *Search* (icon:search[role="blue"]). +
→ The corresponding log entries are shown.

[#50]
== Filtering by level

Here you can see the different log levels such as *Error*, *Info* etc.

[.instruction]
Filtering by the variable *Level*:

. Go to *Data » Log*.
. Click on *Level*. +
→ A list with different options opens.
. Select a level.
. Click on *Search* (icon:search[role="blue"]). +
→ The corresponding log entries are shown.

*_Note:_* Activate all levels for this option.

[#60]
== Filtering by reference type

Here you can see the reference type to which the entry belongs (e.g. VariationID, OrderID etc.).

[.instruction]
Filtering by the variable *Reference type*:

. Go to *Data » Log*.
. Click on *Reference type*. +
→ A list with different options opens.
. Select a reference type.
. Click on *Search* (icon:search[role="blue"]). +
→ The corresponding log entries are shown.

[#70]
== Filtering by reference value

Here you can see the value of the reference. As an example, for the reference type *ItemID*, this would be the value of this ID. The search results are reduced to matches with this value.

[.instruction]
Filtering by the variable *Reference value*:

. Go to *Data » Log*.
. Click on *Reference value*.
. Enter a reference value.
. Click on *Search* (icon:search[role="blue"]). +
→ The corresponding log entries are shown.

[#80]
== Filtering by date

Here you can individually adjust the search results and reduce them to a specific time frame.

[.instruction]
Filtering by the variable *Date*:

. Go to *Data » Log*.
. Select a starting date.
. Select an ending date.
. Click on *Search* (icon:search[role="blue"]). +
→ The log entries created in the defined time frame are shown.

[#90]
== Filtering by time

Here you can individually adjust the search results and reduce them to a specific time frame.

[.instruction]
Filtering by the variable *Time*:

. Go to *Data » Log*.
. Enter the time from which on you want to search.
. Enter the time up to which you want to search.
. Click on *Search* (icon:search[role="blue"]). +
→ The log entries created in the defined time frame are shown.
