= Data
:keywords: data, data exchange, ElasticSync, Elastic Sync, Elastic-Sync, FormatDesigner, Format Designer, Format-Designer, Elastic Export, raw data
:author: team-plenty-channel
:page-index: false

This area deals with exchanging data in plentymarkets. Data can be exchanged automatically or manually. Use the link:https://developers.plentymarkets.com/[REST API] or the sub-menus in the **Data exchange** menu to exchange data between your plentymarkets system and external systems. The **import tool** is used to manually transfer data.

You can also use the data exchange to quickly and easily make changes and adapt settings in your plentymarkets system. Simply export the data of your items, customers, stocks or orders into a CSV file, make changes to the data and import the file back into the system.

*Import*
* xref:data:ElasticSync.adoc#[Using the import tool]

*Export*
* xref:data:FormatDesigner.adoc#[Creating data formats with FormatDesigner]
* xref:data:elastic-export.adoc#[Exporting data with Elastic Export]
* xref:business-decisions:manage-reports.adoc#[Exporting raw data]
