= Data log
:keywords: log, logs, data log, log entries, log level, reference type, reference value, configure logs, configuring logs
:keywords: Find out how to use the data log to find error messages and information about system events.
:author: team-plenty-channel

Events in your system are logged in the menu *Data » Log*. This allows you to check the data log for errors without relying on our support.

Events with the severities *Error*, *Critical*, *Alert* and *Emergency* are logged automatically. You can activate logging of other events for a limited time if and when needed.

== What is the data log?

The data log documents events that occur in your system.

* Each log entry is equivalent to one event in your system.
* Each log entry is available for four weeks after the event. After that time, the log entry is deleted automatically.
* Events can have different degrees of severity. In plentymarkets, these different severities are called log levels.
* Events with the log levels *Error*, *Critical*, *Alert* and *Emergency* are logged automatically.
* The log levels *Debug*, *Info*, *Notice* and *Warning* are not logged by default. Instead, you need to activate them to document events with this severity. (<<#10, How?>>)
* Each log entry contains the following information about the event:

[cols="1,2a"]
|====
| *Timestamp*
| The date and time of the event

| *Level*
| The severity of the event +
(<<#log-levels, What do the log levels mean?>>)

| *Integration*
| The area of the system in which the event too place.

*_Examples:_*

* Ceres
* DHLShipping
* Etsy

| *Identifier*
| The sub area of the system in which the event too place.

*_Examples:_*

* AmazonCatalog

| *Reference type*
| The type of record: For example, is it an address ID, a catalogue name or the ID of an Etsy listing?

| *Reference value*
| The value of the record to which the event relates. For example, this could be the ID of an item, of a variation or of a category.

| *Message*
| A description of the event

| *Log details* +
(in a separate window)
| Click on the log entry to show more details. More information about the event is displayed. In this window, you can also jump to the previous or next log entry. In addition, you can show or hide the information.
|====

[#log-levels]
== What do the log levels mean?

[[table-meaning-of-log-levels]]
.Meaning of the different log levels
[cols="1,4,1"]
|====
|Log level |Description |Activated by default

| *Debug*
| Detailed status messages
| No

| *Info*
| General information about the system
| No

| *Notice*
| An error message that should be dealt with, but is not urgent.
| No

| *Warning*
| Something is not working as intended. However, it might not be an error.
| No

| *Error*
| Standard system error; when errors occur, the system usually keeps running.
| Yes

| *Critical*
| These errors can cause a system crash.
| Yes

| *Alert*
| You need to react immediately. +
*_Example:_* The online store or database is not reachable.
| Yes

| *Emergency*
| Absolute emergency. The system is unusable.
| Yes
|====

[#20]
== Finding log entries

When you open the menu *Data » Log*, a list of all logged events for the default client is shown. This list is sorted by date and time. As such, the latest event is at the top of the list.

You can filter the log entries to reduce the list of events and make it more manageable.

[.instruction]
Filtering the list of log entries:

. Go to *Data » Log*. +
→ All logged events of the default client are shown.
. At the top left of the toolbar, click on (material:tune[]). +
→ The available filters are shown.
. Select the filters you want to apply. Note the explanations in <<#log-filter>>. +
*_Is a filter missing from the drop-down lists?_* +
The drop-down lists only contain filters for events for which log entries exist. So if for example you cannot select a filter for *OTTO Market* from the list, that means that no events were logged for this market in the last four weeks.
. Click on (icon:search[role="blue"]) *Search*. +
→ The filtered log entries are shown. +
*_Could not find the log entry you were looking for?_* +
 Not all events are logged by default. So you might have to <<#10, activate the logging for the event you are trying to find>>.

[[log-filter]]
.Available filters
[cols="1,3a"]
|===
|Filter |Explanation

| *Client*
| By default, the list is filtered to only show log entries for the default client. To show events for another client (store), select that client (store) from the drop-down list.

| *Integration*
| The area of the system in which the event too place.

*_Examples:_*

* Ceres
* DHLShipping
* Etsy

| *Identifier*
| The sub area of the system in which the event too place.

*_Examples:_*

* AmazonCatalog

| *Level*
| The severity of the event. +
(<<#log-levels, What do the log levels mean?>>)

| *Reference type*
| The type of record: For example, is it an address ID, a catalogue name or the ID of an Etsy listing?

| *Reference value*
| The value of the record to which the event relates. For example, this could be the ID of an item, of a variation or of a category.

| *Date from*
| Click on the calendar icon to select a date. +
→ Only events from this date onwards are shown in the list. +
*_Note:_* You can select any date you want. However, note that only events of the last four weeks can shown. Log entries are automatically deleted after four weeks.

| *Time from*
| Enter a time in the format HH:MM:SS. +
→ If you have selected a *Date from*, events starting from this time on the selected date are shown. +
→ If you have not selected a *Date from*, events starting from this time today are shown.

| *Date to*
| Click on the calendar icon to select a date. +
→ Only events up to and including this date are shown in the list. +
*_Note:_* You can select any date you want. However, note that only events of the last four weeks can shown. Log entries are automatically deleted after four weeks.

| *Time to*
| Enter a time in the format HH:MM:SS. +
→ If you have selected a *Date to*, events up to this time on the selected date are shown. +
→ If you have not selected a *Date to*, events up to this time today are shown.
|===

[#10]
== Activating optional logging

Events with the log levels *Error*, *Critical*, *Alert* and *Emergency* are logged automatically.
However, to log events with the log levels *Debug*, *Info*, *Notice* or *Warning*, you need to activate logging first.

* Logging ends automatically once the duration you set is up.
* You are unsure about what to log and confused about integrations, reference types and identifiers? For many markets, you can find info on what to filter for on the manual page for that market. Or head to the forum to ask which system areas you need to log to find out what’s going on.

[.instruction]
Activating optional logging:

. Go to *Data » Log*. +
→ All events logged for the default client are shown.
. In the top left of the toolbar, click on *Configure logs* (icon:cog[]). +
→ The window *Log configuration* opens. +
→ On the left side, the system areas and any installed plugins are listed.
. Select the area in which you want to configure logs. +
→ On the right side, the settings for the area you selected are shown.
. Activate the option *Active*.
. In the drop-down list *Duration*, select how long you want to log events for this area.
. In the drop-down list *Log level*, select the events that you want to log. +
<<#log-levels, What do the log levels mean?>>
. *Save* (icon:save[role="green"]) the settings. +
→ The logging of the events starts. +
→ Logging ends automatically once the duration you set is up. +
*_Important:_* The first log entry only becomes available once the event that you want to log next occurs.
