= Data
:keywords: data, data exchange, ElasticSync, Elastic Sync, Elastic-Sync, FormatDesigner, Format Designer, Format-Designer, Elastic Export, raw data
:id: PXLNINJ
:author: team-plenty-channel

This area deals with exchanging data in plentymarkets. Data can be exchanged automatically or manually. Use the link:https://developers.plentymarkets.com/[REST API]{nbsp}icon:external-link[] or the sub-menus in the **Data exchange** menu to exchange data between your plentymarkets system and external systems. The **import tool** is used to manually transfer data. xref:data:api-log.adoc#[Log entries] in the API log help you keep track of the data you exchanged.

You can also use the data exchange to quickly and easily make changes and adapt settings in your plentymarkets system. Simply export the data of your items, customers, stocks or orders into a CSV file, make changes to the data and import the file back into the system.

[.row]
====
[.col-md-4]
.Data exchange
=====
* xref:data:ElasticSync.adoc#[Using the import tool]
* xref:data:FormatDesigner.adoc#[Creating data formats with FormatDesigner]
* xref:data:elastic-export.adoc#[Exporting data with Elastic Export]
* xref:business-decisions:manage-reports.adoc#[Exporting raw data]
=====

[.col-md-4]
.Interfaces
=====

* link:https://developers.plentymarkets.com/[REST API^]{nbsp}icon:external-link[]
* *Deprecated*: link:{imagesdir}/business-decisions/assets/SOAP-Version-200-Documentation-2016-07-14.zip[SOAP API]{nbsp}icon:external-link[]
=====

[.col-md-4]
.Protocols

* *Deprecated* xref:data:api-log.adoc#[API log]
=====
====
