= Newsletter
:lang: en
include::{includedir}/_header.adoc[]
:keywords: import newsletter data, import newsletter recipients, import newsletter addresses
:position: 130
:url: data/importing-data/sync-types/elasticSync-newsletter
:id: 8YOA2GS
:author: team-crm

This page explains the matching and mapping fields that you can use while importing newsletter recipients. This page serves purely as a reference and it assumes that you already have a basic understanding of the <<data/importing-data/ElasticSync#, import tool>>.

[#matching-fields]
== Matching fields

The following field is available for matching newsletter recipients: During the import, plentymarkets checks if the imported data record already exists based on the matching field.

[[table-matching-field-newsletter-recipient]]
.Fields for importing newsletter data
[cols="1,3"]
|===
|Matching field |Explanation

|ID
|Which column of your CSV file lists the IDs of the email addresses which the newsletters are to be sent to? Choose this column here. This option is useful if you want to _update existing newsletter data_. +
If you want to import new email addresses, leave this field empty. The IDs for the email addresses are automatically assigned when carrying out the import.

*_Background info:_* Every new newsletter data record automatically receives an ID, which cannot be changed. The ID is used to uniquely identify the contact. Because the ID is unique, it’s a good way to check whether the imported data record already exists in plentymarkets.

|===

[#mapping-fields]
== Mapping fields

This chapter explains the fields that are available for mapping newsletter data. Use these fields to specify which _column of your file_ corresponds to which _data field in your system_.

[.instruction]
Basic procedure:

. *_In your CSV file_*: Enter a valid import value into a column.
. *_In plentymarkets_*: Assign this column to the appropriate mapping field.
. *_After the import_*: Check the result in the back end.

[TIP]
.No mapping field? Default value applies!
====
If you don’t include a certain piece of information in your CSV file, i.e. if you _don’t use_ a certain mapping field, then your newsletter will be given the default value.
====


[#newsletter]
=== Newsletter

[#id]
==== ID

Enter the ID of the email address to which the newsletter is sent in your CSV file.

*_Default value:_* No default value

*_Permitted import values:_* Numeric (internal ID)

You can find the result of the import in the back end menu <<crm/sending-newsletters#, *Setup » CRM » Newsletter » Emails » [Expand folder]*>> after you have carried out the search (icon:search[role="blue"]).

'''

[#folder-id]
==== ID of the folder

Enter the ID of the folder in which the email address of the newsletter recipient is saved in your CSV file.

*_Default value:_* No default value



*_Permitted import values:_* Numeric (internal ID)

You can find the result of the import in the back end menu <<crm/sending-newsletters#, *Setup » CRM » Newsletter » Emails* in the overview *Emails per folder*>>.

'''

[#contact-id]
==== Contact ID

Do you want to establish a link to an existing contact when carrying out the import? Enter the ID of the contact in your CSV file.

*_Default value:_* No default value

*_Permitted import values:_* Numeric (internal ID)

'''

[#first-name]
==== First name

Enter the recipient’s first name in your CSV file.

*_Default value:_* No default value

*_Permitted import values:_* Text

You can find the result of the import in the back end menu <<crm/sending-newsletters#, *Setup » CRM » Newsletter » Emails » [Expand folder]*>>. Then click on search (icon:search[role="blue"]) and expand (icon:plus-square-o[]) the data record. The value is saved in the *First name* field.

'''

[#last-name]
==== Last name

Enter the recipient’s last name in your CSV file.

*_Default value:_* No default value

*_Permitted import values:_* Text

You can find the result of the import in the back end menu <<crm/sending-newsletters#, *Setup » CRM » Newsletter » Emails » [Expand folder]*>>. Then click on search (icon:search[role="blue"]) and expand (icon:plus-square-o[]) the data record. The value is saved in the *Last name* field.

'''

[#email]
==== Email

Enter the recipient’s email address in your CSV file.

*_Default value:_* No default value

*_Permitted import values:_* Alpha-numeric

You can find the result of the import in the back end menu <<crm/sending-newsletters#, *Setup » CRM » Newsletter » Emails » [Expand folder]*>>. Then click on search (icon:search[role="blue"]) and expand (icon:plus-square-o[]) the data record. The value is saved in the *Email* field.

'''

[#form-of-address]
==== Form of address

Enter the recipient’s form of address in your CSV file.

*_Default value:_* No default value

*_Permitted import values:_* Text

This information might be useful for external newsletter providers, for example.

'''

[#birthday]
==== Birthday

Enter the recipient’s date of birth in your CSV file.

*_Default value:_* No default value

*_Permitted import values:_* Date

This information might be useful for external newsletter providers, for example.

'''

[#language-template]
==== Template language

Enter the language that is saved for the email template in your CSV file.

[TIP]
The language is set in the *Email message* tab of the email template.

*_Default value:_* No default value

*_Permitted import values:_* Alpha-numeric

This information might be useful for external newsletter providers, for example.


'''

[#confirmed-at]
==== Confirmed at

Enter the date when the recipient confirmed the newsletter receipt in your CSV file.

*_Default value:_* No default value

*_Permitted import values:_* Date

You can find the result of the import in the back end menu <<crm/sending-newsletters#, *Setup » CRM » Newsletter » Emails » [Expand folder]*>>. Then click on search (icon:search[role="blue"]) and expand (icon:plus-square-o[]) the data record. The value is saved in the *Confirmed at* field.

'''

[#ip-address]
==== IP address

Enter the IP address that the recipient used to confirm the newsletter registration in your CSV file.

*_Default value:_* No default value

*_Permitted import values:_* Numeric

This information might be useful for external newsletter providers, for example.

'''

[#confirmation-link]
==== Confirmation link

What is the confirmation link that the persons who want to register for the newsletter receipt have to click? Enter this confirmation link in your CSV file.

[TIP]
The confirmation link can be inserted in the email template via the template variable `$NewsletterConfirmURL`.

*_Default value:_* No default value

*_Permitted import values:_* URL

This information might be useful for external newsletter providers, for example.

'''
