= Coupon codes
:lang: en
include::{includedir}/_header.adoc[]
:keywords: import coupon codes, coupon code import
:position: 68
:url: data/importing-data/sync-types/elasticSync-coupon-codes
:id: 5YTZP74
:author: team-crm

This page explains the matching and mapping fields that you can use while importing coupon codes and the corresponding data. This page serves purely as a reference and it assumes that you already have a basic understanding of the <<data/importing-data/ElasticSync#, import tool>>.

[#matching-fields]
== Matching fields

The following field is available for matching coupon codes and the corresponding data. During the import, plentymarkets checks if the imported data record already exists based on the matching field.

[[table-matching-field-coupon-codes]]
.Matching field for importing coupon codes and the corresponding data
[cols="1,3"]
|===
|Setting |Explanation

|Campaign ID
|Which column of your CSV file lists the campaign IDs? Choose this column here. This option is useful if you want to _update existing coupon codes or the corresponding data_. +
If you want to import new coupon codes, leave this field empty. The IDs for the campaigns are automatically assigned when carrying out the import.

*_Background info:_* Every new campaign automatically receives an ID, which cannot be changed. The ID is used to uniquely identify the campaign. Because the ID is unique, it’s a good way to check whether the imported data record already exists in plentymarkets.
|===

[#mapping-fields]
== Mapping fields

This chapter explains the fields that are available for mapping coupon codes and the corresponding data. Use these fields to specify which _column of your file_ corresponds to which _data field in your system_.

[.instruction]
Basic procedure:

. *_In your CSV file_*: Enter a valid import value into a column.
. *_In plentymarkets_*: Assign this column to the appropriate mapping field.
. *_After the import_*: Check the result in the back end.

[TIP]
.No mapping field? Default value applies!
====
If you don’t include a certain piece of information in your CSV file, i.e. if you _don’t use_ a certain mapping field, then your coupon will be given the default value.
====

[#campaign-code]
=== Campaign code

[#code]
==== Code

Enter the coupon code into your CSV file.

*_Default value:_* No default value

*_Permitted import values:_* Alpha-numeric

You can find the result of the import in the back end menu <<orders/coupons#generate-coupon-codes, *Orders » Coupons » [Open campaign]* in the *Codes* tab>>.

'''

[#campaign-id]
==== Campaign ID

What’s the ID of the campaign that should be assigned to the coupon code? Enter the campaign ID in your CSV file.

*_Default value:_* No default value

*_Permitted import values:_* Numeric (internal ID)

You can find the result of the import in the back end menu <<orders/coupons#create-campaign, *Orders » Coupons* » in the campaign overview>>.

'''

[#number-redemptions]
==== Number of redemptions

Enter the number of redemptions into your CSV file. The number refers to how often the coupon has already been redeemed.

*_Default value:_* No default value

*_Permitted import values:_* Numeric

You can find the result of the import in the back end menu <<orders/coupons#create-campaign, *Orders » Coupons* » in the campaign overview>>.

'''

[#redeemed-amount]
==== Redeemed amount

Enter the redeemed amount of the coupon into your CSV file. The redeemed amount can only be used for coupons of the type *Multipurpose coupon*.

[TIP]
During import, _not_ the residual balance of the coupon is imported, but the amount already redeemed (see example below).

*_Default value:_* No default value

*_Permitted import values:_* Numeric

You can find the result of the import in the back end menu <<orders/coupons#generate-coupon-codes, *Orders » Coupons » [Open campaign] in the *Codes* tab>>.

*_Example:_* The coupon has a value of EUR 100.00. The customer redeems EUR 80.00 of it. Thus, the residual balance is EUR 20.00. The value that is imported with this mapping field, is EUR 80.00.

'''

[#discount-value]
==== Discount value

Enter the discount value of the coupon into your CSV file.

*_Default value:_* No default value

*_Permitted import values:_* Numeric

You can find the result of the import in the back end menu <<orders/coupons#intable-coupon-campaign-discount-value, *Orders » Coupons* » in the campaign overview and in the campaign in the *Coupon* area>>.

'''
