= Payments
:keywords: exporting payments, export format payments
:description: Learn how to export payments from your plentymarkets system by using catalogues.
:page-aliases: catalogues-payments.adoc
:id: W8ZJUWG
:author: team-payment

This manual page contains information on the export format *Payments*, which you can use in order to export payment data from your plentymarkets system by using catalogues.
If you are not familiar with the usage of catalogues yet, refer to the manual page xref:data:file-export.adoc#[Using standard formats] first. There you will find out how to create and manage catalogues.

[discrete]
==== Format type: Payments

The format type described on this page is found in the menu *Data » Catalogues*.
When creating a new catalogue, you’ll select the standard format from the upper drop-down list.
Then you can select the format type *Payments* from the middle drop-down list.

[TIP]
.No export to marketplaces
====
The export format *Payments* is a so-called standard format, which you can use to export data from your system, but not to transfer data to a marketplace.
====

[TIP]
.Adapting export keys
====
To the left of newly added data fields, you can enter an *Export key*. The export key is the name under which the values of a data field are grouped in your export file. The export keys can be adapted. +
Always make sure that the export key is unique especially when you add the same data field several times and select different options. If the same export key is used more than once only the data field which was added last with this export key is exported. +
Find more information on data fields in general in the manual chapter xref:data:export-standard-formats.adoc#add-fields[Adding data fields to export].
====


[#10]
== Available data fields

The following table lists all available data fields of the export format *Payments* as well as an explanation on the meaning of these fields.

[[table-data-fields-payments]]
.Data fields for payments
[cols="2,3"]
|====
|Data field |Explanation

2+^|*Payment*

|*Payment ID*
|ID of the payment

|*Amount*
|Amount of the payment

|*Is system currency*
|Indicates whether the payment was carried out in the system currency or in another currency.

|*Currency*
|Currency of the payment

|*Exchange rate*
|Exchange rate of the payment

|*Received on*
|Date on which the payment was received

|*Import date*
|Date of the payment’s import

|*Payment method ID*
|ID of the payment method

|*Parent ID*
|ID of the parent

|*Debit / Credit*
|Incoming payments with a negative or positive value

|*Payment status*
|Status of the payment

|*Transaction type*
|Type of the transaction

|*Payment property*
|Property of the payment. Select a property from the drop-down list.

2+^|*Relation*

|*ID*
|ID of the relation. Select the relation type *Order* or *Contact*.

|*Assignment date*
|Date of the payment’s assignment. Select the relation type *Order* or *Contact*.

|====

[#20]
== Adding filters

In order to only export specific payments, you can select filters and thus narrow down the data. How to add filters is described in xref:data:export-standard-formats.adoc#filter-data[this chapter].

[#30]
=== Available filters

The following table lists all available filters for the export format *Payments* and gives an explanation on the usage of the respective filter.

[[table-filter-payments]]
.Filters for payments
[cols="2,3"]
|====
|Filter |Explanation

|*Transaction ID*
|Filters by payments with this Transaction ID.

|*Payment method ID*
|Filters by payments with this Payment method ID.

|*Debit / Credit*
|Filters by payments with Debit / Credit. Select Debit or Credit. +
*Debit* = All incoming payments with a negative value are displayed. +
*Credit* = All incoming payments with a positive value are displayed.

|*Amount*
|Filters by payments with this amount. Select an operator and enter an amount.

|*Assignment*
|Filters by payments with this assignment. +
Select *Assigned* to filter by payments that have been assigned to an order. +
Select *Unassigned* to filter by payments that have not been assigned to an order.

|*Payment status*
|Filters by payments with this payment status. Select one of the available statuses from the drop-down list.

|*Transaction type*
|Filters by payments with this transaction type. Select *Provisional posting* or *Booked posting*.

|*Currency*
|Filters by payments with this currency. Select one of the available currencies from the drop-down list.

|*Import date*
|Filters by payments with this import date. Select a time range or a date.

|*Received on*
|Filters by payments that have been received on that date. Select a time range or a date.

|*Assignment date*
|Filters by payments that have been assigned on that date. Select a time range or a date.

|====
