= FacetReference
:lang: en
include::{includedir}/_header.adoc[]
:position: 10105
:url: data/export-import/data-formats/facetreference
:id: JF1PP2J
:author: team-item

Use the data format **FacetReference** to edit the links of the faceted search.
Create and export the data format in the **Data » Dynamic export** menu.
The <<data/export-import/exporting-data#, Exporting data>> page of the manual describes how you export the data format.

Pay close attention to the exact spelling of the data fields. The data cannot be processed if the data fields are spelled incorrectly.

[IMPORTANT]
.Has the module been activated?
====
The data format is only available if you have booked and activated the Faceted search module.
====

== Overview of the data fields

Table 1 explains the data fields for the **FacetReference** data format in alphabetical order as well as filter options that you set in the **Filter** tab of the data format.

.Data fields of the data format **FacetReference**
[cols="1,3,3"]
|====
|Field name |Explanation |Filter

|FacetValueID
|ID of a facet value
|Activate the filter, select the operator and enter the value.

// td><strong>AttributeValueSurcharge</strong></td> <td>Aufpreis des Attributwertes; Wert des gewählten Aufpreises</td> <td>&nbsp;</td> </tr> <tr
|ReferenceValueID
|Either the attribute ID, the characteristic ID, the manufacturer ID or the availability ID depending on the reference type
|

|ReferenceType
|Reference types: attribute, character, manufacturer, availability
|

|Delete
|Delete the link, i.e. the reference
|

|
|Filter: Export for customer class
|Activate the filter and select the customer class.
|====

== Overview of the synchronisation fields

The data fields that are listed in table 2 are available for <<data/export-import/importing-data#25, data synchronisation>>. For mandatory synchronisation fields (M), select the option **Synchronisation** as **Import procedure**.

.Data fields with the import procedure set to **Synchronisation**
[cols="1,3,3"]
|====
|Field name |Explanation |Synchronisation field

| **FacetValueID**
|ID of a facet value
|M

| **ReferenceValueID**
|Depends on the reference type (see above)
|
|====
