= Getting to know the Import tool
:keywords: Import data, Data import, Import, ElasticSync, Synchronise, Synchronisation
:description: Get to know the plentymarkets Import tool: Definitions and video tutorials to get you started.
:author: team-plenty-channel

You don’t know the Import tool yet? Then you’re in the right place.

[#imports-define]
== What are imports?

Imports are used to import data from a file into plentymarkets. This import file must be accessible either in a webspace or a HTTPS.

The steps for creating and carrying out imports are identical for all import types. As such, the steps described in the following apply to all import types.

Go to *Data » Import* to create, edit and manage imports.

[#imports-terms]
== Important terms

[[import-definitions]]
.Import: Important terms
[cols="1,5a"]
|===
|Term |Explanation

| Import
| The term “import” has two different meanings in the Import tool:

. The import process.
. The sum of all settings for a specific import process. Go to *Data » Import* to see a list of all imports.

| Import types
| Depending on what type of data you want to import, you need different import types. Each import type saves the data in a different plentymarkets area during the import.

*_Examples of import types:_* Items, properties, manufacturers, etc. All import types are listed xref:data:import-types.adoc#[here].

| Data source/source
| The term “source” has two different meanings in the Import tool:

. The import file. You can upload this file manually. Or you can specify a HTTPS storage location for the file. For such files, you can specify an import interval. When you do that, the files are automatically imported again and again.
. A column of a CSV file. Each column is a source. TXT files are structured differently. However, it makes it easier to also imagine the data they contain as columns.

| Matching
| Use the matching to set what data is used to check if a data record already exists in plentymarkets or not.

| Mapping
| Use the mapping to decide which column of your import file is imported to which data field in plentymarkets.

*_Example:_* Your file contains a column*Product ID*. You want to save this product ID as the plentymarkets item ID during the import. To do so, you map the source *Product ID* to the plentymarkets field *Item ID*.
|===

[#import-videos]
== Video introduction

Are you working with imports for the first time? Then we recommend our video introductions.

*_Note:_* The term *ElasticSync* is outdated and has been replaced by *import*. The videos still offer a good introduction.

[#imports-video-intro]
=== Video: First steps with the import tool

This video offers an introduction to the import tool.

video::322745347[vimeo]

[#imports-video-manual-import]
=== Video: Manual import

This video shows you how to manually import files.

video::321227231[vimeo]

[#imports-video-automatic]
=== Video: Automatic import

This video shows you how to instruct plentymarkets to automatically import new files and archive old files.

video::322745747[vimeo]

== Ready?

Great. xref:data:ElasticSync.adoc#[Then create your first import.]
