= ItemImageReference
:lang: en
include::{includedir}/_header.adoc[]
:position: 10153
:url: data/export-import/data-formats/itemimagereference
:id: TPMJ6ZL
:author: team-item

Use the data format **ItemImageReference** to export the image availabilities for item images.
Create and export the data format in the **Data » Dynamic export** menu.
The <<data/export-import/exporting-data#, Exporting data>> page of the manual describes how you export the data format.

Pay close attention to the exact spelling of the data fields. The data cannot be processed if the data fields are spelled incorrectly.

== Overview of the data fields

The following table explains the data fields for the data format **ItemImageReference**. The data fields are listed in alphabetical order:

.Data fields of the data format **ItemImageReference**
[cols="1,3,3"]
|====
|Field |Description |Filter options (tab: Filter)

| **ItemImageID**
|Item image ID
|Select the operator and enter the value.

| **ItemImageItemID**
|Item ID
|Select the operator and enter the value.

| **ItemImageReferenceDelete**
| **1** = Deletes the image availability +
For further information, refer to the **Filter** page of the manual.
|

| **ItemImageReferenceType**
|The image availability type +
**mandant** = Client (store) +
**marketplace** = Referrer +
**listing** = Listing
|Select the operator and enter the value.

| **ItemImageReferenceValue**
|The image availability value +
If **mandant** is displayed as the type, then the ItemImageReferenceValue column contains the **client ID**. +
If **marketplace** is displayed as the type, then the ItemImageReferenceValue column contains the **referrer ID** for the market. +
If **listing** is displayed as the type, then the ItemImageReferenceValue column contains the **referrer ID** for the listing market. +
**-1** = **all**.
|Select the operator and enter the value.

| **ItemImageURL**
|Item image URL
|
|====

== Synchronization fields

The data fields that are listed alphabetically in the following table are available for **data synchronization**. The mandatory synchronization fields have to be selected in order for the synchronization to take place.

.Data fields that can be used for the **synchronization**
[cols="1,3,3"]
|====
|Field |Description |Mandatory synchronization fields (M) and alternatives

| **ItemImageID**
|Item image ID
|M

| **ItemImageReferenceType**
|The image availability type
|

| **ItemImagereferenceValue**
|The image availability value
|
|====
