= ItemImage
:lang: en
include::{includedir}/_header.adoc[]
:position: 10151
:url: data/export-import/data-formats/itemimage
:id: LQK63HJ
:author: team-item

The data format **ItemImage** is used to export item images.
Create and export the data format in the **Data » Dynamic export** menu.
The <<data/export-import/exporting-data#, Exporting data>> page of the manual describes how you export the data format.

Pay close attention to the exact spelling of the data fields. The data cannot be processed if the data fields are spelled incorrectly.

== Overview of the data fields

Table 1 explains the data fields for the **ItemImage** data format in alphabetical order as well as filter options that you set in the **Filter** tab of the data format.

.Data fields of the data format **ItemImage**
[cols="1,3,3"]
|====
|Field name |Explanation |Filter

| **ItemImageID**
|Item image ID
|Activate the filter, select the operator and enter the value.

| **ItemImageItemID**
|Item ID
|Activate the filter, select the operator and enter the value.

| **ItemImageType**
|Image type; only relevant for the export
|Activate the filter and select the image type. +
**INTERNAL** = Images that were saved in the item data record. +
**EXTERNAL** = Image links that were imported via SOAP.

| **ItemImageFileType**
|File format: jpg, jpeg, png, gif or svg
|

| **ItemImageURL**
|Item image URL
|

| **ItemImagePosition**
|Image position +
If no position was set, then the next highest position will be used during the import.
|Activate the filter, select the operator and enter the value.

| **ItemImageLastUpdate**
|Last update
|

| **ItemImageInserted**
|Date when the image was uploaded
|

| **PrimaryVariationCustomNumber**
|Number of the main variation
|

| **AttributeValueID**
|Attribute value ID that links the item image to the attribute value for markets. Image is only transferred to markets for variations with this attribute value.
|

| **ItemImageDelete**
| **1** = Deletes the item image +
Deletes the item image completely and irreversibly when the value 1 is entered. For further information about filters, refer to the <<data/export-import/exporting-data#20, Exporting data>> page of the manual.
|

| **VariationLink**
|Import only. Enter variation IDs to link an image with these variations. Use commas to separate multiple variation IDs.
|
|====

== Overview of the mandatory fields

The following mandatory fields must be available for the data format **ItemImage** and need to have a valid value saved for them:

* **ItemImageItemID**
* **PrimaryVariationCustomNumber**

== Overview of the synchronisation fields

The data fields that are listed in table 2 are available for <<data/export-import/importing-data#25, data synchronisation>>. For mandatory synchronisation fields (M), select the option **Synchronisation** as **Import procedure**. The rest of the fields can also be used for the synchronisation if desired. Alternative synchronisation fields are marked with an **A**.

.Data fields with the import procedure set to **Synchronisation**
[cols="1,3,3"]
|====
|Field name |Explanation |Synchronisation field

| **ItemImageID**
|Item image ID +
This data field is a mandatory synchronisation field when updating images.
|M

| **ItemImageItemID**
|Item ID
|A

| **PrimaryVariationCustomNumber**
|Number of the main variation
|A
|====
