= Characteristic links
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Importing characteristic link, Importing characteristic links, Characteristic link importing, Characteristic links importing, Characteristic link import, Characteristic links import, Import characteristic link, Import characteristic links
:position: 100
:url: data/importing-data/elasticsync-best-practices/best-practices-elasticsync-property-links
:id: EXWPB7O
:author: team-item

== Exporting and importing property links

This chapter describes how to export and import characteristic links.

NOTE: To benefit from this best practice, you should be familiar with the basic functionality of the import tool. Check the <<data/importing-data/ElasticSync#, Using the import tool>> page of the manual for general information about how the plugin works.


[#export_property_links]
=== Exporting characteristic links

==== Creating the format in the FormatDesigner

The characteristics currently linked to variations can be exported using the FormatDesigner. To do so, go to *Data » FormatDesigner* and create a new format of the type *Item*.

After that, select the data fields:

* To allow mapping during import, from the *Item* area select the *ID* of the item or from the *Variation* area select the *ID* or the *Number* of the variation.

* You then add the actual characteristic links in the *VariationProperty* area:

You can select between 3 values:

- *value*: Returns the value of the characteristic mapped in the format.
- *all*: Returns all linked characteristics of an item with values.
- *allIds*: Returns all linked characteristic IDs of an item without any values.

After you have saved the format, you can set up the export in the elastic export.

==== Setting up the export in the elastic export

Go to *Data » Elastic export* to set up the export of the format you created.

To do so, click on *New export* and save a name, the type *Item*, the format you created, a limit and a file name.

[TIP]
.Exporting the file in CSV format
====
If you want to download the file in CSV format, specify the suffix *.csv* as part of the file name.
====

Once you save the format, you are done setting it up.

==== Exporting data

There are several ways of exporting the data:

* In the export, click *Download*.
* Open the URL in a browser.
* In the export overview, click *Download*.

[#import_property_links]
=== Importing characteristic links

==== Creating the import via the import tool

To import the characteristic links, you can go to *Data » Import* and create an import of the type *Item*. Alternatively, you can add the fields to an existing import.

The synchronisation can be based on a variation-specific field, for example the *Variation number*, or based on the *item ID* if the links are created using a separate import.

In the mapping of the import, you can select different fields to create or edit the links. For example, you can add the fields *ID, Value and Language* (you need to add all 3 fields) or instead the field *Characteristics combination*. The latter must be structured as follows in the file:

*InternalName1:Value1:Language;InternalName2:Value2:Language*

If you want to delete characteristic links, use the field *Delete (Yes/No)*. In the file, the value *1* must be specified if the links are to be deleted. Specify the value *0* if you do not want to delete the link.

That is all you need for the link. The import is now ready to go and you can start linking characteristics.
