= ASIN and ePID
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Importing ASIN, Importing ASINs, ASIN importing, ASINs importing, ASIN import, ASINs import, Import ASIN, Import ASINs, ASIN-Import, ASINs-Import, Import-ASIN, Import-ASINs, Importing ePID, Importing ePIDs, ePID importing, ePIDs importing, ePID import, ePIDs import, Import ePID, Import ePIDs, ePID-Import, ePIDs-Import, Import-ePID, Import-ePIDs
:position: 10
:url: data/importing-data/elasticsync-best-practices/best-practices-elasticsync-asin-epid
:id: M534KLI
:author: team-item

== Exporting and importing ASIN and ePID

This chapter describes how to export and import ASIN and ePID data.

NOTE: To benefit from this best practice, you should be familiar with the basic functionality of the import tool. Check the <<data/importing-data/ElasticSync#, Using the import tool>> page of the manual for general information about how the plugin works.

[#export_ASIN_ePID]
=== Exporting ASIN and ePID

==== Creating the format in the FormatDesigner

The ASINs and ePIDs currently linked to variations can be exported using the FormatDesigner. To do so, go to *Data » FormatDesigner* and create a new format of the type *Item*.

After that, select the data fields:

* To allow mapping during import, from the *Variation* area select the *ID* or the *Number* of the variation.

* The actual links are added in the *VariationMarketIdentNumber* area.

You can select 3 values:

- *countryID*: Returns the ID of the country.
- *type*: Returns the type, i.e. ASIN or ePID.
- *value*: Returns the value that was saved for the ASIN or ePID.

The type has to be mapped for all 3 fields. As such, if you want to export all ASINs and ePIDs, every field must be added to the format twice.

After you have saved the format, you can set up the export in the elastic export.

==== Setting up the export in the elastic export

Go to *Data » Elastic export* to set up the export of the format you created.

To do so, click on *New export* and save a name, the type *Item*, the format you created, a limit and a file name.

[TIP]
.Exporting the file in CSV format
====
If you want to download the file in CSV format, specify the suffix *.csv* as part of the file name.
====

Once you save the format, you are done setting it up.

==== Exporting data

There are several ways of exporting the data:

* In the export, click *Download*.
* Open the URL in a browser.
* In the export overview, click *Download*.

[#import_ASIN_ePID]
=== Importing ASIN and ePID

==== Creating the import in the import tool

To import and edit the ASINs and ePIDs, you can go to *Data » Import* and create an import of the type *Item*. Alternatively, you can add the fields to an existing import.

* The synchronisation must be based on a variation-specific field, for example the *Variation number*.

* To *map* the import, in the *ASIN/ePID* area the fields *Country*, *Type* and *Value* must be saved and linked to the columns in the CSV file.

* You need to save the ID of the country and the type must be either ASIN or ePID.

That is all you need for the link. The import is now ready to go and you can start linking properties.
