= Creating parts compatibility listings
:lang: en
include::{includedir}/_header.adoc[]
:keywords: parts compatibility listing, fitment
:position: 50
:url: data/importing-data/elasticsync-best-practices/best-practices-elasticsync-parts-compatibility-listing
:id: LJBIR0F
:author: team-multi-channel

Use the import type *Parts compatibility listing* to create, update or delete parts compatibility listings or individual data sets from parts compatibility listings. This is done in the *Data » Import* menu. +

This best practice provides you with useful tips on what to keep in mind when creating or updating parts compatibility listings with the import type *Parts compatibility listing* via the import tool.

[#100]
== Creating parts compatibility listings

Pay attention to the following if a new parts compatibility listing should be created:

* *Mandatory fields* for the creation of parts compatibility listings via the import tool:
  - Name
  - Referrer ID
  - Category ID
* Name, referrer ID, and category ID must be identical for each data set/list entry to add all data sets in one parts compatibility listing.
* If a data set/list entry already exists in this combination for name, referrer ID, and category ID, then no new parts compatibility listing will be created and there will be no update of an existing parts compatibility listing.
* If no new parts compatibility listing should be created and no vehicle ID is given, then there will be no check whether the vehicle already exists. Instead, the vehicle is newly created. Note that this might lead to doublings.
* If no vehicle ID is given, then a new vehicle is created.

[#200]
== Updating parts compatibility listings

Pay attention to the following if an existing parts compatibility listing should be updated:

* *Mandatory field* for updating an existing parts compatibility listing:
  - Parts compatibility listing ID
* All other values can be specified as desired.
* When a list ID is given, the parts compatibility listing is updated.
* If only list ID and vehicle properties are given, then the vehicle properties are added to the list as a new vehicle.
* If vehicle properties should be updated, first all vehicle properties are deleted and the vehicle properties from the CSV file are added.
* If a vehicle ID is given, the list is updated. Check therefore that the vehicle ID and the parts compatibility listing ID are correct. Otherwise, the wrong list will be updated.
