= Properties
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Exporting property, Exporting properties, Property exporting, Properties exporting, Property export, Properties export, Export property, Export properties, Property-Export, Properties-Export, Export-Property, Export-Properties
:position: 70
:url: data/exporting-data/FormatDesigner/format-types/properties
:author: team-item

////
zuletzt bearbeitet 03.08.2021
////

This page explains the data fields that are available for exporting properties and property groups.
This page serves purely as a reference and assumes that you already have a basic understanding of <<data/exporting-data/FormatDesigner#, FormatDesigner>> and the <<data/exporting-data/elastic-export#, Elastic Export>>.

[TIP]
.Links are not exported
====
This format type exports information about properties and property groups.
It does _not_ export the links between variations and properties, i.e. it does not indicate which properties are linked to which variations.
If you want to export such property links, then use the <<data/exporting-data/FormatDesigner/format-types/item#1600, format type Item>> instead.
====

'''
[#100]
== Group

=== id

The ID of the property group.
The group ID is a unique and continuous number, which is used to clearly identify every property group.

Corresponds to the option in the menu: <<item/settings/properties#1200, Setup » Settings » Properties » Groups » [Open group] » Option: ID>>

[TIP]
Click on icon:sign-in[role="darkGrey"] and decide which property group the ID should be exported for.
Add this field multiple times if you want to export the IDs of several groups.

'''
=== position

The position number of the property group.

Corresponds to the option in the menu: <<item/settings/properties#1200, Setup » Settings » Properties » Groups » [Open group] » Entry field: Position>>

[TIP]
Click on icon:sign-in[role="darkGrey"] and decide which property group the position number should be exported for.
Add this field multiple times if you want to export the positions of several groups.

'''
[#200]
== GroupName

=== description

The description of the property group.

Corresponds to the option in the menu: <<item/settings/properties#1200, Setup » Settings » Properties » Groups » [Open group] » Entry field: Description>>

[TIP]
Click on icon:sign-in[role="darkGrey"] and decide which property group and language the description should be exported for.
Add this field multiple times if you want to export the description of several groups or in several languages.

'''
=== name

The name of the property group.

Corresponds to the option in the menu: <<item/settings/properties#1200, Setup » Settings » Properties » Groups » [Open group] » Entry field: Name>>

[TIP]
Click on icon:sign-in[role="darkGrey"] and decide which property group and language the name should be exported for.
Add this field multiple times if you want to export the name of several groups or in several languages.

'''
[#300]
== Property

=== allGroups

The names of all the groups that the property is assigned to.
The group names are separated by commas.

Corresponds to the option in the menu: <<item/settings/properties#600, Setup » Settings » Properties » Configuration » [Open property] » Area: Groups>>

'''
=== cast

The type of the property.

[cols="1,1"]
|====
|Export values in CSV file |Result in the back end

|`empty`
|None

|`date`
|Date

|`file`
|File

|`int`
|Whole number

|`float`
|Decimal number

|`string`
|Character string

|`html`
|HTML

|`text`
|Text

|`selection`
|Selection

|`multiSelection`
|Multi selection
|====

Corresponds to the option in the menu: <<item/settings/properties#600, Setup » Settings » Properties » Configuration » [Open property] » Option: Type>>

'''
=== id

The ID of the property.
The property ID is a unique and continuous number, which is used to clearly identify every property.

Corresponds to the option in the menu: <<item/settings/properties#600, Setup » Settings » Properties » Configuration » [Open property] » Option: ID>>

'''
=== position

The position number of the property.

Corresponds to the option in the menu: <<item/settings/properties#600, Setup » Settings » Properties » Configuration » [Open property] » Entry field: Position>>

'''
=== typeIdentifier

The section of the property.

[cols="1,1"]
|====
|Export values in CSV file |Result in the back end

|`item`
|Item

|`contact`
|Contact

|`stock`
|Storage location
|====

Corresponds to the option in the menu: <<item/settings/properties#600, Setup » Settings » Properties » Configuration » [Open property] » Option: Section>>

[#400]
== PropertyName

=== description

The description of the property.

Corresponds to the option in the menu: <<item/settings/properties#600, Setup » Settings » Properties » Configuration » [Open property] » Entry field: Description>>

[TIP]
Click on icon:sign-in[role="darkGrey"] and decide which language the description should be exported in.
Add this field multiple times if you want to export the description in several languages.

'''
=== name

The name of the property.

Corresponds to the option in the menu: <<item/settings/properties#600, Setup » Settings » Properties » Configuration » [Open property] » Entry field: Name>>

[TIP]
Click on icon:sign-in[role="darkGrey"] and decide which language the name should be exported in.
Add this field multiple times if you want to export the name in several languages.


'''
[#500]
== custom_value

<<table-fields-custom-values>> lists the fields available for exporting custom values.

[[table-fields-custom-values]]
.Fields for exporting custom values
[cols="1,3"]
|====
|Field |Explanation

|custom_value
|Custom value
|====

[#600]
== date
<<table-field-date>> lists the field available for exporting the current date. For further information, refer to this link:http://php.net/manual/en/function.date.php[page^]{nbsp}icon:external-link[].

[[table-field-date]]
.Field for exporting the current date
[cols="1,3"]
|====
|Field |Explanation

|date
|Current date
|====
