= Setting up REST API
:lang: en
include::{includedir}/_header.adoc[]
:keywords: rest api, interface
:description: Use REST API to communicate with external systems.
:position: 67
:url: data/rest-api
:id: JWGLMYW
:author: team-plugin-core

The term REST API is made up of two acronyms. REST stands for _Representational State Transfer_, API for _application programming interface_. Essentially this means that you can use external calls to communicate with your plentymarkets system in certain ways. This allows you to, for example, retrieve the data of all your contacts at once.

Some examples include link:https://marketplace.plentymarkets.com/plugins/channels/marktplaetze/ebayoauth2_4787[eBay OAuth2^] and link:https://marketplace.plentymarkets.com/plugins/channels/marktplaetze/etsy_4689[Etsy^]{nbsp}icon:external-link[]. For these plugins to work properly, you must grant them certain permissions.

[#end-users]
== For end users

If you want to use plugins that require REST routes, you must grant them permission to access certain parts of your system.

[.instruction]
Creating a Back end user account:

. Go to **Setup » Settings » User » Accounts**.
. Click on **New**. +
→ The **Create new user** window opens.
. Enter the **User name**.
. Enter the **Real name**.
. Enter the **Password**.
. Repeat the password.
. Enter the user's email address. This allows the user to receive messages from the system.
. Select **Back end** as **User access**.
. **Save** the settings.

The user name must not contain any spaces and must have at least 5 characters.

Go to **Setup » Settings » User » Rights » User** to specify which rights to grant the user. No REST API rights are activated by default. Rights are granted separately for different modules and sub-modules of the REST API. Under **Authorisation**, for example, you define whether the REST API user account can display rights or display, create and delete user roles.

To check which rights a plugin requires, see the description of the respective plugin.

[.instruction]
Activating REST API areas:

. Go to *Setup » Settings » User » Rights » User*. +
→ The overview opens.
. Open a user account. +
→ The *Rights* menu item containing the visibilities opens.
. Assign the rights for the respective area by ticking the check boxes. Activate entire areas or expand areas to activate individual rights that the user account should have access to.
. *Save* the settings.

_Note_: The areas *Authorisations* and *Menu visibilities* are linked, which is why the selected rights are automatically activated for both areas.

[#developers]
== For developers

[NOTE]
.Developers site
====

====

If you are interested in developing and selling a plugin that utilizes REST API, you can upload it to the link:https://marketplace.plentymarkets.com/en[plentyMarketplace^] free of charge. In addition to plentymarkets plugins, it is also possible to integrate external offers. link:https://www.plentymarkets.com/dialogue/partners/become-a-partner/[Register here to become a partner.^]{nbsp}icon:external-link[]

See our developers site for link:https://developers.plentymarkets.com/rest-doc/gettingstarted[general information^] on the plentymarkets REST API  as well as the link:https://developers.plentymarkets.com/rest-doc[available routes^]{nbsp}icon:external-link[]. You can also check our tutorials for some examples of how to implement them:
====
* link:https://developers.plentymarkets.com/tutorials/contactdata[Create a contact and an account^]{nbsp}icon:external-link[]
* link:https://developers.plentymarkets.com/tutorials/order-data[Retrieve order data^]{nbsp}icon:external-link[]
* link:https://developers.plentymarkets.com/tutorials/item-data[Create an item^]{nbsp}icon:external-link[]
* link:https://developers.plentymarkets.com/tutorials/bulk-routes[Use bulk routes^]{nbsp}icon:external-link[]
====
