= VariationSupplier
:lang: en
include::{includedir}/_header.adoc[]
:position: 10300
:url: data/export-import/data-formats/variationsupplier
:id: 3ZR2YS0
:author: team-item

Suppliers can be assigned to variations.
The corresponding data is exported with the data format **VariationSupplier**.
Create and export the data format in the **Data » Dynamic export** menu.
The <<data/export-import/exporting-data#, Exporting data>> page of the manual describes how you export the data format.

Pay close attention to the exact spelling of the data fields. The data cannot be processed if the data fields are spelled incorrectly.

== Overview of the data fields

Table 1 explains the data fields for the **VariationSupplier** data format in alphabetical order as well as filter options that you set in the **Filter** tab of the data format.

.Data fields of the data format **VariationSupplier**
[cols="1,3,3"]
|====
|Field name |Explanation |Filter

| **DeleteSupplier**
|Delete supplier +
Value to delete = 1 +
Delete the supplier by marking the field **SupplierRowID** and selecting **Synchronisation**.
|

| **DeliveryTimeInDays**
|Delivery time in days
|

| **Discount**
|Discount
|

| **Discountable**
|Discountable
|

| **ItemName**
|Item name
|

| **LastPriceQuery**
|The date of the last price query +
Format: DD.MM.YYYY
|

| **MinimumOrderValue**
|Minimum order value
|

| **PackagingUnit**
|Packaging unit
|

| **PurchasePrice**
|Purchase price
|

| **SupplierID**
|The supplier's ID +
See: **Customers » Tab: Supplier**
|Activate the filter, select the operator and enter the value.

| **SupplierItemNo**
|The supplier's item number
|

| **SupplierNumber**
|The supplier's number +
See: Tab: **Customer data** of a supplier
|

| **SupplierRowID**
|Unique matching field for the suppliers. It is used if a supplier was saved several times for a variation, e.g. in order to set up different prices for various quantities.
|

| **VariationCustomNumber**
|Variation number
|

| **VariationID**
|Variation ID
|Activate the filter, select the operator and enter the value.

| **Barcode_xxx**
|Barcode +
**__Note__**: The number of the barcode data fields that is displayed here depends on the barcode type that you selected in the **Setup » Item » Barcode** menu. Available barcode types: **GTIN 8**, **GTIN 13**, **GTIN 14**, **GTIN 128**, **ISBN**, **QR**, **CODE 128** und **UPC**.
|Activate the filter, select the operator and enter the value.

| **Export for customer class**
| **__Note__**: filter setting only
|Activate the filter and select the customer class. In order to export data for all customer classes, do not activate the filter. Go to <<crm/managing-contacts#15, Setup » CRM » Classes>> to set up customer classes.
|====

== Overview of the mandatory fields

The following mandatory fields must be available for the data format **VariationSupplier** and need to have a valid value saved for them:

* **SupplierID**
* **VariationID**

== Overview of the synchronisation fields

The data fields that are listed in table 2 are available for <<data/export-import/importing-data#25, data synchronisation>>. For mandatory synchronisation fields, select the option **Synchronisation** as **Import procedure**. The rest of the fields can also be used for the synchronisation if desired. Mandatory synchronisation fields are marked with an **M**.

.Data fields with the import procedure set to **Synchronisation**
[cols="1,3,3"]
|====
|Field name |Explanation |Synchronisation fields

| **Barcode_xxx**
|Barcode, as created in the **Setup » Item » Barcode** menu
|Alternative to **Variation ID**

| **SupplierID**
|Supplier ID
|M

| **SupplierItemNo**
|The supplier's item number
|Alternative to **Variation ID**

| **SupplierNumber**
|The supplier's number
|Alternative to **SupplierID**

| **SupplierRowID**
|Unique matching field
|

| **VariationCustomNumber**
|Variation number
|Alternative to **Variation ID**

| **VariationID**
|Variation ID
|M
|====

[IMPORTANT]
.Deviating import procedure if the supplier was not yet saved for the variation
====
If the supplier was not yet saved for the variation, it is strictly speaking not a synchronisation, but an import. Therefore, when creating the data format, make sure that the data fields **SupplierID** and **VariationID** have the import procedure set to **Import**.
====

== Overview of the procedures

In the **Procedures** tab, select which procedures you want to be carried out during the data export. Activate the **LastPriceQuery** procedure. Select the **set the current date** option from the drop-down list. A timestamp will be added to the supplier data during the import, indicating when the last price query took place.
