= VariationCategories
:lang: en
include::{includedir}/_header.adoc[]
:position: 10260
:url: data/export-import/data-formats/variationcategories
:id: B8M3ONH
:author: team-item

The data format **VariationCategories** is used to export variation category links.
You can also use the data format <<data/export-import/data-formats/variation#, Variation>> to edit category links via data exchange.
The data format **VariationCategories**, however, is especially suited to create or edit multiple links per variation. +
For example, use the format **VariationCategories** to assign category links to newly imported variations.
Once you have imported the new variations, export the category links for your variations.
Open the CSV file and save values for the category links that you want to assign to newly imported variations.

Create and export the data format in the **Data » Dynamic export** menu.
The <<data/export-import/exporting-data#, Exporting data>> page of the manual describes how you export the data format.

Pay close attention to the exact spelling of the data fields. The data cannot be processed if the data fields are spelled incorrectly.

== Important notes

By using the data field **DeleteOld** with the value **1**, it is possible to delete old category links during the import. If you entered several category links per variation and these category links are all in different lines, then only enter the value **1** into the first line (see table 1).

[IMPORTANT]
.Use the data format **Category** for new categories
====
It is not possible to use the data format **VariationCategories** for creating new categories. With the data format **VariationCategories**, you can only create new category links within the variation. Use the data format <<data/export-import/data-formats/category#, Category>> instead to create new categories.
====

== Overview of the data fields

Table 1 explains the data fields for the **VariationCategories** data format in alphabetical order as well as filter options that you set in the **Filter** tab of the data format.

.Data fields of the data format **VariationCategories**
[cols="1,3,3"]
|====
|Field name |Explanation |Filter

| **Categories**
|Categories +
Category IDs are separated by comma. Use hyphens to enter the IDs for category paths.
|

| **CategoryBranches**
|The IDs of the category branches +
Use commas to separate these IDs. It is also possible to save each category link in a different line.
|Activate the filter, select the operator and enter the value.

| **CategoryNameLang**
|The language of the category names
|Activate the filter and select the language from the drop-down list.

| **CategoryNames**
|Category names +
The names of different categories are separated by comma. Use a greater-than symbol to enter path names.
|

| **DeleteOld**
|Delete old category links +
**0** = No +
**1** = Yes +
**__Important__**: If you entered several category links per variation and these category links are all in different lines, then only enter the value 1 into the first line.
|

| **Position**
|Category position
|

| **VariationID**
|Variation ID
|Activate the filter, select the operator and enter the value.
|====
