= VariationAdditionalSKU
:lang: en
include::{includedir}/_header.adoc[]
:position: 10235
:url: data/export-import/data-formats/variationadditionalsku
:id: ETCLIAT
:author: team-item

The data format *VariationAdditionalSKU* is used to export variation SKUs.
Create and export the data format in the *Data » Dynamic export* menu.
The <<data/export-import/exporting-data#, Exporting data>> page of the manual describes how you export the data format.

Pay close attention to the exact spelling of the data fields. The data cannot be processed if the data fields are spelled incorrectly.

== Overview of the data fields

Table 1 explains the data fields for the *VariationAdditionalSKU* data format in alphabetical order as well as filter options that you set in the *Filter* tab of the data format.

.Data fields of the data format *VariationAdditionalSKU*
[cols="1,3,3"]
|====
|Field name |Explanation |Filter

| *Delete*
| *1* = Delete SKU +
Deletes the SKU if the value 1 is entered. The value 0 is transmitted by default. +
|

| *ItemMarking1*
|Flag 1 of the item; 0 = No flag
|Activate the filter and select the operator and the flag.

| *ItemMarking2*
|Flag 2 of the item; 0 = No flag
|Activate the filter and select the operator and the flag.

| *MarketAccountID*
|ID of the market account
|

| *MarketID*
|Market ID
|Activate the filter, select the operator and enter the value.

| *ProducerName*
|Name of the manufacturer
|Activate filter and select name.

| *SKU*
|SKU
|

| *VariationID*
|Variation ID
|

| *PrimaryVariationID*
|Main variation ID
|
|====

== Overview of the mandatory fields

The following mandatory fields must be available for the data format *VariationAdditionalSKU* and have a valid value saved for them:

* *VariationID*
* *MarketID*
* *MarketAccountID*
* *SKU*

== Overview of the synchronisation fields

The data fields that are listed in table 2 are available for <<data/export-import/importing-data#25, data synchronisation>>. These data fields are mandatory synchronisation fields. For mandatory synchronisation fields, select the option *Synchronisation* as *Import procedure*.

.Data fields with the import procedure set to *Synchronisation*
[cols="1,3"]
|====
|Field name |Explanation

| *VariationID*
|Variation ID

| *MarketID*
|Market ID

| *MarketAccountID*
|ID of the market account

| *SKU*
|SKU
|====
