= VariationBundle
:lang: en
include::{includedir}/_header.adoc[]
:position: 10250
:url: data/export-import/data-formats/variationbundle
:id: MFXHUVW
:author: team-item

The data format **VariationBundle** is used to export variation bundles.
Create and export the data format in the **Data » Dynamic export** menu.
The <<data/export-import/exporting-data#, Exporting data>> page of the manual describes how you export the data format.

Pay close attention to the exact spelling of the data fields. The data cannot be processed if the data fields are spelled incorrectly.

== Overview of the data fields

Table 1 explains the data fields for the **VariationBundle** data format in alphabetical order as well as filter options that you set in the **Filter** tab of the data format.

.Data fields of the data format **VariationBundle**
[cols="1,3,3"]
|====
|Field name |Explanation |Filter

| **Quantity**
|Quantity
|

| **VariationID**
|The Variation ID of a bundle component
|Activate the filter, select the operator and enter the value.

| **VariationSourceID**
|The variation ID of the bundle item
|Activate the filter, select the operator and enter the value.
|====

== Overview of the mandatory fields

The following mandatory fields must be available for the data format **VariationBundle** and need to have a valid value saved for them:

* **Quantity**
* **VariationID**
* **VariationSourceID**

== Overview of the synchronisation fields

The data fields that are listed in table 2 are available for <<data/export-import/importing-data#25, data synchronisation>>. These data fields are mandatory synchronisation fields. For mandatory synchronisation fields, select the option **Synchronisation** as **Import procedure**.

.Data fields with the import procedure set to **Synchronisation**
[cols="1,3"]
|====
|Field name |Explanation

| **VariationID**
|The Variation ID of a bundle component

| **VariationSourceID**
|The variation ID of the bundle item
|====
