= VariationBarcode
:lang: en
include::{includedir}/_header.adoc[]
:position: 10240
:url: data/export-import/data-formats/variationbarcode
:id: PL8WIX7
:author: team-item

The data format **VariationBarcode** is used to export barcodes.
Barcodes are created in the **Setup » Item » Barcode** menu.
Create and export the data format in the **Data » Dynamic export** menu.
The <<data/export-import/exporting-data#, Exporting data>> page of the manual describes how you export the data format.

Pay close attention to the exact spelling of the data fields. The data cannot be processed if the data fields are spelled incorrectly.

== Overview of the data fields

Table 1 explains the data fields for the **VariationBarcode** data format in alphabetical order as well as filter options that you set in the **Filter** tab of the data format.

.Data fields of the data format **VariationBarcode**
[cols="1,3,3"]
|====
|Field name |Explanation |Filter

| **BarcodeID**
|ID of barcode
|Activate the filter and select the value from the drop-down list.

| **BarcodeName**
|Barcode name
|

| **BarcodeType**
|Barcode type
|Activate the filter and select the value from the drop-down list.

| **Code**
|Code
|

| **VariationNumber**
|(previously VariationCustomNumber) Variation number
|

| **VariationID**
|Variation ID
|Activate the filter, select the operator and enter the value.
|====

== Overview of the synchronisation fields

The data fields that are listed in table 2 are available for <<data/export-import/importing-data#25, data synchronisation>>. These data fields are mandatory synchronisation fields. For mandatory synchronisation fields, select the option **Synchronisation** as **Import procedure**. At least one of the data fields from the following table must be selected for synchronisation.

.Data fields with the import procedure set to **Synchronisation**
[cols="1,3"]
|====
|Field name |Explanation

| **VariationCustomNumber**
|Variation number
|====
