= VariationMarketLink
:lang: en
include::{includedir}/_header.adoc[]
:position: 10280
:url: data/export-import/data-formats/variationmarketlink
:id: XTK27MX
:author: team-item

Use the data format **VariationMarketLink** to link the variations with markets in order that these variations are available for the market.
Create and export the data format in the **Data » Dynamic export** menu.
The <<data/export-import/exporting-data#, Exporting data>> page of the manual describes how you export the data format.

Pay close attention to the exact spelling of the data fields. The data cannot be processed if the data fields are spelled incorrectly.

== Overview of the data fields

Table 1 explains the data fields for the **VariationMarketLink** data format in alphabetical order as well as filter options that you set in the **Filter** tab of the data format.

[cols="1,3,3"]
|====
|Field name |Explanation |Filter

| **VariationID**
|Variation ID
|Activate the filter, select the operator and enter the value.

| **VariationCustomNumber**
|Variation number
|

| **Client (store)**
|The client's (store) visibility. +
**VISIBLE** = The variation is available for the market. +
**INVISIBLE** = The variation is not available for the market.
|Activate the filter and select the value from the drop-down list.
|====

__Table 1: data fields of the data format **VariationMarketLink**__

== Overview of the mandatory fields

The following mandatory fields must be available for the data format **VariationMarketLink** and need to have a valid value saved for them:

* **VariationID** = ID of the variation
* The market you wish to import

== Overview of the synchronisation fields

The data fields that are listed in table 2 are available for <<data/export-import/importing-data#25, data synchronisation>>. These data fields are mandatory synchronisation fields. For mandatory synchronisation fields, select the option **Synchronisation** as **Import procedure**.

[cols="1,3"]
|====
|Field name |Explanation

| **VariationID**
|Variation ID

|Market
|Select the market you wish to import
|====

__Table 2: data fields with the import procedure set to **Synchronisation**__
