= Variation
:lang: en
include::{includedir}/_header.adoc[]
:position: 10230
:url: data/export-import/data-formats/variation
:id: ZQYE7NM
:author: team-item

The data format **Variation** is used to export variation data.
Create and export the data format in the **Data » Dynamic export** menu.
The <<data/export-import/exporting-data#, Exporting data>> page of the manual describes how you export the data format.

Pay close attention to the exact spelling of the data fields. The data cannot be processed if the data fields are spelled incorrectly.

[#10]
== Important notes

Each variation is given a number (ID) and as such is also uniquely defined by the data field **VariationID**. The following three scenarios could occur for the export and import:

* If the field **VariationID** is neither exported along with the export of variation fields nor imported later on, then new variations will be created with available variation IDs.
* If the data record **VariationID** is exported and later imported again, then changes will be made to the corresponding variations.
* If variation data is imported with variation IDs that do not yet exist in plentymarkets, then new variations will be created with these variation IDs.

If the import procedure **Synchronisation** is selected in the data export settings, then the variation data will be synchronised during the import.

[#20]
== The 1:n problem

The 1:n problem, i.e. one to n, occurs when several characteristics were defined for one variation. The following characteristics can be allocated to a variation multiple times in plentymarkets:

* **Sales prices**

Every sales price is uniquely defined by the field **SalesPriceID**. If this ID is not specified, then a new sales price will always be added and the existing prices will be deleted. If available, the existing price will be changed.

* **Categories**

One variation can be available in multiple categories at the same time. However, if category data fields (CategoryLevel) were entered during the import, then all of the previous category links for this variation will be deleted.

[IMPORTANT]
.Use the data format Category for new categories
====
It is not possible to use the data format **Variation** for creating new categories. With the data format **Variation**, you can only create new category links within the variation. Use the data format <<data/export-import/data-formats/category#, Category>> instead to create new categories.
====

* **Item images**

This data format allows you to import external images with the help of URLs. Existing item images will be replaced in the process. If multiple item images are imported, then these item images have to be separated by a comma without spaces when they are entered. If you do not want to replace the existing images, then import the <<item/managing-items#680, images>> via FTP upload.

[#30]
== Overview of the data fields

Table 1 explains the data fields for the **Variation** data format in alphabetical order as well as filter options that you set in the **Filter** tab of the data format.

.Data fields of the data format **Variation**
[cols="1,3,3"]
|====
|Field name |Explanation |Filter

| **Active**
|Active variations +
**N** = No +
**Y** = Yes
|

| **AttributeValueSetID**
|Internal ID; determines the variation type +
**__Example__**: ID 1 = colour red, size XL; ID 2 = colour green, size XL.
|

| **AutoStockInvisible**
|Automatically invisible in the online store. Set online store to 0 if no stock is available. +
**N** = No +
**Y** = Yes
|

| **AutoStockNoStockIcon**
|The variation's availability icon +
**N** = Has to be deactivated manually +
**Y** = Hide when there is no net stock
|

| **AutoStockPositiveStockIcon**
|The variation's availability icon +
**N** = Has to be activated manually +
**Y** = Display when the net stock is positive
|

| **AutoStockVisible**
|Automatically visible in the online store. Set store to 1 if the stock is available. +
**N** = No +
**Y** = Yes
|

| **Availability**
|Availability of the variation
|

| **AvailableUntil**
| **Available until** +
The setting is found under **Item » Edit item » [Open item] » [Open variation] » Tab: Settings** in the **Availability** area.
|

| **CreatedTimestamp**
|Date and time when the variation was created. Format: dd.mm.yyyy hh:mm +
**__Note__**: The field is only available for the export.
|

| **VariationNumber**
|Variation number
|Activate the filter, select the operator and enter the value.

| **CustomsPercent**
|Percentage of the customs duties
|

| **DeleteVariation**
| **1** = Deletes the variation +
Deletes the variation when the value 1 is entered. +
**__Note:__** Main variations cannot be deleted.
|

| **EstimatedAvailability**
|Availability in supply
|

| **ExternalID**
|External variation ID
|Activate the filter, select the operator and enter the value.

| **ExtraShippingCharge1**
|Extra shipping charge 1
|

| **ExtraShippingCharge2**
|Extra shipping charge 2
|

| **HeightMM**
|Height in mm
|

| **IntervalOrderQuantity**
|Interval order quantity
|

| **isHiddenInCategoryList**
| **Y** = Variation is not visible in item list +
**N** = Variation is visible in item list
|

| **ItemID**
|Unique item ID; maximum numerical value 2^31
|Activate the filter, select the operator and enter the value.

| **LastUpdateTimestamp**
|Last change, date and time. Format: dd.mm.yyyy hh:mm
|

| **LengthMM**
|Length in mm
|

| **LimitOrderByStockSelect**
|Limit variation to stock +
**0** = No limitation +
**1** = Limited to net stock +
**2** = Do not administer stock for this variation
|

| **MainWarehouse**
|The main warehouse's ID reference number. The setting is found under **Item » Edit item » [Open item] » [Open variation] » Tab: Settings** in the **Shipping** area.
|

| **MaximumOrderQuantity**
|Maximum order quantity for one order +
The value **0** is selected by default; with the value **0**, the maximum order quantity is unlimited.
|

| **MinimumOrderQuantity**
|Minimu order quantity per order
|

| **Model**
|Model name
|

| **OperatingCostsPercent**
|Percentage of the entire operating costs
|

| **PackingUnitType**
|Type of packaging for packing units
|

| **PackingUnits**
|Packing units; numerical value
|

| **Picking**
|Order picking
|

| **Position**
|This position number is used to sort the variation within the variation list in the online store.
|

| **PriceCalculationID**
|ID of the calculated price; decimal value
|

| **PurchasePrice**
|Purchase price (net)
|

| **ReleaseDate**
|Release date, format YYYY-MM-DD HH:MM:SS
|

| **StorageCosts**
|Storage costs
|

| **TransportationCosts**
|Transportation costs
|

| **UnitID**
|ID of the unit; ID lists are found in the menu **Setup » Item » Units**.
|

| **UnitContent**
|Quantity contained within the unit
|

| **UnitLoadDevice**
|Pallet type
|

| **UnitsContained**
|Units contained
|

| **VATID**
|ID of the VAT rate
|

| **VariationID**
|Variation ID
|Activate the filter, select the operator and enter the value.

| **VariationName**
|Name of the variation
|

| **VariationAttributes**
|List of the attributes that are linked to the variation; ID list can be found in the menu **Setup » Item » Attributes**
|

| **WeightG**
|The gross weight (with packaging) in grams; numerical value
|

| **WeightNetG**
|The net weight (without packaging) in grams; numerical value
|

| **WidthMM**
|Width in mm
|
|====

[#40]
== Overview of the synchronisation fields

The data fields that are listed in table 2 are available for <<data/export-import/importing-data#25, data synchronisation>>. These data fields are compulsory synchronisation fields. At least one of the data fields from the following table must be selected for synchronisation. For the selected data field, select the option **Synchronisation** as **Import procedure**.

.Data fields with the import procedure set to **Synchronisation**
[cols="1,3"]
|====
|Field name |Explanation

| **VariationNumber**
|Variation number

| **ExternalID**
|External variation ID

| **VariationID**
|Variation ID
|====

[IMPORTANT]
.Field VariationID
====
The field **VariationID** is usually a mandatory synchronisation field. However, this field does not necessarily have to be used for this data format. You can use any of the fields listed. One field is sufficient for the synchronisation.
====
