= Changelog 2. November 2022
:author: kevin-stederoth
:sectnums!:
:page-index: false
:page-aliases: ROOT:changelog.adoc
:startWeekDate: 27. Oktober 2022
:endWeekDate: 2. November 2022

// Ab diesem Eintrag weitermachen: LINK EINFÜGEN

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Aufträge

* Die alte Auftragsherkunft-UI wurde modernisiert. Informationen zu den Neuerungen findest du auf der Handbuchseite xref:auftraege:auftragsherkunft-neu.adoc[Auftragsherkunft^].
* In der Übersicht der neuen Auftrags-UI ist es jetzt möglich, den Status für einen einzelnen Auftrag zu ändern.
* In der Übersicht der neuen Auftrags-UI ist es jetzt möglich, den Warenbestand für die Positionen eines Auftrags anzuzeigen.
* In der neuen Auftrags-UI wurden die Daten eines Auftrags bisher jedes Mal abgerufen, wenn ein Auftrag in der Seitennavigation gewählt wurde. Dies wurde geändert, sodass der Auftrag nur einmal geladen wird und im Cache bleibt, bis:
** die Schaltfläche *Auftrag neu laden* innerhalb der Detailansicht eines Auftrags geklickt wird,
** der Auftrag aus der Seitennavigation entfernt wird
** oder das *Aufträge*-Tab geschlossen wird.

[discrete]
=== Check24

* In den Katalogen für Check24, Check24 Furniture und Check24 Fashion wurden zwei neue Datenfelder zum Verknüpfen von Bildern hinzugefügt: *Bild-URLs* und *Varianten-Bild-URLs*. Die alten Datenfelder zur Verknüpfung von Bildern (*Bild-URL 1-10*) wurden aus den Katalogen entfernt. Mit den neuen Datenfeldern können nun Bilderlisten verknüpft werden. Wenn ein Artikel beispielsweise 2 Artikelbilder und 3 Variantenbilder hat, werden in der CSV-Exportdatei die Spalten für Bilder 1 bis 5 befüllt.
+
[IMPORTANT]
.To-Do
======
Prüfe deine Kataloge für *Check24*, *Check24 Furniture* und *Check24 Fashion* und verknüpfe die neuen Datenfelder zur Übertragung von Bildern.

[cols="1,3"]
.Empfohlene Datenfeld-Zuordnungen
|========
|Datenfeld |Empfohlene Zuordnung

|*Bild-URLs*
|*Bild » Artikel Bilder » Bilderliste*, Bildinformation *Vollbild-URL*

|*Varianten-Bild-URLs*
|*Bild » Varianten Bilder » Bilderliste*, Bildinformation *Vollbild-URL*
|========

Wie du Datenfelder im Katalog verknüpfst, findest du auf der Handbuchseite xref:maerkte:check24.adoc#data-field-mappings[Check24].
======

[discrete]
=== Import

* Ab sofort kannst du einen Live-Import starten und den den Fortschritt in Echtzeit verfolgen. Weitere Informationen findest du auf der Handbuchseite xref:daten:ElasticSync.adoc#import-manual[Import-Tool nutzen].

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Aufträge

* Beim Bearbeiten der Ansicht in der neuen Auftrags-UI konnte der Button zum *Speichern* bei der ersten Anpassung einer Einstellung nicht geklickt werden, sodass die Änderungen nicht gespeichert werden konnten. Dieser Fehler wurde behoben.
* Alte Zahlungsarten wurden in der neuen Auftragsübersicht und in den Auftragsdetails nicht angezeigt. Dieses Verhalten wurde behoben.

[discrete]
=== Prozesse

* In der Aktion *Wareneingang (einfach)* gab es beim Einbuchen von Artikeln sowie beim Drucken von Artikeletiketten ein Problem, wenn am Artikel kein Preis hinterlegt war. Dieses Verhalten wurde behoben.

--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.



--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|
|
|

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

====
