= Changelog 7. September 2022
:author: kevin-stederoth
:sectnums!:
:page-index: false
:startWeekDate: 1. September 2022
:endWeekDate: 7. September 2022

// Ab diesem Eintrag weitermachen: https://forum.plentymarkets.com/t/neuer-emailbuilder-migration-der-alten-vorlagen-new-emailbuilder-migration-of-old-templates/693655

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Amazon

* Für Amazon-Berichte wurde das Menü *Berichte » Verarbeitung* hinzugefügt. Du findest das Menü unter *Einrichtung » Märkte » Amazon » Berichte » Verarbeitung*.
+
In diesem Menü erhältst du einen Überblick über den Verarbeitungsstand deiner Amazon-Berichte. Du kannst dort sehen, welche Berichte bereits verarbeitet wurden und welche Berichte sich noch in der Warteschlange befinden.
+
Außerdem kannst du die Berichte dort auch zurücksetzen oder überspringen. So kannst du festlegen, welche Berichte zuerst verarbeitet werden sollen oder zum Beispiel auch die Auslastung deines Systems reduzieren, indem du Berichte überspringst. Beachte jedoch, dass Berichte, die im Hintergrund bereits von einem Prozess aufgegriffen wurden, in diesem Menü nicht übersprungen werden können. Du kannst die Amazon-Berichte in diesem Menü auch herunterladen.
+
Weitere Informationen zum neuen Berichts-Menü findest du auf der Handbuchseite xref:maerkte:amazon-einrichten.adoc#amazon-berichte-verwalten[Amazon einrichten].
+
[IMPORTANT]
.Hinweis
======
Das neue Menü *Berichte » Verarbeitung* wird zukünftig einige Bereiche des Menüs *Einrichtung » Märkte » Amazon » Datenaustausch » Berichte* ersetzen. Im Moment sind noch beide Menüs verfügbar. Ein Großteil des alten Menüs ist jedoch durch die Abschaltung der MWS-Schnittstelle ohne Funktion.
======

[discrete]
=== Kaufland

* Produkt-Updates werden nun auch über den Katalogexport an Kaufland übertragen. Dabei wird über den Katalog eine CSV-Datei exportiert, die die Produkt-Updates enthält. Diese CSV-Datei wird einmal pro Nacht generiert. Die Felder und Werte der CSV-Datei ergeben sich aus den Zuordnungen in deinem Kaufland-Katalog.
+
Zuvor konnten Produkt-Updates nur über die alte Logik an Kaufland übertragen werden. Da Produkt-Updates jetzt aber auch über den Katalog an Kaufland übertragen werden können, kannst du die Einstellungen für den alten Artikelexport zu Kaufland deaktivieren. Es handelt sich hierbei um die Einstellungen *Artikelexport aktivieren* und *Angebotsabgleich aktivieren* im Menü *Einrichtung » Märkte » Kaufland.de » Einstellungen*. Außerdem müssen beim Katalogexport auch keine Kategorien und Merkmale mehr verknüpft werden. Weitere Informationen dazu findest du auf der Handbuchseite xref:maerkte:kaufland-de-einrichten.adoc#old-export[Kaufland.de einrichten].
+
Das bedeutet, dass nun alle Artikel- und Produktdaten per Katalogexport an Kaufland übertragen werden können. Erstelle deshalb Kataloge für Kaufland, wenn noch nicht geschehen. Wie du einen Katalog für Kaufland erstellst, ist auf der Handbuchseite xref:maerkte:kaufland-de-einrichten.adoc#catalogue-export[Kaufland.de einrichten] beschrieben.
+
[IMPORTANT]
.To-Do
======
Stelle sicher, dass du jede deiner Varianten mit einem Kaufland-Katalog verknüpft hast, bevor du den alten Artikelexport deaktivierst. Wenn du die oben genannten Einstellungen deaktivierst, aber eine Variante nicht mit einem Kaufland-Katalog verknüpft ist, kann diese Variante auch nicht über den Katalog zu Kaufland exportiert werden.
======

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== OTTO

:otto-master-date: 02.09.2022
:otto-master-link: https://forum.plentymarkets.com/uploads/short-url/umPczR9Hg7EpDT3XVugjcyKDaTt.xlsx

include::partial$otto-master-file.adoc[]

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== CRM

* Im Menü *Einrichtung » Mandant » [Mandant wählen] » E-Mail » Vorlagen* hat die Variable `$ItemASIN` keinen Wert ausgegeben, wenn man diese mit der Variable `$ItemListHTML` verwenden wollte. Dieses Verhalten wurde behoben.

[discrete]
=== Prozesse

* In der Aktion *Wareneingang (einfach)* konnte es vorkommen, dass manche Artikel nicht geladen wurden, wenn die Verknüpfung der Artikelbilder fehlerhaft war. Dieses Verhalten wurde behoben.
* In der Aktion *Retoure anlegen/bearbeiten* gab es ein Problem beim Zurückbuchen von Bundles. Dieses Verhalten wurde behoben.

--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== CRM

* In der Kontakt-UI wurde im Bereich *Primäre Adresse* des Kontaktdatensatzes die Funktion zum Kopieren der E-Mail-Adresse und der Telefonnummer hinzugefügt. Mit einem Klick auf die E-Mail-Adresse und die Telefonnummer kopierst du so die Werte aus der primären Rechnungs- und primären Lieferadresse in die Zwischenablage.

[discrete]
=== Kataloge

* Ab sofort kannst du Kataloge über die Detailansicht des Menüs *Daten » Katalogexportstatus* herunterladen. Die Download-Buttons sind nur für den Exporttyp *Async* verfügbar.

[discrete]
=== Prozesse

* Ab sofort gibt es in den Prozessen die Möglichkeit, Tags zu euren Aufträgen hinzuzufügen oder aus euren Aufträgen zu entfernen. Dazu stehen euch fortan zwei Möglichkeiten zur Verfügung.
+
Die erste Möglichkeit befindet sich in der Auftragsabwicklung unter *Aufträge markieren*. Dort könnt ihr die Tags auswählen, die jeweils zu euren Aufträgen hinzugefügt oder daraus entfernt werden sollen.
+
Die zweite Möglichkeit bietet die neue Subaktion *Tags hinzufügen/entfernen* in der Aktion *Auftrag*. Hier könnt ihr auswählen, ob die gewählten Tags zu euren Aufträgen hinzugefügt oder aus den Aufträgen entfernt werden sollen.

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Ereignisaktionen

* Das Ereignis zum Hinzufügen oder Entfernen von Auftrags-Tags greift nun für alle Auftragstypen und ist nicht mehr wie zuvor auf *Nachbestellung*, *Umbuchung* und *Aboauftrag* beschränkt.

[discrete]
=== Prozesse

* Es gab eine interne Anpassung an der Aktion *Versand-Center*. Diese greift nun auf eine andere interne Schnittstelle zu. Die bestehenden Prozesse und Aktionen laufen weiter wie bisher, es bedarf keinerlei Änderungen eurerseits.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Aufträge

* Bei der Ermittlung der Versandkosten für einen Auftrag wurden die Beträge von Bestelleigenschaften nicht berücksichtigt. Dies wurde behoben.

[discrete]
=== Prozesse

* In der Aktion zum Erfassen der Seriennummern gab es ein Problem bei der Anzeige von Artikelbildern. Dieses Verhalten wurde behoben.

--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|link:https://marketplace.plentymarkets.com/avocado_55217[AvocadoStore Connector^]
|1.0.8
|-

|link:https://marketplace.plentymarkets.com/etsy_4689[Etsy^]
|2.1.35
|-

|link:https://marketplace.plentymarkets.com/formatdesigner_6483[FormatDesigner^]
|1.3.9
|-

|link:https://marketplace.plentymarkets.com/mytoys_54776[MyToys^]
|1.0.41
|-

|link:https://marketplace.plentymarkets.com/paypal_4690[PayPal Checkout^]
|6.0.17
|-

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

====
