= Changelog 20. Juli 2022
:author: kevin-stederoth
:sectnums!:
:page-index: false
:startWeekDate: 14. Juli 2022
:endWeekDate: 20. Juli 2022

// Ab dem Eintrag nach diesem weitermachen: https://forum.plentymarkets.com/t/eigner-im-kontaktdatensatz-in-alphabetischer-reihenfolge-owner-in-contact-data-record-sorted-by-alphabet/688411

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== CRM

* Im EmailBuilder wurde eine Funktion zum Kopieren von Vorlagen hinzugefügt. Mit einem Klick auf das Kontextmenü an der Vorlage kopierst du die Vorlage und kannst sie anschließend nach deinen Wünschen anpassen.

[discrete]
=== Ereignisaktionen

* In den Ereignisaktionen wurde ein neuen Filter *Vorhandene Dokumente* hinzugefügt. Mit diesem ist es möglich nach Aufträgen zu Filtern bei denen alle ausgewählten Typen von Auftragsdokumenten vorhanden sind. Weitere Informationen findest du auf der Handbuchseite xref:automatisierung:ereignisaktionen.adoc#events-filters-order[Ereignisaktionen].
* In der Ereignisgruppe Dokumente wurde das neue Ereignis *Dokument generiert* hinzugefügt. Das Ereignis wird ausgelöst wenn eines der ausgewählten Dokumente generiert wird. Es können mehrere Dokumenttypen ausgewählt werden bei denen das Ereignis ausgelöst werden soll. Weitere Informationen findest du auf der Handbuchseite xref:automatisierung:ereignisaktionen.adoc#events-documents[Ereignisaktionen].

[discrete]
=== Fulfillment

* Im Assistenten *eBay Fulfillment by Orange Connex* wurde der Schritt *Outbound-Auftragsdokumente* hinzugefügt. Hier entscheidest du, welche Dokumente zusammen mit dem Outbound-Auftrag übermittelt werden sollen. Zur Auswahl stehen die Dokumente *Lieferschein*, *Rücksendeschein* und *Retourenlabel*.
* Im Versand-Center 2.0 wurden in der Detailansicht im Bereich *Pakete* die Funktionen zum Hinzufügen eines neuen Pakets und zum Löschen eines bestehenden Pakets hinzugefügt. Beim Klick auf das Plus (*Paket hinzufügen*) öffnet sich ein weiteres Fenster, in dem man den Pakettyp, den Typ der Verpackungseinheit und das Paketgewicht festlegen kann.
* Das Erstellen einer Umbuchung im Menü *Waren » Amazon: Shipments* hat nicht funktioniert. Beim Klick auf Umbuchung erstellen hat die Oberfläche nicht reagiert. Dieses Verhalten wurde behoben.

[discrete]
=== Kaufland

* Du kannst Artikeldaten ab sofort per Katalogexport an Kaufland übertragen. Kataloge für Kaufland werden im Menü *Einrichtung » Assistenten » Omni-Channel* mit dem Assistenten *Kaufland - Kataloge* erstellen erstellt.
+
[NOTE]
.Hinweis
======
Für jede Produktkategorie von Kaufland, in der du deine Artikel anbieten möchtest, muss ein eigener Katalog erstellt werden.

Wenn du für eine Kaufland-Produktkategorie noch keinen Katalog erstellt hast, werden Artikel dieser Produktkategorie über den alten Artikelexport zu Kaufland exportiert.

Weitere Informationen zur Erstellung von Katalogen findest du auf der Handbuchseite xref:maerkte:kaufland-de-einrichten.adoc#catalogue-export[Kaufland.de einrichten].
======

[IMPORTANT]
.To-Do
======
Wenn du Artikeldaten mit Katalogen an Kaufland übertragen willst, erstelle Kataloge mit dem Assistenten Kaufland - Kataloge erstellen.

*_Hinweis:_* Momentan können Kataloge für Kaufland nur mit dem Assistenten Kaufland - Kataloge erstellen und nicht über das Menü Daten » Kataloge erstellt werden.

. Öffne das Menü Einrichtung » Assistenten » Omni-Channel.
. Klicke auf den Assistenten Kaufland - Kataloge erstellen.
. Durchlaufe den Assistenten. +
Weitere Informationen zum Assistenten findest du auf der Handbuchseite xref:maerkte:kaufland-de-einrichten.adoc#catalogue-export[Kaufland.de einrichten]. +
→ Im Menü Daten » Kataloge wird ein Katalog für Kaufland erstellt.

Nachdem du den Assistenten durchlaufen hast, wird im Menü *Daten » Kataloge* ein Katalog für Kaufland erstellt. In diesem Katalog verknüpfst du anschließend in plentymarkets gespeicherte Artikeldaten mit den Datenfeldern von Kaufland. So legst du fest, welche Artikeldaten an Kaufland übertragen werden sollen.
======

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== CRM

* Im Menü *Einrichtung » Einstellungen » Benutzer » Konten* im Tab *Eigner* wurde die Option *Kunde* in *Kontakt* umbenannt.
* Das Feld *FSK* in den Adressoptionen im Menü *CRM » Kontakte* war bisher ein Eingabefeld, in das man die Altersfreigabe manuell eintragen konnte. Wir haben das Feld *FSK* umbenannt in *Altersfreigabe* und in eine Dropdown-Liste mit vorgegebenen Werten umgewandelt. Diese Liste ist nun identisch mit den Dropdown-Listen in der Rechnungsadresse des Auftrags sowie in den Ereignisaktionen.

[discrete]
=== Kaufland

* Für Lager und Versandprofile gibt es in den Kaufland-Katalogen jetzt komplexe Zuordnungen. Es handelt sich um die folgenden Datenfelder:
** `id_shipping_group`: Hier verknüpfst du Versandprofile.
** `id_warehouse`: Hier verknüpfst du Lager.

+
Bei komplexen Zuordnungen gibt es für ein Marktplatz-Datenfeld verschiedene Werte zur Auswahl, die zugeordnet werden können. Bei der Zuordnung von Versandprofilen kannst du also zum Beispiel verschiedene Kaufland-Versandprofile auswählen, die du deinen plentymarkets Versandprofilen zuordnest. Weitere Informationen zur komplexen Zuordnung und zu den neuen Datenfeldern findest du auf der Handbuchseite xref:maerkte:kaufland-de-einrichten.adoc#data-field-mappings[Kaufland.de einrichten].

[discrete]
=== OTTO

:otto-master-date: 15.07.2022
:otto-master-link: https://forum.plentymarkets.com/uploads/short-url/2wHq1kpv52EKksABCZ0itWjTxGZ.xlsx

include::partial$otto-master-file.adoc[]

[discrete]
=== plentyShop

* Im Zuge der Vereinfachung des plentymarkets Backends wurden einige Einstellungen im Systembaum an andere Stellen bewegt. Dabei handelt es sich zunächst nur um Einstellungen, die für plentyShops relevant sind oder für dessen Vorgänger Callisto relevant waren. Es handelt sich dabei ausschließlich um kosmetische/organisatorische Änderungen. Die folgenden Einstellungen/Menüs wurden an anderer Stelle im Systembaum untergebracht, um Einstellungen kund:innenfreundlicher zu bündeln. Die folgende Tabelle listet die Änderungen an den Einstellungen auf:
+
[cols="2"]
|======
|Alter Pfad |Neuer Pfad

|Einrichtung » Mandant » Global » Live-Shopping
|Einrichtung » plentyShop » Globale Einstellungen » Live-Shopping

|Einrichtung » Mandant » Global » Dienste » Facettensuche
|Einrichtung » plentyShop » Globale Einstellungen » Suche » Facettensuche

|Einrichtung » Mandant » (Mandanten wählen) » Version
|Einrichtung » Mandant » Global » Version

|Einrichtung » Mandant » (Mandanten wählen) » Webshop » Webshop sperren
|Einrichtung » Mandant » Global » Webshop » Shop sperren

|Einrichtung » Mandant » (Mandanten wählen) » SEO
|Einrichtung » plentyShop » (Mandanten wählen) » SEO

|Einrichtung » Mandant » (Mandanten wählen) » Kategorien » Rabatte
|Einrichtung » plentyShop » (Mandanten wählen) » Kategorierabatte

|Einrichtung » Mandant » (Mandanten wählen) » Dienste » Facettenverknüpfung
|Einrichtung » plentyShop » (Mandanten wählen) » Facettenverknüpfung
|======

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== CRM

* In der Vorschau im EmailBuilder gab es einen Anzeigefehler bei den Variablen `Datum des Auftragseingangs` und `Datum und Uhrzeit des Auftragseingangs`:
** Bei der Variable `Datum des Auftragseingangs` wurde zusätzlich die Zeit mit angezeigt.
** Die Variable `Datum und Uhrzeit des Auftragseingangs` wurde in der Vorschau gar nicht angezeigt.

+
Dieses Verhalten wurde behoben. Die Variablen werden nun mit den korrekten Werten in der Vorschau angezeigt.
* In einigen Fällen konnte es vorkommen, dass beim Öffnen der Vorschau oder beim Senden der Vorlage im Menü *Aufträge » Aufträge bearbeiten* ein Fehler angezeigt wurde. Die E-Mail-Vorschau und der Versand der Vorlage funktionierten nicht. Außerdem gab es Fälle, in denen die E-Mail-Vorlage nicht gespeichert werden konnte, wenn man versuchte Variablen wie Rechnungsadresse oder Lieferadresse zu verwenden. Dieses Verhalten wurde behoben.
* Wenn man die Telefonnummer nachträglich in den Adressoptionen und den Kontaktoptionen im Menü *CRM » Kontakte* ändern wollte und diese einen Bindestrich enthält, wurde ein Fehler angezeigt und die geänderte Telefonnummer konnte nicht gespeichert werden. Dieses Verhalten wurde behoben.
* Wenn man im EmailBuilder 2 statische Anhänge an die Vorlage anhängen wollte, wurde nur der zweite Anhang versendet. Dieses Verhalten wurde behoben.
* Wenn man im Kontaktdatensatz im Menü *CRM » Kontakte* eine bereits gespeicherte Bewertung von beispielsweise 2 Sternen auf 0 Sterne ändern wollte, konnte diese Änderung nicht gespeichert werden. Dieses Verhalten wurde behoben.
* In einigen Systemen wurde ein Validierungsfehler angezeigt, wenn man im Kontaktdatensatz im Menü *CRM » Kontakte* Änderungen, beispielsweise an den Eigenschaften oder Kontaktoptionen, vorgenommen hat. Außerdem gab es in einigen Systemen Probleme mit Eigenschaften, die als Pflichtfeld gekennzeichnet waren.
+
Dieses Verhalten wurde behoben. Wenn es einen Fehler beim Speichern der Eigenschaften gibt, wird nun angezeigt, welche Eigenschaft fehlerhaft ist. Der Fehler, dass man die Option *Pflichtfeld* bei den Eigenschaften nicht ändern konnte, wurde behoben.
* Bei einigen Kunden wurden die Tickets mit einer mehrstündigen Verzögerung importiert. Dies wurde dadurch verursacht, dass der Import-Cron mehrfach gleichzeitig gestartet wurde. Dieses Verhalten wurde behoben.
+
Auch wenn eine E-Mail vom Import übersprungen wurde (z. B. weil sie von einem Mailer-Daemon generiert wurde), blieb die E-Mail als nicht gelesen und der Import-Cron versuchte erneut, sie zu importieren, wenn er das nächste Mal ausgeführt wurde. Dieses Verhalten wurde geändert, die E-Mail wird nun als gelesen markiert.
* Beim Erstellen neuer Kontakte wurden in der Bezirksauswahl initial immer die deutschen Bundesländer angezeigt. Dieser Fehler wurde behoben, sodass die Bezirke nun zur Vorauswahl des Landes passen.
* Wenn eine EmailBuilder-Vorlage für einen anderen als den Standardmandanten erstellt wurde, konnte die Vorlage nicht in der Auftrags-UI als Vorschau angezeigt oder gesendet werden. Dieses Verhalten wurde behoben.

[discrete]
=== Ereignisaktionen

* Bei der Ereignisaktion *Mail versenden* kam es zu einem Fehler wodurch keine Mail versendet werden konnte, wenn es sich bei dem Auftrag um eine Umbuchung gehandelt hat. Dies wurde behoben.

'''

[discrete]
== Gelöscht

Folgende Funktionalität wurde in den letzten 7 Tagen von *{version}* gelöscht.

[discrete]
=== Payment

* Wie in link:https://forum.plentymarkets.com/t/update-abschaltung-alte-benutzeroberflaeche-zahlungsverkehr-announcement-abandonment-of-old-user-interface-payments/655278[diesem Beitrag^] angekündigt, wurde die alte Bedienoberfläche *Zahlungsverkehr* aus dem Menü *Aufträge* entfernt.

[discrete]
=== plentyShop

* Im Zuge der Vereinfachung des plentymarkets Backends haben wir einige veraltete Menüpfade und Einstellungen entfernt. Dabei handelt es sich zunächst nur um Einstellungen, die für plentyShops relevant sind oder für dessen Vorgänger Callisto relevant waren. Es handelt sich dabei ausschließlich um kosmetische/organisatorische Änderungen; durch das Entfernen von Menüs werden keine Funktionalitäten entfernt. Die folgenden Einstellungen wurden aus dem plentymarkets Backend entfernt:
** Einrichtung » Mandant » Global » Sprachpakete
** Einrichtung » Mandant » Global » Feedback
** Einrichtung » Mandant » Global » Geschenke
** Einrichtung » Mandant » Global » Gewinnspiel
** Einrichtung » Mandant » Global » Dienste » bit.ly
** Einrichtung » Mandant » Global » Dienste » Dropbox
** Einrichtung » Mandant » Global » Dienste » Facebook
** Einrichtung » Mandant » Global » Dienste » Familienkarte
** Einrichtung » Mandant » Global » Dienste » Lionbridge
** Einrichtung » Mandant » Global » Dienste » Picalike
** Einrichtung » Mandant » Global » Dienste » Testberichte.de
** Einrichtung » Mandant » Global » Dienste » Twitter
** Einrichtung » Mandant » Global » Dienste » Dropbox
** Einrichtung » Mandant » (Mandanten wählen) » Webshop » Währung (kann im plentyShop-Assistenten eingestellt werden)
** Einrichtung » Mandant » (Mandanten wählen) » Webshop » Weiterleitung
** Einrichtung » Mandant » (Mandanten wählen) » Webshop » Seiten
** Einrichtung » Mandant » (Mandanten wählen) » Webshop » Artikelsuche
** Einrichtung » Mandant » (Mandanten wählen) » Artikelansichten » Verfügbarkeit
** Einrichtung » Mandant » (Mandanten wählen) » Kategorien
** Einrichtung » Mandant » (Mandanten wählen) » Kategorien » Einstellungen
** Einrichtung » Mandant » (Mandanten wählen) » Kategorien » Aktivieren
** Einrichtung » Mandant » (Mandanten wählen) » Bestellvorgang » DHL Packstation
** Einrichtung » Mandant » (Mandanten wählen) » Mein Konto » Auftragsinformationen
** Einrichtung » Mandant » (Mandanten wählen) » Dienste
** Einrichtung » Mandant » (Mandanten wählen) » Affiliate
** Einrichtung » Mandant » (Mandanten wählen) » Module

--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== CRM

* Im EmailBuilder wurden Abonnement-bezogene Variablen hinzugefügt. Diese neuen Variablen befinden sich als Unterkategorie *Abonnement* in der Kategorie *Auftrag*.

[discrete]
=== Ereignisaktionen

* Wir haben die fehlende Aktion *Stornobeleg Mahnung erzeugen* hinzugefügt.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Artikel

* Aufgrund von leeren Spracheinträgen in den Texteigenschaften kam es vor, dass die Änderungserkennung in der neuen Artikel-UI direkt beim Öffnen einer Variante aktiv wurde. Wir haben dieses Verhalten nun korrigiert.

[discrete]
=== CRM

* Die Dropdown-Liste Eigner im Bereich *Kontaktdetails* des Kontaktdatensatzes im Menü *CRM » Kontakte* war bisher anhand der Benutzer-ID sortiert. Ab sofort sind die Benutzer:innen in der Dropdown-Liste *Eigner* in alphabetischer Reihenfolge sortiert.

--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|link:https://marketplace.plentymarkets.com/persistentshoppingcart_55154[Bleibender Warenkorb^]
|1.0.6
|-

|link:https://marketplace.plentymarkets.com/customerclasshomepage_6067[Customer Class HomePage^]
|2.2.8
|-

|link:https://marketplace.plentymarkets.com/googletagmanagerultimate_54789[Google Tag Manager + Conversions API - 18 Tools in einem^]
|1.3.0
|-

|link:https://marketplace.plentymarkets.com/cfourmanufacturersliderwidget_6905[Hersteller Slider Widget^]
|1.0.5
|-

|link:https://marketplace.plentymarkets.com/elasticexportidealode_4723[idealo.de^]
|3.3.33
|-

|link:https://marketplace.plentymarkets.com/mirakl_6917[Mirakl Connector^]
|1.1.70
|-

|link:https://marketplace.plentymarkets.com/multicontentwidget_6082[Multicontent Toolbox^]
|4.7.17
|-

|link:https://marketplace.plentymarkets.com/paypal_4690[PayPal Checkout^]
|6.0.13
|-

|link:https://marketplace.plentymarkets.com/shopify_4944[Shopify.com^]
|2.12.1
|-

|link:https://marketplace.plentymarkets.com/d2gpmpluginsocialicons_55170[Social Icons Widget^]
|1.0.1
|-

|link:https://marketplace.plentymarkets.com/d2gpmpluginshippingicons_6756[Versand Icons Widget^]
|1.0.4
|-

|link:https://marketplace.plentymarkets.com/d2gpmpluginpaymenticons_7033[Zahlungs Icons Widget^]
|1.0.7
|-

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

====
