= Changelog 6. Juli 2022
:author: kevin-stederoth
:sectnums!:
:page-index: false
:page-aliases: ROOT:changelog.adoc
:startWeekDate: 30. Juni 2022
:endWeekDate: 6. Juli 2022

// Ab diesem Eintrag weitermachen: LINK EINFÜGEN

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Artikel

* Wir haben den Bilderupload in der neuen Artikel-UI vereinheitlicht und im gleichen Zug die Buttons zum Umschalten in den Uploadmodus und den Übersetzungsmodus entfernt.

[discrete]
=== Dokumente

* Wir haben Hinweise hinzugefügt, wie viele Zeichen für den Startwert und den Nummernkreis erlaubt sind. Somit können nicht mehr als die erlaubte Anzahl an Zeichen in den Eingabefelder eingetragen werden.

[discrete]
=== Prozesse

* In der Auftragssuche / Auftragsauswahl wurde bei den Adressen keine Firma und kein Kundenname angezeigt. Diese werden nun angezeigt, sofern sie in der Adresse angegeben sind.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Aufträge

* In der alten UI wurde für die Auftragsanlage die ausgewählte Herkunft nicht übernommen, wenn eine Auftragsvorlage verwendet wurde.

[discrete]
=== CRM

* Wenn man im Menü *CRM » Kontakte* zum Beispiel einen Filter für die Kundenklasse und einen für die Kontaktdaten gesetzt hatte, konnte es in manchen Fällen vorkommen, dass die Sortierung der PLZ nicht funktionierte. Dieses Verhalten wurde behoben.

[discrete]
=== Prozesse

* In der Aktion Retouren anlegen/bearbeiten wurde bei der Artikelauswahl kein GTIN-Code angezeigt. Dieser Fehler wurde behoben.

[discrete]
=== Warenwirtschaft

* Das Verknüpfung von Lagerorteigenschaften während sie erstellt werden ist nun wieder möglich. Zusätzlich wurde ein Fehler in der Gruppenfunktion zum Verknüpfung dieser Eigenschaften behoben.

--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.



--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|
|
|

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

====
