= Changelog 26. Oktober 2022
:author: kevin-stederoth
:sectnums!:
:page-index: false
:page-aliases: ROOT:changelog.adoc
:startWeekDate: 20. Oktober 2022
:endWeekDate: 26. Oktober 2022

// Ab diesem Eintrag weitermachen: LINK EINFÜGEN

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== CRM

* Im Assistenten *E-Mail-Konten* im Menü *Einrichtung » Assistenten » Grundeinrichtung* wurde im Schritt *Signatur* ein weiteres Textfeld hinzugefügt, in dem du die Signatur im reinen Textformat speichern kannst.

[discrete]
=== Ereignisaktionen

* In den Ereignisaktionen gibt es nun das neue Ereignis *Auftragsadresse geändert*, das ausgelöst wird, wenn der Inhalt einer Auftragsadresse geändert oder eine andere Adresse zugewiesen wird. Dabei kannst du einstellen, auf welchen Adresstyp im Ereignis reagiert werden soll: Rechnungs-, Lieferadresse oder beide Adressen.

[discrete]
=== Prozesse

* In der Aktion *Artikelerfassung* gibt es nun eine neue Option, mit der du einstellen kannst, ob in der Detailansicht die Rechnungs- oder Lieferadresse eines Auftrags angezeigt werden soll.

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== CRM

* Wie im Changelog vom 6. Juli 2022 beschrieben, wurde die Reihenfolge der Anzeige im Suchfeld der Kontakte-UI angepasst (erst Name, dann ID). Aufgrund einer Änderung an der Komponente wurde die geänderte Reihenfolge wieder rückgängig gemacht. Dieses Verhalten wurde nun behoben: Die Reihenfolge im Suchfeld der Kontakte-UI zeigt nun wieder an erster Stelle den Namen und dann die ID.

--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.



--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|
|
|

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

====
