= Changelog 14. September 2022
:author: kevin-stederoth
:sectnums!:
:page-index: false
:startWeekDate: 8. September 2022
:endWeekDate: 14. September 2022

// Ab diesem Eintrag weitermachen: https://forum.plentymarkets.com/t/aenderungen-im-systembaum-pos-changes-to-the-system-tree-pos/694390

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Amazon

* Die Auftragsherkunft *Amazon Belgium* wurde hinzugefügt. Damit wirst du deine Artikel in Zukunft auch auf Amazon in Belgien anbieten können.
+
[NOTE]
.Hinweis
======
Amazon hat den Marktplatz noch nicht gestartet. Das bedeutet, dass du momentan noch keine Artikel auf Amazon in Belgien verkaufen kannst.
======

[discrete]
=== CRM

* In der Kontakt-UI wurde im Bereich *Primäre Adresse* des Kontaktdatensatzes die Funktion zum Kopieren der E-Mail-Adresse und der Telefonnummer hinzugefügt. Mit einem Klick auf die E-Mail-Adresse und die Telefonnummer kopierst du so die Werte aus der primären Rechnungs- und primären Lieferadresse in die Zwischenablage.

[discrete]
=== Kataloge

* Ab sofort kannst du Kataloge über die Detailansicht des Menüs *Daten » Katalogexportstatus* herunterladen. Die Download-Buttons sind nur für den Exporttyp *Async* verfügbar.

[discrete]
=== Prozesse

* Ab sofort gibt es in den Prozessen die Möglichkeit, Tags zu euren Aufträgen hinzuzufügen oder aus euren Aufträgen zu entfernen. Dazu stehen euch fortan zwei Möglichkeiten zur Verfügung.
+
Die erste Möglichkeit befindet sich in der Auftragsabwicklung unter *Aufträge markieren*. Dort könnt ihr die Tags auswählen, die jeweils zu euren Aufträgen hinzugefügt oder daraus entfernt werden sollen.
+
Die zweite Möglichkeit bietet die neue Subaktion *Tags hinzufügen/entfernen* in der Aktion *Auftrag*. Hier könnt ihr auswählen, ob die gewählten Tags zu euren Aufträgen hinzugefügt oder aus den Aufträgen entfernt werden sollen.

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Ereignisaktionen

* Das Ereignis zum Hinzufügen oder Entfernen von Auftrags-Tags greift nun für alle Auftragstypen und ist nicht mehr wie zuvor auf *Nachbestellung*, *Umbuchung* und *Aboauftrag* beschränkt.

[discrete]
=== Prozesse

* Es gab eine interne Anpassung an der Aktion *Versand-Center*. Diese greift nun auf eine andere interne Schnittstelle zu. Die bestehenden Prozesse und Aktionen laufen weiter wie bisher, es bedarf keinerlei Änderungen eurerseits.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Aufträge

* Bei der Ermittlung der Versandkosten für einen Auftrag wurden die Beträge von Bestelleigenschaften nicht berücksichtigt. Dies wurde behoben.

[discrete]
=== Prozesse

* In der Aktion zum Erfassen der Seriennummern gab es ein Problem bei der Anzeige von Artikelbildern. Dieses Verhalten wurde behoben.

--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== CRM

* Die neue Version des EmailBuilder wurde veröffentlicht und bietet die folgenden Features:
** Mehrsprachigkeit
** Sprachabhängige Einstellungen von den globalen Einstellungen getrennt
** Vorlagen für andere Sprachen kopieren
** Eigner und Mandant einer Vorlage zuweisen
** Filter, um nach Vorlagen suchen zu können
** komplette Vorlagen mit allen Sprachen und Einstellungen kopieren
** Vorlagen verschieben / Ordner verschieben

+
Alle alten Vorlagen, die ihr bereits im Menü *Einrichtung » Mandant » [Mandant wählen] » E-Mail » Vorlagen* erstellt habt, werden in diesem Zuge automatisch in den EmailBuilder migriert.

+
[IMPORTANT]
.To-Do
======
* Prüfe die Inhalte der migrierten Vorlagen.
* Prüfe in deinem gesamten plentymarkets System alle Stellen, an denen du E-Mail-Vorlagen verknüpft hast, die automatisiert versendet werden.
* Wenn du in der vorherigen Version des EmailBuilder bereits mehrsprachige Vorlagen angelegt hast, musst du diese manuell überführen.

Weitere Informationen findest du im link:https://forum.plentymarkets.com/t/neue-funktionen-des-emailbuilders-inkl-migration-bestehender-vorlagen-new-features-of-emailbuilder-incl-migration-of-existing-templates/693489#new-features-of-the-emailbuilder-including-migration-of-existing-templates-9[Forum^] und auf der Handbuchseite xref:crm:emailbuilder.adoc[EmailBuilder (Testphase)].
======

[discrete]
=== Fulfillment

* Ab sofort ist die neue Paketinhaltsliste im Menü Aufträge » Paketinhaltsliste (Testphase) verfügbar. Weitere Informationen findest du in im link:https://forum.plentymarkets.com/t/ankuendigung-neue-paketinhaltsliste-announcement-new-package-content-list/693629[Forum^] und auf der Handbuchseite xref:fulfillment:paketinhaltsliste-testphase.adoc[Paketinhaltsliste (Testphase)]. Die alte Paketinhaltsliste wurde in diesem Zuge als *veraltet* gekennzeichnet.

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Benutzeroberfläche

* In allen Ansichten, in denen die Schnellsuche vorhanden ist, wird nun direkt eine Suche ausgeführt, sobald Du zu Deinem eingegebenen Stichwort einen vorgeschlagenen Filter auswählst. Solltest Du mehrere Filter für Deine Suche benötigen, kannst Du diese wie gehabt im Filter-Menü setzen.

[discrete]
=== CRM

* Die folgenden Menüpunkte wurden im Menü *Einrichtung » Mandant » [Mandant wählen] » E-Mail* entfernt:
** *Zugangsdaten*
** *Signatur*
** *Infodienst*

+
Du kannst diese Einstellungen ab sofort nur noch im Assistenten *E-Mail-Konten* vornehmen. Du findest den Assistenten im Menü *Einrichtung » Assistenten » Grundeinrichtung*.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== CRM

* Wenn man im Kontaktdatensatz im Bereich Kontaktdetails die Zahlungsart Lastschrift aktiviert hat, wurde diese Aktion nicht gespeichert. Dieses Verhalten wurde behoben.

'''

[discrete]
== Gelöscht

Folgende Funktionalität wurde in den letzten 7 Tagen von *{version}* gelöscht.

[discrete]
=== plentyShop

* Im Zuge der Vereinfachung des plentymarkets Backends haben wir einige weitere veraltete Menüpfade und Einstellungen entfernt. Dabei handelt es sich zunächst nur um Einstellungen, die für plentyShops relevant sind oder für dessen Vorgänger Callisto relevant waren. Es handelt sich dabei ausschließlich um kosmetische/organisatorische Änderungen; durch das Entfernen von Menüs werden keine Funktionalitäten entfernt! Die folgenden Einstellungen wurden aus dem plentymarkets Backend entfernt:
** Einrichtung » Mandant » (Mandanten wählen) » Webshop » Multilingual » Bereich
** Einrichtung » Mandant » (Mandanten wählen) » Webshop » Multilingual » Automatische Spracherkennung
** Einrichtung » Mandant » (Mandanten wählen) » Artikelansichten » Einstellungen » Artikelanzeige
** Einrichtung » Mandant » (Mandanten wählen) » Artikelansichten » Einstellungen » Attribut-Verfügbarkeit
** Einrichtung » Mandant » (Mandanten wählen) » Artikelansichten » Einstellungen » Sortierung der Artikelkategorien (Ebene 1)
** Einrichtung » Mandant » (Mandanten wählen) » Artikelansichten » Einstellungen » Sortierung der Artikelkategorien (Ebene 2)
** Einrichtung » Mandant » (Mandanten wählen) » Artikelansichten » Einstellungen » Automatische Sortierung nach monatlichen Verkäufen
** Einrichtung » Mandant » (Mandanten wählen) » Bestellvorgang » Einstellungen » Artikelpaket
** Einrichtung » Mandant » (Mandanten wählen) » Bestellvorgang » Einstellungen » Standard-Lieferland
** Einrichtung » Mandant » (Mandanten wählen) » Bestellvorgang » Einstellungen » Grundpreis
** Einrichtung » Mandant » (Mandanten wählen) » Bestellvorgang » Einstellungen » Zahlungsinformation
** Einrichtung » Mandant » (Mandanten wählen) » Bestellvorgang » Einstellungen » Versandart
** Einrichtung » Mandant » (Mandanten wählen) » Bestellvorgang » Einstellungen » Newsletter-Anmeldung im Bestellvorgang
** Einrichtung » Mandant » (Mandanten wählen) » Bestellvorgang » Einstellungen » IP-Adresse des Käufers
** Einrichtung » Mandant » (Mandanten wählen) » Bestellvorgang » Einstellungen » Angabe Lieferdatum
** Einrichtung » Mandant » (Mandanten wählen) » Bestellvorgang » Einstellungen » Externe Umsatzsteuer-ID-Prüfung

--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|link:https://marketplace.plentymarkets.com/proslider_55225[18BITS PRO SLIDER^]
|1.0.3
|-

|link:https://marketplace.plentymarkets.com/cfourcustomcssjs_5143[Custom CSS/JS im Frontend^]
|2.0.7
|-

|link:https://marketplace.plentymarkets.com/easycredit_5109[easyCredit-Ratenkauf^]
|2.0.4
|-

|link:https://marketplace.plentymarkets.com/extendedimagecarouselwidget_55287[Erweiterter Bilder-Karussell Widget^]
|1.0.1
|-

|link:https://marketplace.plentymarkets.com/edon_6618[FairGeben^]
|1.4.0
|-

|link:https://marketplace.plentymarkets.com/mirakl_6917[Mirakl Connector^]
|1.2.3
|-

|link:https://marketplace.plentymarkets.com/mytoys_54776[MyToys^]
|1.0.45
|-

|link:https://marketplace.plentymarkets.com/wishlistwidgets_55040[Optimierte Wunschliste + Widget^]
|1.0.4
|Wenn die Wunschlisten-Artikel weiterhin überschrieben werden sollen, muss die Checkbox in der Plugin-Konfiguration neu gesetzt werden.

|link:https://marketplace.plentymarkets.com/woocommerce_5102[woocommerce.com^]
|3.0.9
|-

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

====
