= Changelog 19. Oktober 2022
:author: kevin-stederoth
:sectnums!:
:page-index: false
:page-aliases: ROOT:changelog.adoc
:startWeekDate: 13. Oktober 2022
:endWeekDate: 19. Oktober 2022

// Ab diesem Eintrag weitermachen: LINK EINFÜGEN

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Kataloge

* Wenn du einen Katalog öffnest, wird in der Navigation links unter *Filter* in Klammern angezeigt, wie viele Filter für den Katalog gesetzt sind. Bisher enthielt die angezeigte Zahl auch die Template-Filter, also die Filter, die automatisch gesetzt werden. Ab sofort ist das anders: Jetzt werden die Template-Filter nicht mehr berücksichtigt. Wenn du neben *Filter* also zum Beispiel eine 2 siehst, hast du selbst zwei Filter für diesen Katalog gesetzt.

[discrete]
=== UI

* Ergebnisse der Eingaben in Filter-Menüs werden allgemein durch sogenannte Chips dargestellt. Das Verhalten dieser Chips wurde vereinheitlicht, sodass die Ergebnisse nach dem Absenden der Filter-Eingaben angezeigt bzw. aktualisiert werden. Beispiele sind zu finden in den Menüs *Einrichtung » Aufträge » Eigenschaftskopie* oder *Artikel » Artikel-UI*.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Aufträge

* Beim Duplizieren von Aufträgen wurden bei Gutscheinen die internen Referenzen nicht gesetzt. Dadurch konnten die Gutscheine bei Retouren nicht in die Artikelpreise eingerechnet werden. Dies wurde behoben.

[discrete]
=== Payment

* Bei der Auswahl von Filtern im Menü Zahlungsverkehr ließ sich das Fenster nicht bis zum Suchen-Button nach unten scrollen, so dass die Filter nicht gesetzt werden konnten. Dieser Fehler ist nun behoben.

--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.



--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|
|
|

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

====
