= Changelog 29. Juni 2022
:author: kevin-stederoth
:sectnums!:
:page-index: false
:page-aliases: ROOT:changelog.adoc
:startWeekDate: 23. Juni 2022
:endWeekDate: 29. Juni 2022

// Ab diesem Eintrag weitermachen: https://forum.plentymarkets.com/t/plentyshop-basket-variable-wird-aus-dem-globalcontext-entfernt-basket-variable-is-removed-from-the-globalcontext/685718

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Kaufland.de

* Du kannst ab jetzt mehrere Konten für Kaufland einrichten. Im Menü *Einrichtung » Märkte » Kaufland.de » Einstellungen » [Kaufland-Konto öffnen]* wurden dazu die Tabs Konten und Neues Konto hinzugefügt.
** Im Tab *Konten* werden alle Konten angezeigt, die du für Kaufland eingerichtet hast. +
*_Hinweis:_* Momentan wird hier nur ein Konto angezeigt, da du bisher nur ein Konto für Kaufland in plentymarkets einrichten konntest. Hier wird also nur dein bisheriges Kaufland-Konto angezeigt.
** Im Tab *Neues Konto* kannst du ein neues Konto für Kaufland hinzufügen.

+
Du kannst für jedes Konto, das du für Kaufland einrichtest, einen Anzeigenamen vergeben. Das Konto wird dann unter diesem Namen im Tab *Konten* angezeigt. Der Anzeigename wird nur in deinem plentymarkets System verwendet und dient einer besseren Übersicht.
* Außerdem wurde im Menü *Einrichtung » Märkte » Kaufland.de » Einstellungen » Tab: Konten » [Kaufland-Konto öffnen]* die Einstellung *Konfiguration für alte Aufträge verwenden* hinzugefügt.
Diese Einstellung ist für dein bisheriges Kaufland-Konto standardmäßig aktiviert. Damit wird sichergestellt, dass Aufträge, die vor dem Update auf Kaufland generiert wurden, in plentymarkets verarbeitet werden können. Für neue Kaufland-Konten ist diese Einstellung nicht relevant und deshalb in einer neuen Konfiguration standardmäßig deaktiviert.
+
[NOTE]
.Kein To-Do
======
Du musst keine weiteren Schritte vornehmen. Alle Einstellungen deines Kaufland-Kontos bleiben auch nach dem Update bestehen. Du findest dein Kaufland-Konto jetzt im Menü *Einrichtung » Märkte » Kaufland.de » Einstellungen » Tab: Konten*.

Weitere Informationen findest du auf der Handbuchseite xref:maerkte:kaufland-de-einrichten.adoc#200[Kaufland.de einrichten].
======

[discrete]
=== Prozesse

* In den Prozessen wurden neue Dokumente als Aktion zur Verfügung gestellt. Diese können für die Generierung sowie für den Druck und das Speichern verwendet werden. Die folgenden Dokumente sind nun verfügbar:
** Externe Gutschrift
** Externe Rechnung
** Stornobeleg Mahnung
** Stornobeleg Gutschrift
** Stornobeleg Rechnung

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== OTTO

:otto-master-date: 24.06.2022
:otto-master-link: https://forum.plentymarkets.com/uploads/short-url/iv12Ss7JR1TdUGu8nhv0GjUtIgN.xlsx

include::partial$otto-master-file.adoc[]

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Artikel

* Es gibt nun wieder eine Fehlermeldung im Log, wenn eine Preiskalkulation eine Eigenschaft nutzt, die nicht mit der Variante verknüpft ist.

[discrete]
=== Aufträge

* Es war bei den Auftragsvorlagen nicht möglich einen Status mit mehr als 2 Nachkommastellen auszuwählen.
* Die Fehlermeldungen in der Status-UI wurden nun wieder angezeigt und der Text wurde angepasst.

[discrete]
=== Kataloge

* Im Katalogformat *Warenbestand* werden die Einstellungen zum Dezimaltrennzeichen nun korrekt beachtet.

[discrete]
=== Prozesse

* Die Subaktion *Speichern* blieb bei einigen Dokumenten bei 92% stehen und der Prozess wurde nicht weiter ausgeführt. Dieser Fehler wurde behoben und betraf nur beta und early.

--

early::
+
--

:version: early

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Artikel

* Wir haben den Bilderupload in der neuen Artikel-UI vereinheitlicht und im gleichen Zug die Buttons zum Umschalten in den Uploadmodus und den Übersetzungsmodus entfernt.

[discrete]
=== Dokumente

* Wir haben Hinweise hinzugefügt, wie viele Zeichen für den Startwert und den Nummernkreis erlaubt sind. Somit können nicht mehr als die erlaubte Anzahl an Zeichen in den Eingabefelder eingetragen werden.

[discrete]
=== Prozesse

* In der Auftragssuche / Auftragsauswahl wurde bei den Adressen keine Firma und kein Kundenname angezeigt. Diese werden nun angezeigt, sofern sie in der Adresse angegeben sind.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Aufträge

* In der alten UI wurde für die Auftragsanlage die ausgewählte Herkunft nicht übernommen, wenn eine Auftragsvorlage verwendet wurde.

[discrete]
=== CRM

* Wenn man im Menü *CRM » Kontakte* zum Beispiel einen Filter für die Kundenklasse und einen für die Kontaktdaten gesetzt hatte, konnte es in manchen Fällen vorkommen, dass die Sortierung der PLZ nicht funktionierte. Dieses Verhalten wurde behoben.

[discrete]
=== Prozesse

* In der Aktion Retouren anlegen/bearbeiten wurde bei der Artikelauswahl kein GTIN-Code angezeigt. Dieser Fehler wurde behoben.

[discrete]
=== Warenwirtschaft

* Das Verknüpfung von Lagerorteigenschaften während sie erstellt werden ist nun wieder möglich. Zusätzlich wurde ein Fehler in der Gruppenfunktion zum Verknüpfung dieser Eigenschaften behoben.

--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|link:https://marketplace.plentymarkets.com/cfourcustomcssjs_5143[Custom CSS/JS im Frontend^]
|2.0.6
|-

|link:https://marketplace.plentymarkets.com/etsy_4689[Etsy^]
|2.1.17
|-

|link:https://marketplace.plentymarkets.com/formatdesigner_6483[FormatDesigner^]
|1.3.6
|-

|link:https://marketplace.plentymarkets.com/elasticexportidealode_4723[idealo.de^]
|3.3.32
|-

|link:https://marketplace.plentymarkets.com/elasticexportkaufluxde_4737[kauflux.de^]
|1.1.10
|-

|link:https://marketplace.plentymarkets.com/klarna_6731[Klarna^]
|2.4.5
|-

|link:https://marketplace.plentymarkets.com/mirakl_6917[Mirakl Connector^]
|1.1.68
|-

|link:https://marketplace.plentymarkets.com/novalnet_5231[Novalnet^]
|2.3.1
|-

|link:https://marketplace.plentymarkets.com/paypal_4690[PayPal Checkout^]
|6.0.9
|-

|link:https://marketplace.plentymarkets.com/shopify_4944[Shopify.com^]
|2.11.0
|-

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

Dokumentation::
+
--

[discrete]
=== Handbuch

* Du kannst ab jetzt auf knowledge.plentymarkets.com und developers.plentymarkets.com zwischen verschiedenen Themes wechseln.

--

====
