= Changelog 06. April 2022
:author: kevin-stederoth
:sectnums!:
:page-index: false
:page-aliases: ROOT:changelog.adoc
:startWeekDate: 31. März 2022
:endWeekDate: 06. April 2022

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{{version}}* veröffentlicht.

[discrete]
=== Ereignisaktionen

* Die Ereignisaktionen wurden um das Ereignis *Gelangensbestätigung generiert* erweitert.
* Die Ereignisaktionen wurden um das Ereignis *Sammelrechnung generiert* erweitert.
* Die Ereignisaktionen wurden um das Ereignis *Sammelgutschrift generiert* erweitert.

[discrete]
=== Kelkoo

* Ab sofort kannst du Artikeldaten mit einem Katalog an das Preisportal Kelkoo exportieren. Das Marktplatz-Format Kelkoo findest du jetzt im Menü *Daten » Kataloge*.
+
[NOTE]
.Du exportierst schon Artikeldaten zu Kelkoo über den elastischen Export?
======
* Merkmale und Freitextfelder können für den Katalogexport nicht mehr verwendet werden. Prüfe deshalb, welche Merkmale du aktuell für das Preisportal verwendest. Erstelle Eigenschaften für alle Merkmale, die du weiterhin benötigst.
* Beim Wechsel solltest du deinen alten Elastischen Export exakt in dem neuen Katalog nachbauen, damit der Artikelexport weiterhin funktioniert. Ordne also alle Datenfelder so zu, wie sie auch im Elastischen Export an das Preisportal übertragen wurden. Wenn du bestimmte Datenfelder anders als bisher zuordnest, werden möglicherweise beim Export neue Artikel erstellt.
* Wie du einen Katalog für Kelkoo einrichtest, erfährst du wie immer im xref:maerkte:kelkoo.adoc[plentymarkets Handbuch].
======

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{{version}}* veröffentlicht.



'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{{version}}* behoben.

[discrete]
=== Aufträge

* Szenario: Auftrag hat eine Fremdwährung, die Zahlung ist in Systemwährung hinterlegt. Für die Berechnung des bezahlten Betrags wurde dann die Zahlung mit dem tagesaktuellem Wechselkurs in die Währung des Auftrags umgerechnet. Das konnte dazu führen, dass der Auftrag nicht exakt zu 100% bezahlt ist. Es wird nun die Zahlung mit dem Wechselkurs des Auftrags umgerechnet.
* Beim Öffnen einer Nachbestellung wurde die Statushistorie nicht geladen. Dies ist nun behoben.

[discrete]
=== Dokumente

* Der Wert von Bestelleigenschaften vom Typ *Kein* wurde auf den Auftragsdokumenten ausgegeben. Das ist falsch, denn solche Bestelleigenschaften können keinen Wert haben. Wurde aber trotzdem ein Wert bei der Auftragsanlage angegeben, wurde dieser Wert ausgegeben. Nun wird ein möglicherweise vorhandener Wert einer solchen Bestelleigenschaft einfach ignoriert und nicht auf dem Auftragsdokument ausgegeben.

[discrete]
=== Prozesse

* Innerhalb der Aktion *Wareneingang (einfach)* konnte ein Problem auftreten, wenn mehr als 200 Varianten nachgeladen werden sollen. Dieses Verhalten wurde behoben.
* Die Ergebnisliste innerhalb der Aktion *Wareneingang (einfach)* wurde zu klein dargestellt. Wir haben die Standard-Feldbreiten erhöht, sodass die Ergebnisse nun besser sichtbar sind. Diese Anpassung betrifft nur Benutzer, die die Tabelle nicht bereits selbst angepasst haben, also die Standardansicht verwenden.

--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{{version}}* veröffentlicht.



'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf **{{version}}** veröffentlicht.



'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{{version}}* behoben.



--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|
|
|

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

====
