= Changelog 9. November 2022
:author: kevin-stederoth
:sectnums!:
:page-index: false
:page-aliases: ROOT:changelog.adoc
:startWeekDate: 3. November 2022
:endWeekDate: 9. November 2022

// Ab diesem Eintrag weitermachen: LINK EINFÜGEN

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Aufträge

* In der neuen Auftrags-UI ist jetzt möglich, den Artikelnamen, das Gewicht, die Länge und die Breite in der Artikeltabelle zu bearbeiten. Diese Möglichkeit steht dir im zweiten Schritt der Auftragsanlage oder in der Ansicht Artikel bearbeiten eines Auftrags zur Verfügung.
* Im Bearbeitungsmodus für die Auftragsübersicht wurde eine Einstellung hinzugefügt, um die Tabelle der Auftragspositionen für alle Aufträge immer ausgeklappt anzuzeigen.
* In der Auftragsübersicht der neuen Auftrags-UI ist es jetzt möglich, einen neuen Auftrag anzulegen.
* Die Benutzeroberfläche zum Erstellen von Aufträgen wurde überarbeitet. In diesem Schritt wurde die Möglichkeit hinzugefügt, Gastbestellungen anzulegen und nach Kontakten zu suchen.
* Beim Erstellen von Gutschriften und Gewährleistungen in der neuen Auftrags-UI ist jetzt möglich, die Versandkosten anzupassen.
* In der Übersicht der neuen Auftrags-UI kannst du jetzt definieren, welche Menüfunktionen für Aufträge direkt als Icon angezeigt werden sollen und welche Funktionen im Kontextmenü verfügbar sein sollen.
* In der Übersicht der neuen Auftrags-UI ist es jetzt möglich, die Paketnummern anzuzeigen, den Tracking-Link zu öffnen und das Versand-Center zu öffnen.

[discrete]
=== Payment

* Es ist nun möglich, Zahlungen nicht nur unter Verwendung der Auftrags-ID, sondern auch anhand der Rechnungsnummer zuzuordnen. Wähle dazu im 3-Punkte-Menü die entsprechende Option aus.

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Payment

* Wenn du dir im Menü Zahlungsverkehr die Filter anzeigen lässt, werden diese nun in zwei Spalten statt wie bisher in einer angezeigt. Dadurch wird verhindert, dass der Suchen-Button unerreichbar wird. Zusätzlich wurden die Filter überarbeitet, sodass nun der Abfrageoperator bei den Filtern selbst gewählt werden kann. So ist es bspw. Möglich nach mehreren Zahlungsarten gleichzeitig zu filtern.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Aufträge

* Es war möglich, eine Auftragseigenschaft mit einem leerem String zu aktualisieren. Dies wurde behoben. Auftragseigenschaften mit leeren Strings werden nun beim Aktualisieren und Anlegen ignoriert.

[discrete]
=== CRM

* Im Kontaktdatensatz gab es ein Problem beim Speichern der Schaltflächen zum Erlauben bzw. Nicht-erlauben der Zahlungsarten *Lastschrift* und *Rechnung* im Portlet *Kontaktdetails*. Dieses Verhalten wurde behoben.

--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.



--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|
|
|

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

====
