= Changelog 14. September 2022
:author: kevin-stederoth
:sectnums!:
:page-index: false
:page-aliases: ROOT:changelog.adoc
:startWeekDate: 8. September 2022
:endWeekDate: 14. September 2022

// Ab diesem Eintrag weitermachen: LINK EINFÜGEN

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== CRM

* In der Kontakt-UI wurde im Bereich *Primäre Adresse* des Kontaktdatensatzes die Funktion zum Kopieren der E-Mail-Adresse und der Telefonnummer hinzugefügt. Mit einem Klick auf die E-Mail-Adresse und die Telefonnummer kopierst du so die Werte aus der primären Rechnungs- und primären Lieferadresse in die Zwischenablage.

[discrete]
=== Kataloge

* Ab sofort kannst du Kataloge über die Detailansicht des Menüs *Daten » Katalogexportstatus* herunterladen. Die Download-Buttons sind nur für den Exporttyp *Async* verfügbar.

[discrete]
=== Prozesse

* Ab sofort gibt es in den Prozessen die Möglichkeit, Tags zu euren Aufträgen hinzuzufügen oder aus euren Aufträgen zu entfernen. Dazu stehen euch fortan zwei Möglichkeiten zur Verfügung.
+
Die erste Möglichkeit befindet sich in der Auftragsabwicklung unter *Aufträge markieren*. Dort könnt ihr die Tags auswählen, die jeweils zu euren Aufträgen hinzugefügt oder daraus entfernt werden sollen.
+
Die zweite Möglichkeit bietet die neue Subaktion *Tags hinzufügen/entfernen* in der Aktion *Auftrag*. Hier könnt ihr auswählen, ob die gewählten Tags zu euren Aufträgen hinzugefügt oder aus den Aufträgen entfernt werden sollen.

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Ereignisaktionen

* Das Ereignis zum Hinzufügen oder Entfernen von Auftrags-Tags greift nun für alle Auftragstypen und ist nicht mehr wie zuvor auf *Nachbestellung*, *Umbuchung* und *Aboauftrag* beschränkt.

[discrete]
=== Prozesse

* Es gab eine interne Anpassung an der Aktion *Versand-Center*. Diese greift nun auf eine andere interne Schnittstelle zu. Die bestehenden Prozesse und Aktionen laufen weiter wie bisher, es bedarf keinerlei Änderungen eurerseits.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Aufträge

* Bei der Ermittlung der Versandkosten für einen Auftrag wurden die Beträge von Bestelleigenschaften nicht berücksichtigt. Dies wurde behoben.

[discrete]
=== Prozesse

* In der Aktion zum Erfassen der Seriennummern gab es ein Problem bei der Anzeige von Artikelbildern. Dieses Verhalten wurde behoben.

--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.



--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|
|
|

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

====
