= Changelog 9. November 2022
:author: kevin-stederoth
:sectnums!:
:page-index: false
:startWeekDate: 3. November 2022
:endWeekDate: 9. November 2022

// Ab diesem Eintrag weitermachen: https://forum.plentymarkets.com/t/auftrags-ui-testphase-fix-fuer-zahlungsbedingungen-order-ui-test-phase-fix-for-payment-terms/700969

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Aufträge

* In der neuen Auftrags-UI ist jetzt möglich, den Artikelnamen, das Gewicht, die Länge und die Breite in der Artikeltabelle zu bearbeiten. Diese Möglichkeit steht dir im zweiten Schritt der Auftragsanlage oder in der Ansicht Artikel bearbeiten eines Auftrags zur Verfügung.
* Im Bearbeitungsmodus für die Auftragsübersicht wurde eine Einstellung hinzugefügt, um die Tabelle der Auftragspositionen für alle Aufträge immer ausgeklappt anzuzeigen.
* In der Auftragsübersicht der neuen Auftrags-UI ist es jetzt möglich, einen neuen Auftrag anzulegen.
* Die Benutzeroberfläche zum Erstellen von Aufträgen wurde überarbeitet. In diesem Schritt wurde die Möglichkeit hinzugefügt, Gastbestellungen anzulegen und nach Kontakten zu suchen.
* Beim Erstellen von Gutschriften und Gewährleistungen in der neuen Auftrags-UI ist jetzt möglich, die Versandkosten anzupassen.
* In der Übersicht der neuen Auftrags-UI kannst du jetzt definieren, welche Menüfunktionen für Aufträge direkt als Icon angezeigt werden sollen und welche Funktionen im Kontextmenü verfügbar sein sollen.
* In der Übersicht der neuen Auftrags-UI ist es jetzt möglich, die Paketnummern anzuzeigen, den Tracking-Link zu öffnen und das Versand-Center zu öffnen.

[discrete]
=== Elastischer Export

* Im Elastischen Export wurden für den Formattyp *Kontakte* die Felder *createdAt* und *updatedAt* hinzugefügt. Dieses Update ist verfügbar ab Plugin-Version 1.3.10 des link:https://marketplace.plentymarkets.com/formatdesigner_6483[FormatDesigner^]-Plugins.

[discrete]
=== Payment

* Es ist nun möglich, Zahlungen nicht nur unter Verwendung der Auftrags-ID, sondern auch anhand der Rechnungsnummer zuzuordnen. Wähle dazu im 3-Punkte-Menü die entsprechende Option aus.

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Payment

* Wenn du dir im Menü Zahlungsverkehr die Filter anzeigen lässt, werden diese nun in zwei Spalten statt wie bisher in einer angezeigt. Dadurch wird verhindert, dass der Suchen-Button unerreichbar wird. Zusätzlich wurden die Filter überarbeitet, sodass nun der Abfrageoperator bei den Filtern selbst gewählt werden kann. So ist es bspw. Möglich nach mehreren Zahlungsarten gleichzeitig zu filtern.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Aufträge

* Es war möglich, eine Auftragseigenschaft mit einem leerem String zu aktualisieren. Dies wurde behoben. Auftragseigenschaften mit leeren Strings werden nun beim Aktualisieren und Anlegen ignoriert.
* In der neuen Bearbeitungsansicht von Artikeln in der Auftrags-UI (Testphase) wurden die Artikel nicht mehr geladen, wenn eine Variante entfernt wurde. Dieser Fehler wurde behoben.

[discrete]
=== CRM

* Im Kontaktdatensatz gab es ein Problem beim Speichern der Schaltflächen zum Erlauben bzw. Nicht-erlauben der Zahlungsarten *Lastschrift* und *Rechnung* im Portlet *Kontaktdetails*. Dieses Verhalten wurde behoben.
* Bei der Ausgabe der Werte der Variablen im EmailBuilder, die Beträge und Summen enthalten, kam es zu einem Fehler bei den Nachkommastellen. Dieses Verhalten wurde behoben.
* Bei der Verwendung eines SMTP-Server Alias für den E-Mail-Versand, kam es zu einem Fehler bei der Zertifikats-Überprüfung: `Unable to connect with STARTTLS: stream_socket_enable_crypto(): Peer certificate CN='[...]' did not match expected CN='[...]'`. Dieses Verhalten wurde behoben.

[discrete]
=== Plugins

* Nach einer erfolgreichen Bereitstellung eines Plugin-Sets war es möglich, dass der Button für eine erneute Bereitstellung temporär ausgegraut war und damit eine Bereitstellung nicht möglich war. Dieses Verhalten wurde behoben. Das bedeutet für dich, dass nach einer Bereitstellung sofort eine neue Bereitstellung gestartet werden kann.

--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== CRM

* Im EmailBuilder wurden im Bereich *Globals* die folgenden Variablen hinzugefügt:
** Allgemeine Geschäftsbedingungen im HTML-Format
** Allgemeine Geschäftsbedingungen im reinen Textformat

+
Diese Variablen geben den gesamten Text der AGB aus wie im Menü *Einrichtung » Mandant » [Mandant wählen] » Webshop » Rechtliches* gespeichert.

[discrete]
=== Payment

* Im Menü *Zahlungsverkehr* wurden folgende Spalten neu hinzugefügt:
** *Transaktionscode*
** *Referenz-ID*
** *Transaktionstyp*

+
Diese Kategorien waren bereits als Filter vorhanden, können nun aber auch nach Wunsch als Spalten hinzugefügt werden.
* Außerdem wurden folgende Spalten neu hinzugefügt:
** *Zahlungsart-ID*
** *Zahlungsart-Symbol*
** *Name der Zahlungsart*

+
Diese Informationen sind weiterhin in der Spalte Zahlungsart verfügbar, können nun aber auch als separate Spalten dargestellt werden. Standardmäßig sind die neuen Spalten deaktiviert. Über die Einstellungen (*Spalten konfigurieren*) kannst du sie aktivieren.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Aufträge

* Bei dem Exportformat für Zahlungen in den Katalogen (*Daten » Kataloge*) kam es bei der Verwendung von dem Datenformat CSV und Datenfeldern bei denen der Export Key einen Punkt beinhaltete zu einer fehlerhaften Darstellung. Dies wurde behoben.

[discrete]
=== CRM

* Im Portlet *Aufträge* im Kontaktdatensatz wurde der falsche Mandant in der Spalte *Herkunftsname* angezeigt. Dieses Verhalten wurde behoben.

--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|link:https://marketplace.plentymarkets.com/emarketing_6198[emarketing - Google Shopping, Microsoft Advertising, Facebook Ads & Instagram^]
|1.1.11
|-

|link:https://marketplace.plentymarkets.com/elasticexportfashionde_4742[Fashion.de^]
|1.0.16
|-

|link:https://marketplace.plentymarkets.com/formatdesigner_6483[FormatDesigner^]
|1.3.10
|-

|link:https://marketplace.plentymarkets.com/io_4696[IO^]
|5.0.56
|-

|link:https://marketplace.plentymarkets.com/metro_6600[Metro^]
|2.2.7
|-

|link:https://marketplace.plentymarkets.com/mirakl_6917[Mirakl Connector^]
|1.2.6
|-

|link:https://marketplace.plentymarkets.com/mollie_6272[Mollie^]
|2.8.18
|-

|link:https://marketplace.plentymarkets.com/mytoys_54776[myToys^]
|1.0.55
|-

|link:https://marketplace.plentymarkets.com/paypal_4690[PayPal Checkout^]
|6.1.1
|-

|link:https://marketplace.plentymarkets.com/ceres_4697[plentyShop LTS^]
|5.0.56
a| * Die ShopBuilder-Inhalte für Bestellbestätigungsseiten müssen im Menü *CMS » ShopBuilder* über die Schaltfläche *Inhalte neu generieren* aktualisiert werden.
* Falls du Gastkund:innen die Möglichkeit geben willst, einen neuen Auftragsbestätigungslink anzufordern, musst du dafür eine neue E-Mail-Vorlage erstellen und verknüpfen. Weitere Informationen findest du auf der xref:webshop:shop-builder.adoc#softlogin[ShopBuilder-Handbuchseite].
* Im Zuge des Releases von Ceres 5.0.56 gab es Änderungen an Template-Dateien, die für Theme-Entwickler:innen relevant sind. Die Verlinkung führt direkt zu der umgesetzten Änderung in den entsprechenden Dateien.
** link:https://github.com/plentymarkets/plugin-ceres/pull/3340/files#diff-1b8d2c7ce7416f660f89d11ad8e368be614c2b98efc30526e74286c7f180c3b8[resources/views/Category/Item/Partials/Pagination.twig^]
** link:https://github.com/plentymarkets/plugin-ceres/pull/3339/files#diff-82affb09026a21fd94995e057ae7214f6751cf84dfed718216f4760865567c33[resources/views/Widgets/OrderConfirmation/OrderDataWidget.twig^]

|link:https://marketplace.plentymarkets.com/shopify_4944[Shopify.com^]
|2.12.7
|-

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

====
