= Changelog 14. Dezember 2022
:author: kevin-stederoth
:sectnums!:
:page-index: false
:page-aliases: ROOT:changelog.adoc
:startWeekDate: 8. Dezember 2022
:endWeekDate: 14. Dezember 2022

// Ab diesem Eintrag weitermachen: LINK EINFÜGEN

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Aufträge

* In der Auftragsübersicht der neuen Auftrags-UI wird nun bei einem Statuswechsel für einen einzelnen Auftrag der aktuelle Status vorausgewählt.
* Es wurde eine Einstellung für das Standard-Lager in der Auftragsanlage hinzugefügt.

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Aufträge

* In der UI der Auftragsherkünfte wurde die Möglichkeit integriert, die HerkunftsID bei der Anlage einer neuen Herkunft selbst zu bestimmen.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Aufträge

* In der neuen UI zur Auftragsanlage wurden Varianten bei der Wahl einer Vorlage im ersten Schritt in der falschen Menge zum Warenkorb hinzugefügt. Dies wurde behoben, sodass nun die korrekte Varianten-Menge aus der Auftragsvorlage übernommen wird.
* In der Variantensuche im 2. Schritt der neuen Auftragsanlage und in der Ansicht zum Bearbeiten von Artikeln in der neuen Auftrags-UI ist nun eine Teilsuche für Variantennummern möglich.
* Nach dem Löschen einer Auftragsposition in einem Lieferauftrag war diese Position im Hauptauftrag für einen neuen Lieferauftrag nicht wieder verfügbar. Dies wurde behoben.
* Die Verlinkung zu Umbuchungen in Warenbewegungen hat nicht funktioniert. Dies wurde behoben.
* Bei der Verarbeitung von Lieferaufträgen konnte es zu Fehlern kommen, wenn im Auftrag Artikelpakete mit Bestelleigenschaften vorhanden waren. Dies wurde behoben.
* In der neuen Auftragsanlage und in der neuen Auftrags-UI (Testphase) fehlten die Werte für die Attribute-Spalte in der Variantensuche. Dies wurde behoben.
* Bei Änderung der Mengen in der Variantensuche (Step 2) wurde bei der erneuten Preiskalkulation die Kundenklasse nicht beachtet. Dies wurde behoben.
* Die Markierung *Nicht im Bestand* wurde in der Variantensuche (Step 2) nicht korrekt angezeigt. Dies wurde behoben.

[discrete]
=== CRM

* Wenn man bei einem Lieferland die Einstellung *Lieferant aktiv* im Menü *Einrichtung » Aufträge » Versand » Optionen* im Tab *Lieferländer* gewählt hatte, war dieses Lieferland in den Adressen eines Kontakts des Typs *Lieferant* nicht verfügbar. Dieses Verhalten wurde behoben.

[discrete]
=== Dokumente

* Beim Drucken von Dokumenten als Sammeldokument kam es zu einem Fehler, wenn nur ein Dokument verfügbar war. Dies wurde behoben.

[discrete]
=== Fulfillment

* Im neuen Versand-Center wurde in bestimmten Fällen das falsche Produktbild für Varianten angezeigt: Es wurde standardmäßig das erste Bild angezeigt statt das Bild, das der Variante entspricht. Dieser Fehler wurde behoben.

--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.



--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|
|
|

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

====
