= Changelog 30. November 2022
:author: kevin-stederoth
:sectnums!:
:page-index: false
:page-aliases: ROOT:changelog.adoc
:startWeekDate: 24. November 2022
:endWeekDate: 30. November 2022

// Ab diesem Eintrag weitermachen: LINK EINFÜGEN

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Änderungshistorie

* Der Änderungshistorie wurde die Komponente speicherbare Filter hinzugefügt. Damit kannst du ab sofort Filter speichern und wiederverwenden.

[discrete]
=== Aufträge

* In der neuen Auftrags-UI wurde der Filter für das Kundenzeichen zu den Filtern in der Auftragssuche hinzugefügt. Dieser Filter ist optional und kann in den *MyView*-Einstellungen aktiviert werden.
* In der neuen Auftrags-UI kannst du im Bereich Allgemein eines Auftrags ab sofort den Handelsvertreter wählen. Außerdem kannst du das Feld Handelsvertreter in der Tabelle der Auftragsübersicht hinzufügen und somit nach Aufträgen eines Handelsvertreters filtern.
* In der neuen Auftragsanlage wurden die folgenden Felder zum ersten Schritt eines neuen Auftrags hinzugefügt:
** Skontofrist (Tage)
** Skonto (%)
** Valuta (Tage)
** Zahlungsziel (Tage)

[discrete]
=== CRM

* Bei der Auswahl von E-Mail-Vorlagen in Nachbestellungen, Ereignisaktionen (Aufträge und Ticketsystem), Aktionsmanager (Aufträge und Ticketsystem), Gruppenfunktionen, Messenger, Ticketsystem, Aufträge-UI, Assistenten *E-Mail-Konten* und *Messenger-Konfiguration* und in den Prozessen wurde die Anzeige der E-Mail-Vorlagen nach folgendem Muster vereinheitlicht:
+
--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.



--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|
|
|

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

====
