= Changelog 31. August 2022
:author: kevin-stederoth
:sectnums!:
:page-index: false
:page-aliases: ROOT:changelog.adoc
:startWeekDate: 25. August 2022
:endWeekDate: 31. August 2022

// Ab diesem Eintrag weitermachen: LINK EINFÜGEN

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== plentyBI

* Ab sofort kannst du leichter einsehen, welche Kennzahlen in welchen Dashboard-Ansichten verwendet werden.
+
Öffne dazu das Menü *Einrichtung » plentyBI » Kennzahlen*. Klicke auf eine bereits angelegte Kennzahl. In der Detailansicht der Kennzahl steht nun der Bereich *Einsehen* zur Verfügung. Klappe den Bereich auf und klicke auf *Verwendung einsehen*. Danach wird eine Liste mit Links zu Dashboard-Ansichten angezeigt, in denen die Kennzahl genutzt und angezeigt wird.

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Artikel

* In der neuen Artikel-UI wird beim Filtern nach Lieferanten nun an erster Stelle der Firmenname angezeigt und anschließend der Nach- und Vorname des Kontakts. Die Sortierung innerhalb des Filters erfolgt alphabetisch.

[discrete]
=== Payment

* Wenn du im alten Dashboard das Element *Zahlungen* aktiviert hattest, wurdest du z.B. beim Klick auf die Anzahl der nicht zugeordneten Zahlungen oder der Zahlungen am aktuellen Tag zum alten Menü *Aufträge » Zahlungsverkehr (veraltet)* weitergeleitet. Dies wurde geändert. Ab sofort wirst du auf die neue UI im Menü *Aufträge » Zahlungsverkehr* weitergeleitet.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Artikel

* Das Speichern der Bildverknüpfung für Varianten über die Neue Artikel-UI ist jetzt wieder möglich.

[discrete]
=== Aufträge

* In der Auftrags-UI konnte der Upload bei einen Bestellmerkmal von Typ *Datei* nicht geöffnet werden. Es ist dabei immer zu einen Access-Denied Fehler gekommen. Diese wurde nun behoben.
* Beim Finanzbuchhaltungs-Export hat die Einstellung *Markiere exportierte Datensätze* nicht korrekt funktioniert, da ein nicht exportierter Auftrag als exportiert markiert wurde.
+
Wurden nach dem Export neue Dokumente erstellt, wurden diese nicht im Export angezeigt, wenn die Option *Nur markierte Aufträge exportieren* aktiviert war. Dieses Verhalten wurde behoben und nun wird jedes exportierte Dokument markiert. Diese Änderung greift nur für Dokumente, die nach dieser Änderung erstellt wurden.

[discrete]
=== CRM

* Beim Versuch, das SEPA-Lastschriftmandat als Anhang in einer E-Mail-Vorlage zu versenden, ist es in manchen Systemen zu einem Fehler gekommen. Dieses Verhalten wurde behoben.

[discrete]
=== Ereignisaktionen

* Wenn in einer Ereignisaktion eingestellt ist, dass die E-Mail-Vorlage an die Lieferadresse gesendet werden soll, dort aber keine E-Mail-Adresse gespeichert ist, wird als Fallback die E-Mail-Adresse, die am Kontakt gespeichert ist, gesendet. Dieser Fallback hat nicht auf allen Systemen funktioniert. Dieses Verhalten wurde behoben; der Fallback auf die E-Mail-Adresse am Kontakt funktioniert wieder.

--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.



--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|
|
|

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

====
