= Changelog 24. August 2022
:author: kevin-stederoth
:sectnums!:
:page-index: false
:page-aliases: ROOT:changelog.adoc
:startWeekDate: 18. August 2022
:endWeekDate: 24. August 2022

// Ab diesem Eintrag weitermachen: LINK EINFÜGEN

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== CRM

* Das Feld *Eigner* im Bereich *Kontaktdetails* des Kontaktdatensatzes beinhaltet nun eine Vorschlagsliste. Wenn du also einen Buchstaben des Eignernamens in diesem Feld eingibst, schlägt dir das System bereits gespeicherte Eigner zum Auswählen vor.

[discrete]
=== plentyBI

* Bisher mussten für die Erstellung von Kennzahlen spezielle Rohdatenformate im Menü *Einrichtung » plentyBI » Rohdaten* aktiviert werden. Dieser Schritt ist nun nicht mehr notwendig. Stattdessen werden die benötigten Rohdatenformate automatisch im Hintergrund aktiviert, wenn neue Kennzahlkonfigurationen im Menü *Einrichtung » plentyBI » Kennzahlen* oder aus einer bestehenden Dashboard-Ansicht heraus xref:business-entscheidungen:myview-dashboard.adoc#200[angelegt] und abgespeichert werden.
+
[NOTE]
.Kein To-Do
======
Die Änderung hat keine Auswirkungen auf bestehende Kennzahlkonfigurationen.
======

[discrete]
=== Prozesse

* Wir haben eine die Einstellung xref:automatisierung:aktionen.adoc#380[Etiketten generieren] eingeführt, mit der man bestimmen kann, welche Etiketten gedruckt bzw. gespeichert werden sollen:
** *Etiketten immer generieren* +
Dies bildet das bisherige Verhalten ab. Es werden neue Etiketten registriert und sowohl vorhandene als auch neue Etiketten gedruckt/gespeichert.
** *Etiketten generieren, wenn keine existieren* +
Existieren bereits Etiketten, werden diese gedruckt/gespeichert. Ansonsten werden neue Etiketten registriert und gedruckt/gespeichert.
** *Bestehende Etiketten verwenden* +
Es werden nur vorhandene Etiketten gedruckt/gespeichert. Existieren keine Etiketten, wird eine entsprechende Fehlermeldung angezeigt.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Aufträge

* Aufträge können nicht mehr ohne die Berechtigung *Aufträge » Aktualisieren* kopiert werden.
* In der Statistik der Retourengründe wurde die Versandkostenposition bei *Zurückgesendeten Artikel* in der Daten-Tabelle mit einberechnet diese werden nun korrekt ausgeschlossen.

[discrete]
=== Prozesse

* Es war bisher nicht möglich, die Aktion *Retoure anlegen/bearbeiten* für Lager zu benutzen, die keine Lagerorte haben. Nun bieten wir die Möglichkeit an, den Standard-Lagerort auszuwählen.

--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.



--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|
|
|

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

====
