= Changelog 12. Oktober 2022
:author: kevin-stederoth
:sectnums!:
:page-index: false
:page-aliases: ROOT:changelog.adoc
:startWeekDate: 6. Oktober 2022
:endWeekDate: 12. Oktober 2022

// Ab diesem Eintrag weitermachen: LINK EINFÜGEN

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== CRM

* Im *Aufträge*-Portlet im Kontaktdatensatz wurden die folgenden Felder hinzugefügt:
** Auftragsdatum
** Herkunfts-ID
** Herkunftsname
** Zahlungseingang
** Warenausgang
** Versanddatum
** Mandant

+
Du kannst diese Felder mit einem Klick auf *Spalten konfigurieren* im *Aufträge*-Portlet oben rechts aktivieren.

[discrete]
=== Ereignisaktionen

* Wir haben die Ereignisaktion *Dokument hochgeladen* hinzugefügt, die ausgelöst wird, wenn ein externes Dokument des neuen Typs *Hochgeladen* am Auftrag generiert wird.

[discrete]
=== Fulfillment

* In der Auftragsansicht des neuen Versand-Center kannst du einzelne Pakete eines Auftrags jetzt leichter konfigurieren, indem du einfach auf die Zeile mit dem entsprechenden Paket klickst. Es öffnet sich dann ein Fenster, das dir verschiedene Optionen zur Konfiguration bietet. Diese bestätigst du direkt in diesem Fenster mit einem Klick auf den Button *Paket konfigurieren*. Weitere Informationen findest du auf der Handbuchseite xref:fulfillment:versand-center-2-0.adoc#pakete[Versand-Center 2.0 (Testphase)].

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== UI

* Unter dem Menüpunkt *Einrichtung* wurde die Seitennavigation angepasst, so dass eine optische Einheitlichkeit besteht.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Aufträge

* In der Nachbestellungs-UI wurde der gewählte Filter für *Warenbewegungen* bei Aktualisierung der Tabelle nicht berücksichtigt.

[discrete]
=== CRM

* Im EmailBuilder im Widget *Auftragspositionen* fehlte die Artikel-ID. Dieses Feld wurde nun ergänzt.

--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.



--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|
|
|

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

====
