= Changelog 31. August 2022
:author: kevin-stederoth
:sectnums!:
:page-index: false
:startWeekDate: 25. August 2022
:endWeekDate: 31. August 2022

// Ab diesem Eintrag weitermachen: https://forum.plentymarkets.com/t/prozesse-auftrags-tags-hinzufuegen-entfernen-processes-add-or-remove-order-tags/692918

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== plentyBI

* Ab sofort kannst du leichter einsehen, welche Kennzahlen in welchen Dashboard-Ansichten verwendet werden.
+
Öffne dazu das Menü *Einrichtung » plentyBI » Kennzahlen*. Klicke auf eine bereits angelegte Kennzahl. In der Detailansicht der Kennzahl steht nun der Bereich *Einsehen* zur Verfügung. Klappe den Bereich auf und klicke auf *Verwendung einsehen*. Danach wird eine Liste mit Links zu Dashboard-Ansichten angezeigt, in denen die Kennzahl genutzt und angezeigt wird.

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Artikel

* In der neuen Artikel-UI wird beim Filtern nach Lieferanten nun an erster Stelle der Firmenname angezeigt und anschließend der Nach- und Vorname des Kontakts. Die Sortierung innerhalb des Filters erfolgt alphabetisch.

[discrete]
=== OTTO Market

* OTTO Market aktualisiert am 31.08.2022 einige Produktkategorien. Betroffen sind 412 Produktkategorien. Bei der Aktualisierung werden in den meisten Fällen nur die Namen der Produktkategorien geändert.
+
[IMPORTANT]
.To-Do
======
Die meisten Änderungen an den OTTO Market-Produktkategorien werden von uns migriert. Hier musst du also nichts weiter tun.

Einige Produktkategorien können jedoch nicht migriert werden. Diese Produktkategorien sind in der folgenden Tabelle aufgelistet.

Wenn du Varianten hast, die in diesen alten Produktkategorien enthalten sind, musst du diese Varianten jetzt in Katalogen für die neuen Kategoriegruppen zuordnen.

Wenn du noch keine Kataloge für die neuen Produktkategorien hast, erstelle neue Kataloge mit dem Assistenten Kataloge erstellen - OTTO Market. Weitere Informationen zum Erstellen von Katalogen findest du auf der Handbuchseite xref:maerkte:otto-market.adoc#_katalog_mit_dem_assistenten_erstellen[Otto Market].

.Übersicht der Produktkategorien, die nicht migriert werden:
[cols="4"]
|========
|alte Produktkategorie |alte Kategoriegruppe |neue Produktkategorie |neue Kategoriegruppe

|Adapter (Adapter)
|Adapter
|in passende Produktkategorie überführen
|in passende Kategoriegruppe überführen

|Anti-Schnarch-Kissen (Kopfkissen)
|Kopfkissen
|Anti-Schnarch Kissen
|Kissen

|Augenlid-Tape (Pflaster)
|Pflaster
|Augenpatches; Augenpads
|Augenpflegemittel

|Schlauchverbinder (Schlauchverbinder)
|Schlauchverbinder
|in passende Produktkategorie überführen
|in passende Kategoriegruppe überführen

|Tablett (Dekofiguren)
|Dekofiguren
|Dekotablett
|Dekoschalen
|========

_Hinweis_: Weitere Informationen und eine Liste aller OTTO Market-Produktkategorien, die aktualisiert werden, findest du im link:https://forum.plentymarkets.com/t/otto-market-update-der-produkt-kategorien-am-31-08-2022-update-of-product-categories-on-31-08-2022/691704[Forum^].
======

[discrete]
=== Payment

* Wenn du im alten Dashboard das Element *Zahlungen* aktiviert hattest, wurdest du z.B. beim Klick auf die Anzahl der nicht zugeordneten Zahlungen oder der Zahlungen am aktuellen Tag zum alten Menü *Aufträge » Zahlungsverkehr (veraltet)* weitergeleitet. Dies wurde geändert. Ab sofort wirst du auf die neue UI im Menü *Aufträge » Zahlungsverkehr* weitergeleitet.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Artikel

* Das Speichern der Bildverknüpfung für Varianten über die Neue Artikel-UI ist jetzt wieder möglich.

[discrete]
=== Aufträge

* In der Auftrags-UI konnte der Upload bei einen Bestellmerkmal von Typ *Datei* nicht geöffnet werden. Es ist dabei immer zu einen Access-Denied Fehler gekommen. Diese wurde nun behoben.
* Beim Finanzbuchhaltungs-Export hat die Einstellung *Markiere exportierte Datensätze* nicht korrekt funktioniert, da ein nicht exportierter Auftrag als exportiert markiert wurde.
+
Wurden nach dem Export neue Dokumente erstellt, wurden diese nicht im Export angezeigt, wenn die Option *Nur markierte Aufträge exportieren* aktiviert war. Dieses Verhalten wurde behoben und nun wird jedes exportierte Dokument markiert. Diese Änderung greift nur für Dokumente, die nach dieser Änderung erstellt wurden.

[discrete]
=== CRM

* Beim Versuch, das SEPA-Lastschriftmandat als Anhang in einer E-Mail-Vorlage zu versenden, ist es in manchen Systemen zu einem Fehler gekommen. Dieses Verhalten wurde behoben.

[discrete]
=== Ereignisaktionen

* Wenn in einer Ereignisaktion eingestellt ist, dass die E-Mail-Vorlage an die Lieferadresse gesendet werden soll, dort aber keine E-Mail-Adresse gespeichert ist, wird als Fallback die E-Mail-Adresse, die am Kontakt gespeichert ist, gesendet. Dieser Fallback hat nicht auf allen Systemen funktioniert. Dieses Verhalten wurde behoben; der Fallback auf die E-Mail-Adresse am Kontakt funktioniert wieder.

[discrete]
=== Plugin

* Wenn in den Einstellungen eines Plugins ein Dropdown-Menü verwendet wird, kann die Auswahl des Dropdown-Menüs jetzt auch wieder gespeichert werden, wenn es keinen expliziten Standardwert für die Einstellung gibt. In diesem Fall wird die erste Option gewählt.

[discrete]
=== Prozesse

* Aufgrund eines Updates konnte es in der Aktion *Retourenetikett* vorkommen, dass der Prozess stehenbleibt. Dieses Verhalten wurde behoben.

--

early::
+
--

:version: early

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== CRM

* Im Menü *Einrichtung » Mandant » [Mandant wählen] » E-Mail » Vorlagen* hat die Variable `$ItemASIN` keinen Wert ausgegeben, wenn man diese mit der Variable `$ItemListHTML` verwenden wollte. Dieses Verhalten wurde behoben.

[discrete]
=== Prozesse

* In der Aktion *Wareneingang (einfach)* konnte es vorkommen, dass manche Artikel nicht geladen wurden, wenn die Verknüpfung der Artikelbilder fehlerhaft war. Dieses Verhalten wurde behoben.
* In der Aktion *Retoure anlegen/bearbeiten* gab es ein Problem beim Zurückbuchen von Bundles. Dieses Verhalten wurde behoben.

--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|link:https://marketplace.plentymarkets.com/backmarket_6485[Backmarket^]
|1.3.3
|-

|link:https://marketplace.plentymarkets.com/dpdshippingservices_6320[DPD Versand Services^]
|1.7.14
|-

|link:https://marketplace.plentymarkets.com/clearvat_6925[eClear – Grenzüberschreitender E-Commerce – so einfach wie Inlandsverkäufe^]
|3.0.1
|-

|link:https://marketplace.plentymarkets.com/etsy_4689[Etsy^]
|2.1.33
|-

|link:https://marketplace.plentymarkets.com/feed4ceres_6097[Feed4Ceres^]
|4.1.1
|-

|link:https://marketplace.plentymarkets.com/fruugo_6875[Fruugo.com^]
|1.3.6
|-

|link:https://marketplace.plentymarkets.com/mirakl_6917[Mirakl Connector^]
|1.2.2
|-

|link:https://marketplace.plentymarkets.com/mytoys_54776[MyToys^]
|1.0.40
|-

|link:https://marketplace.plentymarkets.com/trackingmanager_54743[TrackingManager^]
|1.2.4
|-

|link:https://marketplace.plentymarkets.com/woocommerce_5102[woocommerce.com^]
|3.0.8
|-

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

App::
+
--

[discrete]
== Neu

Folgende Neuerungen wurden in Version 1.11.31 der *plentymarkets App* veröffentlicht.

* Ab sofort wird App-Nutzern bei jedem Login eine Benachrichtigung angezeigt. Somit informieren wir flächendeckend über die künftigen Mindestanforderungen an die Betriebssystem-Version bei Android-Geräten. Bitte lest link:https://forum.plentymarkets.com/t/ankuendigung-mindestversion-fuer-android-geraete-wird-angehoben-minimum-version-for-android-devices-will-be-increased/691890[diesen Beitrag] sorgfältig durch, um euren Handlungsbedarf zu prüfen und weitere Informationen zu erhalten.

[discrete]
== Behoben

Folgende Probleme wurden in Version 1.11.31 der *plentymarkets App* behoben.

* Bei Zahlungen über Zettle Kartenterminals konnte es zu einem Fehler im Zusammenhang mit der technischen Sicherheitseinrichtung kommen, sodass die Zahlung unter Umständen nicht abgeschlossen werden konnte. Dieses Verhalten wurde behoben.

--
====
