= Changelog 27. Juli 2022
:author: kevin-stederoth
:sectnums!:
:page-index: false
:page-aliases: ROOT:changelog.adoc
:startWeekDate: 21. Juli 2022
:endWeekDate: 27. Juli 2022

// Ab diesem Eintrag weitermachen: LINK EINFÜGEN

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== CRM

* Im EmailBuilder wurden Abonnement-bezogene Variablen hinzugefügt. Diese neuen Variablen befinden sich als Unterkategorie *Abonnement* in der Kategorie *Auftrag*.

[discrete]
=== Ereignisaktionen

* Wir haben die fehlende Aktion *Stornobeleg Mahnung erzeugen* hinzugefügt.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Artikel

* Aufgrund von leeren Spracheinträgen in den Texteigenschaften kam es vor, dass die Änderungserkennung in der neuen Artikel-UI direkt beim Öffnen einer Variante aktiv wurde. Wir haben dieses Verhalten nun korrigiert.

[discrete]
=== CRM

* Die Dropdown-Liste Eigner im Bereich *Kontaktdetails* des Kontaktdatensatzes im Menü *CRM » Kontakte* war bisher anhand der Benutzer-ID sortiert. Ab sofort sind die Benutzer:innen in der Dropdown-Liste *Eigner* in alphabetischer Reihenfolge sortiert.

--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.



--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|
|
|

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

====
