= Changelog 21. Dezember 2022
:author: kevin-stederoth
:sectnums!:
:page-index: false
:page-aliases: ROOT:changelog.adoc
:startWeekDate: 15. Dezember 2022
:endWeekDate: 21. Dezember 2022

// Ab diesem Eintrag weitermachen: LINK EINFÜGEN

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Aufträge

* Die Spalte Variantennummer ist nun in den folgenden UIs eine optionale Spalte:
** In der neuen Auftragsanlage: in der Artikeltabelle des zweiten Schritts und in der Warenkorb-Tabelle des letzten Schritts.
** In der neuen Auftrags-UI (Testphase): in der Warenkorb-Tabelle der Ansicht *Artikel bearbeiten* und in der Artikeltabelle der Detailansicht eines Auftrags.
** In der Warenkorb-Tabelle eines neuen Kindauftrags in der neuen Auftrags-UI (Testphase).
** In der Ansicht beim Teilen von Aufträgen in der neuen Auftrags-UI (Testphase).
* Das Eingabefeld für das Lager in der Detailansicht der neuen Auftrags-UI und in der Auftragsanlage wurde überarbeitet. Die Lager können nun über ein Textfeld gefiltert werden.

[discrete]
=== CRM

* Im Menü *CRM » Firmen* wurde ein Suchfeld hinzugefügt, in dem du nach dem Namen der Firma suchen kannst.
* Wenn man in der Detailansicht des Messengers einer Nachricht geöffnet hat, werden ab sofort weniger Nachrichten in der Übersicht angezeigt, damit das Feld zum Beantworten der Nachricht größer dargestellt wird.
* Eine Schaltfläche wurde an der Nachricht im Messenger hinzugefügt. Mit einem Klick auf diese Schaltfläche wird die Nachricht im Vollbildmodus angezeigt. Wenn man den Vollbildmodus wieder schließt, gelangt man zurück zur Übersicht.

[discrete]
=== eBay

* Du kannst ab jetzt Eigenschaften für den Marktplatz eBay verwenden. Um eine Eigenschaft für eBay zu verwenden, musst du die Eigenschaft im Menü *Einrichtung » Einstellungen » Eigenschaften » Konfiguration » [Eigenschaft öffnen]* unter *Herkunft* für die gewünschte eBay-Plattform aktivieren. Wie das geht, ist auf der Handbuchseite xref:maerkte:ebay-einrichten.adoc#eigenschaften-verwenden[eBay einrichten] beschrieben.
+
[NOTE]
.Hinweis
======
Wenn du Eigenschaften in einer Layout-Vorlage verwenden willst, musst du folgende Template-Funktionen in die Layout-Vorlage einfügen: `GetItemPropertyV2ById()`, `GetItemPropertyV2ByName()` und `PropertyListV2()`.

Weitere Informationen zur Verwendung von Template-Funktionen findest du auf der Handbuchseite xref:maerkte:ebay-einrichten.adoc#3050[eBay einrichten].
======
+
[NOTE]
.Zusatzinformationen
======
*Was ist der Unterschied zwischen eBay-Merkmalen, Eigenschaften und plentymarkets Merkmalen?*

Bei eBay hast du die Möglichkeit, Informationen zu deinen Listings auf verschiedenen Wegen anzugeben: über eBay-Merkmale, Eigenschaften oder plentymarkets Merkmale. Alle drei Möglichkeiten erfüllen dieselbe Funktion - sie dienen dazu, deinen Listings weitere Informationen hinzuzufügen und sie detaillierter zu beschreiben.

Wenn du deinen Listings weitere Informationen hinzufügen willst, empfehlen wir, entweder eBay-Merkmale oder Eigenschaften zu verwenden. Neue plentymarkets Merkmale solltest du nicht mehr erstellen, da die Merkmale nicht mehr weiterentwickelt und in Zukunft komplett durch Eigenschaften ersetzt werden.

*Was wird zu eBay übertragen?*

Wenn du beispielsweise ein eBay-Merkmal, eine Eigenschaft und ein plentymarkets Merkmal hast und alle drei dieselben Informationen enthalten, werden nicht alle drei zu eBay übertragen. plentymarkets prüft immer zuerst, ob ein eBay-Merkmal vorhanden ist und wenn ja, wird das eBay-Merkmal übertragen. Ist keines mit diesen Informationen vorhanden, wird die Eigenschaft übertragen.

Die Priorisierung bei der Übertragung der eBay-Merkmale, Eigenschaften und plentymarkets Merkmale sieht also folgendermaßen aus:

. eBay-Merkmal
. Eigenschaft
. plentymarkets Merkmal

Wenn du eBay-Merkmal, Eigenschaft und plentymarkets Merkmal mit denselben Informationen hast, wird also immer nur die höchste Priorität zu eBay übertragen.
======

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Payment

* In der Zahlungs-UI wird der Betrag von Soll-Zahlungen nun in rot dargestellt. Zusätzlich wird bei Anlage einer Zahlung der Betrag geprüft, sodass es nicht mehr möglich ist negative Beträge an einer Zahlung anzulegen.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Aufträge

* In der neuen Auftrags-UI (Testphase) enthielt der Filter *Versandart* die falschen Namen der Versandarten. Dies wurde behoben.

[discrete]
=== CRM

* Wenn man den Messenger über die Nachbestellungs-UI aufgerufen hat, wurden die Nachrichten nicht korrekt geladen bzw. aktualisiert. Dieses Verhalten wurde behoben.
* Die Variablen `URL zum Ändern des Passworts` und `URL zum neuen Passwort` haben immer auf den Hauptmandanten verlinkt, auch wenn der Kontakt einem anderen Mandanten zugeordnet war. Dieses Verhalten wurde behoben.

--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.



--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|link:https://marketplace.plentymarkets.com/addressfactorydirect_6077[Address Cleansing^]
|1.1.7
|-

|link:https://marketplace.plentymarkets.com/addressdoctor_6106[Adressprüfung und Adresskorrektur mit AddressDoctor^]
|1.2.33
|-

|link:https://marketplace.plentymarkets.com/uniservaddresscleansing_6869[Adressprüfung und Adresskorrektur mit Uniserv^]
|2.0.3
|-

|link:https://marketplace.plentymarkets.com/amazonloginandpay_5072[Amazon Pay^]
|1.6.6
|-

|link:https://marketplace.plentymarkets.com/dhlshipping_4871[DHL Shipping (Versenden)^]
|3.1.23
|-

|link:https://marketplace.plentymarkets.com/emailblacklist_6011[E-Mail Blacklist^]
|3.1.3
|-

|link:https://marketplace.plentymarkets.com/limango_7023[limango^]
|1.4.23
|-

|link:https://marketplace.plentymarkets.com/metro_6600[Metro^]
|2.3.2
|-

|link:https://marketplace.plentymarkets.com/multicontentwidget_6082[Multicontent Toolbox^]
|4.7.22
|-

|link:https://marketplace.plentymarkets.com/mytoys_54776[myToys^]
|1.0.60
|-

|link:https://marketplace.plentymarkets.com/vatidcheck_6023[VAT ID Check^]
|2.2.8
|-

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

====
