= Changelog 27. Juli 2022
:author: kevin-stederoth
:sectnums!:
:page-index: false
:page-aliases: ROOT:changelog.adoc
:startWeekDate: 21. Juli 2022
:endWeekDate: 27. Juli 2022

// Ab dem Eintrag nach diesem weitermachen: https://forum.plentymarkets.com/t/katalog-format-check24-furniture-hinzugefuegt-check24-und-check24-offer-aktualisiert-added-catalogue-format-check24-furniture-updated-check24-and-check24-offer/689194
// Auch diesen Eintrag beachten: https://forum.plentymarkets.com/t/bi-dashboard-diagrammtyp-einfaches-saeulendiagramm-entfernt-graph-type-simple-bar-chart-removed/688774
// Auch diesen Eintrag beachten: https://forum.plentymarkets.com/t/bi-dashboard-aenderungen-am-element-globale-filter-changes-for-the-element-global-filters/688847

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Check24

* Für Check24 wurde das Katalog-Format *Check24 Furniture* hinzugefügt. Mit diesem Katalog-Format können Artikeldaten für die Check24-Produktkategorie Möbel an Check24 übertragen werden. Einen Katalog für *Check24 Furniture* erstellst du im Menü *Daten » Kataloge*. Informationen zu Katalogen und Empfehlungen für Datenfeld-Zuordnungen im Katalog findest du auf der Handbuchseite xref:maerkte:check24.adoc#recommended-mappings[Check24].
+
[IMPORTANT]
.To-Do
======
Wir empfehlen dir, nach dem Update in deinen bereits erstellten Katalogen für *Check24* und *Check24 Offer* zu prüfen, ob alle Pflichtfelder zugeordnet sind.
======

[discrete]
=== CRM

* Im EmailBuilder wurden Abonnement-bezogene Variablen hinzugefügt. Diese neuen Variablen befinden sich als Unterkategorie *Abonnement* in der Kategorie *Auftrag*.

[discrete]
=== Ereignisaktionen

* Wir haben die fehlende Aktion *Stornobeleg Mahnung erzeugen* hinzugefügt.

[discrete]
=== Kaufland

* In Kaufland-Katalogen wurde das Datenfeld *Kategorie* hinzugefügt. Es bezieht sich auf die Kaufland-Produktkategorie und wird automatisch zugeordnet.

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf {version} veröffentlicht.

[discrete]
=== Kaufland

* Das Datenfeld Zustand in den Kaufland-Katalogen wurde in eine komplexe Zuordnung umgewandelt. Das bedeutet, dass für das Marktplatz-Datenfeld feste Werte des Marktplatzes zur Verfügung stehen, denen du plentymarkets Werte zuordnest. Mit diesem Datenfeld gibst du den Zustand der Variante an. Für das Datenfeld Zustand stehen diese Werte zur Verfügung:
** NEW
** USED__AS_NEW
** USED__VERY_GOOD
** USED__GOOD
** USED__ACCEPTABLE

+
[IMPORTANT]
.To-Do
======
Wenn du das Datenfeld *Zustand* in deinen Kaufland-Katalogen bereits zugeordnet hast, musst du es nach dem Update neu zuordnen, da es jetzt eine komplexe Zuordnung ist.

Weitere Informationen zu Katalogen und Empfehlungen für Datenfeld-Zuordnungen findest du auf der Handbuchseite xref:maerkte:kaufland-de-einrichten.adoc#906[Kaufland.de einrichten].
======
* In den Kaufland-Katalogen wurden die Datenfelder für die Angebotsdaten übersetzt:
+
[cols="2"]
.Datenfelder in Kaufland-Katalogen
|===
|Alter Name |Neuer Name

|sku
|SKU

|skuBase
|SKU-Basis

|skuStatus
|SKU-Status

|condition
|Zustand

|listing_price
|Verkaufspreis

|minimum_price
|Mindestpreis

|amount
|Bestand

|note
|Zustandsbeschreibung

|handling_time
|Bearbeitungszeit in Tagen

|id_shipping_group
|Kaufland Versandgruppen-ID

|id_warehouse
|Kaufland Lager-ID
|===

[discrete]
=== OTTO

:otto-master-date: 22.07.2022
:otto-master-link: https://forum.plentymarkets.com/uploads/short-url/gpxsICngeDKolI0Xg0BiuUaZaBN.xlsx

include::partial$otto-master-file.adoc[]

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Artikel

* Aufgrund von leeren Spracheinträgen in den Texteigenschaften kam es vor, dass die Änderungserkennung in der neuen Artikel-UI direkt beim Öffnen einer Variante aktiv wurde. Wir haben dieses Verhalten nun korrigiert.

[discrete]
=== Aufträge

* Der Tab *Zahlung* wurde nicht mehr im Auftrag angezeigt. Dies wurde behoben.

[discrete]
=== CRM

* Die Dropdown-Liste Eigner im Bereich *Kontaktdetails* des Kontaktdatensatzes im Menü *CRM » Kontakte* war bisher anhand der Benutzer-ID sortiert. Ab sofort sind die Benutzer:innen in der Dropdown-Liste *Eigner* in alphabetischer Reihenfolge sortiert.
* Die französische Übersetzung für die im Code fest hinterlegte Gutscheininfo fehlte. Stattdessen wurde der deutsche Text auf französischen Gutscheinen ausgegeben. Dieses Verhalten wurde behoben.

[discrete]
=== Elastischer Export

* Der Export von Kontaktdaten war nicht möglich. Ein interner Serverfehler wurde angezeigt. Dieses Verhalten wurde behoben.

[discrete]
=== Payment

* Beim Booten von Plugins, die eine Zahlungsart per Closure registrieren konnte es zu einem Fehler kommen. Dies machte sich durch den Fehler `Illegal offset type error` im Log bemerkbar. Dadurch war unter Umständen der Shop oder die REST Api nicht verfügbar. Dies wurde entsprechend behoben.

--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== CRM

* Im EmailBuilder wurden Ticketsystem-bezogene Variablen in der Kategorie *Ticket* hinzugefügt.

[discrete]
=== Plugins

* Du kannst ab jetzt den Namen und die Beschreibung eines Plugin-Sets direkt in der Plugin-Set-Übersicht bearbeiten. Das bedeutet für dich, dass du das Plugin-Set nicht mehr öffnen musst, um diese Informationen anzupassen.

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Plugins

* Die Funktion *Plugin-Set löschen* in der Plugin-Set-Übersicht befindet sich jetzt in dem Dreipunktmenü.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Aufträge

* Beim Anlegen oder Löschen von Auftragsnotizen über die UI wurde das Änderungsdatum des Auftrags nicht aktualisiert. Dies wurde behoben.
* Der Ankerpunkt in der Seitennavigation der Status-UI wird nach dem Speichern eines Status nicht mehr geschlossen.
* Folgende Probleme mit Bestelleigenschaften wurden behoben:
** Auftrags-UI: Bei einer Bestelleigenschaft konnte der Preis von 0 nicht gespeichert werden.
** Auftrags-UI: Beim Ändern des Preises bei einer Bestelleigenschaft wurden die Auftragssummen teilweise nicht neu berechnet.
** Email-Template: Bei Artikelpaketen wurden die Bestelleigenschaften nicht dargestellt.

[discrete]
=== Import

* Es konnten bei Adressen nicht die Daten für Postnummer angeben werden. Dieses Feld wurde nun hinzugefügt.

[discrete]
=== Kataloge

* Der Katalog vom Format-Typ *Newsletter-Empfänger* ließ sich nicht öffnen. Dieses Verhalten wurde behoben.

[discrete]
=== Plugins

* Wenn ein Plugin-Set keine Plugins enthält, wird eine Nachricht angezeigt. In der Nachricht wird sowohl auf den Integrationen-Assistenten als auch auf die Installationsansicht von Plugins verlinkt. Der Link zur Installationsansicht war fehlerhaft. Dieses Problem wurde jetzt behoben.

--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|link:https://marketplace.plentymarkets.com/persistentshoppingcart_55154[Bleibender Warenkorb^]
|1.0.7
|Aufgrund von Änderungen an bestehenden Widgets müssen die ShopBuilder-Inhalte im Menü *CMS » ShopBuilder* über die Schaltfläche *Inhalte neu generieren* aktualisiert werden.

|link:https://marketplace.plentymarkets.com/cfourfullcrossselling_6125[Crossselling Artikellisten für die Produkt Seite^]
|1.0.14
|-

|link:https://marketplace.plentymarkets.com/etsy_4689[Etsy^]
|2.1.18
|-

|link:https://marketplace.plentymarkets.com/fruugo_6875[Fruugo.com^]
|1.3.5
|-

|link:https://marketplace.plentymarkets.com/galaxus_4788[Galaxus.ch^]
|1.13.0
|-

|link:https://marketplace.plentymarkets.com/googleanalytics_4725[GoogleAnalytics^]
|1.1.4
|-

|link:https://marketplace.plentymarkets.com/elasticexportidealode_4723[idealo.de^]
|3.3.36
|-

|link:https://marketplace.plentymarkets.com/invoice_4760[Kauf auf Rechnung^]
|2.0.11
|-

|link:https://marketplace.plentymarkets.com/metro_6600[Metro^]
|2.2.3
|-

|link:https://marketplace.plentymarkets.com/mollie_6272[Mollie^]
|2.8.12
|-

|link:https://marketplace.plentymarkets.com/payever_5623[payever^]
|2.6.1
|-

|link:https://marketplace.plentymarkets.com/payone_5434[PAYONE^]
|2.5.1
|-

|link:https://marketplace.plentymarkets.com/paypal_4690[PayPal Checkout^]
|6.0.14
|-

|link:https://marketplace.plentymarkets.com/plentymarketsshopwarecore_54952[Shopware 6 Connector Core^]
|1.0.12
|-

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

====
