= Changelog 8. Juni 2022
:author: kevin-stederoth
:sectnums!:
:page-index: false
:page-aliases: ROOT:changelog.adoc
:startWeekDate: 2. Juni 2022
:startWeekDate: 8. Juni 2022

// Ab diesem Eintrag weitermachen: LINK EINFÜGEN

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== CRM

* Beim Erstellen eines neuen Kontakts im Menü *CRM » Kontakte* wurde das Feld *Handelsvertreter, der dem Kontakt zugeordnet ist* hinzugefügt. Du kannst dieses Feld über die MyView mit einem Klick auf *Ansicht bearbeiten* hinzufügen.
* Im EmailBuilder wird ab sofort die ID der Vorlage in Klammern vor dem Namen der Vorlage angezeigt.

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Backend

* Im Zuge der Entfernung aller veralteten Komponenten haben wir nun alle Breadcrumbs in plenty durch die Seitennavigation ersetzt. Im Einstellungs-Baum wird dies allerdings nur eine temporäre Lösung sein, da möglicherweise 2 Seitennavigationen nebeneinander platziert sein können.
* Im Zuge der Entfernung aller veralteten Komponenten haben wir nun alle TerraOverlays in plenty durch MaterialOverlays ersetzt.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Aufträge

* Aufträge mit Bestelleigenschaften bei denen die Relation gefehlt hat werden nun wieder in der Auftragsssuche angezeigt.
* Bei Aufträgen mit Lieferaufträgen konnte es unter Umständen vorkommen, dass sich der Standort des Hauptauftrages geändert hat.

[discrete]
=== Prozesse

* Es gab einen kleinen Fehler mit der Artikelbilderanzeige in der Artikelerfassung der Prozesse, sodass alle Artikelbilder in der Aktion Artikelerfassung nicht angezeigt werden konnten. Dieses Verhalten wurde behoben.

--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.



--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|
|
|

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

====
