= Changelog 3. August 2022
:author: kevin-stederoth
:sectnums!:
:page-index: false
:page-aliases: ROOT:changelog.adoc
:startWeekDate: 28. Juli 2022
:endWeekDate: 3. August 2022

// Ab diesem Eintrag weitermachen: LINK EINFÜGEN

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== CRM

* Im EmailBuilder wurden Ticketsystem-bezogene Variablen in der Kategorie *Ticket* hinzugefügt.

[discrete]
=== Plugins

* Du kannst ab jetzt den Namen und die Beschreibung eines Plugin-Sets direkt in der Plugin-Set-Übersicht bearbeiten. Das bedeutet für dich, dass du das Plugin-Set nicht mehr öffnen musst, um diese Informationen anzupassen.

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Plugins

* Die Funktion *Plugin-Set löschen* in der Plugin-Set-Übersicht befindet sich jetzt in dem Dreipunktmenü.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Aufträge

* Beim Anlegen oder Löschen von Auftragsnotizen über die UI wurde das Änderungsdatum des Auftrags nicht aktualisiert. Dies wurde behoben.
* Der Ankerpunkt in der Seitennavigation der Status-UI wird nach dem Speichern eines Status nicht mehr geschlossen.
* Folgende Probleme mit Bestelleigenschaften wurden behoben:
** Auftrags-UI: Bei einer Bestelleigenschaft konnte der Preis von 0 nicht gespeichert werden.
** Auftrags-UI: Beim Ändern des Preises bei einer Bestelleigenschaft wurden die Auftragssummen teilweise nicht neu berechnet.
** Email-Template: Bei Artikelpaketen wurden die Bestelleigenschaften nicht dargestellt.

[discrete]
=== Import

* Es konnten bei Adressen nicht die Daten für Postnummer angeben werden. Dieses Feld wurde nun hinzugefügt.

[discrete]
=== Kataloge

* Der Katalog vom Format-Typ *Newsletter-Empfänger* ließ sich nicht öffnen. Dieses Verhalten wurde behoben.

[discrete]
=== Plugins

* Wenn ein Plugin-Set keine Plugins enthält, wird eine Nachricht angezeigt. In der Nachricht wird sowohl auf den Integrationen-Assistenten als auch auf die Installationsansicht von Plugins verlinkt. Der Link zur Installationsansicht war fehlerhaft. Dieses Problem wurde jetzt behoben.

--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.



--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|
|
|

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

====
