= Changelog 16. November 2022
:author: kevin-stederoth
:sectnums!:
:page-index: false
:page-aliases: ROOT:changelog.adoc
:startWeekDate: 10. November 2022
:endWeekDate: 16. November 2022

// Ab diesem Eintrag weitermachen: LINK EINFÜGEN

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== CRM

* Im EmailBuilder wurden im Bereich *Globals* die folgenden Variablen hinzugefügt:
** Allgemeine Geschäftsbedingungen im HTML-Format
** Allgemeine Geschäftsbedingungen im reinen Textformat

+
Diese Variablen geben den gesamten Text der AGB aus wie im Menü *Einrichtung » Mandant » [Mandant wählen] » Webshop » Rechtliches* gespeichert.

[discrete]
=== Payment

* Im Menü *Zahlungsverkehr* wurden folgende Spalten neu hinzugefügt:
** *Transaktionscode*
** *Referenz-ID*
** *Transaktionstyp*

+
Diese Kategorien waren bereits als Filter vorhanden, können nun aber auch nach Wunsch als Spalten hinzugefügt werden.
* Außerdem wurden folgende Spalten neu hinzugefügt:
** *Zahlungsart-ID*
** *Zahlungsart-Symbol*
** *Name der Zahlungsart*

+
Diese Informationen sind weiterhin in der Spalte Zahlungsart verfügbar, können nun aber auch als separate Spalten dargestellt werden. Standardmäßig sind die neuen Spalten deaktiviert. Über die Einstellungen (*Spalten konfigurieren*) kannst du sie aktivieren.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Aufträge

* Bei dem Exportformat für Zahlungen in den Katalogen (*Daten » Kataloge*) kam es bei der Verwendung von dem Datenformat CSV und Datenfeldern bei denen der Export Key einen Punkt beinhaltete zu einer fehlerhaften Darstellung. Dies wurde behoben.

[discrete]
=== CRM

* Im Portlet *Aufträge* im Kontaktdatensatz wurde der falsche Mandant in der Spalte *Herkunftsname* angezeigt. Dieses Verhalten wurde behoben.

--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.



--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|
|
|

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

====
