= Changelog 7. Dezember 2022
:author: kevin-stederoth
:sectnums!:
:page-index: false
:startWeekDate: 1. Dezember 2022
:endWeekDate: 7. Dezember 2022

// Ab diesem Eintrag weitermachen: https://forum.plentymarkets.com/t/variantennummer-als-optionale-spalte-in-warenkorb-tabellen-variation-number-as-optional-column-in-shopping-cart-tables/704296

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Artikel-UI (Neu)

* Es ist jetzt möglich Artikeletiketten in der neuen Artikel-UI zu erstellen. Zusätzlich hat man auf der Variantendetailansicht die Möglichkeit einen spezifischen Lagerort für das Etikett zu wählen.
* Es ist jetzt möglich, eine Variante zur neuen Hauptvariante zu machen.

[discrete]
=== Aufträge

* In der Detailansicht der neuen Auftrags-UI können jetzt die verwendeten Umsatzsteuersätze angezeigt werden.
* In der Auftragsanlage wird nun die Kundenbewertung angezeigt.
* Im letzten Schritt der neuen Auftragsanlage wurde im Feld *Gutscheincodes* ein neuer Button hinzugefügt, über den man externe und interne Gutscheincodes einlösen kann.
* Die *Auftragsherkunft* ist nun ein Standardfilter in der Auftragsübersicht.
* Die Spalte *Externe Auftrags-ID* ist nun eine Standardspalte in der Tabelle der Auftragsübersicht.
* In den Auftragsdetails ist nun standardmäßig auch der Bereich *Messenger* verfügbar, der direkt neben den Notizen zu finden ist. Diese Änderung gilt für alle Auftragstypen.
* In der neuen Auftrags-UI werden bei den Auftragsreferenzen nun nicht mehr nur direkte Eltern- und Kindaufträge, sondern alle verwandten Aufträge angezeigt.
* m Menü *Einrichtung » Aufträge » Auftragstypen » Lieferauftrag* wurde bei der Einstellung *Aufträge in Lieferaufträge splitten nach* die neue *Option Lager- und Netto-Warenbestand >= Menge Auftragsposition* hinzugefügt. In diesen Schritt wurde außerdem die Option *Lager- und Netto-Warenbestand* in *Lager- und Netto-Warenbestand > 0* umbenannt.

[discrete]
=== CRM

* Im Assistenten Messenger-Konfiguration wurde im Schritt Einstellungen für den E-Mail-Empfang eine Einstellung hinzugefügt, mit der man die Benachrichtigungen über neue Nachrichten über den Messenger aktivieren bzw. deaktivieren kann. Wenn diese Einstellung deaktiviert ist, erhältst du über das Glocken-Symbol oben rechts im plentymarkets Backend keine Benachrichtigungen mehr bei Erhalt neuer Nachrichten über den Messenger.
* Wenn man im EmailBuilder eine bestehende Vorlage von einem Ordner in einen anderen Ordner verschiebt, wird ab sofort der Zielordner aufgeklappt.

[discrete]
=== Fulfillment

* Wenn im neuen Versand-Center oder in der Paketinhaltsliste ein Paket hinzugefügt wird, ist es nun auch dort möglich, eine Paketnummer einzutragen. Diese Nummer wird dann in der Pakete-Tabelle angezeigt und kann bearbeitet werden, wenn die Zeile in der Tabelle angeklickt wird.

[discrete]
=== Netto

* Über die Anbindung von Netto kann ab dem 01.01.2023 der neue Verkaufskanal Marktkauf bedient werden. Hierfür wurde
** eine neue Auftragsherkunft mit der ID `171.00` ergänzt. Diese wird direkt aktiv gesetzt, wenn ihr bereits die Herkunft für Netto aktiv habt.
** eine neue Zahlungsart *Marktkauf* ergänzt, welche angezeigt wird, wenn ihr die Netto-Einstellungen gesetzt habt.
** Unter *Einrichtung » Märkte » Netto eStores » Tab: Kategorien aktivieren* eine Spalte für Marktkauf ergänzt.

+
Ob eine Variante auf Marktkauf oder Netto angeboten wird, wird wie gewohnt über die Marktplatzverfügbarkeit an der Variante gesteuert.

+
[NOTE]
.Hinweis
======
Es ist bis zur Umstellung auf den Katalog nicht möglich, für Netto und Marktkauf separate Preise zu bestimmen.
======

[discrete]
=== Plugins

* Sollte durch Wartungsarbeiten am Plugin Build dieser nicht nutzbar sein, erhälst Du nun eine Info darüber in der Plugin Build-UI. Sollte es nötig sein, dass durch Wartungsarbeiten die Bereitstellung deaktiviert werden muss, wirst Du nach wie vor via Forum & Statusmail informiert.

[discrete]
=== Prozesse

* In der Prozessbearbeitung kannst du jetzt den *Namen* und die *ID* als Überschrift sehen. Damit kannst du bei mehreren Prozessen einfacher den Überblick behalten und es ist außerdem möglich, den Namen und die ID zu kopieren.
* Wir haben in den Prozessen die neue Subaktion *Generieren* eingeführt, mit der ihr die Möglichkeit habt, folgende Dokumente vorab zu generieren:
** Rechnung
** Mahnung
** Lieferschein
** Gutschrift
** Korrekturbeleg
** Reparaturschein
** Auftragsbestätigung
** Angebot
** Rücksendeschein
** Gelangensbestätigung
** Abhol-/Lieferschein
** Stornobeleg Mahnung
** Stornobeleg Rechnung
** Stornobeleg Gutschrift
** Proformarechnung

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== ShopBuilder

* Der Kategoriebaum im ShopBuilder zeigt jetzt mit einem Link Symbol an, ob eine Kategorie mit einer Route verknüpft ist.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Artikel-UI (Neu)

* Wenn man in der neuen Artikel-UI Bestelleigenschaften verknüpfen möchte, dann werden im Dialog zur Auswahl der gewünschten Eigenschaften jetzt ausschließlich Bestelleigenschaften angezeigt.

[discrete]
=== Aufträge

* Im zweiten Schritt der neuen Auftragsanlage wurde eine Warnmeldung mehrfach für dieselbe Varianten-ID angezeigt, wenn der Preis niedriger war als der Verkaufspreis. Die Warnmeldung wird nun lediglich im letzten Schritt angezeigt und auch die mehrfache Anzeige wurde behoben.
* In der Artikeltabelle der neuen Auftragsanlade wurden die Spalten *System-EK*, *Lager* und *Nettobestand* nicht richtig angezeigt. Dieser Fehler wurde behoben.
* In der Übersicht der neuen Auftrags-UI wurde immer die Systemwährung angezeigt - auch wenn der Auftrag eine andere Währung hatte. Dies wurde behoben.
* In der neuen Auftrags-UI (Testphase) wurde das Dokumenten-Widget nach der Erstellung neuer Dokumente nicht neu geladen. Dieser Fehler wurde behoben.
* In der neuen Auftrags-UI (Testphase) wurden Aktionsgutscheine und Mehrzweckgutscheine in der Artikeltabelle nicht angezeigt. Dieser Fehler wurde behoben.
* In der UI für Bestellungen wurden Tags nicht gespeichert wenn eine neue Umbuchung erstellt oder eine bestehende Umbuchung bearbeitet wurde. Dieser Fehler wurde behoben.
* Der Filter *Kontaktdaten* in der Auftragssuche hat nicht funktioniert. Dies wurde behoben.
* In der neuen UI zur Auftragsanlage wurden Varianten bei der Wahl einer Vorlage im ersten Schritt in der falschen Menge zum Warenkorb hinzugefügt. Dies wurde behoben, sodass nun die korrekte Varianten-Menge aus der Auftragsvorlage übernommen wird.
* In der neuen Auftragsanlage fehlten die deutschen Übersetzungen für die Felder der Zahlungsbedingungen im ersten Schritt. Dies wurde behoben.

[discrete]
=== CRM

* Die Variable *Tracking-URL* im EmailBuilder hat keinen klickbaren Link ausgegeben, der zur Seite des Versanddienstleisters führt. Dieses Verhalten wurde behoben.
* Bestehende Kontaktoptionen im Kontaktdatensatz konnten nicht aktualisiert und dann gespeichert werden, wenn man die Portlets *Tags*, *Eigenschaften* oder *Optionen* aus der MyView entfernt hat. Dieses Verhalten wurde behoben.
* Wenn man im Messenger auf eine Nachricht antwortete, konnte es in einigen Systemen vorkommen, dass im Empfängerfeld die Empfänger-E-Mail-Adresse mehrfach angezeigt wurde. Dieses Verhalten wurde behoben.

[discrete]
=== Prozesse

* Bei der Anmeldung des Versands in den Prozessen konnte es zu einer Fehlermeldung (`Response is NOT a valid JSON document`) im Backend-Log kommen. Dieses Verhalten wurde behoben.
* Die Aktion *Rücksendeschein* funktionierte in den Prozessen nicht, wenn der Rücksendeschein für einen Lieferauftrag generiert werden sollte. Dieses Verhalten wurde behoben.

[discrete]
=== ShopBuilder

* Die UI *Globale Einstellungen* lädt jetzt schneller, dank lokalem Caching und einer Optimierung der Datenanfragen.

--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Aufträge

* In der Auftragsübersicht der neuen Auftrags-UI wird nun bei einem Statuswechsel für einen einzelnen Auftrag der aktuelle Status vorausgewählt.
* Es wurde eine Einstellung für das Standard-Lager in der Auftragsanlage hinzugefügt.

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Aufträge

* In der UI der Auftragsherkünfte wurde die Möglichkeit integriert, die HerkunftsID bei der Anlage einer neuen Herkunft selbst zu bestimmen.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Aufträge

* In der neuen UI zur Auftragsanlage wurden Varianten bei der Wahl einer Vorlage im ersten Schritt in der falschen Menge zum Warenkorb hinzugefügt. Dies wurde behoben, sodass nun die korrekte Varianten-Menge aus der Auftragsvorlage übernommen wird.
* In der Variantensuche im 2. Schritt der neuen Auftragsanlage und in der Ansicht zum Bearbeiten von Artikeln in der neuen Auftrags-UI ist nun eine Teilsuche für Variantennummern möglich.
* Nach dem Löschen einer Auftragsposition in einem Lieferauftrag war diese Position im Hauptauftrag für einen neuen Lieferauftrag nicht wieder verfügbar. Dies wurde behoben.
* Die Verlinkung zu Umbuchungen in Warenbewegungen hat nicht funktioniert. Dies wurde behoben.
* Bei der Verarbeitung von Lieferaufträgen konnte es zu Fehlern kommen, wenn im Auftrag Artikelpakete mit Bestelleigenschaften vorhanden waren. Dies wurde behoben.
* In der neuen Auftragsanlage und in der neuen Auftrags-UI (Testphase) fehlten die Werte für die Attribute-Spalte in der Variantensuche. Dies wurde behoben.
* Bei Änderung der Mengen in der Variantensuche (Step 2) wurde bei der erneuten Preiskalkulation die Kundenklasse nicht beachtet. Dies wurde behoben.
* Die Markierung *Nicht im Bestand* wurde in der Variantensuche (Step 2) nicht korrekt angezeigt. Dies wurde behoben.

[discrete]
=== CRM

* Wenn man bei einem Lieferland die Einstellung *Lieferant aktiv* im Menü *Einrichtung » Aufträge » Versand » Optionen* im Tab *Lieferländer* gewählt hatte, war dieses Lieferland in den Adressen eines Kontakts des Typs *Lieferant* nicht verfügbar. Dieses Verhalten wurde behoben.

[discrete]
=== Dokumente

* Beim Drucken von Dokumenten als Sammeldokument kam es zu einem Fehler, wenn nur ein Dokument verfügbar war. Dies wurde behoben.

[discrete]
=== Fulfillment

* Im neuen Versand-Center wurde in bestimmten Fällen das falsche Produktbild für Varianten angezeigt: Es wurde standardmäßig das erste Bild angezeigt statt das Bild, das der Variante entspricht. Dieser Fehler wurde behoben.

--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|link:https://marketplace.plentymarkets.com/cfourcustomcssjs_5143[Custom CSS/JS im Frontend^]
|2.0.8
|-

|link:https://marketplace.plentymarkets.com/ebaysdk_4784[eBay SDK^]
|1.3.0
|-

|link:https://marketplace.plentymarkets.com/limango_7023[limango^]
|1.4.22
|-

|link:https://marketplace.plentymarkets.com/mytoys_54776[myToys^]
|1.0.59
|-

|link:https://marketplace.plentymarkets.com/shopify_4944[Shopify.com^]
|2.14.1
|-

|link:https://marketplace.plentymarkets.com/trackingmanager_54743[TrackingManager^]
|1.2.9
|-

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

====
