= Changelog 18. Mai 2022
:author: kevin-stederoth
:sectnums!:
:page-index: false
:page-aliases: ROOT:changelog.adoc
:startWeekDate: 12. Mai 2022
:endWeekDate: 18. Mai 2022

// Ab dem Eintrag nach diesem weitermachen: https://forum.plentymarkets.com/t/neuerungen-an-den-katalogen-updates-to-catalogues/680685

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Kataloge

* Für den Namen der Exportdatei stehen dir schon länger Platzhalter zur Verfügung. Nun haben wir weitere Platzhalter hinzugefügt, damit du auch Informationen zum Zeitpunkt der letzten Änderung in den Dateinamen einfügen kannst:
** `$lastChangeTimestamp` = Zeitstempel der letzten Änderung
** `$lastChangeDatetime` = Datum und Uhrzeit der letzten Änderung
** `$lastChangeYear` = Jahr der letzten Änderung
** `$lastChangeMonth` = Monat der letzten Änderung
** `$lastChangeDay` = Tag der letzten Änderung
** `$lastChangeHour` = Stunde der letzten Änderung
** `$lastChangeMinute` = Minute der letzten Änderung
** `$lastChangeSecond` = Sekunde der letzten Änderung
* Im Katalog wird unten links nun nicht nur das Datum angezeigt, an dem der Katalog erstellt wurde, sondern auch die Uhrzeit. Zusätzlich wird dort auch das Datum und die Uhrzeit der letzten Änderung angezeigt.

[discrete]
=== Prozesse

* Für die Arbeitsschritte Auftragsabwicklung und Auftragsbearbeitung steht nun der Filter *Tag* zur Verfügung. Damit können Aufträge anhand der Tags gefiltert werden, die an ihnen hinterlegt sind. Außerdem kann innerhalb der Filtereinstellungen festgelegt werden, ob exakt oder mindestens nach den gewählten Tags gefiltert werden soll.

'''

[discrete]
=== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Kataloge

* Die Filterfunktionen für die Liste der Kataloge Im Menü *Daten » Kataloge* wurde überarbeitet. Die Filter werden nun erst eingeblendet, wenn du auf das Filter-Icon links oben in der Symbolleiste klickst. Außerdem wurden die folgenden Filter hinzugefügt:
** *Template-Name*
** *Name*
** *ID*
** *Aktiv*
** *Erstellt von*
** *Erstellt bis*
** *Letzte Änderung von*
** *Letzte Änderung bis*

[discrete]
=== OTTO

:otto-master-date: 18.05.2022
:otto-master-link: https://forum.plentymarkets.com/uploads/short-url/11fqROI5mkCDw8JRyndAwlgOzWe.xlsx

include::partial$otto-master-file.adoc[]

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Artikel

* Die Preisberechnung der Kalkulation wird nun auch korrekt angestoßen, wenn der EK automatisch durch die Paketbestandteile berechnet wird.

[discrete]
=== Aufträge

* Das Popup in der Abonnement-UI, wenn Nachrichten im Messenger gelöscht werden sollen, wurde angepasst und es lassen sich nun wieder Nachrichten löschen.
* Es könnte beim händischen Ändern von Preisen in bestimmten Fällen zu einer falschen Preisberechnung kommen.

[discrete]
=== Prozesse

* In der Aktion Retoure anlegen/bearbeiten wurden bereits retournierte Artikel nicht gezählt und standen somit dauerhaft für eine weitere Retoure zur Verfügung. Dieses Verhalten wurde behoben.

--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== CRM

* Im Menü *CRM » Kontakte* im Portlet *Aufträge* wurde die Spalte *Haupt* hinzugefügt. Diese Spalte zeigt den Hauptauftrag einer Gutschrift, Reparatur etc. an. Mit einem Klick auf die ID in der Spalte *Haupt* wird man in den Auftrag weitergeleitet.

[discrete]
=== Ereignisaktionen

* Die Ereignisaktionen *Offene Mengen in Nachbestellung stornieren* und *Gewährleistung anlegen* sind nun im Menü *Einrichtung » Aufträge » Ereignisse* verfügbar.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== CRM

* Nach ändern der Tabellenspalten des Kontos wurden diese beim nächsten Aufruf nicht geladen. Dies ist nun behoben.

--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|link:https://marketplace.plentymarkets.com/adcelltracking_6493[ADCELL Conversion Tracking^]
|2.0.15
|-

|link:https://marketplace.plentymarkets.com/addressdoctor_6106[AddressDoctor^]
|1.2.30
|-

|link:https://marketplace.plentymarkets.com/itemgridwidget_55036[Artikel-Listen Raster, Slider oder Einzeldarstellung^]
|1.0.8
|Aufgrund von Änderungen an bestehenden Widgets müssen die ShopBuilder-Inhalte im Menü *CMS » ShopBuilder* über die Schaltfläche *Inhalte neu generieren* aktualisiert werden.

|link:https://marketplace.plentymarkets.com/cfourcereselectronic5_6861[Electronic Theme^]
|5.1.0
|-

|link:https://marketplace.plentymarkets.com/edon_6618[FairGeben^]
|1.3.5
|-

|link:https://marketplace.plentymarkets.com/formatdesigner_6483[FormatDesigner^]
|1.3.1
|-

|link:https://marketplace.plentymarkets.com/galaxus_4788[Galaxus.ch^]
|1.12.6
|-

|link:https://marketplace.plentymarkets.com/googletagmanagerultimate_54789[Google Tag Manager + Conversions API | 18 Tools in einem^]
|1.2.9
a| * Der link:https://felixri.es/gtmconfig[Konfigurator^] muss erneut durchlaufen werden
* Nutze beim Import im Google Tag Manager die Option "Zusammenführen", wenn du eigene Anpassungen an der Konfiguration vorgenommen hast
* Nutze die Option "Überschreiben", wenn du die Standardkonfiguration verwendest

|link:https://marketplace.plentymarkets.com/elasticexportidealode_4723[idealo.de^]
|3.3.27
|-

|link:https://marketplace.plentymarkets.com/shopboosterparams_55043[In 2 min zu kürzeren Ladezeiten - ShopBooster Add-on^]
|1.0.3
|Falls du Facebook, LinkedIn oder Microsoft Ads im Einsatz habt, kannst du diese Parameter einfach in der Standard-Konfiguration ergänzen und hinten an die Liste anhängen (mit Komma trennen): *fbclid,li_fat_id,msclkid*

|link:https://marketplace.plentymarkets.com/multicontentwidget_6082[Multicontent Toolbox^]
|4.7.11
|-

|link:https://marketplace.plentymarkets.com/mobilenavigation_55038[Optimierte mobile Navigation^]
|1.0.6
|-

|link:https://marketplace.plentymarkets.com/paypal_4690[PayPal Checkout^]
|6.0.6
|-

|link:https://marketplace.plentymarkets.com/shopify_4944[Shopify.com^]
|2.10.10
|-

|link:https://marketplace.plentymarkets.com/cytitemavailabilitynotification_6906[Verfügbarkeitsbenachrichtigung mit Statistik^]
|1.4.5
|-

|link:https://marketplace.plentymarkets.com/woocommerce_5102[woocommerce.com^]
|3.0.4
|-

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

====
