= Changelog 7. Dezember 2022
:author: kevin-stederoth
:sectnums!:
:page-index: false
:page-aliases: ROOT:changelog.adoc
:startWeekDate: 1. Dezember 2022
:endWeekDate: 7. Dezember 2022

// Ab diesem Eintrag weitermachen: LINK EINFÜGEN

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Artikel-UI (Neu)

* Es ist jetzt möglich Artikeletiketten in der neuen Artikel-UI zu erstellen. Zusätzlich hat man auf der Variantendetailansicht die Möglichkeit einen spezifischen Lagerort für das Etikett zu wählen.
* Es ist jetzt möglich, eine Variante zur neuen Hauptvariante zu machen.

[discrete]
=== Aufträge

* In der Detailansicht der neuen Auftrags-UI können jetzt die verwendeten Umsatzsteuersätze angezeigt werden.
* In der Auftragsanlage wird nun die Kundenbewertung angezeigt.
* Im letzten Schritt der neuen Auftragsanlage wurde im Feld *Gutscheincodes* ein neuer Button hinzugefügt, über den man externe und interne Gutscheincodes einlösen kann.
* Die *Auftragsherkunft* ist nun ein Standardfilter in der Auftragsübersicht.
* Die Spalte *Externe Auftrags-ID* ist nun eine Standardspalte in der Tabelle der Auftragsübersicht.
* In den Auftragsdetails ist nun standardmäßig auch der Bereich *Messenger* verfügbar, der direkt neben den Notizen zu finden ist. Diese Änderung gilt für alle Auftragstypen.
* In der neuen Auftrags-UI werden bei den Auftragsreferenzen nun nicht mehr nur direkte Eltern- und Kindaufträge, sondern alle verwandten Aufträge angezeigt.
* m Menü *Einrichtung » Aufträge » Auftragstypen » Lieferauftrag* wurde bei der Einstellung *Aufträge in Lieferaufträge splitten nach* die neue *Option Lager- und Netto-Warenbestand >= Menge Auftragsposition* hinzugefügt. In diesen Schritt wurde außerdem die Option *Lager- und Netto-Warenbestand* in *Lager- und Netto-Warenbestand > 0* umbenannt.

[discrete]
=== CRM

* Im Assistenten Messenger-Konfiguration wurde im Schritt Einstellungen für den E-Mail-Empfang eine Einstellung hinzugefügt, mit der man die Benachrichtigungen über neue Nachrichten über den Messenger aktivieren bzw. deaktivieren kann. Wenn diese Einstellung deaktiviert ist, erhältst du über das Glocken-Symbol oben rechts im plentymarkets Backend keine Benachrichtigungen mehr bei Erhalt neuer Nachrichten über den Messenger.
* Wenn man im EmailBuilder eine bestehende Vorlage von einem Ordner in einen anderen Ordner verschiebt, wird ab sofort der Zielordner aufgeklappt.

[discrete]
=== Prozesse

* In der Prozessbearbeitung kannst du jetzt den *Namen* und die *ID* als Überschrift sehen. Damit kannst du bei mehreren Prozessen einfacher den Überblick behalten und es ist außerdem möglich, den Namen und die ID zu kopieren.
* Wir haben in den Prozessen die neue Subaktion *Generieren* eingeführt, mit der ihr die Möglichkeit habt, folgende Dokumente vorab zu generieren:
** Rechnung
** Mahnung
** Lieferschein
** Gutschrift
** Korrekturbeleg
** Reparaturschein
** Auftragsbestätigung
** Angebot
** Rücksendeschein
** Gelangensbestätigung
** Abhol-/Lieferschein
** Stornobeleg Mahnung
** Stornobeleg Rechnung
** Stornobeleg Gutschrift
** Proformarechnung

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Artikel-UI (Neu)

* Wenn man in der neuen Artikel-UI Bestelleigenschaften verknüpfen möchte, dann werden im Dialog zur Auswahl der gewünschten Eigenschaften jetzt ausschließlich Bestelleigenschaften angezeigt.

[discrete]
=== Aufträge

* Im zweiten Schritt der neuen Auftragsanlage wurde eine Warnmeldung mehrfach für dieselbe Varianten-ID angezeigt, wenn der Preis niedriger war als der Verkaufspreis. Die Warnmeldung wird nun lediglich im letzten Schritt angezeigt und auch die mehrfache Anzeige wurde behoben.
* In der Artikeltabelle der neuen Auftragsanlade wurden die Spalten *System-EK*, *Lager* und *Nettobestand* nicht richtig angezeigt. Dieser Fehler wurde behoben.
* In der Übersicht der neuen Auftrags-UI wurde immer die Systemwährung angezeigt - auch wenn der Auftrag eine andere Währung hatte. Dies wurde behoben.
* In der neuen Auftrags-UI (Testphase) wurde das Dokumenten-Widget nach der Erstellung neuer Dokumente nicht neu geladen. Dieser Fehler wurde behoben.
* In der neuen Auftrags-UI (Testphase) wurden Aktionsgutscheine und Mehrzweckgutscheine in der Artikeltabelle nicht angezeigt. Dieser Fehler wurde behoben.
* In der UI für Bestellungen wurden Tags nicht gespeichert wenn eine neue Umbuchung erstellt oder eine bestehende Umbuchung bearbeitet wurde. Dieser Fehler wurde behoben.
* Der Filter *Kontaktdaten* in der Auftragssuche hat nicht funktioniert. Dies wurde behoben.
* In der neuen UI zur Auftragsanlage wurden Varianten bei der Wahl einer Vorlage im ersten Schritt in der falschen Menge zum Warenkorb hinzugefügt. Dies wurde behoben, sodass nun die korrekte Varianten-Menge aus der Auftragsvorlage übernommen wird.

[discrete]
=== CRM

* Die Variable *Tracking-URL* im EmailBuilder hat keinen klickbaren Link ausgegeben, der zur Seite des Versanddienstleisters führt. Dieses Verhalten wurde behoben.
* Bestehende Kontaktoptionen im Kontaktdatensatz konnten nicht aktualisiert und dann gespeichert werden, wenn man die Portlets *Tags*, *Eigenschaften* oder *Optionen* aus der MyView entfernt hat. Dieses Verhalten wurde behoben.

[discrete]
=== Prozesse

* Bei der Anmeldung des Versands in den Prozessen konnte es zu einer Fehlermeldung (`Response is NOT a valid JSON document`) im Backend-Log kommen. Dieses Verhalten wurde behoben.

--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.



--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|
|
|

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

====
