= Changelog 29. Juni 2022
:author: kevin-stederoth
:sectnums!:
:page-index: false
:page-aliases: ROOT:changelog.adoc
:startWeekDate: 23. Juni 2022
:endWeekDate: 29. Juni 2022

// Ab diesem Eintrag weitermachen: LINK EINFÜGEN

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Kaufland.de

* Du kannst ab jetzt mehrere Konten für Kaufland einrichten. Im Menü *Einrichtung » Märkte » Kaufland.de » Einstellungen » [Kaufland-Konto öffnen]* wurden dazu die Tabs Konten und Neues Konto hinzugefügt.
** Im Tab *Konten* werden alle Konten angezeigt, die du für Kaufland eingerichtet hast. +
*_Hinweis:_* Momentan wird hier nur ein Konto angezeigt, da du bisher nur ein Konto für Kaufland in plentymarkets einrichten konntest. Hier wird also nur dein bisheriges Kaufland-Konto angezeigt.
** Im Tab *Neues Konto* kannst du ein neues Konto für Kaufland hinzufügen.

+
Du kannst für jedes Konto, das du für Kaufland einrichtest, einen Anzeigenamen vergeben. Das Konto wird dann unter diesem Namen im Tab *Konten* angezeigt. Der Anzeigename wird nur in deinem plentymarkets System verwendet und dient einer besseren Übersicht.
* Außerdem wurde im Menü *Einrichtung » Märkte » Kaufland.de » Einstellungen » Tab: Konten » [Kaufland-Konto öffnen]* die Einstellung *Konfiguration für alte Aufträge verwenden* hinzugefügt.
Diese Einstellung ist für dein bisheriges Kaufland-Konto standardmäßig aktiviert. Damit wird sichergestellt, dass Aufträge, die vor dem Update auf Kaufland generiert wurden, in plentymarkets verarbeitet werden können. Für neue Kaufland-Konten ist diese Einstellung nicht relevant und deshalb in einer neuen Konfiguration standardmäßig deaktiviert.
+
[NOTE]
.Kein To-Do
======
Du musst keine weiteren Schritte vornehmen. Alle Einstellungen deines Kaufland-Kontos bleiben auch nach dem Update bestehen. Du findest dein Kaufland-Konto jetzt im Menü *Einrichtung » Märkte » Kaufland.de » Einstellungen » Tab: Konten*.

Weitere Informationen findest du auf der Handbuchseite xref:maerkte:kaufland-de-einrichten.adoc#200[Kaufland.de einrichten].
======

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Artikel

* Es gibt nun wieder eine Fehlermeldung im Log, wenn eine Preiskalkulation eine Eigenschaft nutzt, die nicht mit der Variante verknüpft ist.

[discrete]
=== Aufträge

* Es war bei den Auftragsvorlagen nicht möglich einen Status mit mehr als 2 Nachkommastellen auszuwählen.
* Die Fehlermeldungen in der Status-UI wurden nun wieder angezeigt und der Text wurde angepasst.

[discrete]
=== Kataloge

* Im Katalogformat *Warenbestand* werden die Einstellungen zum Dezimaltrennzeichen nun korrekt beachtet.

--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.



--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|
|
|

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

====
