= Changelog 24. August 2022
:author: kevin-stederoth
:sectnums!:
:page-index: false
:startWeekDate: 18. August 2022
:endWeekDate: 24. August 2022

// Ab diesem Eintrag weitermachen: https://forum.plentymarkets.com/t/fix-variable-itemasin-gibt-keinen-wert-aus-fix-variable-itemasin-does-not-return-value/692243

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== CRM

* Das Feld *Eigner* im Bereich *Kontaktdetails* des Kontaktdatensatzes beinhaltet nun eine Vorschlagsliste. Wenn du also einen Buchstaben des Eignernamens in diesem Feld eingibst, schlägt dir das System bereits gespeicherte Eigner zum Auswählen vor.

[discrete]
=== plentyBI

* Bisher mussten für die Erstellung von Kennzahlen spezielle Rohdatenformate im Menü *Einrichtung » plentyBI » Rohdaten* aktiviert werden. Dieser Schritt ist nun nicht mehr notwendig. Stattdessen werden die benötigten Rohdatenformate automatisch im Hintergrund aktiviert, wenn neue Kennzahlkonfigurationen im Menü *Einrichtung » plentyBI » Kennzahlen* oder aus einer bestehenden Dashboard-Ansicht heraus xref:business-entscheidungen:myview-dashboard.adoc#200[angelegt] und abgespeichert werden.
+
[NOTE]
.Kein To-Do
======
Die Änderung hat keine Auswirkungen auf bestehende Kennzahlkonfigurationen.
======

[discrete]
=== Prozesse

* Wir haben eine die Einstellung xref:automatisierung:aktionen.adoc#380[Etiketten generieren] eingeführt, mit der man bestimmen kann, welche Etiketten gedruckt bzw. gespeichert werden sollen:
** *Etiketten immer generieren* +
Dies bildet das bisherige Verhalten ab. Es werden neue Etiketten registriert und sowohl vorhandene als auch neue Etiketten gedruckt/gespeichert.
** *Etiketten generieren, wenn keine existieren* +
Existieren bereits Etiketten, werden diese gedruckt/gespeichert. Ansonsten werden neue Etiketten registriert und gedruckt/gespeichert.
** *Bestehende Etiketten verwenden* +
Es werden nur vorhandene Etiketten gedruckt/gespeichert. Existieren keine Etiketten, wird eine entsprechende Fehlermeldung angezeigt.

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Plugins

* Wenn du ein Plugin-Set kopierst, kannst du das ursprüngliche Plugin-Set nicht mehr löschen bis der Kopiervorgang abgeschlossen ist. Durch diese Änderung werden mögliche Probleme beim Kopiervorgang verhindert.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Aufträge

* Aufträge können nicht mehr ohne die Berechtigung *Aufträge » Aktualisieren* kopiert werden.
* In der Statistik der Retourengründe wurde die Versandkostenposition bei *Zurückgesendeten Artikel* in der Daten-Tabelle mit einberechnet diese werden nun korrekt ausgeschlossen.
* In der Abonnement-UI werden die Felder *Währung* und *Versandkosten* nun richtig gespeichert.

[discrete]
=== CRM

* Beim Verwenden der Variable *URL zum Variantenbild* (`orderItem.formattedImageUrl`) im EmailBuilder wurde nur das Bild der ersten Variante in der E-Mail ausgegeben. Dieses Verhalten wurde behoben. Ab sofort werden die Bilder aller enthaltenen Varianten in der E-Mail ausgegeben.

[discrete]
=== Dokumente

* Die Auswahl für den Filter der Zahlungsarten in der Fulfillment-UI war auf Zahlungsarten begrenzt, die als *Aktiv im Backend* galten, nicht wie an anderen Stellen wo Zahlungsarten in der Auswahl angezeigt werden die *Suchbar im Backend* sind. Dies wurde angeglichen.

[discrete]
=== Ereignisaktionen

* Bei Verwendung des Filters *Auftragslager* konnte es bei der Einstellung *Mehrere Lager pro Auftrag* dazu kommen, dass dieser fälschlicherweise für Aufträge akzeptiert wurde, obwohl diese nur ein Lager haben. Dieses Verhalten konnte nur in einer Kombination der Lagereinstellung (*Zuordnung des Lager* mit der Einstellung *a) pro Auftrag kann ein Lager zugeordnet werden*) und Aufträgen mit Lieferaufträgen auftreten. Dies wurde behoben.

[discrete]
=== Fulfillment

* Bei der Versandanmeldung über UPS an amerikanische Adressen in den USA kam es zu einer Fehlermeldung. Dies lag an der Adressvalidierung bezüglich der Reihenfolge von Hausnummer und Straßenname. Dieses Verhalten wurde behoben. Die Versandanmeldung über UPS in die USA funktioniert nun wieder wie gewohnt.

[discrete]
=== Prozesse

* Es war bisher nicht möglich, die Aktion *Retoure anlegen/bearbeiten* für Lager zu benutzen, die keine Lagerorte haben. Nun bieten wir die Möglichkeit an, den Standard-Lagerort auszuwählen.

--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== plentyBI

* Ab sofort kannst du leichter einsehen, welche Kennzahlen in welchen Dashboard-Ansichten verwendet werden.
+
Öffne dazu das Menü *Einrichtung » plentyBI » Kennzahlen*. Klicke auf eine bereits angelegte Kennzahl. In der Detailansicht der Kennzahl steht nun der Bereich *Einsehen* zur Verfügung. Klappe den Bereich auf und klicke auf *Verwendung einsehen*. Danach wird eine Liste mit Links zu Dashboard-Ansichten angezeigt, in denen die Kennzahl genutzt und angezeigt wird.

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Artikel

* In der neuen Artikel-UI wird beim Filtern nach Lieferanten nun an erster Stelle der Firmenname angezeigt und anschließend der Nach- und Vorname des Kontakts. Die Sortierung innerhalb des Filters erfolgt alphabetisch.

[discrete]
=== Payment

* Wenn du im alten Dashboard das Element *Zahlungen* aktiviert hattest, wurdest du z.B. beim Klick auf die Anzahl der nicht zugeordneten Zahlungen oder der Zahlungen am aktuellen Tag zum alten Menü *Aufträge » Zahlungsverkehr (veraltet)* weitergeleitet. Dies wurde geändert. Ab sofort wirst du auf die neue UI im Menü *Aufträge » Zahlungsverkehr* weitergeleitet.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Artikel

* Das Speichern der Bildverknüpfung für Varianten über die Neue Artikel-UI ist jetzt wieder möglich.

[discrete]
=== Aufträge

* In der Auftrags-UI konnte der Upload bei einen Bestellmerkmal von Typ *Datei* nicht geöffnet werden. Es ist dabei immer zu einen Access-Denied Fehler gekommen. Diese wurde nun behoben.
* Beim Finanzbuchhaltungs-Export hat die Einstellung *Markiere exportierte Datensätze* nicht korrekt funktioniert, da ein nicht exportierter Auftrag als exportiert markiert wurde.
+
Wurden nach dem Export neue Dokumente erstellt, wurden diese nicht im Export angezeigt, wenn die Option *Nur markierte Aufträge exportieren* aktiviert war. Dieses Verhalten wurde behoben und nun wird jedes exportierte Dokument markiert. Diese Änderung greift nur für Dokumente, die nach dieser Änderung erstellt wurden.

[discrete]
=== CRM

* Beim Versuch, das SEPA-Lastschriftmandat als Anhang in einer E-Mail-Vorlage zu versenden, ist es in manchen Systemen zu einem Fehler gekommen. Dieses Verhalten wurde behoben.

[discrete]
=== Ereignisaktionen

* Wenn in einer Ereignisaktion eingestellt ist, dass die E-Mail-Vorlage an die Lieferadresse gesendet werden soll, dort aber keine E-Mail-Adresse gespeichert ist, wird als Fallback die E-Mail-Adresse, die am Kontakt gespeichert ist, gesendet. Dieser Fallback hat nicht auf allen Systemen funktioniert. Dieses Verhalten wurde behoben; der Fallback auf die E-Mail-Adresse am Kontakt funktioniert wieder.

--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|link:https://marketplace.plentymarkets.com/axytosinvoice_54780[axytos Rechnungskauf 3.0^]
|1.1.0
|-

|link:https://marketplace.plentymarkets.com/backmarket_6485[Backmarket^]
|1.3.2
|-

|link:https://marketplace.plentymarkets.com/dhlshippingstates_55231[DHL Versandstatus Tracking^]
|1.0.1
|-

|link:https://marketplace.plentymarkets.com/glsshippingstates_55045[GLS Versandstatus Tracking^]
|1.0.3
|-

|link:https://marketplace.plentymarkets.com/etsy_4689[Etsy^]
|2.1.32
|-

|link:https://marketplace.plentymarkets.com/fahrsicherung_55252[FahrSicherung^]
|1.0.5
|-

|link:https://marketplace.plentymarkets.com/findologic_6390[Findologic - Product Discovery Platform^]
|3.9.5
|-

|link:https://marketplace.plentymarkets.com/multicontentwidget_6082[Multicontent Toolbox^]
|4.7.19
|-

|link:https://marketplace.plentymarkets.com/mytoys_54776[MyToys^]
|1.0.39
|-

|link:https://marketplace.plentymarkets.com/paypal_4690[PayPal Checkout^]
|6.0.16
|-

|link:https://marketplace.plentymarkets.com/shopify_4944[Shopify.com^]
|2.1.12
|Händler:innen, die einen plentymarkets Artikel für Shopify Gutscheine erstellt haben und diesen Artikel über die SKU abgleichen, müssen diesen Artikel mit einem Mehrwertsteuersatz von 0% speichern. Sonst wird beim Import von Shopify-Bestellungen automatisch die Mehrwertsteuer auf den Gutschein angewendet.

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

====
