= Changelog 10. August 2022
:author: kevin-stederoth
:sectnums!:
:page-index: false
:page-aliases: ROOT:changelog.adoc
:startWeekDate: 4. August 2022
:endWeekDate: 10. August 2022

// Ab diesem Eintrag weitermachen: LINK EINFÜGEN

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== CRM

* Der Fehler bei der E-Mail-Vorschau in den Nachbestellungen mit alten Vorlagen wurde korrigiert.
* Der Fehler beim Speichern von Kontaktoptionen wie E-Mailadressen oder Telefonnummer in der alten Kontakt-UI wurde korrigiert.

[discrete]
=== eBay

* Im Menü *Einrichtung » Märkte » eBay » Einstellungen » Tab: Kontoeinstellungen* wurde die Einstellung *Auftragsstatus für Aufträge mit fehlgeschlagener Rückerstattung* hinzugefügt.
+
*_Hintergrund_*: Mit der Ereignisaktion *eBay-Rückerstattung veranlassen* führst du eine Rückerstattung für einen Auftrag durch. Mit der Einstellung *Auftragsstatus für Aufträge mit fehlgeschlagener Rückerstattung* legst du fest, in welchen Status Aufträge geschoben werden sollen, wenn diese Ereignisaktion nicht ausgeführt werden konnte.

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== plentyBI

* Das Element *Globales Zeitintervall* kann künftig nicht mehr als separates Element zum Dashboard hinzugefügt werden. Die Funktionalität wurde stattdessen vollständig in das Element *Globale Filter* überführt. Um das globale Zeitintervall zu verändern und die Daten auf dem Dashboard entsprechend filtern, muss von nun an das Element *Globale Filter* auf dem Dashboard platziert und eingerichtet werden. Die notwendigen Einstellungen sind auf der Handbuchseite xref:business-entscheidungen:myview-dashboard.adoc#850[Dashboard] beschrieben.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== CRM

* Der dynamische Anhang *Voucher* im EmailBuilder wurde nicht an die E-Mail-Vorlage angehangen, wenn ein Gutschein gekauft wurde. Dieses Verhalten wurde behoben.
* n einigen Systemen konnten E-Mail-Vorlagen aus dem Mail-Tab des Auftrags heraus nicht gesendet werden. Auch das Öffnen der Vorlagenvorschau in diesem Bereich hat nicht immer funktioniert. Dieses Verhalten wurde behoben.
* Wenn man im Kontaktdatensatz im Menü *CRM » Kontakte* eine Adresse eingegeben hat, ohne diese zu speichern, und dann ein anderes Menü, beispielsweise den Auftrag geöffnet hat, waren die bereits eingegebenen Daten der Adresse beim Klick zurück in den Kontaktdatensatz nicht mehr vorhanden. Dieses Verhalten wurde behoben.

[discrete]
=== Spezialexport

* Beim Spezialexport *Finanzbuchhaltung* wird der Preis der letzten Position eines Auftrags so angepasst, dass die Summe der Preise der Positionen der Rechnungssumme entspricht. Dies hatte nicht in allen Fällen funktioniert und wurde jetzt angepasst.

'''

[discrete]
== Gelöscht

Folgende Funktionalität wurde in den letzten 7 Tagen auf *{version}* entfernt.

[discrete]
=== plentyBI

* Das Element *Einfaches Säulendiagramm* wird aus dem plentyBI Dashboard entfernt und ist somit nicht mehr verwendbar. Alternativ kann der Diagrammtyp xref:business-entscheidungen:myview-dashboard.adoc#720[Säulendiagramm] genutzt werden.
+
[NOTE]
.Kein To-Do
======
Hast du bereits ein einfaches Säulendiagramm auf deinem Dashboard eingerichtet und verwendet, musst du nichts weiter tun. Die Daten werden automatisch in ein neues Diagramm vom Typ Säulendiagramm überführt und wie gewohnt angezeigt. Deine vorherigen Einstellungen bleiben dabei unverändert und keine Daten gehen verloren. Zudem gehen durch den Wechsel zum regulären Säulendiagramm keine Einstellungsmöglichkeiten verloren, sodass dir alle gewohnten Funktionalitäten im gleichen Umfang erhalten bleiben.
======

--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.



--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|
|
|

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

====
