= Changelog 13. Juli 2022
:author: kevin-stederoth
:sectnums!:
:page-index: false
:page-aliases: ROOT:changelog.adoc
:startWeekDate: 7. Juli 2022
:endWeekDate: 13. Juli 2022

// Ab diesem Eintrag weitermachen: LINK EINFÜGEN

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Artikel

* Wir haben die Option Neuer Sammelauftrag an den folgenden Stellen im Menü *CRM » Kontakte* hinzugefügt:
** in der Übersicht im Kontextmenü unter *Aufträge*
** im Kontaktdatensatz im Portlet *Aufträge* (Plus-Zeichen)

[discrete]
=== Kataloge

* m Katalog (Format: *Artikel Neu*) lassen sich nun die Felder *Niedrigster Preis der letzten 30 Tage* und *Niedrigster Preis automatisch ermittelt* exportieren.
* Es gab eine Änderung im Katalog, dass man nun im Baum der Exportfelder das Feld *Verkaufspreise* wählt. In dem hinzugefügten Feld lässt sich dann per Dropdown der Preis auswählen.
+
[NOTE]
.Kein To-do
======
Es gab eine Migration, so dass ihr nichts nacharbeiten müsst.
======

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Amazon

* Als erster Schritt des Amazon-Schnittstellen-Upgrades auf die neue Selling Partner API (SP-API) wurde der Autorisierungs-Workflow umgestellt. Damit gehen folgende Änderungen einher:
** Der Amazon-Assistent für die *Grundeinstellungen* wurde im Schritt zur Autorisierung aktualisiert. Ein Button leitet Benutzer:innen in das Amazon-Backend, um plentymarkets zu erlauben, im Namen der Händler:in mit der SP-API zu kommunizieren und plentymarkets die notwendigen Rechte zu gewähren.
** Abgelaufene Tokens für die MWS-API müssen jetzt durch Händler:innen aufgrund des neuen SP-API-Autorisierungs-Workflows manuell erneuert werden.
** Bestehende und gültige Autorisierungen für die MWS-API werden automatisch um die Autorisierung zur SP API erweitert und von plentymarkets migriert. Dies erlaubt einen fließenden Übergang beim Wechsel auf die neue Schnittstelle.

+
[NOTE]
.Hinweis
======
Der neue Autorisierungsworkflow kann sowohl für eine neue Autorisierung als auch die Verlängerung einer bestehender Authorisierung für *MWS und SP-API* genutzt werden.
======

[discrete]
=== CRM

* Wenn man im Suchfeld im Menü *CRM » Kontakte* einen Wert eingegeben hat, wurde bisher an erster Stelle der Suchparameter `ID` angezeigt. Dies wurde geändert. Ab sofort wird an erster Stelle der Suchparameter `Name` angezeigt.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Artikel

* Es gab einen Fehler, dass sich die neue Tagübersicht nicht nach dem Namen sortieren ließ. Diesen Fehler konnten wir beheben.

[discrete]
=== CRM

* Wenn man zwei Mal nacheinander auf das Hauptmenü *CRM* geklickt hat, öffnete sich beim ersten Klick zwar das Menü *CRM » Kontakte*, beim zweiten Klick auf CRM jedoch ein leeres Tab. Dieses Verhalten wurde behoben.
* Menü *CRM » Kontakte*: Wenn ein Kunde sich über den Abmelde-Link vom Newsletter abgemeldet hat, wurde zwar die E-Mail-Adresse aus dem entsprechenden Ordner entfernt. Jedoch waren das Datum des Newsletter-Abonnements im Kontaktdatensatz und der Haken in der Kontakte-Übersicht in der Spalte *Newsletter* immer noch sichtbar. Dieses Verhalten wurde behoben.
* Im Menü *CRM » Kontakte* waren nicht nur Tags sichtbar und auswählbar, die für den Bereich *Kontakte* erstellt worden sind, sondern auch solche Tags, die für andere Bereiche in plentymarkets erstellt worden sind. Dieses Verhalten wurde behoben.

[discrete]
=== Dokumente

* Bei der Erstellung von Auftragsdokumenten konnte es zu einem Fehler kommen, wenn Varianten des Auftrags nicht mehr existiert haben.

--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.



--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|
|
|

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

====
