= Changelog 25. Januar 2023
:author: kevin-stederoth
:sectnums!:
:page-index: false
:startWeekDate: 19. Januar 2023
:endWeekDate: 25. Januar 2023

// Ab diesem Eintrag weitermachen: https://forum.plentymarkets.com/t/neue-auftrags-ui-testphase-fix-fuer-hochladen-externer-rechnung-new-order-ui-test-phase-fix-for-uploading-external-invoice/709204
// Auch diesen Eintrag beachten: https://forum.plentymarkets.com/t/auftragspositionseigenschaft-fuer-lager-bei-paketbestandteilen-order-item-property-for-warehouse-of-bundle-components/708848
// Auch diesen Eintrag beachten: https://forum.plentymarkets.com/t/auftrag-updatedat-zeitstempel-bei-zahlung-order-updatedat-timestamp-on-payment/708850

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Aufträge

* In der neuen Auftrags-UI (Testphase) sind die *Variantennummer* und die *Externe Auftrags-ID* nun für die Schnellsuche in den Filtern der Auftragsübersicht aktiviert. Um die Schnellsuche auszulösen, muss etwas in das Eingabefeld des Filters eingetragen werden.

[discrete]
=== CRM

* Ab sofort kannst du im Messenger Prioritäten in Form von Sternen für Konversationen setzen. Außerdem kannst du Konversationen mit einer bestimmten Priorität über den Filter suchen und die Prioritäten in der Übersicht auf- und absteigend sortieren.

[discrete]
=== Kataloge

* Beim Katalog für Aufträge ist jetzt die Auftragseigenschaft für den Handelsvertreter verfügbar (Typ-ID 992).

[discrete]
=== Mein Konto

* Im Bereich *Verrechnungskonto* deines *Mein Konto*-Bereichs gibt es unter *Verrechnete Buchungen* folgende Neuerungen. Ab sofort kannst du:
** nach dem Verrechnungszeitraum filtern
** nach der Auftrags-ID filtern
** einen Bericht als PDF oder CSV-Datei herunterladen
** die Referenznachrichten in einem Overlay öffnen

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Ereignisaktionen

* Wir haben den Namen der Aktion *Status des Hauptauftrags ändern* zu *Status des Elternauftrags ändern* geändert. Von eurer Seite aus sind keine Änderungen notwendig.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Aufträge

* In der neuen Auftragsanlage wurden die Auftragsdetails im ersten Schritt nicht zurückgesetzt, nachdem ein Auftrag erstellt wurde. Dies wurde behoben.
* In der neuen Auftrags-UI (Testphase) wurden nach Ausführung der Aktion *Warenausgang buchen* und anschließendem Wechsel in einen anderen Auftrag in der Seitennavigation die ursprünglichen Auftragsdetails wiederhergestellt, wenn man zum eigentlichen Auftrag zurück navigierte. Dies wurde behoben.
* In der neuen Auftrags-UI (Testphase) und in der neuen Auftragsanlage hatten die Tabellenspalten mit anpassbarer Größe die falsche Standardbreite, was die Daten unlesbar machte. Dies wurde behoben und eine Standardbreite wurde für jede Spalte hinzugefügt.

[discrete]
=== CRM

* In der Auftragsübersicht wurden die neuen EmailBuilder-Vorlagen an die E-Mail-Adresse gesendet, die in den Kontaktoptionen gespeichert ist. Dieses Verhalten wurde behoben. Die EmailBuilder-Vorlagen werden nun an die E-Mail-Adresse gesendet, die in der Rechnungsadresse des Auftrags gespeichert ist.

[discrete]
=== Plugins

* Bei manchen Plugins (wie dem Wallee-Payment-Plugin) kam es vor, dass die Standard-Container nicht verknüpft werden konnten und einzeln verknüpft werden mussten. Dieser Fehler wurde nun behoben.

[discrete]
=== Prozesse

* Dokumente vom Typ *Lieferschein* und *Angebot*, die über REST an den Hauptauftrag geladen werden, können jetzt wieder von den Prozessen abgerufen werden.

'''

[discrete]
== Entfernt

Folgende Funktionalität wurde in den letzten 7 Tagen in *{version}* entfernt.

[discrete]
=== Artikel

* Wir haben Suchfelder entfernt, die keinen Einfluss auf die Suche haben.

--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Aufträge

* In der neuen Auftrags-UI (Testphase) wurden die optionalen Spalten *Kontakt (Rechnungsadresse*) und *Kontakt (Lieferadresse)* sowie ein optionaler Filter für *Adressdaten* hinzugefügt.

[discrete]
=== CRM

* Im Messenger kannst du ab sofort eigene Ordner erstellen und die Konversationen in einen oder mehrere Ordner verschieben. Füge in der Übersicht die Spalte *Ordner* hinzu, damit du auf einen Blick sehen kannst, in welchen Ordnern die Konversation gespeichert ist. Die Ordner können auch umbenannt und gelöscht werden.

[discrete]
=== Fulfillment

* Wie im neuen Versand-Center kannst du jetzt auch in der Paketinhaltsliste durch einen Klick auf die Paketnummer die Sendungsverfolgung öffnen.

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Aufträge

* In der Detailansicht der neuen Auftrags-UI wurde das Warengewicht falsch berechnet. Dies wurde behoben.
* In der neuen Auftrags-UI (Testphase) waren die Werte der Spalte *Versandkosten* ist der Übersichtstabelle nicht sichtbar. Dies wurde behoben.

[discrete]
=== CRM

* Die Variable für den Gutscheincode hat mehrere Gutscheincodes generiert, wenn diese in der Newsletter Opt-In-E-Mail enthalten war: einmal wenn der Kunde sich für den Newsletter registriert hat und ein weiteres Mal, wenn die Anmeldung zum Newsletter bestätigt wurde. Dieses Verhalten wurde behoben.
* Im Bereich *Sprachabhängige Einstellungen* einer E-Mail-Vorlage im EmailBuilder wurden in der gesendeten E-Mail statt 2 Nachkommastellen standardmäßig 4 Nachkommastellen für das Feld *Anzahl der Dezimalstellen* ausgegeben. Dieses Verhalten wurde behoben. Ab sofort werden standardmäßig 2 Nachkommastellen in gesendeten E-Mails ausgegeben.

--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|link:https://marketplace.plentymarkets.com/edon_6618[FairGeben^]
|1.5.0
|-

|link:https://marketplace.plentymarkets.com/reviewconverter_6843[Google Shopping Produktbewertungen (Sterne)^]
|1.2.0
|-

|link:https://marketplace.plentymarkets.com/mytoys_54776[myToys^]
|1.0.63
|-

|link:https://marketplace.plentymarkets.com/itemvideoplugin_6915[Produkt Video Plugin^]
|1.6.2
|-

|link:https://marketplace.plentymarkets.com/freeshippinggoal_55307[Versandkostenfrei ab Warenwert erreichen^]
|1.0.2
|-

|link:https://marketplace.plentymarkets.com/woocommerce_5102[woocommerce.com^]
|3.2.1
|-

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

App::
+
--

[discrete]
== Geändert

Folgende Änderungen wurden in Version 1.1.12 der *plentymarkets App* veröffentlicht.

* Künftig werden Auftragslisten für die Rollende Kommissionierung bei Auftragsabruf durch mehrere Benutzer nicht mehr zeitgleich, sondern nacheinander generiert.

--

Warehouse-App::
+
--

[discrete]
== Geändert

Folgende Änderungen wurden in Version 1.0.2 der *plentymarkets App* veröffentlicht.

* Künftig werden Auftragslisten für die Rollende Kommissionierung bei Auftragsabruf durch mehrere Benutzer nicht mehr zeitgleich, sondern nacheinander generiert.

--

====
