= Changelog 18. Januar 2023
:author: kevin-stederoth
:sectnums!:
:page-index: false
:page-aliases: ROOT:changelog.adoc
:startWeekDate: 12. Januar 2023
:endWeekDate: 18. Januar 2023

// Ab diesem Eintrag weitermachen: LINK EINFÜGEN

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Artikel

* Wir haben einen Zeichenzähler für die Artikel-Texte, sowie die HTML-, Text-, und Zeichenketten-Eigenschaften eingefügt.
* In der neuen Artikel-UI ist es jetzt möglich, die Varianten-Gruppenfunktion in der Variantenübersicht eines Artikels zu verwenden.
* Es gibt nun einen Schalter unter *Einrichtung > Artikel > Neue Artikel-UI (Testphase)*, um die neue Artikel-UI als Standard Artikel-UI festzulegen. Links aus anderen UIs (z. B. Aufträge) leiten ebenfalls auf die neue Artikel UI um. Diese Einstellung gilt nur für den jeweiligen Nutzer und lässt sich jederzeit aktivieren oder deaktivieren.

[discrete]
=== Aufträge

* In der neuen Auftrags-UI und in der Auftragsanlage kann der Rabatt nun für jeden einzelnen Artikel bearbeitet werden.
* In der neuen Auftrags-UI kannst du im Bereich *Allgemein* eines Auftrags ab sofort die Markierung wählen. Es handelt sich dabei um ein reines Anzeigefeld, d.h. die Markierung kann nicht geändert werden.
* In den Auftragsdetails steht nun der Bereich *Tickets* zur Verfügung. Dieser ist standardmäßig nicht eingeblendet, kann aber über die MyView hinzugefügt werden.
* In der neuen Auftrags-UI kann die Größe der Spalten von nun an in den folgenden Tabellen angepasst werden:
** Tabelle in der Auftragsübersicht;
** Tabelle der Auftragspositionen (in der Übersicht sowie in den Auftragsdetails);
** Tabelle der Variantensuche in der Ansicht Artikel bearbeiten;
** Tabelle des Warenkorbs in der Ansicht Artikel bearbeiten

[discrete]
=== CRM

* Wenn eine Adresse mit einem Auftrag verknüpft ist, kann man diese Adresse nicht löschen. Wir haben im Hintergrund die Funktion eingebaut, dass die Relation „Kontakt/Adresse“ jetzt entfernt wird, wenn das Löschen der Adresse fehlschlägt. Die neue Meldung im Backend lautet: `Die Adresse konnte nicht gelöscht werden, weil sie mit einem Auftrag verknüpft ist. Die Relation zum Kontakt wurde gelöscht.`
* Im Messenger wurde der Filter *Posteingang* hinzugefügt, mit dem du nach Konversationen aus einem bestimmten Posteingang suchen kannst.

[discrete]
=== Fulfillment

* Unter der Paketnummer im Versand-Center 2.0 ist nun die Sendungsverfolgung für das jeweilige Paket hinterlegt und kann durch einen Klick auf die Nummer direkt aufgerufen werden.
* Die zuletzt verwendeten Werte für den Versanddienstleister, die zwei Auftragsstatusfelder sowie für den Versanddientsleister im Fall einer Retoure bleiben ab sofort im Cache, so dass diese Einstellungen nicht wieder neu ausgewählt werden müssen.

[discrete]
=== Kataloge

* Im Menü *Daten » Katalogexportstatus* kannst du ab sofort die Kataloge auch danach filtern, ob sie Fehler enthalten oder nicht. Weitere Informationen findest du auf der Handbuchseite xref:daten:catalogues-status.adoc#overview-filters[Exportstatus prüfen].

[discrete]
=== Shopify-App

* In der neuen Shopify-App haben wir die folgenden Funktionen ergänzt:
** Die Verbindungsbereitschaft prüfen.
** Exportbedingungen einer Variante prüfen.
** Alle 10 Minuten einen Artikel manuell exportieren.
** Alle 5 Minuten den Warenbestand einer Variante oder eines ganzen Artikels exportieren.
** Die plentymarkets Auftrags-ID anhand der Shopify-Auftragsnummer finden.
** Eine Artikelbereinigung planen.

+
Im Zuge der Neuerung wurde auch xref:externe-webshops:shopify-app.adoc#plugin-help[die Handbuchseite zur Shopify-App] erweitert. Eine Checkliste für den Variantenexport hilft dir dabei, deine Varianten für den Export flott zu machen.

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Aufträge

* Bisher konnte die PDF-Datei für Mehrzweckgutscheine nur erstellt werden, wenn der dazugehörige Auftrag vollständig bezahlt war. Bei überbezahlten Aufträgen hingegen wurde keine PDF-Datei erstellt. Nun werden PDFs auch für überbezahlte Aufträge erstellt.
* In der neuen Auftragsanlage war in den Eingabefeldern *Preis (brutto)* und *Preis (netto)* im 2. Schritt der Warenkorb-Tabelle der Wert `0` nicht möglich. Dies wurde behoben.
* In der Auftragsübersicht ist es im Dialog *Referenzierte Bestellungen anzeigen* zu einen Fehler gekommen, wenn man einen Auftrag öffnen wollte. Dieser Fehler wurde behoben.
* Im letzten Schritt der neuen Auftragsanlage wurde bei der *Artikelmenge (gesamt)* die Menge der Auftragsposition angezeigt und nicht die Summierten mengen der einzelnen Positionen. Dieser Fehler wurde behoben.
* In der neuen Auftrags-UI hat das Duplizieren des Auftrags-Tabs nicht funktioniert. Dies wurde behoben.

[discrete]
=== Elastischer Export

* Im Elastischen Export hat der Filter für den Mandanten nicht funktioniert. Wenn dieser Filter gesetzt war, wurde keine CSV-Datei ausgegeben. Beim Export mit einem Limit höher als 9999 wurde eine leere Datei ausgegeben. Dieses Verhalten wurde behoben.

--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.



--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|
|
|

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

====
