= Changelog 26. April 2023
:author: kevin-stederoth
:sectnums!:
:page-index: false
:page-aliases: ROOT:changelog.adoc
:startWeekDate: 20. April 2023
:endWeekDate: 26. April 2023

// Ab diesem Eintrag weitermachen: LINK EINFÜGEN

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Aufträge

* Die folgenden Änderungen wurden in der neuen Auftrags-UI implementiert:
** In der Kompaktansicht wurde in den Feldern für *Rechnungsadresse* und *Lieferadresse* der ISO-Code des Landes neben der Stadt hinzugefügt.
** In der Kompaktansicht wurde in den Feldern für *Rechnungsadresse* und *Lieferadresse* der eBay-Name vor dem Namen eingefügt.
** In der Detailansicht des Auftrags wurden die Adressoptionen innerhalb des Adress-Widgets hinzugefügt und können ein- und ausgeklappt werden.
** In der Detailansicht des Auftrags enthält das Adress-Widget nun auch den eBay-Namen als Adressoption.
** Die Adressoptionen wurden in den Spalten *Rechnungsadresse* und *Lieferadresse* der Übersichtstabelle in der Auftragsübersicht hinzugefügt.

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Aufträge

* Die folgenden Änderungen wurden an der Kompaktansicht vorgenommen:
** Die Kompaktansicht ist in neuen Systemen standardmäßig aktiviert.
** Gesetzte Filter werden automatisch übernommen, wenn man zwischen der Kompaktansicht und der Listenansicht wechselt.
** Die Suche wird ausgelöst, wenn man zwischen der Kompaktansicht und der Listenansicht wechselt.
** Die Standardeinstellung für *Farbliche Markierung* wurde zu blau für die Adressfelder und zu grün für die Felder *Rechnungsnummer* und *Kontakt-ID* geändert.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Aufträge

* In der Kompaktansicht werden die Symbole jetzt korrekt zentriert, wenn die Einstellung *Nur Symbol anzeigen* aktiviert wurde.
* Es wurde beim Klicken auf den Status im Dashboard kein Filter in der neuen Auftrags-UI gesetzt und die Suche wurde nicht ausgelöst. Das wurde jetzt behoben.

--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.



--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|
|
|

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

====
