= Changelog 1. März 2023
:author: kevin-stederoth
:sectnums!:
:page-index: false
:page-aliases: ROOT:changelog.adoc
:startWeekDate: 23. Februar 2023
:endWeekDate: 1. März 2023

// Ab diesem Eintrag weitermachen: LINK EINFÜGEN

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Artikel (Neue UI)

* In der Variantenansicht ist es nun möglich, sowohl die verknüpften Kategorien als auch die Liste der Kategorien beim Hinzufügen zu sortieren. Die entsprechenden Einstellungen sind im Editiermodus der Ansicht am Kategorie-Element zu finden.
** Sortierung in der Tabelle nach:
*** Name der Kategorie
*** Position der Verknüpfung
*** Position der Kategorie
*** ID der Kategorie
** Sortierung im Picker:
*** Name der Kategorie
*** Position der Kategorie

[discrete]
=== CRM

* Im Messenger wurde der Filter *Absender:in* hinzugefügt.

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== plentyShop LTS

Die Anzahl der maximalen Einträge pro Sitemap für plentyShops wurde von 50000 auf 25000 reduziert, da es aufgrund der Dateigröße der Sitemaps vermehrt zu Ablehnungen seitens Google kam.

Bitte überprüft, ob ihr in den von euch verwendeten SEO-Tools (bspw. Google Search Console) die allgemeine Sitemap hinterlegt habt (www.beispieldomain.de/sitemap.xml) oder ob ihr separate sitemap.xml Dateien (bspw. `Sitemap_item.xml`, `Sitemap_item_2.xml`, etc.) hinterlegt habt. Falls ihr nur die allgemeine Sitemap hinterlegt habt, besteht eurerseits kein weiterer Handlungsbedarf.

Falls ihr in euren SEO-Tools separate Sitemap-Dateien gelistet habt, kann es sein, dass sich die Anzahl der Sitemap-Dateien durch die Reduktion der Einträge pro Sitemap erhöht. In diesem Fall solltet ihr die hinzugekommenen Sitemap-Dateien in euren SEO-Tools ergänzen, um sicherzustellen, dass diese Seiten weiterhin wie gewünscht indexiert werden können.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Aufträge

* In der neuen Auftragsanlage konnte der letzte Schritt oben über den Stepper erreicht werden, obwohl die Warenkorbtabelle ungültige Verkaufspreise enthielt. Dies wurde behoben.
* In einer Retoure war es möglich, für eine Auftragsposition die komplette Menge vom Hauptauftrag zurückzubuchen. Dies wurde nun auf die Menge in der Retoure beschränkt.
* In der Detailansicht eines Auftrags funktionierte die Suche nach einem Status nicht richtig. Dies wurde behoben.

'''

[discrete]
== Gelöscht

Folgende Funktionalität wurde in den letzten 7 Tagen auf *{version}* entfernt.

[discrete]
=== Fulfillment

* Die DHL Freight-Anwendung ist obsolet und wurde daher aus dem Menü entfernt.

--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.



--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|
|
|

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

====
