= Changelog 8. Februar 2023
:author: kevin-stederoth
:sectnums!:
:page-index: false
:startWeekDate: 2. Februar 2023
:endWeekDate: 8. Februar 2023

// Ab diesem Eintrag weitermachen: https://forum.plentymarkets.com/t/fix-waehrung-bei-der-erstellung-von-nachbestellungen-fix-currency-when-creating-a-purchase-order/710986
// Auch diesen Eintrag beachten: https://forum.plentymarkets.com/t/aenderung-umzug-der-persoenlichen-einstellungen-in-das-dropdown-menue-unter-dem-plenty-p-change-personal-settings-move-the-dropdown-menu-under-the-plenty-p/710834

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Artikel (Neue UI)

* In der neuen Artikel-UI kann man jetzt Einstellungen für die Sortierung der Verkaufspreisverknüpfungen in der Tabelle und dem Verkaufspreispicker vornehmen. Mögliche Sortierungen in der Tabelle:
** Verkaufspreis Name
** Verkaufspreis Position
** Verknüpfter Verkaufspreis aktualiert am
** Verkaufspreis ID
** Verkaufspreis Wert

+
Mögliche Sortierung in dem Picker:
** Verkaufspreis Name
** Verkaufspreis Position
** Verkaufspreis Wert
* In der neuen Artikel-UI gibt es nun einen Link zum entsprechenden Auftrag einer Warenbewegung (sofern verfügbar).
* Für neue Systeme gibt es nun vereinfachte Standard Ansichten. Dies betrifft die Artikelansicht, die Variantenansicht, die Artikeltextansicht und die Eigenschaftenansicht. Hintergrund ist die Reduzierung von intial angezeigten Datenfeldern für Neukunden um einen leichteren Einstieg zu gewährleisten.
* In der Variantenansicht ist es nun möglich, sowohl die verknüpften Barcodes als auch die Liste der Barcodes beim Hinzufügen nach Name oder Typ zu sortieren. Die entsprechenden Einstellungen sind im Editiermodus der Ansicht am Barcode-Element zu finden.

[discrete]
=== Aufträge

* In der Übersicht der neuen Auftrags-UI wurde bei der Übersicht des Warenbestands ein Link zu den Nachbestellungen hinzugefügt.
* In der Übersicht der neuen Auftrags-UI wurde bei der Übersicht des Warenbestands die Spalte für den reservierten Bestand hinzugefügt.

[discrete]
=== CRM

* Ab sofort kannst du in der Übersicht des Messengers die Breite der Tabellenspalten nach deinen Wünschen anpassen.
* Ab sofort kannst du eine geöffnete Konversation per Klick wieder schließen, um in die Übersicht des Messenger zurückzukehren.

[discrete]
=== Shopify-App

Ab 1. April 2023 können wir die Fulfillment-Informationen nicht mehr wie bisher an die Shopify-API senden. Shopify hat diese Änderung link:https://shopify.dev/apps/fulfillment/migrate[schon länger angekündigt^].

Deshalb haben wir bereits neue Berechtigungen in der plentymarkets-App eingeführt. Das To-Do dazu findest du in link:https://forum.plentymarkets.com/t/shopify-app-neue-rechte-erforderlich-shopify-app-new-permissions-required/707136[einem älteren Changelog^].

Wir haben plentymarkets nun aktualisiert, um die neuen Shopify-Fulfillment-Prozesse handhaben zu können.

*Sobald die neue API-Version Pflicht wird, akzeptiert Shopify nur noch eine Tracking-Nummer pro Bestellung.*

Um trotzdem mehr als eine Tracking-Nummer zu senden, kannst du die Bestellung in Lieferaufträge aufteilen. Wenn du keine Lieferaufträge erstellst oder wenn eine Bestellung nur einen Artikel enthält, der in mehreren Paketen versandt wird (z.B. Möbel), wird plentymarkets nun alle Tracking-Nummern derselben Bestellung verketten und durch Kommas trennen (z.B. 123456789,123456778).

In Shopify werden diese verketteten Tracking-Nummern als eine einzige Tracking-Nummer behandelt. Wenn Kund:innen also auf den Link zur Sendungsverfolgung klicken, um Informationen über ihre Pakete zu erhalten, wird nur die erste Tracking-Nummer auf der Website des Versandunternehmens aufgerufen. Kund:innen müssen die anderen Nummern manuell kopieren und einfügen. Außerdem müssen sie selbst darauf kommen, dass überhaupt mehr als eine Kontrollnummer angegeben ist.

*Wie geht es weiter?*

* Wenn du die neuen Berechtigungen in der Shopify-App schon erteilt hast, wird die neue API-Version verwendet, sobald die Änderung deine plentymarkets Version erreicht.
* Wenn du die neuen Berechtigungen noch nicht erteilt hast, link:link:https://forum.plentymarkets.com/t/shopify-app-neue-rechte-erforderlich-shopify-app-new-permissions-required/707136[tue dies bitte so bald wie möglich^].

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Amazon

* Beim Auftragsimport werden Aufträge, welche über Amazon Click & Collect generiert wurden, ab sofort ignoriert.
Dies ist notwendig um Konflikte mit Partner-Lösungen für Amazon Click & Collect zu vermeiden, da diese in der Regel selbst die Aufträge ins plentymarkets einspielen.

[discrete]
=== Artikel (Neue UI)

* Die Spaltenreihenfolge für verknüpfte Eigenschaften wurde geändert in "Name - Wert - Eigenschaftsgrupp". Im Fall von Bestelleigenschaften zu "Name - Aufpreis - Eigenschaftsgruppe". Dadurch wird unnötiges horizontales Scrollen vermieden.
* Wir haben die Standardansicht für die Variantenübersichten vereinfacht. Wer andere Spalten und Spaltenreihenfolgen braucht und diese nicht bereits eingerichtet hat, kann dies jederzeit über den Button für die Spaltenkonfiguration einrichten.
* Wir haben das Standard Layout der EIgenschaftenunterseite angepasst. Insbesondere haben wir 33/33/33 Raumaufteilungen zugunsten von 50/50 Raumaufteilungen geändert.

[discrete]
=== Aufträge

* Die alten UIs unter *Einrichtung » Aufträge » Auftragstypen » Reparatur* und *Einrichtung » Aufträge » Auftragstypen » Retoure* wurden modernisiert.
* In der neuen Auftrags-UI werden nun bestimmte Funktionen nur dargestellt, wenn die benötigten Rechte dafür vorhanden sind. Vorher kam es beim Ausführen der Funktion zu einem Fehler, wenn bestimmte Benutzerrechte fehlten. Dies ist nun nicht mehr der Fall. Weitere Informationen findest du auf der Handbuchseite xref:auftraege:preparatory-settings.adoc#benutzerrechte-vergeben[Vorbereitende Einstellungen vornehmen].

[discrete]
=== POS

* Die Menüeinträge *Kassenjournal*, *IDEA-Export*, *DEP-Export*, *TSE-Export* und *DSFinV-K-Export* sind jetzt unter dem neuen Menüpunkt *Daten » POS » Protokolle* zu finden.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Amazon

* Der FBA Retourenimport arbeitet nur mit Berichten aus einem bestimmten Zeitintervall.
Normalerweise sollte nach offenen Berichten der letzten 48 Stunden gesucht werden.
Durch einen Fehler wurden stattdessen nur offene Berichte aus einem Sekundenintervall berücksichtigt, was im Normalfall dann kein Bericht war. Dies wurde nun korrigiert.
+
Da das Problem auf Basis von Berichten von Händler:innen seit ca. 11.01.2023 zu bestehen scheint, wurde das abgefragte Intervall auf 30 Tage erhöht, während pro Prozesslauf aber maximal 10 Berichte ausgewertet werden. Dies sollte dafür sorgen, dass die ausstehenden Berichte alle noch nachträglich einlaufen, ohne Gefahr zu laufen, dass der Prozess aufgrund zu langer Laufzeit abbricht.

[discrete]
=== Artikel (Neue UI)

* Unter gewissen Bedingungen war es möglich, dass das erneute Öffnen einer Hauptvariante nach dem Speichern diese in einem veraltetet Zustand dargestellt hat. Dieses Fehlverhalten haben wir behoben.

[discrete]
=== Aufträge

* In Aufträgen wurde bei Paketbestandteilen keine Auftragspositionseigenschaft für das Lager angelegt. Das Lager konnte somit z.B. nicht über den Katalog exportiert werden. Dies wurde behoben.
* Beim Verknüpfen einer Zahlung mit einem Auftrag wurde der `updatedAt`-Zeitstempel des Auftrags nicht jedesmal aktualisiert. Dies wurde behoben.
* In der neuen Auftrags-UI kam es beim Wechsel zwischen verschieden Aufträgen gelegentlich zu dem Fehler, dass mehrere externe Rechnungen hochgeladen werden konnten. Dieser Fehler wurde behoben.
* In der Übersichtstabelle der neuen Auftrags-UI wurde bei nicht gesperrten Aufträgen ein Entsperrt-Symbol angezeigt. Für eine bessere Übersichtlichkeit wurde dieses Symbol entfernt. Nun wird nur noch bei gesperrten Aufträgen ein Gesperrt-Symbol angezeigt.
* In der Auftragsanlage konnte es vorkommen, dass einige Eigner nicht angezeigt wurden. Dies wurde behoben.
* In der neuen Auftrags-UI (Testphase) wurden die Versandkosten beim Öffnen der Auftragsdetails auf die nächste ganze Zahl gerundet. Dies wurde behoben.

[discrete]
=== CRM

* Wenn man im Menü *CRM » Schnellsuche* nach Gastbestellungen gesucht hat, ohne einen Filter zu setzen, wurden keine Ergebnisse angezeigt. Ebenso wurden keine Ergebnisse angezeigt, wenn man nach dem vollständigen Namen (z.B. Max Mustermann) im Filter *Name* gesucht hat. Die Suche nach nur dem Vornamen oder nur dem Nachnamen hingegen hat die korrekten Ergebnisse angezeigt. Dieses Verhalten wurde behoben.

[discrete]
=== Fulfillment

* Im Versand-Center 2.0 konnte es bei einigen Aktionen wie dem Registrieren von Sendungen oder dem Erstellen von Polling Dateien dazu kommen das Daten doppelt übermittelt wurden und somit einzelne Aktionen mehrfach für einen Auftrag ausgeführt wurden. Dies wurde behoben.
* Im Filter *Zahlungsart* des neuen Versand-Centers wurden nur die im Backend aktiven Zahlungsarten angezeigt. Dadurch kam es vor, dass Zahlungsarten bei einer Suche fehlten. Dies wurde behoben: Nun werden alle im Backend suchbaren Zahlungsarten im Filter angezeigt.

[discrete]
=== Kataloge

* Ist im Katalog eine Währung beim Verkaufspreis eingestellt, wird er nun erst korrekt umgerechnet, wenn am Preis auch die Live-Umrechnung aktiv ist.

[discrete]
=== Payment

* Es war Nutzern ohne Admin-Rechte nicht möglich, Aufträgen Zahlungen zuzuordnen, da die Aktionen im entsprechenden Fenster für sie nicht sichtbar waren. Dieses Problem wurde nun behoben.

[discrete]
=== Plugins

* Bisher konnte bei Plugin-Sets nicht unterschieden werden ob dieses über Git oder Marketplace bereitgestellt wird. Dieser Fehler wurde nun behoben. Es lässt sich nun über das Git- und Marketplace-Symbol hinter dem Namen des Plugins erkennen.

--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Aufträge

* In der neuen Auftrags-UI (Testphase) wurde eine neue Spalte für die Firma als optionale Spalte hinzugefügt. Ist ein Kontakt für den Auftrag verfügbar, wird die Firma vom Kontakt übernommen. Handelt es sich um eine Gastbestellung, wird die Firma von der Rechnungsadresse übernommen.
* In der neuen Auftrags-UI (Testphase) wurde die Spalte *Externe Artikel-ID* bei den Auftragspositionen um den Marktplatz-Link erweitert. Dieser wird bei Aufträgen von eBay und Amazon dargestellt.

[discrete]
=== CRM

* Einige Verbesserungen wurden im Messenger veröffentlicht:
** Der Ordner *Meine Ordner* wird jetzt auf der selben Ebene wie *Posteingang* und *Papierkorb* angezeigt.
** *In Ordner verschieben* wurde umbenannt in *Ordner verwalten*.
** Ein neues Icon wurde für *Aus allen Ordnern entfernen* hinzugefügt.
** Wenn eine Konversation in mehreren Ordnern gespeichert wurde, werden die Ordner in der Übersicht nun in einer Zeile kommasepariert angezeigt.

[discrete]
=== Fulfillment

* Da die Übersicht der neuen Paketinhaltsliste mehr Spalten enthält, wurden weitere Suchfilter hinzugefügt. Außer nach Auftrags-ID, Packzustand und Auftragsdatum kannst du nun auch nach Auftragstyp und Auftragsstatus suchen.

[discrete]
=== KUPONA

Ab sofort kannst du Artikeldaten mit einem Katalog an Kupona exportieren. Das Marktplatz-Format für Kupona findest du jetzt im Menü *Daten » Kataloge*.

Bisher war der Export von Artikeldaten an Kupona nur über den Elastischen Export möglich. Beim Wechsel auf den Artikeldatenexport mit Katalogen solltest du deshalb Folgendes beachten:

* Merkmale und Freitextfelder können für den Katalogexport nicht mehr verwendet werden. Prüfe deshalb, welche Merkmale du aktuell für Kupona verwendest. Erstelle Eigenschaften für alle Merkmale, die du weiterhin benötigst.
* Beim Wechsel solltest du deinen alten Elastischen Export exakt in dem neuen Katalog nachbauen, damit der Artikelexport weiterhin funktioniert. Ordne also alle Datenfelder so zu, wie sie auch im Elastischen Export an den Marktplatz übertragen wurden. Wenn du bestimmte Datenfelder anders als bisher zuordnest, werden möglicherweise beim Export neue Artikel erstellt.
* Wie du einen Katalog für Kupona einrichtest, erfährst du auf der Handbuchseite xref:maerkte:kupona.adoc#catalogue-export[KUPONA].

[NOTE]
.Hinweis
======
Der Elastische Export und die Exportformate werden nicht mehr weiterentwickelt. Wir empfehlen dir deshalb, schon jetzt Kataloge zu erstellen.
======

[discrete]
=== Payment

* Statt wie bisher nur Ziffern sind bei der Zuweisung einer Rechnungsnummer nun alle Zeichen erlaubt. Außerdem erhältst du bei der Suchanfrage jetzt detailliertere Fehlermeldungen, wenn die eingegebene Rechnungsnummer mehrere Ergebnisse hervorbringt (bis zu fünf übereinstimmende Nummern werden angezeigt).

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== UI

* Die Anzeige der Reihenfolge der Tabellenspalten verhält sich nun anders. Es werden nun zuerst die ausgewählten Spalten in der ausgewählten Reihenfolge angezeigt, gefolgt von den nicht ausgewählten Spalten.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Aufträge

* Beim Hinzufügen von Varianten zum Warenkorb wird versucht, den Artikeltext in der Sprache des Kontakts zu nutzen, wenn dieser am Artikel hinterlegt ist. Sollte kein Text in der Sprache des Kontakts existieren, dient hier die aktuelle Logik über die User- / Systemsprache als Fallback.
* In der Detailansicht der neuen Auftrags-UI wurde beim Aktualisieren der Umsatzsteuernummer der Adressen nicht immer die zugehörige Auftragseigenschaft aktualisiert. Das konnte dazu führen, dass die Umsatzsteuernummer auf Dokumenten von Kindaufträgen nicht korrekt war. Dies wurde behoben.
* In der neuen Auftrags-UI (Testphase) wurden die Versandkosten in der Detailansicht eines Auftrags beim Bearbeiten teilweise nicht korrekt gespeichert.

[discrete]
=== CRM

* Wenn man eine neue Nachricht im Messenger schreiben wollte, wurde die gelbe Warnmeldung *Der Kontakt hat eine andere Sprache, als die ausgewählte Vorlage.* angezeigt, obwohl noch gar kein Kontakt gewählt war. Dieses Verhalten wurde behoben.

[discrete]
=== Spezialexport

* Bei den Spezialexporten wurden die Namen der Monate immer in Englisch angezeigt. Dies wurde behoben.

[discrete]
=== UI

* Bisher konntest Du beim Einstellen der Reihenfolge von Tabellenspalten nicht die Drag and Drop Funktion nutzen, wenn Du gleichzeitig scrollen musstest. Dieser Fehler wurde behoben. Es ist jetzt möglich, die Drag and Drop Funktion beim Scrollen zu nutzen.

'''

[discrete]
== Gelöscht

Folgende Funktionalität wurde in den letzten 7 Tagen auf *{version}* entfernt.

[discrete]
=== Rechte

* Die Eignerrechte für Kalendar und Artikel unter *Einrichtung » Einstellungen » Benutzer » Konten » [Name des Kontos] » Eigner* werden entfernt, weil sie nicht in Gebrauch sind.

--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|link:https://marketplace.plentymarkets.com/addressdoctor_6106[Adressprüfung und Adresskorrektur mit AddressDoctor^]
|1.2.36
|-

|link:https://marketplace.plentymarkets.com/uniservaddresscleansing_6869[Adressprüfung und Adresskorrektur mit Uniserv^]
|2.0.5
|-

|link:https://marketplace.plentymarkets.com/edon_6618[FairGeben^]
|1.5.3
|-

|link:https://marketplace.plentymarkets.com/limango_7023[limango^]
|1.4.26
|-

|link:https://marketplace.plentymarkets.com/paypal_4690[PayPal Checkout^]
|6.2.0
|-

|link:https://marketplace.plentymarkets.com/plentyshopltsmodern_55193[plentyShop LTS Modern^]
|1.0.6
|-

|link:https://marketplace.plentymarkets.com/saturdaydelivery_55321[Termin-/Samstagszustellung buchen^]
|1.0.1
|-

|link:https://marketplace.plentymarkets.com/trackingmanager_54743[TrackingManager^]
|1.3.0
|-

|link:https://marketplace.plentymarkets.com/wayfair_6273[Wayfair^]
|1.2.10
|-

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

Warehouse-App::
+
--

[discrete]
=== Behoben

Folgende Probleme wurden in Version 1.0.4 der *plentymarkets Warehouse App* behoben.

* Das Verwenden von Leerzeichen vor und hinter dem realen Namen in Benutzerkonten konnte in plentyWarehouse dazu führen, dass das Benutzerkonto nicht mit der App verwendet werden konnte. Dieses Verhalten wurde behoben.
* n der Rollenden Kommissionierung war es bei der Artikelerfassung möglich zu scannen, während die Umbuchung bereits lief. Dieses Verhalten wurde behoben.

--

====
