= Changelog 31. Mai 2023
:author: kevin-stederoth
:sectnums!:
:page-index: false
:startWeekDate: 25. Mai 2023
:endWeekDate: 31. Mai 2023

// Ab diesem Eintrag weitermachen: https://forum.plentymarkets.com/t/neues-feature-gefuehrte-touren-new-feature-guided-tours/723210

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Aufträge

* In der neuen Auftrags-UI sind die Tabellenüberschriften und die Suchkomponente jetzt beim Scrollen durch die Auftragsliste fixiert.
* In der neuen Auftrags-UI werden die Preise mit zwei Dezimalstellen angezeigt, und der Tooltip wird bei Bedarf mit vier Dezimalstellen angezeigt.
* Der Buchstabe des Mehrwertsteuersatzes wird jetzt immer mit angezeigt bei den Auftragspositionen.
* In der Auftragsübersicht wurde die Möglichkeit geschaffen, über die MyView-Einstellungen die vorgeschlagenen Filter in der Autovervollständigung selbst zu konfigurieren.

[discrete]
=== CRM

* In den Kontaktoptionen im Menü *CRM » Kontakte* steht dir unter Zusatz der Eintrag *Follow-up-Datum* zur Verfügung. Hier kannst du ein Datum und eine Uhrzeit zur Wiedervorlage speichern. Mit einem Klick auf *Zum Kalender hinzufügen* öffnet sich dein Google Kalender, und du kannst ein Meeting an diesem Follow-up-Datum als Erinnerung in deinem Google-Kalender erstellen.
** In den Filtern wurden die Felder *Follow-up-Datum von* und *Follow-up-Datum bis* hinzugefügt.
** Außerdem kannst du über die Funktion *Spalten konfigurieren* oben rechts das *Follow-up-Datum* aus den Kontaktoptionen in der Übersicht anzeigen lassen und die Übersicht auf- oder absteigend anhand des Follow-up-Datums sortieren.
* Im *Aufträge*-Portlet des Kontaktdatensatzes im Menü *CRM » Kontakte* wurde ein Filter hinzugefügt, mit dem du nach einem oder mehreren Auftragstypen suchen kannst.

[discrete]
=== Kontoverwaltung

* Ab heute kannst du Rechte an Rollen vergeben, die Nutzer:innen MyView-Ansichten erstellen, bearbeiten und löschen lassen. Diese Rechte sind mit dem *Betrachten*-Recht der jeweiligen Benutzeroberfläche der MyView-Ansicht verbunden. Diese neuen Rechte heißen *Ansichten* und du findest sie im einfachen Modus ganz oben.

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Amazon

* Wir haben den Amazon-MFN-Retourenprozess überarbeitet: Ab sofort wird nicht mehr auf die alten Einstellungen im Menü *Einrichtung » Märkte » Amazon » Einstellungen* zurückgegriffen. Stattdessen werden die neuen Kontoeinstellungen im Menü *Einrichtung » Märkte » Amazon » Neue Einstellungen* genutzt.
+
[NOTE]
.To-Do
======
Der Retourenprozess funktioniert genauso wie vorher. Auch an den Einstellungen im plentymarkets Backend hat sich nichts geändert.
======

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Amazon

* Es konnte dazu kommen, dass bei den Artikeldatenexporten für andere Plattformen außer DE die Artikeltexte und Eigenschaften in Sprache Deutsch exportiert wurden statt in der jeweiligen Sprache der Plattform. Dies ist nun behoben.
* Es konnte dazu kommen, dass bei FBA Aufträgen von US Konten die bezahlten Beträge zu niedrig waren. Dazu wurde ein Fix bereitgestellt.

[discrete]
=== CRM

* Beim Versuch, eine Newsletter-Double-Opt-In-Mail über das Formular im Webshop oder die Schnellsuche zu versenden, wurde eine Fehlermeldung im Log angezeigt und die E-Mail wurde nicht versendet. Dieses Verhalten wurde behoben.

[discrete]
=== Prozesse

* Beim Wechsel von Tabs in den Prozessen konnte es passieren, dass der Inhalt der Prozesse nicht angezeigt wurde. Dieses Verhalten wurde behoben.

--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Aufträge

* Ab sofort können in der Auftragsübersicht Notizen zu Aufträgen erstellt werden. Außerdem werden bereits vorhandene Notizen zu einem Auftrag angezeigt.
* In der Detailansicht der neuen Auftrags UI ist es jetzt möglich, ein Abonnement aus einem Angebot zu erstellen.
* In der neuen Auftrags-UI enthält das Zahlungs-Widget in der Auftrags-Detailansicht jetzt eine neue Schaltfläche zum Zurücksetzen der Zahlungen für einen Auftrag.
* In der neuen Auftrags-UI wurde beim Bearbeiten des Versandpreises in der Auftrags-Detailansicht und Drücken der Eingabetaste eine Bestätigungsmeldung für die Änderung des Auftrags angezeigt. Dies wurde behoben.

[discrete]
=== CRM

* Ab sofort kannst du über die MyView im Kontaktdatensatz Einstellungen zum Adress-Layout in der primären Adresse vornehmen. Über das Stift-Symbol gelangst du direkt in das Menü *Einrichtung » CRM » Adress-Layout*.
+
Wenn du die Schaltfläche aktivierst, kannst du zwischen den Optionen *Layout basierend auf dem Adressland verwenden* und *Immer das selbe Adress-Layout verwenden* wählen.
+
Wenn du die Option *Immer das selbe Adress-Layout verwenden* wählst, öffnet sich die Dropdown-Liste Adress-Layouts und du kannst das von dir im Menü *Einrichtung » CRM » Adress-Layout* erstellte Adress-Layout wählen.

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== CRM

* Wie in diesem link:https://forum.plentymarkets.com/t/ankuendigung-schnellsuche-wird-in-kontakte-integriert-announcement-quick-search-will-be-integrated-in-contact/721970[Beitrag^] angekündigt, wurden die folgenden Funktionen aus der Schnellsuche in das Menü *CRM » Kontakte* umgezogen:
** Alle Daten aus einem Datensatz herunterladen
** Datensatz anonymisieren
** Gast in Kontakt umwandeln

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Aufträge

* Wenn ein Auftrag Lieferaufträge hatte und ein Artikel zu dem Auftrag hinzugefügt wurde, dann hat in manchen Fällen die Lagerermittlung nicht funktioniert. Dies wurde behoben.
* Es konnte zu Fehlern kommen, wenn Auftragspositionen ohne Preis ein Rabatt zugeordnet wurde. Dies wurde behoben.
* Im neuen Auftrag erstellen UI waren die Änderungen des Mehrwertsteuersatzes und des Artikelnamens im zweiten Schritt nicht im letzten Schritt sichtbar. Dies wurde behoben.
* In der neuen Auftrags-UI wurde beim Bearbeiten der Auftragspositionen eine Warnmeldung angezeigt, wenn der Verkaufspreis kleiner als der Einkaufspreis war, aber es wurden keine relevanten Details über die betreffende Variante angezeigt. Dies wurde angepasst und die Warnung enthält nun die Variations-ID und den tatsächlichen Preis.
* In der neuen Auftrag erstellen UI wurden beim Neuladen der Aufträge in der Kompaktansicht die erweiterten Auftragspositionen nicht mit den neuen Daten neu geladen. Dies wurde nun behoben.
* Warenbestand ermitteln ist nun auch für Lieferauftrag und Reparatur verfügbar.
* Wenn eine Aktion an einen Auftrag in der Kompaktansicht durchgeführt wurde (z.B. Statuswechsel), hat sich der Auftrag in der Anzeige nicht aktualisiert. Dies wurde nun behoben.
* Die folgenden Änderungen wurden an der Auftragsdetails vorgenommen:
** Im Addresse-Widget wird nun bei Klick auf die Email-Adresse die Order ID als Betreff übernommen
** Bei dem Auftragstyp Gutschrift, kannst du im Bereich Allgemein eines Auftrags ab sofort das Feld *Zeichen Kunde* über die MyView hinzufügen
** Beim Erstellen eines manuellen Zahlungseingangs in der Auftrags-UI, konnte der Betrag nur mit Punkt angegeben werden. Dies wurde nun gefixt und es ist auch wieder ein Komma möglich.

[discrete]
=== CRM

* Wenn man eine EmailBuilder-Vorlage über die Vorschau in der Auftrags-UI geöffnet hat, wurde statt des Namens die E-Mail-Adresse im Empfängerfeld angezeigt. Dieses Verhalten wurde behoben. Nun wird wieder der Name im Empfängerfeld angezeigt.

[discrete]
=== Dokumente

* Der Platzhalter `[DiscountInvoiceAmountGross]` gab bei netto Aufträgen in den Auftragsdokumenten den skontierten brutto Betrag aus. Dies wurde behoben.

[discrete]
=== MyView

* In MyView-Elementen war das Drag&Drop-Verhalten bisher fehlerhaft. Dieses Verhalten wurde nun angepasst, ab jetzt kannst du in einem MyView-Element die Drag&Drop-Funktion korrekt nutzen und somit die Elemente auch so platzieren wie du willst ohne das es zu Fehlern kommt.

[discrete]
=== plentyBase

* In den Backend-Einstellungen von plentyBase wurde das Access-Token nicht in voller Länge angezeigt. Dieses Verhalten wurde behoben.

'''

[discrete]
== Gelöscht

Folgende Funktionalität wurde in den letzten 7 Tagen von *{version}* entfernt.

[discrete]
=== CRM

* Das Menü *CRM » Schnellsuche* wurde aus dem Backend entfernt.

--

Plugin-Updates::
+
--
In den letzten 7 Tagen wurden keine neuen Plugins auf plentyMarketplace veröffentlicht:

Wenn du dir eine Übersicht aller neuen oder aktualisierten Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

====
