= Changelog 15. Februar 2023
:author: kevin-stederoth
:sectnums!:
:page-index: false
:page-aliases: ROOT:changelog.adoc
:startWeekDate: 9. Februar 2023
:endWeekDate: 15. Februar 2023

// Ab diesem Eintrag weitermachen: LINK EINFÜGEN

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Aufträge

* In der neuen Auftrags-UI (Testphase) wurde eine neue Spalte für die Firma als optionale Spalte hinzugefügt. Ist ein Kontakt für den Auftrag verfügbar, wird die Firma vom Kontakt übernommen. Handelt es sich um eine Gastbestellung, wird die Firma von der Rechnungsadresse übernommen.
* In der neuen Auftrags-UI (Testphase) wurde die Spalte *Externe Artikel-ID* bei den Auftragspositionen um den Marktplatz-Link erweitert. Dieser wird bei Aufträgen von eBay und Amazon dargestellt.

[discrete]
=== CRM

* Einige Verbesserungen wurden im Messenger veröffentlicht:
** Der Ordner *Meine Ordner* wird jetzt auf der selben Ebene wie *Posteingang* und *Papierkorb* angezeigt.
** *In Ordner verschieben* wurde umbenannt in *Ordner verwalten*.
** Ein neues Icon wurde für *Aus allen Ordnern entfernen* hinzugefügt.
** Wenn eine Konversation in mehreren Ordnern gespeichert wurde, werden die Ordner in der Übersicht nun in einer Zeile kommasepariert angezeigt.

[discrete]
=== Fulfillment

* Da die Übersicht der neuen Paketinhaltsliste mehr Spalten enthält, wurden weitere Suchfilter hinzugefügt. Außer nach Auftrags-ID, Packzustand und Auftragsdatum kannst du nun auch nach Auftragstyp und Auftragsstatus suchen.

[discrete]
=== KUPONA

Ab sofort kannst du Artikeldaten mit einem Katalog an Kupona exportieren. Das Marktplatz-Format für Kupona findest du jetzt im Menü *Daten » Kataloge*.

Bisher war der Export von Artikeldaten an Kupona nur über den Elastischen Export möglich. Beim Wechsel auf den Artikeldatenexport mit Katalogen solltest du deshalb Folgendes beachten:

* Merkmale und Freitextfelder können für den Katalogexport nicht mehr verwendet werden. Prüfe deshalb, welche Merkmale du aktuell für Kupona verwendest. Erstelle Eigenschaften für alle Merkmale, die du weiterhin benötigst.
* Beim Wechsel solltest du deinen alten Elastischen Export exakt in dem neuen Katalog nachbauen, damit der Artikelexport weiterhin funktioniert. Ordne also alle Datenfelder so zu, wie sie auch im Elastischen Export an den Marktplatz übertragen wurden. Wenn du bestimmte Datenfelder anders als bisher zuordnest, werden möglicherweise beim Export neue Artikel erstellt.
* Wie du einen Katalog für Kupona einrichtest, erfährst du auf der Handbuchseite xref:maerkte:kupona.adoc#catalogue-export[KUPONA].

[NOTE]
.Hinweis
======
Der Elastische Export und die Exportformate werden nicht mehr weiterentwickelt. Wir empfehlen dir deshalb, schon jetzt Kataloge zu erstellen.
======

[discrete]
=== Payment

* Statt wie bisher nur Ziffern sind bei der Zuweisung einer Rechnungsnummer nun alle Zeichen erlaubt. Außerdem erhältst du bei der Suchanfrage jetzt detailliertere Fehlermeldungen, wenn die eingegebene Rechnungsnummer mehrere Ergebnisse hervorbringt (bis zu fünf übereinstimmende Nummern werden angezeigt).

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== MyView

* Die Anzeige der Reihenfolge der Tabellenspalten verhält sich nun anders. Es werden nun zuerst die ausgewählten Spalten in der ausgewählten Reihenfolge angezeigt, gefolgt von den nicht ausgewählten Spalten.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Aufträge

* Beim Hinzufügen von Varianten zum Warenkorb wird versucht, den Artikeltext in der Sprache des Kontakts zu nutzen, wenn dieser am Artikel hinterlegt ist. Sollte kein Text in der Sprache des Kontakts existieren, dient hier die aktuelle Logik über die User- / Systemsprache als Fallback.
* In der Detailansicht der neuen Auftrags-UI wurde beim Aktualisieren der Umsatzsteuernummer der Adressen nicht immer die zugehörige Auftragseigenschaft aktualisiert. Das konnte dazu führen, dass die Umsatzsteuernummer auf Dokumenten von Kindaufträgen nicht korrekt war. Dies wurde behoben.
* In der neuen Auftrags-UI (Testphase) wurden die Versandkosten in der Detailansicht eines Auftrags beim Bearbeiten teilweise nicht korrekt gespeichert.

[discrete]
=== CRM

* Wenn man eine neue Nachricht im Messenger schreiben wollte, wurde die gelbe Warnmeldung *Der Kontakt hat eine andere Sprache, als die ausgewählte Vorlage.* angezeigt, obwohl noch gar kein Kontakt gewählt war. Dieses Verhalten wurde behoben.

[discrete]
=== MyView

* Bisher konntest Du beim Einstellen der Reihenfolge von Tabellenspalten nicht die Drag and Drop Funktion nutzen, wenn Du gleichzeitig scrollen musstest. Dieser Fehler wurde behoben. Es ist jetzt möglich, die Drag and Drop Funktion beim Scrollen zu nutzen.

[discrete]
=== Spezialexport

* Bei den Spezialexporten wurden die Namen der Monate immer in Englisch angezeigt. Dies wurde behoben.

'''

[discrete]
== Gelöscht

Folgende Funktionalität wurde in den letzten 7 Tagen auf *{version}* entfernt.

[discrete]
=== Rechte

* Die Eignerrechte für Kalendar und Artikel unter *Einrichtung » Einstellungen » Benutzer » Konten » [Name des Kontos] » Eigner* werden entfernt, weil sie nicht in Gebrauch sind.

--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.



--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|
|
|

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

====
