= Changelog 8. März 2023
:author: kevin-stederoth
:sectnums!:
:page-index: false
:page-aliases: ROOT:changelog.adoc
:startWeekDate: 2. März 2023
:endWeekDate: 8. März 2023

// Ab diesem Eintrag weitermachen: LINK EINFÜGEN

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Artikel (Neue UI)

* In der Variantenansicht ist es nun möglich, sowohl die verknüpften Lieferanten als auch die Liste der Lieferanten beim Hinzufügen zu sortieren. Die entsprechenden Einstellungen sind im Editiermodus der Ansicht am Lieferanten-Element zu finden.

[discrete]
=== CRM

* Ab sofort kannst du im Messenger Typen und Status festlegen. Zu den Typen und Status gelangst du im Messenger mit einem Klick auf *Einstellungen » Typen und Status*. Du wirst weitergeleitet in das neue Menü *Einrichtung » CRM » Messenger » Typen und Status*, wo du dann die Einstellungen für die Typen und Status vornehmen kannst.
+
Sobald du Typen und Status definiert hast, kannst du über das Kontextmenü der Konversation Typen und Status zuweisen und den Typ und den Status in der Übersicht anzeigen. Außerdem kannst du nach Typen und Status im Filterbereich suchen.
* Aufgrund der Geoblocking-Verordnung sind für Rechnungsadressen im Kontaktdatensatz automatisch alle EU-Länder freigeschaltet, wenn die Rechnungsadresse auf *Ja* oder *Ja, primär* gesetzt ist und wenn die Lieferadresse auf *Nein* gesetzt ist. Auch im Bereich *Bank* eines Kontaktdatensatzes sind nun automatisch alle EU-Länder in der Länderliste enthalten. Weitere Informationen zum Geoblocking findest du auf der Seite der link:https://www.bundesnetzagentur.de/DE/Fachthemen/Digitalisierung/Internet/Geoblocking/start.html[Bundesnetzagentur^].

[discrete]
=== Shopzilla

Ab sofort kannst du Artikeldaten mit einem Katalog an Shopzilla exportieren. Das Marktplatz-Format für Shopzilla findest du jetzt im Menü *Daten » Kataloge*.

Bisher war der Export von Artikeldaten an Shopzilla nur über den Elastischen Export möglich. Beim Wechsel auf den Artikeldatenexport mit Katalogen solltest du deshalb Folgendes beachten:

* Merkmale und Freitextfelder können für den Katalogexport nicht mehr verwendet werden. Prüfe deshalb, welche Merkmale du aktuell für Shopzilla verwendest. Erstelle Eigenschaften für alle Merkmale, die du weiterhin benötigst.
* Beim Wechsel solltest du deinen alten Elastischen Export exakt in dem neuen Katalog nachbauen, damit der Artikelexport weiterhin funktioniert. Ordne also alle Datenfelder so zu, wie sie auch im Elastischen Export an den Marktplatz übertragen wurden. Wenn du bestimmte Datenfelder anders als bisher zuordnest, werden möglicherweise beim Export neue Artikel erstellt.
* Wie du einen Katalog für Shopzilla einrichtest, erfährst du auf der Handbuchseite xref:maerkte:shopzilla.adoc#catalogue-export[Shopzilla^].

[NOTE]
.Hinweis
======
Der Elastische Export und die Exportformate werden nicht mehr weiterentwickelt. Wir empfehlen dir deshalb, schon jetzt Kataloge zu erstellen.
======

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Rechte

Die Eigner-Rechte ziehen um zu den API-Nutzungsrechten. Die Eigner-Rechte werden in bestimmten Bereichen immer aktiv sein wenn:

[cols=2]
|======
|Aktives Recht |Eigner

|*Aufträge*
|
*Auftrag-Eigner:in*

|
*Aufträge*
_oder_
*Aufträge » Scheduler*
|
*Scheduler-Eigner:in*

|*Blog*
|
*Blog-Eigner:in*

|
*CRM*
_oder_
*CRM » Kontakte*
|
*Kontakt-Eigner:in*

|
*CRM*
_oder_
*CRM » Ticket*
|
*Ticket-Eigner:in*

|
*Warenbestände*
_oder_
*Warenbestände » Wareneingänge*
|
*Wareneingang-Eigner:in*
|======

Auch wenn die Nutzer:in Admin-Rechte besitzt, ist sie in allen diesen Bereichen Eigner:in.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Aufträge

* In der neuen Auftrags-UI (Testphase) wurden die folgenden Dinge in der Übersichtstabelle behoben:
** Die Werte in der Spalte *Lieferland* waren in der Übersichtstabelle nicht sichtbar. Dies wurde behoben.
** Die Werte in der Spalte *Bezahlter Betrag (%)* waren teilweise inkorrekt. Dies wurde behoben.
** In der Spalte *Zahlungsstatus* wurden die Daten nicht richtig angezeigt. Dies wurde behoben.

--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.



--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|
|
|

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

====
