= Changelog 19. April 2023
:author: kevin-stederoth
:sectnums!:
:page-index: false
:page-aliases: ROOT:changelog.adoc
:startWeekDate: 13. April 2023
:endWeekDate: 19. April 2023

// Ab diesem Eintrag weitermachen: LINK EINFÜGEN

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Aktionsmanager

* Für die Aktionen haben wir beim Filter *Auftragstyp* die Einstellung *Aufträge mit Lieferaufträgen ignorieren* eingeführt. Wird diese Einstellung aktiviert, werden keine Aufträge von der Aktion betroffen, die Lieferaufträge haben.

[discrete]
=== Artikel (Neue UI)

* In der neuen Artikel-UI ist es nun möglich per Variantengruppenfunktion Eigenschaften mehreren Varianten gleichzeitig hinzuzufügen. Diese Gruppenfunktion befindet sich in der allgemeinen Variantenübersicht als auch in der Variantenübersicht innerhalb eines Artikels.
+
Ein paar Hinweise zur Funktionsweise: Es werden nur Eigenschaften hinzugefügt, die noch nicht verknüpft sind. Ist die Eigenschaftsvererbung beim Hinzufügen von Eigenschaften aktiv, so wird die Verberbung aufgehoben.

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Aufträge

* Das Feld *Auftragssumme (Brutto)* wurde in der Detailansicht durch das Feld *Rechnungsbetrag* ersetzt.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Aufträge

* Im Bereich *Status & Tags* funktionierte die Tag-Suche bei der Eingabe eines Tag-Namen nicht korrekt. Dies wurde behoben.
* In auftragsbezogenen Tabellen war der Titel von Spalten, die eine Nummer enthalten, nicht rechtsbündig, wenn die Sortierung aktiviert war. Dies wurde behoben.
* Für die Ansicht zum Bearbeiten von Artikeln wurden die folgenden Fehler behoben:
** Im Bereich zum Hinzufügen einer Variante war der Button zum Hinzufügen nicht sichtbar. Dies wurde behoben.
** Für die Auftragstypen *Retoure* und *Gutschrift* waren die Aktionen zum Hinzufügen und Entfernen einer Variante beide sichtbar. Dies wurde behoben.
** In der Artikeltabelle konnte das *Lager* angepasst werden, wenn keine Variante zugewiesen war. Dies wurde behoben.
* In der Kompaktansicht war das Icon im Feld *Versandprofil* nicht korrekt ausgerichtet, wenn die Einstellung *Nur Symbol anzeigen* aktiviert war.
* In der Auftragsübersicht hat der Filter für das eBay-Konto nicht korrekt funktioniert. Dieses verhalten wurde behoben.
* In der Detailansicht der Aufträge kann nun das Kundenzeichen gelöscht werden.

[discrete]
=== CRM

* Im Assistenten *E-Mail-Konten* im Schritt *Infodienst* wurden die Blindkopien nicht an die dort eingegebenen E-Mail-Adressen gesendet, wenn die Vorlage über den EmailBuilder versendet wurde. Dieses Verhalten wurde behoben.
* Die Variable *URL zum Variantenbild* (`orderItem.formattedImageUrl`) hat in der versendeten E-Mail keinen Wert ausgegeben. Dieses Verhalten wurde behoben.
* Wenn man innerhalb eines Prozesses, eine EmailBuilder-Vorlage versenden wollte, erschien eine Fehlermeldung. Die E-Mail wurde nicht versendet. Dieses Verhalten wurde behoben.
* Nach der Migration einer E-Mail-Vorlage, die die alte Variable `$OrderProperties` enthielt, hat die Artikelliste zu viele Werte wie zum Beispiel die ID des Versandprofils ausgegeben, die vorher mit der alten Variable nicht ausgegeben wurden. Der Grund dafür lag in der Variable `orderItem.formattedProperties.all | raw`. Dieses Verhalten wurde behoben.

--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.



--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|
|
|

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

====
