= Changelog 25. Oktober 2023
:author: kevin-stederoth
:sectnums!:
:page-index: false
:page-aliases: ROOT:changelog.adoc
:startWeekDate: 19. Oktober 2023
:endWeekDate: 25. Oktober 2023

// Ab diesem Eintrag weitermachen: https://forum.plentymarkets.com/t/auftrag-ui-overlay-beim-druecken-von-enter-order-ui-overlay-on-enter-fix/741389

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Artikel (Neue UI)

* Es ist jetzt während der Tabellenbearbeitung auch möglich, die Barcodes, Artikelnamen und Preise zu bearbeiten.

[discrete]
=== Aufträge

* Es wurden in der Auftragsübersicht bei dem Feld Lieferland in der Kompaktansicht, die Einstellung *Anzeigeoption* hinzugefügt. Mit den Optionen ob der Name oder ISO-Code des Lieferland angezeigt werden soll.
* Es wurden in die Tabelle für die Auftragspositionen die Spalte *Gewinnspanne (netto) gesamt* hinzugefügt.
* Das Feld *Kundenklasse* wurde in der Übersicht hinzugefügt.

[discrete]
=== Decathlon

* Texte, die HTML-Formatierungen enthalten, können ab sofort zu Decathlon übertragen werden, da sie beim Export umgewandelt werden. Das bedeutet, dass du in deinen Artikel- und Angebotstexten für Decathlon nun auch HTML verwenden kannst.
+
Bisher konnten Texte mit HTML-Formatierung nicht zu Decathlon übertragen werden. Stattdessen musste die Auszeichnungssprache markdown verwendet werden. Ab sofort werden HTML-Formatierungen beim Katalogexport aber in markdown konvertiert, sodass die Beschreibungen korrekt auf Decathlon angezeigt werden.

[discrete]
=== Dokumente

* Analog zur Breite des Barcodes haben wir nun auch die Höhe des Barcodes als Einstellung eingeführt.
* Für alle Auftragsdokumente steht nun die neue Variable *Dokument » Rechnungsnummer* zur Verfügung.

[discrete]
=== MyView

* Vor ein paar Wochen haben wir in den Ansichten das Abstandhalter-Element eingeführt. Bis jetzt ließ sich die Höhe dieses Elements nur rechts über die Einstellungen anpassen. Das wurde nun geändert.
+
Ab sofort kannst du die Höhe des Abstandhalter-Elements auch anpassen, indem du es mit der Maus anklickt und den Mauscursor nach oben oder unten bewegst.

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Aufträge

* Folgende Änderungen wurden an der Artikelsuche in der Auftragserstellung und Auftragpositionsbearbeitung veröffentlicht:
** Das alte Feld *Volltext* wurde umbenannt in *Artikel-ID / Varianten-ID / Variantennummer*
** Es wurde eine neue Feld *Artikeldaten* hinzugefügt. Dieses Feld besitzt einen Toggle, für die Auswahl, welcher Suchindex aus *Einrichtung » Artikel » Suche » Backend » Suchindex*. Ist der Toggle nicht aktive wird der *Standard-Index* genutzt, bei aktivierten Toggle wird der *Erweiterte Index* für die Suche verwendet.
** Änderung des Tag-Filters, von einer Einzelauswahl zu einer Mehrfachauswahl. Desweitern wurde dem Feld ein Toggle hinzugefügt, für die Auswahl ob eine Variante von den ausgewählten Tags eins oder alle besitzen muss.
* In der Auftrag UI wurde an den Positionen die Spalte *Bruttopreis* in *Rechnungsbetrag* und die Spalte *Gesamtbetrag (brutto)* in *Gesamtrechnungsbetrag* umbenannt. Bei Netto-Aufträgen werden dann dort die Netto-Beträge statt der Brutto-Beträge dargestellt.
* Bei Abonnements hat jetzt jede Position ein eigenes Startdatum, Enddatum und Kündigungsdatum. In Kindaufträge werden dann nur die Positionen übernommen, die zu diesem Zeitpunkt aktiv sind. Es kann weiterhin am Auftrag ein End- / Kündigungsdatum gesetzt werden. Dieses wird dann aber nur an die Positionen übernommen, die bisher noch kein solches Datum haben.
+
Weitere Informationen dazu wie die REST-API und Plugins von dieser Änderung betroffen sind, findest du link:https://forum.plentymarkets.com/t/abonnement-startdatum-und-enddatum-per-position-subscription-start-date-and-end-date-per-order-item/740105[im Forum].

[discrete]
=== CRM

Die folgenden Auslöser in den ereignisbasierten Messenger-Automatisierungen im Menü *Einrichtung » CRM » Messenger » Automatisierung* wurden umbenannt:

[cols="2"]
|======
|Alt |Neu

|Neue Konversation
|Neue Konversation vom Benutzer

|Neue Antwort auf Konversation
|Neue Antwort vom Benutzer

|Neue E-Mail vom Kontakt
|Neue Konversation vom Kontakt
|======


[discrete]
=== Dokumente

* Im DocumentBuilder gibt es jetzt eine Suchfunktion für die Einschränkungen.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Amazon

* Dokumente für Amazon VCS konnten nicht mit dem DocumentBuilder generiert werden. Dieser Fehler wurde nun behoben und VCS-Dokumente können jetzt mit dem DocumentBuilder erstellt werden.

[discrete]
=== Artikel (Neue UI)

* Der Löschen Button innerhalb einer Variante ist nun nicht mehr dauerhaft inaktiv.
* Es konnte passieren, dass eine Eigenschaft nach dem Hinzufügen erst nach dem Speichern der Variante im entsprechenden Portlet angezeigt wurde. Das haben wir korrigiert, Eigenschaften werten direkt nach dem Hinzufügen angezeigt.
* Es werden jetzt die korrekten Namen der Markierungen in den Filterchips angezeigt.
* Die Prüfung auf doppelte Barcodes funktioniert nun korrekterweise auch innerhalb einer Variante.

[discrete]
=== Aufträge

* Auftrag UI wurden gelöschte Nachbestellungen weiterhin referenziert. Dies wurde behoben.
* In der neuen Auftrags-UI wurden Kassenbelege im Dokumente-Portlet nicht unter *Alle Dokumente* angezeigt. Dieses Verhalten wurde behoben. Des Weiteren wurde die Option *Archivieren* für Kassenbelege entfernt.
* Selectbox mit Suche angepasst, dass diese nach oben springt, wenn man nach etwas sucht.

[discrete]
=== CRM

* Die Variable *Nachbestellung Lieferdatum* im EmailBuilder hat keinen Wert ausgegeben, obwohl das Datum in der Nachbestellung angegeben war. Dieses Verhalten wurde behoben.
* Die Variable *Versanddienstleister* im EmailBuilder nutzte den Backend-Namen des Versandprofils, wenn kein Name in der richtigen Sprache gefunden werden konnte.
+
Dies wurde so behoben, dass in diesem Fall der Versanddienstleister-Name in der ersten verfügbaren Sprache genutzt wird. Sollte auch kein Name in einer anderen Sprache gefunden werden, wird stattdessen der Backend-Name des Versanddienstleisters genutzt.
* Wenn die SMTP-Zugangsdaten für den E-Mail-Versand als ungültig erkannt wurden, war der Versand gesperrt und konnte nur durch löschen des REDIS-Cache entsperrt werden. Von nun an setzt die erneute Ausführung des E-Mail-Konten-Assistenten (ohne Änderung der Anmeldeinformationen) den Sperrstatus zurück.

[discrete]
=== Dokumente

* Für die Ländernamen in den Filtern und Einstellungen des DocumentBuilders und der Nummernkreise wurde der Standardname genutzt anstelle des Names in der Sprache des Benutzers. Das wurde behoben, der Standardname wird nur genommen, wenn es keine Übersetzung in der Sprache gibt.
* Selbst mit der Einstellung *Rechnungen der Aufträge integrieren* aktiviert, wurden keine Einzelrechnungen in die Sammelrechnung aufgenommen. Dies wurde behoben.
* Wurde am Auftrag ein Zahlungsziel hinterlegt so wurde beim Erstellen eines Dokuments das aktuelle Datum mit dem Zahlungsziel addiert und als Anzeigedatum hinterlegt. Dieses Verhalten wurde behoben.

--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Aktionsmanager

* Der Filter *Versanddatum* im Aktionsmanager wurde um folgende Filteroptionen erweitert:
** *in 6 Tagen*
** *in 7 Tagen*
** *in 8 Tagen*
** *in 9 Tagen*

[discrete]
=== Artikel

Im Artikel-Katalog wurden folgende Felder hinzugefügt:
** `bundle type`: Artikelpaket-Typ
** `estimated Available At`: Zulaufdatum
** `hasCalculatedBundleMovingAveragePrice`: GLD EK Paketautomatik
** `hasCalculatedBundleNetWeight`: Gewicht netto Paketautomatik
** `hasCalculatedBundlePurchasePrice`: EK Paketautomatik
** `hasCalculatedBundleWeight`: Gewicht brutto Paketautomatik
** `is hidden in category list`: unsichtbar in Artikelauflistung
** `is Visible In List If NetStock Is Positive`: Artikelauflistung: automatisch sichtbar
** `is Invisible In List If NetStock Is Not Positive`: Artikelauflistung: automatisch unsichtbar
** `main Warehouse ID`: Hauptlager ID
** `main Warehouse name`: Hauptlager Name
** `may Show Unit Price`: Grundpreisanzeige
** `moving Average Price`: GLD EK
** `packing Unit Type ID`: Packstücke ID
** `packing Unit Type name`: Packstücke Name
** `packing Units quantity`: Packstücke Menge
** `pallet Type ID`: Lademittel ID
** `pallet Type Name`: Lademittel Name
** `price calculation UUID`: Preiskalkulation UUID
** `VAT ID`: Umsatzsteuer-ID
** `VAT`: Umsatzsteuer %

[discrete]
=== Aufträge

* Wir haben für die Gruppenfunktion *Dokumente zusammenfügen* neue Rechte hinzugefügt. Für diesen Fall müssen folgende Rechte gesetzt werden.
** *Aufträge > Bearbeiten* (Standardansicht)
** *Aufträge > Gruppenfunktion (neue Auftrags-UI) > Dokumente zusammenfügen > Lesen* (Erweiterte Ansicht)
* Die Größe der Spalten von Tabellen in der Kindauftrag-Erstellung Ansicht sind nun dynamisch verstellbar.
* Bei der Konfiguration der Auftragsherkünfte wurde ein Filter für die Sichtbarkeit hinzugefügt.
* In der Auftragssuche der Auftrag UI wurde ein Filter für Gastaufträge hinzugefügt.
* Über die Auftragsanlage der Auftrag UI können jetzt auch Vorbestellungen angelegt werden.
* Fünf weitere Felder für benutzerdefinierte Auftragseigenschaften wurden für den Kompaktmodus hinzugefügt. Die Felder können unter *My view > Kompakte Felder* aktiviert werden und die benötigte benutzerdefinierte Eigenschaft kann für jedes benutzerdefinierte Eigenschaftsfeld in den Feldeinstellungen ausgewählt werden.
* In den Einstellungen von My view werden die inaktiven Kompaktfelder jetzt alphabetisch sortiert.

[discrete]
=== CRM

* Ab sofort stehen dir für den Messenger übergeordnete Gruppen zur Verfügung. Dadurch kannst du Typen und Status zum Beispiel für einzelne Marktplätze getrennt voneinander bearbeiten. Mit einem Klick auf die jeweilige Gruppe kannst du zwischen den verschiedenen Gruppen im Messenger hin- und herwechseln.
+
Standardmäßig sind die Gruppen *Alle* und *Allgemein* in deinem System vorhanden. Die Gruppen und die dazugehörigen Typen und Status erstellst du im Menü *Einrichtung » CRM » Messenger » Gruppen, Typen und Status*.
+
Im Assistenten *Messenger-Konfiguration* im Schritt *Einstellungen für den E-Mail-Empfang* wählst du die Gruppen, Typen und Status, die dann neuen Konversationen in diesem Posteingang zugewiesen werden. Du findest den Assistenten im Menü *Einrichtung » CRM » Messenger » Posteingänge*.
* Im Bereich *Newsletter* der EmailBuilder-Variablen wurde die Variable *URL zum Abmelden des Newsletters* hinzugefügt. Wenn du diese Variable in deine Vorlage einfügst, erhalten die Empfänger:innen einen klickbaren Link, über den sie sich von allen abonnierten Newslettern abmelden können.

[discrete]
=== Prozesse

* In den Prozessen wurde eine neue Option für *Nicht pickbare Artikel* hinzugefügt (Artikeltyp 10 z.B. Pfand, Trinkgeld). Diese Option gibt es im *Arbeitsschritt: Auftragsabwicklung* und in der *Aktion: Picklisten-Suche*.
+
Die Option wurde hinzugefügt weil es vorgekommen ist, dass Aufträge mit Trinkgeld nicht von den Prozessen angezeigt wurden.

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Geändert

* In der Auftrag UI wurde das Speichern bei der Erzeugung von Kindaufträgen überarbeitet. Beim Klick auf den Speicher-Button öffnet sich jetzt ein Menü. Dort kann ausgewählt werden, wohin nach dem Speichern weitergeleitet werden soll.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Artikel (Neue UI)

* In der neuen Artikel UI wird der Lagerortvorschlag innerhalb der Lagerverknüpfung einer Variante nun richtig angezeigt.
* Klickt man auf die Variantenübersicht in einem Artikel, werden die zugehörigen Varianten nun direkt angezeigt, ohne erneut die Suche klicken zu müssen.

[discrete]
=== Aufträge

* In der Gruppenfunktion *Dokument erstellen* fehlten einige Dokumenttypen. Wir haben diese nun nachgereicht. Ausserdem wurden auch die fehlenden Rechte für die fehlenden Dokumenttypen bereitgestellt. Fehlende Dokumenttypen:
** Korrekturbeleg
** Mahnung
** Stornobeleg Mahnung
** Reparaturschein
** Proformarechnung
* In der Auftrag UI konnte es bei der Anlage von Kindaufträgen zu dem Fehler `Auftrag NaN existiert nicht` kommen. Dies wurde behoben.
* In der Detailansicht der Auftrag UI wurden in manchen Fällen lange Notizen abgeschnitten. Dies wurde behoben.
* In der neuen Auftrags-UI werden beim Scrollen nach unten zu einem bestimmten Auftrag die Aufträge durch die Ausführung der Gruppenfunktionen neu geladen und das Scrollen zur vorherigen Scrollposition im Kompaktmodus funktioniert nicht. Dies wurde nun behoben.

[discrete]
=== CRM

* Die Benennungen der Namens- und Adressfelder in den Adressen des Kontaktdatensatzes waren nicht einheitlich. Hier haben wir eine Anpassung vorgenommen, sodass die "realen" Namen immer an erster Stelle angezeigt werden und die Datenfeldnamen in Klammern dahinter. Beispiel:
** Alt: *Adresse 2 (Hausnummer)*
** Neu: *Hausnummer (Adresse 2)*
* In der Messenger-Gruppenfunktion gab es bei einigen Tags Probleme mit der Darstellung: Entweder wurden sie nicht korrekt dargestellt oder sie verschwanden, wenn man ein anderes Tag gewählt hat. Außerdem waren in der Tag-Auswahl die bereits gesetzten Tags nicht markiert. Somit war es auch nicht möglich, Tags wieder zu entfernen.
* Die Zeilen in der Übersicht des *Aufträge*-Portlets im Kontaktdatensatz wurden nicht abwechselnd in grau/weiß hervorgehoben. Dieses Verhalten wurde behoben.

--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|link:https://marketplace.plentymarkets.com/mediamarkt_6918[Mediamarkt^]
|1.2.0
|-

|link:https://marketplace.plentymarkets.com/mirakl_6917[Mirakl Connector^]
|1.5.0
|-

|link:https://marketplace.plentymarkets.com/wayfair_6273[Wayfair^]
|1.3.0
|-

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

====
