= Changelog 2. August 2023
:author: kevin-stederoth
:sectnums!:
:page-index: false
:startWeekDate: 27. Juli 2023
:endWeekDate: 2. August 2023

// Ab diesem Eintrag weitermachen: https://forum.plentymarkets.com/t/neue-auftrags-ui-benutzerdefiniertes-auftragsdokument-erstellen-new-order-ui-create-custom-order-document/731395
// Auch diesen Eintrag beachten: https://forum.plentymarkets.com/t/new-order-ui-button-show-stock-in-the-toolbar-neue-auftrags-ui-button-warenbestand-ermitteln-in-der-toolbar/730887

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Aufträge

* In der Detailansicht der neuen Auftrag UI ist jetzt das Feld für die externe Auftrags-ID bei Retouren verfügbar.
* Das Feld *Status* kann nun angeklickt werden, um den Status direkt zu ändern.
* Bestimmte Felder in der Kompaktansicht haben jetzt die Option *Anzeigen in Kopfzeile* um Felder in der Kopfzeile (ähnlich wie in der alten UI) anzuzeigen. Diese Einstellung ist für folgende Felder verfügbar:
** Status
** Lieferland
** Zahlungsmethode
** Währung
** Rechnungsbetrag
** USt.
** Zahlungsstatus
** Mahnstufe
** Versandprofil
** Warenausgangsdatum
* In der neuen Auftrags-UI wurde das virtuelle Scrollen mit automatischer Größe in ein virtuelles Scrollen mit Elementen fester Höhe geändert. Die neue Implementierung verbessert die Performance des Kompaktmodus und behebt das Problem, dass einige Aufträge bei der Suche nicht angezeigt wurden. Außerdem wird das Scrollen in der Ansicht nach dem zurücknavigieren zur Bestellübersicht stabiler und die Weiterleitung zu anderen UIs ist nicht mehr betroffen.

[discrete]
=== CRM

* Wir haben dem Messenger die folgenden Gruppenfunktionen hinzufügt:
** zu einem Ordner Hinzufügen
** aus einem Ordner entfernen
* Die Variable für die Bestellmerkmale wurde für den EmailBuilder hinzugefügt.
Wir haben dem Messenger die folgenden Aktionen für die Ereignisaktion hinzufügt. Du findest diese unter *CRM » Messenger » Einstellungen » Automatisierung*.
** Konversation löschen
** Konversation archivieren
* Im Kontaktdatensatz gibt es ab sofort im Bereich Dokumente die Möglichkeit, Links hinzuzufügen. Klicke dazu auf *Link hinzufügen*. Im nächsten Schritt gibst du dann den Link ein und kannst optional einen Titel eingeben.
* Ab sofort zeigt die Seitennavigation im Kontaktdatensatz automatisch die Reihenfolge der Portlets analog zur Ansicht rechts an. Bisher war die Seitennavigation eine statische Liste, die nicht automatisch angepasst wurde.
+
*_Beispiel:_* Wenn du in der MyView das Portlet *Aufträge* ganz nach oben schiebst, passt sich die Seitennavigation automatisch an und *Aufträge* wird ebenfalls ganz oben in der Seitennavigationsliste angezeigt.

[discrete]
=== Dokumente

* Das Dokumenten-Widget in der Auftrags-UI wurde für den DocumentBuilder optimiert, sodass hier nun der aktuelle Status des Dokumentes angezeigt wird. Somit werden nun auch Dokumente sichtbar/angezeigt, die sich aktuell noch in Bearbeitung befinden oder bei denen es bei der Erstellung zu einem Fehler kam.

[discrete]
=== MyView

Ab sofort hast du in jeder MyView-Benutzeroberfläche die Möglichkeit, eine bestehende MyView-Ansicht zu importieren oder zu exportieren. Die Schaltflächen dafür befinden sich neben der Auswahl der Ansichten.

Du kannst nur Ansichten in eine Benutzeroberfläche importieren, die auch für diese gedacht sind, also zum Beispiel eine Dashboard-Anischt in dein Dashboard importieren. Dieselbe Ansicht lässt sich allerdings nicht in die Benutzeroberfläche von Order oder Item importieren.

Für das Importieren von Ansichten braucht Benutzer:innen-Konto folgendes Recht:
*Ansichten » Erstellen*

[discrete]
=== plentyShop

* Es wurde eine neue Benutzerrecht-Kategorie hinzugefügt: *CMS » PWA » Bereitstellen*.

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Aufträge

* Die Komponente zur Auswahl des Status in den Auftragsdetails wurde angepasst und hat nun den Fokus direkt auf dem ausgewählten Status, d.h. kein unnötiges Scrollen mehr beim Ändern des Status.

[discrete]
=== Fulfillment

* Durch die Aufteilung in verschiedene Module im Hintergrund, wurden nicht notwendige Inhalte in den Bereichen, Versand-Center, Paketinhaltsliste und dem Paket-Widget herausgenommen, womit die Performance und Stabilität verbessert wurde.

[discrete]
=== plentyShop

* Die Benutzerrecht-Kategorie *CMS » Neuer Webshop* wurde umbenannt in *CMS » Webshop*.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Aufträge

* Die neuen Einstellungen für die Felder in der Kompaktansicht wurden in alten Ansichten nicht angezeigt.
* In der neuen Auftrags UI wurde bei Kontakten bisher nicht der Name der Firma angezeigt, wenn kein Name hinterlegt war. Dies wurde behoben.
* Die Tab *Aufträge* kann aufgrund einiger Änderungen in der neuen Angular-Version nicht dupliziert werden. Dies wurde behoben. Aufgrund dieser Korrektur wird ein Klick auf die Hauptnavigation *Aufträge* immer auf die neue Bestelloberfläche umgeleitet, ohne dass die Einstellungen *Neue AuftragsUI verwenden und mit anderen Menüs verknüpfen* berücksichtigt werden. Die alte AuftragsUI ist weiterhin über das MouseOver-Menü für Systeme zugänglich, in denen die alte AuftragsUI verfügbar ist.
* Ab jetzt funktioniert der Bearbeitungs-Button in der Auftrags-Detailansicht wieder, um Rechnungsanschriften zu bearbeiten.
* In der neuen Auftrags-UI und der UI zum Anlegen neuer Aufträge wird der Verkaufspreis zurückgesetzt, wenn ein Artikel in den Warenkorb gelegt wird und die Verkaufspreise geändert werden und der dadurch ausgelöste Ladevorgang abgeschlossen war. Dies wurde behoben.

[discrete]
=== CRM

* Bei der Migration von alten E-Mail-Vorlagen in den EmailBuilder kam es zu einem Fehler, sodass in einigen Fällen Sprachen gefehlt haben. Dieser Fehler wurde nun behoben.
* In der Kontakt-UI wurde die Login-URL im plentyShop-Login Portlet nicht aktualisiert, wenn zwischen verschiedenen Kontakten gewechselt wurde. Dieses Verhalten wurde nun behoben.
* Beim Versand einer EmailBuilder-Vorlage über Ereignisaktionen kam es in manchen Fällen vor, dass die Variable `URL zum Artikel` zum falschen Mandanten verlinkt hat. Dieses Verhalten wurde behoben.
* In einigen Fällen kam es vor, dass nach dem Klick auf das Speichern-Symbol die Änderung im Code-Widget nicht gespeichert wurde. Ab sofort kannst du weder auf Speichern noch auf Vorschau klicken, solange der Code-Widget-Editor geöffnet ist (die Schaltflächen für Speichern und Vorschau sind solange ausgegraut). Zusätzlich wird beim Versuch in eine andere Vorlage zu wechseln eine Hinweismeldung angezeigt, wenn der Editor geöffnet ist.

[discrete]
=== Dokumente

* Im DocumentBuilder konnten Ausgabeeinstellungen aus den Vorlageeinstellungen geöffnet aber nicht gespeichert werden, sondern nur in dem Editor selbst. Dies wurde behoben.
* Im DocumentBuilder hat die Variable *Auftragsposition » Lager* statt dem Lagernamen den Inhalt des Lagerobjektes ausgegeben. Dies wurde behoben.

[discrete]
=== Fulfillment

* Im Bereich Versand-Center wurde folgendes Verhalten behoben:
** Das Exportlabel-Icon wurde nicht immer angezeigt
** Beim Wechsel aus der Detailansicht in die Übersicht wurden die Suchergebnisse verändert
** Icons für den nachträglichen Download von Versandlabel verschwindet nach kurzer Zeit in der Detailansicht
** Die Paketnummer wird nach Stornierung/Zurücksetzen der Sendung nicht gelöscht (noch sichtbar beim Bearbeiten eines Paketes)
* Im Paket-Widget wurden die Einstellungen von *Titel* und *Portlet einklappen* nicht übernommen. Dieses Verhalten wurde behoben.

[discrete]
=== MyView

* Durch einen Fehler in der Zuordnung von MyViews konnte es passieren, dass beim Wechsel zwischen verschiedenen Ansichten (bspw. Wechsel von Order compact UI auf Order detailview) nicht die korrekten MyView-Sets zur Auswahl angezeigt wurden. Dieses Verhalten ist nun gefixt.
* Beim Wechseln von der compactView auf die detailView, und andersherum, in der neuen Order-UI konnte es sein, dass die falsche, mit der Rolle verknüpfte, myView geladen wurde. Dieses Verhalten ist nun behoben.

[discrete]
=== plentyBase

* Wenn man in der plentyWarehouse App keine Wagenkennung eingegeben hat, also das Feld der Wagenkennen leer blieb. Konnte es beim lösen der Wagenkennung an der Pickliste über den Prozess zu einem Fehler kommen. Dieser Fehlern wurde behoben.

[discrete]
=== plentyBI

* Beim Öffnen des Bearbeitungsmodus im Menü *plentysystems Logo (Start) » Dashboard* wurden bereits auf dem Dashboard vorhandene Elemente ohne Inhalt dargestellt. Somit war es nicht möglich, die Einstellungen für diese Elemente zu ändern. Dieses Verhalten wurde behoben.

'''

[discrete]
== Gelöscht

Folgende Funktionalität wurde in den letzten 7 Tagen auf *{version}* gelöscht.

[discrete]
=== Amazon

* Der temporäre Prozess link:https://forum.plentymarkets.com/t/717722[zur Identifizierung unvollständiger FBA-Aufträge], zusammenhängende Berichte und Oberflächen werden jetzt wieder entfernt, da diese nicht mehr benötigt werden.

--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Artikel (Neue UI)

* Die Spaltenbreite in den restlichen Tabellen der neuen Artikel UI ist jetzt konfigurierbar. Für neue User muss sie eventuell einmalig eingestellt werden, wie gewünscht.

[discrete]
=== Aufträge

* Das Versenden von E-Mails steht in der neuen Auftrags-UI jetzt auch als Menüfunktion zur Verfügung.

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Artikel (Neue UI)

* Der CrossSelling-Typ *Konfigurator* wurde ausgeblendet. Er wurde unbeabsichtigt in der neuen Artikel-UI angezeigt.

[discrete]
=== CRM

* Im Messenger wurden folgende Änderungen vorgenommen:
** *Meine Ordner* ist nun immer sichtbar
** Die Schaltfläche *Neuen Ordner hinzufügen* befindet sich nun im Kontext-Menü von *Meine Ordner*
** *Angeheftete Konversationen* ist nun immer sichtbar
** Die Icons für *Meine Ordner*, *Angeheftete Konversationen* und *Konversation lösen* wurden geändert
** Das Laden von angehefteten Konversationen wurde verbessert

[discrete]
=== Dokumente

* Dokumenttypen die für die Erstellung im DocumentBuilder aktiviert sind können nicht mehr über die UI unter *Aufträge » Fulfillment* generiert werden. Für die betroffenen Dokumenttypen wird hier nun ein Hinweis angezeigt und die Aktion zum Erstellen ist nicht mehr vorhanden.
+
Die Erstellung von Dokumenten für eine Liste von Aufträgen ist über eine Gruppenfunktion in der Auftrags-UI weiterhin möglich. Eine Gruppenfunktion um Dokumente zu einem PDF zusammenzuführen wird in naher Zukunft folgen um hier den gleichen Funktionsumfang sicherzustellen.

[discrete]
=== Netto

Der Katalog von Netto wurde um folgende Funktionen und Felder erweitert:

. Separate kanalspezifische Felder für Netto und Marktkauf:
** Preis
** Provision
** Lieferzeit
** Grundpreis: Verkaufspreis
** Grundpreis: Einheit
** Grundpreis: Menge
** Alter Preis
** Kategorien
. Neue Steuerklasse: 0% (Solarprodukte)
. Neue Felder für EAR-Bestimmungen:
** WEEE_Pflicht
** EAR_Kategorie
** EAR_Marke
** WEEE_Nummer
. Asynchroner Bilderupload: Der Upload der Bilder auf den SFTP in einen Microservice ausgelagert. Dadurch schlägt sich der zeitintensive Upload nicht mehr den täglichen Cron-Prozess nieder und findet nachgelagert zur Übertragung der Produktdatei statt.

Der Nutzung des Katalogs steht damit nichts mehr im Wege.

[IMPORTANT]
.To-Do
======
Um den Katalog zu nutzen, muss man mindestens einen Katalog anlegen, mappen, aktivieren und kann dann unter *Einrichtung » Märkte » Netto eStores » Tab: Einstellungen* über die Optionen *Artikelexport aktivieren* und *Bestandsabgleich aktivieren* und den neuen Auswahlwert *Ja (Katalog)* diese separat umstellen.
======

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Aufträge

* Die folgenden Korrekturen wurden zur Tabelle der Auftragspositionen und zur Tabelle des Warenkorbs hinzugefügt:
** Die Eigenschaften der Bestellpositionen wurden in der Artikeltabelle und in der Tabelle des Warenkorbs auf der Grundlage der Speicherreihenfolge sortiert. Dies wurde behoben.
** Die Eigenschaften der Auftragspositionen konnten im dritten Schritt der Benutzeroberfläche zum Anlegen eines neuen Auftrags nicht aufgeklappt werden. Dies wurde behoben.

+
Die Korrekturen sind sowohl für die neue Benutzeroberfläche zum Anlegen von Aufträgen als auch für die neue Benutzeroberfläche für Aufträge verfügbar.
* Beim Zurücksetzen des Warenausgangs über die neue Auftrags UI wurde der Benutzer nicht in den Warenbewegungen der Variante angezeigt. Dies wurde behoben.
* In der neuen Auftrags-UI erlaubt die Datumsauswahl bei der Dokumentenerstellung nicht die Eingabe des richtigen Formats für die Lokalisierung. Dies wurde behoben.
* In der Benutzeroberfläche für das Anlegen neuer Aufträge und in der Benutzeroberfläche für das Bearbeiten von Auftragspositionen wurde bei schnellen Änderungen der Artikelmenge mehrerer Artikel die Menge manchmal durch den im Hintergrund ausgeführten Preview-Aufruf zurückgesetzt. Dies wurde behoben und die bearbeitbaren Felder sind nun deaktiviert, während des Aufrufs der Auftragsvorschau.
* Wenn in der neuen Auftrags-UI versucht wird einen Unterauftrag in einem duplizierten Auftrags-Tab zu erstellen, wurde die Erstellung des Kinderauftrags im ersten Auftrags-Tab durchgeführt und nicht in dem, in dem der Prozess gestartet wurde. Dies wurde behoben.
* Wenn man in der neuen Auftrags-UI vom Dashboard zur Auftragsübersicht navigiert und von der Kompaktansicht zur Listenansicht wechselt, erscheint eine weiße Seite. Dies wurde behoben.
* In der neuen Benutzeroberfläche für Aufträge gingen beim Wechsel zwischen der Kompaktansicht und der Listenansicht die Suchparameter verloren. Dies wurde behoben.
* In der neuen Auftrags-UI bekommen Bundleartikel nicht die richtigen Preise und Mehrwertsteuer, wenn die Einstellung *Bundlespositionen im Bestellprozess durch die Basisartikel ersetzen* aktiviert ist. Dies wurde behoben.
* Es kam zu einem Fehler wenn kein Einkaufspreis gesetzt ist. Dieses Verhalten wurde behoben.
* In der neuen Auftrags-UI können die Bookmarks für einen Datumsfilter mit dem Operator *zwischen* jetzt wieder gespeichert werden.
* Das Zahlungs-Widget wird in der neuen Auftrags-UI jetzt auch für Sammelaufträge in den Auftragsdetails angezeigt.
* Verschiedene Buttons, wie z.B. der Button zum Kopieren von Aufträgen, wurden so angepasst, dass bei mehrfachem Drücken keine doppelten Auftäge erzeugt werden.
* Datumsfilter funktioniert nun wieder nachdem man beispielsweise von einer anderen UI wie dem Dashboard zur Auftragsübersicht weitergeleitet wurde.

[discrete]
=== CRM

* Beim Einrichten des E-Mail-Kontos ist es nun auch erlaubt, im Feld für den Namen des Absenders Sonderzeichen zu verwenden.

--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|link:https://marketplace.plentymarkets.com/b2bshop_6574[B2B Shop^]
|1.7.3
|-

|link:https://marketplace.plentymarkets.com/pluginsolutetracking_55135[billiger.de Tracking Plugin^]
|1.0.5
|-

|link:https://marketplace.plentymarkets.com/blog_6103[Blog^]
|2.1.0
|-

|link:https://marketplace.plentymarkets.com/elasticexportidealode_4723[idealo.de^]
|3.4.8
|-

|link:https://marketplace.plentymarkets.com/limango_7023[limango^]
|1.5.5
|-

|link:https://marketplace.plentymarkets.com/metro_6600[Metro^]
|2.3.5
|-

|link:https://marketplace.plentymarkets.com/mirakl_6917[Mirakl Connector^]
|1.4.2
|-

|link:https://marketplace.plentymarkets.com/mollie_6272[Mollie^]
|2.8.29
|-

|link:https://marketplace.plentymarkets.com/newsfeedwidget_55031[Newsfeed Widget^]
|2.1.0
|-

|link:https://marketplace.plentymarkets.com/paypal_4690[PayPal Checkout^]
|6.3.6
|-

|link:https://marketplace.plentymarkets.com/shopifytoolbox_55341[Shopify Toolbox - Erweiterung der Shopify Schnittstelle^]
|1.0.2
|-

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

Warehouse-App::
+
--

[discrete]
== Neu

Folgende Neuerungen wurden in Version 1.0.21 der *plentymarkets Warehouse App* veröffentlicht.

* Innerhalb der Funktion *Einzelkommissionierung* wird beim Fokus auf ein Suchfeld und anschließendem Scannen der entsprechenden Auftragsinformation der Suchvorgang jetzt automatisch gestartet.

'''

[discrete]
== Geändert

Folgende Änderungen wurden in Version 1.0.21 der *plentymarkets Warehouse App* veröffentlicht.

* Die Formulierung von Fehlermeldungen im Fall von fehlenden Benutzerrechten wurde von *Anzeigen* zu *Lesen* geändert.

'''

[discrete]
=== Behoben

Folgende Probleme wurden in Version 1.0.21 der *plentymarkets Warehouse App* behoben.

* Beim Laden der Auftragspositionen einer Nachbestellung innerhalb der Funktion Wareneingang konnte es zu einem Fehler kommen. Dieser Fehler verhinderte, dass die Auftragspositionen korrekt angezeigt wurden. Dieses Verhalten wurde behoben.

--

====
