= Changelog 10. Mai 2023
:author: kevin-stederoth
:sectnums!:
:page-index: false
:page-aliases: ROOT:changelog.adoc
:startWeekDate: 4. Mai 2023
:endWeekDate: 10. Mai 2023

// Ab diesem Eintrag weitermachen: LINK EINFÜGEN

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Artikel (Neue UI)

* Die Änderungsverläufe von Artikeln, Varianten und speziell Verkaufspreisen stehen nun direkt in der neuen Artikel-UI zur Verfügung. Die Änderungsverläufe für Artikel und Varianten sind links in der Navigationsleiste zu finden. Der Änderungsverlauf von Verkaufspreisen lässt sich zudem direkt einsehen. Hier gibt es zwei Wege:
** Am Verkauspreis-Panel für alle Verkaufspreisänderungen einer Variante
** An einem bestimmten Verkaufspreis für dessen Änderungen
* In der neuen Artikel UI haben wir mehrere Verbesserungen zur Lesbarkeit veröffentlicht. Dies betrifft hauptsächlich Auswahl- und Mehrfachauswahleigenschaften
** Lange Eigenschaftsnamen werden nun in der Breite begrenzt
** im Tooltip der Eigenschaftsnamen sieht man den volständigen Namen inklusive der Beschreibung (wenn vorhanden)
** im Tooltip der Auswahlwerte im Dropdown für Auswahl- und Mehrfachauswahleigenschaften sieht man nun die vollständingen Auswahlwertnamen sowie deren Beschreibung (wenn vorhanden)
** im Tooltip des Drowdowns werden die Namen der gewählten Auswahlwerte samt Beschreibung angezeigt (falls vorhanden)

+
Weitere Informationen findest du auf der Handbuchseite xref:daten:aenderungshistorie.adoc[Änderungshistorie].

[discrete]
=== Aufträge

* Du kannst ab jetzt die Gruppenfunktionen *Löschen* und *Rabatt* beim Bearbeiten von Auftragspositionen verwenden.
* Die neue Auftrags-UI wurde um die folgenden Änderungen ergänzt:
** In der Übersichtstabelle enthält die Komponente Eigenschaften der Auftragsposition auch die Merkmale.
** Im Auftragspositionen-Widget der Auftragsdetails sind die Merkmale der Auftragspositionen nun in der Tabelle der Auftragspositionseigenschaften verfügbar.
** In der Ansicht *Artikel bearbeiten* sind die Merkmale jetzt in der Tabelle mit den Eigenschaften der Auftragsposition verfügbar.
* In der neuen Auftrags-UI ist es jetzt möglich, einen Artikelnamen über mehrere Zeilen zu erstellen.
* In der Übersicht der neuen Auftrags-UI gibt es jetzt eine Gruppenfunktion, um E-Mails zu versenden.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Artikel (Neue UI)

* Es gab einen Fehler mit der Suche in Eigenschafts-Detailseite, der die Detailseite der verknüpften Eigenschaften kaputt machte. Dieser Fehler wurde behoben.

[discrete]
=== Aufträge

* Das Ticket-Widget war nicht sichtbar, wenn es in die MyView-Elemente der Detailsansicht gezogen wurde. Dies wurde behoben.
* Die Infoboxen *Brutto-Gutschein-Rabatt* und *Netto-Gutschein-Rabatt* waren nicht sichtbar, wenn die Auftragsdetails eines Auftrags geöffnet wurden. Dies wurde behoben.
* Der Auftragsstatus kann nicht mehr mit leerem Namen angelegt werden.
* In der Detailansicht der neuen Auftrags-UI wurde in manchen Fällen der Benutzername nicht in der Historie angezeigt. Dies wurde behoben.

'''

[discrete]
== Gelöscht

Folgende Funktionalität wurde in den letzten 7 Tagen auf *{version}* gelöscht.

[discrete]
=== Fulfillment

* Die alten Integrationen folgender Versanddienstleister wurden entfernt:
** *DHL Easylog*: von DHL abgeschaltet
** *GLS Germany*: Plugin vorhanden
** *Parcelforce Worldwide*: keine aktiven Nutzer

--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.



--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|
|
|

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

====
