= Changelog 21. Juni 2023
:author: kevin-stederoth
:sectnums!:
:page-index: false
:page-aliases: ROOT:changelog.adoc
:startWeekDate: 15. Juni 2023
:endWeekDate: 21. Juni 2023

// Ab diesem Eintrag weitermachen: https://forum.plentymarkets.com/t/hinzufuegen-einer-auftragsnotiz-nach-anmeldung-einer-retourensendung-adding-an-order-note-after-registering-a-return-shipment/725837

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Dokumente

* Es ist jetzt möglich die Auftrags-ID einer Nachbestellung unter *Einrichtung » Waren » Bestellwesen » Nachbestellung » Dokumente » Nachbestellung* zu konfigurieren und auf dem Nachbestellung-PDF auszugeben.

[discrete]
=== plentyBI

* Mit der neuen Berechnungsart *Retourenquote Artikel* bei der Kennzahl *Retourenquote* lässt sich nun die Quote auf Artikelebene berechnen. Die Retourenquote für Artikel wird berechnet, indem die Anzahl aller retournierten Artikel zusammengezählt wird. Dieses Ergebnis wird dann durch die Anzahl der insgesamt bestellten Artikel geteilt und mit 100 multipliziert.
+
Diese Kennzahl steht euch als kostenlose Standard-Kennzahl zur Verfügung.
* Ab sofort steht im Menü *Einrichtung » plentyBI » Kennzahlen* die kostenlose neue Standard-Kennzahl *Nettoumsatz* zur Verfügung. Diese Kennzahl erlaubt es euch, den Gesamt-Nettoumsatz auszuwerten. Berechnet wird der Nettoumsatz indem der Umsatz aller Gutschriften vom Umsatz aller Aufträge abgezogen wird.

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Amazon

* Es wurde ein neues Pattern der SKU-Konfiguration für Amazon Accounts in der Benutzeroberfläche implementiert.

[discrete]
=== Artikel (Neue UI)

* Das bisherige Verhalten des Scrollens (per Mausraud) innerhalb eines Eingabefeldes für Zahlen wurde geändert. Bisher erhöhte oder verringerte sich durch das Scrollen der Zahlwert des Eingebefeldes und gleichzeitig scrollte die Seite selbst. Nach dieser Änderung scrollt nur noch die Seite selbst. Dieses neue Verhalten wurde implementiert in folgenden UIs:
** Neue Artikel UI
** Preiskalkulationen
** Barcodes
** Einheiten
** Suchsprachen
** Bildereinstellungen
** Eigenschaften
** Eigenschaftengruppen
** Tags
** Lager

[discrete]
=== CRM

* Du kannst jetzt direkt im Messenger-Portlet Konversationen öffnen, auf diese antworten und neue Nachrichten senden.

[discrete]
=== Fulfillment

* Der Assistent zu eBay Fulfillment wurde von *Einrichtung » Assistenten » Integration » eBay Fulfillment by Orange Connex* in das Menü *Einrichtung » Aufträge » Versand » Fulfillment » eBay Fulfillment by Orange Connex* umgezogen.
* Der Assistent zu Versandeinstellungen wurde aus *Einrichtung » Assistenten » Integration » Versandeinstellungen* entfernt. Eine Tour steht euch unter *Einrichtung » Geführte Touren » plentyShop einrichten » Versandvorbereitung* zur Verfügung.

[discrete]
=== plentyBI

* Folgende Dimensionen wurden in ihren plentyBI Tarifen heruntergestuft:
** Auftragsherkunft Plugin, Erstellungsdatum: S zu XS
** Auftragsherkunft, Erstellungsdatum: S zu XS
** Auftragsherkunft, Fertigstellungsdatum: M zu S
** Auftragsherkunft, Zahlungsdatum: M zu S

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Artikel (Neue UI)

* Wir haben das Verhalten korrigiert, dass man einzelne Eigenschaften in gewissen Konstellationen mehrfach hinzufügen konnte.
* Eine Bestandskorrektur ist nun auch möglich, wenn der Bestand einer Variante in einem Lager 0 ist.
* Der Warenbestands-Korrektur-Dialog im Bestandsbereich eines Artikels lässt sich wieder wie gewohnt öffnen.

[discrete]
=== Aufträge

* In der Übersicht der Auftrags-UI erschien nach dem Zusammenklappen der Seitennavigation ein weißer Stelle neben der Tabelle der Auftragspositionen. Dies wurde behoben.
* In der Auftrags-UI kann der Auftragstitel im Kompaktansicht angepasst werden, indem der Sperrstatus, der Referenzauftrag und die Mahnstufe hinzugefügt werden. Diese Informationen können in den MyView-Einstellungen hinzugefügt werden.
* In der neuen Auftrags-UI waren bei der Filterung nach Herkünften die inaktiven Herkünfte, die nicht verfügbar sein sollten, in der Herkunftsliste sichtbar. Dies wurde behoben.

[discrete]
=== CRM

* Wenn man eine Nachricht über das Ticketsystem versendet hat, wurde die E-Mail-Adresse aus dem *Antwort an*-Feld im Bereich *Versand* (Menü *Einrichtung » CRM » Ticketsystem » E-Mail-Konten*) als Absender verwendet. Dieses Verhalten wurde behoben. Ab sofort wird die E-Mail-Adresse, die im Bereich Konto gespeichert ist, als Absender verwendet.

[discrete]
=== plentyBI

* Bei Kennzahlen welche die Dimension *Lager, Fertigstellungsdatum* verwenden, war es nicht möglich in den Einstellungen eines Dashboard-Elements nach einem bestimmten Dimensionswert zu filtern. Dieser Fehler wurde behoben.

--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Artikel

* Du kannst in der neuen Artikel-UI jetzt nach der verknüpften Preiskalkulation filtern.

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== CRM

* Das Tag *Testphase* wurde am Menüpunkt *CRM » Messenger* entfernt. In diesem Zuge wurde am Menüpunkt *CRM » Ticketsystem* das Tag *Veraltet* hinzugefügt.

[discrete]
=== OTTO Market

* Die Intervalle der Cache-Generierung für OTTO Market Kataloge wurden angepasst. Anstatt jede Stunde werden Caches nur noch zwischen 7:00 und 23:00 im Intervall von 2h und zwischen 0:00 und 1:00 im Intervall von 20min aktualisiert. Die Intervalle sind mögliche Startzeitpunkte, es kann jedoch zu Verzögerungen kommen. Durch diese Änderung werden redundante Generierungen reduziert.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Aufträge

* In der neuen Auftrags-UI wurde beim Entfernen des Datumsfilterchips in der Übersichtstabelle der Filter immer noch mit der Suchanfrage gesendet. Dies wurde behoben.

[discrete]
=== Fulfillment

* Nach der Anmeldung einer Exportsendung mit DHL *Warenpost International* war das Icon für Exportdokumente aktiv, aber es zeigte nach einem Klick nur ein leeres PDF an. Wenn Exportangaben notwendig sind, befinden sich diese jedoch auf dem Versandlabel direkt (CN22).
+
Weitere Exportdokumente wurden in dem Fall von DHL erstellt oder an uns gesendet, daher wird das Exportdokument-Icon nun ausgegraut, wenn für eine Exportlieferung keine Exportdokumente verfügbar sind.

--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|link:https://marketplace.plentymarkets.com/uniservaddresscleansing_6869[Adressprüfung und Adresskorrektur mit Uniserv^]
|2.0.18
|-

|link:https://marketplace.plentymarkets.com/ebics_5098[EBICS^]
|1.2.4
|-

|link:https://marketplace.plentymarkets.com/findologic_6390[Findologic - OnSite-Suche & Product Discovery Platform^]
|5.1.1
|-

|link:https://marketplace.plentymarkets.com/tracking_6452[Google Tag Manager Tracking ENTERPRISE^]
|5.2.1
|-

|link:https://marketplace.plentymarkets.com/feedback_5115[Kunden-Feedback^]
|4.0.9
|-

|link:https://marketplace.plentymarkets.com/limango_7023[limango^]
|1.5.2
|-

|link:https://marketplace.plentymarkets.com/plentyshopltsmodern_55193[plentyShop LTS Modern^]
|1.0.9
|-

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

====
