= Changelog 8. Februar 2023
:author: kevin-stederoth
:sectnums!:
:page-index: false
:page-aliases: ROOT:changelog.adoc
:startWeekDate: 2. Februar 2023
:endWeekDate: 8. Februar 2023

// Ab diesem Eintrag weitermachen: LINK EINFÜGEN

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Artikel (Neue UI)

* In der neuen Artikel-UI kann man jetzt Einstellungen für die Sortierung der Verkaufspreisverknüpfungen in der Tabelle und dem Verkaufspreispicker vornehmen. Mögliche Sortierungen in der Tabelle:
** Verkaufspreis Name
** Verkaufspreis Position
** Verknüpfter Verkaufspreis aktualiert am
** Verkaufspreis ID
** Verkaufspreis Wert

+
Mögliche Sortierung in dem Picker:
** Verkaufspreis Name
** Verkaufspreis Position
** Verkaufspreis Wert
* In der neuen Artikel-UI gibt es nun einen Link zum entsprechenden Auftrag einer Warenbewegung (sofern verfügbar).
* Für neue Systeme gibt es nun vereinfachte Standard Ansichten. Dies betrifft die Artikelansicht, die Variantenansicht, die Artikeltextansicht und die Eigenschaftenansicht. Hintergrund ist die Reduzierung von intial angezeigten Datenfeldern für Neukunden um einen leichteren Einstieg zu gewährleisten.
* In der Variantenansicht ist es nun möglich, sowohl die verknüpften Barcodes als auch die Liste der Barcodes beim Hinzufügen nach Name oder Typ zu sortieren. Die entsprechenden Einstellungen sind im Editiermodus der Ansicht am Barcode-Element zu finden.

[discrete]
=== Aufträge

* In der Übersicht der neuen Auftrags-UI wurde bei der Übersicht des Warenbestands ein Link zu den Nachbestellungen hinzugefügt.
* In der Übersicht der neuen Auftrags-UI wurde bei der Übersicht des Warenbestands die Spalte für den reservierten Bestand hinzugefügt.

[discrete]
=== CRM

* Ab sofort kannst du in der Übersicht des Messengers die Breite der Tabellenspalten nach deinen Wünschen anpassen.
* Ab sofort kannst du eine geöffnete Konversation per Klick wieder schließen, um in die Übersicht des Messenger zurückzukehren.

[discrete]
=== Shopify-App

Ab 1. April 2023 können wir die Fulfillment-Informationen nicht mehr wie bisher an die Shopify-API senden. Shopify hat diese Änderung link:https://shopify.dev/apps/fulfillment/migrate[schon länger angekündigt^].

Deshalb haben wir bereits neue Berechtigungen in der plentymarkets-App eingeführt. Das To-Do dazu findest du in link:https://forum.plentymarkets.com/t/shopify-app-neue-rechte-erforderlich-shopify-app-new-permissions-required/707136[einem älteren Changelog^].

Wir haben plentymarkets nun aktualisiert, um die neuen Shopify-Fulfillment-Prozesse handhaben zu können.

*Sobald die neue API-Version Pflicht wird, akzeptiert Shopify nur noch eine Tracking-Nummer pro Bestellung.*

Um trotzdem mehr als eine Tracking-Nummer zu senden, kannst du die Bestellung in Lieferaufträge aufteilen. Wenn du keine Lieferaufträge erstellst oder wenn eine Bestellung nur einen Artikel enthält, der in mehreren Paketen versandt wird (z.B. Möbel), wird plentymarkets nun alle Tracking-Nummern derselben Bestellung verketten und durch Kommas trennen (z.B. 123456789,123456778).

In Shopify werden diese verketteten Tracking-Nummern als eine einzige Tracking-Nummer behandelt. Wenn Kund:innen also auf den Link zur Sendungsverfolgung klicken, um Informationen über ihre Pakete zu erhalten, wird nur die erste Tracking-Nummer auf der Website des Versandunternehmens aufgerufen. Kund:innen müssen die anderen Nummern manuell kopieren und einfügen. Außerdem müssen sie selbst darauf kommen, dass überhaupt mehr als eine Kontrollnummer angegeben ist.

*Wie geht es weiter?*

* Wenn du die neuen Berechtigungen in der Shopify-App schon erteilt hast, wird die neue API-Version verwendet, sobald die Änderung deine plentymarkets Version erreicht.
* Wenn du die neuen Berechtigungen noch nicht erteilt hast, link:link:https://forum.plentymarkets.com/t/shopify-app-neue-rechte-erforderlich-shopify-app-new-permissions-required/707136[tue dies bitte so bald wie möglich^].

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Artikel (Neue UI)

* Die Spaltenreihenfolge für verknüpfte Eigenschaften wurde geändert in "Name - Wert - Eigenschaftsgrupp". Im Fall von Bestelleigenschaften zu "Name - Aufpreis - Eigenschaftsgruppe". Dadurch wird unnötiges horizontales Scrollen vermieden.
* Wir haben die Standardansicht für die Variantenübersichten vereinfacht. Wer andere Spalten und Spaltenreihenfolgen braucht und diese nicht bereits eingerichtet hat, kann dies jederzeit über den Button für die Spaltenkonfiguration einrichten.
* Wir haben das Standard Layout der EIgenschaftenunterseite angepasst. Insbesondere haben wir 33/33/33 Raumaufteilungen zugunsten von 50/50 Raumaufteilungen geändert.

[discrete]
=== Aufträge

* Die alten UIs unter *Einrichtung » Aufträge » Auftragstypen » Reparatur* und *Einrichtung » Aufträge » Auftragstypen » Retoure* wurden modernisiert.
* In der neuen Auftrags-UI werden nun bestimmte Funktionen nur dargestellt, wenn die benötigten Rechte dafür vorhanden sind. Vorher kam es beim Ausführen der Funktion zu einem Fehler, wenn bestimmte Benutzerrechte fehlten. Dies ist nun nicht mehr der Fall. Weitere Informationen findest du auf der Handbuchseite xref:auftraege:preparatory-settings.adoc#benutzerrechte-vergeben[Vorbereitende Einstellungen vornehmen].

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Artikel (Neue UI)

* Unter gewissen Bedingungen war es möglich, dass das erneute Öffnen einer Hauptvariante nach dem Speichern diese in einem veraltetet Zustand dargestellt hat. Dieses Fehlverhalten haben wir behoben.

[discrete]
=== Aufträge

* In Aufträgen wurde bei Paketbestandteilen keine Auftragspositionseigenschaft für das Lager angelegt. Das Lager konnte somit z.B. nicht über den Katalog exportiert werden. Dies wurde behoben.
* Beim Verknüpfen einer Zahlung mit einem Auftrag wurde der `updatedAt`-Zeitstempel des Auftrags nicht jedesmal aktualisiert. Dies wurde behoben.
* In der neuen Auftrags-UI kam es beim Wechsel zwischen verschieden Aufträgen gelegentlich zu dem Fehler, dass mehrere externe Rechnungen hochgeladen werden konnten. Dieser Fehler wurde behoben.
* In der Übersichtstabelle der neuen Auftrags-UI wurde bei nicht gesperrten Aufträgen ein Entsperrt-Symbol angezeigt. Für eine bessere Übersichtlichkeit wurde dieses Symbol entfernt. Nun wird nur noch bei gesperrten Aufträgen ein Gesperrt-Symbol angezeigt.
* In der Auftragsanlage konnte es vorkommen, dass einige Eigner nicht angezeigt wurden. Dies wurde behoben.
* In der neuen Auftrags-UI (Testphase) wurden die Versandkosten beim Öffnen der Auftragsdetails auf die nächste ganze Zahl gerundet. Dies wurde behoben.

[discrete]
=== Kataloge

* Ist im Katalog eine Währung beim Verkaufspreis eingestellt, wird er nun erst korrekt umgerechnet, wenn am Preis auch die Live-Umrechnung aktiv ist.

--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.



--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|
|
|

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

====
