= Changelog 25. Januar 2023
:author: kevin-stederoth
:sectnums!:
:page-index: false
:page-aliases: ROOT:changelog.adoc
:startWeekDate: 19. Januar 2023
:endWeekDate: 25. Januar 2023

// Ab diesem Eintrag weitermachen: LINK EINFÜGEN

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Aufträge

* In der neuen Auftrags-UI (Testphase) sind die *Variantennummer* und die *Externe Auftrags-ID* nun für die Schnellsuche in den Filtern der Auftragsübersicht aktiviert. Um die Schnellsuche auszulösen, muss etwas in das Eingabefeld des Filters eingetragen werden.

[discrete]
=== CRM

* Ab sofort kannst du im Messenger Prioritäten in Form von Sternen für Konversationen setzen. Außerdem kannst du Konversationen mit einer bestimmten Priorität über den Filter suchen und die Prioritäten in der Übersicht auf- und absteigend sortieren.

[discrete]
=== Kataloge

* Beim Katalog für Aufträge ist jetzt die Auftragseigenschaft für den Handelsvertreter verfügbar (Typ-ID 992).

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Ereignisaktionen

* Wir haben den Namen der Aktion *Status des Hauptauftrags ändern* zu *Status des Elternauftrags ändern* geändert. Von eurer Seite aus sind keine Änderungen notwendig.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Aufträge

* In der neuen Auftragsanlage wurden die Auftragsdetails im ersten Schritt nicht zurückgesetzt, nachdem ein Auftrag erstellt wurde. Dies wurde behoben.
* In der neuen Auftrags-UI (Testphase) wurden nach Ausführung der Aktion *Warenausgang buchen* und anschließendem Wechsel in einen anderen Auftrag in der Seitennavigation die ursprünglichen Auftragsdetails wiederhergestellt, wenn man zum eigentlichen Auftrag zurück navigierte. Dies wurde behoben.
* In der neuen Auftrags-UI (Testphase) und in der neuen Auftragsanlage hatten die Tabellenspalten mit anpassbarer Größe die falsche Standardbreite, was die Daten unlesbar machte. Dies wurde behoben und eine Standardbreite wurde für jede Spalte hinzugefügt.

[discrete]
=== Prozesse

* Dokumente vom Typ *Lieferschein* und *Angebot*, die über REST an den Hauptauftrag geladen werden, können jetzt wieder von den Prozessen abgerufen werden.

'''

[discrete]
== Entfernt

Folgende Funktionalität wurde in den letzten 7 Tagen in *{version}* entfernt.

[discrete]
=== Artikel

* Wir haben Suchfelder entfernt, die keinen Einfluss auf die Suche haben.

--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.



--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|
|
|

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

====
