= Changelog 12. Juli 2023
:author: kevin-stederoth
:sectnums!:
:page-index: false
:page-aliases: ROOT:changelog.adoc
:startWeekDate: 6. Juli 2023
:endWeekDate: 12. Juli 2023

// Ab diesem Eintrag weitermachen: LINK EINFÜGEN

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Aufträge

* In der Auftrags UI werden nach dem Speichern von Änderungen an einem Auftrag diese auch in der Auftragsübersicht dargestellt. Dieses Verhalten wurde auch für die Bearbeitung der Auftragspositionen implementiert. Wenn Änderungen an Auftragspositionen gespeichert werden, werden diese sowohl in der Übersichtstabelle als auch in den Auftragsdetails dargestellt.

[discrete]
=== CRM

* Du kannst nun in EmailBuilder-Vorlagen Variablen für die URL zum Variantenbild in vier verschiedenen Bildgrößen verwenden:
** *Variantenbild URL (Vorschau Größe)*: `orderItem.formattedImageUrlSize.preview`
** *Variantenbild URL (2. Vorschau Größe)*: `orderItem.formattedImageUrlSize.secondPreview`
** *Variantenbild URL (Mittlere Größe)*: `orderItem.formattedImageUrlSize.middle`
** *Variantenbild URL (Volle Größe)*: `orderItem.formattedImageUrl`
+
[NOTE]
.Neue Benennung
======
Die Variable *Variantenbild URL (Volle Größe)* hieß bisher *URL zum Variantenbild*.
======

[discrete]
=== Kataloge

* Du kannst im Artikel-Katalog nun einen Varianten-IDs Filter nutzen.

[discrete]
=== plentyBI

* Ab sofort steht im Menü *Einrichtung » plentyBI » Kennzahlen* die neue kostenlose Kennzahl *Listings (Live)* zur Verfügung. Diese Kennzahl erlaubt es euch, Daten zu im System vorhandenen Listings mithilfe verschiedener Kriterien auszuwerten. Wie auch das Widget auf dem alten Dashboard beschränkt sich die Auswertung auf den Zeitraum des Vortages bis zum aktuellen Tag. Folgende Filtermöglichkeiten stehen zur Verfügung:
** Marktplatz (eBay, Hood, Ricardo)
** Erfolgreich ( ja / nein)
** Prüfung (Erfolgreich / Fehlgeschlagen)

+
*_Hinweis:_* Aufgrund der Konzeption und Besonderheiten dieser Kennzahl solltet ihr die Kennzahl auf dem Dashboard in Form von Tabellen oder Kacheln und nicht als Diagramme einbinden.

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Dokumente

* Durch das Löschen von externen Rechnungen und Gutschriften wurde bisher die Dokumentnummer nicht von dem zugehörigen Auftrag entfernt. Dies wurde angepasst.
+
Zusätzlich wird nun beim Löschen geprüft ob noch eine ältere externe Rechnungen / Gutschriften existierenden und wenn vorhanden wird die Dokumentnummer am Auftrag entsprechend der nun aktuellsten externen Rechnung / Gutschrift an dem Auftrag hinterlegt.

[discrete]
=== Fulfillment

* Wenn in der Übersicht des Versand-Center verschiedene Aufträge ausgewählt werden, wird diese Auswahl nun erhalten, wenn man wieder zurück wechselt, z.B. von der Detailansicht oder Auftrags-UI zurück zur Versand-Center Übersicht.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Artikel (Neue UI)

* Die Gruppenfunktion zum Verknüpfen von Eigenschaften in der neuen Artikel-UI verknüpft nun korrekt alle gewählten Eigenschaften.

[discrete]
=== Aufträge

* Wurden bei der Anlage oder beim Bearbeiten von Aufträgen fehlerhafte Tag Daten übergeben, so wurden die vorhandenen Tags gelöscht. Dies wurde behoben.
* Die Tabelle der Auftragspositionen lädt nun nicht mehr endlos, wenn keine Auftragspositionen vorhanden sind.
* Der *Zahlungsstatus* wird bei Auftragsarten die keine Zahlung besitzen können nicht mehr angezeigt: *Lieferungsauftrag*, *Angebot*, *Retoure*, *Vorbestellung* und *Teil-Lieferung*.
* Die *Alles auswählen*-Logik wurde so angepasst, dass nur noch alle gefilterten Einträge ausgewählt werden und nicht mehr alle Einträge.

[discrete]
=== CRM

* Im E-Mail-Service der Nachbestellungen wurde auch nach dem Wechsel der Sprache immer die Vorlagensprache deutsch angezeigt. Dieser Fehler wurde nun behoben.
* In einigen Systemen kam es in EmailBuilder vor, dass die Variable `orderItem.formattedImageUrl` keinen Wert ausgegeben hat. Dieses Verhalten wurde behoben.

--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.



--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|
|
|

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

====
