= Changelog 26. Juli 2023
:author: kevin-stederoth
:sectnums!:
:page-index: false
:page-aliases: ROOT:changelog.adoc
:startWeekDate: 20. Juli 2023
:endWeekDate: 26. Juli 2023

// Ab diesem Eintrag weitermachen: LINK EINFÜGEN

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Artikel (Neue UI)

* Spaltenbreite anpassbar in folgenden UIs:
** Artikelübersicht
** Variantenübersicht
** Paketbestandteile hinzufügen
** Setbestandteile hinzufügen
** Cross-selling hinzufügen

[discrete]
=== Aufträge

* In der Auftrags-UIs sind die Spalten in der Verlaufstabelle jetzt in der Größe veränderbar.
* Der Transfer-Lagerort wurde als optionales Element in den MyView-Bereich *Allgemein* der Auftragsdetailansicht hinzugefügt.

[discrete]
=== CRM

* Im Firmendatensatz im Menü *CRM » Firma* haben wir das Portlet *Aufträge* hinzugefügt. Das Portlet zeigt die Aufträge von allen Kontakten, die mit dieser Firma verknüpft sind.
+
Die Option zum Hinzufügen eines neuen Auftrags wurde entfernt und es wurden zwei neue Spalten (Kontakt-ID und Kontaktname) in der Übersicht hinzugefügt. Beim Klick auf die Kontakt-ID wird man zum Kontaktdatensatz im Menü *CRM » Kontakte* weitergeleitet.

[discrete]
=== Dokumente

* In den Ausgabeeinstellungen des DocumentBuilder kann nun für jede Vorlage eingestellt werden ob als Währungsformat der ISO-Code (EUR, USD) oder das Symbol ($, €) verwendet werden soll.
* Im DocumentBuilder können auf *Auftragsebene* nun zusätzlich folgende Variablen genutzt werden:
** Externe Quellauftrags-ID (Auftragseigenschaft mit der Typ-ID `62`)
* Im DocumentBuilder können für *Artikelpositionen* nun zusätzlich folgende Variablen genutzt werden:
** Seriennummer
** Model
** Herstellerland
** Artikelvorschautext

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== CRM

* Das Limit für den Mindestbestellwert bei Firmen wurde auf 999999999,99 angehoben.
* Die Assistenten *E-Mail-Konten* und *Messenger-Konfiguration* wurden verschoben:
** Die *E-Mail-Konten* findest du ab sofort unter *Einrichtung » Mandant » Global » E-Mail-Konten*.
** Die *Messenger-Konfiguration* findest du unter *Einrichtung » CRM » Messenger » Posteingänge*.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Artikel (Neue UI)

* Tritt ein Fehler bei der Gruppenfunktion in der neuen Artikel-UI auf, friert das Fenster dazu nicht mehr ein.
* In manchen Tabellen hat das Hinzufügen von Markierungen dafür gesorgt, dass die Tabelle nicht richtig geladen wurden. Dieses Problem haben wir behoben.
* Wenn man nach dem ersten Artikel einen weiteren im gleichen Durchlauf erstellen wollte, hat das trotz Erfolgsmeldung nicht funktioniert. Außerdem gab es keine Fehlermeldung, wenn eine Variante mit gleicher Variantennummer angelegt werden sollte. Beide Fehlverhalten haben wir korrigiert.

[discrete]
=== Aufträge

* In der neuen Auftrags-UI wurden für den Filter *Auftragstyp*, der in den Filtern der Auftragsübersichtstabelle verfügbar ist, die Optionen *Teilweise Lieferung* und *Multi-Lieferung* entfernt.
* Fehler behoben, dass die PDF Vorschau im Safari Browser nicht funktioniert.
* Das Notizen-Widget in den Auftragsdetails wurde angepasst, dass der Text nicht mehr abgeschnitten ist.
* Styling für die Felder *Markierung* und *Mahnstufe* im Kompaktmodus angepasst
* In der Nachbestellung bei den Verkaufspreisen können jetzt 4 Nachkommastellen verwendet werden.
* In der neuen Auftrags-UI war es nicht möglich den Mandant bei einen Sammelauftrag zu ändern. Dies wurde nun behoben.
* In der Rückbuchungsansicht für den Bestand, wurde unter Artikel-ID die ID der Auftragsposition angezeigt. Dies wurde nun behoben.
* Fehler behoben, dass die Versandkosten nicht geändert werden konnten, falls diese nicht als Auftragsposition existiert haben.

[discrete]
=== Prozesse

* In den Prozessen ist es vorgekommen das die Wagenkennung nach dem vollständigen erfassen und Abschliessen der Pickliste über die Aktion *Artikelerfassung* nicht von der Pickliste getrennt wurde. Diese Situation ist meist im Parallelbetrieb der Prozesse und plentyWarehouse App vorgekommen.
Dieser Fehler wurde behoben.

'''

[discrete]
== Gelöscht

Folgende Funktionalität wurde in den letzten 7 Tagen auf *{version}* gelöscht.

[discrete]
=== CRM

* Die Assistenten *Basics* und *Kontaktdatenimport* wurden aus dem Menü *Einrichtung » Assistenten » Grundeinrichtung* entfernt. Die Einstellungen, die im Assistenten *Basics* vorgenommen werden konnten, kannst du in den folgenden Menüs vornehmen:
** *Einrichtung » Einstellungen » Stammdaten*
** *Einrichtung » Einstellungen » Bankdaten*
** *Einrichtung » Kontoverwaltung » Konten*

+
Den Kontaktdatenimport bereitest du im Menü *Daten » Import* im Import-Typ *Kontakte, Firmen und Adressen* vor.

--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.



--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|
|
|

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

====
