= Changelog 17. Mai 2023
:author: kevin-stederoth
:sectnums!:
:page-index: false
:page-aliases: ROOT:changelog.adoc
:startWeekDate: 11. Mai 2023
:endWeekDate: 17. Mai 2023

// Ab diesem Eintrag weitermachen: LINK EINFÜGEN

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Aufträge

* In der neuen Auftrags-UI verwendet die *Kompakte Ansicht* jetzt ein virtuelles Scrollen, um die Leistung zu verbessern, wenn mehr als 25 Artikel pro Seite angezeigt werden.
* In der neuen Auftrags-UI kann die Übersichtssuche auch durch Drücken der Eingabetaste innerhalb eines Filters ausgelöst werden. Das Drücken der Eingabetaste funktioniert nicht bei Datums-, Auswahl- und Mehrfachauswahlfiltern.
* Die Spalte *Versandprofil* wurde in der neuen Auftrags-UI für die Tabelle der Auftragspositionen eingeführt. Die Spalte *Versandprofil* ist optional und kann über die konfigurierbaren Tabellentitel in der Auftragsübersicht und in der Auftragsdetailansicht aktiviert werden.

[discrete]
=== CRM

* Ab sofort kannst du Konversationen im Messenger anheften, um noch einfacher und schneller zwischen diesen Konversationen hin- und herzuwechseln. Sobald du eine Konversation angeheftet hast, wird in der linken Seite der Navigation der Bereich *Angeheftete Konversationen* sichtbar.
+
Du kannst mit einem Klick auf das Kontextmenü in der Zeile *Angeheftete Konversationen* alle Konversationen auf einmal wieder lösen oder mit einem Klick auf *Konversation lösen* in der Zeile der angehefteten Konversation in der Seitennavigation oder in der geöffneten Konversation selbst eine einzelne Konversation wieder lösen.

[discrete]
=== Plugins

* Die Standardseite beim Öffnen eines Plugins aus der Plugin-Übersicht wurde von der Beschreibung auf die Konfiguration angepasst. Die Beschreibung enthält nun nicht mehr nur due Kurzbeschreibung, sondern die ausführliche Beschreibung aus dem Marketplace.

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Aufträge

* In der Kompaktansicht steht der Länder-ISO Code nun vor der Postleitzahl und im Tooltip ist das Land nun ausgeschrieben.
* Die folgenden Änderungen wurden an der Auftragsdetails vorgenommen:
** Im Addresse-Widget wird `Name4` dargestellt, wenn dieser vorhanden ist
** Im Addresse-Widget ist die Mail-Addresse nun klickbar (mailto aktion)
** Beim erstellen einer Nachbestellung aus einen Auftrag sind die Menge vorausgefühlt
** Warenwert Brutto widget im Übersicht-Portlet hinzugefügt

[discrete]
=== CRM

* Das Limit der dynamischen Anhänge im EmailBuilder wurde von 3 auf 4 Anhänge erhöht.

[discrete]
=== Kontoverwaltung

* Den Filtern unter *Kontoverwaltung » Konten* wurde der Filter *Rollen* hinzugefügt. Somit kannst du künftig die Benutzer:innen-Konten nach vergebenen Rollen filtern.

[discrete]
=== Plugins

* Wenn du für ein Plugin den GitHub Branch wechselst, musst du künftig diesen Wechsel in einem Popup-Fenster bestätigen.
* Branches und Tags werden jetzt nicht mehr alphabetisch sortiert, sondern nach Aktualität, vom neuesten Tag/Branch zum ältesten.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Aufträge

* In der Detailansicht der neuen Auftrags-UI hatte das Markieren von Text in den Notizen nicht richtig funktioniert. Dies wurde behoben.
* Die folgenden Änderungen wurden an der Kompaktansicht vorgenommen:
** Die Einstellung in der Pagination *Ergebnisse pro Seite* wird nun gespeichert
** Nach der ausführen einer Gruppenfunktion bleibt man auf der aktuellen Seite, und wechselt nicht zurück zur ersten Seite des Suchergebnisses

[discrete]
=== CRM

* Beim Versuch Rechnungs- oder Lieferadressen für einen bestehenden Kontakt zu importieren, ohne ein Feld im Datensatz zu ändern, wurde zwar eine Meldung angezeigt, dass alle Daten erfolgreich importiert wurden, aber die Adresse wurde weder erstellt noch mit dem Kontakt verknüpft. Dieses Verhalten wurde behoben.

--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.



--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|
|
|

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

====
