= Changelog 25. Oktober 2023
:author: kevin-stederoth
:sectnums!:
:page-index: false
:page-aliases: ROOT:changelog.adoc
:startWeekDate: 19. Oktober 2023
:endWeekDate: 25. Oktober 2023

// Ab diesem Eintrag weitermachen: LINK EINFÜGEN

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Artikel (Neue UI)

* Es ist jetzt während der Tabellenbearbeitung auch möglich, die Barcodes, Artikelnamen und Preise zu bearbeiten.

[discrete]
=== Aufträge

* Es wurden in der Auftragsübersicht bei dem Feld Lieferland in der Kompaktansicht, die Einstellung *Anzeigeoption* hinzugefügt. Mit den Optionen ob der Name oder ISO-Code des Lieferland angezeigt werden soll.
* Es wurden in die Tabelle für die Auftragspositionen die Spalte *Gewinnspanne (netto) gesamt* hinzugefügt.
* Das Feld *Kundenklasse* wurde in der Übersicht hinzugefügt.

[discrete]
=== Decathlon

* Texte, die HTML-Formatierungen enthalten, können ab sofort zu Decathlon übertragen werden, da sie beim Export umgewandelt werden. Das bedeutet, dass du in deinen Artikel- und Angebotstexten für Decathlon nun auch HTML verwenden kannst.
+
Bisher konnten Texte mit HTML-Formatierung nicht zu Decathlon übertragen werden. Stattdessen musste die Auszeichnungssprache markdown verwendet werden. Ab sofort werden HTML-Formatierungen beim Katalogexport aber in markdown konvertiert, sodass die Beschreibungen korrekt auf Decathlon angezeigt werden.

[discrete]
=== Dokumente

* Analog zur Breite des Barcodes haben wir nun auch die Höhe des Barcodes als Einstellung eingeführt.
* Für alle Auftragsdokumente steht nun die neue Variable *Dokument » Rechnungsnummer* zur Verfügung.

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Aufträge

* Folgende Änderungen wurden an der Artikelsuche in der Auftragserstellung und Auftragpositionsbearbeitung veröffentlicht:
** Das alte Feld *Volltext* wurde umbenannt in *Artikel-ID / Varianten-ID / Variantennummer*
** Es wurde eine neue Feld *Artikeldaten* hinzugefügt. Dieses Feld besitzt einen Toggle, für die Auswahl, welcher Suchindex aus *Einrichtung » Artikel » Suche » Backend » Suchindex*. Ist der Toggle nicht aktive wird der *Standard-Index* genutzt, bei aktivierten Toggle wird der *Erweiterte Index* für die Suche verwendet.
** Änderung des Tag-Filters, von einer Einzelauswahl zu einer Mehrfachauswahl. Desweitern wurde dem Feld ein Toggle hinzugefügt, für die Auswahl ob eine Variante von den ausgewählten Tags eins oder alle besitzen muss.
* In der Auftrag UI wurde an den Positionen die Spalte *Bruttopreis* in *Rechnungsbetrag* und die Spalte *Gesamtbetrag (brutto)* in *Gesamtrechnungsbetrag* umbenannt. Bei Netto-Aufträgen werden dann dort die Netto-Beträge statt der Brutto-Beträge dargestellt.
* Bei Abonnements hat jetzt jede Position ein eigenes Startdatum, Enddatum und Kündigungsdatum. In Kindaufträge werden dann nur die Positionen übernommen, die zu diesem Zeitpunkt aktiv sind. Es kann weiterhin am Auftrag ein End- / Kündigungsdatum gesetzt werden. Dieses wird dann aber nur an die Positionen übernommen, die bisher noch kein solches Datum haben.
+
Weitere Informationen dazu wie die REST-API und Plugins von dieser Änderung betroffen sind, findest du link:https://forum.plentymarkets.com/t/abonnement-startdatum-und-enddatum-per-position-subscription-start-date-and-end-date-per-order-item/740105[im Forum].

[discrete]
=== CRM

Die folgenden Auslöser in den ereignisbasierten Messenger-Automatisierungen im Menü *Einrichtung » CRM » Messenger » Automatisierung* wurden umbenannt:

[cols="2"]
|======
|Alt |Neu

|Neue Konversation
|Neue Konversation vom Benutzer

|Neue Antwort auf Konversation
|Neue Antwort vom Benutzer

|Neue E-Mail vom Kontakt
|Neue Konversation vom Kontakt
|======


[discrete]
=== Dokumente

* Im DocumentBuilder gibt es jetzt eine Suchfunktion für die Einschränkungen.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Artikel (Neue UI)

* Der Löschen Button innerhalb einer Variante ist nun nicht mehr dauerhaft inaktiv.
* Es konnte passieren, dass eine Eigenschaft nach dem Hinzufügen erst nach dem Speichern der Variante im entsprechenden Portlet angezeigt wurde. Das haben wir korrigiert, Eigenschaften werten direkt nach dem Hinzufügen angezeigt.
* Es werden jetzt die korrekten Namen der Markierungen in den Filterchips angezeigt.

[discrete]
=== Aufträge

* Auftrag UI wurden gelöschte Nachbestellungen weiterhin referenziert. Dies wurde behoben.
* In der neuen Auftrags-UI wurden Kassenbelege im Dokumente-Portlet nicht unter *Alle Dokumente* angezeigt. Dieses Verhalten wurde behoben. Des Weiteren wurde die Option *Archivieren* für Kassenbelege entfernt.
* Selectbox mit Suche angepasst, dass diese nach oben springt, wenn man nach etwas sucht.

[discrete]
=== CRM

* Die Variable *Nachbestellung Lieferdatum* im EmailBuilder hat keinen Wert ausgegeben, obwohl das Datum in der Nachbestellung angegeben war. Dieses Verhalten wurde behoben.
* Die Variable *Versanddienstleister* im EmailBuilder nutzte den Backend-Namen des Versandprofils, wenn kein Name in der richtigen Sprache gefunden werden konnte.
+
Dies wurde so behoben, dass in diesem Fall der Versanddienstleister-Name in der ersten verfügbaren Sprache genutzt wird. Sollte auch kein Name in einer anderen Sprache gefunden werden, wird stattdessen der Backend-Name des Versanddienstleisters genutzt.

[discrete]
=== Dokumente

* Für die Ländernamen in den Filtern und Einstellungen des DocumentBuilders und der Nummernkreise wurde der Standardname genutzt anstelle des Names in der Sprache des Benutzers. Das wurde behoben, der Standardname wird nur genommen, wenn es keine Übersetzung in der Sprache gibt.
* Selbst mit der Einstellung *Rechnungen der Aufträge integrieren* aktiviert, wurden keine Einzelrechnungen in die Sammelrechnung aufgenommen. Dies wurde behoben.

--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.



--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|
|
|

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

====
