= Changelog 29. März 2023
:author: kevin-stederoth
:sectnums!:
:page-index: false
:page-aliases: ROOT:changelog.adoc
:startWeekDate: 23. März 2023
:endWeekDate: 29. März 2023

// Ab diesem Eintrag weitermachen: LINK EINFÜGEN

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Aktionsmanager

* Im Aktionsmanager gibt es nun die Möglichkeit, nach Tags zu filtern oder diese am Auftrag zu setzen oder zu entfernen.

[discrete]
=== Amazon

Es wurden zwei neue Typen für Auftragsartikeleigenschaften ergänzt:

. Typ-ID 95: URL zu einer externen Datei mit Kundenanpassungen des Artikels
. Typ-ID 96: URL zu einer externen Seite mit Kundenanpassungen des Artikels

In diesen werden an Auftragsartikeln jetzt für Custom-Artikel die Links zu den gewählten Anpassungen der/des Endkund:in hinterlegt.
Über den Link des Typs 95 kann eine Datei heruntergeladen werden, welche die notwendigen Daten in unterschiedlichen Datentypen (XML, JSON, SVG, JPG) bereitstellt.
Über den Link des Typs 96 gelangt man in die Übersicht zu den gewünschten Anpassungen in der Seller Central.

Typ-ID 96 steht nur zur Verfügung, wenn der Auftrag über einen Auftragsbericht importiert wurde. Wenn der Auftrag über API importiert wurde, z.B. über den nächtlichen Backup-Import, steht der Link nicht zur Verfügung, da er auch in der API nicht zur Verfügung steht.

[IMPORTANT]
.Nur via REST-API
======
Diese beiden Eigenschaftstypen sind zum aktuellen Zeitpunkt nicht über die UI erreichbar. Lediglich via REST können diese Informationen abgerufen werden.
======

[discrete]
=== Amazon-MFN

Der Amazon-Bericht für den Amazon-MFN-Auftragsimport (`GET_ORDER_REPORT_DATA_INVOICING`) enthält keine Informationen zum Amazon-Geschenkservice. Deshalb werden ab sofort die folgenden Informationen innerhalb von 5 Minuten über einen separaten Prozess nachträglich importiert:
* Geschenkpapierart
* Geschenkpapierpreis
* Geschenknachricht (optional)

[discrete]
=== Artikel

* Die Werkzeugleisten der Artikel- sowie Variantenansicht sind nun über die MyView konfigurierbar. Die Werkzeugleisten müssen allen individuellen Ansichten nachträglich hinzugefügt werden. Die Toolbars befinden sich immer ganz oben in den Ansicht und können nicht weggescrollt werden.
+
[IMPORTANT]
.To-Do
======
Da die Werkzeugleisten nun Teil der MyView sind, müssen sie allen bereits erstellten individuellen Ansichten nachträglich hinzugefügt werden. Im Standard sind sie bereits enthalten. Deshalb musst du im Zuge des Updates folgende Schritte durchführen, wenn du bereits eigene Ansichten verwendest und diesen die Werkzeugleisten hinzufügen möchtest:

. Öffne die Artikelansicht.
. Wähle deine eigene Ansicht aus.
. Wechsele in den Editiermodus der Ansicht.
. Ziehe die Werkzeugleiste in die Ansicht an erste Stelle.
. Konfiguriere die Werkzeugleiste nach eigenen Vorlieben.
. Speicher die Ansicht mit der konfigurierten Werkzeugleiste.
. Wiederhole die Schritte 2-6 für deine anderen eigenen Ansichten.
. Wiederhole die Schritte 2-6 für deine Ansichten auf Variantenebene.
======
* Die Externe ID kann nun in der Artikel/Varianten-Übersicht als Spalte hinzugefügt werden.
* Die Markierungen in der Übersicht haben jetzt einen Tooltip, der den Namen und die ID der Markierung anzeigt.

[discrete]
=== CRM

* Im Messenger wurden neue Gruppenaktionen im Kontextmenü integriert:
** *Typ und Status der Konversationen ändern*
** *Deadline der Konversationen ändern*
** *Priorität der Konversationen ändern*
** *Konversationen abonnieren*
** *Konversationen nicht mehr abonnieren*

[discrete]
=== Ereignisaktionen

* In den Ereignisaktionen ist es nun möglich, bestehende Tags eines Auftrags zu ignorieren. Um dies zu tun, müssen ein oder mehrere Tags hinzugefügt werden, die dann am Auftrag gesetzt sind. Diese Option ist verfügbar, sobald man mindestens ein Tag hinzufügt.

[discrete]
=== Kataloge

* Beim Katalog für Aufträge wurden die folgenden Möglichkeiten hinzugefügt:
** Tags exportieren
** Nach Tags filtern
** Tags als Exportaktion setzen

[discrete]
=== Prozesse

* In der Auftragsabwicklung sowie in der Subaktion *Tags hinzufügen/entfernen* ist es nun möglich, bestehende Tags eines Auftrags zu ignorieren. Um dies zu tun, müssen ein oder mehrere Tags hinzufügt werden, die dann am Auftrag gesetzt sind. Diese Option ist verfügbar, sobald man mindestens ein Tag hinzufügt.

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== CRM

* Die Suchparameter im Filter *Kontaktdaten* im Menü *CRM » Kontakte* und *CRM » Schnellsuche* wurden angepasst. In diesem Feld kannst du nach den folgenden Werten suchen:
** Vorname und Nachname des Kontakts
** Vorname und Nachname aus der Adresse
** Firmenname aus der Adresse (address.name1)
** Zusätzliche Adressinformationen (address.name4)
** Externe Nummer des Kontakts
** Kundennummer
** Firmenname
** UstId-Nr. der Firma
** eBay-Name des Kontakts

[discrete]
=== Shopify-App

Am 10. Januar haben wir ein erstes To-do zum Thema neue Shopify-Fullfilment-API veröffentlicht. Darin wurdest du aufgefordert, deiner Shopify-App zusätzliche Berechtigungen zu erteilen.

Jetzt wird es ernst! Denn ab sofort nutzt plentymarkets die neue Shopify-Fullfilment-API. Das heißt, dass deine Fulfillment-Abläufe nicht mehr funktionieren, wenn du die Berechtigungen nicht erteilt hast.

Wenn du die Berechtigungen noch nicht erteilt hast, musst du deiner plentymarkets App für Shopify jetzt DRINGEND diese zusätzlichen Berechtigungen erteilen:

* `read_assigned_fulfillment_orders`
* `write_assigned_fulfillment_orders`
* `read_merchant_managed_fulfillment_orders`
* `write_merchant_managed_fulfillment_orders`

*_Hintergrund_*: Diese Änderung der Berechtigungen ist erforderlich, weil Shopify seine Fulfillment-API aktualisiert und wir die Fulfillment-Informationen deshalb nicht mehr wie bisher an die Shopify-API senden können. Shopify hat link:https://shopify.dev/api/release-notes/2022-07#breaking-changes[diese Änderung^] schon länger link:https://shopify.dev/apps/fulfillment/migrate[angekündigt^].

[IMPORTANT]
.To-Do
======
Damit deine Fulfillment-Abläufe weiterhin funktionieren, führe folgende Schritte aus:

. Melde dich in deinem Shopify-Dashboard an. +
Du wirst aufgefordert, die App zu aktualisieren.
. Aktualisiere die App. Klicke dazu auf *App aktualisieren*. +
Damit ist sichergestellt, dass dein Shopify-Shop für die neue Fulfillment-API bereit ist.
======

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== CRM

* Wenn man eine mit dem EmailBuilder erstellte Vorlage über die Vorschau im Auftrag geöffnet hat, wurden weder der Empfängername noch die E-Mail-Adresse angezeigt. Dieses Verhalten wurde behoben.

[discrete]
=== Kataloge

* Das Limit in den Exporteinstellungen wird nun im Auftragsformat berücksichtigt.

[discrete]
=== POS

* Wenn zweimal derselbe Artikel in der Rollenden Kommissionierung vorhanden ist, aber mit unterschiedlichen Bestelleigenschaften, wurden diese nicht einzeln angezeigt. Dieses verhalten wurde nun behoben.

--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.



--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|
|
|

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

====
