= Changelog 8. März 2023
:author: kevin-stederoth
:sectnums!:
:page-index: false
:startWeekDate: 2. März 2023
:endWeekDate: 8. März 2023

// Ab diesem Eintrag weitermachen: https://forum.plentymarkets.com/t/neue-artikel-ui-listings-erstellen-new-item-ui-create-listings/714362

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Artikel (Neue UI)

* In der Variantenansicht ist es nun möglich, sowohl die verknüpften Lieferanten als auch die Liste der Lieferanten beim Hinzufügen zu sortieren. Die entsprechenden Einstellungen sind im Editiermodus der Ansicht am Lieferanten-Element zu finden.
* Ab sofort stehen die Artikel-Sets auch in der neuen Artikel-UI zur Verfügung. Dies betrifft die Anlage neuer als auch die Pflege bestehender Artikel-Sets. Sowohl die Artikelansicht als auch die Variantenansicht eines Artikel Sets sind eigene spezielle Ansichten. Das bedeutet, dass die Bearbeitungsansichten für Artikel-Sets separat von Standardartikeln konfiguriert werden können. Weitere Informationen findest du auf der Handbuchseite xref:artikel:multipack-paket-set.adoc#300[Multipacks, Artikelpakete und Sets].

[discrete]
=== CRM

* Ab sofort kannst du im Messenger Typen und Status festlegen. Zu den Typen und Status gelangst du im Messenger mit einem Klick auf *Einstellungen » Typen und Status*. Du wirst weitergeleitet in das neue Menü *Einrichtung » CRM » Messenger » Typen und Status*, wo du dann die Einstellungen für die Typen und Status vornehmen kannst.
+
Sobald du Typen und Status definiert hast, kannst du über das Kontextmenü der Konversation Typen und Status zuweisen und den Typ und den Status in der Übersicht anzeigen. Außerdem kannst du nach Typen und Status im Filterbereich suchen.
* Aufgrund der Geoblocking-Verordnung sind für Rechnungsadressen im Kontaktdatensatz automatisch alle EU-Länder freigeschaltet, wenn die Rechnungsadresse auf *Ja* oder *Ja, primär* gesetzt ist und wenn die Lieferadresse auf *Nein* gesetzt ist. Auch im Bereich *Bank* eines Kontaktdatensatzes sind nun automatisch alle EU-Länder in der Länderliste enthalten. Weitere Informationen zum Geoblocking findest du auf der Seite der link:https://www.bundesnetzagentur.de/DE/Fachthemen/Digitalisierung/Internet/Geoblocking/start.html[Bundesnetzagentur^].
* Über das Kontextmenü kannst du ab sofort eine Deadline für eine Konversation setzen. Außerdem kannst du im Filterbereich nach Konversationen suchen, die die folgende Deadline haben. Und auch in der Übersicht kannst du die Spalte *Deadline* anzeigen lassen und diese auf- oder absteigend sortieren.
* m EmailBuilder war es nicht möglich, eine Vorlage zu bearbeiten, wenn Header oder Footer in der gewählten Sprache zwar vorhanden, aber leer waren. Dieses Verhalten wurde behoben, indem in der Sprachenliste (Button *Sprache hinzufügen*) in der Vorlage im EmailBuilder mit der Option *Alle* ein Fallback hinzugefügt wurde:
** Wenn eine Vorlage nicht in der erforderten Sprache erstellt wurde oder der Inhalt leer ist, verwende die Sprache *Alle*.
** Wenn der Header nicht in der erforderten Sprache erstellt wurde oder der Inhalt leer ist, verwende die Sprache *Alle*.
** Wenn der Footer nicht in der erforderten Sprache erstellt wurde oder der Inhalt leer ist, verwende die Sprache *Alle*.

[discrete]
=== Shopzilla

Ab sofort kannst du Artikeldaten mit einem Katalog an Shopzilla exportieren. Das Marktplatz-Format für Shopzilla findest du jetzt im Menü *Daten » Kataloge*.

Bisher war der Export von Artikeldaten an Shopzilla nur über den Elastischen Export möglich. Beim Wechsel auf den Artikeldatenexport mit Katalogen solltest du deshalb Folgendes beachten:

* Merkmale und Freitextfelder können für den Katalogexport nicht mehr verwendet werden. Prüfe deshalb, welche Merkmale du aktuell für Shopzilla verwendest. Erstelle Eigenschaften für alle Merkmale, die du weiterhin benötigst.
* Beim Wechsel solltest du deinen alten Elastischen Export exakt in dem neuen Katalog nachbauen, damit der Artikelexport weiterhin funktioniert. Ordne also alle Datenfelder so zu, wie sie auch im Elastischen Export an den Marktplatz übertragen wurden. Wenn du bestimmte Datenfelder anders als bisher zuordnest, werden möglicherweise beim Export neue Artikel erstellt.
* Wie du einen Katalog für Shopzilla einrichtest, erfährst du auf der Handbuchseite xref:maerkte:shopzilla.adoc#catalogue-export[Shopzilla^].

[NOTE]
.Hinweis
======
Der Elastische Export und die Exportformate werden nicht mehr weiterentwickelt. Wir empfehlen dir deshalb, schon jetzt Kataloge zu erstellen.
======

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== plentyShop

* Um die Webshop-Performance zu verbessern, wurden einige kleinere Änderungen an den Prozessen, die Daten für bestimmte E-Mail-Variablen beschaffen, vorgenommen. Diese Änderungen betreffen in erster Linie *Passwort vergessen*-E-Mails.
+
[NOTE]
.Kein To-Do
======
Es besteht kein Handlungsbedarf auf Seite der Händler:innen.
======

[discrete]
=== Rechte

Die Eigner-Rechte ziehen um zu den API-Nutzungsrechten. Die Eigner-Rechte werden in bestimmten Bereichen immer aktiv sein wenn:

[cols=2]
|======
|Aktives Recht |Eigner

|*Aufträge*
|
*Auftrag-Eigner:in*

|
*Aufträge*
_oder_
*Aufträge » Scheduler*
|
*Scheduler-Eigner:in*

|*Blog*
|
*Blog-Eigner:in*

|
*CRM*
_oder_
*CRM » Kontakte*
|
*Kontakt-Eigner:in*

|
*CRM*
_oder_
*CRM » Ticket*
|
*Ticket-Eigner:in*

|
*Warenbestände*
_oder_
*Warenbestände » Wareneingänge*
|
*Wareneingang-Eigner:in*
|======

Auch wenn die Nutzer:in Admin-Rechte besitzt, ist sie in allen diesen Bereichen Eigner:in.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Amazon

* Der FBA-Warenbestandsimport konnte seit kurzem Fehlbestände importieren, da Amazon in den Berichten für die FBA-Warenbestände zusätzlich MFN-Bestände übertragen hat. Das wurde bisher nicht abgefangen und konnte dazu führen, dass diese Bestände auch in den Artikeln gespeichert wurden. Mit dem Fix werden diese MFN-SKUs identifiziert und nicht berücksichtigt.

[discrete]
=== Aufträge

* In der neuen Auftrags-UI (Testphase) wurden die folgenden Dinge in der Übersichtstabelle behoben:
** Die Werte in der Spalte *Lieferland* waren in der Übersichtstabelle nicht sichtbar. Dies wurde behoben.
** Die Werte in der Spalte *Bezahlter Betrag (%)* waren teilweise inkorrekt. Dies wurde behoben.
** In der Spalte *Zahlungsstatus* wurden die Daten nicht richtig angezeigt. Dies wurde behoben.

[discrete]
=== CRM

* Unter anderem wurden in der Schnellsuche weder Gäste noch Firmen über den Filter *Name* gefunden. Dieses Verhalten wurde behoben.

--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Artikel (Neue UI)

* In der Eigenschaftenansicht ist es nun möglich, sowohl die verknüpften Eigenschaften als auch die Liste der Eigenschaften beim Hinzufügen zu sortieren. Die entsprechenden Einstellungen sind im Editiermodus der Ansicht der Eigenschaften zu finden.

[discrete]
=== Aufträge

* Textfarbe und Hintergrundfarbe kann jetzt im Editor der Auftragsnotizen verwendet werden.

[discrete]
=== Fulfillment

* Die Filter-UI im Versand-Center wurde aktualisiert. Die Filter werden nun übersichtlich in zwei Spalten angezeigt. Die häufig benötigten Filter *Auftrags-ID* und *Kontakt-ID* befinden sich oben in der Auflistung.
Das Datums im Kalender kann nun einfach ausgewählt werden. Neue Features:
** Mehrere Lieferländer auswählbar
** Auswahl des Eigners und Anzeige in alphabetischer Reihenfolge
** Auswahl der Zahlungsarten
** Mandantenauswahl
** Lagerauswahl
** Unter *Auftragsstatus* können mehrere Optionen angezeigt werden.
** Hauptaufträge können aus der Auswahl ausgeschlossen werden.

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Plugins

* Wir ändern eine Funktion in der Git-Benutzeroberfläche. Anstatt ein Git-Plugin mit einem Commit-Hash auf einen bestimmten Zustand zu fixieren, muss es in Zukunft mit einem Tag fixiert werden. Die Branch-Funktionalität bleibt erhalten.
+
[NOTE]
.Kein To-Do
======
Wenn aktuell ein Commit für ein Git-Plugin gewählt wird, bleibt es so. Erst wenn du das Plugin für die Zukunft auf einen bestimmten Zustand festlegen möchtest, musst du stattdessen ein Tag verwenden.
======

[discrete]
=== Rechte

In den vergangenen Monaten haben wir mit dem Großteil des Plattform-Kern-Teams an dem Login- und Rechtesystem von plentymarkets gearbeitet.

Die ersten Projekte, die nun bereitgestellt werden, sind die umgebauten Benutzeroberflächen sowie die Rechtevergabe von Benutzer:innen. Das Ziel hierbei war es, die Rechtevergabe einfacher und verständlicher zu gestalten. Im Kern wurden Daten in neue Strukturen übertragen und alles weitere für zukünftige Schritte vorbereitet.

Dabei wurden nicht nur neue UIs, sondern auch strukturelle Änderungen vorgenommen:
* API-Rechte, Ressourcen sowie Sichtbarkeiten können nur noch an Rollen hinterlegt werden. Dabei wurden alle vorhandenen Einstellungen der Benutzer:innen in individuelle Rollen hinterlegt. Die Rechte bestehender Benutzer:innen-Konten ändern sich dadurch nicht.
* Die Session-Verwaltung UI wurde entfernt.
* Die UIs unter *Einrichtung » Einstellungen » Benutzer* wurden umgezogen zu *Einrichtung » Kontoverwaltung*.

Im Menü *Einrichtung » Kontoverwaltung » Konten* werden die Benutzer:innen-Konten des plentymarkets Systems verwaltet. Die Zuweisung von Berechtigungen erfolgt hierbei nur noch durch das Verknüpfen von Rollen.

Im Menü *Einrichtung » Kontoverwaltung » Rollen* werden die Benutzer:innen-Rollen verwaltet. Die Konfiguration der Rechte erfolgt nicht mehr primär durch die API-Berechtigungen, sondern durch Sichtbarkeiten der jeweiligen Menüpunkte und deren Unterbereiche.

[IMPORTANT]
.API-Rechte
======
Die benötigten API-Berechtigungen werden nun automatisch der Rolle zugewiesen, je nachdem welche Sichtbarkeiten vergeben sind. Die dadurch vergebenen API-Berechtigungen können nicht eingeschränkt werden.

Sollten Komponenten in den sichtbaren UIs hinzugefügt oder entfernt werden, werden die API-Berechtigungen entsprechend automatisch hinzugefügt oder entfernt.
======

Für dich bedeutet das folgendes:

* Es ist keine manuelle Pflege von API-Berechtigungen mehr notwendig, falls Komponenten in den UIs von uns ergänzt oder umgebaut werden.
* Sichtbarkeiten von Plugin-Menüpunkten sind ebenfalls im Menü-Baum zu finden.
* Explizite API-Berechtigungen können weiterhin über den erweiterten Modus zugewiesen werden.
* Zugriffseinschränkungen für Lager, Kennzahlen, Auftragsherkünfte und Mandanten werden ebenfalls an den Rollen gepflegt.
* Freigabe für benutzerdefinierte Ansichten (jetzt rollendefinierte Ansichten) erfolgt ebenfalls an den Rollen.
* Eigner:innenrechte werden jetzt im einfachen Modus der Rollenbearbeitung vergeben, durch das aktivieren von *Bearbeiten* oder *Erstellen*.

Im Menü *Einrichtung » Kontoverwaltung » Sicherheit* befindet sich jetzt die Konfigurationen für Passwortsicherheit.

Weitere Informationen zu den Änderungen und Auswirkungen auf bestehende Abläufe findest du auf der Handbuchseite xref:business-entscheidungen:benutzerkonten-zugaenge.adoc[Benutzer:innen-Konten und Zugänge].

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Artikel (Neue UI)

* In der neuen Artikel-UI kam es zum Fehler, dass beim Varianten erstellen 0 Varianten erzeugt wurden. Dieses Verhalten haben wir nun korrigiert und das Erstellen funktioniert wieder korrekt.
* Das Hochladen und Aktualisieren von Dateien an Dateieigenschaften funktioniert wieder wie gewohnt.

[discrete]
=== Aufträge

* Fehlermeldungen werden jetzt angezeigt, wenn das Speichern von Auftragsnotizen fehlschlägt.
* In den überarbeiten Einstellungs-UIs unter *Einrichtung » Aufträge » Auftragstypen » Reparatur* bzw. *Einrichtung » Aufträge » Auftragstypen » Retouren* können nun bis zu 100 Werte hinterlegt werden (früher waren nur 25 Werte möglich). Beim Erstellen einer neuen Retoure / Reparatur kam es zu einem Validierungsfehler, wenn der dort eingestellte Grund größer als 25 war. Dies wurde nun korrigiert.

[discrete]
=== Payment

* Für die Währungen KES, ANG, UAH, VND, XCD, BOB, IDR wurden keine Umrechnungskurse von unserer verwendeten API zur Verfügung gestellt. In der Vergangenheit hat dies dazu geführt, dass bei diesen Währungen immer der Umrechnungskurs auf 1 gesetzt wurde, wenn die Einstellung *Umrechnungsfaktoren täglich automatisch aktualisieren* aktiv war. Für diese Währungen ist es nun möglich, im Menü *Einrichtung » Aufträge » Zahlung » Währung* einen Umrechnungskurs zu hinterlegen, auch wenn die Einstellung *Umrechnungsfaktoren täglich automatisch aktualisieren* aktiv ist.

--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|link:https://marketplace.plentymarkets.com/dhlshipping_4871[DHL Shipping (Versenden)^]
|3.1.24
|-

|link:https://marketplace.plentymarkets.com/checkoutgoodie_55295[Gratiszugabe im Warenkorb anzeigen^]
|1.1.1
|-

|link:https://marketplace.plentymarkets.com/mirakl_6917[Mirakl Connector^]
|1.2.9
|-

|link:https://marketplace.plentymarkets.com/mollie_6272[Mollie^]
|2.8.24
|-

|link:https://marketplace.plentymarkets.com/multicontentwidget_6082[Multicontent Toolbox^]
|4.7.25
|-

|link:https://marketplace.plentymarkets.com/paypal_4690[PayPal Checkout^]
|6.2.4
|-

|link:https://marketplace.plentymarkets.com/freeshippinggoal_55307[Versandkostenfrei ab Warenwert erreichen^]
|1.0.6
|-

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

====
