= Changelog 19. Juli 2023
:author: kevin-stederoth
:sectnums!:
:page-index: false
:startWeekDate: 13. Juli 2023
:endWeekDate: 19. Juli 2023

// Ab diesem Eintrag weitermachen: https://forum.plentymarkets.com/t/auftrag-ui-externe-auftrags-id-fuer-retouren-order-ui-external-order-id-for-returns/729650
// Auch folgenden Eintrag beachten: https://forum.plentymarkets.com/t/new-order-ui-select-status-component-adapted-neue-auftrags-ui-status-auswaehlen-komponente-angepasst/728760
// Auch folgenden Eintrag beachten: https://forum.plentymarkets.com/t/benutzerrechte-neue-und-geaenderte-rechte-fuer-cms-user-rights-new-and-changed-rights-for-cms/728913

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Aufträge

* In der Auftrags-UI werden nach dem Speichern von Änderungen an einem Auftrag diese auch in der Auftragsübersicht dargestellt. Dieses Verhalten wurde auch für die Bearbeitung der Auftragspositionen implementiert. Wenn Änderungen an Auftragspositionen gespeichert werden, werden diese sowohl in der Übersichtstabelle als auch in den Auftragsdetails dargestellt.
* Die Felder im Kompaktmodus haben jetzt ein neues Aussehen.
+
Um den Kompaktmodus weiter zu verbessern und die Felder besser zu unterscheiden, haben die Kompaktfelder jetzt ein neues Aussehen. Jedes Feld wird mit einem grauen Hintergrund und abgerundeten Ecken dargestellt.
+
Die Standardfarbe für die Hervorhebung der Felder bleibt unverändert und sorgt für Vertrautheit und Benutzerfreundlichkeit. Sowohl das Standard-Ansichten-Set als auch alle zuvor gespeicherten Ansichten-Sets behalten ihre ursprünglichen Farben. Die neuen Designverbesserungen fügen sich nahtlos in die bestehenden Ansichtssätze ein.
* Für folgende Filter wurde der neue Filteroperator `NIN` (nicht enthalten) hinzugefügt:
** Tag
** Lager
** Auftragsstatus
** Herkunft
** Mandant (Shop)
** Auftragstyp
** Zahlungsstatus
** Zahlungsart
** Versandart
** Rechnungsland
** Lieferland
** Kundenklasse
** Versandprofil
** Markierung

[discrete]
=== Fulfillment

* Du kannst ab jetzt im Versand-Center den Filter für die externe Auftragsnummer finden. Um die externe Auftragsnummer in der Übersicht sehen zu können, füge die Spalte über die Konfiguration (material:settings[]) hinzu.

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== CRM

* Bei den Zugangsdaten von E-Mail-Konten wird das Passwort nicht mehr angezeigt. Diese Änderung wurde für den E-Mail-Assistenten, den Messenger-Assistenten, die Newsletter-Kontoeinstellungen und die Ticket-Konteneinstellungen vorgenommen.

[discrete]
=== plentyShop

* Die Einstellung *Shop sperren* kann jetzt genutzt werden um plentyShops von individuellen Mandanten zu sperren. Das entsprechende Menü wurde vorher nur beim Hauptmandanten angezeigt. Es ist nun für alle Mandanten an dieser Stelle auffindbar: *Einrichtung » Mandant » Mandanten wählen » Webshop » Shop sperren*.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Aufträge

* Die folgenden Korrekturen wurden für den Kompaktansicht hinzugefügt:
** Aufgrund der Scrollposition-Implementierung für den Kompaktmodus war die Navigation nicht ohne die erste Datensuche bzw. ohne ein initiales Scrollen möglich. Dies wurde behoben.
** Beim Scrollen von weniger als zehn Aufträgen im Kompaktmodus funktionierte die Funktion *Scrollposition merken* nicht. Dies wurde behoben.
** Beim Duplizieren eines Auftragstabs ist es zu einen Fehler gekommen und die Benutzeroberfläche wurde nicht korrekt geladen. Dies wurde nun behoben.
* Die folgenden Behebungen wurden der Warenkorb-Tabelle für Auftragspositionen hinzugefügt:
** Die Liste der gültigen Verkaufspreise enthielt einen NaN *Manueller Preis* und der Auftrag konnte nicht gespeichert werden. Dies wurde behoben.
** Die Bundle-Komponenten erhalten nach dem Bearbeiten des Bundle-Preises einen gültigen Verkaufspreis. Dies wurde behoben.
** Die Spalten *Nettopreis* und *Bruttopreis* wurden mit NaN gefüllt, wenn ein neuer Artikel zur Einkaufswagentabelle hinzugefügt wurde. Dies wurde behoben.
* Bei der neuen Auftragsanlage konnte es unter Umständen zu einem Fehler beim Anlegen kommen. Dies wurde behoben.
* Die Möglichkeit Nachbestellung aus einem Lieferauftrag anzulegen wurde hinzugefügt.
* Im Dialog zum bearbeiten der Adresse wurde in einigen Fällen die Paketstation nicht korrekt erkannt. Dies wurde nun behoben.

[discrete]
=== Dokumente

* In DocumentBuilder wurde die Variable `Lieferanten-Artikelbezeichnung` auf Nachbestellungsdokumenten nicht korrekt gefüllt. Diese wurde behoben.

[discrete]
=== Prozesse

* Wenn man mit den Prozessen eine Retoure bearbeiten wollte die einen Tag am Retouren Auftrag gesetzt hatte, kam es dazu das diese Retoure vom Prozess nicht bearbeitet werden konnte (`Fehler beim Aktualisieren der Retoure XXX: validation error found`).

--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Artikel (Neue UI)

* Spaltenbreite anpassbar in folgenden UIs:
** Artikelübersicht
** Variantenübersicht
** Paketbestandteile hinzufügen
** Setbestandteile hinzufügen
** Cross-selling hinzufügen

[discrete]
=== Aufträge

* In der Auftrags-UIs sind die Spalten in der Verlaufstabelle jetzt in der Größe veränderbar.
* Der Transfer-Lagerort wurde als optionales Element in den MyView-Bereich *Allgemein* der Auftragsdetailansicht hinzugefügt.

[discrete]
=== CRM

* Im Firmendatensatz im Menü *CRM » Firma* haben wir das Portlet *Aufträge* hinzugefügt. Das Portlet zeigt die Aufträge von allen Kontakten, die mit dieser Firma verknüpft sind.
+
Die Option zum Hinzufügen eines neuen Auftrags wurde entfernt und es wurden zwei neue Spalten (Kontakt-ID und Kontaktname) in der Übersicht hinzugefügt. Beim Klick auf die Kontakt-ID wird man zum Kontaktdatensatz im Menü *CRM » Kontakte* weitergeleitet.

[discrete]
=== Dokumente

* In den Ausgabeeinstellungen des DocumentBuilder kann nun für jede Vorlage eingestellt werden ob als Währungsformat der ISO-Code (EUR, USD) oder das Symbol ($, €) verwendet werden soll.
* Im DocumentBuilder können auf *Auftragsebene* nun zusätzlich folgende Variablen genutzt werden:
** Externe Quellauftrags-ID (Auftragseigenschaft mit der Typ-ID `62`)
* Im DocumentBuilder können für *Artikelpositionen* nun zusätzlich folgende Variablen genutzt werden:
** Seriennummer
** Model
** Herstellerland
** Artikelvorschautext

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== CRM

* Das Limit für den Mindestbestellwert bei Firmen wurde auf 999999999,99 angehoben.
* Die Assistenten *E-Mail-Konten* und *Messenger-Konfiguration* wurden verschoben:
** Die *E-Mail-Konten* findest du ab sofort unter *Einrichtung » Mandant » Global » E-Mail-Konten*.
** Die *Messenger-Konfiguration* findest du unter *Einrichtung » CRM » Messenger » Posteingänge*.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Artikel (Neue UI)

* Tritt ein Fehler bei der Gruppenfunktion in der neuen Artikel-UI auf, friert das Fenster dazu nicht mehr ein.
* In manchen Tabellen hat das Hinzufügen von Markierungen dafür gesorgt, dass die Tabelle nicht richtig geladen wurden. Dieses Problem haben wir behoben.
* Wenn man nach dem ersten Artikel einen weiteren im gleichen Durchlauf erstellen wollte, hat das trotz Erfolgsmeldung nicht funktioniert. Außerdem gab es keine Fehlermeldung, wenn eine Variante mit gleicher Variantennummer angelegt werden sollte. Beide Fehlverhalten haben wir korrigiert.

[discrete]
=== Aufträge

* In der neuen Auftrags-UI wurden für den Filter *Auftragstyp*, der in den Filtern der Auftragsübersichtstabelle verfügbar ist, die Optionen *Teilweise Lieferung* und *Multi-Lieferung* entfernt.
* Fehler behoben, dass die PDF Vorschau im Safari Browser nicht funktioniert.
* Das Notizen-Widget in den Auftragsdetails wurde angepasst, dass der Text nicht mehr abgeschnitten ist.
* Styling für die Felder *Markierung* und *Mahnstufe* im Kompaktmodus angepasst
* In der Nachbestellung bei den Verkaufspreisen können jetzt 4 Nachkommastellen verwendet werden.
* In der neuen Auftrags-UI war es nicht möglich den Mandant bei einen Sammelauftrag zu ändern. Dies wurde nun behoben.
* In der Rückbuchungsansicht für den Bestand, wurde unter Artikel-ID die ID der Auftragsposition angezeigt. Dies wurde nun behoben.
* Fehler behoben, dass die Versandkosten nicht geändert werden konnten, falls diese nicht als Auftragsposition existiert haben.

[discrete]
=== Prozesse

* In den Prozessen ist es vorgekommen das die Wagenkennung nach dem vollständigen erfassen und Abschliessen der Pickliste über die Aktion *Artikelerfassung* nicht von der Pickliste getrennt wurde. Diese Situation ist meist im Parallelbetrieb der Prozesse und plentyWarehouse App vorgekommen.
Dieser Fehler wurde behoben.

'''

[discrete]
== Gelöscht

Folgende Funktionalität wurde in den letzten 7 Tagen auf *{version}* gelöscht.

[discrete]
=== CRM

* Die Assistenten *Basics* und *Kontaktdatenimport* wurden aus dem Menü *Einrichtung » Assistenten » Grundeinrichtung* entfernt. Die Einstellungen, die im Assistenten *Basics* vorgenommen werden konnten, kannst du in den folgenden Menüs vornehmen:
** *Einrichtung » Einstellungen » Stammdaten*
** *Einrichtung » Einstellungen » Bankdaten*
** *Einrichtung » Kontoverwaltung » Konten*

+
Den Kontaktdatenimport bereitest du im Menü *Daten » Import* im Import-Typ *Kontakte, Firmen und Adressen* vor.

--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|link:https://marketplace.plentymarkets.com/enderecoaddressautocomplete_6622[Adressprüfung und Adresskorrektur mit Endereco^]
|2.1.6
|-

|link:https://marketplace.plentymarkets.com/edon_6618[FairGeben^]
|1.8.1
|-

|link:https://marketplace.plentymarkets.com/elasticexportidealode_4723[idealo.de^]
|3.4.7
|-

|link:https://marketplace.plentymarkets.com/io_4696[IO^]
|5.0.60
|-

|link:https://marketplace.plentymarkets.com/netseasypay_55565[Nexi - Nets Checkout^]
|1.0.1
|-

|link:https://marketplace.plentymarkets.com/paypal_4690[PayPal Checkout^]
|6.3.4
|-

|link:https://marketplace.plentymarkets.com/ceres_4697[plentyShop LTS^]
|5.0.60
a|
Im Zuge des Releases von Ceres 5.0.60 gab es Änderungen an Template-Dateien, die für Theme-Entwickler:innen relevant sind. Die Verlinkung führt direkt zu der umgesetzten Änderung in den entsprechenden Dateien.

* link:https://github.com/plentymarkets/plugin-ceres/pull/3421/files#diff-1b8d2c7ce7416f660f89d11ad8e368be614c2b98efc30526e74286c7f180c3b8[resources/views/Category/Item/Partials/Pagination.twig^]
* link:https://github.com/plentymarkets/plugin-ceres/pull/3433/files#diff-192a8837dba88964356b7ecd49003fe083ed719e2c601b9623e6dd4b24be9326[resources/views/Item/SingleItemWrapper.twig^]
* link:https://github.com/plentymarkets/plugin-ceres/pull/3427/files#diff-4c35af622ef09ba8949eb1c47557e3e6651b088291a0d2e2463c9244007b5516[resources/js/src/app/components/itemList/CategoryItem.vue^]

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

Warehouse-App::
+
--

[discrete]
== Neu

Folgende Neuerungen wurden in Version 1.0.19 der *plentymarkets Warehouse App* veröffentlicht.

* Wenn innerhalb der *Inventur* alle benötigten Daten für MHD und Charge gescannt wurden, muss die Eingabe nun nicht mehr manuell bestätigt werden.
* Innerhalb der Funktion *Wareneingang* wird nun automatisch der Lieferant gesetzt, der am einzubuchenden Artikel gepflegt ist. Dieses Verhalten lässt sich über die Einstellung innerhalb der plentyWarehouse App steuern.

In der plentyWarehouse App wurde außerdem eine neue Funktion zur Kommissionierung hinzugefügt. Mit der Funktion namens Einzelkommissionierung lassen sich gezielt einzelne Aufträge suchen und die Artikel für diese Aufträge kommissionieren. Wird ein Auftrag über die im Feature integrierte Auftragssuche ausgewählt, wird für diesen Auftrag eine temporäre Pickliste generiert. Diese Pickliste wird dann in plentyWarehouse angezeigt und kann direkt abgearbeitet werden.

Im Menü *Einstellungen » Einzelkommissionierung* der plentyWarehouse App lassen sich wie auch in anderen Features der plentyWarehouse App die Suchfelder, der Fokus, die Sortierung der Suchergebnisse und Einstellungen zur Artikel-Scanpflicht einstellen. Außerdem ist es vor der erstmaligen Nutzung der Funktion notwendig, vier Status festzulegen:

* *Quellstatus*: Status, aus denen in plentyWarehouse Aufträge für die Einzelkommissionierung ausgewählt werden können
* *Erfolgsstatus*: Status, in den Aufträge verschoben werden, nachdem sie vollständig kommissioniert wurden
* *Blockstatus*: Status, in den Aufträge während des laufenden Pickvorgangs verschoben werden
* *Fehlerstatus*: Status, in den Aufträge geschoben werden, wenn während des Pickvorgangs Probleme auftreten und der Vorgang abgebrochen wird

Damit die Funktion für Lager-Mitarbeiter:innen ohne Admin-Rollen sicht- und nutzbar ist, muss das entsprechende Recht in der Rollenverwaltung im plentymarkets Backend gesetzt werden. Öffnet dazu das Menü *Einrichtung » Kontoverwaltung » Rollen » [Rolle öffnen]* und aktiviert im Abschnitt *plentyWarehouse* die Option *Einzelkommissionierung*.

'''

[discrete]
=== Behoben

Folgende Probleme wurden in Version 1.0.20 der *plentymarkets Warehouse App* behoben.

* Wenn im Menü *Einstellungen » Wareneingang* ein fester Ziellagerort für jeden Wareneingang ausgewählt wurde, wurde dieser nach erstmaligem Abschluss eines Wareneingangs nicht mehr für nachfolgende Wareneingänge automatisch gesetzt. Dieses Verhalten wurde behoben, sodass der ausgewählte Lagerort
für alle nachfolgenden Wareneingänge automatisch gesetzt wird.
* Wenn im Menü *Einstellungen » Picklisten* der plentyWarehouse App die Option *Eingabe einer Wagenkennung ermöglichen* aktiviert war, konnten innerhalb der Funktion *Einzelkommissionierung* keine Picklisten geöffnet werden. Dieses Verhalten wurde behoben.
* In manchen Fällen konnten gewisse Aufträge nicht über die Auftragssuche der Funktion *Einzelkommissionierung* gefunden werden. Dieses Verhalten wurde behoben.

--

====
