= Changelog 18. Januar 2023
:author: kevin-stederoth
:sectnums!:
:page-index: false
:startWeekDate: 12. Januar 2023
:endWeekDate: 18. Januar 2023

// Ab diesem Eintrag weitermachen: https://forum.plentymarkets.com/t/fix-gutscheincode-variable-hat-mehrere-gutscheincodes-generiert-fix-coupon-code-variable-generated-multiple-coupon-codes/708553
// Auch diesen Eintrag beachten: https://forum.plentymarkets.com/t/auftraege-testphase-falsches-warengewicht-orders-test-phase-wrong-item-weight/708166

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Artikel

* Wir haben einen Zeichenzähler für die Artikel-Texte, sowie die HTML-, Text-, und Zeichenketten-Eigenschaften eingefügt.
* In der neuen Artikel-UI ist es jetzt möglich, die Varianten-Gruppenfunktion in der Variantenübersicht eines Artikels zu verwenden.
* Es gibt nun einen Schalter unter *Einrichtung > Artikel > Neue Artikel-UI (Testphase)*, um die neue Artikel-UI als Standard Artikel-UI festzulegen. Links aus anderen UIs (z. B. Aufträge) leiten ebenfalls auf die neue Artikel UI um. Diese Einstellung gilt nur für den jeweiligen Nutzer und lässt sich jederzeit aktivieren oder deaktivieren.

[discrete]
=== Aufträge

* In der neuen Auftrags-UI und in der Auftragsanlage kann der Rabatt nun für jeden einzelnen Artikel bearbeitet werden.
* In der neuen Auftrags-UI kannst du im Bereich *Allgemein* eines Auftrags ab sofort die Markierung wählen. Es handelt sich dabei um ein reines Anzeigefeld, d.h. die Markierung kann nicht geändert werden.
* In den Auftragsdetails steht nun der Bereich *Tickets* zur Verfügung. Dieser ist standardmäßig nicht eingeblendet, kann aber über die MyView hinzugefügt werden.
* In der neuen Auftrags-UI kann die Größe der Spalten von nun an in den folgenden Tabellen angepasst werden:
** Tabelle in der Auftragsübersicht;
** Tabelle der Auftragspositionen (in der Übersicht sowie in den Auftragsdetails);
** Tabelle der Variantensuche in der Ansicht Artikel bearbeiten;
** Tabelle des Warenkorbs in der Ansicht Artikel bearbeiten

[discrete]
=== CRM

* Wenn eine Adresse mit einem Auftrag verknüpft ist, kann man diese Adresse nicht löschen. Wir haben im Hintergrund die Funktion eingebaut, dass die Relation „Kontakt/Adresse“ jetzt entfernt wird, wenn das Löschen der Adresse fehlschlägt. Die neue Meldung im Backend lautet: `Die Adresse konnte nicht gelöscht werden, weil sie mit einem Auftrag verknüpft ist. Die Relation zum Kontakt wurde gelöscht.`
* Im Messenger wurde der Filter *Posteingang* hinzugefügt, mit dem du nach Konversationen aus einem bestimmten Posteingang suchen kannst.

[discrete]
=== Fulfillment

* Unter der Paketnummer im Versand-Center 2.0 ist nun die Sendungsverfolgung für das jeweilige Paket hinterlegt und kann durch einen Klick auf die Nummer direkt aufgerufen werden.
* Die zuletzt verwendeten Werte für den Versanddienstleister, die zwei Auftragsstatusfelder sowie für den Versanddientsleister im Fall einer Retoure bleiben ab sofort im Cache, so dass diese Einstellungen nicht wieder neu ausgewählt werden müssen.

[discrete]
=== Kataloge

* Im Menü *Daten » Katalogexportstatus* kannst du ab sofort die Kataloge auch danach filtern, ob sie Fehler enthalten oder nicht. Weitere Informationen findest du auf der Handbuchseite xref:daten:catalogues-status.adoc#overview-filters[Exportstatus prüfen].

[discrete]
=== Kaufland

Ab sofort kannst du deine Artikel auf den neuen Kaufland-Länderplattformen Kaufland CZ (Tschechien) und Kaufland SK (Slowakei) listen.

[NOTE]
.Hinweis
======
Da Kaufland die neuen Marktplätze für Tschechien und die Slowakei noch nicht eröffnet hat, kannst du deine Artikel dort auch noch nicht verkaufen. Du kannst aber bereits Kataloge für die Länderplattformen erstellen und so bereits die Artikel zum Verkauf vorbereiten. Deine Artikel werden dann schon an Kaufland übertragen, können jedoch noch nicht auf den Marktplätzen Kaufland.cz und Kaufland.sk von Kund:innen gekauft werden. Der Marktplatz Kaufland SK wird im Februar 2023 eröffnet.
======

[IMPORTANT]
.To-Do
======
*Kataloge für Kaufland CZ und Kaufland SK erstellen*

Um Artikel auf Kaufland in Tschechien oder der Slowakei zu listen, erstelle mit dem Assistenten *Kaufland - Kataloge erstellen* Kataloge für die neuen Länderplattformen. Dazu wählst du im Assistenten die gewünschte Länderplattform und die Produktkategorie aus. Anschließend verknüpfst du die Datenfelder im neu erstellten Katalog. Wie das geht, ist auf der Handbuchseite xref:maerkte:kaufland-de-einrichten.adoc#create-catalogue[Kaufland.de einrichten] beschrieben.

Verknüpfe außerdem deine Varianten mit der Produktkategorie (Eigenschaft), in der sie auf Kaufland CZ oder Kaufland SK gelistet werden sollen. Weitere Infos dazu findest du ebenfalls auf der Handbuchseite xref:maerkte:kaufland-de-einrichten.adoc#varianten-mit-katalog-kategorie-verknüpfen[Kaufland.de einrichten].

*Hinweis: Sprache für Produktdaten*

* In den Katalogen für Kaufland wurde das Feld *Sprache der plentymarkets Produktdaten* hinzugefügt. Dieses Feld ist kein Pflichtfeld; es ist jedoch für die Kaufland-Länderplattformen CZ und SK relevant, wenn die Produktdaten in plentymarkets auf Deutsch gepflegt werden.
* Wenn das Feld *Sprache der plentymarkets Produktdaten* nicht zugeordnet wird und leer bleibt, dann geht das System davon aus, dass die Produktdaten in plentymarkets in der Sprache des jeweiligen Marktplatzes gepflegt werden.
* Wenn die Produktdaten in plentymarkets auf Deutsch gepflegt werden, muss dieses Feld also zugeordnet werden, damit die Produktdaten bei der Übertragung in die Sprache des Marktplatzes übersetzt werden.
* Erlaubte Werte für die Zuordnung: `de`, `sk`, `cz`

*Neue Auftragsherkünfte aktivieren*

Vergiss nicht, die neuen xref:maerkte:kaufland-de-einrichten.adoc#250[Auftragsherkünfte zu aktivieren]:

* *102.02 Kaufland CZ*
* *102.03 Kaufland SK*

*_Hinweis:_* Wenn du deine Artikel auf allen Kaufland-Länderplattformen, also in Deutschland, Tschechien und der Slowakei anbieten willst, musst du nur die übergeordnete Herkunft für Kaufland aktivieren (*102 Kaufland*).
(Natürlich müssen die Artikel dafür auch mit der Produktkategorie für die jeweilige Länderplattform verknüpft sein.)
======

[NOTE]
.Mit der Neuerung verbundene Änderungen
======
Aus diesem Update ergeben sich außerdem folgende Änderungen:

* Alle Kaufland-Aufträge haben nun die Herkunft *102.01 Kaufland DE*.
* Wenn du im Menü *Daten » Log* nach Einträgen zu Kaufland suchen willst, verwende ab sofort den Identifikator *Kaufland* (nicht mehr *Kaufland.de*).
======

[discrete]
=== Netto

Unter *Einrichtung » Märkte » Netto eStores » Tab: Einstellungen » Bereich: Bestelleinstellungen* wurden Optionen für die Zuordnung deiner Versanddienstleister zu Netto hinzugefügt.

Wenn kein passender Versanddienstleister bei Netto vorliegt, dann wähle keinen Versanddienstleister. Dann übertragen wir abhängig davon, ob eine Paketnummer am Auftrag vorliegt, automatisch entweder `Sonstige` oder `Sonstige mit Paketnummer`.

[IMPORTANT]
.To-Do
======
Im Zuge des Updates musst du folgende Schritte durchführen:

. Gehe unter *Einrichtung » Märkte » Netto eStores » Tab: Einstellungen* in den Bereich *Bestelleinstellungen*.
. Ordne deine Versanddienstleister den Versanddienstleistern von Netto zu.

*_Wichtig:_* Dieser Schritt muss spätestens vor dem nächsten Speichern der Einstellungen geschehen. Sonst werden die Zuordnungen ohne tatsächliche Zuordnungen gespeichert. Das führt dazu, dass wir als Versanddienstleister Sonstige übertragen werden.
======

[discrete]
=== Prozesse

* Der Auftragsabruf für die Aktion Auftragsabwicklung wurde optimiert. Die folgenden Rechte sollten wie üblich an dem Benutzerkonto oder an der Rolle gesetzt sein.
** *Aufträge > Aktualisieren*
** *Aufträge > Auftragsstatus > Aktualisieren*

[discrete]
=== Shopify-App

* In der neuen Shopify-App haben wir die folgenden Funktionen ergänzt:
** Die Verbindungsbereitschaft prüfen.
** Exportbedingungen einer Variante prüfen.
** Alle 10 Minuten einen Artikel manuell exportieren.
** Alle 5 Minuten den Warenbestand einer Variante oder eines ganzen Artikels exportieren.
** Die plentymarkets Auftrags-ID anhand der Shopify-Auftragsnummer finden.
** Eine Artikelbereinigung planen.

+
Im Zuge der Neuerung wurde auch xref:externe-webshops:shopify-app.adoc#plugin-help[die Handbuchseite zur Shopify-App] erweitert. Eine Checkliste für den Variantenexport hilft dir dabei, deine Varianten für den Export flott zu machen.

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Amazon

FBA-Aufträge aus Nordamerika, für die wir keine Adressdaten im Auftragsbericht erhalten, werden im Status `[1.0000]` ohne Adressen importiert. Ein neuer Prozess, der alle 5-Minuten läuft, prüft auf FBA-Aufträge in diesem Status und aktualisiert diese Aufträge. Dabei werden so lange Adressdaten nachgeladen, bis wir auf das API-Limit stoßen und dann erst beim nächsten Lauf des Prozesses weiter gemacht.

Bei der Adressaktualisierung, wird außerdem
* der Auftrag in den Status verschoben, der für deinen Auftragseingang in den Amazon-Einstellungen definiert wurde.
* der Warenausgang gebucht, falls dies in den Amazon-Einstellungen definiert wurde.
* der Auftrag als bezahlt markiert.

[IMPORTANT]
.To-Do
======
Es muss sichergestellt werden, dass die FBA-Aufträge im Status `[1]` verbleiben. Sämtliche Ereignisaktionen, die diese Aufträge verschieben könnten, müssen entweder deaktiviert oder so angepasst werden, dass sie nicht mehr durch FBA-Aufträge mit den Herkünften aus Nordamerika ausgelöst werden.
======

[discrete]
=== Netto

In Absprache mit Netto wurde die Zuordnung von Paketnummern zu Auftragspositionen in der Versandmeldung vereinfacht. Bisher wurde bei mehreren Paketnummern jeder Menge 1 einer Auftragsposition eine Paketnummer zugeordnet. Da die Paketnummern aber keinen Auftragsartikeln zugeordnet sind, war dies mehr oder minder zufällig. Im Folgenden findest du ein Beispiel:

[source,xml]
------
<LINE_ITEM_ID>1</LINE_ITEM_ID>
<PRODUCT_ID>
    <bmecat:SUPPLIER_PID>XXXXX</bmecat:SUPPLIER_PID>
    <bmecat:BUYER_PID>XXXXXXXXXX</bmecat:BUYER_PID>
    <bmecat:DESCRIPTION_SHORT>Item Name</bmecat:DESCRIPTION_SHORT>
</PRODUCT_ID>
<QUANTITY>3</QUANTITY>
<bmecat:ORDER_UNIT>C62</bmecat:ORDER_UNIT>
<DELIVERY_COMPLETED>true</DELIVERY_COMPLETED>
<ORDER_REFERENCE>
    <ORDER_ID>XXXXXXXXX</ORDER_ID>
    <LINE_ITEM_ID>1</LINE_ITEM_ID>
</ORDER_REFERENCE>
<SHIPMENT_PARTIES_REFERENCE>
    <DELIVERY_IDREF>XXXXXXXXX</DELIVERY_IDREF>
</SHIPMENT_PARTIES_REFERENCE>
<LOGISTIC_DETAILS>
    <PACKAGE_INFO>
        <PACKAGE>
            <PACKAGE_ID>1244334234</PACKAGE_ID>
            <PACKAGE_QUANTITY>1</PACKAGE_QUANTITY>
        </PACKAGE>
        <PACKAGE>
            <PACKAGE_ID>12414124124</PACKAGE_ID>
            <PACKAGE_QUANTITY>2</PACKAGE_QUANTITY>
        </PACKAGE>
    </PACKAGE_INFO>
</LOGISTIC_DETAILS>
------

Da die Summe der Mengen in den Logistic Details nicht mehr korrekt sein müssen, werden jetzt alle Paketnummern immer der Gesamtmenge aller Auftragspositionen zugeordnet:

[source,xml]
------
<LINE_ITEM_ID>1</LINE_ITEM_ID>
<PRODUCT_ID>
    <bmecat:SUPPLIER_PID>20837</bmecat:SUPPLIER_PID>
    <bmecat:BUYER_PID>2450141000</bmecat:BUYER_PID>
    <bmecat:DESCRIPTION_SHORT>[BUNDLE] Juskys Balkonkraftwerk 600W
        So</bmecat:DESCRIPTION_SHORT>
</PRODUCT_ID>
<QUANTITY>3</QUANTITY>
<bmecat:ORDER_UNIT>C62</bmecat:ORDER_UNIT>
<DELIVERY_COMPLETED>true</DELIVERY_COMPLETED>
<ORDER_REFERENCE>
    <ORDER_ID>065504208</ORDER_ID>
    <LINE_ITEM_ID>1</LINE_ITEM_ID>
</ORDER_REFERENCE>
<SHIPMENT_PARTIES_REFERENCE>
    <DELIVERY_IDREF>215756189</DELIVERY_IDREF>
</SHIPMENT_PARTIES_REFERENCE>
<LOGISTIC_DETAILS>
    <PACKAGE_INFO>
        <PACKAGE>
            <PACKAGE_ID>1244334234</PACKAGE_ID>
            <PACKAGE_QUANTITY>3</PACKAGE_QUANTITY>
        </PACKAGE>
        <PACKAGE>
            <PACKAGE_ID>12414124124</PACKAGE_ID>
            <PACKAGE_QUANTITY>3</PACKAGE_QUANTITY>
        </PACKAGE>
    </PACKAGE_INFO>
</LOGISTIC_DETAILS>
------

Hiermit wird gewährleistet, dass Endkund:innen immer alle Paketnummern erhalten.

[discrete]
=== Payment

* Da aufgrund der anpassbaren Tabellenbreite in der Zahlungsverkehr-UI nicht alle zur Auswahl stehenden Aktionen am rechten Rand sichtbar waren, wurden diese nun in einem Kontextmenü (Drei-Punkte-Menü) untergebracht.
* Die Auswahl der Zahlungsarten im Filter für Zahlungsarten ist auf *Suchbar im Backend* eingeschränkt. Hierdurch wurden die Zahlungsarten *Manuelle Zahlung* sowie *Bankbuchung* nicht mehr angezeigt. Diese werden nun korrekt als *Suchbar im Backend* registriert.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Amazon

Es wurde eine nachhaltige Lösung für FBA-Aufträge aus Nordamerika entwickelt, für die wir in den Auftragsberichten keine Adressen mehr von Amazon erhielten. Bisher gab es nur eine kurzzeitige Lösung, bei der die Adressdaten per API direkt beim Import nachgeladen wurden, was aber aufgrund der API-Limitierungen regelmäßig nicht funktionierte. Mehr Details findest du im Abschnitt *Geändert*.

Aufträge, für die keine Adressdaten abgerufen werden konnten, wurden nicht importiert. Für den betroffenen Zeitraum seit Juli 2022 werden automatisiert neue Auftragsberichte erzeugt, um fehlende Aufträge im Laufe der Woche nachträglich zu importieren.

[discrete]
=== Aufträge

* Bisher konnte die PDF-Datei für Mehrzweckgutscheine nur erstellt werden, wenn der dazugehörige Auftrag vollständig bezahlt war. Bei überbezahlten Aufträgen hingegen wurde keine PDF-Datei erstellt. Nun werden PDFs auch für überbezahlte Aufträge erstellt.
* In der neuen Auftragsanlage war in den Eingabefeldern *Preis (brutto)* und *Preis (netto)* im 2. Schritt der Warenkorb-Tabelle der Wert `0` nicht möglich. Dies wurde behoben.
* In der Auftragsübersicht ist es im Dialog *Referenzierte Bestellungen anzeigen* zu einen Fehler gekommen, wenn man einen Auftrag öffnen wollte. Dieser Fehler wurde behoben.
* Im letzten Schritt der neuen Auftragsanlage wurde bei der *Artikelmenge (gesamt)* die Menge der Auftragsposition angezeigt und nicht die Summierten mengen der einzelnen Positionen. Dieser Fehler wurde behoben.
* In der neuen Auftrags-UI hat das Duplizieren des Auftrags-Tabs nicht funktioniert. Dies wurde behoben.

[discrete]
=== Elastischer Export

* Im Elastischen Export hat der Filter für den Mandanten nicht funktioniert. Wenn dieser Filter gesetzt war, wurde keine CSV-Datei ausgegeben. Beim Export mit einem Limit höher als 9999 wurde eine leere Datei ausgegeben. Dieses Verhalten wurde behoben.

[discrete]
=== Ereignisaktionen

* In der Ereignisaktion konnte es zu einem Fehler kommen, wenn ein gesetzter Tag-Filter vor dem 11.01.2023 erstellt order zuletzt gespeichert wurde. Dieses Verhalten wurde behoben.

[discrete]
=== Netto

[.collapseBox]
.Fehler bei Auftragsmeldungen vom 12.01.2023
----
Am 12.01.2023 kam es zu Problemen bei den Auftragsmeldungen (Versand, Storno und Retoure) zu Netto- und Marktkauf-Aufträgen durch ein unsichtbares Sonderzeichen in der XML.

Das Problem wurde bereits am Abend des 12.01.2023 gelöst. Wir haben von Netto eine Liste betroffener Händler und Aufträge bekommen.

Da wir unabhängig vom Auftragstyp nachvollziehen können, ob eine Auftragsmeldung am 12.01.2023 erfolgte oder nicht, werden folgende Meldungen für die betroffenen Aufträge ausgeführt.

* Reguläre Aufträge oder Lieferaufträge werden als storniert gemeldet, wenn diese sich in einem Status von `8.000` bis `8.999` befinden. Ansonsten wird eine Versandmeldung ausgelöst.
* Retouren und Gutschriften lösen eine erneute Retourenmeldung aus.

Betroffene Systeme bekommen nach Ausführung der Migration eine Benachrichtigung im System angezeigt, welche über die Anzahl der betroffenen Aufträge laut Netto und die Anzahl der erneut gemeldeten Aufträge. Zusätzlich können diese Händler unter *Daten » Log* über den Identifikator *NettoResendOrderNotifications20230113* Meldungen zu den Einzelaufträgen finden.
----

[.collapseBox]
.Versandmeldungsprobleme für Lieferaufträge mit Paketkomponenten
----
Wenn zu Aufträgen mit Paketartikeln Lieferaufträge erstellt werden, dann werden nur die Paketbestandteile in die Lieferaufträge übernommen. Dadurch wurde bei der Versandmeldung über den Lieferauftrag stattdessen eine Stornierung ausgelöst, weil die Artikelmenge auf 0 gesetzt wurde. Die Artikelmenge kommt zustande, weil die Paketkomponente keine direkte Relation zum ursprünglich bestellten Artikel auf Netto mehr hat.

Das Problem wurde jetzt behoben. Dazu wurde Folgendes angepasst:

* Der Paketbestandteil aus dem Lieferauftrag wird auf den Paketartikel aus dem Hauptauftrag referenziert und der anteilige Bestand (aufgerundet auf natürliche Zahlen) des Lieferauftrags gemeldet. Beispiel:
** Auftrag 1 hat einen Paketartikel mit der Menge 2.
** Ein Paket besteht aus 2 Komponenten A und 2 Komponenten B.
** Wenn in einem Lieferauftrag zu dem Auftrag 1-2 Komponenten A hinterlegt sind, dann wird ein Paketartikel als versendet gemeldet. Wenn 3-4 Komponenten A hinterlegt sind, dann wird die Menge 2 als versendet gemeldet.
* Wir dürfen in Summe der Versandmeldungen nie mehr als die ursprünglich bestellte Menge übermitteln und müssen übermitteln, ob es sich um die letzte Versandmeldung handelt. Dazu wird jetzt beim Auslösen der Ereignisaktion durch einen Hauptauftrag mit Lieferaufträgen oder einen Lieferauftrag alle verwandten Haupt- und Lieferaufträge auf die Summe der bereits übermittelten Auftragspositionen geprüft. Wurden bereits alle Positionen gemeldet, wird die Meldung abgebrochen.

*_Achtung:_* Daraus ergibt sich automatisch, dass nur die Paketnummern des Auftrags übermittelt werden, für den die Ereignisaktion ausgelöst wurde. Dies war vorher auch schon der Fall, wir wollten es aber nochmal hervorheben.
----

[discrete]
=== Payment

* Die Übereinstimmungsrate wurde bei der Zahlungszuordnung nicht in allen Fällen korrekt erhöht wenn die externe Auftragsnummer ein "-" Zeichen beinhaltet hat. Diese wurde behoben.

[discrete]
=== Plugins

* Bei ClosedSource-Plugins wurde die Übersetzung der Konfigurationsfelder nicht angezeigt. Dieses Verhalten ist nun behoben.

--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Aufträge

* In der neuen Auftrags-UI (Testphase) sind die *Variantennummer* und die *Externe Auftrags-ID* nun für die Schnellsuche in den Filtern der Auftragsübersicht aktiviert. Um die Schnellsuche auszulösen, muss etwas in das Eingabefeld des Filters eingetragen werden.

[discrete]
=== CRM

* Ab sofort kannst du im Messenger Prioritäten in Form von Sternen für Konversationen setzen. Außerdem kannst du Konversationen mit einer bestimmten Priorität über den Filter suchen und die Prioritäten in der Übersicht auf- und absteigend sortieren.

[discrete]
=== Kataloge

* Beim Katalog für Aufträge ist jetzt die Auftragseigenschaft für den Handelsvertreter verfügbar (Typ-ID 992).

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Ereignisaktionen

* Wir haben den Namen der Aktion *Status des Hauptauftrags ändern* zu *Status des Elternauftrags ändern* geändert. Von eurer Seite aus sind keine Änderungen notwendig.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Aufträge

* In der neuen Auftragsanlage wurden die Auftragsdetails im ersten Schritt nicht zurückgesetzt, nachdem ein Auftrag erstellt wurde. Dies wurde behoben.
* In der neuen Auftrags-UI (Testphase) wurden nach Ausführung der Aktion *Warenausgang buchen* und anschließendem Wechsel in einen anderen Auftrag in der Seitennavigation die ursprünglichen Auftragsdetails wiederhergestellt, wenn man zum eigentlichen Auftrag zurück navigierte. Dies wurde behoben.
* In der neuen Auftrags-UI (Testphase) und in der neuen Auftragsanlage hatten die Tabellenspalten mit anpassbarer Größe die falsche Standardbreite, was die Daten unlesbar machte. Dies wurde behoben und eine Standardbreite wurde für jede Spalte hinzugefügt.

[discrete]
=== Prozesse

* Dokumente vom Typ *Lieferschein* und *Angebot*, die über REST an den Hauptauftrag geladen werden, können jetzt wieder von den Prozessen abgerufen werden.

'''

[discrete]
== Entfernt

Folgende Funktionalität wurde in den letzten 7 Tagen in *{version}* entfernt.

[discrete]
=== Artikel

* Wir haben Suchfelder entfernt, die keinen Einfluss auf die Suche haben.

--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|link:https://marketplace.plentymarkets.com/avocado_55217[AvocadoStore Connector^]
|1.1.8
|-

|link:https://marketplace.plentymarkets.com/ebics_5098[EBICS^]
|1.2.1
|-

|link:https://marketplace.plentymarkets.com/etsy_4689[Etsy^]
|2.1.37
|-

|link:https://marketplace.plentymarkets.com/limango_7023[limango^]
|1.4.25
|-

|link:https://marketplace.plentymarkets.com/mirakl_6917[Mirakl Connector^]
|1.2.8
|-

|link:https://marketplace.plentymarkets.com/mollie_6272[Mollie^]
|2.8.21
|-

|link:https://marketplace.plentymarkets.com/paypal_4690[PayPal Checkout^]
|6.1.6
|-

|link:https://marketplace.plentymarkets.com/schuhe24_54954[Schuhe24 Import-/Exportplugin^]
|2.10.2
|-

|link:https://marketplace.plentymarkets.com/shopifytoolbox_55341[Shopify Toolbox - Erweiterung der Shopify Schnittstelle^]
|1.0.1
|-

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

====
