= Changelog 1. Februar 2023
:author: kevin-stederoth
:sectnums!:
:page-index: false
:page-aliases: ROOT:changelog.adoc
:startWeekDate: 26. Januar 2023
:endWeekDate: 1. Februar 2023

// Ab diesem Eintrag weitermachen: https://forum.plentymarkets.com/t/1-0-4-benutzerkonten-mit-ueberfluessigen-leerzeichen-im-realen-namen-nicht-verwendbar-user-accounts-with-superfluous-spaces-in-the-real-name-could-not-be-used/710274

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Aufträge

* In der neuen Auftrags-UI (Testphase) wurden die optionalen Spalten *Kontakt (Rechnungsadresse*) und *Kontakt (Lieferadresse)* sowie ein optionaler Filter für *Adressdaten* hinzugefügt.

[discrete]
=== Check24

Zu den Check24-Katalogen *Check24* und *Check24 Furniture* wurden neue Datenfelder hinzugefügt.

.Neue Datenfelder im Katalog Check24
[cols="1,3"]
|===
|Datenfeld |Empfohlene Zuordnung

|Energieeffizienzklasse (A-G)
|Eigenschaft des Typs *Text* oder *Auswahl*, _erlaubte Werte_: `A`, `B`, `C`, `D`, `E`, `F`, `G`

|Energieverbrauchskennzeichnung
|Eigenschaft des Typs *Text*, URL der Energieverbrauchskennzeichnung als Text eingeben

|Produktdatenblatt
|Eigenschaft des Typs *Text*, URL des Produktdatenblatts als Text eingeben

|Montageanleitung
|Eigenschaft des Typs *Text*, URL der Montageanleitung als Text eingeben
|===

.Neue Datenfelder im Katalog Check24 Furniture
[cols="1,3"]
|===
|Datenfeld |Empfohlene Zuordnung

|Energieverbrauchskennzeichnung
|Eigenschaft des Typs *Text*, URL der Energieverbrauchskennzeichnung als Text eingeben
|Produktdatenblatt
|Eigenschaft des Typs *Text*, URL des Produktdatenblatts als Text eingeben
|Montageanleitung
|Eigenschaft des Typs *Text*, URL der Montageanleitung als Text eingeben
|===

Weitere Informationen zur Erstellung von Katalogen und Verknüpfung von Datenfeldern findest du auf der Handbuchseite xref:maerkte:check24.adoc#catalogue-export[Check24].

[discrete]
=== CRM

* Im Messenger kannst du ab sofort eigene Ordner erstellen und die Konversationen in einen oder mehrere Ordner verschieben. Füge in der Übersicht die Spalte *Ordner* hinzu, damit du auf einen Blick sehen kannst, in welchen Ordnern die Konversation gespeichert ist. Die Ordner können auch umbenannt und gelöscht werden.

[discrete]
=== Etsy

*Kein Etsy-Plugin mehr nötig*

Für die Einrichtung von Etsy in plentymarkets ist jetzt kein Plugin mehr nötig.

Wenn du Etsy in plentymarkets einrichten willst, um deine Artikel dort anzubieten, öffne das Menü *Einrichtung » Märkte » Etsy » Einstellungen*. Dieses Menü ist jetzt standardmäßig in jedem plentymarkets System vorhanden und du musst kein Plugin mehr installieren, um Etsy nutzen zu können.

*Neue Auftragsherkunft für Etsy*

Da das Etsy-Plugin nicht mehr benötigt wird, bekommen Aufträge für Etsy nun eine neue Auftragsherkunft:

* `156.00 Etsy`

Etsy-Aufträge werden also ab sofort mit der Herkunft `156.00 Etsy` in dein plentymarkets System importiert.

*Überarbeitete Menüs für Einstellungen und rechtliche Hinweise*

Im Zuge dieses Updates wurden auch die Etsy-Menüs Einstellungen und Rechtliche Hinweise überarbeitet, um sie moderner und benutzerfreundlicher zu machen. Die Einstellungen für Etsy bleiben gleich.

[NOTE]
.Hinweis
======
Das Menü *Einrichtung » Märkte » Etsy » Authentifizierung* ist veraltet und hat keine Funktion mehr, da es für das Etsy-Plugin benötigt wurde. Dieses Menü wird aus plentymarkets entfernt. Du musst hier also keine Einstellungen vornehmen. Wichtig ist aber, dass du dein Etsy-Konto im Menü *Einrichtung » Märkte » Etsy » OAuth2* für OAuth2 authentifizierst.
======

[discrete]
=== Fulfillment

* Wie im neuen Versand-Center kannst du jetzt auch in der Paketinhaltsliste durch einen Klick auf die Paketnummer die Sendungsverfolgung öffnen.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Amazon

[IMPORTANT]
.Betroffene Systeme
======
Der folgende Fehler betrifft nur Systeme, bei welchen bereits die Versandmeldung auf die SP-API umgestellt wurde. Dies ist aktuell nur bei early- und beta-Systemen der Fall. Siehe dazu auch folgendes Thema im Forum: link:https://forum.plentymarkets.com/t/update-wechsel-auf-amazon-selling-partner-api-phase-2-switch-to-amazon-selling-partner-api-phase-2/704375[Amazon Selling Partner API: Rollout Phase 2^]
======

Es kam bei Versandmeldungen für Aufträge ohne Paketnummer zu einem Fehler, wodurch die Versandmeldung für diese Aufträge nicht erfolgte und auch keine Einträge für diese Aufträge in den API-Logs zu finden sind. Dies lag daran, dass für die SP-API fälschlicherweise die Paketnummer als Pflichtfeld angenommen wurde, was so nicht korrekt war. Das Feld wird jetzt wieder korrekt als optional angesehen.

[IMPORTANT]
.To-Do
======
Solltet ihr den Versand nicht bereits manuell gemeldet haben, dann könnt ihr die Versandmeldung unter *Einrichtung » Märkte » Amazon » Datenaustausch » Versandbestätigung* neu auslösen.
======

[discrete]
=== Aufträge

* In der Detailansicht der neuen Auftrags-UI wurde das Warengewicht falsch berechnet. Dies wurde behoben.
* In der neuen Auftrags-UI (Testphase) waren die Werte der Spalte *Versandkosten* ist der Übersichtstabelle nicht sichtbar. Dies wurde behoben.
* Bei der Erstellung von Umbuchungen wird der Button zum Hinzufügen von Items nicht mehr fälschlicherweise deaktiviert.

[discrete]
=== CRM

* Die Variable für den Gutscheincode hat mehrere Gutscheincodes generiert, wenn diese in der Newsletter Opt-In-E-Mail enthalten war: einmal wenn der Kunde sich für den Newsletter registriert hat und ein weiteres Mal, wenn die Anmeldung zum Newsletter bestätigt wurde. Dieses Verhalten wurde behoben.
* Im Bereich *Sprachabhängige Einstellungen* einer E-Mail-Vorlage im EmailBuilder wurden in der gesendeten E-Mail statt 2 Nachkommastellen standardmäßig 4 Nachkommastellen für das Feld *Anzahl der Dezimalstellen* ausgegeben. Dieses Verhalten wurde behoben. Ab sofort werden standardmäßig 2 Nachkommastellen in gesendeten E-Mails ausgegeben.

[discrete]
=== Kataloge

* Die Formelberechnung im Artikelkatalog berechnet einen nicht verknüpften Lagereintrag in der Formelberechnung nun mit 0 und bricht nicht mehr ab.

[discrete]
=== Payment

* In der Auftragsansicht der Zahlungsverkehr-UI wurden alle Zahlungen angezeigt, nicht nur die, die zu dem entsprechenden Auftrag gehörten. Dieser Fehler wurde behoben.

--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Artikel (Neue UI)

* In der neuen Artikel-UI kann man jetzt Einstellungen für die Sortierung der Verkaufspreisverknüpfungen in der Tabelle und dem Verkaufspreispicker vornehmen. Mögliche Sortierungen in der Tabelle:
** Verkaufspreis Name
** Verkaufspreis Position
** Verknüpfter Verkaufspreis aktualiert am
** Verkaufspreis ID
** Verkaufspreis Wert

+
Mögliche Sortierung in dem Picker:
** Verkaufspreis Name
** Verkaufspreis Position
** Verkaufspreis Wert
* In der neuen Artikel-UI gibt es nun einen Link zum entsprechenden Auftrag einer Warenbewegung (sofern verfügbar).
* Für neue Systeme gibt es nun vereinfachte Standard Ansichten. Dies betrifft die Artikelansicht, die Variantenansicht, die Artikeltextansicht und die Eigenschaftenansicht. Hintergrund ist die Reduzierung von intial angezeigten Datenfeldern für Neukunden um einen leichteren Einstieg zu gewährleisten.
* In der Variantenansicht ist es nun möglich, sowohl die verknüpften Barcodes als auch die Liste der Barcodes beim Hinzufügen nach Name oder Typ zu sortieren. Die entsprechenden Einstellungen sind im Editiermodus der Ansicht am Barcode-Element zu finden.

[discrete]
=== Aufträge

* In der Übersicht der neuen Auftrags-UI wurde bei der Übersicht des Warenbestands ein Link zu den Nachbestellungen hinzugefügt.
* In der Übersicht der neuen Auftrags-UI wurde bei der Übersicht des Warenbestands die Spalte für den reservierten Bestand hinzugefügt.

[discrete]
=== CRM

* Ab sofort kannst du in der Übersicht des Messengers die Breite der Tabellenspalten nach deinen Wünschen anpassen.
* Ab sofort kannst du eine geöffnete Konversation per Klick wieder schließen, um in die Übersicht des Messenger zurückzukehren.

[discrete]
=== Shopify-App

Ab 1. April 2023 können wir die Fulfillment-Informationen nicht mehr wie bisher an die Shopify-API senden. Shopify hat diese Änderung link:https://shopify.dev/apps/fulfillment/migrate[schon länger angekündigt^].

Deshalb haben wir bereits neue Berechtigungen in der plentymarkets-App eingeführt. Das To-Do dazu findest du in link:https://forum.plentymarkets.com/t/shopify-app-neue-rechte-erforderlich-shopify-app-new-permissions-required/707136[einem älteren Changelog^].

Wir haben plentymarkets nun aktualisiert, um die neuen Shopify-Fulfillment-Prozesse handhaben zu können.

*Sobald die neue API-Version Pflicht wird, akzeptiert Shopify nur noch eine Tracking-Nummer pro Bestellung.*

Um trotzdem mehr als eine Tracking-Nummer zu senden, kannst du die Bestellung in Lieferaufträge aufteilen. Wenn du keine Lieferaufträge erstellst oder wenn eine Bestellung nur einen Artikel enthält, der in mehreren Paketen versandt wird (z.B. Möbel), wird plentymarkets nun alle Tracking-Nummern derselben Bestellung verketten und durch Kommas trennen (z.B. 123456789,123456778).

In Shopify werden diese verketteten Tracking-Nummern als eine einzige Tracking-Nummer behandelt. Wenn Kund:innen also auf den Link zur Sendungsverfolgung klicken, um Informationen über ihre Pakete zu erhalten, wird nur die erste Tracking-Nummer auf der Website des Versandunternehmens aufgerufen. Kund:innen müssen die anderen Nummern manuell kopieren und einfügen. Außerdem müssen sie selbst darauf kommen, dass überhaupt mehr als eine Kontrollnummer angegeben ist.

*Wie geht es weiter?*

* Wenn du die neuen Berechtigungen in der Shopify-App schon erteilt hast, wird die neue API-Version verwendet, sobald die Änderung deine plentymarkets Version erreicht.
* Wenn du die neuen Berechtigungen noch nicht erteilt hast, link:link:https://forum.plentymarkets.com/t/shopify-app-neue-rechte-erforderlich-shopify-app-new-permissions-required/707136[tue dies bitte so bald wie möglich^].

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Artikel (Neue UI)

* Die Spaltenreihenfolge für verknüpfte Eigenschaften wurde geändert in "Name - Wert - Eigenschaftsgrupp". Im Fall von Bestelleigenschaften zu "Name - Aufpreis - Eigenschaftsgruppe". Dadurch wird unnötiges horizontales Scrollen vermieden.
* Wir haben die Standardansicht für die Variantenübersichten vereinfacht. Wer andere Spalten und Spaltenreihenfolgen braucht und diese nicht bereits eingerichtet hat, kann dies jederzeit über den Button für die Spaltenkonfiguration einrichten.
* Wir haben das Standard Layout der EIgenschaftenunterseite angepasst. Insbesondere haben wir 33/33/33 Raumaufteilungen zugunsten von 50/50 Raumaufteilungen geändert.

[discrete]
=== Aufträge

* Die alten UIs unter *Einrichtung » Aufträge » Auftragstypen » Reparatur* und *Einrichtung » Aufträge » Auftragstypen » Retoure* wurden modernisiert.
* In der neuen Auftrags-UI werden nun bestimmte Funktionen nur dargestellt, wenn die benötigten Rechte dafür vorhanden sind. Vorher kam es beim Ausführen der Funktion zu einem Fehler, wenn bestimmte Benutzerrechte fehlten. Dies ist nun nicht mehr der Fall. Weitere Informationen findest du auf der Handbuchseite xref:auftraege:preparatory-settings.adoc#benutzerrechte-vergeben[Vorbereitende Einstellungen vornehmen].

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Artikel (Neue UI)

* Unter gewissen Bedingungen war es möglich, dass das erneute Öffnen einer Hauptvariante nach dem Speichern diese in einem veraltetet Zustand dargestellt hat. Dieses Fehlverhalten haben wir behoben.

[discrete]
=== Aufträge

* In Aufträgen wurde bei Paketbestandteilen keine Auftragspositionseigenschaft für das Lager angelegt. Das Lager konnte somit z.B. nicht über den Katalog exportiert werden. Dies wurde behoben.
* Beim Verknüpfen einer Zahlung mit einem Auftrag wurde der `updatedAt`-Zeitstempel des Auftrags nicht jedesmal aktualisiert. Dies wurde behoben.
* In der neuen Auftrags-UI kam es beim Wechsel zwischen verschieden Aufträgen gelegentlich zu dem Fehler, dass mehrere externe Rechnungen hochgeladen werden konnten. Dieser Fehler wurde behoben.
* In der Übersichtstabelle der neuen Auftrags-UI wurde bei nicht gesperrten Aufträgen ein Entsperrt-Symbol angezeigt. Für eine bessere Übersichtlichkeit wurde dieses Symbol entfernt. Nun wird nur noch bei gesperrten Aufträgen ein Gesperrt-Symbol angezeigt.
* In der Auftragsanlage konnte es vorkommen, dass einige Eigner nicht angezeigt wurden. Dies wurde behoben.
* In der neuen Auftrags-UI (Testphase) wurden die Versandkosten beim Öffnen der Auftragsdetails auf die nächste ganze Zahl gerundet. Dies wurde behoben.

[discrete]
=== Kataloge

* Ist im Katalog eine Währung beim Verkaufspreis eingestellt, wird er nun erst korrekt umgerechnet, wenn am Preis auch die Live-Umrechnung aktiv ist.

--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|link:https://marketplace.plentymarkets.com/uniservaddresscleansing_6869[Adressprüfung und Adresskorrektur mit Uniserv^]
|2.0.4
|-

|link:https://marketplace.plentymarkets.com/blog_6103[Blog^]
|2.0.6
|-

|link:https://marketplace.plentymarkets.com/deepl_5900[DeepL - Für professionelle Übersetzungen^]
|2.3.0
|-

|link:https://marketplace.plentymarkets.com/clearvat_6925[eClear - Grenzüberschreitender E-Commerce - so einfach wie Inlandsverkäufe^]
|3.0.2
|-

|link:https://marketplace.plentymarkets.com/klarna_6731[Klarna^]
|2.4.7
|-

|link:https://marketplace.plentymarkets.com/lexoffice_54996[Lexoffice^]
|1.0.7
|-

|link:https://marketplace.plentymarkets.com/mollie_6272[Mollie^]
|2.8.22
|-

|link:https://marketplace.plentymarkets.com/multicontentwidget_6082[Multicontent Toolbox^]
|4.7.24
|-

|link:https://marketplace.plentymarkets.com/mytoys_54776[myToys^]
|1.0.64
|-

|link:https://marketplace.plentymarkets.com/shopify_4944[Shopify.com^]
|2.15.0
|Bevor du das Plugin aktualisierst, musst du plentymarkets zusätzliche Berechtigungen zuweisen. Wie das geht, erfährst du im link:https://forum.plentymarkets.com/t/shopify-plugin-update-auf-neue-shopify-fulfillment-api-shopify-plugin-update-to-new-shopify-fulfillment-api/710252[Forum^].

Wenn du das Plugin aktualisierst, bevor du die nötigen Rechte erteilt hast, können Shopify und plentymarkets keine Daten mehr austauschen.

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

Warehouse-App::
+
--

[discrete]
== Neu

Folgende Neuerungen wurden in Version 1.0.3 der *plentymarkets Warehouse App* veröffentlicht.

* Beim Laden einer Nachbestellung im Wareneingang ist es nun möglich, die bereits hinzugefügten Artikel den Positionen der Nachbestellung zuzuordnen.

'''

[discrete]
=== Behoben

Folgende Probleme wurden in Version 1.0.3 der *plentymarkets Warehouse App* behoben.

* In der Vergangenheit war es nicht möglich, Nachbestellungen aus dem Wareneingang zu entfernen. Die Artikel der Nachbestellung und die Verknüpfungen zur Nachbestellung blieben erhalten. Dieses Verhalten wurde nun behoben. Das neue Verhalten ist wie folgt:
** Wird der letzte Artikel aus einer Nachbestellung entfernt, so wird auch die Nachbestellung entfernt.
** Wird die Nachbestellung entfernt, werden auch alle nicht gepickten Artikel entfernt. Nur die gepickten Artikel bleiben erhalten, aber ihre Verknüpfung zur Nachbestellung wird entfernt.
* Hat ein Nutzer nicht die notwendigen REST-API-Rechte für eine Aktion, sieht der Nutzer einen Hinweis, dass ihm die Rechte fehlen.
* Der Firmenname eines Lieferanten wurde nicht durchgehend angezeigt. Dieses Verhalten wurde behoben. Wenn ein Firmenname für einen Kontakt gespeichert wurde, wird dieser nun angezeigt. Ansonsten wird die Kombination aus Vor- und Nachname (vollständiger Name) angezeigt.
* Picklisten konnten bei nachträglich gelöschten Artikelpositionen nicht geladen werden. Dieser Fehler wurde behoben.
* Artikelpositionen die nicht Teil der zuvor ausgewählten Nachbestellung sind werden nun grau markiert. Somit lässt sich besser unterscheiden ob Artikel Teil der Nachbestellung sind oder nicht.

--

====
