= Changelog 7. Juni 2023
:author: kevin-stederoth
:sectnums!:
:page-index: false
:startWeekDate: 1. Juni 2023
:endWeekDate: 7. Juni 2023

// Ab diesem Eintrag weitermachen: https://forum.plentymarkets.com/t/auftrag-ui-weisse-leere-stelle-in-der-in-uebersichtsartikeln-tabelle-order-ui-white-space-in-overview-items-table/724273

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Amazon

* Folgende Amazon-Prozesse wurde überarbeitet:
** Bestandsupdate
** Rückerstattungsimport

+
[NOTE]
.Kein To-Do
======
Der Prozess funktioniert genauso wie vorher. Auch an den Einstellungen im plentymarkets Backend hat sich nichts geändert.
======

[discrete]
=== Aufträge

* Ab sofort können in der Auftragsübersicht Notizen zu Aufträgen erstellt werden. Außerdem werden bereits vorhandene Notizen zu einem Auftrag angezeigt.
* In der Detailansicht der neuen Auftrags UI ist es jetzt möglich, ein Abonnement aus einem Angebot zu erstellen.
* In der neuen Auftrags-UI enthält das Zahlungs-Widget in der Auftrags-Detailansicht jetzt eine neue Schaltfläche zum Zurücksetzen der Zahlungen für einen Auftrag.

[discrete]
=== CRM

* Ab sofort kannst du über die MyView im Kontaktdatensatz Einstellungen zum Adress-Layout in der primären Adresse vornehmen. Über das Stift-Symbol gelangst du direkt in das Menü *Einrichtung » CRM » Adress-Layout*.
+
Wenn du die Schaltfläche aktivierst, kannst du zwischen den Optionen *Layout basierend auf dem Adressland verwenden* und *Immer das selbe Adress-Layout verwenden* wählen.
+
Wenn du die Option *Immer das selbe Adress-Layout verwenden* wählst, öffnet sich die Dropdown-Liste Adress-Layouts und du kannst das von dir im Menü *Einrichtung » CRM » Adress-Layout* erstellte Adress-Layout wählen.

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Amazon

Im Menü *Artikel » Artikel (Testphase) » [Variante öffnen]* wird im Bereich *SKU* für die Herkunft *Amazon* das Amazon-Konto nun im folgenden Format dargestellt:

`<alte Konto-ID> - <Konto-Name (ISO2 des Channels)>`

*_Beispiel:_* `6 - beispiel@beispiel.de (DE)`

[discrete]
=== CRM

* Wie in diesem link:https://forum.plentymarkets.com/t/ankuendigung-schnellsuche-wird-in-kontakte-integriert-announcement-quick-search-will-be-integrated-in-contact/721970[Beitrag^] angekündigt, wurden die folgenden Funktionen aus der Schnellsuche in das Menü *CRM » Kontakte* umgezogen:
** Alle Daten aus einem Datensatz herunterladen
** Datensatz anonymisieren
** Gast in Kontakt umwandeln

[discrete]
=== Kaufland

* Die Zahlungsart *Zahlung über real.de* wurde umbenannt in *Kaufland*. Diese Änderung ist mit Kaufland so abgesprochen.
+
[NOTE]
.Kein To-Do
======
Es sind keine weitere Handlungen eurerseits erforderlich.
======

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Amazon

* Bei der Migration der Einstellungen in die neue UI und damit auch Logik wurde der Wert der Option *Menge für Artikel ohne Bestandsbindung* nicht übernommen und daher auch bei dem Bestandsabgleich nicht berücksichtigt. Dies wurde behoben.

[discrete]
=== Aufträge

* Wenn ein Auftrag Lieferaufträge hatte und ein Artikel zu dem Auftrag hinzugefügt wurde, dann hat in manchen Fällen die Lagerermittlung nicht funktioniert. Dies wurde behoben.
* Es konnte zu Fehlern kommen, wenn Auftragspositionen ohne Preis ein Rabatt zugeordnet wurde. Dies wurde behoben.
* Im neuen Auftrag erstellen UI waren die Änderungen des Mehrwertsteuersatzes und des Artikelnamens im zweiten Schritt nicht im letzten Schritt sichtbar. Dies wurde behoben.
* In der neuen Auftrags-UI wurde beim Bearbeiten der Auftragspositionen eine Warnmeldung angezeigt, wenn der Verkaufspreis kleiner als der Einkaufspreis war, aber es wurden keine relevanten Details über die betreffende Variante angezeigt. Dies wurde angepasst und die Warnung enthält nun die Variations-ID und den tatsächlichen Preis.
* In der neuen Auftrag erstellen UI wurden beim Neuladen der Aufträge in der Kompaktansicht die erweiterten Auftragspositionen nicht mit den neuen Daten neu geladen. Dies wurde nun behoben.
* Warenbestand ermitteln ist nun auch für Lieferauftrag und Reparatur verfügbar.
* Wenn eine Aktion an einen Auftrag in der Kompaktansicht durchgeführt wurde (z.B. Statuswechsel), hat sich der Auftrag in der Anzeige nicht aktualisiert. Dies wurde nun behoben.
* Die folgenden Änderungen wurden an der Auftragsdetails vorgenommen:
** Im Addresse-Widget wird nun bei Klick auf die Email-Adresse die Order ID als Betreff übernommen
** Bei dem Auftragstyp Gutschrift, kannst du im Bereich Allgemein eines Auftrags ab sofort das Feld *Zeichen Kunde* über die MyView hinzufügen
** Beim Erstellen eines manuellen Zahlungseingangs in der Auftrags-UI, konnte der Betrag nur mit Punkt angegeben werden. Dies wurde nun gefixt und es ist auch wieder ein Komma möglich.
* In der neuen Auftrags-UI wurde beim Bearbeiten des Versandpreises in der Auftrags-Detailansicht und Drücken der Eingabetaste eine Bestätigungsmeldung für die Änderung des Auftrags angezeigt. Dies wurde behoben.
* In der neuen Auftrags-UI wurde beim Bearbeiten der Auftragspositionen die Vorschau-Route bei jeder Änderung der Spalte mit dem Positionsnamen aufgerufen. Dies wurde behoben.

[discrete]
=== CRM

* Wenn man eine EmailBuilder-Vorlage über die Vorschau in der Auftrags-UI geöffnet hat, wurde statt des Namens die E-Mail-Adresse im Empfängerfeld angezeigt. Dieses Verhalten wurde behoben. Nun wird wieder der Name im Empfängerfeld angezeigt.
* In einigen Systemen kam es vor, dass die EmailBuilder-Vorlagen bei Aufträgen mit Bundles als Artikelposition nicht versendet werden konnten und der critical error `Division by zero` wurde im Log angezeigt. Dieses Verhalten wurde behoben.

[discrete]
=== Dokumente

* Der Platzhalter `[DiscountInvoiceAmountGross]` gab bei netto Aufträgen in den Auftragsdokumenten den skontierten brutto Betrag aus. Dies wurde behoben.

[discrete]
=== Kaufland

* Kaufland-Aufträge kommen immer unvollständig im Status 1 in das System und werden nach kurzer Zeit mit den fehlenden Informationen ergänzt und wechseln dann in den Status 3. Das Ergänzen der Aufträge konnte aufgrund eines Fehlverhaltens in vielen Fällen nicht statt finden. Das Problem wurde nun behoben.

[discrete]
=== MyView

* In MyView-Elementen war das Drag&Drop-Verhalten bisher fehlerhaft. Dieses Verhalten wurde nun angepasst, ab jetzt kannst du in einem MyView-Element die Drag&Drop-Funktion korrekt nutzen und somit die Elemente auch so platzieren wie du willst ohne das es zu Fehlern kommt.

[discrete]
=== plentyBase

* In den Backend-Einstellungen von plentyBase wurde das Access-Token nicht in voller Länge angezeigt. Dieses Verhalten wurde behoben.

'''

[discrete]
== Gelöscht

Folgende Funktionalität wurde in den letzten 7 Tagen von *{version}* entfernt.

[discrete]
=== CRM

* Das Menü *CRM » Schnellsuche* wurde aus dem Backend entfernt.

--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Aufträge

* Das Feld *Mahnstufe* steht jetzt in der Kompakt und Tabellenansicht verfügbar.
* In der Übersicht der neuen Auftrags-UI wurden Filter für Externe Artikel-ID (z.B. eBay-Artikelnummer), Externe Token-ID und Auftragspositionstyp hinzugefügt.
* In der Detailansicht der neuen Auftrags-UI wird eine vorhandene Umsatzsteuer-ID an der Rechnungsadresse dargestellt.
* In der Übersicht der neuen Auftrags-UI wird nun am Icon eingeblendet, wieviele Notizen für einen Auftrag bereits existieren.
* Bei der Erstellung von Kindaufträgen werden nun die Attribute der Auftragsposition angezeigt.

[discrete]
=== Dokumente

Ab sofort kann jede:r selbst entscheiden, wann und in welchem Umfang der DocumentBuilder zur Erstellung der Dokumentvorlagen genutzt wird. Unter dem Menüpunkt *Einrichtung » Dokumente* sind dann der DocumentBuilder und die Nummernkreise sowie die UI-Einstellungen in allen Systemen verfügbar. Über diese Einstellungs-UI kann man pro Dokumenttyp entscheiden, ob die alten Dokumentvorlagen oder der DocumentBuilder verwendet werden sollen.

Was ist zu beachten?

* Es wird sofort auf die Umstellung des Schalters in der Einstellungs-UI reagiert. Stellt also sicher, dass die Vorlagen für den entsprechenden Dokumenttyp vorhanden und (im Falle des DocumentBuilders) aktiviert sind, bevor ihr wechselt.
* Es gibt Standardvorlagen für Rechnung, Gutschrift, Mahnung, dazugehörige Storno- und Korrekturbelege sowie den Lieferschein. Diese sind immer aktiv und sind als letzter Fallback eingebaut, falls keine andere passende Vorlage gefunden wird. Das heißt, selbst wenn noch keine eigene Vorlage erstellt wurde, kann eine Standardvorlage zur Erstellung von Dokumenten genutzt werden, falls für den entsprechenden Dokumenttyp der DocumentBuilder in der Einstellungs-UI ausgewählt wurde.
* Nummernkreise werden ab sofort über die neue Nummernkreis UI für alle Dokumente erstellt und bearbeitet werden. Bestehende Nummernkreise wurden überführt und der alte Einstellungspunkt innerhalb der Dokumente wurde entfernt.
* Mit dem Wechsel zum DocumentBuilder wird auch die neue Logik im Hintergrund aktiviert und die Dokumente werden asynchron erstellt.
* Für alle neuen UIs stehen neue Benutzerrechte zur Verfügung. Alle Benutzerrechte und Sichtbarkeiten könnt ihr wie gewohnt im Backend einstellen.

[IMPORTANT]
.To-Do
======
Die asynchrone Erstellung erfordert Anpassungen an Ereignisaktionen und Prozessen.

* Prozesse: In Prozessen, in denen Dokumente gedruckt werden sollen, muss die xref:automatisierung:subaktionen.adoc#192[Subaktion Generieren] vorher eingefügt werden. So wird sichergestellt, dass das Dokument zur Verfügung steht.
* Ereignisaktionen: Sobald ein Dokument für eine Aktion zur Verfügung stehen muss, sollte dafür eine eigene Ereignisaktionen erstellt werden. Bestehende Ereignisaktionen sollten in diesem Fall voneinander getrennt werden. Habt ihr zum Beispiel eine gemeinsame Ereignisaktion für die Erstellung eines Dokuments und den Mailversand dieses Dokuments, solltet ihr diese Ereignisaktion trennen. So wird die Mail erst versendet, wenn das Dokument zur Verfügung steht.
======

link:https://forum.plentymarkets.com/t/ankuendigung-offene-beta-documentbuilder-ab-01-juni-announcement-open-beta-documentbuilder-from-june-1st/721015[Ankündigung]

xref:auftraege:nummernkreise-festlegen.adoc[Handbuchseite Nummernkreise]

xref:auftraege:document-builder.adoc[Handbuchseite DocumentBuilder]

[discrete]
=== Einrichtung

Unser Ziel ist es, für euch die Einrichtung eures plentymarkets Systems deutlich zu vereinfachen. In diesem Zuge gibt es folgende Anpassungen.

[discrete]
==== Assistenten

Mit Assistenten konnten wir die Einrichtung einzelner Bereiche vereinfachen. Dennoch sind wir mit dieser Technologie an Grenzen gestoßen. Nicht alle einzurichtenden Bereiche konnten gut mit Assistenten abgebildet werden. Wir haben uns dazu entschlossen, nicht weiter auf Assistenten zu setzen. Einige Assistenten haben wir bereits ersetzt, die restlichen werden schrittweise folgen. Übergangsweise werden die verbleibenden Assistenten in der Seitennavigation der Einstellungen in die thematisch passenden Menüpunkte umgezogen.

Zudem erhalten Assistenten, die durch Plugins erstellt werden, einen eigenen Menüpunkt.

[discrete]
==== Umbau der Einrichtungs-Benutzeroberflächen

Anstelle von Assistenten fahren wir zukünftig eine Doppelstrategie: Zum einen werden die Einrichtungs-Benutzeroberflächen neu gebaut und weiterhin nehmen wir euch durch Touren an die Hand, damit ihr schneller und Schritt für Schritt alle nötigen Einstellungen vornehmen könnt.

Da wir nicht alles direkt umsetzen konnten, haben wir uns im ersten Schritt auf die Bereiche fokussiert, die euch den größten Wert bringen: Die Einrichtung der drei umsatzstärksten Verkaufskanäle über alle unsere Händler hinweg. Es handelt sich um Amazon, plentyShop und OTTO Market.

Durch den Umbau der Benutzeroberflächen, die geführten Touren und den Wegfall der Assistenten schaffen wir ein einheitliches und klares Bild für unsere Einrichtung. Wir nutzen hiermit die vollen Möglichkeiten, die uns das aktuelle UI Framework bietet und geben euch gleichzeitig die notwendige Hilfestellung, das System zielgerichtet einzurichten.

[discrete]
==== Geführte Touren für Einrichtungen (neues Feature)

Mit geführten Touren erreichen wir zwei Ziele. Zum einen helfen sie dabei, sich einfacher in Einrichtungs-Benutzeroberflächen zurechtzufinden, weil diese Touren euch Schritt für Schritt die Oberflächen erklären. Zum anderen haben wir die Touren einem höheren Ziel, wir haben es intern "Reise" genannt, zugeordnet. Eine dieser möglichen Reisen ist zum Beispiel Amazon Eigenversand (MFN) einrichten. Somit erreichen wir, dass ihr euch einfacher in unseren Einrichtungs-Benutzeroberflächen zurecht findet und zum anderen wisst ihr auch genau, was alles zu erledigen ist, um den Zweck der Reise zu erfüllen.

Die Touren werden als erledigt angezeigt, sobald ihr diese komplett durchlaufen habt. Ihr könnt Touren aber auch als erledigt markieren, ohne sie zu durchlaufen oder auch wieder zurückzusetzen. Touren können in jedem Zustand beliebig oft gestartet oder auch zwischendurch geschlossen werden. Eine geschlossene Tour wird dann bei erneutem Aufrufen von vorne gestartet.

Die geführten Touren findet ihr unter *Einrichtung » Geführte Touren*.

Wenn ihr während einer Tour in eine andere Oberfläche wechseln müsst (z.B. Aufträge), z.B. weil ein Telefonat euch unterbricht und ihr etwas nachschauen müsst, dann könnt ihr über den Tab Einrichtung wieder zur Tour zurückkehren.

Wir werden diese geführten Touren nach und nach ausbauen, um euch bei weiteren Einrichtungen zu unterstützen.

[discrete]
==== Geführte Touren für täglich genutzte Benutzeroberflächen

Mit den geführten Touren für die Einrichtung haben wir einen ersten großen Schritt getan, um die Einrichtung deutlich zu vereinfachen. Als nächsten Schritt wollen wir diese Technologie verwenden, um euch damit die Nutzung von täglich verwendeten Benutzeroberflächen wie Artikel oder Aufträge näherzubringen und zu erklären. Hierfür haben die Planungen bereits begonnen.

[discrete]
=== plentyBI

* Im Bearbeitungsmenü für Tabellen im Menü *plentymarkets Logo (Start) » Dashboard* kannst du nun auswählen, wie viele Nachkommastellen für die Kennzahlergebnisse angezeigt werden. Dazu haben wir die neue Option *Nachkommastellen* hinzugefügt. Per Klick auf diese Option kannst du bis zu 4 Nachkommastellen für Ergebnisse von Kennzahlen in Tabellen anzeigen lassen. Weitere Informationen zur Einstellung findest du auf der Handbuchseite xref:business-entscheidungen:myview-dashboard.adoc#intable-decimal-places[Dashboard] (klappe die Box namens "Einstellungen für Tabellen vornehmen" auf).

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Aufträge

* Die Felder *Lager* und *Lager-ID* wurden zu einem Feld verbunden. Per MyView-Einstellung lässt sich nun auswählen, ob ID, Name oder ID und Name angezeigt werden soll.
* In der neuen Auftrags-UI war der Umrechnungskurs nicht mehr änderbar über die Benutzeroberfläche. Diese Möglichkeit wurde wieder zur Verfügung gestellt.

[discrete]
=== CRM

* Wenn für einen Kontakt mehr als 2 Bankdatensätze gespeichert sind, werden die Bankdaten in Form einer Tabelle angezeigt. In der Tabelle kannst du die Reihenfolge der Spalten nach deinen Wünschen anzeigen lassen. Wenn maximal 2 Bankdatensätze für den Kontakt gespeichert sind, werden diese weiterhin in Form von Kacheln angezeigt.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Artikel (Neue UI)

* Das Bearbeiten von Netto-Preisen in der neuen Artikel-UI ist wieder wie gewohnt möglich.

[discrete]
=== Aufträge

* In der Detailansicht von Abonnements wurde das Datum *Letzter Durchlauf* falsch angezeigt. Dies wurde behoben.
* Die Filter werden nun überschrieben, wenn man von einer anderen UI in die Auftragsübersicht mit vorgegebenen Filtern weitergeleitet wird.
* Der Fehler wurde behoben, dass die UI manchmal keine Aufträge anzeigt und leer bleibt, nach dem Tab-Wechsel.

[discrete]
=== CRM

* Das Menü *Einrichtung » CRM » Buchhaltung*, in dem man Einstellungen für die Anzeige in der OP-Liste vornehmen kann, war für einige Admin-Benutzer:innen nicht mehr sichtbar. Dieses Verhalten wurde behoben.
* Obwohl die Berechtigung für die Sichtbarkeit der alten E-Mail-Vorlagen erteilt war, wurden diese bei Benutzern ohne Admin Rechte nicht angezeigt. Dieses Verhalten wurde behoben.

[discrete]
=== Prozesse

* In den Prozessen konnte es vorkommen, dass ein altes nicht mehr gültiges Storno-Dokument geladen wurde, anstatt ein neues zu erstellen. Dieses Verhalten wurde behoben.

--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|link:https://marketplace.plentymarkets.com/uniservaddresscleansing_6869[Adressprüfung und Adresskorrektur mit Uniserv^]
|2.0.16
|-

|link:https://marketplace.plentymarkets.com/ebics_5098[EBICS^]
|1.2.3
|-

|link:https://marketplace.plentymarkets.com/debit_6362[Lastschrift^]
|1.0.15
|-

|link:https://marketplace.plentymarkets.com/extendedimagecarouselwidget_55287[Produkt Video + Bilder-Karussell Widget^]
|1.1.1
|-

|link:https://marketplace.plentymarkets.com/cfourproductwall5_6893[Produktwand Widget^]
|2.0.11
|-

|link:https://marketplace.plentymarkets.com/uptain_55274[uptain® Conversion Optimierung mit Popups und Abbrecher-Mails^]
|1.0.2
|-

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

Warehouse-App::
+
--

[discrete]
=== Neu

Folgende Funktionalität wurde in Version 1.0.12 der *plentymarkets Warehouse App* hinzugefügt.

* Innerhalb der Funktion *Picklisten* wird nun automatisch zur zuletzt geänderten Position der Pickliste gescrollt. Zusätzlich wird der Eintrag optisch hervorgehoben.
* Beim Öffnen der plentyWarehouse App wird nun ein Dialog angezeigt, der auf die anstehenden Änderungen im Bezug auf notwendige Benutzerrechte hinweist. Alle wichtigen Informationen zum Thema sind link:https://forum.plentymarkets.com/t/to-do-neue-rechte-fuer-rollen-in-plentywarehouse-new-rights-for-roles-in-plentywarehouse/721648[in dieser Ankündigung^] zu finden.

[discrete]
== Geändert

Folgende Änderungen wurden in Version 1.0.12 der *plentymarkets Warehouse App* veröffentlicht.

* Innerhalb der Funktion *Wareneingang* wird die Anzahl bereits erfasster Artikel nun links- statt rechtsbündig dargestellt.
* In den Funktionen *Lagerort inspizieren* und *Verräumen* wurden Shortcuts zur Druckansicht für Lagerort-Labels hinzugefügt.

[discrete]
=== Behoben

Folgende Probleme wurden in Version 1.0.12 der *plentymarkets Warehouse App* behoben.

* Beim Drucken eines Artikeletiketts wurde stets der Standardlagerort für das Etikett übernommen. Dieses Verhalten wurde behoben, sodass nun der aktuelle Lagerort des Artikels auf dem Etikett angezeigt wird.
* Innerhalb der Funktion *Picklisten* wurde die für die Einstellung *Einzelerfassung bis Menge* gewählte Artikelmenge nicht berücksichtigt, wenn Artikel durch Scan erfasst wurden. Dieses Verhalten wurde behoben, sodass die Einstellung auch berücksichtigt wird, wenn auf den Eintrag des entsprechenden Artikels in der Pickliste getippt.

--

====
