= Changelog 22. März 2023
:author: kevin-stederoth
:sectnums!:
:page-index: false
:page-aliases: ROOT:changelog.adoc
:startWeekDate: 16. März 2023
:endWeekDate: 22. März 2023

// Ab diesem Eintrag weitermachen: LINK EINFÜGEN

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Artikel (Neue UI)

* Es ist jetzt möglich in der neuen Artikel-UI Listings zu erstellen und vorhanden Listings zu öffnen. Neue Listings werden über einen Stepper erstellt.
* Wir haben den Picker für Lagerorte und Lieferanten an den folgenden Stellen an einer Variante in der neuen Item-UI ausgetauscht:
** Lagerort-Picker
*** Lagerkonfiguration
*** Wareneingang
*** Umbuchung
** Lieferanten-Picker
*** Wareneingang

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== CRM

* Die Symbole für die Prioritäten im Messenger wurden geändert. Statt der Sterne kannst du jetzt die Prioritäten von *Sehr hoch* bis *Sehr niedrig* vergeben.

[discrete]
=== plentyBI

* Die Begrenzung der Kennzahlen innerhalb einer einzelnen Komponenten wurde für auf 12 erhöht. Diese Änderung ist unabhängig von der verwendeten plentyBI Edition. Wenn die maximale Anzahl an Kennzahlen erreicht wurde, erscheint ein Tooltip beim Versuch eine neue Kennzahl in einer kombinierten Tabelle oder einem Diagramm zu verwenden.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Aufträge

* In einer Retoure war es unter Umständen nicht möglich, den Warenbestand für Paketbestandteile zurückzubuchen. Dies wurde behoben.
* Der Fokus des Eingabefelds beim Drücken der Eingabetaste wurde in der Filteransicht behoben.

'''

[discrete]
== Gelöscht

Folgende Funktionalität wurde in den letzten 7 Tagen auf *{version}* entfernt.

[discrete]
=== Fulfillment

* Die Versanddienstleister CBC Logistics/ParcelOne und NetDespatch wurden nicht verwendet und daher entfernt.

--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.



--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|
|
|

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

====
