= Changelog 11. Januar 2023
:author: kevin-stederoth
:sectnums!:
:page-index: false
:page-aliases: ROOT:changelog.adoc
:startWeekDate: 5. Januar 2023
:endWeekDate: 11. Januar 2023

// Ab diesem Eintrag weitermachen: LINK EINFÜGEN

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== CRM

* Wir haben im EmailBuilder 2 neue Schaltflächen hinzugefügt:
** eine Schaltfläche zum Migrieren aller Vorlagen
** eine Schaltfläche zum erneuten Erstellen der Standardvorlagen, falls ihr diese gelöscht habt.

+
In den alten E-Mail-Vorlagen-Einstellungen haben wir eine Schaltfläche hinzugefügt, mit der die gewählte Vorlage in den EmailBuilder migriert werden kann.
+
[IMPORTANT]
.To-Do
======
Wir haben die Migration verbessert. Die Migration könnt ihr jederzeit manuell anstoßen, indem ihr die oben genannten Schaltflächen anklickt.
Wenn ihr z.B. komplexe, verschachtelte if statements in euren Vorlagen verwendet habt, ist es nicht immer möglich, diese korrekt zu migrieren.

Prüft daher nach der Migration jede einzelne Vorlage. Um es einfacher und übersichtlicher für euch zu gestalten, haben wir diese Fehler in roter Schrift hervorgehoben.
======
* Im Bereich *Sprachabhängige Einstellungen* einer E-Mail-Vorlage im EmailBuilder wurden die Felder *Zahlenformat*, *Anzahl der Dezimalstellen*, *Datumsformat* und *Zeitformat* hinzugefügt. So kannst du nun für jede Sprache einstellen, wie die Variablenwerte in der E-Mail-Vorlage ausgegeben werden sollen. Die Einstellungen, die du dort vornimmst, finden dann Anwendung bei allen Variablen, die Zahlen, Datums- und Zeitformate ausgeben.
* Im Messenger ist das Wählen eines Tags in der Funktion *Minuten erfassen* nun auch Pflicht, wenn es sich um Freiminuten handelt.

[discrete]
=== Ereignisaktionen

* In den Ereignisaktionen wurden die folgenden Optionen zum Tag-Filter hinzugefügt:
** Aufträge ohne Tags
** Aufträge ohne diese Tags
** Aufträge mit mindestens einem dieser Tags

[discrete]
=== Prozesse

* n den Prozessen wurden die folgenden Optionen zum Tag-Filter hinzugefügt:
** Aufträge ohne Tags
** Aufträge ohne diese Tags
** Aufträge mit mindestens einem dieser Tags

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== CRM

* Weil die Zahlenformatierungen in den TWIG-Ausdrücken der Variablen nun nicht mehr benötigt werden, wurden diese auch entfernt. Beispiel:
** Alt: `{⁠{order.formattedGeneral.invoiceTotal | number_format(2, ',', '.')}⁠}`
** Neu: `{⁠{order.formattedGeneral.invoiceTotal}⁠}`
* Die Variable `Name des retournierten Artikels` im EmailBuilder wurde umbenannt in `Statusname des retournierten Artikels`.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Aufträge

* In der neuen Auftragsanlage wurde folgendes Verhalten behoben:
** Beim Erstellen einer Adresse im 1. Schritt wurden durch mehrfaches Klicken auf *Speichern* mehrere Adressen erstellt;
** Beim Einlösen von Gutscheinen wurde der Gutschein durch mehrfaches Klicken auf *Einlösen* mehrmals zum Auftrag hinzugefügt.
* In der Übersichtstabelle der neuen Aufträge-UI wurden die Anzahl der Ergebnisse pro Seite nicht gespeichert, wenn die Seite neu geladen wurde. Dieser Fehler wurde nun behoben.

[discrete]
=== CRM

* In der Übersicht der Schnellsuche wurde die Anzahl der Aufträge bei Gastbestellungen nicht angezeigt. Auch wenn man den Datensatz der Gastbestellung geöffnet hat, wurde die Anzahl der Aufträge nicht korrekt angezeigt. Dieses Verhalten wurde behoben.

[discrete]
=== Prozesse

* Beim Versuch, mehrere Dokumente über die Aktionen *Externe Rechnung* und *Externe Gutschrift* zu laden, konnte es dazu kommen, dass der Prozess hängen blieb. Dieses Verhalten wurde behoben.

'''

[discrete]
== Gelöscht

Folgende Funktionalität wurde in den letzten 7 Tagen auf *{version}* gelöscht.

[discrete]
=== CRM

* Die Variable *Gesamtrechnungsbetrag, durch Punkt getrennt* wurden aus dem EmailBuilder entfernt, weil diese nun nicht mehr benötigt wird.

--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.



--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|
|
|

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

====
