= Changelog 28. Juni 2023
:author: kevin-stederoth
:sectnums!:
:page-index: false
:page-aliases: ROOT:changelog.adoc
:startWeekDate: 22. Juni 2023
:endWeekDate: 28. Juni 2023

// Ab dem Eintrag nach diesem weitermachen: https://forum.plentymarkets.com/t/auftrag-ui-tracking-url-bei-mehreren-paketen-order-ui-tracking-url-for-multiple-packages/726671
// Auch folgenden Eintrag beachten: https://forum.plentymarkets.com/t/auftraege-validierung-von-tag-daten-orders-tag-data-validation/726464

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Artikel

* Du kannst in der neuen Artikel-UI jetzt nach der verknüpften Preiskalkulation filtern.

[discrete]
=== Aufträge

* Die Fußzeile der Auftrags-Detailansicht wurde erweitert um zwei neue Buttons:
** Bei einen Klick auf *Referenzierte Bestellungen*, wird ein neue Tab der Auftragssuche geöffnet / ausgeführt und als Filter werden die OrderIDs aller referenzierenden Bestellung gesetzt. Dies soll eine schnelle Möglichkeit bieten alle zusammenhängen Aufträge zu finden.
** Bei einen Klick auf *Kundenaufträge*, wird ein neue Tab der Auftragssuche geöffnet / ausgeführt und der Filter KontaktID automatisch gesetzt. Dies soll eine schnelle Möglichkeit bieten alle Aufträge des Kontaktes zu finden.
* *Markierung* wurde als Filter und Feld (Kompakt und Tabellenansicht) hinzugefügt.

[discrete]
=== Dokumente

* Die Übersicht in der Nummernkreis-UI wurde um eine optionale Spalte *Mandant: Standort* erweitert, die ihr einblenden könnt um für die Standorte auch die entsprechenden Mandanten direkt in der Übersicht sehen zu können.
* In der Einstellung für den Präfix steht euch nun auch eine Variable für ein zweistelliges Jahr zur Verfügung (`$yearShort`).
* Es wurden zusätzliche Tooltips an einigen Stellen hinzugefügt und erweitert.

[discrete]
=== Fulfillment

Für die Auftrags-UI steht nun das Pakete-Widget zur Verfügung. In der Detailansicht eines Auftrags kann über die myView die Position bestimmt werden.

Mit dem Widget wird die Funktionalität zu Versandpaketen aus dem Versand-Center bereitgestellt, so dass mit einen Klick in die Reihe ein Overlay geöffnet wird indem die Paketdaten angepasst werden können wie z.B. das Hinterlegen einer Paketnummer.

Weitere Pakete zu erstellen ist über das material:add[] möglich. Mit einem Klick auf die PaketId, wird die Paketinhaltsliste geöffnet, möchtet ihr die Sendungsverfolgung öffnen, funktioniert dies mit einem Klick auf eine hinterlegte Paketnummer.

Wie in allen neueren UIs, lassen sich die Spalten ein- oder ausblenden und in der Reihenfolge verschieben.

[discrete]
=== Kataloge

* Im Menü *Daten » Katalog* steht dir ab sofort der Format-Typ *Kontakt (Testphase)* zur Verfügung. Bitte beachten: Dieser Format-Typ befindet sich in der Testphase, weil noch nicht alle Felder aus dem FormatDesigner in den Katalog überführt wurden.

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Aufträge

* In der AuftragsUI bei der Übersicht oder Detailansicht, wurde beim Klick auf die Tracking-Nummer immer nur der URL für die erste Nummer in einen neuen Browserfenster geändert. Dies wurde nun angepasst, wenn beim Versanddienstleister, die Option *URLs splitten* aktive ist öffnet sich für jede Paketnummer ein eigenes Browserfenster.

[discrete]
=== CRM

* Das Tag *Testphase* wurde am Menüpunkt *CRM » Messenger* entfernt. In diesem Zuge wurde am Menüpunkt *CRM » Ticketsystem* das Tag *Veraltet* hinzugefügt.

[discrete]
=== OTTO Market

* Die Intervalle der Cache-Generierung für OTTO Market Kataloge wurden angepasst. Anstatt jede Stunde werden Caches nur noch zwischen 7:00 und 23:00 im Intervall von 2h und zwischen 0:00 und 1:00 im Intervall von 20min aktualisiert. Die Intervalle sind mögliche Startzeitpunkte, es kann jedoch zu Verzögerungen kommen. Durch diese Änderung werden redundante Generierungen reduziert.

[discrete]
=== plentyShop

* Die Benutzer:innenoberflächen der folgenden plentyShop Menüs wurde überarbeitet, um sie besser für geführte Touren nutzbar zu machen:
** *Einrichtung » Mandant » [Mandanten wählen] » Einstellungen*
** *Einrichtung » Mandant » [Mandanten wählen] » Webshop » Multilingual*
** *Einrichtung » Mandant » [Mandanten wählen] » Webshop » Shop sperren*
** *Einrichtung » Mandant » [Mandanten wählen] » Webshop » Rechtliches*

[discrete]
=== Zalando

* Die E-Mail sowie die externe Nummer des Kunden werden ab sofort zusätzlich zur Rechnungsadresse auch an der Lieferadresse hinterlegt.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Aufträge

* In der neuen Auftrags-UI wurde beim Entfernen des Datumsfilterchips in der Übersichtstabelle der Filter immer noch mit der Suchanfrage gesendet. Dies wurde behoben.
* In der Kompaktansicht, wurde bei den dargestellten Rechnungsbetrag nicht die Summe der Gutscheine herausgerechnet. Dieses Verhalten wurde behoben.
* In der Detailansicht in der neuen AuftragsUI, wurde das Element für das Warenausgangsdatum verschoben zu anderen Elementen dargestellt. Dieses Verhalten wurde behoben.
* In der Ansicht zum Splitten des Auftrags wurde in der Spalte *verfügbaren Bestand* nicht der korrekte Warenbestand dargestellt. Dieses Verhalten wurde behoben.
* Bei der Erstellung eines neuen Auftrags, wurde bei den Filtern Hersteller der Artikelsuche, immer nur die ersten 50 dargestellt. Dieses Verhalten wurde behoben.
* In der Auftrags-UI gingen bei der Bearbeitung von Auftragspositionen die nicht gespeicherten Änderungen nach dem Wechsel der Ansicht verloren. Dies wurde behoben.
* In der Auftrags-UI verschwanden während der Bearbeitung der Bestellpositionen die gültigen Preise nach dem Wechsel der Ansicht. Dies wurde behoben.
* Wenn über die Übersicht Notizen bearbeitet wurden, wurde die Anzahl der Notizen nicht aktualisiert. Dies wurde behoben.
* Wenn an mehreren Positionen hintereinander die Menge geändert wurde, konnte es dazu kommen, dass Änderungen nicht übernommen wurden. Dies wurde behoben.

[discrete]
=== CRM

* Die EmailBuilder-Variable für das Datum des Auftragseingang wurde nicht ausgegeben. Dieses Verhalten wurde nun behoben.

[discrete]
=== Dokumente

* In der Nummernkreis-UI wurden folgende Fehler behoben:
** Variable `$plentyID` wurde nicht ersetzt
** Validierung des Präfix zeigt Fehler an, obwohl alles korrekt ist
** Mandant des Standortes ist nicht erkennbar
** Bei Wechseln zwischen mehreren Nummerkreisen werden Werte von vorherigen angezeigt
** Filter in der Suche funktionieren nicht in bestimmten Kombinationen
** Variablen `$yearMonthDay` und `$yearMonth` werden nicht korrekt in der Vorschau angezeigt
** Variablen `$yearMonthDay` und `$year` sind vertauscht
** In der Auswahl stehen nicht alle Herkünfte zur Verfügung
** Zuletzt generierte Nummer passt nicht für die aktuellen Änderungen im Nummernkreis
* Bei der Verwendung des DocumentBuilder konnte es dazu kommen das Templates für bestimmt Dokumenttypen nicht gefunden wurden, obwohl diese definiert waren (zB. Nachbestellungsdokument). Dies wurde behoben.
* Es konnte dazu kommen das die DocumentBuilder-UI sich machmal nicht öffnen ließ, dies trat bei Systemen mit vielen Kontakten auf und wurde behoben.

[discrete]
=== Fulfillment

* Nach der Anmeldung einer Exportsendung mit DHL *Warenpost International* war das Icon für Exportdokumente aktiv, aber es zeigte nach einem Klick nur ein leeres PDF an. Wenn Exportangaben notwendig sind, befinden sich diese jedoch auf dem Versandlabel direkt (CN22).
+
Weitere Exportdokumente wurden in dem Fall von DHL erstellt oder an uns gesendet, daher wird das Exportdokument-Icon nun ausgegraut, wenn für eine Exportlieferung keine Exportdokumente verfügbar sind.

--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Aufträge

* Bei der Artikelsuche beim Erstellen eines neuen Auftrags oder bei dem editieren von Auftragsposition in der OrderUI, wurde die Spalte *Menge im Zulauf* hinzugefügt.
* Bei der Erstellung von Kindaufträgen wird nun der Variantenname angezeigt.
* In der neuen Auftrags-UI wurden für die Erstellung von Nachbestellungen folgenden Änderungen vorgenommen:
** Es wurden zwei neue Spalten *Reservierter Bestand* und *Zulauf* bei der Erstellung von einer Nachbestellung aus dem Auftrag hinzugefügt.
** Es wurde ein neuer Button im Overlay *Warenbestand ermitteln* in der Auftragsübersicht hinzugefügt. Über diesen Button wird man direkt in die UI zum Erstellung einer Nachbestellung für diesen Auftrag weitergeleitet, und der entsprechende Artikel ist vorausgewählt.
* Eigene Auftragspositionseigenschaften, die z.B. per Rest oder Plugin erstellt wurden, lassen sich nun in den Artikelpositionen der Auftrags UI / Auftragserstellung / Abonnement-UI darstellen. Diese werden in der zweiten Ebene unterhalb der Auftragspositionen neben den Bestelleigenschaften dargestellt und können in der Bearbeitungsansicht der Auftragsposition geändert werden.
* Es wurden in die Tabelle für die Auftragspositionen neue Spalten für Gewicht, Länge und Breite hinzugefügt.

[discrete]
=== Fulfillment

* Nachdem eine Retourensendung angemeldet wurde, wird nun eine Auftragsnotiz erstellt, die den Retourenversanddienstleiter und die Sendungsnummer festhält.

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Ereignisaktionen

* Ab sofort wird folgendes Recht benötigt, um Tags zu laden: *Einrichtung > Einstellungen > Tags Betrachten*

[discrete]
=== OTTO Market

Die Anbindung der OTTO Market API-Endpunkte für Belege wurde auf Version 3 aktualisiert, da die Version 2 in Kürze abgeschaltet wird.

[NOTE]
.Kein To-Do
======
Da dies eine Änderung im Hintergrund ist, besteht kein To Do für Händler:innen.
======

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== CRM

* In der Auftragstabelle am Kontakt wurde in der Spalte *Zahlungsarten* kein Wert angegeben.
Dieser Fehler wurde nun behoben.

[discrete]
=== Ereignisaktionen

* Es gab in den Ereignisaktionen das Problem, dass nach dem Ändern des Namens eines Tags, immer noch der alte Name angezeigt wurde. Dieses Verhalten wurde behoben. Des Weiteren wird nun auch die korrekte Farbe des Tags angezeigt.

[discrete]
=== Rechteverwaltung

* Beim Setzen von Rechten im einfachen Modus konnte es sein, dass die dazugehörenden Rechte im erweiterten Modus nicht automatisch ausgewählt wurden. Dieses Verhalten ist nun gefixt.

'''

[discrete]
== Gelöscht

Folgende Funktionalität wurde in den letzten 7 Tagen auf *{version}* gelöscht.

[discrete]
=== Aufträge

* Es ist nicht mehr möglich, Auftragsnotizen zu bearbeiten.

--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|link:https://marketplace.plentymarkets.com/cytautomaticcrossselling_7016[Automatisiertes Crossselling - Wird oft gekauft mit...^]
|1.2.2
|-

|link:https://marketplace.plentymarkets.com/conradextension_6948[Conrad^]
|1.3.1
|-

|link:https://marketplace.plentymarkets.com/hermesshippinginterface_5437[Hermes^]
|1.0.25
|-

|link:https://marketplace.plentymarkets.com/mirakl_6917[Mirakl Connector^]
|1.4.1
|-

|link:https://marketplace.plentymarkets.com/mediamarkt_6918[Mediamarkt^]
|1.1.2
|-

|link:https://marketplace.plentymarkets.com/voelknerextension_6949[Voelkner^]
|1.3.1
|-

|link:https://marketplace.plentymarkets.com/cytitemavailabilitynotification_6906[Wieder auf Lager! - Verfügbarkeitsbenachrichtigung mit Statistik^]
|1.6.4
|-

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

POS-App::
+
--

[discrete]
=== Neu

Folgende Funktionalität wurde in Version 1.12.5 der *plentymarkets Warehouse App* hinzugefügt.

* In plentyPOS kannst du ab sofort zusätzliche Artikelinfomationen, wie z.B. Einkaufspreise oder Netto-Warenbestand, in der Kassieransicht anzeigen und auf Wunsch ausblenden. Zuvor musst du im Einstellungsmenü der Kasse (*Einrichtung » POS » [Mandant öffnen] » [Kasse öffnen] » Tab: Grundeinstellungen*) festlegen, welche Informationen angezeigt werden sollen. +
*_Hinweis:_* Informationen zu Attributen wurden bereits zuvor angezeigt und sind weiterhin standardmäßig für die Anzeige aktiviert.
+
Weitere Informationen findest du auf der Handbuchseite xref:pos:pos-einrichten.adoc[plentyPOS einrichten].

[discrete]
=== Behoben

Folgende Probleme wurden in Version 1.12.5 der *plentymarkets Warehouse App* behoben.

* In machen Fällen konnte es vorkommen, dass die Schaltfläche *Erstattung durch Gutschein* in der Retoure fälschlicherweise nicht aktiv war, sodass keine Erstattung in Form von Gutscheinen angelegt werden konnte. Dieses Verhalten wurde behoben.

--

====
