= Changelog 26. Juli 2023
:author: kevin-stederoth
:sectnums!:
:page-index: false
:startWeekDate: 20. Juli 2023
:endWeekDate: 26. Juli 2023

// Ab diesem Eintrag weitermachen: https://forum.plentymarkets.com/t/new-order-ui-order-item-properties-sort-and-expand-fixes-neue-auftrags-ui-fehlerbehebungen-fuer-die-eigenschaften-der-auftragspositionen-betreffend-sortierung-und-ausklappen/730406

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Artikel (Neue UI)

* Spaltenbreite anpassbar in folgenden UIs:
** Artikelübersicht
** Variantenübersicht
** Paketbestandteile hinzufügen
** Setbestandteile hinzufügen
** Cross-selling hinzufügen

[discrete]
=== Aufträge

* In der Auftrags-UIs sind die Spalten in der Verlaufstabelle jetzt in der Größe veränderbar.
* Der Transfer-Lagerort wurde als optionales Element in den MyView-Bereich *Allgemein* der Auftragsdetailansicht hinzugefügt.

[discrete]
=== CRM

* Im Firmendatensatz im Menü *CRM » Firma* haben wir das Portlet *Aufträge* hinzugefügt. Das Portlet zeigt die Aufträge von allen Kontakten, die mit dieser Firma verknüpft sind.
+
Die Option zum Hinzufügen eines neuen Auftrags wurde entfernt und es wurden zwei neue Spalten (Kontakt-ID und Kontaktname) in der Übersicht hinzugefügt. Beim Klick auf die Kontakt-ID wird man zum Kontaktdatensatz im Menü *CRM » Kontakte* weitergeleitet.
* Im Messenger kannst du ab sofort Textblöcke verwenden. Erstelle und Verwalte deine Textblöcke im Menü *CRM » Textblöcke / FAQ*. Du kannst auch bereits erstellte FAQ-Einträge aus dem Ticketsystem im Messenger verwenden.
* Im Messenger hast du jetzt die Möglichkeit Konversationen zu archivieren. Weitere Informationen findest du link:https://forum.plentymarkets.com/t/messenger-konversationen-archivieren-messenger-archive-conversations/730396/2[in der Kurzanleitung].

[discrete]
=== Dokumente

* In den Ausgabeeinstellungen des DocumentBuilder kann nun für jede Vorlage eingestellt werden ob als Währungsformat der ISO-Code (EUR, USD) oder das Symbol ($, €) verwendet werden soll.
* Im DocumentBuilder können auf *Auftragsebene* nun zusätzlich folgende Variablen genutzt werden:
** Externe Quellauftrags-ID (Auftragseigenschaft mit der Typ-ID `62`)
* Im DocumentBuilder können für *Artikelpositionen* nun zusätzlich folgende Variablen genutzt werden:
** Seriennummer
** Model
** Herstellerland
** Artikelvorschautext

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== CRM

* Das Limit für den Mindestbestellwert bei Firmen wurde auf 999999999,99 angehoben.
* Die Assistenten *E-Mail-Konten* und *Messenger-Konfiguration* wurden verschoben:
** Die *E-Mail-Konten* findest du ab sofort unter *Einrichtung » Mandant » Global » E-Mail-Konten*.
** Die *Messenger-Konfiguration* findest du unter *Einrichtung » CRM » Messenger » Posteingänge*.

[discrete]
=== plentyShop

* Im plentyShop LTS wurden herstellerbezogene Daten ausgegeben, die nicht über die `ResultFields` eingeschränkt wurden. Das Verhalten wurde geändert und die `ResultFields` werden jetzt korrekt berücksichtigt.
+
[IMPORTANT]
.To-Do
======
Kunden mit Theme oder individuellen Code Widgets, müssen ggf. benötigte `ResultFields` nachpflegen.
======

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Artikel (Neue UI)

* Tritt ein Fehler bei der Gruppenfunktion in der neuen Artikel-UI auf, friert das Fenster dazu nicht mehr ein.
* In manchen Tabellen hat das Hinzufügen von Markierungen dafür gesorgt, dass die Tabelle nicht richtig geladen wurden. Dieses Problem haben wir behoben.
* Wenn man nach dem ersten Artikel einen weiteren im gleichen Durchlauf erstellen wollte, hat das trotz Erfolgsmeldung nicht funktioniert. Außerdem gab es keine Fehlermeldung, wenn eine Variante mit gleicher Variantennummer angelegt werden sollte. Beide Fehlverhalten haben wir korrigiert.
* Wurden Artikelbilder in der neuen Artikel-UI mit Varianten verknüpft, konnte es vorkommen, dass es dabei zu einem Fehler kam.

[discrete]
=== Aufträge

* In der neuen Auftrags-UI wurden für den Filter *Auftragstyp*, der in den Filtern der Auftragsübersichtstabelle verfügbar ist, die Optionen *Teilweise Lieferung* und *Multi-Lieferung* entfernt.
* Fehler behoben, dass die PDF Vorschau im Safari Browser nicht funktioniert.
* Das Notizen-Widget in den Auftragsdetails wurde angepasst, dass der Text nicht mehr abgeschnitten ist.
* Styling für die Felder *Markierung* und *Mahnstufe* im Kompaktmodus angepasst
* In der Nachbestellung bei den Verkaufspreisen können jetzt 4 Nachkommastellen verwendet werden.
* In der neuen Auftrags-UI war es nicht möglich den Mandant bei einen Sammelauftrag zu ändern. Dies wurde nun behoben.
* In der Rückbuchungsansicht für den Bestand, wurde unter Artikel-ID die ID der Auftragsposition angezeigt. Dies wurde nun behoben.
* Fehler behoben, dass die Versandkosten nicht geändert werden konnten, falls diese nicht als Auftragsposition existiert haben.
* Die folgenden Fehlerbehebungen wurden in der Warenkorb-Tabelle vorgenommen:
** Die Eigenschaften wurden nicht korrekt gespeichert, wenn mehrere Auftragspositionen bearbeitet wurden. Dies wurde behoben.
** Beim Löschen eine Auftragsposition waren die Eigenschaften des Artikels weiterhin verfügbar, wenn derselbe Artikel in den Warenkorb gelegt wurde. Dies wurde behoben.
** Beim Hinzufügen einer Eigenschaft, um sie zu bearbeiten, war der Wert immer noch zur Auswahl verfügbar. Dieses Problem wurde behoben.

+
Die Korrekturen sind sowohl für die neue Benutzeroberfläche zum Erstellen von Aufträgen als auch für die neue Benutzeroberfläche für Aufträge verfügbar.
* In einem bestimmten Fall konnte der Tab *Aufträge* nicht geschlossen werden. Dies ist nun behoben.
* In der Detailansicht der neuen Auftrags UI und in der neuen Auftragsanlage standen unter Umständen zu viele Kombinationen von Versandprofilen zur Auswahl. Dies wurde behoben.
* Während der Bearbeitung von Auftragspositionen in der neuen Auftrags-UI wurde die Vorschau-Route ohne Grund mehrfach ausgeführt und die UI war bei Aufträgen mit vielen Positionen langsam. Dies wurde nun behoben.

[discrete]
=== Prozesse

* In den Prozessen ist es vorgekommen das die Wagenkennung nach dem vollständigen erfassen und Abschliessen der Pickliste über die Aktion *Artikelerfassung* nicht von der Pickliste getrennt wurde. Diese Situation ist meist im Parallelbetrieb der Prozesse und plentyWarehouse App vorgekommen.
Dieser Fehler wurde behoben.

'''

[discrete]
== Gelöscht

Folgende Funktionalität wurde in den letzten 7 Tagen auf *{version}* gelöscht.

[discrete]
=== CRM

* Die Assistenten *Basics* und *Kontaktdatenimport* wurden aus dem Menü *Einrichtung » Assistenten » Grundeinrichtung* entfernt. Die Einstellungen, die im Assistenten *Basics* vorgenommen werden konnten, kannst du in den folgenden Menüs vornehmen:
** *Einrichtung » Einstellungen » Stammdaten*
** *Einrichtung » Einstellungen » Bankdaten*
** *Einrichtung » Kontoverwaltung » Konten*

+
Den Kontaktdatenimport bereitest du im Menü *Daten » Import* im Import-Typ *Kontakte, Firmen und Adressen* vor.

--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Aufträge

* In der Detailansicht der neuen Auftrag UI ist jetzt das Feld für die externe Auftrags-ID bei Retouren verfügbar.
* Das Feld *Status* kann nun angeklickt werden, um den Status direkt zu ändern.
* Bestimmte Felder in der Kompaktansicht haben jetzt die Option *Anzeigen in Kopfzeile* um Felder in der Kopfzeile (ähnlich wie in der alten UI) anzuzeigen. Diese Einstellung ist für folgende Felder verfügbar:
** Status
** Lieferland
** Zahlungsmethode
** Währung
** Rechnungsbetrag
** USt.
** Zahlungsstatus
** Mahnstufe
** Versandprofil
** Warenausgangsdatum

[discrete]
=== CRM

* Wir haben dem Messenger die folgenden Gruppenfunktionen hinzufügt:
** zu einem Ordner Hinzufügen
** aus einem Ordner entfernen
* Die Variable für die Bestellmerkmale wurde für den EmailBuilder hinzugefügt.
Wir haben dem Messenger die folgenden Aktionen für die Ereignisaktion hinzufügt. Du findest diese unter *CRM » Messenger » Einstellungen » Automatisierung*.
** Konversation löschen
** Konversation archivieren

[discrete]
=== Dokumente

* Das Dokumenten-Widget in der Auftrags-UI wurde für den DocumentBuilder optimiert, sodass hier nun der aktuelle Status des Dokumentes angezeigt wird. Somit werden nun auch Dokumente sichtbar/angezeigt, die sich aktuell noch in Bearbeitung befinden oder bei denen es bei der Erstellung zu einem Fehler kam.

[discrete]
=== MyView

Ab sofort hast du in jeder MyView-Benutzeroberfläche die Möglichkeit, eine bestehende MyView-Ansicht zu importieren oder zu exportieren. Die Schaltflächen dafür befinden sich neben der Auswahl der Ansichten.

Du kannst nur Ansichten in eine Benutzeroberfläche importieren, die auch für diese gedacht sind, also zum Beispiel eine Dashboard-Anischt in dein Dashboard importieren. Dieselbe Ansicht lässt sich allerdings nicht in die Benutzeroberfläche von Order oder Item importieren.

Für das Importieren von Ansichten braucht Benutzer:innen-Konto folgendes Recht:
*Ansichten » Erstellen*

[discrete]
=== plentyShop

* Es wurde eine neue Benutzerrecht-Kategorie hinzugefügt: *CMS » PWA » Bereitstellen*.

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Aufträge

* Die Komponente zur Auswahl des Status in den Auftragsdetails wurde angepasst und hat nun den Fokus direkt auf dem ausgewählten Status, d.h. kein unnötiges Scrollen mehr beim Ändern des Status.

[discrete]
=== plentyShop

* Die Benutzerrecht-Kategorie *CMS » Neuer Webshop* wurde umbenannt in *CMS » Webshop*.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Aufträge

* Die neuen Einstellungen für die Felder in der Kompaktansicht wurden in alten Ansichten nicht angezeigt.

[discrete]
=== CRM

* Bei der Migration von alten E-Mail-Vorlagen in den EmailBuilder kam es zu einem Fehler, sodass in einigen Fällen Sprachen gefehlt haben. Dieser Fehler wurde nun behoben.

[discrete]
=== MyView

* Durch einen Fehler in der Zuordnung von MyViews konnte es passieren, dass beim Wechsel zwischen verschiedenen Ansichten (bspw. Wechsel von Order compact UI auf Order detailview) nicht die korrekten MyView-Sets zur Auswahl angezeigt wurden. Dieses Verhalten ist nun gefixt.

'''

[discrete]
== Gelöscht

Folgende Funktionalität wurde in den letzten 7 Tagen auf *{version}* gelöscht.

[discrete]
=== Amazon

* Der temporäre Prozess link:https://forum.plentymarkets.com/t/717722[zur Identifizierung unvollständiger FBA-Aufträge], zusammenhängende Berichte und Oberflächen werden jetzt wieder entfernt, da diese nicht mehr benötigt werden.

--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|link:https://marketplace.plentymarkets.com/uniservaddresscleansing_6869[Adressprüfung und Adresskorrektur mit Uniserv^]
|2.0.19
|-

|link:https://marketplace.plentymarkets.com/mollie_6272[Mollie^]
|2.8.28
|-

|link:https://marketplace.plentymarkets.com/paypal_4690[PayPal Checkout^]
|6.3.5
|-

|link:https://marketplace.plentymarkets.com/uptain_55274[uptain® Conversion Optimierung mit Popups und Abbrecher-Mails^]
|1.0.4
|-

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

====
