= Changelog 9. August 2023
:author: kevin-stederoth
:sectnums!:
:page-index: false
:page-aliases: ROOT:changelog.adoc
:startWeekDate: 3. August 2023
:endWeekDate: 9. August 2023

// Ab diesem Eintrag weitermachen: LINK EINFÜGEN

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Artikel (Neue UI)

* Die Spaltenbreite in den restlichen Tabellen der neuen Artikel UI ist jetzt konfigurierbar. Für neue User muss sie eventuell einmalig eingestellt werden, wie gewünscht.

[discrete]
=== Aufträge

* Das Versenden von E-Mails steht in der neuen Auftrags-UI jetzt auch als Menüfunktion zur Verfügung.

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Artikel (Neue UI)

* Der CrossSelling-Typ *Konfigurator* wurde ausgeblendet. Er wurde unbeabsichtigt in der neuen Artikel-UI angezeigt.

[discrete]
=== CRM

* Im Messenger wurden folgende Änderungen vorgenommen:
** *Meine Ordner* ist nun immer sichtbar
** Die Schaltfläche *Neuen Ordner hinzufügen* befindet sich nun im Kontext-Menü von *Meine Ordner*
** *Angeheftete Konversationen* ist nun immer sichtbar
** Die Icons für *Meine Ordner*, *Angeheftete Konversationen* und *Konversation lösen* wurden geändert
** Das Laden von angehefteten Konversationen wurde verbessert

[discrete]
=== Dokumente

* Dokumenttypen die für die Erstellung im DocumentBuilder aktiviert sind können nicht mehr über die UI unter *Aufträge » Fulfillment* generiert werden. Für die betroffenen Dokumenttypen wird hier nun ein Hinweis angezeigt und die Aktion zum Erstellen ist nicht mehr vorhanden.
+
Die Erstellung von Dokumenten für eine Liste von Aufträgen ist über eine Gruppenfunktion in der Auftrags-UI weiterhin möglich. Eine Gruppenfunktion um Dokumente zu einem PDF zusammenzuführen wird in naher Zukunft folgen um hier den gleichen Funktionsumfang sicherzustellen.

[discrete]
=== Netto

Der Katalog von Netto wurde um folgende Funktionen und Felder erweitert:

. Separate kanalspezifische Felder für Netto und Marktkauf:
** Preis
** Provision
** Lieferzeit
** Grundpreis: Verkaufspreis
** Grundpreis: Einheit
** Grundpreis: Menge
** Alter Preis
** Kategorien
. Neue Steuerklasse: 0% (Solarprodukte)
. Neue Felder für EAR-Bestimmungen:
** WEEE_Pflicht
** EAR_Kategorie
** EAR_Marke
** WEEE_Nummer
. Asynchroner Bilderupload: Der Upload der Bilder auf den SFTP in einen Microservice ausgelagert. Dadurch schlägt sich der zeitintensive Upload nicht mehr den täglichen Cron-Prozess nieder und findet nachgelagert zur Übertragung der Produktdatei statt.

Der Nutzung des Katalogs steht damit nichts mehr im Wege.

[IMPORTANT]
.To-Do
======
Um den Katalog zu nutzen, muss man mindestens einen Katalog anlegen, mappen, aktivieren und kann dann unter *Einrichtung » Märkte » Netto eStores » Tab: Einstellungen* über die Optionen *Artikelexport aktivieren* und *Bestandsabgleich aktivieren* und den neuen Auswahlwert *Ja (Katalog)* diese separat umstellen.
======

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Aufträge

* Die folgenden Korrekturen wurden zur Tabelle der Auftragspositionen und zur Tabelle des Warenkorbs hinzugefügt:
** Die Eigenschaften der Bestellpositionen wurden in der Artikeltabelle und in der Tabelle des Warenkorbs auf der Grundlage der Speicherreihenfolge sortiert. Dies wurde behoben.
** Die Eigenschaften der Auftragspositionen konnten im dritten Schritt der Benutzeroberfläche zum Anlegen eines neuen Auftrags nicht aufgeklappt werden. Dies wurde behoben.

+
Die Korrekturen sind sowohl für die neue Benutzeroberfläche zum Anlegen von Aufträgen als auch für die neue Benutzeroberfläche für Aufträge verfügbar.
* Beim Zurücksetzen des Warenausgangs über die neue Auftrags UI wurde der Benutzer nicht in den Warenbewegungen der Variante angezeigt. Dies wurde behoben.
* In der neuen Auftrags-UI erlaubt die Datumsauswahl bei der Dokumentenerstellung nicht die Eingabe des richtigen Formats für die Lokalisierung. Dies wurde behoben.
* In der Benutzeroberfläche für das Anlegen neuer Aufträge und in der Benutzeroberfläche für das Bearbeiten von Auftragspositionen wurde bei schnellen Änderungen der Artikelmenge mehrerer Artikel die Menge manchmal durch den im Hintergrund ausgeführten Preview-Aufruf zurückgesetzt. Dies wurde behoben und die bearbeitbaren Felder sind nun deaktiviert, während des Aufrufs der Auftragsvorschau.
* Wenn in der neuen Auftrags-UI versucht wird einen Unterauftrag in einem duplizierten Auftrags-Tab zu erstellen, wurde die Erstellung des Kinderauftrags im ersten Auftrags-Tab durchgeführt und nicht in dem, in dem der Prozess gestartet wurde. Dies wurde behoben.
* Wenn man in der neuen Auftrags-UI vom Dashboard zur Auftragsübersicht navigiert und von der Kompaktansicht zur Listenansicht wechselt, erscheint eine weiße Seite. Dies wurde behoben.
* In der neuen Benutzeroberfläche für Aufträge gingen beim Wechsel zwischen der Kompaktansicht und der Listenansicht die Suchparameter verloren. Dies wurde behoben.
* In der neuen Auftrags-UI bekommen Bundleartikel nicht die richtigen Preise und Mehrwertsteuer, wenn die Einstellung *Bundlespositionen im Bestellprozess durch die Basisartikel ersetzen* aktiviert ist. Dies wurde behoben.
* Es kam zu einem Fehler wenn kein Einkaufspreis gesetzt ist. Dieses Verhalten wurde behoben.
* In der neuen Auftrags-UI können die Bookmarks für einen Datumsfilter mit dem Operator *zwischen* jetzt wieder gespeichert werden.
* Das Zahlungs-Widget wird in der neuen Auftrags-UI jetzt auch für Sammelaufträge in den Auftragsdetails angezeigt.
* Verschiedene Buttons, wie z.B. der Button zum Kopieren von Aufträgen, wurden so angepasst, dass bei mehrfachem Drücken keine doppelten Auftäge erzeugt werden.
* Datumsfilter funktioniert nun wieder nachdem man beispielsweise von einer anderen UI wie dem Dashboard zur Auftragsübersicht weitergeleitet wurde.

[discrete]
=== CRM

* Beim Einrichten des E-Mail-Kontos ist es nun auch erlaubt, im Feld für den Namen des Absenders Sonderzeichen zu verwenden.

--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.



--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|
|
|

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

====
