= Changelog 20. September 2023
:author: kevin-stederoth
:sectnums!:
:page-index: false
:page-aliases: ROOT:changelog.adoc
:startWeekDate: 14. September 2023
:endWeekDate: 20. September 2023

// Ab diesem Eintrag weitermachen: LINK EINFÜGEN

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Aufträge

* Du kannst ab jetzt den Operator *Zeitraum* für jeden Datumsfilter in der Auftragsübersicht verwenden.
Es stehen die Optionen *Heute*, *Gestern*, *Letzte 7 Tage* und *Letzte 30 Tage* zur Verfügung.
* Die Auftrags-UI zeigt jetzt eine Warnung nach dem Speichern an, wenn der Status sich nicht aktualisiert hat. Beispielsweise wenn der Warenausgang gebucht wurde und der Status zurück geändert werden sollte.
* In den Detailansicht der Auftrags-UI wurde den Elementen Notizen, Dokumente und Auftragshistorie eine maximale Höhe von 30% der Bildschirmhöhe gegeben. Wenn der Inhalt zu groß ist, wird eine Scollbalken angezeigt und der Inhalt kann gescrollt werden.
* In der Auftrag UI wird nun die Einstellung für das Format von Gewichten (*Einrichtung » Einstellungen » Zahlenformate*) beachtet.
* In den Bearbeitungsansicht der Auftragsposition in der Auftrag-UI ist es nun möglich, die Variante zu ändern, ohne sie vorher zu lösen und danach neu zu zuweisen.
* In der Auftrag UI wurde der Button *Kaufabwicklung* für Gutschriften hinzugefügt.

[discrete]
=== CRM

* In den sprachabhängigen Einstellungen des EmailBuilder gibt es jetzt einen Upload-Button, mit dem du statische Anhänge direkt von deinem Computer hochladen kannst.

[discrete]
=== Dokumente

* Es stehen zwei neue Einstellungen für das Auftragspositionen-Widget:
** *Tabellenüberschrift auf Folgeseiten wiederholen*: Wird diese Checkbox gesetzt, so wiederholt sich die Tabellenüberschrift der Artikeltabelle auf jeder neuen Seite. Standard: keine Wiederholung der Tabellenüberschrift.
** *Unterbinde Seitenumbruch in Tabellenzeilen*: Wird diese Checkbox gesetzt, werden Tabellenzeilen nicht auf zwei Seiten geteilt, wenn der Platz auf einer Seite nicht für die volle Zeile reicht, sondern komplett auf der neuen Seite ausgegeben. Standard: Zeile wird geteilt.
* Für die Einstellung *Dateiname* der DocumentBuilder Vorlagen steht nun die Variable `$orderId` zur Verfügung.

[discrete]
=== Prozesse

* In der Aktion *Artikelerfassung* konnte es dazu kommen, dass die Tabelle in der Detailansicht eines Auftrags zu gross geworden ist und man Felder nur durch Scrollen lesen konnte. Wir haben die Möglichkeit geschaffen, dass Tabellenfelder der Detailansicht jetzt verschoben werden können.
+
Möglicherweise muss bei manchen Benutzern nach der Verteilung die Auftrags-Detailansicht in der Artikelerfassung einmalig neu eingestellt werden.

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Artikel (Neue UI)

* Die Standardsortierung der Artikelübersicht in der neuen Artikel-UI findet nun nach Artikel-ID absteigend statt. So sieht man den neuesten angelegten Artikel immer ganz oben.
* Der Filter nach Verkaufskanälen zeigt nur noch tatsächlich sichtbar geschaltete Marktplätze zur Auswahl an.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Aufträge

* Die Gruppenfunktion *Rabatt* in der Auftragspositionen bearbeiten Ansicht erlaubt es nun, den Rabatt auf 0 zu setzen.
* Bei der Auftragserstellung konnte es dazu kommen, dass man nicht zum letzten Schritt springen konnte, obwohl die Verkaufspreise schon aktualisiert wurden, dies wurde behoben.
* Beim Löschen von Sammelaufträgen und Sammelgutschriften in der Detailansicht der Auftrag UI kam es zu einem Fehler. Dies wurde behoben.
* In der Auftrag UI konnte es beim Bearbeiten von Adressen zu dem Fehler `order.orderUI.details.addresses.addressFormIsInvalid` kommen. Dies wurde behoben.
* Wenn aus einem Auftrag heraus eine Nachbestellung angelegt wurde, konnten die Attribute in der Nachbestellung nicht angezeigt werden. Dies ist nun behoben.
* In der Auftrag UI kam es bei Reparaturen beim Zuweisen und Lösen von Varianten zu einem Fehler. Dies wurde behoben.
* Wenn eine Auswahleigenschaft keinen Namen hat, wird der Name der Auswahl als Eigenschaftsname im Dialogfeld „Eigenschaften der Auftragsposition bearbeiten“ verwendet. Dies wurde behoben und ein Fallback wurde hinzugefügt, um den ersten Namen für ein solches Szenario zu erhalten.
* In der UI für die Bearbeitung von Auftragspositionen verhindert der Mechanismus für gültige Verkaufspreise das Speichern der Auftragspositionen, wenn einem Artikel keine Variante zugeordnet ist. Dies wurde behoben.
* Wenn ein Dokument von der Übersichts-UI aus erstellt wird, wird die Scrollposition zurückgesetzt, da die Auftragssuche durchgeführt wird. Dies wurde behoben.
* Der Zahlungsstatus in Prozent wurde auch bei den Auftragstypen Angebot, Lieferauftrag, Retoure, erweiterte Aufträge und Teillieferung angezeigt. Dies wurde behoben.
* Wenn in der neuen Auftrags-UI versucht wurde, die Auftragsreferenzen von der Fußzeile der Seitennavigation aus zu öffnen, während die Auftragsdetails in einem duplizierten Tab geöffnet waren, führte der Redirect zu einem Fehler. Dieser Fehler wurde behoben.

[discrete]
=== CRM

* Beim Wechseln zwischen zwei Gastbesteller Adressen wurde das Adress-Portlet nicht aktualisiert.
Dieses Verhalten wurde behoben.
* Beim Klicken auf den Firmennamen eines Gastbestellers in der Kontaktübersicht wurde man auf das Dashboard und nicht in die Firmen-UI geleitet. Dieses Verhalten wurde behoben.
* Wenn im Messenger-Assistenten ein Posteingang als Standard bestimmt war, wurde das in der in der Zusammenfassung falsch angezeigt. Dieses Verhalten wurde behoben.
* Beim Einfügen eines HTML-Textblocks im Messenger-Editor wurde statt des formatierten Textes der HTML-Code im Textbereich angezeigt. Dieses Verhalten wurde nun behoben.

[discrete]
=== Dokumente

* Die Variable *Retourengrund* hat die ID des Grundes und nicht den Grund selbst ausgegeben. Das wurde behoben.

--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.



--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|
|
|

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

====
