= Changelog 27. September 2023
:author: kevin-stederoth
:sectnums!:
:page-index: false
:page-aliases: ROOT:changelog.adoc
:startWeekDate: 21. September 2023
:endWeekDate: 27. September 2023

// Ab diesem Eintrag weitermachen: LINK EINFÜGEN

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Aufträge

* In der Auftrags-UI enthielt die MyView Liste einige Pflicht-Widgets, die die Verwendung solcher Widgets erzwangen. Die Deklarierung als Pflicht-Widget wurde von allen Widgets entfernt.
* Die Buttons, zum Warenausgang zurückbuchen (Übersicht und Detailansicht) haben jetzt eine grüne Markierung, damit man direkt erkennt, dass der Warenausgang gebucht wurde.
* Der Button zum Warenausgang zurückbuchen wird jetzt Standardmäßig in der Standardansicht und Classic Ansicht angezeigt.
* In der Auftrags-UI war es bei den Eingabefeldern vom Typ Zahl möglich, den Wert durch Scrollen zu ändern. Dies hat sich nun geändert und die Funktion wurde aus allen Zahlenfeldern entfernt.
* In der Auftrag UI wurde der Filter *Auftragsadressdaten* in in Standard Ansicht hinzugefügt.

[discrete]
=== Dokumente

* Bei der Aktivierung der Nummernkreise wurden Hinweise zu möglichen Überschneidungen mit anderen Nummernkreisen eingefügt.
* In DocumentBuilder werden Einschränkungen der Ausgabe eines Text-Widgets nun bereits im Editor selbst dargestellt. Dies passiert durch Einfärben des Hintergrundes des betroffenen Text-Widgets.

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Aufträge

* Wenn man zur Auftragsübersicht mit vorausgefüllten Filtern navigiert und einige Filter bereits in der Auftragsübersicht gesetzt waren, wurden diese Filter nicht von den neuen Filtern überschrieben. Dies wurde behoben.
* In der neuen Auftrags-UI war der Button *Warenbestand ermitteln* in der Symbolleiste der Auftragsdetails nicht sichtbar. Dies wurde nun behoben.
* Wenn in der UI für die Auftragserstellung zu einer anderen Tab oder UI navigiert wird, während der Prozess der Auftragserstellung noch nicht abgeschlossen ist, werden bei der Rückkehr zur Auftragserstellung, um diese abzuschließen, die Kontakdaten oder Auftragspositionen zurückgesetzt und beim Speichern wird ein Fehler ausgegeben. Dies wurde behoben.
* In der Auftrags-UI hatte die Spalte *Erweitern* in der Tabelle der Auftragspositionen eine doppelte Breite. Dies wurde behoben.

[discrete]
=== CRM

* Im Ticket-Portlet der Kontakt-UI war die Schaltfläche *Neues Ticket* nur für Administratoren sichtbar, auch wenn der angemeldete Benutzer die Berechtigung *CRM » Ticketsystem » Erstellen* hatte. Dieses Verhalten wurde nun behoben.
* Die EmailBuilder-Variable `Rechnungsnummer-ID` hat nur die Rechnungsnummer ausgegeben, aber nicht die Nummer mit dem Präfix. Dieses Verhalten wurde behoben.
* Im Portlet *Primäre Adresse* im Kontaktdatensatz waren unnötige Kommata zwischen der Hausnummer und dem Straßennamen und zwischen der Postleitzahl und dem Ort sichtbar. Diese wurden entfernt.

[discrete]
=== Dokumente

* Manche Variablen haben die Sprache des Auftrages nicht berücksichtigt. So wurde für das Land der Adressen der Standardname benutzt, anstelle des übersetzten Ländernamens. Auch wurde für den Standard-Lagerort immer *Default* genutzt. Beides wurde behoben, im deutschen wird für den Standard-Lagerort jetzt *Standard* genutzt.
* Die Variablen `Umsatzsteuerbetrag (X)` haben bei netto Aufträgen einen Wert gehabt. Diese werden nun nicht gesetzt, somit greift die Einschränkung auf diese Variablen wie gewünscht.
* In der UI der Nachbestellungen wurde beim Hauptdokument anstelle des Dateinamens die Dokumentnummer angezeigt. Dadurch gab es Irritationen mit der Einstellung des Dateinamens in den Vorlagen des DocumentBuilders. Dies wurde behoben.

[discrete]
=== Prozesse

* Nach der ersten Überarbeitung der Sammeldokumente wurden wir von euch auf Prozesse aufmerksam gemacht, die mit bestimmten Subaktionkobinationen von Drucken und Speichern, mit und ohne der Sammeldokumente, ein mehrfaches Speichern oder einen mehrfacher Ausdruck möglich gemacht haben. Dieser Fehler wurde behoben.

'''

[discrete]
== Gelöscht

Folgende Funktionalität wurde in den letzten 7 Tagen von *{version}* entfernt.

[discrete]
=== CRM

* Das Ereignis *Benachrichtigung bei verfügbarem Artikel* war noch im Assistenten *E-Mail-Konten* im Schritt *Automatischer Versand* sichtbar, obwohl das Ereignis gar nicht mehr ausgelöst wurde. Das Ereignis wurde aus der Liste im Assistenten entfernt.

--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.



--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|
|
|

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

====
