= Changelog 26. April 2023
:author: kevin-stederoth
:sectnums!:
:page-index: false
:startWeekDate: 20. April 2023
:endWeekDate: 26. April 2023

// Ab diesem Eintrag weitermachen: https://forum.plentymarkets.com/t/new-order-ui-test-phase-fix-ticket-widget-visibility-in-order-details-view-neue-auftrags-ui-testphase-fix-fuer-sichtbarkeit-des-ticket-widgets-in-detailansicht/719694

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Aufträge

* Die folgenden Änderungen wurden in der neuen Auftrags-UI implementiert:
** In der Kompaktansicht wurde in den Feldern für *Rechnungsadresse* und *Lieferadresse* der ISO-Code des Landes neben der Stadt hinzugefügt.
** In der Kompaktansicht wurde in den Feldern für *Rechnungsadresse* und *Lieferadresse* der eBay-Name vor dem Namen eingefügt.
** In der Detailansicht des Auftrags wurden die Adressoptionen innerhalb des Adress-Widgets hinzugefügt und können ein- und ausgeklappt werden.
** In der Detailansicht des Auftrags enthält das Adress-Widget nun auch den eBay-Namen als Adressoption.
** Die Adressoptionen wurden in den Spalten *Rechnungsadresse* und *Lieferadresse* der Übersichtstabelle in der Auftragsübersicht hinzugefügt.

[discrete]
=== Zalando

Die Pilotphase für Zalando ZFS wurde abgeschlossen und ZFS und Händler:innen können das Onboarding für Zalando ZFS beginnen.

Folgende Funktionen werden für ZFS angeboten:

. Synchronisieren von ZFS-Lagerbeständen summiert pro Land.
. Import von ZFS-Aufträgen
* Nur von Zalando versandte Aufträge werden importiert. Stornierte ZFS-Aufträge werden ignoriert.
* Unter der ID 172 finden sich eigene länderspezifische Auftragsherkünfte für ZFS, die den Aufträgen zugeordnet werden.
* Die Aufträge werden mit gebuchtem Warenausgang und gebuchter Zahlung importiert.
* Das Lager wird dem entsprechenden ZFS-Lager zugeordnet, wenn möglich.
* Ein Parallelbetrieb von ZFS und Eigenversand in einem Land ist möglich.
. Import von ZFS-Retouren
* Funktioniert nur, wenn der ursprüngliche Auftrag auch im System vorliegt.

Die Einstellungsmöglichkeiten findet ihr im Menü *Einrichtung » Assistenten » Omni-Channel » Kontoeinstellungen Zalando* im jeweiligen Account in den Schritten *Zalando Fulfillment Solutions (ZFS)* und den xref:maerkte:zalando.adoc#assistant-2[Kanal-Einstellungen des jeweiligen Landes]. Die Einstellungen in den Kanal-Einstellungen werden nur sichtbar, wenn der ZFS im Schritt *Zalando Fulfillment Solutions (ZFS)* aktiviert wurde.

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Aufträge

* Die folgenden Änderungen wurden an der Kompaktansicht vorgenommen:
** Die Kompaktansicht ist in neuen Systemen standardmäßig aktiviert.
** Gesetzte Filter werden automatisch übernommen, wenn man zwischen der Kompaktansicht und der Listenansicht wechselt.
** Die Suche wird ausgelöst, wenn man zwischen der Kompaktansicht und der Listenansicht wechselt.
** Die Standardeinstellung für *Farbliche Markierung* wurde zu blau für die Adressfelder und zu grün für die Felder *Rechnungsnummer* und *Kontakt-ID* geändert.

[discrete]
=== Kontoeinstellungen

In den letzten Wochen haben wir an den ersten Anpassungen der neuen Kontoverwaltung gearbeitet. Folgende UIs sind von den Änderungen betroffen:

* *Einstellungen » Kontoverwaltung » Konten*:
** Ab sofort findet sich in der Toolbar des Menüs *Einstellungen » Kontoverwaltung » Konten* die Funktion *Neues Konto*, mit der du neue Benutzer:innen-Konten hinzuzufügen kannst. Außerdem wurde die Suche in der Toolbar in Konten suchen umbenannt und in die Funktion ein neues Benutzer:innen-Konto hinzuzufügen in der Navigation von *Neu* in *Neues Konto*.
** Ab sofort lässt sich die Größe der Tabellenspalten im Menü *Einstellungen » Kontoverwaltung » Konten* ändern.
** Ab sofort ist die Spalte *ID* die erste in der Tabelle des Menüs *Einstellungen » Kontoverwaltung » Konten*. Außerdem haben die Spalten *Sprache* und *E-Mail* die Plätze getauscht.
** Ab sofort sind alle Filter in der Toolbar im Menü *Einstellungen » Kontoverwaltung » Konten* in einer Spalte untereinander.
* *Einstellungen » Kontoverwaltung » Konten » Detailansicht*:
** Ab sofort bleibt das Speichern-Symbol in der Detailansicht unter *Einstellungen » Kontoverwaltung » Konten » [Konto auswählen]* ausgegraut, wenn keine Änderungen im Konto vorgenommen wurden.
* *Einstellungen » Kontoverwaltung » Rollen*:
** Ab sofort lässt sich die Größe der Tabellenspalten im Menü *Einstellungen » Kontoverwaltung » Rollen* ändern.
** Ab sofort findet sich in der Toolbar des Menüs *Einstellungen » Kontoverwaltung » Rollen* die Funktion, neue Rollen hinzuzufügen. Außerdem wurde die Suche in der Toolbar in *Rolle suchen* umbenannt und die Funktion eine neue Rolle hinzuzufügen in der Navigation von *Neu* in *Neue Rolle*.
* *Einstellungen » Kontoverwaltung » Rollen » Detailansicht*:
** Ab sofort bleibt das Speichern-Symbol in der Detailansicht unter *Einstellungen » Kontoverwaltung » Rollen » [Rolle auswählen]* ausgegraut, wenn keine Änderungen in der Rolle vorgenommen wurden.
* *Einstellungen » Kontoverwaltung » Sicherheit.*:
** Ab sofort bleibt das Speichern-Symbol im Menü *Einstellungen » Kontoverwaltung » Sicherheit* ausgegraut, wenn keine Änderungen vorgenommen wurden.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Aufträge

* In der Kompaktansicht werden die Symbole jetzt korrekt zentriert, wenn die Einstellung *Nur Symbol anzeigen* aktiviert wurde.
* Es wurde beim Klicken auf den Status im Dashboard kein Filter in der neuen Auftrags-UI gesetzt und die Suche wurde nicht ausgelöst. Das wurde jetzt behoben.

[discrete]
=== CRM

* Wenn ein Ticket per E-Mail ins Ticketsystem importiert wird, ist standardmäßig kein Kontakt verlinkt, jedoch ist die Absender-E-Mail-Adresse verfügbar. Wenn eine Ticketsystem-Ereignisaktion aktiv ist, die eine E-Mail an den Kontakt senden soll, wurde diese Ereignisaktion nicht ausgelöst, wenn kein Kontakt verlinkt ist. In diesem Fall konnte also keine Antwort an den Kontakt gesendet werden.
+
Dieses Verhalten wurde nun so gelöst: Wenn kein Kontakt im Ticket verlinkt ist, wird die Absender-E-Mail-Adresse aus dem Ticket verwendet, um auf das Ticket zu antworten.
* Wenn man im Assistenten *Messenger-Konfiguration* im Schritt *Service-Aktivierung* den Messenger deaktiviert hat, konnten dennoch E-Mails über den Messenger versendet und empfangen werden. Dieses Verhalten wurde behoben.

[discrete]
=== plentyBI

* Wenn im Menü *Einrichtung » plentyBI » Kennzahlen* der Name einer Kennzahlkonfiguration geändert wurde, wurde diese Änderung nach dem Speichern nicht für entsprechenden Eintrag der Kennzahl in der linken Seitennavigation übernommen. Dieses Verhalten wurde behoben, sodass der Name nun korrekt aktualisiert wird.

--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Aufträge

* In der Kompaktansicht wurde eine Checkbox in der Toolbar hinzugefügt, um alle Aufträge für Gruppenfunktionen auszuwählen.
* In der Kompaktansicht wurden neue Sortieroptionen hinzugefügt:
** Zahlungsdatum
** Warenausgangsdatum
** Postleitzahl
** Lieferdatum
** Hauptdokument
* In der Kompaktansicht wurden neue Filter hinzugefügt:
** Externe Lieferscheinnummer
** Externe Quellauftrags-ID

[discrete]
=== CRM

* Die automatisch generierte E-Mail-Adresse im Assistenten *Messenger-Konfiguration* wurde angepasst, um dem RFC-Standard 2821 zu entsprechen. Bitte beachte unser Praxisbeispiel xref:crm:praxisbeispiel-e-mail-weiterleitung-messenger.adoc[E-Mail-Weiterleitung für den Messenger einrichten].
+
[IMPORTANT]
.To-Do
======
Damit die kürzere E-Mail-Adresse verwendet wird, muss eine xref:crm:messenger-testphase.adoc#assistent-durchlaufen[neue Inbox] angelegt werden. Bereits erstellte E-Mail-Adressen werden weiterhin unterstützt.
======

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== CRM

* In der Kontakte-Übersicht (Menü *CRM » Kontakte*) sowie in allen Bereichen innerhalb des Kontaktdatensatzes, in denen es die Funktion gibt, sich eine Anzahl der Ergebnisse pro Seite anzeigen zu lassen, merkt sich das System ab sofort, welche Zahl man gewählt hatte, wenn man sich das nächste Mal einloggt. Bisher wurde immer die kleinste Zahl (5) beim erneuten Login angezeigt, auch wenn mehr als 5 Ergebnisse vorhanden waren.

[discrete]
=== Kontoeinstellungen

* Der Suche in der UI *Einstellungen » Kontoverwaltung » Konten* wurden Filter hinzugefügt, um nach Administratoren, Nicht-Administratoren und allen Benutzer:innen-Konten zu suchen.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Aufträge

* Der Tooltip des Icons zeigt nun auch an, welches Amazon-/eBay-Treueprogramm verwendet wird.

[discrete]
=== Dokumente

* Wenn die Einstellung *Anzahl Nachkommastellen bei Auftragspositionen* auf die Option *4* gesetzt war, wurde die MwSt. nicht zur Menge 1, sondern zur aktuellen Positionsmenge angezeigt. Dies wurde behoben.

[discrete]
=== Ereignisaktionen

* Für die Aktion *Tags hinzufügen/löschen* wurde in der Übersicht der Ereignisaktionen kein Wert angezeigt. Nun ist es möglich zu sehen, welche Tags zum Hinzufügen oder Löschen gewählt wurden und ob sie entfernt werden.

[discrete]
=== plentyBI

* Für die Kennzahl *Retourenquote* wurden innerhalb von Tabellen oder Diagrammen auf dem Dashboard keine Ergebnisse angezeigt, wenn in der Kennzahlkonfiguration die Dimension *Auftragsherkunft* verwendet wurde. Dieses Verhalten wurde behoben, sodass die Daten nun korrekt angezeigt werden.

--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|link:https://marketplace.plentymarkets.com/formatdesigner_6483[FormatDesigner^]
|1.3.11
|-

|link:https://marketplace.plentymarkets.com/glsshippingstates_55045[GLS Versandstatus Tracking^]
|1.1.3
|-

|link:https://marketplace.plentymarkets.com/cfourcontainerinfoelement5_54773[Info-Element^]
|1.0.3
|-

|link:https://marketplace.plentymarkets.com/mollie_6272[Mollie^]
|2.8.25
|-

|link:https://marketplace.plentymarkets.com/mytoys_54776[myToys^]
|1.0.65
|-

|link:https://marketplace.plentymarkets.com/reviewwidget_55394[Plenty Reviews 5 in 1 Plugin - das Toolkit für Ihre Artikelbewertungen^]
|1.0.3
|-

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

====
