= Changelog 24. Mai 2023
:author: kevin-stederoth
:sectnums!:
:page-index: false
:page-aliases: ROOT:changelog.adoc
:startWeekDate: 18. Mai 2023
:endWeekDate: 24. Mai 2023

// Ab diesem Eintrag weitermachen: LINK EINFÜGEN

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Amazon

* Der Amazon-Artikeldatenexport wurde überarbeitet.
* Im Menü *Einrichtung » Artikel » Verkaufspreise* wurde die Einstellung *Amazon-Konten* in *Amazon-Channels* umbenannt. Als Optionen sind die Channels wählbar.

*Hintergrund*

Vor Kurzem wurde das neue Menü für das Hinzufügen von Amazon-Konten veröffentlicht. Im Moment kannst du im Menü *Einrichtung » Märkte » Amazon » Neue Einstellungen* zwar noch keine Konten erstellen und bearbeiten. Es werden dort aber schon deine vorhandenen Amazon-Konten angezeigt. Wir arbeiten weiter daran, diese neuen Einstellungen zum Standard zu machen.

*Was ist neu?*

Als nächsten Schritt haben wir den Amazon FBA-Bestandsimport überarbeitet: Ab sofort wird beim Abgleich von FBA-Bestand nicht mehr auf die alten Einstellungen im Menü *Einrichtung » Märkte » Amazon » Einstellungen* zurückgegriffen. Stattdessen werden die neuen Kontoeinstellungen genutzt, um die Bestandsdaten abzugleichen.

[NOTE]
.Kein To-Do
======
Der Bestandsabgleich funktioniert genauso wie vorher. Auch an den Einstellungen im plentymarkets Backend hat sich nichts geändert.
======

[discrete]
=== Aufträge

* Du kannst ab jetzt negative Preise an den Auftragspositionen setzen.
* In der Übersicht der neuen Auftrags UI wurden Filter für Retourengrund und Versandprofil hinzugefügt.
* In MyView wurde dem Feld *Herkunft* die neue Einstellung *Anzeigeoption* hinzugefügt. Du kannst jetzt bestimmen, ob du nur den Namen, nur die ID oder beides angezeigt bekommen möchtest. Folglich wurde das separate Feld *Herkunfts-ID* entfernt.

[discrete]
=== CRM

* In der UI zum Erstellen eines neuen Kontakts im Menü *CRM » Kontakte* wurde in der Toolbar die Schaltfläche *Zurücksetzen* hinzugefügt. Mit einem Klick auf diese Schaltfläche kannst du alle bisherig getätigten Eingaben wieder zurücksetzen. Außerdem wurde die Toolbar oben angeheftet, sodass diese auch sichtbar ist, wenn du in dieser Ansicht weiter nach unten scrollst.
* Die Gruppenfunktion in der Übersicht des Menüs *CRM » Kontakte* wurde um die folgenden Punkte erweitert:
** Tags hinzufügen
** Kundenklasse ändern
** Eigner ändern
** Bewertung ändern
** Kundentyp ändern

[discrete]
=== Import

* Beim Importformat für Aufträge wurde die Möglichkeit hinzugefügt, Tags zu importieren.

[discrete]
=== plentyBI

* Ab sofort kannst du im Menü *Einrichtung » plentyBI » Kennzahlen » [Kennzahlkonfiguration öffnen]* für jede Kennzahl eine Einheit angeben. Dazu haben wir innerhalb der Kennzahlkonfiguration die neue Option *Ergebniseinheit* hinzugefügt.
+
Hier kannst du selbst bestimmen, mit welchem Text die Einheit der Kennzahl auf den Darstellungselementen im Dashboard dargestellt wird. Je nach der *Berechnung*, die in der Kennzahlkonfiguration gewählt wurde, wird das Feld *Ergebniseinheit* mit einem passenden Vorschlag für die Benennung der Einheit vorausgefüllt.
+
Du kannst stattdessen aber auch einen individuellen Namen eingeben. Beachte dabei, dass maximal 8 Zeichen möglich sind und das Feld nicht leer sein darf, da die Kennzahlkonfiguration sonst nicht gespeichert werden kann.

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Aufträge

* In der Detailansicht der neuen Auftrags-UI kam es bei gesperrten Aufträgen in machen Fällen beim Bearbeiten von Adressen zu einem Fehler. Dies wurde behoben.

--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.



--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|
|
|

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

====
