= Changelog 5. Juli 2023
:author: kevin-stederoth
:sectnums!:
:page-index: false
:page-aliases: ROOT:changelog.adoc
:startWeekDate: 29. Juni 2023
:endWeekDate: 5. Juli 2023

// Ab diesem Eintrag weitermachen: LINK EINFÜGEN

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Aufträge

* Bei der Artikelsuche beim Erstellen eines neuen Auftrags oder bei dem editieren von Auftragsposition in der OrderUI, wurde die Spalte *Menge im Zulauf* hinzugefügt.
* Bei der Erstellung von Kindaufträgen wird nun der Variantenname angezeigt.
* In der neuen Auftrags-UI wurden für die Erstellung von Nachbestellungen folgenden Änderungen vorgenommen:
** Es wurden zwei neue Spalten *Reservierter Bestand* und *Zulauf* bei der Erstellung von einer Nachbestellung aus dem Auftrag hinzugefügt.
** Es wurde ein neuer Button im Overlay *Warenbestand ermitteln* in der Auftragsübersicht hinzugefügt. Über diesen Button wird man direkt in die UI zum Erstellung einer Nachbestellung für diesen Auftrag weitergeleitet, und der entsprechende Artikel ist vorausgewählt.
* Eigene Auftragspositionseigenschaften, die z.B. per Rest oder Plugin erstellt wurden, lassen sich nun in den Artikelpositionen der Auftrags UI / Auftragserstellung / Abonnement-UI darstellen. Diese werden in der zweiten Ebene unterhalb der Auftragspositionen neben den Bestelleigenschaften dargestellt und können in der Bearbeitungsansicht der Auftragsposition geändert werden.
* Es wurden in die Tabelle für die Auftragspositionen neue Spalten für Gewicht, Länge und Breite hinzugefügt.

[discrete]
=== Fulfillment

* Nachdem eine Retourensendung angemeldet wurde, wird nun eine Auftragsnotiz erstellt, die den Retourenversanddienstleiter und die Sendungsnummer festhält.

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Ereignisaktionen

* Ab sofort wird folgendes Recht benötigt, um Tags zu laden: *Einrichtung > Einstellungen > Tags Betrachten*

[discrete]
=== OTTO Market

Die Anbindung der OTTO Market API-Endpunkte für Belege wurde auf Version 3 aktualisiert, da die Version 2 in Kürze abgeschaltet wird.

[NOTE]
.Kein To-Do
======
Da dies eine Änderung im Hintergrund ist, besteht kein To Do für Händler:innen.
======

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== CRM

* In der Auftragstabelle am Kontakt wurde in der Spalte *Zahlungsarten* kein Wert angegeben.
Dieser Fehler wurde nun behoben.

[discrete]
=== Ereignisaktionen

* Es gab in den Ereignisaktionen das Problem, dass nach dem Ändern des Namens eines Tags, immer noch der alte Name angezeigt wurde. Dieses Verhalten wurde behoben. Des Weiteren wird nun auch die korrekte Farbe des Tags angezeigt.

[discrete]
=== Rechteverwaltung

* Beim Setzen von Rechten im einfachen Modus konnte es sein, dass die dazugehörenden Rechte im erweiterten Modus nicht automatisch ausgewählt wurden. Dieses Verhalten ist nun gefixt.

'''

[discrete]
== Gelöscht

Folgende Funktionalität wurde in den letzten 7 Tagen auf *{version}* gelöscht.

[discrete]
=== Aufträge

* Es ist nicht mehr möglich, Auftragsnotizen zu bearbeiten.

--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.



--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|
|
|

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

====
