= Changelog 19. April 2023
:author: kevin-stederoth
:sectnums!:
:page-index: false
:page-aliases: ROOT:changelog.adoc
:startWeekDate: 13. April 2023
:endWeekDate: 19. April 2023

// Ab diesem Eintrag weitermachen: https://forum.plentymarkets.com/t/dokumente-fehlerhafte-anzeige-der-mwst-in-artikelliste-documents-incorrect-display-of-vat-in-item-list/718988

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Aktionsmanager

* Für die Aktionen haben wir beim Filter *Auftragstyp* die Einstellung *Aufträge mit Lieferaufträgen ignorieren* eingeführt. Wird diese Einstellung aktiviert, werden keine Aufträge von der Aktion betroffen, die Lieferaufträge haben.

[discrete]
=== Artikel (Neue UI)

* In der neuen Artikel-UI ist es nun möglich per Variantengruppenfunktion Eigenschaften mehreren Varianten gleichzeitig hinzuzufügen. Diese Gruppenfunktion befindet sich in der allgemeinen Variantenübersicht als auch in der Variantenübersicht innerhalb eines Artikels.
+
Ein paar Hinweise zur Funktionsweise: Es werden nur Eigenschaften hinzugefügt, die noch nicht verknüpft sind. Ist die Eigenschaftsvererbung beim Hinzufügen von Eigenschaften aktiv, so wird die Verberbung aufgehoben.

[discrete]
=== Shopify

Endlich ist es so weit: Bestandskund:innen können ab sofort vom Shopify-Plugin auf die plentymarkets App für Shopify wechseln.

Die plentymarkets App für Shopify gibt es schon länger. Bisher konntest du sie aber nur für neue Verbindungen zu Shopify nutzen. Die Zeiten sind vorbei: Ab jetzt kannst du deine vorhandenen Shopify-Verbindungen migrieren.

Das Shopify-Plugin wird ab sofort nicht mehr weiterentwickelt. Klar, wenn was kaputt ist, wird es gefixt. Aber Neuerungen und Verbesserungen wird es nicht mehr geben. Schon jetzt kannst du zum Beispiel Grundpreisangaben nur mit der App zu Shopify exportieren. Und das ist erst der Anfang. Also nichts wie ran an die Migration!

Wie du die Migration durchführst, erfährst du auf der Handbuchseite xref:externe-webshops:shopify-migration.adoc[Migration zu Shopify-App].

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Aufträge

* Das Feld *Auftragssumme (Brutto)* wurde in der Detailansicht durch das Feld *Rechnungsbetrag* ersetzt.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Aufträge

* Im Bereich *Status & Tags* funktionierte die Tag-Suche bei der Eingabe eines Tag-Namen nicht korrekt. Dies wurde behoben.
* In auftragsbezogenen Tabellen war der Titel von Spalten, die eine Nummer enthalten, nicht rechtsbündig, wenn die Sortierung aktiviert war. Dies wurde behoben.
* Für die Ansicht zum Bearbeiten von Artikeln wurden die folgenden Fehler behoben:
** Im Bereich zum Hinzufügen einer Variante war der Button zum Hinzufügen nicht sichtbar. Dies wurde behoben.
** Für die Auftragstypen *Retoure* und *Gutschrift* waren die Aktionen zum Hinzufügen und Entfernen einer Variante beide sichtbar. Dies wurde behoben.
** In der Artikeltabelle konnte das *Lager* angepasst werden, wenn keine Variante zugewiesen war. Dies wurde behoben.
* In der Kompaktansicht war das Icon im Feld *Versandprofil* nicht korrekt ausgerichtet, wenn die Einstellung *Nur Symbol anzeigen* aktiviert war.
* In der Auftragsübersicht hat der Filter für das eBay-Konto nicht korrekt funktioniert. Dieses verhalten wurde behoben.
* In der Detailansicht der Aufträge kann nun das Kundenzeichen gelöscht werden.

[discrete]
=== CRM

* Im Assistenten *E-Mail-Konten* im Schritt *Infodienst* wurden die Blindkopien nicht an die dort eingegebenen E-Mail-Adressen gesendet, wenn die Vorlage über den EmailBuilder versendet wurde. Dieses Verhalten wurde behoben.
* Die Variable *URL zum Variantenbild* (`orderItem.formattedImageUrl`) hat in der versendeten E-Mail keinen Wert ausgegeben. Dieses Verhalten wurde behoben.
* Wenn man innerhalb eines Prozesses, eine EmailBuilder-Vorlage versenden wollte, erschien eine Fehlermeldung. Die E-Mail wurde nicht versendet. Dieses Verhalten wurde behoben.
* Nach der Migration einer E-Mail-Vorlage, die die alte Variable `$OrderProperties` enthielt, hat die Artikelliste zu viele Werte wie zum Beispiel die ID des Versandprofils ausgegeben, die vorher mit der alten Variable nicht ausgegeben wurden. Der Grund dafür lag in der Variable `orderItem.formattedProperties.all | raw`. Dieses Verhalten wurde behoben.

[IMPORTANT]
.To-Do
======
Bei folgenden twig expressions im Code-Widget des EmailBuilder muss `| raw` am Ende eingefügt werden, damit die entsprechenden Werte korrekt in der gesendeten E-Mail dargestellt werden können. Die twig expressions sollten dann folgendermaßen aussehen:

* `{{ globals.legalInformation.termsConditions.html | raw }}``
* `{{ globals.legalInformation.cancellationRights.html | raw }}``
* `{{ globals.legalInformation.privacyPolicy.html | raw }}``
* `{{ globals.legalInformation.withdrawalForm.html | raw }}``
* `{{ globals.legalInformation.legalDisclosure.html | raw }}``
* `{{ globals.account.signatureHTML | raw }}``
* `{{ globals.account.signatureText | raw }}``
======

[discrete]
=== Fulfillment

* Wenn im Versand-Center 2.0 eine Paketnummer eingetragen oder aktualisiert wurde oder wenn eine Sendung angemeldet und dadurch eine Paketnummer hinzugefügt wurde, erschien der entsprechende Benutzer nicht in der Statushistorie. Dieses Verhalten wurde behoben.
* Nach dem Importieren von Adressdaten auf DHL Internetmarke wurden Umlaute nicht richtig dargestellt. Dieser Fehler wurde behoben.

--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Aufträge

* Die folgenden Änderungen wurden in der neuen Auftrags-UI implementiert:
** In der Kompaktansicht wurde in den Feldern für *Rechnungsadresse* und *Lieferadresse* der ISO-Code des Landes neben der Stadt hinzugefügt.
** In der Kompaktansicht wurde in den Feldern für *Rechnungsadresse* und *Lieferadresse* der eBay-Name vor dem Namen eingefügt.
** In der Detailansicht des Auftrags wurden die Adressoptionen innerhalb des Adress-Widgets hinzugefügt und können ein- und ausgeklappt werden.
** In der Detailansicht des Auftrags enthält das Adress-Widget nun auch den eBay-Namen als Adressoption.
** Die Adressoptionen wurden in den Spalten *Rechnungsadresse* und *Lieferadresse* der Übersichtstabelle in der Auftragsübersicht hinzugefügt.

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Aufträge

* Die folgenden Änderungen wurden an der Kompaktansicht vorgenommen:
** Die Kompaktansicht ist in neuen Systemen standardmäßig aktiviert.
** Gesetzte Filter werden automatisch übernommen, wenn man zwischen der Kompaktansicht und der Listenansicht wechselt.
** Die Suche wird ausgelöst, wenn man zwischen der Kompaktansicht und der Listenansicht wechselt.
** Die Standardeinstellung für *Farbliche Markierung* wurde zu blau für die Adressfelder und zu grün für die Felder *Rechnungsnummer* und *Kontakt-ID* geändert.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Aufträge

* In der Kompaktansicht werden die Symbole jetzt korrekt zentriert, wenn die Einstellung *Nur Symbol anzeigen* aktiviert wurde.
* Es wurde beim Klicken auf den Status im Dashboard kein Filter in der neuen Auftrags-UI gesetzt und die Suche wurde nicht ausgelöst. Das wurde jetzt behoben.

--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|link:https://marketplace.plentymarkets.com/googleanalytics_4725[GoogleAnalytics^]
|2.0.1
a|
* Diese Plugin-Version kommuniziert ausschließlich mit GA4 Properties. Prüfe daher, ob eine GA4-kompatible link:https://support.google.com/analytics/answer/12270356?hl=de[Mess-ID^] im Format (G-XXXXX) in den Plugin-Einstellungen eingetragen wurde.
* In den Plugin-Einstellungen muss die Container-Verknüpfung *Google Analytics purchase event code* gesetzt werden.

|link:https://marketplace.plentymarkets.com/paypal_4690[PayPal Checkout^]
|6.2.6
|-

|link:https://marketplace.plentymarkets.com/responsivetabswidget_55426[Responsive Tabs Widget^]
|1.0.2
|-

|link:https://marketplace.plentymarkets.com/trackingmanager_54743[TrackingManager^]
|1.3.2
|-

|link:https://marketplace.plentymarkets.com/trustedshops_4962[Trusted Shops Reviews Toolkit^]
|2.2.3
|-

|link:https://marketplace.plentymarkets.com/vatidcheck_6023[VAT ID Check^]
|2.2.9
|-

|link:https://marketplace.plentymarkets.com/cytitemavailabilitynotification_6906[Wieder auf Lager! - Verfügbarkeitsbenachrichtigung mit Statistik^]
|1.6.2
|-

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

====
