= Changelog 12. April 2023
:author: kevin-stederoth
:sectnums!:
:page-index: false
:page-aliases: ROOT:changelog.adoc
:startWeekDate: 6. April 2023
:endWeekDate: 12. April 2023

// Ab diesem Eintrag weitermachen: LINK EINFÜGEN

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Aufträge

* Beim Bearbeiten oder Erstellen von Lieferadressen gibt es nun die Optionen für eine Packstation oder eine Postfiliale.
* Neue MyView Einstellung *Read-only* für die Eingabefelder in der Detailansicht hinzugefügt, womit eingeschränkt wird, ob der Nutzer die Eingabefelder verändern kann.
* Die Einstellungen für die verschiedenen Auftragstypen wurden überarbeitet und für einige Auftragstypen wurden neue UIs hinzugefügt. Weitere Informationen dazu findest du auf den Handbuchseite xref:auftraege:order-types.adoc[der Auftragstypen].
* Das Feld *Treueprogramm* ist für die Auftragsübersicht (Kompakt und Listenansicht) und Detailansicht (Allgemein Widget) verfügbar.

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Artikel (Neue UI)

* Die Darstellung der Zeitstempel an verschiedenen Stellen der neuen Artikelbenutzeröberfläche wurden angepasst, so dass sie die Uhrzeit anzeigen und die Formatierung der jeweils eingestellten Sprache angemessen ist. Diese Änderung betrifft:
** Artikelübersicht
** Artikel Informationselement in der Werkzeugleiste der Artikelansicht
** Variantenübersicht innerhalb eines Artikels
** Varianten Informationselement in der Werkzeugleiste der Variantenansicht
** Warenbewegungen innerhalb der Variantenansicht
** Varianten Notizen

[discrete]
=== bol.com

Die verwendeten APIs für unsere Prozesse wurden auf die neuste API Version von bol.com aktualisiert:

[cols="3,1,1"]
|===
|Prozess |Alte Version |Neue Version

|Auftragsimport
|v6
|v9

|Auftragsverwaltung (Versand, Stornierung, Retoure)
|v6
|v9

|Retourenimport
|v6
|v9

|Abgleich Angebotsdaten
|v6
|v9

|Abgleich Produktdaten
|v8
|v9
|===

[NOTE]
.Kein To-Do
======
Die Änderungen sind minimal und die Prozesse bleiben unverändert. Es gibt keinen weiteren Handlungsbedarf.
======

[NOTE]
.Auftragsimport
======
Beim Auftragsimport unterscheidet sich die Versionierung von den anderen Prozessen. Dort werden die Änderungen bereits am 03.04.2023 in stable Auswirkungen haben.
======


[discrete]
=== Fulfillment

* Wenn an einem Auftrag im neuen Versand-Center ein Versandlabel verfügbar war, führt ein Klick auf das Icon direkt dazu, dass das Label heruntergeladen wird. Dies wurde erweitert: Wie im alten Versand-Center gibt es nun ein zusätzliches Icon, sodass sich nach dem Klicken auf das Icon nun zunächst das PDF des Versandlabels öffnet.
* Im neuen Versand-Center war die Anzahl der aufgelisteten Aufträge auf 100 beschränkt. Diese Zahl wurde auf 200 erhöht.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Aufträge

* In der Detailansicht der Aufträge kann nun die externe Auftragsnummer gelöscht werden.
* Die Auftragssuche dauerte lange, wenn Aufträge keine Adressdaten hatten. Dies wurde behoben.

[discrete]
=== CRM

* Wenn man benutzerdefiniertes Styling in einem Widget in einer EmailBuilder-Vorlage verwendet hatte und dieses Styling wieder entfernen wollte, wurde ein Fehler angezeigt, der besagte, dass das Feld ausgefüllt sein muss. Es war also nicht möglich, das Feld wieder leer zu speichern. Dieses Verhalten wurde behoben.
* Im Assistenten *E-Mail-Konten* im Menü *Einrichtung » Assistenten » Grundeinrichtung* im Schritt *Infodienst* war es nicht möglich, mehrere E-Mail-Adressen im Feld E-Mails als Blindkopie erhalten zu speichern. Es konnte immer nur eine E-Mail-Adresse dort gespeichert werden. Dieses Verhalten wurde behoben.
* In manchen EmaillBuilder-Vorlagen hat die Twig-Expression `{{ orderItem.variation.item.ArtNo }}` für die Artikelnummer nicht immer einen Wert in der versendeten E-Mail ausgegeben. Dieses Verhalten wurde behoben.

'''

[discrete]
== Gelöscht

Folgende Funktionalität wurde in den letzten 7 Tagen von *{version}* entfernt.

[discrete]
=== Fulfillment

* Die EasyPAK-Schnittstelle ist obsolet, daher wurde dieser Versanddienstleister aus dem Menü entfernt.
* Das alte Menü für DHL Retoure Online wurde gelöscht: Die alte Schnittstelle wurde von DHL abgeschaltet und die neue ist über das Plugin verfügbar.

--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.



--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|
|
|

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

====
