= Changelog 24. Mai 2023
:author: kevin-stederoth
:sectnums!:
:page-index: false
:page-aliases: ROOT:changelog.adoc
:startWeekDate: 18. Mai 2023
:endWeekDate: 24. Mai 2023

// Ab diesem Eintrag weitermachen: https://forum.plentymarkets.com/t/change-myview-korrektes-drag-drop-verhalten-change-myview-correct-drag-and-drop-behaviour/722520
// Auch folgenden Eintrag beachten: https://forum.plentymarkets.com/t/plentybase-einstellungen-anzeigefehler-bei-access-token-behoben-plentybase-settings-fixed-display-error-for-access-token/722092

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Amazon

* Der Amazon-Artikeldatenexport wurde überarbeitet.
* Im Menü *Einrichtung » Artikel » Verkaufspreise* wurde die Einstellung *Amazon-Konten* in *Amazon-Channels* umbenannt. Als Optionen sind die Channels wählbar.

*Hintergrund*

Vor Kurzem wurde das neue Menü für das Hinzufügen von Amazon-Konten veröffentlicht. Im Moment kannst du im Menü *Einrichtung » Märkte » Amazon » Neue Einstellungen* zwar noch keine Konten erstellen und bearbeiten. Es werden dort aber schon deine vorhandenen Amazon-Konten angezeigt. Wir arbeiten weiter daran, diese neuen Einstellungen zum Standard zu machen.

*Was ist neu?*

Als nächsten Schritt haben wir den Amazon FBA-Bestandsimport überarbeitet: Ab sofort wird beim Abgleich von FBA-Bestand nicht mehr auf die alten Einstellungen im Menü *Einrichtung » Märkte » Amazon » Einstellungen* zurückgegriffen. Stattdessen werden die neuen Kontoeinstellungen genutzt, um die Bestandsdaten abzugleichen.

[NOTE]
.Kein To-Do
======
Der Bestandsabgleich funktioniert genauso wie vorher. Auch an den Einstellungen im plentymarkets Backend hat sich nichts geändert.
======

[discrete]
=== Aufträge

* Du kannst ab jetzt negative Preise an den Auftragspositionen setzen.
* In der Übersicht der neuen Auftrags UI wurden Filter für Retourengrund und Versandprofil hinzugefügt.
* In MyView wurde dem Feld *Herkunft* die neue Einstellung *Anzeigeoption* hinzugefügt. Du kannst jetzt bestimmen, ob du nur den Namen, nur die ID oder beides angezeigt bekommen möchtest. Folglich wurde das separate Feld *Herkunfts-ID* entfernt.

[discrete]
=== CRM

* In der UI zum Erstellen eines neuen Kontakts im Menü *CRM » Kontakte* wurde in der Toolbar die Schaltfläche *Zurücksetzen* hinzugefügt. Mit einem Klick auf diese Schaltfläche kannst du alle bisherig getätigten Eingaben wieder zurücksetzen. Außerdem wurde die Toolbar oben angeheftet, sodass diese auch sichtbar ist, wenn du in dieser Ansicht weiter nach unten scrollst.
* Die Gruppenfunktion in der Übersicht des Menüs *CRM » Kontakte* wurde um die folgenden Punkte erweitert:
** Tags hinzufügen
** Kundenklasse ändern
** Eigner ändern
** Bewertung ändern
** Kundentyp ändern

[discrete]
=== Import

* Beim Importformat für Aufträge wurde die Möglichkeit hinzugefügt, Tags zu importieren.

[discrete]
=== plentyBI

* Ab sofort kannst du im Menü *Einrichtung » plentyBI » Kennzahlen » [Kennzahlkonfiguration öffnen]* für jede Kennzahl eine Einheit angeben. Dazu haben wir innerhalb der Kennzahlkonfiguration die neue Option *Ergebniseinheit* hinzugefügt.
+
Hier kannst du selbst bestimmen, mit welchem Text die Einheit der Kennzahl auf den Darstellungselementen im Dashboard dargestellt wird. Je nach der *Berechnung*, die in der Kennzahlkonfiguration gewählt wurde, wird das Feld *Ergebniseinheit* mit einem passenden Vorschlag für die Benennung der Einheit vorausgefüllt.
+
Du kannst stattdessen aber auch einen individuellen Namen eingeben. Beachte dabei, dass maximal 8 Zeichen möglich sind und das Feld nicht leer sein darf, da die Kennzahlkonfiguration sonst nicht gespeichert werden kann.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Aufträge

* In der Detailansicht der neuen Auftrags-UI kam es bei gesperrten Aufträgen in machen Fällen beim Bearbeiten von Adressen zu einem Fehler. Dies wurde behoben.

[discrete]
=== Fulfillment

* Beim Anmelden einer Sendung über die interne DPD-Integration kam es zu einer Fehlermeldung, da die alternativen Kontaktdaten (Handynummer oder E-Mail-Adresse) nicht übertragen wurden. Dieses Problem wurde behoben.
* Der automatische Versandlabel-Download funktionierte im Versandcenter 2.0 nur in der Suche-Ansicht, nicht aber in der Detailansicht. Dieses Problem wurde behoben.

--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Aufträge

* In der neuen Auftrags-UI sind die Tabellenüberschriften und die Suchkomponente jetzt beim Scrollen durch die Auftragsliste fixiert.
* In der neuen Auftrags-UI werden die Preise mit zwei Dezimalstellen angezeigt, und der Tooltip wird bei Bedarf mit vier Dezimalstellen angezeigt.
* Der Buchstabe des Mehrwertsteuersatzes wird jetzt immer mit angezeigt bei den Auftragspositionen.
* In der Auftragsübersicht wurde die Möglichkeit geschaffen, über die MyView-Einstellungen die vorgeschlagenen Filter in der Autovervollständigung selbst zu konfigurieren.

[discrete]
=== CRM

* In den Kontaktoptionen im Menü *CRM » Kontakte* steht dir unter Zusatz der Eintrag *Follow-up-Datum* zur Verfügung. Hier kannst du ein Datum und eine Uhrzeit zur Wiedervorlage speichern. Mit einem Klick auf *Zum Kalender hinzufügen* öffnet sich dein Google Kalender, und du kannst ein Meeting an diesem Follow-up-Datum als Erinnerung in deinem Google-Kalender erstellen.
** In den Filtern wurden die Felder *Follow-up-Datum von* und *Follow-up-Datum bis* hinzugefügt.
** Außerdem kannst du über die Funktion *Spalten konfigurieren* oben rechts das *Follow-up-Datum* aus den Kontaktoptionen in der Übersicht anzeigen lassen und die Übersicht auf- oder absteigend anhand des Follow-up-Datums sortieren.
* Im *Aufträge*-Portlet des Kontaktdatensatzes im Menü *CRM » Kontakte* wurde ein Filter hinzugefügt, mit dem du nach einem oder mehreren Auftragstypen suchen kannst.

[discrete]
=== Kontoverwaltung

* Ab heute kannst du Rechte an Rollen vergeben, die Nutzer:innen MyView-Ansichten erstellen, bearbeiten und löschen lassen. Diese Rechte sind mit dem *Betrachten*-Recht der jeweiligen Benutzeroberfläche der MyView-Ansicht verbunden. Diese neuen Rechte heißen *Ansichten* und du findest sie im einfachen Modus ganz oben.

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Prozesse

* Beim Wechsel von Tabs in den Prozessen konnte es passieren, dass der Inhalt der Prozesse nicht angezeigt wurde. Dieses Verhalten wurde behoben.

--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|link:https://marketplace.plentymarkets.com/dpdshippingservices_6320[DPD Versand Services^]
|1.7.19
|-

|link:https://marketplace.plentymarkets.com/elasticexportidealode_4723[idealo.de^]
|3.4.5
|-

|link:https://marketplace.plentymarkets.com/mollie_6272[Mollie^]
|2.8.26
|-

|link:https://marketplace.plentymarkets.com/mytoys_54776[myToys^]
|1.1.1
|-

|link:https://marketplace.plentymarkets.com/payone_5434[PAYONE^]
|2.6.0
|-

|link:https://marketplace.plentymarkets.com/extendedimagecarouselwidget_55287[Produkt Video + Bilder-Karussell Widget^]
|1.1.0
a|
* Nach dem Update auf Version 1.1.0 müssen Widgets im Menü *CMS » ShopBuilder* durch Klick auf *Inhalte neu generieren* aktualisiert werden.
* Überprüfen Sie die Texte unter *CMS » Mehrsprachigkeit*
* Passen Sie den Cookie-Richtlinie Link-Text beim Bedarf an.

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

====
