= Changelog 3. Mai 2023
:author: kevin-stederoth
:sectnums!:
:page-index: false
:startWeekDate: 27. April 2023
:endWeekDate: 3. Mai 2023

// Ab diesem Eintrag weitermachen: https://forum.plentymarkets.com/t/fix-falsche-berechnung-beim-gesamtrabatt-im-auftragspositionen-widget-fix-wrong-calculation-of-total-discount-in-order-items-widget/720505

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Aufträge

* In der Kompaktansicht wurde eine Checkbox in der Toolbar hinzugefügt, um alle Aufträge für Gruppenfunktionen auszuwählen.
* In der Kompaktansicht wurden neue Sortieroptionen hinzugefügt:
** Zahlungsdatum
** Warenausgangsdatum
** Postleitzahl
** Lieferdatum
** Hauptdokument
* In der Kompaktansicht wurden neue Filter hinzugefügt:
** Externe Lieferscheinnummer
** Externe Quellauftrags-ID

[discrete]
=== CRM

* Die automatisch generierte E-Mail-Adresse im Assistenten *Messenger-Konfiguration* wurde angepasst, um dem RFC-Standard 2821 zu entsprechen. Bitte beachte unser Praxisbeispiel xref:crm:praxisbeispiel-e-mail-weiterleitung-messenger.adoc[E-Mail-Weiterleitung für den Messenger einrichten].
+
[IMPORTANT]
.To-Do
======
Damit die kürzere E-Mail-Adresse verwendet wird, muss eine xref:crm:messenger-testphase.adoc#assistent-durchlaufen[neue Inbox] angelegt werden. Bereits erstellte E-Mail-Adressen werden weiterhin unterstützt.
======
* Im Kontaktdatensatz im Bereich *Aufträge* konntest du bisher 5, 10 oder 25 Ergebnisse pro Seite anzeigen lassen. Nun kannst du dir auch 50 Aufträge in der Übersicht anzeigen lassen.
* Im Messenger sind nun alle Nachrichten innerhalb der Konversationen standardmäßig ausgeklappt, wenn man eine Konversation anklickt, und grundlegende Formatierungen wie Fettdruck, neue Zeilen und Listen werden in der Vorschau angezeigt. Außerdem wird die Anzahl der Nachrichten innerhalb der Konversation neben dem Betreff der Konversation angezeigt.
* Im Messenger wurde in der linken Seitennavigation der Ordner Meine Filter hinzugefügt. Dieser Ordner enthält xref:crm:messenger-testphase.adoc#aktuellen-filter-speichern[alle Filter, die du im Messenger gespeichert hast]. So kannst du noch schneller auf deine Filter zugreifen. Mit einem Klick auf den jeweiligen Filter werden die Filtereinstellungen in dem Ordner, in dem du dich gerade befindest, angewendet.

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== CRM

* In der Kontakte-Übersicht (Menü *CRM » Kontakte*) sowie in allen Bereichen innerhalb des Kontaktdatensatzes, in denen es die Funktion gibt, sich eine Anzahl der Ergebnisse pro Seite anzeigen zu lassen, merkt sich das System ab sofort, welche Zahl man gewählt hatte, wenn man sich das nächste Mal einloggt. Bisher wurde immer die kleinste Zahl (5) beim erneuten Login angezeigt, auch wenn mehr als 5 Ergebnisse vorhanden waren.
* Im Kontaktdatensatz wurde der Bereich *Konto* in *Zahlungsübersicht* umbenannt.

[discrete]
=== Kontoeinstellungen

* Der Suche in der UI *Einstellungen » Kontoverwaltung » Konten* wurden Filter hinzugefügt, um nach Administratoren, Nicht-Administratoren und allen Benutzer:innen-Konten zu suchen.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Aufträge

* Der Tooltip des Icons zeigt nun auch an, welches Amazon-/eBay-Treueprogramm verwendet wird.

[discrete]
=== CRM

* Wenn man im Messenger eine neue Nachricht erstellt hat, wurde diese Nachricht zwar gesendet, aber nicht im Messenger angezeigt. Dieses Verhalten wurde behoben.

[discrete]
=== Dokumente

* Wenn die Einstellung *Anzahl Nachkommastellen bei Auftragspositionen* auf die Option *4* gesetzt war, wurde die MwSt. nicht zur Menge 1, sondern zur aktuellen Positionsmenge angezeigt. Dies wurde behoben.

[discrete]
=== Ereignisaktionen

* Für die Aktion *Tags hinzufügen/löschen* wurde in der Übersicht der Ereignisaktionen kein Wert angezeigt. Nun ist es möglich zu sehen, welche Tags zum Hinzufügen oder Löschen gewählt wurden und ob sie entfernt werden.

[discrete]
=== Fulfillment

* Wenn im Versand-Center die Option *Versandlabels im PDF-Format nach der Anmeldung automatisch herunterladen* verwendet wurde, wurden die Versandlabels in einer von der Sortierung der Aufträge bei der Anmeldung abweichenden Reihenfolge gedruckt. Dieses Verhalten wurde korrigiert.

[discrete]
=== Netto

In den folgenden Szenarien konnte es dazu kommen, dass keine Storno-Meldung an Netto übermittelt wurde:

* Wenn nur ein Lieferauftrag existiert zu einem Auftrag existiert der nicht alle Artikel des Auftrags beinhaltet.
* Wenn mehr als ein Lieferauftrag zu einem Auftrag existiert und ein Vollstorno durchgeführt wird.
* Wenn mehr als ein Lieferauftrag zu einem Auftrag existiert und eine Teilstornierung gemeldet wird, bevor der Versand der Teilieferung gemeldet wurde.

Dieses Szenarien werden jetzt korrekt behandelt.

[IMPORTANT]
.To-Do
======
Für betroffene Aufträge, die diese Szenarien seit der folgenden Änderung durchlaufen sind, link:https://forum.plentymarkets.com/t/netto-probleme-bei-meldung-von-teilieferungen-und-stornos-issues-with-notification-for-partial-shipping-confirmations-and-cancelations/714724[muss die Stornierung per Ereignisaktion neu gemeldet werden^].
======

[discrete]
=== plentyBI

* Für die Kennzahl *Retourenquote* wurden innerhalb von Tabellen oder Diagrammen auf dem Dashboard keine Ergebnisse angezeigt, wenn in der Kennzahlkonfiguration die Dimension *Auftragsherkunft* verwendet wurde. Dieses Verhalten wurde behoben, sodass die Daten nun korrekt angezeigt werden.

--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Artikel (Neue UI)

* Die Änderungsverläufe von Artikeln, Varianten und speziell Verkaufspreisen stehen nun direkt in der neuen Artikel-UI zur Verfügung. Die Änderungsverläufe für Artikel und Varianten sind links in der Navigationsleiste zu finden. Der Änderungsverlauf von Verkaufspreisen lässt sich zudem direkt einsehen. Hier gibt es zwei Wege:
** Am Verkauspreis-Panel für alle Verkaufspreisänderungen einer Variante
** An einem bestimmten Verkaufspreis für dessen Änderungen
* In der neuen Artikel UI haben wir mehrere Verbesserungen zur Lesbarkeit veröffentlicht. Dies betrifft hauptsächlich Auswahl- und Mehrfachauswahleigenschaften
** Lange Eigenschaftsnamen werden nun in der Breite begrenzt
** im Tooltip der Eigenschaftsnamen sieht man den volständigen Namen inklusive der Beschreibung (wenn vorhanden)
** im Tooltip der Auswahlwerte im Dropdown für Auswahl- und Mehrfachauswahleigenschaften sieht man nun die vollständingen Auswahlwertnamen sowie deren Beschreibung (wenn vorhanden)
** im Tooltip des Drowdowns werden die Namen der gewählten Auswahlwerte samt Beschreibung angezeigt (falls vorhanden)

+
Weitere Informationen findest du auf der Handbuchseite xref:daten:aenderungshistorie.adoc[Änderungshistorie].

[discrete]
=== Aufträge

* Du kannst ab jetzt die Gruppenfunktionen *Löschen* und *Rabatt* beim Bearbeiten von Auftragspositionen verwenden.
* Die neue Auftrags-UI wurde um die folgenden Änderungen ergänzt:
** In der Übersichtstabelle enthält die Komponente Eigenschaften der Auftragsposition auch die Merkmale.
** Im Auftragspositionen-Widget der Auftragsdetails sind die Merkmale der Auftragspositionen nun in der Tabelle der Auftragspositionseigenschaften verfügbar.
** In der Ansicht *Artikel bearbeiten* sind die Merkmale jetzt in der Tabelle mit den Eigenschaften der Auftragsposition verfügbar.
* In der neuen Auftrags-UI ist es jetzt möglich, einen Artikelnamen über mehrere Zeilen zu erstellen.
* In der Übersicht der neuen Auftrags-UI gibt es jetzt eine Gruppenfunktion, um E-Mails zu versenden.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Artikel (Neue UI)

* Es gab einen Fehler mit der Suche in Eigenschafts-Detailseite, der die Detailseite der verknüpften Eigenschaften kaputt machte. Dieser Fehler wurde behoben.

[discrete]
=== Aufträge

* Das Ticket-Widget war nicht sichtbar, wenn es in die MyView-Elemente der Detailsansicht gezogen wurde. Dies wurde behoben.
* Die Infoboxen *Brutto-Gutschein-Rabatt* und *Netto-Gutschein-Rabatt* waren nicht sichtbar, wenn die Auftragsdetails eines Auftrags geöffnet wurden. Dies wurde behoben.
* Der Auftragsstatus kann nicht mehr mit leerem Namen angelegt werden.
* In der Detailansicht der neuen Auftrags-UI wurde in manchen Fällen der Benutzername nicht in der Historie angezeigt. Dies wurde behoben.

'''

[discrete]
== Gelöscht

Folgende Funktionalität wurde in den letzten 7 Tagen auf *{version}* gelöscht.

[discrete]
=== Fulfillment

* Die alten Integrationen folgender Versanddienstleister wurden entfernt:
** *DHL Easylog*: von DHL abgeschaltet
** *GLS Germany*: Plugin vorhanden
** *Parcelforce Worldwide*: keine aktiven Nutzer

--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|link:https://marketplace.plentymarkets.com/elasticexportidealode_4723[idealo.de^]
|3.4.2
|-

|link:https://marketplace.plentymarkets.com/klarna_6731[Klarna^]
|2.4.10
|-

|link:https://marketplace.plentymarkets.com/plentybaseitemcachepos_6313[plentyBase ItemCachePOS^]
|1.0.9
|-

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

App::
+
--

[discrete]
== Behoben

Folgende Probleme wurden in Version 1.12.13 der *plentymarkets App* behoben.

* In plentyPOS war es möglich, Aufträge die nicht vom Typ Auftrag sind in die POS-Retoure zu laden und zu retournieren. Dieses Verhalten wurde behoben.
* Das Händlerlogo auf dem Kassenbon wurde nicht angezeigt, wenn der Kassenbon mit einem IOS-Gerät gedruckt wurde. Dieses Verhalten wurde behoben.

--

Warehouse-App::
+
--

[discrete]
== Neu

Folgende Neuerungen wurden in Version 1.0.10 der *plentymarkets Warehouse App* veröffentlicht.

* Eine Sprachausgabe für die Funktion *Wareneingang* wurde hinzugefügt. Die Sprachausgabe kann ab sofort im Menü *Einstellungen » Sprachausgabe » Wareneingang* aktiviert werden.

'''

[discrete]
== Geändert

Folgende Änderungen wurden in Version 1.0.10 der *plentymarkets Warehouse App* veröffentlicht.

* Die Dialoge, die zum Abschluss des Wareneingangs führen, wurden überarbeitet.
* Wenn die noch offene Bestellmenge eines nachbestellten Artikels erreicht wird, kann die einzubuchende Artikelmenge nun nicht mehr per Tippen erhöht werden. Dabei verschwindet auch das **+1**-Icon in der oberen linken Ecke des Listeneintrags für den Artikel und es werden keine weiteren Artikel mehr hinzugefügt.
* Für die Artikelansicht innerhalb der Funktion *Picklisten* wurden kleinere Verbesserungen am Layout vorgenommen, sodass Artikeldaten und Felder nun übersichtlicher angezeigt werden.

'''

[discrete]
== Behoben

Folgende Probleme wurden in Version 1.0.10 der *plentymarkets Warehouse App* behoben.

* Wenn nach dem Laden einer Nachbestellung ein passender Artikel mit MHD- oder Chargeinformationen über die Artikelsuche hinzugefügt wurde, konnte es passieren, dass ein neuer Listeneintrag erstellt wurde, anstatt den vorhandenen Listeneintrag für den Artikel aus der Nachbestellung zu aktualisieren. Dieses Verhalten wurde behoben.
* Beim Öffnen der Funktion *Wareneingang* findet nun eine Überprüfung des Lagerorts statt, der in den Einstellungen für den Wareneingang vorausgewählt wurde. Handelt es sich um einen ungültigen Lagerort, wird eine entsprechende Fehlermeldung mit weiteren Handlungsanweisungen angezeigt.
* Nachdem über die Funktion *Lagerort inspizieren* eine Variante per Shortcut umgebucht wurde, kam es zu Problemen. Die Ansicht wurde nicht neu geladen und es war nicht möglich, nach der Umbuchung in die Funktion zurück zu navigieren.
* Wenn im Menü *Einstellungen* Änderungen an bereits bestehenden Feature-Einstellungen vorgenommen wurden, wurden einige Felder nicht aktualisiert. Dieses Verhalten wurde behoben.
* Wenn in den Artikelinformationen ein neuer Barcode hinzugefügt wurde, wurden die Barcodes in der Ansicht nicht aktualisiert. Dieses Verhalten wurde behoben.
* Beim Erfassen von Artikeln mit MHD- und Chargeninformationen für den Wareneingang gab es einen Fehler, der den Abschluss des Wareneingangs verhindern konnte. Dieses Verhalten wurde behoben.
* Wenn während der Verknüpfung einer Box mit einem Auftrag ein Fehler auftrat und der entsprechende Dialog angezeigt wurde, konnte das Scannen der Box Folgefehler verursachen. Die App reagierte dann nicht mehr auf Eingaben. Dieses Verhalten wurde behoben.

--

====
