= Changelog 2. August 2023
:author: kevin-stederoth
:sectnums!:
:page-index: false
:page-aliases: ROOT:changelog.adoc
:startWeekDate: 27. Juli 2023
:endWeekDate: 2. August 2023

// Ab diesem Eintrag weitermachen: LINK EINFÜGEN

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Aufträge

* In der Detailansicht der neuen Auftrag UI ist jetzt das Feld für die externe Auftrags-ID bei Retouren verfügbar.
* Das Feld *Status* kann nun angeklickt werden, um den Status direkt zu ändern.
* Bestimmte Felder in der Kompaktansicht haben jetzt die Option *Anzeigen in Kopfzeile* um Felder in der Kopfzeile (ähnlich wie in der alten UI) anzuzeigen. Diese Einstellung ist für folgende Felder verfügbar:
** Status
** Lieferland
** Zahlungsmethode
** Währung
** Rechnungsbetrag
** USt.
** Zahlungsstatus
** Mahnstufe
** Versandprofil
** Warenausgangsdatum

[discrete]
=== CRM

* Wir haben dem Messenger die folgenden Gruppenfunktionen hinzufügt:
** zu einem Ordner Hinzufügen
** aus einem Ordner entfernen
* Die Variable für die Bestellmerkmale wurde für den EmailBuilder hinzugefügt.
Wir haben dem Messenger die folgenden Aktionen für die Ereignisaktion hinzufügt. Du findest diese unter *CRM » Messenger » Einstellungen » Automatisierung*.
** Konversation löschen
** Konversation archivieren

[discrete]
=== Dokumente

* Das Dokumenten-Widget in der Auftrags-UI wurde für den DocumentBuilder optimiert, sodass hier nun der aktuelle Status des Dokumentes angezeigt wird. Somit werden nun auch Dokumente sichtbar/angezeigt, die sich aktuell noch in Bearbeitung befinden oder bei denen es bei der Erstellung zu einem Fehler kam.

[discrete]
=== MyView

Ab sofort hast du in jeder MyView-Benutzeroberfläche die Möglichkeit, eine bestehende MyView-Ansicht zu importieren oder zu exportieren. Die Schaltflächen dafür befinden sich neben der Auswahl der Ansichten.

Du kannst nur Ansichten in eine Benutzeroberfläche importieren, die auch für diese gedacht sind, also zum Beispiel eine Dashboard-Anischt in dein Dashboard importieren. Dieselbe Ansicht lässt sich allerdings nicht in die Benutzeroberfläche von Order oder Item importieren.

Für das Importieren von Ansichten braucht Benutzer:innen-Konto folgendes Recht:
*Ansichten » Erstellen*

[discrete]
=== plentyShop

* Es wurde eine neue Benutzerrecht-Kategorie hinzugefügt: *CMS » PWA » Bereitstellen*.

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Aufträge

* Die Komponente zur Auswahl des Status in den Auftragsdetails wurde angepasst und hat nun den Fokus direkt auf dem ausgewählten Status, d.h. kein unnötiges Scrollen mehr beim Ändern des Status.

[discrete]
=== plentyShop

* Die Benutzerrecht-Kategorie *CMS » Neuer Webshop* wurde umbenannt in *CMS » Webshop*.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Aufträge

* Die neuen Einstellungen für die Felder in der Kompaktansicht wurden in alten Ansichten nicht angezeigt.

[discrete]
=== CRM

* Bei der Migration von alten E-Mail-Vorlagen in den EmailBuilder kam es zu einem Fehler, sodass in einigen Fällen Sprachen gefehlt haben. Dieser Fehler wurde nun behoben.

[discrete]
=== MyView

* Durch einen Fehler in der Zuordnung von MyViews konnte es passieren, dass beim Wechsel zwischen verschiedenen Ansichten (bspw. Wechsel von Order compact UI auf Order detailview) nicht die korrekten MyView-Sets zur Auswahl angezeigt wurden. Dieses Verhalten ist nun gefixt.

'''

[discrete]
== Gelöscht

Folgende Funktionalität wurde in den letzten 7 Tagen auf *{version}* gelöscht.

[discrete]
=== Amazon

* Der temporäre Prozess link:https://forum.plentymarkets.com/t/717722[zur Identifizierung unvollständiger FBA-Aufträge], zusammenhängende Berichte und Oberflächen werden jetzt wieder entfernt, da diese nicht mehr benötigt werden.

--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.



--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|
|
|

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

====
