= Changelog 10. Mai 2023
:author: kevin-stederoth
:sectnums!:
:page-index: false
:page-aliases: ROOT:changelog.adoc
:startWeekDate: 4. Mai 2023
:endWeekDate: 10. Mai 2023

// Ab diesem Eintrag weitermachen: https://forum.plentymarkets.com/t/import-format-auftraege-um-tags-erweitert-import-format-orders-extended-by-tags/721223
// Auch folgenden Eintrag beachten: https://forum.plentymarkets.com/t/new-order-ui-test-phase-order-create-negative-prices-on-order-items-neue-auftrags-ui-testphase-auftragsanlage-negative-preise-an-auftragspositionen/721037

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Artikel (Neue UI)

* Die Änderungsverläufe von Artikeln, Varianten und speziell Verkaufspreisen stehen nun direkt in der neuen Artikel-UI zur Verfügung. Die Änderungsverläufe für Artikel und Varianten sind links in der Navigationsleiste zu finden. Der Änderungsverlauf von Verkaufspreisen lässt sich zudem direkt einsehen. Hier gibt es zwei Wege:
** Am Verkauspreis-Panel für alle Verkaufspreisänderungen einer Variante
** An einem bestimmten Verkaufspreis für dessen Änderungen
* In der neuen Artikel UI haben wir mehrere Verbesserungen zur Lesbarkeit veröffentlicht. Dies betrifft hauptsächlich Auswahl- und Mehrfachauswahleigenschaften
** Lange Eigenschaftsnamen werden nun in der Breite begrenzt
** im Tooltip der Eigenschaftsnamen sieht man den volständigen Namen inklusive der Beschreibung (wenn vorhanden)
** im Tooltip der Auswahlwerte im Dropdown für Auswahl- und Mehrfachauswahleigenschaften sieht man nun die vollständingen Auswahlwertnamen sowie deren Beschreibung (wenn vorhanden)
** im Tooltip des Drowdowns werden die Namen der gewählten Auswahlwerte samt Beschreibung angezeigt (falls vorhanden)

+
Weitere Informationen findest du auf der Handbuchseite xref:daten:aenderungshistorie.adoc[Änderungshistorie].

[discrete]
=== Aufträge

* Du kannst ab jetzt die Gruppenfunktionen *Löschen* und *Rabatt* beim Bearbeiten von Auftragspositionen verwenden.
* Die neue Auftrags-UI wurde um die folgenden Änderungen ergänzt:
** In der Übersichtstabelle enthält die Komponente Eigenschaften der Auftragsposition auch die Merkmale.
** Im Auftragspositionen-Widget der Auftragsdetails sind die Merkmale der Auftragspositionen nun in der Tabelle der Auftragspositionseigenschaften verfügbar.
** In der Ansicht *Artikel bearbeiten* sind die Merkmale jetzt in der Tabelle mit den Eigenschaften der Auftragsposition verfügbar.
* In der neuen Auftrags-UI ist es jetzt möglich, einen Artikelnamen über mehrere Zeilen zu erstellen.
* In der Übersicht der neuen Auftrags-UI gibt es jetzt eine Gruppenfunktion, um E-Mails zu versenden.

[discrete]
=== Kataloge

* Ab sofort kannst du festlegen, dass Standardformate nur an bestimmten Wochentagen exportiert werden sollen.
** Die neue Einstellung *Wochentage* wird erst angezeigt, wenn du für die Einstellung *Übertragung* eine andere Option als die Standardoption *Nie* wählst.
** Standardmäßig sind immer alle Wochentage ausgewählt. Du wählst also die Wochentage ab, an denen kein Export stattfinden soll.
** Im Zuge dieser Neuerung wurden zwei Optionen der Einstellung Übertragung umbenannt: *Stündlich* wurde in *Einmal pro Stunde* umbenannt; *Täglich* wurde in *Einmal pro Tag* umbenannt.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Artikel (Neue UI)

* Es gab einen Fehler mit der Suche in Eigenschafts-Detailseite, der die Detailseite der verknüpften Eigenschaften kaputt machte. Dieser Fehler wurde behoben.

[discrete]
=== Aufträge

* Das Ticket-Widget war nicht sichtbar, wenn es in die MyView-Elemente der Detailsansicht gezogen wurde. Dies wurde behoben.
* Die Infoboxen *Brutto-Gutschein-Rabatt* und *Netto-Gutschein-Rabatt* waren nicht sichtbar, wenn die Auftragsdetails eines Auftrags geöffnet wurden. Dies wurde behoben.
* Der Auftragsstatus kann nicht mehr mit leerem Namen angelegt werden.
* In der Detailansicht der neuen Auftrags-UI wurde in manchen Fällen der Benutzername nicht in der Historie angezeigt. Dies wurde behoben.

[discrete]
=== CRM

* Im Widget *Auftragspositionen* des EmailBuilder fand eine falsche Berechnung beim Gesamtrabatt statt. Die fehlerhafte Berechnung wirkte sich zwar nicht auf die Endsumme der Rechnung aus, jedoch wurde ein Aufpreis als Rabatt ausgewiesen. Dieses Verhalten wurde behoben.

[discrete]
=== Ereignisaktionen

* Für kurze Zeit wurde in den Ereignisaktionen bei der Aktion *Korrekturbeleg erzeugen* eine Gutschrift als Dokument erzeugt. Dies wurde behoben.

[discrete]
=== Netto

Unabhängig von der Markierung, ob ein Produkt xref:maerkte:plus-gartenxxl.adoc#365[als Grundpreispflichtig gekennzeichnet] wurde oder nicht, wurde bisher der Grundpreis berechnet und in der Produktdatei mitgeben, wenn die Menge von 1 und die Einheit von Stück abwich. Beispiel:

`<unitbaseprice>1 Paar = 36.49 EUR</unitbaseprice>`

Dies sorgte bei Netto/Marktkauf für rechtliche Probleme im Shop, weswegen die Produkte nun kurzfristig von Netto/Marktkauf offline genommen wurden.

Unsererseits wurde die Logik jetzt so angepasst, dass der Grundpreis nur berechnet und mitgegeben wird, wenn der Artikel als Grundpreispflichtig deklariert wurde.

Über Nacht eine neue korrekte Produktdatei bereitgestellt werden kann. Dadurch sollten die Produkte wieder online sein.

'''

[discrete]
== Gelöscht

Folgende Funktionalität wurde in den letzten 7 Tagen auf *{version}* gelöscht.

[discrete]
=== Fulfillment

* Die alten Integrationen folgender Versanddienstleister wurden entfernt:
** *DHL Easylog*: von DHL abgeschaltet
** *GLS Germany*: Plugin vorhanden
** *Parcelforce Worldwide*: keine aktiven Nutzer

--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Aufträge

* In der neuen Auftrags-UI verwendet die *Kompakte Ansicht* jetzt ein virtuelles Scrollen, um die Leistung zu verbessern, wenn mehr als 25 Artikel pro Seite angezeigt werden.
* In der neuen Auftrags-UI kann die Übersichtssuche auch durch Drücken der Eingabetaste innerhalb eines Filters ausgelöst werden. Das Drücken der Eingabetaste funktioniert nicht bei Datums-, Auswahl- und Mehrfachauswahlfiltern.
* Die Spalte *Versandprofil* wurde in der neuen Auftrags-UI für die Tabelle der Auftragspositionen eingeführt. Die Spalte *Versandprofil* ist optional und kann über die konfigurierbaren Tabellentitel in der Auftragsübersicht und in der Auftragsdetailansicht aktiviert werden.

[discrete]
=== CRM

* Ab sofort kannst du Konversationen im Messenger anheften, um noch einfacher und schneller zwischen diesen Konversationen hin- und herzuwechseln. Sobald du eine Konversation angeheftet hast, wird in der linken Seite der Navigation der Bereich *Angeheftete Konversationen* sichtbar.
+
Du kannst mit einem Klick auf das Kontextmenü in der Zeile *Angeheftete Konversationen* alle Konversationen auf einmal wieder lösen oder mit einem Klick auf *Konversation lösen* in der Zeile der angehefteten Konversation in der Seitennavigation oder in der geöffneten Konversation selbst eine einzelne Konversation wieder lösen.

[discrete]
=== Plugins

* Die Standardseite beim Öffnen eines Plugins aus der Plugin-Übersicht wurde von der Beschreibung auf die Konfiguration angepasst. Die Beschreibung enthält nun nicht mehr nur due Kurzbeschreibung, sondern die ausführliche Beschreibung aus dem Marketplace.

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Aufträge

* In der Kompaktansicht steht der Länder-ISO Code nun vor der Postleitzahl und im Tooltip ist das Land nun ausgeschrieben.
* Die folgenden Änderungen wurden an der Auftragsdetails vorgenommen:
** Im Addresse-Widget wird `Name4` dargestellt, wenn dieser vorhanden ist
** Im Addresse-Widget ist die Mail-Addresse nun klickbar (mailto aktion)
** Beim erstellen einer Nachbestellung aus einen Auftrag sind die Menge vorausgefühlt
** Warenwert Brutto widget im Übersicht-Portlet hinzugefügt

[discrete]
=== CRM

* Das Limit der dynamischen Anhänge im EmailBuilder wurde von 3 auf 4 Anhänge erhöht.

[discrete]
=== Kontoverwaltung

* Den Filtern unter *Kontoverwaltung » Konten* wurde der Filter *Rollen* hinzugefügt. Somit kannst du künftig die Benutzer:innen-Konten nach vergebenen Rollen filtern.

[discrete]
=== Plugins

* Wenn du für ein Plugin den GitHub Branch wechselst, musst du künftig diesen Wechsel in einem Popup-Fenster bestätigen.
* Branches und Tags werden jetzt nicht mehr alphabetisch sortiert, sondern nach Aktualität, vom neuesten Tag/Branch zum ältesten.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Aufträge

* In der Detailansicht der neuen Auftrags-UI hatte das Markieren von Text in den Notizen nicht richtig funktioniert. Dies wurde behoben.
* Die folgenden Änderungen wurden an der Kompaktansicht vorgenommen:
** Die Einstellung in der Pagination *Ergebnisse pro Seite* wird nun gespeichert
** Nach der ausführen einer Gruppenfunktion bleibt man auf der aktuellen Seite, und wechselt nicht zurück zur ersten Seite des Suchergebnisses

[discrete]
=== CRM

* Beim Versuch Rechnungs- oder Lieferadressen für einen bestehenden Kontakt zu importieren, ohne ein Feld im Datensatz zu ändern, wurde zwar eine Meldung angezeigt, dass alle Daten erfolgreich importiert wurden, aber die Adresse wurde weder erstellt noch mit dem Kontakt verknüpft. Dieses Verhalten wurde behoben.

--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|link:https://marketplace.plentymarkets.com/limango_7023[limango^]
|1.5.0
|-

|link:https://marketplace.plentymarkets.com/wayfair_6273[Wayfair^]
|1.2.13
|-

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

====
