= Changelog 21. Juni 2023
:author: kevin-stederoth
:sectnums!:
:page-index: false
:page-aliases: ROOT:changelog.adoc
:startWeekDate: 15. Juni 2023
:endWeekDate: 21. Juni 2023

// Ab diesem Eintrag weitermachen: LINK EINFÜGEN

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== plentyBI

* Mit der neuen Berechnungsart *Retourenquote Artikel* bei der Kennzahl *Retourenquote* lässt sich nun die Quote auf Artikelebene berechnen. Die Retourenquote für Artikel wird berechnet, indem die Anzahl aller retournierten Artikel zusammengezählt wird. Dieses Ergebnis wird dann durch die Anzahl der insgesamt bestellten Artikel geteilt und mit 100 multipliziert.
+
Diese Kennzahl steht euch als kostenlose Standard-Kennzahl zur Verfügung.

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Amazon

* Es wurde ein neues Pattern der SKU-Konfiguration für Amazon Accounts in der Benutzeroberfläche implementiert.

[discrete]
=== Artikel (Neue UI)

* Das bisherige Verhalten des Scrollens (per Mausraud) innerhalb eines Eingabefeldes für Zahlen wurde geändert. Bisher erhöhte oder verringerte sich durch das Scrollen der Zahlwert des Eingebefeldes und gleichzeitig scrollte die Seite selbst. Nach dieser Änderung scrollt nur noch die Seite selbst. Dieses neue Verhalten wurde implementiert in folgenden UIs:
** Neue Artikel UI
** Preiskalkulationen
** Barcodes
** Einheiten
** Suchsprachen
** Bildereinstellungen
** Eigenschaften
** Eigenschaftengruppen
** Tags
** Lager

[discrete]
=== CRM

* Du kannst jetzt direkt im Messenger-Portlet Konversationen öffnen, auf diese antworten und neue Nachrichten senden.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Artikel (Neue UI)

* Wir haben das Verhalten korrigiert, dass man einzelne Eigenschaften in gewissen Konstellationen mehrfach hinzufügen konnte.
* Eine Bestandskorrektur ist nun auch möglich, wenn der Bestand einer Variante in einem Lager 0 ist.
* Der Warenbestands-Korrektur-Dialog im Bestandsbereich eines Artikels lässt sich wieder wie gewohnt öffnen.

[discrete]
=== Aufträge

* In der Übersicht der Auftrags-UI erschien nach dem Zusammenklappen der Seitennavigation ein weißer Stelle neben der Tabelle der Auftragspositionen. Dies wurde behoben.
* In der Auftrags-UI kann der Auftragstitel im Kompaktansicht angepasst werden, indem der Sperrstatus, der Referenzauftrag und die Mahnstufe hinzugefügt werden. Diese Informationen können in den MyView-Einstellungen hinzugefügt werden.
* In der neuen Auftrags-UI waren bei der Filterung nach Herkünften die inaktiven Herkünfte, die nicht verfügbar sein sollten, in der Herkunftsliste sichtbar. Dies wurde behoben.

--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.



--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|
|
|

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

====
