= Changelog 19. Juli 2023
:author: kevin-stederoth
:sectnums!:
:page-index: false
:page-aliases: ROOT:changelog.adoc
:startWeekDate: 13. Juli 2023
:endWeekDate: 19. Juli 2023

// Ab diesem Eintrag weitermachen: LINK EINFÜGEN

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Aufträge

* In der Auftrags-UI werden nach dem Speichern von Änderungen an einem Auftrag diese auch in der Auftragsübersicht dargestellt. Dieses Verhalten wurde auch für die Bearbeitung der Auftragspositionen implementiert. Wenn Änderungen an Auftragspositionen gespeichert werden, werden diese sowohl in der Übersichtstabelle als auch in den Auftragsdetails dargestellt.
* Die Felder im Kompaktmodus haben jetzt ein neues Aussehen.
+
Um den Kompaktmodus weiter zu verbessern und die Felder besser zu unterscheiden, haben die Kompaktfelder jetzt ein neues Aussehen. Jedes Feld wird mit einem grauen Hintergrund und abgerundeten Ecken dargestellt.
+
Die Standardfarbe für die Hervorhebung der Felder bleibt unverändert und sorgt für Vertrautheit und Benutzerfreundlichkeit. Sowohl das Standard-Ansichten-Set als auch alle zuvor gespeicherten Ansichten-Sets behalten ihre ursprünglichen Farben. Die neuen Designverbesserungen fügen sich nahtlos in die bestehenden Ansichtssätze ein.

[discrete]
=== Fulfillment

* Du kannst ab jetzt im Versand-Center den Filter für die externe Auftragsnummer finden. Um die externe Auftragsnummer in der Übersicht sehen zu können, füge die Spalte über die Konfiguration (material:settings[]) hinzu.

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== plentyShop

* Die Einstellung *Shop sperren* kann jetzt genutzt werden um plentyShops von individuellen Mandanten zu sperren. Das entsprechende Menü wurde vorher nur beim Hauptmandanten angezeigt. Es ist nun für alle Mandanten an dieser Stelle auffindbar: *Einrichtung » Mandant » Mandanten wählen » Webshop » Shop sperren*.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.



--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.



--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|
|
|

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

====
