= Changelog 9. August 2023
:author: kevin-stederoth
:sectnums!:
:page-index: false
:startWeekDate: 3. August 2023
:endWeekDate: 9. August 2023

// Ab diesem Eintrag weitermachen: https://forum.plentymarkets.com/t/variationssuche-zeigt-falschen-nettobestand-variation-search-showing-wrong-net-stock/732176
// Auch folgenden Eintrag beachten: https://forum.plentymarkets.com/t/auftrags-ui-adressen-editieren-order-ui-editing-addresses/732105
// Auch folgenden Eintrag beachten: https://forum.plentymarkets.com/t/kaufland-sku-anpassungen-fuer-kaufland-marktplaetze-sku-adjustments-for-kaufland-storefronts/731463

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Artikel (Neue UI)

* Die Spaltenbreite in den restlichen Tabellen der neuen Artikel UI ist jetzt konfigurierbar. Für neue User muss sie eventuell einmalig eingestellt werden, wie gewünscht.

[discrete]
=== Aufträge

* Das Versenden von E-Mails steht in der neuen Auftrags-UI jetzt auch als Menüfunktion zur Verfügung.
* Es ist jetzt möglich beim Zurückbuchen von Waren die Variantennummer anzeigen zu lassen.

[discrete]
=== Decathlon

* Im Menü *Einrichtung » Märkte » Decathlon » Einstellungen » Bereich: Versandprofile verknüpfen* wurde die Auswahl *Standardzuordnung* hinzugefügt.
* Bei der Katalogzuordnung für das Feld *Hauptbild* kann ab jetzt *Bild » Alle Bilder » Bilderliste* ausgewählt werden.

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Artikel (Neue UI)

* Der CrossSelling-Typ *Konfigurator* wurde ausgeblendet. Er wurde unbeabsichtigt in der neuen Artikel-UI angezeigt.

[discrete]
=== CRM

* Im Messenger wurden folgende Änderungen vorgenommen:
** *Meine Ordner* ist nun immer sichtbar
** Die Schaltfläche *Neuen Ordner hinzufügen* befindet sich nun im Kontext-Menü von *Meine Ordner*
** *Angeheftete Konversationen* ist nun immer sichtbar
** Die Icons für *Meine Ordner*, *Angeheftete Konversationen* und *Konversation lösen* wurden geändert
** Das Laden von angehefteten Konversationen wurde verbessert

[discrete]
=== Dokumente

* Dokumenttypen die für die Erstellung im DocumentBuilder aktiviert sind können nicht mehr über die UI unter *Aufträge » Fulfillment* generiert werden. Für die betroffenen Dokumenttypen wird hier nun ein Hinweis angezeigt und die Aktion zum Erstellen ist nicht mehr vorhanden.
+
Die Erstellung von Dokumenten für eine Liste von Aufträgen ist über eine Gruppenfunktion in der Auftrags-UI weiterhin möglich. Eine Gruppenfunktion um Dokumente zu einem PDF zusammenzuführen wird in naher Zukunft folgen um hier den gleichen Funktionsumfang sicherzustellen.

[discrete]
=== Netto

Der Katalog von Netto wurde um folgende Funktionen und Felder erweitert:

. Separate kanalspezifische Felder für Netto und Marktkauf:
** Preis
** Provision
** Lieferzeit
** Grundpreis: Verkaufspreis
** Grundpreis: Einheit
** Grundpreis: Menge
** Alter Preis
** Kategorien
. Neue Steuerklasse: 0% (Solarprodukte)
. Neue Felder für EAR-Bestimmungen:
** WEEE_Pflicht
** EAR_Kategorie
** EAR_Marke
** WEEE_Nummer
. Asynchroner Bilderupload: Der Upload der Bilder auf den SFTP in einen Microservice ausgelagert. Dadurch schlägt sich der zeitintensive Upload nicht mehr den täglichen Cron-Prozess nieder und findet nachgelagert zur Übertragung der Produktdatei statt.

Der Nutzung des Katalogs steht damit nichts mehr im Wege.

[IMPORTANT]
.To-Do
======
Um den Katalog zu nutzen, muss man mindestens einen Katalog anlegen, mappen, aktivieren und kann dann unter *Einrichtung » Märkte » Netto eStores » Tab: Einstellungen* über die Optionen *Artikelexport aktivieren* und *Bestandsabgleich aktivieren* und den neuen Auswahlwert *Ja (Katalog)* diese separat umstellen.
======

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Artikel (Neue UI)

* Man kann nun auch mit einem duplizierten Tab der Artikel UI arbeiten.

[discrete]
=== Aufträge

* Die folgenden Korrekturen wurden zur Tabelle der Auftragspositionen und zur Tabelle des Warenkorbs hinzugefügt:
** Die Eigenschaften der Bestellpositionen wurden in der Artikeltabelle und in der Tabelle des Warenkorbs auf der Grundlage der Speicherreihenfolge sortiert. Dies wurde behoben.
** Die Eigenschaften der Auftragspositionen konnten im dritten Schritt der Benutzeroberfläche zum Anlegen eines neuen Auftrags nicht aufgeklappt werden. Dies wurde behoben.

+
Die Korrekturen sind sowohl für die neue Benutzeroberfläche zum Anlegen von Aufträgen als auch für die neue Benutzeroberfläche für Aufträge verfügbar.
* Beim Zurücksetzen des Warenausgangs über die neue Auftrags UI wurde der Benutzer nicht in den Warenbewegungen der Variante angezeigt. Dies wurde behoben.
* In der neuen Auftrags-UI erlaubt die Datumsauswahl bei der Dokumentenerstellung nicht die Eingabe des richtigen Formats für die Lokalisierung. Dies wurde behoben.
* In der Benutzeroberfläche für das Anlegen neuer Aufträge und in der Benutzeroberfläche für das Bearbeiten von Auftragspositionen wurde bei schnellen Änderungen der Artikelmenge mehrerer Artikel die Menge manchmal durch den im Hintergrund ausgeführten Preview-Aufruf zurückgesetzt. Dies wurde behoben und die bearbeitbaren Felder sind nun deaktiviert, während des Aufrufs der Auftragsvorschau.
* Wenn in der neuen Auftrags-UI versucht wird einen Unterauftrag in einem duplizierten Auftrags-Tab zu erstellen, wurde die Erstellung des Kinderauftrags im ersten Auftrags-Tab durchgeführt und nicht in dem, in dem der Prozess gestartet wurde. Dies wurde behoben.
* Wenn man in der neuen Auftrags-UI vom Dashboard zur Auftragsübersicht navigiert und von der Kompaktansicht zur Listenansicht wechselt, erscheint eine weiße Seite. Dies wurde behoben.
* In der neuen Benutzeroberfläche für Aufträge gingen beim Wechsel zwischen der Kompaktansicht und der Listenansicht die Suchparameter verloren. Dies wurde behoben.
* In der neuen Auftrags-UI bekommen Bundleartikel nicht die richtigen Preise und Mehrwertsteuer, wenn die Einstellung *Bundlespositionen im Bestellprozess durch die Basisartikel ersetzen* aktiviert ist. Dies wurde behoben.
* Es kam zu einem Fehler wenn kein Einkaufspreis gesetzt ist. Dieses Verhalten wurde behoben.
* In der neuen Auftrags-UI können die Bookmarks für einen Datumsfilter mit dem Operator *zwischen* jetzt wieder gespeichert werden.
* Das Zahlungs-Widget wird in der neuen Auftrags-UI jetzt auch für Sammelaufträge in den Auftragsdetails angezeigt.
* Verschiedene Buttons, wie z.B. der Button zum Kopieren von Aufträgen, wurden so angepasst, dass bei mehrfachem Drücken keine doppelten Auftäge erzeugt werden.
* Datumsfilter funktioniert nun wieder nachdem man beispielsweise von einer anderen UI wie dem Dashboard zur Auftragsübersicht weitergeleitet wurde.
* Wenn an einem Auftrag ein nicht mehr existierender Transfer-Lagerort verknüpft war, konnte der Auftrag nicht mehr geöffnet werden. Dies wurde behoben.
* Es wurden bei der neuen Auftragsanlage nicht die Attributnamen in der jeweiligen Auftragssprache verwendet. Dies wurde behoben.
* In der Detailansicht der neuen Auftrag UI wurden für das Bearbeiten von Artikel mehr Benutzerrechte abgefragt, als tatsächlich benötigt werden. Dies wurde behoben.
* Beim erstmaligen Öffnen des Dialogs zur Bearbeitung der Eigenschaften von Auftragspositionen oder im zweiten Schritt der Erstellung einer neuen Bestellung ist die Dropdown-Liste der verfügbaren Eigenschaften leer. Dies wurde behoben.
* Beim mehrmaligen Öffnen des Dialogs für die Eigenschaften von Auftragspositionen oder im zweiten Schritt der Erstellung eines neuen Auftrags wurden einige Eigenschaften im Dropdown-Menü mit den verfügbaren Eigenschaften doppelt angezeigt. Dies wurde behoben.

[discrete]
=== CRM

* Beim Einrichten des E-Mail-Kontos ist es nun auch erlaubt, im Feld für den Namen des Absenders Sonderzeichen zu verwenden.
* Bei einigen Anbietern wurde im Messenger bei der Weiterleitung die Groß- und Kleinschreibung der Weiterleitungs-Adressen verändert, weshalb E-Mails nicht importiert werden konnten. Dieses Problem wurde behoben und wird mit neu angelegten Weiterleitungs-Adressen nicht mehr auftreten.
+
[IMPORTANT]
.To-Do
======
Wenn du von dem Problem betroffen warst muss der Posteingang neu angelegt werden, damit du eine neue Adresse erhältst.
======
* Bei einigen Ereignisaktionen in denen EmailBuilder Vorlagen versendet werden sollten wurde nach dem Auslösen die Fehlermeldung `This action is unauthorised` im Log generiert und die Vorlage wurde nicht versendet. Dieses Verhalten wurde behoben.
* Beim Wechseln zwischen zwei Konversationen wurde in manchen Fällen die ausgewählten Tags übernommen. Dieses Verhalten wurde behoben.
* Wenn eine EmailBuilder Vorlage aus der Vorschau von der Auftrags UI heraus versendet wurde kam es in einigen Fällen vor dass die Vorlage ohne HTML-Header und Styling versendet wurde. Dieses Verhalten wurde behoben.

[discrete]
=== Decathlon

* Ein Problem beim Verknüpfen von Versandprofilen wurde behoben.

[discrete]
=== Dokumente

* In den Ausgabeeinstellungen im DocumentBuilder kann über das *Dateiformat* zwischen *PDF*, *XML* und *PDF/A3* gewechselt werden.
+
Neben dem üblichen *PDF* kann hier mittels der Einstellung *PDF/A3* ein PDF erstellt werden, in dem ein XML eingebettet ist. Dieses XML entspricht dem *Factur-X* Standard. Das resultierende *PDF/A3* entspricht dem *ZUGFeRD* Standard. Die Einstellung *XML* erzeugt entsprechend ausschließlich das XML im *Factur-X* Standard.
* In der Nummernkreis-UI wurde folgende Probleme behoben:
** Lieferländer werden bei aktiven Nummernkreisen jetzt angezeigt
** Rechungs- und Lieferländern werden nun in der Übersicht korrekt dargestellt
** Änderung an der Einstellung für *Hochzählen erlauben* führt nun dazu das der Speicherbutton klickbar wird
** Bei dem Wechsel zwischen Nummernkreisen in der UI kommt es nicht mehr dazu das Werte von einem anderen Nummernkreis angezeigt werden
* Wenn in den Auftragseinstellungen einer Vorlage im DocumentBuilder explizit Kundenklassen ausgewählt wurden konnte es zu einem Fehler kommen, da hier die Position einer Kundenklasse anstatt die ID beachtet wurde. Das gleiche Verhalten trat im Filter für Kundenklassen auf.
+
Dies führte zu Problem wenn die Position einer Kundenklasse nicht mit ihrer ID übereinstimmt oder mehrere Kundenklasse die gleiche Position haben. Dies wurde behoben.

--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Artikel (Neue UI)

In der neuen Artikel-UI ist es nun möglich, Artikel- und Variantendaten direkt in der Tabelle zu bearbeiten. Dieser Bearbeitungsmodus beinhaltet zudem eine Undo / Redo Funktionalität und vor dem Speichern werden die Änderungen noch einmal zur Überprüfung angezeigt.

Dieser Bearbeitungsmodus ist in der Standardansicht der Übersicht nicht automatisch vorhanden, sondern muss in einer eigenen Ansicht aktiviert werden.

*Wie greife ich auf den Bearbeitungsmodus zu?*

Dazu müsst ihr eine eigene Ansicht erstellen und konfigurieren:

. Erstellt eine neue Ansicht.
. In der neuen Ansicht, gebt den Button für das Wechseln zum Editiermodus frei.
. Nun könnt ihr in eurer Ansicht zum Bearbeitungsmodus wechseln.

*Welche Daten lassen sich in der Übersicht bearbeiten?*

Steht sofort zu Verfügung:

* Markierung 1
* Markierung 2
* Hersteller
* Variante ist aktiv
* Variantennummer
* Variantenname
* Externe Id
* Position
* Verfügbarkeit (Angezeigte Lieferzeit)

Befindet sich in Entwicklung:

* Barcodes
* Artikelnamen 1, 2 und 3
* Verkaufspreise

*Welche Besonderheiten gibt es?*

* Vererbte Felder und Vererbungsstatus werden als solche im jeweiligen Element sichtbar gemacht.
* Änderungen von vererbbaren Feldern an der Hauptvariante werden für jede aufgelistete zugehörige Variante angezeigt, wenn diese die Vererbung dafür aktiv hat.
* Änderungen in Feldern, die gerade geerbt sind, deaktivieren die Vererbung für dieses Feld.
* Änderungen von Artikeldaten (Markierungen, Name 1, 2, 3 und Hersteller) werden für jede aufgelistete Variante dieses Artikels angezeigt.
* Beim Speichern gibt es eine bestimmte Reihenfolge: Zuerst werden die Hauptvarianten gespeichert, dann alle nicht-Hauptvarianten. Parallel dazu werden die Artikeländerungen gespeichert.

Gespeicherte Artikeländerungen können einen manuellen Refresh erfordern, dass sie nach dem Speichern auch korrekt angezeigt werden. Wir untersuchen dieses unerwünschte Verhalten derzeit.

[discrete]
=== Aufträge

* In der Toolbar der Detailansicht von Aufträgen gibt es jetzt den Button **Warenbestand ermitteln**.
Ausserdem wurde das Icon für die Lagerortzuweisung geändert.
* In der Auftrags-UI können nun Dokumente vom Typ *Benutzerdefiniertes Auftragsdokument* erstellt werden. Dabei stehen folgende Möglichkeiten zur Verfügung:
** Gruppenfunktion in der Übersicht
** Aktion in der Übersicht pro Auftrag
** Dokument-Widget in der Detail-Ansicht eines Auftrages
* In der Kompaktansicht können nun die Farben des Bestellstatus und des Zahlungsstatus als Hintergrundfarbe für die jeweiligen Felder festlegen. Die neue Einstellung finden ihr in den MyView-Einstellungen unter den Feldern *Status* und *Zahlungsstatus*.
* Es ist nun möglich das voraussichtliches Versanddatum der Auftragspositionen in den Listen anzuzeigen und im Bearbeitungsmodus auch zu editieren.
* Es ist jetzt möglich Markierungen über die Gruppenfunktion zu setzen. Das Overlay ist aktuell ohne Farben, diese werden nachgeliefert.

[discrete]
=== Dokumente

* Im DocumentBuilder steht neben der *Menge* einer Artikelposition nun auch die Variable *Menge (ganze Zahl)* zur Verfügung. Diese stellt die Menge ohne Nachkommastellen dar, wenn möglich.
+
Die *Menge* 2.00 würde mit *Menge (ganze Zahl)* mit 2 dargestellt werden, 2.50 hingegen würde unverändert angezeigt werden.
* In den Ausgabeeinstellungen einer Vorlage kann nun das *XML-Format* gewählt werden. Dabei stehen die Formate *X-Rechnung* und *Factur-X-Basic* zur Auswahl. Im Standard ist das XML-Format *X-Rechnung*. Diese Einstellung nimmt Einfluss wenn das *Dateiformat* auf *PDF/A3* bzw. *XML* gestellt ist und kann auch nur in diesen Fällen geändert werden.

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== App

* Die Einstellung *Von Pickliste ausschließen* zur Option *Kommissionierung* im Einstellungsbereich *Versand* einer Variante greift nun auch für die Rollende Kommissionierung in plentyWarehouse. Ist diese Option für die Variante ausgewählt, kann die Variante nun nicht mehr über die rollende Kommissionierung gepickt werden.
+
[IMPORTANT]
.Achtung
======
Artikel die in von der Rollenden Kommissionierung ausgeschlossen werden, dürfen keinen Bestand führen, da es ansonsten nicht möglich ist den Warenausgang vom Transfer-Lagerort zu buchen. Artikel die Bestand führen, müssen also wie bisher auch gepickt werden.
======

[discrete]
=== Dokumente

* Im DocumentBuilder wird der Vorlagenname von Standardvorlagen ab sofort in Systemsprache angelegt, bisher war dieser immer in Englisch.
* Die bestehende Variable `Einheit der Variante` beinhaltet ab jetzt ausschließlich die Einheit selbst ohne informationen über die Menge. Zusätzlich wurden die Variable `VPE` und `VPE * Artikelmenge` äquivalent zu den alten Dokumenteinstellungen eingeführt.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Aufträge

* Das Ticket-Widget wurde für Gastbestellungen nicht angezeigt. Das wurde behoben.
* In der neuen Auftrags-UI wird der Rabatt zurückgesetzt, wenn ein neuer Artikel hinzugefügt wird oder wenn die gültigen Verkaufspreise aktualisiert werden. Dies wurde behoben.

[discrete]
=== MyView

* Im Texteditor in MyViews konnte es beim Scrollen in Dropdowns dazu kommen, dass dies nicht wie erwartet funktioniert hat, sowie dass sich Dropdowns überlappen. Dieses Verhalten wurde nun behoben.

[discrete]
=== plentyBI

* Wurde die Kennzahl *Artikel unter Meldebestand (Live)* innerhalb eines Elements vom Typ *Tabelle* auf dem Dashboard dargestellt, funktionierte beim Klicken auf die Tabelleinträge in der Spalte *Dimension* die Weiterleitung in das Tab *Waren » Warenbestände* des entsprechenden Lagers nicht mehr. Dieses Verhalten wurde behoben, sodass diese Links nun wieder ordnungsgemäß funktionieren.

[discrete]
=== Prozesse

* Es konnte vorkommen das die Prozessen zum stillstand kommen wenn man in der Subaktion *Speichern / Drucken* die Sammeldokumente aktiviert hat. Dieser Fehler wurde behoben.

--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|link:https://marketplace.plentymarkets.com/uniservaddresscleansing_6869[Adressprüfung und Adresskorrektur mit Uniserv^]
|2.0.20
|-

|link:https://marketplace.plentymarkets.com/elasticexportidealode_4723[idealo.de^]
|3.4.10
|-

|link:https://marketplace.plentymarkets.com/metro_6600[Metro^]
|2.3.6
|-

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

====
