= Changelog 28. Juni 2023
:author: kevin-stederoth
:sectnums!:
:page-index: false
:page-aliases: ROOT:changelog.adoc
:startWeekDate: 22. Juni 2023
:endWeekDate: 28. Juni 2023

// Ab diesem Eintrag weitermachen: LINK EINFÜGEN

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Artikel

* Du kannst in der neuen Artikel-UI jetzt nach der verknüpften Preiskalkulation filtern.

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== CRM

* Das Tag *Testphase* wurde am Menüpunkt *CRM » Messenger* entfernt. In diesem Zuge wurde am Menüpunkt *CRM » Ticketsystem* das Tag *Veraltet* hinzugefügt.

[discrete]
=== OTTO Market

* Die Intervalle der Cache-Generierung für OTTO Market Kataloge wurden angepasst. Anstatt jede Stunde werden Caches nur noch zwischen 7:00 und 23:00 im Intervall von 2h und zwischen 0:00 und 1:00 im Intervall von 20min aktualisiert. Die Intervalle sind mögliche Startzeitpunkte, es kann jedoch zu Verzögerungen kommen. Durch diese Änderung werden redundante Generierungen reduziert.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Aufträge

* In der neuen Auftrags-UI wurde beim Entfernen des Datumsfilterchips in der Übersichtstabelle der Filter immer noch mit der Suchanfrage gesendet. Dies wurde behoben.

[discrete]
=== Fulfillment

* Nach der Anmeldung einer Exportsendung mit DHL *Warenpost International* war das Icon für Exportdokumente aktiv, aber es zeigte nach einem Klick nur ein leeres PDF an. Wenn Exportangaben notwendig sind, befinden sich diese jedoch auf dem Versandlabel direkt (CN22).
+
Weitere Exportdokumente wurden in dem Fall von DHL erstellt oder an uns gesendet, daher wird das Exportdokument-Icon nun ausgegraut, wenn für eine Exportlieferung keine Exportdokumente verfügbar sind.

--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.



--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|
|
|

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

====
