= Changelog 1. März 2023
:author: kevin-stederoth
:sectnums!:
:page-index: false
:page-aliases: ROOT:changelog.adoc
:startWeekDate: 23. Februar 2023
:endWeekDate: 1. März 2023

// Ab diesem Eintrag weitermachen: https://forum.plentymarkets.com/t/neue-auftrags-ui-testphase-textfarbe-und-hintergrundfarbe-fuer-die-auftragsnotizen-hinzugefuegt-new-order-ui-test-phase-text-color-and-background-color-added-for-the-order-notes/713517

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Artikel (Neue UI)

* In der Variantenansicht ist es nun möglich, sowohl die verknüpften Kategorien als auch die Liste der Kategorien beim Hinzufügen zu sortieren. Die entsprechenden Einstellungen sind im Editiermodus der Ansicht am Kategorie-Element zu finden.
** Sortierung in der Tabelle nach:
*** Name der Kategorie
*** Position der Verknüpfung
*** Position der Kategorie
*** ID der Kategorie
** Sortierung im Picker:
*** Name der Kategorie
*** Position der Kategorie

[discrete]
=== CRM

* Im Messenger wurde der Filter *Absender:in* hinzugefügt.

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== CRM

* Ab sofort wird im Messenger nur noch neben dem Posteingang die Anzahl der ungelesenen Nachrichten angezeigt. Die Anzahl der ungelesenen Nachrichten wird in Echtzeit angezeigt. Mit einem Klick auf *Neue Nachrichten* sieht man dann alle ungelesenen Nachrichten auf einen Blick. Du siehst ab sofort, wenn eine andere Benutzer:in im System auf eine Nachricht antwortet.

[discrete]
=== Kaufland

* Das alte Menü zur Einrichtung von Kaufland wurde entfernt und vollständig durch das neue Einrichtungsmenü ersetzt. Ab jetzt richtest du den Marktplatz im Menü *Einrichtung » Märkte » Kaufland » Einstellungen* ein.

[discrete]
=== plentyShop LTS

Die Anzahl der maximalen Einträge pro Sitemap für plentyShops wurde von 50000 auf 25000 reduziert, da es aufgrund der Dateigröße der Sitemaps vermehrt zu Ablehnungen seitens Google kam.

Bitte überprüft, ob ihr in den von euch verwendeten SEO-Tools (bspw. Google Search Console) die allgemeine Sitemap hinterlegt habt (www.beispieldomain.de/sitemap.xml) oder ob ihr separate sitemap.xml Dateien (bspw. `Sitemap_item.xml`, `Sitemap_item_2.xml`, etc.) hinterlegt habt. Falls ihr nur die allgemeine Sitemap hinterlegt habt, besteht eurerseits kein weiterer Handlungsbedarf.

Falls ihr in euren SEO-Tools separate Sitemap-Dateien gelistet habt, kann es sein, dass sich die Anzahl der Sitemap-Dateien durch die Reduktion der Einträge pro Sitemap erhöht. In diesem Fall solltet ihr die hinzugekommenen Sitemap-Dateien in euren SEO-Tools ergänzen, um sicherzustellen, dass diese Seiten weiterhin wie gewünscht indexiert werden können.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Amazon

* Durch eine Änderung seitens Amazons im Auftragsbericht, konnte es dazu kommen, Aufträge mit stornierten Auftragspositionen importiert wurden, welche wir normalerweise ignorieren. Bisher wies Amazon die Menge 0 bei diesen Auftragspositionen aus und hat dies nun geändert und weist stattdessen einen Preis von 0 aus. Wir prüfen jetzt, ob eins von beidem zutrifft und ignorieren die Auftragsposition in beiden Fällen.

[discrete]
=== Aufträge

* In der neuen Auftragsanlage konnte der letzte Schritt oben über den Stepper erreicht werden, obwohl die Warenkorbtabelle ungültige Verkaufspreise enthielt. Dies wurde behoben.
* In einer Retoure war es möglich, für eine Auftragsposition die komplette Menge vom Hauptauftrag zurückzubuchen. Dies wurde nun auf die Menge in der Retoure beschränkt.
* In der Detailansicht eines Auftrags funktionierte die Suche nach einem Status nicht richtig. Dies wurde behoben.

[discrete]
=== Fulfillment

* Verschiedene Fehler, die im Versand-Center 2.0 aufgetreten sind, wurden behoben:
** Kritische Fehlermeldungen, die u.a. bei der Versandanmeldung angezeigt wurden
** Fehler beim Herunterladen von Versandlabels für 50 oder mehr Aufträge (Dokumente wurden nicht korrekt erstellt)
** Sonderzeichen (Umlaute und ß) wurden nicht korrekt in die Polling-Datei für DPD Delisprint importiert

'''

[discrete]
== Gelöscht

Folgende Funktionalität wurde in den letzten 7 Tagen auf *{version}* entfernt.

[discrete]
=== Fulfillment

* Die DHL Freight-Anwendung ist obsolet und wurde daher aus dem Menü entfernt.

--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Artikel (Neue UI)

* In der Variantenansicht ist es nun möglich, sowohl die verknüpften Lieferanten als auch die Liste der Lieferanten beim Hinzufügen zu sortieren. Die entsprechenden Einstellungen sind im Editiermodus der Ansicht am Lieferanten-Element zu finden.

[discrete]
=== CRM

* Ab sofort kannst du im Messenger Typen und Status festlegen. Zu den Typen und Status gelangst du im Messenger mit einem Klick auf *Einstellungen » Typen und Status*. Du wirst weitergeleitet in das neue Menü *Einrichtung » CRM » Messenger » Typen und Status*, wo du dann die Einstellungen für die Typen und Status vornehmen kannst.
+
Sobald du Typen und Status definiert hast, kannst du über das Kontextmenü der Konversation Typen und Status zuweisen und den Typ und den Status in der Übersicht anzeigen. Außerdem kannst du nach Typen und Status im Filterbereich suchen.
* Aufgrund der Geoblocking-Verordnung sind für Rechnungsadressen im Kontaktdatensatz automatisch alle EU-Länder freigeschaltet, wenn die Rechnungsadresse auf *Ja* oder *Ja, primär* gesetzt ist und wenn die Lieferadresse auf *Nein* gesetzt ist. Auch im Bereich *Bank* eines Kontaktdatensatzes sind nun automatisch alle EU-Länder in der Länderliste enthalten. Weitere Informationen zum Geoblocking findest du auf der Seite der link:https://www.bundesnetzagentur.de/DE/Fachthemen/Digitalisierung/Internet/Geoblocking/start.html[Bundesnetzagentur^].

[discrete]
=== Shopzilla

Ab sofort kannst du Artikeldaten mit einem Katalog an Shopzilla exportieren. Das Marktplatz-Format für Shopzilla findest du jetzt im Menü *Daten » Kataloge*.

Bisher war der Export von Artikeldaten an Shopzilla nur über den Elastischen Export möglich. Beim Wechsel auf den Artikeldatenexport mit Katalogen solltest du deshalb Folgendes beachten:

* Merkmale und Freitextfelder können für den Katalogexport nicht mehr verwendet werden. Prüfe deshalb, welche Merkmale du aktuell für Shopzilla verwendest. Erstelle Eigenschaften für alle Merkmale, die du weiterhin benötigst.
* Beim Wechsel solltest du deinen alten Elastischen Export exakt in dem neuen Katalog nachbauen, damit der Artikelexport weiterhin funktioniert. Ordne also alle Datenfelder so zu, wie sie auch im Elastischen Export an den Marktplatz übertragen wurden. Wenn du bestimmte Datenfelder anders als bisher zuordnest, werden möglicherweise beim Export neue Artikel erstellt.
* Wie du einen Katalog für Shopzilla einrichtest, erfährst du auf der Handbuchseite xref:maerkte:shopzilla.adoc#catalogue-export[Shopzilla^].

[NOTE]
.Hinweis
======
Der Elastische Export und die Exportformate werden nicht mehr weiterentwickelt. Wir empfehlen dir deshalb, schon jetzt Kataloge zu erstellen.
======

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Rechte

Die Eigner-Rechte ziehen um zu den API-Nutzungsrechten. Die Eigner-Rechte werden in bestimmten Bereichen immer aktiv sein wenn:

[cols=2]
|======
|Aktives Recht |Eigner

|*Aufträge*
|
*Auftrag-Eigner:in*

|
*Aufträge*
_oder_
*Aufträge » Scheduler*
|
*Scheduler-Eigner:in*

|*Blog*
|
*Blog-Eigner:in*

|
*CRM*
_oder_
*CRM » Kontakte*
|
*Kontakt-Eigner:in*

|
*CRM*
_oder_
*CRM » Ticket*
|
*Ticket-Eigner:in*

|
*Warenbestände*
_oder_
*Warenbestände » Wareneingänge*
|
*Wareneingang-Eigner:in*
|======

Auch wenn die Nutzer:in Admin-Rechte besitzt, ist sie in allen diesen Bereichen Eigner:in.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Aufträge

* In der neuen Auftrags-UI (Testphase) wurden die folgenden Dinge in der Übersichtstabelle behoben:
** Die Werte in der Spalte *Lieferland* waren in der Übersichtstabelle nicht sichtbar. Dies wurde behoben.
** Die Werte in der Spalte *Bezahlter Betrag (%)* waren teilweise inkorrekt. Dies wurde behoben.
** In der Spalte *Zahlungsstatus* wurden die Daten nicht richtig angezeigt. Dies wurde behoben.

--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|link:https://marketplace.plentymarkets.com/enderecoaddressautocomplete_6622[Adressprüfung und Adresskorrektur mit Endereco^]
|2.1.3
|-

|link:https://marketplace.plentymarkets.com/uniservaddresscleansing_6869[Adressprüfung und Adresskorrektur mit Uniserv^]
|2.0.11
|-

|link:https://marketplace.plentymarkets.com/io_4696[IO^]
|5.0.59
|-

|link:https://marketplace.plentymarkets.com/limango_7023[limango^]
|1.4.28
|-

|link:https://marketplace.plentymarkets.com/klarna_6731[Klarna^]
|2.4.9
|-

|link:https://marketplace.plentymarkets.com/mollie_6272[Mollie^]
|2.8.23
|-

|link:https://marketplace.plentymarkets.com/paypal_4690[PayPal Checkout^]
|6.0.22
|-

|link:https://marketplace.plentymarkets.com/ceres_4697[plentyShop LTS^]
|5.0.59
a|Aufgrund von Änderungen an bestehenden Widgets müssen die ShopBuilder-Inhalte im Menü *CMS » ShopBuilder* über die Schaltfläche Inhalte neu generieren aktualisiert werden.

Im Zuge des Releases von Ceres 5.0.59 gab es Änderungen an Template-Dateien, die für Theme-Entwickler:innen relevant sind. Die Verlinkung führt direkt zu der umgesetzten Änderung in den entsprechenden Dateien.

* link:https://github.com/plentymarkets/plugin-ceres/pull/3387/files#diff-9f438954b9f177761379a8b382eea014077ec743060583796ac4f9aaed3d3003[resources/views/Widgets/Common/ImageBoxWidget.twig^]
* link:https://github.com/plentymarkets/plugin-ceres/pull/3417/files/#diff-969624803dfeb696a58e16de0d95c285a458ec83a615026882d9b1e65386935b[resources/views/Customer/Components/AddressSelect/AddressSelect.twig^]
* link:https://github.com/plentymarkets/plugin-ceres/pull/3417/files/#diff-ac3499fe39e67fd08b24086c79be769096e1ab58885fd4a233847c502b94b317[resources/views/Checkout/Components/PlaceOrder.twig^]

|link:https://marketplace.plentymarkets.com/trackingmanager_54743[TrackingManager^]
|1.3.1
|-

|link:https://marketplace.plentymarkets.com/plentyshopltsmodern_55193[plentyShop LTS Modern^]
|1.0.8
|-

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

====
