= Changelog 8. November 2023
:author: kevin-stederoth
:sectnums!:
:page-index: false
:page-aliases: ROOT:changelog.adoc
:startWeekDate: 2. November 2023
:endWeekDate: 8. November 2023

// Ab diesem Eintrag weitermachen: LINK EINFÜGEN

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== CRM

* Im Menü *Einrichtung » CRM » Job-Titel* wird in der Übersicht nun neben dem deutschen Namen auch der englische Name des Job-Titels angezeigt, sofern du beide Sprachen gespeichert hast. Auch beim Erstellen eines neuen Job-Titels sind ab sofort die Felder für die deutsche und englische Sprache sofort sichtbar, ohne dass du auf das Plus-Symbol zum Hinzufügen der englischen Sprache klicken musst.
* Ab sofort stehen dir im EmailBuilder dir die Variablen für die Eigenschaften der Kontakte und für die Eigenschaften der Artikel zur Verfügung.
** Alle kontaktbezogenen Eigenschaften findest du im EmailBuilder unter *Kontakte* in der Unterkategorie *Eigenschaften*. Hier werden alle Variablen angezeigt, für die du Eigenschaften für den Bereich *Kontakt* im Menü *Einrichtung » Einstellungen » Eigenschaften* erstellt hast.
** Alle artikelbezogenen Eigenschaften findest du im EmailBuilder unter *Auftrag / Auftragspositionen (nur für Artikellisten-Widget)* in der Unterkategorie *Eigenschaften*. Hier werden alle Variablen angezeigt, für die du Eigenschaften für den Bereich *Artikel* im Menü *Einrichtung » Einstellungen » Eigenschaften* erstellt hast.
* Im Menü *Einrichtung » CRM » Messenger » Automatisierung* wurden die folgenden Filter hinzugefügt:
** Betreff enthält
** Absender-E-Mail enthält

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Aufträge

* Der Button zum Warenausgang buchen wird jetzt immer angezeigt, auch wenn der Warenausgang gebucht ist, dann gibt es einen farblichen Hinweis, um zu sehen, dass dieser gebucht ist.
* Der farbliche Hinweis war vorher nur am Warenausgang zurückbuchen Button zu sehen und wurde dort entfernt.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Artikel (Neue UI)

* Der in der Lagerkonfiguration eingetragene Meldebestand wird nun korrekt im Bestandsbereich einer Variante angezeigt.

[discrete]
=== Aufträge

* Beim Drücken von *Enter* in den Auftragsdetails in bestimmten Feldern öffnete sich ein Overlay falsch, dies ist nun behoben.
* In der Auftrag UI wurde beim Aktualieren eines Auftrags nicht die Einstellung für den betroffen Statusbereich (4.x) für die Warenbestandsautomatik beachtet. Dies wurde behoben.

[discrete]
=== CRM

* Wenn ein Messenger-Ereignis eine E-Mail sendete (Aktionen *Antwort hinzufügen* oder *E-Mail senden*), enthielten die E-Mail-Variablen für Auftrag und Kontakt keine Werte, obwohl die Konversation die richtigen Relationen hatte. Dieses Verhalten wurde nun behoben.

[discrete]
=== Ereignisaktionen

* Es ist in den Ereignissen vorgekommen das man Tags nicht mehr löschen konnte aus den Bestehenden eingerichteten Filtern und Aktionen. Dieser Fehler wurde behoben.

--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.



--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|
|
|

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

====
