= Changelog 31. Mai 2023
:author: kevin-stederoth
:sectnums!:
:page-index: false
:page-aliases: ROOT:changelog.adoc
:startWeekDate: 25. Mai 2023
:endWeekDate: 31. Mai 2023

// Ab diesem Eintrag weitermachen: LINK EINFÜGEN

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Aufträge

* In der neuen Auftrags-UI sind die Tabellenüberschriften und die Suchkomponente jetzt beim Scrollen durch die Auftragsliste fixiert.
* In der neuen Auftrags-UI werden die Preise mit zwei Dezimalstellen angezeigt, und der Tooltip wird bei Bedarf mit vier Dezimalstellen angezeigt.
* Der Buchstabe des Mehrwertsteuersatzes wird jetzt immer mit angezeigt bei den Auftragspositionen.
* In der Auftragsübersicht wurde die Möglichkeit geschaffen, über die MyView-Einstellungen die vorgeschlagenen Filter in der Autovervollständigung selbst zu konfigurieren.

[discrete]
=== CRM

* In den Kontaktoptionen im Menü *CRM » Kontakte* steht dir unter Zusatz der Eintrag *Follow-up-Datum* zur Verfügung. Hier kannst du ein Datum und eine Uhrzeit zur Wiedervorlage speichern. Mit einem Klick auf *Zum Kalender hinzufügen* öffnet sich dein Google Kalender, und du kannst ein Meeting an diesem Follow-up-Datum als Erinnerung in deinem Google-Kalender erstellen.
** In den Filtern wurden die Felder *Follow-up-Datum von* und *Follow-up-Datum bis* hinzugefügt.
** Außerdem kannst du über die Funktion *Spalten konfigurieren* oben rechts das *Follow-up-Datum* aus den Kontaktoptionen in der Übersicht anzeigen lassen und die Übersicht auf- oder absteigend anhand des Follow-up-Datums sortieren.
* Im *Aufträge*-Portlet des Kontaktdatensatzes im Menü *CRM » Kontakte* wurde ein Filter hinzugefügt, mit dem du nach einem oder mehreren Auftragstypen suchen kannst.

[discrete]
=== Kontoverwaltung

* Ab heute kannst du Rechte an Rollen vergeben, die Nutzer:innen MyView-Ansichten erstellen, bearbeiten und löschen lassen. Diese Rechte sind mit dem *Betrachten*-Recht der jeweiligen Benutzeroberfläche der MyView-Ansicht verbunden. Diese neuen Rechte heißen *Ansichten* und du findest sie im einfachen Modus ganz oben.

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Prozesse

* Beim Wechsel von Tabs in den Prozessen konnte es passieren, dass der Inhalt der Prozesse nicht angezeigt wurde. Dieses Verhalten wurde behoben.

--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.



--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|
|
|

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

====
