= Changelog 4. Oktober 2023
:author: kevin-stederoth
:sectnums!:
:page-index: false
:page-aliases: ROOT:changelog.adoc
:startWeekDate: 28. September 2023
:endWeekDate: 4. Oktober 2023

// Ab diesem Eintrag weitermachen: LINK EINFÜGEN

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Aufträge

* In der Zahlungshistorie im Historie-Widget werden zugeordnete und nicht zugeordnete Zahlungen farblich gekennzeichnet.
* Beim Ändern des Versandprofils im Bereich Auftragsdetails wirst du ab jetzt per Aufforderung gefragt, ob du die Versandkosten für den Auftrag entsprechend des neu gewählten Versandprofils aktualisieren möchtest.

[discrete]
=== CRM

* Ab sofort steht dir im Menü *CRM » Kontakte* der Filter *Ist Gast* zur Verfügung. Wenn du im Filter *Ja* wählst, werden alle Gastbestellungen angezeigt. Wenn du *Nein* wählst, werden alle Nicht-Gastbestellungen, also reguläre Kontaktdatensätze, angezeigt.
* Im EmailBuilder wurde im Variablenbereich *Messenger* die Variable *Abgekürzte ID der Konversation* hinzugefügt. Diese Variable gibt die abgekürzte ID aus dem Messenger aus.
* Ab sofort steht dir eine Vorschaufunktion für Anhänge im Messenger zur Verfügung. Mit einem Klick auf die angehängte Datei öffnet sich der Anhang in einem neuen Fenster, über das du den Anhang entweder herunterladen oder wieder schließen kannst.
* Im EmailBuilder kannst du ab sofort die Ordner und Vorlagen jeweils auf- oder absteigend nach ID, Name oder Erstelldatum sortieren. Sortiert wird erst anhand der Ordner, dann nach Vorlagen, Header-Vorlagen und Footer-Vorlagen. Wenn du *ID* als Sortierwert wählst, werden die Ordner anhand des Namens sortiert, weil diese keine ID haben.
* Der neue Menüpunkt *Einrichtung » CRM » Job-Titel* ist nun verfügbar. 25 Job-Titel sind bereits standardmäßig in deinem System vorhanden. Du kannst natürlich weitere Job-Titel in Deutsch und Englisch speichern und vorhandene Job-Titel löschen.
+
Das Menü hat die bekannten Standard-Features wie sortieren, suchen, Filter speichern und eine Aktion zum Löschen einzelner Job-Titel.
+
Für dieses neue Feature wurde auch das neue Benutzerrecht *CRM > Job-Titel* hinzugefügt.
+
Die im neuen Menü *Einrichtung » CRM » Job-Titel* gespeicherten Job-Titel kannst du dann im Bereich *Kontaktdetails* des Kontaktdatensatzes über MyView hinzufügen und auswählen. Du kannst die Spalte *Job-Titel* auch in der Kontaktübersicht hinzufügen und nach Job-Titeln im Filterbereich suchen.

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Amazon

* Zur Verbesserung der Nachvollziehbarkeit bei Problemfällen wurden die Logs des Amazon MFN-Auftragsimports ergänzt oder verbessert. Die Logs können zukünftig unter anderem nach folgenden Referenzen durchsucht werden:
** `legacyAccountId`
** `orderId`
** `externalOrderId`
** `reportId`
** `sellerId`
** `processId`

[discrete]
=== Aufträge

* Das Historie-Widget lädt die Zahlungshistorie nicht mehr standardmäßig, damit die UI schneller lädt. Die Zahlungshistorie, kann mit einem klick auf den neuen Button geladen werden.

[discrete]
=== POS

* Aufträge, die sich im Quellstatus für die Funktion *Rollende Kommissionierung* befinden, aber keine Artikel enthalten, die gepickt werden können, werden nun in den Fehlerstatus verschoben. Gleichzeitig werden diese Aufträge automatisch mit einer Auftragsnotiz versehen.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Aufträge

* Die Spalte *Regulärer Bruttopreis* aus der Auftragspositionstabelle hat in der Übersicht und der Detailansicht gefehlt. Diese wurde hinzugefügt.
* Beim Hinzufügen von Tags in den Auftragsdetails, wurde der Tag-Name erst nach dem Speichern des Auftrags angezeigt. Dies wurde behoben.
* Bei der Nutzung von Templates in der Auftragserstellung zeigte sich folgendes Verhalten: Auch wenn das Template so angelegt wurde, dass eine bestimmte Variante mehrfach bestellt werden sollte, wurde diese Variante in dem erstellten Auftrag nur einmal hinzugefügt. Dieses Verhalten wurde behoben.
* Es wurde eine Classic Ansicht für Auftragstyp: *Auftrag* hinzugefügt.
* In den Details der Auftrags-UI wurden längere Namen für Zahlungsarten falsch angezeigt. Dies ist nun behoben.

[discrete]
=== CRM

* In der Kontakt-UI im Bereich *Adressen* fehlte die Übersetzung der Tooltips für die Buttons *Neue Rechnungsadresse ableiten* und *Neue Lieferadresse ableiten*. Dieses Verhalten wurde behoben.
* Wenn man eine Konversation aus einem Auftrag oder aus dem Kontakt-Portlet heraus begonnen hat, war es möglich, den Empfänger, der automatisch gewählt war, zu entfernen. Dieser Empfänger wurde jedoch immer noch berücksichtigt, wenn man nach dem Entfernen des Empfängers eine E-Mail versendet hat. Dieses Verhalten wurde behoben. Es ist ab sofort nicht mehr möglich, den Empfänger zu entfernen.
* Die Nachrichtenvorschau hat unnötige Zeilenumbrüche angezeigt. Dieses Verhalten wurde behoben.

Im EmailBuilder wurden die folgenden Variablen und twig expressions als reiner Text generiert und nicht als klickbare Links. Die generierten Werte sind ab sofort klickbar.

Die Variablen wurden geändert. Die alten Variablen funktionieren weiterhin korrekt in bestehenden Vorlagen, aber sie können nicht mehr in neuen Vorlagen eingefügt werden.

[cols="3"]
|======
|Variable |Alt |Neu

|URL zum Artikel
|`{{ orderItem.formattedLink }}`
|`{{ orderItem.formattedLinkNew \| raw }}`

|DHL Retoure Online QR-Code URL
|`{{ order.formattedGeneral.DHLRetoureOnlineQRCodeURL }}`
|`{{ order.formattedGeneral.DHLRetoureOnlineQRCodeURLNew \| raw }}`

|URL zur Auftragsübersicht
|`{{ globals.links.linkCheckout }}`
|`{{ globals.links.linkCheckoutNew \| raw }}`

|URL zum Warenkorb
|`{{ globals.links.linkBasket }}`
|`{{ globals.links.linkBasketNew \| raw }}`

|URL zu den Geschäftsbedingungen
|`{{ globals.links.linkTermsConditions }}`
|`{{ globals.links.linkTermsConditionsNew \| raw }}`

|URL zum Webshop
|`{{ globals.links.linkWebstore }}`
|`{{ globals.links.linkWebstoreNew \| raw }}`

|URL zum neuen Passwort
|`{{ globals.links.linkNewPassword }}`
|`{{ globals.links.linkNewPasswordNew \| raw }}`

|URL zum Ändern des Passworts
|`{{ globals.links.linkChangePassword }}`
|`{{ globals.links.linkChangePasswordNew \| raw }}`

|URL zum Bestätigen der E-Mail-Adresse
|`{{ globals.account.newCustomerEmail }}`
|`{{ globals.account.newCustomerEmailNew \| raw }}`

|URL zur Bestätigung des Newsletter-Abonnements
|`{{ newsletter.formattedConfirmUrl }}`
|`{{ newsletter.formattedConfirmUrlNew \| raw }}`

|Ticket-URL
|`{{ ticket.formattedUrl.url }}`
|`{{ ticket.formattedUrl.urlNew \| raw }}`

|Ticket-Backend-URL
|`{{ ticket.formattedUrl.backendUrl }}`
|`{{ ticket.formattedUrl.backendUrlNew \| raw }}`
|======


--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.



--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|
|
|

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

====
