= Changelog 11. Oktober 2023
:author: kevin-stederoth
:sectnums!:
:page-index: false
:page-aliases: ROOT:changelog.adoc
:startWeekDate: 5. Oktober 2023
:endWeekDate: 11. Oktober 2023

// Ab diesem Eintrag weitermachen: LINK EINFÜGEN

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Aufträge

* In der Auftragsübersicht erscheint nach dem Anklicken der Schaltfläche zum Ändern des Tabellenstils (Kompaktansicht / Listenansicht aktivieren) eine Bestätigungsmeldung, in der um die Bestätigung der Aktion gebeten wird. Die Änderung wird erst nach Betätigung der Schaltfläche Bestätigen durchgeführt.

[discrete]
=== CRM

* Im Menü *Einrichtung » CRM » Messenger » Automatisierung* wurde in *Automatisierungen* vom Typ *Ereignisbasiert* der Filter *Job-Titel des Kontakts* hinzugefügt.

[discrete]
=== Dokumente

* Ab jetzt stehen folgende neuen Variablen im DocumentBuilder zur Verfügung:
** *Auftrag*: neue Variablen für benutzerdefinierte Eigenschaften (ID >1000)
** *Auftrag » Kundenwunsch*: Mit dieser Variable können Kundenwünsche, die für einen Auftrag erfasst wurden, auf per Vorlage generierten Dokumenten angegeben werden.
** *Auftrag » Treueprogramm*: Mit der neuen Variable kann der Namen eines im Auftrag hinterlegten Treueprogramms auf Dokumenten angegeben werden, die über die Vorlage generiert wurden.
** *Auftragsposition*:  neue Variablen für benutzerdefinierte Eigenschaften (ID >1000)
** *Auftragsposition » GesamtRabattBrutto*
** *Auftragsposition » GesamtRabattNetto*
** *Auftragsposition » RabattBrutto*
** *Auftragsposition » RabattNetto*
** *Auftragsposition » UVP*
** *Gesamtgewicht*: Diese Variable zeigt das Gesamtgewicht des Auftrags an.
* Du hast jetzt Variablen für deine Eigenschaften in DocumentBuilder. Du musst nur sicherstellen, dass du in den Sichtbarkeitseinstellungen der Eigenschaft *Anzeige auf PDF-Dokumenten* aktiviert hast.

[discrete]
=== Fulfillment

* Option zum De-/Aktivieren der Erstellung einer Auftragsnotiz nach Retourenanmeldung. Unter *Einrichtung » Aufträge » Einstellung > Retouren* kannst du nun bestimmen, ob eine Auftragsnotiz nach Anmeldung einer Retoure erstellt werden soll. Die vorausgegangene Anpassung war im standardmäßig aktiv, welches wir beibelassen haben.

[discrete]
=== Import

* Im Import-Typ *Kontakte, Firmen und Adressen* wurde im Zuordnungsfeld *Kontakt* die Option *Job-Titel-ID* hinzugefügt.

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Artikel (Neue UI)

* Der Bilderupload in der neuen Artikel-UI findet nun nacheinander statt. Dadurch kann es nicht mehr passieren, dass unterschiedliche Bilder die selbe URL bekommen.
* Die Werkzeugleiste wurde nach dem Öffnen der MyView-Einstellungen manchmal nicht angezeigt. Dieses Verhalten haben wir korrigiert.

[discrete]
=== Aufträge

* In der Auftragssuche der Auftrag UI wurde der Filter *Herkunft* unter Umständen nicht korrekt angezeigt. Dies wurde behoben.
* In der neuen Auftrags-UI waren einige Spalten aus der Tabelle der Auftragspositionen nicht sichtbar, weil das Styling für die Tabellenspalten fehlte. Dies wurde behoben.

[discrete]
=== CRM

* Bei einigen EmailBuilder-Vorlagen hatte die empfangene E-Mail bei der Vorschau in der Auftrags-UI und beim anschließenden Versand einen anderen Zeilenabstand als beim direkten Versand oder beim Versand aus Ereignissen. Dieses Verhalten wurde behoben.

[discrete]
=== Dokumente

* Die Variablen der Gruppe Zahlungsbedingungen funktionieren jetzt insofern korrekt, als dass, wenn ihr Wert gleich 0 ist, der Widget sie als leer erkennt und keinen entsprechenden Inhalt im Dokument anzeigen lässt.

[discrete]
=== plentyBI

* Die Kennzahl *Aufträge (Live)* hat das Ergebnis `0` angezeigt, wenn der Filter *Lager* innerhalb der Kennzahlkonfiguration verwendet wurde. Dieses Verhalten wurde behoben, sodass wieder korrekte Ergebnisse angezeigt werden.

--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.



--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|
|
|

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

====
