= Changelog 15. November 2023
:author: kevin-stederoth
:sectnums!:
:page-index: false
:page-aliases: ROOT:changelog.adoc
:startWeekDate: 9. November 2023
:endWeekDate: 15. November 2023

// Ab diesem Eintrag weitermachen: LINK EINFÜGEN

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Aufträge

* In der Übersicht der Auftrags-UI ist das Abzeichen mit der Anzahl der Notizen jetzt grün.

[discrete]
=== CRM

* Ab sofort steht dir für jede Konversation im Messenger eine Konversationshistorie zur Verfügung. Du kannst die Historie über das Drei-Punkte-Menü in der Übersicht und über das Drei-Punkte-Menü in der geöffneten Konversation aufrufen.
+
Du siehst in der Historie den alten und den neuen Wert sowie das Datum und die Uhrzeit der Änderung und den Benutzer oder die Automatisierung, die die Änderung ausgelöst hat.
* Ab sofort stehen dir im EmailBuilder dir die Variablen für die Adressoptionen aus der Rechnungsadresse und aus der Lieferadresse zur Verfügung. Du findest die neue Variablenliste unter *Kontakte > Adressoptionen*.

[discrete]
=== Dokumente

* Im Editor des Document Builders sind die folgenden Funktionen nun für das Code-Widget verfügbar:
** Das Code-Widget kann wie die anderen Widgets per Drag & Drop an die gewünschte Stelle im Editor gezogen werden.
** Auf der linken Seite ist nun eine Liste der Variablen verfügbar, sobald man in das Widget geklickt hat.
** Die Variablen können überall dort platziert werden, wo sich der Cursor befindet, indem einfach auf die gewünschte Variable in der Liste auf der linken Seite geklickt wird.
** Die Schaltfläche „Speichern“ in der Toolbar oben wird aktiviert, sobald Änderungen vorgenommen wurden.

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Artikel (Neue UI)

* Der Tag Name wurde in der Übersicht nicht immer komplett angezeigt, wenn er zu lang gewesen ist. Dieses Verhalten haben wir korrigiert.

[discrete]
=== Aufträge

* Die Verkaufspreise wurden in der Auftrag UI bisher nicht nach der Position sortiert. Dies wurde behoben.

[discrete]
=== CRM

* Die Vorschau von PDF-Dokumenten in den Messenger-Anhängen funktionierte nicht mehr. Statt des Dokuments wurde entweder eine leere Seite oder eine 404-Seite des plentyShops angezeigt. Dieses Verhalten wurde behoben.
* Die folgenden Variablen wurden im EmailBuilder ohne Zeilenumbrüche dargestellt. Dieses Verhalten wurde behoben.
** Widerrufsrecht im reinen Textformat
** Datenschutzerklärung im reinen Textformat
** Impressum im reinen Textformat
** Widerrufsformular im reinen Textformat
** Allgemeine Geschäftsbedingungen im reinen Textformat.
* Ebenso wurden die Pfade der dazugehörigen twig expressions dieser Variablen geändert. Die neue Pfade lauten:
**Widerrufsrecht im reinen Textformat: `globals.legalInformation.cancellationRights.plainNew | raw`
**Datenschutzerklärung im reinen Textformat: `globals.legalInformation.privacyPolicy.plainNew | raw`
**Impressum im reinen Textformat: `globals.legalInformation.legalDisclosure.plainNew | raw`
**Widerrufsformular im reinen Textformat: `globals.legalInformation.withdrawalForm.plainNew | raw`
**Allgemeine Geschäftsbedingungen im reinen Textformat: `globals.legalInformation.termsConditions.plainNew | raw`

--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.



--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|
|
|

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

====
