= Changelog 17. Mai 2023
:author: kevin-stederoth
:sectnums!:
:page-index: false
:page-aliases: ROOT:changelog.adoc
:startWeekDate: 11. Mai 2023
:endWeekDate: 17. Mai 2023

// Ab dem Eintrag nach diesem weitermachen: https://forum.plentymarkets.com/t/plentybi-neue-kennzahl-zahlungen-live-new-key-figure-payments-live/721961
// Auch folgenden Eintrag beachten: https://forum.plentymarkets.com/t/aenderung-myview-rechte-zum-erstellen-bearbeiten-und-loeschen-von-myview-ansichten-change-myview-rights-to-create-edit-and-delete-myview-sets/721910

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Amazon

Der Amazon FBA-Bestandsabgleich wurde überarbeitet.

*Hintergrund*

Vor Kurzem wurde das neue Menü für das Hinzufügen von Amazon-Konten veröffentlicht. Im Moment kannst du im Menü *Einrichtung » Märkte » Amazon » Neue Einstellungen* zwar noch keine Konten erstellen und bearbeiten. Es werden dort aber schon deine vorhandenen Amazon-Konten angezeigt. Wir arbeiten weiter daran, diese neuen Einstellungen zum Standard zu machen.

*Was ist neu?*

Als nächsten Schritt haben wir den Amazon FBA-Bestandsimport überarbeitet: Ab sofort wird beim Abgleich von FBA-Bestand nicht mehr auf die alten Einstellungen im Menü *Einrichtung » Märkte » Amazon » Einstellungen* zurückgegriffen. Stattdessen werden die neuen Kontoeinstellungen genutzt, um die Bestandsdaten abzugleichen.

[NOTE]
.Kein To-Do
======
Der Bestandsabgleich funktioniert genauso wie vorher. Auch an den Einstellungen im plentymarkets Backend hat sich nichts geändert.
======

[discrete]
=== Aufträge

* In der neuen Auftrags-UI verwendet die *Kompakte Ansicht* jetzt ein virtuelles Scrollen, um die Leistung zu verbessern, wenn mehr als 25 Artikel pro Seite angezeigt werden.
* In der neuen Auftrags-UI kann die Übersichtssuche auch durch Drücken der Eingabetaste innerhalb eines Filters ausgelöst werden. Das Drücken der Eingabetaste funktioniert nicht bei Datums-, Auswahl- und Mehrfachauswahlfiltern.
* Die Spalte *Versandprofil* wurde in der neuen Auftrags-UI für die Tabelle der Auftragspositionen eingeführt. Die Spalte *Versandprofil* ist optional und kann über die konfigurierbaren Tabellentitel in der Auftragsübersicht und in der Auftragsdetailansicht aktiviert werden.

[discrete]
=== CRM

* Ab sofort kannst du Konversationen im Messenger anheften, um noch einfacher und schneller zwischen diesen Konversationen hin- und herzuwechseln. Sobald du eine Konversation angeheftet hast, wird in der linken Seite der Navigation der Bereich *Angeheftete Konversationen* sichtbar.
+
Du kannst mit einem Klick auf das Kontextmenü in der Zeile *Angeheftete Konversationen* alle Konversationen auf einmal wieder lösen oder mit einem Klick auf *Konversation lösen* in der Zeile der angehefteten Konversation in der Seitennavigation oder in der geöffneten Konversation selbst eine einzelne Konversation wieder lösen.
* Ab sofort kannst du im Menü *Einrichtung » CRM » Messenger » Automatisierung* Filter, Aktionen und Auslöser (ereignis- oder zeitbasiert) einrichten, um deine Abläufe zu automatisieren. Weitere Informationen findest du auf der Handbuchseite xref:crm:messenger-testphase.adoc#ereignisse-automatisieren[Messenger (Testphase)].
+
[IMPORTANT]
.Bekannte Bugs
======
Es gibt bei der Neuerung einige link:https://forum.plentymarkets.com/t/neu-ereignisse-im-messenger-automatisieren-new-automate-events-in-messenger/721924[bekannte Probleme^]. Diese Probleme werden zeitnah behoben.
======

[discrete]
=== Import

* Ab sofort steht dir im Import-Typ *Kontakte, Firmen und Adressen* im Bereich *Kontakt* das Datenfeld *Tag-IDs* zur Verfügung. Dies ermöglicht es dir, Tags für deine Kontakte zu importieren.

[discrete]
=== Kaufland

In Kaufland-Katalogen können ab jetzt für Felder, die mehr als einen Wert akzeptieren, auch mehrere Werte über plenty übergeben werden. Bisher konntest du bei der Zuordnung der Felder zwar mehrere Felder aneinander hängen aber diese wurden im Anschluss als ein einzelner Wert zu Kaufland übertragen.

Damit die Übergabe von mehreren Werten funktioniert, müssen die zugeordneten Felder aneinander gehangen werden und im Anschluss muss ein vorgegebenes Trennzeichen eingestellt werden.

Das vordefinierte Trennzeichen ist `__SEPARATOR__`.

. Im ersten Step könnt ihr über den rot umrandeten Button beliebig viele Datenfelder aneinander hängen.
. Im zweiten Step könnt ihr dann über das Einstellungen-Symbol die Datenspalten-Einstellungen aufrufen.
. In den Datenspalten-Einstellungen wählt ihr für das Trennzeichen die Option Eigenes Trennzeichen hinzufügen aus und könnt in dem danach auftauchenden Feld das eigene Trennzeichen eingeben. Tragt hier nun `__SEPARATOR__` ein.

Ausgenommen davon ist das Feld für die Bilder. Hier gibt es eine separate Logik und es muss kein Trennzeichen eingestellt werden.

[discrete]
=== plentyBI

* Ab sofort steht im Menü *Einrichtung » plentyBI » Kennzahlen* die kostenlose neue Kennzahl *Zahlungen (Live)* zur Verfügung. Diese Kennzahl erlaubt es euch, Daten zu im System vorhandenen Zahlungen mithilfe verschiedener Kriterien auszuwerten. Weitere Informationen findest du auf der Handbuchseite xref:business-entscheidungen:live-payments.adoc[Zahlungen (Live)].

[discrete]
=== Plugins

* Die Standardseite beim Öffnen eines Plugins aus der Plugin-Übersicht wurde von der Beschreibung auf die Konfiguration angepasst. Die Beschreibung enthält nun nicht mehr nur due Kurzbeschreibung, sondern die ausführliche Beschreibung aus dem Marketplace.

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Aufträge

* In der Kompaktansicht steht der Länder-ISO Code nun vor der Postleitzahl und im Tooltip ist das Land nun ausgeschrieben.
* Die folgenden Änderungen wurden an der Auftragsdetails vorgenommen:
** Im Addresse-Widget wird `Name4` dargestellt, wenn dieser vorhanden ist
** Im Addresse-Widget ist die Mail-Addresse nun klickbar (mailto aktion)
** Beim erstellen einer Nachbestellung aus einen Auftrag sind die Menge vorausgefühlt
** Warenwert Brutto widget im Übersicht-Portlet hinzugefügt

[discrete]
=== CRM

* Das Limit der dynamischen Anhänge im EmailBuilder wurde von 3 auf 4 Anhänge erhöht.
* Im Filterbereich und in der Übersicht im Menü *CRM » Kontakte*, im Kontaktdatensatz im Bereich *Tags* und in der UI zum Erstellen eines neuen Kontakts werden die Tags nun unabhängig von der Groß-/Kleinschreibung alphabetisch sortiert in der Sprache des eingeloggten Benutzers angezeigt. Wenn ein Tag nicht in der Sprache des Benutzers vorhanden ist, wird das Tag in der nächsten verfügbaren Sprache angezeigt.

[discrete]
=== Kontoverwaltung

* Den Filtern unter *Kontoverwaltung » Konten* wurde der Filter *Rollen* hinzugefügt. Somit kannst du künftig die Benutzer:innen-Konten nach vergebenen Rollen filtern.

[discrete]
=== plentyBI

* Im Menü *Rechteverwaltung* wurde die Benennung bestehender Kennzahlkonfigurationen angepasst. Diese Änderung soll die Identifizierung von bereits angelegten Kennzahlen bei der Freigabe für Rollen ohne Admin-Rechte vereinfachen.
+
In der Auflistung bestehender Kennzahlkonfigurationen im Menü *Einrichtung » Kontoverwaltung » Rollen » [Rolle öffnen] » Zugriffsrechte » Kennzahlen* wird nun jeweils der bei der Anlage der Konfiguration von Benutzern vergebene Name der Kennzahlkonfiguration angezeigt. Zuvor wurde an dieser Stelle der systemseitig vergebene allgemeine Name der Kennzahl angezeigt.

[discrete]
=== Plugins

* Wenn du für ein Plugin den GitHub Branch wechselst, musst du künftig diesen Wechsel in einem Popup-Fenster bestätigen.
* Branches und Tags werden jetzt nicht mehr alphabetisch sortiert, sondern nach Aktualität, vom neuesten Tag/Branch zum ältesten.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Aufträge

* In der Detailansicht der neuen Auftrags-UI hatte das Markieren von Text in den Notizen nicht richtig funktioniert. Dies wurde behoben.
* Die folgenden Änderungen wurden an der Kompaktansicht vorgenommen:
** Die Einstellung in der Pagination *Ergebnisse pro Seite* wird nun gespeichert
** Nach der ausführen einer Gruppenfunktion bleibt man auf der aktuellen Seite, und wechselt nicht zurück zur ersten Seite des Suchergebnisses

[discrete]
=== CRM

* Beim Versuch Rechnungs- oder Lieferadressen für einen bestehenden Kontakt zu importieren, ohne ein Feld im Datensatz zu ändern, wurde zwar eine Meldung angezeigt, dass alle Daten erfolgreich importiert wurden, aber die Adresse wurde weder erstellt noch mit dem Kontakt verknüpft. Dieses Verhalten wurde behoben.
* Bei Lieferungen in Nicht-EU-Länder wurde in der EmailBuilder-Vorlage fälschlicherweise die Mehrwertsteuer ausgewiesen. Dieses Verhalten wurde behoben.

[discrete]
=== Dokumente

* Wenn die Rechnungsnummer mehr als 18 Zeichen hat, z.B. bei Rechnungen, die hochgeladen wurden, wurde die Rechnungsnummer auf dem Dokument nach dem 18ten Zeichen abgeschnitten. Dies wurde behoben.

[discrete]
=== Fulfillment

* Bei der Anmeldung von aus mehreren Paketen bestehenden Lieferaufträgen bei Amazon Prime kam es zu Fehlermeldungen beim Erzeugen von Versandetiketten und die Aufträge konnten nicht oder nur teilweise angemeldet werden. Dieses Problem wurde behoben.

--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Amazon

* Der Amazon-Artikeldatenexport wurde überarbeitet.
* Im Menü *Einrichtung » Artikel » Verkaufspreise* wurde die Einstellung *Amazon-Konten* in *Amazon-Channels* umbenannt. Als Optionen sind die Channels wählbar.

*Hintergrund*

Vor Kurzem wurde das neue Menü für das Hinzufügen von Amazon-Konten veröffentlicht. Im Moment kannst du im Menü *Einrichtung » Märkte » Amazon » Neue Einstellungen* zwar noch keine Konten erstellen und bearbeiten. Es werden dort aber schon deine vorhandenen Amazon-Konten angezeigt. Wir arbeiten weiter daran, diese neuen Einstellungen zum Standard zu machen.

*Was ist neu?*

Als nächsten Schritt haben wir den Amazon FBA-Bestandsimport überarbeitet: Ab sofort wird beim Abgleich von FBA-Bestand nicht mehr auf die alten Einstellungen im Menü *Einrichtung » Märkte » Amazon » Einstellungen* zurückgegriffen. Stattdessen werden die neuen Kontoeinstellungen genutzt, um die Bestandsdaten abzugleichen.

[NOTE]
.Kein To-Do
======
Der Bestandsabgleich funktioniert genauso wie vorher. Auch an den Einstellungen im plentymarkets Backend hat sich nichts geändert.
======

[discrete]
=== Aufträge

* Du kannst ab jetzt negative Preise an den Auftragspositionen setzen.
* In der Übersicht der neuen Auftrags UI wurden Filter für Retourengrund und Versandprofil hinzugefügt.
* In MyView wurde dem Feld *Herkunft* die neue Einstellung *Anzeigeoption* hinzugefügt. Du kannst jetzt bestimmen, ob du nur den Namen, nur die ID oder beides angezeigt bekommen möchtest. Folglich wurde das separate Feld *Herkunfts-ID* entfernt.

[discrete]
=== CRM

* In der UI zum Erstellen eines neuen Kontakts im Menü *CRM » Kontakte* wurde in der Toolbar die Schaltfläche *Zurücksetzen* hinzugefügt. Mit einem Klick auf diese Schaltfläche kannst du alle bisherig getätigten Eingaben wieder zurücksetzen. Außerdem wurde die Toolbar oben angeheftet, sodass diese auch sichtbar ist, wenn du in dieser Ansicht weiter nach unten scrollst.
* Die Gruppenfunktion in der Übersicht des Menüs *CRM » Kontakte* wurde um die folgenden Punkte erweitert:
** Tags hinzufügen
** Kundenklasse ändern
** Eigner ändern
** Bewertung ändern
** Kundentyp ändern

[discrete]
=== Import

* Beim Importformat für Aufträge wurde die Möglichkeit hinzugefügt, Tags zu importieren.

[discrete]
=== plentyBI

* Ab sofort kannst du im Menü *Einrichtung » plentyBI » Kennzahlen » [Kennzahlkonfiguration öffnen]* für jede Kennzahl eine Einheit angeben. Dazu haben wir innerhalb der Kennzahlkonfiguration die neue Option *Ergebniseinheit* hinzugefügt.
+
Hier kannst du selbst bestimmen, mit welchem Text die Einheit der Kennzahl auf den Darstellungselementen im Dashboard dargestellt wird. Je nach der *Berechnung*, die in der Kennzahlkonfiguration gewählt wurde, wird das Feld *Ergebniseinheit* mit einem passenden Vorschlag für die Benennung der Einheit vorausgefüllt.
+
Du kannst stattdessen aber auch einen individuellen Namen eingeben. Beachte dabei, dass maximal 8 Zeichen möglich sind und das Feld nicht leer sein darf, da die Kennzahlkonfiguration sonst nicht gespeichert werden kann.

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Aufträge

* In der Detailansicht der neuen Auftrags-UI kam es bei gesperrten Aufträgen in machen Fällen beim Bearbeiten von Adressen zu einem Fehler. Dies wurde behoben.

--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|link:https://marketplace.plentymarkets.com/clearvat_6925[eClear - Grenzüberschreitender E-Commerce - so einfach wie Inlandsverkäufe^]
|3.0.3
|-

|link:https://marketplace.plentymarkets.com/wesiopropertygenerator_55102[Eigenschaften in Textfeld Generator^]
|1.0.1
|-

|link:https://marketplace.plentymarkets.com/googleanalytics_4725[GoogleAnalytics^]
|2.0.2
|-

|link:https://marketplace.plentymarkets.com/elasticexportidealode_4723[idealo.de^]
|3.4.4
|-

|link:https://marketplace.plentymarkets.com/limango_7023[limango^]
|1.5.1
|-

|link:https://marketplace.plentymarkets.com/mytoys_54776[myToys^]
|1.1.0
|-

|link:https://marketplace.plentymarkets.com/uptain_55274[uptain® Conversion Optimierung mit Popups und Abbrecher-Mails^]
|1.0.1
|-

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

Warehouse-App::
+
--

[discrete]
== Neu

Folgende Neuerungen wurden in Version 1.0.11 der *plentymarkets Warehouse App* veröffentlicht.

* Für die Funktion *Inventur* wurde die Option *Einzelerfassung bis Menge* hinzugefügt. Ab der im Menü *Einstellungen » Inventur* festgelegten Menge wird der Mengendialog geöffnet, über den dann weitere Artikelmengen eingegeben werden können.

'''

[discrete]
== Geändert

Folgende Änderungen wurden in Version 1.0.11 der *plentymarkets Warehouse App* veröffentlicht.

* Innerhalb der Funktionen *Wareneingang* und *Inventur* wurden die Texte angepasst, die angezeigt werden, wenn noch keine Artikel erfasst wurden.

'''

[discrete]
== Behoben

Folgende Probleme wurden in Version 1.0.11 der *plentymarkets Warehouse App* behoben.

* In bestimmten Fällen wurde aufgrund eines Übertragungsfehlers im Hintergrund die Ansicht zum Drucken von Artikeletiketten nicht korrekt angezeigt. Dieses Verhalten wurde behoben.
* Innerhalb der Funktionen *Verräumen* und *Lagerort inspizieren* wurde in manchen Fällen die Benutzeroberfläche nicht korrekt aktualisiert. Dieses Verhalten wurde behoben.

--

====
