= Changelog 3. Mai 2023
:author: kevin-stederoth
:sectnums!:
:page-index: false
:page-aliases: ROOT:changelog.adoc
:startWeekDate: 27. April 2023
:endWeekDate: 3. Mai 2023

// Ab diesem Eintrag weitermachen: LINK EINFÜGEN

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Aufträge

* In der Kompaktansicht wurde eine Checkbox in der Toolbar hinzugefügt, um alle Aufträge für Gruppenfunktionen auszuwählen.
* In der Kompaktansicht wurden neue Sortieroptionen hinzugefügt:
** Zahlungsdatum
** Warenausgangsdatum
** Postleitzahl
** Lieferdatum
** Hauptdokument
* In der Kompaktansicht wurden neue Filter hinzugefügt:
** Externe Lieferscheinnummer
** Externe Quellauftrags-ID

[discrete]
=== CRM

* Die automatisch generierte E-Mail-Adresse im Assistenten *Messenger-Konfiguration* wurde angepasst, um dem RFC-Standard 2821 zu entsprechen. Bitte beachte unser Praxisbeispiel xref:crm:praxisbeispiel-e-mail-weiterleitung-messenger.adoc[E-Mail-Weiterleitung für den Messenger einrichten].
+
[IMPORTANT]
.To-Do
======
Damit die kürzere E-Mail-Adresse verwendet wird, muss eine xref:crm:messenger-testphase.adoc#assistent-durchlaufen[neue Inbox] angelegt werden. Bereits erstellte E-Mail-Adressen werden weiterhin unterstützt.
======

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== CRM

* In der Kontakte-Übersicht (Menü *CRM » Kontakte*) sowie in allen Bereichen innerhalb des Kontaktdatensatzes, in denen es die Funktion gibt, sich eine Anzahl der Ergebnisse pro Seite anzeigen zu lassen, merkt sich das System ab sofort, welche Zahl man gewählt hatte, wenn man sich das nächste Mal einloggt. Bisher wurde immer die kleinste Zahl (5) beim erneuten Login angezeigt, auch wenn mehr als 5 Ergebnisse vorhanden waren.

[discrete]
=== Kontoeinstellungen

* Der Suche in der UI *Einstellungen » Kontoverwaltung » Konten* wurden Filter hinzugefügt, um nach Administratoren, Nicht-Administratoren und allen Benutzer:innen-Konten zu suchen.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Aufträge

* Der Tooltip des Icons zeigt nun auch an, welches Amazon-/eBay-Treueprogramm verwendet wird.

[discrete]
=== Dokumente

* Wenn die Einstellung *Anzahl Nachkommastellen bei Auftragspositionen* auf die Option *4* gesetzt war, wurde die MwSt. nicht zur Menge 1, sondern zur aktuellen Positionsmenge angezeigt. Dies wurde behoben.

[discrete]
=== Ereignisaktionen

* Für die Aktion *Tags hinzufügen/löschen* wurde in der Übersicht der Ereignisaktionen kein Wert angezeigt. Nun ist es möglich zu sehen, welche Tags zum Hinzufügen oder Löschen gewählt wurden und ob sie entfernt werden.

[discrete]
=== plentyBI

* Für die Kennzahl *Retourenquote* wurden innerhalb von Tabellen oder Diagrammen auf dem Dashboard keine Ergebnisse angezeigt, wenn in der Kennzahlkonfiguration die Dimension *Auftragsherkunft* verwendet wurde. Dieses Verhalten wurde behoben, sodass die Daten nun korrekt angezeigt werden.

--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.



--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|
|
|

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

====
