= Changelog 23. August 2023
:author: kevin-stederoth
:sectnums!:
:page-index: false
:page-aliases: ROOT:changelog.adoc
:startWeekDate: 17. August 2023
:endWeekDate: 23. August 2023

// Ab diesem Eintrag weitermachen: LINK EINFÜGEN

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Artikel (Neue UI)

* In der Variantenansicht der neuen Artikel-UI werden im Bilderpanel nun zuerst die mit der Variante verknüpften Bilder angezeigt, danach die nicht verknüpften. Zusätzlich sind die verknüpften als auch die unverknüpften Bilder nach Position sortiert.

[discrete]
=== Aufträge

* Es ist nun möglich über die Toolbar der Detailansicht von Aufträgen einen neuen Auftrag zu erstellen. Man kann zwischen den Typen Auftrag, Angebot und Abonnement wählen. Der Punkt Abonnement steht bei Gastbestellungen nicht zur Verfügung.
* In der Kompaktansicht der neuen Auftrag UI ist es jetzt möglich den bezahlten Betrag in Prozent im Titel anzeigen zu lassen.
* In der neuen Auftrag UI werden beim Zurückbuchen von Bestand jetzt auch die Lagerorte mit Bestand und die an der Variante konfigurierten Lagerorte vorgeschlagen.
* Bei der Erstellung eines neuen Auftrags oder bei der Bearbeitung von Auftragspositionen, wurde der Filtern *Lieferanten-Artikel-Nummer* bei der Artikelsuche hinzugefügt.
* Die Eigenschaft *Externe Quellauftrags-ID* wurde für den Export für Aufträge über den Katalog freigegeben.
* In der Auftragsdetailansicht kann jetzt über die Adresse die UmsatzsteuerID geprüft werden.
Dazu einfach zur Adresse navigieren, dort auf das Drei-Punkte Menü klicken und *UmStID überprüfen* auswählen.

[discrete]
=== Dokumente

* In der Nummernkreis-UI wurde ein Filter für aktive/inaktive Nummernkreise hinzugefügt.

[discrete]
=== plentyBI

* Ab sofort steht im Menü *Einrichtung » plentyBI » Kennzahlen* die neue kostenlose Kennzahl *Wareneingänge* zur Verfügung. Diese Kennzahl erlaubt es euch, Daten zu im System vorhandenen Wareneingängen mithilfe verschiedener Kriterien auszuwerten.
** Berechnungsgrundlagen:
*** Umsatz
*** Absatz
** Dimensionen:
*** Erstellungsdatum
*** Lieferant, Erstellungsdatum
*** Lager, Erstellungsdatum
** Filter:
*** Lieferant
*** Lager
*** Artikel ID
*** Varianten ID
* Wird die Kennzahl xref:business-entscheidungen:live-payments.adoc[Zahlungen (Live)] innerhalb einer xref:business-entscheidungen:myview-dashboard.adoc#600[Tabelle] auf dem Dashboard dargestellt, gelangt man per Klick auf den Eintrag in der Spalte *Dimension* nun in das Menü *Aufträge » Zahlungsverkehr*. Dort werden die Zahlungen automatisch nach den entsprechenden Dimensionswerten gefiltert angezeigt.

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Aufträge

* Es ist nun auch bei Gutschriften möglich die Variante zuzuordnen oder die Zuordnung aufzuheben.
* Wir haben das Compact View Template *Classic* mit den neuen Features, die wir in den letzten Wochen implementiert haben, wie z.B. die Toolbar im Header, angepasst, so dass es mehr wie das alte UI aussieht.
* Folgende Änderungen wurden an den Gruppenfunktionen vorgenommen:
** Status ändern
*** Man kann nun nach dem Status suchen
*** Die Farben der Statuswerte werden berücksichtigt und angezeigt
** E-Mail-Service
*** Man kann nun nach den Vorlagen suchen
** Markierung ändern
*** Die Färbung der Markierungen wurde implementiert

[discrete]
=== Kaufland

Die SKUs für Kaufland wurden angepasst. Seit der Änderung erhalten alle neu angelegten Varianten über Katalog pro Marktplatz die SKU mit der Endung des jeweiligen Storefronts.

* Für den deutschen Marktplatz wird die SKU mit der Endung `_de` versehen.
* Für den slowakischen Marktplatz wird die SKU mit der Endung `_sk` versehen.
* Für den tschechischen Marktplatz wird die SKU mit der Endung `_cz` versehen.

Die Anpassung der SKUs für Kaufland erfolgt aufgrund der Vorgabe, dass Kaufland ausschließlich eindeutige SKUs über alle Storefronts hinweg erlaubt. Demnach kann dieselbe SKU nicht für alle drei Storefronts (DE, SK und CZ) verwendet werden.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Artikel

* Unter bestimmten Bedingung kam es vor, dass im Bilderpanel in der Artikel- und Variantenansicht die Bilder nicht gerendert hat. Dieses Problem wurde behoben.

[discrete]
=== Aufträge

* Versuchte man etwas an der Adresse zu ändern, z.B. die E-Mail entfernen, so wurde eine neue identische Adresse mit neuer ID erstellt und zugewiesen. Nun wird in der Regel auch weiterhin eine neue Adresse erstellt, sofern die aktuelle Adresse auch von anderer Stelle referenziert wird, aber die Änderungen werden korrekt übernommen.
* In der Variantensuche (sowohl in der Auftragsbearbeitung als auch in der Auftragserstellung) wurden Artikel, die auch Teil eines Bundels waren, mit einem falschen Wert für den Nettobestand angezeigt. Dies ist nun behoben.
* Wenn während der Auftragsanlage von einem *Angebot* den Tab gewechselt wurde, wurde der Auftragstyp wieder auf *Auftrag* geändert. Dies wurde behoben.
* In der neuen Auftrags-UI wurden die folgenden Fixes hinzugefügt:
** Wenn einige Felder in der KompaktUI entfernt werden und nur die Hälfte des Containers für die Felder im Kompaktmodus verbleibt, bleibt aufgrund einer festen Höhe ein weißer Raum unter den Feldern. Dies wurde behoben.
** Beim Hinzufügen einer Paketnummer für eine Bestellung in der Auftrags-Detailansicht und anschließendem Navigieren zur Auftragsübersicht und Neuladen der Auftragsübersicht wird die Schaltfläche *Sendungsverfolgungslink öffnen* nicht angezeigt. Dies wurde behoben.
** In der Auftragsdetailansicht werden die Auftragspositionen aufgrund einer in der Anfrage verwendeten Beziehung geladen, obwohl sie nicht mehr benötigt werden. Dies wurde behoben.
** In der Auftragsdetailansicht, wurde das Menü *Waren zurückbuchen* in der Toolbar nicht geschlossen, wenn ein Eintrag gewählt wurde. Dies wurde behoben.
** In einer duplizierten Registerkarte der Order-UI wurden nicht alle Elemente korrekt angezeigt. Dies wurde behoben.
* Die folgenden Korrekturen wurden für die Tabelle des Warenkorbs bei der Erstellung eines neuen Auftrags und bei der Bearbeitung von Auftragspositionen hinzugefügt:
** In der neuen Bestell-UI war beim Bearbeiten der Bestellpositionen oder beim Anlegen einer neuen Bestellung das in der Artikeltabelle verfügbare Mengenfeld immer für Änderungen verfügbar, auch für Bundleartikel und Bundle-Komponenten. Dies wurde behoben, und jetzt ist die Menge sichtbar oder schreibgeschützt, je nachdem, welche Einstellung unter *Setup » Aufträge » Einstellungen » Änderung der Menge für Bundle-Artikel und Bundle-Komponenten zulassen* verfügbar ist.
** Wenn die Menge einer Bundle-Komponente geändert wird, wird die Schaltfläche *Verkaufspreise aktualisieren* nach dem erneuten Laden der gültigen Verkaufspreise nicht ausgeblendet. Dies wurde behoben.
* Beim erstellen einer Umbuchung wurden Artikel, die auch Teil eines Bundels waren, teilweise mit einen Einkaufspreis von 0 gespeichert. Dies ist nun behoben.

--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.



--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|
|
|

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

====
