= Changelog 18. Oktober 2023
:author: kevin-stederoth
:sectnums!:
:page-index: false
:page-aliases: ROOT:changelog.adoc
:startWeekDate: 12. Oktober 2023
:endWeekDate: 18. Oktober 2023

// Ab diesem Eintrag weitermachen: LINK EINFÜGEN

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Aufträge

* Bei der manuellen Auftragsanlage kann nun die externe Auftrags-ID angegeben werden.
* In der Detailansicht der Auftrag UI kann nun in der Übersicht der Skonto-Endbetrag angezeigt werden.
* Bundesland/Provinz wird in den Auftragsdetails im Adress-Widget und in der Auftragsübersicht (Kompaktansicht) im Tooltip der Adresse jetzt angezeigt.
* In der Auftragssuche der Auftrag-UI ist für den Eigner Filter jetzt der Operator *Existiert* verfügbar.
* In der Detailansicht der Auftrag UI ist es jetzt möglich die Lieferadresse als Rechnungsadresse und auch die Rechnungsadresse als Lieferadresse zu übernehmen.
* Die externe Rechnung und die externe Gutschrift sind jetzt in der Gruppenfunktion der Auftrags-UI verfügbar. Du kannst sie dann für das Zusammenführen von Dokumenten auswählen.

[discrete]
=== CRM

* Im Kontaktdatensatz im Bereich *Aufträge* findest du ab sofort einen Button, über den du in die Auftragsübersicht im Menü *Aufträge » Aufträge* gelangst. Dort sind die Aufträge des Kontakts bereits gefiltert.

[discrete]
=== Kataloge

Wir haben folgende Felder im Katalogformat *Artikel (Neu)* ergänzt.

ASIN:

* Land Name
* Land ID
* Wert
* Link ID
* Link Position

Moin:

* Land Name
* Land ID
* Wert
* Link ID
* Link Position

ePID:

* Land Name
* Land ID
* Wert
* Link ID
* Link Position

Barcode:

* Code
* Name
* ID

Artikel:

* Amazon FBA Plattform
* Amazon Produkttyp
* Zustand Name
* Zustand API Name
* Aktionsgutschein
* eBay Kategorie 1
* eBay Kategorie 2
* Listing-Vorlage ID
* eBay Shop Kategorie 1
* eBay Shop Kategorie 2
* Markierung 1
* Markierung 2
* Seriennummer
* Amazon FBA
* Versandpaket
* Abonnement
* Artikeltyp
* Herstellerlogo-URL
* max. Bestellmenge
* Erlöskonto
* Warentyp
* Shop-Aktion ID
* Shop-Aktion Name

[discrete]
=== MyView

* Ab jetzt hast du die Möglichkeit ein Abstandhalter-Element in deine Ansicht einzubauen, welches die anderen Elemente sichtbar voneinander trennt. Die Höhe des Elements lässt sich manuell einstellen und anpassen, die Breite ist vorgegeben und passt sich automatisch der Spaltenbreite an.

[discrete]
=== plentyBI

* Ab sofort kannst du Daten, die innerhalb einer Tabelle auf dem Dashboard dargestellt werden, im CSV-Format exportieren. Dazu haben wir eine neue Option im Kontextmenü für Tabellen hinzugefügt. Klicke auf Aktionen (drei-Punkte-Symbol) oben rechts an einer Tabelle und dann auf *CSV-Export*. Anschließend wird automatisch eine CSV-Datei mit den entsprechenden Daten heruntergeladen.

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== CRM

* In der Kampagne im Bereich *E-Mail-Vorlage* wurde die Auswahl der Variable auf den Gutscheintyp *Gutschein* und die Gutscheinart *Aktionsgutschein* beschränkt. Das heißt, es ist ab sofort nicht mehr möglich, einen Wert für die E-Mail-Variable zu setzen, wenn die Kampagne nicht die zulässigen Kriterien erfüllt.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Aufträge

* Wenn in der Artikel bearbeiten UI Artikel in den Einkaufswagen gelegt wurden, traten aus folgendem Grund Performance-Probleme auf: Beim Verlassen von Eingabefeldern und beim Klicken auf Enter ohne in den Eingabefeldern Änderungen vorgenommen zu haben, wurde die Vorschau-Route mehrfach ausgelöst. Dieses Verhalten wurde behoben.
* Wenn in der Artikel bearbeiten UI Text- oder Zahlenangaben in der Tabelle Auftragspositionen geändert wurden, blieb das Speichern-Symbol inaktiv. Dies lag daran, dass der Preview-Call, der beim Verlassen der Eingabefelder ausgelöst werden sollte, nicht ausgeführt wurde. Dieses Verhalten wurde behoben.
* Das Feld *eBay Konto* in den Auftragsdetails wurde behoben, dass es jetzt immer den Verkäuferaccount anzeigt.
* Die Filter werden beim Wechseln vom Tab nicht mehr überschrieben.
* Die Herkunft mit der ID 100 wird nun in der Auswahl der Herkunft angezeigt und kann somit gesetzt werden.
* Beim Wechsel der Ansicht (Kompaktansicht, Tabellenansicht) wurden die Datumsfilter zurückgesetzt, die Filter bleiben jetzt bestehen.

[discrete]
=== CRM

* Beim Versuch, eine E-Mail-Vorlage über die Vorschau mit dem Dokument SEPA-Lastschriftmandat im Anhang zu versenden, trat ein Fehler auf. Dieser Fehler wurde behoben.
* Im EmailBuilder haben die Variablen *Gutschein-Code (1)* bis *Gutschein-Code (10)* keinen Wert in der versendeten E-Mail angezeigt, wenn die Variable als twig expression im Code-Widget des EmailBuilder eingefügt wurde (Beispiel: `{⁠{ globals.coupons.couponCode10 }⁠}`). Dieses Verhalten wurde behoben.
* Wenn man eine EmailBuilder-Vorlage versendet hat, die Nummernvariablen im Betreff enthielt, wurde die Nummernformatierung nicht korrekt ausgegeben. Dieses Verhalten wurde behoben.

'''

[discrete]
== Gelöscht

Folgende Funktionalität wurde in den letzten 7 Tagen auf *{version}* entfernt.

[discrete]
=== Amazon

* Der Assistent für die Amazon-Grundeinstellungen wurde entfernt, um auf den Umzug auf die neuen Amazon-Einstellungen vorzubereiten und den Wartungsaufwand zu reduzieren. Du kannst deine Einstellungen für Amazon-Benutzerkonten weiterhin im Menü *Einrichtung » Märkte » Amazon* setzen.

[discrete]
=== CRM

* Wie in diesem link:https://forum.plentymarkets.com/t/ankuendigung-eol-kalender/731674/3[Beitrag^] angekündigt, wurde der Kalender aus dem Menü *plentymarkets Logo (Start) » Kalender* entfernt.

--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.



--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|
|
|

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

====
