= Changelog 5. April 2023
:author: kevin-stederoth
:sectnums!:
:page-index: false
:page-aliases: ROOT:changelog.adoc
:startWeekDate: 30. März 2023
:endWeekDate: 5. April 2023

// Ab diesem Eintrag weitermachen: LINK EINFÜGEN

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite xref:business-entscheidungen:versionszyklus.adoc#[Versionszyklus]. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[tabs]
====
stable::
+
--

:version: stable

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.

[discrete]
=== Amazon

Die neue Einstellungs-Oberfläche für Amazon-Konten ist unter *Einrichtung » Märkte » Amazon » Neue Einstellungen* in der Vorschau verfügbar.

Die Oberfläche ist soweit vollständig funktional, außer dass Löschen, Erstellen, Speichern und das Verbinden mit Amazon-Konten deaktiviert wurde, bis auch im Hintergrund sämtliche Prozesse auf die neue Hintergrundstruktur umgezogen wurden.

Die alten Konten, werden per Migration in die neuen Konten überführt und sollten für euch direkt sichtbar sein, sobald die Oberfläche für euch sichtbar ist. Jedes Speichern der alten Einstellungen führt direkt zu einer Migration der neuen Konten, sodass eure Änderungen dort spätestens nach einem erneuten Laden der Einstellungen sichtbar sein sollten.

[IMPORTANT]
.To-Do
======
Prüft bitte unter *Einrichtung » Märkte » Amazon » Neue Einstellungen*, ob die Einstellungen in der neuen Oberfläche den Einstellungen in der alten Oberfläche unter *Einrichtung » Märkte » Amazon » Einstellungen* entsprechen und meldet euch frühzeitig, sollten euch Probleme auffallen.
======

[NOTE]
.Feedback
======
Gebt uns gerne Feedback zur neuen Einstellungs-Oberfläche link:https://forum.plentymarkets.com/t/amazon-neue-einstellungsoberflaeche-new-settings-user-interface/708645[in diesem Thema im Forum^].
======

[discrete]
=== Aufträge

* Ab sofort steht euch im Menü *Aufträge » Aufträge (Testphase)* neben der bisherigen Listenansicht auch die Kompaktansicht für eure Aufträge zur Verfügung.
+
Diese ermöglicht es euch, bestimmte Auftragsdetails direkt in der Übersicht anzuzeigen. Außerdem könnt ihr bestimmen, wie groß die gewählten Felder angezeigt werden sollen und bei Bedarf eine farbliche Markierung hinzufügen sowie den Titel der Felder ändern. Alle diese Einstellungen findet ihr im Bearbeitungsmodus (MyView).
+
Um zwischen den Ansichten zu wechseln, steht euch oben rechts in der Übersicht der Button *Zur Listenansicht wechseln* bzw. *Zur Kompaktansicht wechseln* zur Verfügung. Weitere Informationen zur Kompaktansicht findet ihr auf der Handbuchseite xref:auftraege:design-order-view.adoc#compact-vs-list-view[Auftragsansicht gestalten].

[discrete]
=== CRM

* Im Menü *CRM » Kontakte* wurden die folgenden Anpassungen vorgenommen:
** In der Übersicht neben der E-Mail-Adresse findest du neben dem Kopieren-Icon nun das Icon *E-Mail senden*. Dieses Icon erscheint, wenn du über die E-Mail-Adresse hoverst. Mit einem Klick auf das Icon öffnet sich dein Standard-E-Mail-Programm mit der bereits vorausgefüllten E-Mail-Adresse des Kontakts im Empfängerfeld und du kannst dem Kontakt direkt eine E-Mail schreiben.
** In der Übersicht neben der Telefonnummer findest du neben dem Kopieren-Icon das Icon *Anrufen*. Dieses Icon erscheint, wenn du über die Telefonnummer hoverst. Mit einem Klick auf das Icon öffnet sich deine Standard-Telefon-App und du kannst du die dort gespeicherte Telefonnummer z.B. über FaceTime oder Skype anrufen.
** Diese beiden neuen Funktionen *E-Mail senden* und *Anrufen* findest du ebenso in den Portlets *Optionen*, *Primäre Adresse* und *Adressen*.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.

[discrete]
=== Aufträge

* Beim Wechseln zwischen der Kompakt- und der Listenansicht in der Auftragsübersicht und beim Wechseln zwischen den Auftragsdetails und der Auftragsübersicht, war die Auftragsübersicht leer. Dies wurde behoben.

--

early::
+
--

:version: early

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *{version}* veröffentlicht.



'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *{version}* behoben.



--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|
|
|

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].

--

====
