= Container_CheckoutOrderParamsList
:lang: en
// include::{includedir}/_header.adoc[]
:keywords: Container_CheckoutOrderParamsList
:position: 10258

//  auto generated content Thu, 06 Jul 2017 00:02:17 +0200
== Short description

Returns the content of the container for selecting order characteristics.

== Description of this function

[source,plenty]
----

Container_CheckoutOrderParamsList( string $itemID  , string $quantity  , string $basketItemID  ) : string

----

== Template CheckoutOrderParamsList

=== CheckoutOrderParamsListBasketItem

==== Variables

These variables are available in this container.

* $CheckoutOrderParamsListBasketItemID — Contains the ID of the shopping cart item for listing the order characteristics.
* $CheckoutOrderParamsListBasketItemItemID — Contains the item's ID for listing the order characteristics.
* $CheckoutOrderParamsListBasketItemQuantity — Contains the order quantity of the shopping cart items for listing the order characteristics.

=== CheckoutOrderParamsListGroupItem

==== Variables

These variables are available in this container.

* $OrderParamsGroupItemID — Contains the characteristic group's ID.
* $OrderParamsGroupItemInputName — Contains the form name for selecting the characteristic groups. This name is relevant for groupings of the type "single selection".
* $OrderParamsGroupItemName — Contains the name of the characteristic group.
* $OrderParamsGroupItemPosition — Contains the position of the characteristic group.
* $OrderParamsGroupItemSelectedValues — Contains the selected values of the characteristic group. Use this data for the groupings "Single selection" and "Multiple selection".
* $OrderParamsGroupItemType — Contains the characteristics group's type. Is comparable to the template variable$ORDER_PARAMS_GROUP_TYPE_X.

=== CheckoutOrderParamsListValueItem

==== Variables

These variables are available in this container.

* $OrderParamsValueItemID — Contains the characteristics group's ID.
* $OrderParamsValueItemInputName — Contains the form name for entering the characteristics value.
* $OrderParamsValueItemIsSelected — Flags whether the characteristics has been selected.
* $OrderParamsValueItemMarkup — Contains the characteristic's surcharge.
* $OrderParamsValueItemName — Contains the name of the characteristic.
* $OrderParamsValueItemPosition — Contains the position of the characteristic.
* $OrderParamsValueItemSelectList — Contains the values of characteristics of the type "Selection".
* $OrderParamsValueItemType — Contains the characteristic type.
* $OrderParamsValueItemValue — Contains the characteristic value. This characteristic value should be specified as "value" in form elements.
