= Email
:lang: en
// include::{includedir}/_header.adoc[]
:keywords: Email
:position: 10101

//  auto generated content Thu, 06 Jul 2017 00:52:28 +0200
== Short description

These template functions and template variables can only be used to configure the layout of email templates. Find out more about email templates <<crm/sending-emails#1200, here>>.

== Global Template Functions

* <<omni-channel/online-store/setting-up-clients/cms-syntax#email-email-link-basket, Link_Basket>> — This function returns the URL for the shopping cart.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#email-email-link-checkout, Link_Checkout>> — This function returns a URL for the checkout.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#email-email-link-item, Link_Item>>
* <<omni-channel/online-store/setting-up-clients/cms-syntax#email-email-link-newpassword, Link_NewPassword>> — This function returns a URL for the form used to create a new password.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#email-email-link-termsconditions, Link_TermsConditions>> — This function returns the URL for the terms and conditions.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#email-email-link-webstore, Link_Webstore>> — This function returns the URL for the online store.

== Global Template Variables

* $BankAccount — This variable contains your bank account number as it was entered in the Setup » Settings » Bank menu.
* $BankCode — This variable contains your sort code as it was entered in the Setup » Settings » Bank menu.
* $BankIBAN — This variable contains your IBAN as it was entered in the Setup » Settings » Bank menu.
* $BankName — This variable contains the name of your bank as it was entered in the Setup » Settings » Bank menu.
* $BankOwner — This variable contains the account holder as it was entered in the Setup » Settings » Bank menu.
* $BankSwift — This variable contains your BIC as it was entered in the Setup » Settings » Bank menu.
* $BarcodeOrderID
* $CancellationRightsHTML — This variable contains the cancellation rights in HTML format.
* $CancellationRightsText — This variable contains the cancellation rights in text format.
* $CouponCode1
* $CouponCode2
* $CouponCode3
* $CouponCode4
* $CouponCode5
* $CouponCode6
* $CouponCode7
* $CouponCode8
* $CouponCode9
* $CouponCode10
* $CouponValue
* $Currency — This variable contains the currency.
* $CustomerAccountOwner — This variable contains the account holder name of the customer account.
* $CustomerAdditionalAddress — This variable contains additional address information for the customer's address.
* $CustomerBIC — This variable contains the customer's BIC or SWIFT code.
* $CustomerBankName — This variable contains the name of the customer's bank.
* $CustomerCity — This variable contains the name of the town of the customer / the person receiving the invoice.
* $CustomerCityWithZip — This variable contains the postcode and name of the town of the customer / the person receiving the invoice.
* $CustomerClass — This variable contains the customer's customer class.
* $CustomerCompany — This variable contains the name of the company of the customer / the person receiving the invoice.
* $CustomerCountry — This variable contains the name of the country of the customer / the person receiving the invoice.
* $CustomerCountryID — This variable contains the customer's country ID. The ID is assigned by the system.
* $CustomerCountryIsoCode — This variable contains the ISO code for the country of the customer / the person receiving the invoice.
* $CustomerEbayName — This variable contains the customer's eBay name.
* $CustomerEmail — This variable contains the customer's email address.
* $CustomerFax — This variable contains the fax number of the customer / the person receiving the invoice.
* $CustomerFirstName — This variable contains the first name of the customer / the person receiving the invoice.
* $CustomerFullName — This variable contains the customer's complete name, i.e. their first name and surname.
* $CustomerIBAN — This variable contains the customer's IBAN.
* $CustomerID — This variable contains the customer ID.
* $CustomerLang — This variable contains the customer's language.
* $CustomerLastName — This variable contains the surname of the customer / the person receiving the invoice.
* $CustomerLeadID
* $CustomerMobilePhone — This variable contains the mobile phone number of the customer / the person receiving the invoice.
* $CustomerNumber — This variable contains the customer's customer number.
* $CustomerPassword — This variable contains the customer's password.
* $CustomerPhone — This variable contains the phone number of the customer / the person receiving the invoice.
* $CustomerSalutationKey
* $CustomerSalutationLabel
* $CustomerSign
* $CustomerSpecialWishes — This variable contains the special wish of customer. The customer can usually enter a special wish, when ordering from an online store. This special wish is saved in the order data as order note.
* $CustomerState — This variable contains the name of the state/region of the customer.
* $CustomerStreet — This variable contains the name of the street of the customer / the person receiving the invoice.
* $CustomerTitle
* $CustomerZip — This variable contains the postcode of the customer / the person receiving the invoice.
* $DeliveryAddressAdditionalAddress — This variable contains the recipient's additional address information.
* $DeliveryAddressCity — This variable contains the name of the recipient's town.
* $DeliveryAddressCityWithZip — This variable contains the recipient's postcode and town.
* $DeliveryAddressCompany — This variable contains the recipient's company name.
* $DeliveryAddressCountry — This variable contains the name of the recipient's country.
* $DeliveryAddressCountryID — This variable contains the recipient's country ID. The ID is assigned by the system.
* $DeliveryAddressCountryIsoCode — This variable contains the ISO code of the recipient's country.
* $DeliveryAddressFirstName — This variable contains the recipient's first name.
* $DeliveryAddressFullName — This variable contains the recipient's complete name, i.e. their first name and surname.
* $DeliveryAddressLastName — This variable contains the recipient's surname.
* $DeliveryAddressPhone — This variable contains the recipient's phone number.
* $DeliveryAddressState — This variable contains the name of the recipient's state/region.
* $DeliveryAddressStreet — This variable contains the name of the recipient's street.
* $DeliveryAddressZip — This variable contains the recipient's postcode.
* $Domain
* $DomainCSR
* $DomainCertType
* $DomainDNS
* $DomainFQDN
* $DomainID
* $DomainIP
* $EbaySellerAccount
* $EbayUniquePaymentID
* $EmailFrom — This variable contains an email's sender.
* $EmailMessage — This variable contains the email message of a tell-a-friend email.
* $EmailSubject — This variable contains the customer title.
* $EventBillable
* $EventBilled
* $EventBilledRequiringPayment
* $EventDuration
* $EventInfo
* $EventNotBilled
* $EventNotBilledRequiringPayment
* $EventStaffer
* $EventType
* $ExternalOrderID — This variable contains the external order ID for orders not generated on external platforms.
* $ForumSubscription
* $GeneralTermsConditionsHTML — This variable contains the terms and conditions in HTML format.
* $GeneralTermsConditionsText — This variable contains the terms and conditions in text format.
* $InvoiceTotal — This variable contains the gross total invoice amount with a comma as the decimal separator.
* $InvoiceTotalDecimalSeparatorDot — This variable contains the gross total invoice amount with a dot as the decimal separator.
* $InvoiceTotalNet — This variable contains the net total invoice amount with a comma as the decimal separator.
* $IsNewsletterActive
* $ItemCategoryLevel1List
* $ItemListHTML
* $ItemListPlain
* $ItemURLTellAFriend — This variable contains an item URL that can be emailed to others to recommend the item.
* $LegalDisclosureHTML — This variable contains the legal disclosure in HTML format.
* $LegalDisclosureText — This variable contains the legal disclosure in text format.
* $MethodOfPaymentID — This variable contains the payment method ID. The ID is assigned by the system. The IDs are listed in the Setup » Orders » Payment » Payment methods menu.
* $MethodOfPaymentName — This variable contains the name of the payment method as it was entered in the Setup » Orders » Payment » Payment methods menu.
* $NewCustomerEmail
* $NewsletterConfirmURL — This variable contains the URL for confirming the newsletter subscription.
* $OpenAmount — This variable contains the outstanding amount.
* $OrderAccessKey
* $OrderCount — This variable contains the number of orders.
* $OrderDate — This variable contains the order date.
* $OrderEarliestDeliveryDate — This variable contains the estimated delivery date.
* $OrderEstimatedDeliveryDate — This variable contains the estimated delivery date.
* $OrderEstimatedShipmentDate — This variable contains the estimated shipping date.
* $OrderID — This variable contains the order ID.
* $OrderReturnDate — This variable contains the date of incoming returns.
* $OrderStatusID — This variable contains the order's status ID.
* $OrderStatusLabel — This variable contains the order's status text.
* $OrderTotalNet — This variable contains the net order value.
* $OrderType — This variable contains the order type.
* $OverpaidAmount — This variable contains the overpaid amount.
* $PackageCount
* $PaidAmount — This variable contains the amount already paid.
* $PartialPaymentAmount — This variable contains the amount of the partial payment.
* $PartialPaymentOpenAmount — This variable contains the outstanding partial payment amount.
* $PaymentDate — This variable contains the date of the incoming payment.
* $PlentyID
* $PrivacyPolicyHTML — This variable contains the privacy policy in HTML format.
* $PrivacyPolicyText — This variable contains the privacy policy in text format.
* $RebateAmount — This variable contains a discount value.
* $ReferrerID — This variable contains the referrer ID. The ID is assigned by the system. The IDs are listed in the Setup » Orders » Order referrer menu.
* $ReferrerName — This variable contains the name of the order referrer as it was entered in the Setup » Orders » Order referrer menu.
* $ReorderDeliveryDate — This variable contains the reorder's delivery date.
* $ReorderID — This variable contains the reorder ID.
* $ReturnReasonID
* $ReturnReasonLabel
* $SchedulerEndDate — This variable contains the date on which the subscription order ends.
* $SchedulerExecutionCount — This variable contains the number of orders included in the subscription order.
* $SchedulerID — This variable contains the subscription order ID.
* $SchedulerInterval — This variable contains the subscription interval.
* $SchedulerStartDate — This variable contains the date on which the subscription order starts.
* $SchedulerTotalAmount — This variable contains the total invoice amount for all orders of the subscription order.
* $ShippingCosts — This variable contains the shipping costs.
* $ShippingProfileID — This variable contains the shipping profile ID. The ID is assigned by the system. The IDs are listed in the Setup » Orders » Shipping » Shipping options » Tab: Shipping profiles menu.
* $ShippingProfileName — This variable contains the shipping profile's name.
* $ShippingServiceProviderID — This variable contains the shipping service provider's ID. The ID is assigned by the system. The IDs are listed in the Setup » Orders » Shipping » Shipping options » Tab: Shipping service provider menu.
* $ShippingServiceProviderName — This variable contains the shipping service provider's name.
* $SignatureHTML — This variable contains the signature that was set for this client (store) in HTML format. This signature is saved in the Setup » Client » Select client » Email » Signature menu.
* $SignatureText — This variable contains the signature that was set for this client (store) in text format. This signature is saved in the Setup » Client » Select client » Email » Signature menu.
* $SystemPassword
* $SystemURL
* $SystemUsername
* $TicketBackendURL — This variable contains the ticket URL for the plentymarkets back end. For this variable to be populated, an email template must be created.
* $TicketHistory — This variable contains the last process that was saved in the ticket. This can be a comment or a message. For this variable to be populated, an email template and event procedures must be created. The event procedures must be based on the events New comment, New message from employee or New message from customer. This variable will then be populated based on the event. The variable will not be populated if any other event occurs.
* $TicketID — This variable contains the ticket ID. For this variable to be populated, an email template must be created.
* $TicketLastComment — This variable contains the last comment that was saved in the ticket. For this variable to be populated, an email template and an event procedure must be created. This event procedure must be based on the event New comment. The variable will not be populated if any other event occurs.
* $TicketLastMessage — This variable contains the last message that was saved in the ticket. For this variable to be populated, an email template and an event procedure must be created. The event procedure must be based on the event New message from employee or New message from customer. We recommend that you create an event procedure for each of these events. This will ensure that you receive an email, regardless whether an employee or a customer writes to you. The variable will not be populated if any other event occurs.
* $TicketPriority — This variable contains the ticket's priority. For this variable to be populated, an email template must be created.
* $TicketStatus — This variable contains the ticket status. For this variable to be populated, an email template must be created.
* $TicketTags
* $TicketTitle — This variable contains the ticket title. For this variable to be populated, an email template must be created.
* $TicketURL — This variable contains the ticket URL for the online store's My account area. For this variable to be populated, an email template must be created.
* $TodaysDate — This variable contains the current date.
* $TotalVAT
* $TrackingURL
* $TrustedShopsRating — This variable contains the result of the reviews submitted to Trusted Shops.
* $TrustedShopsRatingEmailButton — This variable contains the button for submitting a Trusted Shops review. This button can be inserted into emails.
* $TrustedShopsRatingShopButton — This variable contains the button for submitting a Trusted Shops review. This button can be inserted into the layout.
* $TrustedShopsSeal — This variable contains the Trusted Shops Trustbadge.
* $ValueOfItems
* $WarehouseID — This variable contains the warehouse ID. The ID is assigned by the system. The ID is listed in the Setup » Stock » Warehouse » Settings menu.
* $WebstoreID — This variable contains the client ID. The ID is assigned by the system. The ID is listed in the Setup » Client » Select client » Settings menu under Webstore ID.
* $WithdrawalFormHTML
* $WithdrawalFormText
