= ItemView
:lang: en
// include::{includedir}/_header.adoc[]
:keywords: ItemView
:position: 10004

//  auto generated content Thu, 06 Jul 2017 00:26:22 +0200
== Short description

This section contains information on the functions and variables for designing item layouts, e.g. lists, product pages and the item search.

== Global Template Functions

* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-container-formitemfeedback, Container_FormItemFeedback>> — Returns the template FormItemFeedback. This template is used to display a form in which customers can give feedback on items.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-container-itemviewadvancedorderitemslist, Container_ItemViewAdvancedOrderItemsList>> — Returns the template ItemViewAdvancedOrderItemsList. This template is used to display a list of preordered items.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-container-itemviewadvancedorderitemslist2, Container_ItemViewAdvancedOrderItemsList2>> — Returns the template ItemViewAdvancedOrderItemsList2. This template is used to display a list of preordered items.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-container-itemviewadvancedorderitemslist3, Container_ItemViewAdvancedOrderItemsList3>> — Returns the template ItemViewAdvancedOrderItemsList3. This template is used to display a list of preordered items.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-container-itemviewadvancedorderitemsmultipageslist, Container_ItemViewAdvancedOrderItemsMultiPagesList>> — Returns the template ItemViewAdvancedOrderItemsMultiPagesList. This template is used to display a multi-page list of preordered items.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-container-itemviewbasketitemslist, Container_ItemViewBasketItemsList>> — Returns the template ItemViewBasketItemsList. This template is used to display a list of shopping cart items.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-container-itemviewbasketitemslist2, Container_ItemViewBasketItemsList2>> — Returns the template ItemViewBasketItemsList2. This template is used to display a list of shopping cart items.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-container-itemviewbasketpreviewlist, Container_ItemViewBasketPreviewList>> — Returns the template ItemViewBasketPreviewList. This template is used to display a preview of shopping cart items.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-container-itemviewcategorieslist, Container_ItemViewCategoriesList>> — Returns the template ItemViewCategoriesList. This template is used to display items of a category.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-container-itemviewcategorieslist2, Container_ItemViewCategoriesList2>> — Returns the template ItemViewCategoriesList2. This template is used to display items of a category.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-container-itemviewcategorieslist3, Container_ItemViewCategoriesList3>> — Returns the template ItemViewCategoriesList3. This template is used to display items of a category.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-container-itemviewcategorieslist4, Container_ItemViewCategoriesList4>> — Returns the template ItemViewCategoriesList4. This template is used to display items of a category.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-container-itemviewcategorieslist5, Container_ItemViewCategoriesList5>> — Returns the template ItemViewCategoriesList5. This template is used to display items of a category.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-container-itemviewcategorieslist6, Container_ItemViewCategoriesList6>> — Returns the template ItemViewCategoriesList6. This template is used to display items of a category.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-container-itemviewcategorieslist7, Container_ItemViewCategoriesList7>> — Returns the template ItemViewCategoriesList7. This template is used to display items of a category.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-container-itemviewcategorieslist8, Container_ItemViewCategoriesList8>> — Returns the template ItemViewCategoriesList8. This template is used to display items of a category.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-container-itemviewcategorieslist9, Container_ItemViewCategoriesList9>> — Returns the template ItemViewCategoriesList9. This template is used to display items of a category.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-container-itemviewcategorieslist10, Container_ItemViewCategoriesList10>> — Returns the template ItemViewCategoriesList10. This template is used to display items of a category.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-container-itemviewcrosssellingitemslist, Container_ItemViewCrossSellingItemsList>> — Returns the template ItemViewCrossSellingItemsList. This template is used to display a list of cross-selling items.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-container-itemviewcrosssellingitemslist2, Container_ItemViewCrossSellingItemsList2>> — Returns the template ItemViewCrossSellingItemsList2. This template is used to display a list of cross-selling items.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-container-itemviewcrosssellingitemslist3, Container_ItemViewCrossSellingItemsList3>> — Returns the template ItemViewCrossSellingItemsList3. This template is used to display a list of cross-selling items.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-container-itemviewfurtheritemslist, Container_ItemViewFurtherItemsList>> — Returns the template ItemViewFurtherItemsList. This template allows you to change the layout of the items of an item list. This is achieved by applying a different template.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-container-itemviewfurtheritemslist2, Container_ItemViewFurtherItemsList2>> — Returns the template ItemViewFurtherItemsList2. This template allows you to change the layout of the items of an item list. This is achieved by applying a different template.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-container-itemviewfurtheritemslist3, Container_ItemViewFurtherItemsList3>> — Returns the template ItemViewFurtherItemsList3. This template allows you to change the layout of the items of an item list. This is achieved by applying a different template.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-container-itemviewfurtheritemslist4, Container_ItemViewFurtherItemsList4>> — Returns the template ItemViewFurtherItemsList4. This template allows you to change the layout of the items of an item list. This is achieved by applying a different template.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-container-itemviewfurtheritemslist5, Container_ItemViewFurtherItemsList5>> — Returns the template ItemViewFurtherItemsList5. This template allows you to change the layout of the items of an item list. This is achieved by applying a different template.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-container-itemviewfurtheritemslist6, Container_ItemViewFurtherItemsList6>> — Returns the template ItemViewFurtherItemsList6. This template allows you to change the layout of the items of an item list. This is achieved by applying a different template.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-container-itemviewitemtobasketconfirmationoverlay, Container_ItemViewItemToBasketConfirmationOverlay>> — Returns the template ItemViewItemToBasketConfirmationOverlay. This template is used to display an overlay to confirm that the item was placed in the shopping cart.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-container-itemviewitemsbypositionlist, Container_ItemViewItemsByPositionList>> — Returns the template ItemViewItemsByPositionList. This template is used to display a list of items sorted in descending order by item position.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-container-itemviewitemsbypositionlist2, Container_ItemViewItemsByPositionList2>> — Returns the template ItemViewItemsByPositionList2. This template is used to display a list of items sorted in descending order by item position.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-container-itemviewitemsbypositionmultipageslist, Container_ItemViewItemsByPositionMultiPagesList>> — Returns the template ItemViewItemsByPositionMultiPagesList. This template is used to display a multi-page list of items sorted in descending order by item position.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-container-itemviewlastseenlist, Container_ItemViewLastSeenList>> — Returns the template ItemViewLastSeenList. This template is used to display a list of the last viewed items.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-container-itemviewlastseenlist2, Container_ItemViewLastSeenList2>> — Returns the template ItemViewLastSeenList2. This template is used to display a list of the last viewed items.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-container-itemviewlatestitemslist, Container_ItemViewLatestItemsList>> — Returns the template ItemViewLatestItemsList. This template is used to display a list of the latest items.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-container-itemviewlatestitemslist2, Container_ItemViewLatestItemsList2>> — Returns the template ItemViewLatestItemsList2. This template is used to display a list of the latest items.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-container-itemviewlatestitemslist2bydate, Container_ItemViewLatestItemsList2ByDate>> — Returns the template ItemViewLatestItemsList2ByDate. This template is used to display a list of the latest items sorted by date.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-container-itemviewlatestitemslist3, Container_ItemViewLatestItemsList3>> — Returns the template ItemViewLatestItemsList3. This template is used to display a list of the latest items.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-container-itemviewlatestitemslist3bydate, Container_ItemViewLatestItemsList3ByDate>> — Returns the template ItemViewLatestItemsList3ByDate. This template is used to display a list of the latest items sorted by date.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-container-itemviewlatestitemslistbydate, Container_ItemViewLatestItemsListByDate>> — Returns the template ItemViewLatestItemsListByDate. This template is used to display a list of the latest items sorted by date.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-container-itemviewlatestitemsmultipageslist, Container_ItemViewLatestItemsMultiPagesList>> — Returns the template ItemViewLatestItemsMultiPagesList. This template is used to display a multi-page list of the latest items.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-container-itemviewlatestitemsmultipageslist2, Container_ItemViewLatestItemsMultiPagesList2>> — Returns the template ItemViewLatestItemsMultiPagesList2. This template is used to display a multi-page list of the latest items.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-container-itemviewlatestitemsmultipageslist2bydate, Container_ItemViewLatestItemsMultiPagesList2ByDate>> — Returns the template ItemViewLatestItemsMultiPagesList2ByDate. This template is used to display a multi-page list of the latest items sorted by date.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-container-itemviewlatestitemsmultipageslistbydate, Container_ItemViewLatestItemsMultiPagesListByDate>> — Returns the template ItemViewLatestItemsMultiPagesListByDate. This template is used to display a multi-page list of the latest items sorted by date.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-container-itemviewliveshopping, Container_ItemViewLiveShopping>> — Returns the template ItemViewLiveShopping. This template is used to display a live shopping view.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-container-itemviewliveshopping2, Container_ItemViewLiveShopping2>> — Returns the template ItemViewLiveShopping2. This template is used to display a live shopping view.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-container-itemviewmanualselectionlist, Container_ItemViewManualSelectionList>> — Returns the template ItemViewManualSelectionList. This template is used to display a list of manually selected items.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-container-itemviewmanualselectionlist2, Container_ItemViewManualSelectionList2>> — Returns the template ItemViewManualSelectionList2. This template is used to display a list of manually selected items.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-container-itemviewmanualselectionlist3, Container_ItemViewManualSelectionList3>> — Returns the template ItemViewManualSelectionList3. This template is used to display a list of manually selected items.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-container-itemviewmanualselectionlist4, Container_ItemViewManualSelectionList4>> — Returns the template ItemViewManualSelectionList4. This template is used to display a list of manually selected items.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-container-itemviewmanualselectionlist5, Container_ItemViewManualSelectionList5>> — Returns the template ItemViewManualSelectionList5. This template is used to display a list of manually selected items.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-container-itemviewmanualselectionlist6, Container_ItemViewManualSelectionList6>> — Returns the template ItemViewManualSelectionList6. This template is used to display a list of manually selected items.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-container-itemviewrandomlist, Container_ItemViewRandomList>> — Returns the template ItemViewRandomList. This template is used to display a list of randomly selected items.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-container-itemviewsinglecrosssellingitem, Container_ItemViewSingleCrossSellingItem>> — Returns the template ItemViewSingleCrossSellingItem. This template is used to display a single item view of a cross-selling item.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-container-itemviewsingleitem, Container_ItemViewSingleItem>> — Returns the ItemViewSingleItem template. This template is used to display a single item view.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-container-itemviewsingleitem2, Container_ItemViewSingleItem2>> — Returns the ItemViewSingleItem2 template. This template is used to display a single item view.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-container-itemviewsingleitem3, Container_ItemViewSingleItem3>> — Returns the ItemViewSingleItem3 template. This template is used to display a single item view.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-container-itemviewsingleitem4, Container_ItemViewSingleItem4>> — Returns the ItemViewSingleItem4 template. This template is used to display a single item view.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-container-itemviewsingleitem5, Container_ItemViewSingleItem5>> — Returns the ItemViewSingleItem5 template. This template is used to display a single item view.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-container-itemviewspecialofferslist, Container_ItemViewSpecialOffersList>> — Returns the ItemViewSpecialOffersList template. This template is used to display a list of special offer items.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-container-itemviewspecialofferslist2, Container_ItemViewSpecialOffersList2>> — Returns the ItemViewSpecialOffersList2 template. This template is used to display a list of special offer items.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-container-itemviewspecialoffersmultipageslist, Container_ItemViewSpecialOffersMultiPagesList>> — Returns the ItemViewSpecialOffersMultiPagesList template. This template is used to display a multi-page list of special offer items.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-container-itemviewtopsellerslist, Container_ItemViewTopSellersList>> — Returns the ItemViewTopSellersList template. This template is used to display a list of top-selling items.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-container-itemviewtopsellerslist2, Container_ItemViewTopSellersList2>> — Returns the ItemViewTopSellersList2 template. This template is used to display a list of top-selling items.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-container-itemviewtopsellersmultipageslist, Container_ItemViewTopSellersMultiPagesList>> — Returns the ItemViewTopSellersMultiPagesList template. This template is used to display a multi-page list of top-selling items.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-container-yoochoose-recommendations, Container_YOOCHOOSE_Recommendations>> — Corresponds to the template Container_ItemViewCrossSellingItemsList or Container_ItemViewCrossSellingItemsList2. However, the items that were recommended by YOOCHOOSE are used instead of the cross-selling items. Youchoose must be activated in the *Setup » Client » Select client » Services » YOOCHOOSE* menu.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-getdeliverydate, GetDeliveryDate>>
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-getitempropertieslistbygroupid, GetItemPropertiesListByGroupId>> — Returns an array of data fields for all characteristics of a characteristics group.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-getitemviewadvancedorderitemslist, GetItemViewAdvancedOrderItemsList>> — Returns an array of items that can be preordered.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-getitemviewadvancedorderitemslist2, GetItemViewAdvancedOrderItemsList2>> — Returns an array of items that can be preordered.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-getitemviewadvancedorderitemslist3, GetItemViewAdvancedOrderItemsList3>> — Returns an array of items that can be preordered.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-getitemviewadvancedorderitemsmultipageslist, GetItemViewAdvancedOrderItemsMultiPagesList>> — Returns an multi-page array of items that can be preordered. You can limit the number of items per page (optional) and only display items of the current category (optional).
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-getitemviewbasketitemslist, GetItemViewBasketItemsList>> — Returns an array of the items in the shopping cart.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-getitemviewbasketitemslist2, GetItemViewBasketItemsList2>> — Returns an array of the items in the shopping cart.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-getitemviewbasketpreviewlist, GetItemViewBasketPreviewList>> — Returns an array with a preview of the items in the shopping cart.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-getitemviewcategorieslist, GetItemViewCategoriesList>> — Returns an array of all item data associated with the current category.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-getitemviewcategorieslist2, GetItemViewCategoriesList2>> — Returns an array of all item data associated with the current category.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-getitemviewcategorieslist3, GetItemViewCategoriesList3>> — Returns an array of all item data associated with the current category.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-getitemviewcategorieslist4, GetItemViewCategoriesList4>> — Returns an array of all item data associated with the current category.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-getitemviewcategorieslist5, GetItemViewCategoriesList5>> — Returns an array of all item data associated with the current category.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-getitemviewcategorieslist6, GetItemViewCategoriesList6>> — Returns an array of all item data associated with the current category.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-getitemviewcategorieslist7, GetItemViewCategoriesList7>> — Returns an array of all item data associated with the current category.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-getitemviewcategorieslist8, GetItemViewCategoriesList8>> — Returns an array of all item data associated with the current category.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-getitemviewcategorieslist9, GetItemViewCategoriesList9>> — Returns an array of all item data associated with the current category.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-getitemviewcategorieslist10, GetItemViewCategoriesList10>> — Returns an array of all item data associated with the current category.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-getitemviewcrosssellingitemslist, GetItemViewCrossSellingItemsList>> — Returns an array of all item data defined as cross-selling items. Depending on the transfer parameters, the cross-selling items of the current item (SingleItem), of the last viewed item (LastSeenItem) or of the items in the shopping cart are returned.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-getitemviewcrosssellingitemslist2, GetItemViewCrossSellingItemsList2>> — Returns an array of all item data defined as cross-selling items. Depending on the transfer parameters, the cross-selling items of the current item (SingleItem), of the last viewed item (LastSeenItem) or of the items in the shopping cart are returned.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-getitemviewcrosssellingitemslist3, GetItemViewCrossSellingItemsList3>> — Returns an array of all item data defined as cross-selling items. Depending on the transfer parameters, the cross-selling items of the current item (SingleItem), of the last viewed item (LastSeenItem) or of the items in the shopping cart are returned.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-getitemviewcrosssellingitemslistbycharacter, GetItemViewCrossSellingItemsListByCharacter>> — Returns an array of items that the specified characteristic is linked to. The item ID and the characteristic ID must be specified. This can be limited to displaying items of a particular cross-selling type (optional).
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-getitemviewcrosssellingitemslistbytype, GetItemViewCrossSellingItemsListByType>> — Returns an array of the items defined as cross-selling items with the specified cross-selling relationship. The item ID and the cross-selling type must be specified.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-getitemviewitemparamslist, GetItemViewItemParamsList>> — Returns an array with characteristics belonging to an item. The item ID must be specified.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-getitemviewitemsbypositionlist, GetItemViewItemsByPositionList>> — Returns an array of items sorted by item position.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-getitemviewitemsbypositionlist2, GetItemViewItemsByPositionList2>> — Returns an array of items sorted by item position.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-getitemviewitemsbypositionmultipageslist, GetItemViewItemsByPositionMultiPagesList>> — Returns an array of items sorted by item position. The list is displayed on several pages.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-getitemviewitemslistbycharacter, GetItemViewItemsListByCharacter>> — Returns an array of items that the specified characteristic is linked to.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-getitemviewlastseenlist, GetItemViewLastSeenList>> — Returns an array of the last viewed items. This can be limited to displaying items of the current category (optional).
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-getitemviewlastseenlist2, GetItemViewLastSeenList2>> — Returns an array of the last viewed items. This can be limited to displaying items of the current category (optional).
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-getitemviewlatestitemslist, GetItemViewLatestItemsList>> — Returns an array of the latest items. This can be limited to displaying items of the current category (optional).
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-getitemviewlatestitemslist2, GetItemViewLatestItemsList2>> — Returns an array of the latest items. This can be limited to displaying items of the current category (optional).
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-getitemviewlatestitemslist2bydate, GetItemViewLatestItemsList2ByDate>> — Returns an array of the latest items sorted by date. This can be limited to displaying items of the current category (optional).
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-getitemviewlatestitemslist3, GetItemViewLatestItemsList3>> — Returns an array of the latest items. This can be limited to displaying items of the current category (optional).
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-getitemviewlatestitemslist3bydate, GetItemViewLatestItemsList3ByDate>> — Returns an array of the latest items sorted by date. This can be limited to displaying items of the current category (optional).
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-getitemviewlatestitemslistbydate, GetItemViewLatestItemsListByDate>> — Returns an array of the latest items sorted by date. This can be limited to displaying items of the current category (optional).
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-getitemviewlatestitemsmultipageslist, GetItemViewLatestItemsMultiPagesList>> — Returns an multi-page array of the latest items. This can be limited to displaying items of the current category (optional).
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-getitemviewlatestitemsmultipageslist2, GetItemViewLatestItemsMultiPagesList2>> — Returns an multi-page array of the latest items. This can be limited to displaying items of the current category (optional).
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-getitemviewlatestitemsmultipageslist2bydate, GetItemViewLatestItemsMultiPagesList2ByDate>> — Returns an multi-page array of the latest items sorted by date. This can be limited to displaying items of the current category (optional).
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-getitemviewlatestitemsmultipageslistbydate, GetItemViewLatestItemsMultiPagesListByDate>> — Returns an multi-page array of the latest items sorted by date.  This can be limited to displaying items of the current category (optional).
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-getitemviewmanualselectionlist, GetItemViewManualSelectionList>> — Returns an array of manually selected items.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-getitemviewmanualselectionlist2, GetItemViewManualSelectionList2>> — Returns an array of manually selected items.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-getitemviewmanualselectionlist3, GetItemViewManualSelectionList3>> — Returns an array of manually selected items.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-getitemviewmanualselectionlist4, GetItemViewManualSelectionList4>> — Returns an array of manually selected items.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-getitemviewmanualselectionlist5, GetItemViewManualSelectionList5>> — Returns an array of manually selected items.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-getitemviewmanualselectionlist6, GetItemViewManualSelectionList6>> — Returns an array of manually selected items.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-getitemviewrandomlist, GetItemViewRandomList>> — Returns an array of randomly selected items.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-getitemviewspecialofferslist, GetItemViewSpecialOffersList>> — Returns an array of the items defined as special offer items.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-getitemviewspecialofferslist2, GetItemViewSpecialOffersList2>> — Returns an array of the items defined as special offer items.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-getitemviewspecialoffersmultipageslist, GetItemViewSpecialOffersMultiPagesList>> — Returns an array of the items defined as special offer items. The list is displayed on several pages.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-getitemviewtopsellerslist, GetItemViewTopSellersList>> — Returns an array of the top selling-items. This can be limited to displaying items of the current category (optional).
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-getitemviewtopsellerslist2, GetItemViewTopSellersList2>> — Returns an array of the top selling-items. This can be limited to displaying items of the current category (optional).
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-getitemviewtopsellersmultipageslist, GetItemViewTopSellersMultiPagesList>> — Returns an array of the top selling-items. The list is displayed on several pages. This can be limited to displaying items of the current category (optional).

== Templates

* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-itemviewitemtobasketconfirmationcontainer, ItemViewItemToBasketConfirmationContainer>>

== Global Template Variables

* $CHANGE_VIEW_TO_FURTHER_ITEMS_LIST — Is a constant for changing the item view. Is equivalent to the setting *ItemViewFurtherItemsList*.
* $CHANGE_VIEW_TO_FURTHER_ITEMS_LIST2 — Is a constant for changing the item view. Is equivalent to the setting *ItemViewFurtherItemsList2*.
* $CHANGE_VIEW_TO_FURTHER_ITEMS_LIST3 — Is a constant for changing the item view. Is equivalent to the setting *ItemViewFurtherItemsList3*.
* $CHANGE_VIEW_TO_FURTHER_ITEMS_LIST4 — Is a constant for changing the item view. Is equivalent to the setting *ItemViewFurtherItemsList4*.
* $CHANGE_VIEW_TO_FURTHER_ITEMS_LIST5 — Is a constant for changing the item view. Is equivalent to the setting *ItemViewFurtherItemsList5*.
* $CHANGE_VIEW_TO_FURTHER_ITEMS_LIST6 — Is a constant for changing the item view. Is equivalent to the setting *ItemViewFurtherItemsList6*.
* $CurrentItemId — Contains the current item's ID.
* $CurrentPage — Contains the current page's page number.
* $GROUP_ITEMS_BY_ATTRIBUTES — Is a constant for grouping items in the item category view. Is equivalent to the setting *Grouping by attributes*.
* $GROUP_ITEMS_BY_VARIANT — Is a constant for grouping items in the item category view. Is equivalent to the setting *Grouping by variations*.
* $GROUP_ITEMS_NO — Is a constant for variation grouping the item category view. Is equivalent to the setting *No grouping*.
* $ITEM_SORTING_ID_DESC — Is a constant for sorting items. Is equivalent to the setting *Item ID descending*.
* $ITEM_SORTING_NAME_ASC — Is a constant for sorting items. Is equivalent to the setting *Item name ascending*.
* $ITEM_SORTING_NAME_DESC — Is a constant for sorting items. Is equivalent to the setting *Item name descending*.
* $ITEM_SORTING_POSITION_ASC — Is a constant for sorting items. Is equivalent to the setting *Item position ascending*.
* $ITEM_SORTING_POSITION_DESC — Is a constant for sorting items. Is equivalent to the setting *Item position descending*.
* $ITEM_SORTING_PRICE_ASC — Is a constant for sorting items. Is equivalent to the setting *Price in ascending order*.
* $ITEM_SORTING_PRICE_DESC — Is a constant for sorting items. Is equivalent to the setting *Price in descending order*.
* $ITEM_SORTING_PRODUCER_NAME_ASC — Is a constant for sorting items. Is equivalent to the setting *Manufacturer name ascending*.
* $ITEM_SORTING_PUBLICATION_DATE_ASC
* $ITEM_SORTING_PUBLICATION_DATE_DESC
* $ITEM_SORTING_RANDOM — Is a constant for sorting items. Is equivalent to the setting *item_random* and means items are sorted randomly.
* $ITEM_SORTING_RELEASE_DATE_ASC — Is a constant for sorting items. Is equivalent to the setting *Release date ascending*.
* $ITEM_SORTING_RELEASE_DATE_DESC — Is a constant for sorting items. Is equivalent to the setting *Release date descending*.
