= Setting up clients
:author: team-webshop
:keywords: Store, Client, Shop, plentyShop, Webshop, Online shop
:id: BU7X5JP
:description: Learn how to set up, manage, and delete additional clients in plentymarkets. 
:icons: font
:docinfodir: /workspace/manual-adoc
:docinfo1:

*Setup » Client » Select client*

== Content of this chapter

This chapter explains various basic settings for configuring your xref:omni-channel:online-store.adoc#[plentyShop]. Here you can save settings for your default shop and configure the xref:crm:sending-emails.adoc#[email service]. Settings for *search engine optimization* are particularly important. These settings ensure that your plentyShop is easy to find on the Internet. This chapter also explains basic settings for xref:item:managing-categories.adoc#[categories], the xref:omni-channel:my-account.adoc#[my account] area and the xref:omni-channel:order-process.adoc#[order process]. It also provides information about the basic settings of your xref:omni-channel:item-layouts.adoc#[item layouts].

[TIP]
.Tip
====
Every additional plentyShop or client (store) is configured in its own menu. These additional menus have the same structure as the Standard menu. The system automatically gives the menu the same name as the online shop.
====

[#basic-settings]
== Basic settings

Here you can see your shops's IDs and additional data such as the store type and the domain.

[WARNING]
.Users will be logged out
====
Whenever you carry out changes in this menu and click on the save icon, other users will be logged out automatically and will need to log in again. This ensures that the changes will also apply to the other user profiles. Therefore, it is recommended that you announce changes in advance.
====

== Configuration

Pay attention to the explanations given in the following table and carry out the configuration as desired.

.entering basic settings
[cols="1,3"]
|====
|Setting |Explanation

| *Store ID*
|The store ID is the ID for the shop or client (store). The store ID of a client (store) is displayed in the basic settings for that particular store. +
Default store = *0* +
First client (store) = *1* +
Second client (store) = *2* +
etc. +
External stores also receive a store ID.

| *plenty ID*
|The plentymarkets system's ID is displayed here.

| *Store type*
|Indicates the store type: *plentymarkets* or *Shopware*.

| *Domain*
|The store domain's URL is displayed here. Click on the *preview icon* to view your plentyShop.

| *Name*
|The name of the shop.

| *Default language*
|Select the default language for the online store.

| *Default location*
|Select which location should be the default location. This will be used in other areas, e.g. during the order process in the online store. As such, it affects how VAT is displayed. It is not possible to delete the default location.

| *eBay account*
|Select the eBay account(s) that should be linked with this store. The orders for this eBay account will automatically be assigned to this store. +
*Important*: If the same eBay account is selected for two different stores, then the orders will be assigned to whichever store has the lowest ID.
|====


== Links to other menus

Before you start working with the xref:crm:using-the-ticket-system.adoc#[ticket system] or sending out xref:crm:sending-newsletters.adoc#[newsletters], you will first have to save the configurations in the xref:crm:sending-emails.adoc#[email] area. The settings saved in the "Item layouts" area lay the foundation for managing your xref:item:item.adoc#[items].

Direct access to important pages of the manual

* xref:omni-channel:setting-up-clients.adoc#basic-settings[Basic settings]
* xref:omni-channel:multilingual-online-store.adoc#[Multilingualism]
* xref:omni-channel:online-store.adoc#legal-information[Legal information]
* xref:crm:sending-emails.adoc#100[Access data]
* xref:crm:sending-emails.adoc#1200[email templates]
* xref:omni-channel:item-layouts.adoc#[Item layouts]
* *URL structure*
* *Sitemap.xml*
* xref:item:managing-categories.adoc#[Categories]
* xref:omni-channel:my-account.adoc#[My account]
* xref:omni-channel:order-process.adoc#[Order process]
* xref:omni-channel:extras.adoc#[External services]
* xref:omni-channel:trusted-shops.adoc#[Trusted Shops]
* xref:omni-channel:modules.adoc#[Modules]
