= Template functions
:page-index: false

== General information

The CMS syntax supports several kinds of functions. These functions can either be used globally or within specific templates.

== Global Functions

This section describes the functions that are used in both the web design and email templates.

Some PHP functions have been integrated into the CMS syntax. Their usage corresponds to that directly in PHP.

xref:omni-channel:cms-syntax.adoc#global-phpfunctions[Open PHP functions]

== Web design

[.row]
====
[.col-md-6]
.PageDesign
=====
This section primarily contains link functions that return URLs to specific sections such as categories, home page, shopping cart, etc.

xref:omni-channel:cms-syntax.adoc#web-design-pagedesign[Open PageDesign]
=====

[.col-md-6]
.Navigation
=====
The functions in this section call various containers for displaying navigation menus (category navigation).

xref:omni-channel:cms-syntax.adoc#web-design-navigation[Open navigation]
=====
====

[.row]
====
[.col-md-6]
.ItemView
=====
The largest number of containers and thus functions are available for displaying items (e.g. product page, search result).

xref:omni-channel:cms-syntax.adoc#web-design-itemview[Open ItemView]
=====

[.col-md-6]
.Category
=====
This section only contains a small number of functions. However, note the function Form() that is used to return forms.

xref:omni-channel:cms-syntax.adoc#web-design-category[Open Category]
=====
====
== email templates

Some link functions are available for using in email templates.

xref:omni-channel:cms-syntax.adoc#email-email[Open email]
