= Validator
:lang: en
// include::{includedir}/_header.adoc[]
:keywords: Validator
:position: 10010

//  auto generated content Thu, 06 Jul 2017 00:52:02 +0200
== Short description

This section contains information on the functions and variables for designing the validators. Validators check the details customers enter before these are saved. As soon as the order process data is submitted, the relevant validator template is called. For example, if the invoice address is submitted, the template ValidatorCustomerInvoiceAddress is called. If the customer did not fill in any fields of the invoice address that were defined as mandatory in the template, the respective error messages are returned. The data is not saved while error messages are still returned.

== Global Template Functions

* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-validator-adderror, AddError>> — Allows you to display an error message. All error messages are managed here: *Setup » Client » Settings » Languages*
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-validator-validateminimumbasketvalue, ValidateMinimumBasketValue>> — Checks the minimum order quantity.

== Templates

* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-validator-validatorcoupon, ValidatorCoupon>> — You can define checks for entering coupons in this template. This validator is called as soon as a coupon code is submitted.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-validator-validatorcustomerinvoiceaddress, ValidatorCustomerInvoiceAddress>> — You can define checks for the invoice address in this template. This validator is called when the invoice address is submitted during the order process.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-validator-validatorcustomershippingaddress, ValidatorCustomerShippingAddress>> — You can define checks for the delivery address in this template. This validator is called when the delivery address is submitted during the order process.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-validator-validatorplaceorder, ValidatorPlaceOrder>> — You can define checks for submitting the order in this template. For example, you can check if the terms and conditions or the cancellation rights were accepted by placing a check mark in the relevant check box.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-validator-validatorscheduler, ValidatorScheduler>> — You can define checks for submitting subscription settings in this template.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-validator-validatorshippingcountry, ValidatorShippingCountry>> — You can define checks for the country of delivery in this template. This validator is called when the country of delivery is submitted during the order process.
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-validator-validatorshippingprofile, ValidatorShippingProfile>> — You can define checks for the shipping method in this template. This validator is called when the shipping method is submitted during the order process.
