[#git-plugins]
= Git-Plugins

Wenn du plentysystems erweitern möchtest, aber kein Plugin mit der entsprechenden Funktionalität auf plentyMarketplace findest, kannst du deinem System Plugins über Git hinzuzufügen. Manche externen Entwickler:innen bieten Plugins auf diesem Weg an. Wenn du weitere Informationen zu Git-Plugins erhalten möchtest, nimm direkt mit diesen Entwickler:innen Kontakt auf. Nutze dafür entweder die link:https://marketplace.plentymarkets.com/partners[Partnerübersicht^], schreibe eine Nachricht in der Forumskategorie link:https://forum.plentymarkets.com/c/suche-biete/suche-biete-plugins[Suche/Biete^] oder erstelle eine link:https://marketplace.plentymarkets.com/plentyprojects[neue Projektanfrage^] auf plentyMarketplace.

[NOTE]
.Keine Prüfung durch plentysystems
====
Wenn ein Plugin auf plentyMarketplace hochgeladen wird, wird es durch Mitarbeiter:innen von plentysystems geprüft. Bei Plugins, die nicht über plentyMarketplace vertrieben werden, findet keine Prüfung statt. Das heißt, dass plentysystems die Funktionalität des Plugins in diesen Fällen nicht sicherstellen kann.

Möchtest du ein Plugin von einem Drittanbieter aus einer anderen Quelle als plentyMarketplace in deinem System einbinden, empfehlen wir dir, dich datenschutzrechtlich abzusichern und den Funktionsumfang des Plugins nach dem Einbinden gründlich zu prüfen.
====

[#zugriffstoken-private-repositorys]
== Zugriffstoken für private Repositorys erzeugen

Fügst du deinem System ein privates Repository hinzu, wird zusätzlich zur URL des Repositorys ein persönlicher Zugriffstoken benötigt. Dabei unterscheidet sich der Vorgang zum Erzeugen des Tokens leicht von Seite zu Seite.

[IMPORTANT]
.Unterstützte Anbieter
====
Aktuell werden folgende Anbieter unterstützt: GitHub, Bitbucket, GitLab. 

Wenn du ein Plugin über einen anderen Anbieter hinzufügst, leisten wir bei Fehlverhalten keinen Support. 
====

[tabs]
====
GitHub::
+
--
include::partial$git-zugriffstoken-github.adoc[]
--

Bitbucket::
+
--
include::partial$git-zugriffstoken-bitbucket.adoc[]
--

GitLab::
+
--
include::partial$git-zugriffstoken-gitlab.adoc[]
--
====

[#git-repository-hinzufuegen]
== Git-Repository hinzufügen

Im Folgenden wird beschrieben, wie du ein Git-Repository zu deinem System hinzufügst. Dadurch nutzt du das im Repository verwaltete Plugin.

Wenn du ein privates Repository hinzufügen möchtest, generiere zunächst einen Zugriffstoken wie zuvor beschrieben. Bei öffentlichen Repositorys benötigst du keinen Zugriffstoken.

include::partial$git-repository-hinzufuegen.adoc[]

include::partial$hinzugefuegte-plugins-installieren.adoc[]

[#git-repositorys-funktionsuebersicht]
== Funktionsübersicht

include::partial$git-repository-verwaltung.adoc[]
