[#plugin-prioritäten]
= Prioritäten der Plugins

Die Priorität eines Plugins legt fest, ob es vor oder nach den anderen Plugins in deinem Plugin-Set geladen wird. Diese legst du über einen Zahlenwert fest, 0 ist dabei der geringste Wert, Plugins mit einer Null als Priorität werden also als letztes geladen.

Das Festlegen einer Priorität wird dann wichtig, wenn die Plugins Abhängigkeiten untereinander haben. Beispielsweise muss das *Mirkakl* Plugin nach dem *Völkner/Conrad* Plugin geladen werden, das heißt, du musst dem *Mirakl Plugin* eine niedrigere Priorität zuweisen. Welche Prioritäten für welches Plugin eintragen musst, kannst du der Anleitung des Plugins entnehmen.

[.instruction]
Gehe wie folgt vor, um Prioritäten für ein Plugin zu vergeben:

. Öffne das Menü *Plugins » Plugin-Set-Übersicht » [Plugin-Set wählen] » Prioritäten festlegen*.
. Gehe in der Zeile des Plugins, dessen Priorität du ändern willst, in die Spalte *Priorität*.
. Trage die Priorität ein.
. *Speichere* (material:save[]) deine Einstellungen.

[ATTENTION]
.Falsche Prioritäten setzen

====
Setzt du falsche Prioritäten, die die Abhängigkeiten der Plugins untereinander nicht beachten, kann es sein, dass du dich nicht mehr normal in dein Backend einloggen kannst (sondern nur noch über den xref:willkommen:login-rundgang.adoc#70[abgesicherten Modus]). Falsch gesetzte Prioritäten können sich auch auf deinen Shop auswirken, zum Beispiel wenn du dein eigenes Theme benutzt und dieses die falsche Priorität hat, wird zuerst das Standard CSS-Theme geladen und nicht deins.

Sei deshalb vorsichtig beim Setzen der Prioritäten und beachte deshalb immer die Anleitungen der Plugins.
====

[.collapseBox]
.Ich habe die falsche Priorität gesetzt und kann mich nun nicht mehr in meinem System anmelden. Was kann ich tun?
--
Nutze den Login via Safemode unter https://plentymarkets-cloud-de.com/?safemode=1[] oder https://plentymarkets-cloud-ie.com/?safemode=1[], um dich im System einzuloggen. Im Anschluss änderst du die Prioritäten ab und stellst abschließend das Plugin-Set bereit. Nach der erfolgreichen Bereitstellung kannst du dich wieder normal im System anmelden.
--