= Barcodes and labels
:keywords: Barcode, Barcodes, Label, Labels, Item label, Item labels, Barcode type, Barcode types, GS1, GTIN, ISBN, QR, CODE 128, UPC, FNSKU, Number range, Unit price
:description: Learn to configure barcodes step by step and display them on item labels.
:author: team-item

////
zuletzt bearbeitet 01.12.2022
////

Barcodes are used to uniquely identify items.
For example, they are displayed on item labels or on documents like invoices and delivery notes.

This page guides you through the configuration step by step:

* xref:item:barcodes.adoc#100[Configure the barcode types]: Specify whether you need GTIN, ISBN, UPC or QR barcodes.
* xref:item:barcodes.adoc#200[Acquire a pool of barcodes if needed]: If you don’t get barcodes directly from your manufacturer, i.e. if you sell your own brand of products, then you’ll need to acquire the actual barcodes from an organisation like GS1.
* xref:item:barcodes.adoc#300[Assign the barcodes to your items]: Link your barcodes to your variations.
* xref:item:barcodes.adoc#900[Design the item labels]: Decide how large the label should be and which information should be displayed on the label.
* xref:item:barcodes.adoc#1000[Print the item labels]: Labels can be generated and printed for a specific storage location, a specific variation or for other use-cases.

[#100]
== Configuring barcode types

Which types of barcodes do you need?
Which sales platforms will you use each type of barcode on?
First, save some basic information about your barcodes.

. Go to *Setup » Item » Barcode*.
. Click on icon:plus[role="darkGrey"]. +
→ A pop-up window opens. This window is divided into several steps.
. Carry out the settings in each step.

---

[discrete]
==== Step: Name

[cols="1,4a"]
|===
|Setting |Explanation

| *Name* +
[red]#(Mandatory field)#
|Enter a name for the barcode type.
The name is the keyword or phrase that highlights the data record.

*_Tip_*: The name can include spaces. In other words, the name can consist of multiple words.

| *Type* +
[red]#(Mandatory field)#
|Select the type from the drop-down list.

[cols="1,4"]
!===

!
*GTIN 8*; +
*GTIN 13*; +
*GTIN 14*; +
*GTIN 128*
! The Global Trade Item Number (formerly European Article Number, EAN) is a product barcode for items.
The GTIN consists of 8, 13, 14 or a maximum of 128 characters and is centrally administered and issued for manufacturers upon request.

13-digit GTINs consist of the basic group, the item reference and the check digit.
The basic group has 7 to 9 digits and contains the GS1 prefix with the country code, for example 500 to 509 for the UK, as well as the company number.
The item reference of the manufacturer consists of 3 to 5 digits (depending on the basic group's length).
The check digit is the last digit.

! *ISBN*
! The International Standard Book Number is a unique number of 10 or 13 characters to register books and other independent, discontinuous publications like multimedia products and software.

! *QR*
! Quick Response Code.
The code contains data such as the version, the data format and other information.

! *CODE 128*
! Alphanumeric barcode.
The Code128 consists of start character, encoded data, check character and stop character.

! *UPC*
! The Universal Product Code is a product barcode for items.
The UPC is a 12-digit number.
By adding a leading *0*, this barcode can be used as a 13-digit GTIN.

!===

*_Practical example: FNSKU barcodes_*:
Even though there’s not a specific barcode type for FNSKU, you can still configure FNSKU barcodes in plentymarkets.
Enter a meaningful name and select the desired type, e.g. Code 128.

|===

---

[discrete]
==== Step: Sales channels

[cols="1,4a"]
|===
|Setting |Explanation

| *Barcode sales channel*
|Which sales platforms will you use this type of barcode on?
Select all of the appropriate sales channels (icon:check-square[role="blue"]).

|===

---

[discrete]
==== Step: Done

[cols="1,4"]
|===
|Setting |Explanation

| *Summary*
a|Here you can see a summary of the settings that you selected.
Click on *Create barcode* if you are satisfied with the settings.

Afterwards, you will have the following options:

[cols="1,4a"]
!===

! *To the barcode*
!The pop-up window will close and the newly created barcode type will open for further editing.

! *Create another barcode*
!The pop-up window will re-start for the next barcode type.

! *Close*
!The pop-up window will close.

!===

|===

[#200]
== Acquiring barcodes and saving a number range

Do you already have GTINs (barcodes) for your items?
You might not if you directly import items and your manufacturer doesn’t assign GTINs.
In this case, you can acquire GTINs from an organisation like link:https://www.gs1uk.org/[GS1^].
For example, you can buy a range of 1000 barcode numbers.

But how do you get this pool of barcodes into plentymarkets?
You don’t need to import them.
Simply tell plentymarkets how many GTINs you have and which number your range begins with.
Then when you xref:item:barcodes.adoc#300[assign a barcode to an item], the next available barcode will automatically be used.

[.instruction]
Saving a GTIN number range:

. Go to *Setup » Item » GTIN*.
. Enter the starting value. +
→ For 13 digit GTINs this must be a 12 digit value.
The check digit is entered automatically.
. Enter the number of GTINs.
. *Save* (terra:save[role="green"]) the settings.

[TIP]
.Why doesn't the number range look consecutive?
====
At first glance, it might not look like the numbers always increase by 1.
But don’t forget that the last digit is a check digit.
The 12 places before it are consecutive.
Leave out the check digit when you enter the starting value.
====

[#300]
== Assigning barcodes to products

A barcode is linked to xref:item:structure.adoc#[an individual variation] and not to the item as a whole.
So if you sell a t-shirt in the colours red or blue, for example, then the red and blue t-shirts will each have their own barcode.

There are a few different ways to assign barcodes to products:

[.collapseBox]
.*Manually*
--

If you only have a few products, then it will probably be quickest to manually link barcodes.

//neue Artikel-UI - Konfig unten löschen und dafür die include einblenden
//include::page$directory.adoc[tag=barcode-manually-link]

. Go to *Item » Edit item » [Open variation] » Tab: Settings » Area: Barcode*.
. Select a previously configured barcode type from the drop-down list.
. Click on *Add* (icon:plus[role="green"]). +
→ The barcode type is added and displayed in the list.
. Enter the code into the *Code* field.
. *Save* (terra:save[role="green"]) the settings.

--

[.collapseBox]
.*Import*
--

If you have lots of products, then it will probably be quickest to import the barcodes.

plentymarkets has an xref:data:ElasticSync.adoc#[import tool], which you can use to import several barcodes at once.
The idea is simple.
Rather than manually assigning barcodes to items, you’ll enter the same information into a CSV file and then import this file into your system.

* Instead of selecting the barcode type in the item data record, you’ll xref:data:elasticSync-item.adoc#1910[use the barcode type as a matching field].
* Instead of manually entering the barcode in the item data record, you’ll xref:data:elasticSync-item.adoc#2320[enter the barcode in a mapping field].

--

[.collapseBox]
.*Automatically from the number range*
--

If you bought a xref:item:barcodes.adoc#200[range of GTIN 13 barcodes], then plentymarkets can automatically assign the next available barcode to your item.

//neue Artikel-UI - Konfig unten löschen und dafür die include einblenden
//include::page$directory.adoc[tag=barcode-automatic-link]

. Go to *Item » Edit item » [Open variation] » Tab: Settings » Area: Barcode*.
. Select a previously configured GTIN 13 barcode type from the drop-down list.
. Click on *Add* (icon:plus[role="green"]). +
→ The barcode type is added and displayed in the list.
. Click on *Generate GTIN* (icon:execute[set=plenty]) to automatically insert the next available barcode.
. *Save* (terra:save[role="green"]) the settings.

//neue Artikel-UI - Tip einblenden und dafür den gleichen Tip weiter unten löschen
//TIP: Use the xref:item:group-functions.adoc#300[variation group function] to generate GTINs for several variations at the same time.

TIP: Use the xref:item:mass-processing.adoc#300[variation group function] or xref:item:mass-processing.adoc#600[variation batch processing] to generate GTINs for several variations at the same time.

TIP: This function is only available for the type *GTIN 13*. The button is deactivated for all other types.

--

[#700]
== Troubleshooting: Duplicate barcodes

It’s technically possible to save the same barcode for multiple variations.
If you don’t want duplicate barcodes, then you can search for and correct any duplicate codes in the system.

[#730]
=== Finding and correcting duplicates

. Go to *Setup » Item » Barcode*.
. Click on material:manage_search[role="darkGrey"] *Duplicates* in the left navigation bar. +
→ A list of all duplicate barcodes opens.
. Use the filters (material:tune[role="darkGrey"]) to narrow down the search results as needed.
. Click on the ID of the variation whose code should be changed. +
→ The variation opens.
. Edit the variation's code.
. *Save* (terra:save[role="darkGrey"]) the change.

[#760]
=== Modifying the default settings

How precise should the test for duplicate barcodes be?
Do you want to prevent duplicate barcodes altogether?
You can customise the settings to meet the needs of your company.

. Go to *Setup » Item » Settings*.
. Choose the settings for duplicate barcodes. Note the following table.
. *Save* (terra:save[role="green"]) the settings.

[TIP]
.The test is only conducted in the back end
====
How do you create barcodes?
Via the back end (user interface), import or REST?
The test for duplicate barcodes is only conducted in the back end.
It is possible to link duplicate barcodes via import or REST, regardless of the settings.
====

[cols="1,3a"]
|===
|Setting |Explanation

| *Precision of duplicate barcode check*
|How precise should the search be?
This setting controls how closely the system checks for duplicate barcodes.

[cols="1,3"]
!===

! *Barcode Definition*
!There is a check per numeric code.
In other words, the system checks whether a specific code is already saved for a specific definition.

*_Example_*:
If you’ve saved the barcode 1234 for the definition "GTIN 13_1", then you could still save the same code for the definition "GTIN 13_2".

! *Barcode Type*
!There is a check per barcode type.
For example: duplicate barcodes of the type GTIN.

! *Global*
!There is a check across all barcodes.

!===

| *Behaviour in case of duplicate barcodes*
|How should plentymarkets react if you try to assign a barcode to a product, but the barcode is already in use?

[cols="1,3"]
!===

! *Allow*
!It is possible to save duplicate barcodes.

! *Warn*
!It is possible to save duplicate barcodes.
However, you will see a yellow warning message, which tells you that the barcode is already saved for another variation.

! *Prevent*
!It is not possible to save duplicate barcodes.
You will see a red warning message, which tells you that the barcode was not saved because it is already being used for another variation.

!===

|===

[#900]
== Designing labels

Item labels are attached to an item or to the item packaging.
They include information like the price, content, barcode, etc.
First, you’ll design your labels with the help of templates.
Each template includes information about the size of the label, which data should be displayed on the label and where each piece of data should be positioned on the label.
You can create up to 10 label templates.

. Go to *Setup » Item » Labels*.
. Expand the *New template* area (icon:plus-square-o[role="darkGrey"]).
. Customise the settings to meet your needs:
.. xref:item:barcodes.adoc#930[Enter basic information and the label size].
.. xref:item:barcodes.adoc#960[Decide which data should appear on the label].
.. xref:item:barcodes.adoc#980[Configure the appearance of the label].
. *Save* (terra:save[role="green"]) the settings.

[#930]
=== Basic information and label size

[cols="1,3a"]
|===
|Setting |Explanation

| *Name*
|Enter an internal name for the label.
The name is not visible to customers.
If you create multiple label templates, then the name will help you tell your labels apart.

| *Language*
|Which language should the label be in?
Select the appropriate language from the drop-down list.
The system language is set by default.

| *Character set*
|Which character set should the label use?
Select the character set from the drop-down list.

| *Page*
|Enter the page width and height in millimetres.
If you use a xref:automation:printer.adoc#50[label printer], then the page size and label size can be identical.

| *Margin*
|Enter the margins left and top in millimetres.

| *Label*
|Enter the label width and height in millimetres.
The label size must be consistent with the page size as well as the number of lines and columns.

| *Lines per page*
|Enter the number of lines per page.

| *Columns per page*
|Enter the number of columns per page.
|===

[#960]
=== Which data should appear on the label?

Use X-Y coordinates to specify which information should be displayed on the label and where each piece of information should be positioned.

* *_Which info_*:
The labels only show values for which X and Y coordinates have been saved.
In other words, enter coordinates for each piece of information that should appear on the label.

* *_Position of the info_*:
Enter coordinates to position the item data on the label.
The values are based on a coordinate system with an x-axis and a y-axis.
The X-axis runs from left to right and the Y-axis from top to bottom.
The points of origin are in the upper left corner.

[cols="1s,3a"]
|===
|Setting |Explanation

|Language
|
. Enter X-Y coordinates to display xref:item:barcodes.adoc#930[the selected language] on the label.
. xref:item:barcodes.adoc#980[Configure the appearance].

|Item ID; +
Variation ID; +
Variation No.; +
Variation name; +
External variation ID; +
Model; +
Main variation number
|
. Enter X-Y coordinates to display the item data on the label.
. xref:item:barcodes.adoc#980[Configure the appearance].

|Item name
|
. Enter X-Y coordinates to display the item name on the label.
. xref:item:barcodes.adoc#980[Configure the appearance].

[cols="1s,4"]
!===

!Name
!Specify whether you want to use name 1, 2 or 3 as the item name.

!===

|Barcode; +
GTIN barcode; +
ISBN
|
. Enter X-Y coordinates to display the barcode on the label.
. xref:item:barcodes.adoc#980[Configure the appearance].

[cols="1s,4"]
!===

!Display GTIN
!Select this option (icon:check-square[role="blue"]) if you want the GTIN to appear underneath the barcode.

!===

|1\. Price; +
2\. Price; +
Unit price
|
. Enter X-Y coordinates to display the variation’s price/unit price.
. xref:item:barcodes.adoc#980[Configure the appearance].

[cols="1s,4"]
!===

!Price type
!Decide whether the sales price or the RRP should be displayed. +
*_Note_*: If you choose RRP, then the variation’s RRP will be displayed, regardless whether you also select a sales price.

!Sales price
!Decide which sales price should be displayed. +
*_Note_*: If the price type is set to *Sales price*, then the monetary amount will only be taken from the variation if no price is saved for the order item. Otherwise the price will be taken from the order item. +
This only applies, however, if the labels are created for an order. In this case, labels can be created from the order or from the preview.

!===

*_Note_*: If you want to display both the price and the unit price, then make sure that the same price type and/or sales price is selected for both options.

|Attributes
|
. Enter X-Y coordinates to display the variation’s attribute names and attribute values.
. xref:item:barcodes.adoc#980[Configure the appearance].

[cols="1s,4"]
!===

!Hide attribute names
!Select this option (icon:check-square[role="blue"]) if you only want the attribute value to be displayed. The attribute name will be hidden.

!===

|Storage location
|
. Enter X-Y coordinates to display the xref:stock-management:variations-track-stock.adoc#300[variation’s suggested storage location] on the label.
. xref:item:barcodes.adoc#980[Configure the appearance].

|Stock; +
Unit; +
Currency
|
. Enter X-Y coordinates to display the item data on the label.
. xref:item:barcodes.adoc#980[Configure the appearance].

|Item image
|Enter X-Y coordinates to display the item image on the label.

[cols="1s,4"]
!===

!Height/Width (mm)
!Enter maximum values for the image height and width.
If the image is larger than the entered values, the image will be resized. The proportions will remain the same so that the image is not distorted.

!Item image position
!Many items have more than just one image.
By selecting a position number here, you specify which item image should appear on the label.

*Position 0* is set by default.
The item image positions are defined in the item's *Images* tab.
If no image is available for the position that was selected, then the first available image will be used, beginning with position 0.

!===

|Item free text field 1 to 4
|
. Enter X-Y coordinates to display the free text field on the label.
. xref:item:barcodes.adoc#980[Configure the appearance].

[cols="1s,4"]
!===

!Free text field
!Select the xref:item:import-export-create-directory.adoc#70[free text field] whose text should be displayed on the label.

!===

|Free text fields 1 to 4
|
. Enter X-Y coordinates to display the free text field on the label.
. xref:item:barcodes.adoc#980[Configure the appearance].

[cols="1s,4"]
!===

!Entry field
!Here you can set up additional free text fields.
Enter text into the field.
The entered text will be displayed on the label.

!===

|Graphic
|Enter X-Y coordinates to display a graphic on the label.

[cols="1s,4a"]
!===

!Height/Width (mm)
!Enter maximum values for the image height and width.
If the image is larger than the entered values, the image will be resized. The proportions will remain the same so that the image is not distorted.

!URL
!
. Upload your graphics in the menu *CMS » Webspace*.
. Copy the graphic’s URL from the webspace.
. Insert the URL into this field.

!===

2+^s|Order-related data

|Order ID; +
External order ID; +
Number of items
|
. Enter X-Y coordinates to display the order-related parameters on the label.
. xref:item:barcodes.adoc#980[Configure the appearance].

|Country of delivery
|
. Enter X-Y coordinates to display the country of delivery on the label.
. xref:item:barcodes.adoc#980[Configure the appearance].

[cols="1s,4"]
!===

!Display
!Decide whether the country’s name or ISO code should be displayed on the label.

!===

|===

[#980]
=== Appearance of the label

[cols="1s,3a"]
|===
|Setting |Explanation

|X/Y
|Use X-Y coordinates to specify which information should be displayed on the label and where each piece of information should be positioned.

* *_Which info_*:
The labels only show values for which X and Y coordinates have been saved.
In other words, enter coordinates for each piece of information that should appear on the label.

* *_Position of the info_*:
Enter coordinates to position the item data on the label.
The values are based on a coordinate system with an x-axis and a y-axis.
The X-axis runs from left to right and the Y-axis from top to bottom.
The points of origin are in the upper left corner.

|5px
|Should the item data be small or large?
Select the appropriate font size from the drop-down list.

|Normal
|Should the item data be displayed in normal or bold font?
Select the appropriate font style from the drop-down list.

|Hide title
|The item parameter’s title is displayed on the label by default.
Select this option (icon:check-square[role="blue"]) if you do not want the title to be displayed.

|Allow line break
|Select this option (icon:check-square[role="blue"]) if you want the text to wrap to the next line when it exceeds the width of the label.

|===

[TIP]
.Print test page
====
Depending on which printer you use, the printed labels may differ from the template settings even if all settings are correct. As such, print some test pages on normal paper. Adjust the positions until you have reached the desired result before using more expensive label paper.
====

[#1000]
== Generating and printing labels

There are a few different ways to generate and print labels.

[.collapseBox]
.*Manually generating labels for a storage location*
--

Proceed as follows to manually generate and print labels for a specific storage location:

. Go to *Item » Edit item*.
. xref:item:search.adoc#400[Search for] and open the variation.
. Click on the *Warehouse* tab.
. Make sure you’ve selected a storage location in the field *Suggested storage location*.
If no storage location was selected for a variation, then the default storage location will automatically be used as a placeholder instead.
. Click on the label symbol (icon:barcode[role="blue"]) further to the right. +
→ The *Generate labels* window opens.
. Enter the number of labels to generate.
. Select a label template from the drop-down list.
. Click on terra:execute[role="darkGrey"] *Generate labels*. +
→ A PDF file with the selected number of labels is generated.

TIP: Do you only ever see the default storage location on your labels? +
 +
*_Tip 1_*: You might not have saved a suggested storage location for the variation.
Open the variation and click on the *Warehouse* tab.
Make sure you’ve selected a storage location in the field *Suggested storage location*.
If no storage location was selected for a variation, then the default storage location will automatically be used as a placeholder instead. +
 +
*_Tip 2_*: You might have clicked on the wrong label symbol.
Click on the label symbol icon:barcode[role="blue"] further to the right in the *Warehouse* tab.
If you click on the label symbol in the item toolbar further up, then the default storage location will be displayed on your label.
Remember that each variation can be stored in a different location.
In other words, an item can have multiple storage locations.
So if you generate a label for the entire item, then plentymarkets won’t know which storage location is intended. It will use the default storage location instead.

--

[.collapseBox]
.*Manually generating labels for a variation*
--

Proceed as follows to manually generate and print labels for a specific variation:

. Go to *Item » Edit item*.
. xref:item:search.adoc#400[Search for] and open the variation.
. Click on the label symbol (icon:barcode[role="blue"]) in the lower toolbar. +
→ The *Generate labels* window opens.
. Enter the number of labels to generate.
. Select a label template from the drop-down list.
. Click on *Generate labels* (terra:execute[role="darkGrey"]). +
→ A PDF file with the selected number of labels is generated.


TIP: It’s also possible to generate labels for all variations of an item.
To do so, click on the label symbol icon:barcode[role="blue"] in the upper toolbar.

--

[.collapseBox]
.*Manually generating labels for all items in an order*
--

Once you’ve finished creating a xref:item:barcodes.adoc#900[label template], a new option will appear.
Use this option to manually generate labels for all of the items that belong to a specific order.

. Go to *Setup » Item » Labels*.
. Expand an existing template (icon:plus-square-o[role="darkGrey"]).
. Enter the order ID.
. Click on *Preview* (icon:eye[role="blue"]). +
→ A PDF file with the labels for the items of this order is generated.

--

[.collapseBox]
.*Printing labels from the plentyWarehouse app*
--

Do you use the plentyWarehouse app?
Then you can use your mobile device to search for items and print labels.

xref:stock-management:printing-labels.adoc#[Further information].

--

[.collapseBox]
.*Automatically printing labels while receiving goods*
--

Do you want to automatically print labels while receiving goods?
Then create a xref:automation:setting-up-processes.adoc#[plentymarkets process] and add xref:automation:procedures.adoc#150[the “item label” procedure] to it.

--
