= Item templates (not recommended)
:lang: en
include::{includedir}/_header.adoc[]
:position: 10060
:url: item/online-store/callisto-templates
:id: QPVEO0X
:author: team-item

////
zuletzt bearbeitet 21.12.2020
////

[WARNING]
.ShopBuilder has replaced the item templates
====
It’s technically possible to use item templates with the plentyShop.
However, we don’t recommend doing so for two reasons:

* Item templates overwrite your “normal” product pages and are therefore not particularly useful in real life situations.
* This procedure is more complicated than link:https://vimeo.com/360260315[designing product pages with ShopBuilder] (see German video starting from minute 12:17).
====

You can use item templates to design your plentyShop's product pages.
You’ll proceed as follows:

. Create a new category of the type “Content” and insert HTML code into the “Template” tab.
. Link the desired items to this category.
. Finally, deploy the plentyShop LTS plugin.

[#100]
== Creating a category for the item template

. Go to *Item » Category*.
. Click on icon:plus[role="green"] *New category*. +
→ The *Create new category* window opens.
. Enter a name for the category.
. Click on icon:save[set=plenty, role="green"] *Create*. +
→ The category is created and displayed in the directory tree on the left.
. Click on this category's *Settings* tab.
. Select the type *Content*.
. *Save* (icon:save[set=plenty, role="green"]) the settings.
. Click on the tab *Template* and insert HTML code. This is the template.
. *Save* (icon:save[set=plenty, role="green"]) the settings.

[#200]
== Linking items with the template category

Once you’ve created the item template, you’ll link this template with the desired items.
You can either link the template with one single item or with several items at once.

[#300]
=== Linking the template with one item

. Go to *Item » Edit item*.
. <<item/introduction/search#100, Search for>> and open the item.
. Click on the *Texts* tab in the upper row.
. Scroll down to the option *Item template*.
. Click on *Assign category* (icon:pencil[role="yellow"]). +
→ The *Select item template* window opens.
. Click on the category of the type “Content”.
. Click on icon:execute[set=plenty] *Select*. +
→ The template will be linked to the item.
. *Save* (icon:save[set=plenty, role="green"]) the settings.

[#400]
=== Linking the template with multiple items

. Go to *Item » Edit item*.
. Set the filter *Table type* to *Item*.
. Choose additional <<item/introduction/search#100, filters on the left>> if needed and click on *Search* (icon:search[role="blue"]).
. Select (icon:check-square[role="blue"]) the items to be edited from the overview on the right.
. Click on *Item group function*. +
→ The *Item group function* window opens.
. Link the item template. To do so:
.. Search for the *Item template* option in the *Global* area.
.. Click on the check box (icon:check-square[role="blue"]) to the left of this option.
.. Click on *Assign category* (icon:pencil[role="yellow"]) to the right of this option. +
→ The *Select item template* window opens.
.. Click on the category of the type “Content”.
.. Click on icon:execute[set=plenty] *Select*.
.. Click on icon:execute[set=plenty] *Execute*. +
→ The template will be linked to all of the selected items.

[#500]
== Deploying the plugin

<<welcome/quick-start/quick-start-online-store#270, Deploy the plentyShop LTS plugin>> and check what the template looks like in your plentyShop.
Keep in mind that item templates overwrite your “normal” product pages and are therefore not particularly useful in real life situations.
