= Customising the tab names
////
= Designing your own editing window
////
:lang: en
include::{includedir}/_header.adoc[]
:description: This page teaches you how to customise the names of tabs.
:position: 50
:url: item/import-export-create/create/design-editing-window
:id: 864QUOC
:author: team-item

////
langfristig zukunftsmusik - basically trash this page and instead add MyView info, then rethink page name and intro as commented
mittelfristig zukunftsmusik - rework the instructions below so that there aren't 2 or 3 tips right after each other, maybe info boxes instead

Did you know that you can customise your plentymarkets system?
////
Did you know that you can customise some aspects of your plentymarkets system?
This page teaches you how to customise the names of tabs.

[discrete]
===== What exactly is it about?

When you <<item/introduction/search#100, search for items>>, you’ll see the results displayed in an overview.
Click on one of these items to open it in a new tab.
The item ID is displayed in this tab by default.
But you can decide if you’d rather see the item’s name or number in the tab.
Of course you can change these settings at any time.

[TIP]
.Further customisation options
====
You can also decide, e.g.:

* <<welcome/customise-system#160, which columns>> should be displayed in the item overview.
* whether the item information should be displayed in <<welcome/customise-system#170, ascending or descending order>>.
====

== Item tabs

By default, the item ID is shown as the tab title of items. Instead of showing the item ID in the tab, you can display the name or the number of the item’s main variation.

[.instruction]
Customising the item tabs:

. Go to *Item » Edit item*.
. <<item/introduction/search#100, Search for>> and open an item. +
→ The item data record opens in a new tab.
. Move the mouse cursor over the currently opened item tab.
. Right-click your mouse. +
→ A drop-down list opens.
. Click on *Rename*. +
→ The *Select tab title* window opens.
. Decide which data should be displayed.
. Click on *Rename*. +
→ The selected item data is shown as tab titles for all items. +

*_Tip:_* If you select the setting *Variation name of the main variation* or *Variation number of the main variation* and this information is not saved for an item, the *Item ID* is shown instead.

*_Tip_*: The tab title of the item that currently is open only changes after you reload the item.


== Variation tabs

By default, the variation ID is shown as the tab title of variations. Alternatively, you can display the variation name or the variation number.

[.instruction]
Customising the variation tabs:

. Go to *Item » Edit item*.
. <<item/introduction/search#100, Search for>> and open an item.
. Move the mouse cursor over the tab *Settings* in the lower row of tabs.
. Right-click your mouse. +
→ A drop-down list opens.
. Click on *Rename*. +
→ The *Select tab title* window opens.
. Decide which data should be displayed.
. Click on *Rename*. +
→ The selected variation data is shown as tab titles for all variations. +

*_Tip:_* If you select the setting *Variation name* or *Variation number* and this information is not saved for a variation, the *Variation ID* is shown instead.

*_Tip_*: The tab title of the variation that currently is open only changes after you reload the item.

*_Tip_*: If the drop-down list doesn’t appear when you right-click, then switch to the tab of the main variation.
