= Export
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Exporting item data, Exporting item, Exporting items, Item exporting, Items exporting, Item export, Items export, Export item, Export items, Item-Export, Items-Export, Export-Item, Export-Items, Exporting variation, Exporting variations, Variation exporting, Variations exporting, Variation export, Variations export, Export variation, Export variations, Variation-Export, Variations-Export, Export-Variation, Export-Variations, Exporting product, Exporting products, Exporting goods
:description: This page introduces several tools for exporting item and variation data.
:position: 20
:url: item/import-export-create/export
:id: MZZOOGM
:author: team-item

There are many reasons to export item and variation data.
For example, you might want to:

* transmit your item and variation data to marketplaces.
* export a CSV file containing your product data. Then revise the file and import it again.

This page introduces the tools for doing so. Click on the links to read more comprehensive information about the tools.


[discrete]
=== Catalogue

Use <<data/exporting-data/managing-catalogues#, catalogues>> to export variation data to markets and other sales channels. Currently, you can use catalogues to transfer data to the markets REWE, Etsy, Metro, OTTO Market and Amazon.

Catalogues are used to prepare variation data for exporting them to a sales channel.


[discrete]
=== Elastic Export

Do you want to export a CSV file containing your product data? Afterwards, you can e.g. revise the file and import it again.
Item data is exported in two steps:

First you’ll use the <<data/exporting-data/FormatDesigner#, FormatDesigner>> to create so-called data formats. In other words, you'll decide which data should be exported.

In a second step, you’ll use the <<data/exporting-data/elastic-export#, Elastic Export>> tool to export the data format that you just created.
