= Creating new items (new item UI)
:keywords: New item UI, Item » Item UI, Create items, Creating items, Create item data, Add item, Adding items, Add item data, Create variation, Create variations, Create variation data, Item creation, Manually create items, New item, New items, New variation, New variations, New product, New products, Variation creation
:description: Learn how to manually create items and variations.
:author: team-item

////
zuletzt bearbeitet 16.05.22
////

//ToDo - gifs erstellen
//ToDo - sobald der Artikeltyp bei der Anlage auswählbar ist, die Inhalte überarbeiten und sichtbar schalten
//ToDo - bei Anker 400 - Links ergänzen sobald die neue Verzeichnisseite live ist
//ToDo - langfristig: video erstellen

Ready to start entering item data into plentymarkets?
This page teaches you how to manually create items and variations.

//#video#

[discrete]
==== Procedure

* Create the xref:item:manually-create-item.adoc#200[item data record].
* Should the item be available e.g. in various sizes or colours? Then create xref:item:manually-create-item.adoc#300[all of the necessary variations].
* Add xref:item:manually-create-item.adoc#400[further product data] like images, texts and stock information.
* Regularly xref:item:manually-create-item.adoc#500[preview the item in plentyShop] and see where you need to add more product data or adjust the settings.
* xref:item:manually-create-item.adoc#600[Activate the item] once it’s ready to be sold.

[TIP]
.Would you rather import items?
====
This page teaches you how to manually create items and variations.
This is useful, e.g. if you only want to add a few new products to your assortment.
But what if you want to add several hundred item data records?
It would take far too long to do this manually.
Take a look at the various xref:item:import-export-create.adoc#[tools] for importing item information.
Choose the tool that is most appropriate for your situation.
====

[#100]
== Requirements

This page assumes that you already have basic knowledge of the item structure in plentymarkets:

* Do you know the xref:item:structure.adoc#[difference between items and variations]?
* Do you know how variations can xref:item:inheritance.adoc#[inherit data]?

Furthermore, make sure you’ve saved the following data in your system before you start manually creating items and variations:

* xref:item:attributes.adoc#[Attributes and attribute values]
* xref:item:categories.adoc#[Categories]
* xref:item:prices.adoc#[Sales prices]


[#200]
== Creating a new item

Create the item data record by entering some basic information about the product.
Don’t worry, the item will not be available for sale immediately.
After creating the item, you will add further product information and then activate the item when it is ready to be sold.

//#gif#

[.instruction]
Creating a new item:

. Go to *Item » Item UI*.
. Click on *Create a new item* (icon:plus[role="darkGrey"]). +
→ A pop-up window opens. This window is divided into several steps.
. Carry out the settings in each step.

[discrete]
==== Step: Name

:manual:

[cols="1,4a"]
|====
|Setting |Explanation

//|[#intable-type]*Type*
//a|What sort of item do you want to create? In most cases, you’ll probably create a “normal item”, i.e. an item of the type *Default*.

//The other options in the drop-down list are intended for other situations:

//* *Standard* = Creates a normal item or an xref:item:combining-products.adoc#2000[item bundle].
//* *Set* = Creates an xref:item:combining-products.adoc#3000[item set].
//* *Multipack* = Creates a xref:item:combining-products.adoc#1000[multipack item].

//*_Note_*: This setting can no longer be changed once the item has been created.

| *Name* +
[red]#(Mandatory field)#
|Enter a name for the item.

*_Note_*:
Once you’ve created the item, you can translate the name into other languages or save additional names, e.g. if you want the item to have a different name on marketplaces.

|====

[discrete]
==== Step: Categories

[cols="1,4"]
|====
|Setting |Explanation

| *Choose categories* +
[red]#(Mandatory field)#
a|Which category should the item be sorted into?

. Click on *Choose categories*. +
→ A pop-up window opens.
. Expand the entries (icon:chevron-right[role="darkGrey"]) and select all of the categories (icon:check-square[role="blue"]) that this item should appear in.
. Click on *Apply*. +
→ The selected categories will be displayed as a table.
Click on material:delete[role="darkGrey"] to remove a category from this list or click on icon:pencil[role="darkGrey"] *Choose categories* to add further categories.

*_Note_*: This list only includes the xref:item:categories.adoc#[categories] that you’ve already created in plentymarkets.

|====

[discrete]
==== Step: Main variation (Optional)

[TIP]
.What’s a main variation?
====
An item’s first variation is called its main variation.
If an item has multiple variations, then the main variation can either be a saleable product or it can be a virtual data record. A virtual main variation is used to manage the other variations of the item with inheritance.
====

[cols="1,4"]
|====
|Setting |Explanation

| *Variation number*
|Enter a number for the main variation.

| *Content* +
*Unit*
|Enter a numerical value for the main variation and choose a unit from the drop-down list, e.g. 500ml or 150g.

| *Choose attributes*
a|The main variation can either be a saleable product or it can be a virtual data record. A virtual main variation is used to manage the other variations of the item with inheritance.
That means, the main variation can have attributes, but it is not required to.

. Click on *Choose attributes*. +
→ A pop-up window opens.
. Expand the attributes (icon:chevron-right[role="darkGrey"]) and select the attribute values (icon:check-square[role="blue"]) that you want to use for the main variation, e.g. the size "small" and the colour "red".
. Click on *Apply*. +
→ The selected attribute values will be displayed as a table.
Click on material:delete[role="darkGrey"] to remove an attribute value from this list or click on icon:pencil[role="darkGrey"] *Choose attributes* to add further attribute values.

*_Note_*: This list only includes the xref:item:attributes.adoc#[attributes and values] that you’ve already created in plentymarkets.

*_Recommendation_*: It’s technically possible to select attributes here. However, we don’t recommend this.
Rather, we recommend that you first create the new item without any attributes. Afterwards, we recommend that you select attributes while you xref:item:manually-create-item.adoc#300[create the necessary variations]. +
Why? If you link attributes with the main variation right now, then all of the following variations will have to be created from the same attributes too. This is not the case if you wait to link attributes while creating variations.
In other words, it makes you more flexible in the future.
|====

[discrete]
==== Step: Done

[cols="1,4"]
|====
|Setting |Explanation

| *Summary*
a|Here you can see a summary of the settings that you selected.
Click on *Create item* if you are satisfied with the settings.

Afterwards, you will have the following options:

[cols="1,4a"]
!===

! *To the item*
!The pop-up window will close and the newly created item data record will open for further editing.

! *Create another item*
!The pop-up window will re-start for the next item.

! *Close*
!The pop-up window will close.

!===

|====

[#300]
== Creating the necessary variations

Some items like shoes and t-shirts are sold in various sizes and colours.
In other words: customers don’t simply buy a t-shirt, but rather a specific variation of a t-shirt, e.g. in the colour red and the size S.
First, create all of the necessary variations.

//#gif#

[.instruction]
Creating the necessary variations:

. Go to *Item » Item UI » [Open item] » Variation overview*.
. Click on *Create variations* (icon:plus[role="darkGrey"]). +
→ A pop-up window opens. This window is divided into several steps.
. Carry out the settings in each step.

[discrete]
==== Step: Settings

[cols="1,4"]
|====
|Setting |Explanation

| *Content* +
*Unit*
a|Use this area if the variations should differ in terms of quantity and/or unit.

*_Example_*: A bottle of soap that’s available in 100ml, 250ml and 500ml.

*_Instructions_*:

. Enter the quantity and unit for the first variation, e.g. 100ml.
. Click on *Create variations*.
. Repeat the procedure for 250ml and for 500ml.

| *Select attributes*
a|Use this area if the variations should differ in terms of their attribute values.

*_Example_*: A t-shirt that’s available in the colours green or blue and in the sizes S, M or L.

*_Instructions_*:

. Click on *Select attributes*. +
→ A pop-up window opens.
. Expand the attributes (icon:chevron-right[role="darkGrey"]) and select all of the attribute values (icon:check-square[role="blue"]) that you want to use, e.g. the sizes "S", "M", "L" and the colours "green" and "blue".
. Click on *Apply*. +
→ The selected attribute values will be displayed as a table.
Click on icon:pencil[role="darkGrey"] *Select attributes* if you want to change your selection.
. Click on *Preview* and make sure that the combinations are correct.
. Click on *Create variations*.

*_Note_*: This list only includes the xref:item:attributes.adoc#[attributes and values] that you’ve already created in plentymarkets.

|====

[discrete]
==== Step: Preview

[cols="1,4"]
|====
|Setting |Explanation

| *Preview*
|Use this area if you want to make sure that the combinations are correct.

*_Example_*: If you combine the sizes "S", "M", "L" with the colours “green” and “blue”, then you will have 6 variations.

*_Note_*: Above the table, you can see how many combinations will be created.
There is no limit to how many combinations are possible.
|====

[discrete]
==== Step: Summary

[cols="1,4"]
|====
|Setting |Explanation

| *Summary*
|Here you’ll see a confirmation that the variations were created.

*_Note_*:
It can take a few minutes for the new variations to appear in the overview.

|====

[#400]
== Adding further product data

While creating the item, you entered some basic information about the product.
Now you can add further information.
For example, you can:

//Links ergänzen sobald die neue Verzeichnisseite live ist

* Upload images
* Write product texts
* Save prices
* Add stock information

[#500]
== Looking at the item in the front end

Are you curious what the new product looks like in your plentyShop or on Amazon?
See a preview of the item and find out where you need to add further product data or adjust the settings.

//#gif#

[.instruction]
Viewing a preview of the item:

. Click on *Product Link* (material:open_in_new[role="darkGrey"]) in the toolbar. +
→ A pop-up window opens.
. Carry out the settings.
. Click on material:open_in_new[role="darkGrey"] *Open*. +
→ A preview of the item is shown.

[TIP]
.Product links for items or variations
====
You can access the product link for an item or for a variation.
The product link button is located in the toolbar of the item view and the variation view.
====

[cols="1,4a"]
|====
|Setting |Explanation

| *URL*
|The product's URL is displayed in an info box up top.
Click on the URL to open the page in a new tab.
Click on terra:copy[role="darkGrey"] to copy the URL to the clipboard.

| *Sales channel*
|Do you want to see what the product will look like in your plentyShop or on Amazon?

[cols="1,4a"]
!===

! *plentyShop LTS Preview*
!
You will see a preview in the plentyShop.
Possible use-cases:

* You want to check what a product will look like in the plentyShop before you make it visible for your end customers.
* You are currently re-designing your plentyShop and you want to check what a product would look like with a different plugin set.

*_Additional settings_*: Also select the client and the plugin set.

! *plentyShop LTS live*
!
You will see what the product currently looks like in the plentyShop.
Possible use-case:

* You want to check which prices and information are displayed when end customers access your plentyShop via a specific price comparison portal.

*_Additional settings_*: Also select the client and the referrer.

! *Amazon*
!You will see a preview on Amazon.
Make sure that you have already saved an ASIN for the variation.
The preview can only be generated if the variation has an ASIN.

!===

| *Client (store)*
|Which client, i.e. which webshop, do you want to see the preview in?
Select the client from the drop-down list.

*_Background info_*: With plentymarkets, you can manage several online stores, i.e. xref:online-store:setting-up-clients.adoc#[several clients], with only one software.
Consequently, it is possible to manage several different areas of business with one plentymarkets system.

*_Note_*: This option is only displayed if you chose the sales channel *plentyShop LTS Preview* or *plentyShop LTS live*.

| *Plugin set*
|Which plugin set do you want to see the preview in?
Select the plugin set from the drop-down list.

*_Background info_*: plentymarkets doesn't consider each xref:plugins:plugins.adoc#[plugin] in a vacuum, but compiles them in so-called plugin sets.
For example, plugin sets allow you to design seasonal layouts for your plentyShop or test new versions of plugins before switching them live.

*_Note_*: This option is only displayed if you chose the sales channel *plentyShop LTS Preview*.

| *Referrer*
|Do you want to check which prices and information are displayed when end customers access your plentyShop via a specific price comparison portal?
Select the referrer from the drop-down list.

*_Note_*: This option is only displayed if you chose the sales channel *plentyShop LTS live*.

| *ASIN*
|Which ASIN do you want to use for the preview?
Select the ASIN from the drop-down list.

*_Note_*: This drop-down list only includes the ASINs that were already saved for the variation.
You haven't saved an ASIN for the variation yet?
Or you haven't selected an ASIN from the drop-down list?
Then you will see an error message in the info box up top.

*_Note_*: This option is only displayed if you chose the sales channel *Amazon*.

|====

[#600]
== Putting products up for sale

Variations are not visible to customers in the plentyShop until they have been activated.
In other words, you can work on inactive variations without your customers noticing.
You activate the variation when you’re ready for it to be visible in your plentyShop.

[.instruction]
Activating a variation:

. Go to *Item » Item UI » [Open variation] » Element: Availability and visibility*.
. Select the option *Active* (icon:toggle-on[role="blue"]).
. *Save* (terra:save[role="darkGrey"]) the settings.

[TIP]
.Complete checklist for item visibility
====
Not only do items need to be activated, but they also need to have a price, a category and positive net stock.
Otherwise customers wouldn’t be able to buy the item.
Work through xref:item:checklist-items-visibility.adoc#[this checklist] and make sure your item meets all of the requirements for being visible in the plentyShop.
This checklist helps you find any possible errors that are preventing your items from being displayed.
====
