= Items (new item UI)
:description: This chapter describes the new item menu, which is currently in a test phase.
:author: team-item

////
zuletzt bearbeitet 10.05.2023
////

This chapter describes the new item menu, which is currently in a test phase. That means:

* There is a new menu for managing item data in plentysystems.
* Test phase means that you can see and test the new item menu.
However, the new item menu does not yet include every function.

== FAQ

[.collapseBox]
.*How can I give feedback?*
--

If you want to give feedback about the new item menu, then please use link:https://forum.plentymarkets.com/c/item/18[this forum category].

--

[.collapseBox]
.*Will the old item menu be removed soon?*
--

No.
The menu *Item » Edit item* will not be removed in the near future.
For now, both the old and new item menus can be used in parallel.

--

[.collapseBox]
.*Do links from other menus lead to the new item menu?*
--

You can decide whether the old or new item menu should be used by default.

. Go to *Setup » Item » New item UI (Test phase)*.
. Activate the toggle button (icon:toggle-on[role="blue"]) if you want the new item menu to be used by default.
If the toggle button is activated, then links from other menus (e.g. Orders) will lead to the new item menu.
. Save (terra:save[role="darkGrey"]) the settings.
. Log out of plentysystems and then log back in.

The setting only applies to the specific user account.
It can be activated or deactivated any time.

--

[.collapseBox]
.*Which functions are still missing?*
--

The following functions are missing and are not planned for the future:

* Characteristics
* Free text fields
* Item tab: Media
* Item tab: Statistics

--
