= Back end search behaviour
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Search behaviour, Item search, Backend, Back end, Back end item search, Search index, Item search index, Characteristic search index
:description: How do you want the back end item search to work? You can customise the pre-defined search behaviour to meet your needs.
:url: item/use-cases/search-behaviour
:position: 70
:id: DY9U831
:author: team-item

////
zuletzt bearbeitet 12.03.2021
////

You probably already know that you can search for product data records in the menu *Item » Edit item*.
But did you also know that you can modify the search behaviour to meet your needs?
For example, you can decide:

* which sales price or barcode should be displayed in the search results.
* which item parameters are relevant for the search.

[#100]
== Which price or barcode is preferred?

By default, the first sales price and barcode saved for the variation is displayed in the search results in the menu *Item » Edit item*.
But what if this pre-defined setting doesn’t meet your needs?
You can decide which sales price or barcode you want to see.

. Go to *Setup » Item » Settings*.
. Carry out the settings. Note <<table-price-barcode-settings>>.
. *Save* (icon:save[set=plenty, role="green"]) the settings.

[[table-price-barcode-settings]]
.Which price or barcode should be displayed in the item overview?
[cols="1,3"]
|====
|Setting |Explanation

| *Prioritised price in item overview*
|Select a sales price from the drop-down list.
The price that you choose here will be displayed in the search results in the menu *Item » Edit item*.
It appears in the column *Sales price*.

*_Note_*:
If a variation is not linked to this sales price, then one of the other prices will be displayed instead.

| *Prioritised barcode in item overview*
|Select a barcode from the drop-down list.
The barcode that you choose here will be displayed in the search results in the menu *Item » Edit item*.
It appears in the column *Barcode*.

*_Note_*:
If a variation is not linked to this barcode, then one of the other barcodes will be displayed instead.
|====

[#200]
== Which item parameters are relevant?

Which item parameters should be considered when you search for products in the menu *Item » Edit item*?
First: configure the search index so that all of the relevant item data is taken into consideration.
Second: update the search index.

[#300]
=== Configuring the search index

. Go to *Setup » Item » Search » Backend » Search index*.
. Click on the *Default index* tab.
. Select the parameters (icon:check-square[role="blue"]) that should be taken into consideration for the item search.
. Click on the *Extended index* tab.
. Select the parameters (icon:check-square[role="blue"]) that should be taken into consideration for the item search, when using the search filter <<item/introduction/search#intable-description, Browse description>>.
. *Save* (icon:save[set=plenty, role="green"]) the settings. +
→ The selected parameters will be taken into consideration.

[TIP]
.Default index vs. Extended index
====
Use the default index to specify which parameters should be taken into consideration for the back end search.

Use the extended index to specify which parameters should be taken into consideration for the back end search, when using the search filter <<item/introduction/search#intable-description, Browse description>>.
====

[TIP]
.Limited number of characters
====
The default and extended search index only allow a limited number of characters.
That means, if you choose all of the parameters, then they might not all be included in the index.
The additional characters will be cut off.
====

[#400]
=== Manually building the search index

It’s possible to manually re-build the search index.
This is useful, e.g. after you’ve changed the configuration.

. Go to *Setup » Item » Search » Backend » Search index*.
. Save the settings in the tab *Default index* or *Extended index*.
. Switch back to the *Overview* tab.
. Click on *Set up an item search index* (icon:execute[set=plenty]). +
→ A maximum of 3000 items are indexed per cycle.
So if you have more than 3000 items, you’ll need to click on the button multiple times.

[TIP]
.When is the search index automatically built?
====
* *_New items_*: The search index is automatically built when a new item is created.
* *_Item import_*: If you import items, the search index will be updated over night.
There is only one cycle with a maximum of 3000 items.
So if there are more than 3000 items in the system, then it will take several nights until the search index is updated.
If you want the items to be indexed faster, then manually build the search index.
====

[TIP]
.Item catalogue vs. Item characteristics
====
* *_Item catalogue_*: Here you can see how many items in total are included in the search index.
* *_Item characteristics_*: Here you can see how many items with characteristics are included in the search index.

Both tabs function the same way.
So you can also manually build the characteristic search index as described above.
====

[#500]
=== Working with the overview

The overview in the menu *Setup » Item » Search » Backend » Search index* shows you how many items are saved in the system and how many items are included in the search index.

[[table-searchindex-overview]]
.Information in the overview
[cols="1,3"]
|====
|Setting |Explanation

| *Indexed items*
|Here you’ll see the number of items (per language) that are included in the search index. +


| *Total number of items*
|Here you’ll see the number of items in your plentymarkets system. The figure includes newly imported and not yet indexed items.


| *Set up an item search index* (icon:execute[set=plenty])
|Click on this button to <<item/use-cases/search-behaviour#400, manually build the search index>>.
|====
