= Search filters and example items
:keywords: Item search, Item search, Item search, Product search, Variation search, Variant search, Backend search, Back end search, Search for items, Searching for items, Search for variations, Searching for items, Search for products, Searching for products, Search option, Search options, Filter, Filters, Item list, Search behaviour, Example item, Example items
:description: Learn how to search for item data in the back end. See a few example items that come with new systems.
:author: team-item

////
zuletzt bearbeitet 12.03.2021
////

Get to know the item overview!
Learn how to search for item data in the plentymarkets back end. See a few example items that come with new systems.

[#100]
== Searching for items and variations

[tabs]
====
Default search::
+
--
. Go to *Item » Edit item*.
. Choose *filters* in the left column. Note <<table-filter-item-variations>>.
. Click on *Search* (icon:search[role="blue"]). +
→ The xref:item:search.adoc#600[search results] are displayed in an overview on the right.

--
Searching for items in a category::
+
--
It’s also possible to search for items that belong to a specific xref:item:managing-items.adoc#300[category].

. Go to *Item » Edit item*.
. Click on the *Category* tab in the left column.
. Click on a category or a subcategory. +
→ The items in this category or subcategory are displayed in the item overview.
. *_Optional_*: Switch back to the *Filter* tab in the left column.
Select additional filters to limit the search results even further.

[TIP]
.Where do I find the subcategories?
======
Click on a category’s folder icon (icon:folder[role="darkGrey"]) on the far left. This displays the subcategories within.
======

[TIP]
.Searching for items in any category again
======
Click on the *Filter* tab and remove the check mark next to *With categories*. The next search finds items in all of the categories.
======
--
Searching for items in a client::
+
--
Are you responsible for the item data in multiple plentyShops?
Proceed as described below to search for the items that belong to a specific xref:item:managing-items.adoc#360[client (store)].

. Go to *Item » Edit item*.
. Click on the *Client* tab in the left column.
. Click on a client. +
→ This client’s items are displayed in the item overview.

[TIP]
.Combining a client with a category and filters
======
Click on a client’s folder icon (icon:folder[role="darkGrey"]) on the far left. Then click on one of the categories within the folder. The search results will be limited to items within a specific category and that belong to a specific client. Use the client search along with the filter settings listed in <<table-filter-item-variations>>. This will limit your search results even further.
======

[TIP]
.Searching for the items that are not available for a client
======
Place a check mark next to the words *Not available* and click on a client. The items that are not available for the client will be displayed in the item overview.
======

--
====

[TIP]
.Why aren’t my items found?
====
Do you see the xref:item:search.adoc#intable-active[Active] filter in the left column? Use this filter to specify whether you only want to search for items and variations that are currently activated for a plentyShop. This filter is set to *Yes* by default. Once you have many items and variations, this filter will help you edit your items quicker. However, it can also cause some confusion in the beginning because inactive items will not be found. Set the filter to *No* or *ALL* and search again.
====

[[table-filter-item-variations]]
.Filter settings for items and variations
[cols="1,4"]
|====
|Filter |Explanation

|[#intable-table-type]*Table type*
a|Should xref:item:structure.adoc#[items and variations] be grouped together in the search results? In other words, should the table list all of the possible variations or each item as a whole?

* *Item* = The overview only displays entire items. You will need to open the item data record if you want to xref:item:search.adoc#400[see its variations]. This is the default setting. +
* *Variations* = The overview displays each individual variation. +
* *Extended* = One item is displayed per line. Expand the item (icon:chevron-down[role="darkGrey"]) to see its variations.

| *Item ID*
|Enter an ID to search for the item with this ID.

| *Variation ID*
|Enter an ID to search for the variation with this ID.

| *Variation number*
a|Enter a variation number to search for the variation with this number.

*_Note_*:
Use the character `%` to search for a partial number.

*_Examples_*:

* You want to search for the variation `AB1234`, but you only know the part `1234`.
In this case, enter `%1234` into the search field.
* You want to search for all of the variations whose number begins with `NEW-`.
In this case, enter `NEW-%` into the search field.
* You want to search for all of the variations whose number contains the word `blue`.
In this case, enter `%blue%` into the search field.

| *Barcode*
|Enter a barcode to search for the xref:item:managing-items.adoc#250[variation with this code].

|[#intable-item-data]*Item data*
|Enter item data, e.g. the item’s name, model, or an appropriate keyword.
The search results display products that match this data.

*_Note_*: Only the item data that was xref:item:search-behaviour.adoc#200[activated for the search index] will be taken into consideration.

*_Searching through the item description_*: Do you want to search for items whose description contains a particular keyword? Enter the keyword into this search field and select xref:item:search.adoc#intable-description[Browse description] (icon:check-square[role="blue"]) further below.

| *Serial number*
|Enter a serial number to search for the item with this serial number.

| *SKU*
a|. Enter a SKU into the text field.
. Optionally, select the referrer from the drop-down list.
This specifies which marketplace the given SKU refers to.
. The search results display products that were xref:item:managing-items.adoc#370[linked to this SKU].

|[#intable-tags]*Click to add tags*
a|. Click into the field and select a tag from the drop-down list. +
*_Tip_*: Enter the first few letters of the tag’s name and then use the auto-complete function.
. Repeat the procedure to add any number of tags.
. The search results display products that were xref:item:managing-items.adoc#268[linked to these tags].

*_Additional search filter_*:
Use this search filter together with the option *Tag search mode* further below.

| *Tag search mode*
a|Do you want to search for variations that are linked to all of the selected tags or just one of the selected tags?

Choose the appropriate search mode from the drop-down list.

* *Or* = The variation must have at least one of the selected tags.
* *And* = The variation must have all of the selected tags.

*_Additional search filter_*: Use this search filter together with the option *Click to add tags* further above.

| *Note text*
|Enter text to search for items and variations that have notes containing this text.

| *Supplier variation number*
|Enter the item number of the supplier to search for the item with this number.

| *Type*
|Do you want to search for a particular type of item? Use this filter to narrow down the search results so that they only include default items, xref:item:combining-products.adoc#[sets or multi-packs]. +
*_What about item bundles?_*: It’s also possible to search for item bundles or individual bundle components. Use the *Bundle* filter to do so.

|[#intable-description]*Browse description*
|Select this option (icon:check-square[role="blue"]) to search for a keyword in the item description. Enter the keyword into the xref:item:search.adoc#intable-item-data[Item data] field further above.

*_Note_*: Only the item data that was xref:item:search-behaviour.adoc#200[activated for the extended search index] will be taken into consideration.

| *Item list*
|Do you want to search for variations whose xref:item:managing-items.adoc#intable-item-list[item list option] was set to visible or invisible?

| *Image*
|Do you want to search for items that have xref:item:managing-items.adoc#90[an image saved] for them?

| *Flag 1; +
Flag 2*
|Select a flag or the option *ALL* from both of the drop-down lists.
The search results only display items that have this xref:item:flags.adoc#300[combination of flags].

|[#intable-manufacturer]*Manufacturer*
|Select a manufacturer or the option *ALL*.
The search results only display items that are xref:item:managing-items.adoc#40[linked to this manufacturer].

Select the option *None* to search for items that are not linked to any manufacturer.

*_Note_*: This list only includes the xref:item:manufacturers.adoc#[manufacturer data records] that you’ve already saved in plentymarkets.

|[#intable-all]*ALL* +
(List of attributes)
a|. Select an attribute or the option *ALL* from the left drop-down list.
. Select an attribute value or the option *ALL* from the right drop-down list.
. The search results display products that were linked to this attribute value.

*_Note_*: These lists only include the xref:item:attributes.adoc#[attributes and attribute values] that you have already saved in plentymarkets.

|[#intable-active]*Active*
a|Do you only want to search for xref:item:managing-items.adoc#intable-active[active items], i.e. items that are ready to be sold?

* *Yes* = Default setting. Search for all active items. +
* *ALL* = Search for all items. The overview will display both active and inactive items. +
* *No* = Search for inactive items.

| *Client (store)*
|Select a client (store) or the option *ALL*.
The search results only display products that are xref:item:managing-items.adoc#360[linked to this client].

| *Available*
|Select an availability level or the option *ALL*.
The search results only display products that are xref:item:managing-items.adoc#200[linked to this availability level].

| *Sales price*
|Select a sales price or the option *ALL*.
The search results only display products that are xref:item:managing-items.adoc#240[linked to this sales price].

| *Shipping*
|Select a shipping profile or the option *ALL*.
The search results only display products that are xref:item:managing-items.adoc#_shipping_profiles[linked to this shipping profile].

| *Warehouse*
|Select a warehouse or the option *ALL*.
The search results only display products that are xref:item:managing-items.adoc#312[linked to this warehouse].

| *Stock limit*
a|This filter limits the search results so that they only include items that have a specific xref:item:managing-items.adoc#intable-limitation[stock limitation].

* *No limitation* = The search results will only include items whose *Limitation* option was set to *None*.
* *Limited to net stock* = The search results will only include items whose *Limitation* option was set to *To net stock*.
* *Do not administer the stock* = The search results will only include items whose *Limitation* option was set to *Do not administer stock for this variation*.
* *ALL* = The search results will include items with any stock limitation setting. This is the default setting.

| *Stock*
|Select a stock level or the option *ALL*.
The search results only display products that xref:stock-management:managing-stocks.adoc#400[have this stock level].

| *Stock type*
a|Select a stock type or the option *ALL*.
The search results only display products that are xref:item:managing-items.adoc#_basic_settings[linked to this type].

* *No colli* = Items of the type Colli will be excluded from the search.

| *Bundle*
a|Do you want to search for xref:item:combining-products.adoc#[item bundles] or individual bundle components?

* *Yes* = The search results will only include items and variations that are the main item of a bundle.
* *No* = The search results will include items and variations that are neither the main item nor a component of a bundle.
* *Component* = The search results will only include items and variations that are components of a bundle.
* *ALL* = The search results will include item bundles and items that are not part of a bundle. This is the default setting.

| *Listing*
a|Do you want to search for items that are part of a listing or an auction?

* *Yes* = The search results will only include items that are part of a listing or an auction, i.e. items with a xref:item:search.adoc#800[yellow listing symbol] (terra:listings_show[role="yellow"]).
* *No* = The search results will only include items that are not part of a listing or an auction, i.e. items with a xref:item:search.adoc#800[grey listing symbol] (terra:listings_show[role="darkGrey"]).
* *Auction (yes)* = The search results will only include items that are part of an auction. This means that xref:markets:ebay-setup.adoc#3500[the *Type* option was set to *Auction*].
* *Shop item / fixed price (yes)* = The search results will only include items that are part of a listing. This means that xref:markets:ebay-setup.adoc#3500[the *Type* option was set to *Fixed price* or *Shop item*].
* *ALL* = The search results will include items that are part of a listing and items that are not part of a listing. This is the default setting.

| *Store special*
|This filter limits the search results to items that are part of a xref:item:store-specials.adoc#[store special].
In other words, the filter searches for items that were marked as a *Special offer*, *New item* or *Top item* in the *Global* tab.

| *Age rating*
|You can use this filter to narrow down the search results so that they only include items with a specific xref:item:managing-items.adoc#40[age rating].

| *Updated from; +
Updated to*
|Select dates from the calendars.
The search results only display products that were modified during this time period.

| *Product type*
|This filter narrows down the search results so that they only include items with a specific xref:item:managing-items.adoc#_amazon[Amazon product type].

| *Allyouneed*; +
*Amazon Canada*; +
*Amazon FBA*; +
... +
*Zalando* +
*Zentralverkauf.de*
a|Do you only want to search for items that are xref:item:managing-items.adoc#350[available on a specific marketplace]?

* *Visible* = This market was selected in the variation’s *Availability* tab.
* *Invisible* = This market was not selected in the variation’s *Availability* tab.
* *ALL* = The search results include items that are available on this market and items that are not available on this market. This is the default setting.

*_Note_*: Here you’ll see a filter for each marketplace that was activated (icon:check-square[role="blue"]) in the menu *Setup » Orders » Order referrer*.
|====

[#500]
== Modifying the default search behaviour

You can customise the xref:item:search-behaviour.adoc#[pre-defined search behaviour] to meet your needs.
For example, you can decide:

* which sales price or barcode should be displayed in the item overview.
* which item parameters should be included in the search index.

[#600]
== Working with the search results

Once you’ve used the xref:item:search.adoc#100[search options on the left], you’ll see the search results displayed in an overview on the right.
Click on an item in the overview to open it and xref:item:managing-items.adoc#[edit the item data record].

[#700]
=== Customising the columns and their sort sequence

Additional symbols appear when you move your cursor over the column headings.
Use these symbols to customise the table so that it meets your needs.

[cols="1,4"]
|====
|Symbol |Explanation

|icon:gear[role="darkGrey"]
|Which columns should be included in the table? Click on *Customise the layout* (icon:gear[role="darkGrey"]) and select the columns that you want to see (icon:check-square[role="blue"]).

|icon:arrows[role="darkGrey"]
|Should certain columns be positioned further to the right or the left? If your cursor changes its shape (icon:arrows[role="darkGrey"]), then you can move the column. Simply click on the column header and drag the column to the desired position.

|icon:caret-down[role="darkGrey"]
|Do you want numbers to be sorted in ascending or descending order? Click on the small triangle (icon:caret-down[role="darkGrey"]), to change the sort sequence.
|====

[#800]
=== Symbols in the overview

Do you see the *Procedures* column in the table? The symbols in this column help you manage your items quickly and easily.

[cols="1,4"]
|====
|Symbol |Explanation

|icon:pencil[role="yellow"]
|Click on *Edit item* (icon:pencil[role="yellow"]) to open the item data record. Alternatively, click directly on the item in the overview.

|icon:eye[role="blue"]
|Click on *Visible in online store* (icon:eye[role="blue"]) to see xref:item:online-store.adoc#[what the item looks like in your plentyShop]. If the symbol is crossed out, then the item is *Invisible in the online store* (terra:item_webshop_invisible[role="blue"]).

|terra:listings_show[role="yellow"]
|Click on *Listing* (terra:listings_show[role="yellow"]) to see an overview of all the listings or auctions with this item ID. If the symbol is greyed out, then there are no listings for the item.

|terra:listing_create[role="green"]
|Click on *New listing* (terra:listing_create[role="green"]) to sell this item in a xref:markets:ebay-setup.adoc#3400[listing or auction on eBay], xref:markets:hood.adoc#2300[Hood] or xref:markets:ricardo-ch.adoc#1900[ricardo].

|terra:order_note_create[role="green"]
|Click on *Add note* (terra:order_note_create[role="green"]) to write a xref:item:managing-items.adoc#2090[note for the variation].
|====

[TIP]
.Additional symbols in the item data record
====
Once you’ve opened an item, you will see additional symbols in the row of tabs.
====

[#400]
=== Searching for variations within an item data record

Items always include one or more variations. When you open an item, the first variation, i.e. the xref:item:structure.adoc#300[main variation], will automatically open as well. But how do you access an item’s additional sub-variations? Proceed as described below to search for an item’s variations.

[.instruction]
Searching for variations within items:

. Go to *Item » Edit item*.
. xref:item:search.adoc#100[Search for] and open the item.
. Click on the *Variations* tab.
. Select the *Filters*. Note <<table-filter-variations>>.
. Click on *Search* (icon:search[role="blue"]). +
→ The filtered variations will be displayed within the item data record.

[[table-filter-variations]]
.Searching for variations within an item data record
[cols="1,3"]
|====
|Filter |Explanation

| *ID*
|Enter the ID to search for the variation with this ID.

| *Variation No.*
|Enter the variation number to search for the variation with this number.

| *External variation ID*
|Enter the ID to search for the variation with this external variation ID.

| *Barcode*
|Enter the barcode to search for the variation with this barcode.

| *Attributes*
|Select an attribute value or *ALL* to search for variations with this attribute value. Attributes are loaded dynamically. As such, only attributes linked with variations are displayed.
|====

[TIP]
.Would you prefer to search for variations directly in the main overview?
====
Use the filters described in <<table-filter-item-variations>> to see variations in the main overview rather than within an item data record. In the xref:item:search.adoc#intable-table-type[Table type] filter, choose the option *Variations* or *Extended*. Also use the *Variation ID* or *Variation number* filter to search for specific variations.
====

[#900]
== Example items

[#1000]
=== Understanding the example items

include::welcome:partial$understanding-example-items.adoc[]

[#1100]
==== Displaying the example items

include::welcome:partial$displaying-example-items.adoc[]

[#1200]
=== Deleting the example items

include::welcome:partial$deleting-example-items.adoc[]
