= Units
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Unit, Units, Unit of measure, Units of measure, Size, Measurements, Length, Width, ISO code, ISO, Decimal numbers, Content, Unit price, Price per, Piece, Each, Kilogram, Gram, Milligram, Litre, Liter
:description: There are 52 units saved in plentymarkets by default. Learn how to create additional units of measure as needed.
:url: item/settings/units
:position: 100
:id: IHTSF1W
:author: team-item

////
zuletzt bearbeitet 18.10.2021
////

Units such as kilograms, litres and centimetres help you define the size or dimensions of your products.
There are 52 units saved according to their ISO code in plentymarkets by default.
However, you can <<item/settings/units#100, create additional units of measure>> or edit the existing units as needed.

Furthermore, you can:

* specify the <<item/settings/units#150, content>> of your variations, e.g. 1 piece, 500 grams, 2.4 litres, etc.
* <<item/settings/units#200, create variations>> by combining units with different quantities.
For example, you might sell a bottle of soap that’s available in 50ml, 100ml or 150ml.
* specify the <<item/settings/units#300, unit price>> of your variations, i.e. the price per pound, litre or other unit of measure.

[#100]
== Creating new units and editing existing ones

There are 52 units saved according to their ISO code in plentymarkets by default.
Take a look at the existing units.
Create additional units of measure or edit the existing units as needed.

[.tabs]
====
Creating a new unit::
+
--

. Go to *Setup » Item » Units*.
. Click on icon:plus[role="green"] *New*. +
→ The *Create new unit* window opens.
. Enter a name for the unit.
Choose an appropriate name, since the text is visible to customers in the online shop.
. Optionally, enter a position number.
If you do not enter a number, then the position number 0 will automatically be assigned.
. Click on icon:save[set=plenty, role="green"] *Save*. +
→ The new unit will be created and it will open automatically in a new tab.
. Modify the settings further as needed.

--
Editing an existing unit::
+
--

. Go to *Setup » Item » Units*.
. Click on a unit. +
→ The unit opens in a new tab.
. Modify the settings as needed.
. *Save* (icon:save[set=plenty, role="green"]) the settings.

--
====

[cols="1,3"]
|====
|Setting |Explanation

| *Position*
|Enter a position number for the unit.
The units are displayed sorted by their position number in the back end.

*_Note_*: If you did not enter a position number while creating the unit, then the position number 0 will automatically be assigned.

| *Units of measure (ISO)*
|Select a unit of measure according to its ISO code.

*_Note_*: You can only choose from the existing ISO codes.
You can not manually add new ISO codes.

| *Decimal numbers*
|Should decimal numbers be allowed for this unit of measure?
For example, half a litre makes sense.
But half a container would not make sense.

| *Language*
|The variation’s content and unit are displayed in the online shop, e.g. 1 piece, 500 grams, 2.5 litres, etc.
Therefore, enter an appropriate name for the unit in all of the languages that you use.
|====

[#150]
== Specifying the content of your variations

[.tabs]
====
Manually::
+
--

If you only want to specify the content _for a few variations_, then it makes sense to do this manually.

. Go to *Item » Edit item » [Open variation] » Tab: Settings » Area: Dimensions » Option: Content*.
. Enter a number into the field on the left.
. Select a unit from the drop-down list on the right.
. *Save* (icon:save[set=plenty, role="green"]) the settings.

--
Import::
+
--

If you want to specify the content for _lots of variations_, then it makes sense to do this <<data/importing-data/ElasticSync#, via import>>.

. Create an <<data/importing-data/sync-types/elasticSync-item#, import of the type Item>>.
. Use the mapping fields:
.. <<data/importing-data/sync-types/elasticSync-item#1810, Content value>> and <<data/importing-data/sync-types/elasticSync-item#1800, Content unit>>. +
+
or
.. <<data/importing-data/sync-types/elasticSync-item#1810, Content value>> and <<data/importing-data/sync-types/elasticSync-item#1820, Content measuring unit (ISO)>>.

--
====

[#200]
== Combining units and creating variations

You can create variations by combining units with different quantities. For example, you might sell a bottle of soap that’s available in 50ml, 100ml or 150ml.

You can enter an item’s unit and content <<item/import-export-create/create/new-item#200, while creating the item>>. If you <<item/import-export-create/create/new-item#400, create additional variations>>, then you can enter the unit and content for each variation separately.

[#300]
== Displaying the unit price on sales channels and labels

You’ve surely seen an item’s unit price displayed on the shelves in grocery stores.
The unit price tells you how much the item costs per pound, litre or other unit of measure.

It’s calculated based on the item’s <<item/managing-items#270, content, unit>> and <<item/managing-items#240, price>>.
It can be displayed <<item/managing-items#270, in the plentyShop>>, on sales channels such as <<markets/amazon/preparing-variations#860, Amazon>>, <<markets/ebay/ebay-setup#4000, eBay>>, <<markets/otto/otto-market#1302, OTTO>> or <<markets/plus-gartenxxl#365, Netto>> and <<item/settings/barcodes#900, on item labels>>.
