= Point of sale system plentyPOS
:author: team-app-bi
:keywords: plentyPOS overview, POS functions, plenty POS
:description: plentyPOS is the the point of sale system developed by plentysystems. The plentyPOS functions are included in the plentymarkets app.

[#100]
== What is plentyPOS?

plentyPOS (*Point of Sale*) is our in-house developed solution for managing till sales at your local store. The plentyPOS functions are provided as part of the link:https://knowledge.plentymarkets.com/en-gb/manual/main/app/app.html[plentymarkets app^].
This manual page offers you an overview on where to find information on setting up plentyPOS and using its functions to their best.

[TIP]
.POS demo mode
====
Are you interested in using plentyPOS and want to take a look at its functions without any obligation? Check out our detailed instructions on using the plentyPOS demo mode xref:pos:demo.adoc#[here].
====

[#200]
== How do you set it up?

Have you already decided to use plentyPOS as the point of sale system for your local store? Great! Take a look at the following pages to find further instructions as well as information on how to contact our specialised service partners.

* xref:welcome:quick-start-system-requirements.adoc#500[Selecting suitable hardware]
* xref:pos:integrating-plentymarkets-pos.adoc#[Integrating plentyPOS]
* xref:pos:plentymarkets-pos-for-pos-users.adoc#[plentyPOS for POS users]

[#300]
== Which functions are available?

Once completely set up, your plentyPOS system offers you a variety of possibilities for managing your daily business in your local store. Depending on how exactly you would like to work with the point of sale, the following functions are available:

** xref:pos:plentymarkets-pos-for-pos-users.adoc#30[Ringing up customers]
** xref:pos:integrating-plentymarkets-pos.adoc#2700[Selling and redeeming gift cards and coupons]
** xref:app:item-search.adoc#400[Printing item labels]
** xref:pos:plentymarkets-pos-for-pos-users.adoc#173[Cancelling orders]
** xref:pos:plentymarkets-pos-for-pos-users.adoc#175[Booking returns]
** xref:pos:pos-online-orders.adoc#[Completing Click & Collect orders at the POS]
** xref:pos:plentymarkets-pos-for-pos-users.adoc#180[Withdrawing or depositing cash into the cash drawer]
** xref:pos:plentymarkets-pos-for-pos-users.adoc#210[Creating z reports, x reports and till count reports]

In addition, there are legal regulations and specific exports that you need to take into account when using plentyPOS:

** xref:pos:pos-legal-compliance.adoc#100[Documenting POS transactions for German tax authorities]
** xref:pos:pos-legal-compliance.adoc#1000[Operating legally compliant POS In Austria]
** xref:pos:pos-legal-compliance.adoc#300[Creating IDEA exports]
** xref:pos:pos-legal-compliance.adoc#950[Creating a DSFinV-K export]
** xref:pos:integrating-plentymarkets-pos.adoc#950[Saving booking accounts for POS events]


[#400]
== Stay up to date

Are you looking forward to an upcoming feature for plentyPOS? We’re happy to keep you in the loop about changes to the software! You can see a record of changes link:https://forum.plentymarkets.com/c/changelog/changelog-app[in our changelog^]. Subscribe to the changelog and always stay up to date.
