= The plentymarkets app
:author: team-app-bi
:keywords: App, plentymarkets app, app hardware, install app, set up app, customise app
:description: The plentymarkets app contains the functionalities of the point of sale solution plentyPOS. You can also use the app to securely access the data stored in your plentymarkets back end. This way, you can comfortably keep track of your business while on the go.

[#100]
== Why you should use the app

Keep track of your business on the go. Do you want to see key performance indicators like revenue and sales figures directly on your smartphone? The plentymarkets app is just the tool you need!

Do you want your warehouse technicians to pick orders with a mobile inventory management system? The plentymarkets app helps you pick and pack. Warehouse technicians can also use the app to reshelve items or take stock.

Do you want to link plentymarkets to your brick and mortar store? The plentymarkets mobile POS system is the right tool for the job. Have your employees ring up customers intuitively. The app notifies plentymarkets of any business transactions. That means your online and offline sales always stay in sync.

[#200]
== How do you set it up?

[#300]
=== Download the app and install it on the appropriate hardware

What do you want to use the app for? xref:app:installation.adoc#100[Which hardware you need] depends on what you want to do with the app. For example, if you want to scan barcodes and accept credit card payments, then you’ll need more hardware than if you only want to track sales figures.

Decide which hardware is right for you and download the app on these devices.

* For Android devices: link:https://play.google.com/store/apps/details?id=eu.plentymarkets.mobile&hl=en[plentymarkets app on Google Play^]
* For iOS devices: link:https://apps.apple.com/gb/app/plentymarkets/id957702618[plentymarkets app on iTunes^]

[#400]
=== Log in and grant access

The plentymarkets app will only work if you’ve link:https://www.plentymarkets.com/[booked a plentymarkets ERP system^]. In other words, you’ll xref:app:installation.adoc#1200[log into the app with the same access data] that you use for your plentymarkets system.

If you want other employees to use the plentymarkets app too, then you’ll need to give them access data. xref:app:installation.adoc#600[Decide which areas of the app] your employees should have access to.

[#500]
=== Customise the app

Do you want to control, e.g. which information is displayed first, second, third, etc and which font size is used to display information in the app? Or do you want to use colours that match your own corporate design instead of the default background? xref:app:installation.adoc#1800[Customise the app] and set it up the way you want!

[#600]
=== Stay up to date

Are you looking forward to an upcoming feature? We’re happy to keep you in the loop about changes to the software! Each version of the app gets its own version number. You can see a record of changes link:https://forum.plentymarkets.com/c/changelog/changelog-app[in our changelog^]. Subscribe to the changelog and always stay up to date.


[#700]
== Which functions are available?

The plentymarkets app includes a wide range of useful functions. Learn all about them on the following pages.

[IMPORTANT]
.Switch to the plentyWarehouse app now!
====
The functions for mobile stock management included in the plentymarkets app will not be developed further. We recommend that you use the new and improved functions included in the plentyWarehouse app instead. Click xref:stock-management:plentywarehouse.adoc#[here] to get all important information regarding plentyWarehouse.
====

* xref:app:key-figures.adoc#[Viewing key performance indicators]
* xref:app:item-search.adoc#[Viewing item, customer and order data]
* xref:app:warehouse-management.adoc#[Mobile inventory management system]
** xref:app:mobile-box-picking.adoc#[Box picking]
** xref:app:receiving-rebooking.adoc#[Receiving goods and replenishing stock]
** xref:app:reshelving.adoc#[Reshelving items]
** xref:app:stocktaking.adoc#[Stocktaking]
* xref:pos:pos.adoc#[The plentymarkets mobile POS system]
** xref:pos:plentymarkets-pos-for-pos-users.adoc#30[Ringing up customers]
** xref:pos:integrating-plentymarkets-pos.adoc#2700[Selling and redeeming gift cards and coupons]
** xref:pos:plentymarkets-pos-for-pos-users.adoc#173[Cancellations and returns]
** xref:pos:pos-online-orders.adoc#[Processing online orders (Click & Collect)]
** xref:pos:plentymarkets-pos-for-pos-users.adoc#180[Deposits and withdrawals]
** xref:pos:plentymarkets-pos-for-pos-users.adoc#210[Creating z reports and till count reports]
