= Searching for items, customers and orders
:lang: en
include::{includedir}/_header.adoc[]
:author: team-mobile
:keywords: App, app item search, app item labels, print labels, app order search, app customer search, search filters app
:description: The plentymarkets app makes it easy to search for items while on the go.
:position: 20
:url: app/functions/item-search
:icons: font
:docinfodir: /workspace/manual-adoc
:docinfo1:

Keep track of your business on the go. Do you want to monitor new orders directly on your smartphone? Do you want to look up a customer’s address or telephone number? The plentymarkets app is just the tool you need!

[#100]
== Item search

The plentymarkets app makes it easy to search for items while on the go. Do you want to quickly check an item’s price? Do you want to see how many copies are still in stock? Or do you want to use the app to print out the item label? The plentymarkets app makes it possible.

The plentymarkets app includes an item search function, which is described on this page. First, <<app/functions/item-search#200, configure a few basic settings>> and decide what you want the search results to look like. These settings will go into effect when you <<app/functions/item-search#300, search for items>> later.

[#200]
=== Customising the item search

How many search results do you want to see at once? Should some pieces of information be displayed in large or small font? Do you typically search for items by their ID, name or barcode? You’ll answer these sorts of questions while customising the default search settings.

[.instruction]
Customising the item search:

. <<app/installation#1100, Log into the plentymarkets app>>.
. Tap on the menu icon (icon:bars[role="blue"]) in the top left corner of the app.
. Tap on icon:cog[role="darkGrey"] *Settings*.
. Tap on icon:search[role="darkGrey"] *Item search*.
. Carry out the settings. Note <<table-customise-item-search>>.
. Tap on the check mark (icon:check[role="blue"]) in the upper right corner to confirm the change.

[[table-customise-item-search]]
.Customising the item search
[cols="1,3"]
|====
|Setting |Explanation

| *Number of items to be loaded*
|How many search results do you want to see at once? Select a number from the drop-down list.

| *Item search fields*
|Which information do you use when searching for items? Use the toggle buttons to specify which parameters can be used for the item search. +
*Activated* (icon:toggle-on[role="green"]) = You will be able to use this parameter when searching for items.

| *Focus on search field*
|Do you typically search by a particular parameter? Tap on whichever parameter you use most often. When you search for items later, your cursor will automatically start in this field. Of course, it will still be possible to manually place the cursor in another field.

| *Template*
|What should the search results look like? The plentymarkets app comes with a default template, which is appropriate for most item searches. However, you can create <<app/installation#1900, additional templates>> in the plentymarkets backend menu *Setup » plenty app » Item search* and then select these templates from the drop-down list here. +
*_Tip:_* Templates let you control, e.g. which information is displayed first, second, third, etc and which font size each piece of information should have. In other words, templates let you control how information is displayed in the search results and the detailed view of an item.

| *Item label*
|Do you want to use the plentymarkets app to print item labels? Choose the <<item/settings/barcodes#800, item label that you’ve designed for this purpose>>. +
*_Tip:_* This area is only displayed if you’ve <<app/installation#2050, linked the app to plentyBase>>.

| *Printer*
|Do you want to use the plentymarkets app to print item labels? Select whichever printer you want to use for printing labels. +
*_Tip:_* This area is only displayed if you’ve <<app/installation#2050, linked the app to plentyBase>>.
|====

[#300]
=== Searching for items

Search for the item and access your entire product catalogue.

[.instruction]
Searching for items:

. <<app/installation#1100, Log into the plentymarkets app>>.
. Tap on the menu icon (icon:bars[role="blue"]) in the top left corner of the app.
. Tap on icon:search[role="darkGrey"] *Item search*. +
→ The item search opens.
. Enter a search criteria, e.g. an item ID.
. Tap on icon:search[role="blue"] *Search*. +
→ A list of items matching the search criteria is displayed.
. Select an item (icon:check[role="green"]). +
→ The detailed view is shown.

[TIP]
.Viewing stock information
====
//Umbuchung-Link auch anpassen auf dem bestimmten Kapitel nachdem die Info auf die Umbuchung-Seite ergänzt wurde.
Tap on the boxes (icon:cubes[role="blue"]) to see stock information. Then tap on the three dots (icon:ellipsis-h[role="blue"]) if you want to <<app/functions/warehouse-management/receiving-rebooking#500, replenish the stock>> or if you want to <<app/functions/item-search#400, print the item label>>.
====

[#400]
=== Printing labels with the plentymarkets app

You can use the app to manually generate labels for specific items.

[TIP]
.Have you met all the requirements?
====
Before you can print labels with the app, you have to:

* download a tool called plentyBase and <<app/installation#2050, link it to the app>>
* use <<item/settings/barcodes#800, templates to design your labels>>
* specify which <<app/functions/item-search#200, label template and printer>> you want to use
====

[.instruction]
Printing labels with the plentymarkets app:

. <<app/functions/item-search#300, Search for the item in the app>>.
. Tap on the boxes (icon:cubes[role="blue"]) to see stock information. +
→ The storage locations of the item are shown.
. Tap on the three dots (icon:ellipsis-h[role="blue"]). +
→ Additional options are shown.
. Tap on icon:print[role="blue"] *Print item label*. +
→ The label is printed.

[#500]
== Customer search

The plentymarkets app makes it easy to search for customers while on the go.
Do you need to look up a customer’s email address or telephone number?
Do you want to check whether you have special payment conditions for this customer? For example, if this customer receives a percentage discount if he pays within a certain time frame?
The plentymarkets app makes it possible.

The plentymarkets app includes a customer search function, which is described on this page. First, <<app/functions/item-search#600, configure a few basic settings>> and decide what you want the search results to look like. These settings will go into effect when you <<app/functions/item-search#700, search for customers>> later.

[#600]
=== Customising the customer search

How many search results do you want to see at once?
Do you typically search for customers by their ID, name or postcode? You’ll answer these sorts of questions while customising the default search settings.

[.instruction]
Customising the customer search:

. <<app/installation#1100, Log into the plentymarkets app>>.
. Tap on the menu icon (icon:bars[role="blue"]) in the top left corner of the app.
. Tap on icon:cog[role="darkGrey"] *Settings*.
. Tap on icon:address-card-o[role="darkGrey"] *Customer search*.
. Carry out the settings. Note <<table-modify-customer-search>>.
. Tap on the check mark (icon:check[role="blue"]) in the upper right corner to confirm the change.

[[table-modify-customer-search]]
.Customising the customer search
[cols="1,3"]
|====
|Setting |Explanation

| *Number of customers to be loaded*
|How many search results do you want to see at once? Select a number from the drop-down list.

| *Customer search fields*
|Which information do you use when searching for customers? Use the toggle buttons to specify which parameters can be used for the customer search. +
*Activated* (icon:toggle-on[role="green"]) = You will be able to use this parameter when searching for customers.

| *Focus on search field*
|Do you typically search by a particular parameter? Tap on whichever parameter you use most often. When you search for customers later, your cursor will automatically start in this field. Of course, it will still be possible to manually place the cursor in another field.
|====

[#700]
=== Searching for customers

Use the customer search and access your entire customer database.

[.instruction]
Searching for customers:

. <<app/installation#1100, Log into the plentymarkets app>>.
. Tap on the menu icon (icon:bars[role="blue"]) in the top left corner of the app.
. Tap on icon:address-card-o[role="darkGrey"] *Customer search*. +
→ The customer search opens.
. Enter a search criteria, e.g. a contact ID.
. Tap on icon:search[role="blue"] *Search*. +
→ You’ll see all the customer data records that were found.
. Tap on a customer data record. +
→ The detailed view is shown.

[TIP]
.Viewing company and address data
====
Tap on the factory (icon:industry[role="blue"]) to see company information.
For example, here you can check whether this customer receives a percentage discount if he pays within a certain time frame.
Keep in mind that this area will only include information if you’ve saved <<crm/managing-contacts#90, company information in the customer data record>>.

Tap on the map marker (icon:map-marker[role="blue"]) to see address information.
====

[#800]
== Order search

The plentymarkets app includes an order search function, which is described on this page. First, <<app/functions/item-search#900, configure a few basic settings>> and decide what you want the search results to look like. These settings will go into effect when you <<app/functions/item-search#1000, search for orders>> later.

[#900]
=== Customising the order search

How many search results do you want to see at once? Should some pieces of information be displayed in large or small font?
You’ll answer these sorts of questions while customising the default search settings.

[.instruction]
Customising the order search:

. <<app/installation#1100, Log into the plentymarkets app>>.
. Tap on the menu icon (icon:bars[role="blue"]) in the top left corner of the app.
. Tap on icon:cog[role="darkGrey"] *Settings*.
. Tap on icon:list-alt[role="darkGrey"] *Orders*.
. Carry out the settings. Note <<table-modify-order-search>>.
. Tap on the check mark (icon:check[role="blue"]) in the upper right corner to confirm the change.

[[table-modify-order-search]]
.Customising the order search
[cols="1,3"]
|====
|Setting |Explanation

| *Number of orders to be loaded*
|How many search results do you want to see at once? Select a number from the drop-down list.

| *Template*
|What should the order data look like? The plentymarkets app comes with a default template, which is appropriate for most order searches. However, you can create <<app/installation#1900, additional templates>> in the plentymarkets backend menu *Setup » plenty app » Order overview* and then select these templates from the drop-down list here. +
*_Tip:_* Templates let you control, e.g. which information is displayed first, second, third, etc and which font size each piece of information should have. In other words, templates let you control how the order and item information is displayed.
|====

[TIP]
.Save frequently used search criteria
====
When you <<app/functions/item-search#1000, search for orders>> later, the app will automatically load your newest orders.
But maybe you want to regularly search for orders that are in a specific status or that came from a specific sales platform.
Not only can you <<app/functions/item-search#1100, use filters to narrow down the search results>>, but you can also save your most frequently used search criteria so you don’t have to re-enter the filter parameters every time you search.
====

[#1000]
=== Searching for orders

Use the order search to look up important information about your orders.

[.instruction]
Searching for orders:

. <<app/installation#1100, Log into the plentymarkets app>>.
. Tap on the menu icon (icon:bars[role="blue"]) in the top left corner of the app.
. Tap on icon:list-alt[role="darkGrey"] *Orders*. +
→ Your orders will be loaded.
. Tap on an order. +
→ The detailed view is shown.
. Look up the relevant order information. Note <<table-order-areas>>.

[[table-order-areas]]
.Order areas
[cols="1,9"]
|====
|Area |Explanation

|icon:info-circle[role="blue"]
|Basic information about the order, e.g. its ID and status, the payment and shipping method, the price, the weight, etc. <<app/functions/item-search#900, Create a template>> if you want to control which information is displayed in this area. Tap on the three dots (icon:ellipsis-v[role="blue"]) to manually change the order status in the app.

|icon:list[role="blue"]
|Information about the items that were ordered, e.g. the item name, quantity and price. <<app/functions/item-search#900, Create a template>> if you want to control which information is displayed in this area.

|icon:thumb-tack[role="blue"]
|Notes that were saved for this order. Tap on the three dots (icon:ellipsis-v[role="blue"]) to add a new note.

|icon:money[role="blue"]
|Payments belonging to this order.

|icon:history[role="blue"]
|The order’s status history.
|====

[TIP]
.Can I also fulfil orders in the app?
====
There are only a few limited options for processing orders with the app. Tap on the three dots (icon:ellipsis-v[role="blue"]) if you want to manually change the order’s status, send an email to the customer or write a note for this order.
====

[#1100]
=== Filters

When you <<app/functions/item-search#1000, search for orders>>, the app automatically loads your newest orders.
But maybe you want to search for orders that are in a specific status or that came from a specific sales platform.
Simply use filters to narrow down the search results! You can also save your most frequently used search criteria so you don’t have to re-enter the filter parameters every time you search.

[.instruction]
Filtering orders:

. <<app/installation#1100, Log into the plentymarkets app>>.
. Tap on the menu icon (icon:bars[role="blue"]) in the top left corner of the app.
. Tap on icon:list-alt[role="darkGrey"] *Orders*. +
→ Your orders will be loaded.
. Tap on the filter icon (icon:filter[role="blue"]) in the top right corner. +
→ The filter settings are shown.
. Select the appropriate filters.
. Tap on icon:filter[role="blue"] *Apply*. +
→ The orders that match the filter criteria will be displayed.

[TIP]
.Save your most frequently used search criteria
====
Do you want to re-use these filter settings in the future? Then scroll down to the bottom and tap on the empty line to the left of the check mark.
Enter a name for the filter template and tap on the check mark (icon:check[role="blue"]).

When you search for orders in the future, you’ll be able to select this filter template from the drop-down list at the top of the screen and then tap on icon:filter[role="blue"] *Apply*.
====
