= Mobile inventory management system
:author: team-app
:keywords: App, mobile warehouse management, app warehouse management, app stock management, mobile stock management
:description: Do you want your warehouse technicians to pick orders with a mobile inventory management system? The plentymarkets app helps you pick and pack. Warehouse technicians can also use the app to reshelve items or take stock.

Do you want your warehouse technicians to pick orders with a mobile inventory management system? The plentymarkets app helps you pick and pack. Warehouse technicians can also use the app to reshelve items or take stock.

[IMPORTANT]
.Switch to the plentyWarehouse app now!
====
The functions for mobile stock management included in the plentymarkets app will not be developed further. We recommend that you use the new and improved functions included in the plentyWarehouse app instead. Click xref:stock-management:plentywarehouse.adoc#[here] to get all important information regarding plentyWarehouse.
====

* xref:app:mobile-box-picking.adoc#[Box picking]
* xref:app:receiving-rebooking.adoc#[Booking incoming items and redistributing items]
* xref:app:reshelving.adoc#[Reshelving items]
* xref:app:stocktaking.adoc#[Stocktaking]
