= Abhollieferung
:page-aliases: dokument-abhollieferung-erzeugen.adoc
:keywords: Abhollieferung, Abhollieferungen, Abhol-/Lieferschein, Abholschein, Lieferschein, Auftragsdokumente, Dokumentenvorlage, Dokumententyp, Dokument, Dokumentvorlage, Dokumenttyp,
:author: team-docs-automation
:description: Erfahre, wie du eine Dokumentenvorlage für Abhollieferungen anlegst und damit ein Dokument zur Abhollieferung erzeugst. In plentymarkets wird das Dokument auch Abhol-/Lieferschein genannt.

Ware wird bei dir abgeholt? Nutze dafür das Dokument Abhollieferung, auch Abhol-/Lieferschein genannt. Dieser kann als PDF-Datei generiert werden, um diesen dann zum Beispiel zu drucken oder als E-Mail-Anhang zu verschicken.

[#100]
== Dokumentenvorlage für Abhollieferungen einrichten

Bevor du Abhollieferungen generieren kannst, muss eine Dokumentenvorlage eingerichtet werden. Dies geschieht im Menü *Einrichtung » Mandant » [Mandant wählen] » Standorte » [Standort wählen] » Dokumente » Abhol-Lieferschein*. +
Weitere Informationen und Anleitungen zur Einrichtung der Dokumentenvorlage findest du auf der Handbuchseite xref:auftraege:auftragsdokumente-neu.adoc#[Auftragsdokumente].

[#200]
== Einzelne Abhollieferung erzeugen

Das Dokument Abhollieferung kannst du manuell an verschiedenen Auftragstypen erzeugen. Gehe dafür wir im Folgenden beschrieben vor.

[.instruction]
Dokument Abhollieferung manuell erzeugen:

. Öffne das Menü *Aufträge » Aufträge (Testphase)*.
→ Die Auftragsübersicht wird geöffnet.
. Führe die Suche (material:search[]) aus, um Aufträge anzuzeigen.
. Öffne den Auftrag, für den eine Abhollieferung erzeugt werden soll.
. Gehe in den Bereich *Dokumente*.
. Klicke oben links auf *Dokument erstellen* (material:add[]).
. Wähle das Dokument *Abhollieferung* aus der Dropdown-Liste. +
→ Das Fenster *Dokument erzeugen: Abhollieferung* wird geöffnet.
. Gib ein Datum ein, das auf der Abhollieferung angezeigt werden soll.
. Gib optional einen Kommentar ein, der auf der Abhollieferung angezeigt werden soll.
. Klicke auf *Erstellen* (material:add[role="green"]). +
→ Die Abhollieferung wird erstellt und im Bereich *Dokumente* hinzugefügt.
