= Abonnement
:keywords: Abonnement-Übersicht, Scheduler, Abo, Abonnement, Abo-Modul, Abomodul, Scheduler-Auftrag, Durchlauf, Durchläufe, automatischer Durchlauf, Durchlaufvorschau, Abo-Aufträge, Abo-Auftrag, Intervall, Abo-Intervall, Abo-Funktion, Abofunktion, Subscription, Abointervall, Aboauftrag, Gesperrte Abonnements, Abos, Aboübersicht
:author: team-order-core
:description: Erfahre, wie du Abonnements anlegst und verwaltest. Lerne außerdem, wie du anhand der Durchlaufvorschau eine Liste aller fälligen Abonnements generierst oder wie du Abonnements sperrst und wieder entsperrst.

Das Menü *Aufträge » Abonnement* ermöglicht es dir, für Kund:innen intervallgesteuert automatisierte Aufträge anzulegen. So bekommen deine Kund:innen in regelmäßigen zeitlichen Abständen die ausgewählten Artikel zugeschickt, ohne dass du jeden Auftrag einzeln anlegen musst. Erstelle ein individuelles Abonnement für eine Kund:in und konfiguriere es wie gewünscht. +
Das Erstellen und Bearbeiten der Abonnements findet gut überschaubar in einem eigenen Menü deines plentymarkets Systems statt. Die Abonnements können auch aus Aufträgen vom Typ *Angebot* heraus erstellt werden. Durch Abonnements generierte Aufträge bearbeitest du dann wie andere Aufträge auch in der Auftragsübersicht. Im Folgenden erfährst du, wie du <<#200, Abonnements anlegst>>, die <<#300, Einstellungen vornimmst>> und welche Bearbeitungsmöglichkeiten dir zur Verfügung stehen.

[#100]
== Vorbereitende Einstellungen

Neue Einstellungen
Damit du so bequem wie möglich mit dem Abonnement arbeiten kannst, solltest du vorher einige vorbereitende Einstellungen beachten und vornehmen. Zum einen hast du die Möglichkeit, <<#110, Standardeinstellungen>> für deine Abonnements zu wählen, sodass diese beim Anlegen neuer Abonnements vorausgewählt sind und nicht jedes Mal neu von dir eingestellt werden müssen. Auf diese Weise kannst du im Voraus Einstellungen festlegen und beim Anlegen neuer Abonnements Zeit sparen. Zum anderen solltest du <<#120, Benutzerrechte vergeben>>, wenn auch Benutzer:innen vom Typ *Backend* mit Abonnements arbeiten sollen. In den folgenden zwei Kapiteln werden sowohl die Standardeinstellungen als auch die Einstellungen für die Vergabe der notwendigen Benutzerrechte beschrieben.

Außerdem kannst du die Tabellen individuell anpassen. Das bedeutet, dass du selbst entscheiden kannst, welche Informationen in den Tabellenspalten angezeigt werden. Gehe dafür wie im Folgenden beschrieben vor:

[.instruction]
Tabelle individualisieren:

. Klicke auf *Spalten konfigurieren* (material:settings[]). +
→ Das Fenster *Spalten konfigurieren* wird geöffnet.
. Wähle, welche Spalten angezeigt werden sollen.
. Verschiebe (material:drag_indicator[]) die Spalten, sodass sie in der Reihenfolge angezeigt werden, in der du sie benötigst.
. Klicke auf *Bestätigen*, um deine Auswahl zu speichern.

Wenn du eine Tabelle angepasst hast, wird diese Auswahl gespeichert. Du kannst die Tabellen jederzeit anpassen.

[#110]
=== Standardeinstellungen festlegen

Im Menü *Einrichtung » Aufträge » Auftragstypen » Abonnement* kannst du einige grundlegende Einstellungen in Form von Standardeinstellungen für deine Abonnements festlegen. +
So sind die hier vorgenommenen Einstellungen für deine neu angelegten Abonnements dann vorausgewählt.
Sie können deine Arbeit beschleunigen, wenn du regelmäßig die gleichen Einstellungen beim Anlegen von Abonnements wählst. Es ist aber dennoch weiterhin möglich, beim Anlegen eines Abonnements abweichende Einstellungen zu vorzunehmen.

[.instruction]
Standardeinstellungen vornehmen:

. Öffne das Menü *Einrichtung » Aufträge » Auftragstypen » Abonnement*.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<#table-subscription-default-settings>>.
. *Speichere* (material:save[]) die Einstellungen.

[[table-subscription-default-settings]]
.Standardeinstellungen des Abonnements
[cols="1,3"]
|===
|Einstellung |Erläuterung

|[#intable-subscription-automatic-orders]*Für fällige Abonnements automatisch Aufträge erzeugen*
|Wähle, ob für jedes Abonnement automatisch Aufträge mit zugeordneter Auftrags-ID erstellt werden sollen, wenn diese fällig sind. Diese Aufträge werden dann automatisch in der Auftragsübersicht eingeordnet und können dort bearbeitet werden. +
*_Hinweis:_* Die Aufträge werden _nicht_ automatisch erzeugt. Wenn du diese Option nicht aktivierst, müssen die Aufträge somit manuell angestoßen werden.

|[#intable-subscription-default-status]*Standard-Status*
|Wähle einen Standardstatus, der für Abonnements gelten soll. Dieser Status ist dann für neu angelegte Abonnements vorausgewählt, kann aber individuell angepasst werden. Dir stehen alle xref:auftraege:order-statuses.adoc#[Status] zur Verfügung, die du in deinem plentymarkets System festgelegt hast.

|[#intable-subscription-default-owner]*Standard-Eigner*
|Wähle einen Standardeigner. Achte darauf, dass der zugewiesene Eigner die benötigten <<#120, Benutzerrechte>> für das Abonnement hat.

|[#intable-subscription-default-interval]*Standard-Intervall*
|Wähle optional einen Zeitabstand, in dem die Artikel eines Abonnements standardmäßig verschickt werden sollen. Dieses Intervall ist dann für neu angelegte Abonnements vorausgewählt, kann aber individuell angepasst werden.

|[#intable-subscription-default-client]*Standard-Mandant*
|Wähle einen Standard-Mandanten, der beim Anlegen neuer Abonnements vorausgewählt sein soll.

|[#intable-subscription-default-referrer]*Standard-Herkunft*
|Wähle eine Standard-Herkunft, die beim Anlegen neuer Abonnements vorausgewählt sein soll.

|*Anzeige von hinzugefügten Artikeln im Warenkorb*
|Wähle, wie die Artikel zum Warenkorb hinzugefügt werden sollen. +
*Als eine Auftragsposition, Mengen werden erhöht* = Gleiche Artikel werden in einer Auftragsposition zusammengefasst und die Menge wird entsprechend angepasst. Dies ist die Standardeinstellung. +
*Als separate Auftragspositionen* = Auch gleiche Artikel werden einzeln hinzugefügt, d.h. jeder Artikel wird in einer eigenen Zeile dargestellt.

|===

[.discrete]
==== Durchlaufvorschau

Im gleichen Menübereich unter *Einrichtung » Aufträge » Auftragstypen » Abonnement* steht dir auch die *Durchlaufvorschau* zur Verfügung.
Klicke oben auf die Schaltfläche *Durchlaufvorschau*, um eine Auflistung *Fälliger Abonnements* zu sehen. Die fälligen Abonnements sind aufsteigend nach der Auftrags-ID sortiert.
Außerdem siehst du die Laufzeit der Abonnements sowie den letzten und nächsten Durchlauf auf einen Blick.

Die Fälligkeit der Abonnements wird systemseitig _einmal täglich_ abgefragt und angestoßen. Die *Durchlaufvorschau* bietet dir nicht nur die Möglichkeit zur Übersicht und Überprüfung anstehender Abonnements, du kannst fällige Abonnements hier auch selbst sofort anstoßen. Beachte dabei, dass hier _alle auf einmal und sofort_ angestoßen werden. Eine Auswahl einzelner Abonnements ist in dieser Ansicht nicht möglich.
Wie du manuelle Durchläufe für einzelne Abonnements in der Detailansicht jedes Abonnements durchführst, ist im Kapitel <<#800, Abgeschlossene Aufträge: Durchläufe>> ausführlicher erläutert.

Wenn dir also fällige Abonnements angezeigt werden, klicke für das sofortige Anstoßen rechts unten im Fenster auf *Durchlaufvorschau* und warte einen Moment.
Die Meldung *Durchlauf durchgeführt* wird nach der Beendigung angezeigt. Die auf diese Weise generierten Aufträge findest du nun sowohl in der *Auftragsübersicht* als auch im Bereich <<#800, Abgeschlossene Aufträge>> in der Detailansicht des dazugehörigen Abonnements.

[IMPORTANT]
.Verwendung der Durchlaufvorschau
====
Das sofortige Anstoßen aller fälligen Abonnements lässt sich nicht rückgängig machen. In der Auftragsübersicht kannst du die generierten Aufträge allerdings stornieren.
====

[#120]
=== Benutzerrechte vergeben

:rights-purpose: Abonnements sehen und bearbeiten können
:right-one: pass:quotes[*Artikel > Artikel > Variante > Lesen*]
:right-two: pass:quotes[*Artikel > Artikel > Variante > Preis > Lesen*]
:right-three: pass:quotes[*Artikel > Verkaufspreis > Lesen*]
:right-four: pass:quotes[*Aufträge > Lesen*]
:right-five: pass:quotes[*CRM > Nachricht > Lesen*]
:right-six: pass:quotes[*Einrichtung > Tag > Lesen*]

include::_includes:partial$rights.adoc[]

Sollen Mitarbeiter:innen ohne Adminrechte Abonnements auch anlegen können, benötigen diese Mitarbeiter:innen zusätzlich die folgenden Rechte:

* *CRM > Adresse > Lesen*
* *CRM > Kontakt > Lesen*
* *Einrichtung > Eigenschaft > Lesen*
* *Einrichtung > Tag > Tag-Verknüpfung > Löschen*
* *POS > POS > Lesen*

[#subscription-myview]
== MyView nutzen

Die Bedienoberfläche der Detailansichten von Abonnements stehen dir als MyView zur Verfügung. Das bedeutet, dass Benutzer:innen sich jeweils eine eigene Ansicht mit den zur Verfügung stehenden Elementen erstellen können. Dadurch kann jede:r selbst bestimmen, welche Informationen an welcher Stelle benötigt werden. Durch diese Individualisierung wird das Arbeiten nicht nur komfortabler, sondern auch beschleunigt. In diesem Kapitel wird erklärt, wie du anhand der MyView eine eigene Ansicht anlegst. Das Bearbeiten von Abonnements, z.B. das <<#400, Erstellen einer Artikelliste>> oder das <<#600, Ändern der Versandkosten und Versandart>>, wird in den nachfolgenden Kapiteln erklärt.

Zur Detailansicht eines Abonnements gelangst du von der Übersichtstabelle im Menü *Aufträge » Abonnement* aus. Klicke in die Zeile des Abonnements, um die Detailansicht des ausgewählten Abonnements zu öffnen. +
Wenn du hier noch keine eigene Ansicht erstellt hast, wird dir die *Standardansicht* angezeigt. Du kannst diese Ansicht so lassen und damit arbeiten oder dir eine eigene Ansicht erstellen. Eigene Ansichten werden gespeichert und stehen dir dann zusammen mit der Standardansicht als Auswahl unter der Liste der Ansichten (icon:caret-down[role="darkGrey"]) zur Verfügung. Somit kannst du jederzeit zwischen den Ansichten wechseln. Die ausgewählte Ansicht wird beim Öffnen eines Abonnements automatisch angewendet.

[#create-new-view]
=== Neue Ansicht erstellen

. Klicke auf die Liste der Ansichten (icon:caret-down[role="darkGrey"]).
. Klicke auf icon:plus[role="darkGrey"] *Neue Ansicht erstellen ...*.
. Gib einen Namen ein.
. Klicke auf *Ansicht erstellen*. +
→ Die neue Ansicht wird erstellt und automatisch geöffnet, d.h. sie wird angewendet.
Es ist jetzt möglich, zwischen den Ansichten zu wechseln.

[#create-grid]
=== Ein Raster erstellen

. Klicke auf *Ansicht bearbeiten* (terra:design_inline_edit[]).
. Füge Zeilen und Spalten hinzu, um ein Raster zu erstellen.
.. Klicke auf icon:ellipsis-v[role="blue"] und anschließend auf icon:plus[role="darkGrey"] *Zeile hinzufügen*.
.. Klicke auf *Spalte hinzufügen* (icon:plus[role="darkGrey"]).
.. Ziehe die Spalten, um sie zu vergrößern oder zu verkleinern.

[#place-elements]
=== Elemente platzieren

. Füge Elemente per Drag & Drop hinzu.
. Klicke auf icon:pencil[role="blue"] und passe die Einstellungen für das Element an.
.. Ändere den Namen.
.. Entscheide, welche Datenfelder das Element enthalten soll.
.. Lege die Reihenfolge der Datenfelder per Drag & Drop fest.
. Klicke auf icon:close[role="blue"].

[cols="1,4a"]
|====
|Symbol |Erläuterung

| icon:pencil[role="blue"]
|Führt eine Ebene tiefer.

| icon:trash[role="blue"]
|Löscht das Element.

| icon:close[role="blue"]
|Führt eine Ebene höher.
|====

[TIP]
.Kann ich Elemente mehrfach hinzufügen?
======
Die Zahl am Element gibt an, wie oft du das Element verwenden kannst. Die meisten Elemente können nur einmal hinzugefügt werden.
======

[#finalise-editing]
=== Bearbeitung abschließen

. Speichere die Ansicht (terra:save[role="darkGrey"]) und schließe den Bearbeitungsmodus (icon:close[role="darkGrey"]).
. Prüfe das Ergebnis im Hauptfenster.
. Falls erforderlich:
.. Klicke noch einmal auf *Ansicht bearbeiten* (terra:design_inline_edit[]) und passe die Ansicht weiter an.
.. Erlaube anderen Benutzer:innen, die Ansicht zu sehen.

[#editing-functions]
==== Funktionen im Bearbeitungsmodus

[cols="1,4"]
|====
|Symbol |Erläuterung

| icon:reply[role=darkGrey]
|Macht die letzte Änderung rückgängig, soweit die betreffende Änderung noch nicht gespeichert wurde.

| icon:share[role=darkGrey]
|Stellt eine rückgängig gemachte Änderung wieder her.

| icon:caret-down[role="darkGrey"]
|Öffnet die Liste der Ansichten.
Der Name der aktuell geöffneten Ansicht wird angezeigt.
Klicke auf icon:caret-down[role="darkGrey"], um zu einer anderen Ansicht zu wechseln oder eine <<#create-new-view, neue Ansicht>> zu erstellen.

| terra:items_incoming_history[]
|Setzt die Ansicht auf den Stand des letzten Speicherpunkts zurück.

| terra:save[role="darkGrey"]
|Speichert die Änderungen, die an der Ansicht vorgenommenen wurden.

| terra:close[]
|Schließt den Bearbeitungsmodus.
Falls ungespeicherte Änderungen vorhanden sind, wird eine Sicherheitsabfrage angezeigt.
|====


[#200]
== Neues Abonnement anlegen

Ein neues Abonnements legst du über das Menü *<<#250, CRM » Kontakte>>* oder aus einem Auftrag vom Typ *<<#610, Angebot>>* heraus an.

[#250]
=== Abonnements über Kontakte anlegen

[.instruction]
Neues Abonnement über die Kontaktübersicht anlegen:

. Öffne das Menü *CRM » Kontakte*.
. Suche den Kontakt anhand der Filtereinstellungen. Beachte dazu die Erläuterungen zu den Filtern auf der Seite xref:crm:kontakt-suchen.adoc#[Kontakt suchen]. +
→ Die Kontakte, die den Suchkriterien entsprechen, werden angezeigt.
. Klicke in der Zeile des Kontakts ganz links auf material:more_vert[]. +
→ Eine Auswahl der verfügbaren Optionen wird geöffnet.
. Navigiere zu material:shopping_cart[] *Aufträge* > *Neues Abonnement*. +
→ Du wirst automatisch zu den Einstellungen für das neue Abonnement weitergeleitet.

[#300]
==== Einstellungen vornehmen

Aus dem Kontaktdatensatz des gewählten Kontakts werden bereits Daten für das Abonnement übernommen. Dazu zählen zum Beispiel die Adressen oder die dem Kontakt zugeordnete Zahlungsart. Grundlegende Einstellungen des Abonnements werden in <<#table-basic-settings-subscription>> erläutert.

[[table-basic-settings-subscription]]
.Erläuterungen zu den Einstellungen des Abonnements
[cols="1,3"]
|====
|Einstellung|Erläuterung

|[#intable-subscription-status]*Status*
|Wenn du einen <<#intable-subscription-default-status, Standardstatus>> eingestellt hast, ist dieser hier vorausgewählt. Darüber hinaus stehen dir hier alle xref:auftraege:order-statuses.adoc#[Status] zur Verfügung, die du in deinem plentymarkets System angelegt hast. Wähle den passenden Status manuell aus der Dropdown-Liste.

|[#intable-subscription-tags]*Tags*
|Hier stehen dir Tags zur Verfügung, die du in deinem plentymarkets System angelegt hast. Wähle das gewünschte Tag aus der Dropdown-Liste.

|[#intable-subscription-invoice-address]*Rechnungsadresse*
|Wähle die gewünschte Rechnungsadresse des Kontakts aus der Dropdown-Liste. Zur Auswahl stehen die Adressen, die auch im dazugehörigen Kontaktdatensatz gespeichert sind. Zur Unterscheidung von mehreren gespeicherten Adressen für einen Kontakt wird die Adress-ID ebenfalls angegeben. Wenn eine Adresse als primäre Rechnungsadresse festgelegt ist, wird diese durch einen Stern gekennzeichnet. +
_Dies ist ein Pflichtfeld._

|[#intable-subscription-invoice-address]*Lieferadresse*
|Wähle die gewünschte Lieferadresse des Kontakts aus der Dropdown-Liste. Zur Auswahl stehen die Adressen, die auch im dazugehörigen Kontaktdatensatz gespeichert sind. Zur Unterscheidung von mehreren gespeicherten Adressen für einen Kontakt wird die Adress-ID ebenfalls angegeben. Wenn eine Adresse als primäre Lieferadresse festgelegt ist, wird diese durch einen Stern gekennzeichnet. +
_Dies ist ein Pflichtfeld._

|[#intable-subscription-interval]*Abo-Intervall*
|Das hier gewählte Intervall legt fest, in welchen Zeitabständen Artikel an Kund:innen versendet werden. Wenn du ein <<#intable-subscription-default-interval, Standard-Intervall>> eingestellt hast, ist dieses Intervall hier vorausgewählt. Das Intervall lässt sich durch die Auswahl in der Dropdown-Liste anpassen. +
_Dies ist ein Pflichtfeld._

|[#intable-subscription-currency]*Währung*
|Wähle die Währung für das Abonnement. Die von dir eingestellte xref:payment:waehrungen.adoc#30[Systemwährung] ist vorausgewählt.

|[#intable-subscription-start]*Beginn des Abonnements*
|Wähle das Startdatum (material:today[]) für das Abonnement. Beachte, dass das Startdatum vor dem Enddatum liegen muss. Wenn das Startdatum in der Vergangenheit liegt, wird der erste automatische Durchlauf für das Abonnement am ausgewählten Startdatum plus dem ausgewählten Intervall ausgeführt. Vorher wird kein automatischer Durchlauf ausgeführt. Es ist aber jederzeit möglich, einen <<#800, manuellen Durchlauf>> anzustoßen. +
_Dies ist ein Pflichtfeld._

|[#intable-subscription-end]*Ende des Abonnements*
|Wähle das Enddatum (material:today[]) für das Abonnement. Beachte, dass das Enddatum nach dem Startdatum liegen muss. Nach dem gewählten Enddatum finden keine Durchläufe mehr für das Abonnement statt. +
_Dies ist ein Pflichtfeld._

|[#intable-subscription-cancelled]*Gekündigt*
|Wähle ein Kündigungsdatum (material:today[]) für das Abonnement, wenn es gekündigt wurde. Das Kündigungsdatum kann auch vor dem Startdatum des Abonnements liegen. Das Kündigungsdatum kann nicht nach dem Enddatum liegen. Nach dem gewählten Kündigungsdatum finden keine Durchläufe mehr für das Abonnement statt.

|[#intable-subscription-payment-method]*Zahlungsart*
|Wähle die Zahlungsart, die für das Abonnement gelten soll. Ist im Kontaktdatensatz eine Zahlungsart dem Kontakt zugeordnet, wird diese hier vorausgewählt, lässt sich aber anpassen. +
_Dies ist ein Pflichtfeld._

|[#intable-subscription-shipping-costs]*Versandkosten*
|Das Feld für die Versandkosten ist nach dem Erstellen des Abonnements verfügbar. +
Nach dem Erstellen des Abonnements kannst du die Versandkosten bei Bedarf anpassen. Bei einer Änderung werden der Netto- und der Bruttowarenwert automatisch neu berechnet und angezeigt.

|[#intable-subscription-shipping-method]*Versandart*
|Das Feld für die Versandart ist nach dem Erstellen des Abonnements verfügbar. +
Um die <<#600, Versandart bearbeiten>> zu können, klicke nach dem Erstellen und Speichern des Abonnements auf *Versandprofilverknüpfungen neu berechnen* (terra:execute[]). Bei einer Änderung werden der Netto- und der Bruttowarenwert automatisch neu berechnet und angezeigt.

|[#intable-subscription-client]*Mandant*
|Wähle den Mandanten, für den das Abonnement gelten soll. Wenn du einen <<#intable-subscription-default-client, Standard-Mandanten>> eingestellt hast, ist dieser hier vorausgewählt. +
_Dies ist ein Pflichtfeld._

|[#intable-subscription-owner]*Eigner*
|Wenn du einen <<#intable-subscription-default-owner, Standard-Eigner>> eingestellt hast, ist dieser hier vorausgewählt. Der Eigner lässt sich durch die Auswahl in der Dropdown-Liste anpassen.

|[#intable-subscription-referrer]*Herkunft*
|Lege die Auftragsherkunft für Abonnements fest. Die Herkunft *Manuelle Eingabe* ist vorausgewählt. Es werden nur die xref:auftraege:auftragsherkunft-neu.adoc#[Herkünfte] angezeigt, die im Backend aktiv geschaltet sind. +
_Dies ist ein Pflichtfeld._

|====

Sobald alle Pflichtfelder im Bereich *Details* ausgefüllt wurden, können dem Abonnement Artikel hinzugefügt werden.

[#400]
==== Artikelliste erstellen

Zur vollständigen Anlage des Abonnements müssen Artikel hinzugefügt werden. Erst danach wird das Abonnement gespeichert und angelegt. Führe die Suche (material:search[]) aus, um die gewünschten Artikel zu finden und zum Abonnement hinzuzufügen.

[.collapseBox]
.*Suchfunktionen*
--
Es gibt mehrere Möglichkeiten, um nach Artikeln zu suchen. Du kannst einen Wert im Suchfeld eingeben und den passenden Vorschlag wählen, um danach zu filtern. Wiederhole dies, um Filter miteinander zu kombinieren. Klicke anschließend auf material:search[], um die Suche auszuführen. +
Wenn du aus der verfügbaren Filterliste wählen möchtest, klicke auf die Liste und gib einen Wert im gewünschten Filter ein. Wenn du alle benötigten Filter gesetzt hast, klicke auf *Suchen*. +
Wenn du einen gesetzten Filter löschen möchtest, entferne den Chip. In <<#table-filters-item-search-subscription>> werden die verfügbaren Filter erläutert.

Außerdem kannst du mit der Komponente *Gespeicherte Filter* (material:bookmarks[]) ausgewählte Filter im Menü speichern. Gespeicherte Filtersets können dann in dieser Komponente bei jedem Öffnen des Menüs gewählt werden, ähnlich wie Lesezeichen. Jede:r Benutzer:in kann eigene Filter festlegen.

[.instruction]
Filter speichern:

. Setze die gewünschten Filter mit den entsprechenden Werten.
. Führe die Suche aus.
. Klicke auf *Gespeicherte Filter* (material:bookmarks[]).
. Klicke auf *Aktuellen Filter speichern*. +
→ Das Fenster *Filter speichern* wird geöffnet.
. Vergib einen *Filternamen*.
. Entscheide, ob das Filterset für alle Benutzer:innen zur Verfügung stehen soll.
. Klicke auf *Speichern*.

[[table-filters-item-search-subscription]]
.Verfügbare Filter in der Artikelsuche
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Variantennummer*
|Gib eine Variantennummer ein, um nach Varianten mit dieser Nummer zu suchen.

|*Varianten-ID*
|Gib eine ID ein, um nach Varianten mit dieser ID zu suchen.

|*Artikelname*
|Gib einen Artikelnamen ein, um nach Artikeln mit diesem Namen zu suchen.

|*Artikel-ID*
|Gib eine ID ein, um nach Artikeln mit dieser ID zu suchen.

|*Barcode*
|Gib einen Barcode ein, um nach Varianten mit diesem Barcode zu suchen.

|====

--

[.instruction]
Artikel zum Warenkorb hinzufügen:

. Klicke unter *Artikelliste* auf *Hinzufügen* (material:add[]). +
→ Du wirst zu den *Auftragspositionen* weitergeleitet.
. Suche die gewünschten Artikel oder Varianten.
. Wähle den passenden Verkaufspreis aus der *Preisauswahl* Dropdown-Liste.
. Gib die Menge des Artikels ein, die dem Abonnement hinzugefügt werden soll. +
→ Bei Preis- und Mengenänderungen muss der Verkaufspreis durch klicken auf *Verkaufspreis aktualisieren* (material:refresh[]) aktualisiert werden.
. Füge die Artikel zum Warenkorb (material:add_shopping_cart[]) hinzu. +
→ Die Warenkorbtabelle wird unterhalb der Artikelliste geöffnet.
. Nimm bei Bedarf weitere <<#425, Änderungen in der Warenkorbtabelle>> vor.
. *Speichere* (material:save[]) den Warenkorb. +
→ Die Auftragspositionen werden hinzugefügt und du wirst zu den Einstellungen des Abonnements zurückgeleitet.
. *Speichere* (material:save[]) das Abonnement. +
→ Das Abonnement wird angelegt.

[TIP]
.Preisauswahl
====
In einer Dropdown-Liste werden alle für dieses Abonnement ermittelten Verkaufspreise angezeigt. Du kannst einen der angezeigten Preise wählen, um ihn als Grundlage für die weiteren Berechnungen zu verwenden. Wenn der Preis einen Rabatt enthält, wird dies hinter dem Preisnamen und dem Betrag angezeigt. Die optionalen Spalten *Kundenklassenrabatt* und *Kategorierabatt* zeigen den Prozentsatz des angewendeten Rabatts an. +
Wenn kein gültiger Verkaufspreis ermittelt werden konnte, wird *Kein gültiger Verkaufspreis* in der Dropdown-Liste angezeigt. Du kannst den Artikel dennoch in den Warenkorb legen. Im Warenkorb kannst du den Preis manuell anpassen. Das Abonnement lässt sich bei Bedarf aber auch ohne gültige Verkaufspreise anlegen.

Eine manuelle Anpassung des Preises kannst du im Warenkorb vornehmen. Weitere Informationen dazu findest du im Kapitel <<#425, Warenkorb: Preisauswahl>>.
====

[.collapseBox]
.*Tabelle Auftragspositionen individualisieren*
--

Die Tabelle zum Hinzufügen von Auftragspositionen lässt sich individuell anpassen. Du kannst wählen, welche Tabellenspalten in welcher Reihenfolge in der Tabelle angezeigt werden sollen. Standardmäßig werden beim Öffnen des Menüs folgende Tabellenspalten angezeigt:

* Artikelname
* Varianten-ID / Nr.
* Attribute
* Menge
* Preisauswahl

Die folgenden Tabellenspalten können optional hinzugefügt werden:

* Artikel-ID
* Varianten-ID
* Variantennummer
* Variantenname
* Barcode
* Kundenklassenrabatt = der für den ausgewählten Verkaufspreis angewendete Kundenklassenrabatt in Prozent
* Kategorierabatt = der für den ausgewählten Verkaufspreis angewendete Kategorierabatt in Prozent

Passe die Tabelle deinen Bedürfnissen und deinem Arbeitsablauf an. Wenn du die Tabelle angepasst hast, wird diese Auswahl gespeichert. Du kannst die Tabelle jederzeit anpassen.

[.instruction]
Tabelle individualisieren:

. Klicke auf *Spalten konfigurieren* (material:settings[]). +
→ Das Fenster *Spalten konfigurieren* wird geöffnet.
. Wähle, welche Spalten angezeigt werden sollen.
. Verschiebe (material:drag_indicator[]) die Spalten, sodass sie in der Reihenfolge angezeigt werden, in der du sie benötigst.
. Klicke auf *Bestätigen*, um deine Auswahl zu speichern.

--

[.collapseBox]
.*Tabelle Warenkorb individualisieren*
--

Die Tabelle Warenkorb lässt sich individuell anpassen. Du kannst wählen, welche Tabellenspalten dir in welcher Reihenfolge in der Tabelle angezeigt werden sollen. Standardmäßig werden dir beim Öffnen des Menüs folgende Tabellenspalten angezeigt:

* Artikelname
* Varianten-ID / Nr.
* Attribute
* Verkaufspreis
* Menge
* Aufpreis gesamt = die Summe der Aufpreise für Bestelleigenschaften
* Gesamtsumme = der Artikelpreis zuzüglich Aufpreise für Bestelleigenschaften

Die folgenden Tabellenspalten können ausgewählt werden, werden aber standardmäßig nicht angezeigt:

* Artikel-ID
* Varianten-ID
* Variantennummer
* Variantenname
* Barcode

Passe die Tabelle deinen Bedürfnissen und deinem Arbeitsablauf an. Wenn du die Tabelle angepasst hast, wird diese Auswahl gespeichert. Du kannst die Tabelle jederzeit anpassen.

[.instruction]
Tabelle individualisieren:

. Klicke auf *Spalten konfigurieren* (material:settings[]). +
→ Das Fenster *Spalten konfigurieren* wird geöffnet.
. Wähle, welche Spalten angezeigt werden sollen.
. Verschiebe (material:drag_indicator[]) die Spalten, sodass sie in der Reihenfolge angezeigt werden, in der du sie benötigst.
. Klicke auf *Bestätigen*, um deine Auswahl zu speichern.

--

[#425]
==== Warenkorb: Preisauswahl

Beim Hinzufügen eines Artikel wurden dir in der Dropdown-Liste der Spalte *Preisauswahl* alle für dieses Abonnement ermittelten Verkaufspreise angezeigt. Der dort gewählte Preis wird dann als Grundlage für die weiteren Berechnungen verwendet.

Im Warenkorb kannst du ebenfalls eine Anpassung des Preises vornehmen. Wähle dafür einen Preis aus der Dropdown-Liste der Spalte *Preisauswahl*. Du kannst im Warenkorb auch manuell einen anderen Preis eingeben. Dieser wird in der Auswahl dann als *Manueller Preis* angezeigt. +
Wenn du einen anderen Verkaufspreis als den ersten ermittelten wählst oder Mengen änderst, muss der Verkaufspreis aktualisiert werden. Klicke dafür auf *Verkaufspreis aktualisieren* (material:refresh[]). Du kannst jeden Artikel einzeln aktualisieren oder mit der Schaltfläche oberhalb der Warenkorbtabelle alle Auftragspositionen auf einmal aktualisieren. Nach dem Aktualisieren ist die Schaltfläche zum Speichern (material:save[]) wieder verfügbar.

Folgendes gilt für die Verkaufspreise:

* Wenn du manuell einen Preis eingibst, bleibt dieser in der Dropdown-Liste als Auswahl für diesen Auftrag erhalten, auch wenn du zwischendurch einen anderen Preis auswählst.
* Wenn kein gültiger Verkaufspreis ermittelt werden konnte, kannst du einen manuellen Preis im Warenkorb eingeben. Es ist möglich, das Abonnement ohne gültigen Preis anzulegen.
* Es ist zulässig, den Preis 0,00 einzugeben.

[#450]
==== Warenkorb: Eigenschaften an Auftragspositionen

Vom Warenkorb aus kannst du die Eigenschaften der Auftragspositionen eines Abonnements (Bestelleigenschaften) bearbeiten. Die hier vorgenommenen Änderungen gelten nur für die Auftragspositionen dieses Abonnements. Die im System angelegten Eigenschaften werden nicht überschrieben. Es stehen dir hier nur Eigenschaften zur Verfügung, die du bereits im System angelegt hast. +
Wenn du Eigenschaften erstellen und bearbeiten möchtest oder du noch nicht mit der Struktur von Eigenschaften vertraut bist, informiere dich auf der Handbuchseite xref:artikel:eigenschaften.adoc#500[Eigenschaften].

Damit eine Eigenschaft an einer Auftragsposition gesetzt werden kann, muss sie in den Eigenschaftseinstellungen im Bereich *Optionen* als *Bestelleigenschaft* definiert werden. Lege unter xref:artikel:eigenschaften.adoc#property-options[Optionen] außerdem mögliche Aufpreise und Besteuerungen fest. Die hier gespeicherten Werte werden in die Berechnungen einbezogen.

Wenn bereits eine Eigenschaft mit einer Auftragsposition verknüpft ist, wird diese in einer zweiten Tabellenzeile direkt unterhalb der dazugehörigen Auftragsposition angezeigt. Durch Klicken auf material:expand_more[] wird die zweite Tabellenzeile angezeigt. Hier findest du Angaben zu *Name*, *Wert* und *Aufpreis* der Eigenschaft. Außerdem kannst du die Eigenschaften der Auftragspositionen *löschen* (material:delete[]). Gelöschte Eigenschaften werden dann für dieses Abonnement nicht mehr berücksichtigt. +
Um die Eigenschaften zu bearbeiten oder weitere bereits bestehende Eigenschaften zu einer Auftragsposition hinzuzufügen, klicke auf *Eigenschaften bearbeiten* (material:edit[]). Das Bearbeitungsfenster *Eigenschaften von [ausgewählte Auftragsposition mit ID] bearbeiten* wird geöffnet und du kannst weitere Anpassungen vornehmen.
Folgende Angaben zu Eigenschaften einer Auftragsposition werden hier angezeigt:

* *Name* = Zeigt den Namen der Eigenschaft an. Ein rotes Sternchen am Namen der Eigenschaft kennzeichnet, dass es eine *verpflichtende* Eigenschaft ist. Ob eine Eigenschaft *verpflichtend* ist, bestimmst du in den Einstellungen der Eigenschaften im Bereich xref:artikel:eigenschaften.adoc#property-options[Optionen]. Wähle dazu in der Dropdown-Liste *Bestelloptionen* die Einstellung *Verpflichtend*.
* *Wert* = Zeigt den Wert der Eigenschaft an. Du kannst den Wert anpassen. Je nach Eigenschaftstyp kannst du eine Auswahl treffen, den Wert ändern, einen Wert eingeben oder eine Datei hochladen. Die Änderungen gelten nur für dieses Abonnement.
* *Aufpreis* = Zeigt den Aufpreis der Eigenschaft an, sofern ein Aufpreis zugeordnet wurde. Der Aufpreis kann bearbeitet werden. Die Änderungen gelten nur für dieses Abonnement.

Außerdem hast du in diesem Fenster einige weitere Bearbeitungsmöglichkeiten. Durch Klicken auf *Löschen* (material:delete[]) entfernst du eine Eigenschaft von einer Auftragsposition. Diese Eigenschaft wird dann für dieses Abonnement nicht mehr berücksichtigt. +
Du kannst weitere bereits angelegte Eigenschaften hinzufügen. Wähle eine Eigenschaft aus der Dropdown-Liste des Feldes *Eigenschaft wählen* und füge sie durch Klicken auf *Eigenschaft hinzufügen* (material:add[]) zu dieser Auftragsposition hinzu. +
Wenn du alle erforderlichen Anpassungen vorgenommen hast, klicke auf *Eigenschaften speichern*. Das Bearbeitungsfenster wird geschlossen und du kannst bei Bedarf die Eigenschaften weiterer Auftragspositionen auf die gleiche Weise bearbeiten.

Wenn du die Eigenschaften auf Dokumenten ausgeben lassen möchtest, musst du dies in der Konfiguration der Eigenschaften einstellen. Stelle sicher, dass im Bereich xref:artikel:eigenschaften.adoc#property-visibilities[Sichtbarkeiten] die beiden folgenden Einstellungen gewählt sind:

* in der Dropdown-Liste *Überall anzeigen* die Option *Anzeige auf PDF-Dokumenten*
* in der Dropdown-Liste *Mandant* der richtige Mandant

Wo die Eigenschaften auf dem Dokument ausgegeben werden, hängt von der jeweiligen Eigenschaft und ihrer Konfiguration ab. Eigenschaften, denen in der Konfiguration im Bereich *Optionen* kein Steuersatz zugewiesen wurde oder für die aus der Dropdown-Liste *Bestelleigenschaft* die Option *zusätzliche Kosten anzeigen* gewählt wurde, werden unterhalb der Summen angezeigt. Andere Eigenschaften werden in der Artikelpositionstabelle angezeigt.

Speichere (material:save[]) den Warenkorb, wenn du mit dem Bearbeiten der Auftragseigenschaften und des Warenkorbs fertig bist. Nach dem Speichern wirst du zur Detailansicht des Abonnements zurückgeleitet.

[#500]
==== Artikelliste nachträglich bearbeiten

Auch nach Anlegen des Abonnements kannst du die Artikelliste bearbeiten und anpassen. Dies geht solange, bis ein Durchlauf einen ersten Auftrag generiert hat. Danach ist das Abonnement gesperrt und kann nur noch eingeschränkt bearbeitet werden. Es ist möglich, das Abonnement zu <<#850, entsperren>>. Danach kann auch die Artikelliste wieder bearbeitet werden.

[.collapseBox]
.*Tabelle Artikelliste individualisieren*
--

Die Tabelle Artikelliste lässt sich individuell anpassen. Du kannst wählen, welche Tabellenspalten in welcher Reihenfolge in der Tabelle angezeigt werden sollen. Standardmäßig werden beim Öffnen des Menüs folgende Tabellenspalten angezeigt:

* Artikelname
* Varianten-ID / Nr.
* Attribute
* Preis
* Menge

Die folgenden Tabellenspalten können optional hinzugefügt werden:

* Artikel-ID
* Varianten-ID
* Variantennummer
* Variantenname

Passe die Tabelle deinen Bedürfnissen und deinem Arbeitsablauf an. Wenn du die Tabelle angepasst hast, wird diese Auswahl gespeichert. Du kannst die Tabelle jederzeit anpassen.

[.instruction]
Tabelle individualisieren:

. Klicke auf *Spalten konfigurieren* (material:settings[]). +
→ Das Fenster *Spalten konfigurieren* wird geöffnet.
. Wähle, welche Spalten angezeigt werden sollen.
. Verschiebe (material:drag_indicator[]) die Spalten, sodass sie in der Reihenfolge angezeigt werden, in der du sie benötigst.
. Klicke auf *Bestätigen*, um deine Auswahl zu speichern.

--

Durch Klicken auf *Hinzufügen* (material:add[]) in der *Artikelliste* eines Abonnements wirst du direkt zur Artikelsuche weitergeleitet und kannst wie im Kapitel <<#400, Artikelliste erstellen>> beschrieben Artikel hinzufügen. Auch die unten aufgeführten Bearbeitungsmöglichkeiten stehen dir hier offen.

Oder klicke in der *Artikelliste* eines Abonnements auf *Bearbeiten* (material:edit[]), um direkt zum bestehenden *Warenkorb* für das ausgewählte Abonnement zu gelangen. Folgende Bearbeitungsmöglichkeiten stehen dir dort zur Verfügung:

[[table-editing-order-items-subscription]]
.Bearbeitungsmöglichkeiten der Artikelliste
[cols="1,3"]
|====
|Einstellung|Erläuterung

|[#intable-subscription-adding-items]*Artikel hinzufügen*
|Füge weitere Artikel zum Warenkorb des Abonnements hinzu (material:add_shopping_cart[]). Gehe dabei wie im Kapitel <<#400, Artikelliste erstellen>> beschrieben vor.

|[#intable-subscription-delete-items]*Artikel löschen*
|Entferne Artikel aus dem Warenkorb des Abonnements über *Artikel löschen* (material:delete[]).

|[#intable-subscription-change-items]*Mengen anpassen*
|Ändere die Menge eines Artikels im Warenkorb des Abonnements durch Klicken in die Zeile des Artikels im Warenkorb. +
*_Hinweis:_* Eine Änderung an Mengen erfordert eine Aktualisierung der Preise, bevor der Warenkorb gespeichert werden kann. Klicke dafür auf *Verkaufspreis aktualisieren* (material:refresh[]).

|[#intable-subscription-change-prices]*Preise anpassen*
|Passe den Preis eines Artikels im Warenkorb des Abonnements an. Beachte, dass die Preisänderung nur für das ausgewählte Abonnement gilt. +
*_Hinweis:_* Eine Änderung an Preisen erfordert eine Aktualisierung, bevor der Warenkorb gespeichert werden kann. Klicke dafür auf *Verkaufspreis aktualisieren* (material:refresh[]).

|====

*Speichere* (material:save[]) den Warenkorb, nachdem du die gewünschten Änderungen vorgenommen hast. Anschließend wirst du zu den Einstellungen des Abonnements zurückgeleitet.
Der *Bruttowarenwert* und der *Nettowarenwert* werden automatisch neu berechnet und angezeigt. +

In der Detailansicht des Abonnements kannst du außerdem den *Artikelnamen* ändern. Auch diese Änderung gilt nur für das ausgewählte Abonnement.

[TIP]
.Änderungen an Artikeln nur für gewähltes Abonnement
====
Änderungen an Artikeln in der Ansicht des Abonnements gelten nur für das ausgewählte Abonnement. Für dauerhafte Änderungen an Artikeln müssen die Anpassungen im Menü *Artikel » Artikel (Testphase)* oder *Einrichtung » Artikel* vorgenommen werden.
//ToDo - sobald die neue Artikel-UI standard ist, dann diesen Satz einblenden und dafür den alten Pfad löschen
//Für dauerhafte Änderungen an Artikeln müssen die Anpassungen unter *Artikel » Artikel* oder *Einrichtung » Artikel* vorgenommen werden.
Das Bearbeiten von Artikeln ist im Handbuch auf der Seite xref:artikel:artikel.adoc#[Artikel] beschrieben.
====

[#600]
==== Versandart und Versandkosten ändern

Sowohl der *Nettowarenwert* als auch der *Bruttowarenwert* wurden nach dem Anlegen der Artikelliste und Speichern des Abonnements automatisch berechnet. Nach dem Speichern des Abonnements kannst du die Versandart und die Versandkosten bearbeiten.

[.instruction]
Versandprofilverknüpfungen neu berechnen:

. Klicke auf *Versandprofilverknüpfungen neu berechnen* (terra:execute[]). +
→ Während der Neuberechnung sind die Bearbeitungsmöglichkeiten kurzzeitig gesperrt.
. Wähle die gewünschte *Versandart*. Es stehen dir die xref:fulfillment:versand-vorbereiten.adoc#[Versandarten] zur Verfügung, die du in deinem plentymarkets System gespeichert hast. +
→ Die *Versandkosten* werden automatisch eingefügt.
. Passe die *Versandkosten* bei Bedarf manuell an. +
. *Speichere* (material:save[]) das Abonnement. +
→ Der Nettowarenwert und der Bruttowarenwert werden automatisch neu berechnet.

[#610]
=== Abonnements über Angebotsaufträge anlegen

Als erstes stellst du sicher, dass du deine gewünschten Grundeinstellungen für Abonnements im Menü *Einrichtung » Auftrag » Auftragsarten » Abonnement* vorgenommen hast.
Dann, um ein Abonnement aus einem Angebotsauftrag zu erstellen, muss das Auftragsangebot bereits im System vorhanden sein.

[.instruction]
Abonnement anlegen:

. Öffne das Menü *Aufträge » Aufträge*.
. Führe die Suche aus, um Aufträge anzuzeigen.
. Öffne den Angebotauftrag, zu dem du eine Abonnement anlegen möchtest.
. Klicke oben auf *Aufträge erstellen (material:shopping_cart[]) » Abonnement*.
. Wähle eine Option. Für alle Auftragspositionen oder Für bestimmte Auftragspositionen
. Wählst du die Option Für alle Auftragspositionen. Beachte dazu die Erläuterungen in Tabelle 1. 
. Wählst du die Option Für bestimmte Auftragspositionen,Beachte dazu die Erläuterungen in Tabelle 2.
. Speichere (icon:save[role="green"]) die Einstellungen. +
→ Das Abonnement wird angelegt.


.Tabelle 1. Alle Auftragspositionen 
[cols="1,3"]
|====
|Einstellung|Erläuterung

|[#intable-subscription-status]*Status*
|Status des Abonnements

| *Eigner*
|Der Eigner des Abonnements

| *Beginn des Abonnements*
|Das Anfangsdatum des Abonnements

| *Abo-Intervall*
|Das Intervall des Abonnements


.Tabelle 2. Bestimmte Auftragspositionen 
[cols="1,3"]
|====
|Einstellung|Erläuterung

|[#intable-subscription-status]*Status*
|Der Status des Abonnements.

| *Eigner*
|Der Eigner des Abonnements.

| *Beginn des Abonnements*
|Das Anfangsdatum des Abonnements.

| *Abo-Intervall*
|Das Intervall des Abonnements

| *Warenkorb*
|Die Artikel, die du aus dem Einkaufswagen auswählen kannst

[#700]
== Weitere Funktionen in der Detailansicht

In der Detailansicht eines ausgewählten Abonnements stehen dir neben den oben beschriebenen außerdem die Funktionen <<#800, Abgeschlossene Aufträge>>, <<#900, Messenger>> und die <<#1000, Auftragshistorie>> zur Verfügung. Diese kannst du wahlweise über die Navigation links oder in der Detailansicht ansteuern. Die Anordnung der Elemente in der Detailansicht kannst du anhand der <<#subscription-myview, MyView>> selbst bestimmen.

Außerdem liefern Infoboxen in der Detailansicht jedes Abonnements grundlegende Informationen:

* Nettowarenwert: Der Nettowarenwert der bestellten Artikel wird angezeigt. Grau bedeutet, dass der Wert bei Null liegt. Grün bedeutet, dass der Wert über Null liegt.
* Bruttowarenwert: Der Bruttowarenwert der bestellten Artikel wird angezeigt. Grau bedeutet, dass der Wert bei Null liegt. Grün bedeutet, dass der Wert über Null liegt.
* Letzter Durchlauf: Das Datum des letzten Durchlaufs des Abonnements wird angezeigt. Wenn kein Datum in der Infobox zu sehen ist, wurde noch kein Durchlauf ausgeführt.

[#800]
=== Abgeschlossene Aufträge: Durchläufe

In diesem Bereich werden die bereits abgeschlossenen Aufträge des Abonnements angezeigt. Diese können durch automatische oder manuelle Durchläufe entstanden sein. +
Ein *automatischer Durchlauf* erfolgt in den Zeitabständen, die du im Intervall für das Abonnement ausgewählt hast. Wenn das Ende des Abonnements erreicht ist oder das Abonnement gekündigt wurde, finden keine automatischen Durchläufe mehr statt.

Zusätzlich zu den automatischen Durchläufen hast du die Möglichkeit, einen *manuellen Durchlauf* (material:subscriptions[]) anzustoßen. Beachte, dass ein manueller Durchlauf immer _sofort_ ausgeführt wird. Gehe für das Anstoßen eines manuellen Durchlaufs wie folgt vor.

[.instruction]
Manuellen Durchlauf anstoßen:

. Öffne das Menü *Aufträge » Abonnement*.
. Klicke in die Zeile eines Abonnements. +
→ Die Detailansicht des Abonnements wird geöffnet.
. Gehe in den Bereich *Abgeschlossene Aufträge*.
. Klicke auf *Manuellen Durchlauf starten* (material:subscriptions[]).
. Wähle in der Abfrage, ob du den nächsten automatischen Durchlauf des Abonnements überspringen möchtest oder nicht. +
→ Der nächste automatische Durchlauf hängt vom gewählten Intervall ab. +
→ Der manuelle Durchlauf wird durchgeführt. +
→ Der Auftrag erhält eine *Auftrags-ID* und ist sowohl im Bereich *Abgeschlossene Aufträge* als auch in der *Auftragsübersicht* zu sehen.

Im Bereich *Abgeschlossene Aufträge* wird nicht nur die ID angezeigt, du erhältst auch Informationen zum Auftrag, z.B. wann der Auftrag erstellt wurde oder welche Zahlungsart ausgewählt ist.
Außerdem hast du die Möglichkeit, einzelne Aufträge eines Abonnements zu löschen (material:remove_circle[]). Durch das Löschen des Auftrags wird der Auftrag gleichzeitig auch aus der Auftragsübersicht unter *Aufträge » Aufträge (Testphase)* entfernt. Beachte, dass Aufträge _nicht_ gelöscht werden können, wenn bereits steuerrelevante Dokumente, wie z.B. eine Rechnung, erzeugt wurden.

[WARNING]
.Überspringen eines automatischen Durchlaufs
====
Wenn du beim Durchführen eines manuellen Durchlaufs die Option *Nächsten automatischen Durchlauf überspringen* gewählt hast, wird der nächste automatische Durchlauf auch dann übersprungen, wenn du den Auftrag aus dem manuellen Durchlauf löschst.
====

[.collapseBox]
.*Tabelle Abgeschlossene Aufträge individualisieren*
--

Du kannst die Tabelle *Abgeschlossene Aufträge* individuell anpassen und wählen, welche Tabellenspalten in welcher Reihenfolge in der Tabelle angezeigt werden sollen. Passe die Tabelle somit deinen Bedürfnissen und deinem Arbeitsablauf an. Wenn du die Tabelle angepasst hast, wird diese Auswahl gespeichert. Du kannst die Tabelle jederzeit anpassen.

[.instruction]
Tabelle individualisieren:

. Klicke auf *Spalten konfigurieren* (material:settings[]). +
→ Das Fenster *Spalten konfigurieren* wird geöffnet.
. Wähle, welche Spalten angezeigt werden sollen.
. Verschiebe (material:drag_indicator[]) die Spalten, sodass sie in der Reihenfolge angezeigt werden, in der du sie benötigst.
. Klicke auf *Bestätigen*, um deine Auswahl zu speichern.

--

[#850]
[.discrete]
==== Sperren und Entsperren von Abonnements

Nach dem Generieren des ersten Auftrags wird das Abonnement gesperrt und die Bearbeitungsmöglichkeiten in der Detailansicht stehen nur noch sehr eingeschränkt zur Verfügung. Das End- und Kündigungsdatum des Abonnements kann weiterhin bearbeitet werden. Wenn der Auftrag gelöscht wird, wird auch das Abonnement wieder freigeschaltet. Beachte allerdings, dass Aufträge _nicht_ gelöscht werden können, sobald steuerrelevante Dokumente für diesen Auftrag existieren.

Außerdem gibt es die Möglichkeit, durch Klick auf *Abonnement entsperren* (material:lock[]) das Abonnement zu entsperren, sodass alle Bearbeitungsmöglichkeiten wieder zur Verfügung stehen. Die <<#1000, Auftragshistorie>> dokumentiert, welche Benutzer:in diese Aktion wann ausgeführt hat. Durch einen Klick auf *Abonnement sperren* (material:lock_open[]) wird das Abonnement wieder gesperrt. Wenn dieser Schritt nicht ausgeführt wird, wird das Abonnement automatisch nach dem nächsten Durchlauf wieder gesperrt. Es wird allerdings empfohlen, das Abonnement nach dem Bearbeiten wieder zu sperren, da auch diese Aktion als Eintrag in der Auftragshistorie hinzugefügt wird. So wird die Transparenz und Nachvollziehbarkeit der Bearbeitung eines Abonnements sichergestellt.

[#900]
=== Messenger nutzen

Nutze den Messenger, um im Backend Nachrichten zu erstellen, die deinen Kontakten zugeordnet werden. Diese Nachrichten funktionieren wie Notizen und sind nur in deinem plentymarkets Backend sichtbar und können nicht von deinen Kontakten aufgerufen werden.

[.instruction]
So erstellst du eine neue Nachricht:

. Öffne das Menü *Aufträge » Abonnement*.
. Öffne das Abonnement.
. Klicke auf der linken Seite auf *Messenger*.
. Klicke auf *Neue Nachricht* (material:add[]). +
→ Ein Textfeld wird geöffnet.
. Wähle einen oder mehrere Empfänger:innen. +
*_Hinweis:_* Die ID des Abonnements ist bereits vorausgefüllt.
. Gib einen Betreff ein.
. Gib den Text ins Textfeld ein. +
→ Mit einem Doppelklick auf das Wort stehen dir Formatierungsmöglichkeiten für deine Nachricht zur Verfügung.
. Füge optional mit einem Klick auf material:attach_file[] *Anhänge hinzufügen* eine Datei an.
. Klicke auf material:visibility_off[] *FLÜSTERN*, um die Nachricht zu senden.

Die Nachricht kannst du entweder in der Detailansicht des Abonnements unter *Messenger* öffnen oder in dem Kontakt, zu dem du die Nachricht erstellt hast. Gehe dazu in die Kontaktansicht. Eine ausführliche Anleitung findest du auf der Handbuchseite xref:crm:messenger-testphase.adoc#[Messenger (Testphase)].

[#1000]
=== Auftragshistorie

Die Auftragshistorie bietet dir eine Übersicht über die ausgeführten Aktionen in einem angelegten Abonnement. Aufgeführt werden nach Datum sortiert z.B. Aktualisierungen von Aufträgen oder das Entsperren und Sperren von Abonnements. In der Tabelle siehst du, wann die Aktion durchgeführt wurde, von welcher Benutzer:in, um welche Aktion es sich handelt und in welchem Status des Abonnements die Aktion ausgeführt wurde.

[#1100]
== Übersicht der Abonnements

In die Übersicht der angelegten Abonnements gelangst du über *Aufträge » Abonnement*. Hier werden alle angelegten Abonnements aufsteigend nach ihrer Auftrags-ID aufgeführt. Darüber hinaus werden für jedes Abonnement die folgenden Informationen angezeigt:

* Auftrags-ID
* Kontakt
* Abo-Intervall
* Zahlungsart
* Status
* Start des Abonnements
* Ende des Abonnements
* Gekündigt
* Letzter Durchlauf

Wenn du den Status eines Abonnements ändern möchtest, kannst du dies direkt in der Übersicht vornehmen. Wähle dafür im Feld *Status* den gewünschten Status aus der Dropdown-Liste. +
Für weiterführende Änderungen an einem der in der Übersicht aufgelisteten Abonnements, klicke in die jeweilige Zeile des Abonnements. Die Detailansicht des Abonnements wird geöffnet und du kannst Änderungen vornehmen. +
Solange noch kein Auftrag generiert wurde, stehen alle Bearbeitungsmöglichkeiten zur Verfügung. Wenn schon ein Auftrag vorhanden ist, sind die Bearbeitungsmöglichkeiten eingeschränkt. Es bleibt jedoch weiterhin möglich, z.B. das End- und das Kündigungsdatum des Abonnements anzupassen. Auch einen manuellen Durchlauf kannst du jederzeit starten.

[.collapseBox]
.*Übersichtsabelle individualisieren*
--

Die Übersichtstabelle lässt sich individuell anpassen. Du kannst wählen, welche Tabellenspalten in welcher Reihenfolge in der Tabelle angezeigt werden sollen. Passe die Tabelle damit deinen Bedürfnissen und deinem Arbeitsablauf an. Wenn du die Tabelle angepasst hast, wird diese Auswahl gespeichert. Du kannst die Tabelle jederzeit anpassen.

[.instruction]
Tabelle individualisieren:

. Klicke auf *Spalten konfigurieren* (material:settings[]). +
→ Das Fenster *Spalten konfigurieren* wird geöffnet.
. Wähle, welche Spalten angezeigt werden sollen.
. Verschiebe (material:drag_indicator[]) die Spalten, sodass sie in der Reihenfolge angezeigt werden, in der du sie benötigst.
. Klicke auf *Bestätigen*, um deine Auswahl zu speichern.

--

[#1200]
=== Abonnements suchen

Du möchtest das Abonnement einer Kund:in anpassen oder alle Abonnements überprüfen, die noch keinen initialen Durchlauf hatten? Dann führe eine Suche in der Abonnements-Übersicht im Menü *Aufträge » Abonnement* aus.

Es gibt mehrere Möglichkeiten, die Suche zu nutzen. Du kannst einen Wert im Suchfeld eingeben und dann den passenden Vorschlag wählen. Bei Eingabe einer Zahl oder eines Buchstabens werden dir mögliche Filter vorgeschlagen, wie z.B. die Auftrags-IDs oder die Variantennummer. Wiederhole dies, um Filter miteinander zu kombinieren. Klicke auf *Suchen* (material:search[]), um die Suche auszuführen. +
Wenn du erst einen Filter aus der Filterliste wählen möchtest, klicke auf *Filter* (material:tune[]). Die verfügbaren Filter werden angezeigt. Gib einen Wert im gewünschten Filter ein. Wenn du alle benötigten Filter gesetzt hast, klicke auf *Suchen*. +
Wenn du einen gesetzten Filter löschen möchtest, entferne den Chip. In <<#table-search-subscriptions>> werden die verfügbaren Filter erläutert.

Außerdem kannst du mit der Komponente *Gespeicherte Filter* (material:bookmarks[]) ausgewählte Filter in der UI speichern. Gespeicherte Filtersets können dann in dieser Komponente bei jedem Öffnen des Menüs gewählt werden, ähnlich wie Lesezeichen. Jede:r Benutzer:in kann eigene Filter festlegen.

[.instruction]
Filter speichern:

. Setze die gewünschten Filter mit den entsprechenden Werten.
. Führe die Suche aus.
. Klicke auf *Gespeicherte Filter* (material:bookmarks[]).
. Klicke auf *Aktuellen Filter speichern* (material:bookmark_border[]). +
→ Das Fenster *Filter speichern* wird geöffnet.
. Vergib einen *Filternamen*.
. Entscheide, ob das Filterset als Standard-Filterset genutzt werden soll.
. Entscheide, ob das Filterset für alle Benutzer:innen zur Verfügung stehen soll.
. Klicke auf *Speichern*.

[[table-search-subscriptions]]
.Abonnements suchen
[cols="1,3"]
|====
|Einstellung|Erläuterung

|[#intable-subscription-search-order-id]*Auftrags-ID*
|Gib eine ID ein, um nach dem Abonnement mit dieser ID zu suchen. Du kannst mehrere IDs kommasepariert eingeben.

|[#intable-subscription-search-interval]*Intervall*
|Durch Wahl eines der Intervalle werden dir alle Abonnements mit diesem Intervall angezeigt.

|[#intable-subscription-search-no-initial-run]*Noch kein initialer Durchlauf*
|Aktiviere diese Option, wenn du nach Abonnements suchen möchtest, für die noch kein Durchlauf, weder manuell noch automatisch, stattgefunden hat. Wenn du diese Option auswählst, wird die Datumsauswahl gesperrt, weil für diesen Suchfilter keine zeitliche Eingrenzung notwendig und somit keine Kombinationsmöglichkeit gegeben ist.

|[#intable-subscription-search-date]*Datumstyp*
|Wähle zwischen Startdatum, Enddatum, Kündigungsdatum oder Datum des letzten Durchlaufs. In Kombination mit *Auftragsdatum von* und *Auftragsdatum bis* werden dir die Abonnements angezeigt, deren Start-, End- oder Kündigungsdatum im ausgewählten Zeitraum liegt (icon:calendar[]).

|[#intable-subscription-search-date-from]*Datum von*
|Definiere in Kombination mit *Auftragsdatum bis* einen Zeitraum und wähle einen Datumstyp, nach dem gesucht werden soll. Es werden die Abonnements angezeigt, deren Start-, End- oder Kündigungsdatum in diesem Zeitraum liegt (icon:calendar[]).

|[#intable-subscription-search-date-to]*Datum bis*
|Definiere in Kombination mit *Auftragsdatum von* einen Zeitraum und wähle einen Datumstyp, nach dem gesucht werden soll. Es werden dir Abonnements angezeigt, deren Start-, End- oder Kündigungsdatum in diesem Zeitraum liegt (icon:calendar[]).

|[#intable-subscription-search-client]*Mandant*
|Wähle den Mandanten, um nur Abonnements dieses Mandaten anzuzeigen.

|[#intable-subscription-search-contact]*Kontakt-ID*
|Suche Abonnements von bestimmten Kund:innen über die Kontakt-IDs. Du kannst mehrere IDs kommasepariert eingeben.

|[#intable-subscription-search-owner]*Eigner*
|Wähle einen Eigner, um nach Abonnements dieses Eigners zu suchen.

|[#intable-subscription-search-status-from]*Status von*
|Wähle in Kombination mit *Status bis* einen Statusbereich. Es werden die Abonnements angezeigt, die in diesem Bereich liegen.

|[#intable-subscription-search-status-to]*Status bis*
|Wähle in Kombination mit *Status von* einen Statusbereich. Es werden die Abonnements angezeigt, die in diesem Bereich liegen.

|[#intable-subscription-search-payment-method]*Zahlungsart*
|Wähle eine Zahlungsart. Es werden dir alle Abonnements angezeigt, für die diese Zahlungsart gewählt ist.

|[#intable-subscription-search-reset]*Zurücksetzen*
|Setzt alle eingestellten Filter zurück.

|[#intable-subscription-search]*Suche*
|Führt die Suche aus.

|====

[#1300]
=== Gruppenfunktion: Manueller Durchlauf

In der Übersicht steht dir auch die Gruppenfunktion *Manuellen Durchlauf starten* (material:subscriptions[]) zur Verfügung. Sobald du mindestens ein Abonnement gewählt hast, wird die Gruppenfunktion oberhalb der Tabelle angezeigt. Mit dieser Funktion kannst du für bis zu 20 gewählte Abonnements auf einmal einen manuellen Durchlauf anstoßen. Wie auch beim Anstoßen eines einzelnen manuellen Durchlaufs in der Detailansicht eines Abonnements, wird der manuelle Durchlauf der Gruppenfunktion _sofort_ ausgeführt. Um die Gruppenfunktion zu nutzen, gehe vor wie folgt.

[.instruction]
Gruppenfunktion nutzen:

. Öffne das Menü *Aufträge » Abonnement*.
. Suche nach den Abonnements, für die du einen manuellen Durchlauf anstoßen möchtest.
. Wähle (material:check_box[role=skyBlue]) die entsprechenden Abonnements.
. Klicke auf *Manuellen Durchlauf starten* (material:subscriptions[]). +
→ Ein manueller Durchlauf wird für die gewählten Abonnements ausgeführt. Wenn für eines oder mehrere Abonnements kein manueller Durchlauf ausgeführt werden konnte, z.B. weil das Abonnement schon beendet ist, wird dies in einer Fehlermeldung angezeigt.

[#1400]
=== Abonnements in der Auftragsübersicht

In der Auftragsübersicht im Menü *Aufträge » Aufträge (Testphase)* werden die durch die Abonnements generierten Aufträge aufgelistet. +
In der Zeile des Auftrags wird angezeigt, zu welchem Abonnement ein Auftrag gehört. Wenn du auf die ID des Abonnements klickst, wirst du zur Detailansicht des Abonnements geleitet. Du kannst das ausgewählte Abonnement in der Detailansicht bearbeiten.

Wie andere Aufträge auch, verwaltest du die Aufträge eines Abonnements in der Auftragsübersicht.
