= Angebote
:page-aliases: angebot-erzeugen.adoc
:keywords: Angebot, Angebote, Angebot erzeugen, Auftragsdokumente, Dokumentenvorlage, Dokumententyp, Dokument, Angebotsdokument, Dokumentvorlage, Dokumenttyp
:author: team-docs-automation
:description: Erfahre, wie du deine Kund:innen mithilfe des Dokuments Angebot über Angebote informierst. Sobald du eine Dokumentenvorlage eingerichtet hast, kannst du Angebote als PDF generieren und per E-Mail-Anhang versenden.

Du kannst Kund:innen individuell Angebote erstellen und ihnen zukommen lassen. Dafür gibt es das Dokument Angebot, das du als PDF-Datei generieren kannst, um es z.B. zu drucken oder deinen Kund:innen als E-Mail-Anhang zukommen zu lassen.

[#100]
== Dokumentenvorlage für Angebote einrichten

Bevor du das Dokument Angebot generieren kannst, muss eine Dokumentenvorlage eingerichtet werden. Dies geschieht im Menü *Einrichtung » Mandant » [Mandant wählen] » Standorte » [Standort wählen] » Dokumente » Angebot*. +
Weitere Informationen und Anleitungen zur Einrichtung der Dokumentenvorlage findest du auf der Handbuchseite xref:auftraege:auftragsdokumente-neu.adoc#[Auftragsdokumente].

[#200]
== Einzelnes Dokument Angebot erzeugen

Angebote erstellst du individuell für Kund:innen, daher sind auch die dazugehörigen Dokumente direkt mit diesem Auftrag vom Typ *Angebot* verknüpft. Das bedeutet, dass das Dokument nur für den Auftragstyp Angebot erstellt werden kann. Möchtest du also z.B. ein PDF-Dokument *Angebot* verschicken, lege zunächst das Angebot als Auftragstyp an. Das dazugehörige Dokument erstellst du manuell wie im Folgenden beschrieben.

[.instruction]
Dokument Angebot manuell erzeugen:

. Öffne das Menü *Aufträge » Aufträge*. +
→ Die Auftragsübersicht wird geöffnet.
. Führe die Suche (material:search[]) aus, um Aufträge anzuzeigen.
. Öffne den Auftrag vom Typ Angebot, für den ein Angebot erzeugt werden soll. Beachte, dass Aufträge nur in der Listenansicht geöffnet werden können.
. Gehe in den Bereich *Dokumente*.
. Klicke oben links auf *Dokument erstellen* (material:add[]).
. Wähle das Dokument *Angebot* aus der Dropdown-Liste. +
→ Das Fenster *Dokument erzeugen: Angebot* wird geöffnet.
. Gib ein Datum ein, das auf dem Angebot angezeigt werden soll.
. Gib optional einen Kommentar ein, der auf dem Angebot angezeigt werden soll.
. Klicke auf *Erstellen* (material:add[role="green"]). +
→ Das Angebot wird erstellt und im Bereich *Dokumente* hinzugefügt.

[#300]
== Versand von Angebotsdokumenten automatisieren

Du hast Kund:innen individuelle Angebote erstellt, die dazugehörigen Dokumente erzeugt und möchtest diese nun an die Kund:innen senden? Diesen Arbeitsschritt kannst du automatisieren, indem du die passende Ereignisaktion einrichtest. Zum Versenden des Dokuments Angebot als E-Mail Anhang empfehlen wir dir die in <<table-event-procedure-sending-offer-document>> beschriebene Ereignisaktion. Gehe wie im Folgenden beschrieben vor, um die Ereignisaktion einzurichten.

:table-event-procedure: <<table-event-procedure-sending-offer-document>>
include:_includes:partial$event-procedure.adoc[]

[[table-event-procedure-sending-offer-document]]
.Ereignisaktion "Angebot als PDF versenden" einrichten
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

| *Ereignis*
| *Dokumente > Angebot generiert*
|

| *Filter*
| *Auftrag > Auftragstyp*
| *Angebot*

| *Aktion*
| *Kunde > E-Mail versenden*
|Wähle über *Hinzufügen* (icon:plus-square[role="green"]) die entsprechende E-Mail-Vorlage für den Versand des Angebots (z.B. "Angebot als PDF senden") an die Kund:in.
|====

[TIP]
.Du siehst die passende E-Mail-Vorlage nicht?
====
Du siehst für die Ereignisaktion "Angebot als PDF versenden" die passende E-Mail-Vorlage nicht? Dann liegt das daran, dass du sie noch nicht erstellt hast. Dies kannst du im Menü *Einrichtung » Mandant » _Mandant wählen_ » E-Mail » Vorlagen* tun. Klicke dort auf *Neue E-Mail-Vorlage* (icon:plus-square[role="green"]) und erstelle die Vorlage nach deinen Anforderungen. Der Name, den du hier für die E-Mail-Vorlage vergibst, wird dann auch in den Ereignisaktionen ausgegeben. Weitere Informationen zum Einrichten findest du auf der Handbuchseite xref:crm:e-mails-versenden.adoc#1200[E-Mail-Vorlage erstellen].
====
