= Auftragsherkunft
:keywords: Auftragsherkunft, Auftragsherkünfte, Herkunft, Herkünfte, Referrer, Herkunft aktivieren, Auftragsherkunft aktivieren, Unterherkunft, Unterherkünfte, Herkunfts-ID, Referrer-ID, Auftragsherkunft löschen, Herkunft löschen
:author: team-order-core

Omni-Channel-Verkauf mit plentymarkets bedeutet, dass du deine Artikel über eine Vielzahl von Kanälen anbieten und so Aufträge aus den verschiedensten Quellen generieren kannst.
Einige Auftragsherkünfte sind im System vorab angelegt und können nicht geändert werden. Andere Herkünfte werden automatisch hinzugefügt, zum Beispiel durch das Einbinden eines Plugins oder xref:pos:pos.adoc#[plentyPOS].
Plugin-Herkünfte können nicht gelöscht werden. Du kannst Herkünfte aber auch manuell hinzufügen.

Jede Herkunft erhält eine eigene ID. Manche Herkünfte haben Unterherkünfte, bei denen die IDs dann Dezimalstellen haben. Die Marktplätze *Amazon* und *eBay* sowie plentyPOS haben je eine allgemeine Herkunft und Unterherkünfte.
Bei eBay oder Amazon hat jede Länderplattform eine eigene Unterherkunft, ebenso wie jede plentyPOS-Kasse.

Unabhängig von der Herkunft sind alle Aufträge im Menü *Aufträge » Aufträge bearbeiten* aufgelistet und bearbeitbar. Dort ist die Herkunft an jedem Auftrag hinterlegt. In der zum Auftrag gehörenden Zeile wird die ID der Herkunft angezeigt. Zudem ist die Herkunft im Tab *Einstellungen* eines Auftrags erkennbar.
Diese Herkunft kann geändert werden, allerdings nur bei manuell angelegten Herkünften und auch nur solange noch keine Rechnung erzeugt wurde.

[#spalten-konfigurieren]
== Spalten in der Übersicht konfigurieren

Die Tabellenspalten in der Übersicht der Auftragsherkünfte sind konfigurierbar. Beim ersten Öffnen des Menüs *Einrichtung » Aufträge » Auftragsherkunft* wird dir die Standardansicht der Tabelle angezeigt. Mit Klick auf *Spalten konfigurieren* (material:settings[]) kannst du wählen, welche Spalten du sehen möchtest und in welcher Reihenfolge diese angezeigt werden sollen.

[.collapseBox]
.*Spalten konfigurieren*
--
Wenn du die Tabelle einmal angepasst hast, wird diese Auswahl gespeichert. Du kannst das Layout jederzeit ändern. Die zur Verfügung stehenden Spalten findest du in <<table-order-referrer>>. Gehe wie im Folgenden beschrieben vor, um die Tabelle anzupassen.

[.instruction]
Spalten konfigurieren:

. Öffne das Menü *Einrichtung » Aufträge » Auftragsherkunft*.
. Klicke oben rechts auf *Spalten konfigurieren* (material:settings[]). +
→ Das Fenster *Spalten konfigurieren* wird geöffnet.
. Wähle die Spalten, die angezeigt werden sollen (material:done[]). Beachte dazu die Erläuterungen in <<table-order-referrer>>.
. Ziehe (material:drag_indicator[]) die Spalten per Drag-and-drop an die gewünschte Stelle, bis sie in der für dich richtigen Reihenfolge angezeigt werden.
. Füge bei Bedarf Spalten hinzu oder wähle Spalten ab, wenn du sie nicht benötigst.
. Klicke auf *Bestätigen*. +
→ Die Einstellungen werden gespeichert.
--

Die folgenden Spalten stehen für die Übersicht der Auftragsherkünfte zur Verfügung.

[[table-order-referrer]]
.Übersicht der Auftragsherkünfte
[cols="1,3"]
|===
|Einstellung |Erläuterung

| *Auswahl*
|Ermöglicht die Auswahl der Herkünfte über eine Checkbox, damit du die vorhandenen <<#gruppenfunktionen-verwenden, Gruppenfunktionen>> ausführen kannst.

| *ID*
|Zeigt die ID der Herkunft an. Jede Auftragsherkunft erhält eine eigene ID. Diese wird automatisch vom System zugewiesen und ist nicht änderbar. Für manuelle Herkünfte stehen die IDs im Bereich 9-100 zur Verfügung. Die IDs 1-8 sowie die IDs ab 101 sind von fest im System hinterlegten Auftragsherkünften besetzt. Unterherkünfte sind an dezimalen IDs zu erkennen, zum Beispiel 2.08 für eBay Germany. +
*_Tipp:_* Mit Klick auf den Pfeil im Tabellenheader kannst du die Herkünfte der Tabelle auf- oder absteigend nach ID sortieren.

| *Name*
|Zeigt den Namen der Herkunft an. Der Name wird im System angezeigt, zum Beispiel bei der Auftragssuche. Der Name kann jederzeit geändert werden. +
*_Tipp:_* Mit Klick auf den Pfeil im Tabellenheader kannst du die Herkünfte der Tabelle alphabetisch nach Namen sortieren.

| *Interner Name*
|Zeigt den internen Namen der Herkunft an. Der interne Name ist nicht änderbar und wird nicht im System angezeigt. Nur fest hinterlegte Auftragsherkünfte erhalten einen internen Namen, manuell angelegte Herkünfte nicht.

| *Eigner*
|Zeigt den Eigner der Herkunft an, der für einen Auftrag automatisch als Eigner eingetragen wird. Zur Auswahl stehen die im Menü *Einrichtung » Einstellungen » Benutzer » Konten* xref:business-entscheidungen:benutzerkonten-zugaenge.adoc#[berechtigten Personen].

| *Sichtbar in Auswahl*
|Zeigt an, ob die Herkunft in der Auswahl sichtbar ist. Ist die Herkunft aktiviert (material:done[]), wird sie in anderen Menüs angezeigt. Ist die Herkunft deaktiviert, wird sie in anderen Menüs nicht angezeigt.

| *Aktionen*
|Stellt rechts in der Zeile einer Herkunft weitere <<#weitere-aktionen, Aktionen>> zur Verfügung.

|===

[TIP]
.Daten aktualisieren
======
Mit Klick auf *Daten aktualisieren* (material:refresh[]) oben rechts wird die Ansicht aktualisiert.
======

[#herkuenfte-suchen]
== Nach Herkünften suchen

Verwende eine der folgenden Möglichkeiten, um nach Herkünften zu suchen. Wenn du eine Suche ausführst, werden deine gewählten Sucheinstellungen oben als Chips dargestellt.

[.instruction]
Nach Herkünften suchen:

. Öffne das Menü *Einrichtung » Aufträge » Auftragsherkunft*.
.. *_Möglichkeit 1:_* Klicke auf material:search[], um direkt eine Liste aller Herkünfte zu sehen.
.. *_Möglichkeit 2:_* Gib etwas in das Suchfeld ein und klicke auf einen der automatischen Vorschläge.
.. *_Möglichkeit 3:_* Klicke auf material:tune[], um die Suchergebnisse mit Hilfe von Filtern einzugrenzen.

[#filter-verwenden]
=== Filter verwenden

Verwende Filter, um die Suche nach Herkünften weiter einzugrenzen. Deine gewählten Filter werden oben als Chips dargestellt. Die folgende Tabelle listet alle verfügbaren Filter.

[[table-filters-referrer]]
.Filter für Herkünfte
[cols="1,3"]
|===
|Filter |Erläuterung

| *Herkunft von*
|Gib eine Herkunft ein, ab der gefiltert werden soll.

| *Herkunft bis*
|Gib eine Herkunft ein, bis zu der gefiltert werden soll.

| *Name*
|Gib einen Namen ein, um nach Herkünften mit diesem Namen zu filtern.

| *Nur Hauptherkünfte anzeigen*
|Setze ein Häkchen, um nur nach Hauptherkünften zu filtern.

| *Nur eigene Herkünfte anzeigen*
|Setze ein Häkchen, um nur nach eigenen Herkünften zu filtern.

|===

.Funktionen
[cols="1,4a"]
|===
|Element |Erläuterung

|material:undo[role=darkGrey]
|Setzt die gewählten Filterkriterien zurück.

|material:search[role=skyBlue] *SUCHEN*
|Führt die Suche aus.
|===

[#weitere-aktionen]
== Weitere Aktionen durchführen

Rechts in der Spalte einer Auftragsherkunft stehen dir weitere Funktionen zur Verfügung. Dort kannst du <<#herkunft-bearbeiten, Herkünfte bearbeiten>>, <<#webshop-url-kopieren, Webshop-URLs kopieren>> und <<#herkunft-loeschen, Herkünfte löschen>>. In den folgenden Kapiteln werden diese Funktionen näher beschrieben.

[#herkunft-bearbeiten]
=== Herkunft bearbeiten

Du kannst Herkünfte jederzeit bearbeiten. Gehe dazu wie im Folgenden beschrieben vor.

[.instruction]
Herkunft bearbeiten:

. Öffne das Menü *Einrichtung » Aufträge » Auftragsherkunft*.
. Führe die Suche (material:search[]) aus, um Herkünfte anzuzeigen.
. Klicke rechts in der Zeile der Herkunft auf *Bearbeiten* (material:edit[]). +
→ Ein Fenster zum Bearbeiten der Herkunft wird geöffnet.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<#table-edit-referrer>>.
. Klicke auf *Speichern* (material:save[role=skyBlue]). +
→ Die Änderungen werden übernommen.

[[table-edit-referrer]]
.Herkunft bearbeiten
[cols="1,3"]
|===
|Einstellung |Erläuterung

| *Name*
|Gib bei Bedarf einen neuen Namen ein.

| *Eigner*
|Wähle bei Bedarf einen anderen Eigner aus der Dropdown-Liste. +
*_Tipp:_* Nutze die <<#gruppenfunktionen-verwenden, Gruppenfunktion>> *Eigner ändern*, um den Eigner für mehrere Herkünfte auf einmal zu ändern. Die Option *Alle auswählen* im Tabellenheader ermöglicht es dir außerdem, den Eigner für alle Herkünfte auf einmal zu ändern.

| *Sichtbar in Auswahl*
|Ändere bei Bedarf die Sichtbarkeit in der Auswahl. Ist die Umschaltfläche aktiviert (material:toggle_on[role=skyBlue]), wird die Herkunft in anderen Menüs angezeigt. Ist die Herkunft deaktiviert, wird sie in anderen Menüs nicht angezeigt. +
*_Tipp:_* Nutze die <<#gruppenfunktionen-verwenden, Gruppenfunktion>> *Sichtbarkeit ändern*, um mehrere Herkünfte auf einmal für die Sichtbarkeit in der Auswahl zu aktivieren bzw. zu deaktivieren. Die Option *Alle auswählen* im Tabellenheader ermöglicht es dir außerdem, alle Herkünfte auf einmal dafür zu aktivieren bzw. zu deaktivieren.

|===

[#webshop-url-kopieren]
=== Webshop-URL kopieren

Die Webshop-URL wird zum Beispiel für Affiliate-Dienste benötigt. Sie enthält die jeweilige ID als sogenannte Referrer-ID. Um eine Webshop-URL in den Zwischenspeicher zu kopieren, gehe wie im Folgenden beschrieben vor.

[.instruction]
Webshop-URL kopieren:

. Öffne das Menü *Einrichtung » Aufträge » Auftragsherkunft*.
. Führe die Suche (material:search[]) aus, um Auftragsherkünfte anzuzeigen.
. Klicke rechts in der Zeile der Herkunft auf *Webshop-URLs* (material:remove_red_eye[]). +
→ Ein Fenster mit allen für die Herkunft verfügbaren Webshop-URLs wird geöffnet.
. Klicke auf (terra:copy_clipboard[]), um die Webshop-URL in den Zwischenspeicher zu kopieren. +
*_Hinweis:_* Hast du mehr als einen Mandanten, werden alle Webshop-URLs untereinander angezeigt.

[#herkunft-loeschen]
=== Herkunft löschen

Herkünfte, die du selbst erstellt hast, können gelöscht werden. Systemherkünfte sind hingegen nicht löschbar. Um eine Herkunft zu löschen, gehe wie im Folgenden beschrieben vor. +
*_Tipp:_* Nutze die <<#gruppenfunktionen-verwenden, Gruppenfunktion>> *Auftragsherkunft löschen*, um mehrere Herkünfte auf einmal zu löschen.

[.instruction]
Herkunft löschen:

. Öffne das Menü *Einrichtung » Aufträge » Auftragsherkunft*.
. Führe die Suche (material:search[]) aus, um Herkünfte anzuzeigen.
. Klicke rechts in der Zeile der Herkunft auf *Löschen* (material:delete[]). +
*_Hinweis:_* Das Löschen-Symbol kann nur bei löschbaren Herkünften angeklickt werden.
. Bestätige die Sicherheitsabfrage, indem du auf *Löschen* (material:delete[role=red]) klickst. +
→ Die Herkunft wird gelöscht.

[#neue-herkunft-erstellen]
== Neue Herkunft erstellen

Du kannst dem System jederzeit neue Auftragsherkünfte hinzufügen. Gehe wie im Folgenden beschrieben vor, um eine Auftragsherkunft manuell anzulegen.

[.instruction]
Neue Herkunft erstellen:

. Öffne das Menü *Einrichtung » Aufträge » Auftragsherkunft*. +
→ Die Übersicht der Auftragsherkünfte wird geöffnet.
. Klicke oben auf *Neue Herkunft erstellen* (material:add[]). +
→ Das Fenster zum Erstellen einer neuen Herkunft wird geöffnet.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<#table-create-referrer>>.
. Klicke auf *Erstellen* (material:add[role=green]). +
→ Die Herkunft wird erstellt.

[[table-create-referrer]]
.Herkunft erstellen
[cols="1,3"]
|===
|Einstellung |Erläuterung

| *Herkunfts-ID*
|Die nächste freie ID ist hier bereits voreingetragen. Passe sie bei Bedarf an, aber beachte, dass für manuell angelegte Herkünfte lediglich die IDs 9-100 zur Verfügung stehen.

| *Name*
|Gib einen Namen für die Herkunft ein.

| *Eigner*
|Wähle einen Eigner für die Herkunft.

| *Sichtbar in Auswahl*
|Aktiviere die Umschaltfläche, wenn die Herkunft in der Auswahl sichtbar sein soll. Ist die Umschaltfläche aktiviert (material:toggle_on[role=skyBlue]), wird die Herkunft in anderen Menüs angezeigt. Ist die Herkunft deaktiviert, wird sie in anderen Menüs nicht angezeigt.

|===

[#gruppenfunktionen-verwenden]
== Gruppenfunktionen verwenden

Anhand einer Gruppenfunktion kannst du eine bestimmte Aktion für alle gewählten Auftragsherkünfte auf einmal durchführen. In der folgenden Tabelle werden die für Auftragsherkünfte verfügbaren Gruppenfunktionen aufgelistet und näher beschrieben.

[[table-group-functions-order-referrer]]
.Gruppenfunktionen für Auftragsherkünfte
[cols="2,1,6a"]
|===
|Gruppenfunktion |Symbol |Erläuterung

| *Sichtbarkeit ändern*
|material:remove_red_eye[]
|Ändert die Sichtbarkeit in der Auswahl für alle gewählten Auftragsherkünfte. Je nach Einstellung sind die Herkünfte in anderen Menüs *sichtbar* oder *nicht sichtbar*.

| *Eigner ändern*
|material:people_alt[]
|Ändert den Eigner aller gewählten Auftragsherkünfte. Wähle einen anderen Eigner aus der Dropdown-Liste.

| *Auftragsherkunft löschen*
|material:delete[]
|Löscht alle gewählten Auftragsherkünfte. Beachte, dass nur von dir selbst angelegte Auftragsherkünfte gelöscht werden können. Vom System automatisch angelegte Herkünfte sind nicht löschbar.

|===

[TIP]
.Herkunft wird für Affiliate-Dienstleister benötigt
====
Die Auftragsherkunft ist auch Voraussetzung für die Kooperation mit Affiliate-Partnern. Diese Partner vermitteln dir kaufinteressierte Besucher:innen über definierte Tracking-URLs und erwarten bei einem durch sie vermittelten Verkauf eine Provision.
====

[#analyse-orders]
== Aufträge nach Auftragsherkunft filtern und auswerten

Die Auftragssuche im Menü *Aufträge » Aufträge bearbeiten* bietet viele Filter, um deine Suche einzugrenzen. Der Filter *Herkunft* sucht Aufträge nach der Auftragsherkunft (zum Beispiel gefiltert nach Mandant (Shop), Amazon, eBay etc.). Für Amazon und eBay gibt es sowohl allgemeine Herkünfte als auch eine Unterherkunft für jede Länderplattform.

Bei monatlichen Auswertungen ist es sinnvoll, Suchfilter zu kombinieren und einen zusätzlichen Datumsfilter, zum Beispiel das Datum des Auftragseingangs, zu wählen und einen genauen Zeitraum festzulegen.

Die Herkunftsangabe ist für die Erfolgskontrolle in deinem Webshop wichtig. Nur über diese Einstellung kannst du nachvollziehen, welche Plattformen für dein Warenangebot profitabel sind. Neben der Suchfunktion im Menü *Aufträge » Aufträge bearbeiten* stehen dir im Bereich xref:business-entscheidungen:plenty-bi.adoc#[plentyBI] weitere Auswertungsmöglichkeiten zur Verfügung. Dort kannst du über die Herkunftsangabe die Umsätze der Auftragsherkünfte sehen. So entscheidest du fundiert, wie du dein Werbebudget künftig immer gezielter und effizienter einsetzt.
