= Aufträge
:keywords: Aufträge verwalten, Auftrag, Aufträge, Auftragsabwicklung
:author: team-order-core, team-docs-automation

In diesem Themenbereich findest du alle Informationen zu eingehenden Aufträgen und wie du nach dem Auftragseingang fortfährst. Je nachdem für welche Verkaufsstrategie und Verkaufskanäle du dich entscheidest, fließen nach erfolgreicher Einrichtung der Kanäle Aufträge verschiedener xref:auftraege:auftragsherkunft.adoc#[Herkünfte] in dein plentymarkets System ein. Neben dem eigenen Webshop sind dies in erster Linie die verschiedenen xref:maerkte:maerkte.adoc#[Marktplätze und Preisportale].

plentymarkets verfügt u.a. über eine umfangreiche Schnittstelle zu xref:maerkte:amazon-einrichten.adoc#[Amazon], die nicht nur den automatisierten Abgleich mit dem Seller Central gewährleistet, sondern auch weitere Amazon-Angebote wie xref:maerkte:amazon-fulfillment.adoc#[Fulfillment by Amazon] umfasst.

Dank der vollständigen xref:maerkte:ebay-einrichten.adoc#[eBay-Anbindung] in plentymarkets kannst du u.a. Listings starten und eBay-Shop-Artikel bei eBay einstellen, Verkäufe abrufen, automatisch Bewertungen abgeben und Käufer:innen anmahnen.

Nach dem Auftragseingang werden alle Aufträge in einem Menü gesammelt und in einem identischen Format dargestellt, damit die xref:auftraege:auftraege-verwalten.adoc#1500[Bearbeitung] leicht erfolgen kann. Jeder Auftrag erhält eine eindeutige *Auftrags-ID*. Weitere Schritte nach dem Auftragseingang, wie die Eingangsbestätigung zur Bestellung, andere E-Mails oder die Generierung von xref:auftraege:auftragsdokumente.adoc#[Auftragsdokumenten], lassen sich automatisieren. Neben dem eigentlichen Auftrag, der im Rahmen einer Bestellung angelegt wird, gibt es in plentymarkets weitere *Auftragstypen*. Die Auftragstypen dienen dazu, verschiedene Geschäftsvorfälle abzubilden.

Folgende Auftragstypen gibt es in plentymarkets:

 * xref:auftraege:auftraege-verwalten.adoc#[Auftrag]
 * xref:auftraege:auftraege-verwalten.adoc#240[Angebot]
 * xref:auftraege:auftraege-verwalten.adoc#1100[Vorbestellung]
 * xref:auftraege:auftraege-verwalten.adoc#600[Gewährleistung]
 * xref:auftraege:auftraege-verwalten.adoc#500[Gutschrift]
 * xref:auftraege:auftraege-verwalten.adoc#300[Lieferauftrag]
 * xref:auftraege:auftraege-verwalten.adoc#700[Reparatur]
 * xref:auftraege:auftraege-verwalten.adoc#400[Retoure]
 * xref:auftraege:auftraege-verwalten.adoc#800[Sammelauftrag]
 * xref:auftraege:auftraege-verwalten.adoc#850[Sammelgutschrift]

Für den Versand stehen mit Dokumenten wie der xref:auftraege:pickliste.adoc#[Pickliste] und der xref:auftraege:packliste.adoc#[Packliste] die notwendigen Unterlagen zur Verfügung, um ein schnellstmögliches Fulfillment zu gewährleisten.

Im xref:fulfillment:versand-center-2-0.adoc#auftrag-anmelden[Versand-Center] meldest du die Versandaufträge an, bearbeitest diese bei Bedarf oder lässt dir spezielle Versandaufträge anzeigen.

Zur effizienten Bearbeitung von Aufträgen und anderen Geschäftsvorfällen kannst du außerdem xref:automatisierung:prozesse-einrichten.adoc#[Prozesse] anlegen und diese automatisiert ablaufen lassen. Prozesse bieten den höchsten Grad der Automatisierung in plentymarkets. Darüber hinaus stehen dir noch xref:automatisierung:ereignisaktionen.adoc#[Ereignisaktionen] und der xref:automatisierung:aktionsmanager.adoc#[Aktionsmanager] zur Verfügung, um deine Auftragsabwicklung durch Automatismen zu erleichtern.
