= Auftragstypen [Testphase] 
:keywords: Auftrag, Auftrag, Auftrag, Aufträge, Aufträge,...
:description: Erfahre, wie du mit Auftragstypen in der Aufträge-UI [Testphase] in plentymarkets arbeitest.
:author: team-order-core

//// 
// TODO: xref anpassen
Folgende Auftragstypen gibt es in plentymarkets:
 * xref:auftraege:auftraege-verwalten.adoc#[Auftrag]
 * xref:auftraege:auftraege-verwalten.adoc#240[Angebot]
 * xref:auftraege:auftraege-verwalten.adoc#1100[Vorbestellung] noch hinzufügen
 * xref:auftraege:auftraege-verwalten.adoc#600[Gewährleistung]
 * xref:auftraege:auftraege-verwalten.adoc#500[Gutschrift]
 * <</auftraege/auftraege-verwalten#300, Lieferauftrag>>
 * xref:auftraege:auftraege-verwalten.adoc#700[Reparatur]
 * xref:auftraege:auftraege-verwalten.adoc#400[Retoure]
 * xref:auftraege:auftraege-verwalten.adoc#800[Sammelauftrag]
 * xref:auftraege:auftraege-verwalten.adoc#850[Sammelgutschrift]

 siehe: auftraege-testphase.adoc
Auftragsdokumente: team-docs-automation

== Auftrag [Beta]
Unter: Einrichtung - Aufträge - Auftragstypen - Auftrag [Beta]

// TODO: einheitlich für alle: rechts icon:settings[set=material] *Spalten konfigurieren* und Mülleimer (tooltip fehlt). Durch Klick auf icon:delete[set=material] geht der Artikel zurück in die Auswahl.
////

== Lieferauftrag

[.instruction]
Gehe folgendermaßen vor, um einen Lieferauftrag anzulegen:

. Öffne das Menü *Aufträge » Aufträge [Testphase]*.
→ Die Auftragsübersicht öffnet sich.
. Suche (icon:search[role="blue"]) anhand der Filtereinstellungen den Auftrag, für den ein Lieferauftrag angelegt werden soll.
. Öffne den *Auftrag*, für den ein Lieferauftrag angelegt werden soll.
. Klicke auf Warenkorb (icon:shopping_cart[set=material]) *Aufträge erstellen*. Es öffnet sich ein Bearbeitungsfenster. Wähle *Lieferauftrag*, um einen Lieferauftrag anzulegen.
. Wähle entweder die Option *Automatisch aufteilen* oder *Für bestimmte Positionen*.  +
→ Ein Bearbeitungsfenster wird geöffnet.
. Nimm die Einstellungen anhand <<table-xxx>> vor.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Der Lieferauftrag wird angelegt und in einem eigenen Fenster geöffnet.
// TODO: table suchen/anlegen; Schritte für automatisch und ausgewählte Positionen


Einstellungen für Aufträge in Lieferaufträge splitten
. Öffne das Menü *Einrichtung » Aufträge » Lieferauftrag*.
→ Die Ansicht *Aufträge in Lieferaufträge splitten nach* öffnet sich. Voreingestellt ist die Option *Lager*. 
. Wähle aus der Dropdown-Liste:
* *Aus*
* *Lager* 
* *Versandprofil* 
* *Lager und Versandprofil*
* *Lager- und Netto-Warenbestand*


[#order-type-delivery-order]
== Auftragstyp Lieferauftrag nutzen

Mithilfe des Auftragstyps *Lieferauftrag* werden aus einem Hauptauftrag Lieferaufträge für die enthaltenen Auftragspositionen generiert, so dass du diese einzeln oder in Teilen verschicken kannst. So kannst du beispielsweise Artikel, die du auf Lager hast, sofort losschicken und Artikel, die du erst noch geliefert bekommst, später nachsenden. Führe dies mit unterschiedlichen oder auch nur mit einem Versanddienstleister durch. +
Lieferaufträge können *manuell*, *automatisch* oder per *Ereignisaktion* erstellt werden.

[WARNING]
.Alle Auftragspositionen in Lieferaufträge übernehmen
====
Erstellst du Lieferaufträge aus einem Auftrag, müssen _alle_ Auftragspositionen des Hauptauftrags in Lieferaufträge überführt werden. Übernimmst du nicht alle Auftragspositionen in Lieferaufträge, kommt es zu Fehlern im Bestand und den Lagern.
====

[#delivery-order-characteristics]
=== Merkmale von Lieferaufträgen

Im Allgemeinen besitzen Lieferaufträge folgende Eigenschaften:

* Die Auftragspositionen eines Lieferauftrages lassen sich nach dem Erzeugen des Lieferauftrages *nicht* mehr anpassen.
* Der *Preis* und das *Gewicht* eines Artikels werden aus dem Hauptauftrag übernommen.
* Die Auftragssprache wird aus dem Hauptauftrag übernommen.
* *Adressetikett*, *Lieferschein*, *Proformarechung* und *Gelangensbestätigung* können im Tab *Belege* ? eines Lieferauftrags generiert werden.
* Die *Rechnung* und alle weiteren Dokumente werden zentral im Hauptauftrag generiert.
* Die Bestandsreservierung für die in einem Lieferauftrag enthaltene Menge wird beim Anlegen eines Lieferauftrags vom Hauptauftrag auf den Lieferauftrag übertragen.

[IMPORTANT]
.Gemeinsamer Status
====
Der Hauptauftrag folgt immer dem Status des Lieferauftrags mit dem niedrigsten Status.
Wenn z.B. ein Auftrag in Status *5.0* zwei Lieferaufträge hat und einer dieser Lieferaufträge wechselt in den Status *6.5*, ändert sich am Status des Hauptauftrages zunächst nichts. Erst wenn der zweite Lieferauftrag ebenfalls in den Status *6.5* wechselt, wird automatisch auch der Status des Hauptauftrages zu *6.5* geändert.
====

[#basic-settings-delivery-order]
=== Grundeinstellungen für Lieferaufträge vornehmen

[WARNING]
.Lager pro Auftragsposition zuordnen
====
Im Menü *Einrichtung » Aufträge » Einstellungen* muss zwingend für die xref:auftraege:grundeinstellungen.adoc#intable-warehouse-assignment[Zuordnung des Lagers] die Option *b) pro Artikelposition kann ein Lager zugeordnet werden* ausgewählt werden.
====
// TODO: xref anpassen


[#edit-orders-and-delivery-orders]
=== Haupt- und Lieferaufträge bearbeiten

// TODO: Text aus alter UI - anpassen
Wenn du einen Hauptauftrag löschen möchtest, musst du zuerst die Lieferaufträge löschen. Lieferaufträge können einzeln oder über die Gruppenfunktion in der Auftragssuche gelöscht werden. Erst danach kann der Hauptauftrag gelöscht werden. Beachte aber, dass Aufträge nicht gelöscht werden können, sobald steuerrelevante Dokumente für diesen Auftrag existieren.

Es können weitere Auftragspositionen zum Hauptauftrag hinzugefügt oder daraus gelöscht werden. Allerdings können nur Auftragspositionen, die nicht in Lieferaufträgen enthalten sind, aus dem Hauptauftrag gelöscht werden. Die Menge der Artikel im Hauptauftrag lässt sich erhöhen oder verringern. Löschen solltest du jedoch nur *nicht zu Lieferaufträgen zugeordnete Mengen*.

[WARNING]
.Löschen von Positionen in einem Lieferauftrag
====
Technisch möglich ist zwar auch das Löschen von Positionen, die bereits in einem Lieferauftrag enthalten sind. Dies solltest du jedoch vermeiden, um Fehlfunktionen zu verhindern.
====


[#create-order-from-existing-order]
=== Auftrag über einen bestehenden Auftrag anlegen

In einem Auftrag findest du das Symbol *Neuer Auftrag* (icon:plus-square[role="green"]) im Bereich *Allgemein*. Gehe folgendermaßen vor, um einen neuen Auftrag in einem bestehenden Auftrag anzulegen.
. Öffne einen Auftrag.
. Im Bereich *Allgemein* hast du die Möglichkeit, einen Auftragstyp zu wählen.
. Wähle *Auftrag* oder *Vorbestellung*. 
. Mache dann...
// TODO: Was sollte dann passieren? Text auf neue UI anpassen


[#create-delivery-order-manually]
=== Lieferaufträge manuell anlegen

Bei Bedarf kannst du Lieferaufträge manuell über den Hauptauftrag anlegen. Bei dieser Methode wählst du für jeden Lieferauftrag einzeln die Auftragspositionen und -mengen aus, die der Lieferauftrag enthalten soll.

:ordertype: Lieferauftrag

[.instruction]
Lieferaufträge manuell anlegen:

// TODO: prüfen ob richtig erklärt
. Öffne das Menü *Aufträge » Aufträge [Testphase]*.
. Wähle über das Symbol *Filter* im Filter *Auftragstyp* die Option *Auftrag*.
. Klicke auf *Suchen* (icon:search[role="blue"]). +
→ Es werden nur Aufträge aufgelistet.
. Klicke in den Auftrag, für den du einen Lieferauftrag anlegen möchtest.
. Klicke auf icon:shopping_cart[set=material] und wähle den Auftragstyp *Lieferauftrag*.
. Wähle die Option *Für bestimmte Positionen*. +
→ Der Lieferauftrag wird angelegt und erscheint in der Seitennavigation links als *Neuer Lieferauftrag*.
. Wiederhole bei Bedarf die Schritte, um weitere Lieferaufträge anzulegen.


[#create-delivery-orders-automatically]
=== Lieferaufträge automatisch anlegen

[IMPORTANT]
.Bedingung für das automatische Anlegen von Lieferaufträgen
====
Lieferaufträge können nur automatisch erzeugt werden, wenn noch kein Lieferauftrag zu dem Auftrag besteht.
====

Wenn du Lieferaufträge automatisch anlegen lässt, greifen die zuvor in <<table-order-types-delivery-order-options>> beschriebenen Kriterien zum Aufsplitten in Lieferaufträge. Somit müssen die Auftragspostionen und -mengen nicht einzeln ausgewählt werden. Stattdessen überführt das System je nach gewähltem Kriterium alle Auftragspositionen automatisch in Lieferaufträge.
// TODO: Tabelle - wohin? https://knowledge.plentymarkets.com/de-de/manual/main/auftraege/auftraege-verwalten.html#intable-splitting-orders

[.instruction]
Lieferaufträge automatisch anlegen

. Öffne das Menü *Aufträge » Aufträge [Testphase]*.
. Gehe in die Auftragsübersicht.
. Öffne aus der Übersicht den Auftrag, für den Lieferaufträge angelegt werden sollen.
. Klicke auf das Warenkorb und wähle den Auftragstyp *Lieferauftrag*.
. Wähle die Option *Automatisch aufteilen*. +
→ Der Lieferauftrag wird angelegt.
. Wiederhole den Prozess, um be Bedarf weitere Lieferaufträge anzulegen.

////
nach Rücksprache mit Patrick derzeitige Beispiele weiterhin nutzbar
Hier die Beispiele einfügen
[#create-delivery-order-via-ea] 
=== Lieferaufträge per Ereignisaktion anlegen
////


== Angebot

:ordertype: Angebot
////
siehe https://knowledge.plentymarkets.com/de-de/manual/main/auftraege/angebot.html
////

// TODO: fertigstellen
neue UI:
Kontakte - Kontextmenü icon:more_vert[set=material] - icon:shopping_cart[set=material] *Aufträge* - Auswahl:
*Aufträge*
*Neuer Auftrag*
*Neues Angebot*
*Neuer Auftrag [Beta]*
*Neues Angebot [Beta]*
*Neues Abonnement [Beta]*

Um ein neues Angebot zu erstellen, muss beim Kontakt eine Rechnungsadresse hinterlegt sein.
// TODO: Ansonsten Fehlermeldung: weiße Schrift auf rot: Fehler: Rechnungsadresse muss vorhanden sein.

[.instruction]
Neues Angebot anlegen:

. Klicke auf *CRM*. Die Kontaktübersicht öffnet sich.
. Wähle einen Kontakt und klicke auf icon:more_vert[set=material], um das Kontextmenü zu öffnen.
. Wähle den Kontakt, zu dem du ein *Neues Angebot [Beta]* erstellen möchtest.
→ ein neues Fenster öffnet sich.
Level 1: Einstellungen
Level 2: durch Icon Aufklappen kannst du das 2. Level *Auftragspositionen* aufklappen.
// TODO: ausformulieren

[[table-settings-new-offer]]
.Neues Angebot
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+^| *Einstellungen*

| *Auftrag/Angebot*
|Voreingestellt ist *Angebot*. Alternativ könnte der Typ zu Auftrag geändert werden. +
Rechts daneben siehst du Name und ID.

| *Auftragsvorlage*
|Voreingestellt ist Kunde.


2+^| *Auftragspositionen*

| *Rechnungsadresse*
|Angezeigt wird die *Rechnungsadresse*. +
Es muss eine Rechnungsadresse hinterlegt sein, um ein Angebot erstellen zu können.
Über das Icon Auge rechts kannst du den Kontakt öffnen.
// TODO: rotes Sternchen = Pflichtfeld

| *Lieferadresse*
|Angezeigt wird die *Lieferadresse*. +
Es muss eine Lieferadresse hinterlegt sein, um ein Angebot erstellen zu können.
Icon checkbox: Wie Rechnungsadresse. Du kannst wählen, ob die Lieferadresse gleich die Rechnungadresse sein soll.
// TODO: rotes Sternchen = Pflichtfeld

| *Zahlungsart*
|Die hinterlegte *Zahlungsart* wird angezeigt.
graues Sternchen = Pflichtfeld

| *Währung*
|Die hinterlegte *Währung* wird angezeigt. +
Du kannst die Währung über die Dropdown-Liste ändern.
graues Sternchen = Pflichtfeld

| *Rabatt in %*
|Der hinterlegte *Rabatt in %* wird angezeigt.

| *Mandant*
|Die hinterlegte *Zahlungsart* wird angezeigt. +
graues Sternchen = Pflichtfeld

| *Herkunft*
|Die hinterlegte *Zahlungsart* wird angezeigt. +
Über Dropwdown kannst du wählen zwischen *Abo-Aufträge* und *Manuelle Eingabe*.
graues Sternchen = Pflichtfeld

| *Lager*
|Die hinterlegte *Lager* (Abhängig vom Warenbestand) wird angezeigt.

| *Eigner*
|Der *Eigner* wird angezeigt. +
graues Sternchen = Pflichtfeld
|====

// TODO: ausformulieren/korrigieren/Icons
Button "Pfeil Artikel hinzufügen"
Das Fenster schließt sich.

Rechts oben erscheint danach icon:shopping_cart[set=material], daneben mit weißer Zahl in blauem Kreis Anzahl der Artikel. Wenn du darauf klickst, öffnet sich der Warenkorb als *Side cart*.

Der Warenkorb zeigt dir folgende Informationen:
* Bild
* Artikelname
* Barcode
* Preisauswahl (Dropdown)
* Preis
* Menge

Du kannst die *Auftragspositionseigenschaften* über icon:edit[set=material] bearbeiten.
. Klicke auf icon:edit[set=material] *Bearbeiten*, um folgende Eigenschaften zu bearbeiten: Name, Wert, Aufpreis.
. Wähle eine Eigenschaft (Dropdown).
. Über icon:add[set=material] *Hinzufügen* kannst du eine *Eigenschaft hinzufügen*. 
. Klicke auf icon:save[set=material] *Speichern*, um die Änderungen zu speichern.
. Über Icon roter Kreis minus ?? kannst du *Artikel löschen*.
Aufpreis, Rabatt, Summe pro Artikel
Aufpreis gesamt
Zwischensumme

. Über Icon gelb hinterlegt ?? kannst du den *Verkaufpreis aktualisieren*.
. Klicke auf Icon x im schwarzen Kreis, um den Warenkorb zu schließen.



== Retoure
////
https://docs.google.com/document/d/150V8oNG2UrRsHYFXWacR0zbX17F7QP8DN1JxL3rRxnE/edit
erlaubte Kindaufträge: Gewährleistung, Gutschrift, Reparatur
////

[#order-type-return]
=== Auftragstyp Retoure nutzen

Der Auftragstyp Retoure bildet den Geschäftsvorfall einer Retoure ab. Retouren können manuell erfasst werden. Zusätzlich kannst du auch deinen Webshop-Kund:innen erlauben, Retouren über den *Mein Konto* Bereich anzumelden. Das Erfassen einer Retoure bucht die retournierten Artikel noch nicht zurück in den Warenbestand. Du erfasst also zunächst die retournierten Artikel und entscheidest dann, ob die Artikel wieder zum Bestand gebucht werden oder ob weitere Schritte, wie z.B. eine Reparatur, notwendig sind. Die Retoure ist ein untergeordneter Auftragstyp, da Retouren entweder einem Auftrag oder einer Gewährleistung zugeordnet sind.
Bevor du Retouren erfassen kannst, lege xref:auftraege:auftraege-verwalten.adoc#410[Retourengründe] und xref:auftraege:auftraege-verwalten.adoc#420[Artikelstatus für retournierte Artikel] an.
// TODO: xref anpassen

Der Standardstatus für Retouren ist Status 9. Jede Retoure, die erfasst wird, erhält automatisch diesen Status. Du kannst jedoch jederzeit im Menü *Einrichtung » Aufträge » Einstellungen* einen anderen Status als xref:auftraege:grundeinstellungen.adoc#intable-default-status-return[Standard-Status Retoure] festlegen.
// TODO: xref anpassen

[#enter-return-reason]
=== Retourengründe eingeben

Du kannst bis zu 20 Retourengründe eingeben. Beim Erfassen einer Retoure wählst du für jede Auftragsposition einen Grund. Anhand von Retourengründen ist später nachvollziehbar, ob ein Artikel besonders häufig wegen desselben Grundes retourniert wurde. Die Retourengründe können in mehreren Sprachen hinterlegt werden.

:ordertype: Retoure

[.instruction]
Retourengründe eingeben:

. Öffne das Menü *Einrichtung » Aufträge » Auftragstypen » Retoure*.
. Wähle die *Sprache* aus der Dropdown-Liste aus.
. Gib *Gründe* für Retouren für die gewählte Sprache ein. +
*_Hinweis:_* Pro Artikelposition kann ein Grund definiert werden.
. *Speichere* die Einstellungen.
. Wiederhole dies ggf. für weitere Sprachen.


[#enter-status-returns]
=== Status für retournierte Artikel eintragen

Du kannst bis zu 12 Artikelstatus anlegen. Die Status kannst du z.B. nutzen, um einerseits den Zustand der retournierten Artikel, aber auch um den Fortschritt beim Bearbeiten der retournierten Artikel anzugeben. Die Status stehen in einer Retoure im Bereich *Übersicht* bei den Auftragspositionen zur Wahl. Um je nach Fortschritt der Bearbeitung verschiedene Status zuzuweisen, lege die benötigten Status an. Du kannst Retourenstatus in mehreren Sprachen hinterlegen.

:ordertype: Retoure

[.instruction]
Status für retournierte Artikel eintragen:

. Öffne das Menü *Einrichtung » Aufträge » Auftragstypen » Retoure*.
. Wähle die *Sprache* aus der Dropdown-Liste aus.
. Trage die gewünschten *Status* für die Zuordnung zurückgesendeter Artikel für die ausgewählte Sprache ein. +
Hinweis: Pro Artikelposition kann ein eigener Status definiert werden.
. *Speichere* (icon:save[role="green"]) die Einstellungen.
. Wiederhole dies ggf. für weitere Sprachen.


[#create-edit-return]
=== Retoure erfassen und bearbeiten

Eine Retoure erfasst du manuell, wenn ein Paket bei dir eingegangen ist oder du erlaubst deinen registrierten Webshop-Kund:innen, direkt im Kundenkonto des Shops Retouren anzumelden. Nachdem eine Retoure erfasst wurde, werden weitere Bearbeitungsmöglichkeiten sichtbar. So kannst du z.B. den Artikelstatus der retournierten Artikel erst nach dem Erfassen angeben.

[.instruction]
Gehe folgendermaßen vor, um eine Retoure zu erfassen:

. Öffne das Menü *Aufträge » Aufträge [Testphase]*.
→ Die Auftragsübersicht öffnet sich.
. Suche (icon:search[role="blue"]) anhand der Filtereinstellungen den Auftrag, für den eine Retoure erzeugt werden soll.
. Öffne den Auftrag oder die Gewährleistung, für den oder die eine Retoure angelegt werden soll.
. Klicke auf (icon:shopping_cart[set=material]) *Aufträge erstellen*, um auf die Auswahl zu gelangen. Wähle *Retoure*, um eine Retoure anzulegen.
. Wähle entweder die Option *aus einzelnen Positionen* oder *aus allen Positionen*.  +
→ Ein Bearbeitungsfenster wird geöffnet.
. Nimm die Einstellungen anhand <<table-settings-return>> vor.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Die Retoure wird angelegt und in einem eigenen Fenster geöffnet.
////
include::partial$tabelle-aus-optionen-anlegen.adoc[]
////

[[table-settings-return]]
.Optionen beim Erfassen einer Retoure
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+^| *Einstellungen*

| *Status*
|Einen Status für die Retoure aus der Dropdown-Liste wählen. +
Voreingestellt ist der Standardstatus, der im Menü *Einrichtung » Aufträge » Einstellungen* gespeichert wurde.

| *Eigner*
|Einen Eigner aus der Dropdown-Liste wählen, der dem Retourenauftrag zugewiesen wird.

| *Retourengrund*
|Einen Grund für die Retoure aus der Dropdown-Liste wählen.

| *Paketcode der Retoure*
|Paketcode der Retoure eintragen.


2+^| *Artikel*

| *Artikel-ID*
|Die *Artikel-ID* wird angezeigt. (Link)

| *Varianten-ID*
|Die *Varianten-ID* wird angezeigt. (Link)

| *Artikelname*
|Der *Artikelname* wird angezeigt.

| *Attribute*
|Die *Attribute* werden angezeigt.

| *Variantenname*
|Der *Variantenname* wird angezeigt.

| *Barcode*
|Der *Barcode* wird angezeigt.

| *System-EK*
|Der *System-EK* wird angezeigt.

| *Preisauswahl*
|Die *Preisauswahl* wird angezeigt. (editable)

| *Kategorierabatt*
|Der *Kategorierabatt* wird angezeigt.

| *Kundenklassenrabatt*
|Der *Kundenklassenrabatt* wird angezeigt.

| *Verfügbarkeit*
|Die *Verfügbarkeit* wird angezeigt.

| *Netto-WB*
|Der *Netto-WB* wird angezeigt.

| *Lager*
|Das *Lager* wird angezeigt.

Klicke auf icon:add_shopping_cart[set=material], um einen Artikel in den Warenkorb zu legen;

2+^| *Warenkorb*

| *Menge*
|Die Artikelmenge eintragen, die in die Retoure übernommen werden soll.

| *Artikel-ID*
|Die *Artikel-ID* wird angezeigt. (Link)

| *Varianten-ID*
|Die *Varianten-ID* wird angezeigt. (Link)

| *Variantennummer*
|Die *Variantennummer* wird angezeigt. (Link)

| *Artikelname*
|Der *Artikelname* wird angezeigt.

| *Attribute*
|Die *Attribut* werden angezeigt.

| *Variantenname*
|Der *Artikelname* wird angezeigt.

| *Barcode*
|Der *Barcode* wird angezeigt.

| *System-EK*
|Der *System-EK* wird angezeigt.

| *Preisauswahl*
|Die *Preisauswahl* wird angezeigt. (editable)

| *Kategorierabatt*
|Der *Kategorierabatt* wird angezeigt.

| *Kundenklassenrabatt*
|Der *Kundenklassenrabatt* wird angezeigt.

| *Nettopreis*
|Der *Nettopreis* wird angezeigt.

| *Regulärer Nettopreis*
|Der *Reguläre Nettopreis* wird angezeigt.

| *Bruttopreis*
|Der *Bruttopreis* wird angezeigt.

| *Aufpreis gesamt*
|Der *Aufpreis gesamt* wird angezeigt.

| *Rabatt*
|Der *Rabatt* wird angezeigt.

| *Gesamtbetrag (brutto)*
|Der *Gesamtbetrag (brutto)* wird angezeigt.

| *Lager*
|Das *Lager* wird angezeigt.

| *USt.(%)*
|Die *USt.* in Prozent wird angezeigt.

| *Bemerkung*
|Textfeld, um Bemerkungen und Notizen einzutragen.

| *Artikestatus*
|Der zuvor ausgewählte Status des Artikels wird angezeigt.

| *Retourengrund*
|Der zuvor ausgewählte Grund für die Retoure wird angezeigt.
*_Hinweis_*: Wenn ein Grund für alle gewählt wurde, hat dieser Grund Priorität.

| *Verbleibender Positionswert (%)*
|Der verbleibende Wert des Auftrags wird angezeigt. +
Der Wert liegt zwischen 0 und 100.

Nachdem eine Retoure erfasst wurde, kannst du den Artikelstatus für retournierte Artikel wählen. Außerdem werden weitere Bearbeitungsmöglichkeiten sichtbar.

// TODO: prüfen: in basket/general view/edit items: return reason, note, item value %, item status

|====

// TODO: gehört das auf diese Seite?
[#create-return-note]
=== Rücksendeschein erstellen
//// 
Einen Rücksendeschein kannst du deinen Kund:innen bei Zustellung der Ware im Paket beilegen. In diesem Fall sollte der Rücksendeschein Blankofelder für die Retourengründe enthalten. Du kannst deinen Kund:innen aber auch erlauben den Rücksendeschein im *Mein Konto* Bereich auszufüllen, auszudrucken und der Retoure beizulegen.
Bevor Rücksendescheine erzeugt werden können, muss die Dokumentenvorlage
// TODO:prüfen, xref prüfen
xref:auftraege:ruecksendeschein-erzeugen.adoc#[Rücksendeschein] 
Menü *Einrichtung » Mandant » [Mandant wählen] » Standorte » [Standort wählen] » Dokumente » Rücksendeschein* einrichten.
...
====
////


// TODO: besser formulieren
==== Bundle handling 
am Beispiel *Retoure* (für alle Kindauftragstypen)

Erstellen einer Retoure für ein Artikelpaket (Bundle) 
Im System ist ein Artikelpaket (Bundle) als ein Artikel hinterlegt, der aber aufgesplittet wird, wenn du ihn in den Warenkorb legt. Der Preis ist mit diesem Artikel verknüpft. Die Komponenten werde als separate Artikel hinzugefügt und haben einen eigenen Typ. Du kannst daher nur entweder das Bundle oder die einzelnen Komponenten in den Warenkorb legen. 
Je nachdem, welche Option du wählst, wird icon:shopping_cart[set=material] *Zum Warenkorb hinzufügen* unsichtbar, die Menge wird validiert, damit nicht beide zugefügt werden können. 
* Legst du das Artikelpaket in den Warenkorb, verschwindet icon:shopping_cart[set=material] rechts bei den Komponeten des Artikelpakets.
* Legst du eine Komponente in den Warenkorb, wird icon:shopping_cart[set=material] am Artikelpaket unsichtbar.

* Sonderfall Artikelpakete: +
**Artikelpakete** bestehen aus mehreren Einzelartikeln. Für diese Pakete wird in plentymarkets kein eigener Warenbestand geführt. Der Bestand der Artikelpakete richtet sich nach dem Bestand der darin enthaltenen Artikel. Wird ein Artikelpaket verkauft, werden die darin enthaltenen Artikel automatisch in den reservierten Bestand übernommen. +
*_Hinweis:_* Damit ein Paket verfügbar ist, müssen dessen Bestandteile im selben Lager liegen.


== Reparatur

[#use-order-type-repair]
=== Auftragstyp Reparatur nutzen

Reparaturen werden in plentymarkets durch einen eigenen Auftragstyp abgebildet. Reparaturen bestehen aus retournierter, reparaturbedürftiger Ware. Reparaturaufträge können daher nur aus xref:auftraege:auftraege-verwalten.adoc#400[Retourenaufträgen] angelegt werden. Eine Reparatur muss manuell angelegt werden, da jeder Artikel geprüft werden muss.
// TODO: xref prüfen

[#enter-repair-status]
=== Status für Reparaturen eingeben

Hinterlege vor dem Anlegen von Reparaturen verschiedene *Status* für die einzelnen Stationen des Reparaturvorgangs, um den Reparaturverlauf in deinem plentymarkets System genau nachvollziehen zu können. Die Reparaturstatus können in mehreren Sprachen hinterlegt werden.

:ordertype: Reparatur

[.instruction]
Status für Reparaturen eingeben:

. Öffne das Menü *Einrichtung » Aufträge » Auftragstypen » Reparatur*.
. Wähle die *Sprache* aus der Dropdown-Liste aus.
. Trage die von dir benötigten *Status* für Reparaturen für die ausgewählte Sprache ein.
. *Speichere* (icon:save[role="green"]) die Einstellungen.
. Wiederhole dies ggf. für weitere Sprachen.
*_Hinweis:_* Pro Reparatur kann ein Status definiert werden. Es können bis zu 15 Status eingegeben werden.

[#enter-repair-state]
=== Zustände für Reparaturen eingeben

Mit einem *Zustand* kannst du den Artikel genau beschreiben, z.B. ob dieser überhaupt eine Reparatur benötigt oder auch, dass es nicht möglich ist, diesen zu reparieren. Die Zustände können in mehreren Sprachen eingetragen werden.

[.instruction]
Zustände für Reparaturen eingeben:

. Öffne das Menü *Einrichtung » Aufträge » Auftragstypen » Reparatur*.
. Wähle die *Sprache* aus der Dropdown-Liste aus.
. Trage die von dir benötigten *Zustände* für die Zuordnung der Artikelpositionen für die ausgewälte Sprache ein. +
. *Speichere* (icon:save[role="green"]) die Einstellungen.
. Wiederhole dies ggf. für weitere Sprachen.
*_Hinweis:_* Pro Artikelposition kann ein eigener Zustand definiert werden. Es können bis zu 15 Artikelzustände eingegeben werden.


[#create-repair]
=== Reparatur anlegen

[.instruction]
Gehe folgendermaßen vor, um eine Reparatur anzulegen: 

// TODO: table anpassen
. Öffne das Menü *Aufträge » Aufträge [Testphase]*.
→ Die Auftragsübersicht öffnet sich.
. Suche (icon:search[role="blue"]) anhand der Filtereinstellungen nach der Retoure, für den eine Reparatur angelegt werden soll.
. Öffne die *Retoure*, für die eine Reparatur angelegt werden soll.
. Klicke auf (icon:shopping_cart[set=material]) *Aufträge erstellen*, um auf die Auswahl zu gelangen.
. Wähle *Reparatur*, um eine Reparatur anzulegen.
. Wähle *Für bestimmte Positionen*.  +
→ Ein Bearbeitungsfenster wird geöffnet.
. Nimm die Einstellungen anhand <<table-xxx>> vor.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Die Reparatur wird angelegt und in einem neuen Fenster geöffnet.
. Wähle einen *Status*. Voreingestellt ist *12 Reparatur*. Dies ist ein Pflichtfeld (Sternchen). Über die Dropdown-Liste kann ein abweichender Status gewählt werden.
. Wähle einen *Eigner* über die Dropdown-Liste. Dies ist ein Pflichtfeld (Sternchen).
. Wähle einen *Status der Reparatur* über die Dropdown-Liste. 

. *Speichere* (icon:save[role="green"]) die Einstellungen. +
Die *Neue Reparatur* wird in der Seitennavigation links unter Auftragsreferenzen in blauer Schrift angezeigt. Öffne darüber den Bereich *Auftragsrefenrenzen*.


[#edit-repair]
=== Reparatur bearbeiten

Je nach Grund der Rücksendung oder Zustand der zu reparierenden Artikel müssen bei der Bearbeitung verschiedene Schritte durchgeführt werden. +
Da es sich bei einer Reparatur um einen eigenen Auftragstyp handelt, kannst du über Detailansicht über den Bereich *Übersicht* durch Klick auf icon:shopping_cart[set=material] der Reparatur entweder eine *Gutschrift*, eine *Gewährleistung* oder eine *Retoure* anlegen. Die jeweils nötigen Schritte wie die Dokumentenerzeugung, Buchungen des Warenausgangs oder -eingangs oder der eventuellen Buchung von Zahlungen sind jeweils identisch mit denen der Auftragstypen xref:auftraege:auftraege-verwalten.adoc#500[Gutschrift], xref:auftraege:auftraege-verwalten.adoc#600[Gewährleistung] und xref:auftraege:auftraege-verwalten.adoc#400[Retoure] ab.
// TODO: Schritte und xref prüfen


[[table-settings-repair]]
.Optionen beim Erfassen einer Reparatur
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+^| *Einstellungen*

| *Status*
|Einen Status für die Reparatur über die Dropdown-Liste  wählen. +
Voreingestellt ist der Standardstatus, der im Menü *Einrichtung » Aufträge » Einstellungen* gespeichert wurde.

| *Eigner*
|Einen Eigner für die Reparatur über die Dropdown-Liste wählen. +
Voreingestellt ist der aktuelle Benutzer, wenn er Eigner sein kann.

| *Status der Reparatur*
|Einen *Status der Reparatur* über die Dropdown-Liste für die Reparatur wählen. +
Es gibt keine Vorauswahl.


2+^| *Artikel* 

// TODO: Balken farbig und Punkt farbig erkläeren
| *Artikel-ID*
|Die *Artikel-ID* wird angezeigt. (Link)

| *Varianten-ID*
|Die *Varianten-ID* wird angezeigt. (Link)

| *Artikelname*
|Der *Artikelname* wird angezeigt.

| *Attribute*
|Die *Attribute* werden angezeigt.

| *Variantenname*
|Der *Variantenname* wird angezeigt.

| *System-EK*
|Der *System-EK* wird angezeigt.

| *Preisauswahl*
|Die *Preisauswahl* wird angezeigt.

| *Verfügbarkeit*
|Die *Verfügbarkeit* wird angezeigt.
// TODO: Bild Verfügbarkeiten Farben?

| *Netto-WB*
|Der *Netto-Warenbestand* wird angezeigt.

| *Lager*
|Das *Lager* wird angezeigt.

| *Menge*
|Die *Menge* wird angezeigt.

Klicke auf icon:add_shopping_cart[set=material], um einen Artikel in den Warenkorb zu legen. 
Klicke links auf Icon 3 Striche plus *Füge alle offenen Mengen in den Warenkorb*


2+^| *Warenkorb*

| *Menge*
|Die *Menge* wird angezeigt. (editable with validation)

| *Artikel-ID*
|Die *Artikel-ID* wird angezeigt.

| *Varianten-ID*
|Die *Varianten-ID* wird angezeigt.

| *Variantennummer*
|Die *Variantennummer* wird angezeigt.

| *Artikelname*
|Der *Artikelname* wird angezeigt.
Pflichtfeld Sternchen

| *Attribute*
|Die *Attribute* werden angezeigt.

| *Preisauswahl*
|Die *Preisauswahl* wird angezeigt. (editable)

| *Nettopreis*
|Der *Nettopreis* der Auftragsposition wird angezeigt.

| *Bruttopreis*
|Der *Bruttopreis* der Auftragsposition wird angezeigt.

| *Rabatt [%]*
|Der für die Auftragsposition gewährte *Rabatt* wird angezeigt.

| *Gesamtbetrag (brutto)*
|Die Bruttogesamtsumme der Auftragsposition wird angezeigt.

| *Lager*
|Das Lager der Auftragsposition wird angezeigt. +
Über die Dropdown-Liste kann ein Lager gewählt werden.

| *USt. (%)*
|Der Umsatzsteuersatz in Prozent wird angezeigt. +
Über die Dropdown-Liste kann die Umsatzsteuer gewählt werden.

| *Bemerkung*
|Eine *Bemerkung* kann in das Textfeld eingefügt werden. + 

| *Artikelstatus*
|Der *Artikelstatus* wird angezeigt. Es gibt keine Vorauswahl.

Rechts stehen dir die icon:edit[set=material] *Bearbeiten* und icon:delete[set=material] *Löschen* zur Verfügung.


[#order-type-credit-note]
== Gutschrift

In plentymarkets kannst du Gutschriften als PDF-Dateien generieren, um diese z.B. zu drucken oder deinen Kund:innen als E-Mail Anhang zukommen zu lassen. +
Gutschriften nutzt du beispielsweise, um bei bereits bezahlten Aufträgen nachträgliche Preisnachlässe zu gewähren oder wenn im Rahmen von Retouren Rückerstattungen veranlasst werden sollen.

[#use-order-type-credit-note]
=== Auftragstyp Gutschrift nutzen

Bei einer Gutschrift bekommen deine Kund:innen einen Betrag zurückerstattet. Dies kann beispielsweise nach einer xref:auftraege:auftraege-verwalten.adoc#400[Retoure] der Fall sein. Bei der Gutschrift in plentymarkets handelt es sich also nicht um eine Art umgekehrte Rechnung, sondern um eine Rückzahlung. Gutschriftaufträge erzeugst du unter *Aufträge » Aufträge bearbeiten* aus einem Auftrag. Eine Gutschrift ist also immer einem Auftrag zugeordnet. Die in einem Gutschriftauftrag erzeugten Gutschriftbelege werden auch in Buchhaltungsexporten, wie dem *DATEV*-Export, berücksichtigt.
// TODO: xref prüfen

[#save-status-credit-note]
=== Standardstatus für Gutschriften speichern

Bevor du eine Gutschrift anlegst, prüfe den xref:auftraege:grundeinstellungen.adoc#intable-default-status-credit-note[Standard-Status für Gutschriften] im Menü *Einrichtung » Aufträge » Einstellungen*. Passe den Standardstatus bei Bedarf an und speichere die Einstellungen.

[#create-credit-note]
=== Gutschrift anlegen

Eine Gutschrift ist immer mit einem bestehenden Auftrag in deinem plentymarkets System verknüpft. Deshalb musst du den gewünschten Auftrag zunächst in der Auftragsübersicht öffnen, bevor du eine Gutschrift angelegen kannst.

[TIP]
.Gutschriften im Hauptauftrag oder im Retourenauftrag anlegen
====
Hat eine Kund:in den Auftrag bereits gezahlt, beispielsweise per Vorkasse, und entscheidet sich vor dem Warenausgang gegen den Kauf, empfehlen wir den Auftrag zu stornieren und direkt im Hauptauftrag eine Gutschrift über alle Auftragspositionen anzulegen.

// TODO: xref prüfen
Kommt es nach erfolgter Zahlung, Warenausgang und Zustellung der Ware für eine oder alle Auftragspositionen zu einer xref:auftraege:auftraege-verwalten.adoc#400[Retoure] oder im Folgenden zu einem xref:auftraege:auftraege-verwalten.adoc#700[Reparaturauftrag], lege die Gutschrift direkt im entsprechenden Retouren- oder Reparaturauftrag an.
====


:ordertype: Gutschriften

[.instruction]
Gutschriftauftrag anlegen:

. Öffne das Menü *Aufträge » Aufträge [Testphase]*.
→ Die Auftragsübersicht öffnet sich.
. Suche (icon:search[role="blue"]) den Auftrag, für den eine Gutschrift erzeugt werden soll.
. Öffne den Auftrag, für den eine Gutschrift angelegt werden soll.
. Klicke auf Warenkorb (icon:shopping_cart[set=material]) *Aufträge erstellen*, um auf die Auswahl zu gelangen. Wähle *Gutschrift*, um eine Gutschrift anzulegen.
. Wähle entweder *Für alle Positionen* oder *Für bestimmte Positionen*.  +
→ Ein Bearbeitungsfenster wird geöffnet.
. Nimm die Einstellungen anhand <<table-settings-return>> vor.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Die Gutschrift wird angelegt und in einem eigenen Fenster geöffnet.

//// 
include::partial$tabelle-aus-optionen-anlegen.adoc[] 
////

[#create-credit-note-specific]
=== Gutschrift aus bestimmten Position erzeugen

Einzelne Gutschriften kannst du manuell am jeweiligen Gutschriftauftrag erzeugen. Weitere Informationen und Anleitungen zum Anlegen von Gutschriftaufträgen findest du im Kapitel xref:auftraege:auftraege-verwalten.adoc#500[Gutschrift anlegen].
// TODO: xref prüfen

// TODO: besser formulieren
[.instruction]
Gutschrift aus bestimmten Positionen erzeugen:
. Öffne das Menü *Aufträge » Aufträge [Testphase]*. +
→ Die Auftragsübersicht öffnet sich.
. Suche (icon:search[role="blue"]) den Auftrag, für den eine Gutschrift erzeugt werden soll.
. Öffne den gewünschten Auftrag.
. Klicke auf (icon:shopping_cart[set=material]) *Aufträge erstellen*. +
. Wähle aus der Dropdown-Liste *Gutschrift* die Option *Gutschrift für bestimmte Positionen* erstellen. +
→ Die *Gutschrift* zum Auftrag wird erstellt und links in der Navigation als *Gutschrift* unter dem Auftrag angezeigt.
. Klappe den Bereich *Historie* auf. Dort siehst du das Erstellungsdatum, den Benutzer, als Aktion *Neue Gutschrift* und als Status 11 Gutschrift.

Im Bereich *Übersicht* siehst du den Auftragstyp jetzt als Gewährleistung. Links in der Seitennavigation kann der *Auftragstyp* durch Klick auf x geschlossen werden.

[#create-credit-note-several]
=== Mehrere Gutschriften erzeugen
////
Sollen mehrere Gutschriften zugleich erzeugt werden, kannst du ... Zudem kannst du in diesem Menü festlegen, ob der Status des Auftrags geändert werden soll, nachdem die Dokumente erzeugt wurden. 
Neu: sollte das so gehen wie bei Retoure auch - beschreiben.
////

// TODO: Schritte anpassen
[.instruction]
Mehrere Gutschriften erzeugen:

. Öffne das Menü *Aufträge » Aufträge [Testphase]* » usw*.
. Nimm die Einstellungen anhand <<table-settings-fulfillment-credit-notes>> vor. +
_Beachte_, dass die Einstellungen sowohl *Suchfilter* als auch *Aktionen* umfassen.
. Klicke auf icon:settings[set=material], um die Gutschriften zu erzeugen. +
→ Es öffnet sich eine *PDF-Datei*, in der die zugehörigen Gutschriften aller von dir durch die Suchfilter bestimmten Aufträge enthalten sind.


[[table-settings-return]]
.Optionen beim Erfassen einer Gutschrift
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+^| *Einstellungen*

| *Status*
|Einen Status aus der Dropdown-Liste für die Gutschrift wählen. Voreingestellt ist der Standardstatus, der im Menü *Einrichtung » Aufträge » Einstellungen* gespeichert wurde.

| *Eigner*
|Einen Eigner aus der Dropdown-Liste wählen, der der Gutschrift zugewiesen wird.

| *Versandkosten*
|Wähle, ob die Versandkosten aus dem Hauptauftrag in die Gutschrift übernommen werden sollen. Die Option, die du für *Versandkosten in Gutschrift übernehmen* im Menü *Einrichtung » Aufträge » Einstellungen* gespeichert hast, ist voreingestellt. Du kannst die gespeicherte Einstellung anpassen. Wenn du JA wählst, werden die Versandkosten zum Warenkorb hinzugefügt.


2+^| *Artikel*

| *Artikel-ID*
|Die Artikel-ID wird angezeigt.

| *Varianten-ID*
|Die Varianten-ID wird angezeigt.

| *Menge*
|Die Menge wird angezeigt. - editable with validation

| *Verfügbare Menge*
|Die Verfügbare Menge wird angezeigt.

Klicke auf icon:add_shopping_cart[set=material], um weitere Artikel hinzuzufügen.


2+^| *Warenkorb*

| *Artikel-ID*
|Die Artikel-ID wird angezeigt.

| *Varianten-ID*
|Die Varianten-ID wird angezeigt.

| *Menge*
|Die Menge wird angezeigt. - editable with validation

| *Name der Artikelposition*
|Die Artikelposition ist editierbar.
|====

NEU: Die erstellte *Gutschrift* wird links in der Seitennavigation unter dem jeweiligen Auftrag angezeigt.
//// 
alte UI:
Wenn ein Gutschriftauftrag zu einem Auftrag angelegt wurde, wird im Tab *Übersicht* des Haupfauftrags rechts der Hinweis *Gutschrift verfügbar* angezeigt. Zusätzlich kannst du bereits angelegte Gutschriftaufträge im Tab *Übersicht* des Hauptauftrags über die Dropdown-Liste *Gutschrift / suchen* aufrufen.
////

[#create-credit-note-note]
=== Gutschriftbeleg erstellen

Nach dem Anlegen des Gutschriftauftrags muss ein Gutschriftbeleg direkt im Gutschriftauftrag erstellt werden. Vor dem ersten Erzeugen eines xref:auftraege:gutschriften-erzeugen.adoc#[Gutschriftbelegs] muss die Dokumentenvorlage im Menü *Einrichtung » Mandant » [Mandant wählen] » Standorte » [Standort wählen] » Dokumente » Gutschrift* eingerichtet werden.

Bevor du den Gutschriftbeleg des Gutschriftauftrags erzeugst, solltest du die im Gutschriftauftrag enthaltenen Auftragspositionen prüfen und bei Bedarf ändern.
//// 
[.instruction]
Gutschriftbeleg erstellen: alte UI

. Öffne den Gutschriftauftrag, für den ein Gutschriftbeleg erzeugt werden soll.
. Wähle die Option *Gutschrift* aus der Dropdown-Liste unter *Beleg / erstellen*.
. Klicke auf *Beleg erstellen*. +
→ Der Gutschriftbeleg wird erzeugt und in einem eigenen Tab geöffnet.
////

Erstellte Gutschriften weisen jeweils eine Referenz zu der Rechnung des dazugehörigen Auftrages auf. Im Portlet *Dokumente* eines Auftrags wird dies in der Benennung der Gutschrift angezeigt.


[#order-type-warranty]
== Gewährleistung

=== Auftragstyp Gewährleistung nutzen

Gewährleistungen sind xref:auftraege:auftraege-verwalten.adoc#400[Retouren] relativ ähnlich, denn in beiden Fällen bekommst du Waren eines Auftrags im *Status 7* wieder zurückgesendet. Im Gegensatz zur Retoure erwarten Kund:innen bei einer Gewährleistung aber entweder eine neue Lieferung oder eine Rückerstattung des Rechnungsbetrags mittels einer xref:auftraege:auftraege-verwalten.adoc#500[Gutschrift].
// TODO: xref prüfen

[TIP]
.Garantie vs. Gewährleistung
====
Im Gegensatz zur freiwillig erklärten Garantie handelt es sich bei der Gewährleistung um die *gesetzliche Pflicht* der Händler:innen, Mängel am Artikel, die bereits bei Lieferung bestanden haben, für Käufer:innen kostenlos zu beseitigen. Käufer:innen können die Gewährleistung gerichtlich bis zu 2 Jahre bei beweglichen Artikeln oder 3 Jahre bei unbeweglichen Artikeln geltend machen. Ab 6 Monaten nach Erhalt der Ware müssen Käufer:innen jedoch beweisen, dass die Mängel bereits bei Erhalt der Ware vorhanden war.
====

Wenn ein Gewährleistungsfall vorliegt, entscheidest du als Händler:in, ob du Käufer:innen die Kosten erstattest, den Artikel reparierst oder den Artikel austauschst. Soll ein Umtausch durchgeführt werden, lege eine *Gewährleistung* an. Möchtest du das Geld erstatten, lege eine xref:auftraege:auftraege-verwalten.adoc#500[Gutschrift] im Tab *Übersicht* der Gewährleistung an. Ob du die *Versandkosten* in einer Gewährleistung übernimmst oder nicht, wählst du in den xref:auftraege:grundeinstellungen.adoc#intable-shipping-costs-in-warranty[Grundeinstellungen] im Menü *Einrichtung » Aufträge » Einstellungen*.
// TODO: xref

[TIP]
.Einstellungen einer Gewährleistung
====
Wenn du eine Gewährleistung aus einem Auftrag heraus erzeugst, wird automatisch das *Versandprofil* des Auftrags übernommen. Die Einstellungen sind jedoch in der Gewährleistung änderbar. Bei *Lieferaufträgen* wird ebenfalls automatisch das korrekte Lager eingestellt. Die *Zahlungsart* bei Gewährleistungen ist änderbar.
====

[#create-warranty]
=== Gewährleistung anlegen

Normalerweise legst du eine Gewährleistung in einem bestehenden Retourenauftrag an. Es ist jedoch auch möglich, diese direkt aus dem zugrunde liegenden Hauptauftrag heraus anzulegen. +
Wird die Ware nach Lieferung beanstandet und du entscheidest dich beispielsweise aus Kostengründen gegen die Rücksendung der Ware, lege die Gewährleistung direkt im Hauptauftrag an. +
Möchtest du dagegen erst den Eingang der Retoure abwarten und die Ware prüfen, lege zunächst einen Retourenauftrag an und erstelle im Rahmen der Abwicklung dort eine Gewährleistung.


:ordertype: Gewährleistungen

[.instruction]
Eine Gewährleistung anlegen:

. Öffne das Menü *Aufträge » Aufträge [Testphase]*. +
→ Die Auftragsübersicht öffnet sich.
. Suche (icon:search[role="blue"]) den Auftrag, zu dem du eine Gutschrift anlegen möchtest.
. Öffne den gewünschten Haupt- oder Retourenauftrag. +
. Klicke auf auf Warenkorb (icon:shopping_cart[set=material]) *Aufträge erstellen* und wähle aus der Dropdown-Liste *Gewährleistung*.
. Wähle entweder die Option *Für alle Positionen* oder *Für bestimmte Positionen*.
Beachte dazu die Erläuterungen in <<tabelle-{ordertype}-anlegen>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Die Gewährleistung wird angelegt und erscheint links in der Navigation unter der Retoure oder dem Hauptauftrag.

Im Portlet *Historie* siehst du die Informationen: 
* Datum der Erstellung
* Benutzer
* die ausgeführte Aktion (hier: Neue Gewährleistung und darüber Warenbestandsautomatik) 
* geänderten Status.

[[table-settings-warranry]]
.Optionen beim Erfassen einer Gewährleistung
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+^| *Einstellungen*

| *Status*
|Einen Status aus der Dropdown-Liste für die Gewährleistung wählen. Voreingestellt ist der Standardstatus, der im Menü *Einrichtung » Aufträge » Einstellungen* gespeichert wurde.

| *Eigner*
|Einen Eigner aus der Dropdown-Liste wählen. Voreingestellt ist der aktuelle Benutzer.

// TODO: abgleichen
| *Versandkosten*
|Wähle, ob die Versandkosten aus dem Hauptauftrag in die Gewährleistung übernommen werden sollen (Versandkosten kopieren). Die Option, die du für *Versandkosten in Gewährleistung übernehmen* im Menü *Einrichtung » Aufträge » Einstellungen* gespeichert hast, ist voreingestellt. Du kannst die gespeicherte Einstellung anpassen.
* *JA* - die Versandkosten werden in den Warenkorb übernommen (nicht sichtbar).
* *NEIN* - die Versandkosten werden nicht in den Warenkorb übernommen.


2+^| *Artikel*

| *Artikel-ID*
|Die Artikel-ID wird angezeigt.

| *Varianten-ID*
|Die Varianten-ID wird angezeigt.

| *Menge*
|Die Menge wird angezeigt. - editable with validation

| *Verbleibende Stückzahl*
|Die Verbleibende Stückzahl wird angezeigt.

| *Offene Menge*
|Die Verfügbare Menge wird angezeigt.

| *Artikelname*
|Der Artikelname wird angezeigt.

Klicke auf icon:add_shopping_cart[set=material], um Artikel in den Warenkorb zu legen.


2+^| *Warenkorb* 

| *Artikel-ID*
|Die Artikel-ID wird angezeigt.

| *Varianten-ID*
|Die Varianten-ID wird angezeigt.

| *Menge*
|Die Menge wird angezeigt. - editable with validation

| *Artikelname*
|Der Artikelname wird angezeigt.

|====

[#edit-warranty]
=== Gewährleistung bearbeiten
 
Gewährleistungsaufträge werden in der Navigation unter Auftragssuche angezeigt. Öffne eine Gewährleistung, um beispielsweise einen zusätzlichen *Preis* einzugeben, wenn du dem Käufer einen höherpreisigen Artikel als Ersatz liefern willst. Falls nötig, können hier auch die Mengen der in der Gewährleistung enthaltenen Auftragspositionen verändert werden. Um eine Gewährleistung zu bearbeiten, gehe wie im Folgenden beschrieben vor.

[.instruction]
Gewährleistung bearbeiten:

. Öffne das Menü *Aufträge » Aufträge [Testphase]*.
. Gehe in die Auftragsübersicht.
. Wähle über das Symbol *Filter* im Filter *Auftragstyp* die Option *Gewährleistung*.
. Klicke auf *Suchen* (icon:search[role="blue"]). +
→ Es werden nur Gewährleistungen aufgelistet.
. Klicke in die Zeile der Gewährleistung, die du bearbeiten möchtest. +
→ Die Gewährleistung wird geöffnet.

//// 
Neu: Im Bereich *Allgemein* ändert sich der Auftragstyp zu *Gewährleistung*.
////

[#finish-warranty]
=== Gewährleistung abschließen

Zum Abschließen einer Gewährleistung musst du, wenn für die Ersatzware ein Aufpreis berechnet wird, eine Rechnung in der Gewährleistung erzeugen. Falls du keine Ersatzware versendest, sondern dich mit der Käufer:in auf einen nachträglichen Preisnachlass auf die beanstandete Ware einigst, legst du eine Gutschrift im Hauptauftrag an.

Um die Bearbeitung einer Gewährleistung durch einen Umtausch abzuschließen, gehe wie im Folgenden beschrieben vor.

[.instruction]
Gewährleistung durch Umtausch abschließen:

. Öffne in der *Gewährleistung* den Bereich *Dokumente*.
. Klicke auf das Symbol Dokument + *Dokument erstellen*.
. Wähle *Rechnung* aus der Liste *Dokument erstellen*. +
→ Ein neues Bearbeitungsfenster *Dokument erzeugen: Rechnung* öffnet sich. +
. Gib ein Datum und einen Kommentar ein.
//// 
Aktionen: Auftragsstatus ändern. 
. Wähle aus der Dropdown-Liste.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Die Rechnung wird erzeugt und in einem eigenen Tab geöffnet.
. Wechsle in den Bereich *?*.
////
. Klicke in der Zeile *Warenausgang* auf das Symbol *Warenausgang buchen*. +
→ Der Warenausgang wird gebucht und der *Status* wechselt automatisch zu *[7] Warenausgang gebucht*.
. Wechsle in das Menü *Aufträge » Aufträge [Testphase]*.
. Setze den Status der Gewährleistung manuell auf Status *[10] Gewährleistung*.
. *Speichere* (icon:save[role="green"]) die Einstellungen.


[TIP]
.Zahlungseingang bei Gewährleistungen buchen
====
Grundsätzlich müssen Zahlungen zu Gewährleistungen nur dann gebucht werden, wenn mit Käufer:innen ein Aufpreis vereinbart wurde. In diesem Fall buchst du den Zahlungseingang nach erfolgter Zahlung im Portlet *Zugeordnete Zahlung* der Gewährleistung.
====

Um die Bearbeitung einer Gewährleistung durch eine Gutschrift an den Käufer abzuschließen, gehe wie im Folgenden beschrieben vor:
//// 
[.instruction]
Gewährleistung durch Gutschrift abschließen:

. Öffne den Haupt- oder Retourenauftrag zur Gewährleistung, für die du eine Gutschrift anlegen möchtest.
. Öffne den Bereich *Übersicht*
. Klicke auf ? die Dropdown-Liste *Gutschrift* und dort auf die Einstellung *anlegen*. +
→ Der Gutschriftauftrag wird angelegt und in einem eigenen Fenster geöffnet.
////
Der weitere Bearbeitungsprozess läuft identisch mit dem regulären Anlegen einer Gutschrift und dem Erzeugen eines Gutschriftbelegs ab und wird im Kapitel xref:auftraege:auftraege-verwalten.adoc#500[Auftragstyp Gutschrift nutzen] detailliert beschrieben.



[#order-type-multi-order]
== Auftragstyp Sammelauftrag (Multi-Order) nutzen
// TODO: überarbeiten
Unbezahlte Aufträge können in einem Sammelauftrag zusammengefasst werden. Du kannst im Menü *Aufträge » Aufträge [Testphase]* oder im *???* eines Kontakts mit dem Suchfilter *Zahlungsstatus*, z.B. anhand eines Status im Bereich *[3] Warten auf Zahlung*, nach solchen unbezahlten Aufträgen suchen. Somit hast du zwei Möglichkeiten, Sammelaufträge zu erzeugen, die nachfolgend beschrieben werden.
Für beide Möglichkeiten übernimmst du im Menü *Aufträge » ?* noch nicht bezahlte Aufträge in einen Sammelauftrag. Im Bereich *?* des Sammelauftrags ist dann das Erzeugen von Sammelrechnungen möglich.


//// 
Tab *Sammelaufträge*
+- *Sammelaufträge generieren*
| *Kundenklasse*
|Wähle die Kundenklasse aus der Dropdown-Liste.
Voreinstellt ist *Standard-Kundenklasse*
Zeitraum: Haken setzen
Wenn ein Zeitraum angehakt ist, von _a_ bis _ eingeben, indem du in das leere Feld klickst. Der Kalender öffnet sich.
Über Icon Zahnrad Pfeil kannst du... (tooltip fehlt)

+- *Sammelgutschriften generieren*
| *Kundenklasse*
|Wähle die Kundenklasse aus der Dropdown-Liste.
Voreinstellt ist *Standard-Kundenklasse*
Zeitraum: Haken setzen
Wenn ein Zeitraum angehakt ist, von _a_ bis _ eingeben, indem du in das leere Feld klickst. Der Kalender öffnet sich.
Über Icon Zahnrad Pfeil kannst du... (tooltip fehlt)
////


[#basic-settings-multi-orders]
=== Grundeinstellungen für Sammelaufträge vornehmen

Im Menü *Einrichtung » Aufträge » Auftragstypen » Multi-Order* nimmst du die Grundeinstellungen für Sammelaufträge vor. Hier legst du beispielsweise fest, für welche Auftragstypen und Auftragsstatus Sammelaufträge angelegt werden können.

[.instruction]
Grundeinstellungen für Sammelaufträge vornehmen:

. Öffne das Menü *Einrichtung » Aufträge » Auftragstypen » Multi-Order*.
. Nimm die Einstellungen gemäß <<table-multi-order-settings>> vor.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[[table-multi-order-settings]]
.Grundeinstellungen für Sammelaufträge (Multi-Order)
[cols="1,3"]
|====
|Einstellung|Erläuterung

| *Auftragstypen*
|Die Auftragstypen wählen, die für Sammelaufträge verwendbar sein sollen. Eine Mehrfachauswahl ist möglich. Nur die aufgeführten Auftragstypen *Auftrag*, *Gewährleistung* und *Reparatur* sind als Sammelaufträge umsetzbar.

| *Artikeltext*
|Die Optionen für die Spalte *Artikeltext* der Artikelpositionen eines Sammelauftrags wählen. Eine Mehrfachauswahl ist möglich. Die gewählten Optionen werden für jeden Einzelauftrag separat im Sammelauftrag aufgelistet und ermöglichen eine Zuordnung zur Kund:in und zum Einzelauftrag.

| *Auftragssortierung*
|Wählen, wie die einzelnen Aufträge im Sammelauftrag sortiert sein sollen. Nur eine Auswahl ist möglich. Die Aufträge sind anhand der der Auftrags-ID (*Order ID aufsteigend* oder *Order ID absteigend*) oder dem Zeitpunkt des Warenausgangs (*Warenausgang aufsteigend* oder *Warenausgang absteigend*) sortierbar.

| *Auftragsstatus Aufträge*
|Wählen, in welchem Status sich Aufträge befinden müssen, um für Sammelaufträge berücksichtigt zu werden. Eine Mehrfachauswahl ist möglich. Um gezielt nur Aufträge zu erfassen, die für Sammelaufträge vorgesehen sind, empfehlen wir, je nach Anwendungsfall einen eigenen Auftragsstatus anzulegen.

| *Auftragsstatus Gutschriften*
|Wählen, in welchem Status sich xref:auftraege:auftraege-verwalten.adoc#500[Gutschriftaufträge] befinden müssen, um für Sammelgutschriften berücksichtigt zu werden. Eine Mehrfachauswahl ist möglich.
// TODO: xref anpassen
|====

Im Menü *Einrichtung » Aufträge » Einstellungen* kannst du mit der Option xref:auftraege:grundeinstellungen.adoc#intable-default-status-multi-order[Standard-Status Sammelauftrag] festlegen, welchen Auftragsstatus ein Sammelauftrag beim Anlegen erhalten soll. Standardmäßig steht dafür der Status *[13] Sammelauftrag* zur Verfügung. Wähle zudem mit der Option *Standard-Status Sammelgutschrift* einen Status für Sammelgutschriften aus. Standardmäßig steht dafür der Status *[14] Sammelgutschrift* zur Verfügung.
// TODO: xref anpassen


// TODO: auf neue UI anpassen, xref anpassen
[#820] 
=== Sammelauftrag pro Kundenklasse anlegen

Fallbeispiel: Ein Unternehmen möchte für die Mitarbeiter:innen monatlich die anfallenden Rechnungen in deinem Webshop bezahlen. Richte dafür eine eigene Kundenklasse ein. Mit der Kunden-ID in der vorgesehenen Kundenklasse wird die Rechnungsempfänger:in bestimmt. Diese Rechnungsempfänger:in erhält dann die Sammelrechnung, die direkt aus dem Sammelauftrag heraus erzeugt wird. +

Einen Sammelauftrag für eine bestimmte Kundenklasse sowie einen Zeitraum legst du im Menü *Aufträge » Sammelaufträge* an. Alle unbezahlten Aufträge der Kundenklasse werden somit gesammelt in einem Sammelauftrag abgelegt. Hinterlege in den Einstellungen der Kundenklassen anhand der Option *Kunden-ID*, welche Kund:in für die Kundenklasse als Eigner des Sammelauftrags sowie als Empfänger:in der Sammelrechnung aufgeführt werden soll. Je nach Anforderung empfiehlt es sich, eigene xref:crm:kontakte-verwalten.adoc#15[Kundenklassen] für Sammelaufträge anzulegen.

[.instruction]
Sammelauftrag für eine Kundenklasse anlegen:

. Öffne das Menü *Aufträge » Sammelaufträge*.
. Klicke auf das Icon + im Kasten ?? vor *Sammelaufträge generieren*
-> Öffne das Untermenü *Sammelaufträge generieren*.
. Wähle die *Kundenklasse* und optional einen *Zeitraum*. Der Zeitraum bezieht sich auf das Datum des Auftragseingangs.
. Klicke auf icon:execute[set=plenty]. +
→ Der Sammelauftrag wird angelegt.


[#create-multi-order-in-contacts]
=== Sammelauftrag pro Kontakt anlegen

Eine Kund:in möchte nicht jede Rechnung einzeln bezahlen, sondern pro Monat oder pro Quartal bezahlen. +
In diesem Fall legst du einen Sammelauftrag für einen bestimmten Kontakt direkt im Kontaktdatensatz im Menü *CRM » Kontakte* an. Öffne dazu einen Kontakt.
//// 
alte UI: wähle links im Menü die Option *Neuer Sammelauftrag*. Anschließend wird automatisch ein Sammelauftrag generiert, der alle unbezahlten Aufträge des Kontakts enthält.
// TODO: erklären lassen wie in neuer UI

[TIP]
.Aufträge prüfen
====
Um sicher zu gehen, dass geeignete Aufträge für die Erzeugung eines Sammelauftrags vorhanden sind, suche im Tab *Aufträge* der Kund:in nach unbezahlten Aufträgen.
====
////

[#840]
=== Sammelrechnung generieren
// TODO: überarbeiten
Die Erstellung von Sammelrechnungen ist nur in den dazugehörigen Sammelaufträgen möglich. Richte zuerst eine xref:auftraege:auftragsdokumente.adoc#[Dokumentenvorlage] für Sammelrechnungen im Menü *Einrichtung » Mandant » OrderPayment Powershop (beta) » Standorte » [Standort wählen] » Dokumente » Sammelrechnung* ein. In diesem Menü kannst du das Dokument detailliert einstellen sowie eine Dokumentenvorlage in Form einer PDF-Datei hinterlegen. In der Grundeinstellung der Vorlage sind bereits Standardwerte hinterlegt, die du bei Bedarf durch Kopie aus einer anderen Vorlage, z.B. der Dokumentenvorlage *Rechnung*, mit geringem Aufwand weiter vervollständigen kannst.

Sammelrechnung
* Grundeinstellungen: Sammelrechnung
* Seitenränder
* Positionierung der Pflichtelemente
* Spalten Artikelpositionen
* Summen
* Optionale Elemente
* Optionale Elemente unter Artikelpositionstabelle

////
siehe auch: https://knowledge.plentymarkets.com/de-de/manual/main/auftraege/best-pratices.html#_was_du_brauchst
////

[.instruction]
Sammelrechnung erzeugen:

. Öffne das Menü *Aufträge » Aufträge [Testphase]*. +
→ Die Auftragsübersicht öffnet sich.
. Suche (icon:search[role="blue"]) anhand der Filtereinstellungen den Sammelauftrag, für den eine Sammelrechnung erzeugt werden soll.
. Öffne den Sammelauftrag.
//// 
. Wechsle in das Tab *Belege*. +
. Wähle aus der Dropdown-Liste *Beleg erstellen* das Dokument *Sammelrechnung* aus. +
. Nimm die Einstellungen anhand <<table-orders-generate-multi-invoice>> vor. +
. *Speichere* (icon:plus-square[role="green"]) die Einstellungen, um die Sammelrechnung zu erzeugen. +
→ Es öffnet sich eine *PDF-Datei* mit der soeben erzeugten Sammelrechnung.
////

[[table-orders-generate-multi-invoice]]
.Einstellungen für Sammelrechnungen
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Datum*
|Gib das Datum an, das als Rechnungsdatum auf dem Dokument angezeigt wird. Standardmäßig ist das aktuelle Datum voreingestellt.

|*Nummer*
|Die Nummer des Dokuments wird automatisch vergeben. Hier muss keine Angabe gemacht werden.

|*Rechnungen der Aufträge generieren*
|Mit *JA* oder *NEIN* auswählen, ob die einzelnen Rechnungen zu den im Sammelauftrag enthaltenen Aufträgen ebenfalls generiert werden sollen.

| *Buche Warenausgang*
|Mit *JA* oder *NEIN* auswählen, ob mit dem Erzeugen der Sammelrechnung auch der Warenausgang gebucht werden soll.

| *Ändere Auftragsstatus auf Status*
|Einen Status wählen, in den der Auftrag nach dem Erzeugen der Sammelrechnung wechseln sollen. Wenn kein Statuswechsel gewünscht ist, die Option *Keine Änderung* wählen.

| *Kommentar*
|Einen Text eingeben, der auf der Sammelrechnung unterhalb der Artikelpositionen angezeigt wird. Die Eingabe ist optional.
|====

[IMPORTANT]
.Zahlungseingänge bei Sammelaufträgen
====
Wird eine Sammelrechnung bezahlt und der Sammelauftrag als bezahlt markiert, werden die Zahlungseingänge *nicht* automatisch an den einzelnen im Sammelauftrag zusammengefassten Aufträgen gebucht. Zahlungseingänge musst du an den einzelnen Aufträgen manuell buchen.
====
//// 
[.discrete]
==== Sammelrechnung über Ereignisaktion generieren

Mithilfe der in plentymarkets verfügbaren Ereignisaktionen kannst du die Sammelrechnung automatisiert generieren, sobald ein Sammelauftrag angelegt wird. Gehe dazu wie nachfolgend beschrieben vor:

:table-event-procedure: <<table-event-procedure-multi-invoice-automatic>>
include::_includes:page$EA.adoc[]

[[table-event-procedure-multi-invoice-automatic]]
.Ereignisaktion "Sammelrechnung automatisch generieren"
[cols="1,3"]
|====
|Einstellung|Auswahl

| *Ereignis*
|

| *Auftragsanlage > Neuer Sammelauftrag*
|

| *Aktion*
|

| *Dokumente > Sammelrechnung erzeugen* +
|

|====


[#850]
=== Sammelgutschrift generieren

Eine Sammelgutschrift erzeugst du im Menü *Aufträge » Sammelaufträge*. +
Alle Gutschriften der ausgewählten Kundenklasse werden gesammelt in einer Sammelgutschrift abgelegt. Diese Sammelgutschrift ist wie Sammelaufträge auch nach Erstellung in der Auftragsübersicht bearbeitbar. Je nach Anwendungsfall empfehlen wir, eigene xref:crm:kontakte-verwalten.adoc#15[Kundenklassen] für Sammelgutschriften anzulegen.

[.instruction]
Sammelgutschrift für eine Kundenklasse generieren:

. Öffne das Menü *Aufträge » Sammelaufträge*.
. Öffne das Untermenü *Sammelgutschriften generieren*.
. Wähle die *Kundenklasse* aus.
. Wähle optional einen *Zeitraum*. Der Zeitraum bezieht sich auf das Datum des Gutschrifteingangs.
. Klicke auf icon:execute[set=plenty]. +
→ Die Sammelgutschrift wird angelegt.

[#860]
=== Dokument Sammelgutschrift generieren

Die Erstellung des Dokuments Sammelgutschrift ist nur im dazugehörigen Auftragstyp Sammelgutschrift möglich. Richte zuerst eine Dokumentenvorlage für Sammelgutschriften im Menü *Einrichtung » Mandant » [Mandant wählen] » Standorte » [Standort wählen] » Dokumente » Sammelgutschrift* ein. In diesem Menü kannst du das Dokument detailliert einstellen sowie eine Dokumentenvorlage in Form einer PDF-Datei hinterlegen. In der Grundeinstellung der Vorlage sind bereits Standardwerte hinterlegt, die du bei Bedarf durch Kopie aus einer anderen Vorlage, z.B. der Dokumentenvorlage Gutschrift, mit geringem Aufwand weiter vervollständigen kannst.

Anschließend kannst du im Tab *Belege* der Sammelgutschrift das Dokument Sammelgutschrift generieren. Gehe dafür wie im Folgenden beschrieben vor.

[.instruction]
Dokument Sammelgutschrift erzeugen:

. Öffne das Menü *Aufträge » Aufträge [Testphase]*. +
→ Die Auftragsübersicht öffnet sich.
. Suche (icon:search[role="blue"]) anhand der Filtereinstellungen die Sammelgutschrift, für die ein Dokument Sammelgutschrift erzeugt werden soll.
. Öffne die Sammelgutschrift.
. Wechsle in das Tab *Belege*. +
. Wähle aus der Dropdown-Liste *Beleg erstellen* das Dokument *Sammelgutschrift* aus. +
. Nimm die Einstellungen anhand <<table-orders-generate-document.multi-credit-note>> vor. +
. *Speichere* (icon:plus-square[role="green"]) die Einstellungen, um das Dokument Sammelgutschrift zu erzeugen. +
→ Es öffnet sich eine *PDF-Datei* mit der soeben erzeugten Sammelgutschrift.

[[table-orders-generate-document.multi-credit-note]]
.Einstellungen für Dokument Sammelgutschrift
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Datum*
|Gib das Datum an, das als Gutschriftsdatum auf dem Dokument angezeigt wird. Standardmäßig ist das aktuelle Datum voreingestellt.

|*Nummer*
|Die Nummer des Dokuments wird automatisch vergeben. Hier muss keine Angabe gemacht werden.

| *Buche Warenausgang*
|Mit *JA* oder *NEIN* auswählen, ob mit dem Erzeugen der Sammelgutschrift auch ein Warenausgang gebucht werden soll.

| *Ändere Auftragsstatus auf Status*
|Einen Status wählen, in den der Auftrag nach dem Erzeugen der Sammelgutschrift wechseln sollen. Wenn kein Statuswechsel gewünscht ist, die Option *Keine Änderung* wählen.

| *Kommentar*
|Einen Text eingeben, der auf der Sammelgutschrift unterhalb der Artikelpositionen angezeigt wird. Die Eingabe ist optional.

|====
////


[#order-type-advance-order]
== Auftragstyp Vorbestellung nutzen

Vorbestellungen sind im Online-Handel ein wichtiges Instrument im Marketing-Mix. Meist können Artikel noch vor der tatsächlichen Verfügbarkeit zum günstigen Einführungspreis bestellt werden. Für eine Warenwirtschaft stellt diese Situation einen Sonderfall dar, da noch nicht verfügbare Artikel noch keinen Lagerbestand haben können.

Vorbestellungen sind in plentymarkets sehr einfach zu erstellen. Es gibt dafür den Auftragstyp *Vorbestellung*, den du bei manuell erfassten Aufträgen verwenden kannst.
// TODO: anpassen auf neue UI

Um Vorbestellungen über den Webshop entgegennehmen zu können, sind das Erscheinungsdatum und die Artikelverfügbarkeit notwendig. Nimm dazu die auf dieser Seite beschriebenen Einstellungen am Artikel vor.


[IMPORTANT]
.Manuelle Auftragseingabe
====
Der Auftragstyp *Vorbestellung* kann nur bei manueller Auftragseingabe gewählt werden.
====

//// 
[#1110]
=== Erscheinungsdatum

Die Option *Erscheinungsdatum* findest du in der Artikelbearbeitung im Tab *Verfügbar*. Hier kannst du über einen Kalender das Datum hinterlegen, zu dem der Artikel verfügbar sein wird. Gehe dazu wie im Folgenden beschrieben vor.

[.instruction]
Erscheinungsdatum eintragen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Öffne einen Artikel, den du vorbestellbar machen musst.
. Öffne die Variante, die vorbestellbar ist.
. Im Tab *Einstellungen* der Variante scrolle in den Abschnitt *Verfügbarkeit*.
. Trage bei *Erscheinungsdatum* das Datum ein, ab dem der Artikel verfügbar sein soll.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

Im nächsten Schritt sorge dafür, dass das Erscheinungsdatum deinen Kunden angezeigt wird. Gehe dazu wie im Folgenden beschrieben vor.

[.instruction]
Erscheinungsdatum im Webshop sichtbar machen:

. Öffne das Menü *CMS » Webdesign » Ordner: Layout » Ordner: ItemView*.
. Öffne das Template *ItemViewSingleItem*.
. Füge die Template-Variable *$ReleaseDate* ein.
. *Speichere* die Einstellungen.

[#1120]
=== Artikelverfügbarkeit

Eine weitere Voraussetzung ist die korrekte Einstellung der *Artikelverfügbarkeit*. Gehe dazu wie im Folgenden beschrieben vor.

[.instruction]
Artikelverfügbarkeit für Vorbestellungen einstellen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Öffne einen Artikel, den du vorbestellbar machen möchtest.
. Wechsle in das Tab *Einstellungen*.
. Wähle für die Option *Beschränkung* die Einstellung *Keine Beschränkung*. +
→ Der Artikel kann nun ohne tatsächlichen Bestand vorbestellt, also gekauft werden.

[TIP]
.Maximale Bestellmenge
====
Damit andere Online-Händler:innen deine Vorbestellungen nicht dazu missbrauchen können, deine Bestände zum günstigen Preis komplett aufzukaufen, trage im *Tab Verfügbar* bei der Option *Maximale Bestellmenge* einen Wert ein. Trage dort den Wert *1* ein und der Artikel kann pro Bestellung nur ein einziges Mal gekauft werden. Setze die maximale Abgabemenge auf den Wert *0*, um ohne Beschränkung zu verkaufen.
====
////


[#create-order-from-offer]
=== Auftrag über ein Angebot anlegen

In einem bestehenden Angebot kannst du über icon:shopping_cart[set=material] *Auftrag* einen neuen Auftrag anlegen. +
Die Besonderheit ist, dass du bei Menge eine beliebige Menge eingeben kannst. Der neue *Auftrag* wird dir in der Navigation unter dem Angebot in blauer Schrift angezeigt sowie im Bereich *Auftragsreferenzen*.

// TODO: Text auf neue UI anpassen
[.instruction]
Auftrag aus Angebot anlegen

. Öffne das Menü *Aufträge » Aufträge [Testphase]*.
. Gehe in die Auftragsübersicht.
. Wähle über das Symbol *Filter* im Filter *Auftragstyp* die Option *Angebot*.
. Klicke auf *Suchen* (icon:search[role="blue"]). +
→ Es werden nur Angebote aufgelistet.
. Klicke in das Angebot, aus dem heraus du einen Auftrag anlegen möchtest.
. Klicke auf icon:shopping_cart[set=material], um einen *Auftrag* anzulegen.
. Wähle *Für alle Positionen* oder *Für bestimmte Positionen*.
→ Ein neuer Auftrag wird geöffnet. +
Nachricht grün hinterlegt: Auftrag erfolgreich erstellt

[[table-order-from-offer]]
.Auftrag aus Angebot
[cols="1,3"]
|====
|Einstellung |Erläuterung
// TODO: Text auf neue UI anpassen

2+^| *Einstellungen*

| *Status*
|Wähle einen Status aus der Dropdown-Liste. 

| *Eigner*
|Wähle einen Eigner aus der Dropdown-Liste. +
Angezeigt wird der aktuelle Nutzer.

Über icon:playlist_add[set=material] *Füge alle offenen Mengen in den Warenkorb* kannst du mit einem Klick alle Mengen in den Warenkorb fügen.


2+^| *Artikel*

| *Artikel-ID*
|Die Artikel-ID wird angezeigt.
 
| *Varianten-ID*
|Die Varianten-ID wird angezeigt.
 
| *Menge*
|Die Menge wird angezeigt. (Validierung)
 
| *Verbleibende Stückzahl*
|Die Verbleibende Stückzahl wird angezeigt. +
Die *verbleibende Stückzahl* zeigt dir an, wie viele Artikel du noch übernehmen kannst bzw. wie viele du dem aktuellen Lieferauftrag noch hinzugefügen kannst.
 
| *Offene Menge*
|Die Offene Menge wird angezeigt. +
Die *Offene Menge* zeigt dir an, wie viele Artikel nicht in den Lieferauftrag überführt werden können.
 
| *Verfügbarer Warenbestand*
|Der Verfügbare Warenbestand wird angezeigt.
 
| *Artikelname*
|Der Artikelname wird angezeigt.
 
Klicke auf icon:add_shopping_cart[set=material], um weitere Artikel hinzuzufügen.

 
2+^| *Warenkorb*
 
| *Artikel-ID*
|Die Artikel-ID wird angezeigt.
 
| *Varianten-ID*
|Die Varianten-ID wird angezeigt.
 
| *Menge*
|Die Menge wird angezeigt. +
Die Menge kann hier verändert werden und beliebig hoch sein.
////
|*Menge*
|Gib die Menge ein, in der der Artikel dem Warenkorb hinzugefügt werden soll. Du kannst nur ganze Zahlen eingeben, negative Mengen oder Mengen, die den Nettobestand übersteigen, sind nicht erlaubt. In diesem Fall wird eine Fehlernachricht angezeigt. Wenn die hinzugefügte Menge den Nettobestand auf = oder niedriger setzt, wird der Statusbalken für die Bestandsanzeige auf rot gesetzt. +
Bei Mengenänderungen ändert sich der Verkaufspreis, daher muss der Verkaufspreis aktualisiert werden. Klicke dafür auf *Verkaufspreis aktualisieren* (icon:refresh[set=material]). Nach der Aktualisierung ist die Warenkorb-Schaltfläche (icon:add_shopping_cart[set=material]) wieder verfügbar und die Artikel können hinzugefügt werden. +
////

| *Artikelname*
|Der Artikelname wird angezeigt.
|====


[[table-delivery-order]]
.Auftrag aus Angebot
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+^| *Einstellungen*

| *Status*
|Wähle einen Status aus der Dropdown-Liste. 

| *Eigner*
|Wähle einen Eigner aus der Dropdown-Liste.
Angezeigt wird der aktuelle Nutzer.

Symbol 3 Striche mit +

2+^| *Artikel*

| *Artikel-ID*
|Die Artikel-ID wird angezeigt.

== geteilter Auftrag

Beim Teilen eines Auftrags wählst du Artikelpositionen, mit denen ein neuer Auftrag angelegt wird, der diese Positionen enthält. Der neu angelegte Auftrag kann wiederum geteilt werden. Der usprüngliche Auftrag bleibt erhalten, es werden nur die gewählten Artikelpositionen entfernt. Für jeden geteilten Auftrag stehen alle Bearbeitungsmöglichkeiten zur Verfügung.

////
Tabelle 21 unter https://knowledge.plentymarkets.com/de-de/manual/main/auftraege/auftraege-verwalten.html#intable-splitting-orders
////

Im Menü *Einrichtung » Aufträge » Auftragstypen » Lieferauftrag* legst du vorab fest, nach welchem Kriterium Aufträge in Lieferaufträge gesplittet werden.

[.instruction]
Optionen für das Splitten von Aufträgen in Lieferaufträge wählen:

. Öffne das Menü *Einrichtung » Aufträge » Auftragstypen » Lieferauftrag*.
. Nimm die Einstellungen anhand von <<table-order-types-delivery-order-options>> vor.
. *Speichere* (icon:save[role="green"]) die Einstellungen.


[[table-order-types-delivery-order-options]]
.Optionen für das *Splitten von Aufträgen in Lieferaufträge*
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+^| *Aufträge in Lieferaufträge splitten nach*

| *Aus*
|Es erfolgt *keine Aufsplittung*. +
*_Achtung_*: Wenn du diese Option aktivierst, können Lieferaufträge nur noch manuell angelegt werden. Das automatische Generieren sowie das Erstellen von Lieferaufträgen per Ereignisaktion sind bei dieser Auswahl nicht möglich.

| *Lager*
|Die Lieferaufträge werden anhand der verschiedenen *Lager* der Auftragspositionen erstellt.

| *Versandprofil*
|Die Lieferaufträge werden anhand der verschiedenen *Versandprofile* der Auftragspositionen erstellt.

| *Lager und Versandprofil*
|Die Lieferaufträge werden anhand der verschiedenen *Lager und der Versandprofile* der Auftragspositionen erstellt.

| *Lager und Netto-Warenbestand*
|Die Lieferaufträge werden anhand der verschiedenen *Lager und des Netto-Warenbestands* der Auftragspositionen erstellt.
|====


[[table-settings-split-order]]
.Optionen beim Erfassen eines geteilten Auftrags
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+^| *Einstellungen*

| *Eigner*
|Einen Eigner aus der Dropdown-Liste wählen. Voreingestellt ist der aktuelle Benutzer.

| *Status*
|Einen Status aus der Dropdown-Liste für die Gutschrift wählen. Voreingestellt ist der Standardstatus, der im Menü *Einrichtung » Aufträge » Einstellungen* gespeichert wurde.

2+^| *Artikel*

| *Artikel-ID*
|Die Artikel-ID wird angezeigt.

| *Varianten-ID*
|Die Varianten-ID wird angezeigt.

| *Menge*
|Die Menge wird angezeigt. - editable with validation

| *Verfügbare Menge*
|Die Verfügbare Menge wird angezeigt.

| *Name der Artikelposition*
|Die Artikelposition wird angezeigt.

Klicke auf icon:add_shopping_cart[set=material], um Artikel in den Warenkorb zu legen.

2+^| *Warenkorb*

| *Artikel-ID*
|Die Artikel-ID wird angezeigt.

| *Varianten-ID*
|Die Varianten-ID wird angezeigt.

| *Menge*
|Die Menge wird angezeigt. - editable with validation

| *Name der Artikelposition*
|Die Artikelposition ist editierbar.
|====