= Aufträge verwalten
:keywords: Auftrag, Auftrag, Auftrag, Aufträge, Aufträge, Aufträge, Auftrags-ID, Auftragsabwicklung, Auftragsbearbeitung, Auftrag, Aufträge, Auftrag bearbeiten, Aufträge bearbeiten, Auftragsstatus, Status, Standardstatus, Auftragstyp, Auftrags-Typ, Auftragsart, Lieferauftrag, Lieferaufträge, Auftragsanlage, manuelle Auftragsanlage, Retoure, retournieren, Retouren, Retoure erstellen, Retoure anlegen, Gutschrift, Gewährleistung, Garantie, Reparatur, Reparaturauftrag, Sammelauftrag, Multi-Order, Multiorder, Multiauftrag, Multi-Auftrag, Sammelaufträge, Sammelauftrag, Vorbestellung, Vorbestellungen, Auftragssuche, Auftrag suchen, Auftrag filtern, Auftragsübersicht, Auftragsansicht, Auftrag anlegen, Auftrag erstellen, Auftragsdokument, Auftragsposition, Auftragseingang, Rechnung, Retourengründe, Retourengrund, Rückerstattung, Rückzahlung, Artikelmenge, Umtausch, Zahlungseingang, Warenausgang, Hauptauftrag, Retourenauftrag, Storno, Stornierung, Stornierungsbeleg, Stornobeleg, Korrektur, Korrekturbeleg, Auftragshistorie, Historie, Statushistorie, Lieferland, Auftragsbestätigung, Auftragsdetails, Sammelrechnung, Zahlungsbedingungen
:author: team-order-core
:description: Erfahre alles rund um das Thema Auftragsverwaltung und lerne, wie du Aufträge anlegst, mit Auftragstypen und Auftragsstatus arbeitest oder Auftragsdokumente anlegst. Beachte, dass diese Seite die veraltete Auftrags-UI beschreibt, die bald durch die neue Auftrags-UI abgelöst wird.

Aufträge bilden deine Verkäufe sowie damit einhergehende und übliche Geschäftsvorfälle ab. Mithilfe von Auftragstypen werden die unterschiedlichen Geschäftsvorfälle kenntlich gemacht. Fortschritte bei der Bearbeitung eines Auftrags werden durch xref:auftraege:auftraege-verwalten.adoc#1200[Auftragsstatus] angezeigt. Welche Möglichkeiten dir Auftragstypen und Auftragsstatus bieten und wie du Aufträge abwickelst, erfährst du in den folgenden Beschreibungen. Alle Aufträge werden zentral und in einem einheitlichen Format erfasst. Bereits in der xref:auftraege:auftraege-verwalten.adoc#1400[Auftragsübersicht] siehst du wichtige Informationen auf einen Blick und kannst einige Arbeiten direkt ausführen.

[#100]
== Allgemeines zur Auftragsanlage in plentymarkets

In plentymarkets wird ein Auftrag automatisch angelegt, wenn Kund:innen Bestellungen in deinem Webshop oder auf einem angebundenen Marktplatz tätigen. Unterschiedliche Geschäftsvorfälle wie xref:auftraege:auftraege-verwalten.adoc#300[Lieferaufträge], xref:auftraege:auftraege-verwalten.adoc#400[Retouren], xref:auftraege:auftraege-verwalten.adoc#500[Gutschriften], xref:auftraege:auftraege-verwalten.adoc#600[Gewährleistungen] und xref:auftraege:auftraege-verwalten.adoc#700[Reparaturen] werden mithilfe eigener Aufträge verschiedener Typen abgebildet, die immer mit dem Hauptauftrag verbunden sind. Über die xref:auftraege:auftraege-verwalten.adoc#1400[Auftragsübersicht] lassen sich Aufträge ungeachtet der xref:auftraege:auftragsherkunft.adoc#[Auftragsherkunft] öffnen und bearbeiten. Für viele Auftragstypen, wie zum Beispiel xref:auftraege:auftraege-verwalten.adoc#300[Lieferaufträge], ist das Einrichten von xref:automatisierung:ereignisaktionen.adoc#[Ereignisaktionen] sinnvoll, um Vorgänge zu automatisieren. Einige Beispiele für die Nutzung von Ereignisaktionen für die Auftragsabwicklung werden in den folgenden Kapiteln erläutert. +
Aufträge, die nicht über den Webshop oder einen Marktplatz bei dir eingehen, legst du xref:auftraege:auftraege-verwalten.adoc#200[manuell] im System an. Das ist beispielsweise bei telefonischen oder E-Mail-Bestellungen sowie bei Barverkäufen der Fall.

Passe die xref:auftraege:grundeinstellungen.adoc#[Grundeinstellungen] im Menü *Einrichtung » Aufträge » Einstellungen* an, bevor du die ersten Aufträge in deinem plentymarkets System abwickelst. Speichere die Grundeinstellungen auch dann einmalig ab, wenn du die voreingestellten Werte nicht verändert hast.

[#200]
== Aufträge manuell anlegen

Wie du Aufträge im System anlegst, z.B. wenn eine Bestellung per Telefon getätigt wird, ist in den folgenden Kapiteln beschrieben. Die folgenden Möglichkeiten stehen dir für die Auftragsanlage in plentymarkets zur Verfügung:

* Über einen <<#create-order-via-cash-sale, Barverkauf>>
* Über <<#create-order-via-order, Aufträge>>
* Über <<#create-order-via-contact, Kontakte>>

*_Tipp:_* Die Vorgehensweise für Angebote ist identisch. Wähle im ersten Schritt der Auftragsanlage für die Einstellung *Auftragstyp* die Option *Angebot*, um ein Angebot zu erstellen.

[NOTE]
.Vorgehensweise für Auftragsanlage über neue Auftrags-UI
======
Auf dieser Seite wird die Auftragsanlage über das Menü *Aufträge » Aufträge (Testphase)* beschrieben, da die Vorgehensweise über das Menü *Aufträge » Aufträge bearbeiten* veraltet ist.
======

[IMPORTANT]
.E-Mail-Versand
====
Bei manuell angelegten Aufträgen wird keine automatische E-Mail, z.B. als Auftragsbestätigung, an Kund:innen versendet. Grund dafür ist, dass das System nicht wissen kann, wann die Einstellungen zu diesem Auftrag vorgenommen wurden. Stoße daher den Versand einer xref:crm:emailbuilder.adoc#[E-Mail-Vorlage] manuell im Auftrag über die Funktion *E-Mail-Service* an.
====

[#create-order-via-cash-sale]
=== Auftrag oder Angebot über Barverkauf anlegen

Im Menü *CRM » Kontakte* hast du die Möglichkeit, Barverkäufe über das Kundenprofil *Barverkauf* abzuwickeln. Das Kundenprofil *Barverkauf* erlaubt dir, Aufträge ohne Kundenzuordnung anzulegen. Das Kundenprofil *Barverkauf* ist in deinem System standardmäßig eingerichtet.

[WARNING]
.Zahlungsart und Auftragsdokumente bei Barverkäufen
====
Achte darauf, bei der Auftragsanlage über Barverkauf in den *Auftragsdaten* die passende *Zahlungsart* auszuwählen. Zudem findet bei dieser Art der Auftragsanlage keine Zuordnung zu einem in deinem System gespeicherten Kund:innen statt. Generiere deshalb die benötigten xref:auftraege:auftragsdokumente.adoc#[Auftragsdokumente], wie die Rechnung, direkt während der Abwicklung des Barverkaufs manuell im Bereich *Dokumente* des Auftrags.
====

[.instruction]
Auftrag oder Angebot über Barverkauf anlegen:

. Öffne das Menü *CRM » Kontakte*.
. Gib im Suchfeld *ID* die gewünschte ID ein. +
→ Eine Liste der Suchergebnisse wird eingeblendet.
. Wähle *Barverkauf* aus der *Ergebnisliste*. +
→ Das Kundenprofil für Barverkäufe mit der gesuchten ID wird geöffnet.
. Gehe in den Bereich *Aufträge*.
. Klicke rechts auf *Optionen* (material:add[]).
. Wähle die Option *Neuer Auftrag* oder *Neues Angebot*. +
→ Die Übersicht zum Erstellen eines neuen Auftrags oder eines neuen Angebots wird geöffnet.
. Nimm die Einstellungen vor. Beachte dazu die Erläterungen zur <<#create-order-or-offer, Anlage von Aufträgen oder Angeboten>>.

[#create-order-via-order]
=== Auftrag oder Angebot über Aufträge anlegen

Im Menü *Aufträge » Aufträge (Testphase)* kannst du sowohl in der Auftragsübersicht als auch in der Detailansicht eines Auftrags neue Aufträge oder Angebote anlegen. Gehe dazu vor wie folgt.

[.instruction]
Auftrag oder Angebot über Aufträge anlegen:

. Öffne das Menü *Aufträge » Aufträge (Testphase)*.
. Führe die Suche (material:search[]) aus, um Aufträge anzuzeigen.
. Klicke links in der Seitennavigation auf (material:add[role=skyBlue]) *Neuer Auftrag*. +
*_Tipp:_* Möchtest du anstatt eines Auftrags ein Angebot anlegen, wähle im ersten Schritt für den *Auftragstyp* die Option *Angebot*. +
icon:map-signs[] *_Oder:_* Öffne in der Auftragsübersicht den Auftrag der Kund:in, für die du einen neuen Auftrag anlegen möchtest.
. Klicke unten in der Seitennavigation auf die *Kontakt-ID*. +
→ Der Auftrag wird im Menü *CRM » Kontakte* geöffnet.
. Gehe in den Bereich *Aufträge*.
. Klicke rechts auf *Optionen* (material:add[]).
. Wähle die Option *Neuer Auftrag* oder *Neues Angebot*. +
→ Die Übersicht zum Erstellen eines neuen Auftrags oder eines neuen Angebots wird geöffnet.
. Nimm die Einstellungen vor. Beachte dazu die Erläterungen zur <<#create-order-or-offer, Anlage von Aufträgen oder Angeboten>>.

[#create-order-via-contact]
=== Auftrag oder Angebot über Kontakte anlegen

Aufträge oder Angebote kannst du auch über die Kontaktübersicht oder die Detailansicht eines Kontakts im Menü *CRM » Kontakte* anlegen. Nimm dazu zunächst die <<#carrying-out-standard-settings, Standardeinstellungen>> vor.

[.instruction]
Auftrag oder Angebot über Kontakte anlegen:

. Öffne das Menü *CRM » Kontakte*.
. Suche den Kontakt anhand der Filtereinstellungen. Beachte dazu die Erläuterungen zu den Filtern auf der Seite xref:crm:kontakt-suchen.adoc#[Kontakt suchen]. +
→ Die Kontakte, die den Suchkriterien entsprechen, werden angezeigt.
. Klicke in der Zeile des Kontakts rechts auf material:more_vert[].
. Navigiere zu material:shopping_cart[] *Aufträge* > *Neuer Auftrag* oder *Neues Angebot*. +
icon:map-signs[] *_Oder:_* Öffne einen Kontakt.
. Klicke im Bereich *Aufträge* rechts auf material:add[] *Optionen*.
. Navigiere zu *Neuer Auftrag* oder *Neues Angebot*.
→ Du wirst automatisch zu den Auftragsdetails für den neuen Auftrag bzw. das neue Angebot weitergeleitet.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen zur <<#create-order-or-offer, Anlage von Aufträgen oder Angeboten>>.

[#carrying-out-standard-settings]
==== Standardeinstellungen vornehmen

Beim Anlegen von Aufträgen und Angeboten über die Kontaktübersicht werden Daten, wie zum Beispiel Adressen oder Mandanten, direkt aus dem Kontakt übernommen, wenn sie dort hinterlegt sind. Die Kontaktdaten haben in der Regel also Priorität. Zusätzlich stehen dir einige Standardeinstellungen zur Verfügung, auf die zurückgegriffen wird, wenn eine Information nicht aus dem Kontakt genommen wird. +
Um die Auftragsanlage zu erleichtern und schneller vorgehen zu können, solltest du zunächst diese Standardeinstellungen festlegen. *_Beachte_*, dass die Standardeinstellungen auch für über diese Benutzeroberfläche angelegte Angebote gelten. Gehe folgendermaßen vor, um die Standardeinstellungen vorzunehmen.

[.instruction]
Standardeinstellungen vornehmen:

. Öffne das Menü *Einrichtung » Aufträge » Auftragstypen » Auftrag*.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<table-default-settings-order-contact>>.
. *Speichere* (material:save[role=green]) die Einstellungen.

[[table-default-settings-order-contact]]
.Standardeinstellungen für die Auftragsanlage
[cols="1,3"]
|===
|Einstellung |Erläuterung

|[#intable-standard-eigner]*Standard-Eigner*
|Wählst du einen Standard-Eigner, ist dieser in den Auftragsdetails des neuen Auftrags oder Angebots standardmäßig vorausgewählt. Der Eigner wird generell nicht aus den Kontaktdaten übernommen.

|[#intable-standard-mandant]*Standard-Mandant*
|Der hier ausgewählte Standard-Mandant ist beim Anlegen des neuen Auftrags oder Angebots vorausgewählt, wenn in den Kontaktdaten kein Mandant hinterlegt ist. Ist in den Kontaktdaten ein Mandant hinterlegt, hat dieser Priorität.

|[#intable-standard-herkunft]*Standard-Herkunft*
|Die hier ausgewählte Standard-Herkunft ist beim Anlegen des neuen Auftrags oder Angebots vorausgewählt, wenn in den Kontaktdaten keine Herkunft hinterlegt ist. Ist in den Kontaktdaten eine Herkunft hinterlegt, hat diese Priorität.

|[#intable-standard-lager]*Standard-Lager*
|Das hier ausgewählte Standard-Lager ist beim Anlegen des neuen Auftrags oder des Angebots vorausgewählt, wenn in den Kontaktdaten kein Lager hinterlegt ist. Ist in den Kontaktdaten ein Lager hinterlegt, hat dieses Lager Priorität.

|[#intable-standard-vorlage]*Standard-Auftragsvorlage*
|Wählst du eine xref:auftraege:auftraege-verwalten.adoc#295[Auftragsvorlage] als Standard-Auftragsvorlage, ist diese für den neuen Auftrag oder das Angebot standardmäßig vorausgewählt. Die Werte der ausgewählten Auftragsvorlage werden dann automatisch für den Auftrag oder das Angebot übernommen. Es können nur bereits angelegte Auftragsvorlagen ausgewählt werden. +
Standardmäßig ist *Keine Auftragsvorlage vorausgewählt* gesetzt. Wählst du eine Auftragsvorlage als Standard und wird diese zu irgendeinem Zeitpunkt gelöscht, wird als Standard für diese Einstellung wieder *Keine* gesetzt.

|[#intable-endpoint-after-completion]*Endpunkt nach Abschluss eines Auftrags*
|Wähle, wohin im System du nach Abschluss eines Auftrages geleitet werden möchtest. Du kannst wählen zwischen: +
*Aktuelle Ansicht* = Leitet dich zur Auftragsansicht des Kontakts, für den du den Auftrag angelegt hast. Dies ist die Standardeinstellung. +
*Auftragsübersicht* = Leitet dich zur allgemeinen Auftragsübersicht. +
*Detailansicht des neuen Auftrags* = Leitet dich zur Detailansicht des gerade erstellten Auftrags.

|*Filteroption ‚Nur vorrätige Artikel anzeigen‘ in der Artikelsuche vorausgewählt*
|Aktiviere diese Option, damit sie für die Artikelsuche vorausgewählt ist. Angezeigt werden in den Suchergebnissen dann nur Artikel, die einen physischen Warenbestand haben.

|*Filteroption ‚Nur Vertriebslager anzeigen‘ in der Artikelsuche vorausgewählt*
|Aktiviere diese Option, damit sie für die Artikelsuche vorausgewählt ist. Angezeigt werden in den Suchergebnissen dann nur Artikel, die in Vertriebslagern gelagert werden.

|*Filteroption ‚Nur aktive Artikel anzeigen‘ in der Artikelsuche vorausgewählt*
|Aktiviere diese Option, damit sie für die Artikelsuche vorausgewählt ist. Angezeigt werden in den Suchergebnissen dann nur xref:artikel:checkliste-artikel-anzeige.adoc#100[aktivierte Artikel].

|*Filteroption ‚Nur Artikel mit gültigem Preis anzeigen‘ in der Artikelsuche vorausgewählt*
|Aktiviere diese Option, damit sie für die Artikelsuche vorausgewählt ist. Angezeigt werden in den Suchergebnissen dann nur Artikel, für die ein gültiger Preis hinterlegt ist.

|*Änderung der Mehrwertsteuersätze in der Artikelübersichtstabelle im letzten Schritt der Auftragserstellung erlauben.*
|Durch Aktivierung dieser Option erlaubst du, dass vor dem Abschluss des Auftrages im letzten Schritt xref:auftraege:auftraege-verwalten.adoc#290[Übersicht] der Auftragsanlage Steuersätze geändert werden dürfen. Die Steuersätze richten sich dabei nach der Lieferadresse des Auftrags. +
Diese Option ist standardmäßig deaktiviert. Lasse sie deaktiviert, wenn du die Mehrwertsteuersätze in der Übersicht nur sichtbar, aber nicht bearbeitbar lassen möchtest.

|*Anzeige von hinzugefügten Artikeln im Warenkorb*
|Wähle, wie die Artikel zum Warenkorb hinzugefügt werden sollen. Die Standardeinstellung ist *Als eine Auftragsposition, Mengen werden erhöht*. +
*Als separate Auftragspositionen.* = Auch gleiche Artikel werden einzeln hinzugefügt, d.h. jeder Artikel wird in einer eigenen Zeile dargestellt. +
*Als eine Auftragsposition, Mengen werden erhöht.* = Gleiche Artikel werden in einer Auftragsposition zusammengefasst und die Menge wird entsprechend angepasst.

|*Bei Auftragserstellung Preise nur im Warenkorb neu ermitteln*
|Durch Aktivierung dieser Option legst du fest, dass Preise von Artikeln nur dann neu ermittelt werden, wenn sie in den Warenkorb gelegt werden. Standardmäßig werden Preise schon in der Artikelsuche innerhalb der Auftragsanlage ermittelt und sind dort wählbar.

|===

[#create-order-or-offer]
=== Auftrag oder Angebot anlegen

Egal für welchen der oben beschriebenen Wege du dich entscheidest - die Anlage eines neuen Auftrags oder Angebots verläuft immer in drei Schritten. Im ersten Schritt werden <<#step-one-basics, Auftragsdetails erfasst>>, im zweiten Schritt werden <<#step-two-add-items, Artikel hinzugefügt>> und im dritten Schritt wird der <<#step-three-summary, Auftrag abgeschlossen>>. Wähle zunächst aus den Kontakten, für wen der Auftrag oder das Angebot angelegt werden soll.

Oberhalb der Auftragsdetails kannst du aus der Dropdown-Liste auch nachträglich zwischen Auftrag und Angebot wählen. Zudem kannst du optional eine <<create-and-apply-order-templates, Auftragsvorlage>> aus der Dropdown-Liste wählen, die auf diesen Auftrag angewendet werden soll. In der Standardeinstellung ist hier keine Auftragsvorlage ausgewählt.

Die im Folgenden beschriebenen Schritte sind für Aufträge und Angebote gleich.

Die Ansichten der Benutzeroberfläche sind so gestaltet, dass sich Aufträge schnell und übersichtlich anlegen lassen. Dies ist vor allem bei der telefonischen Aufnahme von Bestellungen von Vorteil. Zunächst werden die Auftragsdetails wie z.B. Adressen oder die Zahlungsart abgefragt. Danach werden dem Auftrag Artikel hinzugefügt, um ihn im letzten Schritt zu überprüfen und anzulegen.

[TIP]
.Name, ID und Bewertung des Kontakts auf einen Blick
======
Unten links in der Fußzeile der Auftragsanlage kannst du den Namen, die ID sowie die Bewertung des Kontaks sehen.
======

[#step-one-basics]
==== Schritt 1: Auftragsdetails / Angebotsdetails

Wenn der neue Auftrag oder das neue Angebot über die Kontaktübersicht angelegt wird, werden in den Auftragsdetails bereits einige der im Kontakt hinterlegten Daten übernommen. Welche Informationen übernommen werden, hängt davon ab, welche Daten im Kontakt gespeichert sind. Ansonsten greifen die <<#carrying-out-standard-settings, Standardeinstellungen>>. Beachte dazu auch <<#table-order-details-new-order, diese Tabelle>>.

[[table-order-details-new-order]]
.Allgemeine Einstellungen
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Auftragstyp*
|Wähle aus der Dropdown-Liste, ob du einen *Auftrag* oder ein *Angebot* erstellen möchtest.

| *Auftragsvorlage*
|Wähle die Vorlage des Auftrags aus der Dropdown-Liste.

| *Kontakt*
|Wenn du den Auftrag über das Menü *CRM » Kontakte* anlegst, ist hier der Name des Kontakts bereits vorausgewählt. Möchtest du einen anderen Kontakt wählen, gib mindestens 3 Buschstaben ein, um Vorschläge zu sehen. Alternativ kannst du auch die E-Mail-Adresse des Kontakts eingeben. Alle am Kontakt hinterlegten Daten werden automatisch in die anderen Felder eingefügt. +
*_Tipp:_* Möchtest du einen Auftrag als Gast anlegen, wähle die Option *Gast* aus der Dropdown-Liste und füge im Anschluss eine neue *Rechnungsadresse* sowie eine neue *Lieferadresse* hinzu.

2+^| *Auftragsdetails*

| *Rechnungsadresse*
|Die im Datensatz des Kontaktes hinterlegte Rechnungsadresse wird übernommen. Sind mehrere Rechnungsadressen hinterlegt, wird die als primär definierte Rechnungsadresse übernommen. Wenn keine Rechnungsadresse als primäre Adresse definiert ist, kann man aus der Dropdown-Liste die gewünschte Adresse wählen. +
Über die Vorschau (material:visibility[]) gelangst du direkt in den Kontaktatensatz. Die bereits gewählten Einstellungen in den Auftragsdetails gehen nicht verloren. +
Legst du den Auftrag als *Gast* an, füge hier eine neue Rechnungsadresse hinzu.

| *Lieferadresse*
|Wenn du in der Box *Wie Rechnung* ein Häkchen setzt, wird die unter *Rechnungsadresse* eingegebene Adresse auch als Lieferadresse übernommen. Ansonsten wird die im Datensatz des Kontaktes hinterlegte Lieferadresse übernommen. Sind mehrere Lieferadressen hinterlegt, wird die als primär definierte Lieferadresse übernommen. Wenn keine Lieferadresse als primäre Adresse definiert ist, kann man aus der Dropdown-Liste die gewünschte Adresse wählen. +
In der Dropdown-Liste hast du auch die Möglichkeit, eine neue Lieferadresse einzugeben und im Kontaktdatensatz zu speichern. Beachte dazu die Erläuterungen in der ausklappbaren Box am Ende dieses Abschnitts. +
Über die Vorschau (material:visibility[]) gelangst du direkt in den Kontaktdatensatz. Die bereits gewählten Einstellungen in den Auftragsdetails gehen nicht verloren. +
Legst du den Auftrag als *Gast* an, füge hier eine neue Lieferadresse hinzu.

| *Zahlungsart*
|Wenn im Kontakt eine Zahlungsart definiert ist, zum Beispiel über eine xref:crm:vorbereitende-einstellungen.adoc#kundenklasse-erstellen[Kundenklasse], ist diese vorausgewählt. Ansonsten kannst du eine Zahlungsart eingeben und dann wählen. Angeboten werden dir alle Zahlungsarten, die bereits in deinem plentymarkets System integriert sind. +
Nutzt du eine <<#create-and-apply-order-templates, Auftragsvorlage>>, wird die Zahlungsart der Auftragsvorlage verwendet, sobald du die Vorlage für den Auftrag wählst. Danach ist die Zahlungsart manuell anpassbar.

| *Währung*
|Die xref:payment:waehrungen.adoc#30[Systemwährung] ist vorausgewählt. Über die Dropdown-Liste kannst du die Währung für den Auftrag anpassen.

| *Rabatt in %*
|Hier kannst du manuell einen prozentualen Rabatt eingeben, der auf alle Auftragspositionen des Auftrags angewendet wird. Der eingegebene Wert muss zwischen 0 und 100 liegen, Werte im Minusbereich sind nicht erlaubt. +
Es ist ein Rabatt voreingetragen, wenn der Kontakt zu einer Kundenklasse gehört, in der die Option *Standardrabatt für manuelle Aufträge* mit einem Wert gefüllt ist. Du findest diese Option im Bereich xref:crm:vorbereitende-einstellungen.adoc#intable-customer-class-discount-type[Rabattart] im Menü *Einrichtung » CRM » Kundenklassen*. Den voreingetragenen Wert in den Auftragsdetails kannst du anpassen.

| *Lager*
|Welche Optionen dir angezeigt werden, hängt von den Grundeinstellungen ab, die du für die xref:auftraege:preparatory-settings.adoc#intable-warehouse-assignment[Zuordnung von Lagern] gewählt hast: +
- Ist *a) pro Auftrag kann ein Lager zugeordnet werden* ausgewählt, kannst du in den Auftragsdetails aus einer Dropdown-Liste ein Lager für den Auftrag wählen oder den Namen eines Lagers eingeben, um danach zu suchen. +
Hast du im Menü *Einrichtung » Aufträge » Auftragstypen » Auftrag [Beta]* ein Standard-Lager gewählt, ist dieses Lager hier vorausgewählt.
- Ist *b) pro Artikelposition kann ein Lager zugeordnet werden* ausgewählt, wird dir *Abhängig von den Auftragspositionen* angezeigt. Im nächsten Schritt werden dem Auftrag Artikel hinzugefügt. Dort kannst du dann für jede Variante ein Lager aus einer Dropdown-Liste wählen. +
Hast du im Menü *Einrichtung » Aufträge » Auftragstypen » Auftrag [Beta]* ein Standard-Lager gewählt, ist dieses Lager im nächsten Schritt in der Artikeltabelle vorausgewählt.

| *Mandant*
|Wähle aus der Dropdown-Liste den Mandanten aus, für den dieser Auftrag gelten soll. Vorausgewählt ist entweder der Mandant aus den Kontaktdaten oder als nächste Option ein <<#intable-standard-mandant, Standard-Mandant>>, wenn du diesen festgelegt hast.

| *Eigner*
|Wähle den Eigner für den Auftrag aus der Dropdown-Liste. Hast du einen <<#intable-standard-eigner, Standard-Eigner>> gesetzt, ist dieser vorausgewählt. Ansonsten werden dir in der Dropdown-Liste nur Eigner angezeigt, die das Benutzerrecht haben, Aufträge zu erstellen und zu bearbeiten.

| *Auftragsherkunft*
|Wähle die Herkunft für den Auftrag aus der Dropdown-Liste. Vorausgewählt ist entweder die Herkunft aus den Kontaktdaten oder als nächste Option eine <<#intable-standard-herkunft, Standard-Herkunft>>, wenn du diese festgelegt hast. Darüber hinaus werden nur die xref:auftraege:auftragsherkunft.adoc#[Herkünfte] angezeigt, die aktiv geschaltet sind.

| *Skonto (%)*
|Gib das Skonto, d.h. den Wert in Prozent, der bei Einhaltung der Skontofrist (Tage) abgezogen wird, ein. +
Diese Einstellung ist nur für die Zahlungsarten *Rechnung* und *Vorkasse* verfügbar.

| *Skontofrist (Tage)*
|Gib die Skontofrist, d.h. die Anzahl der Tage ab Rechnungserstellung, in denen skontiert offene Forderungen bezahlt werden können, ein. +
Diese Einstellung ist nur für die Zahlungsarten *Rechnung* und *Vorkasse* verfügbar.

| *Valuta (Tage)*
|Gib das Valutadatum, d.h. den Zeitraum ab Rechnungserstellung, bevor der Zeitraum des Zahlungsziels beginnt, ein. +
Diese Einstellung ist nur für die Zahlungsarten *Rechnung* und *Vorkasse* verfügbar.

| *Zahlungsziel (Tage)*
|Gib das Zahlungsziel, d.h. die Frist für die Zahlung in Tagen, ein. +
Diese Einstellung ist nur für die Zahlungsarten *Rechnung* und *Vorkasse* verfügbar.

|====

[.collapseBox]
.*Neue Lieferadresse anlegen*
--

Von der Dropdown-Liste im Feld *Lieferadresse* aus kannst du nicht nur eine bestehende Lieferadresse wählen, du kannst auch eine neue Adresse anlegen. Um eine neue Lieferadresse anzulegen, gehe wie im Folgenden beschrieben vor. +
*_Tipp:_* Für eine neue Rechnungsadresse sind die Einstellungen identisch.

[.instruction]
Neue Lieferadresse anlegen:

. Wähle aus der Dropdown-Liste *Lieferadresse* die Option *(material:add[]) Neue Lieferadresse hinzufügen*. +
→ Das Fenster *Neue Lieferadresse hinzufügen* wird geöffnet.
. Wähle, ob es sich um die *Primäre* Lieferadresse handelt.
. Gib die Daten ein. Beachte hierzu <<#table-new-delivery-address>>.
. *Speichere* die neue Adresse.

Nach dem Speichern wird die neue Lieferadresse in den entsprechenden Kontaktdatensatz übernommen. Für den neuen Auftrag ist sie nach dem Anlegen im Feld *Lieferadresse* ausgewählt.

[[table-new-delivery-address]]
.Auftragsdetails: Neue Lieferadresse anlegen
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Primär*
|Aktiviere die Option, wenn es sich bei der neuen Adresse um die primäre Lieferadresse handelt. Bei Aktivierung wird diese Lieferadresse beim Anlegen neuer Aufträge automatisch in den neuen Auftrag übernommen.

|*Anrede*
|Wähle optional eine Anrede aus der Dropdown-Liste.

|*Firma (Name 1)*
|Gib den Firmenname ein. Wenn unter *Vorname* und *Nachname* kein Eintrag gemacht wurde, ist dies ein Pflichtfeld.

|*Vorname (Name 2)*
|Gib den Vorname des Kontakts ein. Wenn unter *Firma* und *Nachname* kein Eintrag gemacht wurde, ist dies ein Pflichtfeld.

|*Nachname (Name 3)*
|Gib den Nachname des Kontakts ein. Wenn unter *Firma* und *Vorname* kein Eintrag gemacht wurde, ist dies ein Pflichtfeld.

|*Zusatz (Name 4)*
|Gib optional Zusatzangaben zum Kontakt ein, wie z.B. _z. Hd. Herrn Max Mustermann_.

|*Adresse 1 (Straße)* +
*Adresse 2 (Hausnummer)*
|Gib die Straße und Hausnummer ein. +
*Straße* ist ein Pflichtfeld, wenn unter *Hausnummer* und *Adresszusatz* kein Eintrag gemacht wurde. *Hausnummer* ist ein Pflichtfeld, wenn unter *Straße* und *Adresszusatz* kein Eintrag gemacht wurde.

|*Adresse 3 (Adresszusatz)*
|Gib optional einen Adresszusatz ein, wie z.B. _Appartement 12a_. Wenn unter *Straße* und *Hausnummer* kein Eintrag gemacht wurde, ist dies ein Pflichtfeld.

|*Adresse 4 (Frei)*
|Dies ist ein Feld zur freien Verfügung.

|*Postleitzahl* +
*Ort*
|Gib die Postleitzahl und den Ort des Kontakts ein. *Ort* ist ein Pflichtfeld. +
Bei bestimmten Ländern, z.B. Vereinigtes Königreich, wird die Reihenfolge der Optionen *Postleitzahl* und *Ort* getauscht.

|*Land* +
*Region/Bezirk*
|Wähle Werte aus den Dropdown-Listen. +
*_Beachte:_* Die Dropdown-Liste *Region/Bezirk* ist nicht für alle Länder verfügbar.

|*E-Mail*
|Gib optional eine E-Mail-Adresse ein.

|*Telefon*
|Gib optional eine Telefonnummer ein.

|*Typ* und *Wert*
|Wähle einen Typ aus der Dropdown-Liste. Zur Verfügung stehen: Umsatzsteuernummer, Externe Adress-ID, Gelangensbestätigung, Postnummer, Personennummer, FSK, Geburtstag, Titel, Ansprechpartner, Externe Kunden-ID. Gib den passenden *Wert* für den ausgewählten Typ ein. +
Über *Adressoption hinzufügen* kannst du weitere *Typen* mit den dazugehörigen *Werten* hinzufügen.

|====

--

Nachdem du alle Einstellungen vorgenommen hast, gehe zum nächsten Schritt weiter, indem du unten auf *ARTIKEL HINZUFÜGEN* klickst. Alternativ kannst du auch oben auf den Schritt *Artikel hinzufügen* klicken. Die Auftragsdetails werden gespeichert und du wirst zum nächsten Arbeitsschritt geleitet. In diesem Schritt fügst du dem Auftrag Artikel hinzu.

[#step-two-add-items]
==== Schritt 2: Artikel hinzufügen

Sobald du alle Auftragsdetails in Schritt 1 eingetragen hast, kannst du nun in einem weiteren Schritt deine gewünschten Artikel zum Auftrag hinzufügen. In diesem Schritt werden die Auftragsdetails nicht angezeigt. Erst im dritten Schritt sind die Auftrags- bzw. Angebotsdetails wieder verfügbar. *_Beachte_* allerdings, dass dort nur wenige Einstellungen bearbeitet werden können.

[.collapseBox]
.*Artikeltabelle individualisieren*
--

Die Artikeltabelle kann individuell gestaltet werden. Das bedeutet, dass du selbst entscheiden kannst, welche Informationen dir in den Tabellenspalten angezeigt werden und in welcher Reihenfolge sie platziert sind. Um die Tabelle anzupassen, gehe vor wie folgt.

[.instruction]
Tabelle individualisieren:

. Klicke auf *Spalten konfigurieren* (material:settings[]). +
→ Das Fenster *Spalten konfigurieren* wird geöffnet.
. Wähle, welche Spalten angezeigt werden sollen. Beachte dazu die Einstellungen in <<table-overview-item-search>>.
. Verschiebe (material:drag_indicator[]) die Spalten so, dass sie in der gewünschten Reihenfolge angezeigt werden.
. Klicke auf *Bestätigen*, um deine Auswahl zu speichern.

Wenn du die Tabelle einmal angepasst hast, wird diese Auswahl gespeichert. Die Tabelle bleibt also gleich, auch wenn du diesen Auftrag abgeschlossen hast und weitere Aufträge anlegst. Du kannst das Layout jederzeit ändern. Die zur Verfügung stehenden Spalten findest du in <<table-overview-item-search>>. Dort ist zu jeder Spalte auch die Information hinterlegt, ob es sich um eine Standardspalte handelt. Standardspalten werden angezeigt, wenn die Tabelle nicht individualisiert ist.

[[table-overview-item-search]]
.Tabellenspalten Artikel
[cols="1,3"]
|===
|Einstellung |Erläuterung

|*Bestandsanzeige*
|Ein roter Statusbalken zeigt an, wenn kein Nettobestand für einen Artikel verfügbar ist. Der rote Statusbalken wird nicht angezeigt, wenn Nettobestand für den Artikel vorhanden ist. Wenn du zum Beispiel *Nur vorrätige Artikel anzeigen* ausgewählt hast, wird kein roter Statusbalken angezeigt. Der Statusbalken wird erst rot, wenn der Bestand während des Hinzufügens von Artikeln unter 0 sinkt. +
Diese Spalte ist eine Standardspalte.

|*Status*
|In dieser Spalte wird angezeigt, ob diese Variante im Webshop aktiv oder inaktiv ist. Informationen zur Aktivierung oder Deaktivierung einer Variante findest du auf der Handbuchseite xref:artikel:checkliste-artikel-anzeige.adoc#100[Hast du die Variante aktiviert?]. +
Diese Spalte ist eine Standardspalte.

|*Artikel-ID*
|Zeigt die ID des Artikels an. Wenn du auf die Artikel-ID klickst, gelangst du direkt in die Einstellungen des jeweiligen Artikels. +
Diese Spalte ist eine Standardspalte.

|*Varianten-ID*
|Zeigt die Varianten-ID an. Wenn du auf die Varianten-ID klickst, gelangst du direkt in die Einstellungen der Variante. +
Diese Spalte ist eine Standardspalte.

|*Artikel-ID/Varianten-ID*
|Zeigt die Artikel-ID und die Varianten-ID kombiniert und nicht in zwei separaten Spalten an. Wenn du auf die Artikel-ID oder die Varianten-ID klickst, gelangst du direkt in die Einstellungen des jeweiligen Artikels bzw. der Variante. +
Diese Spalte ist eine Standardspalte.

|*Variantennummer*
|Zeigt die Variantennummer an. Wenn du auf die Variantennummer klickst, gelangst du direkt in die Einstellungen der jeweiligen Variante. +
Diese Spalte ist eine optionale Spalte.

|*Artikelname*
|Zeigt den am Artikel hinterlegten Namen an. +
Diese Spalte ist eine Standardspalte.

|*Attribute*
|Zeigt die am Artikel hinterlegten Attribute an. +
Diese Spalte ist eine Standardspalte.

|*Variantenname*
|Zeigt den an der Variante hinterlegten Variantennamen an. +
Diese Spalte ist eine Standardspalte.

|*Barcode*
|Zeigt den Barcode des Artikels an. +
Diese Spalte ist eine Standardspalte.

| *System-EK*
|Zeigt den Einkaufspreis des Systems an. +
Diese Spalte ist eine Standardspalte.

|[#intable-item-search-price-selection]*Preisauswahl*
|In einer Dropdown-Liste werden dir alle für diesen Auftrag ermittelten Verkaufspreise angezeigt. Du kannst einen der angezeigten Preise wählen, der dann als Grundlage für die weiteren Auftragsberechnungen verwendet wird. Enthält der Preis einen Rabatt, wird dies hinter dem Preisnamen und dem Betrag angezeigt. Die Spalten *Kundenklassenrabatt* und *Kategorierabatt* zeigen den Prozentsatz des angewendeten Rabatts an. +
Eine manuelle Anpassung des Preises kannst du im <<#shopping-cart, Warenkorb>> vornehmen. Wählst du einen anderen Verkaufspreis als den ersten ermittelten, muss der Verkaufspreis aktualisiert werden. Klicke dafür auf *Verkaufspreis aktualisieren* (material:refresh[]). Nach der Aktualisierung ist die Warenkorb-Schaltfläche (material:add_shopping_cart[]) wieder verfügbar und die Artikel können hinzugefügt werden. Dies gilt auch für Mengenänderungen. +
Konnte kein gültiger Verkaufspreis ermittelt werden, wird *Kein gültiger Verkaufspreis* in der Dropdown-Liste angezeigt. Ohne gültigen Verkaufspreis kann der Auftrag nicht abgeschlossen werden. Lege daher den Artikel in den Warenkorb und passe den Preis dort manuell an. +
Diese Spalte ist eine Standardspalte.

| *Kategorierabatt*
|Zeigt den für den ausgewählten Verkaufspreis angewendeten Kategorierabatt in Prozent an. +
Diese Spalte ist eine Standardspalte.

| *Kundenklassenrabatt*
|Zeigt den für den ausgewählten Verkaufspreis angewendeten Kundenklassenrabatt in Prozent an. +
Diese Spalte ist eine Standardspalte.

| *Verfügbarkeit*
|Zeigt die Verfügbarkeit des Artikels an. +
Diese Spalte ist eine Standardspalte.

| *Netto-WB*
|Zeigt den Netto-Warenbestand des Artikels an. +
Diese Spalte ist eine Standardspalte.

| *Lager*
|Zeigt das Lager des Artikels an. Wähle bei Bedarf ein anderes Lager aus der Dropdown-Liste oder gib den Namen eines Lagers ein, um danach zu suchen. Beachte, dass dies nur möglich ist, wenn du für die *Zuordnung des Lagers* die Einstellung *b) Pro Artikelposition kann ein Lager zugeornet werden* gewählt hast. +
Hast du im Menü *Einrichtung » Aufträge » Auftragstypen » Auftrag [Beta]* ein Standard-Lager gewählt, ist dieses Lager hier vorausgewählt. +
Diese Spalte ist eine Standardspalte.

|*Menge*
|Gib die Menge ein, in der der Artikel dem Warenkorb hinzugefügt werden soll. Du kannst nur ganze Zahlen eingeben, negative Mengen oder Mengen, die den Nettobestand übersteigen, sind nicht erlaubt. In diesem Fall wird eine Fehlermeldung angezeigt. Wenn die hinzugefügte Menge den Nettobestand auf 0 oder niedriger setzt, wird der Statusbalken für die Bestandsanzeige auf rot gesetzt. +
Bei Mengenänderungen ändert sich der Verkaufspreis, daher muss der Verkaufspreis aktualisiert werden. Klicke dafür auf *Verkaufspreis aktualisieren* (material:refresh[]). Nach der Aktualisierung ist die Warenkorb-Schaltfläche (material:add_shopping_cart[]) wieder verfügbar und die Artikel können hinzugefügt werden. +
Diese Spalte ist eine Standardspalte.

|*Warenkorb-Symbol*
|Durch Klick auf den Warenkorb (material:add_shopping_cart[]) wird der Artikel in der ausgewählten *Menge* dem Warenkorb hinzugefügt. +
Diese Spalte ist eine Standardspalte.

|===

--

[#search-items]
===== Artikel suchen

Anhand der Suche (material:search[]) kannst du die gewünschten Artikel finden und dem Auftrag hinzufügen. Wenn du eine Suche ausführst, werden deine gewählten Sucheinstellungen oben als Chips dargestellt. Diese Sucheinstellungen kannst du speichern, um sie in Zukunft schneller und einfacher wieder verwenden zu können. +
Verwende eine der folgenden Möglichkeiten, um nach Artikeln zu suchen.

[.instruction]
Artikel suchen:

.. *_Möglichkeit 1:_* Klicke auf material:search[], um direkt eine Liste aller Artikel zu sehen.
.. *_Möglichkeit 2:_* Gib etwas in das Suchfeld ein und klicke auf einen der automatischen Vorschläge.
.. *_Möglichkeit 3:_* Klicke auf material:tune[], um die Suchergebnisse mit Hilfe von Filtern einzugrenzen.

Führe eine <<#search-items, Suche>> (material:search[]) aus, um die passenden Artikel zu finden und dem Auftrag hinzuzufügen. Nutze außerdem die in der folgenden Tabelle aufgeführten Filter, um die Suche weiter einzugrenzen. Beachte, dass deine zuvor vorgenommenen <<carrying-out-standard-settings, Standardeinstellungen>> bei der Suche greifen.

[[table-order-filters]]
.Filter für Auftragspositionen
[cols="1,3"]
|===
|Filter |Erläuterung

| *Volltext*
|Gib etwas ein, um eine Volltextsuche zu starten.

| *Artikel-ID*
|Gib eine ID ein, um nach Artikeln mit dieser ID zu filtern.

| *Artikelname*
|Gib einen Namen ein, um nach Artikeln mit diesem Namen zu filtern.

| *Variantennummer*
|Gib eine Variantennummer ein, um nach Artikeln mit dieser Variantennummer zu filtern. +
*_Tipp:_* Für diesen Filter ist auch eine Teilsuche möglich. Somit genügt es, wenn du lediglich die ersten Zeichen der Variantennummer eingibst, um danach zu suchen.

| *Varianten-ID*
|Gib eine Varianten-ID ein, um nach Artikeln mit dieser Varianten-ID zu filtern.

| *Barcode*
|Gib einen Barcode ein, um nach Artikeln mit diesem Barcode zu filtern.

| *Hersteller*
|Gib einen Hersteller ein, um nach Artikeln dieses Herstellers zu filtern.

| *Artikel-Tag*
|Gib ein Tag ein, um nach Artikeln mit diesem Tag zu filtern.

| *Nur vorrätige Artikel anzeigen*
|Aktiviere diese Option (material:done[role=skyBlue]), um nach vorrätigen Artikeln zu filtern.

| *Nur aktive Artikel anzeigen*
|Aktiviere diese Option (material:done[role=skyBlue]), um nach aktiven Artikeln zu filtern.

| *Nur Vertriebslager anzeigen*
|Aktiviere diese Option (material:done[role=skyBlue]), um nach Artikeln in Vertriebslagern zu filtern. +
*_Hinweis:_* Wenn du in den Grundeinstellungen die Lagereinstellung *a) pro Auftrag kann ein Lager zugeordnet werden* gewählt hast, steht dir die Option *Nur Vertriebslager anzeigen* nicht zur Verfügung, weil du das Lager bereits bestimmt hast.

| *Nur Artikel mit gültigem Preis anzeigen*
|Aktiviere diese Option (material:done[role=skyBlue]), um nach Artikeln mit gültigem Preis zu filtern.

|===

[#save-current-filter]
===== Aktuellen Filter speichern

. Führe eine Suche aus.
. Klicke auf *Gespeicherte Filter* (material:bookmarks[role=darkGrey]).
. Klicke auf material:bookmark_border[role=darkGrey] *Aktuellen Filter speichern*.
. Gib einen Namen ein und schalte die optionalen Einstellungen bei Bedarf ein (material:toggle_on[role=skyBlue]).
. Klicke auf *Speichern*. +
→ Die Filtereinstellungen erscheinen nun unter *Gespeicherte Filter* (material:bookmarks[role=darkGrey]).


[#use-saved-filters]
===== Gespeicherte Filter anwenden

. Klicke auf *Gespeicherte Filter* (material:bookmarks[role=darkGrey]).
. Klicke auf eine bereits erstellte Filtereinstellung. +
→ Die Suche wird ausgeführt und die verwendeten Sucheinstellungen werden oben als Chips dargestellt.

[#adding-items]
==== Artikel hinzufügen

Nachdem du mithilfe der Suche oder anhand von Filtern alle gewünschten Artikel gefunden hast, kannst du sie dem Auftrag hinzufügen. Gehe dazu vor wie folgt.

[.instruction]
Artikel hinzufügen:

. Suche (material:search[]) den gewünschten Artikel.
. Wähle den passenden Verkaufspreis aus der *Preisauswahl* Dropdown-Liste.
. Gib die Menge des Artikels ein, die dem Auftrag hinzugefügt werden soll.
. Nimmst du Preis- oder Mengenänderungen vor, gehe rechts in der jeweiligen Zeile in das Kontextmenü (material:more_vert[]) und aktualisiere den Verkaufspreis mit Klick auf *Verkaufspreise aktualisieren* (material:refresh[]). +
*_Tipp:_* Links oben in der Tabelle kannst du mit Klick auf *Verkaufspreise aktualisieren* (material:refresh[]) alle Preis- und Mengenänderungen auf einmal aktualisieren.
. Klicke am Ende der jeweiligen Zeile auf *Zum Warenkorb hinzufügen* (material:add_shopping_cart[]), um den Artikel zum Warenkorb hinzuzufügen.
. Wiederhole diese Schritte, um weitere Artikel hinzuzufügen.
. Wenn alle Artikel hinzugefügt wurden, gehe zum nächsten Schritt, indem du auf *Auftrag erstellen* bzw. *Angebot erstellen* klickst. +

[#shopping-cart]
==== Warenkorb bearbeiten

In der Tabelle des Warenkorbs kannst du sowohl den *Artikelnamen* als auch die *Menge* und den *Verkaufspreis* anpassen. Sobald du die Angaben der Menge oder des Preises änderst, müssen Aktualisierungen durchgeführt werden. Dies kannst du tun, indem du rechts im Kontextmenü (material:more_vert[]) am jeweiligen Artikel auf *Verkaufspreis aktualisieren* (material:refresh[]) klickst. Oder du nutzt die Schaltfläche *Verkaufspreise aktualisieren* oben links in der Tabelle des Warenkorbs. Erst nach der Aktualisierung kannst du in den nächsten Schritt der Auftragsanlage weitergehen.

Folgendes gilt für Verkaufspreise:

* Gibst du manuell einen Preis ein, bleibt dieser in der Dropdown-Liste als Auswahl für diesen Auftrag erhalten, auch wenn du vor- oder zurückgehst oder zwischendurch einen anderen Preis auswählst.
* Konnte kein gültiger Verkaufspreis ermittelt werden, muss ein manueller Preis eingegeben werden. Die Auftragsanlage ist nur mit gültigen Preisen möglich.
* Es ist zulässig, den Preis 0,00 einzugeben.
* Wenn ein Verkaufspreis eingegeben wird, der niedriger ist als der Einkaufspreis, wirst du durch eine Warnung darauf hingewiesen. Allerdings ist es möglich, einen niedrigeren Verkaufspreis zu wählen, wenn es gewünscht wird.
* Nimm alle Anpassungen an den Artikeln in diesem Schritt vor, denn im dritten und letzten Schritt der Auftragsanlage ist dies nicht mehr möglich. Das Vor- und Zurücknavigieren innerhalb der Schritte der Auftragsanlage bleibt weiterhin möglich.

Auftragspositionen im Warenkorb können auch gelöscht werden. Klicke dafür auf *Löschen* (material:delete[]). Eine weitere Bearbeitungsmöglichkeit der Auftragspositionen im Warenkorb stellen die Eigenschaften dar. Beachte dafür das Kapitel <<#edit-order-item-properties, Eigenschaften von Auftragspositionen bearbeiten>>.

Nachdem du alle gewünschten Artikel im Warenkorb abschließend bearbeitet hast, klicke auf *Auftrag erstellen* bzw. *Angebot erstellen*, um zum dritten und letzten Schritt zu gelangen. Du kannst auch zu den Auftragsdetails zurückkehren, indem du auf *Auftragsdetails* klickst. Artikel im Warenkorb werden gespeichert, wenn du vor- oder zurückgehst.

[.collapseBox]
.*Warenkorbtabelle individualisieren*
--
Die Warenkorbtabelle lässt sich individuell anpassen. Du kannst wählen, welche Tabellenspalten dir in welcher Reihenfolge angezeigt werden sollen. Wenn du die Tabelle angepasst hast, wird diese Auswahl gespeichert.

[.instruction]
Tabelle individualisieren:

. Klicke auf *Spalten konfigurieren* (material:settings[]). +
→ Das Fenster *Spalten konfigurieren* wird geöffnet.
. Wähle, welche Spalten angezeigt werden sollen.
. Verschiebe (material:drag_indicator[]) die Spalten, sodass sie in der Reihenfolge angezeigt werden, in der du sie benötigst.
. Klicke auf *Bestätigen*, um deine Auswahl zu speichern.

[[table-shopping-cart]]
.Tabellenspalten Warenkorb
[cols="1,3"]
|===
|Einstellung |Erläuterung

| *Ausklappen*
|Ermöglicht das Ausklappen der Auftragspositionstabelle und zeigt die Eigenschaften an.

| *Menge*
|Zeigt die Menge der Artikel an. Passe die Menge bei Bedarf an. +
Diese Spalte ist eine Standardspalte.

| *Artikel-ID*
|Zeigt die Artikel-ID an. Mit Klick auf die ID wird der Artikel geöffnet. +
Diese Spalte ist eine Standardspalte.

| *Varianten-ID*
|Zeigt die Varianten-ID der Auftragsposition an. Mit Klick auf die ID wird die Variante geöffnet. +
Diese Spalte ist eine Standardspalte.

| *Artikel-ID* / *Varianten-ID*
|Zeigt die Artikel-ID und die Varianten-ID kombiniert und nicht in zwei separaten Spalten an. Wenn du auf die Artikel-ID oder die Varianten-ID klickst, gelangst du direkt in die Einstellungen des jeweiligen Artikels bzw. der Variante. +
Diese Spalte ist keine Standardspalte.

| *Variantennummer*
|Zeigt die Nummer der Variante an. Wenn du auf die Variantennummer klickst, gelangst du direkt in die Einstellungen der jeweiligen Variante. +
Diese Spalte ist eine optionale spalte.

| *Artikelname*
|Zeigt den am Artikel hinterlegten Namen an. Passe den Namen bei Bedarf an (material:edit[]). +
Diese Spalte ist eine Standardspalte.

| *Attribute*
|Zeigt die Attribute an. +
Diese Spalte ist eine Standardspalte.

| *Variantenname*
|Zeigt den Namen der Variante an. +
Diese Spalte ist eine Standardspalte.

| *Barcode*
|Zeigt den Barcode des Artikels an. +
Diese Spalte ist keine Standardspalte.

| *System-EK*
|Zeigt den Einkaufspreis des Systems an. +
Diese Spalte ist keine Standardspalte.

| *Preisauswahl*
|Zeigt die Preisauswahl an. Wähle bei Bedarf eine andere Preisauswahl aus der Dropdown-Liste. +
Diese Spalte ist eine Standardspalte.

| *Kategorierabatt*
|Zeigt den für den ausgewählten Verkaufspreis angewendeten Kategorierabatt in Prozent an. +
Diese Spalte ist keine Standardspalte.

| *Kundenklassenrabatt*
|Zeigt den für den ausgewählten Verkaufspreis angewendeten Kundenklassenrabatt in Prozent an. +
Diese Spalte ist keine Standardspalte.

| *Nettopreis*
|Zeigt den Nettopreis des Artikels an. Über material:edit[] kannst du das Datenfeld Nettopreis bearbeiten. Der Bruttopreis wird automatisch angepasst. +
Diese Spalte ist eine Standardspalte.

| *Regulärer Nettopreis*
|Zeigt den regulären Nettopreis des Artikels an. +
Diese Spalte ist keine Standardspalte.

| *Bruttopreis*
|Zeigt den Bruttopreis des Aritkels an. Über material:edit[] kannst du das Datenfeld Bruttopreis bearbeiten. Der Nettopreis wird automatisch angepasst. +
Diese Spalte ist eine Standardspalte.

| *Aufpreis gesamt*
|Zeigt die Summe der Aufpreise für Bestelleigenschaften an. +
Diese Spalte ist keine Standardspalte.

| *Rabatt*
|Zeigt den Rabatt an, der in den Auftragsdetails im ersten Schritt der Auftragsanlage eingegeben wurde. +
Diese Spalte ist eine Standardspalte.

| *Gesamtbetrag (brutto)*
|Zeigt den Brutto-Gesamtbetrag des Artikels an. +
Diese Spalte ist eine Standardspalte.

| *Lager*
|Zeigt das Lager des Artikels an. Wähle bei Bedarf ein anderes Lager aus der Dropdown-Liste. Beachte, dass dies nur möglich ist, wenn du für die *Zuordnung des Lagers* die Einstellung *b) Pro Artikelposition kann ein Lager zugeornet werden* gewählt hast. +
Diese Spalte ist eine Standardspalte.

| *USt. (%)*
|Die Umsatzsteuer wird in % angezeigt. Voreingestellt sind 19.00 %. Über die Dropdown-Liste kannst du den Steuersatz ändern. +
Diese Spalte ist eine Standardspalte.

| *Gewicht [g]*
|Zeigt das Gewicht des Artikels in Gramm an. Passe das Gewicht bei Bedarf im Eingabefeld an. +
Diese Spalte ist keine Standardspalte.

| *Länge [mm]*
|Zeigt die Länge des Artikels in mm an. Passe die Länge bei Bedarf im Eingabefeld an. +
Diese Spalte ist keine Standardspalte.

| *Breite [mm]*
|Zeigt die Breite des Artikels in mm an. Passe die Breite bei Bedarf im Eingabefeld an. +
Diese Spalte ist keine Standardspalte.

| *Aktionen*
|Ist dieses Feld gewählt, sind die Aktionen zum Bearbeiten (material:edit[]) und Löschen (material:delete[]) des Artikels verfügbar.
|===

--

[#edit-order-item-properties]
==== Eigenschaften an Auftragspositionen bearbeiten

Vom Warenkorb aus kannst du die Eigenschaften der Auftragspositionen eines Auftrags (Bestelleigenschaften) bearbeiten. Die hier vorgenommenen Änderungen gelten nur für die Auftragspositionen dieses Auftrags. Die im System angelegten Eigenschaften werden nicht überschrieben. In der Auftragsanlage stehen dir nur Eigenschaften zur Verfügung, die du bereits im System angelegt hast. +
Möchtest du Eigenschaften erstellen und bearbeiten oder bist du noch nicht mit der Struktur von Eigenschaften vertraut, informiere dich im Kapitel xref:artikel:eigenschaften.adoc#500[Eigenschaften].

Damit eine Eigenschaft an einer Auftragsposition gesetzt werden kann, muss sie in den Eigenschaftseinstellungen im Bereich *Optionen* als *Bestelleigenschaft* definiert werden. Lege unter xref:artikel:eigenschaften.adoc#property-options[Optionen] außerdem mögliche Aufpreise und Besteuerungen fest. Die hier hinterlegten Werte werden in die Auftragsberechnungen mit einbezogen. Ist bereits eine Eigenschaft mit einer Auftragsposition verknüpft, wird diese an der dazugehörigen Auftragsposition angezeigt.

Die Eigenschaften werden in einer zweiten Tabellenzeile direkt unterhalb der dazugehörigen Auftragsposition angezeigt. Hier findest du Angaben zu *Name*, *Wert*, *Aufpreis* und *USt. %* der Eigenschaft. Die *USt. %*, also den hinterlegten Steuersatz, kannst du direkt in der Tabelle bearbeiten, wenn der Eigenschaftstyp dies zulässt. Zudem kannst du die Eigenschaften der Auftragspositionen *löschen* (material:delete[]). Gelöschte Eigenschaften werden dann für diesen Auftrag nicht berücksichtigt. +
Um die Eigenschaften zu bearbeiten oder weitere bereits bestehende Eigenschaften zu einer Auftragspositionen hinzuzufügen, klicke rechts im Kontextmenü (material:more_vert[]) auf *Eigenschaften bearbeiten* (material:edit[]).


Im Bearbeitungsfenster findest du folgende Angaben zu der Eigenschaft einer Auftragsposition:

* *Name* = Der Name der Eigenschaft wird angezeigt. Ein rotes Sternchen am Namen der Eigenschaft kennzeichnet, dass es eine verpflichtende Eigenschaft ist. Ob eine Eigenschaft verpflichtend ist, bestimmst du in den Einstellungen der Eigenschaften im Bereich xref:artikel:eigenschaften.adoc#property-options[Optionen]. Wähle in der Dropdown-Liste *Bestelloptionen* die Einstellung *Verpflichtend* aus.
* *Wert* = Der Wert der Eigenschaft wird angezeigt. Der Wert kann angepasst werden. Je nach Eigenschaftstyp kannst du eine Auswahl treffen, den Wert ändern, einen Wert eingeben oder eine Datei hochladen. Die Änderungen gelten nur für diesen Auftrag.
* *Aufpreis* = Der Aufpreis der Eigenschaft, sofern ein Aufpreis zugeordnet ist, wird angezeigt. Der Aufpreis kann bearbeitet werden. Die Änderungen gelten nur für diesen Auftrag.

In diesem Fenster gibt es außerdem weitere Bearbeitungsmöglichkeiten. Durch Klicken auf *Löschen* (material:delete[]) entfernst du eine Eigenschaft von einer Auftragsposition. Diese Eigenschaft wird dann für diesen Auftrag nicht berücksichtigt. +
Du kannst weitere bereits angelegte Eigenschaften hinzufügen. Wähle eine Eigenschaft aus der Dropdown-Liste des Felds *Eigenschaft wählen* und füge sie durch Klicken auf *Eigenschaft hinzufügen* (material:add[]) zu dieser Auftragsposition hinzu. +
Hast du alle erforderlichen Anpassungen vorgenommen, klicke auf *Eigenschaften speichern*. Klickst du auf *Abbrechen*, wird keine der vorgenommenen Änderungen übernommen. Das Bearbeitungsfenster wird geschlossen und du kannst nach Bedarf die Eigenschaften weiterer Auftragspositionen auf die gleiche Weise bearbeiten.

Wenn du die Eigenschaften auf Dokumenten ausgeben lassen möchtest, musst du dies in der Konfiguration der Eigenschaften einstellen. Stelle sicher, dass im Bereich xref:artikel:eigenschaften.adoc#property-visibilities[Sichtbarkeiten]

* aus der Dropdown-Liste *Überall anzeigen* die Option *Anzeige auf PDF-Dokumenten* sowie
* aus der Dropdown-Liste *Mandant* die richtigen Mandanten ausgewählt sind.

Wo die Eigenschaften auf dem Dokument ausgegeben werden, hängt von der jeweiligen Eigenschaft und deren Konfiguration ab. Eigenschaften, die in der Konfiguration im Bereich *Optionen* keinen Steuersatz zugewiesen bekommen haben oder für die aus der Dropdown-Liste *Bestelleigenschaft* die Option *zusätzliche Kosten anzeigen* ausgewählt ist, werden unterhalb der Summen angezeigt. Andere Eigenschaften werden in der Tabelle der Artikelpositionen angezeigt.

Wenn du mit der Bearbeitung der Auftragseigenschaften und des Warenkorbs fertig bist, folgt der letzte Schritt in der Auftragsanlage. In diesem Schritt werden die Eigenschaften für Auftragspositionen nicht noch einmal angezeigt. Stelle daher sicher, dass du alle Anpassungen vorgenommen hast. Klicke auf *Auftrag ertellen* bzw. *Angebot erstellen*.

[#step-three-summary]
==== Schritt 3: Auftrag erstellen / Angebot erstellen

Im letzten Schritt wird der Auftrag oder das Angebot abgeschlossen. Oberhalb der Auftragsdetails werden dir Infoboxen mit verschiedenen Beträgen für diesen Auftrag oder für dieses Angebot angezeigt:

* Gesamtbetrag (brutto): Zeigt den errechneten Gesamtbruttobetrag des Auftrags an. Der Statusbalken ist grün, wenn es sich bei dem Auftrag um einen Bruttoauftrag handelt. Ansonsten ist der Statusbalken grau.
* Gesamtbetrag (netto): Zeigt den errechneten Gesamtnettobetrag des Auftrags an. Der Statusbalken ist grün, wenn es sich bei dem Auftrag um einen Nettoauftrag handelt. Ansonsten ist der Statusbalken grau.
* Artikelmenge (gesamt): Zeigt die Gesamtanzahl der Artikelpositionen des Auftrags an. Der Statusbalken ist immer grau.
* Gutscheinbetrag: Zeigt die Ermäßigung durch Aktionsgutscheine an. Der Statusbalken ist orange, wenn ein Gutschein im Auftrag verwendet wurde. Ansonsten ist der Statusbalken grau.
* Auftragsrabatt: Zeigt den Rabattbetrag an, der sich durch den im ersten Schritt der Auftragsanlage vergebenen Rabatt ergibt. Errechnet wird der summierte Rabatt für alle Auftragspositionen. Der Statusbalken ist orange, wenn im ersten Schritt ein Rabatt gesetzt wurde. Ansonsten ist der Statusbalken grau.
* Offener Betrag: Zeigt den von der Kund:in zu zahlenden Rechnungsbetrag an. Der Statusbalken ist grün, wenn der Betrag bei null liegt, d.h. wenn der Auftrag vollständig bezahlt wurde. Rot bedeutet, dass der vollständige Rechnungsbetrag noch offen ist. Orange bedeutet, dass ein Teil des Rechnungsbetrags noch offen ist.

In den Auftragsdetails kannst du die *Zahlungsart*, die *Versandkosten*, die *Versandart* sowie den *Eigner* bei Bedarf noch einmal anpassen. +

Außerdem kannst du einen oder mehrere *Gutschein-Codes* eingeben, die mit diesem Auftrag eingelöst werden sollen. Die Werte der Gutscheine werden dann mit dem Auftragswert verrechnet. Gutscheine werden nicht als Auftragspositionen im Warenkorb hinzugefügt. Gutscheine können nicht für Angebote eingelöst werden. Das bedeutet, dass das Eingabefeld *Gutschein-Codes* nur in der Auftragserstellung, nicht aber in der Angebotserstellung verfügbar ist. Bei Gutscheinen wird zwischen den Typen *plentymarkets Kampagne* und *Externe Kampagne* unterschieden. Um Gutscheicodes einzulösen, gehe wie im Folgenden beschrieben vor.

[tabs]
====
Gutschein-Codes einer plentymarkets Kampagne einlösen::
+
--
[.instruction]
Gutschein-Codes einer plentymarkets Kampagne einlösen:

. Gib im Feld *Gutschein-Codes* den Code einer plentymarkets Kampagne ein.
. Klicke anschließend auf _Enter_ oder klicke außerhalb des Felds. +
→ Es wird geprüft, ob der Gutschein-Code gültig ist. Kann der Gutschein eingelöst werden, wird er in grün mit dem Wert des Gutscheins angezeigt. Ist ein Gutschein-Code hingegen nicht gültig, wird dieser in rot mit der Info *Nicht einlösbar* angezeigt. +
*_Tipp:_* Ein Tooltip zeigt an, um welche Art von Gutschein es sich handelt.
. Gib bei Bedarf weitere Gutschein-Codes ein. +
icon:map-signs[] *_Oder:_* Klicke rechts in der Zeile des Felds *Gutschein-Codes* auf *Gutschein-Code hinzufügen* (material:add[]). +
→ Das Fenster *Gutschein einlösen* wird geöffnet.
. Wähle den Kampagnen-Typ *plentymarkets Kampagne* aus der Dropdown-Liste.
. Gib den Gutschein-Code der plentymarkets Kampagne ein.
. Klicke auf *Einlösen*. +
→ Der Gutschein-Code wird hinzugefügt und mit diesem Auftrag eingelöst.
--

Gutschein-Codes einer externen Kampagne einlösen::
+
--

[.instruction]
Gutschein-Codes einer externen Kampagne einlösen:

. Klicke rechts in der Zeile des Felds *Gutschein-Codes* auf *Gutschein-Code hinzufügen* (material:add[]). +
→ Das Fenster *Gutschein einlösen* wird geöffnet.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<table-redeem-coupon-codes>>.
. Klicke auf *Einlösen*. +
→ Der Gutschein-Code wird in blau mit dem Wert des Gutscheins hinzugefügt und mit diesem Auftrag eingelöst.

[[table-redeem-coupon-codes]]
.Gutschein-Codes einlösen
[cols="1,3"]
|===
|*Einstellung* |*Erläuterung*

| *Kampagnen-Typ*
|Wähle den Typ *Externe Kampagne* aus der Dropdown-Liste.

| *Code*
|Gib einen Gutschein-Code ein.

| *Typ*
|Wähle, ob es sich um einen *Aktionsgutschein* oder einen *Mehrzweckgutschein* handelt.

| *Wert in €*
|Gib den Wert des Gutscheins in der jeweiligen Währung ein.

|===
--
====

Unterhalb der Auftragsdetails wird eine Tabelle mit den ausgewählten Artikelpositionen angezeigt. Zusätzlich zu den Angaben in der vorherigen Ansicht werden dir hier weitere Preise und die Umsatzsteuer ausgegeben. Die Steuersätze kannst du anpassen, wenn du dies in den <<#carrying-out-standard-settings, Standardeinstellungen>> erlaubt hast.

[.collapseBox]
.*Tabelle individualisieren*
--

Die Tabelle im letzten Schritt der Auftragsanlage lässt sich individuell anpassen. Du kannst wählen, welche Tabellenspalten dir in welcher Reihenfolge angezeigt werden sollen. Wenn du die Tabelle angepasst hast, wird diese Auswahl gespeichert.

[.instruction]
Tabelle individualisieren:

. Klicke auf *Spalten konfigurieren* (material:settings[]). +
→ Das Fenster *Spalten konfigurieren* wird geöffnet.
. Wähle, welche Spalten angezeigt werden sollen.
. Verschiebe (material:drag_indicator[]) die Spalten, sodass sie in der Reihenfolge angezeigt werden, in der du sie benötigst.
. Klicke auf *Bestätigen*, um deine Auswahl zu speichern.

Die Tabelle verfügt über die folgenden Spalten: +

* Ausklappen
* Menge
* Artikel-ID
* Variantennr.
* Variantenname
* Varianten-ID
* Artikelname
* Attribute
* Nettopreis
* Regulärer Nettopreis
* Bruttopreis
* Rabatt
* Aufpreis gesamt
* Gesamtbetrag (netto)
* Gesamtbetrag (brutto)
* Lager
* USt.
* Externe Artikel-ID
* Externe Auftragspositions-ID
* Eigenschafts-ID
* Lagerorte
* Gewinnspanne (netto)
* Nachbestellungs-ID

--

Wenn du Änderungen an den Versandkosten oder der Versandart vornimmst oder Gutscheine hinzufügst, werden die Gesamtsummen automatisch neu berechnet. Um den Auftrag fertigzustellen, klicke auf material:save[role=green] *Auftrag anlegen*. Der Auftrag ist nun erstellt und je nach Einstellung wirst du in die entsprechende Ansicht weitergeleitet. Der Auftrag ist anschließend in der Auftragsübersicht im Menü *Aufträge » Aufträge (Testphase)* verfügbar.

[#295]
=== Auftragsvorlagen erstellen und anwenden

Im Menü *Einrichtung » Aufträge » Auftragsvorlage* kannst du Auftragsvorlagen erstellen. Diese kannst du dann beim Anlegen eines manuellen Auftrags auswählen oder über eine xref:automatisierung:ereignisaktionen.adoc#intable-auftragsvorlage[Ereignisaktion] auf einen Auftrag anwenden lassen. Wählst du eine Auftragsvorlage für einen Auftrag, werden die dort hinterlegten Daten auf den Auftrag angewendet. Nach der Verwendung einer Auftragsvorlage kannst du Aufträge wie üblich bearbeiten und auch die Auftragsinformationen anpassen.

Gehe folgendermaßen vor, um eine Auftragsvorlage zu erstellen:

[.instruction]
Auftragsvorlage erstellen:

. Öffne das Menü *Einrichtung » Aufträge » Auftragsvorlage*.
. Wechsele in das Tab *Neue Vorlage*.
. Trage einen eindeutigen *Namen* ein.
. Wähle aus der jeweiligen Dropdown-Liste *Zahlungsart* und *Auftragsstatus* aus.
. Füge über *Artikel hinzufügen* optional Artikel hinzu.
. Speichere (material:save[role=green]) die Auftragsvorlage.

[[table-order-templates]]
.Datenfelder Auftragsvorlage
[cols="1,3"]
|===
|Einstellung |Erläuterung

| *Name*
|Gib einen Namen für die Auftragsvorlage ein. Dieser Name wird anschließend in Dropdown-Listen zur Auswahl der Auftragsvorlage angezeigt.

| *Zahlungsart*
|Wähle eine Zahlungsart aus der Dropdown-Liste. Diese Zahlungsart wird anschließend bei Anwendung der Vorlage zum entsprechenden Auftrag hinzugefügt.

| *Auftragsstatus*
|Wähle einen Auftragsstatus aus der Dropdown-Liste. Bei Anwendung der Vorlage auf einen Auftrag wird dieser Auftrag dann in diesen Auftragsstatus geschoben.

| *Artikel*
|Hast du der Auftragsvorlage Artikel hinzugefügt, werden diese Artikel in der Tabelle angezeigt. Das Hinzufügen von Artikeln ist optional. Die hier angezeigten Artikel werden bei Anwendung der Auftragsvorlage zum Auftrag hinzugefügt. Du siehst zudem die Menge und den Artikeltext für jeden Artikel. Außerdem kannst du in der Tabelle Artikel aus der Auftragsvorlage löschen. +
*_Beachte_*, dass bei Anwendung einer Auftragsvorlage mit Artikeln dem Auftrag noch keine Artikel hinzugefügt sein sollten. Bereits vorhandene Artikel werden überschrieben. Nach Anwendung der Auftragsvorlage kannst du schließlich weitere Artikel zum Auftrag hinzufügen.

| *Artikel hinzufügen*
|In diesem Tab kannst du optional Artikel zur Auftragsvorlage hinzufügen. Diese Artikel werden anschließend bei Anwendung der Auftragsvorlage zum Auftrag hinzugefügt. +
Setze Filter und führe eine Suche (material:search[role=skyBlue]) aus, um Artikel anzuzeigen. Füge (material:add_shopping_cart[role=green]) die gewünschten Artikel zur Auftragsvorlage hinzu. Diese werden dann im Tab *Artikel* angezeigt. +
*Menge* = Du kannst Artikel mehrmals hinzufügen. Ist dies der Fall, werden sie jeweils in einer neuen Tabellenzeile angezeigt. Alternativ kannst du im Tab *Artikel* in der Spalte *Menge* die Menge eines Artikels anpassen.

|===

Du kannst Auftragsvorlagen jederzeit anpassen. Nach jeder Änderung musst du die Auftragsvorlage speichern (material:save[role=green]). Änderungen an Auftragsvorlagen werden nicht rückwirkend auf Aufträge angewendet, sondern gelten nur ab dem Zeitpunkt der Änderung.

Auftragsvorlagen werden nur auf einen Auftrag angewendet, wenn du dies bestimmst. Möchtest du eine Auftragsvorlage immer auf bestimmte Aufträge anwenden, empfehlen wir die Einrichtung einer entsprechenden xref:automatisierung:ereignisaktionen.adoc#intable-auftragsvorlage[Ereignisaktion]. Lege in der Ereignisaktion durch Auswahl eines Ereignisses und durch Filter fest, wann und auf welche Aufträge welche Auftragsvorlage angewendet werden soll.

Möchtest du eine Auftragsvorlage bei Erstellung eines xref:auftraege:auftraege-verwalten.adoc#200[manuellen Auftrags] anwenden, wähle im Bereich *Auftragsdaten* aus der Dropdown-Liste *Vorlage verwenden* die gewünschte Auftragsvorlage aus. In der Auftragsanlage kannst du im ersten Schritt die Vorlage aus der Dropdown-Liste *Auftragsvorlage* wählen.

[#300]
== Auftragstyp Lieferauftrag nutzen

Mithilfe des Auftragstyps *Lieferauftrag* werden aus einem Hauptauftrag Lieferaufträge für die enthaltenen Auftragspositionen generiert, so dass du diese einzeln oder in Teilen verschicken kannst. So kannst du beispielsweise Artikel, die du auf Lager hast, sofort losschicken und Artikel, die du erst noch geliefert bekommst, später nachsenden. Führe dies mit unterschiedlichen oder auch nur mit einem Versanddienstleister durch. +
Lieferaufträge können *manuell*, *automatisch* oder per *Ereignisaktion* erstellt werden.

[WARNING]
.Alle Auftragspositionen in Lieferaufträge übernehmen
====
Erstellst du Lieferaufträge aus einem Auftrag müssen _alle_ Auftragspositionen des Hauptauftrags in Lieferaufträge überführt werden. Übernimmst du nicht alle Auftragspositionen in Lieferaufträge, kommt es zu Fehlern im Bestand und den Lagern.
====

[#310]
=== Merkmale von Lieferaufträgen

Im Allgemeinen besitzen Lieferaufträge folgende Eigenschaften:

* Die Auftragspositionen eines Lieferauftrages lassen sich nach dem Erzeugen des Lieferauftrages *nicht* mehr anpassen.
* Der *Preis* und das *Gewicht* eines Artikels werden aus dem Hauptauftrag übernommen.
* Die Auftragssprache wird aus dem Hauptauftrag übernommen.
* *Adressetikett*, *Lieferschein*, *Proformarechung* und *Gelangensbestätigung* können im Tab *Belege* eines Lieferauftrags generiert werden.
* Die *Rechnung* und alle weiteren Dokumente werden zentral im Hauptauftrag generiert.
* Die Bestandsreservierung für die in einem Lieferauftrag enthaltene Menge wird beim Anlegen eines Lieferauftrags vom Hauptauftrag auf den Lieferauftrag übertragen.

[IMPORTANT]
.Gemeinsamer Status
====
Der Hauptauftrag folgt immer dem Status des Lieferauftrags mit dem niedrigsten Status.
Wenn z.B. ein Auftrag in Status *5.0* zwei Lieferaufträge hat und einer dieser Lieferaufträge wechselt in den Status *6.5*, ändert sich am Status des Hauptauftrages zunächst nichts. Erst wenn der zweite Lieferauftrag ebenfalls in den Status *6.5* wechselt, wird automatisch auch der Status des Hauptauftrages zu *6.5* geändert.
====

[#320]
=== Grundeinstellungen für Lieferaufträge vornehmen

[WARNING]
.Lager pro Auftragsposition zuordnen
====
Im Menü *Einrichtung » Aufträge » Einstellungen* muss zwingend für die xref:auftraege:grundeinstellungen.adoc#intable-warehouse-assignment[Zuordnung des Lagers] die Option *b) pro Artikelposition kann ein Lager zugeordnet werden* ausgewählt werden.
====

Im Menü *Einrichtung » Aufträge » Auftragstypen » Lieferauftrag* legst du vorab fest, nach welchem Kriterium Aufträge in Lieferaufträge gesplittet werden.

[.instruction]
Optionen für das Splitten von Aufträgen in Lieferaufträge wählen:

. Öffne das Menü *Einrichtung » Aufträge » Auftragstypen » Lieferauftrag*.
. Nimm die Einstellungen anhand von <<table-order-types-delivery-order-options>> vor.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[[table-order-types-delivery-order-options]]
.Optionen für das *Splitten von Aufträgen in Lieferaufträge*
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+^| *Aufträge in Lieferaufträge splitten nach*

| *Aus*
|Es erfolgt *keine Aufsplittung*. +
*_Achtung_*: Wenn du diese Option aktivierst, können Lieferaufträge nur noch manuell angelegt werden. Das automatische Generieren sowie das Erstellen von Lieferaufträgen per Ereignisaktion sind bei dieser Auswahl nicht möglich.

| *Lager*
|Die Lieferaufträge werden anhand der verschiedenen *Lager* der Auftragspositionen erstellt.

| *Versandprofil*
|Die Lieferaufträge werden anhand der verschiedenen *Versandprofile* der Auftragspositionen erstellt.

| *Lager und Versandprofil*
|Die Lieferaufträge werden anhand der verschiedenen *Lager und der Versandprofile* der Auftragspositionen erstellt.

| *Lager und Netto-Warenbestand*
|Die Lieferaufträge werden anhand der verschiedenen *Lager und des Netto-Warenbestands* der Auftragspositionen erstellt.
|====

[#330]
=== Lieferaufträge manuell anlegen

Bei Bedarf kannst du Lieferaufträge manuell über den Hauptauftrag anlegen. Bei dieser Methode wählst du für jeden Lieferauftrag einzeln die Auftragspositionen und -mengen aus, die der Lieferauftrag enthalten soll.

Wir empfehlen, grundsätzlich für *alle* Auftragspositionen Lieferaufträge anzulegen. Verbleiben eine oder mehrere Auftragspositionen ohne Zuordnung zu einem Lieferauftrag im Hauptauftrag, kann es zu Fehlfunktionen kommen. Zudem darf die Menge, die du unter *LiefAufMenge* einträgst, nicht größer sein, als die unter *NZMenge* (nicht zugeordnete Menge) angezeigte Menge.

[.instruction]
Lieferaufträge manuell anlegen:

. Öffne das Menü *Aufträge » Aufträge bearbeiten*.
. Öffne den Auftrag, für den Lieferaufträge angelegt werden sollen.
. Wechsle in das Tab *Lief*.
. Trage in das Feld *LiefAufMenge* (Menge für den Lieferauftrag), die *Menge* ein, die in den Lieferauftrag überführt werden soll.
. Klicke anschließend auf das *Lieferauftrag anlegen* (terra:execute[]). +
→ Der Lieferauftrag wird angelegt.
. Wiederhole den Prozess, um weitere Lieferaufträge anzulegen.

[#340]
=== Lieferaufträge automatisch anlegen

[IMPORTANT]
.Bedingung für das automatische Anlegen von Lieferaufträgen
====
Lieferaufträge können nur automatisch erzeugt werden, wenn noch kein Lieferauftrag zu dem Auftrag besteht.
====

Wenn du Lieferaufträge automatisch anlegen lässt, greifen die zuvor in <<table-order-types-delivery-order-options>> beschriebenen Kriterien zum Aufsplitten in Lieferaufträge. Somit müssen die Auftragspostionen und -mengen nicht einzeln ausgewählt werden. Stattdessen überführt das System je nach gewähltem Kriterium alle Auftragspositionen automatisch in Lieferaufträge.

[.instruction]
Lieferaufträge automatisch anlegen

. Öffne das Menü *Aufträge » Aufträge bearbeiten*.
. Öffne den Auftrag, für den Lieferaufträge angelegt werden sollen.
. Wechsle in das Tab *Lief*.
. Klicke auf *Lieferauftrag automatisch anlegen* (icon:gear[role="darkGrey"]). +
→ Die Lieferaufträge werden angelegt.

[#350]
=== Lieferaufträge per Ereignisaktion anlegen

Lieferaufträge werden idealerweise über eine Ereignisaktion generiert. Du als Händler:in kannst somit bestimmen, wann und wie die Lieferaufträge zu einem Auftrag generiert werden. Im Folgenden werden drei Beispiele zum Generieren von Lieferaufträgen per Ereignisaktion beschrieben.

==== Beispiel A: Ereignisaktion "Lieferauftrag generieren bei Auftragseingang"

Wenn du möchtest, dass schon beim Eingang eines Auftrags die zugehörigen Lieferaufträge generiert werden, nutze die in <<table-event-procedure-delivery-order-when-new-order>> beschriebene Ereignisaktion.

Da diese Ereignisaktion direkt beim Auftragseingang greift, wird der Status des Hauptauftrags nicht beachtet. Somit werden auch Lieferaufträge von Aufträgen in Status *3.0* (oder *1.0* wenn du mit Auktionsplattformen wie eBay arbeitest) generiert. Diese nehmen beim Generieren den Status des Hauptauftrages an.

:table-event-procedure: <<table-event-procedure-delivery-order-when-new-order>>
include::_includes:partial$event-procedure.adoc[]

[[table-event-procedure-delivery-order-when-new-order]]
.Ereignisaktion "Lieferauftrag generieren bei Auftragseingang" einrichten
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

| *Ereignis*
| *Neuer Auftrag*
|

| *Filter 1*
| *Auftrag > Auftragstyp*
| *Auftrag*

| *Filter 2*
| *Auftrag > Auftragslager*
| *Mehrere Lager pro Auftrag*

| *Aktion*
| *Auftrag > Lieferaufträge generieren*
|

|====

==== Beispiel B: Ereignisaktion "Lieferauftrag generieren bei Wechsel zu Status 5" einrichten

Wenn du möchtest, dass zu einem Auftrag, der in den Status 5.0 (Freigabe Versand) wechselt, Lieferaufträge generiert werden, nutze die in <<table-event-procedure-delivery-order-status-5>> beschriebene Ereignisaktion.

Nach dem Generieren der Lieferaufträge darfst du den Hauptauftrag nicht mehr ändern, damit die Summe der Artikel der Lieferaufträge der des Hauptauftrags entspricht.

:table-event-procedure: <<table-event-procedure-delivery-order-status-5>>
include::_includes:partial$event-procedure.adoc[]

[[table-event-procedure-delivery-order-status-5]]
.Ereignisaktion "Lieferauftrag generieren bei Wechsel zu Status 5" einrichten
[cols="1,3,3"]
|===
|Einstellung |Option |Auswahl

| *Ereignis*
| *Auftragsänderung > Statuswechsel*
| *Freigabe Versand*

| *Filter 1*
| *Auftrag > Auftragstyp*
| *Auftrag*

| *Filter 2*
| *Auftrag > Auftragslager*
| *Mehrere Lager pro Auftrag*

| *Aktion*
| *Auftrag > Lieferaufträge generieren*
|

|===

==== Beispiel C: Ereignisaktion "Lieferauftrag generieren bei Rechnungserzeugung"

Wenn du möchtest, dass zu einem Auftrag beim Erzeugen der Rechnung die Lieferaufträge angelegt werden, nutze die in <<table-event-procedure-invoice-generated>> beschriebene Ereignisaktion. +
Somit kannst du am Hauptauftrag solange Änderungen vornehmen, bis du ihn durch den Rechnungsdruck zum Versand freigibst. Folgende Einstellungen sind nötig:

:table-event-procedure: <<table-event-procedure-invoice-generated>>
include::_includes:partial$event-procedure.adoc[]

[[table-event-procedure-invoice-generated]]
.Ereignisaktion "Lieferauftrag generieren bei Rechnungserzeugung" einrichten
[cols="1,3,3"]
|===
|Einstellung |Option |Auswahl

| *Ereignis*
| *Dokumente > Rechnung generiert*
|

| *Filter 1*
| *Auftrag > Auftragstyp*
| *Auftrag*

| *Filter 2*
| *Auftrag > Auftragslager*
| *Mehrere Lager pro Auftrag*

| *Aktion*
| *Auftrag > Lieferaufträge generieren*
|

|===

[#360]
=== Haupt- und Lieferaufträge bearbeiten

Um den Hauptauftrag öffnen zu dürfen, müssen variable Benutzer:innen über die xref:business-entscheidungen:benutzerkonten-zugaenge.adoc#100[Berechtigung] für alle Lager der Lieferaufträge eines Hauptauftrags verfügen. Prüfe dazu die Einstellungen im Menü *Einrichtung » Einstellungen » Benutzer » Konten » Tab: Berechtigungen*.

Wenn du einen Hauptauftrag löschen möchtest, müssen zuerst die Lieferaufträge gelöscht werden. Lieferaufträge können einzeln oder über die Gruppenfunktion in der Auftragssuche gelöscht werden. Erst danach kann der Hauptauftrag gelöscht werden. Beachte aber, dass Aufträge nicht gelöscht werden können, sobald steuerrelevante Dokumente für diesen Auftrag existieren.

Es können weitere Auftragspositionen zum Hauptauftrag hinzugefügt oder daraus gelöscht werden. Allerdings können nur Auftragspositionen, die nicht in Lieferaufträgen enthalten sind, aus dem Hauptauftrag gelöscht werden. Die Menge der Artikel im Hauptauftrag lässt sich erhöhen oder verringern. Löschen solltest du jedoch nur *nicht zu Lieferaufträgen zugeordnete Mengen*.

[WARNING]
.Löschen von Positionen in einem Lieferauftrag
====
Technisch möglich ist zwar auch das Löschen von Positionen, die bereits in einem Lieferauftrag enthalten sind. Dies solltest du jedoch vermeiden, um Fehlfunktionen zu verhindern.
====

[#400]
== Auftragstyp Retoure nutzen

Der Auftragstyp Retoure bildet den Geschäftsvorfall einer Retoure ab. Retouren können manuell erfasst werden. Zusätzlich kannst du auch deinen Webshop-Kund:innen erlauben, Retouren über den *Mein Konto* Bereich anzumelden. Das Erfassen einer Retoure bucht die retournierten Artikel noch nicht zurück in den Warenbestand. Du erfasst also die retournierten Artikel zunächst und entscheidest anschließend, ob die Artikel wieder zum Bestand gebucht werden oder ob weitere Schritte, wie z.B. eine Reparatur, notwendig sind. Die Retoure ist ein untergeordneter Auftragstyp, da Retouren entweder einem Auftrag oder einer Gewährleistung zugeordnet sind.
Bevor du Retouren erfassen kannst, lege xref:auftraege:auftraege-verwalten.adoc#410[Retourengründe] und xref:auftraege:auftraege-verwalten.adoc#420[Artikelstatus für retournierte Artikel] an.

Der Standardstatus für Retouren ist Status 9. Jede Retoure, die erfasst wird, erhält automatisch diesen Status. Du kannst jedoch jederzeit im Menü *Einrichtung » Aufträge » Einstellungen* einen anderen Status als xref:auftraege:grundeinstellungen.adoc#intable-default-status-return[Standard-Status Retoure] festlegen.

[#410]
=== Retourengründe eintragen

Du kannst bis zu 20 Retourengründe eintragen. Beim Erfassen einer Retoure wählst du dann für jede Auftragsposition einen Grund. Anhand von Retourengründen ist später nachvollziehbar, ob ein Artikel besonders häufig wegen des selben Grundes retourniert wurde. Die Retourengründe können in mehreren Sprachen hinterlegt werden.

[.instruction]
Retourengründe anlegen:

. Öffne das Menü *Einrichtung » Aufträge » Auftragstypen » Retoure*.
. Wähle die *Sprache* aus der Dropdown-Liste aus.
. Trage *Gründe* für Retouren für die ausgewählte Sprache ein.
. *Speichere* die Einstellungen.
. Wiederhole dies ggf. für weitere Sprachen.

[#420]
=== Status für retournierte Artikel eintragen

Du kannst bis zu 12 Artikelstatus anlegen. Die Status kannst du z.B. nutzen, um einerseits den Zustand der retournierten Artikel, aber auch um den Fortschritt beim Bearbeiten der retournierten Artikel anzugeben. Die Status stehen in einer Retoure im Tab *Übersicht* bei den Auftragspositionen zur Wahl. Um je nach Fortschritt der Bearbeitung verschiedene Status zuzuweisen, lege die benötigten Status an. Du kannst Retourenstatus in mehreren Sprachen hinterlegen.

[.instruction]
Status für retournierte Artikel eintragen:

. Öffne das Menü *Einrichtung » Aufträge » Auftragstypen » Retoure*.
. Wähle die *Sprache* aus der Dropdown-Liste aus.
. Trage die gewünschten *Status* für die Zuordnung zurückgesendeter Artikel für die ausgewählte Sprache ein.
. *Speichere* (icon:save[role="green"]) die Einstellungen.
. Wiederhole dies ggf. für weitere Sprachen.

[#440]
=== Retoure erfassen und bearbeiten

Eine Retoure erfasst du manuell, wenn ein Paket bei dir eingegangen ist oder du erlaubst deinen registrierten Webshop-Kund:innen, direkt im Kundenkonto des Shops Retouren anzumelden. Nachdem eine Retoure erfasst wurde, werden weitere Bearbeitungsmöglichkeiten sichtbar. So kannst du z.B. den Artikelstatus der retournierten Artikel erst nach dem Erfassen angeben.

==== Retoure erfassen

[.instruction]
Gehe folgendermaßen vor, um eine Retoure zu erfassen:

. Öffne das Menü *Aufträge » Aufträge bearbeiten*.
. Öffne den Auftrag oder die Gewährleistung, für den eine Retoure angelegt werden soll.
. Klicke im Tab *Übersicht* unter *Retoure* auf *anlegen*. +
→ Ein Bearbeitungsfenster wird geöffnet.
. Nimm die Einstellungen anhand <<table-settings-return>> vor.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Die Retoure wird angelegt und in einem eigenen Tab geöffnet.

[[table-settings-return]]
.Optionen beim Erfassen einer Retoure
[cols="1,3"]
|===
|Einstellung |Erläuterung

2+^| *Einstellungen*

| *Status*
|Einen Status für die Retoure wählen. Voreingestellt ist der Standardstatus, der im Menü *Einrichtung » Aufträge » Einstellungen* gespeichert wurde.

| *Eigner*
|Einen Eigner auswählen, der dem Retourenauftrag zugewiesen wird.

| *Paketcode der Retoure*
|Paketcode der Retoure eintragen.

2+^| *Artikel*

| *Retourengrund übertragen*
|Einen Grund für die Retoure wählen, der für alle Artikel der Retoure gilt. +
Wenn hier ein Grund gewählt wird, hat dieser Grund Priorität gegenüber den einzeln wählbaren Gründen auf Artikelpositionsebene.

| *Übernehmen*
|Artikel wählen, die in die Retoure übernommen werden sollen.

| *Menge*
|Artikelmenge eintragen, die in die Retoure übernommen werden soll.

| *Grund der Retoure*
|Individuellen Grund für die Retoure eines Artikels wählen. +
*_Hinweis_*: Wenn ein Grund für alle gewählt wurde, hat dieser Grund Priorität.

| *Artikel*
|Der Artikelname kann hier angepasst werden.
|===

Nachdem eine Retoure erfasst wurde, kannst du den Artikelstatus für retournierte Artikel wählen. Außerdem werden weitere Bearbeitungsmöglichkeiten sichtbar.

[#450]
=== Rücksendeschein erstellen

Einen Rücksendeschein kannst du deinen Kund:innen bei Zustellung der Ware im Paket beilegen. In diesem Fall sollte der Rücksendeschein Blankofelder für die Retourengründe enthalten. Du kannst deinen Kund:innen aber auch erlauben den Rücksendeschein im *Mein Konto* Bereich auszufüllen, auszudrucken und der Retoure beizulegen.
Bevor Rücksendescheine erzeugt werden können, muss die Dokumentenvorlage xref:auftraege:ruecksendeschein-erzeugen.adoc#[Rücksendeschein] im Menü *Einrichtung » Mandant » [Mandant wählen] » Standorte » [Standort wählen] » Dokumente » Rücksendeschein* eingerichtet werden.

[TIP]
.Retourengründe auf der Vorlage einstellen
====
Du kannst einen unausgefüllten Rücksendeschein in jedem Paket beilegen, dass du versendest. Hierfür generierst du den Rücksendeschein direkt im Auftrag, ohne dass es überhaupt eine Retoure geben muss. Die zweite Möglichkeit ist, dass du deinen Webshop-Kund:innen erlaubst Retouren im Mein-Konto-Bereich des Shops anzumelden und hier die Retourengründe anzugeben. Anschließend kann der Rücksendeschein ausgefüllt ausdruckt werden. Egal wie du den Rücksendeschein deinen Kund:innen zukommen lässt: Damit Retourengründe eingetragen werden können, musst du die Spalte Retourengründe unterhalb der Artikelpositionen platzieren.
====

Prüfe die Artikelpositionen der Retoure und ändere bei Bedarf die Optionen, z.B. die Menge eines Artikels, bevor du im Tab *Belege* der Retoure einen Rücksendeschein erzeugst.

[.instruction]
Rücksendeschein manuell erstellen:

. Öffne die Retoure und klicke auf das Tab *Belege*.
. Wähle die Option *Rücksendeschein* aus der Dropdown-Liste *Beleg erstellen*. +
→ Ein Fenster öffnet sich.
. Nimm die Einstellungen für den Rücksendeschein vor.
. *Speichere* (icon:save[role="green"]) die Einstellungen, um den Rücksendeschein zu generieren.

[TIP]
.Rücksendeschein automatisch generieren
====
Richte eine Ereignisaktion ein, die den Rücksendeschein automatisch generiert. Wenn du hier als Ereignis *Neue Retoure (durch Kunden)* einstellst und nach der Herkunft Webshop filterst, kannst du ausgefüllte Rücksendescheine generieren und musst diese dann lediglich noch zum Download für Kund:innen bereitstellen.
====

[#460]
=== Warenbestand zurückbuchen

Wenn du einen Artikel über eine Retoure zurück erhältst, kannst du den Warenbestand ganz oder teilweise zurückbuchen oder auch den gesamten Warenausgang zurücksetzen.

[.instruction]
Warenbestand zurückbuchen:

. Öffne das Menü *Aufträge » Aufträge bearbeiten*.
. Wähle in den Filtereinstellungen unter *Typ* die Option *Retoure*.
. Klicke auf *Suchen* (icon:search[role="blue"]). +
→ Die Retourenaufträge werden aufgelistet.
. Öffne die Retoure, für die der Bestand zurückgebucht werden soll.
. Öffne das Tab *Einstellungen*.
. Klicke bei der Option *Warenbestand* auf *Warenbestand einbuchen*. +
→ Ein Bearbeitungsfenster öffnet sich.
. Nimm die Einstellungen anhand <<table-reversing-stock-return>> vor.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

Die Vorgehensweise zum Zurückbuchen des Warenbestands ist auch für Retouren zu Aufträgen mit Lieferaufträgen gleich. Dass Lieferaufträge vorhanden sind, wird dir im Bearbeitungsfenster für das Rückbuchen angezeigt.

[[table-reversing-stock-return]]
.Optionen für das Rückbuchen des Warenbestands
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Warenausgang komplett zurücksetzen*
|Setzt den Warenausgang vollständig zurück. Auch das Datum des Warenausgangs wird gelöscht.

2+^| *Warenbestand zurückbuchen*

| *Komplette Menge wählen*
|Trägt die komplette Menge des Artikels im Auftrag in die Spalte *Rückbuchen* ein.

| *Komplette Menge abwählen*
|Setzt die Artikelmengen in der Spalte *Rückbuchen* auf 0.

| *Rückbuchen*
|Wenn Teilmengen zurückgebucht werden sollen, dann hier die Artikelmengen manuell eintragen.

| *Lager*
|Das Lager wählen, in das die Artikel zurückgebucht werden sollen.

| *Lagerort*
|Den Lagerort wählen, in den die Artikel zurückgebucht werden sollen.

| *Menge im Auftrag*
|Zeigt die Menge der Artikel an, die im Auftrag enthalten sind.

| *Zurückgebucht*
|Zeigt bereits zurückgebuchte Artikelmengen an.

| *Charge*
|Zeigt die Chargennumer des Artikels an.

| *MHD*
|Zeigt das Mindeshaltbarkeitsdaum des Artikels an.

| *ID*
|ID des Artikels.

| *Artikel*
|Name des Artikels.
|====

[TIP]
.Retouren-Artikel im Zulauf
====
Im Menü xref:warenwirtschaft:rueckstandsliste-verwalten.adoc#400[Waren » Retouren » Zulauf] findest du eine Übersicht aller durch Retouren im Zulauf befindlichen Artikel.
====

[#500]
== Auftragstyp Gutschrift nutzen

Bei einer Gutschrift bekommen deine Kund:innen einen Betrag zurückerstattet. Dies kann beispielsweise nach einer xref:auftraege:auftraege-verwalten.adoc#400[Retoure] der Fall sein. Bei der Gutschrift in plentymarkets handelt es sich also nicht um eine Art umgekehrte Rechnung, sondern um eine Rückzahlung. Gutschriftaufträge erzeugst du unter *Aufträge » Aufträge bearbeiten* aus einem Auftrag. Eine Gutschrift ist also immer einem Auftrag zugeordnet. Die in einem Gutschriftauftrag erzeugten Gutschriftbelege werden auch in Buchhaltungsexporten, wie dem *DATEV*-Export, berücksichtigt.

[#510]
=== Standardstatus für Gutschriften speichern

Bevor du eine Gutschrift anlegst, prüfe den xref:auftraege:grundeinstellungen.adoc#intable-default-status-credit-note[Standard-Status für Gutschriften] im Menü *Einrichtung » Aufträge » Einstellungen*. Passe den Standardstatus bei Bedarf an und speichere die Einstellungen.

[#520]
=== Gutschrift anlegen

Eine Gutschrift ist immer mit einem bestehenden Auftrag in deinem plentymarkets System verknüpft. Deshalb musst du den gewünschten Auftrag zunächst in der Auftragsübersicht öffnen, bevor du eine Gutschrift angelegen kannst.

[TIP]
.Gutschriften im Hauptauftrag oder im Retourenauftrag anlegen
====
Hat eine Kund:in den Auftrag bereits gezahlt, beispielsweise per Vorkasse, und entscheidet sich vor dem Warenausgang gegen den Kauf, empfehlen wir den Auftrag zu stornieren und direkt im Hauptauftrag eine Gutschrift über alle Auftragspositionen anzulegen.

Kommt es nach erfolgter Zahlung, Warenausgang und Zustellung der Ware für eine oder alle Auftragspositionen zu einer xref:auftraege:auftraege-verwalten.adoc#400[Retoure] oder im Folgenden zu einem xref:auftraege:auftraege-verwalten.adoc#700[Reparaturauftrag], lege die Gutschrift direkt im entsprechenden Retouren- oder Reparaturauftrag an.
====

:ordertype: Gutschriften

[.instruction]
Gutschriftauftrag anlegen:

. Öffne das Menü *Aufträge » Aufträge bearbeiten*.
. Suche (icon:search[role="blue"]) den Auftrag, zu dem du eine Gutschrift anlegen möchtest.
. Öffne den Auftrag. +
→ Der Auftrag wird in einem eigenen Tab geöffnet.
. Klicke auf das Tab *Übersicht*.
. Klicke auf die Dropdown-Liste *Gutschrift*.
. Wähle eine Option. Beachte dazu die Erläuterungen in <<tabelle-{ordertype}-anlegen>>. +
→ Der Gutschriftauftrag wird angelegt und in einem eigenen Tab geöffnet.

include::partial$tabelle-aus-optionen-anlegen.adoc[]

Wenn bereits ein Gutschriftauftrag zu einem Auftrag angelegt wurde, wird im Tab *Übersicht* des Haupfauftrags rechts der Hinweis *Gutschrift verfügbar* angezeigt. Zusätzlich kannst du bereits angelegte Gutschriftaufträge im Tab *Übersicht* des Hauptauftrags über die Dropdown-Liste *Gutschrift / suchen* aufrufen.

[#530]
=== Gutschriftbeleg erstellen

Nach dem Anlegen des Gutschriftauftrags muss ein Gutschriftbeleg direkt im Gutschriftauftrag erstellt werden. Vor dem ersten Erzeigen eines xref:auftraege:gutschriften-erzeugen.adoc#[Gutschriftbelegs], muss die Dokumentenvorlage im Menü *Einrichtung » Mandant » [Mandant wählen] » Standorte » [Standort wählen] » Dokumente » Gutschrift* eingerichtet werden.

Bevor du den Gutschriftbeleg im Tab *Belege* des Gutschriftauftrags erzeugst, solltest du die im Gutschriftauftrag enthaltenen Auftragspositionen prüfen und bei Bedarf ändern.

[.instruction]
Gutschriftbeleg erstellen:

. Öffne den Gutschriftauftrag, für den ein Gutschriftbeleg erzeugt werden soll.
. Wähle die Option *Gutschrift* aus der Dropdown-Liste unter *Beleg / erstellen*.
. Klicke auf *Beleg erstellen*. +
→ Der Gutschriftbeleg wird erzeugt und in einem eigenen Tab geöffnet.

Erstellte Gutschriften weisen jeweils eine Referenz zu der Rechnung des dazugehörigen Auftrages auf. Im Tab *Dokumente* eines Auftrags wird dies in der Benennung der Gutschrift angezeigt.

[#540]
=== Gutschriftbeleg korrigieren und stornieren

Einen Gutschriftauftrag und den dazugehörigen Gutschriftbeleg korrigierst du, indem du zunächst einen *Stornobeleg Gutschrift* erzeugst. Danach ist der Gutschriftauftrag auch wieder entsperrt. Denn nach dem Erstellen eines Gutschriftbelegs ist der Gutschriftauftrag selbst für die Bearbeitung gesperrt, damit steuerrelevante Daten nicht verändert werden können. Anschließend kann der Gutschriftauftrag wieder bearbeitet werden. Du kannst die Daten korrigieren und einen neuen Gutschriftbeleg erstellen.

Vor dem ersten Erzeugen des Dokuments muss im Menü *Einrichtung » Mandant » [Mandant wählen] » Standorte » [Standort wählen] » Dokumente » Stornobeleg Gutschrift* zunächst die xref:auftraege:auftragsdokumente.adoc#300[Vorlage] für das Dokument *Stornobeleg Gutschrift* eingerichtet werden.

[IMPORTANT]
.Stornieren eines Gutschriftbelegs
====
Das Stornieren eines Gutschriftbelegs dient der nachvollziehbaren Korrektur von steuerrelevanten Daten und *nicht* der Stornierung eines Gutschriftauftrags selbst.
====

Gehe zur Korrektur eines Gutschriftauftrags und der Erstellung eines *Stornobelegs Gutschrift* wie im Folgenden beschrieben vor.

[.instruction]
Gutschriftauftrag korrigieren:

. Öffne das Menü *Aufträge » Aufträge bearbeiten*.
. Öffne den Auftrag, in dem du den Gutschriftbeleg stornieren möchtest.
. Wechsle in das Tab *Belege*.
. Wähle aus der Dropdown-Liste *Beleg erstellen* den *Stornobeleg*. +
→ Ein Fenster mit optionalen Einstellungen öffnet sich.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Der Stornobeleg wird erzeugt und die Auftragseinstellungen des Gutschriftauftrags entsperrt.
. Bearbeite die Daten, die du korrigieren möchtest.
. Wechsle wieder in das Tab *Belege*.
. Wähle aus der Dropdown-Liste *Beleg erstellen* das Dokument *Gutschrift*. +
→ Ein Fenster mit optionalen Einstellungen öffnet sich.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Die Gutschrift wird erzeugt und die Auftragseinstellungen des Gutschriftauftrags erneut gesperrt.

[#550]
=== Rückzahlungen buchen

Nachdem du einen Gutschriftbeleg erstellt hast, muss die Rückzahlung des gutgeschriebenen Betrags in deinem plentymarkets System gebucht werden. Rückzahlungen über bestimmte Zahlungsarten, die du in deinem System eingerichtet hast, buchst du direkt im Tab *Einstellungen* des Gutschriftauftrags. Die Option *Rückzahlung an Kunden* wird nur bei den Zahlungsarten *PayPal*, *ClickandBuy* und *heidelpay* angezeigt.

[IMPORTANT]
.Bedingung bei PayPal
====
Bei *PayPal* ist es nicht möglich, höhere Beträge einzugeben als mit der ursprünglichen Paypal-Transaktion bezahlt wurden.
====

[.instruction]
Rückzahlung im Tab *Einstellungen* buchen:

. Öffne das Menü *Aufträge » Aufträge bearbeiten*.
. Öffne den Gutschriftauftrag, für den du eine Rückzahlung buchen möchtest.
. Öffne das Tab *Einstellungen*.
. Klicke bei der Option *Rückzahlung* auf das *Zahlungs-Icon*.
. Prüfe den *Betrag* der Rückzahlung und passe diesen falls nötig an.
. Klicke auf das *Zahnrad* (icon:gear[]), um die Rückzahlung zu buchen. +
→ Die Rückzahlung wird gebucht.

Alternativ ist es auch möglich, die Rückzahlung im Tab *Zahlung* des Gutschriftauftrags zu buchen. Im Tab *Zahlung* siehst du alle Zahlungen und Teilzahlungen, die zum Auftrag gehören. Das Rückbuchen der Zahlung in diesem Tab ist vor allem notwendig, wenn die Zahlung für den Hauptauftrag nicht über eine in plentymarkets integrierte Zahlungsart getätigt wurde.

[.instruction]
Rückzahlung im Tab *Zahlung* buchen:

. Öffne das Menü *Aufträge » Aufträge bearbeiten*.
. Öffne den Gutschriftauftrag, für den du eine Rückzahlung buchen möchtest.
. Öffne das Tab *Zahlung*.
. Klicke auf das Icon *Zahlung buchen*.
. Gib den *Betrag* (Soll) sowie falls nötig eine *Währung* und einen *Verwendungszweck* ein.
. Klicke auf *Zahlung buchen*. +
→ Die Rückzahlung wird gebucht und wird im Tab *Zahlung* angezeigt.

[#560]
=== Warenbestand zurückbuchen

Wenn der Warenausgang bereits gebucht wurde und die Waren beispielsweise im Rahmen einer xref:auftraege:auftraege-verwalten.adoc#400[Retoure] wieder in das Lager zurückgebucht werden sollen, wird dies im Tab *Einstellungen* des Gutschriftauftrags vorgenommen.

[.instruction]
Warenbestand zurückbuchen:

. Öffne das Menü *Aufträge » Aufträge bearbeiten*.
. Öffne den Gutschriftauftrag, für den der Warenbestand zurückgebucht werden soll.
. Wechsle in das Tab *Einstellungen*.
. Klicke bei der Option *Warenausgang* auf den Link *Warenbestand einbuchen*.
. Wähle im angezeigten Fenster die gewünschte Option gemäß den Erläuterungen in <<table-settings-reverse-stock>>.
. Klicke auf *Speichern* (icon:save[role="green"]), um den Vorgang auszuführen.

[[table-settings-reverse-stock]]
.Optionen zur Rückbuchung des Warenbestandes
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Warenausgang komplett zurücksetzen*
|Setzt den Warenausgang vollständig zurück. Auch das Datum des Warenausgangs im Hauptauftrag wird gelöscht.

| *Warenbestand zurückbuchen*
|Bucht die Artikel vollständig oder teilweise zurück. Bei dieser Option wird der Warenausgang *nicht* zurückgesetzt.

| *Komplette Menge wählen*
|Trägt die komplette Menge des Artikels im Auftrag in das Feld *Rückbuchen* ein.

| *Komplette Menge abwählen*
|Setzt die Artikelmengen unter *Rückbuchen* auf Null.

| *Rückbuchen*
|Die Artikelmenge(n) eintragen, die zurückgebucht werden soll(en), wenn Teilmengen zurückgebucht werden sollen.

| *Lager*
|Das Lager wählen, in das die Artikel zurückgebucht werden sollen.

| *Lagerort*
|Den Lagerort wählen, in den die Artikel zurückgebucht werden sollen.

| *Menge im Auftrag*
|Zeigt die Menge der Artikel an, die im Auftrag enthalten sind.

| *Zurückgebucht*
|Zeigt bereits zurückgebuchte Artikelmengen an.

| *Charge*
|Zeigt die Chargennummer der Artikel an, die im Auftrag enthalten sind.

| *MHD*
|Zeigt das Mindesthaltbarkeitsdatum der Artikel an, die im Auftrag enthalten sind.

| *ID*
|ID des Artikels

| *Artikel*
|Name des Artikels
|====

[#600]
== Auftragstyp Gewährleistung nutzen

Gewährleistungen sind xref:auftraege:auftraege-verwalten.adoc#400[Retouren] relativ ähnlich, denn in beiden Fällen bekommst du Waren eines Auftrags im *Status 7* wieder zurückgesendet. Im Gegensatz zur Retoure erwarten Kund:innen bei einer Gewährleistung aber entweder eine neue Lieferung oder eine Rückerstattung des Rechnungsbetrags mittels einer xref:auftraege:auftraege-verwalten.adoc#500[Gutschrift].

[TIP]
.Garantie vs. Gewährleistung
====
Im Gegensatz zur freiwillig erklärten Garantie handelt es sich bei der Gewährleistung um die *gesetzliche Pflicht* der Händler:innen, Mängel am Artikel, die bereits bei Lieferung bestanden haben, für Käufer:innen kostenlos zu beseitigen. Käufer:innen können die Gewährleistung gerichtlich bis zu 2 Jahre bei beweglichen Artikeln oder 3 Jahre bei unbeweglichen Artikeln geltend machen. Ab 6 Monaten nach Erhalt der Ware müssen Käufer:innen jedoch beweisen, dass die Mängel bereits bei Erhalt der Ware vorhanden war.
====

Wenn ein Gewährleistungsfall vorliegt, entscheidest du als Händler:in, ob du Käufer:innen die Kosten erstattest, den Artikel reparierst oder den Artikel austauschst. Soll ein Umtausch durchgeführt werden, lege eine *Gewährleistung* an. Möchtest du das Geld erstatten, lege eine xref:auftraege:auftraege-verwalten.adoc#500[Gutschrift] im Tab *Übersicht* der Gewährleistung an. Ob du die *Versandkosten* in einer Gewährleistung übernimmst oder nicht, wählst du in den xref:auftraege:grundeinstellungen.adoc#intable-shipping-costs-in-warranty[Grundeinstellungen] im Menü *Einrichtung » Aufträge » Einstellungen*.

[TIP]
.Einstellungen einer Gewährleistung
====
Wenn du aus einem Auftrag heraus eine Gewährleistung erzeugst, wird automatisch das *Versandprofil* des Auftrags übernommen. Die Einstellungen sind jedoch in der Gewährleistung änderbar. Bei *Lieferaufträgen* wird ebenfalls automatisch das korrekte Lager eingestellt. Die *Zahlungsart* bei Gewährleistungen ist änderbar.
====

[#610]
=== Gewährleistung anlegen

Normalerweise legst du eine Gewährleistung in einem bestehenden Retourenauftrag an. Es ist jedoch auch möglich, diese direkt aus dem zugrunde liegenden Hauptauftrag heraus anzulegen.

Wird die Ware nach Lieferung beanstandet und du entscheidest dich beispielsweise aus Kostengründen gegen die Rücksendung der Ware, lege die Gewährleistung direkt im Hauptauftrag an.

Möchtest du dagegen erst den Eingang der Retoure abwarten und die Ware prüfen, lege zunächst einen Retourenauftrag an und erstelle im Rahmen der Abwicklung dort eine Gewährleistung.

:ordertype: Gewährleistungen

[.instruction]
Eine Gewährleistung anlegen:

. Öffne das Menü *Aufträge » Aufträge bearbeiten*.
. Öffne den gewünschten Haupt- oder Retourenauftrag.
. Klicke auf die Dropdown-Liste *Gewährleistung*.
. Wähle eine Option. Beachte dazu die Erläuterungen in <<tabelle-{ordertype}-anlegen>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Die Gewährleistung wird angelegt und in einem eigenen Tab geöffnet.

include::partial$tabelle-aus-optionen-anlegen.adoc[]

[#620]
=== Gewährleistung bearbeiten

Gewährleistungsaufträge werden in der Auftragsübersicht angezeigt. Öffne eine Gewährleistung, um beispielsweise einen zusätzlichen *Preis* einzugeben, wenn du dem Käufer einen höherpreisigen Artikel als Ersatz liefern willst. Falls nötig, können hier auch die Mengen der in der Gewährleistung enthaltenen Auftragspositionen verändert werden. Um eine Gewährleistung zu bearbeiten, gehe wie im Folgenden beschrieben vor.

[.instruction]
Gewährleistung bearbeiten:

. Öffne das Menü *Aufträge » Aufträge bearbeiten*.
. Wähle im Tab *Filter* für den Filter *Typ* die Option *Gewährleistung*.
. Klicke auf *Suchen* (icon:search[role="blue"]). +
→ Es werden nur Gewährleistungen aufgelistet.
. Klicke in die Zeile der Gewährleistung, die du bearbeiten möchtest. +
→ Die Gewährleistung wird geöffnet und der Artikel kann über das Tab *Bearbeiten* bearbeitet werden.


[#630]
=== Gewährleistung abschließen

Zum Abschließen einer Gewährleistung musst du, wenn für die Ersatzware ein Aufpreis berechnet wird, zunächst eine Rechnung in der Gewährleistung erzeugen. Falls du keine Ersatzware versendest, sondern dich mit der Käufer:in auf einen nachträglichen Preisnachlass auf die beanstandete Ware einigst, legst du eine Gutschrift im Hauptauftrag an.

Um die Bearbeitung einer Gewährleistung durch einen Umtausch abzuschließen, gehe wie im Folgenden beschrieben vor.

[.instruction]
Gewährleistung durch Umtausch abschließen:

. Öffne in der Gewährleistung das Tab *Belege*.
. Wähle *Rechnung* aus der Dropdown-Liste *Beleg erstellen*. +
→ Ein neues Bearbeitungsfenster öffnet sich. +
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Die Rechnung wird erzeugt und in einem eigenen Tab geöffnet.
. Wechsle in das Tab *Einstellungen*.
. Klicke in der Zeile *Warenausgang* auf das Symbol *Warenausgang buchen*. +
→ Der Warenausgang wird gebucht und der *Status* wechselt automatisch zu *[7] Warenausgang gebucht*.
. Wechsle in das Menü *Aufträge » Aufträge bearbeiten*.
. Setze den Status der Gewährleistung manuell auf Status *[10] Gewährleistung*.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[TIP]
.Zahlungseingang bei Gewährleistungen buchen
====
Grundsätzlich müssen Zahlungen zu Gewährleistungen nur dann gebucht werden, wenn mit Käufer:innen ein Aufpreis vereinbart wurde. In diesem Fall buchst du den Zahlungseingang nach erfolgter Zahlung im Tab *Zahlung* der Gewährleistung.
====

Um die Bearbeitung einer Gewährleistung durch eine Gutschrift an den Käufer abzuschließen, gehe wie im Folgenden beschrieben vor:

[.instruction]
Gewährleistung durch Gutschrift abschließen:

. Öffne den Haupt- oder Retourenauftrag zur Gewährleistung, für die du eine Gutschrift anlegen möchtest.
. Öffne das Tab *Übersicht*
. Klicke auf die Dropdown-Liste *Gutschrift* und dort auf die Einstellung *anlegen*. +
→ Der Gutschriftauftrag wird angelegt und in einem eigenen Tab geöffnet.

Der weitere Bearbeitungsprozess läuft identisch mit dem regulären Anlegen einer Gutschrift und dem Erzeugen eines Gutschriftbelegs ab und wird im Kapitel xref:auftraege:auftraege-verwalten.adoc#500[Auftragstyp Gutschrift nutzen] detailliert beschrieben.

[#700]
== Auftragstyp Reparatur nutzen

Reparaturen werden in plentymarkets durch einen eigenen Auftragstyp abgebildet. Reparaturen bestehen aus retournierter, reparaturbedürftiger Ware. Reparaturaufträge können daher nur aus xref:auftraege:auftraege-verwalten.adoc#400[Retourenaufträgen] angelegt werden.

[#710]
=== Status für Reparaturen anlegen

Hinterlege vor dem Anlegen von Reparaturen verschiedene *Status* für die einzelnen Stationen des Reparaturvorgangs, um den Reparaturverlauf in deinem plentymarkets System genau nachvollziehen zu können. Die Reparaturstatus können in mehreren Sprachen hinterlegt werden.

[.instruction]
Status für Reparaturen hinterlegen:

. Öffne das Menü *Einrichtung » Aufträge » Auftragstypen » Reparatur*.
. Wähle die *Sprache* aus der Dropdown-Liste aus.
. Trage die von dir benötigten *Status* für Reparaturen für die ausgewählte Sprache ein.
. *Speichere* (icon:save[role="green"]) die Einstellungen.
. Wiederhole dies ggf. für weitere Sprachen.

[#720]
=== Zustände für Reparaturen anlegen

Mit einem *Zustand* kannst du den Artikel genau beschreiben, z.B. ob dieser überhaupt eine Reparatur benötigt oder auch, dass es nicht möglich ist, diesen zu reparieren. Die Zustände können in mehreren Sprachen eingetragen werden.

[.instruction]
Zustände für Reparaturen anlegen:

. Öffne das Menü *Einrichtung » Aufträge » Auftragstypen » Reparatur*.
. Wähle die *Sprache* aus der Dropdown-Liste aus.
. Trage die von dir benötigten *Zustände* für die Zuordnung der Artikelpositionen für die ausgewälte Sprache ein. +
. *Speichere* (icon:save[role="green"]) die Einstellungen.
. Wiederhole dies ggf. für weitere Sprachen.

[#730]
=== Reparatur anlegen

[.instruction]
Gehe wie beschrieben vor, um eine Reparatur anzulegen:

. Öffne das Menü *Aufträge » Aufträge bearbeiten*.
. Öffne die Retoure, zu der du eine Reparatur anlegen möchtest.
. Öffne das Tab *Übersicht*
. Klicke auf die Dropdown-Liste *Reparatur* und dort auf die Einstellung *anlegen*. +
→ Ein Bearbeitungsfenster öffnet sich. Gib den gewünschten *Status* und den *Zustand* der Reparatur an. Wähle die zu reparierenden *Artikel* aus. Gib optional einen *Hinweis* ein.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Die Reparatur wird angelegt und in einem eigenen Tab geöffnet.

[#740]
=== Reparatur bearbeiten

Je nach Grund der Rücksendung oder Zustand der zu reparierenden Artikel müssen bei der Bearbeitung verschiedene Schritte durchgeführt werden. +
Da es sich bei einer Reparatur um einen eigenen Auftragstyp handelt, kannst du direkt im Tab *Übersicht* der Reparatur nach den bereits beschriebenen Vorgehensweisen entweder eine Gutschrift, eine Gewährleistung oder eine Retoure anlegen. Die jeweils nötigen Schritte wie die Dokumentenerzeugung, Buchungen des Warenausgangs oder -eingangs oder der eventuellen Buchung von Zahlungen laufen jeweils identisch mit den Auftragstypen xref:auftraege:auftraege-verwalten.adoc#500[Gutschrift], xref:auftraege:auftraege-verwalten.adoc#600[Gewährleistung] und xref:auftraege:auftraege-verwalten.adoc#400[Retoure] ab.

[#800]
== Auftragstyp Sammelauftrag nutzen

Unbezahlte Aufträge können in einem Sammelauftrag zusammengefasst werden. Du kannst im Menü *Aufträge » Aufträge bearbeiten* oder im Tab *Aufträge* eines Kontakts mit dem Suchfilter *Auftragsstatus*, z.B. anhand eines Status im Bereich *[3] Warten auf Zahlung*, nach solchen unbezahlten Aufträgen suchen. Somit hast du zwei Möglichkeiten, Sammelaufträge zu erzeugen, die nachfolgend beschrieben werden.
Für beide Möglichkeiten übernimmst du im Menü *Aufträge » Sammelaufträge* noch nicht bezahlte Aufträge in einen Sammelauftrag. Im Tab *Belege* des Sammelauftrags ist dann das Erzeugen von Sammelrechnungen möglich.

[#810]
=== Grundeinstellungen für Sammelaufträge vornehmen

Im Menü *Einrichtung » Aufträge » Auftragstypen » Multi-Order* nimmst du die Grundeinstellungen für Sammelaufträge vor. Hier legst du beispielsweise fest, für welche Auftragstypen und Auftragsstatus Sammelaufträge angelegt werden können.

[.instruction]
Grundeinstellungen für Sammelaufträge vornehmen:

. Öffne das Menü *Einrichtung » Aufträge » Auftragstypen » Multi-Order*.
. Nimm die Einstellungen gemäß <<table-multi-order-settings>> vor.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[[table-multi-order-settings]]
.Grundeinstellungen für Sammelaufträge
[cols="1,3"]
|===
|Einstellung |Erläuterung

| *Auftragstypen*
|Die Auftragstypen wählen, die für Sammelaufträge verwendbar sein sollen. Eine Mehrfachauswahl ist möglich. Nur die aufgeführten Auftragstypen *Auftrag*, *Gewährleistung* und *Reparatur* sind als Sammelaufträge umsetzbar.

| *Artikeltext*
|Die Optionen für die Spalte *Artikeltext* der Artikelpositionen eines Sammelauftrags wählen. Eine Mehrfachauswahl ist möglich. Die gewählten Optionen werden für jeden Einzelauftrag separat im Sammelauftrag aufgelistet und ermöglichen eine Zuordnung zur Kund:in und zum Einzelauftrag.

| *Auftragssortierung*
|Wählen, wie die einzelnen Aufträge im Sammelauftrag sortiert sein sollen. Nur eine Auswahl ist möglich. Die Aufträge sind anhand der der Auftrags-ID (*Order ID aufsteigend* oder *Order ID absteigend*) oder dem Zeitpunkt des Warenausgangs (*Warenausgang aufsteigend* oder *Warenausgang absteigend*) sortierbar.

| *Auftragsstatus Aufträge*
|Wählen, in welchem Status sich Aufträge befinden müssen, um für Sammelaufträge berücksichtigt zu werden. Eine Mehrfachauswahl ist möglich. Um gezielt nur Aufträge zu erfassen, die für Sammelaufträge vorgesehen sind, empfehlen wir, je nach Anwendungsfall einen eigenen Auftragsstatus anzulegen.

| *Auftragsstatus Gutschriften*
|Wählen, in welchem Status sich xref:auftraege:auftraege-verwalten.adoc#500[Gutschriftaufträge] befinden müssen, um für Sammelgutschriften berücksichtigt zu werden. Eine Mehrfachauswahl ist möglich.
|===

Weiterhin legst du im Menü *Einrichtung » Aufträge » Einstellungen* mit der Option xref:auftraege:grundeinstellungen.adoc#intable-default-status-multi-order[Standard-Status Sammelauftrag] fest, welchen Auftragsstatus ein Sammelauftrag beim Anlegen erhalten soll. Standardmäßig steht dafür der Status *[13] Sammelauftrag* zur Verfügung. Wähle zudem mit der Option *Standard-Status Sammelgutschrift* einen Status für Sammelgutschriften aus. Standardmäßig steht dafür der Status *[14] Sammelgutschrift* zur Verfügung.

[#820]
=== Sammelauftrag pro Kundenklasse anlegen

Fallbeispiel: Ein Unternehmen möchte für die Mitarbeiter:innen monatlich die anfallenden Rechnungen in deinem Webshop bezahlen. Richte dafür eine eigene Kundenklasse ein. Mit der Kunden-ID in der vorgesehenen Kundenklasse wird die Rechnungsempfänger:in bestimmt. Diese Rechnungsempfänger:in erhält dann die Sammelrechnung, die direkt aus dem Sammelauftrag heraus erzeugt wird. +

Einen Sammelauftrag für eine bestimmte Kundenklasse sowie einen Zeitraum legst du im Menü *Aufträge » Sammelaufträge* an. Alle unbezahlten Aufträge der Kundenklasse werden somit gesammelt in einem Sammelauftrag abgelegt. Hinterlege in den Einstellungen der Kundenklassen anhand der Option *Kunden-ID*, welche Kund:in für die Kundenklasse als Eigner des Sammelauftrags sowie als Empfänger:in der Sammelrechnung aufgeführt werden soll. Je nach Anforderung empfiehlt es sich, eigene xref:crm:vorbereitende-einstellungen.adoc#kundenklasse-erstellen[Kundenklassen] für Sammelaufträge anzulegen.

[.instruction]
Sammelauftrag für eine Kundenklasse anlegen:

. Öffne das Menü *Aufträge » Sammelaufträge*.
. Öffne das Untermenü *Sammelaufträge generieren*.
. Wähle die *Kundenklasse* und optional einen *Zeitraum*. Der Zeitraum bezieht sich auf das Datum des Auftragseingangs.
. Klicke auf terra:execute[]. +
→ Der Sammelauftrag wird angelegt.

[#830]
=== Sammelauftrag pro Kontakt anlegen

Eine Kund:in möchte nicht jede Rechnung einzeln bezahlen, sondern pro Monat oder pro Quartal bezahlen. +
In diesem Fall legst du einen Sammelauftrag für einen bestimmten Kontakt direkt im Kontaktdatensatz im Menü *CRM » Kontakte* an. Öffne dazu einen Kontakt und wähle links im Menü die Option *Neuer Sammelauftrag*. Anschließend wird automatisch ein Sammelauftrag generiert, der alle unbezahlten Aufträge des Kontakts enthält.

[TIP]
.Aufträge prüfen
====
Um sicher zu gehen, dass geeignete Aufträge für die Erzeugung eines Sammelauftrags vorhanden sind, suche im Tab *Aufträge* der Kund:in nach unbezahlten Aufträgen.
====

[#840]
=== Sammelrechnung generieren

Die Erstellung von Sammelrechnungen ist nur in den dazugehörigen Sammelaufträgen möglich. Richte zuerst eine xref:auftraege:auftragsdokumente.adoc#[Dokumentenvorlage] für Sammelrechnungen im Menü *Einrichtung » Mandant » [Mandant wählen] » Standorte » [Standort wählen] » Dokumente » Sammelrechnung* ein. In diesem Menü kannst du das Dokument detailliert einstellen sowie eine Dokumentenvorlage in Form einer PDF-Datei hinterlegen. In der Grundeinstellung der Vorlage sind bereits Standardwerte hinterlegt, die du bei Bedarf durch Kopie aus einer anderen Vorlage, z.B. der Dokumentenvorlage *Rechnung*, mit geringem Aufwand weiter vervollständigen kannst.

Anschließend kannst du im Tab *Belege* des Sammelauftrags eine Sammelrechnung generieren. Gehe dafür wie im Folgenden beschrieben vor.

[.instruction]
Sammelrechnung erzeugen:

. Öffne das Menü *Aufträge » Aufträge bearbeiten*. +
→ Die Auftragsübersicht öffnet sich.
. Suche (icon:search[role="blue"]) anhand der Filtereinstellungen den Sammelauftrag, für den eine Sammelrechnung erzeugt werden soll.
. Öffne den Sammelauftrag.
. Wechsle in das Tab *Belege*. +
. Wähle aus der Dropdown-Liste *Beleg erstellen* das Dokument *Sammelrechnung* aus. +
. Nimm die Einstellungen anhand <<table-orders-generate-multi-invoice>> vor. +
. *Speichere* (icon:plus-square[role="green"]) die Einstellungen, um die Sammelrechnung zu erzeugen. +
→ Es öffnet sich eine *PDF-Datei* mit der soeben erzeugten Sammelrechnung.

[[table-orders-generate-multi-invoice]]
.Einstellungen für Sammelrechnungen
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Datum*
|Gib das Datum an, das als Rechnungsdatum auf dem Dokument angezeigt wird. Standardmäßig ist das aktuelle Datum voreingestellt.

|*Nummer*
|Die Nummer des Dokuments wird automatisch vergeben. Hier muss keine Angabe gemacht werden.

|*Rechnungen der Aufträge generieren*
|Mit *JA* oder *NEIN* auswählen, ob die einzelnen Rechnungen zu den im Sammelauftrag enthaltenen Aufträgen ebenfalls generiert werden sollen.

| *Buche Warenausgang*
|Mit *JA* oder *NEIN* auswählen, ob mit dem Erzeugen der Sammelrechnung auch der Warenausgang gebucht werden soll.

| *Ändere Auftragsstatus auf Status*
|Einen Status wählen, in den der Auftrag nach dem Erzeugen der Sammelrechnung wechseln sollen. Wenn kein Statuswechsel gewünscht ist, die Option *Keine Änderung* wählen.

| *Kommentar*
|Einen Text eingeben, der auf der Sammelrechnung unterhalb der Artikelpositionen angezeigt wird. Die Eingabe ist optional.
|====

[IMPORTANT]
.Zahlungseingänge bei Sammelaufträgen
====
Wird eine Sammelrechnung bezahlt und der Sammelauftrag als bezahlt markiert, werden die Zahlungseingänge *nicht* automatisch an den einzelnen im Sammelauftrag zusammengefassten Aufträgen gebucht. Zahlungseingänge musst du an den einzelnen Aufträgen manuell buchen.
====

[.discrete]
==== Sammelrechnung über Ereignisaktion generieren

Mithilfe der in plentymarkets verfügbaren Ereignisaktionen kannst du die Sammelrechnung automatisiert generieren, sobald ein Sammelauftrag angelegt wird. Gehe dazu wie nachfolgend beschrieben vor:

:table-event-procedure: <<table-event-procedure-multi-invoice-automatic>>
include::_includes:partial$event-procedure.adoc[]

[[table-event-procedure-multi-invoice-automatic]]
.Ereignisaktion "Sammelrechnung automatisch generieren"
[cols="1,3"]
|====
|Einstellung|Auswahl

| *Ereignis*

| *Auftragsanlage > Neuer Sammelauftrag*

| *Aktion*

| *Dokumente > Sammelrechnung erzeugen* +

|====

[#850]
=== Sammelgutschrift generieren

Eine Sammelgutschrift erzeugst du im Menü *Aufträge » Sammelaufträge*. +
Alle Gutschriften der ausgewählten Kundenklasse werden gesammelt in einer Sammelgutschrift abgelegt. Diese Sammelgutschrift ist wie Sammelaufträge auch nach Erstellung in der Auftragsübersicht bearbeitbar. Je nach Anwendungsfall empfehlen wir, eigene xref:crm:vorbereitende-einstellungen.adoc#kundenklasse-erstellen[Kundenklassen] für Sammelgutschriften anzulegen.

[.instruction]
Sammelgutschrift für eine Kundenklasse generieren:

. Öffne das Menü *Aufträge » Sammelaufträge*.
. Öffne das Untermenü *Sammelgutschriften generieren*.
. Wähle die *Kundenklasse* aus.
. Wähle optional einen *Zeitraum*. Der Zeitraum bezieht sich auf das Datum des Gutschrifteingangs.
. Klicke auf terra:execute[]. +
→ Die Sammelgutschrift wird angelegt.

[#860]
=== Dokument Sammelgutschrift generieren

Die Erstellung des Dokuments Sammelgutschrift ist nur im dazugehörigen Auftragstyp Sammelgutschrift möglich. Richte zuerst eine Dokumentenvorlage für Sammelgutschriften im Menü *Einrichtung » Mandant » [Mandant wählen] » Standorte » [Standort wählen] » Dokumente » Sammelgutschrift* ein. In diesem Menü kannst du das Dokument detailliert einstellen sowie eine Dokumentenvorlage in Form einer PDF-Datei hinterlegen. In der Grundeinstellung der Vorlage sind bereits Standardwerte hinterlegt, die du bei Bedarf durch Kopie aus einer anderen Vorlage, z.B. der Dokumentenvorlage Gutschrift, mit geringem Aufwand weiter vervollständigen kannst.

Anschließend kannst du im Tab *Belege* der Sammelgutschrift das Dokument Sammelgutschrift generieren. Gehe dafür wie im Folgenden beschrieben vor.

[.instruction]
Dokument Sammelgutschrift erzeugen:

. Öffne das Menü *Aufträge » Aufträge bearbeiten*. +
→ Die Auftragsübersicht öffnet sich.
. Suche (icon:search[role="blue"]) anhand der Filtereinstellungen die Sammelgutschrift, für die ein Dokument Sammelgutschrift erzeugt werden soll.
. Öffne die Sammelgutschrift.
. Wechsle in das Tab *Belege*. +
. Wähle aus der Dropdown-Liste *Beleg erstellen* das Dokument *Sammelgutschrift* aus. +
. Nimm die Einstellungen anhand <<table-orders-generate-document.multi-credit-note>> vor. +
. *Speichere* (icon:plus-square[role="green"]) die Einstellungen, um das Dokument Sammelgutschrift zu erzeugen. +
→ Es öffnet sich eine *PDF-Datei* mit der soeben erzeugten Sammelgutschrift.

[[table-orders-generate-document.multi-credit-note]]
.Einstellungen für Dokument Sammelgutschrift
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Datum*
|Gib das Datum an, das als Gutschriftsdatum auf dem Dokument angezeigt wird. Standardmäßig ist das aktuelle Datum voreingestellt.

|*Nummer*
|Die Nummer des Dokuments wird automatisch vergeben. Hier muss keine Angabe gemacht werden.

| *Buche Warenausgang*
|Mit *JA* oder *NEIN* auswählen, ob mit dem Erzeugen der Sammelgutschrift auch ein Warenausgang gebucht werden soll.

| *Ändere Auftragsstatus auf Status*
|Einen Status wählen, in den der Auftrag nach dem Erzeugen der Sammelgutschrift wechseln sollen. Wenn kein Statuswechsel gewünscht ist, die Option *Keine Änderung* wählen.

| *Kommentar*
|Einen Text eingeben, der auf der Sammelgutschrift unterhalb der Artikelpositionen angezeigt wird. Die Eingabe ist optional.
|====

[#1100]
== Auftragstyp Vorbestellung nutzen

Vorbestellungen sind im Online-Handel ein wichtiges Instrument im Marketing-Mix. Meist können Artikel noch vor der tatsächlichen Verfügbarkeit zum günstigen Einführungspreis bestellt werden. Für eine Warenwirtschaft stellt diese Situation einen Sonderfall dar, da noch nicht verfügbare Artikel natürlich auch noch keinen Lagerbestand haben können.

Vorbestellungen sind in plentymarkets sehr einfach zu erstellen. Es gibt dafür den Auftragstyp *Vorbestellung*, den du bei manuell erfassten Aufträgen verwenden kannst.

Um Vorbestellungen entgegennehmen zu können, müssen zwei Voraussetzungen erfüllt sein: das Erscheinungsdatum und die Einstellung der Bestandsbeschränkung.

[IMPORTANT]
.Manuelle Auftragseingabe
====
Der Auftragstyp *Vorbestellung* kann nur bei manueller Auftragseingabe gewählt werden.
====

[#1110]
=== Erscheinungsdatum

Im ersten Schritt gibst du an, wann der Artikel verfügbar sein wird.

[.instruction]
Erscheinungsdatum eintragen:

. Öffne das Menü *Artikel » Artikel bearbeiten » [Variante öffnen] » Tab: Einstellungen » Bereich: Verfügbarkeit*.
//ToDo - sobald die neue Artikel-UI standard ist, dann diesen Satz einblenden und dafür den alten Pfad löschen
//. Öffne das Menü *Artikel » Artikel-UI » [Variante öffnen] » Element: Verfügbarkeit und Sichtbarkeit*.
. Trage bei *Erscheinungsdatum* das Datum ein, ab dem der Artikel verfügbar sein soll.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

---

Im zweiten Schritt sorgst du dafür, dass das Erscheinungsdatum deinen Kunden im plentyShop angezeigt wird.

[.instruction]
Erscheinungsdatum im plentyShop sichtbar machen:

. Öffne das Menü *CMS » ShopBuilder » [Artikelansicht öffnen]*.
. Füge das Widget xref:webshop:shop-builder.adoc#_text[Text » Text] zur Artikeldetailseite hinzu.
. Klicke auf das Stiftsymbol des Text-Widgets.
. Füge das Erscheinungsdatum zum Textfeld hinzu.
Klicke dazu auf *Verfügbarkeit » Erscheinungsdatum*.
. *Speichere* die Einstellungen.

[#1120]
=== Bestandsbeschränkung

Im ersten Schritt wird ermöglicht, dass der Artikel ohne tatsächlichen Bestand gekauft, d.h. vorbestellt werden kann.

[.instruction]
Keine Bestandsbeschränkung einstellen:

. Öffne das Menü *Artikel » Artikel bearbeiten » [Variante öffnen] » Tab: Einstellungen » Bereich: Verfügbarkeit*.
. Finde die Option *Beschränkung* und wähle die Einstellung *Keine*.
//ToDo - sobald die neue Artikel-UI standard ist, dann diese 2 Sätze einblenden und dafür den alten Sätzen löschen
//. Öffne das Menü *Artikel » Artikel-UI » [Variante öffnen] » Element: Verfügbarkeit und Sichtbarkeit*.
//. Finde die Option *Bestandsbeschränkung* und wähle die Einstellung *Keine*.
. *Speichere* die Einstellungen. +
→ Der Artikel kann nun ohne tatsächlichen Bestand gekauft, d.h. vorbestellt werden.

---

Im zweiten Schritt legst du eine maximale Bestellmenge fest.
Damit verhinderst du zum Beispiel, dass die Konkurrenz deinen gesamten Bestand zum günstigen Einführungspreis aufkaufen kann.

[.instruction]
Maximale Bestellmenge einstellen:

. Öffne das Menü *Artikel » Artikel bearbeiten » [Variante öffnen] » Tab: Einstellungen » Bereich: Verfügbarkeit*.
. Trage einen Wert in das Feld *Max. Bestellmenge* ein.
//ToDo - sobald die neue Artikel-UI standard ist, dann diese 2 Sätze einblenden und dafür den alten Sätzen löschen
//. Öffne das Menü *Artikel » Artikel-UI » [Variante öffnen] » Element: Verfügbarkeit und Sichtbarkeit*.
//. Trage einen Wert in das Feld *Maximale Bestellmenge* ein.
* Beispiel: Wenn du den Wert 1 einträgst, dann kann pro Bestellung nur ein Exemplar gekauft werden.
* Wenn du den Wert 0 einträgst oder dieses Feld leer lässt, dann gibt es keine Begrenzung.
. *Speichere* die Einstellungen.

[#1130]
=== Zahlungsaufforderung für Vorbestellungen einrichten

Die Option *Versanddatum* bleibt bei normalen Bestellungen in der Regel ungenutzt, kann jedoch für Vorbestellungen sinnvoll verwendet werden. Liegt das Erscheinungsdatum eines Artikels in der Zukunft, so wird das Erscheinungsdatum bei der Bestellung als Versanddatum hinterlegt, da ja erst mit dem Erscheinen des Artikels geliefert werden kann. Das Versanddatum kannst du in der Auftragssuche als Filteroption verwenden und über den Aktionsmanager nutzen.

Meist werden Vorbestellungen einige Zeit vor dem Erscheinen eines Artikels generiert, von den Kunden zum Zeitpunkt der Bestellung aber noch nicht bezahlt. Daher ist es sinnvoll, Kund:innen einige Tage vor dem Erscheinungs- bzw. Versanddatum über den bevorstehenden Versand zu informieren und sie zur Zahlung aufzufordern. Dies kann der *Aktionsmanager* automatisch für dich erledigen. Kund:innen werden dann wenige Tage vor dem geplanten Versand eine Erinnerungs-E-Mail mit deinen Bankdaten und dem Link zur Kaufabwicklung gesendet. Gehe wie unten beschrieben vor, um die automatische Zahlungsaufforderung für Vorbestellungen einzurichten.

[.instruction]
Zahlungsaufforderung per E-Mail einrichten:

. Erstelle eine geeignete xref:crm:e-mails-versenden.adoc#1200[E-Mail-Vorlage].
. Öffne das Menü *Einrichtung » Aufträge » Aktionen*.
. Wechsle in das Tab *Neue Aktion*.
. Trage dort im Tab *Einstellungen* einen *Namen* ein.
. Wähle bei der Option *Täglich ausführen um* eine Uhrzeit aus der Dropdown-Liste.
. Setze ein Häkchen bei *Aktiv* (icon:check-square[role="blue"]), um die Aktion zu aktivieren.
. Wechsle in das Tab *Filter*.
. Wähle für den *Status* die Einstellung *[3] Warten auf Zahlung*.
. Wähle unter *Versanddatum* z.B. die Einstellung *in 4 Tagen*.
. Wechsle in das Tab *Aktion*.
. Wähle bei der Option *Versende E-Mail-Vorlage* die zuvor erstellte E-Mail-Vorlage. Diese Vorlage wird dann mit dieser Aktion automatisch an den Kunden gesendet.
. Klicke auf *Speichern* (icon:save[role="green"]), um die Aktion zu sichern.

[#1200]
== Auftragsstatus verwenden

Mit Auftragsstatus wird der Fortschritt bei der Abwicklung von Aufträgen abgebildet. 19 Status mit je 4 Nachkommastellen, d.h. eine Anzahl von 199999, stehen dir im System zur Verfügung. 28 Status sind bereits vorangelegt. Diese vorangelegten Status stellen einen Grundstock für übliche Abwicklungsschritte dar. Einige der 28 voreingetragenen Status sind mit Systemautomatismen verknüpft und sollten von dir auch nur für die systemseitig vorgesehenen Zwecke verwendet werden. Der Auftragsstatus eines Auftrags ändert sich durch diese Systemautomatismen, durch von dir eingerichtete Automatismen oder kann auch manuell geändert werden. Auftragsstatus dienen außerdem zur besseren Auftragssuche.

Spiele deine Auftragsabwicklung einmal grob durch und überlege dir, wann du Aufträgen einen neuen Status zuordnen möchtest, um den Fortschritt bei der Abwicklung kenntlich zu machen. Richte anschließend die Status ein, indem du Namen für die Status eingibst. Beachte jedoch die zweckgebundenen Status, die in <<table-default-statuses>> erwähnt sind.

[TIP]
.Berechtigungen beachten
======
Beachte, dass dir in Dropdown-Listen etc. nur die *Webshops* und *Auftragsstatus* angezeigt werden, die für dein Benutzerkonto freigegeben wurden. Wenn du einen Status nicht siehst, fehlt dir wahrscheinlich die Berechtigung für den Status. Berechtigungen können durch Admin-Benutzer:innen vergeben werden.
======

[#preselected-statuses]
=== Voreingestellte Status verstehen

Die folgenden 28 Statuseinträge sind bereits zu Beginn in deinem plentymarkets System vorhanden und sind teilweise mit Systemautomatismen verknüpft. Die mit Systemautomatismen verknüpften Status können nicht gelöscht werden.

[[table-default-statuses]]
.Standardstatus und Systemautomatismen
[cols="1,3"]
|===
|Status |Erläuterung

| *[1]* Unvollständige Daten
|Wird automatisch zugeordnet, wenn Daten eines Auftrages unvollständig sind, z.B. Adressdaten noch fehlen. Unvollständige Daten sind teilweise bei Importen von Märkten der Fall. Aufträge in diesem Status dürfen noch nicht weiter bearbeitet werden. Die Daten werden durch nachfolgende Importe noch vervollständigt. Die unvollständigen Daten dienen z.B. der frühzeitigen Bestandsreservierung.

| *[1.1]* Warten auf Zahlung &amp; Freischaltung
.3+^|Werden nicht automatisch vergeben. Ein Anwendungsfall ist der vorbefüllte Warenkorb. Ein Auftrag wird angelegt und ein Link zum Warenkorb des Auftrags wird zur Bestätigung an Kund:innen geschickt.

| *[1.2]* Freigeschaltet, warten auf Zahlung

| *[2]* Warten auf Freischaltung

| *[3]* Warten auf Zahlung
|Wird jedem unbezahlten Auftrag vom Typ *Auftrag* automatisch zugeordnet.

| *[3.2]* In Warteposition
a|Wird automatisch in folgenden Fällen gesetzt: +

* Wenn für einen Auftrag eine Teilzahlung gebucht wird, aber kein Warenbestand vorhanden ist. +
* Wenn für einen Auftrag eine Anzahlung gebucht wird, aber kein Warenbestand vorhanden ist. +
* Wenn für einen Auftrag eine Überbezahlung gebucht wird, unabhängig davon, ob Warenbestand vorhanden ist oder nicht.

| *[3.3]* Versandfertig; warten auf Zahlung
|Wird automatisch einem Auftrag des Typs *Auftrag* zugeordnet, wenn für den Auftrag eine Teil- oder Anzahlung gebucht wird und Warenbestand für den Auftrag vorhanden ist.

| *[3.4]* Mahnung versendet
|Empfohlen, um zu erkennen, dass eine Mahnung versendet wurde. Mithilfe von Ereignisaktionen oder Prozessen kann hier auch eine Automatisierung eingerichtet werden. Der Status wird jedoch nicht durch einen Systemautomatismus gesetzt.

| *[4]* In Versandvorbereitung
|Steht in Verbindung mit Bestandsbeschränkung. Wenn du keinen Bestand führst und keine Beschränkung nutzt, dann steht der Status zur freien Verfügung. +
Wenn die Bestandsbeschränkung genutzt wird, wird der Status automatisch zugeordnet, wenn ein Auftrag vom Typ *Auftrag* bezahlt ist, aber der Bestand der Artikel für den Auftrag nicht ausreicht. Die Beschränkung von Artikeln muss auf Nettowarenbestand eingestellt sein. +
Wenn du die Bestandsbeschränkung und diesen Status bei fehlendem Bestand nutzt, kannst du z.B. erreichen, dass nur Lieferscheine und Rechnungen für Aufträge erzeugt werden, die auch weiter abgewickelt werden können.

| *[5]* Freigabe Versand
|Wird automatisch zugeordnet, wenn ein Auftrag vom Typ *Auftrag* bezahlt oder die Zahlungsart z.B. Rechnung oder Vorkasse ist und der Bestand der Artikel für den Auftrag ausreicht oder der Bestand unbeschränkt ist.

| *[5.1]* Abwicklung extern
|Empfohlen, um zu kennzeichnen, dass die Ware durch einen Fulfillment-Anbieter zusammengestellt und verschickt wird. Der Status wird jedoch nicht durch einen Systemautomatismus gesetzt.

| *[6]* Gerade im Versand
|Empfohlen, um zu kennzeichnen, dass Aufträge zum Picken und Packen an das Lager übertragen wurden. Mithilfe von Ereignisaktionen oder Prozessen lässt sich hier eine Automatisierung erreichen.

| *[7]* Warenausgang gebucht
|Wird automatisch zugeordnet, wenn der Warenausgang in einem Auftrag gebucht wurde. Das manuelle Setzen des Status sorgt wiederum nicht dafür, dass der Warenausgang tatsächlich gebucht und der Bestand reduziert wird. Deshalb sollte dieser Status nicht manuell, sondern per Ereignisaktion oder Prozess gesetzt werden.

| *[7.1]* Auftrag exportiert
|Steht zur freien Verfügung. Möglicher Anwendungsfall ist das Setzen des Status, nachdem Aufträge zur Auswertung exportiert wurden.

| *[8]* Storniert
|Empfohlen, um zu kennzeichnen, dass ein Auftrag vom Typ *Auftrag* storniert wurde. Status 8 ist als Standard für stornierte Aufträge festgelegt. Du kannst die Standardfestlegung für stornierte Aufträge jedoch im Menü *Einrichtung » Aufträge » Einstellungen* ändern. Die Einstellung hierfür heißt xref:auftraege:preparatory-settings.adoc#intable-default-status-cancelled-orders[Status stornierter Aufträge]. Wenn du einen anderen Status für Stornierungen festgelegt hast, kannst du Status 8 frei nutzen.

| *[8.1]* Storniert durch Kunden
|Empfohlen, um zu kennzeichnen, dass ein Auftrag durch die Kund:in storniert wurde.

| *[9]* Retoure
|Ist beim Anlegen eines Auftrags vom Typ *Retoure* automatisch vorausgewählt. Du kannst auch einen anderen xref:auftraege:preparatory-settings.adoc#intable-default-status-return[Status als Standard für Retouren] festlegen. Die Einstellung erfolgt im Menü *Einrichtung » Aufträge » Einstellungen*.

| *[9.1]* Ware wird geprüft
|Empfohlen, um in einer Retoure anzuzeigen, dass die retournierte Ware geprüft wird.

| *[9.2]* Warten auf Retoure von Großhändler
|Steht zur freien Verfügung.

| *[9.3]* Gewährleistung eingeleitet
|Empfohlen, um zu kennzeichnen, dass eine Gewährleistung zur Retoure eingeleitet wurde.

| *[9.4]* Umtausch eingeleitet
|Empfohlen, um in einer Retoure anzuzeigen, dass ein Umtausch der retournierten Ware eingeleitet wurde.

| *[9.5]* Gutschrift angelegt
|Empfohlen, um in einer Retoure anzuzeigen, dass eine Gutschrift zur Retoure angelegt wurde.

| *[10]* Gewährleistung
|Steht zur freien Verfügung. Kann genutzt werden, um eine Gewährleistung als abgeschlossen zu kennzeichnen. Beim Anlegen einer Gewährleistung erhält der Gewährleistungsauftrag je nach Bestandsführung Status 4 oder 5.

| *[11]* Gutschrift
|Wird einem Auftrag vom Typ *Gutschrift* automatisch zugeordnet, wenn eine Gutschrift angelegt wird. Du kannst auch einen anderen xref:auftraege:preparatory-settings.adoc#intable-default-status-credit-note[Status als Standard für Gutschriften] festlegen. Die Einstellung erfolgt im Menü *Einrichtung » Aufträge » Einstellungen*.

| *[11.1]* Gutschrift ausgezahlt
|Empfohlen, um zu kennzeichnen, dass die Gutschrift ausgezahlt wurde und abgeschlossen ist.

| *[12]* Reparatur
|Ist beim Anlegen eines Auftrags vom Typ *Reparatur* automatisch vorausgewählt. Du kannst auch einen anderen xref:auftraege:grundeinstellungen.adoc#intable-default-status-repairs[Status als Standard für Reparaturen] festlegen. Die Einstellung erfolgt im Menü *Einrichtung » Aufträge » Einstellungen*.

| *[13]* Sammelauftrag
|Wird einem Auftrag vom Typ *Sammelauftrag* automatisch zugeordnet, wenn der Sammelauftrag angelegt wird. Du kannst auch einen anderen xref:auftraege:grundeinstellungen.adoc#intable-default-status-multi-order[Status als Standard für Sammelaufträge] festlegen. Die Einstellung erfolgt im Menü *Einrichtung » Aufträge » Einstellungen*.

| *[14]* Sammelgutschrift
|Wird einem Auftrag vom Typ *Sammelgutschrift* automatisch zugeordnet, wenn die Sammelgutschrift angelegt wird. Du kannst auch einen anderen xref:auftraege:grundeinstellungen.adoc#intable-default-status-multi-credit-note[Status als Standard für Sammelgutschriften] festlegen. Die Einstellung erfolgt im Menü *Einrichtung » Aufträge » Einstellungen*.

|===

[TIP]
.Status-ID in Statusname anzeigen
======
Mit der Umschaltfläche *Status-ID im Statusnamen anzeigen* in den Einstellungen legst du fest, ob nur der vergebene Name des Status oder zusätzlich auch die Status-ID angezeigt werden soll.
======

[#search-for-order-statuses]
=== Nach Auftragsstatus suchen

Verwende eine der folgenden Möglichkeiten, um nach Auftragsstatus zu suchen.

[.instruction]
Nach Auftragsstatus suchen:

. Öffne das Menü *Einrichtung » Aufträge » Auftragsstatus*.
.. *_Möglichkeit 1:_* Klicke auf material:search[], um direkt eine Liste aller Status zu sehen.
.. *_Möglichkeit 2:_* Gib etwas in das Suchfeld ein und klicke auf einen der automatischen Vorschläge.
.. *_Möglichkeit 3:_* Klicke auf material:tune[], um die Suchergebnisse mit Hilfe von Filtern einzugrenzen.

[#use-filters]
==== Filter verwenden

Um noch gezielter nach bestimmten Auftragsstatus zu suchen, stehen dir die folgenden Filter zur Verfügung.

[[table-filters-order-status]]
.Filter für Auftragsstatus
[cols="1,3"]
|===
|Einstellung |Erläuterung

| *Status von*
|Filtert nach Status ab dieser Statusnummer.

| *Status bis*
|Filtert nach Status bis zu dieser Statusnummer.

| *Sprache*
|Filtert nach Status mit dieser Sprache.

|===

[#configure-columns]
=== Spalten in der Übersicht konfigurieren

In der Übersicht kannst du selbst entscheiden, welche Spalten in der Tabelle sichtbar sein sollen und in welcher Reihenfolge diese angezeigt werden. Um die Spalten zu konfigurieren, gehe vor wie folgt.

[.instruction]
Spalten konfigurieren:

. Öffne das Menü *Einrichtung » Aufträge » Auftragsstatus*.
. Klicke oben rechts auf *Spalten konfigurieren* (material:settings[]). +
→ Das Fenster *Spalten konfigurieren* wird geöffnet.
. Wähle die Spalten, die angezeigt werden sollen (material:done[]). Beachte dazu die Erläuterungen in <<table-order-status-columns>>.
. Ziehe (material:drag_indicator[]) die Spalten per Drag-and-drop an die gewünschte Stelle, bis sie in der für dich richtigen Reihenfolge angezeigt werden.
. Füge bei Bedarf Spalten hinzu oder wähle Spalten ab, wenn du sie nicht benötigst.
. Klicke auf *Bestätigen*. +
→ Die Einstellungen werden gespeichert.

[[table-order-status-columns]]
.Spalten in der Statusübersicht
[cols="1,3"]
|===
|Spalte |Erläuterung

| *Checkbox*
|Zeigt am Anfang der Zeile eine Checkbox an. Hake die Box an, um eine der verfügbaren <<#order-status-group-functions, Gruppenfunktionen>> für diesen Status zu verwenden.

| *Status*
|Zeigt den Status des Auftrags an.

| *Farbe*
|Zeigt die Farbe des Auftragsstatus an.

| *Name*
|Zeigt den Namen des Auftragsstatus an. Wenn du die Umschaltfläche *Status-ID im Statusnamen anzeigen* aktiviert hast (material:toggle_on[]), wird die ID ebenfalls angezeigt.

| *Name (Sprache)*
|Zeigt den Statusnamen für die in Klammern angegebene Sprache an. Wähle hier die Sprachen, die du benötigst.

| *Löschen*
|Zeigt am Ende der Zeile die Funktion zum Löschen des Status an (material:delete[]). +
*_Beachte:_* Status, die aus dem System stammen, können nicht gelöscht werden.

|===

[#order-status-group-functions]
=== Gruppenfunktionen verwenden

Es gibt verschiedene Gruppenfunktionen, mit denen du Aktionen für mehrere Status gleichzeitig durchführen kannst. Sie bieten dir die Möglichkeit, die <<#change-visibility, Sichtbarkeit zu ändern>>, die <<#change-colour, Farbe zu ändern>> oder bestimmte <<#delete-status, Status zu löschen>>.

[#change-visibility]
==== Sichtbarkeit ändern

Die Sichtbarkeit von Auftragsstatus kann für verschiedene Bereiche eingestellt werden. Um die Sichtbarkeit für einen oder mehrere Status zu ändern, gehe wie im Folgenden beschrieben vor.

[.instruction]
Sichtbarkeit ändern:

. Öffne das Menü *Einrichtung » Aufträge » Auftragsstatus*.
. Führe die Suche (material:search[]) aus, um Auftragsstatus anzuzeigen.
. Setze für einen oder mehrere Status ein Häkchen (material:check_box[]).
. Klicke oben auf die Funktion *Sichtbarkeit ändern* (material:remove_red_eye[]). +
→ Das Fenster *Sichtbarkeit ändern* wird geöffnet.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<table-change-visibility>>.
. Klicke auf *Sichtbarkeit ändern* (material:remove_red_eye[role=skyBlue]). +
→ Die Sichtbarkeit wird geändert.

[[table-change-visibility]]
.Sichtbarkeit für Auftragsstatus
[cols="1,3"]
|===
|Einstellung |Erläuterung

| *Sichtbarkeit im Webshop*
|Wähle aus der Dropdown-Liste, ob der Auftragsstatus im Webshop sichtbar sein soll.

| *Sichtbarkeit in Nachbestellungen*
|Wähle aus der Dropdown-Liste, ob der Auftragsstatus in Nachbestellungen sichtbar sein soll.

| *Sichtbarkeit in Umbuchungen*
|Wähle aus der Dropdown-Liste, ob der Auftragsstatus in Umbuchungen sichtbar sein soll.

|===

[#change-colour]
==== Farbe ändern

Die Farbe für einen Auftragsstatus kannst du jederzeit anpassen. Um die Farbe für einen oder mehrere Auftragsstatus zu ändern, gehe wie im Folgenden beschrieben vor.

[.instruction]
Farbe ändern:

. Öffne das Menü *Einrichtung » Aufträge » Auftragsstatus*.
. Führe die Suche (material:search[]) aus, um Auftragsstatus anzuzeigen.
. Setze für einen oder mehrere Status ein Häkchen (material:check_box[]).
. Klicke oben auf die Funktion *Farbe ändern* (material:color_lens[]). +
→ Das Fenster *Farbe ändern* wird geöffnet.
. Wähle eine neue Farbe. Gib dazu entweder einen HEX-Code ein oder wähle Werte für RGB (Red, Green, Blue) bzw. HSL (Schattierung, Sättigung und Helligkeit).
. Klicke auf *Farbe ändern* (material:color_lens[role=skyBlue]). +
→ Die Farbe wird geändert.

[#delete-status]
==== Auftragsstatus löschen

Auftragsstatus können auch gelöscht werden. Beachte allerdings, dass dies für Staus, die aus dem System stammen, nicht möglich ist. Um Auftragsstatus zu löschen, gehe wie im Folgenden beschrieben vor.

[.instruction]
Status löschen:

. Öffne das Menü *Einrichtung » Aufträge » Auftragsstatus*.
. Führe die Suche (material:search[]) aus, um Auftragsstatus anzuzeigen.
. Setze für einen oder mehrere Status ein Häkchen (material:check_box[]).
. Klicke oben auf die Funktion *Status löschen* (material:delete[]). +
icon:map-signs[] *_Oder:_* Klicke rechts in der Zeile eines Status auf *Löschen* (material:delete[]), um nur diesen Status zu löschen. +
→ Das Fenster *Status löschen* wird geöffnet.
. Wenn du dir sicher bist, dass du alle gewählten Status löschen möchtest, bestätige die Sicherheitsabfrage und klicke auf *Status löschen* (material:delete[role=red]). +
→ Die Status werden gelöscht.

=== Neuen Status erstellen

Im Menü *Einrichtung » Aufträge » Auftragsstatus* kannst du neben den in <<table-default-statuses>> aufgeführten Status auch eigene Status hinzufügen. Die bereits vorhandenen Status kannst du bearbeiten. Pflege Status in verschiedenen Sprachen, um deine Kund:innen per E-Mail oder im Kund:innenkonto des Webshops über den Fortschritt zu informieren. Status, die mit Systemautomatismen verbunden sind, kannst du umbenennen. Du solltest die mit Systemautomatismen verbundenen Status jedoch nicht zweckentfremden. Um einen neuen Status zu erstellen, gehe vor wie im Folgenden beschrieben.

[.instruction]
Neuen Status erstellen:

. Öffne das Menü *Einrichtung » Aufträge » Auftragsstatus*.
. Klicke auf *Neuen Status erstellen* (material:add[]). +
→ Das Fenster *Neuen Status erstellen* wird geöffnet.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<table-create-new-status>>.
. Klicke auf *Erstellen* (material:add[role=green]). +
→ Der neue Status wird erstellt.

[[table-create-new-status]]
.Neuen Status erstellen
[cols="1,3"]
|===
|Einstellung |Erläuterung

| *Neuer Status*
|Gib eine Statusnummer (z.B. 2.5) ein. Stelle sicher, dass dieser Status einmalig ist. Wenn der eingegebene Status bereits existiert, wird eine Fehlermeldung angezeigt. +
Dies ist ein Pflichtfeld.

| *Name in Systemsprache (Sprache)*
|Gib einen Namen für den neuen Status ein. Die Sprache, in der du eingeloggt bist, wird im Eingabefeld angezeigt. +
Dies ist ein Pflichtfeld.

| *Farbe*
|Wähle eine Farbe für den neuen Status. Gib dazu entweder einen HEX-Code ein oder wähle Werte für RGB (Red, Green, Blue) bzw. HSL (Schattierung, Sättigung und Helligkeit).

| *Sichtbarkeit*
|Wähle, ob der neue Status im Webshop, in Nachbesellungen oder in Umbuchungen sichtbar sein soll.

|===

[TIP]
.Nachkommastellen beachten
======
Achte bei der Vergabe der Statusnummern darauf, dass diese nicht auf 0 enden. Besteht die letzte Nachkommastelle aus einer 0, wird diese automatisch vom System gekürzt. In plentymarkets wird somit nicht zwischen einem Status mit der Nummer 1.1 und einem Status mit der Nummer 1.10 unterschieden.
======

[#edit-status]
=== Status bearbeiten

Status können jederzeit bearbeitet werden. Über die Gruppenfunktion kannst du auch mehrere Status auf einmal öffnen und diese nacheinander bearbeiten. Um Status zu bearbeiten, gehe wie im Folgenden beschrieben vor.

[.instruction]
Status bearbeiten:

. Öffne das Menü *Einrichtung » Aufträge » Auftragsstatus*.
. Führe die Suche (material:search[]) aus, um Aufträge anzuzeigen.
. Setze für alle Status ein Häkchen (material:check_box[]), die du bearbeiten möchtest.
. Klicke in die Zeile eines gewählten Status. +
*_Tipp:_* Wenn du mehrere Status auf einmal wählst, werden diese gesammelt geöffnet und du kannst sie nacheinander bearbeiten. +
→ Die Detailansicht des Status wird geöffnet. Hast du mehrere Status gewählt, werden diese links untereinander angezeigt und du kannst zwischen den Ansichten der Status wechseln.
. Nimm die gewünschten Änderungen für die *Namen*, die *Farbe* oder die *Sichtbarkeit* vor.
. *Speichere* (material:save[]) die Einstellungen. +
→ Die Änderungen werden übernommen.

[#1300]
== Aufträge suchen

Mit der Auftragssuche kannst du sowohl alle Aufträge auflisten als auch bestimmte Aufträge gezielt finden. Beim Öffnen des Menüs wird standardmäßig keine Suche ausgeführt, jedoch ist der Filter Datum standardmäßig auf *Auftragseingang* in den letzten 2 Monaten eingestellt. Alle anderen Filteroptionen stehen zunächst auf *ALLE*. Ändere die Filtereinstellungen, um die Suche einzuschränken und führe dann eine Suche aus.

[.instruction]
Aufträge suchen:

. Öffne das Menü *Aufträge » Aufträge bearbeiten*
. Nimm Filtereinstellungen vor.
. Prüfe, ob die Standardeinstellung für die Option *Datum* und den Zeitraum unter *von bis* deinen Kriterien entspricht.
. Klicke auf *Suchen* (icon:search[role="blue"]), um die Aufträge anzuzeigen.

Wenn du z.B. nach Aufträgen suchst, die in einem Status kleiner als (<) Status 7 sind, bei denen der Warenausgang nicht gebucht ist und du kein Datum berücksichtigst, erhältst du alle Aufträge, die noch nicht abgeschlossen sind.

Klicke auf *Zurücksetzen* (icon:undo[role="orange"]), um deine Filtereinstellungen auf die Standardwerte zurückzusetzen. Klicke dann erneut auf *Suchen* (icon:search[role="blue"]), um auch das Suchergebnis zurückzusetzen.

[TIP]
.Suchergebnisse nach Statuswechsel
====
Wenn Aufträge den Status gewechselt haben kann es vorkommen, dass sie nicht sofort als Suchergebnisse auftauchen. Wurden Aufträge z.B von Status 6.9 in Status 7 verschoben und du suchst direkt im Anschluss alle Aufträge in Status 7, werden die geänderten Aufträge eventuell noch nicht sofort gelistet. Durch den Abgleich im Hintergrund entsteht eine kurze Zeitverzögerung, führe die Suche daher nach einiger Zeit erneut durch, um alle Aufträge korrekt angezeigt zu bekommen.
====

[#1310]
=== Nach IDs und Nummern filtern

Um nach IDs oder Nummern zu filtern, gib eine ID oder Nummer ein. Durch Eingabe einer *Kunden-ID* erhältst du z.B. nur die Aufträge der Kund:in mit dieser ID.

Wenn du eine 3 in das Feld *Auftrags-ID* eingibst und suchst, wird auch nur der Auftrag mit der ID 3 in der Übersicht angezeigt. Es handelt sich also um eine genaue Suche und keine unscharfe Suche. Jedoch kannst du bei den Auftrags-IDs mehrere IDs kommagetrennt eintragen und auf diese Weise auch nach mehreren Aufträgen suchen.

[TIP]
.Status-Suchfilter prüfen
====
Wenn du nach Nummern oder IDs suchst, ist es sinnvoll den Status nicht einzuschränken und *Alle* einzustellen. Es werden nur Aufträge angezeigt, die alle eingestellten Kriterien erfüllen. Wenn du einen Auftrag trotz eindeutiger ID nicht findest, hast du vielleicht den Suchfilter *Status* nicht auf den Wert *ALLE* umgestellt.
====

[#1320]
=== Nach Kunden- bzw. Artikeldaten und Rechnungsnummern filtern

Für gezielte Suchen anhand von artikelbezogenen Angaben oder Daten von Kund:innen nutzt du am besten die Suchfelder *Kundendaten* und *Artikeldaten*. Hier ist die Eingabe von Suchbegriffen und Zahlen gleichermaßen zulässig. Bei den *Kundendaten* sind neben Namen auch Postleitzahlangaben möglich, jedoch keine Telefonnummern. Bei den *Artikeldaten* werden Artikel-ID, Artikel-Nummer und Name abgefragt, jedoch nicht die Felder mit den Beschreibungstexten (short_description, description). Bei der Suche nach *Rechnungsnummern* ist auch die Suche nach externen Rechnungsnummern möglich.

[TIP]
.Suchbegriffe und Zahlen nur am Ende kürzen
====
Bei der Suche nach Kunden bzw. Artikeldaten reicht es häufig aus, nur den Wortstamm einzugeben. Achte aber darauf, dass du Suchwörter hinten fast beliebig kürzen kannst, am Wortanfang allerdings nicht. Suche z.B. nach Artikeln mit dem Stichwort Startersets, kannst du Starterset oder Starter oder Start eingeben. Eine Suche nach arterset hingegen führt zu keinem Ergebnis. Gleichermaßen verhält es sich mit Zahlenwerten wie z. B. Kundennummern oder PLZ.
====

[#1330]
=== Nach Auftragstypen filtern

Nutze den Filter *Typ*, um nach folgenden *Auftragstypen* zu suchen:

* Auftrag
* Gutschrift
* Sammelgutschrift
* Retoure
* Gewährleistung
* Angebot
* Vorbestellung
* Lieferauftrag
* Reparatur
* Sammelauftrag
* Aufträge, Gewährleistungen, Lieferaufträge und Reparaturen
* Aufträge und Lieferaufträge

Nur die gewählten Auftragstypen bzw. die Kombinationen werden gesucht. In der Standardeinstellung steht der Filter auf *ALLE*, d.h. alle Auftragstypen werden gesucht.

[#1340]
=== Nach Datum filtern

Nutze den Filter *Datum*, um Aufträge zu suchen, die in einem von dir ausgewählten Zeitraum einen bestimmten Schritt in der Auftragsabwicklung bereits durchlaufen haben. Zur Wahl dafür stehen dir unter *Datum*: *Auftragseingang*, *Zahlungseingang* oder *Warenausgang*. Wähle dann unter *von* das Startdatum und unter *bis* das Enddatum des Zeitraums. +
Alle Aufträge, die innerhalb des gewählten Zeitraums den gewählten Schritt durchlaufen haben, werden angezeigt. Für die Suche ist standardmäßig *Auftragseingang* und ein Zeitraum von 2 Monaten rückwirkend zum aktuellen Datum eingestellt.
Wenn du Aufträge nicht mit der Standardeinstellung von 2 Monaten rückwirkend suchen möchtest, stelle den gewünschten Zeitraum wie oben erläutert ein.

[#1350]
=== Nach Markierungen filtern

Du kannst Aufträgen unabhängig vom Auftragsstatus Markierungen zuweisen. Auch nach diesen Markierungen kannst du Aufträge filtern. So kannst du z.B. festlegen, dass problematische Aufträge mit einem bestimmten Symbol gekennzeichnet werden und vor der Auslieferung von einem Verantwortlichen freigegeben werden müssen. Dieser kann die Aufträge einmal täglich über den Filter *Markierung* suchen, eine Information hinterlegen und die Markierung dann wieder zurücksetzen.

[#1360]
=== Nach Dokumenten filtern

Nutze den Filter *Dokument*, um Aufträge zu suchen, für die bereits ein xref:auftraege:auftragsdokumente.adoc#[Auftragsdokument] eines bestimmten Typs angelegt wurde. Du kannst entweder nach einem bestimmten *Dokumententyp* oder nur nach einer *Dokumentennummer* suchen. Du kannst diese beiden Suchkriterien aber auch kombinieren und nach einem Auftrag suchen, für den ein bestimmter Dokumententyp mit einer konkreten Auftragsnummer erstellt wurde. +
Bei der Suche nach *Dokumententyp* werden dir als Ergebnis alle Aufträge angezeigt, für die dieses Dokument bereits erstellt wurde. Es handelt sich also eher um eine Überblickssuche. Durch die Suche nach konkreten *Dokumentennummern* kannst du spezifischer nach bestimmten Dokumenten bzw. den Aufträgen, für die diese erstellt wurden, suchen.

Um alle Aufträge anzuzeigen, für die ein Dokument eines Typs angelegt wurde, gehe wie im Folgenden beschrieben vor.

[.instruction]
Alle Aufträge mit bestimmtem Dokumententyp anzeigen:

. Öffne das Menü *Aufträge » Aufträge bearbeiten*.
. Wähle im Tab *Filter* einen Dokumententyp aus der Dropdown-Liste *Dokument*, z.B. Rechnung.
. Beachte den Filter *Datum*, da standardmäßig nur Aufträge der letzten 2 Monate angezeigt werden. Passe den Filter gegebenenfalls an.
. Klicke auf *Suchen* (icon:search[role="blue"]). +
→ Alle Aufträge, für die bereits eine Rechnung generiert wurde, werden im Suchergebnis angezeigt.

Um einen Auftrag zu suchen, der ein Dokument mit einer bestimmten Nummer enthält, gehe wie im Folgenden beschrieben vor.

[.instruction]
Einen Auftrag mit bestimmtem Dokument anzeigen:

. Öffne das Menü *Aufträge » Aufträge bearbeiten*.
. Wähle im Tab *Filter* einen Dokumententyp aus der Dropdown-Liste *Dokument*, z.B. Lieferschein.
. Trage im Feld *Nummer* rechts daneben die Nummer des gesuchten Lieferscheins ein.
. Beachte den Filter *Datum*, da standardmäßig nur Aufträge der letzten 2 Monate angezeigt werden. Passe den Filter gegebenenfalls an.
. Klicke auf *Suchen* (icon:search[role="blue"]). +
→ Nur der Auftrag, zu dem der Lieferschein mit der eingegeben Nummer gehört, wird im Suchergebnis angezeigt.

[TIP]
.Auswahl eines Dokumententyps bei Suche mit Nummer nicht zwingend erforderlich
====
Die Suche nach einer Dokumentennummer funktioniert auch, wenn du die Standardeinstellung *Dokument* stehen lässt, also keinen Typen wählst. Wenn jedoch die Nummern verschiedener Dokumententypen identisch sind, werden dir alle Aufträge, die ein Dokument mit dieser Nummer haben, angezeigt. Dies kann zum Beispiel der Fall sein, wenn du alle Dokumente ohne xref:auftraege:auftragsdokumente.adoc#1800[Nummernkreis] durchnummerierst.
====

[#1370]
=== Nach Gutscheincodes filtern

Nach Aufträgen mit xref:auftraege:gutscheine.adoc#[Gutscheinen] suchst du, indem du den Gutscheincodes in das Suchfeld *Gutschein-Code* einträgst. Zusätzlich stehen die Optionen *Alle*, *Eingelöst* und *Verkauft* zur Verfügung. *Alle* ist standardmäßig voreingestellt. Mit *Eingelöst* suchst du nur Aufträge, in denen der Gutscheincode eingelöst wurde. Mit *Verkauft* suchst du nur Aufträge, in denen ein Gutschein mit dem eingetragenen Gutscheincode verkauft wurde. *Alle* sucht sowohl Aufträge, in denen der Code eingelöst als auch verkauft wurde. Der Suchfilter, auch mit der Option *Alle*, greift nur, wenn ein Gutscheincode eingetragen ist. Du kannst den Suchfilter also nicht nutzen, um alle Aufträge mit Gutscheinen zu suchen.

[#1400]
== Auftragsübersicht einrichten

Damit du die Suchergebnisse gut überblicken und bearbeiten kannst, passe die Auftragsübersicht an. Zu dieser kommst du über das Menü *Aufträge » Aufträge bearbeiten*. Hier werden dir alle Aufträge mit den wichtigsten Informationen zu jedem Auftrag angezeigt. Neben Informationen zu Kund:innen, dem Auftragsstatus, dem Zahlungsstatus sowie den Artikeln des Auftrags erkennst du z.B. auf einen Blick, ob der Warenausgang gebucht und ob eine Rechnung erzeugt wurde. So hast du die wichtigsten Vorgänge im Blick, ohne den Auftrag zu öffnen. Bewege den Mauszeiger über die Symbole und Angaben, um Tooltips mit weiteren Informationen anzuzeigen. Eine Auflistung der Symbole mit Beschreibung findest du in <<table-symbols-order-overview>>.

Durch Klick auf ein *Icon* öffnen sich außerdem bestimmte Bereiche des Auftrags. Klicke z.B. auf *Warenbestand*, um den aktuellen Warenbestand der Artikel abzufragen und ggf. Nachbestellungen auszulösen.
Zudem kannst du einstellen, wie viele Aufträge pro Seite in der Auftragsübersicht angezeigt werden. Die höchste Anzahl an Aufträgen pro Seite ist 400, die niedrigste 50. +
Nutze die Pfeile, um zur nächsten Seite oder zurück zu wechseln. Du kannst die gewünschte Seitenziffer auch direkt eintragen und die Eingabetaste betätigen.

In der Auftragsübersicht passt du außerdem bei Bedarf den *Status*, das *Porto*, die *Artikeldaten* oder den *Rabatt* an. Unten wird beispielhaft das Vorgehen bei einer Statusänderung beschrieben.

[.instruction]
Auftragsstatus in der Auftragsübersicht anpassen:

. Klicke auf *Status*. +
→ Eine Liste mit den verfügbaren Status wird angezeigt.
. Wähle den gewünschten Status. +
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Der Status wird aktualisiert.

[#1410]
=== Auftragspositionen ein- oder ausblenden

In der Auftragsübersicht werden standardmäßig die Auftragspositionen mit angezeigt. So stehen dir auf einen Blick die im Auftrag enthaltenen Artikel mit wichtigen Parametern, z.B. *Titel*, *Größe*, *Preis* zur Verfügung. Du kannst die Auftragspositionen jedoch auch ausblenden. Du kannst die Positionen entweder nur bei einzelnen Aufträgen oder bei allen ausblenden. Um die Positionen eines einzelnen Auftrages auszublenden, nutze das Pfeilsymbol *Artikelliste schließen*. Um die Positionen für alle Aufträge auszublenden, folge den aufgeführten Schritten.

[.instruction]
Auftragspositionen für alle Aufträge ausblenden:

. Öffne das Menü *Aufträge » Aufträge bearbeiten*.
. Wähle im Tab *Filter* für den Filter *Artikelposition* die Einstellung *Nicht anzeigen*.
. Klicke auf *Suchen* (icon:search[role="blue"]). +
→ Die Artikellisten der angezeigten Aufträge werden geschlossen.

[#1420]
=== Informationen und Symbole in der Auftragsübersicht verstehen

In der Auftragsübersicht werden je nach Zustand eines Auftrags verschiedene Symbole angezeigt.
Die folgende Tabelle enthält eine Übersicht der möglichen Informationen. Einige Symbole erlauben dir auch direkt Aktionen auszuführen. Beachte, dass nie alle Symbole angezeigt werden, sondern nur die zum Bearbeitungsstand passenden.

[[table-symbols-order-overview]]
.Mögliche Symbole in der Auftragsübersicht
[cols="1,3a"]
|====
|Tooltip des Symbols |Erläuterung

| *Auftragsstatus*
|Zeigt den aktuellen Auftragsstatus und erlaubt auch den Status zu ändern. Zum ändern, einfach auf den Status klicken und einen neuen wählen. +
*Wichtig*: Ein Auftragsstatus &gt;= 7 kann nicht verringert werden, ohne dass vorher die Buchung des Warenausgangs zurückgesetzt wird.

| *Versanddienstleister*
|Individuelles Symbol des zugeordneten Dienstleisters. Ein Symbol wird jedoch nur angezeigt, wenn im xref:fulfillment:versand-vorbereiten.adoc#1000[Versandprofil] eine Markierung eingestellt wurde.

| *DHL-Packstation*
|Das Symbol wird nur angezeigt, wenn die Packstationsdaten korrekt im Auftrag hinterlegt sind. Es kann bei Aufträgen von Marktplätzen vorkommen, dass Packstationsdaten nicht korrekt sind, wenn der Marktplatz z.B. keine Validierung bereitstellt. In einem solchen Fall wird das Symbol nicht angezeigt, da aufgrund der falschen Daten nicht an eine Packstation geliefert werden kann.

| *Versandart* oder +
 *Versanddienstleisterservice*
| *Schnellversand* ist ein Service, der zusätzlich durch ein Symbol angezeigt wird.

| *Zahlungsart*
|Individuelles Symbol der Zahlungsart.

| *Warenausgang gebucht*
|Wird nur angezeigt, wenn der Warenausgang gebucht wurde. Falls nur der Status in Status 7 geändert wurde, wird das Symbol nicht angezeigt.

| *Mahnstufe*
| xref:automatisierung:aktionsmanager.adoc#intable-dunning-level-procedure-manager[Mahnstufen] können per Aktionsmanager zugeordnet werden.

| *Markierung*
|Individuelle Auftragsmarkierung.

| *Lieferland*
|ISO-Code für das Lieferland nach ISO-3166 Alpha 2.

| *Währung*
|ISO-Code der Auftragswährung nach ISO 4217.

| *Zahlungsstatus*
|Wird passend zur Zahlung als farbiger Balken und zusätzlich in einem Tooltip als Prozentwert angezeigt.

| *Auftragsbestätigung erstellen*
|Auftragsbestätigung direkt erstellen.

| *Rechnung erstellen*
|Rechnung direkt erstellen.

| *Zahlungseingang direkt buchen*
|Zahlung direkt zum Auftrag buchen. Der Betrag ist frei einstellbar. Der offene Rechnungsbetrag ist voreingetragen.

| *Lieferschein erstellen*
|Lieferschein direkt erstellen.

| *Warenausgang buchen*
|Erlaubt den Warenausgang direkt zu buchen, wodurch der Bestand der Varianten reduziert wird, wenn du Bestand führst. Der Status der Auftrags ändert sich automatisch in Status 7.

| *Tracking-URL anzeigen*
|Die Tracking-URL dient zur Sendungsverfolgung eines Paketes. Die xref:fulfillment:versand-vorbereiten.adoc#840[Tracking-URL] musst du beim Einrichten von Versanddienstleistern eintragen und speichern.

| *Notiz zum Auftrag erstellen*
|Erlaubt eine Notiz zum Auftrag zu verfassen sowie eine bereits vorhandene Notiz zu lesen. An einem Symbol ohne Plus ist erkennbar, dass bereits eine Notiz existiert.

| *Notizen zum Kunden*
|Erlaubt eine Notiz zur Kund:in zu verfassen sowie eine bereits vorhandene Notiz zu lesen.

| *E-Mail-Adresse des Kunden*
|Erlaubt über dein E-Mail-Programm direkt eine E-Mail an die Kund:in des Auftrags zu senden.

| *E-Mail-Service*
|Öffnet das Tab E-Mail-Vorlagen und erlaubt so direkt eine E-Mail-Vorlage an die Kund:in zu senden oder bereits gesendete Vorlagen einzusehen.

| *Vorhandene Vorgänge anzeigen*
|Zeigt u.a. eine Liste von Retouren und Gutschriften mit Datum und Wert.

| *Warenbestand ermitteln*
|Lädt eine Warenbestandsübersicht für die im Auftrag enthaltenen Varianten. +
Über den Warenkorb sind Nachbestellungen möglich.

| *Artikelliste öffnen* oder *schließen*
|Erlaubt die Auftragspositionen eines Auftrags ein- oder auszublenden.

| *Nachbestellung anzeigen*
|Öffnet die auftragsbezogene Nachbestellung im Menü *Nachbestellungen*.

| *Rechnungsnummer*
|Öffnet die Rechnung.

| *Artikel-ID* oder *Varianten-ID*
|Öffnet den Artikel oder die Variante im Menü *Artikel » Artikel bearbeiten*.
|====

[#1500]
== Aufträge bearbeiten

Im Menü *Aufträge » Aufträge bearbeiten* werden deine Aufträge in der oben beschriebenen xref:auftraege:auftraege-verwalten.adoc#1400[Übersicht] angezeigt. Wie oben erklärt, stehen dir bereits in der Übersicht einige Bearbeitungsmöglichkeiten zur Verfügung, um einen schnellen Zugriff auf oft genutzte Funktionen zu gewährleisten. Zudem siehst du so auf einen Blick die grundlegenden Informationen, die du zu einem Auftrag benötigst. +
Die vollständigen und umfangreichen Bearbeitungsmöglichkeiten sind verfügbar, wenn du auf die Auftrags-ID des Auftrages, den du bearbeiten möchtest, klickst. Der gewählte Auftrag öffnet sich und die Auftragseinstellungen stehen dir nach Tabs geordnet zur Verfügung. Du kannst Aufträge bearbeiten, bis ein Dokument für einen Auftrag erstellt wurde. Danach wird der Auftrag aus rechtlichen Gründen gesperrt. +
In den folgenden Unterkapiteln werden dir die Tabs, auf die die Einstellungen sich verteilen, mit den verschiedenen Funktionen zur Bearbeitung erläutert.

[#1520]
=== Auftrag öffnen und bearbeiten

Das Bearbeitungsmenü des Auftrags öffnest du, indem du auf die Titelzeile in der Auftragsliste klickst. Der Auftrag wird dann in einem eigenen Tab geöffnet. Wie oben erwähnt, sind die verschiedenen Bereiche in weitere Tabs unterteilt, die auf dieser Handbuchseite beschrieben werden. Ein geöffneter Auftrag ist an der *ID* im Titel des Tabs erkennbar.

Die meisten Tabs eines Auftrags enthalten kein Speichern-Symbol (icon:save[role="green"]). In diesen Tabs werden die geänderten Einstellungen automatisch gespeichert, z.B. beim Ändern der Markierung oder Mahnstufe im Tab *Übersicht*. Du kannst das Tab wechseln oder den Auftrag gänzlich schließen und erneut öffnen, ohne dass die vorgenommenen Einstellungen verloren gehen. Einige Tabs enthalten jedoch ein Speichern-Symbol (icon:save[role="green"]), z.B. das Tab *Einstellungen*. Hier kannst du das Tab wechseln, ohne deine Änderungen zu verlieren. Du musst jedoch deine Änderungen speichern (icon:save[role="green"]), bevor du den Auftrag schließt.

[IMPORTANT]
.Grundeinstellungen zur Auftragsbearbeitung durch variable Benutzer:innen
====
Damit variable Benutzer:innen Aufträge öffnen können, müssen im Menü *Einrichtung » Aufträge » Einstellungen* die xref:auftraege:grundeinstellungen.adoc#intable-default-status-return[Standard-Status] für *Retouren* und *Gutschriften* gespeichert werden. In der Grundeinstellung ist dort kein Status voreingestellt. Außerdem müssen variable Benutzer:innen im Benutzerprofil unter xref:business-entscheidungen:benutzerkonten-zugaenge.adoc#110[Berechtigung » Tab: Menü » Bereich: Aufträge] für die Bearbeitung von Aufträgen berechtigt sein.
====

[TIP]
.plentyPOS sind nur eingeschränkt bearbeitbar
====
Aufträge, die über das xref:pos:pos.adoc#[Kassensystem plentyPOS] in das System gelangen, sind aus Gründen der Rechtssicherheit zur Bearbeitung gesperrt. Nur wenige Einstellungen lassen sich bearbeiten.
====

[#1530]
=== Tab: Übersicht

Im Tab *Übersicht* eines Auftrags findest du die wichtigsten Parameter zu einem Auftrag. Du erhältst auf einen Blick Informationen zu Preis, Versandkosten, Mehrwertsteuer, Status etc.

[TIP]
.Tipp: Werte ändern
====
Änderbare Werte erkennst du an einer Dropdown-Liste oder an einem *Stift*. Klicke auf einen Stift, um den betreffenden Parameter zu ändern (z.B. Bild 16, links oben unter *Gewicht*).
====

[[table-options-tab-overview]]
.Optionen im Tab *Übersicht* eines Auftrags
[cols="1,2"]
|===
|Einstellung |Erläuterung

| *Auftrag-ID*
|ID des Auftrags. Diese wird automatisch vergeben und ist nicht änderbar.

| *Kunden-ID*
|ID der Kund:in.

| *Kaufabwicklung*
|Öffnet den Auftrag im Bereich *Mein Konto* des Webshops.

| *Eingabe*
|Datum des Auftragseingangs, d.h. wann der Auftrag angelegt wurde bzw. im System eingegangen ist. Das Eingabedatum kann manuell geändert werden, jedoch nur so lange keine Dokumente für den Auftrag existieren.

| *IP-Adresse*
|Zeigt optional die IP-Adresse der Kund:in an. +
Die Option *IP-Adresse des Käufers* wird im Menü *Einrichtung » Mandant » [Mandant wählen\] » Bestellvorgang » Einstellungen* aktiviert bzw. deaktiviert.

| *Markierung*
|Auf Wunsch dem Auftrag eine Markierung zuweisen. Mit Markierungen können Aufträge kategorisiert und so z.B. mit dem Suchfilter gesucht oder für automatische Funktionen, z.B. Ereignisaktionen, verwendet werden.

| *Mahnstufe*
|Wenn eine Kund:in den Auftrag nicht bezahlt, werden hier verschiedene Mahnstufen eingestellt. Diese Mahnstufen werden für automatische Prozesse im Mahnvorgang verwendet.

| *Voraussichtlicher Versand*
|Das Datum des voraussichtlichen Versands wird aus dem Datum ermittelt, das bei einer xref:warenwirtschaft:nachbestellungen-vornehmen.adoc#[Nachbestellung] als Liefertermin hinterlegt wurde. Damit der voraussichtliche Versand angezeigt wird, müssen die Nachbestellung sowie der Liefertermin des Artikels bestätigt sein und der Auftrag muss sich in *Status 4* befinden. +
*_Wichtig_*: Die weitere Option <<#intable-shipped-on, Versanddatum>> im Tab *Einstellungen* hat eine andere Funktion.

| *Kopieren*
|Kopiert den Auftrag und legt in einem separaten Auftrags-Tab einen neuen Auftrag mit eigener ID an.

| *Löschen*
|Löscht den Auftrag. Es erfolgt eine Sicherheitsabfrage. +
Das Löschen-Symbol (icon:minus-square[role="red"]) wird in folgenden Fällen nicht angezeigt: +
- Wenn bereits steuerrelevante Dokumente für den Auftrag existieren. +
- Wenn die Benutzer:in nicht xref:business-entscheidungen:benutzerkonten-zugaenge.adoc#100[berechtigt] ist, Aufträge zu löschen. +
- Nach dem Buchen des Warenausgangs. +
- Wenn ein Lieferauftrag angelegt wurde. +
- Wenn Kindaufträge existieren. +
Generell sollten Aufträge nicht gelöscht werden. Durch die Verknüpfung mit Artikeln, Versandeinstellungen und weiteren Funktionen, wie Stornierungen und Retouren, kann es nach dem Löschen zu Fehlern an den Verknüpfungspunkten kommen. Neu angelegte Aufträge können jedoch gelöscht werden. Möchtest du einen Auftrag mit Kindaufträgen löschen, müssen zuerst die Kindaufträge gelöscht werden.

| [#intable-splitting-orders]*Teilen*
|Teilt den Auftrag. Das Verhalten beim Teilen ist abhängig von deiner xref:auftraege:grundeinstellungen.adoc#intable-behaviour-after-splitting[Grundeinstellung] dafür. +
Im Standardverhalten werden beim Teilen eines Auftrags 2 neue Aufträge erstellt. Der ursprüngliche Auftrag wird gelöscht. Für die neuen Aufträge werden jeweils die Versandkosten neu ermittelt. Bevor der Auftrag geteilt wird erfolgt eine Abfrage zur Verteilung der Auftragspositionen. +
Ein Auftrag kann geteilt werden, wenn: +
- Er nicht gesperrt ist, +
- noch kein Warenausgang gebucht wurde, +
- keine Kindaufträge erzeugt wurden (z.B. eine Retoure oder Lieferaufträge), +
- keine steuerrelevanten Dokumente am Auftrag hängen und +
- dem Auftrag noch keine Zahlung zugeordnet wurde. +
Hast du die andere Option *Statuswechsel* gewählt, entstehen ebenfalls 2 neue Aufträge, aber der Originalauftrag bleibt erhalten und wird in einen von dir definierten Auftragsstatus verschoben. Ein weiterer Unterschied ist, dass mit dieser Einstellung auch Aufträge geteilt werden dürfen, denen bereits eine Zahlung zugeordnet wurde oder für die steuerrelevante Dokumente (Wichtig: Rechnung und Stornobeleg) erstellt wurden. Sowohl die zugeordnete Zahlung als auch die Dokumente bleiben für den Originalauftrag erhalten und werden nicht in die aufgeteilten Aufträge übernommen. +
Möchtest du ein anderes xref:auftraege:grundeinstellungen.adoc#intable-splitting-behaviour-shipping-costs[Verhalten der Versandkosten] als den oben beschriebenen Standard, kannst du dieses in den Grundeinstellungen für Aufträge auswählen.

| *Retoure; Gutschrift; Gewährleistung*
|Auf die Dropdown-Liste klicken, um das Auftragsdokument anzulegen oder zu suchen.

| *Neuer Auftrag*
|Legt einen neuen Auftrag für den Kunden an. Darin werden automatisch Standardeinstellungen vorgenommen, die ggf. angepasst werden müssen.

| *Rechnungsanschrift*
|Auf das *kleine Plus* klicken, um die Rechnungsanschrift einzublenden. Auch Telefonnummer, E-Mail-Adresse und ggf. eBay-Kontoname des Kunden werden angezeigt.

| *Lieferanschrift*
|Auf das *kleine Plus* klicken, um die Lieferanschrift einzublenden. Ist die Lieferanschrift mit der Rechnungsanschrift identisch, wird *Lieferanschrift* durchgestrichen angezeigt. +
Bei Bedarf auf *Neue Lieferanschrift* klicken, um eine neue Lieferanschrift anzulegen, oder auf *Alle Lieferanschriften auflisten*, um eine Lieferanschrift zu wählen. +
*Lieferanschrift exportieren* = Exportiert die Lieferanschrift im für den gewünschten Versanddienstleister ausgewählten Export-Format.

| *Bankdaten*
|Auf das *kleine Plus* klicken, um die xref:payment:bankdaten-verwalten.adoc#bankdaten-kunden[Bankdaten des Kunden] einzublenden und bei Bedarf zu bearbeiten.

| *Kundennotizen*
|Du wirst weitergeleitet zum Bereich *Messenger* des Kontaktdatensatzes. Hier kannst du entweder eine neue Nachricht erstellen oder bereits vorhandene Nachrichten öffnen.

| *Auftragsnotiz*
|Zeigt die zur Kund:in gespeicherten Auftragsnotizen an. Auf *Neue Notiz* klicken, um eine Auftragsnotiz anzulegen. Neue Notizen werden mit den üblichen Editor-Funktionen formatiert.

| *Statushistorie*
|Zeigt eine Liste aller Statusänderungen des Auftrags an.

| *Zahlungshistorie*
|Zeigt Details zu Zahlungen wie Zahlungsart, Währung, Zahlungs-ID oder Datum.

| *Artikelpositionen*
|Zeigt Informationen zu den Artikelpositionen des Auftrags an.

| *Bearbeiten*
|Bei Bedarf die Artikeldaten bearbeiten, d.h. Artikelmenge, Artikeldetails, Preise, Rabatte und Mehrwertsteuer-Sätze.

| *Hinzufügen*
|Über die integrierte Artikelsuche bei Bedarf weitere Artikel zum Auftrag hinzufügen.

| *Lagerort zuordnen*
|Ordnet der Auftragsposition einen Lagerort zu. Ist für einen Artikel mehr als ein Lagerort hinterlegt, werden die Lagerorte anhand der Position priorisiert. Wurde kein Lagerort hinterlegt, wird der *Standard-Lagerort* zugeordnet. +
Die Zuordnung des Lagerorts ist für Pick-/Packlisten relevant. +
_Tipp_: Lagerorte können Artikeln auch per xref:automatisierung:ereignisaktionen.adoc#[Ereignisaktion] zugeordnet werden.

| *Zuordnung lösen*
|Hebt die aktuelle Zuordnung des Lagerorts auf. Durch erneutes Klicken auf *Lagerort zuordnen* (siehe oben) kann eine neue Zuordnung vorgenommen und diese so an aktuelle Lagergegebenheiten angepasst werden.
|===

[#1540]
=== Tab: Einstellungen

Im Tab *Einstellungen* sind die grundlegenden Parameter eines Auftrags hinterlegt, wie *Status*, *Herkunft* oder *Zahlungsart*.

[[table-options-tab-settings]]
.Optionen im Tab *Einstellungen* eines Auftrags
[cols="1,2"]
|====
|Einstellung |Erläuterung

| *Status*
|Der Status in dem der Auftrag sich befindet, wird angezeigt. Bei Bedarf kann der Status hier angepasst werden. +
Beachte, dass der Auftragsstatus *[7] Warenausgang gebucht* nicht in einen niedrigeren Status geändert werden kann. Grund ist, dass die Ware bereits verschickt wurde. Sollte dies trotzdem gewünscht sein, muss die Buchung des Warenausgangs vorher zurückgesetzt werden. Danach ist die Änderung in einen niedrigeren Auftragsstatus möglich.

|*Auftragstyp*
|Der Auftragstyp des Auftrages wird angezeigt. Über die Dropdown-Liste ist der Auftragstyp manuell anpassbar.

|*Eigner*
|Der Eigner des Auftrages wird angezeigt. Über die Dropdown-Liste ist der Eigner manuell anpassbar. +
Der Hinweis *Fehlendes Eignerrecht Aufträge* wird angezeigt, wenn der hinterlegte Eigner nicht die erforderlichen xref:business-entscheidungen:benutzerkonten-zugaenge.adoc#40[Eignerrechte] hat. Lege im Menü *Einrichtung » Einstellungen » Benutzer » Konten* fest, dass der Bereich Aufträge für diesen Benutzer als Eigner zur Verfügung stehen soll. +
Sollte der hinterlegte Eigner am Auftrag nicht als Benutzer in plentymarkets angelegt sein, wird der Hinweis *Unbekannter Benutzer* angezeigt. Lege ggf. ein xref:business-entscheidungen:benutzerkonten-zugaenge.adoc#10[Benutzerkonto] für diesen Benutzer an.

|*Herkunft*
|Die Herkunft des Auftrages wird angezeigt. Über die Dropdown-Liste ist die Herkunft manuell anpassbar.

|*Standort*
| Der für den Auftrag gültige Standort wird angezeigt.

|*Sprache*
|Die Sprache des Auftrags. Auftragsdokumente sowie E-Mails werden in der Auftragssprache erzeugt. Die Sprache ist manuell anpassbar. +
Beachte, dass zur Erzeugung der Dokumente und E-Mails in verschiedenen Sprachen die jeweiligen Vorlagen erstellt sein müssen.

| *Lager*
|Lager der Auftragsartikel bzw. das Hauptlager. Bei Bedarf auf *Lagerkorrektur* klicken, um das Lager zu ändern. +
*_Wichtig_*: Die Option *Lagerkorrektur* gleicht die Anzeige im Tab *Einstellungen* des Auftrags mit dem Lager ab, das an den enthaltenen Auftragspositionen hinterlegt ist. Die Option wird nur angezeigt, wenn du in den xref:auftraege:grundeinstellungen.adoc#intable-warehouse-assignment[Grundeinstellungen] im Menü *Einrichtung » Aufträge » Einstellungen* die Option *b) pro Artikelposition kann ein Lager zugeordnet werden* gewählt hast. Änderst du im Tab *Übersicht* an einer Auftragsposition manuell das Lager und wird das neue Lager nicht automatisch in das Tab *Einstellungen* des Auftrags übernommen, klicke auf *Lagerkorrektur*, um die Anzeige des Lagers zu aktualisieren.

| *Warenausgang*
|Zeigt an, ob der Warenausgang gebucht wurde und ggf. das Buchungsdatum. +
Bei Bedarf auf *Warenausgang buchen* (terra:order_sent[]) klicken, um den Warenausgang manuell zu buchen.

| [#intable-shipped-on]*Versanddatum*
|Das Versanddatum wird vom Artikel aus der Option *Erscheinungsdatum* übernommen und ist damit eine Funktion für xref:auftraege:auftraege-verwalten.adoc#1100[Vorbestellungen]. Sind mehrere vorbestellte Artikel im Auftrag vorhanden, wird das am weitesten in der Zukunft liegende Datum hier übernommen. Das Datum ist manuell änderbar.

| *Rückgabedatum*
|Das Datum einer Retoure hinterlegen, wenn Artikel des Auftrags zurückgegeben wurden. Dient als Information zu einer Retoure, damit diese nicht extra geöffnet werden muss.

| *Währung*
|Die Währung des Auftrags. Über *Bearbeiten* (icon:pencil[role="yellow-background"]) lässt sich die Währung ändern sowie ggf. ein Umrechnungskurs eingeben.

| *Zahlungsart*
|Um Änderungen vorzunehmen, eine *Zahlungsart* aus der Dropdown-Liste wählen.

| [#intable-zahlungsbedingungen-auftrag]*Zahlungsbedingungen*
|Mit den Werten *Zahlungsziel (Tage)*, *Valuta (Tage)*, *Skonto (Tage)* und *Skonto (%)* werden die Zahlungsbedingungen gestaltet. *_Wichtig_*: Möchtest du Valuta und Skonto nutzen, muss ein Zahlungsziel angeben sein. Wenn für Zahlungsziel nichts oder der Wert 0 eingetragen ist, sind die Zahlungsbedingungen nicht gültig und werden auch nicht auf Dokumenten übernommen. +
Wenn die Werte bereits an der Firma in den xref:crm:kontakt-bearbeiten.adoc#erlaeuterungen-einzelne-bereiche[Kundendaten] hinterlegt sind, werden sie vom System automatisch übernommen und hier eingetragen. Die Kundendaten haben also Priorität. Ist in den Kundendaten nichts hinterlegt, wird als nächstes überprüft, ob die Zahlungsbedingungen in einer xref:crm:vorbereitende-einstellungen.adoc#kundenklasse-erstellen[Kundenklasse] definiert sind. Falls ja, werden diese Daten übernommen und hier am Auftrag eingetragen. Sind die Werte weder in den Kundendaten noch in einer Kundenklasse hinterlegt, bleiben die Felder zu den Zahlungsbedingungen am Auftrag leer. +
Am Auftrag lassen sich die Zahlungsbedingungen manuell eintragen oder verändern. Dies ist unabhängig davon, von wo Werte übertragen wurden oder ob keine Werte übernommen wurden. +
Auf Dokumenten werden die Werte übernommen, die am dazugehörigen Auftrag hinterlegt sind. Beachte auch die xref:auftraege:auftragsdokumente.adoc#intable-zahlungsbedingungen-dokumente[Dokumenteneinstellungen]. Die Zahlungsbedingungen werden auf den Auftragsdokumenten xref:auftraege:rechnungen-erzeugen.adoc#[Rechnung], xref:auftraege:proformarechnung-erzeugen.adoc#[Proformarechnung], xref:auftraege:auftragsbestaetigung-erzeugen.adoc#[Auftragsbestätigung] und xref:auftraege:dokument-angebot-erzeugen.adoc#[Angebot] ausgegeben. +
 *_Wichtig_*: Die Zahlungsbedingungen werden nur auf diese Dokumente übernommen, wenn es sich um einen Auftrag mit der xref:payment:kauf-auf-rechnung.adoc#[Zahlungsart Rechnung] oder der xref:payment:vorkasse.adoc#[Zahlungsart Vorkasse] handelt.

| *Versanddienstleister*
|Der Versanddienstleister, über den die Artikel des Auftrags versendet werden, wird angezeigt. Der Versanddienstleister wird über das Versandprofil ermittelt und automatisch eingetragen. Anpassungen sind über das Bearbeiten des Versandprofils möglich.

| *Versandprofil &amp; Porto*
|Das Versandprofil und die Portokosten des Auftrags werden angezeigt. Klicke auf *Ändern und neu berechnen* (icon:cog[]), um das Versandprofil anzupassen. Bei Bedarf kann auch das Porto noch manuell angepasst werden.

| *Ext. Auftragsnummer*
|Bei Aufträgen, die z.B. aus einem externen System stammen, kann hier die externe Auftragsnummer eingetragen werden.

| *Zeichen Kunde*
|Zeigt ein Zeichen bzw. einen Text an, den der Kunde bei der Bestellung hinterlegen kann, wenn das Feld *Ihr Zeichen* für den Bestellvorgang sichtbar ist.

| *Pakete*
|Anzahl der zum Auftrag gehörenden Pakete. +
*_Wichtig_*: Dieser Eintrag ist unabhängig von der im Versand-Center eingestellten Paketanzahl. Wenn du die Anzahl der Pakete verändern möchtest, passe dies im Versand-Center an.

| *Paketnummer*
|Paketnummer des Versandpakets. Über *Hinzufügen* (icon:plus-square[role="green"]) kannst du die Paketnummer sowie weitere Informationen zum Paket eingeben. +
Wenn eine Paketnummer hinterlegt wurde, kann das Paket über *Vorschau* (icon:eye[role="blue"]) verfolgt werden. Allerdings nur, wenn unter *Einrichtung » Aufträge » Versand » Optionen » Tab: Versanddienstleister* eine Tracking-URL für den entsprechenden xref:fulfillment:versand-vorbereiten.adoc#800[Versanddienstleister] hinterlegt wurde. Sonst wird das Vorschau-Symbol nicht angezeigt.
|====

[#1550]
=== Tab: Mail

Im Tab *Mail* sind alle xref:crm:e-mails-versenden.adoc#1200[E-Mail-Vorlagen] verfügbar, die du unter *Einrichtung » Mandant » [Mandant wählen] » E-Mail » Vorlagen* konfiguriert hast und die gemäß des Template-Typs für Aufträge sichtbar sind. Du kannst diese Vorlagen per manueller Aktion an Kund:innen schicken, wenn z.B. eine außerplanmäßige E-Mail nötig ist bzw. eine, die nicht durch eine automatische Aktion erfolgt. Gehe wie unten beschrieben vor, um eine E-Mail-Vorlage zu verschicken.

[.instruction]
E-Mail-Vorlage verschicken:

. Öffne das Menü *Aufträge » Aufträge bearbeiten*.
. Öffne den Auftrag.
. Klicke auf das Tab *Mail*.
. Wähle ggf. die *Sprache*.
. Wähle im Tab *E-Mail-Vorlagen* das Tab, das die gewünschte E-Mail-Vorlage enthält.
. Markiere die Vorlage.
. Klicke auf *Direkter E-Mail-Versand*. +
→ Die E-Mail wird versendet.
. Warte, bis der Versand durch eine Meldung bestätigt wird.

Bei nicht erfolgreichem E-Mail-Versand prüfe die xref:crm:e-mails-versenden.adoc#100[Zugangsdaten]. Im Menü *Daten » API-Log (veraltet)* werden die Fehlermeldungen zum Vorgang *E-Mail* gespeichert.


[IMPORTANT]
.Kunden ein neues Passwort senden
====
Die E-Mail-Vorlage *Sende Kunde neues Passwort* ist für den Versand aus einem Auftrag nicht verwendbar. Diese E-Mail-Vorlage versendest du im Datensatz des Kunden. Dort ist im Tab *Einstellungen* das Tab *Passwort* verfügbar, wenn sich ein Kunde im Webshop registriert hat. Hier ist der Versand dieser E-Mail-Vorlage vorgesehen.
====

Das Tab *Gesendete E-Mails* bietet eine Übersicht der gesendeten E-Mail-Vorlagen. Dort werden *Datum*, *Empfänger*, die Bezeichnung der *Vorlage* sowie die *Auftrags-ID* aufgeführt. Es werden alle an die Kund:in gesendeten E-Mails aufgelistet, auch die von anderen Aufträgen.

[#1560]
=== Tab: Zahlung

Im Tab *Zahlung* siehst du alle Zahlungen und Teilzahlungen, die zum Auftrag gehören. Über Filter suchst du außerdem nach einzelnen Zahlungen des Auftrags. Im Tab *Zahlungsverkehr* werden in der obersten Leiste der Rechnungsbetrag, der bereits bezahlte Rechnungsbetrag sowie der noch offene Rechnungsbetrag angezeigt. So hast du anhand dieser Zahlen direkt einen Überblick. Außerdem buchst du in diesem Tab Zahlungen manuell über die Schaltfläche *Zahlung buchen*.

[TIP]
.Fehlende Zahlungseingänge
====
Wenn nicht alle Zahlungen des Auftrags angezeigt werden, ändere den Filter *Eingangsdatum von*, um den Zeitraum, ab dem gesucht wird, anzupassen.
====

Weitere Informationen zum Verwalten von Zahlungen findest du auf der Handbuchseite xref:payment:beta-zahlungen-verwalten.adoc#[Zahlungen verwalten].

[#1570]
=== Tab: Belege

Im Tab *Belege* erzeugst du Belege, d.h. z.B. eine Auftragsbestätigung, einen Lieferschein oder eine Rechnung. Beachte, dass das Eingabedatum des Auftrags nicht mehr geändert werden kann, nachdem du Dokumente zu einem Auftrag erzeugt hast.

Die Dokumente werden anhand von xref:auftraege:auftragsdokumente.adoc#[Dokumentenvorlagen] erstellt. Prüfe daher vor der Erstellung der Belege bzw. auch bei einer Fehlermeldung, ob du die Dokumentenvorlagen erstellt hast.

[TIP]
.Tipp: Dokumentenvorlagen kopieren
====
Wenn du bei der Einrichtung der xref:auftraege:auftragsdokumente.adoc#300[Dokumentenvorlagen] Zeit sparen möchtest, kopiere sie von einer bereits konfigurierten Dokumentenvorlage und passe sie nach Bedarf an.
====

*_Beachte_*, dass erstellte Belege nicht gelöscht werden können, lediglich externe Dokumente. Das Erstellen eines Belegs ist nicht rückgängig zu machen. Zu einigen Dokumenten, zum Beispiel einer Rechnung, Gutschrift oder Mahnung, können Stornobelege erstellt werden. So ist die Nachvollziehbarkeit und Unveränderbarkeit von Rechnungsdokumenten gewährleistet.

Es ist jedoch möglich Dokumente zu archivieren. Das Archivieren von Dokumenten ermöglicht es dir, diese Dokumente neu zu erstellen. Klicke zum Archivieren auf *Archivieren* (terra:receipt_archive[]). Die archivierten Dokumente findest du im Tab *Archivierte Dokumente* unter dem Tab *Belege*. Davon ausgenommen sind, wie oben erwähnt Dokumente, für die ein Stornobeleg erstellt werden muss. Das Archivieren von Dokumenten ist nicht rückgängig zu machen. Liegen die Dokumente einmal im Tab *Archivierte Dokumente*, können sie nicht wieder in den Tab *Dokumente* verschoben werden.

[IMPORTANT]
.Aufbewahrungspflicht
====
Beachte, dass Dokumente einer Aufbewahrungspflicht unterliegen. Stelle also sicher, dass Dokumente in regelmäßigen Abständen gespeichert werden.
====

Die Belege werden jeweils vor der Erstellung konfiguriert. Du kannst je nach Beleg verschiedene Parameter anpassen, z.B. bei einer Rechnung das Datum oder ob der Warenausgang gebucht werden soll. Außerdem kann bei Erzeugung des Belegs ein Statuswechsel für den zugehörigen Auftrag veranlasst werden.

[#1580]
=== Tab: Kunde

Im Tab *Kunde* wird der xref:crm:kontakt-bearbeiten.adoc#erlaeuterungen-einzelne-bereiche[Kontaktdatensatz] angezeigt. Du kannst diese Informationen bearbeiten.

[#1590]
=== Tab: Tickets

Im Tab *Tickets* werden xref:crm:ticketsystem-nutzen.adoc#[Tickets] der Kund:in angezeigt. Du kannst diese Tickets direkt bearbeiten, ohne ins Ticketsystem zu wechseln.

[#1600]
=== Tab: Aufträge

Im Tab *Aufträge* findest du die weiteren Aufträge der Kund:in des betreffenden Auftrags. Du kannst die Aufträge des Kunden dort auch bearbeiten.

[#1610]
=== Tab: Waren

Im Tab *Waren* werden die xref:warenwirtschaft:warenbestaende-verwalten.adoc#[Warenbestandsdaten] der Artikel angezeigt, die in dem Auftrag enthalten sind. Das Tab bietet die volle Funktionalität des Menüs *Warenbestand* mit Ausnahme der Filterfunktionen. Du kannst Warenbestände einsehen und bei Bedarf konfigurieren.

[#1620]
=== Tab: Nachbestellung

Im Tab *Nachbestellung* wählst du Auftragspositionen für eine Nachbestellung. Dabei wählst du, ob eine Nachbestellung nur für den Auftrag erzeugt werden soll oder ob eine Nachbestellung erzeugt werden soll, der auch nachbestellte Auftragspositionen aus anderen Aufträgen hinzugefügt werden. +
Eine Bedingung in beiden Fällen ist, dass die Lieferant:in (Kund:in) und das Lager bei allen Positionen gleich sind. Ist das nicht der Fall, wird für jede Lieferanten-/Lager-Konstellation eine separate Nachbestellung erzeugt.

Damit eine Bestellung möglich ist, muss für jeden Artikel ein Lieferant hinterlegt sein.

[#1630]
==== Auftragspositionen wählen

Gehe wie unten beschrieben vor, um einzelne Positionen bzw. alle Positionen eines Auftrags für die Nachbestellung zu wählen.

[.instruction]
Einzelne Positionen für die Nachbestellung wählen:

. Öffne das Menü *Aufträge » Aufträge bearbeiten*.
. Öffne den gewünschten Auftrag.
. Klicke auf das Tab *Nachbestellung*.
. Wähle die *Varianten*, die du nachbestellen möchtest.
. Klicke auf *Markierte Positionen nachbestellen*. +
→ Eine allgemeine, offene Nachbestellung wird erzeugt, in die neben den markierten Positionen auch Auftragspositionen aus anderen Aufträgen überführt werden, wenn diese über diese Schaltfläche gewählt wurden. Die Teilmengen werden unter *Menge* angezeigt.

Wenn du bestimmte Artikelpositionen für die Nachbestellung gewählt hast, wird *Alle Positionen nachbestellen* deaktiviert und ist nicht mehr wählbar.

[.instruction]
Alle Positionen für eine Nachbestellung wählen:

. Öffne das Menü *Aufträge » Aufträge bearbeiten*.
. Öffne den gewünschten Auftrag.
. Klicke auf das Tab *Nachbestellung.*
. Klicke auf *Alle Positionen nachbestellen*. +
→ Es wird nur für diesen Auftrag eine Nachbestellung erzeugt, die alle Positionen des Auftrags enthält. Die Teilmengen werden unter *Menge* angezeigt.

[#1640]
==== Nachbestellung ausführen

[TIP]
.Bedeutung der Angaben unter Menge
====
In der Spalte *Menge* siehst du auf einen Blick die gelieferte Menge (grüne Zahl), die offene Menge (rote Zahl) und die bestellte Menge. +
Unter *geliefert* werden Teilmengen angezeigt, wenn diese als Teillieferung in der Nachbestellung unter *Status* gebucht werden. +
====

Nachdem du die Auftragspositionen gewählt haben, führst du nun die eigentliche Nachbestellung aus. Gehe dazu wie folgt vor:

[.instruction]
Nachbestellung ausführen:

. Klicke im Tab *Nachbestellung* des Auftrags auf einen *Warenkorb* (material:add_shopping_cart[]). +
→ Das Menü *Nachbestellung* wird geöffnet. Im Abschnitt *Auftragspositionen* der Nachbestellung werden die bestellten Artikel angezeigt.
. Klicke im Bereich *Auftragsdetails* auf *Bestellung auslösen* (icon:gear[role="darkGrey", stack="long-arrow-right,lr,darkGrey"]). +
→ Die Bestellung wird ausgeführt. Die Bestelldaten werden auch im Auftrag im Tab *Nachbestellung* angezeigt.

[TIP]
.EK und Menge anpassen
====
Du kannst im Bereich *Auftragspositionen* die Optionen *EK* und *Bestellt* anpassen, bevor die Nachbestellung ausgeführt wird.
====

Weitere Details zur Bearbeitung der Nachbestellung und wie du z.B. Teilmengen buchst findest du auf der Handbuchseite xref:warenwirtschaft:nachbestellungen-vornehmen.adoc#[Nachbestellungen].

[#1650]
==== Variantenmengen einer Nachbestellung erhöhen

Bei noch offenen Nachbestellungen kannst du die Mengen für Varianten erhöhen. Dies ist für Werte möglich, für die bei der xref:artikel:attribute.adoc#200[Mengenverteilung] prozentuale Anteile hinterlegt wurden. Gehe wie folgt vor, um die Menge für Varianten zu erhöhen.

[.instruction]
Menge für Variante erhöhen:

. Suche den Auftrag, für den du die Nachbestellung anpassen möchtest.
. Wechsle in das Tab *Nachbestellung* des Auftrags.
. Klicke auf *Mengen für Varianten erhöhen*.
. Wähle die *ID der Nachbestellung* und den *Artikel* aus den Dropdown-Listen.
. Wähle das *Attribut* und den *Wert*.
. Trage die *Menge* ein.
. Klicke auf *Menge erhöhen*.
. Wiederhole diese Schritte für jede gewünschte weitere Variante, um die Mengen zu erhöhen.

[#1660]
=== Tab: Lief

Im Tab *Lief* werden xref:auftraege:auftraege-verwalten.adoc#300[Lieferaufträge] erstellt. Du siehst dort die Artikelpositionen des Auftrags, die noch nicht in Lieferaufträge überführt wurden.

[.instruction]
Lieferaufträge manuell anlegen:

. Öffne das Menü *Aufträge » Aufträge bearbeiten*.
. Öffne den gewünschten Auftrag.
. Klicke auf das Tab *Lief*.
. Trage in das Feld *LiefAufMenge* (Menge für den Lieferauftrag) die Menge ein, die in den Lieferauftrag überführt werden soll. +
→ Die eingetragene Menge darf nicht größer sein als die unter *NZMenge* (nicht zugeordnete Menge) angezeigte Menge.
. Klicke auf das *Lieferauftrag anlegen* (terra:execute[]), um den Lieferauftrag anzulegen.

[TIP]
.Lieferaufträge automatisch anlegen
====
Klicke auf *Lieferauftrag automatisch anlegen*, um die Aufträge entsprechend der unter xref:auftraege:auftraege-verwalten.adoc#300[Einrichtung » Aufträge » Auftragstypen » Lieferauftrag] im Feld *Aufträge in Lieferaufträge splitten nach* gewählten Einstellung anzulegen. Es werden alle Auftragspositionen in Lieferaufträge geteilt. Diese Funktion kannst du nur nutzen, wenn noch kein Lieferauftrag zu dem Auftrag besteht.
====

Für die in einem Lieferauftrag enthaltene Menge wird die Bestandsreservierung beim Anlegen eines Lieferauftrags vom Hauptauftrag auf den Lieferauftrag übertragen. Werden Lieferaufträge einzeln angelegt und im Hauptauftrag sind noch Artikel vorhanden, werden diese Artikel ebenfalls reserviert.

[TIP]
.Tipp: Auftragspositionen im Hauptauftrag bearbeiten
====
Auftragspositionen können zum Hauptauftrag hinzugefügt oder daraus gelöscht werden. Allerdings können nur Auftragspositionen, die nicht in Lieferaufträgen enthalten sind, aus dem Hauptauftrag gelöscht werden. Die Menge der Artikel im Hauptauftrag lässt sich erhöhen oder verringern. Du solltest jedoch nur nicht zugeordnete Mengen löschen. Technisch möglich ist auch das Löschen von Positionen, die bereits in einem Lieferauftrag enthalten sind. Dies solltest du jedoch vermeiden.
====

[#1700]
=== Gruppenfunktionen nutzen und mehrere Aufträge bearbeiten

Mit der *Gruppenfunktion* ist es möglich, Prozesse für eine größere Menge an Aufträgen gleichzeitig auszuführen. Damit werden Vorgänge, z.B. eine Statusänderung oder ein E-Mail-Service, auf alle markierten Aufträge angewendet. Die Gruppenfunktion ist besonders zu empfehlen, wenn viele Aufträge bearbeitet werden müssen und die individuelle Bearbeitung sehr zeitaufwändig wäre. Gehe wie folgt vor, um mehrere Aufträge über die Gruppenfunktion zu bearbeiten.

[.instruction]
Gruppenfunktion nutzen:

. Nutze die xref:auftraege:auftraege-verwalten.adoc#1300[Suche], um die Aufträge zu suchen, die du über die Gruppenfunktion bearbeiten möchtest.
. Wähle (icon:check-square[role="blue"]) die Aufträge, die du bearbeiten musst.
. Klicke auf *Gruppenfunkion* über der Auftragsübersicht. +
→ Das Fenster *Gruppenfunktion* mit weiteren Einstellungen öffnet sich.
. Wähle (icon:check-square[role="blue"]) die Gruppenfunktion, die du auf die ausgewählten Aufträge anwenden möchtest.
. Wenn erforderlich, triff weitere Einstellungen für die Gruppenfunktion.
. Klicke auf *Anwenden* (terra:execute[]) über den Gruppenfunktionen. +
→ Die ausgewählte Aktion wird auf die vorher ausgewählten Aufträge angewendet.

[[table-group-functions]]
.Gruppenfunktionen für Aufträge
[cols="1,2"]
|====
|Einstellung |Erläuterung

| *Aufträge gruppieren*
| Mit dieser Gruppenfunktion kannst du einzelne Aufträge in einem neuen Auftrag zusammenfassen indem du sie gruppierst. Das Verhalten beim Gruppieren ist abhängig von deiner xref:auftraege:grundeinstellungen.adoc#intable-behaviour-after-grouping[Grundeinstellung] dafür. Im Standardverhalten werden die ursprünglichen Aufträge beim Gruppieren gelöscht. Die Versandkosten werden dann für den neuen Auftrag neu berechnet. Damit Aufträge gruppiert werden können, müssen sie folgende Kriterien erfüllen: +
- Die Aufträge dürfen nicht gesperrt sein. +
- Der Warenausgang darf nicht gebucht sein. +
- Den Aufträgen dürfen noch keine Zahlungen zugeordnet sein. +
- Die Aufträge dürfen keine steuerrelevanten Dokumente haben. +
- Die Aufträge müssen die gleiche plentyID haben. +
- Die Aufträge müssen vom gleichen Auftragstyp sein. +
- Die Aufträge müssen die gleiche Herkunft haben. +
- Die Aufträge müssen den gleichen Eigner haben. +
- Die Aufträge müssen den gleichen Kontakt haben. +
- Die Aufträge müssen die gleiche Adresse haben. +
- Die Aufträge müssen die gleiche Zahlungsart haben. +
- Die Aufträge müssen die gleiche Währung und den gleichen Wechselkurs haben. +
Hast du die in den Grundeinstellungen die andere Option *Statuswechsel* gewählt, entsteht beim Gruppieren ebenfalls 1 neuer Auftrag, aber die Originalaufträge bleiben erhalten und werden in einen von dir definierten Auftragsstatus verschoben. Ein weiterer Unterschied ist, dass mit dieser Einstellung auch Aufträge gruppiert werden dürfen, denen bereits eine Zahlung zugeordnet wurde oder für die steuerrelevante Dokumente (Wichtig: Rechnung und Stornobeleg) erstellt wurden. Sowohl die zugeordneten Zahlungen als auch die Dokumente bleiben für die Originalaufträge erhalten und werden nicht in den gruppierten Auftrag übernommen. +
Unabhängig von der gewählten Einstellung werden Versandkosten für gruppierte Aufträge neu berechnet. Zudem werden Auftragsnotizen in den neuen Auftrag übernommen.

| *E-Mail Service*
| Mit dieser Gruppenfunktion kannst du entweder an die Kund:innen oder die Lager der ausgewählten Aufträge eine E-Mail senden. Wähle dafür aus den Dropdown-Listen einen *Empfänger*, eine *Vorlage* und optional eine *Markierung*. Achte darauf, dass du vorher eine xref:crm:e-mails-versenden.adoc#1200[E-Mail-Vorlage] eingerichtet hast, damit sie hier als Auswahl zur Verfügung steht.

| *Markierung ändern*
| Mit dieser Gruppenfunktion kannst du die Markierung für die ausgewählten Aufträge ändern. Wähle dafür aus der Dropdown-Liste die Markierung, die den Aufträgen zugewiesen werden soll.

| *Status ändern*
| Mit dieser Gruppenfunktion kannst du den xref:auftraege:auftraege-verwalten.adoc#1200[Auftragsstatus] für die ausgewählten Aufträge ändern. Wähle dafür aus der Dropdown-Liste den Auftragsstatus, der den Aufträgen zugewiesen werden soll.

| *Versandprofil ändern*
| Mit dieser Gruppenfunktion kannst du die xref:fulfillment:versand-vorbereiten.adoc#1000[Versandprofile] der ausgewählten Aufträge ändern. Wähle dafür aus der Dropdown-Liste das Versandprofil aus, das den Aufträgen zugewiesen werden soll. Zudem kannst du zusätzliche *Versandkosten* veranschlagen und aktivieren (icon:check-square[role="blue"]).

| *Eigner ändern*
| Mit dieser Gruppenfunktion kannst du den Eigner für die ausgewählten Aufträge ändern. Wähle dafür aus der Dropdown-Liste den Eigner, der den Aufträgen zugewiesen werden soll.

| *Warenausgang buchen*
| Mit dieser Gruppenfunktion kannst du den Warenausgang für die ausgewählten Aufträge buchen. Wähle dafür das Datum und die Uhrzeit, wann die Buchung erfolgen soll. Wird der Warenausgang für Aufträge gebucht, ändert sich auch der Auftragsstatus der Aufträge zu *7 - Warenausgang gebucht*.

| *Lieferdatum setzen*
| Mit dieser Gruppenfunktion kannst du das Lieferdatum für Auftragspositionen setzen. Nutze dafür den Kalender.

| *Versanddatum setzen*
| Mit dieser Gruppenfunktion kannst du das Versanddatum eines Auftrags setzen. Nutze dafür den Kalender. Das Versanddatum findest du im Tab *Einstellungen* in der Detailansicht eines Auftrags.

| *Newsletter*
| Mit dieser Gruppenfunktion kannst du einen Newsletter den ausgewählten Aufträgen hinzufügen. Dieser wird dann den Kund:innen der Aufträge zugeschickt. Wähle dafür aus der Dropdown-Liste den passenden Newsletter aus. Achte darauf, dass du den xref:crm:newsletter-versenden.adoc#[Newsletter] eingerichtet hast.

| *An atriga (Inkasso) übergeben*
| Diese Gruppenfunktion ist nicht mehr nutzbar.

| *Leads anlegen*
| Diese Gruppenfunktion ist nicht mehr nutzbar.

| *Warenausgang zurückbuchen*
| Mit dieser Gruppenfunktion kannst du einen bereits gebuchten Warenausgang für die ausgewählten Aufträge wieder zurückbuchen, z.B. im Fall von Retouren. Beachte, dass beim Zurücksetzen des Warenausgangs sich auch der Auftragsstatus ändert.

| *Löschen*
| Mit dieser Gruppenfunktion kannst du die ausgewählten Aufträge löschen. Beachte, dass du gut überprüfst, ob du die ausgewählten Aufträge wirklich löschen kannst und solltest. Generell sollten Aufträge nicht gelöscht werden. Durch die Verknüpfung mit Artikeln, Versandeinstellungen und weiteren Funktionen, wie Stornierungen und Retouren, kann es nach dem Löschen zu Fehlern an den Verknüpfungspunkten kommen. Neu angelegte Aufträge können jedoch gelöscht werden. Beachte auch, dass nicht alle Aufträge gelöscht werden können. Folgende Aspekte verhindern das Löschen von Aufträgen: +
- Wenn bereits steuerrelevante Dokumente für den Auftrag existieren. +
- Wenn die Benutzer:in nicht berechtigt ist, Aufträge zu löschen. +
- Nach dem Buchen des Warenausgangs. +
- Wenn ein Lieferauftrag angelegt wurde. +
- Wenn Kindaufträge existieren. Bevor ein Hauptauftrag mit Kindaufträgen gelöscht werden kann, müssen die Kindaufträge gelöscht werden.

|====

[IMPORTANT]
.Anwendung von Gruppenfunktionen
====
Stelle beim Anwenden von Gruppenfunktionen immer sicher, dass du die richtigen Aufträge ausgewählt hast. Beachte zudem, dass manche Änderungen an Aufträgen weitere Abläufe in der Auftragsbearbeitung aber auch Automatismen wie Ereignisaktionen oder Prozesse beeinflussen oder auslösen können. Zum Beispiel könnte durch eine Änderung des Auftragsstatus eine bestimmte Ereignisaktion ausgelöst werden.
====

[.discrete]
==== Beispiele

Nachfolgend findest du zwei Beispiele für die Verwendung der Gruppenfunktion. In Beispiel A soll der Warenausgang für mehrere Aufträge gleichzeitig gebucht werden, in Beispiel B sollen Kunden per Mail über eine Artikelverfügbarkeit informiert werden.

[.instruction]
*Beispiel A*: Warenausgang per Gruppenfunktion buchen

. Öffne das Menü *Aufträge » Aufträge bearbeiten*.
. Markiere die *Aufträge*, für die Warenausgang per Gruppenfunktion gebucht werden soll.
. Klicke auf *Gruppenfunktion*.
. Markiere die Option *Warenausgang buchen*.
. Wähle das *Datum* und die *Uhrzeit*. +
→ Für das Datum und die Uhrzeit wird automatisch das aktuelle Datum und die derzeitige Uhrzeit gewählt, dies ist jedoch änderbar. Die Wahl des Datums und der Uhrzeit ist bei dieser Gruppenfunktion Pflicht.
. Klicke auf *Anwenden* (terra:execute[]), um die Aktion auszuführen.

[TIP]
.Grundeinstellungen zur Auftragsbearbeitung durch variable Benutzer:innen
====
Damit variable Benutzer:innen Aufträge öffnen können, müssen im Menü *Einrichtung » Aufträge » Einstellungen* die xref:auftraege:grundeinstellungen.adoc#200[Standard-Status] für *Retouren* und *Gutschriften* gespeichert worden sein. In der Grundeinstellung ist dort kein Status voreingestellt.
Außerdem müssen diese Benutzer:innen für die Erstellung und Bearbeitung von Aufträgen im xref:business-entscheidungen:benutzerkonten-zugaenge.adoc#110[Benutzerprofil] unter *Berechtigung » Tab: Menü » Bereich: Aufträge* berechtigt werden. +
====

[.instruction]
*Beispiel B*: Kund:innen informieren durch E-Mail mit Gruppenfunktion

*Ausgangssituation*: Ein begehrter Artikel in deinem Shop ist vorübergehend nicht lieferbar, es liegen aber bereits eine ganze Reihe von Bestellungen dafür vor. Gegen solche Lieferverzögerungen sind Händler in aller Regel machtlos, müssen aber die betroffenen Kund:innen schnellstmöglich über einen solchen Umstand informieren.

. Öffne das Menü *Aufträge » Aufträge bearbeiten*.
. Suche (icon:search[role="blue"]) die *Aufträge*, für die die Information per E-Mail an die Kunden verschickt werden soll. +
→ Suche mithilfe der *Artikel-ID* oder der *Artikelbezeichnung* alle Aufträge in Status *ALLE <7*, denn deine Aktion ist nur für die Aufträge relevant, bei denen der Warenausgang noch nicht erfolgt ist.
. Wähle die nach der Suche angezeigten Aufträge aus.
. Klicke auf *Gruppenfunktion*.
. Markiere die Option *E-Mail-Service*.
. Wähle einen *Empfänger*, eine *Vorlage* und optional eine *Markierung*. +
→ Achte darauf, dass du vorher eine xref:crm:e-mails-versenden.adoc#1200[E-Mail-Vorlage] erstellt hast, damit sie dir hier als Auswahl zur Verfügung steht.
. Klicke auf *Anwenden* (terra:execute[]), um die Aktion auszuführen. +
→ Die E-Mail wird an die Kund:innen versendet.

[TIP]
.Status &gt;= 7
====
Beachte, dass ein *Auftragsstatus &gt;= 7* nicht verringert werden kann, ohne dass vorher die Buchung des Warenausgangs zurückgesetzt wird. Für Aufträge mit Auftragsstatus ab Status 7 musst du vorher den *Warenausgang* per Gruppenfunktion rückbuchen.
====

[#1800]
=== Checkliste für Verkaufspreise

Nutze diese Checkliste, wenn du in einem Auftrag etwas an den Artikelpositionen ändern möchtest und auf Probleme stößt. In vielen Fällen liegt es daran, dass die Einstellungen für die Verkaufspreise nicht zu den Parametern des Auftrages passen.

Überprüfe daher, ob folgende Einstellungen für den entsprechenden Preis im Menü *Einrichtung » Artikel » Verkaufspreise* gesetzt sind:

[%interactive]

* [ ] Für *Ab Menge* ist *1* gesetzt.
* [ ] Die *Währung* des Auftrages ist für den Preis freigeschaltet.
* [ ] Dem Preis ist kein *Preistyp* zugeordnet, d.h. weder UVP, noch Aktionspreis oder Setpreis sind ausgewählt.
* [ ] Der *Mandant* des Auftrages ist aktiviert.
* [ ] Die entsprechende *Kundenklasse* ist aktiviert, wenn sie im System eingerichtet sind.
* [ ] Das *Land*, aus dem der Auftrag kommt, ist aktiviert.
* [ ] In den *Herkünften* ist *Manuelle Eingabe* aktiviert.
* [ ] Die entsprechende *Herkunft* des Auftrages ist aktiviert.

Konntest du diese Punkte abhaken, solltest du Änderungen an den Artikelpositionen vornehmen können. Falls du immer noch auf Schwierigkeiten stößt, findest du ausführlichere Informationen zu Verkaufspreisen auf der Handbuchseite xref:artikel:preise.adoc#[Verkaufspreise und Preiskalkulation] oder du fragst unsere Supporter im link:https://forum.plentymarkets.com/[Forum].
