= Aufträge (Testphase)
:keywords: auftrag, auftraege, gutschrift
:description: Erfahre, wie du mit der neuen Aufträge-UI (Testphase) in plentymarkets arbeitest.
:author: team-order-core

== Einleitung
// TODO: Text ergänzen

== Auftragsübersicht

Im Menü *Aufträge » Aufträge [Testphase]* steht dir eine Übersicht deiner Aufträge zur Verfügung. Die Übersichtstabelle ist durchsuchbar und hat zwei Level. Im ersten Level werden dir grundlegende Auftragsinformationen angezeigt. Im zweiten Level werden dir grundlegende Informationen zu den Auftragspositionen angezeigt. Du kannst die Level ausklappen, indem du auf *Ausklappen* (icon:chevron_right[set=material]) klickst.

////
Auf dieser Handbuchseite erhältst du eine Übersicht über

Tabellen individualisieren
Auftragssuche
Auftragspositionen
// TODO: neue Ansicht und weitere Themen


außerdem wird dir erklärt wie du
// TODO: Filter und Operatoren
////

Die Tabellenspalten sind für beide Level konfigurierbar. Beim ersten Öffnen wird dir jeweils die Standardansicht der Tabelle angezeigt. Durch Klicken auf Zahnrad (icon…) öffnet sich das Fenster mit der Auswahl Order table und Order item table. Darüber kannst über *Spalten konfigurieren* (icon:settings[set=material]) wählen, welche Spalten dir in welcher Reihenfolge angezeigt werden. Wähle

[.collapseBox]
.*Spalten konfigurieren*
--

Wenn du die Tabelle einmal angepasst hast, wird diese Auswahl gespeichert. Du kannst das Layout jederzeit ändern. Die zu Verfügung stehenden Spalten findest du in <<tabelle-auftragsuebersicht-auftragsinformationen>> sowie <<tabelle-auftragsuebersicht-auftragspositionen>>. Dort ist zu jeder Spalte auch die Information hinterlegt, ob es sich um eine Standardspalte handelt. Standardspalten werden angezeigt, wenn die Tabelle nicht konfiguriert ist. Gehe wie im Folgenden beschrieben vor, um die Tabelle anzupassen:

[.instruction]
Tabelle individualisieren:

. Klicke auf *Spalten konfigurieren* (icon:settings[set=material]).
. Wähle aus, welches Tabellenlevel du konfigurieren möchtest. +
→ Das Fenster *Spalten konfigurieren* öffnet sich.
. Wähle aus, welche Spalten angezeigt werden sollen. Beachte dafür entsprechend <<tabelle-auftragsuebersicht-auftragsinformationen>> oder <<tabelle-auftragsuebersicht-auftragspositionen>>.
. Verschiebe (icon:sort[set=material]) die Spalten, so dass sie in der Reihenfolge angezeigt werden, in der du sie brauchst.
. Klicke auf *Bestätigen*, um deine Auswahl zu speichern.

[TIP]
Du kannst die Reihenfolge per Drag-and-drop mit einem Klick auf *Verschieben* (icon:drag_indicator[set=material]) verändern. Durch “Haken setzen oder herausnehmen” kannst du die Anzahl der Spalten verändern.


--

Folgende Informationen werden dir in der Auftragstabelle angezeigt:


[[tabelle-auftragsuebersicht-auftragsinformationen]]
.Auftragsübersicht
[cols="1,3"]
|====
|Einstellung|Erläuterung

|*Sperrstatus*
|Zeigt, ob der Auftrag gesperrt ist oder nicht. Ein Auftrag wird gesperrt, sobald eine Rechnung erzeugt wurde. Eine Gutschrift wird gesperrt, sobald ein Gutschriftsdokument erzeugt wurde. Du kannst den Auftrag oder die Gutschrift entsperren, wenn du einen Stornobeleg für das jeweilige Dokument erzeugst. +
Diese Spalte ist eine Standardspalte.

|*Auftragstyp*
|Zeigt dir den Auftragstyp des Auftrags an. Zum Beispiel Gutschrift, Retoure oder Auftrag. +
Diese Spalte ist eine Standardspalte.

|*Auftrags-ID*
|Die ID des Auftrags wird angezeigt. Durch Klicken auf die ID öffnet sich die Detailansicht des Auftrags. Dort stehen dir Bearbeitungsmöglichkeiten für den Auftrag zur Verfügung. +
Diese Spalte ist eine Standardspalte.

|*Kontakt*
|Der Kontakt, …. +
// TODO: nachfragen/probieren. +

|*Kontakt-ID*
|Die ID des Kontakts, d.h. der Käufer:in, wird angezeigt. Damit eine ID angezeigt wird, muss ein Kontaktdatensatz für diese Käufer:in angelegt sein. Handelt es sich um eine Gastbestellung, wird *Gast* angezeigt. +
Durch Klicken auf die ID wird der Kontaktdatensatz geöffnet. +
Dies ist eine Standardspalte.

|*Mandant*
|Der Mandant, über den der Auftrag erstellt wurde, wird angezeigt. +
Diese Spalte ist eine Standardspalte.

|*Mandanten-ID*
|Die ID des Mandanten… wird angezeigt. +
Diese Spalte ist eine Standardspalte.

|Standort*
|Der Standort, zu dem der Mandant gehört über den der Auftrag erstellt wurde, wird angezeigt. +
Diese Spalte ist eine Standardspalte.

|*Standort-ID*
|Die ID des Standortes, zu dem der Mandant gehört, über den der Auftrag erstellt wurde, wird angezeigt. +
Dies ist eine optionale Spalte.

|*Artikelmenge*
| Zeigt die Artikelmenge aller Artikel im Auftrag an. +
Diese Spalte ist eine Standardspalte.

|*Auftragssumme (netto)*
|Die Nettogesamtsumme des Auftrags wird in der Auftragswährung angezeigt. +
Diese Spalte ist eine Standardspalte.

|*Auftragssumme (brutto)*
|Die Bruttogesamtsumme des Auftrags wird in der Auftragswährung angezeigt. +
Diese Spalte ist eine Standardspalte.

|*USt.*
|Der auf den Auftrag angewendete Umsatzsteuersatz wird angezeigt. +
Diese Spalte ist eine Standardspalte.

|*Status*
|Der Bearbeitungsstatus des Auftrags wird durch einen farbigen Punkt dargestellt, dahinter Zahl Strich Status, wie Gutschrift, Storniert. +
Diese Spalte ist eine Standardspalte.

|*Warenausgangsdatum*
|Das Datum, an dem die Waren ausgebucht wurden, wird angezeigt. +
Diese Spalte ist eine Standardspalte.

|*Auftragsdatum*
|Das Datum, an dem der Auftrag ins System kam, wird angezeigt. +
Diese Spalte ist eine Standardspalte.

|*Zahlungsart*
|Die für diesen Auftrag gewählte Zahlungsart wird angezeigt. +
Diese Spalte ist eine Standardspalte.

|*Rechnungsnummer*
|Wurde bereits eine Rechnung für den Auftrag erstellt, wird die Rechnungsnummer angezeigt. +
Diese Spalte ist eine Standardspalte.

|*Zahlungsstatus*
|Der Zahlungsstatus des Auftrags wird angezeigt. +
Ausstehend = Der vollständige Betrag ist noch offen. +
Vorausbezahlt = Der Betrag oder ein Teilbetrag wurde bereits im Voraus bezahlt. +
Teilbezahlt = Der Betrag wurde teilweise bezahlt. +
Bezahlt = Der Betrag wurde vollständig bezahlt. +
Überbezahlt = Es wurde mehr als der ausstehende Betrag gezahlt. +
Diese Spalte ist eine Standardspalte.
// TODO: prüfen

|*Zahlungsdatum*
|Das Datum, an dem die Zahlung für diesen Auftrag eingegangen ist, wird angezeigt. +
Diese Spalte ist eine Standardspalte.

|*Währung*
|Die Währung des Auftrags wird angezeigt. +
Diese Spalte ist eine Standardspalte.

|*Lieferland*
|Das Land, in das dieser Auftrag versendet wird, wird angezeigt. Das angezeigte Lieferland wird der angegebenen Lieferadresse entnommen. +
Diese Spalte ist eine Standardspalte.

|*Lieferdatum*
|Das voraussichtliches Lieferdatum des Auftrags wird angezeigt. +
Diese Spalte ist eine Standardspalte.

|*Quelle*
|Zeigt an, wie der Auftrag erstellt wurde, z.B. manuell oder über REST. ??? Auswahl ManualEntry oder webshop +
Diese Spalte ist eine Standardspalte.

|*Eigner*
| Die Eigner:in des Auftrags wird angezeigt. +
Dies ist eine optionale Spalte.

|*Herkunfts-ID*
| Die ID der Herkunft, über die der Auftrag erstellt wurde, wird angezeigt. Die <<Link zur Seite Auftragsherkunft einfügen#, Auftragsherkunft>> ist der Verkaufskanal, über den ein Auftrag generiert wird. +
Dies ist eine optionale Spalte.

|*Herkunft*
| Die Herkunft, …. +
Dies ist eine optionale Spalte.

|*Lager*
|Das Hauptlager des Auftrags wird angezeigt.  +
Diese Spalte ist eine Standardspalte.

|*Lager-ID*
| Die ID die Hauptlagers wird angezeigt. +
Dies ist eine optionale Spalte.

|*Versandkosten*
|Die Versandkosten des Auftrags werden angezeigt. +
Diese Spalte ist eine Standardspalte.

|*Gewicht [Kg]*
| Das Gesamtgewicht des Auftrags wird angezeigt. +
Dies ist eine optionale Spalte.

|*Referenz*
| Die ID des referenzierten Auftrags wird angezeigt. Durch Klicken auf die ID öffnet sich der referenzierte Auftrag. +
Dies ist eine optionale Spalte.

|*Rechnungsadresse*
|Die Rechnungsadresse wird angezeigt.

|*Lieferadresse*
|Die Lieferadresse wird angezeigt.

// TODO: nicht in der Liste - prüfen
|*Auftragsherkunft*
|Die Auftragsherkunft, über die der Auftrag  erstellt wurde, wird angezeigt. Die <<Link zur Seite Auftragsherkunft einfügen#, Auftragsherkunft>> ist der Verkaufskanal, über den ein Auftrag generiert wird. +
Diese Spalte ist eine Standardspalte.

|*Kontaktname*
|Der Vor- und Nachname des Kontaktes bzw. der Käufer:in wird angezeigt. +
Dies ist eine optionale Spalte.

|*Mandanten-ID*
|Die ID des Mandanten, über den der Auftrag erstellt wurde, wird angezeigt. +
Dies ist eine optionale Spalte.

|Tags*
|Dem Auftrag zugeordnete Tags werden angezeigt. +
Dies ist eine optionale Spalte.

|*Auftragsstatus*
|Der aktuelle <<Link zur Seite Auftragsstatus einfügen#, Auftragsstatus>> des Auftrags wird angezeigt. +
Diese Spalte ist eine Standardspalte.



|====

Klappst du den zweiten Level aus (icon:chevron_right[set=material]), werden dir Informationen zu den Auftragspositionen angezeigt.


[[tabelle-auftragsuebersicht-auftragspositionen]]
.Auftragspositionen
[cols="1,3"]
|====
|Einstellung|Erläuterung

|*Menge*
|Die bestellte Menge der Auftragsposition wird angezeigt. +
Diese Spalte ist eine Standardspalte.

|*Variantennr.*
|Die Variantennummer der Auftragsposition wird angezeigt. +
Dies ist eine optionale Spalte.

|*Variantenname*
|Der Variantenname der Auftragsposition wird angezeigt. +
Dies ist eine optionale Spalte.

|*Varianten-ID*
|Die Varianten-ID der Auftragsposition wird angezeigt.  Durch Klicken auf die ID wird die Variation geöffnet. +
Diese Spalte ist eine Standardspalte.

|*Artikelname*
|Der Artikelname der Auftragsposition wird angezeigt. +
Dies ist eine optionale Spalte.

|*Attribute*
|Die Attribute der Auftragsposition werden angezeigt. +
Diese Spalte ist eine Standardspalte.

|*Nettopreis*
|Der Nettopreis der Auftragsposition wird angezeigt.  +
Diese Spalte ist eine Standardspalte.

|*Bruttopreis*
|Der Bruttopreis der Auftragsposition wird angezeigt.  +
Diese Spalte ist eine Standardspalte.

|*Artikel-ID*
|Die Artikel-ID der Auftragsposition wird angezeigt. Durch Klicken auf die ID wird der Artikel geöffnet. +
Dies ist eine optionale Spalte.

|*Rabatt [%]*
| Der für die Auftragsposition gewährte Rabatt wird angezeigt. +
Diese Spalte ist eine Standardspalte.

|*Aufpreis gesamt*
|Die Summe der Aufpreise der Bestelleigenschaften der Auftragsposition werden angezeigt. +
Diese Spalte ist eine Standardspalte.

|*Gesamtbetrag (netto)*
|Die Nettogesamtsumme der Auftragsposition wird angezeigt. +
Diese Spalte ist eine Standardspalte.

|*Gesamtbetrag (brutto)*
|Die Bruttogesamtsumme der Auftragsposition wird angezeigt. +
Diese Spalte ist eine Standardspalte.

|*Lager*
|Das Lager der Auftragsposition wird angezeigt. +
Diese Spalte ist eine Standardspalte.

|*USt. [%]*
|Der Umsatzsteuersatz der Auftragsposition wird angezeigt. +
Diese Spalte ist eine Standardspalte.

|*Externe Artikel-ID*
|Die externe Artikel-ID wird angezeigt. +
Dies ist eine optionale Spalte.

|*Externe Auftragspositions-ID*
|Die vom Marktplatz übermittelte externe Auftragspositions-ID wird angezeigt. +
Dies ist eine optionale Spalte.


|====

[#order-search]
== Aufträge suchen

Mit der Auftragssuche kannst du sowohl alle Aufträge auflisten als auch bestimmte Aufträge gezielt finden. Beim Öffnen des Menüs wird standardmäßig keine Suche ausgeführt. Du musst die Suche erst ausführen, um Ergebnisse angezeigt zu bekommen. +
Zwei Filter sind für diese initiale Suche standardmäßig gesetzt. Der Filter *Auftragstyp* steht auf ALLE, der Filter *Erstellungsdatum* ist standardmäßig für die letzten zwei Monate gesetzt. +
Du kannst Filter entfernen, wenn du sie nicht nutzen möchtest. Du kannst auch gezielt weitere Sucheinstellungen vornehmen, um die Suche einzuschränken.
siehe dazu Filter neu

Du hast mehrere Möglichkeiten, die Suche zu nutzen. Du kannst einen Wert im Suchfeld eingeben und dann den entsprechenden Filter auswählen. Bei Eingabe einer Zahl oder eines Buchstabens werden dir mögliche Filter vorgeschlagen. Gib den Wert vollständig ein und wähle den passenden Filter aus den Vorschlägen. Wiederhole dies, um Filter miteinander zu kombinieren. Klicke auf *Suchen* (icon:search[set=material]), um die Suche auszuführen. +

Möchtest du erst einen Filter aus der Filterliste wählen, klicke auf *Filter* (icon:tune[set=material]). Die verfügbaren Filter werden dir angezeigt. Gib einen Wert im gewünschten Filter ein. Hast du alle benötigten Filter gesetzt, klicke auf *Suchen*. +
Möchtest du einen gesetzten Filter löschen, entferne den Chip, indem du auf x klickst. In <<table-order-search-filters>> werden die verfügbaren Filter erläutert.

Zudem kannst du mit der Komponente *Gespeicherte Filter* (icon:bookmarks[set=material]) ausgewählte Filter in der UI speichern. Gespeicherte Filtersets sind dann in dieser Komponente bei jedem Öffnen des Menüs auswählbar, ähnlich wie Lesezeichen. Jede:r Benutzer:in kann eigene Filter festlegen.

// TODO: nicht in der Liste, prüfen
|*Datum*
|Filtert nach einem bestimmten Datum, das du hier über den Kalender wählen kannst. Dieser Filter ermöglicht es dir somit, Warenbestand zu einem bestimmten Zeitpunkt zu exportieren. +
*_Hinweis:_* Mit dem Datumsfilter kann lediglich die Bestandsmenge pro Lager, nicht aber pro Lagerort ausgegeben werden. Aktiviere deshalb die folgenden Datenfelder _nicht_: *Lagerort*, *Lagerort-ID*, *Lagerortmenge*, *Lagerortname*. +
Die Bestandsmenge für das gewählte Datum wird anschließend im Datenfeld *Physischer Bestand* des Ordners *Warenbestand* angezeigt.

|====


[[table-order-search-filters]]
.Verfügbare Filter in der Auftragssuche TODO: ergänzen
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Auftrags-ID*
|Gib eine oder mehrere Auftrags-IDs ein, um diese konkreten Aufträge zu suchen.

|*Status*
|Wähle einen Status aus der Dropdown-Liste, um alle Aufträge mit diesem Status zu suchen.

|*Eigner*
|Wähle einen Eigner aus der Dropdown-Liste.

|*Mandant (Shop)*
|Wähle einen Mandanten aus der Dropdown-Liste.

|*Auftragstyp*
|Wähle einen Auftragstyp aus der Dropdown-Liste, um alle Aufträge dieser Art zu suchen.
xref:auftraege:auftraege-verwalten.adoc[Aufträge verwalten].

|*Erstellungsdatum*
|Gib ein Datum ein oder wähle ein Datum über den Kalender, um alle Aufträge zu suchen, die an diesem Datum erstellt wurden.

|*Auftragseingang*
|Gib ein Datum ein oder wähle ein Datum über den Kalender, um alle Aufträge zu suchen, die an diesem Datum eingegangen sind.

|*Warenausgang*
|Gib ein Datum ein oder wähle ein Datum über den Kalender, um alle Aufträge zu suchen, die an diesem Datum verschickt wurden.

|*Zahlungsstatus*
|Wähle einen Zahlungsstatus aus der Dropdown-Liste, um alle Aufträge mit diesem Zahlungsstatus zu suchen. Es stehen die folgenden Zahlungsstatus zur Verfügung:
Ausstehend, Vorausbezahlt, Teilbezahlt, Bezahlt, Überbezahlt.
// TODO: Verweis xref  - hinzufügen zu weiter oben

|*Varianten-ID*
|Gib eine oder mehrere Varianten-IDs ein, um Aufträge zu suchen, die diese Varianten enthalten.

|*Lager*
|Wähle eine Lager aus der Dropdown-Liste.

|*Tag*
|Wähle einen Tag aus der Dropdown-Liste.

|*Dokumentennummer*
|Gib eine Dokumentennummer ein.

|*Dokumentart*
|Wähle eine Dokumentart aus der Dropdown-Liste.

|*Hauptauftrag ausschließen*
|Wähle in der Dropdown-Liste, ob bei der Suche auch Hauptaufträge mit ausgegeben werden sollen oder nicht. Dies bezieht sich z.B. auf die Suche von Lieferaufträgen. +
*Ja* = Es werden keine Hauptaufträge in den Ergebnissen ausgegeben. +
*Nein* = Hauptaufträge werden in den Ergebnissen auch ausgegeben.

| *Variantennummer*
|Gib eine Variantennummer ein, um Aufträge zu suchen.

| *Externe Auftragsnummer*
|Gib eine Externe Auftragsnummer ein, um Aufträge zu suchen.

|*Kontaktdaten*
|Gib ein Suchwort ein, um nach dem entsprechenden Kontakt zu suchen.
// TODO: prüfen * xref:auftraege:auftraege-verwalten.adoc#210[Kontaktdaten]

|*Artikeldaten*
|Gib Artikeldaten ein, um nach Aufträgen zu suchen.

=== Nach Aufträgen filtern

Wenn du eine Suche ausführst, siehst du deine gewählten Filter oben als Chips dargestellt. Um voreingestellte Filter zu sehen oder auszuwählen, gehe folgendermaßen vor.

[.instruction]
Nach Aufträgen filtern:

. Öffne das Menü *Aufträge » Aufträge (Testphase)*.
. Gehe in die Suchleiste und klicke auf den Filter (icon:tune[set=material]). +
→ Die Filtereinstellungen werden geöffnet..
. Wähle Filter, um nur ausgewählte Daten in der Auftragsübersicht zu sehen. Die Auswahl der Filter kann verändert werden.
. Klicke auf *SUCHEN*. +
→ Du erhältst eine Liste der gefilterten Daten.


=== Filteransicht anpassen

Die Filteransicht entspricht nicht deinen Vorstellungen und du möchtest diese gerne auf deine Bedürfnisse anpassen? Über den Bearbeitungsmodus kannst du die Ansicht beliebig verändern.

[.instruction]
Filteransicht anpassen:

. Öffne das Menü *Aufträge » Aufträge [Testphase]*.
. Klicke auf *Ansicht bearbeiten* (icon:design_inline_edit[set=plenty]). +
→ Der Bearbeitungsmodus wird geöffnet und die Standardansicht der Filter wird angezeigt.
. Klappe rechts die *Einstellungen* auf.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<table-filter-settings>>.


==== Angezeigte Filter wählen

Im Bearbeitungsmodus unter *Einstellungen » Filter-Einstellungen* werden dir die Filter in den Spalten *Verfügbare Filter* und *Angezeigte Filter* angezeigt. Entscheide selbst, welche Filter in der Ansicht sichtbar sein sollen.


[[table-name]]
.Verfügbare und Angezeigte Filter in der Auftragssuche
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Verfügbare Filter*
|In der linken Spalte werden alle verfügbaren Filter angezeigt. +
Hinweis: Die Filter werden in die Gruppen *Nummern und IDs*, *Daten* und *Andere* gruppiert.

|*Angezeigte Filter*
|In der rechten Spalte werden die ausgewählten Filter angezeigt.



[.instruction]
Angezeigte Filter wählen:

. Öffne das Menü *Aufträge » Aufträge [Testphase]*.
. Klicke auf *Ansicht bearbeiten* (icon:design_inline_edit[set=plenty]). +
→ Der Bearbeitungsmodus wird geöffnet.
. Klappe die Einstellungen auf, um die *Verfügbaren Filter* und die *Angezeigten Filter* zu sehen.
. Verschiebe die Filter, die angezeigt werden sollen, per Drag & Drop vom Bereich *Verfügbare Filter* in den Bereich *Angezeigte Filter*.
*_Tipp:_* Ziehe die Filter in der Spalte *Angezeigte Filter* an die gewünschte Stelle und passe so die Reihenfolge beliebig an.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Die ausgewählten Filter werden in der Auftragsübersicht angezeigt. +
*_Tipp:_* Wenn dir Filter fehlen, kannst du sie über die oben beschriebenen Schritte ergänzen.
. Klicke auf icon:delete[set=material], um einen nicht benötigten Filter zu schließen. +
→ Der Filter wird dann wieder im Bereich *Verfügbare Filter* angezeigt.     Tooltip remove filter
. Klicke auf icon:plus[role="darkGrey"], um einen *Verfügbaren Filter* in den Bereich *Angezeigte Filter* zu verschieben.      Tooltip add filter


[#aktuellen-filter-speichern]

=== Aktuellen Filter speichern

Wenn du eine Suche mit Filtern ausführst, siehst du deine gewählten Filter oben als Chips dargestellt. Diese Filter kannst du speichern, um sie in Zukunft schneller und einfacher wieder verwenden zu können. Du kannst entweder einen Filter direkt beim Erstellen als Standard festlegen (Kugel nach rechts schieben, wird blau) oder du legst den Filter nachträglich aus der Übersicht heraus als Standard fest (auf Sternsymbol klicken *Als Standard festlegen*).

// TODO: Screenshots sinnvoll?

[.instruction]
Filter speichern:

. Öffne das Menü *Aufträge » Aufträge [Testphase]*.
. Gehe in die Suchleiste. Wähle die gewünschten Filter und gebe die entsprechenden xx (Zahlen, Buchstaben,...) ein.
. Führe die Suche aus.
. Klicke auf *Gespeicherte Filter* (icon:bookmarks[set=material]).
. Klicke auf *Aktuellen Filter speichern* (icon:bookmark_border[set=material]). +
→ Das Fenster *Filter speichern* öffnet sich.
. Vergib einen *Filternamen*.
. Entscheide, ob
** das Filterset als Standard-Filterset genutzt werden soll (icon:toggle-on[role="blue"]) (Als Standard festlegen).
** das Filterset für alle Benutzer:innen zur Verfügung stehen soll (icon:toggle-on[role="blue"]) (Filter für alle Benutzer erstellen).
. Klicke auf *SPEICHERN*.
→ Der Filter erscheint nun unter *Gespeicherte Filter* (icon:bookmarks[set=material]). +

*_Tipp:_* Wenn dir Filter fehlen, kannst du sie über die oben beschriebenen Schritte ergänzen.



[#gespeicherte-filter-anwenden]
=== Gespeicherte Filter anwenden

[.instruction]
Gespeicherte Filter anwenden:

. Klicke auf *Gespeicherte Filter* (icon:bookmarks[set=material]).
. Klicke auf einen bereits erstellten Filter. +
→ Die Suche wird ausgeführt und die verwendeten Filtereinstellungen werden oben als Chips dargestellt.


[#aktuellen-filter-speichern] - kopiert aus Versandcenter

=== Aktuellen Filter speichern
…

[.instruction]
Aktuellen Filter speichern:
…
. Entscheide, ob
** dieser <<#filter-als-standard, Filter als Standard>> festgelegt werden soll (icon:toggle-on[role="blue"])
** dieser Filter für alle Benutzer:innen erstellt werden soll (icon:toggle-on[role="blue"]).
. Klicke auf *SPEICHERN*. +

|====

// TODO: prüfen [#order-overview-single-actions]
== Aufträge in der Übersicht bearbeiten

In der Auftragsübersicht stehen dir für Aufträge verschiedene Bearbeitungsfunktionen zur Verfügung. Diese ermöglichen eine schnelle Bearbeitung, ohne in die Detailansicht eines Auftrags gehen zu müssen. Du kannst entweder <<LINK#, einzelne Aufträge>> bearbeiten oder über die <<LINK#, Gruppenfunktion>> mehrere Aufträge gleichzeitig bearbeiten ??. +
In der Detailansicht eines Auftrags stehen dir umfassendere Funktionen zur Verfügung. Zudem kannst du die Detailansicht eines Auftrags individuell gestalten. Mit MyView kannst du bestimmen, welche Informationen dir in welcher Struktur angezeigt werden. Mit diesem besseren Überblick wird deine Auftragsbearbeitung auch effizienter.

// TODO: prüfen [#order-overview-single-functions]

=== Einzelne Bearbeitungsfunktionen

Schon in der Auftragsübersicht stehen dir Bearbeitungsfunktionen für Aufträge zur Verfügung. Das bedeutet, dass du für die wichtigsten Schritte in der Auftragsbearbeitung nicht extra in die Detailansicht eines Auftrags gehen musst. So ermöglichen die Funktionen eine schnelle Bearbeitung von Aufträgen mit wenigen Klicks.

Beachte, dass nur die Funktionen angezeigt werden, die auf diesen Auftrag angewendet werden können und für die die Benutzer:in die Rechte hat.

[.instruction]
Einzelfunktion für Auftrag nutzen:

. Suche den Auftrag, den du bearbeiten möchtest.
. Klicke auf das Kontextmenü (icon:more_vert[set=material]) am Ende der Zeile. +
→ Dadurch öffnet sich ein Overlay mit den für den Auftrag verfügbaren Funktionen.
. Wähle die Funktion aus, die du auf den Auftrag anwenden möchtest.


[[table-single-functions]]
.Einzelne Bearbeitungsfunktionen für Aufträge
[cols="1,3,3"]
|====
|Einstellung |Erläuterung |Rechte

|*Dokument erstellen*
|Mit der Funktion *Dokument erstellen* (icon:note_add[set=material]) erstellst du für den Auftrag ein Dokument. In der Auswahl werden dir nur die Dokumente angezeigt, die du für diesen Auftrag erstellen kannst. Wurde z.B. schon eine Rechnung für diesen Auftrag erstellt, steht dir Rechnung nicht mehr zur Auswahl, dafür aber eine Rechnungsstornierung.

|*Warenausgang buchen*
|Mit der Funktion *Warenausgang buchen* (icon:output[set=material]) buchst du für den Auftrag den Warenausgang sofort. Das Warenausgangsdatum und die Uhrzeit werden dir in einem Fenster angezeigt, sobald du auf diese Funktion klickst.
|

|*Referenzierte Bestellungen anzeigen*
|Mit der Funktion *Referenzierte Bestellungen anzeigen* (icon:account_tree[set=material]) kannst du dir zu diesem Auftrag gehörende andere Aufträge anzeigen lassen. Bei einer Retoure z.B. den dazugehörigen Originalauftrag. Die Aufträge werden dir in einem Fenster angezeigt, sobald du auf diese Funktion klickst.

|*Zahlung buchen*
|Mit der Funktion *Zahlung buchen* (icon:credit_card[set=material]) fügst du dem Auftrag eine manuelle Zahlung hinzu. Durch Klicken auf diese Funktion öffnet sich das Bearbeitungsfenster *Zahlung buchen*, in dem du die erforderlichen Einstellungen treffen kannst.

// TODO: prüfen
ADD INFO Angezeigt werden die Auftrags-ID und der Betrag.
. Wähle durch Klick auf *Haben/Soll* die gewünschte Option aus. Voreingestellt ist Haben.
. Wähle durch Klick auf *Währung* per Dropdown die gewünschte Währung aus. Voreingestellt ist EUR.
Wechselkurs wird angezeigt.
Verwendungszweck wird angezeigt.
Bei Zahlungseingang wird das aktuelle Datum angezeigt. Durch Klick auf das Kalendersymbol kann das Datum geändert werden.
. Klicke auf *Ausführen* (icon…), um die Angaben zu bestätigen.
|

|*Auftrag löschen*
|Mit der Funktion *Auftrag löschen* (icon:delete[set=material]) löschst du den Auftrag. Beachte, dass du gut überprüfst, ob du den Auftrag wirklich löschen kannst und solltest. Generell sollten Aufträge nicht gelöscht werden. Durch die Verknüpfung mit Artikeln, Versandeinstellungen und weiteren Funktionen, wie Stornierungen und Retouren, kann es nach dem Löschen zu Fehlern an den Verknüpfungspunkten kommen. Neu angelegte Aufträge können jedoch gelöscht werden. +
Beachte auch, dass nicht alle Aufträge gelöscht werden können. Folgendes verhindert das Löschen von Aufträgen: +
- Wenn bereits steuerrelevante Dokumente für den Auftrag existieren. +
- Wenn die Benutzer:in nicht berechtigt ist, Aufträge zu löschen. +
- Wenn der Warenausgang bereits gebucht wurde. +
- Wenn ein Lieferauftrag angelegt wurde. +
- Wenn Kindaufträge existieren. Hauptaufträge mit Kindaufträgen können erst gelöscht werden, wenn die Kindaufträge gelöscht wurden.
|

|====

[#order-overview-group-functions]
=== Gruppenfunktionen nutzen

Mit Gruppenfunktionen ist es möglich, Prozesse für eine größere Menge an Aufträgen gleichzeitig auszuführen. Damit werden Vorgänge, z.B. eine Statusänderung oder ein E-Mail-Service, auf alle ausgewählten Aufträge angewendet. Die Nutzung einer Gruppenfunktion ist besonders zu empfehlen, wenn viele Aufträge bearbeitet werden müssen und die einzelne Bearbeitung sehr zeitaufwändig wäre.

Die Gruppenfunktionen werden dir über der Übersichtstabelle angezeigt, sobald du mindestens einen Auftrag ausgewählt hast. Gehe wie folgt vor, um mehrere Aufträge über die Gruppenfunktion zu bearbeiten.

// TODO: ergänzen Anzeige der Gruppenfunktion über myView

[.instruction]
Gruppenfunktion nutzen:

. Suche die Aufträge, die du über die Gruppenfunktion bearbeiten möchtest.
. Wähle (icon:check-square[role="blue"]) die Aufträge, die du bearbeiten möchtest.
. Klicke über der Auftragsübersicht auf die Gruppenfunktion, die du ausführen möchtest. +
→ Ein Bearbeitungsfenster mit weiteren Einstellungen oder einer Abfrage öffnet sich.
. Wenn erforderlich, triff weitere Einstellungen für die Gruppenfunktion.
. Klicke auf *Anwenden* (icon:execute[set=plenty]). +

→ Die ausgewählte Aktion wird auf die vorher ausgewählten Aufträge angewendet.


[.instruction]
Gruppenfunktion mit der MyView nutzen:

. Öffne das Menü xy…
. Klicke auf *Ansicht bearbeiten* (icon:design_inline_edit[set=plenty]). +
→ Der Bearbeitungsmodus wird aktiviert.
. Klappe die *Einstellungen* auf, um die Gruppenfunktionen zu sehen. Zunächst werden die *Standard-Gruppenfunktionen* angezeigt.
. Wähle die Gruppenfunktionen mit Klick auf den jeweiligen Namen ab, die nicht angezeigt werden sollen.  +
→ Nur die gewählten Gruppenfunktionen werden weiterhin angezeigt.

*Standard-Gruppenfunktionen* sind:
. Aufträge gruppieren
. Warenausgang buchen
. Status ändern
. Tag ändern
. Warenausgang zurückbuchen
. Aufträge löschen


[[table-group-functions]]
.Gruppenfunktionen für Aufträge
[cols="1,2"]
|====
|Einstellung |Erläuterung

| *Aufträge gruppieren*
| Mit der Gruppenfunktion *Aufträge gruppieren* (icon:library_add_check[set=material]) kannst du einzelne Aufträge in einem neuen Auftrag zusammenfassen indem du sie gruppierst. Das Verhalten beim Gruppieren ist abhängig von deiner <<auftraege/grundeinstellungen#intable-behaviour-after-grouping, Grundeinstellung>> dafür. Im Standardverhalten werden die ursprünglichen Aufträge beim Gruppieren gelöscht. Die Versandkosten werden dann für den neuen Auftrag neu berechnet. Damit Aufträge gruppiert werden können, müssen sie folgende Kriterien erfüllen: +
- Die Aufträge dürfen nicht gesperrt sein. +
- Der Warenausgang darf nicht gebucht sein. +
- Den Aufträgen dürfen noch keine Zahlungen zugeordnet sein. +
- Die Aufträge dürfen keine steuerrelevanten Dokumente haben. +
- Die Aufträge müssen die gleiche plentyID haben. +
- Die Aufträge müssen vom gleichen Auftragstyp sein. +
- Die Aufträge müssen die gleiche Herkunft haben. +
- Die Aufträge müssen den gleichen Eigner haben. +
- Die Aufträge müssen den gleichen Kontakt haben. +
- Die Aufträge müssen die gleiche Adresse haben. +
- Die Aufträge müssen die gleiche Zahlungsart haben. +
- Die Aufträge müssen die gleiche Währung und den gleichen Wechselkurs haben. +
Hast du die in den Grundeinstellungen die andere Option *Statuswechsel* gewählt, entsteht beim Gruppieren ebenfalls 1 neuer Auftrag, aber die Originalaufträge bleiben erhalten und werden in einen von dir definierten Auftragsstatus verschoben. Ein weiterer Unterschied ist, dass mit dieser Einstellung auch Aufträge gruppiert werden dürfen, denen bereits eine Zahlung zugeordnet wurde oder für die steuerrelevante Dokumente (Wichtig: Rechnung und Stornobeleg) erstellt wurden. Sowohl die zugeordneten Zahlungen als auch die Dokumente bleiben für die Originalaufträge erhalten und werden nicht in den gruppierten Auftrag übernommen. +
Unabhängig von der gewählten Einstellung werden Versandkosten für gruppierte Aufträge neu berechnet. Zudem werden Auftragsnotizen in den neuen Auftrag übernommen.

| *Status ändern*
| Mit der Gruppenfunktion *Status ändern* (icon:repeat_one[set=material]) kannst du den <<auftraege/auftraege-verwalten#1200, Auftragsstatus>> für die ausgewählten Aufträge ändern. Wähle dafür aus der Dropdown-Liste den Auftragsstatus, der den Aufträgen zugewiesen werden soll.

| *Tag ändern*
| Mit der Gruppenfunktion*Tag ändern* (icon:label[set=material]) kannst du Tags für die ausgewählten Aufträge ändern. Du kannst sowohl Tags hinzufügen als auch Tags entfernen. Wähle aus den Dropdown-Listen die Tags aus, die du den Aufträgen hinzufügen oder von ihnen entfernen möchtest. Du kannst jeweils mehrere Tags auswählen.

| *Warenausgang buchen*
| Mit der Gruppenfunktion *Warenausgang buchen* (icon:output[set=material]) kannst du den Warenausgang für die ausgewählten Aufträge buchen. Wähle dafür das Datum und die Uhrzeit, wann die Buchung erfolgen soll. Wird der Warenausgang für Aufträge gebucht, ändert sich auch der Auftragsstatus der Aufträge zu *7 - Warenausgang gebucht*.

| *Aufträge löschen*
| Mit der Gruppenfunktion *Aufträge löschen* (icon:delete[set=material]) kannst du die ausgewählten Aufträge löschen. Beachte, dass du gut überprüfst, ob du die ausgewählten Aufträge wirklich löschen kannst und solltest. Generell sollten Aufträge nicht gelöscht werden. Durch die Verknüpfung mit Artikeln, Versandeinstellungen und weiteren Funktionen, wie Stornierungen und Retouren, kann es nach dem Löschen zu Fehlern an den Verknüpfungspunkten kommen. Neu angelegte Aufträge können jedoch gelöscht werden. Beachte auch, dass nicht alle Aufträge gelöscht werden können. Folgendes verhindert das Löschen von Aufträgen: +
- Wenn bereits steuerrelevante Dokumente für den Auftrag existieren. +
- Wenn die Benutzer:in nicht berechtigt ist, Aufträge zu löschen. +
- Wenn der Warenausgang bereits gebucht wurde. +
- Wenn ein Lieferauftrag angelegt wurde. +
- Wenn Kindaufträge existieren.

| *Eigner ändern*
| Mit der Gruppenfunktion *Eigner ändern* (icon:people_alt[set=material]) kannst du den Eigner für die ausgewählten Aufträge ändern. Wähle dafür aus der Dropdown-Liste den Eigner, der den Aufträgen zugewiesen werden soll.

| *Versandprofil ändern*
| Mit der Gruppenfunktion *Versandprofil ändern* (icon:local_shipping[set=material]) kannst du die <<fulfillment/versand-vorbereiten#1000, Versandprofile>> der ausgewählten Aufträge ändern. Wähle dafür aus der Dropdown-Liste das Versandprofil aus, das den Aufträgen zugewiesen werden soll.

| *Lieferdatum für Auftrag setzen*
| Mit der Gruppenfunktion *Lieferdatum für Auftrag setzen* (icon:schedule_send[set=material]) kannst du das Lieferdatum für Auftragspositionen setzen. Gib ein Datum ein oder nutze den Kalender zur Datumsauswahl.

| *Versanddatum für Auftragsposition setzen*
| Mit der Gruppenfunktion *Versanddatum für Auftragsposition setzen* (icon:pending_actions[set=material]) kannst du das Versanddatum eines Auftrags setzen. Gib ein Datum ein oder nutze den Kalender zur Datumsauswahl.

| *Warenausgang zurückbuchen*
| Mit der Gruppenfunktion *Warenausgang zurückbuchen* (icon:input[set=material]) kannst du einen bereits gebuchten Warenausgang für die ausgewählten Aufträge wieder zurückbuchen, z.B. im Fall von Retouren. Beachte, dass sich beim Zurücksetzen des Warenausgangs auch der Auftragsstatus ändert.

////
| *E-Mail Service* - siehe alte UI
| Mit dieser Gruppenfunktion kannst du entweder an die Kund:innen oder die Lager der ausgewählten Aufträge eine E-Mail senden. Wähle dafür aus den Dropdown-Listen einen *Empfänger*, eine *Vorlage* und optional eine *Markierung*. Achte darauf, dass du vorher eine <<crm/e-mails-versenden#1200, E-Mail-Vorlage>> eingerichtet hast, damit sie hier als Auswahl zur Verfügung steht.

| *Newsletter* - siehe alte UI
| Mit dieser Gruppenfunktion kannst du einen Newsletter den ausgewählten Aufträgen hinzufügen. Dieser wird dann den Kund:innen der Aufträge zugeschickt. Wähle dafür aus der Dropdown-Liste den passenden Newsletter aus. Achte darauf, dass du den <<crm/newsletter-versenden#, Newsletter>> eingerichtet hast.
////

| *Leads anlegen* - siehe alte UI
| Diese Gruppenfunktion ist nicht mehr nutzbar.

|====

[IMPORTANT]
.Anwendung von Gruppenfunktionen
====
Stelle beim Anwenden von Gruppenfunktionen immer sicher, dass du die richtigen Aufträge ausgewählt hast. Beachte zudem, dass manche Änderungen an Aufträgen weitere Abläufe in der Auftragsbearbeitung beeinflussen können. Es können auch Automatismen wie Ereignisaktionen oder Prozesse ausgelöst werden.
====

Aufträge bearbeiten::
+
--
Gehe wie im Folgenden beschrieben vor, um mehrere Aufträge über die Gruppenfunktion zu bearbeiten.

[.instruction]
Mehrere Aufträge über die Gruppenfunktion bearbeiten:

. Öffne das Menü *Aufträge » Aufträge (Testphase)*.
. Suche die Aufträge anhand der Filtereinstellungen wie im Kapitel <<#auftrag-suchen, Auftrag im Versand-Center suchen>> beschrieben. +
→ Die Aufträge, die den eingestellten Suchkriterien entsprechen, werden in der Übersicht angezeigt.
. Wähle (icon:check-square[role="blue"]) die Aufträge, die du bearbeiten möchtest.
. Klicke in der Symbolleiste ganz oben auf *Aufträge bearbeiten* (icon:edit[set=plenty]). +
→ Die gewählten Aufträge werden auf der linken Seite angezeigt. TODO: formulieren Haben Haken auf blau und Anzahl oben
. Klicke in die Zeile des Auftrags icon:shopping_cart[set=material] *Auftrags-ID*, um den Auftrag in der Detailansicht zu öffnen.
. Nimm die gewünschten Änderungen vor.
. Klicke auf icon:close[set=material] in der Zeile eines Auftrags, um den Auftrag wieder aus der Liste zu entfernen.
. Klicke auf icon:angle-left[] in der Zeile eines Auftrags, um eine Liste mit den Bereichen des Auftrags zu öffnen. +
→ Klicke auf einen der Bereiche, um den Auftrag in der Detailansicht zu öffnen.
. Klicke auf icon:angle-down[], um die Bereiche des Auftrags wieder zu schließen. +
→ Der Auftrag bleibt aber in der Liste sichtbar.
