= Auftragstypen [Testphase] 
:keywords: Auftrag, Auftrag, Auftrag, Aufträge, Aufträge,...
:description: Erfahre, wie du mit Auftragstypen in der Aufträge-UI [Testphase] in plentymarkets arbeitest.
:author: team-order-core


== Auftrag [Beta]
Unter Einrichtung - Aufträge - Auftragstypen - Auftrag [Beta]
siehe auftraege-testphase

== Lieferauftrag

[.instruction]
Gehe folgendermaßen vor, um einen Lieferauftrag anzulegen:

. Öffne das Menü *Aufträge » Aufträge [Testphase]*.
→ Die Auftragsübersicht öffnet sich.
. Suche (icon:search[role="blue"]) anhand der Filtereinstellungen den Auftrag, für den ein Lieferauftrag angelegt werden soll.
. Öffne den *Auftrag*, für den ein Lieferauftrag angelegt werden soll.
. Klicke auf Warenkorb (icon:shopping_cart[set=material]) *Aufträge erstellen*, um auf die Auswahl zu gelangen. Es öffnet sich ein Bearbeitungsfenster. Wähle *Lieferauftrag*, um einen Lieferauftrag anzulegen.
. Wähle entweder die Option *Automatisch aufteilen* oder *Für bestimmte Positionen*.  +
→ Ein Bearbeitungsfenster wird geöffnet.
. Nimm die Einstellungen anhand <<table-xxx>> vor.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Der Lieferauftrag wird angelegt und in einem eigenen Fenster geöffnet.
// TODO: table suchen/anlegen; Schritte für automatisch und best. Positionen

Aufträge in Lieferaufträge splitten
. Öffne das Menü *Einrichtung » Aufträge » Lieferauftrag*.
→ Die Ansicht *Aufträge in Lieferaufträge splitten nach* öffnet sich. Voreingestellt ist die Option *Lager*. 
. Wähle aus der Dropdown-Liste:
Aus, 
Lager, 
Versandprofil, 
Lager und Versandprofil, 
Lager- und Netto-Warenbestand



== Angebot
////
https://knowledge.plentymarkets.com/de-de/manual/main/auftraege/angebot.html
////
// TODO: neue UI 

== Retoure

[#order-type-return]
=== Auftragstyp Retoure nutzen

Der Auftragstyp Retoure bildet den Geschäftsvorfall einer Retoure ab. Retouren können manuell erfasst werden. Zusätzlich kannst du auch deinen Webshop-Kund:innen erlauben, Retouren über den *Mein Konto* Bereich anzumelden. Das Erfassen einer Retoure bucht die retournierten Artikel noch nicht zurück in den Warenbestand. Du erfasst also zunächst die retournierten Artikel und entscheidest anschließend, ob die Artikel wieder zum Bestand gebucht werden oder ob weitere Schritte, wie z.B. eine Reparatur, notwendig sind. Die Retoure ist ein untergeordneter Auftragstyp, da Retouren entweder einem Auftrag oder einer Gewährleistung zugeordnet sind.
Bevor du Retouren erfassen kannst, lege xref:auftraege:auftraege-verwalten.adoc#410[Retourengründe] und xref:auftraege:auftraege-verwalten.adoc#420[Artikelstatus für retournierte Artikel] an.
// TODO: xref anpassen

Der Standardstatus für Retouren ist Status 9. Jede Retoure, die erfasst wird, erhält automatisch diesen Status. Du kannst jedoch jederzeit im Menü *Einrichtung » Aufträge » Einstellungen* einen anderen Status als xref:auftraege:grundeinstellungen.adoc#intable-default-status-return[Standard-Status Retoure] festlegen.
// TODO: xref anpassen

[#enter-return-reason]
=== Retourengründe eingeben

Du kannst bis zu 20 Retourengründe eingeben. Beim Erfassen einer Retoure wählst du für jede Auftragsposition einen Grund. Anhand von Retourengründen ist später nachvollziehbar, ob ein Artikel besonders häufig wegen desselben Grundes retourniert wurde. Die Retourengründe können in mehreren Sprachen hinterlegt werden.

[.instruction]
Retourengründe eingeben:

. Öffne das Menü *Einrichtung » Aufträge » Auftragstypen » Retoure*.
. Wähle die *Sprache* aus der Dropdown-Liste aus.
. Gib *Gründe* für Retouren für die gewählte Sprache ein. +
*_Hinweis:_* Pro Artikelposition kann ein Grund definiert werden.
. *Speichere* die Einstellungen.
. Wiederhole dies ggf. für weitere Sprachen.


[#enter-status-returns]
=== Status für retournierte Artikel eintragen

Du kannst bis zu 12 Artikelstatus anlegen. Die Status kannst du z.B. nutzen, um einerseits den Zustand der retournierten Artikel, aber auch um den Fortschritt beim Bearbeiten der retournierten Artikel anzugeben. Die Status stehen in einer Retoure im Portlet *Übersicht* bei den Auftragspositionen zur Wahl. Um je nach Fortschritt der Bearbeitung verschiedene Status zuzuweisen, lege die benötigten Status an. Du kannst Retourenstatus in mehreren Sprachen hinterlegen.

[.instruction]
Status für retournierte Artikel eintragen:

. Öffne das Menü *Einrichtung » Aufträge » Auftragstypen » Retoure*.
. Wähle die *Sprache* aus der Dropdown-Liste aus.
. Trage die gewünschten *Status* für die Zuordnung zurückgesendeter Artikel für die ausgewählte Sprache ein. +
Hinweis: Pro Artikelposition kann ein eigener Status definiert werden.
. *Speichere* (icon:save[role="green"]) die Einstellungen.
. Wiederhole dies ggf. für weitere Sprachen.


[#create-edit-return]
=== Retoure erfassen und bearbeiten

Eine Retoure erfasst du manuell, wenn ein Paket bei dir eingegangen ist oder du erlaubst deinen registrierten Webshop-Kund:innen, direkt im Kundenkonto des Shops Retouren anzumelden. Nachdem eine Retoure erfasst wurde, werden weitere Bearbeitungsmöglichkeiten sichtbar. So kannst du z.B. den Artikelstatus der retournierten Artikel erst nach dem Erfassen angeben.
////
Hinweis: Die Retourengründe (dropdown grün) werden durch die übergeordneten Retourengründe (gelb) überschrieben.
////

==== Retoure erfassen

[.instruction]
Gehe folgendermaßen vor, um eine Retoure zu erfassen:

. Öffne das Menü *Aufträge » Aufträge [Testphase]*.
→ Die Auftragsübersicht öffnet sich.
. Suche (icon:search[role="blue"]) anhand der Filtereinstellungen den Auftrag, für den eine Retoure erzeugt werden soll.
. Öffne den Auftrag oder die Gewährleistung, für den oder die eine Retoure angelegt werden soll.
. Klicke auf Warenkorb (icon:shopping_cart[set=material]) *Aufträge erstellen*, um auf die Auswahl zu gelangen. Wähle *Retoure*, um eine Retoure anzulegen.
. Wähle entweder die Option *aus einzelnen Positionen* oder *aus allen Positionen*.  +
→ Ein Bearbeitungsfenster wird geöffnet.
. Nimm die Einstellungen anhand <<table-settings-return>> vor.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Die Retoure wird angelegt und in einem eigenen Fenster geöffnet.
////
include::partial$tabelle-aus-optionen-anlegen.adoc[]
////

[[table-settings-return]]
.Optionen beim Erfassen einer Retoure
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+^| *Einstellungen*

| *Status*
|Einen Status für die Retoure aus der Dropdown-Liste wählen. Voreingestellt ist der Standardstatus, der im Menü *Einrichtung » Aufträge » Einstellungen* gespeichert wurde.

| *Eigner*
|Einen Eigner aus der Dropdown-Liste wählen, der dem Retourenauftrag zugewiesen wird.

| *Retourengrund*
|Einen Grund für die Retoure aus der Dropdown-Liste wählen.

| *Paketcode der Retoure*
|Paketcode der Retoure eintragen.

|*Status*
|Wähle einen Status aus der Dropdown-Liste, z.B. Waren auf Zahlung. +
Diese Spalte ist eine Standardspalte.


2+^| *Artikel*

| *Artikel-ID*
|Die Artikel-ID wird angezeigt.

| *Varianten-ID*
|Die Varianten-ID wird angezeigt.

| *Menge*
|Die Verbleibende Menge wird angezeigt.

| *Name der Auftragsposition/Artikel-Name*
|Der Name der Auftragsposition wird angezeigt.

| *Retourengrund*
|Der zuvor ausgewählte Grund für die Retoure wird angezeigt.

| *Artikel-Status/Auftrags-Status**
|Der zuvor ausgewählte Status des Artikels wird angezeigt.

| *Verbleibender Auftragswert in (%)*
|Der verbleibende Wert des Auftrags wird angezeigt. Der Wert liegt zwischen 0 und 100.

| *Retourengrund übertragen*
|Einen Grund für die Retoure wählen, der für alle Artikel der Retoure gilt. +
Wenn hier ein Grund gewählt wird, hat dieser Grund Priorität gegenüber den einzeln wählbaren Gründen auf Artikelpositionsebene.

| *Übernehmen*
|Artikel wählen, die in die Retoure übernommen werden sollen.

| *Menge*
|Artikelmenge eintragen, die in die Retoure übernommen werden soll.

| *Grund der Retoure*
|Individuellen Grund für die Retoure eines Artikels wählen. +
*_Hinweis_*: Wenn ein Grund für alle gewählt wurde, hat dieser Grund Priorität.

| *Artikel*
|Der Artikelname kann hier angepasst werden.

Nachdem eine Retoure erfasst wurde, kannst du den Artikelstatus für retournierte Artikel wählen. Außerdem werden weitere Bearbeitungsmöglichkeiten sichtbar.

|====

// TODO: gehört das auf diese Seite?
[#create-return-note]
=== Rücksendeschein erstellen
//// 
Einen Rücksendeschein kannst du deinen Kund:innen bei Zustellung der Ware im Paket beilegen. In diesem Fall sollte der Rücksendeschein Blankofelder für die Retourengründe enthalten. Du kannst deinen Kund:innen aber auch erlauben den Rücksendeschein im *Mein Konto* Bereich auszufüllen, auszudrucken und der Retoure beizulegen.
Bevor Rücksendescheine erzeugt werden können, muss die Dokumentenvorlage
// TODO:prüfen, xref prüfen
xref:auftraege:ruecksendeschein-erzeugen.adoc#[Rücksendeschein] 
Menü *Einrichtung » Mandant » [Mandant wählen] » Standorte » [Standort wählen] » Dokumente » Rücksendeschein* einrichten.

[TIP]
.Retourengründe auf der Vorlage einstellen
====
[...]
====
////

Prüfe die Artikelpositionen der Retoure und ändere bei Bedarf die Optionen, z.B. die Menge eines Artikels, bevor du im Tab *Belege* der Retoure einen Rücksendeschein erzeugst.


[#use-order-type-repair]
=== Auftragstyp Reparatur nutzen

Reparaturen werden in plentymarkets durch einen eigenen Auftragstyp abgebildet. Reparaturen bestehen aus retournierter, reparaturbedürftiger Ware. Reparaturaufträge können daher nur aus xref:auftraege:auftraege-verwalten.adoc#400[Retourenaufträgen] angelegt werden. Eine Reparatur muss manuell angelegt werden, da jeder Artikel geprüft werden muss.
// TODO: xref prüfen

[#repair-status]
=== Status für Reparaturen eingeben

Hinterlege vor dem Anlegen von Reparaturen verschiedene *Status* für die einzelnen Stationen des Reparaturvorgangs, um den Reparaturverlauf in deinem plentymarkets System genau nachvollziehen zu können. Die Reparaturstatus können in mehreren Sprachen hinterlegt werden.

[.instruction]
Status für Reparaturen eingeben:

. Öffne das Menü *Einrichtung » Aufträge » Auftragstypen » Reparatur*.
. Wähle die *Sprache* aus der Dropdown-Liste aus.
. Trage die von dir benötigten *Status* für Reparaturen für die ausgewählte Sprache ein.
. *Speichere* (icon:save[role="green"]) die Einstellungen.
. Wiederhole dies ggf. für weitere Sprachen.
*_Hinweis:_* Pro Reparatur kann ein Status definiert werden. Es können bis zu 15 Status eingegeben werden.

[#repair-state]
=== Zustände für Reparaturen eingeben

Mit einem *Zustand* kannst du den Artikel genau beschreiben, z.B. ob dieser überhaupt eine Reparatur benötigt oder auch, dass es nicht möglich ist, diesen zu reparieren. Die Zustände können in mehreren Sprachen eingetragen werden.

[.instruction]
Zustände für Reparaturen eingeben:

. Öffne das Menü *Einrichtung » Aufträge » Auftragstypen » Reparatur*.
. Wähle die *Sprache* aus der Dropdown-Liste aus.
. Trage die von dir benötigten *Zustände* für die Zuordnung der Artikelpositionen für die ausgewälte Sprache ein. +
. *Speichere* (icon:save[role="green"]) die Einstellungen.
. Wiederhole dies ggf. für weitere Sprachen.
*_Hinweis:_* Pro Artikelposition kann ein eigener Zustand definiert werden. Es können bis zu 15 Artikelzustände eingegeben werden.

[#create-repair]
=== Reparatur anlegen

[.instruction]
Gehe folgendermaßen vor, um eine Reparatur anzulegen: 

// TODO: table anpassen
. Öffne das Menü *Aufträge » Aufträge [Testphase]*.
→ Die Auftragsübersicht öffnet sich.
. Suche (icon:search[role="blue"]) anhand der Filtereinstellungen nach der Retoure, für den eine Reparatur angelegt werden soll.
. Öffne die *Retoure*, für die eine Reparatur angelegt werden soll.
. Klicke auf (icon:shopping_cart[set=material]) *Aufträge erstellen*, um auf die Auswahl zu gelangen. Es öffnet sich ein .... Wähle *Reparatur*, um eine Reparatur anzulegen.
. Wähle *Für bestimmte Positionen*.  +
→ Ein Bearbeitungsfenster wird geöffnet.
. Nimm die Einstellungen anhand <<table-xxx>> vor.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Die Reparatur wird angelegt und in einem ... geöffnet.
. Wähle einen *Status*. Voreingestellt ist *12 Reparatur*. Dies ist ein Pflichtfeld (Icon Sternchen). Über die Dropdown-Liste kann ein abweichender Status gewählt werden.
. Wähle einen *Eigner* über die Dropdown-Liste. Dies ist ein Pflichtfeld (Icon Sternchen).
. Wähle einen *Status der Reparatur* über die Dropdown-Liste. 

. *Speichere* (icon:save[role="green"]) die Einstellungen. +
Die *Neue Reparatur* wird in der Seitennavigation links unter Auftragsreferenzen in blauer Schrift angezeigt. Öffne darüber das Portlet Auftragsrefenrenzen.


[#edit-repair]
=== Reparatur bearbeiten
// TODO: Portlet prüfen
Je nach Grund der Rücksendung oder Zustand der zu reparierenden Artikel müssen bei der Bearbeitung verschiedene Schritte durchgeführt werden. +
Da es sich bei einer Reparatur um einen eigenen Auftragstyp handelt, kannst du über Detailansicht über Portlet *Übersicht* durch Klick auf den Warenkorb Icon der Reparatur entweder eine Gutschrift, eine Gewährleistung oder eine Retoure anlegen. Die jeweils nötigen Schritte wie die Dokumentenerzeugung, Buchungen des Warenausgangs oder -eingangs oder der eventuellen Buchung von Zahlungen sind jeweils identisch mit denen der Auftragstypen xref:auftraege:auftraege-verwalten.adoc#500[Gutschrift], xref:auftraege:auftraege-verwalten.adoc#600[Gewährleistung] und xref:auftraege:auftraege-verwalten.adoc#400[Retoure] ab.
// TODO: Schritte und xref prüfen

[[table-settings-repair]]
.Optionen beim Erfassen einer Reparatur
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+^| *Einstellungen*

| *Status*
|Einen Status aus der Dropdown-Liste für die Reparatur wählen. Voreingestellt ist der Standardstatus, der im Menü *Einrichtung » Aufträge » Einstellungen* gespeichert wurde.

| *Eigner*
|Einen Eigner aus der Dropdown-Liste wählen, der der Reparatur zugewiesen wird. Voreingestellt ist der aktuelle Benutzer, wenn er der Eigner sein kann.

| *Status der Reparatur*
|Einen *Status der Reparatur* aus der Dropdown-Liste für die Reparatur wählen. Es gibt keine Vorauswahl.


2+^| *Artikel* 

| *Artikel-ID*
|Die *Artikel-ID* wird angezeigt.

| *Varianten-ID*
|Die *Varianten-ID* wird angezeigt.

| *Menge*
|Die *Menge* wird angezeigt.

| *Verbleibende Stückzahl*
|Die *Verbleibende Stückzahl* wird angezeigt.

| *Offene Menge*
|Die *Offene Menge* wird angezeigt.

| *Artikelname*
|Der *Artikelname* wird angezeigt.

// TODO: Klicke rechts auf den Warenkorb (icon:shopping_cart[set=material]), um einen Artikel hinzuzufügen; 

// TODO: Klicke links auf 3 Striche plus *Füge alle offenen Mengen in den Warenkorb*
Unterhalb öffent sich eine neue Tabelle.
Warenkorb
| *Artikel-ID*
|Die Artikel-ID wird angezeigt.

| *Varianten-ID*
|Die Varianten-ID wird angezeigt.

| *Menge*
|Die Menge wird angezeigt. - editable with validation
Pflichtfeld Sternchen

| *Artikelname*
|Der Artikelname wird angezeigt.
Pflichtfeld Sternchen

| *Artikelstatus*
|Eine Dropdown-Liste mit den Zuständen ist verfügbar. Es gibt keine Vorauswahl. Liste ist leer?
Rechts über Icon Mülleimer...



[#order-type-credit-note]
== Gutschrift

In plentymarkets kannst du Gutschriften als PDF-Dateien generieren, um diese z.B. zu drucken oder deinen Kund:innen als E-Mail Anhang zukommen zu lassen. +
Gutschriften nutzt du beispielsweise, um bei bereits bezahlten Aufträgen nachträgliche Preisnachlässe zu gewähren oder wenn im Rahmen von Retouren Rückerstattungen veranlasst werden sollen.

[#use-order-type-credit-note]
=== Auftragstyp Gutschrift nutzen

Bei einer Gutschrift bekommen deine Kund:innen einen Betrag zurückerstattet. Dies kann beispielsweise nach einer xref:auftraege:auftraege-verwalten.adoc#400[Retoure] der Fall sein. Bei der Gutschrift in plentymarkets handelt es sich also nicht um eine Art umgekehrte Rechnung, sondern um eine Rückzahlung. Gutschriftaufträge erzeugst du unter *Aufträge » Aufträge bearbeiten* aus einem Auftrag. Eine Gutschrift ist also immer einem Auftrag zugeordnet. Die in einem Gutschriftauftrag erzeugten Gutschriftbelege werden auch in Buchhaltungsexporten, wie dem *DATEV*-Export, berücksichtigt.
// TODO: xref prüfen

[#save-status-credit-note]
=== Standardstatus für Gutschriften speichern

Bevor du eine Gutschrift anlegst, prüfe den xref:auftraege:grundeinstellungen.adoc#intable-default-status-credit-note[Standard-Status für Gutschriften] im Menü *Einrichtung » Aufträge » Einstellungen*. Passe den Standardstatus bei Bedarf an und speichere die Einstellungen.

[#create-credit-note]
=== Gutschrift anlegen

Eine Gutschrift ist immer mit einem bestehenden Auftrag in deinem plentymarkets System verknüpft. Deshalb musst du den gewünschten Auftrag zunächst in der Auftragsübersicht öffnen, bevor du eine Gutschrift angelegen kannst.

[TIP]
.Gutschriften im Hauptauftrag oder im Retourenauftrag anlegen
====
Hat eine Kund:in den Auftrag bereits gezahlt, beispielsweise per Vorkasse, und entscheidet sich vor dem Warenausgang gegen den Kauf, empfehlen wir den Auftrag zu stornieren und direkt im Hauptauftrag eine Gutschrift über alle Auftragspositionen anzulegen.

// TODO: xref prüfen
Kommt es nach erfolgter Zahlung, Warenausgang und Zustellung der Ware für eine oder alle Auftragspositionen zu einer xref:auftraege:auftraege-verwalten.adoc#400[Retoure] oder im Folgenden zu einem xref:auftraege:auftraege-verwalten.adoc#700[Reparaturauftrag], lege die Gutschrift direkt im entsprechenden Retouren- oder Reparaturauftrag an.
====


:ordertype: Gutschriften

[.instruction]
Gutschriftauftrag anlegen:

. Öffne das Menü *Aufträge » Aufträge [Testphase]*.
→ Die Auftragsübersicht öffnet sich.
. Suche (icon:search[role="blue"]) den Auftrag, für den eine Gutschrift erzeugt werden soll.
. Öffne den Auftrag, für den eine Gutschrift angelegt werden soll.
. Klicke auf Warenkorb (icon:shopping_cart[set=material]) *Aufträge erstellen*, um auf die Auswahl zu gelangen. Wähle *Gutschrift*, um eine Gutschrift anzulegen.
. Wähle entweder die Option *Für alle Positionen* oder *Für bestimmte Positionen*.  +
→ Ein Bearbeitungsfenster wird geöffnet.
. Nimm die Einstellungen anhand <<table-settings-return>> vor.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Die Gutschrift wird angelegt und in einem eigenen Fenster geöffnet.

//// 
include::partial$tabelle-aus-optionen-anlegen.adoc[] 
////

[#create-credit-note-specific]
=== Gutschrift aus spezifischen Position erzeugen

Einzelne Gutschriften kannst du manuell am jeweiligen Gutschriftauftrag erzeugen. Weitere Informationen und Anleitungen zum Anlegen von Gutschriftaufträgen findest du im Kapitel xref:auftraege:auftraege-verwalten.adoc#500[Gutschrift anlegen].
// TODO: xref prüfen

[.instruction]
Gutschrift aus spezifischen Positionen erzeugen:

. Öffne das Menü *Aufträge » Aufträge [Testphase]*. +
→ Die Auftragsübersicht öffnet sich.
. Suche (icon:search[role="blue"]) den Auftrag, für den ein Dokument Gutschrift erzeugt werden soll.
. Öffne den gewünschten Auftrag.
. Klicke auf (icon:shopping_cart[set=material]) *Aufträge erstellen*. +
. Wähle aus der Dropdown-Liste *Gutschrift* die Option *Gutschrift für einzelne Positionen* erstellen. +
→ Die *Gutschrift* zum Auftrag wird erstellt und links in der Navigation als *Gutschrift* unter dem Auftrag angezeigt.
. Klappe das Portlet *Historie* auf. Dort steht links das Erstellungsdatum, der Benutzer, als Aktion Neue Gutschrift und als Status 11 Gutschrift.
In dem Portlet *Übersicht* siehst du den Auftragstyp jetzt als Gewährleistung. Links in der Navigation kann der *Auftragstyp* durch Klick auf x geschlossen werden.

[#create-credit-note-all]
=== Mehrere Gutschriften erzeugen
////
Sollen mehrere Gutschriften zugleich erzeugt werden, kannst du über einen Suchfilter im Menü *Aufträge » Fulfillment* festlegen, welche Aufträge berücksichtigt werden. Zudem kannst du in diesem Menü festlegen, ob der Status des Auftrags geändert werden soll, nachdem die Dokumente erzeugt wurden. Neu sollte das so gehen wie bei Retoure auch.
////

[.instruction]
Mehrere Gutschriften erzeugen:

// TODO: stimmt noch nicht
. Öffne das Menü *Aufträge » Aufträge [Testphase]* » usw*.
. Nimm die Einstellungen anhand <<table-settings-fulfillment-credit-notes>> vor. +
_Beachte_, dass die Einstellungen sowohl *Suchfilter* als auch *Aktionen* umfassen.
. Klicke auf icon:settings[set=material], um die Gutschriften zu erzeugen. +
→ Es öffnet sich eine *PDF-Datei*, in der die zugehörigen Gutschriften aller von dir durch die Suchfilter bestimmten Aufträge enthalten sind.


[[table-settings-return]]
.Optionen beim Erfassen einer Gutschrift
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+^| *Einstellungen*

| *Status*
|Einen Status aus der Dropdown-Liste für die Gutschrift wählen. Voreingestellt ist der Standardstatus, der im Menü *Einrichtung » Aufträge » Einstellungen* gespeichert wurde.

| *Eigner*
|Einen Eigner aus der Dropdown-Liste wählen, der der Gutschrift zugewiesen wird.

// TODO: hier und so richtig?
| *Versandkosten*
|Wähle, ob die Versandkosten aus dem Hauptauftrag in die Gutschrift übernommen werden sollen. Die Option, die du für *Versandkosten in Gutschrift übernehmen* im Menü *Einrichtung » Aufträge » Einstellungen* gespeichert hast, ist voreingestellt.Du kannst die gespeicherte Einstellung anpassen.
////
add the shipping costs to the basket (only for the request / not visible in the basket) if the option is yes
////


2+^| *Artikel*

| *Artikel-ID*
|Die Artikel-ID wird angezeigt.

| *Varianten-ID*
|Die Varianten-ID wird angezeigt.

| *Menge*
|Die Menge wird angezeigt. - editable with validation

| *Verfügbare Menge*
|Die Verfügbare Menge wird angezeigt.

Um Artikel hinzuzufügen, klicke auf icon:shopping_cart[set=material]. Durch Klick auf icon:add[set=material] kannst du weitere Artikel hinzufügen.
// TODO: Bezeichnungen anpassen

Cart
| *Artikel-ID*
|Die Artikel-ID wird angezeigt.

| *Varianten-ID*
|Die Varianten-ID wird angezeigt.

| *Menge*
|Die Menge wird angezeigt. - editable with validation

| *Name der Artikelposition*
|Die Artikelposition ist editierbar.
|====


// TODO: Tab Übersicht

Wenn ein Gutschriftauftrag zu einem Auftrag angelegt wurde, wird im Tab *Übersicht* ?? des Haupfauftrags rechts der Hinweis *Gutschrift verfügbar* angezeigt. Zusätzlich kannst du bereits angelegte Gutschriftaufträge im Tab *Übersicht* des Hauptauftrags über die Dropdown-Liste *Gutschrift / suchen* aufrufen.
// TODO: Neu: wird links unter Auftrag angezeigt ….


[#create-credit-note-note]
=== Gutschriftbeleg erstellen

Nach dem Anlegen des Gutschriftauftrags muss ein Gutschriftbeleg direkt im Gutschriftauftrag erstellt werden. Vor dem ersten Erzeugen eines xref:auftraege:gutschriften-erzeugen.adoc#[Gutschriftbelegs] muss die Dokumentenvorlage im Menü *Einrichtung » Mandant » [Mandant wählen] » Standorte » [Standort wählen] » Dokumente » Gutschrift* eingerichtet werden.

//// 
Bevor du den Gutschriftbeleg im Tab *Belege* ?? des Gutschriftauftrags erzeugst, solltest du die im Gutschriftauftrag enthaltenen Auftragspositionen prüfen und bei Bedarf ändern.

[.instruction]
Gutschriftbeleg erstellen:

. Öffne den Gutschriftauftrag, für den ein Gutschriftbeleg erzeugt werden soll.
. Wähle die Option *Gutschrift* aus der Dropdown-Liste unter *Beleg / erstellen*.
. Klicke auf *Beleg erstellen*. +
→ Der Gutschriftbeleg wird erzeugt und in einem eigenen Tab geöffnet.
////

Erstellte Gutschriften weisen jeweils eine Referenz zu der Rechnung des dazugehörigen Auftrages auf. Im Portlet *Dokumente* eines Auftrags wird dies in der Benennung der Gutschrift angezeigt.


[#order-type-warranty]
== Gewährleistung

=== Auftragstyp Gewährleistung nutzen

Gewährleistungen sind xref:auftraege:auftraege-verwalten.adoc#400[Retouren] relativ ähnlich, denn in beiden Fällen bekommst du Waren eines Auftrags im *Status 7* wieder zurückgesendet. Im Gegensatz zur Retoure erwarten Kund:innen bei einer Gewährleistung aber entweder eine neue Lieferung oder eine Rückerstattung des Rechnungsbetrags mittels einer xref:auftraege:auftraege-verwalten.adoc#500[Gutschrift].
// TODO: xref prüfen

[TIP]
.Garantie vs. Gewährleistung
====
Im Gegensatz zur freiwillig erklärten Garantie handelt es sich bei der Gewährleistung um die *gesetzliche Pflicht* der Händler:innen, Mängel am Artikel, die bereits bei Lieferung bestanden haben, für Käufer:innen kostenlos zu beseitigen. Käufer:innen können die Gewährleistung gerichtlich bis zu 2 Jahre bei beweglichen Artikeln oder 3 Jahre bei unbeweglichen Artikeln geltend machen. Ab 6 Monaten nach Erhalt der Ware müssen Käufer:innen jedoch beweisen, dass die Mängel bereits bei Erhalt der Ware vorhanden war.
====

Wenn ein Gewährleistungsfall vorliegt, entscheidest du als Händler:in, ob du Käufer:innen die Kosten erstattest, den Artikel reparierst oder den Artikel austauschst. Soll ein Umtausch durchgeführt werden, lege eine *Gewährleistung* an. Möchtest du das Geld erstatten, lege eine xref:auftraege:auftraege-verwalten.adoc#500[Gutschrift] im Tab *Übersicht* der Gewährleistung an. Ob du die *Versandkosten* in einer Gewährleistung übernimmst oder nicht, wählst du in den xref:auftraege:grundeinstellungen.adoc#intable-shipping-costs-in-warranty[Grundeinstellungen] im Menü *Einrichtung » Aufträge » Einstellungen*.
// TODO: xref

[TIP]
.Einstellungen einer Gewährleistung
====
Wenn du eine Gewährleistung aus einem Auftrag heraus erzeugst, wird automatisch das *Versandprofil* des Auftrags übernommen. Die Einstellungen sind jedoch in der Gewährleistung änderbar. Bei *Lieferaufträgen* wird ebenfalls automatisch das korrekte Lager eingestellt. Die *Zahlungsart* bei Gewährleistungen ist änderbar.
====

[#create-warranty]
=== Gewährleistung anlegen

Normalerweise legst du eine Gewährleistung in einem bestehenden Retourenauftrag an. Es ist jedoch auch möglich, diese direkt aus dem zugrunde liegenden Hauptauftrag heraus anzulegen.

Wird die Ware nach Lieferung beanstandet und du entscheidest dich beispielsweise aus Kostengründen gegen die Rücksendung der Ware, lege die Gewährleistung direkt im Hauptauftrag an.

Möchtest du dagegen erst den Eingang der Retoure abwarten und die Ware prüfen, lege zunächst einen Retourenauftrag an und erstelle im Rahmen der Abwicklung dort eine Gewährleistung.


:ordertype: Gewährleistungen

[.instruction]
Eine Gewährleistung anlegen:

. Öffne das Menü *Aufträge » Aufträge [Testphase]*. +
→ Die Auftragsübersicht öffnet sich.
. Suche (icon:search[role="blue"]) den Auftrag, zu dem du eine Gutschrift anlegen möchtest.
. Öffne den gewünschten Haupt- oder Retourenauftrag. +
. Klicke auf auf Warenkorb (icon:shopping_cart[set=material]) *Aufträge erstellen* und wähle aus der Dropdown-Liste *Gewährleistung*.
. Wähle entweder die Option *Für alle Positionen* oder *Für bestimmte Positionen*.
Beachte dazu die Erläuterungen in <<tabelle-{ordertype}-anlegen>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Die Gewährleistung wird angelegt und erscheint links in der Navigation unter der Retoure oder dem Hauptauftrag.
// TODO: Tabelle ordertype

Im Portlet *Historie* siehst du die Informationen: 
* Datum der Erstellung
* Benutzer
* die ausgeführte Aktion (hier: Neue Gewährleistung und darüber Warenbestandsautomatik) 
* geänderten Status.

[[table-settings-warranry]]
.Optionen beim Erfassen einer Gewährleistung
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+^| *Einstellungen*

| *Status*
|Einen Status aus der Dropdown-Liste für die Gewährleistung wählen. Voreingestellt ist der Standardstatus, der im Menü *Einrichtung » Aufträge » Einstellungen* gespeichert wurde.

| *Eigner*
|Einen Eigner aus der Dropdown-Liste wählen. Voreingestellt ist der aktuelle Benutzer.

// TODO: später abgleichen
| *Versandkosten*
|Wähle, ob die Versandkosten aus dem Hauptauftrag in die Gewährleistung übernommen werden sollen (Versandkosten kopieren). Die Option, die du für *Versandkosten in Gewährleistung übernehmen* im Menü *Einrichtung » Aufträge » Einstellungen* gespeichert hast, ist voreingestellt. Du kannst die gespeicherte Einstellung anpassen.
JA übernehmen - dann werden die Versandkosten in den Warenkorb übernommen (nicht sichtbar).
NEIN nicht übernehmen


2+^| *Artikel*

| *Artikel-ID*
|Die Artikel-ID wird angezeigt.

| *Varianten-ID*
|Die Varianten-ID wird angezeigt.

| *Menge*
|Die Menge wird angezeigt. - editable with validation

| *Verbleibende Stückzahl*
|Die *Verbleibende Stückzahl* wird angezeigt.

| *Offene Menge*
|Die Verfügbare Menge wird angezeigt.

| *Artikelname*
|Der Artikelname wird angezeigt.

Klicke auf das Icon Warenkorb +, um Artikel in den Warenkorb zu legen.

Warenkorb - rechts Symbol *Spalten konfigurieren* und Mülleimer (tooltip fehlt). Durch Klick auf Mülleimer geht der Artikel zurück in die Auswahl.
| *Artikel-ID*
|Die Artikel-ID wird angezeigt.

| *Varianten-ID*
|Die Varianten-ID wird angezeigt.

| *Menge*
|Die Menge wird angezeigt. - editable with validation

| *Artikelname*
|Der Artikelname wird angezeigt.

|====

[#edit-warranty]
=== Gewährleistung bearbeiten
 
Gewährleistungsaufträge werden in der Navigation unter Auftragssuche angezeigt. Öffne eine Gewährleistung, um beispielsweise einen zusätzlichen *Preis* einzugeben, wenn du dem Käufer einen höherpreisigen Artikel als Ersatz liefern willst. Falls nötig, können hier auch die Mengen der in der Gewährleistung enthaltenen Auftragspositionen verändert werden. Um eine Gewährleistung zu bearbeiten, gehe wie im Folgenden beschrieben vor.

[.instruction]
Gewährleistung bearbeiten:

. Öffne das Menü *Aufträge » Aufträge [Testphase]*.
. Gehe in die Auftragsübersicht.
. Wähle über das Symbol *Filter* im Filter *Auftragstyp* die Option *Gewährleistung*.
. Klicke auf *Suchen* (icon:search[role="blue"]). +
→ Es werden nur Gewährleistungen aufgelistet.
. Klicke in die Zeile der Gewährleistung, die du bearbeiten möchtest. +
→ Die Gewährleistung wird geöffnet.

Der Artikel kann über ... bearbeitet werden. Neu öffnen sich die Portlets und im Portlet *Allgemein* ändert sich der Auftragstyp zu *Gewährleistung*.
// TODO: prüfen/anpassen

[#finish-warranty]
=== Gewährleistung abschließen

Zum Abschließen einer Gewährleistung musst du, wenn für die Ersatzware ein Aufpreis berechnet wird, eine Rechnung in der Gewährleistung erzeugen. Falls du keine Ersatzware versendest, sondern dich mit der Käufer:in auf einen nachträglichen Preisnachlass auf die beanstandete Ware einigst, legst du eine Gutschrift im Hauptauftrag an.

Um die Bearbeitung einer Gewährleistung durch einen Umtausch abzuschließen, gehe wie im Folgenden beschrieben vor.

[.instruction]
Gewährleistung durch Umtausch abschließen:

. Öffne in der Gewährleistung das Portlet *Dokumente*.
. Klicke auf das Symbol Dokument + *Dokument erstellen*.
. Wähle *Rechnung* aus der Liste *Dokument erstellen*. +
→ Ein neues Bearbeitungsfenster *Dokument erzeugen: Rechnung* öffnet sich. +
Eingabe: Datum, Kommentar
Aktionen: Auftragsstatus ändern. Wähle aus der Dropdown-Liste.
//// 
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Die Rechnung wird erzeugt und in einem eigenen Tab geöffnet.
. Wechsle in das Portlet *?*.
. Klicke in der Zeile *Warenausgang* auf das Symbol *Warenausgang buchen*. +
→ Der Warenausgang wird gebucht und der *Status* wechselt automatisch zu *[7] Warenausgang gebucht*.
. Wechsle in das Menü *Aufträge » Aufträge [Testphase]*.
. Setze den Status der Gewährleistung manuell auf Status *[10] Gewährleistung*.
. *Speichere* (icon:save[role="green"]) die Einstellungen.
////

[TIP]
.Zahlungseingang bei Gewährleistungen buchen
====
Grundsätzlich müssen Zahlungen zu Gewährleistungen nur dann gebucht werden, wenn mit Käufer:innen ein Aufpreis vereinbart wurde. In diesem Fall buchst du den Zahlungseingang nach erfolgter Zahlung im Portlet *Zugeordnete Zahlung* der Gewährleistung.
====
//// 
Um die Bearbeitung einer Gewährleistung durch eine Gutschrift an den Käufer abzuschließen, gehe wie im Folgenden beschrieben vor:

[.instruction]
Gewährleistung durch Gutschrift abschließen:

. Öffne den Haupt- oder Retourenauftrag zur Gewährleistung, für die du eine Gutschrift anlegen möchtest.
. Öffne das Portlet *Übersicht*
. Klicke auf die Dropdown-Liste *Gutschrift* und dort auf die Einstellung *anlegen*. +
→ Der Gutschriftauftrag wird angelegt und in einem eigenen Tab geöffnet.

Der weitere Bearbeitungsprozess läuft identisch mit dem regulären Anlegen einer Gutschrift und dem Erzeugen eines Gutschriftbelegs ab und wird im Kapitel xref:auftraege:auftraege-verwalten.adoc#500[Auftragstyp Gutschrift nutzen] detailliert beschrieben.
////

// TODO: 
== Lieferauftrag

[#order-type-delivery-order]
== Auftragstyp Lieferauftrag nutzen

Mithilfe des Auftragstyps *Lieferauftrag* werden aus einem Hauptauftrag Lieferaufträge für die enthaltenen Auftragspositionen generiert, so dass du diese einzeln oder in Teilen verschicken kannst. So kannst du beispielsweise Artikel, die du auf Lager hast, sofort losschicken und Artikel, die du erst noch geliefert bekommst, später nachsenden. Führe dies mit unterschiedlichen oder auch nur mit einem Versanddienstleister durch. +
Lieferaufträge können *manuell*, *automatisch* oder per *Ereignisaktion* erstellt werden.

[WARNING]
.Alle Auftragspositionen in Lieferaufträge übernehmen
====
Erstellst du Lieferaufträge aus einem Auftrag, müssen _alle_ Auftragspositionen des Hauptauftrags in Lieferaufträge überführt werden. Übernimmst du nicht alle Auftragspositionen in Lieferaufträge, kommt es zu Fehlern im Bestand und den Lagern.
====

[#delivery-order-characteristics]
=== Merkmale von Lieferaufträgen

Im Allgemeinen besitzen Lieferaufträge folgende Eigenschaften:

* Die Auftragspositionen eines Lieferauftrages lassen sich nach dem Erzeugen des Lieferauftrages *nicht* mehr anpassen.
* Der *Preis* und das *Gewicht* eines Artikels werden aus dem Hauptauftrag übernommen.
* Die Auftragssprache wird aus dem Hauptauftrag übernommen.
* *Adressetikett*, *Lieferschein*, *Proformarechung* und *Gelangensbestätigung* können im Tab *Belege* eines Lieferauftrags generiert werden.
* Die *Rechnung* und alle weiteren Dokumente werden zentral im Hauptauftrag generiert.
* Die Bestandsreservierung für die in einem Lieferauftrag enthaltene Menge wird beim Anlegen eines Lieferauftrags vom Hauptauftrag auf den Lieferauftrag übertragen.

[IMPORTANT]
.Gemeinsamer Status
====
Der Hauptauftrag folgt immer dem Status des Lieferauftrags mit dem niedrigsten Status.
Wenn z.B. ein Auftrag in Status *5.0* zwei Lieferaufträge hat und einer dieser Lieferaufträge wechselt in den Status *6.5*, ändert sich am Status des Hauptauftrages zunächst nichts. Erst wenn der zweite Lieferauftrag ebenfalls in den Status *6.5* wechselt, wird automatisch auch der Status des Hauptauftrages zu *6.5* geändert.
====

[#basic-settings-delivery-order]
=== Grundeinstellungen für Lieferaufträge vornehmen

[WARNING]
.Lager pro Auftragsposition zuordnen
====
Im Menü *Einrichtung » Aufträge » Einstellungen* muss zwingend für die xref:auftraege:grundeinstellungen.adoc#intable-warehouse-assignment[Zuordnung des Lagers] die Option *b) pro Artikelposition kann ein Lager zugeordnet werden* ausgewählt werden.
====
// TODO: xref

[#edit-orders-and-delivery-orders]
=== Haupt- und Lieferaufträge bearbeiten

// TODO: Text aus alter UI - anpassen
Wenn du einen Hauptauftrag löschen möchtest, musst du zuerst die Lieferaufträge löschen. Lieferaufträge können einzeln oder über die Gruppenfunktion in der Auftragssuche gelöscht werden. Erst danach kann der Hauptauftrag gelöscht werden. Beachte aber, dass Aufträge nicht gelöscht werden können, sobald steuerrelevante Dokumente für diesen Auftrag existieren.

Es können weitere Auftragspositionen zum Hauptauftrag hinzugefügt oder daraus gelöscht werden. Allerdings können nur Auftragspositionen, die nicht in Lieferaufträgen enthalten sind, aus dem Hauptauftrag gelöscht werden. Die Menge der Artikel im Hauptauftrag lässt sich erhöhen oder verringern. Löschen solltest du jedoch nur *nicht zu Lieferaufträgen zugeordnete Mengen*.

[WARNING]
.Löschen von Positionen in einem Lieferauftrag
====
Technisch möglich ist zwar auch das Löschen von Positionen, die bereits in einem Lieferauftrag enthalten sind. Dies solltest du jedoch vermeiden, um Fehlfunktionen zu verhindern.
====

[#create-order-from-existing-order]
=== Auftrag über einen bestehenden Auftrag anlegen

In einem Auftrag findest du das Symbol *Neuer Auftrag* (icon:plus-square[role="green"]) im Portlet *Allgemein*. Gehe folgendermaßen vor, um einen neuen Auftrag in einem bestehenden Auftrag anzulegen.
. Öffne einen Auftrag.
. Im Portlet *Allgemein* hast du die Möglichkeit, einen Auftragstyp zu wählen.
. Wähle *Auftrag* oder *Vorbestellung*. 
// TODO: Was sollte dann passieren? Text auf neue UI anpassen


// TODO: anpassen auf neue UI; Suchfilter Zahlungsstatus?
[#order-type-multi-order]
== Auftragstyp Sammelauftrag (Multi-Order) nutzen

Unbezahlte Aufträge können in einem Sammelauftrag zusammengefasst werden. Du kannst im Menü *Aufträge » Aufträge [Testphase]* oder im *???* eines Kontakts mit dem Suchfilter *Zahlungsstatus*, z.B. anhand eines Status im Bereich *[3] Warten auf Zahlung*, nach solchen unbezahlten Aufträgen suchen. Somit hast du zwei Möglichkeiten, Sammelaufträge zu erzeugen, die nachfolgend beschrieben werden.
Für beide Möglichkeiten übernimmst du im Menü *Aufträge » ?* noch nicht bezahlte Aufträge in einen Sammelauftrag. Im Portlet *?* des Sammelauftrags ist dann das Erzeugen von Sammelrechnungen möglich.

Tab *Sammelaufträge*
+- *Sammelaufträge generieren*
| *Kundenklasse*
|Wähle die Kundenklasse aus der Dropdown-Liste.
Voreinstellt ist *Standard-Kundenklasse*
Zeitraum: Haken setzen
Wenn Zeitraum angehakt ist, von bis eingeben, indem du in das leere Feld klickst. Der Kalender öffnet sich.
Über Icon Zahnrad Pfeil kannst du... (tooltip fehlt)

+- *Sammelgutschriften generieren*
| *Kundenklasse*
|Wähle die Kundenklasse aus der Dropdown-Liste.
Voreinstellt ist *Standard-Kundenklasse*
Zeitraum: Haken setzen
Wenn Zeitraum angehakt ist, von bis eingeben, indem du in das leere Feld klickst. Der Kalender öffnet sich.
Über Icon Zahnrad Pfeil kannst du...


// TODO: alte UI https://knowledge.plentymarkets.com/de-de/manual/main/auftraege/auftraege-verwalten.html#800


[#basic-settings-multi-orders]
=== Grundeinstellungen für Sammelaufträge vornehmen

Im Menü *Einrichtung » Aufträge » Auftragstypen » Multi-Order* nimmst du die Grundeinstellungen für Sammelaufträge vor. Hier legst du beispielsweise fest, für welche Auftragstypen und Auftragsstatus Sammelaufträge angelegt werden können.

[.instruction]
Grundeinstellungen für Sammelaufträge vornehmen:

. Öffne das Menü *Einrichtung » Aufträge » Auftragstypen » Multi-Order*.
. Nimm die Einstellungen gemäß <<table-multi-order-settings>> vor.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[[table-multi-order-settings]]
.Grundeinstellungen für Sammelaufträge
[cols="1,3"]
|====
|Einstellung|Erläuterung

| *Auftragstypen*
|Die Auftragstypen wählen, die für Sammelaufträge verwendbar sein sollen. Eine Mehrfachauswahl ist möglich. Nur die aufgeführten Auftragstypen *Auftrag*, *Gewährleistung* und *Reparatur* sind als Sammelaufträge umsetzbar.

| *Artikeltext*
|Die Optionen für die Spalte *Artikeltext* der Artikelpositionen eines Sammelauftrags wählen. Eine Mehrfachauswahl ist möglich. Die gewählten Optionen werden für jeden Einzelauftrag separat im Sammelauftrag aufgelistet und ermöglichen eine Zuordnung zur Kund:in und zum Einzelauftrag.

| *Auftragssortierung*
|Wählen, wie die einzelnen Aufträge im Sammelauftrag sortiert sein sollen. Nur eine Auswahl ist möglich. Die Aufträge sind anhand der der Auftrags-ID (*Order ID aufsteigend* oder *Order ID absteigend*) oder dem Zeitpunkt des Warenausgangs (*Warenausgang aufsteigend* oder *Warenausgang absteigend*) sortierbar.

| *Auftragsstatus Aufträge*
|Wählen, in welchem Status sich Aufträge befinden müssen, um für Sammelaufträge berücksichtigt zu werden. Eine Mehrfachauswahl ist möglich. Um gezielt nur Aufträge zu erfassen, die für Sammelaufträge vorgesehen sind, empfehlen wir, je nach Anwendungsfall einen eigenen Auftragsstatus anzulegen.

| *Auftragsstatus Gutschriften*
|Wählen, in welchem Status sich xref:auftraege:auftraege-verwalten.adoc#500[Gutschriftaufträge] befinden müssen, um für Sammelgutschriften berücksichtigt zu werden. Eine Mehrfachauswahl ist möglich.
|====

Im Menü *Einrichtung » Aufträge » Einstellungen* kannst du mit der Option xref:auftraege:grundeinstellungen.adoc#intable-default-status-multi-order[Standard-Status Sammelauftrag] festlegen, welchen Auftragsstatus ein Sammelauftrag beim Anlegen erhalten soll. Standardmäßig steht dafür der Status *[13] Sammelauftrag* zur Verfügung. Wähle zudem mit der Option *Standard-Status Sammelgutschrift* einen Status für Sammelgutschriften aus. Standardmäßig steht dafür der Status *[14] Sammelgutschrift* zur Verfügung.

//// 
[#820]
=== Sammelauftrag pro Kundenklasse anlegen

Fallbeispiel: Ein Unternehmen möchte für die Mitarbeiter:innen monatlich die anfallenden Rechnungen in deinem Webshop bezahlen. Richte dafür eine eigene Kundenklasse ein. Mit der Kunden-ID in der vorgesehenen Kundenklasse wird die Rechnungsempfänger:in bestimmt. Diese Rechnungsempfänger:in erhält dann die Sammelrechnung, die direkt aus dem Sammelauftrag heraus erzeugt wird. +

Einen Sammelauftrag für eine bestimmte Kundenklasse sowie einen Zeitraum legst du im Menü *Aufträge » Sammelaufträge* an. Alle unbezahlten Aufträge der Kundenklasse werden somit gesammelt in einem Sammelauftrag abgelegt. Hinterlege in den Einstellungen der Kundenklassen anhand der Option *Kunden-ID*, welche Kund:in für die Kundenklasse als Eigner des Sammelauftrags sowie als Empfänger:in der Sammelrechnung aufgeführt werden soll. Je nach Anforderung empfiehlt es sich, eigene xref:crm:kontakte-verwalten.adoc#15[Kundenklassen] für Sammelaufträge anzulegen.

[.instruction]
Sammelauftrag für eine Kundenklasse anlegen:

. Öffne das Menü *Aufträge » Sammelaufträge*.
. Öffne das Untermenü *Sammelaufträge generieren*.
. Wähle die *Kundenklasse* und optional einen *Zeitraum*. Der Zeitraum bezieht sich auf das Datum des Auftragseingangs.
. Klicke auf icon:execute[set=plenty]. +
→ Der Sammelauftrag wird angelegt.

[#830]
=== Sammelauftrag pro Kontakt anlegen

Eine Kund:in möchte nicht jede Rechnung einzeln bezahlen, sondern pro Monat oder pro Quartal bezahlen. +
In diesem Fall legst du einen Sammelauftrag für einen bestimmten Kontakt direkt im Kontaktdatensatz im Menü *CRM » Kontakte* an. Öffne dazu einen Kontakt und wähle links im Menü die Option *Neuer Sammelauftrag*. Anschließend wird automatisch ein Sammelauftrag generiert, der alle unbezahlten Aufträge des Kontakts enthält.

[TIP]
.Aufträge prüfen
====
Um sicher zu gehen, dass geeignete Aufträge für die Erzeugung eines Sammelauftrags vorhanden sind, suche im Tab *Aufträge* der Kund:in nach unbezahlten Aufträgen.
====

[#840]
=== Sammelrechnung generieren

Die Erstellung von Sammelrechnungen ist nur in den dazugehörigen Sammelaufträgen möglich. Richte zuerst eine xref:auftraege:auftragsdokumente.adoc#[Dokumentenvorlage] für Sammelrechnungen im Menü *Einrichtung » Mandant » [Mandant wählen] » Standorte » [Standort wählen] » Dokumente » Sammelrechnung* ein. In diesem Menü kannst du das Dokument detailliert einstellen sowie eine Dokumentenvorlage in Form einer PDF-Datei hinterlegen. In der Grundeinstellung der Vorlage sind bereits Standardwerte hinterlegt, die du bei Bedarf durch Kopie aus einer anderen Vorlage, z.B. der Dokumentenvorlage *Rechnung*, mit geringem Aufwand weiter vervollständigen kannst.

Anschließend kannst du im Tab *Belege* des Sammelauftrags eine Sammelrechnung generieren. Gehe dafür wie im Folgenden beschrieben vor.

[.instruction]
Sammelrechnung erzeugen:

. Öffne das Menü *Aufträge » Aufträge bearbeiten*. +
→ Die Auftragsübersicht öffnet sich.
. Suche (icon:search[role="blue"]) anhand der Filtereinstellungen den Sammelauftrag, für den eine Sammelrechnung erzeugt werden soll.
. Öffne den Sammelauftrag.
. Wechsle in das Tab *Belege*. +
. Wähle aus der Dropdown-Liste *Beleg erstellen* das Dokument *Sammelrechnung* aus. +
. Nimm die Einstellungen anhand <<table-orders-generate-multi-invoice>> vor. +
. *Speichere* (icon:plus-square[role="green"]) die Einstellungen, um die Sammelrechnung zu erzeugen. +
→ Es öffnet sich eine *PDF-Datei* mit der soeben erzeugten Sammelrechnung.

[[table-orders-generate-multi-invoice]]
.Einstellungen für Sammelrechnungen
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Datum*
|Gib das Datum an, das als Rechnungsdatum auf dem Dokument angezeigt wird. Standardmäßig ist das aktuelle Datum voreingestellt.

|*Nummer*
|Die Nummer des Dokuments wird automatisch vergeben. Hier muss keine Angabe gemacht werden.

|*Rechnungen der Aufträge generieren*
|Mit *JA* oder *NEIN* auswählen, ob die einzelnen Rechnungen zu den im Sammelauftrag enthaltenen Aufträgen ebenfalls generiert werden sollen.

| *Buche Warenausgang*
|Mit *JA* oder *NEIN* auswählen, ob mit dem Erzeugen der Sammelrechnung auch der Warenausgang gebucht werden soll.

| *Ändere Auftragsstatus auf Status*
|Einen Status wählen, in den der Auftrag nach dem Erzeugen der Sammelrechnung wechseln sollen. Wenn kein Statuswechsel gewünscht ist, die Option *Keine Änderung* wählen.

| *Kommentar*
|Einen Text eingeben, der auf der Sammelrechnung unterhalb der Artikelpositionen angezeigt wird. Die Eingabe ist optional.
|====

[IMPORTANT]
.Zahlungseingänge bei Sammelaufträgen
====
Wird eine Sammelrechnung bezahlt und der Sammelauftrag als bezahlt markiert, werden die Zahlungseingänge *nicht* automatisch an den einzelnen im Sammelauftrag zusammengefassten Aufträgen gebucht. Zahlungseingänge musst du an den einzelnen Aufträgen manuell buchen.
====

[.discrete]
==== Sammelrechnung über Ereignisaktion generieren

Mithilfe der in plentymarkets verfügbaren Ereignisaktionen kannst du die Sammelrechnung automatisiert generieren, sobald ein Sammelauftrag angelegt wird. Gehe dazu wie nachfolgend beschrieben vor:

:table-event-procedure: <<table-event-procedure-multi-invoice-automatic>>
include::_includes:page$EA.adoc[]

[[table-event-procedure-multi-invoice-automatic]]
.Ereignisaktion "Sammelrechnung automatisch generieren"
[cols="1,3"]
|====
|Einstellung|Auswahl

| *Ereignis*

| *Auftragsanlage > Neuer Sammelauftrag*

| *Aktion*

| *Dokumente > Sammelrechnung erzeugen* +

|====

[#850]
=== Sammelgutschrift generieren

Eine Sammelgutschrift erzeugst du im Menü *Aufträge » Sammelaufträge*. +
Alle Gutschriften der ausgewählten Kundenklasse werden gesammelt in einer Sammelgutschrift abgelegt. Diese Sammelgutschrift ist wie Sammelaufträge auch nach Erstellung in der Auftragsübersicht bearbeitbar. Je nach Anwendungsfall empfehlen wir, eigene xref:crm:kontakte-verwalten.adoc#15[Kundenklassen] für Sammelgutschriften anzulegen.

[.instruction]
Sammelgutschrift für eine Kundenklasse generieren:

. Öffne das Menü *Aufträge » Sammelaufträge*.
. Öffne das Untermenü *Sammelgutschriften generieren*.
. Wähle die *Kundenklasse* aus.
. Wähle optional einen *Zeitraum*. Der Zeitraum bezieht sich auf das Datum des Gutschrifteingangs.
. Klicke auf icon:execute[set=plenty]. +
→ Die Sammelgutschrift wird angelegt.

[#860]
=== Dokument Sammelgutschrift generieren

Die Erstellung des Dokuments Sammelgutschrift ist nur im dazugehörigen Auftragstyp Sammelgutschrift möglich. Richte zuerst eine Dokumentenvorlage für Sammelgutschriften im Menü *Einrichtung » Mandant » [Mandant wählen] » Standorte » [Standort wählen] » Dokumente » Sammelgutschrift* ein. In diesem Menü kannst du das Dokument detailliert einstellen sowie eine Dokumentenvorlage in Form einer PDF-Datei hinterlegen. In der Grundeinstellung der Vorlage sind bereits Standardwerte hinterlegt, die du bei Bedarf durch Kopie aus einer anderen Vorlage, z.B. der Dokumentenvorlage Gutschrift, mit geringem Aufwand weiter vervollständigen kannst.

Anschließend kannst du im Tab *Belege* der Sammelgutschrift das Dokument Sammelgutschrift generieren. Gehe dafür wie im Folgenden beschrieben vor.

[.instruction]
Dokument Sammelgutschrift erzeugen:

. Öffne das Menü *Aufträge » Aufträge [Testphase]*. +
→ Die Auftragsübersicht öffnet sich.
. Suche (icon:search[role="blue"]) anhand der Filtereinstellungen die Sammelgutschrift, für die ein Dokument Sammelgutschrift erzeugt werden soll.
. Öffne die Sammelgutschrift.
. Wechsle in das Tab *Belege*. +
. Wähle aus der Dropdown-Liste *Beleg erstellen* das Dokument *Sammelgutschrift* aus. +
. Nimm die Einstellungen anhand <<table-orders-generate-document.multi-credit-note>> vor. +
. *Speichere* (icon:plus-square[role="green"]) die Einstellungen, um das Dokument Sammelgutschrift zu erzeugen. +
→ Es öffnet sich eine *PDF-Datei* mit der soeben erzeugten Sammelgutschrift.

[[table-orders-generate-document.multi-credit-note]]
.Einstellungen für Dokument Sammelgutschrift
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Datum*
|Gib das Datum an, das als Gutschriftsdatum auf dem Dokument angezeigt wird. Standardmäßig ist das aktuelle Datum voreingestellt.

|*Nummer*
|Die Nummer des Dokuments wird automatisch vergeben. Hier muss keine Angabe gemacht werden.

| *Buche Warenausgang*
|Mit *JA* oder *NEIN* auswählen, ob mit dem Erzeugen der Sammelgutschrift auch ein Warenausgang gebucht werden soll.

| *Ändere Auftragsstatus auf Status*
|Einen Status wählen, in den der Auftrag nach dem Erzeugen der Sammelgutschrift wechseln sollen. Wenn kein Statuswechsel gewünscht ist, die Option *Keine Änderung* wählen.

| *Kommentar*
|Einen Text eingeben, der auf der Sammelgutschrift unterhalb der Artikelpositionen angezeigt wird. Die Eingabe ist optional.
|====
////