= Auftragsbestätigungen
:page-aliases: dokument-auftragsbestaetigung-erzeugen.adoc
:keywords: Auftragsbestätigung, Auftragsbestätigungen erzeugen, Auftragsdokumente, Dokumentenvorlage, Dokumententyp, Dokument, Dokumentvorlage, Dokumenttyp
:author: team-docs-automation
:description: Erfahre, wie du mithilfe einer Dokumentenvorlage ein Dokument zur Auftragsbestätigung erzeugst. Lerne außerdem, wie du das Erzeugen und Versenden von Auftragsbestätigungen anhand einer Ereignisaktion automatisierst.

Ist ein Auftrag ins System eingegangen, kannst du der Kund:in eine Auftragsbestätigung zukommen lassen. In plentymarkets kannst du Auftragsbestätigungen als PDF-Dateien generieren, um diese z.B. zu drucken oder deinen Kund:innen als E-Mail-Anhang zukommen zu lassen.

[#100]
== Dokumentenvorlage für Auftragsbestätigungen einrichten

Bevor du Auftragsbestätigungen generieren kannst, muss eine Dokumentenvorlage eingerichtet werden. Dies geschieht im Menü *Einrichtung » Mandant » [Mandant wählen] » Standorte » [Standort wählen] » Dokumente » Auftragsbestätigung*. +
Weitere Informationen und Anleitungen zur Einrichtung der Dokumentenvorlage findest du auf der Handbuchseite xref:auftraege:auftragsdokumente-neu.adoc#[Auftragsdokumente].

[#200]
== Einzelne Auftragsbestätigung erzeugen

Auftragsbestätigungen kannst du manuell am jeweiligen Auftrag erzeugen. Gehe dabei wie im Folgenden beschrieben vor.

[.instruction]
Auftragsbestätigung manuell erzeugen:

. Öffne das Menü *Aufträge » Aufträge (Testphase)*. +
→ Die Auftragsübersicht wird geöffnet.
. Führe die Suche (material:search[]) aus, um Aufträge anzuzeigen.
. Öffne den Auftrag, für den eine Auftragsbestätigung erzeugt werden soll.
. Gehe in den Bereich *Dokumente*.
. Klicke oben links auf *Dokument erstellen* (material:add[]).
. Wähle das Dokument *Auftragsbestätigung* aus der Dropdown-Liste. +
→ Das Fenster *Dokument erzeugen: Auftragsbestätigung* wird geöffnet.
. Gib ein Datum ein, das auf der Auftragsbestätigung angezeigt werden soll.
. Gib optional einen Kommentar ein, der auf der Auftragsbestätigung angezeigt werden soll.
. Klicke auf *Erstellen* (material:add[role="green"]). +
→ Die Auftragsbestätigung wird erstellt und im Bereich *Dokumente* hinzugefügt.

[#300]
== Erzeugung und Versand von Auftragsbestätigungen automatisieren

Das Erzeugen und Versenden von Auftragsbestätigungen kannst du automatisieren, indem du die entsprechenden Ereignisaktionen einrichtest. So musst du nicht all deine Auftragseingänge stetig im Blick behalten und jede Auftragsbestätigung einzeln manuell erstellen, sondern kannst deinen Workflow durch die Automatisierung erleichtern. Erstelle zunächst eine Ereignisaktion für die Erzeugung des Dokuments und im zweiten Schritt eine Ereignisaktion, damit die Auftragsbestätigung per E-Mail an die Kund:in versendet wird. Gehe dafür wie im Folgenden beschrieben vor.

:table-event-procedure: <<table-event-procedure-generate-order-confirmation>>
include::_includes:partial$event-procedure.adoc[]

[[table-event-procedure-generate-order-confirmation]]
.Ereignisaktion "Auftragsbestätigung erzeugen" einrichten
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

| *Ereignis*
| *Auftragsanlage » Neuer Auftrag*
|

| *Filter*
| *Auftrag > Auftragstyp*
| *Auftrag*

| *Aktion*
| *Dokumente > Auftragsbestätigung erzeugen*
|Aktiviere bei Bedarf die Optionen *Zahlungsziel* und *Skonto* oder gib einen *Kommentar* ein, der auf der erzeugten Auftragsbestätigung angezeigt wird. +
|====

Möchtest du die Auftragsbestätigung nach Erzeugung direkt als E-Mail-Anhang an deine Kund:in versenden, empfehlen wir die in <<table-event-procedure-send-order-confirmation>> beschriebene Ereignisaktion.

:table-event-procedure: <<table-event-procedure-send-order-confirmation>>
include::_includes:partial$event-procedure.adoc[]

[[table-event-procedure-send-order-confirmation]]
.Ereignisaktion "Auftragsbestätigung versenden" einrichten
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

| *Ereignis*
| *Dokumente > Auftragsbestätigung generiert*
|

| *Filter*
| *Auftrag > Auftragstyp*
| *Auftrag*

| *Aktion*
| *Kunde > E-Mail versenden*
|Wähle über *Hinzufügen* (icon:plus-square[role="green"]) die entsprechende E-Mail-Vorlage für den Versand der Auftragsbestätigung (z.B. "Auftrag: Auftragsbestätigung PDF-Anhang") an die Kund:in.
|====

[TIP]
.Du siehst die passende E-Mail-Vorlage nicht?
====
Du siehst für die Ereignisaktion "Auftragsbestätigung versenden" die passende E-Mail-Vorlage nicht? Dann liegt das daran, dass du sie noch nicht erstellt hast. Dies kannst du im Menü *Einrichtung » Mandant » _Mandant wählen_ » E-Mail » Vorlagen* tun. Klicke dort auf *Neue E-Mail-Vorlage* (icon:plus-square[role="green"]) und erstelle die Vorlage nach deinen Anforderungen. Der Name, den du hier für die E-Mail-Vorlage vergibst, wird dann auch in den Ereignisaktionen ausgegeben. Weitere Informationen zum Einrichten findest du auf der Handbuchseite xref:crm:e-mails-versenden.adoc#1200[E-Mail-Vorlage erstellen].
====
