= Auftragsansicht gestalten

:keywords: MyView, Auftragsansicht gestalten
:author: team-order-core

Auf dieser Handbuchseite erfährst du, wie du die Auftragsübersicht nach deinen Bedürfnissen gestaltest. Mit Hilfe der MyView kannst du beispielsweise entscheiden, welche Splaten für deine Aufträge sichtbar sind und wie diese angeordnet sind.
Die Detailansicht eines Auftrags ändert sich je nach Auftragstyp. Für jeden Typ gibt es somit eine individuelle Übersicht mit den jeweils relevanten Informationen.

[#design-toolbar]
== Toolbar in Auftrags-Detailansicht nutzen
//add screenshot of toolbar

Öffnest du einen Auftrag, stehen dir je nach Auftragstyp verschiedene Funktionen in der Toolbar zur Verfügung.
//Kann die Toolbar auch selbst gestaltet werden? Ab wann möglich?
//Entscheide hier selbst, welche Funktionen du direkt angezeigt bekommen möchtest und welche Funktionen im Kontextmenü (material:more_vert[]) verfügbar sein sollen. Klicke dazu auf *Spalten konfigurieren* und nimm die Einstellungen vor, um für dich wichtige Funktionen einzublenden und weniger relevante Funktionen über das Kontextmenü erreichbar zu machen.

[[table-toolbar-functions]]
.Funktionen in der Toolbar
[cols="2,1,6a"]
|===
|Bedienelement |Symbol |Erläuterung

| *Speichern*
| material:save[]
|Hast du Änderungen in einem Auftrag vorgenommen, wird diese Schaltfläche aktiviert und du kannst deine Änderungen speichern. +
Diese Schaltfläche wird standardmäßig in der Toolbar angezeigt.

| *Aufträge erstellen*
| material:shopping_cart[]
|Ermöglicht das Erstellen von Kindaufträgen für einen Auftrag. Je nach Auftragstyp stehen verschiedene Optionen zur Verfügung. +
Diese Schaltfläche wird standardmäßig in der Toolbar angezeigt. +
Du kannst die folgenden Auftragstypen als Kindaufträge anlegen:

* Auftrag
* Gewährleistung
* Gutschrift
* Lieferauftrag
* Nachbestellung
* Reparatur
* Retoure
* Sammelauftrag
* Sammelgutschrift
* Sammellieferung
* Teillieferung
* Vorbestellung

** Für alle Artikel: Alle Artikel werden jeweils mit der maximal verfügbaren Anzahl automatisch zum Warenkorb hinzugefügt.
** Für bestimmte Artikel: Die Tabelle des Warenkorbs ist zunächst leer, d.h. die gewünschten Artikel müssen manuell hinzugefügt werden.
** Automatisch aufteilen (Nur beim Typ Lieferauftrag): Die Artikel werden je nach Einstellungen automatisch aufgeteilt.

| *Warenausgang buchen*
| material:input[]
|Erlaubt den Warenausgang direkt zu buchen, wodurch der Bestand der Varianten reduziert wird, wenn du Bestand führst. Der Status des Auftrags ändert sich automatisch in Status 7. +
Diese Schaltfläche wird standardmäßig in der Toolbar angezeigt.

//wo verfügbar? Ansonsten rausnehmen
| *Waren zurückbuchen*
| material:input[]
|Bucht die Artikel vollständig oder teilweise zurück. Bei dieser Option wird der Warenausgang nicht zurückgesetzt. +
Diese Schaltfläche wird standardmäßig in der Toolbar angezeigt.

| *E-Mail-Service*
| material:email[]
|Öffnet das Tab *E-Mail-Vorlagen* und ermöglicht es dir, eine E-Mail-Vorlage direkt an die Kund:in zu senden oder bereits gesendete Vorlagen einzusehen. +
Diese Schaltfläche wird standardmäßig in der Toolbar angezeigt.

| *Auftrag teilen*
| material:call_split[]
|Teilt einen Auftrag. +
Diese Funktion ist im Kontextmenü (material:more_vert[]) der Toolbar verfügbar.
//weitere Schritte geteilter Auftrag?

| *Kopieren*
| material:content_copy[]
|Kopiert einen Auftrag. Anschließend wird der kopierte Auftrag in blauer Schrift in der Seitennavigation angezeigt. +
Du kannst einen Auftrag vollständig kopieren, z.B. wenn die Kund:in die gleiche Bestellung noch einmal tätigt oder mehrere Personen die gleiche Bestellung tätigen. +
Diese Funktion ist im Kontextmenü (material:more_vert[]) der Toolbar verfügbar.

| *Lagerorte zuweisen*
| material:warehouse[]
|Weist Lagerorte zu oder löst zugewiesene Lagerorte. +
*Lagerorte zuweisen*: Weist der Auftragsposition einen Lagerort zu. Ist für einen Artikel mehr als ein Lagerort hinterlegt, werden die Lagerorte anhand der Position priorisiert. Wurde kein Lagerort hinterlegt, wird der Standard-Lagerort zugeordnet.
Die Zuordnung des Lagerorts ist für Pick-/Packlisten relevant. +
*_Tipp:_* Lagerorte können Artikeln auch per Ereignisaktion zugeordnet werden. +
*Lagerorte lösen*: Löst zugewiesene Lagerorte von der Auftragsposition. +
Diese Funktion ist im Kontextmenü (material:more_vert[]) der Toolbar verfügbar.

| *Kaufabwicklung*
| material:visibility[]
|Klicke auf material:visibility[], um zum plentyShop LTS weitergeleitet zu werden. Der Auftrag wird dort geöffnet. +
Diese Funktion ist im Kontextmenü (material:more_vert[]) der Toolbar verfügbar.

| *Gutschein einlösen*
| material:card_giftcard[]
|Ermöglicht das manuelle Einlösen von Gutscheinen. Hier wird zwischen plentymarkets Kampagnen und externen Kampagnen unterschieden. Weitere Informationen findest du im Kapitel xref:working-with-orders#redeem-coupon[Gutscheine einlösen]. +
Diese Funktion ist im Kontextmenü (material:more_vert[]) der Toolbar verfügbar.

| *Gesperrt*
| material:lock[]
|Der Auftrag kann nur eingeschränkt bearbeitet werden. Wenn du mit der Maus über die Schaltfläche fährst, werden weitere Informationen zum Sperrstatus angezeigt und wie du den Auftrag entsperren kannst. +
Diese Schaltfläche befindet sich ganz rechts in der Toolbar und wird nur in gesperrten Aufträgen angezeigt.

| *Auftrag löschen*
| material:delete[]
|Klicke rechts oben auf material:delete[] *Auftrag löschen*, um einen Auftrag zu löschen. Bestätige anschließend die Sicherheitsabfrage. +
Beachte, dass nicht alle Aufträge gelöscht werden können. +
Diese Funktion ist im Kontextmenü (material:more_vert[]) der Toolbar verfügbar.
//wann kann ein Auftrag nicht gelöscht werden?
|===

[TIP]
.Seitennavigation ein- und ausblenden
====
Sowohl in der Auftragsübersicht als auch in der Detailansicht eines Auftrags hast du die Möglichkeit, die Seitennavigation ein- und auszuklappen. Klicke dazu oben links auf material:menu[].
====

[#configure-columns]
== Spalten in der Übersicht konfigurieren

Die Tabellenspalten der Auftrags-Übersicht sind für beide Ebenen konfigurierbar. Beim ersten Öffnen des Menüs *Aufträge » Aufträge (Testphase)* wird dir die Standardansicht der Tabelle angezeigt. Mit Klick auf *Spalten konfigurieren* (material:settings[]) rechts öffnet sich das Fenster mit den Optionen *Tabelle Aufträge* und *Tabelle Auftragspositionen*. Im Fenster *Spalten konfigurieren* kannst du jeweils wählen, welche Spalten du sehen möchtest und in welcher Reihenfolge diese angezeigt werden sollen.

[.collapseBox]
.*Spalten konfigurieren*
--
Wenn du die Tabelle einmal angepasst hast, wird diese Auswahl gespeichert. Du kannst das Layout jederzeit ändern. Die zur Verfügung stehenden Spalten findest du in <<table-order-overview>> sowie <<table-order-items>>. Dort ist ebenfalls beschrieben, bei welchen Spalten es sich um Standardspalten handelt. Standardspalten werden angezeigt, wenn die Tabelle nicht konfiguriert ist. Gehe wie im Folgenden beschrieben vor, um die Tabelle anzupassen.

[.instruction]
Spalten konfigurieren:

. Öffne das Menü *Aufträge » Aufträge (Testphase)*.
. Klicke oben rechts auf *Spalten konfigurieren* (material:settings[]).
. Wähle, welche Ebene der Tabelle du konfigurieren möchtest. +
→ Das Fenster *Spalten konfigurieren* wird geöffnet.
. Wähle die Spalten, die angezeigt werden sollen. Beachte dazu die Erläuterungen in <<table-order-overview>> und <<table-order-items>>.
. Verschiebe (material:sort[]) die Spalten so, dass sie in der gewünschten Reihenfolge angezeigt werden.
. Füge bei Bedarf Spalten hinzu oder wähle sie ab, wenn du sie nicht benötigst.
. Klicke auf *Bestätigen*. +
→ Die Einstellungen werden gespeichert.

[TIP]
.Reihenfolge via Drag-and-drop anpassen
====
Du kannst die Reihenfolge der Tabellenspalten per Drag-and-drop mit einem Klick auf material:drag_indicator[] beliebig verändern. Ziehe die Einträge an die gewünschte Stelle und speichere deine Änderungen anschließend.
====

[#table-columns-orders]
=== Tabellenspalten für Aufträge konfigurieren

Folgende Spalten stehen für die *Auftragsübersicht* zur Verfügung:

[[table-order-overview]]
.Auftragsübersicht
[cols="1,3"]
|====
|Einstellung|Erläuterung

|*Ausklappen*
|Ermöglicht das Ausklappen eines Auftrags in der Auftragsübersicht.

|*Auswahl*
|Ermöglicht das Auswählen von Aufträgen, um Funktionen für alle gewählten Aufträge durchzuführen.

| *Sperrstatus*
|Zeigt an, ob der Auftrag gesperrt ist oder nicht. Ein Auftrag wird gesperrt, sobald eine Rechnung erzeugt wurde. Eine Gutschrift wird gesperrt, sobald ein Gutschriftsdokument erzeugt wurde. Du kannst den Auftrag oder die Gutschrift entsperren, wenn du einen Stornobeleg für das jeweilige Dokument erzeugst. +
* (material:lock_open[]) = Nicht gesperrt
* (material:lock[]) =  Gesperrt +
Diese Spalte ist eine Standardspalte.

| *Auftragstyp*
|Der Typ des Auftrags wird angezeigt. +
Diese Spalte ist eine Standardspalte.

| *Auftrags-ID*
|Die ID des Auftrags wird angezeigt.
Diese Spalte ist eine Standardspalte.

| *Kontakt*
|Der Name des Kontakts wird angezeigt. +
Diese Spalte ist eine Standardspalte.

| *Kontakt-ID*
|Die ID des Kontakts, d.h. der Käufer:in, wird angezeigt. +
Damit eine ID angezeigt wird, muss ein Kontaktdatensatz für diese Käufer:in angelegt sein. Handelt es sich um eine Gastbestellung, wird *Gast* angezeigt. Durch Klick auf die Kontakt-ID wird der Kontaktdatensatz geöffnet. +
Dies ist eine Standardspalte.

| *Mandant*
|Der Mandant, über den der Auftrag erstellt wurde, wird angezeigt. +
Diese Spalte ist eine Standardspalte.

| *Mandanten-ID*
|Die ID des Mandanten wird angezeigt. +
Diese Spalte ist eine Standardspalte.

| *Standort*
|Der Standort, zu dem der Mandant gehört, über den der Auftrag erstellt wurde, wird angezeigt. +
Diese Spalte ist eine Standardspalte.

| *Standort-ID*
|Die ID des Standortes, zu dem der Mandant gehört, über den der Auftrag erstellt wurde, wird angezeigt. +
Diese Spalte ist eine Standardspalte.

| *Artikelmenge*
| Zeigt die Artikelmenge aller Artikel im Auftrag an. +
Diese Spalte ist eine Standardspalte.

| *Auftragssumme (netto)*
|Die Nettogesamtsumme des Auftrags wird in der Auftragswährung angezeigt. +
Diese Spalte ist eine Standardspalte.

| *Auftragssumme (brutto)*
|Die Bruttogesamtsumme des Auftrags wird in der Auftragswährung angezeigt. +
Diese Spalte ist eine Standardspalte.

| *USt.*
|Der auf den Auftrag angewendete Umsatzsteuersatz wird angezeigt. +
Diese Spalte ist eine Standardspalte.

| *Status*
|Der Bearbeitungsstatus des Auftrags wird angezeigt. +
Diese Spalte ist eine Standardspalte.

| *Warenausgangsdatum*
|Das Datum, an dem die Waren ausgebucht wurden, wird angezeigt. +
Diese Spalte ist eine Standardspalte.

| *Auftragsdatum*
|Das Datum, an dem der Auftrag ins System kam, wird angezeigt. +
Diese Spalte ist eine Standardspalte.

| *Zahlungsart*
|Die für diesen Auftrag gewählte Zahlungsart wird angezeigt. +
Diese Spalte ist eine Standardspalte.

| *Rechnungsnummer*
|Wurde bereits eine Rechnung für den Auftrag erstellt, wird die Rechnungsnummer angezeigt. +
Diese Spalte ist eine Standardspalte.

| *Zahlungsstatus*
|Der Zahlungsstatus des Auftrags wird angezeigt. +
* Ausstehend = Der vollständige Betrag ist noch offen.
* Vorausbezahlt = Der Betrag oder ein Teilbetrag wurde bereits im Voraus bezahlt.
* Teilbezahlt = Der Betrag wurde teilweise bezahlt.
* Bezahlt = Der Betrag wurde vollständig bezahlt.
* Überbezahlt = Es wurde mehr als der ausstehende Betrag gezahlt. +
Diese Spalte ist eine Standardspalte.

| *Zahlungsdatum*
|Das Datum, an dem die Zahlung für diesen Auftrag eingegangen ist, wird angezeigt. +
Diese Spalte ist eine Standardspalte.

| *Währung*
|Die Währung des Auftrags wird angezeigt. +
Diese Spalte ist eine Standardspalte.

| *Lieferland*
|Das Land, in das dieser Auftrag versendet wird, wird angezeigt. Das angezeigte Lieferland wird der angegebenen Lieferadresse entnommen. +
Diese Spalte ist eine Standardspalte.

| *Lieferdatum*
|Das voraussichtliches Lieferdatum des Auftrags wird angezeigt. +
Diese Spalte ist eine Standardspalte.

| *Quelle*
|Zeigt an, wie der Auftrag erstellt wurde, z.B. manuell oder über Rest. +
Diese Spalte ist eine Standardspalte.

| *Eigner*
| Die Eigner:in des Auftrags wird angezeigt. +
Dies ist eine optionale Spalte.

| *Herkunfts-ID*
| Die ID der Herkunft, über die der Auftrag erstellt wurde, wird angezeigt. Die xref:auftraege:auftragsherkunft.adoc#[Auftragsherkunft] ist der Verkaufskanal, über den ein Auftrag generiert wird. +
Diese Spalte ist eine Standardspalte.

| *Herkunft*
| Die Herkunft des Auftrags wird angezeigt, d.h. *Mandant (Shop)* oder *Manuelle Eingabe*. +
Diese Spalte ist eine Standardspalte.

| *Lager*
|Das Hauptlager des Auftrags wird angezeigt.  +
Diese Spalte ist eine Standardspalte.

| *Lager-ID*
| Die ID des Hauptlagers wird angezeigt. +
Dies ist eine optionale Spalte.

| *Versandkosten*
|Die Versandkosten des Auftrags werden angezeigt. +
Diese Spalte ist eine Standardspalte.

| *Gewicht [kg]*
| Das Gesamtgewicht des Auftrags wird angezeigt. +
Dies ist eine optionale Spalte.

| *Referenz*
| Die ID des referenzierten Auftrags wird angezeigt. Durch Klick auf die ID öffnet sich der referenzierte Auftrag. +
Dies ist eine optionale Spalte.

| *Rechnungsadresse*
|Die Rechnungsadresse wird angezeigt.
Diese Spalte ist eine Standardspalte.

| *Lieferadresse*
|Die Lieferadresse wird angezeigt.
Diese Spalte ist eine Standardspalte.

//IN UI NICHT SICHTBAR
| *Auftragsherkunft*
|Die Auftragsherkunft, über die der Auftrag  erstellt wurde, wird angezeigt. Die xref:auftraege:auftragsherkunft.adoc#[Auftragsherkunft] ist der Verkaufskanal, über den ein Auftrag generiert wird. +
Diese Spalte ist eine Standardspalte.

| *Tags*
|Dem Auftrag zugeordnete Tags werden angezeigt. +
Dies ist eine optionale Spalte.

| *Versandprofil*
|Das Versandprofil wird angezeigt.
Diese Spalte ist eine Standardspalte.

| *Versanddienstleister*
|Der Versanddiensteister wird angezeigt.
Diese Spalte ist eine optionale Spalte.

|*Aktionen*
|Zeigt die weiteren Aktionen (icon) an, die für den jeweiligen Auftrag zur Verfügung stehen.
|====

[#table-columns-order-items]
=== Tabellenspalten für Auftragspositionen konfigurieren

Wenn du die zweite Ebene aufklappst (material:chevron_right[]), werden dir Informationen zu den *Auftragspositionen* angezeigt. Dafür stehen die in der folgenden Tabelle aufgelisteten Spalten zur Verfügung. Beachte, dass Auftragspositionen nicht bearbeitet werden können. +
*_Hinweis:_* Die Auftragspositionen sind nicht für alle Auftragstypen gleich.

[[table-order-items]]
.Auftragspositionen
[cols="1,3"]
|====
|Einstellung|Erläuterung

| *Ausklappen*
|Ermöglicht das Ausklappen weiterer Informationen zu Auftragspositionen und zeigt den *Namen*, den *Wert* sowie den *Aufpreis* an.

| *Menge*
|Die bestellte Menge der Auftragsposition wird angezeigt. +
Diese Spalte ist eine Standardspalte.

| *Artikel-ID*
|Die Artikel-ID der Auftragsposition wird angezeigt. Durch Klick auf die ID wird der Artikel geöffnet. +
Diese Spalte ist eine Standardspalte.

| *Variantennummer*
|Die Variantennummer der Auftragsposition wird angezeigt. +
Diese Spalte ist eine Standardspalte.

| *Variantenname*
|Der Variantenname der Auftragsposition wird angezeigt. +
Diese Spalte ist eine Standardspalte.

| *Varianten-ID*
|Die Varianten-ID der Auftragsposition wird angezeigt. Durch Klick auf die ID wird die Variante geöffnet. +
Diese Spalte ist eine Standardspalte.

| *Artikelname*
|Der Artikelname der Auftragsposition wird angezeigt. +
Dies ist eine optionale Spalte.

| *Attribute*
|Die Attribute der Auftragsposition werden angezeigt. +
Diese Spalte ist eine Standardspalte.

| *Nettopreis*
|Der Nettopreis der Auftragsposition wird angezeigt.  +
Diese Spalte ist eine Standardspalte.

| *Regulärer Nettopreis*
|Der reguläre Nettopreis der Auftragsposition wird angezeigt.  +
Diese Spalte ist eine optionale Spalte.

| *Bruttopreis*
|Der Bruttopreis der Auftragsposition wird angezeigt.  +
Diese Spalte ist eine Standardspalte.

| *Rabatt [%]*
|Der für die Auftragsposition gewährte Rabatt wird angezeigt. +
Diese Spalte ist eine Standardspalte.

| *Aufpreis gesamt*
|Die Summe der Aufpreise der Bestelleigenschaften der Auftragsposition wird angezeigt. +
Diese Spalte ist eine Standardspalte.

| *Gesamtbetrag (netto)*
|Die Nettogesamtsumme der Auftragsposition wird angezeigt. +
Diese Spalte ist eine Standardspalte.

| *Gesamtbetrag (brutto)*
|Die Bruttogesamtsumme der Auftragsposition wird angezeigt. +
Diese Spalte ist eine Standardspalte.

| *Lager*
|Das Lager der Auftragsposition wird angezeigt. +
Diese Spalte ist eine Standardspalte.

| *USt. [%]*
|Der Umsatzsteuersatz der Auftragsposition wird angezeigt. +
Diese Spalte ist eine Standardspalte.

| *Externe Artikel-ID*
|Die externe Artikel-ID wird angezeigt. +
Dies ist eine optionale Spalte.

| *Externe Auftragspositions-ID*
|Die vom Marktplatz übermittelte externe Auftragspositions-ID wird angezeigt. +
Dies ist eine optionale Spalte.

| *Eigenschafts-ID*
|Die Eigenschafts-ID wird angezeigt. +
Dies ist eine optionale Spalte.

| *Lagerorte*
|Die Lagerorte der Auftragsposition werden angezeigt. +
Diese Spalte ist eine ? Spalte.

| *Gewinnspanne (netto)*
|Die Netto-Gewinnspanne der Auftragsposition wird angezeigt. +
Diese Spalte ist eine ? Spalte.

| *Bemerkung*
|Das Feld Bemerkung wird angezeigt. +
*_Hinweis:_* Dieses Datenfeld gibt es für Retoure und Reparatur.

| *Artikelstatus*
|Das Lager der Auftragsposition wird angezeigt. +
Diese Spalte ist eine Standardspalte. +
*_Hinweis:_* Dieses Datenfeld gibt es für Retoure und Reparatur.

| *Nachbestellungs-ID*
|Die ID der Nachbestellung wird angezeigt. Klicke auf die ID, um die Nachbestellung zu öffnen.
|====


[#editing-mode]
== Bearbeitungsmodus verwenden

Der Bearbeitungsmodus bietet dir viel Flexibilität beim Anordnen von Inhalten und Daten im Menü *Aufträge » Aufträge (Tesphase)*. Grundsätzlich platzierst du Elemente intuitiv per Drag-and-drop. Du kannst jedes Element individuell anpassen und weiter bearbeiten. <<#table-functions-editing-mode>> enthält einen Überblick über die Funktionen, die im Bearbeitungsmodus zur Verfügung stehen.

[TIP]
.Hast du Admin-Rechte?
======
Nur xref:business-entscheidungen:benutzerkonten-zugaenge.adoc#[Admin-Nutzer] können Ansichten erstellen und bearbeiten.
Falls du kein Admin bist:

. Wende dich an eine Person mit Admin-Rechten.
. Bitte die Person, die erforderlichen Ansichten zu erstellen und sie für dein Benutzerkonto freizugeben.
======

[[table-functions-editing-mode]]
.Verfügbare Funktionen im Bearbeitungsmodus
[cols="2,1,6"]
|===

|Bedienelement |Symbol |Erläuterung

| *Ansicht bearbeiten*
|icon:design_inline_edit[set=plenty]
| Öffnet die Ansicht zur Bearbeitung. +
Du kannst die Elemente per Drag-and-drop an einer anderen Stelle positionieren und die Größe der Elemente anpassen.

| *Rückgängig*
|icon:undo[set=material]
| Macht die letzte Änderung rückgängig, solange die betreffende Änderung noch nicht gespeichert wurde.

| *Wiederherstellen*
|icon:redo[set=material]
| Stellt eine rückgängig gemachte Änderung wieder her.

| *Standardansicht*
|
| Dieser Bereich zeigt an, welche Ansicht aktuell geöffnet ist. Klicke auf icon:sort-down[role=darkGrey], um zu einer anderen Ansicht zu wechseln oder eine neue Ansicht zu erstellen.

| *Letzten Speicherpunkt wiederherstellen*
|icon:restore[set=material]
| Setzt die Ansicht auf den Stand zurück, der beim letzten Speichern vorhanden war.

| *Speichern*
|icon:save[set=material]
| Speichert die Änderungen. Auf diese Weise kannst du beliebig viele Ansichten nach deinen Wünschen speichern. +
Wenn du das nächste Mal {edit-object} bearbeiten möchtest, kannst du die von dir bevorzugte Ansicht über die Dropdown-Liste oben rechts öffnen. Ebenfalls über diese Dropdown-Liste erstellst du mit einem Klick auf icon:add[set=material] *Neue Ansicht erstellen…* eine neue Ansicht.

| *Bearbeiten*
|icon:edit[set=material]
|Wenn du das Element bearbeitest, siehst du auf der rechten Seite im Bereich *Elemente*, welche Elemente in diesem Bereich noch nicht verwendet wurden und dir somit noch zur Verfügung stehen. Bereits verwendete Elemente sind ausgegraut und können nicht ein weiteres Mal verwendet werden.

| *Löschen*
|icon:delete[set=material]
|Löscht das Element.

| *Schließen*
|icon:close[set=material]
| Beendet den Bearbeitungsmodus. Wenn du die Änderungen nicht gespeichert hast, wird eine Sicherheitsabfrage angezeigt.

|===

[#create-new-view]
=== Neue Ansicht erstellen
Um eine neue Ansicht zu erstellen, gehe vor wie im Folgenden beschrieben.

[.instruction]
Neue Ansicht erstellen:

. Klicke auf die Liste der Ansichten (icon:caret-down[role="darkGrey"]).
. Klicke auf icon:add[set=material] *Neue Ansicht erstellen ...*.
. Gib einen Namen ein.
. Klicke auf *Ansicht erstellen*. +
→ Die neue Ansicht wird erstellt und automatisch geöffnet, d.h. sie wird angewendet.
Es ist jetzt möglich, zwischen den Ansichten zu wechseln.

[#place-elements]
=== Elemente anordnen

Platziere die Elemente intuitiv per Drag-and-drop genau an der Stelle, an der du sie haben möchtest. Passe außerdem die Größe der Elemente an deine Bedürfnisse an. +
Um Elemente hinzuzufügen, gehe vor wie im Folgenden beschrieben.

[.instruction]
Elemente anordnen:

. Öffne das Menü *Aufträge » Aufträge (Testphase)*.
. Öffne die Auftragsansicht, in der du ein Element platzieren möchtest.
. Klicke auf icon:design_inline_edit[set=plenty] *Ansicht bearbeiten*.
. Wähle rechts ein Element und platziere es per Drag-and-drop an der gewünschten Stelle. +
*_Optional:_* Bewege deinen Mauszeiger an den Rand eines Elementes und ziehe das Element mit gedrückter Maustaste in die beliebige Größe. +
*_Tipp:_* Möchtest du deine Elemente später an eine andere Stelle verschieben? Dann kannst du dies jederzeit per Drag-and-drop tun, bis alle Elemente ideal platziert sind.

[#complete-editing]
=== Bearbeitung abschließen

Hast du alle Einstellungen vorgenommen, kannst du deine Änderungen speichern und den Bearbeitungsmodus abschließen. Prüfe im Anschluss, ob die Ansicht nun deinen Vorstellungen entspricht.

[.instruction]
Bearbeitung abschließen:

. Speichere die Ansicht (terra:save[role="darkGrey"]) und schließe den Bearbeitungsmodus (icon:close[role="darkGrey"]).
. Prüfe das Ergebnis im Hauptfenster.
. Falls erforderlich:
.. Klicke noch einmal auf *Ansicht bearbeiten* (terra:design_inline_edit[role="darkGrey"]) und passe die Ansicht weiter an.
.. Erlaube anderen Benutzer:innen, die Ansicht zu sehen.

//evtl. in Konfig umschreiben
[#show-order-items]
== Auftragspositionen ein- und ausblenden

In der Auftragsübersicht werden die Auftragspositionen standardmäßig nicht angezeigt. Möchtest du aber Eigenschaften zu Auftragspositionen, wie *Name* oder *Wert* sehen, klicke in der Zeile des Auftrags links auf das Pfeilsymbol (material:chevron_right[]). Zunächst werden dir die Informationen zum Auftrag, wie *Menge*, *Artikel-ID* oder *Variantennummer* angezeigt. Klicke auf dieser Ebene ein weiteres Mal links auf das Pfeilsymbol (material:chevron_right[]), um die Eigenschaften zu sehen.

*_Hinweis:_* Möchtest du die Eigenschaften der Auftragspositionen bearbeiten, öffne den gewünschten Auftrag und klicke im Bereich *Auftragspositionen* auf *Bearbeiten* (material:edit[]).


[#asterisk-unsaved-changes]
== Ungespeicherte Änderungen erkennen

//add screenshot
Hast du Änderungen an einem Auftrag vorgenommen, erscheint ein Sternchen links in der Seitennavigation. Dieses Sternchen zeigt an, auf welcher Ebene ungespeicherte Änderungen vorhanden sind. Sobald du die Änderungen speicherst (material:save[]) oder die Änderungen auf den vorherigen Stand zurücksetzt, verschwindet das Sternchen wieder.

// Link zur nächsten Seite hier einfügen
