= Vorbereitende Einstellungen vornehmen
:keywords: DocumentBuilder vorbereitende Einstellungen vornehmen, DocumentBuilder Rechte vergeben, DokumentBuilder prerequisites, DocumentBuilder Voraussetzungen, DocumentBuilder Nummernkreise
:author: team-docs-automation
:description: Erfahre, welche vorbereitende Einstellungen du vornehmen musst, bevor du mit dem DocumentBuilder arbeiten kannst.

Bevor du mit dem DocumentBuilder arbeiten kannst, ist ein wenig Vorarbeit nötig. In den folgenden Unterkapiteln erfährst du, wie du die notwendigen Rechte für Mitarbeiter:innen vergibst, und wie du Nummernkreise für Dokumenttypen festlegst.

[#benutzerrechte-vergeben]
== Rechte vergeben

:rights-purpose: pass:quotes[mit dem DocumentBuilder arbeiten können]
:right-one: pass:quotes[*Dokumente > DocumentBuilder > Lesen*]
:right-two: pass:quotes[*Dokumente > DocumentBuilder > Aktualisieren*]
:right-four: pass:quotes[*Dokumente > DocumentBuilder > Erstellen*]
:right-five: pass:quotes[*Dokumente > DocumentBuilder > Löschen*]

include::_includes:partial$rights.adoc[]

[#nummernkreise-festlegen]
== Nummernkreise für Dokumenttypen festlegen


Mithilfe der Nummernkreise im Menü *Einrichtung » Dokumente » Nummernkreise* legst du fortlaufende Nummern für die verschiedenen Dokumenttypen an. Diese Nummern ermöglichen es dir, die später generierten Dokumente eindeutig zu identifizieren und zu verfolgen. 
Eine ausführliche Anleitung dazu findest du auf der Handbuchseite xref:auftraege:nummernkreise-festlegen.adoc#[Nummernkreise festlegen].


