= Vorbereitende Einstellungen vornehmen
:keywords: DocumentBuilder vorbereitende Einstellungen vornehmen, document builder, DokumentBuilder, Dokument Builder, Dokumente erstellen, Auftragsdokumente erstellen, 
:author: team-docs-automation
:description: Erfahre, wie du anhand des DocumentBuilders Vorlagen für verschiedene Dokumente erstellst und nach deinen Wünschen gestaltest.

Bevor du mit dem DocumentBuilder arbeiten kannst, ist ein wenig Vorarbeit nötig. In den folgenden Unterkapiteln erfährst du, wie du die notwendigen Rechte für Mitarbeiter:innen vergibst, und wie du Nummernkreise für Dokumenttypen festlegst.

[#benutzerrechte-vergeben]
== Rechte für Backendbenutzer:innen vergeben

:rights-purpose: pass:quotes[mit dem DocumentBuilder arbeiten können]
:right-one: pass:quotes[*Dokumente > DocumentBuilder > Lesen*]
:right-two: pass:quotes[*Dokumente > DocumentBuilder > Aktualisieren*]
:right-four: pass:quotes[*Dokumente > DocumentBuilder > Erstellen*]
:right-five: pass:quotes[*Dokumente > DocumentBuilder > Löschen*]

include::_includes:partial$rights.adoc[]

[#nummernkreise-festlegen]
== Nummernkreise für Dokumenttypen festlegen


Mithilfe der Nummernkreise (*Einrichtung » Dokumente » Nummernkreise*) legst du fortlaufende Nummern für die verschiedenen Dokumenttypen an. Diese Nummern ermöglichen es dir, die später generierten Dokumente eindeutig zu identifizieren und zu verfolgen. 
Eine ausführliche Anleitung dazu findest du auf der Handbuchseite xref:auftraege:nummernkreise-festlegen.adoc#[Nummernkreise festlegen].


