= Standardvorlagen verwenden
:keywords: DocumentBuilder Standardvorlagen, Standard vorlagen, standard template, Standardvorlage löschen, Standardvorlage deaktivieren, Standardvorlage nutzen, 
:author: team-docs-automation
:description: Erfahre, was Standardvorlagen sind und wie du sie verwendest.

////
TODO: Keywords ändern; description ergänzen; Seiten einkopieren
////


Für Dokumente mit Steuerrelevanz sowie für Lieferscheine stehen im DocumentBuilder Standardvorlagen zur Verfügung. Die Standardvorlagen sind standardmäßig aktiviert und dienen als *“Fallback”*. Das bedeutet: Falls für den jeweiligen Auftrag keine andere Vorlage verfügbar ist, greift das System auf die Standardvorlage zurück. 

*Standardvorlagen kannst du nicht bearbeiten, löschen oder einzeln deaktivierten/aktivieren*. Wenn du die Standardvorlagen gesammelt deaktivieren/aktivieren möchtest, nutze die Umschaltfläche in der DocumentBuilder-Übersicht. + 
*_Hinweis:_* Wenn du alle Standardvorlagen deaktivierst, dienen sie nicht mehr als Fallback.


Eine Standardvorlage kannst du <<#standardvorlagen-direkt-verwenden, direkt verwenden>> oder sie xref:auftraege:documentbuilder-vorlage-erstellen.adoc#vorlage-kopieren[duplizieren] und die Kopie nach deinen Wünschen anpassen.

Für folgende Dokumenttypen enthält der DocumentBuilder Standardvorlagen: 

* Rechnung
* Lieferschein
* Mahnung
* Korrekturbeleg
* Auftragsbestätigung
* Stornobeleg Rechnung
* Stornobeleg Gutschrift
* Stornobeleg Mahnung

Für jede Standardvorlage gibt es vier Versionen: deutsch und englisch; brutto und netto.



[#standardvorlagen-direkt-verwenden]
== Standardvorlagen direkt verwenden 

Die Standardvorlagen im DocumentBuilder sind standardmäßig aktiviert und mit allen Pflichtangaben für den jeweiligen Dokumenttyp vorkonfiguriert. Um sie direkt zu verwenden, musst du nichts weiter tun. 

*_Hinweis:_* Wenn du dich für die direkte Verwendung entscheidest, beachte, dass in der Systemhierarchie Standardvorlagen deinen eigenen Vorlagen unterstellt sind. Das bedeutet: Sobald eine aktive eigene Vorlage vorhanden ist, die für die gleichen Auftragsparameter wie eine Standardvorlage eingestellt ist, wird die Standardvorlage nicht mehr verwendet. 

[#standardvorlage-kopieren]
== Standardvorlage kopieren

Die Standardvorlagen im DocumentBuilder bieten eine gute Basis für das Erstellen neuer Vorlagen, die du an deine Bedürfnisse anpassen kannst.

Um zu erfahren, wie du im DocumentBuilder eine Vorlage kopierst, um daraus eine neue, editierbare Vorlage zu erstellen, wechsele zunächst auf die Handbuchseite xref:auftraege:documentbuilder-vorlage-erstellen.adoc#[Neue Vorlage erstellen].
Dort findest du ausführliche Informationen zum Erstellen, Kopieren und Einstellen von Vorlagen.

