= Standardvorlagen verwenden
:keywords: DocumentBuilder vorbereitende Einstellungen vornehmen, document builder, DokumentBuilder, Dokument Builder, Dokumente erstellen, Auftragsdokumente erstellen, 
:author: team-docs-automation
:description: Erfahre, wie du .

////
TODO: Keywords ändern; description ergänzen; Seiten einkopieren
////



[#Standardvorlagen]
== Standardvorlagen

Standardvorlagen stehen für Aufträge zur Verfügung, für die systemtechnisch zwingend ein Dokument generiert werden muss. Hier dienen sie als *“Fallback”*. D.h.: Falls für den jeweiligen Auftrag keine andere Vorlage verfügbar ist, greift das System auf die Standardvorlage zurück. Aus diesem Grund können *Standardvorlagen nicht bearbeitet, deaktiviert oder gelöscht werden*.

Eine Standardvorlage kannst du *direkt verwenden* oder sie duplizieren und die Kopie *nach deinen Wünschen anpassen*.

Für folgende Dokumenttypen enthält der DocumentBuilder Standardvorlagen: 

* Rechnung
* Lieferschein
* Mahnung
* Korrekturbeleg
* Stornobeleg Rechnung
* Stornobeleg Gutschrift
* Stornobeleg Mahnung

Für jede Standardvorlage gibt es vier Versionen: deutsch und englisch; brutto und netto.

[#Standardvorlagen direkt verwenden]
=== Standardvorlagen direkt verwenden 

Die Standardvorlagen sind bereits vorformatiert und mit allen Pflichtangaben für den jeweiligen Dokumenttyp vorkonfiguriert. *Um sie direkt zu verwenden, musst du nichts weiter tun*. Wenn du dich für die direkte Verwendung entscheidest, beachte folgenden Punkt: 

* In der Systemhierarchie sind Standardvorlagen deinen eigenen Vorlagen unterstellt. D.h.: Sobald eine aktive eigene Vorlage vorhanden ist, die für die gleichen Auftragsparameter wie eine Standardvorlage eingestellt ist (über Dokumenttyp und Auftragseinstellungen), wird die Standardvorlage nicht mehr verwendet.

[#Neue Vorlage aus Standardvorlage erstellen]
=== Neue Vorlage aus Standardvorlage erstellen

Gehe wie folgt vor um im DokumentBuilder eine Standardvorlage zu duplizieren und aus der Kopie eine neue Vorlage zu erstellen, die du nach deinen Wünschen anpassen kannst:

[.instruction]

. Öffne das Menü *Einrichtung » Dokumente » DocumentBuilder*. +
→ Die Übersicht des DocumentBuilders wird geöffnet.
. Führe die Suche (material:search[]) aus, um Dokumentvorlagen anzuzeigen.
. Klicke rechts in der Zeile der Vorlage, die du kopieren möchtest auf das Kontextmenü (material:more_vert[]).
. Klicke auf material:file_copy[] *Vorlage kopieren*. +
→ Die Vorlage wird kopiert und direkt geöffnet. +
*_Hinweis:_* Die neue Vorlage erhält denselben Namen mit dem Zusatz "Kopie" am Ende. Kopierte Vorlagen sind standardmäßig deaktiviert.
. Passe für die Vorlage die Einstellungen an. Beachte dazu die Erläuterungen in Kapitel
xref:auftraege:documentbuilder-vorlage-erstellen.adoc#Einstellungen-in-Vorlage-vornehmen[Einstellungen in einer Vorlage vornehmen].
. Gestalte für die Vorlage die Struktur und den Inhalt. Beachte dazu die Erläuterungen im Themenbereich xref:auftraege:documentbuilder-vorlagenstrukur-gestalten[Vorlagenstruktur im Editor gestalten].

