= Dokumentenarchiv (Testphase)

:keywords: Dokumente, Dokument, Archiv, Dokumentenarchiv, Sammeldokument, Sammeldokumente, Auftragsdokumente, Dokumentenexport, Gutscheinexport, archiviert, archiviertes Dokument, Dokument archivieren, Rechnung archivieren
:description: Erfahre auf dieser Handbuchseite, wie du archivierte Dokumente finden und herunterladen kannst.
:author: team-automation-docs

Das neue Dokumentenarchiv im Menü unter *Daten » Dokumentenarchiv (Testphase)* befindet sich zurzeit in der Testphase und wird das xref:auftraege:dokumentenarchiv.adoc[bisherige Dokumentenarchiv] bald ablösen.

Im Dokumentenarchiv kannst du dir bereits generierte PDF-Dokumente einzeln anzeigen lassen oder Sammeldokumente im ZIP-Format generieren. In diesem Archiv werden PDF-Dokumente abgelegt, die in deinem plentymarkets System im Rahmen der Auftragsabwicklung, beim Kassenverkauf mit POS oder im Bereich Warenwirtschaft erzeugt wurden. +
Folgende Dokumenttypen sind im Dokumentenarchiv verfügbar:

//MÖGLICHKEIT, PDF-DOKUMENTE ZUSAMMENZUFÜHREN SPÄTER ERGÄNZEN

[.row]
====
[.col-md-4]
.In plentymarkets erzeugte Auftragsdokumente
=====
* xref:auftraege:abhollieferung-erzeugen.adoc#[Abhollieferung]
* xref:auftraege:dokument-angebot-erzeugen.adoc#[Angebote]
* xref:auftraege:auftragsbestaetigung-erzeugen.adoc#[Auftragsbestätigungen]
* *Externe Gutschriften*
* *Externe Rechnungen*
* xref:auftraege:gelangensbestaetigung-erzeugen.adoc#[Gelangensbestätigungen]
* xref:auftraege:gutschriften-erzeugen.adoc#[Gutschriften]
* xref:auftraege:korrekturbeleg-erzeugen.adoc#[Korrekturbelege]
* xref:auftraege:lieferscheine-erzeugen.adoc#[Lieferscheine]
* xref:auftraege:mahnungen-erzeugen.adoc#[Mahnungen]
* xref:warenwirtschaft:nachbestellungen-vornehmen.adoc#140[Nachbestellung]
* xref:warenwirtschaft:umbuchungen-vornehmen.adoc#800[PO Lieferscheine]
* xref:auftraege:proformarechnung-erzeugen.adoc#[Proformarechnungen]
* xref:auftraege:rechnungen-erzeugen.adoc#[Rechnungen]
* xref:auftraege:reparaturschein-erzeugen.adoc#[Reparaturscheine]
* xref:auftraege:ruecksendeschein-erzeugen.adoc#[Rücksendescheine]
* xref:auftraege:auftraege-verwalten.adoc#850[Sammelgutschriften]
* xref:auftraege:auftraege-verwalten.adoc#840[Sammelrechnungen]
* xref:auftraege:auftraege-verwalten.adoc#530[Stornobeleg Gutschriften]
* xref:auftraege:mahnungen-erzeugen.adoc#400[Stornobeleg Mahnungen]
* xref:auftraege:rechnungen-erzeugen.adoc#400[Stornobeleg Rechnungen]
=====

[.col-md-4]
.POS-Dokumente
=====
* xref:pos:pos-einrichten.adoc#1000[Kassenbeleg]
* xref:pos:pos-kassenbenutzer.adoc#210[Kassengutscheinbeleg]
* xref:pos:pos-einrichten.adoc#400[Kassenjournal]
* xref:pos:pos-kassenbenutzer.adoc#210[Kassenrechnung]
* xref:pos:pos-kassenbenutzer.adoc#210[Kassenstornierung]
* xref:pos:pos-kassenbenutzer.adoc#210[Kassenstornorechnung]
* xref:pos:pos-kassenbenutzer.adoc#450[Kassensturz]
* xref:pos:pos-kassenbenutzer.adoc#230[Tagesabschlussbericht/Z-Report]
=====

[.col-md-4]
.Sonstige Dokumente
=====
* *Abrechnungsbericht*
* xref:payment:bankdaten-verwalten.adoc#70[EBICS INI-Brief]
* *Exportdokument*
* *Externes Dokument*
* xref:auftraege:gutscheine.adoc#[Gutscheine]
* *Retourenetikett*
* xref:payment:bankdaten-verwalten.adoc#220[SEPA-Lastschriftmandat]
* *Versandetikett*
=====
====

[#customise-overview]
== Spalten in der Übersicht konfigurieren

Die Tabellenspalten in der Übersicht des Dokumentenarchivs sind konfigurierbar. Beim ersten Öffnen des Menüs *Daten » Dokumentenarchiv (Testphase)* wird dir die Standardansicht der Tabelle angezeigt. Mit Klick auf *Spalten konfigurieren* (material:settings[]) kannst du wählen, welche Spalten du sehen möchtest und in welcher Reihenfolge diese angezeigt werden sollen.

[.collapseBox]
.*Spalten konfigurieren*
--
Wenn du die Tabelle einmal angepasst hast, wird diese Auswahl gespeichert. Du kannst das Layout jederzeit ändern. Die zur Verfügung stehenden Spalten findest du in <<table-document-archive>>. Dort ist ebenfalls beschrieben, bei welchen Spalten es sich um Standardspalten handelt. Standardspalten werden angezeigt, wenn die Tabelle nicht konfiguriert ist. Gehe wie im Folgenden beschrieben vor, um die Tabelle anzupassen.

[.instruction]
Spalten konfigurieren:

. Öffne das Menü *Daten » Dokumentenarchiv (Testphase)*.
. Klicke oben rechts auf *Spalten konfigurieren* (material:settings[]). +
→ Das Fenster *Spalten konfigurieren* wird geöffnet.
. Wähle die Spalten, die angezeigt werden sollen (material:done[]). Beachte dazu die Erläuterungen in <<table-document-archive>>.
. Ziehe (material:drag_indicator[]) die Spalten per Drag-and-drop an die gewünschte Stelle, bis sie in der für dich richtigen Reihenfolge angezeigt werden.
. Füge bei Bedarf Spalten hinzu oder wähle Spalten ab, wenn du sie nicht benötigst.
. Klicke auf *Bestätigen*. +
→ Die Einstellungen werden gespeichert.
--

Die folgenden Spalten stehen für die Übersicht des Dokumentenarchivs zur Verfügung.

[[table-document-archive]]
.Übersicht des Dokumentenarchivs
[cols="1,3"]
|===
|Einstellung |Erläuterung

| *Dokumentname*
|Zeigt den Namen des Dokuments an. Mit Klick auf den Dokumentnamen wird die Vorschau des Dokuments geöffnet. +
Dies ist eine Standardspalte.

| *Dokumenttyp*
|Zeigt den Typ des Dokuments an. +
Dies ist eine Standardspalte.

| *Dokumentnummer*
|Zeigt die Nummer des Dokuments an. +
Dies ist eine Standardspalte.

| *Auftrags-ID*
|Zeigt die ID des Auftrags an, aus dem das Dokument stammt. Mit Klick auf die Auftrags-ID wird der Auftrag geöffnet. +
Dies ist eine Standardspalte.

| *Eigner*
|Zeigt den Eigner des Dokuments an. +
Dies ist eine Standardspalte.

| *Kontakt-ID*
|Zeigt die ID des Kontakts an, zu dem das Dokument gehört. Mit Klick auf die ID wird der Kontakt geöffnet. +
Dies ist eine Standardspalte.

| *Mandant*
|Zeigt den Mandant an, zu dem das Dokument gehört. +
Dies ist eine Standardspalte.

| *Anzeigedatum*
|Zeigt das Datum an, das auf dem Dokument ausgegeben wird. +
Dies ist eine Standardspalte.

| *Erstellungsdatum*
|Zeigt das Datum an, an dem das Dokument erstellt wurde. +
Dies ist eine Standardspalte.

| *Letzte Änderung*
|Zeigt das Datum an, an dem zuletzt eine Änderung an dem Dokument vorgenommen wurde. +
Diese Spalte wird standardmäßig nicht angezeigt.

| *Stornobeleg*
|Zeigt den Stornobeleg des Dokuments an, falls dieser existiert. +
Diese Spalte wird standardmäßig nicht angezeigt.

|===

[TIP]
.Seitennavigation ein- oder ausblenden
======
Im Dokumentenarchiv hast du die Möglichkeit, die Seitennavigation ein- oder auszuklappen. Klicke dazu oben links auf material:menu[].
======

[#search-for-documents]
== Archivierte PDF-Dokumente suchen

Verwende eine der folgenden Möglichkeiten, um nach archivierten Dokumenten zu suchen.

[.instruction]
Nach Dokumenten suchen:

. Öffne das Menü *Daten » Dokumentenarchiv (Testphase)*.
.. *_Möglichkeit 1:_* Klicke auf material:search[], um direkt eine Liste aller Dokumente zu sehen.
.. *_Möglichkeit 2:_* Gib etwas in das Suchfeld ein und klicke auf einen der automatischen Vorschläge.
.. *_Möglichkeit 3:_* Klicke auf material:tune[], um die Suchergebnisse mit Hilfe von Filtern einzugrenzen.

[#use-filters]
=== Filter verwenden

Um im Dokumentenarchiv noch gezielter nach Dokumenten zu suchen, stehen dir die folgenden Filter zur Verfügung.

[[table-filters-document-archive]]
.Filter für archivierte Dokumente
[cols="1,3"]
|===
|Einstellung |Erläuterung

| *Dokumentnummer mit Präfix*
|Filtert nach Dokumenten mit dieser Dokumentnummer.

| *Auftrags-ID*
|Filtert nach Dokumenten mit dieser Auftrags-ID.

| *Kontakt-ID*
|Filtert nach Dokumenten mit dieser Kontakt-ID.

| *Dokumenttyp*
|Filtert nach Dokumenten dieses Typs.

| *Mandant*
|Filtert nach Dokumenten dieses Mandanten.

| *Erstellungsdatum von*
|Filtert nach Dokumenten, die ab diesem Datum erstellt wurden.

| *Erstellungsdatum bis*
|Filtert nach Dokumenten, die bis zu diesem Datum erstellt wurden.

| *Anzeigedatum von*
|Filtert nach Dokumenten ab diesem Anzeigedatum.

| *Anzeigedatum bis*
|Filtert nach Dokumenten bis zu diesem Anzeigedatum.

|===

[TIP]
.Filtereinstellungen zurücksetzen
======
In den Filtereinstellungen kannst du mit Klick auf material:replay[] alle aktuellen Filtereinstellungen zurücksetzen.
======

[#save-search-settings]
=== Sucheinstellungen speichern

Wenn du eine Suche ausführst, werden deine gewählten Sucheinstellungen oben als Chips dargestellt.
Diese Sucheinstellungen kannst du speichern, um sie in Zukunft schneller und einfacher wieder verwenden zu können.

[#save-current-filter]
==== Aktuellen Filter speichern

. Führe eine Suche aus.
. Klicke auf *Gespeicherte Filter* (material:bookmarks[role=darkGrey]).
. Klicke auf material:bookmark_border[role=darkGrey] *Aktuellen Filter speichern*.
. Gib einen Namen ein und schalte die optionalen Einstellungen bei Bedarf ein (material:toggle_on[role=skyBlue]).
. Klicke auf *Speichern*. +
→ Die Filtereinstellungen erscheinen nun unter *Gespeicherte Filter* (material:bookmarks[role=darkGrey]).

[#use-saved-filters]
==== Gespeicherte Filter anwenden

. Klicke auf *Gespeicherte Filter* (material:bookmarks[role=darkGrey]).
. Klicke auf eine bereits erstellte Filtereinstellung. +
→ Die Suche wird ausgeführt und die verwendeten Sucheinstellungen werden oben als Chips dargestellt.

[TIP]
.Dokumentenvorschau, Auftrag oder Kontakt öffnen
======
Mit Klick auf den Dokumentname, die Auftrags-ID oder die Kontakt-ID kannst du jeweils die Vorschau des Dokuments, den Auftrag oder den Kontakt öffnen.
======

[#download-documents]
== Dokumente herunterladen

Dokumente können entweder einzeln oder gesammelt als ZIP-Datei heruntergeladen werden. Gehe wie im Folgenden beschrieben vor, um Dokumente herunterzuladen.

//WEITERE GRUPPENFUNKTION SPÄTER HINZUFÜGEN (DOKUMENTE ALS PDF ZUSAMMENFÜHREN)

[#download-single-documents]
=== Einzelne Dokumente herunterladen

. Öffne das Menü *Daten » Dokumentenarchiv (Testphase)*.
. Führe die Suche (material:search[]) aus, um archivierte Dokumente anzuzeigen.
. Klicke rechts in der Zeile des gewünschten Dokuments auf *Herunterladen* (material:file_download[]). +
→ Das Dokument wird heruntergeladen.

[#download-as-zip-file]
=== Dokumente gesammelt als ZIP-Datei herunterladen

. Öffne das Menü *Daten » Dokumentenarchiv (Testphase)*.
. Führe die Suche (material:search[]) aus, um archivierte Dokumente anzuzeigen.
. Setze links für die Dokumente ein Häkchen (material:check_box[role=skyBlue]), die du gesammelt herunterladen möchtest.
. Klicke anschließend oben auf die Gruppenfunktion *Dokumente als ZIP-Datei herunterladen* (material:file_download[]). +
→ Alle gewählten Dokumente werden gesammelt als ZIP-Datei heruntergeladen.
