= Gelangensbestätigungen
:keywords: Gelangensbestätigung, Gelangensbestätigungen erzeugen, Auftragsdokumente, Auslandslieferung, Buchhaltung, Dokumentenvorlage, Dokumentvorlage, Dokumenttyp, Dokumententyp,
:author: team-docs-automation
:description: Eine Gelangensbestätigung bestätigt den Erhalt von Ware im EU-Ausland. Erfahre auf dieser Seite, wie du Gelangensbestätigungen als PDF-Datei generierst, druckst und deinen Kund:innen per E-Mail zuschickst.

In plentymarkets kannst du Gelangensbestätigungen als PDF-Dateien generieren, um diese z.B. zu drucken oder deinen Kund:innen als E-Mail-Anhang zukommen zu lassen. +
Bei Lieferungen von Deutschland in ein anderes EU-Land ist die Ausstellung von Gelangensbestätigungen vorgeschrieben. Empfänger:innen bestätigen beispielsweise mittels Unterschrift auf der Gelangensbestätigung und die anschließende Rückübermittlung den erfolgten Wareneingang im jeweiligen EU-Land. +
Somit ist die Gelangensbestätigung nicht nur ein Begleitdokument bei Auslandslieferungen, sondern auch ein steuerrechtlich relevanter Beleg für deine Buchhaltung.

[#100]
== Dokumentenvorlage für Gelangensbestätigungen einrichten

Bevor du Gelangensbestätigungen generieren kannst, muss eine Dokumentenvorlage eingerichtet werden. Dies geschieht im Menü *Einrichtung » Mandant » [Mandant wählen] » Standorte » [Standort wählen] » Dokumente » Gelangensbestätigung*. +
Weitere Informationen und Anleitungen zur Einrichtung der Dokumentenvorlage findest du auf der Handbuchseite xref:auftraege:auftragsdokumente-neu.adoc#[Auftragsdokumente].

[#200]
== Einzelne Gelangensbestätigung erzeugen

Eine einzelne Gelangensbestätigung kannst du in plentymarkets bei Bedarf manuell am Auftrag erzeugen.

[.instruction]
Einzelne Gelangensbestätigung erzeugen:

. Öffne das Menü *Aufträge » Aufträge (Testphase)*. +
→ Die Auftragsübersicht wird geöffnet.
. Führe die Suche (material:search[]) aus, um Aufträge anzuzeigen.
. Öffne den Auftrag, für den eine Gelangensbestätigung erzeugt werden soll. Beachte, dass Aufträge nur in der Listenansicht geöffnet werden können.
. Gehe in den Bereich *Dokumente*.
. Klicke oben links auf *Dokument erstellen* (material:add[]).
. Wähle das Dokument *Gelangensbestätigung* aus der Dropdown-Liste. +
→ Das Fenster *Dokument erzeugen: Gelangensbestätigung* wird geöffnet.
. Gib ein Datum ein, das auf der Gelangensbestätigung angezeigt werden soll.
. Gib optional einen Kommentar ein, der auf der Gelangensbestätigung angezeigt werden soll.
. Klicke auf *Erstellen* (material:add[role="green"]). +
→ Die Gelangensbestätigung wird erstellt und im Bereich *Dokumente* hinzugefügt.

[#300]
== Mehrere Gelangensbestätigungen erzeugen

Sollen mehrere Gelangensbestätigungen zugleich erzeugt werden, kannst du über einen Suchfilter im Menü *Aufträge » Fulfillment* bestimmen, welche Aufträge berücksichtigt werden. Zudem kannst du in diesem Menü festlegen, ob der Status des Auftrags geändert werden soll, nachdem die Gelangensbestätigungen erzeugt wurden.

[.instruction]
Mehrere Gelangensbestätigungen erzeugen:

. Öffne das Menü *Aufträge » Fulfillment*.
. Klicke auf das kleine Plus in der Zeile *Gelangensbestätigung erzeugen*.
. Nimm die Einstellungen anhand <<table-settings-fulfillment-entry-certificate>> vor. +
_Beachte_, dass die Einstellungen sowohl *Suchfilter* als auch *Aktionen* umfassen.
. Klicke auf das *Zahnrad* (icon:cog[]), um die Gelangensbestätigungen zu erzeugen. +
→ Eine *PDF-Datei* wird geöffnet, in der die zugehörigen Gelangensbestätigungen aller von dir durch die Suchfilter bestimmten Aufträge enthalten sind.

[[table-settings-fulfillment-entry-certificate]]
.Optionen im Menü *Gelangensbestätigung erzeugen*
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+^| *Suchfilter*

| *Auftragsstatus*
|Wähle den Status der Aufträge aus der Dropdown-Liste, die für die Erstellung der Gelangensbestätigungen berücksichtigt werden sollen.

| *Eigner*
|Wähle einen Eigner aus der Dropdown-Liste, für dessen Aufträge die Gelangensbestätigungen erzeugt werden sollen oder wähle die Option *ALLE*, wenn für alle Eigner Gelangensbestätigungen erzeugt werden sollen.

| *Standort*
|Wähle einen Standort aus der Dropdown-Liste, für den die Gelangensbestätigungen erzeugt werden sollen.

| *Lager*
|Wähle ein Lager aus der Dropdown-Liste, für das die Gelangensbestätigungen erzeugt werden sollen oder wähle die Option *ALLE*, wenn Gelangensbestätigungen für alle Lager erzeugt werden sollen.

| *Zahlungsart*
|Wähle eine Zahlungsart aus der Dropdown-Liste, für die die Gelangensbestätigungen erzeugt werden sollen oder wähle die Option *ALLE*, wenn für alle Zahlungsarten Gelangensbestätigungen erzeugt werden sollen.

| *Sortierung*
|Lege fest, wie die erzeugten Gelangensbestätigungen sortiert werden sollen. Die Optionen *Auftrags-ID*, *Kunden-ID* und *Artikel-ID* geben verschiedene Sortierungen aus.

| *Limit*
|Lege fest, wie viele Gelangensbestätigungen maximal pro Durchgang erzeugt werden sollen. Das Maximum liegt bei *200*.

2+^| *Aktion*

| *Ändere Auftragsstatus*
|Wähle einen Status, in den die Aufträge nach Erzeugung der Gelangensbestätigunen wechseln sollen. +
Der Statuswechsel ist wichtig, damit für bereits bearbeitete Aufträge ein Prozess nicht noch einmal durchgeführt wird.

| *Kommentar*
|Gib optional einen Kommentar ein, der auf allen erzeugten Gelangensbestätigungen unterhalb der Artikelpositionen angezeigt werden soll.
|====
