= Gutschriften
:keywords: Gutschrift, Gutschriften erzeugen, Gutschriftsbeleg, Gutschriftsdokument, Korrekturbeleg, Dokument, Auftragsdokument, Dokumentenvorlage, Dokumententyp, Dokumentvorlage, Dokumenttyp,
:author: team-docs-automation
:description: Erfahre, wie du eine Dokumentenvorlage für Gutschriften einrichtest, Gutschriften erzeugst und deinen Kund:innnen zuschickst.

In plentymarkets kannst du Gutschriften als PDF-Dateien generieren, um diese z.B. zu drucken oder deinen Kund:innen als E-Mail Anhang zukommen zu lassen. +
Gutschriften nutzt du beispielsweise, um bei bereits bezahlten Aufträgen nachträgliche Preisnachlässe zu gewähren oder wenn im Rahmen von Retouren Rückerstattungen veranlasst werden sollen.

[TIP]
.Standardeinstellungen für Gutschriften
====
Nimm im Menü *Einrichtung » Aufträge » Einstellungen* einmalig die gewünschten Standardeinstellungen zu Gutschriften vor und speichere diese ab. Nur so werden die Einstellungen zum Standard-Status von Gutschriften und zur Übernahme der Versandkosten in Gutschriften wirksam. Weitere Informationen zu den Grundeinstellungen für Aufträge findest du auf der Handbuchseite zum Thema xref:auftraege:preparatory-settings.adoc#[Grundeinstellungen].
====

[#200]
== Dokumentenvorlage für Gutschriften einrichten

Bevor du Gutschriften generieren kannst, muss eine Dokumentenvorlage eingerichtet werden. Dies geschieht im Menü *Einrichtung » Mandant » [Mandant wählen] » Standorte » [Standort wählen] » Dokumente » Gutschrift*. +
Weitere Informationen und Anleitungen zur Einrichtung der Dokumentenvorlage findest du auf der Handbuchseite xref:auftraege:auftragsdokumente-neu.adoc#[Auftragsdokumente].

[#300]
== Einzelne Gutschrift erzeugen

Einzelne Gutschriften kannst du bei Bedarf manuell am jeweiligen Gutschriftauftrag erzeugen. Weitere Informationen und Anleitungen zum Anlegen von Gutschriftaufträgen findest du auf der Seite xref:auftraege:order-type-credit-note.adoc#[Auftragstyp Gutschrift].

[.instruction]
Einzelne Gutschrift erzeugen:

. Öffne das Menü *Aufträge » Aufträge*. +
→ Die Auftragsübersicht wird geöffnet.
. Führe die Suche (material:search[]) aus, um Aufträge anzuzeigen.
. Öffne den Auftrag vom Typ Gutschrift, für den eine Gutschrift erzeugt werden soll. Beachte, dass Aufträge nur in der Listenansicht geöffnet werden können.
. Gehe in den Bereich *Dokumente*.
. Klicke oben links auf *Dokument erstellen* (material:add[]).
. Wähle das Dokument *Gutschrift* aus der Dropdown-Liste. +
→ Das Fenster *Dokument erzeugen: Gutschrift* wird geöffnet.
. Gib ein Datum ein, das auf der Gutschrift angezeigt werden soll.
. Gib optional einen Kommentar ein, der auf der Gutschrift angezeigt werden soll.
. Klicke auf *Erstellen* (material:add[role="green"]). +
→ Die Gutschrift wird erstellt und im Bereich *Dokumente* hinzugefügt.

*_Tipp:_* In der Spalte *Referenz* wird die dazugehörige Rechnung angezeigt.

[#400]
== Mehrere Gutschriften erzeugen

Sollen mehrere Gutschriften zugleich erzeugt werden, kannst du über einen Suchfilter im Menü *Aufträge » Fulfillment* festlegen, welche Aufträge berücksichtigt werden. Zudem kannst du in diesem Menü festlegen, ob der Status des Auftrags geändert werden soll, nachdem die Dokumente erzeugt wurden.

[.instruction]
Mehrere Gutschriften erzeugen:

. Öffne das Menü *Aufträge » Fulfillment*.
. Klicke auf das kleine Plus in der Zeile *Gutschriften / Korrekturbelege erzeugen*.
. Nimm die Einstellungen anhand <<table-settings-fulfillment-credit-notes>> vor. +
_Beachte_, dass die Einstellungen sowohl *Suchfilter* als auch *Aktionen* umfassen.
. Klicke auf das *Zahnrad* (icon:cog[]), um die Gutschriften zu erzeugen. +
→ Eine *PDF-Datei* wird geöffnet, in der die zugehörigen Gutschriften aller von dir durch die Suchfilter bestimmten Aufträge enthalten sind.

[[table-settings-fulfillment-credit-notes]]
.Optionen im Menü *Gutschriften / Korrekturbelege erzeugen*
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+^| *Suchfilter*

| *Dokumenttyp*
|Wähle den Dokumenttyp *Gutschrift* aus der Dropdown-Liste.

| *Auftragsstatus*
|Wähle den Status der Aufträge aus der Dropdown-Liste, die für die Erstellung der Gutschriften berücksichtigt werden sollen.

| *Eigner*
|Wähle einen Eigner aus der Dropdown-Liste, für dessen Aufträge die Gutschriften erzeugt werden sollen oder wähle die Option *ALLE*, wenn für alle Eigner Gutschriften erzeugt werden sollen.

| *Standort*
|Wähle einen Standort aus der Dropdown-Liste, für den die Gutschriften erzeugt werden sollen.

| *Lager*
|Wähle ein Lager aus der Dropdown-Liste, für das Gutschriften erzeugt werden sollen oder wähle die Option *ALLE*, um Gutschriften für alle Lager zu erzeugen.

| *Zahlungsart*
|Wähle eine Zahlungsart aus der Dropdown-Liste, für die Gutschriften erzeugt werden sollen oder wähle die Option *ALLE*, um Gutschriften für alle Zahlungsarten zu erzeugen.

| *Sortierung*
|Lege fest, wie die erzeugten Gutschriften sortiert werden sollen. Die Optionen *Gutschriftnummer*, *Auftrags-ID*, *Kunden-ID* und *Artikel-ID* geben verschiedene Sortierungen aus.

| *Limit*
|Lege fest, wie viele Gutschriften maximal pro Durchgang erzeugt werden sollen. Das Maximum liegt bei *200*.

2+^| *Aktion*

| *Ändere Auftragsstatus*
|Wähle einen Status aus der Dropdown-Liste, in den die Gutschriftaufträge nach Erzeugung der Gutschriften wechseln sollen. +
Der Statuswechsel ist wichtig, damit für bereits bearbeitete Aufträge ein Prozess nicht noch einmal durchgeführt wird.

| *Kommentar*
|Gib optional einen Kommentar ein, der später auf allen erzeugten Gutschriften unterhalb der Artikelpositionen angezeigt werden soll.
|====
