= Korrekturbelege
:page-aliases: dokument-korrekturbeleg-erzeugen.adoc
:keywords: Korrekturbeleg, Korrekturbeleg erzeugen, Korrektur, Korrektur-Beleg, Auftragsdokumente, Dokumentenvorlage, Dokumententyp, Dokument, Gutschrift, Gutschriftauftrag, Dokumentvorlage, Dokumenttyp,
:author: team-docs-automation
:description: Um bestehende Aufträge zu korrigieren, kann für den Auftragstyp Gutschrift ein Korrekturbeleg estellt werden. Erfahre hier, wie du eine Dokumentenvorlage für Korrekturbelege einrichtest und Korrekturbelege erzeugst.

Einen Korrekturbeleg nutzt du, wenn eine Korrektur für einen Auftrag notwendig ist. Stell dir zum Beispiel vor, du kannst einer Kund:in nur zwei von drei bestellten Artikelpositionen zusenden. Du teilst dies deiner Kund:in mit und diese entscheidet sich für eine Rückerstattung des Geldes für den fehlenden Artikel. Wie geht es nun weiter? Du legst zu diesem Auftrag einen xref:auftraege:order-type-credit-note.adoc#[Auftragstyp Gutschrift] an, damit der Vorgang technisch im System abgebildet ist. Erst dann ist es möglich, in diesem Auftragstyp Gutschrift einen Korrekturbeleg zu erstellen. Du kannst entweder einen einzelnen Korrekturbeleg oder mehrere Korrekturbelege auf einmal erzeugen. Erstelle anschließend PDF-Dateien, um diese z.B. zu drucken oder deinen Kund:innen als E-Mail-Anhang zukommen zu lassen.

[#100]
== Dokumentenvorlage für Korrekturbelege einrichten

Bevor du Korrekturbelege generieren kannst, muss eine Dokumentenvorlage eingerichtet werden. Dies geschieht im Menü *Einrichtung » Mandant » [Mandant wählen] » Standorte » [Standort wählen] » Dokumente » Korrekturbeleg*. +
Weitere Informationen und Anleitungen zur Einrichtung der Dokumentenvorlage findest du auf der Handbuchseite xref:auftraege:auftragsdokumente-neu.adoc#[Auftragsdokumente].

[#200]
== Einzelnen Korrekturbeleg erzeugen

Korrekturbelege können nur für den Auftragstyp *Gutschrift* erzeugt werden. Um einen einzelnen Korrekturbeleg manuell aus einem bestimmten Gutschriftauftrag zu erzeugen, gehe wie im Folgenden beschrieben vor.

[.instruction]
Einzelnen Korrekturbeleg erzeugen:

. Öffne das Menü *Aufträge » Aufträge*. +
→ Die Auftragsübersicht wird geöffnet.
. Führe die Suche (material:search[]) aus, um Aufträge anzuzeigen.
. Öffne den Auftrag vom Typ Gutschrift, für den ein Korrekturbeleg erzeugt werden soll. Beachte, dass Aufträge nur in der Listenansicht geöffnet werden können.
. Gehe in den Bereich *Dokumente*.
. Klicke oben links auf *Dokument erstellen* (material:add[]).
. Wähle das Dokument *Korrekturbeleg* aus der Dropdown-Liste. +
→ Das Fenster *Dokument erzeugen: Korrekturbeleg* wird geöffnet.
. Gib ein Datum ein, das auf dem Korrekturbeleg angezeigt wird.
. Gib optional einen Kommentar ein, der auf dem Korrekturbeleg angezeigt wird.
. Klicke auf *Erstellen* (material:add[role="green"]). +
→ Der Korrekturbeleg wird erstellt und im Bereich *Dokumente* hinzugefügt.

[#300]
== Mehrere Korrekturbelege erzeugen

Sollen mehrere Korrekturbelege zugleich erzeugt werden, legst du über Suchfilter im Menü *Aufträge » Fulfillment* fest, welche Gutschriftaufträge berücksichtigt werden. Zudem kannst du in diesem Menü bestimmen, ob der Status des Gutschriftauftrags geändert werden soll, nachdem die Korrekturbelege erzeugt wurden.

[.instruction]
Mehrere Korrekturbelege erzeugen:

. Öffne das Menü *Aufträge » Fulfillment*
. Klicke auf das kleine Plus in der Zeile *Gutschriften / Korrekturbelege erzeugen*.
. Nimm die Einstellungen anhand <<table-settings-fulfillment-adjustment-forms>> vor. +
_Beachte_, dass die Einstellungen sowohl *Suchfilter* als auch *Aktionen* umfassen.
. Klicke auf das *Zahnrad* (icon:cog[]), um den Korrekturbeleg zu erzeugen. +
→ Eine *PDF-Datei* wird geöffnet, in der die zugehörigen Korrekturbelege aller von dir durch die Suchfilter bestimmten Gutschriftaufträge enthalten sind.

[[table-settings-fulfillment-adjustment-forms]]
.Optionen im Untermenü *Gutschriften / Korrekturbelege erzeugen*
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+^| *Suchfilter*

|*Dokumenttyp*
|Wähle den Dokumenttyp *Korrekturbeleg* aus der Dropdown-Liste.

| *Auftragsstatus*
|Wähle den Status der Gutschriftaufträge aus der Dropdown-Liste, die für die Korrekturbelege berücksichtigt werden sollen.

| *Eigner*
|Wähle einen Eigner aus der Dropdown-Liste, für dessen Aufträge die Korrekturbelege erzeugt werden sollen oder die Option *ALLE*, wenn für alle Eigner die Korrekturbelege erzeugt werden sollen.

| *Standort*
|Wähle einen Standort aus der Dropdown-Liste, für den die Korrekturbelege erzeugt werden sollen.

| *Lager*
|Wähle ein Lager aus der Dropdown-Liste, für das die Korrekturbelege erzeugt werden sollen. Wähle alternativ die Option *ALLE*.

| *Zahlungsart*
|Wähle eine Zahlungsart aus der Dropdown-Liste, für die Korrekturbelege erzeugt werden sollen. Wähle alternativ die Option *ALLE*.

| *Sortierung*
|Lege fest, wie die erzeugten Korrekturbelege sortiert werden sollen. Die Optionen *Gutschriftennummer*, *Auftrags-ID*, *Kunden-ID* und *Artikel-ID* geben verschiedene Sortierungen aus.

| *Limit*
|Lege fest, wie viele Korrekturbelege maximal pro Durchgang erzeugt werden sollen. Das Maximum liegt bei *200*.

2+^| *Aktion*

| *Ändere Auftragsstatus*
|Wähle einen Status, in den die Gutschriftaufträge nach Erzeugung der Korrekturbelege wechseln sollen. +
Der Statuswechsel ist wichtig, damit für bereits bearbeitete Aufträge ein Prozess nicht noch einmal durchgeführt wird.

| *Kommentar*
|Gib optional einen Kommentar ein, der auf den Korrekturbelegen unterhalb der Artikelpositionen angezeigt wird.
|====
