= Mahnungen
:keywords: Mahnung, Mahnungen erzeugen, Dokument, Auftragsdokument, Dokumentenvorlage, Dokumentvorlage, Dokumenttyp, Dokumententyp, Mahngebühr, Mahnlevel, Mahnungslevel, Stornobeleg Mahnung, Storno Mahnung, Mahnungsstorno, Mahnungs-Storno
:author: team-docs-automation
:description: Erfahre, wie du eine Dokumentenvorlage für Mahnungen einrichtest, um Mahnungen zu erzeugen und an deine Kund:innen zu senden. Mahnungen kannst du nutzen, um deine Kund:innen an ausstehende Zahlungen zu erinnern, wenn die Zahlungsfrist bereits abgelaufen ist. Lerne außerdem, wie du einen Stornobeleg Mahnung erstellst, um Mahnungen zu stornieren.

In plentymarkets kannst du Mahnungen als PDF-Dateien generieren, um diese z.B. zu drucken oder deinen Kund:innen als E-Mail Anhang zukommen zu lassen. +
Eine Mahnung verwendest du nach Ablauf der Zahlungsfrist, um deine Kund:innen an die ausstehende Zahlung zu erinnern. Sie kann nur erstellt werden, wenn für den Auftrag bereits eine Rechnung existiert, da diese beiden Dokumententypen in Abhängigkeit zueinander stehen. Daher ist es auch nur möglich, eine Rechnung zu stornieren, wenn du vorher eventuell bestehende Mahnungen stornierst. Dafür gibt es einen eigenen Dokumententyp, den <<#400, Stornobeleg Mahnung>>. +
Es stehen dir 4 Mahnstufen zur Verfügung. Du hast also die Möglichkeit, Kund:innen mehrmals zur Zahlung aufzufordern und für jede Aufforderung eine neue Mahnung mit jeweils anderen Mahngebühren zu erstellen. Lege daher für jede Mahnstufe Mahngebühren fest, die du vorher als Varianten-ID angelegt hast. Diese Varianten-ID fügst du dann bei der Erstellung des Dokumentes als Wert ein, wie in <<table-orders-receipts-dunning-letter>> beschrieben. +
Diese Funktionen folgen steuerrechtlichen Vorgaben und helfen dir somit, GoBD-konform zu arbeiten.

[NOTE]
.Mahnstufen dienen lediglich als Markierung
====
Wenn du eine Mahnstufe zu einem Auftrag hinzufügst, dient diese lediglich als Markierung. Diese ist somit nicht mit der Generierung einer Mahnung verknüpft.
====

[#100]
== Dokumentenvorlage für Mahnungen einrichten

Bevor du Mahnungen generieren kannst, muss eine Dokumentenvorlage eingerichtet werden. Dies geschieht im Menü *Einrichtung » Mandant » [Mandant wählen] » Standorte » [Standort wählen] » Dokumente » Mahnung*. +
Weitere Informationen und Anleitungen zur Einrichtung der Dokumentenvorlage findest du auf der Handbuchseite xref:auftraege:auftragsdokumente-neu.adoc#[Auftragsdokumente].

[#200]
== Einzelne Mahnung erzeugen

Eine einzelne Mahnung kannst du in plentymarkets bei Bedarf manuell direkt am Auftrag erzeugen.

[.instruction]
Einzelne Mahnung erzeugen:

. Öffne das Menü *Aufträge » Aufträge (Testphase)*.
→ Die Auftragsübersicht wird geöffnet.
. Führe die Suche (material:search[]) aus, um Aufträge anzuzeigen.
. Öffne den Auftrag, für den eine Mahnung erzeugt werden soll.
. Gehe in den Bereich *Dokumente*.
. Klicke oben links auf *Dokument erstellen* (material:add[]).
. Wähle das Dokument *Mahnung* aus der Dropdown-Liste. +
→ Das Fenster *Dokument erzeugen: Mahnung* wird geöffnet.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<table-create-dunning-letter>>.
. Klicke auf *Erstellen* (material:add[role="green"]). +
→ Die Mahnung wird erstellt und im Bereich *Dokumente* hinzugefügt.

[[table-create-dunning-letter]]
.Einstellungen Dokument Mahnung
[cols="1,3"]
|===
|Einstellung |Erläuterung

| *Datum*
|Gib ein Datum ein, das auf der Mahnung angezeigt werden soll. Das aktuelle Datum ist standardmäßig vorausgewählt.

| *Varianten-ID für Mahngebühr*
|Eine *Mahngebühr* musst du als eigenständigen Artikel mit einem Preis anlegen. Dieser Artikel wird dann als separater Posten auf der Mahnung angezeigt und gibt die Mahngebühr aus. Wenn du den Artikel angelegt hast, kannst du die entsprechende ID der Hauptvariante hier eintragen. Diese wird dann automatisch allen generierten Mahnungen hinzugefügt. +
Mehr Informationen und Anleitungen zum Erstellen von Artikeln findest du auf der Handbuchseite xref:artikel:neue-artikel.adoc#[Artikel manuell anlegen].

| *Kommentar*
|Gib optional einen Kommentar ein, der auf der Mahnung unterhalb der Artikelpositionen angezeigt werden soll.

|===

[#300]
== Mehrere Mahnungen erzeugen

Sollen mehrere Mahnungen zugleich erzeugt werden, kannst du über einen Suchfilter im Menü *Aufträge » Fulfillment* festlegen, welche Aufträge berücksichtigt werden. Zudem kannst du in diesem Menü festlegen, ob der Status des Auftrags geändert werden soll, nachdem die Mahnungen erzeugt wurden.

[.instruction]
Mehrere Mahnungen erzeugen:

. Öffne das Menü *Aufträge » Fulfillment*.
. Klicke auf das kleine Plus in der Zeile *Mahnungen erzeugen*.
. Nimm die Einstellungen anhand <<table-settings-fulfilment-dunning-letters>> vor. +
_Beachte_, dass die Einstellungen sowohl *Suchfilter* als auch *Aktionen* umfassen.
. Klicke auf das *Zahnrad* (icon:cog[]), um die Mahnungen zu erzeugen. +
→ Eine *PDF-Datei* wird geöffnet, in der die zugehörigen Mahnungen aller von dir durch die Suchfilter bestimmten Aufträge enthalten sind.

[[table-settings-fulfilment-dunning-letters]]
.Optionen im Menü *Mahnungen erzeugen*
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+^| *Suchfilter*

| *Auftragsdatum von ... bis*
|Begrenze die zu mahnenden Aufträge durch Auswahl eines Anfangs- und Enddatums aus den Kalendern. Es werden die Aufträge gefunden, die im gewählten Zeitraum eingegangen sind.

| *Auftragsstatus*
|Wähle einen Status für die Aufträge aus der Dropdown-Liste, die für das Erzeugen der Mahnungen berücksichtigt werden sollen.

| *Land*
|Wähle ein Land aus der Dropdown-Liste, auf das die Suche beschränkt werden soll oder wähle die Option *ALLE*, um Mahnungen für alle Länder zu erzeugen.

| *Eigner*
|Wähle einen Eigner aus der Dropdown-Liste, für dessen Aufträge die Mahnungen erzeugt werden sollen oder wähle die Option *ALLE*, wenn für alle Eigner Mahnungen erzeugt werden sollen.

| *Standort*
|Wähle einen Standort aus der Dropdown-Liste, für den die Mahnungen erzeugt werden sollen.

| *Lager*
|Wähle ein Lager aus der Dropdown-Liste, für das die Mahnungen erzeugt werden sollen oder wähle die Option *ALLE*, wenn Mahnungen für alle Lager erzeugt werden sollen.

| *Zahlungsart*
|Wähle eine Zahlungsart aus der Dropdown-Liste, für die die Mahnungen erzeugt werden sollen oder wähle die Option *ALLE*, wenn Mahnungen für alle Zahlungsarten erzeugt werden sollen.

| *Sortierung*
|Lege fest, wie die erzeugten Mahnungen sortiert werden sollen. Die Optionen *Auftrags-ID* und *Kunden-ID* geben verschiedene Sortierungen aus.

2+^| *Aktion*

| *Ändere Auftragsstatus*
|Wähle einen Status, in den die Aufträge nach Erzeugung der Mahnungen wechseln sollen. +
Der Statuswechsel ist wichtig, damit für bereits bearbeitete Aufträge ein Prozess nicht noch einmal durchgeführt wird.

| *Varianten-ID*
|Eine *Mahngebühr* musst du als eigenständigen Artikel mit einem Preis anlegen. Dieser Artikel wird dann als separater Posten auf der Mahnung angezeigt und gibt die Mahngebühr aus. Wenn du den Artikel angelegt hast, kannst du die ID der Hauptvariante des Artikels hier eintragen. Diese wird dann automatisch allen generierten Mahnungen hinzugefügt. +
Mehr Informationen und Anleitungen zum Erstellen von Artikeln findest du auf der Handbuchseite xref:artikel:neue-artikel.adoc#[Artikel manuell anlegen].

| *Kommentar*
|Gib optional einen Kommentar ein, der auf allen Mahnungen unterhalb der Artikelpositionen angezeigt werden soll.
|====

[#400]
== Stornobeleg Mahnung erstellen

Einen *Stornobeleg Mahnung* nutzt du, um eine Mahnung zu stornieren. Dies kann z.B. vorkommen, wenn du eine Rechnung stornieren willst und bereits eine oder mehrere Mahnungen existieren. In diesem Fall müssen erst die Mahnungen storniert werden, bevor die Rechnung storniert werden kann.

Wie bei anderen Dokumententypen auch, muss zunächst eine Dokumentenvorlage eingerichtet werden. Dies geschieht im Menü *Einrichtung » Mandant » _Mandant wählen_ » Standorte » _Standort wählen_ » Dokumente » Stornobeleg Mahnung*. Weitere Informationen und Anleitungen zur Einrichtung der Dokumentenvorlage findest du auf der Handbuchseite xref:auftraege:auftragsdokumente-neu.adoc#[Auftragsdokumente].

Nach Einrichtung der Dokumentenvorlage können die Stornobelege Mahnung direkt am Auftrag erstellt werden. Gehe dabei wie im Folgenden beschrieben vor.

[.instruction]
Stornobeleg Mahnung erstellen:

. Öffne das Menü *Aufträge » Aufträge (Testphase)*.
→ Die Auftragsübersicht wird geöffnet.
. Führe die Suche (material:search[]) aus, um Aufträge anzuzeigen.
. Öffne den Auftrag, für den ein *Stornobeleg Mahnung* erzeugt werden soll.
. Gehe in den Bereich *Dokumente*.
. Klicke oben links auf *Dokument erstellen* (material:add[]).
. Wähle das Dokument *Stornobeleg Mahnung* aus der Dropdown-Liste. +
→ Das Fenster *Dokument erzeugen: Stornobeleg Mahnung* wird geöffnet.
. Gib ein Datum ein, das auf dem Stornobeleg Mahnung angezeigt werden soll.
. Gib optional einen Kommentar ein, der auf dem Stornobeleg Mahnung unterhalb der Artikelpositionen angezeigt werden soll.
. Klicke auf *Erstellen* (material:add[role="green"]). +
→ Die Mahnung wird erstellt und im Bereich *Dokumente* hinzugefügt.
