= Aufträge manuell anlegen
:keywords: Aufträge manuell anlegen, Aufträge über Kontakt anlegen, manuelle Auftragsanlage
:author: team-order-core

//adjust links to new pages where possible (auftragsdokumente once this has been moved)

Anders als du vielleicht vermutest, werden Aufträge nicht direkt im Menü *Aufträge » Aufträge (Testphase)* angelegt. Wie du Aufträge im System anlegst, z.B. wenn eine Bestellung per Telefon getätigt wird, ist auf dieser Seite beschrieben. Die folgenden Möglichkeiten stehen dir für die Auftragsanlage in plentymarkets zur Verfügung:

* In der <<#create-order-in-contact-overview, Kontaktübersicht>>
* In den <<#create-order-via-contact, Kontaktdaten>>
* In einem bestehenden <<#create-order-via-existing-order, Auftrag>>
* Über einen <<#create-order-via-cash-sale, Barverkauf>>

Diese verschiedenen Vorgehensweisen werden nachfolgend beschrieben.

[IMPORTANT]
.E-Mail-Versand
====
Bei manuell angelegten Aufträgen wird keine automatische E-Mail, z.B. als Auftragsbestätigung, an Kund:innen versendet. Grund dafür ist, dass das System nicht wissen kann, wann die Einstellungen zu diesem Auftrag vorgenommen wurden. Stoße daher den Versand einer xref:crm:emailbuilder.adoc#[E-Mail-Vorlage] manuell im Auftrag über die Funktion *E-Mail-Service* an.
====

[#create-order-via-contact]
== Auftrag über den Kontakt anlegen

Im Menü *CRM » Kontakte* legst du einen neuen Auftrag wie unten beschrieben über die Kontaktdaten an.

[.instruction]
Auftrag über Kontakt anlegen:

//ggf. noch anpassen, wohin man genau gelangt, wenn man auf aufträge > neuer auftrag beta klickt (neue UI)

. Öffne das Menü *CRM » Kontakte*.
. Suche den Kontakt anhand der Filtereinstellungen. Beachte dazu die Erläuterungen zu den Filtern auf der Seite xref:crm:kontakt-suchen.adoc#[Kontakt suchen]. +
→ Die Kontakte, die den Suchkriterien entsprechen, werden angezeigt.
. Klicke rechts in der Zeile des Kontakts auf die weiteren Optionen (material:more_vert[]). +
→ Eine Auswahl der verfügbaren Optionen wird geöffnet.
. Wähle die Option material:shopping_cart[] *Aufträge* > *Neuer Auftrag [Beta]*. +
→ Die Übersicht zur Anlage eines neuen Auftrags wird geöffnet.
. Wähle die Artikel und die entsprechenden Mengen, die du zum Auftrag hinzufügen möchtest.
. *Speichere* (material:save[]) die Einstellungen. +
→ Der Auftrag wird angelegt.

[#create-order-via-existing-order]
== Auftrag über einen bestehenden Auftrag anlegen

Dank der Verknüpfung zwischen der Auftrags-UI und der Kontakt-UI kannst du mit nur wenigen Klicks einen neuen Auftrag über einen bestehenden Auftrag anlegen. Gehe wie unten beschrieben vor, um einen neuen Auftrag anzulegen.

[.instruction]
Auftrag über einen bestehenden Auftrag anlegen:

. Öffne das Menü *Aufträge » Aufträge (Testphase)*.
. Führe die Suche (material:search[]) aus, um Aufträge anzuzeigen.
. Öffne den Auftrag der Kund:in, für die du einen neuen Auftrag anlegen möchtest.
. Klicke unten in der Seitennavigation auf die *Kontakt-ID*. +
→ Der Auftrag wird im Menü *CRM » Kontakte* geöffnet.
. Gehe in den Bereich *Aufträge*.
. Klicke rechts auf *Optionen* (material:add[]).
. Wähle die Option *Neuer Auftrag*. +
→ Die Übersicht zum Erstellen eines neuen Auftrags wird geöffnet.
. Wähle die Artikel und die Mengen, die du zum Auftrag hinzufügen möchtest.
. *Speichere* (material:save[]) die Einstellungen. +
→ Der Auftrag wird angelegt.

[#create-order-via-cash-sale]
== Auftrag über Barverkauf anlegen

Im Menü *CRM » Kontakte* hast du die Möglichkeit, Barverkäufe über das Kundenprofil *Barverkauf* abzuwickeln. Das Kundenprofil *Barverkauf* erlaubt dir, Aufträge ohne Kundenzuordnung anzulegen. Das Kundenprofil *Barverkauf* ist in deinem System standardmäßig eingerichtet.

[WARNING]
.Zahlungsart und Auftragsdokumente bei Barverkäufen
====
Achte darauf, bei der Auftragsanlage über Barverkauf in den *Auftragsdaten* die passende *Zahlungsart* auszuwählen. Zudem findet bei dieser Art der Auftragsanlage keine Zuordnung zu einem in deinem System gespeicherten Kund:innen statt. Generiere deshalb die benötigten xref:auftraege:auftragsdokumente.adoc#[Auftragsdokumente], wie die Rechnung, direkt während der Abwicklung des Barverkaufs manuell im Bereich *Dokumente* des Auftrags.
====

[.instruction]
Neuen Auftrag über Barverkauf anlegen:

. Öffne das Menü *CRM » Kontakte*.
. Gib im Suchfeld *ID* die gewünschte ID ein. +
→ Eine Liste der Suchergebnisse wird eingeblendet.
. Wähle *Barverkauf* aus der *Ergebnisliste*. +
→ Das Kundenprofil für Barverkäufe mit der gesuchten ID wird geöffnet.
. Klicke auf *Neuer Auftrag*, um einen neuen Auftrag für einen Barverkauf anzulegen. +
→ Die Übersicht zum Anlegen eines neuen Auftrags wird geöffnet.
. Wähle die Artikel und die entsprechenden Mengen, die du zum Auftrag hinzufügen möchtest.
. *Speichere* (material:save[]) die Einstellungen. +
→ Der Auftrag wird angelegt.

[#create-order-in-contact-overview]
== beta: Auftrag oder Angebot aus der Kontaktübersicht anlegen

Dieses Kapitel beschreibt das Anlegen von Aufträgen oder Angeboten über die Kontaktübersicht im Menü *CRM » Kontakte*.

[#carrying-out-standard-settings]
=== Standardeinstellungen vornehmen

Beim Anlegen von Aufträgen und Angeboten über die Kontaktübersicht werden Daten, wie zum Beispiel Adressen oder Mandanten, direkt aus dem Kontakt übernommen, wenn sie dort hinterlegt sind. Die Kontaktdaten haben in der Regel also Priorität. Zusätzlich stehen dir einige Standardeinstellungen zur Verfügung, auf die zurückgegriffen wird, wenn eine Information nicht aus dem Kontakt genommen wird. +
Um die Auftragsanlage zu erleichtern und schneller vorgehen zu können, solltest du zunächst diese Standardeinstellungen festlegen. +
*_Hinweis:_* Die Standardeinstellungen gelten auch für Angebote, die über die Kontakt-UI angelegt sind.

[.instruction]
Standardeinstellungen vornehmen:

. Öffne das Menü *Einrichtung » Aufträge » Auftragstypen » Auftrag [Beta]*.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<table-default-settings-order-contact>>.
. *Speichere* (material:save[role="green"]) die Einstellungen.

[[table-default-settings-order-contact]]
.Standardeinstellungen für die neue Auftragsanlage (beta)
[cols="1,3"]
|===
|Einstellung |Erläuterung

|[#intable-standard-eigner]*Standard-Eigner*
|Wählst du einen Standard-Eigner, ist dieser in den Auftragsdetails des neuen Auftrags oder Angebots standardmäßig vorausgewählt. Der Eigner wird generell nicht aus den Kontaktdaten übernommen.

|[#intable-standard-mandant]*Standard-Mandant*
|Der hier ausgewählte Standard-Mandant ist beim Anlegen des neuen Auftrags oder des Angebots vorausgewählt, wenn in den Kontaktdaten kein Mandant hinterlegt ist. Ist in den Kontaktdaten ein Mandant hinterlegt, hat dieser Mandant Priorität.

|[#intable-standard-herkunft]*Standard-Herkunft*
|Die hier ausgewählte Standard-Herkunft ist beim Anlegen des neuen Auftrags oder Angebots vorausgewählt, wenn in den Kontaktdaten keine Herkunft hinterlegt ist. Ist in den Kontaktdaten eine Herkunft hinterlegt, hat diese Herkunft Priorität.

|[#intable-endpoint-after-completion]*Endpunkt nach Abschluss eines Auftrags*
|Wähle, wohin du nach Abschluss einer Auftragsanlage geleitet werden möchtest. Du kannst wählen zwischen: +
*Auftragsübersicht des Kontakts* = Leitet dich zur Auftragsübersicht im Kontaktdatensatz des Kontakts des gerade erstellten Auftrags. Dies ist die Standardeinstellung. +
*Auftragsübersicht* = Leitet dich zur allgemeinen Auftragsübersicht weiter. +
*Detailansicht des neuen Auftrags* = Leitet dich zur Detailansicht des gerade erstellten Auftrags.

|[#intable-shopping-cart-type]*Verwendeter Warenkorbtyp in der Auftragserstellung*
|Wähle, welchen Typ von Warenkorb du in der Auftragserstellung nutzen möchtest. Standardmäßig ist der Side cart ausgewählt. Die Funktionen im Warenkorb sind bei beiden Typen gleich. +
*Warenkorb als Side cart* = Der Warenkorb wird seitlich als Overlay dargestellt, wenn man ihn öffnet. +
*Warenkorb als Tabelle (unterhalb der Suchergebnisse)* = Der Warenkorb wird als Tabelle unterhalb der Artikeltabelle (generiert durch die Artikelsuche) dargestellt.

|[#intable-standard-vorlage]*Standard-Auftragsvorlage*
|Wählst du eine <<#create-and-apply-order-templates, Auftragsvorlage>> als Standard-Auftragsvorlage, ist diese für den neuen Auftrag oder das Angebot standardmäßig vorausgewählt. Die Werte der ausgewählten Auftragsvorlage werden dann automatisch für den Auftrag oder das Angebot übernommen. Es können nur bereits angelegte Auftragsvorlagen ausgewählt werden. +
Standardmäßig ist *Keine Auftragsvorlage vorausgewählt* gesetzt. Wählst du eine Auftragsvorlage als Standard und wird diese zu irgendeinem Zeitpunkt gelöscht, wird als Standard für diese Einstellung wieder *Keine* gesetzt.

|*Filteroption ‚Nur vorrätige Artikel anzeigen‘ in der Artikelsuche vorausgewählt*
|Aktiviere diese Option, damit sie für die Artikelsuche vorausgewählt ist. In den Suchergebnissen werden dann nur Artikel angezeigt, die einen physischen Warenbestand haben.

|*Filteroption ‚Nur Vertriebslager anzeigen‘ in der Artikelsuche vorausgewählt*
|Aktiviere diese Option, damit sie für die Artikelsuche vorausgewählt ist. In den Suchergebnissen werden dann nur Artikel angezeigt, die in Vertriebslagern gelagert werden.

|*Filteroption ‚Nur aktive Artikel anzeigen‘ in der Artikelsuche vorausgewählt*
|Aktiviere diese Option, damit sie für die Artikelsuche vorausgewählt ist. In den Suchergebnissen werden dann nur xref:artikel:checkliste-artikel-anzeige.adoc#100[aktivierte Artikel] angezeigt.

|*Filteroption ‚Nur Artikel mit gültigem Preis anzeigen‘ in der Artikelsuche vorausgewählt*
|Aktiviere diese Option, damit sie für die Artikelsuche vorausgewählt ist. In den Suchergebnissen werden dann nur Artikel angezeigt, die einen gültigen Preis hinterlegt haben.

|*Änderung der Mehrwertsteuersätze in der Artikelübersichtstabelle im letzten Schritt der Auftragserstellung erlauben*
|Durch Aktivierung dieser Option erlaubst du, dass vor dem Abschließen des Auftrags im letzten Schritt der Auftragsanlage Steuersätze geändert werden dürfen. Die Steuersätze richten sich dabei nach der Lieferadresse des Auftrags. +
Diese Option ist standardmäßig deaktiviert. Lasse sie deaktiviert, wenn du die Mehrwertsteuersätze in der Übersicht nur sichtbar, aber nicht bearbeitbar lassen möchtest.

|*Anzeige von hinzugefügten Artikeln im Warenkorb*
|Wähle, wie die Artikel zum Warenkorb hinzugefügt werden sollen. Die Standardeinstellung ist *Als eine Auftragsposition, Mengen werden erhöht*. +
*Als separate Auftragspositionen* = Auch gleiche Artikel werden einzeln hinzugefügt, d.h. jeder Artikel wird in einer eigenen Zeile dargestellt. +
*Als eine Auftragsposition, Mengen werden erhöht* = Gleiche Artikel werden in einer Auftragsposition zusammengefasst und die Menge wird entsprechend angepasst.

|*Bei Auftragserstellung Preise nur im Warenkorb neu ermitteln*
|Durch Aktivierung dieser Option legst du fest, dass Preise von Artikeln nur dann neu ermittelt werden, wenn sie in den Warenkorb gelegt werden. Standardmäßig werden Preise schon in der Artikelsuche innerhalb der Auftragsanlage ermittelt und sind dort wählbar.

|===

[#create-order-or-offer]
=== Auftrag oder Angebot anlegen

Der Auftrag oder das Angebot wird individuell für Kund:innen im Menü *CRM » Kontakte* erstellt. Die Anlage verläuft in drei Schritten. Im ersten Schritt werden Auftragsdetails erfasst, im zweiten Schritt werden Artikel hinzugefügt und im dritten Schritt wird der Auftrag abgeschlossen. Wähle zunächst aus den Kontakten, für wen der Auftrag oder das Angebot angelegt werden soll. Gehe dabei wie im Folgenden beschrieben vor.

[.instruction]
Auftrag oder Angebot über Kontakt anlegen:

. Öffne das Menü *CRM » Kontakte*.
. Suche den Kontakt anhand der Filtereinstellungen. Beachte dazu die Erläuterungen zu den Filtern auf der Seite xref:crm:kontakt-suchen.adoc#[Kontakt suchen]. +
→ Die Kontakte, die den Suchkriterien entsprechen, werden angezeigt.
. Klicke rechts in der Zeile des Kontakts auf material:more_vert[]. +
→ Eine Auswahl der verfügbaren Optionen wird geöffnet.
. Wähle die Option material:shopping_cart[] *Aufträge* > *Neuer Auftrag [Beta]* oder *Neues Angebot [Beta]*. +
→ Du wirst automatisch zu den Auftragsdetails für den neuen Auftrag bzw. das neue Angebot weitergeleitet.

Oberhalb der Auftragsdetails kannst du aus der Dropdown-Liste auch nachträglich zwischen Auftrag und Angebot wählen. Zudem kannst du optional eine <<#create-and-apply-order-templates, Auftragsvorlage>> aus der Dropdown-Liste wählen, die auf diesen Auftrag angewendet werden soll. In der Standardeinstellung ist hier keine Auftragsvorlage ausgewählt.

Die im Folgenden beschriebenen Schritte sind für Auftrag und Angebot gleich.

Die Ansichten der Benutzeroberfläche sind so gestaltet, dass sich Aufträge schnell und übersichtlich anlegen lassen. Dies ist vor allem bei der telefonischen Aufnahme von Bestellungen von Vorteil. Zunächst werden die Auftragsdetails wie z.B. Adressen oder die Zahlungsart abgefragt. Danach werden dem Auftrag Artikel hinzugefügt, um ihn im letzten Schritt zu überprüfen und anzulegen.

[#order-details]
=== Auftragsdetails

Da der neue Auftrag oder das neue Angebot über die Kontaktübersicht angelegt wird, werden in den Auftragsdetails bereits einige der im Kontakt hinterlegten Daten übernommen. Welche Informationen übernommen werden, hängt davon ab, welche Daten im Kontakt gespeichert sind. Ansonsten greifen die <<#carrying-out-standard-settings, Standardeinstellungen>>. Beachte dazu auch <<table-order-details-new-order, diese Tabelle>>. Alle Angaben in den Auftragsdetails sind Pflichtfelder.

[[table-order-details-new-order]]
.Neuer Auftrag: Auftragsdetails
[cols="1,3"]
|===
|Einstellung |Erläuterung

|*Rechnungsadresse*
|Die im Datensatz des Kontakts hinterlegte Rechnungsadresse wird übernommen. Sind mehrere Rechnungsadressen hinterlegt, wird die als primär definierte Rechnungsadresse übernommen. Wenn keine Rechnungsadresse als primäre Adresse definiert ist, kannst du aus der Dropdown-Liste die gewünschte Adresse wählen. +
Über die Vorschau (material:visibility[]) gelangst du direkt in den Kontaktatensatz. Die bereits gewählten Einstellungen in den Auftragsdetails gehen nicht verloren.

|*Lieferadresse*
|Wenn du die Option *Wie Rechnung* auswählst, wird die unter *Rechnungsadresse* eingegebene Adresse auch als Lieferadresse übernommen. Ansonsten wird die im Datensatz des Kontakts hinterlegte Lieferadresse übernommen. Sind mehrere Lieferadressen hinterlegt, wird die als primär definierte Adresse übernommen. Wenn keine Lieferadresse als primäre definiert ist, kannst du aus der Dropdown-Liste die gewünschte Adresse wählen. +
In der Dropdown-Liste hast du auch die Möglichkeit, eine neue Lieferadresse einzugeben und im Kontaktdatensatz zu speichern. Beachte dazu die Erläuterungen in der ausklappbaren Box unterhalb am Ende dieses Abschnitts. +
Über die Vorschau (material:visibility[]) gelangst du direkt in den Kontaktdatensatz. Die bereits gewählten Einstellungen in den Auftragsdetails gehen nicht verloren.

|*Zahlungsart*
|Wenn im Kontakt eine Zahlungsart definiert ist, zum Beispiel über eine xref:crm:vorbereitende-einstellungen.adoc#kundenklasse-erstellen[Kundenklasse], ist diese vorausgewählt. Ansonsten kannst du eine Zahlungsart eingeben und dann auswählen. Angeboten werden dir alle Zahlungsarten, die bereits in deinem plentymarkets System integriert sind. +
Nutzt du eine <<#create-and-apply-order-templates, Auftragsvorlage>>, wird die Zahlungsart der Auftragsvorlage genommen, sobald du die Vorlage für den Auftrag wählst. Danach ist die Zahlungsart manuell anpassbar.

|*Rabatt in %*
|Gib einen prozentualen Rabatt ein, der auf alle Auftragspositionen des Auftrags angewendet wird. Der eingegebene Wert muss zwischen 0 und 100 liegen, Werte im Minusbereich sind nicht erlaubt. +
Es ist ein Rabatt voreingetragen, wenn der Kontakt zu einer Kundenklasse gehört, in der die Option *Standardrabatt für manuelle Aufträge* mit einem Wert gefüllt ist. Du findest diese Option im Bereich xref:crm:vorbereitende-einstellungen.adoc#intable-customer-class-discount-type[Rabattart] im Menü *Einrichtung » CRM » Kundenklassen*. Der voreingetragene Wert in den Auftragsdetails ist anpassbar.

|*Währung*
|Die xref:payment:waehrungen.adoc#30[Systemwährung] ist vorausgewählt. Über die Dropdown-Liste kannst du die Währung für den Auftrag anpassen.

|*Lager*
|Welche Optionen dir angezeigt werden, hängt von den Grundeinstellungen ab, die du für die xref:auftraege:preparatory-settings.adoc#intable-warehouse-assignment[Zuordnung von Lagern] gewählt hast: +
- Ist *a) pro Auftrag kann ein Lager zugeordnet werden* ausgewählt, kannst du in den Auftragsdetails aus einer Dropdown-Liste ein Lager für den Auftrag wählen. +
- Ist *b) pro Artikelposition kann ein Lager zugeordnet werden* ausgewählt, wird dir *Abhängig vom Warenbestand* angezeigt. In der nächsten Ansicht werden dem Auftrag Artikel hinzugefügt. Dort kannst du dann für jede Variante ein Lager aus der Dropdown-Liste wählen.

|*Mandant*
|Wähle aus der Dropdown-Liste den Mandanten, für den dieser Auftrag gelten soll. Vorausgewählt ist entweder der Mandant aus den Kontaktdaten oder als nächste Option ein <<#intable-standard-mandant, Standard-Mandant>>, wenn du diesen festgelegt hast.

|*Eigner*
|Wähle aus der Dropdown-Liste den Eigner für diesen Auftrag. Hast du einen <<#intable-standard-eigner, Standard-Eigner>> gesetzt, ist dieser vorausgewählt. Ansonsten werden dir in der Dropdown-Liste nur Eigner angezeigt, die das Benutzerrecht haben, Aufträge zu erstellen und zu bearbeiten.

|*Herkunft*
|Wähle aus der Dropdown-Liste die Herkunft für diesen Auftrag. Vorausgewählt ist entweder die Herkunft aus den Kontaktdaten oder als nächste Option eine <<#intable-standard-herkunft, Standard-Herkunft>>, wenn du diese festgelegt hast. Darüber hinaus werden nur die xref:auftraege:auftragsherkunft.adoc#[Herkünfte] angezeigt, die aktiv geschaltet sind.

|===

Nachdem du alle Einstellungen vorgenommen hast, gehe zum nächsten Schritt und füge die gewünschten Artikel dem Auftrag hinzu.


[.collapseBox]
.*Neue Lieferadresse anlegen*
--

Von der Dropdown-Liste im Feld *Lieferadresse* aus kannst du nicht nur eine bestehende Lieferadresse wählen, du kannst auch eine neue anlegen.

[.instruction]
Neue Lieferadresse anlegen:

. Wähle aus der Dropdown-Liste *Lieferadresse* die Option *(material:add[]) Neue Lieferadresse hinzufügen*. +
→ Das Fenster *Neue Lieferadresse hinzufügen* öffnet sich.
. Wähle, ob es sich um die *Primäre* Lieferadresse handelt.
. Gib die Daten ein. Beachte hierzu <<#table-new-delivery-address>>.
. *Speichere* die neue Adresse.

Nach dem Speichern wird die neue Lieferadresse in den entsprechenden Kontaktdatensatz übernommen. Für den neuen Auftrag ist sie nach dem Anlegen im Feld *Lieferadresse* ausgewählt.

[[table-new-delivery-address]]
.Auftragsdetails: Neue Lieferadresse anlegen
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Primär*
|Aktiviere die Option, wenn es sich bei der neuen Adresse um die primäre Lieferadresse handelt. Bei Aktivierung wird diese Lieferadresse beim Anlegen neuer Aufträge automatisch für den neuen Auftrag übernommen.

|*Anrede*
|Wähle optional eine Anrede aus der Dropdown-Liste.

|*Firma (Name 1)*
|Gib den Firmenname ein. Dies ist ein Pflichtfeld, wenn unter *Vorname* und *Nachname* kein Eintrag gemacht wird.

|*Vorname (Name 2)*
|Gib den Vorname des Kontakts ein. Das ist ein Pflichtfeld, wenn unter *Firma* und *Nachname* kein Eintrag gemacht wird.

|*Nachname (Name 3)*
|Gib den Nachname des Kontakts ein. Das ist ein Pflichtfeld, wenn unter *Firma* und *Vorname* kein Eintrag gemacht wird.

|*Zusatz (Name 4)*
|Gib optional Zusatzangaben zum Kontakt ein, wie z.B. z. Hd. Herrn Max Mustermann.

|*Adresse 1 (Straße)* +
*Adresse 2 (Hausnummer)*
|Gib die Straße und Hausnummer ein. +
*Straße* ist ein Pflichtfeld, wenn unter *Hausnummer* und *Adresszusatz* kein Eintrag gemacht wird. *Hausnummer* ist ein Pflichtfeld, wenn unter *Straße* und *Adresszusatz* kein Eintrag gemacht wird.

|*Adresse 3 (Adresszusatz)*
|Gib optional einen Adresszusatz ein, wie z.B. Apartment 12a. Dies ist ein Pflichtfeld, wenn unter *Straße* und *Hausnummer* kein Eintrag gemacht wird.

|*Adresse 4 (Frei)*
|Dies ist ein Feld zur freien Verfügung.

|*Postleitzahl* +
*Ort*
|Gib die Postleitzahl und den Ort des Kontakts ein. *Ort* ist ein Pflichtfeld. +
Bei bestimmten Ländern, z.B. Vereinigtes Königreich, wird die Reihenfolge der Optionen *Postleitzahl* und *Ort* getauscht.

|*Land* +
*Region/Bezirk*
|Wähle Werte aus den Dropdown-Listen. +
*_Hinweis:_* Die Dropdown-Liste *Region/Bezirk* ist nicht für alle Länder verfügbar.

|*E-Mail*
|Gib optional eine E-Mail-Adresse ein.

|*Telefon*
|Gib optional eine Telefonnummer ein.

|*Typ* und *Wert*
|Wähle einen Typ aus der Dropdown-Liste. Zur Verfügung stehen: Umsatzsteuernummer, Externe Adress-ID, Gelangensbestätigung, Postnummer, Personennummer, FSK, Geburtstag, Titel, Ansprechpartner, Externe Kunden-ID. Gib außerdem den passenden *Wert* für den ausgewählten Typ eingeben. +
Über *Adressoption hinzufügen* kannst du weitere *Typen* mit den dazugehörigen *Werten* hinzufügen.

|====

--

[#add-items]
=== Artikel hinzufügen

In diesem Schritt werden die Auftragsdetails nicht angezeigt. Erst im dritten Schritt, der Überprüfung, sind die Auftragsdetails wieder verfügbar. Beachte, dass dort lediglich die Versandart und die Versandkosten bearbeitet werden können.

Um einen Auftrag abzuschließen und ihn anzulegen, müssen Artikel hinzugefügt werden. Führe eine Suche aus, um die passenden Artikel zu finden und dann hinzuzufügen. Für die Artikelsuche kannst du zwischen verschiedenen Filtern wählen:

* Artikel-ID
* Artikelname
* Variantennummer
* Varianten-ID
* Barcode
* Hersteller
* Tag Artikel

Zusätzlich kannst du die Optionen *Nur aktive Artikel anzeigen*, *Nur vorrätige Artikel anzeigen*, *Nur Vertriebslager anzeigen* und *Nur Artikel mit gültigem Preis anzeigen* wählen. Wenn wie oben beschrieben deine Lagereinstellung in den Grundeinstellungen *a) pro Auftrag kann ein Lager zugeordnet werden* ist, steht dir die Option *Nur Vertriebslager anzeigen* nicht zur Verfügung, weil du das Lager bereits vorher bestimmt hast. Zudem greifen bei der Suche die <<#carrying-out-standard-settings, Standardeinstellungen>>, die du vorher vorgenommen hast.

Führe die Suche (material:search[]) aus, um die gewünschten Auftragspositionen zu finden und dem Auftrag hinzuzufügen.

[.collapseBox]
.*Suchfunktionen*
--
Du hast mehrere Möglichkeiten, die Suche zu nutzen. Du kannst einen Wert im Suchfeld eingeben und dann den entsprechenden Filter auswählen. Bei Eingabe einer Zahl oder eines Buchstaben werden dir mögliche Filter vorgeschlagen, z.B. Auftrags-IDs oder Variantennummer. Gib den Wert vollständig ein und wähle den passenden Filter aus den Vorschlägen. Wiederhole dies, um Filter miteinander zu kombinieren. Klicke auf *Suchen* (material:search[]), um die Suche auszuführen. +
Möchtest du erst einen Filter aus der Filterliste wählen, klicke auf *Filter* (material:tune[]). Die verfügbaren Filter werden dir angezeigt. Gib einen Wert im gewünschten Filter ein. Hast du alle benötigten Filter gesetzt, klicke auf *Suchen*. +
Möchtest du einen gesetzten Filter löschen, entferne den Chip.

Zudem kannst du mit der Komponente *Gespeicherte Filter* (material:bookmarks[]) ausgewählte Filter in der UI speichern. Gespeicherte Filtersets sind dann in dieser Komponente bei jedem Öffnen des Menüs auswählbar, ähnlich wie Lesezeichen. Jede:r Benutzer:in kann eigene Filter festlegen.

[.instruction]
Filter speichern:

. Setze die gewünschten Filter mit den entsprechenden Werten.
. Führe die Suche aus.
. Klicke auf *Gespeicherte Filter* (material:bookmarks[]).
. Klicke auf *Aktuellen Filter speichern* (material:bookmark_border[]). +
→ Das Fenster *Filter speichern* öffnet sich.
. Vergib einen *Filternamen*.
. Entscheide, ob das Filterset als Standard-Filterset genutzt werden soll.
. Entscheide, ob das Filterset für alle Benutzer:innen zur Verfügung stehen soll.
. Klicke auf *Speichern*.

--

Die Artikeltabelle ist individuell anpassbar. Das bedeutet, dass du selbst entscheiden kannst, welche Informationen dir in den Tabellenspalten angezeigt werden. Gehe dafür folgendermaßen vor:

[.instruction]
Tabelle individualisieren:

. Klicke auf *Spalten konfigurieren* (material:settings[]). +
→ Das Fenster *Spalten konfigurieren* öffnet sich.
. Wähle, welche Spalten angezeigt werden sollen. Beachte dafür <<table-overview-item-search>>.
. Verschiebe (material:sort[]) die Spalten, so dass sie in der Reihenfolge angezeigt werden, in der du sie brauchst.
. Klicke auf *Bestätigen*, um deine Auswahl zu speichern.

Wenn du die Tabelle einmal angepasst hast, wird diese Auswahl gespeichert. Die Tabelle bleibt also gleich, auch wenn du diesen Auftrag abgeschlossen hast und weitere anlegst. Du kannst das Layout jederzeit ändern. Die zu Verfügung stehenden Spalten findest du in <<table-overview-item-search>>. Dort ist zu jeder Spalte auch die Information hinterlegt, ob es sich um eine Standardspalte handelt. Standardspalten werden angezeigt, wenn die Tabelle nicht individualisiert ist.

[[table-overview-item-search]]
.Spalten Tabelle Artikelsuche
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Bestandsanzeige*
|Ein roter Statusbalken zeigt an, wenn kein Nettobestand für einen Artikel verfügbar ist. Der rote Statusbalken wird nicht angezeigt, wenn Nettobestand für den Artikel vorhanden ist. Wenn du zum Beispiel *Nur vorrätige Artikel anzeigen* ausgewählt hast, wird kein Statusbalken in rot angezeigt werden. Der Statusbalken wird erst rot, wenn der Bestand unter 0 sinkt während des Hinzufügens zum Warenkorb. +
Diese Spalte ist eine Standardspalte.

|*Status*
|In dieser Spalte wird angezeigt, ob diese Variante im Webshop aktiv oder inaktiv ist. Informationen zur Aktivierung oder Deaktivierung einer Variante findest du auf der Handbuchseite xref:artikel:checkliste-artikel-anzeige.adoc#100[Hast du die Variante aktiviert?]. +
Diese Spalte ist eine Standardspalte.

|*Artikel-ID*
|Wenn du auf die Artikel-ID klickst, gelangst du direkt in die Einstellungen des jeweiligen Artikels. +
Diese Spalte ist keine Standardspalte.

|*Varianten-ID*
|Wenn du auf die Varianten-ID klickst, gelangst du direkt in die Einstellungen der Variante. +
Diese Spalte ist keine Standardspalte.

|*Artikel-ID/Varianten-ID*
|Diese Spalte zeigt dir die Artikel-ID und die Varianten-ID kombiniert und nicht in zwei separaten Spalten an. Wenn du auf die Artikel-ID oder die Varianten-ID klickst, gelangst du direkt in die Einstellungen des jeweiligen Artikels bzw. der Variante. +
Diese Spalte ist keine Standardspalte.

|*Variantennummer*
|Wenn du auf die Variantennummer klickst, gelangst du direkt in die Einstellungen der jeweiligen Variante. +
Diese Spalte ist eine Standardspalte.

|*Artikelname*
|Die am Artikel hinterlegte Beschreibung wird angezeigt. +
Diese Spalte ist eine Standardspalte.

|*Attribute*
|Die am Artikel hinterlegten Attribute werden angezeigt. +
Diese Spalte ist eine Standardspalte.

|*Variantenname*
|Der an der Variante hinterlegte Variantenname wird angezeigt. +
Diese Spalte ist eine Standardspalte.

|*Barcode*
|Barcodes werden angezeigt. +
Diese Spalte ist keine Standardspalte.

|*Menge*
|Gib die Menge ein, in der der Artikel dem Warenkorb hinzugefügt werden soll. Du kannst nur ganze Zahlen eingeben. Negative Mengen oder Mengen, die den Nettobestand übersteigen, sind nicht erlaubt. In diesem Fall wird eine Fehlermeldung angezeigt. Wenn die hinzugefügte Menge den Nettobestand auf 0 oder niedriger setzt, wird der Statusbalken für die Bestandsanzeige auf rot gesetzt. +
Bei Mengenänderungen ändert sich der Verkaufspreis, daher muss der Verkaufspreis aktualisiert werden. Klicke dafür auf *Verkaufspreis aktualisieren* (material:refresh[]). Nach der Aktualisierung ist die Warenkorb-Schaltfläche (material:add_shopping_cart[]) wieder verfügbar und die Artikel können hinzugefügt werden. +
Dies ist eine Standardspalte.

|*Verkaufspreis*
|Der aus der <<#intable-item-search-price-selection, Preisauswahl>> gewählte Verkaufspreis für diesen Artikel wird angezeigt. +
Dies ist eine Standardspalte.

|[#intable-item-search-price-selection]*Preisauswahl*
|In einer Dropdown-Liste werden dir alle für diesen Auftrag ermittelten Verkaufspreise angezeigt. Du kannst einen der angezeigten Preise wählen, dieser wird dann als Grundlage für die weiteren Auftragsberechnungen genommen. Enthält der Preis einen Rabatt, wird dies hinter dem Preisnamen und dem Betrag angezeigt. Die Spalten *Kundenklassenrabatt* und *Kategorierabatt* zeigen den Prozentsatz des angewendeten Rabatts an. +
Eine manuelle Anpassung des Preises kannst du im <<#shopping-cart, Warenkorb>> vornehmen. Wählst du einen anderen Verkaufspreis als den zuerst ermittelten, muss der Verkaufspreis aktualisiert werden. Klicke dafür auf *Verkaufspreis aktualisieren* (material:refresh[]). Nach der Aktualisierung ist die Warenkorb-Schaltfläche (material:add_shopping_cart[]) wieder verfügbar und die Artikel können hinzugefügt werden. Dies gilt auch für Mengenänderungen. +
Konnte kein gültiger Verkaufspreis ermittelt werden, wird *Kein gültiger Verkaufspreis* in der Dropdown-Liste angezeigt. Ohne gültigen Verkaufspreis kann der Auftrag nicht abgeschlossen werden. Lege daher den Artikel in den Warenkorb und passe den Preis dort manuell an. +
Diese Spalte ist eine Standardspalte.

|*Verfügbarkeit*
|In dieser Spalte wird die Verfügbarkeit der Variante angezeigt. Das dargestellte Symbol hängt davon ab, welches du im Menü *Einrichtung » Artikel » Verfügbarkeit* vergeben hast. Weitere Informationen zu diesen Einstellungen findest du auf der Handbuchseite xref:artikel:verfuegbarkeiten.adoc#[Verfügbarkeiten]. +
Diese Spalte ist eine Standardspalte.

|*Netto-WB*
|Der Warenbestand für das ausgewählte Lager wird angezeigt. +
Diese Spalte ist eine Standardspalte.

|*Lager*
|Das Lager des Artikels wird angezeigt. +
Diese Spalte ist eine Standardspalte.

|*Warenkorb Icon*
|Durch Klick auf den diesen Warenkorb (material:add_shopping_cart[]) wird der Artikel in der ausgewählten *Menge* dem Warenkorb hinzugefügt. +
Diese Spalte ist eine Standardspalte.

|====

[.instruction]
Artikel hinzufügen:

. Suche (material:search[]) den gewünschten Artikel.
. Wähle den passenden Verkaufspreis aus der *Preisauswahl* Dropdown-Liste.
. Gib die Menge des Artikels ein, die dem Auftrag hinzugefügt werden soll. +
→ Bei Preis- und Mengenänderungen muss der Verkaufspreis durch klicken auf *Verkaufspreis aktualisieren* (material:refresh[]) aktualisiert werden.
. Füge die Artikel dem Auftrag hinzu, indem du am Ende der jeweiligen Zeile auf den Warenkorb (material:add_shopping_cart[]) klickst. +
→ Wenn ein Artikel erfolgreich hinzugefügt wurde, verändert das Warenkorb-Symbol (material:add_shopping_cart[]) kurzzeitig Größe und Farbe.
. Wiederhole diese Schritte, um weitere Artikel hinzuzufügen.
. Wenn alle Artikel hinzugefügt wurden, gehe zum nächsten Schritt, indem du auf *Übersicht* klickst. +
→ Der Warenkorb wird gespeichert.

[#shopping-cart]
=== Warenkorb

Am Warenkorb-Symbol (material:shopping_cart[]) über der Tabelle wird dir die Anzahl der bereits hinzugefügten Artikel angezeigt. Möchtest du während des Hinzufügens von Artikeln den Warenkorb überprüfen oder hinzugefügte Artikel löschen, klicke auf diesen Warenkorb (material:shopping_cart[]).

Je nachdem, welchen <<#intable-shopping-cart-type, Warenkorbtyp>> du in den Standardeinstellungen ausgewählt hast, öffnet sich entweder der seitliche Warenkorb oder die Ansicht springt direkt zur Warenkorbtabelle. Unabhängig vom Warenkorbtyp kannst du dort sowohl die *Menge* als auch den *Verkaufspreis* anpassen. Sobald du die Angaben in einem der Felder änderst, müssen Aktualisierungen durchgeführt werden. Dies kannst du entweder am jeweiligen Artikel machen durch Klicken auf *Verkaufspreis aktualisieren* (material:refresh[]). Oder du nutzt die Schaltfläche *Verkaufspreise aktualisieren* unter dem Warenkorb. Erst nach der Aktualisierung kannst du in den nächsten Schritt der Auftragsanlage weitergehen.

Folgendes gilt für die Verkaufspreise:

* Gibst du manuell einen Preis ein, bleibt dieser in der Dropdown-Liste als Auswahl für diesen Auftrag erhalten, auch wenn du vor- oder zurückgehst oder zwischendurch einen anderen Preis auswählst.
* Konnte kein gültiger Verkaufspreis ermittelt werden, muss ein manueller Preis eingegeben werden. Die Auftragsanlage ist nur mit gültigen Preisen möglich.
* Es ist zulässig den Preis 0,00 einzugeben.
* Wenn ein Verkaufspreis eingegeben wird, der niedriger ist als der Einkaufspreis, wirst du durch eine Warnung darauf hingewiesen. Allerdings ist es möglich einen niedrigeren Verkaufspreis zu wählen, wenn es gewünscht wird.
* Nimm alle Anpassungen an Artikeln in diesem Schritt vor, im dritten und letzten Schritt der Auftragsanlage geht dies nicht. Vor und zurück navigieren innerhalb der Schritte der Auftragsanlage bleibt möglich.

Zudem können Auftragspositionen im Warenkorb auch gelöscht werden. Klicke dafür auf *Löschen* (material:delete[]). Eine weitere Bearbeitungsmöglichkeit der Auftragspositionen im Warenkorb stellen die Eigenschaften dar. Beachte dafür das folgende Kapitel <<#order-item-properties, Eigenschaften von Auftragspositionen>>.

Nachdem du alle gewünschten Artikel im Warenkorb abschließend bearbeitet hast, klicke auf *Übersicht*, um zum dritten und letzten Schritt zu gelangen. Du kannst auch zu den Auftragsdetails zurückkehren, indem du auf *Auftragsdetails* klickst. Artikel im Warenkorb werden gespeichert, wenn du vor oder zurück gehst.

[.collapseBox]
.*Warenkorbtabelle individualisieren*
--
Die Warenkorbtabelle lässt sich individuell anpassen. Du kannst wählen, welche Tabellenspalten dir in welcher Reihenfolge in der Tabelle angezeigt werden sollen. Standardmäßig werden dir beim Öffnen des Menüs folgende Tabellenspalten angezeigt:

* Artikel-ID/Varianten-ID
* Varianten Nr.
* Artikelname
* Attribute
* System-EK
* Preis
* Aufpreis gesamt = Die Summe der Aufpreise für Bestelleigenschaften.
* Gesamtsumme = Der Artikelpreis zuzüglich Aufpreise für Bestelleigenschaften.
* Rabatt = Beinhaltet den Rabatt, der in den Auftragsdetails im ersten Schritt der Auftragsanlage eingegeben wurde.
* Lager
* Menge
* Aktion

Die folgenden Tabellenspalten können ausgewählt werden, werden aber nicht standardmäßig angezeigt:

* Artikel-ID
* Varianten-ID
* Preisauswahl
* Kundenklassenrabatt = Der für den ausgewählten Verkaufspreis angewendete Kundenklassenrabatt in Prozent.
* Kategorierabatt = Der für den ausgewählten Verkaufspreis angewendete Kategorierabatt in Prozent.

Passe die Tabelle deinen Bedürfnissen und deinem Arbeitsablauf an. Wenn du die Tabelle angepasst hast, wird diese Auswahl gespeichert. Die Tabelle ist jederzeit anpassbar.

[.instruction]
Tabelle individualisieren:

. Klicke auf *Spalten konfigurieren* (material:settings[]). +
→ Das Fenster *Spalten konfigurieren* öffnet sich.
. Wähle aus, welche Spalten angezeigt werden sollen.
. Verschiebe (material:sort[]) die Spalten, so dass sie in der Reihenfolge angezeigt werden, in der du sie brauchst.
. Klicke auf *Bestätigen*, um deine Auswahl zu speichern.

--

[#order-item-properties]
=== Eigenschaften an Auftragspositionen

Vom Warenkorb aus kannst du die Eigenschaften der Auftragspositionen eines Auftrags (Bestelleigenschaften) bearbeiten. Die hier vorgenommenen Änderungen gelten nur für die Auftragspositionen dieses Auftrags. Die im System angelegten Eigenschaften werden nicht überschrieben. In der Auftragsanlage stehen dir nur Eigenschaften zur Verfügung, die du bereits im System angelegt hast. +
Möchtest du Eigenschaften erstellen und bearbeiten oder bist noch nicht mit der Struktur von Eigenschaften vertraut, informiere dich im Handbuchkapitel xref:artikel:eigenschaften.adoc#500[Eigenschaften].

Damit eine Eigenschaft an einer Auftragsposition gesetzt werden kann, muss sie in den Eigenschaftseinstellungen im Bereich *Optionen* als *Bestelleigenschaft* definiert werden. Lege unter xref:artikel:eigenschaften.adoc#property-options[Optionen] außerdem mögliche Aufpreise und Besteuerungen fest. Die hier hinterlegten Werte werden in die Auftragsberechnungen einbezogen.

Ist bereits eine Eigenschaft mit einer Auftragsposition verknüpft, wird diese an der dazugehörigen Auftragsposition angezeigt. Wie Eigenschaften angezeigt werden, hängt von deiner <<#intable-shopping-cart-type, Auswahl des Warenkorbtyps>> ab.

[tabs]
====
Warenkorb als Side cart::
+
--
Der Wert einer Eigenschaft wird unter der jeweiligen Auftragsposition als Chip angezeigt. Entfernst du einen Chip, wird diese Eigenschaft gelöscht und für diesen Auftrag nicht berücksichtigt. +
Um die Eigenschaften zu bearbeiten oder weitere bereits bestehende Eigenschaften zu einer Auftragspositionen hinzuzufügen, klicke auf material:edit[] unter *Auftragspositionseigenschaften*. Das gleiche Bearbeitungsfenster wie vom Warenkorb als Tabelle aus öffnet sich.

--

Warenkorb als Tabelle::
+
--
Die Eigenschaften werden in einer zweiten Tabellenzeile direkt unterhalb der dazugehörigen Auftragsposition angezeigt. Hier findest du Angaben zu *Name*, *Wert*, *Aufpreis* und *Ust. %* der Eigenschaft. *Ust. %*, also den hinterlegten Steuersatz, kannst du direkt in der Tabelle bearbeiten, wenn der Eigenschaftstyp dies zulässt. Zudem kannst du die Eigenschaften der Auftragspositionen *löschen* (material:delete[]). Gelöschte Eigenschaften werden dann für diesen Auftrag nicht berücksichtigt. +
Um die Eigenschaften zu bearbeiten oder weitere bereits bestehende Eigenschaften zu einer Auftragspositionen hinzuzufügen, klicke auf *Eigenschaften bearbeiten* (material:edit[]). Das gleiche Bearbeitungsfenster wie vom Warenkorb als Side cart aus öffnet sich.

--
====

Im Bearbeitungsfenster *Eigenschaften von [ausgewählte Auftragsposition mit ID] bearbeiten* findest du folgende Angaben zu der Eigenschaft einer Auftragsposition:

* *Name* = Der Name der Eigenschaft wird angezeigt. Ein rotes Sternchen am Namen der Eigenschaft kennzeichnet, dass es eine *Verpflichtende* Eigenschaft ist. Ob eine Eigenschaft *Verpflichtend* ist, bestimmst du in den Einstellungen der Eigenschaften im Bereich xref:artikel:eigenschaften.adoc#property-options[Optionen]. Wähle in der Dropdown-Liste *Bestelloptionen* die Einstellung *Verpflichtend* aus.
* *Wert* = Der Wert der Eigenschaft wird angezeigt. Der Wert ist anpassbar. Je nach Eigenschaftstyp kannst du eine Auswahl treffen, den Wert ändern, einen Wert eingeben oder eine Datei hochladen. Die Änderungen gelten nur für diesen Auftrag.
* *Aufpreis* = Der Aufpreis der Eigenschaft, sofern sie einen zugeordnet hat, wird angezeigt. Der Aufpreis ist bearbeitbar. Die Änderungen gelten nur für diesen Auftrag.

Zudem hast du in diesem Fenster einige weitere Bearbeitungsmöglichkeiten. Durch Klicken auf *Löschen* (material:delete[]) entfernst du eine Eigenschaft von einer Auftragsposition. Diese Eigenschaft wird dann für diesen Auftrag nicht berücksichtigt. +
Du kannst weitere bereits angelegte Eigenschaften hinzufügen. Wähle eine Eigenschaft aus der Dropdown-Liste des Feldes *Eigenschaft wählen* aus und füge sie durch Klicken auf *Eigenschaft hinzufügen* (icon:plus-square[role="green"]) zu dieser Auftragsposition hinzu. +
Hast du alle erforderlichen Anpassungen vorgenommen, klicke auf *Eigenschaften speichern*. Klickst du auf *Verwerfen*, wird keine der vorgenommenen Änderungen übernommen. Das Bearbeitungsfenster wird geschlossen und du kannst nach Bedarf die Eigenschaften weiterer Auftragspositionen auf die gleiche Weise bearbeiten.

Wenn du die Eigenschaften auf Dokumenten ausgeben lassen möchtest, musst du dies in der Konfiguration der Eigenschaften einstellen. Stelle sicher, dass im Bereich xref:artikel:eigenschaften.adoc#property-visibilities[Sichtbarkeiten] die folgenden Optionen gewählt sind:

* aus der Dropdown-Liste *Überall anzeigen* die Option *Anzeige auf PDF-Dokumenten* sowie
* aus der Dropdown-Liste *Mandant* die richtigen Mandanten.

Wo die Eigenschaften auf dem Dokument ausgegeben werden, hängt von der jeweiligen Eigenschaft und ihrer Konfiguration ab. Eigenschaften, die in der Konfiguration im Bereich *Optionen* keinen Steuersatz zugewiesen bekommen haben oder für die aus der Dropdown-Liste *Bestelleigenschaft* die Option *zusätzliche Kosten anzeigen* ausgewählt ist, werden unter den Summen angezeigt. Andere Eigenschaften werden in der Artikelpositionstabelle angezeigt.

Wenn du mit der Bearbeitung der Auftragseigenschaften und des Warenkorbs fertig bist, folgt der Schritt *Übersicht* in der Auftragsanlage. In diesem Schritt werden die Eigenschaften für Auftragspositionen nicht noch einmal angezeigt. Stelle daher sicher, dass du alle Anpassungen vorgenommen hast, bevor du in der Erstellung des Auftrags weitergehst.

[#complete-order]
=== Übersicht: Auftrag abschließen

In der letzten Ansicht wird der Auftrag abgeschlossen. Über den Auftragsdetails werden dir Infoboxen mit verschiedenen Beträgen für diesen Auftrag angezeigt:

* Gesamtbetrag (brutto): Zeigt den errechneten Gesamtbruttobetrag des Auftrags. Der Statusbalken wird in grün angezeigt, wenn es sich bei dem Auftrag um einen Bruttoauftrag handelt. Ansonsten ist der Statusbalken grau.
* Gesamtbetrag (netto): Zeigt den errechneten Gesamtnettobetrag des Auftrags. Der Statusbalken wird in grün angezeigt, wenn es sich bei dem Auftrag um einen Nettoauftrag handelt. Ansonsten ist der Statusbalken grau.
* Artikelmenge (gesamt): Zeigt die Gesamtanzahl der Artikelpositionen des Auftrags an. Der Statusbalken wird immer in grau angezeigt.
* Gutscheinbetrag: Zeigt die Ermäßigung durch Aktionsgutscheine.  Der Statusbalken wird in orange angezeigt, wenn ein Gutschein im Auftrag verwendet wurde. Ansonsten ist der Statusbalken grau.
* Auftragsrabatt: Zeigt den Rabattbetrag, der sich durch den im ersten Schritt der Auftragsanlage vergebenen Rabatt ergibt. Errechnet wird der summierte Rabatt für alle Auftragspositionen. Der Statusbalken wird in orange angezeigt, wenn im ersten Schritt ein Rabatt gesetzt wird. Ansonsten ist der Statusbalken grau.
* Offener Betrag: Zeigt den von Kund:in zu zahlenden Rechnungsbetrag. Der Statusbalken wird in grün angezeigt, wenn der Betrag bei null liegt, d.h. der Auftrag vollständig bezahlt wurde. Rot bedeutet, der vollständige Rechnungsbetrag ist noch offen. Orange bedeutet, dass ein Teil des Rechnungsbetrags noch offen ist.

In den Auftragsdetails kannst du die *Versandart* und die *Versandkosten* anpassen. +
Zudem kannst du einen oder mehrer *Gutscheincodes* eingeben, die mit diesem Auftrag eingelöst werden. Drück nach Eingabe des Codes _Enter_ oder klicke mit der Maus außerhalb des Feldes. Es wird sofort überprüft, ob der Gutscheincode einlösbar ist. Einlösbare Gutscheine werden in grün mit dem Wert des Gutscheins wiedergegeben. Ein Tooltip zeigt an, um welche Art von Gutschein es sich handelt. Gutscheine, die nicht einlösbar sind, werden in rot wiedergegeben und *Nicht einlösbar* wird angezeigt statt des eingegebenen Codes. Du kannst mehrere Codes eingeben, wenn du möchtest. +
Die Werte der Gutscheine werden mit dem Auftragswert verrechnet. Gutscheine werden nicht als Auftragspositionen im Warenkorb hinzugefügt. Gutscheine können nicht für Angebote eingelöst werden. Dies bedeutet, dass das Eingabefeld *Gutscheincodes* nur in der Auftragserstellung und nicht in der Angebotsrestellung verfügbar ist.

Unterhalb der Auftragsdetails wird eine Tabelle mit den ausgewählten Artikelpositionen angezeigt. Zusätzlich zu den Angaben in der vorherigen Ansicht werden dir in dieser weitere Preise und die Umsatzsteuer ausgegeben. Steuersätze lassen sich anpassen, wenn du dies in den <<#carrying-out-standard-settings, Standardeinstellungen>> erlaubt hast. +
Außerdem kannst du in dieser Tabelle die *Artikelbeschreibung* individuell anpassen. Die angepasste Artikelbeschreibung wird nur für diesen Auftrag übernommen. Das bedeutet, dass die angepasste Beschreibung für die Auftragsdaten und auch die Auftragsdokumente dieses Auftrags übernommen wird. Außerhalb dieses Auftrags bleibt die bereits im System hinterlegte Artikelbeschreibung bestehen. Es gibt eine Beschränkung von 1500 Zeichen für die *Artikelbeschreibung*.

[.collapseBox]
.*Tabelle individualisieren*
--
Die Tabelle im letzten Schritt der Auftragsanlage lässt sich individuell anpassen. Du kannst wählen, welche Tabellenspalten dir in welcher Reihenfolge in der Tabelle angezeigt werden sollen. Standardmäßig werden dir beim Öffnen des Menüs folgende Tabellenspalten angezeigt:

* Artikel-ID/Varianten-ID
* Varianten Nr.
* Artikelname
* Attribute
* Variantenname
* System-EK
* Preisauswahl
* Nettopreis
* Bruttopreis
* Gesamtsumme = Der Artikelpreis zuzüglich Aufschläge für Bestelleigenschaften.
* Rabatt = Beinhaltet den Rabatt, der in den Auftragsdetails im ersten Schritt der Auftragsanlage eingegeben wurde.
* Lager
* USt. %
* Löschen icon

Die folgenden Tabellenspalten können ausgewählt werden, werden aber nicht standardmäßig angezeigt:

* Menge
* Artikel-ID
* Varianten-ID
* Barcode
* Aufpreis gesamt = Die Summe der Aufschläge für Bestelleigenschaften.
* Kundenklassenrabatt = Der für den ausgewählten Verkaufspreis angewendete Kundenklassenrabatt in Prozent.
* Kategorierabatt = Der für den ausgewählten Verkaufspreis angewendete Kategorierabatt in Prozent.

Passe die Tabelle deinen Bedürfnissen und deinem Arbeitsablauf an. Wenn du die Tabelle angepasst hast, wird diese Auswahl gespeichert. Die Tabelle ist jederzeit anpassbar.

[.instruction]
Tabelle individualisieren:

. Klicke auf *Spalten konfigurieren* (material:settings[]). +
→ Das Fenster *Spalten konfigurieren* öffnet sich.
. Wähle aus, welche Spalten angezeigt werden sollen.
. Verschiebe (material:sort[]) die Spalten, so dass sie in der Reihenfolge angezeigt werden, in der du sie brauchst.
. Klicke auf *Bestätigen*, um deine Auswahl zu speichern.

--

Wenn du Änderungen an Versandkosten oder der Versandart vornimmst, müssen *Neuberechnungen* ausgeführt werden, da die Preiskalkulation von diesen Faktoren abhängig ist. Bevor du den Auftrag abschließen kannst, musst du daher auf *Auftrag neu berechnen* klicken. Durch die Neuberechnung passen sich die Gesamtsummen an. Um danach den Auftrag fertigzustellen, klicke auf *Auftrag anlegen*. Der Auftrag ist nun erstellt und du wirst zur Auftragsübersicht des Kontaktes weitergeleitet. Der Auftrag ist in der allgemeinen Auftragsübersicht im Menü *Aufträge » Aufträge (Testphase)* verfügbar.

[#create-and-apply-order-templates]
== Auftragsvorlagen erstellen und anwenden

Im Menü *Einrichtung » Aufträge » Auftragsvorlage* kannst du Auftragsvorlagen erstellen. Diese kannst du dann beim Anlegen eines manuellen Auftrags auswählen oder über eine xref:automatisierung:ereignisaktionen.adoc#intable-auftragsvorlage[Ereignisaktion] auf einen Auftrag anwenden lassen. Wählst du eine Auftragsvorlage für einen Auftrag aus, werden die dort hinterlegten Daten auf den Auftrag angewendet. Du kannst nach Verwendung einer Auftragsvorlage Aufträge wie üblich bearbeiten und auch Auftragsinformationen ändern und anpassen.

Gehe folgendermaßen vor, um eine Auftragsvorlage zu erstellen:

[.instruction]
Auftragsvorlage erstellen:

. Öffne das Menü *Einrichtung » Aufträge » Auftragsvorlage*.
. Wechsele in das Tab *Neue Vorlage*.
. Trage einen eindeutigen *Namen* ein.
. Wähle aus der jeweiligen Dropdown-Liste *Zahlungsart* und *Auftragsstatus* aus.
. Füge über *Artikel hinzufügen* optional Artikel hinzu.
. Speichere (icon:save[role="green"]) die Auftragsvorlage.

[[table-order-templates]]
.Datenfelder Auftragsvorlage
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Name*
|Gib einen Namen für die Auftragsvorlage ein. Dieser wird dann in Dropdown-Listen zur Auswahl der Auftragsvorlage angezeigt.

|*Zahlungsart*
|Wähle eine Zahlungsart aus der Dropdown-Liste aus. Diese Zahlungsart wird dann bei Anwendung der Vorlage dem entsprechenden Auftrag hinzugefügt.

|*Auftragsstatus*
|Wähle einen Auftragsstatus aus der Dropdown-Liste aus. Bei Anwendung der Vorlage auf einen Auftrag wird dieser Auftrag dann in diesen Auftragsstatus geschoben.

|*Artikel*
|Hast du der Auftragsvorlage Artikel hinzugefügt, werden dir diese Artikel in der Tabelle angezeigt. Das Hinzufügen von Artikeln ist optional. Die hier angezeigten Artikel werden bei Anwendung der Auftragsvorlage zum Auftrag hinzugefügt. Du siehst zudem pro Artikel die Menge und den Artikeltext. Außerdem kannst du in der Tabelle Artikel aus der Auftragsvorlage löschen. +
*_Beachte:_* Bei Anwendung einer Auftragsvorlage mit Artikeln sollten dem Auftrag noch keine Artikel hinzugefügt worden sein. Bereits vorher vorhandene Artikel werden überschrieben. Du kannst aber nach Anwendung der Auftragsvorlage weitere Artikel zum Auftrag hinzufügen.

|*Artikel hinzufügen*
|In diesem Tab kannst du optional Artikel zur Auftragsvorlage hinzufügen. Diese Artikel werden dann bei Anwendung der Auftragsvorlage zum Auftrag hinzugefügt. +
Setze Filter und führe eine Suche (icon:search[role="blue"]) aus, um Artikel anzeigen zu lassen. Füge (icon:cart-plus[role="green"]) die gewünschten Artikel zur Auftragsvorlage hinzu. Diese werden dir dann im Tab *Artikel* angezeigt. +
*Menge* = Du kannst Artikel mehrmals hinzufügen. Dann werden sie jeweils in einer neuen Tabellenzeile angezeigt. Alternativ kannst du im Tab *Artikel* in der Spalte *Menge* die Menge eines Artikels anpassen.

|====

Du kannst Auftragsvorlagen jederzeit bearbeiten und anpassen. Nach jeder Änderung musst du die Auftragsvorlage speichern (icon:save[role="green"]). Änderungen an Auftragsvorlagen werden nicht rückwirkend auf Aufträge angewendet sondern gelten nur ab dem Zeitpunkt der Änderung.

Auftragsvorlagen werden nur auf einen Auftrag angewendet, wenn du dies bestimmst. Möchtest du eine Auftragsvorlage immer auf bestimmte Aufträge anwenden, empfehlen wir die Einrichtung einer entsprechenden xref:automatisierung:ereignisaktionen.adoc#intable-auftragsvorlage[Ereignisaktion]. Lege in der Ereignisaktion durch Auswahl eines Ereignisses und durch Filter fest, wann und auf welche Aufträge welche Auftragsvorlage angewendet werden soll.

Möchtest du eine Auftragsvorlage bei der manuellen Erstellung eines Auftrags anwenden, wähle im Bereich *Auftragsdaten* aus der Dropdown-Liste *Vorlage verwenden* die gewünschte Auftragsvorlage aus. In der neuen Auftragsanlage (Beta) kannst du im ersten Schritt der Auftragsanlage die Vorlage aus der Dropdown-Liste *Auftragsvorlage* über den Auftragsdetails auswählen.
