= Aufträge manuell anlegen
:keywords: Aufträge manuell anlegen, Aufträge über Kontakt anlegen, manuelle Auftragsanlage
:author: team-order-core
:description: Erfahre, wie du Aufträge oder Angebote manuell in drei Schritten anlegst. Dies ist über einen Barverkauf, über Aufträge oder über Kontakte möglich.

Wie du Aufträge im System anlegst, z.B. wenn eine Bestellung per Telefon getätigt wird, ist auf dieser Seite beschrieben. Die folgenden Möglichkeiten stehen dir für die Auftragsanlage in plentymarkets zur Verfügung:

* Über einen <<#create-order-via-cash-sale, Barverkauf>>
* Über <<#create-order-via-order, Aufträge>>
* Über <<#create-order-via-contact, Kontakte>>

*_Tipp:_* Die Vorgehensweise für Angebote ist identisch. Wähle im ersten Schritt der Auftragsanlage für die Einstellung *Auftragstyp* die Option *Angebot*, um ein Angebot zu erstellen.

[IMPORTANT]
.E-Mail-Versand
====
Bei manuell angelegten Aufträgen wird keine automatische E-Mail, z.B. als Auftragsbestätigung, an Kund:innen versendet. Grund dafür ist, dass das System nicht wissen kann, wann die Einstellungen zu diesem Auftrag vorgenommen wurden. Stoße daher den Versand einer xref:crm:emailbuilder.adoc#[E-Mail-Vorlage] manuell im Auftrag über die Funktion *E-Mail-Service* an.
====

[#create-order-via-cash-sale]
== Auftrag oder Angebot über Barverkauf anlegen

Im Menü *CRM » Kontakte* hast du die Möglichkeit, Barverkäufe über das Kundenprofil *Barverkauf* abzuwickeln. Das Kundenprofil *Barverkauf* erlaubt dir, Aufträge ohne Kundenzuordnung anzulegen. Das Kundenprofil *Barverkauf* ist in deinem System standardmäßig eingerichtet.

[WARNING]
.Zahlungsart und Auftragsdokumente bei Barverkäufen
====
Achte darauf, bei der Auftragsanlage über Barverkauf in den *Auftragsdaten* die passende *Zahlungsart* auszuwählen. Zudem findet bei dieser Art der Auftragsanlage keine Zuordnung zu einem in deinem System gespeicherten Kund:innen statt. Generiere deshalb die benötigten xref:auftraege:auftragsdokumente-neu.adoc#[Auftragsdokumente], wie die Rechnung, direkt während der Abwicklung des Barverkaufs manuell im Bereich *Dokumente* des Auftrags.
====

[.instruction]
Auftrag oder Angebot über Barverkauf anlegen:

. Öffne das Menü *CRM » Kontakte*.
. Gib im Suchfeld *ID* die gewünschte ID ein. +
→ Eine Liste der Suchergebnisse wird eingeblendet.
. Wähle *Barverkauf* aus der *Ergebnisliste*. +
→ Das Kundenprofil für Barverkäufe mit der gesuchten ID wird geöffnet.
. Gehe in den Bereich *Aufträge*.
. Klicke rechts auf *Optionen* (material:add[]).
. Wähle die Option *Neuer Auftrag* oder *Neues Angebot*. +
→ Die Übersicht zum Erstellen eines neuen Auftrags oder eines neuen Angebots wird geöffnet.
. Nimm die Einstellungen vor. Beachte dazu die Erläterungen zur <<#create-order-or-offer, Anlage von Aufträgen oder Angeboten>>.

[#create-order-via-order]
== Auftrag oder Angebot über Aufträge anlegen

Im Menü *Aufträge » Aufträge (Testphase)* kannst du sowohl in der Auftragsübersicht als auch in der Detailansicht eines Auftrags neue Aufträge oder Angebote anlegen. Gehe dazu vor wie folgt. Beachte, dass das Öffnen eines Auftrags nur in der Listenansicht möglich ist.

[.instruction]
Auftrag oder Angebot über Aufträge anlegen:

. Öffne das Menü *Aufträge » Aufträge (Testphase)*.
. Führe die Suche (material:search[]) aus, um Aufträge anzuzeigen.
. Klicke links in der Seitennavigation auf (material:add[role=skyBlue]) *Neuer Auftrag*. +
*_Tipp:_* Möchtest du anstatt eines Auftrags ein Angebot anlegen, wähle im ersten Schritt für den *Auftragstyp* die Option *Angebot*. +
icon:map-signs[] *_Oder:_* Öffne in der Auftragsübersicht den Auftrag der Kund:in, für die du einen neuen Auftrag anlegen möchtest. Beachte, dass Aufträge nur in der Listenansicht geöffnet werden können.
. Klicke unten in der Seitennavigation auf die *Kontakt-ID*. +
→ Der Auftrag wird im Menü *CRM » Kontakte* geöffnet.
. Gehe in den Bereich *Aufträge*.
. Klicke rechts auf *Optionen* (material:add[]).
. Wähle die Option *Neuer Auftrag* oder *Neues Angebot*. +
→ Die Übersicht zum Erstellen eines neuen Auftrags oder eines neuen Angebots wird geöffnet.
. Nimm die Einstellungen vor. Beachte dazu die Erläterungen zur <<#create-order-or-offer, Anlage von Aufträgen oder Angeboten>>.

[#create-order-via-contact]
== Auftrag oder Angebot über Kontakte anlegen

Aufträge oder Angebote kannst du auch über die Kontaktübersicht oder die Detailansicht eines Kontakts im Menü *CRM » Kontakte* anlegen. Nimm dazu zunächst die <<#carrying-out-standard-settings, Standardeinstellungen>> vor.

[.instruction]
Auftrag oder Angebot über Kontakte anlegen:

. Öffne das Menü *CRM » Kontakte*.
. Suche den Kontakt anhand der Filtereinstellungen. Beachte dazu die Erläuterungen zu den Filtern auf der Seite xref:crm:kontakt-suchen.adoc#[Kontakt suchen]. +
→ Die Kontakte, die den Suchkriterien entsprechen, werden angezeigt.
. Klicke in der Zeile des Kontakts rechts auf material:more_vert[].
. Navigiere zu material:shopping_cart[] *Aufträge* > *Neuer Auftrag* oder *Neues Angebot*. +
icon:map-signs[] *_Oder:_* Öffne einen Kontakt.
. Klicke im Bereich *Aufträge* rechts auf material:add[] *Optionen*.
. Navigiere zu *Neuer Auftrag* oder *Neues Angebot*.
→ Du wirst automatisch zu den Auftragsdetails für den neuen Auftrag bzw. das neue Angebot weitergeleitet.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen zur <<#create-order-or-offer, Anlage von Aufträgen oder Angeboten>>.

[#carrying-out-standard-settings]
=== Standardeinstellungen vornehmen

Beim Anlegen von Aufträgen und Angeboten über die Kontaktübersicht werden Daten, wie zum Beispiel Adressen oder Mandanten, direkt aus dem Kontakt übernommen, wenn sie dort hinterlegt sind. Die Kontaktdaten haben in der Regel also Priorität. Zusätzlich stehen dir einige Standardeinstellungen zur Verfügung, auf die zurückgegriffen wird, wenn eine Information nicht aus dem Kontakt genommen wird. +
Um die Auftragsanlage zu erleichtern und schneller vorgehen zu können, solltest du zunächst diese Standardeinstellungen festlegen. +
*_Hinweis:_* Die Standardeinstellungen gelten auch für Angebote, die über die Kontakt-UI angelegt wurden.

[.instruction]
Standardeinstellungen vornehmen:

. Öffne das Menü *Einrichtung » Aufträge » Auftragstypen » Auftrag*.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<table-default-settings-order-contact>>.
. *Speichere* (material:save[role=green]) die Einstellungen.

[[table-default-settings-order-contact]]
.Standardeinstellungen für die Auftragsanlage
[cols="1,3"]
|===
|Einstellung |Erläuterung

|[#intable-standard-eigner]*Standard-Eigner*
|Wählst du einen Standard-Eigner, ist dieser Eigner in den Auftragsdetails des neuen Auftrags oder des Angebots standardmäßig vorausgewählt. Der Eigner wird generell nicht aus den Kontaktdaten übernommen.

|[#intable-standard-mandant]*Standard-Mandant*
|Der hier ausgewählte Standard-Mandant ist beim Anlegen des neuen Auftrags oder Angebots vorausgewählt, wenn in den Kontaktdaten kein Mandant hinterlegt ist. Ist in den Kontaktdaten ein Mandant hinterlegt, hat dieser Mandant Priorität.

|[#intable-standard-herkunft]*Standard-Herkunft*
|Die hier ausgewählte Standard-Herkunft ist beim Anlegen des neuen Auftrags oder des Angebots vorausgewählt, wenn in den Kontaktdaten keine Herkunft hinterlegt ist. Ist in den Kontaktdaten eine Herkunft hinterlegt, hat diese Herkunft Priorität.

|[#intable-standard-lager]*Standard-Lager*
|Das hier ausgewählte Standard-Lager ist beim Anlegen des neuen Auftrags oder des Angebots vorausgewählt, wenn in den Kontaktdaten kein Lager hinterlegt ist. Ist in den Kontaktdaten ein Lager hinterlegt, hat dieses Lager Priorität.

|[#intable-standard-vorlage]*Standard-Auftragsvorlage*
|Wählst du eine <<#create-and-apply-order-templates, Auftragsvorlage>> als Standard-Auftragsvorlage, ist diese für den neuen Auftrag oder das Angebot standardmäßig vorausgewählt. Die Werte der ausgewählten Auftragsvorlage werden dann automatisch für den Auftrag oder das Angebot übernommen. Es können nur bereits angelegte Auftragsvorlagen ausgewählt werden. +
Standardmäßig ist *Keine Auftragsvorlage vorausgewählt* gesetzt. Wählst du eine Auftragsvorlage als Standard und wird diese zu irgendeinem Zeitpunkt gelöscht, wird als Standard für diese Einstellung wieder *Keine* gesetzt.

|[#intable-endpoint-after-completion]*Endpunkt nach Abschluss eines Auftrags*
|Wähle, wohin im System du nach Abschluss eines Auftrages geleitet werden möchtest. Du kannst wählen zwischen: +
*Aktuelle Ansicht* = Leitet dich zur Auftragsansicht des Kontakts, für den du den Auftrag angelegt hast. Dies ist die Standardeinstellung. +
*Auftragsübersicht* = Leitet dich zur allgemeinen Auftragsübersicht. +
*Detailansicht des neuen Auftrags* = Leitet dich zur Detailansicht des gerade erstellten Auftrags.

|*Filteroption ‚Nur vorrätige Artikel anzeigen‘ in der Artikelsuche vorausgewählt*
|Aktiviere diese Option, damit sie für die Artikelsuche vorausgewählt ist. In den Suchergebnissen werden dann nur Artikel angezeigt, die einen physischen Warenbestand haben.

|*Filteroption ‚Nur Vertriebslager anzeigen‘ in der Artikelsuche vorausgewählt*
|Aktiviere diese Option, damit sie für die Artikelsuche vorausgewählt ist. In den Suchergebnissen werden dann nur Artikel angezeigt, die in Vertriebslagern gelagert werden.

|*Filteroption ‚Nur aktive Artikel anzeigen‘ in der Artikelsuche vorausgewählt*
|Aktiviere diese Option, damit sie für die Artikelsuche vorausgewählt ist. In den Suchergebnissen werden dann nur xref:artikel:checkliste-artikel-anzeige.adoc#100[aktivierte Artikel] angezeigt.

|*Filteroption ‚Nur Artikel mit gültigem Preis anzeigen‘ in der Artikelsuche vorausgewählt*
|Aktiviere diese Option, damit sie für die Artikelsuche vorausgewählt ist. In den Suchergebnissen werden dann nur Artikel angezeigt, für die ein gültiger Preis hinterlegt ist.

|*Änderung der Mehrwertsteuersätze in der Artikelübersichtstabelle im letzten Schritt der Auftragserstellung erlauben.*
|Durch Aktivierung dieser Option erlaubst du, dass vor dem Abschluss des Auftrags im letzten Schritt der Auftragsanlage Steuersätze geändert werden dürfen. Die Steuersätze richten sich dabei nach der Lieferadresse des Auftrags. +
Diese Option ist standardmäßig deaktiviert. Lasse sie deaktiviert, wenn du die Mehrwertsteuersätze in der Übersicht nur sichtbar, aber nicht bearbeitbar lassen möchtest.

|*Anzeige von hinzugefügten Artikeln im Warenkorb*
|Wähle, wie die Artikel zum Warenkorb hinzugefügt werden sollen. Die Standardeinstellung ist *Als eine Auftragsposition, Mengen werden erhöht*. +
*Als separate Auftragspositionen* = Auch gleiche Artikel werden einzeln hinzugefügt, d.h. jeder Artikel wird in einer eigenen Zeile dargestellt. +
*Als eine Auftragsposition, Mengen werden erhöht* = Gleiche Artikel werden in einer Auftragsposition zusammengefasst und die Menge wird entsprechend angepasst.

|*Bei Auftragserstellung Preise nur im Warenkorb neu ermitteln*
|Durch Aktivierung dieser Option legst du fest, dass Preise von Artikeln nur dann neu ermittelt werden, wenn sie in den Warenkorb gelegt werden. Standardmäßig werden Preise schon in der Artikelsuche innerhalb der Auftragsanlage ermittelt und sind dort wählbar.

|===

[#create-order-or-offer]
== Auftrag oder Angebot anlegen

Egal für welchen der oben beschriebenen Wege du dich entscheidest - die Anlage eines neuen Auftrags oder Angebots verläuft immer in drei Schritten. Im ersten Schritt werden <<#step-one-basics, Auftragsdetails erfasst>>, im zweiten Schritt werden <<#step-two-add-items, Artikel hinzugefügt>> und im dritten Schritt wird der <<#step-three-summary, Auftrag abgeschlossen>>. Wähle zunächst aus den Kontakten, für wen der Auftrag oder das Angebot angelegt werden soll.

Oberhalb der Auftragsdetails kannst du aus der Dropdown-Liste auch nachträglich zwischen Auftrag und Angebot wählen. Zudem kannst du optional eine <<create-and-apply-order-templates, Auftragsvorlage>> aus der Dropdown-Liste wählen, die auf diesen Auftrag angewendet werden soll. In der Standardeinstellung ist hier keine Auftragsvorlage ausgewählt.

Die im Folgenden beschriebenen Schritte sind für Aufträge und Angebote gleich.

Die Ansichten der Benutzeroberfläche sind so gestaltet, dass sich Aufträge schnell und übersichtlich anlegen lassen. Dies ist vor allem bei der telefonischen Aufnahme von Bestellungen von Vorteil. Zunächst werden die Auftragsdetails wie z.B. Adressen oder die Zahlungsart abgefragt. Danach werden dem Auftrag Artikel hinzugefügt, um ihn im letzten Schritt zu überprüfen und anzulegen.

[TIP]
.Name, ID und Bewertung des Kontakts auf einen Blick
======
Unten links in der Fußzeile der Auftragsanlage kannst du den Namen, die ID sowie die Bewertung des Kontaks sehen.
======

[#step-one-basics]
=== Schritt 1: Auftragsdetails / Angebotsdetails

Wenn der neue Auftrag oder das neue Angebot über die Kontaktübersicht angelegt wird, werden in den Auftrags- bzw. Angebotsdetails bereits einige der im Kontakt hinterlegten Daten übernommen. Welche Informationen übernommen werden, hängt davon ab, welche Daten im Kontakt gespeichert sind. Ansonsten greifen die <<#carrying-out-standard-settings, Standardeinstellungen>>. Beachte dazu auch <<#table-order-details-new-order, diese Tabelle>>.

[[table-order-details-new-order]]
.Allgemeine Einstellungen
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Auftragstyp*
|Wähle aus der Dropdown-Liste, ob du einen *Auftrag* oder ein *Angebot* erstellen möchtest.

| *Auftragsvorlage*
|Wähle die Vorlage des Auftrags aus der Dropdown-Liste.

| *Kontakt*
|Wenn du den Auftrag über das Menü *CRM » Kontakte* anlegst, ist hier der Name des Kontakts bereits vorausgewählt. Möchtest du einen anderen Kontakt wählen, gib mindestens 3 Buschstaben ein, um Vorschläge zu sehen. Alternativ kannst du auch die E-Mail-Adresse des Kontakts eingeben. Alle am Kontakt hinterlegten Daten werden automatisch in die anderen Felder eingefügt. +
*_Tipp:_* Möchtest du einen Auftrag als Gast anlegen, wähle die Option *Gast* aus der Dropdown-Liste und füge im Anschluss eine neue *Rechnungsadresse* sowie eine neue *Lieferadresse* hinzu.

2+^| *Auftragsdetails*

| *Rechnungsadresse*
|Die im Datensatz des Kontaktes hinterlegte Rechnungsadresse wird übernommen. Sind mehrere Rechnungsadressen hinterlegt, wird die als primär definierte Rechnungsadresse übernommen. Wenn keine Rechnungsadresse als primäre Adresse definiert ist, kann man aus der Dropdown-Liste die gewünschte Adresse wählen. +
Über die Vorschau (material:visibility[]) gelangst du direkt in den Kontaktatensatz. Die bereits gewählten Einstellungen in den Auftragsdetails gehen nicht verloren. +
Legst du den Auftrag als *Gast* an, füge hier eine neue Rechnungsadresse hinzu.

| *Lieferadresse*
|Wenn du in der Box *Wie Rechnung* ein Häkchen setzt, wird die unter *Rechnungsadresse* eingegebene Adresse auch als Lieferadresse übernommen. Ansonsten wird die im Datensatz des Kontakts hinterlegte Lieferadresse übernommen. Sind mehrere Lieferadressen hinterlegt, wird die als primär definierte Lieferadresse übernommen. Wenn keine Lieferadresse als primäre Adresse definiert ist, kann man aus der Dropdown-Liste die gewünschte Adresse wählen. +
In der Dropdown-Liste hast du auch die Möglichkeit, eine neue Lieferadresse einzugeben und im Kontaktdatensatz zu speichern. Beachte dazu die Erläuterungen in der ausklappbaren Box am Ende dieses Abschnitts. +
Über die Vorschau (material:visibility[]) gelangst du direkt in den Kontaktdatensatz. Die bereits gewählten Einstellungen in den Auftragsdetails gehen nicht verloren. +
Legst du den Auftrag als *Gast* an, füge hier eine neue Lieferadresse hinzu.

| *Zahlungsart*
|Wenn im Kontakt eine Zahlungsart definiert ist, zum Beispiel über eine xref:crm:vorbereitende-einstellungen.adoc#kundenklasse-erstellen[Kundenklasse], ist diese vorausgewählt. Ansonsten kannst du eine Zahlungsart eingeben und dann wählen. Angeboten werden dir alle Zahlungsarten, die bereits in deinem plentymarkets System integriert sind. +
Nutzt du eine <<#create-and-apply-order-templates, Auftragsvorlage>>, wird die Zahlungsart der Auftragsvorlage verwendet, sobald du die Vorlage für den Auftrag wählst. Danach ist die Zahlungsart manuell anpassbar.

| *Währung*
|Die xref:payment:waehrungen.adoc#30[Systemwährung] ist vorausgewählt. Über die Dropdown-Liste kannst du die Währung für den Auftrag anpassen.

| *Rabatt in %*
|Hier kannst du manuell einen prozentualen Rabatt eingeben, der auf alle Auftragspositionen des Auftrags angewendet wird. Der eingegebene Wert muss zwischen 0 und 100 liegen, Werte im Minusbereich sind nicht erlaubt. +
Es ist ein Rabatt voreingetragen, wenn der Kontakt zu einer Kundenklasse gehört, in der die Option *Standardrabatt für manuelle Aufträge* mit einem Wert gefüllt ist. Du findest diese Option im Bereich xref:crm:vorbereitende-einstellungen.adoc#intable-customer-class-discount-type[Rabattart] im Menü *Einrichtung » CRM » Kundenklassen*. Den voreingetragenen Wert in den Auftragsdetails kannst du anpassen.

| *Lager*
|Welche Optionen dir angezeigt werden, hängt von den Grundeinstellungen ab, die du für die xref:auftraege:preparatory-settings.adoc#intable-warehouse-assignment[Zuordnung von Lagern] gewählt hast: +
- Ist *a) pro Auftrag kann ein Lager zugeordnet werden* ausgewählt, kannst du in den Auftragsdetails aus einer Dropdown-Liste ein Lager für den Auftrag wählen oder den Namen eines Lagers eingeben, um danach zu suchen. +
Hast du im Menü *Einrichtung » Aufträge » Auftragstypen » Auftrag [Beta]* ein Standard-Lager gewählt, ist dieses Lager hier vorausgewählt.
- Ist *b) pro Artikelposition kann ein Lager zugeordnet werden* ausgewählt, wird dir *Abhängig von den Auftragspositionen* angezeigt. Im nächsten Schritt werden dem Auftrag Artikel hinzugefügt. Dort kannst du dann für jede Variante ein Lager aus einer Dropdown-Liste wählen. +
Hast du im Menü *Einrichtung » Aufträge » Auftragstypen » Auftrag [Beta]* ein Standard-Lager gewählt, ist dieses Lager im nächsten Schritt in der Artikeltabelle vorausgewählt.

| *Mandant*
|Wähle aus der Dropdown-Liste den Mandanten aus, für den dieser Auftrag gelten soll. Vorausgewählt ist entweder der Mandant aus den Kontaktdaten oder als nächste Option ein <<#intable-standard-mandant, Standard-Mandant>>, wenn du diesen festgelegt hast.

| *Eigner*
|Wähle den Eigner für den Auftrag aus der Dropdown-Liste. Hast du einen <<#intable-standard-eigner, Standard-Eigner>> gesetzt, ist dieser vorausgewählt. Ansonsten werden dir in der Dropdown-Liste nur Eigner angezeigt, die das Benutzerrecht haben, Aufträge zu erstellen und zu bearbeiten.

| *Auftragsherkunft*
|Wähle die Herkunft für den Auftrag aus der Dropdown-Liste. Vorausgewählt ist entweder die Herkunft aus den Kontaktdaten oder als nächste Option eine <<#intable-standard-herkunft, Standard-Herkunft>>, wenn du diese festgelegt hast. Darüber hinaus werden nur die xref:auftraege:auftragsherkunft.adoc#[Herkünfte] angezeigt, die aktiv geschaltet sind.

| *Skonto (%)*
|Gib das Skonto, d.h. den Wert in Prozent, der bei Einhaltung der Skontofrist (Tage) abgezogen wird, ein. +
Diese Einstellung ist nur für die Zahlungsarten *Rechnung* und *Vorkasse* verfügbar.

| *Skontofrist (Tage)*
|Gib die Skontofrist, d.h. die Anzahl der Tage ab Rechnungserstellung, in denen skontiert offene Forderungen bezahlt werden können, ein. +
Diese Einstellung ist nur für die Zahlungsarten *Rechnung* und *Vorkasse* verfügbar.

| *Valuta (Tage)*
|Gib das Valutadatum, d.h. den Zeitraum ab Rechnungserstellung, bevor der Zeitraum des Zahlungsziels beginnt, ein. +
Diese Einstellung ist nur für die Zahlungsarten *Rechnung* und *Vorkasse* verfügbar.

| *Zahlungsziel (Tage)*
|Gib das Zahlungsziel, d.h. die Frist für die Zahlung in Tagen, ein. +
Diese Einstellung ist nur für die Zahlungsarten *Rechnung* und *Vorkasse* verfügbar.

|====

[.collapseBox]
.*Neue Lieferadresse anlegen*
--

Von der Dropdown-Liste im Feld *Lieferadresse* aus kannst du nicht nur eine bestehende Lieferadresse wählen, du kannst auch eine neue Adresse anlegen. Um eine neue Lieferadresse anzulegen, gehe wie im Folgenden beschrieben vor. +
*_Tipp:_* Für eine neue Rechnungsadresse sind die Einstellungen identisch. +
*_Hinweis:_* Wählst du oben in den Adressangaben der Lieferadresse die Option *DHL Packstation* oder *DHL Postfiliale*, werden die Eingabefelder für die Lieferadresse entsprechend angepasst.

[.instruction]
Neue Lieferadresse anlegen:

. Wähle aus der Dropdown-Liste *Lieferadresse* die Option *(material:add[]) Neue Lieferadresse hinzufügen*. +
→ Das Fenster *Neue Lieferadresse hinzufügen* wird geöffnet.
. Wähle, ob es sich um die *Primäre* Lieferadresse handelt.
. Gib die Daten ein. Beachte hierzu <<#table-new-delivery-address>>.
. *Speichere* die neue Adresse.

Nach dem Speichern wird die neue Lieferadresse in den entsprechenden Kontaktdatensatz übernommen. Für den neuen Auftrag ist sie nach dem Anlegen im Feld *Lieferadresse* ausgewählt.

[[table-new-delivery-address]]
.Auftragsdetails: Neue Lieferadresse anlegen
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Primär*
|Aktiviere die Option, wenn es sich bei der neuen Adresse um die primäre Lieferadresse handelt. Bei Aktivierung wird diese Lieferadresse beim Anlegen neuer Aufträge automatisch in den neuen Auftrag übernommen.

|*Anrede*
|Wähle optional eine Anrede aus der Dropdown-Liste.

|*Firma (Name 1)*
|Gib den Firmenname ein. Wenn unter *Vorname* und *Nachname* kein Eintrag gemacht wurde, ist dies ein Pflichtfeld.

|*Vorname (Name 2)*
|Gib den Vorname des Kontakts ein. Wenn unter *Firma* und *Nachname* kein Eintrag gemacht wurde, ist dies ein Pflichtfeld.

|*Nachname (Name 3)*
|Gib den Nachname des Kontakts ein. Wenn unter *Firma* und *Vorname* kein Eintrag gemacht wurde, ist dies ein Pflichtfeld.

|*Zusatz (Name 4)*
|Gib optional Zusatzangaben zum Kontakt ein, wie z.B. _z. Hd. Herrn Max Mustermann_.

|*Adresse 1 (Straße)* +
*Adresse 2 (Hausnummer)*
|Gib die Straße und Hausnummer ein. +
*Straße* ist ein Pflichtfeld, wenn unter *Hausnummer* und *Adresszusatz* kein Eintrag gemacht wurde. *Hausnummer* ist ein Pflichtfeld, wenn unter *Straße* und *Adresszusatz* kein Eintrag gemacht wurde. +
*_Hinweis:_* Hast du oben in den Adressangaben der Lieferadresse die Option *DHL Packstation* oder *DHL Postfiliale* gewählt, wird das Feld *DHL Packstation* bzw. *DHL Postfiliale* hier entsprechend sichtbar. Gib in diesem Fall die Adresse der Packstation bzw. der Postfiliale ein.

|*Adresse 3 (Adresszusatz)*
|Gib optional einen Adresszusatz ein, wie z.B. _Appartement 12a_. Wenn unter *Straße* und *Hausnummer* kein Eintrag gemacht wurde, ist dies ein Pflichtfeld.

|*Adresse 4 (Frei)*
|Dies ist ein Feld zur freien Verfügung.

|*Postleitzahl* +
*Ort*
|Gib die Postleitzahl und den Ort des Kontakts ein. *Ort* ist ein Pflichtfeld. +
Bei bestimmten Ländern, z.B. Vereinigtes Königreich, wird die Reihenfolge der Optionen *Postleitzahl* und *Ort* getauscht.

|*Land* +
*Region/Bezirk*
|Wähle Werte aus den Dropdown-Listen. +
*_Beachte:_* Die Dropdown-Liste *Region/Bezirk* ist nicht für alle Länder verfügbar.

|*E-Mail*
|Gib optional eine E-Mail-Adresse ein.

|*Telefon*
|Gib optional eine Telefonnummer ein.

|*Typ* und *Wert*
|Wähle einen Typ aus der Dropdown-Liste. Zur Verfügung stehen: Umsatzsteuernummer, Externe Adress-ID, Gelangensbestätigung, Postnummer, Personennummer, FSK, Geburtstag, Titel, Ansprechpartner, Externe Kunden-ID. Gib den passenden *Wert* für den ausgewählten Typ ein. +
Über *Adressoption hinzufügen* kannst du weitere *Typen* mit den dazugehörigen *Werten* hinzufügen.

|====

--

Nachdem du alle Einstellungen vorgenommen hast, gehe zum nächsten Schritt weiter, indem du unten auf *ARTIKEL HINZUFÜGEN* klickst. Alternativ kannst du auch oben auf den Schritt *Artikel hinzufügen* klicken. Die Auftragsdetails werden gespeichert und du wirst zum nächsten Arbeitsschritt geleitet. In diesem Schritt fügst du dem Auftrag Artikel hinzu.

[#step-two-add-items]
=== Schritt 2: Artikel hinzufügen

Sobald du alle Auftragsdetails in Schritt 1 eingetragen hast, kannst du nun in einem weiteren Schritt deine gewünschten Artikel zum Auftrag hinzufügen. In diesem Schritt werden die Auftragsdetails nicht angezeigt. Erst im dritten Schritt sind die Auftrags- bzw. Angebotsdetails wieder verfügbar. *_Beachte_* allerdings, dass dort nur wenige Einstellungen bearbeitet werden können.

[.collapseBox]
.*Artikeltabelle individualisieren*
--

Die Artikeltabelle kann individuell gestaltet werden. Das bedeutet, dass du selbst entscheiden kannst, welche Informationen dir in den Tabellenspalten angezeigt werden und in welcher Reihenfolge sie platziert sind. Um die Tabelle anzupassen, gehe vor wie folgt.

[.instruction]
Tabelle individualisieren:

. Klicke auf *Spalten konfigurieren* (material:settings[]). +
→ Das Fenster *Spalten konfigurieren* wird geöffnet.
. Wähle, welche Spalten angezeigt werden sollen. Beachte dazu die Einstellungen in <<table-overview-item-search>>.
. Verschiebe (material:drag_indicator[]) die Spalten so, dass sie in der gewünschten Reihenfolge angezeigt werden.
. Klicke auf *Bestätigen*, um deine Auswahl zu speichern.

Wenn du die Tabelle einmal angepasst hast, wird diese Auswahl gespeichert. Die Tabelle bleibt also gleich, auch wenn du diesen Auftrag abgeschlossen hast und weitere Aufträge anlegst. Du kannst das Layout jederzeit ändern. Die zur Verfügung stehenden Spalten findest du in <<table-overview-item-search>>. Dort ist zu jeder Spalte auch die Information hinterlegt, ob es sich um eine Standardspalte handelt. Standardspalten werden angezeigt, wenn die Tabelle nicht individualisiert ist.

[[table-overview-item-search]]
.Tabellenspalten Artikel
[cols="1,3"]
|===
|Einstellung |Erläuterung

|*Bestandsanzeige*
|Ein roter Statusbalken zeigt an, wenn kein Nettobestand für einen Artikel verfügbar ist. Der rote Statusbalken wird nicht angezeigt, wenn Nettobestand für den Artikel vorhanden ist. Wenn du zum Beispiel *Nur vorrätige Artikel anzeigen* ausgewählt hast, wird kein roter Statusbalken angezeigt. Der Statusbalken wird erst rot, wenn der Bestand während des Hinzufügens von Artikeln unter 0 sinkt. +
Diese Spalte ist eine Standardspalte.

|*Status*
|In dieser Spalte wird angezeigt, ob diese Variante im Webshop aktiv oder inaktiv ist. Informationen zur Aktivierung oder Deaktivierung einer Variante findest du auf der Handbuchseite xref:artikel:checkliste-artikel-anzeige.adoc#100[Hast du die Variante aktiviert?]. +
Diese Spalte ist eine Standardspalte.

|*Artikel-ID*
|Zeigt die ID des Artikels an. Wenn du auf die Artikel-ID klickst, gelangst du direkt in die Einstellungen des jeweiligen Artikels. +
Diese Spalte ist eine Standardspalte.

|*Varianten-ID*
|Zeigt die Varianten-ID an. Wenn du auf die Varianten-ID klickst, gelangst du direkt in die Einstellungen der Variante. +
Diese Spalte ist eine Standardspalte.

|*Artikel-ID/Varianten-ID*
|Zeigt die Artikel-ID und die Varianten-ID kombiniert und nicht in zwei separaten Spalten an. Wenn du auf die Artikel-ID oder die Varianten-ID klickst, gelangst du direkt in die Einstellungen des jeweiligen Artikels bzw. der Variante. +
Diese Spalte ist eine Standardspalte.

|*Variantennummer*
|Zeigt die Variantennummer an. Wenn du auf die Variantennummer klickst, gelangst du direkt in die Einstellungen der jeweiligen Variante. +
Diese Spalte ist eine optionale Spalte.

|*Artikelname*
|Zeigt den am Artikel hinterlegten Namen an. +
Diese Spalte ist eine Standardspalte.

|*Attribute*
|Zeigt die am Artikel hinterlegten Attribute an. +
Diese Spalte ist eine Standardspalte.

|*Variantenname*
|Zeigt den an der Variante hinterlegten Variantennamen an. +
Diese Spalte ist eine Standardspalte.

|*Barcode*
|Zeigt den Barcode des Artikels an. +
Diese Spalte ist eine Standardspalte.

| *System-EK*
|Zeigt den Einkaufspreis des Systems an. +
Diese Spalte ist eine Standardspalte.

|[#intable-item-search-price-selection]*Preisauswahl*
|In einer Dropdown-Liste werden dir alle für diesen Auftrag ermittelten Verkaufspreise angezeigt. Du kannst einen der angezeigten Preise wählen, der dann als Grundlage für die weiteren Auftragsberechnungen verwendet wird. Enthält der Preis einen Rabatt, wird dies hinter dem Preisnamen und dem Betrag angezeigt. Die Spalten *Kundenklassenrabatt* und *Kategorierabatt* zeigen den Prozentsatz des angewendeten Rabatts an. +
Eine manuelle Anpassung des Preises kannst du im <<#shopping-cart, Warenkorb>> vornehmen. Wählst du einen anderen Verkaufspreis als den ersten ermittelten, muss der Verkaufspreis aktualisiert werden. Klicke dafür auf *Verkaufspreis aktualisieren* (material:refresh[]). Nach der Aktualisierung ist die Warenkorb-Schaltfläche (material:add_shopping_cart[]) wieder verfügbar und die Artikel können hinzugefügt werden. Dies gilt auch für Mengenänderungen. +
Konnte kein gültiger Verkaufspreis ermittelt werden, wird *Kein gültiger Verkaufspreis* in der Dropdown-Liste angezeigt. Ohne gültigen Verkaufspreis kann der Auftrag nicht abgeschlossen werden. Lege daher den Artikel in den Warenkorb und passe den Preis dort manuell an. +
Diese Spalte ist eine Standardspalte.

| *Kategorierabatt*
|Zeigt den für den ausgewählten Verkaufspreis angewendeten Kategorierabatt in Prozent an. +
Diese Spalte ist eine Standardspalte.

| *Kundenklassenrabatt*
|Zeigt den für den ausgewählten Verkaufspreis angewendeten Kundenklassenrabatt in Prozent an. +
Diese Spalte ist eine Standardspalte.

| *Verfügbarkeit*
|Zeigt die Verfügbarkeit des Artikels an. +
Diese Spalte ist eine Standardspalte.

| *Netto-WB*
|Zeigt den Netto-Warenbestand des Artikels an. +
Diese Spalte ist eine Standardspalte.

| *Lager*
|Zeigt das Lager des Artikels an. Wähle bei Bedarf ein anderes Lager aus der Dropdown-Liste oder gib den Namen eines Lagers ein, um danach zu suchen. Beachte, dass dies nur möglich ist, wenn du für die *Zuordnung des Lagers* die Einstellung *b) Pro Artikelposition kann ein Lager zugeornet werden* gewählt hast. +
Hast du im Menü *Einrichtung » Aufträge » Auftragstypen » Auftrag [Beta]* ein Standard-Lager gewählt, ist dieses Lager hier vorausgewählt. +
Diese Spalte ist eine Standardspalte.

|*Menge*
|Gib die Menge ein, in der der Artikel dem Warenkorb hinzugefügt werden soll. Du kannst nur ganze Zahlen eingeben, negative Mengen oder Mengen, die den Nettobestand übersteigen, sind nicht erlaubt. In diesem Fall wird eine Fehlermeldung angezeigt. Wenn die hinzugefügte Menge den Nettobestand auf 0 oder niedriger setzt, wird der Statusbalken für die Bestandsanzeige auf rot gesetzt. +
Bei Mengenänderungen ändert sich der Verkaufspreis, daher muss der Verkaufspreis aktualisiert werden. Klicke dafür auf *Verkaufspreis aktualisieren* (material:refresh[]). Nach der Aktualisierung ist die Warenkorb-Schaltfläche (material:add_shopping_cart[]) wieder verfügbar und die Artikel können hinzugefügt werden. +
Diese Spalte ist eine Standardspalte.

|*Warenkorb-Symbol*
|Durch Klick auf den Warenkorb (material:add_shopping_cart[]) wird der Artikel in der ausgewählten *Menge* dem Warenkorb hinzugefügt. +
Diese Spalte ist eine Standardspalte.

|===

--

[#search-items]
==== Artikel suchen

Anhand der Suche (material:search[]) kannst du die gewünschten Artikel finden und dem Auftrag hinzufügen. Wenn du eine Suche ausführst, werden deine gewählten Sucheinstellungen oben als Chips dargestellt. Diese Sucheinstellungen kannst du speichern, um sie in Zukunft schneller und einfacher wieder verwenden zu können. +
Verwende eine der folgenden Möglichkeiten, um nach Artikeln zu suchen.

[.instruction]
Artikel suchen:

.. *_Möglichkeit 1:_* Klicke auf material:search[], um direkt eine Liste aller Artikel zu sehen.
.. *_Möglichkeit 2:_* Gib etwas in das Suchfeld ein und klicke auf einen der automatischen Vorschläge.
.. *_Möglichkeit 3:_* Klicke auf material:tune[], um die Suchergebnisse mit Hilfe von Filtern einzugrenzen.

Führe eine <<#search-items, Suche>> (material:search[]) aus, um die passenden Artikel zu finden und dem Auftrag hinzuzufügen. Nutze außerdem die in der folgenden Tabelle aufgeführten Filter, um die Suche weiter einzugrenzen. Beachte, dass deine zuvor vorgenommenen <<carrying-out-standard-settings, Standardeinstellungen>> bei der Suche greifen.

[[table-order-filters]]
.Filter für Auftragspositionen
[cols="1,3"]
|===
|Filter |Erläuterung

| *Volltext*
|Gib etwas ein, um eine Volltextsuche zu starten.

| *Artikel-ID*
|Gib eine ID ein, um nach Artikeln mit dieser ID zu filtern.

| *Artikelname*
|Gib einen Namen ein, um nach Artikeln mit diesem Namen zu filtern.

| *Variantennummer*
|Gib eine Variantennummer ein, um nach Artikeln mit dieser Variantennummer zu filtern. +
*_Tipp:_* Für diesen Filter ist auch eine Teilsuche möglich. Somit genügt es, wenn du lediglich die ersten Zeichen der Variantennummer eingibst, um danach zu suchen.

| *Varianten-ID*
|Gib eine Varianten-ID ein, um nach Artikeln mit dieser Varianten-ID zu filtern.

| *Barcode*
|Gib einen Barcode ein, um nach Artikeln mit diesem Barcode zu filtern.

| *Hersteller*
|Gib einen Hersteller ein, um nach Artikeln dieses Herstellers zu filtern.

| *Artikel-Tag*
|Gib ein Tag ein, um nach Artikeln mit diesem Tag zu filtern.

| *Nur vorrätige Artikel anzeigen*
|Aktiviere diese Option (material:done[role=skyBlue]), um nach vorrätigen Artikeln zu filtern.

| *Nur aktive Artikel anzeigen*
|Aktiviere diese Option (material:done[role=skyBlue]), um nach aktiven Artikeln zu filtern.

| *Nur Vertriebslager anzeigen*
|Aktiviere diese Option (material:done[role=skyBlue]), um nach Artikeln in Vertriebslagern zu filtern. +
*_Hinweis:_* Wenn du in den Grundeinstellungen die Lagereinstellung *a) pro Auftrag kann ein Lager zugeordnet werden* gewählt hast, steht dir die Option *Nur Vertriebslager anzeigen* nicht zur Verfügung, weil du das Lager bereits bestimmt hast.

| *Nur Artikel mit gültigem Preis anzeigen*
|Aktiviere diese Option (material:done[role=skyBlue]), um nach Artikeln mit gültigem Preis zu filtern.

|===

[#save-current-filter]
==== Aktuellen Filter speichern

. Führe eine Suche aus.
. Klicke auf *Gespeicherte Filter* (material:bookmarks[role=darkGrey]).
. Klicke auf material:bookmark_border[role=darkGrey] *Aktuellen Filter speichern*.
. Gib einen Namen ein und schalte die optionalen Einstellungen bei Bedarf ein (material:toggle_on[role=skyBlue]).
. Klicke auf *Speichern*. +
→ Die Filtereinstellungen erscheinen nun unter *Gespeicherte Filter* (material:bookmarks[role=darkGrey]).


[#use-saved-filters]
==== Gespeicherte Filter anwenden

. Klicke auf *Gespeicherte Filter* (material:bookmarks[role=darkGrey]).
. Klicke auf eine bereits erstellte Filtereinstellung. +
→ Die Suche wird ausgeführt und die verwendeten Sucheinstellungen werden oben als Chips dargestellt.

[#adding-items]
=== Artikel hinzufügen

Nachdem du mithilfe der Suche oder anhand von Filtern alle gewünschten Artikel gefunden hast, kannst du sie dem Auftrag hinzufügen. Gehe dazu vor wie folgt.

[.instruction]
Artikel hinzufügen:

. Suche (material:search[]) den gewünschten Artikel.
. Wähle den passenden Verkaufspreis aus der *Preisauswahl* Dropdown-Liste.
. Gib die Menge des Artikels ein, die dem Auftrag hinzugefügt werden soll.
. Nimmst du Preis- oder Mengenänderungen vor, gehe rechts in der jeweiligen Zeile in das Kontextmenü (material:more_vert[]) und aktualisiere den Verkaufspreis mit Klick auf *Verkaufspreise aktualisieren* (material:refresh[]). +
*_Tipp:_* Links oben in der Tabelle kannst du mit Klick auf *Verkaufspreise aktualisieren* (material:refresh[]) alle Preis- und Mengenänderungen auf einmal aktualisieren.
. Klicke am Ende der jeweiligen Zeile auf *Zum Warenkorb hinzufügen* (material:add_shopping_cart[]), um den Artikel zum Warenkorb hinzuzufügen.
. Wiederhole diese Schritte, um weitere Artikel hinzuzufügen.
. Wenn alle Artikel hinzugefügt wurden, gehe zum nächsten Schritt, indem du auf *Auftrag erstellen* bzw. *Angebot erstellen* klickst. +
→ Der Warenkorb wird gespeichert und du wirst zum letzten Schritt weitergeleitet.

[#shopping-cart]
=== Warenkorb bearbeiten

In der Tabelle des Warenkorbs kannst du sowohl den *Artikelnamen* als auch die *Menge* und den *Verkaufspreis* anpassen. Sobald du die Angaben der Menge oder des Preises änderst, müssen Aktualisierungen durchgeführt werden. Dies kannst du tun, indem du rechts im Kontextmenü (material:more_vert[]) am jeweiligen Artikel auf *Verkaufspreis aktualisieren* (material:refresh[]) klickst. Oder du nutzt die Schaltfläche *Verkaufspreise aktualisieren* oben links in der Tabelle des Warenkorbs. Erst nach der Aktualisierung kannst du in den nächsten Schritt der Auftragsanlage weitergehen.

Folgendes gilt für Verkaufspreise:

* Gibst du manuell einen Preis ein, bleibt dieser in der Dropdown-Liste als Auswahl für diesen Auftrag erhalten, auch wenn du vor- oder zurückgehst oder zwischendurch einen anderen Preis auswählst.
* Konnte kein gültiger Verkaufspreis ermittelt werden, muss ein manueller Preis eingegeben werden. Die Auftragsanlage ist nur mit gültigen Preisen möglich.
* Es ist zulässig, den Preis 0,00 einzugeben.
* Wenn ein Verkaufspreis eingegeben wird, der niedriger ist als der Einkaufspreis, wirst du durch eine Warnung darauf hingewiesen. Allerdings ist es möglich, einen niedrigeren Verkaufspreis zu wählen, wenn es gewünscht wird.
* Nimm alle Anpassungen an den Artikeln in diesem Schritt vor, denn im dritten und letzten Schritt der Auftragsanlage ist dies nicht mehr möglich. Das Vor- und Zurücknavigieren innerhalb der Schritte der Auftragsanlage bleibt weiterhin möglich.

Auftragspositionen im Warenkorb können auch gelöscht werden. Klicke dafür auf *Löschen* (material:delete[]). Eine weitere Bearbeitungsmöglichkeit der Auftragspositionen im Warenkorb stellen die Eigenschaften dar. Beachte dafür das Kapitel <<#edit-order-item-properties, Eigenschaften von Auftragspositionen bearbeiten>>.

Nachdem du alle gewünschten Artikel im Warenkorb abschließend bearbeitet hast, klicke auf *Auftrag erstellen* bzw. *Angebot erstellen*, um zum dritten und letzten Schritt zu gelangen. Du kannst auch zu den Auftragsdetails zurückkehren, indem du auf *Auftragsdetails* klickst. Artikel im Warenkorb werden gespeichert, wenn du vor- oder zurückgehst.

[.collapseBox]
.*Warenkorbtabelle individualisieren*
--
Die Warenkorbtabelle lässt sich individuell anpassen. Du kannst wählen, welche Tabellenspalten dir in welcher Reihenfolge angezeigt werden sollen. Wenn du die Tabelle angepasst hast, wird diese Auswahl gespeichert.

[.instruction]
Tabelle individualisieren:

. Klicke auf *Spalten konfigurieren* (material:settings[]). +
→ Das Fenster *Spalten konfigurieren* wird geöffnet.
. Wähle, welche Spalten angezeigt werden sollen.
. Verschiebe (material:drag_indicator[]) die Spalten, sodass sie in der Reihenfolge angezeigt werden, in der du sie benötigst.
. Klicke auf *Bestätigen*, um deine Auswahl zu speichern.

[[table-shopping-cart]]
.Tabellenspalten Warenkorb
[cols="1,3"]
|===
|Einstellung |Erläuterung

| *Ausklappen*
|Ermöglicht das Ausklappen der Auftragspositionstabelle und zeigt die Eigenschaften an.

| *Menge*
|Zeigt die Menge der Artikel an. Passe die Menge bei Bedarf an. +
*_Hinweis:_* Wenn du die Menge änderst, musst du die *Verkaufspreise aktualisieren* (materiel:refresh[]). Erst dann ist es auch möglich, zum nächsten Schritt (Übersicht) zu gelangen. +
Diese Spalte ist eine Standardspalte.

| *Artikel-ID*
|Zeigt die Artikel-ID an. Mit Klick auf die ID wird der Artikel geöffnet. +
Diese Spalte ist eine Standardspalte.

| *Varianten-ID*
|Zeigt die Varianten-ID der Auftragsposition an. Mit Klick auf die ID wird die Variante geöffnet. +
Diese Spalte ist eine Standardspalte.

| *Artikel-ID* / *Varianten-ID*
|Zeigt die Artikel-ID und die Varianten-ID kombiniert und nicht in zwei separaten Spalten an. Wenn du auf die Artikel-ID oder die Varianten-ID klickst, gelangst du direkt in die Einstellungen des jeweiligen Artikels bzw. der Variante. +
Diese Spalte ist keine Standardspalte.

| *Variantennummer*
|Zeigt die Nummer der Variante an. Wenn du auf die Variantennummer klickst, gelangst du direkt in die Einstellungen der jeweiligen Variante. +
Diese Spalte ist eine optionale Spalte.

| *Artikelname*
|Zeigt den am Artikel hinterlegten Namen an. Passe den Namen bei Bedarf an (material:edit[]). +
Diese Spalte ist eine Standardspalte.

| *Attribute*
|Zeigt die Attribute an. +
Diese Spalte ist eine Standardspalte.

| *Variantenname*
|Zeigt den Namen der Variante an. +
Diese Spalte ist eine Standardspalte.

| *Barcode*
|Zeigt den Barcode des Artikels an. +
Diese Spalte ist keine Standardspalte.

| *System-EK*
|Zeigt den Einkaufspreis des Systems an. +
Diese Spalte ist keine Standardspalte.

| *Preisauswahl*
|Zeigt die Preisauswahl an. Wähle bei Bedarf eine andere Preisauswahl aus der Dropdown-Liste. +
Diese Spalte ist eine Standardspalte.

| *Kategorierabatt*
|Zeigt den für den ausgewählten Verkaufspreis angewendeten Kategorierabatt in Prozent an. +
Diese Spalte ist keine Standardspalte.

| *Kundenklassenrabatt*
|Zeigt den für den ausgewählten Verkaufspreis angewendeten Kundenklassenrabatt in Prozent an. +
Diese Spalte ist keine Standardspalte.

| *Nettopreis*
|Zeigt den Nettopreis des Artikels an. Wenn du einen Rabatt angewendet hast, wurde dieser hier bereits abgezogen. Der Bruttopreis wird automatisch mit angepasst. +
Diese Spalte ist eine Standardspalte.

| *Regulärer Nettopreis*
|Zeigt den ursprünglichen Nettopreis des Artikels an, bevor ein Rabatt angewendet wurde. Du kannst den regulären Nettopreis bei Bedarf anpassen (material:edit[]). +
Diese Spalte ist eine Standardspalte.

| *Bruttopreis*
|Zeigt den Bruttopreis des Aritkels an. Wenn du einen Rabatt angewendet hast, wurde dieser hier bereits abgezogen. Der Nettopreis wird automatisch mit angepasst. +
Diese Spalte ist eine Standardspalte.

| *Regulärer Bruttopreis*
|Zeigt den ursprünglichen Bruttopreis des Artikels an, bevor ein Rabatt angewendet wurde. Du kannst den regulären Bruttopreis bei Bedarf anpassen (material:edit[]). +
Diese Spalte ist eine Standardspalte.

| *Aufpreis gesamt*
|Zeigt die Summe der Aufpreise für Bestelleigenschaften an. +
Diese Spalte ist keine Standardspalte.

| *Rabatt [%]*
|Zeigt den Rabatt in Prozent an, der in den Auftragsdetails im ersten Schritt der Auftragsanlage eingegeben wurde. Möchtest du den Rabatt jedoch als Betrag angeben, wähle die Option *Betrag* aus der Dropdown-Liste. +
*_Hinweis:_* Der Betrag wird in der Währung des Auftrags angezeigt. +
Diese Spalte ist eine Standardspalte.

| *Gesamtbetrag (netto)*
|Zeigt den Netto-Gesamtbetrag des Artikels an. +
Diese Spalte ist eine Standardspalte.

| *Gesamtbetrag (brutto)*
|Zeigt den Brutto-Gesamtbetrag des Artikels an. +
Diese Spalte ist eine Standardspalte.

| *Lager*
|Zeigt das Lager des Artikels an. Wähle bei Bedarf ein anderes Lager aus der Dropdown-Liste. Beachte, dass dies nur möglich ist, wenn du für die *Zuordnung des Lagers* die Einstellung *b) Pro Artikelposition kann ein Lager zugeornet werden* gewählt hast. +
Diese Spalte ist eine Standardspalte.

| *USt. (%)*
|Die Umsatzsteuer wird in % angezeigt. Voreingestellt sind 19.00 %. Über die Dropdown-Liste kannst du den Steuersatz ändern. +
Diese Spalte ist eine Standardspalte.

| *Gewicht [g]*
|Zeigt das Gewicht des Artikels in Gramm an. Passe das Gewicht bei Bedarf im Eingabefeld an. +
Diese Spalte ist keine Standardspalte.

| *Länge [mm]*
|Zeigt die Länge des Artikels in mm an. Passe die Länge bei Bedarf im Eingabefeld an. +
Diese Spalte ist keine Standardspalte.

| *Breite [mm]*
|Zeigt die Breite des Artikels in mm an. Passe die Breite bei Bedarf im Eingabefeld an. +
Diese Spalte ist keine Standardspalte.

| *Aktionen*
|Ist dieses Feld gewählt, sind die Aktionen zum Bearbeiten (material:edit[]) und Löschen (material:delete[]) des Artikels verfügbar.
|===

--

[#edit-order-item-properties]
=== Eigenschaften an Auftragspositionen bearbeiten

Vom Warenkorb aus kannst du die Eigenschaften der Auftragspositionen eines Auftrags (Bestelleigenschaften) bearbeiten. Die hier vorgenommenen Änderungen gelten nur für die Auftragspositionen dieses Auftrags. Die im System angelegten Eigenschaften werden nicht überschrieben. In der Auftragsanlage stehen dir nur Eigenschaften zur Verfügung, die du bereits im System angelegt hast. +
Möchtest du Eigenschaften erstellen und bearbeiten oder bist du noch nicht mit der Struktur von Eigenschaften vertraut, informiere dich im Kapitel xref:artikel:eigenschaften.adoc#500[Eigenschaften].

Damit eine Eigenschaft an einer Auftragsposition gesetzt werden kann, muss sie in den Eigenschaftseinstellungen im Bereich *Optionen* als *Bestelleigenschaft* definiert werden. Lege unter xref:artikel:eigenschaften.adoc#property-options[Optionen] außerdem mögliche Aufpreise und Besteuerungen fest. Die hier hinterlegten Werte werden in die Auftragsberechnungen mit einbezogen. Ist bereits eine Eigenschaft mit einer Auftragsposition verknüpft, wird diese an der dazugehörigen Auftragsposition angezeigt.

Die Eigenschaften werden in einer zweiten Tabellenzeile direkt unterhalb der dazugehörigen Auftragsposition angezeigt. Hier findest du Angaben zu *Name*, *Wert*, *Aufpreis* und *USt. %* der Eigenschaft. Die *USt. %*, also den hinterlegten Steuersatz, kannst du direkt in der Tabelle bearbeiten, wenn der Eigenschaftstyp dies zulässt. Zudem kannst du die Eigenschaften der Auftragspositionen *löschen* (material:delete[]). Gelöschte Eigenschaften werden dann für diesen Auftrag nicht berücksichtigt. +
Um die Eigenschaften zu bearbeiten oder weitere bereits bestehende Eigenschaften zu einer Auftragspositionen hinzuzufügen, klicke rechts im Kontextmenü (material:more_vert[]) auf *Eigenschaften bearbeiten* (material:edit[]).


Im Bearbeitungsfenster findest du folgende Angaben zu der Eigenschaft einer Auftragsposition:

* *Name* = Der Name der Eigenschaft wird angezeigt. Ein rotes Sternchen am Namen der Eigenschaft kennzeichnet, dass es eine verpflichtende Eigenschaft ist. Ob eine Eigenschaft verpflichtend ist, bestimmst du in den Einstellungen der Eigenschaften im Bereich xref:artikel:eigenschaften.adoc#property-options[Optionen]. Wähle in der Dropdown-Liste *Bestelloptionen* die Einstellung *Verpflichtend* aus.
* *Wert* = Der Wert der Eigenschaft wird angezeigt. Der Wert kann angepasst werden. Je nach Eigenschaftstyp kannst du eine Auswahl treffen, den Wert ändern, einen Wert eingeben oder eine Datei hochladen. Die Änderungen gelten nur für diesen Auftrag.
* *Aufpreis* = Der Aufpreis der Eigenschaft, sofern ein Aufpreis zugeordnet ist, wird angezeigt. Der Aufpreis kann bearbeitet werden. Die Änderungen gelten nur für diesen Auftrag.

In diesem Fenster gibt es außerdem weitere Bearbeitungsmöglichkeiten. Durch Klicken auf *Löschen* (material:delete[]) entfernst du eine Eigenschaft von einer Auftragsposition. Diese Eigenschaft wird dann für diesen Auftrag nicht berücksichtigt. +
Du kannst weitere bereits angelegte Eigenschaften hinzufügen. Wähle eine Eigenschaft aus der Dropdown-Liste des Felds *Eigenschaft wählen* und füge sie durch Klicken auf *Eigenschaft hinzufügen* (material:add[]) zu dieser Auftragsposition hinzu. +
Hast du alle erforderlichen Anpassungen vorgenommen, klicke auf *Eigenschaften speichern*. Klickst du auf *Abbrechen*, wird keine der vorgenommenen Änderungen übernommen. Das Bearbeitungsfenster wird geschlossen und du kannst nach Bedarf die Eigenschaften weiterer Auftragspositionen auf die gleiche Weise bearbeiten.

Wenn du die Eigenschaften auf Dokumenten ausgeben lassen möchtest, musst du dies in der Konfiguration der Eigenschaften einstellen. Stelle sicher, dass im Bereich xref:artikel:eigenschaften.adoc#property-visibilities[Sichtbarkeiten]

* aus der Dropdown-Liste *Überall anzeigen* die Option *Anzeige auf PDF-Dokumenten* sowie
* aus der Dropdown-Liste *Mandant* die richtigen Mandanten ausgewählt sind.

Wo die Eigenschaften auf dem Dokument ausgegeben werden, hängt von der jeweiligen Eigenschaft und deren Konfiguration ab. Eigenschaften, die in der Konfiguration im Bereich *Optionen* keinen Steuersatz zugewiesen bekommen haben oder für die aus der Dropdown-Liste *Bestelleigenschaft* die Option *zusätzliche Kosten anzeigen* ausgewählt ist, werden unterhalb der Summen angezeigt. Andere Eigenschaften werden in der Tabelle der Artikelpositionen angezeigt.

Wenn du mit der Bearbeitung der Auftragseigenschaften und des Warenkorbs fertig bist, folgt der letzte Schritt in der Auftragsanlage. In diesem Schritt werden die Eigenschaften für Auftragspositionen nicht noch einmal angezeigt. Stelle daher sicher, dass du alle Anpassungen vorgenommen hast. Klicke auf *Auftrag ertellen* bzw. *Angebot erstellen*.

[#step-three-summary]
=== Schritt 3: Auftrag erstellen / Angebot erstellen

Im letzten Schritt wird der Auftrag oder das Angebot abgeschlossen. Oberhalb der Auftragsdetails werden dir Infoboxen mit verschiedenen Beträgen für diesen Auftrag oder für dieses Angebot angezeigt:

* Gesamtbetrag (brutto): Zeigt den errechneten Gesamtbruttobetrag des Auftrags an. Der Statusbalken ist grün, wenn es sich bei dem Auftrag um einen Bruttoauftrag handelt. Ansonsten ist der Statusbalken grau.
* Gesamtbetrag (netto): Zeigt den errechneten Gesamtnettobetrag des Auftrags an. Der Statusbalken ist grün, wenn es sich bei dem Auftrag um einen Nettoauftrag handelt. Ansonsten ist der Statusbalken grau.
* Artikelmenge (gesamt): Zeigt die Gesamtanzahl der Artikelpositionen des Auftrags an. Der Statusbalken ist immer grau.
* Gutscheinbetrag: Zeigt die Ermäßigung durch Aktionsgutscheine an. Der Statusbalken ist orange, wenn ein Gutschein im Auftrag verwendet wurde. Ansonsten ist der Statusbalken grau.
* Auftragsrabatt: Zeigt den Rabattbetrag an, der sich durch den im ersten Schritt der Auftragsanlage vergebenen Rabatt ergibt. Errechnet wird der summierte Rabatt für alle Auftragspositionen. Der Statusbalken ist orange, wenn im ersten Schritt ein Rabatt gesetzt wurde. Ansonsten ist der Statusbalken grau.
* Offener Betrag: Zeigt den von der Kund:in zu zahlenden Rechnungsbetrag an. Der Statusbalken ist grün, wenn der Betrag bei null liegt, d.h. wenn der Auftrag vollständig bezahlt wurde. Rot bedeutet, dass der vollständige Rechnungsbetrag noch offen ist. Orange bedeutet, dass ein Teil des Rechnungsbetrags noch offen ist.

In den Auftragsdetails kannst du die *Zahlungsart*, die *Versandkosten*, die *Versandart* sowie den *Eigner* bei Bedarf noch einmal anpassen. +

Außerdem kannst du einen oder mehrere *Gutschein-Codes* eingeben, die mit diesem Auftrag eingelöst werden sollen. Die Werte der Gutscheine werden dann mit dem Auftragswert verrechnet. Gutscheine werden nicht als Auftragspositionen im Warenkorb hinzugefügt. Gutscheine können nicht für Angebote eingelöst werden. Das bedeutet, dass das Eingabefeld *Gutschein-Codes* nur in der Auftragserstellung, nicht aber in der Angebotserstellung verfügbar ist. Bei Gutscheinen wird zwischen den Typen *plentymarkets Kampagne* und *Externe Kampagne* unterschieden. Um Gutscheicodes einzulösen, gehe wie im Folgenden beschrieben vor.

[tabs]
====
Gutschein-Codes einer plentymarkets Kampagne einlösen::
+
--
[.instruction]
Gutschein-Codes einer plentymarkets Kampagne einlösen:

. Gib im Feld *Gutschein-Codes* den Code einer plentymarkets Kampagne ein.
. Klicke anschließend auf _Enter_ oder klicke außerhalb des Felds. +
→ Es wird geprüft, ob der Gutschein-Code gültig ist. Kann der Gutschein eingelöst werden, wird er in grün mit dem Wert des Gutscheins angezeigt. Ist ein Gutschein-Code hingegen nicht gültig, wird dieser in rot mit der Info *Nicht einlösbar* angezeigt. +
*_Tipp:_* Ein Tooltip zeigt an, um welche Art von Gutschein es sich handelt.
. Gib bei Bedarf weitere Gutschein-Codes ein. +
icon:map-signs[] *_Oder:_* Klicke rechts in der Zeile des Felds *Gutschein-Codes* auf *Gutschein-Code hinzufügen* (material:add[]). +
→ Das Fenster *Gutschein einlösen* wird geöffnet.
. Wähle den Kampagnen-Typ *plentymarkets Kampagne* aus der Dropdown-Liste.
. Gib den Gutschein-Code der plentymarkets Kampagne ein.
. Klicke auf *Einlösen*. +
→ Der Gutschein-Code wird hinzugefügt und mit diesem Auftrag eingelöst.
--

Gutschein-Codes einer externen Kampagne einlösen::
+
--

[.instruction]
Gutschein-Codes einer externen Kampagne einlösen:

. Klicke rechts in der Zeile des Felds *Gutschein-Codes* auf *Gutschein-Code hinzufügen* (material:add[]). +
→ Das Fenster *Gutschein einlösen* wird geöffnet.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<table-redeem-coupon-codes>>.
. Klicke auf *Einlösen*. +
→ Der Gutschein-Code wird in blau mit dem Wert des Gutscheins hinzugefügt und mit diesem Auftrag eingelöst.

[[table-redeem-coupon-codes]]
.Gutschein-Codes einlösen
[cols="1,3"]
|===
|*Einstellung* |*Erläuterung*

| *Kampagnen-Typ*
|Wähle den Typ *Externe Kampagne* aus der Dropdown-Liste.

| *Code*
|Gib einen Gutschein-Code ein.

| *Typ*
|Wähle, ob es sich um einen *Aktionsgutschein* oder einen *Mehrzweckgutschein* handelt.

| *Wert in €*
|Gib den Wert des Gutscheins in der jeweiligen Währung ein.

|===
--
====

Unterhalb der Auftragsdetails wird eine Tabelle mit den ausgewählten Artikelpositionen angezeigt. Zusätzlich zu den Angaben in der vorherigen Ansicht werden dir hier weitere Preise und die Umsatzsteuer ausgegeben. Die Steuersätze kannst du anpassen, wenn du dies in den <<#carrying-out-standard-settings, Standardeinstellungen>> erlaubt hast.

[.collapseBox]
.*Tabelle individualisieren*
--

Die Tabelle im letzten Schritt der Auftragsanlage lässt sich individuell anpassen. Du kannst wählen, welche Tabellenspalten dir in welcher Reihenfolge angezeigt werden sollen. Wenn du die Tabelle angepasst hast, wird diese Auswahl gespeichert.

[.instruction]
Tabelle individualisieren:

. Klicke auf *Spalten konfigurieren* (material:settings[]). +
→ Das Fenster *Spalten konfigurieren* wird geöffnet.
. Wähle, welche Spalten angezeigt werden sollen.
. Verschiebe (material:drag_indicator[]) die Spalten, sodass sie in der Reihenfolge angezeigt werden, in der du sie benötigst.
. Klicke auf *Bestätigen*, um deine Auswahl zu speichern.

Die Tabelle verfügt über die folgenden Spalten: +

* Ausklappen
* Menge
* Artikel-ID
* Variantennr.
* Variantenname
* Varianten-ID
* Artikelname
* Attribute
* Nettopreis
* Regulärer Nettopreis
* Bruttopreis
* Rabatt
* Aufpreis gesamt
* Gesamtbetrag (netto)
* Gesamtbetrag (brutto)
* Lager
* USt.
* Externe Artikel-ID
* Externe Auftragspositions-ID
* Eigenschafts-ID
* Lagerorte
* Gewinnspanne (netto)
* Nachbestellungs-ID

--

Wenn du Änderungen an den Versandkosten oder der Versandart vornimmst oder Gutscheine hinzufügst, werden die Gesamtsummen automatisch neu berechnet. Um den Auftrag fertigzustellen, klicke auf material:save[role=green] *Auftrag anlegen*. Der Auftrag ist nun erstellt und je nach Einstellung wirst du in die entsprechende Ansicht weitergeleitet. Der Auftrag ist anschließend in der Auftragsübersicht im Menü *Aufträge » Aufträge (Testphase)* verfügbar.


[#create-and-apply-order-templates]
== Auftragsvorlagen erstellen und anwenden

Im Menü *Einrichtung » Aufträge » Auftragsvorlage* kannst du Auftragsvorlagen erstellen. Diese kannst du dann beim Anlegen eines manuellen Auftrags auswählen oder über eine xref:automatisierung:ereignisaktionen.adoc#intable-auftragsvorlage[Ereignisaktion] auf einen Auftrag anwenden lassen. Wählst du eine Auftragsvorlage für einen Auftrag, werden die dort hinterlegten Daten auf den Auftrag angewendet. Nach der Verwendung einer Auftragsvorlage kannst du Aufträge wie üblich bearbeiten und auch die Auftragsinformationen anpassen.

Gehe folgendermaßen vor, um eine Auftragsvorlage zu erstellen:

[.instruction]
Auftragsvorlage erstellen:

. Öffne das Menü *Einrichtung » Aufträge » Auftragsvorlage*.
. Wechsele in das Tab *Neue Vorlage*.
. Trage einen eindeutigen *Namen* ein.
. Wähle aus der jeweiligen Dropdown-Liste *Zahlungsart* und *Auftragsstatus* aus.
. Füge über *Artikel hinzufügen* optional Artikel hinzu.
. Speichere (material:save[role=green]) die Auftragsvorlage.

[[table-order-templates]]
.Datenfelder Auftragsvorlage
[cols="1,3"]
|===
|Einstellung |Erläuterung

| *Name*
|Gib einen Namen für die Auftragsvorlage ein. Dieser Name wird anschließend in Dropdown-Listen zur Auswahl der Auftragsvorlage angezeigt.

| *Zahlungsart*
|Wähle eine Zahlungsart aus der Dropdown-Liste. Diese Zahlungsart wird anschließend bei Anwendung der Vorlage zum entsprechenden Auftrag hinzugefügt.

| *Auftragsstatus*
|Wähle einen Auftragsstatus aus der Dropdown-Liste. Bei Anwendung der Vorlage auf einen Auftrag wird dieser Auftrag dann in diesen Auftragsstatus geschoben.

| *Artikel*
|Hast du der Auftragsvorlage Artikel hinzugefügt, werden diese Artikel in der Tabelle angezeigt. Das Hinzufügen von Artikeln ist optional. Die hier angezeigten Artikel werden bei Anwendung der Auftragsvorlage zum Auftrag hinzugefügt. Du siehst zudem die Menge und den Artikeltext für jeden Artikel. Außerdem kannst du in der Tabelle Artikel aus der Auftragsvorlage löschen. +
*_Beachte_*, dass bei Anwendung einer Auftragsvorlage mit Artikeln dem Auftrag noch keine Artikel hinzugefügt sein sollten. Bereits vorhandene Artikel werden überschrieben. Nach Anwendung der Auftragsvorlage kannst du schließlich weitere Artikel zum Auftrag hinzufügen.

| *Artikel hinzufügen*
|In diesem Tab kannst du optional Artikel zur Auftragsvorlage hinzufügen. Diese Artikel werden anschließend bei Anwendung der Auftragsvorlage zum Auftrag hinzugefügt. +
Setze Filter und führe eine Suche (material:search[role=skyBlue]) aus, um Artikel anzuzeigen. Füge (material:add_shopping_cart[role=green]) die gewünschten Artikel zur Auftragsvorlage hinzu. Diese werden dann im Tab *Artikel* angezeigt. +
*Menge* = Du kannst Artikel mehrmals hinzufügen. Ist dies der Fall, werden sie jeweils in einer neuen Tabellenzeile angezeigt. Alternativ kannst du im Tab *Artikel* in der Spalte *Menge* die Menge eines Artikels anpassen.

|===

Du kannst Auftragsvorlagen jederzeit anpassen. Nach jeder Änderung musst du die Auftragsvorlage speichern (material:save[role=green]). Änderungen an Auftragsvorlagen werden nicht rückwirkend auf Aufträge angewendet, sondern gelten nur ab dem Zeitpunkt der Änderung.

Auftragsvorlagen werden nur auf einen Auftrag angewendet, wenn du dies bestimmst. Möchtest du eine Auftragsvorlage immer auf bestimmte Aufträge anwenden, empfehlen wir die Einrichtung einer entsprechenden xref:automatisierung:ereignisaktionen.adoc#intable-auftragsvorlage[Ereignisaktion]. Lege in der Ereignisaktion durch Auswahl eines Ereignisses und durch Filter fest, wann und auf welche Aufträge welche Auftragsvorlage angewendet werden soll.

Möchtest du eine Auftragsvorlage bei der manuellen Erstellung eines Auftrags anwenden, wähle im Bereich *Auftragsdaten* aus der Dropdown-Liste *Vorlage verwenden* die gewünschte Auftragsvorlage aus. In der Auftragsanlage kannst du im ersten Schritt die Vorlage aus der Dropdown-Liste *Auftragsvorlage* wählen.
