= Nummernkreise festlegen

:keywords: Nummernkreis, Dokumente, Startwert, Präfix, Lieferland, Rechnungsland
:author: team-docs-automation
:description: Erfahre auf dieser Seite, wie du Nummernkreise für Dokumente anlegst und verwaltest.

[TIP]
.Geführte Tour verfügbar
====
Für das Menü *Einrichtung » Dokumente » Nummernkreise* steht dir die geführte Tour *Nummernkreise* zur Verfügung. Die Tour zeigt dir Schritt für Schritt die wichtigsten Funktionen. +
Du findest die Tour in der unteren linken Ecke des Menüs Einrichtung » Dokumente » Nummernkreise. KIicke auf material:rocket_launch[] Geführte Touren, um die Tour zu starten.
====

Um bei der Vielzahl an Dokumenten und deren Nummern nicht den Überblick zu verlieren, stehen dir im Menü *Einrichtung » Dokumente » Nummernkreise* Einstellungen für Nummernkreise zur Verfügung. Hier kannst du Nummernkreise für deine Dokumente bestimmen und so beispielsweise die Vergabe von eindeutigen Rechnungsnummern automatisieren. +

[#grant-user-rights]
== Benutzerrechte vergeben

Personen mit *Backend*-Zugriffsrechten können xref:business-entscheidungen:benutzerkonten-zugaenge.adoc#105[nur bestimmte Bereiche und Menüs] in plentymarkets sehen. Sie können also nur eingeschränkt im System arbeiten. Sollen Mitarbeiter:innen mit dem Zugang *Backend* mit Nummernkreisen arbeiten können, benötigen sie mindestens die folgenden Rechte: +

* *Dokumente > Nummernkreise > Lesen*
* *Dokumente > Nummernkreise > Aktualisieren*
* *Dokumente > Nummernkreise > Löschen*

[#configure-columns]
== Spalten in der Übersicht konfigurieren

Du kannst die Tabellenspalten in der Übersicht der Nummernkreise nach deinen Bedürfnissen konfigurieren. Beim ersten Öffnen des Menüs wird dir die Standardansicht der Tabelle angezeigt. Mit Klick auf *Spalten konfigurieren* (material:settings[]) oben rechts öffnet sich die Tabelle mit den verfügbaren Spalten. Dort kannst du wählen, welche Spalten du sehen möchtest und in welcher Reihenfolge diese angezeigt werden sollen. Gehe dazu vor wie folgt.

[.instruction]
Spalten in der Übersicht konfigurieren:

. Öffne das Menü *Einrichtung » Dokumente » Nummernkreise*.
. Klicke oben rechts auf *Spalten konfigurieren* (material:settings[]). +
→ Das Fenster *Spalten konfigurieren* wird geöffnet.
. Wähle die Spalten, die angezeigt werden sollen (material:check_box[role=skyBlue]). Beachte dazu die Erläuterungen in <<table-columns-number-ranges>>.
. Ziehe (material:drag_indicator[]) die Spalten per Drag-and-drop an die gewünschte Stelle, bis sie in der für dich richtigen Reihenfolge angezeigt werden.
. Füge bei Bedarf Spalten hinzu oder wähle Spalten ab, wenn du sie nicht benötigst.
. Klicke auf *Bestätigen*. +
→ Die Einstellungen werden gespeichert.

[[table-columns-number-ranges]]
.Tabellenspalten für Nummernkreise
[cols="1,3"]
|===
|Einstellung |Erläuterung

| *Auswahl*
|Anhand der Auswahlbox kann der Nummernkreis gewählt werden, um beispielsweise Aktionen wie das Bearbeiten oder Löschen des Nummernkreises vorzunehmen. +
Dies ist eine Standardspalte.

| *Aktiv*
|Zeigt an, ob der Nummernkreis aktiv (material:circle[role=green]) oder inaktiv (material:circle[]) ist. Ist ein Nummernkreis aktiv, wird dieser automatisch für neue Dokumente dieses Typs vergeben. Beachte, dass aktive Nummernkreise nicht bearbeitet oder gelöscht werden können. +
*_Tipp:_* Bei der Suche nach Nummernkreisen kannst du die Suchergebnisse ab- oder aufsteigend nach der Art der Aktivierung sortieren. Klicke dazu auf den Pfeil, der neben der Spaltenüberschrift erscheint. +
Dies ist eine Standardspalte.

| *Name*
|Zeigt den Namen des Nummernkreises an. +
*_Tipp:_* Bei der Suche nach Nummernkreisen kannst du die Suchergebnisse ab- oder aufsteigend nach dem Namen sortieren. Klicke dazu auf den Pfeil, der neben der Spaltenüberschrift erscheint. +
Dies ist eine Standardspalte.

| *Dokumenttyp*
|Zeigt den Dokumenttyp des Nummernkreises an. +
Dies ist eine Standardspalte.

| *Präfix*
|Zeigt das Präfix des Nummernkreises an (z.B. *DE-INV*). +
Dies ist eine Standardspalte.

| *Letzte (De)aktivierung*
|Zeigt das Datum an, an dem der Nummernkreis zuletzt aktiviert bzw. deaktiviert wurde. +
*_Tipp:_* Bei der Suche nach Nummernkreisen kannst du die Suchergebnisse ab- oder aufsteigend nach dem Datum der letzten (De)aktivierung sortieren. Klicke dazu auf den Pfeil, der neben der Spaltenüberschrift erscheint. +
Dies ist eine Standardspalte.

| *Aktionen*
|Ermöglicht das *Aktivieren* (material:task[]) und *Löschen* (material:delete[]) des Nummernkreises über das Kontextmenü (material:more_vert[]).

| *Präfix-Vorschau*
|Zeigt eine Vorschau der Präfixe für den Nummernkreis an. +
Dies ist eine optionale Spalte.

| *Startwert*
|Zeigt den Startwert des Nummernkreises an. +
Der Startwert ist die Nummer, die als erster Wert verwendet werden soll. Beachte, dass hier maximal 9 Zeichen möglich sind. +
Diese Nummer muss nicht zwingend die `1` sein. Wenn du z.B. bereits nummerierte Rechnungen im System abgelegt hast, kannst du die Startnummer an die bestehenden Nummern anschließend eintragen. Wenn die Nummer über eine bestimmte Anzahl von Stellen verfügen soll, gib den Startwert mit führenden Nullen an (z.B. 00001). +
Dies ist eine optionale Spalte.

| *Standort*
|Zeigt den Standort an, für den der Nummernkreis verwendet wird. +
Dies ist eine optionale Spalte.

| *Mandant: Standort*
|Zeigt den Mandantenstandort an, für den der Nummernkreis verwendet wird. +
Dies ist eine optionale Spalte.

| *Herkunft*
|Zeigt die Auftragsherkunft an, für die der Nummernkreis verwendet wird. +
Dies ist eine optionale Spalte.

| *Rechnungsland*
|Zeigt das Rechnungsland an, für das der Nummernkreis verwendet wird. +
Dies ist eine optionale Spalte.

| *Lieferland*
|Zeigt das Lieferland an, für das der Nummernkreis verwendet wird. +
Dies ist eine optionale Spalte.

| *Nummernkreis-ID*
|Zeigt die ID des Nummernkreises an. +
Dies ist eine optionale Spalte.

|===

[TIP]
.Größe der Tabellenspalten beliebig anpassen
====
In der Übersichtstabelle der Nummernkreise kannst du die Größe der Spalten nach deinen Bedürfnissen anpassen. Fahre dazu mit der Maus über die entsprechende Tabellenspalte und ziehe sie anhand der blauen Linien in die gewünschte Breite.
====

[#search-for-number-ranges]
== Nach Nummernkreisen suchen

Verwende eine der folgenden Möglichkeiten, um nach Nummernkreisen zu suchen.

[.instruction]
Nach Nummernkreisen suchen:

. Öffne das Menü *Einrichtung » Dokumente » Nummernkreise*.
.. *_Möglichkeit 1:_* Klicke auf icon:search[role="darkGrey"], um direkt eine Liste aller Nummernkreise zu sehen.
.. *_Möglichkeit 2:_* Gib eine Zahl in das Suchfeld ein und klicke auf einen der automatischen Vorschläge.
Klicke dann auf icon:search[role="darkGrey"], um die Suche auszuführen.
.. *_Möglichkeit 3:_* Klicke auf icon:tune[set=material], um die Suchergebnisse mit Hilfe von Filtern einzugrenzen.

[#filter-for-number-ranges]
== Nach Nummernkreisen filtern

Mithilfe von Filtern kannst du die Suche eingrenzen und nur nach bestimmten Nummernkreisen suchen. Die folgende Tabelle listet alle verfügbaren Filter.

[[filters-number-ranges]]
.Filter für Nummernkreise
[cols="1,3"]
|===
|Filter |Erläuterung

| *Name*
|Gib einen Namen ein, um nach Nummernkreisen mit diesem Namen zu filtern.

| *Dokumenttyp*
|Wähle einen Dokumenttyp aus der Dropdown-Liste, um nach Nummernkreisen dieses Dokumenttyps zu filtern.

| *Herkunft*
|Wähle eine oder mehrere Herkünfte aus der Dropdown-Liste, um nach Nummernkreisen mit diesen Herkünften zu filtern.

| *Standort*
|Wähle einen oder mehrere Standorte aus der Dropdown-Liste, um nach Nummernkreisen mit diesen Standorten zu filtern.

| *Rechnungsland*
|Wähle ein oder mehrere Rechnungsländer aus der Dropdown-Liste, um nach Nummernkreisen mit diesen Rechnungsländern zu filtern.

| *Lieferland*
|Wähle ein oder mehrere Lieferländer aus der Dropdown-Liste, um nach Nummernkreisen mit diesen Lieferländern zu filtern.

| *Aktivierung*
|Wähle aktiv oder inaktiv aus der Dropdown-Liste, um nach dem Aktivierungsstatus zu filtern.

| *Präfix*
|Gib ein Präfix ein, um nach Nummernkreisen mit diesem Präfix zu filtern.

|===

[#create-number-ranges]
== Neuen Nummernkreis erstellen

Um neue Nummernkreise für deine Dokumente zu erstellen, gehe vor wie folgt.

[.instruction]
Nummernkreis erstellen:

. Öffne das Menü *Einrichtung » Dokumente » Nummernkreise*. +
→ Die Übersicht der Nummernkreise wird geöffnet.
. Klicke oben auf *Neuen Nummernkreis hinzufügen* (material:add[]). +
icon:map-signs[] *_Oder:_* Klicke links in der Seitennavigation auf *+ Neuen Nummernkreis hinzufügen*. +
→ Die Ansicht mit den Einstellungen für den neuen Nummernkreis wird geöffnet.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<table-create-number-range>>.

[[table-create-number-range]]
.Nummernkreis erstellen
[cols="1,3"]
|===
|Einstellung |Erläuterung

2+^| *Grundeinstellungen*

| *Name*
|Gib einen Namen für den Nummernkreis ein. +
Dies ist ein Pflichtfeld.

| *Beschreibung*
|Gib optional eine Beschreibung für den Nummernkreis ein. Die Beschreibung kann maximal 256 Zeichen haben.

| *Dokumenttyp*
|Wähle den Dokumenttyp aus der Dropdown-Liste, für den der Nummernkreis verwendet werden soll. +
Dies ist ein Pflichtfeld.

| *Standort*
|Wähle einen oder mehrere Standorte aus der Dropdown-Liste, für die der Nummernkreis verwendet werden soll. +
*_Hinweis:_* Erst wenn du einen Standort gewählt hast, wird die Auswahl der Herkunft ermöglicht.

| *Herkunft*
|Wähle eine oder mehrere Herkünfte aus der Dropdown-Liste, für die der Nummernkreis verwendet werden soll. +
*_Hinweis:_* Erst wenn du eine Herkunft gewählt hast, wird die Auswahl des Rechnungslands ermöglicht.

| *Rechnungsland*
|Wähle ein oder mehrere Rechnungsländer aus der Dropdown-Liste, für die der Nummernkreis verwendet werden soll. +
*_Hinweis:_* Erst wenn du ein Rechnungsland gewählt hast, wird die Auswahl des Lieferlands ermöglicht.

| *Lieferland*
|Wähle ein oder mehrere Lieferländer aus der Dropdown-Liste, für die der Nummernkreis verwendet werden soll.

2+^| *Einstellungen*

| *Präfix*
|Gib ein Präfix ein, das vor der Nummer stehen soll. Standardmäßig beginnt das Präfix mit dem Jahr (z.B. `2023-`). +
Dies ist ein Pflichtfeld.
//will more variables be added here in the future? (year, year-month, year-month-day)

| *Stellenanzahl*
|Definiere die Anzahl der Stellen, die der Nummernkreis haben soll. Du kannst eine Stellenanzahl zwischen 2 und 9 wählen. Der Standardwert für die Stellenanzahl ist 5. +
//in Zukunft wird die Stellenanzahl 1 ebenfalls möglich sein!?
Dies ist ein Pflichtfeld. +
*_Hinweis:_* Aktiviere (material:check_box[role=skyBlue]) die Option *Hochzählen erlauben*, um das Hochzählen zu erlauben, wenn alle Nummern der gewählten Stellenanzahl bereits vergeben wurden. +
_Beispiel:_ Wenn du die Stellenanzahl 2 gewählt hast und bereits 99 Dokumentnummern vergeben wurden, wird automatisch die 100 und somit die Stellenanzahl 3 für das nächste Dokument verwendet. Aktivierst du diese Option nicht, können keine weiteren Dokumentnummern vergeben werden.

| *Startwert*
|Gib einen Wert ein, ab dem der Nummernkreis beginnen soll. Der Startwert hängt von der gewählten Stellenanzahl des Nummernkreises ab. Hast du beispielsweise die Stellenanzahl 3 gewählt, kann der Startwert zwischen 1 und 999 liegen. Der Standardwert für den Startwert ist 1. +
Dies ist ein Pflichtfeld.

| *Vorschau mit aktuellen Einstellungen*
|Zeigt die Vorschau des Nummernkreises mit den aktuellen Einstellungen an.

| *Zuletzt generierte Nummer*
|Klicke rechts auf *Zuletzt generierte Nummer anzeigen* (material:refresh[]), um die zuletzt generierte Nummer anzuzeigen. +
*_Hinweis:_* Diese Funktion ist nur verfügbar, wenn bereits eine Nummer generiert wurde.

|===

[TIP]
.Sternchen zeigt ungespeicherte Änderungen an
====
Wird links in der Seitennavigation ein kleines Sternchen angezeigt, weist dies auf ungespeicherte Änderungen hin. Sobald du deine Änderungen gespeichert hast, verschwindet das Sternchen wieder.
====

[#deactivate-number-ranges]
== Nummernkreise (de)aktivieren

Um Nummernkreise zu aktivieren bzw. zu deaktivieren, gehe vor wie folgt. Beachte, dass aktive Nummernkreise nicht bearbeitet oder gelöscht werden können.

[.instruction]
Nummernkreise aktivieren/deaktivieren:

. Öffne das Menü *Einrichtung » Dokumente » Nummernkreise*. +
→ Die Übersicht der Nummernkreise wird geöffnet.
. Führe die Suche (material:search[]) aus, um Nummernkreise anzuzeigen.
. Klicke rechts in der Zeile des Nummernkreises, den du aktivieren möchtest, auf das Kontextmenü (material:more_vert[]).
. Wähle die Option *Nummernkreis aktivieren* (material:task[]) bzw. *Nummernkreis deaktivieren* (material:task[]).
. Bestätige die Sicherheitsabfrage. +
→ Der Nummernkreis wird aktiviert und für neue Dokumente dieses Typs verwendet bzw. deaktiviert und nicht mehr für neue Dokumente verwendet. +
icon:map-signs[] *_Oder:_* Klicke auf den Nummernkreis, den du aktivieren bzw. deaktivieren möchtest. +
→ Die Einstellungen des Nummernkreises werden geöffnet.
. Klicke oben auf die Umschaltfläche, um den Nummernkreis zu aktivieren (material:toggle_on[role=skyBlue]) oder zu deaktivieren (material:toggle_off[]).
. Bestätige die Sicherheitsabfrage. +
→ Der Nummernkreis wird aktiviert bzw. deaktiviert.

[#delete-number-ranges]
== Nummernkreise löschen

Um Nummernkreise zu löschen, gehe vor wie folgt. Beachte, dass aktive Nummernkreise nicht gelöscht werden können.

[.instruction]
Nummernkreise löschen:

. Öffne das Menü *Einrichtung » Dokumente » Nummernkreise*. +
→ Die Übersicht der Nummernkreise wird geöffnet.
. Führe die Suche (material:search[]) aus, um Nummernkreise anzuzeigen.
. Wähle (material:check_box[role=skyBlue]) den Nummernkreis, den du löschen möchtest.
. Klicke oben in der Toolbar auf *Nummernkreis löschen* (material:delete[]). +
icon:map-signs[] *_Oder:_* Klicke rechts in der Zeile des Nummernkreises, den du löschen möchtest, auf das Kontextmenü (material:more_vert[]).
. Wähle die Option *Nummernkreis löschen* (material:delete[]).
. Bestätige die Sicherheitsabfrage. +
→ Der Nummernkreis wird gelöscht.

[TIP]
.Gruppenfunktionen verwenden
====
Mit der Gruppenfunktion *Nummernkreise öffnen* (material:edit[]) oder *Nummernkreise löschen* (material:delete[]) kannst du alle in der Übersicht gewählten (material:check_box[role=skyBlue]) Nummernkreise auf einmal öffnen oder löschen. Beachte allerdings, dass aktive Nummernkreise nicht gelöscht werden können.
====
