= Auftragstyp Gewährleistung

:keywords: Gewährleistung, Garantie, Umtausch, neue Lieferung, Rückerstattung
:author: team-order-core
:description: Erfahre, wie du anhand des Auftragstyps Gewährleistung Gewährleistungen erstellst, um Kund:innen eine neue Lieferung zu senden oder ihnen den Rechnungsbetrag zurückzuerstatten. Lerne außderdem, wie du die Rückerstattung von Versandkosten festlegst.

Gewährleistungen sind xref:auftraege:order-type-return.adoc#[Retouren] relativ ähnlich, denn in beiden Fällen bekommst du Waren eines Auftrags im *Status 7* wieder zurückgesendet. Im Gegensatz zur Retoure erwarten Kund:innen bei einer Gewährleistung aber entweder eine neue Lieferung oder eine Rückerstattung des Rechnungsbetrags mittels einer xref:auftraege:order-type-credit-note.adoc#[Gutschrift].

[TIP]
.Garantie vs. Gewährleistung
======
Im Gegensatz zur freiwillig erklärten Garantie handelt es sich bei der Gewährleistung um die *gesetzliche Pflicht* der Händler:innen, Mängel am Artikel, die bereits bei der Lieferung bestanden haben, für Käufer:innen kostenlos zu beseitigen. Käufer:innen können die Gewährleistung gerichtlich bis zu 2 Jahre bei beweglichen Artikeln oder 3 Jahre bei unbeweglichen Artikeln geltend machen. Ab 6 Monaten nach Erhalt der Ware müssen Käufer:innen jedoch beweisen, dass die Mängel bereits bei Erhalt der Ware vorhanden waren.
======

Wenn ein Gewährleistungsfall vorliegt, entscheidest du als Händler:in, ob du Käufer:innen die Kosten erstattest, den Artikel reparierst oder den Artikel austauschst. Soll ein Umtausch durchgeführt werden, lege eine *Gewährleistung* an. Möchtest du das Geld erstatten, lege eine xref:auftraege:order-type-credit-note.adoc#[Gutschrift] für die Gewährleistung an. Ob du die *Versandkosten* in einer Gewährleistung übernimmst oder nicht, wählst du in den Grundeinstellungen im Menü *Einrichtung » Aufträge » Auftragstypen » Gewährleistung*.

[TIP]
.Einstellungen einer Gewährleistung
======
Wenn du aus einem Auftrag heraus eine Gewährleistung erzeugst, wird automatisch das *Versandprofil* des Auftrags übernommen. Die Einstellungen können jedoch in der Gewährleistung angepasst werden. Bei *Lieferaufträgen* wird ebenfalls automatisch das korrekte Lager eingestellt. Die *Zahlungsart* bei Gewährleistungen kann bearbeitet werden.
======

== Grundeinstellungen für Gewährleistungen vornehmen

Im Menü *Einrichtung » Aufträge » Auftragstypen » Gewährleistung* nimmst du die Grundeinstellungen vor, die für neue Gewährleistungen standardmäßig verwendet werden.

[.instruction]
Grundeinstellungen vornehmen:

. Öffne das Menü *Einrichtung » Aufträge » Auftragstypen » Gewährleistung*.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<table-general-settings-warranty>>.
. Speichere (material:save[]) die Einstellungen.

[[table-general-settings-warranty]]
.Grundeinstellungen für Gewährleistungen
[cols="1,3"]
|===
|Einstellung |Erläuterung

| *Standard-Status*
|Wähle, welcher Status bei Gewährleistungen automatisch eingestellt sein soll.

| *Standard-Status zum Zurücksetzen des Warenausgangs*
|Wähle, welcher Status für das Zurücksetzen des Warenausgangs automatisch eingestellt sein soll. +
Wenn kein besonderer Status benötigt wird, wähle die Option *Letzter Status*. Dann wird der vor dem Warenausgang durchlaufene Status wieder eingestellt.

| *Versandkosten kopieren*
|Wähle, ob die Versandkosten für Gewährleistungen übernommen werden sollen.

|===


[#create-warranty]
== Gewährleistung anlegen

Normalerweise legst du eine Gewährleistung in einem bestehenden Retourenauftrag an. Es ist jedoch auch möglich, diese direkt aus dem zugrunde liegenden Hauptauftrag heraus anzulegen.

Wird die Ware nach Lieferung beanstandet und du entscheidest dich beispielsweise aus Kostengründen gegen die Rücksendung der Ware, lege die Gewährleistung direkt im Hauptauftrag an.

Möchtest du dagegen erst den Eingang der Retoure abwarten und die Ware prüfen, lege zunächst einen Retourenauftrag an und erstelle im Rahmen der Abwicklung dort eine Gewährleistung.

:ordertype: Gewährleistungen

[.instruction]
Gewährleistung anlegen:

. Öffne das Menü *Aufträge » Aufträge (Testphase)*.
. Führe die Suche (material:search[]) aus, um Aufträge anzuzeigen.
. Öffne den Haupt- oder Retourenauftrag, für den du eine Gewährleistung anlegen möchtest.
. Klicke oben auf *Aufträge erstellen* (material:shopping_cart[]).
. Wähle eine Option. Beachte dazu die Erläuterungen in <<table-create-{ordertype}>>.
. Wählst du die Option *Für bestimmte Auftragspositionen*, nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<table-create-warranty>>.
. *Speichere* (material:save[]) die Einstellungen. +
→ Die Gewährleistung wird angelegt.

include::partial$create-order-type.adoc[]

[[table-create-warranty]]
.Einstellungen für Gewährleistungen
[cols="1,3"]
|===
|Einstellung |Erläuterung

| *Status*
|Wähle einen Status aus der Dropdown-Liste.

| *Eigner*
|Wähle einen Eigner aus der Dropdown-Liste.

| *Versandkosten kopieren*
|Wähle aus der Dropdown-Liste, ob die Versandkosten in die Gewährleistung übernommen werden sollen.

2+^| *Artikelinformationen*

| *Füge alle offenen Mengen in den Warenkorb* (material:playlist_add[])
|Fügt alle offenen Mengen dem Warenkorb hinzu.

| *Artikel-ID*
|Zeigt die Artikel-ID an.

| *Varianten-ID*
|Zeigt die Varianten-ID an.

| *Variantennummer*
|Zeigt die Variantennummer an.

| *Menge*
|Zeigt die Menge des Artikels an. Passe die Menge bei Bedarf an.

| *Verbleibende Stückzahl*
|Zeigt die verbleibende Stückzahl des Artikels an.

| *Offene Menge*
|Zeigt die offene Menge des Artikels an.

| *Artikelname*
|Zeigt den Name des Artikels an.

| *Zum Warenkorb hinzufügen* (material:add_shopping_cart[])
|Fügt nur bestimmte Artikel zur Gewährleistung hinzu. Diese Schaltfläche ist nur verfügbar, wenn mindestens 1 Artikel vorhanden ist. +
*_Tipp:_* Passe die Artikelmenge bei Bedarf im Feld *Menge* an.

2+^| *Warenkorb*

| *Artikel aus Warenkorb entfernen* (material:delete[])
|Leert den Warenkorb komplett. Möchtest du nur bestimmte Artikel entfernen, klicke rechts neben dem jeweiligen Artikel auf *Artikel aus Warenkorb entfernen* (material:delete[]).

| *Artikel-ID*
|Zeigt die Artikel-ID an.

| *Varianten-ID*
|Zeigt die Varianten-Id an.

| *Menge*
|Zeigt die Artikelmenge an. Passe die Menge bei Bedarf an.

| *Artikelname*
|Zeigt den Artikelname an. Passe den Name bei Bedarf an.

|===

[#determine-shipping-costs]
== Versandkosten bei Rückerstattung festlegen

Bei Kindaufträgen vom Typ *Gutschrift* oder *Gewährleistung* kannst du selbst entscheiden, wie hoch die Versandkosten sein sollen, die der Käufer:in für einen Artikel rückerstattet werden. Um den Betrag der Versandkosten festzulegen, gehe vor wie folgt.

[TIP]
.Versandkostenrückerstattung für Gewährleistungen und Gutschriften einstellen
======
Lege im Menü *Einrichtung » Aufträge » Einstellungen* fest, ob Versandkosten für Käufer:innen bei Gewährleistungen und Gutschriften rückwirkend erstattet werden sollen. Wähle dazu bei den Einstellungen *Versandkosten in Gewährleistung übernehmen* und *Versandkosten in Gutschrift übernehmen* die Option *Ja*, um Versandkosten zu erstatten oder *Nein*, wenn Kund:innen die Versandkosten selbst tragen sollen.
======

[.instruction]
Versandkosten bei Rückerstattung festlegen:

. Öffne das Menü *Aufträge » Aufträge (Testphase)*.
. Führe die Suche (material:search[]) aus, um Aufträge anzuzeigen.
. Öffne den Auftrag, in dem du die Versandkosten festlegen möchtest.
. Klicke auf *Aufträge erstellen* (material:shopping_cart[]) und wähle die Option *Gewährleistung bzw. Gutschrift > Für bestimmte Auftragspositionen*. +
→ Der Kindauftrag vom Typ *Gewährleistung* oder *Gutschrift* wird geöffnet.
. Wähle für den Artikel im Feld *Versandkosten kopieren* die Option *Ja*, um die Versandkosten zu übernehmen. +
→ Das Feld *Versandkosten in €* wird sichtbar. +
*_Hinweis:_* Hier sind zunächst die Versandkosten des Hauptauftrags voreingestellt.
. Möchtest du die Versandkosten anpassen, die der Kund:in zurückerstattet werden sollen, gib einen anderen Betrag im Feld *Versandkosten in €* ein.
. Klicke rechts auf *Zum Warenkorb hinzufügen* (material:add_shopping_cart[]). +
→ Der Artikel wird zum Warenkorb hinzugefügt.
. *Speichere* (material:save[]) die Einstellungen. +
→ Die Versandkosten für die Rückerstattung des Artikels werden übernommen.

[#edit-warranty]
== Gewährleistung bearbeiten

Gewährleistungsaufträge werden in der Auftragsübersicht angezeigt. Öffne eine Gewährleistung, um beispielsweise einen zusätzlichen *Preis* einzugeben, wenn du der Käufer:in einen höherpreisigen Artikel als Ersatz liefern möchtest. Falls nötig, können hier auch die Mengen der in der Gewährleistung enthaltenen Auftragspositionen verändert werden. Um eine Gewährleistung zu bearbeiten, gehe wie im Folgenden beschrieben vor.

[.instruction]
Gewährleistung bearbeiten:

. Öffne das Menü *Aufträge » Aufträge (Testphase)*.
. Klicke oben auf *Filter* (material:tune[]).
. Wähle für den Filter *Auftragstyp* die Option *Gewährleistung*.
. Klicke auf *Suchen* (material:search[]). +
→ Alle Gewährleistungen werden aufgelistet.
. Klicke in die Zeile der Gewährleistung, die du bearbeiten möchtest. +
→ Die Gewährleistung wird geöffnet.
. Klicke im Bereich *Auftragspositionen* auf *Bearbeiten* (material:edit[]). +
→ Die Artikelansicht wird geöffnet und du kannst die Einstellungen anpassen.
. *Speichere* (material:save[]) die Einstellungen.

[#finalise-warranty]
== Gewährleistung abschließen

Zum Abschließen einer Gewährleistung musst du, wenn für die Ersatzware ein Aufpreis berechnet wird, zunächst eine Rechnung in der Gewährleistung erzeugen. Falls du keine Ersatzware versendest, sondern dich mit der Käufer:in auf einen nachträglichen Preisnachlass auf die beanstandete Ware einigst, legst du eine Gutschrift im Hauptauftrag an.

Um die Bearbeitung einer Gewährleistung durch einen Umtausch abzuschließen, gehe wie im Folgenden beschrieben vor.

[.instruction]
Gewährleistung durch Umtausch abschließen:

. Öffne das Menü *Aufträge » Aufträge (Testphase)*.
. Führe die Suche (material:search[]) aus, um Aufträge anzuzeigen.
. Klicke rechts in der Zeile der Gewährleistung auf das Kontextmenü (material:more_vert[]).
. Wähle *Dokument erstellen* > *Rechnung*. +
icon:map-signs[] *_Oder:_* Öffne die Gewährleistung, die du abschließen möchtest.
. Gehe in den Bereich *Dokumente*.
. Klicke auf *Dokument erstellen* (material:add[]).
. Wähle die Option *Rechnung*. +
→ Das Fenster zum Erstellen der Rechnung wird geöffnet.
. Nimm bei Bedarf Einstellungen vor.
. Klicke auf *Ausführen*. +
→ Die Rechnung wird erzeugt.
. Klicke anschließend oben in der Toolbar auf *Warenausgang buchen* (material:input).
. Passe bei Bedarf das Datum des Warenausgangsdatum an.
. Klicke auf *Ausführen*. +
→ Der Warenausgang wird gebucht und der *Status* wechselt automatisch zu *[7] Warenausgang gebucht*.
. Gehe anschließend in den Bereich *Staus und Tags*.
. Setze den Status der Gewährleistung manuell auf Status *[10] Gewährleistung*.
. *Speichere* (material:save[]) die Einstellungen.

[TIP]
.Zahlungseingang bei Gewährleistungen buchen
======
Grundsätzlich müssen Zahlungen zu Gewährleistungen nur dann gebucht werden, wenn mit Käufer:innen ein Aufpreis vereinbart wurde. In diesem Fall buchst du den Zahlungseingang nach erfolgter Zahlung im Bereich *Zugeordnete Zahlungen* der Gewährleistung.
======
