= Auftragstyp Gutschrift

:keywords: Gutschrift, Gutschriftauftrag, Gutschriftdokument, Gutschriftbeleg, Gutschriftbeleg stornieren, Rückzahlung, Warenbestand zurückbuchen
:author: team-order-core
:description: Erfahre, wie du anhand eines Gutschriftauftrags Gutschriften erstellst, um Kund:innen einen Betrag zurückzuerstatten. Lerne außerdem, wie du das Dokument Gutschrift erstellst, korrigierst und stornierst oder die Versandkosten bei einer Rückerstattung festlegst.

Bei einer Gutschrift bekommen deine Kund:innen einen Betrag zurückerstattet. Dies kann beispielsweise nach einer xref:auftraege:order-type-return.adoc#[Retoure] der Fall sein. Bei der Gutschrift in plentymarkets handelt es sich also nicht um eine Art umgekehrte Rechnung, sondern um eine Rückzahlung. Gutschriftaufträge erzeugst du unter *Aufträge » Aufträge* aus einem Auftrag. Eine Gutschrift ist also immer einem Auftrag zugeordnet. Die in einem Gutschriftauftrag erzeugten Gutschriftdokumente werden auch in Buchhaltungsexporten, wie dem xref:auftraege:buchhaltung.adoc#650[DATEV-Export], berücksichtigt.

[#saving-standard-status]
== Standardstatus für Gutschriften speichern

Bevor du eine Gutschrift anlegst, prüfe den *Standard-Status* für Gutschriften im Menü *Einrichtung » Aufträge » Auftragstypen » Gutschrift*. Passe den Standardstatus bei Bedarf an und speichere die Einstellungen. In diesem Menü kannst du außerdem anhand der Option *Versandkosten kopieren* festlegen, ob die Versandkosten des Auftrags in die Gutschrift übernommen werden sollen.

[#create-credit-note]
== Gutschrift anlegen

Eine Gutschrift ist immer mit einem bestehenden Auftrag in deinem plentymarkets System verknüpft. Deshalb musst du den gewünschten Auftrag zunächst in der Auftragsübersicht öffnen, bevor du eine Gutschrift anlegen kannst.

[TIP]
.Gutschriften im Hauptauftrag oder im Kindauftrag anlegen
======
Hat eine Kund:in den Auftrag bereits gezahlt, beispielsweise per Vorkasse, und entscheidet sich vor dem Warenausgang gegen den Kauf, empfehlen wir, den Auftrag zu stornieren und direkt im Hauptauftrag eine Gutschrift über alle Auftragspositionen anzulegen.

Kommt es nach erfolgter Zahlung, Warenausgang und Zustellung der Ware für eine oder alle Auftragspositionen zu einer xref:auftraege:order-type-return.adoc#[Retoure] oder zu einem xref:auftraege:order-type-repair.adoc#[Reparaturauftrag], lege die Gutschrift direkt im entsprechenden Retouren- oder Reparaturauftrag an.
======

:ordertype: Gutschriften

[.instruction]
Gutschriftauftrag anlegen:

. Öffne das Menü *Aufträge » Aufträge*.
. Führe die Suche (material:search[]) aus, um Aufträge anzuzeigen.
. Öffne den Auftrag, zu dem du eine Gutschrift anlegen möchtest. Beachte, dass Aufträge nur in der Listenansicht geöffnet werden können.
. Klicke oben auf *Aufträge erstellen* (material:shopping_cart[]) > *Gutschrift*.
. Wähle eine Option. Beachte dazu die Erläuterungen in <<table-create-{ordertype}>>.
. Wählst du die Option *Für bestimmte Auftragspositionen*, nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<table-create-credit-note>>.
. *Speichere* (material:save[]) die Einstellungen. +
→ Der Gutschriftauftrag wird angelegt.

include:partial$create-order-type.adoc[]

[[table-create-credit-note]]
.Einstellungen für Gutschriften
[cols="1,3"]
|===
|Einstellung |Erläuterung

| *Status*
|Wähle einen Status aus der Dropdown-Liste.

| *Eigner*
|Wähle einen Eigner aus der Dropdown-Liste.

| *Versandkosten kopieren*
|Wähle aus der Dropdown-Liste, ob die Versandkosten kopiert werden sollen.

2+^| *Artikelinformationen*

| *Füge alle offenen Mengen in den Warenkorb* (material:playlist_add[])
|Fügt alle offenen Mengen dem Warenkorb hinzu.

| *Artikel-ID*
|Zeigt die Artikel-ID an.

| *Varianten-ID*
|Zeigt die Varianten-ID an.

| *Variantennummer*
|Zeigt die Variantennummer an.

| *Menge*
|Zeigt die Menge des Artikels an. Passe die Menge bei Bedarf an.

| *Verbleibende Stückzahl*
|Zeigt die verbleibende Stückzahl des Artikels an.

| *Offene Menge*
|Zeigt die offene Menge des Artikels an.

| *Artikelname*
|Zeigt den Name des Artikels an.

| *Zum Warenkorb hinzufügen* (material:add_shopping_cart[])
|Fügt nur bestimmte Artikel zur Gutschrift hinzu. Diese Schaltfläche ist nur verfügbar, wenn mindestens 1 Artikel vorhanden ist. +
*_Tipp:_* Passe die Artikelmenge bei Bedarf im Feld *Menge* an.

2+^| *Warenkorb*

| *Artikel aus Warenkorb entfernen* (material:delete[])
|Leert den Warenkorb komplett. Möchtest du nur bestimmte Artikel entfernen, klicke rechts neben dem jeweiligen Artikel auf *Artikel aus Warenkorb entfernen* (material:delete[]).

| *Artikel-ID*
|Zeigt die Artikel-ID an.

| *Varianten-ID*
|Zeigt die Varianten-Id an.

| *Menge*
|Zeigt die Artikelmenge an. Passe die Menge bei Bedarf an.

| *Artikelname*
|Zeigt den Artikelname an. Passe den Name bei Bedarf an.

|===

[#determine-shipping-costs]
== Versandkosten bei Rückerstattung festlegen

Bei Kindaufträgen vom Typ *Gutschrift* oder *Gewährleistung* kannst du selbst entscheiden, wie hoch die Versandkosten sein sollen, die der Käufer:in für einen Artikel rückerstattet werden. Um den Betrag der Versandkosten festzulegen, gehe vor wie folgt.

[TIP]
.Versandkostenrückerstattung für Gewährleistungen und Gutschriften einstellen
======
Lege im Menü *Einrichtung » Aufträge » Einstellungen* fest, ob Versandkosten für Käufer:innen bei Gewährleistungen und Gutschriften rückwirkend erstattet werden sollen. Wähle dazu bei den Einstellungen *Versandkosten in Gewährleistung übernehmen* und *Versandkosten in Gutschrift übernehmen* die Option *Ja*, um Versandkosten zu erstatten oder *Nein*, wenn Kund:innen die Versandkosten selbst tragen sollen.
======

[.instruction]
Versandkosten bei Rückerstattung festlegen:

. Öffne das Menü *Aufträge » Aufträge*.
. Führe die Suche (material:search[]) aus, um Aufträge anzuzeigen.
. Öffne den Auftrag, in dem du die Versandkosten festlegen möchtest. Beachte, dass Aufträge nur in der Listenansicht geöffnet werden können.
. Klicke auf *Aufträge erstellen* (material:shopping_cart[]) und wähle die Option *Gewährleistung bzw. Gutschrift > Für bestimmte Auftragspositionen*. +
→ Der Kindauftrag vom Typ *Gewährleistung* oder *Gutschrift* wird geöffnet.
. Wähle für den Artikel im Feld *Versandkosten kopieren* die Option *Ja*, um die Versandkosten zu übernehmen. +
→ Das Feld *Versandkosten in €* wird sichtbar. +
*_Hinweis:_* Hier sind zunächst die Versandkosten des Hauptauftrags voreingestellt.
. Möchtest du die Versandkosten anpassen, die der Kund:in zurückerstattet werden sollen, gib einen anderen Betrag im Feld *Versandkosten in €* ein.
. Klicke rechts auf *Zum Warenkorb hinzufügen* (material:add_shopping_cart[]). +
→ Der Artikel wird zum Warenkorb hinzugefügt.
. *Speichere* (material:save[]) die Einstellungen. +
→ Die Versandkosten für die Rückerstattung des Artikels werden übernommen.

[#create-document-credit-note]
== Dokument Gutschrift erstellen

Nach dem Anlegen des Gutschriftauftrags muss das Dokument *Gutschrift* direkt im Gutschriftauftrag erstellt werden. Vor dem ersten Erzeugen dieses Dokuments muss die Dokumentenvorlage im Menü *Einrichtung » Mandant » [Mandant wählen] » Standorte » [Standort wählen] » Dokumente » Gutschrift* eingerichtet werden.

Bevor du aber das Dokument im Gutschriftauftrag erzeugst, solltest du die im Gutschriftauftrag enthaltenen Auftragspositionen prüfen und bei Bedarf anpassen.

[.instruction]
Dokument *Gutschrift* erstellen:

. Öffne das Menü *Aufträge » Aufträge*.
. Führe die Suche (material:search[]) aus, um Aufträge anzuzeigen.
. Klicke rechts in der Zeile der Gutschrift auf das Kontextmenü (material:more_vert[]).
. Wähle *Dokument erstellen* > *Gutschrift*. +
icon:map-signs[] *_Oder:_* Öffne den Gutschriftauftrag, für den du das Dokument *Gutschrift* erstellen möchtest. Beachte, dass Aufträge nur in der Listenansicht geöffnet werden können.
. Gehe in den Bereich *Dokumente*.
. Klicke auf *Dokument erstellen* (material:add[]).
. Wähle die Option *Gutschrift*. +
→ Das Fenster zum Erstellen des Dokuments wird geöffnet.
. Nimm bei Bedarf Einstellungen vor.
. Klicke auf *Ausführen*. +
→ Das Dokument *Gutschrift* wird erzeugt.

[#correct-and-cancel-credit-note-document]
== Dokument Gutschrift korrigieren und stornieren

Einen Gutschriftauftrag und das dazugehörige Dokument korrigierst du, indem du zunächst einen *Stornobeleg Gutschrift* erzeugst. Danach ist der Gutschriftauftrag auch wieder entsperrt. Denn nach dem Erstellen eines Gutschriftdokuments ist der Gutschriftauftrag selbst für die Bearbeitung gesperrt, damit steuerrelevante Daten nicht verändert werden können. Anschließend kann der Gutschriftauftrag wieder bearbeitet werden. Du kannst die Daten korrigieren und ein neues Dokument für die Gutschrift erstellen.

Vor dem ersten Erzeugen des Dokuments muss im Menü *Einrichtung » Mandant » [Mandant wählen] » Standorte » [Standort wählen] » Dokumente » Stornobeleg Gutschrift* zunächst die xref:auftraege:auftragsdokumente-neu.adoc#300[Vorlage] für das Dokument *Stornobeleg Gutschrift* eingerichtet werden.

[IMPORTANT]
.Stornieren eines Gutschriftdokuments
====
Das Stornieren eines Gutschriftdokuments dient der nachvollziehbaren Korrektur von steuerrelevanten Daten und *nicht* der Stornierung eines Gutschriftauftrags selbst.
====

Gehe zur Korrektur eines Gutschriftauftrags und der Erstellung eines *Stornobelegs Gutschrift* wie im Folgenden beschrieben vor.

[.instruction]
Gutschriftauftrag korrigieren:

. Öffne das Menü *Aufträge » Aufträge*.
. Führe die Suche (material:search[]) aus, um Aufträge anzuzeigen.
. Klicke rechts in der Zeile der Gutschrift auf das Kontextmenü (material:more_vert[]).
. Wähle *Dokument erstellen* > *Stornobeleg Gutschrift*. +
icon:map-signs[] *_Oder:_* Öffne den Gutschriftauftrag, für den du den *Stornobeleg Gutschrift* erstellen möchtest. Beachte, dass Aufträge nur in der Listenansicht geöffnet werden können.
. Klicke im Bereich *Dokumente* auf *Dokument erstellen* (material:add[]).
. Wähle die Option *Stornobeleg Gutschrift*. +
*_Hinweis:_* Diese Option ist nur verfügbar, wenn bereits ein Gutschriftdokument erstellt wurde.
. Nimm bei Bedarf Einstellungen vor.
. Klicke anschließend auf *Ausführen*. +
→ Der Stornobeleg wird erzeugt.
. Klicke anschließend erneut auf *Dokument erstellen* (material:add[]).
. Wähle die Option *Gutschrift*, um ein neues Gutschriftdokument zu erstellen.
. Nimm bei Bedarf Einstellungen vor.
. Klicke anschließend auf *Ausführen*. +
→ Das neue Gutschriftdokument wird erzeugt.

[#booking-refunds]
== Rückzahlungen buchen

Nachdem du ein Gutschriftdokument erstellt hast, muss die Rückzahlung des gutgeschriebenen Betrags in deinem plentymarkets System gebucht werden. Rückzahlungen über bestimmte Zahlungsarten, die du in deinem System eingerichtet hast, buchst du direkt im Bereich *Zugeordnete Zahlungen* des Gutschriftauftrags.

[IMPORTANT]
.Bedingung bei PayPal
====
Bei *PayPal* ist es nicht möglich, höhere Beträge einzugeben als mit der ursprünglichen Paypal-Transaktion bezahlt wurden.
====

[.instruction]
Rückzahlung buchen:

. Öffne das Menü *Aufträge » Aufträge*.
. Führe die Suche (material:search[]) aus, um Aufträge anzuzeigen.
. Öffne den Gutschriftauftrag, für den du eine Rückzahlung buchen möchtest. Beachte, dass Aufträge nur in der Listenansicht geöffnet werden können.
. Gehe in den Bereich *Zugeordnete Zahlungen*.
. Klicke auf *Zahlung erstellen* (material:add[]).
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<table-booking-refunds>>.
. Klicke auf *Ausführen*. +
→ Die Rückzahlung wird gebucht.

[[table-booking-refunds]]
.Einstellungen zum Buchen von Rückzahlungen
[cols="1,3"]
|===

| *Auftrags-ID*
|Zeigt die Auftrags-ID an.

| *Betrag*
|Zeigt den Betrag an, der zurückgebucht wird. Passe den Betrag bei Bedarf an.

| *Haben/Soll*
|Wähle aus der Dropdown-Liste, ob es sich um eine Haben-/oder Soll-Buchung handelt.

| *Währung*
|Wähle eine Währung aus der Dropdown-Liste.

| *Wechselkurs*
|Zeigt den Wechselkurs an.

| *Verwendungszweck*
|Gib einen Verwendungszweck ein.

| *Zahlungseingang*
|Gib ein Datum für den Zahlungseingang ein oder wähle ein Datum über den Kalender (material:today[]). Das aktuelle Datum ist voreingestellt.

|===
