= Auftragstypen

:keywords: Auftragstypen, Übersicht Auftragstypen
:author: team-order-core
:description: Erfahre, welche Auftragstypen dir in plentymarkets zur Verfügung stehen.

Mithilfe von Auftragstypen werden die unterschiedlichen Geschäftsvorfälle von Aufträgen kenntlich gemacht. Welche Möglichkeiten dir Auftragstypen bieten und wie du mit diesen arbeitest, erfährst du auf den unten aufgeführten Seiten.
Die folgenden Auftragstypen stehen dir in plentymarkets zur Verfügung.

* xref:auftraege:order-type-offer.adoc#[Angebot]
* xref:auftraege:order-type-order.adoc#[Auftrag]
* xref:auftraege:order-type-warranty.adoc#[Gewährleistung]
* xref:auftraege:order-type-credit-note.adoc#[Gutschrift]
* xref:auftraege:order-type-delivery-order.adoc#[Lieferauftrag]
* xref:auftraege:order-type-repair.adoc#[Reparatur]
* xref:auftraege:order-type-return.adoc#[Retoure]
* xref:auftraege:order-type-multi-order.adoc#[Sammelauftrag]
* xref:auftraege:order-type-multi-order.adoc#generate-multi-credit-note[Sammelgutschrift]
* xref:auftraege:order-type-advance-order.adoc#[Vorbestellung]

[TIP]
.Ansicht der Auftragstypen individualisieren
Über den xref:auftraege:design-order-view.adoc#editing-mode[Bearbeitungsmodus] kannst du die Ansicht der unterschiedlichen Auftragstypen nach deinen Wünschen individuell gestalten. Wähle beispielsweise, welche Felder für die verschiedenen xref:auftraege:working-with-orders.adoc#order-areas[Bereiche] angezeigt werden sollen.
