= Auftragstyp Retoure

:keywords: Retoure, Retourengrund, retournierte Artikel, Rücksendeschein, Waren zurückbuchen, Warenbestand zurückbuchen
:author: team-order-core
:description: Erfahre, wie du anhand des Auftragstyps Retoure Retouren erstellst. Lerne außerdem, wie du Retourengründe anlegst, Rücksendescheine erstellst und Ware zurückbuchst.

Der Auftragstyp *Retoure* bildet den Geschäftsvorfall einer Retoure ab. Retouren können manuell erfasst werden. Zusätzlich kannst du deinen Webshop-Kund:innen auch erlauben, Retouren über den *Mein Konto*-Bereich anzumelden. Das Erfassen einer Retoure bucht die retournierten Artikel noch nicht zurück in den Warenbestand. Du erfasst also die retournierten Artikel zunächst und entscheidest anschließend, ob die Artikel wieder zum Bestand gebucht werden sollen, oder ob weitere Schritte, wie z.B. eine Reparatur, notwendig sind. Die Retoure ist ein untergeordneter Auftragstyp, da Retouren entweder einem Auftrag oder einer Gewährleistung zugeordnet sind.
Bevor du Retouren erfassen kannst, lege xref:auftraege:order-type-return.adoc#enter-return-reasons[Retourengründe] und <<#status-returned-items, Artikelstatus für retournierte Artikel>> an.

Der Standard-Status für Retouren ist Status 9. Jede Retoure, die erfasst wird, erhält automatisch diesen Status. Du kannst jedoch oben in den *Einstellungen* einen anderen Status als *Standard-Status* für Retouren festlegen.

[#enter-return-reasons]
== Retourengründe anlegen

Du kannst bis zu 20 Retourengründe anlegen. Beim Erfassen einer Retoure wählst du dann für jede Auftragsposition einen Grund. Anhand von Retourengründen ist später nachvollziehbar, ob ein Artikel besonders häufig wegen des selben Grundes retourniert wurde. Die Retourengründe können in mehreren Sprachen angelegt werden.

[.instruction]
Retourengründe anlegen:

. Öffne das Menü *Einrichtung » Aufträge » Auftragstypen » Retoure*.
. Klicke oben links auf *Neuen Retourengrund erstellen* (material:add[]). +
→ Das Fenster *Neuen Retourengrund erstellen* wird geöffnet.
. Gib eine *Retourengrund-ID* ein.
. Gib einen Namen für die jeweilige Sprache ein. +
*_Tipp:_* Klicke auf *Sprache hinzufügen* (material:add[]), um weitere Sprachen hinzuzufügen und gib für alle gewählten Sprachen einen Namen ein. +
. Klicke auf *Erstellen* (material:add[role=green]), um den Retourengrund zu erstellen.

[#configure-columns-return-reasons]
== Spalten für Retourengründe konfigurieren

In der Übersicht kannst du selbst entscheiden, welche Spalten in der Tabelle für Retourengründe sichtbar sein sollen und in welcher Reihenfolge diese angezeigt werden. Um die Spalten zu konfigurieren, gehe vor wie folgt.

[.instruction]
Spalten für Retourengründe konfigurieren:

. Öffne das Menü *Einrichtung » Aufträge » Auftragstypen » Retoure*.
. Klicke oben rechts in der Tabelle der Retourengründe auf *Spalten konfigurieren* (material:settings[]). +
→ Das Fenster *Spalten konfigurieren* wird geöffnet.
. Wähle die Spalten, die angezeigt werden sollen (material:done[]). Beachte dazu die Erläuterungen in <<table-return-reasons-columns>>.
. Ziehe (material:drag_indicator[]) die Spalten per Drag-and-drop an die gewünschte Stelle, bis sie in der für dich richtigen Reihenfolge angezeigt werden.
. Füge bei Bedarf Spalten hinzu oder wähle Spalten ab, wenn du sie nicht benötigst.
. Klicke auf *Bestätigen*. +
→ Die Einstellungen werden gespeichert.

[[table-return-reasons-columns]]
.Spalten für Retourengründe
[cols="1,3"]
|===
|Spalte |Erläuterung

| *Retourengrund-ID*
|Zeigt die ID des Retourengrunds an.

| *Name*
|Zeigt den Namen des Retourengrunds an.

| *Name (Sprache)*
|Zeigt den Namen des Retourengrunds für die in Klammern angegebene Sprache an. Wähle hier die Sprachen, die du benötigst.

| *Aktionen*
|Zeigt am Ende der Zeile die Funktionen zum Bearbeiten (material:edit[]) und Löschen (material:delete[]) des Retourengrunds an.

|===

[#edit-return-reason]
=== Retourengrund bearbeiten

Um einen Retourengrund zu bearbeiten, gehe vor wie folgt. Beachte, dass lediglich der Name, nicht aber die ID eines Retourengrunds geändert werden kann.

[.instruction]
Retourengrund bearbeiten:

. Öffne das Menü *Einrichtung » Aufträge » Auftragstypen » Retoure*.
. Klicke rechts in der Zeile des Retourengrunds, den du bearbeiten möchtest, auf *Retourengrund bearbeiten* (material:edit[]). +
→ Die Einstellungen des Retourengrunds werden geöffnet.
. Passe den Namen für eine oder mehrere Sprachen an.
. *Speichere* (material:save[role=skyBlue]) die Änderungen.

[#delete-return-reason]
=== Retourengrund löschen

Um einen Retourengrund zu löschen, gehe vor wie folgt.

. Öffne das Menü *Einrichtung » Aufträge » Auftragstypen » Retoure*.
. Klicke rechts in der Zeile des Retourengrunds, den du löschen möchtest, auf *Retourengrund löschen* (material:delete[]). +
→ Der Retourengrund wird gelöscht.

[#status-returned-items]
== Status für retournierte Artikel anlegen

Du kannst bis zu 12 Artikelstatus anlegen. Die Status kannst du z.B. nutzen, um einerseits den Zustand der retournierten Artikel, und andererseits den Fortschritt beim Bearbeiten der retournierten Artikel anzugeben. Die Status stehen in einer Retoure im Bereich *Status und Tags* zur Auswahl. Um je nach Fortschritt der Bearbeitung verschiedene Status zuzuweisen, lege die benötigten Status an. Du kannst Retourenstatus in mehreren Sprachen erstellen.

[.instruction]
Status für retournierte Artikel anlegen:

. Öffne das Menü *Einrichtung » Aufträge » Auftragstypen » Retoure*.
. Klicke oben links auf *Neuen Artikelstatus erstellen* (material:add[]). +
→ Das Fenster *Neuen Artikelstatus erstellen* wird geöffnet.
. Gib eine *Artikelstatus-ID* ein.
. Gib einen Namen für die jeweilige Sprache ein. +
*_Tipp:_* Klicke auf *Sprache hinzufügen* (material:add[]), um weitere Sprachen hinzuzufügen und gib für alle gewählten Sprachen einen Namen ein. +
. Klicke auf *Erstellen* (material:add[role=green]), um den Artikelstatus zu erstellen.

[#configure-columns-item-statuses]
== Spalten für Artikelstatus konfigurieren

In der Übersicht kannst du selbst entscheiden, welche Spalten in der Tabelle für Artikelstatus sichtbar sein sollen und in welcher Reihenfolge diese angezeigt werden. Um die Spalten zu konfigurieren, gehe vor wie folgt.

[.instruction]
Spalten für Artikelstatus konfigurieren:

. Öffne das Menü *Einrichtung » Aufträge » Auftragstypen » Retoure*.
. Klicke oben rechts in der Tabelle der Artikelstatus auf *Spalten konfigurieren* (material:settings[]). +
→ Das Fenster *Spalten konfigurieren* wird geöffnet.
. Wähle die Spalten, die angezeigt werden sollen (material:done[]). Beachte dazu die Erläuterungen in <<table-item-statuses-columns>>.
. Ziehe (material:drag_indicator[]) die Spalten per Drag-and-drop an die gewünschte Stelle, bis sie in der für dich richtigen Reihenfolge angezeigt werden.
. Füge bei Bedarf Spalten hinzu oder wähle Spalten ab, wenn du sie nicht benötigst.
. Klicke auf *Bestätigen*. +
→ Die Einstellungen werden gespeichert.

[[table-item-statuses-columns]]
.Spalten für Artikelstatus
[cols="1,3"]
|===
|Spalte |Erläuterung

| *Artikelstatus-ID*
|Zeigt die ID des Artikelstatus an.

| *Name*
|Zeigt den Namen des Artikelstatus an.

| *Name (Sprache)*
|Zeigt den Namen des Artikelstatus für die in Klammern angegebene Sprache an. Wähle hier die Sprachen, die du benötigst.

| *Aktionen*
|Zeigt am Ende der Zeile die Funktionen zum Bearbeiten (material:edit[]) und Löschen (material:delete[]) des Artikelstatus an.

|===

[#edit-item-status]
=== Artikelstatus bearbeiten

Um einen Artikelstatus zu bearbeiten, gehe vor wie folgt. Beachte, dass lediglich der Name, nicht aber die ID eines Artikelstatus geändert werden kann.

[.instruction]
Artikelstatus bearbeiten:

. Öffne das Menü *Einrichtung » Aufträge » Auftragstypen » Retoure*.
. Klicke rechts in der Zeile des Artikelstatus, den du bearbeiten möchtest, auf *Artikelstatus bearbeiten* (material:edit[]). +
→ Die Einstellungen des Artikelstatus werden geöffnet.
. Passe den Namen für eine oder mehrere Sprachen an.
. *Speichere* (material:save[role=skyBlue]) die Änderungen.

[#delete-item-status]
=== Artikelstatus löschen

Um einen Artikelstatus zu löschen, gehe vor wie folgt.

. Öffne das Menü *Einrichtung » Aufträge » Auftragstypen » Retoure*.
. Klicke rechts in der Zeile des Artikelstatus, den du löschen möchtest, auf *Artikelstatus löschen* (material:delete[]). +
→ Der Artikelstatus wird gelöscht.

[TIP]
.Daten aktualisieren
====
Klicke oberhalb der jeweiligen Tabelle auf *Daten aktualisieren* (material:refresh[]), um die Daten der Tabelle auf den neuesten Stand zu bringen.
====

[#create-and-edit-return]
== Retoure erfassen und bearbeiten

Eine Retoure erfasst du manuell, wenn ein Paket bei dir eingegangen ist oder du erlaubst deinen registrierten Webshop-Kund:innen, direkt im Kundenkonto des Shops Retouren anzumelden. Nachdem eine Retoure erfasst wurde, werden weitere Bearbeitungsmöglichkeiten sichtbar. So kannst du z.B. den Artikelstatus der retournierten Artikel erst nach dem Erfassen angeben.

[#create-return]
=== Retoure erfassen

[.instruction]
Gehe folgendermaßen vor, um eine Retoure zu erfassen:

. Öffne das Menü *Aufträge » Aufträge (Testphase)*.
. Führe die Suche (material:search[]) aus, um Aufträge anzuzeigen.
. Öffne den Auftrag oder die Gewährleistung, für die eine Retoure angelegt werden soll. Beachte, dass Aufträge nur in der Listenansicht geöffnet werden können.
. Klicke oben auf *Aufträge erstellen* (material:shopping_cart[]) > *Retoure*.
. Wähle die Option *Für bestimmte Auftragspositionen*. +
→ Die Übersicht zum Anlegen der Retoure wird geöffnet.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<table-settings-return>>.
. *Speichere* (material:save[]) die Einstellungen. +
→ Die Retoure wird erfasst.

[[table-settings-return]]
.Einstellungen zum Erfassen einer Retoure
[cols="1,3"]
|===
|Einstellung |Erläuterung

| *Status*
|Wähle einen Status aus der Dropdown-Liste. Der Standard-Status, der im Menü *Einrichtung » Aufträge » Einstellungen* gespeichert wurde, ist voreingestellt.

| *Eigner*
|Wähle einen Eigner aus der Dropdown-Liste, der dem Retourenauftrag zugewiesen wird.

| *Retourengrund übertragen*
|Wähle einen Grund aus der Dropdown-Liste, der für alle Artikel der Retoure gilt. +
Wählst du hier einen Grund, hat dieser Grund Priorität gegenüber den einzeln wählbaren Gründen auf Artikelpositionsebene.

| *Paketcode der Retoure*
|Gib den Paketcode der Retoure ein.

2+^| *Artikelinformationen*

| *Füge alle offenen Mengen in den Warenkorb* (material:playlist_add[])
|Fügt alle offenen Mengen dem Warenkorb hinzu.

| *Artikel-ID*
|Zeigt die Artikel-ID an.

| *Varianten-ID*
|Zeigt die Varianten-ID an.

| *Variantennummer*
|Zeigt die Variantennummer an.

| *Menge*
|Zeigt die Menge des Artikels an. Passe die Menge bei Bedarf an.

| *Verbleibende Stückzahl*
|Zeigt die verbleibende Stückzahl des Artikels an.

| *Offene Menge*
|Zeigt die offene Menge des Artikels an.

| *Artikelname*
|Zeigt den Name des Artikels an.

| *Zum Warenkorb hinzufügen* (material:add_shopping_cart[])
|Fügt nur bestimmte Artikel zur Retoure hinzu. Diese Schaltfläche ist nur verfügbar, wenn mindestens 1 Artikel vorhanden ist. +
*_Tipp:_* Passe die Artikelmenge bei Bedarf im Feld *Menge* an.

2+^| *Warenkorb*

| *Artikel aus Warenkorb entfernen* (material:delete[])
|Leert den Warenkorb komplett. Möchtest du nur bestimmte Artikel entfernen, klicke rechts neben dem jeweiligen Artikel auf *Artikel aus Warenkorb entfernen* (material:delete[]).

| *Artikel-ID*
|Zeigt die Artikel-ID an.

| *Varianten-ID*
|Zeigt die Varianten-ID an.

| *Menge*
|Zeigt die Artikelmenge an. Passe die Menge bei Bedarf an.

| *Artikelname*
|Zeigt den Artikelname an. Passe den Name bei Bedarf an.

| *Retourengrund*
|Zeigt den Retourengrund an. Wähle bei Bedarf einen anderen Retourengrund aus der Dropdown-Liste.

| *Artikelstatus*
|Zeigt den Artikelstatus an. Wähle bei Bedarf einen anderen Status aus der Dropdown-Liste.

| *Verbleibender Positionswert [%]*
|Zeigt den verbleibenden Positionswert in % an. Passe den Wert bei Bedarf an.

|===


[#create-return-label]
== Rücksendeschein erstellen

//link für Rücksendeschein nach Umzug anpassen

Einen Rücksendeschein kannst du deinen Kund:innen bei Zustellung der Ware im Paket beilegen. In diesem Fall sollte der Rücksendeschein Blankofelder für die Retourengründe enthalten. Du kannst deinen Kund:innen aber auch erlauben, den Rücksendeschein im *Mein Konto*-Bereich auszufüllen, auszudrucken und der Retoure beizulegen.
Bevor Rücksendescheine erzeugt werden können, muss die Dokumentenvorlage xref:auftraege:ruecksendeschein-erzeugen.adoc#[Rücksendeschein] im Menü *Einrichtung » Mandant » [Mandant wählen] » Standorte » [Standort wählen] » Dokumente » Rücksendeschein* eingerichtet werden.

[TIP]
.Retourengründe auf der Vorlage einstellen
======
Du kannst einen unausgefüllten Rücksendeschein in jedem Paket beilegen, das du versendest. Hierfür generierst du den Rücksendeschein direkt im Auftrag, ohne dass es überhaupt eine Retoure geben muss. Die zweite Möglichkeit ist, dass du deinen Webshop-Kund:innen erlaubst, Retouren im Mein Konto-Bereich des Shops anzumelden und hier die Retourengründe anzugeben. Anschließend kann der Rücksendeschein ausgefüllt ausdruckt werden. Egal wie du den Rücksendeschein deinen Kund:innen zukommen lässt: Damit Retourengründe eingetragen werden können, musst du die Spalte *Retourengründe* unterhalb der Artikelpositionen platzieren.
======

Prüfe die Artikelpositionen des Auftrags und ändere bei Bedarf die Optionen, z.B. die Menge eines Artikels, bevor du einen Rücksendeschein erzeugst.

[.instruction]
Rücksendeschein manuell erstellen:

. Öffne das Menü *Aufträge » Aufträge (Testphase)*.
. Führe die Suche (material:search[]) aus, um Aufträge anzuzeigen.
. Klicke rechts in der Zeile der Retoure auf das Kontextmenü (material:more_vert[]).
. Wähle *Dokument erstellen* > *Rücksendeschein*. +
icon:map-signs[] *_Oder:_* Öffne die Retoure, für die du einen Rücksendeschein erstellen möchtest. Beachte, dass Retouren nur in der Listenansicht geöffnet werden können.
. Gehe in den Bereich *Dokumente*.
. Klicke auf *Dokument erstellen* (material:add[]).
. Wähle die Option *Rücksendeschein*.
. Nimm die Einstellungen für den Rücksendeschein vor. Beachte dazu die Erläuterungen in <<table-generate-return-slip>>.
. Klicke anschließend auf *Ausführen*, um den Rücksendeschein zu erstellen.

[[table-generate-return-slip]]
.Einstellungen für Rücksendescheine
[cols="1,3"]
|===
|Einstellung |Erläuterung

| *Datum*
|Gib ein Datum ein oder wähle ein Datum über den Kalender (material:today[]). Dieses Datum wird dann auf dem Rücksendeschein angezeigt. Das aktuelle Datum ist voreingestellt.

| *Kommentar*
|Gib optional einen Kommentar ein, der auf dem Rücksendeschein angezeigt werden soll.

|===

[TIP]
.Rücksendeschein automatisch generieren
======
Richte eine Ereignisaktion ein, die den Rücksendeschein automatisch generiert. Wenn du hier als Ereignis *Neue Retoure (durch Kunden)* einstellst und nach der Herkunft *Webshop* filterst, kannst du ausgefüllte Rücksendescheine generieren und musst diese dann lediglich noch zum Download für Kund:innen bereitstellen.
======

[#book-back-items]
== Waren zurückbuchen

Wenn du einen Artikel über eine Retoure zurück erhältst, kannst du den Warenbestand ganz oder teilweise zurückbuchen oder auch den gesamten Warenausgang zurücksetzen.

[.instruction]
Waren zurückbuchen:

//Positionen zurückbuchen vs. Artikel zurückbuchen? Terminologie klären + in Konfig und Tabelle ggf. anpassen

. Öffne das Menü *Aufträge » Aufträge (Testphase)*.
. Führe die Suche (material:search[]) aus, um Aufträge anzuzeigen.
. Öffne die Retoure, für die du Waren zurückbuchen möchtest. Beachte, dass Retouren nur in der Listenansicht geöffnet werden können.
. Klicke oben auf das Kontextmenü (material:more_vert[] und wähle *Waren zurückbuchen* (material:input[]).
. Wähle *Ausgewählte Positionen zurückbuchen*, um nur bestimmte Positionen zurückzubuchen oder *Alle Positionen zurückbuchen*, um alle Positionen zurückzubuchen. Beachte dazu die Erläuterungen in <<table-book-back-items>>.
. *Speichere* (material:save[]) die Einstellungen. +
→ Die Waren werden zurückgebucht.

Die Vorgehensweise zum Zurückbuchen des Warenbestands ist auch für Retouren zu Aufträgen mit Lieferaufträgen gleich.

[[table-book-back-items]]
.Optionen zum Zurückbuchen von Waren
[cols="1,3"]
|===
|Einstellung |Erläuterung

| *Alle Positionen zurückbuchen*
|Setzt den Warenausgang vollständig zurück. Auch das Datum des Warenausgangs wird gelöscht.

2+^| *Ausgewählte Positionen zurückbuchen*

| *Füge alle offenen Mengen in den Warenkorb* (material:playlist_add[])
|Fügt alle offenen Mengen dem Warenkorb hinzu.

| *Menge*
|Zeigt die Menge des Artikels an.

| *Offene Menge*
|Zeigt die offene Menge des Artikels an.

| *Verbleibende Stückzahl*
|Zeigt die verlbeibende Stückzahl des Artikels an.

| *Charge*
|Zeigt die Chargennummer des Artikels an.

| *MHD*
|Zeigt das Mindesthaltbarkeitsdatum des Artikels an.

| *Artikel-ID*
|ID des Artikels

| *Attribute*
|Attribute des Artikels

| *Varianten-ID*
|ID der Variante

| *Artikelname*
|Name des Artikels

2+^| *Warenkorb*

| *Artikel-ID*
|ID des Artikels

| *Artikelname*
|Name des Artikels

| *Varianten-ID*
|ID der Variante

| *MHD*
|Zeigt das Mindeshaltbarkeitsdaum des Artikels an.

| *Charge*
|Zeigt die Chargennumer des Artikels an.

| *Lager*
|Das Lager wählen, in das die Artikel zurückgebucht werden sollen.

| *Auftragsmenge*
|Zeigt die Menge der Artikel an, die im Auftrag enthalten sind.

| *Rückbuchung*
|Wenn Teilmengen zurückgebucht werden sollen, dann hier die Artikelmengen manuell eintragen.

| *Lagerort*
|Den Lagerort wählen, in den die Artikel zurückgebucht werden sollen.

|===

[TIP]
.Retouren-Artikel im Zulauf
======
Im Menü xref:warenwirtschaft:rueckstandsliste-verwalten.adoc#400[Waren » Retouren » Zulauf] findest du eine Übersicht aller durch Retouren im Zulauf befindlichen Artikel.
======
