= Auftragstyp Retoure

:keywords: Retoure, Retourengrund, retournierte Artikel, Rücksendeschein, Waren zurückbuchen, Warenbestand zurückbuchen
:author: team-order-core

//adjust links
Der Auftragstyp Retoure bildet den Geschäftsvorfall einer Retoure ab. Retouren können manuell erfasst werden. Zusätzlich kannst du deinen Webshop-Kund:innen auch erlauben, Retouren über den *Mein Konto*-Bereich anzumelden. Das Erfassen einer Retoure bucht die retournierten Artikel noch nicht zurück in den Warenbestand. Du erfasst also die retournierten Artikel zunächst und entscheidest anschließend, ob die Artikel wieder zum Bestand gebucht werden sollen, oder ob weitere Schritte, wie z.B. eine Reparatur, notwendig sind. Die Retoure ist ein untergeordneter Auftragstyp, da Retouren entweder einem Auftrag oder einer Gewährleistung zugeordnet sind.
Bevor du Retouren erfassen kannst, lege xref:auftraege:order-type-return.adoc#enter-return-reasons[Retourengründe] und xref:auftraege:auftraege-verwalten.adoc#420[Artikelstatus für retournierte Artikel] an.

Der Standardstatus für Retouren ist Status 9. Jede Retoure, die erfasst wird, erhält automatisch diesen Status. Du kannst jedoch jederzeit im Menü *Einrichtung » Aufträge » Einstellungen* einen anderen Status als xref:auftraege:preparatory-settings.adoc#intable-default-status-return[Standard-Status Retoure] festlegen.

[#enter-return-reasons]
== Retourengründe eintragen

Du kannst bis zu 20 Retourengründe eintragen. Beim Erfassen einer Retoure wählst du dann für jede Auftragsposition einen Grund. Anhand von Retourengründen ist später nachvollziehbar, ob ein Artikel besonders häufig wegen des selben Grundes retourniert wurde. Die Retourengründe können in mehreren Sprachen hinterlegt werden.

[.instruction]
Retourengründe anlegen:

. Öffne das Menü *Einrichtung » Aufträge » Auftragstypen » Retoure*.
. Wähle die *Sprache* aus der Dropdown-Liste aus.
. Trage *Gründe* für Retouren für die ausgewählte Sprache ein.
. *Speichere* die Einstellungen.
. Wiederhole dies ggf. für weitere Sprachen.

[#420]
== Status für retournierte Artikel eintragen

Du kannst bis zu 12 Artikelstatus anlegen. Die Status kannst du z.B. nutzen, um einerseits den Zustand der retournierten Artikel, aber auch um den Fortschritt beim Bearbeiten der retournierten Artikel anzugeben. Die Status stehen in einer Retoure im Tab *Übersicht* bei den Auftragspositionen zur Wahl. Um je nach Fortschritt der Bearbeitung verschiedene Status zuzuweisen, lege die benötigten Status an. Du kannst Retourenstatus in mehreren Sprachen hinterlegen.

[.instruction]
Status für retournierte Artikel eintragen:

. Öffne das Menü *Einrichtung » Aufträge » Auftragstypen » Retoure*.
. Wähle die *Sprache* aus der Dropdown-Liste aus.
. Trage die gewünschten *Status* für die Zuordnung zurückgesendeter Artikel für die ausgewählte Sprache ein.
. *Speichere* (icon:save[role="green"]) die Einstellungen.
. Wiederhole dies ggf. für weitere Sprachen.

[#440]
== Retoure erfassen und bearbeiten

Eine Retoure erfasst du manuell, wenn ein Paket bei dir eingegangen ist oder du erlaubst deinen registrierten Webshop-Kund:innen, direkt im Kundenkonto des Shops Retouren anzumelden. Nachdem eine Retoure erfasst wurde, werden weitere Bearbeitungsmöglichkeiten sichtbar. So kannst du z.B. den Artikelstatus der retournierten Artikel erst nach dem Erfassen angeben.

=== Retoure erfassen
// auf neue UI anpassen

[.instruction]
Gehe folgendermaßen vor, um eine Retoure zu erfassen:

. Öffne das Menü *Aufträge » Aufträge (Testphase)*.
. Führe die Suche aus, um Aufträge anzuzeigen.
. Öffne den Auftrag oder die Gewährleistung, für die eine Retoure angelegt werden soll.
. Klicke oben auf *Aufträge erstellen* (material:shopping_cart[]).
. Wähle die Option *Retoure* > *Für bestimmte Artikel*. +
→ Die Übersicht zum Anlegen der Retoure wird geöffnet.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<table-settings-return>>.
. *Speichere* (material:save[]) die Einstellungen. +
→ Die Retoure wird erfasst.

[[table-settings-return]]
.Einstellungen zum Erfassen einer Retoure
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+^| *Retoure-Einstellungen*

| *Status*
|Wähle einen Status aus der Dropdown-Liste. Der Standardstatus, der im Menü *Einrichtung » Aufträge » Einstellungen* gespeichert wurde, ist voreingestellt.

| *Eigner*
|Wähle einen Eigner, der dem Retourenauftrag zugewiesen wird.

| *Retourengrund übertragen*
|Wähle einen Grund aus der Dropdown-Liste, der für alle Artikel der Retoure gilt. +
Wählst du hier einen Grund, hat dieser Grund Priorität gegenüber den einzeln wählbaren Gründen auf Artikelpositionsebene.

| *Paketcode der Retoure*
|Gib den Paketcode der Retoure ein.

2+^| *Artikelinformationen*
// icon?
| *Füge alle offenen Mengen in den Warenkorb*
|Klicke links oberhalb der Tabelle der verfügbaren Artikel auf *Füge alle offenen Mengen in den Warenkorb*, um alle offenen Mengen in den Warenkorb hinzuzufügen.

| *Artikel-ID*
|Zeigt die Artikel-ID an. Dieses Feld kann nicht bearbeitet werden.

| *Varianten-ID*
|Zeigt die Varianten-ID an. Dieses Feld kann nicht bearbeitet werden.

| *Variantennummer*
|Zeigt die Variantennummer an. Dieses Feld kann nicht bearbeitet werden.

| *Menge*
|Zeigt die Menge des Artikels an. Passe die Menge bei Bedarf an.

| *Verbleibende Stückzahl*
|Zeigt die verbleibende Stückzahl des Artikels an. Dieses Feld kann nicht bearbeitet werden.

| *Offene Menge*
|Zeigt die offene Menge des Artikels an. Dieses Feld kann nicht bearbeitet werden.

| *Artikelname*
|Zeigt den Name des Artikels an. Dieses Feld kann nicht bearbeitet werden.

| *Zum Warenkorb hinzufügen* (material:add_shopping_cart[])
|Möchtest du nicht alle, sondern nur bestimmte Artikel zur Retoure hinzufügen, klicke rechts neben den gewünschten Artikeln auf *Zum Warenkorb hinzufügen* (material:add_shopping_cart[]). Diese Schaltfläche ist nur verfügbar, wenn mindestens 1 Artikel vorhanden ist. +
*_Tipp:_* Passe die Artikelmenge bei Bedarf im Feld *Menge* an.

2+^| Warenkorb

| *Artikel aus Warenkorb entfernen* (material:delete[])
|Möchtest du alle Artikel aus dem Warenkorb entfernen, klicke links oben in der Tabelle des Warenkorbs auf *Artikel aus Warenkorb entfernen* (material:delete[]), um den Warenkorb komplett zu leeren. Möchtest du nur bestimmte Artikel entfernen, klicke rechts neben dem jeweiligen Artikel auf *Artikel aus Warenkorb entfernen* (material:delete[]).

| *Artikel-ID*
|Zeigt die Artikel-ID an. Dieses Feld kann nicht bearbeitet werden.

| *Varianten-ID*
|Zeigt die Varianten-Id an. Dieses Feld kann nicht bearbeitet werden.

| *Menge*
|Zeigt die Artikelmenge an. Passe die Menge bei Bedarf an.

| *Artikelname*
|Zeigt den Artikelname an. Passe den Name bei Bedarf an.

| *Retourengrund*
|Zeigt den Retourengrund an. Wähle bei Bedarf einen anderen Retourengrund aus der Dropdown-Liste.

| *Artikelstatus*
|Zeigt den Artikelstatus an. Wähle bei Bedarf einen anderen Status aus der Dropdown-Liste.

| *Verbleibender Positionswert [%]*
|Zeigt den verbleibenden Positionswert in % an. Passe den Wert bei Bedarf an.

|====


[#450]
== Rücksendeschein erstellen

Einen Rücksendeschein kannst du deinen Kund:innen bei Zustellung der Ware im Paket beilegen. In diesem Fall sollte der Rücksendeschein Blankofelder für die Retourengründe enthalten. Du kannst deinen Kund:innen aber auch erlauben den Rücksendeschein im *Mein Konto* Bereich auszufüllen, auszudrucken und der Retoure beizulegen.
Bevor Rücksendescheine erzeugt werden können, muss die Dokumentenvorlage xref:auftraege:ruecksendeschein-erzeugen.adoc#[Rücksendeschein] im Menü *Einrichtung » Mandant » [Mandant wählen] » Standorte » [Standort wählen] » Dokumente » Rücksendeschein* eingerichtet werden.

[TIP]
.Retourengründe auf der Vorlage einstellen
====
Du kannst einen unausgefüllten Rücksendeschein in jedem Paket beilegen, dass du versendest. Hierfür generierst du den Rücksendeschein direkt im Auftrag, ohne dass es überhaupt eine Retoure geben muss. Die zweite Möglichkeit ist, dass du deinen Webshop-Kund:innen erlaubst Retouren im Mein-Konto-Bereich des Shops anzumelden und hier die Retourengründe anzugeben. Anschließend kann der Rücksendeschein ausgefüllt ausdruckt werden. Egal wie du den Rücksendeschein deinen Kund:innen zukommen lässt: Damit Retourengründe eingetragen werden können, musst du die Spalte Retourengründe unterhalb der Artikelpositionen platzieren.
====

Prüfe die Artikelpositionen der Retoure und ändere bei Bedarf die Optionen, z.B. die Menge eines Artikels, bevor du im Tab *Belege* der Retoure einen Rücksendeschein erzeugst.

[.instruction]
Rücksendeschein manuell erstellen:

. Öffne die Retoure und klicke auf das Tab *Belege*.
. Wähle die Option *Rücksendeschein* aus der Dropdown-Liste *Beleg erstellen*. +
→ Ein Fenster öffnet sich.
. Nimm die Einstellungen für den Rücksendeschein vor.
. *Speichere* (icon:save[role="green"]) die Einstellungen, um den Rücksendeschein zu generieren.

[TIP]
.Rücksendeschein automatisch generieren
====
Richte eine Ereignisaktion ein, die den Rücksendeschein automatisch generiert. Wenn du hier als Ereignis *Neue Retoure (durch Kunden)* einstellst und nach der Herkunft Webshop filterst, kannst du ausgefüllte Rücksendescheine generieren und musst diese dann lediglich noch zum Download für Kund:innen bereitstellen.
====

[#460]
== Warenbestand zurückbuchen
// auf neue UI anpassen

Wenn du einen Artikel über eine Retoure zurück erhältst, kannst du den Warenbestand ganz oder teilweise zurückbuchen oder auch den gesamten Warenausgang zurücksetzen.

[.instruction]
Warenbestand zurückbuchen:

. Öffne das Menü *Aufträge » Aufträge bearbeiten*.
. Wähle in den Filtereinstellungen unter *Typ* die Option *Retoure*.
. Klicke auf *Suchen* (icon:search[role="blue"]). +
→ Die Retourenaufträge werden aufgelistet.
. Öffne die Retoure, für die der Bestand zurückgebucht werden soll.
. Öffne das Tab *Einstellungen*.
. Klicke bei der Option *Warenbestand* auf *Warenbestand einbuchen*. +
→ Ein Bearbeitungsfenster öffnet sich.
. Nimm die Einstellungen anhand <<table-reversing-stock-return>> vor.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

Die Vorgehensweise zum Zurückbuchen des Warenbestands ist auch für Retouren zu Aufträgen mit Lieferaufträgen gleich. Dass Lieferaufträge vorhanden sind, wird dir im Bearbeitungsfenster für das Rückbuchen angezeigt.

[[table-reversing-stock-return]]
.Optionen für das Rückbuchen des Warenbestands
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Warenausgang komplett zurücksetzen*
|Setzt den Warenausgang vollständig zurück. Auch das Datum des Warenausgangs wird gelöscht.

2+^| *Warenbestand zurückbuchen*

| *Komplette Menge wählen*
|Trägt die komplette Menge des Artikels im Auftrag in die Spalte *Rückbuchen* ein.

| *Komplette Menge abwählen*
|Setzt die Artikelmengen in der Spalte *Rückbuchen* auf 0.

| *Rückbuchen*
|Wenn Teilmengen zurückgebucht werden sollen, dann hier die Artikelmengen manuell eintragen.

| *Lager*
|Das Lager wählen, in das die Artikel zurückgebucht werden sollen.

| *Lagerort*
|Den Lagerort wählen, in den die Artikel zurückgebucht werden sollen.

| *Menge im Auftrag*
|Zeigt die Menge der Artikel an, die im Auftrag enthalten sind.

| *Zurückgebucht*
|Zeigt bereits zurückgebuchte Artikelmengen an.

| *Charge*
|Zeigt die Chargennumer des Artikels an.

| *MHD*
|Zeigt das Mindeshaltbarkeitsdaum des Artikels an.

| *ID*
|ID des Artikels.

| *Artikel*
|Name des Artikels.
|====

[TIP]
.Retouren-Artikel im Zulauf
====
Im Menü xref:warenwirtschaft:rueckstandsliste-verwalten.adoc#400[Waren » Retouren » Zulauf] findest du eine Übersicht aller durch Retouren im Zulauf befindlichen Artikel.
====
