= Auftragstyp Sammelauftrag

:keywords: Sammelauftrag, Sammelrechnung, Sammelgutschrift
:author: team-order-core
:description: Erfahre, wie du unbezahlte Aufträge in einen Sammalauftrag zusammenfasst und Sammelrechnungen erzeugst. Lerne außerdem, wie du eine Sammelgutschrift erstellst, um alle Gutschriften einer Kundenklasse zusammenzufassen.

Unbezahlte Aufträge können in einem Sammelauftrag zusammengefasst werden. Du kannst im Menü *Aufträge » Aufträge (Testphase)* mit dem Suchfilter *Auftragsstatus*, z.B. anhand des Status *[3] Warten auf Zahlung*, nach solchen unbezahlten Aufträgen suchen. +
Dafür übernimmst du im Menü *Aufträge » Sammelaufträge* noch nicht bezahlte Aufträge in einen Sammelauftrag. Im Bereich *Dokumente* des Sammelauftrags ist dann das Erzeugen von Sammelrechnungen möglich.

[NOTE]
======
Aufträge sollten *nicht* zu einem Sammelauftrag zusammengefasst werden, wenn sie:

* nicht die gleiche Brutto-/Netto-Ausweisung haben
* unterschiedliche Währungen haben
* unterschiedliche Steuersätze haben.
======

[#basic-settings-multi-order]
== Grundeinstellungen für Sammelaufträge vornehmen

Im Menü *Einrichtung » Aufträge » Auftragstypen » Sammelauftrag* nimmst du die Grundeinstellungen für Sammelaufträge vor. Hier legst du beispielsweise fest, für welche Auftragstypen und Auftragsstatus Sammelaufträge angelegt werden können.

[.instruction]
Grundeinstellungen für Sammelaufträge vornehmen:

. Öffne das Menü *Einrichtung » Aufträge » Auftragstypen » Sammelauftrag*.
. Nimm die Einstellungen gemäß <<table-multi-order-settings>> vor.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[[table-multi-order-settings]]
.Grundeinstellungen für Sammelaufträge
[cols="1,3"]
|===
|Einstellung |Erläuterung

| *Auftragstypen*
|Wähle die Auftragstypen, die für Sammelaufträge verwendbar sein sollen. Eine Mehrfachauswahl ist möglich. Nur die aufgeführten Auftragstypen *Auftrag*, *Gewährleistung* und *Reparatur* sind als Sammelaufträge umsetzbar.

| *Artikeltext*
|Wähle die Optionen für die Spalte *Artikeltext* der Artikelpositionen eines Sammelauftrags. Eine Mehrfachauswahl ist möglich. Die gewählten Optionen werden für jeden Einzelauftrag separat im Sammelauftrag aufgelistet und ermöglichen eine Zuordnung zur Kund:in und zum Einzelauftrag.

| *Auftragsstatus*
|Wähle, in welchem Status sich Aufträge befinden müssen, um für Sammelaufträge berücksichtigt zu werden. Eine Mehrfachauswahl ist möglich. Um gezielt nur Aufträge zu erfassen, die für Sammelaufträge vorgesehen sind, empfehlen wir, je nach Anwendungsfall einen eigenen Auftragsstatus anzulegen.

| *Standard-Status*
|Wähle einen Standard-Status, den ein Sammelauftrag beim Anlegen erhalten soll. Standardmäßig steht dafür der Status *[13] Sammelauftrag* zur Verfügung.

| *Auftragssortierung*
|Wähle, wie die einzelnen Aufträge im Sammelauftrag sortiert sein sollen. Nur eine Auswahl ist möglich. Die Aufträge sind anhand der der Auftrags-ID (*Auftrags-ID aufsteigend* oder *Auftrags-ID absteigend*) oder dem Zeitpunkt des Warenausgangs (*Warenausgang aufsteigend* oder *Warenausgang absteigend*) sortierbar.

|===

[#multi-order-per-customer-class]
== Sammelauftrag pro Kundenklasse anlegen

Fallbeispiel: Ein Unternehmen möchte für die Mitarbeiter:innen monatlich die anfallenden Rechnungen in deinem Webshop bezahlen. Richte dafür eine eigene Kundenklasse ein. Mit der Kunden-ID in der vorgesehenen Kundenklasse wird die Rechnungsempfänger:in bestimmt. Diese Rechnungsempfänger:in erhält dann die Sammelrechnung, die direkt aus dem Sammelauftrag heraus erzeugt wird. +

Einen Sammelauftrag für eine bestimmte Kundenklasse sowie einen Zeitraum legst du im Menü *Aufträge » Sammelaufträge* an. Alle unbezahlten Aufträge der Kundenklasse werden somit gesammelt in einem Sammelauftrag abgelegt. Speichere in den Einstellungen der Kundenklassen anhand der Option *Kunden-ID*, welche Kund:in für die Kundenklasse als Eigner des Sammelauftrags sowie als Empfänger:in der Sammelrechnung aufgeführt werden soll. Je nach Anforderung empfiehlt es sich, eigene xref:crm:vorbereitende-einstellungen.adoc#kundenklasse-erstellen[Kundenklassen] für Sammelaufträge anzulegen.

[.instruction]
Sammelauftrag für eine Kundenklasse anlegen:

. Öffne das Menü *Aufträge » Sammelaufträge*.
. Öffne das Untermenü *Sammelaufträge generieren*.
. Wähle die *Kundenklasse* und optional einen *Zeitraum*. Der Zeitraum bezieht sich auf das Datum des Auftragseingangs.
. Klicke auf terra:execute[]. +
→ Der Sammelauftrag wird angelegt.

[#multi-order-per-contact]
== Sammelauftrag pro Kontakt anlegen

Eine Kund:in möchte nicht jede Rechnung einzeln bezahlen, sondern pro Monat oder pro Quartal bezahlen. +
In diesem Fall legst du einen Sammelauftrag für einen bestimmten Kontakt direkt im Kontaktdatensatz im Menü *CRM » Kontakte* an. Öffne dazu einen Kontakt und wähle im Bereich *Aufträge* mit einem Klick auf material:add[] die Option *Neuer Sammelauftrag*. Anschließend wird automatisch ein Sammelauftrag generiert, der alle unbezahlten Aufträge des Kontakts enthält.

[TIP]
.Aufträge prüfen
======
Um sicher zu gehen, dass geeignete Aufträge für das Erzeugen eines Sammelauftrags vorhanden sind, verwende die Filter im Menü *Aufträge » Aufträge (Testphase)*, um nach unbezahlten Aufträgen der Kund:in zu suchen.
======

[#generate-multi-order]
== Sammelrechnung generieren

Das Erstellen von Sammelrechnungen ist nur in den dazugehörigen Sammelaufträgen möglich. Richte zuerst eine xref:auftraege:auftragsdokumente-neu.adoc#[Dokumentenvorlage] für Sammelrechnungen im Menü *Einrichtung » Mandant » [Mandant wählen] » Standorte » [Standort wählen] » Dokumente » Sammelrechnung* ein. In diesem Menü kannst du das Dokument detailliert einstellen sowie eine Dokumentenvorlage in Form einer PDF-Datei hinterlegen. In der Grundeinstellung der Vorlage sind bereits Standardwerte hinterlegt, die du bei Bedarf durch Kopie aus einer anderen Vorlage, z.B. der Dokumentenvorlage *Rechnung*, mit geringem Aufwand weiter vervollständigen kannst.

Anschließend kannst du im Bereich *Dokumente* des Sammelauftrags eine Sammelrechnung generieren. Gehe dafür wie im Folgenden beschrieben vor.

[.instruction]
Sammelrechnung erzeugen:

. Öffne das Menü *Aufträge » Aufträge (Testphase)*. +
. Führe die Suche (material:search[]) aus, um Aufträge anzuzeigen.
. Klicke rechts in der Zeile des Sammelauftrags auf das Kontextmenü (material:more_vert[]).
. Wähle *Dokument erstellen* > *Sammelrechnung*. +
icon:map-signs[] *_Oder:_* Öffne den Sammelauftrag, für den eine Sammelrechnung erzeugt werden soll.
. Gehe in den Bereich *Dokumente*.
. Klicke rechts auf *Dokument erstellen* (material:add[]).
. Wähle die Option *Sammelrechnung*. +
→ Das Fenster zum Erstellen der Sammelrechnung wird geöffnet.
. Nimm bei Bedarf Einstellungen vor. Beachte dazu die Erläuterungen in <<table-orders-generate-multi-invoice>>.
. Klicke auf *Ausführen*. +
→ Die *Sammelrechnung* wird erzeugt.

[[table-orders-generate-multi-invoice]]
.Einstellungen für Sammelrechnungen
[cols="1,3"]
|===
|Einstellung |Erläuterung

| *Datum*
|Gib das Datum an, das als Rechnungsdatum auf dem Dokument angezeigt wird. Standardmäßig ist das aktuelle Datum voreingestellt.

| *Kommentar*
|Gib optional einen Text ein, der auf der Sammelrechnung unterhalb der Artikelpositionen angezeigt wird.
|===

[IMPORTANT]
.Zahlungseingänge bei Sammelaufträgen
======
Wird eine Sammelrechnung bezahlt und der Sammelauftrag als bezahlt markiert, werden die Zahlungseingänge _nicht_ automatisch an den einzelnen im Sammelauftrag zusammengefassten Aufträgen gebucht. Zahlungseingänge musst du an den einzelnen Aufträgen manuell buchen.
======

[.discrete]
=== Sammelrechnung über Ereignisaktion generieren

Mithilfe der in plentymarkets verfügbaren Ereignisaktionen kannst du die Sammelrechnung automatisiert generieren, sobald ein Sammelauftrag angelegt wird. Gehe dazu wie nachfolgend beschrieben vor:

:table-event-procedure: <<table-event-procedure-multi-invoice-automatic>>
include::_includes:partial$event-procedure.adoc[]

[[table-event-procedure-multi-invoice-automatic]]
.Ereignisaktion "Sammelrechnung automatisch generieren"
[cols="1,3"]
|===
|Einstellung |Auswahl

| *Ereignis*

| *Auftragsanlage > Neuer Sammelauftrag*

| *Aktion*

| *Dokumente > Sammelrechnung erzeugen* +

|===

[#generate-multi-credit-note]
== Sammelgutschrift generieren

Eine Sammelgutschrift erzeugst du im Menü *Aufträge » Sammelaufträge*. +
Alle Gutschriften der ausgewählten Kundenklasse werden gesammelt in einer Sammelgutschrift abgelegt. Ebenso wie Sammelaufträge kannst du diese Sammelgutschrift nach dem Erstellen in der Auftragsübersicht bearbeiten. Je nach Anwendungsfall empfehlen wir, eigene xref:crm:vorbereitende-einstellungen.adoc#kundenklasse-erstellen[Kundenklassen] für Sammelgutschriften anzulegen.

[.instruction]
Sammelgutschrift für eine Kundenklasse generieren:

. Öffne das Menü *Aufträge » Sammelaufträge*.
. Öffne das Untermenü *Sammelgutschriften generieren*.
. Wähle die *Kundenklasse* aus.
. Wähle optional einen *Zeitraum*. Der Zeitraum bezieht sich auf das Datum des Gutschrifteingangs.
. Klicke auf terra:execute[]. +
→ Die Sammelgutschrift wird angelegt.

[#generate-document-multi-credit-note]
== Dokument Sammelgutschrift generieren

Das Erstellen des Dokuments *Sammelgutschrift* ist nur im dazugehörigen Auftragstyp Sammelgutschrift möglich. Richte zuerst eine Dokumentenvorlage für Sammelgutschriften im Menü *Einrichtung » Mandant » [Mandant wählen] » Standorte » [Standort wählen] » Dokumente » Sammelgutschrift* ein. In diesem Menü kannst du das Dokument detailliert einstellen sowie eine Dokumentenvorlage in Form einer PDF-Datei hinterlegen. In der Grundeinstellung der Vorlage sind bereits Standardwerte hinterlegt, die du bei Bedarf durch Kopie aus einer anderen Vorlage, z.B. der Dokumentenvorlage Gutschrift, mit geringem Aufwand weiter vervollständigen kannst.

Anschließend kannst du im Bereich *Dokumente* der Sammelgutschrift das Dokument *Sammelgutschrift* generieren. Gehe dafür wie im Folgenden beschrieben vor.

[.instruction]
Dokument *Sammelgutschrift* erzeugen:

. Öffne das Menü *Aufträge » Aufträge (Testphase)*. +
. Führe die Suche (material:search[]) aus, um Aufträge anzuzeigen.
. Klicke rechts in der Zeile der Sammelgutschrift auf das Kontextmenü (material:more_vert[]).
. Wähle *Dokument erstellen* > *Sammelgutschrift*. +
icon:map-signs[] *_Oder:_* Öffne die Sammelgutschrift, für die ein Dokument *Sammelgutschrift* erzeugt werden soll.
. Gehe in den Bereich *Dokumente*.
. Klicke auf *Dokument erstellen* (material:add[]).
. Wähle die Option *Sammelgutschrift*. +
→ Das Fenster zum Erstellen der Sammelgutschrift wird geöffnet.
. Nimm bei Bedarf Einstellungen vor. Beachte dazu die Erläuterungen in <<table-orders-generate-multi-credit-note>>.
. Klicke auf *Ausführen*. +
→ Das Dokument *Sammelgutschrift* wird erzeugt.

[[table-orders-generate-multi-credit-note]]
.Einstellungen für Dokument Sammelgutschrift
[cols="1,3"]
|===
|Einstellung |Erläuterung

| *Datum*
|Gib das Datum ein, das als Gutschriftsdatum auf dem Dokument angezeigt wird. Standardmäßig ist das aktuelle Datum voreingestellt.

| *Kommentar*
|Gib optional einen Text ein, der auf der Sammelgutschrift unterhalb der Artikelpositionen angezeigt wird.
|===
