= Auftragstyp Vorbestellung

:keywords: Vorbestellung
:author: team-order-core

Vorbestellungen sind im Online-Handel ein wichtiges Instrument im Marketing-Mix. Meist können Artikel noch vor der tatsächlichen Verfügbarkeit zum günstigen Einführungspreis bestellt werden. Für eine Warenwirtschaft stellt diese Situation einen Sonderfall dar, da noch nicht verfügbare Artikel natürlich auch noch keinen Lagerbestand haben können.

Vorbestellungen sind in plentymarkets sehr einfach zu erstellen. Es gibt dafür den Auftragstyp *Vorbestellung*, den du bei manuell erfassten Aufträgen verwenden kannst.

Um Vorbestellungen über den Webshop entgegennehmen zu können, sind das Erscheinungsdatum und die Artikelverfügbarkeit notwendig. Nimm dazu die auf dieser Seite beschriebenen Einstellungen am Artikel vor.

[IMPORTANT]
.Manuelle Auftragseingabe
====
Der Auftragstyp *Vorbestellung* kann nur bei manueller Auftragseingabe gewählt werden.
====

[#release-date]
== Erscheinungsdatum

Die Option *Erscheinungsdatum* findest du in der Artikelbearbeitung im Tab *Verfügbar*. Hier kannst du über einen Kalender das Datum hinterlegen, zu dem der Artikel verfügbar sein wird. Gehe dazu wie im Folgenden beschrieben vor.

[.instruction]
Erscheinungsdatum eintragen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Öffne einen Artikel, den du vorbestellbar machen musst.
. Öffne die Variante, die vorbestellbar ist.
. Im Tab *Einstellungen* der Variante scrolle in den Abschnitt *Verfügbarkeit*.
. Trage bei *Erscheinungsdatum* das Datum ein, ab dem der Artikel verfügbar sein soll.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

Im nächsten Schritt sorge dafür, dass das Erscheinungsdatum deinen Kunden angezeigt wird. Gehe dazu wie im Folgenden beschrieben vor.

[.instruction]
Erscheinungsdatum im Webshop sichtbar machen:

. Öffne das Menü *CMS » Webdesign » Ordner: Layout » Ordner: ItemView*.
. Öffne das Template *ItemViewSingleItem*.
. Füge die Template-Variable *$ReleaseDate* ein.
. *Speichere* die Einstellungen.

[#1120]
=== Artikelverfügbarkeit

Eine weitere Voraussetzung ist die korrekte Einstellung der *Artikelverfügbarkeit*. Gehe dazu wie im Folgenden beschrieben vor.

[.instruction]
Artikelverfügbarkeit für Vorbestellungen einstellen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Öffne einen Artikel, den du vorbestellbar machen möchtest.
. Wechsle in das Tab *Einstellungen*.
. Wähle für die Option *Beschränkung* die Einstellung *Keine Beschränkung*. +
→ Der Artikel kann nun ohne tatsächlichen Bestand vorbestellt, also gekauft werden.

[TIP]
.Maximale Bestellmenge
====
Damit andere Online-Händler:innen deine Vorbestellungen nicht dazu missbrauchen können, deine Bestände zum günstigen Preis komplett aufzukaufen, trage im *Tab Verfügbar* bei der Option *Maximale Bestellmenge* einen Wert ein. Trage dort den Wert *1* ein und der Artikel kann pro Bestellung nur ein einziges Mal gekauft werden. Setze die maximale Abgabemenge auf den Wert *0*, um ohne Beschränkung zu verkaufen.
====

[#1130]
=== Zahlungsaufforderung für Vorbestellungen einrichten

Die Option *Versanddatum* bleibt bei normalen Bestellungen in der Regel ungenutzt, kann jedoch für Vorbestellungen sinnvoll verwendet werden. Liegt das Erscheinungsdatum eines Artikels in der Zukunft, so wird das Erscheinungsdatum bei der Bestellung als Versanddatum hinterlegt, da ja erst mit dem Erscheinen des Artikels geliefert werden kann. Das Versanddatum kannst du in der Auftragssuche als Filteroption verwenden und über den Aktionsmanager nutzen.

Meist werden Vorbestellungen einige Zeit vor dem Erscheinen eines Artikels generiert, von den Kunden zum Zeitpunkt der Bestellung aber noch nicht bezahlt. Daher ist es sinnvoll, Kund:innen einige Tage vor dem Erscheinungs- bzw. Versanddatum über den bevorstehenden Versand zu informieren und sie zur Zahlung aufzufordern. Dies kann der *Aktionsmanager* automatisch für dich erledigen. Kund:innen werden dann wenige Tage vor dem geplanten Versand eine Erinnerungs-E-Mail mit deinen Bankdaten und dem Link zur Kaufabwicklung gesendet. Gehe wie unten beschrieben vor, um die automatische Zahlungsaufforderung für Vorbestellungen einzurichten.

[.instruction]
Zahlungsaufforderung per E-Mail einrichten:

. Erstelle eine geeignete xref:crm:e-mails-versenden.adoc#1200[E-Mail-Vorlage].
. Öffne das Menü *Einrichtung » Aufträge » Aktionen*.
. Wechsle in das Tab *Neue Aktion*.
. Trage dort im Tab *Einstellungen* einen *Namen* ein.
. Wähle bei der Option *Täglich ausführen um* eine Uhrzeit aus der Dropdown-Liste.
. Setze ein Häkchen bei *Aktiv* (icon:check-square[role="blue"]), um die Aktion zu aktivieren.
. Wechsle in das Tab *Filter*.
. Wähle für den *Status* die Einstellung *[3] Warten auf Zahlung*.
. Wähle unter *Versanddatum* z.B. die Einstellung *in 4 Tagen*.
. Wechsle in das Tab *Aktion*.
. Wähle bei der Option *Versende E-Mail-Vorlage* die zuvor erstellte E-Mail-Vorlage. Diese Vorlage wird dann mit dieser Aktion automatisch an den Kunden gesendet.
. Klicke auf *Speichern* (icon:save[role="green"]), um die Aktion zu sichern.
