= Auftragstyp Reparatur

:keywords: Reparatur, Reparaturstatus, Zustand Reparatur
:author: team-order-core
:description: Erfahre, wie du anhand des Auftragstyps Reparatur Reparaturen für retournierte oder reparaturbedürftige Ware anlegst. Lerne außerdem, wie du Status und Zustände für Reparaturen anlegst.

Reparaturen werden in plentymarkets durch einen eigenen Auftragstyp abgebildet. Reparaturen bestehen aus retournierter, reparaturbedürftiger Ware. Reparaturaufträge können daher nur aus xref:auftraege:order-type-return.adoc#[Retourenaufträgen] angelegt werden.

[#repair-standard-status]
== Standard-Status für Reparaturen festlegen

Lege zunächst Standard-Status für das Arbeiten mit Reparaturen fest. Beachte dazu die Erläuterungen in der folgenden Tabelle.

[[table-standard-status]]
.Standard-Status für Reparaturen
[cols="1,3"]
|===
|Spalte |Erläuterung

| [#intable-default-status-repairs]*Standard-Status*
|Wähle, welcher Status bei Reparatur-Aufträgen automatisch eingestellt sein soll.

| [#intable-default-status-reversal]*Standard-Status zum Zurücksetzen des Warenausgangs*
|Wähle, welcher Status für das Zurücksetzen des Warenausgangs automatisch eingestellt sein soll. +
Wenn kein besonderer Status benötigt wird, wähle die Option *Letzter Status*. Dann wird der vor dem Warenausgang durchlaufene Status wieder eingestellt.

|===

[#repair-statuses]
== Status für Reparaturen anlegen

Hinterlege vor dem Anlegen von Reparaturen verschiedene *Status* für die einzelnen Stationen des Reparaturvorgangs, um den Reparaturverlauf in deinem plentymarkets System genau nachvollziehen zu können. Die Reparaturstatus können in mehreren Sprachen hinterlegt werden.

[.instruction]
Status für Reparaturen hinterlegen:

. Öffne das Menü *Einrichtung » Aufträge » Auftragstypen » Reparatur*.
. Klicke oben links auf *Neuen Reparaturstatus erstellen* (material:add[]). +
→ Das Fenster *Neuen Reparaturstatus erstellen* wird geöffnet.
. Gib eine *Reparaturstatus-ID* ein.
. Gib einen Namen für die jeweilige Sprache ein. +
*_Tipp:_* Klicke auf *Sprache hinzufügen* (material:add[]), um weitere Sprachen hinzuzufügen und gib für alle gewählten Sprachen einen Namen ein. +
. Klicke auf *Erstellen* (material:add[role=green]), um den Reparaturstatus zu erstellen.

[#configure-columns-repair-statuses]
== Spalten für Reparaturstatus konfigurieren

In der Übersicht kannst du selbst entscheiden, welche Spalten in der Tabelle für Reparaturstatus sichtbar sein sollen und in welcher Reihenfolge diese angezeigt werden. Um die Spalten zu konfigurieren, gehe vor wie folgt.

[.instruction]
Spalten für Reparaturstatus konfigurieren:

. Öffne das Menü *Einrichtung » Aufträge » Auftragstypen » Reparatur*.
. Klicke oben rechts in der Tabelle der Reparaturstatus auf *Spalten konfigurieren* (material:settings[]). +
→ Das Fenster *Spalten konfigurieren* wird geöffnet.
. Wähle die Spalten, die angezeigt werden sollen (material:done[]). Beachte dazu die Erläuterungen in <<table-repair-statuses-columns>>.
. Ziehe (material:drag_indicator[]) die Spalten per Drag-and-drop an die gewünschte Stelle, bis sie in der für dich richtigen Reihenfolge angezeigt werden.
. Füge bei Bedarf Spalten hinzu oder wähle Spalten ab, wenn du sie nicht benötigst.
. Klicke auf *Bestätigen*. +
→ Die Einstellungen werden gespeichert.

[[table-repair-statuses-columns]]
.Spalten für Reparaturstatus
[cols="1,3"]
|===
|Spalte |Erläuterung

| *Reparaturstatus-ID*
|Zeigt die ID des Reparaturstatus an.

| *Name*
|Zeigt den Namen des Reparaturstatus an.

| *Name (Sprache)*
|Zeigt den Namen des Reparaturstatus für die in Klammern angegebene Sprache an. Wähle hier die Sprachen, die du benötigst.

| *Aktionen*
|Zeigt am Ende der Zeile die Funktionen zum Bearbeiten (material:edit[]) und Löschen (material:delete[]) des Reparaturstatus an.

|===

[#edit-repair-status]
=== Reparaturstatus bearbeiten

Um einen Reparaturstatus zu bearbeiten, gehe vor wie folgt. Beachte, dass lediglich der Name, nicht aber die ID eines Reparaturstatus geändert werden kann.

[.instruction]
Reparaturstatus bearbeiten:

. Öffne das Menü *Einrichtung » Aufträge » Auftragstypen » Reparatur*.
. Klicke rechts in der Zeile des Reparaturstatus, den du bearbeiten möchtest, auf *Reparaturstatus bearbeiten* (material:edit[]). +
→ Die Einstellungen des Reparaturstatus werden geöffnet.
. Passe den Namen für eine oder mehrere Sprachen an.
. *Speichere* (material:save[role=skyBlue]) die Änderungen.

[#delete-repair-status]
=== Reparaturstatus löschen

Um einen Reparaturstatus zu löschen, gehe vor wie folgt.

. Öffne das Menü *Einrichtung » Aufträge » Auftragstypen » Reparatur*.
. Klicke rechts in der Zeile des Reparaturstatus, den du löschen möchtest, auf *Reparaturstatus löschen* (material:delete[]). +
→ Der Reparaturstatus wird gelöscht.

[#repair-conditions]
== Zustände für Artikel anlegen

Mit einem *Zustand* kannst du den Artikel genau beschreiben, z.B. ob dieser überhaupt eine Reparatur benötigt oder auch, dass es nicht möglich ist, diesen zu reparieren. Die Zustände können in mehreren Sprachen eingetragen werden.

[.instruction]
Zustände für Artikel anlegen:

. Öffne das Menü *Einrichtung » Aufträge » Auftragstypen » Reparatur*.
. Klicke oben links auf *Neuen Artikelzustand hinzufügen* (material:add[]). +
→ Das Fenster *Neuen Artikelzustand hinzufügen* wird geöffnet.
. Gib eine *Artikelzustand-ID* ein.
. Gib einen Namen für die jeweilige Sprache ein. +
*_Tipp:_* Klicke auf *Sprache hinzufügen* (material:add[]), um weitere Sprachen hinzuzufügen und gib für alle gewählten Sprachen einen Namen ein. +
. Klicke auf *Erstellen* (material:add[role=green]), um den Artikelzustand zu erstellen.

[#configure-columns-item-conditions]
== Spalten für Artikelzustände konfigurieren

In der Übersicht kannst du selbst entscheiden, welche Spalten in der Tabelle für Artikelzustände sichtbar sein sollen und in welcher Reihenfolge diese angezeigt werden. Um die Spalten zu konfigurieren, gehe vor wie folgt.

[.instruction]
Spalten für Artikelzustände konfigurieren:

. Öffne das Menü *Einrichtung » Aufträge » Auftragstypen » Reparatur*.
. Klicke oben rechts in der Tabelle der Artikelzustände auf *Spalten konfigurieren* (material:settings[]). +
→ Das Fenster *Spalten konfigurieren* wird geöffnet.
. Wähle die Spalten, die angezeigt werden sollen (material:done[]). Beachte dazu die Erläuterungen in <<table-item-conditions-columns>>.
. Ziehe (material:drag_indicator[]) die Spalten per Drag-and-drop an die gewünschte Stelle, bis sie in der für dich richtigen Reihenfolge angezeigt werden.
. Füge bei Bedarf Spalten hinzu oder wähle Spalten ab, wenn du sie nicht benötigst.
. Klicke auf *Bestätigen*. +
→ Die Einstellungen werden gespeichert.

[[table-item-conditions-columns]]
.Spalten für Artikelzustände
[cols="1,3"]
|===
|Spalte |Erläuterung

| *Artikelzustand-ID*
|Zeigt die ID des Artikelzustands an.

| *Name*
|Zeigt den Namen des Artikelzustands an.

| *Name (Sprache)*
|Zeigt den Namen des Artikelzustands für die in Klammern angegebene Sprache an. Wähle hier die Sprachen, die du benötigst.

| *Aktionen*
|Zeigt am Ende der Zeile die Funktionen zum Bearbeiten (material:edit[]) und Löschen (material:delete[]) des Artikelzustands an.

|===

[#edit-item-condition]
=== Artikelzustand bearbeiten

Um einen Artikelzustand zu bearbeiten, gehe vor wie folgt. Beachte, dass lediglich der Name, nicht aber die ID eines Artikelzustands geändert werden kann.

[.instruction]
Artikelzustand bearbeiten:

. Öffne das Menü *Einrichtung » Aufträge » Auftragstypen » Reparatur*.
. Klicke rechts in der Zeile des Artikelzustands, den du bearbeiten möchtest, auf *Artikelzustand bearbeiten* (material:edit[]). +
→ Die Einstellungen des Artikelzustands werden geöffnet.
. Passe den Namen für eine oder mehrere Sprachen an.
. *Speichere* (material:save[role=skyBlue]) die Änderungen.

[#delete-item-condition]
=== Artikelzustand löschen

Um einen Artikelzustand zu löschen, gehe vor wie folgt.

. Öffne das Menü *Einrichtung » Aufträge » Auftragstypen » Reparatur*.
. Klicke rechts in der Zeile des Artikelzustands, den du löschen möchtest, auf *Artikelzustand löschen* (material:delete[]). +
→ Der Artikelzustand wird gelöscht.

[TIP]
.Daten aktualisieren
====
Klicke oberhalb der jeweiligen Tabelle auf *Daten aktualisieren* (material:refresh[]), um die Daten der Tabelle auf den neuesten Stand zu bringen.
====

[#create-repair]
== Reparatur anlegen

[.instruction]
Gehe wie unten beschrieben vor, um eine Reparatur anzulegen:

. Öffne das Menü *Aufträge » Aufträge (Testphase)*.
. Führe die Suche (material:search[]) aus, um Aufträge anzuzeigen.
. Öffne die Retoure, zu der du eine Reparatur anlegen möchtest.
. Klicke oben in der Toolbar auf *Aufträge erstellen* > *Reparatur*.
. Wähle die Option *Für bestimmte Auftragspositionen*. +
→ Die Übersicht zum Anlegen der Reparatur wird geöffnet.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<table-settings-repair>>.
. *Speichere* (material:save[]) die Einstellungen. +
→ Die Reparatur wird angelegt.

[[table-settings-repair]]
.Einstellungen zum Erfassen einer Reparatur
[cols="1,3"]
|===
|Einstellung |Erläuterung

| *Status*
|Wähle einen Status aus der Dropdown-Liste. Der Standard-Status, der im Menü *Einrichtung » Aufträge » Einstellungen* gespeichert wurde, ist voreingestellt.

| *Eigner*
|Wähle einen Eigner aus der Dropdown-Liste, der dem Reparaturauftrag zugewiesen wird.

| *Reparaturstatus*
|Wähle einen Reparaturstatus aus der Dropdown-Liste, der für alle Artikel der Reparatur gilt. +

2+^| *Artikelinformationen*

| *Füge alle offenen Mengen in den Warenkorb* (material:playlist_add[])
|Fügt alle offenen Mengen dem Warenkorb hinzu.

| *Artikel-ID*
|Zeigt die Artikel-ID an.

| *Varianten-ID*
|Zeigt die Varianten-ID an.

| *Variantennummer*
|Zeigt die Variantennummer an.

| *Menge*
|Zeigt die Menge des Artikels an. Passe die Menge bei Bedarf an.

| *Verbleibende Stückzahl*
|Zeigt die verbleibende Stückzahl des Artikels an.

| *Offene Menge*
|Zeigt die offene Menge des Artikels an.

| *Artikelname*
|Zeigt den Name des Artikels an.

| *Zum Warenkorb hinzufügen* (material:add_shopping_cart[])
|Fügt nur bestimmte Artikel zur Reparatur hinzu. Diese Schaltfläche ist nur verfügbar, wenn mindestens 1 Artikel vorhanden ist. +
*_Tipp:_* Passe die Artikelmenge bei Bedarf im Feld *Menge* an.

2+^| *Warenkorb*

| *Artikel aus Warenkorb entfernen* (material:delete[])
|Leert den Warenkorb komplett. Möchtest du nur bestimmte Artikel entfernen, klicke rechts neben dem jeweiligen Artikel auf *Artikel aus Warenkorb entfernen* (material:delete[]).

| *Artikel-ID*
|Zeigt die Artikel-ID an.

| *Varianten-ID*
|Zeigt die Varianten-ID an.

| *Menge*
|Zeigt die Artikelmenge an. Passe die Menge bei Bedarf an.

| *Artikelname*
|Zeigt den Artikelname an. Passe den Name bei Bedarf an.

| *Artikelstatus*
|Zeigt den Artikelstatus an. Wähle bei Bedarf einen anderen Status aus der Dropdown-Liste.

|===

[#edit-repair]
== Reparatur bearbeiten

Je nach Grund der Rücksendung oder des Zustands der zu reparierenden Artikel müssen bei der Bearbeitung verschiedene Schritte durchgeführt werden. +
Da es sich bei einer Reparatur um einen eigenen Auftragstyp handelt, kannst du im Reparaturauftrag oben in der Toolbar über *Aufträge erstellen* (material:shopping_cart[]) direkt eine xref:auftraege:order-type-credit-note.adoc#[Gutschrift], eine xref:auftraege:order-type-warranty.adoc#[Gewährleistung] oder eine xref:auftraege:order-type-return.adoc#[Retoure] anlegen.
