= Auftragstyp Vorbestellung

:keywords: Vorbestellung, Zahlungsaufforderung, Erscheinungsdatum
:author: team-order-core
:description: Erfahre, wie du Vorbestellungen mithilfe des Auftragstyps Vorbestellung erstellst. Lerne außerdem, wie du ein Erscheinungsdatum hinterlegst, die Artikelverfügbarkeit einstellst und Zahlungsaufforderungen für Vorbestellungen einrichtest.

Vorbestellungen sind im Online-Handel ein wichtiges Instrument im Marketing-Mix. Meist können Artikel noch vor der tatsächlichen Verfügbarkeit zum günstigen Einführungspreis bestellt werden. Für eine Warenwirtschaft stellt diese Situation einen Sonderfall dar, da noch nicht verfügbare Artikel natürlich auch noch keinen Lagerbestand haben können.

Vorbestellungen sind in plentymarkets sehr einfach zu erstellen. Es gibt dafür den Auftragstyp *Vorbestellung*, den du bei manuell erfassten Aufträgen verwenden kannst.

Um Vorbestellungen entgegennehmen zu können, müssen zwei Voraussetzungen erfüllt sein: das Erscheinungsdatum und die Einstellung der Bestandsbeschränkung.

[IMPORTANT]
.Manuelle Auftragseingabe
======
Der Auftragstyp *Vorbestellung* kann nur bei manueller Auftragseingabe gewählt werden.
======

[#release-date]
== Erscheinungsdatum

Im ersten Schritt gibst du an, wann der Artikel verfügbar sein wird.

[.instruction]
Erscheinungsdatum eintragen:

. Öffne das Menü *Artikel » Artikel bearbeiten » [Variante öffnen] » Tab: Einstellungen » Bereich: Verfügbarkeit*.
//ToDo - sobald die neue Artikel-UI standard ist, dann diesen Satz einblenden und dafür den alten Pfad löschen
//. Öffne das Menü *Artikel » Artikel » [Variante öffnen] » Element: Verfügbarkeit und Sichtbarkeit*.
. Trage bei *Erscheinungsdatum* das Datum ein, ab dem der Artikel verfügbar sein soll.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

---

Im zweiten Schritt sorgst du dafür, dass das Erscheinungsdatum deinen Kunden im plentyShop angezeigt wird.

[.instruction]
Erscheinungsdatum im plentyShop sichtbar machen:

. Öffne das Menü *CMS » ShopBuilder » [Artikelansicht öffnen]*.
. Füge das Widget xref:webshop:shop-builder.adoc#_text[Text » Text] zur Artikeldetailseite hinzu.
. Klicke auf das Stiftsymbol des Text-Widgets.
. Füge das Erscheinungsdatum zum Textfeld hinzu.
Klicke dazu auf *Verfügbarkeit » Erscheinungsdatum*.
. *Speichere* die Einstellungen.

[#item-availability]
== Bestandsbeschränkung

Im ersten Schritt wird ermöglicht, dass der Artikel ohne tatsächlichen Bestand gekauft, d.h. vorbestellt werden kann.

[.instruction]
Keine Bestandsbeschränkung einstellen:

. Öffne das Menü *Artikel » Artikel bearbeiten » [Variante öffnen] » Tab: Einstellungen » Bereich: Verfügbarkeit*.
. Finde die Option *Beschränkung* und wähle die Einstellung *Keine*.
//ToDo - sobald die neue Artikel-UI standard ist, dann diese 2 Sätze einblenden und dafür den alten Sätzen löschen
//. Öffne das Menü *Artikel » Artikel » [Variante öffnen] » Element: Verfügbarkeit und Sichtbarkeit*.
//. Finde die Option *Bestandsbeschränkung* und wähle die Einstellung *Keine*.
. *Speichere* die Einstellungen. +
→ Der Artikel kann nun ohne tatsächlichen Bestand gekauft, d.h. vorbestellt werden.

---

Im zweiten Schritt legst du eine maximale Bestellmenge fest.
Damit verhinderst du zum Beispiel, dass die Konkurrenz deinen gesamten Bestand zum günstigen Einführungspreis aufkaufen kann.

[.instruction]
Maximale Bestellmenge einstellen:

. Öffne das Menü *Artikel » Artikel bearbeiten » [Variante öffnen] » Tab: Einstellungen » Bereich: Verfügbarkeit*.
. Trage einen Wert in das Feld *Max. Bestellmenge* ein.
//ToDo - sobald die neue Artikel-UI standard ist, dann diese 2 Sätze einblenden und dafür den alten Sätzen löschen
//. Öffne das Menü *Artikel » Artikel » [Variante öffnen] » Element: Verfügbarkeit und Sichtbarkeit*.
//. Trage einen Wert in das Feld *Maximale Bestellmenge* ein.
* Beispiel: Wenn du den Wert 1 einträgst, dann kann pro Bestellung nur ein Exemplar gekauft werden.
* Wenn du den Wert 0 einträgst oder dieses Feld leer lässt, dann gibt es keine Begrenzung.
. *Speichere* die Einstellungen.

[#payment-request-advance-orders]
== Zahlungsaufforderung für Vorbestellungen einrichten

Die Option *Versanddatum* bleibt bei normalen Bestellungen in der Regel ungenutzt, kann jedoch für Vorbestellungen sinnvoll verwendet werden. Liegt das Erscheinungsdatum eines Artikels in der Zukunft, so wird das Erscheinungsdatum bei der Bestellung als Versanddatum hinterlegt, da ja erst mit dem Erscheinen des Artikels geliefert werden kann. Das Versanddatum kannst du in der Auftragssuche als Filteroption verwenden und über den Aktionsmanager nutzen.

Meist werden Vorbestellungen einige Zeit vor dem Erscheinen eines Artikels generiert, von den Kunden zum Zeitpunkt der Bestellung aber noch nicht bezahlt. Daher ist es sinnvoll, Kund:innen einige Tage vor dem Erscheinungs- bzw. Versanddatum über den bevorstehenden Versand zu informieren und sie zur Zahlung aufzufordern. Dies kann der *Aktionsmanager* automatisch für dich erledigen. Kund:innen werden dann wenige Tage vor dem geplanten Versand eine Erinnerungs-E-Mail mit deinen Bankdaten und dem Link zur Kaufabwicklung gesendet. Gehe wie unten beschrieben vor, um die automatische Zahlungsaufforderung für Vorbestellungen einzurichten.

[.instruction]
Zahlungsaufforderung per E-Mail einrichten:

. Erstelle eine geeignete xref:crm:e-mails-versenden.adoc#1200[E-Mail-Vorlage].
. Öffne das Menü *Einrichtung » Aufträge » Aktionen*.
. Wechsle in das Tab *Neue Aktion*.
. Trage dort im Tab *Einstellungen* einen *Namen* ein.
. Wähle bei der Option *Täglich ausführen um* eine Uhrzeit aus der Dropdown-Liste.
. Setze ein Häkchen bei *Aktiv* (icon:check-square[role="blue"]), um die Aktion zu aktivieren.
. Wechsle in das Tab *Filter*.
. Wähle für den *Status* die Einstellung *[3] Warten auf Zahlung*.
. Wähle unter *Versanddatum* z.B. die Einstellung *in 4 Tagen*.
. Wechsle in das Tab *Aktion*.
. Wähle bei der Option *Versende E-Mail-Vorlage* die zuvor erstellte E-Mail-Vorlage. Diese Vorlage wird dann mit dieser Aktion automatisch an den Kunden gesendet.
. Klicke auf *Speichern* (icon:save[role="green"]), um die Aktion zu sichern.
