= Auftragsstatus verwenden

:keywords: Auftragsstatus, Standardstatus, Status wählen, Status hinzufügen, Status bearbeiten
:author: team-order-core

Mit Auftragsstatus wird der Fortschritt bei der Abwicklung von Aufträgen abgebildet. 19 Status mit je 4 Nachkommastellen, d.h. eine Anzahl von 199999, stehen dir im System zur Verfügung. 28 Status sind bereits vorangelegt. Diese vorangelegten Status stellen einen Grundstock für übliche Abwicklungsschritte dar. Einige der 28 voreingetragenen Status sind mit Systemautomatismen verknüpft und sollten von dir auch nur für die systemseitig vorgesehenen Zwecke verwendet werden. Der Auftragsstatus eines Auftrags ändert sich durch diese Systemautomatismen, durch von dir eingerichtete Automatismen oder kann auch manuell geändert werden. Auftragsstatus dienen auch zur besseren Auftragssuche.

Spiele deine Auftragsabwicklung einmal grob durch und überlege dir, wann du Aufträgen einen neuen Status zuordnen möchtest, um den Fortschritt bei der Abwicklung kenntlich zu machen. Richte anschließend die Status ein, indem du Namen für die Status eingibst. Beachte jedoch die zweckgebundenen Status, die in <<table-default-statuses>> erwähnt sind.

[TIP]
.Berechtigungen beachten
====
Beachte, dass dir in Dropdown-Listen etc. nur die *Shops* und *Auftragsstatus* angezeigt werden, die für deine Benutzer:innen freigegeben wurden. Wenn du einen Status nicht siehst, fehlt dir wahrscheinlich die Berechtigung für den Status. Berechtigungen können durch Admin-Benutzer:innen vergeben werden.
====

[#preselected-statuses]
== Voreingestellte Status verstehen

Die folgenden 28 Statuseinträge sind bereits zu Beginn in deinem plentymarkets System vorhanden und sind teilweise mit Systemautomatismen verknüpft. Die mit Systemautomatismen verknüpften Status sind nicht löschbar.

[[table-default-statuses]]
.Standardstatus und Systemautomatismen
[cols="1,3"]
|===
|Status |Erläuterung

| *[1]* Unvollständige Daten
|Wird automatisch zugeordnet, wenn Daten eines Auftrages unvollständig sind, z.B. Adressdaten noch fehlen. Unvollständige Daten sind teilweise bei Importen von Märkten der Fall. Aufträge in diesem Status dürfen noch nicht weiter bearbeitet werden. Die Daten werden durch nachfolgende Importe noch vervollständigt. Die unvollständigen Daten dienen z.B. der frühzeitigen Bestandsreservierung.

| *[1.1]* Warten auf Zahlung &amp; Freischaltung
.3+^|Werden nicht automatisch vergeben. Ein Anwendungsfall ist der vorbefüllte Warenkorb. Ein Auftrag wird angelegt und ein Link zum Warenkorb des Auftrags wird zur Bestätigung an Kund:innen geschickt.

| *[1.2]* Freigeschaltet, warten auf Zahlung

| *[2]* Warten auf Freischaltung

| *[3]* Warten auf Zahlung
|Wird jedem unbezahlten Auftrag vom Typ Auftrag automatisch zugeordnet.

| *[3.2]* In Warteposition
|Wird automatisch in folgenden Fällen gesetzt: +
- Wenn für einen Auftrag eine Teilzahlung gebucht wird, aber kein Warenbestand vorhanden ist. +
- Wenn für einen Auftrag eine Anzahlung gebucht wird, aber kein Warenbestand vorhanden ist. +
- Wenn für einen Auftrag eine Überbezahlung gebucht wird, unabhängig davon, ob Warenbestand vorhanden ist oder nicht.

| *[3.3]* Versandfertig; warten auf Zahlung
|Wird automatisch einem Auftrag des Typs Auftrag zugeordnet, wenn für den Auftrag eine Teil- oder Anzahlung gebucht wird und Warenbestand für den Auftrag vorhanden ist.

| *[3.4]* Mahnung versendet
|Empfohlen, um zu erkennen, dass eine Mahnung versendet wurde. Mithilfe einer Ereignisaktion oder Prozessen lässt sich hier eine Automatisierung erreichen. Der Status wird jedoch nicht durch einen Systemautomatismus gesetzt.

| *[4]* In Versandvorbereitung
|Steht in Verbindung mit Bestandsbeschränkung. Wenn du keinen Bestand führst und keine Beschränkung nutzt, dann steht der Status zur freien Verfügung. +
Wenn die Bestandsbeschränkung genutzt wird, wird der Status automatisch zugeordnet, wenn ein Auftrag vom Typ Auftrag bezahlt ist, aber der Bestand der Artikel für den Auftrag nicht ausreicht. Die Beschränkung von Artikeln muss auf Nettowarenbestand eingestellt sein. +
Wenn du die Bestandsbeschränkung und diesen Status bei fehlendem Bestand nutzt, kannst du z.B. erreichen, dass nur Lieferscheine und Rechnungen für Aufträge erzeugt werden, die auch weiter abgewickelt werden können.

| *[5]* Freigabe Versand
|Wird automatisch zugeordnet, wenn ein Auftrag vom Typ Auftrag bezahlt oder die Zahlungsart z.B. Rechnung oder Vorkasse ist und der Bestand der Artikel für den Auftrag ausreicht oder der Bestand unbeschränkt ist.

| *[5.1]* Abwicklung extern
|Empfohlen, um zu kennzeichnen, dass die Ware durch einen Fulfillment-Anbieter zusammengestellt und verschickt wird. Der Status wird jedoch nicht durch einen Systemautomatismus gesetzt.

| *[6]* Gerade im Versand
|Empfohlen, um zu kennzeichnen, dass Aufträge zum Picken und Packen an das Lager übertragen wurden. Mithilfe von Ereignisaktionen oder Prozessen lässt sich hier eine Automatisierung erreichen.

| *[7]* Warenausgang gebucht
|Wird automatisch zugeordnet, wenn der Warenausgang in einem Auftrag gebucht wurde. Das manuelle Setzen des Status sorgt wiederum nicht dafür, dass der Warenausgang tatsächlich gebucht und der Bestand reduziert wird. Deshalb sollte dieser Status nicht manuell, sondern per Ereignisaktion oder Prozess gesetzt werden.

| *[7.1]* Auftrag exportiert
|Steht zur freien Verfügung. Möglicher Anwendungsfall ist das Setzen des Status, nachdem Aufträge zur Auswertung exportiert wurden.

| *[8]* Storniert
|Empfohlen, um zu kennzeichnen, dass ein Auftrag vom Typ Auftrag storniert wurde. Status 8 ist als Standard für stornierte Aufträge festgelegt. Du kannst die Standardfestlegung für stornierte Aufträge jedoch im Menü *Einrichtung » Aufträge » Einstellungen* ändern. Die Einstellung hierfür heißt xref:auftraege:grundeinstellungen.adoc#intable-default-status-cancelled-orders[Status stornierter Aufträge]. Wenn du einen anderen Status für Stornierungen festgelegt hast, kannst du Status 8 frei nutzen.

| *[8.1]* Storniert durch Kunden
|Empfohlen, um zu kennzeichnen, dass ein Auftrag durch die Kund:in storniert wurde.

| *[9]* Retoure
|Ist beim Anlegen eines Auftrags vom Typ Retoure automatisch vorausgewählt. Du kannst auch einen anderen xref:auftraege:grundeinstellungen.adoc#intable-default-status-return[Status als Standard für Retouren] festlegen. Die Einstellung erfolgt im Menü *Einrichtung » Aufträge » Einstellungen*.

| *[9.1]* Ware wird geprüft
|Empfohlen, um in einer Retoure anzuzeigen, dass die retournierte Ware geprüft wird.

| *[9.2]* Warten auf Retoure von Großhändler
|Steht zur freien Verfügung.

| *[9.3]* Gewährleistung eingeleitet
|Empfohlen, um zu kennzeichnen, dass eine Gewährleistung zur Retoure eingeleitet wurde.

| *[9.4]* Umtausch eingeleitet
|Empfohlen, um in einer Retoure anzuzeigen, dass ein Umtausch der retournierten Ware eingeleitet wurde.

| *[9.5]* Gutschrift angelegt
|Empfohlen, um in einer Retoure anzuzeigen, dass eine Gutschrift zur Retoure angelegt wurde.

| *[10]* Gewährleistung
|Steht zur freien Verfügung. Kann genutzt werden, um eine Gewährleistung als abgeschlossen zu kennzeichnen. Beim Anlegen einer Gewährleistung erhält der Gewährleistungsauftrag je nach Bestandsführung Status 4 oder 5.

| *[11]* Gutschrift
|Wird einem Auftrag vom Typ Gutschrift automatisch zugeordnet, wenn eine Gutschrift angelegt wird. Du kannst auch einen anderen xref:auftraege:grundeinstellungen.adoc#intable-default-status-credit-note[Status als Standard für Gutschriften] festlegen. Die Einstellung erfolgt im Menü *Einrichtung » Aufträge » Einstellungen*.

| *[11.1]* Gutschrift ausgezahlt
|Empfohlen, um zu kennzeichnen, dass die Gutschrift ausgezahlt wurde und abgeschlossen ist.

| *[12]* Reparatur
|Ist beim Anlegen eines Auftrags vom Typ Reparatur automatisch vorausgewählt. Du kannst auch einen anderen xref:auftraege:grundeinstellungen.adoc#intable-default-status-repairs[Status als Standard für Reparaturen] festlegen. Die Einstellung erfolgt im Menü *Einrichtung » Aufträge » Einstellungen*.

| *[13]* Sammelauftrag
|Wird einem Auftrag vom Typ Sammelauftrag automatisch zugeordnet, wenn er angelegt wird. Du kannst auch einen anderen xref:auftraege:grundeinstellungen.adoc#intable-default-status-multi-order[Status als Standard für Sammelaufträge] festlegen. Die Einstellung erfolgt im Menü *Einrichtung » Aufträge » Einstellungen*.

| *[14]* Sammelgutschrift
|Wird einem Auftrag vom Typ Sammelgutschrift automatisch zugeordnet, wenn er angelegt wird. Du kannst auch einen anderen xref:auftraege:grundeinstellungen.adoc#intable-default-status-multi-credit-note[Status als Standard für Sammelgutschriften] festlegen. Die Einstellung erfolgt im Menü *Einrichtung » Aufträge » Einstellungen*.
|===

[#add-and-edit-statuses]
== Status hinzufügen und bearbeiten

Im Menü *Einrichtung » Aufträge » Status* kannst du neben den in <<table-default-statuses>> aufgeführten Status eigene hinzufügen. Die bereits vorhandenen kannst du bearbeiten und z.B. umbenennen. Pflege Status in verschiedenen Sprachen, um deine Kund:innen per E-Mail oder im Kundenkonto des Webshops über den Fortschritt zu informieren. Bis auf Status, die mit Systemautomatismen verbunden sind, kannst du alle Status auch wieder löschen. Status, die mit Systemautomatismen verbunden sind, kannst du umbenennen. Du solltest die mit Systemautomatismen verbundenen Status jedoch nicht zweckentfremden. +
Entscheide in diesem Menü zusätzlich, wie dir die Status in deinem plentymarkets System angezeigt werden sollen. Mit dem Toggle *Status-ID im Statusnamen* anzeigen wählst du aus, ob dir nur der vergebene Name des Status oder zusätzlich auch die Status-ID angezeigt werden sollen.

[TIP]
.Name ist kein Pflichtfeld
====
Der Name ist kein Pflichtfeld. Wenn du keinen Namen pflegst, siehst du in Filtern jedoch nur eine Liste vermeintlich leerer Status und in der Auftragsübersicht ein leeres Statusfeld. Trage deshalb z.B. wenigstens die Statusnummer auch als Namen für deine hauptsächlich genutzte Sprache, Deutsch oder Englisch, ein. Übersetzungen in andere Sprachen dienen nur der Anzeige im Kundenkonto deines Shops sowie zur Kundenbenachrichtigung per E-Mail.
====

[#adding-statuses]
=== Status hinzufügen

[.instruction]
Um einen Status hinzuzufügen, gehe wie folgt vor:

. Öffne das Menü *Einrichtung » Aufträge » Status*.
. Klicke auf *Neuen Status erstellen* (icon:plus-square[role="green"]).
. Trage eine Statusnummer ein. +
→ Die höchstmögliche Nummer ist 19.9999.
. Trage optional einen Namen ein. +
→ Die Sprache, in der du eingeloggt bist, wird als Eingabefeld angezeigt.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Eingabefelder für weitere Einstellungen werden sichtbar. +
. Füge bei Bedarf weitere Sprachen für den Auftragsstatus hinzu.
. Unter *Farbe* kannst du eine individuelle Farbe für den Auftragsstatus wählen. +
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[TIP]
.Nachkommastellen
====
Achte bei der Vergabe der Statusnummern darauf, dass diese nicht auf 0 enden. Besteht die letzte Nachkommastelle aus einer 0, wird diese automatisch vom System gekürzt. In plentymarkets wird somit nicht zwischen einem Status mit der Nummer 1.1 und einem Status mit der Nummer 1.10 unterschieden.
====

[#edit-statuses]
=== Status bearbeiten

Gehe wie folgt vor, um einen bestehenden Status zu bearbeiten. Du kannst entweder einen einzelnen Status bearbeiten oder über die Gruppenfunktion mehrere auf einmal.

[.instruction]
Einzelnen Status bearbeiten:

. Öffne das Menü *Einrichtung » Aufträge » Status*.
. Klicke auf *Suchen* (icon:search[role="blue"]). +
→ Eine Liste aller vorhandenen Status wird geöffnet.
. Wähle den gewünschten Status aus der Ergebnisliste. +
→ Die Detailansicht des Status wird geöffnet.
. Ändere den Namen des Status.
. Ändere die *Farbe* des Status.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

Nutze die Gruppenfunktion im Menü *Einrichtung » Aufträge » Status*, um mehrere Status zugleich zu bearbeiten.

[.instruction]
Mehrere Status bearbeiten:

. Öffne das Menü *Einrichtung » Aufträge » Status*.
. Klicke auf *Suchen* (icon:search[role="blue"]). +
→ Eine Liste aller vorhandenen Status wird geöffnet.
. Setze in der Statusliste ein Häkchen (icon:check-square-o[role="blue"]) bei allen Status, die bearbeitet werden sollen.
. Klicke auf *Gruppenfunktion* (icon:gear[role="darkGrey", stack="gear,lr,darkGrey"]). +
→ Ein neuer Bearbeitungsbereich wird angezeigt.
. Aktiviere (icon:check-square-o[role="blue"]) im Bearbeitungsbereich die Option *Neue Farbe*, um eine neue Statusfarbe auszuwählen.
. Aktiviere (icon:check-square-o[role="blue"]) die Option *Shop-Sichtbarkeit* und wähle die gewünschte Einstellung aus dem Dropdown-Menü.
. Klicke auf das *Lieferauftrag anlegen* (terra:execute[]), um die Einstellungen auf die ausgewählten Status zu übertragen. +
→ Eine Sicherheitsfrage wird geöffnet.
. Bestätige die Sicherheitsfrage mit einem Klick auf *Status ändern*. +
→ Die Änderungen werden gespeichert.
