= Auftragstyp Gewährleistung

:keywords: Gewährleistung, Garantie, Umtausch, Gutschrift
:author: team-order-core

Gewährleistungen sind xref:auftraege:order-type-return.adoc#[Retouren] relativ ähnlich, denn in beiden Fällen bekommst du Waren eines Auftrags im *Status 7* wieder zurückgesendet. Im Gegensatz zur Retoure erwarten Kund:innen bei einer Gewährleistung aber entweder eine neue Lieferung oder eine Rückerstattung des Rechnungsbetrags mittels einer xref:auftraege:order-type-credit-note.adoc#[Gutschrift].

[TIP]
.Garantie vs. Gewährleistung
====
Im Gegensatz zur freiwillig erklärten Garantie handelt es sich bei der Gewährleistung um die *gesetzliche Pflicht* der Händler:innen, Mängel am Artikel, die bereits bei Lieferung bestanden haben, für Käufer:innen kostenlos zu beseitigen. Käufer:innen können die Gewährleistung gerichtlich bis zu 2 Jahre bei beweglichen Artikeln oder 3 Jahre bei unbeweglichen Artikeln geltend machen. Ab 6 Monaten nach Erhalt der Ware müssen Käufer:innen jedoch beweisen, dass die Mängel bereits bei Erhalt der Ware vorhanden waren.
====

Wenn ein Gewährleistungsfall vorliegt, entscheidest du als Händler:in, ob du Käufer:innen die Kosten erstattest, den Artikel reparierst oder den Artikel austauschst. Soll ein Umtausch durchgeführt werden, lege eine *Gewährleistung* an. Möchtest du das Geld erstatten, lege eine xref:auftraege:order-type-credit-note.adoc#[Gutschrift] für die Gewährleistung an. Ob du die *Versandkosten* in einer Gewährleistung übernimmst oder nicht, wählst du in den xref:auftraege:preparatory-settings.adoc#intable-shipping-costs-in-warranty[Grundeinstellungen] im Menü *Einrichtung » Aufträge » Einstellungen*.

[TIP]
.Einstellungen einer Gewährleistung
====
Wenn du aus einem Auftrag heraus eine Gewährleistung erzeugst, wird automatisch das *Versandprofil* des Auftrags übernommen. Die Einstellungen sind jedoch in der Gewährleistung änderbar. Bei *Lieferaufträgen* wird ebenfalls automatisch das korrekte Lager eingestellt. Die *Zahlungsart* bei Gewährleistungen ist änderbar.
====

[#create-warranty]
== Gewährleistung anlegen

Normalerweise legst du eine Gewährleistung in einem bestehenden Retourenauftrag an. Es ist jedoch auch möglich, diese direkt aus dem zugrunde liegenden Hauptauftrag heraus anzulegen.

Wird die Ware nach Lieferung beanstandet und du entscheidest dich beispielsweise aus Kostengründen gegen die Rücksendung der Ware, lege die Gewährleistung direkt im Hauptauftrag an.

Möchtest du dagegen erst den Eingang der Retoure abwarten und die Ware prüfen, lege zunächst einen Retourenauftrag an und erstelle im Rahmen der Abwicklung dort eine Gewährleistung.

:ordertype: Gewährleistungen

// so korrekt für neue UI?
[.instruction]
Eine Gewährleistung anlegen:

. Öffne das Menü *Aufträge » Aufträge (Testphase)*.
. Suche (material:search[]) den Haupt- oder Retourenauftrag, für den du eine Gewährleistung anlegen möchtest.
. Öffne den Auftrag.
. Klicke oben auf *Aufträge erstellen* (material:shopping_cart[]).
. Wähle eine Option. Beachte dazu die Erläuterungen in <<table-create-{ordertype}>>.
. *Speichere* (material:save[]) die Einstellungen. +
→ Die Gewährleistung wird angelegt.

include::partial$create-order-type.adoc[]

[#edit-warranty]
== Gewährleistung bearbeiten

Gewährleistungsaufträge werden in der Auftragsübersicht angezeigt. Öffne eine Gewährleistung, um beispielsweise einen zusätzlichen *Preis* einzugeben, wenn du der Käufer:in einen höherpreisigen Artikel als Ersatz liefern möchtest. Falls nötig, können hier auch die Mengen der in der Gewährleistung enthaltenen Auftragspositionen verändert werden. Um eine Gewährleistung zu bearbeiten, gehe wie im Folgenden beschrieben vor.

// so korrekt für neue UI?
[.instruction]
Gewährleistung bearbeiten:

. Öffne das Menü *Aufträge » Aufträge (Testphase)*.
. Klicke oben auf *Filter* (material:tune[]).
. Wähle für den Filter *Auftragstyp* die Option *Gewährleistung*.
. Klicke auf *Suchen* (material:search[]). +
→ Es werden alle Gewährleistungen aufgelistet.
. Klicke in die Zeile der Gewährleistung, die du bearbeiten möchtest. +
→ Die Gewährleistung wird geöffnet.
. Klicke im Tab *Auftragspositionen* auf *Bearbeiten* (material:edit[]). +
→ Die Artikelansicht wird geöffnet und du kannst die Einstellungen anpassen.
. *Speichere* (material:save[]) die Einstellungen.

[#finalise-warranty]
== Gewährleistung abschließen

Zum Abschließen einer Gewährleistung musst du, wenn für die Ersatzware ein Aufpreis berechnet wird, zunächst eine Rechnung in der Gewährleistung erzeugen. Falls du keine Ersatzware versendest, sondern dich mit der Käufer:in auf einen nachträglichen Preisnachlass auf die beanstandete Ware einigst, legst du eine Gutschrift im Hauptauftrag an.

Um die Bearbeitung einer Gewährleistung durch einen Umtausch abzuschließen, gehe wie im Folgenden beschrieben vor.

// für neue UI anpassen
[.instruction]
Gewährleistung durch Umtausch abschließen:

. Öffne in der Gewährleistung das Tab *Belege*.
. Wähle *Rechnung* aus der Dropdown-Liste *Beleg erstellen*. +
→ Ein neues Bearbeitungsfenster öffnet sich. +
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Die Rechnung wird erzeugt und in einem eigenen Tab geöffnet.
. Wechsle in das Tab *Einstellungen*.
. Klicke in der Zeile *Warenausgang* auf das Symbol *Warenausgang buchen*. +
→ Der Warenausgang wird gebucht und der *Status* wechselt automatisch zu *[7] Warenausgang gebucht*.
. Wechsle in das Menü *Aufträge » Aufträge bearbeiten*.
. Setze den Status der Gewährleistung manuell auf Status *[10] Gewährleistung*.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[TIP]
.Zahlungseingang bei Gewährleistungen buchen
====
Grundsätzlich müssen Zahlungen zu Gewährleistungen nur dann gebucht werden, wenn mit Käufer:innen ein Aufpreis vereinbart wurde. In diesem Fall buchst du den Zahlungseingang nach erfolgter Zahlung im Tab *Zahlung* der Gewährleistung.
====

Um die Bearbeitung einer Gewährleistung durch eine Gutschrift an die Käufer:in abzuschließen, gehe wie im Folgenden beschrieben vor.

// korrekt so für neue UI? oder hier "Für alle Arikel" wählen, da Gewährleistund abgeschlossen werden soll?

[.instruction]
Gewährleistung durch Gutschrift abschließen:

. Öffne das Menü *Aufträge » Aufträge (Testphase)*.
. Führe die Suche aus, um Aufträge anzuzeigen.
. Öffne den Haupt- oder Retourenauftrag zur Gewährleistung, für die du eine Gutschrift anlegen möchtest.
. Klicke oben auf *Aufträge erstellen* (material:shopping_cart[]) > *Gutschrift*.
. Wähle eine Option. Beachte dazu die Erläuterungen in <<table-create-{ordertype}>>. +
→ Wählst du *Für bestimmte Artikel*, wird die Übersicht zum Anlegen der Gutschrift geöffnet.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<table-settings-cretdit-note>>.
. *Speichere* (material:save[]) die Einstellungen. +
→ Die Gutschrift wird angelegt.

include::partial$create-order-type.adoc[]

//hier tabelle mit einstellungen hinzufügen (für bestimmte Artikel)

// prüfen: für neue UI noch korrekt?
Der weitere Bearbeitungsprozess läuft identisch mit dem regulären Anlegen einer Gutschrift und dem Erzeugen eines Gutschriftbelegs ab und wird im Kapitel xref:auftraege:auftraege-verwalten.adoc#500[Auftragstyp Gutschrift nutzen] detailliert beschrieben.
