= Vorbereitende Einstellungen vornehmen

:keywords: Auftragseinstellungen, Auftrags-Einstellungen, Auftragsgrundlagen
:author: team-order-core
:description: Erfahre, welche vorbereitenden Einstellungen für das Arbeiten mit Aufträgen erforderlich sind. Lerne außerdem, wie du anhand der Eigenschaftskopie Auftragsinformationen in einen anderen Auftrag übernimmst.

Bevor du mit der Verwaltung und Abwicklung deiner Aufträge starten kannst, solltest du verschiedene Grundeinstellungen vornehmen. Auf dieser Seite findest du alle relevanten Informationen zu diesem Thema.

Im Menü *Einrichtung » Aufträge » Einstellungen* wählst du zunächst die Einstellungen, die für Aufträge automatisch eingestellt werden bzw. bei bestimmten Auftragsstatus oder Bedingungen gelten sollen. Zum Beispiel wählst du Standard-Einstellungen für die Auftragsherkunft und den Status von Aufträgen.

[TIP]
.Umschaltfläche für neue Auftrags-UI aktivieren
======
Während sich die neue Auftrags-UI noch in der beta-Phase befindet, kannst du selbst entscheiden, ob du diese bereits für die Verwaltung von Aufträgen verwenden möchtest. Aktivierst du im Menü *Einrichtung » Aufträge » Auftragstypen » Auftrag [Beta]* oben die Umschaltfläche *Neue Auftrags-UI (beta) verwenden und mit anderen Menüs verknüpfen*, wird automatisch die neue UI verwendet und mit anderen Menüs verknüpft. Mit Klick auf den Haupteintrag *Aufträge* gelangst du dann ebenfalls in das Menü *Aufträge » Aufträge (Testphase)* und Links aus anderen Bereichen deines plentymarkets Systems führen immer dorthin. Diese Einstellung musst du manuell vornehmen, denn standardmäßig ist die alte Auftrags-UI vorausgewählt und mit den anderen Menüs verknüpft.
======

[#conditions]
== Wichtige Vorbedingungen beachten

Bei neuen Systemen sind Standardstatus eingestellt, z.B. für Retouren der Status [9] und für Gutschriften der Status [11]. Diese Einstellungen sind änderbar. Wähle dazu einen anderen Status. Alternativ legst du im Menü *Einrichtung » Aufträge » Auftragsstatus* einen neuen xref:auftraege:order-statuses.adoc#[Auftragsstatus] an. Ein dort angelegter Status wird im Menü *Grundeinstellungen* angezeigt und ist auch als Standardstatus einstellbar.

[WARNING]
.Benutzer-Login
======
Wenn du in diesem Menü Änderungen vornimmst, werden andere Benutzer:innen automatisch ausgeloggt und müssen sich neu einloggen, damit die Änderungen auch für diese Benutzerprofile greifen. Kündige Änderungen daher ggf. weiteren Benutzer:innen an.
======

[#benutzerrechte-vergeben]
== Rechte für Backend-Benutzer:innen vergeben

Damit Benutzer:innen vom Typ *Backend* Aufträge öffnen können, müssen hier Standardstatus für *Retouren* und *Gutschriften* gespeichert sein. In der Grundeinstellung ist kein Status voreingestellt. +
Backend-Benutzer:innen müssen außerdem zur Bearbeitung von Aufträgen xref:business-entscheidungen:benutzerkonten-zugaenge.adoc#105[berechtigt werden].
Zudem müssen Backend-Benutzer:innen Aufträge der Typen *Retoure*, *Gewährleistung* und *Reparatur* anlegen können. Dafür müssen sie für die im Menü *Einrichtung » Aufträge » Einstellungen* hinterlegten Standardstatus dieser drei Auftragstypen berechtigt sein. +
Lege außerdem fest, welche Benutzer:innen was im System sehen dürfen. Lege dafür die xref:business-entscheidungen:benutzerkonten-zugaenge.adoc#100[Sichtbarkeiten] fest, z.B. für Lager und Auftragsstatus. +
Im folgenden Abschnitt werden die Rechte für alle relevanten Bereiche aufgeführt. Entscheide hier selbst, welche Rechte für Backend-Benutzer:innen vergeben werden sollen.

[discrete]
=== Rechte vergeben

Beachte, dass nur *Admins* Rechte vergeben können.

[.instruction]
Rechte vergeben:

. Öffne das Menü *Einrichtung » Einstellungen » Benutzer » Rechte » Benutzer*. +
→ Die Benutzerkonten werden in einer Übersicht angezeigt.
. Klicke auf ein Benutzerkonto. +
→ Der Menüpunkt *Rechte* mit den Sichtbarkeiten wird geöffnet.
. Vergib die Rechte für den jeweiligen Bereich durch Anklicken der Checkboxen. +
*_Hinweis_*: Du kannst entweder Rechte für einen kompletten Bereich vergeben oder dem Konto nur eingeschränkt Rechte gewähren. Klappe für diese Option den Bereich auf.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[TIP]
======
Die Bereiche *Berechtigungen* und *Menü-Sichtbarkeiten* sind verknüpft. Wenn du also Rechte in einem der beiden Bereiche aktivierst, sind sie automatisch auch für den anderen Bereich aktiv.
======

[.collapseBox]
.Rechte für Kontaktdaten für Backend-Benutzer:innen vergeben
--

Personen mit *Backend*-Zugriffsrechten können xref:business-entscheidungen:benutzerkonten-zugaenge.adoc#105[nur bestimmte Bereiche und Menüs] in plentymarkets sehen. Sie können also nur eingeschränkt im System arbeiten. Sollen Mitarbeiter:innen mit dem Zugang *Backend* mit Kontaktdaten arbeiten können, benötigen sie mindestens die folgenden Rechte: +

* *CRM > Adresse > Anzeigen*
* *CRM > Adresse > Löschen*
* *CRM > Bankdaten > Aktualisieren*
* *CRM > Bankdaten > Anzeigen*
* *CRM > Bankdaten > Bearbeiten*
* *CRM > Bankdaten > Erstellen*
* *CRM > Kontakt > Anzeigen*
--

[.collapseBox]
.Rechte für Artikeldaten für Backend-Benutzer:innen vergeben
--

Personen mit *Backend*-Zugriffsrechten können xref:business-entscheidungen:benutzerkonten-zugaenge.adoc#105[nur bestimmte Bereiche und Menüs] in plentymarkets sehen. Sie können also nur eingeschränkt im System arbeiten. Sollen Mitarbeiter:innen mit dem Zugang *Backend* Artikeldaten sehen können, benötigen sie mindestens die folgenden Rechte: +

* *Artikel > Artikel > Anzeigen*
* *Artikel > Artikel > Artikelbild > Anzeigen*
* *Artikel > Artikel > Artikelbild > Artikelbildname > Anzeigen*
* *Artikel > Artikel > Variante > Anzeigen*
* *Artikel > Hersteller > Anzeigen*
* *Artikel > Verkaufspreis > Anzeigen*
--

[.collapseBox]
.Rechte für Märkte für Backend-Benutzer:innen vergeben
--

Personen mit *Backend*-Zugriffsrechten können xref:business-entscheidungen:benutzerkonten-zugaenge.adoc#105[nur bestimmte Bereiche und Menüs] in plentymarkets sehen. Sie können also nur eingeschränkt im System arbeiten. Sollen Mitarbeiter:innen mit dem Zugang *Backend* Zugangsdaten zu Märkten sehen können, benötigen sie mindestens das folgende Recht: +

* *Märkte > Zugangsdaten > Anzeigen*
--

[.collapseBox]
.Rechte für Aufträge und Auftragsdokumente für Backend-Benutzer:innen vergeben
--

Personen mit *Backend*-Zugriffsrechten können xref:business-entscheidungen:benutzerkonten-zugaenge.adoc#105[nur bestimmte Bereiche und Menüs] in plentymarkets sehen. Sie können also nur eingeschränkt im System arbeiten. Sollen Mitarbeiter:innen mit dem Zugang *Backend* mit Aufträgen und Auftragsdokumenten arbeiten können, benötigen sie mindestens die folgenden Rechte: +

* *Aufträge > Anzeigen*
* *Aufträge > Aktualisieren*
* *Aufträge > Erstellen*
* *Aufträge > Löschen*
* *Aufträge > Auftragseigenschaften > Anzeigen*
* *Aufträge > Dokumente > Anlegen*
* *Aufträge > Dokumente > Anzeigen*
* *Aufträge > Dokumente > Löschen*
--

[.collapseBox]
.Rechte für den Warenausgang für Backend-Benutzer:innen vergeben
--

Personen mit *Backend*-Zugriffsrechten können xref:business-entscheidungen:benutzerkonten-zugaenge.adoc#105[nur bestimmte Bereiche und Menüs] in plentymarkets sehen. Sie können also nur eingeschränkt im System arbeiten. Sollen Mitarbeiter:innen mit dem Zugang *Backend* Aktionen für den Warenausgang durchführen können, benötigen sie mindestens die folgenden Rechte: +

* *Aufträge > Warenausgang buchen*
* *Aufträge > Warenausgang der Auftragsposition zurücksetzen*
* *Aufträge > Warenausgang zurücksetzen*
--

[.collapseBox]
.Rechte für Eigenschaften und Tags für Backend-Benutzer:innen vergeben
--
Personen mit *Backend*-Zugriffsrechten können xref:business-entscheidungen:benutzerkonten-zugaenge.adoc#105[nur bestimmte Bereiche und Menüs] in plentymarkets sehen. Sie können also nur eingeschränkt im System arbeiten. Sollen Mitarbeiter:innen mit dem Zugang *Backend* mit Eigenschaften und Tags arbeiten können, benötigen sie mindestens die folgenden Rechte: +

* *Einrichtung > Eigenschaft > Anzeigen*
* *Einrichtung > Tag > Anzeigen*
* *Einrichtung > Tag > Tag-Verknüpfung > Erstellen*
* *Einrichtung > Tag > Tag-Verknüpfung > Löschen*
--

[.collapseBox]
.Rechte für Benutzerdaten für Backend-Benutzer:innen vergeben
--

Personen mit *Backend*-Zugriffsrechten können xref:business-entscheidungen:benutzerkonten-zugaenge.adoc#105[nur bestimmte Bereiche und Menüs] in plentymarkets sehen. Sie können also nur eingeschränkt im System arbeiten. Sollen Mitarbeiter:innen mit dem Zugang *Backend* Benutzerdaten konfigurieren können, benötigen sie mindestens das folgende Recht: +

* *Benutzer > Konfigurieren*
--

Falls dir in der Auftrags-UI einige Funktionen oder Einstellungen nicht angezeigt werden, kannst du in der folgenden Tabelle prüfen, welche Rechte dir fehlen.

[.collapseBox]
.Rechte für Funktionen in Order-UI
--
[[table-required-user-rights]]
.Benötigte Benutzerrechte
[cols="1,3"]
|===
|Aktion |Benötigte Rechte

2+^| *Auftragsdetails*

| *Auftragspositionen bearbeiten*
|Aufträge > Aktualisieren +
Aufträge > Erstellen +
Einrichtung > Eigenschaft > Anzeigen +
Artikel > Verkaufspreis > Anzeigen +
Artikel > Artikel > Variante > Anzeigen

| *Adresse bearbeiten*
|Aufträge > Aktualisieren +
CRM > Adresse > Typ der Adressoption > Anzeigen

| *Adresse ändern*
|Aufträge > Aktualisieren +
CRM > Adresse > Anzeigen

| *Bankdaten hinzufügen/aktualisieren*
|Aufträge > Aktualisieren +
CRM > Bankdaten > Erstellen +
CRM > Bankdaten > Aktualisieren

| *Dokumente hinzufügen*
|Aufträge > Aktualisieren +
Aufträge > Dokumente > Anlegen

| *Dokumente löschen/archivieren*
|Aufträge > Aktualisieren +
Aufträge > Dokumente > Löschen

2+^| *Toolbar*

| *Aufträge erstellen/teilen/duplizieren*
|Aufträge > Aktualisieren +
Aufträge > Erstellen

| *Lagerorte zuweisen*
|Aufträge > Aktualisieren

| *Gutscheine einlösen*
|Aufträge > Aktualisieren

| *Warenausgang buchen*
|Aufträge > Aktualisieren +
Aufträge > Warenausgang buchen

| *Waren zurückbuchen*
|Aufträge > Aktualisieren +
Aufträge > Warenausgang zurücksetzen +
Aufträge > Warenausgang der Auftragsposition zurücksetzen

| *Aufträge löschen*
|Aufträge > Löschen

2+^| *Auftragsübersicht (Gruppenfunktionen)*

| *Aufträge gruppieren*
|Aufträge > Erstellen +
Aufträge > Aktualisieren +
Aufträge > Gruppenfunktion (neue Auftrags-UI) > Aufträge gruppieren

| *Status ändern*
|Aufträge > Aktualisieren +
Aufträge > Gruppenfunktion (neue Auftrags-UI) > Status

| *Tag ändern*
|Aufträge > Aktualisieren +
Aufträge > Gruppenfunktion (neue Auftrags-UI) > Tags

| *Versanddatum von Auftragspositionen setzen*
|Aufträge > Aktualisieren +
Aufträge > Gruppenfunktion (neue Auftrags-UI) > Versanddatum

| *Lieferdatum von Aufträgen setzen*
|Aufträge > Aktualisieren +
Aufträge > Gruppenfunktion (neue Auftrags-UI) > Lieferdatum

| *Versandprofil ändern*
|Aufträge > Aktualisieren +
Aufträge > Gruppenfunktion (neue Auftrags-UI) > Versandprofil

| *Eigner ändern*
|Aufträge > Aktualisieren +
Aufträge > Gruppenfunktion (neue Auftrags-UI) > Eigner

| *Aufträge löschen*
|Aufträge > Löschen +
Aufträge > Gruppenfunktion (neue Auftrags-UI) > Löschen

| *Warenausgang buchen*
|Aufträge > Aktualisieren +
Aufträge > Gruppenfunktion (neue Auftrags-UI) > Warenausgang buchen +
Aufträge > Warenausgang buchen

| *Warenausgang zurücksetzen*
|Aufträge > Aktualisieren +
Aufträge > Gruppenfunktion (neue Auftrags-UI) > Warenausgang zurücksetzen +
Aufträge > Warenausgang zurücksetzen

| *Dokumente erstellen*
|Aufträge > Dokumente > Anlegen +
Aufträge > Gruppenfunktion (neue Auftrags-UI) > Dokumente > Auftragsbestätigung +
Aufträge > Gruppenfunktion (neue Auftrags-UI) > Dokumente > Gelangensbestätigung +
Aufträge > Gruppenfunktion (neue Auftrags-UI) > Dokumente > Gutschrift +
Aufträge > Gruppenfunktion (neue Auftrags-UI) > Dokumente > Lieferschein +
Aufträge > Gruppenfunktion (neue Auftrags-UI) > Dokumente > Rechnung +
Aufträge > Gruppenfunktion (neue Auftrags-UI) > Dokumente > Rücksendeschein +
Aufträge > Gruppenfunktion (neue Auftrags-UI) > Dokumente > Stornobeleg Gutschrift +
Aufträge > Gruppenfunktion (neue Auftrags-UI) > Dokumente > Stornobeleg Rechnung

2+^| *Kontextmenü*

| *Dokumente erstellen*
|Aufträge > Dokumente > Anlegen

| *Warenausgang buchen*
|Aufträge > Aktualisieren +
Aufträge > Warenausgang buchen

| *Warenausgang zurücksetzen*
|Aufträge > Aktualisieren +
Aufträge > Warenausgang zurücksetzen

| *Aufträge löschen*
|Aufträge > Löschen

| *Status ändern*
|Aufträge > Aktualisieren +
*_Hinweis:_* Kannst du bestimmte Status in der Auftragsübersicht oder in den Auftragsdetails nicht sehen, benötigst du die jeweiligen Rechte für die *Setzbaren Auftragsstatus*. Bitte einen Admin darum, dir die notwendigen Rechte im Menü *Einrichtung » Einstellungen » Benutzer » Konten » [Konto wählen] » Tab: Berechtigungen* zuzuweisen.

|===
--

[#basic-settings]
== Grundeinstellungen vornehmen

Gehe wie unten beschrieben vor, um die Grundeinstellungen für die Auftragsbearbeitung vorzunehmen.

[.instruction]
Grundeinstellungen vornehmen:

. Öffne das Menü *Einrichtung » Aufträge » Einstellungen*.
. Nimm die Einstellungen gemäß <<table-orders-basic-settings>> vor.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[[table-orders-basic-settings]]
.Optionen im Menü *Einrichtung » Aufträge » Einstellungen*
[cols="1,3"]
|===
|Einstellung |Erläuterung

2+^| *Einstellungen*

| [#intable-warehouse-assignment]*Lagerzuordnung*
|Wähle die Lagerzuordnung. +
*a) pro Auftrag kann ein Lager zugeordnet werden* (Standardeinstellung) = Wähle diese Option, wenn nur mit einem Lager bzw. Logistiker gearbeitet wird. +
*b) pro Artikelposition kann ein Lager zugeordnet werden* = Wähle diese Option, wenn mit mehreren Lagern bzw. Logistikern gearbeitet wird.

| [#intable-warehouse-selection]*Automatische Lagerauswahl*
|Wähle die Kriterien, nach denen das Lager gewählt werden soll. +
*a) in Abhängigkeit des Lieferlandes* (Standardeinstellung) = Das Lager für das *Lieferland* ist im Menü *Einrichtung » Aufträge » Versand » Optionen » Tab: Lieferländer* hinterlegt. +
*_Tipp:_* Prüfe bei der Wahl dieser Option die Lagerzuordnung zu den Lieferländern. +
*b) in Abhängigkeit des Hauptlagers des Artikels* = Es wird das Lager bestimmt, das beim jeweiligen Artikel als Hauptlager hinterlegt ist. +
*_Hinweis:_* Wenn für einen Artikel kein Hauptlager hinterlegt wurde, wird das Lager anhand des Lieferlandes gewählt. +
*c) in Abhängigkeit des höchsten Warenbestandes* = Der Auftrag wird dem Lager mit dem höchsten Warenbestand der Artikelposition zugeordnet. +
*d) in Abhängigkeit der Lagerpriorität und des höchsten Warenbestandes* = Der Auftrag wird einem Lager nach folgenden Kriterien zugeordnet. Dabei wird nach folgender Reihenfolge geprüft: +
1) Nach der *Priorität* des Lagers (Option in den xref:warenwirtschaft:lager-einrichten.adoc#300[Lagereinstellungen]). +
Bei ausreichendem bzw. gleichem Warenbestand in allen Lagern wird das Lager nach Priorität gewählt. Es kommt bei Kriterium 1 nicht auf die Menge an, sondern nur darauf, dass genügend Bestand vorhanden ist. Das heißt, dass kein Lager aufgrund der Menge bevorzugt wird, sondern dann mit Kriterium 2 anhand der Priorität. Umgekehrt ist mangelnder Bestand ein Ausschlusskriterium. +
2) Es muss ausreichend Warenbestand vorhanden sein. +
*e) in Abhägigkeit des niedrigsten Warenbestandes* = Der Auftrag wird dem Lager mit dem niedrigsten Warenbestand der Artikelposition zugeordnet. +
*f) in Abhängigkeit der Lagerpriorität und des niedrigsten Warenbestandes* = Der Auftrag wird einem Lager nach folgenden Kriterien zugeordnet. Dabei wird nach folgender Reihenfolge geprüft: +
1) Nach der *Prioriät* des Lagers (Option in den Lagereinstellungen). +
Bei ausreichendem bzw. gleichem Warenbestand in allen Lagern wird das Lager nach Priorität gewählt. Es kommt bei Kriterium 1 nicht auf die Menge an, sondern nur darauf, dass genügend Bestand vorhanden ist. Das heißt, dass kein Lager aufgrund der Menge bevorzugt wird, sondern dann mit Kriterium 2 anhand der Priorität. Umgekehrt ist mangelnder Bestand ein Ausschlusskriterium. +
2) Das Lager mit dem niedrigsten Warenbestand wird gewählt. +
*g) in Abhängigkeit der Lagerpriorität und des höchsten Warenbestands (sonst Hauptlager)* = Für die Lagerzuordnung werden zunächst die Einstellungen für die Priorität des Lagers geprüft. Das zweite Kriterium ist der Warenbestand, es wird also nach dem höchsten Warenbestand zugeordnet. Erfüllt kein Lager diese Kriterien, d.h. ist kein ausreichender Warenbestand vorhanden, wird dem Auftrag das Hauptlager der Variante zugeordnet. +
*h) in Abhängigkeit der Lagerpriorität und des niedrigsten Warenbestandes (sonst Hauptlager)* = Für die Lagerzuordnung werden zunächst die Einstellungen für die Priorität des Lagers geprüft. Das zweite ist der Warenbestand, es wird also nach dem niedrigsten Warenbestand zugeordnet. Erfüllt kein Lager diese Kriterien, d.h. ist keine Lagerpriorität vergeben und kein Warenbestand vorhanden, wird dem Auftrag das Hauptlager der Variante zugeordnet. +
*_Hinweis:_* Wenn kein gültiges Lager mit diesen Einstellungen ermittelt werden kann, wird versucht, das Lager mit der höchsten Priorität zu ermitteln, das für die Herkunft des Auftrags freigegeben ist. Ist kein Lager für die Herkunft des Auftrags freigegeben, wird das Lager mit der höchsten Priorität ermittelt.

| [#intable-default-status-cancelled-orders-from]*Status stornierter Aufträge von*
|Wähle den Statusbereich, ab dem Aufträge storniert werden sollen. +
Sobald ein Auftrag in diesem Statusbereich ankommt, werden alle Bestandsreservierungen der darin enthaltenen Artikel aufgehoben. Das heißt, der Warenbestand steht wieder für Bestellungen zur Verfügung. Status können von dieser Automatik ausgenommen werden, wenn dies nötig ist bzw. wenn Artikel mit dem Status nicht zurückgebucht werden sollen.

| [#intable-default-status-cancelled-orders-to]*Status stornierter Aufträge bis*
|Wähle den Statusbereich, bis zu dem Aufträge storniert werden sollen.

|[#intable-prefix-bundles]*Präfix für Artikelpakete*
|Lege fest, welches Präfix in der Benennung für Artikelpakete (Bundles) verwendet werden soll. Beachte, dass ein Leerzeichen hinter dem Präfix eingefügt werden sollte. Standardmäßig ist das Präfix [BUNDLE] eingetragen. +
Zur Nutzung dieser Einstellung benötigst du plentyShop LTS/IO in Version 5.0.40 oder höher.

|[#intable-prefix-bundle-components]*Präfix für Artikelpaketbestandteile*
|Lege fest, welches Präfix in der Benennung für Bestandteile von Artikelpaketen (Bundles) verwendet werden soll. Beachte, dass ein Leerzeichen hinter dem Präfix eingefügt werden sollte. Standardmäßig ist das Präfix [-] eingetragen. +
Zur Nutzung dieser Einstellung benötigst du plentyShop LTS/IO in Version 5.0.40 oder höher.

| [#intable-default-referrer]*Standard-Auftragsherkunft*
|Wähle eine:n Anbieter:in bzw. Marktplatz oder die Einstellung *Webshop* als Herkunft, die bei Aufträgen automatisch voreingestellt werden soll. Wähle die Option *Manuelle Eingabe*, wenn keine Voreinstellung gewünscht ist, also die Auftragsherkunft individuell hinterlegt werden soll.

| [#intable-default-variation-id-dunning-fees]*Standard-Varianten-ID für Mahngebühren*
|Gib eine Standard-Varianten-ID für Mahngebühren ein. Diese ID ist dann für Mahnungen automatisch vorausgewählt.

| [#intable-deposit-production-item]*Anzahlung auf Produktionsware*
|Wähle die Höhe einer Anzahlung (in Prozent) oder die Option *keine Anzahlung anbieten*.

| [#intable-display-inactive-payment-plugins]*Inaktive Zahlungsarten anzeigen*
| *aktiv* = Es werden in Dropdown-Listen auch inaktive Plugin-Zahlungsarten zur Auswahl angezeigt. +
*inaktiv* (Standardeinstellung) = Es werden in Dropdown-Listen nur aktive Plugin-Zahlungsarten zur Auswahl angezeigt.

2+^| *Warenbestand*

| [#intable-default-status-order-reservation-from]*Status Auftragsreservierung von*
|Sobald ein Auftrag in dem hier gewählten Statusbereich ankommt, wird automatisch für die im Auftrag enthaltenen Artikel Bestand reserviert. Zusätzlich kannst du wählen, ob die Einstellung für alle Aufträge oder nur für bezahlte Aufträge gelten soll. Wenn z.B. für nicht bezahlte Aufträge kein Bestand reserviert werden soll, wähle weiter unten in den Einstellungen die Option *Nur bezahlte Aufträge*.

| [#intable-default-status-order-reservation-to]*Status Auftragsreservierung bis*
|Wähle den Statusbereich, bis zu dem für die im Auftrag enthaltenen Artikel automatisch Bestand reserviert werden soll. Zusätzlich kannst du wählen, ob die Einstellung für alle Aufträge oder nur für bezahlte Aufträge gelten soll. Wenn z.B. für nicht bezahlte Aufträge kein Bestand reserviert werden soll, wähle weiter unten in den Einstellungen die Option *Nur bezahlte Aufträge*.

| [#intable-affected-status-range]*Betroffener Statusbereich im Status [4.x] von*
|Grenze den Statusbereich ein, wenn eigene Statusvarianten im Bereich von Status [4] angelegt wurden. +
Die Standardeinstellung ist *[4] In Versandvorbereitung*.

| [#intable-affected-status-range]*Betroffener Statusbereich im Status [4.x] bis*
|Grenze den Statusbereich ein, wenn eigene Statusvarianten im Bereich von Status [4] angelegt wurden. +
Die Standardeinstellung ist *[4] In Versandvorbereitung*.

| [#intable-order-reservation-paid-orders]*Auftragsreservierung nur für bezahlte Aufträge*
|Aktiviere diese Option, wenn Bestandsreservierungen nur für bezahlte Aufträge vorgenommen werden sollen.

| [#intable-status-change-missing-stock]*Statuswechsel auf [4] statt [5], wenn Warenbestand fehlt*
|Aktiviere diese Option, wenn ein Auftrag erst für den Versand freigegeben werden soll, wenn genügend Ware auf Lager ist. Sobald genügend Ware eingebucht wurde, wird der xref:auftraege:order-statuses.adoc#[Auftragsstatus] von *[4]* auf *[5]* geändert. Standardmäßig ist diese Einstellung aktiv. +
*Status [4]* = In Versandvorbereitung +
*Status [5]* = Freigabe Versand

2+^| *Auftrags-UI*

| [#intable-show-address]*In Auftrag/Auftragsübersicht anzeigen*
|Wähle, ob im Auftrag und in der Auftragsübersicht die *Rechnungsadresse* (Standardeinstellung) oder die *Lieferadresse* angezeigt werden soll.

| [#intable-item-price]*Artikelpreis-Darstellung*
|Wähle, ob die Preise der Artikelliste im Auftrag *Brutto* oder *Netto* dargestellt werden sollen.

| [#use-new-order-ui]*Neue Auftrags-UI (beta) verwenden und mit anderen Menüs verknüpfen*
| *aktiv* = Die neue Auftrags-UI im Menü *Aufträge » Aufträge (Testphase)*
wird für deine Arbeit im System verwendet und mit anderen Menüs verknüpft. Mit Klick auf den Haupteintrag *Aufträge* gelangst du dann ebenfalls in das Menü *Aufträge » Aufträge (Testphase)* und Links aus anderen Bereichen deines plentymarkets Systems führen immer dorthin. +
*inaktiv* = Die alte Auftrags-UI im Menü *Aufträge » Aufträge bearbeiten* wird für deine Arbeit im System verwendet (Standardeinstellung). Beachte jedoch, dass diese bald abgeschaltet wird.

| [#intable-quantity-bundles]*Mengenänderung von Bundle-Artikeln und Bundle-Bestandteilen erlauben*
| *inaktiv* (Standardeinstellung) = Die Mengen von Bundle-Artikeln und Bundle-Bestandteilen können nicht nachträglich manuell in einem Auftrag geändert werden. Um die Menge anzupassen, muss das Bundle in der gewünschten Menge neu zum Auftrag hinzugefügt werden. +
*aktiv* = Die Mengen von Bundle-Artikeln und Bundle-Bestandteilen können nachträglich manuell in einem Auftrag geändert werden. +
*_Hinweis:_* Werden Mengen nachträglich manuell in einem Auftrag geändert, führt dies nicht automatisch zu einer Anpassung der Mengen der Bestandteile eines Bundles und auch nicht zu einer Preisanpassung.

|===

[#transfer-property]
== Eigenschaftskopie

Bei der Eigenschaftskopie legst du fest, welche Auftragsinformationen (Eigenschaften eines Auftrags) in einen anderen Auftrag übernommen werden sollen. Zum Beispiel werden Eigenschaften beim Erstellen von Lieferaufträgen oder Retouren vom Hauptauftrag kopiert. Dies sind Informationen, die an einem Auftrag hängen, wie z.B. das Versandprofil, der Zahlungsstatus oder die Dokumentensprache. Eigenschaften können am Auftrag oder an einer Auftragsposition hängen. +
*_Beachte:_* Dies bezieht sich auf xref:artikel:eigenschaften.adoc#500[Eigenschaften], die du nicht selbst erstellt hast, wie z.B. xref:artikel:personalisierte-artikel.adoc#95[Bestellmerkmale].

[IMPORTANT]
.Standard für kopierte Eigenschaften
======
Standardmäßig werden alle benötigten Eigenschaften vom einen in den jeweils anderen Auftragstyp übernommen. Ändere nur nach sorgfältiger Überlegung etwas an den kopierten Eigenschaften.
======

Bestimme im Menü *Einrichtung » Aufträge » Eigenschaftskopie*, welche Eigenschaften kopiert werden sollen. Du kannst dies individuell für verschiedene Kombinationen, z.B. von Auftrag (Quelle) zu Lieferauftrag (Ziel), festlegen. Beachte, dass nicht alle Eigenschaften zum Kopieren freigeschaltet sind. Die Tabellenspalte *Quelle* gibt wieder, woher die Eigenschaft kommt. *Intern* bedeutet, dass die Eigenschaft vom System kommt. *Interface* bedeutet, dass die Eigenschaft über eine Schnittstelle wie ein Plugin oder per REST erstellt wurde. +
Beim Öffnen des Menüs sind bereits einige Filter vorausgewählt. Passe diese bei Bedarf an wie folgt.

[.instruction]
Eigenschaften zum Kopieren aktivieren:

. Öffne das Menü *Einrichtung » Aufträge » Eigenschaftskopie*.
. Öffne die Suchfilter (material:filter_alt[]).
. Wähle für den Filter *Auftragstyp Quelle* den Auftragstyp, von dem die Eigenschaften kopiert werden sollen.
. Wähle für den Filter *Auftragstyp Ziel* den Auftragstyp, in den die Eigenschaften kopiert werden sollen.
. Führe die Suche aus. +
→ Die Eigenschaften werden in der Tabelle angezeigt.
. Aktiviere oder deaktiviere in der Tabellenspalte *Auftragseigenschaft kopieren* die Eigenschaften, die kopiert werden sollen.
. Aktiviere oder deaktiviere in der Tabellenspalte *Auftragspositionseigenschaft kopieren* die Eigenschaften, die kopiert werden sollen. +
→ Die aktivierten Eigenschaften werden fortan kopiert.

Darüber hinaus stehen dir in der Suche (material:filter_alt[]) noch folgende Filter zur Verfügung:

* *Nur kopierbare Eigenschaften anzeigen* = Wähle *Ja*, wenn dir in der Tabelle nur die Eigenschaften angezeigt werden sollen, die von einem Auftragstyp zum anderen übertragen werden können. Wähle *Nein*, wenn dir in der Tabelle alle Eigenschaften, auch die nicht kopierbaren, angezeigt werden sollen.
* *Eigenschafts-ID* = Gib eine konkrete Eigenschafts-ID ein, nach der du suchen möchtest. Es kann nur eine ID eingegeben werden.
* *Quelle* = Wählst du nichts aus, werden die Eigenschaften aller Quellen angezeigt. Wählst du *Intern* oder *Interface*, werden dir jeweils nur die Eigenschaften dieser Quellen angezeigt.
