= Proformarechnungen
:page-aliases: dokument-proformarechnung-erzeugen.adoc
:keywords: Proformarechnung, Proformarechnung erzeugen, Proforma-rechnung, Pro-formarechnung, Auftragsdokumente, Dokumentenvorlage, Dokumententyp, Dokument, Dokumentvorlage, Dokumenttyp
:author: team-docs-automation
:description: Erfahre, wie du anhand einer Dokumentenvorlage Proformarechnungen erstellst und diese als PDF-Datei generierst, um sie als Vorabrechnung oder als Grundlage für steuerliche Zwecke zu nutzen.

In plentymarkets kannst du Proformarechnungen als PDF-Dateien generieren, um diese z.B. zu drucken oder als E-Mail-Anhang zu verschicken. Proformarechnungen werden in der Regel als Vorabrechnungen oder als Grundlage für steuerliche Zwecke, zum Beispiel für den Zoll bei Einfuhr- und Ausfuhrlieferungen, genutzt.

[#100]
== Dokumentenvorlage für Proformarechnungen einrichten

Bevor du Proformarechnungen generieren kannst, muss eine Dokumentenvorlage eingerichtet werden. Dies geschieht im Menü *Einrichtung » Mandant » [Mandant wählen] » Standorte » [Standort wählen] » Dokumente » Proformarechnung*. +
Weitere Informationen und Anleitungen zur Einrichtung der Dokumentenvorlage findest du auf der Handbuchseite xref:auftraege:auftragsdokumente-neu.adoc#[Auftragsdokumente].

[TIP]
.Angaben zu Zahlungsziel und Skonto auf der Proformarechnung
====
Damit Angaben zu Zahlungsbedingungen (Valuta, Zahlungsziel, Skonto) auf Proformarechnungen angezeigt werden, müssen diese beim xref:auftraege:auftragsdokumente-neu.adoc#intable-zahlungsbedingungen-dokumente[Einrichten der Dokumentenvorlage] für Proformarechnungen aktiviert werden.
====

[#200]
== Einzelne Proformarechnungen erzeugen

Proformarechnungen kannst du manuell an verschiedenen Auftragstypen erzeugen. Zur Verfügung steht dir die Proformarechnung bei Aufträgen, Angeboten, Vorbestellungen, Reparaturen, Gewährleistungen und bei Lieferaufträgen. Gehe dabei wir im Folgenden beschrieben vor.

[.instruction]
Proformarechnung manuell erzeugen:

. Öffne das Menü *Aufträge » Aufträge*. +
→ Die Auftragsübersicht wird geöffnet.
. Führe die Suche (material:search[]) aus, um Aufträge anzuzeigen.
. Öffne den Auftrag, für den eine Proformarechnung erzeugt werden soll. Beachte, dass Aufträge nur in der Listenansicht geöffnet werden können.
. Gehe in den Bereich *Dokumente*.
. Klicke oben links auf *Dokument erstellen* (material:add[]).
. Wähle das Dokument *Proformarechnung* aus der Dropdown-Liste. +
→ Das Fenster *Dokument erzeugen: Proformarechnung* wird geöffnet.
. Gib ein Datum ein, das auf der Proformarechnung angezeigt werden soll.
. Gib optional einen Kommentar ein, der auf der Proformarechnung angezeigt werden soll.
. Klicke auf *Erstellen* (material:add[role="green"]). +
→ Die Proformarechnung wird erstellt und im Bereich *Dokumente* hinzugefügt.
