= Rechnungen
:keywords: Rechnung, Rechnungen erzeugen, Dokument, Auftragsdokument, Dokumentenvorlage, Dokumenttyp, Dokumententyp, Rechnungsdaten, Storno, Stornobeleg, Rechnungsdatum, Steuerdokument, Dokumentvorlage, Rechnungsstorno, Zahlungsbedingungen
:author: team-docs-automation

In plentymarkets generierst du Rechnungen entweder einzeln oder gesammelt als PDF-Dateien, um diese z.B. zu drucken oder deinen Kund:innen
 als E-Mail Anhang zukommen zu lassen. +
Je nach Lieferland und Standort unterliegen Rechnungen verschiedenen gesetzlichen Bestimmungen. Informiere dich genau über diese Bestimmungen und stelle sicher, dass alle jeweils vorgegebenen Rechnungsdaten enthalten sind.

[#100]
== Dokumentenvorlagen für Rechnungen einrichten

Bevor du Rechnungen generieren kannst, muss eine Dokumentenvorlage eingerichtet werden. Dokumentenvorlagen richtest du im Menü *Einrichtung » Mandant » [Mandant wählen] » Standorte » [Standort wählen] » Dokumente » Rechnung* ein. +
Weitere Informationen und Anleitungen zur Einrichtung der Dokumentenvorlage findest du auf der Handbuchseite xref:auftraege:auftragsdokumente.adoc#[Auftragsdokumente].

[TIP]
.Angaben zu Zahlungsziel und Skonto auf der Rechnung
====
Damit Angaben zu Zahlungsbedingungen (Valuta, Zahlungsziel, Skonto) auf Rechnungen angezeigt werden, müssen diese beim xref:auftraege:auftragsdokumente.adoc#intable-zahlungsbedingungen-dokumente[Einrichten der Dokumentenvorlage] für Rechnungen aktiviert werden.
====

[#200]
== Einzelne Rechnung erzeugen

Eine einzelne Rechnung kannst du in plentymarkets bei Bedarf direkt an einem beliebigen Auftrag erzeugen.

[.instruction]
Einzelne Rechnung erzeugen:

. Öffne das Menü *Aufträge » Aufträge bearbeiten*. +
→ Die Auftragsübersicht öffnet sich.
. Suche (icon:search[role="blue"]) anhand der Filtereinstellungen den Auftrag, für den eine Rechnung erzeugt werden soll.
. Öffne den gewünschten Auftrag.
. Wechsle in das Tab *Belege*. +
. Wähle aus der Dropdown-Liste *Beleg erstellen* das Dokument *Rechnung* aus. +
. Nimm die Einstellungen anhand <<table-orders-receipts-invoice>> vor. +
. *Speichere* (icon:plus-square[role="green"]) die Einstellungen, um die Rechnung zu erzeugen. +
→ Es öffnet sich eine *PDF-Datei* mit der soeben erzeugten Rechnung.

[[table-orders-receipts-invoice]]
.Einstellungen für Rechnungen im Menü *Beleg erstellen*
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Datum*
|Gib das Datum an, das als Rechnungsdatum auf der Rechnung angezeigt wird. Standardmäßig ist das aktuelle Datum voreingestellt.

| *Ändere Auftragsstatus auf Status*
|Einen Status wählen, in den der Auftrag nach dem Erzeugen der Rechnung wechseln sollen. Wenn kein Statuswechsel gewünscht ist, die Option *Keine Änderung* wählen.

| *Kommentar*
|Einen Text eingeben, der auf der Rechnung unterhalb der Artikelpositionen angezeigt wird. Die Eingabe ist optional.
|====

[IMPORTANT]
.Gesperrte Aufträge
====
Nach dem Erzeugen einer Rechnung werden Aufträge standardmäßig gesperrt. Es können dann z.B. keine Artikelpositionen mehr hinzugefügt werden. Erstelle einen xref:auftraege:rechnungen-erzeugen.adoc#400[Stornobeleg], um einen Auftrag trotz vorhandener Rechnung zu bearbeiten.
====

[#300]
== Mehrere Rechnungen erzeugen

Sollen mehrere Rechnungen zugleich erzeugt werden, legst du über einen Suchfilter im Menü *Aufträge » Fulfillment* fest, welche Aufträge berücksichtigt werden. Zudem kannst du in diesem Menü festlegen, ob der Status des Auftrags geändert werden soll, nachdem die Rechnungen erzeugt wurden.

[.instruction]
Mehrere Rechnungen erzeugen:

. Öffne das Menü *Aufträge » Fulfillment » Rechnungen erzeugen*.
. Nimm die Einstellungen anhand <<table-settings-fulfillment-invoices>> vor. +
_Beachte_, dass die Einstellungen sowohl *Suchfilter* als auch *Aktionen* umfassen.
. Klicke auf das *Zahnrad* (icon:cog[]), um die Rechnungen zu erzeugen. +
→ Es öffnet sich eine *PDF-Datei*, in der die zugehörigen Rechnungen aller von dir durch die Suchfilter bestimmten Aufträge enthalten sind.

[[table-settings-fulfillment-invoices]]
.Optionen *Rechnungen erzeugen*
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Auftragsstatus*
|Aus der Liste den Status der Aufträge wählen, die für die Rechnung berücksichtigt werden sollen. +
_Hinweis_: Wenn du nach Aufträgen mit dem Status *Warenausgang gebucht* (Status 7) filterst, wird im Hintergrund nach allen Aufträgen gesucht, für die heute, am aktuellen Datum, der Warenausgang gebucht wurde. Es wird der Hinweis *Warenausgang: HEUTE* angezeigt, um dies zu verdeutlichen.

| *Eigner*
|Wähle einen Eigner aus, für dessen Aufträge die Rechnungen erzeugt werden sollen oder die Option *ALLE*, wenn für alle Eigner die Rechnungen erzeugt werden sollen.

| *Standort*
|Wähle einen Standort aus, für den die Rechnungen erzeugt werden sollen.

| *Lager*
|Wähle ein Lager oder *ALLE* aus.

| *Kundenklasse*
|Wähle eine Kundenklasse aus, für die die Rechnungen erzeugt werden sollen oder die Option *ALLE*, wenn für alle Kundenklassen die Rechnungen erzeugt werden sollen.

| *Zahlungsart*
|Wähle eine der Zahlungsarten oder die Option *ALLE*.

| *Sortierung*
|Lege fest, wie die erzeugten Rechnungen sortiert werden sollen. Die Optionen *Auftrags-ID*, *Kunden-ID* und *Artikel-ID* geben verschiedene Sortierungen aus.

| *Limit*
|Lege fest, wie viele Rechnungen maximal pro Durchgang erzeugt werden. Das Maximum liegt bei *200* Rechnungen.

| *Rechnungsdatum* (Aktion)
|Wähle ein Datum aus dem Kalender aus, das als Rechnungsdatum auf den Rechnungen erscheinen soll.

| *Ändere Auftragsstatus* (Aktion)
|Wähle einen Status, in den die Aufträge nach Erzeugung der Rechnungen wechseln sollen. +
Der Statuswechsel ist wichtig, damit für bereits bearbeitete Aufträge ein Prozess nicht noch einmal durchgeführt wird.
|====

[#400]
== Rechnung korrigieren und stornieren

Wenn du oder deine Kund:in nachträglich feststellen, dass eine Angabe auf der Rechnung fehlerhaft ist und du diese korrigieren möchtest, erstelle einen Stornobeleg und erzeuge anschließend eine neue Rechnung.
Durch Stornieren der Rechnung können Änderungen schnell nachvollzogen werden, da sowohl die alte Rechnung, der Stornobeleg und die neue Rechnung vorhanden sind. Wenn du den gesamten Auftrag stornieren möchtest, nutze den Auftragsstatus *storniert*. Wenn du den Auftrag bearbeiten möchtest und einige Angaben korrigierst, nutze den Stornobeleg. +
Beachte, dass eine Rechnung nur storniert werden kann, wenn keine Mahnung für den entsprechenden Auftrag existiert. In diesem Fall muss auch die Mahnung erst storniert werden. Nutze hierzu den xref:auftraege:mahnungen-erzeugen.adoc#400[Stornobeleg Mahnung].

[#500]
=== Vorlage Stornobeleg einrichten

Richte zunächst die Vorlage für das Dokument Stornobeleg ein. Der schnellste Weg ist in diesem Fall das Übernehmen der Einstellungen aus der Standard-Dokumentvorlage oder das Kopieren der Einstellungen einer Rechnungsvorlage. +
Im Folgenden wird kurz das Übernehmen der Standard-Dokumentvorlage beschrieben.

[.instruction]
Vorlage einrichten:

. Öffne das Menü *Einrichtung » Mandant » [Mandant wählen] » Standorte » [Standort wählen] » Dokumente » Stornobeleg Rechnung*.
. Wechsle in das Tab *Transfer*.
. Klicke unter *Einstellungen aus Standard-Dokumentenvorlage übernehmen* auf *Übernehmen* (icon:gear[role="darkGrey", stack="long-arrow-right,lr,darkGrey"]).

Da die Einstellungen der Vorlage für Stornobelege mit den Einstellungen der Vorlage für Rechnungen übereinstimmen, findest du nähere Erläuterungen zu den einzelnen Einstellungen auf der Seite xref:auftraege:rechnungen-erzeugen.adoc#[Rechnungen erzeugen].

[#600]
=== Rechnung korrigieren

Eine Rechnung korrigierst du, indem du sie zunächst stornierst. Das Stornieren einer Rechnung dient der nachvollziehbaren Korrektur von rechnungsrelevanten Daten und nicht der Stornierung eines Auftrages. Anschließend kann der Auftrag wieder bearbeitet werden und eine neue Rechnung erzeugt werden.

[.instruction]
Rechnung korrigieren:

. Öffne das Menü *Aufträge » Aufträge bearbeiten*.
. Öffne den Auftrag, dessen Rechnung du stornieren möchtest.
. Wechsle in das Tab *Belege*.
. Wähle aus der Dropdown-Liste *Beleg erstellen* den *Stornobeleg*. +
→ Ein Fenster mit optionalen Einstellungen wird geöffnet.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Der Stornobeleg wird erzeugt und die Auftragseinstellungen entsperrt.
. Bearbeite jetzt die Daten, die du korrigieren möchtest. +
→ Trage z.B. eine Umsatzsteueridentifiaktionsnummer in der Rechnungsanschrift nach.
. Wechsle wieder in das Tab *Belege*.
. Wähle aus der Dropdown-Liste *Beleg erstellen* die *Rechnung*. +
→ Ein Fenster mit optionalen Einstellungen wird geöffnet.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Die Rechnung wird erzeugt und die Auftragseinstellungen gesperrt.
