= Rechnungen
:keywords: Rechnung, Rechnungen erzeugen, Dokument, Auftragsdokument, Dokumentenvorlage, Dokumenttyp, Dokumententyp, Rechnungsdaten, Storno, Stornobeleg, Rechnungsdatum, Steuerdokument, Dokumentvorlage, Rechnungsstorno, Zahlungsbedingungen
:author: team-docs-automation
:description: Erfahre, wie du Rechnungen entweder einzeln oder gesammelt als PDF-Datei generierst und an deine Kund:innen versendest. Lerne außderdem, wie du Rechnungen korrigierst und stornierst.

In plentymarkets generierst du Rechnungen entweder einzeln oder gesammelt als PDF-Dateien, um diese z.B. zu drucken oder deinen Kund:innen als E-Mail Anhang zukommen zu lassen. +
Je nach Lieferland und Standort unterliegen Rechnungen verschiedenen gesetzlichen Bestimmungen. Informiere dich genau über diese Bestimmungen und stelle sicher, dass alle jeweils vorgegebenen Rechnungsdaten enthalten sind.

[#100]
== Dokumentenvorlagen für Rechnungen einrichten

Bevor du Rechnungen generieren kannst, muss eine Dokumentenvorlage eingerichtet werden. Dokumentenvorlagen richtest du im Menü *Einrichtung » Mandant » [Mandant wählen] » Standorte » [Standort wählen] » Dokumente » Rechnung* ein. +
Weitere Informationen und Anleitungen zur Einrichtung der Dokumentenvorlage findest du auf der Handbuchseite xref:auftraege:auftragsdokumente-neu.adoc#[Auftragsdokumente].

[TIP]
.Angaben zu Zahlungsziel und Skonto auf der Rechnung
====
Damit Angaben zu Zahlungsbedingungen (Valuta, Zahlungsziel, Skonto) auf Rechnungen angezeigt werden, müssen diese beim xref:auftraege:auftragsdokumente-neu.adoc#intable-zahlungsbedingungen-dokumente[Einrichten der Dokumentenvorlage] für Rechnungen aktiviert werden.
====

[#200]
== Einzelne Rechnung erzeugen

Eine einzelne Rechnung kannst du in plentymarkets bei Bedarf direkt an einem beliebigen Auftrag erzeugen.

[.instruction]
Einzelne Rechnung erzeugen:

. Öffne das Menü *Aufträge » Aufträge*. +
→ Die Auftragsübersicht wird geöffnet.
. Führe die Suche (material:search[]) aus, um Aufträge anzuzeigen.
. Öffne den Auftrag, für den eine Rechnung erzeugt werden soll. Beachte, dass Aufträge nur in der Listenansicht geöffnet werden können.
. Gehe in den Bereich *Dokumente*.
. Klicke oben links auf *Dokument erstellen* (material:add[]).
. Wähle das Dokument *Rechnung* aus der Dropdown-Liste. +
→ Das Fenster *Dokument erzeugen: Rechnung* wird geöffnet.
. Gib ein Datum ein, das als Rechnungsdatum auf der Rechnung angezeigt werden soll.
. Gib optional einen Kommentar ein, der auf der Rechnung angezeigt werden soll.
. Klicke auf *Erstellen* (material:add[role="green"]). +
→ Die Rechnung wird erstellt und im Bereich *Dokumente* hinzugefügt.

[IMPORTANT]
.Gesperrte Aufträge
====
Nach dem Erzeugen einer Rechnung werden Aufträge standardmäßig gesperrt. Es können dann z.B. keine Artikelpositionen mehr hinzugefügt werden. Erstelle einen xref:auftraege:rechnungen-erzeugen.adoc#400[Stornobeleg], um einen Auftrag trotz vorhandener Rechnung zu bearbeiten.
====

[#300]
== Mehrere Rechnungen erzeugen

Sollen mehrere Rechnungen zugleich erzeugt werden, legst du über einen Suchfilter im Menü *Aufträge » Fulfillment* fest, welche Aufträge berücksichtigt werden. Zudem kannst du in diesem Menü festlegen, ob der Status des Auftrags geändert werden soll, nachdem die Rechnungen erzeugt wurden.

[.instruction]
Mehrere Rechnungen erzeugen:

. Öffne das Menü *Aufträge » Fulfillment*.
. Klicke auf das kleine Plus in der Zeile *Rechnungen erzeugen*.
. Nimm die Einstellungen anhand <<table-settings-fulfillment-invoices>> vor. +
_Beachte_, dass die Einstellungen sowohl *Suchfilter* als auch *Aktionen* umfassen.
. Klicke auf das *Zahnrad* (icon:cog[]), um die Rechnungen zu erzeugen. +
→ Eine *PDF-Datei* wird geöffnet, in der die zugehörigen Rechnungen aller von dir durch die Suchfilter bestimmten Aufträge enthalten sind.

[[table-settings-fulfillment-invoices]]
.Optionen *Rechnungen erzeugen*
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+^| *Suchfilter*

| *Auftragsstatus*
|Aus der Liste den Status der Aufträge wählen, die für die Rechnung berücksichtigt werden sollen. +
_Hinweis_: Wenn du nach Aufträgen mit dem Status *Warenausgang gebucht* (Status 7) filterst, wird im Hintergrund nach allen Aufträgen gesucht, für die heute, am aktuellen Datum, der Warenausgang gebucht wurde. Es wird der Hinweis *Warenausgang: HEUTE* angezeigt, um dies zu verdeutlichen.

| *Eigner*
|Wähle einen Eigner aus, für dessen Aufträge die Rechnungen erzeugt werden sollen oder die Option *ALLE*, wenn für alle Eigner die Rechnungen erzeugt werden sollen.

| *Standort*
|Wähle einen Standort aus, für den die Rechnungen erzeugt werden sollen.

| *Lager*
|Wähle ein Lager oder *ALLE* aus.

| *Kundenklasse*
|Wähle eine Kundenklasse aus, für die die Rechnungen erzeugt werden sollen oder die Option *ALLE*, wenn für alle Kundenklassen die Rechnungen erzeugt werden sollen.

| *Zahlungsart*
|Wähle eine der Zahlungsarten oder die Option *ALLE*.

| *Sortierung*
|Lege fest, wie die erzeugten Rechnungen sortiert werden sollen. Die Optionen *Auftrags-ID*, *Kunden-ID* und *Artikel-ID* geben verschiedene Sortierungen aus.

| *Limit*
|Lege fest, wie viele Rechnungen maximal pro Durchgang erzeugt werden. Das Maximum liegt bei *200* Rechnungen.

2+^| *Aktion*

| *Rechnungsdatum*
|Wähle ein Datum aus dem Kalender aus, das als Rechnungsdatum auf den Rechnungen erscheinen soll.

| *Ändere Auftragsstatus*
|Wähle einen Status, in den die Aufträge nach Erzeugung der Rechnungen wechseln sollen. +
Der Statuswechsel ist wichtig, damit für bereits bearbeitete Aufträge ein Prozess nicht noch einmal durchgeführt wird.
|====

[#400]
== Rechnung stornieren und korrigieren

Wenn du oder deine Kund:in nachträglich feststellen, dass eine Angabe auf der Rechnung fehlerhaft ist und du diese korrigieren möchtest, erstelle einen Stornobeleg und erzeuge anschließend eine neue Rechnung.
Durch Stornieren der Rechnung können Änderungen schnell nachvollzogen werden, da sowohl die alte Rechnung, der Stornobeleg und die neue Rechnung vorhanden sind. Wenn du den gesamten Auftrag stornieren möchtest, nutze den Auftragsstatus *storniert*. Wenn du den Auftrag bearbeiten möchtest und einige Angaben korrigierst, nutze den Stornobeleg. +
Beachte, dass eine Rechnung nur storniert werden kann, wenn keine Mahnung für den entsprechenden Auftrag existiert. In diesem Fall muss auch die Mahnung erst storniert werden. Nutze hierzu den xref:auftraege:mahnungen-erzeugen.adoc#400[Stornobeleg Mahnung].

[#600]
=== Stornobeleg Rechnung erstellen

Eine Rechnung korrigierst du, indem du sie zunächst stornierst. Das Stornieren einer Rechnung dient der nachvollziehbaren Korrektur von rechnungsrelevanten Daten und nicht der Stornierung eines Auftrages. Anschließend kann der Auftrag wieder bearbeitet werden und eine neue Rechnung erzeugt werden.

[.instruction]
Stornobeleg Rechnung erstellen:

. Öffne das Menü *Aufträge » Aufträge*.
. Führe die Suche (material:search[]) aus, um Aufträge anzuzeigen.
. Öffne den Auftrag, dessen Rechnung du stornieren möchtest. Beachte, dass Aufträge nur in der Listenansicht geöffnet werden können.
. Gehe in den Bereich *Dokumente*.
. Klicke oben links auf *Dokument erstellen* (material:add[]).
. Wähle das Dokument *Stornobeleg Rechnung* aus der Dropdown-Liste. +
→ Das Fenster *Dokument erzeugen: Stornobeleg Rechnung* wird geöffnet.
. Gib ein Datum ein, das als Stornierungsdatum angezeigt wird.
. Gib optional einen Kommentar ein, der auf dem Stornobeleg angezeigt wird.
. Klicke auf *Erstellen* (material:add[role="green"]). +
→ Die Rechnung wird erstellt und im Bereich *Dokumente* hinzugefügt.

[#700]
=== Neue Rechnung erstellen

Nachdem du einen Stornobeleg für die Rechnung erstellt und den Auftrag entsprechend angepasst hast, kannst du nun eine neue Rechnung erstellen.

[.instruction]
Neue Rechung erstellen:

. Öffne das Menü *Aufträge » Aufträge*. +
→ Die Auftragsübersicht wird geöffnet.
. Suche anhand der Filtereinstellungen den Auftrag, für den eine neue Rechnung erzeugt werden soll.
. Öffne den gewünschten Auftrag. Beachte, dass Aufträge nur in der Listenansicht geöffnet werden können.
. Gehe in den Bereich *Dokumente*.
. Klicke oben links auf *Dokument erstellen* (material:add[]).
. Wähle das Dokument *Rechnung* aus der Dropdown-Liste. +
→ Das Fenster *Dokument erzeugen: Rechnung* wird geöffnet.
. Gib ein Datum ein, das als Rechnungsdatum auf der neuen Rechnung angezeigt wird.
. Gib optional einen Kommentar ein, der auf der neuen Rechnung angezeigt wird.
. Klicke auf *Erstellen* (material:add[role="green"]). +
→ Die neue Rechnung wird erstellt und im Bereich *Dokumente* hinzugefügt.
