= Reparaturscheine
:page-aliases: dokument-reparaturschein-erzeugen.adoc
:keywords: Reparaturschein, Reparaturschein erzeugen, Auftragsdokumente, Dokumentenvorlage, Dokumententyp, Dokument, Dokumentvorlage, Dokumenttyp, Reparaturdokument
:author: team-docs-automation
:description: Erfahre, wie du Reparaturscheine im Zusammenhang mit dem Auftragstyp Reparatur für retournierte oder reparaturbedürftige Ware erstellst.

Reparaturscheine nutzt du im Zusammenhang mit dem xref:auftraege:order-type-repair.adoc#[Auftragstyp Reparatur]. Reparaturen und Reparaturscheine sind also immer retournierter, reparaturbedürftiger Ware zugeordnet. Daher lassen sich Reparaturscheine auch nur aus einem Reperaturauftrag heraus erzeugen.

[#100]
== Dokumentenvorlage für Reparaturscheine einrichten

Bevor du Reparaturscheine generieren kannst, muss eine Dokumentenvorlage eingerichtet werden. Dies geschieht im Menü *Einrichtung » Mandant » [Mandant wählen] » Standorte » [Standort wählen] » Dokumente » Reparaturschein*. +
Weitere Informationen und Anleitungen zur Einrichtung der Dokumentenvorlage findest du auf der Handbuchseite xref:auftraege:auftragsdokumente-neu.adoc#[Auftragsdokumente].

[#200]
== Einzelnen Reparaturschein erzeugen

Reparaturscheine können nur für den Auftragstypen *Reparatur* erzeugt werden. Um einen Reparaturschein manuell aus einem bestimmten Reparaturauftrag zu erzeugen, gehe wie im Folgenden beschrieben vor.

[.instruction]
Einzelnen Reparaturschein erzeugen:

. Öffne das Menü *Aufträge » Aufträge*. +
→ Die Auftragsübersicht wird geöffnet.
. Führe die Suche (material:search[]) aus, um Aufträge anzuzeigen.
. Öffne den Auftrag vom Typ Reparatur, für den ein Reparaturschein erzeugt werden soll. Beachte, dass Aufträge nur in der Listenansicht geöffnet werden können.
. Gehe in den Bereich *Dokumente*.
. Klicke oben links auf *Dokument erstellen* (material:add[]).
. Wähle das Dokument *Reparaturschein* aus der Dropdown-Liste. +
→ Das Fenster *Dokument erzeugen: Reparaturschein* wird geöffnet.
. Gib ein Datum ein, das auf dem Reparaturschein angezeigt werden soll.
. Gib optional einen Kommentar ein, der auf dem Reparaturschein angezeigt werden soll.
. Klicke auf *Erstellen* (material:add[role="green"]). +
→ Der Reparaturschein wird erstellt und im Bereich *Dokumente* hinzugefügt.
