= Rücksendescheine
:keywords: Rücksendeschein, Rücksendescheine erzeugen, Dokument, Auftragsdokument, Dokumentenvorlage, Dokumenttyp, Dokumententyp, Dokumentvorlage
:author: team-docs-automation
:description: Erfahre, wie du Rücksendescheine als PDF-Datei erzeugst und deinen Kund:innen zusendest, damit sie diesen beim Umtausch oder bei einer Retoure der Warensendung beilegen können.

In plentymarkets generierst du Rücksendescheine als PDF-Dateien, um diese z.B. zu drucken oder deinen Kund:innen als E-Mail-Anhang zukommen zu lassen. Somit können deine Kund:innen Rücksendescheine beispielsweise beim Umtausch von Artikeln oder bei Retouren einfach der Warensendung beilegen.

[#200]
== Dokumentenvorlage für Rücksendescheine einrichten

Bevor du Rücksendescheine generieren kannst, muss eine Dokumentenvorlage eingerichtet werden. Dokumentenvorlagen richtest du im Menü *Einrichtung » Mandant » [Mandant wählen] » Standorte » [Standort wählen] » Dokumente » Rücksendeschein* ein. +
Weitere Informationen und Anleitungen zur Einrichtung der Dokumentenvorlage findest du auf der Handbuchseite xref:auftraege:auftragsdokumente-neu.adoc#[Auftragsdokumente].

[#300]
== Einzelnen Rücksendeschein erzeugen

In manchen Fällen macht es Sinn, Rücksendescheine zu bestimmten Aufträgen manuell zu erzeugen. Dies geschieht sowohl für reguläre Aufträge als auch für Retourenaufträge in der Auftragsübersicht.

Einen einzelnen Rücksendeschein kannst du in plentymarkets bei Bedarf manuell direkt am Auftrag erzeugen. Der so erzeugte Rücksendeschein beinhaltet dann alle im Auftrag enthaltenen Artikelpositionen. Nutze diese Methode, um jedem Paket, das du versendest, einen unausgefüllten Rücksendeschein beizulegen. Weitere Informationen hierzu findest du im Kapitel xref:auftraege:order-type-return.adoc#create-return-label[Rücksendeschein erstellen].

[.instruction]
Einzelnen Rücksendeschein erzeugen:

. Öffne das Menü *Aufträge » Aufträge (Testphase)*.
→ Die Auftragsübersicht wird geöffnet.
. Führe die Suche (material:search[]) aus, um Aufträge anzuzeigen.
. Öffne den Auftrag, für den ein Rücksendeschein erzeugt werden soll.
. Gehe in den Bereich *Dokumente*.
. Klicke oben links auf *Dokument erstellen* (material:add[]).
. Wähle das Dokument *Rücksendeschein* aus der Dropdown-Liste. +
→ Das Fenster *Dokument erzeugen: Rücksendeschein* wird geöffnet.
. Gib ein Datum ein, das auf dem Rücksendeschein angezeigt werden soll.
. Gib optional einen Kommentar ein, der auf dem Rücksendeschein angezeigt werden soll.
. Klicke auf *Erstellen* (material:add[role="green"]). +
→ Der Rücksendeschein wird erstellt und im Bereich *Dokumente* hinzugefügt.

[#600]
== Mehrere Rücksendescheine erzeugen

Sollen für mehrere Aufträge zugleich Rücksendescheine erzeugt werden, kannst du über einen Suchfilter im Menü *Aufträge » Fulfillment* bestimmen, welche Aufträge berücksichtigt werden. Zudem kannst du in diesem Menü festlegen, ob der Status des Auftrags geändert werden soll, nachdem die Rücksendescheine erzeugt wurden.

[.instruction]
Mehrere Rücksendescheine erzeugen:

. Öffne das Menü *Aufträge » Fulfillment*.
. Klicke auf das kleine Plus in der Zeile *Rücksendeschein erzeugen*.
. Nimm die Einstellungen anhand <<table-settings-fulfillment-return-slip>> vor. +
_Beachte_, dass die Einstellungen sowohl *Suchfilter* als auch *Aktionen* umfassen.
. Klicke auf das *Zahnrad* (icon:cog[]), um die Rücksendescheine zu erzeugen. +
→ Eine *PDF-Datei* wird geöffnet, in der die zugehörigen Rücksendescheine aller von dir durch die Suchfilter bestimmten Aufträge enthalten sind.

[[table-settings-fulfillment-return-slip]]
.Optionen im Menü *Rücksendeschein erzeugen*
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+^| *Suchfilter*

| *Auftragsstatus*
|Wähle den Status der Aufträge aus der Dropdown-Liste, die für das Erzeugen der Rücksendescheine berücksichtigt werden sollen.

| *Eigner*
|Wähle einen Eigner aus der Dropdown-Liste, für dessen Aufträge die Rücksendescheine erzeugt werden sollen oder wähle die Option *ALLE*, wenn für alle Eigner Rücksendescheine erzeugt werden sollen.

| *Standort*
|Wähle einen Standort aus der Dropdown-Liste, für den die Rücksendescheine erzeugt werden sollen.

| *Lager*
|Wähle ein Lager aus der Dropdown-Liste, für das die Rücksendescheine erzeugt werden sollen oder wähle die Option *ALLE*, wenn für alle Lager Rücksendescheine erzeugt werden sollen.

| *Zahlungsart*
|Wähle eine Zahlungsart aus der Dropdown-Liste, für die die Rücksendescheine erzeugt werden sollen oder wähle die Option *ALLE*, wenn für alle Zahlungsarten Rücksendescheine erzeugt werden sollen.

| *Sortierung*
|Lege fest, wie die erzeugten Rücksendescheine sortiert werden sollen. Die Optionen *Auftrags-ID*, *Kunden-ID* und *Artikel-ID* geben verschiedene Sortierungen aus.

| *Limit*
|Lege fest, wie viele Rücksendescheine maximal pro Durchgang erzeugt werden sollen. Das Maximum liegt bei *200*.

2+^| *Aktion*

| *Ändere Auftragsstatus*
|Wähle einen Status, in den die Aufträge nach Erzeugung der Rücksendescheine wechseln sollen. +
Der Statuswechsel ist wichtig, damit für bereits bearbeitete Aufträge ein Prozess nicht noch einmal durchgeführt wird.

| *Kommentar*
|Gib optional einen Kommentar ein, der auf allen Rücksendescheinen unterhalb der Artikelpositionen angezeigt werden soll.
|====
