= Mit Aufträgen arbeiten

:keywords: Auftragsanlage, Aufträge anlegen, Gruppenfunktionen für Aufträge, Bereiche für Aufträge, Auftrag teilen, Gutschein einlösen, Verkaufspreise
:author: team-order-core
:description: Erfahre, wie du mit Aufträgen arbeitest, Gruppenfunktionen nutzt und Einstellungen in den verschiedenen Bereichen eines Auftrags vornimmst. Lerne außerdem, wie du Gutscheine einlöst.

//menü artikel bearbeiten (im bereich auftragspositionen) hinzufügen

Aufträge bilden deine Verkäufe sowie damit einhergehende und übliche Geschäftsvorfälle ab. Mithilfe von xref:auftraege:order-types.adoc#[Auftragstypen] werden die unterschiedlichen Geschäftsvorfälle kenntlich gemacht. Fortschritte bei der Bearbeitung eines Auftrags werden durch xref:auftraege:order-statuses.adoc#[Auftragsstatus] angezeigt. Alle Aufträge werden zentral und in einem einheitlichen Format erfasst. Bereits in der Auftragsübersicht siehst du wichtige Informationen auf einen Blick und kannst einige Arbeiten direkt ausführen.

[#basic-info-create-orders]
== Allgemeines zur Auftragsanlage in plentymarkets

In plentymarkets wird ein Auftrag automatisch angelegt, wenn Kund:innen Bestellungen in deinem Webshop oder auf einem angebundenen Marktplatz tätigen. Unterschiedliche Geschäftsvorfälle wie xref:auftraege:order-type-delivery-order.adoc#[Lieferaufträge], xref:auftraege:order-type-return.adoc#[Retouren], xref:auftraege:order-type-credit-note.adoc#[Gutschriften], xref:auftraege:order-type-warranty.adoc#[Gewährleistungen] und xref:auftraege:order-type-repair.adoc#[Reparaturen] werden mithilfe eigener Aufträge verschiedener Typen abgebildet, die immer mit dem Hauptauftrag verbunden sind. Über die Auftragsübersicht lassen sich Aufträge ungeachtet der xref:auftraege:auftragsherkunft.adoc#[Auftragsherkunft] öffnen und bearbeiten. Für viele Auftragstypen, wie zum Beispiel xref:auftraege:order-type-delivery-order.adoc#[Lieferaufträge], ist das Einrichten von xref:automatisierung:ereignisaktionen.adoc#[Ereignisaktionen] sinnvoll, um Vorgänge zu automatisieren. Einige Beispiele für die Nutzung von Ereignisaktionen für die Auftragsabwicklung werden in den folgenden Kapiteln erläutert. +
Aufträge, die nicht über den Webshop oder einen Marktplatz bei dir eingehen, legst du xref:auftraege:manually-create-orders.adoc#[manuell] im System an. Das ist beispielsweise bei telefonischen oder E-Mail-Bestellungen sowie bei Barverkäufen der Fall.

Passe die xref:auftraege:preparatory-settings.adoc#[Grundeinstellungen] im Menü *Einrichtung » Aufträge » Einstellungen* an, bevor du die ersten Aufträge in deinem plentymarkets System abwickelst. Speichere die Grundeinstellungen auch dann einmalig ab, wenn du die voreingestellten Werte nicht verändert hast.

[#order-group-functions]
== Gruppenfunktionen nutzen

Nutze die Gruppenfunktionen, um für mehrere Aufträge gleichzeitig eine Aktion auszuführen. Für Aufträge stehen dir die folgenden Gruppenfunktionen zur Verfügung.

[.instruction]
Gruppenfunktionen nutzen:

. Öffne das Menü *Aufträge » Aufträge (Testphase)*.
. Führe die Suche (material:search[]) aus, um Aufträge anzuzeigen.
. Wähle (material:check_box[role=skyBlue]) alle Aufträge, für die du gesammelt eine Aktion ausführen möchtest.
. Wähle eine der verfügbaren Gruppenfunktionen. Beachte dazu die Erläuterungen in <<table-order-group-functions>>.

[TIP]
.Standard-Gruppenfunktionen wählen
Im Bearbeitungsmodus (terra:design_inline_edit[role="darkGrey"]) der Auftragsübersicht kannst du *Standard-Gruppenfunktionen* festlegen, die beim Wählen von Aufträgen direkt sichtbar werden. Alle übrigen Gruppenfunktionen werden automatisch in das Kontextmenü (material:more_vert[]) verlagert.

[[table-order-group-functions]]
.Gruppenfunktionen für Aufträge
[cols="2,1,6a"]
|===
|Einstellung |Symbol |Erläuterung

| *Aufträge gruppieren*
|material:library_add_check[]
|Gruppiert die gewählten Aufträge.

| *Status ändern*
|material:repeat_one[]
|Ändert den Status für die gewählten Aufträge. Wähle einen anderen Status aus der Dropdown-Liste.

| *Tag ändern*
|material:label[]
|Ändert das Tag für die gewählten Aufträge. Du kannst sowohl Tags hinzufügen als auch Tags entfernen. Wähle die gewünschten Tags aus der Dropdown-Liste.

| *Warenausgang buchen*
|material:book[]
|Bucht den Warenausgang für alle gewählten Aufträge. Wähle ein Datum für den Warenausgang.

| *Aufträge löschen*
|material:delete[]
|Löscht alle gewählten Aufträge.

3+^| *Kontextmenü* (material:more_vert[])
| *Warenausgang zurückbuchen*
|material:book[]
|Bucht den Warenausgang von allen gewählten Aufträgen zurück.

| *Eigner ändern*
|material:people_alt[]
|Ändert den Eigner für alle gewählten Aufträge. Wähle einen Eigner aus der Dropdown-Liste.

| *Versandprofil ändern*
|material:local_shipping[]
|Ändert das Versandprofil für alle gewählten Aufträge. Wähle ein Versandprofil aus der Dropdown-Liste.

| *Lieferdatum für Auftrag setzen*
|material:schedule_send[]
|Setzt ein Lieferdatum für alle gewählten Aufträge. Gib ein Lieferdatum ein oder wähle ein Datum über den Kalender (material:today[]).

| *Versanddatum für Auftragsposition setzen*
|material:pending_actions[]
|Setzt ein Versanddatum für die Auftragsposition aller gewählten Aufträge. Gib ein Versanddatum ein oder wähle ein Datum über den Kalender (material:today[]).

| *Dokument erstellen*
|material:note_add[]
|Erstellt ein Dokument für alle gewählten Aufträge. Wähle einen Dokumenttyp aus der Dropdown-Liste. Gib außerdem ein Erstellungsdatum für das Dokument ein oder wähle ein Datum über den Kalender (material:today[]).

|===

== Weitere Funktionen in der Auftragsübersicht nutzen

Rechts in der Auftragsübersicht sind je nach Auftragstyp weitere Funktionen über das Kontextmenü (material:more_vert[]) verfügbar. Darüber kannst du beispielsweise Dokumente anlegen oder Zahlungen buchen.

[[table-context-menu-functions]]
.Weitere Funktionen für Aufträge
[cols="2,1,6a"]
|===

|Einstellung |Symbol |Erläuterung

| *Dokument erstellen*
|material:add[]
|Ermöglicht das Erstellen von Dokumenten. Je nach Auftragstyp sind verschiedene Dokumente verfügbar.

| *Status ändern*
|material:repeat_one[]
|Ermöglicht das Ändern des Status für einen Auftrag. Der aktuelle Status ist hier vorausgewählt. Wähle einen anderen Status aus der Dropdown-Liste.

| *Warenausgang buchen*
|material:output[]
|Bucht den Warenausgang. Das aktuelle Datum sowie die Uhrzeit der Buchung wird angezeigt. Wähle bei Bedarf ein anderes Buchungsdatum oder eine andere Uhrzeit über den Kalender (material:today[]).

| *Referenzierte Bestellungen anzeigen*
|material:account_tree[]
|Zeigt die Auftragsreferenzen an. Konfiguriere (material:settings[]) die Spalten der Tabelle bei Bedarf.

| *Zahlung buchen*
|material:payment[]
|Ermöglicht das Buchen einer Zahlung. Gib die Daten der Zahlung ein, die du buchen möchtest.

| *Warenbestand ermitteln*
|material:warehouse[]
|Zeigt den Warenbestand sowie eventuelle Nachbestellungen für das Lager der Auftragsposition an. Klappe die Zeilen aus (material:chevron_right[]), um weitere Informationen zum Warenbestand zu sehen.

| *Tracking-Link öffnen*
|terra:shipment_tracking[]
|Öffnet den Tracking-Link der Paketnummern.

| *Auftrag im Versand-Center öffnen*
|terra:outgoing_items[]
|Öffnet den Auftrag im Versand-Center 2.0.

| *Auftrag löschen*
|material:delete[]
|Ermöglicht das Löschen eines Auftrags. Beachte, dass Aufträge unter Umständen nicht gelöscht werden können.

|===

[TIP]
Hast du einen Auftrag geöffnet, kannst du ganz unten links in der Seitennavigation die ID des Auftrags mit einem Klick auf die Auftrags-ID (material:content_copy[]) in die Zwischenablage kopieren.

[#order-areas]
== Erläuterungen zu den einzelnen Bereichen

Alle in einem Auftrag verfügbaren Bereiche und deren Funktionen werden in den folgenden Unterkapiteln erläutert. Verwende den xref:design-order-view.adoc#editing-mode[Bearbeitungsmodus] und entscheide selbst, welche Felder dir in welchem Bereich angezeigt werden und in welcher Reihenfolge sie angeordnet sind. So kannst du deine Ansicht individuell gestalten und auf deine Bedürfnisse anpassen. Beachte, dass die verfügbaren Felder je nach Auftragstyp variieren können. Sobald du einen Auftrag geöffnet hast, werden alle Bereiche links in der Seitennavigation angezeigt. +
Mit einem Klick auf einen Eintrag in der folgenden Liste gelangst du direkt in das jeweilige Unterkapitel, in dem du weitere Informationen findest.

* <<#area-overview, Übersicht>>
* <<#area-status-tags, Status und Tags>>
* <<#area-general, Allgemein>>
* <<#area-addresses, Adressen>>
* <<#area-messenger, Messenger>>
* <<#area-order-items, Auftragspositionen>>
* <<#area-payment-terms, Zahlungsbedingungen>>
* <<#area-bank-data, Bankdaten>>
* <<#area-assigned-payments, Zugeordnete Zahlungen>>
* <<#area-order-references, Auftragsreferenzen>>
* <<#area-properties, Eigenschaften>>
* <<#area-documents, Dokumente>>
* <<#area-history, Historie>>
* <<#area-notes, Notizen>>
* <<#area-messenger, Messenger>>

[TIP]
.Wie werden die Daten in den einzelnen Bereichen geladen?
======
Wenn du in einem Auftrag auf der linken Seite in der Navigation auf den jeweiligen Bereich klickst, den du bearbeiten möchtest, leuchtet dieser Bereich kurz in blau auf, die vorhandenen Daten für diesen Bereich werden geladen und du kannst direkt mit der Bearbeitung beginnen. +
*_Hinweis:_* Die folgenden Bereiche werden bereits beim Öffnen des Auftrags initial geladen und geöffnet: *Übersicht*, *Status und Tags*, *Adressen*, *Allgemein*, *Auftragspositionen*, *Zahlungsbedingungen*, *Zugeordnete Zahlungen*, *Dokumente*, *Historie*, *Notizen*, *Messenger*. +
Die folgenden Bereiche werden erst nach einem Klick in der Navigation auf der linken Seite geladen und geöffnet: *Bankdaten*, *Auftragsreferenzen*, *Eigenschaften*.
======

[IMPORTANT]
.Backend-Benutzer:innen: Fehlende Rechte für bestimmte Bereiche, Schaltflächen und Funktionen im Auftrag?
====
Wenn eine Person mit *Backend*-Zugriffsrechten bestimmte Bereiche und/oder darin enthaltene Schaltflächen und Funktionen in einem Auftrag nicht sehen kann, muss eine Person mit *Admin*-Zugriffsrechten weitere Rechte im Benutzer:innenkonto im Menü *Einrichtung » Einstellungen » Benutzer » Rechte » Benutzer* aktivieren. +
Alle benötigten Rechte für die einzelnen Bereiche, Schaltflächen und Funktionen in Aufträgen findest du auf der Handbuchseite xref:auftraege:preparatory-settings.adoc#[Vorbereitende Einstellungen vornehmen] im Kapitel xref:auftraege:preparatory-settings.adoc#grant-user-rights[Rechte für Backend-Benutzer:innen vergeben].
====

[#area-overview]
=== Bereich: Übersicht

Im Bereich *Übersicht* siehst du alle grundlegenden Informationen zum Auftrag. <<#table-tab-overview>> listet alle Felder, die im Bereich *Übersicht* des Auftrags verfügbar sind.

[[table-tab-overview]]
.Einstellungen im Bereich *Übersicht*
[cols="1,3"]
|===

| *Warenwert brutto*
|Zeigt den Brutto-Warenwert an.

| *Warenwert netto*
|Zeigt den Netto-Warenwert an.

| *MwSt.*
|Zeigt die Mehrwertsteuer an.

| *Rechnungsbetrag*
|Zeigt den Rechnungsbetrag an.

| *Bezahlter Betrag*
|Zeigt den bezahlten Betrag an. +
Bei diesem Feld kannst du im Bearbeitungsmodus über die Einstellung *Anzeigeformat Betrag* wählen, ob der Betrag *prozentual* oder *absolut* angezeigt werden soll.

| *Versandkosten brutto*
|Zeigt die Brutto-Versandkosten an.

| *Versandkosten netto*
|Zeigt die Netto-Versandkosten an.

| *Artikelmenge*
|Zeigt die Anzahl der Artikel an.

| *Warengewicht*
|Zeigt das Warengewicht an.

| *Gewinnspanne netto*
|Zeigt die Netto-Gewinnspanne an.

| *Gutscheinzahlung*
|Zeigt die Gutscheinzahlung an.

| *Steuerfreier Betrag*
|Zeigt den steuerfreien Betrag an.

| *Gutscheinrabatt brutto*
|Zeigt den Brutto-Gutscheinrabatt an.

| *Gutscheinrabatt netto*
|Zeigt den Netto-Gutscheinrabatt an.

| *Mahnstufe*
|Zeigt die Mahnstufe an.

| *Umsatzsteuersätze*
|Zeigt die für den Auftrag verwendeten Umsatzsteuersätze an.

|===

[#area-status-tags]
=== Bereich: Status und Tags

Im Bereich *Status und Tags* siehst du den Status des Auftrags sowie die gewählten Tags.

[[table-area-status-tags]]
.Einstellungen im Bereich *Status und Tags*
[cols="1,3"]
|===
|Einstellung |Erläuterung

| *Status*
|Zeigt den Status an, in dem sich der Auftrag befindet. +
Wähle bei Bedarf einen anderen Auftragsstatus aus der Dropdown-Liste. +
*_Hinweis:_* Der Auftragsstatus *[7] Warenausgang gebucht* kann nicht in einen niedrigeren Status geändert werden, da die Ware bereits verschickt wurde. Um den Status dennoch zu ändern, muss die Buchung des Warenausgangs vorher zurückgesetzt werden.

| *Tags*
a|Zeigt die gewählten Tags. +
In der Dropdown-Liste werden alle von dir erstellten Tags angezeigt.

|===

[#area-general]
=== Bereich: Allgemein

Im Bereich *Allgemein* siehst du grundlegende Informationen zu deinem Auftrag auf einen Blick. Entscheide über den Bearbeitungsmodus selbst, welche Einstellungen in diesem Bereich angezeigt werden sollen.

[[table-area-general]]
.Einstellungen im Bereich *Allgemein*
[cols="1,3"]
|===
|Einstellung |Erläuterung

| *Auftragstyp*
|Zeigt den Auftragstyp an. Die Standardeinstellung für den Auftragstyp ist *Auftrag*. +
*_Tipp:_* Ein Auftrag kann mit nur wenigen Klicks in eine Vorbestellung geändert werden und andersherum. Klicke dazu rechts auf material:change_circle[] und bestätige die Abfrage.

| *Sprache*
|Zeigt die Sprache des Auftrags an. Die Standardeinstellung ist *Deutsch*. +
Auftragsdokumente sowie E-Mails werden in der Auftragssprache erzeugt. Du kannst die Sprache über die Dropdown-Liste beliebig anpassen. +
Beachte, dass zur Erzeugung der Dokumente und E-Mails in verschiedenen Sprachen die jeweiligen Vorlagen erstellt sein müssen.

| *Eigner*
|Wähle einen Eigner aus der Dropdownliste.

| *Benutzerdefiniertes Datum*
|Wähle ein benutzerdefiniertes Datum. +
*_Hinweis:_* Es können maximal 5 Daten hinzugefügt werden.

| *Mandant*
|Der hinterlegte Mandant wird angezeigt.

| *Standort*
|Zeigt den im Auftrag hinterlegten Standort an. +
Die Standardeinstellung ist *Deutschland*.

| *Lager*
|Zeigt das Lager bzw. das Hauptlager der Auftragsartikel an. +
*_Hinweis:_* Die Option *Lagerkorrektur* gleicht die Anzeige in den Einstellungen des Auftrags mit dem Lager ab, das im Bereich *Auftragspositionen* hinterlegt ist. Die Option wird nur angezeigt, wenn du in den Grundeinstellungen im Menü *Einrichtung » Aufträge » Einstellungen* bei *Zuordnung des Lagers* die Option *b) pro Artikelposition kann ein Lager zugeordnet werden* gewählt hast. Änderst du an einer Auftragsposition manuell das Lager und wird das neue Lager nicht automatisch in den Einstellungen des Auftrags übernommen, klicke auf *Lagerkorrektur*, um die Anzeige des Lagers zu aktualisieren.

| *Versandprofil und Porto*
|Zeigt das Versandprofil und die Portokosten an.

| *Benutzerdefinierte Eigenschaft*
|Wähle eine benutzerdefinierte Eigenschaft. +
*_Hinweis:_* Es können maximal 3 Eigenschaften hinzugefügt werden.

| *Herkunft*
|Zeigt die Herkunft des Auftrags an. Über die Dropdown-Liste kannst du die Herkunft anpassen. +
Die Standardeinstellung für für die Herkunft ist *0.00 Manuelle Eingabe*.

| *Zahlungsart*
|Zeigt die Zahlungsart an. Wähle die gewünschte Zahlungsart aus der Dropdown-Liste. Standardmäßig ist die Option *Vorkasse* vorausgewählt.

| *Externe Auftrags-ID*
|Zeigt die externe ID des Auftrags an.

| *Währung*
|Zeigt die Währung an. +
Die Standardeinstellung für die Währung ist *Euro (EUR)*.

| *Eingabedatum*
|Gib ein Eingabedatum ein oder wähle ein Datum über den Kalender (material:today[]).

| *Zeichen Kunde*
|Zeigt das Zeichen der Kund:in an.

| *Versanddatum*
|Gib ein Versanddatum ein oder wähle ein Datum über den Kalender (material:today[]).

| *Rückgabedatum*
|Gib ein Rückgabedatum ein oder wähle ein Datum über den Kalender (material:today[]).

| *Paketnummern*
|Zeigt die Paketnummern kommasepariert an.
Über *Tracking-Link öffnen* (terra:shipment_tracking[]) wird der Tracking-Link der Paketnummern geöffnet. +
Über *Versand-Center öffnen* (terra:outgoing_items[]) wird der Auftrag im xref:fulfillment:versand-center-2-0.adoc#[Versand-Center 2.0] geöffnet.

| *Mahnstufe*
|Zeigt die Mahnstufe an. +
In der Dropdown-Liste kannst du zwischen *Keine* und *Stufe 1* bis *Stufe 4* wählen.

| *Hauptdokument*
|Zeigt das Hauptdokument an.

| *Wechselkurs*
|Zeigt den Wechselkurs der gewählten Währung an.

| *Warenausgang*
|Zeigt das Datum und die Uhrzeit des Warenausgangs an.

| *Währung*
|Zeigt die Währung an.

| *Retoure-Paketnummern*
|Zeigt die Paketnummern einer Retoure kommasepariert an. Dieses Feld ist nur für den Auftragstyp *Retoure* verfügbar. Mit Klick auf terra:order_return[] wirst du zum Versand-Center 2.0 weitergeleitet.

| *Handelsvertreter*
|Gib den Namen des Handelsvertreters ein, um ihn für den Auftrag zu wählen. Alternativ kannst du auch die ID oder die E-Mail-Adresse des Handelsvertreters eingeben.

| *Status*
|Wähle einen Status aus der Dropdownliste.

|===

==== Pakete via Tracking-Link verfolgen

Über den an der Paketnummer hinterlegten Tracking-Link kannst du die Pakete deiner Aufträge verfolgen und somit sehen, wo sich deine Ware gerade befindet. Um Pakete zu verfolgen, gehe vor wie folgt.

[.instruction]
Pakete via Tracking-Link verfolgen:

. Öffne das Menü *Aufträge » Aufträge (Testphase)*.
. Führe die Suche (material:search[]) aus, um Aufträge anzuzeigen.
. Klicke oben rechts auf *Spalten konfigurieren* (material:settings[]).
. Wähle die Option *Tabelle Auftragsübersicht*.
. Wähle (icon:check[]) die Spalte *Paketnummern*.
. Klicke auf *Bestätigen*. +
→ Die Spalte *Paketnummern* wird mit den kommaseparierten Paketnummern des Auftrags in der Auftragsübersicht angezeigt.
. Klicke in der Zeile des Auftrags auf eine Paketnummer. +
icon:map-signs[] *_Oder:_* Klicke in der Zeile des Auftrags auf das Kontextmenü (material:more_vert[]) und wähle die Option *Tracking-Link öffnen* (terra:shipment_tracking[]).
→ Der Tracking-Link wird geöffnet.

[TIP]
.Tracking-Link bei mehreren Paketnummern splitten
======
Aktiviere im Menü *Einrichtung » Aufträge » Versand » Optionen* im Tab *Versanddienstleister* die Option *URLs splitten*, wenn ein Tracking-Link bei mehreren Paketnummern gesplittet werden soll. In diesem Fall wird für jede Paketnummer ein separater Link verwendet. Ist die Option nicht aktiviert, gibt es einen gemeinsamen Tracking-Link für alle Paketnummern.
======

[#area-addresses]
=== Bereich: Adressen

Im Bereich *Adressen* siehst du alle Informationen zur Rechnungs- und Lieferadresse.
Über das Kontextmenü (material:more_vert[]) kannst du die Einstellungen anpassen.

[[table-area-addresses]]
.Einstellungen im Bereich *Adressen*
[cols="1,3"]
|===
|Einstellung |Erläuterung

| *Rechnung*
a|Zeigt die Rechnungsadresse sowie die ID der Adresse an. Die Standardeinstellung enthält die folgenden Informationen: Name, Straße, PLZ und Ort, Land, E-Mail-Adresse sowie die ID. +
Die folgenden Felder stehen dir zur Verfügung: +

* Adressangaben +
** Anrede +
** Firma (Name 1) +
** Vorname (Name 2) +
** Nachname (Name 3) +
** Zusatz (Name 4) +
** Adresse 1 (Straße) +
** Adresse 2 (Hausnummer) +
** Adresse 3 (Adresszusatz) +
** Adresse 4 (Frei) +
** Postleitzahl +
** Ort +
** Land +
** Region/Bezirk +
* Adressoptionen: +
** E-Mail +
** Telefon +
** Typ +
** Wert

| *Lieferung*
a|Zeigt die Lieferadresse sowie die ID der Adresse an. Die Standardeinstellung enthält die folgenden Informationen: Name, Straße, PLZ und Ort, Land, E-Mail-Adresse sowie die ID. +
Die folgenden Felder stehen dir zur Verfügung: +

* Adressangaben +
** Anrede +
** Firma (Name 1) +
** Vorname (Name 2) +
** Nachname (Name 3) +
** Zusatz (Name 4) +
** Adresse 1 (Straße) +
** Adresse 2 (Hausnummer) +
** Adresse 3 (Adresszusatz) +
** Adresse 4 (Frei) +
** Postleitzahl +
** Ort +
** Land +
** Region/Bezirk +
* Adressoptionen: +
** E-Mail +
** Telefon +
** Typ +
** Wert

|===

==== Adresse ändern

Bei einer Adresse kannst du entweder einzelne Felder der aktuellen Adresse anpassen oder eine bereits bestehende Adresse zuweisen, die die aktuelle Adresse ersetzt. Gehe wie im Folgenden beschrieben vor, um eine Adresse zu ändern.

[.instruction]
Einzelne Felder einer Adresse ändern:

. Öffne das Menü *Aufträge » Aufträge (Testphase)*.
. Führe die Suche (material:search[]) aus, um Aufträge anzuzeigen.
. Öffne den Auftrag, für den du eine Adresse ändern möchtest.
. Gehe in den Bereich *Adressen*.
. Klicke bei der Rechnungs- bzw. Lieferadresse auf das Kontextmenü (material:more_vert[]).
. Wähle die Option *Adresse bearbeiten* (material:edit[]). +
→ Die Einstellungen der Adresse werden geöffnet.
. Nimm die Änderungen vor.
. *Speichere* (material:save[]) die Einstellungen. +
→ Die Adresse wird den Einstellungen entsprechend angepasst.


[.instruction]
Andere Adresse zuweisen:

. Öffne das Menü *Aufträge » Aufträge (Testphase)*.
. Führe die Suche (material:search[]) aus, um Aufträge anzuzeigen.
. Öffne den Auftrag, für den du eine Adresse ändern möchtest.
. Gehe in den Bereich *Adressen*.
. Klicke bei der Rechnungs- bzw. Lieferadresse auf das Kontextmenü (material:more_vert[]).
. Wähle die Option *Adresse ändern* (material:social_distance[]). +
→ Ein Fenster mit allen bereits verfügbaren Adressen des Kontakts wird geöffnet.
. Klicke rechts in der Zeile der gewünschten Adresse auf *Adresse zuweisen* (material:add_link[]). +
→ Die gewählte Adresse wird als neue Adresse zugewiesen.

*_Hinweis:_* Ist ein Auftrag gesperrt, können nur die folgenden Felder geändert werden: +

* Rechnungsadresse: *E-Mail-Adresse* und *Telefonnummer*
* Lieferadresse: alle Felder außer *Umsatzsteuernummer* und *Land*

[#area-messenger]
=== Bereich: Messenger

Im Bereich *Messenger* siehst du alle zum Auftrag gehörigen Nachrichten. Du kannst Nachrichten <<#nachricht-fluestern, flüstern>>, sodass sie nur intern sichtbar sind und _nicht_ für deine Kund:innen. Du kannst Nachrichten <<#nachricht-senden, senden>> und du kannst <<#nachricht-minuten-erfassen, Minuten für die Nachricht erfassen>> und diese Minuten als Freiminuten oder bezahlte Minuten speichern.

Mit einem Klick auf die bereits erstellte Nachricht wird die Konversation im Messenger geöffnet. Dort kannst du weitere Einstellungen vornehmen. Möchtest du eine neue Nachricht erstellen, klicke oben rechts auf *Neue Nachricht* (material:add[]). Anschließend wirst du zum Messenger weitergeleitet, um die Nachricht zu erstellen. Weitere Informationen findest du auf der Handbuchseite xref:crm:messenger-testphase.adoc#[Messenger (Testphase)].

[#nachricht-fluestern]
==== Nachricht flüstern

Gehe wie im Folgenden beschrieben vor, um eine Nachricht zu flüstern.

[.instruction]
Nachricht flüstern:

. Öffne das Menü *Aufträge » Aufträge (Testphase)*.
. Führe die Suche (material:search[]) aus, um Aufträge anzuzeigen.
. Öffne den Auftrag, für den du eine Nachricht flüstern möchtest.
. Klicke auf der linken Seite auf *Messenger*.
. Klicke auf *Neue Nachricht* (material:add[]). +
→ Der Messenger wird geöffnet.
. Wähle einen oder mehrere Empfänger:innen. +
*_Hinweis:_* Die ID des Auftrags ist bereits als Empfänger vorausgefüllt. Somit wird die E-Mail an die in der Rechnungsadresse gespeicherte E-Mail-Adresse gesendet.
. Gib bei Bedarf weitere Empfänger:innen ein.
. Gib einen Betreff ein.
. Gib den Text ins Textfeld ein. +
→ Mit einem Doppelklick auf das Wort stehen dir Formatierungsmöglichkeiten für deine Nachricht zur Verfügung.
. Füge optional mit einem Klick auf material:attach_file[] *Anhänge hinzufügen* eine Datei an.
. Klicke auf material:visibility_off[] *FLÜSTERN*, um die Nachricht zu flüstern.

[#nachricht-senden]
==== Nachricht senden

Gehe wie im Folgenden beschrieben vor, um eine Nachricht zu senden.

[.instruction]
Nachricht senden:

. Öffne das Menü *Aufträge » Aufträge (Testphase)*.
. Führe die Suche (material:search[]) aus, um Aufträge anzuzeigen.
. Öffne den Auftrag, für den du eine Nachricht senden möchtest.
. Klicke auf der linken Seite auf *Messenger*.
. Klicke auf *Neue Nachricht* (material:add[]). +
→ Der Messenger wird geöffnet.
. Wähle einen oder mehrere Empfänger:innen. +
*_Hinweis:_* Die ID des Auftrags ist bereits als Empfänger vorausgefüllt. Somit wird die E-Mail an die in der Rechnungsadresse gespeicherte E-Mail-Adresse gesendet.
. Gib bei Bedarf weitere Empfänger:innen ein.
. Gib einen Betreff ein.
. Gib den Text ins Textfeld ein. +
→ Mit einem Doppelklick auf das Wort stehen dir Formatierungsmöglichkeiten für deine Nachricht zur Verfügung.
. Füge optional mit einem Klick auf material:attach_file[] *Anhänge hinzufügen* eine Datei an.
. Klicke auf material:visibility_off[] *Flüster-Modus*, um den Flüster-Modus auszuschalten. +
*_Hinweis:_* Die Schaltfläche ändert sich von material:visibility_off[] *FLÜSTERN* in material:forward_to_inbox[role=skyBlue] *SENDEN*.
. Klicke auf material:forward_to_inbox[role=skyBlue] *SENDEN*, um die Nachricht zu senden.

[#nachricht-minuten-erfassen]
==== Minuten für die Nachricht erfassen

Gehe wie im Folgenden beschrieben vor, um Minuten für die Nachricht zu erfassen. Du kannst dann entscheiden, ob es sich bei diesen Minuten um Freiminuten oder bezahlte Minuten handelt.

Das Erfassen von Minuten ist nur bei geflüsterten Nachrichten möglich.

[.instruction]
Minuten für die Nachricht erfassen:

. Öffne das Menü *Aufträge » Aufträge (Testphase)*.
. Führe die Suche (material:search[]) aus, um Aufträge anzuzeigen.
. Öffne den Auftrag, für den du eine Nachricht mit erfassten Minuten erstellen möchtest.
. Klicke auf der linken Seite auf *Messenger*.
. Klicke auf *Neue Nachricht* (material:add[]). +
→ Der Messenger wird geöffnet.
. Wähle einen oder mehrere Empfänger:innen. +
*_Hinweis:_* Die ID des Auftrags ist bereits als Empfänger vorausgefüllt. Somit wird die E-Mail an die in der Rechnungsadresse gespeicherte E-Mail-Adresse gesendet.
. Gib bei Bedarf weitere Empfänger:innen ein.
. Gib einen Betreff ein.
. Gib den Text ins Textfeld ein. +
→ Mit einem Doppelklick auf das Wort stehen dir Formatierungsmöglichkeiten für deine Nachricht zur Verfügung.
. Füge optional mit einem Klick auf material:attach_file[] *Anhänge hinzufügen* eine Datei an.
. Klicke auf material:more_vert[] und aktiviere (material:toggle_on[role=skyBlue]) dann die Option *Minuten erfassen*. +
*_Hinweis:_* Die Schaltfläche ändert sich in material:visibility_off[role=skyBlue] *MINUTEN ERFASSEN*.
. Klicke auf material:visibility_off[role=skyBlue] *MINUTEN ERFASSEN*, um die Minuten für die Nachricht zu erfassen. +
→ Das Fenster *Minuten erfassen* wird geöffnet.
. Passe ggf. die Minuten an.
. Wähle (material:radio_button_checked[role=skyBlue]), ob es sich um *Freiminuten* oder *Bezahlte Minuten* handelt.
. Weise der Nachricht ggf. Tags zu.
. Klicke auf *ERFASSEN UND SPEICHERN*.

Informationen zu den verschiedenen Tabellenspalten im Bereich *Messenger* findest du in xref:crm:messenger-testphase.adoc#spalten-konfigurieren[diesem Kapitel].

[#area-order-items]
=== Bereich: Auftragspositionen

Im Bereich *Auftragspositionen* siehst du detaillierte Informationen zu den Auftragspositionen.

[[table-order-items]]
.Bereich: Auftragspositionen
[cols="1,3"]
|===
|Einstellung |Erläuterung

| *Menge*
|Zeigt die bestellte Menge der Auftragsposition an. +
Diese Spalte ist eine Standardspalte.

| *Artikel-ID*
|Zeigt die Artikel-ID der Auftragsposition an. Durch Klick auf die ID wird der Artikel geöffnet. +
Dies ist eine optionale Spalte.

| *Variantennummer*
|Zeigt die Variantennummer der Auftragsposition an. +
Dies ist eine optionale Spalte.

| *Variantenname*
|Zeigt den Variantennamen der Auftragsposition an. +
Dies ist eine optionale Spalte.

| *Varianten-ID*
|Zeigt die Varianten-ID der Auftragsposition an.  Durch Klick auf die ID wird die Variation geöffnet. +
Diese Spalte ist eine Standardspalte.

| *Artikelname*
|Zeigt den Artikelnamen der Auftragsposition an. +
Dies ist eine optionale Spalte.

| *Attribute*
|Zeigt die Attribute der Auftragsposition an. +
Diese Spalte ist eine Standardspalte.

| *Nettopreis*
|Zeigt den Nettopreis der Auftragsposition an. +
Diese Spalte ist eine Standardspalte.

| *Regulärer Nettopreis*
|Zeigt den regulären Nettopreis an.

| *Bruttopreis*
|Zeigt den Bruttopreis der Auftragsposition an. +
Diese Spalte ist eine Standardspalte.

| *Rabatt [%]*
|Zeigt den für die Auftragsposition gewährten Rabatt an. +
Diese Spalte ist eine Standardspalte.

| *Aufpreis gesamt*
|Zeigt die Summe der Aufpreise der Bestelleigenschaften der Auftragsposition an. +
Diese Spalte ist eine Standardspalte.

| *Gesamtbetrag (netto)*
|Zeigt die Nettogesamtsumme der Auftragsposition an. +
Diese Spalte ist eine Standardspalte.

| *Gesamtbetrag (brutto)*
|Zeigt die Bruttogesamtsumme der Auftragsposition an. +
Diese Spalte ist eine Standardspalte.

| *Lager*
|Zeigt das *Lager* der Auftragsposition an. +
Diese Spalte ist eine Standardspalte.

| *USt. [%]*
|Zeigt den Umsatzsteuersatz der Auftragsposition in Prozent an. +
Diese Spalte ist eine Standardspalte.

| *Externe Artikel-ID*
|Zeigt die externe *Artikel-ID* an.

| *Externe Auftragspositions-ID*
|Zeigt die vom Marktplatz übermittelte *externe Auftragspositions-ID* an.

| *Eigenschafts-ID*
|Zeigt die ID der Eigenschaft an.

| *Lagerorte*
|Zeigt den Lagerort der Auftragsposition an.

| *Gewinnspanne (netto)*
|Zeigt die Netto-Gewinnspanne an.

| *Nachbestellungs-ID*
|Zeigt die ID der Nachbestellung an.

|===

[#edit-items]
[discrete]
==== Artikel bearbeiten

Im Bereich *Auftragspositionen* hast du je nach Auftragstyp die Möglichkeit, die im Auftrag vorhandenen Artikel zu bearbeiten. Klicke dazu links auf *Artikel bearbeiten* (material:edit[]). Die folgende Tabelle listet die verfügbaren Felder, die auch hier je nach Auftragstyp variieren können.

[[table-edit-items]]
.Artikel bearbeiten
[cols="1,3"]
|===
|Einstellung |Erläuterung
2+^| *Artikel*

| *Artikel-ID*
|Zeigt die Artikel-ID an.

| *Varianten-ID*
|Zeigt die Varianten-ID an. +
Diese Spalte ist eine Standardspalte.

| *Variantennummer*
|Zeigt die Variantennummer an.

| *Artikelname*
|Zeigt den Artikelnamen an.

| *Attribute*
|Zeigt die Attribute an.

| *Variantenname*
|Zeigt den Variantennamen an.

| *Barcode*
|Zeigt den Barcode an.

| *System-EK*
|Zeigt den Einkaufspreis des Systems an.

| *Preisauswahl*
|Zeigt die Preisauswahl an.

| *Kategorierabatt*
|Der Kategorierabatt wird angezeigt.

| *Kundenklassenrabatt*
|Zeigt den Rabatt der Kundenklasse an.

| *Verfügbarkeit*
|Zeigt die Verfügbarkeit an.

| *Netto-WB*
|Zeigt den Netto-Warenbestand an.

| *Lager*
|Zeigt das Lager an.

| *Menge*
|Zeigt die Menge an.

2+^| *Warenkorb*

| *Menge*
|Zeigt die Menge der Artikel an. Passe die Menge bei Bedarf an.

| *Artikel-ID*
|Zeigt die Artikel-ID an. +
Mit Klick auf die ID wird der Artikel geöffnet.

| *Varianten-ID*
|Zeigt die Varianten-ID der Auftragsposition an. +
Mit Klick auf die ID wird die Variante geöffnet.

| *Artikel-ID* / *Varianten-ID*
|Zeigt sowohl die Artikel-ID als auch die Varianten-ID an.

| *Variantennummer*
|Zeigt die Nummer der Variante an.

| *Artikelname*
|Zeigt den Namen des Artikels an. +
Passe den Namen bei Bedarf im Eingabefeld an.

| *Attribute*
|Zeigt die Attribute an.

| *Variantenname*
|Zeigt den Namen der Variante an.

| *Barcode*
|Zeigt den Barcode an.

| *System-EK*
|Zeigt den Einkaufspreis des Systems an.

| *Preisauswahl*
|Zeigt die Preisauswahl an. Wähle bei Bedarf eine andere Preisauswahl aus der Dropdown-Liste.

| *Kategorierabatt*
|Zeigt den Rabatt der Kategorie an.

| *Kundenklassenrabatt*
|Zeigt den Rabatt der Kundenklasse an.

| *Nettopreis*
|Zeigt den Nettopreis an. +
Über material:edit[] kannst du das Datenfeld Nettopreis bearbeiten. Der Bruttopreis wird automatisch angepasst.

| *Regulärer Nettopreis*
|Zeigt den regulären Nettopreis an.

| *Bruttopreis*
|Zeigt den Bruttopreis an. +
Über material:edit[] kannst du das Datenfeld Bruttopreis bearbeiten. Der Nettopreis wird automatisch angepasst.

| *Aufpreis gesamt*
|Zeigt den Gesamtbetrag des Aufpreises an.

| *Rabatt*
|Zeigt den Rabatt an.

| *Gesamtbetrag (brutto)*
|Zeigt den Brutto-Gesamtbetrag an.

| *Lager*
|Zeigt das Lager an. Wähle bei Bedarf ein anderes Lager aus der Dropdown-Liste oder gib den Namen eines Lagers ein, um danach zu suchen.

| *USt. [%]*
|Die Umsatzsteuer wird in % angezeigt. +
Voreingestellt sind 19.00 %. Über die Dropdown-Liste kannst du den Steuersatz ändern.

| *Gewicht [g]*
|Zeigt das Gewicht des Artikels in Gramm an. +
Passe das Gewicht bei Bedarf im Eingabefeld an.

| *Länge [mm]*
|Zeigt die Länge des Artikels in mm an. +
Passe die Länge bei Bedarf im Eingabefeld an.

| *Breite [mm]*
|Zeigt die Breite des Artikels in mm an. +
Passe die Breite bei Bedarf im Eingabefeld an.

| *Aktionen*
|Stellt rechts im Kontextmenü (material:more_vert[]) weitere Aktionen für die Artikel zur Verfügung.

2+^| *Auftragspositionen löschen*

| *Löschen* (material:delete[])
|Rechts über material:delete[] kannst du eine Auftragsposition löschen.

2+^| *Kontextmenü* (material:more_vert[])

| *Verkaufspreise aktualisieren* (material:refresh[])
|Aktualisiert die Verkaufspreise.

| *Variante entfernen* (material:link_off[])
|Entfernt die zugeordnete Variante von der Auftragsposition.

| *Eigenschaften bearbeiten* (material:edit[])
|Ermöglicht das Bearbeiten der Eigenschaft. Im Bearbeitungsmodus kannst du die Felder *Name*, *Wert* und *Aufpreis* anpassen.
|===

[#order-item-properties]
[discrete]
==== Auftragspositionseigenschaften anzeigen und bearbeiten

Klicke in einer beliebigen Zeile im Bereich *Artikel bearbeiten* links auf das Pfeilsymbol (material:chevron_right[]), um die Auftragspositionseigenschaften anzuzeigen. Sind Eigenschaften für die Auftragspositionen hinterlegt, kannst du diese über das Kontextmenü (material:more_vert[]) bearbeiten (material:edit[]).

[#area-payment-terms]
=== Bereich: Zahlungsbedingungen

Im Bereich *Zahlungsbedingungen* siehst du die Informationen *Zahlungsziel*, *Skonto (%)* und *Valuta (Tage)*.

[IMPORTANT]
.Zahlungsziel angeben
======
Möchtest du Valuta und Skonto nutzen, muss ein Zahlungsziel angegeben sein. Wenn für das Zahlungsziel nichts bzw. der Wert 0 eingetragen ist, sind die Zahlungsbedingungen nicht gültig und werden nicht auf Dokumente übernommen.
======

Wenn die Werte bereits in den xref:crm:kontakt-bearbeiten.adoc#kontaktdetails[Kontaktdaten] hinterlegt sind, werden sie vom System automatisch übernommen und hier eingetragen. Die Kontaktdaten haben somit Priorität. Ist in den Kontaktdaten nichts hinterlegt, wird als nächstes überprüft, ob die Zahlungsbedingungen in einer xref:crm:vorbereitende-einstellungen.adoc#kundenklasse-erstellen[Kundenklasse] definiert sind. Falls ja, werden diese Daten übernommen und hier am Auftrag eingetragen. Sind die Werte weder in den Kontaktdaten noch in einer Kundenklasse hinterlegt, bleiben die Felder zu den Zahlungsbedingungen am Auftrag leer. +
Am Auftrag lassen sich die Zahlungsbedingungen manuell eintragen und verändern. Dies ist unabhängig davon, woher Werte übertragen wurden oder ob keine Werte übernommen wurden. +
Auf Dokumenten werden die Werte übernommen, die am dazugehörigen Auftrag hinterlegt sind. Beachte dazu auch die xref:auftraege:auftragsdokumente-neu.adoc#intable-zahlungsbedingungen-dokumente[Dokumenteneinstellungen]. Die Zahlungsbedingungen werden auf den Auftragsdokumenten xref:auftraege:rechnungen-erzeugen.adoc#[Rechnung], xref:auftraege:proformarechnung-erzeugen.adoc#[Proformarechnung], xref:auftraege:auftragsbestaetigung-erzeugen.adoc#[Auftragsbestätigung] und xref:auftraege:dokument-angebot-erzeugen.adoc#[Angebot] ausgegeben. +
*_Hinweis:_* Die Zahlungsbedingungen werden nur auf diese Dokumente übernommen, wenn es sich um einen Auftrag mit der xref:payment:kauf-auf-rechnung.adoc#[Zahlungsart Rechnung] oder der xref:payment:vorkasse.adoc#[Zahlungsart Vorkasse] handelt.

[[table-payment-terms]]
.Einstellungen im Bereich *Zahlungsbedingungen*
[cols="1,3"]
|===
|Einstellung |Erläuterung

| *Zahlungsziel*
|Zeigt das Zahlungsziel an.

| *Skonto (%)*
|Zeigt das Skonto in Prozent an.

| *Valuta (Tage)*
|Zeigt die Valuta (Wertstellung) in Tagen an.
|===

[#area-bank-data]
=== Bereich: Bankdaten

Im Bereich *Bankdaten* siehst du die Bankdaten auf einen Blick. Klicke auf *Neue Bankdaten* (material:add[]), um Daten einzugeben.

[[table-bank-data]]
.Einstellungen im Bereich *Bankdaten*
[cols="1,3"]
|===
|Einstellung |Erläuterung

| *IBAN*
|Gib die *IBAN* ein. +
Dieses Feld ist ein Pflichtfeld.

| *BIC*
|Gib die *BIC* ein. +
Dieses Feld ist ein optionales Feld.

| *Inhaber:in*
|Gib die *Inhaber:in* ein. +
Dieses Feld ist ein Pflichtfeld.

| *Kontonummer*
|Gib die *Kontonummer* ein. +
Dieses Feld ist ein optionales Feld.

| *Bankleitzahl*
|Gib die *Bankleitzahl* ein. +
Dieses Feld ist ein optionales Feld.

| *Bank*
|Gib den Namen der *Bank* ein. +
Dieses Feld ist ein optionales Feld.

| *Straße der Bank*
|Gib die *Straße der *Bank* ein. +
Dieses Feld ist ein optionales Feld.

| *PLZ und Ort der Bank*
|Gib die *PLZ und den Ort der Bank* ein. +
Dieses Feld ist ein optionales Feld.

| *Land der Bank*
|Wähle das *Land der Bank* aus der Dropdown-Liste. +
Dieses Feld ist ein optionales Feld.

| *SEPA-Lastschriftmandat*
|Aktiviere das *SEPA-Lastschriftmandat* über die Umschaltfläche icon:toggle_on[set=material, role=skyBlue]. Anschließend werden weitere Felder angezeigt. Nimm die Einstellungen entsprechend vor. Du kannst das Datum über den Kalender (material:today[]) ändern.

| *Art des Mandats*
|Wähle zwischen *SEPA-Firmen-Lastschrift* und *SEPA-Basis-Lastschrift*. +
Dieses Feld ist nur sichtbar, wenn das SEPA-Lastschriftmandat aktiviert wurde.

| *Ausführungsmodalität*
|Wähle zwischen *Einmalige Zahlung* und *Wiederkehrende Zahlung*. +
Dieses Feld ist nur sichtbar, wenn das SEPA-Lastschriftmandat aktiviert wurde.

|===

[#area-assigned-payments]
=== Bereich: Zugeordnete Zahlungen

Im Bereich *Zugeordnete Zahlungen* siehst du alle Informationen zu den Zahlungen, die dem Auftrag zugeordnet sind. Du kannst sowohl die Spalten konfigurieren (material:settings[]) als auch neue Zahlungen erstellen (material:add[]).

[[table-assigned-payments]]
.Einstellungen im Bereich *Zugeordnete Zahlungen*
[cols="1,3"]
|===
|Einstellung |Erläuterung

| *Gesamtbetrag Auftrag*
|Zeigt den Gesamtbetrag des Auftrags an.

| *Bezahlt*
|Zeigt den bezahlten Betrag an.

| *Offen*
|Zeigt den offenen Betrag an.
|===

[[table-assigned-payments-available-columns]]
.Verfügbare Spalten für zugeordnete Zahlungen
[cols="1,3"]
|===
|Einstellung |Erläuterung

| *Zahlungs-ID*
|Zeigt die ID der Zahlung an.

| *Eltern-ID*
|Zeigt die übergeordnete ID an.

| *Auftrags-ID*
|Zeigt die ID des Auftrags an.

| *Kunden-ID*
|Zeigt die ID der Kund:in an.

| *Zahlungsart*
|Zeigt die Zahlungsart an.

| *Soll/Haben*
|Zeigt das Soll/Haben an.

| *Betrag*
|Zeigt den Betrag an.

| *Status*
|Zeigt den Status an.

| *Verwendungszweck*
|Zeigt den Verwendungszweck an.

| *Absender der Zahlung*
|Zeigt den Absender der Zahlung an.

| *Eingangsdatum*
|Zeigt das Eingangsdatum der Zahlung an.

| *Importiert*
|Zeigt das Datum und die Uhrzeit des Imports der Zahlung an.

|===

//Einstellungen für Zahlung buchen hier hinzufügen

[#area-order-references]
=== Bereich: Auftragsreferenzen

Im Bereich *Auftragsreferenzen* siehst du die mit dem Auftrag verbundenen Informationen. Über *Spalten konfigurieren* (material:settings[]) kannst du die Spalten beliebig anpassen.

[TIP]
Wähle im Bearbeitungsmodus, ob es sich bei der Währung um die *Systemwährung* oder die *Auftragswährung* handelt.

[[table-order-references]]
.Einstellungen im Bereich *Auftragsreferenzen*
[cols="1,3"]
|===
|Einstellung |Erläuterung

| *Beziehung*
|Zeigt die Beziehung zu diesem Auftrag an. In dieser Spalte werden nicht nur die direkten Eltern- und Kindaufträge, sondern alle verknüpften Aufträge angezeigt. Letztere haben die Kennzeichnung _Andere_.

| *ID*
|Zeigt die ID des Auftrags an.

| *Typ*
|Zeigt den Auftragstyp an.

| *Dokument*
|Zeigt die Nummer des Hauptdokuments an.

| *Status*
|Zeigt den Status der Bearbeitung an.

| *Erstellt*
|Zeigt das Erstellungsdatum an.

| *Betrag*
|Zeigt den Betrag an.

| *Zahlungsart*
|Zeigt die gewählte Zahlungsart an.

| *Rechnungsadresse*
|Zeigt die Rechnungsadresse an. Die im Datensatz des Kontakts hinterlegte Rechnungsadresse wird übernommen. Sind mehrere Rechnungsadressen hinterlegt, wird die als primär definierte Rechnungsadresse übernommen.

| *Lieferadresse*
|Zeigt die Lieferadresse an. Wenn du die Option *Wie Rechnung* gewählt hast, wird die unter *Rechnungsadresse* eingegebene Adresse auch als Lieferadresse übernommen. Ansonsten wird die im Datensatz des Kontakts hinterlegte Lieferadresse übernommen.
|===

[#area-properties]
=== Bereich Eigenschaften

Im Bereich *Eigenschaften* siehst du Eigenschaften der Auftragspositionen. Über *Spalten konfigurieren* (material:settings[]) kannst du die Spalten beliebig konfigurieren.

[[table-properties]]
.Einstellungen im Bereich *Eigenschaften*
[cols="1,3"]
|===
|Einstellung |Erläuterung

| *Typ-ID*
|Zeigt die ID des Typs an.

| *Name*
|Zeigt den Namen der Auftragseigenschaft an.

| *Wert*
|Zeigt den Wert der Auftragseigenschaft an.

| *Erstellungsdatum*
|Zeigt das Erstellungsdatum sowie die Uhrzeit an.

| *Letzte Änderung*
|Zeigt das Datum der letzten Änderung sowie die Uhrzeit an.
|===

[#area-documents]
=== Bereich: Dokumente

Im Bereich *Dokumente* siehst du alle vorhandenen sowie archivierten Dokumente deiner Aufträge. Du kannst die Spalten konfigurieren (material:settings[]), neue Dokumente erstellen (material:add[]) und externe Dokumente hochladen (material:file_upload[]).

[[table-documents]]
.Einstellungen im Bereich *Dokumente*
[cols="1,3"]
|===
|Einstellung |Erläuterung

| *Alle Dokumente*
|Zeigt alle vorhandenen Dokumente an. Je nach Auftragstyp sind verschiedene Dokumente verfügbar.

| *Archivierte Dokumente*
|Zeigt alle archivierten Dokumente an. Je nach Auftragstyp sind verschiedene Dokumente verfügbar.

| *Name*
|Zeigt den Namen des Dokuments an.

| *Nummer*
|Zeigt die Nummer des Dokuments an.

| *Typ*
|Zeigt den Typ des Dokuments an.

| *Referenz*
|Zeigt die Referenz an.

| *Lager*
|Zeigt das Lager an.

| *Eigner*
|Zeigt den Eigner an.

| *Letzte Änderung*
|Zeigt das Datum der letzten Änderung an.

| *Anzeigedatum*
|Zeigt das Datum an, das auf dem Dokument ausgewiesen wird.

| *Aktionen*
|Ermöglicht das *Archivieren* und *Herunterladen* des Dokuments über das Kontextmenü (material:more_vert[]).
|===

[NOTE]
.Gutschein-Dokumente
======
Hast du verkaufte Gutscheine oder Vouchers, werden diese ebenfalls in den Dokumenten angezeigt. Bei Dokumenten vom Typ *Gutschein* handelt es sich also nicht um Gutscheine, die im Auftrag eingelöst wurden, sondern um Gutscheine, die mit diesem Auftrag verkauft wurden. Über das Kontextmenü (material:more_vert[]) kann ein Gutschein mit Klick auf *Neu erzeugen* (material:restore_page[]) neu erzeugt werden.
======

[#area-history]
=== Bereich: Historie

Im Bereich *Historie* siehst du eine Übersicht der getätigten Aktionen mit dem jeweiligen Status und dem Datum. Du kannst die Spalten beliebig konfigurieren (material:settings[]).

[[table-history]]
.Einstellungen im Bereich *Historie*
[cols="1,3"]
|===
|Einstellung |Erläuterung

| *Datum*
|Zeigt das Datum und die Uhrzeit an.

| *Benutzer*
|Zeigt die Benutzer:in an.

| *Aktion*
|Zeigt die durchgeführte Aktion an.

| *Status*
|Zeigt den aktuellen Status an.

|===

[#area-notes]
=== Bereich: Notizen

Im Bereich *Notizen* kannst du interne Auftragsnotizen sowie Notizen von Kund:innen mit dem Erstelldatum und dem Zeitstempel einsehen. Die aktuellste Notiz wird jeweils oben angezeigt. Füge außerdem weitere Notizen hinzu (material:add[]) und bearbeite oder lösche interne Notizen über das Kontextmenü (material:more_vert[]). Notizen, die von Kund:innen stammen, können allerdings nicht bearbeitet, sondern nur gelöscht werden. Handelt es sich um Wünsche von Kund:innen, werden diese automatisch mit einem Tag versehen.

[#splitting-orders]
== Aufträge teilen

Die Funktion zum Teilen von Aufträgen findest du in der Toolbar eines geöffneten Auftrags im Menü *Aufträge » Aufträge (Testphase)*. Das Verhalten beim Teilen ist abhängig von deiner xref:auftraege:preparatory-settings.adoc#intable-behaviour-after-splitting[Grundeinstellung] dafür. +
Im Standardverhalten werden beim Teilen eines Auftrags 2 neue Aufträge erstellt. Der ursprüngliche Auftrag wird gelöscht. Für die neuen Aufträge werden jeweils die Versandkosten neu ermittelt. Bevor der Auftrag geteilt wird, erfolgt eine Abfrage zur Verteilung der Auftragspositionen. +
Ein Auftrag kann geteilt werden, wenn: +

* er nicht gesperrt ist, +
* noch kein Warenausgang gebucht wurde, +
* keine Kindaufträge erzeugt wurden (z.B. eine Retoure oder Lieferaufträge), +
* keine steuerrelevanten Dokumente am Auftrag hängen und +
* dem Auftrag noch keine Zahlung zugeordnet wurde. +

Hast du die andere Option *Statuswechsel* gewählt, entstehen ebenfalls 2 neue Aufträge, aber der Originalauftrag bleibt erhalten und wird in einen von dir definierten Auftragsstatus verschoben. Ein weiterer Unterschied ist, dass mit dieser Einstellung auch Aufträge geteilt werden dürfen, denen bereits eine Zahlung zugeordnet wurde oder für die steuerrelevante Dokumente (Wichtig: Rechnung und Stornobeleg) erstellt wurden. Sowohl die zugeordnete Zahlung als auch die Dokumente bleiben für den Originalauftrag erhalten und werden nicht in die aufgeteilten Aufträge übernommen. +
Möchtest du ein anderes xref:auftraege:preparatory-settings.adoc#intable-splitting-behaviour-shipping-costs[Verhalten der Versandkosten] als den oben beschriebenen Standard, kannst du dieses in den Grundeinstellungen für Aufträge auswählen.

[#redeem-coupon]
== Gutscheine einlösen

Du hast bereits einen Auftrag angelegt und möchtest im Nachhinein noch Gutschein-Codes hinzufügen? Mit der Funktion *Gutschein einlösen* ist dies für Aufträge und Vorbestellungen problemlos möglich. Je nachdem, ob es sich um eine plentymarkets Kampagne oder eine externe Kampagne handelt, sind unterschiedliche Einstellungen verfügbar. Um einen Gutschein einzulösen, gehe vor wie folgt.

[.instruction]
Gutscheine einlösen:

. Öffne das Menü *Aufträge » Aufträge (Testphase)*. +
→ Die Auftragsübersicht wird geöffnet.
. Führe die Suche aus oder nutze Filter, um Aufträge anzuzeigen.
. Klicke in die Zeile eines Auftrags, um den Auftrag zu öffnen.
. Klicke oben auf *Gutschein einlösen* (material:redeem[]). +
→ Das Fenster *Gutschein einlösen* wird geöffnet.
. Wähle zunächst, ob es sich um eine plentymarkets Kampagne oder eine externe Kampagne handelt.
. Nimm die weiteren Einstellungen vor. Beachte dazu die Erläuterungen in <<table-redeem-coupon>>.
. Klicke auf *Einlösen*. +
→ Der Gutschein wird eingelöst.

[[table-redeem-coupon]]
.Gutscheine einlösen
[cols="1,3"]
|===
|*Einstellung* |*Erläuterung*

2+^| *plentymarkets Kampagne*

|*Code*
|Gib den Gutschein-Code ein und klicke auf *Validieren*. Anschließend werden weitere Felder sichtbar, die allerdings nicht bearbeitet werden können.

|*Typ*
|Der Typ des Gutscheins wird angezeigt. Dieses Feld kann nicht bearbeitet werden.

|*Wert in €*
|Der Wert des Gutscheins wird in € angezeigt. Dieses Feld kann nicht bearbeitet werden.

2+^| *Externe Kampagne*

|*Code*
|Gib den Gutschein-Code ein.

|*Typ*
|Wähle den Typ des Gutscheins.

|*Wert in €*
|Gib den Wert des Gutscheins in € ein.

|===

[#checklist-sales-prices]
== Checkliste für Verkaufspreise

Nutze diese Checkliste, wenn du in einem Auftrag etwas an den Artikelpositionen ändern möchtest und auf Probleme stößt. In vielen Fällen liegt es daran, dass die Einstellungen für die Verkaufspreise nicht zu den Parametern des Auftrags passen.

Überprüfe daher, ob folgende Einstellungen für den entsprechenden Preis im Menü *Einrichtung » Artikel » Verkaufspreise* gesetzt sind:

[%interactive]

* [ ] Für *Ab Menge* ist *1* gesetzt.
* [ ] Die *Währung* des Auftrages ist für den Preis freigeschaltet.
* [ ] Dem Preis ist kein *Preistyp* zugeordnet, d.h. weder UVP, noch Aktionspreis oder Setpreis sind ausgewählt.
* [ ] Der *Mandant* des Auftrages ist aktiviert.
* [ ] Die entsprechende *Kundenklasse* ist aktiviert, wenn sie im System eingerichtet sind.
* [ ] Das *Land*, aus dem der Auftrag kommt, ist aktiviert.
* [ ] In den *Herkünften* ist *Manuelle Eingabe* aktiviert.
* [ ] Die entsprechende *Herkunft* des Auftrages ist aktiviert.

Konntest du diese Punkte abhaken, solltest du Änderungen an den Artikelpositionen vornehmen können. Falls du immer noch auf Schwierigkeiten stößt, findest du ausführlichere Informationen zu Verkaufspreisen auf der Handbuchseite xref:artikel:preise.adoc#[Verkaufspreise und Preiskalkulation]. Kontaktiere ansonsten unsere Supporter im link:https://forum.plentymarkets.com/[Forum].

[discrete]
== Rechte für Preise für Backend-Benutzer:innen vergeben

:rights-purpose: Preise sehen und bearbeiten können
:right-one: pass:quotes[*Artikel > Artikel > Variante > Preis > Anzeigen*]
:right-two: pass:quotes[*Artikel > Artikel > Variante > Preis > Aktualisieren*]
:right-three: pass:quotes[*Aufträge > Auftragsposition > Deckungsbeitrag > Anzeigen*]

include::_includes:partial$rights.adoc[]
