= Mit Aufträgen arbeiten

:keywords: Auftragsanlage, Aufträge anlegen, Gruppenfunktionen für Aufträge
:author: team-order-core

//menü artikel bearbeiten (im bereich auftragspositionen) hinzufügen

Aufträge bilden deine Verkäufe sowie damit einhergehende und übliche Geschäftsvorfälle ab. Mithilfe von xref:auftraege:order-types.adoc#[Auftragstypen] werden die unterschiedlichen Geschäftsvorfälle kenntlich gemacht. Fortschritte bei der Bearbeitung eines Auftrags werden durch xref:auftraege:order-statuses.adoc#1200[Auftragsstatus] angezeigt. Welche Möglichkeiten dir Auftragstypen und Auftragsstatus bieten und wie du Aufträge abwickelst, erfährst du in den folgenden Beschreibungen. Alle Aufträge werden zentral und in einem einheitlichen Format erfasst. Bereits in der xref:auftraege:auftraege-verwalten.adoc#1400[Auftragsübersicht] siehst du wichtige Informationen auf einen Blick und kannst einige Arbeiten direkt ausführen.

[#basic-info-create-orders]
== Allgemeines zur Auftragsanlage in plentymarkets

In plentymarkets wird ein Auftrag automatisch angelegt, wenn Kund:innen Bestellungen in deinem Webshop oder auf einem angebundenen Marktplatz tätigen. Unterschiedliche Geschäftsvorfälle wie xref:auftraege:auftraege-verwalten.adoc#300[Lieferaufträge], xref:auftraege:auftraege-verwalten.adoc#400[Retouren], xref:auftraege:auftraege-verwalten.adoc#500[Gutschriften], xref:auftraege:auftraege-verwalten.adoc#600[Gewährleistungen] und xref:auftraege:auftraege-verwalten.adoc#700[Reparaturen] werden mithilfe eigener Aufträge verschiedener Typen abgebildet, die immer mit dem Hauptauftrag verbunden sind. Über die xref:auftraege:auftraege-verwalten.adoc#1400[Auftragsübersicht] lassen sich Aufträge ungeachtet der xref:auftraege:auftragsherkunft.adoc#[Auftragsherkunft] öffnen und bearbeiten. Für viele Auftragstypen, wie zum Beispiel xref:auftraege:auftraege-verwalten.adoc#300[Lieferaufträge], ist das Einrichten von xref:automatisierung:ereignisaktionen.adoc#[Ereignisaktionen] sinnvoll, um Vorgänge zu automatisieren. Einige Beispiele für die Nutzung von Ereignisaktionen für die Auftragsabwicklung werden in den folgenden Kapiteln erläutert. +
Aufträge, die nicht über den Webshop oder einen Marktplatz bei dir eingehen, legst du xref:auftraege:auftraege-verwalten.adoc#200[manuell] im System an. Das ist beispielsweise bei telefonischen oder E-Mail-Bestellungen sowie bei Barverkäufen der Fall.

Passe die xref:auftraege:grundeinstellungen.adoc#[Grundeinstellungen] im Menü *Einrichtung » Aufträge » Einstellungen* an, bevor du die ersten Aufträge in deinem plentymarkets System abwickelst. Speichere die Grundeinstellungen auch dann einmalig ab, wenn du die voreingestellten Werte nicht verändert hast.


[#order-group-functions]
== Gruppenfunktionen nutzen

Nutze die Gruppenfunktionen, um für mehrere Aufträge gleichzeitig eine Aktion auszuführen. Für Aufträge stehen dir die folgenden Gruppenfunktionen zur Verfügung.

[[table-order-group-functions]]
.Gruppenfunktionen für Aufträge
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Aufträge gruppieren*
|Gruppiert die gewählten Aufträge.

| *Status ändern*
|Ändert den Status für die gewählten Aufträge. Wähle einen Status aus der Dropdown-Liste.

| *Tag ändern*
|Ändert das Tag für die gewählten Aufträge. Du kannst sowohl Tags hinzufügen als auch Tags entfernen. Wähle die gewünschten Tags aus der Dropdown-Liste.

| *Warenausgang buchen*
|Bucht den Warenausgang für alle gewählten Aufträge. Wähle ein Datum für den Warenausgang.

| *Aufträge löschen*
|Löscht alle gewählten Aufträge. +
Beachte, dass Aufträge aufgrund von bestimmten Einstellungen eventuell nicht gelöscht werden können.
//ergänzen, in welchen Fällen dies der Fall ist

2+^| Kontextmenü (material:more_vert[])
| *Warenausgang zurückbuchen*
|Bucht den Warenausgang von allen gewählten aufträgen zurück.

| *Eigner ändern*
|Ändert den Eigner für alle gewählten Aufträge. Wähle einen Eigner aus der Dropdown-Liste.

| *Versandprofil ändern*
|Ändert das Versandprofil für alle gewählten Aufträge. Wähle ein Versandprofil aus der Dropdown-Liste.

| *Lieferdatum für Auftrag setzen*
|Setzt ein Lieferdatum für alle gewählten Aufträge. Gib ein Lieferdatum ein oder wähle ein Datum über den Kalender (material:today[]).

| *Versanddatum für Auftragsposition setzen*
|Setzt ein Versanddatum für die Auftragsposition aller gewählten Aufträge. Gib ein Versanddatum ein oder wähle ein Datum über den Kalender (material:today[]).
|====

== Weitere Funktionen in der Auftragsübersicht nutzen

Rechts in der Auftragsübersicht sind je nach Auftragstyp weitere Funktionen über das Kontextmenü (material:more_vert[]) verfügbar. Darüber kannst du beispielsweise Dokumente anlegen oder Zahlungen buchen.

[[table-context-menu-functions]]
.Weitere Funktionen für Aufträge
[cols="1,3"]
|===

|Einstellung |Erläuterung

| *Dokument erstellen*
|Ermöglicht das Erstellen von Dokumenten. Je nach Auftragstyp sind verschiedene Dokumente verfügbar.

| *Warenausgang buchen*
|Bucht den Warenausgang.

//was bedeutet referenziert? Damit verknüpft?
| *Referenzierte Bestellungen anzeigen*
|Zeigt die vorhandenen Bestellungen an.

| *Zahlung buchen*
|Ermöglicht das Buchen einer Zahlung.

| *Auftrag löschen*
|Ermöglicht das Löschen eines Auftrags. Beachte, dass nicht alle Aufträge gelöscht werden können
//wann können Aufträge nicht gelöscht werden? Wenn sie gesperrt sind...wann noch?

|===


//Alle Bereiche hier aufführen


//evtl. zu kapitel zur toolbar hinzufügen?
[#redeem-coupon]
== Gutscheine einlösen

Du hast bereits einen Auftrag angelegt und möchtest im Nachhinein noch Gutschein-Codes hinzufügen? Mit der Funktion *Gutschein einlösen* ist dies für Aufträge und Vorbestellungen problemlos möglich. Je nachdem, ob es sich um eine plentymarkets Kampagne oder eine externe Kampagne handelt, sind unterschiedliche Einstellungen verfügbar. Um einen Gutschein einzulösen, gehe vor wie folgt.

[.instruction]
Gutscheine einlösen:

. Öffne das Menü *Aufträge » Aufträge (Testphase)*. +
→ Die Auftragsübersicht wird geöffnet.
. Führe die Suche aus oder nutze Filter, um Aufträge anzuzeigen.
. Klicke in die Zeile eines Auftrags, um den Auftrag zu öffnen.
. Klicke oben auf *Gutschein einlösen* (material:redeem[]). +
→ Das Fenster *Gutschein einlösen* wird geöffnet.
. Wähle zunächst, ob es sich um eine plentymarkets Kampagne oder eine externe Kampagne handelt.
. Nimm die weiteren Einstellungen vor. Beachte dazu die Erläuterungen in <<table-redeem-coupon>>.
. Klicke auf *Einlösen*. +
→ Der Gutschein wird eingelöst.

[[table-redeem-coupon]]
.Gutscheine einlösen
[cols=”1,3”]
|===
|*Einstellung* |*Erläuterung*

2+^| *plentymarkets Kampagne*

|*Code*
|Gib den Gutschein-Code ein und klicke auf *Validieren*. Anschließend werden weitere Felder sichtbar, die allerdings nicht bearbeitet werden können.

|*Typ*
|Der Typ des Gutscheins wird angezeigt. Dieses Feld kann nicht bearbeitet werden.

|*Wert in €*
|Der Wert des Gutscheins wird in € angezeigt. Dieses Feld kann nicht bearbeitet werden.

2+^| *Externe Kampagne*

|*Code*
|Gib den Gutschein-Code ein.

|*Typ*
|Wähle den Typ des Gutscheins.

|*Wert in €*
|Gib den Wert des Gutscheins in € ein.

|===








[#checklist-sales-prices]
== Checkliste für Verkaufspreise

Nutze diese Checkliste, wenn du in einem Auftrag etwas an den Artikelpositionen ändern möchtest und auf Probleme stößt. In vielen Fällen liegt es daran, dass die Einstellungen für die Verkaufspreise nicht zu den Parametern des Auftrages passen.

Überprüfe daher, ob folgende Einstellungen für den entsprechenden Preis im Menü *Einrichtung » Artikel » Verkaufspreise* gesetzt sind:

[%interactive]

* [ ] Für *Ab Menge* ist *1* gesetzt.
* [ ] Die *Währung* des Auftrages ist für den Preis freigeschaltet.
* [ ] Dem Preis ist kein *Preistyp* zugeordnet, d.h. weder UVP, noch Aktionspreis oder Setpreis sind ausgewählt.
* [ ] Der *Mandant* des Auftrages ist aktiviert.
* [ ] Die entsprechende *Kundenklasse* ist aktiviert, wenn sie im System eingerichtet sind.
* [ ] Das *Land*, aus dem der Auftrag kommt, ist aktiviert.
* [ ] In den *Herkünften* ist *Manuelle Eingabe* aktiviert.
* [ ] Die entsprechende *Herkunft* des Auftrages ist aktiviert.

Konntest du diese Punkte abhaken, solltest du Änderungen an den Artikelpositionen vornehmen können. Falls du immer noch auf Schwierigkeiten stößt, findest du ausführlichere Informationen zu Verkaufspreisen auf der Handbuchseite xref:artikel:preise.adoc#[Verkaufspreise und Preiskalkulation]. Kontaktiere ansonsten unsere Supporter im link:https://forum.plentymarkets.com/[Forum].
