= Mit Aufträgen arbeiten

:keywords: Auftragsanlage,
:author: team-order-core

Aufträge bilden deine Verkäufe sowie damit einhergehende und übliche Geschäftsvorfälle ab. Mithilfe von xref:auftraege:order-types.adoc#[Auftragstypen] werden die unterschiedlichen Geschäftsvorfälle kenntlich gemacht. Fortschritte bei der Bearbeitung eines Auftrags werden durch xref:auftraege:order-statuses.adoc#1200[Auftragsstatus] angezeigt. Welche Möglichkeiten dir Auftragstypen und Auftragsstatus bieten und wie du Aufträge abwickelst, erfährst du in den folgenden Beschreibungen. Alle Aufträge werden zentral und in einem einheitlichen Format erfasst. Bereits in der xref:auftraege:auftraege-verwalten.adoc#1400[Auftragsübersicht] siehst du wichtige Informationen auf einen Blick und kannst einige Arbeiten direkt ausführen.

[#basic-info-create-orders]
== Allgemeines zur Auftragsanlage in plentymarkets

In plentymarkets wird ein Auftrag automatisch angelegt, wenn Kund:innen Bestellungen in deinem Webshop oder auf einem angebundenen Marktplatz tätigen. Unterschiedliche Geschäftsvorfälle wie xref:auftraege:auftraege-verwalten.adoc#300[Lieferaufträge], xref:auftraege:auftraege-verwalten.adoc#400[Retouren], xref:auftraege:auftraege-verwalten.adoc#500[Gutschriften], xref:auftraege:auftraege-verwalten.adoc#600[Gewährleistungen] und xref:auftraege:auftraege-verwalten.adoc#700[Reparaturen] werden mithilfe eigener Aufträge verschiedener Typen abgebildet, die immer mit dem Hauptauftrag verbunden sind. Über die xref:auftraege:auftraege-verwalten.adoc#1400[Auftragsübersicht] lassen sich Aufträge ungeachtet der xref:auftraege:auftragsherkunft.adoc#[Auftragsherkunft] öffnen und bearbeiten. Für viele Auftragstypen, wie zum Beispiel xref:auftraege:auftraege-verwalten.adoc#300[Lieferaufträge], ist das Einrichten von xref:automatisierung:ereignisaktionen.adoc#[Ereignisaktionen] sinnvoll, um Vorgänge zu automatisieren. Einige Beispiele für die Nutzung von Ereignisaktionen für die Auftragsabwicklung werden in den folgenden Kapiteln erläutert. +
Aufträge, die nicht über den Webshop oder einen Marktplatz bei dir eingehen, legst du xref:auftraege:auftraege-verwalten.adoc#200[manuell] im System an. Das ist beispielsweise bei telefonischen oder E-Mail-Bestellungen sowie bei Barverkäufen der Fall.

Passe die xref:auftraege:grundeinstellungen.adoc#[Grundeinstellungen] im Menü *Einrichtung » Aufträge » Einstellungen* an, bevor du die ersten Aufträge in deinem plentymarkets System abwickelst. Speichere die Grundeinstellungen auch dann einmalig ab, wenn du die voreingestellten Werte nicht verändert hast.

[#manually-create-orders]
== Aufträge manuell anlegen

Du kannst Aufträge manuell im System anlegen, z.B. wenn eine Bestellung per Telefon getätigt wird. Es gibt verschiedene Möglichkeiten, die du dafür nutzen kannst:

* In der xref:auftraege:auftraege-verwalten.adoc#240[Kontaktübersicht]
* In den xref:auftraege:auftraege-verwalten.adoc#210[Kontaktdaten]
* In einem bestehenden xref:auftraege:auftraege-verwalten.adoc#220[Auftrag]
* Über einen xref:auftraege:auftraege-verwalten.adoc#230[Barverkauf]

Diese verschiedenen Vorgehensweisen werden nachfolgend beschrieben.

[IMPORTANT]
.E-Mail-Versand
====
Bei manuell angelegten Aufträgen wird keine automatische E-Mail, z.B. als Auftragsbestätigung, an Kund:innen versendet. Grund dafür ist, dass das System nicht wissen kann, wann alle Einstellungen zu diesem Auftrag vorgenommen wurden. Stoße daher den Versand einer E-Mail-Vorlage manuell im Auftrag im Bereich xref:auftraege:working-with-orders.adoc#available-areas[E-Mail-Service] an.
====




[#order-group-functions]
== Gruppenfunktionen nutzen

Nutze die Gruppenfunktionen, um für mehrere Aufträge gleichzeitig eine Aktion auszuführen. Für Aufträge stehen dir die folgenden Gruppenfunktionen zur Verfügung.

[[table-order-group-functions]]
.Gruppenfunktionen für Aufträge
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Aufträge gruppieren*
|Gruppiert die gewählten Aufträge.

| *Status ändern*
|Ändert den Status für die gewählten Aufträge. Wähle einen Status aus der Dropdown-Liste.

| *Tag ändern*
|Ändert das Tag für die gewählten Aufträge. Du kannst sowohl Tags hinzufügen als auch Tags entfernen. Wähle die gewünschten Tags aus der Dropdown-Liste.

| *Warenausgang buchen*
|Bucht den Warenausgang für alle gewählten Aufträge. Wähle ein Datum für den Warenausgang.

| *Aufträge löschen*
|Löscht alle gewählten Aufträge. +
Beachte, dass Aufträge aufgrund von bestimmten Einstellungen eventuell nicht gelöscht werden können.
//ergänzen, in welchen Fällen dies der Fall ist

2+[]| Kontextmenü (material:more_vert[])
| *Warenausgang zurückbuchen*
|Bucht den Warenausgang von allen gewählten aufträgen zurück.

| *Eigner ändern*
|Ändert den Eigner für alle gewählten Aufträge. Wähle einen Eigner aus der Dropdown-Liste.

| *Versandprofil ändern*
|Ändert das Versandprofil für alle gewählten Aufträge. Wähle ein Versandprofil aus der Dropdown-Liste.

| *Lieferdatum für Auftrag setzen*
|Setzt ein Lieferdatum für alle gewählten Aufträge. Gib ein Lieferdatum ein oder wähle ein Datum über den Kalender (material:today[]).

| *Versanddatum für Auftragsposition setzen*
|Setzt ein Versanddatum für die Auftragsposition aller gewählten Aufträge. Gib ein Versanddatum ein oder wähle ein Datum über den Kalender (material:today[]).
|====
//Alle Bereiche hier aufführen


[#redeem-coupon]
