= Automatisierung
:author: team-docs-automation
:description: Erfahre, wie du deine täglichen Aufgaben mithilfe des Aktionsmanagers oder anhand von Ereignisaktionen und Prozessen automatisierst.

Automatisiere deine täglichen Aufgaben! plentymarkets beinhaltet drei verschiedene Tools, um deine routine Geschäftsprozesse zu automatisieren.

Wir stellen die drei Tools spielerisch vor:

.Automatisiere deine Arbeitsabläufe
video::197506169[vimeo]

== Aktionsmanager

In plentymarkets lässt du tägliche Ereignisse automatisch über den xref:automatisierung:aktionsmanager.adoc#[Aktionsmanager] zu bestimmten Uhrzeiten ausführen.

So kannst du den xref:automatisierung:best-practices-automatisierung.adoc#_praxisbeispiele_aktionsmanager[Aktionsmanager beispielsweise nutzen], um einen täglichen Zeitpunkt festzulegen, zu dem nicht zahlende Kund:innen von eBay oder deinem eigenen Webshop eine Zahlungserinnerung oder eine Mahnung erhalten sollen und diese automatisch per E-Mail versenden lassen.

== Ereignisaktionen

Das Grundprinzip von xref:automatisierung:ereignisaktionen.adoc#[Ereignisaktionen] ist leicht verständlich: Bestimmte *_Ereignisse_* im Webshop lösen bestimmte *_Aktionen_* aus.

So kannst du xref:automatisierung:best-practices-automatisierung.adoc#_praxisbeispiele_ereignisaktionen[Ereignisaktionen beispielsweise nutzen], um E-Mails an deine Kund:innen zu versenden. Mit den Ereignisaktionen stellt dir plentymarkets ein effektives Werkzeug zur Verfügung, mit dem du solche Automatismen einstellen und zuverlässig durch das System ausführen lassen kannst.

== Prozesse

Über Prozesse automatisierst du komplexe Arbeitsabläufe in plentymarkets.

So kannst du xref:automatisierung:best-practices.adoc#[Prozesse beispielsweise nutzen], um Artikel im Lager zu kommissionieren.
