= DocumentBuilder (Testphase)

:keywords: Dokumentenvorlage, Dokumentvorlage, Template, Dokumente, Vorlagen
:description:
:author: team-automation-docs

Es ist an der Zeit, eine Rechnung zu erstellen oder eine Retoure vorzubereiten? Und damit das in Zukunft noch schneller geht, möchtest du dafür eine Dokumentenvorlage erstellen, die genau auf deine Bedürfnisse zugeschnitten ist? Dann ist der DocumentBuilder genau das richtige Tool für dich. Mithilfe des DocumentBuilders im Menü *Einrichtung » Dokumente » DocumentBuilder* kannst du deine Dokumentenvorlagen im Handumdrehen erstellen und zentral an einer Stelle verwalten. Somit hast du all deine Vorlagen an einem Ort und zu jeder Zeit griffbereit.

Auf dieser Seite lernst du, wie du bereits erstellte Vorlagen suchst oder neue Vorlagen erstellst. Außerdem findest du Informationen dazu, wie du Vorlagen (de)aktivierst, bearbeitest, kopierst und verschiebst.

[NOTE]
.Testphase
Der DocumentBuilder befindet sich zurzeit in der Testphase, was bedeutet, dass wir dir das Menü nun zum Kennenlernen und Ausprobieren zur Verfügung stellen. In der nächsten Zeit werden wir weiter an der Performance arbeiten und weitere Anpassungen vornehmen.

[#vorbereitende-einstellungen]
== Vorbereitende Einstellungen vornehmen

Sind Einstellungen in anderen Menüs notwendig?
Nummernkreise müssen eingestellt sein

[#benuterrechte-vergeben]
=== Rechte für Backendbenutzer:innen vergeben

Welche Rechte benötigt man?
Rechte werden noch festgelegt


Die Übersicht des DocumentBuilders liefert alle relevanten Informationen auf einen Blick. Hier kannst du beispielsweise sehen, welche Vorlage aktuell aktiviert ist und welche Vorlage als Standardvorlage verwendet wird. Über das Kontextmenü (material:more_vert[]) rechts kannst du jeweils weitere Aktionen für eine Vorlage ausführen.

[#spalten-konfigurieren]
== Spalten in der Übersicht konfigurieren

In der Übersicht kannst du selbst entscheiden, welche Spalten in der Tabelle sichtbar sein sollen und in welcher Reihenfolge diese angezeigt werden. Um die Spalten zu konfigurieren, gehe vor wie folgt.

[.instruction]
Spalten konfigurieren:

. Öffne das Menü *Einrichtung » Dokumente » DocumentBuilder*.
. Klicke oben rechts auf *Spalten konfigurieren* (material:settings[]). +
→ Das Fenster *Spalten konfigurieren* wird geöffnet.
. Wähle die Spalten, die angezeigt werden sollen (material:done[]). Beachte dazu die Erläuterungen in <<table-document-builder-columns>>.
. Ziehe (material:drag_indicator[]) die Spalten per Drag-and-drop an die gewünschte Stelle, bis sie in der für dich richtigen Reihenfolge angezeigt werden.
. Füge bei Bedarf Spalten hinzu oder wähle Spalten ab, wenn du sie nicht benötigst.
. Klicke auf *Bestätigen*. +
→ Die Einstellungen werden gespeichert.

[[table-order-status-columns]]
.Spalten in der Statusübersicht
[cols="1,3"]
|===
|Spalte |Erläuterung

| *Aktiv*
|Zeigt an, ob die Vorlage aktiv (blauer Punkt) oder inaktiv (grauer Punkt) ist. +
*_Hinweis:_* Ist eine Vorlage aktiv, wird sie zum Generieren von Dokumenten verwendet. Ist eine Vorlage hingegen inaktiv, hat diese keine Funktion.

| *Name der Vorlage*
|Zeigt den Namen der Vorlage an.

| *Dokumenttyp*
|Zeigt den Typ des Dokuments an.

| *Standardvorlage*
|Zeigt an, ob es sich um eine Standardvorlage handelt. Ist dies der Fall, wird ein Häkchen angezeigt. +
*_Hinweis:_* Standardvorlagen können nicht gelöscht werden.

| *Dateiname*
|Zeigt den Dateinamen an.

| *Tags*
|Zeigt die Tags der Vorlage an. Sind mehrere Tags vorhanden, fahre mit der Maus über das angezeigte Tags, um alle weiteren Tags zu sehen.

| *Letzte (De)aktivierung*
|Zeigt das Datum der letzten (De)aktivierung der Vorlage an.

2+^| Kontextmenü

| *Vorlage kopieren* (material:file_copy[])
|Ermöglicht das Kopieren der Vorlage.
//weiter beschreiben, sobald Funktion verfügbar ist

| *Vorlage löschen* (material:delete[])
|Ermöglicht das Löschen der Vorlage.
//weiter beschreiben, sobald Funktion verfügbar ist
|===


[#vorlagen-suchen]
== Vorlagen suchen

Mit der Suche kannst du sowohl alle Vorlagen auflisten als auch bestimmte Vorlagen gezielt finden. Beim Öffnen des Menüs wird standardmäßig keine Suche ausgeführt. Klicke auf *Suchen* (material:search[]), um alle Vorlagen anzuzeigen. Außerdem helfen dir Filter dabei, die Suche weiter einzugrenzen, damit du schnell die passende Vorlage findest.

Verwende eine der folgenden Möglichkeiten, um nach Vorlagen zu suchen.

[.instruction]
Vorlagen suchen:

. Öffne das Menü *Einrichtung » Dokumente » DocumentBuilder*.
.. *_Möglichkeit 1:_* Klicke auf material:search[], um direkt eine Liste aller Vorlagen zu sehen.
.. *_Möglichkeit 2:_* Gib etwas in das Suchfeld ein und klicke auf einen der automatischen Vorschläge.
Klicke dann auf material:search[], um die Suche auszuführen.
.. *_Möglichkeit 3:_* Klicke auf material:tune[], um die Suchergebnisse mit Hilfe von Filtern einzugrenzen. Die folgende Tabelle listet alle verfügbaren Filter.
//Which filters are multi-select?
//Adjust filter names --> forward to Kevin

[[table-template-filters]]
.Filter für Vorlagen
[cols="1,3"]
|===
|Filter |Erläuterung

| *Name der Vorlage*
|Gib den Namen der Vorlage ein.

| *Dokumenttyp*
|Wähle den Typ des Dokuments aus der Dropdown-Liste.
multi-select

| *Lieferland*
|Wähle ein Lieferland aus der Dropdown-Liste.
multi-select

| *Art der Steuerzahlung*
//wieder anpassen in Brutto/Netto
|Wähle, ob es sich um eine Vorlage mit Brutto- oder Nettowerten handelt.

| *Zahlungsmethode*
|Wähle eine Zahlungsmethode aus der Dropdown-Liste.
multi-select

| *Tags*
|Gib den Namen eines Tags ein. Für den Typ der Dokumentenvorlage vorhandene Tags werden zur Auswahl angezeigt.
multi-select

| *Herkunft*
|Wähle die Herkunft der Vorlage.
multi

| *Kundenklassen-ID*
|Gib die ID der Kundenklasse ein.

| *Aktivierung*
|Wähle, ob die Vorlage aktiv oder inaktiv ist.

| *Sprache*
|Wähle die Sprache der Vorlage aus der Dropdown-Liste.
mulit

| *Standardvorlage*
|Wähle, ob die Vorlage eine Standardvorlage ist.

| *Standort*
|Wähle den Standort des Mandanten. Du kannst hier auch mehrere Standorte wählen.
|===

.Steuerelemente
[cols="1,4a"]
|===
|Element |Erläuterung

| icon:undo[role="darkGrey"]
|Setzt die gewählten Filterkriterien zurück.

| material:search[role=skyBlue] *SUCHEN*
|Führt die Suche aus.
|===


[#sucheinstellungen-speichern]
== Sucheinstellungen speichern

Wenn du eine Suche ausführst, werden deine gewählten Sucheinstellungen oben als Chips dargestellt.
Diese Sucheinstellungen kannst du speichern, um sie in Zukunft schneller und einfacher wieder verwenden zu können.

[#aktuellen-filter-speichern]
=== Aktuellen Filter speichern

. Führe eine Suche aus.
. Klicke auf *Gespeicherte Filter* (material:bookmarks[role="darkGrey"]).
. Klicke auf material:bookmark_border[role="darkGrey"] *Aktuellen Filter speichern*.
. Gib einen Namen ein und schalte die optionalen Einstellungen bei Bedarf ein (icon:toggle-on[role="blue"]).
. Klicke auf *Speichern*. +
→ Die Filtereinstellungen erscheinen nun unter *Gespeicherte Filter* (material:bookmarks[role="darkGrey"]).


[#gespeicherte-filter-anwenden]
=== Gespeicherte Filter anwenden

. Klicke auf *Gespeicherte Filter* (material:bookmarks[role="darkGrey"]).
. Klicke auf eine bereits erstellte Filtereinstellung. +
→ Die Suche wird ausgeführt und die verwendeten Sucheinstellungen werden oben als Chips dargestellt.

[#filter-als-standard-festlegen]
=== Filter als Standard festlegen???

[#gruppenfunktionen-verwenden]
== Gruppenfunktionen verwenden

In der Übersicht des DocumentBuilders kannst du Gruppenfunktionen verwenden, um bestimmte Aktionen für mehrere Vorlagen gleichzeitig auszuführen. Die folgende Tabelle listet alle verfügbaren Gruppenfunktionen.

//welche Gruppenfunktionen wird es geben?
Vorlagen öffnen/Open templates (material:file_open)
Vorlagen löschen/Delete templates (material:delete[])
((De)Aktivierung?)

Vorlagen wählen (anhaken), dann oben die Gruppenfunktion wählen.
Gruppenfunktionen in Tabelle aufführen.

[#vorlage-erstellen]
== Vorlagen erstellen

Im DocumentBuilder kannst du für jeden Dokumenttyp eine oder mehrere Vorlagen erstellen und nach deinen Wünschen gestalten. Aktivierst (Link) du eine Vorlage anschließend, wird sie zum Generieren von Dokumenten verwendet. Um eine Vorlage zu erstellen, gehe wie im Folgenden beschrieben vor.
Kann immer nur eine Vorlage aktiviert sein? Oder pro Dokumententyp?

[.instruction]
Vorlage erstellen:

. Öffne das Menü *Einrichtung » Dokumente » DocumentBuilder*.
. Führe die Suche (material:search[]) aus, um Dokumentvorlagen anzuzeigen.





Vorlage erstellen
Einstellungen:
Dokumententyp
Name der Vorlage
Dateiname


Widgets + Logo?

Entscheide selbst, welche Vorlage aktiviert und zum Generieren deiner Dokumente verwendet werden soll

Hinweis zum Aktivieren einer Vorlage: Eine Vorlage kann erst aktiviert werden, sobald alle ungespeicherten Änderungen gespeichert wurden.


[#detailansicht]
== Detailansicht einer Vorlage (Einstellungen)

ganz oben ist die Einstellung zum (De)aktivieren der Vorlage (Toggle button)

Template structure / Struktur der Vorlage/Vorlagenstruktur?
Template settings / Einstellungen der Vorlage/Vorlageneinsellungen?
Order settings /Auftragseinstellungen

Sternchen links in Navigation zeigt ungespeicherte Änderungen in dem jeweiligen Bereich an (von anderer Doku übernehmen - Order UI?)


Template structure
?

Template settings
Document type
Template name
File name

Order settings
Language
Location
Referrer
Payment method
Delivery country
Net/Gross
Contact class


Editor (mit Bearbeitungsstift): noch eine Ebene tiefer (unter Template structure)
Im Editor oben via Zahnrad-Button können die “Output settings” geöffnet werden
links daneben ist noch ein Auge-Icon: Preview-Funktion?


Overlay Ausgabeeinstellungen

[[table-output-settings]]
[cols="1,3"]
.Ausgabeeinstellungen
|===
| *Format*
|US Letter, US Legal, US Tabloid, A0, A1, A2, A3, A4, A5, A6, Benutzerdefiniert

| *Ausrichtung*
|Hochformat, Querformat

| *Breite (mm)*
|

| *Höhe (mm)*
|

| *Rand oben (mm)*
|

| *Rand unten (mm)*
|

| *Rand links (mm)*
|

| *Rand rechts (mm)*
|

| *Kopfzeile anzeigen*
|

| *Fußzeile anzeigen*
|

|===

Canvas settings
Neue side nav wird links im tree sein
Editor: Widgets wählen und platzieren...

== Vorschau anzeigen (Notizen überarbeiten) - ask Isabela for more details

Oben auf das Preview-Icon klicken (material:remove_red_eye[])
Es öffnet sich ein Overlay "Vorschau Vorlage anzeigen"
Vorschau-Format wählen (HTML oder PDF)
Bei PDF werden nur gespeicherte Änderungen in der Vorschau angezeigt.
Auftrags-IDS eingeben
unten auf button "Vorschau Vorlage anzeigen" (material:remove_red_eye[role=skyBlue]) klicken
Die Vorschau wird geladen und angezeigt

Labels:

Preview template - Vorschau Vorlage anzeigen
Template preview HTML - HTML-Vorschau Vorlage
Template preview PDF - PDF-Vorschau Vorlage
Preview format - Vorschau-Format
Order ID - Auftrags-ID


= Verfügbare Widgets

Zweispaltiges Layout
Dreispaltiges Layout
Text: _Hinweis zum Editor_: In diesem Widget kannst du Text eingeben und Variablen verwenden. Du hast auch die Möglichkeit, den eingegebenen Text zu formatieren. Mache dazu einen Doppelklick auf das Wort, das du formatieren möchtest. (von EmailBuilder übernommen)
Bild
... vervollständigen
Frage: Ist der Editor nocht irgendwo anders verfügbar?

== Verfügbare Variablen
Tabelle mit Variablen hinzufügen - 1 Tabelle pro Gruppe von Variablen - siehe EmailBuilder
Variablen werden noch neu gruppiert - in UI schauen, welche es gibt und hier in Tabellen auflisten
ebenfalls twig expressions hinzufügen? (siehe EmailBuilder)

Gruppe *Kopfzeile / Fußzeile* / *Header / Footer*:
DE: *Seitenanzahl*, *Seiten gesamt*; EN: *Page number*, *Total pages* --> Seite 1/12; Page 1/12
Besonderheit ist, dass die Variablen nur in Header und Footer verwendet wird, im Content selbst wird der Wert bei der Generierung nicht gefüllt.
Important to know for these is that they can only be displayed in the header and footer sections of the canvas. Therefore, they will be added to a separate group so that users know this.
Also, the HTML preview normally doesn't show page numbers. A solution has to be found for that, maybe we will just display a kind of placeholder so that users know that the variable is there.


= Editor (kein eigenes Kapitel - dient hier nur als Notiz)
Anhand des Editors kannst du deine Texte beliebig formatieren und nach deinen Wünschen hervorheben.
*_Hinweis:_* Die verfügbaren Formatierungen werden erst sichtbar, wenn du Text markierst.
Text vom EmailBuilder zum Text-Widget:
In diesem Widget kannst du Text eingeben und Variablen verwenden. Du hast auch die Möglichkeit, den eingegebenen Text zu formatieren. Mache dazu einen Doppelklick auf das Wort, das du formatieren möchtest.

(Nicht aufzählen, nur als Info)
verfügbare Formatierungen:
bold, italic, underlined
font (size & family) ..was bedeutet das??
alignment (left, right, centered)
numbering and listing (bullet points and 1, 2, 3...)
font colour and highlighting in colour
