= Prozesse ausführen
:keywords: Prozesse ausführen, Prozess starten, Prozess anstoßen
:author: team-docs-automation
:description: Erfahre, wie du angelegte Prozesse ausführst.

[IMPORTANT]
.plentyBase installieren
====
Du benötigst das Tool xref:automatisierung:plentybase-installieren.adoc#[plentyBase], um Prozesse im plentymarkets Backend zu erstellen und auszuführen. Die Installationsdateien für plentyBase findest du im link:https://marketplace.plentymarkets.com/plugins/externe-tools/plentyBase_5053/[plentyMarketplace^].
====

Über das Menü *Prozesse* führst du die Prozesse aus, die im Menü xref:automatisierung:prozesse-einrichten.adoc#[Einrichtung » Prozesse] erstellt wurden.

[#10]
== Prozess ausführen

Gehe wie unten beschrieben vor, um einen Prozess auszuführen. Beachte, dass nur die Prozesse angezeigt werden, die deinem Benutzer:innenkonto oder deiner Rolle zugeordnet wurden.

[discrete]
=== Rechte vergeben

:rights-purpose: Prozesse aufrufen und starten können
:right-one: pass:quotes[*Prozesse > Lesen*]
:right-two: pass:quotes[*Prozesse > Aktualisieren*]

include::_includes:partial$rights.adoc[]

[.instruction]
Prozess ausführen:

. Öffne das Menü *Prozesse*. +
→ Die verfügbaren Prozesse werden angezeigt.
. Klicke auf einen Prozess. +
→ Der Prozess wird angezeigt und befindet sich im Status *Wartend*.
. Klicke auf *Start*. +
→ Der Prozess wird gestartet. +
→ Die Balken im Tab *Arbeitsschritte* zeigen den Fortschritt der einzelnen Prozessschritte an. +
→ Abhängig vom gewählten Prozess ist während der Ausführung ein Eingreifen der Person erforderlich, die den Prozess ausführt.
