= Subaktionen
:keywords: Subaktion, Prozesse Subaktionen
:author: team-docs-automation
:description: Diese Seite bietet dir eine Übersicht der Subaktionen, die du für Prozesse einrichten kannst. Lerne außerdem, wie du Subaktionen zu einer Aktion hinzufügst und allgemeine Einstellungen vornimmst.

Auf dieser Handbuchseite findest du Erläuterungen zu den Subaktionen, die du im Menü **Einrichtung » Prozesse** zu den Aktionen deiner Prozesse hinzufügen kannst.

[IMPORTANT]
.Tool plentyBase erforderlich
====
Um Prozesse zu erstellen und auszuführen benötigst du das Tool xref:automatisierung:plentybase-installieren.adoc#[plentyBase]. Die Installationsdateien für plentyBase findest du im link:https://marketplace.plentymarkets.com/plugins/externe-tools/plentyBase_5053/[plentyMarketplace^].
====

== Subaktion zu Aktion hinzufügen

Gehe wie unten beschrieben vor, um eine Subaktion zu einer Aktion hinzuzufügen. Eine Liste der verfügbaren Subaktionen findest du auf der Handbuchseite xref:automatisierung:subaktionen.adoc#[Subaktionen].

[.instruction]
Subaktion zu Aktion hinzufügen:

. Öffne das Menü *Einrichtung » Prozesse » [Ordner wählen] » [Prozess wählen]*.
. Zeige mit der Maus auf die Aktion, zu der die Subaktion hinzugefügt werden soll. +
→ Das Kontextmenü der Aktion wird geöffnet.
. Klicke auf *Hinzufügen*. +
→ Das Fenster *Hinzufügen* wird angezeigt.
. Wähle die Subaktion aus der Dropdown-Liste. +
Nimm ggf. weitere Einstellungen vor. Beachte dazu die Informationen auf der Handbuchseite xref:automatisierung:aktionen.adoc#[Aktionen].
. *Speichere* die Einstellungen. +
→ Die Subaktion wird erstellt.
. Zeige ggf. mit der Maus auf die Subaktion, um die *Position* oder andere Einstellungen zu bearbeiten.

[TIP]
.Kontextmenü nutzen
====
Wenn die Aktion bereits eine Subaktion enthält, können weitere Subaktionen auch über das Kontextmenü hinzugefügt werden. Klicke dazu mit der rechten Maustaste auf eine Subaktion und wähle *Subaktion davor einfügen* oder *Subaktion dahinter einfügen*.
====

== Verzeichnis der Subaktionen

Die Subaktionen sind in alphabetischer Reihenfolge aufgelistet. Der Aufbau der Informationen pro Subaktion folgt diesem Muster:

* Kurze Erläuterung der Subaktion
* Aktionen, für die die Subaktion verfügbar ist
* Einstellungen, die zusätzlich zu den xref:automatisierung:subaktionen.adoc#110[allgemeinen Einstellungen] für diese Subaktion verfügbar sind

Die Informationen auf dieser Seite dienen als Nachschlagewerk für Benutzer:innen, die mit den Grundprinzipien von plentymarkets Prozessen vertraut sind. Grundlegende Informationen zu Prozessen findest du auf der Handbuchseite xref:automatisierung:prozesse-einrichten.adoc#[Prozesse einrichten].


[#110]
=== Allgemeine Einstellungen

Bestimmte Einstellungen sind für alle Subaktionen verfügbar. <<table-sub-procedures-general-settings>> erläutert diese Einstellungen.

[[table-sub-procedures-general-settings]]
.Allgemeine Einstellungen für Subaktionen
[cols="1,3"]
|====
|Einstellung |Erläuterung

| **Position**
|Zeigt die aktuelle Position der Subaktion innerhalb der Aktion an. Die Subaktion mit der niedrigsten Positionsnummer wird als erstes ausgeführt. Andere Position aus der Dropdown-Liste wählen, um die Abfolge der Subaktionen in der Aktion zu ändern.
|====

[#120]
=== Artikel scannen

Die Subaktion **Artikel scannen** öffnet eine Eingabemaske zum Scannen von Artikeln mit einem Barcode-Scanner.

[.subhead]
Aktionen

Die Subaktion steht für folgende Aktionen zur Verfügung:

* xref:automatisierung:aktionen.adoc#160[Artikelsuche]

[.subhead]
Einstellungen

Für diese Subaktion sind keine zusätzlichen Einstellungen verfügbar. Informationen zu den allgemeinen Einstellungen für Subaktionen findest du in <<table-sub-procedures-general-settings>>.

[#130]
=== Auftragsnotizen hinzufügen

Mit der Subaktion **Auftragsnotizen hinzufügen** fügst du einem Auftrag eine Notiz hinzu.

[.subhead]
Aktionen

Die Subaktion steht für folgende Aktionen zur Verfügung:

* xref:automatisierung:aktionen.adoc#170[Auftrag]

[.subhead]
Einstellungen

<<table-sub-procedure-add-order-notes>> erläutert die zusätzlichen Einstellungen der Subaktion. Informationen zu den allgemeinen Einstellungen für Subaktionen findest du in <<table-sub-procedures-general-settings>>.

[[table-sub-procedure-add-order-notes]]
.Subaktion **Auftragsnotizen hinzufügen**
[cols="1,3"]
|====
|Einstellung |Erläuterung

|Notiz
|Wählen, welche Art von Notizen zum Auftrag hinzugefügt werden soll. +
**Individuelle Eingabe** = Ermöglicht die Eingabe einer Nachricht durch die Person, die den Prozess ausführt, im Prozessablauf. Die Notiz wird am Auftrag hinterlegt. +
**Vordefinierte Eingabe** = Öffnet ein Fenster, in dem im Bereich **Nachricht** eine Nachricht hinterlegt werden kann, die im Prozessablauf bei Aufträgen automatisch als Notiz hinterlegt wird. +
**Keine** = (Nur bei Aktion im Fehlerfall) Legt keine individuelle oder vorgefertigte Notiz am Auftrag an. Empfohlen, wenn nur die Fehlermeldung als Auftragsnotiz hinterlegt werden soll.

|Fehlermeldung als zusätzliche Notiz hinterlegen
|(Nur bei Aktion im Fehlerfall) Häkchen setzen, um die im Prozess ausgegebene Fehlermeldung als Notiz am Auftrag zu hinterlegen.
|====

[#140]
=== Aus Prozess entfernen

Mit der Subaktion **Aus Prozess entfernen** entfernst du Aufträge aus dem Prozess. Der Auftrag wird auch aus Filtern oder angefangenen Boxkommissionierungen entfernt.

[.subhead]
Aktionen

Die Subaktion steht für folgende Aktionen zur Verfügung:

* xref:automatisierung:aktionen.adoc#170[Auftrag]

[.subhead]
Einstellungen

Für diese Subaktion sind keine zusätzlichen Einstellungen verfügbar. Informationen zu den allgemeinen Einstellungen für Subaktionen findest du in <<table-sub-procedures-general-settings>>.

[#150]
=== Bestellung scannen

Die Subaktion **Bestellung scannen** öffnet eine Maske, über die Bestellungen per Barcode-Scanner eingelesen werden.

[.subhead]
Aktionen

Die Subaktion steht für folgende Aktionen zur Verfügung:

* xref:automatisierung:aktionen.adoc#200[Bestellsuche]

[.subhead]
Einstellungen

Für diese Subaktion sind keine zusätzlichen Einstellungen verfügbar. Informationen zu den allgemeinen Einstellungen für Subaktionen findest du in <<table-sub-procedures-general-settings>>.

[#160]
=== Buchung durchführen

Mit der Subaktion **Buchung durchführen** wird automatisch der Wareneingang oder Warenausgang gebucht.

[.subhead]
Aktionen

Die Subaktion steht für folgende Aktionen zur Verfügung:

* xref:automatisierung:aktionen.adoc#440[Warenausgang]
* xref:automatisierung:aktionen.adoc#450[Wareneingang (Bestellung)]

[.subhead]
Einstellungen

Für diese Subaktion sind keine zusätzlichen Einstellungen verfügbar. Informationen zu den allgemeinen Einstellungen für Subaktionen findest du in <<table-sub-procedures-general-settings>>.

[#170]
=== Buchung zurücksetzen

Mit der Subaktion **Buchung zurücksetzen** wird der gebuchte Warenausgang für die gewählten Aufträge zurückgesetzt.

[.subhead]
Aktionen

Die Subaktion steht für folgende Aktionen zur Verfügung:

* xref:automatisierung:aktionen.adoc#440[Warenausgang]

[.subhead]
Einstellungen

Für diese Subaktion sind keine zusätzlichen Einstellungen verfügbar. Informationen zu den allgemeinen Einstellungen für Subaktionen findest du in <<table-sub-procedures-general-settings>>.

[#180]
=== Drucken

Für den Druck von Dokumenten, zum Beispiel Lieferscheinen oder Rechnungen, wählst du beim Hinzufügen dieser Subaktion den gewünschten Drucker.

[.subhead]
Aktionen

Die Subaktion steht für folgende Aktionen zur Verfügung:

* xref:automatisierung:aktionen.adoc#110[Abhol-/Lieferschein]
* xref:automatisierung:aktionen.adoc#120[Adressetikett]
* xref:automatisierung:aktionen.adoc#130[Angebot]
* xref:automatisierung:aktionen.adoc#150[Artikeletikett]
* xref:automatisierung:aktionen.adoc#180[Auftragsbestätigung]
* xref:automatisierung:aktionen.adoc#210[Dokumente]
* xref:automatisierung:aktionen.adoc#240[Gelangensbestätigung]
* xref:automatisierung:aktionen.adoc#250[Gutschrift]
* xref:automatisierung:aktionen.adoc#255[Externe Gutschrift]
* xref:automatisierung:aktionen.adoc#270[Korrekturbeleg]
* xref:automatisierung:aktionen.adoc#280[Lager-Pickliste]
* xref:automatisierung:aktionen.adoc#290[Lieferschein]
* xref:automatisierung:aktionen.adoc#300[Mahnung]
* xref:automatisierung:aktionen.adoc#310[Packliste]
* xref:automatisierung:aktionen.adoc#320[Pickliste]
* xref:automatisierung:aktionen.adoc#350[Rechnung]
* xref:automatisierung:aktionen.adoc#355[Externe Rechnung]
* xref:automatisierung:aktionen.adoc#360[Reparaturschein]
* xref:automatisierung:aktionen.adoc#380[Retourenetikett]
* xref:automatisierung:aktionen.adoc#390[Rücksendeschein]
* xref:automatisierung:aktionen.adoc#422[Stornobeleg Gutschrift]
* xref:automatisierung:aktionen.adoc#424[Stornobeleg Mahnung]
* xref:automatisierung:aktionen.adoc#426[Stornobeleg Rechnung]
* xref:automatisierung:aktionen.adoc#430[Versand-Center]

[.subhead]
Einstellungen

<<table-sub-procedure-print>> erläutert die zusätzlichen Einstellungen der Subaktion. Informationen zu den allgemeinen Einstellungen für Subaktionen findest du in <<table-sub-procedures-general-settings>>.

[[table-sub-procedure-print]]
.Subaktion **Drucken**
[cols="1,3"]
|====
|Einstellung |Erläuterung

|Druckereinstellung
|Eines der im Menü **Einrichtung » Einstellungen » Drucker** gespeicherten xref:automatisierung:drucker.adoc#[Druckerprofile] wählen.

|Kopien
|Anzahl der Kopien pro Ausdruck eingeben.

|Als Sammeldokument
|Häkchen setzen, um alle Dokumente in einem einzigen Dokument zusammenzufassen und gleichzeitig zu drucken.
|====

[#190]
=== Eigner ändern

Mit der Subaktion **Eigner ändern** führst du einen Eignerwechsel durch. Auswählbar sind die in deinem System hinterlegten Eigner.

[.subhead]
Aktionen

Die Subaktion steht für folgende Aktionen zur Verfügung:

* xref:automatisierung:aktionen.adoc#170[Auftrag]

[.subhead]
Einstellungen

<<table-sub-procedure-change-owner>> erläutert die zusätzlichen Einstellungen der Subaktion. Informationen zu den allgemeinen Einstellungen für Subaktionen findest du in <<table-sub-procedures-general-settings>>.

[[table-sub-procedure-change-owner]]
.Subaktion **Eigner ändern**
[cols="1,3"]
|====
|Einstellung |Erläuterung

|Eigner
|Person aus der Dropdown-Liste wählen, der die Subaktion zugewiesen werden soll. Zur Auswahl stehen alle im System angelegten Eigner.
|====

[#192]
=== Generieren

Verwende die Subaktion *Generieren*, um die Generierung eines Dokuments anzustoßen. Somit steht dir das gewünschte Dokument zu einem späteren Zeitpunkt im Prozess direkt zur Verfügung. +
Um das Dokument ebenfalls herunterzuladen, vewende die Aktion <<#350, Zwischenspeichern>>.

[.subhead]
Aktionen

Die Subaktion steht für folgende Aktionen zur Verfügung:

* xref:automatisierung:aktionen.adoc#110[Abhol-/Lieferschein]
* xref:automatisierung:aktionen.adoc#130[Angebot]
* xref:automatisierung:aktionen.adoc#180[Auftragsbestätigung]
* xref:automatisierung:aktionen.adoc#240[Gelangensbestätigung]
* xref:automatisierung:aktionen.adoc#250[Gutschrift]
* xref:automatisierung:aktionen.adoc#270[Korrekturbeleg]
* xref:automatisierung:aktionen.adoc#290[Lieferschein]
* xref:automatisierung:aktionen.adoc#300[Mahnung]
* xref:automatisierung:aktionen.adoc#345[Proformarechnung]
* xref:automatisierung:aktionen.adoc#350[Rechnung]
* xref:automatisierung:aktionen.adoc#360[Reparaturschein]
* xref:automatisierung:aktionen.adoc#390[Rücksendeschein]
* xref:automatisierung:aktionen.adoc#422[Stornobeleg Gutschrift]
* xref:automatisierung:aktionen.adoc#424[Stornobeleg Mahnung]
* xref:automatisierung:aktionen.adoc#426[Stornobeleg Rechnung]

[.subhead]
Einstellungen

Für diese Subaktion sind keine zusätzlichen Einstellungen verfügbar. Informationen zu den allgemeinen Einstellungen für Subaktionen findest du in <<table-sub-procedures-general-settings>>.

[#195]
=== Entferne Auftrag vom Box

Die Subaktion **Entferne Auftrag vom Box** wird für die xref:app:rollende-kommissionierung.adoc#[rollende Kommissionierung] verwendet. Mit dieser Subaktion löst du die Verbindung zwischen Auftrag und Box. Somit steht die Box wieder frei zur Verfügung und kann beim nächsten Durchlauf wiederverwendet werden.

[.subhead]
Aktionen

Die Subaktion steht für folgende Aktionen zur Verfügung:

* xref:automatisierung:aktionen.adoc#170[Auftrag]

[.subhead]
Einstellungen

Für diese Subaktion sind keine zusätzlichen Einstellungen verfügbar. Informationen zu den allgemeinen Einstellungen für Subaktionen findest du in <<table-sub-procedures-general-settings>>.

[#200]
=== Hinweis anzeigen

Die Subaktion **Hinweis** zeigt einen Hinweistext an, den du hinterlegst. Einstellbar ist auch die Zeit, nach der der Hinweis wieder ausgeblendet werden soll.

[.subhead]
Aktionen

Die Subaktion steht für folgende Aktionen zur Verfügung:

* xref:automatisierung:aktionen.adoc#260[Hinweis]

[.subhead]
Einstellungen

<<table-sub-procedure-note>> erläutert die zusätzlichen Einstellungen der Subaktion. Informationen zu den allgemeinen Einstellungen für Subaktionen findest du in <<table-sub-procedures-general-settings>>.

[[table-sub-procedure-note]]
.Subaktion **Hinweis**
[cols="1,3"]
|====
|Einstellung |Erläuterung

| **Titel**
|Aussagekräftigen Titel für den Hinweis eingeben, der angezeigt werden soll.

| **Automatisch schließen**
|Festlegen, ob der Hinweis automatisch geschlossen werden soll, nachdem er angezeigt wurde. +
**Nie** = Der Hinweis muss per Klick geschlossen werden. +
**Nach 1 - 5 Sekunden** = Der Hinweis wird danach automatisch geschlossen.

| **Nachricht**
|Text eingeben, der als Hinweis ausgegeben werden soll. *_Tipp:_* Verwende den Platzhalter *$OrderID*, um automatisch die ID des Auftrags, der aktuell vom Prozess verarbeitet wird, im Hinweistext auszugeben.
|====

[#210]
=== Markierung ändern

Mit der Subaktion **Markierung ändern** führst du eine Änderung der Markierung aus. Auswählbar sind die in deinem System hinterlegten Markierungen.

[.subhead]
Aktionen

Die Subaktion steht für folgende Aktionen zur Verfügung:

* xref:automatisierung:aktionen.adoc#170[Auftrag]

[.subhead]
Einstellungen

<<table-sub-procedure-change-flag>> erläutert die zusätzlichen Einstellungen der Subaktion. Informationen zu den allgemeinen Einstellungen für Subaktionen findest du in <<table-sub-procedures-general-settings>>.

[[table-sub-procedure-change-flag]]
.Subaktion **Markierung ändern**
[cols="1,3"]
|====
|Einstellung |Erläuterung

|Markierung
|Markierung aus der Dropdown-Liste wählen, die durch die Subaktion zugewiesen werden soll.
|====

[#230]
=== Notizen zum Auftrag

Bei der Subaktion **Notizen zum Auftrag** werden während des Prozesses in Verbindung mit der Aktion xref:automatisierung:aktionen.adoc#260[Hinweis] die im Menü xref:auftraege:auftraege-verwalten.adoc#1530[Aufträge » Aufträge bearbeiten » Tab: Übersicht] hinterlegten Informationen angezeigt und können von der Person, die den Prozess ausführt, berücksichtigt werden. Die Notizen können bei der Bestellung angegeben werden. Beispiel:

* Den kostenlosen Werbeartikel nicht senden, habe dafür keine Verwendung!

Oder trage Notizen selbst ein. Beispiel:

* Keine Werbeartikel beilegen!

[.subhead]
Aktionen

Die Subaktion steht für folgende Aktionen zur Verfügung:

* xref:automatisierung:aktionen.adoc#260[Hinweis]

[.subhead]
Einstellungen

<<table-sub-procedure-notes-concerning-order>> erläutert die zusätzlichen Einstellungen der Subaktion. Informationen zu den allgemeinen Einstellungen für Subaktionen findest du in <<table-sub-procedures-general-settings>>.

[[table-sub-procedure-notes-concerning-order]]
.Subaktion **Notizen zum Auftrag**
[cols="1,3"]
|====
|Einstellung |Erläuterung

|Sichtbarkeit
|Wählen, welche Notizen angezeigt werden sollen. +
**ALLE** = Alle Notizen werden angezeigt. +
**Nur Kundennotizen** = Nur Notizen werden angezeigt, die bei einer Bestellung eingegeben wurden. +
**Nur Mitarbeiternotizen** = Nur Notizen werden angezeigt, die Mitarbeiter:innen eingegeben haben.
|====

[#240]
=== Notizen zum Kunden

Bei der Subaktion **Notizen zum Kunden** werden während des Prozesses in Verbindung mit der Aktion xref:automatisierung:aktionen.adoc#260[Hinweis] die im Menü **CRM » Kontakte » Ansicht: Notizen** hinterlegten Informationen angezeigt und können von der Person, die den Prozess ausführt, berücksichtigt werden. +
Beispiel:

* Kontakt möchte keine Werbung erhalten.

[.subhead]
Aktionen

Die Subaktion steht für folgende Aktionen zur Verfügung:

* xref:automatisierung:aktionen.adoc#260[Hinweis]

[.subhead]
Einstellungen

Für diese Subaktion sind keine zusätzlichen Einstellungen verfügbar. Informationen zu den allgemeinen Einstellungen für Subaktionen findest du in <<table-sub-procedures-general-settings>>.

[#245]
=== Online speichern

Mit der Subaktion **Online speichern** speicherst du eine Online-Pickliste, die in der plentymarkets App aufgerufen und abgearbeitet werden kann.

[.subhead]
Aktionen

Die Subaktion steht für folgende Aktionen zur Verfügung:

* xref:automatisierung:aktionen.adoc#320[Pickliste]

[.subhead]
Einstellungen

Für diese Subaktion sind keine zusätzlichen Einstellungen verfügbar. Informationen zu den allgemeinen Einstellungen für Subaktionen findest du in <<table-sub-procedures-general-settings>>.

[#250]
=== Paketnummer erfassen

Mit der Subaktion **Paketnummer erfassen** erfasst du eine Paketnummer.

[.subhead]
Aktionen

Die Subaktion steht für folgende Aktionen zur Verfügung:

* xref:automatisierung:aktionen.adoc#170[Auftrag]

[.subhead]
Einstellungen

<<table-sub-procedure-scan-package-number>> erläutert die zusätzlichen Einstellungen der Subaktion. Informationen zu den allgemeinen Einstellungen für Subaktionen findest du in <<table-sub-procedures-general-settings>>.

[[table-sub-procedure-scan-package-number]]
.Subaktion **Paketnummer erfassen**
[cols="1,3"]
|====
|Einstellung |Erläuterung

|Paketnummern-Format
|Paketnummern-Format aus der Dropdown-Liste wählen.
|====

[#260]
=== Seriennummern erfassen

Mit der Subaktion **Seriennummern erfassen** erfasst du im Prozessablauf xref:artikel:seriennummern.adoc#[Seriennummern] per Barcode-Scanner. Wähle, ob du neue Seriennummern erlauben möchtest und ob Seriennummern automatisch gespeichert werden sollen.

[.subhead]
Aktionen

Die Subaktion steht für folgende Aktionen zur Verfügung:

* xref:automatisierung:aktionen.adoc#420[Seriennummern]

[.subhead]
Einstellungen

<<table-sub-procedure-register-serial-numbers>> erläutert die zusätzlichen Einstellungen der Subaktion. Informationen zu den allgemeinen Einstellungen für Subaktionen findest du in <<table-sub-procedures-general-settings>>.

[[table-sub-procedure-register-serial-numbers]]
.Subaktion **Seriennummern erfassen**
[cols="1,3"]
|====
|Einstellung |Erläuterung

|Neue Seriennummern
a|Soll es möglich sein, Seriennummern zu scannen, die nicht zuvor in deinem xref:artikel:seriennummern.adoc#[Pool von Seriennummern im Artikeldatensatz] gespeichert wurden?

* *Erlauben* = Jede Seriennummer kann gescannt werden. Dabei spielt es keine Rolle, ob die Seriennummer bereits im Artikeldatensatz existiert.
** *_Vorteil_*: Diese Methode kann Zeit sparen, da die Seriennummern nicht vorab gespeichert werden müssen.
** *_Nachteil_*: Diese Methode ist etwas fehleranfälliger. Was ist zum Beispiel, wenn dein Lagermitarbeiter versehentlich die EAN scannt? plentymarkets hätte keine Möglichkeit, zu verifizieren, ob es sich hier um eine echte Seriennummer handelt oder nicht. +
* *Nicht erlauben* = Eine Seriennummer kann nur gescannt werden, wenn sie im Artikeldatensatz vorhanden ist.

|Automatisches Speichern
| **Ja** = Nach erfolgreicher Erfassung der Seriennummern aller Artikelpositionen eines Artikels wird gespeichert und der Prozess automatisch fortgesetzt. +
**Nein** = Nach erfolgreicher Erfassung der Seriennummern aller Artikelpositionen eines Artikels muss im Prozessablauf auf **Speichern** geklickt werden, bevor der Prozess fortgesetzt wird.
|====

[#270]
=== Sounds

Mit der Subaktion **Sounds** gibst du zur Bestätigung, dass eine Aktion ausgeführt wurde, ein akustisches Signal aus.

[.subhead]
Aktionen

Die Subaktion steht für folgende Aktionen zur Verfügung:

* xref:automatisierung:aktionen.adoc#110[Abhol-/Lieferschein]
* xref:automatisierung:aktionen.adoc#120[Adressetikett]
* xref:automatisierung:aktionen.adoc#130[Angebot]
* xref:automatisierung:aktionen.adoc#150[Artikeletikett]
* xref:automatisierung:aktionen.adoc#160[Artikelsuche]
* xref:automatisierung:aktionen.adoc#170[Auftrag]
* xref:automatisierung:aktionen.adoc#180[Auftragsbestätigung]
* xref:automatisierung:aktionen.adoc#210[Dokumente]
* xref:automatisierung:aktionen.adoc#220[E-Mail]
* xref:automatisierung:aktionen.adoc#240[Gelangensbestätigung]
* xref:automatisierung:aktionen.adoc#250[Gutschrift]
* xref:automatisierung:aktionen.adoc#260[Hinweis]
* xref:automatisierung:aktionen.adoc#270[Korrekturbeleg]
* xref:automatisierung:aktionen.adoc#280[Lager-Pickliste]
* xref:automatisierung:aktionen.adoc#290[Lieferschein]
* xref:automatisierung:aktionen.adoc#300[Mahnung]
* xref:automatisierung:aktionen.adoc#310[Packliste]
* xref:automatisierung:aktionen.adoc#320[Pickliste]
* xref:automatisierung:aktionen.adoc#340[Polling]
* xref:automatisierung:aktionen.adoc#350[Rechnung]
* xref:automatisierung:aktionen.adoc#360[Reparaturschein]
* xref:automatisierung:aktionen.adoc#380[Retourenetikett]
* xref:automatisierung:aktionen.adoc#390[Rücksendeschein]
* xref:automatisierung:aktionen.adoc#400[SEPA Pain001]
* xref:automatisierung:aktionen.adoc#410[SEPA Pain008]
* xref:automatisierung:aktionen.adoc#430[Versand-Center]
* xref:automatisierung:aktionen.adoc#440[Warenausgang]

[.subhead]
Einstellungen

<<table-sub-procedure-sounds>> erläutert die zusätzlichen Einstellungen der Subaktion. Informationen zu den allgemeinen Einstellungen für Subaktionen findest du in <<table-sub-procedures-general-settings>>.

[[table-sub-procedure-sounds]]
.Subaktion **Sounds**
[cols="1,3"]
|====
|Einstellung |Erläuterung

|Sounds
|Akustisches Signal wählen, das ausgegeben werden soll, wenn eine Aktion ausgeführt wurde.
|====

[#280]
=== Speichern

Die Dokumente werden in einem Ordner gespeichert, den du beim Erstellen der Subaktion wählst. Wenn mehrere Benutzer:innen den Prozess verwenden sollen, gib einen für alle verfügbaren Ordner an.

[.subhead]
Aktionen

Die Subaktion steht für folgende Aktionen zur Verfügung:

* xref:automatisierung:aktionen.adoc#110[Abhol-/Lieferschein]
* xref:automatisierung:aktionen.adoc#120[Adressetikett]
* xref:automatisierung:aktionen.adoc#130[Angebot]
* xref:automatisierung:aktionen.adoc#150[Artikeletikett]
* xref:automatisierung:aktionen.adoc#180[Auftragsbestätigung]
* xref:automatisierung:aktionen.adoc#210[Dokumente]
* xref:automatisierung:aktionen.adoc#220[E-Mail]
* xref:automatisierung:aktionen.adoc#230[FiBu-Export]
* xref:automatisierung:aktionen.adoc#240[Gelangensbestätigung]
* xref:automatisierung:aktionen.adoc#250[Gutschrift]
* xref:automatisierung:aktionen.adoc#270[Korrekturbeleg]
* xref:automatisierung:aktionen.adoc#280[Lager-Pickliste]
* xref:automatisierung:aktionen.adoc#290[Lieferschein]
* xref:automatisierung:aktionen.adoc#300[Mahnung]
* xref:automatisierung:aktionen.adoc#310[Packliste]
* xref:automatisierung:aktionen.adoc#320[Pickliste]
* xref:automatisierung:aktionen.adoc#340[Polling]
* xref:automatisierung:aktionen.adoc#350[Rechnung]
* xref:automatisierung:aktionen.adoc#360[Reparaturschein]
* xref:automatisierung:aktionen.adoc#380[Retourenetikett]
* xref:automatisierung:aktionen.adoc#390[Rücksendeschein]
* xref:automatisierung:aktionen.adoc#400[SEPA Pain001]
* xref:automatisierung:aktionen.adoc#410[SEPA Pain008]
* xref:automatisierung:aktionen.adoc#430[Versand-Center]

[.subhead]
Einstellungen

<<table-sub-procedure-save>> erläutert die zusätzlichen Einstellungen der Subaktion. Informationen zu den allgemeinen Einstellungen für Subaktionen findest du in <<table-sub-procedures-general-settings>>.

[[table-sub-procedure-save]]
.Subaktion **Speichern**
[cols="1,3"]
|====
|Einstellung |Erläuterung

|Zielordner
|Auf *Bearbeiten* klicken und den Pfad wählen, unter dem die Dokumente gespeichert werden sollen.

|Dateiname
|Wählen, unter welchem Namen die Dokumente gespeichert werden sollen. +
**Standard** = Dateien erhalten den Standardnamen. +
**Benutzerdefiniert** = Eigenen Namen eingeben. Verfügbare Variable: $PlentyID. +
**Unterordner erstellen** = Die Dokumente werden in einem Unterordner angelegt. Dieser Unterordner wird nach dem Muster Zielordner/Typ_Datum_Uhrzeit/ erstellt.

|Als Sammeldokument
|Häkchen setzen, um alle Dokumente in einem Dokument zusammenzufassen und nur dieses Dokument zu speichern.
|====

[#290]
=== Status ändern

Mit der Subaktion **Status ändern** führst du einen Statuswechsel durch. Auswählbar sind die in deinem System gespeicherten Status.

[.subhead]
Aktionen

Die Subaktion steht für folgende Aktionen zur Verfügung:

* xref:automatisierung:aktionen.adoc#170[Auftrag]

[.subhead]
Einstellungen

<<table-sub-procedure-change-status>> erläutert die zusätzlichen Einstellungen der Subaktion. Informationen zu den allgemeinen Einstellungen für Subaktionen findest du in <<table-sub-procedures-general-settings>>.

[[table-sub-procedure-change-status]]
.Subaktion **Status ändern**
[cols="1,3"]
|====
|Einstellung |Erläuterung

|Status
|Status aus der Dropdown-Liste wählen, der durch die Subaktion zugewiesen werden soll.
|====

[#300]
=== Tags hinzufügen/entfernen

Mit der Subaktion *Tags hinzufügen/entfernen* fügst du Tags zu einem Auftrag hinzu oder entfernst Tags aus einem Auftrag.

[.subhead]
Aktionen

Die Subaktion steht für folgende Aktionen zur Verfügung:

* xref:automatisierung:aktionen.adoc#170[Auftrag]

[.subhead]
Einstellungen

<<table-sub-procedure-add-remove-tags>> erläutert die zusätzlichen Einstellungen der Subaktion. Informationen zu den allgemeinen Einstellungen für Subaktionen findest du in <<table-sub-procedures-general-settings>>.

[[table-sub-procedure-add-remove-tags]]
.Subaktion *Tags hinzufügen/entfernen*
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Ausgewählte Tags*
|Wähle aus der Dropdown-Liste, ob du Tags hinzufügen oder entfernen möchtest.

| *Tags*
|Klicke in das Feld, um Tags zu wählen. Je nach Einstellung werden diese Tags zum Auftrag hinzugefügt oder aus dem Auftrag entfernt.
|====

[#310]
=== Versandpakete

Mit der Subaktion **Versandpakete** legst du Versandpakete an und bearbeitest diese Versandpakete.

[.subhead]
Aktionen

Die Subaktion steht für folgende Aktionen zur Verfügung:

* xref:automatisierung:aktionen.adoc#170[Auftrag]

[.subhead]
Einstellungen

Für diese Subaktion sind keine zusätzlichen Einstellungen verfügbar. Informationen zu den allgemeinen Einstellungen für Subaktionen findest du in <<table-sub-procedures-general-settings>>.

[#320]
=== Versandprofil ändern

Mit der Subaktion **Versandprofil ändern** wechselst du ein Versandprofil.

[.subhead]
Aktionen

Die Subaktion steht für folgende Aktionen zur Verfügung:

* xref:automatisierung:aktionen.adoc#170[Auftrag]

[.subhead]
Einstellungen

<<table-sub-procedure-change-shipping-profile>> erläutert die zusätzlichen Einstellungen der Subaktion. Informationen zu den allgemeinen Einstellungen für Subaktionen findest du in <<table-sub-procedures-general-settings>>.

[[table-sub-procedure-change-shipping-profile]]
.Subaktion **Versandprofil ändern**
[cols="1,3"]
|====
|Einstellung |Erläuterung

|Versandprofil
|Ein Versandprofil aus der Dropdown-Liste wählen, um dieses Versandprofil durch die Subaktion zuzuweisen. Zur Auswahl stehen alle im System angelegten Versandprofile.

|Checkbox
|Häkchen setzen, um andere Versandkosten als die Versandkosten aus dem gewählten Versandprofil zu verwenden.

|Versandkosten
|Versandkosten eingeben. Wenn in der Checkbox ein Häkchen gesetzt ist, werden die eingetragenen Versandkosten verwendet.
|====

[#330]
=== Versenden

Mit der Subaktion **Versenden** versendst du die E-Mail-Vorlage, die für die Aktion xref:automatisierung:aktionen.adoc#220[E-Mail] eingestellt wurde.

[.subhead]
Aktionen

Die Subaktion steht für folgende Aktionen zur Verfügung:

* xref:automatisierung:aktionen.adoc#220[E-Mail]

[.subhead]
Einstellungen

Für diese Subaktion sind keine zusätzlichen Einstellungen verfügbar. Informationen zu den allgemeinen Einstellungen für Subaktionen findest du in <<table-sub-procedures-general-settings>>.

[#340]
=== Zahlungsart ändern

Mit der Subaktion **Zahlungsart ändern** änderst du die Zahlungsart eines Auftrags.

[.subhead]
Aktionen

Die Subaktion steht für folgende Aktionen zur Verfügung:

* xref:automatisierung:aktionen.adoc#170[Auftrag]

[.subhead]
Einstellungen

<<table-sub-procedure-payment-method>> erläutert die zusätzlichen Einstellungen der Subaktion. Informationen zu den allgemeinen Einstellungen für Subaktionen findest du in <<table-sub-procedures-general-settings>>.

[[table-sub-procedure-payment-method]]
.Subaktion **Zahlungsart ändern**
[cols="1,3"]
|====
|Einstellung |Erläuterung

| **Zahlungsart**
|Neue Zahlungsart aus der Dropdown-Liste wählen, die den Aufträgen zugewiesen werden soll.
|====

[#350]
=== Zwischenspeichern

Mit der Subaktion *Zwischenspeichern* wird ein Dokument generiert und heruntergeladen, sodass es zu einem späteren Zeitpunkt im Prozess verwendet werden kann. Da das Dokument auch heruntergeladen wird, können Aktionen wie Speichern oder Drucken direkt ausgeführt werden. +
Wenn viele Dokumente gespeichert oder gedruckt werden sollen, kann es im Prozessablauf zu Wartezeiten kommen. Um dies zu vermeiden, platziere die Subaktion *Zwischenspeichern* zum Beispiel vor einer Aktion, die mehr Zeit beansprucht als der Speichervorgang. Das Zwischenspeichern läuft dann im Hintergrund ab, während die Aktion ausgeführt wird. Danach kannst du zum Beispiel die Subaktion *Drucken* einbauen. Der Drucker greift dann auf die im Hintergrund geladenen und gespeicherten Dokumente zu und druckt diese Dokumente.

[NOTE]
.Zwischenspeichern nicht mit Aktion für den Fehlerfall kombinieren
====
Richte die Subaktion **Zwischenspeichern** nicht für eine Aktion ein, für die du auch eine Aktion für den Fehlerfall erstellst. Da das Zwischenspeichern asynchron läuft, behindern sich diese Vorgänge sonst gegenseitig.
====

[.subhead]
Aktionen

Die Subaktion steht für folgende Aktionen zur Verfügung:

* xref:automatisierung:aktionen.adoc#110[Abhol-/Lieferschein]
* xref:automatisierung:aktionen.adoc#120[Adressetikett]
* xref:automatisierung:aktionen.adoc#130[Angebot]
* xref:automatisierung:aktionen.adoc#150[Artikeletikett]
* xref:automatisierung:aktionen.adoc#180[Auftragsbestätigung]
* xref:automatisierung:aktionen.adoc#210[Dokumente]
* xref:automatisierung:aktionen.adoc#240[Gelangensbestätigung]
* xref:automatisierung:aktionen.adoc#250[Gutschrift]
* xref:automatisierung:aktionen.adoc#270[Korrekturbeleg]
* xref:automatisierung:aktionen.adoc#280[Lager-Pickliste]
* xref:automatisierung:aktionen.adoc#290[Lieferschein]
* xref:automatisierung:aktionen.adoc#300[Mahnung]
* xref:automatisierung:aktionen.adoc#310[Packliste]
* xref:automatisierung:aktionen.adoc#320[Pickliste]
* xref:automatisierung:aktionen.adoc#350[Rechnung]
* xref:automatisierung:aktionen.adoc#360[Reparaturschein]
* xref:automatisierung:aktionen.adoc#380[Retourenetikett]
* xref:automatisierung:aktionen.adoc#390[Rücksendeschein]
* xref:automatisierung:aktionen.adoc#430[Versand-Center]

[.subhead]
Einstellungen

Für diese Subaktion sind keine zusätzlichen Einstellungen verfügbar. Informationen zu den allgemeinen Einstellungen für Subaktionen findest du in <<table-sub-procedures-general-settings>>.
