= Kataloge kennenlernen
:keywords:
:description: Du beschäftigst dich zum ersten Mal mit den Katalogen? Dann bist du hier richtig.
:page-index:
:author: team-plenty-channel

Du beschäftigst dich zum ersten Mal mit den Katalogen? Dann bist du hier richtig.

* <<#catalogue-formats, Welche Arten von Katalogen gibt es?>>
* <<#catalogue-overview, Lerne die Katalogübersicht kennen.>>

include::_includes:page$new-page-info-box.adoc[]

[#catalogue-formats]
== Welche Arten von Katalogen gibt es?

Kataloge dienen dazu, Daten aus deinem plentymarkets System zu exportieren. Es gibt Kataloge mit Marktplatz-Formaten und Kataloge mit Standardformaten.

[cols="1,4a"]
|===

| *Standardformate*
| Mit den Standardformaten *_exportierst du Daten aus deinem plentymarkets System in eine CSV-, JSON-, TXT- oder XML-Datei_*.

Für den Export verschiedener Daten stehen dir verschiedene Standardformate zur Verfügung. Um zum Beispiel deine Warenbestände zu exportieren, nutzt du das Standardformat xref:daten:katalog-warenbestaende.adoc#[Warenbestände]. Zum Exportieren von Artikeldaten steht das Standardformat xref:daten:katalog-artikel.adoc#[Artikel] zur Verfügung.

Bisher kannst du noch nicht alle Arten von Daten über Kataloge exportieren. Bis Standardformate für alle Datenarten verfügbar sind, kannst du weiterhin den xref:page$FormatDesigner.adoc#[Formatdesigner] nutzen.

* Wie du Kataloge mit Standardformaten erstellst, ist auf der Seite xref:daten:dateiexport.adoc#[Standardformate nutzen] beschrieben.

| *Marktplatz-Format*
| Mit den Marktplatz-Formaten *_exportierst du Variantendaten an Marktplätze und andere Verkaufskanäle._*

Jeder Verkaufskanal benötigt unterschiedliche Produktdaten. Häufig müssen auch für verschiedene Produktkategorien unterschiedliche Produktdaten an denselben Verkaufskanal exportiert werden. Bei Tierfutter musst du zum Beispiel den Grundpreis angeben. Bei Kleidung und Schuhen sind Materialangaben notwendig.

Ein Marktplatz-Format stellt ein Gerüst der Daten bereit, die der Verkaufskanal entgegennehmen kann. So kannst du die Informationen zu deinem Produktsortiment auf die Anforderungen und die Zielgruppe eines Verkaufskanals zuschneiden.

* Eine Einführung in das Thema Marktplatzformate findest du auf der Seite xref:daten:marktplatzexport.adoc#[Marktplatz-Formate nutzen].
* Wie du Kataloge mit Marktplatz-Formaten erstellst, ist xref:maerkte:maerkte.adoc#[auf den Seiten der einzelnen Verkaufskanäle beschrieben].

|===

[#catalogue-overview]
== Katalogübersicht kennenlernen

include::partial$catalogue-overview.adoc[]

[#faq]
== FAQ: Fragen und Antworten

include::partial$catalogues-faq.adoc[tag=faq-which-format]

include::partial$catalogues-faq.adoc[tag=rights]
