= Daten-Log
:keywords: Log, Logs, Datenlog, Log-Einträge, Logeintrag, Log-Level, Referenztyp, Referenzwert, Logs konfigurieren, Fehlermeldungen, Schweregrad, Ereignisse, Systemereignisse
:description: Erfahre, wie du im Daten-Log nach Fehlermeldungen und Informationen zu Systemereignissen suchst.
:author: team-plenty-channel

Im Menü *Daten » Log* werden Ereignisse protokolliert, die in deinem System stattfinden. Wenn also etwas schiefgelaufen ist, kannst du im Daten-Log selbst nach dem Fehler suchen und bist nicht auf unseren Support angewiesen.

Ereignisse mit den Schweregraden *Error*, *Critical*, *Alert* und *Emergency* werden automatisch protokolliert. Für andere Ereignisse kannst du optional die Protokollierung für einen bestimmten Zeitraum aktivieren.

== Was ist das Daten-Log?

Daten-Log bedeutet auf Deutsch "Datenprotokoll". Im Daten-Log werden also Ereignisse protokolliert, die in deinem System stattfinden.

* Jeder Log-Eintrag steht für ein Ereignis in deinem System.
* Jeder Log-Eintrag ist ab dem Ereignis vier Wochen verfügbar. Danach wird der Log-Eintrag automatisch gelöscht.
* Ereignisse haben verschiedene Schweregrade. In plentymarkets heißen diese Schweregrade "Log-Levels".
* Ereignisse mit den Log-Levels *Error*, *Critical*, *Alert* und *Emergency* werden automatisch protokolliert.
* Die Log-Level *Debug*, *Info*, *Notice* und *Warning* müssen aktiviert werden, damit Ereignisse dieser Levels protokolliert werden. (<<#10, Wie?>>)
* Jeder Log-Eintrag enthält die folgenden Informationen über das Ereignis:

[cols="1,2a"]
|===
| *Zeitstempel*
| Das Datum und die Uhrzeit des Ereignisses

| *Level*
| Der Schweregrad des Ereignisses +
(<<#log-levels, Was bedeuten die Log-Levels?>>)

| *Integration*
| Der Bereich des Systems, in dem das Ereignis stattgefunden hat.

*_Beispiele:_*

* Ceres
* DHLShipping
* Etsy

| *Identifikator*
| Der Unterbereich, in dem das Ereignis stattgefunden hat.

*_Beispiele:_*

* AmazonCatalog

| *Referenztyp*
| Die Art des Datensatzes: Handelt es sich zum Beispiel um eine Adress-ID, einen Katalognamen oder um die ID des Etsy-Listings?

| *Referenzwert*
| Der Wert des Datensatzes, der vom Ereignis betroffenen ist. Also zum Beispiel die ID eines Artikels, einer Variante oder einer Kategorie.

| *Nachricht*
| Eine Beschreibung des Ereignisses

| *Log-Details* +
(in separatem Fenster)
| Klicke auf einen Log-Eintrag, um die Detailansicht zu öffnen. Hier findest du weitere Informationen zum Ereignis. In diesem Fenster kannst du auch zum vorherigen oder zum nächsten Log-Eintrag springen. Außerdem kannst du die Informationen einklappen oder ausklappen.
|===

[#log-levels]
== Bedeutung der Log-Levels

[[tabelle-bedeutung-log-level]]
.Bedeutung der verschiedenen Log-Level
[cols="1,4,1"]
|===
|Log-Level |Bedeutung |Standardmäßig aktiviert

| *Debug*
| Detaillierte Statusmeldungen
| Nein

| *Info*
| Allgemeine Informationen zum System
| Nein

| *Notice*
| Eine zu klärende, aber nicht dringende Fehlermeldung.
| Nein

| *Warning*
| Etwas läuft nicht wie gewünscht. Es muss sich aber nicht um einen Fehler handeln.
| Nein

| *Error*
| Standard-Systemfehler; bei Fehlern läuft das System in der Regel weiter.
| Ja

| *Critical*
| Diese Fehler können zum Systemabsturz führen.
| Ja

| *Alert*
| Es muss sofort reagiert werden. +
*_Beispiel:_* Webshop oder Datenbank sind nicht erreichbar.
| Ja

| *Emergency*
| Absoluter Notfall. Das gesamte System funktioniert nicht.
| Ja
|===

[#20]
== Log-Einträge finden

Wenn du das Menü *Daten » Log* öffnest, wird eine Liste aller protokollierten Ereignisse für den Standardmandanten angezeigt. Diese Liste ist nach Datum und Uhrzeit des Ereignisses sortiert. Das neueste Ereignis steht also ganz oben.

Um die Liste der Ereignisse zu reduzieren und übersichtlicher zu machen, kannst du die Log-Einträge filtern.

[.instruction]
Liste der Log-Einträge filtern:

. Öffne das Menü *Daten » Log*. +
→ Alle protokollierten Ereignisse des Standard-Mandanten werden angezeigt.
. Klicke oben links in der Symbolleiste auf material:tune[]. +
→ Die verfügbaren Filter werden angezeigt.
. Setze die gewünschten Filter. Beachte dazu die Erläuterungen in <<#log-filter>>. +
*_Fehlt ein Filter in den Dropdown-Listen?_* +
Die Dropdown-Listen enthalten nur Filter für Ereignisse, für die es auch Log-Einträge gibt. Wenn also zum Beispiel in der Liste kein Eintrag für *OTTO Market* wählbar ist, wurden in den letzten vier Wochen keine Ereignisse für diesen Marktplatz protokolliert.
. Klicke auf icon:search[] *Suchen*. +
→ Die Log-Einträge werden gefiltert angezeigt. +
*_Du hast den gesuchten Eintrag nicht gefunden?_* +
 Nicht alle Ereignisse werden standardmäßig protokolliert. Deshalb musst du möglicherweise <<#10, die Protokollierung für das gesuchte Ereignis erst aktivieren>>.

[[log-filter]]
.Verfügbare Filter
[cols="1,3a"]
|===
|Filter |Erläuterung

| *Mandant*
| Standardmäßig ist als Filter der Standard-Mandant eingestellt. Einen anderen Mandanten aus der Dropdown-Liste wählen, um Ereignisse für diesen Mandanten anzuzeigen.

| *Integration*
| Der Bereich des Systems, in dem das Ereignis stattgefunden hat.

*_Beispiele:_*

* Ceres
* DHLShipping
* Etsy

| *Identifikator*
| Der Unterbereich, in dem das Ereignis stattgefunden hat.

*_Beispiele:_*

* AmazonCatalog

| *Level*
| Der Schweregrad des Ereignisses. +
(<<#log-levels, Was beuten die Log-Levels?>>)

| *Referenztyp*
| Die Art des Datensatzes: Handelt es sich zum Beispiel um eine Adress-ID, einen Katalognamen oder um die ID des Etsy-Listings?

| *Referenzwert*
| Der Wert des Datensatzes, der vom Ereignis betroffenen ist. Also zum Beispiel die ID eines Artikels, einer Variante oder einer Kategorie.

| *Datum vom*
| Auf das Kalendersymbol (material:today[]) klicken, um ein Datum zu wählen. +
→ Nur Ereignisse ab diesem Datum werden in der Liste angezeigt. +
*_Hinweis:_* Du kannst ein beliebiges Datum wählen. Beachte jedoch, dass nur Ereignisse der letzten vier Wochen angezeigt werden können. Nach vier Wochen werden Log-Einträge automatisch gelöscht.

| *Uhrzeit von*
| Uhrzeit im Format HH:MM:SS eingeben. +
→ Wenn du ein *Datum vom* wählst, werden Ereignisse ab dieser Uhrzeit am gewählten Datum angezeigt. +
→ Wenn du kein *Datum vom* wählst, werden Ereignisse ab dieser Uhrzeit am heutigen Tag angezeigt.

| *Datum bis*
| Auf das Kalendersymbol (material:today[]) klicken, um ein Datum zu wählen. +
→ Nur Ereignisse bis einschließlich diesem Datum werden in der Liste angezeigt. +
*_Hinweis:_* Du kannst ein beliebiges Datum wählen. Beachte jedoch, dass nur Ereignisse der letzten vier Wochen angezeigt werden können. Nach vier Wochen werden Log-Einträge automatisch gelöscht.

| *Uhrzeit bis*
| Uhrzeit im Format HH:MM:SS eingeben. +
→ Wenn du ein *Datum bis* wählst, werden Ereignisse bis einschließlich dieser Uhrzeit am gewählten Datum angezeigt. +
→ Wenn du kein *Datum bis* wählst, werden Ereignisse bis einschließlich dieser Uhrzeit am heutigen Tag angezeigt.
|===

[#10]
== Optionale Protokollierung aktivieren

Ereignisse mit den Log-Levels *Error*, *Critical*, *Alert* und *Emergency* werden automatisch protokolliert.
Damit aber Ereignisse mit den Log-Levels *Debug*, *Info*, *Notice* und *Warning* protokolliert werden, muss die Protokollierung erst aktiviert werden.

* Die Protokollierung endet nach der eingestellten Dauer automatisch.
* Du weißt nicht, was du protokollieren musst, und vor lauter Integrationen, Referenztypen und Identifikatoren dreht sich alles? Für viele Marktplätze findest du die nötigen Infos auf der Handbuchseite des Marktplatzes. Oder frag einfach im Forum nach, welche Bereiche du protokollieren musst.

[.instruction]
Optionale Protokollierung aktivieren:

. Öffne das Menü *Daten » Log*. +
→ Alle für den Standard-Mandanten protokollierten Ereignisse werden angezeigt.
. Klicke oben links in der Toolbar auf *Logs konfigurieren* (icon:cog[]). +
→ Das Fenster *Log-Konfiguration* wird geöffnet. +
→ Auf der linken Seite werden die Systembereiche und die installierten Plugins angezeigt.
. Wähle den Bereich, in dem du Logs konfigurieren möchtest. +
→ Auf der rechten Seite werden die Einstellungen für  diesen Bereich angezeigt.
. Aktiviere die Option *Aktiv*.
. Wähle in der Dropdown-Liste *Dauer*, wie lange Ereignisse für diesen Bereich protokolliert werden sollen.
. Wähle in der Dropdown-Liste *Log-Level*, welche Ereignisse du protokollieren möchtest. +
<<#log-levels, Was bedeuten die Log-Levels?>>
. Speichere (icon:save[]) die Einstellungen. +
→ Die Protokollierung wird gestartet. +
→ Die Protokollierung endet nach der eingestellten Dauer automatisch. +
*_Wichtig:_* Wann der erste Log-Eintrag verfügbar ist hängt davon ab, wann das Ereignis das nächste Mal auftritt, das du protokollierst.
