= Daten
:lang: de
:keywords: Daten, Datenaustausch, ElasticSync, FormatDesigner, Elastischer Export, Rohdaten
:position: 90
:url: daten
:id: PXLNINJ
:nav-alias: Übersicht
:author: team-plenty-channel

Dieser Themenbereich befasst sich mit dem Datenaustausch in plentymarkets. Daten können automatisch oder manuell ausgetauscht werden. Für den Austausch von Daten zwischen deinem plentymarkets System und externen Systemen stehen dir die link:https://developers.plentymarkets.com/[REST-API^]{nbsp}icon:external-link[] und Untermenüs im Menü **Datenaustausch** zur Verfügung. **ElasticSync** dient dem manuellen Austausch von Daten. Im API-Log kannst du anhand von xref:daten:api-log.adoc#[Log-Einträgen] den Datenaustausch nachvollziehen.

Nutze den Datenaustausch außerdem, um systemintern Einstellungen einfach und zeitsparend anzupassen. Einfach Daten zu Artikeln, Kund:innen, Warenbeständen oder Aufträgen in eine CSV-Datei exportieren, in der Datei anpassen und anschließend importieren.

[.row]
====
[.col-md-4]
.Datenaustausch
=====
* xref:daten:ElasticSync.adoc#[Import-Tool nutzen]
* xref:daten:FormatDesigner.adoc#[Datenformate mit FormatDesigner erstellen]
* xref:daten:elastischer-export.adoc#[Daten mit dem Elastischen Export exportieren]
* xref:business-entscheidungen:reports-verwalten.adoc#[Rohdaten exportieren]
=====

[.col-md-4]
.Schnittstellen
=====

* link:https://developers.plentymarkets.com/[REST-API^]{nbsp}icon:external-link[]
* *Deprecated*: link:{imagesdir}/business-entscheidungen/assets/SOAP-Version-200-Documentation-2016-07-14.zip[SOAP API]{nbsp}icon:external-link[]
=====

[.col-md-4]
.Protokolle

* *Deprecated* xref:daten:api-log.adoc#[API-Log]
=====
====
