= Daten-Log
:keywords: Log, Logs, Datenlog, Log-Einträge, Logeintrag, Log-Level, Referenztyp, Referenzwert, Logs konfigurieren
:description: Erfahre, wie du nach Log-Einträgen suchen kannst.
:id: 8PM1DPV
:author: team-plenty-channel

Im Menü unter *Daten » Log* werden alle Log-Einträge angezeigt. Diese Log-Einträge sind für vier Wochen verfügbar, bevor die Einträge gelöscht werden. Logs können einzeln aktiviert werden und zusätzlich kann für jeden Log-Eintrag die Dauer eingestellt werden, mit der festgelegt wird, wie lange der Log-Eintrag aktiv bleiben soll.

== Was ist das Daten-Log?

Daten-Log bedeutet auf Deutsch "Datenprotokoll". Im Daten-Log werden also Ereignisse protokolliert, die in deinem System stattfinden.

* Jeder Log-Eintrag steht für ein Ereignis in deinem System.
* Jeder Log-Eintrag ist ab dem Ereignis vier Wochen verfügbar. Danach wird der Log-Eintrag automatisch gelöscht.
* Ereignisse mit den Log-Levels *Error*, *Critical*, *Alert* und *Emergency* werden automatisch protokolliert.
* Die Log-Level *Debug*, *Info*, *Notice* und *Warning* müssen aktiviert werden, damit Ereignisse dieser Levels protokolliert werden. (<<#10, Wie?>>)
* Jeder Log-Eintrag enthält die folgenden Informationen über das Ereignis:

[cols="1,2"]
|====
| *Zeitstempel*
| Das Datum und die Uhrzeit des Ereignisses

| *Level*
| Der Schweregrad des Ereignisses +
(<<#log-levels, Was beuten die Log-Level?>>)

| *Integration*
| Der Bereich, in dem das Ereignis stattgefunden hat

| *Identifikator*
| Der Unterbereich, in dem das Ereignis stattgefunden hat

| *Referenz*
| Der Referenztyp mit der entsprechenden ID

| *Nachricht*
| Eine Beschreibung des Ereignisses

| *Log-Details* +
(in separatem Fenster)
| Klicke auf einen Log-Eintrag, um die Detailansicht zu öffnen. Hier findest du weitere Informationen zum Ereignis. In diesem Fenster kannst du auch zum vorherigen oder zum nächsten Log-Eintrag springen. Außerdem kannst du die Informationen einklappen oder ausklappen.
|====

[#10]
== Optionale Protokollierung aktivieren

Ereignisse mit den Log-Levels *Error*, *Critical*, *Alert* und *Emergency* werden automatisch protokolliert.
Damit aber Ereignisse mit den Log-Levels *Debug*, *Info*, *Notice* und *Warning* protokolliert werden, muss die Protokollierung erst aktiviert werden.

* Die Protokollierung endet nach der eingestellten Dauer automatisch.

[.instruction]
Optionale Protokollierung aktivieren:

. Öffne das Menü *Daten » Log*. +
→ Alle protokollierten Ereignisse des Standard-Mandanten werden angezeigt.
. Klicke oben links in der Toolbar auf *Logs konfigurieren* (icon:cog[]). +
→ Das Fenster *Log-Konfiguration* wird geöffnet. +
→ Auf der linken Seite werden die Systembereiche und die installierten Plugins angezeigt.
. Wähle den Bereich, in dem du Logs konfigurieren möchtest. +
→ Auf der rechten Seite werden die Einstellungen für  diesen Bereich angezeigt.
. Aktiviere die Option *Aktiv*.
. Wähle in der Dropdown-Liste *Dauer*, wie lange Ereignisse für diesen Bereich protokolliert werden sollen.
. Wähle in der Dropdown-Liste *Log-Level*, welche Ereignisse du protokollieren möchtest. +
<<#log-levels, Was beuten die Log-Level?>>
. Speichere (icon:save[role="green"]) die Einstellungen. +
→ Die Protokollierung wird gestartet. +
→ Die Protokollierung endet nach der eingestellten Dauer automatisch. +
*_Wichtig:_* Wann der erste Log-Eintrag verfügbar ist hängt davon ab, wann das Ereignis das nächste Mal auftritt, das du protokollierst.

[#20]
== Liste der Log-Einträge filtern

Wenn du das Menü *Daten » Log* öffnest, wird eine Liste aller protokollierten Ereignisse für den Standardmandanten angezeigt. Diese Liste ist nach Datum und Uhrzeit des Ereignisses sortiert: Das neueste Ereignis steht ganz oben.

Um die Liste der Ereignisse zu reduzieren und übersichtlicher zu machen, kannst du die Log-Einträge filtern.

[.instruction]
Liste der Log-Einträge filtern:

. Öffne das Menü *Daten » Log*. +
→ Alle protokollierten Ereignisse des Standard-Mandanten werden angezeigt.
. Klicke oben links in der Symbolleiste auf icon:filter[set=material]. +
→ Die verfügbaren Filter werden angezeigt.
. Setze die gewünschten Filter. Beachte dazu die Erläuterungen in <<#log-filter>>. +
*_Fehlt ein Filter in den Dropdown-Listen?_* +
Die Dropdown-Listen enthalten nur Filter für Ereignisse, für die es auch Log-Einträge gibt. Wenn also zum Beispiel in der Liste kein eintrag für *OTTO Market* wählbar ist, wurden in den letzten vier Wochen keine Ereignisse für diesen Marktplatz protokolliert.
. Klicke auf icon:search[role="blue"] *Suchen*. +
→ Die Log-Einträge werden gefiltert angezeigt.

[[log-filter]]
.Verfügbare Filter
[cols="1,3a"]
|===
|Filter |Erläuterung

| *Mandant*
| Standardmäßig ist als Filter der Standard-Mandant eingestellt. Einen anderen Mandanten aus der Dropdown-Liste wählen, um Ereignisse für diesen Mandanten anzuzeigen.

| *Integration*
|

| *Identifikator*
| Der Identifikator gibt an, zu welchem Unterbereich der Log gehört.

| *Level*
| Ein Level aus der Dropdown-Liste wählen. +
→ Nur

*_Hinweis:_* Hierfür müssen bereits alle Level aktiv gesetzt sein.

| *Referenztyp*
| Hier wird der Referenztyp angegeben, zu dem der Eintrag gehört (z.B. VariationID, OrderID etc.).

| *Referenzwert*
| Hier wird der Wert der Referenz angegeben. Beispielsweise wäre das beim Referenztyp *ItemID* der Wert dieser ID. Die Suchergebnisse werden auf Treffer mit diesem Wert reduziert.

| *Datum vom*
| Auf das Kalendersymbol klicken, um ein Datum zu wählen. +
→ Nur Ereignisse ab diesem Datum werden in der Liste angezeigt. +
*_Hinweis:_* Du kannst ein beliebiges Datum wählen. Beachte jedoch, dass nur Ereignisse der letzten vier Wochen angezeigt werden können. Nach vier Wochen werden Log-Einträge automatisch gelöscht.

| *Uhrzeit von*
| Uhrzeit im Format HH:MM:SS eingeben. +
→ Wenn du ein *Datum vom* wählst, werden Ereignisse ab dieser Uhrzeit am gewählten Datum angezeigt. +
→ Wenn du kein *Datum vom* wählst, werden Ereignisse ab dieser Uhrzeit am heutigen Tag angezeigt.

| *Datum bis*
| Auf das Kalendersymbol klicken, um ein Datum zu wählen. +
→ Nur Ereignisse bis einschließlich diesem Datum werden in der Liste angezeigt. +
*_Hinweis:_* Du kannst ein beliebiges Datum wählen. Beachte jedoch, dass nur Ereignisse der letzten vier Wochen angezeigt werden können. Nach vier Wochen werden Log-Einträge automatisch gelöscht.

| *Uhrzeit bis*
| Uhrzeit im Format HH:MM:SS eingeben. +
→ Wenn du ein *Datum bis* wählst, werden Ereignisse bis einschließlich dieser Uhrzeit am gewählten Datum angezeigt. +
→ Wenn du kein *Datum bis* wählst, werden Ereignisse bis einschließlich dieser Uhrzeit am heutigen Tag angezeigt.
|===

[#log-levels]
== Bedeutung der Log-Levels

[[tabelle-bedeutung-log-level]]
.Bedeutung der verschiedenen Log-Level
[cols="1,4,1"]
|====
|Log-Level |Bedeutung |Standardmäßig aktiviert

| *Debug*
| Detaillierte Statusmeldungen
| Nein

| *Info*
| Allgemeine Informationen zum System
| Nein

| *Notice*
| Eine zu klärende, aber nicht dringende Fehlermeldung.
| Nein

| *Warning*
|E twas läuft nicht wie gewünscht. Es muss sich aber nicht um einen Fehler handeln.
| Nein

| *Error*
| Standard-Systemfehler; bei Fehlern läuft das System in der Regel weiter.
| Ja

| *Critical*
| Diese Fehler können zum Systemabsturz führen.
| Ja

| *Alert*
| Es muss sofort reagiert werden. +
*_Beispiel:_* Webshop oder Datenbank sind nicht erreichbar.
| Ja

| *Emergency*
| Absoluter Notfall. Das gesamte System funktioniert nicht.
| Ja
|====
