= Daten exportieren
:keywords: Export, ElasticExport, Elastischer Export, FormatDesigner, Katalog, Kataloge, Daten exportieren, Daten übertragen, Daten übermitteln, Artikel exportieren, Datenexport, Artikelexport, Produkte an Marktplätze übertragen, Artikel an Marktplätze übertragen
:description: Erfahre mehr über die verschiedenen Tools, mit denen du Daten aus deinem plentymarkets System exportieren kannst.
:author: team-plenty-channel

Es gibt viele Gründe, Daten aus deinem plentymarkets System zu exportieren.
Vielleicht willst du zum Beispiel:

* deine Artikel- und Variantendaten an Marktplätze übertragen.
* eine CSV-Datei exportieren, die mit Produktdaten, Lagerdaten, Auftragsdaten usw. gefüllt ist.
Die Datei kannst du anschließend überarbeiten und wieder importieren.

Diese Seite stellt die unterschiedlichen Tools dafür kurz vor. Klicke auf die Links, um ausführlichere Informationen über die Tools zu lesen.

== Elastischer Export

Der elastische Export ist ein kostenloses Plugin, das du von plentyMarketplace herunterladen und zu deinem System hinzufügen kannst.

Je nachdem, was du erreichen willst, gehst du unterschiedlich vor:

[tabs]
====
Produkte an Marktplätze übertragen::
+
--

. Lade die nötigen Plugins herunter:
.. Elastischer Export
.. Sogenannte Datenformat-Plugins für deine gewünschten Marktplätze
. Richte den elastischen Export ein.
Wähle dabei das Datenformat für den entsprechenden Marktplatz aus.
. Übertrage die CSV-Datei an den Marktplatz.

--
Daten exportieren, überarbeiten, neu importieren::
+
--

. Lade die nötigen Plugins herunter:
.. Elastischer Export
.. FormatDesigner
. Erstelle sogenannte Datenformate mit Hilfe des FormatDesigners.
. Richte den elastischen Export ein.
Wähle dabei das soeben erstellte Datenformat aus.
. Exportiere die CSV-Datei, überarbeite diese und importiere sie wieder in plentymarkets.

--
====

[discrete]
=== Vorteile und Nachteile des elastischen Exports

* *_Vorteil_*: Kann mit vielen verschiedenen Marktplätzen verwendet werden.

* *_Nachteil_*: Ältere Technologie, die schrittweise durch den Katalog ersetzt wird.


[discrete]
=== Weiterführende Informationen

[.row]
====
[.col-md-6]
.Elastischer Export
=====
* link:https://marketplace.plentymarkets.com/plugins/sales/marktplaetze/elasticexport_4763[Plugin: Elastischer Export^]
* xref:daten:elastischer-export.adoc#[Einrichung und Verwendung]
* xref:daten:best-practices-elastischer-export.adoc#[Fehlerbehebung]
* xref:daten:dropshipping-elasticexport-bp.adoc#[Praxisbeispiel]
=====

[.col-md-6]
.FormatDesigner
=====
* link:https://marketplace.plentymarkets.com/formatdesigner_6483[Plugin: FormatDesigner^]
* xref:daten:FormatDesigner.adoc#[Eigene Datenformate erstellen]
* xref:daten:format-typen.adoc#[Liste der verfügbaren Formattypen]
=====
====

== Kataloge

Kataloge dienen dazu, Daten für den Export im Vorhinein ideal vorzubereiten.
Dieses Tool ist noch relativ neu in plentymarkets.
Weitere Funktionen werden laufend hinzugefügt.
Aktuell kannst du den Katalog nutzen, um Daten an die Marktplätze Amazon, Etsy, Metro und OTTO Market zu übertragen.
Es gibt auch eine Demo-Funktion, mit der du Artikeldaten exportieren, überarbeiten und wieder importieren kannst.

Je nachdem, was du erreichen willst, gehst du unterschiedlich vor:

[tabs]
====
Produkte an Märkte übertragen::
+
--

. Erstelle einen Katalog. Wähle dabei das Marktplatz-Format als Exporttyp aus.
. Ordne deine plentymarkets Datenfelder den Datenfeldern des Marktplatzes zu.
. Entscheide wann und wie deine Daten übertragen werden sollen und aktiviere den Katalog.

--
Daten exportieren, bearbeiten, neu importieren::
+
--

. Erstelle einen Katalog. Wähle dabei das Standard-Format als Exporttyp aus.
. Entscheide, welche plentymarkets Datenfelder die CSV-Datei enthalten soll.
. Exportiere die CSV-Datei, überarbeite diese und importiere sie wieder in plentymarkets.

--
====


[discrete]
=== Vorteile und Nachteile des Katalogs

*_Vorteile_*:

* Vorgegebene Datenstruktur:
Der Marktplatz gibt vor, welche Produktdaten benötigt werden.
Du ordnest lediglich deine plentymarkets Datenfelder den erwarteten Daten zu.
* Ausweich-Datenfelder:
Du entscheidest, welches Datenfeld als Ersatz verwendet werden soll, wenn ein bestimmtes Feld in plentymarkets nicht vorhanden ist.
* Datenfelder kombinieren: Du kannst Datenfelder miteinander kombinieren und entscheiden, welches Trennzeichen dazwischen verwendet werden soll.
Zum Beispiel: Name 1 + Name 2.

*_Nachteile_*:

* Noch nicht mit allen Märkten kompatibel.
* Derzeit nur ein Demo-Standardformat verfügbar.
Langfristig soll der Katalog den elastischen Export ersetzen.
Vorher müssen jedoch alle Standardformate und Exportfilter in den Katalog implementiert werden.

[discrete]
=== Weiterführende Informationen

[.row]
====
[.col-md-6]
.Kataloge
=====
* xref:daten:kataloge.adoc#[Einrichung und Verwendung]
=====
====
