= Daten
:keywords: Daten, Datenaustausch, ElasticSync, FormatDesigner, Elastischer Export, Rohdaten
:author: team-plenty-channel
:page-index: false

Dieser Themenbereich befasst sich mit dem Datenaustausch in plentymarkets. Daten können automatisch oder manuell ausgetauscht werden. Für den Austausch von Daten zwischen deinem plentymarkets System und externen Systemen stehen dir die link:https://developers.plentymarkets.com/[REST-API^] und Untermenüs im Menü **Datenaustausch** zur Verfügung. Das Import-Tool dient dem manuellen Austausch von Daten.

Nutze den Datenaustausch außerdem, um systemintern Einstellungen einfach und zeitsparend anzupassen. Einfach Daten zu Artikeln, Kund:innen, Warenbeständen oder Aufträgen in eine CSV-Datei exportieren, in der Datei anpassen und dann wieder importieren.

*Import*

* xref:daten:ElasticSync.adoc#[Import-Tool nutzen]

*Export*

* xref:daten:FormatDesigner.adoc#[Datenformate mit FormatDesigner erstellen]
* xref:daten:elastischer-export.adoc#[Daten mit dem Elastischen Export exportieren]
* xref:business-entscheidungen:reports-verwalten.adoc#[Rohdaten exportieren]
