= Zuordnung Zolltarifnummer
:keywords: Zuordnung Zolltarifnummer, Taricimport, Taric-Import, Zolltarifnummernimport
:author: team-order-core
:description: Datenimport: Zolltarifnummern können in plentymarkets importiert werden. Diese Seite dient als Referenz und listet die dafür verfügbaren Abgleich- und Zuordnungsfelder.

//optional - add extra sentences between the brackets in einleitung-weitere-info if you want to have further info in your introduction
:einleitung-daten: pass:quotes[Zolltarifnummern]
:einleitung-weitere-info: pass:quotes[]
:abgleich-tabelle: <<table-mapping-taric>>
:abgleich-daten: pass:quotes[Zolltarifnummern]
:zuordnung-daten: pass:quotes[Zolltarifnummern]
:zuordnung-standardwert: pass:quotes[die Zolltarifnummer]

include::partial$einleitung.adoc[]

Mit einem Import des Typs *Zuordnung Zolltarifnummer* importierst du Daten für die Zolltarifnummerntabelle im Menü *Einrichtung » Mandant » Global » Zolltarifnummern*. Damit die Zuordnung der Zolltarifnummern zu Varianten und Steuersätzen hinterher im System funktioniert, müssen an den entsprechenden Varianten Zolltarifnummern hinterlegt sein. Um Zolltarifnummern an Varianten per Import zu hinterlegen, gehe zum xref:daten:elasticSync-artikel.adoc#2300[Import-Typ Artikel].

[#10]
== Felder für den Abgleich

include::partial$abgleich.adoc[]

[[table-mapping-taric]]
.Abgleichfelder für Zolltarifnummernimport
[cols="1,3"]
|===
|Einstellung |Erläuterung

|*Zolltarifnummer*
|In welcher Spalte deiner CSV-Datei werden Zolltarifnummern aufgelistet? Wähle diese Spalte hier. +
Mehr Informationen über Zolltarifnummern findest du im Abschnitt xref:auftraege:buchhaltung.adoc#620[Zolltarifnummern] im Handbuch.

|*Land*
|In welcher Spalte deiner CSV-Datei werden Länder aufgelistet? Wähle diese Spalte hier. +
Trage die Länder in deiner CSV-Datei entweder anhand der *Country-ID* oder anhand des *IsoCodes* ein. Beides findest du im Abschnitt xref:daten:interne-IDs.adoc#20[Länder]  im Handbuch.

|===

[#20]
== Felder für die Zuordnung

include::partial$zuordnung.adoc[]

[#30]
=== Zuordnung

[#40]
==== Umsatzsteuer

Welche Umsatzsteuer soll zugewiesen werden? Gib diesen Umsatzsteuersatz abgebildet durch eine Zahl in deine CSV-Datei ein. +
Steuersatz A = 0 +
Steuersatz B = 1 +
Steuersatz C = 2 +
Steuersatz D = 3 +
Steuersatz E = 4 +
Steuersatz F = 5

*_Standardwert_*: Kein Standardwert

*_Zulässige Importwerte_*: Numerisch

Das Ergebnis des Imports findest du im Backend im Menü *Einrichtung » Mandant » Global » Zolltarifnummern*.

[#50]
==== Löschen

Entscheide, ob eine bereits bestehende Zuordnung zwischen einem Umsatzsteuersatz, einer Zolltarifnummer und einem Land gelöscht werden soll.

*_Standardwert_*: Kein Standardwert

*_Zulässige Importwerte_*: Numerisch

[[table-delete-taric-data]]
[cols="1,1"]
|===
|Zulässige Importwerte in CSV-Datei |Optionen in der Dropdown-Liste im Backend

|`0`
|Nicht löschen

|`1`
|Löschen
|===

Das Ergebnis des Imports findest du im Backend im Menü *Einrichtung » Mandant » Global » Zolltarifnummern*.
