= SerialKeys
:page-index: false
:id: YM58IAX
:author: team-item

Das Datenformat **SerialKeys** wird verwendet, um Seriennummern zu exportieren.
Du erstellst und exportierst das Datenformat im Menü **Daten » Dynamischer Export**.
Wie du das Datenformat exportierst, ist auf der Handbuchseite xref:daten:alte-tools-daten-exportieren.adoc#[Daten exportieren] beschrieben.

Achte auf die exakte Schreibweise der Datenfelder, da die Daten sonst nicht verarbeitet werden können.

== Übersicht der Datenfelder

Tabelle 1 erläutert die Datenfelder des Datenformats **SerialKeys** in alphabetischer Reihenfolge sowie die Filteroptionen, die du im Tab **Filter** des Datenformats vornimmst.

.Datenfelder des Datenformats **SerialKeys**
[cols="1,3,3"]
|===
|Feldname |Erläuterung |Filter

| **ItemID**
|Artikel-ID
|Filter aktivieren, Operator wählen und Wert eingeben.

| **OrderID**
|Auftrags-ID
|

| **OrderRowID**
|Auftrags-ID der Artikelposition
|

| **SerialKey**
|Seriennummer
|

| **ID**
|ID der Seriennummer
|
|===

== Übersicht der Pflichtfelder

Das folgende Pflichtfeld muss für das Datenformat **SerialKeys** vorhanden sein und ein gültiger Wert muss eingegeben sein:

* ItemID

== Übersicht der Abgleichfelder

Das in Tabelle 2 aufgelistete Datenfeld steht zum xref:daten:alte-tools-daten-exportieren.adoc#20[Datenabgleich] zur Verfügung. Bei diesem Pflichtabgleichfeld muss für die **Importaktion** die Option **Abgleich** gewählt werden.

.Datenfelder mit Einstellung auf die Option **Abgleich**
[cols="1,3"]
|===
|Feldname |Erläuterung

| **ID**
|ID der Seriennummer
|===
