= VariationMarketLink
:page-index: false
:id: XTK27MX
:author: team-item

Mit dem Datenformat **VariationMarketLink** verknüpfst du Varianten mit Marktplätzen, damit diese für den Marktplatz verfügbar sind.
Du erstellst und exportierst das Datenformat im Menü **Daten » Dynamischer Export**.
Wie du das Datenformat exportierst, ist auf der Handbuchseite xref:daten:alte-tools-daten-exportieren.adoc#[Daten exportieren] beschrieben.

Achte auf die exakte Schreibweise der Datenfelder, da die Daten sonst nicht verarbeitet werden können.

== Übersicht der Datenfelder

Tabelle 1 erläutert die Datenfelder des Datenformats **VariationMarketLink** in alphabetischer Reihenfolge sowie die Filteroptionen, die du im Tab **Filter** des Datenformats vornimmst.

.Datenfelder des Datenformats **VariationMarketLink**
[cols="1,3,3"]
|===
|Feldname |Erläuterung |Filter

| **VariationID**
|Varianten-ID
|Filter aktivieren, Operator wählen und Wert eingeben.

| **VariationCustomNumber**
|Variantennummer
|

| **Mandant (Shop)**
|Sichtbarkeit des Mandanten (Shop). +
**VISIBLE** = Variante ist auf dem Marktplatz verfügbar. +
**INVISIBLE** = Variante ist nicht auf dem Marktplatz verfügbar.
|Filter aktivieren und Wert aus der Dropdown-Liste wählen.
|===

== Übersicht der Pflichtfelder

Die folgenden Pflichtfelder müssen für das Datenformat **VariationMarketLink** vorhanden sein und ein gültiger Wert muss eingegeben sein:

* **VariationID** = ID der Variante
* Marktplatz, der importiert werden soll

== Übersicht der Abgleichfelder

Die in Tabelle 2 aufgelisteten Datenfelder stehen zum xref:daten:alte-tools-daten-exportieren.adoc#20[Datenabgleich] zur Verfügung. Es handelt sich um Pflichtabgleichfelder. Bei Pflichtabgleichfeldern muss für die **Importaktion** die Option **Abgleich** gewählt werden.

.Datenfelder mit Einstellung auf die Option **Abgleich**
[cols="1,3"]
|===
|Feldname |Erläuterung

| **VariationID**
|ID der Variante

|Marktplatz
|Marktplatz wählen, der importiert werden soll
|===
