= Zahlungen
:keywords: Zahlungen exportieren, Export-Format Zahlungen
:description: Erfahre, wie du mithilfe von Katalogen Zahlungen aus deinem plentymarkets System exportierst.
:page-aliases: katalog-zahlungen.adoc
:id: W8ZJUWG
:author: team-payment

Diese Handbuchseite enthält Informationen zum Export-Format *Zahlungen*, mit dem du anhand von Katalogen Zahlungen aus deinem plentymarkets System exportieren kannst.
Solltest du mit der Funktionsweise der Kataloge noch nicht vertraut sein, informiere dich zunächst auf der Handbuchseite xref:daten:dateiexport.adoc#[Standardformate nutzen]. Dort ist beschrieben, wie du Kataloge erstellst und verwaltest.

[discrete]
==== Format-Typ: Zahlungen

Der auf dieser Seite beschriebene Format-Typ befindet sich im Menü *Daten » Kataloge*.
Beim Erstellen eines neuen Katalogs wählst du zuerst das Standardformat aus der oberen Dropdown-Liste.
Danach kannst du den Format-Typ *Zahlungen* aus der mittleren Dropdown-Liste wählen.

[TIP]
.Kein Export an Marktplätze
====
Bei dem Exportformat *Zahlungen* handelt es sich um ein sog. Standardformat, d.h. ein Format, mit dem du Daten aus deinem System exportieren, aber nicht an einen Marktplatz übertragen kannst.
====

[TIP]
.Export keys anpassen
====
Links neben einem hinzugefügten Datenfeld kannst du einen *Export key* vergeben. Der Export key ist der Name, unter dem die Werte des entsprechenden Datenfelds in deiner Exportdatei exportiert werden. Du kannst bei Bedarf den Export key anpassen. +
Stelle immer sicher, dass der Export key einzigartig ist, z.B. bei mehrmaligem Hinzufügen eines Datenfelds mit verschiedener Auswahl. Ist der gleiche Export key mehrmals vergeben, wird immer nur das letzte hinzugefügte Datenfeld mit diesem Export key exportiert. +
Mehr Informationen zu Datenfeldern allgemein findest du im Handbuchkapitel xref:daten:dateiexport.adoc#add-fields[Datenfelder zu Export hinzufügen].
====

[#10]
== Verfügbare Datenfelder

In der folgenden Tabelle findest du alle verfügbaren Datenfelder des Export-Formats *Zahlungen* sowie eine Erläuterung zur Bedeutung dieser Felder.

[[tabelle-datenfelder-zahlungen]]
.Datenfelder für Zahlungen
[cols="2,3"]
|===
|Datenfeld |Erläuterung

2+^|*Zahlung*

|*Zahlungs-ID*
|ID der Zahlung

|*Betrag*
|Betrag der Zahlung

|*Ist Systemwährung*
|Gibt an, ob die Zahlung in der Systemwährung oder einer anderen Währung getätigt wurde.

|*Währung*
|Währung der Zahlung

|*Wechselkurs*
|Wechselkurs der Zahlung

|*Eingangsdatum*
|Datum des Zahlungseingangs

|*Importdatum*
|Datum des Zahlungsimports

|*Zahlungsart-ID*
|ID der Zahlungsart

|*Eltern-ID*
|Übergeordnete ID

|*Soll / Haben*
|Zahlungseingänge mit negativem oder positivem Wert

|*Zahlungsstatus*
|Status der Zahlung

|*Transaktionstyp*
|Typ der Transaktion

|*Zahlungseigenschaft*
|Eigenschaft der Zahlung. Wähle eine Eigenschaft aus der Dropdown-Liste.

2+^|*Relation*

|*ID*
|ID der Relation. Wähle den Relationstyp *Auftrag* oder *Kontakt*.

|*Zuordnungsdatum*
|Datum, an dem die Zahlung zugeordnet wurde. Wähle den Relationstyp *Auftrag* oder *Kontakt*.

|===

[#20]
== Filter hinzufügen

Um nur bestimmte Zahlungen zu exportieren, kannst du Filter wählen und somit die Daten eingrenzen. Wie du Filter hinzufügst, erfährst du in xref:daten:standardformate-exportieren.adoc#filter-data[diesem Kapitel].

[#30]
=== Verfügbare Filter

In der folgenden Tabelle findest du alle für das Export-Format *Zahlungen* verfügbaren Filter sowie eine Erläuterung zur Funktion des jeweiligen Filters.

[[tabelle-filter-zahlungen]]
.Filter für Zahlungen
[cols="2,3"]
|===
|Filter |Erläuterung

|*Transaktions-ID*
|Filtert nach Zahlungen mit dieser Transaktions-ID.

|*Zahlungsart-ID*
|Filtert nach Zahlungen mit dieser Zahlungsart-ID.

|*Soll / Haben*
|Filtert nach Zahlungen mit Soll / Haben. Wähle zwischen Soll und Haben. +
*Soll* = Alle Zahlungseingänge mit negativem Wert werden angezeigt. +
*Haben* = Alle Zahlungseingänge mit positivem Wert werden angezeigt.

|*Betrag*
|Filtert nach Zahlungen mit diesem Betrag. Wähle dazu einen Operator und gib einen Betrag ein.

|*Zuordnung*
|Filtert nach Zahlungen mit dieser Zuordnung. +
Wähle *Zugeordnet*, um nach Zahlungen zu filtern, die einem Auftrag zugeordnet sind. +
Wähle *Nicht zugeordnet*, um nach Zahlungen zu filtern, die keinem Auftrag zugeordnet sind.

|*Zahlungsstatus*
|Filtert nach Zahlungen mit diesem Zahlungsstatus. Wähle einen der verfügbaren Status aus der Dropdown-Liste.

|*Transaktionstyp*
|Filtert nach Zahlungen mit diesem Transaktionstyp. Wähle *Vormerkposten* oder *Standardposten*.

|*Währung*
|Filtert nach Zahlungen mit dieser Währung. Wähle eine der verfügbaren Währungen aus der Dropdown-Liste.

|*Importdatum*
|Filtert nach Zahlungen mit diesem Importdatum. Wähle einen Zeitraum oder ein Datum.

|*Eingangsdatum*
|Filtert nach Zahlungen mit diesem Eingangsdatum. Wähle einen Zeitraum oder ein Datum.

|*Zuordnungsdatum*
|Filtert nach Zahlungen mit diesem Zuordnungsdatum. Wähle einen Zeitraum oder ein Datum.

|===
