Items have to be available for Amazon country platforms. This is done in the *Availability* tab of an item within the *Item » Edit item » [Open item] » [Open variation]* menu.

[TIP]
.Use group function or batch processing
====
You can edit the availability of several variations at once by using either the <<item/import-export-create/create/mass-processing#100, variation group function>> or <<item/import-export-create/create/mass-processing#400, batch processing>>.
====

[.instruction]
Activating the variation availability for an Amazon country platform:

. Go to *Item » Edit item » [Open item] » [Open variation]*. +
→ The *Settings* tab of the variation opens. +
*_Tip:_* To sell all variations of an item on the Amazon platform, carry out the settings for the item’s main variation. This activates the availability of all variations of the item.
. In the *Availability* area, activate the option *Active*.
. Click on the *Availability* tab.
. In the *Markets* area, click in the selection field. +
→ A list of all available markets is displayed.
. Select the Amazon country platform(s) for which the variation should be available.
. Activate the option *Web API*.
. Click on *Add* (icon:plus-square[role="green"]). +
→ The market is added.
. Save (icon:save[set=plenty]) the settings.
. Click on the *Multi-Channel* tab.
. Carry out the settings in the *Amazon* area. Pay attention to the explanations given in <<#item-availability-amazon>>.
. Save (icon:save[set=plenty]) the settings.

[[item-availability-amazon]]
.Activating the variation availability for Amazon
[cols="1,3a"]
|====
| Setting | Explanation

| *Product type*
|
//tag::product-type[]
Select the appropriate Amazon product type from the drop-down list.
//end::product-type[]
//tag::product-type-export[]
You can think of the product type as the Amazon category under which this item should appear.
<<markets/amazon/variation-export#, When you transmit your items to Amazon>>, you’ll transmit one product type at a time, i.e. one category at a time.
//end::product-type-export[]

//tag::product-type-note[]
*_Note_*: You can download an overview of Amazon product types link:https://cdn02.plentymarkets.com/pmsbpnokwu6a/frontend/plenty_article_amazon_type.csv[here^]{nbsp}icon:external-link[].
The table lists the product types and their corresponding IDs.
//end::product-type-note[]

| *FBA Fulfillment*
|
//tag::fba-fulfillment[]
Should the item be sold via FBA?
If so, then select the appropriate Amazon marketplace from the drop-down list.

* *AMAZON_EU* = Europe
* *AMAZON_FE* = Far East
* *AMAZON_NA* = North America
//end::fba-fulfillment[]

| *Amazon FBA*
|
//tag::amazon-fba[]
Should the item be sold via FBA?
If so, then select this option (icon:check-square[role="blue"]).
//end::amazon-fba[]

//tag::amazon-fba-note[]
*_Note_*: By doing so, the FBA stock of this item can be imported into plentymarkets and Amazon Multi-Channel orders that are shipped with FBA can be booked.
//end::amazon-fba-note[]
|====

[IMPORTANT]
.Variation availability for MFN and FBA
====
In order to set up variations for MFN as well as FBA, select the Amazon country platform *Amazon country* and the platform *Amazon country FBA*.
====
