You have to save some information in your plentymarkets categories in order for your items to automatically be assigned to the existing categories when exporting them to Amazon. The so called Browse Tree Guides (BTG) from Amazon provide you with classification information. This information is provided in table format (MS Excel) and contains unique classification numbers, the so called Browse Node IDs, which you will have to assign to your plentymarkets categories. The lists are available in the help centre of the Seller Central or via this link:https://sellercentral-europe.amazon.com/gp/help/help-folder.html/?ie=UTF8&itemID=1661[link^].

Using the official Browse Tree Guides for the Amazon platform that you want to sell your products on ensures that your items can be found quickly and easily in the Amazon catalogue. The Browse Node IDs form the basis for the item/product assignment in the navigation as well as in the product search. Due to the large amount of items offered on Amazon, an explicit assignment of your items into these Browse Node IDs determines whether a customer will find your product in the corresponding category or not. Therefore, we recommend that you take some time when carrying out this next step and that you select the Browse Node IDs carefully.

Go to *Setup » Markets » Amazon » Category link* to link categories. In plentymarkets, you can link each item category with up to two Amazon classification numbers from the Browse Tree Guides.

It is absolutely necessary that you link the entered values separately line by line.

The category links are only taken into consideration for the default categories, which were selected for an item under *Item » Edit item » [Open item] » Tab: Categories*.

[.instruction]
Linking Amazon categories:

. Use this link:https://sellercentral-europe.amazon.com/gp/help/help-folder.html/?ie=UTF8&itemID=1661[link^] to access the help centre within Seller Central.
. Select the desired classification list, e.g. apparel.
. Look up the desired category name in the *node path* column (e.g. blouse).
. Go to *Setup » Markets » Amazon » Category link* in your plentymarkets back end.
. Enter the corresponding Browse Node ID from the list into the table.
. Click on the *gear-wheel icon* that corresponds to the category that you want to link.

[IMPORTANT]
.Exporting the Browse Node ID
====
The Browse Node ID that was assigned when selecting the category is inserted into the *RecommendedBrowseNode1* field during the data export. The *RecommendedBrowseNode2* field is only used for categories that are linked multiple times.
====
