Set up the market in plentymarkets in the *Setup » Markets » Amazon » New settings* menu. +
You can add several Amazon accounts with different settings.

// Account or Amazon account

[#new-account]
=== Adding a new account

First, add a new account for Amazon.

[.instruction]
Adding a new account:

. Go to *Setup » Markets » Amazon » New settings*.
. Click on *Add account* (material:add[]). +
→ The *Add account* window opens.
. Select the *region* that you want to use this Amazon account for from the drop-down list.
. Select one or more *channels*. +
*_Note:_* Channels are Amazon’s sales channels (countries, for example amazon.co.uk) on which you can offer your items. Which channels can be selected here depends on the selected region.
. Enter an *account name*. +
*_Note:_* The name can be freely selected, but it has to be unique. This means that you cannot assign the same name to two different accounts.
. Click on *Save*. +
→ A view with further settings opens.
. Carry out the additional settings. Pay attention to the explanations given in <<#basic-settings-amazon>>.
. Save (terra:save[]) the settings.

[[basic-settings-amazon]]
.Settings for the market Amazon
[cols="1,3a"]
|===
|Setting |Explanation

| *Advanced settings*
| Activate to display the advanced settings. +
Advanced settings are settings which you do not necessarily need to set up your Amazon account. However, those settings are very useful and we recommend to take a look at the advanced settings after you carried out the basic settings. +
Advanced settings are available for the areas *MFN*, *FBA*, and for the *channels*.

| material:link[role="blue"] *Connect*
| The account is connected with an Amazon account. +

When you click on material:link[role="blue"] *Connect*, you will be forwarded to Amazon and an Amazon page will open in a new tab. Login to your Amazon seller account using your Amazon access data and grant plentymarkets access to your Amazon account. Once the process is completed and everything went well, the message “Authorisation completed” is displayed. +

If the account is connected with an Amazon account, then the seller ID of the Amazon account is displayed here. +

The account can also be reconnected, if necessary.

2+^| *Account*

| *Account*
| The name of your Amazon account. You entered the name when you created the account.

| *Active*
| Activate the Amazon account. The data exchange with Amazon is started. +

We recommend to only activate the account after you carried out all settings.

*_Note:_* The account has to be connected to an Amazon account so that data can be exchanged between plentymarkets and Amazon. To connect to an Amazon account, click on material:link[role="blue"] *Connect* at the top of the window.

| *Client*
| Select a client (shop). The orders of this Amazon account will be assigned to this client.

| *Activate B2B*
| Do you want to use B2B for this Amazon account? The account will be activated for Amazon Business. This means that you sell your items to business customers. +

*_Note:_* If you want to use Amazon Business, then you need an link:https://business.amazon.co.uk/?ld=NSGoogle_BIZDE&ref_=b2b_reg_search_FAQ_NSGoogle_BIZDE[Amazon Business account^]. 

| *Activate MFN*
| Do you want to use MFN for this Amazon account? +
MFN (= Merchant Fulfillment Network) means that you store and ship your items yourself.

| *Activate FBA*
| Do you want to use FBA for this Amazon account? +
FBA (= Fulfillment by Amazon) means that Amazon stores and ships your items to your customers. Of course, you then have to store at least some of your items with Amazon.

| *Activate VCS*
| Do you use Amazon’s VAT calculation service (VCS = Vat Calculation Service)? +

Select one of the following options: +

* *plentymarkets* = You do not use VCS. plentymarkets calculates the VAT and generates the invoice. You set up an event procedure which uploads the invoices to Amazon via Amazon IDU. See <<#3175, Setting up Amazon IDU>>. +
* *Yes, VCS Lite* = You use VCS. Amazon invoices are automatically generated by plentymarkets and transferred to Amazon. Amazon calculates the VAT. See <<#3150, Setting up VCS plentymarkets>>. +
*_Note:_* VCS must be activated in Amazon Seller Central. +
* *Yes, VCS* = You use VCS. Invoices for Amazon orders are generated by Amazon. +
Invoices for Amazon orders and credit notes are imported into plentymarkets. See <<#6900, Setting up VCS Amazon>>. +
*_Note:_* VCS must be activated in Amazon Seller Central. +

*_Note:_* If you want to use Amazon Business, activate the option *VCS Lite* or *VCS*.

2+^| *Orders*

| *Order import start date*
| Date in the format *DD.MM.YYYY* or select a date via the calendar (material:today[]). +
Only orders starting from this date will be imported into plentymarkets. Orders which were generated before this date will not be imported. +
However, note that orders older than this will be imported into plentymarkets again if they were updated on Amazon. +

This setting applies to both own shipping (MFN) and to shipping by Amazon (FBA).

*_Note:_* Every order that was imported into plentymarkets will be billed.

| *Order import start date*
| You can also enter a time or select a time via (material:schedule[]). +
Only orders starting from this time will be imported into plentymarkets. Orders which were generated before this time will not be imported.

| *Item name in orders*
| Which product name should be shown in order items of Amazon orders? +

*_Possible options:_* +
*Default item name of client*,+
*Item name from Amazon - with SKU*, +
*Item name from Amazon - without SKU*

| *Import credit notes*
| Activate to import credit notes every 4 hours. VCS credit notes are imported once per hour. +

This setting applies to both own shipping (MFN) and to shipping by Amazon (FBA).

| *Products listed with starsellersworld*
| Do you list your items on Amazon with link:https://www.starsellersworld.com/[starsellersworld^]? Then activate this option. +

The item SKU will be cut off right behind the last "-" when importing the items. This makes it possible to match the item in the system.
|===

[#account-overview]
=== Account overview

The *Setup » Markets » Amazon » New settings* menu provides an overview of your Amazon accounts. <<tabelle-konto-uebersicht>> lists the columns and available actions in the account overview.

[TIP]
.Configuring columns
====
Click on *Configure columns* (material:settings[]) to define which settings should be displayed in the account overview. +
The columns *Account name*, *Active*, *Seller ID*, *Connected*, *Client*, *B2B*, *MFN*, *FBA*, and *VCS* are displayed in the overview by default.
====

*_Note:_* The account overview looks different depending on which columns you add or hide via *Configure columns* (material:settings[]). The following table only lists the columns which are displayed in the overview by default.

[TIP]
.Searching for Amazon accounts
====
If you have many Amazon accounts and you cannot find the desired account immediately, then you can use the search to find the account. To do so, enter the *account name*, select the *seller ID* and *region*, and click on *Search* (material:search[role="blue"]).
====

[[table-account-overview]]
.Amazon account overview
[cols="1a,3a"]
|===
|Column |Explanation

| *Account name*
| The name of your Amazon account.

| *Active*
| material:circle[role="blue"] = The account is active and data is exchanged with Amazon. +
material:circle[] = The account is not active. No data is exchanged with Amazon. +

*_Note:_* The data exchange between plentymarkets and Amazon will only work if the account was connected to Amazon. Whether the account is connected is displayed in the column *Connected*.

| *Seller ID*
| The seller ID of your Amazon account. You have received the seller ID from Amazon.

| *Connected*
| material:link[role="blue"] = The account is connected with Amazon. plentymarkets can access your Amazon account and exchange data. +
material:link_off[] = The account is not connected with Amazon. Data cannot be exchanged between plentymarkets and Amazon.

| *Client*
| The client (shop) that orders of this Amazon account are assigned to.

| *B2B*
| material:done[] = You use B2B for this Amazon account (you sell your items to business customers). +
material:close[] = You do not use B2B for this Amazon account.

| *MFN*
| material:done[] = You use MFN (shipment by the seller) for this Amazon account. +
material:close[] =  You do not use MFN for this Amazon account.

| *FBA*
| material:done[] = You use FBA (storage and shipment by Amazon) for this Amazon account. +
material:close[] = You do not use FBA for this Amazon account.

| *VCS*
| material:done[] = Amazon’s VAT calculation service is activated for this Amazon account. In the overview, you can also see whether  you use *VCS* or *VCS Lite*. +
material:close[] = VCS is not activated for this Amazon account.
|===