Proceed as described below to set up Amazon in the setup menu.

==== Setting up the MWS interface

Once you have registered, set up the MWS interface on Amazon. MWS stands for Marketplace Web Service. This service supports API functions. As such, it needs to be set up in order to exchange data with plentymarkets.

Open this link:https://sellercentral.amazon.de/apps/manage[link^]{nbsp}icon:external-link[] and click on *Authorise a developer* to authorise plentymarkets as developer and to allow access to your account. You need the following information for the interface:

*  Developer Nickname: plentymarkets
*  Developer ID for European markets: 6860-7675-7360
*  Developer ID for the US market: 5751-6263-3716

Once you have set up Amazon MWS, you will receive the merchant ID that you need for setting up the interface in plentymarkets.

How to set up the MWS interface at Amazon is also explained in this video tutorial:

.Setting up the MWS interface
video::196421219[vimeo]

[TIP]
.MWS Auth token
====
The MWS Auth Token has an expiration date and has to be activated again in the Seller Central when it has expired.
====

[#200]
[#300]
==== Setting up an Amazon account

Set up a new Amazon account in plentymarkets.

[TIP]
.Set up your Amazon user account with the assistant
====
Use the *Amazon Basic settings* assistant in the *Setup » Assistants » Omni-Channel* menu to set up your Amazon account in plentymarkets quickly and easily. Moreover, you can carry out settings for the data transfer and for Amazon MFN and Amazon FBA with this assistant.
====

[.instruction]
Creating an account:

. Go to *Setup » Markets » Amazon » Settings*.
. Click on *New account*. +
→ The *Create new Amazon Seller Central account* window opens.
. Select an *Amazon platform*.
. Enter the *Email address* that you use for the platform. +
*_Important:_* All plentymarkets email addresses which are used to send messages to Amazon have to be authorised first within your Seller Central account on Amazon.
. Click on *Create new account*. +
→ The account is created.
. Click on the previously created account in the overview on the left.
. Carry out the settings in the *Settings* tab. Pay attention to the explanations given in <<#amazon-tab-settings>>. +
*_Note:_* All *Access data* fields are mandatory.
. Save (icon:save[set=plenty]) the settings.

[[amazon-tab-settings]]
.Settings for *Access data*
[cols="1,3a"]
|====
| Setting | Explanation

| *Amazon platform*
| A platform has to be selected when the account is created. However, the platform can be changed here. If you have a European Marketplaces Account, then you can carry out the settings for each platform on which you want to offer your products separately. For further information, refer to the section <<Setting up an account, Amazon platform>>.

| *Seller ID*
| Enter the seller ID that you have received from Amazon. If you have a European Marketplaces Account, then the same seller ID is used for every platform.

| *Merchant token*
| Enter the merchant token that you can find on Seller Central.

| *Email address*
| Enter the email address that is used as user name for the Seller Central account. +
*_Important:_* All plentymarkets email addresses which are used to send messages to Amazon have to be authorised first within your Seller Central account on Amazon.

| *Active*
| Activate the interface. +
*_Note:_* Only activate once all of the settings have been carried out. This prevents incorrect data from accidentally being transferred.

| *B2B*
| Select to activate this account for Amazon Business.

2+| Area *Initial settings*

| *Client*
| Select which client should be used for orders from Amazon.

| *SKU structure*
| The SKU (Stock Keeping Unit) is a unique reference number for all items and item variations on Amazon. +
Select one of the following options: +
*Variation ID* +
*GTIN if available, otherwise variation ID* +
*Variation number if available, otherwise variation ID* +
The selected setting only goes into effect for items that are exported to Amazon for the first time. Amazon and your plentyShop exchange data based on these SKUs. +
*_Important:_* Do not change this setting after items have been transferred to Amazon. If you do so, communication, e.g. stock updates, between plentymarkets and Amazon will no longer be possible. +
*_Important:_* If you have already started selling your items on Amazon and now you want to start selling them with plentymarkets, you have to assign already existing SKUs in the *Item » Edit item » [Open item] » [Open variation] » Tab: Settings » Tab: Availability* menu.

| *Catalogue was listed with SSW*
a| * *Yes* = Items are listed on Amazon with link:https://www.starsellersworld.com/[starsellersworld^]{nbsp}icon:external-link[]. The item SKU will be cut off right behind the last "-" when importing the items. This makes it possible to match the item in the system. +
* *No* = Items are not listed on Amazon with starsellersworld.

| *Generate invoice*
a| Select whether invoices should be generated by plentymarkets or by Amazon. See also <<#6800, Setting up invoice generation for Amazon orders>>. +
*_Note:_* If you want to use Amazon Business, activate the option *VCS plentymarkets* (VCS Lite) or *VCS Amazon*. +

* *plentymarkets* = plentymarkets calculates the VAT and generates the invoice. You set up an event procedure which uploads the invoices to Amazon via Amazon IDU. See <<#3175, Setting up Amazon IDU>>. +
* *VCS plentymarkets* (VCS Lite) = Amazon invoices are automatically generated by plentymarkets and transferred to Amazon. Amazon calculates the VAT. Amazon calls this option VCS Lite. See <<#3150, Setting up VCS plentymarkets>>. +
*_Note:_* VCS must be activated in Amazon Seller Central. +
* *VCS Amazon* = Invoices for Amazon orders are generated by Amazon. +
Invoices for Amazon orders and credit notes are imported into plentymarkets. See <<#6900, Setting up VCS Amazon>>. +
*_Note:_* VCS must be activated in Amazon Seller Central.
|====

[TIP]
.SKU settings and stock synchronisation
====
If the same settings for SKU numbers are selected for all platforms, then you can synchronise all platforms for the European Marketplaces Account with the stock synchronisation. If the settings are not the same, then the synchronisation must be carried out separately for each platform.

Because the stock is managed globally for a European Marketplaces Account, it is sufficient to activate the stock for your home marketplace. Nevertheless, the SKU settings must match.
====

[#500]
====  Carrying out item settings

In the *Item settings* tab, you carry out settings related to the item export. For example, you can configure automatic processes and export filters. If you use export filters, then only items with the selected filters are exported.

Watch this video tutorial for further information about item settings for Amazon:

.Amazon item settings
video::199997850[vimeo]

[.instruction]
Carrying out item settings:

. Go to *Setup » Markets » Amazon » Settings*.
. In the account overview to the left, click on the account.
. Carry out the settings in the *Item settings* tab. Pay attention to the explanations given in <<#tab-item-settings>>.
. Save (icon:save[set=plenty]) the settings.

[[tab-item-settings]]
.Settings in the *Item settings* tab
[cols="1,3a"]
|====
| Setting | Explanation

2+| Automatic processes

| *Item export*; +
*Price changes*; +
*Stock synchronisation*; +
*Stock changes*
| Do not transfer the information or select how often the information should be transferred.

2+| Export filter

| *Item availability*; +
*Export categories*; +
*BMVD categories*; +
*Flag 1*; +
*Flag 2*; +
*Tags*; +
*Store item*
a| Only items with the selected filters are exported. +

* *Item availability* = If a parent (main item) has an availability that was not selected here, then it will not be transferred. +
* *Flag 1* and *2* = These filters only apply to the daily export. +
* *Tags* = You can select one or more tags. +
* *Store item* = If you select the filter *Only items visible in online store*, the items which should be exported have to be activated for the shop which was selected for the *Client* in the *Setup » Markets » Amazon » Settings » Tab: Settings* menu for the selected Amazon account. If you select the filter *All items*, then all items are exported, independent of the selected shop.

2+| Export settings

| *Item name*; +
*Item description*
| The selected information is exported.

| *Allow HTML tags*
| The following tags are allowed: < br >, < b >, < i >, < p > ,< ul >, < li >, < table >, < tr >, < td >, < th >, < tbody > and < strong >.

| *Warehouse selection*
| Select one of the following options: *Transfer stock quantity of distribution warehouse that currently has largest stock*, *Use item's main warehouse*, *Transfer sum of the stock quantities from all distribution warehouses*, or *Select warehouses*. If you select the option *Select warehouses*, then the setting *Warehouse* is displayed below.

*_Note:_* Since 19/5/2021, shipping confirmations to Amazon must contain the address details of the warehouse. In Seller Central, these address details are shown in the *Ship from* field. As such, make sure that address details are saved for all warehouses from which you want to ship Amazon orders. Go to *Setup » Stock » Warehouse » [Open warehouse] » Settings* to confirm that all necessary address details are saved.

| *Warehouse*
| Select one or more warehouses. This setting is only displayed if you selected the option *Select warehouses* under warehouse selection. +
The stock of the selected warehouses is summed up and transmitted to Amazon. Buffers and maximum amounts are also taken into consideration. This allows you to systematically offer the stock of specific warehouses on specific Amazon accounts or Amazon platforms. +
If you selected the option *Select warehouses* under *Warehouse selection*, but have not selected a warehouse, the item is not exported because the stock cannot be calculated.

| *Stock buffer*
| If an item is limited to net stock, the exported stock is reduced by the value entered.

| *Maximum stock*
| Defines the upper limit for exported stock for all items. This setting takes priority over the setting below *Quantity for items not limited to stock*.

| *Quantity for items that are not limited to the stock*
| For items with the setting *no limitation*, the maximum amount of the real stock and the quantity defined here is transferred. +
*_Example:_* Setting 0, net stock 8\. plentymarkets transfers 8. +
Items with the setting *Limited to net stock* are not taken into consideration.

| *Average delivery period*
| Select *Do not transfer*, *Transmit "average delivery time in days"*, or *Transmit "average delivery time in days” + Additional delay in delivery*.

| *Processing time*
| Enter a number of days for the additional delay in delivery. This option is only displayed if the *Average delivery period* option is set to *Transmit "average delivery time in days + handling time*.

| *Manufacturer part number*
| Select whether you want to transfer the SKU, variation number, GTIN, variation ID, external variation ID, model or no value at all for the CSV file’s field.

| *Additional SKU*
| Activate the data exchange for additional Amazon SKUs. +
Activate *ALL*, the *Stock update*, or the *Price update* for <<markets/amazon/preparing-variations#760, additional SKUs>>.
|====

[#600]
==== Carrying out order settings

In the *Order settings* tab, you carry out settings related to shipping.

The abbreviation MFN stands for merchant-fulfilled network. This means that the seller takes care of order processing. Watch this video tutorial for further information about Amazon MFN:

.Amazon MFN
video::307433826[vimeo]

[.instruction]
Carrying out order settings:

. Go to *Setup » Markets » Amazon » Settings*.
. In the account overview to the left, click on the account.
. Carry out the settings in the *Order settings* tab. Pay attention to the explanations given in <<#tab-order-settings>>.
. Save (icon:save[set=plenty]) the settings.

[[tab-order-settings]]
.Settings in the *Order settings* tab
[cols="1,3a"]
|====
| Setting | Explanation

2+| Ship own orders (MFN)

| *Order import*
| Do not transfer the information or choose how often the information should be imported.

| *Order import start date*
| Enter a date. Only orders starting from this date will be imported into plentymarkets. +
*_Note:_* Every order that was imported into plentymarkets will be billed.

| *Shipping confirmation*
| Do not export the shipping confirmation to Amazon or choose how often the shipping confirmation should be exported.

| *Order item*
| Defines how the item name is displayed in the order item. Select one of the following options:

* *Copy item name from store*
* *Copy item name from Amazon - with SKU*
* *Copy item name from Amazon - without SKU*

| *Incoming payment*
| Select *Incoming payment booked* if the incoming payment should be displayed as booked when MFN and FBA orders are imported. +
*_Note:_* This setting applies to both own shipping (MFN) and to shipping by Amazon (FBA).

| *Status for transmitted returns*
|Select the <<order-processing/orders/managing-orders#1200, order status>> for returns that were successfully reported to Amazon.

| *Status for untransmitted returns*
|Select the <<order-processing/orders/managing-orders#1200, order status>> for returns that were not reported to Amazon.

| *Pending orders*
| Decide whether pending orders should be imported every 15 minutes or never.

| *Credit note import*
| Select whether Amazon credit notes for MFN and FBA orders should be imported into your plentymarkets system. +

[cols="1,3a"]
!===
! *No* (default)
! Credit notes are not imported. If you select *No*, create an event procedure to import returns into your plentymarkets system in form of credit notes.

! *Yes*
! Amazon credit notes are imported into your plentymarkets system every 4 hours.
!===

*_Note:_* This setting applies to both own shipping (MFN) and to shipping by Amazon (FBA).

2+| Shipment by Amazon (FBA)

| *Active*
| Place a check mark to activate Amazon FBA.

| *Referrers*
| Select whether only orders from Amazon should be processed with FBA or whether orders from other <<orders/order-referrer#, referrers>> should be processed with FBA as well.

| *Status*
|Select the <<orders/managing-orders#1200, order status>> for orders that were imported from Amazon.

| *Warehouse*
| Select which Amazon FBA warehouse should be used for stock synchronisation with the account. This warehouse is also used to assign the FBA order to the account if no FBA order could be assigned to the country the order originates in.

| *Warehouse for unsellable stock*
| Select which <<#60, Amazon FBA warehouse>> should be used for unsellable stock for this account. If you do not select a warehouse, the unsellable stock will not be imported. +
Unsellable stock is defined as the number of units you have for a SKU in Amazon fulfillment centers in unsellable condition. In Amazon's "Manage FBA Inventory" report, this stock is equivalent to the quantity in the column *afn-unsellable-quantity*.

| *Outgoing items*
| Select whether outgoing items should be marked as booked or not. The option *Mark as booked* does not trigger an item movement. In order to trigger an item movement, select the option *Do not mark as booked* and set up an event procedure.

| *Returns import*
| Do not import returns or select *daily* import of returns.

| *Include coupons to returns*
| Select whether coupons can be used for returns or not. If the FBA order was paid fully or partly with a coupon, the coupon is added to the return. A minimum order quantity for the coupon is not taken into consideration.

| *Stock import*
| Select whether the stock should be imported *hourly* or never.

| *Status for transmitted orders*
|Select the <<orders/managing-orders#1200, order status>> for orders that were successfully transferred to FBA.

| *Ignore item discounts from campaigns during import*
| Amazon order reports do not specify if any item discounts were granted by the seller or by Amazon. In both cases, the discounted amount is deducted from the order value during the order import. However, if Amazon granted the discount, the order value differs from the amount that Amazon pays you for the order. In such cases, you need to manually adjust the order. Otherwise, you do not pay enough VAT on the order.

Select how to deal with item discounts when orders are imported.

[cols="1,3a"]
!===
! *No* (default setting)
! The discount amount is imported. If Amazon granted the discount, the order must be adjusted manually.

Discount granted by Amazon:

* A customer buys one of your items for 10.00 GBP.
* Amazon grants the customer a discount of 1.00 GBP.
* The order is imported with an order value of 9.00 GBP.
* Amazon pays you 10.00 GBP. +
→ The order value and the amount that Amazon pays you do not match. The order must be adjusted manually.

Discount granted by the seller:

* A customer buys one of your items for 10.00 GBP.
* You grant the customer a discount of 1.00 GBP.
* The order is imported with an order value of 9.00 GBP.
* Amazon pays you 9.00 GBP. +
→ All amounts are correct.

! *Yes*
! The discounted amount is deducted from the order value during the import. This setting is recommended for sellers that do not offer their own discount campaigns on Amazon platforms. If the seller granted the discount, the order must be adjusted manually.

Discount granted by Amazon:

* A customer buys one of your items for 10.00 GBP.
* Amazon grants the customer a discount of 1.00 GBP.
* Amazon pays you 10.00 GBP.
* The order is imported with an order value of 10.00 GBP. +
→ All amounts are correct.

Discount granted by the seller:

* A customer buys one of your items for 10.00 GBP.
* You grant the customer a discount of 1.00 GBP.
* The order is imported with an order value of 10.00 GBP.
* Amazon pays you 9.00 GBP. +
→ The order value and the amount that Amazon pays you do not match. The order must be adjusted manually.

*_Note:_* To simplify the examples, the fees that you need to pay Amazon for the order are ignored.
!===

| *Ignore shipping discounts from campaigns during import*
| Amazon order reports do not specify of any shipping discounts were granted by the seller or by Amazon. In both cases, the discounted amount is deducted from the order value during the order import. However, if Amazon granted the discount, the order value differs from the amount that Amazon pays you for the order. In such cases, you need to manually adjust the order. Otherwise, you do not pay enough VAT on the order.

Select how to deal with shipping discounts when orders are imported.

[cols="1,3a"]
!===
! *No* (default setting)
! The discount amount is imported. If Amazon granted the discount, the order must be adjusted manually.

Discount granted by Amazon:

* A customer buys one of your items for 10.00 GBP plus 3.00 GBP shipping.
* Amazon waives the shipping costs.
* The order is imported with an order value of 10.00 GBP plus 3.00 GBP shipping.
* Amazon pays you 13.00 GBP. +
→ The order value and the amount that Amazon pays you do not match. The order must be adjusted manually.

Discount granted by the seller:

* A customer buys one of your items for 10.00 GBP plus 3.00 GBP shipping.
* You waive the shipping costs.
* The order is imported with an order value of 10.00 GBP plus 3.00 GBP shipping.
* Amazon pays you 13.00 GBP. +
→ All amounts are correct.

! *Yes*
! The discounted amount is deducted from the order value during the import. This setting is recommended for sellers that do not offer their own discount campaigns on Amazon platforms. If the seller granted the discount, the order must be adjusted manually.

Discount granted by Amazon:

* A customer buys one of your items for 10.00 GBP plus 3.00 GBP shipping.
* Amazon waives the shipping costs.
* The order is imported with an order value of 10.00 GBP plus 3.00 GBP shipping.
* Amazon pays you 13.00 GBP. +
→ All amounts are correct.

Discount granted by the seller:

* A customer buys one of your items for 10.00 GBP plus 3.00 GBP shipping.
* You waive the shipping costs.
* The order is imported with an order value of 10.00 GBP plus 3.00 GBP shipping.
* Amazon pays you 13.00 GBP. +
→ The order value and the amount that Amazon pays you do not match. The order must be adjusted manually.

*_Note:_* To simplify the examples, the fees that you need to pay Amazon for the order are ignored.
!===

| *Item bundles Multichannel*
| Select which positions should be transferred to Amazon. +

[cols="1,3a"]
!===
! *Transmit all order positions*
! Transmit all positions included in the order to Amazon. If you select this option, then both the package position and the contents of the package are transmitted to Amazon.

! *Transmit package position only*
! Only the package position is transferred to Amazon.

! *Transmit without package position*
! Only the contents of the package are transferred to Amazon.
!===

| *Shipping category*
| Select a shipping category.

[cols="1,3a"]
!===
! *Standard*
! Normal shipping

! *Expedited*
! Express shipping

! *Priority*
! Fastest shipping service
!===

| Additional settings for FBA
a| The following settings are located in the *Ship own orders (MFN)* area at the top of the menu. However, these settings apply to both own shipping (MFN) and to shipping by Amazon (FBA). As such, also select options for these settings:

[cols="1,3a"]
!===

! *Incoming payment*
! Select *Incoming payment booked* if the incoming payment should be displayed as booked when MFN and FBA orders are imported.

! *Credit note import*
! Select whether Amazon credit notes for MFN and FBA orders should be imported into your plentymarkets system.

* *No* (default) = Credit notes are not imported. If you select *No*, create an event procedure to import returns into your plentymarkets system in form of credit notes. +
* *Yes* = Amazon credit notes are imported into your plentymarkets system every 4 hours.

!===

*_Note:_* These settings apply to both own shipping (MFN) and to shipping by Amazon (FBA).
|====
