Add SKUs manually for specific referrers in the *Item » Edit item » [Open item] » [Open variation] » Tab: Availability* menu if needed. If you have already started selling your items on Amazon and now you want to start selling them with plentymarkets, you have to assign already existing SKUs in this menu.

[.instruction]
Adding SKU:

. Go to *Item » Edit item » [Open item] » [Open variation] » Tab: Settings*.
. Click on the *Availability* tab.
. In the *SKU* area, click on *Add* (icon:plus-square[role="green"]). +
→ The *New SKU* window opens.
. Select the referrer *Amazon* to add the SKU.
. Select the corresponding marketplace account.
. Enter the SKU.
. Enter the parent SKU.
. Click on *Add* (icon:plus-square[role="green"]). +
→ The SKU is saved and displayed.

SKUs can still be changed afterwards. However, note that Amazon might be unable to assign the items if you make changes to SKUs.

[IMPORTANT]
.Parent SKU
====
Parent SKUs can be saved for both items and variations. The manual maintenance of SKUs enables you to assign the Parent SKU of entirely different item variations to variations of an item. For example, you can assign the Parent SKU of a variation which belongs to an entirely different item 5 times to an item with 5 variations. These variations are listed on Amazon as variations of the item with the Parent SKU they are assigned to. +
If one variation has a different Parent SKU than the remaining variations of an item, then two different items are listed on Amazon, but you only have to maintain one item in your plentymarkets system.
====
