Add SKUs manually for specific referrers in the *Item » Edit item » [Open item] » [Open variation] » Tab: Availability* menu if needed.

[.instruction]
Adding SKU:

. Go to *Item » Edit item » [Open item] » [Open variation] » Tab: Settings*.
. Click on the *Availability* tab.
. In the *SKU* area, click on *Add* (icon:plus-square[role="green"]). +
→ The window *New SKU* is displayed.
. Select the referrer *Amazon* to add the SKU.
. Select the corresponding marketplace account.
. Enter the SKU.
. Click on *Add*. +
→ The SKU is saved and displayed. +
*_Tip:_* SKUs can still be changed afterwards.

[discrete]
===== Activating the stock update and price update for additional SKUs

Additional SKUs are automatically included in the Amazon order import. Activate the stock update and price update for additional SKUs manually in the *Setup » Markets » Amazon » Settings » Tab: Item settings* menu. +

The stock update and price update for additional SKUs is carried out along with the normal stock update and price update at the interval that you have selected within *Setup » Markets » Amazon » Settings » Tab: Item settings* for the options *Price changes* and *Stock synchronisation* in the *Automatic processes* area. +

During the stock update for additional SKUs, FBA stock is also updated.

[.instruction]
Activating the stock and price update:

. Go to *Setup » Markets » Amazon » Settings » Tab: Item settings*.
. In the *Export settings* area, activate *Stock update* and *Price update* for the *Additional SKU* option, depending on which options you want to activate. *ALL* activates both the stock update and the price update.
. Save (icon:save[set=plenty]) the settings.
