[#3UIG01]
== Setting up Amazon

Set up the market in plentymarkets in the *Setup » Markets » Amazon » New settings* menu. +
You can add several Amazon accounts with different settings.

// Account or Amazon account

[#new-account]
=== Adding a new account

First, add a new account for Amazon.

[.instruction]
Adding a new account:

. Go to *Setup » Markets » Amazon » New settings*.
. Click on *Add account* (material:add[]). +
→ The *Add account* window opens.
. Select the *region* that you want to use this Amazon account for from the drop-down list.
. Select one or more *channels*. +
*_Note:_* Channels are Amazon’s sales channels (or countries, for example amazon.co.uk) on which you can offer your items. Which channels can be selected here depends on the selected region.
. Enter an *account name*. +
*_Note:_* The name can be freely selected, but it has to be unique. This means that you cannot assign the same name to two different Amazon accounts.
. Click on *Save*. +
→ A view with further settings opens.
. Carry out the settings. Pay attention to the explanations given in <<#basic-settings-amazon>>.
. Save (terra:save[]) the settings.

[[basic-settings-amazon]]
.Basic settings for the market Amazon
[cols="1,4a"]
|===
|Setting |Explanation

| *Advanced settings*
| Activate to display the advanced settings. +
Advanced settings are settings which you do not necessarily need to set up your Amazon account. However, those settings are very useful and we recommend to take a look at the advanced settings after you carried out the basic settings. +
Advanced settings are available for the areas *MFN*, *FBA*, and for the *channels*.

| material:link[role="blue"] *Connect*
| The account is connected with an Amazon account. +

When you click on material:link[role="blue"] *Connect*, you will be forwarded to Amazon and an Amazon page will open in a new tab. Login using the access data of you Amazon seller account and grant plentymarkets access to your Amazon account. Once the process is completed and everything went well, the message “Authorisation completed” is displayed. +

If the account is connected with an Amazon account, then the seller ID of the Amazon account is displayed here. +

The account can also be reconnected, if necessary.

2+^| *Account*

| *Account*
| The name of your Amazon account. You entered the name when you created the account.

| *Active*
| Activate the Amazon account. The data exchange with Amazon is started. +

We recommend to only activate the account after you carried out all settings.

*_Note:_* The account has to be connected to an Amazon account so that data can be exchanged between plentymarkets and Amazon. To connect to an Amazon account, click on material:link[role="blue"] *Connect* at the top of the window.

| *Client*
| Select a client (shop). The orders of this Amazon account will be assigned to this client.

| *Activate B2B*
| Do you want to use B2B for this Amazon account? The account will be activated for Amazon Business. This means that you sell your items to business customers. +

*_Note:_* If you want to use Amazon Business, then you need an link:https://business.amazon.co.uk/?ld=NSGoogle_BIZDE&ref_=b2b_reg_search_FAQ_NSGoogle_BIZDE[Amazon Business account^].

| *Activate MFN*
| Do you want to use MFN for this Amazon account? +
MFN (= Merchant Fulfillment Network) means that you store and ship your items yourself.

| *Activate FBA*
| Do you want to use FBA for this Amazon account? +
FBA (= Fulfillment by Amazon) means that Amazon stores and ships your items to your customers. Of course, you then have to store at least some of your items with Amazon.

| *Activate VCS*
| Do you use Amazon’s VAT calculation service (VCS = Vat Calculation Service)? +

Select one of the following options: +

* *plentymarkets* = You do not use VCS. plentymarkets calculates the VAT and generates the invoice. You set up an event procedure which uploads the invoices to Amazon via Amazon IDU. See <<#3175, Setting up Amazon IDU>>. +
* *Yes, VCS Lite* = You use VCS. Amazon invoices are automatically generated by plentymarkets and transferred to Amazon. Amazon calculates the VAT. See <<#3150, Setting up VCS plentymarkets>>. +
*_Note:_* VCS must be activated in Amazon Seller Central. +
* *Yes, VCS* = You use VCS. Invoices for Amazon orders are generated by Amazon. +
Invoices for Amazon orders and credit notes are imported into plentymarkets. See <<#6900, Setting up VCS Amazon>>. +
*_Note:_* VCS must be activated in Amazon Seller Central. +

*_Note:_* If you want to use Amazon Business, activate the option *VCS Lite* or *VCS*.
|===

[#account-overview]
=== Account overview

The *Setup » Markets » Amazon » New settings* menu provides an overview of your Amazon accounts. <<tabelle-konto-uebersicht>> lists the columns and available actions in the account overview.

[TIP]
.Configuring columns
====
Click on *Configure columns* (material:settings[]) to define which settings should be displayed in the account overview. +
The columns *Account name*, *Active*, *Seller ID*, *Connected*, *Client*, *B2B*, *MFN*, *FBA*, and *VCS* are displayed in the overview by default.
====

*_Note:_* The account overview looks different depending on which columns you add or hide via *Configure columns* (material:settings[]). The following table only lists the columns which are displayed in the overview by default.

[TIP]
.Searching for Amazon accounts
====
If you have many Amazon accounts and you cannot find the desired account right away, then you can use the search (material:search[role="blue"]) to find the account. Open the filters (material:tune[]) and enter the *Account name*, the *Seller ID*, and the *Region* to find the desired account.
====

[[table-account-overview]]
.Amazon account overview
[cols="1a,4a"]
|===
|Column |Explanation

| *Account name*
| The name of your Amazon account.

| *Active*
| material:circle[role="blue"] = The account is active and data is exchanged with Amazon. +
material:circle[] = The account is not active. No data is exchanged with Amazon. +

*_Note:_* The data exchange between plentymarkets and Amazon will only work if the account was connected to Amazon. Whether the account is connected is displayed in the column *Connected*.

| *Seller ID*
| The seller ID of your Amazon account. You have received the seller ID from Amazon.

| *Connected*
| material:link[role="blue"] = The account is connected with Amazon. plentymarkets can access your Amazon account and exchange data. +
material:link_off[] = The account is not connected with Amazon. Data cannot be exchanged between plentymarkets and Amazon.

| *Client*
| The client (shop) that orders of this Amazon account are assigned to.

| *B2B*
| material:done[] = You use B2B for this Amazon account (you sell your items to business customers). +
material:close[] = You do not use B2B for this Amazon account.

| *MFN*
| material:done[] = You use MFN (shipment by the seller) for this Amazon account. +
material:close[] =  You do not use MFN for this Amazon account.

| *FBA*
| material:done[] = You use FBA (storage and shipment by Amazon) for this Amazon account. +
material:close[] = You do not use FBA for this Amazon account.

| *VCS*
| material:done[] = Amazon’s VAT calculation service is activated for this Amazon account. The overview also shows you whether you use *VCS* (Amazon calculates VAT and generates invoices) or *VCS Lite* (Amazon calculates VAT and plentymarkets generates invoices). +
material:close[] = VCS is not activated for this Amazon account.
|===

[#J48FUC6T]
== Carrying out order settings

[.instruction]
Carrying out order settings:

. Go to *Setup » Markets » Amazon » New settings » [Open account]*.
. Navigate to the area *Orders*.
. Carry out the settings. Pay attention to the information given in <<#tab-order>>. +
*_Tip:_* Is a setting missing? Then activate the option *Advanced settings*.
. Save (terra:save[]) the settings.

[[tab-order]]
.Settings in the tab *Orders*
[cols="1,3a"]
|===
| Setting | Explanation

| *Order import start date*
| Date in the format *DD.MM.YYYY* or select a date via the calendar (material:today[]). +

In the line *Order import start time*, you can also enter a time or select a time via (material:schedule[]). +

Only orders starting from this date and time will be imported into plentymarkets. Orders which were generated before this date will not be imported. +
However, note that orders older than this will be imported into plentymarkets again if they were updated on Amazon. +

*_Note:_* This setting applies to both own shipping (MFN) and to shipping by Amazon (FBA).

*_Note:_* Every order that was imported into plentymarkets will be billed.

| *Item name in orders*
| Which product name should be shown in order items of Amazon orders? +

*_Possible options:_* +
*Default item name of client* = The item name that is used in the default online shop is displayed in Amazon orders. +
*Item name from Amazon - with SKU* = The item name that is used on Amazon plus SKU is displayed in Amazon orders. +
*Item name from Amazon - without SKU* The item name that is used on Amazon is displayed in Amazon orders.

| *Import credit notes*
| Activate to import credit notes every 4 hours. VCS credit notes are imported once per hour. +

*_Note:_* This setting applies to both own shipping (MFN) and to shipping by Amazon (FBA).

| *Products listed with starsellersworld*
| Do you list your items on Amazon with link:https://www.starsellersworld.com/[starsellersworld^]? Then activate this option. +

The item SKU will be cut off right behind the last "-" when importing the items. This makes it possible to match the item in the system.
|===

[#J48KIC6T]
== Carrying out product settings

In the view *Product*, you carry out settings related to the item export.

[.collapseBox]
.What’s the difference between products and offers?
--

* *Product* is an entire item data set displayed on an Amazon product detail page. This also includes prices and stock information. The product detail page contains all important information about a product that is relevant for customers.
* For *offers*, only your prices and stock information are exported for an item. The product itself is "owned" by another merchant on the marketplace. As such, you just "attach" yourself to that product and publish your own price. On Amazon, this also means that your offer does not get the Buy Box. Instead, your offer appears further down in the "Other sellers on Amazon" box.

--

[.instruction]
Carrying out product settings:

. Go to *Setup » Markets » Amazon » New settings » [Open account]*.
. Navigate to the area *Products*.
. Carry out the settings. Pay attention to the information given in <<#tab-product>>. +
*_Tip:_* Is a setting missing? Then activate the option *Advanced settings*.
. Save (terra:save[]) the settings.

[[tab-product]]
.Settings in the tab *Products*
[cols="1,3a"]
|===
| Setting | Explanation

| *SKU structure*
| How do you want to create new SKU if a variation does not have an SKU when it is first exported?

The SKU (Stock Keeping Unit) is a unique reference number for all items and item variations on Amazon.

Select one of the following options:

* *Variation ID* +
* *GTIN if available, otherwise variation ID* +
* *Variation number if available, otherwise variation ID*

The option is only applied to variations that are exported to Amazon for the first time and do not have an SKU yet.

[.collapseBox]
.You already sell on Amazon and now want to sell on Amazon using plentymarkets?
--


Then save the SKU numbers that you already use on Amazon in your variations.

[.instruction]
Adding existing SKU:

. Go to *Item » Edit item » [Open item] » [Open variation] » Variation tab: Settings*.
. Click on the variation tab *Availability*.
. In the *SKU* area, click on *Add* (icon:plus-square[role="green"]). +
→ The *New SKU* window opens.
. Select the referrer *Amazon*.
. Select the associated Amazon account.
. Enter the SKU.
. Click on *Add* (icon:plus-square[role="green"]). +
→ The SKU is saved and displayed.

// TODO: Or link to "prepare variations"?
--

| *Activate long lead time*
| Does Amazon allow you longer lead times?

[cols="1a,5a"]
!===
! material:toggle_off[role="darkGrey"] +
(default)
! The default Amazon lead time is used.

material:toggle_on[role="blue"]
! Increases the maximum processing time of Amazon orders from 30 to up to 120 days. +
*_Note:_* Only activate this setting if Amazon has activated your account for extended lead times.
!===

| *Export stock changes*
| Do you want to export stock changes to Amazon every 15 minutes? +
*_Important:_* This setting applies to all channels of the Amazon account.

[cols="1a,5a"]
!===
! material:toggle_off[role="darkGrey"] +
(default)
! Stock changes are not updated.

material:toggle_on[role="blue"]
! Stock changes are exported to Amazon every 15 minutes.
!===


| *Export full stock*
| Do you want to export stock data to Amazon once per day? +
*_Important:_* This setting applies to all channels of the Amazon account.

[cols="1a,5a"]
!===
! material:toggle_off[role="darkGrey"] +
(default)
! The stock is not updated.

material:toggle_on[role="blue"]
! All stock is exported once per day.
!===
|===

[#CNQFKI]
== Carrying out fulfilment settings

You can organise the shipping of variations sold on Amazon in different ways:

* *Amazon FBA:* FBA stands for Fulfilment by Amazon. With this service, Amazon takes on the warehousing and shipping of your items. In other words: Amazon stores and ships your products. <<#MTHE2U4J, How to set up Amazon FBA.>>
* *Amazon MFN:* MFN is short for Merchant Fulfillment Network. You stock and ship your products yourself.
<<#LZUYXNNP, How to set up Amazon MFN.>>

//tag::amazon-mfn-video[]
Watch this video tutorial for visual information about Amazon MFN:

.Amazon MFN
video::307433826[vimeo]
//end::amazon-mfn-video[]

[#XZK4GY]
=== Setting up Amazon MFN

// TODO: Introduction

[.instruction]
Setting up Amazon MFN:

. Go to *Setup » Markets » Amazon » Settings*.
. Navigate to the area *MFN*.
. Carry out the settings. Pay attention to the information given in <#tab-MFN>. +
*_Tip:_* Is a setting missing? Then activate the option *Advanced settings*.
. Save (terra:save[]) the settings.

[[tab-MFN]]
.Setting up Amazon MFN
[cols="1,3a"]
|===
| Setting | Explanation

| *Import MFN orders*
|
[cols="1a,5a"]
!===
! material:toggle_off[role="darkGrey"] +
(default)
! MFN orders are not imported for this account.

material:toggle_on[role="blue"]
! MFN orders are imported every 15 minutes for this account.

*_Note:_* Orders are pulled every 15 minutes. However, in some cases it can take up to 90 minutes until an order that was generated in Amazon will appear in your plentymarkets system. That is not a malfunction, but rather is the only possibility due to technical reasons. Usually, an email from Amazon informs you about the sale beforehand and you can already see the order in Seller Central.
!===

| *Order status for transmitted refunds*
| Select an xref:orders:order-statuses.adoc#create-status[order referrer]. Orders are moved to this order status when a refund was successfully transferred to Amazon.

| *Order status for refunds that were not transmitted*
| Select an xref:orders:order-statuses.adoc#create-status[order referrer]. Orders are moved to this order status when a refund could not be transferred to Amazon.

| *Importing outstanding orders*
| Decide whether pending orders should be imported. 

[cols="1a,5a"]
!===
! material:toggle_off[role="darkGrey"] +
(default)
! Outstanding orders are not imported. As such, no stock is reserved.

material:toggle_on[role="blue"]
! Outstanding orders are imported every 15 minutes. The stock is reserved.

*_Workflow:_*

* Outstanding Amazon orders are imported with the status *[1] Incomplete data*. Orders stay in this status until Amazon releases the order.
* No addresses and no item prices are saved in the order until it is approved.
* After the approval by Amazon, the order is updated and addresses and prices are saved.
* If Amazon does not approve the order, the order is automatically moved to status *[8] Cancelled*. The stock is released.
!===

| *Activate shipping confirmations*
| Do you want to send shipping confirmations to Amazon?
// TODO: What if not? Then EA?
|===

[#92ZUDZ]
=== Setting up Amazon FBA

If you use Amazon FBA, specify how FBA orders from Amazon are to be processed.

[#60]
==== Creating a warehouse for Amazon FBA

Start by creating warehouses for Amazon fulfilment orders. You need to create a warehouse in plentymarkets for every Amazon logistic warehouse that you send items to. This ensures that the complete range of stock management functions remain intact with the FBA programme and that you can keep track of the stock at Amazon in your plentymarkets system.

You need the following warehouses:

* one warehouse for each country where Amazon stores your FBA inventory
* A warehouse for unsellable FBA inventory for each country where Amazon stores your FBA inventory

[.instruction]
Creating a warehouse for Amazon FBA:

. Go to *Setup » Stock » Warehouse*.
. Click on *New warehouse*.
. Enter a name for the warehouse.
. Select the warehouse type *Repair*.
. Select *Amazon* as *Logistics type*.
. Save (terra:save[]) the settings. +
→ The warehouse is listed in the overview in alphabetical order and opened.
. Carry out further settings according to the explanations on the manual page xref:stock-management:setting-up-a-warehouse.adoc#[Setting up a warehouse].
. Save (terra:save[]) the settings. +
→ The warehouse is created.
// TODO: insert warehouse settings here

[TIP]
.Separate Amazon FBA stock display for EU and UK
====
Since Brexit, the FBA UK stock for amazon.co.uk is managed separately and not subsumed under the FBA EU stock. To have the *FBA EU stock* as well as the *FBA UK stock* displayed, at least one account is needed in the system which is linked to a European seller account and which is allowed to retrieve information from a European Amazon platform. An additional account is needed in the system, which is linked to a European seller account and which is allowed to retrieve information from the platform amazon.co.uk. This account then retrieves the total FBA UK stock. For more information, refer to the best practice xref:markets:best-practices-amazon-fba-stock-display.adoc#[Amazon FBA stock display for EU and UK].
====

[#92ZFDZ]
==== Setting up Amazon FBA

If you use Amazon FBA, specify how FBA orders from Amazon are to be processed.

// tag::amazon-fba-settings[]
[.instruction]
Setting up Amazon FBA:

. Go to *Setup » Markets » Amazon » Settings » [Open account]*.
. Navigate to the area *FBA*.
. Carry out the settings. Pay attention to the information given in <#tab-fba>. +
*_Tip:_* Is a setting missing? Then activate the option *Advanced settings*.
. Save (terra:save[]) the settings.

[[tab-fba]]
.Setting up Amazon FBA
[cols="1,3a"]
|===

2+^| Fulfillment by Amazon (FBA)

| *Import FBA orders*
| Do you want to import FBA orders to plentymarkets?

[cols="1a,5a"]
!===
! material:toggle_off[role="darkGrey"] +
(default)
! FBA orders are not imported for this account.

material:toggle_on[role="blue"]
! FBA orders are imported every 4 hours for this account.
!===

| *Order status for imported FBA orders*
| Which xref:orders:manage-orders.adoc#1200[order status] do you want to assign to FBA orders when they are imported to plentymarkets?

*_Note:_* If you activate the setting *Import orders with outgoing items booked*, you must select at least status *7* here.

| *Import orders with outgoing items booked*
| Should FBA orders be marked as "outgoing items booked" during the import?

Orders are flagged as booked if this option is active. However, no stock movement is triggered. The stock is only reduced once the Amazon order report containing the order is imported.

*_Important:_* If the setting is active, select at least status 7 for the setting *Order status for imported FBA orders*.

| *Importing returns*
| Do you want to import returns into plentymarkets?

[cols="1a,5a"]
!===
material:toggle_on[role="blue"] +
(default)
! Returns are imported once per day. +
*_Important:_* Returns will only be imported if the order exists in plentymarkets and its external order number was not changed.

*_Tip:_* In the case of a return, purchasers send the items back to Amazon. The return is imported into your plentymarkets system and listed in the order menu. It is given the return status that you selected in the *Setup » Orders » Settings* menu.

! material:toggle_off[role="darkGrey"]
! Returns are not imported.
!===

| *Add coupons to returns*
| Select whether discounts granted by Amazon are considered for returns. A minimum order quantity for the coupon is not taken into consideration.

*_Important:_* "Coupons" can be discounts from Amazon Delivery Campaigns, Amazon Campaigns or any other discounts granted by Amazon. However, these might also be additional charged applied by Amazon. For example, these might be charges for gift wrapping or cases where Amazon applies its own shipping costs.

[cols="1a,5a"]
!===
material:toggle_on[role="blue"] +
(default)
! FBA returns include order items for discounts or additional charges from Amazon. As such, the credit note amount does not match the amount in the original order. If necessary, the credit note must be corrected. Go to *Cancellation document » Order adjustment » New credit note* to do this.

[.collapseBox]
.Example
--

* Goods value of the original order: 50.00 GBP
* Additional shipping costs charged by Amazon: 5.00 GBP
* Amount in credit note: 55 GBP
--

! material:toggle_off[role="darkGrey"]
! Order items for Amazon coupons are not imported. As such, discounts and additional costs applied by Amazon are ignored and not taken into account in the calculation.

[.collapseBox]
.Example
--

* Goods value of the original order: 50.00 GBP
* Additional shipping costs charged by Amazon: 5.00 GBP
* Amount in credit note: 50 GBP
--
!===
  
| *Ignore item discounts from campaigns*
| Select how to deal with item discounts when orders are imported.

*_Background:_* Amazon order reports do not specify if any item discounts were granted by the seller or by Amazon. In both cases, the discounted amount is deducted from the order value during the order import. However, if Amazon granted the discount, the order value differs from the amount that Amazon pays you for the order. In such cases, you need to manually adjust the order. Otherwise, you do not pay enough VAT on the order.

*_Recommendation:_* Activate this setting if you do not offer product discount campaigns on Amazon platforms.

[cols="1,4a"]
!===
! material:toggle_off[role="darkGrey"] +
(default)
! The discount amount is imported. If Amazon granted the discount, the order must be adjusted manually.

[.collapseBox]
.Example
--

*_Workflow if discount granted by Amazon:_*

* A customer buys one of your items for 10.00 GBP.
* Amazon grants the customer a discount of 1.00 GBP.
* The order is imported with an order value of 9.00 GBP.
* Amazon pays you 10.00 GBP. +
→ The order value and the amount that Amazon pays you do not match. The order must be adjusted manually.

*_Workflow if discount granted by the seller:_*

* A customer buys one of your items for 10.00 GBP.
* You grant the customer a discount of 1.00 GBP.
* The order is imported with an order value of 9.00 GBP.
* Amazon pays you 9.00 GBP. +
→ All amounts are correct.

*_Note:_* To simplify the examples, any fees that you need to pay Amazon for the order are ignored.
--

material:toggle_on[role="blue"]
! The discounted amount is deducted from the order value during the import. This setting is recommended for sellers that do not offer their own discount campaigns on Amazon platforms. If the seller granted the discount, the order must be adjusted manually.

[.collapseBox]
.Example
--

*_Workflow if discount granted by Amazon:_*

* A customer buys one of your items for 10.00 GBP.
* Amazon grants the customer a discount of 1.00 GBP.
* Amazon pays you 10.00 GBP.
* The order is imported with an order value of 10.00 GBP. +
→ All amounts are correct.

*_Workflow if discount granted by the seller:_*

* A customer buys one of your items for 10.00 GBP.
* You grant the customer a discount of 1.00 GBP.
* The order is imported with an order value of 10.00 GBP.
* Amazon pays you 9.00 GBP. +
→ The order value and the amount that Amazon pays you do not match. The order must be adjusted manually.

*_Note:_* To simplify the examples, any fees that you need to pay Amazon for the order are ignored.
--
!===

| *Ignore shipping discounts from campaigns*
| Select how to deal with shipping discounts when orders are imported.

*_Background:_* Amazon order reports do not specify if any shipping discounts were granted by the seller or by Amazon. In both cases, the discounted amount is deducted from the order value during the order import. However, if Amazon granted the discount, the order value differs from the amount that Amazon pays you for the order. In such cases, you need to manually adjust the order. Otherwise, you do not pay enough VAT on the order.

*_Recommendation:_* Activate this setting if you do not offer shipping discount campaigns on Amazon platforms.

[cols="1,4a"]
!===
! *No*
(default)
! The discount amount is imported. If Amazon granted the discount, the order must be adjusted manually.

[.collapseBox]
.Example
--

*_Workflow if discount granted by Amazon:_*

* A customer buys one of your items for 10.00 GBP plus 3.00 GBP shipping.
* Amazon waives the shipping costs.
* The order is imported with an order value of 10.00 GBP plus 3.00 GBP shipping.
* Amazon pays you 13.00 GBP. +
→ The order value and the amount that Amazon pays you do not match. The order must be adjusted manually.

*_Workflow if discount granted by the seller:_*

* A customer buys one of your items for 10.00 GBP plus 3.00 GBP shipping.
* You waive the shipping costs.
* The order is imported with an order value of 10.00 GBP plus 3.00 GBP shipping.
* Amazon pays you 13.00 GBP. +
→ All amounts are correct.

*_Note:_* To simplify the examples, any fees that you need to pay Amazon for the order are ignored.
--

! *Yes*
! The discounted amount is deducted from the order value during the import. This setting is recommended for sellers that do not offer their own discount campaigns on Amazon platforms. If the seller granted the discount, the order must be adjusted manually.

[.collapseBox]
.Example
--

*_Workflow if discount granted by Amazon:_*

* A customer buys one of your items for 10.00 GBP plus 3.00 GBP shipping.
* Amazon waives the shipping costs.
* The order is imported with an order value of 10.00 GBP plus 3.00 GBP shipping.
* Amazon pays you 13.00 GBP. +
→ All amounts are correct.

*_Workflow if discount granted by the seller:_*

* A customer buys one of your items for 10.00 GBP plus 3.00 GBP shipping.
* You waive the shipping costs.
* The order is imported with an order value of 10.00 GBP plus 3.00 GBP shipping.
* Amazon pays you 13.00 GBP. +
→ The order value and the amount that Amazon pays you do not match. The order must be adjusted manually.

*_Note:_* To simplify the examples, any fees that you need to pay Amazon for the order are ignored.
--
!===

2+^| *FBA settings: Stock*

| *Import FBA stock*
| Do you want to import stock information from Amazon to your plentymarkets FBA warehouse?

[cols="1a,5a"]
!===
! material:toggle_off[role="darkGrey"] +
(default)
! FBA stock is not exchanged with Amazon.

material:toggle_on[role="blue"]
! FBA stock is imported to plentymarkets once per hour.
!===

| *Warehouse*
| Which plentymarkets warehouse do you want to use for FBA stock synchronisations with the account?

This warehouse is also used to assign the FBA order to the account if no FBA order could be assigned to the country the order originates in because no warehouse is set up for the order country.

| *Warehouse UK*
| Which plentymarkets warehouse do you want to use for FBA stock synchronisation for the UK?

| *Warehouse for unsellable stock*
| Which plentymarkets warehouse should be used to book in unsellable FBA stock for this account? If you do not select a warehouse, the unsellable stock will not be imported in plentymarkets.

*_Note:_* Do not select the same warehouse for this setting that you also selected for the option *Warehouse* (FBA warehouse). Otherwise, the stock of the warehouse is overwritten.

[.collapseBox]
.What is unsellable stock?
--
Unsellable stock is defined as the number of units you have for a SKU in Amazon fulfillment centers in unsellable condition. In Amazon's "Manage FBA Inventory" report, this stock is equivalent to the quantity in the column *afn-unsellable-quantity*.
--

| *Warehouse for unsellable stock UK*
| Which plentymarkets warehouse should be used to book in unsellable FBA stock for this account in Great Britain? If you do not select a warehouse, the unsellable stock will not be imported in plentymarkets.

*_Note:_* Do not select the same warehouse for this setting that you also selected for the option *Warehouse UK* (FBA warehouse). Otherwise, the stock of the warehouse is overwritten.

[.collapseBox]
.What is unsellable stock?
--
Unsellable stock is defined as the number of units you have for a SKU in Amazon fulfillment centers in unsellable condition. In Amazon's "Manage FBA Inventory" report, this stock is equivalent to the quantity in the column *afn-unsellable-quantity*.
--
//end::amazon-fba-settings[]

//tag::amazon-multi-channel-settings[]
2+^| *Multi-Channel*

| *Activate Multi-Channel shipping*
| Should orders from other sales channels also be processed with Amazon FBA?

*_What is Multi-Channel shipping?_*

You can also use Amazon FBA to fulfil orders generated on other sales channels, for example on other marketplaces or in your online store. As such, Amazon stores and ships your items to your customers on your behalf.

| *Order status for transmitted Multi-Channel orders*
| Select an xref:orders:order-statuses.adoc#create-status[order referrer]. This order status is assigned to Multi-Channel orders that have been successfully transferred to Amazon.

| *Item bundles Multi-Channel*
| Which order items do you want to transfer to Amazon for FBA Multi-Channel orders? +

*_Background:_* Which option you select depends on how you store item bundles in the Amazon warehouse. Are all bundle components of item bundles packaged and stored together in the Amazon warehouse? Or does Amazon pick the individual bundle components to create item bundles?

[cols="1,3a"]
!===
! *Transmit all order positions*
! Both the package position and the item bundle components are transmitted to Amazon.

*_Important: Do not activate this option. Otherwise, Amazon may ship items twice or may not fulfil the order._*

! *Transmit package position only*
! Only the package position is transferred to Amazon.

*_Requirement:_* All bundle components of the item bundle are stored in a single package in the Amazon warehouse. The item bundle only has one SKU. As such, Amazon only picks one order item.

! *Transmit without package position*
! Only the contents of the package are transferred to Amazon.

*_Requirement:_* The item bundle consists of individual items. These items are stored in individual storage locations in the Amazon warehouse(s). Each item has its own SKU. The individual items only become an item bundle by being picked.
!===

| *Shipping category*
| How do you want Amazon to ship your Multi-Channel orders?

[cols="1,3a"]
!===
! *Standard*
! Normal shipping

! *Expedited*
! Express shipping

! *Priority*
! Fastest shipping service
!===
|===
//end::amazon-multi-channel-settings[]

[#HBN7346B]
== Managing channels

Channels are the individual sales channels of Amazon in the different countries.

[#HBN7446B]
=== Adding channels

You can either add channels with default settings or copy and edit an existing channel.

[tabs]
====
Adding channel(s) with default settings::
+
--

[.instruction]
Adding channel(s) with default settings:

. Go to *Setup » Markets » Amazon » Settings*.
. Navigate to the area *Channels*.
. Click on icon:plus[] *Add channel(s) with default settings*. +
→ The window *Add channel(s) with default settings* is shown.
. Select one or more channels from the drop-down list.
. Click on *Save*. +
→ The channels are added to the list of channels.
// TODO: What are the default settings?

--
 
Copying settings of an existing channel::
+
--

[.instruction]
Copying settings of an existing channel:

. Go to *Setup » Markets » Amazon » Settings*.
. Navigate to the area *Channels*.
. In the row of the channel, click on the further actions (material:more_vert[]).
. Select the option *Copy settings to new channel(s)*. +
→ The window *Copy settings to new channel(s)* is shown.
. From the drop-down list *Channels*, select one or more channels.
. Click on *Save*. +
→ The channels are added to the list of channels.

--
====

[#5T93GW10]
=== Editing channel settings

////
In diesem Video-Tutorial erhältst du weitere Informationen zu den verschiedenen Artikeleinstellungen:

.Amazon item settings
video::199997850[vimeo]
////

[.instruction]
Editing channel settings:

. Go to *Setup » Markets » Amazon » Settings*.
. Navigate to the area *Channels*.
. Click on the channel that you want to edit.
. Carry out the settings. Pay attention to the information given in <<#tab-channels>>. +
*_Tip:_* Is a setting missing? Then activate the option *Advanced settings*.
. Save (terra:save[]) the settings.

[[tab-channels]]
.Available channel settings
[cols="1,3a"]
|===
| Setting | Explanation

2+^| Products

| *Export items*
| Do you want to export item data to this Amazon channel?

[cols="1a,5a"]
!===
! material:toggle_off[role="darkGrey"] +
(default)
! Item data is not exported.

material:toggle_on[role="blue"]
! Item data is exported to this Amazon channel once per day.
!===

| *Export filter*
a| Using the export filters, you can exclude variations from the export based on certain criteria. The filters are optional. If you do not set any filters, all variants that are activated for the referrer and meet the export criteria are exported.

*_Important:_* If you set several filters, only those variants are exported to which _all_ selected filters apply.

[cols="1a,4a"]
!===

! *Categories*
! Only variations of the selected category are exported.

! *BMVD categories*
! Only variations of the selected category are exported. +
*_Tip:_* BMVD stands for Books, Music, Video and DVD.

! *Item availability*
! Only variations with the selected availabilities are exported. +
*_Tip:_* The variation availabilities are saved in the *Setup » Item » Availability* menu. For individual variations, select the variation availability in the area *Availability* of the menu *Item » Edit item » [Open item] » [Open variation] » Variation tab: Settings*.

! *Flag 1*; +
*Flag 2*
! Only variations with the selected flags are exported. If you set filters for *Flag 1* and *Flag 2*, only variants that have both these flags are exported.

! *Tags*
! Only variations with the selected tags are exported. You can select one or more tags. If you select multiple tags, only variations with all of these tags are exported.

! *Available in the client's online shop*
! Activate this option to export only variants that are activated for this client.

material:toggle_off[role="darkGrey"] (Standard) = All variations are exported, irrespective of the selected client. +
material:toggle_on[role="blue"] = Only variations that are also activated for the client linked to this Amazon account are exported. +
*_Tip:_* Go to *Item » Edit item » [Open item] » [Open variation] » Variation tab: Availability » Area: Client (store)* to activate the client availability.
!===

| *Manufacturer part number*
| Select whether you want to transfer the SKU, variation number, GTIN, variation ID, external variation ID, model or no value at all as the part_number.

| *Item name*
| Which plentymarkets field do you want to export as the item name?

| *Item description*
| Which plentymarkets field do you want to export as the item description?

| *Allow HTML tags*
|
[cols="1a,5a"]
!===
! material:toggle_off[role="darkGrey"] +
(default)
! All HTML tags are removed from the item description during export.

material:toggle_on[role="blue"]
! Some HTML tags are not removed from the item description.

The following HTML tags are not removed: +
< br >, < b >, < i >, < p > ,< ul >, < li >, < table >, < tr >, < td >, < th >, < tbody > and < strong >
!===

2+^| *Offers*

| *Update prices*
| Do you want to export price changes to this Amazon channel?

[cols="1a,5a"]
!===
! material:toggle_off[role="darkGrey"] +
(default)
! Price changes are not exported.

material:toggle_on[role="blue"]
! Price changes are exported to this Amazon channel once per hour.
!===

| *Additional SKU*
| Activate the data exchange for additional Amazon SKUs. +
Activate *ALL*, the *Stock update*, or the *Price update* for xref:markets:preparing-variations.adoc#760[additional SKUs].

Additional SKUs are automatically included in the Amazon order import. This activates the stock update and the price update for additional SKUs manually.

* *ALL* = Activates the stock update and the price update for additional SKUs.
* *Stock synchronisation* = The stock for additional SKU is synchronised at the same time as the stock.
* *Price synchronisation* = The price for additional SKU is adjusted at the interval you set for the setting *Price Changes *.

During the stock update for additional SKUs, FBA stock information is also imported to plentymarkets.

[.collapseBox]
.What is an additional SKU?
--
Additional SKU can be used in addition to the variation SKU for the stock export and the price export.

*_Example:_* More than one offer is active in your Seller Central for the same variation. If you enable stock synchronisation and/or price synchronisation for additional SKU, you can also update stock and prices for the additional offers using plentymarkets.

*_Important:_* Additional SKU _cannot_ be used for the item export. Why? Amazon does not allow the creation of multiple offers for a product with the same identification (EAN, ASIN, etc.).

Additional SKU can also be used to assign the variation when importing orders.
--

| *Stock source*
a| Possible options:

* *Stock quantity of sales warehouse with highest stock*
* *Stock quantity sum of all sales warehouses*
* *Item's main warehouse*
* *Select warehouse* = The option *Warehouse selection* is shown.

*_Important:_* Shipping confirmations to Amazon must contain the address details of the warehouse. In Seller Central, these address details are shown in the *Ship from* field. As such, make sure that address details are saved for all warehouses from which you want to ship Amazon orders. Go to *Setup » Stock » Warehouse » [Open warehouse] » Settings* to confirm that all necessary address details are saved.

| *Warehouse selection* +
(only if *Select warehouse*)
| Select one or more warehouses. The stock of the selected warehouses is summed up and transmitted to Amazon. The settings for the stock buffer and for maximum stock are also taken into account. +

*_Important:_* If you select the option *Select warehouses* for the setting *Warehouse selection*, but have not selected a *warehouse*, the item is not exported. This is because the stock cannot be calculated.

| *Stock buffer*
| If an item is limited to net stock, the exported stock is reduced by the value entered.

| *Maximum stock*
| Defines the upper limit for exported stock for all items. This setting takes priority over the setting *Quantity for items not limited to stock*.

| *Quantity for items* +
*with no stock limit*
| For items with the setting *no limitation*, the maximum amount of the real stock and the quantity defined here is transferred. +
*_Example:_* Setting 0, net stock 8\. plentymarkets transfers 8. +
Items with the setting *Limited to net stock* are not taken into consideration.

| *Average delivery time in days*
| Select the average delivery time that is exported.

* *Do not transmit* 
* *Average delivery time in days*
* *Average delivery time in days + Processing time* = Opens a field where you can enter the handling time.

*_Tip_*: Enter realistic delivery times. Customers interpret this information as a serious commitment. It is also relevant in terms of competition laws.

| *Processing time* +
(only if *Average delivery time in days + Processing time*)
| Enter handling time in days. This lead time is added to the average delivery time.
|===

=== Delete channel

You want to delete a channel? 

*_Important:_* At least one channel must be saved for each account at all times. The delete buttons are disabled if you select all channels in the group function or if you open the context menu of the last remaining channel.

[tabs]
====
Deleting one channel::
+
--
. Go to *Setup » Markets » Amazon » Settings » [Open account] » View: Channels*.
. In the list, navigate to the channel that you want to delete. +
. Click on the further actions (material:more_vert[]) of the channel.
. In the context menu, click on *Delete channel* (material:delete[]). +
*_Important:_* At least one channel must be saved for each account at all times. As such, the *Delete channel* option is deactivated when you open the context menu of the last channel. +
→ You are asked to confirm your decision.
. Confirm your decision. +
→ The channel is deleted.

--
 
Deleting several channels::
+
--
. Go to *Setup » Markets » Amazon » Settings » [Open account] » View: Channels*.
. In the column to the very left, activate all channels that you want to delete. +
. Click on *Delete* (material:delete[]). +
*_Important:_* At least one channel must be saved for each account at all times. This is why the option *Delete* is disabled if you select all channels in the list. +
→ You are asked to confirm your decision.
. Confirm your decision. +
→ The selected channels are deleted.

// TODO: When will the items no longer be available on the channel?

--
====

////

| Additional settings for FBA
a| The following settings are located in the *Ship own orders (MFN)* area at the top of the menu. However, these settings apply to both own shipping (MFN) and to shipping by Amazon (FBA). As such, also select options for these settings:

| *Order import start date*
| Enter a date. Only orders starting from this date will be imported into plentymarkets. +
*_Note:_* Every order that was imported into plentymarkets will be billed.

| *Order item*
| Defines how the item name is displayed in the order item. Select one of the following options:

* *Copy item name from store*
* *Copy item name from Amazon - with SKU*
* *Copy item name from Amazon - without SKU*

| *Incoming payment*
| Select *Incoming payment booked* if the incoming payment should be displayed as booked when MFN and FBA orders are imported. +
*_Note:_* This setting applies to both own shipping (MFN) and to shipping by Amazon (FBA).

| *Status for transmitted returns*
|Select the xref:orders:order-statuses.adoc#create-status[order status] for returns that were successfully reported to Amazon.

| *Status for untransmitted returns*
|Select the xref:orders:order-statuses.adoc#create-status[order status] for returns that were not reported to Amazon.

| *Pending orders*
| Decide whether pending orders should be imported every 15 minutes or never.

| *Credit note import*
| Select if Amazon credit notes for MFN and FBA orders should be imported into your plentymarkets system as orders of the type *Credit note*.

[cols="1,3a"]
!===
! *No* (default)
! Credit notes are not imported.

! *Yes*
! Amazon credit notes are imported into your plentymarkets system every 4 hours.
!===

*_Note:_* This setting applies to both own shipping (MFN) and to shipping by Amazon (FBA).

| *Active*
| Place a check mark to activate Amazon FBA.

| *Referrer*
| Select whether only orders from Amazon should be processed with FBA or whether orders from other xref:orders:order-referrer.adoc#[referrers] should be processed with FBA as well.

! *Paid on*
! Select *Incoming payment booked* if the incoming payment should be displayed as booked when MFN and FBA orders are imported.

! *Credit note import*
! Select whether Amazon credit notes for MFN and FBA orders should be imported into your plentymarkets system.

* *No* (default) = Credit notes are not imported. If you select *No*, create an event procedure to import returns into your plentymarkets system in form of credit notes. +
* *Yes* = Amazon credit notes are imported into your plentymarkets system every 4 hours.

!===

*_Note:_* These settings apply to both own shipping (MFN) and to shipping by Amazon (FBA).
|===
////