[.instruction]
Creating a catalogue:

. Go to *Data » Catalogues*.
. Click on *Create catalogue* (material:add[]).
. Enter a name for the catalogue.
. In the drop-down list *Export type*, select the option *{catalogue-template-name}*. +
ifdef::limango[*_Note:_* Select the format *limango new*, not the old format *limango*.]
ifdef::catalogue-plugin[*_Note:_* The export type *{catalogue-template-name}* is only shown when the plugin *{plugin}* is installed.]
ifdef::general-catalogue-info[*_Hinweis:_* The export types of some markets can only be selected after you have installed and provisioned the plugin for that market.]
ifdef::format-item-new[. In the drop-down list *Format type*, select the option *Item (new)*.]
ifndef::format-item-new[. In the drop-down list *Format type*, select the option *Item*.]
ifdef::one-per-category[. In the drop-down list *Format*, select a category of the marketplace. +]
ifdef::etsy[]
. From the drop-down list *Format*, select the option *Etsy*. +
*_Tip:_* You can only create one catalogue for this market. Thus, the only format you can select is the name of the market.
endif::[]
ifndef::one-per-category,etsy[]
. In the drop-down list *Format*, select the option *{catalogue-template-name}*. +
*_Tip:_* You can only create one catalogue for this market. Thus, the only format you can select is the name of the market.
endif::[]
ifdef::idealo[. Select the *idealo account* that you want to create a catalogue for.]
ifdef::Check24[*_Tip:_* You can create one catalogue for the category Check24 and one catalogue for the category Check24 Offer.]
. Save (terra:save[]) the settings. +
→ The catalogue is created. +
→ The catalogue is opened for editing. +
ifdef::decathlon[]
. On the left-hand side of the menu, click on material:settings[] *Settings*.
. In the *Basic settings*, select the *account* that you want to use this catalogue for.
. Save (terra:save[]) the settings.
endif::decathlon[]

ifndef::url-export,price-search-engine[]

ifdef::decathlon[]
[IMPORTANT]
.Select account and add filters
====
It is mandatory to select a Decathlon account in the catalogue’s *Settings* so that the catalogue can be exported to Decathlon. +

Additionally, we recommend to set *filters* before you activate the catalogue. This is to ensure that your items are exported into the correct Decathlon product category. For further information, see <<#link-product-category, Linking variations to a Decathlon product category>>.
====
endif::decathlon[]

[discrete]
===== Other catalogue settings

Other catalogue settings are optional. Once you carried out the settings described on this page, your catalogue is automatically exported to {market}. That means you can ignore the catalogue settings for *Format settings*, *Export settings* and *Download settings*.

The *Format settings*, *Export settings*, and *Download settings* allow you xref:data:export-marketplace-formats.adoc#file-export[to create a file with the variation data contained in the catalogue]. However, this file does not contain information about whether the data export to {market} was successful.
endif::url-export,price-search-engine[]

*_Note:_* You should not change the *format* in the catalogue's *Format settings*. To ensure that the export to the market works, all required settings are already configured when you create a catalogue. If you change the settings, errors might occur during the export.