After you created a marketplace format for {market} with the *{assistant-name} Catalog* assistant or manually, the property *{market}* is created in your plentymarkets system. A new selection value is added to the *{market} category group* property for each category selected in the *Settings* step of the assistant. In order for your variations to be exported in the appropriate catalogue, they have to be linked to the *{market} category group* property in the *Properties* tab of a variation.

[.instruction]
Linking a variation to a category:

. Go to *Item » Edit item » [Open item]*.
. Click on the *Variations* tab.
. Open the variation that should be linked.
. Open the *Properties* tab.
. In the *Variation properties* area, select the property *{market} category group* from the *Properties* drop-down list and click on *Add* (icon:plus-square[role="green"]). +
→ The property is added.
. Select the desired category group from the *Value* drop-down list for the *{market} category group* property. +
→ The variation will be exported in this catalogue. +
*_Example:_* If you pick the value *{category-example}*, the catalogue variation is exported for the *{category-example}* category.
. Repeat steps 5 and 6 for all categories where you want to offer the variation.
. Save (icon:save[set=plenty]) the settings.

[discrete]
=== Further possibilities to link variations

* via import: Go to *Setup » Settings » Properties » Configuration*, open the property *{assistant-name} category mapping* and click on *Values*. You can find there the selection value IDs that are needed for the import.
* via REST API: Use the REST routes from the areas link:https://developers.plentymarkets.com/en-gb/plentymarkets-rest-api/index.html#/Property[Property^] and link:https://developers.plentymarkets.com/en-gb/plentymarkets-rest-api/index.html#/Item[Item^] to link the catalogue with the variation. +
*_Note_*: If no marketplace category is available in the assistant *{assistant-name} Catalog*, you might have entered the wrong API environment in the *Authentication* step of the assistant *{assistant-name}*.
