The orders are automatically imported in your plentymarkets system every 15 minutes.
ifdef::voelkner[]
Once Voelkner has accepted the order, the payment is collected by Voelkner.
endif::voelkner[]
ifdef::conrad,mediamarkt[]
The seller accepts the order via an event procedure. The payment is collected by {market}.
endif::conrad,mediamarkt[]
With the payment confirmation, the invoice and delivery address on the order are updated in your plentymarkets system. Via an event procedure, the shipping service provider as well as the package number are updated on the order in Mirakl.
ifdef::conrad,voelkner[]
In the next step, the shipping notification is reported to {market} via another event procedure. The invoice created by {market} is imported to the order in your plentymarkets system.
endif::conrad,voelkner[]
ifdef::mediamarkt,voelkner[]
Via an event procedure, an invoice is sent to Mediamarkt.
endif::mediamarkt,voelkner[]
ifdef::conrad,mediamarkt[]
You can also set up event procedures for refunds and order cancellations.
endif::conrad,mediamarkt[]
ifdef::voelkner[]
You can also set up event procedures for refunds.
endif::voelkner[]

[#event-procedures]
== Setting up event procedures

Set up an <<automation/event-procedures#, event procedure>> to automatically update the order status on {market} whenever specific events occur. You can set up the following event procedures:

ifdef::EP-order-confirmation[]
* Report order confirmation to {market}
endif::EP-order-confirmation[]
ifdef::EP-order-rejection[]
* Report order cancellation to {market}
endif::EP-order-rejection[]
ifdef::EP-shipping-confirmation[]
* Report shipping confirmation to {market}
endif::EP-shipping-confirmation[]
ifdef::EP-cancellation[]
* Report order cancellation to {market}
endif::EP-cancellation[]
ifdef::EP-refund[]
* Report refund to {market}
endif::EP-refund[]
ifdef::EP-send-invoice[]
* Send invoice to {market}
endif::EP-send-invoice[]

How to set up the event procedures in plentymarkets is described in the following chapters.

[IMPORTANT]
.Additional procedures
====
In addition to the event procedures listed above, the {market} plugin provides several other event procedures. These procedures exist because order processing differs between plentymarkets and Mirakl.

However, we recommend that you only use the procedures described in detail.
====
