//tag::create-properties[]
Properties can be used to map the market’s data fields for which there is no designated setting in plentymarkets when exporting item data using a catalogue.  To do so, create a property. In the catalogue, you map this property to the data field of the market.

[.collapseBox]
.What’s a property?
--
Properties can be used to provide more details about your variations. For example, you can specify technical details of a variation by creating a property, e.g. the property _Bluetooth_ for headphones. +
Moreover, you can use properties to save information which is required by the market but has no designated setting in plentymarkets. This way, when exporting item data using a catalogue, you can create properties for each marketplace data field which has no designated setting in plentymarkets. For example, if specific information about contact lenses is required by the market, you can save this information by creating properties. +
Would you like to know more about properties? For further information, refer to the xref:item:properties.adoc#500[Characteristics and properties] page.
--
//end::create-properties[]

ifdef::conrad,voelkner[]
The following properties are created automatically in your plentymarkets system and mapped in the assistant when you install the plugins:

* Logistics class
* Leadtime to ship (Versandvorlaufzeit)
* Reverse charge (Abzugsverfahren)
* update-delete
endif::conrad,voelkner[]

ifdef::mediamarkt[]
You can create the properties that are specified by MediaMarkt in the *Setup » Settings » Properties » Configuration* menu.
For MediaMarkt, you need the following properties:

* <<#property-logistic-class, Logistics class>>
* <<#property-leadtime-to-ship, leadtime to ship>>
* update-delete
endif::mediamarkt[]

ifdef::mediamarkt[]
[#property-logistic-class]
=== Logistics class: Creating the property

For each variation, you need to export a shipping profile code to {market}. You can configure shipping profiles in the Mirakl back end. For a list of shipping profiles, refer to the *Platform settings > Shipping* menu in the Mirakl back end. You can find the code in the *Logistics class* column in brackets behind the name of the logistics class.

:property: Logistics class

include::partial$properties-creation.adoc[]

:property: Logistics class
:property-area: Item
:property-type: text
:property-name: {market} logistics class

include::partial$properties-creation-table.adoc[]
endif::mediamarkt[]

ifdef::mediamarkt[]
[#property-leadtime-to-ship]
=== Leadtime to ship: Creating the property

You can export a lead time to ship for every variation. The lead time to ship is the time in days that sellers need from accepting the order to confirming shipping. +
*_Note:_* You have to enter a whole number between 1 and 45 for the leadtime to ship.

:property: Leadtime to ship

include::partial$properties-creation.adoc[]

:property: Leadtime to ship
:property-area: Item
:property-type: whole number
:property-name: {market} leadtime to ship

include::partial$properties-creation-table.adoc[]
endif::mediamarkt[]

[#property-attributes]
=== Creating properties for attributes

If you’ve defined more than one xref:item:attributes.adoc#[attributes] for any of your variations, create a property that combines these attributes. For example, if you distinguish a variation both by colour and by size, you can create a property called “Grey XL”. Then, xref:item:properties.adoc#1400[link these properties] to your variations.

[#additional-properties]
=== Creating additional properties

In addition to the properties described previously, you need properties for all data fields of the marketplace whose data you want to export, but that don’t have a designated setting in plentymarkets. You can see by the data fields in the market’s catalogue which properties you need. Mandatory fields which have to be transferred to the market are marked with an asterisk (*).
