[#register]
== Registering with {market}

First, become a link:{registration-url}[{market}^]{nbsp} member and create a {market} account. After registering, you will receive login details from {market}. You need these login details to set up {market} in plentymarkets.

//TODO: insert Frequency of data exchange

[#download-plugins]
== Downloading and installing the plugins

You need the following plugins to send item data to {market}:

[.collapseBox]
.Why do I need two plugins?
--
{market} is connected with plentymarkets via the platform Mirakl. To sell your items on the {type-of-market} {market} with plentymarkets, you also need the *Mirakl Connector* plugin. The *Mirakl Connector* allows {market} and plentymarkets to automatically exchange item and order data and you can offer your items on {market}.
--

* link:https://marketplace.plentymarkets.com/mirakl_6917[Mirakl Connector^]
* link:{plugin-link}[{plugin-name}^]

:plugin: Mirakl Connector
:priority: 0
:main-client:

include::partial$plugin-installation.adoc[]
:!plugin:

:plugin: {plugin-name}
:priority: 1
:main-client:

include::partial$plugin-installation.adoc[]
:!plugin:

ifdef::video-id[]
[#webinar]
== Setup: Webinar

To set up {market} in plentymarkets, you can either follow the instructions on this page or have a look at the following webinar:

video::{video-id}[youtube]

endif::video-id[]
