With the attribute help tool, you can search for different attributes and take a look at the valid attribute values. In order to use the tool, you need to have completed the *{assistant-name}* assistant. +

You can find the attribute help tool under the following URL: `domain/marketplace_extension/attribute_values`.
Replace `domain` with your plenty domain. +
For example, if your domain was called `https:://www.my-plenty-domain.com`, the URL would be set up as follows: `https://www.my-plenty-domain.com/{market}_extension/attribute_values`.

*_Tip:_*
Enter `SAP.TaxIndicator` into the search field of the attribute help tool to find the valid values for *VAT class*. +
Enter `SAP.BaseUnits` into the search field of the attribute help tool to find the valid values for *Sales unit*.

[IMPORTANT]
.Attribute values will be displayed on the following day
====
The table of the valid attribute values is updated over night. After you installed the plugin in your plentymarkets system, the valid values will not be displayed until the next day. +
In case you entered the wrong API environment and/or the wrong API key in the assistant, the valid attribute values cannot be loaded.
====

In the catalogue you will find the names of the marketplace attributes, such as *Brand*. To find out which values are valid for a specific attribute, proceed as follows.

[.instruction]
Using the attribute help tool:

. Enter the URL in your browser. +
→ You can find the attribute help tool under the following URL: `domain/marketplace_extension/attribute_values`. Replace `domain` with your plenty domain. For example, if your domain was called `https:://www.my-plenty-domain.com`, the URL would be set up as follows: `https://www.my-plenty-domain.com/{market}_extension/attribute_values`.
. Enter the name of the attribute into the search field or press Ctrl+F or Cmd+F to browse through the search results. +
→ The attribute is shown in the *Attribute label* column. +
→ The column *Value Code* lists the valid values that have to be transferred for the attribute values listed in the *Value Label* column.

== Mapping and transferring valid attribute values

In case there are different attribute values that might be valid depending on the variation that you want to transfer, the first question is how you keep your item data up-to-date.
If you manage your item data manually, it is recommended to use a property of the type *Selection*. You can save a description for the selection here. This description will then be shown in the property overview at the variation.
Once the code was mapped to the property, you can use the real name of the variation in the field *Description*. This means the code is transferred via the catalogue and the real name is shown in brackets behind. +

*_Tip:_* If you always want to transfer only one single value for an attribute, e.g. you want to use always *BRAND_12345678* for the brand, you can use the option *Own value* in the catalogue.
