In the catalogue, you can see the marketplace data fields that you can export to {market}. {market} also calls these data fields "attributes". The market expects specific values for most of these data fields. This is where the *attribute help tool* comes in handy. Enter a data field into this tool to find out which values are currently valid. In order to use the tool, you need to have completed the *{assistant-name}* assistant.

*_Tips:_*

* Enter `SAP.TaxIndicator` into the search field of the attribute help tool to find the valid values for *VAT class*. +
* Enter `SAP.BaseUnits` into the search field of the attribute help tool to find the valid values for *Sales unit*.

To find out which values are valid for a data field, proceed as follows.

[.instruction]
Using the attribute help tool:

. Enter the following URL into your browser: +
  * `[your-domain]/{market-attribute-help-tool}_extension/attribute_values`
. Replace `[your-domain]` with your plentymarkets domain. +
*_Example:_* For the plentymarkets domain `\https://www.my-plenty-domain.com` the URL would be `\https://www.my-plenty-domain.com/{market}_extension/attribute_values`.
. Enter the name of the data field into the search field or use Ctrl+F or Cmd+F to search the list of results. +
→ The column *Attribute Label* contains the data field. +
→ The column *Value Code* contains the values that can be exported for this data field.

=== Tip: Linking valid values

Most {market} attributes are codes, so they can be cryptic. Brands are a good example. The code is based on the pattern `BRAND_12345678`. So it can be a bit tricky to keep track of the different values and linking them to your variations. We recommend the following workflow:

* Create a property of the type *Selection*.
* Save the codes as selection values.
* Save the real value of the code in the value's *Description* field.
* Links the property with the variation.
* In the column *Value*, click on the drop-down list. +
→ In the list of values, the code is shown with the description in brackets. +
→ The catalogue only exports the code.

*_Tip:_* If you want to export the same value for every variation, you can use the catalogue option *Own value* instead of a property.
