[#archive-orders]
== Archiving unconfirmed orders

When an order was rejected or cancelled, or there’s a credit note for an order, you should archive the order. You can do this automatically by using the procedure manager.

You have to create a separate procedure for each status.

[#1110]
=== Archiving rejected orders

[.collapseBox]
.Setting up a procedure:
--
[.instruction]
Setting up a procedure:

. Go to *Setup » Orders » Procedures*.
. Click on the *New action* tab.
 Carry out the desired settings according to <<#{market}-procedure-manager-rejected-orders>>.
. Click on the *Filter* tab.
. Carry out the desired settings according to <<#{market}-procedure-manager-rejected-orders>>.
. Click on the *Procedure* tab.
. Carry out the desired settings according to <<#{market}-procedure-manager-rejected-orders>>.
. Save (icon:save[set=plenty]) the settings. +
→ The procedure is created.

--

[#{market}-procedure-manager-rejected-orders]
.Procedure manager settings
[cols="1,3a"]
|===
|Tab |Setting

| *Status*
| Activate the option *Active*. +
Select when the procedure should be carried out each day. +
Enter a name.

| *Order type*
| From the *Status* drop-down list, select the option *[7] Outgoing items booked*. +
From the *Last status change* drop-down list, select the option *Enter the days*. Enter the value `2` in the new text field. +
From the *Order referrer* list, select the option *{market}*.

| *Procedure*
| Select a final status from the *Change order status* drop-down list, for example *[7.99]*.

|===

[#1120]
=== Archiving cancelled orders

[.collapseBox]
.Setting up a procedure:
--
[.instruction]
Setting up a procedure:

. Go to *Setup » Orders » Procedures*.
. Click on the *New action* tab.
. Carry out the desired settings according to <<#{market}-procedure-manager-cancelled-orders>>.
. Click on the *Filter* tab.
. Carry out the desired settings according to <<#{market}-procedure-manager-cancelled-orders>>.
. Click on the *Procedure* tab.
. Carry out the desired settings according to <<#{market}-procedure-manager-cancelled-orders>>.
. Save (icon:save[set=plenty]) the settings. +
→ The procedure is created.

--

[#{market}-procedure-manager-cancelled-orders]
.Procedure manager settings
[cols="1,3a"]
|===
|Tab |Setting

| *Status*
| Activate the option *Active*. +
Select when the procedure should be carried out each day. +
Enter a name.

| *Order type*
| From the *Status* drop-down list, select the option *[8] Cancelled*. +
From the *Last status change* drop-down list, select the option *Enter the days*. Enter the value `2` in the new text field. +
From the *Order referrer* list, select the option *{market}*.

| *Procedure*
| Select a final status from the *Change order status* drop-down list, for example *[8.99]*.

|===

[#1130]
=== Archiving order with credit notes

[.collapseBox]
.Setting up a procedure:
--
[.instruction]
Setting up a procedure:

. Go to *Setup » Orders » Procedures*.
. Click on the *New action* tab.
. Carry out the desired settings according to <<#{market}-procedure-manager-credit-notes>>.
. Click on the *Filter* tab.
. Carry out the desired settings according to <<#{market}-procedure-manager-credit-notes>>.
. Click on the *Procedure* tab.
. Carry out the desired settings according to <<#{market}-procedure-manager-credit-notes>>.
. Save (icon:save[set=plenty]) the settings. +
→ The procedure is created.

--

[#{market}-procedure-manager-credit-notes]
.Procedure manager settings
[cols="1,3a"]
|===
|Tab |Setting

| *Status*
| Activate the option *Active*. +
Select when the procedure should be carried out each day. +
Enter a name.

| *Order type*
| From the *Status* drop-down list, select the option *[11] Credit note*. +
From the *Last status change* drop-down list, select the option *Enter the days*. Enter the value `2` in the new text field. +
From the *Order referrer* list, select the option *{market}*.

| *Procedure*
| Select a final status from the *Change order status* drop-down list, for example *[11.99]*.

|===
