ifdef::voelkner[]
== Error reports

In the plentymarkets back end, you will see the following areas:

* For product exports go to *Data » Voelkner item export reports*
* For offer exports go to *Data » Voelkner offer export reports*
endif::voelkner[]

[#mirakl-faq]
== FAQ and troubleshooting

[.collapseBox]
.The wrong stock was exported for one or more variations. What can I do?
--

First, check the stock settings: Does the problem only affect variations without stock limitation?

*_How can I recognise variations without stock limitation?_*

. Open the variation: *Item » Edit item » [Open variation] » Tab: Settings » Area: Availability*.
. Check the setting for the drop-down list *Limitation*.
. Is this set to either *None* or *Do not administer stock for this variation*? Then the variation has no stock limitation. +
*_Tip:_* You can also filter variations in the item overview. Set the filter *Stock limit* first to *No limitation* and then to *Do not administer the stock*. Only variations without stock limitation are shown. This allows you to find patterns in the variations that were not exported.


*_How do I check that the settings for variations with no stock limitation are correct?_*

. Open the assistant *Setup » Assistants » Plugins » [Select plugin set] » Assistant: {assistant-name}*.
. Navigate to the step *Offer export settings*.
. Check that the following settings are correct:
  * The setting *Replace stock amount for items not limited to stock* is active.
  * The field *Quantity for items not limited to stock* contains a number that is higher than 0.
. Modify the settings as needed.

*_Important:_* Offers for variations without stock limitations are exported to {market} once daily during the night. As such, variations are not exported immediately when you change these settings.

--

[.collapseBox]
.You cannot access the attribute help tool.
--
*_Possible reasons:_*

* You have not completed the assistant *{assistant-name}*.
* You see *Your plentymarkets store is currently under construction* instead? Your plentyShop is probably locked. Go to *Setup » plentyShop » (Select client) » Lock store* to unlock your plentyShop. Do not forget to lock your plentyShop once you are done.
* The table of valid attribute values is always updated over night. As such, after you installed the plugin in your plentymarkets system, the valid values will not be shown until the next day.
* In case you entered the wrong API environment and/or the wrong API key in the assistant, the valid attribute values cannot be loaded.
--

[.collapseBox]
.You cannot access the attribute help tool and see the message "Your plentymarkets store is currently under construction" instead?
--
Your plentyShop is probably locked. Go to *Setup » plentyShop » (Select client) » Lock store* to unlock your plentyShop. Do not forget to lock your plentyShop once you are done.
--
