SKU are generated automatically when your variations are exported. However, you can also save market specific SKU for variations that you want to sell on this market instead.

ifdef::sku-cdiscount[]
[IMPORTANT]
.Automatic SKU generation
====
If the *Request product creation* setting is activated in the *Setup » Markets » Cdiscount.com » Tab: Settings* menu, an SKU is generated for each exported variation during the nightly export. This SKU matches the variation ID.
====

[IMPORTANT]
.SKUs of already existing items
====
Do you want to sell products that you have previously created on Cdiscount manually or using a different software? Link these products with your variations in plentymarkets. To do so, save the identification as an SKU in plentymarkets. The identification can be found as *Your reference* in the Cdiscount seller back end.
====
endif::sku-cdiscount[]

[.tabs]
====
Manually adding an SKU::
+
--
. Go to *Item » Edit item » [Open item] » [Open variation] » Tab: Settings*.
. Click on the *Availability* tab.
. In the *SKU* area, click on *Add* (icon:plus-square[role="green"]). +
→ The *New SKU* window opens.
. Select the referrer *{referrer-sku}*. +
ifdef::sku-netto[]
*_Tip:_* The referrer *Plus.de* also covers the market Netto Marken-Discount when you add SKUs.
endif::sku-netto[]
ifdef::sku-account[]
. Select the corresponding marketplace account.
endif::sku-account[]
. Enter the SKU.
. Click on *Add* (icon:plus-square[role="green"]). +
→ The SKU is saved and displayed.
--

Importing SKU::
+
--

TIP: Only the most important settings for the import are described here. Is this your first time working with the import tool? Then get familiar with <<data/importing-data/ElasticSync#, how data imports work in plentymarkets first>>.

* Create a CSV file with at least the columns described in <<#table-sku-import>>.
* Create an import with the following settings:
  ** Select the type *Item*.
  ** Select the matching field *Variation ID*.
  ** Map the plentymarkets data fields as described in <<#table-sku-import>>.

[[table-sku-import]]
.Recommended columns of the import file
[cols="1a,3a,2a"]
|======
|Column in CSV file |Explanation |plentymarkets data field for mapping

| Variation ID
| Enter the variation ID in this column.
| *Variation ID*

| Market ID
| Enter the referrer ID *{referrer-id}* in this column.
| *SKU* > *Marketplace ID*

| Account ID
|
ifdef::sku-amazon[]
Enter the ID of the marketplace account in this column. +
*_Tip:_* To find the marketplace account ID go to +
*Setup » Markets » Amazon » Settings*
endif::sku-amazon[]
ifdef::sku-ebay[]
Enter the ID of the marketplace account in this column. +
*_Tip:_* To find the marketplace account ID go to +
*Setup » Markets » eBay » Settings » Account settings*
endif::sku-ebay[]
ifdef::sku-rakuten[]
Enter the ID of the marketplace account in this column. +
*_Tip:_* To find the marketplace account ID go to +
*Setup » Markets » Rakuten.de*
endif::sku-rakuten[]
ifdef::sku-client[]
Enter the plenty ID of the client in this column. +
*_Tip:_* To find the plenty ID go to +
*Setup » Client » [Select client] » Settings » Option: Plenty ID*
endif::sku-client[]
ifdef::sku-others[]
This market does not require a marketplace account. As such, enter the number *0* in this column.
endif::sku-others[]
| *SKU* > *Marketplace ID*

| SKU
| Enter the SKU that you want to save for the variation for this market in this column.
| *SKU* > *SKU*
|======
--
====
'''

////
:referrer-sku: xxxx
:referrer-id: xxx
// :sku-others:
// :sku-client:
// :sku-amazon:
// :sku-ebay:
// :sku-rakuten:

...
////
