There are a number of reports available for Zalando. Go to the *Setup » Markets » Zalando » Settings » Tab: processing reports* menu to download the following reports:

[cols="1,3a"]
|===
|Report |Explanation

2+^| *Export-Log*

| *zalandoArticleExportLog.txt*
a| The export log *zalandoArticleExportLog.txt* contains log entries for variations. The export log is generated once every night. The file contains entries for variations that were exported successfully and for variations that could not be exported to Zalando.

<<#905, How to download the export log>>

2+^| *Reports*

| *Product status reports*
a| Zalando generates the product status reports are generated once daily during the night. These reports only contain information regarding variations that were successfully exported to Zalando.

[cols="1,3"]
!===
! *_ProductErrorReport.csv_*
! Contains variations that cannot be sold on Zalando since the last export. The report is generated once every night.

! *_ProductLiveReport.csv_*
! Contains variations that can be sold on Zalando since the last export as well as stock and price of each variation on the different Zalando channels (DE, FR, etc.) at the time that the file was generated. The report is generated once every night.
!===

<<#910, How to download product status reports>>

| *Price reports*
a| Zalando generates a price report for each active channel once daily during the night. These reports contain information on the processing status of all price updates that Zalando received in the last seven days.

<<#915, How to download price reports>>
|===

[#905]
=== Downloading the export log

The export log contains plentymarkets log entries. The file contains entries for variations that were exported successfully and for variations that could not be exported to Zalando.

[.instruction]
Downloading the export log:

. Go to *Setup » Markets » Zalando » Settings*.
. Click on the *Processing reports* tab.
. In the *Export log* area, click on *Download file* (icon:eye[role="blue"]). +
→ The CSV file is generated.
. Save the CSV file on your computer.
. Filter the entries to only see the status *error*.
. Check the entries. Correct any variation data in the plentymarkets back end. +
*_Tip:_* You can ignore any entries with the status *warning*.

[[zalando-errors]]
.Error messages in the export log (zalandoArticleExportLog.txt)
[cols="1,3a"]
|===
|Setting |Explanation


| specialDescriptions
| Technical data

| brand
| Characteristic *Zalando » Hersteller-Code* (manufacturer code)

| season
| Characteristic *Zalando » Jahreszeiten-Code* (season code)

| genders
| Characteristic *Zalando » Geschlecht* (gender)

| ageGroups
| Characteristic *Zalando » Altersgruppe(n)* (age groups)

| sizeRegister
| Characteristic *Zalando » Größen-Register* (size register)

| mainColorCode
| From the Characteristic *Zalando » 1. Farbcode* (Zalando » 1st colour code) +
*_Exception:_* The variation has a colour attribute. In that case, attribute links are used to manage colours.

| supplierColor
| Characteristic *Zalando » Hersteller-Farbe* (Zalando » Manufacturer colour) or an optional 2nd attribute link

| images
| The variation must have at least one image.

| ean
| The variation needs a GTIN 13.

| lengthRegister
| Characteristic *Zalando » Längen-Register* (length register)

| Keywords
| Meta keywords (item tab: Texts)
|===

[#910]
=== Downloading product status reports

Product status reports contain information regarding the items that were exported to Zalando. These reports are generated by Zalando. As such, these reports only contain information regarding variations that were successfully exported to Zalando. The following reports are available:

* *_ProductErrorReport.csv_*: Contains variations that cannot be sold on Zalando since the last export. The report also contains the first five error codes and an error description. The report is generated once every night. Click on *Update file* (icon:cog[]) before downloading the file to get current data from Zalando.
* *_ProductLiveReport.csv_*: Contains variations that can be sold on Zalando since the last export. The report also contains information on the stock and price of the variations on the different Zalando channels (DE, FR, etc.) at the time the file was generated. The report is generated once every night. Click on *Update file* (icon:cog[]) before downloading the file to get current data from Zalando.

[.instruction]
Downloading a product status report:

. Go to *Setup » Markets » Zalando » Settings*.
. Click on the *Processing reports* tab. +
→ The following files can be downloaded in the *Product status reports - Account ID* area:

  * *_ProductErrorReport.csv_* contains the variations that cannot be sold on Zalando since the last export.
  * *_ProductLiveReport.csv_* contains the variations that can be sold on Zalando since the last export.

. *_Optional:_* By default, the file is updated once every night. To get current data from Zalando before downloading the file, go to the *Product status-reports - Account ID* area and click on *Update file* (icon:cog[]).
. Go to the *Product status reports - Account ID* area. In the row of a processing report click on *Download file* (icon:eye[role="blue"]). +
→ The CSV file is generated.
. Save the CSV file on your computer.

[#915]
=== Downloading price reports

Zalando generates a price report for each active channel once daily during the night. These reports contain information on the processing status of all price updates that Zalando received in the last seven days. As such, the reports may contain several entries for the same EAN.

[.instruction]
Downloading price reports:

. Go to *Setup » Markets » Zalando » Settings*.
. Click on the *Processing reports* tab. +
→ In the area *Price reports*, files are available for all active channels.
. *_Optional:_* By default, the file is updated once every night. In the column *Actions*, click on *Update file* (icon:cog[]) to get current data from Zalando before downloading the file.
. Go to the *Price reports* area. In the row of a processing report, click on *Download file* (icon:eye[role="blue"]). +
→ The CSV file is generated.
. Save the CSV file on your computer.

[.collapseBox]
.What information do the price reports contain?
--
[cols="1,3"]
|===
| Timestamp
| Corresponds to the latest timestamp from the columns *Status History* and *Scheduled Price (1-3) - Status History*.

| EAN
| The EAN of the variation whose price has been updated.

| Ignore Warnings?
| Corresponds to the setting *Ignore Warnings* in the *Setup » Assistants » Omni-Channel » Zalando account settings » [Open account] » Step: Prices for [target country]* menu at the time the update was transferred.

| Regular Price
| Transferred value of the regular price.

| Regular Price Currency
| Transferred currency of the regular price.

| Promotional Price
| Transferred value of the reduced price.

| Promotional Price Currency
| Transferred currency of the reduced price.

| Status
a| Status of the processing. Possible statuses:

[cols="1,3"]
!===
! RECEIVED
! The price has been received.

! ACCEPTED
! The price has been accepted and forwarded for further validation.

! REJECTED
! The price has not passed validation. See the status messages in *Status History* for more information.

! FAILED
! An unexpected error occurred during the price update. See the status messages in *Status History* for more information.

! SCHEDULED
! The price has been successfully validated and is awaiting submission.

! SUBMITTED
! The price has been submitted and will be shown in the shop shortly.

! AWAITING_ONBOARDING
! The price has been accepted but the item has not yet been activated. The price will be applied once onboarding is complete.
!===

| Status History
a| Status change history. For each change, the cell contains a paragraph with the following pattern (placeholders in square brackets):

* [timestamp]: FROM [original status] TO [new status] - code: [code] [severity] [message]

| Scheduled Price (1-3) - Start
| Start date of the scheduled price.

| Scheduled Price (1-3) - End
| End date of the scheduled price.

| Scheduled Price (1-3) - Regular Price
| Transferred value of the regular price for the scheduled price.

| Scheduled Price (1-3) - Regular Price Currency
| Transferred currency of the regular price.

| Scheduled Price (1-3) - Promotional Price
| Transferred value of the reduced price.

| Scheduled Price (1-3) - Promotional Price Currency
| Transferred currency of the reduced price.

| Scheduled Price (1-3) - Status
a| Status of the processing of the scheduled price. Possible statuses:

[cols="1,3"]
!===
! RECEIVED
! The price has been received.

! ACCEPTED
! The price has been accepted and forwarded for further validation.

! REJECTED
! The price has not passed validation. See the status messages in *Scheduled Price (1-3) - Status History* for more information.

! FAILED
! An unexpected error occurred during the price update. See the status messages in *Scheduled Price (1-3) - Status History* for more information.

! SCHEDULED
! The price has been successfully validated and is awaiting submission.

! OVERRIDDEN
! The price was scheduled but overwritten by a new price update before it could be submitted.

! SUBMITTED
! The price has been submitted and will be shown in the shop shortly.

! AWAITING_ONBOARDING
! The price has been accepted but the item has not yet been activated. The price will be applied once onboarding is complete.
!===

| Scheduled Price (1-3) - Status History
a| History of the status change of the scheduled price. For each change, the cell contains a paragraph with the following pattern (placeholders in square brackets):

* [Timestamp] from [Original Status] to [New Status] - Code [code] Severity [severity] Message [message]
|===
--

[#1010]
== Viewing the data log

:market: Zalando
include::partial$viewing_logs.adoc[tag=data-log-intro]

* *Identifier* » *Zalando*

include::partial$viewing_logs.adoc[tag=data-log-config]

Use any filters listed in <<#table-reference-types>> to limit the search results.

[[table-reference-types]]
.Filters
[cols="1a,2a,2a"]
|===
|Log entries |Recommended filters |Explanation

| Price updates
| * Identifier » Zalando
* Level: Error
* References:
    ** Reference type » action +
    Reference value » PriceUpdate
    ** Reference type » ean +
    Reference value » EAN of variation
| While the <<#915, price reports>> are generated, an error log is also written for all entries that have been in the REJECTED, FAILED or OVERRIDDEN status since the file was last generated (minus one hour as a buffer).

| Price reports
| * Identifier » Zalando
* References:
  ** Reference type » action +
  Reference value » PriceReporting
| Log entries for errors during generation of price reports

| Stock synchronisation
| * Identifier » Zalando
* References:
  ** Reference type » action +
  Reference value » StockUpdate
  ** Reference type » variationId
  ** Reference type » ean
  ** Reference type » accountId
  ** Reference type » salesChannel
  ** Reference type » jobUniqueId
| Log entries for errors during stock updates

|===