= Amazon FBA Inbound
:keywords: Amazon FBA Inbound
:description: Erfahre, wie du Amazon FBA Inbound in plentymarkets einrichtest.
:author: team-fulfillment-payment

Auf dieser Seite findest du einen Überblick über Amazon FBA Inbound sowie die wichtigsten Links, die du im Zusammenhang mit der Einrichtung von Amazon FBA Inbound benötigst.

== Was bedeutet Inbound?

Inbound bedeutet, dass du Amazon mit Waren versorgst, die Amazon an deine Kundschaft liefert.

* Inbound-Sendungen sind deine Sendungen an ein Amazon FBA-Logistikzentrum.

* Inbound-Aufträge sind die Aufträge, die in plentymarkets für deine Inbound-Sendungen erstellt werden.


== Wie ist der FBA Inbound-Ablauf?

Seit dem 01.03.2023 hat sich der Arbeitsablauf der Amazon FBA Inbound API geändert.
Du hast drei Möglichkeiten, deine Sendungen zu erstellen und zu bearbeiten.

[WARNING]
====
Beachte, dass deine Sendungen nur bei einer dieser Optionen für plentymarkets verfügbar bleiben. 
====

=== Reine Bearbeitung im Amazon Seller Central
Du erstellst und bearbeitest deine Sendungen im Seller Central (dort über den Menüpunkt *Sendungen >> An Amazon senden*). Bei dieser Option kann plentymarkets keine Daten von Amazon abrufen. Das heißt, du arbeitest ausschließlich über das Seller Central.

=== Übermittlung über die API / Bearbeitung nur in plentymarkets
Du erstellst die Sendungen in plentymarkets und plentymarkets übermittelt sie über die API an Amazon. Du bearbeitest die Sendungen ausschließlich in plentymarkets. Um diese Option beizubehalten, ist es wichtig, dass du keine Änderungen im Seller Central vornimmst, da sonst die Option 3 greift.

[#amazon-fba-inbound-ablauf]
[.collapseBox]
.Amazon FBA Inbound-Ablauf
--
. Du erstellst im Amazon Seller Central eine FBA-Inbound-Sendung. +
→ Die Sendung wird in plentymarkets importiert, wenn ihr Status im Amazon Seller Central *_In Bearbeitung_* ist. +
→ Die Sendung wird im Menü *Waren » Amazon: Shipments* angezeigt.
. Du erstellst eine Umbuchung für die Sendung. +
→ In plentymarkets wird ein FBA-Inbound-Auftrag im Menü *Waren » Amazon FBA Inbound* erstellt.
. Der Auftrag kann im Lager weiter bearbeitet werden.

[NOTE]
====
Nur Sendungen, die im Amazon Seller Central den Status *_In Bearbeitung_* haben, werden in plentymarkets importiert.
====
--
=== Kombination aus plentymarkets und Seller Central
Du erstellst die Sendungen in plentymarkets wie oben beschrieben und kannst sie im Seller Central manuell bearbeiten. Jedoch kann plentymarkets nach der Bearbeitung im Seller Central keine aktualisierten Daten mehr über die API abrufen und du kannst keine Aktualisierungen der Sendungsdaten mehr in plentymarkets durchführen.



== Was muss ich einrichten?

[IMPORTANT]
.Welche Einstellungen muss ich vorab vornehmen?
====
Im Vorfeld musst du folgende Punkte bereits erledigt haben:

* xref:maerkte:amazon-einrichten.adoc[Amazon] ist eingerichtet
* deine xref:maerkte:varianten-vorbereiten.adoc[Varianten] sind vorbereitet
* der xref:maerkte:variantendaten-exportieren.adoc[Variantenexport] ist eingerichtet
====

== Wo finde ich weitere Informationen?

Wie du nun Amazon FBA Inbound einrichtest und deine Inbound-Sendungen an ein Amazon FBA-Logistikzentrum sendest, ist auf der Handbuchseite xref:maerkte:amazon-fba-nutzen.adoc[FBA-Service von Amazon nutzen] beschrieben.

Wenn du schnell und gezielt zu bestimmten Kapiteln gelangen möchtest, hilft dir die folgende Liste weiter:

* xref:maerkte:amazon-fba-nutzen.adoc#60[Lager für Amazon FBA erstellen]

* xref:maerkte:amazon-fba-nutzen.adoc#90[Einstellungen für FBA-Inbound-Sendungen vornehmen]

* xref:maerkte:amazon-fba-nutzen.adoc#130[FBA-Sendung in Amazon Seller Central erstellen]

* xref:maerkte:amazon-fba-nutzen.adoc#125[FBA-Inbound-Sendungen in plentymarkets anzeigen]

* xref:maerkte:amazon-fba-nutzen.adoc#140[Umbuchung für die Sendung erstellen]

* xref:maerkte:amazon-fba-nutzen.adoc#150[FBA-Inbound-Aufträge anzeigen]

* xref:maerkte:amazon-fba-nutzen.adoc#160[FBA-Inbound-Aufträge im Lager bearbeiten]

** xref:maerkte:amazon-fba-nutzen.adoc#200[Pickliste drucken]

** xref:maerkte:amazon-fba-nutzen.adoc#170[Paketinhaltsliste öffnen]

** xref:maerkte:amazon-fba-nutzen.adoc#180[FBA-Inbound-Auftrag bei Amazon anmelden]

** xref:maerkte:amazon-fba-nutzen.adoc#185[FBA-Inbound-Auftrag bei Amazon stornieren]
