= FAQ
:keywords: Häufig gestellte Fragen
:description: Hier findest du Fragen und Antworten aus dem Themengebiet Fulfillment
:author: team-fulfillment-payment

Auf dieser Handbuchseite findest du Fragen und Antworten aus dem Themengebiet Fulfillment. Wir werden diese Liste kontinuierlich um weitere Fragen und Antworten ergänzen.

[#faq-bereich-gegenüberstellung-versand-center]
== Gegenüberstellung: Versand-Center und Versand-Center 2.0

Neben der Anpassung an andere neue Benutzeroberflächen bietet das neue Versand-Center 2.0 bereits einige neue und praktische Features:

* Du kannst bei der Auftragsanmeldung nun jeweils einen Auftragsstatus für den Erfolgsfall und für den Fehlerfall wählen, in dem die Aufträge nach der erfolgreichen bzw. fehlgeschlagenen Anmeldung landen sollen.
* Gruppenfunktion zum Zurücksetzen von Aufträgen
* Gruppenfunktion zum Herunterladen von Retourenlabels
* Checkbox zum automatischen Download der Versandlabels beim Anmelden der Aufträge
* Eine Spalte mit angemeldeten Retouren kann in der Übersicht angezeigt werden.
* Neue Filter: Auftragsdatum, Auftragstyp, Land
* Die Sendungsverfolgung kann direkt aus dem Versand-Center erfolgen, wenn der Versanddienstleister dies ermöglicht und alles richtig eingestellt ist.
* Du kannst mehr sehen und mehr anpassen.
* Du kannst die gewählten Filter speichern und musst sie bei der nächsten Anmeldung nicht erneut auswählen.
Die Spaltenbreiten sind anpassbar, so dass die Tabellen noch übersichtlicher werden.

Ein entscheidender Unterschied ist, dass das neue Versand-Center keine Tabs mehr verwendet, sondern die Funktionen in Icons hinterlegt sind, die erscheinen, wenn du einen oder mehrere Aufträge auswählst.

Um dich beim Umstieg vom alten auf das neue Versand-Center zu unterstützen, möchten wir im Folgenden ein paar der häufigsten Anwendungsfälle gegenüberstellen. 

[#faq-versandauftrag-anmelden]
[.collapseBox]
.Versandauftrag anmelden (am Beispiel DHL)
--
[cols="1,1"]
|===
|_alt_
|_neu_

a|. Öffne das Menü *Aufträge » Versand-Center*.
Wähle aus der Dropdown-Liste *Versandstatus* die Option *offen*.
. Wähle aus der Dropdown-Liste *Versanddienstleister* die Option *DHL*.
. Klicke auf die Lupe.
→ Die offenen Versandaufträge für DHL werden angezeigt.
. Wechsele in das Tab *Anmelden*.
. Wähle aus der Dropdown-Liste *Versanddienstleister* die Option *DHL Shipping* aus.
. Wähle aus der Dropdown-Liste *Ändere Auftragsstatus* den Auftragsstatus, den die Aufträge nach erfolgreicher Anmeldung erhalten sollen.
. Aktiviere die Aufträge, die du bei DHL Shipping anmelden möchtest.
. Klicke auf *Anmelden*, um die Aufträge zu übertragen.
a|. Öffne das Menü *Aufträge » Versand-Center 2.0*.
. Suche anhand der Filtereinstellungen den Auftrag, den du anmelden möchtest.
→ Die Aufträge, die den eingestellten Suchkriterien entsprechen, werden in der Übersicht angezeigt.
Wähle den Auftrag bzw. die Aufträge, den/die du anmelden möchtest.
. Klicke in der Symbolleiste ganz oben auf *Auftrag anmelden*.
→ Das Fenster *Auftrag anmelden* öffnet sich.
. Wähle den Versanddienstleister, bei dem du den Auftrag anmelden möchtest, aus der Dropdown-Liste (z.B. DHL).
. Wähle den Auftragsstatus, in dem sich der Auftrag nach erfolgreicher Anmeldung beim Versanddienstleister befinden soll, aus der Dropdown-Liste.
. Wähle den Auftragsstatus, in dem sich der Auftrag nach fehlgeschlagener Anmeldung beim Versanddienstleister befinden soll, aus der Dropdown-Liste.
. Klicke auf *Anmelden*.
→ Der Auftrag wird beim Versanddienstleister angemeldet.
→ Der angemeldete Auftrag erhält eine Paketnummer im Bereich *Pakete*.
|===
--
[#faq-versandauftrag-zurücksetzen]
[.collapseBox]
.Versandauftrag zurücksetzen
--
[cols="1,1"]
|===
|_alt_
|_neu_

a|. Öffne das Menü *Aufträge » Versand-Center*.
. Suche den Versandauftrag.
. Klappe den Versandauftrag auf.
. Wechsele in das Tab *Zurücksetzen*.
. Klicke auf *Versand zurücksetzen*.
a|. Öffne das Menü *Aufträge » Versand-Center 2.0*.
. Suche anhand der Filtereinstellungen den Auftrag, den du zurücksetzen möchtest.
→ Die Aufträge, die den eingestellten Suchkriterien entsprechen, werden in der Übersicht angezeigt.
. Wähle den Auftrag bzw. die Aufträge.
. Klicke in der Symbolleiste ganz oben auf *Auftrag zurücksetzen*.
→ Ein Fenster mit einer Sicherheitsabfrage öffnet sich.
Bestätige die Aktion mit einem Klick auf *Auftrag zurücksetzen*.
→ Der Auftrag wird zurückgesetzt.
|===
--
[#faq-versandauftrag-stornieren]
[.collapseBox]
.Versandauftrag stornieren
--
[cols="1,1"]
|===
|_alt_
|_neu_

a|. Öffne das *Menü Aufträge » Versand-Center*.
. Suche den angemeldeten Versandauftrag.
. Klappe den angemeldeten Versandauftrag auf.
. Wechsele in das Tab *Stornierung*.
. Klicke auf *Versand stornieren*.
a|. Öffne das Menü *Aufträge » Versand-Center 2.0*.
. Suche anhand der Filtereinstellungen den Auftrag, den du stornieren möchtest.
→ Die Aufträge, die den eingestellten Suchkriterien entsprechen, werden in der Übersicht angezeigt.
. Wähle den Auftrag bzw. die Aufträge.
. Klicke in der Symbolleiste ganz oben auf *Auftrag stornieren*.
→ Ein Fenster mit einer Sicherheitsabfrage öffnet sich.
. Bestätige die Aktion mit einem Klick auf *Auftrag stornieren*.
→ Der Auftrag wird storniert.
|===
--
[#faq-daten-einzelner-aufträge-bearbeiten]
[.collapseBox]
.Daten einzelner Aufträge bearbeiten
--
[cols="1,1"]
|===
|_alt_
|_neu_

a|. Klappe im Menü *Aufträge » Versand-Center* den angemeldeten Auftrag auf.
. Klicke auf den Stift an der Stelle, an der du Änderungen vornehmen möchtest.
. Speichere die Einstellungen.
a|Du kannst einzelne Pakete konfigurieren, indem du auf die Zeile des entsprechenden Pakets klickst. Es öffnet sich dann ein Fenster, in dem du den Pakettyp, den Typ der Verpackungseinheit, das Paketgewicht, das Paketvolumen und die Paketnummer anpassen kannst. Deine Einstellungen bestätigst du mit einem Klick auf den Button *Paket konfigurieren*.
|===
--
[#faq-retoure-anmelden]
[.collapseBox]
.Retoure anmelden
--
[cols="1,1"]
|===
|_alt_
|_neu_

a|Im Menü *Aufträge » Versand-Center* im Tab *Retoure* meldest du Retouren bei einem Versanddienstleister an. Nach dem Anmelden der Retoure sind die Etiketten als PDF-Dateien verfügbar. Du meldest eine Retoure entweder über den Hauptauftrag oder über die Retoure an.
Um Retourenetiketten abzurufen, meldest du Retouren im Versand-Center bei einem Versanddienstleister an.
a|. Öffne das Menü *Aufträge » Versand-Center 2.0*.
. Suche den Auftrag, für den du eine Retoure anmelden möchtest, anhand der Filtereinstellungen.
→ Die Aufträge, die den eingestellten Suchkriterien entsprechen, werden in der Übersicht angezeigt.
. Wähle den Auftrag bzw. die Aufträge.
. Klicke in der Symbolleiste ganz oben auf *Retoure anmelden*.
→ Das Fenster *Retoure anmelden* öffnet sich.
. Wähle den Retourendienstleister aus der Dropdown-Liste.
. Klicke auf *Retoure anmelden*.
→ Die Retoure wird für den Auftrag angemeldet und die Paketnummer wird am Auftrag gespeichert.
|===
--
[#faq-polling-datei-erzeugen]
[.collapseBox]
.Polling-Datei erzeugen
--
[cols="1,1"]
|===
|_alt_
|_neu_

a|. Öffne das Menü *Aufträge » Versand-Center*.
. Wähle die Suchkriterien für den Auftrag. 
. Aktiviere den Auftrag.
. Wechsele in das Tab *Polling*.
. Wähle den Versanddienstleister.
. Wähle den Auftragsstatus, in den die Aufträge geändert werden sollen.
. Aktiviere die Aufträge, die über den gewählten Versanddienstleister verschickt werden sollen.
. Klicke auf *Anmelden*, um die Polling-Datei zu erzeugen.
→ Die Polling-Datei wird erzeugt. 
. Speichere die Datei auf deinem Computer.
a|. Öffne das Menü *Aufträge » Versand-Center 2.0*.
Suche den Auftrag anhand der Filtereinstellungen.
→ Die Aufträge, die den eingestellten Suchkriterien entsprechen, werden in der Übersicht angezeigt.
. Wähle den Auftrag bzw. die Aufträge.
. Klicke in der Symbolleiste ganz oben auf Polling.
. Wähle den Dienstleister aus der Dropdown-Liste.
. Wähle den Auftragsstatus, in den der Auftrag geändert werden soll.
. Klicke auf *Polling-Datei erstellen*.
→ Die Polling-Datei wird erzeugt.
. Speichere die Datei auf deinem Computer und sende sie an den Versanddienstleister.

|===
--

[#faq-bereich-allgemein]
== Allgemein

[#faq-versandeinstellungen-nicht-geladen-versanddienstleister-nicht-angezeigt]
[.collapseBox]
.Die Versandeinstellungen im Assistenten werden nicht geladen, oder der Versanddienstleister wird nicht angezeigt. Was kann ich tun?
--
Grundsätzlich müssen alle Versanddienstleister-Plugins ständig aktualisiert werden.
Wenn ein neues Plugin installiert und aktiviert wird, müssen alle Anleitungsschritte befolgt werden.

Wenn du einen dieser Fehler feststellst, lies weiter unten nach, wie du das Problem beheben kannst:

* Die Assistenten werden nicht angezeigt.
* Der Versanddienstleister im Versand-Center ist nicht erreichbar.
* Die Fehlermeldung *Unauthorised* erscheint.

Kontrolliere zunächst Folgendes:

. Ist das Plugin auf dem aktuellen Stand und aktiv?
. Ist das Backend-Plugin-Set korrekt ausgewählt worden?
. Wurde das Plugin-Set erfolgreich bereitgestellt? (Speichere die Einstellungen im Set erneut.)
. Wurden die Plugin-Prioritäten korrekt eingestellt (plentyShop LTS, IO)?
. Kontrolliere alle Einstellungen, die in der Beschreibung des Plugins genannt werden.
. Wenn alles gut aussieht, das Problem aber weiterhin besteht, repariere das Plugin oder installiere es ganz neu und speichere die Einstellungen im Set erneut.
. Leere den Cache und versuche danach noch einmal, die Einstellungen aufzurufen bzw. einzurichten.

--

[#faq-eori-nummer]
[.collapseBox]
.Was ist die EORI-Nummer und wo trage ich sie ein?
--
Bei Importen aus Nicht-EU-Ländern in die EU benötigen Firmen und Selbständige für die Zollabfertigung unbedingt eine EORI-Nummer (Economic Operator's Registration and Identification number). Diese ersetzt innerhalb der EU die deutsche Zollnummer. 
In deinem plenty-System trägst du die EORI-Nummer bei Bedarf im Assistenten unter *Einrichtung » Grundeinrichtung » Basics » Firmendaten* in das Feld *EORI-Nummer* ein.
--

[#faq-versandprofil-nicht-ermittelt]
[.collapseBox]
.Das Versandprofil wird nicht ermittelt. Was kann ich tun? 
--
Damit ein Versandprofil für einen Auftrag ermittelt wird, müssen alle Einstellungen korrekt eingerichtet und das Versandprofil am Artikel aktiviert werden. Ausführliche Anleitungen zu diesem Thema findest du auf der Handbuchseite xref:versand-vorbereiten.adoc#[Versand vorbereiten].

Vergewissere dich,

* dass das Versandprofil am Artikel aktiv ist.
* dass das Lieferland / die Versandregion in der Portotabelle des Versandprofils aktiv ist.
* dass Mandant und Auftragsherkunft am Versandprofil aktiv sind.
* dass die Versandgruppe / die Kundenklassen am Versandprofil nicht gesperrt sind.
* ob ein Treueprogramm aktiv ist. Dies sorgt dafür, dass das Versandprofil nur für Aufträge mit dem jeweiligen Treueprogramm verfügbar ist.
* ob es eine Beschränkung in der Portotabelle gibt (z.B. Gewichtsbeschränkung).
* ob am Artikel eine Altersbeschränkung aktiv ist. (Am Versandprofil muss POSTIDENT aktiviert werden.)
* dass die Zahlungsarten am Versandprofil nicht gesperrt sind.
* dass die Zahlungsart für die Kundenklasse aktiv ist.
* dass das Lieferland in der Zahlungsart aktiv ist.

[IMPORTANT]
.Wichtig
====
Wenn du mehrere Versandprofile mit verschiedenen Einstellungen in der *Portotabelle* (*Berechnungstyp* und *Beschränkungstyp*) und diese mit verschiedenen *Kategorien* unter den *Base*-Einstellungen einrichtest, kann dies zu einem Fehler in der Logik führen.

Nutze bitte entweder einen *Berechnungstyp* und/oder *Beschränkungstyp* oder die *Kategorisierung* - so vermeidest du den Fehler und richtest die Einstellungen so ein, dass nur die relevanten Versandprofile für den Auftrag ermittelt werden.
====
[TIP]
.Beachte, dass...
====
...das Versandprofil am Auftrag nur geändert oder aktualisiert werden kann, wenn keine *Rechnung* vorhanden ist. Sobald eine Rechnung erstellt wird, ist die Bearbeitung nur begrenzt möglich. Um die Bearbeitung des Versandprofils in diesem Fall zu ermöglichen, muss ein Stornobeleg angelegt werden.
====

--

[#ebay-fulfillment-by-orange-connex]
[.collapseBox]
.Ich möchte eBay Fulfillment by Orange Connex verwenden,aber es sind keine Dienste verfügbar. Was kann ich tun? 
--
Wenn du die Fehlermeldung erhälst, dass keine Dienste verfügbar sind, kontrolliere die Service-Verknüpfungen im Assistenten von eBay Fulfillment by Orange Connex. Überprüfe auch, ob die Authentifizierung noch gültig ist: Sie läuft nach einem Jahr ab.
Wenn im Assistenten alles in Ordnung ist, melde den Fehler im Forum in der Kategorie Fulfillment/eBay Fulfillment by Orange Connex, so dass wir ihn an unseren Ansprechpartner bei Orange Connex weiterleiten können.
--

