= FAQ
:keywords: Häufig gestellte Fragen
:description: Hier findest du Fragen und Antworten aus dem Themengebiet Fulfillment
:author: team-fulfillment-payment

Auf dieser Handbuchseite findest du Fragen und Antworten aus dem Themengebiet Fulfillment. Wir werden diese Liste kontinuierlich um weitere Fragen und Antworten ergänzen.

[#faq-bereich-allgemein]
== Allgemein

[#faq-versandeinstellungen-nicht-geladen-versanddienstleister-nicht-angezeigt]
[.collapseBox]
.Die Versandeinstellungen im Assistenten werden nicht geladen, oder der Versanddienstleister wird nicht angezeigt. Was kann ich tun?
--
Grundsätzlich müssen alle Versanddienstleister-Plugins ständig aktualisiert werden.
Wenn ein neues Plugin installiert und aktiviert wird, müssen alle Anleitungsschritte befolgt werden.

Wenn du einen dieser Fehler feststellst, kannst du weiter unten nachlesen, was du tun kannst, um das Problem zu beheben:

* Die Assistenten werden nicht angezeigt.
* Der Versanddienstleister im Versand-Center ist nicht erreichbar.
* Die Fehlermeldung *Unauthorised* erscheint.

Kontrolliere zunächst Folgendes:

. Ist das Plugin auf dem aktuellen Stand und aktiv?
. Ist das Backend-Plugin-Set korrekt ausgewählt worden?
. Wurde das Plugin-Set erfolgreich bereitgestellt? (Speichere die Einstellungen im Set erneut.)
. Sind die Plugin-Prioritäten korrekt eingestellt worden (plentyShop LTS, IO)?
. Kontrolliere alle Einstellungen, die in der Beschreibung des Plugins genannt werden.
. Wenn alles gut aussieht, das Problem aber weiterhin besteht, repariere das Plugin oder installiere es ganz neu und speichere die Einstellungen im Set erneut.
. Leere den Cache und versuche danach noch einmal, die Einstellungen aufzurufen bzw. einzurichten.

--

[#faq-eori-nummer]
[.collapseBox]
.Was ist die EORI-Nummer und wo trage ich sie ein?
--
Bei Importen aus Nicht-EU-Ländern in die EU benötigen Firmen und Selbständige für die Zollabfertigung unbedingt eine EORI-Nummer (Economic Operator's Registration and Identification number). Diese ersetzt innerhalb der EU die deutsche Zollnummer. 
In deinem plenty-System trägst du die EORI-Nummer bei Bedarf im Assistenten unter Einrichtung » Grundeinrichtung » Basics » Firmendaten in das Feld *EORI-Nummer* ein.
--

--

[#faq-versandprofil-nicht-ermittelt]
[.collapseBox]
.Das Versandprofil wird nicht ermittelt. Was kann ich tun? 
--
Damit ein Versandprofil für einen Auftrag ermittelt wird, müssen alle Einstellungen korrekt eingerichtet und das Versandprofil am Artikel aktiviert werden. Ausführliche Anleitungen zu diesem Thema findest du auf der Handbuchseite xref:versand-vorbereiten.adoc#[Versand vorbereiten].

Zunächst solltest du Folgendes kontrollieren:

. Ist das Versandprofil am Artikel aktiv?
. Ist das Lieferland / die Versandregion in der Portotabelle des Versandprofils aktiv?
. Sind Mandant und Auftragsherkunft am Versandprofil aktiv?

--

