= FAQ
:keywords: Häufig gestellte Fragen
:description: Hier findest du Fragen und Antworten aus dem Themengebiet Fulfillment
:author: team-fulfillment-payment

Auf dieser Handbuchseite findest du Fragen und Antworten aus dem Themengebiet Fulfillment. Wir werden diese Liste kontinuierlich um weitere Fragen und Antworten ergänzen.

[#faq-bereich-allgemein]
== Allgemein

[#faq-versandeinstellungen-nicht-geladen-versanddienstleister-nicht-angezeigt]
[.collapseBox]
.Die Versandeinstellungen im Assistenten werden nicht geladen, oder der Versanddienstleister wird nicht angezeigt. Was kann ich tun?
--
Grundsätzlich müssen alle Versanddienstleister-Plugins ständig aktualisiert werden.
Wenn ein neues Plugin installiert und aktiviert wird, müssen alle Anleitungsschritte befolgt werden.

Wenn du einen dieser Fehler feststellst, kannst du weiter unten nachlesen, was du tun kannst, um das Problem zu beheben:

* Die Assistenten werden nicht angezeigt.
* Der Versanddienstleister im Versand-Center ist nicht erreichbar.
* Die Fehlermeldung *Unauthorised* erscheint.

Kontrolliere zunächst Folgendes:

. Ist das Plugin auf dem aktuellen Stand und aktiv?
. Ist das Backend-Plugin-Set korrekt ausgewählt worden?
. Wurde das Plugin-Set erfolgreich bereitgestellt? (Speichere die Einstellungen im Set erneut.)
. Sind die Plugin-Prioritäten korrekt eingestellt worden (plentyShop LTS, IO)?
. Kontrolliere alle Einstellungen, die in der Beschreibung des Plugins genannt werden.
. Wenn alles gut aussieht, das Problem aber weiterhin besteht, repariere das Plugin oder installiere es ganz neu und speichere die Einstellungen im Set erneut.
. Leere den Cache und versuche danach noch einmal, die Einstellungen aufzurufen bzw. einzurichten.

--

[#faq-eori-nummer]
[.collapseBox]
.Was ist die EORI-Nummer und wo trage ich sie ein?
--
Bei Importen aus Nicht-EU-Ländern in die EU benötigen Firmen und Selbständige für die Zollabfertigung unbedingt eine EORI-Nummer (Economic Operator's Registration and Identification number). Diese ersetzt innerhalb der EU die deutsche Zollnummer. 
In deinem plenty-System trägst du die EORI-Nummer bei Bedarf im Assistenten unter *Einrichtung » Grundeinrichtung » Basics » Firmendaten* in das Feld *EORI-Nummer* ein.
--

[#faq-versandprofil-nicht-ermittelt]
[.collapseBox]
.Das Versandprofil wird nicht ermittelt. Was kann ich tun? 
--
Damit ein Versandprofil für einen Auftrag ermittelt wird, müssen alle Einstellungen korrekt eingerichtet und das Versandprofil am Artikel aktiviert werden. Ausführliche Anleitungen zu diesem Thema findest du auf der Handbuchseite xref:versand-vorbereiten.adoc#[Versand vorbereiten].

Vergewissere dich,

* dass das Versandprofil am Artikel aktiv ist.
* dass das Lieferland / die Versandregion in der Portotabelle des Versandprofils aktiv ist.
* dass Mandant und Auftragsherkunft am Versandprofil aktiv sind.
* dass die Versandgruppe / die Kundenklassen am Versandprofil nicht gesperrt sind.
* ob ein Treueprogramm aktiv ist. Dies sorgt dafür, dass das Versandprofil nur für Auftäge mit dem jeweiligen Treueprogramm verfügbar ist.
* ob es eine Beschränkung in der Portotabelle gibt (z.B. Gewichtsbeschränkung).
* ob am Artikel eine Altersbeschränkung aktiv ist. (Am Versandprofil muss POSTIDENT aktiviert werden.)
* dass die Zahlungsarten am Versandprofil nicht gesperrt sind.
* dass die Zahlungsart für die Kundenklasse aktiv ist.
* dass das Lieferland in der Zahlungsart aktiv ist.

[IMPORTANT]
.Wichtig
====
Wenn du mehrere Versandprofile mit verschiedenen Einstellungen in der *Portotabelle* (*Berechnungstyp* und *Beschränkungstyp*) und diese mit verschiedenen *Kategorien* unter den *Base*-Einstellungen einrichtest, kann dies zu einem Fehler in der Logik führen.

Nutze bitte entweder einen *Berechnungstyp* und/oder *Beschränkungstyp* oder die *Kategorisierung* - so vermeidest du den Fehler und richtest die Einstellungen so ein, dass nur die relevanten Versandprofile für den Auftrag ermittelt werden.
====
[TIP]
.Beachte, dass...
====
...das Versandprofil am Auftrag nur geändert oder aktualisiert werden kann, wenn keine *Rechnung* vorhanden ist. Sobald eine Rechnung erstellt wird, ist die Bearbeitung nur begrenzt möglich. Um die Bearbeitung des Versandprofils in diesem Fall zu ermöglichen, muss ein Stornobeleg angelegt werden.
====

--

[#ebay-fulfillment-by-orange-connex]
[.collapseBox]
.Ich möchte eBay Fulfillment by Orange Connex verwenden,aber es sind keine Dienste verfügbar. Was kann ich tun? 
--
Wenn du die Fehlermeldung erhälst, dass keine Dienste verfügbar sind, kontrolliere die Service-Verknüpfungen im Assistenten von eBay Fulfillment by Orange Connex. Überprüfe auch, ob die Authentifizierung noch gültig ist: Sie läuft nach einem Jahr ab.
Wenn im Assistenten alles in Ordnung ist, melde den Fehler im Forum in der Kategorie Fulfillment/eBay Fulfillment by Orange Connex, so dass wir ihn an unseren Ansprechpartner bei Orange Connex weiterleiten können.
--

