= PostNL
:keywords: postNL, postnl, post.nl, post-nl, Post Niederlande
:description: Erfahre, wie du das Plugin "PostNL" in plentymarkets einrichtest.
:author: team-fulfillment-payment

[IMPORTANT]
.PostNL-Plugin herunterladen
====
Die Schnittstelle zu PostNL wird über ein Plugin integriert. Um das PostNL-Plugin nutzen zu können, lade das Plugin im link:https://marketplace.plentymarkets.com/postNL_7014[plentyMarketplace^] herunter.
====

[#bei-postnl-registrieren]
== Bei PostNL registrieren

Mit dem Plugin *PostNL* können Versender aus den Niederlanden schnell und einfach Versandlabels erstellen und die Sendungsverfolgung in plentymarkets nutzen.

Um die Schnittstelle für PostNL in deinem plentymarkets System einrichten und nutzen zu können, musst du dich bei link:https://www.postnl.be/en/log-in-business/[PostNL^] registrieren. Du erhältst von PostNL die Daten, die du für die Einstellungen in plentymarkets benötigst. Kontaktierte ggf. deinen Account Manager bei PostNL.

[#postnl-einrichten]
== PostNL in plentymarkets einrichten

[TIP]
.PostNL mit Hilfe eines Assistenten einfach einrichten
====
Die Schnittstelle zu PostNL wird über ein Plugin integriert. Um das PostNL-Plugin nutzen zu können, lade das Plugin im link:https://marketplace.plentymarkets.com/postNL_7014[plentyMarketplace^] herunter. +
Dir steht dann zum einfachen Einrichten ein PostNL-Assistent im Menü *Einrichtung » Assistenten » Plugins* im relevanten Plugin-Set zur Verfügung.

Bevor du den PostNL-Assistenten durchläufst, durchlaufe die Tour *Versandvorbereitung*. Diese Tour steht dir im Menü *Einrichtung » Geführte Einrichtung » plentyShop* zur Verfügung. Dort nimmst du die folgenden Einstellungen vor:

* der Versandeinstellung (sprich: dem Versandprofil) einen Namen geben
* vorhandene Regionen aktivieren oder eine neue Region erstellen
* die Versandkosten festlegen und den Berechnungstypen wählen
* *_Hinweis:_* Weitere Einstellungen müssen anschließend im Versandprofil im Menü *Einrichtung » Aufträge » Versand » Optionen* im Tab *Versandprofile* vorgenommen werden. Weitere Hinweise dazu findest du weiter unten auf dieser Handbuchseite.

Anschließend durchläufst du den PostNL-Assistenten.
====

[#vorbereitende-einstellungen]
== Vorbereitende Einstellungen vornehmen

Zunächst musst du einige vorbereitende Einstellungen vornehmen:

* xref:fulfillment:versand-vorbereiten.adoc#100[Lieferländer einrichten]

** Lieferländer kannst du über die Tour *Versandvorbereitung* oder im Backend einrichten.

* xref:fulfillment:versand-vorbereiten.adoc#400[Regionen erstellen]
** Regionen kannst du über die Tour *Versandvorbereitung* oder im Backend erstellen.

* den xref:fulfillment:versand-vorbereiten.adoc#800[Versanddienstleister] *PostNL* erstellen
** Versanddienstleister kannst du aktuell nur im Backend und _nicht_ über einen Assistenten erstellen.

* xref:fulfillment:versand-vorbereiten.adoc#1000[Versandprofile] und xref:fulfillment:versand-vorbereiten.adoc#1500[Portotabellen] für *PostNL* erstellen +
** Die wichtigsten Versandeinstellungen kannst du über die Tour *Versandvorbereitung* einrichten. Die restlichen Einstellungen nimmst du im Backend im Menü *Einrichtung » Aufträge » Versand » Optionen* im Tab *Versandprofile* vor. +

[#assistenten-durchlaufen]
== Assistenten durchlaufen

Sobald du das xref:plugins:hinzugefuegte-plugins-installieren.adoc#plugin-installieren[Plugin in einem Plugin-Set installiert] hast, ist der PostNL-Assistenten im Menü *Einrichtung » Assistenten » Plugins* im relevanten Plugin-Set verfügbar und du kannst mit dem Einrichten beginnen. +
Für die Versandeinstellungen steht dir die geführte Tour *Versandvorbereitung* zur Verfügung. Die Tour zeigt dir Schritt für Schritt die wichtigsten Funktionen. + 

Nimm die Einstellungen nun in der folgenden Reihenfolge vor:

1. *Versandeinstellungen*
2. *PostNL*

[#tour-versandvorbereitung]
=== Tour *Versandvorbereitung* durchlaufen

Du findest die Tour im Menü *Einrichtung » Geführte Einrichtung » plentyShop einrichten*. Klicke auf material:local_shipping[] *Versandvorbereitung*, um die Tour zu starten.
In dieser Tour nimmst du die folgenden Einstellungen vor:

* Du gibst der Versandeinstellung einen Backend-Namen und einen Frontend-Namen. Diese Namen können pro Sprache gewählt werden. +
 ** Diesen Namen verknüpfst du später im Assistenten *PostNL*.

* Du wählst das Plugin des Versanddienstleisters, für den du die Versandkosten einrichten möchtest. +
 ** Das PostNL-Plugin muss im link:https://marketplace.plentymarkets.com/postNL_7014[plentyMarketplace^] heruntergeladen worden sein, damit es dir hier angezeigt wird.

* Du wählst eine Region, gibst die Versandkosten ein und wählst den Berechnungstypen für die gewählten Länder. Außerdem kannst du festlegen, ab welchem Warenwert keine Versandkosten für deine Kund:innen berechnet werden.

[IMPORTANT]
.Weitere Einstellungen für die Versandeinstellung im Backend vornehmen
====
Wenn du die Tour *Versandvorbereitung* abgeschlossen hast, wird das Versandprofil auch im Menü *Einrichtung » Aufträge » Versand » Optionen* im Tab *Versandprofile* angezeigt. +
Die folgenden Einstellungen sind mit Abschluss der Tour bereits vorhanden:

* der Name des Versandprofils ist gespeichert
* der Versanddienstleister ist gespeichert
* die Option *Bei neuen Artikeln aktiveren* ist aktiviert
* alle Mandanten (Shops) sind aktiviert
* alle Auftragsherkünfte sind aktiviert
* die Versandkosten sind gespeichert
* die Region ist gespeichert

Wenn du weitere Einstellungen vornehmen möchtest wie z.B. das Sperren von Kundenklassen oder Zahlungsarten oder dem Aktivieren der Option zum Einwilligen der Datenübermittlung an Versanddienstleister, musst du diese im entsprechenden Versandprofil im Menü *Einrichtung » Aufträge » Versand » Optionen* im Tab *Versandprofile* vornehmen.
====


[.collapseBox]
.Welche Informationen werden mit der Tour *Versandvorbereitung* eingegeben?
--

Wenn du die geführte Tour *Versandvorbereitung* abgeschlossen hast, hast du die folgenden Informationen eingegeben oder ausgewählt:

** Backend-Name
** Region
** Versanddienstleister
** Backend-Name
** Region
** Versanddienstleister
** Frontend-Name
** ID des Versandprofils

--

[#assistent-postnl]
=== Assistent *PostNL* durchlaufen

Du findest den Assistenten *PostNL* im Menü *Einrichtung » Assistenten » Plugins* im relevanten Plugin-Set. Im Folgenden werden die einzelnen Schritte, die du in diesem Assistenten durchläufst, beschrieben.

[discrete]
==== Globale Einstellungen

In diesem Schritt legst du fest, ob du die globalen Einstellungen ändern möchtest.

Wenn die Option aktiviert (icon:toggle-on[role="green"]) ist, kannst du jederzeit Änderungen in den Schritten *Zugangsdaten*, *Absenderdaten* und *Angaben auf dem Label* vornehmen. Wenn die Option deaktiviert (icon:toggle-off[role="red"]) ist, ist nur der Schritt *Einstellungsverknüpfung* sichtbar und änderbar.

[discrete]
==== Zugangsdaten

In diesem Schritt gibst du deine Zugangsdaten in Form deines API-Schlüssels ein. Gib jedem API-Schlüssel, den du eingibst, im Feld *Name des API-Schlüssels* einen Namen deiner Wahl. Mit einem Klick auf icon:plus-square[role="green"] fügst du weitere Zugangsdaten hinzu.

[discrete]
==== Absenderdaten

In diesem Schritt gibst du deine Absenderadresse ein. Mit einem Klick auf icon:plus-square[role="green"] fügst du weitere Absenderadressen hinzu.

[discrete]
==== Angaben auf dem Label

In diesem Schritt wählst du, welche Angaben auf dem Versandlabel angezeigt werden sollen. Du kannst die folgenden Werte wählen:

* Keine Angabe
* Auftrags-ID
* Externe Auftrags-ID
* Auftrags-ID + externe Auftrags-ID

[discrete]
==== Einstellungsverknüpfung

In diesem Schritt verknüpfst du die Einstellungen, die du zuvor im Assistenten *Versandeinstellungen* und in den einzelnen Schritten des *PostNL*-Assistenten vorgenommen hast. Du verknüpfst deine Versandeinstellung mit deinen Zugangsdaten, den Produkten, Services und Produkt-Codes, der Absenderadresse und der Artikelbeschreibung.

Wenn du ein <<#produkte-services-produkt-codes, Produkt>> wählst, werden in einer Liste darunter die <<#table-products-services-product-codes, zugehörigen Services und Produkt-Codes>> geladen, die du dann wählen kannst. Beachte, dass dich dein Account Manager bei PostNL für bestimmte Produkte und Services zunächst freischalten muss.

Die Artikelbeschreibung bezieht sich auf die Werte, die du im Menü *Artikel » Artikel bearbeiten* » _Artikel öffnen_ im Tab *Texte* in den Feldern *Name 1*, *Name 2*, *Name 3* und *Vorschautext* gespeichert hast. Du kannst in diesem Schritt eines dieser vier Felder wählen.

Außerdem wählst du in diesem Schritt, ob du den Produktivmodus oder den Testmodus aktivieren möchtest.

Wenn du international versendest (icon:toggle-on[role="green"]), musst du zusätzlich noch den Zollerklärungstyp und die Standardzollnummer eingeben.

[discrete]
==== Zusammenfassung

In diesem Schritt wird eine Zusammenfassung aller getätigten Eingaben in den einzelnen Schritten aufgelistet. Du kannst deine Angaben prüfen, in den einzelnen Schritten ggf. Anpassungen vornehmen und den Assistenten danach über die Zusammenfassung abschließen.

[.collapseBox]
.Welche Informationen werden bei dem abgeschlossenen Assistenten *PostNL* angezeigt?
--

Wenn du den Assistenten *PostNL* abgeschlossen hast und diesen erneut öffnest, werden die folgenden Informationen angezeigt:

* In der Kachelansicht:

** Versandeinstellung
** Region
** Name des API-Schlüssels
** Service

* In der Tabellenübersicht:

** Versandeinstellung
** Region
** Name des API-Schlüssels
** Service

--

[#produkte-services-produkt-codes]
== Aktuell verfügbare Produkte, Services und Produkt-Codes

<<#table-products-services-product-codes>> listet alle Produkte, Services und Produkt-Codes auf, die aktuell über das Plugin *PostNL* zur Verfügung stehen. Beachte, dass dich dein Account Manager bei PostNL für bestimmte Produkte und Services zunächst freischalten muss.

[[table-products-services-product-codes]]
.Aktuell verfügbare Produkte, Services und Produkt-Codes
[cols="1,3,3"]
|====
|Produkt |Service |Produkt-Code

|Inländische Produkte (Zielort Niederlande)
|Inländische Produkte
a|
* 3085 - Standardlieferung +
* 3385 - Lieferung an die angegebene Adresse +
* 3090 - Lieferung an den Nachbarn + Retoure bei Nichtantreffen der Person +
* 3390 - Lieferung an die angegebene Adresse + Retoure bei Nichtantreffen der Person

//* Abholstellen +

|
|Standardabholstellen  +
Dies sind z.B. ausgewählte Supermärkte und Buchhandlungen.
a|
* 3533 - Abholung in PostNL-Abholstelle + Unterschrift bei Lieferung +
* 3534 - Abholung in PostNL-Abholstelle + zusätzliche Versicherungssumme +
* 3543 - Abholung in PostNL-Abholstelle + Unterschrift bei Lieferung + Benachrichtigung +
* 3544 - Abholung in PostNL-Abholstelle + zusätzliche Versicherungssumme + Benachrichtigung

|
|Briefkastensendung +
Für kleine Sendungen, die in die Briefkästen deiner Endkund:innen passen.
a|
* 2928 - Brievenbuspakje

|
|Smarte Retouren +
Deine Kund:innen können über einen Barcode auf dem Smartphone das Retourenlabel in einer PostNL-Filiale drucken lassen.
a|
* 2285 - Business reply number (Antwoordnummer)

|Zielort EU
|Pakete EU +
Aktuell ist der Versand aus den Niederlanden in 27 Länder möglich. Kontaktiere ggf. deinen Account Manager bei PostNL für weitere Informationen.
a|
* 4590 - Pakete EU B2B (Lieferung an Nachbarn + Unterschrift bei Lieferung + Standardversicherungssumme) +
* 4952 - Pakete EU B2C (Lieferung an Nachbarn + Unterschrift bei Lieferung + Standardversicherungssumme)


|Zielort Rest der Welt
|GlobalPack-Produkte
a|
* 4947 - GlobalPack

|Internationale Brief- und Paketsendungen
|Internationale Brief- und Paketsendungen
 a|
* 6405 - Prio-Paket +
* 6350 - Prio-Paket, mit Nachverfolgung +
* 6906 - Prio-Paket Extra +
* 6408 - Briefsendung, mit Registrierung +
* 6040 - Buchsendung, mit Registrierung



|====

[#auftrag-anmelden]
== Auftrag anmelden

Im Menü *Aufträge » Versand-Center* meldest du deine Aufträge bei PostNL an und überträgst gleichzeitig die Auftragsdaten an PostNL. Gehe wie im Folgenden beschrieben vor.

[.instruction]
Auftrag anmelden:

. Öffne das Menü *Aufträge » Versand-Center*.
. Suche die Aufträge anhand der Filtereinstellungen wie auf der Handbuchseite xref:fulfillment:versand-center-2-0.adoc#auftrag-suchen[Versand-Center] beschrieben. +
→ Die Aufträge, die den eingestellten Suchkriterien entsprechen, werden in der Übersicht angezeigt.
. Wähle (material:check_box[role=skyBlue]) die Aufträge, die du anmelden möchtest.
. Klicke in der Symbolleiste ganz oben auf *Aufträge anmelden* (terra:outgoing_items[]). +
→ Das Fenster *Aufträge anmelden* öffnet sich.
. Wähle *PostNL* aus der Dropdown-Liste.
. Wähle den Auftragsstatus, in dem sich die Aufträge nach erfolgreicher Anmeldung bei PostNL befinden sollen, aus der Dropdown-Liste. +
*_Hinweis:_* Du kannst den Wechsel in diesen Auftragsstatus dann mit einer xref:automatisierung:ereignisaktionen.adoc[Ereignisaktion], die z.B. automatisch den Warenausgang bucht, verknüpfen.
. Wähle den Auftragsstatus, in dem sich die Aufträge nach fehlgeschlagener Anmeldung bei PostNL befinden sollen, aus der Dropdown-Liste. +
*_Hinweis:_* Du kannst den Wechsel in diesen Auftragsstatus dann mit einer xref:automatisierung:ereignisaktionen.adoc[Ereignisaktion] verknüpfen.
. Wenn du _nicht_ möchtest, dass die Versandlabels nach der Anmeldung automatisch heruntergeladen werden, deaktiviere (material:check_box_outline_blank[]) die Option *Versandlabels im PDF-Format nach der Anmeldung automatisch herunterladen*. +
*_Hinweis:_* Diese Option ist standardmäßig aktiviert.
. Klicke auf *Aufträge anmelden*. +
→ Die Aufträge werden bei PostNL angemeldet.

Weitere Informationen zum Anmelden von Aufträgen findest du auf der Handbuchseite xref:fulfillment:versand-center-2-0.adoc#[Versand-Center].