= Zalando Fulfillment Solutions
:keywords: ZFS, Zalando Fulfillment Solutions
:description: Erfahre mehr über ZFS.
:author: team-fulfillment-payment

Auf dieser Seite findest du einen Überblick über Zalando Fulfillment Solutions sowie die wichtigsten Links, die du im Zusammenhang mit der Einrichtung von ZFS benötigst.

== Was bedeutet ZFS?

ZFS steht für Zalando Fulfillment Solutions und bietet Händlern die Möglichkeit, für Artikel, die über Zalando verkauft werden, das Logistiknetzwerk von Zalando zu nutzen: Du sendest deine Artikel an Zalando und Zalando übernimmt deren Lagerung und den Versand an deine Kund:innnen.

== Wie kann ich ZFS nutzen?

Die Voraussetzung um ZFS nutzen zu können, ist zunächst, dass du mit Zalando einen Vertrag für Zalando Fulfillment Solutions abgeschlossen hast. Nimm dann im Zalando-Assistent die entsprechenden Einstellungen vor:

1. Öffne das Menü *Einrichtung » Assistenten » Omni-Channel*.

2. Klicke auf den Assistenten *Kontoeinstellungen - Zalando*.

3. Folge den Anweisungen auf dem Bildschirm. 

4. Prüfe im Schritt *Zusammenfassung* deine Einstellungen noch einmal auf mögliche Fehler. +
_Wichtig:_ Du hast die Einrichtung noch nicht abgeschlossen. Aktiviere im Schritt *Konto-Aktivierung* das Zalando-Konto deshalb noch nicht.

5. Wenn alles passt, klicke auf *Abschließen*.
→ Die Einstellungen werden gespeichert. +
_Tipp:_ Du kannst den Assistenten jederzeit noch einmal durchlaufen, um Einstellungen anzupassen.

6. Aktiviere den Toogle-Button, um Zalando Fulfillment Solutions zu nutzen.

7. Ordne nun den Zalando-Standorten (Ländern) Lager aus plentymarkets zu. + 
In jedem Land, das zur Auswahl steht, gibt es ein Zalando Fulfillment-Lager, in dem deine Artikel gelagert werden können. Diesen Zalando-Lagern ordnest du ein Lager in plentymarkets zu. So hast du eine Übersicht darüber, an welchen Zalando-Standorten deine Artikel gerade gelagert werden. Die Bestände aus den Zalando-Standorten werden an deine plentymarkets Lager übertragen.

Weitere Informationen findest du xref:maerkte:zalando.adoc[hier].

