= Zalando Fulfillment Solutions
:keywords: ZFS, Zalando Fulfillment Solutions
:description: Erfahre mehr über ZFS.
:author: team-fulfillment-payment

Auf dieser Seite findest du einen Überblick über Zalando Fulfillment Solutions sowie die wichtigsten Links, die du im Zusammenhang mit der Einrichtung von ZFS benötigst.

== Was bedeutet ZFS?

ZFS steht für Zalando Fulfillment Solutions und bietet Händlern die Möglichkeit, für Artikel, die über Zalando verkauft werden, das Logistiknetzwerk von Zalando zu nutzen: Du sendest deine Artikel an Zalando und Zalando übernimmt deren Lagerung und den Versand an deine Kund:innnen.

== Wie kann ich ZFS nutzen?

Die Voraussetzung um ZFS nutzen zu können, ist zunächst, dass du mit Zalando einen Vertrag für Zalando Fulfillment Solutions abgeschlossen und Zalando in plentymarkets eingerichtet hast. +

Weitere Informationen zu Zalando und ZFS findest du xref:maerkte:zalando.adoc[hier].

1. Aktiviere den Toogle-Button, um Zalando Fulfillment Solutions zu nutzen. +
2. Ordne nun den Zalando-Standorten (Ländern) Lager aus plentymarkets zu. +
In jedem Land, das zur Auswahl steht, gibt es ein Zalando Fulfillment-Lager, in dem deine Artikel gelagert werden können. Diesen Zalando-Lagern ordnest du ein Lager in plentymarkets zu. So hast du eine Übersicht darüber, an welchen Zalando-Standorten deine Artikel gerade gelagert werden. Die Bestände aus den Zalando-Standorten werden an deine plentymarkets Lager übertragen.

[IMPORTANT]
Um Zalando ZFS-Bestände in plentymarkets abzubilden, benötigst du ein oder mehrere Reparaturlager.

[TIP]
Erstelle eigene Lager für Zalando Fulfillment Solutions.
Du kannst entweder ein Standardlager oder ein Standardlager und weitere Lager pro Zalando-Kanal festlegen.

*Möglichkeit 1:* _Nur ein Standardlager festlegen_ +

1. Wähle für die Einstellung *Standard-Lager für Zalando ZFS wählen* ein plentymarkets Reparaturlager aus der Dropdown-Liste. +
→ Bestandsdaten für alle Zalando-ZFS-Lager werden in dieses Reparaturlager importiert.

[IMPORTANT] 
Wenn du keine weiteren Lager zuordnest, werden die Bestandsdaten aus allen Zalando-Standorten gesammelt in dieses plentymarkets Lager importiert.

*Möglichkeit 2:* _Ein Standardlager und weitere Lager pro Zalando-Kanal festlegen_ +

1. Wähle für die Einstellung *Standard-Lager für Zalando ZFS wählen* ein plentymarkets Reparaturlager. +
2. Klicke unten rechts auf (material:add[]), um eine weitere Zuordnung hinzuzufügen. +
3. Wähle aus der Dropdown-Liste *Zalando-Standort* ein Land. +
4. Wähle aus der Dropdown-Liste *plentymarkets Lager* ein Reparaturlager. +
→ Bestandsdaten aus diesem Land werden in das gewählte Lager importiert.
[TIP]
Du kannst jeden Zalando-Standort nur _einem_ plentymarkets Lager zuordnen.
5. Klicke wenn nötig unten rechts auf (material:add[]), um eine weitere Zuordnung hinzuzufügen.
→ In das Standard-Lager werden Bestandsdaten von Zalando-Standorten importiert, die keinem plentymarkets Lager zugeornet wurden. +
_Beispiel:_ Erstelle ein Lager *Zalando Deutschland*. Ordne diesem Lager den Zalando-Standort *Deutschland* zu. So kannst du jederzeit sehen, welche Bestände Zalando für dich in Deutschland lagert.





