= Zalando Fulfillment Solutions
:keywords: ZFS, Zalando Fulfillment Solutions
:description: Erfahre mehr über ZFS.
:author: team-fulfillment-payment

Auf dieser Seite findest du einen Überblick über Zalando Fulfillment Solutions sowie die wichtigsten Links, die du im Zusammenhang mit der Einrichtung von ZFS benötigst.

== Was bedeutet ZFS?

ZFS steht für Zalando Fulfillment Solutions und bietet Händlern die Möglichkeit, für Artikel, die über Zalando verkauft werden, das Logistiknetzwerk von Zalando zu nutzen: Du sendest deine Artikel an Zalando und Zalando übernimmt deren Lagerung und den Versand an deine Kund:innnen.

== Wie kann ich ZFS nutzen?

Die Voraussetzung um ZFS nutzen zu können, ist zunächst, dass du mit Zalando einen Vertrag für Zalando Fulfillment Solutions abgeschlossen hast. +

Weitere Informationen zu Zalando und ZFS findest du xref:maerkte:zalando.adoc[hier].

Aktiviere den Toogle-Button, um Zalando Fulfillment Solutions zu nutzen.

Ordne nun den Zalando-Standorten (Ländern) Lager aus plentymarkets zu. + 
In jedem Land, das zur Auswahl steht, gibt es ein Zalando Fulfillment-Lager, in dem deine Artikel gelagert werden können. Diesen Zalando-Lagern ordnest du ein Lager in plentymarkets zu. So hast du eine Übersicht darüber, an welchen Zalando-Standorten deine Artikel gerade gelagert werden. Die Bestände aus den Zalando-Standorten werden an deine plentymarkets Lager übertragen.




