= Connecting Shopify
:keywords: Shopify, plentymarkets app, shopify assistant, shopify shops, connect shopify, link shopify
:description: Learn how to connect your plentymarkets account with Shopify in order to synchronise your data.
:author: team-plenty-channel

On this page, you will learn how to connect your plentymarkets account with Shopify so you can synchronise your data between both systems. The two Shopify assistants will guide you through all required steps so you can start right away.

[IMPORTANT]
.The Shopify app is only available for new plentymarkets systems
====
Due to technical reasons, the new Shopify app will only be available for new plentymarkets systems for the time being. Existing integrations will continue to use the Shopify plugin. The possibility to migrate from the plugin to the new app is currently being developed.
====

[#about]
== About Shopify

Just like plentymarkets, Shopify is a complete e-commerce platform that lets you start, grow, and manage your online business. As Shopify is entirely cloud-based and hosted, there is no need to worry about upgrading or maintaining the software or any web servers.

[#registration]
== Registering with Shopify

To register with Shopify, follow the app installation steps below.

[.instruction]
Registering with Shopify:

. Go to link:https://www.shopify.com/signup[Shopify^].
. Go to *Admin » Apps*.
. Click on *Customize your store*.
. Search for the *plentymarkets* app. +
→ The plentymarkets app is shown.
. Click on *Add app*. +
→ The confirmation view opens.
. Click on *Install app*. +
→ The app is installed and the plentymarkets registration view opens.
. Enter your PID, user and password. +
*_Tip:_* If you don't have these credentials yet, you can register for a system.
. Click on *Login*. +
→ The plentymarkets app opens.
. Connect a plentymarkets client. +
*_Tip:_* The toggle on the right tells you whether a client is connected. +
→ You can now carry out the import and export settings as desired.

[#integration]
== Setting up Shopify

The following chapters describe how to set up the interface to Shopify in plentymarkets.

[#2885714092]
=== Video tutorial: Installation and configuration

video::4D_3vFrVBIQ[youtube]

[#shopify-configuration-assistant]
=== Using the Shopify Configuration assistant

The *Shopify Configuration* assistant will guide you through the required steps to set up your Shopify connection. <<table-shopify-configuration-assistant>> shows which settings you can carry out in the individual steps of the assistant. You can find the Shopify configuration assistant in the *Setup » Assistants* menu in the *Omni-Channel* area.

[.instruction]
Using the *Shopify Configuration* assistant:

. Go to *Setup » Assistants » Omni-Channel*.
. Click on the *Shopify Configuration* assistant.
. Click on the available configuration. +
→ The assistant opens.
. Follow the instructions on the screen. If you need additional information about one of the options, expand the info box below this description (icon:chevron-down[role="darkGrey"]).
. If everything is as it should be, click on icon:check[role="green"] *Finalise*. +
→ The assistant is completed. The connection to Shopify has been set up.

[.collapseBox]
.Options in the assistant
--

[width="100%"]
[cols="1,2a"]
|======
|Setting |Explanation

2+^| Step *Shopify Connection*

| Shopify connection
| Shows the Shopify hostname, the connected plentymarkets client and the connection status. No action is required in this step.

2+^| Step *Item management*

a| Item management
| Decide whether you want to import or export items and how this should be handled. +
*_Note:_* Import and export processes for items cannot be both active at the same time.

2+^| Step *Stock management*

| Stock management
| Configure how the import and export of stock should be handled. Item prices are included here, too. +
*_Note:_* Import and export processes for stock cannot be both active at the same time.

2+^| Step *Warehouse to location mapping*

| Warehouse mappings
| Link your plentymarkets warehouses to Shopify locations. You can link multiple plentymarkets warehouses to one and the same Shopify location. The selection in this step will affect stock imports and exports as well as order fulfilment notifications to Shopify. +
*_Note:_* Only stock from mapped warehouses and locations will be exported and imported.

2+^| Step *Order management*

| Order management
| Configure how the import of order details from Shopify should be handled. Furthermore, determine how you want to manage refunds and cancellation requests.

2+^| Step *Contact management*

| Contact management
| Configure how the import of contact details from Shopify should be handled.

2+^| Step *Shipping profiles mapping*

| Shipping profiles mapping
| Link Shopify and plentymarkets shipping profiles. By doing so, shipping profiles for imported orders will automatically be determined for imported orders. For each existing Shopify profile you can choose a corresponding profile from plentymarkets.
|======
--

[#shopify-assistant-input-fields]
=== Using the Input field mapping assistant

The *Input field mappings* assistant helps you to create custom mappings between Shopify input fields and plentymarkets data fields. These mappings are used for the item export.

[.instruction]
Using the input field mapping assistant:

. Go to *Setup » Assistants » Omni-Channel*.
. Click on the *Input field mappings* assistant.
. Click on the available configuration. +
→ The assistant opens.
. Follow the instructions on the screen. If you need additional information about one of the options, expand the info box below this description (icon:chevron-down[role="darkGrey"]).
. If everything is as it should be, click on icon:check[role="green"] *Finalise*. +
→ The assistant is completed. The input field mappings have been created.

[.collapseBox]
.Options in the assistant
--

[width="100%"]
[cols="1,2a"]
|======
|Setting |Explanation

2+^| Step *Shopify account*

| *Shopify account*
| Shows for which Shopify account you are carrying out the settings. No action is required in this step.

2+^| Step *Existing input field mappings*

| *Existing input field mappings*
| Shows the current input field mappings. In case some of them are no longer needed, you can select them here for deletion. Once the assistant has been completed, the selected mappings will be deleted.

2+^| Step *Creating a new field mapping*

| *Creating a new field mapping*
| Select the Shopify field that contains the exported data. If you do not want to create a new mapping at this point, leave this field empty.

*_Note:_* You can only create one input field mapping each time you go through the assistant. Therefore, you have to go through the assistant again each time you want to create a new mapping. Choosing a meta field will trigger a new assistant step.


2+| Step *Metafield configuration* (optional)

| *Metafield configuration*
| This step is only available if you choose the option *Metafield* in the *Create new field mapping* step. Specify the namespace and the name of the Shopify Metafield. +

*_Note:_* Shopify Metafields are not visible in the Shopify back end without a specific Shopify app. For more details regarding Shopify Metafields, consult the link:https://help.shopify.com/en/manual/metafields[Shopify Help Center^] and enter the keyword *Metafield*.

2+| Step *plentymarkets source input field*

| *plentymarkets source input field*
| Select the plentymarkets source field that will be used to export the customised data. +
*_Note:_* Source input field mappings are only available for *Item export* processes.

2+| Step *Property* (optional)

| *Property*
| This step is only available if you chose the option *Property* in the *plentymarkets source input field* step. Select the property you want to use as export data source.
|======
--

[#further-shops]
== _Optional:_ Connecting additional Shopify shops

Note the following if you want to link more than one Shopify shop with plentymarkets:

* Each new connection requires a separate plentymarkets client and a separate Shopify account.
* To create an additional connection you need to install the plentymarkets app in each Shopify shop you wish to connect.

[#stock-limitation]
== Logic for limiting stock

In the Shopify back end, the option *Continue selling when out of stock* determines if products are sold if no or not enough stock is in the warehouse. When stock is exported, this option is either activated or not. This depends on the plentymarkets setting xref:item:directory.adoc#220[Stock limitation].

Depending on which *Limitation* you selected for a variation in plentymarkets, the checkbox *Continue selling when out of stock* is either activated or not:

[cols="2,3"]
|====
| Option *"Limitation"* in plentymarkets | Option *Continue selling when out of stock* in Shopify

| *None*
| Activated

| *To net stock*
| Not activated

| *Do not administer stock for this variation*
| Activated
|====

[#custom-order-properties]
== Importing custom order properties

The Shopify integration also enables you to import custom order properties using the order import process. 

For example, you can create custom order properties with the Shopify plugin link:https://apps.shopify.com/product-personalizer[Product Personalizer^]. This plugin gives your customers the option to enter custom text during the order process. This allows you to offer personalized products, for example with engravings.

Requirements for importing custom order properties:

* In the menu *Setup » Item » Characteristics*, create a characteristic for which you activate the option *Order characteristic* on the right.
* If you want to import such properties, make sure that the plentymarkets item has a characteristic where the option *Order characteristic* is activated.

[#event-procedures]
== Setting up event procedures

Use xref:automation:event-procedures.adoc#[plentymarkets event procedures] to automate order communication with Shopify.

[#event-procedures]
=== Available event procedures

The following event procedures are available for the Shopify app:

*_Tip:_* Event procedures are set up in the menu *Setup » Orders » Events*. In the list *Add procedure*, the procedures for the Shopify apps are listed in the folder *Plugins*.

* Shopify App: Save plentymarkets order Id in Shopify
* Shopify App: Archive Shopify order
* Shopify App: Send manually added payment to Shopify
* Shopify App: Send fulfilment notification to Shopify
* Shopify App: Send returns to Shopify
* Shopify App: Send cancel notification to Shopify
* Shopify App: Send credit note to Shopify
* Shopify App: Send cancellation/refund to Shopify
* Shopify App: Send refund/cancellation to Shopify without stock adjustment

[#gdpr]
== Contact import and GDPR

Due to GDPR specifications, the following policies for customer accounts and orders have been implemented:

[[table-gdpr]]
.GDPR considerations during the contact import
[cols="1,2"]
|===
|*Scenario* |*Explanation*

| Customer is imported as regular contact
| If the authenticity of the Shopify customer is guaranteed by a unique external contact ID, a regular account is created.

| An existing plentymarkets contact is linked to the imported order
| It is checked whether a customer from Shopify with this external contact ID has been imported in the past. If a contact is found, the new order is assigned to this contact.

| Customer is imported as guest
| If the customer does not have a plentymarkets account and Shopify also cannot guarantee the authenticity of the customer, the contact is imported as a guest. That also applies if the contact data of several orders are identical.

*Tip:* You can convert contacts of the type *Guest* to xref:quick-search.adoc#convert-guest-account[regular contacts].
|===

[#plugin-help]
== Using help functions

The menu *Setup » Markets » Shopify app* offers the following functionality:

* <<#3873695972, Check the connection to Shopify.>>
* <<#6535986175, Check the export conditions of a variation.>>
* <<#8878636701, Manually export an item every 10 minutes.>>
* <<#4973807959, Export the stock of a variation or an item every 5 minutes.>>
* <<#0389029301, Find a plentymarkets order ID by entering the Shopify order number.>>
* <<#7088931107, Plan an item cleanup.>>

[#3873695972]
=== Checking the connection to Shopify

[.instruction]
Checking the connection to Shopify:

. Go to *Setup » Markets » Shopify app » Health check*.
. Click on *Check*. +
→ The system checks if a connection to Shopify.com can be established. +
→ The system checks if Shopify Direct Checkout is installed.
*_Tip:_* Conditions that are fulfilled are marked with a green *OK*. Conditions that have failed are marked in red and with an *X*.

*_No connection to Shopify? Then check the following conditions:_*

* In the menu *Setup » Orders » Order referrer*, Is the order referrer *Shopify* active?
* Is there more than one *Shopify* referrer entry in the menu *Setup » Orders » Referrer*? Make sure that the ID with the highest number is active.

[#6535986175]
=== Checking export conditions for variations

Check if a variation meets all requirements to be exported to Shopify.

[.instruction]
Checking export conditions for variations:

. Select the online shop that you want to check the variation for.
. Go to *Setup » Markets » Shopify app » Export conditions*.
. Enter a valid variation ID.
. Click on *Check*. +
→ The variation is checked.
*_Tip:_* Conditions that are fulfilled are marked with a green *OK*. Conditions that have failed are marked in red and with an *X*. +
*_Important:_* Variations must meet all requirements to be exported.

*_The following conditions are checked:_*

* Is the variation active? +
→ In the menu *Item » Variation » Settings*, area *Availability*, the checkbox *Active* must be set.
* Is the variation available for Shopify? +
→ *Item » Variation » Availability » Area: Markets » Option Shopify* must be selected.
* Does the *Variation » Client* assignment match your *online shop* selection? +
→ *Item » Variation » Availability » Area: Client » [Selected client*.
* Is an *item text* saved for the item? +
→ *Item » Texts » Item text* must be entered.
* Is a *Name 1* saved for the item? +
→ *Item » Texts » Name 1* must be saved.
* Does the variation have an SKU for Shopify? +
→ *Item » Variation » Availability » Area: SKU* section must contain an *SKU* for the referrer *Shopify*.
* Does the variation have a sales price with default currency that is activated for Shopify?
* Is a variation attribute name saved for the selected item export language?
* Is a variation attribute value saved for the selected item export language?
* Is an item title and description saved in the selected item export language?
* Does the item have no more than 100 variations? +
→ Exported items must not contain more than 100 variations. This limit is set by Shopify.

[#8878636701]
=== Manually exporting items

For testing purposes, you can manually export an item every 10 minutes.

[.instruction]
Manually exporting an item:

. Go to *Setup » Markets » Shopify app Item export*.
. Select an online shop.
. Enter a valid item ID.
. Click on *Execute*. +
→ If all export requirements are met, the item and the corresponding variations will be exported.

*_Note:_* If you have deleted one or more items on Shopify to re-export them, the first export only cleans up the database. Only the second export saved the item in Shopify again.

[#2729787975]
=== Manually exporting stock

For testing purposes, you can manually export an item’s stock every 5 minutes. For variations, you can start an export every 3 minutes.

[tabs]
====
Manually exporting stock for an item::
+
--

[.instruction]
Exporting stock for an item:

. Go to *Setup » Markets » Shopify app » Stock export*.
. Select an online shop.
. From the drop-down list *xxx*, select the option *Export stock for item*.
. Enter a valid *item ID*.
. Click on *Execute*. +
→ If all export requirements are met, the stock of the item will be exported. +
*_Note:_* You need to wait 5 minutes before exporting another item.
--
 
Manually exporting stock for a variation::
+
--
[.instruction]
Exporting stock for a variation:

. Go to *Setup » Markets » Shopify app » Stock export*.
. Select an online shop.
. From the drop-down list *xxx*, select the option *Export stock for variation*.
. Enter a valid *variation ID*.
. Click on *Execute*. +
→ If all export requirements are met, the stock of the variation will be exported. +
*_Note:_* You need to wait 3 minutes before exporting another variation.
--
====

[#8869548744]
=== Setting a custom start date for stock exports

If you want to export stock quantities for items with an older *last change* date.

[.instruction]
Setting a start date:

. Go to *Setup » Markets » Shopify app » Stock export*.
. Select an online shop.
. From the drop-down list *xxx*, select the option *Update date*.
. Select a start date from the *calendar*.
. Enter a time.
. Click on *Save*. +
→ The next stock export runs at the time you selected. +
*_Important:_* The start date shown is updated after every export.

[#0389029301]
== Finding the plentymarkets order ID by using Shopify order number

If a customer contacts you with the Shopify order ID, you can use this ID to find out the corresponding plentymarkets order ID.

[.instruction]
Finding the plentymarkets order ID:

. Go to *Setup » Markets » Shopify app » Find order ID*.
. Select the webshop.
. Enter a valid Shopify order number.
. Click on *Search*. +
→ If the Shopify order number is valid, the plentymarkets order ID will be shown.

[#7088931107]
== Planning an item cleanup

Plan an item cleanup if: 

* You have deleted or deactivated items or variations from plentymarkets and you also need to remove them from Shopify.
* You have manually deleted items or variations from Shopify and they are not re-exported by the plugin.
* You want to delete all items from Shopify and start a new item export from plentymarkets. In this case, deactivate the item export and delete all items from Shopify. Plan an item cleanup. You can reactivate the item export the next morning.

*_Note:_* Do not use the item cleanup if your items were imported from Shopify after you set up the connection. This can delete items on Shopify. The item cleanup only runs once after you planned it. If necessary, plan additional item cleanups.
 
[.instruction]
Planning an item cleanup:

. Go to *Setup » Markets » Shopify app » Item cleanup*.
. Select the *online shop* that you want to plan a cleanup for.
. Click on *Plan cleanup*. +
→ Affected items are deleted from Shopify during the next nightly export.

*_Note:_* Items and variations that were already exported will be deleted from Shopify if:

* The *client* and the availability *Shopify* were removed from the variation.
* The variation was deleted from plentymarkets.
* For items with no active variations, the complete item is deleted from Shopify.