= Connecting to Shopify app
:keywords: Shopify, plentymarkets app, shopify assistant, shopify shops, connect shopify, link shopify
:description: Learn how to connect your plentymarkets account with Shopify in order to synchronise your data.
:author: team-plenty-channel

:shopify:
:market: Shopify
:referrer-option: Shopify
:referrer: Shopify

Just like plentymarkets, Shopify is a complete e-commerce platform that lets you start, grow, and manage your online business. As Shopify is entirely cloud-based and hosted, there is no need to worry about upgrading or maintaining the software or any web servers.

include::partial$shopify-differences.adoc[]

[#registration]
== Registering with Shopify

First, register with link:https://www.shopify.com[Shopify^].

[.instruction]
Registering with Shopify:

. Open https://www.shopify.com/signup[Shopify.com].
. Follow the steps for the Shopify registration.

////
[.instruction]
Bei Shopify registrieren:

. Go to link:https://www.shopify.com/signup[Shopify^].
. Go to *Admin » Apps*.
. Click on *Customize your store*.
. Search for the *plentymarkets* app. +
→ The plentymarkets app is shown.
. Click on *Add app*. +
→ The confirmation view opens.
. Click on *Install app*. +
→ The app is installed and the plentymarkets registration view opens.
. Enter your PID, user and password. +
*_Tip:_* If you don't have these credentials yet, you can register for a system.
. Click on *Login*. +
→ The plentymarkets app opens.
. Connect a plentymarkets client. +
*_Tip:_* The toggle on the right tells you whether a client is connected. +
→ You can now carry out the import and export settings as desired.
////

[#integration]
== Setting up plentymarkets app in Shopify

First, install the plentymarkets app in your Shopify back end.

[#2885714092]
=== Video tutorial: Installation and configuration

Are you the visual type? Then check out our video tutorial first.

video::4D_3vFrVBIQ[youtube]

[#BL4N76]
=== Installing and connecting plentymarkets app in Shopify

//tag::migration-installation[]
Keep your plentymarkets credentials at hand. You need your plentyID, your user name and your password to proceed.

[.instruction]
Installing and connecting plentymarkets app in Shopify:

. Open the plentymarkets app in the link:https://apps.shopify.com/plentymarkets-1?locale=en[Shopify App Store].
. Click on *Add app*. +
. Enter your credentials for Shopify. +
→ You are directed to your Shopify back end.
. Click on *Install app*. +
*_Important:_* This grants plentymarkets rights for exchanging data with Shopify. Check the *Data protection details* shown on the screen. +
→ The app is installed.
. Enter your plentymarkets credentials: plentyID, user name and password. +
→ A list of your plentymarkets clients is shown.
//end::migration-installation[]
. Activate the plentymarkets client that you want to connect to this Shopify account. To do so, activate the toggle *Connected* on the right. +
*_Important:_* You need a separate plentymarkets client for each Shopify shop. As such, only select one client. +
→ The data exchange options can be selected.
. Set the desired options for the data exchange. Pay attention to <<#QVFOWVID>>. +
*_Important:_* Prices, stock and item data can only be sent in one direction at a time. The direction you choose depends on where your item data is stored. Are your items stored in plentymarkets or in Shopify? Check <<#QVFOWVID>> for different scenarios.
. Save the settings.

[[QVFOWVID]]
.Options for data exchange
[cols="1,3a"]
|===
|Setting |Explanation

| *from Shopify to plentymarkets*
|
[cols="1a,3a"]
!===

! *Prices and stock*
! Activate to import prices and stock to plentymarkets every 15 minutes.

! *Items*
! Activate to import item data in plentymarkets. Item data is imported once per day. Updates to item data are imported once per hour.

! *Categories*
! Activate to import categories in plentymarkets. 

! *Orders*
! Activate to import orders in plentymarkets. Orders are then imported every 15 minutes.

! *Customers*
! Activate to import customer data in plentymarkets. Customer data is then imported once per day.

! *Payments*
! Activate to import payments in plentymarkets.
!===

| *from plentymarkets to Shopify*
|
[cols="1a,3a"]
!===
! *Prices and stock*
! Activate to export prices and stock to Shopify every 15 minutes.

! *Items*
! Activate to export item data to Shopify. Item data is exported once per day. Updates to item data are exported once per hour.

! *Categories*
! Activate to export categories to Shopify.
!===

| *_Which direction is right for you?_*
|
include::page$shopify-app.adoc[tag=sync-direction]
|===

[#shopify-configuration-assistant]
== Setting up Shopify in plentymarkets

No, head over to the plentymarkets back end to continue the setup process.

[#RM4IZXPC]
=== Completing the configuration assistant

The assistant *Shopify configuration* will guide you through the required steps to set up your Shopify connection.

[.instruction]
Using the *Shopify Configuration* assistant:

. Go to *Setup » Assistants » Omni-Channel*.
. Click on the *Shopify Configuration* assistant.
. Click on the available configuration. +
→ The assistant opens.
. Follow the instructions on the screen. If you need additional information about one of the options, expand the info box below this description (icon:chevron-down[role="darkGrey"]).
. If everything is as it should be, click on icon:check[role="green"] *Finalise*. +
→ The assistant is completed. +
→ The connection to Shopify is set up.

[width="100%"]
[cols="1,3a"]
|===
|Setting |Explanation

2+^| Step *Shopify Connection*

| Shopify connection
| Shows the Shopify hostname, the connected plentymarkets client and the connection status. No action is required in this step.

2+^| Step *Item management*

a| Item management
| Decide whether you want to import or export items and how this should be handled. +
*_Note:_* Import and export processes for items cannot be both active at the same time.

*_Background:_*
//tag::sync-direction[]
Prices, stock and item data can only be sent in one direction at a time. The direction you choose depends on where your item data is stored. Are your items stored in plentymarkets or in Shopify? Below are the most common scenarios.

[.collapseBox]
.Scenario 1: You only have items in plentymarkets
--

Your item data is saved in plentymarkets. You now want to export this item data to Shopify.

You need the following settings:

[cols="1,3a"]
!===
!Where? !What?

! plentymarkets App +
in Shopify back end
! Activate the following options in the column *from plentymarkets to Shopify*:
    
* *Prices and stock*
* *Items*
* *Categories*

! plentymarkets back end
! In the assistant *Shopify configuration*, step *Item management*, activate the following option:

* *Do you want to export items to Shopify?*

*_Tip:_* Go to *Setup » Assistants » Omni-Channel* to open the assistant.
!===

--

[.collapseBox]
.Scenario 1: You only have items in Shopify
--

Your item data is saved in Shopify. You now want to import this item data to plentymarkets.

You need the following settings:

*_Important:_* You need to activate the client and the referrer Shopify for your variations before they are exported to Shopify. Find out how in the chapter <<#XV8ANTMR, Preparing variations>>. 

[cols="1,3a"]
!===
!Where? !What? 

! plentymarkets App +
in Shopify back end
! Activate the following options in the column *from Shopify to plentymarkets*:
    
* *Prices and stock*
* *Items*
* *Categories*

! plentymarkets back end
! In the assistant *Shopify configuration*, step *Item management*, activate the following option:

* *Do you want to import items from Shopify?*

*_Tip:_* Go to *Setup » Assistants » Omni-Channel* to open the assistant.
!===
--

[.collapseBox]
.Scenario 3: You have items in Shopify and in plentymarkets
--

Your item data is saved in plentymarkets and in Shopify. You want to synchronise these two sets of item data and manage them in plentymarkets from now on. +

In this case, two steps are necessary:

*1*. Import your Shopify items to plentymarkets. Select the following settings:

[cols="1,3a"]
!===
!Where? !What? 

! plentymarkets App +
in Shopify back end
! Activate the following options in the column *from Shopify to plentymarkets*:
    
* *Prices and stock*
* *Items*
* *Categories*

! plentymarkets back end
! In the assistant *Shopify configuration*, step *Item management*, activate the following option:

* *Do you want to import items from Shopify?*

*_Tip:_* Go to *Setup » Assistants » Omni-Channel* to open the assistant.
!===

*2*. After the import, you change the settings so that your items are exported from plentymarkets to Shopify. Select the following settings:

*_Important:_* You need to activate the client and the referrer Shopify for your variations before they are exported to Shopify. Find out how in the chapter <<#XV8ANTMR, Preparing variations>>.

[cols="1,3a"]
!===
!Where? !What?

! plentymarkets App +
in Shopify back end
! _After the item import from Shopify_, activate the following options in the column *from plentymarkets to Shopify*:
    
* *Prices and stock*
* *Items*
* *Categories*

*_Tip:_* To activate the new options, you first need to deactivate the same options in the column *from Shopify to plentymarkets*.

! plentymarkets back end
! _After the item import from Shopify_, activate the following option in the assistant *Shopify configuration*, step *Item management*:

* *Do you want to export items to Shopify?*

*_Tip:_* To activate the new option, you first need to deactivate the option *Do you want to import items from Shopify?*.
!===
//end::sync-direction[]
--

2+^| Step *Stock management*

| Stock management
| Configure how the import and export of stock should be handled. Item prices are included here, too. +
*_Note:_* Import and export processes for stock cannot be both active at the same time.

2+^| Step *Warehouse to location mapping*

| Warehouse mappings
| Link your plentymarkets sales warehouses to Shopify locations. You can link multiple plentymarkets sales warehouses to one and the same Shopify location. The selection in this step will affect stock imports and exports as well as order fulfilment notifications to Shopify. +
*_Note:_* Only stock from mapped sales warehouses and locations will be exported and imported.

2+^| Step *Order management*

| Order management
| Configure how the import of order details from Shopify should be handled. Furthermore, determine how you want to manage refunds and cancellation requests.

2+^| Step *Contact management*

| Contact management
| Configure how the import of contact details from Shopify should be handled.

2+^| Step *Shipping profiles mapping*

| Shipping profiles mapping
| Link Shopify and plentymarkets shipping profiles. By doing so, shipping profiles for imported orders will automatically be determined for imported orders. For each existing Shopify profile you can choose a corresponding profile from plentymarkets.
|===

[#shopify-assistant-input-fields]
=== Using the Input field mapping assistant

The *Input field mappings* assistant helps you to create custom mappings between Shopify input fields and plentymarkets data fields. These mappings are used for the item export.

*_Note:_* You can only create one input field mapping each time you go through the assistant. Therefore, you have to go through the assistant again each time you want to create a new mapping.

[.instruction]
Using the input field mapping assistant:

. Go to *Setup » Assistants » Omni-Channel*.
. Click on the *Input field mappings* assistant.
. Click on the available configuration. +
→ The assistant opens.
. Follow the instructions on the screen. If you need additional information about one of the options, expand the info box below this description (icon:chevron-down[role="darkGrey"]).
. If everything is as it should be, click on icon:check[role="green"] *Finalise*. +
→ The assistant is completed. +
→ The input field mappings are created.

[.collapseBox]
.Options in the assistant
--

[width="100%"]
[cols="1,2a"]
|===
|Setting |Explanation

2+^| Step *Shopify account*

| *Shopify account*
| Shows for which Shopify account you are carrying out the settings. No action is required in this step.

2+^| Step *Existing input field mappings*

| *Existing input field mappings*
| Shows the current input field mappings. In case some of them are no longer needed, you can select them here for deletion. Once the assistant has been completed, the selected mappings will be deleted.

2+^| Step *Creating a new field mapping*

| *Creating a new field mapping*
| Select the Shopify field to which you want to map a plentymarkets data source in the next step. If you do not want to create a new mapping at this point, leave this field empty.

*_Note:_* You can only create one input field mapping each time you go through the assistant. Therefore, you have to go through the assistant again each time you want to create a new mapping. Choosing *metafield* will create a new assistant step.

2+^| Step *Metafield configuration* (optional)

| *Metafield configuration*
| This step is only available if you choose the option *Metafield* in the *Create new field mapping* step. Enter a metafield namespace and a metafield name for Shopify.

*_Tip:_* During the item export, metafields are automatically created on Shopify based on your input. As such, you do not have to add these metafields in Shopify yourself.

*_Note:_* Shopify Metafields are not visible in the Shopify back end without a specific Shopify app. For more details regarding Shopify metafields, consult the link:https://help.shopify.com/en/manual/metafields[Shopify Help Center^]. Enter the search term *metafield*.

2+^| Step *plentymarkets source input field*

| *plentymarkets source input field*
| Select the plentymarkets source field that will be used to export the customised data. +
*_Note:_* Source input field mappings are only available for *Item export* processes.

2+^| Step *Property* (optional)

| *Property*
| This step is only available if you chose the option *Property* in the *plentymarkets source input field* step. Select the property you want to use as export data source.

|===
--

[.collapseBox]
.*_Example configuration:_* Mapping the base price
--

In Shopify, unit price details are handled using metafields. These metafields are created automatically during the item export. As such, you do not have to create these metafields in Shopify yourself.

To export the unit price to Shopify, you will run through the assistant *Shopify: Input field mapping* three times. During these three run-throughs, you map the following plentymarkets data fields to Shopify metafields:

* Unit price
* Unit price: content
* Unit price » Unit

The steps and settings for each run-through are only described once.

[.instruction]
Mapping plentymarkets data fields for unit price details:

. Go to *Setup » Assistants » Omni-Channel*.
. Open the assistant *Shopify: Input field mapping*.
. Select the Shopify account for which you want to create the mappings. +
→ The step *New input field mapping* is shown.
. From the drop-down list *Mappable Shopify input fields*, select the option *Metafield*.
. Click on *Next*. +
The step *Metafield configuration* is shown.
. Carry out the metafield settings:
    * *_Run-through 1:_* Enter a *metafield namespace* and *metafield name* for the unit price.
    * *_Run-through 2:_* Enter a *metafield namespace* and *metafield name* for the content of the unit price.
    * *_Run-through 3:_* Enter a *metafield namespace* and *metafield name* for the unit of the unit price. +
*_Tip:_* Metafield namespace and metafield name must be unique.
. Click on *Next*. +
The step *plentymarkets source input field* is shown.
. Select an option.
    * *_Run-through 1:_* Select the option *Unit price*.
    * *_Run-through 2:_* Select the option *Unit price: content*.
    * *_Run-through 3:_* Select the option *Unit price: unit*. The table below shows the permitted values for each unit.
. Click on *Next*.
. Click on *Complete*. +
→ The metafields are created on Shopify with the next item export.

[cols="1,3a"]
|===
| Unit | Allowed values

| Length (mm)
| * meter
* Centimetre
* Millimetre
* Customs +
-> The values are exported in meters.

| Volume
| * litre
* millilitre +
-> The values are exported in litres.

| Weight (g)
| * kilogram
* gram
* Milligram
* Ounces +
-> The values are exported in kilograms.
|===

--

[#RM4RZXPC]
=== Activating the order referrer

:referrer: Shopify
:referrer-option: pass:quotes[option *Shopify*]

include::markets:partial$activate-referrer.adoc[]

[#UNO4F1PH]
=== Selecting the sales price

:referrer-price: Shopify

include::markets:partial$define-sales-price.adoc[]

[#LFL990IP]
=== *_Optional:_* Importing custom order properties

The Shopify integration also enables you to import custom order properties using the order import process. 

For example, you can create custom order properties with the Shopify plugin link:https://apps.shopify.com/product-personalizer[Product Personalizer^]. This plugin gives your customers the option to enter custom text during the order process. This allows you to offer personalized products, for example with engravings.

Requirements for importing custom order properties are:

* In the menu *Setup » Item » Characteristics*, create a characteristic for which you activate the option *Order characteristic* on the right.
* The plentymarkets item is linked to the characteristic for which the option *Order characteristic* is activated.

[#further-shops]
=== _Optional:_ Connecting additional Shopify shops

Note the following if you want to connect more than one Shopify shop with plentymarkets:

* Each new connection requires a separate plentymarkets client and a separate Shopify account.
* To create an additional connection, you need to install the plentymarkets app in each Shopify shop you wish to connect.

[#XV8ANTMR]
== Preparing variations

Now, prepare your variations.

*_Before you start:_* Each item can only have up to 100 variations. This limit is set by Shopify. As such, items with more than 100 variations are not exported to Shopify.

[#stock-limitation]
=== Information about stock limitation

In the Shopify back end, the option *Continue selling when out of stock* determines if products are sold if no or not enough stock is in the warehouse. When stock is exported, this option is either activated or not. This depends on the plentymarkets setting xref:item:directory.adoc#220[Stock limitation].

Depending on which *Limitation* you selected for a variation in plentymarkets, the checkbox *Continue selling when out of stock* is either activated or not:

[cols="2,2"]
|====
| plentymarkets option *"Limitation"* | Shopify option *"Continue selling when out of stock"*

| *None*
| Activated

| *To net stock*
| Not activated

| *Do not administer stock for this variation*
| Activated
|====

[#300]
=== Setting the variation availability

:market-availability: Shopify
:option-availability: Shopify

include::markets:partial$variation-availability.adoc[]

[#0U31GAX6]
=== Activating the client for a variation

Only variations that are activated for the client (store) that you use to sell on {market} are exported.

[.instruction]
Activating the client for a variation:

. Go to *Item » Edit item » [Open item] » [Open variation]*.
. Click on the variation tab *Availability*.
. In the area *Client (store)*, activate the client (store) that you use to sell on {market}.
. Save the setting.

[#MK10HTRN]
=== Saving SKU

Only variations with an SKU for the referrer *Shopify* are exported.

[.instruction]
Saving an SKU for Shopify:

. Go to *Item » Edit item » [Open item] » [Open variation] » Variation tab: Settings*.
. Click on the *Availability* tab.
. In the *SKU* area, click on *Add* (icon:plus-square[role="green"]). +
→ The *New SKU* window opens.
. Select the referrer *Shopify*.
. Select the corresponding marketplace account.
. Enter the SKU.
. Click on *Add* (icon:plus-square[role="green"]). +
→ The SKU is saved and displayed.

[#TUVEBVS1]
=== Saving other mandatory information

The following information is mandatory for exporting variations to Shopify. Save this information to export your variations.

[.collapseBox]
.Save a "Name 1" and an "Item text" saved for the item.
--

[.instruction]
Saving Name 1 and item text:

. Go to *Item » Edit item » [Open item]*.
. Switch to the tab *Texts*.
. In the toolbar, select the *Language* in which you export item data to Shopify.
. Enter a name in the field *Name 1*.
. Enter an item text in the field *Item text*.
. Click on *Save*.
--

[.collapseBox]
.Ensure that an attribute name and an attribute value are saved for the variation in the export language.
--

An attribute name and an attribute value must be saved for the variation in the language you use for the item export.

[.instruction]
Checking attribute name and attribute value for a variation:

. Go to *Item » Edit item » [Open item] » [Open variation]*.
. In the tab *Settings*, navigate to the area *Basic settings*. +
→ The attributes that are linked to the variation are listed underneath the setting *Position*.

Now, you can check the settings of the attributes. Are the attribute name and the attribute value saved in the language you need?

[.instruction]
Checking name and value of an attribute:

. Go to *Setup » Item » Attributes » [Open attribute] » Tab: Values*.
. Click on the *Name* tab.
. Check the content of the field for the language.
. If necessary, enter a name for the attribute.
. Click on the *Values* tab.
. In the toolbar, select the *Language* in which you export item data to Shopify.
→ The values of the attribute are shown.
. If necessary, enter a name for the attribute value.
. Click on *Sav* if you have made changes.
--

[#OPOU57M9]
=== _Check list:_ Requirements for exporting variations

include::markets:partial$checklist-variations.adoc[tag=checklist-intro]

include::markets:partial$checklist-variations.adoc[tag=checklist-variation-active]

include::markets:partial$checklist-variations.adoc[tag=checklist-variation-referrer]

include::markets:partial$checklist-variations.adoc[tag=checklist-availability-active]

include::markets:partial$checklist-variations.adoc[tag=checklist-net-stock]

include::markets:partial$checklist-variations.adoc[tag=checklist-sales-price]

:number-of-variations: 100
include::markets:partial$checklist-variations.adoc[tag=checklist-number-of-variations]

include::markets:partial$checklist-variations.adoc[tag=checklist-name-text-shopify]

include::markets:partial$checklist-variations.adoc[tag=checklist-attributes-shopify]

include::markets:partial$checklist-variations.adoc[tag=checklist-market-sku]

include::markets:partial$checklist-variations.adoc[tag=checklist-market-client]

[#E4EO9VDN]
== Order group processing

Find out how orders are processed.

[#event-procedures]
=== Setting up event procedures

Use xref:automation:event-procedures.adoc#[plentymarkets event procedures] to automate order communication with Shopify.

The following event procedures are available for the Shopify app:

*_Tip:_* Event procedures are set up in the menu *Setup » Orders » Events*. In the list *Add procedure*, the procedures for the Shopify apps are listed in the folder *Plugins*.

* Shopify App: Save plentymarkets order Id in Shopify
* Shopify App: Archive Shopify order
* Shopify App: Send manually added payment to Shopify
* Shopify App: Send fulfilment notification to Shopify
* Shopify App: Send returns to Shopify
* Shopify App: Send cancel notification to Shopify
* Shopify App: Send credit note to Shopify
* Shopify App: Send cancellation/refund to Shopify
* Shopify App: Send refund/cancellation to Shopify without stock adjustment

[#gdpr]
== Contact import and GDPR

Due to GDPR specifications, the following policies for customer accounts and orders have been implemented:

[[table-gdpr]]
.GDPR considerations during order import
[cols="1,2"]
|===
|*Scenario* |*Explanation*

| Customer is imported as regular contact
| If the authenticity of the Shopify customer is guaranteed by a unique external contact ID, a regular account is created.

| An existing plentymarkets contact is linked to the imported order
| It is checked whether a customer from Shopify with this external contact ID has been imported in the past. If a contact is found, the new order is assigned to this contact.

| Customer is imported as guest
| If the customer does not have a plentymarkets account and Shopify also cannot guarantee the authenticity of the customer, the contact is imported as a guest. That also applies if the contact data of several orders are identical.

*Tip:* You can convert contacts of the type *Guest* to xref:quick-search.adoc#convert-guest-account[regular contacts].
|===

[#plugin-help]
== Using help functions

The menu *Setup » Markets » Shopify app* offers the following functionality:

* <<#3873695972, Check the connection to Shopify.>>
* <<#6535986175, Check the export conditions of a variation.>>
* <<#8878636701, Manually export an item every 10 minutes.>>
* <<#4973807959, Export the stock of a variation or an item every 5 minutes.>>
* <<#0389029301, Find a plentymarkets order ID by entering the Shopify order number.>>
* <<#7088931107, Plan an item cleanup.>>

[#3873695972]
=== Checking the connection to Shopify

[.instruction]
Checking the connection to Shopify:

. Go to *Setup » Markets » Shopify app » Health check*.
. Click on *Check*. +
→ The system checks if a connection to Shopify.com can be established. +
→ The system checks if Shopify Direct Checkout is installed. +
*_Tip:_* Conditions that are fulfilled are marked with a green *OK*. Conditions that have failed are marked in red and with an *X*.

*_No connection to Shopify? Then check the following conditions:_*

* In the menu *Setup » Orders » Order referrer*, Is the order referrer *Shopify* active?
* Is there more than one *Shopify* referrer entry in the menu *Setup » Orders » Referrer*? Make sure that the ID with the highest number is active.

[#6535986175]
=== Checking export conditions for variations

Check if a variation meets all requirements to be exported to Shopify.

[.instruction]
Checking export conditions for variations:

. Select the online shop that you want to check the variation for.
. Go to *Setup » Markets » Shopify App » Export conditions*.
. Enter a valid variation ID.
. Click on *Check*. +
→ The variation is checked. +
*_Tip:_* Conditions that are fulfilled are marked with a green *OK*. Conditions that have failed are marked in red and with an *X*. +
*_Important:_* Variations must meet all requirements to be exported.

*_The following conditions are checked:_*

* Is the variation active? +
→ In the menu *Item » Variation » Settings » Area: Availability*, the checkbox *Active* must be set.
* Is the variation available for Shopify? +
→ *Item » Variation » Availability » Area: Markets » Option Shopify* must be selected.
* Does the *Variation » Client* assignment match your *online shop* selection? +
→ *Item » Variation » Availability » Area: Client » [Selected client*.
* Is an *item text* saved for the item? +
→ *Item » Texts » Item text* must be entered.
* Is a *Name 1* saved for the item? +
→ *Item » Texts » Name 1* must be saved.
* Does the variation have an SKU for Shopify? +
→ *Item » Variation » Availability » Area: SKU* section must contain an *SKU* for the referrer *Shopify*.
* Does the variation have a sales price with default currency that is activated for Shopify?
* Is a variation attribute name saved for the selected item export language?
* Is a variation attribute value saved for the selected item export language?
* Is an item title and description saved in the selected item export language?
* Does the item have no more than 100 variations? +
→ Exported items must not contain more than 100 variations. This limit is set by Shopify.

// TODO: Liste besser gestalten.

[#8878636701]
=== Manually exporting items

For testing purposes, you can manually export an item every 10 minutes.

[.instruction]
Manually exporting an item:

. Go to *Setup » Markets » Shopify app Item export*.
. Select an online shop.
. Enter a valid item ID.
. Click on *Execute*. +
→ If all export requirements are met, the item and the corresponding variations will be exported.

*_Note:_* If you have deleted one or more items on Shopify to re-export them, the first export only cleans up the database. Only the second export saved the item in Shopify again.

[#2729787975]
=== Manually exporting stock

For testing purposes, you can manually export an item’s stock every 5 minutes. For variations, you can start an export every 3 minutes.

[tabs]
====
Manually exporting stock for an item::
+
--

[.instruction]
Exporting stock for an item:

. Go to *Setup » Markets » Shopify app » Stock export*.
. Select an online shop.
. From the drop-down list *xxx*, select the option *Export stock for item*.
. Enter a valid *item ID*.
. Click on *Execute*. +
→ If all export requirements are met, the stock of the item will be exported. +
*_Note:_* You need to wait 5 minutes before exporting another item.
--
 
Manually exporting stock for a variation::
+
--
[.instruction]
Exporting stock for a variation:

. Go to *Setup » Markets » Shopify app » Stock export*.
. Select an online shop.
. From the drop-down list *xxx*, select the option *Export stock for variation*.
. Enter a valid *variation ID*.
. Click on *Execute*. +
→ If all export requirements are met, the stock of the variation will be exported. +
*_Note:_* You need to wait 3 minutes before exporting another variation.
--
====

[#8869548744]
=== Setting a custom start date for stock exports

If you want to export stock quantities for items with an older *last change* date.

[.instruction]
Setting a start date:

. Go to *Setup » Markets » Shopify app » Stock export*.
. Select an online shop.
. From the drop-down list, select the option *Update date*.
. Select a start date from the *calendar*.
. Enter a *time*.
. Click on *Save*. +
→ The next stock export runs at the time you selected. +
*_Important:_* The start date shown is updated after every export.

[#0389029301]
== Finding the plentymarkets order ID by using Shopify order number

If a customer contacts you with the Shopify order ID, you can use this ID to find out the corresponding plentymarkets order ID.

[.instruction]
Finding the plentymarkets order ID:

. Go to *Setup » Markets » Shopify App » Find order ID*.
. Select the webshop.
. Enter a valid Shopify order number.
. Click on *Search*. +
→ If the Shopify order number is valid, the plentymarkets order ID will be shown.

[#7088931107]
== Planning an item cleanup

Plan an item cleanup if: 

* You have deleted or deactivated items or variations from plentymarkets and you also need to remove them from Shopify.
* You have manually deleted items or variations from Shopify and they are not re-exported by the plugin.
* You want to delete all items from Shopify and start a new item export from plentymarkets. In this case, deactivate the item export and delete all items from Shopify. Plan an item cleanup. You can reactivate the item export the next morning.

*_Note:_* Do not use the item cleanup if your items were imported from Shopify after you set up the connection. This can delete items on Shopify. The item cleanup only runs once after you planned it. If necessary, plan additional item cleanups.
 
[.instruction]
Planning an item cleanup:

. Go to *Setup » Markets » Shopify app » Item cleanup*.
. Select the *online shop* that you want to plan a cleanup for.
. Click on *Plan cleanup*. +
→ Affected items are deleted from Shopify during the next nightly export.

*_Note:_* Items and variations that were already exported will be deleted from Shopify if:

* The *client* and the availability *Shopify* were removed from the variation.
* The variation was deleted from plentymarkets.
* For items with no active variations, the complete item is deleted from Shopify.
