= SPoCC Connector
:keywords: SPoCC, SPoCC interface, SPoCC connector, SPoCC extension, Apollon, Single Point of Content and Communication
:description: Learn how to connect your SPoCC system with plentymarkets.
:page-index: false
:author: team-plenty-channel

////
erstellt am 28.06.2022
Project Manager: Tina Gerber
https://docs.google.com/presentation/d/12mym8JIQqPc1BhJEeYFlxQfGqoQC9IiBvyt1mDx3fJo/edit#slide=id.g1321ed4c3cb_0_86
////

//ToDo when the page can be made visible in the left navigation - remove the attribute :page-index: false from the header and add the page to the navigation file in the ROOT folder

SPoCC and plentymarkets – a great combination.
Do you already use SPoCC as an inventory management tool for shoe retail?
And are you ready to get started in e-commerce with plentymarkets?
Then you’re in the right place.
The SPoCC plugin connects your SPoCC system to plentymarkets.

* Continue using SPoCC for your sales.
* Import the item data imported in the SPoCC database to plentymarkets.
* Modify the item data in plentymarkets as needed and then sell your items on various marketplaces, sales channels and online shops.
* Export order data to SPoCC.

NOTE: This manual page is right for you if you are a SPoCC customer but do not yet use plentymarkets productively.
Do you already use plentymarkets and want to get started on SPoCC? Then contact our setup team.

[#6600540000]
== Data exchange

After you have set up the interface to SPoCC, the automatic processes described in <<#data-exchange>> are available.

[[data-exchange]]
.Data exchange
[cols="3a,3a"]
|===
|Data |Interval

| Import of new items to plentymarkets +
Master data: EAN, name, itemnumbers, colour, size, etc.
| Once every 24 hours

| Import of additional item data to plentymarkets: +
SPoCC attributes in properties
| Every 60 minutes

| Import of images to plentymarkets
| Every 60 minutes

| Import of prices to plentymarkets
| * Complete import every 24 hours
* Changed data every 15 minutes

| Import of stock details to plentymarkets
| * Complete import every 24 hours
* Changed data every 15 minutes

| Export of orders to SPoCC:

* Create order, notifications, reserve stock
* Update order when ready four shipping
| When event procedure is triggered

| Request order status:

* Cancellation
| Every 20 minutes

| Provide shipping documents
| When event procedure is triggered
|===

[#5733676376]
== Requirements

This page assumes that you are already a customer of link:https://www.SPoCC.io/[SPoCC] and link:https://www.plentymarkets.com/[plentymarkets].
Have your access data for both systems at hand.
While setting up the interface, you will enter your access data to make the connection.

Furthermore, you will map your SPoCC barcodes, sales prices, categories, etc. to those in plentymarkets.
If you have not set up your plentymarkets system yet, then you should create the following data before you continue:

* xref:stock-management:setting-up-a-warehouse.adoc#[Warehouses]
* xref:orders:order-referrer.adoc#[Order referrers]
* xref:item:flags.adoc#400[Tags]
* xref:item:barcodes.adoc#[Barcodes]
* xref:item:attributes.adoc#[Attributes]
* xref:item:properties.adoc#[Properties]
* xref:item:prices.adoc#[Sales prices]
* xref:item:categories.adoc#[Categories]

[#6203207193]
== Downloading and installing the plugin

The SPoCC plugin is available on plentyMarketplace.
The plugin connects your SPoCC system to plentymarkets.

The SPoCC plugin offers the following functionality:

* *_Import items_*:
Item data is exported from SPoCC to plentymarkets.
You decide which item data is sent to plentymarkets and how the items are structured there.
* *_Export orders_*:
Order data is transmitted from plentymarkets to SPoCC.
plentymarkets notifies SPoCC of the sale and automatically books the revenue into the correct SPoCC sales store.
* *_Update stock levels and prices_*:
Whenever stock levels or prices are updated in SPoCC, this information is transmitted to plentymarkets.

[.collapseBox]
.*Step-by-step instructions*
--

. Download the SPoCC plugin from plentyMarketplace. +
→ If prompted, sign into plentyMarketplace.
Use the same access data as for the “My account” area.
. Go to *Plugins » Plugin set overview*.
Plugins can only be used as part of a plugin set. Therefore:
.. *_Option A_*: Create a completely new plugin set.
To do so, click on icon:plus[role="darkGrey"] *Add plugin set* and enter a name.
.. *_Option B_*: Create a copy of an existing plugin set.
To do so, go to the *Actions* column and click on *Copy plugin set* (icon:copy[set=plenty]).
.. *_Option C_*: Decide which existing plugin set is suitable for the SPoCC plugin.
. Open the plugin set by clicking on the line in the table. +
→ The plugin set opens.
. Click on icon:plus[role="darkGrey"] *Add plugin*.
. Select the SPoCC plugin from the plugin list. +
→ Information about the plugin is displayed.
. Select the version you want to install from the *Select version* drop-down list.
The newest version is selected by default.
. To install the plugin, click on icon:arrow-down[role="darkGrey"] *Install*. +
→ The plugin is installed. +
→ After installation has finished, the plugin set opens.
. Switch the plugin to active (icon:toggle-on[role="blue"]).
. Deploy the plugin set (icon:cloud-upload[role="darkGrey"]).

Are you new to plugins?
The xref:plugins:plugins.adoc#[plugins chapter] of the manual teaches you more about plugins and how they work in plentymarkets.

--

[TIP]
.Interface is set up in the assistant
====
You do not need to configure any settings directly in the plugin.
Instead, open the assistant.
The assistant guides you through the setup process.
====

[#8286334278]
== Completing the assistant

The assistant helps you specify how plentymarkets and SPoCC communicate with each other.
For example, you’ll decide which item data is sent to plentymarkets and how the items are structured there.

[.instruction]
Configuring the settings in the assistant:

. Go to *Setup » Assistants » Plugins » [Open plugin set]*.
. Click on *SPoCC assistant*.
. Follow the instructions on the screen.
Information about the individual steps can be found further below on this page.
. In the step *Summary*, check your settings to makes sure they are correct.
. Once all of the settings are correct, click on icon:check[role="green"] *Finalise*. +
→ The settings are saved.

[#8232754027]
=== Step "Connection"

In this step, you’ll connect plentymarkets and SPoCC.
In other words, you’ll enter your access data so that plentymarkets and SPoCC can communicate with each other.

[[table-connection-settings]]
.Step "Connection"
[cols="1,2"]
|===
|Setting |Explanation

2+^| *Test mode*

| *Test mode*
| Activate this option to use the test mode for exchanging data between SPoCC and plentymarkets.

2+^| *Login details*

| *Global Stock API Key* +
(mandatory)
| Enter the key for the Global Stock API that you received from SPoCC.

| *Transaction Service API Key* +
(mandatory)
| Enter the key for the Transaction Service API that you received from SPoCC.

| *Content Article API Key* +
(mandatory)
| Enter the key for the Content Article API that you received from SPoCC.

| *Retailer ID* +
(mandatory)
| Enter the seller ID that you received from SPoCC.

//| *Customer number* +
//(mandatory)
//| Enter your SPoCC customer number.

//| *Channel ID* +
//(mandatory)
//| Enter the number *4*. At SPoCC, plentymarkets always has this channel ID.
|===

[#9643799177]
=== Step "Item import"

In this step, you’ll decide what the data that comes from SPoCC should look like in plentymarkets.
In other words, where the data should be saved in plentymarkets.

[[table-item-import-field-mappings]]
.Options for the item import
[cols="1,3a"]
|===
|Setting |Explanation

| *Complete item import*
| Activate this option to activate the complete item import. +
*_Important:_* This option is deactivated automatically after the first complete item import. As such, only new and changed item data is imported. If you need another complete item import at a later date, activate this option again and complete the assistant.

| *Tag for importing extended item data*
| This tag is used to flag variations for which additional item data is to be imported from SPoCC. Data such as EAN, images and properties is imported from SPOCC for variations that you flag with this tag. 

*_Requirement_*:
Have you already xref:item:flags.adoc#400[created the necessary tags in plentymarkets]?
This drop-down list only includes tags that have already been created and made available for variations.

| *Default category*
| Imagine you created a new category in SPoCC.
But you forgot to map it with a corresponding plentymarkets category.
If you import items from the non-mapped category, they will land in the default plentymarkets category that you select here.

*_Requirement_*: Have you already xref:item:categories.adoc#[created categories in plentymarkets]?
This drop-down list only includes the categories that already exist in plentymarkets.

| *Barcode*
| Which plentymarkets barcode type matches your SPoCC barcode?
Select the barcode type from the drop-down list.

*_Requirement_*: Have you already xref:item:barcodes.adoc#100[configured barcode types in plentymarkets]?
This drop-down list only includes the barcode types that already exist in plentymarkets.

| *Barcode as SPoCC ID*
| When variations are created, a unique SPoCC ID is saved as the variation number. This ID is composed of the eight digit ECC variation number and a three digit size number. However, to make sure that existing variations can also be matched correctly, you need an additional barcode type where this ID can be saved for all variations. 

*_Requirement_*: Have you already xref:item:barcodes.adoc#100[configured barcode types in plentymarkets]?
This drop-down list only includes the barcode types that already exist in plentymarkets.

| Attribute: *Colour attribute*
| Which plentymarkets attribute matches your SPoCC colour attribute?
Select the attribute from the drop-down list.

*_Requirement_*: Have you already xref:item:attributes.adoc#[configured attributes in plentymarkets]?
This drop-down list only includes the attributes that already exist in plentymarkets.

| Attribute: *Size attribute*
| Which plentymarkets attribute matches your SPoCC size?
Select the attribute from the drop-down list.

*_Requirement_*: Have you already xref:item:attributes.adoc#[configured attributes in plentymarkets]?
This drop-down list only includes the attributes that already exist in plentymarkets.
|===

[#3309305166]
=== Step "Sales prices"

There are three prices in SPoCC:

* Sales price
* Target price
* Recommended retail price

[[table-sales-prices]]
.Mapping of sales prices
[cols="1,3a"]
|===
|Setting |Explanation

| *Sales price* +
(retailPrice)
| Which plentymarkets sales price do you want to use for the sale price in SPoCC?
Select the appropriate plentymarkets sales price from the drop-down list.

* The price including VAT that the customer has to pay.

*_Requirement_*: Have you already xref:item:prices.adoc#[configured sales prices in plentymarkets]?
This drop-down list only includes the sales prices that already exist in plentymarkets.

| *Target price* +
(targetPrice)
| Which plentymarkets sales price do you want to use for the target price in SPoCC?
Select the appropriate plentymarkets sales price from the drop-down list.

* The target price is the price including VAT that you use as your regular price.

*_Requirement_*: Have you already xref:item:prices.adoc#[configured sales prices in plentymarkets]?
This drop-down list only includes the sales prices that already exist in plentymarkets.

| *Recommended retail price* +
(recommendedRetailPrice)
| Which plentymarkets sales price do you want to use for the recommended retail price in SPoCC?
Select the appropriate plentymarkets sales price from the drop-down list.

* The recommended retail price is the price including VAT that the supplier or manufacturer suggests as the regular price.
* The recommended retail price is usually only shown if the target price is lower than the recommended retail price, i.e. to show a lower price.

*_Requirement_*: Have you already xref:item:prices.adoc#[configured sales prices in plentymarkets]?
This drop-down list only includes the sales prices that already exist in plentymarkets.
|===

[#5583100996]
=== Step "Map properties"

In plentymarkets, you use properties to handle SPoCC attributes.
As such, you map plentymarkets properties to your SPoCC attributes in this step.

// TODO: Explain what attributes are in SPOCC.

. On the very right, click on icon:plus[].
. From the drop-down list *plentymarkets property* on the left side, select a property. +
*_Requirement_*: Have you already xref:item:properties.adoc#[configured properties in plentymarkets]?
This drop-down list only includes the properties that already exist in plentymarkets.
. From the drop-down list *SPoCC attribute* on the right, select an attribute. +
→ The two records are mapped to each other.
. Map additional properties in the same way.

[[table-property-mapping]]
.Properties mapping
[cols="1,3a"]
|===
|Setting |Explanation

| *plentymarkets property*
| This drop-down list contains the categories that you have set up in plentymarkets.
Select the appropriate property from the drop-down list.

*_Requirement_*: Have you already xref:item:properties.adoc#[configured properties in plentymarkets]?
This drop-down list only includes the properties that already exist in plentymarkets.

| *SPoCC attribute*
| This drop-down list contains your SPoCC attributes.
Select the appropriate attribute from the drop-down list.

| icon:plus[role="green"]
| Adds another line.
This allows you to map additional properties.

| icon:minus-circle[role="red"]
|Deletes a line.
This allows you to remove mappings that are no longer needed.
|===

// TODO: Insert example with screenshot

[#3055919608]
=== Step "Categories"

In this step, you map the product groups used in SPoCC to the categories in plentymarkets.
This way, your items are directly sorted into the correct plentymarkets categories when they are imported from SPoCC.

*_Important:_* Items in SPoCC categories that you did not map in this step will be sorted into a default category. This default category is the one you select in the step *Options for the item import*.

[[table-category-mapping]]
.Mapping of categories
[cols="1,3a"]
|===
|Setting |Explanation

| *SPoCC product group*
| These are your product groups in SPoCC.
Select the appropriate product group from the drop-down list.

| *plentymarkets category*
| These are the categories that you’ve set up in plentymarkets.
Select the appropriate category from the drop-down list.

*_Requirement_*: Have you already xref:item:categories.adoc#[created categories in plentymarkets]?
This drop-down list only includes the categories that already exist in plentymarkets.

| icon:plus[role="green"]
| Adds another line.
This allows you to map multiple categories.

| icon:minus-circle[role="red"]
| Deletes a line.
This allows you to remove mappings that are no longer needed.
|===

[TIP]
.Alternative procedure without assigning categories
====
Technically speaking, you could just select a default category in the step "Item import" and then skip the rest of the category assignment.
As a result, your items would always land in the default category when they are imported.
If needed, you would then have to move the items into different plentymarkets categories manually.
====

[#5582523636]
=== Step "Warehouse"

In this step, you map your Channel Store Number from SPoCC to your plentymarkets warehouses.

[[table-warehouse-mapping]]
.Mapping warehouses
[cols="1,3a"]
|===
|Setting |Explanation

| *SPoCC Channel Store Number*
| These are your warehouses in SPoCC.
Select the appropriate Channel Store Number from the drop-down list.

| *plentymarkets warehouse*
| These are your warehouses in the plentymarkets menu *Setup » Stock » Warehouse*.

| icon:plus[role="green"]
| Adds another line.
This allows you to map multiple warehouses.

| icon:minus-circle[role="red"]
| Deletes a line.
This allows you to remove mappings that are no longer needed.
|===

[#5725666131]
=== Step "Markets"

[[table-market-mapping]]
.Mapping markets
[cols="1,3a"]
|===
|Setting |Explanation

| *plentymarkets referrers*
| The drop-down list contains your markets in plentymarkets.
Select a character set from the drop-down list.

| *SPoCC referrers*
| The drop-down list contains your markets in SPoCC. Select the same market from the drop-down list.

| icon:plus[role="green"]
| Adds another line.
This allows you to map multiple markets.

| icon:minus-circle[role="red"]
| Deletes a line.
This allows you to remove markets that are no longer needed.
|===

[#8356545049]
=== Step "Return reasons"

[[table-return-reason-mapping]]
.Mapping return reasons
[cols="1,3a"]
|===
|Setting |Explanation

| *plentymarkets return reasons*
| The drop-down list contains your return reasons in plentymarkets.
Select a return reason from the drop-down list.

*_Important:_* SPoCC always expects that a return reason is given. If you have not mapped a SPoCC return reason for a plentymarkets return reason, the return reason *[1] No reason* is exported to SPoCC.

| *SPoCC reasons for return*
| The drop-down list contains your return reasons in SPoCC. From the drop-down list, select a return reason that corresponds to the reason you selected in the column *plentymarkets return reason*.

| icon:plus[role="green"]
| Adds another line.
This allows you to map multiple return reasons.

| icon:minus-circle[role="red"]
| Deletes a line.
This allows you to remove return reasons that are no longer needed.
|===

[#2236081566]
=== Step "Processes"

Data is transmitted between SPoCC and plentymarkets with the help of Crons.

include::_includes:partial$crons.adoc[]

In this step, you’ll activate the processes that should run automatically (icon:check-square[role="blue"]).

[[table-cron-settings]]
.When do the processes run?
[cols="1,1,3a"]
|===
|Process |Interval |Explanation

| *Import of SPoCC attributes*
| Hourly
| Imports the SPoCC attributes to plentymarkets.

| *Item import*
| Daily
|
* Once you have completed the assistant, all of your items will initially be transmitted from SPoCC to plentymarkets.
This initial, full import can take a few days to finish, depending on the number of products.
* Afterwards, only a sub-set of items will be imported, based on the previously selected <<#80, import settings>>.
* Only new items, new variations of existing items and changed items and variations are imported.
* The item import starts at the end of the day, or rather during the night.

| *Import of extended item data*
| ???
| Imports EAN, images and properties for variations that are flagged with the tag you selected for the setting *Tag for importing extended item data*.

| *Import of images*
| Every 60 minutes
| Imports SPoCC images to plentymarkets.

| *Complete stock/price update*
| Once every 24 hours
| All stock and price data is updated.

| *Update changed stock and price data*
| Every 15 minutes
| Only changed stock and price data is updated.
|===


[#4201942886]
== Opening and modifying newly imported item data

The next time the process runs, your item data will be imported from SPoCC to plentymarkets.
This assumes that you’ve:

* activated the *Item import* process (icon:check-square[role="blue"]).
* completed the assistant.
* activated the plugin within the set.

[#7263303278]
=== Opening newly imported items

Open a few item data records and make sure that your item data was correctly imported.

. Go to *Item » Edit item*.
. Use the xref:item:search.adoc#[search filters] on the left to specify which items you want to access.
For example:
.. Set the *Active* filter to *ALL* or *No*, since items are inactive when they are imported.
. Click on *Search* (icon:search[role="blue"]). +
→ The search results are displayed in an overview on the right.
. Click on an item in the overview to open the item data record.

[TIP]
.Main variation vs. Sub-variation
====
Check the data that was transmitted for the main variation and for the sub-variations:

* *_Main variation_*: An item’s first variation is called its main variation.
It is not for sale, but rather is purely virtual and helps you manage the sub-variations via xref:item:inheritance.adoc#[inheritance].
When you open an item data record, the main variation automatically opens too.
* *_Sub-variation_*: The sub-variations are the saleable versions of the product.
For example, if a t-shirt is sold in the colours blue and red and the sizes S, M, L, then every single combination (Blue S, Blue M, Blue L, Red S, Red M, Red L) is a sub-variation.
To open a sub-variation, click on the tab *Variations* and then on *Search* (icon:search[role="blue"]).
Finally, click on a sub-variation in the overview.
====

[#9285917774]
=== Modifying item data

Once you’re happy with the item data that was transmitted, you can start preparing your items to be sold online.
For example, you can:

* add xref:item:managing-items.adoc#50[descriptive texts], xref:item:managing-items.adoc#90[product images] and relevant xref:item:managing-items.adoc#50[meta data].
* specify where your products should be sold, i.e. select xref:item:managing-items.adoc#340[order referrers] and xref:item:managing-items.adoc#340[clients].
* xref:item:managing-items.adoc#200[activate] your variations when you are ready for them to go live.

For a complete list of all the item data fields in plentymarkets, refer to the page xref:item:managing-items.adoc#[Directory of data fields].

[#9632625453]
== Processing orders

When a product is sold, the order data lands in the plentymarkets menu *Orders » Edit orders*.
The order can be processed here and its progress can be tracked with the help of a status.

Further information about processing orders in plentymarkets can be found on the xref:orders:managing-orders.adoc#[Managing orders] page of the manual.

[#2728429959]
== Setting up event procedures

Of course, the order data shouldn’t just stay in plentymarkets. Rather, it should also be transmitted to SPoCC.
You will set up event procedures to do this.
These event procedures only need to be set up once, in order for the export to work correctly.

The following event procedures are available for SPOCC:

* <<#5454333207, Notify SPoCC of new orders>>
* <<#8993901978, Inform SPoCC about payments>>
* <<#0414974358, Inform SPoCC about the creation of order documents>>
* <<#1052999368, Inform SPoCC about returns>>
* <<#UI7TSJAK, Process orders after shipping confirmation>>
* <<#VOQ82RU7, Process orders not registered with SPOCC>>
* <<#KZ1UJ2CB, Process orders after a cancellation request>> 

For further information, refer to the xref:automation:event-procedures.adoc#[Event procedures] page of the manual.

[#5454333207]
=== Notifying SPoCC of new orders

When a new order lands in plentymarkets, SPoCC should be informed of the order.
This allows SPoCC to reserve the necessary stock and avoid overselling.

Set up an xref:automation/event-procedures.adoc#[event procedure] for that purpose.

:table-event-procedure: <<#table-event-procedure-one>>

include::_includes:partial$event-procedure.adoc[]

[[table-event-procedure-one]]
[cols="1,3a"]
|===

| Event
| New order

|Filter (optional)
|Order > Referrer +
Order > Client (store)

| Action
| Plugins > SPoCCConnector: Register order +
→ An order with the SPoCC status ID is created in SPoCC. +
→ The stock is reserved in SPoCC.
|===

[#8993901978]
=== Inform SPoCC about payments

SPoCC is to be informed when the order is paid.
Only then, the order becomes accessible for the SPoCC shop and the order can be processed by the warehouse.

Set up an xref:automation/event-procedures.adoc#[event procedure] for that purpose.

:table-event-procedure: <<#table-event-procedure-8993901978>>

include::_includes:partial$event-procedure.adoc[]

[[table-event-procedure-8993901978]]
[cols="1,3a"]
|===

| Event
| *Status change > [Select status that is to be set when event is triggered]*

|Filter (optional)
|Order > Referrer +
Order > Client (store)

| Action
| Plugins > SPoCCConnector: Order paid +
→ The order is moved to the SPoCC status ??? in SPoCC. +
→ The order becomes accessible for the SPoCC shop and can be processed by the warehouse.
|===

[#0414974358]
=== Inform SPoCC about the creation of order documents

Automatically inform SPOCC that shipping documents have been created. This informs the store that the order can be shipped.

Set up an xref:automation/event-procedures.adoc#[event procedure] for that purpose.

:table-event-procedure: <<#table-event-procedure-0414974358>>

include::_includes:partial$event-procedure.adoc[]

[[table-event-procedure-0414974358]]
[cols="1,3a"]
|===

| Event
| *Status change > [Select status that is to be set when event is triggered]* +
*_Example:_* *Status change > [5] Cleared for shipping*


|Filter (optional)
|Order > Referrer +
Order > Client (store)

| Action
| Plugins > SPoCCConnector: Shipping documents created +
→ Order documents are exported to SPoCC. +
|===

[#1052999368]
=== Inform SPoCC about returns

Automatically inform SPoCC that a variation is to be returned. The store knows that a return is on its way.

Set up an xref:automation/event-procedures.adoc#[event procedure] for that purpose.

:table-event-procedure: <<#table-event-procedure-1052999368>>

include::_includes:partial$event-procedure.adoc[]

[[table-event-procedure-1052999368]]
[cols="1,3a"]
|===

| Event
| *Status change > [Select status that is to be set when event is triggered]* +

|Filter (optional)
|Order > Referrer +
Order > Client (store)

| Action
| Plugins > SPoCCConnector: Register return +
→ The order is moved to the SPoCC status ID 18 in SPoCC. +
→ The return reason is exported. If you have not mapped a SPoCC return reason for a plentymarkets return reason, the return reason *[1] No reason* is exported to SPoCC.

|===

[#UI7TSJAK]
=== Processing orders after shipping confirmation

Select what happens to orders after SPoCC has confirmed shipping.

Set up an xref:automation/event-procedures.adoc#[event procedure] for that purpose.

:table-event-procedure: <<#table-event-procedure-UI7TSJAK>>

include::_includes:partial$event-procedure.adoc[]

[[table-event-procedure-UI7TSJAK]]
[cols="1,3a"]
|===

| Event
| SpoccConnector | Order shipped

|Filter (optional)
|Order > Referrer +
Order > Client (store)

| Action
| [Select procedure.] +
*_Example:_* *Status change* > *[7] Outgoing items booked*]

|===

[#VOQ82RU7]
=== Processing orders not registered with SPOCC

Select what happens to orders that could not be registered with SpoCC. These are new orders for which the procedure *SPoCCConnector: Register order* could not be triggered.

Set up an xref:automation/event-procedures.adoc#[event procedure] for that purpose.

:table-event-procedure: <<#table-event-procedure-VOQ82RU7>>

include::_includes:partial$event-procedure.adoc[]

[[table-event-procedure-VOQ82RU7]]
[cols="1,3a"]
|===

| Event
| SpoccConnector | Registration failed

|Filter (optional)
|Order > Referrer +
Order > Client (store)

| Action
| [Select procedure.] +
*_Example:_* *Change status > *[Select status for manual check]*

|===

[#KZ1UJ2CB]
=== Processing orders after a cancellation request

Select what happens to orders that were cancelled in SPoCC.

Set up an xref:automation/event-procedures.adoc#[event procedure] for that purpose.

:table-event-procedure: <<#table-event-procedure-KZ1UJ2CB>>

include::_includes:partial$event-procedure.adoc[]

[[table-event-procedure-KZ1UJ2CB]]
[cols="1,3a"]
|===

| Event
| SpoccConnector | Cancellation requested

|Filter (optional)
|Order > Referrer +
Order > Client (store)

| Action
| [Select procedure.] +
*_Example:_* *Status change* > *[8.1] Cancelled by customer*]

|===