//

If you want to create a new view set, you can use an existing view set as template.
Use the export function to export your view sets, which are saved as .json files. You can then import these files in other view sets to use them as template. +

You can also import view sets from different menus. Meaning that you can import a dashboard view set into an item view set.
Incompatible elements are not transferred during the import to guarantee that the menu still works with the imported view set. +

To import and export view sets you will need the following right: *View sets » Create*


== Exporting view sets

[.instruction]

Proceed as follows to export a view set:

. Open the view set you want to export.
. Click on *Export selected view* (material:download_2[]).
→ The selected view set is downloaded as a json file.

== Importing view sets

[.instruction]

Proceed as follows to import view sets:

. Open the menu in which you want to import a view set.
. Click on *Import view sets* (material:upload_2[]).
→ The window *Import view* opens.
. Click on *Select file*(material:attach_file[]).
. Select the .json file you want to import.
. Click on *Import*.
→ The view set is imported.