////
Nutzung:

:rights-purpose: What are the rights needed for?
:right-one: *CRM > Campaign > Code > Show*

include::PATH_TO_FILE/rights.adoc[]

The attributes :right-one: up to :right-nine: contain the paths for the needed rights.
If less than nine attributes are needed do not type in the attribute.
////

Users without administrator rights xref:business-decisions:user-accounts-access.adoc#105[can only see certain areas and menus] in plentymarkets. This means they only have limited access to the system. Should coworker {rights-purpose} they need at least one of the following rights:

ifdef::right-one[]
* {right-one}
endif::[]
ifdef::right-two[]
* {right-two}
endif::[]
ifdef::right-three[]
* {right-three}
endif::[]
ifdef::right-four[]
* {right-four}
endif::[]
ifdef::right-five[]
* {right-five}
endif::[]
ifdef::right-six[]
* {right-six}
endif::[]
ifdef::right-seven[]
* {right-seven}
endif::[]
ifdef::right-eight[]
* {right-eight}
endif::[]
ifdef::right-nine[]
* {right-nine}
endif::[]

[.collapseBox]
.*Tip: How to grant rights*
--

Note that only *Admin* users can grant rights.

[.instruction]
Assigning rights:

. Open the menu  *Setup » Account management » Roles*. +
→ The roles overview opens.
. Click on *New* (material:add[]). +
→ The role creation menu opens.
. Enter a name for the role.
. Switch to the advanced mode by toggling *Advanced* (material:toggle_on[role=skyBlue]) slider.
. Assign the rights for the respective area by ticking the check boxes indicated above. +
*_Note_*: You can either grant rights for complete areas or limit the rights you grant the user. To only grant limited rights in a certain area, expand the area.
. *Save* (material:save[]) the settings.

[TIP]
======
 The simple mode and advanced mode are linked. If you check menu visibilities in the simple mode the corresponding permissions in the advanced mode will be checked automatically. The connection only exists in this direction. If you check permissions in the advanced mode no menu or plugin visibilities will be checked automatically.
======

--

:!right-one:
:!right-two:
:!right-three:
:!right-four:
:!right-five:
:!right-six:
:!right-seven:
:!right-eight:
:!right-nine:
