////
zuletzt bearbeitet 30.07.2021
////

Items are managed centrally in plentymarkets.
In other words, you’ll enter your product information into plentymarkets.
Then you can sell your items on various <<markets#, markets>>, in your own <<online-store#, plentyShop>> and in your <<pos#, brick and mortar store>>.

If you need to make any changes in the future, e.g. edit an item's price or description, then you'll only have to modify this data centrally in plentymarkets.
The data can automatically be changed on all of your sales channels.

[#100]
== Introducing the item structure

Are you new to plentymarkets?
Before you start entering data, learn how items are structured!
The introduction teaches you about the topic and answers your basic questions:

* What’s the difference between xref:item:structure.adoc#[items and variations]?
* How does xref:item:inheritance.adoc#[inheritance] work?
* Where do I find my xref:item:search.adoc#100[items in the back end]?
* Can I also see a few xref:item:search.adoc#900[example items]?

[#200]
== Preparatory settings

//tag::preparatory-settings[]
Items are made up of lots of information, e.g. categories, prices and manufacturers.
But before you can sort an item into a specific category, the category first needs to exist in plentymarkets.
Before you can select an item’s manufacturer, the manufacturer data needs to exist in plentymarkets.
//end::preparatory-settings[]

Once you’ve saved such xref:item:settings.adoc#[preparatory settings] in plentymarkets, you’ll be able to apply them to all of the relevant items and variations.

include::page$structure.adoc[tag=system-settings-list]

[#300]
== Import, export and manual processing

//tag::import-export-create[]

////
Zukunftsmusik - irgendwann bei Gelegenheit den Artikel-Assistenten im Handbuch beschreiben - ab dem Zeitpunkt, den Bulletpoint auch einblenden - Link soll dann aber auf diese Seite sein und nicht die Assistenten-Übersicht.
////

Ready to start entering item data into plentymarkets?
Or do you want to send product information back and forth between your own plentymarkets system and other external systems?
There are several different tools available to you.
For example, item data records can be:

* xref:item:new-item.adoc#[manually created] in plentymarkets.
* managed in CSV files and then xref:item:import.adoc#[imported].
//* imported with the help of an xref:welcome:assistants.adoc#[assistant].
* imported from existing xref:markets:ebay-setup.adoc#11000[eBay listings].
* imported from other systems with the xref:data:rest-api.adoc#[REST-API].
* xref:item:export.adoc#[exported] out of your plentymarkets system.
//end::import-export-create[]

[#500]
== Use cases

//tag::use-cases[]
Do you have a particular scenario in mind?
In this chapter, you’ll learn how to:

//* Manage item data in multiple languages
* xref:item:combining-products.adoc#[Combine products] and sell them as a unit
* Sell xref:item:personalised-items.adoc#[personalised items] in your plentyShop
* xref:item:give-aways.adoc#[Add give-aways or promotional gifts] to an order
* Work with items that have xref:item:serial-numbers.adoc#[serial numbers or license keys]
* xref:item:changes.adoc#[Track changes to items], i.e. track the entire life cycle of an item
* Modify the xref:item:search-behaviour.adoc#[default item search behaviour] in the plentymarkets backend
//end::use-cases[]

[#400]
== Appearance in the plentyShop

//tag::appearance-webshop[]
Once you’ve saved your items in plentymarkets, you’re ready to start selling them.
plentymarkets comes with a free <<online-store#, online store>>, which you can use to sell your products.

Turn to this chapter for help if your items or categories aren't displayed in the plentyShop.
This chapter also shows you how to set up additional functions for displaying your items exactly how you want:

* xref:item:checklist-categories-visibility.adoc#[Category isn't visible in plentyShop]
* xref:item:checklist-items-visibility.adoc#[Item isn't visible in plentyShop]
* xref:item:search-bar.adoc#[Search bar]
* xref:item:frontend-item-search.adoc#[Search filters]
* xref:item:cross-selling.adoc#[Cross-selling]
* xref:item:store-specials.adoc#[Store specials]
//end::appearance-webshop[]
