Have you finished <<item/settings/properties#300, creating your characteristics>> and <<item/settings/properties#200, sorting them into groups>>? Then you’re ready to link your characteristics to items.

For example, if you created a characteristic called “Bluetooth”, then next you would specify which of your products are equipped with Bluetooth.

//tag::instruction[]
[.instruction]
Linking a characteristic with an item:

. Go to *Item » Edit item*.
. <<item/introduction/search#100, Search for>> and open the item.
. Click on the *Characteristics* tab. The screen is divided into two areas:

* Characteristics that have already been linked to the item are displayed in the upper area called *Characteristics*,
* Characteristics that have not yet been linked are displayed in the lower area called *Activate further characteristics*. Here, the characteristics are sorted into their groups.

. Expand the characteristic group in the lower area if needed (icon:plus-square-o[role="grey"]) and select the characteristic (icon:check-square[role="blue"]).
. *Save* (icon:save[set=plenty, role="green"]) the settings. +
→ The characteristic is now linked to the item and displayed in the upper area.
//end::instruction[]

[TIP]
.Linking a characteristic with multiple items
====
Use the <<item/import-export-create/create/mass-processing#200, item group function>> if you want to link several items at once.
====

[discrete]
==== Saving additional information

Depending on the scenario, it might be necessary to save additional information. For example, if the characteristic is something like a weight or a length, then it will be necessary to enter a numeric value.

. Carry out additional settings in the *Characteristics* tab. Note <<table-link-characteristic>>.
. *Save* (icon:save[set=plenty, role="green"]) the settings.

[[table-link-characteristic]]
.Information about the characteristic
[cols="1,3a"]
|====
|Setting |Explanation

| *Name*
|Here you’ll see the characteristic’s name and, if applicable, the group that it was sorted into.
This is purely informative and cannot be changed here.

| *Type*
|Here you’ll see the characteristic type.
This is purely informative and cannot be changed here.

*_Note_*: The characteristic type determines how you will interact with the *Default language* column and with the drop-down list of language abbreviations.

| *Default language*
|How you interact with this column depends on the characteristic type.

[cols="1,3a"]
!===
!Type !Interaction

!Blank
!No further action is necessary.

!Number +
Decimal number
!Enter the numerical value here, e.g. the weight or the length.

!Text
!Choose the appropriate language from the drop-down list in the next column. Enter the text in this language. Save the changes and repeat the process as needed for other languages.

!Selection
!Select the appropriate option.

!File
!Upload the appropriate file.

!(Order characteristic)
!Order characteristics allow your customers to personalise their items, e.g. by entering a text or a number, by selecting an option or by uploading a file.
Therefore, you - the seller - do not need to take any further action for this field. Rather, your customers will make an entry when purchasing the item in your plentyShop.
!===

| *Cross-selling*
|Select this option (icon:check-square[role="blue"]) to enable <<item/online-store/cross-selling#, cross-selling>> between this item and other items that have the same characteristic and value.

| *Surcharge*
|You might have already saved a surcharge <<item/settings/properties#300, while creating the characteristic>>.
But what should you do if not every item should be given the same surcharge?
Enter a different surcharge here. This will overwrite the surcharge that was saved for the characteristic as a whole.

*_Note_*: The entry field _only appears for order characteristics_.
|====

[TIP]
.Modifying the additional information for multiple items
====
Use the group function in the menu *Setup » Item » Characteristics » Tab: Group function* if you want to edit this information for several items at once.

. Select the characteristic's language.
. *Property selection*: Choose the characteristic that you want to edit.
. *Value to be changed*: Enter the old value for the characteristic.
. *New value*: Enter the new value for the characteristic.
. When you save the settings, the characteristic value will be changed for all of the items that have this value.
====
