The priority of a plugin set determines in which order the plugins of the plugin set are booted. You determine this priority by numbers, where 0 is the lowest value you can choose, meaning that plugins with 0 as priority are booted last.

Determining a set priority gets important if the plugins within the set are dependent on another. For example: the *Mirakle* plugin must be booted before the *Völkner/Conrad* plugin, thus the *Mirakl* plugin needs a lower priority. You can find which priority you need for which plugin in the plugin user guide.

[.instruction]
Proceed as follows to determine set priority:

. Go to *Plugins » Plugin set overview » [select Plugin set] » Set priorities*.
. Go to the line of the plugin that you want to change priority for and enter the column *Priority*.
. Enter the priority.
. *Save* (material:save[]) your settings.

[ATTENTION]
.Setting wrong priorities

====
Setting wrong plugin priorities that don't match the dependencies between the plugins, can lead to you being unable to login into your back end normally (in this case use the xref:welcome:login-tour.adoc#70[safe mode]). Wrong priorities can also effect your shop. For example if you use your own theme for the shop with the wrong priority, the theme won't load but rather the standard CSS theme.

So be careful when setting priorities and consider the user guide of the respective plugin.
====

[.collapseBox]
.I've set the wrong priorities and can't login to my system. What can I do?
--
Use the safe mode under https://plentymarkets-cloud-de.com/?safemode=1[] or https://plentymarkets-cloud-ie.com/?safemode=1[], to login into your system. Then adjust the plugin priorities and deploy the plugin set. After a successful deploy, you can login as usual into your system.
--