name: Docs health check

on:
  schedule:
  - cron: '0 6 * * 1'
  workflow_dispatch:

jobs:
  html-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Checkout UI repo
        uses: actions/checkout@v4
        with:
          repository: plentymarkets/plenty-docs-ui
          path: plenty-docs-ui-repo

      - name: Move I18N files
        run: |
          mkdir ./lang/
          mv ${GITHUB_WORKSPACE}/plenty-docs-ui-repo/src/lang/en-gb.json ./lang/en-gb.json
          mv ${GITHUB_WORKSPACE}/plenty-docs-ui-repo/src/lang/de-de.json ./lang/de-de.json

      # - name: Use htmltest
      #   run: curl https://htmltest.wjdp.uk | bash

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build site
        run: |
          npm install
          npm run prod
          
      - name: Assemble site
        run: |
          # Move index to build directory
          mv index.html ./build/index.html
          mv 404.html ./build/404.html
          mv sitemap.xml ./build/sitemap.xml

      # - name: Run htmltest
      #   run: bin/htmltest

      # - name: Upload test results as artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: health-check
      #     path: ./tmp/.htmltest/htmltest.log
      #     retention-days: 14

      - name: Upload build as artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: ./build
          retention-days: 7
