name: Docs health check

on:
  schedule:
  - cron: '0 6 * * 1'
  workflow_dispatch:

jobs:
  html-test:
    runs-on: ["self-hosted", "stable", "2xlarge", "spot"]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Checkout UI repo
        uses: actions/checkout@v3
        with:
          repository: plentymarkets/plenty-docs-ui
          path: plenty-docs-ui-repo

      - name: Move I18N files
        run: |
          mkdir ./lang/
          mv ${GITHUB_WORKSPACE}/plenty-docs-ui-repo/src/lang/en-gb.json ./lang/en-gb.json
          mv ${GITHUB_WORKSPACE}/plenty-docs-ui-repo/src/lang/de-de.json ./lang/de-de.json

      - name: Use htmltest
        run: curl https://htmltest.wjdp.uk | bash

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Build site
        run: |
          npm i -g @antora/cli@2.3 @antora/site-generator-default@2.3
          antora antora-playbook-de.yml --fetch --stacktrace
          antora antora-playbook-en.yml --fetch --stacktrace
          
      - name: Assemble site
        run: |
          # Move index to build directory
          mv index.html ./build/index.html
          mv 404.html ./build/404.html
          mv sitemap.xml ./build/sitemap.xml

      - name: Run htmltest
        run: bin/htmltest

      - name: Upload test results as artifact
        uses: actions/upload-artifact@v3
        with:
          name: health-check
          path: ./tmp/.htmltest/htmltest.log
          retention-days: 14

      - name: Create notification
        run: node ./.github/scripts/health-check.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUN_ID: ${{ github.run_id }}
