name: Trigger Memsource Webhook

on:
  push:
    branches: [ "main" ]
    paths:
      - 'docs/de-de/modules/daten/partials/**.adoc'

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger Webhook (Daten - Partials)
      run: curl -X POST https://cloud.memsource.com/web/api2/v1/automatedProjects/webhooks/vu0wpant8012T76i21XnYzF2LdKeHKvfI0R1zhHq652yIuXupI0oH1pr4pcV4kEfb2-emzNaAhkH07xcffShkvVXV5xEyr51UQ2kBMn5PkyEY0
