# Clone the UI repository from plenty-docs-ui.
# Make a copy of this file and place it in the root directory, plenty-manual-docs/
# Change USER in the url paths to your user name.
site:
  title: plentymarkets manual
  url: https://knowledge.plentymarkets.com/de-de
  lang: de-de
content:
  sources:
    - url: ./
      branches: HEAD
      start_path: docs/de-de
asciidoc:
  attributes:
    # Organisation
    copyright: © 2022 plentysystems AG
    orgname: plentysystems AG
    # General
    icons: font
    linkattrs:
    sectnums:
    numbered:
    xrefstyle: short
    source-highlighter: highlightjs
    example-caption!:
    stem: latexmath
    # Extensions
    tabs: tabs
    # L10N
    appendix-caption: Anhang
    caution-caption: Achtung
    chapter-label: Kapitel
    example-caption: Beispiel
    figure-caption: Bild
    important-caption: Wichtig
    last-update-label: Zuletzt aktualisiert
    listing-caption: Listing
    manname-title: BEZEICHNUNG
    note-caption: Anmerkung
    preface-title: Vorwort
    table-caption: Tabelle
    tip-caption: Hinweis
    toc-title: Inhalt
    untitled-label: Ohne Titel
    version-label: Version
    warning-caption: Warnung
  extensions:
  - ./lib/tabs-block.js
  - ./lib/inline-icon.js
output:
  dir: ./build/de-de
ui:
  bundle:
    url: /Users/USER/workspace/plenty-docs-ui/build/ui-bundle.zip
    snapshot: true
